gem5: base/addr_range.hh File Reference
addr_range.hh File Reference
#include <algorithm>
#include <list>
#include <vector>
#include "base/bitfield.hh"
#include "base/cprintf.hh"
#include "base/logging.hh"
#include "base/types.hh"
Classes
class AddrRange
The AddrRange class encapsulates an address range, and supports a number of tests to check if two ranges intersect, if a range contains a specific address etc.
Typedefs
typedef std::list< AddrRange > AddrRangeList
Convenience typedef for a collection of address ranges.
Functions
AddrRange RangeEx (Addr start, Addr end)
AddrRange RangeIn (Addr start, Addr end)
AddrRange RangeSize (Addr start, Addr size)
Typedef Documentation
AddrRangeList
typedef std::list<AddrRange> AddrRangeList
Convenience typedef for a collection of address ranges.
Definition at line 573 of file addr_range.hh.
Function Documentation
RangeEx()
AddrRange RangeEx (Addr start, Addr end) inline
Definition at line 576 of file addr_range.hh.
References AddrRange::AddrRange().
Referenced by X86ISA::Interrupts::getIntAddrRange(), init_range(), and TEST().
RangeIn()
AddrRange RangeIn (Addr start, Addr end) inline
Definition at line 580 of file addr_range.hh.
References AddrRange::AddrRange().
Referenced by init_range(), and TEST().
RangeSize()
AddrRange RangeSize (Addr start, Addr size) inline
Definition at line 584 of file addr_range.hh.
References AddrRange::AddrRange().
Referenced by AddrRangeMap< AbstractMemory *, 1 >::contains(), Packet::getAddrRange(), NoMaliGpu::getAddrRanges(), TsunamiPChip::getAddrRanges(), Uart8250::getAddrRanges(), Gicv2m::getAddrRanges(), Iob::getAddrRanges(), X86ISA::I8042::getAddrRanges(), GpuDispatcher::getAddrRanges(), Gicv3Its::getAddrRanges(), BasicPioDevice::getAddrRanges(), VGic::getAddrRanges(), PciDevice::getAddrRanges(), X86ISA::Interrupts::getAddrRanges(), GenericPciHost::getAddrRanges(), Pl111::getAddrRanges(), UFSHostDevice::getAddrRanges(), HDLcd::HDLcd(), Gicv3::init(), init_range(), and TEST().