gem5: mem/ruby/profiler/AddressProfiler.hh File Reference
AddressProfiler.hh File Reference
#include <iostream>
#include <unordered_map>
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Histogram.hh"
#include "mem/ruby/profiler/AccessTraceForAddress.hh"
#include "mem/ruby/profiler/Profiler.hh"
#include "mem/ruby/protocol/AccessType.hh"
#include "mem/ruby/protocol/RubyRequest.hh"
Classes
class AddressProfiler
Functions
AccessTraceForAddress & lookupTraceForAddress (Addr addr, AddressProfiler::AddressMap &record_map)
void printSorted (std::ostream &out, int num_of_sequencers, const AddressProfiler::AddressMap &record_map, std::string description, Profiler *profiler)
std::ostream & operator<< (std::ostream &out, const AddressProfiler &obj)
Function Documentation
lookupTraceForAddress()
AccessTraceForAddress& lookupTraceForAddress (Addr addr, AddressProfiler::AddressMap & record_map)
Definition at line 45 of file AddressProfiler.cc.
References ArmISA::i, MipsISA::r, and AccessTraceForAddress::setAddress().
Referenced by AddressProfiler::addTraceSample(), and AddressProfiler::profileRetry().
operator<<()
std::ostream& operator<< (std::ostream & out, const AddressProfiler & obj) inline
Definition at line 108 of file AddressProfiler.hh.
References AddressProfiler::print().
printSorted()
void printSorted (std::ostream & out, int num_of_sequencers, const AddressProfiler::AddressMap & record_map, std::string description, Profiler * profiler)