gem5: mem/ruby/common/Address.hh File Reference
Address.hh File Reference
#include <cassert>
#include <iomanip>
#include <iostream>
#include "base/types.hh"
Functions
Addr bitSelect (Addr addr, unsigned int small, unsigned int big)
Addr maskLowOrderBits (Addr addr, unsigned int number)
Addr getOffset (Addr addr)
Addr makeLineAddress (Addr addr)
Addr makeNextStrideAddress (Addr addr, int stride)
std::string printAddress (Addr addr)
Function Documentation
bitSelect()
Addr bitSelect (Addr addr, unsigned int small, unsigned int big)
Definition at line 35 of file Address.cc.
References addr.
Referenced by CheckTable::addCheck(), CacheMemory::addressToCacheSet(), getOffset(), and mapAddressToRange().
getOffset()
Addr getOffset (Addr addr)
Definition at line 48 of file Address.cc.
References bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by GPUCoalescer::atomicCallback(), Sequencer::hitCallback(), GPUCoalescer::hitCallback(), SubBlock::internalMergeFrom(), SubBlock::internalMergeTo(), Packet::isWholeLineWrite(), AbstractController::queueMemoryWritePartial(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvTimingReq(), Packet::setDataFromBlock(), MessageBuffer::stallMessage(), and Packet::writeDataToBlock().
makeLineAddress()
Addr makeLineAddress (Addr addr)
Definition at line 54 of file Address.cc.
References addr, and RubySystem::getBlockSizeBits().
Referenced by Prefetcher::accessNonunitFilter(), Prefetcher::accessUnitFilter(), CacheMemory::addressToCacheSet(), AddressProfiler::addTraceSample(), PerfectCacheMemory< ENTRY >::allocate(), CacheMemory::allocate(), GPUCoalescer::atomicCallback(), CacheMemory::cacheAvail(), CacheMemory::cacheProbe(), PerfectCacheMemory< ENTRY >::changePermission(), CacheMemory::clearLocked(), PersistentTable::countReadStarvingForAddress(), PersistentTable::countStarvingForAddress(), PerfectCacheMemory< ENTRY >::deallocate(), CacheMemory::deallocate(), PersistentTable::findSmallest(), CacheMemory::findTagInSet(), CacheMemory::findTagInSetIgnorePermissions(), RubySystem::functionalRead(), RubySystem::functionalWrite(), PerfectCacheMemory< ENTRY >::getPermission(), GPUCoalescer::getRequestStatus(), GPUCoalescer::hitCallback(), Prefetcher::initializeStream(), Sequencer::insertRequest(), GPUCoalescer::insertRequest(), PersistentTable::isLocked(), CacheMemory::isLocked(), TBETable< ENTRY >::isPresent(), DMASequencer::issueNext(), GPUCoalescer::issueRequest(), PerfectCacheMemory< ENTRY >::isTagPresent(), CacheMemory::isTagPresent(), PerfectCacheMemory< ENTRY >::lookup(), CacheMemory::lookup(), makeNextStrideAddress(), DMASequencer::makeRequest(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), PersistentTable::markEntries(), Prefetcher::observeMiss(), PersistentTable::okToIssueStarving(), Check::performCallback(), PersistentTable::persistentRequestLock(), PersistentTable::persistentRequestUnlock(), printAddress(), Sequencer::readCallback(), GPUCoalescer::readCallback(), RubyPort::MemSlavePort::recvFunctional(), GPUCoalescer::removeRequest(), RubyRequest::RubyRequest(), TimerTable::set(), CacheMemory::setLocked(), testAndRead(), testAndReadMask(), testAndWrite(), CacheMemory::testCacheAccess(), CacheMemory::tryCacheAccess(), PersistentTable::typeOfSmallest(), TimerTable::unset(), Sequencer::writeCallback(), and GPUCoalescer::writeCallback().
makeNextStrideAddress()
Addr makeNextStrideAddress (Addr addr, int stride)
Definition at line 61 of file Address.cc.
References RubySystem::getBlockSizeBytes(), makeLineAddress(), and ArmISA::stride.
Referenced by Prefetcher::accessUnitFilter(), Prefetcher::getPrefetchEntry(), Prefetcher::initializeStream(), and Prefetcher::issueNextPrefetch().
maskLowOrderBits()
Addr maskLowOrderBits (Addr addr, unsigned int number)
Definition at line 42 of file Address.cc.
References addr.
printAddress()
std::string printAddress (Addr addr)
Definition at line 67 of file Address.cc.
References makeLineAddress().
Referenced by Sequencer::issueRequest(), GPUCoalescer::issueRequest(), Sequencer::recordMissLatency(), and GPUCoalescer::recordMissLatency().