gem5: mem/ruby/profiler/AddressProfiler.cc File Reference
AddressProfiler.cc File Reference
#include "mem/ruby/profiler/AddressProfiler.hh"
#include <vector>
#include "base/bitfield.hh"
#include "base/stl_helpers.hh"
#include "mem/ruby/profiler/Profiler.hh"
#include "mem/ruby/protocol/RubyRequest.hh"
Typedefs
typedef AddressProfiler::AddressMap AddressMap
Functions
AccessTraceForAddress & lookupTraceForAddress (Addr addr, AddressMap &record_map)
void printSorted (ostream &out, int num_of_sequencers, const AddressMap &record_map, string description, Profiler *profiler)
Typedef Documentation
AddressMap
typedef AddressProfiler::AddressMap AddressMap
Definition at line 39 of file AddressProfiler.cc.
Function Documentation
lookupTraceForAddress()
AccessTraceForAddress& lookupTraceForAddress (Addr addr, AddressMap & record_map)
Definition at line 45 of file AddressProfiler.cc.
References ArmISA::i, MipsISA::r, and AccessTraceForAddress::setAddress().
Referenced by AddressProfiler::addTraceSample(), and AddressProfiler::profileRetry().
printSorted()
void printSorted (ostream & out, int num_of_sequencers, const AddressMap & record_map, string description, Profiler * profiler)
Definition at line 67 of file AddressProfiler.cc.
References Histogram::add(), Profiler::getAllInstructions(), AccessTraceForAddress::getTotal(), AccessTraceForAddress::getTouchedBy(), ArmISA::i, ArmISA::j, and AccessTraceForAddress::less_equal().
Referenced by AddressProfiler::printStats().