gem5: arch/x86/linux/process.cc File Reference
process.cc File Reference
#include "arch/x86/linux/process.hh"
#include <sys/syscall.h>
#include "arch/x86/isa_traits.hh"
#include "arch/x86/linux/linux.hh"
#include "arch/x86/registers.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/linux/linux.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
Classes
struct UserDesc64
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
static SyscallReturn archPrctlFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
BitUnion32 (UserDescFlags) Bitfield< 0 > seg_32bit
EndBitUnion (UserDescFlags) struct UserDesc32
static SyscallReturn setThreadArea32Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Variables
Bitfield< 2, 1 > contents
Bitfield< 3 > read_exec_only
Bitfield< 4 > limit_in_pages
Bitfield< 5 > seg_not_present
Bitfield< 6 > useable
static SyscallDesc syscallDescs64 []
static SyscallDesc syscallDescs32 []
Function Documentation
archPrctlFunc()
static SyscallReturn archPrctlFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 112 of file process.cc.
References addr, BitUnion32(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), MipsISA::index, X86ISA::MISCREG_FS_BASE, X86ISA::MISCREG_FS_EFF_BASE, X86ISA::MISCREG_GS_BASE, X86ISA::MISCREG_GS_EFF_BASE, MipsISA::p, ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscRegNoEffect(), and PortProxy::write().
BitUnion32()
BitUnion32 (UserDescFlags)
Referenced by archPrctlFunc(), and SparcISA::SparcStaticInst::passesCondition().
EndBitUnion()
EndBitUnion (UserDescFlags)
Definition at line 160 of file process.cc.
References X86ISA::limit.
Referenced by TEST_F().
setThreadArea32Func()
static SyscallReturn setThreadArea32Func (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 178 of file process.cc.
References bits(), X86ISA::X86Process::gdtSize(), X86ISA::X86Process::gdtStart(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::i, MipsISA::index, SyscallDesc::name(), and panic.
unameFunc()
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 94 of file process.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and name().
Variable Documentation
contents
Bitfield<2, 1> contents
Definition at line 155 of file process.cc.
limit_in_pages
Bitfield<4> limit_in_pages
Definition at line 157 of file process.cc.
read_exec_only
Bitfield<3> read_exec_only
Definition at line 156 of file process.cc.
seg_not_present
Bitfield<5> seg_not_present
Definition at line 158 of file process.cc.
syscallDescs32
SyscallDesc syscallDescs32[] static
Definition at line 593 of file process.cc.
syscallDescs64
SyscallDesc syscallDescs64[] static
Definition at line 260 of file process.cc.
useable
Bitfield<6> useable
Definition at line 159 of file process.cc.