gem5: arch/sparc/solaris/process.cc File Reference
process.cc File Reference
#include "arch/sparc/solaris/process.hh"
#include "arch/sparc/isa_traits.hh"
#include "arch/sparc/registers.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/solaris/solaris.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
Function Documentation
unameFunc()
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 75 of file process.cc.
References brkFunc(), chownFunc(), closeFunc(), exitFunc(), getgidFunc(), getpidFunc(), ThreadContext::getProcessPtr(), getuidFunc(), ThreadContext::getVirtProxy(), MipsISA::index, lseekFunc(), munmapFunc(), name(), pipePseudoFunc(), readlinkFunc(), setuidFunc(), umaskFunc(), unimplementedFunc(), and unlinkFunc().