gem5: arch/alpha/linux/process.cc File Reference
process.cc File Reference
#include "arch/alpha/linux/process.hh"
#include "arch/alpha/isa_traits.hh"
#include "arch/alpha/linux/linux.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "debug/SyscallVerbose.hh"
#include "kern/linux/linux.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
static SyscallReturn osf_getsysinfoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target osf_getsysyinfo() handler.
static SyscallReturn osf_setsysinfoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target osf_setsysinfo() handler.
Function Documentation
osf_getsysinfoFunc()
static SyscallReturn osf_getsysinfoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target osf_getsysyinfo() handler.
Even though this call is borrowed from Tru64, the subcases that get used appear to be different in practice from those used by Tru64 processes.
Definition at line 100 of file process.cc.
References BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and X86ISA::op.
Referenced by osf_setsysinfoFunc().
osf_setsysinfoFunc()
static SyscallReturn osf_setsysinfoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target osf_setsysinfo() handler.
Definition at line 129 of file process.cc.
References brkFunc(), chownFunc(), closeFunc(), BaseBufferArg::copyIn(), DPRINTFR, dupFunc(), exitFunc(), exitGroupFunc(), fchownFunc(), fcntlFunc(), ftruncateFunc(), getcwdFunc(), getgidPseudoFunc(), gethostnameFunc(), getpagesizeFunc(), getpidPseudoFunc(), ThreadContext::getProcessPtr(), getuidPseudoFunc(), ThreadContext::getVirtProxy(), ignoreFunc(), MipsISA::index, letoh(), lseekFunc(), mkdirFunc(), munmapFunc(), X86ISA::op, osf_getsysinfoFunc(), pipePseudoFunc(), readlinkFunc(), renameFunc(), setuidFunc(), truncateFunc(), umaskFunc(), unameFunc(), unimplementedFunc(), and unlinkFunc().
unameFunc()
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 80 of file process.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and name().
Referenced by osf_setsysinfoFunc().