gem5: arch/arm/linux/process.cc File Reference
process.cc File Reference
#include "arch/arm/linux/process.hh"
#include <sys/syscall.h>
#include "arch/arm/isa_traits.hh"
#include "arch/arm/linux/linux.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/linux/linux.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn unameFunc32 (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
static SyscallReturn unameFunc64 (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
static SyscallReturn setTLSFunc32 (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target set_tls() handler.
static SyscallReturn setTLSFunc64 (SyscallDesc *desc, int callnum, ThreadContext *tc)
Variables
static SyscallDesc syscallDescs32 []
static SyscallDesc syscallDescs64 []
static SyscallDesc privSyscallDescs32 []
static SyscallDesc privSyscallDescs64 []
Function Documentation
setTLSFunc32()
static SyscallReturn setTLSFunc32 (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target set_tls() handler.
Definition at line 144 of file process.cc.
References ArmLinuxProcess32::commPage, ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::MISCREG_TPIDRURO, ThreadContext::setMiscReg(), and PortProxy::writeBlob().
setTLSFunc64()
static SyscallReturn setTLSFunc64 (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 157 of file process.cc.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), MipsISA::index, ArmISA::MISCREG_TPIDRRO_EL0, and ThreadContext::setMiscReg().
unameFunc32()
static SyscallReturn unameFunc32 (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 108 of file process.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and name().
unameFunc64()
static SyscallReturn unameFunc64 (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 126 of file process.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and name().
Variable Documentation
privSyscallDescs32
SyscallDesc privSyscallDescs32[] static
Initial value:
= {
     SyscallDesc("breakpoint", unimplementedFunc),
     SyscallDesc("cacheflush", unimplementedFunc),
     SyscallDesc("usr26", unimplementedFunc),
     SyscallDesc("usr32", unimplementedFunc),
     SyscallDesc("set_tls", setTLSFunc32)
}
Definition at line 1635 of file process.cc.
Referenced by ArmLinuxProcess32::ArmLinuxProcess32().
privSyscallDescs64
SyscallDesc privSyscallDescs64[] static
Initial value:
= {
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("cacheflush", unimplementedFunc),
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("unallocated", unimplementedFunc),
     SyscallDesc("set_tls", setTLSFunc64)
}
Definition at line 1644 of file process.cc.
Referenced by ArmLinuxProcess64::ArmLinuxProcess64().
syscallDescs32
SyscallDesc syscallDescs32[] static
Definition at line 167 of file process.cc.
Referenced by ArmLinuxProcess32::ArmLinuxProcess32().
syscallDescs64
SyscallDesc syscallDescs64[] static
Definition at line 544 of file process.cc.
Referenced by ArmLinuxProcess64::ArmLinuxProcess64().