gem5: arch/x86/types.cc File Reference
types.cc File Reference
#include "arch/x86/types.hh"
#include "sim/serialize.hh"
Functions
template<>
void paramOut (CheckpointOut &cp, const string &name, ExtMachInst const &machInst)
template<>
void paramIn (CheckpointIn &cp, const string &name, ExtMachInst &machInst)
Function Documentation
paramIn()
template<> void paramIn (CheckpointIn & cp, const string & name, ExtMachInst & machInst)
Definition at line 71 of file types.cc.
References X86ISA::ExtMachInst::addrSize, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, X86ISA::ExtMachInst::immediate, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::modRM, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::stackSize, X86ISA::ExtMachInst::type, and X86ISA::ExtMachInst::vex.
Referenced by ArmSemihosting::FileBase::create(), AnnotateDumpCallback::process(), Pl011::unserialize(), FlashDevice::unserialize(), PacketFifoEntry::unserialize(), SymbolTable::unserialize(), ArmSemihosting::unserialize(), EthPacketData::unserialize(), Globals::unserialize(), MemState::unserialize(), ArmISA::PMU::unserialize(), EtherLink::Link::unserialize(), CopyEngineReg::Regs::unserialize(), Pl050::unserialize(), Iob::unserialize(), IdeController::unserialize(), EmulationPageTable::unserialize(), ArchTimer::unserialize(), MC146818::unserialize(), SparcISA::TLB::unserialize(), Intel8254Timer::Counter::unserialize(), Time::unserialize(), VGic::unserialize(), PacketFifo::unserialize(), CopyEngineReg::ChanRegs::unserialize(), PciDevice::unserialize(), MultiLevelPageTable< EntryTypes >::unserialize(), Sinic::Device::unserialize(), VirtQueue::unserialize(), ArmISA::TlbEntry::unserialize(), and iGbReg::Regs::unserialize().
paramOut()
template<> void paramOut (CheckpointOut & cp, const string & name, ExtMachInst const & machInst)
Definition at line 40 of file types.cc.
References X86ISA::ExtMachInst::addrSize, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, X86ISA::ExtMachInst::immediate, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::modRM, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::stackSize, X86ISA::ExtMachInst::type, and X86ISA::ExtMachInst::vex.
Referenced by AnnotateDumpCallback::process(), Pl011::serialize(), FlashDevice::serialize(), PacketFifoEntry::serialize(), SymbolTable::serialize(), ArmSemihosting::serialize(), EthPacketData::serialize(), Globals::serialize(), MemState::serialize(), Random::serialize(), EtherLink::Link::serialize(), CopyEngineReg::Regs::serialize(), ArmSemihosting::FileBase::serialize(), Pl050::serialize(), Ticked::serialize(), Iob::serialize(), IdeController::serialize(), EmulationPageTable::serialize(), MC146818::serialize(), ArchTimer::serialize(), Intel8254Timer::Counter::serialize(), Time::serialize(), CopyEngineReg::ChanRegs::serialize(), VGic::serialize(), PacketFifo::serialize(), GenericTimer::serialize(), PciDevice::serialize(), MultiLevelPageTable< EntryTypes >::serialize(), Sinic::Device::serialize(), ArmISA::TlbEntry::serialize(), GenericTimerMem::serialize(), and iGbReg::Regs::serialize().