gem5: base/time.hh File Reference
time.hh File Reference
#include <sys/time.h>
#include <inttypes.h>
#include <cmath>
#include <cstring>
#include <ctime>
#include <iosfwd>
#include <iostream>
#include <string>
#include "base/types.hh"
#include "sim/serialize.hh"
Classes
class Time
Functions
void sleep (const Time &time)
bool operator== (const Time &l, const Time &r)
bool operator!= (const Time &l, const Time &r)
bool operator< (const Time &l, const Time &r)
bool operator<= (const Time &l, const Time &r)
bool operator> (const Time &l, const Time &r)
bool operator>= (const Time &l, const Time &r)
Time operator+ (const Time &l, const Time &r)
Time operator- (const Time &l, const Time &r)
std::ostream & operator<< (std::ostream &out, const Time &time)
time_t mkutctime (struct tm *time)
Function Documentation
mkutctime()
time_t mkutctime (struct tm * time)
Definition at line 155 of file time.cc.
References fatal, and ArmISA::tz.
Referenced by ArmSemihosting::ArmSemihosting(), DumbTOD::DumbTOD(), operator<<(), and MC146818::tickClock().
operator!=()
bool operator!= (const Time & l, const Time & r) inline
Definition at line 213 of file time.hh.
References Time::nsec(), and Time::sec().
operator+()
Time operator+ (const Time & l, const Time & r) inline
Definition at line 247 of file time.hh.
References MipsISA::r, and Time::time().
operator-()
Time operator- (const Time & l, const Time & r) inline
Definition at line 255 of file time.hh.
References MipsISA::r, and Time::time().
operator<()
bool operator< (const Time & l, const Time & r) inline
Definition at line 219 of file time.hh.
References Time::nsec(), and Time::sec().
Referenced by MultiperspectivePerceptron::findBest(), and sc_core::sc_process_handle::operator=().
operator<<()
std::ostream& operator<< (std::ostream & out, const Time & time) inline
Definition at line 263 of file time.hh.
References Time::date(), and mkutctime().
operator<=()
bool operator<= (const Time & l, const Time & r) inline
Definition at line 226 of file time.hh.
References Time::nsec(), and Time::sec().
operator==()
bool operator== (const Time & l, const Time & r) inline
Definition at line 207 of file time.hh.
References Time::nsec(), and Time::sec().
operator>()
bool operator> (const Time & l, const Time & r) inline
Definition at line 233 of file time.hh.
References Time::nsec(), and Time::sec().
operator>=()
bool operator>= (const Time & l, const Time & r) inline
Definition at line 240 of file time.hh.
References Time::nsec(), and Time::sec().
sleep()
void sleep (const Time & time)
Definition at line 143 of file time.cc.
References ArmISA::ts.
Referenced by Time::operator-=(), and Root::timeSync().