gem5: base/bitfield.test.cc File Reference
bitfield.test.cc File Reference
#include <gtest/gtest.h>
#include "base/bitfield.hh"
Functions
TEST (BitfieldTest, Mask0Bits)
TEST (BitfieldTest, Mask1Bit)
TEST (BitfieldTest, Mask8Bits)
TEST (BitfieldTest, Mask16Bits)
TEST (BitfieldTest, Mask32Bits)
TEST (BitfieldTest, MaskAllBits)
TEST (BitfieldTest, MaskAllBitsGreaterThan64)
TEST (BitfieldTest, MaskOneBit)
TEST (BitfieldTest, MaskTwoBits)
TEST (BitfieldTest, MaskThreeBits)
TEST (BitfieldTest, MaskEntireRange)
TEST (BitfieldTest, MaskOutsideOfRange)
TEST (BitfieldTest, ExtractOneBit)
TEST (BitfieldTest, Extract63rdBit)
TEST (BitfieldTest, ExtractFirstBit)
TEST (BitfieldTest, ExtractFirstBitFirstBitZero)
TEST (BitfieldTest, ExtractThreeBits)
TEST (BitfieldTest, MbitsStandardCase)
TEST (BitfieldTest, MbitsEntireRange)
TEST (BitfieldTest, SignExtendPositiveInput)
TEST (BitfieldTest, SignExtendNegativeInput)
TEST (BitfieldTest, SignExtendPositiveInputOutsideRange)
TEST (BitfieldTest, SignExtendNegativeInputOutsideRange)
TEST (BitfieldTest, InsertOneBitTo3)
TEST (BitfieldTest, InsertOneBitTo18)
TEST (BitfieldTest, InsertOneBitTo3LsbZero)
TEST (BitfieldTest, InsertOneBitTo18LsbZero)
TEST (BitfieldTest, InsertOnBitTo8LsbZero)
TEST (BitfieldTest, InsertMultipleBits)
TEST (BitfieldTest, InsertMultipleBitsOverwrite)
TEST (BitfieldTest, ReverseBits8Bit)
TEST (BitfieldTest, ReverseBits64Bit)
TEST (BitfieldTest, FindMsb29)
TEST (BitfieldTest, FindMsb63)
TEST (BitfieldTest, FindMsbZero)
TEST (BitfieldTest, FindLsb)
TEST (BitfieldTest, FindLsbZero)
TEST (BitfieldTest, IsPow2)
TEST (BitfieldTest, IsNotPow2)
TEST (BitfieldTest, IsPow2Zero)
TEST (BitfieldTest, PopCountNoBits)
TEST (BitfieldTest, PopCountOneBit)
TEST (BitfieldTest, PopCountManyBits)
TEST (BitfieldTest, PopCountAllOnes)
TEST (BitfieldTest, AlignToPowerOfTwo0)
TEST (BitfieldTest, AlignToPowerOfTwo3)
TEST (BitfieldTest, AlignToPowerOfTwo5)
TEST (BitfieldTest, AlignToPowerOfTwo10)
TEST (BitfieldTest, AlignToPowerOfTwo16)
TEST (BitfieldTest, AlignToPowerOfTwo31)
TEST (BitfieldTest, CountTrailingZeros32BitsNoTrailing)
TEST (BitfieldTest, CountTrailingZeros32Bits)
TEST (BitfieldTest, CountTrailingZeros64BitsNoTrailing)
TEST (BitfieldTest, CountTrailingZeros64Bits)
TEST (BitfieldTest, CountTrailingZero64AllZeros)
Function Documentation
TEST() [1/55]
TEST (BitfieldTest , Mask0Bits)
Definition at line 48 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [2/55]
TEST (BitfieldTest , Mask1Bit)
Definition at line 53 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [3/55]
TEST (BitfieldTest , Mask8Bits)
Definition at line 58 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [4/55]
TEST (BitfieldTest , Mask16Bits)
Definition at line 63 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [5/55]
TEST (BitfieldTest , Mask32Bits)
Definition at line 68 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [6/55]
TEST (BitfieldTest , MaskAllBits)
Definition at line 73 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [7/55]
TEST (BitfieldTest , MaskAllBitsGreaterThan64)
Definition at line 78 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [8/55]
TEST (BitfieldTest , MaskOneBit)
Definition at line 90 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [9/55]
TEST (BitfieldTest , MaskTwoBits)
Definition at line 95 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [10/55]
TEST (BitfieldTest , MaskThreeBits)
Definition at line 100 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [11/55]
TEST (BitfieldTest , MaskEntireRange)
Definition at line 105 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [12/55]
TEST (BitfieldTest , MaskOutsideOfRange)
Definition at line 110 of file bitfield.test.cc.
References EXPECT_EQ, and ArmISA::mask.
TEST() [13/55]
TEST (BitfieldTest , ExtractOneBit)
Definition at line 120 of file bitfield.test.cc.
References bits(), EXPECT_EQ, and X86ISA::x.
TEST() [14/55]
TEST (BitfieldTest , Extract63rdBit)
Definition at line 126 of file bitfield.test.cc.
References bits(), EXPECT_EQ, ULL, and X86ISA::x.
TEST() [15/55]
TEST (BitfieldTest , ExtractFirstBit)
Definition at line 132 of file bitfield.test.cc.
References bits(), EXPECT_EQ, and X86ISA::x.
TEST() [16/55]
TEST (BitfieldTest , ExtractFirstBitFirstBitZero)
Definition at line 138 of file bitfield.test.cc.
References bits(), EXPECT_EQ, and X86ISA::x.
TEST() [17/55]
TEST (BitfieldTest , ExtractThreeBits)
Definition at line 144 of file bitfield.test.cc.
References bits(), EXPECT_EQ, and X86ISA::x.
TEST() [18/55]
TEST (BitfieldTest , MbitsStandardCase)
Definition at line 155 of file bitfield.test.cc.
References EXPECT_EQ, mbits(), and X86ISA::x.
TEST() [19/55]
TEST (BitfieldTest , MbitsEntireRange)
Definition at line 161 of file bitfield.test.cc.
References EXPECT_EQ, mbits(), ULL, and X86ISA::x.
TEST() [20/55]
TEST (BitfieldTest , SignExtendPositiveInput)
Definition at line 171 of file bitfield.test.cc.
References EXPECT_EQ, output(), and X86ISA::val.
TEST() [21/55]
TEST (BitfieldTest , SignExtendNegativeInput)
Definition at line 178 of file bitfield.test.cc.
References EXPECT_EQ, output(), and X86ISA::val.
TEST() [22/55]
TEST (BitfieldTest , SignExtendPositiveInputOutsideRange)
Definition at line 185 of file bitfield.test.cc.
References EXPECT_EQ.
TEST() [23/55]
TEST (BitfieldTest , SignExtendNegativeInputOutsideRange)
Definition at line 190 of file bitfield.test.cc.
References EXPECT_EQ, output(), and X86ISA::val.
TEST() [24/55]
TEST (BitfieldTest , InsertOneBitTo3)
Definition at line 201 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [25/55]
TEST (BitfieldTest , InsertOneBitTo18)
Definition at line 208 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [26/55]
TEST (BitfieldTest , InsertOneBitTo3LsbZero)
Definition at line 215 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [27/55]
TEST (BitfieldTest , InsertOneBitTo18LsbZero)
Definition at line 222 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [28/55]
TEST (BitfieldTest , InsertOnBitTo8LsbZero)
Definition at line 229 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [29/55]
TEST (BitfieldTest , InsertMultipleBits)
Definition at line 236 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), ULL, and X86ISA::val.
TEST() [30/55]
TEST (BitfieldTest , InsertMultipleBitsOverwrite)
Definition at line 243 of file bitfield.test.cc.
References bits(), EXPECT_EQ, insertBits(), and X86ISA::val.
TEST() [31/55]
TEST (BitfieldTest , ReverseBits8Bit)
Definition at line 251 of file bitfield.test.cc.
References EXPECT_EQ, and reverseBits().
TEST() [32/55]
TEST (BitfieldTest , ReverseBits64Bit)
Definition at line 257 of file bitfield.test.cc.
References EXPECT_EQ, and reverseBits().
TEST() [33/55]
TEST (BitfieldTest , FindMsb29)
Definition at line 266 of file bitfield.test.cc.
References EXPECT_EQ, findMsbSet(), and X86ISA::val.
TEST() [34/55]
TEST (BitfieldTest , FindMsb63)
Definition at line 272 of file bitfield.test.cc.
References EXPECT_EQ, findMsbSet(), ULL, and X86ISA::val.
TEST() [35/55]
TEST (BitfieldTest , FindMsbZero)
Definition at line 279 of file bitfield.test.cc.
References EXPECT_EQ, and findMsbSet().
TEST() [36/55]
TEST (BitfieldTest , FindLsb)
Definition at line 284 of file bitfield.test.cc.
References EXPECT_EQ, findLsbSet(), ULL, and X86ISA::val.
TEST() [37/55]
TEST (BitfieldTest , FindLsbZero)
Definition at line 290 of file bitfield.test.cc.
References EXPECT_EQ, and findLsbSet().
TEST() [38/55]
TEST (BitfieldTest , IsPow2)
Definition at line 298 of file bitfield.test.cc.
References EXPECT_TRUE, and isPow2().
TEST() [39/55]
TEST (BitfieldTest , IsNotPow2)
Definition at line 303 of file bitfield.test.cc.
References EXPECT_FALSE, and isPow2().
TEST() [40/55]
TEST (BitfieldTest , IsPow2Zero)
Definition at line 308 of file bitfield.test.cc.
References EXPECT_TRUE, and isPow2().
TEST() [41/55]
TEST (BitfieldTest , PopCountNoBits)
Definition at line 317 of file bitfield.test.cc.
References EXPECT_EQ, and popCount().
TEST() [42/55]
TEST (BitfieldTest , PopCountOneBit)
Definition at line 322 of file bitfield.test.cc.
References EXPECT_EQ, popCount(), and X86ISA::val.
TEST() [43/55]
TEST (BitfieldTest , PopCountManyBits)
Definition at line 328 of file bitfield.test.cc.
References EXPECT_EQ, popCount(), and X86ISA::val.
TEST() [44/55]
TEST (BitfieldTest , PopCountAllOnes)
Definition at line 334 of file bitfield.test.cc.
References EXPECT_EQ, popCount(), and X86ISA::val.
TEST() [45/55]
TEST (BitfieldTest , AlignToPowerOfTwo0)
Definition at line 345 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [46/55]
TEST (BitfieldTest , AlignToPowerOfTwo3)
Definition at line 350 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [47/55]
TEST (BitfieldTest , AlignToPowerOfTwo5)
Definition at line 355 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [48/55]
TEST (BitfieldTest , AlignToPowerOfTwo10)
Definition at line 360 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [49/55]
TEST (BitfieldTest , AlignToPowerOfTwo16)
Definition at line 365 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [50/55]
TEST (BitfieldTest , AlignToPowerOfTwo31)
Definition at line 370 of file bitfield.test.cc.
References alignToPowerOfTwo(), and EXPECT_EQ.
TEST() [51/55]
TEST (BitfieldTest , CountTrailingZeros32BitsNoTrailing)
Definition at line 381 of file bitfield.test.cc.
References ctz32(), and EXPECT_EQ.
TEST() [52/55]
TEST (BitfieldTest , CountTrailingZeros32Bits)
Definition at line 387 of file bitfield.test.cc.
References ctz32(), and EXPECT_EQ.
TEST() [53/55]
TEST (BitfieldTest , CountTrailingZeros64BitsNoTrailing)
Definition at line 393 of file bitfield.test.cc.
References ctz64(), and EXPECT_EQ.
TEST() [54/55]
TEST (BitfieldTest , CountTrailingZeros64Bits)
Definition at line 399 of file bitfield.test.cc.
References ctz64(), EXPECT_EQ, and ULL.
TEST() [55/55]
TEST (BitfieldTest , CountTrailingZero64AllZeros)
Definition at line 405 of file bitfield.test.cc.
References ctz64(), and EXPECT_EQ.