gem5: base/channel_addr.test.cc File Reference
channel_addr.test.cc File Reference
#include <gtest/gtest.h>
#include "base/channel_addr.hh"
Functions
TEST (ChannelAddrRange, DefaultInvalid)
TEST (ChannelAddrRange, Range)
Function Documentation
TEST() [1/2]
TEST (ChannelAddrRange , DefaultInvalid)
Definition at line 45 of file channel_addr.test.cc.
References EXPECT_FALSE, and ChannelAddrRange::valid().
TEST() [2/2]
TEST (ChannelAddrRange , Range)
Definition at line 53 of file channel_addr.test.cc.
References ChannelAddrRange::contains(), ChannelAddrRange::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChannelAddrRange::size(), and ChannelAddrRange::start().