gem5: base/chunk_generator.test.cc File Reference
chunk_generator.test.cc File Reference
#include <gtest/gtest.h>
#include "chunk_generator.hh"
Functions
TEST (ChunkGeneratorTest, StartingConditions)
TEST (ChunkGeneratorTest, AdvanceToNextChunk)
TEST (ChunkGeneratorTest, AdvanceToLastChunk)
TEST (ChunkGeneratorTest, AdvanceToTheEnd)
TEST (ChunkGeneratorTest, SmallerLastChunk)
TEST (ChunkGeneratorTest, ChunkSizeGreaterThanTotalSize)
TEST (ChunkGeneratorTest, ChunkSizeZero)
TEST (ChunkGeneratorTest, StartAtNonZero)
Function Documentation
TEST() [1/8]
TEST (ChunkGeneratorTest , StartingConditions)
Definition at line 39 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, ChunkGenerator::last(), and ChunkGenerator::size().
TEST() [2/8]
TEST (ChunkGeneratorTest , AdvanceToNextChunk)
Definition at line 52 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [3/8]
TEST (ChunkGeneratorTest , AdvanceToLastChunk)
Definition at line 67 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [4/8]
TEST (ChunkGeneratorTest , AdvanceToTheEnd)
Definition at line 86 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [5/8]
TEST (ChunkGeneratorTest , SmallerLastChunk)
Definition at line 113 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [6/8]
TEST (ChunkGeneratorTest , ChunkSizeGreaterThanTotalSize)
Definition at line 131 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [7/8]
TEST (ChunkGeneratorTest , ChunkSizeZero)
Definition at line 154 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().
TEST() [8/8]
TEST (ChunkGeneratorTest , StartAtNonZero)
Definition at line 175 of file chunk_generator.test.cc.
References ChunkGenerator::addr(), ChunkGenerator::complete(), ChunkGenerator::done(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, ChunkGenerator::last(), ChunkGenerator::next(), and ChunkGenerator::size().