gem5: sc_core::sc_signal_resolved Class Reference
sc_core::sc_signal_resolved Class Reference
#include <sc_signal_resolved.hh>
Public Member Functions
sc_signal_resolved ()
sc_signal_resolved (const char *name)
virtual ~sc_signal_resolved ()
virtual void register_port (sc_port_base &, const char *)
virtual void write (const sc_dt::sc_logic &)
sc_signal_resolved & operator= (const sc_dt::sc_logic &)
sc_signal_resolved & operator= (const sc_signal_resolved &)
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_signal< sc_dt::sc_logic, SC_MANY_WRITERS >
sc_signal ()
sc_signal (const char *name)
sc_signal (const char *name, const sc_dt::sc_logic &initial_value)
virtual ~sc_signal ()
sc_signal< sc_dt::sc_logic, WRITER_POLICY > & operator= (const sc_dt::sc_logic &t)
sc_signal< sc_dt::sc_logic, WRITER_POLICY > & operator= (const sc_signal< sc_dt::sc_logic, WRITER_POLICY > &s)
Public Member Functions inherited from sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >
ScSignalBaseT (const char *_name)
ScSignalBaseT (const char *_name, const sc_dt::sc_logic &initial_value)
virtual ~ScSignalBaseT ()
virtual const sc_dt::sc_logic & read () const
operator const sc_dt::sc_logic & () const
virtual const sc_core::sc_event & default_event () const
virtual const sc_core::sc_event & value_changed_event () const
virtual void print (std::ostream &os=std::cout) const
virtual void dump (std::ostream &os=std::cout) const
virtual bool event () const
virtual sc_core::sc_writer_policy get_writer_policy () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_core::sc_signal_in_if< sc_dt::sc_logic >
virtual const sc_event & posedge_event () const =0
virtual const sc_event & negedge_event () const =0
virtual bool posedge () const =0
virtual bool negedge () const =0
Public Member Functions inherited from sc_core::sc_interface
virtual ~sc_interface ()
Protected Member Functions
virtual void update ()
Protected Member Functions inherited from sc_gem5::ScSignalBasePicker< sc_dt::sc_logic >
ScSignalBasePicker (const char *_name)
Protected Member Functions inherited from sc_gem5::ScSignalBaseBinary
ScSignalBaseBinary (const char *_name)
void _signalReset (sc_gem5::Reset *reset)
void _signalReset ()
const sc_core::sc_event & posedgeEvent () const
const sc_core::sc_event & negedgeEvent () const
bool posedge () const
bool negedge () const
void _signalPosedge ()
void _signalNegedge ()
Protected Member Functions inherited from sc_gem5::ScSignalBase
ScSignalBase (const char *_name)
virtual ~ScSignalBase ()
const sc_core::sc_event & defaultEvent () const
const sc_core::sc_event & valueChangedEvent () const
bool event () const
void _signalChange ()
Protected Member Functions inherited from sc_core::sc_prim_channel
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from sc_core::sc_signal_inout_if< sc_dt::sc_logic >
sc_signal_inout_if ()
Protected Member Functions inherited from sc_core::sc_signal_in_if< sc_dt::sc_logic >
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_signal_write_if< sc_dt::sc_logic >
sc_signal_write_if ()
Private Member Functions
sc_signal_resolved (const sc_signal_resolved &)
Private Attributes
std::map<::sc_gem5::Process *, sc_dt::sc_logic > inputs
Additional Inherited Members
Protected Attributes inherited from sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >
sc_dt::sc_logic m_cur_val
sc_dt::sc_logic m_new_val
WriteChecker< WRITER_POLICY > _checker
Protected Attributes inherited from sc_gem5::ScSignalBaseBinary
std::vector< sc_gem5::Reset * > _resets
InternalScEvent _posedgeEvent
InternalScEvent _negedgeEvent
uint64_t _posStamp
uint64_t _negStamp
Protected Attributes inherited from sc_gem5::ScSignalBase
InternalScEvent _valueChangedEvent
uint64_t _changeStamp
sc_core::sc_port_base * _gem5WriterPort
Detailed Description
Definition at line 57 of file sc_signal_resolved.hh.
Constructor & Destructor Documentation
sc_signal_resolved() [1/3]
sc_core::sc_signal_resolved::sc_signal_resolved ()
Definition at line 38 of file sc_signal_resolved.cc.
sc_signal_resolved() [2/3]
sc_core::sc_signal_resolved::sc_signal_resolved (const char * name) explicit
Definition at line 43 of file sc_signal_resolved.cc.
~sc_signal_resolved()
sc_core::sc_signal_resolved::~sc_signal_resolved () virtual
Definition at line 47 of file sc_signal_resolved.cc.
sc_signal_resolved() [3/3]
sc_core::sc_signal_resolved::sc_signal_resolved (const sc_signal_resolved &) inline private
Definition at line 77 of file sc_signal_resolved.hh.
Member Function Documentation
kind()
virtual const char* sc_core::sc_signal_resolved::kind () const inline virtual
Reimplemented from sc_gem5::ScSignalBase.
Definition at line 70 of file sc_signal_resolved.hh.
operator=() [1/2]
sc_signal_resolved & sc_core::sc_signal_resolved::operator= (const sc_dt::sc_logic & l)
Definition at line 66 of file sc_signal_resolved.cc.
References write().
operator=() [2/2]
sc_signal_resolved & sc_core::sc_signal_resolved::operator= (const sc_signal_resolved & r)
Definition at line 73 of file sc_signal_resolved.cc.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::read(), and write().
register_port()
void sc_core::sc_signal_resolved::register_port (sc_port_base & , const char *) virtual
Reimplemented from sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
Definition at line 48 of file sc_signal_resolved.cc.
update()
void sc_core::sc_signal_resolved::update () protected virtual
Reimplemented from sc_core::sc_signal< sc_dt::sc_logic, SC_MANY_WRITERS >.
Definition at line 80 of file sc_signal_resolved.cc.
References inputs, sc_dt::Log_0, sc_dt::Log_1, sc_dt::Log_X, sc_dt::Log_Z, sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >::m_new_val, sc_core::sc_signal< T, WRITER_POLICY >::update(), and sc_dt::sc_logic::value().
write()
void sc_core::sc_signal_resolved::write (const sc_dt::sc_logic & l) virtual
Reimplemented from sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
Definition at line 51 of file sc_signal_resolved.cc.
References sc_gem5::Scheduler::current(), inputs, MipsISA::l, MipsISA::p, sc_core::sc_prim_channel::request_update(), and sc_gem5::scheduler.
Referenced by operator=().
Member Data Documentation
inputs
std::map<::sc_gem5::Process *, sc_dt::sc_logic> sc_core::sc_signal_resolved::inputs private
Definition at line 81 of file sc_signal_resolved.hh.
Referenced by update(), and write().
The documentation for this class was generated from the following files:
systemc/ext/channel/sc_signal_resolved.hh
systemc/channel/sc_signal_resolved.cc