gem5: IntSourcePinBase Class Reference
IntSourcePinBase Class Reference
#include <intpin.hh>
Public Member Functions
IntSourcePinBase (const std::string &_name, PortID _id, bool def_state)
void raise ()
void lower ()
void bind (Port &peer) override
Attach to a peer port.
void unbind () override
Dettach from a peer port.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Private Attributes
IntSinkPinBase * sink = nullptr
bool _state = false
Additional Inherited Members
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Definition at line 92 of file intpin.hh.
Constructor & Destructor Documentation
IntSourcePinBase()
IntSourcePinBase::IntSourcePinBase (const std::string & _name, PortID _id, bool def_state) inline
Definition at line 99 of file intpin.hh.
Member Function Documentation
bind()
void IntSourcePinBase::bind (Port & peer) override virtual
Attach to a peer port.
Reimplemented from Port.
Definition at line 51 of file intpin.cc.
References IntSinkPinBase::_state, Port::bind(), fatal_if, IntSinkPinBase::lower(), and Port::name().
lower()
void IntSourcePinBase::lower () inline
Definition at line 104 of file intpin.hh.
References IntSinkPinBase::bind(), IntSinkPinBase::lower(), and IntSinkPinBase::unbind().
raise()
void IntSourcePinBase::raise () inline
Definition at line 103 of file intpin.hh.
References IntSinkPinBase::raise().
unbind()
void IntSourcePinBase::unbind () override virtual
Dettach from a peer port.
Reimplemented from Port.
Definition at line 65 of file intpin.cc.
References Port::unbind().
Member Data Documentation
_state
bool IntSourcePinBase::_state = false private
Definition at line 96 of file intpin.hh.
sink
IntSinkPinBase* IntSourcePinBase::sink = nullptr private
Definition at line 95 of file intpin.hh.
The documentation for this class was generated from the following files:
dev/intpin.hh
dev/intpin.cc