gem5: Sequencer Class Reference
Sequencer Class Reference
#include <Sequencer.hh>
Public Types
typedef RubySequencerParams Params
Public Types inherited from RubyPort
typedef RubyPortParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Sequencer (const Params *)
~Sequencer ()
void wakeup ()
void resetStats ()
Callback to reset stats.
void collateStats ()
void regStats ()
Callback to set stat parameters.
void writeCallback (Addr address, DataBlock &data, const bool externalHit=false, const MachineType mach=MachineType_NUM, const Cycles initialRequestTime=Cycles(0), const Cycles forwardRequestTime=Cycles(0), const Cycles firstResponseTime=Cycles(0))
void readCallback (Addr address, DataBlock &data, const bool externalHit=false, const MachineType mach=MachineType_NUM, const Cycles initialRequestTime=Cycles(0), const Cycles forwardRequestTime=Cycles(0), const Cycles firstResponseTime=Cycles(0))
RequestStatus makeRequest (PacketPtr pkt)
bool empty () const
int outstandingCount () const
bool isDeadlockEventScheduled () const
void descheduleDeadlockEvent ()
void print (std::ostream &out) const
void checkCoherence (Addr address)
void markRemoved ()
void evictionCallback (Addr address)
void invalidateSC (Addr address)
int coreId () const
void recordRequestType (SequencerRequestType requestType)
Stats::Histogram & getOutstandReqHist ()
Stats::Histogram & getLatencyHist ()
Stats::Histogram & getTypeLatencyHist (uint32_t t)
Stats::Histogram & getHitLatencyHist ()
Stats::Histogram & getHitTypeLatencyHist (uint32_t t)
Stats::Histogram & getHitMachLatencyHist (uint32_t t)
Stats::Histogram & getHitTypeMachLatencyHist (uint32_t r, uint32_t t)
Stats::Histogram & getMissLatencyHist ()
Stats::Histogram & getMissTypeLatencyHist (uint32_t t)
Stats::Histogram & getMissMachLatencyHist (uint32_t t) const
Stats::Histogram & getMissTypeMachLatencyHist (uint32_t r, uint32_t t) const
Stats::Histogram & getIssueToInitialDelayHist (uint32_t t) const
Stats::Histogram & getInitialToForwardDelayHist (const MachineType t) const
Stats::Histogram & getForwardRequestToFirstResponseHist (const MachineType t) const
Stats::Histogram & getFirstResponseToCompletionDelayHist (const MachineType t) const
Stats::Counter getIncompleteTimes (const MachineType t) const
Public Member Functions inherited from RubyPort
RubyPort (const Params *p)
virtual ~RubyPort ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void setController (AbstractController *_cntrl)
uint32_t getId ()
DrainState drain () override
Notify an object that it needs to drain its state.
bool isCPUSequencer ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
void issueRequest (PacketPtr pkt, RubyRequestType type)
void hitCallback (SequencerRequest *srequest, DataBlock &data, bool llscSuccess, const MachineType mach, const bool externalHit, const Cycles initialRequestTime, const Cycles forwardRequestTime, const Cycles firstResponseTime)
void recordMissLatency (SequencerRequest *srequest, bool llscSuccess, const MachineType respondingMach, bool isExternalHit, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
RequestStatus insertRequest (PacketPtr pkt, RubyRequestType primary_type, RubyRequestType secondary_type)
bool handleLlsc (Addr address, SequencerRequest *request)
Sequencer (const Sequencer &obj)
Sequencer & operator= (const Sequencer &obj)
Private Attributes
int m_max_outstanding_requests
Cycles m_deadlock_threshold
CacheMemory * m_dataCache_ptr
CacheMemory * m_instCache_ptr
Cycles m_data_cache_hit_latency
Cycles m_inst_cache_hit_latency
std::unordered_map< Addr, std::list< SequencerRequest > > m_RequestTable
int m_outstanding_count
bool m_deadlock_check_scheduled
int m_coreId
bool m_runningGarnetStandalone
Stats::Histogram m_outstandReqHist
Histogram for number of outstanding requests per cycle.
Stats::Histogram m_latencyHist
Histogram for holding latency profile of all requests.
std::vector< Stats::Histogram * > m_typeLatencyHist
Stats::Histogram m_hitLatencyHist
Histogram for holding latency profile of all requests that hit in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_hitTypeLatencyHist
std::vector< Stats::Histogram * > m_hitMachLatencyHist
Histograms for profiling the latencies for requests that did not required external messages.
std::vector< std::vector< Stats::Histogram * > > m_hitTypeMachLatencyHist
Stats::Histogram m_missLatencyHist
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_missTypeLatencyHist
std::vector< Stats::Histogram * > m_missMachLatencyHist
Histograms for profiling the latencies for requests that required external messages.
std::vector< std::vector< Stats::Histogram * > > m_missTypeMachLatencyHist
std::vector< Stats::Histogram * > m_IssueToInitialDelayHist
Histograms for recording the breakdown of miss latency.
std::vector< Stats::Histogram * > m_InitialToForwardDelayHist
std::vector< Stats::Histogram * > m_ForwardToFirstResponseDelayHist
std::vector< Stats::Histogram * > m_FirstResponseToCompletionDelayHist
std::vector< Stats::Counter > m_IncompleteTimes
EventFunctionWrapper deadlockCheckEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from RubyPort
void trySendRetries ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (Addr address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from RubyPort
RubySystem * m_ruby_system
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
std::vector< MemSlavePort * > slave_ports
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 59 of file Sequencer.hh.
Member Typedef Documentation
Params
typedef RubySequencerParams Sequencer::Params
Definition at line 62 of file Sequencer.hh.
Constructor & Destructor Documentation
Sequencer() [1/2]
Sequencer::Sequencer (const Params * p)
Definition at line 56 of file Sequencer.cc.
References m_coreId, m_dataCache_ptr, m_deadlock_threshold, m_instCache_ptr, m_max_outstanding_requests, m_outstanding_count, m_runningGarnetStandalone, MipsISA::p, and wakeup().
~Sequencer()
Sequencer::~Sequencer ()
Definition at line 76 of file Sequencer.cc.
Sequencer() [2/2]
Sequencer::Sequencer (const Sequencer & obj) private
Member Function Documentation
checkCoherence()
void Sequencer::checkCoherence (Addr address)
Definition at line 685 of file Sequencer.cc.
collateStats()
void Sequencer::collateStats ()
coreId()
int Sequencer::coreId () const inline
Definition at line 104 of file Sequencer.hh.
Referenced by issueRequest().
descheduleDeadlockEvent()
void Sequencer::descheduleDeadlockEvent () inline virtual
Implements RubyPort.
Definition at line 95 of file Sequencer.hh.
empty()
bool Sequencer::empty () const
Definition at line 511 of file Sequencer.cc.
References m_RequestTable.
evictionCallback()
void Sequencer::evictionCallback (Addr address)
Definition at line 696 of file Sequencer.cc.
References RubyPort::ruby_eviction_callback().
getFirstResponseToCompletionDelayHist()
Stats::Histogram& Sequencer::getFirstResponseToCompletionDelayHist (const MachineType t) const inline
Definition at line 147 of file Sequencer.hh.
References ArmISA::t.
getForwardRequestToFirstResponseHist()
Stats::Histogram& Sequencer::getForwardRequestToFirstResponseHist (const MachineType t) const inline
Definition at line 143 of file Sequencer.hh.
References ArmISA::t.
getHitLatencyHist()
Stats::Histogram& Sequencer::getHitLatencyHist () inline
Definition at line 113 of file Sequencer.hh.
Referenced by Profiler::collateStats().
getHitMachLatencyHist()
Stats::Histogram& Sequencer::getHitMachLatencyHist (uint32_t t) inline
Definition at line 117 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getHitTypeLatencyHist()
Stats::Histogram& Sequencer::getHitTypeLatencyHist (uint32_t t) inline
Definition at line 114 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getHitTypeMachLatencyHist()
Stats::Histogram& Sequencer::getHitTypeMachLatencyHist (uint32_t r, uint32_t t) inline
Definition at line 120 of file Sequencer.hh.
References MipsISA::r, and ArmISA::t.
Referenced by Profiler::collateStats().
getIncompleteTimes()
Stats::Counter Sequencer::getIncompleteTimes (const MachineType t) const inline
Definition at line 150 of file Sequencer.hh.
References SequencerRequest::pkt, ArmISA::t, and type.
Referenced by Profiler::collateStats().
getInitialToForwardDelayHist()
Stats::Histogram& Sequencer::getInitialToForwardDelayHist (const MachineType t) const inline
Definition at line 139 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getIssueToInitialDelayHist()
Stats::Histogram& Sequencer::getIssueToInitialDelayHist (uint32_t t) const inline
Definition at line 135 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getLatencyHist()
Stats::Histogram& Sequencer::getLatencyHist () inline
Definition at line 109 of file Sequencer.hh.
Referenced by Profiler::collateStats().
getMissLatencyHist()
Stats::Histogram& Sequencer::getMissLatencyHist () inline
Definition at line 123 of file Sequencer.hh.
Referenced by Profiler::collateStats().
getMissMachLatencyHist()
Stats::Histogram& Sequencer::getMissMachLatencyHist (uint32_t t) const inline
Definition at line 128 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getMissTypeLatencyHist()
Stats::Histogram& Sequencer::getMissTypeLatencyHist (uint32_t t) inline
Definition at line 125 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getMissTypeMachLatencyHist()
Stats::Histogram& Sequencer::getMissTypeMachLatencyHist (uint32_t r, uint32_t t) const inline
Definition at line 132 of file Sequencer.hh.
References MipsISA::r, and ArmISA::t.
Referenced by Profiler::collateStats().
getOutstandReqHist()
Stats::Histogram& Sequencer::getOutstandReqHist () inline
Definition at line 107 of file Sequencer.hh.
Referenced by Profiler::collateStats().
getTypeLatencyHist()
Stats::Histogram& Sequencer::getTypeLatencyHist (uint32_t t) inline
Definition at line 110 of file Sequencer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
handleLlsc()
bool Sequencer::handleLlsc (Addr address, SequencerRequest * request) private
Definition at line 190 of file Sequencer.cc.
References AbstractCacheEntry::clearLocked(), ArmISA::e, AbstractCacheEntry::isLocked(), CacheMemory::lookup(), m_dataCache_ptr, SequencerRequest::m_type, RubyPort::m_version, SequencerRequest::pkt, Packet::req, and AbstractCacheEntry::setLocked().
Referenced by writeCallback().
hitCallback()
void Sequencer::hitCallback (SequencerRequest * srequest, DataBlock & data, bool llscSuccess, const MachineType mach, const bool externalHit, const Cycles initialRequestTime, const Cycles forwardRequestTime, const Cycles firstResponseTime) private
Definition at line 439 of file Sequencer.cc.
References Packet::cmdString(), DPRINTF, CacheRecorder::enqueueNextFetchRequest(), CacheRecorder::enqueueNextFlushRequest(), Packet::findNextSenderState(), Packet::getAddr(), Packet::getConstPtr(), RubySystem::getCooldownEnabled(), DataBlock::getData(), getOffset(), Packet::getSize(), RubySystem::getWarmupEnabled(), Packet::isFlush(), RubySystem::m_cache_recorder, RubyPort::m_ruby_system, SequencerRequest::m_type, RubyPort::m_usingRubyTester, SequencerRequest::pkt, Packet::req, ArmISA::rs, RubyPort::ruby_hit_callback(), DataBlock::setData(), Packet::setData(), RubyPort::testDrainComplete(), type, warn_once, and Packet::writeData().
Referenced by readCallback(), and writeCallback().
insertRequest()
RequestStatus Sequencer::insertRequest (PacketPtr pkt, RubyRequestType primary_type, RubyRequestType secondary_type) private
Definition at line 147 of file Sequencer.cc.
References Clocked::clockEdge(), Clocked::curCycle(), deadlockCheckEvent, Draining, Drainable::drainState(), Packet::getAddr(), m_deadlock_threshold, m_outstanding_count, m_outstandReqHist, m_RequestTable, makeLineAddress(), Stats::DistBase< Derived, Stor >::sample(), EventManager::schedule(), and Event::scheduled().
Referenced by makeRequest().
invalidateSC()
void Sequencer::invalidateSC (Addr address)
Definition at line 179 of file Sequencer.cc.
References AbstractCacheEntry::clearLocked(), ArmISA::e, AbstractCacheEntry::isLocked(), CacheMemory::lookup(), m_dataCache_ptr, and RubyPort::m_version.
isDeadlockEventScheduled()
bool Sequencer::isDeadlockEventScheduled () const inline virtual
Implements RubyPort.
Definition at line 92 of file Sequencer.hh.
issueRequest()
void Sequencer::issueRequest (PacketPtr pkt, RubyRequestType type) private
Definition at line 620 of file Sequencer.cc.
References Clocked::clockEdge(), coreId(), curTick(), Clocked::cyclesToTicks(), DPRINTFR, MessageBuffer::enqueue(), Packet::getAddr(), Packet::getPtr(), Packet::getSize(), InvalidContextID, Packet::isFlush(), RubyPort::m_controller, RubyPort::m_mandatory_q_ptr, RubyPort::m_version, AbstractController::mandatoryQueueLatency(), MipsISA::pc, printAddress(), and Packet::req.
Referenced by makeRequest(), and readCallback().
makeRequest()
RequestStatus Sequencer::makeRequest (PacketPtr pkt) virtual
Implements RubyPort.
Definition at line 517 of file Sequencer.cc.
References DPRINTF, X86ISA::FlagShift, Packet::getAddr(), System::getArch(), insertRequest(), AbstractController::isBlocked(), Packet::isFlush(), Packet::isLLSC(), Packet::isRead(), issueRequest(), Packet::isWrite(), RubyPort::m_controller, m_max_outstanding_requests, m_outstanding_count, makeLineAddress(), panic, Packet::req, ArmISA::status, X86ISA::StoreCheck, and RubyPort::system.
Referenced by CacheRecorder::enqueueNextFetchRequest(), and CacheRecorder::enqueueNextFlushRequest().
markRemoved()
void Sequencer::markRemoved ()
Definition at line 173 of file Sequencer.cc.
References m_outstanding_count.
Referenced by readCallback(), and writeCallback().
operator=()
Sequencer& Sequencer::operator= (const Sequencer & obj) private
outstandingCount()
int Sequencer::outstandingCount () const inline virtual
Implements RubyPort.
Definition at line 90 of file Sequencer.hh.
print()
void Sequencer::print (std::ostream & out) const
Definition at line 673 of file Sequencer.cc.
References m_outstanding_count, m_RequestTable, and RubyPort::m_version.
Referenced by operator<<().
readCallback()
void Sequencer::readCallback (Addr address, DataBlock & data, const bool externalHit = false, const MachineType mach = MachineType_NUM, const Cycles initialRequestTime = Cycles(0), const Cycles forwardRequestTime = Cycles(0), const Cycles firstResponseTime = Cycles(0))
Definition at line 386 of file Sequencer.cc.
References hitCallback(), issueRequest(), m_RequestTable, SequencerRequest::m_second_type, SequencerRequest::m_type, makeLineAddress(), markRemoved(), SequencerRequest::pkt, and recordMissLatency().
recordMissLatency()
void Sequencer::recordMissLatency (SequencerRequest * srequest, bool llscSuccess, const MachineType respondingMach, bool isExternalHit, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime) private
Definition at line 235 of file Sequencer.cc.
References Clocked::curCycle(), curTick(), DPRINTFR, Packet::getAddr(), SequencerRequest::issue_time, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_hitLatencyHist, m_hitMachLatencyHist, m_hitTypeLatencyHist, m_hitTypeMachLatencyHist, m_IncompleteTimes, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, SequencerRequest::m_type, m_typeLatencyHist, RubyPort::m_version, SequencerRequest::pkt, printAddress(), Stats::DistBase< Derived, Stor >::sample(), and type.
Referenced by readCallback(), and writeCallback().
recordRequestType()
void Sequencer::recordRequestType (SequencerRequestType requestType)
Definition at line 690 of file Sequencer.cc.
References DPRINTF.
regStats()
void Sequencer::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 702 of file Sequencer.cc.
References ArmISA::i, Stats::Histogram::init(), ArmISA::j, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_hitLatencyHist, m_hitMachLatencyHist, m_hitTypeLatencyHist, m_hitTypeMachLatencyHist, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_outstandReqHist, m_typeLatencyHist, and Stats::Group::regStats().
resetStats()
void Sequencer::resetStats () virtual
Callback to reset stats.
Reimplemented from Stats::Group.
Definition at line 115 of file Sequencer.cc.
References ArmISA::i, ArmISA::j, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_hitLatencyHist, m_hitMachLatencyHist, m_hitTypeLatencyHist, m_hitTypeMachLatencyHist, m_IncompleteTimes, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_outstandReqHist, m_typeLatencyHist, and Stats::DistBase< Derived, Stor >::reset().
wakeup()
void Sequencer::wakeup ()
Definition at line 81 of file Sequencer.cc.
References Clocked::clockEdge(), Clocked::clockPeriod(), Clocked::curCycle(), deadlockCheckEvent, Draining, Drainable::drainState(), m_deadlock_threshold, m_outstanding_count, m_RequestTable, RubyPort::m_version, panic, and EventManager::schedule().
Referenced by Sequencer().
writeCallback()
void Sequencer::writeCallback (Addr address, DataBlock & data, const bool externalHit = false, const MachineType mach = MachineType_NUM, const Cycles initialRequestTime = Cycles(0), const Cycles forwardRequestTime = Cycles(0), const Cycles firstResponseTime = Cycles(0))
Definition at line 301 of file Sequencer.cc.
References AbstractController::blockOnQueue(), handleLlsc(), hitCallback(), RubyPort::m_controller, RubyPort::m_mandatory_q_ptr, m_RequestTable, m_runningGarnetStandalone, SequencerRequest::m_type, makeLineAddress(), markRemoved(), recordMissLatency(), and AbstractController::unblock().
Member Data Documentation
deadlockCheckEvent
EventFunctionWrapper Sequencer::deadlockCheckEvent private
Definition at line 236 of file Sequencer.hh.
Referenced by insertRequest(), and wakeup().
m_coreId
int Sequencer::m_coreId private
Definition at line 198 of file Sequencer.hh.
Referenced by Sequencer().
m_data_cache_hit_latency
Cycles Sequencer::m_data_cache_hit_latency private
Definition at line 188 of file Sequencer.hh.
m_dataCache_ptr
CacheMemory* Sequencer::m_dataCache_ptr private
Definition at line 181 of file Sequencer.hh.
Referenced by handleLlsc(), invalidateSC(), and Sequencer().
m_deadlock_check_scheduled
bool Sequencer::m_deadlock_check_scheduled private
Definition at line 196 of file Sequencer.hh.
m_deadlock_threshold
Cycles Sequencer::m_deadlock_threshold private
Definition at line 179 of file Sequencer.hh.
Referenced by insertRequest(), Sequencer(), and wakeup().
m_FirstResponseToCompletionDelayHist
std::vector<Stats::Histogram *> Sequencer::m_FirstResponseToCompletionDelayHist private
Definition at line 233 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_ForwardToFirstResponseDelayHist
std::vector<Stats::Histogram *> Sequencer::m_ForwardToFirstResponseDelayHist private
Definition at line 232 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_hitLatencyHist
Stats::Histogram Sequencer::m_hitLatencyHist private
Histogram for holding latency profile of all requests that hit in the controller connected to this sequencer.
Definition at line 211 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_hitMachLatencyHist
std::vector<Stats::Histogram *> Sequencer::m_hitMachLatencyHist private
Histograms for profiling the latencies for requests that did not required external messages.
Definition at line 216 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_hitTypeLatencyHist
std::vector<Stats::Histogram *> Sequencer::m_hitTypeLatencyHist private
Definition at line 212 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_hitTypeMachLatencyHist
std::vector< std::vector<Stats::Histogram *> > Sequencer::m_hitTypeMachLatencyHist private
Definition at line 217 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_IncompleteTimes
std::vector<Stats::Counter> Sequencer::m_IncompleteTimes private
Definition at line 234 of file Sequencer.hh.
Referenced by recordMissLatency(), and resetStats().
m_InitialToForwardDelayHist
std::vector<Stats::Histogram *> Sequencer::m_InitialToForwardDelayHist private
Definition at line 231 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_inst_cache_hit_latency
Cycles Sequencer::m_inst_cache_hit_latency private
Definition at line 189 of file Sequencer.hh.
m_instCache_ptr
CacheMemory* Sequencer::m_instCache_ptr private
Definition at line 182 of file Sequencer.hh.
Referenced by Sequencer().
m_IssueToInitialDelayHist
std::vector<Stats::Histogram *> Sequencer::m_IssueToInitialDelayHist private
Histograms for recording the breakdown of miss latency.
Definition at line 230 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_latencyHist
Stats::Histogram Sequencer::m_latencyHist private
Histogram for holding latency profile of all requests.
Definition at line 206 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_max_outstanding_requests
int Sequencer::m_max_outstanding_requests private
Definition at line 178 of file Sequencer.hh.
Referenced by makeRequest(), and Sequencer().
m_missLatencyHist
Stats::Histogram Sequencer::m_missLatencyHist private
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
Definition at line 221 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missMachLatencyHist
std::vector<Stats::Histogram *> Sequencer::m_missMachLatencyHist private
Histograms for profiling the latencies for requests that required external messages.
Definition at line 226 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missTypeLatencyHist
std::vector<Stats::Histogram *> Sequencer::m_missTypeLatencyHist private
Definition at line 222 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missTypeMachLatencyHist
std::vector< std::vector<Stats::Histogram *> > Sequencer::m_missTypeMachLatencyHist private
Definition at line 227 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_outstanding_count
int Sequencer::m_outstanding_count private
Definition at line 195 of file Sequencer.hh.
Referenced by insertRequest(), makeRequest(), markRemoved(), print(), Sequencer(), and wakeup().
m_outstandReqHist
Stats::Histogram Sequencer::m_outstandReqHist private
Histogram for number of outstanding requests per cycle.
Definition at line 203 of file Sequencer.hh.
Referenced by insertRequest(), regStats(), and resetStats().
m_RequestTable
std::unordered_map<Addr, std::list<SequencerRequest> > Sequencer::m_RequestTable private
Definition at line 192 of file Sequencer.hh.
Referenced by empty(), insertRequest(), print(), readCallback(), wakeup(), and writeCallback().
m_runningGarnetStandalone
bool Sequencer::m_runningGarnetStandalone private
Definition at line 200 of file Sequencer.hh.
Referenced by Sequencer(), and writeCallback().
m_typeLatencyHist
std::vector<Stats::Histogram *> Sequencer::m_typeLatencyHist private
Definition at line 207 of file Sequencer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
The documentation for this class was generated from the following files:
mem/ruby/system/Sequencer.hh
mem/ruby/system/Sequencer.cc