gem5: AlphaBackdoor Class Reference
AlphaBackdoor Class Reference
Memory mapped interface to the system console.
#include <backdoor.hh>
Classes
struct Access
Public Types
typedef AlphaBackdoorParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
AlphaBackdoor (const Params *p)
const Params * params () const
void startup () override
startup() is the final initialization call before simulation.
Tick read (PacketPtr pkt) override
memory mapped reads and writes
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void serialize (CheckpointOut &cp) const override
standard serialization routines for checkpointing
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
union {
Access * alphaAccess
uint8_t * consoleData
};
SimpleDisk * disk
the disk must be accessed from the console
Terminal * terminal
the system console (the terminal) is accessable from the console
AlphaSystem * system
a pointer to the system we are running in
BaseCPU * cpu
a pointer to the CPU boot cpu
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Memory mapped interface to the system console.
This device represents a shared data region between the OS Kernel and the System Console Backdoor.
The system console is a small standalone program that is initially run when the system boots. It contains the necessary code to access the boot disk, to read/write from the console, and to pass boot parameters to the kernel.
This version of the system console is very different from the one that would be found in a real system. Many of the functions use some sort of backdoor to get their job done. For example, reading from the boot device on a real system would require a minimal device driver to access the disk controller, but since we have a simulator here, we are able to bypass the disk controller and access the disk image directly. There are also some things like reading the kernel off the disk image into memory that are normally taken care of by the console that are now taken care of by the simulator.
These shortcuts are acceptable since the system console is primarily used doing boot before the kernel has loaded its device drivers.
Definition at line 74 of file backdoor.hh.
Member Typedef Documentation
Params
typedef AlphaBackdoorParams AlphaBackdoor::Params
Definition at line 101 of file backdoor.hh.
Constructor & Destructor Documentation
AlphaBackdoor()
AlphaBackdoor::AlphaBackdoor (const Params * p)
Definition at line 65 of file backdoor.cc.
References ALPHA_ACCESS_VERSION, alphaAccess, AlphaAccess::cpuStack, AlphaAccess::diskBlock, AlphaAccess::diskCount, AlphaAccess::diskOperation, AlphaAccess::diskPAddr, AlphaAccess::diskUnit, AlphaAccess::inputChar, AlphaAccess::last_offset, AlphaAccess::outputChar, BasicPioDevice::pioSize, and AlphaAccess::version.
Referenced by unserialize().
Member Function Documentation
params()
const Params* AlphaBackdoor::params () const inline
Definition at line 105 of file backdoor.hh.
References SimObject::_params, read(), AlphaBackdoor::Access::serialize(), startup(), AlphaBackdoor::Access::unserialize(), and write().
Referenced by startup().
read()
Tick AlphaBackdoor::read (PacketPtr pkt) override virtual
memory mapped reads and writes
XXX Do we want to push the addr munging to a bus brige or something? So the device has it's physical address and then the bridge adds on whatever machine dependent address swizzle is required?
Implements PioDevice.
Definition at line 103 of file backdoor.cc.
References alphaAccess, Terminal::console_in(), AlphaAccess::cpuClock, AlphaAccess::cpuStack, AlphaAccess::diskBlock, AlphaAccess::diskCount, AlphaAccess::diskOperation, AlphaAccess::diskPAddr, AlphaAccess::diskUnit, DPRINTF, AlphaAccess::entryPoint, Packet::getAddr(), Packet::getLE(), Packet::getSize(), AlphaAccess::intrClockFrequency, AlphaAccess::kernEnd, AlphaAccess::kernStart, AlphaAccess::last_offset, Packet::makeAtomicResponse(), AlphaAccess::mem_size, AlphaAccess::numCPUs, ArmISA::numCPUs, AlphaAccess::outputChar, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, Packet::setBadAddress(), Packet::setLE(), terminal, and AlphaAccess::version.
Referenced by params().
serialize()
void AlphaBackdoor::serialize (CheckpointOut & cp) const override virtual
standard serialization routines for checkpointing
Implements Serializable.
Definition at line 300 of file backdoor.cc.
References alphaAccess, and AlphaBackdoor::Access::serialize().
startup()
void AlphaBackdoor::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 87 of file backdoor.cc.
References alphaAccess, cpu, AlphaAccess::cpuClock, AlphaAccess::entryPoint, fatal, TsunamiIO::frequency(), Clocked::frequency(), System::getKernelEnd(), System::getKernelEntry(), System::getKernelStart(), AlphaAccess::intrClockFrequency, Tsunami::io, AlphaAccess::kernEnd, AlphaAccess::kernStart, AlphaAccess::mem_size, System::memSize(), System::numContexts(), AlphaAccess::numCPUs, params(), BasicPioDevice::pioAddr, AlphaSystem::setAlphaAccess(), and system.
Referenced by params().
unserialize()
void AlphaBackdoor::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 306 of file backdoor.cc.
References alphaAccess, AlphaBackdoor(), and AlphaBackdoor::Access::unserialize().
write()
Tick AlphaBackdoor::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 201 of file backdoor.cc.
References alphaAccess, AlphaAccess::cpuStack, curTick(), disk, AlphaAccess::diskBlock, AlphaAccess::diskCount, AlphaAccess::diskPAddr, AlphaAccess::diskUnit, Packet::getAddr(), Packet::getLE(), Packet::getSize(), inform, Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, SimpleDisk::read(), terminal, X86ISA::val, and Terminal::writeData().
Referenced by params().
Member Data Documentation
@42
union { ... }
alphaAccess
Access* AlphaBackdoor::alphaAccess
Definition at line 84 of file backdoor.hh.
Referenced by AlphaBackdoor(), read(), serialize(), startup(), unserialize(), and write().
consoleData
uint8_t* AlphaBackdoor::consoleData
Definition at line 85 of file backdoor.hh.
cpu
BaseCPU* AlphaBackdoor::cpu protected
a pointer to the CPU boot cpu
Definition at line 98 of file backdoor.hh.
Referenced by startup().
disk
SimpleDisk* AlphaBackdoor::disk protected
the disk must be accessed from the console
Definition at line 89 of file backdoor.hh.
Referenced by write().
system
AlphaSystem* AlphaBackdoor::system protected
a pointer to the system we are running in
Definition at line 95 of file backdoor.hh.
Referenced by startup().
terminal
Terminal* AlphaBackdoor::terminal protected
the system console (the terminal) is accessable from the console
Definition at line 92 of file backdoor.hh.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
dev/alpha/backdoor.hh
dev/alpha/backdoor.cc