gem5: ComputeUnit::LDSPort Class Reference
ComputeUnit::LDSPort Class Reference
the port intended to communicate between the CU and its LDS
#include <compute_unit.hh>
Classes
class SenderState
SenderState is information carried along with the packet, esp.
Public Member Functions
LDSPort (const std::string &_name, ComputeUnit *_cu, PortID _id)
bool isStalled () const
void stallPort ()
void unstallPort ()
virtual bool sendTimingReq (PacketPtr pkt)
attempt to send this packet, either the port is already stalled, the request is nack'd and must stall or the request goes through when a request cannot be sent, add it to the retries queue
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Public Attributes
std::queue< PacketPtr > retries
here we queue all the requests that were not successfully sent.
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
get the result of packets sent to the LDS when they return
virtual Tick recvAtomic (PacketPtr pkt)
virtual void recvFunctional (PacketPtr pkt)
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
virtual void recvReqRetry ()
the bus is telling the port that there is now space so retrying stalled requests should work now this allows the port to have a request be nack'd and then have the receiver say when there is space, rather than simply retrying the send every cycle
Protected Member Functions inherited from MasterPort
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
bool stalled = false
whether or not it is stalled
ComputeUnit * computeUnit
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
the port intended to communicate between the CU and its LDS
Definition at line 602 of file compute_unit.hh.
Constructor & Destructor Documentation
LDSPort()
ComputeUnit::LDSPort::LDSPort (const std::string & _name, ComputeUnit * _cu, PortID _id) inline
Definition at line 605 of file compute_unit.hh.
Member Function Documentation
isStalled()
bool ComputeUnit::LDSPort::isStalled () const inline
Definition at line 610 of file compute_unit.hh.
recvAtomic()
virtual Tick ComputeUnit::LDSPort::recvAtomic (PacketPtr pkt) inline protected virtual
Definition at line 656 of file compute_unit.hh.
recvFunctional()
virtual void ComputeUnit::LDSPort::recvFunctional (PacketPtr pkt) inline protected virtual
Definition at line 659 of file compute_unit.hh.
recvRangeChange()
virtual void ComputeUnit::LDSPort::recvRangeChange () inline protected virtual
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 664 of file compute_unit.hh.
recvReqRetry()
void ComputeUnit::LDSPort::recvReqRetry () protected virtual
the bus is telling the port that there is now space so retrying stalled requests should work now this allows the port to have a request be nack'd and then have the receiver say when there is space, rather than simply retrying the send every cycle
Implements TimingRequestProtocol.
Definition at line 1881 of file compute_unit.cc.
References DPRINTF, fatal_if, and MasterPort::sendTimingReq().
recvTimingResp()
bool ComputeUnit::LDSPort::recvTimingResp (PacketPtr pkt) protected virtual
get the result of packets sent to the LDS when they return
Implements TimingRequestProtocol.
Definition at line 1817 of file compute_unit.cc.
References fatal_if, ComputeUnit::LDSPort::SenderState::getMemInst(), and Packet::senderState.
sendTimingReq()
bool ComputeUnit::LDSPort::sendTimingReq (PacketPtr pkt) virtual
attempt to send this packet, either the port is already stalled, the request is nack'd and must stall or the request goes through when a request cannot be sent, add it to the retries queue
Definition at line 1839 of file compute_unit.cc.
References DPRINTF, fatal_if, ComputeUnit::LDSPort::SenderState::getMemInst(), M5_VAR_USED, Packet::req, Packet::senderState, and MasterPort::sendTimingReq().
Referenced by ComputeUnit::sendToLds().
stallPort()
void ComputeUnit::LDSPort::stallPort () inline
Definition at line 611 of file compute_unit.hh.
unstallPort()
void ComputeUnit::LDSPort::unstallPort () inline
Definition at line 612 of file compute_unit.hh.
Member Data Documentation
computeUnit
ComputeUnit* ComputeUnit::LDSPort::computeUnit protected
Definition at line 650 of file compute_unit.hh.
retries
std::queue<PacketPtr> ComputeUnit::LDSPort::retries
here we queue all the requests that were not successfully sent.
Definition at line 618 of file compute_unit.hh.
stalled
bool ComputeUnit::LDSPort::stalled = false protected
whether or not it is stalled
Definition at line 648 of file compute_unit.hh.
The documentation for this class was generated from the following files:
gpu-compute/compute_unit.hh
gpu-compute/compute_unit.cc