gem5: Request Class Reference
Request Class Reference
#include <request.hh>
Public Types
enum : FlagsType {
ARCH_BITS = 0x000000FF, INST_FETCH = 0x00000100, PHYSICAL = 0x00000200, UNCACHEABLE = 0x00000400,
STRICT_ORDER = 0x00000800, MMAPPED_IPR = 0x00002000, PRIVILEGED = 0x00008000, CACHE_BLOCK_ZERO = 0x00010000,
NO_ACCESS = 0x00080000, LOCKED_RMW = 0x00100000, LLSC = 0x00200000, MEM_SWAP = 0x00400000,
MEM_SWAP_COND = 0x00800000, PREFETCH = 0x01000000, PF_EXCLUSIVE = 0x02000000, EVICT_NEXT = 0x04000000,
ACQUIRE = 0x00020000, RELEASE = 0x00040000, ATOMIC_RETURN_OP = 0x40000000, ATOMIC_NO_RETURN_OP = 0x80000000,
KERNEL = 0x00001000, GENERIC_IPR = 0x08000000, SECURE = 0x10000000, PT_WALK = 0x20000000,
INVALIDATE = 0x0000000100000000, CLEAN = 0x0000000200000000, DST_POU = 0x0000001000000000, DST_POC = 0x0000002000000000,
DST_BITS = 0x0000003000000000, STICKY_FLAGS = INST_FETCH
}
enum : MemSpaceConfigFlagsType {
SCOPE_VALID = 0x00000001, WAVEFRONT_SCOPE = 0x00000002, WORKGROUP_SCOPE = 0x00000004, DEVICE_SCOPE = 0x00000008,
SYSTEM_SCOPE = 0x00000010, GLOBAL_SEGMENT = 0x00000020, GROUP_SEGMENT = 0x00000040, PRIVATE_SEGMENT = 0x00000080,
KERNARG_SEGMENT = 0x00000100, READONLY_SEGMENT = 0x00000200, SPILL_SEGMENT = 0x00000400, ARG_SEGMENT = 0x00000800
}
typedef uint64_t FlagsType
typedef uint8_t ArchFlagsType
typedef ::Flags< FlagsType > Flags
typedef uint32_t MemSpaceConfigFlagsType
typedef ::Flags< MemSpaceConfigFlagsType > MemSpaceConfigFlags
enum : MasterID { wbMasterId = 0, funcMasterId = 1, intMasterId = 2, invldMasterId = std::numeric_limits<MasterID>::max() }
Master Ids that are statically allocated.
Public Member Functions
Request ()
Minimal constructor.
Request (Addr paddr, unsigned size, Flags flags, MasterID mid, InstSeqNum seq_num, ContextID cid)
Request (Addr paddr, unsigned size, Flags flags, MasterID mid)
Constructor for physical (e.g.
Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time)
Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time, Addr pc)
Request (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, ContextID cid)
Request (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, ContextID cid, AtomicOpFunctorPtr atomic_op)
Request (const Request &other)
~Request ()
void setContext (ContextID context_id)
Set up Context numbers.
void setStreamId (uint32_t sid)
void setSubStreamId (uint32_t ssid)
void setVirt (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, AtomicOpFunctorPtr amo_op=nullptr)
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
void setPaddr (Addr paddr)
Set just the physical address.
void splitOnVaddr (Addr split_addr, RequestPtr &req1, RequestPtr &req2)
Generate two requests as if this request had been split into two pieces.
bool hasPaddr () const
Accessor for paddr.
Addr getPaddr () const
bool hasSize () const
Accessor for size.
unsigned getSize () const
const std::vector< bool > & getByteEnable () const
void setByteEnable (const std::vector< bool > &be)
Tick time () const
Accessor for time.
bool hasAtomicOpFunctor ()
Accessor for atomic-op functor.
AtomicOpFunctor * getAtomicOpFunctor ()
Flags getFlags ()
Accessor for flags.
void setFlags (Flags flags)
Note that unlike other accessors, this function sets specific flags (ORs them in); it does not assign its argument to the _flags field.
void setMemSpaceConfigFlags (MemSpaceConfigFlags extraFlags)
bool hasVaddr () const
Accessor function for vaddr.
Addr getVaddr () const
MasterID masterId () const
Accesssor for the requestor id.
uint32_t taskId () const
void taskId (uint32_t id)
uint64_t getAsid () const
Accessor function for asid.
void setAsid (uint64_t asid)
Accessor function for asid.
ArchFlagsType getArchFlags () const
Accessor function for architecture-specific flags.
bool extraDataValid () const
Accessor function to check if sc result is valid.
uint64_t getExtraData () const
Accessor function for store conditional return value.
void setExtraData (uint64_t extraData)
Accessor function for store conditional return value.
bool hasContextId () const
ContextID contextId () const
Accessor function for context ID.
uint32_t streamId () const
bool hasSubstreamId () const
uint32_t substreamId () const
void setPC (Addr pc)
bool hasPC () const
Addr getPC () const
Accessor function for pc.
void incAccessDepth () const
Increment/Get the depth at which this request is responded to.
int getAccessDepth () const
void setTranslateLatency ()
Set/Get the time taken for this request to be successfully translated.
Tick getTranslateLatency () const
void setAccessLatency ()
Set/Get the time taken to complete this request's access, not including the time to successfully translate the request.
Tick getAccessLatency () const
bool hasInstSeqNum () const
Accessor for the sequence number of instruction that creates the request.
InstSeqNum getReqInstSeqNum () const
void setReqInstSeqNum (const InstSeqNum seq_num)
bool isUncacheable () const
Accessor functions for flags.
bool isStrictlyOrdered () const
bool isInstFetch () const
bool isPrefetch () const
bool isPrefetchEx () const
bool isLLSC () const
bool isPriv () const
bool isLockedRMW () const
bool isSwap () const
bool isCondSwap () const
bool isMmappedIpr () const
bool isSecure () const
bool isPTWalk () const
bool isAcquire () const
bool isRelease () const
bool isKernel () const
bool isAtomicReturn () const
bool isAtomicNoReturn () const
bool isAtomic () const
bool isToPOU () const
Accessor functions for the destination of a memory request.
bool isToPOC () const
Flags getDest () const
bool isScoped () const
Accessor functions for the memory space configuration flags and used by GPU ISAs such as the Heterogeneous System Architecture (HSA).
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isGlobalSegment () const
bool isGroupSegment () const
bool isPrivateSegment () const
bool isKernargSegment () const
bool isReadonlySegment () const
bool isSpillSegment () const
bool isArgSegment () const
bool isCacheClean () const
Accessor functions to determine whether this request is part of a cache maintenance operation.
bool isCacheInvalidate () const
bool isCacheMaintenance () const
Public Attributes
Tick translateDelta
Time for the TLB/table walker to successfully translate this request.
Tick accessDelta
Access latency to complete this memory transaction not including translation time.
int depth
Level of the cache hierachy where this request was responded to (e.g.
uint32_t _streamId
The stream ID uniquely identifies a device behind the SMMU/IOMMU Each transaction arriving at the SMMU/IOMMU is associated with exactly one stream ID.
uint32_t _substreamId
The substream ID identifies an "execution context" within a device behind an SMMU/IOMMU.
uint64_t _asid
The address space ID.
Static Public Attributes
static const FlagsType STORE_NO_DATA
Private Types
enum : PrivateFlagsType {
VALID_SIZE = 0x00000001, VALID_PADDR = 0x00000002, VALID_VADDR = 0x00000004, VALID_INST_SEQ_NUM = 0x00000008,
VALID_PC = 0x00000010, VALID_CONTEXT_ID = 0x00000020, VALID_EXTRA_DATA = 0x00000080, VALID_STREAM_ID = 0x00000100,
VALID_SUBSTREAM_ID = 0x00000200, STICKY_PRIVATE_FLAGS = VALID_CONTEXT_ID
}
typedef uint16_t PrivateFlagsType
typedef ::Flags< PrivateFlagsType > PrivateFlags
Private Member Functions
void setPhys (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time)
Set up a physical (e.g.
Private Attributes
Addr _paddr
The physical address of the request.
unsigned _size
The size of the request.
std::vector< bool > _byteEnable
Byte-enable mask for writes.
MasterID _masterId
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Flags _flags
Flag structure for the request.
MemSpaceConfigFlags _memSpaceConfigFlags
Memory space configuraiton flag structure for the request.
PrivateFlags privateFlags
Private flags for field validity checking.
Tick _time
The time this request was started.
uint32_t _taskId
The task id associated with this request.
union {
struct {
uint32_t _streamId
The stream ID uniquely identifies a device behind the SMMU/IOMMU Each transaction arriving at the SMMU/IOMMU is associated with exactly one stream ID.
uint32_t _substreamId
The substream ID identifies an "execution context" within a device behind an SMMU/IOMMU.
}
uint64_t _asid
The address space ID.
};
Addr _vaddr
The virtual address of the request.
uint64_t _extraData
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
ContextID _contextId
The context ID (for statistics, locks, and wakeups).
Addr _pc
program counter of initiating access; for tracing/debugging
InstSeqNum _reqInstSeqNum
Sequence number of the instruction that creates the request.
AtomicOpFunctorPtr atomicOpFunctor
A pointer to an atomic operation.
Detailed Description
Definition at line 87 of file request.hh.
Member Typedef Documentation
ArchFlagsType
typedef uint8_t Request::ArchFlagsType
Definition at line 91 of file request.hh.
Flags
typedef ::Flags<FlagsType> Request::Flags
Definition at line 92 of file request.hh.
FlagsType
typedef uint64_t Request::FlagsType
Definition at line 90 of file request.hh.
MemSpaceConfigFlags
typedef ::Flags<MemSpaceConfigFlagsType> Request::MemSpaceConfigFlags
Definition at line 229 of file request.hh.
MemSpaceConfigFlagsType
typedef uint32_t Request::MemSpaceConfigFlagsType
Definition at line 228 of file request.hh.
PrivateFlags
typedef ::Flags<PrivateFlagsType> Request::PrivateFlags private
Definition at line 261 of file request.hh.
PrivateFlagsType
typedef uint16_t Request::PrivateFlagsType private
Definition at line 260 of file request.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum : FlagsType
Enumerator
ARCH_BITS
Architecture specific flags.
These bits int the flag field are reserved for architecture-specific code. For example, SPARC uses them to represent ASIs.
INST_FETCH
The request was an instruction fetch.
PHYSICAL
The virtual address is also the physical address.
UNCACHEABLE
The request is to an uncacheable address.
Note
Uncacheable accesses may be reordered by CPU models. The STRICT_ORDER flag should be set if such reordering is undesirable.
STRICT_ORDER
The request is required to be strictly ordered by CPU models and is non-speculative.
A strictly ordered request is guaranteed to never be re-ordered or executed speculatively by a CPU model. The memory system may still reorder requests in caches unless the UNCACHEABLE flag is set as well.
MMAPPED_IPR
This request is to a memory mapped register.
PRIVILEGED
This request is made in privileged mode.
CACHE_BLOCK_ZERO
This is a write that is targeted and zeroing an entire cache block.
There is no need for a read/modify/write
NO_ACCESS
The request should not cause a memory access.
LOCKED_RMW
This request will lock or unlock the accessed memory.
When used with a load, the access locks the particular chunk of memory. When used with a store, it unlocks. The rule is that locked accesses have to be made up of a locked load, some operation on the data, and then a locked store.
LLSC
The request is a Load locked/store conditional.
MEM_SWAP
This request is for a memory swap.
MEM_SWAP_COND
PREFETCH
The request is a prefetch.
PF_EXCLUSIVE
The request should be prefetched into the exclusive state.
EVICT_NEXT
The request should be marked as LRU.
ACQUIRE
The request should be marked with ACQUIRE.
RELEASE
The request should be marked with RELEASE.
ATOMIC_RETURN_OP
The request is an atomic that returns data.
ATOMIC_NO_RETURN_OP
The request is an atomic that does not return data.
KERNEL
The request should be marked with KERNEL.
Used to indicate the synchronization associated with a GPU kernel launch or completion.
GENERIC_IPR
The request should be handled by the generic IPR code (only valid together with MMAPPED_IPR)
SECURE
The request targets the secure memory space.
PT_WALK
The request is a page table walk.
INVALIDATE
The request invalidates a memory location.
CLEAN
The request cleans a memory location.
DST_POU
The request targets the point of unification.
DST_POC
The request targets the point of coherence.
DST_BITS
Bits to define the destination of a request.
STICKY_FLAGS
These flags are not cleared when a Request object is reused (assigned a new address).
Definition at line 94 of file request.hh.
anonymous enum
anonymous enum : MasterID
Master Ids that are statically allocated.
Enumerator
wbMasterId
This master id is used for writeback requests by the caches.
funcMasterId
This master id is used for functional requests that don't come from a particular device.
intMasterId
This master id is used for message signaled interrupts.
invldMasterId
Invalid master id for assertion checking only.
It is invalid behavior to ever send this id as part of a request.
Definition at line 210 of file request.hh.
anonymous enum
anonymous enum : MemSpaceConfigFlagsType
Enumerator
SCOPE_VALID
Has a synchronization scope been set?
WAVEFRONT_SCOPE
Access has Wavefront scope visibility.
WORKGROUP_SCOPE
Access has Workgroup scope visibility.
DEVICE_SCOPE
Access has Device (e.g., GPU) scope visibility.
SYSTEM_SCOPE
Access has System (e.g., CPU + GPU) scope visibility.
GLOBAL_SEGMENT
Global Segment.
GROUP_SEGMENT
Group Segment.
PRIVATE_SEGMENT
Private Segment.
KERNARG_SEGMENT
Kergarg Segment.
READONLY_SEGMENT
Readonly Segment.
SPILL_SEGMENT
Spill Segment.
ARG_SEGMENT
Arg Segment.
Definition at line 231 of file request.hh.
anonymous enum
anonymous enum : PrivateFlagsType private
Enumerator
VALID_SIZE
Whether or not the size is valid.
VALID_PADDR
Whether or not paddr is valid (has been written yet).
VALID_VADDR
Whether or not the vaddr & asid are valid.
VALID_INST_SEQ_NUM
Whether or not the instruction sequence number is valid.
VALID_PC
Whether or not the pc is valid.
VALID_CONTEXT_ID
Whether or not the context ID is valid.
VALID_EXTRA_DATA
Whether or not the sc result is valid.
VALID_STREAM_ID
Whether or not the stream ID and substream ID is valid.
VALID_SUBSTREAM_ID
STICKY_PRIVATE_FLAGS
These flags are not cleared when a Request object is reused (assigned a new address).
Definition at line 263 of file request.hh.
Constructor & Destructor Documentation
Request() [1/8]
Request::Request () inline
Minimal constructor.
No fields are initialized. (Note that _flags and privateFlags are cleared by Flags default constructor.)
Definition at line 401 of file request.hh.
Request() [2/8]
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid, InstSeqNum seq_num, ContextID cid) inline
Definition at line 409 of file request.hh.
References curTick(), and Flags< T >::set().
Request() [3/8]
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid) inline
Constructor for physical (e.g.
device) requests. Initializes just physical address, size, flags, and timestamp (to curTick()). These fields are adequate to perform a request.
Definition at line 427 of file request.hh.
References curTick().
Request() [4/8]
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time) inline
Definition at line 437 of file request.hh.
Request() [5/8]
Request::Request (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time, Addr pc) inline
Definition at line 447 of file request.hh.
References Flags< T >::set().
Request() [6/8]
Request::Request (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, ContextID cid) inline
Definition at line 459 of file request.hh.
Request() [7/8]
Request::Request (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, ContextID cid, AtomicOpFunctorPtr atomic_op) inline
Definition at line 471 of file request.hh.
Request() [8/8]
Request::Request (const Request & other) inline
Definition at line 479 of file request.hh.
References atomicOpFunctor.
~Request()
Request::~Request () inline
Definition at line 497 of file request.hh.
Member Function Documentation
contextId()
ContextID Request::contextId () const inline
Accessor function for context ID.
Definition at line 788 of file request.hh.
References Flags< T >::isSet().
extraDataValid()
bool Request::extraDataValid () const inline
Accessor function to check if sc result is valid.
Definition at line 759 of file request.hh.
References Flags< T >::isSet().
getAccessDepth()
int Request::getAccessDepth () const inline
Definition at line 840 of file request.hh.
getAccessLatency()
Tick Request::getAccessLatency () const inline
Definition at line 853 of file request.hh.
getArchFlags()
ArchFlagsType Request::getArchFlags () const inline
Accessor function for architecture-specific flags.
Definition at line 751 of file request.hh.
References Flags< T >::isSet().
getAsid()
uint64_t Request::getAsid () const inline
Accessor function for asid.
Definition at line 736 of file request.hh.
References Flags< T >::isSet().
getAtomicOpFunctor()
AtomicOpFunctor* Request::getAtomicOpFunctor () inline
Definition at line 670 of file request.hh.
getByteEnable()
const std::vector<bool>& Request::getByteEnable () const inline
Definition at line 640 of file request.hh.
getDest()
Flags Request::getDest () const inline
Definition at line 917 of file request.hh.
getExtraData()
uint64_t Request::getExtraData () const inline
Accessor function for store conditional return value.
Definition at line 766 of file request.hh.
References Flags< T >::isSet().
getFlags()
Flags Request::getFlags () inline
Accessor for flags.
Definition at line 678 of file request.hh.
References Flags< T >::isSet().
getPaddr()
Addr Request::getPaddr () const inline
Definition at line 600 of file request.hh.
References Flags< T >::isSet().
getPC()
Addr Request::getPC () const inline
Accessor function for pc.
Definition at line 829 of file request.hh.
References Flags< T >::isSet().
getReqInstSeqNum()
InstSeqNum Request::getReqInstSeqNum () const inline
Definition at line 866 of file request.hh.
References Flags< T >::isSet().
getSize()
unsigned Request::getSize () const inline
Definition at line 633 of file request.hh.
References Flags< T >::isSet().
getTranslateLatency()
Tick Request::getTranslateLatency () const inline
Definition at line 846 of file request.hh.
getVaddr()
Addr Request::getVaddr () const inline
Definition at line 710 of file request.hh.
References Flags< T >::isSet().
hasAtomicOpFunctor()
bool Request::hasAtomicOpFunctor () inline
Accessor for atomic-op functor.
Definition at line 664 of file request.hh.
hasContextId()
bool Request::hasContextId () const inline
Definition at line 781 of file request.hh.
References Flags< T >::isSet().
hasInstSeqNum()
bool Request::hasInstSeqNum () const inline
Accessor for the sequence number of instruction that creates the request.
Definition at line 860 of file request.hh.
References Flags< T >::isSet().
hasPaddr()
bool Request::hasPaddr () const inline
Accessor for paddr.
Definition at line 594 of file request.hh.
References Flags< T >::isSet().
hasPC()
bool Request::hasPC () const inline
Definition at line 822 of file request.hh.
References Flags< T >::isSet().
hasSize()
bool Request::hasSize () const inline
Accessor for size.
Definition at line 627 of file request.hh.
References Flags< T >::isSet().
hasSubstreamId()
bool Request::hasSubstreamId () const inline
Definition at line 802 of file request.hh.
References Flags< T >::isSet().
hasVaddr()
bool Request::hasVaddr () const inline
Accessor function for vaddr.
Definition at line 704 of file request.hh.
References Flags< T >::isSet().
incAccessDepth()
void Request::incAccessDepth () const inline
Increment/Get the depth at which this request is responded to.
This currently happens when the request misses in any cache level.
Definition at line 839 of file request.hh.
isAcquire()
bool Request::isAcquire () const inline
Definition at line 895 of file request.hh.
References Flags< T >::isSet().
isArgSegment()
bool Request::isArgSegment () const inline
Definition at line 995 of file request.hh.
References Flags< T >::isSet().
isAtomic()
bool Request::isAtomic () const inline
Definition at line 902 of file request.hh.
References Flags< T >::isSet().
isAtomicNoReturn()
bool Request::isAtomicNoReturn () const inline
Definition at line 899 of file request.hh.
References Flags< T >::isSet().
isAtomicReturn()
bool Request::isAtomicReturn () const inline
Definition at line 898 of file request.hh.
References Flags< T >::isSet().
isCacheClean()
bool Request::isCacheClean () const inline
Accessor functions to determine whether this request is part of a cache maintenance operation.
At the moment three operations are supported:
1) A cache clean operation updates all copies of a memory location to the point of reference, 2) A cache invalidate operation invalidates all copies of the specified block in the memory above the point of reference, 3) A clean and invalidate operation is a combination of the two operations.
Definition at line 1012 of file request.hh.
References Flags< T >::isSet().
isCacheInvalidate()
bool Request::isCacheInvalidate () const inline
Definition at line 1013 of file request.hh.
References Flags< T >::isSet().
isCacheMaintenance()
bool Request::isCacheMaintenance () const inline
Definition at line 1014 of file request.hh.
References Flags< T >::isSet().
isCondSwap()
bool Request::isCondSwap () const inline
Definition at line 891 of file request.hh.
References Flags< T >::isSet().
isDeviceScope()
bool Request::isDeviceScope () const inline
Definition at line 942 of file request.hh.
References Flags< T >::isSet().
isGlobalSegment()
bool Request::isGlobalSegment () const inline
Definition at line 956 of file request.hh.
References Flags< T >::isSet().
isGroupSegment()
bool Request::isGroupSegment () const inline
Definition at line 965 of file request.hh.
References Flags< T >::isSet().
isInstFetch()
bool Request::isInstFetch () const inline
Definition at line 883 of file request.hh.
References Flags< T >::isSet().
isKernargSegment()
bool Request::isKernargSegment () const inline
Definition at line 977 of file request.hh.
References Flags< T >::isSet().
isKernel()
bool Request::isKernel () const inline
Definition at line 897 of file request.hh.
References Flags< T >::isSet().
isLLSC()
bool Request::isLLSC () const inline
Definition at line 887 of file request.hh.
References Flags< T >::isSet().
isLockedRMW()
bool Request::isLockedRMW () const inline
Definition at line 889 of file request.hh.
References Flags< T >::isSet().
isMmappedIpr()
bool Request::isMmappedIpr () const inline
Definition at line 892 of file request.hh.
References Flags< T >::isSet().
isPrefetch()
bool Request::isPrefetch () const inline
Definition at line 884 of file request.hh.
References Flags< T >::isSet().
isPrefetchEx()
bool Request::isPrefetchEx () const inline
Definition at line 886 of file request.hh.
References Flags< T >::isSet().
isPriv()
bool Request::isPriv () const inline
Definition at line 888 of file request.hh.
References Flags< T >::isSet().
isPrivateSegment()
bool Request::isPrivateSegment () const inline
Definition at line 971 of file request.hh.
References Flags< T >::isSet().
isPTWalk()
bool Request::isPTWalk () const inline
Definition at line 894 of file request.hh.
References Flags< T >::isSet().
isReadonlySegment()
bool Request::isReadonlySegment () const inline
Definition at line 983 of file request.hh.
References Flags< T >::isSet().
isRelease()
bool Request::isRelease () const inline
Definition at line 896 of file request.hh.
References Flags< T >::isSet().
isScoped()
bool Request::isScoped () const inline
Accessor functions for the memory space configuration flags and used by GPU ISAs such as the Heterogeneous System Architecture (HSA).
Note that these are for testing only; setting extraFlags should be done via setMemSpaceConfigFlags().
Definition at line 925 of file request.hh.
References Flags< T >::isSet().
isSecure()
bool Request::isSecure () const inline
Definition at line 893 of file request.hh.
References Flags< T >::isSet().
isSpillSegment()
bool Request::isSpillSegment () const inline
Definition at line 989 of file request.hh.
References Flags< T >::isSet().
isStrictlyOrdered()
bool Request::isStrictlyOrdered () const inline
Definition at line 882 of file request.hh.
References Flags< T >::isSet().
isSwap()
bool Request::isSwap () const inline
Definition at line 890 of file request.hh.
References Flags< T >::isSet().
isSystemScope()
bool Request::isSystemScope () const inline
Definition at line 949 of file request.hh.
References Flags< T >::isSet().
isToPOC()
bool Request::isToPOC () const inline
Definition at line 916 of file request.hh.
References Flags< T >::isSet().
isToPOU()
bool Request::isToPOU () const inline
Accessor functions for the destination of a memory request.
The destination flag can specify a point of reference for the operation (e.g. a cache block clean to the the point of unification). At the moment the destination is only used by the cache maintenance operations.
Definition at line 915 of file request.hh.
References Flags< T >::isSet().
isUncacheable()
bool Request::isUncacheable () const inline
Accessor functions for flags.
Note that these are for testing only; setting flags should be done via setFlags().
Definition at line 881 of file request.hh.
References Flags< T >::isSet().
isWavefrontScope()
bool Request::isWavefrontScope () const inline
Definition at line 928 of file request.hh.
References Flags< T >::isSet().
isWorkgroupScope()
bool Request::isWorkgroupScope () const inline
Definition at line 935 of file request.hh.
References Flags< T >::isSet().
masterId()
MasterID Request::masterId () const inline
Accesssor for the requestor id.
Definition at line 718 of file request.hh.
setAccessLatency()
void Request::setAccessLatency () inline
Set/Get the time taken to complete this request's access, not including the time to successfully translate the request.
Definition at line 852 of file request.hh.
References curTick().
setAsid()
void Request::setAsid (uint64_t asid) inline
Accessor function for asid.
Definition at line 744 of file request.hh.
References ArmISA::asid.
setByteEnable()
void Request::setByteEnable (const std::vector< bool > & be) inline
Definition at line 646 of file request.hh.
References MipsISA::be.
setContext()
void Request::setContext (ContextID context_id) inline
Set up Context numbers.
Definition at line 503 of file request.hh.
References Flags< T >::set().
setExtraData()
void Request::setExtraData (uint64_t extraData) inline
Accessor function for store conditional return value.
Definition at line 774 of file request.hh.
References Flags< T >::set().
setFlags()
void Request::setFlags (Flags flags) inline
Note that unlike other accessors, this function sets specific flags (ORs them in); it does not assign its argument to the _flags field.
Thus this method should rightly be called setFlags() and not just flags().
Definition at line 689 of file request.hh.
References Flags< T >::isSet(), and Flags< T >::set().
setMemSpaceConfigFlags()
void Request::setMemSpaceConfigFlags (MemSpaceConfigFlags extraFlags) inline
Definition at line 696 of file request.hh.
References Flags< T >::isSet(), and Flags< T >::set().
setPaddr()
void Request::setPaddr (Addr paddr) inline
Set just the physical address.
This usually used to record the result of a translation. However, when using virtualized CPUs setPhys() is sometimes called to finalize a physical address without a virtual address, so we can't check if the virtual address is valid.
Definition at line 557 of file request.hh.
References Flags< T >::set().
setPC()
void Request::setPC (Addr pc) inline
Definition at line 815 of file request.hh.
References MipsISA::pc, and Flags< T >::set().
setPhys()
void Request::setPhys (Addr paddr, unsigned size, Flags flags, MasterID mid, Tick time) inline private
Set up a physical (e.g.
device) request in a previously allocated Request object.
Definition at line 295 of file request.hh.
setReqInstSeqNum()
void Request::setReqInstSeqNum (const InstSeqNum seq_num) inline
Definition at line 873 of file request.hh.
References Flags< T >::set().
setStreamId()
void Request::setStreamId (uint32_t sid) inline
Definition at line 510 of file request.hh.
References Flags< T >::set().
setSubStreamId()
void Request::setSubStreamId (uint32_t ssid) inline
Definition at line 517 of file request.hh.
References Flags< T >::isSet(), and Flags< T >::set().
setTranslateLatency()
void Request::setTranslateLatency () inline
Set/Get the time taken for this request to be successfully translated.
Definition at line 845 of file request.hh.
References curTick().
setVirt()
void Request::setVirt (uint64_t asid, Addr vaddr, unsigned size, Flags flags, MasterID mid, Addr pc, AtomicOpFunctorPtr amo_op = nullptr) inline
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
Definition at line 529 of file request.hh.
References ArmISA::asid, Flags< T >::clear(), curTick(), MipsISA::pc, Flags< T >::set(), and MipsISA::vaddr.
splitOnVaddr()
void Request::splitOnVaddr (Addr split_addr, RequestPtr & req1, RequestPtr & req2) inline
Generate two requests as if this request had been split into two pieces.
The original request can't have been translated already.
Definition at line 570 of file request.hh.
References Flags< T >::isSet(), and Flags< T >::noneSet().
streamId()
uint32_t Request::streamId () const inline
Definition at line 795 of file request.hh.
References Flags< T >::isSet().
substreamId()
uint32_t Request::substreamId () const inline
Definition at line 808 of file request.hh.
References Flags< T >::isSet().
taskId() [1/2]
uint32_t Request::taskId () const inline
Definition at line 724 of file request.hh.
taskId() [2/2]
void Request::taskId (uint32_t id) inline
Definition at line 730 of file request.hh.
References ArmISA::id.
time()
Tick Request::time () const inline
Accessor for time.
Definition at line 654 of file request.hh.
References Flags< T >::isSet().
Member Data Documentation
@117
union { ... }
_asid
uint64_t Request::_asid
The address space ID.
Definition at line 371 of file request.hh.
_byteEnable
std::vector<bool> Request::_byteEnable private
Byte-enable mask for writes.
Definition at line 324 of file request.hh.
_contextId
ContextID Request::_contextId private
The context ID (for statistics, locks, and wakeups).
Definition at line 383 of file request.hh.
_extraData
uint64_t Request::_extraData private
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
Definition at line 380 of file request.hh.
_flags
Flags Request::_flags private
Flag structure for the request.
Definition at line 332 of file request.hh.
_masterId
MasterID Request::_masterId private
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Definition at line 329 of file request.hh.
_memSpaceConfigFlags
MemSpaceConfigFlags Request::_memSpaceConfigFlags private
Memory space configuraiton flag structure for the request.
Definition at line 335 of file request.hh.
_paddr
Addr Request::_paddr private
The physical address of the request.
Valid only if validPaddr is set.
Definition at line 314 of file request.hh.
_pc
Addr Request::_pc private
program counter of initiating access; for tracing/debugging
Definition at line 386 of file request.hh.
_reqInstSeqNum
InstSeqNum Request::_reqInstSeqNum private
Sequence number of the instruction that creates the request.
Definition at line 389 of file request.hh.
_size
unsigned Request::_size private
The size of the request.
This field must be set when vaddr or paddr is written via setVirt() or setPhys(), so it is always valid as long as one of the address fields is valid.
Definition at line 321 of file request.hh.
_streamId
uint32_t Request::_streamId
The stream ID uniquely identifies a device behind the SMMU/IOMMU Each transaction arriving at the SMMU/IOMMU is associated with exactly one stream ID.
Definition at line 359 of file request.hh.
_substreamId
uint32_t Request::_substreamId
The substream ID identifies an "execution context" within a device behind an SMMU/IOMMU.
It's intended to map 1-to-1 to PCIe PASID (Process Address Space ID). The presence of a substream ID is optional.
Definition at line 367 of file request.hh.
_taskId
uint32_t Request::_taskId private
The task id associated with this request.
Definition at line 350 of file request.hh.
_time
Tick Request::_time private
The time this request was started.
Used to calculate latencies. This field is set to curTick() any time paddr or vaddr is written.
Definition at line 345 of file request.hh.
_vaddr
Addr Request::_vaddr private
The virtual address of the request.
Definition at line 375 of file request.hh.
accessDelta
Tick Request::accessDelta
Access latency to complete this memory transaction not including translation time.
Definition at line 615 of file request.hh.
atomicOpFunctor
AtomicOpFunctorPtr Request::atomicOpFunctor private
A pointer to an atomic operation.
Definition at line 392 of file request.hh.
Referenced by Request().
depth
int Request::depth mutable
Level of the cache hierachy where this request was responded to (e.g.
0 = L1; 1 = L2).
Definition at line 621 of file request.hh.
privateFlags
PrivateFlags Request::privateFlags private
Private flags for field validity checking.
Definition at line 338 of file request.hh.
STORE_NO_DATA
const FlagsType Request::STORE_NO_DATA static
Initial value:
= CACHE_BLOCK_ZERO |
        CLEAN | INVALIDATE
Definition at line 205 of file request.hh.
Referenced by Minor::LSQ::pushRequest(), LSQUnit< Impl >::write(), AtomicSimpleCPU::writeMem(), TimingSimpleCPU::writeMem(), and CheckerCPU::writeMem().
translateDelta
Tick Request::translateDelta
Time for the TLB/table walker to successfully translate this request.
Definition at line 609 of file request.hh.
The documentation for this class was generated from the following file:
mem/request.hh