gem5: ImageFileData Class Reference
ImageFileData Class Reference
#include <image_file_data.hh>
Public Member Functions
const std::string & filename () const
uint8_t const * data () const
size_t len () const
ImageFileData (const std::string &f_name)
virtual ~ImageFileData ()
Private Attributes
std::string _filename
uint8_t * _data
size_t _len
Detailed Description
Definition at line 39 of file image_file_data.hh.
Constructor & Destructor Documentation
ImageFileData()
ImageFileData::ImageFileData (const std::string & f_name)
Definition at line 101 of file image_file_data.cc.
References _data, _filename, _len, doGzipLoad(), fatal_if, ArmISA::fd, hasGzipMagic(), and panic_if.
Referenced by len().
~ImageFileData()
ImageFileData::~ImageFileData () virtual
Definition at line 127 of file image_file_data.cc.
References _data, and _len.
Referenced by len().
Member Function Documentation
data()
uint8_t const* ImageFileData::data () const inline
Definition at line 48 of file image_file_data.hh.
References _data.
Referenced by TEST().
filename()
const std::string& ImageFileData::filename () const inline
Definition at line 47 of file image_file_data.hh.
References _filename.
Referenced by TEST().
len()
size_t ImageFileData::len () const inline
Definition at line 49 of file image_file_data.hh.
References _len, ImageFileData(), and ~ImageFileData().
Referenced by TEST().
Member Data Documentation
_data
uint8_t* ImageFileData::_data private
Definition at line 43 of file image_file_data.hh.
Referenced by data(), ImageFileData(), and ~ImageFileData().
_filename
std::string ImageFileData::_filename private
Definition at line 42 of file image_file_data.hh.
Referenced by filename(), and ImageFileData().
_len
size_t ImageFileData::_len private
Definition at line 44 of file image_file_data.hh.
Referenced by ImageFileData(), len(), and ~ImageFileData().
The documentation for this class was generated from the following files:
base/loader/image_file_data.hh
base/loader/image_file_data.cc