gem5: SerialLink::SerialLinkSlavePort Class Reference
SerialLink::SerialLinkSlavePort Class Reference
The port on the side that receives requests and sends responses.
#include <serial_link.hh>
Public Member Functions
SerialLinkSlavePort (const std::string &_name, SerialLink &_serial_link, SerialLinkMasterPort &_masterPort, Cycles _delay, int _resp_limit, const std::vector< AddrRange > &_ranges)
Constructor for the SerialLinkSlavePort.
void schedTimingResp (PacketPtr pkt, Tick when)
Queue a response packet to be sent out later and also schedule a send if necessary.
void retryStalledReq ()
Retry any stalled request that we have failed to accept at an earlier point in time.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
bool recvTimingReq (PacketPtr pkt)
When receiving a timing request from the peer port, pass it to the serial_link.
void recvRespRetry ()
When receiving a retry request from the peer port, pass it to the serial_link.
Tick recvAtomic (PacketPtr pkt)
When receiving a Atomic requestfrom the peer port, pass it to the serial_link.
void recvFunctional (PacketPtr pkt)
When receiving a Functional request from the peer port, pass it to the serial_link.
AddrRangeList getAddrRanges () const
When receiving a address range request the peer port, pass it to the serial_link.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Member Functions
bool respQueueFull () const
Is this side blocked from accepting new response packets.
void trySendTiming ()
Handle send event, scheduled when the packet at the head of the response queue is ready to transmit (for timing accesses only).
Private Attributes
SerialLink & serial_link
The serial_link to which this port belongs.
SerialLinkMasterPort & masterPort
Master port on the other side of the serial_link.
const Cycles delay
Minimum request delay though this serial_link.
const AddrRangeList ranges
Address ranges to pass through the serial_link.
std::deque< DeferredPacket > transmitList
Response packet queue.
unsigned int outstandingResponses
Counter to track the outstanding responses.
bool retryReq
If we should send a retry when space becomes available.
unsigned int respQueueLimit
Max queue size for reserved responses.
EventFunctionWrapper sendEvent
Send event for the response queue.
Additional Inherited Members
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
The port on the side that receives requests and sends responses.
The slave port has a set of address ranges that it is responsible for. The slave port also has a buffer for the responses not yet sent.
Definition at line 99 of file serial_link.hh.
Constructor & Destructor Documentation
SerialLinkSlavePort()
SerialLink::SerialLinkSlavePort::SerialLinkSlavePort (const std::string & _name, SerialLink & _serial_link, SerialLinkMasterPort & _masterPort, Cycles _delay, int _resp_limit, const std::vector< AddrRange > & _ranges)
Constructor for the SerialLinkSlavePort.
Parameters
_name the port name including the owner
_serial_link the structural owner
_masterPort the master port on the other side of the serial_link
_delay the delay in cycles from receiving to sending
_resp_limit the size of the response queue
_ranges a number of address ranges to forward
Definition at line 59 of file serial_link.cc.
References trySendTiming().
Member Function Documentation
getAddrRanges()
AddrRangeList SerialLink::SerialLinkSlavePort::getAddrRanges () const protected virtual
When receiving a address range request the peer port, pass it to the serial_link.
Implements SlavePort.
Definition at line 423 of file serial_link.cc.
References SerialLink::SerialLink().
recvAtomic()
Tick SerialLink::SerialLinkSlavePort::recvAtomic (PacketPtr pkt) protected virtual
When receiving a Atomic requestfrom the peer port, pass it to the serial_link.
Implements AtomicResponseProtocol.
Definition at line 376 of file serial_link.cc.
References SerialLink::masterPort, and MasterPort::sendAtomic().
recvFunctional()
void SerialLink::SerialLinkSlavePort::recvFunctional (PacketPtr pkt) protected virtual
When receiving a Functional request from the peer port, pass it to the serial_link.
Implements FunctionalResponseProtocol.
Definition at line 382 of file serial_link.cc.
References ArmISA::i, Packet::makeResponse(), SerialLink::masterPort, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), MasterPort::sendFunctional(), SerialLink::SerialLinkMasterPort::trySatisfyFunctional(), and Packet::trySatisfyFunctional().
recvRespRetry()
void SerialLink::SerialLinkSlavePort::recvRespRetry () protected virtual
When receiving a retry request from the peer port, pass it to the serial_link.
Implements TimingResponseProtocol.
Definition at line 370 of file serial_link.cc.
recvTimingReq()
bool SerialLink::SerialLinkSlavePort::recvTimingReq (PacketPtr pkt) protected virtual
When receiving a timing request from the peer port, pass it to the serial_link.
Implements TimingResponseProtocol.
Definition at line 165 of file serial_link.cc.
References Packet::cacheResponding(), Packet::cmdString(), divCeil(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::headerDelay, SerialLink::masterPort, Packet::needsResponse(), Packet::payloadDelay, SerialLink::SerialLinkMasterPort::reqQueueFull(), SerialLink::SerialLinkMasterPort::schedTimingReq(), and ArmISA::t.
respQueueFull()
bool SerialLink::SerialLinkSlavePort::respQueueFull () const private
Is this side blocked from accepting new response packets.
Returns
true if the reserved space has reached the set limit
Definition at line 120 of file serial_link.cc.
retryStalledReq()
void SerialLink::SerialLinkSlavePort::retryStalledReq ()
Retry any stalled request that we have failed to accept at an earlier point in time.
This call will do nothing if no request is waiting.
Definition at line 232 of file serial_link.cc.
References DPRINTF.
Referenced by SerialLink::SerialLinkMasterPort::trySendTiming().
schedTimingResp()
void SerialLink::SerialLinkSlavePort::schedTimingResp (PacketPtr pkt, Tick when)
Queue a response packet to be sent out later and also schedule a send if necessary.
Parameters
pkt a response to send out after a delay
when tick when response packet should be sent
Definition at line 259 of file serial_link.cc.
References ArmISA::sendEvent().
Referenced by SerialLink::SerialLinkMasterPort::recvTimingResp().
trySendTiming()
void SerialLink::SerialLinkSlavePort::trySendTiming () private
Handle send event, scheduled when the packet at the head of the response queue is ready to transmit (for timing accesses only).
Definition at line 316 of file serial_link.cc.
References curTick(), divCeil(), DPRINTF, Packet::getAddr(), Packet::getSize(), SerialLink::masterPort, SerialLink::SerialLinkMasterPort::reqQueueFull(), ArmISA::sendEvent(), ArmISA::t, and SerialLink::DeferredPacket::tick.
Referenced by SerialLinkSlavePort().
Member Data Documentation
delay
const Cycles SerialLink::SerialLinkSlavePort::delay private
Minimum request delay though this serial_link.
Definition at line 113 of file serial_link.hh.
masterPort
SerialLinkMasterPort& SerialLink::SerialLinkSlavePort::masterPort private
Master port on the other side of the serial_link.
Definition at line 110 of file serial_link.hh.
outstandingResponses
unsigned int SerialLink::SerialLinkSlavePort::outstandingResponses private
Counter to track the outstanding responses.
Definition at line 127 of file serial_link.hh.
ranges
const AddrRangeList SerialLink::SerialLinkSlavePort::ranges private
Address ranges to pass through the serial_link.
Definition at line 116 of file serial_link.hh.
respQueueLimit
unsigned int SerialLink::SerialLinkSlavePort::respQueueLimit private
Max queue size for reserved responses.
Definition at line 133 of file serial_link.hh.
retryReq
bool SerialLink::SerialLinkSlavePort::retryReq private
If we should send a retry when space becomes available.
Definition at line 130 of file serial_link.hh.
sendEvent
EventFunctionWrapper SerialLink::SerialLinkSlavePort::sendEvent private
Send event for the response queue.
Definition at line 150 of file serial_link.hh.
serial_link
SerialLink& SerialLink::SerialLinkSlavePort::serial_link private
The serial_link to which this port belongs.
Definition at line 105 of file serial_link.hh.
transmitList
std::deque<DeferredPacket> SerialLink::SerialLinkSlavePort::transmitList private
Response packet queue.
Response packets are held in this queue for a specified delay to model the processing delay of the serial_link. We use a deque as we need to iterate over the items for functional accesses.
Definition at line 124 of file serial_link.hh.
The documentation for this class was generated from the following files:
mem/serial_link.hh
mem/serial_link.cc