gem5: Iob Class Reference
Iob Class Reference
#include <iob.hh>
Classes
struct IntBusy
struct IntCtl
struct IntMan
Public Types
typedef IobParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Iob (const Params *p)
const Params * params () const
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void generateIpi (Type type, int cpu_id, int vector)
void receiveDeviceInterrupt (DeviceId devid)
bool receiveJBusInterrupt (int cpu_id, int source, uint64_t d0, uint64_t d1)
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Types
enum DeviceId {
Interal = 0, Error = 1, SSI = 2, Reserved = 3,
NumDeviceIds
}
enum Type { Interrupt, Reset, Idle, Resume }
Private Member Functions
void writeIob (PacketPtr pkt)
void writeJBus (PacketPtr pkt)
void readIob (PacketPtr pkt)
void readJBus (PacketPtr pkt)
Private Attributes
IntrControl * ic
Addr iobManAddr
Addr iobManSize
Addr iobJBusAddr
Addr iobJBusSize
Tick pioDelay
IntMan intMan [NumDeviceIds]
IntCtl intCtl [NumDeviceIds]
uint64_t jIntVec
uint64_t jBusData0 [MaxNiagaraProcs]
uint64_t jBusData1 [MaxNiagaraProcs]
IntBusy jIntBusy [MaxNiagaraProcs]
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 73 of file iob.hh.
Member Typedef Documentation
Params
typedef IobParams Iob::Params
Definition at line 126 of file iob.hh.
Member Enumeration Documentation
DeviceId
enum Iob::DeviceId private
Enumerator
Interal
Error
SSI
Reserved
NumDeviceIds
Definition at line 83 of file iob.hh.
Type
enum Iob::Type private
Enumerator
Interrupt
Reset
Idle
Resume
Definition at line 106 of file iob.hh.
Constructor & Destructor Documentation
Iob()
Iob::Iob (const Params * p)
Definition at line 56 of file iob.cc.
References Iob::IntMan::cpu, intCtl, intMan, iobJBusAddr, iobJBusSize, iobManAddr, iobManSize, Iob::IntCtl::mask, MaxNiagaraProcs, NumDeviceIds, params(), Iob::IntCtl::pend, pioDelay, X86ISA::system, ULL, Iob::IntMan::vector, and X86ISA::x.
Referenced by unserialize().
Member Function Documentation
generateIpi()
void Iob::generateIpi (Type type, int cpu_id, int vector)
Definition at line 278 of file iob.cc.
References DPRINTF, ic, SparcISA::SparcFaultBase::invoke(), SparcISA::IT_INT_VEC, System::numContexts(), panic, IntrControl::post(), PioDevice::sys, System::threadContexts, SparcISA::SparcFault< T >::trapType(), and warn.
Referenced by params(), and writeIob().
getAddrRanges()
AddrRangeList Iob::getAddrRanges () const override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 331 of file iob.cc.
References iobJBusAddr, iobJBusSize, iobManAddr, iobManSize, and RangeSize().
Referenced by params().
params()
const Params* Iob::params () const inline
Definition at line 130 of file iob.hh.
References SimObject::_params, generateIpi(), getAddrRanges(), read(), receiveDeviceInterrupt(), receiveJBusInterrupt(), serialize(), type, unserialize(), Iob::IntMan::vector, and write().
Referenced by Iob().
read()
Tick Iob::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 77 of file iob.cc.
References Packet::getAddr(), iobJBusAddr, iobJBusSize, iobManAddr, iobManSize, Packet::makeAtomicResponse(), panic, pioDelay, readIob(), and readJBus().
Referenced by params().
readIob()
void Iob::readIob (PacketPtr pkt) private
Definition at line 92 of file iob.cc.
References Iob::IntMan::cpu, data, Packet::getAddr(), MipsISA::index, intCtl, IntCtlAddr, IntCtlSize, intMan, IntManAddr, IntManSize, iobManAddr, jIntVec, JIntVecAddr, Iob::IntCtl::mask, panic, Iob::IntCtl::pend, Packet::setBE(), and Iob::IntMan::vector.
Referenced by read().
readJBus()
void Iob::readJBus (PacketPtr pkt) private
Definition at line 121 of file iob.cc.
References Iob::IntBusy::busy, MipsISA::cpuid, data, Packet::getAddr(), MipsISA::index, iobJBusAddr, jBusData0, jBusData1, JIntABusyAddr, jIntBusy, JIntBusyAddr, JIntBusySize, JIntData0Addr, JIntData1Addr, JIntDataA0Addr, JIntDataA1Addr, panic, Packet::req, Packet::setBE(), and Iob::IntBusy::source.
Referenced by read().
receiveDeviceInterrupt()
void Iob::receiveDeviceInterrupt (DeviceId devid)
Definition at line 264 of file iob.cc.
References DPRINTF, ic, intCtl, intMan, SparcISA::IT_INT_VEC, ArmISA::mask, Iob::IntCtl::mask, NumDeviceIds, Iob::IntCtl::pend, IntrControl::post(), and X86ISA::vector.
Referenced by params().
receiveJBusInterrupt()
bool Iob::receiveJBusInterrupt (int cpu_id, int source, uint64_t d0, uint64_t d1)
Definition at line 311 of file iob.cc.
References Iob::IntBusy::busy, DPRINTF, ic, SparcISA::IT_INT_VEC, jBusData0, jBusData1, jIntBusy, jIntVec, IntrControl::post(), and Iob::IntBusy::source.
Referenced by params().
serialize()
void Iob::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 341 of file iob.cc.
References csprintf(), intCtl, intMan, jBusData0, jBusData1, jIntBusy, jIntVec, ArmISA::mask, MaxNiagaraProcs, NumDeviceIds, paramOut(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, X86ISA::vector, and X86ISA::x.
Referenced by params().
unserialize()
void Iob::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 362 of file iob.cc.
References csprintf(), intCtl, intMan, Iob(), jBusData0, jBusData1, jIntBusy, jIntVec, ArmISA::mask, MaxNiagaraProcs, NumDeviceIds, paramIn(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, X86ISA::vector, and X86ISA::x.
Referenced by params().
write()
Tick Iob::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 171 of file iob.cc.
References Packet::getAddr(), iobJBusAddr, iobJBusSize, iobManAddr, iobManSize, Packet::makeAtomicResponse(), panic, pioDelay, writeIob(), and writeJBus().
Referenced by params().
writeIob()
void Iob::writeIob (PacketPtr pkt) private
Definition at line 186 of file iob.cc.
References bits(), Iob::IntMan::cpu, data, DPRINTF, generateIpi(), Packet::getAddr(), Packet::getBE(), MipsISA::index, intCtl, IntCtlAddr, IntCtlSize, intMan, IntManAddr, IntManSize, IntVecDisAddr, IntVecDisSize, iobManAddr, jIntVec, JIntVecAddr, Iob::IntCtl::mask, panic, Iob::IntCtl::pend, type, X86ISA::vector, and Iob::IntMan::vector.
Referenced by write().
writeJBus()
void Iob::writeJBus (PacketPtr pkt) private
Definition at line 237 of file iob.cc.
References bits(), Iob::IntBusy::busy, MipsISA::cpuid, data, DPRINTF, Packet::getAddr(), Packet::getBE(), MipsISA::index, iobJBusAddr, JIntABusyAddr, jIntBusy, JIntBusyAddr, JIntBusySize, panic, and Packet::req.
Referenced by write().
Member Data Documentation
ic
IntrControl* Iob::ic private
Definition at line 76 of file iob.hh.
Referenced by generateIpi(), receiveDeviceInterrupt(), and receiveJBusInterrupt().
intCtl
IntCtl Iob::intCtl[NumDeviceIds] private
Definition at line 114 of file iob.hh.
Referenced by Iob(), readIob(), receiveDeviceInterrupt(), serialize(), unserialize(), and writeIob().
intMan
IntMan Iob::intMan[NumDeviceIds] private
Definition at line 113 of file iob.hh.
Referenced by Iob(), readIob(), receiveDeviceInterrupt(), serialize(), unserialize(), and writeIob().
iobJBusAddr
Addr Iob::iobJBusAddr private
Definition at line 79 of file iob.hh.
Referenced by getAddrRanges(), Iob(), read(), readJBus(), write(), and writeJBus().
iobJBusSize
Addr Iob::iobJBusSize private
Definition at line 80 of file iob.hh.
Referenced by getAddrRanges(), Iob(), read(), and write().
iobManAddr
Addr Iob::iobManAddr private
Definition at line 77 of file iob.hh.
Referenced by getAddrRanges(), Iob(), read(), readIob(), write(), and writeIob().
iobManSize
Addr Iob::iobManSize private
Definition at line 78 of file iob.hh.
Referenced by getAddrRanges(), Iob(), read(), and write().
jBusData0
uint64_t Iob::jBusData0[MaxNiagaraProcs] private
Definition at line 116 of file iob.hh.
Referenced by readJBus(), receiveJBusInterrupt(), serialize(), and unserialize().
jBusData1
uint64_t Iob::jBusData1[MaxNiagaraProcs] private
Definition at line 117 of file iob.hh.
Referenced by readJBus(), receiveJBusInterrupt(), serialize(), and unserialize().
jIntBusy
IntBusy Iob::jIntBusy[MaxNiagaraProcs] private
Definition at line 118 of file iob.hh.
Referenced by readJBus(), receiveJBusInterrupt(), serialize(), unserialize(), and writeJBus().
jIntVec
uint64_t Iob::jIntVec private
Definition at line 115 of file iob.hh.
Referenced by readIob(), receiveJBusInterrupt(), serialize(), unserialize(), and writeIob().
pioDelay
Tick Iob::pioDelay private
Definition at line 81 of file iob.hh.
Referenced by Iob(), read(), and write().
The documentation for this class was generated from the following files:
dev/sparc/iob.hh
dev/sparc/iob.cc