gem5: tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process Class Reference
tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process Class Reference
Classes
struct mm_end_event_ext
class process_handle_class
class process_handle_list
Public Types
typedef sync_enum_type(MODULE::* NBTransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* BTransportPtr) (transaction_type &, sc_core::sc_time &)
typedef unsigned int(MODULE::* TransportDbgPtr) (transaction_type &)
typedef bool(MODULE::* GetDirectMemPtr) (transaction_type &, tlm::tlm_dmi &)
Public Member Functions
fw_process (simple_target_socket_b *p_own)
void start_of_simulation ()
void set_nb_transport_ptr (MODULE *mod, NBTransportPtr p)
void set_b_transport_ptr (MODULE *mod, BTransportPtr p)
void set_transport_dbg_ptr (MODULE *mod, TransportDbgPtr p)
void set_get_direct_mem_ptr (MODULE *mod, GetDirectMemPtr p)
sync_enum_type nb_transport_fw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void b_transport (transaction_type &trans, sc_core::sc_time &t)
unsigned int transport_dbg (transaction_type &trans)
bool get_direct_mem_ptr (transaction_type &trans, tlm::tlm_dmi &dmi_data)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Public Member Functions inherited from tlm::tlm_mm_interface
virtual ~tlm_mm_interface ()
Private Member Functions
void nb2b_thread (process_handle_class *h)
void b2nb_thread ()
void free (tlm::tlm_generic_payload *trans)
Private Attributes
process_handle_list m_process_handle
simple_target_socket_b * m_owner
MODULE * m_mod
NBTransportPtr m_nb_transport_ptr
BTransportPtr m_b_transport_ptr
TransportDbgPtr m_transport_dbg_ptr
GetDirectMemPtr m_get_direct_mem_ptr
peq_with_get< transaction_type > m_peq
bool m_response_in_progress
sc_core::sc_event m_end_response
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process
Definition at line 176 of file simple_target_socket.h.
Member Typedef Documentation
BTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::BTransportPtr) (transaction_type &, sc_core::sc_time &)
Definition at line 182 of file simple_target_socket.h.
GetDirectMemPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef bool(MODULE::* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::GetDirectMemPtr) (transaction_type &, tlm::tlm_dmi &)
Definition at line 185 of file simple_target_socket.h.
NBTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::NBTransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 180 of file simple_target_socket.h.
TransportDbgPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef unsigned int(MODULE::* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::TransportDbgPtr) (transaction_type &)
Definition at line 184 of file simple_target_socket.h.
Constructor & Destructor Documentation
fw_process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::fw_process (simple_target_socket_b * p_own) inline
Definition at line 188 of file simple_target_socket.h.
Member Function Documentation
b2nb_thread()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread () inline private
Definition at line 473 of file simple_target_socket.h.
References tlm::BEGIN_REQ, tlm::BEGIN_RESP, tlm_utils::convenience_socket_base::display_error(), tlm::END_REQ, tlm::END_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_current_transaction, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_end_request, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans, sc_assert, sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, tlm::TLM_UPDATED, and sc_core::wait().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
b_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport (transaction_type & trans, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_blocking_transport_if< TYPES::tlm_payload_type >.
Definition at line 309 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_error(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext::done, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans, sc_assert, sc_core::SC_ZERO_TIME, and sc_core::wait().
free()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free (tlm::tlm_generic_payload * trans) inline private virtual
Implements tlm::tlm_mm_interface.
Definition at line 544 of file simple_target_socket.h.
References tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext::done, ArmISA::ext, sc_core::sc_event::notify(), tlm::tlm_generic_payload::reset(), and sc_assert.
get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::get_direct_mem_ptr (transaction_type & trans, tlm::tlm_dmi & dmi_data) inline virtual
Implements tlm::tlm_fw_direct_mem_if< TYPES::tlm_payload_type >.
Definition at line 367 of file simple_target_socket.h.
References tlm::tlm_dmi::allow_read_write(), sc_assert, tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
nb2b_thread()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread (process_handle_class * h) inline private
Definition at line 440 of file simple_target_socket.h.
References tlm::BEGIN_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_nb_transport(), tlm::END_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_suspend, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_trans, sc_assert, sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_COMPLETED, tlm::TLM_UPDATED, and sc_core::wait().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw().
nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_fw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 262 of file simple_target_socket.h.
References tlm::BEGIN_REQ, tlm_utils::convenience_socket_base::display_error(), sc_core::sc_spawn_options::dont_initialize(), tlm::END_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_e, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), sc_core::sc_event::notify(), sc_assert, sc_core::sc_bind(), sc_core::sc_gen_unique_name(), sc_core::sc_spawn(), sc_core::sc_spawn_options::set_sensitivity(), ArmISA::t, tlm::TLM_ACCEPTED, and tlm::TLM_COMPLETED.
set_b_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr (MODULE * mod, BTransportPtr p) inline
Definition at line 223 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport().
set_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr (MODULE * mod, GetDirectMemPtr p) inline
Definition at line 248 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr().
set_nb_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr (MODULE * mod, NBTransportPtr p) inline
Definition at line 210 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw().
set_transport_dbg_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr (MODULE * mod, TransportDbgPtr p) inline
Definition at line 236 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg().
start_of_simulation()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation () inline
Definition at line 197 of file simple_target_socket.h.
References tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), sc_core::sc_spawn_options::dont_initialize(), sc_core::sc_bind(), sc_core::sc_gen_unique_name(), sc_core::sc_spawn(), and sc_core::sc_spawn_options::set_sensitivity().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::start_of_simulation().
transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::transport_dbg (transaction_type & trans) inline virtual
Implements tlm::tlm_transport_dbg_if< TYPES::tlm_payload_type >.
Definition at line 355 of file simple_target_socket.h.
References sc_assert.
Member Data Documentation
m_b_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> BTransportPtr tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_b_transport_ptr private
Definition at line 567 of file simple_target_socket.h.
m_end_response
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sc_core::sc_event tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_end_response private
Definition at line 572 of file simple_target_socket.h.
m_get_direct_mem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> GetDirectMemPtr tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_get_direct_mem_ptr private
Definition at line 569 of file simple_target_socket.h.
m_mod
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> MODULE* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_mod private
Definition at line 565 of file simple_target_socket.h.
m_nb_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> NBTransportPtr tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_nb_transport_ptr private
Definition at line 566 of file simple_target_socket.h.
m_owner
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> simple_target_socket_b* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_owner private
Definition at line 564 of file simple_target_socket.h.
m_peq
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> peq_with_get<transaction_type> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_peq private
Definition at line 570 of file simple_target_socket.h.
m_process_handle
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> process_handle_list tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_process_handle private
Definition at line 437 of file simple_target_socket.h.
m_response_in_progress
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_response_in_progress private
Definition at line 571 of file simple_target_socket.h.
m_transport_dbg_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> TransportDbgPtr tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_transport_dbg_ptr private
Definition at line 568 of file simple_target_socket.h.
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/simple_target_socket.h