gem5: BaseGicRegisters Class Reference
BaseGicRegisters Class Reference abstract
#include <base_gic.hh>
Public Member Functions
virtual uint32_t readDistributor (ContextID ctx, Addr daddr)=0
virtual uint32_t readCpu (ContextID ctx, Addr daddr)=0
virtual void writeDistributor (ContextID ctx, Addr daddr, uint32_t data)=0
virtual void writeCpu (ContextID ctx, Addr daddr, uint32_t data)=0
Detailed Description
Definition at line 119 of file base_gic.hh.
Member Function Documentation
readCpu()
virtual uint32_t BaseGicRegisters::readCpu (ContextID ctx, Addr daddr) pure virtual
Implemented in GicV2, and KvmKernelGicV2.
Referenced by MuxingKvmGic::copyCpuRegister().
readDistributor()
virtual uint32_t BaseGicRegisters::readDistributor (ContextID ctx, Addr daddr) pure virtual
Implemented in GicV2, and KvmKernelGicV2.
Referenced by MuxingKvmGic::copyDistRegister().
writeCpu()
virtual void BaseGicRegisters::writeCpu (ContextID ctx, Addr daddr, uint32_t data) pure virtual
Implemented in GicV2, and KvmKernelGicV2.
Referenced by MuxingKvmGic::copyCpuRegister().
writeDistributor()
virtual void BaseGicRegisters::writeDistributor (ContextID ctx, Addr daddr, uint32_t data) pure virtual
Implemented in GicV2, and KvmKernelGicV2.
Referenced by MuxingKvmGic::clearBankedDistRange(), MuxingKvmGic::clearDistRange(), and MuxingKvmGic::copyDistRegister().
The documentation for this class was generated from the following file:
dev/arm/base_gic.hh