gem5: TraceCPU::ElasticDataGen::InputStream Class Reference
TraceCPU::ElasticDataGen::InputStream Class Reference
The InputStream encapsulates a trace file and the internal buffers and populates GraphNodes based on the input.
Public Member Functions
InputStream (const std::string &filename, const double time_multiplier)
Create a trace input stream for a given file name.
void reset ()
Reset the stream such that it can be played once again.
bool read (GraphNode *element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
uint32_t getWindowSize () const
Get window size from trace.
uint64_t getMicroOpCount () const
Get number of micro-ops modelled in the TraceCPU replay.
Private Attributes
ProtoInputStream trace
Input file stream for the protobuf trace.
const double timeMultiplier
A multiplier for the compute delays in the trace to modulate the Trace CPU frequency either up or down.
uint64_t microOpCount
Count of committed ops read from trace plus the filtered ops.
uint32_t windowSize
The window size that is read from the header of the protobuf trace and used to process the dependency trace.
Detailed Description
The InputStream encapsulates a trace file and the internal buffers and populates GraphNodes based on the input.
Definition at line 795 of file trace_cpu.hh.
Constructor & Destructor Documentation
InputStream()
TraceCPU::ElasticDataGen::InputStream::InputStream (const std::string & filename, const double time_multiplier)
Create a trace input stream for a given file name.
Parameters
filename Path to the file to read from
time_multiplier used to scale the compute delays
Definition at line 1258 of file trace_cpu.cc.
References SimClock::Frequency, panic, ProtoInputStream::read(), trace, and windowSize.
Member Function Documentation
getMicroOpCount()
uint64_t TraceCPU::ElasticDataGen::InputStream::getMicroOpCount () const inline
Get number of micro-ops modelled in the TraceCPU replay.
Definition at line 851 of file trace_cpu.hh.
getWindowSize()
uint32_t TraceCPU::ElasticDataGen::InputStream::getWindowSize () const inline
Get window size from trace.
Definition at line 848 of file trace_cpu.hh.
read()
bool TraceCPU::ElasticDataGen::InputStream::read (GraphNode * element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
Parameters
element Trace element to populate
size of register dependency array stored in the element
Returns
True if an element could be read successfully
Definition at line 1288 of file trace_cpu.cc.
References TraceCPU::ElasticDataGen::GraphNode::asid, TraceCPU::ElasticDataGen::GraphNode::clearRegDep(), TraceCPU::ElasticDataGen::GraphNode::clearRobDep(), TraceCPU::ElasticDataGen::GraphNode::compDelay, TraceCPU::ElasticDataGen::GraphNode::flags, ArmISA::i, ArmISA::j, ArmISA::MaxInstSrcRegs, TraceCPU::ElasticDataGen::GraphNode::maxRobDep, microOpCount, TraceCPU::ElasticDataGen::GraphNode::numRegDep, TraceCPU::ElasticDataGen::GraphNode::numRobDep, TraceCPU::ElasticDataGen::GraphNode::pc, TraceCPU::ElasticDataGen::GraphNode::physAddr, ProtoInputStream::read(), TraceCPU::ElasticDataGen::GraphNode::regDep, TraceCPU::ElasticDataGen::GraphNode::robDep, TraceCPU::ElasticDataGen::GraphNode::robNum, TraceCPU::ElasticDataGen::GraphNode::seqNum, TraceCPU::ElasticDataGen::GraphNode::size, timeMultiplier, trace, TraceCPU::ElasticDataGen::GraphNode::type, and TraceCPU::ElasticDataGen::GraphNode::virtAddr.
Referenced by TraceCPU::FixedRetryGen::nextExecute().
reset()
void TraceCPU::ElasticDataGen::InputStream::reset ()
Reset the stream such that it can be played once again.
Definition at line 1282 of file trace_cpu.cc.
References ProtoInputStream::reset(), and trace.
Referenced by TraceCPU::FixedRetryGen::exit().
Member Data Documentation
microOpCount
uint64_t TraceCPU::ElasticDataGen::InputStream::microOpCount private
Count of committed ops read from trace plus the filtered ops.
Definition at line 812 of file trace_cpu.hh.
Referenced by read().
timeMultiplier
const double TraceCPU::ElasticDataGen::InputStream::timeMultiplier private
A multiplier for the compute delays in the trace to modulate the Trace CPU frequency either up or down.
The Trace CPU's clock domain frequency must also be set to match the expected result of frequency scaling.
Definition at line 809 of file trace_cpu.hh.
Referenced by read().
trace
ProtoInputStream TraceCPU::ElasticDataGen::InputStream::trace private
Input file stream for the protobuf trace.
Definition at line 801 of file trace_cpu.hh.
Referenced by InputStream(), read(), and reset().
windowSize
uint32_t TraceCPU::ElasticDataGen::InputStream::windowSize private
The window size that is read from the header of the protobuf trace and used to process the dependency trace.
Definition at line 818 of file trace_cpu.hh.
Referenced by InputStream().
The documentation for this class was generated from the following files:
cpu/trace/trace_cpu.hh
cpu/trace/trace_cpu.cc