gem5: Fiber Class Reference
Fiber Class Reference abstract
This class represents a fiber, which is a light weight sort of thread which is cooperatively scheduled and runs sequentially with other fibers, swapping in and out of a single actual thread of execution.
#include <fiber.hh>
Public Member Functions
Fiber (size_t stack_size=DefaultStackSize)
stack_size is the size of the stack available to this fiber.
Fiber (Fiber *link, size_t stack_size=DefaultStackSize)
virtual ~Fiber ()
void run ()
Start executing the fiber represented by this object.
bool finished () const
Returns whether the "main" function of this fiber has finished.
bool started () const
Returns whether the "main" function of this fiber has started.
Static Public Member Functions
static Fiber * currentFiber ()
Get a pointer to the current running Fiber.
static Fiber * primaryFiber ()
Get a pointer to the primary Fiber.
Static Public Attributes
static const size_t DefaultStackSize = 0x50000
Protected Member Functions
virtual void main ()=0
This method is called when this fiber is first run.
void setStarted ()
Private Member Functions
void start ()
void createContext ()
Static Private Member Functions
static void entryTrampoline ()
Private Attributes
ucontext_t ctx
Fiber * link
void * stack
size_t stackSize
void * guardPage
size_t guardPageSize
bool _started
bool _finished
Detailed Description
This class represents a fiber, which is a light weight sort of thread which is cooperatively scheduled and runs sequentially with other fibers, swapping in and out of a single actual thread of execution.
To define your own threads, create a subclass of Fiber and override its main() function to do what you want your fiber to do. You can start it by calling its run() method which will stop your execution and start the other fiber in your place.
If your main() function ends, that fiber will automatically switch to either the primary fiber, or to a particular fiber you specified at construction time, and your fiber is considered finished.
Definition at line 64 of file fiber.hh.
Constructor & Destructor Documentation
Fiber() [1/2]
Fiber::Fiber (size_t stack_size = DefaultStackSize)
stack_size is the size of the stack available to this fiber.
link points to another fiber which will start executing when this fiber's main function returns.
Definition at line 86 of file fiber.cc.
Referenced by TEST().
Fiber() [2/2]
Fiber::Fiber (Fiber * link, size_t stack_size = DefaultStackSize)
Definition at line 89 of file fiber.cc.
References fatal, guardPage, guardPageSize, and stack.
~Fiber()
Fiber::~Fiber () virtual
Definition at line 113 of file fiber.cc.
References guardPage, guardPageSize, panic_if, stack, and stackSize.
Member Function Documentation
createContext()
void Fiber::createContext () private
Definition at line 124 of file fiber.cc.
References ctx, entryTrampoline(), panic_if, stack, and stackSize.
Referenced by run().
currentFiber()
Fiber * Fiber::currentFiber () static
Get a pointer to the current running Fiber.
Definition at line 183 of file fiber.cc.
Referenced by m5::Coroutine< Arg, Ret >::call(), and started().
entryTrampoline()
void Fiber::entryTrampoline () static private
Definition at line 81 of file fiber.cc.
Referenced by createContext(), and setStarted().
finished()
bool Fiber::finished () const inline
Returns whether the "main" function of this fiber has finished.
Definition at line 83 of file fiber.hh.
References _finished.
Referenced by sc_gem5::Kernel::init(), m5::Coroutine< Arg, Ret >::operator bool(), sc_gem5::Scheduler::pause(), sc_gem5::Kernel::regStats(), sc_gem5::Kernel::startup(), sc_gem5::Scheduler::stop(), TEST(), and sc_gem5::Scheduler::throwUp().
main()
virtual void Fiber::main () protected pure virtual
This method is called when this fiber is first run.
Override it to give your fiber something to do. When main returns, the fiber will mark itself as finished and switch to its link fiber.
Implemented in m5::Coroutine< Arg, Ret >, LinkedFiber, sc_gem5::Thread::Context, SwitchingFiber, and sc_gem5::ScMainFiber.
Referenced by start(), started(), and TEST().
primaryFiber()
Fiber * Fiber::primaryFiber () static
Get a pointer to the primary Fiber.
This Fiber represents the thread of execution started by the OS, and which has a Fiber attached to it after the fact.
Definition at line 184 of file fiber.cc.
Referenced by sc_gem5::Process::fiber(), sc_gem5::Scheduler::start(), started(), TEST(), and sc_gem5::Scheduler::yield().
run()
void Fiber::run ()
Start executing the fiber represented by this object.
This function will "return" when the current fiber is switched back to later on.
Definition at line 165 of file fiber.cc.
References _finished, _started, createContext(), ctx, and panic_if.
Referenced by m5::Coroutine< Arg, Ret >::call(), sc_gem5::Scheduler::pause(), start(), sc_gem5::Scheduler::start(), sc_gem5::Scheduler::stop(), TEST(), sc_gem5::Scheduler::throwUp(), and sc_gem5::Scheduler::yield().
setStarted()
void Fiber::setStarted () inline protected
Definition at line 103 of file fiber.hh.
References _started, entryTrampoline(), and start().
Referenced by start().
start()
void Fiber::start () private
Definition at line 143 of file fiber.cc.
References _finished, ctx, link, M5_VAR_USED, main(), panic_if, run(), and setStarted().
Referenced by setStarted().
started()
bool Fiber::started () const inline
Returns whether the "main" function of this fiber has started.
Definition at line 87 of file fiber.hh.
References _started, currentFiber(), main(), and primaryFiber().
Referenced by TEST().
Member Data Documentation
_finished
bool Fiber::_finished private
Definition at line 122 of file fiber.hh.
Referenced by finished(), run(), and start().
_started
bool Fiber::_started private
Definition at line 121 of file fiber.hh.
Referenced by run(), setStarted(), and started().
ctx
ucontext_t Fiber::ctx private
Definition at line 109 of file fiber.hh.
Referenced by createContext(), run(), and start().
DefaultStackSize
const size_t Fiber::DefaultStackSize = 0x50000 static
Definition at line 67 of file fiber.hh.
Referenced by sc_gem5::Process::Process().
guardPage
void* Fiber::guardPage private
Definition at line 115 of file fiber.hh.
Referenced by Fiber(), and ~Fiber().
guardPageSize
size_t Fiber::guardPageSize private
Definition at line 116 of file fiber.hh.
Referenced by Fiber(), and ~Fiber().
link
Fiber* Fiber::link private
Definition at line 110 of file fiber.hh.
Referenced by start().
stack
void* Fiber::stack private
Definition at line 113 of file fiber.hh.
Referenced by createContext(), Fiber(), and ~Fiber().
stackSize
size_t Fiber::stackSize private
Definition at line 114 of file fiber.hh.
Referenced by createContext(), and ~Fiber().
The documentation for this class was generated from the following files:
base/fiber.hh
base/fiber.cc