gem5: tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process Class Reference
tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process Class Reference
Public Member Functions
bw_process (simple_target_socket_tagged_b *p_own)
sync_enum_type nb_transport_bw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void invalidate_direct_mem_ptr (sc_dt::uint64 s, sc_dt::uint64 e)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Private Attributes
simple_target_socket_tagged_b * m_owner
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process
Definition at line 714 of file simple_target_socket.h.
Constructor & Destructor Documentation
bw_process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::bw_process (simple_target_socket_tagged_b * p_own) inline
Definition at line 717 of file simple_target_socket.h.
Member Function Documentation
invalidate_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::invalidate_direct_mem_ptr (sc_dt::uint64 s, sc_dt::uint64 e) inline virtual
Implements tlm::tlm_bw_direct_mem_if.
Definition at line 748 of file simple_target_socket.h.
References tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_invalidate_direct_mem_ptr(), and tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner.
nb_transport_bw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_bw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 720 of file simple_target_socket.h.
References tlm::BEGIN_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_nb_transport(), tlm_utils::convenience_socket_base::display_error(), tlm::END_REQ, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_current_transaction, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_end_request, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans, sc_core::sc_event::notify(), sc_core::SC_ZERO_TIME, tlm::TLM_ACCEPTED, and tlm::TLM_COMPLETED.
Member Data Documentation
m_owner
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> simple_target_socket_tagged_b* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner private
Definition at line 754 of file simple_target_socket.h.
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/simple_target_socket.h