gem5: sc_dt::scfx_index Class Reference
sc_dt::scfx_index Class Reference
#include <scfx_rep.hh>
Public Member Functions
scfx_index (int wi_, int bi_)
int wi () const
int bi () const
void wi (int wi_)
Private Attributes
int m_wi
int m_bi
Detailed Description
Definition at line 115 of file scfx_rep.hh.
Constructor & Destructor Documentation
scfx_index()
sc_dt::scfx_index::scfx_index (int wi_, int bi_) inline
Definition at line 118 of file scfx_rep.hh.
Member Function Documentation
bi()
int sc_dt::scfx_index::bi () const inline
Definition at line 121 of file scfx_rep.hh.
References m_bi.
Referenced by sc_dt::scfx_rep::clear(), sc_dt::scfx_rep::get_bit(), sc_dt::scfx_rep::o_bit_at(), sc_dt::scfx_rep::o_extend(), sc_dt::scfx_rep::o_invert(), sc_dt::scfx_rep::o_set(), sc_dt::scfx_rep::o_set_high(), sc_dt::scfx_rep::o_set_low(), sc_dt::scfx_rep::o_zero_left(), sc_dt::scfx_rep::o_zero_right(), sc_dt::scfx_rep::q_bit(), sc_dt::scfx_rep::q_clear(), sc_dt::scfx_rep::q_incr(), sc_dt::scfx_rep::q_odd(), sc_dt::scfx_rep::q_zero(), sc_dt::scfx_rep::scfx_rep(), and sc_dt::scfx_rep::set().
wi() [1/2]
int sc_dt::scfx_index::wi () const inline
Definition at line 120 of file scfx_rep.hh.
References m_wi.
Referenced by sc_dt::scfx_rep::clear(), sc_dt::scfx_rep::get_bit(), sc_dt::scfx_rep::o_bit_at(), sc_dt::scfx_rep::o_extend(), sc_dt::scfx_rep::o_invert(), sc_dt::scfx_rep::o_set(), sc_dt::scfx_rep::o_set_high(), sc_dt::scfx_rep::o_set_low(), sc_dt::scfx_rep::o_zero_left(), sc_dt::scfx_rep::o_zero_right(), sc_dt::scfx_rep::overflow(), sc_dt::scfx_rep::q_bit(), sc_dt::scfx_rep::q_clear(), sc_dt::scfx_rep::q_incr(), sc_dt::scfx_rep::q_odd(), sc_dt::scfx_rep::q_zero(), sc_dt::scfx_rep::quantization(), sc_dt::scfx_rep::scfx_rep(), and sc_dt::scfx_rep::set().
wi() [2/2]
void sc_dt::scfx_index::wi (int wi_) inline
Definition at line 123 of file scfx_rep.hh.
References m_wi.
Member Data Documentation
m_bi
int sc_dt::scfx_index::m_bi private
Definition at line 127 of file scfx_rep.hh.
Referenced by bi().
m_wi
int sc_dt::scfx_index::m_wi private
Definition at line 126 of file scfx_rep.hh.
Referenced by wi().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/scfx_rep.hh