gem5: sc_core::sc_inout< bool > Class Template Reference
sc_core::sc_inout< bool > Class Template Reference
#include <sc_inout.hh>
Public Member Functions
sc_inout ()
sc_inout (const char *name)
virtual ~sc_inout ()
sc_inout (const sc_signal_inout_if< bool > &interface)
sc_inout (const char *name, const sc_signal_inout_if< bool > &interface)
sc_inout (sc_port_b< sc_signal_inout_if< bool > > &parent)
sc_inout (const char *name, sc_port_b< sc_signal_inout_if< bool > > &parent)
sc_inout (sc_port< sc_signal_inout_if< bool >, 1 > &parent)
sc_inout (const char *name, sc_port< sc_signal_inout_if< bool >, 1 > &parent)
void initialize (const bool &b)
void initialize (const sc_signal_in_if< bool > &i)
virtual void end_of_elaboration ()
const bool & read () const
operator const bool & () const
void write (const bool &b)
sc_inout< bool > & operator= (const bool &b)
sc_inout< bool > & operator= (const sc_signal_in_if< bool > &i)
sc_inout< bool > & operator= (const sc_port< sc_signal_in_if< bool >, 1 > &p)
sc_inout< bool > & operator= (const sc_port< sc_signal_inout_if< bool >, 1 > &p)
sc_inout< bool > & operator= (const sc_inout< bool > &p)
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_event & posedge_event () const
const sc_event & negedge_event () const
bool event () const
bool posedge () const
bool negedge () const
sc_event_finder & value_changed () const
sc_event_finder & pos () const
sc_event_finder & neg () const
virtual const char * kind () const
void add_trace (sc_trace_file *tf, const std::string &name) const
Public Member Functions inherited from sc_core::sc_port< sc_signal_inout_if< bool >, 1 >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_inout_if< bool > &interface)
sc_port (const char *name, const sc_signal_inout_if< bool > &interface)
sc_port (sc_port_b< sc_signal_inout_if< bool > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_inout_if< bool > > &parent)
sc_port (sc_port< sc_signal_inout_if< bool >, N, SC_ONE_OR_MORE_BOUND > &parent)
sc_port (const char *name, sc_port< sc_signal_inout_if< bool >, N, SC_ONE_OR_MORE_BOUND > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< bool > >
void operator() (sc_signal_inout_if< bool > &i)
void operator() (sc_port_b< sc_signal_inout_if< bool > > &p)
virtual void bind (sc_signal_inout_if< bool > &i)
virtual void bind (sc_port_b< sc_signal_inout_if< bool > > &p)
sc_signal_inout_if< bool > * operator-> ()
const sc_signal_inout_if< bool > * operator-> () const
sc_signal_inout_if< bool > * operator[] (int n)
const sc_signal_inout_if< bool > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Member Functions
sc_inout (const sc_inout< bool > &)
Private Attributes
bool * initValue
sc_event_finder_t< sc_signal_inout_if< bool > > _valueChangedFinder
sc_event_finder_t< sc_signal_inout_if< bool > > _posFinder
sc_event_finder_t< sc_signal_inout_if< bool > > _negFinder
sc_trace_params_vec traceParamsVec
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< bool > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
template<>
class sc_core::sc_inout< bool >
Definition at line 195 of file sc_inout.hh.
Constructor & Destructor Documentation
sc_inout() [1/9]
sc_core::sc_inout< bool >::sc_inout () inline
Definition at line 198 of file sc_inout.hh.
sc_inout() [2/9]
sc_core::sc_inout< bool >::sc_inout (const char * name) inline explicit
Definition at line 204 of file sc_inout.hh.
~sc_inout()
virtual sc_core::sc_inout< bool >::~sc_inout () inline virtual
Definition at line 211 of file sc_inout.hh.
sc_inout() [3/9]
sc_core::sc_inout< bool >::sc_inout (const sc_signal_inout_if< bool > & interface) inline explicit
Definition at line 214 of file sc_inout.hh.
sc_inout() [4/9]
sc_core::sc_inout< bool >::sc_inout (const char * name, const sc_signal_inout_if< bool > & interface) inline
Definition at line 221 of file sc_inout.hh.
sc_inout() [5/9]
sc_core::sc_inout< bool >::sc_inout (sc_port_b< sc_signal_inout_if< bool > > & parent) inline explicit
Definition at line 229 of file sc_inout.hh.
sc_inout() [6/9]
sc_core::sc_inout< bool >::sc_inout (const char * name, sc_port_b< sc_signal_inout_if< bool > > & parent) inline
Definition at line 236 of file sc_inout.hh.
sc_inout() [7/9]
sc_core::sc_inout< bool >::sc_inout (sc_port< sc_signal_inout_if< bool >, 1 > & parent) inline explicit
Definition at line 243 of file sc_inout.hh.
sc_inout() [8/9]
sc_core::sc_inout< bool >::sc_inout (const char * name, sc_port< sc_signal_inout_if< bool >, 1 > & parent) inline
Definition at line 250 of file sc_inout.hh.
sc_inout() [9/9]
sc_core::sc_inout< bool >::sc_inout (const sc_inout< bool > &) private
Member Function Documentation
add_trace()
void sc_core::sc_inout< bool >::add_trace (sc_trace_file * tf, const std::string & name) const inline
Definition at line 340 of file sc_inout.hh.
default_event()
const sc_event& sc_core::sc_inout< bool >::default_event () const inline
Definition at line 321 of file sc_inout.hh.
end_of_elaboration()
virtual void sc_core::sc_inout< bool >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Definition at line 272 of file sc_inout.hh.
References sc_core::sc_trace().
event()
bool sc_core::sc_inout< bool >::event () const inline
Definition at line 329 of file sc_inout.hh.
initialize() [1/2]
void sc_core::sc_inout< bool >::initialize (const bool & b) inline
Definition at line 259 of file sc_inout.hh.
References ArmISA::b.
initialize() [2/2]
void sc_core::sc_inout< bool >::initialize (const sc_signal_in_if< bool > & i) inline
Definition at line 269 of file sc_inout.hh.
References initialize(), and sc_core::sc_signal_in_if< bool >::read().
Referenced by initialize().
kind()
virtual const char* sc_core::sc_inout< bool >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_inout_if< bool >, 1 >.
Reimplemented in sc_core::sc_out< bool >.
Definition at line 337 of file sc_inout.hh.
neg()
sc_event_finder& sc_core::sc_inout< bool >::neg () const inline
Definition at line 335 of file sc_inout.hh.
negedge()
bool sc_core::sc_inout< bool >::negedge () const inline
Definition at line 331 of file sc_inout.hh.
negedge_event()
const sc_event& sc_core::sc_inout< bool >::negedge_event () const inline
Definition at line 328 of file sc_inout.hh.
operator const bool &()
sc_core::sc_inout< bool >::operator const bool & () const inline
Definition at line 287 of file sc_inout.hh.
operator=() [1/5]
sc_inout<bool>& sc_core::sc_inout< bool >::operator= (const bool & b) inline
Definition at line 291 of file sc_inout.hh.
References write().
operator=() [2/5]
sc_inout<bool>& sc_core::sc_inout< bool >::operator= (const sc_signal_in_if< bool > & i) inline
Definition at line 297 of file sc_inout.hh.
References sc_core::sc_signal_in_if< bool >::read(), and write().
operator=() [3/5]
sc_inout<bool>& sc_core::sc_inout< bool >::operator= (const sc_port< sc_signal_in_if< bool >, 1 > & p) inline
Definition at line 303 of file sc_inout.hh.
References MipsISA::p, and write().
operator=() [4/5]
sc_inout<bool>& sc_core::sc_inout< bool >::operator= (const sc_port< sc_signal_inout_if< bool >, 1 > & p) inline
Definition at line 309 of file sc_inout.hh.
References MipsISA::p, and write().
operator=() [5/5]
sc_inout<bool>& sc_core::sc_inout< bool >::operator= (const sc_inout< bool > & p) inline
Definition at line 315 of file sc_inout.hh.
References read(), and write().
pos()
sc_event_finder& sc_core::sc_inout< bool >::pos () const inline
Definition at line 334 of file sc_inout.hh.
Referenced by sc_core::sc_sensitive::operator()().
posedge()
bool sc_core::sc_inout< bool >::posedge () const inline
Definition at line 330 of file sc_inout.hh.
posedge_event()
const sc_event& sc_core::sc_inout< bool >::posedge_event () const inline
Definition at line 327 of file sc_inout.hh.
read()
const bool& sc_core::sc_inout< bool >::read () const inline
Definition at line 286 of file sc_inout.hh.
Referenced by operator=().
value_changed()
sc_event_finder& sc_core::sc_inout< bool >::value_changed () const inline
Definition at line 333 of file sc_inout.hh.
value_changed_event()
const sc_event& sc_core::sc_inout< bool >::value_changed_event () const inline
Definition at line 323 of file sc_inout.hh.
write()
void sc_core::sc_inout< bool >::write (const bool & b) inline
Definition at line 289 of file sc_inout.hh.
Referenced by operator=().
Member Data Documentation
_negFinder
sc_event_finder_t<sc_signal_inout_if<bool> > sc_core::sc_inout< bool >::_negFinder mutable private
Definition at line 349 of file sc_inout.hh.
_posFinder
sc_event_finder_t<sc_signal_inout_if<bool> > sc_core::sc_inout< bool >::_posFinder mutable private
Definition at line 348 of file sc_inout.hh.
_valueChangedFinder
sc_event_finder_t<sc_signal_inout_if<bool> > sc_core::sc_inout< bool >::_valueChangedFinder mutable private
Definition at line 347 of file sc_inout.hh.
initValue
bool* sc_core::sc_inout< bool >::initValue private
Definition at line 346 of file sc_inout.hh.
traceParamsVec
sc_trace_params_vec sc_core::sc_inout< bool >::traceParamsVec mutable private
Definition at line 351 of file sc_inout.hh.
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_inout.hh