gem5: SimpleCache Class Reference
SimpleCache Class Reference
A very simple cache object.
#include <simple_cache.hh>
Classes
class CPUSidePort
Port on the CPU-side that receives requests.
class MemSidePort
Port on the memory-side that receives responses.
Public Member Functions
SimpleCache (SimpleCacheParams *params)
constructor
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void regStats () override
Register the stats.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
bool handleRequest (PacketPtr pkt, int port_id)
Handle the request from the CPU side.
bool handleResponse (PacketPtr pkt)
Handle the respone from the memory side.
void sendResponse (PacketPtr pkt)
Send the packet to the CPU side.
void handleFunctional (PacketPtr pkt)
Handle a packet functionally.
void accessTiming (PacketPtr pkt)
Access the cache for a timing access.
bool accessFunctional (PacketPtr pkt)
This is where we actually update / read from the cache.
void insert (PacketPtr pkt)
Insert a block into the cache.
AddrRangeList getAddrRanges () const
Return the address ranges this cache is responsible for.
void sendRangeChange () const
Tell the CPU side to ask for our memory ranges.
Private Attributes
const Cycles latency
Latency to check the cache. Number of cycles for both hit and miss.
const unsigned blockSize
The block size for the cache.
const unsigned capacity
Number of blocks in the cache (size of cache / block size)
std::vector< CPUSidePort > cpuPorts
Instantiation of the CPU-side port.
MemSidePort memPort
Instantiation of the memory-side port.
bool blocked
True if this cache is currently blocked waiting for a response.
PacketPtr originalPacket
Packet that we are currently handling.
int waitingPortId
The port to send the response when we recieve it back.
Tick missTime
For tracking the miss latency.
std::unordered_map< Addr, uint8_t * > cacheStore
An incredibly simple cache storage. Maps block addresses to data.
Stats::Scalar hits
Cache statistics.
Stats::Scalar misses
Stats::Histogram missLatency
Stats::Formula hitRatio
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
A very simple cache object.
Has a fully-associative data store with random replacement. This cache is fully blocking (not non-blocking). Only a single request can be outstanding at a time. This cache is a writeback cache.
Definition at line 48 of file simple_cache.hh.
Constructor & Destructor Documentation
SimpleCache()
SimpleCache::SimpleCache (SimpleCacheParams * params)
constructor
Definition at line 37 of file simple_cache.cc.
References cpuPorts, csprintf(), ArmISA::i, and SimObject::name().
Referenced by regStats().
Member Function Documentation
accessFunctional()
bool SimpleCache::accessFunctional (PacketPtr pkt) private
This is where we actually update / read from the cache.
This function is executed on both timing and functional accesses.
Returns
true if a hit, false otherwise
Definition at line 340 of file simple_cache.cc.
References blockSize, cacheStore, Packet::getBlockAddr(), Packet::isRead(), Packet::isWrite(), panic, Packet::setDataFromBlock(), and Packet::writeDataToBlock().
Referenced by accessTiming(), handleFunctional(), handleResponse(), and SimpleCache::MemSidePort::MemSidePort().
accessTiming()
void SimpleCache::accessTiming (PacketPtr pkt) private
Access the cache for a timing access.
This is called after the cache access latency has already elapsed.
Definition at line 282 of file simple_cache.cc.
References accessFunctional(), addr, Packet::allocate(), blockSize, curTick(), DDUMP, DPRINTF, Packet::getAddr(), Packet::getBlockAddr(), Packet::getConstPtr(), Packet::getSize(), hits, Packet::isRead(), Packet::isWrite(), Packet::makeResponse(), memPort, misses, missTime, Packet::needsResponse(), originalPacket, panic, panic_if, Packet::print(), MemCmd::ReadReq, Packet::req, SimpleCache::MemSidePort::sendPacket(), and sendResponse().
Referenced by handleRequest(), and SimpleCache::MemSidePort::MemSidePort().
getAddrRanges()
AddrRangeList SimpleCache::getAddrRanges () const private
Return the address ranges this cache is responsible for.
Just use the same as the next upper level of the hierarchy.
Returns
the address ranges this cache is responsible for
Definition at line 411 of file simple_cache.cc.
References DPRINTF, MasterPort::getAddrRanges(), and memPort.
getPort()
Port & SimpleCache::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 55 of file simple_cache.cc.
References cpuPorts, SimObject::getPort(), InvalidPortID, memPort, and panic_if.
handleFunctional()
void SimpleCache::handleFunctional (PacketPtr pkt) private
Handle a packet functionally.
Update the data on a write and get the data on a read. Called from CPU port on a recv functional.
Parameters
packet to functionally handle
Definition at line 272 of file simple_cache.cc.
References accessFunctional(), Packet::makeResponse(), memPort, and MasterPort::sendFunctional().
Referenced by SimpleCache::MemSidePort::MemSidePort().
handleRequest()
bool SimpleCache::handleRequest (PacketPtr pkt, int port_id) private
Handle the request from the CPU side.
Called from the CPU port on a timing request.
Parameters
requesting packet
id of the port to send the response
Returns
true if we can handle the request this cycle, false if the requestor needs to retry later
Definition at line 192 of file simple_cache.cc.
References accessTiming(), blocked, Clocked::clockEdge(), DPRINTF, Packet::getAddr(), latency, SimObject::name(), EventManager::schedule(), and waitingPortId.
Referenced by SimpleCache::MemSidePort::MemSidePort().
handleResponse()
bool SimpleCache::handleResponse (PacketPtr pkt) private
Handle the respone from the memory side.
Called from the memory port on a timing response.
Parameters
responding packet
Returns
true if we can handle the response this cycle, false if the responder needs to retry later
Definition at line 217 of file simple_cache.cc.
References accessFunctional(), blocked, curTick(), DPRINTF, Packet::getAddr(), insert(), M5_VAR_USED, Packet::makeResponse(), missLatency, missTime, originalPacket, panic_if, Stats::DistBase< Derived, Stor >::sample(), and sendResponse().
Referenced by SimpleCache::MemSidePort::MemSidePort().
insert()
void SimpleCache::insert (PacketPtr pkt) private
Insert a block into the cache.
If there is no room left in the cache, then this function evicts a random entry t make room for the new block.
Parameters
packet with the data (and address) to insert into the cache
Definition at line 360 of file simple_cache.cc.
References blockSize, cacheStore, capacity, data, DDUMP, DPRINTF, Packet::getAddr(), Packet::getBlockAddr(), Packet::getConstPtr(), Packet::isResponse(), memPort, Packet::print(), Random::random(), random_mt, SimpleCache::MemSidePort::sendPacket(), MemCmd::WritebackDirty, and Packet::writeDataToBlock().
Referenced by handleResponse(), and SimpleCache::MemSidePort::MemSidePort().
regStats()
void SimpleCache::regStats () override virtual
Register the stats.
Reimplemented from Stats::Group.
Definition at line 427 of file simple_cache.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), hitRatio, hits, Stats::Histogram::init(), misses, missLatency, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::Group::regStats(), and SimpleCache().
sendRangeChange()
void SimpleCache::sendRangeChange () const private
Tell the CPU side to ask for our memory ranges.
Definition at line 419 of file simple_cache.cc.
References cpuPorts.
sendResponse()
void SimpleCache::sendResponse (PacketPtr pkt) private
Send the packet to the CPU side.
This function assumes the pkt is already a response packet and forwards it to the correct port. This function also unblocks this object and cleans up the whole request.
Parameters
the packet to send to the cpu side
Definition at line 247 of file simple_cache.cc.
References blocked, cpuPorts, DPRINTF, Packet::getAddr(), and waitingPortId.
Referenced by accessTiming(), handleResponse(), and SimpleCache::MemSidePort::MemSidePort().
Member Data Documentation
blocked
bool SimpleCache::blocked private
True if this cache is currently blocked waiting for a response.
Definition at line 281 of file simple_cache.hh.
Referenced by handleRequest(), handleResponse(), and sendResponse().
blockSize
const unsigned SimpleCache::blockSize private
The block size for the cache.
Definition at line 269 of file simple_cache.hh.
Referenced by accessFunctional(), accessTiming(), and insert().
cacheStore
std::unordered_map<Addr, uint8_t*> SimpleCache::cacheStore private
An incredibly simple cache storage. Maps block addresses to data.
Definition at line 294 of file simple_cache.hh.
Referenced by accessFunctional(), and insert().
capacity
const unsigned SimpleCache::capacity private
Number of blocks in the cache (size of cache / block size)
Definition at line 272 of file simple_cache.hh.
Referenced by insert().
cpuPorts
std::vector<CPUSidePort> SimpleCache::cpuPorts private
Instantiation of the CPU-side port.
Definition at line 275 of file simple_cache.hh.
Referenced by getPort(), sendRangeChange(), sendResponse(), and SimpleCache().
hitRatio
Stats::Formula SimpleCache::hitRatio private
Definition at line 300 of file simple_cache.hh.
Referenced by regStats().
hits
Stats::Scalar SimpleCache::hits private
Cache statistics.
Definition at line 297 of file simple_cache.hh.
Referenced by accessTiming(), and regStats().
latency
const Cycles SimpleCache::latency private
Latency to check the cache. Number of cycles for both hit and miss.
Definition at line 266 of file simple_cache.hh.
Referenced by handleRequest().
memPort
MemSidePort SimpleCache::memPort private
Instantiation of the memory-side port.
Definition at line 278 of file simple_cache.hh.
Referenced by accessTiming(), getAddrRanges(), getPort(), handleFunctional(), and insert().
misses
Stats::Scalar SimpleCache::misses private
Definition at line 298 of file simple_cache.hh.
Referenced by accessTiming(), and regStats().
missLatency
Stats::Histogram SimpleCache::missLatency private
Definition at line 299 of file simple_cache.hh.
Referenced by handleResponse(), and regStats().
missTime
Tick SimpleCache::missTime private
For tracking the miss latency.
Definition at line 291 of file simple_cache.hh.
Referenced by accessTiming(), and handleResponse().
originalPacket
PacketPtr SimpleCache::originalPacket private
Packet that we are currently handling.
Used for upgrading to larger cache line sizes
Definition at line 285 of file simple_cache.hh.
Referenced by accessTiming(), and handleResponse().
waitingPortId
int SimpleCache::waitingPortId private
The port to send the response when we recieve it back.
Definition at line 288 of file simple_cache.hh.
Referenced by handleRequest(), and sendResponse().
The documentation for this class was generated from the following files:
learning_gem5/part2/simple_cache.hh
learning_gem5/part2/simple_cache.cc