gem5: sc_dt::sc_fxcast_switch Class Reference
sc_dt::sc_fxcast_switch Class Reference
#include <sc_fxcast_switch.hh>
Public Member Functions
sc_fxcast_switch ()
sc_fxcast_switch (sc_switch)
sc_fxcast_switch (const sc_fxcast_switch &)
sc_fxcast_switch (sc_without_context)
sc_fxcast_switch & operator= (const sc_fxcast_switch &)
const std::string to_string () const
void print (::std::ostream &=::std::cout) const
void dump (::std::ostream &=::std::cout) const
Private Attributes
sc_switch m_sw
Friends
bool operator== (const sc_fxcast_switch &, const sc_fxcast_switch &)
bool operator!= (const sc_fxcast_switch &, const sc_fxcast_switch &)
Detailed Description
Definition at line 71 of file sc_fxcast_switch.hh.
Constructor & Destructor Documentation
sc_fxcast_switch() [1/4]
sc_dt::sc_fxcast_switch::sc_fxcast_switch () inline
Definition at line 114 of file sc_fxcast_switch.hh.
References sc_dt::sc_context< T >::default_value().
sc_fxcast_switch() [2/4]
sc_dt::sc_fxcast_switch::sc_fxcast_switch (sc_switch sw_) inline
Definition at line 119 of file sc_fxcast_switch.hh.
sc_fxcast_switch() [3/4]
sc_dt::sc_fxcast_switch::sc_fxcast_switch (const sc_fxcast_switch & a) inline
Definition at line 121 of file sc_fxcast_switch.hh.
sc_fxcast_switch() [4/4]
sc_dt::sc_fxcast_switch::sc_fxcast_switch (sc_without_context) inline explicit
Definition at line 125 of file sc_fxcast_switch.hh.
Member Function Documentation
dump()
void sc_dt::sc_fxcast_switch::dump (::std::ostream & os = ::std::cout) const
Definition at line 78 of file sc_fxcast_switch.cc.
References m_sw, and sc_dt::to_string().
Referenced by sc_dt::scfx_params::dump().
operator=()
sc_fxcast_switch & sc_dt::sc_fxcast_switch::operator= (const sc_fxcast_switch & a) inline
Definition at line 130 of file sc_fxcast_switch.hh.
References m_sw.
print()
void sc_dt::sc_fxcast_switch::print (::std::ostream & os = ::std::cout) const
Definition at line 72 of file sc_fxcast_switch.cc.
References m_sw, and sc_dt::to_string().
Referenced by sc_dt::operator<<().
to_string()
const std::string sc_dt::sc_fxcast_switch::to_string () const
Definition at line 66 of file sc_fxcast_switch.cc.
References m_sw, and sc_dt::to_string().
Friends And Related Function Documentation
operator!=
bool operator!= (const sc_fxcast_switch & a, const sc_fxcast_switch & b) friend
Definition at line 145 of file sc_fxcast_switch.hh.
operator==
bool operator== (const sc_fxcast_switch & a, const sc_fxcast_switch & b) friend
Definition at line 139 of file sc_fxcast_switch.hh.
Member Data Documentation
m_sw
sc_switch sc_dt::sc_fxcast_switch::m_sw private
Definition at line 92 of file sc_fxcast_switch.hh.
Referenced by dump(), sc_dt::operator!=(), operator=(), sc_dt::operator==(), print(), and to_string().
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxcast_switch.hh
systemc/dt/fx/sc_fxcast_switch.cc