gem5: InstResult Class Reference
InstResult Class Reference
#include <inst_res.hh>
Classes
union MultiResult
Public Types
enum ResultType {
ResultType::Scalar, ResultType::VecElem, ResultType::VecReg, ResultType::VecPredReg,
ResultType::NumResultTypes, ResultType::Invalid
}
Public Member Functions
InstResult ()
Default constructor creates an invalid result.
template<typename T >
InstResult (T i, const ResultType &t)
Scalar result from scalar.
InstResult (const VecRegContainer &v, const ResultType &t)
Vector result.
InstResult (const VecPredRegContainer &v, const ResultType &t)
Predicate result.
InstResult & operator= (const InstResult &that)
bool operator== (const InstResult &that) const
Result comparison Two invalid results always differ.
bool operator!= (const InstResult &that) const
bool isScalar () const
Checks.
bool isVector () const
Is this a vector result?.
bool isVecElem () const
Is this a vector element result?.
bool isPred () const
Is this a predicate result?.
bool isValid () const
Is this a valid result?.
const uint64_t & asInteger () const
Explicit cast-like operations.
const uint64_t & asIntegerNoAssert () const
Cast to integer without checking type.
const VecRegContainer & asVector () const
const VecElem & asVectorElem () const
const VecPredRegContainer & asPred () const
Private Types
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Private Attributes
MultiResult result
ResultType type
Detailed Description
Definition at line 48 of file inst_res.hh.
Member Typedef Documentation
VecElem
using InstResult::VecElem = TheISA::VecElem private
Definition at line 50 of file inst_res.hh.
VecPredRegContainer
using InstResult::VecPredRegContainer = TheISA::VecPredRegContainer private
Definition at line 51 of file inst_res.hh.
VecRegContainer
using InstResult::VecRegContainer = TheISA::VecRegContainer private
Definition at line 49 of file inst_res.hh.
Member Enumeration Documentation
ResultType
enum InstResult::ResultType strong
Enumerator
Scalar
VecElem
VecReg
VecPredReg
NumResultTypes
Invalid
Definition at line 62 of file inst_res.hh.
Constructor & Destructor Documentation
InstResult() [1/4]
InstResult::InstResult () inline
Default constructor creates an invalid result.
Definition at line 77 of file inst_res.hh.
InstResult() [2/4]
template<typename T > InstResult::InstResult (T i, const ResultType & t) inline explicit
Scalar result from scalar.
Definition at line 80 of file inst_res.hh.
References InstResult::MultiResult::dbl, ArmISA::i, and InstResult::MultiResult::integer.
InstResult() [3/4]
InstResult::InstResult (const VecRegContainer & v, const ResultType & t) inline explicit
Vector result.
Definition at line 91 of file inst_res.hh.
References ArmISA::v, and InstResult::MultiResult::vector.
InstResult() [4/4]
InstResult::InstResult (const VecPredRegContainer & v, const ResultType & t) inline explicit
Predicate result.
Definition at line 94 of file inst_res.hh.
References InstResult::MultiResult::pred, and ArmISA::v.
Member Function Documentation
asInteger()
const uint64_t& InstResult::asInteger () const inline
Explicit cast-like operations.
Definition at line 167 of file inst_res.hh.
References InstResult::MultiResult::integer, and isScalar().
Referenced by Checker< O3CPUImpl >::copyResult(), and Checker< O3CPUImpl >::validateExecution().
asIntegerNoAssert()
const uint64_t& InstResult::asIntegerNoAssert () const inline
Cast to integer without checking type.
This is required to have the o3 cpu checker happy, as it compares results as integers without being fully aware of their nature.
Definition at line 178 of file inst_res.hh.
References InstResult::MultiResult::integer.
Referenced by Checker< O3CPUImpl >::validateExecution().
asPred()
const VecPredRegContainer& InstResult::asPred () const inline
Definition at line 196 of file inst_res.hh.
References isPred(), panic_if, and InstResult::MultiResult::pred.
asVector()
const VecRegContainer& InstResult::asVector () const inline
Definition at line 183 of file inst_res.hh.
References isVector(), panic_if, and InstResult::MultiResult::vector.
Referenced by Checker< O3CPUImpl >::copyResult().
asVectorElem()
const VecElem& InstResult::asVectorElem () const inline
Definition at line 189 of file inst_res.hh.
References isVecElem(), panic_if, and InstResult::MultiResult::vecElem.
Referenced by Checker< O3CPUImpl >::copyResult().
isPred()
bool InstResult::isPred () const inline
Is this a predicate result?.
Definition at line 159 of file inst_res.hh.
References VecPredReg.
Referenced by asPred().
isScalar()
bool InstResult::isScalar () const inline
Checks.
Is this a scalar result?.
Definition at line 153 of file inst_res.hh.
References Scalar.
Referenced by asInteger(), Checker< O3CPUImpl >::copyResult(), and Checker< O3CPUImpl >::validateExecution().
isValid()
bool InstResult::isValid () const inline
Is this a valid result?.
Definition at line 161 of file inst_res.hh.
References Invalid.
Referenced by Checker< O3CPUImpl >::copyResult().
isVecElem()
bool InstResult::isVecElem () const inline
Is this a vector element result?.
Definition at line 157 of file inst_res.hh.
References VecElem.
Referenced by asVectorElem(), and Checker< O3CPUImpl >::copyResult().
isVector()
bool InstResult::isVector () const inline
Is this a vector result?.
Definition at line 155 of file inst_res.hh.
References VecReg.
Referenced by asVector(), Checker< O3CPUImpl >::copyResult(), and Checker< O3CPUImpl >::validateExecution().
operator!=()
bool InstResult::operator!= (const InstResult & that) const inline
Definition at line 146 of file inst_res.hh.
References operator==().
operator=()
InstResult& InstResult::operator= (const InstResult & that) inline
Definition at line 97 of file inst_res.hh.
References InstResult::MultiResult::integer, Invalid, panic, InstResult::MultiResult::pred, result, Scalar, type, InstResult::MultiResult::vecElem, VecElem, VecPredReg, VecReg, and InstResult::MultiResult::vector.
operator==()
bool InstResult::operator== (const InstResult & that) const inline
Result comparison Two invalid results always differ.
Definition at line 127 of file inst_res.hh.
References InstResult::MultiResult::integer, Invalid, panic, InstResult::MultiResult::pred, result, Scalar, type, InstResult::MultiResult::vecElem, VecElem, VecPredReg, VecReg, and InstResult::MultiResult::vector.
Referenced by operator!=().
Member Data Documentation
result
MultiResult InstResult::result private
Definition at line 72 of file inst_res.hh.
Referenced by operator=(), and operator==().
type
ResultType InstResult::type private
Definition at line 73 of file inst_res.hh.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following file:
cpu/inst_res.hh