gem5: sc_dt::sc_fxnum_fast_subref Class Reference
sc_dt::sc_fxnum_fast_subref Class Reference
#include <sc_fxnum.hh>
Public Member Functions
sc_fxnum_fast_subref (const sc_fxnum_fast_subref &)
~sc_fxnum_fast_subref ()
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
int length () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
operator sc_bv_base () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
Private Member Functions
bool get () const
bool set ()
sc_fxnum_fast_subref (sc_fxnum_fast &, int, int)
sc_fxnum_fast_subref ()
Private Attributes
sc_fxnum_fast & m_num
int m_from
int m_to
sc_bv_base & m_bv
Friends
class sc_fxnum_fast
class sc_fxnum_subref
Detailed Description
Definition at line 349 of file sc_fxnum.hh.
Constructor & Destructor Documentation
sc_fxnum_fast_subref() [1/3]
sc_dt::sc_fxnum_fast_subref::sc_fxnum_fast_subref (sc_fxnum_fast & num_, int from_, int to_) inline private
Definition at line 1880 of file sc_fxnum.hh.
sc_fxnum_fast_subref() [2/3]
sc_dt::sc_fxnum_fast_subref::sc_fxnum_fast_subref (const sc_fxnum_fast_subref & a) inline
Definition at line 1888 of file sc_fxnum.hh.
~sc_fxnum_fast_subref()
sc_dt::sc_fxnum_fast_subref::~sc_fxnum_fast_subref () inline
Definition at line 1896 of file sc_fxnum.hh.
References ArmISA::a, DEFN_ASN_OP, DEFN_ASN_OP_T, DEFN_REL_OP, m_bv, m_num, and SC_FXNUM_FAST_OBSERVER_WRITE_.
sc_fxnum_fast_subref() [3/3]
sc_dt::sc_fxnum_fast_subref::sc_fxnum_fast_subref () private
Member Function Documentation
and_reduce()
bool sc_dt::sc_fxnum_fast_subref::and_reduce () const
dump()
void sc_dt::sc_fxnum_fast_subref::dump (::std::ostream & os = ::std::cout) const
Definition at line 207 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::dump(), and sc_dt::sc_fxnum_bitref::m_num.
get()
bool sc_dt::sc_fxnum_fast_subref::get () const private
Definition at line 180 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::get_slice(), and sc_dt::sc_fxnum_bitref::m_num.
length()
int sc_dt::sc_fxnum_fast_subref::length () const inline
Definition at line 2064 of file sc_fxnum.hh.
References sc_dt::sc_bv_base::length(), and m_bv.
nand_reduce()
bool sc_dt::sc_fxnum_fast_subref::nand_reduce () const
nor_reduce()
bool sc_dt::sc_fxnum_fast_subref::nor_reduce () const
operator sc_bv_base()
sc_dt::sc_fxnum_fast_subref::operator sc_bv_base () const inline
Definition at line 2141 of file sc_fxnum.hh.
References m_bv, m_num, and SC_FXNUM_FAST_OBSERVER_READ_.
or_reduce()
bool sc_dt::sc_fxnum_fast_subref::or_reduce () const
print()
void sc_dt::sc_fxnum_fast_subref::print (::std::ostream & os = ::std::cout) const
Definition at line 193 of file sc_fxnum.cc.
Referenced by sc_dt::operator<<().
scan()
void sc_dt::sc_fxnum_fast_subref::scan (::std::istream & is = ::std::cin)
Definition at line 200 of file sc_fxnum.cc.
Referenced by sc_dt::operator>>().
set()
bool sc_dt::sc_fxnum_fast_subref::set () private
Definition at line 186 of file sc_fxnum.cc.
References sc_dt::sc_fxnum_bitref::m_num, and sc_dt::sc_fxnum::set_slice().
to_int()
int sc_dt::sc_fxnum_fast_subref::to_int () const inline
Definition at line 2071 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_int().
to_int64()
int64 sc_dt::sc_fxnum_fast_subref::to_int64 () const inline
Definition at line 2079 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_int64().
to_long()
long sc_dt::sc_fxnum_fast_subref::to_long () const inline
Definition at line 2103 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_long().
to_string() [1/3]
const std::string sc_dt::sc_fxnum_fast_subref::to_string () const inline
Definition at line 2119 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_string() [2/3]
const std::string sc_dt::sc_fxnum_fast_subref::to_string (sc_numrep numrep) const inline
Definition at line 2126 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_string() [3/3]
const std::string sc_dt::sc_fxnum_fast_subref::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 2133 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_uint()
unsigned int sc_dt::sc_fxnum_fast_subref::to_uint () const inline
Definition at line 2087 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_uint().
to_uint64()
uint64 sc_dt::sc_fxnum_fast_subref::to_uint64 () const inline
Definition at line 2095 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_uint64().
to_ulong()
unsigned long sc_dt::sc_fxnum_fast_subref::to_ulong () const inline
Definition at line 2111 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_FAST_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_ulong().
xnor_reduce()
bool sc_dt::sc_fxnum_fast_subref::xnor_reduce () const
xor_reduce()
bool sc_dt::sc_fxnum_fast_subref::xor_reduce () const
Friends And Related Function Documentation
sc_fxnum_fast
friend class sc_fxnum_fast friend
Definition at line 351 of file sc_fxnum.hh.
sc_fxnum_subref
friend class sc_fxnum_subref friend
Definition at line 352 of file sc_fxnum.hh.
Member Data Documentation
m_bv
sc_bv_base& sc_dt::sc_fxnum_fast_subref::m_bv private
Definition at line 469 of file sc_fxnum.hh.
Referenced by length(), operator sc_bv_base(), to_int(), to_int64(), to_long(), to_string(), to_uint(), to_uint64(), to_ulong(), and ~sc_fxnum_fast_subref().
m_from
int sc_dt::sc_fxnum_fast_subref::m_from private
Definition at line 466 of file sc_fxnum.hh.
m_num
sc_fxnum_fast& sc_dt::sc_fxnum_fast_subref::m_num private
Definition at line 465 of file sc_fxnum.hh.
Referenced by operator sc_bv_base(), to_int(), to_int64(), to_long(), to_uint(), to_uint64(), to_ulong(), and ~sc_fxnum_fast_subref().
m_to
int sc_dt::sc_fxnum_fast_subref::m_to private
Definition at line 467 of file sc_fxnum.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum.hh
systemc/dt/fx/sc_fxnum.cc