gem5: AlphaISA::ItbPageFault Class Reference
AlphaISA::ItbPageFault Class Reference
#include <faults.hh>
Public Member Functions
ItbPageFault (Addr pc)
FaultName name () const
FaultVect vect ()
FaultStat & countStat ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Public Member Functions inherited from AlphaISA::ItbFault
ItbFault (Addr _pc)
Public Member Functions inherited from AlphaISA::AlphaFault
virtual ~AlphaFault ()
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Static Private Attributes
static FaultName _name = "itbmiss"
static FaultVect _vect = 0x0181
static FaultStat _count
Additional Inherited Members
Protected Member Functions inherited from AlphaISA::AlphaFault
virtual bool skipFaultingInstruction ()
virtual bool setRestartAddress ()
Protected Attributes inherited from AlphaISA::ItbFault
Addr pc
Detailed Description
Definition at line 246 of file faults.hh.
Constructor & Destructor Documentation
ItbPageFault()
AlphaISA::ItbPageFault::ItbPageFault (Addr pc) inline
Definition at line 254 of file faults.hh.
Member Function Documentation
countStat()
FaultStat& AlphaISA::ItbPageFault::countStat () inline virtual
Implements AlphaISA::ItbFault.
Definition at line 257 of file faults.hh.
References AlphaISA::AlphaFault::invoke(), and StaticInst::nullStaticInstPtr.
invoke()
void AlphaISA::ItbPageFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from AlphaISA::ItbFault.
Definition at line 191 of file faults.cc.
References EmulationPageTable::Entry::flags, FullSystem, ThreadContext::getITBPtr(), ThreadContext::getProcessPtr(), AlphaISA::ItbFault::invoke(), EmulationPageTable::lookup(), MipsISA::p, EmulationPageTable::Entry::paddr, AlphaISA::VAddr::page(), panic_if, MipsISA::pc, EmulationPageTable::pid(), Process::pTable, EmulationPageTable::ReadOnly, EmulationPageTable::Uncacheable, and MipsISA::vaddr.
name()
FaultName AlphaISA::ItbPageFault::name () const inline virtual
Implements AlphaISA::ItbFault.
Definition at line 255 of file faults.hh.
vect()
FaultVect AlphaISA::ItbPageFault::vect () inline virtual
Implements AlphaISA::ItbFault.
Definition at line 256 of file faults.hh.
Member Data Documentation
_count
FaultStat AlphaISA::ItbPageFault::_count static private
Definition at line 251 of file faults.hh.
_name
FaultName AlphaISA::ItbPageFault::_name = "itbmiss" static private
Definition at line 249 of file faults.hh.
_vect
FaultVect AlphaISA::ItbPageFault::_vect = 0x0181 static private
Definition at line 250 of file faults.hh.
The documentation for this class was generated from the following files:
arch/alpha/faults.hh
arch/alpha/faults.cc