gem5: LinearEquation Class Reference
LinearEquation Class Reference
This class describes a linear equation with constant coefficients.
#include <linear_solver.hh>
Public Member Functions
LinearEquation (unsigned unknowns)
LinearEquation operator+ (const LinearEquation &rhs)
LinearEquation & operator*= (const double cnt)
double & operator[] (unsigned unkw)
std::string toStr () const
unsigned cnt () const
Private Attributes
std::vector< double > eq
Coefficients.
Detailed Description
This class describes a linear equation with constant coefficients.
The equation has a certain (variable) number of unkowns and it can hold N+1 coefficients.
Definition at line 54 of file linear_solver.hh.
Constructor & Destructor Documentation
LinearEquation()
LinearEquation::LinearEquation (unsigned unknowns) inline
Definition at line 56 of file linear_solver.hh.
References eq.
Member Function Documentation
cnt()
unsigned LinearEquation::cnt () const inline
Definition at line 101 of file linear_solver.hh.
References eq.
Referenced by ThermalResistor::getEquation(), ThermalDomain::getEquation(), ThermalCapacitor::getEquation(), and operator*=().
operator*=()
LinearEquation& LinearEquation::operator*= (const double cnt) inline
Definition at line 73 of file linear_solver.hh.
References ArmISA::c, cnt(), and eq.
operator+()
LinearEquation LinearEquation::operator+ (const LinearEquation & rhs) inline
Definition at line 61 of file linear_solver.hh.
References eq, and ArmISA::i.
operator[]()
double& LinearEquation::operator[] (unsigned unkw) inline
Definition at line 81 of file linear_solver.hh.
References eq.
toStr()
std::string LinearEquation::toStr () const inline
Definition at line 87 of file linear_solver.hh.
References eq, and ArmISA::i.
Member Data Documentation
eq
std::vector<double> LinearEquation::eq private
Coefficients.
Definition at line 106 of file linear_solver.hh.
Referenced by cnt(), LinearEquation(), operator*=(), operator+(), operator[](), LinearSystem::operator[](), toStr(), and LinearSystem::toStr().
The documentation for this class was generated from the following file:
sim/linear_solver.hh