gem5: MipsISA::RemoteGDB::MipsGdbRegCache Class Reference
MipsISA::RemoteGDB::MipsGdbRegCache Class Reference
#include <remote_gdb.hh>
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct {
uint32_t gpr [32]
uint32_t sr
uint32_t lo
uint32_t hi
uint32_t badvaddr
uint32_t cause
uint32_t pc
uint32_t fpr [32]
uint32_t fsr
uint32_t fir
} r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 52 of file remote_gdb.hh.
Member Function Documentation
data()
char* MipsISA::RemoteGDB::MipsGdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 69 of file remote_gdb.hh.
References r.
getRegs()
void RemoteGDB::MipsGdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 172 of file remote_gdb.cc.
References DPRINTF, MipsISA::FLOATREG_FCCR, MipsISA::FLOATREG_FIR, MipsISA::i, MipsISA::INTREG_HI, MipsISA::INTREG_LO, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_STATUS, ThreadContext::pcState(), MipsISA::r, ThreadContext::readFloatReg(), ThreadContext::readIntReg(), and ThreadContext::readMiscRegNoEffect().
Referenced by size().
name()
const std::string MipsISA::RemoteGDB::MipsGdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 74 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::MipsGdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 189 of file remote_gdb.cc.
References DPRINTF, MipsISA::FLOATREG_FCCR, MipsISA::FLOATREG_FIR, MipsISA::i, MipsISA::INTREG_HI, MipsISA::INTREG_LO, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_STATUS, ThreadContext::pcState(), MipsISA::r, ThreadContext::setFloatReg(), ThreadContext::setIntReg(), and ThreadContext::setMiscRegNoEffect().
Referenced by size().
size()
size_t MipsISA::RemoteGDB::MipsGdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 70 of file remote_gdb.hh.
References getRegs(), r, and setRegs().
Member Data Documentation
badvaddr
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::badvaddr
Definition at line 61 of file remote_gdb.hh.
cause
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::cause
Definition at line 62 of file remote_gdb.hh.
fir
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::fir
Definition at line 66 of file remote_gdb.hh.
fpr
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::fpr[32]
Definition at line 64 of file remote_gdb.hh.
fsr
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::fsr
Definition at line 65 of file remote_gdb.hh.
gpr
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::gpr[32]
Definition at line 57 of file remote_gdb.hh.
hi
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::hi
Definition at line 60 of file remote_gdb.hh.
lo
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::lo
Definition at line 59 of file remote_gdb.hh.
pc
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::pc
Definition at line 63 of file remote_gdb.hh.
r
struct { ... } MipsISA::RemoteGDB::MipsGdbRegCache::r
Referenced by data(), and size().
sr
uint32_t MipsISA::RemoteGDB::MipsGdbRegCache::sr
Definition at line 58 of file remote_gdb.hh.
The documentation for this class was generated from the following files:
arch/mips/remote_gdb.hh
arch/mips/remote_gdb.cc