gem5: SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS > Class Template Reference
SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS > Class Template Reference
#include <SimpleBusLT.h>
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm_utils::simple_target_socket_tagged< SimpleBusLT > target_socket_type
typedef tlm_utils::simple_initiator_socket_tagged< SimpleBusLT > initiator_socket_type
Public Member Functions
SC_HAS_PROCESS (SimpleBusLT)
SimpleBusLT (sc_core::sc_module_name name)
unsigned int getPortId (const sc_dt::uint64 &address)
sc_dt::uint64 getAddressOffset (unsigned int portId)
sc_dt::uint64 getAddressMask (unsigned int portId)
unsigned int decode (const sc_dt::uint64 &address)
void initiatorBTransport (int SocketId, transaction_type &trans, sc_core::sc_time &t)
unsigned int transportDebug (int SocketId, transaction_type &trans)
bool limitRange (unsigned int portId, sc_dt::uint64 &low, sc_dt::uint64 &high)
bool getDMIPointer (int SocketId, transaction_type &trans, tlm::tlm_dmi &dmi_data)
void invalidateDMIPointers (int port_id, sc_dt::uint64 start_range, sc_dt::uint64 end_range)
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Attributes
target_socket_type target_socket [NR_OF_INITIATORS]
initiator_socket_type initiator_socket [NR_OF_TARGETS]
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
template<int NR_OF_INITIATORS, int NR_OF_TARGETS>
class SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >
Definition at line 30 of file SimpleBusLT.h.
Member Typedef Documentation
initiator_socket_type
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> typedef tlm_utils::simple_initiator_socket_tagged<SimpleBusLT> SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiator_socket_type
Definition at line 37 of file SimpleBusLT.h.
phase_type
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> typedef tlm::tlm_phase SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::phase_type
Definition at line 34 of file SimpleBusLT.h.
sync_enum_type
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> typedef tlm::tlm_sync_enum SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::sync_enum_type
Definition at line 35 of file SimpleBusLT.h.
target_socket_type
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> typedef tlm_utils::simple_target_socket_tagged<SimpleBusLT> SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::target_socket_type
Definition at line 36 of file SimpleBusLT.h.
transaction_type
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> typedef tlm::tlm_generic_payload SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transaction_type
Definition at line 33 of file SimpleBusLT.h.
Constructor & Destructor Documentation
SimpleBusLT()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT (sc_core::sc_module_name name) inline
Definition at line 45 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), ArmISA::i, SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::invalidateDMIPointers(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::register_b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::register_get_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::register_invalidate_direct_mem_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::register_transport_dbg(), and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug().
Member Function Documentation
decode()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> unsigned int SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::decode (const sc_dt::uint64 & address) inline
Definition at line 79 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getPortId().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport(), and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug().
getAddressMask()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> sc_dt::uint64 SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressMask (unsigned int portId) inline
Definition at line 74 of file SimpleBusLT.h.
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::limitRange(), and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug().
getAddressOffset()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> sc_dt::uint64 SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressOffset (unsigned int portId) inline
Definition at line 69 of file SimpleBusLT.h.
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::limitRange().
getDMIPointer()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> bool SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer (int SocketId, transaction_type & trans, tlm::tlm_dmi & dmi_data) inline
Definition at line 139 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::decode(), tlm::tlm_generic_payload::get_address(), tlm::tlm_dmi::get_end_address(), tlm::tlm_dmi::get_start_address(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressMask(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::limitRange(), tlm::tlm_generic_payload::set_address(), tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT().
getPortId()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> unsigned int SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getPortId (const sc_dt::uint64 & address) inline
Definition at line 64 of file SimpleBusLT.h.
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::decode().
initiatorBTransport()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> void SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport (int SocketId, transaction_type & trans, sc_core::sc_time & t) inline
Definition at line 95 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::decode(), tlm::tlm_generic_payload::get_address(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressMask(), and tlm::tlm_generic_payload::set_address().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT().
invalidateDMIPointers()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> void SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::invalidateDMIPointers (int port_id, sc_dt::uint64 start_range, sc_dt::uint64 end_range) inline
Definition at line 175 of file SimpleBusLT.h.
References ArmISA::i, and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::limitRange().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT().
limitRange()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> bool SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::limitRange (unsigned int portId, sc_dt::uint64 & low, sc_dt::uint64 & high) inline
Definition at line 119 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressMask(), and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressOffset().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), and SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::invalidateDMIPointers().
SC_HAS_PROCESS()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SC_HAS_PROCESS (SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >)
transportDebug()
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> unsigned int SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug (int SocketId, transaction_type & trans) inline
Definition at line 108 of file SimpleBusLT.h.
References SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::decode(), tlm::tlm_generic_payload::get_address(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getAddressMask(), and tlm::tlm_generic_payload::set_address().
Referenced by SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT().
Member Data Documentation
initiator_socket
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> initiator_socket_type SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiator_socket[NR_OF_TARGETS]
Definition at line 41 of file SimpleBusLT.h.
target_socket
template<int NR_OF_INITIATORS, int NR_OF_TARGETS> target_socket_type SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::target_socket[NR_OF_INITIATORS]
Definition at line 40 of file SimpleBusLT.h.
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleBusLT.h