gem5: ArmISA::TLBIALL Class Reference
ArmISA::TLBIALL Class Reference
TLB Invalidate All.
#include <tlbi_op.hh>
Public Member Functions
TLBIALL (ExceptionLevel _targetEL, bool _secure)
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Additional Inherited Members
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
TLB Invalidate All.
Definition at line 86 of file tlbi_op.hh.
Constructor & Destructor Documentation
TLBIALL()
ArmISA::TLBIALL::TLBIALL (ExceptionLevel _targetEL, bool _secure) inline
Definition at line 89 of file tlbi_op.hh.
References ArmISA::TLBIOp::operator()().
Member Function Documentation
operator()()
void ArmISA::TLBIALL::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 48 of file tlbi_op.cc.
References ArmISA::TLB::flushAllSecurity(), ThreadContext::getCheckerCpuPtr(), ArmISA::getDTBPtr(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc