gem5: ArmISA::TLBIASID Class Reference
ArmISA::TLBIASID Class Reference
TLB Invalidate by ASID match.
#include <tlbi_op.hh>
Public Member Functions
TLBIASID (ExceptionLevel _targetEL, bool _secure, uint16_t _asid)
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
uint16_t asid
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
TLB Invalidate by ASID match.
Definition at line 123 of file tlbi_op.hh.
Constructor & Destructor Documentation
TLBIASID()
ArmISA::TLBIASID::TLBIASID (ExceptionLevel _targetEL, bool _secure, uint16_t _asid) inline
Definition at line 126 of file tlbi_op.hh.
References ArmISA::TLBIOp::operator()().
Member Function Documentation
operator()()
void ArmISA::TLBIASID::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 76 of file tlbi_op.cc.
References ArmISA::asid, ArmISA::TLB::flushAsid(), ThreadContext::getCheckerCpuPtr(), ArmISA::getDTBPtr(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
Member Data Documentation
asid
uint16_t ArmISA::TLBIASID::asid protected
Definition at line 133 of file tlbi_op.hh.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc