gem5: Network Class Reference
Network Class Reference abstract
#include <Network.hh>
Classes
struct AddrMapNode
class StatsCallback
Callback class used for collating statistics from all the controller of this type.
Public Types
typedef RubyNetworkParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Network (const Params *p)
const Params * params () const
virtual ~Network ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
int getNumNodes () const
void setToNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void setFromNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type)
virtual void makeExtOutLink (SwitchID src, NodeID dest, BasicLink *link, const NetDest &routing_table_entry)=0
virtual void makeExtInLink (NodeID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry)=0
virtual void makeInternalLink (SwitchID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry, PortDirection src_outport, PortDirection dst_inport)=0
virtual void collateStats ()=0
virtual void print (std::ostream &out) const =0
virtual bool functionalRead (Packet *pkt)
virtual uint32_t functionalWrite (Packet *pkt)
NodeID addressToNodeID (Addr addr, MachineType mtype)
Map an address to the correct NodeID.
Port & getPort (const std::string &, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Static Public Member Functions
static uint32_t getNumberOfVirtualNetworks ()
static uint32_t MessageSizeType_to_int (MessageSizeType size_type)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions
Network (const Network &obj)
Network & operator= (const Network &obj)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
uint32_t m_nodes
std::vector< std::string > m_vnet_type_names
Topology * m_topology_ptr
std::vector< std::vector< MessageBuffer * > > m_toNetQueues
std::vector< std::vector< MessageBuffer * > > m_fromNetQueues
std::vector< bool > m_ordered
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static uint32_t m_virtual_networks
static uint32_t m_control_msg_size
static uint32_t m_data_msg_size
Private Attributes
std::unordered_multimap< MachineType, AddrMapNode > addrMap
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 76 of file Network.hh.
Member Typedef Documentation
Params
typedef RubyNetworkParams Network::Params
Definition at line 79 of file Network.hh.
Constructor & Destructor Documentation
Network() [1/2]
Network::Network (const Params * p)
Definition at line 52 of file Network.cc.
References addrMap, AbstractController::getAddrRanges(), AbstractController::getMachineID(), MachineID::getNum(), MachineID::getType(), ArmISA::i, Network::AddrMapNode::id, AbstractController::initNetworkPtr(), m_control_msg_size, m_fromNetQueues, m_nodes, m_ordered, m_toNetQueues, m_topology_ptr, m_virtual_networks, m_vnet_type_names, BasicExtLink::params(), params(), and Stats::registerDumpCallback().
Referenced by getPort().
~Network()
Network::~Network () virtual
Definition at line 108 of file Network.cc.
References m_fromNetQueues, m_nodes, m_toNetQueues, and m_topology_ptr.
Referenced by params().
Network() [2/2]
Network::Network (const Network & obj) protected
Member Function Documentation
addressToNodeID()
NodeID Network::addressToNodeID (Addr addr, MachineType mtype)
Map an address to the correct NodeID.
This function traverses the global address map to find the NodeID that corresponds to the given address and the type of the destination. For example for a request to a directory this function will return the NodeID of the right directory.
Parameters
the destination address
the type of the destination
Returns
the NodeID of the destination
Definition at line 199 of file Network.cc.
References addrMap, Network::AddrMapNode::id, and Network::AddrMapNode::ranges.
Referenced by functionalWrite(), and AbstractController::mapAddressToMachine().
checkNetworkAllocation()
void Network::checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type) virtual
Definition at line 161 of file Network.cc.
References fatal_if, m_nodes, m_ordered, m_virtual_networks, and m_vnet_type_names.
Referenced by getNumNodes(), setFromNetQueue(), and setToNetQueue().
collateStats()
virtual void Network::collateStats () pure virtual
Implemented in GarnetNetwork, and SimpleNetwork.
Referenced by getNumNodes(), and Network::StatsCallback::process().
functionalRead()
virtual bool Network::functionalRead (Packet * pkt) inline virtual
Reimplemented in SimpleNetwork.
Definition at line 118 of file Network.hh.
References fatal.
functionalWrite()
virtual uint32_t Network::functionalWrite (Packet * pkt) inline virtual
Reimplemented in GarnetNetwork, and SimpleNetwork.
Definition at line 120 of file Network.hh.
References addr, addressToNodeID(), and fatal.
Referenced by RubySystem::functionalWrite().
getNumberOfVirtualNetworks()
static uint32_t Network::getNumberOfVirtualNetworks () inline static
Definition at line 87 of file Network.hh.
References m_virtual_networks.
Referenced by AbstractController::init(), Throttle::regStats(), and AbstractController::resetStats().
getNumNodes()
int Network::getNumNodes () const inline
Definition at line 88 of file Network.hh.
References ArmISA::b, checkNetworkAllocation(), collateStats(), m_nodes, makeExtInLink(), makeExtOutLink(), makeInternalLink(), MessageSizeType_to_int(), print(), setFromNetQueue(), and setToNetQueue().
getPort()
Port& Network::getPort (const std::string & if_name, PortID idx = InvalidPortID) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 138 of file Network.hh.
References RubyDummyPort::instance(), Network(), and operator=().
init()
void Network::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in SimpleNetwork.
Definition at line 126 of file Network.cc.
References RubySystem::getBlockSizeBytes(), m_control_msg_size, and m_data_msg_size.
Referenced by SimpleNetwork::init(), GarnetNetwork::init(), and params().
makeExtInLink()
virtual void Network::makeExtInLink (NodeID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry) pure virtual
Implemented in GarnetNetwork, and SimpleNetwork.
Referenced by getNumNodes(), and Topology::makeLink().
makeExtOutLink()
virtual void Network::makeExtOutLink (SwitchID src, NodeID dest, BasicLink * link, const NetDest & routing_table_entry) pure virtual
Implemented in GarnetNetwork, and SimpleNetwork.
Referenced by getNumNodes(), and Topology::makeLink().
makeInternalLink()
virtual void Network::makeInternalLink (SwitchID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry, PortDirection src_outport, PortDirection dst_inport) pure virtual
Implemented in GarnetNetwork, and SimpleNetwork.
Referenced by getNumNodes(), and Topology::makeLink().
MessageSizeType_to_int()
uint32_t Network::MessageSizeType_to_int (MessageSizeType size_type) static
Definition at line 132 of file Network.cc.
References m_control_msg_size, m_data_msg_size, and panic.
Referenced by NetworkInterface::flitisizeMessage(), getNumNodes(), network_message_to_size(), SimpleNetwork::regStats(), Switch::regStats(), and Throttle::regStats().
operator=()
Network& Network::operator= (const Network & obj) protected
Referenced by getPort().
params()
const Params* Network::params () const inline
Definition at line 81 of file Network.hh.
References SimObject::_params, init(), and ~Network().
Referenced by Switch::addOutPort(), GarnetNetwork::collateStats(), and Network().
print()
virtual void Network::print (std::ostream & out) const pure virtual
Implemented in GarnetNetwork, and SimpleNetwork.
Referenced by getNumNodes(), and operator<<().
setFromNetQueue()
void Network::setFromNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer * b) virtual
Definition at line 188 of file Network.cc.
References ArmISA::b, checkNetworkAllocation(), ArmISA::id, and m_fromNetQueues.
Referenced by getNumNodes().
setToNetQueue()
void Network::setToNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer * b)
Definition at line 177 of file Network.cc.
References ArmISA::b, checkNetworkAllocation(), ArmISA::id, and m_toNetQueues.
Referenced by getNumNodes().
Member Data Documentation
addrMap
std::unordered_multimap<MachineType, AddrMapNode> Network::addrMap private
Definition at line 184 of file Network.hh.
Referenced by addressToNodeID(), and Network().
m_control_msg_size
uint32_t Network::m_control_msg_size static protected
Definition at line 152 of file Network.hh.
Referenced by init(), MessageSizeType_to_int(), and Network().
m_data_msg_size
uint32_t Network::m_data_msg_size static protected
Definition at line 153 of file Network.hh.
Referenced by init(), and MessageSizeType_to_int().
m_fromNetQueues
std::vector<std::vector<MessageBuffer*> > Network::m_fromNetQueues protected
Definition at line 157 of file Network.hh.
Referenced by GarnetNetwork::init(), SimpleNetwork::makeExtOutLink(), Network(), setFromNetQueue(), and ~Network().
m_nodes
uint32_t Network::m_nodes protected
Definition at line 148 of file Network.hh.
Referenced by checkNetworkAllocation(), getNumNodes(), GarnetNetwork::init(), SimpleNetwork::makeExtInLink(), GarnetNetwork::makeExtInLink(), SimpleNetwork::makeExtOutLink(), GarnetNetwork::makeExtOutLink(), Network(), and ~Network().
m_ordered
std::vector<bool> Network::m_ordered protected
Definition at line 158 of file Network.hh.
Referenced by checkNetworkAllocation(), SimpleNetwork::isVNetOrdered(), GarnetNetwork::isVNetOrdered(), and Network().
m_toNetQueues
std::vector<std::vector<MessageBuffer*> > Network::m_toNetQueues protected
Definition at line 156 of file Network.hh.
Referenced by GarnetNetwork::init(), SimpleNetwork::makeExtInLink(), Network(), setToNetQueue(), and ~Network().
m_topology_ptr
Topology* Network::m_topology_ptr protected
Definition at line 151 of file Network.hh.
Referenced by SimpleNetwork::init(), GarnetNetwork::init(), Network(), and ~Network().
m_virtual_networks
uint32_t Network::m_virtual_networks static protected
Definition at line 149 of file Network.hh.
Referenced by checkNetworkAllocation(), GarnetNetwork::GarnetNetwork(), getNumberOfVirtualNetworks(), SimpleNetwork::makeInternalLink(), Network(), and GarnetNetwork::regStats().
m_vnet_type_names
std::vector<std::string> Network::m_vnet_type_names protected
Definition at line 150 of file Network.hh.
Referenced by checkNetworkAllocation(), GarnetNetwork::GarnetNetwork(), and Network().
The documentation for this class was generated from the following files:
mem/ruby/network/Network.hh
mem/ruby/network/Network.cc