gem5: LinuxMipsSystem::SkipDelayLoopEvent Class Reference
LinuxMipsSystem::SkipDelayLoopEvent Class Reference
Public Member Functions
SkipDelayLoopEvent (PCEventScope *s, const std::string &desc, Addr addr)
virtual void process (ThreadContext *tc)
Public Member Functions inherited from SkipFuncEvent
SkipFuncEvent (PCEventScope *s, const std::string &desc, Addr addr)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 54 of file system.hh.
Constructor & Destructor Documentation
SkipDelayLoopEvent()
LinuxMipsSystem::SkipDelayLoopEvent::SkipDelayLoopEvent (PCEventScope * s, const std::string & desc, Addr addr) inline
Definition at line 57 of file system.hh.
References process().
Member Function Documentation
process()
void LinuxMipsSystem::SkipDelayLoopEvent::process (ThreadContext * tc) virtual
Reimplemented from SkipFuncEvent.
Definition at line 82 of file system.cc.
References ThreadContext::getSystemPtr(), SkipFuncEvent::process(), and LinuxMipsSystem::setDelayLoop().
Referenced by LinuxMipsSystem::PrintThreadInfo::PrintThreadInfo(), and SkipDelayLoopEvent().
The documentation for this class was generated from the following files:
arch/mips/linux/system.hh
arch/mips/linux/system.cc