gem5: sc_core::sc_report_handler Class Reference
sc_core::sc_report_handler Class Reference
#include <sc_report_handler.hh>
Static Public Member Functions
static void report (sc_severity, const char *msg_type, const char *msg, const char *file, int line)
static void report (sc_severity, const char *msg_type, const char *msg, int verbosity, const char *file, int line)
static void report (sc_severity, int id, const char *msg, const char *file, int line)
static sc_actions set_actions (sc_severity, sc_actions=SC_UNSPECIFIED)
static sc_actions set_actions (const char *msg_type, sc_actions=SC_UNSPECIFIED)
static sc_actions set_actions (const char *msg_type, sc_severity, sc_actions=SC_UNSPECIFIED)
static int stop_after (sc_severity, int limit=-1)
static int stop_after (const char *msg_type, int limit=-1)
static int stop_after (const char *msg_type, sc_severity, int limit=-1)
static int get_count (sc_severity)
static int get_count (const char *msg_type)
static int get_count (const char *msg_type, sc_severity)
static int set_verbosity_level (int)
static int get_verbosity_level ()
static sc_actions suppress (sc_actions)
static sc_actions suppress ()
static sc_actions force (sc_actions)
static sc_actions force ()
static sc_actions set_catch_actions (sc_actions)
static sc_actions get_catch_actions ()
static void set_handler (sc_report_handler_proc)
static void default_handler (const sc_report &, const sc_actions &)
static sc_actions get_new_action_id ()
static sc_report * get_cached_report ()
static void clear_cached_report ()
static bool set_log_file_name (const char *)
static const char * get_log_file_name ()
Detailed Description
Definition at line 66 of file sc_report_handler.hh.
Member Function Documentation
clear_cached_report()
void sc_core::sc_report_handler::clear_cached_report () static
Definition at line 324 of file sc_report_handler.cc.
References sc_gem5::Scheduler::current(), sc_gem5::globalReportCache, sc_gem5::Process::lastReport(), and sc_gem5::scheduler.
default_handler()
void sc_core::sc_report_handler::default_handler (const sc_report & report, const sc_actions & actions) static
Definition at line 280 of file sc_report_handler.cc.
References ccprintf(), cprintf(), sc_gem5::Scheduler::current(), sc_core::sc_report::get_msg_type(), sc_core::sc_report::get_severity(), sc_core::sc_report::get_time(), sc_gem5::Process::isUnwinding(), report(), sc_core::SC_ABORT, sc_core::sc_abort(), sc_core::SC_DISPLAY, sc_core::SC_INTERRUPT, sc_core::sc_interrupt_here(), sc_core::SC_LOG, sc_core::sc_report_compose_message(), sc_core::SC_STOP, sc_core::sc_stop(), sc_core::sc_stop_here(), sc_core::SC_THROW, sc_gem5::scheduler, and sc_core::sc_time::to_string().
force() [1/2]
sc_actions sc_core::sc_report_handler::force (sc_actions actions) static
Definition at line 244 of file sc_report_handler.cc.
References sc_gem5::reportForcedActions.
force() [2/2]
sc_actions sc_core::sc_report_handler::force () static
Definition at line 252 of file sc_report_handler.cc.
References sc_core::SC_UNSPECIFIED.
get_cached_report()
sc_report * sc_core::sc_report_handler::get_cached_report () static
Definition at line 315 of file sc_report_handler.cc.
References sc_gem5::Scheduler::current(), sc_gem5::globalReportCache, sc_gem5::Process::lastReport(), and sc_gem5::scheduler.
get_catch_actions()
sc_actions sc_core::sc_report_handler::get_catch_actions () static
Definition at line 267 of file sc_report_handler.cc.
References sc_gem5::reportCatchActions.
Referenced by sc_gem5::ScMainFiber::main(), and sc_gem5::Scheduler::throwUp().
get_count() [1/3]
int sc_core::sc_report_handler::get_count (sc_severity severity) static
Definition at line 191 of file sc_report_handler.cc.
References sc_gem5::ReportSevInfo::count, and sc_gem5::reportSevInfos.
get_count() [2/3]
int sc_core::sc_report_handler::get_count (const char * msg_type) static
Definition at line 197 of file sc_report_handler.cc.
References sc_gem5::reportMsgInfoMap(), and sc_core::SC_ID_UNKNOWN_ERROR_.
get_count() [3/3]
int sc_core::sc_report_handler::get_count (const char * msg_type, sc_severity severity) static
Definition at line 206 of file sc_report_handler.cc.
References sc_gem5::reportMsgInfoMap(), and sc_core::SC_ID_UNKNOWN_ERROR_.
get_log_file_name()
const char * sc_core::sc_report_handler::get_log_file_name () static
Definition at line 351 of file sc_report_handler.cc.
get_new_action_id()
sc_actions sc_core::sc_report_handler::get_new_action_id () static
Definition at line 307 of file sc_report_handler.cc.
References sc_core::SC_ABORT.
get_verbosity_level()
int sc_core::sc_report_handler::get_verbosity_level () static
Definition at line 223 of file sc_report_handler.cc.
References sc_gem5::reportVerbosityLevel.
report() [1/3]
void sc_core::sc_report_handler::report (sc_severity severity, const char * msg_type, const char * msg, const char * file, int line) static
Definition at line 55 of file sc_report_handler.cc.
References sc_core::SC_MEDIUM.
Referenced by default_handler(), and report().
report() [2/3]
void sc_core::sc_report_handler::report (sc_severity severity, const char * msg_type, const char * msg, int verbosity, const char * file, int line) static
Definition at line 62 of file sc_report_handler.cc.
References sc_gem5::ReportMsgInfo::actions, sc_gem5::ReportSevInfo::actions, sc_gem5::ReportSevInfo::checkLimit(), sc_gem5::ReportMsgInfo::checkLimits(), sc_gem5::ReportMsgInfo::count, sc_gem5::ReportSevInfo::count, sc_gem5::Scheduler::current(), sc_core::sc_time::from_value(), sc_gem5::globalReportCache, sc_gem5::ReportMsgInfo::id, sc_gem5::Process::lastReport(), sc_core::sc_object::name(), report(), sc_gem5::reportForcedActions, sc_gem5::reportHandlerProc, sc_gem5::reportMsgInfoMap(), sc_gem5::reportSevInfos, sc_gem5::reportSuppressedActions, sc_gem5::reportVerbosityLevel, sc_core::SC_CACHE_REPORT, sc_core::SC_ID_UNKNOWN_ERROR_, sc_core::SC_INFO, sc_core::SC_UNSPECIFIED, sc_gem5::scheduler, sc_gem5::ReportMsgInfo::sevActions, and sc_gem5::ReportMsgInfo::sevCounts.
report() [3/3]
void sc_core::sc_report_handler::report (sc_severity severity, int id, const char * msg, const char * file, int line) static
Definition at line 111 of file sc_report_handler.cc.
References ArmISA::id, report(), sc_gem5::reportIdToMsgMap(), sc_gem5::reportWarningsAsErrors, sc_core::SC_ERROR, and sc_core::SC_WARNING.
set_actions() [1/3]
sc_actions sc_core::sc_report_handler::set_actions (sc_severity severity, sc_actions actions = SC_UNSPECIFIED) static
Definition at line 123 of file sc_report_handler.cc.
References sc_gem5::ReportSevInfo::actions, and sc_gem5::reportSevInfos.
set_actions() [2/3]
sc_actions sc_core::sc_report_handler::set_actions (const char * msg_type, sc_actions actions = SC_UNSPECIFIED) static
Definition at line 132 of file sc_report_handler.cc.
References sc_gem5::ReportMsgInfo::actions, sc_gem5::reportMsgInfoMap(), and sc_core::SC_ID_UNKNOWN_ERROR_.
set_actions() [3/3]
sc_actions sc_core::sc_report_handler::set_actions (const char * msg_type, sc_severity severity, sc_actions actions = SC_UNSPECIFIED) static
Definition at line 144 of file sc_report_handler.cc.
References sc_gem5::reportMsgInfoMap(), sc_core::SC_ID_UNKNOWN_ERROR_, and sc_gem5::ReportMsgInfo::sevActions.
set_catch_actions()
sc_actions sc_core::sc_report_handler::set_catch_actions (sc_actions actions) static
Definition at line 259 of file sc_report_handler.cc.
References sc_gem5::reportCatchActions.
set_handler()
void sc_core::sc_report_handler::set_handler (sc_report_handler_proc proc) static
Definition at line 274 of file sc_report_handler.cc.
References sc_gem5::reportHandlerProc.
Referenced by sc_gem5::reportifyException().
set_log_file_name()
bool sc_core::sc_report_handler::set_log_file_name (const char * new_name) static
Definition at line 335 of file sc_report_handler.cc.
set_verbosity_level()
int sc_core::sc_report_handler::set_verbosity_level (int vl) static
Definition at line 215 of file sc_report_handler.cc.
References sc_gem5::reportVerbosityLevel.
stop_after() [1/3]
int sc_core::sc_report_handler::stop_after (sc_severity severity, int limit = -1) static
Definition at line 157 of file sc_report_handler.cc.
References sc_gem5::ReportSevInfo::limit, X86ISA::limit, and sc_gem5::reportSevInfos.
stop_after() [2/3]
int sc_core::sc_report_handler::stop_after (const char * msg_type, int limit = -1) static
Definition at line 166 of file sc_report_handler.cc.
References sc_gem5::ReportMsgInfo::limit, X86ISA::limit, sc_gem5::reportMsgInfoMap(), and sc_core::SC_ID_UNKNOWN_ERROR_.
stop_after() [3/3]
int sc_core::sc_report_handler::stop_after (const char * msg_type, sc_severity severity, int limit = -1) static
Definition at line 178 of file sc_report_handler.cc.
References X86ISA::limit, sc_gem5::reportMsgInfoMap(), sc_core::SC_ID_UNKNOWN_ERROR_, and sc_gem5::ReportMsgInfo::sevLimits.
suppress() [1/2]
sc_actions sc_core::sc_report_handler::suppress (sc_actions actions) static
Definition at line 230 of file sc_report_handler.cc.
References sc_gem5::reportSuppressedActions.
suppress() [2/2]
sc_actions sc_core::sc_report_handler::suppress () static
Definition at line 238 of file sc_report_handler.cc.
References sc_core::SC_UNSPECIFIED.
The documentation for this class was generated from the following files:
systemc/ext/utils/sc_report_handler.hh
systemc/utils/sc_report_handler.cc