gem5: ImgWriter Class Reference
ImgWriter Class Reference abstract
#include <imgwriter.hh>
Public Member Functions
ImgWriter (const FrameBuffer *_fb)
virtual ~ImgWriter ()
virtual void write (std::ostream &out) const =0
Write the frame buffer data into the provided ostream.
virtual const char * getImgExtension () const =0
Protected Attributes
const FrameBuffer & fb
Detailed Description
Definition at line 50 of file imgwriter.hh.
Constructor & Destructor Documentation
ImgWriter()
ImgWriter::ImgWriter (const FrameBuffer * _fb) inline
Definition at line 53 of file imgwriter.hh.
~ImgWriter()
virtual ImgWriter::~ImgWriter () inline virtual
Definition at line 57 of file imgwriter.hh.
References getImgExtension(), and write().
Member Function Documentation
getImgExtension()
virtual const char* ImgWriter::getImgExtension () const pure virtual
Implemented in BmpWriter, and PngWriter.
Referenced by ~ImgWriter().
write()
virtual void ImgWriter::write (std::ostream & out) const pure virtual
Write the frame buffer data into the provided ostream.
Parameters
out output stream to write to
Implemented in BmpWriter, and PngWriter.
Referenced by ~ImgWriter().
Member Data Documentation
fb
const FrameBuffer& ImgWriter::fb protected
Definition at line 72 of file imgwriter.hh.
Referenced by BmpWriter::getCompleteHeader(), PngWriter::write(), and BmpWriter::write().
The documentation for this class was generated from the following file:
base/imgwriter.hh