gem5: MSHR Class Reference
MSHR Class Reference
Miss Status and handling Register.
#include <mshr.hh>
Classes
class Target
class TargetList
Public Types
typedef std::list< MSHR * > List
A list of MSHRs.
typedef List::iterator Iterator
MSHR list iterator.
Public Member Functions
bool needsWritable () const
The pending* and post* flags are only valid if inService is true.
bool isCleaning () const
bool isPendingModified () const
bool hasPostInvalidate () const
bool hasPostDowngrade () const
bool sendPacket (BaseCache &cache) override
Send this queue entry as a downstream packet, with the exact behaviour depending on the specific entry type.
bool allocOnFill () const
bool hasFromCache () const
Determine if there are non-deferred requests from other caches.
bool isWholeLineWrite () const
Check if this MSHR contains only compatible writes, and if they span the entire cache line.
void allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order, bool alloc_on_fill)
Allocate a miss to this MSHR.
void markInService (bool pending_modified_resp)
void clearDownstreamPending ()
void deallocate ()
Mark this MSHR as free.
void allocateTarget (PacketPtr target, Tick when, Counter order, bool alloc_on_fill)
Add a request to the list of targets.
bool handleSnoop (PacketPtr target, Counter order)
MSHR ()
A simple constructor.
int getNumTargets () const
Returns the current number of allocated targets.
TargetList extractServiceableTargets (PacketPtr pkt)
Extracts the subset of the targets that can be serviced given a received response.
bool hasTargets () const
Returns true if there are targets left.
QueueEntry::Target * getTarget () override
Returns a reference to the first target.
void popTarget ()
Pop first target.
bool promoteDeferredTargets ()
void promoteReadable ()
Promotes deferred targets that do not require writable.
void promoteWritable ()
Promotes deferred targets that do not require writable.
bool trySatisfyFunctional (PacketPtr pkt)
void delay (Tick delay_ticks)
Adds a delay relative to the current tick to the current MSHR.
void print (std::ostream &os, int verbosity=0, const std::string &prefix="") const override
Prints the contents of this MSHR for debugging.
std::string print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
bool matchBlockAddr (const Addr addr, const bool is_secure) const override
Check if entry corresponds to the one being looked for.
bool matchBlockAddr (const PacketPtr pkt) const override
Check if entry contains a packet that corresponds to the one being looked for.
bool conflictAddr (const QueueEntry *entry) const override
Check if given entry's packets conflict with this' entries packets.
Public Member Functions inherited from QueueEntry
QueueEntry ()
bool isUncacheable () const
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Public Member Functions inherited from Printable
Printable ()
virtual ~Printable ()
Public Attributes
bool wasWholeLineWrite
Track if we sent this as a whole line write or not.
bool isForward
True if the entry is just a simple forward from an upper level.
Public Attributes inherited from QueueEntry
bool inService
True if the entry has been sent downstream.
Counter order
Order number assigned to disambiguate writes and misses.
Addr blkAddr
Block aligned address.
unsigned blkSize
Block size of the cache.
bool isSecure
True if the entry targets the secure memory space.
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Private Member Functions
void promoteIf (const std::function< bool(Target &)> &pred)
Promotes deferred targets that satisfy a predicate.
Private Attributes
bool downstreamPending
Flag set by downstream caches.
bool pendingModified
Here we use one flag to track both if:
bool postInvalidate
Did we snoop an invalidate while waiting for data?
bool postDowngrade
Did we snoop a read while waiting for data?
Iterator readyIter
Pointer to this MSHR on the ready list.
Iterator allocIter
Pointer to this MSHR on the allocated list.
TargetList targets
List of all requests that match the address.
TargetList deferredTargets
Friends
template<typename Entry >
class Queue
Consider the queues friends to avoid making everything public.
class MSHRQueue
Additional Inherited Members
Protected Attributes inherited from QueueEntry
Tick readyTime
Tick when ready to issue.
bool _isUncacheable
True if the entry is uncacheable.
Detailed Description
Miss Status and handling Register.
This class keeps all the information needed to handle a cache miss including a list of target requests.
See also
gem5 Memory System
Definition at line 72 of file mshr.hh.
Member Typedef Documentation
Iterator
typedef List::iterator MSHR::Iterator
MSHR list iterator.
Definition at line 337 of file mshr.hh.
List
typedef std::list<MSHR *> MSHR::List
A list of MSHRs.
Definition at line 335 of file mshr.hh.
Constructor & Destructor Documentation
MSHR()
MSHR::MSHR ()
A simple constructor.
Definition at line 64 of file mshr.cc.
Referenced by isWholeLineWrite().
Member Function Documentation
allocate()
void MSHR::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order, bool alloc_on_fill)
Allocate a miss to this MSHR.
Parameters
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original miss.
when_ready When should the MSHR be ready to act upon.
_order The logical order of this MSHR
alloc_on_fill Should the cache allocate a block on fill
Definition at line 253 of file mshr.cc.
References QueueEntry::_isUncacheable, MSHR::TargetList::add(), MSHR::TargetList::blkAddr, MSHR::TargetList::blkSize, Packet::cmd, deferredTargets, downstreamPending, MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MemCmd::HardPFReq, MSHR::TargetList::init(), QueueEntry::inService, isForward, QueueEntry::isSecure, Packet::isSecure(), Packet::matchBlockAddr(), QueueEntry::order, QueueEntry::readyTime, Packet::req, targets, and wasWholeLineWrite.
Referenced by MSHRQueue::allocate(), and isWholeLineWrite().
allocateTarget()
void MSHR::allocateTarget (PacketPtr target, Tick when, Counter order, bool alloc_on_fill)
Add a request to the list of targets.
Parameters
target The target.
Definition at line 326 of file mshr.cc.
References MSHR::TargetList::add(), Packet::cmd, deferredTargets, MSHR::Target::FromCPU, MemCmd::HardPFReq, hasPostDowngrade(), hasPostInvalidate(), QueueEntry::inService, isForward, isPendingModified(), Packet::needsWritable(), replaceUpgrade(), Packet::req, and targets.
Referenced by BaseCache::handleTimingReqMiss(), and isWholeLineWrite().
allocOnFill()
bool MSHR::allocOnFill () const inline
Definition at line 366 of file mshr.hh.
References MSHR::TargetList::allocOnFill, and targets.
Referenced by BaseCache::recvTimingResp().
clearDownstreamPending()
void MSHR::clearDownstreamPending ()
Definition at line 283 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), downstreamPending, and targets.
Referenced by MSHR::TargetList::isReset(), isWholeLineWrite(), and MSHR::TargetList::replaceUpgrades().
conflictAddr()
bool MSHR::conflictAddr (const QueueEntry * entry) const override virtual
Check if given entry's packets conflict with this' entries packets.
Parameters
entry Other entry to compare against.
Returns
True if entry matches given information.
Implements QueueEntry.
Definition at line 709 of file mshr.cc.
References MSHR::TargetList::blkAddr, hasTargets(), QueueEntry::isSecure, and QueueEntry::matchBlockAddr().
Referenced by delay().
deallocate()
void MSHR::deallocate ()
Mark this MSHR as free.
Definition at line 314 of file mshr.cc.
References deferredTargets, QueueEntry::inService, MSHR::TargetList::isReset(), MSHR::TargetList::resetFlags(), and targets.
Referenced by isWholeLineWrite().
delay()
void MSHR::delay (Tick delay_ticks) inline
Adds a delay relative to the current tick to the current MSHR.
Parameters
delay_ticks the desired delay in ticks
Definition at line 524 of file mshr.hh.
References addr, conflictAddr(), curTick(), matchBlockAddr(), X86ISA::os, print(), and QueueEntry::Target::readyTime.
Referenced by MSHRQueue::delay().
extractServiceableTargets()
MSHR::TargetList MSHR::extractServiceableTargets (PacketPtr pkt)
Extracts the subset of the targets that can be serviced given a received response.
This function returns the targets list unless the response is a ReadRespWithInvalidate. The ReadRespWithInvalidate is only invalidating response that its invalidation was not expected when the request (a ReadSharedReq) was sent out. For ReadRespWithInvalidate we can safely service only the first FromCPU target and all FromSnoop targets (inform all snoopers that we no longer have the block).
Parameters
pkt The response from the downstream memory
Definition at line 496 of file mshr.cc.
References MSHR::TargetList::blkAddr, MSHR::TargetList::blkSize, Packet::cmd, MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MSHR::Target::FromSnoop, MSHR::TargetList::init(), MSHR::TargetList::populateFlags(), MemCmd::ReadRespWithInvalidate, and targets.
Referenced by getNumTargets(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
getNumTargets()
int MSHR::getNumTargets () const inline
Returns the current number of allocated targets.
Returns
The current number of allocated targets.
Definition at line 456 of file mshr.hh.
References extractServiceableTargets().
Referenced by BaseCache::handleTimingReqMiss(), Cache::recvTimingSnoopReq(), and NoncoherentCache::serviceMSHRTargets().
getTarget()
QueueEntry::Target* MSHR::getTarget () inline override virtual
Returns a reference to the first target.
Returns
A pointer to the first target.
Implements QueueEntry.
Definition at line 483 of file mshr.hh.
References hasTargets().
Referenced by BaseCache::recvTimingResp(), Cache::sendMSHRQueuePacket(), BaseCache::sendMSHRQueuePacket(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
handleSnoop()
bool MSHR::handleSnoop (PacketPtr target, Counter order)
Definition at line 371 of file mshr.cc.
References MSHR::TargetList::add(), MSHR::TargetList::blkSize, Packet::cmd, curTick(), deferredTargets, downstreamPending, DPRINTF, MSHR::Target::FromSnoop, hasPostInvalidate(), Packet::id, QueueEntry::inService, Packet::isClean(), Packet::isExpressSnoop(), Packet::isInvalidate(), isPendingModified(), name(), Packet::needsResponse(), MSHR::TargetList::needsWritable, Packet::needsWritable(), panic_if, postDowngrade, postInvalidate, Packet::print(), MSHR::TargetList::replaceUpgrades(), Packet::req, Packet::setCacheResponding(), Packet::setHasSharers(), Packet::setResponderHadWritable(), Packet::setSatisfied(), and targets.
Referenced by isWholeLineWrite(), and Cache::recvTimingSnoopReq().
hasFromCache()
bool MSHR::hasFromCache () const inline
Determine if there are non-deferred requests from other caches.
Returns
true if any of the targets is from another cache
Definition at line 375 of file mshr.hh.
References MSHR::TargetList::hasFromCache, promoteIf(), and targets.
hasPostDowngrade()
bool MSHR::hasPostDowngrade () const inline
Definition at line 360 of file mshr.hh.
References QueueEntry::inService, postDowngrade, and sendPacket().
Referenced by allocateTarget(), promoteWritable(), and Cache::serviceMSHRTargets().
hasPostInvalidate()
bool MSHR::hasPostInvalidate () const inline
Definition at line 356 of file mshr.hh.
References QueueEntry::inService, and postInvalidate.
Referenced by allocateTarget(), handleSnoop(), promoteReadable(), promoteWritable(), and Cache::serviceMSHRTargets().
hasTargets()
bool MSHR::hasTargets () const inline
Returns true if there are targets left.
Returns
true if there are targets
Definition at line 477 of file mshr.hh.
Referenced by conflictAddr(), MSHRQueue::forceDeallocateTarget(), getTarget(), and matchBlockAddr().
isCleaning()
bool MSHR::isCleaning () const inline
Definition at line 347 of file mshr.hh.
References Packet::isClean(), QueueEntry::Target::pkt, and targets.
Referenced by BaseCache::allocateBlock().
isPendingModified()
bool MSHR::isPendingModified () const inline
Definition at line 352 of file mshr.hh.
References QueueEntry::inService, and pendingModified.
Referenced by allocateTarget(), BaseCache::functionalAccess(), and handleSnoop().
isWholeLineWrite()
bool MSHR::isWholeLineWrite () const inline
Check if this MSHR contains only compatible writes, and if they span the entire cache line.
This is used as part of the miss-packet creation. Note that new requests may arrive after a miss-packet has been created, and for the fill we therefore use the wasWholeLineWrite field.
Definition at line 416 of file mshr.hh.
References allocate(), allocateTarget(), clearDownstreamPending(), deallocate(), handleSnoop(), MSHR::TargetList::isWholeLineWrite(), markInService(), MSHR(), QueueEntry::Target::order, and QueueEntry::Target::pkt.
Referenced by BaseCache::sendMSHRQueuePacket(), and MSHR::TargetList::updateWriteFlags().
markInService()
void MSHR::markInService (bool pending_modified_resp)
Definition at line 293 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), downstreamPending, QueueEntry::inService, MSHR::TargetList::isWholeLineWrite(), MSHR::TargetList::needsWritable, pendingModified, postDowngrade, postInvalidate, targets, and wasWholeLineWrite.
Referenced by isWholeLineWrite(), and MSHRQueue::markInService().
matchBlockAddr() [1/2]
bool MSHR::matchBlockAddr (const Addr addr, const bool is_secure) const override virtual
Check if entry corresponds to the one being looked for.
Parameters
addr Address to match against.
is_secure Whether the target should be in secure space or not.
Returns
True if entry matches given information.
Implements QueueEntry.
Definition at line 695 of file mshr.cc.
References MSHR::TargetList::blkAddr, hasTargets(), and QueueEntry::isSecure.
Referenced by delay().
matchBlockAddr() [2/2]
bool MSHR::matchBlockAddr (const PacketPtr pkt) const override virtual
Check if entry contains a packet that corresponds to the one being looked for.
Parameters
pkt The packet to search for.
Returns
True if any of its targets' packets matches the given one.
Implements QueueEntry.
Definition at line 702 of file mshr.cc.
References MSHR::TargetList::blkAddr, MSHR::TargetList::blkSize, hasTargets(), QueueEntry::isSecure, and Packet::matchBlockAddr().
needsWritable()
bool MSHR::needsWritable () const inline
The pending* and post* flags are only valid if inService is true.
Using the accessor functions lets us detect if these flags are accessed improperly.True if we need to get a writable copy of the block.
Definition at line 345 of file mshr.hh.
References MSHR::TargetList::needsWritable, and targets.
Referenced by BaseCache::allocateBlock(), and BaseCache::sendMSHRQueuePacket().
popTarget()
void MSHR::popTarget () inline
Pop first target.
Definition at line 492 of file mshr.hh.
References promoteDeferredTargets(), promoteReadable(), promoteWritable(), and trySatisfyFunctional().
Referenced by MSHRQueue::forceDeallocateTarget().
print() [1/2]
void MSHR::print (std::ostream & os, int verbosity = 0, const std::string & prefix = "") const override virtual
Prints the contents of this MSHR for debugging.
Implements Printable.
Definition at line 661 of file mshr.cc.
References QueueEntry::_isUncacheable, MSHR::TargetList::allocOnFill, MSHR::TargetList::blkAddr, MSHR::TargetList::blkSize, ccprintf(), deferredTargets, downstreamPending, MSHR::TargetList::hasFromCache, QueueEntry::inService, isForward, QueueEntry::isSecure, MSHR::TargetList::needsWritable, postDowngrade, postInvalidate, MSHR::TargetList::print(), and targets.
Referenced by Cache::recvTimingSnoopReq().
print() [2/2]
std::string MSHR::print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
Returns
string with mshr fields + [deferred]targets
Definition at line 687 of file mshr.cc.
References MSHR::TargetList::print().
Referenced by delay(), and MSHR::TargetList::isReset().
promoteDeferredTargets()
bool MSHR::promoteDeferredTargets ()
Definition at line 530 of file mshr.cc.
References curTick(), deferredTargets, QueueEntry::order, MSHR::TargetList::populateFlags(), QueueEntry::readyTime, ArmISA::t, and targets.
Referenced by MSHRQueue::forceDeallocateTarget(), popTarget(), and BaseCache::recvTimingResp().
promoteIf()
void MSHR::promoteIf (const std::function< bool(Target &)> & pred) private
Promotes deferred targets that satisfy a predicate.
Deferred targets are promoted to the target list if they satisfy a given condition. The operation stops at the first deferred target that doesn't satisfy the condition.
Parameters
pred A condition on a Target
Definition at line 569 of file mshr.cc.
References MSHR::TargetList::clearDownstreamPending(), deferredTargets, downstreamPending, MSHR::TargetList::populateFlags(), and targets.
Referenced by hasFromCache(), promoteReadable(), and promoteWritable().
promoteReadable()
void MSHR::promoteReadable ()
Promotes deferred targets that do not require writable.
Move targets from the deferred targets list to the target list starting from the first deferred target until the first target that is a cache maintenance operation or needs a writable copy of the block
Definition at line 592 of file mshr.cc.
References deferredTargets, MSHR::Target::FromCPU, hasPostInvalidate(), promoteIf(), and ArmISA::t.
Referenced by popTarget(), and BaseCache::recvTimingResp().
promoteWritable()
void MSHR::promoteWritable ()
Promotes deferred targets that do not require writable.
Requests in the deferred target list are moved to the target list up until the first target that is a cache maintenance operation or needs a writable copy of the block
Definition at line 613 of file mshr.cc.
References deferredTargets, MSHR::Target::FromCPU, hasPostDowngrade(), hasPostInvalidate(), MSHR::TargetList::needsWritable, promoteIf(), Packet::req, ArmISA::t, and targets.
Referenced by popTarget(), and BaseCache::recvTimingResp().
sendPacket()
bool MSHR::sendPacket (BaseCache & cache) override virtual
Send this queue entry as a downstream packet, with the exact behaviour depending on the specific entry type.
Implements QueueEntry.
Definition at line 655 of file mshr.cc.
References BaseCache::sendMSHRQueuePacket().
Referenced by hasPostDowngrade().
trySatisfyFunctional()
bool MSHR::trySatisfyFunctional (PacketPtr pkt)
Definition at line 640 of file mshr.cc.
References MSHR::TargetList::blkAddr, MSHR::TargetList::blkSize, deferredTargets, Packet::isPrint(), QueueEntry::isSecure, targets, MSHR::TargetList::trySatisfyFunctional(), and Packet::trySatisfyFunctional().
Referenced by MSHR::TargetList::isReset(), and popTarget().
Friends And Related Function Documentation
MSHRQueue
friend class MSHRQueue friend
Definition at line 80 of file mshr.hh.
Queue
template<typename Entry > friend class Queue friend
Consider the queues friends to avoid making everything public.
Definition at line 79 of file mshr.hh.
Member Data Documentation
allocIter
Iterator MSHR::allocIter private
Pointer to this MSHR on the allocated list.
See also
MissQueue, MSHRQueue::allocatedList
Definition at line 401 of file mshr.hh.
deferredTargets
TargetList MSHR::deferredTargets private
Definition at line 406 of file mshr.hh.
Referenced by allocate(), allocateTarget(), deallocate(), handleSnoop(), print(), promoteDeferredTargets(), promoteIf(), promoteReadable(), promoteWritable(), and trySatisfyFunctional().
downstreamPending
bool MSHR::downstreamPending private
Flag set by downstream caches.
Definition at line 85 of file mshr.hh.
Referenced by MSHR::TargetList::add(), allocate(), clearDownstreamPending(), handleSnoop(), markInService(), print(), and promoteIf().
isForward
bool MSHR::isForward
True if the entry is just a simple forward from an upper level.
Definition at line 125 of file mshr.hh.
Referenced by allocate(), allocateTarget(), print(), BaseCache::recvTimingResp(), BaseCache::sendMSHRQueuePacket(), and Cache::serviceMSHRTargets().
pendingModified
bool MSHR::pendingModified private
Here we use one flag to track both if:
We are going to become owner or not, i.e., we will get the block in an ownership state (Owned or Modified) with BlkDirty set. This determines whether or not we are going to become the responder and ordering point for future requests that we snoop.
We know that we are going to get a writable block, i.e. we will get the block in writable state (Exclusive or Modified state) with BlkWritable set. That determines whether additional targets with needsWritable set will be able to be satisfied, or if not should be put on the deferred list to possibly wait for another request that does give us writable access.
Condition 2 is actually just a shortcut that saves us from possibly building a deferred target list and calling promoteWritable() every time we get a writable block. Condition 1, tracking ownership, is what is important. However, we never receive ownership without marking the block dirty, and consequently use pendingModified to track both ownership and writability rather than having separate pendingDirty and pendingWritable flags.
Definition at line 111 of file mshr.hh.
Referenced by isPendingModified(), and markInService().
postDowngrade
bool MSHR::postDowngrade private
Did we snoop a read while waiting for data?
Definition at line 117 of file mshr.hh.
Referenced by handleSnoop(), hasPostDowngrade(), markInService(), and print().
postInvalidate
bool MSHR::postInvalidate private
Did we snoop an invalidate while waiting for data?
Definition at line 114 of file mshr.hh.
Referenced by handleSnoop(), hasPostInvalidate(), markInService(), and print().
readyIter
Iterator MSHR::readyIter private
Pointer to this MSHR on the ready list.
See also
MissQueue, MSHRQueue::readyList
Definition at line 395 of file mshr.hh.
Referenced by MSHRQueue::allocate(), MSHRQueue::delay(), MSHRQueue::markInService(), MSHRQueue::markPending(), and MSHRQueue::moveToFront().
targets
TargetList MSHR::targets private
List of all requests that match the address.
Definition at line 404 of file mshr.hh.
Referenced by allocate(), allocateTarget(), allocOnFill(), clearDownstreamPending(), deallocate(), extractServiceableTargets(), handleSnoop(), hasFromCache(), isCleaning(), markInService(), needsWritable(), print(), promoteDeferredTargets(), promoteIf(), promoteWritable(), and trySatisfyFunctional().
wasWholeLineWrite
bool MSHR::wasWholeLineWrite
Track if we sent this as a whole line write or not.
Definition at line 122 of file mshr.hh.
Referenced by allocate(), markInService(), BaseCache::recvTimingResp(), and Cache::serviceMSHRTargets().
The documentation for this class was generated from the following files:
mem/cache/mshr.hh
mem/cache/mshr.cc