gem5: SimpleThread Class Reference
SimpleThread Class Reference
The SimpleThread object provides a combination of the ThreadState object and the ThreadContext interface.
#include <simple_thread.hh>
Public Types
typedef ThreadContext::Status Status
Public Types inherited from ThreadState
typedef ThreadContext::Status Status
Public Types inherited from ThreadContext
enum Status { Active, Suspended, Halting, Halted }
Public Member Functions
std::string name () const
SimpleThread (BaseCPU *_cpu, int _thread_num, System *_system, BaseTLB *_itb, BaseTLB *_dtb, TheISA::ISA *_isa, bool use_kernel_stats=true)
SimpleThread (BaseCPU *_cpu, int _thread_num, System *_system, Process *_process, BaseTLB *_itb, BaseTLB *_dtb, TheISA::ISA *_isa)
virtual ~SimpleThread ()
void takeOverFrom (ThreadContext *oldContext) override
void regStats (const std::string &name) override
void copyState (ThreadContext *oldContext)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup ()
ThreadContext * getTC ()
Returns the pointer to this SimpleThread's ThreadContext.
void demapPage (Addr vaddr, uint64_t asn)
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
void dumpFuncProfile () override
bool schedule (PCEvent *e) override
bool remove (PCEvent *e) override
void scheduleInstCountEvent (Event *event, Tick count) override
void descheduleInstCountEvent (Event *event) override
Tick getCurrentInstCount () override
BaseCPU * getCpuPtr () override
int cpuId () const override
uint32_t socketId () const override
int threadId () const override
void setThreadId (int id) override
ContextID contextId () const override
void setContextId (ContextID id) override
BaseTLB * getITBPtr () override
BaseTLB * getDTBPtr () override
CheckerCPU * getCheckerCpuPtr () override
TheISA::ISA * getIsaPtr () override
TheISA::Decoder * getDecoderPtr () override
System * getSystemPtr () override
Kernel::Statistics * getKernelStats () override
PortProxy & getPhysProxy () override
PortProxy & getVirtProxy () override
void initMemProxies (ThreadContext *tc) override
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
Process * getProcessPtr () override
void setProcessPtr (Process *p) override
Status status () const override
void setStatus (Status newStatus) override
void activate () override
Set the status to Active.
void suspend () override
Set the status to Suspended.
void halt () override
Set the status to Halted.
EndQuiesceEvent * getQuiesceEvent () override
Tick readLastActivate () override
Tick readLastSuspend () override
void profileClear () override
void profileSample () override
void copyArchRegs (ThreadContext *tc) override
void clearArchRegs () override
RegVal readIntReg (RegIndex reg_idx) const override
RegVal readFloatReg (RegIndex reg_idx) const override
const VecRegContainer & readVecReg (const RegId &reg) const override
VecRegContainer & getWritableVecReg (const RegId &reg) override
const VecElem & readVecElem (const RegId &reg) const override
const VecPredRegContainer & readVecPredReg (const RegId &reg) const override
VecPredRegContainer & getWritableVecPredReg (const RegId &reg) override
RegVal readCCReg (RegIndex reg_idx) const override
void setIntReg (RegIndex reg_idx, RegVal val) override
void setFloatReg (RegIndex reg_idx, RegVal val) override
void setVecReg (const RegId &reg, const VecRegContainer &val) override
void setVecElem (const RegId &reg, const VecElem &val) override
void setVecPredReg (const RegId &reg, const VecPredRegContainer &val) override
void setCCReg (RegIndex reg_idx, RegVal val) override
TheISA::PCState pcState () const override
void pcState (const TheISA::PCState &val) override
void pcStateNoRecord (const TheISA::PCState &val) override
Addr instAddr () const override
Addr nextInstAddr () const override
MicroPC microPC () const override
bool readPredicate () const
void setPredicate (bool val)
RegVal readMiscRegNoEffect (RegIndex misc_reg) const override
RegVal readMiscReg (RegIndex misc_reg) override
void setMiscRegNoEffect (RegIndex misc_reg, RegVal val) override
void setMiscReg (RegIndex misc_reg, RegVal val) override
RegId flattenRegId (const RegId &regId) const override
unsigned readStCondFailures () const override
bool readMemAccPredicate ()
void setMemAccPredicate (bool val)
void setStCondFailures (unsigned sc_failures) override
Counter readFuncExeInst () const override
void syscall (int64_t callnum, Fault *fault) override
RegVal readIntRegFlat (RegIndex idx) const override
Flat register interfaces.
void setIntRegFlat (RegIndex idx, RegVal val) override
RegVal readFloatRegFlat (RegIndex idx) const override
void setFloatRegFlat (RegIndex idx, RegVal val) override
const VecRegContainer & readVecRegFlat (RegIndex reg) const override
VecRegContainer & getWritableVecRegFlat (RegIndex reg) override
void setVecRegFlat (RegIndex reg, const VecRegContainer &val) override
template<typename T >
VecLaneT< T, true > readVecLaneFlat (RegIndex reg, int lId) const
template<typename LD >
void setVecLaneFlat (RegIndex reg, int lId, const LD &val)
const VecElem & readVecElemFlat (RegIndex reg, const ElemIndex &elemIndex) const override
void setVecElemFlat (RegIndex reg, const ElemIndex &elemIndex, const VecElem &val) override
const VecPredRegContainer & readVecPredRegFlat (RegIndex reg) const override
VecPredRegContainer & getWritableVecPredRegFlat (RegIndex reg) override
void setVecPredRegFlat (RegIndex reg, const VecPredRegContainer &val) override
RegVal readCCRegFlat (RegIndex idx) const override
void setCCRegFlat (RegIndex idx, RegVal val) override
template<typename T >
VecLaneT< T, true > readVecLane (const RegId &reg) const
Vector Register Lane Interfaces.
virtual ConstVecLane8 readVec8BitLaneReg (const RegId &reg) const override
Reads source vector 8bit operand.
virtual ConstVecLane16 readVec16BitLaneReg (const RegId &reg) const override
Reads source vector 16bit operand.
virtual ConstVecLane32 readVec32BitLaneReg (const RegId &reg) const override
Reads source vector 32bit operand.
virtual ConstVecLane64 readVec64BitLaneReg (const RegId &reg) const override
Reads source vector 64bit operand.
template<typename LD >
void setVecLaneT (const RegId &reg, const LD &val)
Write a lane of the destination vector register.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector register.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::TwoByte > &val) override
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::FourByte > &val) override
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::EightByte > &val) override
Public Member Functions inherited from ThreadState
ThreadState (BaseCPU *cpu, ThreadID _tid, Process *_process)
virtual ~ThreadState ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
int cpuId () const
uint32_t socketId () const
ContextID contextId () const
void setContextId (ContextID id)
void setThreadId (ThreadID id)
ThreadID threadId () const
Tick readLastActivate () const
Tick readLastSuspend () const
void initMemProxies (ThreadContext *tc)
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
void dumpFuncProfile ()
EndQuiesceEvent * getQuiesceEvent ()
void profileClear ()
void profileSample ()
Kernel::Statistics * getKernelStats ()
PortProxy & getPhysProxy ()
PortProxy & getVirtProxy ()
Process * getProcessPtr ()
void setProcessPtr (Process *p)
Counter readFuncExeInst () const
Reads the number of instructions functionally executed and committed.
void setFuncExeInst (Counter new_val)
Sets the total number of instructions functionally executed and committed.
Status status () const
Returns the status of this thread.
void setStatus (Status new_status)
Sets the status of this thread.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from ThreadContext
virtual ~ThreadContext ()
void quiesce ()
Quiesce thread context.
void quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
void setNPC (Addr val)
virtual int exit ()
Public Attributes
PCEventQueue pcEventQueue
EventQueue comInstEventQueue
An instruction-based event queue.
System * system
BaseTLB * itb
BaseTLB * dtb
TheISA::Decoder decoder
Public Attributes inherited from ThreadState
Counter numInst
Number of instructions committed.
Stats::Scalar numInsts
Stat for number instructions committed.
Counter numOp
Number of ops (including micro ops) committed.
Stats::Scalar numOps
Stat for number ops (including micro ops) committed.
Stats::Scalar numMemRefs
Stat for number of memory references.
Counter numLoad
Number of simulated loads, used for tracking events based on the number of loads committed.
Counter startNumLoad
The number of simulated loads committed prior to this run.
Tick lastActivate
Last time activate was called on this thread.
Tick lastSuspend
Last time suspend was called on this thread.
FunctionProfile * profile
ProfileNode * profileNode
Addr profilePC
EndQuiesceEvent * quiesceEvent
Kernel::Statistics * kernelStats
Counter funcExeInst
unsigned storeCondFailures
Protected Types
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Protected Types inherited from ThreadContext
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Protected Attributes
std::array< RegVal, TheISA::NumFloatRegs > floatRegs
std::array< RegVal, TheISA::NumIntRegs > intRegs
std::array< VecRegContainer, TheISA::NumVecRegs > vecRegs
std::array< VecPredRegContainer, TheISA::NumVecPredRegs > vecPredRegs
TheISA::ISA *const isa
TheISA::PCState _pcState
bool predicate
Did this instruction execute or is it predicated false.
bool memAccPredicate
True if the memory access should be skipped for this instruction.
Protected Attributes inherited from ThreadState
ThreadContext::Status _status
BaseCPU * baseCpu
ContextID _contextId
ThreadID _threadId
Process * process
PortProxy * physProxy
A port proxy outgoing only for functional accesses to physical addresses.
PortProxy * virtProxy
A translating port proxy, outgoing only, for functional accesse to virtual addresses.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Member Functions inherited from ThreadContext
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
The SimpleThread object provides a combination of the ThreadState object and the ThreadContext interface.
It implements the ThreadContext interface and adds to the ThreadState object by adding all the objects needed for simple functional execution, including a simple architectural register file, and pointers to the ITB and DTB in full system mode. For CPU models that do not need more advanced ways to hold state (i.e. a separate physical register file, or separate fetch and commit PC's), this SimpleThread class provides all the necessary state for full architecture-level functional simulation. See the AtomicSimpleCPU or TimingSimpleCPU for examples.
Definition at line 97 of file simple_thread.hh.
Member Typedef Documentation
MachInst
typedef TheISA::MachInst SimpleThread::MachInst protected
Definition at line 100 of file simple_thread.hh.
Status
typedef ThreadContext::Status SimpleThread::Status
Definition at line 105 of file simple_thread.hh.
VecElem
using SimpleThread::VecElem = TheISA::VecElem protected
Definition at line 102 of file simple_thread.hh.
VecPredRegContainer
using SimpleThread::VecPredRegContainer = TheISA::VecPredRegContainer protected
Definition at line 103 of file simple_thread.hh.
VecRegContainer
using SimpleThread::VecRegContainer = TheISA::VecRegContainer protected
Definition at line 101 of file simple_thread.hh.
Constructor & Destructor Documentation
SimpleThread() [1/2]
SimpleThread::SimpleThread (BaseCPU * _cpu, int _thread_num, System * _system, BaseTLB * _itb, BaseTLB * _dtb, TheISA::ISA * _isa, bool use_kernel_stats = true)
Definition at line 88 of file simple_thread.cc.
References ThreadState::baseCpu, clearArchRegs(), dumpFuncProfile(), ThreadState::kernelStats, System::kernelSymtab, BaseCPU::params(), ThreadState::profile, ThreadState::profileNode, ThreadState::profilePC, ThreadState::quiesceEvent, registerExitCallback(), and system.
SimpleThread() [2/2]
SimpleThread::SimpleThread (BaseCPU * _cpu, int _thread_num, System * _system, Process * _process, BaseTLB * _itb, BaseTLB * _dtb, TheISA::ISA * _isa)
Definition at line 76 of file simple_thread.cc.
References clearArchRegs(), and ThreadState::quiesceEvent.
~SimpleThread()
virtual SimpleThread::~SimpleThread () inline virtual
Definition at line 155 of file simple_thread.hh.
References name(), serialize(), takeOverFrom(), and unserialize().
Member Function Documentation
activate()
void SimpleThread::activate () override virtual
Set the status to Active.
Implements ThreadContext.
Definition at line 172 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, BaseCPU::activateContext(), ThreadContext::Active, ThreadState::baseCpu, curTick(), ThreadState::lastActivate, and status().
Referenced by BaseKvmCPU::wakeup().
clearArchRegs()
void SimpleThread::clearArchRegs () inline override virtual
Implements ThreadContext.
Definition at line 293 of file simple_thread.hh.
Referenced by CheckerThreadContext< TC >::clearArchRegs(), and SimpleThread().
contextId()
ContextID SimpleThread::contextId () const inline override virtual
Implements ThreadContext.
Definition at line 225 of file simple_thread.hh.
References ThreadState::contextId().
Referenced by Minor::ExecContext::contextId(), TimingSimpleCPU::fetch(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), and TimingSimpleCPU::writeMem().
copyArchRegs()
void SimpleThread::copyArchRegs (ThreadContext * tc) override virtual
Implements ThreadContext.
Definition at line 214 of file simple_thread.cc.
References AlphaISA::copyRegs().
Referenced by CheckerThreadContext< TC >::copyArchRegs(), and copyState().
copyState()
void SimpleThread::copyState (ThreadContext * oldContext)
Definition at line 130 of file simple_thread.cc.
References ThreadState::_contextId, ThreadState::_status, ThreadState::_threadId, ThreadContext::contextId(), copyArchRegs(), FullSystem, ThreadState::funcExeInst, ThreadContext::readFuncExeInst(), ThreadContext::status(), and ThreadContext::threadId().
Referenced by CheckerThreadContext< TC >::takeOverFrom().
cpuId()
int SimpleThread::cpuId () const inline override virtual
Implements ThreadContext.
Definition at line 221 of file simple_thread.hh.
References ThreadState::cpuId().
demapDataPage()
void SimpleThread::demapDataPage (Addr vaddr, uint64_t asn) inline
Definition at line 189 of file simple_thread.hh.
References BaseTLB::demapPage().
demapInstPage()
void SimpleThread::demapInstPage (Addr vaddr, uint64_t asn) inline
Definition at line 184 of file simple_thread.hh.
References BaseTLB::demapPage().
demapPage()
void SimpleThread::demapPage (Addr vaddr, uint64_t asn) inline
Definition at line 178 of file simple_thread.hh.
References BaseTLB::demapPage().
Referenced by SimpleExecContext::demapPage().
descheduleInstCountEvent()
void SimpleThread::descheduleInstCountEvent (Event * event) inline override virtual
Implements ThreadContext.
Definition at line 209 of file simple_thread.hh.
References EventQueue::deschedule().
dumpFuncProfile()
void SimpleThread::dumpFuncProfile () override virtual
Implements ThreadContext.
Definition at line 164 of file simple_thread.cc.
References ThreadState::baseCpu, OutputDirectory::close(), OutputDirectory::create(), csprintf(), FunctionProfile::dump(), SimObject::name(), X86ISA::os, ThreadState::profile, and simout.
Referenced by SimpleThread().
flattenRegId()
RegId SimpleThread::flattenRegId (const RegId & regId) const inline override virtual
Implements ThreadContext.
Definition at line 592 of file simple_thread.hh.
getCheckerCpuPtr()
CheckerCPU* SimpleThread::getCheckerCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 232 of file simple_thread.hh.
getCpuPtr()
BaseCPU* SimpleThread::getCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 219 of file simple_thread.hh.
getCurrentInstCount()
Tick SimpleThread::getCurrentInstCount () inline override virtual
Implements ThreadContext.
Definition at line 214 of file simple_thread.hh.
References EventQueue::getCurTick().
getDecoderPtr()
TheISA::Decoder* SimpleThread::getDecoderPtr () inline override virtual
Implements ThreadContext.
Definition at line 236 of file simple_thread.hh.
References decoder.
getDTBPtr()
BaseTLB* SimpleThread::getDTBPtr () inline override virtual
Implements ThreadContext.
Definition at line 230 of file simple_thread.hh.
Referenced by Minor::ExecContext::demapDataPage(), and Minor::ExecContext::demapPage().
getIsaPtr()
TheISA::ISA* SimpleThread::getIsaPtr () inline override virtual
Implements ThreadContext.
Definition at line 234 of file simple_thread.hh.
getITBPtr()
BaseTLB* SimpleThread::getITBPtr () inline override virtual
Implements ThreadContext.
Definition at line 228 of file simple_thread.hh.
Referenced by Minor::ExecContext::demapInstPage(), and Minor::ExecContext::demapPage().
getKernelStats()
Kernel::Statistics* SimpleThread::getKernelStats () inline override virtual
Implements ThreadContext.
Definition at line 241 of file simple_thread.hh.
References ThreadState::getKernelStats().
getPhysProxy()
PortProxy& SimpleThread::getPhysProxy () inline override virtual
Implements ThreadContext.
Definition at line 246 of file simple_thread.hh.
References ThreadState::getPhysProxy().
getProcessPtr()
Process* SimpleThread::getProcessPtr () inline override virtual
Implements ThreadContext.
Definition at line 254 of file simple_thread.hh.
References ThreadState::getProcessPtr().
getQuiesceEvent()
EndQuiesceEvent* SimpleThread::getQuiesceEvent () inline override virtual
Implements ThreadContext.
Definition at line 271 of file simple_thread.hh.
References ThreadState::getQuiesceEvent().
getSystemPtr()
System* SimpleThread::getSystemPtr () inline override virtual
Implements ThreadContext.
Definition at line 238 of file simple_thread.hh.
References X86ISA::system.
getTC()
ThreadContext* SimpleThread::getTC () inline
Returns the pointer to this SimpleThread's ThreadContext.
Used when a ThreadContext must be passed to objects outside of the CPU.
Definition at line 176 of file simple_thread.hh.
Referenced by AtomicSimpleCPU::amoMem(), BaseKvmCPU::BaseKvmCPU(), BaseSimpleCPU::BaseSimpleCPU(), BaseSimpleCPU::checkForInterrupts(), BaseKvmCPU::doMMIOAccess(), TimingSimpleCPU::fetch(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), MinorCPU::MinorCPU(), BaseSimpleCPU::preExecute(), AtomicSimpleCPU::readMem(), CheckerCPU::setSystem(), Minor::ExecContext::tcBase(), SimpleExecContext::tcBase(), AtomicSimpleCPU::tick(), AtomicSimpleCPU::writeMem(), and TimingSimpleCPU::writeMem().
getVirtProxy()
PortProxy& SimpleThread::getVirtProxy () inline override virtual
Implements ThreadContext.
Definition at line 247 of file simple_thread.hh.
References ThreadState::getVirtProxy().
getWritableVecPredReg()
VecPredRegContainer& SimpleThread::getWritableVecPredReg (const RegId & reg) inline override virtual
Implements ThreadContext.
Definition at line 457 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecPredRegs, and VecPredRegContainer< NumBits, Packed >::print().
Referenced by Minor::ExecContext::getWritableVecPredRegOperand(), CheckerCPU::getWritableVecPredRegOperand(), and SimpleExecContext::getWritableVecPredRegOperand().
getWritableVecPredRegFlat()
VecPredRegContainer& SimpleThread::getWritableVecPredRegFlat (RegIndex reg) inline override virtual
Implements ThreadContext.
Definition at line 699 of file simple_thread.hh.
References X86ISA::reg.
getWritableVecReg()
VecRegContainer& SimpleThread::getWritableVecReg (const RegId & reg) inline override virtual
Implements ThreadContext.
Definition at line 345 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecRegs, and VecRegContainer< Sz >::print().
Referenced by Minor::ExecContext::getWritableVecRegOperand(), CheckerCPU::getWritableVecRegOperand(), and SimpleExecContext::getWritableVecRegOperand().
getWritableVecRegFlat()
VecRegContainer& SimpleThread::getWritableVecRegFlat (RegIndex reg) inline override virtual
Implements ThreadContext.
Definition at line 654 of file simple_thread.hh.
References X86ISA::reg.
halt()
void SimpleThread::halt () override virtual
Set the status to Halted.
Implements ThreadContext.
Definition at line 196 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, ThreadState::baseCpu, BaseCPU::haltContext(), ThreadContext::Halted, and status().
initMemProxies()
void SimpleThread::initMemProxies (ThreadContext * tc) inline override virtual
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
tc ThreadContext for the virtual-to-physical translation
Implements ThreadContext.
Definition at line 249 of file simple_thread.hh.
References ThreadState::initMemProxies().
instAddr()
Addr SimpleThread::instAddr () const inline override virtual
Implements ThreadContext.
Definition at line 561 of file simple_thread.hh.
Referenced by TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), CheckerCPU::instAddr(), BaseSimpleCPU::setupFetchRequest(), and TimingSimpleCPU::writeMem().
microPC()
MicroPC SimpleThread::microPC () const inline override virtual
Implements ThreadContext.
Definition at line 563 of file simple_thread.hh.
Referenced by AtomicSimpleCPU::isCpuDrained(), TimingSimpleCPU::isCpuDrained(), and CheckerCPU::microPC().
name()
std::string SimpleThread::name () const inline
Definition at line 126 of file simple_thread.hh.
References csprintf().
nextInstAddr()
Addr SimpleThread::nextInstAddr () const inline override virtual
Implements ThreadContext.
Definition at line 562 of file simple_thread.hh.
Referenced by CheckerCPU::nextInstAddr().
pcState() [1/2]
TheISA::PCState SimpleThread::pcState () const inline override virtual
Implements ThreadContext.
Definition at line 552 of file simple_thread.hh.
Referenced by BaseSimpleCPU::advancePC(), AtomicSimpleCPU::amoMem(), Minor::LSQ::LSQRequest::completeDisabledMemAccess(), CheckerCPU::dumpAndExit(), TimingSimpleCPU::fetch(), CheckerCPU::genMemFragmentRequest(), Minor::ExecContext::pcState(), CheckerThreadContext< TC >::pcState(), SimpleExecContext::pcState(), CheckerCPU::pcState(), BaseSimpleCPU::preExecute(), SimPoint::profile(), AtomicSimpleCPU::tick(), Minor::LSQ::tryToSendToTransfers(), and Minor::LSQ::LSQRequest::tryToSuppressFault().
pcState() [2/2]
void SimpleThread::pcState (const TheISA::PCState & val) inline override virtual
Implements ThreadContext.
Definition at line 553 of file simple_thread.hh.
References X86ISA::val.
pcStateNoRecord()
void SimpleThread::pcStateNoRecord (const TheISA::PCState & val) inline override virtual
Implements ThreadContext.
Definition at line 556 of file simple_thread.hh.
References X86ISA::val.
profileClear()
void SimpleThread::profileClear () inline override virtual
Implements ThreadContext.
Definition at line 287 of file simple_thread.hh.
References ThreadState::profileClear().
profileSample()
void SimpleThread::profileSample () inline override virtual
Implements ThreadContext.
Definition at line 288 of file simple_thread.hh.
References ThreadState::profileSample().
readCCReg()
RegVal SimpleThread::readCCReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 469 of file simple_thread.hh.
References DPRINTF, AlphaISA::NumCCRegs, and panic.
Referenced by CheckerCPU::readCCRegOperand(), SimpleExecContext::readCCRegOperand(), and Minor::ExecContext::readCCRegOperand().
readCCRegFlat()
RegVal SimpleThread::readCCRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 715 of file simple_thread.hh.
References panic.
readFloatReg()
RegVal SimpleThread::readFloatReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 323 of file simple_thread.hh.
References DPRINTF, and AlphaISA::NumFloatRegs.
Referenced by Minor::ExecContext::readFloatRegOperandBits(), SimpleExecContext::readFloatRegOperandBits(), and CheckerCPU::readFloatRegOperandBits().
readFloatRegFlat()
RegVal SimpleThread::readFloatRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 637 of file simple_thread.hh.
readFuncExeInst()
Counter SimpleThread::readFuncExeInst () const inline override virtual
Implements ThreadContext.
Definition at line 618 of file simple_thread.hh.
References ThreadState::readFuncExeInst().
readIntReg()
RegVal SimpleThread::readIntReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 312 of file simple_thread.hh.
References DPRINTF, and AlphaISA::NumIntRegs.
Referenced by Minor::ExecContext::readIntRegOperand(), SimpleExecContext::readIntRegOperand(), and CheckerCPU::readIntRegOperand().
readIntRegFlat()
RegVal SimpleThread::readIntRegFlat (RegIndex idx) const inline override virtual
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenRegId()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implements ThreadContext.
Definition at line 629 of file simple_thread.hh.
readLastActivate()
Tick SimpleThread::readLastActivate () inline override virtual
Implements ThreadContext.
Definition at line 277 of file simple_thread.hh.
References ThreadState::readLastActivate().
readLastSuspend()
Tick SimpleThread::readLastSuspend () inline override virtual
Implements ThreadContext.
Definition at line 282 of file simple_thread.hh.
References ThreadState::readLastSuspend().
readMemAccPredicate()
bool SimpleThread::readMemAccPredicate () inline
Definition at line 600 of file simple_thread.hh.
Referenced by Minor::ExecContext::readMemAccPredicate(), CheckerCPU::readMemAccPredicate(), and SimpleExecContext::readMemAccPredicate().
readMiscReg()
RegVal SimpleThread::readMiscReg (RegIndex misc_reg) inline override virtual
Implements ThreadContext.
Definition at line 574 of file simple_thread.hh.
Referenced by Minor::ExecContext::readMiscReg(), SimpleExecContext::readMiscReg(), CheckerCPU::readMiscReg(), Minor::ExecContext::readMiscRegOperand(), SimpleExecContext::readMiscRegOperand(), and CheckerCPU::readMiscRegOperand().
readMiscRegNoEffect()
RegVal SimpleThread::readMiscRegNoEffect (RegIndex misc_reg) const inline override virtual
Implements ThreadContext.
Definition at line 568 of file simple_thread.hh.
Referenced by Minor::ExecContext::readMiscRegNoEffect(), and CheckerCPU::readMiscRegNoEffect().
readPredicate()
bool SimpleThread::readPredicate () const inline
Definition at line 564 of file simple_thread.hh.
Referenced by Minor::ExecContext::readPredicate(), CheckerCPU::readPredicate(), and SimpleExecContext::readPredicate().
readStCondFailures()
unsigned SimpleThread::readStCondFailures () const inline override virtual
Implements ThreadContext.
Definition at line 597 of file simple_thread.hh.
Referenced by SimpleExecContext::readStCondFailures(), and CheckerCPU::readStCondFailures().
readVec16BitLaneReg()
virtual ConstVecLane16 SimpleThread::readVec16BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 16bit operand.
Implements ThreadContext.
Definition at line 379 of file simple_thread.hh.
References X86ISA::reg.
Referenced by CheckerCPU::readVec16BitLaneOperand(), and Minor::ExecContext::readVec16BitLaneOperand().
readVec32BitLaneReg()
virtual ConstVecLane32 SimpleThread::readVec32BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 32bit operand.
Implements ThreadContext.
Definition at line 386 of file simple_thread.hh.
References X86ISA::reg.
Referenced by CheckerCPU::readVec32BitLaneOperand(), and Minor::ExecContext::readVec32BitLaneOperand().
readVec64BitLaneReg()
virtual ConstVecLane64 SimpleThread::readVec64BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 64bit operand.
Implements ThreadContext.
Definition at line 393 of file simple_thread.hh.
References X86ISA::reg.
Referenced by CheckerCPU::readVec64BitLaneOperand(), and Minor::ExecContext::readVec64BitLaneOperand().
readVec8BitLaneReg()
virtual ConstVecLane8 SimpleThread::readVec8BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 8bit operand.
Implements ThreadContext.
Definition at line 372 of file simple_thread.hh.
References X86ISA::reg.
Referenced by CheckerCPU::readVec8BitLaneOperand(), and Minor::ExecContext::readVec8BitLaneOperand().
readVecElem()
const VecElem& SimpleThread::readVecElem (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 435 of file simple_thread.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), and AlphaISA::NumVecRegs.
Referenced by Minor::ExecContext::readVecElemOperand(), CheckerCPU::readVecElemOperand(), and SimpleExecContext::readVecElemOperand().
readVecElemFlat()
const VecElem& SimpleThread::readVecElemFlat (RegIndex reg, const ElemIndex & elemIndex) const inline override virtual
Implements ThreadContext.
Definition at line 680 of file simple_thread.hh.
References X86ISA::reg.
readVecLane()
template<typename T > VecLaneT<T, true> SimpleThread::readVecLane (const RegId & reg) const inline
Vector Register Lane Interfaces.
Reads source vector <T> operand.
Definition at line 360 of file simple_thread.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), and AlphaISA::NumVecRegs.
Referenced by SimpleExecContext::readVecLaneOperand().
readVecLaneFlat()
template<typename T > VecLaneT<T, true> SimpleThread::readVecLaneFlat (RegIndex reg, int lId) const inline
Definition at line 667 of file simple_thread.hh.
References X86ISA::reg.
readVecPredReg()
const VecPredRegContainer& SimpleThread::readVecPredReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 446 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecPredRegs, and VecPredRegContainer< NumBits, Packed >::print().
Referenced by Minor::ExecContext::readVecPredRegOperand(), CheckerCPU::readVecPredRegOperand(), and SimpleExecContext::readVecPredRegOperand().
readVecPredRegFlat()
const VecPredRegContainer& SimpleThread::readVecPredRegFlat (RegIndex reg) const inline override virtual
Implements ThreadContext.
Definition at line 693 of file simple_thread.hh.
References X86ISA::reg.
readVecReg()
const VecRegContainer& SimpleThread::readVecReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 334 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecRegs, and VecRegContainer< Sz >::print().
Referenced by Minor::ExecContext::readVecRegOperand(), CheckerCPU::readVecRegOperand(), and SimpleExecContext::readVecRegOperand().
readVecRegFlat()
const VecRegContainer& SimpleThread::readVecRegFlat (RegIndex reg) const inline override virtual
Implements ThreadContext.
Definition at line 648 of file simple_thread.hh.
References X86ISA::reg.
regStats()
void SimpleThread::regStats (const std::string & name) override virtual
Implements ThreadContext.
Definition at line 207 of file simple_thread.cc.
References FullSystem, ThreadState::kernelStats, and Kernel::Statistics::regStats().
Referenced by CheckerThreadContext< TC >::regStats().
remove()
bool SimpleThread::remove (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 201 of file simple_thread.hh.
References ArmISA::e, and PCEventQueue::remove().
schedule()
bool SimpleThread::schedule (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 200 of file simple_thread.hh.
References PCEventQueue::schedule().
scheduleInstCountEvent()
void SimpleThread::scheduleInstCountEvent (Event * event, Tick count) inline override virtual
Implements ThreadContext.
Definition at line 204 of file simple_thread.hh.
References EventQueue::schedule().
serialize()
void SimpleThread::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 143 of file simple_thread.cc.
References ThreadState::serialize().
Referenced by BaseKvmCPU::serializeThread().
setCCReg()
void SimpleThread::setCCReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 539 of file simple_thread.hh.
References DPRINTF, AlphaISA::NumCCRegs, and panic.
Referenced by CheckerThreadContext< TC >::setCCReg(), SimpleExecContext::setCCRegOperand(), CheckerCPU::setCCRegOperand(), and Minor::ExecContext::setCCRegOperand().
setCCRegFlat()
void SimpleThread::setCCRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 721 of file simple_thread.hh.
References panic.
setContextId()
void SimpleThread::setContextId (ContextID id) inline override virtual
Implements ThreadContext.
Definition at line 226 of file simple_thread.hh.
References ThreadState::setContextId().
Referenced by CheckerThreadContext< TC >::setContextId().
setFloatReg()
void SimpleThread::setFloatReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 496 of file simple_thread.hh.
References DPRINTF, and AlphaISA::NumFloatRegs.
Referenced by Minor::ExecContext::ExecContext(), BaseSimpleCPU::preExecute(), CheckerThreadContext< TC >::setFloatReg(), Minor::ExecContext::setFloatRegOperandBits(), SimpleExecContext::setFloatRegOperandBits(), and CheckerCPU::setFloatRegOperandBits().
setFloatRegFlat()
void SimpleThread::setFloatRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 642 of file simple_thread.hh.
References X86ISA::val.
setIntReg()
void SimpleThread::setIntReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 486 of file simple_thread.hh.
References DPRINTF, and AlphaISA::NumIntRegs.
Referenced by Minor::ExecContext::ExecContext(), BaseSimpleCPU::preExecute(), CheckerThreadContext< TC >::setIntReg(), SimpleExecContext::setIntRegOperand(), Minor::ExecContext::setIntRegOperand(), and CheckerCPU::setIntRegOperand().
setIntRegFlat()
void SimpleThread::setIntRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 631 of file simple_thread.hh.
References X86ISA::val.
setMemAccPredicate()
void SimpleThread::setMemAccPredicate (bool val) inline
Definition at line 606 of file simple_thread.hh.
References X86ISA::val.
Referenced by Minor::ExecContext::setMemAccPredicate(), CheckerCPU::setMemAccPredicate(), and SimpleExecContext::setMemAccPredicate().
setMiscReg()
void SimpleThread::setMiscReg (RegIndex misc_reg, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 586 of file simple_thread.hh.
Referenced by Minor::ExecContext::setMiscReg(), SimpleExecContext::setMiscReg(), CheckerThreadContext< TC >::setMiscReg(), CheckerCPU::setMiscReg(), Minor::ExecContext::setMiscRegOperand(), and SimpleExecContext::setMiscRegOperand().
setMiscRegNoEffect()
void SimpleThread::setMiscRegNoEffect (RegIndex misc_reg, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 580 of file simple_thread.hh.
Referenced by CheckerThreadContext< TC >::setMiscRegNoEffect(), and CheckerCPU::setMiscRegNoEffect().
setPredicate()
void SimpleThread::setPredicate (bool val) inline
Definition at line 565 of file simple_thread.hh.
References X86ISA::val.
Referenced by Minor::ExecContext::setPredicate(), CheckerCPU::setPredicate(), and SimpleExecContext::setPredicate().
setProcessPtr()
void SimpleThread::setProcessPtr (Process * p) inline override virtual
Implements ThreadContext.
Definition at line 255 of file simple_thread.hh.
References ThreadState::setProcessPtr().
setStatus()
void SimpleThread::setStatus (Status newStatus) inline override virtual
Implements ThreadContext.
Definition at line 259 of file simple_thread.hh.
References MipsISA::halt.
Referenced by BaseKvmCPU::BaseKvmCPU(), MinorCPU::MinorCPU(), and CheckerThreadContext< TC >::setStatus().
setStCondFailures()
void SimpleThread::setStCondFailures (unsigned sc_failures) inline override virtual
Implements ThreadContext.
Definition at line 612 of file simple_thread.hh.
Referenced by SimpleExecContext::setStCondFailures().
setThreadId()
void SimpleThread::setThreadId (int id) inline override virtual
Implements ThreadContext.
Definition at line 224 of file simple_thread.hh.
References ThreadState::setThreadId().
Referenced by CheckerThreadContext< TC >::setThreadId().
setVecElem()
void SimpleThread::setVecElem (const RegId & reg, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 519 of file simple_thread.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), AlphaISA::NumVecRegs, and X86ISA::val.
Referenced by CheckerThreadContext< TC >::setVecElem(), Minor::ExecContext::setVecElemOperand(), SimpleExecContext::setVecElemOperand(), and CheckerCPU::setVecElemOperand().
setVecElemFlat()
void SimpleThread::setVecElemFlat (RegIndex reg, const ElemIndex & elemIndex, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 686 of file simple_thread.hh.
References X86ISA::reg.
setVecLane() [1/4]
virtual void SimpleThread::setVecLane (const RegId & reg, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector register.
Implements ThreadContext.
Definition at line 410 of file simple_thread.hh.
Referenced by CheckerCPU::setVecLaneOperandT(), Minor::ExecContext::setVecLaneOperandT(), and SimpleExecContext::setVecLaneOperandT().
setVecLane() [2/4]
virtual void SimpleThread::setVecLane (const RegId & reg, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 415 of file simple_thread.hh.
setVecLane() [3/4]
virtual void SimpleThread::setVecLane (const RegId & reg, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 421 of file simple_thread.hh.
setVecLane() [4/4]
virtual void SimpleThread::setVecLane (const RegId & reg, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 427 of file simple_thread.hh.
setVecLaneFlat()
template<typename LD > void SimpleThread::setVecLaneFlat (RegIndex reg, int lId, const LD & val) inline
Definition at line 674 of file simple_thread.hh.
References X86ISA::reg.
setVecLaneT()
template<typename LD > void SimpleThread::setVecLaneT (const RegId & reg, const LD & val) inline
Write a lane of the destination vector register.
Definition at line 401 of file simple_thread.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), AlphaISA::NumVecRegs, and X86ISA::val.
setVecPredReg()
void SimpleThread::setVecPredReg (const RegId & reg, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 529 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecPredRegs, and VecPredRegContainer< NumBits, Packed >::print().
Referenced by CheckerThreadContext< TC >::setVecPredReg(), Minor::ExecContext::setVecPredRegOperand(), SimpleExecContext::setVecPredRegOperand(), and CheckerCPU::setVecPredRegOperand().
setVecPredRegFlat()
void SimpleThread::setVecPredRegFlat (RegIndex reg, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 705 of file simple_thread.hh.
References X86ISA::reg, and X86ISA::val.
setVecReg()
void SimpleThread::setVecReg (const RegId & reg, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 509 of file simple_thread.hh.
References DPRINTF, RegId::index(), AlphaISA::NumVecRegs, and VecRegContainer< Sz >::print().
Referenced by CheckerThreadContext< TC >::setVecReg(), Minor::ExecContext::setVecRegOperand(), SimpleExecContext::setVecRegOperand(), and CheckerCPU::setVecRegOperand().
setVecRegFlat()
void SimpleThread::setVecRegFlat (RegIndex reg, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 660 of file simple_thread.hh.
References X86ISA::reg, and X86ISA::val.
socketId()
uint32_t SimpleThread::socketId () const inline override virtual
Implements ThreadContext.
Definition at line 222 of file simple_thread.hh.
References ThreadState::socketId().
startup()
void SimpleThread::startup ()
Definition at line 158 of file simple_thread.cc.
References isa.
Referenced by BaseKvmCPU::startup().
status()
Status SimpleThread::status () const inline override virtual
Implements ThreadContext.
Definition at line 257 of file simple_thread.hh.
Referenced by activate(), halt(), suspend(), and BaseKvmCPU::wakeup().
suspend()
void SimpleThread::suspend () override virtual
Set the status to Suspended.
Implements ThreadContext.
Definition at line 183 of file simple_thread.cc.
References ThreadState::_status, ThreadState::_threadId, ThreadState::baseCpu, curTick(), ThreadState::lastActivate, ThreadState::lastSuspend, status(), BaseCPU::suspendContext(), and ThreadContext::Suspended.
Referenced by X86KvmCPU::deliverInterrupts(), and BaseKvmCPU::handleKvmExit().
syscall()
void SimpleThread::syscall (int64_t callnum, Fault * fault) inline override virtual
Implements ThreadContext.
Definition at line 624 of file simple_thread.hh.
Referenced by Minor::ExecContext::syscall(), and SimpleExecContext::syscall().
takeOverFrom()
void SimpleThread::takeOverFrom (ThreadContext * oldContext) override virtual
Implements ThreadContext.
Definition at line 119 of file simple_thread.cc.
References decoder, ThreadState::funcExeInst, ThreadContext::getDecoderPtr(), ThreadContext::getKernelStats(), ThreadState::kernelStats, ThreadContext::readFuncExeInst(), and ThreadState::storeCondFailures.
threadId()
int SimpleThread::threadId () const inline override virtual
Implements ThreadContext.
Definition at line 223 of file simple_thread.hh.
References ThreadState::threadId().
Referenced by SimpleExecContext::armMonitor(), SimpleExecContext::getAddrMonitor(), SimpleExecContext::mwait(), and SimpleExecContext::mwaitAtomic().
unserialize()
void SimpleThread::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 151 of file simple_thread.cc.
References ThreadState::unserialize().
Referenced by BaseKvmCPU::unserializeThread().
Member Data Documentation
_pcState
TheISA::PCState SimpleThread::_pcState protected
Definition at line 117 of file simple_thread.hh.
comInstEventQueue
EventQueue SimpleThread::comInstEventQueue
An instruction-based event queue.
Used for scheduling events based on number of instructions committed.
Definition at line 136 of file simple_thread.hh.
Referenced by BaseSimpleCPU::preExecute(), BaseKvmCPU::setupInstStop(), and BaseKvmCPU::tick().
decoder
TheISA::Decoder SimpleThread::decoder
Definition at line 143 of file simple_thread.hh.
Referenced by BaseSimpleCPU::advancePC(), BaseSimpleCPU::checkForInterrupts(), BaseSimpleCPU::preExecute(), and takeOverFrom().
dtb
BaseTLB* SimpleThread::dtb
Definition at line 141 of file simple_thread.hh.
Referenced by AtomicSimpleCPU::amoMem(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), Minor::ExecContext::mwaitAtomic(), CheckerCPU::mwaitAtomic(), SimpleExecContext::mwaitAtomic(), AtomicSimpleCPU::readMem(), AtomicSimpleCPU::writeMem(), and TimingSimpleCPU::writeMem().
floatRegs
std::array<RegVal, TheISA::NumFloatRegs> SimpleThread::floatRegs protected
Definition at line 108 of file simple_thread.hh.
intRegs
std::array<RegVal, TheISA::NumIntRegs> SimpleThread::intRegs protected
Definition at line 109 of file simple_thread.hh.
isa
TheISA::ISA* const SimpleThread::isa protected
Definition at line 115 of file simple_thread.hh.
Referenced by startup().
itb
BaseTLB* SimpleThread::itb
Definition at line 140 of file simple_thread.hh.
Referenced by TimingSimpleCPU::fetch(), and AtomicSimpleCPU::tick().
memAccPredicate
bool SimpleThread::memAccPredicate protected
True if the memory access should be skipped for this instruction.
Definition at line 123 of file simple_thread.hh.
pcEventQueue
PCEventQueue SimpleThread::pcEventQueue
Definition at line 131 of file simple_thread.hh.
predicate
bool SimpleThread::predicate protected
Did this instruction execute or is it predicated false.
Definition at line 120 of file simple_thread.hh.
system
System* SimpleThread::system
Definition at line 138 of file simple_thread.hh.
Referenced by SimpleThread().
vecPredRegs
std::array<VecPredRegContainer, TheISA::NumVecPredRegs> SimpleThread::vecPredRegs protected
Definition at line 111 of file simple_thread.hh.
vecRegs
std::array<VecRegContainer, TheISA::NumVecRegs> SimpleThread::vecRegs protected
Definition at line 110 of file simple_thread.hh.
The documentation for this class was generated from the following files:
cpu/simple_thread.hh
cpu/simple_thread.cc