gem5: ArmSemihosting Class Reference
ArmSemihosting Class Reference
Semihosting for AArch32 and AArch64.
#include <semihosting.hh>
Classes
class File
class FileBase
Internal state for open files.
class FileFeatures
Implementation of the ':semihosting-features' magic file.
struct SemiCall
Semihosting call information structure.
Public Member Functions
ArmSemihosting (const ArmSemihostingParams *p)
uint64_t call64 (ThreadContext *tc, uint32_t op, uint64_t param)
Perform an Arm Semihosting call from aarch64 code.
uint32_t call32 (ThreadContext *tc, uint32_t op, uint32_t param)
Perform an Arm Semihosting call from aarch32 code.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
typedef uint64_t SemiErrno
Protected Member Functions
unsigned calcTickShift () const
uint64_t semiTick (Tick tick) const
void semiExit (uint64_t code, uint64_t subcode)
PortProxy & physProxy (ThreadContext *tc)
std::string readString (ThreadContext *tc, Addr ptr, size_t len)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const std::string cmdLine
const Addr memReserve
const Addr stackSize
const time_t timeBase
Base time when the simulation started.
const unsigned tickShift
Number of bits to right shift gem5 ticks to fit in a uint32_t.
SemiErrno semiErrno
std::vector< std::unique_ptr< FileBase > > files
FILE * stdin
FILE * stdout
FILE * stderr
std::unique_ptr< PortProxy > physProxyS
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Types
typedef std::pair< uint64_t, SemiErrno > RetErrno
Private Member Functions
SEMI_CALL (Open)
SEMI_CALL (Close)
SEMI_CALL (WriteC)
SEMI_CALL (Write0)
SEMI_CALL (Write)
SEMI_CALL (Read)
SEMI_CALL (ReadC)
SEMI_CALL (IsError)
SEMI_CALL (IsTTY)
SEMI_CALL (Seek)
SEMI_CALL (FLen)
SEMI_CALL (TmpNam)
SEMI_CALL (Remove)
SEMI_CALL (Rename)
SEMI_CALL (Clock)
SEMI_CALL (Time)
SEMI_CALL (System)
SEMI_CALL (Errno)
SEMI_CALL (GetCmdLine)
SEMI_CALL (HeapInfo)
SEMI_CALL (Exit)
SEMI_CALL (ExitExtended)
SEMI_CALL (Elapsed)
SEMI_CALL (TickFreq)
Static Private Member Functions
static RetErrno retError (SemiErrno e)
static RetErrno retOK (uint64_t r)
static const SemiCall * getCall (uint32_t op, bool aarch64)
static FILE * getSTDIO (const char *stream_name, const std::string &name, const char *mode)
Static Private Attributes
static const std::map< uint32_t, SemiCall > calls
static const std::vector< const char * > fmodes
static const std::map< uint64_t, const char * > exitCodes
static const std::vector< uint8_t > features
static const std::map< const std::string, FILE * > stdioMap
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Semihosting for AArch32 and AArch64.
This class implements the Arm semihosting interface. This interface allows baremetal code access service, such as IO, from the simulator. It is conceptually a simplified version of gem5's more general syscall emulation mode.
Exits calls (SYS_EXIT, SYS_EXIT_EXTENDED) from the guest get translated into simualtion exits. Well-known exit codes are translated to messages on the form 'semi:ADP_.*' while unknown codes are returned in hex ('semi:0x..'). The subcode is reported in the gem5 exit event.
Definition at line 69 of file semihosting.hh.
Member Typedef Documentation
RetErrno
typedef std::pair<uint64_t, SemiErrno> ArmSemihosting::RetErrno private
Definition at line 266 of file semihosting.hh.
SemiErrno
typedef uint64_t ArmSemihosting::SemiErrno protected
Definition at line 98 of file semihosting.hh.
Constructor & Destructor Documentation
ArmSemihosting()
ArmSemihosting::ArmSemihosting (const ArmSemihostingParams * p)
Definition at line 133 of file semihosting.cc.
References calcTickShift(), files, getSTDIO(), inform, mkutctime(), MipsISA::p, semiErrno, stderr, stdin, stdout, and tickShift.
Referenced by ArmSemihosting::File::unserialize().
Member Function Documentation
calcTickShift()
unsigned ArmSemihosting::calcTickShift () const inline protected
Definition at line 252 of file semihosting.hh.
References findMsbSet(), and SimClock::Frequency.
Referenced by ArmSemihosting().
call32()
uint32_t ArmSemihosting::call32 (ThreadContext * tc, uint32_t op, uint32_t param)
Perform an Arm Semihosting call from aarch32 code.
Definition at line 191 of file semihosting.cc.
References ArmSemihosting::SemiCall::argc32, ArmISA::byteOrder(), ArmSemihosting::SemiCall::call, DPRINTF, getCall(), ArmISA::i, ArmSemihosting::SemiCall::implemented32(), ArmSemihosting::SemiCall::name, physProxy(), PortProxy::read(), semiErrno, and warn.
Referenced by ArmSystem::callSemihosting32().
call64()
uint64_t ArmSemihosting::call64 (ThreadContext * tc, uint32_t op, uint64_t param)
Perform an Arm Semihosting call from aarch64 code.
Definition at line 156 of file semihosting.cc.
References ArmSemihosting::SemiCall::argc64, ArmISA::byteOrder(), ArmSemihosting::SemiCall::call, DPRINTF, getCall(), ArmISA::i, ArmSemihosting::SemiCall::implemented64(), ArmSemihosting::SemiCall::name, physProxy(), PortProxy::read(), semiErrno, and warn.
Referenced by ArmSystem::callSemihosting64().
getCall()
const ArmSemihosting::SemiCall * ArmSemihosting::getCall (uint32_t op, bool aarch64) static private
Definition at line 684 of file semihosting.cc.
References calls.
Referenced by call32(), and call64().
getSTDIO()
FILE * ArmSemihosting::getSTDIO (const char * stream_name, const std::string & name, const char * mode) static private
Definition at line 695 of file semihosting.cc.
References ArmISA::f, fatal, ArmISA::mode, and stdioMap.
Referenced by ArmSemihosting().
physProxy()
PortProxy & ArmSemihosting::physProxy (ThreadContext * tc) protected
Definition at line 253 of file semihosting.cc.
References System::cacheLineSize(), ThreadContext::getPhysProxy(), System::getSystemPort(), ThreadContext::getSystemPtr(), ArmISA::inSecureState(), and physProxyS.
Referenced by call32(), call64(), readString(), semiExit(), and semiTick().
readString()
std::string ArmSemihosting::readString (ThreadContext * tc, Addr ptr, size_t len) protected
Definition at line 270 of file semihosting.cc.
References ArmISA::aarch64, addr, X86ISA::base, ArmISA::byteOrder(), ArmISA::c, cmdLine, ArmSemihosting::FileBase::create(), curTick(), data, DPRINTF, fatal_if, files, fmodes, PhysicalMemory::getConfAddrRanges(), System::getPhysMem(), ThreadContext::getSystemPtr(), inform, ArmISA::len, memReserve, ArmISA::mode, panic_if, Serializable::path, physProxy(), PortProxy::read(), PortProxy::readBlob(), retError(), retOK(), SimClock::Float::s, SimClock::Int::s, semiErrno, semiExit(), stackSize, ArmISA::status, timeBase, ULL, warn, warn_if, PortProxy::write(), and PortProxy::writeBlob().
Referenced by semiTick().
retError()
static RetErrno ArmSemihosting::retError (SemiErrno e) inline static private
Definition at line 267 of file semihosting.hh.
Referenced by readString().
retOK()
static RetErrno ArmSemihosting::retOK (uint64_t r) inline static private
Definition at line 271 of file semihosting.hh.
Referenced by readString(), and semiExit().
SEMI_CALL() [1/24]
ArmSemihosting::SEMI_CALL (Open) private
SEMI_CALL() [2/24]
ArmSemihosting::SEMI_CALL (Close) private
SEMI_CALL() [3/24]
ArmSemihosting::SEMI_CALL (WriteC) private
SEMI_CALL() [4/24]
ArmSemihosting::SEMI_CALL (Write0) private
SEMI_CALL() [5/24]
ArmSemihosting::SEMI_CALL (Write) private
SEMI_CALL() [6/24]
ArmSemihosting::SEMI_CALL (Read) private
SEMI_CALL() [7/24]
ArmSemihosting::SEMI_CALL (ReadC) private
SEMI_CALL() [8/24]
ArmSemihosting::SEMI_CALL (IsError) private
SEMI_CALL() [9/24]
ArmSemihosting::SEMI_CALL (IsTTY) private
SEMI_CALL() [10/24]
ArmSemihosting::SEMI_CALL (Seek) private
SEMI_CALL() [11/24]
ArmSemihosting::SEMI_CALL (FLen) private
SEMI_CALL() [12/24]
ArmSemihosting::SEMI_CALL (TmpNam) private
SEMI_CALL() [13/24]
ArmSemihosting::SEMI_CALL (Remove) private
SEMI_CALL() [14/24]
ArmSemihosting::SEMI_CALL (Rename) private
SEMI_CALL() [15/24]
ArmSemihosting::SEMI_CALL (Clock) private
SEMI_CALL() [16/24]
ArmSemihosting::SEMI_CALL (Time) private
SEMI_CALL() [17/24]
ArmSemihosting::SEMI_CALL (System) private
SEMI_CALL() [18/24]
ArmSemihosting::SEMI_CALL (Errno) private
SEMI_CALL() [19/24]
ArmSemihosting::SEMI_CALL (GetCmdLine) private
SEMI_CALL() [20/24]
ArmSemihosting::SEMI_CALL (HeapInfo) private
SEMI_CALL() [21/24]
ArmSemihosting::SEMI_CALL (Exit) private
SEMI_CALL() [22/24]
ArmSemihosting::SEMI_CALL (ExitExtended) private
SEMI_CALL() [23/24]
ArmSemihosting::SEMI_CALL (Elapsed) private
SEMI_CALL() [24/24]
ArmSemihosting::SEMI_CALL (TickFreq) private
semiExit()
void ArmSemihosting::semiExit (uint64_t code, uint64_t subcode) protected
Definition at line 646 of file semihosting.cc.
References ArmISA::aarch64, ArmISA::byteOrder(), csprintf(), curTick(), exitCodes, exitSimLoop(), SimClock::Frequency, physProxy(), retOK(), semiTick(), and PortProxy::write().
Referenced by readString(), and semiTick().
semiTick()
uint64_t ArmSemihosting::semiTick (Tick tick) const inline protected
Definition at line 256 of file semihosting.hh.
References ArmISA::len, physProxy(), readString(), semiExit(), and tickShift.
Referenced by semiExit().
serialize()
void ArmSemihosting::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 226 of file semihosting.cc.
References csprintf(), files, ArmISA::i, paramOut(), semiErrno, and SERIALIZE_SCALAR.
unserialize()
void ArmSemihosting::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 241 of file semihosting.cc.
References ArmSemihosting::FileBase::create(), csprintf(), files, ArmISA::i, paramIn(), semiErrno, and UNSERIALIZE_SCALAR.
Member Data Documentation
calls
const std::map< uint32_t, ArmSemihosting::SemiCall > ArmSemihosting::calls static private
Definition at line 351 of file semihosting.hh.
Referenced by getCall().
cmdLine
const std::string ArmSemihosting::cmdLine protected
Definition at line 84 of file semihosting.hh.
Referenced by readString().
exitCodes
const std::map< uint64_t, const char * > ArmSemihosting::exitCodes static private
Initial value:
{
    { 0x20000, "semi:ADP_Stopped_BranchThroughZero" },
    { 0x20001, "semi:ADP_Stopped_UndefinedInstr" },
    { 0x20002, "semi:ADP_Stopped_SoftwareInterrupt" },
    { 0x20003, "semi:ADP_Stopped_PrefetchAbort" },
    { 0x20004, "semi:ADP_Stopped_DataAbort" },
    { 0x20005, "semi:ADP_Stopped_AddressException" },
    { 0x20006, "semi:ADP_Stopped_IRQ" },
    { 0x20007, "semi:ADP_Stopped_FIQ" },
    { 0x20020, "semi:ADP_Stopped_BreakPoint" },
    { 0x20021, "semi:ADP_Stopped_WatchPoint" },
    { 0x20022, "semi:ADP_Stopped_StepComplete" },
    { 0x20023, "semi:ADP_Stopped_RunTimeErrorUnknown" },
    { 0x20024, "semi:ADP_Stopped_InternalError" },
    { 0x20025, "semi:ADP_Stopped_UserInterruption" },
    { 0x20026, "semi:ADP_Stopped_ApplicationExit" },
    { 0x20027, "semi:ADP_Stopped_StackOverflow" },
    { 0x20028, "semi:ADP_Stopped_DivisionByZero" },
    { 0x20029, "semi:ADP_Stopped_DivisionByZero" },
}
Definition at line 353 of file semihosting.hh.
Referenced by semiExit().
features
const std::vector< uint8_t > ArmSemihosting::features static private
Initial value:
{
    0x53, 0x48, 0x46, 0x42,
    0x3,
}
Definition at line 354 of file semihosting.hh.
Referenced by ArmSemihosting::FileFeatures::read(), and ArmSemihosting::FileFeatures::seek().
files
std::vector<std::unique_ptr<FileBase> > ArmSemihosting::files protected
Definition at line 246 of file semihosting.hh.
Referenced by ArmSemihosting(), readString(), serialize(), and unserialize().
fmodes
const std::vector< const char * > ArmSemihosting::fmodes static private
Initial value:
{
    "r", "rb", "r+", "r+b",
    "w", "wb", "w+", "w+b",
    "a", "ab", "a+", "a+b",
}
Definition at line 352 of file semihosting.hh.
Referenced by readString().
memReserve
const Addr ArmSemihosting::memReserve protected
Definition at line 85 of file semihosting.hh.
Referenced by readString().
physProxyS
std::unique_ptr<PortProxy> ArmSemihosting::physProxyS protected
Definition at line 263 of file semihosting.hh.
Referenced by physProxy().
semiErrno
SemiErrno ArmSemihosting::semiErrno protected
Definition at line 99 of file semihosting.hh.
Referenced by ArmSemihosting(), call32(), call64(), readString(), serialize(), and unserialize().
stackSize
const Addr ArmSemihosting::stackSize protected
Definition at line 86 of file semihosting.hh.
Referenced by readString().
stderr
FILE* ArmSemihosting::stderr protected
Definition at line 249 of file semihosting.hh.
Referenced by ArmSemihosting(), ArmSemihosting::File::isTTY(), and ArmSemihosting::File::openImpl().
stdin
FILE* ArmSemihosting::stdin protected
Definition at line 247 of file semihosting.hh.
Referenced by ArmSemihosting(), ArmSemihosting::File::isTTY(), and ArmSemihosting::File::openImpl().
stdioMap
const std::map< const std::string, FILE * > ArmSemihosting::stdioMap static private
Initial value:
{
    {"cin",    ::stdin},
    {"stdin",  ::stdin},
    {"cout",   ::stdout},
    {"stdout", ::stdout},
    {"cerr",   ::stderr},
    {"stderr", ::stderr},
}
Definition at line 355 of file semihosting.hh.
Referenced by getSTDIO().
stdout
FILE* ArmSemihosting::stdout protected
Definition at line 248 of file semihosting.hh.
Referenced by ArmSemihosting(), ArmSemihosting::File::isTTY(), and ArmSemihosting::File::openImpl().
tickShift
const unsigned ArmSemihosting::tickShift protected
Number of bits to right shift gem5 ticks to fit in a uint32_t.
Definition at line 95 of file semihosting.hh.
Referenced by ArmSemihosting(), and semiTick().
timeBase
const time_t ArmSemihosting::timeBase protected
Base time when the simulation started.
This is used to calculate the time of date when the guest call SYS_TIME.
Definition at line 92 of file semihosting.hh.
Referenced by readString().
The documentation for this class was generated from the following files:
arch/arm/semihosting.hh
arch/arm/semihosting.cc