gem5: sc_core::sc_signal_in_if< sc_dt::sc_logic > Class Template Reference
sc_core::sc_signal_in_if< sc_dt::sc_logic > Class Template Reference abstract
#include <sc_signal_in_if.hh>
Public Member Functions
virtual const sc_dt::sc_logic & read () const =0
virtual const sc_event & value_changed_event () const =0
virtual const sc_event & posedge_event () const =0
virtual const sc_event & negedge_event () const =0
virtual bool event () const =0
virtual bool posedge () const =0
virtual bool negedge () const =0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_signal_in_if (const sc_signal_in_if< sc_dt::sc_logic > &)
sc_signal_in_if< sc_dt::sc_logic > & operator= (const sc_signal_in_if< sc_dt::sc_logic > &)
Detailed Description
template<>
class sc_core::sc_signal_in_if< sc_dt::sc_logic >
Definition at line 110 of file sc_signal_in_if.hh.
Constructor & Destructor Documentation
sc_signal_in_if() [1/2]
sc_core::sc_signal_in_if< sc_dt::sc_logic >::sc_signal_in_if () inline protected
Definition at line 124 of file sc_signal_in_if.hh.
sc_signal_in_if() [2/2]
sc_core::sc_signal_in_if< sc_dt::sc_logic >::sc_signal_in_if (const sc_signal_in_if< sc_dt::sc_logic > &) inline private
Definition at line 128 of file sc_signal_in_if.hh.
Member Function Documentation
event()
virtual bool sc_core::sc_signal_in_if< sc_dt::sc_logic >::event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
negedge()
virtual bool sc_core::sc_signal_in_if< sc_dt::sc_logic >::negedge () const pure virtual
Implemented in sc_gem5::ScSignalBinary< sc_dt::sc_logic, WRITER_POLICY >.
negedge_event()
virtual const sc_event& sc_core::sc_signal_in_if< sc_dt::sc_logic >::negedge_event () const pure virtual
Implemented in sc_gem5::ScSignalBinary< sc_dt::sc_logic, WRITER_POLICY >.
operator=()
sc_signal_in_if<sc_dt::sc_logic>& sc_core::sc_signal_in_if< sc_dt::sc_logic >::operator= (const sc_signal_in_if< sc_dt::sc_logic > &) inline private
Definition at line 132 of file sc_signal_in_if.hh.
posedge()
virtual bool sc_core::sc_signal_in_if< sc_dt::sc_logic >::posedge () const pure virtual
Implemented in sc_gem5::ScSignalBinary< sc_dt::sc_logic, WRITER_POLICY >.
posedge_event()
virtual const sc_event& sc_core::sc_signal_in_if< sc_dt::sc_logic >::posedge_event () const pure virtual
Implemented in sc_gem5::ScSignalBinary< sc_dt::sc_logic, WRITER_POLICY >.
Referenced by sc_core::sc_sensitive::operator()().
read()
virtual const sc_dt::sc_logic& sc_core::sc_signal_in_if< sc_dt::sc_logic >::read () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
Referenced by sc_core::at_negedge(), sc_core::at_posedge(), sc_core::sc_inout< sc_dt::sc_logic >::initialize(), sc_core::sc_out_resolved::operator=(), sc_core::sc_inout_resolved::operator=(), and sc_core::sc_inout< sc_dt::sc_logic >::operator=().
value_changed_event()
virtual const sc_event& sc_core::sc_signal_in_if< sc_dt::sc_logic >::value_changed_event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_signal_in_if.hh