gem5: EtherBus Class Reference
EtherBus Class Reference
#include <etherbus.hh>
Public Types
typedef EtherBusParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
EtherBus (const Params *p)
virtual ~EtherBus ()
const Params * params () const
void txDone ()
void reg (EtherInt *dev)
bool busy () const
bool send (EtherInt *sender, EthPacketPtr &packet)
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
typedef std::list< EtherInt * > devlist_t
Protected Attributes
devlist_t devlist
double ticksPerByte
bool loopback
EventFunctionWrapper event
EthPacketPtr packet
EtherInt * sender
EtherDump * dump
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 45 of file etherbus.hh.
Member Typedef Documentation
devlist_t
typedef std::list<EtherInt *> EtherBus::devlist_t protected
Definition at line 48 of file etherbus.hh.
Params
typedef EtherBusParams EtherBus::Params
Definition at line 60 of file etherbus.hh.
Constructor & Destructor Documentation
EtherBus()
EtherBus::EtherBus (const Params * p)
Definition at line 53 of file etherbus.cc.
References dump, MipsISA::p, sender, and txDone().
Referenced by send().
~EtherBus()
virtual EtherBus::~EtherBus () inline virtual
Definition at line 62 of file etherbus.hh.
Member Function Documentation
busy()
bool EtherBus::busy () const inline
Definition at line 72 of file etherbus.hh.
References getPort(), InvalidPortID, packet, and send().
Referenced by send().
getPort()
Port & EtherBus::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 85 of file etherbus.cc.
References panic.
Referenced by busy().
params()
const Params* EtherBus::params () const inline
Definition at line 65 of file etherbus.hh.
References SimObject::_params, reg(), and txDone().
reg()
void EtherBus::reg (EtherInt * dev)
Referenced by params().
send()
bool EtherBus::send (EtherInt * sender, EthPacketPtr & packet)
Definition at line 91 of file etherbus.cc.
References busy(), curTick(), DDUMP, DPRINTF, EtherBus(), event, packet, EventManager::schedule(), sender, and ticksPerByte.
Referenced by busy().
txDone()
void EtherBus::txDone ()
Definition at line 61 of file etherbus.cc.
References DDUMP, devlist, DPRINTF, dump, EtherDump::dump(), ArmISA::i, loopback, packet, EtherInt::sendDone(), and sender.
Referenced by EtherBus(), and params().
Member Data Documentation
devlist
devlist_t EtherBus::devlist protected
Definition at line 49 of file etherbus.hh.
Referenced by txDone().
dump
EtherDump* EtherBus::dump protected
Definition at line 57 of file etherbus.hh.
Referenced by EtherBus(), and txDone().
event
EventFunctionWrapper EtherBus::event protected
Definition at line 54 of file etherbus.hh.
Referenced by send().
loopback
bool EtherBus::loopback protected
Definition at line 51 of file etherbus.hh.
Referenced by txDone().
packet
EthPacketPtr EtherBus::packet protected
Definition at line 55 of file etherbus.hh.
Referenced by busy(), send(), and txDone().
sender
EtherInt* EtherBus::sender protected
Definition at line 56 of file etherbus.hh.
Referenced by EtherBus(), send(), and txDone().
ticksPerByte
double EtherBus::ticksPerByte protected
Definition at line 50 of file etherbus.hh.
Referenced by send().
The documentation for this class was generated from the following files:
dev/net/etherbus.hh
dev/net/etherbus.cc