gem5: sc_gem5::ClockTick Class Reference
sc_gem5::ClockTick Class Reference
Public Member Functions
ClockTick (::sc_core::sc_clock *clock, bool to, ::sc_core::sc_time _period)
void createProcess ()
~ClockTick ()
void tick ()
Public Member Functions inherited from sc_gem5::ScEvent
ScEvent (std::function< void()> work)
~ScEvent ()
bool scheduled ()
ScEvents * scheduledOn ()
void when (Tick w)
Tick when ()
void run ()
Private Attributes
::sc_core::sc_time _period
std::string name
Process * p
ProcessMemberFuncWrapper<::sc_core::sc_clock > funcWrapper
Detailed Description
Definition at line 47 of file sc_clock.cc.
Constructor & Destructor Documentation
ClockTick()
sc_gem5::ClockTick::ClockTick (::sc_core::sc_clock * clock, bool to, ::sc_core::sc_time _period) inline
Definition at line 56 of file sc_clock.cc.
References _period, funcWrapper, name, p, sc_core::sc_gen_unique_name(), tick(), sc_core::sc_clock::tickDown(), and sc_core::sc_clock::tickUp().
~ClockTick()
sc_gem5::ClockTick::~ClockTick () inline
Definition at line 75 of file sc_clock.cc.
References sc_gem5::Scheduler::deschedule(), sc_gem5::ListNode::popListNode(), sc_gem5::ScEvent::scheduled(), and sc_gem5::scheduler.
Member Function Documentation
createProcess()
void sc_gem5::ClockTick::createProcess () inline
Definition at line 68 of file sc_clock.cc.
References sc_gem5::Process::dontInitialize(), funcWrapper, sc_gem5::Scheduler::reg(), and sc_gem5::scheduler.
Referenced by sc_core::sc_clock::before_end_of_elaboration().
tick()
void sc_gem5::ClockTick::tick () inline
Definition at line 84 of file sc_clock.cc.
References sc_gem5::Process::ready(), sc_gem5::Scheduler::schedule(), and sc_gem5::scheduler.
Referenced by ClockTick().
Member Data Documentation
_period
::sc_core::sc_time sc_gem5::ClockTick::_period private
Definition at line 50 of file sc_clock.cc.
Referenced by ClockTick().
funcWrapper
ProcessMemberFuncWrapper<::sc_core::sc_clock> sc_gem5::ClockTick::funcWrapper private
Definition at line 53 of file sc_clock.cc.
Referenced by ClockTick(), and createProcess().
name
std::string sc_gem5::ClockTick::name private
Definition at line 51 of file sc_clock.cc.
Referenced by ClockTick().
p
Process* sc_gem5::ClockTick::p private
Definition at line 52 of file sc_clock.cc.
Referenced by ClockTick().
The documentation for this class was generated from the following file:
systemc/channel/sc_clock.cc