gem5: sc_core::sc_signed_part_if Class Reference
sc_core::sc_signed_part_if Class Reference
#include <scx_signal_signed.h>
Public Member Functions
virtual sc_dt::sc_signed * part_read_target ()
virtual sc_dt::sc_signed read_part (int left, int right) const
virtual sc_signed_sigref & select_part (int left, int right)
virtual void write_part (sc_dt::int64 v, int left, int right)
virtual void write_part (sc_dt::uint64 v, int left, int right)
virtual void write_part (const sc_dt::sc_signed &v, int left, int right)
virtual void write_part (const sc_dt::sc_unsigned &v, int left, int right)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_signed_part_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_signed_part_if (const sc_signed_part_if &)
sc_signed_part_if & operator= (const sc_signed_part_if &)
Detailed Description
Definition at line 209 of file scx_signal_signed.h.
Constructor & Destructor Documentation
sc_signed_part_if() [1/2]
sc_core::sc_signed_part_if::sc_signed_part_if () inline protected
Definition at line 212 of file scx_signal_signed.h.
References operator=(), part_read_target(), read_part(), select_part(), ArmISA::v, and write_part().
sc_signed_part_if() [2/2]
sc_core::sc_signed_part_if::sc_signed_part_if (const sc_signed_part_if &) private
Member Function Documentation
operator=()
sc_signed_part_if& sc_core::sc_signed_part_if::operator= (const sc_signed_part_if &) private
Referenced by sc_core::sc_signal_in_if< sc_dt::sc_bigint< W > >::sc_signal_in_if(), sc_signed_part_if(), and sc_core::sc_signed_sigref::~sc_signed_sigref().
part_read_target()
sc_signed * sc_core::sc_signed_part_if::part_read_target () virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 1745 of file scx_signal_signed.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_core::sc_signed_sigref::initialize(), and sc_signed_part_if().
read_part()
sc_signed sc_core::sc_signed_part_if::read_part (int left, int right) const virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 1750 of file scx_signal_signed.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_signed_part_if().
select_part()
sc_signed_sigref & sc_core::sc_signed_part_if::select_part (int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 1755 of file scx_signal_signed.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, SC_REPORT_ERROR, ArmISA::v, and write_part().
Referenced by sc_signed_part_if().
write_part() [1/4]
virtual void sc_core::sc_signed_part_if::write_part (sc_dt::int64 v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Referenced by sc_signed_part_if(), and select_part().
write_part() [2/4]
virtual void sc_core::sc_signed_part_if::write_part (sc_dt::uint64 v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
write_part() [3/4]
void sc_core::sc_signed_part_if::write_part (const sc_dt::sc_signed & v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 1768 of file scx_signal_signed.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
write_part() [4/4]
void sc_core::sc_signed_part_if::write_part (const sc_dt::sc_unsigned & v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 1773 of file scx_signal_signed.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_signed.h