gem5: Net::IpPtr Class Reference
Net::IpPtr Class Reference
#include <inet.hh>
Public Member Functions
IpPtr ()
IpPtr (const EthPacketPtr &ptr)
IpPtr (const EthPtr &ptr)
IpPtr (const IpPtr &ptr)
IpHdr * get ()
IpHdr * operator-> ()
IpHdr & operator* ()
const IpHdr * get () const
const IpHdr * operator-> () const
const IpHdr & operator* () const
const IpPtr & operator= (const EthPacketPtr &ptr)
const IpPtr & operator= (const EthPtr &ptr)
const IpPtr & operator= (const IpPtr &ptr)
const EthPacketPtr packet () const
EthPacketPtr packet ()
bool operator! () const
operator bool () const
int off () const
int pstart () const
Protected Member Functions
void set (const EthPacketPtr &ptr)
Protected Attributes
EthPacketPtr p
bool eth_hdr_vlan
Friends
class TcpPtr
class UdpPtr
Detailed Description
Definition at line 281 of file inet.hh.
Constructor & Destructor Documentation
IpPtr() [1/4]
Net::IpPtr::IpPtr () inline
Definition at line 304 of file inet.hh.
IpPtr() [2/4]
Net::IpPtr::IpPtr (const EthPacketPtr & ptr) inline
Definition at line 305 of file inet.hh.
IpPtr() [3/4]
Net::IpPtr::IpPtr (const EthPtr & ptr) inline
Definition at line 306 of file inet.hh.
References Net::EthPtr::p.
IpPtr() [4/4]
Net::IpPtr::IpPtr (const IpPtr & ptr) inline
Definition at line 307 of file inet.hh.
Member Function Documentation
get() [1/2]
IpHdr* Net::IpPtr::get () inline
Definition at line 309 of file inet.hh.
get() [2/2]
const IpHdr* Net::IpPtr::get () const inline
Definition at line 314 of file inet.hh.
off()
int Net::IpPtr::off () const inline
Definition at line 328 of file inet.hh.
operator bool()
Net::IpPtr::operator bool () const inline
Definition at line 327 of file inet.hh.
operator!()
bool Net::IpPtr::operator! () const inline
Definition at line 326 of file inet.hh.
References MipsISA::p.
operator*() [1/2]
IpHdr& Net::IpPtr::operator* () inline
Definition at line 312 of file inet.hh.
operator*() [2/2]
const IpHdr& Net::IpPtr::operator* () const inline
Definition at line 318 of file inet.hh.
operator->() [1/2]
IpHdr* Net::IpPtr::operator-> () inline
Definition at line 311 of file inet.hh.
operator->() [2/2]
const IpHdr* Net::IpPtr::operator-> () const inline
Definition at line 317 of file inet.hh.
operator=() [1/3]
const IpPtr& Net::IpPtr::operator= (const EthPacketPtr & ptr) inline
Definition at line 320 of file inet.hh.
operator=() [2/3]
const IpPtr& Net::IpPtr::operator= (const EthPtr & ptr) inline
Definition at line 321 of file inet.hh.
References Net::EthPtr::p.
operator=() [3/3]
const IpPtr& Net::IpPtr::operator= (const IpPtr & ptr) inline
Definition at line 322 of file inet.hh.
References p.
packet() [1/2]
const EthPacketPtr Net::IpPtr::packet () const inline
Definition at line 324 of file inet.hh.
References MipsISA::p.
packet() [2/2]
EthPacketPtr Net::IpPtr::packet () inline
Definition at line 325 of file inet.hh.
References MipsISA::p.
pstart()
int Net::IpPtr::pstart () const inline
Definition at line 329 of file inet.hh.
References Net::cksum(), and Net::EthAddr::size().
Referenced by Net::hsplit().
set()
void Net::IpPtr::set (const EthPacketPtr & ptr) inline protected
Definition at line 289 of file inet.hh.
References Net::EthHdr::isVlan(), and Net::EthHdr::type().
Friends And Related Function Documentation
TcpPtr
friend class TcpPtr friend
Definition at line 284 of file inet.hh.
UdpPtr
friend class UdpPtr friend
Definition at line 285 of file inet.hh.
Member Data Documentation
eth_hdr_vlan
bool Net::IpPtr::eth_hdr_vlan protected
Definition at line 287 of file inet.hh.
p
EthPacketPtr Net::IpPtr::p protected
Definition at line 286 of file inet.hh.
Referenced by operator=().
The documentation for this class was generated from the following file:
base/inet.hh