gem5: FPCD Class Reference
FPCD Class Reference
#include <fpcd.hh>
Classes
class PatternFFFF
class PatternFFXX
class PatternMMMMPenultimate
class PatternMMMMPrevious
class PatternMMMXPenultimate
class PatternMMMXPrevious
class PatternMMXXPenultimate
class PatternMMXXPrevious
class PatternRRRR
class PatternXXXX
class PatternXXZZ
class PatternXZZZ
class PatternZXZX
class PatternZZXX
class PatternZZZX
class PatternZZZZ
Public Types
typedef FPCDParams Params
Public Types inherited from DictionaryCompressor< uint32_t >
typedef BaseDictionaryCompressorParams Params
Public Types inherited from BaseDictionaryCompressor
typedef BaseDictionaryCompressorParams Params
Public Types inherited from BaseCacheCompressor
typedef BaseCacheCompressorParams Params
Convenience typedef.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
FPCD (const Params *p)
~FPCD ()=default
Public Member Functions inherited from DictionaryCompressor< uint32_t >
DictionaryCompressor (const Params *p)
~DictionaryCompressor ()=default
Public Member Functions inherited from BaseDictionaryCompressor
BaseDictionaryCompressor (const Params *p)
~BaseDictionaryCompressor ()=default
void regStats () override
Register local statistics.
Public Member Functions inherited from BaseCacheCompressor
BaseCacheCompressor (const Params *p)
Default constructor.
virtual ~BaseCacheCompressor ()
Default destructor.
void compress (const uint64_t *data, Cycles &comp_lat, Cycles &decomp_lat, std::size_t &comp_size_bits)
Apply the compression process to the cache line.
Cycles getDecompressionLatency (const CacheBlk *blk) const
Get the decompression latency if the block is compressed.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Types
enum PatternNumber {
ZZZZ, FFFF, MMMMPenultimate, MMMMPrevious,
ZZZX, XZZZ, RRRR, MMMXPenultimate,
MMMXPrevious, ZZXX, ZXZX, FFXX,
XXZZ, MMXXPenultimate, MMXXPrevious, XXXX,
NUM_PATTERNS
}
The patterns proposed in the paper.
using DictionaryEntry = DictionaryCompressor< uint32_t >::DictionaryEntry
using PatternFactory = Factory< PatternZZZZ, PatternFFFF, PatternMMMMPrevious, PatternMMMMPenultimate, PatternZZZX, PatternXZZZ, PatternRRRR, PatternMMMXPrevious, PatternMMMXPenultimate, PatternZZXX, PatternZXZX, PatternFFXX, PatternXXZZ, PatternMMXXPrevious, PatternMMXXPenultimate, PatternXXXX >
Convenience factory declaration.
Private Member Functions
uint64_t getNumPatterns () const override
Trick function to get the number of patterns.
std::string getName (int number) const override
Get meta-name assigned to the given pattern.
std::unique_ptr< Pattern > getPattern (const DictionaryEntry &bytes, const DictionaryEntry &dict_bytes, const int match_location) const override
void addToDictionary (DictionaryEntry data) override
std::unique_ptr< BaseCacheCompressor::CompressionData > compress (const uint64_t *data, Cycles &comp_lat, Cycles &decomp_lat) override
Apply the compression process to the cache line.
Static Private Attributes
static constexpr int prefixSize = 4
Number of bits in a FPCD pattern prefix.
static constexpr int previousIndex = 1
Index of the previous dictionary entry.
static constexpr int penultimateIndex = 0
Index of the penultimate dictionary entry.
Additional Inherited Members
Static Public Member Functions inherited from BaseCacheCompressor
static void setDecompressionLatency (CacheBlk *blk, const Cycles lat)
Set the decompression latency of compressed block.
static void setSizeBits (CacheBlk *blk, const std::size_t size_bits)
Set the size of the compressed block, in bits.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from DictionaryCompressor< uint32_t >
typedef std::array< uint8_t, sizeof(uint32_t)> DictionaryEntry
Convenience typedef for a dictionary entry.
Protected Member Functions inherited from DictionaryCompressor< uint32_t >
virtual std::unique_ptr< Pattern > getPattern (const DictionaryEntry &bytes, const DictionaryEntry &dict_bytes, const int match_location) const=0
Since the factory cannot be instantiated here, classes that inherit from this base class have to implement the call to their factory's getPattern.
std::unique_ptr< Pattern > compressValue (const uint32_t data)
Compress data.
uint32_t decompressValue (const Pattern *pattern)
Decompress a pattern into a value that fits in a dictionary entry.
virtual void resetDictionary ()
Clear all dictionary entries.
virtual void addToDictionary (const DictionaryEntry data)=0
Add an entry to the dictionary.
std::unique_ptr< BaseCacheCompressor::CompressionData > compress (const uint64_t *data)
Apply compression.
void decompress (const CompressionData *comp_data, uint64_t *data) override
Decompress data.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Static Protected Member Functions inherited from DictionaryCompressor< uint32_t >
static DictionaryEntry toDictionaryEntry (uint32_t value)
Turn a value into a dictionary entry.
static uint32_t fromDictionaryEntry (const DictionaryEntry &entry)
Turn a dictionary entry into a value.
Protected Attributes inherited from DictionaryCompressor< uint32_t >
std::vector< DictionaryEntry > dictionary
The dictionary.
Protected Attributes inherited from BaseDictionaryCompressor
const std::size_t dictionarySize
Dictionary size.
std::size_t numEntries
Number of valid entries in the dictionary.
Stats::Vector patternStats
Number of data entries that were compressed to each pattern.
Protected Attributes inherited from BaseCacheCompressor
const std::size_t blkSize
Uncompressed cache line size (in bytes).
const std::size_t sizeThreshold
Size in bytes at which a compression is classified as bad and therefore the compressed block is restored to its uncompressed format.
Stats::Vector compressionSize
Number of blocks that were compressed to this power of two size.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 54 of file fpcd.hh.
Member Typedef Documentation
DictionaryEntry
using FPCD::DictionaryEntry = DictionaryCompressor<uint32_t>::DictionaryEntry private
Definition at line 57 of file fpcd.hh.
Params
typedef FPCDParams FPCD::Params
Definition at line 146 of file fpcd.hh.
PatternFactory
using FPCD::PatternFactory = Factory<PatternZZZZ, PatternFFFF, PatternMMMMPrevious, PatternMMMMPenultimate, PatternZZZX, PatternXZZZ, PatternRRRR, PatternMMMXPrevious, PatternMMMXPenultimate, PatternZZXX, PatternZXZX, PatternFFXX, PatternXXZZ, PatternMMXXPrevious, PatternMMXXPenultimate, PatternXXXX> private
Convenience factory declaration.
The templates must be organized by size, with the smallest first, and "no-match" last.
Definition at line 110 of file fpcd.hh.
Member Enumeration Documentation
PatternNumber
enum FPCD::PatternNumber private
The patterns proposed in the paper.
Each letter represents a byte: Z is a null byte, M is a dictionary match, X is a new value, R is a repeated value. These are used as indexes to reference the pattern data. If a new pattern is added, it must be done before NUM_PATTERNS.
Enumerator
ZZZZ
FFFF
MMMMPenultimate
MMMMPrevious
ZZZX
XZZZ
RRRR
MMMXPenultimate
MMMXPrevious
ZZXX
ZXZX
FFXX
XXZZ
MMXXPenultimate
MMXXPrevious
XXXX
NUM_PATTERNS
Definition at line 95 of file fpcd.hh.
Constructor & Destructor Documentation
FPCD()
FPCD::FPCD (const Params * p)
Definition at line 40 of file fpcd.cc.
Referenced by compress().
~FPCD()
FPCD::~FPCD () default
Member Function Documentation
addToDictionary()
void FPCD::addToDictionary (DictionaryEntry data) override private
Definition at line 46 of file fpcd.cc.
References data, DictionaryCompressor< uint32_t >::dictionary, BaseDictionaryCompressor::numEntries, penultimateIndex, and previousIndex.
Referenced by getPattern().
compress()
std::unique_ptr< BaseCacheCompressor::CompressionData > FPCD::compress (const uint64_t * cache_line, Cycles & comp_lat, Cycles & decomp_lat) override private virtual
Apply the compression process to the cache line.
Returns the number of cycles used by the compressor, however it is usually covered by a good pipelined execution, and is currently ignored. The decompression latency is also returned, in order to avoid increasing simulation time and memory consumption.
Parameters
cache_line The cache line to be compressed.
comp_lat Compression latency in number of cycles.
decomp_lat Decompression latency in number of cycles.
Returns
Cache line after compression.
Implements BaseCacheCompressor.
Definition at line 58 of file fpcd.cc.
References BaseCacheCompressor::blkSize, DictionaryCompressor< T >::compress(), and FPCD().
Referenced by getPattern().
getName()
std::string FPCD::getName (int number) const inline override private virtual
Get meta-name assigned to the given pattern.
Parameters
number The number of the pattern.
Returns
The meta-name of the pattern.
Implements BaseDictionaryCompressor.
Definition at line 115 of file fpcd.hh.
References FFFF, FFXX, MMMMPenultimate, MMMMPrevious, MMMXPenultimate, MMMXPrevious, MMXXPenultimate, MMXXPrevious, RRRR, XXXX, XXZZ, XZZZ, ZXZX, ZZXX, ZZZX, and ZZZZ.
getNumPatterns()
uint64_t FPCD::getNumPatterns () const inline override private virtual
Trick function to get the number of patterns.
Returns
The number of defined patterns.
Implements BaseDictionaryCompressor.
Definition at line 112 of file fpcd.hh.
References NUM_PATTERNS.
getPattern()
std::unique_ptr<Pattern> FPCD::getPattern (const DictionaryEntry & bytes, const DictionaryEntry & dict_bytes, const int match_location) const inline override private
Definition at line 134 of file fpcd.hh.
References addToDictionary(), compress(), and data.
Member Data Documentation
penultimateIndex
constexpr int FPCD::penultimateIndex = 0 static private
Index of the penultimate dictionary entry.
Definition at line 66 of file fpcd.hh.
Referenced by addToDictionary().
prefixSize
constexpr int FPCD::prefixSize = 4 static private
Number of bits in a FPCD pattern prefix.
Definition at line 60 of file fpcd.hh.
previousIndex
constexpr int FPCD::previousIndex = 1 static private
Index of the previous dictionary entry.
Definition at line 63 of file fpcd.hh.
Referenced by addToDictionary().
The documentation for this class was generated from the following files:
mem/cache/compressors/fpcd.hh
mem/cache/compressors/fpcd.cc