gem5: EventManager Class Reference
EventManager Class Reference
#include <eventq.hh>
Public Member Functions
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Protected Attributes
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 726 of file eventq.hh.
Constructor & Destructor Documentation
EventManager() [1/3]
EventManager::EventManager (EventManager & em) inline
Definition at line 733 of file eventq.hh.
EventManager() [2/3]
EventManager::EventManager (EventManager * em) inline
Definition at line 734 of file eventq.hh.
EventManager() [3/3]
EventManager::EventManager (EventQueue * eq) inline
Definition at line 735 of file eventq.hh.
Member Function Documentation
deschedule() [1/2]
void EventManager::deschedule (Event & event) inline
Definition at line 750 of file eventq.hh.
References EventQueue::deschedule().
Referenced by BaseCPU::activateContext(), IGbE::chkInterrupt(), HDLcd::cmdDisable(), MemTest::completeRequest(), IGbE::cpuPostInt(), BaseCPU::deschedulePowerGatingEvent(), BaseKvmCPU::drain(), ArchTimer::drain(), AtomicSimpleCPU::drain(), BaseTrafficGen::drain(), FullO3CPU< O3CPUImpl >::drain(), IGbE::drain(), VIPERCoalescer::makeRequest(), DVFSHandler::perfLevel(), IGbE::postInterrupt(), Sp804::Timer::restartCounter(), A9GlobalTimer::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), PL031::resyncMatch(), SparcISA::ISA::setFSReg(), BasePixelPump::stop(), BasePixelPump::PixelEvent::suspend(), DRAMCtrl::Rank::suspend(), BaseKvmCPU::suspendContext(), AtomicSimpleCPU::suspendContext(), TimingSimpleCPU::suspendContext(), BaseCPU::switchOut(), Root::timeSyncEnable(), FullO3CPU< O3CPUImpl >::tryDrain(), GpuDispatcher::unserialize(), ArchTimer::updateCounter(), Uart8250::write(), EnergyCtrl::write(), Intel8254Timer::Counter::write(), MC146818::writeData(), AtomicSimpleCPU::~AtomicSimpleCPU(), and MC146818::~MC146818().
deschedule() [2/2]
void EventManager::deschedule (Event * event) inline
Definition at line 768 of file eventq.hh.
References EventQueue::deschedule().
eventQueue()
EventQueue* EventManager::eventQueue () const inline
Definition at line 738 of file eventq.hh.
Referenced by VncServer::accept(), X86KvmCPU::deliverInterrupts(), BaseKvmCPU::deviceEventQueue(), BaseKvmCPU::drain(), sc_gem5::Kernel::Kernel(), TapEvent::process(), Terminal::DataEvent::process(), and BaseKvmCPU::wakeup().
reschedule() [1/2]
void EventManager::reschedule (Event & event, Tick when, bool always = false) inline
Definition at line 756 of file eventq.hh.
References EventQueue::reschedule().
Referenced by FlashDevice::accessDevice(), FlashDevice::actionComplete(), DRAMCtrl::activateBank(), TimingSimpleCPU::advanceInst(), MemTest::completeRequest(), SimpleMemory::dequeue(), EtherSwitch::Interface::enqueue(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), DRAMCtrl::prechargeBank(), DRAMCtrl::processNextReqEvent(), ThreadContext::quiesceTick(), MemTest::recvRetry(), TraceCPU::schedDcacheNextEvent(), PacketQueue::schedSendEvent(), FullO3CPU< O3CPUImpl >::scheduleTickEvent(), IdeDisk::serialize(), AtomicSimpleCPU::tick(), MemTest::tick(), Sinic::Device::transferDone(), NSGigE::transferDone(), X86ISA::Interrupts::unserialize(), IdeDisk::unserialize(), and BaseTrafficGen::update().
reschedule() [2/2]
void EventManager::reschedule (Event * event, Tick when, bool always = false) inline
Definition at line 774 of file eventq.hh.
References EventQueue::reschedule().
schedule() [1/2]
void EventManager::schedule (Event & event, Tick when) inline
Definition at line 744 of file eventq.hh.
References EventQueue::schedule().
Referenced by DRAMSim2::accessAndRespond(), FlashDevice::accessDevice(), BaseKvmCPU::activateContext(), AtomicSimpleCPU::activateContext(), TimingSimpleCPU::activateContext(), BaseCPU::BaseCPU(), BasePixelPump::beginLine(), TraceCPU::checkAndSchedExitEvent(), DRAMCtrl::Rank::checkDrainDone(), IGbE::chkInterrupt(), HDLcd::cmdEnable(), Sinic::Base::cpuIntrPost(), NSGigE::cpuIntrPost(), CPUProgressEvent::CPUProgressEvent(), TraceCPU::dcacheRetryRecvd(), BOPPrefetcher::delayQueueEventWrapper(), TimingSimpleCPU::TimingCPUPort::TickEvent::description(), Shader::dispatch_workgroups(), Pl111::dmaDone(), IdeDisk::doDmaDataRead(), IdeDisk::doDmaDataWrite(), IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), IdeDisk::doDmaWrite(), ThermalModel::doStep(), TimingSimpleCPU::drain(), BaseKvmCPU::drainResume(), AtomicSimpleCPU::drainResume(), TimingSimpleCPU::drainResume(), FullO3CPU< O3CPUImpl >::drainResume(), RubySystem::enqueueRubyEvent(), GoodbyeObject::fillBuffer(), Minor::LSQ::SplitDataRequest::finish(), BaseKvmCPU::finishMMIOPending(), GarnetSyntheticTraffic::GarnetSyntheticTraffic(), GpuDispatcher::GpuDispatcher(), SimpleCache::handleRequest(), DmaPort::handleResp(), X86ISA::GpuTLB::handleTranslationReturn(), RubyDirectedTester::hitCallback(), TraceCPU::icacheRetryRecvd(), TraceCPU::init(), BOPPrefetcher::insertIntoDelayQueue(), Sequencer::insertRequest(), GPUCoalescer::insertRequest(), TimingSimpleCPU::IprEvent::IprEvent(), X86ISA::GpuTLB::issueTLBLookup(), VIPERCoalescer::makeRequest(), GPUCoalescer::makeRequest(), MemTest::MemTest(), ArmISA::TableWalker::nextWalk(), GpuDispatcher::notifyWgCompl(), DVFSHandler::perfLevel(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), IGbE::postInterrupt(), MC146818::RTCEvent::process(), MC146818::RTCTickEvent::process(), CPUProgressEvent::process(), AccessMapPatternMatching::processEpochEvent(), HelloObject::processEvent(), SparcISA::ISA::processHSTickCompare(), DRAMCtrl::Rank::processPowerEvent(), BaseCPU::processProfileEvent(), DRAMCtrl::Rank::processRefreshEvent(), SparcISA::ISA::processSTickCompare(), Shader::processTick(), EtherLink::Link::processTxQueue(), Pl111::readFramebuffer(), BaseCache::recvAtomic(), MemTest::recvRetry(), StubSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), X86ISA::Walker::recvTimingResp(), X86ISA::GpuTLB::MemSidePort::recvTimingResp(), BasePixelPump::renderPixels(), IGbE::restartClock(), Sp804::Timer::restartCounter(), A9GlobalTimer::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), BasePixelPump::PixelEvent::resume(), PL031::resyncMatch(), EtherTapBase::retransmit(), RubyDirectedTester::RubyDirectedTester(), RubyTester::RubyTester(), Gicv3Its::runProcessTiming(), NSGigE::rxKick(), CommMonitor::samplePeriodic(), SMMUv3SlaveInterface::schedAtsTimingResp(), TraceCPU::schedDcacheNextEvent(), TraceCPU::schedIcacheNext(), PacketQueue::schedSendEvent(), MipsISA::ISA::scheduleCP0Update(), SMMUv3SlaveInterface::scheduleDeviceRetry(), GpuDispatcher::scheduleDispatch(), MC146818::RTCEvent::scheduleIntr(), DRAMCtrl::Rank::schedulePowerEvent(), BaseCPU::schedulePowerGatingEvent(), FullO3CPU< O3CPUImpl >::scheduleThreadExitEvent(), FullO3CPU< O3CPUImpl >::scheduleTickEvent(), BaseTrafficGen::scheduleUpdate(), SMMUProcess::scheduleWakeup(), DRAMCtrl::Rank::scheduleWakeUpEvent(), EtherBus::send(), ComputeUnit::sendRequest(), DRAMSim2::sendResponse(), EtherTapBase::sendSimulated(), ComputeUnit::sendSyncRequest(), SparcISA::ISA::setFSReg(), Pl011::setInterrupts(), Intel8254Timer::Counter::CounterEvent::setTo(), BasePixelPump::start(), IdeDisk::startDma(), sc_gem5::Kernel::startup(), HelloObject::startup(), CommMonitor::startup(), BaseKvmCPU::startup(), MC146818::startup(), ThermalModel::startup(), AccessMapPatternMatching::startup(), Intel8254Timer::Counter::startup(), DRAMSim2::startup(), BaseCPU::startup(), DRAMCtrl::Rank::startup(), BaseCPU::suspendContext(), BaseCPU::takeOverFrom(), GarnetSyntheticTraffic::tick(), MemTest::tick(), IGbE::tick(), DRAMSim2::tick(), FullO3CPU< O3CPUImpl >::tick(), BaseKvmCPU::tick(), Root::timeSync(), Root::timeSyncEnable(), X86ISA::GpuTLB::translationReturn(), EtherLink::Link::transmit(), EtherSwitch::Interface::transmit(), NSGigE::transmit(), EtherLink::Link::txDone(), NSGigE::txKick(), ThreadState::unserialize(), Sinic::Base::unserialize(), EtherSwitch::Interface::unserialize(), GpuDispatcher::unserialize(), Uart8250::unserialize(), EtherLink::Link::unserialize(), Sp804::Timer::unserialize(), PL031::unserialize(), EnergyCtrl::unserialize(), A9GlobalTimer::Timer::unserialize(), CpuLocalTimer::Timer::unserialize(), SparcISA::ISA::unserialize(), DVFSHandler::unserialize(), VGic::unserialize(), BaseTrafficGen::unserialize(), X86ISA::Interrupts::unserialize(), Sinic::Device::unserialize(), NSGigE::unserialize(), IdeDisk::unserialize(), Pl111::unserialize(), GicV2::unserialize(), IGbE::unserialize(), ArchTimer::updateCounter(), TLBCoalescer::updatePhysAddresses(), HDLcd::virtRefresh(), FullO3CPU< O3CPUImpl >::wakeCPU(), Sequencer::wakeup(), RubyDirectedTester::wakeup(), GPUCoalescer::wakeup(), RubyTester::wakeup(), EnergyCtrl::write(), GpuDispatcher::write(), SMMUv3::writeControl(), and MC146818::writeData().
schedule() [2/2]
void EventManager::schedule (Event * event, Tick when) inline
Definition at line 762 of file eventq.hh.
References EventQueue::schedule().
setCurTick()
void EventManager::setCurTick (Tick newVal) inline
Definition at line 784 of file eventq.hh.
References EventQueue::setCurTick().
Referenced by RubySystem::memWriteback(), and RubySystem::startup().
wakeupEventQueue()
void EventManager::wakeupEventQueue (Tick when = (Tick)-1) inline
Definition at line 779 of file eventq.hh.
References EventQueue::wakeup().
Member Data Documentation
eventq
EventQueue* EventManager::eventq protected
A pointer to this object's event queue.
Definition at line 730 of file eventq.hh.
Referenced by RubySystem::eventQueueEmpty(), RubySystem::memWriteback(), GicV2::postFiq(), GicV2::postInt(), VGic::postVInt(), and RubySystem::startup().
The documentation for this class was generated from the following file:
sim/eventq.hh