gem5: TAGE_SC_L_8KB_StatisticalCorrector Class Reference
TAGE_SC_L_8KB_StatisticalCorrector Class Reference
#include <tage_sc_l_8KB.hh>
Classes
struct SC_8KB_ThreadHistory
Public Member Functions
TAGE_SC_L_8KB_StatisticalCorrector (TAGE_SC_L_8KB_StatisticalCorrectorParams *p)
unsigned getIndBiasBank (Addr branch_pc, BranchInfo *bi, int hitBank, int altBank) const override
int gPredictions (ThreadID tid, Addr branch_pc, BranchInfo *bi, int &lsum, int64_t phist) override
int gIndexLogsSubstr (int nbr, int i) override
void scHistoryUpdate (Addr branch_pc, const StaticInstPtr &inst, bool taken, BranchInfo *tage_bi, Addr corrTarget) override
void gUpdates (ThreadID tid, Addr pc, bool taken, BranchInfo *bi, int64_t phist) override
Public Member Functions inherited from StatisticalCorrector
StatisticalCorrector (const StatisticalCorrectorParams *p)
virtual BranchInfo * makeBranchInfo ()
virtual void initBias ()
virtual bool scPredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo *bi, bool prev_pred_taken, bool bias_bit, bool use_conf_ctr, int8_t conf_ctr, unsigned conf_bits, int hitBank, int altBank, int64_t phist, int init_lsum=0)
virtual unsigned getIndBias (Addr branch_pc, BranchInfo *bi, bool b) const
virtual unsigned getIndBiasSK (Addr branch_pc, BranchInfo *bi) const
virtual unsigned getIndUpd (Addr branch_pc) const
unsigned getIndUpds (Addr branch_pc) const
int64_t gIndex (Addr branch_pc, int64_t bhist, int logs, int nbr, int i)
int gPredict (Addr branch_pc, int64_t hist, std::vector< int > &length, std::vector< int8_t > *tab, int nbr, int logs, std::vector< int8_t > &w)
virtual void gUpdate (Addr branch_pc, bool taken, int64_t hist, std::vector< int > &length, std::vector< int8_t > *tab, int nbr, int logs, std::vector< int8_t > &w, BranchInfo *bi)
void initGEHLTable (unsigned numLenghts, std::vector< int > lengths, std::vector< int8_t > *&table, unsigned logNumEntries, std::vector< int8_t > &w, int8_t wInitValue)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void regStats () override
Callback to set stat parameters.
void updateStats (bool taken, BranchInfo *bi)
virtual void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *bi, Addr corrTarget, bool bias_bit, int hitBank, int altBank, int64_t phist)
virtual size_t getSizeInBits () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
SCThreadHistory * makeThreadHistory () override
Private Attributes
const unsigned gnb
const unsigned logGnb
std::vector< int > gm
std::vector< int8_t > * ggehl
std::vector< int8_t > wg
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from StatisticalCorrector
template<typename T >
void ctrUpdate (T &ctr, bool taken, int nbits)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from StatisticalCorrector
SCThreadHistory * scHistory
const unsigned logBias
const unsigned logSizeUp
const unsigned logSizeUps
const unsigned numEntriesFirstLocalHistories
const unsigned bwnb
const unsigned logBwnb
std::vector< int > bwm
std::vector< int8_t > * bwgehl
std::vector< int8_t > wbw
const unsigned lnb
const unsigned logLnb
std::vector< int > lm
std::vector< int8_t > * lgehl
std::vector< int8_t > wl
const unsigned inb
const unsigned logInb
std::vector< int > im
std::vector< int8_t > * igehl
std::vector< int8_t > wi
std::vector< int8_t > bias
std::vector< int8_t > biasSK
std::vector< int8_t > biasBank
std::vector< int8_t > wb
int updateThreshold
std::vector< int > pUpdateThreshold
const unsigned chooserConfWidth
const unsigned updateThresholdWidth
const unsigned pUpdateThresholdWidth
const unsigned extraWeightsWidth
const unsigned scCountersWidth
int8_t firstH
int8_t secondH
Stats::Scalar scPredictorCorrect
Stats::Scalar scPredictorWrong
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 70 of file tage_sc_l_8KB.hh.
Constructor & Destructor Documentation
TAGE_SC_L_8KB_StatisticalCorrector()
TAGE_SC_L_8KB_StatisticalCorrector::TAGE_SC_L_8KB_StatisticalCorrector (TAGE_SC_L_8KB_StatisticalCorrectorParams * p)
Definition at line 47 of file tage_sc_l_8KB.cc.
References ggehl, gm, gnb, StatisticalCorrector::initGEHLTable(), logGnb, and wg.
Referenced by gUpdates().
Member Function Documentation
getIndBiasBank()
unsigned TAGE_SC_L_8KB_StatisticalCorrector::getIndBiasBank (Addr branch_pc, BranchInfo * bi, int hitBank, int altBank) const override virtual
Implements StatisticalCorrector.
Definition at line 67 of file tage_sc_l_8KB.cc.
References StatisticalCorrector::BranchInfo::highConf, StatisticalCorrector::logBias, StatisticalCorrector::BranchInfo::lowConf, and StatisticalCorrector::BranchInfo::predBeforeSC.
gIndexLogsSubstr()
int TAGE_SC_L_8KB_StatisticalCorrector::gIndexLogsSubstr (int nbr, int i) override virtual
Implements StatisticalCorrector.
Definition at line 98 of file tage_sc_l_8KB.cc.
gPredictions()
int TAGE_SC_L_8KB_StatisticalCorrector::gPredictions (ThreadID tid, Addr branch_pc, BranchInfo * bi, int & lsum, int64_t phist) override virtual
Implements StatisticalCorrector.
Definition at line 75 of file tage_sc_l_8KB.cc.
References StatisticalCorrector::bwgehl, StatisticalCorrector::bwm, StatisticalCorrector::bwnb, StatisticalCorrector::getIndUpd(), ggehl, TAGE_SC_L_8KB_StatisticalCorrector::SC_8KB_ThreadHistory::globalHist, gm, gnb, StatisticalCorrector::gPredict(), StatisticalCorrector::igehl, StatisticalCorrector::im, StatisticalCorrector::inb, StatisticalCorrector::lgehl, StatisticalCorrector::lm, StatisticalCorrector::lnb, StatisticalCorrector::logBwnb, logGnb, StatisticalCorrector::logInb, StatisticalCorrector::logLnb, StatisticalCorrector::pUpdateThreshold, StatisticalCorrector::scHistory, ArmISA::sh, StatisticalCorrector::updateThreshold, StatisticalCorrector::wbw, wg, StatisticalCorrector::wi, and StatisticalCorrector::wl.
gUpdates()
void TAGE_SC_L_8KB_StatisticalCorrector::gUpdates (ThreadID tid, Addr pc, bool taken, BranchInfo * bi, int64_t phist) override virtual
Implements StatisticalCorrector.
Definition at line 124 of file tage_sc_l_8KB.cc.
References PowerISA::bi, StatisticalCorrector::bwgehl, StatisticalCorrector::bwm, StatisticalCorrector::bwnb, ggehl, TAGE_SC_L_8KB_StatisticalCorrector::SC_8KB_ThreadHistory::globalHist, gm, gnb, StatisticalCorrector::gUpdate(), StatisticalCorrector::igehl, StatisticalCorrector::im, StatisticalCorrector::inb, StatisticalCorrector::lgehl, StatisticalCorrector::lm, StatisticalCorrector::lnb, StatisticalCorrector::logBwnb, logGnb, StatisticalCorrector::logInb, StatisticalCorrector::logLnb, StatisticalCorrector::scHistory, ArmISA::sh, TAGE_SC_L_8KB_StatisticalCorrector(), StatisticalCorrector::wbw, wg, StatisticalCorrector::wi, and StatisticalCorrector::wl.
makeThreadHistory()
TAGE_SC_L_8KB_StatisticalCorrector::SCThreadHistory * TAGE_SC_L_8KB_StatisticalCorrector::makeThreadHistory () override private virtual
Reimplemented from StatisticalCorrector.
Definition at line 58 of file tage_sc_l_8KB.cc.
References StatisticalCorrector::numEntriesFirstLocalHistories, and ArmISA::sh.
scHistoryUpdate()
void TAGE_SC_L_8KB_StatisticalCorrector::scHistoryUpdate (Addr branch_pc, const StaticInstPtr & inst, bool taken, BranchInfo * tage_bi, Addr corrTarget) override virtual
Reimplemented from StatisticalCorrector.
Definition at line 104 of file tage_sc_l_8KB.cc.
References TAGE_SC_L_8KB_StatisticalCorrector::SC_8KB_ThreadHistory::globalHist, StaticInst::isDirectCtrl(), StaticInst::isUncondCtrl(), StatisticalCorrector::scHistory, StatisticalCorrector::scHistoryUpdate(), and ArmISA::sh.
Member Data Documentation
ggehl
std::vector<int8_t>* TAGE_SC_L_8KB_StatisticalCorrector::ggehl private
Definition at line 76 of file tage_sc_l_8KB.hh.
Referenced by gPredictions(), gUpdates(), and TAGE_SC_L_8KB_StatisticalCorrector().
gm
std::vector<int> TAGE_SC_L_8KB_StatisticalCorrector::gm private
Definition at line 75 of file tage_sc_l_8KB.hh.
Referenced by gPredictions(), gUpdates(), and TAGE_SC_L_8KB_StatisticalCorrector().
gnb
const unsigned TAGE_SC_L_8KB_StatisticalCorrector::gnb private
Definition at line 73 of file tage_sc_l_8KB.hh.
Referenced by gPredictions(), gUpdates(), and TAGE_SC_L_8KB_StatisticalCorrector().
logGnb
const unsigned TAGE_SC_L_8KB_StatisticalCorrector::logGnb private
Definition at line 74 of file tage_sc_l_8KB.hh.
Referenced by gPredictions(), gUpdates(), and TAGE_SC_L_8KB_StatisticalCorrector().
wg
std::vector<int8_t> TAGE_SC_L_8KB_StatisticalCorrector::wg private
Definition at line 77 of file tage_sc_l_8KB.hh.
Referenced by gPredictions(), gUpdates(), and TAGE_SC_L_8KB_StatisticalCorrector().
The documentation for this class was generated from the following files:
cpu/pred/tage_sc_l_8KB.hh
cpu/pred/tage_sc_l_8KB.cc