gem5: CircleBuf< T > Class Template Reference
CircleBuf< T > Class Template Reference
Circular buffer backed by a vector though a CircularQueue.
#include <circlebuf.hh>
Public Member Functions
CircleBuf (size_t size)
template<class OutputIterator >
void peek (OutputIterator out, size_t len) const
Copy buffer contents without advancing the read pointer.
template<class OutputIterator >
void peek (OutputIterator out, off_t offset, size_t len) const
Copy buffer contents without advancing the read pointer.
template<class OutputIterator >
void read (OutputIterator out, size_t len)
Copy buffer contents and advance the read pointer.
template<class InputIterator >
void write (InputIterator in, size_t len)
Add elements to the end of the ring buffers and advance.
Public Member Functions inherited from CircularQueue< T >
CircularQueue (uint32_t size=0)
void flush ()
Remove all the elements in the queue.
bool isValidIdx (size_t idx) const
Test if the index is in the range of valid elements.
bool isValidIdx (size_t idx, uint32_t round) const
Test if the index is in the range of valid elements.
reference front ()
reference back ()
uint32_t head () const
uint32_t tail () const
size_t capacity () const
uint32_t size () const
uint32_t moduloAdd (uint32_t s1, uint32_t s2) const
uint32_t moduloSub (uint32_t s1, uint32_t s2) const
void pop_front (size_t num_elem=1)
Circularly increase the head pointer.
void pop_back ()
Circularly decrease the tail pointer.
void push_back (typename Base::value_type val)
Pushes an element at the end of the queue.
void advance_tail ()
Increases the tail by one.
void advance_tail (uint32_t len)
Increases the tail by a specified number of steps.
bool empty () const
Is the queue empty?
bool full () const
Is the queue full? A queue is full if the head is the 0^{th} element and the tail is the (size-1)^{th} element, or if the head is the n^{th} element and the tail the (n-1)^{th} element.
iterator begin ()
Iterators.
iterator begin () const
iterator end ()
iterator end () const
iterator getIterator (size_t idx)
Return an iterator to an index in the vector.
Additional Inherited Members
Protected Types inherited from CircularQueue< T >
using Base = std::vector< T >
Protected Member Functions inherited from CircularQueue< T >
void increase (uint32_t &v, size_t delta=1)
void decrease (uint32_t &v)
Static Protected Member Functions inherited from CircularQueue< T >
static uint32_t moduloAdd (uint32_t op1, uint32_t op2, uint32_t size)
General modular addition.
static uint32_t moduloSub (uint32_t op1, uint32_t op2, uint32_t size)
General modular subtraction.
static int32_t sub (uint32_t op1, uint32_t op2, uint32_t size)
Protected Attributes inherited from CircularQueue< T >
const uint32_t _capacity
uint32_t _head
uint32_t _tail
uint32_t _empty
uint32_t _round
Counter for how many times the tail wraps around.
Detailed Description
template<typename T>
class CircleBuf< T >
Circular buffer backed by a vector though a CircularQueue.
The data in the cricular buffer is stored in a standard vector.
Definition at line 59 of file circlebuf.hh.
Constructor & Destructor Documentation
CircleBuf()
template<typename T> CircleBuf< T >::CircleBuf (size_t size) inline explicit
Definition at line 62 of file circlebuf.hh.
Member Function Documentation
peek() [1/2]
template<typename T> template<class OutputIterator > void CircleBuf< T >::peek (OutputIterator out, size_t len) const inline
Copy buffer contents without advancing the read pointer.
Parameters
out Output iterator/pointer
len Number of elements to copy
Definition at line 79 of file circlebuf.hh.
Referenced by Terminal::accept(), arrayParamOut(), CircleBuf< char >::peek(), CircleBuf< char >::read(), and TEST().
peek() [2/2]
template<typename T> template<class OutputIterator > void CircleBuf< T >::peek (OutputIterator out, off_t offset, size_t len) const inline
Copy buffer contents without advancing the read pointer.
Parameters
out Output iterator/pointer
offset Offset into the ring buffer
len Number of elements to copy
Definition at line 91 of file circlebuf.hh.
read()
template<typename T> template<class OutputIterator > void CircleBuf< T >::read (OutputIterator out, size_t len) inline
Copy buffer contents and advance the read pointer.
Parameters
out Output iterator/pointer
len Number of elements to read
Definition at line 105 of file circlebuf.hh.
Referenced by Terminal::readData(), and TEST().
write()
template<typename T> template<class InputIterator > void CircleBuf< T >::write (InputIterator in, size_t len) inline
Add elements to the end of the ring buffers and advance.
Parameters
in Input iterator/pointer
len Number of elements to read
Definition at line 117 of file circlebuf.hh.
Referenced by arrayParamIn(), Terminal::data(), TEST(), and Terminal::writeData().
The documentation for this class was generated from the following file:
base/circlebuf.hh