gem5: Trace::InstRecord Class Reference
Trace::InstRecord Class Reference abstract
#include <insttracer.hh>
Public Member Functions
InstRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual ~InstRecord ()
void setWhen (Tick new_when)
void setMem (Addr a, Addr s, unsigned f)
template<typename T , size_t N>
void setData (std::array< T, N > d)
void setData (uint64_t d)
void setData (uint32_t d)
void setData (uint16_t d)
void setData (uint8_t d)
void setData (int64_t d)
void setData (int32_t d)
void setData (int16_t d)
void setData (int8_t d)
void setData (double d)
void setData (::VecRegContainer< TheISA::VecRegSizeBytes > &d)
void setData (::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > &d)
void setFetchSeq (InstSeqNum seq)
void setCPSeq (InstSeqNum seq)
void setPredicate (bool val)
virtual void dump ()=0
Tick getWhen () const
ThreadContext * getThread () const
StaticInstPtr getStaticInst () const
TheISA::PCState getPCState () const
StaticInstPtr getMacroStaticInst () const
Addr getAddr () const
Addr getSize () const
unsigned getFlags () const
bool getMemValid () const
uint64_t getIntData () const
double getFloatData () const
int getDataStatus () const
InstSeqNum getFetchSeq () const
bool getFetchSeqValid () const
InstSeqNum getCpSeq () const
bool getCpSeqValid () const
Protected Types
enum DataStatus {
DataInvalid = 0, DataInt8 = 1, DataInt16 = 2, DataInt32 = 4,
DataInt64 = 8, DataDouble = 3, DataVec = 5, DataVecPred = 6
}
What size of data was written?
Protected Attributes
Tick when
ThreadContext * thread
StaticInstPtr staticInst
TheISA::PCState pc
StaticInstPtr macroStaticInst
Addr addr
The address that was accessed.
Addr size
The size of the memory request.
unsigned flags
The flags that were assigned to the request.
union {
uint64_t as_int
double as_double
::VecRegContainer< TheISA::VecRegSizeBytes > * as_vec
::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > * as_pred
} data
InstSeqNum fetch_seq
InstSeqNum cp_seq
enum Trace::InstRecord::DataStatus data_status
bool mem_valid
Are the memory fields in the record valid?
bool fetch_seq_valid
Are the fetch sequence number fields valid?
bool cp_seq_valid
Are the commit sequence number fields valid?
bool predicate
is the predicate for execution this inst true or false (not execed)?
Detailed Description
Definition at line 58 of file insttracer.hh.
Constructor & Destructor Documentation
InstRecord()
Trace::InstRecord::InstRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst = NULL) inline
Definition at line 150 of file insttracer.hh.
~InstRecord()
virtual Trace::InstRecord::~InstRecord () inline virtual
Definition at line 160 of file insttracer.hh.
References data, data_status, DataVec, and DataVecPred.
Member Function Documentation
dump()
virtual void Trace::InstRecord::dump () pure virtual
Implemented in Trace::TarmacTracerRecord, Trace::TarmacParserRecord, Trace::TarmacBaseRecord, Trace::InstPBTraceRecord, Trace::NativeTraceRecord, Trace::ExeTracerRecord, and Trace::IntelTraceRecord.
Referenced by BaseSimpleCPU::postExecute(), setPredicate(), and Checker< O3CPUImpl >::verify().
getAddr()
Addr Trace::InstRecord::getAddr () const inline
Definition at line 233 of file insttracer.hh.
References addr.
Referenced by Trace::TarmacTracerRecordV8::addMemEntry(), Trace::TarmacTracerRecord::addMemEntry(), and Trace::InstPBTraceRecord::dump().
getCpSeq()
InstSeqNum Trace::InstRecord::getCpSeq () const inline
Definition at line 245 of file insttracer.hh.
References cp_seq.
getCpSeqValid()
bool Trace::InstRecord::getCpSeqValid () const inline
Definition at line 246 of file insttracer.hh.
References cp_seq_valid.
getDataStatus()
int Trace::InstRecord::getDataStatus () const inline
Definition at line 240 of file insttracer.hh.
References data_status.
getFetchSeq()
InstSeqNum Trace::InstRecord::getFetchSeq () const inline
Definition at line 242 of file insttracer.hh.
References fetch_seq.
getFetchSeqValid()
bool Trace::InstRecord::getFetchSeqValid () const inline
Definition at line 243 of file insttracer.hh.
References fetch_seq_valid.
getFlags()
unsigned Trace::InstRecord::getFlags () const inline
Definition at line 235 of file insttracer.hh.
References flags.
Referenced by Trace::InstPBTraceRecord::dump().
getFloatData()
double Trace::InstRecord::getFloatData () const inline
Definition at line 239 of file insttracer.hh.
References data.
getIntData()
uint64_t Trace::InstRecord::getIntData () const inline
Definition at line 238 of file insttracer.hh.
References data.
Referenced by Trace::TarmacTracerRecordV8::addMemEntry(), and Trace::TarmacTracerRecord::addMemEntry().
getMacroStaticInst()
StaticInstPtr Trace::InstRecord::getMacroStaticInst () const inline
Definition at line 231 of file insttracer.hh.
References macroStaticInst.
Referenced by Trace::ArmNativeTrace::check().
getMemValid()
bool Trace::InstRecord::getMemValid () const inline
Definition at line 236 of file insttracer.hh.
References mem_valid.
Referenced by Trace::TarmacTracerRecordV8::addMemEntry(), Trace::TarmacTracerRecord::addMemEntry(), and Trace::InstPBTraceRecord::dump().
getPCState()
TheISA::PCState Trace::InstRecord::getPCState () const inline
Definition at line 230 of file insttracer.hh.
References pc.
getSize()
Addr Trace::InstRecord::getSize () const inline
Definition at line 234 of file insttracer.hh.
References size.
Referenced by Trace::TarmacTracerRecordV8::addMemEntry(), Trace::TarmacTracerRecord::addMemEntry(), and Trace::InstPBTraceRecord::dump().
getStaticInst()
StaticInstPtr Trace::InstRecord::getStaticInst () const inline
Definition at line 229 of file insttracer.hh.
References staticInst.
Referenced by Trace::X86NativeTrace::check(), and Trace::ArmNativeTrace::check().
getThread()
ThreadContext* Trace::InstRecord::getThread () const inline
Definition at line 228 of file insttracer.hh.
References thread.
Referenced by Trace::SparcNativeTrace::check(), Trace::X86NativeTrace::check(), and Trace::ArmNativeTrace::check().
getWhen()
Tick Trace::InstRecord::getWhen () const inline
Definition at line 227 of file insttracer.hh.
References when.
setCPSeq()
void Trace::InstRecord::setCPSeq (InstSeqNum seq) inline
Definition at line 219 of file insttracer.hh.
setData() [1/12]
template<typename T , size_t N> void Trace::InstRecord::setData (std::array< T, N > d) inline
Definition at line 179 of file insttracer.hh.
References data, data_status, DataInt16, DataInt32, DataInt64, and DataInt8.
Referenced by amoMemAtomic(), X86ISA::getMem(), getMem(), readMemAtomic(), X86ISA::readMemAtomic(), writeMemAtomic(), X86ISA::writeMemAtomic(), writeMemTiming(), and X86ISA::writeMemTiming().
setData() [2/12]
void Trace::InstRecord::setData (uint64_t d) inline
Definition at line 188 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataInt64.
setData() [3/12]
void Trace::InstRecord::setData (uint32_t d) inline
Definition at line 189 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataInt32.
setData() [4/12]
void Trace::InstRecord::setData (uint16_t d) inline
Definition at line 190 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataInt16.
setData() [5/12]
void Trace::InstRecord::setData (uint8_t d) inline
Definition at line 191 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataInt8.
setData() [6/12]
void Trace::InstRecord::setData (int64_t d) inline
Definition at line 193 of file insttracer.hh.
References setData().
Referenced by setData().
setData() [7/12]
void Trace::InstRecord::setData (int32_t d) inline
Definition at line 194 of file insttracer.hh.
References setData().
Referenced by setData().
setData() [8/12]
void Trace::InstRecord::setData (int16_t d) inline
Definition at line 195 of file insttracer.hh.
References setData().
Referenced by setData().
setData() [9/12]
void Trace::InstRecord::setData (int8_t d) inline
Definition at line 196 of file insttracer.hh.
References setData().
Referenced by setData().
setData() [10/12]
void Trace::InstRecord::setData (double d) inline
Definition at line 198 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataDouble.
setData() [11/12]
void Trace::InstRecord::setData (::VecRegContainer< TheISA::VecRegSizeBytes > & d) inline
Definition at line 201 of file insttracer.hh.
References ArmISA::d, data, data_status, and DataVec.
setData() [12/12]
void Trace::InstRecord::setData (::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > & d) inline
Definition at line 208 of file insttracer.hh.
References ArmISA::d, data, data_status, DataVecPred, AlphaISA::VecPredRegHasPackedRepr, and AlphaISA::VecPredRegSizeBits.
setFetchSeq()
void Trace::InstRecord::setFetchSeq (InstSeqNum seq) inline
Definition at line 216 of file insttracer.hh.
setMem()
void Trace::InstRecord::setMem (Addr a, Addr s, unsigned f) inline
Definition at line 172 of file insttracer.hh.
References ArmISA::a, ArmISA::f, and ArmISA::s.
Referenced by AtomicSimpleCPU::amoMem(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), AtomicSimpleCPU::readMem(), AtomicSimpleCPU::writeMem(), and TimingSimpleCPU::writeMem().
setPredicate()
void Trace::InstRecord::setPredicate (bool val) inline
Definition at line 222 of file insttracer.hh.
References dump(), and X86ISA::val.
Referenced by SimpleExecContext::setPredicate(), and BaseDynInst< Impl >::setPredicate().
setWhen()
void Trace::InstRecord::setWhen (Tick new_when) inline
Definition at line 171 of file insttracer.hh.
Member Data Documentation
addr
Addr Trace::InstRecord::addr protected
The address that was accessed.
Definition at line 83 of file insttracer.hh.
Referenced by getAddr(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::print(), Trace::TarmacTracerRecord::TraceMemEntry::print(), Trace::TarmacBaseRecord::TarmacBaseRecord(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::TraceInstEntryV8(), and Trace::TarmacTracerRecordV8::TraceMemEntryV8::TraceMemEntryV8().
as_double
double Trace::InstRecord::as_double
Definition at line 99 of file insttracer.hh.
as_int
uint64_t Trace::InstRecord::as_int
Definition at line 98 of file insttracer.hh.
as_pred
::VecPredRegContainer<TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr>* Trace::InstRecord::as_pred
Definition at line 102 of file insttracer.hh.
as_vec
::VecRegContainer<TheISA::VecRegSizeBytes>* Trace::InstRecord::as_vec
Definition at line 100 of file insttracer.hh.
cp_seq
InstSeqNum Trace::InstRecord::cp_seq protected
Definition at line 115 of file insttracer.hh.
Referenced by getCpSeq().
data
union { ... } Trace::InstRecord::data
Referenced by Trace::TarmacParserRecord::advanceTrace(), getFloatData(), getIntData(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::print(), Trace::TarmacTracerRecord::TraceMemEntry::print(), setData(), and ~InstRecord().
fetch_seq
InstSeqNum Trace::InstRecord::fetch_seq protected
Definition at line 109 of file insttracer.hh.
Referenced by getFetchSeq().
flags
unsigned Trace::InstRecord::flags protected
The flags that were assigned to the request.
Definition at line 85 of file insttracer.hh.
Referenced by getFlags().
macroStaticInst
StaticInstPtr Trace::InstRecord::macroStaticInst protected
Definition at line 70 of file insttracer.hh.
Referenced by Trace::InstPBTraceRecord::dump(), Trace::TarmacTracerRecord::dump(), Trace::IntelTrace::getInstRecord(), Trace::ExeTracer::getInstRecord(), Trace::NativeTrace::getInstRecord(), Trace::TarmacParser::getInstRecord(), getMacroStaticInst(), and Trace::InstTracer::~InstTracer().
mem_valid
bool Trace::InstRecord::mem_valid protected
Are the memory fields in the record valid?
Definition at line 134 of file insttracer.hh.
Referenced by getMemValid().
pc
TheISA::PCState Trace::InstRecord::pc protected
Definition at line 69 of file insttracer.hh.
Referenced by Trace::TarmacParser::advanceTraceToStartPc(), Trace::InstPBTraceRecord::dump(), Trace::TarmacParserRecord::dump(), Trace::TarmacTracerRecord::dump(), getPCState(), Trace::TarmacBaseRecord::TarmacBaseRecord(), and Trace::InstTracer::~InstTracer().
predicate
bool Trace::InstRecord::predicate protected
is the predicate for execution this inst true or false (not execed)?
Definition at line 147 of file insttracer.hh.
Referenced by Trace::TarmacTracerRecordV8::addInstEntry(), Trace::TarmacTracerRecord::addInstEntry(), and Trace::TarmacBaseRecord::TarmacBaseRecord().
size
Addr Trace::InstRecord::size protected
The size of the memory request.
Definition at line 84 of file insttracer.hh.
Referenced by getSize(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::print(), and Trace::TarmacTracerRecord::TraceMemEntry::print().
staticInst
StaticInstPtr Trace::InstRecord::staticInst protected
Definition at line 68 of file insttracer.hh.
Referenced by Trace::TarmacTracerRecordV8::addRegEntry(), Trace::TarmacTracerRecord::addRegEntry(), Trace::InstPBTraceRecord::dump(), Trace::TarmacParserRecord::dump(), Trace::TarmacTracerRecord::dump(), getStaticInst(), Trace::TarmacBaseRecord::TarmacBaseRecord(), and Trace::InstTracer::~InstTracer().
thread
ThreadContext* Trace::InstRecord::thread protected
Definition at line 65 of file insttracer.hh.
Referenced by Trace::InstPBTraceRecord::dump(), Trace::TarmacParserRecord::dump(), Trace::TarmacTracerRecord::dump(), getThread(), Trace::TarmacParserRecord::readMemNoEffect(), Trace::TarmacBaseRecord::TarmacBaseRecord(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::TraceInstEntryV8(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::TraceMemEntryV8(), Trace::TarmacTracerRecord::TraceRegEntry::updateCC(), Trace::TarmacTracerRecord::TraceRegEntry::updateFloat(), Trace::TarmacTracerRecord::TraceRegEntry::updateInt(), Trace::TarmacTracerRecord::TraceRegEntry::updateMisc(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updatePred(), and Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateVec().
when
Tick Trace::InstRecord::when protected
Definition at line 61 of file insttracer.hh.
Referenced by getWhen(), and Trace::InstTracer::~InstTracer().
The documentation for this class was generated from the following file:
sim/insttracer.hh