gem5: sc_core::sc_inout< sc_dt::sc_bigint< W > > Class Reference
sc_core::sc_inout< sc_dt::sc_bigint< W > > Class Reference
#include <scx_signal_signed.h>
Public Types
typedef sc_dt::sc_bigint< W > data_type
typedef sc_signal_inout_if< sc_dt::sc_bigint< W > > if_type
typedef sc_port< if_type, 1, SC_ONE_OR_MORE_BOUND > base_type
typedef sc_inout< sc_dt::sc_bigint< W > > this_type
typedef if_type inout_if_type
typedef base_type inout_port_type
Public Member Functions
void bind (const inout_if_type &interface_)
void operator() (const inout_if_type &interface_)
void bind (inout_port_type &parent_)
void operator() (inout_port_type &parent_)
sc_inout ()
sc_inout (const char *name_)
sc_inout (inout_if_type &interface_)
sc_inout (const char *name_, inout_if_type &interface_)
sc_inout (inout_port_type &parent_)
sc_inout (const char *name_, inout_port_type &parent_)
sc_inout (this_type &parent_)
sc_inout (const char *name_, this_type &parent_)
virtual ~sc_inout ()
sc_dt::sc_signed_bitref_r operator[] (int i) const
sc_dt::sc_signed_bitref_r bit (int i) const
sc_signed_sigref & operator[] (int i)
sc_signed_sigref & bit (int i)
sc_dt::sc_signed_subref_r operator() (int left, int right) const
sc_dt::sc_signed_subref_r range (int left, int right) const
sc_signed_sigref & operator() (int left, int right)
sc_signed_sigref & range (int left, int right)
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_dt::sc_bigint< W > & read () const
operator const sc_dt::sc_bigint< W > & () const
bool event () const
sc_event_finder & value_changed () const
bool and_reduce () const
bool nand_reduce () const
bool nor_reduce () const
bool or_reduce () const
bool xnor_reduce () const
bool xor_reduce () const
virtual void end_of_elaboration ()
virtual const char * kind () const
void initialize (const sc_dt::sc_bigint< W > &value_)
void add_trace (sc_trace_file *tf_, const std::string &name_) const
virtual int concat_length (bool *xz_present_p) const
virtual sc_dt::uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_dt::sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_dt::sc_digit *dst_p, int low_i) const
virtual void concat_set (sc_dt::int64 src, int low_i)
virtual void concat_set (const sc_dt::sc_signed &src, int low_i)
virtual void concat_set (const sc_dt::sc_unsigned &src, int low_i)
virtual void concat_set (sc_dt::uint64 src, int low_i)
void operator= (const this_type &new_val)
void operator= (const char *new_val)
void operator= (sc_dt::uint64 new_val)
void operator= (sc_dt::int64 new_val)
void operator= (int new_val)
void operator= (long new_val)
void operator= (short new_val)
void operator= (unsigned int new_val)
void operator= (unsigned long new_val)
void operator= (unsigned short new_val)
template<typename T >
void operator= (const sc_dt::sc_generic_base< T > &new_val)
void operator= (const sc_dt::sc_signed &new_val)
void operator= (const sc_dt::sc_unsigned &new_val)
void operator= (const sc_dt::sc_bv_base &new_val)
void operator= (const sc_dt::sc_lv_base &new_val)
void write (const sc_in< sc_dt::sc_bigint< W > > &new_val)
void write (const sc_inout< sc_dt::sc_bigint< W > > &new_val)
void write (const sc_dt::sc_bigint< W > &new_val)
Public Member Functions inherited from sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_inout_if< sc_dt::sc_bigint< W > > &interface)
sc_port (const char *name, const sc_signal_inout_if< sc_dt::sc_bigint< W > > &interface)
sc_port (sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > > &parent)
sc_port (sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, N, P > &parent)
sc_port (const char *name, sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, N, P > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >
void operator() (sc_signal_inout_if< sc_dt::sc_bigint< W > > &i)
void operator() (sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > > &p)
virtual void bind (sc_signal_inout_if< sc_dt::sc_bigint< W > > &i)
virtual void bind (sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > > &p)
sc_signal_inout_if< sc_dt::sc_bigint< W > > * operator-> ()
const sc_signal_inout_if< sc_dt::sc_bigint< W > > * operator-> () const
sc_signal_inout_if< sc_dt::sc_bigint< W > > * operator[] (int n)
const sc_signal_inout_if< sc_dt::sc_bigint< W > > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
virtual int vbind (sc_interface &interface_)
virtual int vbind (sc_port_base &parent_)
void remove_traces () const
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
sc_dt::sc_bigint< W > * m_init_val_p
sc_trace_params_vec * m_traces
Private Member Functions
sc_inout (const sc_inout< sc_dt::sc_bigint< W > > &)
Detailed Description
Definition at line 1198 of file scx_signal_signed.h.
Member Typedef Documentation
base_type
typedef sc_port<if_type,1,SC_ONE_OR_MORE_BOUND> sc_core::sc_inout< sc_dt::sc_bigint< W > >::base_type
Definition at line 1209 of file scx_signal_signed.h.
data_type
typedef sc_dt::sc_bigint<W> sc_core::sc_inout< sc_dt::sc_bigint< W > >::data_type
Definition at line 1207 of file scx_signal_signed.h.
if_type
typedef sc_signal_inout_if<sc_dt::sc_bigint<W> > sc_core::sc_inout< sc_dt::sc_bigint< W > >::if_type
Definition at line 1208 of file scx_signal_signed.h.
inout_if_type
typedef if_type sc_core::sc_inout< sc_dt::sc_bigint< W > >::inout_if_type
Definition at line 1212 of file scx_signal_signed.h.
inout_port_type
typedef base_type sc_core::sc_inout< sc_dt::sc_bigint< W > >::inout_port_type
Definition at line 1213 of file scx_signal_signed.h.
this_type
typedef sc_inout<sc_dt::sc_bigint<W> > sc_core::sc_inout< sc_dt::sc_bigint< W > >::this_type
Definition at line 1210 of file scx_signal_signed.h.
Constructor & Destructor Documentation
sc_inout() [1/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout () inline
Definition at line 1249 of file scx_signal_signed.h.
sc_inout() [2/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (const char * name_) inline explicit
Definition at line 1253 of file scx_signal_signed.h.
sc_inout() [3/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (inout_if_type & interface_) inline explicit
Definition at line 1257 of file scx_signal_signed.h.
sc_inout() [4/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (const char * name_, inout_if_type & interface_) inline
Definition at line 1261 of file scx_signal_signed.h.
sc_inout() [5/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (inout_port_type & parent_) inline explicit
Definition at line 1265 of file scx_signal_signed.h.
sc_inout() [6/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (const char * name_, inout_port_type & parent_) inline
Definition at line 1269 of file scx_signal_signed.h.
sc_inout() [7/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (this_type & parent_) inline
Definition at line 1273 of file scx_signal_signed.h.
sc_inout() [8/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (const char * name_, this_type & parent_) inline
Definition at line 1277 of file scx_signal_signed.h.
~sc_inout()
virtual sc_core::sc_inout< sc_dt::sc_bigint< W > >::~sc_inout () inline virtual
Definition at line 1284 of file scx_signal_signed.h.
sc_inout() [9/9]
sc_core::sc_inout< sc_dt::sc_bigint< W > >::sc_inout (const sc_inout< sc_dt::sc_bigint< W > > &) private
Member Function Documentation
add_trace()
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::add_trace (sc_trace_file * tf_, const std::string & name_) const inline
Definition at line 1403 of file scx_signal_signed.h.
and_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::and_reduce () const inline
Definition at line 1349 of file scx_signal_signed.h.
bind() [1/2]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::bind (const inout_if_type & interface_) inline
Definition at line 1219 of file scx_signal_signed.h.
References sc_core::sc_port_base::bind().
bind() [2/2]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::bind (inout_port_type & parent_) inline
Definition at line 1223 of file scx_signal_signed.h.
References sc_core::sc_port_base::bind().
bit() [1/2]
sc_dt::sc_signed_bitref_r sc_core::sc_inout< sc_dt::sc_bigint< W > >::bit (int i) const inline
Definition at line 1293 of file scx_signal_signed.h.
References ArmISA::i.
bit() [2/2]
sc_signed_sigref& sc_core::sc_inout< sc_dt::sc_bigint< W > >::bit (int i) inline
Definition at line 1297 of file scx_signal_signed.h.
concat_get_ctrl()
virtual bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_get_ctrl (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1420 of file scx_signal_signed.h.
concat_get_data()
virtual bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_get_data (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1422 of file scx_signal_signed.h.
concat_get_uint64()
virtual sc_dt::uint64 sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1418 of file scx_signal_signed.h.
concat_length()
virtual int sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1416 of file scx_signal_signed.h.
concat_set() [1/4]
virtual void sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_set (sc_dt::int64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1424 of file scx_signal_signed.h.
concat_set() [2/4]
virtual void sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_set (const sc_dt::sc_signed & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1430 of file scx_signal_signed.h.
concat_set() [3/4]
virtual void sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_set (const sc_dt::sc_unsigned & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1432 of file scx_signal_signed.h.
concat_set() [4/4]
virtual void sc_core::sc_inout< sc_dt::sc_bigint< W > >::concat_set (sc_dt::uint64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1434 of file scx_signal_signed.h.
default_event()
const sc_event& sc_core::sc_inout< sc_dt::sc_bigint< W > >::default_event () const inline
Definition at line 1313 of file scx_signal_signed.h.
end_of_elaboration()
virtual void sc_core::sc_inout< sc_dt::sc_bigint< W > >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Definition at line 1367 of file scx_signal_signed.h.
References ArmISA::i, sc_core::sc_trace_params::name, MipsISA::p, sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::read(), sc_core::sc_trace(), and sc_core::sc_trace_params::tf.
event()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::event () const inline
Definition at line 1333 of file scx_signal_signed.h.
initialize()
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::initialize (const sc_dt::sc_bigint< W > & value_) inline
Definition at line 1388 of file scx_signal_signed.h.
References sc_core::sc_signal_write_if< T >::write().
kind()
virtual const char* sc_core::sc_inout< sc_dt::sc_bigint< W > >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >.
Definition at line 1383 of file scx_signal_signed.h.
nand_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::nand_reduce () const inline
Definition at line 1351 of file scx_signal_signed.h.
nor_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::nor_reduce () const inline
Definition at line 1353 of file scx_signal_signed.h.
operator const sc_dt::sc_bigint< W > &()
sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator const sc_dt::sc_bigint< W > & () const inline
Definition at line 1328 of file scx_signal_signed.h.
operator()() [1/4]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator() (const inout_if_type & interface_) inline
Definition at line 1221 of file scx_signal_signed.h.
References sc_core::sc_port_base::bind().
operator()() [2/4]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator() (inout_port_type & parent_) inline
Definition at line 1225 of file scx_signal_signed.h.
References sc_core::sc_port_base::bind().
operator()() [3/4]
sc_dt::sc_signed_subref_r sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator() (int left, int right) const inline
Definition at line 1299 of file scx_signal_signed.h.
operator()() [4/4]
sc_signed_sigref& sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator() (int left, int right) inline
Definition at line 1303 of file scx_signal_signed.h.
operator=() [1/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const this_type & new_val) inline
Definition at line 1439 of file scx_signal_signed.h.
References read().
operator=() [2/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const char * new_val) inline
Definition at line 1441 of file scx_signal_signed.h.
References PowerISA::aa.
operator=() [3/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (sc_dt::uint64 new_val) inline
Definition at line 1443 of file scx_signal_signed.h.
operator=() [4/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (sc_dt::int64 new_val) inline
Definition at line 1445 of file scx_signal_signed.h.
operator=() [5/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (int new_val) inline
Definition at line 1447 of file scx_signal_signed.h.
operator=() [6/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (long new_val) inline
Definition at line 1449 of file scx_signal_signed.h.
operator=() [7/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (short new_val) inline
Definition at line 1451 of file scx_signal_signed.h.
operator=() [8/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (unsigned int new_val) inline
Definition at line 1453 of file scx_signal_signed.h.
operator=() [9/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (unsigned long new_val) inline
Definition at line 1455 of file scx_signal_signed.h.
operator=() [10/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (unsigned short new_val) inline
Definition at line 1457 of file scx_signal_signed.h.
operator=() [11/15]
template<typename T > void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
Definition at line 1460 of file scx_signal_signed.h.
operator=() [12/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const sc_dt::sc_signed & new_val) inline
Definition at line 1466 of file scx_signal_signed.h.
operator=() [13/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const sc_dt::sc_unsigned & new_val) inline
Definition at line 1468 of file scx_signal_signed.h.
operator=() [14/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const sc_dt::sc_bv_base & new_val) inline
Definition at line 1470 of file scx_signal_signed.h.
operator=() [15/15]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator= (const sc_dt::sc_lv_base & new_val) inline
Definition at line 1472 of file scx_signal_signed.h.
operator[]() [1/2]
sc_dt::sc_signed_bitref_r sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator[] (int i) const inline
Definition at line 1291 of file scx_signal_signed.h.
References ArmISA::i.
operator[]() [2/2]
sc_signed_sigref& sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator[] (int i) inline
Definition at line 1295 of file scx_signal_signed.h.
or_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::or_reduce () const inline
Definition at line 1355 of file scx_signal_signed.h.
range() [1/2]
sc_dt::sc_signed_subref_r sc_core::sc_inout< sc_dt::sc_bigint< W > >::range (int left, int right) const inline
Definition at line 1301 of file scx_signal_signed.h.
range() [2/2]
sc_signed_sigref& sc_core::sc_inout< sc_dt::sc_bigint< W > >::range (int left, int right) inline
Definition at line 1305 of file scx_signal_signed.h.
read()
const sc_dt::sc_bigint<W>& sc_core::sc_inout< sc_dt::sc_bigint< W > >::read () const inline
Definition at line 1325 of file scx_signal_signed.h.
Referenced by operator=().
remove_traces()
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::remove_traces () const inline protected
Definition at line 1483 of file scx_signal_signed.h.
References ArmISA::i.
value_changed()
sc_event_finder& sc_core::sc_inout< sc_dt::sc_bigint< W > >::value_changed () const inline
Definition at line 1339 of file scx_signal_signed.h.
value_changed_event()
const sc_event& sc_core::sc_inout< sc_dt::sc_bigint< W > >::value_changed_event () const inline
Definition at line 1319 of file scx_signal_signed.h.
vbind() [1/2]
virtual int sc_core::sc_inout< sc_dt::sc_bigint< W > >::vbind (sc_interface & interface_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 1230 of file scx_signal_signed.h.
References sc_core::sc_port_b< IF >::vbind().
vbind() [2/2]
virtual int sc_core::sc_inout< sc_dt::sc_bigint< W > >::vbind (sc_port_base & parent_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 1234 of file scx_signal_signed.h.
References sc_core::sc_port_base::bind().
write() [1/3]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::write (const sc_in< sc_dt::sc_bigint< W > > & new_val) inline
Definition at line 1475 of file scx_signal_signed.h.
write() [2/3]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::write (const sc_inout< sc_dt::sc_bigint< W > > & new_val) inline
Definition at line 1477 of file scx_signal_signed.h.
write() [3/3]
void sc_core::sc_inout< sc_dt::sc_bigint< W > >::write (const sc_dt::sc_bigint< W > & new_val) inline
Definition at line 1479 of file scx_signal_signed.h.
xnor_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::xnor_reduce () const inline
Definition at line 1357 of file scx_signal_signed.h.
xor_reduce()
bool sc_core::sc_inout< sc_dt::sc_bigint< W > >::xor_reduce () const inline
Definition at line 1359 of file scx_signal_signed.h.
Member Data Documentation
m_init_val_p
sc_dt::sc_bigint<W>* sc_core::sc_inout< sc_dt::sc_bigint< W > >::m_init_val_p protected
Definition at line 1494 of file scx_signal_signed.h.
m_traces
sc_trace_params_vec* sc_core::sc_inout< sc_dt::sc_bigint< W > >::m_traces mutable protected
Definition at line 1495 of file scx_signal_signed.h.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_signed.h