gem5: Time Class Reference
Time Class Reference
#include <time.hh>
Public Member Functions
Time ()
Time (double sec)
Time (const Time &val)
Time (uint64_t sec, uint64_t nsec)
Time (const timeval &tv)
Time (const timespec &ts)
time_t sec () const
Accessors for getting and setting the current clock.
long msec () const
long usec () const
long nsec () const
void sec (time_t sec)
void msec (long msec)
void usec (long usec)
void nsec (long nsec)
void clear ()
Clear the time.
void setTimer ()
Use this to set time for the purposes of time measurement (use a monotonic clock if it is available.
void setWallclock ()
Use this to set the time to the actual current time.
void set (time_t _sec, long _nsec)
Set the current time.
void setTick (Tick ticks)
Set the current time from a value measured in Ticks.
Tick getTick () const
Get the current time from a value measured in Ticks.
const Time & operator= (const Time &other)
const Time & operator= (double new_time)
const Time & operator= (const timeval &tv)
const Time & operator= (const timespec &ts)
operator double () const
Get the time in floating point seconds.
operator timespec () const
operators for time conversion
operator timeval () const
const Time & operator+= (const Time &other)
const Time & operator-= (const Time &other)
std::string date (const std::string &format="") const
std::string time () const
void serialize (const std::string &base, CheckpointOut &cp) const
void unserialize (const std::string &base, CheckpointIn &cp)
Static Public Attributes
static const long NSEC_PER_SEC = 1000 * 1000 * 1000
static const long NSEC_PER_MSEC = 1000 * 1000
static const long NSEC_PER_USEC = 1000
Protected Member Functions
void _set (bool monotonic)
Internal time set function.
Protected Attributes
timespec _time
Detailed Description
Definition at line 48 of file time.hh.
Constructor & Destructor Documentation
Time() [1/6]
Time::Time () inline explicit
Definition at line 64 of file time.hh.
References clear().
Time() [2/6]
Time::Time (double sec) inline explicit
Definition at line 65 of file time.hh.
References operator=().
Time() [3/6]
Time::Time (const Time & val) inline
Definition at line 66 of file time.hh.
Time() [4/6]
Time::Time (uint64_t sec, uint64_t nsec) inline
Definition at line 67 of file time.hh.
References nsec(), and sec().
Time() [5/6]
Time::Time (const timeval & tv) inline
Definition at line 68 of file time.hh.
References operator=().
Time() [6/6]
Time::Time (const timespec & ts) inline
Definition at line 69 of file time.hh.
References operator=().
Member Function Documentation
_set()
void Time::_set (bool monotonic) protected
Internal time set function.
Definition at line 46 of file time.cc.
Referenced by setTimer(), and setWallclock().
clear()
void Time::clear () inline
Clear the time.
Definition at line 87 of file time.hh.
Referenced by Time().
date()
string Time::date (const std::string & format = "") const
Definition at line 74 of file time.cc.
Referenced by operator-=(), and operator<<().
getTick()
Tick Time::getTick () const
Get the current time from a value measured in Ticks.
Returns
Time value measured in Ticks.
Definition at line 67 of file time.cc.
References SimClock::Frequency, and SimClock::Float::ns.
Referenced by set(), and Root::timeSyncPeriod().
msec() [1/2]
long Time::msec () const inline
Definition at line 75 of file time.hh.
References NSEC_PER_MSEC.
msec() [2/2]
void Time::msec (long msec) inline
Definition at line 80 of file time.hh.
References NSEC_PER_MSEC.
nsec() [1/2]
long Time::nsec () const inline
Definition at line 77 of file time.hh.
Referenced by operator double(), operator!=(), operator+=(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), set(), and Time().
nsec() [2/2]
void Time::nsec (long nsec) inline
Definition at line 82 of file time.hh.
References nsec().
Referenced by nsec().
operator double()
Time::operator double () const inline
Get the time in floating point seconds.
Definition at line 153 of file time.hh.
References ArmISA::e, nsec(), and sec().
operator timespec()
Time::operator timespec () const inline
operators for time conversion
Definition at line 161 of file time.hh.
References _time.
operator timeval()
Time::operator timeval () const inline
Definition at line 162 of file time.hh.
References sec(), and usec().
operator+=()
const Time& Time::operator+= (const Time & other) inline
Definition at line 171 of file time.hh.
References nsec(), NSEC_PER_SEC, and sec().
operator-=()
const Time& Time::operator-= (const Time & other) inline
Definition at line 185 of file time.hh.
References X86ISA::base, date(), ArmISA::format, nsec(), NSEC_PER_SEC, sec(), serialize(), sleep(), time(), and unserialize().
operator=() [1/4]
const Time& Time::operator= (const Time & other) inline
Definition at line 118 of file time.hh.
References nsec(), and sec().
Referenced by Time().
operator=() [2/4]
const Time& Time::operator= (double new_time) inline
Definition at line 126 of file time.hh.
References nsec(), and sec().
operator=() [3/4]
const Time& Time::operator= (const timeval & tv) inline
Definition at line 135 of file time.hh.
References nsec(), and sec().
operator=() [4/4]
const Time& Time::operator= (const timespec & ts) inline
Definition at line 143 of file time.hh.
References nsec(), and sec().
sec() [1/2]
time_t Time::sec () const inline
Accessors for getting and setting the current clock.
Definition at line 74 of file time.hh.
Referenced by operator double(), operator timeval(), operator!=(), operator+=(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), set(), and Time().
sec() [2/2]
void Time::sec (time_t sec) inline
Definition at line 79 of file time.hh.
References sec().
Referenced by sec().
serialize()
void Time::serialize (const std::string & base, CheckpointOut & cp) const
Definition at line 125 of file time.cc.
References paramOut().
Referenced by operator-=().
set()
void Time::set (time_t _sec, long _nsec) inline
Set the current time.
Definition at line 103 of file time.hh.
References getTick(), nsec(), sec(), and setTick().
setTick()
void Time::setTick (Tick ticks)
Set the current time from a value measured in Ticks.
Parameters
ticks Number of ticks to convert into a time.
Definition at line 58 of file time.cc.
References SimClock::Frequency, and SimClock::Float::GHz.
Referenced by Root::Root(), and set().
setTimer()
void Time::setTimer () inline
Use this to set time for the purposes of time measurement (use a monotonic clock if it is available.
Definition at line 93 of file time.hh.
References _set().
Referenced by Stats::SimTicksReset::process(), Root::Root(), Stats::statElapsedTime(), and Root::timeSync().
setWallclock()
void Time::setWallclock () inline
Use this to set the time to the actual current time.
Definition at line 98 of file time.hh.
References _set().
time()
string Time::time () const
Definition at line 95 of file time.cc.
Referenced by operator+(), operator-(), and operator-=().
unserialize()
void Time::unserialize (const std::string & base, CheckpointIn & cp)
Definition at line 132 of file time.cc.
References paramIn().
Referenced by operator-=().
usec() [1/2]
long Time::usec () const inline
Definition at line 76 of file time.hh.
References NSEC_PER_USEC.
Referenced by operator timeval().
usec() [2/2]
void Time::usec (long usec) inline
Definition at line 81 of file time.hh.
References NSEC_PER_USEC.
Member Data Documentation
_time
timespec Time::_time protected
Definition at line 51 of file time.hh.
Referenced by operator timespec().
NSEC_PER_MSEC
const long Time::NSEC_PER_MSEC = 1000 * 1000 static
Definition at line 60 of file time.hh.
Referenced by msec().
NSEC_PER_SEC
const long Time::NSEC_PER_SEC = 1000 * 1000 * 1000 static
Definition at line 59 of file time.hh.
Referenced by operator+=(), and operator-=().
NSEC_PER_USEC
const long Time::NSEC_PER_USEC = 1000 static
Definition at line 61 of file time.hh.
Referenced by usec().
The documentation for this class was generated from the following files:
base/time.hh
base/time.cc