gem5: GarnetSyntheticTraffic Class Reference
GarnetSyntheticTraffic Class Reference
#include <GarnetSyntheticTraffic.hh>
Classes
class CpuPort
class GarnetSyntheticTrafficSenderState
Public Types
typedef GarnetSyntheticTrafficParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
GarnetSyntheticTraffic (const Params *p)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void tick ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void completeRequest (PacketPtr pkt)
void generatePkt ()
void sendPkt (PacketPtr pkt)
void initTrafficType ()
void doRetry ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
EventFunctionWrapper tickEvent
CpuPort cachePort
PacketPtr retryPkt
unsigned size
int id
std::map< std::string, TrafficType > trafficStringToEnum
unsigned blockSizeBits
Tick noResponseCycles
int numDestinations
Tick simCycles
int numPacketsMax
int numPacketsSent
int singleSender
int singleDest
std::string trafficType
TrafficType traffic
double injRate
int injVnet
int precision
const Cycles responseLimit
MasterID masterId
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class MemCompleteEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 56 of file GarnetSyntheticTraffic.hh.
Member Typedef Documentation
Params
typedef GarnetSyntheticTrafficParams GarnetSyntheticTraffic::Params
Definition at line 59 of file GarnetSyntheticTraffic.hh.
Constructor & Destructor Documentation
GarnetSyntheticTraffic()
GarnetSyntheticTraffic::GarnetSyntheticTraffic (const Params * p)
Definition at line 76 of file GarnetSyntheticTraffic.cc.
References blockSizeBits, cachePort, EventBase::CPU_Tick_Pri, DPRINTF, fatal, initTrafficType(), injRate, injVnet, masterId, SimObject::name(), noResponseCycles, numDestinations, numPacketsMax, numPacketsSent, MipsISA::p, precision, responseLimit, retryPkt, EventManager::schedule(), simCycles, singleDest, singleSender, size, TESTER_NETWORK, tick(), tickEvent, traffic, trafficStringToEnum, and trafficType.
Referenced by printAddr().
Member Function Documentation
completeRequest()
void GarnetSyntheticTraffic::completeRequest (PacketPtr pkt) protected
Definition at line 129 of file GarnetSyntheticTraffic.cc.
References DPRINTF, Packet::isResponse(), Packet::isWrite(), noResponseCycles, and Packet::req.
doRetry()
void GarnetSyntheticTraffic::doRetry () protected
Definition at line 339 of file GarnetSyntheticTraffic.cc.
References cachePort, retryPkt, and MasterPort::sendTimingReq().
generatePkt()
void GarnetSyntheticTraffic::generatePkt () protected
Definition at line 185 of file GarnetSyntheticTraffic.cc.
References BIT_COMPLEMENT_, BIT_REVERSE_, BIT_ROTATION_, blockSizeBits, X86ISA::destination, DPRINTF, fatal, ArmISA::i, id, injVnet, Request::INST_FETCH, masterId, NEIGHBOR_, numDestinations, Random::random(), random_mt, MemCmd::ReadReq, sc_dt::reverse(), sendPkt(), Flags< T >::set(), SHUFFLE_, singleDest, TORNADO_, traffic, TRANSPOSE_, UNIFORM_RANDOM_, and MemCmd::WriteReq.
Referenced by tick().
getPort()
Port & GarnetSyntheticTraffic::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 113 of file GarnetSyntheticTraffic.cc.
References cachePort, and SimObject::getPort().
init()
void GarnetSyntheticTraffic::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 122 of file GarnetSyntheticTraffic.cc.
References numPacketsSent.
initTrafficType()
void GarnetSyntheticTraffic::initTrafficType () protected
Definition at line 326 of file GarnetSyntheticTraffic.cc.
References BIT_COMPLEMENT_, BIT_REVERSE_, BIT_ROTATION_, NEIGHBOR_, SHUFFLE_, TORNADO_, trafficStringToEnum, TRANSPOSE_, and UNIFORM_RANDOM_.
Referenced by GarnetSyntheticTraffic().
printAddr()
void GarnetSyntheticTraffic::printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Definition at line 347 of file GarnetSyntheticTraffic.cc.
References cachePort, GarnetSyntheticTraffic(), and MasterPort::printAddr().
sendPkt()
void GarnetSyntheticTraffic::sendPkt (PacketPtr pkt) protected
Definition at line 68 of file GarnetSyntheticTraffic.cc.
Referenced by generatePkt().
tick()
void GarnetSyntheticTraffic::tick ()
Definition at line 143 of file GarnetSyntheticTraffic.cc.
References Clocked::clockEdge(), curTick(), exitSimLoop(), fatal, generatePkt(), injRate, SimObject::name(), noResponseCycles, numPacketsMax, numPacketsSent, precision, Random::random(), random_mt, responseLimit, EventManager::schedule(), Event::scheduled(), simCycles, singleSender, and tickEvent.
Referenced by GarnetSyntheticTraffic().
Friends And Related Function Documentation
MemCompleteEvent
friend class MemCompleteEvent friend
Definition at line 145 of file GarnetSyntheticTraffic.hh.
Member Data Documentation
blockSizeBits
unsigned GarnetSyntheticTraffic::blockSizeBits protected
Definition at line 116 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
cachePort
CpuPort GarnetSyntheticTraffic::cachePort protected
Definition at line 96 of file GarnetSyntheticTraffic.hh.
Referenced by doRetry(), GarnetSyntheticTraffic(), getPort(), and printAddr().
id
int GarnetSyntheticTraffic::id protected
Definition at line 112 of file GarnetSyntheticTraffic.hh.
Referenced by generatePkt().
injRate
double GarnetSyntheticTraffic::injRate protected
Definition at line 129 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
injVnet
int GarnetSyntheticTraffic::injVnet protected
Definition at line 130 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
masterId
MasterID GarnetSyntheticTraffic::masterId protected
Definition at line 135 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
noResponseCycles
Tick GarnetSyntheticTraffic::noResponseCycles protected
Definition at line 118 of file GarnetSyntheticTraffic.hh.
Referenced by completeRequest(), GarnetSyntheticTraffic(), and tick().
numDestinations
int GarnetSyntheticTraffic::numDestinations protected
Definition at line 120 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
numPacketsMax
int GarnetSyntheticTraffic::numPacketsMax protected
Definition at line 122 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
numPacketsSent
int GarnetSyntheticTraffic::numPacketsSent protected
Definition at line 123 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), init(), and tick().
precision
int GarnetSyntheticTraffic::precision protected
Definition at line 131 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
responseLimit
const Cycles GarnetSyntheticTraffic::responseLimit protected
Definition at line 133 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
retryPkt
PacketPtr GarnetSyntheticTraffic::retryPkt protected
Definition at line 110 of file GarnetSyntheticTraffic.hh.
Referenced by doRetry(), and GarnetSyntheticTraffic().
simCycles
Tick GarnetSyntheticTraffic::simCycles protected
Definition at line 121 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
singleDest
int GarnetSyntheticTraffic::singleDest protected
Definition at line 125 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
singleSender
int GarnetSyntheticTraffic::singleSender protected
Definition at line 124 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
size
unsigned GarnetSyntheticTraffic::size protected
Definition at line 111 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic().
tickEvent
EventFunctionWrapper GarnetSyntheticTraffic::tickEvent protected
Definition at line 77 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and tick().
traffic
TrafficType GarnetSyntheticTraffic::traffic protected
Definition at line 128 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and generatePkt().
trafficStringToEnum
std::map<std::string, TrafficType> GarnetSyntheticTraffic::trafficStringToEnum protected
Definition at line 114 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic(), and initTrafficType().
trafficType
std::string GarnetSyntheticTraffic::trafficType protected
Definition at line 127 of file GarnetSyntheticTraffic.hh.
Referenced by GarnetSyntheticTraffic().
The documentation for this class was generated from the following files:
cpu/testers/garnet_synthetic_traffic/GarnetSyntheticTraffic.hh
cpu/testers/garnet_synthetic_traffic/GarnetSyntheticTraffic.cc