gem5: CallbackQueue Class Reference
CallbackQueue Class Reference
#include <callback.hh>
Public Member Functions
~CallbackQueue ()
std::string name () const
void add (Callback *callback)
Add a callback to the end of the queue.
template<class T , void(T::*)() F>
void add (T *obj)
template<class T , void(T::*)() F>
void add (T &obj)
bool empty () const
Find out if there are any callbacks in the queue.
void process ()
process all callbacks
void clear ()
clear the callback queue
Protected Types
typedef std::list< Callback * > queue
Simple typedef for the data structure that stores all of the callbacks.
Protected Attributes
queue callbacks
List of all callbacks.
Detailed Description
Definition at line 84 of file callback.hh.
Member Typedef Documentation
queue
typedef std::list<Callback *> CallbackQueue::queue protected
Simple typedef for the data structure that stores all of the callbacks.
Definition at line 91 of file callback.hh.
Constructor & Destructor Documentation
~CallbackQueue()
CallbackQueue::~CallbackQueue ()
Definition at line 33 of file callback.cc.
References callbacks, and ArmISA::i.
Member Function Documentation
add() [1/3]
void CallbackQueue::add (Callback * callback) inline
Add a callback to the end of the queue.
Parameters
callback the callback to be added to the queue
Definition at line 107 of file callback.hh.
Referenced by Stats::registerDumpCallback(), registerExitCallback(), Stats::registerResetCallback(), and TEST().
add() [2/3]
template<class T , void(T::*)() F> void CallbackQueue::add (T * obj) inline
Definition at line 114 of file callback.hh.
add() [3/3]
template<class T , void(T::*)() F> void CallbackQueue::add (T & obj) inline
Definition at line 121 of file callback.hh.
clear()
void CallbackQueue::clear () inline
clear the callback queue
Definition at line 150 of file callback.hh.
Referenced by doExitCleanup(), and TEST().
empty()
bool CallbackQueue::empty () const inline
Find out if there are any callbacks in the queue.
Definition at line 129 of file callback.hh.
Referenced by TEST().
name()
std::string CallbackQueue::name () const inline
Definition at line 100 of file callback.hh.
Referenced by TEST().
process()
void CallbackQueue::process () inline
process all callbacks
Definition at line 135 of file callback.hh.
References ArmISA::i.
Referenced by doExitCleanup(), Stats::processDumpQueue(), Stats::processResetQueue(), and TEST().
Member Data Documentation
callbacks
queue CallbackQueue::callbacks protected
List of all callbacks.
To be called in fifo order.
Definition at line 96 of file callback.hh.
Referenced by ~CallbackQueue().
The documentation for this class was generated from the following files:
base/callback.hh
base/callback.cc