gem5: ChannelAddr Class Reference
ChannelAddr Class Reference
Class holding a guest address in a contiguous channel-local address space.
#include <channel_addr.hh>
Public Types
using Type = Addr
Public Member Functions
constexpr ChannelAddr (Type _a)
Explicit constructor assigning a value.
constexpr operator Type () const
Converting back to the value type.
constexpr Type value () const
Converting back to the value type.
constexpr ChannelAddr ()
ChannelAddr (const AddrRange &range, Addr _a)
ChannelAddr (const ChannelAddr &)=default
ChannelAddr & operator= (const ChannelAddr &)=default
Addr getPA (const AddrRange &range) const
constexpr ChannelAddr operator| (const Type b) const
constexpr ChannelAddr operator & (const Type b) const
constexpr ChannelAddr operator>> (const int b) const
constexpr ChannelAddr operator<< (const int b) const
constexpr ChannelAddr operator* (const Type &b) const
constexpr ChannelAddr operator/ (const Type &b) const
constexpr ChannelAddr operator+ (const Type &b) const
constexpr ChannelAddr operator- (const Type &b) const
constexpr ChannelAddr operator| (const ChannelAddr &b) const
constexpr ChannelAddr operator & (const ChannelAddr &b) const
constexpr ChannelAddr operator^ (const ChannelAddr &b) const
constexpr ChannelAddr operator+ (const ChannelAddr &b) const
constexpr ChannelAddr operator- (const ChannelAddr &b) const
constexpr bool operator> (const ChannelAddr &b) const
constexpr bool operator>= (const ChannelAddr &b) const
constexpr bool operator< (const ChannelAddr &b) const
constexpr bool operator<= (const ChannelAddr &b) const
constexpr bool operator== (const ChannelAddr &b) const
constexpr bool operator!= (const ChannelAddr &b) const
Private Attributes
Type a
Member holding the actual value.
Detailed Description
Class holding a guest address in a contiguous channel-local address space.
Definition at line 51 of file channel_addr.hh.
Member Typedef Documentation
Type
using ChannelAddr::Type = Addr
Definition at line 54 of file channel_addr.hh.
Constructor & Destructor Documentation
ChannelAddr() [1/4]
constexpr ChannelAddr::ChannelAddr (Type _a) inline explicit
Explicit constructor assigning a value.
Definition at line 57 of file channel_addr.hh.
ChannelAddr() [2/4]
constexpr ChannelAddr::ChannelAddr () inline
Definition at line 65 of file channel_addr.hh.
Referenced by ChannelAddr(), operator &(), operator*(), operator+(), operator-(), operator/(), operator<<(), operator>>(), operator^(), and operator|().
ChannelAddr() [3/4]
ChannelAddr::ChannelAddr (const AddrRange & range, Addr _a) inline
Definition at line 67 of file channel_addr.hh.
References ChannelAddr(), and operator=().
ChannelAddr() [4/4]
ChannelAddr::ChannelAddr (const ChannelAddr &) default
Member Function Documentation
getPA()
Addr ChannelAddr::getPA (const AddrRange & range) const inline
Definition at line 74 of file channel_addr.hh.
References a, and AddrRange::addIntlvBits().
operator &() [1/2]
constexpr ChannelAddr ChannelAddr::operator& (const Type b) const inline
Definition at line 81 of file channel_addr.hh.
References a, and ChannelAddr().
operator &() [2/2]
constexpr ChannelAddr ChannelAddr::operator& (const ChannelAddr & b) const inline
Definition at line 113 of file channel_addr.hh.
References a, and ChannelAddr().
operator Type()
constexpr ChannelAddr::operator Type () const inline explicit
Converting back to the value type.
Definition at line 60 of file channel_addr.hh.
References a.
operator!=()
constexpr bool ChannelAddr::operator!= (const ChannelAddr & b) const inline
Definition at line 134 of file channel_addr.hh.
References a.
operator*()
constexpr ChannelAddr ChannelAddr::operator* (const Type & b) const inline
Definition at line 93 of file channel_addr.hh.
References a, and ChannelAddr().
operator+() [1/2]
constexpr ChannelAddr ChannelAddr::operator+ (const Type & b) const inline
Definition at line 101 of file channel_addr.hh.
References a, and ChannelAddr().
operator+() [2/2]
constexpr ChannelAddr ChannelAddr::operator+ (const ChannelAddr & b) const inline
Definition at line 121 of file channel_addr.hh.
References a, and ChannelAddr().
operator-() [1/2]
constexpr ChannelAddr ChannelAddr::operator- (const Type & b) const inline
Definition at line 105 of file channel_addr.hh.
References a, and ChannelAddr().
operator-() [2/2]
constexpr ChannelAddr ChannelAddr::operator- (const ChannelAddr & b) const inline
Definition at line 125 of file channel_addr.hh.
References a, and ChannelAddr().
operator/()
constexpr ChannelAddr ChannelAddr::operator/ (const Type & b) const inline
Definition at line 97 of file channel_addr.hh.
References a, and ChannelAddr().
operator<()
constexpr bool ChannelAddr::operator< (const ChannelAddr & b) const inline
Definition at line 131 of file channel_addr.hh.
References a.
operator<<()
constexpr ChannelAddr ChannelAddr::operator<< (const int b) const inline
Definition at line 89 of file channel_addr.hh.
References a, and ChannelAddr().
Referenced by std::hash< ChannelAddr >::operator()().
operator<=()
constexpr bool ChannelAddr::operator<= (const ChannelAddr & b) const inline
Definition at line 132 of file channel_addr.hh.
References a.
operator=()
ChannelAddr& ChannelAddr::operator= (const ChannelAddr &) default
Referenced by ChannelAddr().
operator==()
constexpr bool ChannelAddr::operator== (const ChannelAddr & b) const inline
Definition at line 133 of file channel_addr.hh.
References a.
operator>()
constexpr bool ChannelAddr::operator> (const ChannelAddr & b) const inline
Definition at line 129 of file channel_addr.hh.
References a.
operator>=()
constexpr bool ChannelAddr::operator>= (const ChannelAddr & b) const inline
Definition at line 130 of file channel_addr.hh.
References a.
operator>>()
constexpr ChannelAddr ChannelAddr::operator>> (const int b) const inline
Definition at line 85 of file channel_addr.hh.
References a, and ChannelAddr().
operator^()
constexpr ChannelAddr ChannelAddr::operator^ (const ChannelAddr & b) const inline
Definition at line 117 of file channel_addr.hh.
References a, and ChannelAddr().
operator|() [1/2]
constexpr ChannelAddr ChannelAddr::operator| (const Type b) const inline
Definition at line 78 of file channel_addr.hh.
References a, and ChannelAddr().
operator|() [2/2]
constexpr ChannelAddr ChannelAddr::operator| (const ChannelAddr & b) const inline
Definition at line 109 of file channel_addr.hh.
References a, and ChannelAddr().
value()
constexpr Type ChannelAddr::value () const inline
Converting back to the value type.
Definition at line 63 of file channel_addr.hh.
References a.
Member Data Documentation
a
Type ChannelAddr::a private
Member holding the actual value.
Definition at line 138 of file channel_addr.hh.
Referenced by getPA(), operator &(), operator Type(), operator!=(), std::hash< ChannelAddr >::operator()(), operator*(), operator+(), operator-(), operator/(), operator<(), operator<<(), operator<=(), operator==(), operator>(), operator>=(), operator>>(), operator^(), operator|(), and value().
The documentation for this class was generated from the following file:
base/channel_addr.hh