gem5: StorageSpace Class Reference
StorageSpace Class Reference
#include <hsail_code.hh>
Public Member Functions
StorageSpace (Brig::BrigSegment _class)
StorageElement * addSymbol (const Brig::BrigDirectiveVariable *sym, const BrigObject *obj)
StorageElement * findSymbol (std::string name)
StorageElement * findSymbol (uint64_t addr)
StorageElement * findSymbol (const Brig::BrigDirectiveVariable *brigptr)
int getSize ()
void resetOffset ()
Private Types
typedef std::map< const Brig::BrigDirectiveVariable *, StorageElement * > DirVarToSE_map
Private Attributes
std::list< StorageElement * > elements
AddrRangeMap< StorageElement * > elements_by_addr
DirVarToSE_map elements_by_brigptr
uint64_t nextOffset
Detailed Description
Definition at line 238 of file hsail_code.hh.
Member Typedef Documentation
DirVarToSE_map
typedef std::map<const Brig::BrigDirectiveVariable*, StorageElement*> StorageSpace::DirVarToSE_map private
Definition at line 241 of file hsail_code.hh.
Constructor & Destructor Documentation
StorageSpace()
StorageSpace::StorageSpace (Brig::BrigSegment _class) inline
Definition at line 250 of file hsail_code.hh.
References addr, and Label::name.
Member Function Documentation
addSymbol()
StorageElement * StorageSpace::addSymbol (const Brig::BrigDirectiveVariable * sym, const BrigObject * obj)
Definition at line 288 of file hsail_code.cc.
References Brig::BRIG_TYPE_ARRAY, Brig::BrigDirectiveVariable::dim, DPRINTF, getBrigDataTypeBytes(), BrigObject::getString(), Brig::BrigUInt64::hi, Brig::BrigDirectiveVariable::init, Brig::BrigUInt64::lo, Brig::BrigDirectiveVariable::name, ArmISA::offset, roundUp(), and Brig::BrigDirectiveVariable::type.
Referenced by StorageMap::addSymbol().
findSymbol() [1/3]
StorageElement * StorageSpace::findSymbol (std::string name)
Definition at line 320 of file hsail_code.cc.
Referenced by StorageMap::findSymbol().
findSymbol() [2/3]
StorageElement * StorageSpace::findSymbol (uint64_t addr)
Definition at line 332 of file hsail_code.cc.
findSymbol() [3/3]
StorageElement * StorageSpace::findSymbol (const Brig::BrigDirectiveVariable * brigptr)
Definition at line 346 of file hsail_code.cc.
getSize()
int StorageSpace::getSize () inline
Definition at line 261 of file hsail_code.hh.
Referenced by StorageMap::getSize().
resetOffset()
void StorageSpace::resetOffset () inline
Definition at line 262 of file hsail_code.hh.
Referenced by StorageMap::resetOffset().
Member Data Documentation
elements
std::list<StorageElement*> StorageSpace::elements private
Definition at line 243 of file hsail_code.hh.
elements_by_addr
AddrRangeMap<StorageElement*> StorageSpace::elements_by_addr private
Definition at line 244 of file hsail_code.hh.
elements_by_brigptr
DirVarToSE_map StorageSpace::elements_by_brigptr private
Definition at line 245 of file hsail_code.hh.
nextOffset
uint64_t StorageSpace::nextOffset private
Definition at line 247 of file hsail_code.hh.
The documentation for this class was generated from the following files:
gpu-compute/hsail_code.hh
gpu-compute/hsail_code.cc