gem5: sc_dt::scfx_params Class Reference
sc_dt::scfx_params Class Reference
#include <scfx_params.hh>
Public Member Functions
scfx_params (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &)
const sc_fxtype_params & type_params () const
sc_enc enc () const
const sc_fxcast_switch & cast_switch () const
int wl () const
int iwl () const
int fwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
void dump (::std::ostream &) const
Private Attributes
sc_fxtype_params m_type_params
sc_enc m_enc
sc_fxcast_switch m_cast_switch
Detailed Description
Definition at line 67 of file scfx_params.hh.
Constructor & Destructor Documentation
scfx_params()
sc_dt::scfx_params::scfx_params (const sc_fxtype_params & type_params_, sc_enc enc_, const sc_fxcast_switch & cast_sw) inline
Definition at line 99 of file scfx_params.hh.
References m_enc, m_type_params, sc_dt::sc_fxtype_params::o_mode(), sc_core::SC_ID_INVALID_O_MODE_, sc_core::SC_ID_WRAP_SM_NOT_DEFINED_, SC_REPORT_ERROR, sc_dt::SC_US_, and sc_dt::SC_WRAP_SM.
Member Function Documentation
cast_switch()
const sc_fxcast_switch & sc_dt::scfx_params::cast_switch () const inline
Definition at line 125 of file scfx_params.hh.
References m_cast_switch.
Referenced by sc_dt::sc_fxnum::cast_switch(), and sc_dt::sc_fxnum_fast::cast_switch().
dump()
void sc_dt::scfx_params::dump (::std::ostream & os) const inline
Definition at line 169 of file scfx_params.hh.
References sc_dt::sc_fxcast_switch::dump(), sc_dt::sc_fxtype_params::dump(), m_cast_switch, m_enc, and m_type_params.
enc()
sc_enc sc_dt::scfx_params::enc () const inline
Definition at line 119 of file scfx_params.hh.
References m_enc.
Referenced by sc_dt::scfx_rep::clear(), sc_dt::scfx_rep::overflow(), sc_dt::overflow(), sc_dt::print_other(), and sc_dt::scfx_rep::set().
fwl()
int sc_dt::scfx_params::fwl () const inline
Definition at line 144 of file scfx_params.hh.
References sc_dt::sc_fxtype_params::iwl(), m_type_params, and sc_dt::sc_fxtype_params::wl().
Referenced by sc_dt::sc_fxnum::bit(), sc_dt::sc_fxnum_fast::bit(), sc_dt::sc_fxnum::operator()(), sc_dt::sc_fxnum_fast::operator()(), sc_dt::sc_fxnum::operator[](), sc_dt::sc_fxnum_fast::operator[](), sc_dt::sc_fxnum::range(), and sc_dt::sc_fxnum_fast::range().
iwl()
int sc_dt::scfx_params::iwl () const inline
Definition at line 138 of file scfx_params.hh.
References sc_dt::sc_fxtype_params::iwl(), and m_type_params.
Referenced by sc_dt::scfx_rep::clear(), sc_dt::sc_fxnum::iwl(), sc_dt::sc_fxnum_fast::iwl(), sc_dt::scfx_rep::overflow(), sc_dt::overflow(), sc_dt::print_other(), sc_dt::scfx_rep::quantization(), sc_dt::quantization(), and sc_dt::scfx_rep::set().
n_bits()
int sc_dt::scfx_params::n_bits () const inline
Definition at line 162 of file scfx_params.hh.
References m_type_params, and sc_dt::sc_fxtype_params::n_bits().
Referenced by sc_dt::sc_fxnum::n_bits(), sc_dt::sc_fxnum_fast::n_bits(), sc_dt::scfx_rep::overflow(), and sc_dt::overflow().
o_mode()
sc_o_mode sc_dt::scfx_params::o_mode () const inline
Definition at line 156 of file scfx_params.hh.
References m_type_params, and sc_dt::sc_fxtype_params::o_mode().
Referenced by sc_dt::sc_fxnum::o_mode(), sc_dt::sc_fxnum_fast::o_mode(), sc_dt::scfx_rep::overflow(), and sc_dt::overflow().
q_mode()
sc_q_mode sc_dt::scfx_params::q_mode () const inline
Definition at line 150 of file scfx_params.hh.
References m_type_params, and sc_dt::sc_fxtype_params::q_mode().
Referenced by sc_dt::sc_fxnum::q_mode(), sc_dt::sc_fxnum_fast::q_mode(), sc_dt::scfx_rep::quantization(), and sc_dt::quantization().
type_params()
const sc_fxtype_params & sc_dt::scfx_params::type_params () const inline
Definition at line 113 of file scfx_params.hh.
References m_type_params.
Referenced by sc_dt::sc_fxnum::type_params(), and sc_dt::sc_fxnum_fast::type_params().
wl()
int sc_dt::scfx_params::wl () const inline
Definition at line 132 of file scfx_params.hh.
References m_type_params, and sc_dt::sc_fxtype_params::wl().
Referenced by sc_dt::sc_fxnum::bit(), sc_dt::sc_fxnum_fast::bit(), sc_dt::sc_fxnum::operator()(), sc_dt::sc_fxnum_fast::operator()(), sc_dt::sc_fxnum::operator[](), sc_dt::sc_fxnum_fast::operator[](), sc_dt::scfx_rep::overflow(), sc_dt::overflow(), sc_dt::print_other(), sc_dt::scfx_rep::quantization(), sc_dt::quantization(), sc_dt::sc_fxnum::range(), sc_dt::sc_fxnum_fast::range(), sc_dt::sc_fxnum::wl(), and sc_dt::sc_fxnum_fast::wl().
Member Data Documentation
m_cast_switch
sc_fxcast_switch sc_dt::scfx_params::m_cast_switch private
Definition at line 92 of file scfx_params.hh.
Referenced by cast_switch(), and dump().
m_enc
sc_enc sc_dt::scfx_params::m_enc private
Definition at line 91 of file scfx_params.hh.
Referenced by dump(), enc(), and scfx_params().
m_type_params
sc_fxtype_params sc_dt::scfx_params::m_type_params private
Definition at line 90 of file scfx_params.hh.
Referenced by dump(), fwl(), iwl(), n_bits(), o_mode(), q_mode(), scfx_params(), type_params(), and wl().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/scfx_params.hh