gem5: sc_core::sc_process_handle Class Reference
sc_core::sc_process_handle Class Reference
#include <sc_process_handle.hh>
Public Member Functions
sc_process_handle ()
sc_process_handle (const sc_process_handle &)
sc_process_handle (sc_object *)
~sc_process_handle ()
operator::sc_gem5::Process * () const
sc_process_handle & operator= (::sc_gem5::Process *p)
bool valid () const
sc_process_handle & operator= (const sc_process_handle &)
bool operator== (const sc_process_handle &) const
bool operator!= (const sc_process_handle &) const
bool operator< (const sc_process_handle &) const
void swap (sc_process_handle &)
const char * name () const
sc_curr_proc_kind proc_kind () const
const std::vector< sc_object * > & get_child_objects () const
const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
sc_object * get_process_object () const
bool dynamic () const
bool terminated () const
const sc_event & terminated_event () const
void suspend (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void resume (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void disable (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void enable (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void kill (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void reset (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
bool is_unwinding ()
const sc_event & reset_event () const
void sync_reset_on (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
void sync_reset_off (sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
template<typename T >
void throw_it (const T &user_defined_exception, sc_descendent_inclusion_info include_descendants=SC_NO_DESCENDANTS)
Private Attributes
::sc_gem5::Process * _gem5_process
Detailed Description
Definition at line 151 of file sc_process_handle.hh.
Constructor & Destructor Documentation
sc_process_handle() [1/3]
sc_core::sc_process_handle::sc_process_handle ()
Definition at line 77 of file sc_process_handle.cc.
Referenced by sc_core::sc_get_current_process_handle().
sc_process_handle() [2/3]
sc_core::sc_process_handle::sc_process_handle (const sc_process_handle & handle)
Definition at line 79 of file sc_process_handle.cc.
References _gem5_process, and sc_gem5::Process::incref().
sc_process_handle() [3/3]
sc_core::sc_process_handle::sc_process_handle (sc_object * obj) explicit
Definition at line 86 of file sc_process_handle.cc.
References _gem5_process, and sc_gem5::Process::incref().
~sc_process_handle()
sc_core::sc_process_handle::~sc_process_handle ()
Definition at line 93 of file sc_process_handle.cc.
References _gem5_process, and sc_gem5::Process::decref().
Member Function Documentation
disable()
void sc_core::sc_process_handle::disable (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 229 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::disable(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, and SC_REPORT_WARNING.
dynamic()
bool sc_core::sc_process_handle::dynamic () const
Definition at line 185 of file sc_process_handle.cc.
References _gem5_process, and sc_gem5::Process::dynamic().
enable()
void sc_core::sc_process_handle::enable (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 239 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::enable(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, and SC_REPORT_WARNING.
get_child_events()
const std::vector< sc_event * > & sc_core::sc_process_handle::get_child_events () const
Definition at line 166 of file sc_process_handle.cc.
References _gem5_process, and sc_core::sc_object::get_child_events().
get_child_objects()
const std::vector< sc_object * > & sc_core::sc_process_handle::get_child_objects () const
Definition at line 159 of file sc_process_handle.cc.
References _gem5_process, and sc_core::sc_object::get_child_objects().
get_parent_object()
sc_object * sc_core::sc_process_handle::get_parent_object () const
Definition at line 173 of file sc_process_handle.cc.
References _gem5_process, and sc_core::sc_object::get_parent_object().
get_process_object()
sc_object * sc_core::sc_process_handle::get_process_object () const
Definition at line 179 of file sc_process_handle.cc.
References _gem5_process.
is_unwinding()
bool sc_core::sc_process_handle::is_unwinding ()
Definition at line 269 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::isUnwinding(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, and SC_REPORT_WARNING.
Referenced by sc_core::sc_is_unwinding().
kill()
void sc_core::sc_process_handle::kill (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 249 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::kill(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, and SC_REPORT_WARNING.
name()
const char * sc_core::sc_process_handle::name () const
Definition at line 147 of file sc_process_handle.cc.
References _gem5_process, and sc_core::sc_object::name().
operator!=()
bool sc_core::sc_process_handle::operator!= (const sc_process_handle & handle) const
Definition at line 126 of file sc_process_handle.cc.
operator::sc_gem5::Process *()
sc_core::sc_process_handle::operator::sc_gem5::Process * () const inline
Definition at line 165 of file sc_process_handle.hh.
operator<()
bool sc_core::sc_process_handle::operator< (const sc_process_handle & other) const
Definition at line 132 of file sc_process_handle.cc.
References _gem5_process.
operator=() [1/2]
sc_process_handle& sc_core::sc_process_handle::operator= (::sc_gem5::Process * p) inline
Definition at line 167 of file sc_process_handle.hh.
References Trace::disable(), X86ISA::enable, name(), operator!=(), operator<(), X86ISA::operator==(), MipsISA::p, Stats::reset(), and sc_core::SC_NO_DESCENDANTS.
operator=() [2/2]
sc_process_handle & sc_core::sc_process_handle::operator= (const sc_process_handle & handle)
Definition at line 108 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::decref(), and sc_gem5::Process::incref().
operator==()
bool sc_core::sc_process_handle::operator== (const sc_process_handle & handle) const
Definition at line 119 of file sc_process_handle.cc.
References _gem5_process.
proc_kind()
sc_curr_proc_kind sc_core::sc_process_handle::proc_kind () const
Definition at line 153 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::procKind(), and sc_core::SC_NO_PROC_.
reset()
void sc_core::sc_process_handle::reset (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 259 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::reset(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, and SC_REPORT_WARNING.
reset_event()
const sc_event & sc_core::sc_process_handle::reset_event () const
Definition at line 279 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::resetEvent(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, and SC_REPORT_WARNING.
resume()
void sc_core::sc_process_handle::resume (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 219 of file sc_process_handle.cc.
References _gem5_process, sc_gem5::Process::resume(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, and SC_REPORT_WARNING.
suspend()
void sc_core::sc_process_handle::suspend (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 209 of file sc_process_handle.cc.
References _gem5_process, sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, SC_REPORT_WARNING, and sc_gem5::Process::suspend().
swap()
void sc_core::sc_process_handle::swap (sc_process_handle & handle)
Definition at line 138 of file sc_process_handle.cc.
References _gem5_process.
sync_reset_off()
void sc_core::sc_process_handle::sync_reset_off (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 302 of file sc_process_handle.cc.
References _gem5_process, sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, SC_REPORT_WARNING, and sc_gem5::Process::syncResetOff().
sync_reset_on()
void sc_core::sc_process_handle::sync_reset_on (sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS)
Definition at line 291 of file sc_process_handle.cc.
References _gem5_process, sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, SC_REPORT_WARNING, and sc_gem5::Process::syncResetOn().
terminated()
bool sc_core::sc_process_handle::terminated () const
Definition at line 191 of file sc_process_handle.cc.
References _gem5_process, and sc_gem5::Process::terminated().
terminated_event()
const sc_event & sc_core::sc_process_handle::terminated_event () const
Definition at line 197 of file sc_process_handle.cc.
References _gem5_process, sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, SC_REPORT_WARNING, and sc_gem5::Process::terminatedEvent().
throw_it()
template<typename T > void sc_core::sc_process_handle::throw_it (const T & user_defined_exception, sc_descendent_inclusion_info include_descendants = SC_NO_DESCENDANTS) inline
Definition at line 213 of file sc_process_handle.hh.
References sc_core::sc_allow_process_control_corners, sc_core::sc_get_current_process_handle(), sc_core::SC_ID_EMPTY_PROCESS_HANDLE_, sc_core::SC_INCLUDE_DESCENDANTS, sc_core::sc_is_unwinding(), SC_REPORT_WARNING, and sc_gem5::throw_it_wrapper().
valid()
bool sc_core::sc_process_handle::valid () const
Definition at line 101 of file sc_process_handle.cc.
References _gem5_process.
Referenced by sc_core::sc_mutex::trylock().
Member Data Documentation
_gem5_process
::sc_gem5::Process* sc_core::sc_process_handle::_gem5_process private
Definition at line 154 of file sc_process_handle.hh.
Referenced by disable(), dynamic(), enable(), get_child_events(), get_child_objects(), get_parent_object(), get_process_object(), is_unwinding(), kill(), name(), operator<(), operator=(), operator==(), proc_kind(), reset(), reset_event(), resume(), sc_process_handle(), suspend(), swap(), sync_reset_off(), sync_reset_on(), terminated(), terminated_event(), valid(), and ~sc_process_handle().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_process_handle.hh
systemc/core/sc_process_handle.cc