gem5: FreeBSD::UDelayEvent Class Reference
FreeBSD::UDelayEvent Class Reference
A class to skip udelay() and related calls in the kernel.
#include <events.hh>
Public Member Functions
UDelayEvent (PCEventScope *s, const std::string &desc, Addr addr, uint64_t mult, uint64_t div)
virtual void process (ThreadContext *xc)
Public Member Functions inherited from SkipFuncEvent
SkipFuncEvent (PCEventScope *s, const std::string &desc, Addr addr)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Private Attributes
uint64_t argDivToNs
value to divide arg by to create ns.
uint64_t argMultToNs
value to multiple arg by to create ns.
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
A class to skip udelay() and related calls in the kernel.
This class has two additional parameters that take the argument to udelay and manipulated it to come up with ns and eventually ticks to quiesce for. See descriptions of argDivToNs and argMultToNs below.
Definition at line 45 of file events.hh.
Constructor & Destructor Documentation
UDelayEvent()
FreeBSD::UDelayEvent::UDelayEvent (PCEventScope * s, const std::string & desc, Addr addr, uint64_t mult, uint64_t div) inline
Definition at line 60 of file events.hh.
References process().
Member Function Documentation
process()
void FreeBSD::UDelayEvent::process (ThreadContext * xc) virtual
Reimplemented from SkipFuncEvent.
Definition at line 49 of file events.cc.
References argDivToNs, argMultToNs, AlphaISA::getArgument(), SkipFuncEvent::process(), and PseudoInst::quiesceNs().
Referenced by UDelayEvent().
Member Data Documentation
argDivToNs
uint64_t FreeBSD::UDelayEvent::argDivToNs private
value to divide arg by to create ns.
This is present beacues the linux kernel code sometime precomputes the first multiply that is done in udelay() if the parameter is a constant. We need to undo it so here is how.
Definition at line 52 of file events.hh.
Referenced by process().
argMultToNs
uint64_t FreeBSD::UDelayEvent::argMultToNs private
value to multiple arg by to create ns.
Nominally, this is 1000 to convert us to ns, but since linux can do some preprocessing of constant values something else might be required.
Definition at line 57 of file events.hh.
Referenced by process().
The documentation for this class was generated from the following files:
kern/freebsd/events.hh
kern/freebsd/events.cc