gem5: ObjectMatch Class Reference
ObjectMatch Class Reference
ObjectMatch contains a vector of expressions.
#include <match.hh>
Public Member Functions
ObjectMatch ()
ObjectMatch (const std::string &expression)
void add (const ObjectMatch &other)
void setExpression (const std::string &expression)
void setExpression (const std::vector< std::string > &expression)
std::vector< std::vector< std::string > > getExpressions ()
bool match (const std::string &name) const
Protected Member Functions
bool domatch (const std::string &name) const
Protected Attributes
std::vector< std::vector< std::string > > tokens
Detailed Description
ObjectMatch contains a vector of expressions.
ObjectMatch can then be queried, via ObjectMatch.match(std::string), to check if a string matches any expressions in the vector.
Expressions in ObjectMatch take the form "<token1>.<token2>.<token3>"; a series of expected tokens separated by a period. The input string takes the form "<value1>.<value2>.<value3>". In this case, the input string matches the expression if <value1> == <token1> && <token2> == <value2> && <value3> == <token3>. A token may be a wildcard character, "*", which will match to any value in that position (inclusive of no value at that location).
Definition at line 56 of file match.hh.
Constructor & Destructor Documentation
ObjectMatch() [1/2]
ObjectMatch::ObjectMatch ()
Definition at line 39 of file match.cc.
ObjectMatch() [2/2]
ObjectMatch::ObjectMatch (const std::string & expression)
Member Function Documentation
add()
void ObjectMatch::add (const ObjectMatch & other)
Definition at line 49 of file match.cc.
References ArmISA::i, setExpression(), tokenize(), and tokens.
Referenced by Trace::Logger::addIgnore(), and TEST().
domatch()
bool ObjectMatch::domatch (const std::string & name) const protected
Todo:
this should probably be changed to just use regular expression code
Definition at line 78 of file match.cc.
References ArmISA::i, ArmISA::j, and tokenize().
Referenced by match().
getExpressions()
std::vector< std::vector< std::string > > ObjectMatch::getExpressions ()
Definition at line 109 of file match.cc.
Referenced by TEST().
match()
bool ObjectMatch::match (const std::string & name) const inline
Definition at line 69 of file match.hh.
References domatch().
Referenced by Trace::Logger::dprintf(), Trace::Logger::dump(), Trace::OstreamLogger::logMessage(), SimObject::serializeAll(), and TEST().
setExpression() [1/2]
void ObjectMatch::setExpression (const std::string & expression)
Referenced by add(), and TEST().
setExpression() [2/2]
void ObjectMatch::setExpression (const std::vector< std::string > & expression)
Member Data Documentation
tokens
std::vector<std::vector<std::string> > ObjectMatch::tokens protected
Definition at line 59 of file match.hh.
Referenced by add().
The documentation for this class was generated from the following files:
base/match.hh
base/match.cc