gem5: Linux::DebugPrintkEvent Class Reference
Linux::DebugPrintkEvent Class Reference
#include <events.hh>
Public Member Functions
DebugPrintkEvent (PCEventScope *s, const std::string &desc, Addr addr)
virtual void process (ThreadContext *xc)
Public Member Functions inherited from SkipFuncEvent
SkipFuncEvent (PCEventScope *s, const std::string &desc, Addr addr)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 51 of file events.hh.
Constructor & Destructor Documentation
DebugPrintkEvent()
Linux::DebugPrintkEvent::DebugPrintkEvent (PCEventScope * s, const std::string & desc, Addr addr) inline
Definition at line 54 of file events.hh.
References process().
Member Function Documentation
process()
void Linux::DebugPrintkEvent::process (ThreadContext * xc) virtual
Reimplemented from SkipFuncEvent.
Definition at line 64 of file events.cc.
References DPRINTFN, DTRACE, ThreadContext::getSystemPtr(), PCEvent::name(), SimObject::name(), Printk(), SkipFuncEvent::process(), and ArmISA::ss.
Referenced by DebugPrintkEvent(), Linux::DmesgDumpEvent::DmesgDumpEvent(), Linux::KernelPanicEvent::KernelPanicEvent(), and Linux::UDelayEvent::UDelayEvent().
The documentation for this class was generated from the following files:
kern/linux/events.hh
kern/linux/events.cc