gem5: Gicv3Redistributor Class Reference
Gicv3Redistributor Class Reference
#include <gic_v3_redistributor.hh>
Public Member Functions
void activateIRQ (uint32_t int_id)
bool canBeSelectedFor1toNInterrupt (Gicv3::GroupId group) const
void deactivateIRQ (uint32_t int_id)
Gicv3CPUInterface * getCPUInterface () const
uint32_t processorNumber () const
Gicv3::GroupId getIntGroup (int int_id) const
Gicv3::IntStatus intStatus (uint32_t int_id) const
uint8_t readEntryLPI (uint32_t intid)
void writeEntryLPI (uint32_t intid, uint8_t lpi_entry)
bool isPendingLPI (uint32_t intid)
void setClrLPI (uint64_t data, bool set)
void sendSGI (uint32_t int_id, Gicv3::GroupId group, bool ns)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void update ()
void updateDistributor ()
Gicv3Redistributor (Gicv3 *gic, uint32_t cpu_id)
uint32_t getAffinity () const
void init ()
uint64_t read (Addr addr, size_t size, bool is_secure_access)
void sendPPInt (uint32_t int_id)
void write (Addr addr, uint64_t data, size_t size, bool is_secure_access)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
const uint32_t addrRangeSize
Static Public Attributes
static const uint32_t SMALLEST_LPI_ID = 8192
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
enum {
GICR_CTLR = RD_base + 0x0000, GICR_IIDR = RD_base + 0x0004, GICR_TYPER = RD_base + 0x0008, GICR_WAKER = RD_base + 0x0014,
GICR_PIDR0 = RD_base + 0xffe0, GICR_PIDR1 = RD_base + 0xffe4, GICR_PIDR2 = RD_base + 0xffe8, GICR_PIDR3 = RD_base + 0xffec,
GICR_PIDR4 = RD_base + 0xffd0, GICR_PIDR5 = RD_base + 0xffd4, GICR_PIDR6 = RD_base + 0xffd8, GICR_PIDR7 = RD_base + 0xffdc
}
enum {
GICR_IGROUPR0 = SGI_base + 0x0080, GICR_ISENABLER0 = SGI_base + 0x0100, GICR_ICENABLER0 = SGI_base + 0x0180, GICR_ISPENDR0 = SGI_base + 0x0200,
GICR_ICPENDR0 = SGI_base + 0x0280, GICR_ISACTIVER0 = SGI_base + 0x0300, GICR_ICACTIVER0 = SGI_base + 0x0380, GICR_ICFGR0 = SGI_base + 0x0c00,
GICR_ICFGR1 = SGI_base + 0x0c04, GICR_IGRPMODR0 = SGI_base + 0x0d00, GICR_NSACR = SGI_base + 0x0e00
}
enum {
GICR_SETLPIR = RD_base + 0x0040, GICR_CLRLPIR = RD_base + 0x0048, GICR_PROPBASER = RD_base + 0x0070, GICR_PENDBASER = RD_base + 0x0078,
GICR_INVLPIR = RD_base + 0x00A0, GICR_INVALLR = RD_base + 0x00B0, GICR_SYNCR = RD_base + 0x00C0
}
Protected Member Functions
BitUnion8 (LPIConfigurationTableEntry) Bitfield< 7
EndBitUnion (LPIConfigurationTableEntry) static const uint32_t GICR_CTLR_ENABLE_LPIS
Protected Attributes
Gicv3 * gic
Gicv3Distributor * distributor
Gicv3CPUInterface * cpuInterface
uint32_t cpuId
PortProxy * memProxy
bool peInLowPowerState
std::vector< uint8_t > irqGroup
std::vector< bool > irqEnabled
std::vector< bool > irqPending
std::vector< bool > irqActive
std::vector< uint8_t > irqPriority
std::vector< Gicv3::IntTriggerType > irqConfig
std::vector< uint8_t > irqGrpmod
std::vector< uint8_t > irqNsacr
bool DPG1S
bool DPG1NS
bool DPG0
bool EnableLPIs
Addr lpiConfigurationTablePtr
uint8_t lpiIDBits
Addr lpiPendingTablePtr
priority
Bitfield< 1 > res1
Bitfield< 0 > enable
Static Protected Attributes
static const uint32_t RD_base = 0x0
static const uint32_t SGI_base = 0x10000
static const uint32_t GICR_WAKER_ProcessorSleep = 1 << 1
static const uint32_t GICR_WAKER_ChildrenAsleep = 1 << 2
static const AddrRange GICR_IPRIORITYR
static const uint32_t GICR_CTLR_DPG0 = 1 << 24
static const uint32_t GICR_CTLR_DPG1NS = 1 << 25
static const uint32_t GICR_CTLR_DPG1S = 1 << 26
Friends
class Gicv3CPUInterface
class Gicv3Distributor
class Gicv3Its
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Definition at line 54 of file gic_v3_redistributor.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GICR_CTLR
GICR_IIDR
GICR_TYPER
GICR_WAKER
GICR_PIDR0
GICR_PIDR1
GICR_PIDR2
GICR_PIDR3
GICR_PIDR4
GICR_PIDR5
GICR_PIDR6
GICR_PIDR7
Definition at line 77 of file gic_v3_redistributor.hh.
anonymous enum
anonymous enum protected
Enumerator
GICR_IGROUPR0
GICR_ISENABLER0
GICR_ICENABLER0
GICR_ISPENDR0
GICR_ICPENDR0
GICR_ISACTIVER0
GICR_ICACTIVER0
GICR_ICFGR0
GICR_ICFGR1
GICR_IGRPMODR0
GICR_NSACR
Definition at line 109 of file gic_v3_redistributor.hh.
anonymous enum
anonymous enum protected
Enumerator
GICR_SETLPIR
GICR_CLRLPIR
GICR_PROPBASER
GICR_PENDBASER
GICR_INVLPIR
GICR_INVALLR
GICR_SYNCR
Definition at line 138 of file gic_v3_redistributor.hh.
Constructor & Destructor Documentation
Gicv3Redistributor()
Gicv3Redistributor::Gicv3Redistributor (Gicv3 * gic, uint32_t cpu_id)
Definition at line 54 of file gic_v3_redistributor.cc.
Referenced by processorNumber().
Member Function Documentation
activateIRQ()
void Gicv3Redistributor::activateIRQ (uint32_t int_id)
Definition at line 968 of file gic_v3_redistributor.cc.
References irqActive, and irqPending.
Referenced by Gicv3CPUInterface::generateSGI(), and Gicv3CPUInterface::readMiscReg().
BitUnion8()
Gicv3Redistributor::BitUnion8 (LPIConfigurationTableEntry) protected
canBeSelectedFor1toNInterrupt()
bool Gicv3Redistributor::canBeSelectedFor1toNInterrupt (Gicv3::GroupId group) const
Definition at line 998 of file gic_v3_redistributor.cc.
References distributor, DPG0, DPG1NS, DPG1S, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, Gicv3Distributor::groupEnabled(), and peInLowPowerState.
Referenced by Gicv3Distributor::route().
deactivateIRQ()
void Gicv3Redistributor::deactivateIRQ (uint32_t int_id)
Definition at line 975 of file gic_v3_redistributor.cc.
References irqActive.
Referenced by Gicv3CPUInterface::deactivateIRQ().
EndBitUnion()
Gicv3Redistributor::EndBitUnion (LPIConfigurationTableEntry) const protected
getAffinity()
uint32_t Gicv3Redistributor::getAffinity () const
Definition at line 981 of file gic_v3_redistributor.cc.
References cpuId, ArmISA::getMPIDR(), BaseGic::getSystem(), System::getThreadContext(), and gic.
Referenced by Gicv3CPUInterface::generateSGI(), processorNumber(), and read().
getCPUInterface()
Gicv3CPUInterface* Gicv3Redistributor::getCPUInterface () const inline
Definition at line 203 of file gic_v3_redistributor.hh.
References cpuInterface.
Referenced by Gicv3Distributor::route().
getIntGroup()
Gicv3::GroupId Gicv3Redistributor::getIntGroup (int int_id) const
Definition at line 942 of file gic_v3_redistributor.cc.
References distributor, Gicv3Distributor::DS, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, irqGroup, irqGrpmod, Gicv3::PPI_MAX, and Gicv3::SGI_MAX.
Referenced by processorNumber(), read(), sendSGI(), Gicv3CPUInterface::setMiscReg(), update(), Gicv3CPUInterface::virtualDeactivateIRQ(), and write().
init()
void Gicv3Redistributor::init ()
Definition at line 81 of file gic_v3_redistributor.cc.
References cpuId, cpuInterface, distributor, Gicv3::getCPUInterface(), Gicv3::getDistributor(), BaseGic::getSystem(), gic, memProxy, and System::physProxy.
Referenced by processorNumber().
intStatus()
Gicv3::IntStatus Gicv3Redistributor::intStatus (uint32_t int_id) const
Definition at line 753 of file gic_v3_redistributor.cc.
References Gicv3::INT_ACTIVE, Gicv3::INT_ACTIVE_PENDING, Gicv3::INT_INACTIVE, Gicv3::INT_PENDING, irqActive, irqPending, Gicv3::PPI_MAX, and Gicv3::SGI_MAX.
Referenced by processorNumber().
isPendingLPI()
bool Gicv3Redistributor::isPendingLPI (uint32_t intid)
Definition at line 880 of file gic_v3_redistributor.cc.
References readEntryLPI().
Referenced by ItsCommand::movi(), and processorNumber().
processorNumber()
uint32_t Gicv3Redistributor::processorNumber () const inline
Definition at line 209 of file gic_v3_redistributor.hh.
References addr, cpuId, data, getAffinity(), getIntGroup(), Gicv3Redistributor(), init(), intStatus(), isPendingLPI(), ArmISA::ns, read(), readEntryLPI(), sendPPInt(), sendSGI(), serialize(), setClrLPI(), Gicv3Its::size, unserialize(), update(), updateDistributor(), write(), and writeEntryLPI().
Referenced by Gicv3::read(), and Gicv3::write().
read()
uint64_t Gicv3Redistributor::read (Addr addr, size_t size, bool is_secure_access)
Definition at line 90 of file gic_v3_redistributor.cc.
References AddrRange::contains(), cpuId, distributor, DPG0, DPG1NS, DPG1S, Gicv3Distributor::DS, EnableLPIs, Gicv3::G1NS, getAffinity(), getIntGroup(), BaseGic::getSystem(), gic, GICR_CTLR, GICR_CTLR_DPG0, GICR_CTLR_DPG1NS, GICR_CTLR_DPG1S, GICR_ICACTIVER0, GICR_ICENABLER0, GICR_ICFGR0, GICR_ICFGR1, GICR_ICPENDR0, GICR_IGROUPR0, GICR_IGRPMODR0, GICR_IIDR, GICR_IPRIORITYR, GICR_ISACTIVER0, GICR_ISENABLER0, GICR_ISPENDR0, GICR_NSACR, GICR_PENDBASER, GICR_PIDR0, GICR_PIDR1, GICR_PIDR2, GICR_PIDR3, GICR_PIDR4, GICR_PIDR5, GICR_PIDR6, GICR_PIDR7, GICR_PROPBASER, GICR_SYNCR, GICR_TYPER, GICR_WAKER, GICR_WAKER_ChildrenAsleep, GICR_WAKER_ProcessorSleep, ArmISA::i, Gicv3::INT_EDGE_TRIGGERED, irqActive, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, lpiConfigurationTablePtr, lpiIDBits, lpiPendingTablePtr, System::numContexts(), panic, peInLowPowerState, Gicv3::SGI_MAX, and AddrRange::start().
Referenced by processorNumber(), and Gicv3::read().
readEntryLPI()
uint8_t Gicv3Redistributor::readEntryLPI (uint32_t intid)
Definition at line 857 of file gic_v3_redistributor.cc.
References lpiPendingTablePtr, memProxy, and PortProxy::readBlob().
Referenced by isPendingLPI(), processorNumber(), and setClrLPI().
sendPPInt()
void Gicv3Redistributor::sendPPInt (uint32_t int_id)
Definition at line 705 of file gic_v3_redistributor.cc.
References DPRINTF, irqPending, Gicv3::PPI_MAX, Gicv3::SGI_MAX, and updateDistributor().
Referenced by processorNumber().
sendSGI()
void Gicv3Redistributor::sendSGI (uint32_t int_id, Gicv3::GroupId group, bool ns)
Definition at line 716 of file gic_v3_redistributor.cc.
References distributor, DPRINTF, Gicv3Distributor::DS, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, getIntGroup(), irqNsacr, irqPending, Gicv3::SGI_MAX, and updateDistributor().
Referenced by Gicv3CPUInterface::generateSGI(), and processorNumber().
serialize()
void Gicv3Redistributor::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1024 of file gic_v3_redistributor.cc.
References DPG0, DPG1NS, DPG1S, EnableLPIs, irqActive, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, lpiConfigurationTablePtr, lpiIDBits, lpiPendingTablePtr, peInLowPowerState, SERIALIZE_CONTAINER, and SERIALIZE_SCALAR.
Referenced by processorNumber().
setClrLPI()
void Gicv3Redistributor::setClrLPI (uint64_t data, bool set)
Definition at line 892 of file gic_v3_redistributor.cc.
References cpuInterface, EnableLPIs, lpiIDBits, readEntryLPI(), Gicv3CPUInterface::resetHppi(), updateDistributor(), and writeEntryLPI().
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), Gicv3CPUInterface::generateSGI(), ItsTranslation::main(), ItsCommand::movi(), processorNumber(), and write().
unserialize()
void Gicv3Redistributor::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1045 of file gic_v3_redistributor.cc.
References DPG0, DPG1NS, DPG1S, EnableLPIs, irqActive, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, lpiConfigurationTablePtr, lpiIDBits, lpiPendingTablePtr, peInLowPowerState, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
Referenced by processorNumber().
update()
void Gicv3Redistributor::update ()
Definition at line 781 of file gic_v3_redistributor.cc.
References cpuInterface, distributor, EnableLPIs, Gicv3::G1NS, getIntGroup(), Gicv3CPUInterface::hppi_t::group, Gicv3Distributor::groupEnabled(), Gicv3CPUInterface::hppi, Gicv3CPUInterface::hppi_t::intid, irqActive, irqEnabled, irqPending, irqPriority, lpiConfigurationTablePtr, lpiIDBits, lpiPendingTablePtr, memProxy, Gicv3::PPI_MAX, Gicv3CPUInterface::hppi_t::prio, PortProxy::readBlob(), Gicv3::SGI_MAX, SMALLEST_LPI_ID, and Gicv3CPUInterface::update().
Referenced by processorNumber(), and Gicv3Distributor::update().
updateDistributor()
void Gicv3Redistributor::updateDistributor ()
Definition at line 771 of file gic_v3_redistributor.cc.
References distributor, and Gicv3Distributor::update().
Referenced by Gicv3Its::moveAllPendingState(), processorNumber(), sendPPInt(), sendSGI(), setClrLPI(), and write().
write()
void Gicv3Redistributor::write (Addr addr, uint64_t data, size_t size, bool is_secure_access)
Definition at line 385 of file gic_v3_redistributor.cc.
References bits(), AddrRange::contains(), Trace::disable(), distributor, DPG0, DPG1NS, DPG1S, DPRINTF, Gicv3Distributor::DS, enable, EnableLPIs, Gicv3::G1NS, getIntGroup(), GICR_CLRLPIR, GICR_CTLR, GICR_CTLR_DPG0, GICR_CTLR_DPG1NS, GICR_CTLR_DPG1S, GICR_ICACTIVER0, GICR_ICENABLER0, GICR_ICFGR1, GICR_ICPENDR0, GICR_IGROUPR0, GICR_IGRPMODR0, GICR_INVALLR, GICR_INVLPIR, GICR_IPRIORITYR, GICR_ISACTIVER0, GICR_ISENABLER0, GICR_ISPENDR0, GICR_NSACR, GICR_PENDBASER, GICR_PROPBASER, GICR_SETLPIR, GICR_WAKER, GICR_WAKER_ProcessorSleep, ArmISA::i, Gicv3::INT_EDGE_TRIGGERED, Gicv3::INT_LEVEL_SENSITIVE, irqActive, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, lpiConfigurationTablePtr, lpiIDBits, lpiPendingTablePtr, panic, peInLowPowerState, setClrLPI(), Gicv3::SGI_MAX, AddrRange::start(), and updateDistributor().
Referenced by processorNumber(), and Gicv3::write().
writeEntryLPI()
void Gicv3Redistributor::writeEntryLPI (uint32_t intid, uint8_t lpi_entry)
Definition at line 870 of file gic_v3_redistributor.cc.
References lpiPendingTablePtr, memProxy, and PortProxy::writeBlob().
Referenced by processorNumber(), and setClrLPI().
Friends And Related Function Documentation
Gicv3CPUInterface
friend class Gicv3CPUInterface friend
Definition at line 58 of file gic_v3_redistributor.hh.
Gicv3Distributor
friend class Gicv3Distributor friend
Definition at line 59 of file gic_v3_redistributor.hh.
Gicv3Its
friend class Gicv3Its friend
Definition at line 60 of file gic_v3_redistributor.hh.
Member Data Documentation
addrRangeSize
const uint32_t Gicv3Redistributor::addrRangeSize
Definition at line 193 of file gic_v3_redistributor.hh.
cpuId
uint32_t Gicv3Redistributor::cpuId protected
Definition at line 67 of file gic_v3_redistributor.hh.
Referenced by getAffinity(), init(), processorNumber(), and read().
cpuInterface
Gicv3CPUInterface* Gicv3Redistributor::cpuInterface protected
Definition at line 66 of file gic_v3_redistributor.hh.
Referenced by getCPUInterface(), init(), setClrLPI(), and update().
distributor
Gicv3Distributor* Gicv3Redistributor::distributor protected
Definition at line 65 of file gic_v3_redistributor.hh.
Referenced by canBeSelectedFor1toNInterrupt(), getIntGroup(), init(), read(), sendSGI(), update(), updateDistributor(), and write().
DPG0
bool Gicv3Redistributor::DPG0 protected
Definition at line 166 of file gic_v3_redistributor.hh.
Referenced by canBeSelectedFor1toNInterrupt(), read(), serialize(), unserialize(), and write().
DPG1NS
bool Gicv3Redistributor::DPG1NS protected
Definition at line 165 of file gic_v3_redistributor.hh.
Referenced by canBeSelectedFor1toNInterrupt(), read(), serialize(), unserialize(), and write().
DPG1S
bool Gicv3Redistributor::DPG1S protected
Definition at line 164 of file gic_v3_redistributor.hh.
Referenced by canBeSelectedFor1toNInterrupt(), read(), serialize(), unserialize(), and write().
enable
Bitfield<0> Gicv3Redistributor::enable protected
Definition at line 176 of file gic_v3_redistributor.hh.
Referenced by write().
EnableLPIs
bool Gicv3Redistributor::EnableLPIs protected
Definition at line 167 of file gic_v3_redistributor.hh.
Referenced by read(), serialize(), setClrLPI(), unserialize(), update(), and write().
gic
Gicv3* Gicv3Redistributor::gic protected
Definition at line 64 of file gic_v3_redistributor.hh.
Referenced by getAffinity(), init(), and read().
GICR_CTLR_DPG0
const uint32_t Gicv3Redistributor::GICR_CTLR_DPG0 = 1 << 24 static protected
Definition at line 180 of file gic_v3_redistributor.hh.
Referenced by read(), and write().
GICR_CTLR_DPG1NS
const uint32_t Gicv3Redistributor::GICR_CTLR_DPG1NS = 1 << 25 static protected
Definition at line 181 of file gic_v3_redistributor.hh.
Referenced by read(), and write().
GICR_CTLR_DPG1S
const uint32_t Gicv3Redistributor::GICR_CTLR_DPG1S = 1 << 26 static protected
Definition at line 182 of file gic_v3_redistributor.hh.
Referenced by read(), and write().
GICR_IPRIORITYR
const AddrRange Gicv3Redistributor::GICR_IPRIORITYR static protected
Definition at line 135 of file gic_v3_redistributor.hh.
Referenced by read(), and write().
GICR_WAKER_ChildrenAsleep
const uint32_t Gicv3Redistributor::GICR_WAKER_ChildrenAsleep = 1 << 2 static protected
Definition at line 105 of file gic_v3_redistributor.hh.
Referenced by read().
GICR_WAKER_ProcessorSleep
const uint32_t Gicv3Redistributor::GICR_WAKER_ProcessorSleep = 1 << 1 static protected
Definition at line 104 of file gic_v3_redistributor.hh.
Referenced by read(), and write().
irqActive
std::vector<bool> Gicv3Redistributor::irqActive protected
Definition at line 158 of file gic_v3_redistributor.hh.
Referenced by activateIRQ(), deactivateIRQ(), intStatus(), read(), serialize(), unserialize(), update(), and write().
irqConfig
std::vector<Gicv3::IntTriggerType> Gicv3Redistributor::irqConfig protected
Definition at line 160 of file gic_v3_redistributor.hh.
Referenced by read(), serialize(), unserialize(), and write().
irqEnabled
std::vector<bool> Gicv3Redistributor::irqEnabled protected
Definition at line 156 of file gic_v3_redistributor.hh.
Referenced by read(), serialize(), unserialize(), update(), and write().
irqGroup
std::vector<uint8_t> Gicv3Redistributor::irqGroup protected
Definition at line 155 of file gic_v3_redistributor.hh.
Referenced by getIntGroup(), read(), serialize(), unserialize(), and write().
irqGrpmod
std::vector<uint8_t> Gicv3Redistributor::irqGrpmod protected
Definition at line 161 of file gic_v3_redistributor.hh.
Referenced by getIntGroup(), read(), serialize(), unserialize(), and write().
irqNsacr
std::vector<uint8_t> Gicv3Redistributor::irqNsacr protected
Definition at line 162 of file gic_v3_redistributor.hh.
Referenced by read(), sendSGI(), serialize(), unserialize(), and write().
irqPending
std::vector<bool> Gicv3Redistributor::irqPending protected
Definition at line 157 of file gic_v3_redistributor.hh.
Referenced by activateIRQ(), intStatus(), read(), sendPPInt(), sendSGI(), serialize(), unserialize(), update(), and write().
irqPriority
std::vector<uint8_t> Gicv3Redistributor::irqPriority protected
Definition at line 159 of file gic_v3_redistributor.hh.
Referenced by read(), serialize(), unserialize(), update(), and write().
lpiConfigurationTablePtr
Addr Gicv3Redistributor::lpiConfigurationTablePtr protected
Definition at line 169 of file gic_v3_redistributor.hh.
Referenced by read(), serialize(), unserialize(), update(), and write().
lpiIDBits
uint8_t Gicv3Redistributor::lpiIDBits protected
Definition at line 170 of file gic_v3_redistributor.hh.
Referenced by Gicv3Its::moveAllPendingState(), read(), serialize(), setClrLPI(), unserialize(), update(), and write().
lpiPendingTablePtr
Addr Gicv3Redistributor::lpiPendingTablePtr protected
Definition at line 171 of file gic_v3_redistributor.hh.
Referenced by Gicv3Its::moveAllPendingState(), read(), readEntryLPI(), serialize(), unserialize(), update(), write(), and writeEntryLPI().
memProxy
PortProxy* Gicv3Redistributor::memProxy protected
Definition at line 68 of file gic_v3_redistributor.hh.
Referenced by init(), Gicv3Its::moveAllPendingState(), readEntryLPI(), update(), and writeEntryLPI().
peInLowPowerState
bool Gicv3Redistributor::peInLowPowerState protected
Definition at line 107 of file gic_v3_redistributor.hh.
Referenced by canBeSelectedFor1toNInterrupt(), read(), serialize(), unserialize(), and write().
priority
Gicv3Redistributor::priority protected
Definition at line 174 of file gic_v3_redistributor.hh.
RD_base
const uint32_t Gicv3Redistributor::RD_base = 0x0 static protected
Definition at line 74 of file gic_v3_redistributor.hh.
res1
Bitfield<1> Gicv3Redistributor::res1 protected
Definition at line 175 of file gic_v3_redistributor.hh.
SGI_base
const uint32_t Gicv3Redistributor::SGI_base = 0x10000 static protected
Definition at line 75 of file gic_v3_redistributor.hh.
SMALLEST_LPI_ID
const uint32_t Gicv3Redistributor::SMALLEST_LPI_ID = 8192 static
Definition at line 195 of file gic_v3_redistributor.hh.
Referenced by Gicv3CPUInterface::generateSGI(), Gicv3Its::lpiOutOfRange(), Gicv3CPUInterface::readMiscReg(), and update().
The documentation for this class was generated from the following files:
dev/arm/gic_v3_redistributor.hh
dev/arm/gic_v3_redistributor.cc