gem5: CoherentXBar Class Reference
CoherentXBar Class Reference
A coherent crossbar connects a number of (potentially) snooping masters and slaves, and routes the request and response packets based on the address, and also forwards all requests to the snoopers and deals with the snoop responses.
#include <coherent_xbar.hh>
Classes
class CoherentXBarMasterPort
Declaration of the coherent crossbar master port type, one will be instantiated for each of the slave interfaces connecting to the crossbar.
class CoherentXBarSlavePort
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
class SnoopRespPort
Internal class to bridge between an incoming snoop response from a slave port and forwarding it through an outgoing slave port.
Public Member Functions
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
CoherentXBar (const CoherentXBarParams *p)
virtual ~CoherentXBar ()
virtual void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from BaseXBar
virtual ~BaseXBar ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
A function used to return the port associated with this object.
void regStats () override
Callback to set stat parameters.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool recvTimingReq (PacketPtr pkt, PortID slave_port_id)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
void recvTimingSnoopReq (PacketPtr pkt, PortID master_port_id)
bool recvTimingSnoopResp (PacketPtr pkt, PortID slave_port_id)
void recvReqRetry (PortID master_port_id)
void forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id)
Forward a timing packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
void forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id, const std::vector< QueuedSlavePort *> &dests)
Forward a timing packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Tick recvAtomicBackdoor (PacketPtr pkt, PortID slave_port_id, MemBackdoorPtr *backdoor=nullptr)
Tick recvAtomicSnoop (PacketPtr pkt, PortID master_port_id)
std::pair< MemCmd, Tick > forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id)
Forward an atomic packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
std::pair< MemCmd, Tick > forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id, PortID source_master_port_id, const std::vector< QueuedSlavePort *> &dests)
Forward an atomic packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
void recvFunctional (PacketPtr pkt, PortID slave_port_id)
Function called by the port when the crossbar is recieving a Functional transaction.
void recvFunctionalSnoop (PacketPtr pkt, PortID master_port_id)
Function called by the port when the crossbar is recieving a functional snoop transaction.
void forwardFunctional (PacketPtr pkt, PortID exclude_slave_port_id)
Forward a functional packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
bool sinkPacket (const PacketPtr pkt) const
Determine if the crossbar should sink the packet, as opposed to forwarding it, or responding.
bool forwardPacket (const PacketPtr pkt)
Determine if the crossbar should forward the packet, as opposed to responding to it.
bool isDestination (const PacketPtr pkt) const
Determine if the packet's destination is the memory below.
Protected Member Functions inherited from BaseXBar
virtual void recvRangeChange (PortID master_port_id)
Function called by the port when the crossbar is recieving a range change.
PortID findPort (AddrRange addr_range)
Find which port connected to this crossbar (if any) should be given a packet with this address range.
AddrRangeList getAddrRanges () const
Return the address ranges the crossbar is responsible for.
void calcPacketTiming (PacketPtr pkt, Tick header_delay)
Calculate the timing parameters for the packet.
BaseXBar (const BaseXBarParams *p)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
std::vector< ReqLayer * > reqLayers
Declare the layers of this crossbar, one vector for requests, one for responses, and one for snoop responses.
std::vector< RespLayer * > respLayers
std::vector< SnoopRespLayer * > snoopLayers
std::vector< SnoopRespPort * > snoopRespPorts
std::vector< QueuedSlavePort * > snoopPorts
std::unordered_set< RequestPtr > outstandingSnoop
Store the outstanding requests that we are expecting snoop responses from so we can determine which snoop responses we generated and which ones were merely forwarded.
std::unordered_map< PacketId, PacketPtr > outstandingCMO
Store the outstanding cache maintenance that we are expecting snoop responses from so we can determine when we received all snoop responses and if any of the agents satisfied the request.
System * system
Keep a pointer to the system to be allow to querying memory system properties.
SnoopFilter * snoopFilter
A snoop filter that tracks cache line residency and can restrict the broadcast needed for probes.
const Cycles snoopResponseLatency
Cycles of snoop response latency.
const unsigned int maxOutstandingSnoopCheck
Maximum number of outstading snoops sanity check.
const unsigned int maxRoutingTableSizeCheck
Maximum routing table size sanity check.
const bool pointOfCoherency
Is this crossbar the point of coherency?
const bool pointOfUnification
Is this crossbar the point of unification?
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Stats::Scalar snoops
Stats::Scalar snoopTraffic
Stats::Distribution snoopFanout
Protected Attributes inherited from BaseXBar
const Cycles frontendLatency
Cycles of front-end pipeline including the delay to accept the request and to decode the address.
const Cycles forwardLatency
const Cycles responseLatency
const uint32_t width
the width of the xbar in bytes
AddrRangeMap< PortID, 3 > portMap
std::unordered_map< RequestPtr, PortID > routeTo
Remember where request packets came from so that we can route responses to the appropriate port.
AddrRangeList xbarRanges
all contigous ranges seen by this crossbar
AddrRange defaultRange
std::vector< bool > gotAddrRanges
Remember for each of the master ports of the crossbar if we got an address range from the connected slave.
bool gotAllAddrRanges
std::vector< QueuedSlavePort * > slavePorts
The master and slave ports of the crossbar.
std::vector< MasterPort * > masterPorts
PortID defaultPortID
Port that handles requests that don't match any of the interfaces.
const bool useDefaultRange
If true, use address range provided by default device.
Stats::Vector transDist
Stats for transaction distribution and data passing through the crossbar.
Stats::Vector2d pktCount
Stats::Vector2d pktSize
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
A coherent crossbar connects a number of (potentially) snooping masters and slaves, and routes the request and response packets based on the address, and also forwards all requests to the snoopers and deals with the snoop responses.
The coherent crossbar can be used as a template for modelling QPI, HyperTransport, ACE and coherent OCP buses, and is typically used for the L1-to-L2 buses and as the main system interconnect.
See also
gem5 Memory System
Definition at line 72 of file coherent_xbar.hh.
Constructor & Destructor Documentation
CoherentXBar()
CoherentXBar::CoherentXBar (const CoherentXBarParams * p)
Definition at line 59 of file coherent_xbar.cc.
References csprintf(), BaseXBar::defaultPortID, ArmISA::i, BaseXBar::masterPorts, SimObject::name(), reqLayers, respLayers, BaseXBar::slavePorts, snoopLayers, and snoopRespPorts.
Referenced by regStats().
~CoherentXBar()
CoherentXBar::~CoherentXBar () virtual
Definition at line 110 of file coherent_xbar.cc.
References MipsISA::l, MipsISA::p, reqLayers, respLayers, snoopLayers, and snoopRespPorts.
Member Function Documentation
forwardAtomic() [1/2]
std::pair<MemCmd, Tick> CoherentXBar::forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id) inline protected
Forward an atomic packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Returns
a pair containing the snoop response and snoop latency
Definition at line 349 of file coherent_xbar.hh.
References forwardFunctional(), forwardPacket(), InvalidPortID, CoherentXBar::CoherentXBarSlavePort::recvFunctional(), recvFunctionalSnoop(), and sinkPacket().
Referenced by recvAtomicBackdoor(), and recvAtomicSnoop().
forwardAtomic() [2/2]
std::pair< MemCmd, Tick > CoherentXBar::forwardAtomic (PacketPtr pkt, PortID exclude_slave_port_id, PortID source_master_port_id, const std::vector< QueuedSlavePort *> & dests) protected
Forward an atomic packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
source_master_port_id Id of the master port for snoops from below
dests Vector of destination ports for the forwarded pkt
Returns
a pair containing the snoop response and snoop latency
Definition at line 921 of file coherent_xbar.cc.
References System::bypassCaches(), Packet::cacheResponding(), Packet::cmd, MemCmd::InvalidCmd, InvalidPortID, Packet::isResponse(), BaseXBar::masterPorts, MipsISA::p, Stats::DistBase< Derived, Stor >::sample(), BaseXBar::slavePorts, snoopFanout, snoopFilter, system, SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
forwardFunctional()
void CoherentXBar::forwardFunctional (PacketPtr pkt, PortID exclude_slave_port_id) protected
Forward a functional packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Definition at line 1048 of file coherent_xbar.cc.
References System::bypassCaches(), InvalidPortID, Packet::isResponse(), MipsISA::p, snoopPorts, and system.
Referenced by forwardAtomic(), recvFunctional(), and recvFunctionalSnoop().
forwardPacket()
bool CoherentXBar::forwardPacket (const PacketPtr pkt) protected
Determine if the crossbar should forward the packet, as opposed to responding to it.
Definition at line 1094 of file coherent_xbar.cc.
References Packet::isClean(), isDestination(), Packet::isRead(), Packet::isWrite(), and pointOfCoherency.
Referenced by forwardAtomic(), recvAtomicBackdoor(), and recvTimingReq().
forwardTiming() [1/2]
void CoherentXBar::forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id) inline protected
Forward a timing packet to our snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
Definition at line 317 of file coherent_xbar.hh.
References CoherentXBar::CoherentXBarSlavePort::recvAtomicBackdoor(), and recvAtomicSnoop().
Referenced by recvTimingReq(), and recvTimingSnoopReq().
forwardTiming() [2/2]
void CoherentXBar::forwardTiming (PacketPtr pkt, PortID exclude_slave_port_id, const std::vector< QueuedSlavePort *> & dests) protected
Forward a timing packet to a selected list of snoopers, potentially excluding one of the connected coherent masters to avoid sending a packet back to where it came from.
Parameters
pkt Packet to forward
exclude_slave_port_id Id of slave port to exclude
dests Vector of destination ports for the forwarded pkt
Definition at line 692 of file coherent_xbar.cc.
References System::bypassCaches(), DPRINTF, InvalidPortID, MipsISA::p, Packet::print(), Stats::DistBase< Derived, Stor >::sample(), snoopFanout, and system.
init()
void CoherentXBar::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 123 of file coherent_xbar.cc.
References DPRINTF, SimObject::init(), SimObject::name(), MipsISA::p, SnoopFilter::setSlavePorts(), BaseXBar::slavePorts, snoopFilter, snoopPorts, and warn.
isDestination()
bool CoherentXBar::isDestination (const PacketPtr pkt) const inline protected
Determine if the packet's destination is the memory below.
The memory below is the destination for a cache mainteance operation to the Point of Coherence/Unification if this is the Point of Coherence/Unification.
Parameters
pkt The processed packet
Returns
Whether the memory below is the destination for the packet
Definition at line 415 of file coherent_xbar.hh.
References pointOfCoherency, pointOfUnification, and Packet::req.
Referenced by forwardPacket(), recvAtomicBackdoor(), and recvTimingReq().
recvAtomicBackdoor()
Tick CoherentXBar::recvAtomicBackdoor (PacketPtr pkt, PortID slave_port_id, MemBackdoorPtr * backdoor = nullptr) protected
Definition at line 729 of file coherent_xbar.cc.
References System::bypassCaches(), Packet::clearWriteThrough(), Clocked::clockPeriod(), Packet::cmd, Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), SnoopFilter::finishRequest(), forwardAtomic(), forwardPacket(), Packet::getAddr(), Packet::getAddrRange(), Packet::getSize(), Packet::hasData(), Packet::id, MemCmd::InvalidCmd, InvalidPortID, Packet::isClean(), isDestination(), Packet::isEviction(), Packet::isResponse(), Packet::isSecure(), Packet::isWrite(), SnoopFilter::lookupRequest(), M5_VAR_USED, Packet::makeResponse(), BaseXBar::masterPorts, SimObject::name(), Packet::needsResponse(), outstandingCMO, Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::print(), Packet::satisfied(), Packet::setBlockCached(), sinkPacket(), BaseXBar::slavePorts, snoopFilter, system, BaseXBar::transDist, SnoopFilter::updateResponse(), and MemCmd::WriteClean.
Referenced by CoherentXBar::CoherentXBarSlavePort::recvAtomic(), and CoherentXBar::CoherentXBarSlavePort::recvAtomicBackdoor().
recvAtomicSnoop()
Tick CoherentXBar::recvAtomicSnoop (PacketPtr pkt, PortID master_port_id) protected
Definition at line 880 of file coherent_xbar.cc.
References Clocked::clockPeriod(), Packet::cmd, DPRINTF, forwardAtomic(), Packet::getSize(), Packet::hasData(), MemCmd::InvalidCmd, InvalidPortID, Packet::isResponse(), SnoopFilter::lookupSnoop(), BaseXBar::masterPorts, SimObject::name(), Packet::payloadDelay, Packet::print(), snoopFilter, snoops, and snoopTraffic.
Referenced by forwardTiming(), and CoherentXBar::CoherentXBarMasterPort::recvAtomicSnoop().
recvFunctional()
void CoherentXBar::recvFunctional (PacketPtr pkt, PortID slave_port_id) protected
Function called by the port when the crossbar is recieving a Functional transaction.
Definition at line 992 of file coherent_xbar.cc.
References System::bypassCaches(), DPRINTF, BaseXBar::findPort(), forwardFunctional(), Packet::getAddrRange(), Packet::isPrint(), Packet::isResponse(), Packet::makeResponse(), BaseXBar::masterPorts, SimObject::name(), Packet::needsResponse(), MipsISA::p, Packet::print(), BaseXBar::slavePorts, and system.
Referenced by CoherentXBar::CoherentXBarSlavePort::recvFunctional().
recvFunctionalSnoop()
void CoherentXBar::recvFunctionalSnoop (PacketPtr pkt, PortID master_port_id) protected
Function called by the port when the crossbar is recieving a functional snoop transaction.
Definition at line 1027 of file coherent_xbar.cc.
References DPRINTF, forwardFunctional(), InvalidPortID, Packet::isPrint(), Packet::makeResponse(), BaseXBar::masterPorts, SimObject::name(), Packet::needsResponse(), MipsISA::p, Packet::print(), and BaseXBar::slavePorts.
Referenced by forwardAtomic(), and CoherentXBar::CoherentXBarMasterPort::recvFunctionalSnoop().
recvReqRetry()
void CoherentXBar::recvReqRetry (PortID master_port_id) protected
Definition at line 720 of file coherent_xbar.cc.
References reqLayers.
Referenced by CoherentXBar::CoherentXBarMasterPort::recvReqRetry().
recvTimingReq()
bool CoherentXBar::recvTimingReq (PacketPtr pkt, PortID slave_port_id) protected
Definition at line 147 of file coherent_xbar.cc.
References addr, System::bypassCaches(), Packet::cacheResponding(), BaseXBar::calcPacketTiming(), Packet::clearWriteThrough(), Clocked::clockEdge(), Clocked::clockPeriod(), Packet::cmd, Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), SnoopFilter::finishRequest(), BaseXBar::forwardLatency, forwardPacket(), forwardTiming(), BaseXBar::frontendLatency, Packet::getAddr(), Packet::getAddrRange(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, Packet::id, InvalidPortID, Packet::isClean(), isDestination(), Packet::isEviction(), Packet::isExpressSnoop(), Packet::isSecure(), Packet::isWrite(), SnoopFilter::lookupRequest(), Packet::makeResponse(), BaseXBar::masterPorts, maxOutstandingSnoopCheck, maxRoutingTableSizeCheck, Port::name(), SimObject::name(), Packet::needsResponse(), outstandingCMO, outstandingSnoop, panic_if, Packet::payloadDelay, pendingDelete, BaseXBar::pktCount, BaseXBar::pktSize, Packet::print(), Packet::req, reqLayers, respLayers, BaseXBar::routeTo, Packet::satisfied(), Packet::setBlockCached(), Packet::setExpressSnoop(), sinkPacket(), BaseXBar::slavePorts, Packet::snoopDelay, snoopFilter, snoops, snoopTraffic, system, BaseXBar::transDist, SnoopFilter::updateResponse(), and MemCmd::WriteClean.
Referenced by CoherentXBar::CoherentXBarSlavePort::recvTimingReq().
recvTimingResp()
bool CoherentXBar::recvTimingResp (PacketPtr pkt, PortID master_port_id) protected
Definition at line 444 of file coherent_xbar.cc.
References System::bypassCaches(), BaseXBar::calcPacketTiming(), Clocked::clockEdge(), Clocked::clockPeriod(), Packet::cmdToIndex(), curTick(), DPRINTF, Packet::getSize(), Packet::hasData(), Packet::headerDelay, InvalidPortID, BaseXBar::masterPorts, Port::name(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::print(), Packet::req, respLayers, BaseXBar::responseLatency, BaseXBar::routeTo, BaseXBar::slavePorts, snoopFilter, system, BaseXBar::transDist, and SnoopFilter::updateResponse().
Referenced by CoherentXBar::CoherentXBarMasterPort::recvTimingResp().
recvTimingSnoopReq()
void CoherentXBar::recvTimingSnoopReq (PacketPtr pkt, PortID master_port_id) protected
Definition at line 506 of file coherent_xbar.cc.
References Packet::cacheResponding(), BaseXBar::calcPacketTiming(), Clocked::clockPeriod(), Packet::cmdToIndex(), DPRINTF, BaseXBar::findPort(), BaseXBar::forwardLatency, forwardTiming(), Packet::getAddrRange(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, InvalidPortID, Packet::isExpressSnoop(), SnoopFilter::lookupSnoop(), BaseXBar::masterPorts, SimObject::name(), Packet::print(), Packet::req, BaseXBar::routeTo, Packet::snoopDelay, snoopFilter, snoops, snoopTraffic, and BaseXBar::transDist.
Referenced by CoherentXBar::CoherentXBarMasterPort::recvTimingSnoopReq().
recvTimingSnoopResp()
bool CoherentXBar::recvTimingSnoopResp (PacketPtr pkt, PortID slave_port_id) protected
Definition at line 566 of file coherent_xbar.cc.
References BaseXBar::calcPacketTiming(), Clocked::clockEdge(), Clocked::clockPeriod(), Packet::cmdToIndex(), curTick(), DPRINTF, Packet::getSize(), Packet::hasData(), Packet::headerDelay, InvalidPortID, Packet::isExpressSnoop(), M5_VAR_USED, BaseXBar::masterPorts, Port::name(), outstandingSnoop, Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::print(), Packet::req, respLayers, BaseXBar::responseLatency, BaseXBar::routeTo, BaseXBar::slavePorts, snoopFilter, snoopLayers, snoopResponseLatency, snoopRespPorts, snoops, snoopTraffic, BaseXBar::transDist, SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
Referenced by CoherentXBar::CoherentXBarSlavePort::recvTimingSnoopResp().
regStats()
void CoherentXBar::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 1109 of file coherent_xbar.cc.
References CoherentXBar(), Stats::Distribution::init(), BaseXBar::regStats(), snoopFanout, and snoopPorts.
sinkPacket()
bool CoherentXBar::sinkPacket (const PacketPtr pkt) const protected
Determine if the crossbar should sink the packet, as opposed to forwarding it, or responding.
Definition at line 1070 of file coherent_xbar.cc.
References Packet::cacheResponding(), Packet::isBlockCached(), Packet::isCleanEviction(), Packet::isRead(), Packet::isWrite(), Packet::needsResponse(), Packet::needsWritable(), pointOfCoherency, and Packet::responderHadWritable().
Referenced by forwardAtomic(), recvAtomicBackdoor(), and recvTimingReq().
Member Data Documentation
maxOutstandingSnoopCheck
const unsigned int CoherentXBar::maxOutstandingSnoopCheck protected
Maximum number of outstading snoops sanity check.
Definition at line 285 of file coherent_xbar.hh.
Referenced by recvTimingReq().
maxRoutingTableSizeCheck
const unsigned int CoherentXBar::maxRoutingTableSizeCheck protected
Maximum routing table size sanity check.
Definition at line 288 of file coherent_xbar.hh.
Referenced by recvTimingReq().
outstandingCMO
std::unordered_map<PacketId, PacketPtr> CoherentXBar::outstandingCMO protected
Store the outstanding cache maintenance that we are expecting snoop responses from so we can determine when we received all snoop responses and if any of the agents satisfied the request.
Definition at line 269 of file coherent_xbar.hh.
Referenced by recvAtomicBackdoor(), and recvTimingReq().
outstandingSnoop
std::unordered_set<RequestPtr> CoherentXBar::outstandingSnoop protected
Store the outstanding requests that we are expecting snoop responses from so we can determine which snoop responses we generated and which ones were merely forwarded.
Definition at line 262 of file coherent_xbar.hh.
Referenced by recvTimingReq(), and recvTimingSnoopResp().
pendingDelete
std::unique_ptr<Packet> CoherentXBar::pendingDelete protected
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Definition at line 300 of file coherent_xbar.hh.
Referenced by recvTimingReq().
pointOfCoherency
const bool CoherentXBar::pointOfCoherency protected
Is this crossbar the point of coherency?
Definition at line 291 of file coherent_xbar.hh.
Referenced by forwardPacket(), isDestination(), and sinkPacket().
pointOfUnification
const bool CoherentXBar::pointOfUnification protected
Is this crossbar the point of unification?
Definition at line 294 of file coherent_xbar.hh.
Referenced by isDestination().
reqLayers
std::vector<ReqLayer*> CoherentXBar::reqLayers protected
Declare the layers of this crossbar, one vector for requests, one for responses, and one for snoop responses.
Definition at line 81 of file coherent_xbar.hh.
Referenced by CoherentXBar(), recvReqRetry(), recvTimingReq(), and ~CoherentXBar().
respLayers
std::vector<RespLayer*> CoherentXBar::respLayers protected
Definition at line 82 of file coherent_xbar.hh.
Referenced by CoherentXBar(), recvTimingReq(), recvTimingResp(), recvTimingSnoopResp(), and ~CoherentXBar().
snoopFanout
Stats::Distribution CoherentXBar::snoopFanout protected
Definition at line 423 of file coherent_xbar.hh.
Referenced by forwardAtomic(), forwardTiming(), and regStats().
snoopFilter
SnoopFilter* CoherentXBar::snoopFilter protected
A snoop filter that tracks cache line residency and can restrict the broadcast needed for probes.
NULL denotes an absent filter.
Definition at line 279 of file coherent_xbar.hh.
Referenced by forwardAtomic(), init(), recvAtomicBackdoor(), recvAtomicSnoop(), recvTimingReq(), recvTimingResp(), recvTimingSnoopReq(), and recvTimingSnoopResp().
snoopLayers
std::vector<SnoopRespLayer*> CoherentXBar::snoopLayers protected
Definition at line 83 of file coherent_xbar.hh.
Referenced by CoherentXBar(), recvTimingSnoopResp(), and ~CoherentXBar().
snoopPorts
std::vector<QueuedSlavePort*> CoherentXBar::snoopPorts protected
Definition at line 255 of file coherent_xbar.hh.
Referenced by forwardFunctional(), init(), and regStats().
snoopResponseLatency
const Cycles CoherentXBar::snoopResponseLatency protected
Cycles of snoop response latency.
Definition at line 282 of file coherent_xbar.hh.
Referenced by recvTimingSnoopResp().
snoopRespPorts
std::vector<SnoopRespPort*> CoherentXBar::snoopRespPorts protected
Definition at line 253 of file coherent_xbar.hh.
Referenced by CoherentXBar(), recvTimingSnoopResp(), and ~CoherentXBar().
snoops
Stats::Scalar CoherentXBar::snoops protected
Definition at line 421 of file coherent_xbar.hh.
Referenced by recvAtomicSnoop(), recvTimingReq(), recvTimingSnoopReq(), and recvTimingSnoopResp().
snoopTraffic
Stats::Scalar CoherentXBar::snoopTraffic protected
Definition at line 422 of file coherent_xbar.hh.
Referenced by recvAtomicSnoop(), recvTimingReq(), recvTimingSnoopReq(), and recvTimingSnoopResp().
system
System* CoherentXBar::system protected
Keep a pointer to the system to be allow to querying memory system properties.
Definition at line 275 of file coherent_xbar.hh.
Referenced by forwardAtomic(), forwardFunctional(), forwardTiming(), recvAtomicBackdoor(), recvFunctional(), recvTimingReq(), and recvTimingResp().
The documentation for this class was generated from the following files:
mem/coherent_xbar.hh
mem/coherent_xbar.cc