gem5: RandomGen Class Reference
RandomGen Class Reference
The random generator is similar to the linear one, but does not generate sequential addresses.
#include <random_gen.hh>
Public Member Functions
RandomGen (SimObject &obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
Create a random address sequence generator.
void enter ()
Enter this generator state.
PacketPtr getNextPacket ()
Get the next generated packet.
Tick nextPacketTick (bool elastic, Tick delay) const
Determine the tick when the next packet is available.
Public Member Functions inherited from StochasticGen
StochasticGen (SimObject &obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
Public Member Functions inherited from BaseGen
BaseGen (SimObject &obj, MasterID master_id, Tick _duration)
Create a base generator.
virtual ~BaseGen ()
std::string name () const
Get the name, useful for DPRINTFs.
virtual void exit ()
Exit this generator state.
Protected Attributes
Addr dataManipulated
Counter to determine the amount of data manipulated.
Protected Attributes inherited from StochasticGen
const Addr startAddr
Start of address range.
const Addr endAddr
End of address range.
const Addr blocksize
Blocksize and address increment.
const Addr cacheLineSize
Cache line size in the simulated system.
const Tick minPeriod
Request generation period.
const Tick maxPeriod
const uint8_t readPercent
Percent of generated transactions that should be reads.
const Addr dataLimit
Maximum amount of data to manipulate.
Protected Attributes inherited from BaseGen
const std::string _name
Name to use for status and debug printing.
const MasterID masterID
The MasterID used for generating requests.
Additional Inherited Members
Public Attributes inherited from BaseGen
const Tick duration
Time to spend in this state.
Protected Member Functions inherited from BaseGen
PacketPtr getPacket (Addr addr, unsigned size, const MemCmd &cmd, Request::FlagsType flags=0)
Generate a new request and associated packet.
Detailed Description
The random generator is similar to the linear one, but does not generate sequential addresses.
Instead it randomly picks an address in the range, aligned to the block size.
Definition at line 62 of file random_gen.hh.
Constructor & Destructor Documentation
RandomGen()
RandomGen::RandomGen (SimObject & obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit) inline
Create a random address sequence generator.
Set min_period == max_period for a fixed inter-transaction time.
Parameters
gen Traffic generator owning this sequence generator
_duration duration of this state before transitioning
start_addr Start address
end_addr End address
_blocksize Size used for transactions injected
min_period Lower limit of random inter-transaction time
max_period Upper limit of random inter-transaction time
read_percent Percent of transactions that are reads
data_limit Upper limit on how much data to read/write
Definition at line 82 of file random_gen.hh.
References enter(), getNextPacket(), and nextPacketTick().
Member Function Documentation
enter()
void RandomGen::enter () virtual
Enter this generator state.
Implements BaseGen.
Definition at line 52 of file random_gen.cc.
References dataManipulated.
Referenced by RandomGen().
getNextPacket()
PacketPtr RandomGen::getNextPacket () virtual
Get the next generated packet.
Returns
A packet to be sent at the current tick
Implements BaseGen.
Definition at line 59 of file random_gen.cc.
References addr, StochasticGen::blocksize, dataManipulated, DPRINTF, StochasticGen::endAddr, BaseGen::getPacket(), Random::random(), random_mt, StochasticGen::readPercent, MemCmd::ReadReq, StochasticGen::startAddr, and MemCmd::WriteReq.
Referenced by RandomGen().
nextPacketTick()
Tick RandomGen::nextPacketTick (bool elastic, Tick delay) const virtual
Determine the tick when the next packet is available.
MaxTick means that there will not be any further packets in the current activation cycle of the generator.
Parameters
elastic should the injection respond to flow control or not
delay time the previous packet spent waiting
Returns
next tick when a packet is available
Implements BaseGen.
Definition at line 86 of file random_gen.cc.
References curTick(), StochasticGen::dataLimit, dataManipulated, DPRINTF, StochasticGen::maxPeriod, MaxTick, StochasticGen::minPeriod, Random::random(), random_mt, and sc_core::wait().
Referenced by RandomGen().
Member Data Documentation
dataManipulated
Addr RandomGen::dataManipulated protected
Counter to determine the amount of data manipulated.
Used to determine if we should continue generating requests.
Definition at line 106 of file random_gen.hh.
Referenced by enter(), getNextPacket(), DramGen::getNextPacket(), DramRotGen::getNextPacket(), and nextPacketTick().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/random_gen.hh
cpu/testers/traffic_gen/random_gen.cc