gem5: sc_dt::sc_fxval_fast_observer Class Reference
sc_dt::sc_fxval_fast_observer Class Reference
#include <sc_fxval_observer.hh>
Public Member Functions
virtual void construct (const sc_fxval_fast &)
virtual void destruct (const sc_fxval_fast &)
virtual void read (const sc_fxval_fast &)
virtual void write (const sc_fxval_fast &)
Static Public Attributes
static sc_fxval_fast_observer *(* default_observer)()
Protected Member Functions
sc_fxval_fast_observer ()
virtual ~sc_fxval_fast_observer ()
Detailed Description
Definition at line 133 of file sc_fxval_observer.hh.
Constructor & Destructor Documentation
sc_fxval_fast_observer()
sc_dt::sc_fxval_fast_observer::sc_fxval_fast_observer () inline protected
Definition at line 136 of file sc_fxval_observer.hh.
~sc_fxval_fast_observer()
virtual sc_dt::sc_fxval_fast_observer::~sc_fxval_fast_observer () inline protected virtual
Definition at line 137 of file sc_fxval_observer.hh.
References sc_dt::sc_fxval_observer::construct(), sc_dt::sc_fxval_observer::destruct(), sc_dt::sc_fxval_observer::read(), and sc_dt::sc_fxval_observer::write().
Member Function Documentation
construct()
void sc_dt::sc_fxval_fast_observer::construct (const sc_fxval_fast &) inline virtual
Definition at line 171 of file sc_fxval_observer.hh.
destruct()
void sc_dt::sc_fxval_fast_observer::destruct (const sc_fxval_fast &) inline virtual
Definition at line 172 of file sc_fxval_observer.hh.
read()
void sc_dt::sc_fxval_fast_observer::read (const sc_fxval_fast &) inline virtual
Definition at line 173 of file sc_fxval_observer.hh.
write()
void sc_dt::sc_fxval_fast_observer::write (const sc_fxval_fast &) inline virtual
Definition at line 174 of file sc_fxval_observer.hh.
Member Data Documentation
default_observer
sc_fxval_fast_observer *(* sc_dt::sc_fxval_fast_observer::default_observer)()=0 static
Definition at line 145 of file sc_fxval_observer.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxval_observer.hh
systemc/dt/fx/sc_fxval_observer.cc