gem5: tlm_utils::tlm_quantumkeeper Class Reference
tlm_utils::tlm_quantumkeeper Class Reference
#include <tlm_quantumkeeper.h>
Public Member Functions
tlm_quantumkeeper ()
virtual ~tlm_quantumkeeper ()
virtual void inc (const sc_core::sc_time &t)
virtual void set (const sc_core::sc_time &t)
virtual bool need_sync () const
virtual void sync ()
void set_and_sync (const sc_core::sc_time &t)
virtual void reset ()
virtual sc_core::sc_time get_current_time () const
virtual sc_core::sc_time get_local_time () const
Static Public Member Functions
static void set_global_quantum (const sc_core::sc_time &t)
static const sc_core::sc_time & get_global_quantum ()
Protected Member Functions
virtual sc_core::sc_time compute_local_quantum ()
Protected Attributes
sc_core::sc_time m_next_sync_point
sc_core::sc_time m_local_time
Detailed Description
Definition at line 33 of file tlm_quantumkeeper.h.
Constructor & Destructor Documentation
tlm_quantumkeeper()
tlm_utils::tlm_quantumkeeper::tlm_quantumkeeper () inline
Definition at line 56 of file tlm_quantumkeeper.h.
~tlm_quantumkeeper()
virtual tlm_utils::tlm_quantumkeeper::~tlm_quantumkeeper () inline virtual
Definition at line 60 of file tlm_quantumkeeper.h.
Member Function Documentation
compute_local_quantum()
virtual sc_core::sc_time tlm_utils::tlm_quantumkeeper::compute_local_quantum () inline protected virtual
Definition at line 140 of file tlm_quantumkeeper.h.
References tlm::tlm_global_quantum::compute_local_quantum(), and tlm::tlm_global_quantum::instance().
Referenced by reset().
get_current_time()
virtual sc_core::sc_time tlm_utils::tlm_quantumkeeper::get_current_time () const inline virtual
Definition at line 117 of file tlm_quantumkeeper.h.
References m_local_time, and sc_core::sc_time_stamp().
Referenced by CoreDecouplingLTInitiator::logEndTransaction(), and CoreDecouplingLTInitiator::logStartTransation().
get_global_quantum()
static const sc_core::sc_time& tlm_utils::tlm_quantumkeeper::get_global_quantum () inline static
Definition at line 50 of file tlm_quantumkeeper.h.
References tlm::tlm_global_quantum::get(), and tlm::tlm_global_quantum::instance().
get_local_time()
virtual sc_core::sc_time tlm_utils::tlm_quantumkeeper::get_local_time () const inline virtual
Definition at line 126 of file tlm_quantumkeeper.h.
References m_local_time.
Referenced by CoreDecouplingLTInitiator::logEndTransaction(), CoreDecouplingLTInitiator::logStartTransation(), and CoreDecouplingLTInitiator::run().
inc()
virtual void tlm_utils::tlm_quantumkeeper::inc (const sc_core::sc_time & t) inline virtual
Definition at line 65 of file tlm_quantumkeeper.h.
References m_local_time, and ArmISA::t.
need_sync()
virtual bool tlm_utils::tlm_quantumkeeper::need_sync () const inline virtual
Definition at line 76 of file tlm_quantumkeeper.h.
References m_local_time, m_next_sync_point, and sc_core::sc_time_stamp().
Referenced by CoreDecouplingLTInitiator::run(), and set_and_sync().
reset()
virtual void tlm_utils::tlm_quantumkeeper::reset () inline virtual
Definition at line 106 of file tlm_quantumkeeper.h.
References compute_local_quantum(), m_local_time, m_next_sync_point, sc_core::sc_time_stamp(), and sc_core::SC_ZERO_TIME.
Referenced by CoreDecouplingLTInitiator::CoreDecouplingLTInitiator(), and sync().
set()
virtual void tlm_utils::tlm_quantumkeeper::set (const sc_core::sc_time & t) inline virtual
Definition at line 70 of file tlm_quantumkeeper.h.
References m_local_time, and ArmISA::t.
Referenced by CoreDecouplingLTInitiator::run().
set_and_sync()
void tlm_utils::tlm_quantumkeeper::set_and_sync (const sc_core::sc_time & t) inline
Definition at line 94 of file tlm_quantumkeeper.h.
References need_sync(), sync(), and ArmISA::t.
set_global_quantum()
static void tlm_utils::tlm_quantumkeeper::set_global_quantum (const sc_core::sc_time & t) inline static
Definition at line 44 of file tlm_quantumkeeper.h.
References tlm::tlm_global_quantum::instance(), and tlm::tlm_global_quantum::set().
Referenced by CoreDecouplingLTInitiator::CoreDecouplingLTInitiator().
sync()
virtual void tlm_utils::tlm_quantumkeeper::sync () inline virtual
Definition at line 85 of file tlm_quantumkeeper.h.
References m_local_time, reset(), and sc_core::wait().
Referenced by CoreDecouplingLTInitiator::run(), and set_and_sync().
Member Data Documentation
m_local_time
sc_core::sc_time tlm_utils::tlm_quantumkeeper::m_local_time protected
Definition at line 147 of file tlm_quantumkeeper.h.
Referenced by get_current_time(), get_local_time(), inc(), need_sync(), reset(), set(), and sync().
m_next_sync_point
sc_core::sc_time tlm_utils::tlm_quantumkeeper::m_next_sync_point protected
Definition at line 146 of file tlm_quantumkeeper.h.
Referenced by need_sync(), and reset().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/tlm_quantumkeeper.h