gem5: sc_core::sc_mutex Class Reference
sc_core::sc_mutex Class Reference
#include <sc_mutex.hh>
Public Member Functions
sc_mutex ()
sc_mutex (const char *name)
virtual int lock ()
virtual int trylock ()
virtual int unlock ()
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Member Functions
sc_mutex (const sc_mutex &)
sc_mutex & operator= (const sc_mutex &)
Private Attributes
sc_process_handle holder
sc_gem5::InternalScEvent unlockEvent
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_mutex_if
sc_mutex_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
Definition at line 41 of file sc_mutex.hh.
Constructor & Destructor Documentation
sc_mutex() [1/3]
sc_core::sc_mutex::sc_mutex ()
Definition at line 37 of file sc_mutex.cc.
sc_mutex() [2/3]
sc_core::sc_mutex::sc_mutex (const char * name) explicit
Definition at line 41 of file sc_mutex.cc.
sc_mutex() [3/3]
sc_core::sc_mutex::sc_mutex (const sc_mutex &) inline private
Definition at line 55 of file sc_mutex.hh.
Member Function Documentation
kind()
virtual const char* sc_core::sc_mutex::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 51 of file sc_mutex.hh.
lock()
int sc_core::sc_mutex::lock () virtual
Implements sc_core::sc_mutex_if.
Definition at line 46 of file sc_mutex.cc.
References trylock(), unlockEvent, and sc_core::wait().
Referenced by tlm::tlm_transport_to_master< REQ, RSP >::transport().
operator=()
sc_mutex& sc_core::sc_mutex::operator= (const sc_mutex &) inline private
Definition at line 56 of file sc_mutex.hh.
trylock()
int sc_core::sc_mutex::trylock () virtual
Implements sc_core::sc_mutex_if.
Definition at line 54 of file sc_mutex.cc.
References sc_gem5::Scheduler::current(), holder, sc_gem5::scheduler, and sc_core::sc_process_handle::valid().
Referenced by lock().
unlock()
int sc_core::sc_mutex::unlock () virtual
Implements sc_core::sc_mutex_if.
Definition at line 63 of file sc_mutex.cc.
References holder, sc_core::sc_event::notify(), sc_gem5::scheduler, and unlockEvent.
Referenced by tlm::tlm_transport_to_master< REQ, RSP >::transport().
Member Data Documentation
holder
sc_process_handle sc_core::sc_mutex::holder private
Definition at line 58 of file sc_mutex.hh.
Referenced by trylock(), and unlock().
unlockEvent
sc_gem5::InternalScEvent sc_core::sc_mutex::unlockEvent private
Definition at line 59 of file sc_mutex.hh.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following files:
systemc/ext/channel/sc_mutex.hh
systemc/channel/sc_mutex.cc