gem5: sc_dt::sc_bitref_r< T > Class Template Reference
sc_dt::sc_bitref_r< T > Class Template Reference
#include <sc_bit_proxies.hh>
Public Types
typedef T::traits_type traits_type
typedef traits_type::bit_type bit_type
typedef traits_type::value_type value_type
Public Member Functions
sc_bitref_r (const T &obj_, int index_)
sc_bitref_r (const sc_bitref_r< T > &a)
sc_bitref_r< T > * clone () const
bit_type operator~ () const
operator bit_type () const
value_type value () const
bool is_01 () const
bool to_bool () const
char to_char () const
int length () const
int size () const
value_type get_bit (int n) const
sc_digit get_word (int i) const
sc_digit get_cword (int i) const
void print (::std::ostream &os=::std::cout) const
Protected Attributes
T & m_obj
int m_index
Private Member Functions
sc_bitref_r ()
sc_bitref_r< T > & operator= (const sc_bitref_r< T > &)
Friends
class sc_bv_base
class sc_lv_base
Detailed Description
template<class T>
class sc_dt::sc_bitref_r< T >
Definition at line 44 of file sc_bit_proxies.hh.
Member Typedef Documentation
bit_type
template<class T> typedef traits_type::bit_type sc_dt::sc_bitref_r< T >::bit_type
Definition at line 100 of file sc_bit_proxies.hh.
traits_type
template<class T> typedef T::traits_type sc_dt::sc_bitref_r< T >::traits_type
Definition at line 99 of file sc_bit_proxies.hh.
value_type
template<class T> typedef traits_type::value_type sc_dt::sc_bitref_r< T >::value_type
Definition at line 101 of file sc_bit_proxies.hh.
Constructor & Destructor Documentation
sc_bitref_r() [1/3]
template<class T> sc_dt::sc_bitref_r< T >::sc_bitref_r (const T & obj_, int index_) inline
Definition at line 104 of file sc_bit_proxies.hh.
sc_bitref_r() [2/3]
template<class T> sc_dt::sc_bitref_r< T >::sc_bitref_r (const sc_bitref_r< T > & a) inline
Definition at line 109 of file sc_bit_proxies.hh.
sc_bitref_r() [3/3]
template<class T> sc_dt::sc_bitref_r< T >::sc_bitref_r () private
Member Function Documentation
clone()
template<class T> sc_bitref_r<T>* sc_dt::sc_bitref_r< T >::clone () const inline
Definition at line 113 of file sc_bit_proxies.hh.
Referenced by sc_dt::concat(), and sc_dt::operator,().
get_bit()
template<class T > sc_bitref_r< T >::value_type sc_dt::sc_bitref_r< T >::get_bit (int n) const inline
Definition at line 1734 of file sc_bit_proxies.hh.
get_cword()
template<class T > sc_digit sc_dt::sc_bitref_r< T >::get_cword (int i) const inline
Definition at line 1758 of file sc_bit_proxies.hh.
get_word()
template<class T > sc_digit sc_dt::sc_bitref_r< T >::get_word (int i) const inline
Definition at line 1746 of file sc_bit_proxies.hh.
is_01()
template<class T> bool sc_dt::sc_bitref_r< T >::is_01 () const inline
Definition at line 129 of file sc_bit_proxies.hh.
length()
template<class T> int sc_dt::sc_bitref_r< T >::length () const inline
Definition at line 134 of file sc_bit_proxies.hh.
operator bit_type()
template<class T> sc_dt::sc_bitref_r< T >::operator bit_type () const inline
Definition at line 125 of file sc_bit_proxies.hh.
operator=()
template<class T> sc_bitref_r<T>& sc_dt::sc_bitref_r< T >::operator= (const sc_bitref_r< T > &) private
operator~()
template<class T> bit_type sc_dt::sc_bitref_r< T >::operator~ () const inline
Definition at line 119 of file sc_bit_proxies.hh.
print()
template<class T> void sc_dt::sc_bitref_r< T >::print (::std::ostream & os = ::std::cout) const inline
Definition at line 143 of file sc_bit_proxies.hh.
size()
template<class T> int sc_dt::sc_bitref_r< T >::size () const inline
Definition at line 135 of file sc_bit_proxies.hh.
to_bool()
template<class T> bool sc_dt::sc_bitref_r< T >::to_bool () const inline
Definition at line 130 of file sc_bit_proxies.hh.
Referenced by sc_dt::sc_bitref_conv_r< T, sc_proxy_traits< sc_bv_base > >::operator!().
to_char()
template<class T> char sc_dt::sc_bitref_r< T >::to_char () const inline
Definition at line 131 of file sc_bit_proxies.hh.
value()
template<class T> value_type sc_dt::sc_bitref_r< T >::value () const inline
Definition at line 128 of file sc_bit_proxies.hh.
Referenced by sc_dt::operator!=(), sc_dt::operator&(), sc_dt::sc_bitref< X >::operator=(), sc_dt::operator==(), sc_dt::operator^(), sc_dt::sc_bitref< X >::operator^=(), sc_dt::operator|(), and sc_dt::sc_bitref< X >::operator|=().
Friends And Related Function Documentation
sc_bv_base
template<class T> friend class sc_bv_base friend
Definition at line 94 of file sc_bit_proxies.hh.
sc_lv_base
template<class T> friend class sc_lv_base friend
Definition at line 95 of file sc_bit_proxies.hh.
Member Data Documentation
m_index
template<class T> int sc_dt::sc_bitref_r< T >::m_index protected
Definition at line 147 of file sc_bit_proxies.hh.
m_obj
template<class T> T& sc_dt::sc_bitref_r< T >::m_obj protected
Definition at line 146 of file sc_bit_proxies.hh.
The documentation for this class was generated from the following file:
systemc/ext/dt/bit/sc_bit_proxies.hh