gem5: Stats::Text Class Reference
Stats::Text Class Reference
#include <text.hh>
Public Member Functions
Text ()
Text (std::ostream &stream)
Text (const std::string &file)
~Text ()
void open (std::ostream &stream)
void open (const std::string &file)
std::string statName (const std::string &name) const
void visit (const ScalarInfo &info) override
void visit (const VectorInfo &info) override
void visit (const DistInfo &info) override
void visit (const VectorDistInfo &info) override
void visit (const Vector2dInfo &info) override
void visit (const FormulaInfo &info) override
void visit (const SparseHistInfo &info) override
void beginGroup (const char *name) override
void endGroup () override
bool valid () const override
void begin () override
void end () override
Public Member Functions inherited from Stats::Output
virtual ~Output ()
Public Attributes
bool descriptions
Protected Member Functions
bool noOutput (const Info &info)
Protected Attributes
bool mystream
std::ostream * stream
std::stack< std::string > path
Detailed Description
Definition at line 56 of file text.hh.
Constructor & Destructor Documentation
Text() [1/3]
Stats::Text::Text ()
Definition at line 99 of file text.cc.
Text() [2/3]
Stats::Text::Text (std::ostream & stream)
Definition at line 104 of file text.cc.
References open().
Text() [3/3]
Stats::Text::Text (const std::string & file)
Definition at line 110 of file text.cc.
References open().
~Text()
Stats::Text::~Text ()
Definition at line 117 of file text.cc.
References mystream, and stream.
Member Function Documentation
begin()
void Stats::Text::begin () override virtual
Implements Stats::Output.
Definition at line 156 of file text.cc.
References ccprintf(), and stream.
beginGroup()
void Stats::Text::beginGroup (const char * name) override virtual
Implements Stats::Output.
Definition at line 178 of file text.cc.
References csprintf(), name(), and path.
end()
void Stats::Text::end () override virtual
Implements Stats::Output.
Definition at line 162 of file text.cc.
References ccprintf(), and stream.
endGroup()
void Stats::Text::endGroup () override virtual
Implements Stats::Output.
Definition at line 188 of file text.cc.
References path.
noOutput()
bool Stats::Text::noOutput (const Info & info) protected
Definition at line 195 of file text.cc.
References Stats::display, Stats::Info::flags, Flags< T >::isSet(), Stats::Info::prereq, and Stats::Info::zero().
open() [1/2]
void Stats::Text::open (std::ostream & stream)
Definition at line 126 of file text.cc.
References fatal, mystream, panic, stream, and valid().
Referenced by Stats::initText(), and Text().
open() [2/2]
void Stats::Text::open (const std::string & file)
Definition at line 138 of file text.cc.
References fatal, mystream, panic, stream, and valid().
statName()
std::string Stats::Text::statName (const std::string & name) const
Definition at line 169 of file text.cc.
References csprintf(), name(), and path.
Referenced by Stats::DistPrint::DistPrint(), Stats::DistPrint::init(), and Stats::SparseHistPrint::init().
valid()
bool Stats::Text::valid () const override virtual
Implements Stats::Output.
Definition at line 150 of file text.cc.
References stream.
Referenced by open().
visit() [1/7]
void Stats::Text::visit (const ScalarInfo & info) override virtual
Implements Stats::Output.
Definition at line 546 of file text.cc.
References Stats::ScalarPrint::cdf, Stats::Info::desc, Stats::ScalarPrint::desc, Stats::ScalarPrint::descriptions, Stats::DistPrint::descriptions, Stats::Info::flags, Stats::ScalarPrint::flags, Stats::Info::name, Stats::ScalarPrint::name, NAN, Stats::ScalarPrint::pdf, Stats::Info::precision, Stats::ScalarPrint::precision, Stats::ScalarInfo::result(), and Stats::ScalarPrint::value.
visit() [2/7]
void Stats::Text::visit (const VectorInfo & info) override virtual
Implements Stats::Output.
Definition at line 565 of file text.cc.
References Stats::Info::desc, Stats::VectorPrint::desc, Stats::VectorPrint::descriptions, Stats::DistPrint::descriptions, Stats::Info::flags, Stats::VectorPrint::flags, Stats::VectorPrint::forceSubnames, ArmISA::i, Stats::Info::name, Stats::VectorPrint::name, Stats::Info::precision, Stats::VectorPrint::precision, Stats::VectorInfo::result(), Stats::Info::separatorString, Stats::VectorPrint::separatorString, Stats::VectorInfo::size(), Stats::VectorInfo::subdescs, Stats::VectorPrint::subdescs, Stats::VectorInfo::subnames, Stats::VectorPrint::subnames, Stats::VectorInfo::total(), Stats::VectorPrint::total, and Stats::VectorPrint::vec.
visit() [3/7]
void Stats::Text::visit (const DistInfo & info) override virtual
Implements Stats::Output.
Definition at line 672 of file text.cc.
visit() [4/7]
void Stats::Text::visit (const VectorDistInfo & info) override virtual
Implements Stats::Output.
Definition at line 682 of file text.cc.
References ArmISA::i, and Stats::VectorDistInfo::size().
visit() [5/7]
void Stats::Text::visit (const Vector2dInfo & info) override virtual
Implements Stats::Output.
Definition at line 605 of file text.cc.
References Stats::Vector2dInfo::cvec, Stats::Info::desc, Stats::VectorPrint::desc, Stats::VectorPrint::descriptions, Stats::DistPrint::descriptions, Stats::Info::flags, Stats::VectorPrint::flags, Stats::VectorPrint::forceSubnames, ArmISA::i, Flags< T >::isSet(), ArmISA::j, Stats::Info::name, Stats::VectorPrint::name, Stats::Info::precision, Stats::VectorPrint::precision, Stats::Info::separatorString, Stats::VectorPrint::separatorString, Stats::Vector2dInfo::subnames, Stats::VectorPrint::subnames, sc_dt::to_string(), Stats::total, Stats::Vector2dInfo::total(), Stats::VectorPrint::total, Stats::VectorPrint::vec, Stats::Vector2dInfo::x, Stats::Vector2dInfo::y, and Stats::Vector2dInfo::y_subnames.
visit() [6/7]
void Stats::Text::visit (const FormulaInfo & info) override virtual
Implements Stats::Output.
Definition at line 694 of file text.cc.
visit() [7/7]
void Stats::Text::visit (const SparseHistInfo & info) override virtual
Implements Stats::Output.
Definition at line 769 of file text.cc.
Member Data Documentation
descriptions
bool Stats::Text::descriptions
Definition at line 69 of file text.hh.
Referenced by Stats::DistPrint::init(), Stats::SparseHistPrint::init(), Stats::initText(), Stats::ScalarPrint::operator()(), and Stats::VectorPrint::operator()().
mystream
bool Stats::Text::mystream protected
Definition at line 59 of file text.hh.
Referenced by open(), and ~Text().
path
std::stack<std::string> Stats::Text::path protected
Definition at line 63 of file text.hh.
Referenced by beginGroup(), endGroup(), and statName().
stream
std::ostream* Stats::Text::stream protected
Definition at line 60 of file text.hh.
Referenced by begin(), end(), open(), valid(), and ~Text().
The documentation for this class was generated from the following files:
base/stats/text.hh
base/stats/text.cc