gem5: Minor::ExecContext Class Reference
Minor::ExecContext Class Reference
ExecContext bears the exec_context interface for Minor.
#include <exec_context.hh>
Public Member Functions
ExecContext (MinorCPU &cpu_, SimpleThread &thread_, Execute &execute_, MinorDynInstPtr inst_)
~ExecContext ()
Fault initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >()) override
Initiate a timing memory read operation.
Fault writeMem (uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >()) override
For atomic-mode contexts, perform an atomic memory write operation.
Fault initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) override
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
RegVal readIntRegOperand (const StaticInst *si, int idx) override
Reads an integer register.
RegVal readFloatRegOperandBits (const StaticInst *si, int idx) override
Reads a floating point register in its binary format, instead of by value.
const TheISA::VecRegContainer & readVecRegOperand (const StaticInst *si, int idx) const override
Vector Register Interfaces.
TheISA::VecRegContainer & getWritableVecRegOperand (const StaticInst *si, int idx) override
Gets destination vector register operand for modification.
TheISA::VecElem readVecElemOperand (const StaticInst *si, int idx) const override
Vector Elem Interfaces.
const TheISA::VecPredRegContainer & readVecPredRegOperand (const StaticInst *si, int idx) const override
Predicate registers interface.
TheISA::VecPredRegContainer & getWritableVecPredRegOperand (const StaticInst *si, int idx) override
Gets destination predicate register operand for modification.
void setIntRegOperand (const StaticInst *si, int idx, RegVal val) override
Sets an integer register to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, RegVal val) override
Sets the bits of a floating point register of single width to a binary value.
void setVecRegOperand (const StaticInst *si, int idx, const TheISA::VecRegContainer &val) override
void setVecPredRegOperand (const StaticInst *si, int idx, const TheISA::VecPredRegContainer &val) override
void setVecElemOperand (const StaticInst *si, int idx, const TheISA::VecElem val) override
Sets a vector register to a value.
bool readPredicate () const override
void setPredicate (bool val) override
bool readMemAccPredicate () const override
void setMemAccPredicate (bool val) override
TheISA::PCState pcState () const override
void pcState (const TheISA::PCState &val) override
RegVal readMiscRegNoEffect (int misc_reg) const
RegVal readMiscReg (int misc_reg) override
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
void setMiscReg (int misc_reg, RegVal val) override
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
RegVal readMiscRegOperand (const StaticInst *si, int idx) override
void setMiscRegOperand (const StaticInst *si, int idx, RegVal val) override
void syscall (int64_t callnum, Fault *fault) override
Executes a syscall specified by the callnum.
ThreadContext * tcBase () override
Returns a pointer to the ThreadContext.
unsigned int readStCondFailures () const override
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int st_cond_failures) override
Sets the number of consecutive store conditional failures.
ContextID contextId ()
void demapPage (Addr vaddr, uint64_t asn) override
Invalidate a page in the DTLB and ITLB.
RegVal readCCRegOperand (const StaticInst *si, int idx) override
void setCCRegOperand (const StaticInst *si, int idx, RegVal val) override
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
BaseCPU * getCpuPtr ()
void armMonitor (Addr address) override
bool mwait (PacketPtr pkt) override
void mwaitAtomic (ThreadContext *tc) override
AddressMonitor * getAddrMonitor () override
ConstVecLane8 readVec8BitLaneOperand (const StaticInst *si, int idx) const override
Vector Register Lane Interfaces.
ConstVecLane16 readVec16BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 16bit operand.
ConstVecLane32 readVec32BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 32bit operand.
ConstVecLane64 readVec64BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 64bit operand.
template<typename LD >
void setVecLaneOperandT (const StaticInst *si, int idx, const LD &val)
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::TwoByte > &val) override
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::FourByte > &val) override
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::EightByte > &val) override
Public Member Functions inherited from ExecContext
virtual void setVecRegOperand (const StaticInst *si, int idx, const VecRegContainer &val)=0
Sets a destination vector register operand to a value.
virtual void setVecPredRegOperand (const StaticInst *si, int idx, const VecPredRegContainer &val)=0
Sets a destination predicate register operand to a value.
virtual Fault readMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Perform an atomic memory read operation.
virtual Fault amoMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
Public Attributes
MinorCPU & cpu
SimpleThread & thread
ThreadState object, provides all the architectural state.
Execute & execute
The execute stage so we can peek at its contents.
MinorDynInstPtr inst
Instruction for the benefit of memory operations and for PC.
Additional Inherited Members
Public Types inherited from ExecContext
typedef TheISA::PCState PCState
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
ExecContext bears the exec_context interface for Minor.
This nicely separates that interface from other classes such as Pipeline, MinorCPU and DynMinorInst and makes it easier to see what state is accessed by it.
Definition at line 74 of file exec_context.hh.
Constructor & Destructor Documentation
ExecContext()
Minor::ExecContext::ExecContext (MinorCPU & cpu_, SimpleThread & thread_, Execute & execute_, MinorDynInstPtr inst_) inline
Definition at line 88 of file exec_context.hh.
References DPRINTF, pcState(), SimpleThread::setFloatReg(), SimpleThread::setIntReg(), setMemAccPredicate(), setPredicate(), and AlphaISA::ZeroReg.
~ExecContext()
Minor::ExecContext::~ExecContext () inline
Definition at line 107 of file exec_context.hh.
References readMemAccPredicate(), and readPredicate().
Member Function Documentation
armMonitor()
void Minor::ExecContext::armMonitor (Addr address) inline override virtual
Implements ExecContext.
Definition at line 447 of file exec_context.hh.
References BaseCPU::armMonitor(), and getCpuPtr().
contextId()
ContextID Minor::ExecContext::contextId () inline
Definition at line 404 of file exec_context.hh.
References SimpleThread::contextId().
demapDataPage()
void Minor::ExecContext::demapDataPage (Addr vaddr, uint64_t asn) inline
Definition at line 438 of file exec_context.hh.
References BaseTLB::demapPage(), and SimpleThread::getDTBPtr().
demapInstPage()
void Minor::ExecContext::demapInstPage (Addr vaddr, uint64_t asn) inline
Definition at line 432 of file exec_context.hh.
References BaseTLB::demapPage(), and SimpleThread::getITBPtr().
demapPage()
void Minor::ExecContext::demapPage (Addr vaddr, uint64_t asn) inline override virtual
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 409 of file exec_context.hh.
References BaseTLB::demapPage(), SimpleThread::getDTBPtr(), and SimpleThread::getITBPtr().
getAddrMonitor()
AddressMonitor* Minor::ExecContext::getAddrMonitor () inline override virtual
Implements ExecContext.
Definition at line 456 of file exec_context.hh.
References BaseCPU::getCpuAddrMonitor(), and getCpuPtr().
getCpuPtr()
BaseCPU* Minor::ExecContext::getCpuPtr () inline
Definition at line 443 of file exec_context.hh.
References cpu.
Referenced by armMonitor(), getAddrMonitor(), mwait(), and mwaitAtomic().
getWritableVecPredRegOperand()
TheISA::VecPredRegContainer& Minor::ExecContext::getWritableVecPredRegOperand (const StaticInst * si, int idx) inline override virtual
Gets destination predicate register operand for modification.
Implements ExecContext.
Definition at line 192 of file exec_context.hh.
References StaticInst::destRegIdx(), SimpleThread::getWritableVecPredReg(), RegId::isVecPredReg(), and X86ISA::reg.
getWritableVecRegOperand()
TheISA::VecRegContainer& Minor::ExecContext::getWritableVecRegOperand (const StaticInst * si, int idx) inline override virtual
Gets destination vector register operand for modification.
Implements ExecContext.
Definition at line 168 of file exec_context.hh.
References StaticInst::destRegIdx(), SimpleThread::getWritableVecReg(), RegId::isVecReg(), and X86ISA::reg.
initiateMemAMO()
Fault Minor::ExecContext::initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) inline override virtual
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
Reimplemented from ExecContext.
Definition at line 135 of file exec_context.hh.
References Minor::Execute::getLSQ(), and Minor::LSQ::pushRequest().
initiateMemRead()
Fault Minor::ExecContext::initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>()) inline override virtual
Initiate a timing memory read operation.
Must be overridden for exec contexts that support timing memory mode. Not pure virtual since exec contexts that only support atomic memory mode need not override (though in that case this function should never be called).
Reimplemented from ExecContext.
Definition at line 114 of file exec_context.hh.
References Minor::Execute::getLSQ(), and Minor::LSQ::pushRequest().
mwait()
bool Minor::ExecContext::mwait (PacketPtr pkt) inline override virtual
Implements ExecContext.
Definition at line 450 of file exec_context.hh.
References getCpuPtr(), and BaseCPU::mwait().
mwaitAtomic()
void Minor::ExecContext::mwaitAtomic (ThreadContext * tc) inline override virtual
Implements ExecContext.
Definition at line 453 of file exec_context.hh.
References SimpleThread::dtb, getCpuPtr(), and BaseCPU::mwaitAtomic().
pcState() [1/2]
TheISA::PCState Minor::ExecContext::pcState () const inline override virtual
Implements ExecContext.
Definition at line 344 of file exec_context.hh.
References SimpleThread::pcState().
Referenced by ExecContext().
pcState() [2/2]
void Minor::ExecContext::pcState (const TheISA::PCState & val) inline override virtual
Implements ExecContext.
Definition at line 350 of file exec_context.hh.
References SimpleThread::pcState().
readCCRegOperand()
RegVal Minor::ExecContext::readCCRegOperand (const StaticInst * si, int idx) inline override virtual
Implements ExecContext.
Definition at line 416 of file exec_context.hh.
References RegId::index(), RegId::isCCReg(), SimpleThread::readCCReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readFloatRegOperandBits()
RegVal Minor::ExecContext::readFloatRegOperandBits (const StaticInst * si, int idx) inline override virtual
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 152 of file exec_context.hh.
References RegId::index(), RegId::isFloatReg(), SimpleThread::readFloatReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readIntRegOperand()
RegVal Minor::ExecContext::readIntRegOperand (const StaticInst * si, int idx) inline override virtual
Reads an integer register.
Implements ExecContext.
Definition at line 144 of file exec_context.hh.
References RegId::index(), RegId::isIntReg(), SimpleThread::readIntReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readMemAccPredicate()
bool Minor::ExecContext::readMemAccPredicate () const inline override virtual
Implements ExecContext.
Definition at line 332 of file exec_context.hh.
References SimpleThread::readMemAccPredicate().
Referenced by Minor::Execute::executeMemRefInst(), Minor::Execute::handleMemResponse(), and ~ExecContext().
readMiscReg()
RegVal Minor::ExecContext::readMiscReg (int misc_reg) inline override virtual
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implements ExecContext.
Definition at line 362 of file exec_context.hh.
References SimpleThread::readMiscReg().
readMiscRegNoEffect()
RegVal Minor::ExecContext::readMiscRegNoEffect (int misc_reg) const inline
Definition at line 356 of file exec_context.hh.
References SimpleThread::readMiscRegNoEffect().
readMiscRegOperand()
RegVal Minor::ExecContext::readMiscRegOperand (const StaticInst * si, int idx) inline override virtual
Implements ExecContext.
Definition at line 374 of file exec_context.hh.
References RegId::index(), RegId::isMiscReg(), SimpleThread::readMiscReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readPredicate()
bool Minor::ExecContext::readPredicate () const inline override virtual
Implements ExecContext.
Definition at line 320 of file exec_context.hh.
References SimpleThread::readPredicate().
Referenced by Minor::Execute::commitInst(), Minor::Execute::executeMemRefInst(), Minor::Execute::handleMemResponse(), and ~ExecContext().
readStCondFailures()
unsigned int Minor::ExecContext::readStCondFailures () const inline override virtual
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 401 of file exec_context.hh.
readVec16BitLaneOperand()
ConstVecLane16 Minor::ExecContext::readVec16BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 16bit operand.
Implements ExecContext.
Definition at line 247 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVec16BitLaneReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVec32BitLaneOperand()
ConstVecLane32 Minor::ExecContext::readVec32BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 32bit operand.
Implements ExecContext.
Definition at line 257 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVec32BitLaneReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVec64BitLaneOperand()
ConstVecLane64 Minor::ExecContext::readVec64BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 64bit operand.
Implements ExecContext.
Definition at line 267 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVec64BitLaneReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVec8BitLaneOperand()
ConstVecLane8 Minor::ExecContext::readVec8BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implements ExecContext.
Definition at line 237 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVec8BitLaneReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecElemOperand()
TheISA::VecElem Minor::ExecContext::readVecElemOperand (const StaticInst * si, int idx) const inline override virtual
Vector Elem Interfaces.
Reads an element of a vector register.
Implements ExecContext.
Definition at line 176 of file exec_context.hh.
References RegId::isVecElem(), SimpleThread::readVecElem(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecPredRegOperand()
const TheISA::VecPredRegContainer& Minor::ExecContext::readVecPredRegOperand (const StaticInst * si, int idx) const inline override virtual
Predicate registers interface.
Reads source predicate register operand.
Implements ExecContext.
Definition at line 184 of file exec_context.hh.
References RegId::isVecPredReg(), SimpleThread::readVecPredReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecRegOperand()
const TheISA::VecRegContainer& Minor::ExecContext::readVecRegOperand (const StaticInst * si, int idx) const inline override virtual
Vector Register Interfaces.
Reads source vector register operand.
Implements ExecContext.
Definition at line 160 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVecReg(), X86ISA::reg, and StaticInst::srcRegIdx().
setCCRegOperand()
void Minor::ExecContext::setCCRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Implements ExecContext.
Definition at line 424 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isCCReg(), X86ISA::reg, SimpleThread::setCCReg(), and X86ISA::val.
setFloatRegOperandBits()
void Minor::ExecContext::setFloatRegOperandBits (const StaticInst * si, int idx, RegVal val) inline override virtual
Sets the bits of a floating point register of single width to a binary value.
Implements ExecContext.
Definition at line 208 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isFloatReg(), X86ISA::reg, SimpleThread::setFloatReg(), and X86ISA::val.
setIntRegOperand()
void Minor::ExecContext::setIntRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Sets an integer register to a value.
Implements ExecContext.
Definition at line 200 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isIntReg(), X86ISA::reg, SimpleThread::setIntReg(), and X86ISA::val.
setMemAccPredicate()
void Minor::ExecContext::setMemAccPredicate (bool val) inline override virtual
Implements ExecContext.
Definition at line 338 of file exec_context.hh.
References SimpleThread::setMemAccPredicate().
Referenced by Minor::LSQ::LSQRequest::completeDisabledMemAccess(), and ExecContext().
setMiscReg()
void Minor::ExecContext::setMiscReg (int misc_reg, RegVal val) inline override virtual
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implements ExecContext.
Definition at line 368 of file exec_context.hh.
References SimpleThread::setMiscReg().
setMiscRegOperand()
void Minor::ExecContext::setMiscRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Implements ExecContext.
Definition at line 382 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isMiscReg(), X86ISA::reg, SimpleThread::setMiscReg(), and X86ISA::val.
setPredicate()
void Minor::ExecContext::setPredicate (bool val) inline override virtual
Implements ExecContext.
Definition at line 326 of file exec_context.hh.
References SimpleThread::setPredicate().
Referenced by ExecContext().
setStCondFailures()
void Minor::ExecContext::setStCondFailures (unsigned int sc_failures) inline override virtual
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 402 of file exec_context.hh.
setVecElemOperand()
void Minor::ExecContext::setVecElemOperand (const StaticInst * si, int idx, const TheISA::VecElem val) inline override virtual
Sets a vector register to a value.
Implements ExecContext.
Definition at line 311 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecElem(), X86ISA::reg, and SimpleThread::setVecElem().
setVecLaneOperand() [1/4]
virtual void Minor::ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 285 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [2/4]
virtual void Minor::ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ExecContext.
Definition at line 291 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [3/4]
virtual void Minor::ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ExecContext.
Definition at line 297 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [4/4]
virtual void Minor::ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ExecContext.
Definition at line 303 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperandT()
template<typename LD > void Minor::ExecContext::setVecLaneOperandT (const StaticInst * si, int idx, const LD & val) inline
Write a lane of the destination vector operand.
Definition at line 278 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecReg(), X86ISA::reg, and SimpleThread::setVecLane().
Referenced by setVecLaneOperand().
setVecPredRegOperand()
void Minor::ExecContext::setVecPredRegOperand (const StaticInst * si, int idx, const TheISA::VecPredRegContainer & val) inline override
Definition at line 225 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecPredReg(), X86ISA::reg, and SimpleThread::setVecPredReg().
setVecRegOperand()
void Minor::ExecContext::setVecRegOperand (const StaticInst * si, int idx, const TheISA::VecRegContainer & val) inline override
Definition at line 216 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecReg(), X86ISA::reg, and SimpleThread::setVecReg().
syscall()
void Minor::ExecContext::syscall (int64_t callnum, Fault * fault) inline override virtual
Executes a syscall specified by the callnum.
Implements ExecContext.
Definition at line 390 of file exec_context.hh.
References FullSystem, panic, and SimpleThread::syscall().
tcBase()
ThreadContext* Minor::ExecContext::tcBase () inline override virtual
Returns a pointer to the ThreadContext.
Implements ExecContext.
Definition at line 398 of file exec_context.hh.
References SimpleThread::getTC().
writeMem()
Fault Minor::ExecContext::writeMem (uint8_t * data, unsigned int size, Addr addr, Request::Flags flags, uint64_t * res, const std::vector< bool > & byteEnable = std::vector< bool >()) inline override virtual
For atomic-mode contexts, perform an atomic memory write operation.
For timing-mode contexts, initiate a timing memory write operation.
Implements ExecContext.
Definition at line 124 of file exec_context.hh.
References Minor::Execute::getLSQ(), and Minor::LSQ::pushRequest().
Member Data Documentation
cpu
MinorCPU& Minor::ExecContext::cpu
Definition at line 77 of file exec_context.hh.
Referenced by getCpuPtr().
execute
Execute& Minor::ExecContext::execute
The execute stage so we can peek at its contents.
Definition at line 83 of file exec_context.hh.
inst
MinorDynInstPtr Minor::ExecContext::inst
Instruction for the benefit of memory operations and for PC.
Definition at line 86 of file exec_context.hh.
thread
SimpleThread& Minor::ExecContext::thread
ThreadState object, provides all the architectural state.
Definition at line 80 of file exec_context.hh.
The documentation for this class was generated from the following file:
cpu/minor/exec_context.hh