gem5: DistEtherLink::RxLink Class Reference
DistEtherLink::RxLink Class Reference
Model for a receive link.
#include <dist_etherlink.hh>
Public Member Functions
RxLink (const std::string &name, DistEtherLink *p, Tick delay, EtherDump *d)
~RxLink ()
void setDistInt (DistIface *m)
Register our dist interface to talk to the peer gem5 processes.
const EventFunctionWrapper * doneEvent () const
Done events will be scheduled by DistIface (so we need the accessor)
Public Member Functions inherited from DistEtherLink::Link
Link (const std::string &name, DistEtherLink *p, EtherDump *d, Event *e)
~Link ()
const std::string name () const
bool busy () const
void setLocalInt (LocalIface *i)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Member Functions
void rxDone ()
Receive done callback method.
Protected Attributes
Tick linkDelay
Transmission delay for the simulated Ethernet link.
EventFunctionWrapper _doneEvent
Protected Attributes inherited from DistEtherLink::Link
std::string objName
DistEtherLink * parent
LocalIface * localIface
EtherDump * dump
DistIface * distIface
Event * event
EthPacketPtr packet
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Model for a receive link.
Definition at line 147 of file dist_etherlink.hh.
Constructor & Destructor Documentation
RxLink()
DistEtherLink::RxLink::RxLink (const std::string & name, DistEtherLink * p, Tick delay, EtherDump * d) inline
Definition at line 164 of file dist_etherlink.hh.
References DistEtherLink::Link::name().
~RxLink()
DistEtherLink::RxLink::~RxLink () inline
Definition at line 168 of file dist_etherlink.hh.
References ArmISA::m.
Member Function Documentation
doneEvent()
const EventFunctionWrapper* DistEtherLink::RxLink::doneEvent () const inline
Done events will be scheduled by DistIface (so we need the accessor)
Definition at line 177 of file dist_etherlink.hh.
Referenced by DistEtherLink::init().
rxDone()
void DistEtherLink::RxLink::rxDone () protected
Receive done callback method.
Called from doneEvent.
Definition at line 157 of file dist_etherlink.cc.
References DDUMP, DistEtherLink::distIface, DPRINTF, Stats::dump(), DistEtherLink::localIface, DistIface::packetIn(), and EtherInt::sendPacket().
setDistInt()
void DistEtherLink::RxLink::setDistInt (DistIface * m)
Register our dist interface to talk to the peer gem5 processes.
Definition at line 150 of file dist_etherlink.cc.
References DistEtherLink::distIface, and ArmISA::m.
Referenced by DistEtherLink::LocalIface::LocalIface().
Member Data Documentation
_doneEvent
EventFunctionWrapper DistEtherLink::RxLink::_doneEvent protected
Definition at line 160 of file dist_etherlink.hh.
linkDelay
Tick DistEtherLink::RxLink::linkDelay protected
Transmission delay for the simulated Ethernet link.
Definition at line 154 of file dist_etherlink.hh.
The documentation for this class was generated from the following files:
dev/net/dist_etherlink.hh
dev/net/dist_etherlink.cc