gem5: Scoreboard Class Reference
Scoreboard Class Reference
Implements a simple scoreboard to track which registers are ready.
#include <scoreboard.hh>
Public Member Functions
Scoreboard (const std::string &_my_name, unsigned _numPhysicalRegs)
Constructs a scoreboard.
~Scoreboard ()
Destructor.
std::string name () const
Returns the name of the scoreboard.
bool getReg (PhysRegIdPtr phys_reg) const
Checks if the register is ready.
void setReg (PhysRegIdPtr phys_reg)
Sets the register as ready.
void unsetReg (PhysRegIdPtr phys_reg)
Sets the register as not ready.
Private Attributes
const std::string _name
The object name, for DPRINTF.
std::vector< bool > regScoreBoard
Scoreboard of physical integer registers, saying whether or not they are ready.
unsigned M5_CLASS_VAR_USED numPhysRegs
The number of actual physical registers.
Detailed Description
Implements a simple scoreboard to track which registers are ready.
This class operates on the unified physical register space, because the different classes of registers do not need to be distinguished. Registers being part of a fixed mapping are always considered ready.
Definition at line 52 of file scoreboard.hh.
Constructor & Destructor Documentation
Scoreboard()
Scoreboard::Scoreboard (const std::string & _my_name, unsigned _numPhysicalRegs)
Constructs a scoreboard.
Parameters
_numPhysicalRegs Number of physical registers.
_numMiscRegs Number of miscellaneous registers.
Definition at line 38 of file scoreboard.cc.
~Scoreboard()
Scoreboard::~Scoreboard () inline
Destructor.
Definition at line 75 of file scoreboard.hh.
Member Function Documentation
getReg()
bool Scoreboard::getReg (PhysRegIdPtr phys_reg) const inline
Checks if the register is ready.
Definition at line 81 of file scoreboard.hh.
References PhysRegId::flatIndex(), PhysRegId::isFixedMapping(), RegId::isZeroReg(), and numPhysRegs.
Referenced by DefaultRename< Impl >::renameSrcRegs().
name()
std::string Scoreboard::name () const inline
Returns the name of the scoreboard.
Definition at line 78 of file scoreboard.hh.
References _name.
setReg()
void Scoreboard::setReg (PhysRegIdPtr phys_reg) inline
Sets the register as ready.
Definition at line 99 of file scoreboard.hh.
References RegId::className(), DPRINTF, PhysRegId::flatIndex(), RegId::index(), PhysRegId::isFixedMapping(), and numPhysRegs.
Referenced by FullO3CPU< O3CPUImpl >::insertThread(), and DefaultIEW< Impl >::writebackInsts().
unsetReg()
void Scoreboard::unsetReg (PhysRegIdPtr phys_reg) inline
Sets the register as not ready.
Definition at line 116 of file scoreboard.hh.
References PhysRegId::flatIndex(), PhysRegId::isFixedMapping(), RegId::isZeroReg(), and numPhysRegs.
Referenced by DefaultRename< Impl >::renameDestRegs().
Member Data Documentation
_name
const std::string Scoreboard::_name private
The object name, for DPRINTF.
We have to declare this explicitly because Scoreboard is not a SimObject.
Definition at line 57 of file scoreboard.hh.
Referenced by name().
numPhysRegs
unsigned M5_CLASS_VAR_USED Scoreboard::numPhysRegs private
The number of actual physical registers.
Definition at line 64 of file scoreboard.hh.
Referenced by getReg(), setReg(), and unsetReg().
regScoreBoard
std::vector<bool> Scoreboard::regScoreBoard private
Scoreboard of physical integer registers, saying whether or not they are ready.
Definition at line 61 of file scoreboard.hh.
The documentation for this class was generated from the following files:
cpu/o3/scoreboard.hh
cpu/o3/scoreboard.cc