gem5: sc_dt::sc_fxnum_observer Class Reference
sc_dt::sc_fxnum_observer Class Reference
#include <sc_fxnum_observer.hh>
Public Member Functions
virtual void construct (const sc_fxnum &)
virtual void destruct (const sc_fxnum &)
virtual void read (const sc_fxnum &)
virtual void write (const sc_fxnum &)
Static Public Attributes
static sc_fxnum_observer *(* default_observer)()
Protected Member Functions
sc_fxnum_observer ()
virtual ~sc_fxnum_observer ()
Detailed Description
Definition at line 110 of file sc_fxnum_observer.hh.
Constructor & Destructor Documentation
sc_fxnum_observer()
sc_dt::sc_fxnum_observer::sc_fxnum_observer () inline protected
Definition at line 113 of file sc_fxnum_observer.hh.
~sc_fxnum_observer()
virtual sc_dt::sc_fxnum_observer::~sc_fxnum_observer () inline protected virtual
Definition at line 114 of file sc_fxnum_observer.hh.
References construct(), destruct(), read(), and write().
Member Function Documentation
construct()
void sc_dt::sc_fxnum_observer::construct (const sc_fxnum &) inline virtual
Definition at line 156 of file sc_fxnum_observer.hh.
Referenced by sc_dt::sc_fxnum_fast_observer::~sc_fxnum_fast_observer(), and ~sc_fxnum_observer().
destruct()
void sc_dt::sc_fxnum_observer::destruct (const sc_fxnum &) inline virtual
Definition at line 157 of file sc_fxnum_observer.hh.
Referenced by sc_dt::sc_fxnum_fast_observer::~sc_fxnum_fast_observer(), and ~sc_fxnum_observer().
read()
void sc_dt::sc_fxnum_observer::read (const sc_fxnum &) inline virtual
Definition at line 158 of file sc_fxnum_observer.hh.
Referenced by sc_dt::sc_fxnum_fast_observer::~sc_fxnum_fast_observer(), and ~sc_fxnum_observer().
write()
void sc_dt::sc_fxnum_observer::write (const sc_fxnum &) inline virtual
Definition at line 159 of file sc_fxnum_observer.hh.
Referenced by sc_dt::sc_fxnum_fast_observer::~sc_fxnum_fast_observer(), and ~sc_fxnum_observer().
Member Data Documentation
default_observer
sc_fxnum_observer *(* sc_dt::sc_fxnum_observer::default_observer)()=0 static
Definition at line 122 of file sc_fxnum_observer.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum_observer.hh
systemc/dt/fx/sc_fxnum_observer.cc