gem5: RiscvISA::TLB Class Reference
RiscvISA::TLB Class Reference
#include <tlb.hh>
Public Types
typedef RiscvTLBParams Params
Public Types inherited from BaseTLB
enum Mode { Read, Write, Execute }
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TLB (const Params *p)
int probeEntry (Addr vpn, uint8_t) const
RiscvISA::PTE * getEntry (unsigned) const
virtual ~TLB ()
void takeOverFrom (BaseTLB *otlb) override
Take over from an old tlb context.
int getsize () const
RiscvISA::PTE & index (bool advance=true)
void insert (Addr vaddr, RiscvISA::PTE &pte)
void insertAt (RiscvISA::PTE &pte, unsigned Index, int _smallPages)
void flushAll () override
Remove all entries from the TLB.
void demapPage (Addr vaddr, uint64_t asn) override
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void regStats () override
Callback to set stat parameters.
Fault translateAtomic (const RequestPtr &req, ThreadContext *tc, Mode mode) override
void translateTiming (const RequestPtr &req, ThreadContext *tc, Translation *translation, Mode mode) override
Fault finalizePhysical (const RequestPtr &req, ThreadContext *tc, Mode mode) const override
Do post-translation physical address finalization.
Public Member Functions inherited from BaseTLB
virtual Fault translateFunctional (const RequestPtr &req, ThreadContext *tc, Mode mode)
virtual Port * getTableWalkerPort ()
Get the table walker port if present.
void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static bool validVirtualAddress (Addr vaddr)
static Fault checkCacheability (const RequestPtr &req)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
int smallPages
Protected Types
typedef std::multimap< Addr, int > PageTable
Protected Member Functions
void nextnlu ()
RiscvISA::PTE * lookup (Addr vpn, uint8_t asn) const
Protected Member Functions inherited from BaseTLB
BaseTLB (const Params *p)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
PageTable lookupTable
RiscvISA::PTE * table
int size
int nlu
Stats::Scalar read_hits
Stats::Scalar read_misses
Stats::Scalar read_acv
Stats::Scalar read_accesses
Stats::Scalar write_hits
Stats::Scalar write_misses
Stats::Scalar write_acv
Stats::Scalar write_accesses
Stats::Formula hits
Stats::Formula misses
Stats::Formula accesses
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
Fault translateInst (const RequestPtr &req, ThreadContext *tc)
Fault translateData (const RequestPtr &req, ThreadContext *tc, bool write)
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 56 of file tlb.hh.
Member Typedef Documentation
PageTable
typedef std::multimap<Addr, int> RiscvISA::TLB::PageTable protected
Definition at line 59 of file tlb.hh.
Params
typedef RiscvTLBParams RiscvISA::TLB::Params
Definition at line 82 of file tlb.hh.
Constructor & Destructor Documentation
TLB()
TLB::TLB (const Params * p)
Definition at line 65 of file tlb.cc.
References size, smallPages, and table.
Referenced by index().
~TLB()
TLB::~TLB () virtual
Definition at line 73 of file tlb.cc.
References table.
Member Function Documentation
checkCacheability()
Fault TLB::checkCacheability (const RequestPtr & req) inline static
Definition at line 147 of file tlb.cc.
References NoFault, Request::STRICT_ORDER, and Request::UNCACHEABLE.
Referenced by demapPage(), translateData(), and translateInst().
demapPage()
void RiscvISA::TLB::demapPage (Addr vaddr, uint64_t asn) inline override virtual
Implements BaseTLB.
Definition at line 98 of file tlb.hh.
References checkCacheability(), finalizePhysical(), ArmISA::mode, panic, regStats(), serialize(), translateAtomic(), translateData(), translateInst(), translateTiming(), unserialize(), and validVirtualAddress().
finalizePhysical()
Fault TLB::finalizePhysical (const RequestPtr & req, ThreadContext * tc, Mode mode) const override virtual
Do post-translation physical address finalization.
This method is used by some architectures that need post-translation massaging of physical addresses. For example, X86 uses this to remap physical addresses in the APIC range to a range of physical memory not normally available to real x86 implementations.
Parameters
req Request to updated in-place.
tc Thread context that created the request.
mode Request type (read/write/execute).
Returns
A fault on failure, NoFault otherwise.
Implements BaseTLB.
Definition at line 385 of file tlb.cc.
References NoFault.
Referenced by demapPage().
flushAll()
void TLB::flushAll () override virtual
Remove all entries from the TLB.
Implements BaseTLB.
Definition at line 194 of file tlb.cc.
References DPRINTF, lookupTable, nlu, size, and table.
Referenced by getsize().
getEntry()
RiscvISA::PTE * TLB::getEntry (unsigned Index) const
Definition at line 111 of file tlb.cc.
References size, and table.
getsize()
int RiscvISA::TLB::getsize () const inline
Definition at line 92 of file tlb.hh.
References flushAll(), index(), insert(), insertAt(), size, and RiscvISA::vaddr.
index()
RiscvISA::PTE & TLB::index (bool advance = true)
Definition at line 393 of file tlb.cc.
References nextnlu(), nlu, table, and TLB().
Referenced by getsize(), lookup(), and probeEntry().
insert()
void TLB::insert (Addr vaddr, RiscvISA::PTE & pte)
Definition at line 188 of file tlb.cc.
References fatal.
Referenced by getsize().
insertAt()
void TLB::insertAt (RiscvISA::PTE & pte, unsigned Index, int _smallPages)
Definition at line 160 of file tlb.cc.
References RiscvISA::PTE::asid, RiscvISA::PTE::C0, RiscvISA::PTE::C1, RiscvISA::PTE::D0, RiscvISA::PTE::D1, DPRINTF, RiscvISA::PTE::G, RiscvISA::i, lookupTable, RiscvISA::PTE::Mask, RiscvISA::PTE::PFN0, RiscvISA::PTE::PFN1, size, smallPages, table, RiscvISA::PTE::V0, RiscvISA::PTE::V1, RiscvISA::PTE::VPN, and warn.
Referenced by getsize().
lookup()
RiscvISA::PTE * TLB::lookup (Addr vpn, uint8_t asn) const protected
Definition at line 81 of file tlb.cc.
References RiscvISA::PTE::asid, DPRINTF, RiscvISA::PTE::G, RiscvISA::i, index(), lookupTable, RiscvISA::PTE::Mask, RiscvISA::PTE::PFN1, table, and RiscvISA::PTE::VPN.
Referenced by nextnlu().
nextnlu()
void RiscvISA::TLB::nextnlu () inline protected
Definition at line 66 of file tlb.hh.
References lookup().
Referenced by index().
probeEntry()
int TLB::probeEntry (Addr vpn, uint8_t asn) const
Definition at line 119 of file tlb.cc.
References RiscvISA::PTE::asid, DPRINTF, RiscvISA::PTE::G, RiscvISA::i, index(), lookupTable, RiscvISA::PTE::Mask, table, and RiscvISA::PTE::VPN.
regStats()
void TLB::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 230 of file tlb.cc.
References accesses, Stats::DataWrap< Derived, InfoProxyType >::desc(), hits, misses, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), read_accesses, read_hits, read_misses, Stats::Group::regStats(), write_accesses, write_hits, and write_misses.
Referenced by demapPage().
serialize()
void TLB::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 203 of file tlb.cc.
References csprintf(), RiscvISA::i, nlu, RiscvISA::PTE::serialize(), SERIALIZE_SCALAR, size, and table.
Referenced by demapPage().
takeOverFrom()
void RiscvISA::TLB::takeOverFrom (BaseTLB * otlb) inline override virtual
Take over from an old tlb context.
Implements BaseTLB.
Definition at line 89 of file tlb.hh.
translateAtomic()
Fault TLB::translateAtomic (const RequestPtr & req, ThreadContext * tc, Mode mode) override virtual
Implements BaseTLB.
Definition at line 368 of file tlb.cc.
References BaseTLB::Execute, translateData(), translateInst(), and BaseTLB::Write.
Referenced by demapPage(), and translateTiming().
translateData()
Fault TLB::translateData (const RequestPtr & req, ThreadContext * tc, bool write) private
check if we simulate a bare metal system if so, we have no tlb, phys addr == virt addr
we simply set the virtual address to physical address
as we currently support bare metal only, we throw a panic, if it is not a bare metal system
Definition at line 322 of file tlb.cc.
References checkCacheability(), FullSystem, ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), NoFault, RiscvISA::p, panic, Request::PHYSICAL, Process::pTable, and EmulationPageTable::translate().
Referenced by demapPage(), and translateAtomic().
translateInst()
Fault TLB::translateInst (const RequestPtr & req, ThreadContext * tc) private
check if we simulate a bare metal system if so, we have no tlb, phys addr == virt addr
we simply set the virtual address to physical address
as we currently support bare metal only, we throw a panic, if it is not a bare metal system
Definition at line 287 of file tlb.cc.
References checkCacheability(), FullSystem, ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), NoFault, RiscvISA::p, panic, Request::PHYSICAL, Process::pTable, and EmulationPageTable::translate().
Referenced by demapPage(), and translateAtomic().
translateTiming()
void TLB::translateTiming (const RequestPtr & req, ThreadContext * tc, Translation * translation, Mode mode) override virtual
Implements BaseTLB.
Definition at line 377 of file tlb.cc.
References BaseTLB::Translation::finish(), and translateAtomic().
Referenced by demapPage().
unserialize()
void TLB::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 215 of file tlb.cc.
References csprintf(), RiscvISA::i, lookupTable, nlu, size, table, RiscvISA::PTE::unserialize(), and UNSERIALIZE_SCALAR.
Referenced by demapPage().
validVirtualAddress()
static bool RiscvISA::TLB::validVirtualAddress (Addr vaddr) static
Referenced by demapPage().
Member Data Documentation
accesses
Stats::Formula RiscvISA::TLB::accesses protected
Definition at line 79 of file tlb.hh.
Referenced by regStats().
hits
Stats::Formula RiscvISA::TLB::hits protected
Definition at line 77 of file tlb.hh.
Referenced by regStats().
lookupTable
PageTable RiscvISA::TLB::lookupTable protected
Definition at line 60 of file tlb.hh.
Referenced by flushAll(), insertAt(), lookup(), probeEntry(), and unserialize().
misses
Stats::Formula RiscvISA::TLB::misses protected
Definition at line 78 of file tlb.hh.
Referenced by regStats().
nlu
int RiscvISA::TLB::nlu protected
Definition at line 64 of file tlb.hh.
Referenced by flushAll(), index(), serialize(), and unserialize().
read_accesses
Stats::Scalar RiscvISA::TLB::read_accesses mutable protected
Definition at line 72 of file tlb.hh.
Referenced by regStats().
read_acv
Stats::Scalar RiscvISA::TLB::read_acv mutable protected
Definition at line 71 of file tlb.hh.
read_hits
Stats::Scalar RiscvISA::TLB::read_hits mutable protected
Definition at line 69 of file tlb.hh.
Referenced by regStats().
read_misses
Stats::Scalar RiscvISA::TLB::read_misses mutable protected
Definition at line 70 of file tlb.hh.
Referenced by regStats().
size
int RiscvISA::TLB::size protected
Definition at line 63 of file tlb.hh.
Referenced by flushAll(), getEntry(), getsize(), insertAt(), serialize(), TLB(), and unserialize().
smallPages
int RiscvISA::TLB::smallPages
Definition at line 91 of file tlb.hh.
Referenced by insertAt(), and TLB().
table
RiscvISA::PTE* RiscvISA::TLB::table protected
Definition at line 62 of file tlb.hh.
Referenced by flushAll(), getEntry(), index(), insertAt(), lookup(), probeEntry(), serialize(), TLB(), unserialize(), and ~TLB().
write_accesses
Stats::Scalar RiscvISA::TLB::write_accesses mutable protected
Definition at line 76 of file tlb.hh.
Referenced by regStats().
write_acv
Stats::Scalar RiscvISA::TLB::write_acv mutable protected
Definition at line 75 of file tlb.hh.
write_hits
Stats::Scalar RiscvISA::TLB::write_hits mutable protected
Definition at line 73 of file tlb.hh.
Referenced by regStats().
write_misses
Stats::Scalar RiscvISA::TLB::write_misses mutable protected
Definition at line 74 of file tlb.hh.
Referenced by regStats().
The documentation for this class was generated from the following files:
arch/riscv/tlb.hh
arch/riscv/tlb.cc