gem5: RiscvISA::StackTrace Class Reference
RiscvISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Static Public Attributes
static const int user = 1
static const int console = 2
static const int unknown = 3
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 58 of file stacktrace.hh.
Constructor & Destructor Documentation
StackTrace() [1/2]
RiscvISA::StackTrace::StackTrace ()
Definition at line 66 of file stacktrace.cc.
References panic.
StackTrace() [2/2]
RiscvISA::StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 72 of file stacktrace.cc.
References panic.
~StackTrace()
RiscvISA::StackTrace::~StackTrace ()
Definition at line 78 of file stacktrace.cc.
References panic.
Member Function Documentation
clear()
void RiscvISA::StackTrace::clear () inline
Definition at line 78 of file stacktrace.hh.
decodePrologue()
bool RiscvISA::StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) private
Definition at line 115 of file stacktrace.cc.
References Stats::dump(), and panic.
decodeSave()
bool RiscvISA::StackTrace::decodeSave (MachInst inst, int & reg, int & disp) private
Definition at line 104 of file stacktrace.cc.
References panic.
decodeStack()
bool RiscvISA::StackTrace::decodeStack (MachInst inst, int & disp) private
Definition at line 97 of file stacktrace.cc.
References panic.
dprintf()
void RiscvISA::StackTrace::dprintf () inline
Definition at line 117 of file stacktrace.hh.
getstack()
const std::vector<Addr>& RiscvISA::StackTrace::getstack () const inline
Definition at line 94 of file stacktrace.hh.
References X86ISA::stack.
isEntry()
bool RiscvISA::StackTrace::isEntry (Addr addr) private
Definition at line 90 of file stacktrace.cc.
References panic.
trace() [1/2]
void RiscvISA::StackTrace::trace (ThreadContext * tc, bool is_call) private
Definition at line 84 of file stacktrace.cc.
References panic.
trace() [2/2]
bool RiscvISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 124 of file stacktrace.hh.
References StaticInst::isCall(), and StaticInst::isReturn().
valid()
bool RiscvISA::StackTrace::valid () const inline
Definition at line 85 of file stacktrace.hh.
Member Data Documentation
console
const int RiscvISA::StackTrace::console = 2 static
Definition at line 100 of file stacktrace.hh.
stack
std::vector<Addr> RiscvISA::StackTrace::stack private
Definition at line 62 of file stacktrace.hh.
tc
ThreadContext* RiscvISA::StackTrace::tc private
Definition at line 61 of file stacktrace.hh.
unknown
const int RiscvISA::StackTrace::unknown = 3 static
Definition at line 101 of file stacktrace.hh.
user
const int RiscvISA::StackTrace::user = 1 static
Definition at line 99 of file stacktrace.hh.
The documentation for this class was generated from the following files:
arch/riscv/stacktrace.hh
arch/riscv/stacktrace.cc