gem5: m5::Coroutine< Arg, Ret >::CallerType Class Reference
m5::Coroutine< Arg, Ret >::CallerType Class Reference
CallerType: A reference to an object of this class will be passed to the coroutine task.
#include <coroutine.hh>
Public Member Functions
template<typename T = Ret>
CallerType & operator() (typename std::enable_if< !std::is_same< T, void >::value, T >::type param)
operator() is the way we can jump outside the coroutine and return a value to the caller.
template<typename T = Ret>
std::enable_if< std::is_same< T, void >::value, CallerType >::type & operator() ()
operator() is the way we can jump outside the coroutine
template<typename T = Arg>
std::enable_if<!std::is_same< T, void >::value, T >::type get ()
get() is the way we can extrapolate arguments from the coroutine caller.
Protected Member Functions
CallerType (Coroutine &_coro)
Private Attributes
Coroutine & coro
Fiber * callerFiber
RetChannel retChannel
Friends
class Coroutine
Detailed Description
template<typename Arg, typename Ret>
class m5::Coroutine< Arg, Ret >::CallerType
CallerType: A reference to an object of this class will be passed to the coroutine task.
This is the way it is possible for the coroutine to interface (e.g. switch back) to the coroutine caller.
Definition at line 85 of file coroutine.hh.
Constructor & Destructor Documentation
CallerType()
template<typename Arg, typename Ret> m5::Coroutine< Arg, Ret >::CallerType::CallerType (Coroutine & _coro) inline protected
Definition at line 89 of file coroutine.hh.
Member Function Documentation
get()
template<typename Arg, typename Ret> template<typename T = Arg> std::enable_if<!std::is_same<T, void>::value, T>::type m5::Coroutine< Arg, Ret >::CallerType::get () inline
get() is the way we can extrapolate arguments from the coroutine caller.
The coroutine blocks, waiting for the value, unless it is already available; otherwise caller execution is resumed, and coroutine won't execute until a value is pushed from the caller.
Returns
arg coroutine argument
Definition at line 136 of file coroutine.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUProcess::doRead(), ItsProcess::doRead(), SMMUProcess::doWrite(), ItsProcess::doWrite(), and ItsTranslation::main().
operator()() [1/2]
template<typename Arg, typename Ret> template<typename T = Ret> CallerType& m5::Coroutine< Arg, Ret >::CallerType::operator() (typename std::enable_if< !std::is_same< T, void >::value, T >::type param) inline
operator() is the way we can jump outside the coroutine and return a value to the caller.
This method is generated only if the coroutine returns a value (Ret != void)
Definition at line 101 of file coroutine.hh.
operator()() [2/2]
template<typename Arg, typename Ret> template<typename T = Ret> std::enable_if<std::is_same<T, void>::value, CallerType>::type& m5::Coroutine< Arg, Ret >::CallerType::operator() () inline
operator() is the way we can jump outside the coroutine
This method is generated only if the coroutine doesn't return a value (Ret = void)
Definition at line 118 of file coroutine.hh.
Friends And Related Function Documentation
Coroutine
template<typename Arg, typename Ret> friend class Coroutine friend
Definition at line 87 of file coroutine.hh.
Member Data Documentation
callerFiber
template<typename Arg, typename Ret> Fiber* m5::Coroutine< Arg, Ret >::CallerType::callerFiber private
Definition at line 150 of file coroutine.hh.
Referenced by m5::Coroutine< Arg, Ret >::call().
coro
template<typename Arg, typename Ret> Coroutine& m5::Coroutine< Arg, Ret >::CallerType::coro private
Definition at line 149 of file coroutine.hh.
retChannel
template<typename Arg, typename Ret> RetChannel m5::Coroutine< Arg, Ret >::CallerType::retChannel private
Definition at line 151 of file coroutine.hh.
Referenced by m5::Coroutine< Arg, Ret >::get().
The documentation for this class was generated from the following file:
base/coroutine.hh