gem5: sc_dt::sc_bitref< X > Class Template Reference
sc_dt::sc_bitref< X > Class Template Reference
#include <sc_bit_proxies.hh>
Public Types
typedef sc_bitref_r< X >::value_type value_type
Public Types inherited from sc_dt::sc_bitref_r< X >
typedef X ::traits_type traits_type
typedef traits_type::bit_type bit_type
typedef traits_type::value_type value_type
Public Member Functions
sc_bitref (X &obj_, int index_)
sc_bitref (const sc_bitref< X > &a)
sc_bitref< X > * clone () const
sc_bitref< X > & operator= (const sc_bitref_r< X > &a)
sc_bitref< X > & operator= (const sc_bitref< X > &a)
sc_bitref< X > & operator= (const sc_logic &a)
sc_bitref< X > & operator= (sc_logic_value_t v)
sc_bitref< X > & operator= (bool a)
sc_bitref< X > & operator= (char a)
sc_bitref< X > & operator= (int a)
sc_bitref< X > & operator= (const sc_bit &a)
sc_bitref< X > & operator&= (const sc_bitref_r< X > &a)
sc_bitref< X > & operator&= (const sc_logic &a)
sc_bitref< X > & operator&= (sc_logic_value_t v)
sc_bitref< X > & operator&= (bool a)
sc_bitref< X > & operator&= (char a)
sc_bitref< X > & operator&= (int a)
sc_bitref< X > & operator|= (const sc_bitref_r< X > &a)
sc_bitref< X > & operator|= (const sc_logic &a)
sc_bitref< X > & operator|= (sc_logic_value_t v)
sc_bitref< X > & operator|= (bool a)
sc_bitref< X > & operator|= (char a)
sc_bitref< X > & operator|= (int a)
sc_bitref< X > & operator^= (const sc_bitref_r< X > &a)
sc_bitref< X > & operator^= (const sc_logic &a)
sc_bitref< X > & operator^= (sc_logic_value_t v)
sc_bitref< X > & operator^= (bool a)
sc_bitref< X > & operator^= (char a)
sc_bitref< X > & operator^= (int a)
sc_bitref< X > & b_not ()
void set_bit (int n, value_type value)
void set_word (int i, sc_digit w)
void set_cword (int i, sc_digit w)
void clean_tail ()
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_bitref_r< X >
sc_bitref_r (const X &obj_, int index_)
sc_bitref_r (const sc_bitref_r< X > &a)
sc_bitref_r< X > * clone () const
bit_type operator~ () const
operator bit_type () const
value_type value () const
bool is_01 () const
bool to_bool () const
char to_char () const
int length () const
int size () const
value_type get_bit (int n) const
sc_digit get_word (int i) const
sc_digit get_cword (int i) const
void print (::std::ostream &os=::std::cout) const
Private Member Functions
sc_bitref ()
Friends
class sc_bv_base
class sc_lv_base
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_bitref_r< X >
X & m_obj
int m_index
Detailed Description
template<class X>
class sc_dt::sc_bitref< X >
Definition at line 46 of file sc_bit_proxies.hh.
Member Typedef Documentation
value_type
template<class X> typedef sc_bitref_r<X>::value_type sc_dt::sc_bitref< X >::value_type
Definition at line 388 of file sc_bit_proxies.hh.
Constructor & Destructor Documentation
sc_bitref() [1/3]
template<class X> sc_dt::sc_bitref< X >::sc_bitref (X & obj_, int index_) inline
Definition at line 391 of file sc_bit_proxies.hh.
sc_bitref() [2/3]
template<class X> sc_dt::sc_bitref< X >::sc_bitref (const sc_bitref< X > & a) inline
Definition at line 394 of file sc_bit_proxies.hh.
sc_bitref() [3/3]
template<class X> sc_dt::sc_bitref< X >::sc_bitref () private
Member Function Documentation
b_not()
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::b_not () inline
Definition at line 2058 of file sc_bit_proxies.hh.
References sc_dt::sc_logic::not_table.
clean_tail()
template<class X> void sc_dt::sc_bitref< X >::clean_tail () inline
Definition at line 550 of file sc_bit_proxies.hh.
References sc_dt::concat, MipsISA::is, sc_dt::operator,, and sc_dt::operator>>().
clone()
template<class X> sc_bitref<X>* sc_dt::sc_bitref< X >::clone () const inline
Definition at line 397 of file sc_bit_proxies.hh.
References ArmISA::a.
Referenced by sc_dt::concat(), and sc_dt::operator,().
operator&=() [1/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (const sc_bitref_r< X > & a)
Referenced by sc_dt::sc_bitref< X >::operator=().
operator&=() [2/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (const sc_logic & a)
operator&=() [3/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (sc_logic_value_t v) inline
Definition at line 450 of file sc_bit_proxies.hh.
operator&=() [4/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (bool a) inline
Definition at line 457 of file sc_bit_proxies.hh.
operator&=() [5/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (char a) inline
Definition at line 464 of file sc_bit_proxies.hh.
operator&=() [6/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator &= (int a) inline
Definition at line 471 of file sc_bit_proxies.hh.
References sc_dt::operator|=().
operator=() [1/8]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator= (const sc_bitref_r< X > & a) inline
Definition at line 1973 of file sc_bit_proxies.hh.
References sc_dt::sc_bitref_r< T >::value().
operator=() [2/8]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator= (const sc_bitref< X > & a) inline
Definition at line 1981 of file sc_bit_proxies.hh.
References ArmISA::a, sc_dt::sc_logic::and_table, sc_dt::sc_bitref< X >::operator&=(), sc_dt::sc_bitref_r< X >::value(), sc_dt::sc_bitref_r< T >::value(), and sc_dt::sc_logic::value().
operator=() [3/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (const sc_logic & a) inline
Definition at line 404 of file sc_bit_proxies.hh.
References sc_dt::sc_bitref< X >::set_bit(), and sc_dt::sc_logic::value().
operator=() [4/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (sc_logic_value_t v) inline
Definition at line 411 of file sc_bit_proxies.hh.
operator=() [5/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (bool a) inline
Definition at line 418 of file sc_bit_proxies.hh.
operator=() [6/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (char a) inline
Definition at line 425 of file sc_bit_proxies.hh.
operator=() [7/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (int a) inline
Definition at line 432 of file sc_bit_proxies.hh.
operator=() [8/8]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator= (const sc_bit & a) inline
Definition at line 439 of file sc_bit_proxies.hh.
References sc_dt::operator&=().
operator^=() [1/6]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator^= (const sc_bitref_r< X > & a) inline
Definition at line 2035 of file sc_bit_proxies.hh.
References sc_dt::sc_bitref_r< T >::value(), and sc_dt::sc_logic::xor_table.
operator^=() [2/6]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator^= (const sc_logic & a) inline
Definition at line 2046 of file sc_bit_proxies.hh.
References sc_dt::sc_logic::value(), and sc_dt::sc_logic::xor_table.
operator^=() [3/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator^= (sc_logic_value_t v) inline
Definition at line 512 of file sc_bit_proxies.hh.
operator^=() [4/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator^= (bool a) inline
Definition at line 519 of file sc_bit_proxies.hh.
operator^=() [5/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator^= (char a) inline
Definition at line 526 of file sc_bit_proxies.hh.
operator^=() [6/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator^= (int a) inline
Definition at line 533 of file sc_bit_proxies.hh.
References sc_dt::b_not(), ArmISA::i, ArmISA::n, and MipsISA::w.
operator|=() [1/6]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator|= (const sc_bitref_r< X > & a) inline
Definition at line 2014 of file sc_bit_proxies.hh.
References sc_dt::sc_logic::or_table, and sc_dt::sc_bitref_r< T >::value().
operator|=() [2/6]
template<class X > sc_bitref< X > & sc_dt::sc_bitref< X >::operator|= (const sc_logic & a) inline
Definition at line 2025 of file sc_bit_proxies.hh.
References sc_dt::sc_logic::or_table, and sc_dt::sc_logic::value().
operator|=() [3/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator|= (sc_logic_value_t v) inline
Definition at line 481 of file sc_bit_proxies.hh.
operator|=() [4/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator|= (bool a) inline
Definition at line 488 of file sc_bit_proxies.hh.
operator|=() [5/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator|= (char a) inline
Definition at line 495 of file sc_bit_proxies.hh.
operator|=() [6/6]
template<class X> sc_bitref<X>& sc_dt::sc_bitref< X >::operator|= (int a) inline
Definition at line 502 of file sc_bit_proxies.hh.
References sc_dt::operator^=().
scan()
template<class X > void sc_dt::sc_bitref< X >::scan (::std::istream & is = ::std::cin) inline
Definition at line 2111 of file sc_bit_proxies.hh.
References ArmISA::c.
Referenced by sc_dt::operator>>().
set_bit()
template<class X > void sc_dt::sc_bitref< X >::set_bit (int n, value_type value) inline
Definition at line 2067 of file sc_bit_proxies.hh.
References sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
Referenced by sc_dt::sc_bitref< X >::operator=().
set_cword()
template<class X > void sc_dt::sc_bitref< X >::set_cword (int i, sc_digit w) inline
Definition at line 2094 of file sc_bit_proxies.hh.
References PowerISA::bi, sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
set_word()
template<class X > void sc_dt::sc_bitref< X >::set_word (int i, sc_digit w) inline
Definition at line 2078 of file sc_bit_proxies.hh.
References PowerISA::bi, sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
Friends And Related Function Documentation
sc_bv_base
template<class X> friend class sc_bv_base friend
Definition at line 384 of file sc_bit_proxies.hh.
sc_lv_base
template<class X> friend class sc_lv_base friend
Definition at line 385 of file sc_bit_proxies.hh.
The documentation for this class was generated from the following file:
systemc/ext/dt/bit/sc_bit_proxies.hh