gem5: X86ISA::Decoder Class Reference
X86ISA::Decoder Class Reference
#include <decoder.hh>
Classes
struct InstBytes
Public Member Functions
Decoder (ISA *isa=nullptr)
void setM5Reg (HandyM5Reg m5Reg)
void takeOverFrom (Decoder *old)
void reset ()
void process ()
void moreBytes (const PCState &pc, Addr fetchPC, MachInst data)
bool needMoreBytes ()
bool instReady ()
void updateNPC (X86ISA::PCState &nextPC)
StaticInstPtr decodeInst (ExtMachInst mach_inst)
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
StaticInstPtr decode (X86ISA::PCState &nextPC)
Protected Types
enum State {
ResetState, FromCacheState, PrefixState, Vex2Of2State,
Vex2Of3State, Vex3Of3State, VexOpcodeState, OneByteOpcodeState,
TwoByteOpcodeState, ThreeByte0F38OpcodeState, ThreeByte0F3AOpcodeState, ModRMState,
SIBState, DisplacementState, ImmediateState, ErrorState
}
typedef RegVal CacheKey
Caching for decoded instruction objects.
typedef DecodeCache::AddrMap< Decoder::InstBytes > DecodePages
typedef std::unordered_map< CacheKey, DecodePages * > AddrCacheMap
typedef std::unordered_map< CacheKey, DecodeCache::InstMap< ExtMachInst > * > InstCacheMap
Protected Member Functions
uint8_t getNextByte ()
void getImmediate (int &collected, uint64_t &current, int size)
void updateOffsetState ()
void consumeByte ()
void consumeBytes (int numBytes)
State doResetState ()
State doFromCacheState ()
State doPrefixState (uint8_t)
State doVex2Of2State (uint8_t)
State doVex2Of3State (uint8_t)
State doVex3Of3State (uint8_t)
State doVexOpcodeState (uint8_t)
State doOneByteOpcodeState (uint8_t)
State doTwoByteOpcodeState (uint8_t)
State doThreeByte0F38OpcodeState (uint8_t)
State doThreeByte0F3AOpcodeState (uint8_t)
State doModRMState (uint8_t)
State doSIBState (uint8_t)
State doDisplacementState ()
State doImmediateState ()
State processOpcode (ByteTable &immTable, ByteTable &modrmTable, bool addrSizedImm=false)
State processExtendedOpcode (ByteTable &immTable)
Protected Attributes
MachInst fetchChunk
InstBytes * instBytes
int chunkIdx
Addr basePC
Addr origPC
int offset
ExtMachInst emi
X86Mode mode
X86SubMode submode
uint8_t altOp
uint8_t defOp
uint8_t altAddr
uint8_t defAddr
uint8_t stack
bool outOfBytes
bool instDone
int displacementSize
int immediateSize
int immediateCollected
State state
DecodePages * decodePages
AddrCacheMap addrCacheMap
DecodeCache::InstMap< ExtMachInst > * instMap
Static Protected Attributes
static InstBytes dummy
static InstCacheMap instCacheMap
Private Types
typedef const uint8_t ByteTable[256]
Static Private Attributes
static const uint8_t SizeTypeToSize [3][10]
static ByteTable Prefixes
static ByteTable UsesModRMOneByte
static ByteTable UsesModRMTwoByte
static ByteTable UsesModRMThreeByte0F38
static ByteTable UsesModRMThreeByte0F3A
static ByteTable ImmediateTypeOneByte
static ByteTable ImmediateTypeTwoByte
static ByteTable ImmediateTypeThreeByte0F38
static ByteTable ImmediateTypeThreeByte0F3A
static ByteTable ImmediateTypeVex [10]
Detailed Description
Definition at line 52 of file decoder.hh.
Member Typedef Documentation
AddrCacheMap
typedef std::unordered_map<CacheKey, DecodePages *> X86ISA::Decoder::AddrCacheMap protected
Definition at line 229 of file decoder.hh.
ByteTable
typedef const uint8_t X86ISA::Decoder::ByteTable[256] private
Definition at line 57 of file decoder.hh.
CacheKey
typedef RegVal X86ISA::Decoder::CacheKey protected
Caching for decoded instruction objects.
Definition at line 225 of file decoder.hh.
DecodePages
typedef DecodeCache::AddrMap<Decoder::InstBytes> X86ISA::Decoder::DecodePages protected
Definition at line 227 of file decoder.hh.
InstCacheMap
typedef std::unordered_map< CacheKey, DecodeCache::InstMap<ExtMachInst> *> X86ISA::Decoder::InstCacheMap protected
Definition at line 234 of file decoder.hh.
Member Enumeration Documentation
State
enum X86ISA::Decoder::State protected
Enumerator
ResetState
FromCacheState
PrefixState
Vex2Of2State
Vex2Of3State
Vex3Of3State
VexOpcodeState
OneByteOpcodeState
TwoByteOpcodeState
ThreeByte0F38OpcodeState
ThreeByte0F3AOpcodeState
ModRMState
SIBState
DisplacementState
ImmediateState
ErrorState
Definition at line 177 of file decoder.hh.
Constructor & Destructor Documentation
Decoder()
X86ISA::Decoder::Decoder (ISA * isa = nullptr) inline
Definition at line 238 of file decoder.hh.
References dummy, mode, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::reset(), X86ISA::SixtyFourBitMode, and submode.
Member Function Documentation
consumeByte()
void X86ISA::Decoder::consumeByte () inline protected
Definition at line 151 of file decoder.hh.
References updateOffsetState().
Referenced by doModRMState(), doOneByteOpcodeState(), doPrefixState(), doSIBState(), doThreeByte0F38OpcodeState(), doThreeByte0F3AOpcodeState(), doTwoByteOpcodeState(), doVex2Of2State(), doVex2Of3State(), doVex3Of3State(), and doVexOpcodeState().
consumeBytes()
void X86ISA::Decoder::consumeBytes (int numBytes) inline protected
Definition at line 157 of file decoder.hh.
References updateOffsetState().
Referenced by getImmediate().
decode() [1/2]
StaticInstPtr X86ISA::Decoder::decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
Parameters
mach_inst The binary instruction to decode.
Return values
A pointer to the corresponding StaticInst object.
Definition at line 682 of file decoder.cc.
References decodeInst(), instMap, and X86ISA::si.
Referenced by decode(), and updateNPC().
decode() [2/2]
StaticInstPtr X86ISA::Decoder::decode (X86ISA::PCState & nextPC)
Definition at line 694 of file decoder.cc.
References basePC, X86ISA::Decoder::InstBytes::chunks, decode(), emi, instBytes, instDone, X86ISA::Decoder::InstBytes::lastOffset, X86ISA::mask, X86ISA::Decoder::InstBytes::masks, offset, origPC, X86ISA::Decoder::InstBytes::si, X86ISA::si, and updateNPC().
decodeInst()
StaticInstPtr X86ISA::Decoder::decodeInst (ExtMachInst mach_inst)
Referenced by decode(), and updateNPC().
doDisplacementState()
Decoder::State X86ISA::Decoder::doDisplacementState () protected
Definition at line 587 of file decoder.cc.
References X86ISA::ExtMachInst::displacement, displacementSize, DisplacementState, X86ISA::ExtMachInst::dispSize, DPRINTF, emi, ErrorState, getImmediate(), immediateCollected, immediateSize, ImmediateState, instDone, panic, and ResetState.
Referenced by process().
doFromCacheState()
Decoder::State X86ISA::Decoder::doFromCacheState () protected
Definition at line 144 of file decoder.cc.
References basePC, chunkIdx, X86ISA::Decoder::InstBytes::chunks, DPRINTF, fetchChunk, FromCacheState, instBytes, instDone, X86ISA::Decoder::InstBytes::lastOffset, X86ISA::Decoder::InstBytes::masks, offset, origPC, outOfBytes, PrefixState, ResetState, and X86ISA::Decoder::InstBytes::si.
Referenced by process().
doImmediateState()
Decoder::State X86ISA::Decoder::doImmediateState () protected
Definition at line 635 of file decoder.cc.
References DPRINTF, dummy, emi, ErrorState, getImmediate(), X86ISA::ExtMachInst::immediate, immediateCollected, immediateSize, ImmediateState, instCacheMap, instDone, and ResetState.
Referenced by process().
doModRMState()
Decoder::State X86ISA::Decoder::doModRMState (uint8_t nextByte) protected
Definition at line 510 of file decoder.cc.
References consumeByte(), defOp, displacementSize, DisplacementState, DPRINTF, emi, ErrorState, immediateSize, ImmediateState, instDone, X86ISA::ExtMachInst::modRM, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, ResetState, SIBState, and X86ISA::ExtMachInst::type.
Referenced by process().
doOneByteOpcodeState()
Decoder::State X86ISA::Decoder::doOneByteOpcodeState (uint8_t nextByte) protected
Definition at line 377 of file decoder.cc.
References consumeByte(), DPRINTF, emi, ErrorState, ImmediateTypeOneByte, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), TwoByteOpcodeState, X86ISA::ExtMachInst::type, and UsesModRMOneByte.
Referenced by process().
doPrefixState()
Decoder::State X86ISA::Decoder::doPrefixState (uint8_t nextByte) protected
Definition at line 178 of file decoder.cc.
References X86ISA::AddressSizeOverride, consumeByte(), X86ISA::CSOverride, DPRINTF, X86ISA::DSOverride, emi, X86ISA::ESOverride, X86ISA::FSOverride, X86ISA::GSOverride, X86ISA::ExtMachInst::legacy, X86ISA::Lock, X86ISA::ExtMachInst::mode, OneByteOpcodeState, X86ISA::OperandSizeOverride, panic, PrefixState, X86ISA::Rep, X86ISA::Repne, X86ISA::ExtMachInst::rex, X86ISA::RexPrefix, X86ISA::SixtyFourBitMode, X86ISA::SSOverride, X86ISA::ExtMachInst::vex, Vex2Of2State, Vex2Of3State, X86ISA::Vex2Prefix, and X86ISA::Vex3Prefix.
Referenced by process().
doResetState()
Decoder::State X86ISA::Decoder::doResetState () protected
Definition at line 43 of file decoder.cc.
References basePC, chunkIdx, X86ISA::Decoder::InstBytes::chunks, decodePages, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, DPRINTF, emi, FromCacheState, X86ISA::ExtMachInst::immediate, immediateCollected, instBytes, X86ISA::ExtMachInst::legacy, DecodeCache::AddrMap< Value >::lookup(), X86ISA::ExtMachInst::modRM, offset, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, origPC, PrefixState, X86ISA::ExtMachInst::rex, X86ISA::Decoder::InstBytes::si, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::type, and X86ISA::ExtMachInst::vex.
Referenced by process().
doSIBState()
Decoder::State X86ISA::Decoder::doSIBState (uint8_t nextByte) protected
Definition at line 565 of file decoder.cc.
References consumeByte(), displacementSize, DisplacementState, DPRINTF, emi, ErrorState, immediateSize, ImmediateState, instDone, X86ISA::ExtMachInst::modRM, ResetState, and X86ISA::ExtMachInst::sib.
Referenced by process().
doThreeByte0F38OpcodeState()
Decoder::State X86ISA::Decoder::doThreeByte0F38OpcodeState (uint8_t nextByte) protected
Definition at line 422 of file decoder.cc.
References consumeByte(), DPRINTF, emi, ImmediateTypeThreeByte0F38, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), X86ISA::ExtMachInst::type, and UsesModRMThreeByte0F38.
Referenced by process().
doThreeByte0F3AOpcodeState()
Decoder::State X86ISA::Decoder::doThreeByte0F3AOpcodeState (uint8_t nextByte) protected
Definition at line 436 of file decoder.cc.
References consumeByte(), DPRINTF, emi, ImmediateTypeThreeByte0F3A, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), X86ISA::ExtMachInst::type, and UsesModRMThreeByte0F3A.
Referenced by process().
doTwoByteOpcodeState()
Decoder::State X86ISA::Decoder::doTwoByteOpcodeState (uint8_t nextByte) protected
Definition at line 399 of file decoder.cc.
References consumeByte(), DPRINTF, emi, ErrorState, ImmediateTypeTwoByte, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), ThreeByte0F38OpcodeState, ThreeByte0F3AOpcodeState, X86ISA::ExtMachInst::type, and UsesModRMTwoByte.
Referenced by process().
doVex2Of2State()
Decoder::State X86ISA::Decoder::doVex2Of2State (uint8_t nextByte) protected
Definition at line 245 of file decoder.cc.
References consumeByte(), emi, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::type, X86ISA::ExtMachInst::vex, and VexOpcodeState.
Referenced by process().
doVex2Of3State()
Decoder::State X86ISA::Decoder::doVex2Of3State (uint8_t nextByte) protected
Definition at line 275 of file decoder.cc.
References bits(), consumeByte(), emi, ImmediateTypeOneByte, instDone, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), ResetState, X86ISA::ExtMachInst::rex, X86ISA::SixtyFourBitMode, X86ISA::ExtMachInst::type, UsesModRMOneByte, X86ISA::ExtMachInst::vex, and Vex3Of3State.
Referenced by process().
doVex3Of3State()
Decoder::State X86ISA::Decoder::doVex3Of3State (uint8_t nextByte) protected
Definition at line 316 of file decoder.cc.
References bits(), consumeByte(), emi, ImmediateTypeOneByte, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, processOpcode(), X86ISA::ExtMachInst::rex, X86ISA::SixtyFourBitMode, X86ISA::ExtMachInst::type, UsesModRMOneByte, X86ISA::ExtMachInst::vex, and VexOpcodeState.
Referenced by process().
doVexOpcodeState()
Decoder::State X86ISA::Decoder::doVexOpcodeState (uint8_t nextByte) protected
Definition at line 353 of file decoder.cc.
References consumeByte(), DPRINTF, emi, ImmediateTypeThreeByte0F38, ImmediateTypeThreeByte0F3A, ImmediateTypeTwoByte, X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, panic, processOpcode(), X86ISA::ExtMachInst::type, UsesModRMThreeByte0F38, UsesModRMThreeByte0F3A, and UsesModRMTwoByte.
Referenced by process().
getImmediate()
void X86ISA::Decoder::getImmediate (int & collected, uint64_t & current, int size) inline protected
Definition at line 111 of file decoder.hh.
References consumeBytes(), immediateCollected, and X86ISA::mask.
Referenced by doDisplacementState(), and doImmediateState().
getNextByte()
uint8_t X86ISA::Decoder::getNextByte () inline protected
Definition at line 106 of file decoder.hh.
References offset.
Referenced by process().
instReady()
bool X86ISA::Decoder::instReady () inline
Definition at line 323 of file decoder.hh.
References instDone.
moreBytes()
void X86ISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst data) inline
Definition at line 308 of file decoder.hh.
References DPRINTF, GenericISA::PCStateBase::instAddr(), letoh(), and process().
needMoreBytes()
bool X86ISA::Decoder::needMoreBytes () inline
Definition at line 318 of file decoder.hh.
References outOfBytes.
process()
void X86ISA::Decoder::process ()
Definition at line 74 of file decoder.cc.
References X86ISA::Decoder::InstBytes::chunks, DisplacementState, doDisplacementState(), doFromCacheState(), doImmediateState(), doModRMState(), doOneByteOpcodeState(), doPrefixState(), doResetState(), doSIBState(), doThreeByte0F38OpcodeState(), doThreeByte0F3AOpcodeState(), doTwoByteOpcodeState(), doVex2Of2State(), doVex2Of3State(), doVex3Of3State(), doVexOpcodeState(), ErrorState, fetchChunk, FromCacheState, getNextByte(), ImmediateState, instBytes, instDone, ModRMState, OneByteOpcodeState, outOfBytes, panic, PrefixState, ResetState, SIBState, state, ThreeByte0F38OpcodeState, ThreeByte0F3AOpcodeState, TwoByteOpcodeState, Vex2Of2State, Vex2Of3State, Vex3Of3State, and VexOpcodeState.
Referenced by moreBytes(), and reset().
processExtendedOpcode()
State X86ISA::Decoder::processExtendedOpcode (ByteTable & immTable) protected
processOpcode()
Decoder::State X86ISA::Decoder::processOpcode (ByteTable & immTable, ByteTable & modrmTable, bool addrSizedImm = false) protected
Definition at line 450 of file decoder.cc.
References X86ISA::ExtMachInst::addrSize, altAddr, altOp, defAddr, defOp, emi, ErrorState, immediateSize, ImmediateState, instDone, X86ISA::ExtMachInst::legacy, ModRMState, X86ISA::ExtMachInst::op, ArmISA::opcode, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, ResetState, X86ISA::ExtMachInst::rex, SizeTypeToSize, stack, and X86ISA::ExtMachInst::stackSize.
Referenced by doOneByteOpcodeState(), doThreeByte0F38OpcodeState(), doThreeByte0F3AOpcodeState(), doTwoByteOpcodeState(), doVex2Of3State(), doVex3Of3State(), and doVexOpcodeState().
reset()
void X86ISA::Decoder::reset () inline
Definition at line 299 of file decoder.hh.
References process(), and ResetState.
setM5Reg()
void X86ISA::Decoder::setM5Reg (HandyM5Reg m5Reg) inline
Definition at line 257 of file decoder.hh.
References decodePages, instMap, mode, X86ISA::ExtMachInst::mode, and submode.
takeOverFrom()
void X86ISA::Decoder::takeOverFrom (Decoder * old) inline
Definition at line 286 of file decoder.hh.
References altAddr, altOp, defAddr, defOp, mode, X86ISA::ExtMachInst::mode, stack, and submode.
updateNPC()
void X86ISA::Decoder::updateNPC (X86ISA::PCState & nextPC) inline
Definition at line 329 of file decoder.hh.
References X86ISA::addr, decode(), decodeInst(), DPRINTF, GenericISA::SimplePCState< MachInst >::npc(), origPC, GenericISA::SimplePCState< MachInst >::pc(), and X86ISA::PCState::size().
Referenced by decode().
updateOffsetState()
void X86ISA::Decoder::updateOffsetState () inline protected
Definition at line 134 of file decoder.hh.
References chunkIdx, X86ISA::Decoder::InstBytes::chunks, DPRINTF, and outOfBytes.
Referenced by consumeByte(), and consumeBytes().
Member Data Documentation
addrCacheMap
AddrCacheMap X86ISA::Decoder::addrCacheMap protected
Definition at line 230 of file decoder.hh.
altAddr
uint8_t X86ISA::Decoder::altAddr protected
Definition at line 102 of file decoder.hh.
Referenced by processOpcode(), and takeOverFrom().
altOp
uint8_t X86ISA::Decoder::altOp protected
Definition at line 100 of file decoder.hh.
Referenced by processOpcode(), and takeOverFrom().
basePC
Addr X86ISA::Decoder::basePC protected
Definition at line 90 of file decoder.hh.
Referenced by decode(), doFromCacheState(), and doResetState().
chunkIdx
int X86ISA::Decoder::chunkIdx protected
Definition at line 88 of file decoder.hh.
Referenced by doFromCacheState(), doResetState(), and updateOffsetState().
decodePages
DecodePages* X86ISA::Decoder::decodePages protected
Definition at line 228 of file decoder.hh.
Referenced by doResetState(), and setM5Reg().
defAddr
uint8_t X86ISA::Decoder::defAddr protected
Definition at line 103 of file decoder.hh.
Referenced by processOpcode(), and takeOverFrom().
defOp
uint8_t X86ISA::Decoder::defOp protected
Definition at line 101 of file decoder.hh.
Referenced by doModRMState(), processOpcode(), and takeOverFrom().
displacementSize
int X86ISA::Decoder::displacementSize protected
Definition at line 170 of file decoder.hh.
Referenced by doDisplacementState(), doModRMState(), and doSIBState().
dummy
Decoder::InstBytes X86ISA::Decoder::dummy static protected
Definition at line 83 of file decoder.hh.
Referenced by Decoder(), and doImmediateState().
emi
ExtMachInst X86ISA::Decoder::emi protected
Definition at line 96 of file decoder.hh.
Referenced by decode(), doDisplacementState(), doImmediateState(), doModRMState(), doOneByteOpcodeState(), doPrefixState(), doResetState(), doSIBState(), doThreeByte0F38OpcodeState(), doThreeByte0F3AOpcodeState(), doTwoByteOpcodeState(), doVex2Of2State(), doVex2Of3State(), doVex3Of3State(), doVexOpcodeState(), and processOpcode().
fetchChunk
MachInst X86ISA::Decoder::fetchChunk protected
Definition at line 86 of file decoder.hh.
Referenced by doFromCacheState(), and process().
immediateCollected
int X86ISA::Decoder::immediateCollected protected
Definition at line 175 of file decoder.hh.
Referenced by doDisplacementState(), doImmediateState(), doResetState(), and getImmediate().
immediateSize
int X86ISA::Decoder::immediateSize protected
Definition at line 172 of file decoder.hh.
Referenced by doDisplacementState(), doImmediateState(), doModRMState(), doSIBState(), and processOpcode().
ImmediateTypeOneByte
const Decoder::ByteTable X86ISA::Decoder::ImmediateTypeOneByte static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 , 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 ,
 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 , 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 ,
 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 , 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 ,
 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 , 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , ZW, ZW, BY, BY, 0 , 0 , 0 , 0 ,
 BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY, BY,
 BY, ZW, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 VW, VW, VW, VW, 0 , 0 , 0 , 0 , BY, ZW, 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, BY, BY, BY, BY, BY, VW, VW, VW, VW, VW, VW, VW, VW,
 BY, BY, WO, 0 , 0 , 0 , BY, ZW, EN, 0 , WO, 0 , 0 , BY, 0 , 0 ,
 0 , 0 , 0 , 0 , BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, BY, BY, BY, BY, BY, ZW, ZW, PO, BY, 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 65 of file decoder.hh.
Referenced by doOneByteOpcodeState(), doVex2Of3State(), and doVex3Of3State().
ImmediateTypeThreeByte0F38
const Decoder::ByteTable X86ISA::Decoder::ImmediateTypeThreeByte0F38 static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 67 of file decoder.hh.
Referenced by doThreeByte0F38OpcodeState(), and doVexOpcodeState().
ImmediateTypeThreeByte0F3A
const Decoder::ByteTable X86ISA::Decoder::ImmediateTypeThreeByte0F3A static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , BY, BY, BY, BY, BY, BY, BY, BY,
 0 , 0 , 0 , 0 , BY, BY, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, 0 , BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , BY,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 68 of file decoder.hh.
Referenced by doThreeByte0F3AOpcodeState(), and doVexOpcodeState().
ImmediateTypeTwoByte
const Decoder::ByteTable X86ISA::Decoder::ImmediateTypeTwoByte static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , WO, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , BY,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 BY, BY, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW, ZW,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , BY, 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , ZW, 0 , BY, 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , BY, 0 , BY, BY, BY, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 66 of file decoder.hh.
Referenced by doTwoByteOpcodeState(), and doVexOpcodeState().
ImmediateTypeVex
ByteTable X86ISA::Decoder::ImmediateTypeVex[10] static private
Definition at line 69 of file decoder.hh.
instBytes
InstBytes* X86ISA::Decoder::instBytes protected
Definition at line 87 of file decoder.hh.
Referenced by decode(), doFromCacheState(), doResetState(), and process().
instCacheMap
Decoder::InstCacheMap X86ISA::Decoder::instCacheMap static protected
Definition at line 235 of file decoder.hh.
Referenced by doImmediateState().
instDone
bool X86ISA::Decoder::instDone protected
Definition at line 168 of file decoder.hh.
Referenced by decode(), doDisplacementState(), doFromCacheState(), doImmediateState(), doModRMState(), doSIBState(), doVex2Of3State(), instReady(), process(), and processOpcode().
instMap
DecodeCache::InstMap<ExtMachInst>* X86ISA::Decoder::instMap protected
Definition at line 232 of file decoder.hh.
Referenced by decode(), and setM5Reg().
mode
X86Mode X86ISA::Decoder::mode protected
Definition at line 98 of file decoder.hh.
Referenced by Decoder(), setM5Reg(), and takeOverFrom().
offset
int X86ISA::Decoder::offset protected
Definition at line 94 of file decoder.hh.
Referenced by decode(), doFromCacheState(), doResetState(), and getNextByte().
origPC
Addr X86ISA::Decoder::origPC protected
Definition at line 92 of file decoder.hh.
Referenced by decode(), doFromCacheState(), doResetState(), and updateNPC().
outOfBytes
bool X86ISA::Decoder::outOfBytes protected
Definition at line 166 of file decoder.hh.
Referenced by doFromCacheState(), needMoreBytes(), process(), and updateOffsetState().
Prefixes
const Decoder::ByteTable X86ISA::Decoder::Prefixes static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , ES, 0 , 0 , 0 , 0 , 0 , 0 , 0 , CS, 0,
 0 , 0 , 0 , 0 , 0 , 0 , SS, 0 , 0 , 0 , 0 , 0 , 0 , 0 , DS, 0,
 RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX, RX,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , FS, GS, OO, AO, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , V3, V2, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 LO, 0 , RN, RE, 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 58 of file decoder.hh.
SizeTypeToSize
const uint8_t X86ISA::Decoder::SizeTypeToSize static private
Initial value:
=
    {
        {0,    1,   2,   4,    8,    16,   2,    2,    3,    4      },
        {0,    1,   2,   4,    8,    16,   4,    4,    3,    6      },
        {0,    1,   2,   4,    8,    16,   8,    4,    3,    0      }
    }
Definition at line 56 of file decoder.hh.
Referenced by processOpcode().
stack
uint8_t X86ISA::Decoder::stack protected
Definition at line 104 of file decoder.hh.
Referenced by processOpcode(), and takeOverFrom().
state
State X86ISA::Decoder::state protected
Definition at line 197 of file decoder.hh.
Referenced by process().
submode
X86SubMode X86ISA::Decoder::submode protected
Definition at line 99 of file decoder.hh.
Referenced by Decoder(), setM5Reg(), and takeOverFrom().
UsesModRMOneByte
const Decoder::ByteTable X86ISA::Decoder::UsesModRMOneByte static private
Initial value:
=
    {
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 1 , 0 , 1 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 1
    }
Definition at line 60 of file decoder.hh.
Referenced by doOneByteOpcodeState(), doVex2Of3State(), and doVex3Of3State().
UsesModRMThreeByte0F38
const Decoder::ByteTable X86ISA::Decoder::UsesModRMThreeByte0F38 static private
Initial value:
=
    {
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 1 , 0 , 0 , 0 , 1 , 1 , 0 , 1 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 0 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 62 of file decoder.hh.
Referenced by doThreeByte0F38OpcodeState(), and doVexOpcodeState().
UsesModRMThreeByte0F3A
const Decoder::ByteTable X86ISA::Decoder::UsesModRMThreeByte0F3A static private
Initial value:
=
    {
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 0 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
    }
Definition at line 63 of file decoder.hh.
Referenced by doThreeByte0F3AOpcodeState(), and doVexOpcodeState().
UsesModRMTwoByte
const Decoder::ByteTable X86ISA::Decoder::UsesModRMTwoByte static private
Initial value:
=
    {
 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 0 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 0 , 1 , 0 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1,
 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 1 , 0
    }
Definition at line 61 of file decoder.hh.
Referenced by doTwoByteOpcodeState(), and doVexOpcodeState().
The documentation for this class was generated from the following files:
arch/x86/decoder.hh
arch/x86/decoder.cc
arch/x86/decoder_tables.cc