gem5: CompressedTags Class Reference
CompressedTags Class Reference
A CompressedTags cache tag store.
#include <compressed_tags.hh>
Public Types
typedef CompressedTagsParams Params
Convenience typedef.
Public Types inherited from SectorTags
typedef SectorTagsParams Params
Convenience typedef.
Public Types inherited from BaseTags
typedef BaseTagsParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
CompressedTags (const Params *p)
Construct and initialize this tag store.
virtual ~CompressedTags ()
Destructor.
void tagsInit () override
Initialize blocks as SuperBlk and CompressionBlk instances.
CacheBlk * findVictim (Addr addr, const bool is_secure, const std::size_t compressed_size, std::vector< CacheBlk *> &evict_blks) const override
Find replacement victim based on address.
void insertBlock (const PacketPtr pkt, CacheBlk *blk) override
Insert the new block into the cache and update replacement data.
void forEachBlk (std::function< void(CacheBlk &)> visitor) override
Visit each sub-block in the tags and apply a visitor.
bool anyBlk (std::function< bool(CacheBlk &)> visitor) override
Find if any of the sub-blocks satisfies a condition.
Public Member Functions inherited from SectorTags
SectorTags (const Params *p)
Construct and initialize this tag store.
virtual ~SectorTags ()
Destructor.
void tagsInit () override
Initialize blocks as SectorBlk and SectorSubBlk instances.
void invalidate (CacheBlk *blk) override
This function updates the tags when a block is invalidated but does not invalidate the block itself.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat) override
Access block and update replacement data.
void insertBlock (const PacketPtr pkt, CacheBlk *blk) override
Insert the new block into the cache and update replacement data.
CacheBlk * findBlock (Addr addr, bool is_secure) const override
Finds the given address in the cache, do not update replacement data.
CacheBlk * findVictim (Addr addr, const bool is_secure, const std::size_t size, std::vector< CacheBlk *> &evict_blks) const override
Find replacement victim based on address.
int extractSectorOffset (Addr addr) const
Calculate a block's offset in a sector from the address.
Addr regenerateBlkAddr (const CacheBlk *blk) const override
Regenerate the block address from the tag and location.
void forEachBlk (std::function< void(CacheBlk &)> visitor) override
Visit each sub-block in the tags and apply a visitor.
bool anyBlk (std::function< bool(CacheBlk &)> visitor) override
Find if any of the sub-blocks satisfies a condition.
Public Member Functions inherited from BaseTags
BaseTags (const Params *p)
virtual ~BaseTags ()
Destructor.
void cleanupRefs ()
Average in the reference count for valid blocks when the simulation exits.
void computeStats ()
Computes stats just prior to dump event.
std::string print ()
Print all tags used.
virtual ReplaceableEntry * findBlockBySetAndWay (int set, int way) const
Find a block given set and way.
Addr blkAlign (Addr addr) const
Align an address to the block size.
int extractBlkOffset (Addr addr) const
Calculate the block offset of an address.
virtual void setWayAllocationMax (int ways)
Limit the allocation for the cache ways.
virtual int getWayAllocationMax () const
Get the way allocation mask limit.
virtual Addr extractTag (const Addr addr) const
Generate the tag from the given address.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Attributes
std::vector< CompressionBlk > blks
The cache blocks.
std::vector< SuperBlk > superBlks
The cache superblocks.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from SectorTags
unsigned allocAssoc
The allocatable associativity of the cache (alloc mask).
const bool sequentialAccess
Whether tags and data are accessed sequentially.
BaseReplacementPolicy * replacementPolicy
Replacement policy.
const unsigned numBlocksPerSector
Number of data blocks per sector.
const unsigned numSectors
The number of sectors in the cache.
const int sectorShift
The amount to shift the address to get the sector tag.
const unsigned sectorMask
Mask out all bits that aren't part of the sector tag.
Protected Attributes inherited from BaseTags
const unsigned blkSize
The block size of the cache.
const Addr blkMask
Mask out all bits that aren't part of the block offset.
const unsigned size
The size of the cache.
const Cycles lookupLatency
The tag lookup latency of the cache.
System * system
System we are currently operating in.
BaseIndexingPolicy * indexingPolicy
Indexing policy.
const unsigned warmupBound
The number of tags that need to be touched to meet the warmup percentage.
bool warmedUp
Marked true when the cache is warmed up.
const unsigned numBlocks
the number of blocks in the cache
std::unique_ptr< uint8_t[]> dataBlks
The data blocks, 1 per cache block.
BaseTags::BaseTagStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
A CompressedTags cache tag store.
See also
gem5 Memory System
The Compression Ratio (CR) of a superblock is defined by CR = uncompressed_size / compressed_size.
The CompressedTags placement policy divides the cache into s sets of w superblocks (ways). Each superblock can then contain up to CR compressed blocks.
For each tag entry there can be multiple data blocks. We have the same number of tags a conventional cache would have, but we instantiate the maximum number of data blocks (according to the compression ratio) per tag, to virtually implement compression without increasing the complexity of the simulator.
This is a simple implementation of cache compression, where superblocks can only have at most numBlocksPerSector compressed blocks, each compressed to at least (100/numBlocksPerSector)% of its size.
numBlocksPerSector holds the maximum number of blocks a superblock with the best possible compression factor would hold. It is equivalent to CR from the previous definition.
Definition at line 73 of file compressed_tags.hh.
Member Typedef Documentation
Params
typedef CompressedTagsParams CompressedTags::Params
Convenience typedef.
Definition at line 83 of file compressed_tags.hh.
Constructor & Destructor Documentation
CompressedTags()
CompressedTags::CompressedTags (const Params * p)
Construct and initialize this tag store.
Definition at line 46 of file compressed_tags.cc.
Referenced by anyBlk().
~CompressedTags()
virtual CompressedTags::~CompressedTags () inline virtual
Destructor.
Definition at line 93 of file compressed_tags.hh.
References addr, anyBlk(), findVictim(), forEachBlk(), insertBlock(), and tagsInit().
Member Function Documentation
anyBlk()
bool CompressedTags::anyBlk (std::function< bool(CacheBlk &)> visitor) override virtual
Find if any of the sub-blocks satisfies a condition.
The visitor should be a std::function that takes a cache block reference as its parameter. The visitor will terminate the traversal early if the condition is satisfied.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 196 of file compressed_tags.cc.
References blks, and CompressedTags().
Referenced by ~CompressedTags().
findVictim()
CacheBlk * CompressedTags::findVictim (Addr addr, const bool is_secure, const std::size_t compressed_size, std::vector< CacheBlk *> & evict_blks) const override virtual
Find replacement victim based on address.
Checks if data can be co- allocated before choosing blocks to be evicted.
Parameters
addr Address to find a victim for.
is_secure True if the target memory space is secure.
compressed_size Size, in bits, of new block to allocate.
evict_blks Cache blocks to be evicted.
Returns
Cache block to be replaced.
Implements BaseTags.
Definition at line 104 of file compressed_tags.cc.
References SectorBlk::blks, SuperBlk::canCoAllocate(), DPRINTF, DPRINTFR, SectorTags::extractSectorOffset(), BaseTags::extractTag(), BaseIndexingPolicy::getPossibleEntries(), SectorBlk::getTag(), BaseReplacementPolicy::getVictim(), BaseTags::indexingPolicy, SuperBlk::isCompressed(), SectorBlk::isSecure(), SectorBlk::isValid(), CacheBlk::isValid(), ArmISA::offset, and SectorTags::replacementPolicy.
Referenced by ~CompressedTags().
forEachBlk()
void CompressedTags::forEachBlk (std::function< void(CacheBlk &)> visitor) override virtual
Visit each sub-block in the tags and apply a visitor.
The visitor should be a std::function that takes a cache block. reference as its parameter.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 188 of file compressed_tags.cc.
References blks.
Referenced by ~CompressedTags().
insertBlock()
void CompressedTags::insertBlock (const PacketPtr pkt, CacheBlk * blk) override virtual
Insert the new block into the cache and update replacement data.
Parameters
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BaseTags.
Definition at line 166 of file compressed_tags.cc.
References SuperBlk::canCoAllocate(), SectorSubBlk::getSectorBlock(), CompressionBlk::getSizeBits(), SectorTags::insertBlock(), SuperBlk::isCompressed(), CompressionBlk::setCompressed(), and CompressionBlk::setUncompressed().
Referenced by ~CompressedTags().
tagsInit()
void CompressedTags::tagsInit () override virtual
Initialize blocks as SuperBlk and CompressionBlk instances.
Implements BaseTags.
Definition at line 52 of file compressed_tags.cc.
References blks, SectorBlk::blks, BaseTags::blkSize, CacheBlk::data, BaseTags::dataBlks, BaseTags::indexingPolicy, BaseReplacementPolicy::instantiateEntry(), MipsISA::k, BaseTags::numBlocks, SectorTags::numBlocksPerSector, SectorTags::numSectors, ReplaceableEntry::replacementData, SectorTags::replacementPolicy, SuperBlk::setBlkSize(), BaseIndexingPolicy::setEntry(), SectorSubBlk::setSectorBlock(), SectorSubBlk::setSectorOffset(), and superBlks.
Referenced by ~CompressedTags().
Member Data Documentation
blks
std::vector<CompressionBlk> CompressedTags::blks private
The cache blocks.
Definition at line 77 of file compressed_tags.hh.
Referenced by anyBlk(), forEachBlk(), and tagsInit().
superBlks
std::vector<SuperBlk> CompressedTags::superBlks private
The cache superblocks.
Definition at line 79 of file compressed_tags.hh.
Referenced by tagsInit().
The documentation for this class was generated from the following files:
mem/cache/tags/compressed_tags.hh
mem/cache/tags/compressed_tags.cc