gem5: Stats::VectorStatNode Class Reference
Stats::VectorStatNode Class Reference
#include <statistics.hh>
Public Member Functions
VectorStatNode (const VectorInfo *d)
const VResult & result () const
Return the result vector of this subtree.
Result total () const
Return the total of the result vector.
size_type size () const
Return the number of nodes in the subtree starting at this node.
std::string str () const
Public Member Functions inherited from Stats::Node
virtual ~Node ()
Private Attributes
const VectorInfo * data
Detailed Description
Definition at line 2200 of file statistics.hh.
Constructor & Destructor Documentation
VectorStatNode()
Stats::VectorStatNode::VectorStatNode (const VectorInfo * d) inline
Definition at line 2206 of file statistics.hh.
Member Function Documentation
result()
const VResult& Stats::VectorStatNode::result () const inline virtual
Return the result vector of this subtree.
Returns
The result vector of this subtree.
Implements Stats::Node.
Definition at line 2207 of file statistics.hh.
References Stats::VectorInfo::result().
size()
size_type Stats::VectorStatNode::size () const inline virtual
Return the number of nodes in the subtree starting at this node.
Returns
the number of nodes in this subtree.
Implements Stats::Node.
Definition at line 2210 of file statistics.hh.
References Stats::VectorInfo::size().
str()
std::string Stats::VectorStatNode::str () const inline virtual
Implements Stats::Node.
Definition at line 2212 of file statistics.hh.
References Stats::Info::name.
total()
Result Stats::VectorStatNode::total () const inline virtual
Return the total of the result vector.
Returns
The total of the result vector.
Implements Stats::Node.
Definition at line 2208 of file statistics.hh.
References Stats::VectorInfo::total().
Member Data Documentation
data
const VectorInfo* Stats::VectorStatNode::data private
Definition at line 2203 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh