gem5: Root Class Reference
Root Class Reference
#include <root.hh>
Public Types
typedef RootParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
bool timeSyncEnabled () const
Check whether time syncing is enabled.
const Time timeSyncPeriod () const
Retrieve the period for the sync event.
const Time timeSyncSpinThreshold () const
Retrieve the threshold for time remaining to spin wait.
void timeSyncEnable (bool en)
Enable or disable time syncing.
void timeSyncPeriod (Time newPeriod)
Configure the period for time sync events.
void timeSyncSpinThreshold (Time newThreshold)
Set the threshold for time remaining to spin wait.
const Params * params () const
Root (Params *p)
void startup () override
Schedule the timesync event at startup().
void serialize (CheckpointOut &cp) const override
Serialize an object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static Root * root ()
Use this function to get a pointer to the single Root object in the simulation.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions
void timeSync ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
bool _enabled
Time _period
Tick _periodTick
Time _spinThreshold
Time lastTime
EventFunctionWrapper syncEvent
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Private Attributes
static Root * _root = NULL
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 49 of file root.hh.
Member Typedef Documentation
Params
typedef RootParams Root::Params
Definition at line 97 of file root.hh.
Constructor & Destructor Documentation
Root()
Root::Root (Params * p)
Definition at line 107 of file root.cc.
References _period, _root, _spinThreshold, lastTime, SimObject::name(), MipsISA::p, Time::setTick(), Time::setTimer(), simQuantum, and timeSync().
Referenced by params().
Member Function Documentation
params()
const Params* Root::params () const inline
Definition at line 99 of file root.hh.
References SimObject::_params, MipsISA::p, Root(), serialize(), and startup().
Referenced by startup().
root()
static Root* Root::root () inline static
Use this function to get a pointer to the single Root object in the simulation.
This function asserts that such an object has actual been constructed to avoid having to perform that check everywhere the root is used. This is to allow calling the functions below.
Returns
Pointer to the single root object.
Definition at line 75 of file root.hh.
References _root.
serialize()
void Root::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 128 of file root.cc.
References FullSystem, and SERIALIZE_SCALAR.
Referenced by params().
startup()
void Root::startup () override virtual
Schedule the timesync event at startup().
Reimplemented from SimObject.
Definition at line 122 of file root.cc.
References params(), and timeSyncEnable().
Referenced by params().
timeSync()
void Root::timeSync () protected
Definition at line 51 of file root.cc.
References _periodTick, _spinThreshold, curTick(), DPRINTF, lastTime, sc_dt::remainder, EventManager::schedule(), Time::setTimer(), sleep(), syncEvent, and timeSyncPeriod().
Referenced by Root().
timeSyncEnable()
void Root::timeSyncEnable (bool en)
Enable or disable time syncing.
Definition at line 72 of file root.cc.
References _enabled, _periodTick, curTick(), EventManager::deschedule(), ArmISA::en, EventManager::schedule(), and syncEvent.
Referenced by startup(), timeSyncPeriod(), and timeSyncSpinThreshold().
timeSyncEnabled()
bool Root::timeSyncEnabled () const inline
Check whether time syncing is enabled.
Definition at line 84 of file root.hh.
References _enabled.
Referenced by timeSyncPeriod(), and timeSyncSpinThreshold().
timeSyncPeriod() [1/2]
const Time Root::timeSyncPeriod () const inline
Retrieve the period for the sync event.
Definition at line 86 of file root.hh.
References _period.
Referenced by timeSync(), and timeSyncSpinThreshold().
timeSyncPeriod() [2/2]
void Root::timeSyncPeriod (Time newPeriod)
Configure the period for time sync events.
Definition at line 90 of file root.cc.
References _period, _periodTick, ArmISA::en, Time::getTick(), timeSyncEnable(), and timeSyncEnabled().
timeSyncSpinThreshold() [1/2]
const Time Root::timeSyncSpinThreshold () const inline
Retrieve the threshold for time remaining to spin wait.
Definition at line 88 of file root.hh.
References _spinThreshold, ArmISA::en, timeSyncEnable(), and timeSyncPeriod().
timeSyncSpinThreshold() [2/2]
void Root::timeSyncSpinThreshold (Time newThreshold)
Set the threshold for time remaining to spin wait.
Definition at line 100 of file root.cc.
References _spinThreshold, ArmISA::en, timeSyncEnable(), and timeSyncEnabled().
Member Data Documentation
_enabled
bool Root::_enabled protected
Definition at line 55 of file root.hh.
Referenced by timeSyncEnable(), and timeSyncEnabled().
_period
Time Root::_period protected
Definition at line 56 of file root.hh.
Referenced by Root(), and timeSyncPeriod().
_periodTick
Tick Root::_periodTick protected
Definition at line 57 of file root.hh.
Referenced by timeSync(), timeSyncEnable(), and timeSyncPeriod().
_root
Root * Root::_root = NULL static private
Definition at line 52 of file root.hh.
Referenced by root(), and Root().
_spinThreshold
Time Root::_spinThreshold protected
Definition at line 58 of file root.hh.
Referenced by Root(), timeSync(), and timeSyncSpinThreshold().
lastTime
Time Root::lastTime protected
Definition at line 60 of file root.hh.
Referenced by Root(), and timeSync().
syncEvent
EventFunctionWrapper Root::syncEvent protected
Definition at line 63 of file root.hh.
Referenced by timeSync(), and timeSyncEnable().
The documentation for this class was generated from the following files:
sim/root.hh
sim/root.cc