gem5: NSGigE Class Reference
NSGigE Class Reference
NS DP83820 Ethernet device model.
#include <ns_gige.hh>
Public Types
enum TxState {
txIdle, txDescRefr, txDescRead, txFifoBlock,
txFragRead, txDescWrite, txAdvance
}
Transmit State Machine states.
enum RxState {
rxIdle, rxDescRefr, rxDescRead, rxFifoBlock,
rxFragWrite, rxDescWrite, rxAdvance
}
Receive State Machine States.
enum DmaState {
dmaIdle, dmaReading, dmaWriting, dmaReadWaiting,
dmaWriteWaiting
}
enum EEPROMState { eepromStart, eepromGetOpcode, eepromGetAddress, eepromRead }
EEPROM State Machine States.
typedef NSGigEParams Params
Public Types inherited from EtherDevice
typedef EtherDeviceParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
NSGigE (Params *params)
~NSGigE ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Tick writeConfig (PacketPtr pkt) override
This is to write to the PCI general configuration registers.
Tick read (PacketPtr pkt) override
This reads the device registers, which are detailed in the NS83820 spec sheet.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
bool cpuIntrPending () const
void cpuIntrAck ()
bool recvPacket (EthPacketPtr packet)
void transferDone ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
Public Member Functions inherited from EtherDevBase
EtherDevBase (const EtherDevBaseParams *params)
const EtherDevBaseParams * params () const
Public Member Functions inherited from EtherDevice
EtherDevice (const Params *params)
const Params * params () const
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from PciDevice
virtual Tick readConfig (PacketPtr pkt)
Read from the PCI config space data that is stored locally.
Addr pciToDma (Addr pci_addr) const
void intrPost ()
void intrClear ()
uint8_t interruptLine () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
PciDevice (const PciDeviceParams *params)
Constructor for PCI Dev.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
const PciBusAddr & busAddr () const
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool doRxDmaRead ()
bool doRxDmaWrite ()
bool doTxDmaRead ()
bool doTxDmaWrite ()
void rxDmaReadDone ()
void rxDmaWriteDone ()
void txDmaReadDone ()
void txDmaWriteDone ()
void txReset ()
void rxReset ()
void regsReset ()
void rxKick ()
void txKick ()
void eepromKick ()
Advance the EEPROM state machine Called on rising edge of EEPROM clock bit in MEAR.
void transmit ()
Retransmit event.
void txEventTransmit ()
void txDump () const
void rxDump () const
bool rxFilter (const EthPacketPtr &packet)
void devIntrPost (uint32_t interrupts)
Interrupt management.
void devIntrClear (uint32_t interrupts)
void devIntrChangeMask ()
void cpuIntrPost (Tick when)
void cpuInterrupt ()
void cpuIntrClear ()
Protected Member Functions inherited from PciDevice
bool isLargeBAR (int bar) const
Does the given BAR represent 32 lower bits of a 64-bit address?
bool isBAR (Addr addr, int bar) const
Does the given address lie within the space mapped by the given base address register?
int getBAR (Addr addr)
Which base address register (if any) maps the given address?
bool getBAR (Addr addr, int &bar, Addr &offs)
Which base address register (if any) maps the given address?
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
dp_regs regs
device register file
dp_rom rom
bool ioEnable
pci settings
PacketFifo txFifo
PacketFifo rxFifo
EthPacketPtr txPacket
various helper vars
EthPacketPtr rxPacket
uint8_t * txPacketBufPtr
uint8_t * rxPacketBufPtr
uint32_t txXferLen
uint32_t rxXferLen
bool rxDmaFree
bool txDmaFree
ns_desc32 txDesc32
DescCaches.
ns_desc32 rxDesc32
ns_desc64 txDesc64
ns_desc64 rxDesc64
TxState txState
bool txEnable
bool CTDD
Current Transmit Descriptor Done.
bool txHalt
halt the tx state machine after next packet
Addr txFragPtr
ptr to the next byte in the current fragment
uint32_t txDescCnt
count of bytes remaining in the current descriptor
DmaState txDmaState
RxState rxState
rx State Machine
bool rxEnable
bool CRDD
Current Receive Descriptor Done.
uint32_t rxPktBytes
num of bytes in the current packet being drained from rxDataFifo
bool rxHalt
halt the rx state machine after current packet
Addr rxFragPtr
ptr to the next byte in current fragment
uint32_t rxDescCnt
count of bytes remaining in the current descriptor
DmaState rxDmaState
bool extstsEnable
EEPROMState eepromState
EEPROM State Machine.
bool eepromClk
uint8_t eepromBitsToRx
uint8_t eepromOpcode
uint8_t eepromAddress
uint16_t eepromData
Tick dmaReadDelay
Tick dmaWriteDelay
Tick dmaReadFactor
Tick dmaWriteFactor
void * rxDmaData
Addr rxDmaAddr
int rxDmaLen
void * txDmaData
Addr txDmaAddr
int txDmaLen
EventFunctionWrapper rxDmaReadEvent
EventFunctionWrapper rxDmaWriteEvent
EventFunctionWrapper txDmaReadEvent
EventFunctionWrapper txDmaWriteEvent
bool dmaDescFree
bool dmaDataFree
Tick txDelay
Tick rxDelay
Tick rxKickTick
EventFunctionWrapper rxKickEvent
Tick txKickTick
EventFunctionWrapper txKickEvent
EventFunctionWrapper txEvent
bool rxFilterEnable
receive address filter
bool acceptBroadcast
bool acceptMulticast
bool acceptUnicast
bool acceptPerfect
bool acceptArp
bool multicastHashEnable
Tick intrDelay
Tick intrTick
bool cpuPendingIntr
EventFunctionWrapper * intrEvent
NSGigEInt * interface
Protected Attributes inherited from EtherDevice
Stats::Scalar txBytes
Stats::Scalar rxBytes
Stats::Scalar txPackets
Stats::Scalar rxPackets
Stats::Scalar txIpChecksums
Stats::Scalar rxIpChecksums
Stats::Scalar txTcpChecksums
Stats::Scalar rxTcpChecksums
Stats::Scalar txUdpChecksums
Stats::Scalar rxUdpChecksums
Stats::Scalar descDmaReads
Stats::Scalar descDmaWrites
Stats::Scalar descDmaRdBytes
Stats::Scalar descDmaWrBytes
Stats::Formula totBandwidth
Stats::Formula totPackets
Stats::Formula totBytes
Stats::Formula totPacketRate
Stats::Formula txBandwidth
Stats::Formula rxBandwidth
Stats::Formula txPacketRate
Stats::Formula rxPacketRate
Stats::Scalar postedSwi
Stats::Formula coalescedSwi
Stats::Scalar totalSwi
Stats::Scalar postedRxIdle
Stats::Formula coalescedRxIdle
Stats::Scalar totalRxIdle
Stats::Scalar postedRxOk
Stats::Formula coalescedRxOk
Stats::Scalar totalRxOk
Stats::Scalar postedRxDesc
Stats::Formula coalescedRxDesc
Stats::Scalar totalRxDesc
Stats::Scalar postedTxOk
Stats::Formula coalescedTxOk
Stats::Scalar totalTxOk
Stats::Scalar postedTxIdle
Stats::Formula coalescedTxIdle
Stats::Scalar totalTxIdle
Stats::Scalar postedTxDesc
Stats::Formula coalescedTxDesc
Stats::Scalar totalTxDesc
Stats::Scalar postedRxOrn
Stats::Formula coalescedRxOrn
Stats::Scalar totalRxOrn
Stats::Formula coalescedTotal
Stats::Scalar postedInterrupts
Stats::Scalar droppedPackets
Protected Attributes inherited from PciDevice
const PciBusAddr _busAddr
PCIConfig config
The current config space.
std::vector< MSIXTable > msix_table
MSIX Table and PBA Structures.
std::vector< MSIXPbaEntry > msix_pba
uint32_t BARSize [6]
The size of the BARs.
Addr BARAddrs [6]
The current address mapping of the BARs.
bool legacyIO [6]
Whether the BARs are really hardwired legacy IO locations.
PciHost::DeviceInterface hostInterface
Tick pioDelay
Tick configDelay
const int PMCAP_BASE
The capability list structures and base addresses.
const int PMCAP_ID_OFFSET
const int PMCAP_PC_OFFSET
const int PMCAP_PMCS_OFFSET
PMCAP pmcap
const int MSICAP_BASE
MSICAP msicap
const int MSIXCAP_BASE
const int MSIXCAP_ID_OFFSET
const int MSIXCAP_MXC_OFFSET
const int MSIXCAP_MTAB_OFFSET
const int MSIXCAP_MPBA_OFFSET
int MSIX_TABLE_OFFSET
int MSIX_TABLE_END
int MSIX_PBA_OFFSET
int MSIX_PBA_END
MSIXCAP msixcap
const int PXCAP_BASE
PXCAP pxcap
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
NS DP83820 Ethernet device model.
Definition at line 121 of file ns_gige.hh.
Member Typedef Documentation
Params
typedef NSGigEParams NSGigE::Params
Definition at line 332 of file ns_gige.hh.
Member Enumeration Documentation
DmaState
enum NSGigE::DmaState
Enumerator
dmaIdle
dmaReading
dmaWriting
dmaReadWaiting
dmaWriteWaiting
Definition at line 148 of file ns_gige.hh.
EEPROMState
enum NSGigE::EEPROMState
EEPROM State Machine States.
Enumerator
eepromStart
eepromGetOpcode
eepromGetAddress
eepromRead
Definition at line 158 of file ns_gige.hh.
RxState
enum NSGigE::RxState
Receive State Machine States.
Enumerator
rxIdle
rxDescRefr
rxDescRead
rxFifoBlock
rxFragWrite
rxDescWrite
rxAdvance
Definition at line 137 of file ns_gige.hh.
TxState
enum NSGigE::TxState
Transmit State Machine states.
Enumerator
txIdle
txDescRefr
txDescRead
txFifoBlock
txFragRead
txDescWrite
txAdvance
Definition at line 125 of file ns_gige.hh.
Constructor & Destructor Documentation
NSGigE()
NSGigE::NSGigE (Params * params)
Definition at line 97 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, cpuPendingIntr, dmaDataFree, dmaDescFree, interface, intrDelay, intrEvent, intrTick, multicastHashEnable, SimObject::name(), MipsISA::p, dp_rom::perfectMatch, regsReset(), rom, rxDelay, rxDesc32, rxDesc64, rxDmaReadDone(), rxDmaWriteDone(), rxDmaWriteEvent, rxFilterEnable, rxKick(), rxKickEvent, rxKickTick, txDelay, txDesc32, txDesc64, txDmaReadDone(), txDmaReadEvent, txDmaWriteDone(), txDmaWriteEvent, txEvent, txEventTransmit(), txKick(), txKickEvent, and txKickTick.
Referenced by unserialize().
~NSGigE()
NSGigE::~NSGigE ()
Definition at line 142 of file ns_gige.cc.
References interface.
Member Function Documentation
cpuInterrupt()
void NSGigE::cpuInterrupt () protected
Definition at line 880 of file ns_gige.cc.
References cpuPendingIntr, curTick(), DPRINTF, intrEvent, PciDevice::intrPost(), and intrTick.
Referenced by cpuIntrPost(), and unserialize().
cpuIntrAck()
void NSGigE::cpuIntrAck () inline
Definition at line 349 of file ns_gige.hh.
References serialize(), and unserialize().
cpuIntrClear()
void NSGigE::cpuIntrClear () protected
Definition at line 903 of file ns_gige.cc.
References cpuPendingIntr, DPRINTF, PciDevice::intrClear(), intrEvent, intrTick, and Event::squash().
Referenced by devIntrChangeMask(), and devIntrClear().
cpuIntrPending()
bool NSGigE::cpuIntrPending () const
Definition at line 922 of file ns_gige.cc.
References cpuPendingIntr.
cpuIntrPost()
void NSGigE::cpuIntrPost (Tick when) protected
Todo:
this warning should be removed and the intrTick code should be fixed.
Definition at line 844 of file ns_gige.cc.
References cpuInterrupt(), curTick(), DPRINTF, intrEvent, intrTick, SimObject::name(), EventManager::schedule(), and Event::squash().
Referenced by devIntrChangeMask(), and devIntrPost().
devIntrChangeMask()
void NSGigE::devIntrChangeMask () protected
Definition at line 832 of file ns_gige.cc.
References cpuIntrClear(), cpuIntrPost(), curTick(), DPRINTF, dp_regs::imr, dp_regs::isr, and regs.
Referenced by write().
devIntrClear()
void NSGigE::devIntrClear (uint32_t interrupts) protected
Definition at line 790 of file ns_gige.cc.
References cpuIntrClear(), DPRINTF, dp_regs::imr, dp_regs::isr, ISR_NOIMPL, ISR_RESERVE, ISR_RXDESC, ISR_RXIDLE, ISR_RXOK, ISR_RXORN, ISR_SWI, ISR_TXDESC, ISR_TXIDLE, ISR_TXOK, panic, EtherDevice::postedRxDesc, EtherDevice::postedRxIdle, EtherDevice::postedRxOk, EtherDevice::postedRxOrn, EtherDevice::postedSwi, EtherDevice::postedTxDesc, EtherDevice::postedTxIdle, EtherDevice::postedTxOk, and regs.
Referenced by read().
devIntrPost()
void NSGigE::devIntrPost (uint32_t interrupts) protected
Interrupt management.
Definition at line 733 of file ns_gige.cc.
References cpuIntrPost(), curTick(), DPRINTF, dp_regs::imr, intrDelay, dp_regs::isr, ISR_IMPL, ISR_NODELAY, ISR_NOIMPL, ISR_RESERVE, ISR_RXDESC, ISR_RXIDLE, ISR_RXOK, ISR_RXORN, ISR_SWI, ISR_TXDESC, ISR_TXIDLE, ISR_TXOK, panic, EtherDevice::postedInterrupts, regs, EtherDevice::totalRxDesc, EtherDevice::totalRxIdle, EtherDevice::totalRxOk, EtherDevice::totalRxOrn, EtherDevice::totalSwi, EtherDevice::totalTxDesc, EtherDevice::totalTxIdle, EtherDevice::totalTxOk, and warn.
Referenced by recvPacket(), rxKick(), transmit(), txKick(), and write().
doRxDmaRead()
bool NSGigE::doRxDmaRead () protected
Definition at line 979 of file ns_gige.cc.
References dmaIdle, DmaDevice::dmaPending(), DmaDevice::dmaRead(), dmaReading, dmaReadWaiting, Drainable::drainState(), Running, rxDmaAddr, rxDmaData, rxDmaLen, rxDmaReadEvent, and rxDmaState.
Referenced by rxKick().
doRxDmaWrite()
bool NSGigE::doRxDmaWrite () protected
Definition at line 1010 of file ns_gige.cc.
References dmaIdle, DmaDevice::dmaPending(), DmaDevice::dmaWrite(), dmaWriteWaiting, dmaWriting, Drainable::drainState(), Running, rxDmaAddr, rxDmaData, rxDmaLen, rxDmaState, and rxDmaWriteEvent.
Referenced by rxKick().
doTxDmaRead()
bool NSGigE::doTxDmaRead () protected
Definition at line 1406 of file ns_gige.cc.
References dmaIdle, DmaDevice::dmaPending(), DmaDevice::dmaRead(), dmaReading, dmaReadWaiting, Drainable::drainState(), Running, txDmaAddr, txDmaData, txDmaLen, txDmaReadEvent, and txDmaState.
Referenced by txKick().
doTxDmaWrite()
bool NSGigE::doTxDmaWrite () protected
Definition at line 1437 of file ns_gige.cc.
References dmaIdle, DmaDevice::dmaPending(), DmaDevice::dmaWrite(), dmaWriteWaiting, dmaWriting, Drainable::drainState(), Running, txDmaAddr, txDmaData, txDmaLen, txDmaState, and txDmaWriteEvent.
Referenced by txKick().
drainResume()
void NSGigE::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 2002 of file ns_gige.cc.
References Drainable::drainResume(), rxKick(), and txKick().
eepromKick()
void NSGigE::eepromKick () protected
Advance the EEPROM state machine Called on rising edge of EEPROM clock bit in MEAR.
Definition at line 1799 of file ns_gige.cc.
References EEPROM_PMATCH0_ADDR, EEPROM_PMATCH1_ADDR, EEPROM_PMATCH2_ADDR, EEPROM_READ, EEPROM_SIZE, eepromAddress, eepromBitsToRx, eepromData, eepromGetAddress, eepromGetOpcode, eepromOpcode, eepromRead, eepromStart, eepromState, dp_regs::mear, MEAR_EEDI, MEAR_EEDO, panic, dp_rom::perfectMatch, regs, and rom.
Referenced by write().
getPort()
Port & NSGigE::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from DmaDevice.
Definition at line 175 of file ns_gige.cc.
References DmaDevice::getPort(), and interface.
params()
const Params* NSGigE::params () const inline
Definition at line 333 of file ns_gige.hh.
References InvalidPortID.
Referenced by read().
read()
Tick NSGigE::read (PacketPtr pkt) override virtual
This reads the device registers, which are detailed in the NS83820 spec sheet.
Implements PioDevice.
Definition at line 187 of file ns_gige.cc.
References CCSR, dp_regs::ccsr, CFGR, dp_regs::command, dp_regs::config, CR, CR_RXD, CR_RXR, CR_TXD, CR_TXR, devIntrClear(), DPRINTF, FHASH_ADDR, FHASH_SIZE, dp_rom::filterHash, Packet::getAddr(), Packet::getPtr(), Packet::getSize(), GPIOR, dp_regs::gpior, IER, dp_regs::ier, IHR, dp_regs::ihr, IMR, dp_regs::imr, ioEnable, ISR, dp_regs::isr, ISR_ALL, LAST, M5REG, M5REG_RSS, M5REG_RX_THREAD, M5REG_TX_THREAD, Packet::makeAtomicResponse(), MEAR, dp_regs::mear, MIB_END, MIB_START, MIBC, dp_regs::mibc, MIBC_ACLR, MIBC_MIBS, panic, params(), PCR, dp_regs::pcr, dp_rom::perfectMatch, PciDevice::pioDelay, PQCR, dp_regs::pqcr, PTSCR, dp_regs::ptscr, PciDevice::readConfig(), X86ISA::reg, regs, RESERVED, RFCR, dp_regs::rfcr, RFCR_RFADDR, RFDR, rom, RX_CFG, dp_regs::rxcfg, RXDP, dp_regs::rxdp, RXDP_HI, dp_regs::rxdp_hi, Packet::setLE(), SRR, dp_regs::srr, TANAR, dp_regs::tanar, TANER, dp_regs::taner, TANLPAR, dp_regs::tanlpar, TBICR, dp_regs::tbicr, TBISR, dp_regs::tbisr, TESR, dp_regs::tesr, TX_CFG, dp_regs::txcfg, TXDP, dp_regs::txdp, TXDP_HI, dp_regs::txdp_hi, VDR, dp_regs::vdr, VRCR, dp_regs::vrcr, VTCR, dp_regs::vtcr, WCSR, and dp_regs::wcsr.
recvPacket()
bool NSGigE::recvPacket (EthPacketPtr packet)
Definition at line 1952 of file ns_gige.cc.
References PacketFifo::avail(), devIntrPost(), DPRINTF, EtherDevice::droppedPackets, Net::IpHdr::id(), iGbReg::TxdOp::ip(), ISR_RXORN, PacketFifo::push(), EtherDevice::rxBytes, rxEnable, rxFifo, rxFilter(), rxFilterEnable, rxKick(), EtherDevice::rxPackets, Net::TcpHdr::seq(), and iGbReg::TxdOp::tcp().
Referenced by NSGigEInt::recvPacket().
regsReset()
void NSGigE::regsReset () protected
Definition at line 956 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, dp_regs::brar, CFGR_LNKSTS, CFGR_MODE_1000, CFGR_TBI_EN, dp_regs::config, extstsEnable, dp_regs::mear, dp_regs::mibc, MIBC_FRZ, regs, dp_regs::rxcfg, dp_regs::srr, dp_regs::tesr, dp_regs::txcfg, and dp_regs::vdr.
Referenced by NSGigE(), and write().
rxDmaReadDone()
void NSGigE::rxDmaReadDone () protected
Definition at line 993 of file ns_gige.cc.
References DDUMP, dmaIdle, dmaReading, dmaReadWaiting, dmaWriteWaiting, DPRINTF, rxDmaAddr, rxDmaData, rxDmaLen, rxDmaState, rxKick(), txDmaState, and txKick().
Referenced by NSGigE().
rxDmaWriteDone()
void NSGigE::rxDmaWriteDone () protected
Definition at line 1023 of file ns_gige.cc.
References DDUMP, dmaIdle, dmaReadWaiting, dmaWriteWaiting, dmaWriting, DPRINTF, rxDmaAddr, rxDmaData, rxDmaLen, rxDmaState, rxKick(), txDmaState, and txKick().
Referenced by NSGigE().
rxDump()
void NSGigE::rxDump () const protected
rxFilter()
bool NSGigE::rxFilter (const EthPacketPtr & packet) protected
Definition at line 1909 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, Net::EthAddr::broadcast(), DDUMP, DPRINTF, Net::EthHdr::dst(), Net::EthAddr::multicast(), multicastHashEnable, dp_rom::perfectMatch, rom, Net::EthHdr::type(), type, and Net::EthAddr::unicast().
Referenced by recvPacket().
rxKick()
void NSGigE::rxKick () protected
Todo:
in reality, we should be able to start processing the packet as it arrives, and not have to wait for the full packet ot be in the receive fifo.
Todo:
do we want to schedule a future kick?
Definition at line 1040 of file ns_gige.cc.
References ns_desc32::bufptr, ns_desc64::bufptr, CFGR_M64ADDR, Net::cksum(), Clocked::clockEdge(), ns_desc32::cmdsts, ns_desc64::cmdsts, CMDSTS_INTR, CMDSTS_LEN_MASK, CMDSTS_MORE, CMDSTS_OK, CMDSTS_OWN, dp_regs::config, CRDD, curTick(), EtherDevice::descDmaRdBytes, EtherDevice::descDmaReads, EtherDevice::descDmaWrBytes, EtherDevice::descDmaWrites, devIntrPost(), dmaDataFree, dmaDescFree, dmaIdle, dmaReadWaiting, dmaWriteWaiting, doRxDmaRead(), doRxDmaWrite(), DPRINTF, DTRACE, PacketFifo::empty(), X86ISA::exit, ns_desc32::extsts, ns_desc64::extsts, EXTSTS_IPERR, EXTSTS_IPPKT, EXTSTS_TCPERR, EXTSTS_TCPPKT, EXTSTS_UDPERR, EXTSTS_UDPPKT, extstsEnable, PacketFifo::front(), Net::IpHdr::id(), iGbReg::TxdOp::ip(), ISR_RXDESC, ISR_RXIDLE, ISR_RXOK, ns_desc32::link, ns_desc64::link, NsRxStateStrings, panic, PacketFifo::pop(), regs, rxAdvance, rxDesc32, rxDesc64, rxDescCnt, rxDescRead, rxDescRefr, rxDescWrite, rxDmaAddr, rxDmaData, rxDmaFree, rxDmaLen, rxDmaState, dp_regs::rxdp, rxEnable, rxFifo, rxFifoBlock, rxFragPtr, rxFragWrite, rxIdle, EtherDevice::rxIpChecksums, rxKickEvent, rxKickTick, rxPacket, rxPacketBufPtr, rxPktBytes, rxState, EtherDevice::rxTcpChecksums, EtherDevice::rxUdpChecksums, rxXferLen, EventManager::schedule(), Event::scheduled(), PacketFifo::size(), and iGbReg::TxdOp::tcp().
Referenced by drainResume(), NSGigE(), recvPacket(), rxDmaReadDone(), rxDmaWriteDone(), txDmaReadDone(), txDmaWriteDone(), and write().
rxReset()
void NSGigE::rxReset () protected
Definition at line 941 of file ns_gige.cc.
References PacketFifo::clear(), CRDD, dmaIdle, DPRINTF, rxDescCnt, rxDmaState, rxEnable, rxFifo, rxFragPtr, rxIdle, rxPktBytes, and rxState.
Referenced by write().
serialize()
void NSGigE::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2018 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, dp_regs::brar, dp_regs::brdr, ns_desc32::bufptr, ns_desc64::bufptr, dp_regs::ccsr, ns_desc32::cmdsts, ns_desc64::cmdsts, dp_regs::command, dp_regs::config, cpuPendingIntr, CRDD, CTDD, curTick(), eepromAddress, eepromBitsToRx, eepromClk, eepromData, eepromOpcode, eepromState, ns_desc32::extsts, ns_desc64::extsts, extstsEnable, FHASH_SIZE, dp_rom::filterHash, dp_regs::gpior, dp_regs::ier, dp_regs::ihr, dp_regs::imr, intrEvent, intrTick, ioEnable, dp_regs::isr, ns_desc32::link, ns_desc64::link, dp_regs::mear, dp_regs::mibc, multicastHashEnable, dp_regs::pcr, dp_rom::perfectMatch, dp_regs::pqcr, dp_regs::ptscr, regs, dp_regs::rfcr, dp_regs::rfdr, rom, dp_regs::rxcfg, rxDesc32, rxDesc64, rxDescCnt, rxDmaState, dp_regs::rxdp, dp_regs::rxdp_hi, rxEnable, rxFifo, rxFilterEnable, rxFragPtr, rxKickTick, rxPacket, rxPacketBufPtr, rxPktBytes, rxState, rxXferLen, Event::scheduled(), PacketFifo::serialize(), PciDevice::serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, dp_regs::srr, dp_regs::tanar, dp_regs::taner, dp_regs::tanlpar, dp_regs::tbicr, dp_regs::tbisr, dp_regs::tesr, dp_regs::txcfg, txDesc32, txDesc64, txDescCnt, txDmaState, dp_regs::txdp, dp_regs::txdp_hi, txEnable, txEvent, txFifo, txFragPtr, txKickTick, txPacket, txPacketBufPtr, txState, txXferLen, dp_regs::vdr, dp_regs::vrcr, dp_regs::vtcr, dp_regs::wcsr, and Event::when().
transferDone()
void NSGigE::transferDone ()
Definition at line 1896 of file ns_gige.cc.
References Clocked::clockEdge(), DPRINTF, PacketFifo::empty(), EventManager::reschedule(), txEvent, and txFifo.
Referenced by NSGigEInt::sendDone().
transmit()
void NSGigE::transmit () protected
Retransmit event.
Definition at line 1355 of file ns_gige.cc.
References PacketFifo::avail(), curTick(), DDUMP, devIntrPost(), DPRINTF, DTRACE, PacketFifo::empty(), PacketFifo::front(), interface, iGbReg::TxdOp::ip(), ISR_TXOK, PacketFifo::pop(), retryTime, EventManager::schedule(), Event::scheduled(), EtherInt::sendPacket(), PacketFifo::size(), iGbReg::TxdOp::tcp(), EtherDevice::txBytes, txEvent, txFifo, and EtherDevice::txPackets.
Referenced by txKick().
txDmaReadDone()
void NSGigE::txDmaReadDone () protected
Definition at line 1420 of file ns_gige.cc.
References DDUMP, dmaIdle, dmaReading, dmaReadWaiting, dmaWriteWaiting, DPRINTF, rxDmaState, rxKick(), txDmaAddr, txDmaData, txDmaLen, txDmaState, and txKick().
Referenced by NSGigE().
txDmaWriteDone()
void NSGigE::txDmaWriteDone () protected
Definition at line 1450 of file ns_gige.cc.
References DDUMP, dmaIdle, dmaReadWaiting, dmaWriteWaiting, dmaWriting, DPRINTF, rxDmaState, rxKick(), txDmaAddr, txDmaData, txDmaLen, txDmaState, and txKick().
Referenced by NSGigE().
txDump()
void NSGigE::txDump () const protected
txEventTransmit()
void NSGigE::txEventTransmit () inline protected
Definition at line 291 of file ns_gige.hh.
Referenced by NSGigE().
txKick()
void NSGigE::txKick () protected
Todo:
do we want to schedule a future kick?
Definition at line 1467 of file ns_gige.cc.
References PacketFifo::avail(), Debug::breakpoint(), ns_desc32::bufptr, ns_desc64::bufptr, CFGR_M64ADDR, Net::cksum(), Clocked::clockEdge(), ns_desc32::cmdsts, ns_desc64::cmdsts, CMDSTS_INTR, CMDSTS_LEN_MASK, CMDSTS_MORE, CMDSTS_OK, CMDSTS_OWN, dp_regs::config, CTDD, curTick(), EtherDevice::descDmaRdBytes, EtherDevice::descDmaReads, EtherDevice::descDmaWrBytes, EtherDevice::descDmaWrites, devIntrPost(), dmaDataFree, dmaDescFree, dmaIdle, dmaReadWaiting, dmaWriteWaiting, doTxDmaRead(), doTxDmaWrite(), DPRINTF, X86ISA::exit, ns_desc32::extsts, ns_desc64::extsts, EXTSTS_IPPKT, EXTSTS_TCPPKT, EXTSTS_UDPPKT, extstsEnable, PacketFifo::full(), iGbReg::TxdOp::ip(), ISR_TXDESC, ISR_TXIDLE, ns_desc32::link, ns_desc64::link, NsTxStateStrings, panic, PacketFifo::push(), regs, PacketFifo::reserve(), EventManager::schedule(), Event::scheduled(), Net::IpHdr::sum(), Net::TcpHdr::sum(), Net::UdpHdr::sum(), iGbReg::TxdOp::tcp(), transmit(), txAdvance, txDesc32, txDesc64, txDescCnt, txDescRead, txDescRefr, txDescWrite, txDmaAddr, txDmaData, txDmaFree, txDmaLen, txDmaState, dp_regs::txdp, txEnable, txFifo, txFifoBlock, txFragPtr, txFragRead, txIdle, EtherDevice::txIpChecksums, txKickEvent, txKickTick, txPacket, txPacketBufPtr, txState, EtherDevice::txTcpChecksums, EtherDevice::txUdpChecksums, txXferLen, dp_regs::vtcr, VTCR_PPCHK, and warn_once.
Referenced by drainResume(), NSGigE(), rxDmaReadDone(), rxDmaWriteDone(), txDmaReadDone(), txDmaWriteDone(), and write().
txReset()
void NSGigE::txReset () protected
Definition at line 926 of file ns_gige.cc.
References PacketFifo::clear(), CTDD, dmaIdle, DPRINTF, txDescCnt, txDmaState, txEnable, txFifo, txFragPtr, txIdle, and txState.
Referenced by write().
unserialize()
void NSGigE::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2191 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, dp_regs::brar, dp_regs::brdr, ns_desc32::bufptr, ns_desc64::bufptr, dp_regs::ccsr, ns_desc32::cmdsts, ns_desc64::cmdsts, dp_regs::command, dp_regs::config, cpuInterrupt(), cpuPendingIntr, CRDD, CTDD, curTick(), eepromAddress, eepromBitsToRx, eepromClk, eepromData, eepromOpcode, eepromState, ns_desc32::extsts, ns_desc64::extsts, extstsEnable, FHASH_SIZE, dp_rom::filterHash, dp_regs::gpior, dp_regs::ier, dp_regs::ihr, dp_regs::imr, intrEvent, intrTick, ioEnable, dp_regs::isr, ns_desc32::link, ns_desc64::link, dp_regs::mear, dp_regs::mibc, multicastHashEnable, SimObject::name(), NSGigE(), dp_regs::pcr, dp_rom::perfectMatch, dp_regs::pqcr, dp_regs::ptscr, regs, dp_regs::rfcr, dp_regs::rfdr, rom, dp_regs::rxcfg, rxDesc32, rxDesc64, rxDescCnt, rxDmaState, dp_regs::rxdp, dp_regs::rxdp_hi, rxEnable, rxFifo, rxFilterEnable, rxFragPtr, rxKickEvent, rxKickTick, rxPacket, rxPacketBufPtr, rxPktBytes, rxState, rxXferLen, EventManager::schedule(), dp_regs::srr, dp_regs::tanar, dp_regs::taner, dp_regs::tanlpar, dp_regs::tbicr, dp_regs::tbisr, dp_regs::tesr, dp_regs::txcfg, txDesc32, txDesc64, txDescCnt, txDmaState, dp_regs::txdp, dp_regs::txdp_hi, txEnable, txEvent, txFifo, txFragPtr, txKickEvent, txKickTick, txPacket, txPacketBufPtr, txState, txXferLen, PacketFifo::unserialize(), PciDevice::unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, dp_regs::vdr, dp_regs::vrcr, dp_regs::vtcr, and dp_regs::wcsr.
write()
Tick NSGigE::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 409 of file ns_gige.cc.
References acceptArp, acceptBroadcast, acceptMulticast, acceptPerfect, acceptUnicast, BRAR, dp_regs::brar, BRDR, CCSR, dp_regs::ccsr, CFGR, CFGR_AUTO_1000, CFGR_DUPSTS, CFGR_EXTSTS_EN, CFGR_LNKSTS, CFGR_PCI64_DET, CFGR_RESERVED, CFGR_SPDSTS, CFGR_T64ADDR, dp_regs::command, dp_regs::config, CR, CR_RST, CR_RXD, CR_RXE, CR_RXR, CR_SWI, CR_TXD, CR_TXE, CR_TXR, CRDD, CTDD, devIntrChangeMask(), devIntrPost(), DPRINTF, eepromClk, eepromKick(), eepromStart, eepromState, extstsEnable, FHASH_ADDR, FHASH_SIZE, dp_rom::filterHash, Packet::getAddr(), Packet::getLE(), Packet::getSize(), GPIOR, dp_regs::gpior, GPIOR_GP1_IN, GPIOR_GP2_IN, GPIOR_GP3_IN, GPIOR_GP4_IN, GPIOR_GP5_IN, GPIOR_UNUSED, IER, dp_regs::ier, IHR, dp_regs::ihr, IMR, dp_regs::imr, ioEnable, ISR, ISR_SWI, LAST, Packet::makeAtomicResponse(), MEAR, dp_regs::mear, MEAR_EECLK, MEAR_EEDI, MEAR_EEDO, MEAR_EESEL, MIBC, multicastHashEnable, panic, PCR, dp_regs::pcr, dp_rom::perfectMatch, PciDevice::pioDelay, PQCR, dp_regs::pqcr, PTSCR, dp_regs::ptscr, PTSCR_EEBIST_EN, PTSCR_EELOAD_EN, PTSCR_RBIST_DONE, PTSCR_RBIST_EN, PTSCR_RBIST_RDONLY, X86ISA::reg, regs, regsReset(), RESERVED, RFCR, dp_regs::rfcr, RFCR_AAB, RFCR_AAM, RFCR_AARP, RFCR_AAU, RFCR_APM, RFCR_MHEN, RFCR_RFADDR, RFCR_RFEN, RFCR_UHEN, RFCR_ULM, RFDR, rom, RX_CFG, dp_regs::rxcfg, RXDP, dp_regs::rxdp, RXDP_HI, dp_regs::rxdp_hi, rxEnable, rxFilterEnable, rxIdle, rxKick(), rxReset(), rxState, SRR, TANAR, dp_regs::tanar, TANAR_RF1, TANAR_RF2, TANAR_UNUSED, TANER, TANLPAR, dp_regs::tanlpar, TBICR, dp_regs::tbicr, TBICR_MR_AN_ENABLE, TBICR_MR_LOOPBACK, TBISR, dp_regs::tbisr, TBISR_MR_AN_COMPLETE, TBISR_MR_LINK_STATUS, TESR, dp_regs::tesr, TX_CFG, dp_regs::txcfg, TXDP, dp_regs::txdp, TXDP_HI, dp_regs::txdp_hi, txEnable, txIdle, txKick(), txReset(), txState, VDR, VRCR, dp_regs::vrcr, VTCR, dp_regs::vtcr, WCSR, dp_regs::wcsr, and writeConfig().
writeConfig()
Tick NSGigE::writeConfig (PacketPtr pkt) override virtual
This is to write to the PCI general configuration registers.
Reimplemented from PciDevice.
Definition at line 151 of file ns_gige.cc.
References PciDevice::config, PciDevice::configDelay, PCIConfig::data, Packet::getAddr(), ioEnable, ArmISA::offset, panic, PCI_CMD_IOSE, PCI_COMMAND, PCI_CONFIG_SIZE, PCI_DEVICE_SPECIFIC, and PciDevice::writeConfig().
Referenced by write().
Member Data Documentation
acceptArp
bool NSGigE::acceptArp protected
Definition at line 311 of file ns_gige.hh.
Referenced by NSGigE(), regsReset(), rxFilter(), serialize(), unserialize(), and write().
acceptBroadcast
bool NSGigE::acceptBroadcast protected
Definition at line 307 of file ns_gige.hh.
Referenced by NSGigE(), regsReset(), rxFilter(), serialize(), unserialize(), and write().
acceptMulticast
bool NSGigE::acceptMulticast protected
Definition at line 308 of file ns_gige.hh.
Referenced by NSGigE(), regsReset(), rxFilter(), serialize(), unserialize(), and write().
acceptPerfect
bool NSGigE::acceptPerfect protected
Definition at line 310 of file ns_gige.hh.
Referenced by NSGigE(), regsReset(), rxFilter(), serialize(), unserialize(), and write().
acceptUnicast
bool NSGigE::acceptUnicast protected
Definition at line 309 of file ns_gige.hh.
Referenced by NSGigE(), regsReset(), rxFilter(), serialize(), unserialize(), and write().
cpuPendingIntr
bool NSGigE::cpuPendingIntr protected
Definition at line 323 of file ns_gige.hh.
Referenced by cpuInterrupt(), cpuIntrClear(), cpuIntrPending(), NSGigE(), serialize(), and unserialize().
CRDD
bool NSGigE::CRDD protected
Current Receive Descriptor Done.
Definition at line 214 of file ns_gige.hh.
Referenced by rxKick(), rxReset(), serialize(), unserialize(), and write().
CTDD
bool NSGigE::CTDD protected
Current Transmit Descriptor Done.
Definition at line 200 of file ns_gige.hh.
Referenced by serialize(), txKick(), txReset(), unserialize(), and write().
dmaDataFree
bool NSGigE::dmaDataFree protected
Definition at line 267 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), and txKick().
dmaDescFree
bool NSGigE::dmaDescFree protected
Definition at line 266 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), and txKick().
dmaReadDelay
Tick NSGigE::dmaReadDelay protected
Definition at line 236 of file ns_gige.hh.
dmaReadFactor
Tick NSGigE::dmaReadFactor protected
Definition at line 239 of file ns_gige.hh.
dmaWriteDelay
Tick NSGigE::dmaWriteDelay protected
Definition at line 237 of file ns_gige.hh.
dmaWriteFactor
Tick NSGigE::dmaWriteFactor protected
Definition at line 240 of file ns_gige.hh.
eepromAddress
uint8_t NSGigE::eepromAddress protected
Definition at line 232 of file ns_gige.hh.
Referenced by eepromKick(), serialize(), and unserialize().
eepromBitsToRx
uint8_t NSGigE::eepromBitsToRx protected
Definition at line 230 of file ns_gige.hh.
Referenced by eepromKick(), serialize(), and unserialize().
eepromClk
bool NSGigE::eepromClk protected
Definition at line 229 of file ns_gige.hh.
Referenced by serialize(), unserialize(), and write().
eepromData
uint16_t NSGigE::eepromData protected
Definition at line 233 of file ns_gige.hh.
Referenced by eepromKick(), serialize(), and unserialize().
eepromOpcode
uint8_t NSGigE::eepromOpcode protected
Definition at line 231 of file ns_gige.hh.
Referenced by eepromKick(), serialize(), and unserialize().
eepromState
EEPROMState NSGigE::eepromState protected
EEPROM State Machine.
Definition at line 228 of file ns_gige.hh.
Referenced by eepromKick(), serialize(), unserialize(), and write().
extstsEnable
bool NSGigE::extstsEnable protected
Definition at line 225 of file ns_gige.hh.
Referenced by regsReset(), rxKick(), serialize(), txKick(), unserialize(), and write().
interface
NSGigEInt* NSGigE::interface protected
Definition at line 329 of file ns_gige.hh.
Referenced by getPort(), NSGigE(), transmit(), and ~NSGigE().
intrDelay
Tick NSGigE::intrDelay protected
Definition at line 321 of file ns_gige.hh.
Referenced by devIntrPost(), and NSGigE().
intrEvent
EventFunctionWrapper* NSGigE::intrEvent protected
Definition at line 328 of file ns_gige.hh.
Referenced by cpuInterrupt(), cpuIntrClear(), cpuIntrPost(), NSGigE(), serialize(), and unserialize().
intrTick
Tick NSGigE::intrTick protected
Definition at line 322 of file ns_gige.hh.
Referenced by cpuInterrupt(), cpuIntrClear(), cpuIntrPost(), NSGigE(), serialize(), and unserialize().
ioEnable
bool NSGigE::ioEnable protected
pci settings
Definition at line 172 of file ns_gige.hh.
Referenced by read(), serialize(), unserialize(), write(), and writeConfig().
multicastHashEnable
bool NSGigE::multicastHashEnable protected
Definition at line 312 of file ns_gige.hh.
Referenced by NSGigE(), rxFilter(), serialize(), unserialize(), and write().
regs
dp_regs NSGigE::regs protected
device register file
Definition at line 168 of file ns_gige.hh.
Referenced by devIntrChangeMask(), devIntrClear(), devIntrPost(), eepromKick(), read(), regsReset(), rxKick(), serialize(), txKick(), unserialize(), and write().
rom
dp_rom NSGigE::rom protected
Definition at line 169 of file ns_gige.hh.
Referenced by eepromKick(), NSGigE(), read(), rxFilter(), serialize(), unserialize(), and write().
rxDelay
Tick NSGigE::rxDelay protected
Definition at line 271 of file ns_gige.hh.
Referenced by NSGigE().
rxDesc32
ns_desc32 NSGigE::rxDesc32 protected
Definition at line 191 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), serialize(), and unserialize().
rxDesc64
ns_desc64 NSGigE::rxDesc64 protected
Definition at line 193 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), serialize(), and unserialize().
rxDescCnt
uint32_t NSGigE::rxDescCnt protected
count of bytes remaining in the current descriptor
Definition at line 222 of file ns_gige.hh.
Referenced by rxKick(), rxReset(), serialize(), and unserialize().
rxDmaAddr
Addr NSGigE::rxDmaAddr protected
Definition at line 243 of file ns_gige.hh.
Referenced by doRxDmaRead(), doRxDmaWrite(), rxDmaReadDone(), rxDmaWriteDone(), and rxKick().
rxDmaData
void* NSGigE::rxDmaData protected
Definition at line 242 of file ns_gige.hh.
Referenced by doRxDmaRead(), doRxDmaWrite(), rxDmaReadDone(), rxDmaWriteDone(), and rxKick().
rxDmaFree
bool NSGigE::rxDmaFree protected
Definition at line 186 of file ns_gige.hh.
Referenced by rxKick().
rxDmaLen
int NSGigE::rxDmaLen protected
Definition at line 244 of file ns_gige.hh.
Referenced by doRxDmaRead(), doRxDmaWrite(), rxDmaReadDone(), rxDmaWriteDone(), and rxKick().
rxDmaReadEvent
EventFunctionWrapper NSGigE::rxDmaReadEvent protected
Definition at line 255 of file ns_gige.hh.
Referenced by doRxDmaRead().
rxDmaState
DmaState NSGigE::rxDmaState protected
Definition at line 223 of file ns_gige.hh.
Referenced by doRxDmaRead(), doRxDmaWrite(), rxDmaReadDone(), rxDmaWriteDone(), rxKick(), rxReset(), serialize(), txDmaReadDone(), txDmaWriteDone(), and unserialize().
rxDmaWriteEvent
EventFunctionWrapper NSGigE::rxDmaWriteEvent protected
Definition at line 258 of file ns_gige.hh.
Referenced by doRxDmaWrite(), and NSGigE().
rxEnable
bool NSGigE::rxEnable protected
Definition at line 211 of file ns_gige.hh.
Referenced by recvPacket(), rxKick(), rxReset(), serialize(), unserialize(), and write().
rxFifo
PacketFifo NSGigE::rxFifo protected
Definition at line 177 of file ns_gige.hh.
Referenced by recvPacket(), rxKick(), rxReset(), serialize(), and unserialize().
rxFilterEnable
bool NSGigE::rxFilterEnable protected
receive address filter
Definition at line 305 of file ns_gige.hh.
Referenced by NSGigE(), recvPacket(), serialize(), unserialize(), and write().
rxFragPtr
Addr NSGigE::rxFragPtr protected
ptr to the next byte in current fragment
Definition at line 220 of file ns_gige.hh.
Referenced by rxKick(), rxReset(), serialize(), and unserialize().
rxHalt
bool NSGigE::rxHalt protected
halt the rx state machine after current packet
Definition at line 218 of file ns_gige.hh.
rxKickEvent
EventFunctionWrapper NSGigE::rxKickEvent protected
Definition at line 279 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), and unserialize().
rxKickTick
Tick NSGigE::rxKickTick protected
Definition at line 278 of file ns_gige.hh.
Referenced by NSGigE(), rxKick(), serialize(), and unserialize().
rxPacket
EthPacketPtr NSGigE::rxPacket protected
Definition at line 181 of file ns_gige.hh.
Referenced by rxKick(), serialize(), and unserialize().
rxPacketBufPtr
uint8_t* NSGigE::rxPacketBufPtr protected
Definition at line 183 of file ns_gige.hh.
Referenced by rxKick(), serialize(), and unserialize().
rxPktBytes
uint32_t NSGigE::rxPktBytes protected
num of bytes in the current packet being drained from rxDataFifo
Definition at line 216 of file ns_gige.hh.
Referenced by rxKick(), rxReset(), serialize(), and unserialize().
rxState
RxState NSGigE::rxState protected
rx State Machine
Definition at line 210 of file ns_gige.hh.
Referenced by rxKick(), rxReset(), serialize(), unserialize(), and write().
rxXferLen
uint32_t NSGigE::rxXferLen protected
Definition at line 185 of file ns_gige.hh.
Referenced by rxKick(), serialize(), and unserialize().
txDelay
Tick NSGigE::txDelay protected
Definition at line 270 of file ns_gige.hh.
Referenced by NSGigE().
txDesc32
ns_desc32 NSGigE::txDesc32 protected
DescCaches.
Definition at line 190 of file ns_gige.hh.
Referenced by NSGigE(), serialize(), txKick(), and unserialize().
txDesc64
ns_desc64 NSGigE::txDesc64 protected
Definition at line 192 of file ns_gige.hh.
Referenced by NSGigE(), serialize(), txKick(), and unserialize().
txDescCnt
uint32_t NSGigE::txDescCnt protected
count of bytes remaining in the current descriptor
Definition at line 206 of file ns_gige.hh.
Referenced by serialize(), txKick(), txReset(), and unserialize().
txDmaAddr
Addr NSGigE::txDmaAddr protected
Definition at line 249 of file ns_gige.hh.
Referenced by doTxDmaRead(), doTxDmaWrite(), txDmaReadDone(), txDmaWriteDone(), and txKick().
txDmaData
void* NSGigE::txDmaData protected
Definition at line 248 of file ns_gige.hh.
Referenced by doTxDmaRead(), doTxDmaWrite(), txDmaReadDone(), txDmaWriteDone(), and txKick().
txDmaFree
bool NSGigE::txDmaFree protected
Definition at line 187 of file ns_gige.hh.
Referenced by txKick().
txDmaLen
int NSGigE::txDmaLen protected
Definition at line 250 of file ns_gige.hh.
Referenced by doTxDmaRead(), doTxDmaWrite(), txDmaReadDone(), txDmaWriteDone(), and txKick().
txDmaReadEvent
EventFunctionWrapper NSGigE::txDmaReadEvent protected
Definition at line 261 of file ns_gige.hh.
Referenced by doTxDmaRead(), and NSGigE().
txDmaState
DmaState NSGigE::txDmaState protected
Definition at line 207 of file ns_gige.hh.
Referenced by doTxDmaRead(), doTxDmaWrite(), rxDmaReadDone(), rxDmaWriteDone(), serialize(), txDmaReadDone(), txDmaWriteDone(), txKick(), txReset(), and unserialize().
txDmaWriteEvent
EventFunctionWrapper NSGigE::txDmaWriteEvent protected
Definition at line 264 of file ns_gige.hh.
Referenced by doTxDmaWrite(), and NSGigE().
txEnable
bool NSGigE::txEnable protected
Definition at line 197 of file ns_gige.hh.
Referenced by serialize(), txKick(), txReset(), unserialize(), and write().
txEvent
EventFunctionWrapper NSGigE::txEvent protected
Definition at line 297 of file ns_gige.hh.
Referenced by NSGigE(), serialize(), transferDone(), transmit(), and unserialize().
txFifo
PacketFifo NSGigE::txFifo protected
Definition at line 176 of file ns_gige.hh.
Referenced by serialize(), transferDone(), transmit(), txKick(), txReset(), and unserialize().
txFragPtr
Addr NSGigE::txFragPtr protected
ptr to the next byte in the current fragment
Definition at line 204 of file ns_gige.hh.
Referenced by serialize(), txKick(), txReset(), and unserialize().
txHalt
bool NSGigE::txHalt protected
halt the tx state machine after next packet
Definition at line 202 of file ns_gige.hh.
txKickEvent
EventFunctionWrapper NSGigE::txKickEvent protected
Definition at line 283 of file ns_gige.hh.
Referenced by NSGigE(), txKick(), and unserialize().
txKickTick
Tick NSGigE::txKickTick protected
Definition at line 282 of file ns_gige.hh.
Referenced by NSGigE(), serialize(), txKick(), and unserialize().
txPacket
EthPacketPtr NSGigE::txPacket protected
various helper vars
Definition at line 180 of file ns_gige.hh.
Referenced by serialize(), txKick(), and unserialize().
txPacketBufPtr
uint8_t* NSGigE::txPacketBufPtr protected
Definition at line 182 of file ns_gige.hh.
Referenced by serialize(), txKick(), and unserialize().
txState
TxState NSGigE::txState protected
Definition at line 196 of file ns_gige.hh.
Referenced by serialize(), txKick(), txReset(), unserialize(), and write().
txXferLen
uint32_t NSGigE::txXferLen protected
Definition at line 184 of file ns_gige.hh.
Referenced by serialize(), txKick(), and unserialize().
The documentation for this class was generated from the following files:
dev/net/ns_gige.hh
dev/net/ns_gige.cc