gem5: GarnetNetwork Class Reference
GarnetNetwork Class Reference
#include <GarnetNetwork.hh>
Public Types
typedef GarnetNetworkParams Params
Public Types inherited from Network
typedef RubyNetworkParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
GarnetNetwork (const Params *p)
~GarnetNetwork ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
int getNumRows () const
int getNumCols ()
uint32_t getNiFlitSize () const
uint32_t getVCsPerVnet () const
uint32_t getBuffersPerDataVC ()
uint32_t getBuffersPerCtrlVC ()
int getRoutingAlgorithm () const
bool isFaultModelEnabled () const
bool isVNetOrdered (int vnet) const
VNET_type get_vnet_type (int vc)
int getNumRouters ()
int get_router_id (int ni)
void makeExtOutLink (SwitchID src, NodeID dest, BasicLink *link, const NetDest &routing_table_entry)
void makeExtInLink (NodeID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry)
void makeInternalLink (SwitchID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry, PortDirection src_outport_dirn, PortDirection dest_inport_dirn)
uint32_t functionalWrite (Packet *pkt)
Function for performing a functional write.
void collateStats ()
void regStats ()
Callback to set stat parameters.
void print (std::ostream &out) const
void increment_injected_packets (int vnet)
void increment_received_packets (int vnet)
void increment_packet_network_latency (Cycles latency, int vnet)
void increment_packet_queueing_latency (Cycles latency, int vnet)
void increment_injected_flits (int vnet)
void increment_received_flits (int vnet)
void increment_flit_network_latency (Cycles latency, int vnet)
void increment_flit_queueing_latency (Cycles latency, int vnet)
void increment_total_hops (int hops)
Public Member Functions inherited from Network
Network (const Params *p)
const Params * params () const
virtual ~Network ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
int getNumNodes () const
void setToNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void setFromNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type)
virtual bool functionalRead (Packet *pkt)
NodeID addressToNodeID (Addr addr, MachineType mtype)
Map an address to the correct NodeID.
Port & getPort (const std::string &, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
FaultModel * fault_model
Protected Attributes
int m_num_rows
int m_num_cols
uint32_t m_ni_flit_size
uint32_t m_vcs_per_vnet
uint32_t m_buffers_per_ctrl_vc
uint32_t m_buffers_per_data_vc
int m_routing_algorithm
bool m_enable_fault_model
Stats::Vector m_packets_received
Stats::Vector m_packets_injected
Stats::Vector m_packet_network_latency
Stats::Vector m_packet_queueing_latency
Stats::Formula m_avg_packet_vnet_latency
Stats::Formula m_avg_packet_vqueue_latency
Stats::Formula m_avg_packet_network_latency
Stats::Formula m_avg_packet_queueing_latency
Stats::Formula m_avg_packet_latency
Stats::Vector m_flits_received
Stats::Vector m_flits_injected
Stats::Vector m_flit_network_latency
Stats::Vector m_flit_queueing_latency
Stats::Formula m_avg_flit_vnet_latency
Stats::Formula m_avg_flit_vqueue_latency
Stats::Formula m_avg_flit_network_latency
Stats::Formula m_avg_flit_queueing_latency
Stats::Formula m_avg_flit_latency
Stats::Scalar m_total_ext_in_link_utilization
Stats::Scalar m_total_ext_out_link_utilization
Stats::Scalar m_total_int_link_utilization
Stats::Scalar m_average_link_utilization
Stats::Vector m_average_vc_load
Stats::Scalar m_total_hops
Stats::Formula m_avg_hops
Protected Attributes inherited from Network
uint32_t m_nodes
std::vector< std::string > m_vnet_type_names
Topology * m_topology_ptr
std::vector< std::vector< MessageBuffer * > > m_toNetQueues
std::vector< std::vector< MessageBuffer * > > m_fromNetQueues
std::vector< bool > m_ordered
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
GarnetNetwork (const GarnetNetwork &obj)
GarnetNetwork & operator= (const GarnetNetwork &obj)
Private Attributes
std::vector< VNET_type > m_vnet_type
std::vector< Router * > m_routers
std::vector< NetworkLink * > m_networklinks
std::vector< CreditLink * > m_creditlinks
std::vector< NetworkInterface * > m_nis
Additional Inherited Members
Static Public Member Functions inherited from Network
static uint32_t getNumberOfVirtualNetworks ()
static uint32_t MessageSizeType_to_int (MessageSizeType size_type)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Network
Network (const Network &obj)
Network & operator= (const Network &obj)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Static Protected Attributes inherited from Network
static uint32_t m_virtual_networks
static uint32_t m_control_msg_size
static uint32_t m_data_msg_size
Detailed Description
Definition at line 52 of file GarnetNetwork.hh.
Member Typedef Documentation
Params
typedef GarnetNetworkParams GarnetNetwork::Params
Definition at line 55 of file GarnetNetwork.hh.
Constructor & Destructor Documentation
GarnetNetwork() [1/2]
GarnetNetwork::GarnetNetwork (const Params * p)
Definition at line 59 of file GarnetNetwork.cc.
References CTRL_VNET_, DATA_VNET_, fault_model, ArmISA::i, NetworkInterface::init_net_ptr(), Router::init_net_ptr(), m_buffers_per_ctrl_vc, m_buffers_per_data_vc, m_enable_fault_model, m_ni_flit_size, m_nis, m_num_rows, m_routers, m_routing_algorithm, m_vcs_per_vnet, Network::m_virtual_networks, m_vnet_type, Network::m_vnet_type_names, PowerISA::ni, and safe_cast().
Referenced by print().
~GarnetNetwork()
GarnetNetwork::~GarnetNetwork ()
Definition at line 146 of file GarnetNetwork.cc.
References m5::stl_helpers::deletePointers(), m_creditlinks, m_networklinks, m_nis, and m_routers.
GarnetNetwork() [2/2]
GarnetNetwork::GarnetNetwork (const GarnetNetwork & obj) private
Member Function Documentation
collateStats()
void GarnetNetwork::collateStats () virtual
Implements Network.
Definition at line 399 of file GarnetNetwork.cc.
References Clocked::curCycle(), EXT_IN_, EXT_OUT_, RubySystem::getStartCycle(), ArmISA::i, INT_, ArmISA::j, m_average_link_utilization, m_average_vc_load, m_networklinks, m_routers, m_total_ext_in_link_utilization, m_total_ext_out_link_utilization, m_total_int_link_utilization, Network::params(), ArmISA::rs, and type.
Referenced by get_vnet_type().
functionalWrite()
uint32_t GarnetNetwork::functionalWrite (Packet * pkt) virtual
Function for performing a functional write.
The return value indicates the number of messages that were written.
Reimplemented from Network.
Definition at line 443 of file GarnetNetwork.cc.
References ArmISA::i, m_networklinks, m_nis, and m_routers.
Referenced by get_vnet_type().
get_router_id()
int GarnetNetwork::get_router_id (int ni)
Definition at line 249 of file GarnetNetwork.cc.
References m_nis, and PowerISA::ni.
Referenced by NetworkInterface::flitisizeMessage(), and get_vnet_type().
get_vnet_type()
VNET_type GarnetNetwork::get_vnet_type (int vc) inline
Definition at line 81 of file GarnetNetwork.hh.
References collateStats(), functionalWrite(), get_router_id(), getNumRouters(), getVCsPerVnet(), m_vnet_type, makeExtInLink(), makeExtOutLink(), makeInternalLink(), PowerISA::ni, print(), and regStats().
Referenced by OutVcState::OutVcState().
getBuffersPerCtrlVC()
uint32_t GarnetNetwork::getBuffersPerCtrlVC () inline
Definition at line 71 of file GarnetNetwork.hh.
References m_buffers_per_ctrl_vc.
Referenced by init(), and OutVcState::OutVcState().
getBuffersPerDataVC()
uint32_t GarnetNetwork::getBuffersPerDataVC () inline
Definition at line 70 of file GarnetNetwork.hh.
References m_buffers_per_data_vc.
Referenced by init(), and OutVcState::OutVcState().
getNiFlitSize()
uint32_t GarnetNetwork::getNiFlitSize () const inline
Definition at line 68 of file GarnetNetwork.hh.
References m_ni_flit_size.
Referenced by NetworkInterface::flitisizeMessage().
getNumCols()
int GarnetNetwork::getNumCols () inline
Definition at line 65 of file GarnetNetwork.hh.
References m_num_cols.
Referenced by RoutingUnit::outportComputeXY().
getNumRouters()
int GarnetNetwork::getNumRouters ()
Definition at line 242 of file GarnetNetwork.cc.
References m_routers.
Referenced by get_vnet_type().
getNumRows()
int GarnetNetwork::getNumRows () const inline
Definition at line 64 of file GarnetNetwork.hh.
References m_num_rows.
Referenced by init(), and RoutingUnit::outportComputeXY().
getRoutingAlgorithm()
int GarnetNetwork::getRoutingAlgorithm () const inline
Definition at line 72 of file GarnetNetwork.hh.
References m_routing_algorithm.
Referenced by RoutingUnit::outportCompute().
getVCsPerVnet()
uint32_t GarnetNetwork::getVCsPerVnet () const inline
Definition at line 69 of file GarnetNetwork.hh.
References m_vcs_per_vnet.
Referenced by get_vnet_type().
increment_flit_network_latency()
void GarnetNetwork::increment_flit_network_latency (Cycles latency, int vnet) inline
Definition at line 129 of file GarnetNetwork.hh.
References m_flit_network_latency.
Referenced by NetworkInterface::incrementStats().
increment_flit_queueing_latency()
void GarnetNetwork::increment_flit_queueing_latency (Cycles latency, int vnet) inline
Definition at line 135 of file GarnetNetwork.hh.
References m_flit_queueing_latency.
Referenced by NetworkInterface::incrementStats().
increment_injected_flits()
void GarnetNetwork::increment_injected_flits (int vnet) inline
Definition at line 125 of file GarnetNetwork.hh.
References m_flits_injected.
Referenced by NetworkInterface::flitisizeMessage().
increment_injected_packets()
void GarnetNetwork::increment_injected_packets (int vnet) inline
Definition at line 110 of file GarnetNetwork.hh.
References m_packets_injected.
Referenced by NetworkInterface::flitisizeMessage().
increment_packet_network_latency()
void GarnetNetwork::increment_packet_network_latency (Cycles latency, int vnet) inline
Definition at line 114 of file GarnetNetwork.hh.
References m_packet_network_latency.
Referenced by NetworkInterface::incrementStats().
increment_packet_queueing_latency()
void GarnetNetwork::increment_packet_queueing_latency (Cycles latency, int vnet) inline
Definition at line 120 of file GarnetNetwork.hh.
References m_packet_queueing_latency.
Referenced by NetworkInterface::incrementStats().
increment_received_flits()
void GarnetNetwork::increment_received_flits (int vnet) inline
Definition at line 126 of file GarnetNetwork.hh.
References m_flits_received.
Referenced by NetworkInterface::incrementStats().
increment_received_packets()
void GarnetNetwork::increment_received_packets (int vnet) inline
Definition at line 111 of file GarnetNetwork.hh.
References m_packets_received.
Referenced by NetworkInterface::incrementStats().
increment_total_hops()
void GarnetNetwork::increment_total_hops (int hops) inline
Definition at line 141 of file GarnetNetwork.hh.
References m_total_hops.
Referenced by NetworkInterface::incrementStats().
init()
void GarnetNetwork::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 102 of file GarnetNetwork.cc.
References Topology::createLinks(), FaultModel::declare_router(), fault_model, Router::get_id(), Router::get_num_inports(), Router::get_num_outports(), Router::get_vc_per_vnet(), getBuffersPerCtrlVC(), getBuffersPerDataVC(), getNumRows(), ArmISA::i, Network::init(), isFaultModelEnabled(), M5_VAR_USED, Network::m_fromNetQueues, m_nis, Network::m_nodes, m_num_cols, m_num_rows, m_routers, Network::m_toNetQueues, Network::m_topology_ptr, Router::printAggregateFaultProbability(), Router::printFaultVector(), and safe_cast().
isFaultModelEnabled()
bool GarnetNetwork::isFaultModelEnabled () const inline
Definition at line 74 of file GarnetNetwork.hh.
References m_enable_fault_model.
Referenced by init().
isVNetOrdered()
bool GarnetNetwork::isVNetOrdered (int vnet) const inline
Definition at line 79 of file GarnetNetwork.hh.
References Network::m_ordered.
Referenced by NetworkInterface::scheduleOutputLink().
makeExtInLink()
void GarnetNetwork::makeExtInLink (NodeID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry) virtual
Implements Network.
Definition at line 162 of file GarnetNetwork.cc.
References EXT_IN_, GarnetExtLink::m_credit_links, m_creditlinks, GarnetExtLink::m_network_links, m_networklinks, m_nis, Network::m_nodes, m_routers, safe_cast(), and NetworkLink::setType().
Referenced by get_vnet_type().
makeExtOutLink()
void GarnetNetwork::makeExtOutLink (SwitchID src, NodeID dest, BasicLink * link, const NetDest & routing_table_entry) virtual
Implements Network.
Definition at line 189 of file GarnetNetwork.cc.
References EXT_OUT_, GarnetExtLink::m_credit_links, m_creditlinks, GarnetExtLink::m_network_links, m_networklinks, m_nis, Network::m_nodes, m_routers, BasicLink::m_weight, safe_cast(), and NetworkLink::setType().
Referenced by get_vnet_type().
makeInternalLink()
void GarnetNetwork::makeInternalLink (SwitchID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry, PortDirection src_outport_dirn, PortDirection dest_inport_dirn) virtual
Implements Network.
Definition at line 219 of file GarnetNetwork.cc.
References INT_, GarnetIntLink::m_credit_link, m_creditlinks, GarnetIntLink::m_network_link, m_networklinks, m_routers, BasicLink::m_weight, safe_cast(), and NetworkLink::setType().
Referenced by get_vnet_type().
operator=()
GarnetNetwork& GarnetNetwork::operator= (const GarnetNetwork & obj) private
print()
void GarnetNetwork::print (std::ostream & out) const virtual
Implements Network.
Definition at line 431 of file GarnetNetwork.cc.
References GarnetNetwork().
Referenced by get_vnet_type(), and operator<<().
regStats()
void GarnetNetwork::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 255 of file GarnetNetwork.cc.
References csprintf(), Stats::DataWrap< Derived, InfoProxyType >::flags(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), m_average_link_utilization, m_average_vc_load, m_avg_flit_latency, m_avg_flit_network_latency, m_avg_flit_queueing_latency, m_avg_flit_vnet_latency, m_avg_flit_vqueue_latency, m_avg_hops, m_avg_packet_latency, m_avg_packet_network_latency, m_avg_packet_queueing_latency, m_avg_packet_vnet_latency, m_avg_packet_vqueue_latency, m_flit_network_latency, m_flit_queueing_latency, m_flits_injected, m_flits_received, m_packet_network_latency, m_packet_queueing_latency, m_packets_injected, m_packets_received, m_total_ext_in_link_utilization, m_total_ext_out_link_utilization, m_total_hops, m_total_int_link_utilization, m_vcs_per_vnet, Network::m_virtual_networks, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, Stats::oneline, Stats::pdf, Stats::Group::regStats(), Stats::DataWrapVec< Derived, InfoProxyType >::subname(), RiscvISA::sum, and Stats::total.
Referenced by get_vnet_type().
Member Data Documentation
fault_model
FaultModel* GarnetNetwork::fault_model
Definition at line 75 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), Router::get_aggregate_fault_probability(), Router::get_fault_vector(), init(), and Router::printFaultVector().
m_average_link_utilization
Stats::Scalar GarnetNetwork::m_average_link_utilization protected
Definition at line 183 of file GarnetNetwork.hh.
Referenced by collateStats(), and regStats().
m_average_vc_load
Stats::Vector GarnetNetwork::m_average_vc_load protected
Definition at line 184 of file GarnetNetwork.hh.
Referenced by collateStats(), and regStats().
m_avg_flit_latency
Stats::Formula GarnetNetwork::m_avg_flit_latency protected
Definition at line 178 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_flit_network_latency
Stats::Formula GarnetNetwork::m_avg_flit_network_latency protected
Definition at line 176 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_flit_queueing_latency
Stats::Formula GarnetNetwork::m_avg_flit_queueing_latency protected
Definition at line 177 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_flit_vnet_latency
Stats::Formula GarnetNetwork::m_avg_flit_vnet_latency protected
Definition at line 174 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_flit_vqueue_latency
Stats::Formula GarnetNetwork::m_avg_flit_vqueue_latency protected
Definition at line 175 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_hops
Stats::Formula GarnetNetwork::m_avg_hops protected
Definition at line 187 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_packet_latency
Stats::Formula GarnetNetwork::m_avg_packet_latency protected
Definition at line 167 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_packet_network_latency
Stats::Formula GarnetNetwork::m_avg_packet_network_latency protected
Definition at line 165 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_packet_queueing_latency
Stats::Formula GarnetNetwork::m_avg_packet_queueing_latency protected
Definition at line 166 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_packet_vnet_latency
Stats::Formula GarnetNetwork::m_avg_packet_vnet_latency protected
Definition at line 163 of file GarnetNetwork.hh.
Referenced by regStats().
m_avg_packet_vqueue_latency
Stats::Formula GarnetNetwork::m_avg_packet_vqueue_latency protected
Definition at line 164 of file GarnetNetwork.hh.
Referenced by regStats().
m_buffers_per_ctrl_vc
uint32_t GarnetNetwork::m_buffers_per_ctrl_vc protected
Definition at line 152 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and getBuffersPerCtrlVC().
m_buffers_per_data_vc
uint32_t GarnetNetwork::m_buffers_per_data_vc protected
Definition at line 153 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and getBuffersPerDataVC().
m_creditlinks
std::vector<CreditLink *> GarnetNetwork::m_creditlinks private
Definition at line 196 of file GarnetNetwork.hh.
Referenced by makeExtInLink(), makeExtOutLink(), makeInternalLink(), and ~GarnetNetwork().
m_enable_fault_model
bool GarnetNetwork::m_enable_fault_model protected
Definition at line 155 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and isFaultModelEnabled().
m_flit_network_latency
Stats::Vector GarnetNetwork::m_flit_network_latency protected
Definition at line 171 of file GarnetNetwork.hh.
Referenced by increment_flit_network_latency(), and regStats().
m_flit_queueing_latency
Stats::Vector GarnetNetwork::m_flit_queueing_latency protected
Definition at line 172 of file GarnetNetwork.hh.
Referenced by increment_flit_queueing_latency(), and regStats().
m_flits_injected
Stats::Vector GarnetNetwork::m_flits_injected protected
Definition at line 170 of file GarnetNetwork.hh.
Referenced by increment_injected_flits(), and regStats().
m_flits_received
Stats::Vector GarnetNetwork::m_flits_received protected
Definition at line 169 of file GarnetNetwork.hh.
Referenced by increment_received_flits(), and regStats().
m_networklinks
std::vector<NetworkLink *> GarnetNetwork::m_networklinks private
Definition at line 195 of file GarnetNetwork.hh.
Referenced by collateStats(), functionalWrite(), makeExtInLink(), makeExtOutLink(), makeInternalLink(), and ~GarnetNetwork().
m_ni_flit_size
uint32_t GarnetNetwork::m_ni_flit_size protected
Definition at line 150 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and getNiFlitSize().
m_nis
std::vector<NetworkInterface *> GarnetNetwork::m_nis private
Definition at line 197 of file GarnetNetwork.hh.
Referenced by functionalWrite(), GarnetNetwork(), get_router_id(), init(), makeExtInLink(), makeExtOutLink(), and ~GarnetNetwork().
m_num_cols
int GarnetNetwork::m_num_cols protected
Definition at line 149 of file GarnetNetwork.hh.
Referenced by getNumCols(), and init().
m_num_rows
int GarnetNetwork::m_num_rows protected
Definition at line 148 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), getNumRows(), and init().
m_packet_network_latency
Stats::Vector GarnetNetwork::m_packet_network_latency protected
Definition at line 160 of file GarnetNetwork.hh.
Referenced by increment_packet_network_latency(), and regStats().
m_packet_queueing_latency
Stats::Vector GarnetNetwork::m_packet_queueing_latency protected
Definition at line 161 of file GarnetNetwork.hh.
Referenced by increment_packet_queueing_latency(), and regStats().
m_packets_injected
Stats::Vector GarnetNetwork::m_packets_injected protected
Definition at line 159 of file GarnetNetwork.hh.
Referenced by increment_injected_packets(), and regStats().
m_packets_received
Stats::Vector GarnetNetwork::m_packets_received protected
Definition at line 158 of file GarnetNetwork.hh.
Referenced by increment_received_packets(), and regStats().
m_routers
std::vector<Router *> GarnetNetwork::m_routers private
Definition at line 194 of file GarnetNetwork.hh.
Referenced by collateStats(), functionalWrite(), GarnetNetwork(), getNumRouters(), init(), makeExtInLink(), makeExtOutLink(), makeInternalLink(), and ~GarnetNetwork().
m_routing_algorithm
int GarnetNetwork::m_routing_algorithm protected
Definition at line 154 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and getRoutingAlgorithm().
m_total_ext_in_link_utilization
Stats::Scalar GarnetNetwork::m_total_ext_in_link_utilization protected
Definition at line 180 of file GarnetNetwork.hh.
Referenced by collateStats(), and regStats().
m_total_ext_out_link_utilization
Stats::Scalar GarnetNetwork::m_total_ext_out_link_utilization protected
Definition at line 181 of file GarnetNetwork.hh.
Referenced by collateStats(), and regStats().
m_total_hops
Stats::Scalar GarnetNetwork::m_total_hops protected
Definition at line 186 of file GarnetNetwork.hh.
Referenced by increment_total_hops(), and regStats().
m_total_int_link_utilization
Stats::Scalar GarnetNetwork::m_total_int_link_utilization protected
Definition at line 182 of file GarnetNetwork.hh.
Referenced by collateStats(), and regStats().
m_vcs_per_vnet
uint32_t GarnetNetwork::m_vcs_per_vnet protected
Definition at line 151 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), getVCsPerVnet(), and regStats().
m_vnet_type
std::vector<VNET_type > GarnetNetwork::m_vnet_type private
Definition at line 193 of file GarnetNetwork.hh.
Referenced by GarnetNetwork(), and get_vnet_type().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/GarnetNetwork.hh
mem/ruby/network/garnet2.0/GarnetNetwork.cc