gem5: HDLcd::PixelPump Class Reference
HDLcd::PixelPump Class Reference
#include <hdlcd.hh>
Public Member Functions
PixelPump (HDLcd &p, ClockDomain &pxl_clk, unsigned pixel_chunk)
void dumpSettings ()
Public Member Functions inherited from BasePixelPump
BasePixelPump (EventManager &em, ClockDomain &pxl_clk, unsigned pixel_chunk)
virtual ~BasePixelPump ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void updateTimings (const DisplayTimings &timings)
Update frame size using display timing.
void renderFrame ()
Render an entire frame in KVM execution mode.
void start ()
Starting pushing pixels in timing mode.
void stop ()
Immediately stop pushing pixels.
const DisplayTimings & timings () const
Get a constant reference of the current display timings.
bool active () const
Is the pixel pump active and refreshing the display?
bool underrun () const
Did a buffer underrun occur within this refresh interval?
bool visibleLine () const
Is the current line within the visible range?
unsigned posX () const
Current pixel position within the visible area.
unsigned posY () const
Current pixel position within the visible area.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Member Functions
bool nextPixel (Pixel &p) override
Get the next pixel from the scan line buffer.
void onVSyncBegin () override
First pixel clock of the first VSync line.
void onVSyncEnd () override
Callback on the first pixel of the line after the end VSync region (typically the first pixel of the vertical back porch).
void onUnderrun (unsigned x, unsigned y) override
Buffer underrun occurred on a frame.
void onFrameDone () override
Finished displaying the visible region of a frame.
Protected Member Functions inherited from BasePixelPump
virtual void onHSyncBegin ()
Start of the HSync region.
virtual void onHSyncEnd ()
Start of the first pixel after the HSync region.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
HDLcd & parent
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BasePixelPump
FrameBuffer fb
Output frame buffer.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 324 of file hdlcd.hh.
Constructor & Destructor Documentation
PixelPump()
HDLcd::PixelPump::PixelPump (HDLcd & p, ClockDomain & pxl_clk, unsigned pixel_chunk) inline
Definition at line 327 of file hdlcd.hh.
References dumpSettings().
Member Function Documentation
dumpSettings()
void HDLcd::PixelPump::dumpSettings ()
Definition at line 680 of file hdlcd.cc.
References DisplayTimings::hBackPorch, HDLcd::HDLcd(), DisplayTimings::height, DisplayTimings::hFrontPorch, DisplayTimings::hSync, inform, ArmISA::t, DisplayTimings::vBackPorch, DisplayTimings::vFrontPorch, DisplayTimings::vSync, and DisplayTimings::width.
Referenced by PixelPump(), and HDLcd::pxlFrameDone().
nextPixel()
bool HDLcd::PixelPump::nextPixel (Pixel & p) inline override protected virtual
Get the next pixel from the scan line buffer.
Parameters
p Output pixel value, undefined on underrun
Returns
true on success, false on buffer underrun
Implements BasePixelPump.
Definition at line 333 of file hdlcd.hh.
References parent, and HDLcd::pxlNext().
onFrameDone()
void HDLcd::PixelPump::onFrameDone () inline override protected virtual
Finished displaying the visible region of a frame.
Reimplemented from BasePixelPump.
Definition at line 342 of file hdlcd.hh.
References parent, and HDLcd::pxlFrameDone().
onUnderrun()
void HDLcd::PixelPump::onUnderrun (unsigned x, unsigned y) inline override protected virtual
Buffer underrun occurred on a frame.
This method is called once if there is buffer underrun while refreshing the display. The underrun state is reset on the next refresh.
Parameters
x Coordinate within the visible region.
y Coordinate within the visible region.
Reimplemented from BasePixelPump.
Definition at line 338 of file hdlcd.hh.
References parent, and HDLcd::pxlUnderrun().
onVSyncBegin()
void HDLcd::PixelPump::onVSyncBegin () inline override protected virtual
First pixel clock of the first VSync line.
Reimplemented from BasePixelPump.
Definition at line 335 of file hdlcd.hh.
References parent, and HDLcd::pxlVSyncBegin().
onVSyncEnd()
void HDLcd::PixelPump::onVSyncEnd () inline override protected virtual
Callback on the first pixel of the line after the end VSync region (typically the first pixel of the vertical back porch).
Reimplemented from BasePixelPump.
Definition at line 336 of file hdlcd.hh.
References parent, and HDLcd::pxlVSyncEnd().
Member Data Documentation
parent
HDLcd& HDLcd::PixelPump::parent protected
Definition at line 345 of file hdlcd.hh.
Referenced by nextPixel(), onFrameDone(), onUnderrun(), onVSyncBegin(), and onVSyncEnd().
The documentation for this class was generated from the following files:
dev/arm/hdlcd.hh
dev/arm/hdlcd.cc