gem5: UnifiedFreeList Class Reference
UnifiedFreeList Class Reference
FreeList class that simply holds the list of free integer and floating point registers.
#include <free_list.hh>
Public Member Functions
UnifiedFreeList (const std::string &_my_name, PhysRegFile *_regFile)
Constructs a free list.
std::string name () const
Gives the name of the freelist.
SimpleFreeList * getCCList ()
Returns a pointer to the condition-code free list.
PhysRegIdPtr getIntReg ()
Gets a free integer register.
PhysRegIdPtr getFloatReg ()
Gets a free fp register.
PhysRegIdPtr getVecReg ()
Gets a free vector register.
PhysRegIdPtr getVecElem ()
Gets a free vector elemenet register.
PhysRegIdPtr getVecPredReg ()
Gets a free predicate register.
PhysRegIdPtr getCCReg ()
Gets a free cc register.
void addReg (PhysRegIdPtr freed_reg)
Adds a register back to the free list.
template<class InputIt >
void addRegs (InputIt first, InputIt last)
Adds a register back to the free list.
void addIntReg (PhysRegIdPtr freed_reg)
Adds an integer register back to the free list.
void addFloatReg (PhysRegIdPtr freed_reg)
Adds a fp register back to the free list.
void addVecReg (PhysRegIdPtr freed_reg)
Adds a vector register back to the free list.
void addVecElem (PhysRegIdPtr freed_reg)
Adds a vector element register back to the free list.
void addVecPredReg (PhysRegIdPtr freed_reg)
Adds a predicate register back to the free list.
void addCCReg (PhysRegIdPtr freed_reg)
Adds a cc register back to the free list.
bool hasFreeIntRegs () const
Checks if there are any free integer registers.
bool hasFreeFloatRegs () const
Checks if there are any free fp registers.
bool hasFreeVecRegs () const
Checks if there are any free vector registers.
bool hasFreeVecElems () const
Checks if there are any free vector registers.
bool hasFreeVecPredRegs () const
Checks if there are any free predicate registers.
bool hasFreeCCRegs () const
Checks if there are any free cc registers.
unsigned numFreeIntRegs () const
Returns the number of free integer registers.
unsigned numFreeFloatRegs () const
Returns the number of free fp registers.
unsigned numFreeVecRegs () const
Returns the number of free vector registers.
unsigned numFreeVecElems () const
Returns the number of free vector registers.
unsigned numFreeVecPredRegs () const
Returns the number of free predicate registers.
unsigned numFreeCCRegs () const
Returns the number of free cc registers.
Private Attributes
const std::string _name
The object name, for DPRINTF.
SimpleFreeList intList
The list of free integer registers.
SimpleFreeList floatList
The list of free floating point registers.
SimpleFreeList predList
The list of free predicate registers.
SimpleFreeList ccList
The list of free condition-code registers.
PhysRegFile * regFile
The register file object is used only to distinguish integer from floating-point physical register indices.
SimpleFreeList vecList
The following two are exclusive interfaces.
SimpleFreeList vecElemList
The list of free vector element registers.
Friends
class UnifiedRenameMap
Detailed Description
FreeList class that simply holds the list of free integer and floating point registers.
Can request for a free register of either type, and also send back free registers of either type. This is a very simple class, but it should be sufficient for most implementations. Like all other classes, it assumes that the indices for the floating point registers starts after the integer registers end. Hence the variable numPhysicalIntRegs is logically equivalent to the baseFP dependency. Note that while this most likely should be called FreeList, the name "FreeList" is used in a typedef within the CPU Policy, and therefore no class can be named simply "FreeList".
Todo:
: Give a better name to the base FP dependency.
Definition at line 117 of file free_list.hh.
Constructor & Destructor Documentation
UnifiedFreeList()
UnifiedFreeList::UnifiedFreeList (const std::string & _my_name, PhysRegFile * _regFile)
Constructs a free list.
Parameters
_numPhysicalIntRegs Number of physical integer registers.
reservedIntRegs Number of integer registers already used by initial mappings.
_numPhysicalFloatRegs Number of physical fp registers.
reservedFloatRegs Number of fp registers already used by initial mappings.
Definition at line 39 of file free_list.cc.
References DPRINTF, PhysRegFile::initFreeList(), and regFile.
Member Function Documentation
addCCReg()
void UnifiedFreeList::addCCReg (PhysRegIdPtr freed_reg) inline
Adds a cc register back to the free list.
Definition at line 219 of file free_list.hh.
References SimpleFreeList::addReg().
addFloatReg()
void UnifiedFreeList::addFloatReg (PhysRegIdPtr freed_reg) inline
Adds a fp register back to the free list.
Definition at line 205 of file free_list.hh.
References SimpleFreeList::addReg().
addIntReg()
void UnifiedFreeList::addIntReg (PhysRegIdPtr freed_reg) inline
Adds an integer register back to the free list.
Definition at line 202 of file free_list.hh.
References SimpleFreeList::addReg().
addReg()
void UnifiedFreeList::addReg (PhysRegIdPtr freed_reg) inline
Adds a register back to the free list.
Definition at line 298 of file free_list.hh.
References CCRegClass, RegId::className(), RegId::classValue(), DPRINTF, FloatRegClass, RegId::index(), IntRegClass, panic, VecElemClass, VecPredRegClass, and VecRegClass.
addRegs()
template<class InputIt > void UnifiedFreeList::addRegs (InputIt first, InputIt last) inline
Adds a register back to the free list.
Definition at line 260 of file free_list.hh.
References CCRegClass, FloatRegClass, IntRegClass, panic, panic_if, VecElemClass, VecPredRegClass, and VecRegClass.
Referenced by PhysRegFile::initFreeList(), and UnifiedRenameMap::switchFreeList().
addVecElem()
void UnifiedFreeList::addVecElem (PhysRegIdPtr freed_reg) inline
Adds a vector element register back to the free list.
Definition at line 211 of file free_list.hh.
References SimpleFreeList::addReg().
addVecPredReg()
void UnifiedFreeList::addVecPredReg (PhysRegIdPtr freed_reg) inline
Adds a predicate register back to the free list.
Definition at line 216 of file free_list.hh.
References SimpleFreeList::addReg().
addVecReg()
void UnifiedFreeList::addVecReg (PhysRegIdPtr freed_reg) inline
Adds a vector register back to the free list.
Definition at line 208 of file free_list.hh.
References SimpleFreeList::addReg().
getCCList()
SimpleFreeList* UnifiedFreeList::getCCList () inline
Returns a pointer to the condition-code free list.
Definition at line 174 of file free_list.hh.
getCCReg()
PhysRegIdPtr UnifiedFreeList::getCCReg () inline
Gets a free cc register.
Definition at line 192 of file free_list.hh.
References SimpleFreeList::addReg(), SimpleFreeList::addRegs(), and SimpleFreeList::getReg().
getFloatReg()
PhysRegIdPtr UnifiedFreeList::getFloatReg () inline
Gets a free fp register.
Definition at line 180 of file free_list.hh.
References SimpleFreeList::getReg().
getIntReg()
PhysRegIdPtr UnifiedFreeList::getIntReg () inline
Gets a free integer register.
Definition at line 177 of file free_list.hh.
References SimpleFreeList::getReg().
getVecElem()
PhysRegIdPtr UnifiedFreeList::getVecElem () inline
Gets a free vector elemenet register.
Definition at line 186 of file free_list.hh.
References SimpleFreeList::getReg().
Referenced by UnifiedRenameMap::switchFreeList().
getVecPredReg()
PhysRegIdPtr UnifiedFreeList::getVecPredReg () inline
Gets a free predicate register.
Definition at line 189 of file free_list.hh.
References SimpleFreeList::getReg().
getVecReg()
PhysRegIdPtr UnifiedFreeList::getVecReg () inline
Gets a free vector register.
Definition at line 183 of file free_list.hh.
References SimpleFreeList::getReg().
Referenced by UnifiedRenameMap::switchFreeList().
hasFreeCCRegs()
bool UnifiedFreeList::hasFreeCCRegs () const inline
Checks if there are any free cc registers.
Definition at line 237 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
hasFreeFloatRegs()
bool UnifiedFreeList::hasFreeFloatRegs () const inline
Checks if there are any free fp registers.
Definition at line 225 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
hasFreeIntRegs()
bool UnifiedFreeList::hasFreeIntRegs () const inline
Checks if there are any free integer registers.
Definition at line 222 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
hasFreeVecElems()
bool UnifiedFreeList::hasFreeVecElems () const inline
Checks if there are any free vector registers.
Definition at line 231 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
Referenced by UnifiedRenameMap::switchFreeList().
hasFreeVecPredRegs()
bool UnifiedFreeList::hasFreeVecPredRegs () const inline
Checks if there are any free predicate registers.
Definition at line 234 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
hasFreeVecRegs()
bool UnifiedFreeList::hasFreeVecRegs () const inline
Checks if there are any free vector registers.
Definition at line 228 of file free_list.hh.
References SimpleFreeList::hasFreeRegs().
Referenced by UnifiedRenameMap::switchFreeList().
name()
std::string UnifiedFreeList::name () const inline
Gives the name of the freelist.
Definition at line 171 of file free_list.hh.
numFreeCCRegs()
unsigned UnifiedFreeList::numFreeCCRegs () const inline
Returns the number of free cc registers.
Definition at line 255 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
numFreeFloatRegs()
unsigned UnifiedFreeList::numFreeFloatRegs () const inline
Returns the number of free fp registers.
Definition at line 243 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
numFreeIntRegs()
unsigned UnifiedFreeList::numFreeIntRegs () const inline
Returns the number of free integer registers.
Definition at line 240 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
numFreeVecElems()
unsigned UnifiedFreeList::numFreeVecElems () const inline
Returns the number of free vector registers.
Definition at line 249 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
Referenced by UnifiedRenameMap::switchFreeList().
numFreeVecPredRegs()
unsigned UnifiedFreeList::numFreeVecPredRegs () const inline
Returns the number of free predicate registers.
Definition at line 252 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
numFreeVecRegs()
unsigned UnifiedFreeList::numFreeVecRegs () const inline
Returns the number of free vector registers.
Definition at line 246 of file free_list.hh.
References SimpleFreeList::numFreeRegs().
Referenced by UnifiedRenameMap::switchFreeList().
Friends And Related Function Documentation
UnifiedRenameMap
friend class UnifiedRenameMap friend
Definition at line 157 of file free_list.hh.
Member Data Documentation
_name
const std::string UnifiedFreeList::_name private
The object name, for DPRINTF.
We have to declare this explicitly because Scoreboard is not a SimObject.
Definition at line 123 of file free_list.hh.
ccList
SimpleFreeList UnifiedFreeList::ccList private
The list of free condition-code registers.
Definition at line 144 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
floatList
SimpleFreeList UnifiedFreeList::floatList private
The list of free floating point registers.
Definition at line 129 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
intList
SimpleFreeList UnifiedFreeList::intList private
The list of free integer registers.
Definition at line 126 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
predList
SimpleFreeList UnifiedFreeList::predList private
The list of free predicate registers.
Definition at line 141 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
regFile
PhysRegFile* UnifiedFreeList::regFile private
The register file object is used only to distinguish integer from floating-point physical register indices.
Definition at line 150 of file free_list.hh.
Referenced by UnifiedFreeList().
vecElemList
SimpleFreeList UnifiedFreeList::vecElemList private
The list of free vector element registers.
Definition at line 137 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
vecList
SimpleFreeList UnifiedFreeList::vecList private
The following two are exclusive interfaces.
The list of free vector registers.
Definition at line 134 of file free_list.hh.
Referenced by UnifiedRenameMap::init().
The documentation for this class was generated from the following files:
cpu/o3/free_list.hh
cpu/o3/free_list.cc