gem5: SparcISA::TteTag Class Reference
SparcISA::TteTag Class Reference
#include <pagetable.hh>
Public Member Functions
TteTag ()
TteTag (uint64_t e)
const TteTag & operator= (uint64_t e)
bool valid () const
Addr va () const
Private Attributes
uint64_t entry
bool populated
Detailed Description
Definition at line 49 of file pagetable.hh.
Constructor & Destructor Documentation
TteTag() [1/2]
SparcISA::TteTag::TteTag () inline
Definition at line 56 of file pagetable.hh.
TteTag() [2/2]
SparcISA::TteTag::TteTag (uint64_t e) inline
Definition at line 57 of file pagetable.hh.
Member Function Documentation
operator=()
const TteTag& SparcISA::TteTag::operator= (uint64_t e) inline
Definition at line 60 of file pagetable.hh.
References ArmISA::e.
va()
Addr SparcISA::TteTag::va () const inline
Definition at line 68 of file pagetable.hh.
References bits().
Referenced by SparcISA::vtophys().
valid()
bool SparcISA::TteTag::valid () const inline
Definition at line 67 of file pagetable.hh.
References bits().
Referenced by SparcISA::vtophys().
Member Data Documentation
entry
uint64_t SparcISA::TteTag::entry private
Definition at line 52 of file pagetable.hh.
populated
bool SparcISA::TteTag::populated private
Definition at line 53 of file pagetable.hh.
The documentation for this class was generated from the following file:
arch/sparc/pagetable.hh