gem5: sc_gem5::Port Class Reference
sc_gem5::Port Class Reference
#include <port.hh>
Classes
struct Binding
struct Sensitivity
Public Member Functions
::sc_core::sc_port_base * sc_port_base ()
Port (::sc_core::sc_port_base *port_base, int max)
~Port ()
void bind (::sc_core::sc_interface *interface)
void bind (::sc_core::sc_port_base *port)
void sensitive (StaticSensitivityPort *port)
void sensitive (StaticSensitivityFinder *finder)
void addReset (Reset *reset)
void finalize ()
void regPort ()
int size ()
int maxSize ()
Static Public Member Functions
static Port * fromPort (const ::sc_core::sc_port_base *pb)
Private Member Functions
void finalizePort (StaticSensitivityPort *port)
void finalizeFinder (StaticSensitivityFinder *finder)
void finalizeReset (Reset *reset)
void addInterface (::sc_core::sc_interface *iface)
void addInterfaces (::sc_core::sc_port_base *pb)
::sc_core::sc_interface * getInterface (int i)
Private Attributes
::sc_core::sc_port_base * portBase
bool finalized
int _maxSize
int _size
bool regPortNeeded
std::vector< Binding * > bindings
std::vector< Sensitivity * > sensitivities
std::vector< Reset * > resets
Detailed Description
Definition at line 52 of file port.hh.
Constructor & Destructor Documentation
Port()
sc_gem5::Port::Port (::sc_core::sc_port_base * port_base, int max) inline
Definition at line 130 of file port.hh.
~Port()
sc_gem5::Port::~Port () inline
Definition at line 137 of file port.hh.
Member Function Documentation
addInterface()
void sc_gem5::Port::addInterface (::sc_core::sc_interface * iface) inline private
Definition at line 68 of file port.hh.
References sc_core::sc_port_base::_gem5AddInterface().
Referenced by addInterfaces(), bind(), and finalize().
addInterfaces()
void sc_gem5::Port::addInterfaces (::sc_core::sc_port_base * pb) inline private
Definition at line 75 of file port.hh.
References sc_core::sc_port_base::_gem5Interface(), sc_core::sc_port_base::_gem5Port, addInterface(), ArmISA::i, regPortNeeded, and sc_core::sc_port_base::size().
Referenced by finalize().
addReset()
void Port::addReset (Reset * reset)
Definition at line 87 of file port.cc.
References finalized, finalizeReset(), and resets.
Referenced by bind(), and sc_gem5::newReset().
bind() [1/2]
void sc_gem5::Port::bind (::sc_core::sc_interface * interface) inline
Definition at line 140 of file port.hh.
References addInterface(), and sc_gem5::Port::Binding::Binding().
Referenced by sc_gem5::TlmInitiatorBaseWrapper< BITWIDTH >::bind(), sc_gem5::ScPortWrapper< IF >::bind(), sc_core::sc_port_base::bind(), sc_gem5::TlmTargetBaseWrapper< BITWIDTH >::bind(), sc_gem5::ScInterfaceWrapper< IF >::bind(), and sc_gem5::ScExportWrapper< IF >::bind().
bind() [2/2]
void sc_gem5::Port::bind (::sc_core::sc_port_base * port) inline
Definition at line 149 of file port.hh.
References addReset(), sc_gem5::Port::Binding::Binding(), finalize(), sc_gem5::Port::Binding::port, regPort(), Stats::reset(), and sensitive().
finalize()
void Port::finalize ()
Definition at line 96 of file port.cc.
References sc_core::sc_port_base::_portPolicy(), addInterface(), addInterfaces(), ArmISA::b, bindings, finalized, finalizeFinder(), finalizePort(), finalizeReset(), maxSize(), panic, portBase, MipsISA::r, sc_core::sc_port_base::report_error(), resets, ArmISA::s, sc_core::SC_ALL_BOUND, sc_core::SC_ID_COMPLETE_BINDING_, sc_core::SC_ONE_OR_MORE_BOUND, sc_core::SC_ZERO_OR_MORE_BOUND, sensitivities, size(), and ArmISA::ss.
Referenced by bind().
finalizeFinder()
void Port::finalizeFinder (StaticSensitivityFinder * finder) private
Definition at line 49 of file port.cc.
References sc_gem5::SensitivityEvents::addEvent(), sc_gem5::StaticSensitivityFinder::find(), getInterface(), ArmISA::i, and size().
Referenced by finalize(), and sensitive().
finalizePort()
void Port::finalizePort (StaticSensitivityPort * port) private
Definition at line 42 of file port.cc.
References sc_gem5::SensitivityEvents::addEvent(), getInterface(), ArmISA::i, and size().
Referenced by finalize(), and sensitive().
finalizeReset()
void Port::finalizeReset (Reset * reset) private
Definition at line 56 of file port.cc.
References getInterface(), sc_gem5::Reset::install(), and size().
Referenced by addReset(), and finalize().
fromPort()
static Port* sc_gem5::Port::fromPort (const ::sc_core::sc_port_base * pb) inline static
Definition at line 123 of file port.hh.
Referenced by sc_gem5::newReset(), sc_gem5::newStaticSensitivityFinder(), and sc_gem5::newStaticSensitivityPort().
getInterface()
::sc_core::sc_interface* sc_gem5::Port::getInterface (int i) inline private
Definition at line 84 of file port.hh.
References sc_core::sc_port_base::_gem5Interface().
Referenced by finalizeFinder(), finalizePort(), finalizeReset(), and regPort().
maxSize()
int sc_gem5::Port::maxSize () inline
Definition at line 162 of file port.hh.
References _maxSize, and _size.
Referenced by finalize(), and sc_core::sc_port_base::maxSize().
regPort()
void Port::regPort ()
Definition at line 160 of file port.cc.
References sc_core::sc_port_base::_ifTypeName(), getInterface(), ArmISA::i, portBase, sc_core::sc_interface::register_port(), regPortNeeded, and size().
Referenced by bind().
sc_port_base()
::sc_core::sc_port_base* sc_gem5::Port::sc_port_base () inline
Definition at line 128 of file port.hh.
References portBase.
sensitive() [1/2]
void Port::sensitive (StaticSensitivityPort * port)
Definition at line 69 of file port.cc.
References finalized, finalizePort(), and sensitivities.
Referenced by bind(), sc_gem5::newStaticSensitivityFinder(), and sc_gem5::newStaticSensitivityPort().
sensitive() [2/2]
void Port::sensitive (StaticSensitivityFinder * finder)
Definition at line 78 of file port.cc.
References finalized, finalizeFinder(), and sensitivities.
size()
int sc_gem5::Port::size () inline
Definition at line 161 of file port.hh.
References _size.
Referenced by finalize(), finalizeFinder(), finalizePort(), finalizeReset(), regPort(), and sc_core::sc_port_base::size().
Member Data Documentation
_maxSize
int sc_gem5::Port::_maxSize private
Definition at line 58 of file port.hh.
Referenced by maxSize().
_size
int sc_gem5::Port::_size private
Definition at line 59 of file port.hh.
Referenced by maxSize(), and size().
bindings
std::vector<Binding *> sc_gem5::Port::bindings private
Definition at line 117 of file port.hh.
Referenced by finalize().
finalized
bool sc_gem5::Port::finalized private
Definition at line 57 of file port.hh.
Referenced by addReset(), finalize(), and sensitive().
portBase
::sc_core::sc_port_base* sc_gem5::Port::portBase private
Definition at line 55 of file port.hh.
Referenced by finalize(), regPort(), and sc_port_base().
regPortNeeded
bool sc_gem5::Port::regPortNeeded private
Definition at line 61 of file port.hh.
Referenced by addInterfaces(), and regPort().
resets
std::vector<Reset *> sc_gem5::Port::resets private
Definition at line 119 of file port.hh.
Referenced by addReset(), and finalize().
sensitivities
std::vector<Sensitivity *> sc_gem5::Port::sensitivities private
Definition at line 118 of file port.hh.
Referenced by finalize(), and sensitive().
The documentation for this class was generated from the following files:
systemc/core/port.hh
systemc/core/port.cc