gem5: Minor::MinorActivityRecorder Class Reference
Minor::MinorActivityRecorder Class Reference
ActivityRecorder with a Ticked interface.
#include <activity.hh>
Public Member Functions
void evaluate ()
Ticked interface.
void minorTrace () const
MinorActivityRecorder (const std::string &name, int num_stages, int longest_latency)
Public Member Functions inherited from ActivityRecorder
ActivityRecorder (const std::string &name, int num_stages, int longest_latency, int count)
~ActivityRecorder ()
void activity ()
Records that there is activity this cycle.
void advance ()
Advances the activity buffer, decrementing the activityCount if active communication just left the time buffer, and determining if there is no activity.
void activateStage (const int idx)
Marks a stage as active.
void deactivateStage (const int idx)
Deactivates a stage.
bool getStageActive (const int idx) const
Returns the activity status of a stage.
int getNumStages () const
Returns the number of stages.
int getActivityCount () const
Returns how many things are active within the recorder.
void setActivityCount (int count)
Sets the count to a starting value.
bool active ()
Returns if the CPU should be active.
void reset ()
Clears the time buffer and the activity count.
void dump ()
Debug function to dump the contents of the time buffer.
void validate ()
Debug function to ensure that the activity count matches the contents of the time buffer.
const std::string & name () const
Detailed Description
ActivityRecorder with a Ticked interface.
Definition at line 56 of file activity.hh.
Constructor & Destructor Documentation
MinorActivityRecorder()
Minor::MinorActivityRecorder::MinorActivityRecorder (const std::string & name, int num_stages, int longest_latency) inline
Definition at line 64 of file activity.hh.
Member Function Documentation
evaluate()
void Minor::MinorActivityRecorder::evaluate () inline
Ticked interface.
Definition at line 60 of file activity.hh.
References ActivityRecorder::advance(), and minorTrace().
Referenced by Minor::Pipeline::evaluate().
minorTrace()
void Minor::MinorActivityRecorder::minorTrace () const
Definition at line 50 of file activity.cc.
References ActivityRecorder::getActivityCount(), ActivityRecorder::getNumStages(), ActivityRecorder::getStageActive(), and MINORTRACE.
Referenced by evaluate(), and Minor::Pipeline::minorTrace().
The documentation for this class was generated from the following files:
cpu/minor/activity.hh
cpu/minor/activity.cc