gem5: X86ISA::TLB Class Reference
X86ISA::TLB Class Reference
#include <tlb.hh>
Public Types
typedef X86TLBParams Params
Public Types inherited from BaseTLB
enum Mode { Read, Write, Execute }
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TLB (const Params *p)
void takeOverFrom (BaseTLB *otlb) override
Take over from an old tlb context.
TlbEntry * lookup (Addr va, bool update_lru=true)
void setConfigAddress (uint32_t addr)
Walker * getWalker ()
void flushAll () override
Remove all entries from the TLB.
void flushNonGlobal ()
void demapPage (Addr va, uint64_t asn) override
void evictLRU ()
uint64_t nextSeq ()
Fault translateAtomic (const RequestPtr &req, ThreadContext *tc, Mode mode) override
void translateTiming (const RequestPtr &req, ThreadContext *tc, Translation *translation, Mode mode) override
Fault finalizePhysical (const RequestPtr &req, ThreadContext *tc, Mode mode) const override
Do post-translation physical address finalization.
TlbEntry * insert (Addr vpn, const TlbEntry &entry)
void regStats () override
Callback to set stat parameters.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Port * getTableWalkerPort () override
Get the table walker port.
Public Member Functions inherited from BaseTLB
virtual Fault translateFunctional (const RequestPtr &req, ThreadContext *tc, Mode mode)
void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
typedef std::list< TlbEntry * > EntryList
Protected Member Functions
EntryList::iterator lookupIt (Addr va, bool update_lru=true)
Fault translateInt (const RequestPtr &req, ThreadContext *tc)
Fault translate (const RequestPtr &req, ThreadContext *tc, Translation *translation, Mode mode, bool &delayedResponse, bool timing)
Protected Member Functions inherited from BaseTLB
BaseTLB (const Params *p)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
uint32_t configAddress
Walker * walker
uint32_t size
std::vector< TlbEntry > tlb
EntryList freeList
TlbEntryTrie trie
uint64_t lruSeq
Stats::Scalar rdAccesses
Stats::Scalar wrAccesses
Stats::Scalar rdMisses
Stats::Scalar wrMisses
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class Walker
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 58 of file tlb.hh.
Member Typedef Documentation
EntryList
typedef std::list<TlbEntry *> X86ISA::TLB::EntryList protected
Definition at line 63 of file tlb.hh.
Params
typedef X86TLBParams X86ISA::TLB::Params
Definition at line 69 of file tlb.hh.
Constructor & Destructor Documentation
TLB()
X86ISA::TLB::TLB (const Params * p)
Definition at line 62 of file tlb.cc.
References fatal, freeList, X86ISA::Walker::setTLB(), size, tlb, walker, and X86ISA::x.
Member Function Documentation
demapPage()
void X86ISA::TLB::demapPage (Addr va, uint64_t asn) override virtual
Implements BaseTLB.
Definition at line 162 of file tlb.cc.
References freeList, Trie< Key, Value >::lookup(), Trie< Key, Value >::remove(), trie, and X86ISA::TlbEntry::trieHandle.
evictLRU()
void X86ISA::TLB::evictLRU ()
Definition at line 79 of file tlb.cc.
References freeList, ArmISA::i, lruSeq, Trie< Key, Value >::remove(), size, tlb, and trie.
Referenced by insert().
finalizePhysical()
Fault X86ISA::TLB::finalizePhysical (const RequestPtr & req, ThreadContext * tc, Mode mode) const override virtual
Do post-translation physical address finalization.
Some addresses, for example requests going to the APIC, need post-translation updates. Such physical addresses are remapped into a "magic" part of the physical address space by this method.
Parameters
req Request to updated in-place.
tc Thread context that created the request.
mode Request type (read/write/execute).
Returns
A fault on failure, NoFault otherwise.
Implements BaseTLB.
Definition at line 227 of file tlb.cc.
References AddrRange::contains(), ThreadContext::contextId(), FullSystem, Request::GENERIC_IPR, GenericISA::iprAddressPseudoInst(), X86ISA::MISCREG_APIC_BASE, Request::MMAPPED_IPR, NoFault, X86ISA::PageBytes, ThreadContext::readMiscRegNoEffect(), AddrRange::start(), Request::STRICT_ORDER, Request::UNCACHEABLE, and X86ISA::x86LocalAPICAddress().
Referenced by nextSeq(), and translate().
flushAll()
void X86ISA::TLB::flushAll () override virtual
Remove all entries from the TLB.
Implements BaseTLB.
Definition at line 130 of file tlb.cc.
References DPRINTF, freeList, ArmISA::i, Trie< Key, Value >::remove(), size, tlb, and trie.
flushNonGlobal()
void X86ISA::TLB::flushNonGlobal ()
Definition at line 149 of file tlb.cc.
References DPRINTF, freeList, ArmISA::i, Trie< Key, Value >::remove(), size, tlb, and trie.
getTableWalkerPort()
Port * X86ISA::TLB::getTableWalkerPort () override virtual
Get the table walker port.
This is used for migrating port connections during a CPU takeOverFrom() call. For architectures that do not have a table walker, NULL is returned, hence the use of a pointer rather than a reference. For X86 this method will always return a valid port pointer.
Returns
A pointer to the walker port
Reimplemented from BaseTLB.
Definition at line 517 of file tlb.cc.
References X86ISA::Walker::getPort(), and walker.
Referenced by nextSeq().
getWalker()
Walker * X86ISA::TLB::getWalker ()
Definition at line 451 of file tlb.cc.
References walker.
insert()
TlbEntry * X86ISA::TLB::insert (Addr vpn, const TlbEntry & entry)
Definition at line 97 of file tlb.cc.
References evictLRU(), freeList, Trie< Key, Value >::insert(), X86ISA::TlbEntry::logBytes, Trie< Key, Value >::lookup(), X86ISA::TlbEntry::lruSeq, Trie< Addr, X86ISA::TlbEntry >::MaxBits, nextSeq(), trie, X86ISA::TlbEntry::trieHandle, and X86ISA::TlbEntry::vaddr.
Referenced by nextSeq(), and translate().
lookup()
TlbEntry * X86ISA::TLB::lookup (Addr va, bool update_lru = true)
Definition at line 121 of file tlb.cc.
References Trie< Key, Value >::lookup(), X86ISA::TlbEntry::lruSeq, nextSeq(), and trie.
Referenced by takeOverFrom(), and translate().
lookupIt()
EntryList::iterator X86ISA::TLB::lookupIt (Addr va, bool update_lru = true) protected
Referenced by takeOverFrom().
nextSeq()
uint64_t X86ISA::TLB::nextSeq () inline
Definition at line 120 of file tlb.hh.
References finalizePhysical(), getTableWalkerPort(), insert(), lruSeq, ArmISA::mode, regStats(), serialize(), translateAtomic(), translateTiming(), and unserialize().
Referenced by insert(), and lookup().
regStats()
void X86ISA::TLB::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 457 of file tlb.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), rdAccesses, rdMisses, Stats::Group::regStats(), wrAccesses, and wrMisses.
Referenced by nextSeq().
serialize()
void X86ISA::TLB::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 480 of file tlb.cc.
References csprintf(), freeList, lruSeq, SERIALIZE_SCALAR, size, tlb, and X86ISA::x.
Referenced by nextSeq().
setConfigAddress()
void X86ISA::TLB::setConfigAddress (uint32_t addr)
Definition at line 143 of file tlb.cc.
References X86ISA::addr, and configAddress.
Referenced by takeOverFrom().
takeOverFrom()
void X86ISA::TLB::takeOverFrom (BaseTLB * otlb) inline override virtual
Take over from an old tlb context.
Implements BaseTLB.
Definition at line 72 of file tlb.hh.
References X86ISA::addr, lookup(), lookupIt(), setConfigAddress(), and ArmISA::va.
translate()
Fault X86ISA::TLB::translate (const RequestPtr & req, ThreadContext * tc, Translation * translation, Mode mode, bool & delayedResponse, bool timing) protected
Definition at line 269 of file tlb.cc.
References X86ISA::AddrSizeFlagBit, ArmISA::attr, X86ISA::base, bits(), X86ISA::CPL0FlagBit, DPRINTF, BaseTLB::Execute, X86ISA::expandDown, finalizePhysical(), Process::fixupStackFault(), EmulationPageTable::Entry::flags, X86ISA::FlagShift, FullSystem, ThreadContext::getProcessPtr(), insert(), ThreadContext::instAddr(), X86ISA::limit, X86ISA::TlbEntry::logBytes, lookup(), EmulationPageTable::lookup(), X86ISA::mask, X86ISA::MISCREG_CR0, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::MISCREG_SEG_SEL(), ArmISA::mode, NoFault, X86ISA::offset, X86ISA::p, EmulationPageTable::Entry::paddr, X86ISA::TlbEntry::paddr, EmulationPageTable::pageAlign(), EmulationPageTable::pid(), Process::pTable, rdAccesses, rdMisses, BaseTLB::Read, ThreadContext::readMiscRegNoEffect(), EmulationPageTable::ReadOnly, X86ISA::seg, X86ISA::SEGMENT_REG_ES, X86ISA::SEGMENT_REG_HS, X86ISA::SEGMENT_REG_LS, X86ISA::SEGMENT_REG_MS, X86ISA::SEGMENT_REG_TSG, X86ISA::SegmentFlagMask, X86ISA::SixtyFourBitMode, size, X86ISA::Walker::start(), X86ISA::StoreCheck, Request::STRICT_ORDER, X86ISA::SYS_SEGMENT_REG_IDTR, translateInt(), X86ISA::TlbEntry::uncacheable, EmulationPageTable::Uncacheable, Request::UNCACHEABLE, X86ISA::TlbEntry::user, MipsISA::vaddr, walker, warn_once, wrAccesses, X86ISA::TlbEntry::writable, BaseTLB::Write, and wrMisses.
Referenced by translateAtomic(), and translateTiming().
translateAtomic()
Fault X86ISA::TLB::translateAtomic (const RequestPtr & req, ThreadContext * tc, Mode mode) override virtual
Implements BaseTLB.
Definition at line 430 of file tlb.cc.
References translate().
Referenced by nextSeq().
translateInt()
Fault X86ISA::TLB::translateInt (const RequestPtr & req, ThreadContext * tc) protected
Definition at line 173 of file tlb.cc.
References bits(), configAddress, DPRINTF, X86ISA::IntAddrPrefixCPUID, X86ISA::IntAddrPrefixIO, X86ISA::IntAddrPrefixMask, X86ISA::IntAddrPrefixMSR, X86ISA::mask, mbits(), X86ISA::MISCREG_PCI_CONFIG_ADDRESS, Request::MMAPPED_IPR, X86ISA::msrAddrToIndex(), NoFault, panic, X86ISA::PhysAddrPrefixIO, X86ISA::PhysAddrPrefixPciConfig, ThreadContext::readMiscRegNoEffect(), Request::STRICT_ORDER, Request::UNCACHEABLE, and MipsISA::vaddr.
Referenced by translate().
translateTiming()
void X86ISA::TLB::translateTiming (const RequestPtr & req, ThreadContext * tc, Translation * translation, Mode mode) override virtual
Implements BaseTLB.
Definition at line 437 of file tlb.cc.
References BaseTLB::Translation::finish(), BaseTLB::Translation::markDelayed(), and translate().
Referenced by nextSeq().
unserialize()
void X86ISA::TLB::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 495 of file tlb.cc.
References csprintf(), fatal, freeList, Trie< Key, Value >::insert(), X86ISA::TlbEntry::logBytes, lruSeq, Trie< Addr, X86ISA::TlbEntry >::MaxBits, size, trie, X86ISA::TlbEntry::trieHandle, UNSERIALIZE_SCALAR, Serializable::unserializeSection(), X86ISA::TlbEntry::vaddr, and X86ISA::x.
Referenced by nextSeq().
Friends And Related Function Documentation
Walker
friend class Walker friend
Definition at line 61 of file tlb.hh.
Member Data Documentation
configAddress
uint32_t X86ISA::TLB::configAddress protected
Definition at line 65 of file tlb.hh.
Referenced by setConfigAddress(), and translateInt().
freeList
EntryList X86ISA::TLB::freeList protected
Definition at line 98 of file tlb.hh.
Referenced by demapPage(), evictLRU(), flushAll(), flushNonGlobal(), insert(), serialize(), TLB(), and unserialize().
lruSeq
uint64_t X86ISA::TLB::lruSeq protected
Definition at line 101 of file tlb.hh.
Referenced by evictLRU(), nextSeq(), serialize(), and unserialize().
rdAccesses
Stats::Scalar X86ISA::TLB::rdAccesses protected
Definition at line 104 of file tlb.hh.
Referenced by regStats(), and translate().
rdMisses
Stats::Scalar X86ISA::TLB::rdMisses protected
Definition at line 106 of file tlb.hh.
Referenced by regStats(), and translate().
size
uint32_t X86ISA::TLB::size protected
Definition at line 94 of file tlb.hh.
Referenced by evictLRU(), flushAll(), flushNonGlobal(), serialize(), TLB(), translate(), and unserialize().
tlb
std::vector<TlbEntry> X86ISA::TLB::tlb protected
Definition at line 96 of file tlb.hh.
Referenced by evictLRU(), flushAll(), flushNonGlobal(), serialize(), and TLB().
trie
TlbEntryTrie X86ISA::TLB::trie protected
Definition at line 100 of file tlb.hh.
Referenced by demapPage(), evictLRU(), flushAll(), flushNonGlobal(), insert(), lookup(), and unserialize().
walker
Walker* X86ISA::TLB::walker protected
Definition at line 82 of file tlb.hh.
Referenced by getTableWalkerPort(), getWalker(), TLB(), and translate().
wrAccesses
Stats::Scalar X86ISA::TLB::wrAccesses protected
Definition at line 105 of file tlb.hh.
Referenced by regStats(), and translate().
wrMisses
Stats::Scalar X86ISA::TLB::wrMisses protected
Definition at line 107 of file tlb.hh.
Referenced by regStats(), and translate().
The documentation for this class was generated from the following files:
arch/x86/tlb.hh
arch/x86/tlb.cc