gem5: Stats::Formula Class Reference
Stats::Formula Class Reference
"Statistic Types"
A formula for statistics that is calculated when printed.
#include <statistics.hh>
Public Member Functions
Formula (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
Create and initialize thie formula, and register it with the database.
Formula (Group *parent, const char *name, const char *desc, const Temp &r)
const Formula & operator= (const Temp &r)
Set an unitialized Formula to the given root.
template<typename T >
const Formula & operator= (const T &v)
const Formula & operator+= (Temp r)
Add the given tree to the existing one.
const Formula & operator/= (Temp r)
Divide the existing tree by the given one.
void result (VResult &vec) const
Return the result of the Fomula in a vector.
Result total () const
Return the total Formula result.
size_type size () const
Return the number of elements in the tree.
void prepare ()
void reset ()
Formulas don't need to be reset.
bool zero () const
std::string str () const
Public Member Functions inherited from Stats::DataWrapVec< Formula, FormulaInfoProxy >
DataWrapVec (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
Formula & subname (off_type index, const std::string &name)
Set the subfield name for the given index, and marks this stat to print at the end of simulation.
Formula & subdesc (off_type index, const std::string &desc)
Set the subfield description for the given index and marks this stat to print at the end of simulation.
void prepare ()
void reset ()
Public Member Functions inherited from Stats::DataWrap< Formula, FormulaInfoProxy >
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
DataWrap & operator= (const DataWrap &)=delete
Formula & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Formula & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Formula & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Formula & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Formula & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
Formula & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Attributes
NodePtr root
The root of the tree which represents the Formula.
Friends
class Temp
Additional Inherited Members
Public Types inherited from Stats::DataWrapVec< Formula, FormulaInfoProxy >
typedef FormulaInfoProxy< Formula > Info
Public Types inherited from Stats::DataWrap< Formula, FormulaInfoProxy >
typedef FormulaInfoProxy< Formula > Info
Protected Member Functions inherited from Stats::DataWrap< Formula, FormulaInfoProxy >
Formula & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Detailed Description
A formula for statistics that is calculated when printed.
A formula is stored as a tree of Nodes that represent the equation to calculate.
See also
Stat, ScalarStat, VectorStat, Node, Temp
Definition at line 3014 of file statistics.hh.
Constructor & Destructor Documentation
Formula() [1/2]
Stats::Formula::Formula (Group * parent = nullptr, const char * name = nullptr, const char * desc = nullptr)
Create and initialize thie formula, and register it with the database.
Definition at line 418 of file statistics.cc.
Formula() [2/2]
Stats::Formula::Formula (Group * parent, const char * name, const char * desc, const Temp & r)
Definition at line 426 of file statistics.cc.
References MipsISA::r.
Member Function Documentation
operator+=()
const Formula & Stats::Formula::operator+= (Temp r)
Add the given tree to the existing one.
Parameters
r The root of the expression tree.
Returns
a reference to this formula.
Definition at line 444 of file statistics.cc.
References Stats::Temp::getNodePtr(), root, Stats::InfoAccess::setInit(), and size().
operator/=()
const Formula & Stats::Formula::operator/= (Temp r)
Divide the existing tree by the given one.
Parameters
r The root of the expression tree.
Returns
a reference to this formula.
Definition at line 458 of file statistics.cc.
References root, and size().
operator=() [1/2]
const Formula & Stats::Formula::operator= (const Temp & r)
Set an unitialized Formula to the given root.
Parameters
r The root of the expression tree.
Returns
a reference to this formula.
Definition at line 434 of file statistics.cc.
References Stats::Temp::getNodePtr(), root, Stats::InfoAccess::setInit(), and size().
operator=() [2/2]
template<typename T > const Formula& Stats::Formula::operator= (const T & v) inline
Definition at line 3039 of file statistics.hh.
References MipsISA::r, and Stats::total.
prepare()
void Stats::Formula::prepare () inline
Definition at line 3085 of file statistics.hh.
References Stats::InfoProxy< Stat, Base >::reset(), and Stats::InfoProxy< Stat, Base >::zero().
reset()
void Stats::Formula::reset ()
Formulas don't need to be reset.
Definition at line 491 of file statistics.cc.
result()
void Stats::Formula::result (VResult & vec) const
Return the result of the Fomula in a vector.
If there were no Vector components to the Formula, then the vector is size 1. If there were, like x/y with x being a vector of size 3, then the result returned will be x[0]/y, x[1]/y, x[2]/y, respectively.
Returns
The result vector.
Definition at line 469 of file statistics.cc.
References root.
Referenced by Stats::FormulaNode::result(), and zero().
size()
size_type Stats::Formula::size () const
Return the number of elements in the tree.
Definition at line 482 of file statistics.cc.
References root.
Referenced by operator+=(), operator/=(), operator=(), and Stats::FormulaNode::size().
str()
string Stats::Formula::str () const
Definition at line 507 of file statistics.cc.
References root.
Referenced by Stats::FormulaNode::str().
total()
Result Stats::Formula::total () const
Return the total Formula result.
If there is a Vector component to this Formula, then this is the result of the Formula if the formula is applied after summing all the components of the Vector. For example, if Formula is x/y where x is size 3, then total() will return (x[1]+x[2]+x[3])/y. If there is no Vector component, total() returns the same value as the first entry in the VResult val() returns.
Returns
The total of the result vector.
Definition at line 476 of file statistics.cc.
References root.
Referenced by Stats::FormulaNode::total().
zero()
bool Stats::Formula::zero () const
Definition at line 496 of file statistics.cc.
References ArmISA::i, and result().
Friends And Related Function Documentation
Temp
friend class Temp friend
Definition at line 3019 of file statistics.hh.
Member Data Documentation
root
NodePtr Stats::Formula::root protected
The root of the tree which represents the Formula.
Definition at line 3018 of file statistics.hh.
Referenced by operator+=(), operator/=(), operator=(), result(), size(), str(), and total().
The documentation for this class was generated from the following files:
base/statistics.hh
base/statistics.cc