gem5: sc_core::sc_module Class Reference
sc_core::sc_module Class Reference
#include <sc_module.hh>
Public Member Functions
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
sc_sensitive sensitive
Private Member Functions
sc_module (const sc_module &)
sc_module & operator= (const sc_module &)
Private Attributes
sc_gem5::Module * _gem5_module
Friends
class ::sc_gem5::Kernel
class ::sc_gem5::Module
Detailed Description
Definition at line 99 of file sc_module.hh.
Constructor & Destructor Documentation
~sc_module()
sc_module::~sc_module () virtual
Definition at line 124 of file sc_module.cc.
sc_module() [1/5]
sc_module::sc_module (const sc_module_name &) protected
Definition at line 268 of file sc_module.cc.
sc_module() [2/5]
sc_module::sc_module () protected
Definition at line 258 of file sc_module.cc.
References sc_core::SC_ID_INSERT_MODULE_, sc_core::sc_is_running(), SC_REPORT_ERROR, and sc_gem5::scheduler.
sc_module() [3/5]
sc_module::sc_module (const char * _name) protected
Definition at line 269 of file sc_module.cc.
References _gem5_module, sc_gem5::Module::deprecatedConstructor(), sc_core::SC_ID_BAD_SC_MODULE_CONSTRUCTOR_, and SC_REPORT_WARNING.
sc_module() [4/5]
sc_module::sc_module (const std::string & _name) protected
Definition at line 274 of file sc_module.cc.
References _gem5_module, sc_gem5::Module::deprecatedConstructor(), sc_core::SC_ID_BAD_SC_MODULE_CONSTRUCTOR_, and SC_REPORT_WARNING.
sc_module() [5/5]
sc_core::sc_module::sc_module (const sc_module &) inline private
Definition at line 259 of file sc_module.hh.
Member Function Documentation
async_reset_signal_is() [1/4]
void sc_module::async_reset_signal_is (const sc_in< bool > & port, bool val) protected
Definition at line 313 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
async_reset_signal_is() [2/4]
void sc_module::async_reset_signal_is (const sc_inout< bool > & port, bool val) protected
Definition at line 319 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
async_reset_signal_is() [3/4]
void sc_module::async_reset_signal_is (const sc_out< bool > & port, bool val) protected
Definition at line 325 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
async_reset_signal_is() [4/4]
void sc_module::async_reset_signal_is (const sc_signal_in_if< bool > & signal, bool val) protected
Definition at line 331 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
at_negedge() [1/2]
void sc_module::at_negedge (const sc_signal_in_if< bool > & s) protected
Definition at line 527 of file sc_module.cc.
References sc_core::at_negedge().
at_negedge() [2/2]
void sc_module::at_negedge (const sc_signal_in_if< sc_dt::sc_logic > & s) protected
Definition at line 533 of file sc_module.cc.
References sc_core::at_negedge().
at_posedge() [1/2]
void sc_module::at_posedge (const sc_signal_in_if< bool > & s) protected
Definition at line 515 of file sc_module.cc.
References sc_core::at_posedge().
at_posedge() [2/2]
void sc_module::at_posedge (const sc_signal_in_if< sc_dt::sc_logic > & s) protected
Definition at line 521 of file sc_module.cc.
References sc_core::at_posedge().
before_end_of_elaboration()
virtual void sc_core::sc_module::before_end_of_elaboration () inline protected virtual
Reimplemented in sc_gem5::Gem5ToTlmBridge< BITWIDTH >, and sc_gem5::TlmToGem5Bridge< BITWIDTH >.
Definition at line 250 of file sc_module.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration(), sc_gem5::Module::beforeEndOfElaboration(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::getSocket(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getSocket().
dont_initialize()
void sc_module::dont_initialize () protected
Definition at line 338 of file sc_module.cc.
References sc_gem5::Process::dontInitialize(), sc_gem5::Process::newest(), MipsISA::p, sc_gem5::Process::procKind(), sc_core::SC_CTHREAD_PROC_, sc_core::SC_ID_DONT_INITIALIZE_, and SC_REPORT_WARNING.
Referenced by sc_core::sc_event_queue::sc_event_queue(), SimpleATInitiator1::SimpleATInitiator1(), SimpleATTarget1::SimpleATTarget1(), SimpleATTarget2::SimpleATTarget2(), SimpleLTTarget1::SimpleLTTarget1(), and SimpleLTTarget_ext::SimpleLTTarget_ext().
end_module()
void sc_module::end_module () protected
Definition at line 282 of file sc_module.cc.
References _gem5_module, and sc_gem5::Module::endModule().
end_of_elaboration()
virtual void sc_core::sc_module::end_of_elaboration () inline protected virtual
Definition at line 251 of file sc_module.hh.
Referenced by sc_gem5::Module::endOfElaboration().
end_of_simulation()
virtual void sc_core::sc_module::end_of_simulation () inline protected virtual
Reimplemented in SimpleLTInitiator_ext, SimpleLTInitiator_ext, SimpleLTInitiator1_dmi, and SimpleLTInitiator2_dmi.
Definition at line 253 of file sc_module.hh.
Referenced by sc_gem5::Module::endOfSimulation().
gem5_getPort()
Port & sc_module::gem5_getPort (const std::string & if_name, int idx = -1)
Definition at line 119 of file sc_module.cc.
References fatal, and name().
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::gem5_getPort(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::gem5_getPort(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getAddrRanges(), FastModel::CortexA76::getPort(), and FastModel::CortexA76Cluster::getPort().
get_child_events()
const std::vector< sc_event * > & sc_module::get_child_events () const virtual
Reimplemented from sc_core::sc_object.
Definition at line 253 of file sc_module.cc.
Referenced by Iris::BaseCPU::BaseCPU().
get_child_objects()
const std::vector< sc_object * > & sc_module::get_child_objects () const virtual
Reimplemented from sc_core::sc_object.
Definition at line 247 of file sc_module.cc.
halt()
void sc_module::halt () protected
Definition at line 509 of file sc_module.cc.
References sc_core::halt().
kind()
virtual const char* sc_core::sc_module::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Reimplemented in sc_core::sc_event_queue.
Definition at line 111 of file sc_module.hh.
References sc_dt::operator,, and sc_dt::operator<<().
next_trigger() [1/12]
void sc_module::next_trigger () protected
Definition at line 353 of file sc_module.cc.
References sc_core::next_trigger().
Referenced by sc_core::next_trigger().
next_trigger() [2/12]
void sc_module::next_trigger (const sc_event & e) protected
Definition at line 356 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [3/12]
void sc_module::next_trigger (const sc_event_or_list & eol) protected
Definition at line 362 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [4/12]
void sc_module::next_trigger (const sc_event_and_list & eal) protected
Definition at line 368 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [5/12]
void sc_module::next_trigger (const sc_time & t) protected
Definition at line 374 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [6/12]
void sc_module::next_trigger (double d, sc_time_unit u) protected
Definition at line 380 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [7/12]
void sc_module::next_trigger (const sc_time & t, const sc_event & e) protected
Definition at line 386 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [8/12]
void sc_module::next_trigger (double d, sc_time_unit u, const sc_event & e) protected
Definition at line 392 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [9/12]
void sc_module::next_trigger (const sc_time & t, const sc_event_or_list & eol) protected
Definition at line 398 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [10/12]
void sc_module::next_trigger (double d, sc_time_unit u, const sc_event_or_list & eol) protected
Definition at line 404 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [11/12]
void sc_module::next_trigger (const sc_time & t, const sc_event_and_list & eal) protected
Definition at line 410 of file sc_module.cc.
References sc_core::next_trigger().
next_trigger() [12/12]
void sc_module::next_trigger (double d, sc_time_unit u, const sc_event_and_list & eal) protected
Definition at line 416 of file sc_module.cc.
References sc_core::next_trigger().
operator()()
void sc_module::operator() (const sc_bind_proxy & p001, const sc_bind_proxy & p002 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p003 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p004 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p005 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p006 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p007 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p008 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p009 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p010 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p011 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p012 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p013 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p014 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p015 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p016 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p017 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p018 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p019 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p020 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p021 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p022 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p023 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p024 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p025 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p026 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p027 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p028 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p029 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p030 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p031 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p032 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p033 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p034 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p035 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p036 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p037 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p038 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p039 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p040 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p041 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p042 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p043 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p044 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p045 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p046 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p047 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p048 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p049 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p050 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p051 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p052 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p053 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p054 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p055 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p056 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p057 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p058 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p059 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p060 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p061 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p062 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p063 = SC_BIND_PROXY_NIL, const sc_bind_proxy & p064 = SC_BIND_PROXY_NIL)
Definition at line 127 of file sc_module.cc.
References MipsISA::p.
operator,() [1/2]
sc_module & sc_module::operator, (sc_interface & iface)
Definition at line 233 of file sc_module.cc.
operator,() [2/2]
sc_module & sc_module::operator, (sc_port_base & pb)
Definition at line 240 of file sc_module.cc.
operator<<() [1/2]
sc_module & sc_module::operator<< (sc_interface & iface)
Definition at line 219 of file sc_module.cc.
operator<<() [2/2]
sc_module & sc_module::operator<< (sc_port_base & pb)
Definition at line 226 of file sc_module.cc.
operator=()
sc_module& sc_core::sc_module::operator= (const sc_module &) inline private
Definition at line 260 of file sc_module.hh.
References sc_core::next_trigger(), sc_core::timed_out(), and sc_core::wait().
reset_signal_is() [1/4]
void sc_module::reset_signal_is (const sc_in< bool > & port, bool val) protected
Definition at line 288 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
reset_signal_is() [2/4]
void sc_module::reset_signal_is (const sc_inout< bool > & port, bool val) protected
Definition at line 294 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
reset_signal_is() [3/4]
void sc_module::reset_signal_is (const sc_out< bool > & port, bool val) protected
Definition at line 300 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
reset_signal_is() [4/4]
void sc_module::reset_signal_is (const sc_signal_in_if< bool > & signal, bool val) protected
Definition at line 306 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::newReset().
set_stack_size()
void sc_module::set_stack_size (size_t size) protected
Definition at line 347 of file sc_module.cc.
References sc_gem5::Process::newest(), and sc_gem5::Process::setStackSize().
start_of_simulation()
virtual void sc_core::sc_module::start_of_simulation () inline protected virtual
Reimplemented in MultiSocketSimpleSwitchAT.
Definition at line 252 of file sc_module.hh.
Referenced by sc_gem5::Module::startOfSimulation().
timed_out()
bool sc_module::timed_out () protected
Definition at line 423 of file sc_module.cc.
References sc_core::timed_out().
wait() [1/13]
void sc_module::wait () protected
Definition at line 430 of file sc_module.cc.
References sc_core::wait().
Referenced by sc_core::at_negedge(), sc_core::at_posedge(), MultiSocketSimpleSwitchAT::b_transport(), ExplicitATTarget::beginResponse(), ExplicitLTTarget::myBTransport(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::ResponseThread(), SimpleLTInitiator2::run(), SimpleLTInitiator3::run(), SimpleLTInitiator1::run(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), CoreDecouplingLTInitiator::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), SimpleATInitiator2::run(), SimpleATInitiator1::run(), and sc_core::wait().
wait() [2/13]
void sc_module::wait (int i) protected
Definition at line 436 of file sc_module.cc.
References sc_core::wait().
wait() [3/13]
void sc_module::wait (const sc_event & e) protected
Definition at line 442 of file sc_module.cc.
References sc_core::wait().
wait() [4/13]
void sc_module::wait (const sc_event_or_list & eol) protected
Definition at line 448 of file sc_module.cc.
References sc_core::wait().
wait() [5/13]
void sc_module::wait (const sc_event_and_list & eal) protected
Definition at line 454 of file sc_module.cc.
References sc_core::wait().
wait() [6/13]
void sc_module::wait (const sc_time & t) protected
Definition at line 460 of file sc_module.cc.
References sc_core::wait().
wait() [7/13]
void sc_module::wait (double d, sc_time_unit u) protected
Definition at line 466 of file sc_module.cc.
References sc_core::wait().
wait() [8/13]
void sc_module::wait (const sc_time & t, const sc_event & e) protected
Definition at line 472 of file sc_module.cc.
References sc_core::wait().
wait() [9/13]
void sc_module::wait (double d, sc_time_unit u, const sc_event & e) protected
Definition at line 478 of file sc_module.cc.
References sc_core::wait().
wait() [10/13]
void sc_module::wait (const sc_time & t, const sc_event_or_list & eol) protected
Definition at line 484 of file sc_module.cc.
References sc_core::wait().
wait() [11/13]
void sc_module::wait (double d, sc_time_unit u, const sc_event_or_list & eol) protected
Definition at line 490 of file sc_module.cc.
References sc_core::wait().
wait() [12/13]
void sc_module::wait (const sc_time & t, const sc_event_and_list & eal) protected
Definition at line 496 of file sc_module.cc.
References sc_core::wait().
wait() [13/13]
void sc_module::wait (double d, sc_time_unit u, const sc_event_and_list & eal) protected
Definition at line 502 of file sc_module.cc.
References sc_core::wait().
Friends And Related Function Documentation
::sc_gem5::Kernel
friend class ::sc_gem5::Kernel friend
Definition at line 106 of file sc_module.hh.
::sc_gem5::Module
friend class ::sc_gem5::Module friend
Definition at line 107 of file sc_module.hh.
Member Data Documentation
_gem5_module
sc_gem5::Module* sc_core::sc_module::_gem5_module private
Definition at line 256 of file sc_module.hh.
Referenced by end_module(), sc_gem5::Module::fromScModule(), and sc_module().
sensitive
sc_sensitive sc_core::sc_module::sensitive protected
Definition at line 208 of file sc_module.hh.
Referenced by sc_core::sc_event_queue::sc_event_queue(), SimpleATInitiator1::SimpleATInitiator1(), SimpleATTarget1::SimpleATTarget1(), SimpleATTarget2::SimpleATTarget2(), SimpleLTTarget1::SimpleLTTarget1(), and SimpleLTTarget_ext::SimpleLTTarget_ext().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_module.hh
systemc/core/sc_module.cc