gem5: ArmISA::ITLBIASID Class Reference
ArmISA::ITLBIASID Class Reference
Instruction TLB Invalidate by ASID match.
#include <tlbi_op.hh>
Public Member Functions
ITLBIASID (ExceptionLevel _targetEL, bool _secure, uint16_t _asid)
void broadcast (ThreadContext *tc)=delete
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
uint16_t asid
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
Instruction TLB Invalidate by ASID match.
Definition at line 137 of file tlbi_op.hh.
Constructor & Destructor Documentation
ITLBIASID()
ArmISA::ITLBIASID::ITLBIASID (ExceptionLevel _targetEL, bool _secure, uint16_t _asid) inline
Definition at line 140 of file tlbi_op.hh.
References ArmISA::TLBIOp::broadcast(), and ArmISA::TLBIOp::operator()().
Member Function Documentation
broadcast()
void ArmISA::ITLBIASID::broadcast (ThreadContext * tc) delete
operator()()
void ArmISA::ITLBIASID::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 88 of file tlbi_op.cc.
References ArmISA::asid, ArmISA::TLB::flushAsid(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
Member Data Documentation
asid
uint16_t ArmISA::ITLBIASID::asid protected
Definition at line 149 of file tlbi_op.hh.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc