gem5: BufferArg Class Reference
BufferArg Class Reference
BufferArg represents an untyped buffer in target user space that is passed by reference to an (emulated) system call.
#include <syscall_emul_buf.hh>
Public Member Functions
BufferArg (Addr _addr, int _size)
Allocate a buffer of size 'size' representing the memory at target address 'addr'.
void * bufferPtr ()
Return a pointer to the internal simulator-space buffer.
Public Member Functions inherited from BaseBufferArg
BaseBufferArg (Addr _addr, int _size)
Allocate a buffer of size 'size' representing the memory at target address 'addr'.
~BaseBufferArg ()
bool copyIn (PortProxy &memproxy)
copy data into simulator space (read from target memory)
bool copyOut (PortProxy &memproxy)
copy data out of simulator space (write to target memory)
Additional Inherited Members
Protected Attributes inherited from BaseBufferArg
const Addr addr
address of buffer in target address space
const int size
buffer size
uint8_t *const bufPtr
pointer to buffer in simulator space
Detailed Description
BufferArg represents an untyped buffer in target user space that is passed by reference to an (emulated) system call.
Definition at line 105 of file syscall_emul_buf.hh.
Constructor & Destructor Documentation
BufferArg()
BufferArg::BufferArg (Addr _addr, int _size) inline
Allocate a buffer of size 'size' representing the memory at target address 'addr'.
Definition at line 112 of file syscall_emul_buf.hh.
Member Function Documentation
bufferPtr()
void* BufferArg::bufferPtr () inline
Return a pointer to the internal simulator-space buffer.
Definition at line 117 of file syscall_emul_buf.hh.
References BaseBufferArg::bufPtr.
Referenced by _llseekFunc(), acceptFunc(), bindFunc(), cloneFunc(), connectFunc(), execveFunc(), exitFutexWake(), futexFunc(), getcwdFunc(), gethostnameFunc(), getpeernameFunc(), SparcISA::getresuidFunc(), getsocknameFunc(), getsockoptFunc(), ClDriver::ioctl(), ioctlFunc(), pipeImpl(), pollFunc(), pwrite64Func(), readFunc(), readlinkFunc(), recvfromFunc(), recvmsgFunc(), rmdirFunc(), sendmsgFunc(), sendtoFunc(), setsockoptFunc(), socketpairFunc(), sysctlFunc(), wait4Func(), and writeFunc().
The documentation for this class was generated from the following file:
sim/syscall_emul_buf.hh