gem5: IPACache Class Reference
IPACache Class Reference
#include <smmu_v3_caches.hh>
Classes
struct Entry
Public Member Functions
IPACache (unsigned numEntries, unsigned _associativity, const std::string &policy)
virtual ~IPACache ()
const Entry * lookup (Addr ipa, uint16_t vmid, bool updStats=true)
void store (const Entry &incoming)
void invalidateIPA (Addr ipa, uint16_t vmid)
void invalidateIPAA (Addr ipa)
void invalidateVMID (uint16_t vmid)
void invalidateAll ()
Public Member Functions inherited from SMMUv3BaseCache
SMMUv3BaseCache (const std::string &policy_name, uint32_t seed)
virtual ~SMMUv3BaseCache ()
virtual void regStats (const std::string &name)
Private Types
typedef std::vector< Entry > Set
Private Member Functions
size_t pickSetIdx (Addr ipa, uint16_t vmid) const
size_t pickEntryIdxToReplace (const Set &set)
Private Attributes
std::vector< Set > sets
size_t associativity
Additional Inherited Members
Static Protected Member Functions inherited from SMMUv3BaseCache
static int decodePolicyName (const std::string &policy_name)
Protected Attributes inherited from SMMUv3BaseCache
int replacementPolicy
size_t nextToReplace
Random random
uint32_t useStamp
Stats::Formula averageLookups
Stats::Scalar totalLookups
Stats::Formula averageMisses
Stats::Scalar totalMisses
Stats::Formula averageUpdates
Stats::Scalar totalUpdates
Stats::Formula averageHitRate
Stats::Scalar insertions
Detailed Description
Definition at line 196 of file smmu_v3_caches.hh.
Member Typedef Documentation
Set
typedef std::vector<Entry> IPACache::Set private
Definition at line 227 of file smmu_v3_caches.hh.
Constructor & Destructor Documentation
IPACache()
IPACache::IPACache (unsigned numEntries, unsigned _associativity, const std::string & policy)
Definition at line 628 of file smmu_v3_caches.cc.
References associativity, ArmISA::e, fatal, sets, and IPACache::Entry::valid.
~IPACache()
virtual IPACache::~IPACache () inline virtual
Definition at line 216 of file smmu_v3_caches.hh.
Member Function Documentation
invalidateAll()
void IPACache::invalidateAll ()
Definition at line 754 of file smmu_v3_caches.cc.
References ArmISA::i, ArmISA::s, and sets.
Referenced by SMMUv3::processCommand().
invalidateIPA()
void IPACache::invalidateIPA (Addr ipa, uint16_t vmid)
Definition at line 711 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, IPACache::Entry::ipa, IPACache::Entry::ipaMask, pickSetIdx(), sets, IPACache::Entry::valid, and IPACache::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateIPAA()
void IPACache::invalidateIPAA (Addr ipa)
Definition at line 724 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, IPACache::Entry::ipa, IPACache::Entry::ipaMask, ArmISA::s, sets, and IPACache::Entry::valid.
invalidateVMID()
void IPACache::invalidateVMID (uint16_t vmid)
Definition at line 739 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ArmISA::s, sets, IPACache::Entry::valid, and IPACache::Entry::vmid.
Referenced by SMMUv3::processCommand().
lookup()
const IPACache::Entry * IPACache::lookup (Addr ipa, uint16_t vmid, bool updStats = true)
Definition at line 658 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, IPACache::Entry::ipa, IPACache::Entry::ipaMask, IPACache::Entry::lastUsed, panic, pickSetIdx(), sets, SMMUv3BaseCache::totalLookups, SMMUv3BaseCache::totalMisses, SMMUv3BaseCache::useStamp, IPACache::Entry::valid, and IPACache::Entry::vmid.
Referenced by store(), and SMMUTranslationProcess::translateStage2().
pickEntryIdxToReplace()
size_t IPACache::pickEntryIdxToReplace (const Set & set) private
Definition at line 771 of file smmu_v3_caches.cc.
References associativity, ArmISA::i, SMMUv3BaseCache::insertions, SMMUv3BaseCache::nextToReplace, panic, SMMUv3BaseCache::random, Random::random(), SMMUv3BaseCache::replacementPolicy, SMMU_CACHE_REPL_LRU, SMMU_CACHE_REPL_RANDOM, and SMMU_CACHE_REPL_ROUND_ROBIN.
Referenced by store().
pickSetIdx()
size_t IPACache::pickSetIdx (Addr ipa, uint16_t vmid) const private
Definition at line 765 of file smmu_v3_caches.cc.
References sets.
Referenced by invalidateIPA(), lookup(), and store().
store()
void IPACache::store (const Entry & incoming)
Definition at line 691 of file smmu_v3_caches.cc.
References IPACache::Entry::ipa, IPACache::Entry::lastUsed, lookup(), panic, pickEntryIdxToReplace(), pickSetIdx(), sets, SMMUv3BaseCache::totalUpdates, IPACache::Entry::valid, and IPACache::Entry::vmid.
Referenced by SMMUTranslationProcess::translateStage2().
Member Data Documentation
associativity
size_t IPACache::associativity private
Definition at line 230 of file smmu_v3_caches.hh.
Referenced by IPACache(), and pickEntryIdxToReplace().
sets
std::vector<Set> IPACache::sets private
Definition at line 228 of file smmu_v3_caches.hh.
Referenced by invalidateAll(), invalidateIPA(), invalidateIPAA(), invalidateVMID(), IPACache(), lookup(), pickSetIdx(), and store().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_caches.hh
dev/arm/smmu_v3_caches.cc