gem5: tlm_utils::multi_init_base_if< TYPES > Class Template Reference
tlm_utils::multi_init_base_if< TYPES > Class Template Reference abstract
#include <multi_socket_bases.h>
Public Member Functions
virtual std::vector< callback_binder_bw< TYPES > * > & get_binders ()=0
virtual std::vector< tlm::tlm_fw_transport_if< TYPES > * > & get_sockets ()=0
Protected Member Functions
virtual ~multi_init_base_if ()
Detailed Description
template<typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::multi_init_base_if< TYPES >
Definition at line 351 of file multi_socket_bases.h.
Constructor & Destructor Documentation
~multi_init_base_if()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual tlm_utils::multi_init_base_if< TYPES >::~multi_init_base_if () inline protected virtual
Definition at line 361 of file multi_socket_bases.h.
Member Function Documentation
get_binders()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual std::vector<callback_binder_bw<TYPES> *>& tlm_utils::multi_init_base_if< TYPES >::get_binders () pure virtual
Implemented in tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::before_end_of_elaboration().
get_sockets()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual std::vector<tlm::tlm_fw_transport_if<TYPES> *>& tlm_utils::multi_init_base_if< TYPES >::get_sockets () pure virtual
Implemented in tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::before_end_of_elaboration(), and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::size().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/multi_socket_bases.h