gem5: sc_dt::sc_fxnum_fast_observer Class Reference
sc_dt::sc_fxnum_fast_observer Class Reference
#include <sc_fxnum_observer.hh>
Public Member Functions
virtual void construct (const sc_fxnum_fast &)
virtual void destruct (const sc_fxnum_fast &)
virtual void read (const sc_fxnum_fast &)
virtual void write (const sc_fxnum_fast &)
Static Public Attributes
static sc_fxnum_fast_observer *(* default_observer)()
Protected Member Functions
sc_fxnum_fast_observer ()
virtual ~sc_fxnum_fast_observer ()
Detailed Description
Definition at line 132 of file sc_fxnum_observer.hh.
Constructor & Destructor Documentation
sc_fxnum_fast_observer()
sc_dt::sc_fxnum_fast_observer::sc_fxnum_fast_observer () inline protected
Definition at line 135 of file sc_fxnum_observer.hh.
~sc_fxnum_fast_observer()
virtual sc_dt::sc_fxnum_fast_observer::~sc_fxnum_fast_observer () inline protected virtual
Definition at line 136 of file sc_fxnum_observer.hh.
References sc_dt::sc_fxnum_observer::construct(), sc_dt::sc_fxnum_observer::destruct(), sc_dt::sc_fxnum_observer::read(), and sc_dt::sc_fxnum_observer::write().
Member Function Documentation
construct()
void sc_dt::sc_fxnum_fast_observer::construct (const sc_fxnum_fast &) inline virtual
Definition at line 168 of file sc_fxnum_observer.hh.
destruct()
void sc_dt::sc_fxnum_fast_observer::destruct (const sc_fxnum_fast &) inline virtual
Definition at line 169 of file sc_fxnum_observer.hh.
read()
void sc_dt::sc_fxnum_fast_observer::read (const sc_fxnum_fast &) inline virtual
Definition at line 170 of file sc_fxnum_observer.hh.
write()
void sc_dt::sc_fxnum_fast_observer::write (const sc_fxnum_fast &) inline virtual
Definition at line 171 of file sc_fxnum_observer.hh.
Member Data Documentation
default_observer
sc_fxnum_fast_observer *(* sc_dt::sc_fxnum_fast_observer::default_observer)()=0 static
Definition at line 144 of file sc_fxnum_observer.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum_observer.hh
systemc/dt/fx/sc_fxnum_observer.cc