gem5: sc_core::sc_event_and_expr Class Reference
sc_core::sc_event_and_expr Class Reference
#include <sc_event.hh>
Public Member Functions
sc_event_and_expr (sc_event_and_expr const &e)
operator const sc_event_and_list & () const
void insert (sc_event const &e) const
void insert (sc_event_and_list const &eal) const
~sc_event_and_expr ()
Private Member Functions
sc_event_and_expr ()
Private Attributes
sc_event_and_list * list
Friends
class sc_event_and_list
class sc_event
Detailed Description
Definition at line 127 of file sc_event.hh.
Constructor & Destructor Documentation
sc_event_and_expr() [1/2]
sc_core::sc_event_and_expr::sc_event_and_expr (sc_event_and_expr const & e)
Definition at line 213 of file sc_event.cc.
References list.
~sc_event_and_expr()
sc_core::sc_event_and_expr::~sc_event_and_expr ()
Definition at line 240 of file sc_event.cc.
References list.
sc_event_and_expr() [2/2]
sc_core::sc_event_and_expr::sc_event_and_expr () private
Definition at line 242 of file sc_event.cc.
Member Function Documentation
insert() [1/2]
void sc_core::sc_event_and_expr::insert (sc_event const & e) const
Definition at line 227 of file sc_event.cc.
References sc_core::sc_event_and_list::insert(), and list.
Referenced by sc_core::sc_event::notify_delayed(), sc_core::operator&(), and sc_core::sc_event_and_list::swap().
insert() [2/2]
void sc_core::sc_event_and_expr::insert (sc_event_and_list const & eal) const
Definition at line 234 of file sc_event.cc.
References sc_core::sc_event_and_list::insert(), and list.
operator const sc_event_and_list &()
sc_core::sc_event_and_expr::operator const sc_event_and_list & () const
Definition at line 219 of file sc_event.cc.
References list.
Friends And Related Function Documentation
sc_event
friend class sc_event friend
Definition at line 140 of file sc_event.hh.
sc_event_and_list
friend class sc_event_and_list friend
Definition at line 139 of file sc_event.hh.
Member Data Documentation
list
sc_event_and_list* sc_core::sc_event_and_expr::list mutable private
Definition at line 143 of file sc_event.hh.
Referenced by insert(), operator const sc_event_and_list &(), sc_event_and_expr(), and ~sc_event_and_expr().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_event.hh
systemc/core/sc_event.cc