gem5: ItsTranslation Class Reference
ItsTranslation Class Reference
An ItsTranslation is created whenever a peripheral writes a message in GITS_TRANSLATER (MSI).
#include <gic_v3_its.hh>
Public Member Functions
ItsTranslation (Gicv3Its &_its)
~ItsTranslation ()
Public Member Functions inherited from ItsProcess
ItsProcess (Gicv3Its &_its)
virtual ~ItsProcess ()
const std::string name () const
Returns the Gicv3Its name.
ItsAction run (PacketPtr pkt)
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Protected Member Functions
void main (Yield &yield) override
std::pair< uint32_t, Gicv3Redistributor * > translateLPI (Yield &yield, uint32_t device_id, uint32_t event_id)
Protected Member Functions inherited from ItsProcess
void reinit ()
void writeDeviceTable (Yield &yield, uint32_t device_id, DTE dte)
void writeIrqTranslationTable (Yield &yield, const Addr itt_base, uint32_t event_id, ITTE itte)
void writeIrqCollectionTable (Yield &yield, uint32_t collection_id, CTE cte)
uint64_t readDeviceTable (Yield &yield, uint32_t device_id)
uint64_t readIrqTranslationTable (Yield &yield, const Addr itt_base, uint32_t event_id)
uint64_t readIrqCollectionTable (Yield &yield, uint32_t collection_id)
void doRead (Yield &yield, Addr addr, void *ptr, size_t size)
void doWrite (Yield &yield, Addr addr, void *ptr, size_t size)
void terminate (Yield &yield)
Additional Inherited Members
Public Types inherited from ItsProcess
using DTE = Gicv3Its::DTE
using ITTE = Gicv3Its::ITTE
using CTE = Gicv3Its::CTE
using Coroutine = m5::Coroutine< PacketPtr, ItsAction >
using Yield = Coroutine::CallerType
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Protected Attributes inherited from ItsProcess
Gicv3Its & its
Detailed Description
An ItsTranslation is created whenever a peripheral writes a message in GITS_TRANSLATER (MSI).
In this case main will simply do the table walks until it gets a redistributor and an INTID. It will then raise the LPI interrupt to the target redistributor.
Definition at line 401 of file gic_v3_its.hh.
Constructor & Destructor Documentation
ItsTranslation()
ItsTranslation::ItsTranslation (Gicv3Its & _its)
Definition at line 218 of file gic_v3_its.cc.
References ItsProcess::its, Gicv3Its::pendingTranslations, and ItsProcess::reinit().
~ItsTranslation()
ItsTranslation::~ItsTranslation ()
Definition at line 226 of file gic_v3_its.cc.
References ItsProcess::its, Gicv3Its::pendingCommands, and Gicv3Its::pendingTranslations.
Member Function Documentation
main()
void ItsTranslation::main (Yield & yield) override protected virtual
Implements ItsProcess.
Definition at line 235 of file gic_v3_its.cc.
References m5::Coroutine< Arg, Ret >::CallerType::get(), Packet::getLE(), Gicv3Its::gitsTranslater, ItsProcess::its, Packet::req, Gicv3Redistributor::setClrLPI(), ItsProcess::terminate(), and translateLPI().
translateLPI()
std::pair< uint32_t, Gicv3Redistributor * > ItsTranslation::translateLPI (Yield & yield, uint32_t device_id, uint32_t event_id) protected
Definition at line 259 of file gic_v3_its.cc.
References ItsCommand::clear(), ItsCommand::cmdDispatcher, Gicv3Its::collectionOutOfRange(), COMMAND, Gicv3Its::deviceOutOfRange(), ItsCommand::discard(), ItsCommand::doInt(), Gicv3Its::getRedistributor(), Gicv3Its::idOutOfRange(), ItsCommand::inv(), ItsCommand::invall(), ItsProcess::its, ItsCommand::mapc(), ItsCommand::mapd(), ItsCommand::mapi(), ItsCommand::mapti(), ItsCommand::movall(), ItsCommand::movi(), ItsProcess::readDeviceTable(), ItsProcess::readIrqCollectionTable(), ItsProcess::readIrqTranslationTable(), ItsCommand::sync(), ItsProcess::terminate(), ItsCommand::vinvall(), ItsCommand::vmapi(), ItsCommand::vmapp(), ItsCommand::vmapti(), ItsCommand::vmovi(), ItsCommand::vmovp(), and ItsCommand::vsync().
Referenced by main().
The documentation for this class was generated from the following files:
dev/arm/gic_v3_its.hh
dev/arm/gic_v3_its.cc