gem5: TempCacheBlk Class Reference
TempCacheBlk Class Reference final
Special instance of CacheBlk for use with tempBlk that deals with its block address regeneration.
#include <cache_blk.hh>
Public Member Functions
TempCacheBlk (unsigned size)
Creates a temporary cache block, with its own storage.
TempCacheBlk (const TempCacheBlk &)=delete
TempCacheBlk & operator= (const TempCacheBlk &)=delete
~TempCacheBlk ()
void invalidate () override
Invalidate the block and clear all state.
void insert (const Addr addr, const bool is_secure, const int src_master_ID=0, const uint32_t task_ID=0) override
Set member variables when a block insertion occurs.
Addr getAddr () const
Get block's address.
Public Member Functions inherited from CacheBlk
CacheBlk ()
CacheBlk (const CacheBlk &)=delete
CacheBlk & operator= (const CacheBlk &)=delete
virtual ~CacheBlk ()
bool isWritable () const
Checks the write permissions of this block.
bool isReadable () const
Checks the read permissions of this block.
bool isValid () const
Checks that a block is valid.
bool isDirty () const
Check to see if a block has been written.
bool wasPrefetched () const
Check if this block was the result of a hardware prefetch, yet to be touched.
bool isSecure () const
Check if this block holds data from the secure memory space.
virtual void setValid ()
Set valid bit.
virtual void setSecure ()
Set secure bit.
Tick getWhenReady () const
Get tick at which block's data will be available for access.
void setWhenReady (const Tick tick)
Set tick at which block's data will be available for access.
void trackLoadLocked (PacketPtr pkt)
Track the fact that a local locked was issued to the block.
void clearLoadLocks (const RequestPtr &req)
Clear the any load lock that intersect the request, and is from a different context.
virtual std::string print () const
Pretty-print tag, set and way, and interpret state bits to readable form including mapping to a MOESI state.
bool checkWrite (PacketPtr pkt)
Handle interaction of load-locked operations and stores.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Private Attributes
Addr _addr
Copy of the block's address, used to regenerate tempBlock's address.
Additional Inherited Members
Public Types inherited from CacheBlk
typedef unsigned State
block state: OR of CacheBlkStatusBit
Public Attributes inherited from CacheBlk
uint32_t task_id
Task Id associated with this block.
Addr tag
Data block tag value.
uint8_t * data
Contains a copy of the data in this block for easy access.
State status
The current status of this block.
Tick whenReady
Which curTick() will this block be accessible.
unsigned refCount
Number of references to this block since it was brought in.
int srcMasterId
holds the source requestor ID for this block.
Tick tickInserted
Tick on which the block was inserted in the cache.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Protected Attributes inherited from CacheBlk
std::list< Lock > lockList
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
Special instance of CacheBlk for use with tempBlk that deals with its block address regeneration.
See also
Cache
Definition at line 443 of file cache_blk.hh.
Constructor & Destructor Documentation
TempCacheBlk() [1/2]
TempCacheBlk::TempCacheBlk (unsigned size) inline
Creates a temporary cache block, with its own storage.
Parameters
size The size (in bytes) of this cache block.
Definition at line 456 of file cache_blk.hh.
References CacheBlk::data, and CacheBlk::operator=().
TempCacheBlk() [2/2]
TempCacheBlk::TempCacheBlk (const TempCacheBlk &) delete
~TempCacheBlk()
TempCacheBlk::~TempCacheBlk () inline
Definition at line 462 of file cache_blk.hh.
References CacheBlk::data.
Member Function Documentation
getAddr()
Addr TempCacheBlk::getAddr () const inline
Get block's address.
Returns
addr Address value.
Definition at line 496 of file cache_blk.hh.
Referenced by BaseCache::regenerateBlkAddr().
insert()
void TempCacheBlk::insert (const Addr tag, const bool is_secure, const int src_master_ID = 0, const uint32_t task_ID = 0) inline override virtual
Set member variables when a block insertion occurs.
Resets reference count to 1 (the insertion counts as a reference), and touch block if it hadn't been touched previously. Sets the insertion tick to the current tick. Marks the block valid.
Parameters
tag Block address tag.
is_secure Whether the block is in secure space or not.
src_master_ID The source requestor ID.
task_ID The new task ID.
Reimplemented from CacheBlk.
Definition at line 473 of file cache_blk.hh.
References addr, CacheBlk::setSecure(), CacheBlk::setValid(), and CacheBlk::status.
Referenced by BaseCache::handleFill().
invalidate()
void TempCacheBlk::invalidate () inline override virtual
Invalidate the block and clear all state.
Reimplemented from CacheBlk.
Definition at line 467 of file cache_blk.hh.
References CacheBlk::invalidate(), and MaxAddr.
Referenced by BaseCache::invalidateBlock().
operator=()
TempCacheBlk& TempCacheBlk::operator= (const TempCacheBlk &) delete
Member Data Documentation
_addr
Addr TempCacheBlk::_addr private
Copy of the block's address, used to regenerate tempBlock's address.
Definition at line 449 of file cache_blk.hh.
The documentation for this class was generated from the following file:
mem/cache/cache_blk.hh