gem5: FileFDEntry Class Reference
FileFDEntry Class Reference
Holds file descriptors for host-backed files; host-backed files are files which were opened on the physical machine where the simulation is running (probably the thing on/under your desk).
#include <fd_entry.hh>
Public Member Functions
FileFDEntry (int sim_fd, int flags, std::string const &file_name, uint64_t file_offset, bool close_on_exec=false)
FileFDEntry (FileFDEntry const &reg, bool close_on_exec=false)
std::shared_ptr< FDEntry > clone () const override
std::string const & getFileName () const
uint64_t getFileOffset () const
void setFileName (std::string const &file_name)
void setFileOffset (uint64_t f_off)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from HBFDEntry
HBFDEntry (int flags, int sim_fd, bool close_on_exec=false)
HBFDEntry (HBFDEntry const &reg, bool close_on_exec=false)
int getFlags () const
int getSimFD () const
void setFlags (int flags)
void setSimFD (int sim_fd)
Public Member Functions inherited from FDEntry
FDEntry (bool close_on_exec=false)
bool getCOE () const
void setCOE (bool close_on_exec)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Attributes
std::string _fileName
uint64_t _fileOffset
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from HBFDEntry
int _flags
int _simFD
Protected Attributes inherited from FDEntry
bool _closeOnExec
Detailed Description
Holds file descriptors for host-backed files; host-backed files are files which were opened on the physical machine where the simulation is running (probably the thing on/under your desk).
All regular files are redirected to make it appear that the file descriptor assignment starts at file descriptor '3' (not including stdin, stdout, stderr) and then grows upward.
Definition at line 112 of file fd_entry.hh.
Constructor & Destructor Documentation
FileFDEntry() [1/2]
FileFDEntry::FileFDEntry (int sim_fd, int flags, std::string const & file_name, uint64_t file_offset, bool close_on_exec = false) inline
Definition at line 115 of file fd_entry.hh.
FileFDEntry() [2/2]
FileFDEntry::FileFDEntry (FileFDEntry const & reg, bool close_on_exec = false) inline
Definition at line 121 of file fd_entry.hh.
Member Function Documentation
clone()
std::shared_ptr<FDEntry> FileFDEntry::clone () const inline override virtual
Reimplemented from HBFDEntry.
Definition at line 127 of file fd_entry.hh.
getFileName()
std::string const& FileFDEntry::getFileName () const inline
Definition at line 132 of file fd_entry.hh.
Referenced by openImpl().
getFileOffset()
uint64_t FileFDEntry::getFileOffset () const inline
Definition at line 133 of file fd_entry.hh.
serialize()
void FileFDEntry::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from FDEntry.
Definition at line 53 of file fd_entry.cc.
References FDEntry::_closeOnExec, and SERIALIZE_SCALAR.
setFileName()
void FileFDEntry::setFileName (std::string const & file_name) inline
Definition at line 135 of file fd_entry.hh.
setFileOffset()
void FileFDEntry::setFileOffset (uint64_t f_off) inline
Definition at line 136 of file fd_entry.hh.
References FDEntry::serialize(), and FDEntry::unserialize().
unserialize()
void FileFDEntry::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from FDEntry.
Definition at line 62 of file fd_entry.cc.
References FDEntry::_closeOnExec, and UNSERIALIZE_SCALAR.
Member Data Documentation
_fileName
std::string FileFDEntry::_fileName private
Definition at line 142 of file fd_entry.hh.
_fileOffset
uint64_t FileFDEntry::_fileOffset private
Definition at line 143 of file fd_entry.hh.
The documentation for this class was generated from the following files:
sim/fd_entry.hh
sim/fd_entry.cc