gem5: sc_core::sc_int_part_if Class Reference
sc_core::sc_int_part_if Class Reference
#include <scx_signal_int.h>
Public Member Functions
virtual sc_dt::sc_int_base * part_read_target ()
virtual sc_dt::uint64 read_part (int left, int right) const
virtual sc_int_sigref & select_part (int left, int right)
virtual void write_part (sc_dt::uint64 v, int left, int right)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_int_part_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_int_part_if (const sc_int_part_if &)
sc_int_part_if & operator= (const sc_int_part_if &)
Detailed Description
Definition at line 163 of file scx_signal_int.h.
Constructor & Destructor Documentation
sc_int_part_if() [1/2]
sc_core::sc_int_part_if::sc_int_part_if () inline protected
Definition at line 166 of file scx_signal_int.h.
References operator=(), part_read_target(), read_part(), select_part(), ArmISA::v, and write_part().
sc_int_part_if() [2/2]
sc_core::sc_int_part_if::sc_int_part_if (const sc_int_part_if &) private
Member Function Documentation
operator=()
sc_int_part_if& sc_core::sc_int_part_if::operator= (const sc_int_part_if &) private
Referenced by sc_int_part_if(), sc_core::sc_signal_in_if< sc_dt::sc_int< W > >::sc_signal_in_if(), and sc_core::sc_int_sigref::~sc_int_sigref().
part_read_target()
sc_dt::sc_int_base * sc_core::sc_int_part_if::part_read_target () virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 1557 of file scx_signal_int.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_core::sc_int_sigref::initialize(), and sc_int_part_if().
read_part()
sc_dt::uint64 sc_core::sc_int_part_if::read_part (int left, int right) const virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 1562 of file scx_signal_int.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_int_part_if().
select_part()
sc_int_sigref & sc_core::sc_int_part_if::select_part (int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 1567 of file scx_signal_int.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_int_part_if().
write_part()
void sc_core::sc_int_part_if::write_part (sc_dt::uint64 v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 1572 of file scx_signal_int.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_int_part_if().
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_int.h