gem5: sc_dt::sc_int< W > Class Template Reference
sc_dt::sc_int< W > Class Template Reference
#include <sc_int.hh>
Public Member Functions
sc_int ()
sc_int (int_type v)
sc_int (const sc_int< W > &a)
sc_int (const sc_int_base &a)
sc_int (const sc_int_subref_r &a)
template<class T >
sc_int (const sc_generic_base< T > &a)
sc_int (const sc_signed &a)
sc_int (const sc_unsigned &a)
sc_int (const sc_fxval &a)
sc_int (const sc_fxval_fast &a)
sc_int (const sc_fxnum &a)
sc_int (const sc_fxnum_fast &a)
sc_int (const sc_bv_base &a)
sc_int (const sc_lv_base &a)
sc_int (const char *a)
sc_int (unsigned long a)
sc_int (long a)
sc_int (unsigned int a)
sc_int (int a)
sc_int (uint64 a)
sc_int (double a)
sc_int< W > & operator= (int_type v)
sc_int< W > & operator= (const sc_int_base &a)
sc_int< W > & operator= (const sc_int_subref_r &a)
sc_int< W > & operator= (const sc_int< W > &a)
template<class T >
sc_int< W > & operator= (const sc_generic_base< T > &a)
sc_int< W > & operator= (const sc_signed &a)
sc_int< W > & operator= (const sc_unsigned &a)
sc_int< W > & operator= (const sc_fxval &a)
sc_int< W > & operator= (const sc_fxval_fast &a)
sc_int< W > & operator= (const sc_fxnum &a)
sc_int< W > & operator= (const sc_fxnum_fast &a)
sc_int< W > & operator= (const sc_bv_base &a)
sc_int< W > & operator= (const sc_lv_base &a)
sc_int< W > & operator= (const char *a)
sc_int< W > & operator= (unsigned long a)
sc_int< W > & operator= (long a)
sc_int< W > & operator= (unsigned int a)
sc_int< W > & operator= (int a)
sc_int< W > & operator= (uint64 a)
sc_int< W > & operator= (double a)
sc_int< W > & operator+= (int_type v)
sc_int< W > & operator-= (int_type v)
sc_int< W > & operator*= (int_type v)
sc_int< W > & operator/= (int_type v)
sc_int< W > & operator%= (int_type v)
sc_int< W > & operator&= (int_type v)
sc_int< W > & operator|= (int_type v)
sc_int< W > & operator^= (int_type v)
sc_int< W > & operator<<= (int_type v)
sc_int< W > & operator>>= (int_type v)
sc_int< W > & operator++ ()
const sc_int< W > operator++ (int)
sc_int< W > & operator-- ()
const sc_int< W > operator-- (int)
Public Member Functions inherited from sc_dt::sc_int_base
sc_int_base (int w=sc_length_param().len())
sc_int_base (int_type v, int w)
sc_int_base (const sc_int_base &a)
sc_int_base (const sc_int_subref_r &a)
template<class T >
sc_int_base (const sc_generic_base< T > &a)
sc_int_base (const sc_signed &a)
sc_int_base (const sc_unsigned &a)
sc_int_base (const sc_bv_base &v)
sc_int_base (const sc_lv_base &v)
sc_int_base (const sc_uint_subref_r &v)
sc_int_base (const sc_signed_subref_r &v)
sc_int_base (const sc_unsigned_subref_r &v)
virtual ~sc_int_base ()
sc_int_base & operator= (int_type v)
sc_int_base & operator= (const sc_int_base &a)
sc_int_base & operator= (const sc_int_subref_r &a)
template<class T >
sc_int_base & operator= (const sc_generic_base< T > &a)
sc_int_base & operator= (const sc_signed &a)
sc_int_base & operator= (const sc_unsigned &a)
sc_int_base & operator= (const sc_fxval &a)
sc_int_base & operator= (const sc_fxval_fast &a)
sc_int_base & operator= (const sc_fxnum &a)
sc_int_base & operator= (const sc_fxnum_fast &a)
sc_int_base & operator= (const sc_bv_base &a)
sc_int_base & operator= (const sc_lv_base &a)
sc_int_base & operator= (const char *a)
sc_int_base & operator= (unsigned long a)
sc_int_base & operator= (long a)
sc_int_base & operator= (unsigned int a)
sc_int_base & operator= (int a)
sc_int_base & operator= (uint64 a)
sc_int_base & operator= (double a)
sc_int_base & operator+= (int_type v)
sc_int_base & operator-= (int_type v)
sc_int_base & operator*= (int_type v)
sc_int_base & operator/= (int_type v)
sc_int_base & operator%= (int_type v)
sc_int_base & operator&= (int_type v)
sc_int_base & operator|= (int_type v)
sc_int_base & operator^= (int_type v)
sc_int_base & operator<<= (int_type v)
sc_int_base & operator>>= (int_type v)
sc_int_base & operator++ ()
const sc_int_base operator++ (int)
sc_int_base & operator-- ()
const sc_int_base operator-- (int)
sc_int_bitref & operator[] (int i)
const sc_int_bitref_r & operator[] (int i) const
sc_int_bitref & bit (int i)
const sc_int_bitref_r & bit (int i) const
sc_int_subref & operator() (int left, int right)
const sc_int_subref_r & operator() (int left, int right) const
sc_int_subref & range (int left, int right)
const sc_int_subref_r & range (int left, int right) const
bool test (int i) const
void set (int i)
void set (int i, bool v)
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator int_type () const
int_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
long long_low () const
long long_high () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_int_base
int_type m_val
int m_len
int m_ulen
Detailed Description
template<int W>
class sc_dt::sc_int< W >
Definition at line 72 of file sc_int.hh.
Constructor & Destructor Documentation
sc_int() [1/21]
template<int W> sc_dt::sc_int< W >::sc_int () inline
Definition at line 89 of file sc_int.hh.
sc_int() [2/21]
template<int W> sc_dt::sc_int< W >::sc_int (int_type v) inline
Definition at line 90 of file sc_int.hh.
sc_int() [3/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_int< W > & a) inline
Definition at line 91 of file sc_int.hh.
sc_int() [4/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_int_base & a) inline
Definition at line 93 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [5/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_int_subref_r & a) inline
Definition at line 97 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [6/21]
template<int W> template<class T > sc_dt::sc_int< W >::sc_int (const sc_generic_base< T > & a) inline
Definition at line 102 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [7/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_signed & a) inline
Definition at line 106 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [8/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_unsigned & a) inline
Definition at line 110 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [9/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_fxval & a) inline explicit
Definition at line 114 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [10/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_fxval_fast & a) inline explicit
Definition at line 118 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [11/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_fxnum & a) inline explicit
Definition at line 122 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [12/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_fxnum_fast & a) inline explicit
Definition at line 126 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [13/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_bv_base & a) inline
Definition at line 130 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [14/21]
template<int W> sc_dt::sc_int< W >::sc_int (const sc_lv_base & a) inline
Definition at line 134 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [15/21]
template<int W> sc_dt::sc_int< W >::sc_int (const char * a) inline
Definition at line 138 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [16/21]
template<int W> sc_dt::sc_int< W >::sc_int (unsigned long a) inline
Definition at line 142 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [17/21]
template<int W> sc_dt::sc_int< W >::sc_int (long a) inline
Definition at line 146 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [18/21]
template<int W> sc_dt::sc_int< W >::sc_int (unsigned int a) inline
Definition at line 150 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [19/21]
template<int W> sc_dt::sc_int< W >::sc_int (int a) inline
Definition at line 154 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [20/21]
template<int W> sc_dt::sc_int< W >::sc_int (uint64 a) inline
Definition at line 158 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
sc_int() [21/21]
template<int W> sc_dt::sc_int< W >::sc_int (double a) inline
Definition at line 162 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
Member Function Documentation
operator%=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator%= (int_type v) inline
Definition at line 315 of file sc_int.hh.
References sc_dt::sc_int_base::operator%=().
operator&=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator &= (int_type v) inline
Definition at line 323 of file sc_int.hh.
References sc_dt::sc_int_base::operator&=().
operator*=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator*= (int_type v) inline
Definition at line 303 of file sc_int.hh.
References sc_dt::sc_int_base::operator*=().
operator++() [1/2]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator++ () inline
Definition at line 355 of file sc_int.hh.
References sc_dt::sc_int_base::operator++().
operator++() [2/2]
template<int W> const sc_int<W> sc_dt::sc_int< W >::operator++ (int) inline
Definition at line 361 of file sc_int.hh.
References sc_dt::sc_int_base::operator++().
operator+=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator+= (int_type v) inline
Definition at line 291 of file sc_int.hh.
References sc_dt::sc_int_base::operator+=().
operator--() [1/2]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator-- () inline
Definition at line 366 of file sc_int.hh.
References sc_dt::sc_int_base::operator--().
operator--() [2/2]
template<int W> const sc_int<W> sc_dt::sc_int< W >::operator-- (int) inline
Definition at line 372 of file sc_int.hh.
References sc_dt::sc_int_base::operator--().
operator-=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator-= (int_type v) inline
Definition at line 297 of file sc_int.hh.
References sc_dt::sc_int_base::operator-=().
operator/=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator/= (int_type v) inline
Definition at line 309 of file sc_int.hh.
References sc_dt::sc_int_base::operator/=().
operator<<=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator<<= (int_type v) inline
Definition at line 341 of file sc_int.hh.
References sc_dt::sc_int_base::operator<<=().
operator=() [1/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (int_type v) inline
Definition at line 169 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [2/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_int_base & a) inline
Definition at line 175 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [3/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_int_subref_r & a) inline
Definition at line 181 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [4/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_int< W > & a) inline
Definition at line 187 of file sc_int.hh.
References sc_dt::sc_int_base::m_val.
operator=() [5/20]
template<int W> template<class T > sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_generic_base< T > & a) inline
Definition at line 194 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [6/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_signed & a) inline
Definition at line 200 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [7/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_unsigned & a) inline
Definition at line 206 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [8/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_fxval & a) inline
Definition at line 212 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [9/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_fxval_fast & a) inline
Definition at line 218 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [10/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_fxnum & a) inline
Definition at line 224 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [11/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_fxnum_fast & a) inline
Definition at line 229 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [12/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_bv_base & a) inline
Definition at line 235 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [13/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const sc_lv_base & a) inline
Definition at line 241 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [14/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (const char * a) inline
Definition at line 247 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [15/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (unsigned long a) inline
Definition at line 253 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [16/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (long a) inline
Definition at line 259 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [17/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (unsigned int a) inline
Definition at line 265 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [18/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (int a) inline
Definition at line 271 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [19/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (uint64 a) inline
Definition at line 277 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator=() [20/20]
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator= (double a) inline
Definition at line 283 of file sc_int.hh.
References sc_dt::sc_int_base::operator=().
operator>>=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator>>= (int_type v) inline
Definition at line 347 of file sc_int.hh.
References sc_dt::sc_int_base::operator>>=().
operator^=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator^= (int_type v) inline
Definition at line 335 of file sc_int.hh.
References sc_dt::sc_int_base::operator^=().
operator|=()
template<int W> sc_int<W>& sc_dt::sc_int< W >::operator|= (int_type v) inline
Definition at line 329 of file sc_int.hh.
References sc_dt::sc_int_base::operator|=().
The documentation for this class was generated from the following file:
systemc/ext/dt/int/sc_int.hh