gem5: KvmKernelGicV2 Class Reference
KvmKernelGicV2 Class Reference
KVM in-kernel GIC abstraction.
#include <gic.hh>
Public Member Functions
KvmKernelGicV2 (KvmVM &vm, Addr cpu_addr, Addr dist_addr, unsigned it_lines)
Instantiate a KVM in-kernel GIC model.
virtual ~KvmKernelGicV2 ()
KvmKernelGicV2 (const KvmKernelGicV2 &other)=delete
KvmKernelGicV2 (const KvmKernelGicV2 &&other)=delete
KvmKernelGicV2 & operator= (const KvmKernelGicV2 &&rhs)=delete
KvmKernelGicV2 & operator= (const KvmKernelGicV2 &rhs)=delete
Protected Member Functions
void setIntState (unsigned type, unsigned vcpu, unsigned irq, bool high)
Update the kernel's VGIC interrupt state.
uint32_t getGicReg (unsigned group, unsigned vcpu, unsigned offset)
Get value of GIC register "from" a cpu.
void setGicReg (unsigned group, unsigned vcpu, unsigned offset, unsigned value)
Set value of GIC register "from" a cpu.
Protected Attributes
KvmVM & vm
KVM VM in the parent system.
KvmDevice kdev
Kernel interface to the GIC.
In-kernel GIC API
const AddrRange cpuRange
Address range for the CPU interfaces.
const AddrRange distRange
Address range for the distributor interface.
void setSPI (unsigned spi)
Raise a shared peripheral interrupt.
void clearSPI (unsigned spi)
Clear a shared peripheral interrupt.
void setPPI (unsigned vcpu, unsigned ppi)
Raise a private peripheral interrupt.
void clearPPI (unsigned vcpu, unsigned ppi)
Clear a private peripheral interrupt.
uint32_t readDistributor (ContextID ctx, Addr daddr) override
BaseGicRegisters interface.
uint32_t readCpu (ContextID ctx, Addr daddr) override
void writeDistributor (ContextID ctx, Addr daddr, uint32_t data) override
void writeCpu (ContextID ctx, Addr daddr, uint32_t data) override
Detailed Description
KVM in-kernel GIC abstraction.
This class defines a high-level interface to the KVM in-kernel GIC model. It exposes an API that is similar to that of software-emulated GIC models in gem5.
Definition at line 57 of file gic.hh.
Constructor & Destructor Documentation
KvmKernelGicV2() [1/3]
KvmKernelGicV2::KvmKernelGicV2 (KvmVM & vm, Addr cpu_addr, Addr dist_addr, unsigned it_lines)
Instantiate a KVM in-kernel GIC model.
This constructor instantiates an in-kernel GIC model and wires it up to the virtual memory system.
Parameters
vm KVM VM representing this system
cpu_addr GIC CPU interface base address
dist_addr GIC distributor base address
it_lines Number of interrupt lines to support
Definition at line 50 of file gic.cc.
References KvmVM::enableKernelIRQChip(), kdev, KvmDevice::setAttr(), and vm.
~KvmKernelGicV2()
KvmKernelGicV2::~KvmKernelGicV2 () virtual
Definition at line 69 of file gic.cc.
KvmKernelGicV2() [2/3]
KvmKernelGicV2::KvmKernelGicV2 (const KvmKernelGicV2 & other) delete
KvmKernelGicV2() [3/3]
KvmKernelGicV2::KvmKernelGicV2 (const KvmKernelGicV2 && other) delete
Member Function Documentation
clearPPI()
void KvmKernelGicV2::clearPPI (unsigned vcpu, unsigned ppi)
Clear a private peripheral interrupt.
Parameters
vcpu KVM virtual CPU number ppi PPI interrupt number
Definition at line 92 of file gic.cc.
References setIntState().
Referenced by MuxingKvmGic::clearPPInt().
clearSPI()
void KvmKernelGicV2::clearSPI (unsigned spi)
Clear a shared peripheral interrupt.
Parameters
spi SPI number
Definition at line 80 of file gic.cc.
References setIntState().
Referenced by MuxingKvmGic::clearInt().
getGicReg()
uint32_t KvmKernelGicV2::getGicReg (unsigned group, unsigned vcpu, unsigned offset) protected
Get value of GIC register "from" a cpu.
Parameters
group Distributor or CPU (KVM_DEV_ARM_VGIC_GRP_{DIST,CPU}_REGS)
vcpu CPU id within KVM
offset register offset
Definition at line 113 of file gic.cc.
References ArmISA::attr, KvmDevice::getAttrPtr(), kdev, and X86ISA::reg.
Referenced by readCpu(), and readDistributor().
operator=() [1/2]
KvmKernelGicV2& KvmKernelGicV2::operator= (const KvmKernelGicV2 && rhs) delete
operator=() [2/2]
KvmKernelGicV2& KvmKernelGicV2::operator= (const KvmKernelGicV2 & rhs) delete
readCpu()
uint32_t KvmKernelGicV2::readCpu (ContextID ctx, Addr daddr) override virtual
Implements BaseGicRegisters.
Definition at line 148 of file gic.cc.
References KvmVM::contextIdToVCpuId(), getGicReg(), and vm.
readDistributor()
uint32_t KvmKernelGicV2::readDistributor (ContextID ctx, Addr daddr) override virtual
BaseGicRegisters interface.
Implements BaseGicRegisters.
Definition at line 141 of file gic.cc.
References KvmVM::contextIdToVCpuId(), getGicReg(), and vm.
setGicReg()
void KvmKernelGicV2::setGicReg (unsigned group, unsigned vcpu, unsigned offset, unsigned value) protected
Set value of GIC register "from" a cpu.
Parameters
group Distributor or CPU (KVM_DEV_ARM_VGIC_GRP_{DIST,CPU}_REGS)
vcpu CPU id within KVM
offset register offset
value value to set register to
Definition at line 127 of file gic.cc.
References ArmISA::attr, kdev, X86ISA::reg, and KvmDevice::setAttrPtr().
Referenced by writeCpu(), and writeDistributor().
setIntState()
void KvmKernelGicV2::setIntState (unsigned type, unsigned vcpu, unsigned irq, bool high) protected
Update the kernel's VGIC interrupt state.
Parameters
type Interrupt type (KVM_ARM_IRQ_TYPE_PPI/KVM_ARM_IRQ_TYPE_SPI)
vcpu CPU id within KVM (ignored for SPIs)
irq Interrupt number
high True to signal an interrupt, false to clear it.
Definition at line 98 of file gic.cc.
References KvmVM::setIRQLine(), and vm.
Referenced by clearPPI(), clearSPI(), setPPI(), and setSPI().
setPPI()
void KvmKernelGicV2::setPPI (unsigned vcpu, unsigned ppi)
Raise a private peripheral interrupt.
Parameters
vcpu KVM virtual CPU number ppi PPI interrupt number
Definition at line 86 of file gic.cc.
References setIntState().
Referenced by MuxingKvmGic::sendPPInt().
setSPI()
void KvmKernelGicV2::setSPI (unsigned spi)
Raise a shared peripheral interrupt.
Parameters
spi SPI number
Definition at line 74 of file gic.cc.
References setIntState().
Referenced by MuxingKvmGic::sendInt().
writeCpu()
void KvmKernelGicV2::writeCpu (ContextID ctx, Addr daddr, uint32_t data) override virtual
Implements BaseGicRegisters.
Definition at line 162 of file gic.cc.
References KvmVM::contextIdToVCpuId(), setGicReg(), and vm.
writeDistributor()
void KvmKernelGicV2::writeDistributor (ContextID ctx, Addr daddr, uint32_t data) override virtual
Implements BaseGicRegisters.
Definition at line 155 of file gic.cc.
References KvmVM::contextIdToVCpuId(), setGicReg(), and vm.
Member Data Documentation
cpuRange
const AddrRange KvmKernelGicV2::cpuRange
Address range for the CPU interfaces.
Definition at line 116 of file gic.hh.
distRange
const AddrRange KvmKernelGicV2::distRange
Address range for the distributor interface.
Definition at line 118 of file gic.hh.
kdev
KvmDevice KvmKernelGicV2::kdev protected
Kernel interface to the GIC.
Definition at line 165 of file gic.hh.
Referenced by getGicReg(), KvmKernelGicV2(), and setGicReg().
vm
KvmVM& KvmKernelGicV2::vm protected
KVM VM in the parent system.
Definition at line 162 of file gic.hh.
Referenced by KvmKernelGicV2(), readCpu(), readDistributor(), setIntState(), writeCpu(), and writeDistributor().
The documentation for this class was generated from the following files:
arch/arm/kvm/gic.hh
arch/arm/kvm/gic.cc