gem5: Stats::DataWrapVec2d< Derived, InfoProxyType > Class Template Reference
Stats::DataWrapVec2d< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>
Public Types
typedef InfoProxyType< Derived > Info
Public Types inherited from Stats::DataWrapVec< Derived, InfoProxyType >
typedef InfoProxyType< Derived > Info
Public Types inherited from Stats::DataWrap< Derived, InfoProxyType >
typedef InfoProxyType< Derived > Info
Public Member Functions
DataWrapVec2d (Group *parent, const char *name, const char *desc)
Derived & ysubnames (const char **names)
Derived & ysubname (off_type index, const std::string &subname)
std::string ysubname (off_type i) const
Public Member Functions inherited from Stats::DataWrapVec< Derived, InfoProxyType >
DataWrapVec (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
Derived & subname (off_type index, const std::string &name)
Set the subfield name for the given index, and marks this stat to print at the end of simulation.
Derived & subdesc (off_type index, const std::string &desc)
Set the subfield description for the given index and marks this stat to print at the end of simulation.
void prepare ()
void reset ()
Public Member Functions inherited from Stats::DataWrap< Derived, InfoProxyType >
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap & operator= (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
Derived & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Derived & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Derived & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Derived & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Derived & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
template<class Stat >
Derived & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Additional Inherited Members
Protected Member Functions inherited from Stats::DataWrap< Derived, InfoProxyType >
Derived & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Detailed Description
template<class Derived, template< class > class InfoProxyType>
class Stats::DataWrapVec2d< Derived, InfoProxyType >
Definition at line 439 of file statistics.hh.
Member Typedef Documentation
Info
template<class Derived, template< class > class InfoProxyType> typedef InfoProxyType<Derived> Stats::DataWrapVec2d< Derived, InfoProxyType >::Info
Definition at line 442 of file statistics.hh.
Constructor & Destructor Documentation
DataWrapVec2d()
template<class Derived, template< class > class InfoProxyType> Stats::DataWrapVec2d< Derived, InfoProxyType >::DataWrapVec2d (Group * parent, const char * name, const char * desc) inline
Definition at line 444 of file statistics.hh.
Member Function Documentation
ysubname() [1/2]
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubname (off_type index, const std::string & subname) inline
Definition at line 466 of file statistics.hh.
Referenced by MultiCompressor::regStats(), and ArmISA::TableWalker::regStats().
ysubname() [2/2]
template<class Derived, template< class > class InfoProxyType> std::string Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubname (off_type i) const inline
Definition at line 478 of file statistics.hh.
ysubnames()
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubnames (const char ** names) inline
Warning
This makes the assumption that if you're gonna subnames a 2d vector, you're subnaming across all y
Definition at line 454 of file statistics.hh.
Referenced by Minor::MinorStats::regStats(), InstructionQueue< Impl >::regStats(), and DefaultCommit< Impl >::regStats().
The documentation for this class was generated from the following file:
base/statistics.hh