gem5: tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
Public Types
typedef sync_enum_type(MODULE::* TransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* InvalidateDirectMemPtr) (sc_dt::uint64, sc_dt::uint64)
Public Member Functions
process (simple_socket_base *owner)
void set_transport_ptr (MODULE *mod, TransportPtr p)
void set_invalidate_direct_mem_ptr (MODULE *mod, InvalidateDirectMemPtr p)
sync_enum_type nb_transport_bw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Private Attributes
MODULE * m_mod
TransportPtr m_transport_ptr
InvalidateDirectMemPtr m_invalidate_direct_mem_ptr
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from tlm_utils::convenience_socket_cb_holder
convenience_socket_cb_holder (convenience_socket_base *owner)
void display_warning (const char *msg) const
void display_error (const char *msg) const
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process
Definition at line 78 of file simple_initiator_socket.h.
Member Typedef Documentation
InvalidateDirectMemPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::InvalidateDirectMemPtr) (sc_dt::uint64, sc_dt::uint64)
Definition at line 84 of file simple_initiator_socket.h.
TransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::TransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 82 of file simple_initiator_socket.h.
Constructor & Destructor Documentation
process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::process (simple_socket_base * owner) inline explicit
Definition at line 87 of file simple_initiator_socket.h.
Member Function Documentation
invalidate_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range) inline virtual
Implements tlm::tlm_bw_direct_mem_if.
Definition at line 130 of file simple_initiator_socket.h.
References tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_invalidate_direct_mem_ptr, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, and sc_assert.
nb_transport_bw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_bw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 117 of file simple_initiator_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_error(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_ptr, sc_assert, ArmISA::t, and tlm::TLM_COMPLETED.
set_invalidate_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr (MODULE * mod, InvalidateDirectMemPtr p) inline
Definition at line 105 of file simple_initiator_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_invalidate_direct_mem_ptr, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_invalidate_direct_mem_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_invalidate_direct_mem_ptr().
set_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr (MODULE * mod, TransportPtr p) inline
Definition at line 93 of file simple_initiator_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_ptr, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_bw(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_bw().
Member Data Documentation
m_invalidate_direct_mem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> InvalidateDirectMemPtr tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_invalidate_direct_mem_ptr private
Definition at line 144 of file simple_initiator_socket.h.
Referenced by tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr().
m_mod
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> MODULE* tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod private
Definition at line 142 of file simple_initiator_socket.h.
Referenced by tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr().
m_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> TransportPtr tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_ptr private
Definition at line 143 of file simple_initiator_socket.h.
Referenced by tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/simple_initiator_socket.h