gem5: ARMArchTLB Class Reference
ARMArchTLB Class Reference
#include <smmu_v3_caches.hh>
Classes
struct Entry
Public Member Functions
ARMArchTLB (unsigned numEntries, unsigned _associativity, const std::string &policy)
virtual ~ARMArchTLB ()
const Entry * lookup (Addr va, uint16_t asid, uint16_t vmid, bool updStats=true)
void store (const Entry &incoming)
void invalidateVA (Addr va, uint16_t asid, uint16_t vmid)
void invalidateVAA (Addr va, uint16_t vmid)
void invalidateASID (uint16_t asid, uint16_t vmid)
void invalidateVMID (uint16_t vmid)
void invalidateAll ()
Public Member Functions inherited from SMMUv3BaseCache
SMMUv3BaseCache (const std::string &policy_name, uint32_t seed)
virtual ~SMMUv3BaseCache ()
virtual void regStats (const std::string &name)
Private Types
typedef std::vector< Entry > Set
Private Member Functions
size_t pickSetIdx (Addr va, uint16_t asid, uint16_t vmid) const
size_t pickEntryIdxToReplace (const Set &set)
Private Attributes
std::vector< Set > sets
size_t associativity
Additional Inherited Members
Static Protected Member Functions inherited from SMMUv3BaseCache
static int decodePolicyName (const std::string &policy_name)
Protected Attributes inherited from SMMUv3BaseCache
int replacementPolicy
size_t nextToReplace
Random random
uint32_t useStamp
Stats::Formula averageLookups
Stats::Scalar totalLookups
Stats::Formula averageMisses
Stats::Scalar totalMisses
Stats::Formula averageUpdates
Stats::Scalar totalUpdates
Stats::Formula averageHitRate
Stats::Scalar insertions
Detailed Description
Definition at line 152 of file smmu_v3_caches.hh.
Member Typedef Documentation
Set
typedef std::vector<Entry> ARMArchTLB::Set private
Definition at line 187 of file smmu_v3_caches.hh.
Constructor & Destructor Documentation
ARMArchTLB()
ARMArchTLB::ARMArchTLB (unsigned numEntries, unsigned _associativity, const std::string & policy)
Definition at line 429 of file smmu_v3_caches.cc.
References associativity, ArmISA::e, fatal, sets, and ARMArchTLB::Entry::valid.
~ARMArchTLB()
virtual ARMArchTLB::~ARMArchTLB () inline virtual
Definition at line 173 of file smmu_v3_caches.hh.
References ArmISA::asid, and ArmISA::va.
Member Function Documentation
invalidateAll()
void ARMArchTLB::invalidateAll ()
Definition at line 574 of file smmu_v3_caches.cc.
References ArmISA::i, ArmISA::s, and sets.
Referenced by SMMUv3::processCommand().
invalidateASID()
void ARMArchTLB::invalidateASID (uint16_t asid, uint16_t vmid)
Definition at line 544 of file smmu_v3_caches.cc.
References ARMArchTLB::Entry::asid, ArmISA::e, ArmISA::i, ArmISA::s, sets, ARMArchTLB::Entry::valid, and ARMArchTLB::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVA()
void ARMArchTLB::invalidateVA (Addr va, uint16_t asid, uint16_t vmid)
Definition at line 513 of file smmu_v3_caches.cc.
References ARMArchTLB::Entry::asid, ArmISA::e, ArmISA::i, pickSetIdx(), sets, ARMArchTLB::Entry::va, ARMArchTLB::Entry::valid, ARMArchTLB::Entry::vaMask, and ARMArchTLB::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVAA()
void ARMArchTLB::invalidateVAA (Addr va, uint16_t vmid)
Definition at line 529 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ArmISA::s, sets, ARMArchTLB::Entry::va, ARMArchTLB::Entry::valid, ARMArchTLB::Entry::vaMask, and ARMArchTLB::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVMID()
void ARMArchTLB::invalidateVMID (uint16_t vmid)
Definition at line 559 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ArmISA::s, sets, ARMArchTLB::Entry::valid, and ARMArchTLB::Entry::vmid.
Referenced by SMMUv3::processCommand().
lookup()
const ARMArchTLB::Entry * ARMArchTLB::lookup (Addr va, uint16_t asid, uint16_t vmid, bool updStats = true)
Definition at line 459 of file smmu_v3_caches.cc.
References ARMArchTLB::Entry::asid, ArmISA::e, ArmISA::i, ARMArchTLB::Entry::lastUsed, panic, pickSetIdx(), sets, SMMUv3BaseCache::totalLookups, SMMUv3BaseCache::totalMisses, SMMUv3BaseCache::useStamp, ARMArchTLB::Entry::va, ARMArchTLB::Entry::valid, ARMArchTLB::Entry::vaMask, and ARMArchTLB::Entry::vmid.
Referenced by SMMUTranslationProcess::smmuTLBLookup(), and store().
pickEntryIdxToReplace()
size_t ARMArchTLB::pickEntryIdxToReplace (const Set & set) private
Definition at line 591 of file smmu_v3_caches.cc.
References associativity, ArmISA::i, SMMUv3BaseCache::insertions, SMMUv3BaseCache::nextToReplace, panic, SMMUv3BaseCache::random, Random::random(), SMMUv3BaseCache::replacementPolicy, SMMU_CACHE_REPL_LRU, SMMU_CACHE_REPL_RANDOM, and SMMU_CACHE_REPL_ROUND_ROBIN.
Referenced by store().
pickSetIdx()
size_t ARMArchTLB::pickSetIdx (Addr va, uint16_t asid, uint16_t vmid) const private
Definition at line 585 of file smmu_v3_caches.cc.
References sets.
Referenced by invalidateVA(), lookup(), and store().
store()
void ARMArchTLB::store (const Entry & incoming)
Definition at line 492 of file smmu_v3_caches.cc.
References ARMArchTLB::Entry::asid, ARMArchTLB::Entry::lastUsed, lookup(), panic, pickEntryIdxToReplace(), pickSetIdx(), sets, SMMUv3BaseCache::totalUpdates, ARMArchTLB::Entry::va, ARMArchTLB::Entry::valid, and ARMArchTLB::Entry::vmid.
Referenced by SMMUTranslationProcess::smmuTLBUpdate().
Member Data Documentation
associativity
size_t ARMArchTLB::associativity private
Definition at line 190 of file smmu_v3_caches.hh.
Referenced by ARMArchTLB(), and pickEntryIdxToReplace().
sets
std::vector<Set> ARMArchTLB::sets private
Definition at line 188 of file smmu_v3_caches.hh.
Referenced by ARMArchTLB(), invalidateAll(), invalidateASID(), invalidateVA(), invalidateVAA(), invalidateVMID(), lookup(), pickSetIdx(), and store().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_caches.hh
dev/arm/smmu_v3_caches.cc