gem5: TAGE Class Reference
TAGE Class Reference
#include <tage.hh>
Classes
struct TageBranchInfo
Public Member Functions
TAGE (const TAGEParams *params)
void uncondBranch (ThreadID tid, Addr br_pc, void *&bp_history) override
bool lookup (ThreadID tid, Addr branch_addr, void *&bp_history) override
Looks up a given PC in the BP to see if it is taken or not taken.
void btbUpdate (ThreadID tid, Addr branch_addr, void *&bp_history) override
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
void update (ThreadID tid, Addr branch_addr, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst, Addr corrTarget=MaxAddr) override
Updates the BP with taken/not taken information.
virtual void squash (ThreadID tid, void *bp_history) override
Public Member Functions inherited from BPredUnit
BPredUnit (const Params *p)
void regStats () override
Registers statistics.
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
virtual bool predict (ThreadID tid, Addr branch_pc, bool cond_branch, void *&b)
Protected Member Functions inherited from BPredUnit
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
TAGEBase * tage
Protected Attributes inherited from BPredUnit
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from BPredUnit
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 61 of file tage.hh.
Constructor & Destructor Documentation
TAGE()
TAGE::TAGE (const TAGEParams * params)
Definition at line 50 of file tage.cc.
Referenced by uncondBranch(), and TAGE::TageBranchInfo::~TageBranchInfo().
Member Function Documentation
btbUpdate()
void TAGE::btbUpdate (ThreadID tid, Addr instPC, void *& bp_history) override virtual
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Parameters
inst_PC The PC to look up the local predictor.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Implements BPredUnit.
Definition at line 119 of file tage.cc.
References PowerISA::bi, TAGEBase::btbUpdate(), tage, and TAGE::TageBranchInfo::tageBranchInfo.
Referenced by TAGE::TageBranchInfo::~TageBranchInfo().
lookup()
bool TAGE::lookup (ThreadID tid, Addr instPC, void *& bp_history) override virtual
Looks up a given PC in the BP to see if it is taken or not taken.
Parameters
inst_PC The PC to look up.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Returns
Whether the branch is taken or not taken.
Implements BPredUnit.
Definition at line 105 of file tage.cc.
References PowerISA::bi, DPRINTF, predict(), tage, TAGE::TageBranchInfo::tageBranchInfo, and TAGEBase::updateHistories().
Referenced by TAGE::TageBranchInfo::~TageBranchInfo().
predict()
bool TAGE::predict (ThreadID tid, Addr branch_pc, bool cond_branch, void *& b) protected virtual
Reimplemented in TAGE_SC_L, and LTAGE.
Definition at line 97 of file tage.cc.
References PowerISA::bi, tage, TAGE::TageBranchInfo::tageBranchInfo, and TAGEBase::tagePredict().
Referenced by lookup(), uncondBranch(), and TAGE::TageBranchInfo::~TageBranchInfo().
squash()
void TAGE::squash (ThreadID tid, void * bp_history) override virtual
Parameters
bp_history Pointer to the history object. The predictor will need to update any state and delete the object.
Implements BPredUnit.
Reimplemented in LTAGE.
Definition at line 89 of file tage.cc.
References PowerISA::bi, TAGEBase::BranchInfo::branchPC, DPRINTF, and TAGE::TageBranchInfo::tageBranchInfo.
Referenced by LTAGE::squash(), and TAGE::TageBranchInfo::~TageBranchInfo().
uncondBranch()
void TAGE::uncondBranch (ThreadID tid, Addr br_pc, void *& bp_history) override virtual
Implements BPredUnit.
Definition at line 126 of file tage.cc.
References PowerISA::bi, DPRINTF, predict(), tage, TAGE(), TAGE::TageBranchInfo::tageBranchInfo, and TAGEBase::updateHistories().
Referenced by TAGE::TageBranchInfo::~TageBranchInfo().
update()
void TAGE::update (ThreadID tid, Addr instPC, bool taken, void * bp_history, bool squashed, const StaticInstPtr & inst, Addr corrTarget = MaxAddr) override virtual
Updates the BP with taken/not taken information.
Parameters
inst_PC The branch's PC that will be updated.
taken Whether the branch was taken or not taken.
bp_history Pointer to the branch predictor state that is associated with the branch lookup that is being updated.
squashed Set to true when this function is called during a squash operation.
inst Static instruction information
corrTarget The resolved target of the branch (only needed for squashed branches)
Todo:
Make this update flexible enough to handle a global predictor.
Implements BPredUnit.
Reimplemented in TAGE_SC_L.
Definition at line 56 of file tage.cc.
References PowerISA::bi, TAGEBase::BranchInfo::condBranch, TAGEBase::condBranchUpdate(), DPRINTF, MaxAddr, Random::random(), random_mt, TAGEBase::squash(), tage, TAGE::TageBranchInfo::tageBranchInfo, TAGEBase::BranchInfo::tagePred, TAGEBase::updateHistories(), and TAGEBase::updateStats().
Referenced by TAGE::TageBranchInfo::~TageBranchInfo().
Member Data Documentation
tage
TAGEBase* TAGE::tage protected
Definition at line 64 of file tage.hh.
Referenced by btbUpdate(), lookup(), predict(), LTAGE::predict(), TAGE_SC_L::predict(), uncondBranch(), LTAGE::update(), update(), and TAGE_SC_L::update().
The documentation for this class was generated from the following files:
cpu/pred/tage.hh
cpu/pred/tage.cc