gem5: RiscvISA::RiscvFault Class Reference
RiscvISA::RiscvFault Class Reference
#include <faults.hh>
Protected Member Functions
RiscvFault (FaultName n, bool i, ExceptionCode c)
FaultName name () const override
bool isInterrupt () const
ExceptionCode exception () const
virtual RegVal trap_value () const
virtual void invokeSE (ThreadContext *tc, const StaticInstPtr &inst)
void invoke (ThreadContext *tc, const StaticInstPtr &inst) override
Protected Attributes
const FaultName _name
const bool _interrupt
ExceptionCode _code
Additional Inherited Members
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Detailed Description
Definition at line 95 of file faults.hh.
Constructor & Destructor Documentation
RiscvFault()
RiscvISA::RiscvFault::RiscvFault (FaultName n, bool i, ExceptionCode c) inline protected
Definition at line 102 of file faults.hh.
Member Function Documentation
exception()
ExceptionCode RiscvISA::RiscvFault::exception () const inline protected
Definition at line 108 of file faults.hh.
References _code.
invoke()
void RiscvISA::RiscvFault::invoke (ThreadContext * tc, const StaticInstPtr & inst) override protected virtual
Reimplemented from FaultBase.
Definition at line 54 of file faults.cc.
References _code, addr, RiscvISA::advancePC(), bits(), FullSystem, ThreadContext::instAddr(), invokeSE(), isInterrupt(), RiscvISA::MISCREG_MCAUSE, RiscvISA::MISCREG_MEDELEG, RiscvISA::MISCREG_MEPC, RiscvISA::MISCREG_MIDELEG, RiscvISA::MISCREG_MTVAL, RiscvISA::MISCREG_MTVEC, RiscvISA::MISCREG_PRV, RiscvISA::MISCREG_SCAUSE, RiscvISA::MISCREG_SEDELEG, RiscvISA::MISCREG_SEPC, RiscvISA::MISCREG_SIDELEG, RiscvISA::MISCREG_STATUS, RiscvISA::MISCREG_STVAL, RiscvISA::MISCREG_STVEC, RiscvISA::MISCREG_UCAUSE, RiscvISA::MISCREG_UEPC, RiscvISA::MISCREG_UTVAL, RiscvISA::MISCREG_UTVEC, panic, ThreadContext::pcState(), RiscvISA::PRV_M, RiscvISA::PRV_S, RiscvISA::PRV_U, ThreadContext::readMiscReg(), GenericISA::UPCState< MachInst >::set(), ThreadContext::setMiscReg(), ArmISA::status, and trap_value().
Referenced by RiscvISA::Reset::name(), and trap_value().
invokeSE()
void RiscvISA::RiscvFault::invokeSE (ThreadContext * tc, const StaticInstPtr & inst) protected virtual
Reimplemented in RiscvISA::SyscallFault, RiscvISA::BreakpointFault, RiscvISA::IllegalFrmFault, RiscvISA::UnimplementedFault, RiscvISA::IllegalInstFault, and RiscvISA::UnknownInstFault.
Definition at line 48 of file faults.cc.
References name(), panic, and ThreadContext::pcState().
Referenced by RiscvISA::IllegalFrmFault::IllegalFrmFault(), RiscvISA::IllegalInstFault::IllegalInstFault(), invoke(), RiscvISA::SyscallFault::SyscallFault(), trap_value(), RiscvISA::BreakpointFault::trap_value(), RiscvISA::UnimplementedFault::UnimplementedFault(), and RiscvISA::UnknownInstFault::UnknownInstFault().
isInterrupt()
bool RiscvISA::RiscvFault::isInterrupt () const inline protected
Definition at line 107 of file faults.hh.
References _interrupt.
Referenced by invoke().
name()
FaultName RiscvISA::RiscvFault::name () const inline override protected virtual
Implements FaultBase.
Definition at line 106 of file faults.hh.
References _name.
Referenced by invokeSE().
trap_value()
virtual RegVal RiscvISA::RiscvFault::trap_value () const inline protected virtual
Reimplemented in RiscvISA::BreakpointFault, RiscvISA::AddressFault, and RiscvISA::InstFault.
Definition at line 109 of file faults.hh.
References invoke(), and invokeSE().
Referenced by invoke().
Member Data Documentation
_code
ExceptionCode RiscvISA::RiscvFault::_code protected
Definition at line 100 of file faults.hh.
Referenced by exception(), invoke(), and RiscvISA::SyscallFault::SyscallFault().
_interrupt
const bool RiscvISA::RiscvFault::_interrupt protected
Definition at line 99 of file faults.hh.
Referenced by isInterrupt().
_name
const FaultName RiscvISA::RiscvFault::_name protected
Definition at line 98 of file faults.hh.
Referenced by name(), and RiscvISA::Reset::name().
The documentation for this class was generated from the following files:
arch/riscv/faults.hh
arch/riscv/faults.cc