gem5: GpuDispatcher Class Reference
GpuDispatcher Class Reference
#include <dispatcher.hh>
Classes
class TLBPort
Public Types
typedef GpuDispatcherParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MasterID masterId ()
GpuDispatcher (const Params *p)
~GpuDispatcher ()
void exec ()
virtual void serialize (CheckpointOut &cp) const override
Serialize an object.
virtual void unserialize (CheckpointIn &cp) override
Unserialize an object.
void notifyWgCompl (Wavefront *w)
void scheduleDispatch ()
void accessUserVar (BaseCPU *cpu, uint64_t addr, int val, int off)
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
int getNumCUs ()
int wfSize () const
void setFuncargsSize (int funcargs_size)
uint32_t getStaticContextSize () const
Returns the size of the static hardware context of a wavefront.
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Static Public Member Functions
static void setInstance (GpuDispatcher *_instance)
static GpuDispatcher * getInstance ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
Stats::Scalar num_kernelLaunched
TLBPort * tlbPort
Protected Types
typedef std::unordered_map< uint64_t, uint64_t > TranslationBuffer
Protected Attributes
MasterID _masterId
Addr pioAddr
Addr pioSize
Tick pioDelay
HsaQueueEntry curTask
std::unordered_map< int, NDRange > ndRangeMap
NDRange ndRange
std::queue< int > execIds
std::queue< int > doneIds
uint64_t dispatchCount
bool dispatchActive
BaseCPU * cpu
Shader * shader
ClDriver * driver
EventFunctionWrapper tickEvent
TranslationBuffer tlb
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static GpuDispatcher * instance = nullptr
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 55 of file dispatcher.hh.
Member Typedef Documentation
Params
typedef GpuDispatcherParams GpuDispatcher::Params
Definition at line 58 of file dispatcher.hh.
TranslationBuffer
typedef std::unordered_map<uint64_t, uint64_t> GpuDispatcher::TranslationBuffer protected
Definition at line 95 of file dispatcher.hh.
Constructor & Destructor Documentation
GpuDispatcher()
GpuDispatcher::GpuDispatcher (const Params * p)
Definition at line 51 of file dispatcher.cc.
References EventBase::CPU_Tick_Pri, csprintf(), Stats::DataWrap< Derived, InfoProxyType >::desc(), driver, exec(), getInstance(), NDRange::globalWgId, ClDriver::handshake(), Shader::handshake(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), ndRange, num_kernelLaunched, EventManager::schedule(), setInstance(), shader, tickEvent, tlbPort, and NDRange::wg_disp_rem.
~GpuDispatcher()
GpuDispatcher::~GpuDispatcher () inline
Definition at line 103 of file dispatcher.hh.
References accessUserVar(), addr, exec(), notifyWgCompl(), scheduleDispatch(), serialize(), unserialize(), X86ISA::val, and MipsISA::w.
Member Function Documentation
accessUserVar()
void GpuDispatcher::accessUserVar (BaseCPU * cpu, uint64_t addr, int val, int off)
Definition at line 355 of file dispatcher.cc.
References Shader::AccessMem(), panic, MemCmd::ReadReq, shader, and MemCmd::WriteReq.
Referenced by notifyWgCompl(), write(), and ~GpuDispatcher().
exec()
void GpuDispatcher::exec ()
Definition at line 265 of file dispatcher.cc.
References cpu, Shader::dispatch_workgroups(), doneIds, DPRINTF, execIds, Shader::hostWakeUp(), ndRangeMap, shader, and Shader::updateContext().
Referenced by GpuDispatcher(), and ~GpuDispatcher().
getAddrRanges()
AddrRangeList GpuDispatcher::getAddrRanges () const override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 114 of file dispatcher.cc.
References DPRINTF, pioAddr, pioSize, and RangeSize().
getInstance()
static GpuDispatcher* GpuDispatcher::getInstance () inline static
Definition at line 121 of file dispatcher.hh.
References instance.
Referenced by GpuDispatcher().
getNumCUs()
int GpuDispatcher::getNumCUs ()
Definition at line 372 of file dispatcher.cc.
References Shader::cuList, and shader.
Referenced by ClDriver::ioctl().
getPort()
Port & GpuDispatcher::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from DmaDevice.
Definition at line 255 of file dispatcher.cc.
References DmaDevice::getPort(), and tlbPort.
getStaticContextSize()
uint32_t GpuDispatcher::getStaticContextSize () const
Returns the size of the static hardware context of a wavefront.
Definition at line 390 of file dispatcher.cc.
References Shader::cuList, and shader.
Referenced by ClDriver::ioctl().
masterId()
MasterID GpuDispatcher::masterId () inline
Definition at line 60 of file dispatcher.hh.
References _masterId.
notifyWgCompl()
void GpuDispatcher::notifyWgCompl (Wavefront * w)
Definition at line 310 of file dispatcher.cc.
References accessUserVar(), cpu, curTick(), doneIds, DPRINTF, HostState::event, MipsISA::event, Wavefront::kernId, ndRangeMap, ArmISA::q, Shader::ReadMem(), EventManager::schedule(), Event::scheduled(), shader, tickEvent, Shader::ticks(), and Shader::WriteMem().
Referenced by ~GpuDispatcher().
read()
Tick GpuDispatcher::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 127 of file dispatcher.cc.
References Packet::allocate(), curTask, dispatchActive, DPRINTF, Packet::getAddr(), Packet::getPtr(), Packet::getSize(), Packet::makeAtomicResponse(), ArmISA::offset, pioAddr, pioDelay, pioSize, and Packet::setLE().
scheduleDispatch()
void GpuDispatcher::scheduleDispatch ()
Definition at line 348 of file dispatcher.cc.
References curTick(), EventManager::schedule(), Event::scheduled(), shader, tickEvent, and Shader::ticks().
Referenced by HsailISA::Ret::execute(), and ~GpuDispatcher().
serialize()
void GpuDispatcher::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 85 of file dispatcher.cc.
References fatal, ndRange, Event::scheduled(), SERIALIZE_SCALAR, tickEvent, NDRange::wg_disp_rem, and Event::when().
Referenced by ~GpuDispatcher().
setFuncargsSize()
void GpuDispatcher::setFuncargsSize (int funcargs_size)
Definition at line 384 of file dispatcher.cc.
References Shader::funcargs_size, and shader.
Referenced by ClDriver::handshake().
setInstance()
static void GpuDispatcher::setInstance (GpuDispatcher * _instance) inline static
Definition at line 116 of file dispatcher.hh.
Referenced by GpuDispatcher().
unserialize()
void GpuDispatcher::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 100 of file dispatcher.cc.
References EventManager::deschedule(), EventManager::schedule(), Event::scheduled(), tickEvent, and UNSERIALIZE_SCALAR.
Referenced by ~GpuDispatcher().
wfSize()
int GpuDispatcher::wfSize () const
Definition at line 378 of file dispatcher.cc.
References Shader::cuList, and shader.
Referenced by ClDriver::ioctl().
write()
Tick GpuDispatcher::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 157 of file dispatcher.cc.
References accessUserVar(), NDRange::addrToNotify, HsaQueueEntry::addrToNotify, cpu, NDRange::curCid, curTask, curTick(), HsaQueueEntry::depends, dispatchActive, NDRange::dispatchId, divCeil(), DPRINTF, HostState::event, NDRange::execDone, execIds, HsaQueueEntry::gdSize, Packet::getAddr(), Packet::getLE(), Packet::getPtr(), Packet::getSize(), NDRange::globalWgId, ArmISA::i, Packet::makeAtomicResponse(), ndRangeMap, num_kernelLaunched, NDRange::numDispLeft, HsaQueueEntry::numDispLeft, NDRange::numWg, NDRange::numWgCompleted, NDRange::numWgTotal, ArmISA::offset, pioAddr, pioDelay, pioSize, NDRange::q, Shader::ReadMem(), Packet::req, EventManager::schedule(), Event::scheduled(), shader, tickEvent, Shader::ticks(), NDRange::wg_disp_rem, NDRange::wgId, HsaQueueEntry::wgSize, and Shader::WriteMem().
Member Data Documentation
_masterId
MasterID GpuDispatcher::_masterId protected
Definition at line 63 of file dispatcher.hh.
Referenced by masterId().
cpu
BaseCPU* GpuDispatcher::cpu protected
Definition at line 84 of file dispatcher.hh.
Referenced by exec(), notifyWgCompl(), and write().
curTask
HsaQueueEntry GpuDispatcher::curTask protected
Definition at line 70 of file dispatcher.hh.
Referenced by read(), and write().
dispatchActive
bool GpuDispatcher::dispatchActive protected
Definition at line 82 of file dispatcher.hh.
Referenced by read(), and write().
dispatchCount
uint64_t GpuDispatcher::dispatchCount protected
Definition at line 80 of file dispatcher.hh.
doneIds
std::queue<int> GpuDispatcher::doneIds protected
Definition at line 78 of file dispatcher.hh.
Referenced by exec(), and notifyWgCompl().
driver
ClDriver* GpuDispatcher::driver protected
Definition at line 86 of file dispatcher.hh.
Referenced by GpuDispatcher().
execIds
std::queue<int> GpuDispatcher::execIds protected
Definition at line 76 of file dispatcher.hh.
Referenced by exec(), and write().
instance
GpuDispatcher * GpuDispatcher::instance = nullptr static protected
Definition at line 90 of file dispatcher.hh.
Referenced by getInstance().
ndRange
NDRange GpuDispatcher::ndRange protected
Definition at line 73 of file dispatcher.hh.
Referenced by GpuDispatcher(), and serialize().
ndRangeMap
std::unordered_map<int, NDRange> GpuDispatcher::ndRangeMap protected
Definition at line 72 of file dispatcher.hh.
Referenced by exec(), notifyWgCompl(), and write().
num_kernelLaunched
Stats::Scalar GpuDispatcher::num_kernelLaunched
Definition at line 100 of file dispatcher.hh.
Referenced by GpuDispatcher(), and write().
pioAddr
Addr GpuDispatcher::pioAddr protected
Definition at line 66 of file dispatcher.hh.
Referenced by getAddrRanges(), read(), and write().
pioDelay
Tick GpuDispatcher::pioDelay protected
Definition at line 68 of file dispatcher.hh.
Referenced by read(), and write().
pioSize
Addr GpuDispatcher::pioSize protected
Definition at line 67 of file dispatcher.hh.
Referenced by getAddrRanges(), read(), and write().
shader
Shader* GpuDispatcher::shader protected
Definition at line 85 of file dispatcher.hh.
Referenced by accessUserVar(), exec(), getNumCUs(), getStaticContextSize(), GpuDispatcher(), notifyWgCompl(), scheduleDispatch(), setFuncargsSize(), wfSize(), and write().
tickEvent
EventFunctionWrapper GpuDispatcher::tickEvent protected
Definition at line 87 of file dispatcher.hh.
Referenced by GpuDispatcher(), notifyWgCompl(), scheduleDispatch(), serialize(), unserialize(), and write().
tlb
TranslationBuffer GpuDispatcher::tlb protected
Definition at line 96 of file dispatcher.hh.
tlbPort
TLBPort* GpuDispatcher::tlbPort
Definition at line 141 of file dispatcher.hh.
Referenced by Shader::functionalTLBAccess(), getPort(), and GpuDispatcher().
The documentation for this class was generated from the following files:
gpu-compute/dispatcher.hh
gpu-compute/dispatcher.cc