gem5: DefaultBTB Class Reference
DefaultBTB Class Reference
#include <btb.hh>
Classes
struct BTBEntry
Public Member Functions
DefaultBTB (unsigned numEntries, unsigned tagBits, unsigned instShiftAmt, unsigned numThreads)
Creates a BTB with the given number of entries, number of bits per tag, and instruction offset amount.
void reset ()
TheISA::PCState lookup (Addr instPC, ThreadID tid)
Looks up an address in the BTB.
bool valid (Addr instPC, ThreadID tid)
Checks if a branch is in the BTB.
void update (Addr instPC, const TheISA::PCState &targetPC, ThreadID tid)
Updates the BTB with the target of a branch.
Private Member Functions
unsigned getIndex (Addr instPC, ThreadID tid)
Returns the index into the BTB, based on the branch's PC.
Addr getTag (Addr instPC)
Returns the tag bits of a given address.
Private Attributes
std::vector< BTBEntry > btb
The actual BTB.
unsigned numEntries
The number of entries in the BTB.
unsigned idxMask
The index mask.
unsigned tagBits
The number of tag bits per entry.
unsigned tagMask
The tag mask.
unsigned instShiftAmt
Number of bits to shift PC when calculating index.
unsigned tagShiftAmt
Number of bits to shift PC when calculating tag.
unsigned log2NumThreads
Log2 NumThreads used for hashing threadid.
Detailed Description
Definition at line 39 of file btb.hh.
Constructor & Destructor Documentation
DefaultBTB()
DefaultBTB::DefaultBTB (unsigned numEntries, unsigned tagBits, unsigned instShiftAmt, unsigned numThreads)
Creates a BTB with the given number of entries, number of bits per tag, and instruction offset amount.
Parameters
numEntries Number of entries for the BTB.
tagBits Number of bits for each tag in the BTB.
instShiftAmt Offset amount for instructions to ignore alignment.
Definition at line 37 of file btb.cc.
References btb, DPRINTF, fatal, floorLog2(), ArmISA::i, idxMask, instShiftAmt, isPowerOf2(), numEntries, tagBits, tagMask, and tagShiftAmt.
Member Function Documentation
getIndex()
unsigned DefaultBTB::getIndex (Addr instPC, ThreadID tid) inline private
Returns the index into the BTB, based on the branch's PC.
Parameters
inst_PC The branch to look up.
Returns
Returns the index into the BTB.
Definition at line 75 of file btb.cc.
References idxMask, instShiftAmt, log2NumThreads, and tagShiftAmt.
Referenced by lookup(), update(), and valid().
getTag()
Addr DefaultBTB::getTag (Addr instPC) inline private
Returns the tag bits of a given address.
Parameters
inst_PC The branch's address.
Returns
Returns the tag bits.
Definition at line 85 of file btb.cc.
References tagMask, and tagShiftAmt.
Referenced by lookup(), update(), and valid().
lookup()
TheISA::PCState DefaultBTB::lookup (Addr instPC, ThreadID tid)
Looks up an address in the BTB.
Must call valid() first on the address.
Parameters
inst_PC The address of the branch to look up.
tid The thread id.
Returns
Returns the target of the branch.
Definition at line 112 of file btb.cc.
References btb, getIndex(), getTag(), numEntries, and valid().
Referenced by BPredUnit::BTBLookup(), and BPredUnit::predict().
reset()
void DefaultBTB::reset ()
Definition at line 66 of file btb.cc.
References btb, ArmISA::i, and numEntries.
update()
void DefaultBTB::update (Addr instPC, const TheISA::PCState & targetPC, ThreadID tid)
Updates the BTB with the target of a branch.
Parameters
inst_PC The address of the branch being updated.
target_PC The target address of the branch.
tid The thread id.
Definition at line 130 of file btb.cc.
References btb, getIndex(), getTag(), and numEntries.
Referenced by BPredUnit::BTBUpdate(), and BPredUnit::squash().
valid()
bool DefaultBTB::valid (Addr instPC, ThreadID tid)
Checks if a branch is in the BTB.
Parameters
inst_PC The address of the branch to look up.
tid The thread id.
Returns
Whether or not the branch exists in the BTB.
Definition at line 91 of file btb.cc.
References btb, getIndex(), getTag(), and numEntries.
Referenced by BPredUnit::BTBValid(), lookup(), and BPredUnit::predict().
Member Data Documentation
btb
std::vector<BTBEntry> DefaultBTB::btb private
The actual BTB.
Definition at line 109 of file btb.hh.
Referenced by DefaultBTB(), lookup(), reset(), update(), and valid().
idxMask
unsigned DefaultBTB::idxMask private
The index mask.
Definition at line 115 of file btb.hh.
Referenced by DefaultBTB(), and getIndex().
instShiftAmt
unsigned DefaultBTB::instShiftAmt private
Number of bits to shift PC when calculating index.
Definition at line 124 of file btb.hh.
Referenced by DefaultBTB(), and getIndex().
log2NumThreads
unsigned DefaultBTB::log2NumThreads private
Log2 NumThreads used for hashing threadid.
Definition at line 130 of file btb.hh.
Referenced by getIndex().
numEntries
unsigned DefaultBTB::numEntries private
The number of entries in the BTB.
Definition at line 112 of file btb.hh.
Referenced by DefaultBTB(), lookup(), reset(), update(), and valid().
tagBits
unsigned DefaultBTB::tagBits private
The number of tag bits per entry.
Definition at line 118 of file btb.hh.
Referenced by DefaultBTB().
tagMask
unsigned DefaultBTB::tagMask private
The tag mask.
Definition at line 121 of file btb.hh.
Referenced by DefaultBTB(), and getTag().
tagShiftAmt
unsigned DefaultBTB::tagShiftAmt private
Number of bits to shift PC when calculating tag.
Definition at line 127 of file btb.hh.
Referenced by DefaultBTB(), getIndex(), and getTag().
The documentation for this class was generated from the following files:
cpu/pred/btb.hh
cpu/pred/btb.cc