gem5: sc_gem5::VcdTraceValBase Class Reference
sc_gem5::VcdTraceValBase Class Reference abstract
Public Member Functions
VcdTraceValBase (int width)
~VcdTraceValBase ()
void vcdName (const std::string &vcd_name)
const std::string & vcdName ()
virtual std::string vcdType ()
virtual void output (std::ostream &os)=0
Public Member Functions inherited from sc_gem5::TraceValBase
TraceValBase (int _width)
virtual ~TraceValBase ()
int width ()
virtual void finalize ()
virtual bool check ()=0
Protected Member Functions
const char * stripLeadingBits (const char *orig)
char scLogicToVcdState (char in)
void printVal (std::ostream &os, const std::string &rep)
Protected Attributes
std::string _vcdName
Protected Attributes inherited from sc_gem5::TraceValBase
int _width
Detailed Description
Definition at line 72 of file vcd.cc.
Constructor & Destructor Documentation
VcdTraceValBase()
sc_gem5::VcdTraceValBase::VcdTraceValBase (int width) inline
Definition at line 133 of file vcd.cc.
~VcdTraceValBase()
sc_gem5::VcdTraceValBase::~VcdTraceValBase () inline
Definition at line 134 of file vcd.cc.
Member Function Documentation
output()
virtual void sc_gem5::VcdTraceValBase::output (std::ostream & os) pure virtual
Implemented in sc_gem5::VcdTraceValInt< T >, sc_gem5::VcdTraceValTime, sc_gem5::VcdTraceValEvent, sc_gem5::VcdTraceValFxnum< T >, sc_gem5::VcdTraceValFxval< T >, sc_gem5::VcdTraceValLogic< T >, sc_gem5::VcdTraceValFinite< T >, sc_gem5::VcdTraceValScLogic, sc_gem5::VcdTraceValFloat< T >, and sc_gem5::VcdTraceValBool.
Referenced by vcdType().
printVal()
void sc_gem5::VcdTraceValBase::printVal (std::ostream & os, const std::string & rep) inline protected
Definition at line 117 of file vcd.cc.
References stripLeadingBits(), vcdName(), and sc_gem5::TraceValBase::width().
Referenced by sc_gem5::VcdTraceValBool::output(), sc_gem5::VcdTraceValScLogic::output(), sc_gem5::VcdTraceValFinite< T >::output(), sc_gem5::VcdTraceValLogic< T >::output(), sc_gem5::VcdTraceValFxnum< T >::output(), sc_gem5::VcdTraceValEvent::output(), sc_gem5::VcdTraceValTime::output(), and sc_gem5::VcdTraceValInt< T >::output().
scLogicToVcdState()
char sc_gem5::VcdTraceValBase::scLogicToVcdState (char in) inline protected
Definition at line 95 of file vcd.cc.
Referenced by sc_gem5::VcdTraceValScLogic::output().
stripLeadingBits()
const char* sc_gem5::VcdTraceValBase::stripLeadingBits (const char * orig) inline protected
Definition at line 78 of file vcd.cc.
Referenced by printVal().
vcdName() [1/2]
void sc_gem5::VcdTraceValBase::vcdName (const std::string & vcd_name) inline
Definition at line 136 of file vcd.cc.
Referenced by sc_gem5::VcdTraceScope::output().
vcdName() [2/2]
const std::string& sc_gem5::VcdTraceValBase::vcdName () inline
Definition at line 137 of file vcd.cc.
References _vcdName.
Referenced by sc_gem5::VcdTraceValFloat< T >::output(), sc_gem5::VcdTraceValFxval< T >::output(), printVal(), and sc_gem5::VcdTraceVal<::sc_core::sc_time >::VcdTraceVal().
vcdType()
virtual std::string sc_gem5::VcdTraceValBase::vcdType () inline virtual
Reimplemented in sc_gem5::VcdTraceValTime, sc_gem5::VcdTraceValEvent, sc_gem5::VcdTraceValFxval< T >, and sc_gem5::VcdTraceValFloat< T >.
Definition at line 138 of file vcd.cc.
References X86ISA::os, and output().
Referenced by sc_gem5::VcdTraceScope::output().
Member Data Documentation
_vcdName
std::string sc_gem5::VcdTraceValBase::_vcdName protected
Definition at line 75 of file vcd.cc.
Referenced by vcdName().
The documentation for this class was generated from the following file:
systemc/utils/vcd.cc