gem5: X86ISA::X86FaultBase Class Reference
X86ISA::X86FaultBase Class Reference
#include <faults.hh>
Public Member Functions
virtual uint8_t getVector () const
Get the vector of an interrupt.
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Protected Member Functions
X86FaultBase (const char *_faultName, const char *_mnem, const uint8_t _vector, uint64_t _errorCode=(uint64_t) -1)
const char * name () const
virtual bool isBenign ()
virtual const char * mnemonic () const
virtual bool isSoft ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
virtual std::string describe () const
Protected Attributes
const char * faultName
const char * mnem
uint8_t vector
uint64_t errorCode
Detailed Description
Definition at line 53 of file faults.hh.
Constructor & Destructor Documentation
X86FaultBase()
X86ISA::X86FaultBase::X86FaultBase (const char * _faultName, const char * _mnem, const uint8_t _vector, uint64_t _errorCode = (uint64_t)-1) inline protected
Definition at line 61 of file faults.hh.
Member Function Documentation
describe()
std::string X86ISA::X86FaultBase::describe () const protected virtual
Reimplemented in X86ISA::PageFault.
Definition at line 98 of file faults.cc.
References ccprintf(), errorCode, mnemonic(), and ArmISA::ss.
Referenced by X86ISA::PageFault::describe(), invoke(), isSoft(), and X86ISA::PageFault::PageFault().
getVector()
virtual uint8_t X86ISA::X86FaultBase::getVector () const inline virtual
Get the vector of an interrupt.
Returns
interrupt vector number.
Definition at line 99 of file faults.hh.
References vector.
Referenced by X86KvmCPU::deliverInterrupts().
invoke()
void X86ISA::X86FaultBase::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) protected virtual
Reimplemented from FaultBase.
Reimplemented in X86ISA::StartupInterrupt, X86ISA::InitInterrupt, X86ISA::PageFault, X86ISA::InvalidOpcode, X86ISA::X86Abort, and X86ISA::X86Trap.
Definition at line 55 of file faults.cc.
References describe(), DPRINTF, errorCode, FullSystem, X86ISA::INTREG_MICRO(), FaultBase::invoke(), isSoft(), X86ISA::MISCREG_M5_REG, GenericISA::UPCState< MachInst >::nupc(), panic, GenericISA::SimplePCState< MachInst >::pc(), X86ISA::pc, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), romMicroPC(), ThreadContext::setIntReg(), GenericISA::UPCState< MachInst >::upc(), and vector.
Referenced by X86ISA::InitInterrupt::InitInterrupt(), X86ISA::InvalidOpcode::InvalidOpcode(), X86ISA::X86Trap::invoke(), X86ISA::InvalidOpcode::invoke(), X86ISA::PageFault::invoke(), isSoft(), X86ISA::PageFault::PageFault(), X86ISA::StartupInterrupt::StartupInterrupt(), X86ISA::X86Abort::X86Abort(), and X86ISA::X86Trap::X86Trap().
isBenign()
virtual bool X86ISA::X86FaultBase::isBenign () inline protected virtual
Definition at line 73 of file faults.hh.
isSoft()
virtual bool X86ISA::X86FaultBase::isSoft () inline protected virtual
Reimplemented in X86ISA::SoftwareInterrupt.
Definition at line 83 of file faults.hh.
References describe(), invoke(), and StaticInst::nullStaticInstPtr.
Referenced by invoke().
mnemonic()
virtual const char* X86ISA::X86FaultBase::mnemonic () const inline protected virtual
Definition at line 78 of file faults.hh.
References mnem.
Referenced by describe().
name()
const char* X86ISA::X86FaultBase::name () const inline protected virtual
Implements FaultBase.
Definition at line 68 of file faults.hh.
References faultName.
Member Data Documentation
errorCode
uint64_t X86ISA::X86FaultBase::errorCode protected
Definition at line 59 of file faults.hh.
Referenced by describe(), invoke(), and X86ISA::PageFault::invoke().
faultName
const char* X86ISA::X86FaultBase::faultName protected
Definition at line 56 of file faults.hh.
Referenced by name().
mnem
const char* X86ISA::X86FaultBase::mnem protected
Definition at line 57 of file faults.hh.
Referenced by mnemonic().
vector
uint8_t X86ISA::X86FaultBase::vector protected
Definition at line 58 of file faults.hh.
Referenced by getVector(), invoke(), and X86ISA::StartupInterrupt::invoke().
The documentation for this class was generated from the following files:
arch/x86/faults.hh
arch/x86/faults.cc