gem5: sc_core::sc_in< T > Class Template Reference
sc_core::sc_in< T > Class Template Reference
#include <sc_clock.hh>
Public Member Functions
sc_in ()
sc_in (const char *name)
virtual ~sc_in ()
sc_in (const sc_signal_in_if< T > &interface)
sc_in (const char *name, const sc_signal_in_if< T > &interface)
sc_in (sc_port_b< sc_signal_in_if< T > > &parent)
sc_in (const char *name, sc_port_b< sc_signal_in_if< T > > &parent)
sc_in (sc_port< sc_signal_in_if< T >, 1 > &parent)
sc_in (const char *name, sc_port< sc_signal_in_if< T >, 1 > &parent)
virtual void bind (const sc_signal_in_if< T > &i)
void operator() (const sc_signal_in_if< T > &i)
virtual void bind (sc_port< sc_signal_in_if< T >, 1 > &i)
void operator() (sc_port< sc_signal_in_if< T >, 1 > &p)
virtual void bind (sc_port< sc_signal_inout_if< T >, 1 > &p)
void operator() (sc_port< sc_signal_inout_if< T >, 1 > &p)
virtual void end_of_elaboration ()
const T & read () const
operator const T & () const
const sc_event & default_event () const
const sc_event & value_changed_event () const
bool event () const
sc_event_finder & value_changed () const
virtual const char * kind () const
void add_trace (sc_trace_file *tf, const std::string &name) const
Public Member Functions inherited from sc_core::sc_port< sc_signal_in_if< T >, 1 >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_in_if< T > &interface)
sc_port (const char *name, const sc_signal_in_if< T > &interface)
sc_port (sc_port_b< sc_signal_in_if< T > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_in_if< T > > &parent)
sc_port (sc_port< sc_signal_in_if< T >, N, SC_ONE_OR_MORE_BOUND > &parent)
sc_port (const char *name, sc_port< sc_signal_in_if< T >, N, SC_ONE_OR_MORE_BOUND > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< T > >
void operator() (sc_signal_in_if< T > &i)
void operator() (sc_port_b< sc_signal_in_if< T > > &p)
virtual void bind (sc_signal_in_if< T > &i)
virtual void bind (sc_port_b< sc_signal_in_if< T > > &p)
sc_signal_in_if< T > * operator-> ()
const sc_signal_in_if< T > * operator-> () const
sc_signal_in_if< T > * operator[] (int n)
const sc_signal_in_if< T > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Member Functions
sc_in (const sc_in< T > &)
sc_in< T > & operator= (const sc_in< T > &)
Private Attributes
sc_event_finder_t< sc_signal_in_if< T > > _valueChangedFinder
sc_trace_params_vec traceParamsVec
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< T > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
template<class T>
class sc_core::sc_in< T >
Definition at line 47 of file sc_clock.hh.
Constructor & Destructor Documentation
sc_in() [1/9]
template<class T> sc_core::sc_in< T >::sc_in () inline
Definition at line 52 of file sc_in.hh.
sc_in() [2/9]
template<class T> sc_core::sc_in< T >::sc_in (const char * name) inline explicit
Definition at line 55 of file sc_in.hh.
~sc_in()
template<class T> virtual sc_core::sc_in< T >::~sc_in () inline virtual
Definition at line 58 of file sc_in.hh.
sc_in() [3/9]
template<class T> sc_core::sc_in< T >::sc_in (const sc_signal_in_if< T > & interface) inline explicit
Definition at line 61 of file sc_in.hh.
sc_in() [4/9]
template<class T> sc_core::sc_in< T >::sc_in (const char * name, const sc_signal_in_if< T > & interface) inline
Definition at line 65 of file sc_in.hh.
sc_in() [5/9]
template<class T> sc_core::sc_in< T >::sc_in (sc_port_b< sc_signal_in_if< T > > & parent) inline explicit
Definition at line 69 of file sc_in.hh.
sc_in() [6/9]
template<class T> sc_core::sc_in< T >::sc_in (const char * name, sc_port_b< sc_signal_in_if< T > > & parent) inline
Definition at line 73 of file sc_in.hh.
sc_in() [7/9]
template<class T> sc_core::sc_in< T >::sc_in (sc_port< sc_signal_in_if< T >, 1 > & parent) inline explicit
Definition at line 77 of file sc_in.hh.
sc_in() [8/9]
template<class T> sc_core::sc_in< T >::sc_in (const char * name, sc_port< sc_signal_in_if< T >, 1 > & parent) inline
Definition at line 81 of file sc_in.hh.
sc_in() [9/9]
template<class T> sc_core::sc_in< T >::sc_in (const sc_in< T > &) private
Member Function Documentation
add_trace()
template<class T> void sc_core::sc_in< T >::add_trace (sc_trace_file * tf, const std::string & name) const inline
Definition at line 141 of file sc_in.hh.
bind() [1/3]
template<class T> virtual void sc_core::sc_in< T >::bind (const sc_signal_in_if< T > & i) inline virtual
Definition at line 88 of file sc_in.hh.
Referenced by sc_core::sc_in< sc_dt::sc_lv< W > >::bind(), sc_core::sc_in< bool >::bind(), sc_core::sc_in< sc_dt::sc_logic >::bind(), sc_core::sc_in< sc_dt::sc_lv< W > >::operator()(), sc_core::sc_in< bool >::operator()(), sc_core::sc_in< sc_dt::sc_logic >::operator()(), sc_core::sc_in< sc_dt::sc_lv< W > >::sc_in(), sc_core::sc_in< bool >::sc_in(), and sc_core::sc_in< sc_dt::sc_logic >::sc_in().
bind() [2/3]
template<class T> virtual void sc_core::sc_in< T >::bind (sc_port< sc_signal_in_if< T >, 1 > & i) inline virtual
Definition at line 96 of file sc_in.hh.
bind() [3/3]
template<class T> virtual void sc_core::sc_in< T >::bind (sc_port< sc_signal_inout_if< T >, 1 > & p) inline virtual
Definition at line 107 of file sc_in.hh.
default_event()
template<class T> const sc_event& sc_core::sc_in< T >::default_event () const inline
Definition at line 129 of file sc_in.hh.
end_of_elaboration()
template<class T> virtual void sc_core::sc_in< T >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Reimplemented in sc_core::sc_in_rv< W >.
Definition at line 118 of file sc_in.hh.
Referenced by sc_core::sc_in_resolved::end_of_elaboration().
event()
template<class T> bool sc_core::sc_in< T >::event () const inline
Definition at line 135 of file sc_in.hh.
kind()
template<class T> virtual const char* sc_core::sc_in< T >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_in_if< T >, 1 >.
Reimplemented in sc_core::sc_in_rv< W >.
Definition at line 138 of file sc_in.hh.
operator const T &()
template<class T> sc_core::sc_in< T >::operator const T & () const inline
Definition at line 127 of file sc_in.hh.
operator()() [1/3]
template<class T> void sc_core::sc_in< T >::operator() (const sc_signal_in_if< T > & i) inline
Definition at line 93 of file sc_in.hh.
operator()() [2/3]
template<class T> void sc_core::sc_in< T >::operator() (sc_port< sc_signal_in_if< T >, 1 > & p) inline
Definition at line 101 of file sc_in.hh.
operator()() [3/3]
template<class T> void sc_core::sc_in< T >::operator() (sc_port< sc_signal_inout_if< T >, 1 > & p) inline
Definition at line 112 of file sc_in.hh.
operator=()
template<class T> sc_in<T>& sc_core::sc_in< T >::operator= (const sc_in< T > &) private
read()
template<class T> const T& sc_core::sc_in< T >::read () const inline
Definition at line 126 of file sc_in.hh.
value_changed()
template<class T> sc_event_finder& sc_core::sc_in< T >::value_changed () const inline
Definition at line 136 of file sc_in.hh.
value_changed_event()
template<class T> const sc_event& sc_core::sc_in< T >::value_changed_event () const inline
Definition at line 131 of file sc_in.hh.
Member Data Documentation
_valueChangedFinder
template<class T> sc_event_finder_t<sc_signal_in_if<T> > sc_core::sc_in< T >::_valueChangedFinder mutable private
Definition at line 147 of file sc_in.hh.
Referenced by sc_core::sc_in< sc_dt::sc_lv< W > >::value_changed(), sc_core::sc_in< bool >::value_changed(), and sc_core::sc_in< sc_dt::sc_logic >::value_changed().
traceParamsVec
template<class T> sc_trace_params_vec sc_core::sc_in< T >::traceParamsVec mutable private
Definition at line 149 of file sc_in.hh.
Referenced by sc_core::sc_in< sc_dt::sc_lv< W > >::add_trace(), sc_core::sc_in< bool >::add_trace(), sc_core::sc_in< sc_dt::sc_logic >::add_trace(), sc_core::sc_in< sc_dt::sc_lv< W > >::end_of_elaboration(), sc_core::sc_in< bool >::end_of_elaboration(), and sc_core::sc_in< sc_dt::sc_logic >::end_of_elaboration().
The documentation for this class was generated from the following files:
systemc/ext/channel/sc_clock.hh
systemc/ext/channel/sc_in.hh