gem5: GenericISA::DelaySlotPCState< MachInst > Class Template Reference
GenericISA::DelaySlotPCState< MachInst > Class Template Reference
#include <types.hh>
Public Member Functions
Addr nnpc () const
void nnpc (Addr val)
void set (Addr val)
DelaySlotPCState ()
DelaySlotPCState (Addr val)
bool branching () const
void advance ()
bool operator== (const DelaySlotPCState< MachInst > &opc) const
bool operator!= (const DelaySlotPCState< MachInst > &opc) const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from GenericISA::SimplePCState< MachInst >
Addr pc () const
void pc (Addr val)
Addr npc () const
void npc (Addr val)
void set (Addr val)
void setNPC (Addr val)
SimplePCState ()
SimplePCState (Addr val)
bool branching () const
void advance ()
Public Member Functions inherited from GenericISA::PCStateBase
Addr instAddr () const
Returns the memory address the bytes of this instruction came from.
Addr nextInstAddr () const
Returns the memory address the bytes of the next instruction came from.
MicroPC microPC () const
Returns the current micropc.
void set (Addr val)
Force this PC to reflect a particular value, resetting all its other fields around it.
bool operator== (const PCStateBase &opc) const
bool operator!= (const PCStateBase &opc) const
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Types
typedef SimplePCState< MachInst > Base
Protected Types inherited from GenericISA::SimplePCState< MachInst >
typedef PCStateBase Base
Protected Attributes
Addr _nnpc
Protected Attributes inherited from GenericISA::PCStateBase
Addr _pc
Addr _npc
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from GenericISA::PCStateBase
PCStateBase ()
PCStateBase (Addr val)
Detailed Description
template<class MachInst>
class GenericISA::DelaySlotPCState< MachInst >
Definition at line 294 of file types.hh.
Member Typedef Documentation
Base
template<class MachInst> typedef SimplePCState<MachInst> GenericISA::DelaySlotPCState< MachInst >::Base protected
Definition at line 297 of file types.hh.
Constructor & Destructor Documentation
DelaySlotPCState() [1/2]
template<class MachInst> GenericISA::DelaySlotPCState< MachInst >::DelaySlotPCState () inline
Definition at line 313 of file types.hh.
DelaySlotPCState() [2/2]
template<class MachInst> GenericISA::DelaySlotPCState< MachInst >::DelaySlotPCState (Addr val) inline
Definition at line 314 of file types.hh.
References X86ISA::val.
Member Function Documentation
advance()
template<class MachInst> void GenericISA::DelaySlotPCState< MachInst >::advance () inline
Definition at line 326 of file types.hh.
Referenced by SparcISA::SparcStaticInst::advancePC(), MipsISA::advancePC(), MipsISA::buildRetPC(), and SparcISA::TrapInstruction::invoke().
branching()
template<class MachInst> bool GenericISA::DelaySlotPCState< MachInst >::branching () const inline
Definition at line 317 of file types.hh.
References MipsISA::pc.
nnpc() [1/2]
template<class MachInst> Addr GenericISA::DelaySlotPCState< MachInst >::nnpc () const inline
Definition at line 303 of file types.hh.
Referenced by Trace::SparcNativeTrace::check(), SparcISA::SparcFaultBase::invoke(), SparcISA::PowerOnReset::invoke(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs().
nnpc() [2/2]
template<class MachInst> void GenericISA::DelaySlotPCState< MachInst >::nnpc (Addr val) inline
Definition at line 304 of file types.hh.
References X86ISA::val.
operator!=()
template<class MachInst> bool GenericISA::DelaySlotPCState< MachInst >::operator!= (const DelaySlotPCState< MachInst > & opc) const inline
Definition at line 342 of file types.hh.
operator==()
template<class MachInst> bool GenericISA::DelaySlotPCState< MachInst >::operator== (const DelaySlotPCState< MachInst > & opc) const inline
Definition at line 334 of file types.hh.
References GenericISA::DelaySlotPCState< MachInst >::_nnpc, GenericISA::PCStateBase::_npc, and GenericISA::PCStateBase::_pc.
serialize()
template<class MachInst> void GenericISA::DelaySlotPCState< MachInst >::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from GenericISA::PCStateBase.
Reimplemented in GenericISA::DelaySlotUPCState< MachInst >.
Definition at line 348 of file types.hh.
References serialize(), and SERIALIZE_SCALAR.
set()
template<class MachInst> void GenericISA::DelaySlotPCState< MachInst >::set (Addr val) inline
Definition at line 307 of file types.hh.
References X86ISA::val.
Referenced by MipsISA::skipFunction().
unserialize()
template<class MachInst> void GenericISA::DelaySlotPCState< MachInst >::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from GenericISA::PCStateBase.
Reimplemented in GenericISA::DelaySlotUPCState< MachInst >.
Definition at line 355 of file types.hh.
References unserialize(), and UNSERIALIZE_SCALAR.
Member Data Documentation
_nnpc
template<class MachInst> Addr GenericISA::DelaySlotPCState< MachInst >::_nnpc protected
Definition at line 299 of file types.hh.
Referenced by GenericISA::DelaySlotPCState< MachInst >::operator==(), and GenericISA::DelaySlotUPCState< MachInst >::operator==().
The documentation for this class was generated from the following file:
arch/generic/types.hh