gem5: AtomicResponseProtocol Class Reference
AtomicResponseProtocol Class Reference abstract
#include <atomic.hh>
Protected Member Functions
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
virtual Tick recvAtomic (PacketPtr pkt)=0
Receive an atomic request packet from the peer.
virtual Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)=0
Receive an atomic request packet from the peer, and optionally provide a backdoor to the data being accessed.
Friends
class AtomicRequestProtocol
Detailed Description
Definition at line 90 of file atomic.hh.
Member Function Documentation
recvAtomic()
virtual Tick AtomicResponseProtocol::recvAtomic (PacketPtr pkt) protected pure virtual
Receive an atomic request packet from the peer.
Implemented in BaseCache::CpuSidePort, X86ISA::GpuTLB::CpuSidePort, CommMonitor::MonitorSlavePort, Bridge::BridgeSlavePort, SerialLink::SerialLinkSlavePort, AddrMapper::MapperSlavePort, MemCheckerMonitor::MonitorSlavePort, TLBCoalescer::CpuSidePort, LdsState::CuSidePort, SMMUATSSlavePort, RubyPort::PioSlavePort, CoherentXBar::CoherentXBarSlavePort, DRAMCtrl::MemoryPort, NoncoherentXBar::NoncoherentXBarSlavePort, SimpleCache::CPUSidePort, MemDelay::SlavePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, SMMUControlPort, SimpleMemobj::CPUSidePort, SimpleMemory::MemoryPort, QoS::MemSinkCtrl::MemoryPort, RubyPort::MemSlavePort, SMMUSlavePort, SimpleTimingPort, DRAMSim2::MemoryPort, X86ISA::IntSlavePort< Device >, X86ISA::IntSlavePort< X86ISA::Interrupts >, StubSlavePort, PioPort< Device >, PioPort< PioDevice >, and PioPort< X86ISA::Interrupts >.
Referenced by SlavePort::recvAtomicBackdoor(), and AtomicRequestProtocol::send().
recvAtomicBackdoor()
virtual Tick AtomicResponseProtocol::recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & backdoor) protected pure virtual
Receive an atomic request packet from the peer, and optionally provide a backdoor to the data being accessed.
Implemented in SlavePort, CoherentXBar::CoherentXBarSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, and SimpleMemory::MemoryPort.
Referenced by AtomicRequestProtocol::sendBackdoor().
sendSnoop()
Tick AtomicResponseProtocol::sendSnoop (AtomicRequestProtocol * peer, PacketPtr pkt) protected
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters
peer Peer to send packet to.
pkt Snoop packet to send.
Returns
Estimated latency of access.
Definition at line 69 of file atomic.cc.
References Packet::isRequest(), and AtomicRequestProtocol::recvAtomicSnoop().
Referenced by SlavePort::sendAtomicSnoop().
Friends And Related Function Documentation
AtomicRequestProtocol
friend class AtomicRequestProtocol friend
Definition at line 92 of file atomic.hh.
The documentation for this class was generated from the following files:
mem/protocol/atomic.hh
mem/protocol/atomic.cc