gem5: sc_dt::sc_uint_subref Class Reference
sc_dt::sc_uint_subref Class Reference
#include <sc_uint_base.hh>
Public Member Functions
sc_uint_subref (const sc_uint_subref &init)
sc_uint_subref & operator= (uint_type v)
sc_uint_subref & operator= (const sc_uint_base &a)
sc_uint_subref & operator= (const sc_uint_subref_r &a)
sc_uint_subref & operator= (const sc_uint_subref &a)
template<class T >
sc_uint_subref & operator= (const sc_generic_base< T > &a)
sc_uint_subref & operator= (const char *a)
sc_uint_subref & operator= (unsigned long a)
sc_uint_subref & operator= (long a)
sc_uint_subref & operator= (unsigned int a)
sc_uint_subref & operator= (int a)
sc_uint_subref & operator= (int64 a)
sc_uint_subref & operator= (double a)
sc_uint_subref & operator= (const sc_signed &)
sc_uint_subref & operator= (const sc_unsigned &)
sc_uint_subref & operator= (const sc_bv_base &)
sc_uint_subref & operator= (const sc_lv_base &)
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_uint_subref_r
sc_uint_subref_r (const sc_uint_subref_r &init)
virtual ~sc_uint_subref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_uint_subref ()
Protected Member Functions inherited from sc_dt::sc_uint_subref_r
sc_uint_subref_r ()
void initialize (const sc_uint_base *obj_p, int left_i, int right_i)
Static Protected Attributes
static sc_core::sc_vpool< sc_uint_subref > m_pool
Friends
class sc_uint_base
class sc_core::sc_vpool< sc_uint_subref >
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_uint_subref_r
int m_left
sc_uint_base * m_obj_p
int m_right
Detailed Description
Definition at line 375 of file sc_uint_base.hh.
Constructor & Destructor Documentation
sc_uint_subref() [1/2]
sc_dt::sc_uint_subref::sc_uint_subref () inline protected
Definition at line 382 of file sc_uint_base.hh.
sc_uint_subref() [2/2]
sc_dt::sc_uint_subref::sc_uint_subref (const sc_uint_subref & init) inline
Definition at line 385 of file sc_uint_base.hh.
References ArmISA::a, and ArmISA::v.
Member Function Documentation
concat_set() [1/4]
void sc_dt::sc_uint_subref::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 293 of file sc_uint_base.cc.
References PowerISA::aa, and length.
concat_set() [2/4]
void sc_dt::sc_uint_subref::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 300 of file sc_uint_base.cc.
References PowerISA::aa, length, and sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_uint_subref::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 310 of file sc_uint_base.cc.
References PowerISA::aa, length, and sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_uint_subref::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 320 of file sc_uint_base.cc.
References PowerISA::aa, and length.
operator=() [1/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (uint_type v)
Definition at line 250 of file sc_uint_base.cc.
References ArmISA::mask, sc_dt::mask_int, and X86ISA::val.
operator=() [2/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const sc_uint_base & a) inline
Definition at line 1110 of file sc_uint_base.hh.
operator=() [3/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (const sc_uint_subref_r & a) inline
Definition at line 392 of file sc_uint_base.hh.
operator=() [4/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (const sc_uint_subref & a) inline
Definition at line 397 of file sc_uint_base.hh.
operator=() [5/16]
template<class T > sc_uint_subref& sc_dt::sc_uint_subref::operator= (const sc_generic_base< T > & a) inline
Definition at line 403 of file sc_uint_base.hh.
operator=() [6/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const char * a) inline
Definition at line 1116 of file sc_uint_base.hh.
References PowerISA::aa, and length.
operator=() [7/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (unsigned long a) inline
Definition at line 409 of file sc_uint_base.hh.
operator=() [8/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (long a) inline
Definition at line 414 of file sc_uint_base.hh.
operator=() [9/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (unsigned int a) inline
Definition at line 419 of file sc_uint_base.hh.
operator=() [10/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (int a) inline
Definition at line 424 of file sc_uint_base.hh.
operator=() [11/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (int64 a) inline
Definition at line 429 of file sc_uint_base.hh.
operator=() [12/16]
sc_uint_subref& sc_dt::sc_uint_subref::operator= (double a) inline
Definition at line 434 of file sc_uint_base.hh.
References MipsISA::is.
operator=() [13/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const sc_signed & a)
Definition at line 262 of file sc_uint_base.cc.
References PowerISA::aa, and length.
operator=() [14/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const sc_unsigned & a)
Definition at line 269 of file sc_uint_base.cc.
References PowerISA::aa, and length.
operator=() [15/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const sc_bv_base & a)
Definition at line 276 of file sc_uint_base.cc.
References PowerISA::aa, and length.
operator=() [16/16]
sc_uint_subref & sc_dt::sc_uint_subref::operator= (const sc_lv_base & a)
Definition at line 283 of file sc_uint_base.cc.
References PowerISA::aa, and length.
scan()
void sc_dt::sc_uint_subref::scan (::std::istream & is = ::std::cin)
Definition at line 328 of file sc_uint_base.cc.
References ArmISA::s.
Referenced by sc_dt::operator>>().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_uint_subref >
friend class sc_core::sc_vpool< sc_uint_subref > friend
Definition at line 378 of file sc_uint_base.hh.
sc_uint_base
friend class sc_uint_base friend
Definition at line 377 of file sc_uint_base.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_uint_subref > sc_dt::sc_uint_subref::m_pool static protected
Definition at line 453 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_base::operator()(), and sc_dt::sc_uint_base::range().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_uint_base.hh
systemc/dt/int/sc_uint_base.cc