gem5: MemDelay Class Reference
MemDelay Class Reference
This abstract component provides a mechanism to delay packets.
#include <mem_delay.hh>
Classes
class MasterPort
class SlavePort
Public Member Functions
MemDelay (const MemDelayParams *params)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
bool trySatisfyFunctional (PacketPtr pkt)
virtual Tick delayReq (PacketPtr pkt)
Delay a request by some number of ticks.
virtual Tick delayResp (PacketPtr pkt)
Delay a response by some number of ticks.
virtual Tick delaySnoopResp (PacketPtr pkt)
Delay a snoop response by some number of ticks.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
MasterPort masterPort
SlavePort slavePort
ReqPacketQueue reqQueue
RespPacketQueue respQueue
SnoopRespPacketQueue snoopRespQueue
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
This abstract component provides a mechanism to delay packets.
It can be spliced between arbitrary ports of the memory system and delays packets that pass through it.
Specialisations of this abstract class should override at least one of delayReq, delayResp, deleySnoopReq, delaySnoopResp. These methods receive a PacketPtr as their argument and return a delay in Ticks. The base class implements an infinite buffer to hold delayed packets until they are ready. The intention is to use this component for rapid prototyping of other memory system components that introduce a packet processing delays.
NOTE: Packets may be reordered if the delays aren't constant.
Definition at line 64 of file mem_delay.hh.
Constructor & Destructor Documentation
MemDelay()
MemDelay::MemDelay (const MemDelayParams * params)
Definition at line 45 of file mem_delay.cc.
Member Function Documentation
delayReq()
virtual Tick MemDelay::delayReq (PacketPtr pkt) inline protected virtual
Delay a request by some number of ticks.
Returns
Ticks to delay packet.
Reimplemented in SimpleMemDelay.
Definition at line 140 of file mem_delay.hh.
Referenced by MemDelay::SlavePort::recvAtomic(), and MemDelay::SlavePort::recvTimingReq().
delayResp()
virtual Tick MemDelay::delayResp (PacketPtr pkt) inline protected virtual
Delay a response by some number of ticks.
Returns
Ticks to delay packet.
Reimplemented in SimpleMemDelay.
Definition at line 147 of file mem_delay.hh.
Referenced by MemDelay::SlavePort::recvAtomic(), and MemDelay::MasterPort::recvTimingResp().
delaySnoopResp()
virtual Tick MemDelay::delaySnoopResp (PacketPtr pkt) inline protected virtual
Delay a snoop response by some number of ticks.
Returns
Ticks to delay packet.
Definition at line 154 of file mem_delay.hh.
Referenced by MemDelay::MasterPort::recvAtomicSnoop(), and MemDelay::SlavePort::recvTimingSnoopResp().
getPort()
Port & MemDelay::getPort (const std::string & if_name, PortID idx = InvalidPortID) override protected virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 64 of file mem_delay.cc.
References SimObject::getPort(), masterPort, and slavePort.
init()
void MemDelay::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 56 of file mem_delay.cc.
References fatal, Port::isConnected(), masterPort, and slavePort.
trySatisfyFunctional()
bool MemDelay::trySatisfyFunctional (PacketPtr pkt) protected
Definition at line 76 of file mem_delay.cc.
References masterPort, slavePort, QueuedSlavePort::trySatisfyFunctional(), and QueuedMasterPort::trySatisfyFunctional().
Referenced by MemDelay::SlavePort::recvFunctional(), and MemDelay::MasterPort::recvFunctionalSnoop().
Member Data Documentation
masterPort
MasterPort MemDelay::masterPort protected
Definition at line 127 of file mem_delay.hh.
Referenced by MemDelay::SlavePort::getAddrRanges(), getPort(), init(), MemDelay::SlavePort::recvAtomic(), MemDelay::SlavePort::recvFunctional(), MemDelay::SlavePort::recvTimingReq(), MemDelay::SlavePort::recvTimingSnoopResp(), and trySatisfyFunctional().
reqQueue
ReqPacketQueue MemDelay::reqQueue protected
Definition at line 130 of file mem_delay.hh.
respQueue
RespPacketQueue MemDelay::respQueue protected
Definition at line 131 of file mem_delay.hh.
slavePort
SlavePort MemDelay::slavePort protected
Definition at line 128 of file mem_delay.hh.
Referenced by getPort(), init(), MemDelay::MasterPort::isSnooping(), MemDelay::MasterPort::recvAtomicSnoop(), MemDelay::MasterPort::recvFunctionalSnoop(), MemDelay::MasterPort::recvRangeChange(), MemDelay::MasterPort::recvTimingResp(), MemDelay::MasterPort::recvTimingSnoopReq(), and trySatisfyFunctional().
snoopRespQueue
SnoopRespPacketQueue MemDelay::snoopRespQueue protected
Definition at line 132 of file mem_delay.hh.
The documentation for this class was generated from the following files:
mem/mem_delay.hh
mem/mem_delay.cc