gem5: tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
Public Types
typedef sync_enum_type(MODULE::* NBTransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* BTransportPtr) (transaction_type &, sc_core::sc_time &)
typedef unsigned int(MODULE::* TransportDbgPtr) (transaction_type &)
typedef bool(MODULE::* GetDirectMem_ptr) (transaction_type &, tlm::tlm_dmi &)
Public Member Functions
process (passthrough_socket_base *owner)
void set_nb_transport_ptr (MODULE *mod, NBTransportPtr p)
void set_b_transport_ptr (MODULE *mod, BTransportPtr p)
void set_transport_dbg_ptr (MODULE *mod, TransportDbgPtr p)
void set_get_direct_mem_ptr (MODULE *mod, GetDirectMem_ptr p)
sync_enum_type nb_transport_fw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void b_transport (transaction_type &trans, sc_core::sc_time &t)
unsigned int transport_dbg (transaction_type &trans)
bool get_direct_mem_ptr (transaction_type &trans, tlm::tlm_dmi &dmi_data)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Private Attributes
MODULE * m_mod
NBTransportPtr m_nb_transport_ptr
BTransportPtr m_b_transport_ptr
TransportDbgPtr m_transport_dbg_ptr
GetDirectMem_ptr m_get_direct_mem_ptr
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from tlm_utils::convenience_socket_cb_holder
convenience_socket_cb_holder (convenience_socket_base *owner)
void display_warning (const char *msg) const
void display_error (const char *msg) const
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process
Definition at line 92 of file passthrough_target_socket.h.
Member Typedef Documentation
BTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::BTransportPtr) (transaction_type &, sc_core::sc_time &)
Definition at line 98 of file passthrough_target_socket.h.
GetDirectMem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef bool(MODULE::* tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::GetDirectMem_ptr) (transaction_type &, tlm::tlm_dmi &)
Definition at line 101 of file passthrough_target_socket.h.
NBTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::NBTransportPtr) (transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 96 of file passthrough_target_socket.h.
TransportDbgPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef unsigned int(MODULE::* tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::TransportDbgPtr) (transaction_type &)
Definition at line 100 of file passthrough_target_socket.h.
Constructor & Destructor Documentation
process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::process (passthrough_socket_base * owner) inline explicit
Definition at line 104 of file passthrough_target_socket.h.
Member Function Documentation
b_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport (transaction_type & trans, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_blocking_transport_if< TYPES::tlm_payload_type >.
Definition at line 173 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_error(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, sc_assert, and ArmISA::t.
get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr (transaction_type & trans, tlm::tlm_dmi & dmi_data) inline virtual
Implements tlm::tlm_fw_direct_mem_if< TYPES::tlm_payload_type >.
Definition at line 196 of file passthrough_target_socket.h.
References tlm::tlm_dmi::allow_read_write(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, sc_assert, tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_fw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 159 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_error(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr, sc_assert, ArmISA::t, and tlm::TLM_COMPLETED.
set_b_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr (MODULE * mod, BTransportPtr p) inline
Definition at line 123 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport().
set_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr (MODULE * mod, GetDirectMem_ptr p) inline
Definition at line 147 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr().
set_nb_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr (MODULE * mod, NBTransportPtr p) inline
Definition at line 111 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw().
set_transport_dbg_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr (MODULE * mod, TransportDbgPtr p) inline
Definition at line 135 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr, mod(), MipsISA::p, and sc_assert.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg().
transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg (transaction_type & trans) inline virtual
Implements tlm::tlm_transport_dbg_if< TYPES::tlm_payload_type >.
Definition at line 184 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr, and sc_assert.
Member Data Documentation
m_b_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> BTransportPtr tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr private
Definition at line 213 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr().
m_get_direct_mem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> GetDirectMem_ptr tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr private
Definition at line 215 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr().
m_mod
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> MODULE* tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod private
Definition at line 211 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg().
m_nb_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> NBTransportPtr tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr private
Definition at line 212 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr().
m_transport_dbg_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> TransportDbgPtr tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr private
Definition at line 214 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/passthrough_target_socket.h