gem5: SimpleATTarget1 Class Reference
SimpleATTarget1 Class Reference
#include <SimpleATTarget1.h>
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm_utils::simple_target_socket< SimpleATTarget1 > target_socket_type
Public Member Functions
SC_HAS_PROCESS (SimpleATTarget1)
SimpleATTarget1 (sc_core::sc_module_name name)
sync_enum_type myNBTransport (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void endRequest ()
void beginResponse ()
void endResponse ()
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Attributes
target_socket_type socket
Private Attributes
const sc_core::sc_time ACCEPT_DELAY
const sc_core::sc_time RESPONSE_DELAY
unsigned char mMem [400]
std::queue< transaction_type * > mEndRequestQueue
sc_core::sc_event mEndRequestEvent
std::queue< transaction_type * > mResponseQueue
sc_core::sc_event mBeginResponseEvent
sc_core::sc_event mEndResponseEvent
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
Definition at line 31 of file SimpleATTarget1.h.
Member Typedef Documentation
phase_type
typedef tlm::tlm_phase SimpleATTarget1::phase_type
Definition at line 35 of file SimpleATTarget1.h.
sync_enum_type
typedef tlm::tlm_sync_enum SimpleATTarget1::sync_enum_type
Definition at line 36 of file SimpleATTarget1.h.
target_socket_type
typedef tlm_utils::simple_target_socket<SimpleATTarget1> SimpleATTarget1::target_socket_type
Definition at line 37 of file SimpleATTarget1.h.
transaction_type
typedef tlm::tlm_generic_payload SimpleATTarget1::transaction_type
Definition at line 34 of file SimpleATTarget1.h.
Constructor & Destructor Documentation
SimpleATTarget1()
SimpleATTarget1::SimpleATTarget1 (sc_core::sc_module_name name) inline
Definition at line 44 of file SimpleATTarget1.h.
References beginResponse(), sc_core::sc_module::dont_initialize(), endRequest(), endResponse(), mBeginResponseEvent, mEndRequestEvent, mEndResponseEvent, myNBTransport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_nb_transport_fw(), SC_METHOD, and sc_core::sc_module::sensitive.
Member Function Documentation
beginResponse()
void SimpleATTarget1::beginResponse () inline
Definition at line 151 of file SimpleATTarget1.h.
References tlm::BEGIN_RESP, X86ISA::exit, tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_data_ptr(), mEndResponseEvent, mMem, mResponseQueue, sc_core::sc_event::notify(), sc_core::SC_ZERO_TIME, tlm::tlm_generic_payload::set_response_status(), ArmISA::t, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, tlm::TLM_OK_RESPONSE, tlm::TLM_READ_COMMAND, and tlm::TLM_UPDATED.
Referenced by SimpleATTarget1().
endRequest()
void SimpleATTarget1::endRequest () inline
Definition at line 123 of file SimpleATTarget1.h.
References ACCEPT_DELAY, tlm::END_REQ, mBeginResponseEvent, mEndRequestEvent, mEndRequestQueue, mResponseQueue, sc_core::sc_event::notify(), MipsISA::r, RESPONSE_DELAY, sc_core::SC_ZERO_TIME, ArmISA::t, and tlm::TLM_ACCEPTED.
Referenced by SimpleATTarget1().
endResponse()
void SimpleATTarget1::endResponse () inline
Definition at line 185 of file SimpleATTarget1.h.
References mBeginResponseEvent, mResponseQueue, sc_core::sc_event::notify(), and RESPONSE_DELAY.
Referenced by SimpleATTarget1().
myNBTransport()
sync_enum_type SimpleATTarget1::myNBTransport (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline
Definition at line 73 of file SimpleATTarget1.h.
References ACCEPT_DELAY, tlm::tlm_generic_payload::acquire(), tlm::BEGIN_REQ, data, tlm::END_RESP, X86ISA::exit, tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_data_ptr(), mEndRequestEvent, mEndRequestQueue, mEndResponseEvent, mMem, sc_core::sc_object::name(), sc_core::sc_event::notify(), sc_core::sc_time_stamp(), tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, and tlm::TLM_WRITE_COMMAND.
Referenced by SimpleATTarget1().
SC_HAS_PROCESS()
SimpleATTarget1::SC_HAS_PROCESS (SimpleATTarget1)
Member Data Documentation
ACCEPT_DELAY
const sc_core::sc_time SimpleATTarget1::ACCEPT_DELAY private
Definition at line 199 of file SimpleATTarget1.h.
Referenced by endRequest(), and myNBTransport().
mBeginResponseEvent
sc_core::sc_event SimpleATTarget1::mBeginResponseEvent private
Definition at line 207 of file SimpleATTarget1.h.
Referenced by endRequest(), endResponse(), and SimpleATTarget1().
mEndRequestEvent
sc_core::sc_event SimpleATTarget1::mEndRequestEvent private
Definition at line 205 of file SimpleATTarget1.h.
Referenced by endRequest(), myNBTransport(), and SimpleATTarget1().
mEndRequestQueue
std::queue<transaction_type*> SimpleATTarget1::mEndRequestQueue private
Definition at line 204 of file SimpleATTarget1.h.
Referenced by endRequest(), and myNBTransport().
mEndResponseEvent
sc_core::sc_event SimpleATTarget1::mEndResponseEvent private
Definition at line 208 of file SimpleATTarget1.h.
Referenced by beginResponse(), myNBTransport(), and SimpleATTarget1().
mMem
unsigned char SimpleATTarget1::mMem[400] private
Definition at line 203 of file SimpleATTarget1.h.
Referenced by beginResponse(), and myNBTransport().
mResponseQueue
std::queue<transaction_type*> SimpleATTarget1::mResponseQueue private
Definition at line 206 of file SimpleATTarget1.h.
Referenced by beginResponse(), endRequest(), and endResponse().
RESPONSE_DELAY
const sc_core::sc_time SimpleATTarget1::RESPONSE_DELAY private
Definition at line 200 of file SimpleATTarget1.h.
Referenced by endRequest(), and endResponse().
socket
target_socket_type SimpleATTarget1::socket
Definition at line 40 of file SimpleATTarget1.h.
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleATTarget1.h