gem5: MathExprPowerModel Class Reference
MathExprPowerModel Class Reference
A Equation power model.
#include <mathexpr_powermodel.hh>
Public Types
typedef MathExprPowerModelParams Params
Public Types inherited from PowerModelState
typedef PowerModelStateParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MathExprPowerModel (const Params *p)
double getDynamicPower () const
Get the dynamic power consumption.
double getStaticPower () const
Get the static power consumption.
double getStatValue (const std::string &name) const
Get the value for a variable (maps to a stat)
void startup ()
startup() is the final initialization call before simulation.
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from PowerModelState
PowerModelState (const Params *p)
virtual void setTemperature (double temp)
Temperature update.
void setClockedObject (ClockedObject *clkobj)
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
double eval (const MathExpr &expr) const
Evaluate an expression in the context of this object, fatal if evaluation fails.
double tryEval (const MathExpr &expr) const
Evaluate an expression in the context of this object, set failed if evaluation failed.
Private Attributes
MathExpr dyn_expr
MathExpr st_expr
std::string basename
std::unordered_map< std::string, Stats::Info * > stats_map
bool failed
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from PowerModelState
Stats::Value dynamicPower
Stats::Value staticPower
double _temp
Current temperature.
ClockedObject * clocked_object
The clocked object we belong to.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
A Equation power model.
The power is represented as a combination of some stats and automatic variables (like temperature).
Definition at line 57 of file mathexpr_powermodel.hh.
Member Typedef Documentation
Params
typedef MathExprPowerModelParams MathExprPowerModel::Params
Definition at line 61 of file mathexpr_powermodel.hh.
Constructor & Destructor Documentation
MathExprPowerModel()
MathExprPowerModel::MathExprPowerModel (const Params * p)
Definition at line 50 of file mathexpr_powermodel.cc.
References basename, ArmISA::i, SimObject::name(), Serializable::path, and tokenize().
Referenced by regStats().
Member Function Documentation
eval()
double MathExprPowerModel::eval (const MathExpr & expr) const private
Evaluate an expression in the context of this object, fatal if evaluation fails.
Parameters
expr Expression to evaluate
Returns
Value of expression.
Definition at line 95 of file mathexpr_powermodel.cc.
References failed, panic_if, MathExpr::toStr(), and tryEval().
getDynamicPower()
double MathExprPowerModel::getDynamicPower () const inline virtual
Get the dynamic power consumption.
Returns
Power (Watts) consumed by this object (dynamic component)
Implements PowerModelState.
Definition at line 69 of file mathexpr_powermodel.hh.
getStaticPower()
double MathExprPowerModel::getStaticPower () const inline virtual
Get the static power consumption.
Returns
Power (Watts) consumed by this object (static component)
Implements PowerModelState.
Definition at line 76 of file mathexpr_powermodel.hh.
References name().
getStatValue()
double MathExprPowerModel::getStatValue (const std::string & name) const
Get the value for a variable (maps to a stat)
Parameters
name Name of the variable to retrieve the value from
Returns
Power (Watts) consumed by this object (static component)
Definition at line 121 of file mathexpr_powermodel.cc.
References PowerModelState::_temp, PowerModelState::clocked_object, Clocked::clockPeriod(), failed, ArmISA::fi, panic, PowerISA::si, stats_map, Clocked::voltage(), and warn.
Referenced by tryEval().
regStats()
void MathExprPowerModel::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 155 of file mathexpr_powermodel.cc.
References MathExprPowerModel(), and PowerModelState::regStats().
startup()
void MathExprPowerModel::startup () virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 63 of file mathexpr_powermodel.cc.
References basename, dyn_expr, failed, fatal, ArmISA::i, MipsISA::p, SimObject::params(), st_expr, stats_map, Stats::statsList(), and tryEval().
tryEval()
double MathExprPowerModel::tryEval (const MathExpr & expr) const private
Evaluate an expression in the context of this object, set failed if evaluation failed.
Parameters
expr Expression to evaluate
Returns
Value of expression.
Definition at line 108 of file mathexpr_powermodel.cc.
References MathExpr::eval(), failed, and getStatValue().
Referenced by eval(), and startup().
Member Data Documentation
basename
std::string MathExprPowerModel::basename private
Definition at line 114 of file mathexpr_powermodel.hh.
Referenced by MathExprPowerModel(), and startup().
dyn_expr
MathExpr MathExprPowerModel::dyn_expr private
Definition at line 111 of file mathexpr_powermodel.hh.
Referenced by startup().
failed
bool MathExprPowerModel::failed mutable private
Definition at line 121 of file mathexpr_powermodel.hh.
Referenced by eval(), getStatValue(), startup(), and tryEval().
st_expr
MathExpr MathExprPowerModel::st_expr private
Definition at line 111 of file mathexpr_powermodel.hh.
Referenced by startup().
stats_map
std::unordered_map<std::string, Stats::Info*> MathExprPowerModel::stats_map private
Definition at line 117 of file mathexpr_powermodel.hh.
Referenced by getStatValue(), and startup().
The documentation for this class was generated from the following files:
sim/power/mathexpr_powermodel.hh
sim/power/mathexpr_powermodel.cc