gem5: sc_dt::sc_fxnum_bitref Class Reference
sc_dt::sc_fxnum_bitref Class Reference
#include <sc_fxnum.hh>
Public Member Functions
sc_fxnum_bitref (const sc_fxnum_bitref &)
operator bool () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
Private Member Functions
bool get () const
void set (bool)
sc_fxnum_bitref (sc_fxnum &, int)
sc_fxnum_bitref ()
Private Attributes
sc_fxnum & m_num
int m_idx
Friends
class sc_fxnum
class sc_fxnum_fast_bitref
Detailed Description
Definition at line 97 of file sc_fxnum.hh.
Constructor & Destructor Documentation
sc_fxnum_bitref() [1/3]
sc_dt::sc_fxnum_bitref::sc_fxnum_bitref (sc_fxnum & num_, int idx_) inline private
Definition at line 1207 of file sc_fxnum.hh.
sc_fxnum_bitref() [2/3]
sc_dt::sc_fxnum_bitref::sc_fxnum_bitref (const sc_fxnum_bitref & a) inline
Definition at line 1212 of file sc_fxnum.hh.
References ArmISA::a, ArmISA::b, get(), sc_dt::sc_fxnum_fast_bitref::get(), m_num, sc_dt::sc_fxnum_fast_bitref::m_num, sc_dt::operator&=(), sc_dt::operator^=(), sc_dt::operator|=(), SC_FXNUM_FAST_OBSERVER_READ_, SC_FXNUM_OBSERVER_READ_, and SC_FXNUM_OBSERVER_WRITE_.
sc_fxnum_bitref() [3/3]
sc_dt::sc_fxnum_bitref::sc_fxnum_bitref () private
Member Function Documentation
dump()
void sc_dt::sc_fxnum_bitref::dump (::std::ostream & os = ::std::cout) const
Definition at line 83 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::dump(), m_idx, and m_num.
get()
bool sc_dt::sc_fxnum_bitref::get () const private
Definition at line 68 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::get_bit(), m_idx, and m_num.
Referenced by sc_fxnum_bitref(), and sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref().
operator bool()
sc_dt::sc_fxnum_bitref::operator bool () const inline
Definition at line 1370 of file sc_fxnum.hh.
References m_num, and SC_FXNUM_OBSERVER_READ_.
print()
void sc_dt::sc_fxnum_bitref::print (::std::ostream & os = ::std::cout) const
Definition at line 72 of file sc_fxnum.cc.
Referenced by sc_dt::operator<<().
scan()
void sc_dt::sc_fxnum_bitref::scan (::std::istream & is = ::std::cin)
Definition at line 75 of file sc_fxnum.cc.
References ArmISA::b.
Referenced by sc_dt::operator>>().
set()
void sc_dt::sc_fxnum_bitref::set (bool high) private
Definition at line 69 of file sc_fxnum.cc.
References m_idx, m_num, and sc_dt::sc_fxnum::set_bit().
Friends And Related Function Documentation
sc_fxnum
friend class sc_fxnum friend
Definition at line 99 of file sc_fxnum.hh.
sc_fxnum_fast_bitref
friend class sc_fxnum_fast_bitref friend
Definition at line 100 of file sc_fxnum.hh.
Member Data Documentation
m_idx
int sc_dt::sc_fxnum_bitref::m_idx private
Definition at line 141 of file sc_fxnum.hh.
Referenced by dump(), sc_dt::sc_fxnum_fast_bitref::dump(), get(), sc_dt::sc_fxnum_fast_bitref::get(), set(), and sc_dt::sc_fxnum_fast_bitref::set().
m_num
sc_fxnum& sc_dt::sc_fxnum_bitref::m_num private
Definition at line 140 of file sc_fxnum.hh.
Referenced by dump(), sc_dt::sc_fxnum_fast_bitref::dump(), sc_dt::sc_fxnum_subref::dump(), sc_dt::sc_fxnum_fast_subref::dump(), get(), sc_dt::sc_fxnum_fast_bitref::get(), sc_dt::sc_fxnum_subref::get(), sc_dt::sc_fxnum_fast_subref::get(), operator bool(), sc_fxnum_bitref(), sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref(), set(), sc_dt::sc_fxnum_fast_bitref::set(), sc_dt::sc_fxnum_subref::set(), and sc_dt::sc_fxnum_fast_subref::set().
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum.hh
systemc/dt/fx/sc_fxnum.cc