gem5: Bridge::BridgeMasterPort Class Reference
Bridge::BridgeMasterPort Class Reference
Port on the side that forwards requests and receives responses.
#include <bridge.hh>
Public Member Functions
BridgeMasterPort (const std::string &_name, Bridge &_bridge, BridgeSlavePort &_slavePort, Cycles _delay, int _req_limit)
Constructor for the BridgeMasterPort.
bool reqQueueFull () const
Is this side blocked from accepting new request packets.
void schedTimingReq (PacketPtr pkt, Tick when)
Queue a request packet to be sent out later and also schedule a send if necessary.
bool trySatisfyFunctional (PacketPtr pkt)
Check a functional request against the packets in our request queue.
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
bool recvTimingResp (PacketPtr pkt)
When receiving a timing request from the peer port, pass it to the bridge.
void recvReqRetry ()
When receiving a retry request from the peer port, pass it to the bridge.
Protected Member Functions inherited from MasterPort
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Member Functions
void trySendTiming ()
Handle send event, scheduled when the packet at the head of the outbound queue is ready to transmit (for timing accesses only).
Private Attributes
Bridge & bridge
The bridge to which this port belongs.
BridgeSlavePort & slavePort
The slave port on the other side of the bridge.
const Cycles delay
Minimum delay though this bridge.
std::deque< DeferredPacket > transmitList
Request packet queue.
const unsigned int reqQueueLimit
Max queue size for request packets.
EventFunctionWrapper sendEvent
Send event for the request queue.
Additional Inherited Members
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Port on the side that forwards requests and receives responses.
The master port has a buffer for the requests not yet sent.
Definition at line 223 of file bridge.hh.
Constructor & Destructor Documentation
BridgeMasterPort()
Bridge::BridgeMasterPort::BridgeMasterPort (const std::string & _name, Bridge & _bridge, BridgeSlavePort & _slavePort, Cycles _delay, int _req_limit)
Constructor for the BridgeMasterPort.
Parameters
_name the port name including the owner
_bridge the structural owner
_slavePort the slave port on the other side of the bridge
_delay the delay in cycles from receiving to sending
_req_limit the size of the request queue
Definition at line 69 of file bridge.cc.
References trySendTiming().
Member Function Documentation
recvReqRetry()
void Bridge::BridgeMasterPort::recvReqRetry () protected virtual
When receiving a retry request from the peer port, pass it to the bridge.
Implements TimingRequestProtocol.
Definition at line 329 of file bridge.cc.
recvTimingResp()
bool Bridge::BridgeMasterPort::recvTimingResp (PacketPtr pkt) protected virtual
When receiving a timing request from the peer port, pass it to the bridge.
Implements TimingRequestProtocol.
Definition at line 124 of file bridge.cc.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), Packet::headerDelay, Packet::payloadDelay, Bridge::BridgeSlavePort::schedTimingResp(), and Bridge::slavePort.
reqQueueFull()
bool Bridge::BridgeMasterPort::reqQueueFull () const
Is this side blocked from accepting new request packets.
Returns
true if the occupied space has reached the set limit
Definition at line 118 of file bridge.cc.
Referenced by Bridge::BridgeSlavePort::recvTimingReq(), and Bridge::BridgeSlavePort::trySendTiming().
schedTimingReq()
void Bridge::BridgeMasterPort::schedTimingReq (PacketPtr pkt, Tick when)
Queue a request packet to be sent out later and also schedule a send if necessary.
Parameters
pkt a request to send out after a delay
when tick when response packet should be sent
Definition at line 216 of file bridge.cc.
References ArmISA::sendEvent().
Referenced by Bridge::BridgeSlavePort::recvTimingReq().
trySatisfyFunctional()
bool Bridge::BridgeMasterPort::trySatisfyFunctional (PacketPtr pkt)
Check a functional request against the packets in our request queue.
Parameters
pkt packet to check against
Returns
true if we find a match
Definition at line 374 of file bridge.cc.
References ArmISA::i, Packet::makeResponse(), and Packet::trySatisfyFunctional().
Referenced by Bridge::BridgeSlavePort::recvFunctional().
trySendTiming()
void Bridge::BridgeMasterPort::trySendTiming () private
Handle send event, scheduled when the packet at the head of the outbound queue is ready to transmit (for timing accesses only).
Definition at line 247 of file bridge.cc.
References curTick(), DPRINTF, Packet::getAddr(), Bridge::BridgeSlavePort::retryStalledReq(), ArmISA::sendEvent(), Bridge::slavePort, and Bridge::DeferredPacket::tick.
Referenced by BridgeMasterPort().
Member Data Documentation
bridge
Bridge& Bridge::BridgeMasterPort::bridge private
The bridge to which this port belongs.
Definition at line 229 of file bridge.hh.
delay
const Cycles Bridge::BridgeMasterPort::delay private
Minimum delay though this bridge.
Definition at line 237 of file bridge.hh.
reqQueueLimit
const unsigned int Bridge::BridgeMasterPort::reqQueueLimit private
Max queue size for request packets.
Definition at line 248 of file bridge.hh.
sendEvent
EventFunctionWrapper Bridge::BridgeMasterPort::sendEvent private
Send event for the request queue.
Definition at line 258 of file bridge.hh.
slavePort
BridgeSlavePort& Bridge::BridgeMasterPort::slavePort private
The slave port on the other side of the bridge.
Definition at line 234 of file bridge.hh.
transmitList
std::deque<DeferredPacket> Bridge::BridgeMasterPort::transmitList private
Request packet queue.
Request packets are held in this queue for a specified delay to model the processing delay of the bridge. We use a deque as we need to iterate over the items for functional accesses.
Definition at line 245 of file bridge.hh.
The documentation for this class was generated from the following files:
mem/bridge.hh
mem/bridge.cc