gem5: sc_core::sc_attr_cltn Class Reference
sc_core::sc_attr_cltn Class Reference
#include <sc_attr.hh>
Public Types
typedef sc_attr_base * elem_type
typedef std::vector< elem_type >::iterator iterator
typedef std::vector< elem_type >::const_iterator const_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
sc_attr_cltn ()
sc_attr_cltn (const sc_attr_cltn &)
~sc_attr_cltn ()
bool push_back (sc_attr_base *)
sc_attr_base * operator[] (const std::string &name)
const sc_attr_base * operator[] (const std::string &name) const
sc_attr_base * remove (const std::string &name)
void remove_all ()
int size () const
Private Member Functions
sc_attr_cltn & operator= (const sc_attr_cltn &)
Private Attributes
std::vector< sc_attr_base * > cltn
Detailed Description
Definition at line 76 of file sc_attr.hh.
Member Typedef Documentation
const_iterator
typedef std::vector<elem_type>::const_iterator sc_core::sc_attr_cltn::const_iterator
Definition at line 81 of file sc_attr.hh.
elem_type
typedef sc_attr_base* sc_core::sc_attr_cltn::elem_type
Definition at line 79 of file sc_attr.hh.
iterator
typedef std::vector<elem_type>::iterator sc_core::sc_attr_cltn::iterator
Definition at line 80 of file sc_attr.hh.
Constructor & Destructor Documentation
sc_attr_cltn() [1/2]
sc_core::sc_attr_cltn::sc_attr_cltn ()
Definition at line 67 of file sc_attr.cc.
sc_attr_cltn() [2/2]
sc_core::sc_attr_cltn::sc_attr_cltn (const sc_attr_cltn & other)
Definition at line 68 of file sc_attr.cc.
~sc_attr_cltn()
sc_core::sc_attr_cltn::~sc_attr_cltn ()
Definition at line 69 of file sc_attr.cc.
Member Function Documentation
begin() [1/2]
sc_attr_cltn::iterator sc_core::sc_attr_cltn::begin ()
Definition at line 44 of file sc_attr.cc.
begin() [2/2]
sc_attr_cltn::const_iterator sc_core::sc_attr_cltn::begin () const
Definition at line 50 of file sc_attr.cc.
end() [1/2]
sc_attr_cltn::iterator sc_core::sc_attr_cltn::end ()
Definition at line 56 of file sc_attr.cc.
end() [2/2]
sc_attr_cltn::const_iterator sc_core::sc_attr_cltn::end () const
Definition at line 62 of file sc_attr.cc.
operator=()
sc_attr_cltn& sc_core::sc_attr_cltn::operator= (const sc_attr_cltn &) private
operator[]() [1/2]
sc_attr_base * sc_core::sc_attr_cltn::operator[] (const std::string & name)
Definition at line 82 of file sc_attr.cc.
References ArmISA::attr, cltn, and name().
operator[]() [2/2]
const sc_attr_base * sc_core::sc_attr_cltn::operator[] (const std::string & name) const
Definition at line 91 of file sc_attr.cc.
References ArmISA::attr, cltn, and name().
push_back()
bool sc_core::sc_attr_cltn::push_back (sc_attr_base * attr)
Definition at line 72 of file sc_attr.cc.
References cltn, and sc_core::sc_attr_base::name().
Referenced by sc_gem5::Object::add_attribute().
remove()
sc_attr_base * sc_core::sc_attr_cltn::remove (const std::string & name)
Definition at line 100 of file sc_attr.cc.
References ArmISA::attr, cltn, and name().
Referenced by sc_gem5::Object::remove_attribute().
remove_all()
void sc_core::sc_attr_cltn::remove_all ()
Definition at line 113 of file sc_attr.cc.
References cltn.
Referenced by sc_gem5::Object::remove_all_attributes().
size()
int sc_core::sc_attr_cltn::size () const
Definition at line 115 of file sc_attr.cc.
References cltn.
Referenced by sc_gem5::Object::num_attributes().
Member Data Documentation
cltn
std::vector<sc_attr_base *> sc_core::sc_attr_cltn::cltn private
Definition at line 112 of file sc_attr.hh.
Referenced by operator[](), push_back(), remove(), remove_all(), and size().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_attr.hh
systemc/core/sc_attr.cc