gem5: SimpleFreeList Class Reference
SimpleFreeList Class Reference
Free list for a single class of registers (e.g., integer or floating point).
#include <free_list.hh>
Public Member Functions
SimpleFreeList ()
void addReg (PhysRegIdPtr reg)
Add a physical register to the free list.
template<class InputIt >
void addRegs (InputIt first, InputIt last)
Add physical registers to the free list.
PhysRegIdPtr getReg ()
Get the next available register from the free list.
unsigned numFreeRegs () const
Return the number of free registers on the list.
bool hasFreeRegs () const
True iff there are free registers on the list.
Private Attributes
std::queue< PhysRegIdPtr > freeRegs
The actual free list.
Detailed Description
Free list for a single class of registers (e.g., integer or floating point).
Because the register class is implicitly determined by the rename map instance being accessed, all architectural register index parameters and values in this class are relative (e.g., fp2 is just index 2).
Definition at line 64 of file free_list.hh.
Constructor & Destructor Documentation
SimpleFreeList()
SimpleFreeList::SimpleFreeList () inline
Definition at line 73 of file free_list.hh.
Member Function Documentation
addReg()
void SimpleFreeList::addReg (PhysRegIdPtr reg) inline
Add a physical register to the free list.
Definition at line 76 of file free_list.hh.
Referenced by UnifiedFreeList::addCCReg(), UnifiedFreeList::addFloatReg(), UnifiedFreeList::addIntReg(), UnifiedFreeList::addVecElem(), UnifiedFreeList::addVecPredReg(), UnifiedFreeList::addVecReg(), and UnifiedFreeList::getCCReg().
addRegs()
template<class InputIt > void SimpleFreeList::addRegs (InputIt first, InputIt last) inline
Add physical registers to the free list.
Definition at line 81 of file free_list.hh.
References X86ISA::reg.
Referenced by UnifiedFreeList::getCCReg().
getReg()
PhysRegIdPtr SimpleFreeList::getReg () inline
Get the next available register from the free list.
Definition at line 88 of file free_list.hh.
Referenced by UnifiedFreeList::getCCReg(), UnifiedFreeList::getFloatReg(), UnifiedFreeList::getIntReg(), UnifiedFreeList::getVecElem(), UnifiedFreeList::getVecPredReg(), UnifiedFreeList::getVecReg(), and SimpleRenameMap::rename().
hasFreeRegs()
bool SimpleFreeList::hasFreeRegs () const inline
True iff there are free registers on the list.
Definition at line 100 of file free_list.hh.
Referenced by UnifiedFreeList::hasFreeCCRegs(), UnifiedFreeList::hasFreeFloatRegs(), UnifiedFreeList::hasFreeIntRegs(), UnifiedFreeList::hasFreeVecElems(), UnifiedFreeList::hasFreeVecPredRegs(), and UnifiedFreeList::hasFreeVecRegs().
numFreeRegs()
unsigned SimpleFreeList::numFreeRegs () const inline
Return the number of free registers on the list.
Definition at line 97 of file free_list.hh.
Referenced by UnifiedFreeList::numFreeCCRegs(), SimpleRenameMap::numFreeEntries(), UnifiedFreeList::numFreeFloatRegs(), UnifiedFreeList::numFreeIntRegs(), UnifiedFreeList::numFreeVecElems(), UnifiedFreeList::numFreeVecPredRegs(), and UnifiedFreeList::numFreeVecRegs().
Member Data Documentation
freeRegs
std::queue<PhysRegIdPtr> SimpleFreeList::freeRegs private
The actual free list.
Definition at line 69 of file free_list.hh.
The documentation for this class was generated from the following file:
cpu/o3/free_list.hh