gem5: LinuxMipsSystem Class Reference
LinuxMipsSystem Class Reference
This class contains linux specific system code (Loading, Events).
#include <system.hh>
Classes
class PrintThreadInfo
class SkipDelayLoopEvent
Public Types
typedef LinuxMipsSystemParams Params
Public Types inherited from MipsSystem
typedef MipsSystemParams Params
Public Types inherited from System
typedef SystemParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Addr InitStack () const
Addr EmptyPGT () const
Addr EmptyPGE () const
Addr ZeroPGE () const
Addr StartAddr () const
Addr Param () const
Addr CommandLine () const
Addr InitrdStart () const
Addr InitrdSize () const
LinuxMipsSystem (Params *p)
~LinuxMipsSystem ()
void setDelayLoop (ThreadContext *tc)
Public Member Functions inherited from MipsSystem
MipsSystem (Params *p)
~MipsSystem ()
virtual bool breakpoint ()
void setMipsAccess (Addr access)
Set the m5MipsAccess pointer in the console.
Public Member Functions inherited from System
void init () override
After all objects have been created and all ports are connected, check that the system port is connected.
MasterPort & getSystemPort ()
Get a reference to the system port that can be used by non-structural simulation objects like processes or threads, or external entities like loaders and debuggers, etc, to access the memory system.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Additional function to return the Port of a memory object.
unsigned int cacheLineSize () const
Get the cache line size of the system.
bool schedule (PCEvent *event) override
bool remove (PCEvent *event) override
ThreadContext * getThreadContext (ContextID tid) const
unsigned numContexts () const
int numRunningContexts ()
Return number of running (non-halted) thread contexts in system.
KvmVM * getKvmVM ()
Get a pointer to the Kernel Virtual Machine (KVM) SimObject, if present.
bool validKvmEnvironment () const
Verify gem5 configuration will support KVM emulation.
PhysicalMemory & getPhysMem ()
Get a pointer to access the physical memory of the system.
Addr freeMemSize () const
Amount of physical memory that is still free.
Addr memSize () const
Amount of physical memory that exists.
bool isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
Arch getArch () const
Get the architecture.
ByteOrder getGuestByteOrder () const
Get the guest byte order.
Addr getPageBytes () const
Get the page bytes for the ISA.
Addr getPageShift () const
Get the number of bits worth of in-page address for the ISA.
ThermalModel * getThermalModel () const
The thermal model used for this system (if any).
MasterID getMasterId (const SimObject *master, std::string submaster=std::string())
Request an id used to create a request object in the system.
MasterID getGlobalMasterId (const std::string &master_name)
Registers a GLOBAL MasterID, which is a MasterID not related to any particular SimObject; since no SimObject is passed, the master gets registered by providing the full master name.
std::string getMasterName (MasterID master_id)
Get the name of an object for a given request id.
MasterID lookupMasterId (const SimObject *obj) const
Looks up the MasterID for a given SimObject returns an invalid MasterID (invldMasterId) if not found.
MasterID lookupMasterId (const std::string &name) const
Looks up the MasterID for a given object name string returns an invalid MasterID (invldMasterId) if not found.
MasterID maxMasters ()
Get the number of masters registered in the system.
void regStats () override
Callback to set stat parameters.
uint64_t incWorkItemsBegin ()
Called by pseudo_inst to track the number of work items started by this system.
uint64_t incWorkItemsEnd ()
Called by pseudo_inst to track the number of work items completed by this system.
int markWorkItem (int index)
Called by pseudo_inst to mark the cpus actively executing work items.
void workItemBegin (uint32_t tid, uint32_t workid)
void workItemEnd (uint32_t tid, uint32_t workid)
bool breakpoint ()
System (Params *p)
~System ()
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
const Params * params () const
Addr getKernelStart () const
Returns the address the kernel starts at.
Addr getKernelEnd () const
Returns the address the kernel ends at.
Addr getKernelEntry () const
Returns the address the entry point to the kernel code.
Addr allocPhysPages (int npages)
Allocate npages contiguous unused physical pages.
ContextID registerThreadContext (ThreadContext *tc, ContextID assigned=InvalidContextID)
void replaceThreadContext (ThreadContext *tc, ContextID context_id)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
bool isAtomicMode () const
Is the system in atomic mode?
bool isTimingMode () const
Is the system in timing mode?
bool bypassCaches () const
Should caches be bypassed?
Enums::MemoryMode getMemoryMode () const
Get the memory mode of the system.
void setMemoryMode (Enums::MemoryMode mode)
Change the memory mode of the system.
template<class T , typename... Args>
T * addFuncEvent (const SymbolTable *symtab, const char *lbl, const std::string &desc, Args... args)
Add a function-based event to the given function, to be looked up in the specified symbol table.
template<class T >
T * addFuncEvent (const SymbolTable *symtab, const char *lbl)
template<class T , typename... Args>
T * addFuncEventOrPanic (const SymbolTable *symtab, const char *lbl, Args... args)
template<class T , typename... Args>
T * addKernelFuncEvent (const char *lbl, Args... args)
Add a function-based event to a kernel symbol.
template<class T , typename... Args>
T * addKernelFuncEventOrPanic (const char *lbl, Args... args)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Attributes
static const int CommandLineSize = 256
Static Public Attributes inherited from System
static std::vector< System * > systemList
static int numSystemsRunning = 0
static const int maxPID = 32768
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Private Attributes
Addr KernelStart
Addresses defining where the kernel bootloader places various elements.
Additional Inherited Members
Static Public Member Functions inherited from System
static void printSystems ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from MipsSystem
SymbolTable * consoleSymtab
console symbol table
ObjectFile * console
Object pointer for the console code.
Public Attributes inherited from System
std::vector< ThreadContext * > threadContexts
const bool multiThread
Addr pagePtr
uint64_t init_param
PortProxy physProxy
Port to physical memory used for writing object files into ram at boot.
SymbolTable * kernelSymtab
kernel symbol table
ObjectFile * kernel
Object pointer for the kernel code.
MemoryImage kernelImage
std::vector< ObjectFile * > kernelExtras
Additional object files.
Addr kernelStart
Beginning of kernel code.
Addr kernelEnd
End of kernel code.
Addr kernelEntry
Entry point in the kernel to start at.
Addr loadAddrMask
Mask that should be anded for binary/symbol loading.
Addr loadAddrOffset
Offset that should be used for binary/symbol loading.
std::vector< BaseRemoteGDB * > remoteGDB
Counter totalNumInsts
std::map< std::pair< uint32_t, uint32_t >, Tick > lastWorkItemStarted
std::map< uint32_t, Stats::Histogram * > workItemStats
FutexMap futexMap
std::set< int > PIDs
Process set to track which PIDs have already been allocated.
std::list< BasicSignal > signalList
std::vector< RedirectPath * > redirectPaths
Protected Member Functions inherited from MipsSystem
const Params * params () const
virtual Addr fixFuncEventAddr (Addr addr)
Fix up an address used to match PCs for hooking simulator events on to target function executions.
Protected Member Functions inherited from System
std::string stripSystemName (const std::string &master_name) const
Strips off the system name from a master name.
MasterID _getMasterId (const SimObject *master, const std::string &master_name)
helper function for getMasterId
std::string leafMasterName (const SimObject *master, const std::string &submaster)
Helper function for constructing the full (sub)master name by providing the root master and the relative submaster name.
virtual void serializeSymtab (CheckpointOut &os) const
If needed, serialize additional symbol table entries for a specific subclass of this system.
virtual void unserializeSymtab (CheckpointIn &cp)
If needed, unserialize additional symbol table entries for a specific subclass of this system.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from System
KvmVM *const kvmVM
PhysicalMemory physmem
Enums::MemoryMode memoryMode
const unsigned int _cacheLineSize
uint64_t workItemsBegin
uint64_t workItemsEnd
uint32_t numWorkIds
std::vector< bool > activeCpus
std::vector< MasterInfo > masters
This array is a per-system list of all devices capable of issuing a memory system request and an associated string for each master id.
ThermalModel * thermalModel
Params * _params
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
This class contains linux specific system code (Loading, Events).
It points to objects that are the system binaries to load and patches them appropriately to work in simulator.
Definition at line 51 of file system.hh.
Member Typedef Documentation
Params
typedef LinuxMipsSystemParams LinuxMipsSystem::Params
Definition at line 91 of file system.hh.
Constructor & Destructor Documentation
LinuxMipsSystem()
LinuxMipsSystem::LinuxMipsSystem (Params * p)
Definition at line 64 of file system.cc.
Referenced by LinuxMipsSystem::PrintThreadInfo::process().
~LinuxMipsSystem()
LinuxMipsSystem::~LinuxMipsSystem ()
Definition at line 69 of file system.cc.
Member Function Documentation
CommandLine()
Addr LinuxMipsSystem::CommandLine () const inline
Definition at line 85 of file system.hh.
References Param().
EmptyPGE()
Addr LinuxMipsSystem::EmptyPGE () const inline
Definition at line 80 of file system.hh.
EmptyPGT()
Addr LinuxMipsSystem::EmptyPGT () const inline
Definition at line 79 of file system.hh.
InitrdSize()
Addr LinuxMipsSystem::InitrdSize () const inline
Definition at line 87 of file system.hh.
References Param().
InitrdStart()
Addr LinuxMipsSystem::InitrdStart () const inline
Definition at line 86 of file system.hh.
References Param().
InitStack()
Addr LinuxMipsSystem::InitStack () const inline
Definition at line 78 of file system.hh.
Param()
Addr LinuxMipsSystem::Param () const inline
Definition at line 84 of file system.hh.
References ZeroPGE().
Referenced by CommandLine(), InitrdSize(), and InitrdStart().
setDelayLoop()
void LinuxMipsSystem::setDelayLoop (ThreadContext * tc)
Definition at line 75 of file system.cc.
References panic.
Referenced by LinuxMipsSystem::SkipDelayLoopEvent::process().
StartAddr()
Addr LinuxMipsSystem::StartAddr () const inline
Definition at line 82 of file system.hh.
ZeroPGE()
Addr LinuxMipsSystem::ZeroPGE () const inline
Definition at line 81 of file system.hh.
Referenced by Param().
Member Data Documentation
CommandLineSize
const int LinuxMipsSystem::CommandLineSize = 256 static
Definition at line 88 of file system.hh.
KernelStart
Addr LinuxMipsSystem::KernelStart private
Addresses defining where the kernel bootloader places various elements.
Details found in include/asm-mips/system.h
Definition at line 75 of file system.hh.
The documentation for this class was generated from the following files:
arch/mips/linux/system.hh
arch/mips/linux/system.cc