gem5: CacheMemory Class Reference
CacheMemory Class Reference
#include <CacheMemory.hh>
Public Types
typedef RubyCacheParams Params
typedef std::shared_ptr< ReplacementData > ReplData
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
CacheMemory (const Params *p)
~CacheMemory ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
bool tryCacheAccess (Addr address, RubyRequestType type, DataBlock *&data_ptr)
bool testCacheAccess (Addr address, RubyRequestType type, DataBlock *&data_ptr)
bool isTagPresent (Addr address) const
bool cacheAvail (Addr address) const
AbstractCacheEntry * allocate (Addr address, AbstractCacheEntry *new_entry)
void allocateVoid (Addr address, AbstractCacheEntry *new_entry)
void deallocate (Addr address)
Addr cacheProbe (Addr address) const
AbstractCacheEntry * lookup (Addr address)
const AbstractCacheEntry * lookup (Addr address) const
Cycles getTagLatency () const
Cycles getDataLatency () const
bool isBlockInvalid (int64_t cache_set, int64_t loc)
bool isBlockNotBusy (int64_t cache_set, int64_t loc)
void recordCacheContents (int cntrl, CacheRecorder *tr) const
void setMRU (Addr address)
void setMRU (Addr addr, int occupancy)
int getReplacementWeight (int64_t set, int64_t loc)
void setMRU (const AbstractCacheEntry *e)
void setLocked (Addr addr, int context)
void clearLocked (Addr addr)
bool isLocked (Addr addr, int context)
void print (std::ostream &out) const
void printData (std::ostream &out) const
void regStats ()
Callback to set stat parameters.
bool checkResourceAvailable (CacheResourceType res, Addr addr)
void recordRequestType (CacheRequestType requestType, Addr addr)
int getCacheSize () const
int getCacheAssoc () const
int getNumBlocks () const
Addr getAddressAtIdx (int idx) const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
Stats::Scalar m_demand_hits
Stats::Scalar m_demand_misses
Stats::Formula m_demand_accesses
Stats::Scalar m_sw_prefetches
Stats::Scalar m_hw_prefetches
Stats::Formula m_prefetches
Stats::Vector m_accessModeType
Stats::Scalar numDataArrayReads
Stats::Scalar numDataArrayWrites
Stats::Scalar numTagArrayReads
Stats::Scalar numTagArrayWrites
Stats::Scalar numTagArrayStalls
Stats::Scalar numDataArrayStalls
Private Member Functions
int64_t addressToCacheSet (Addr address) const
int findTagInSet (int64_t line, Addr tag) const
int findTagInSetIgnorePermissions (int64_t cacheSet, Addr tag) const
CacheMemory (const CacheMemory &obj)
CacheMemory & operator= (const CacheMemory &obj)
Private Attributes
bool m_is_instruction_only_cache
std::unordered_map< Addr, int > m_tag_index
std::vector< std::vector< AbstractCacheEntry * > > m_cache
BaseReplacementPolicy * m_replacementPolicy_ptr
We use BaseReplacementPolicy from Classic system here, hence we can use different replacement policies from Classic system in Ruby system.
BankedArray dataArray
BankedArray tagArray
int m_cache_size
int m_cache_num_sets
int m_cache_num_set_bits
int m_cache_assoc
int m_start_index_bit
bool m_resource_stalls
int m_block_size
std::vector< std::vector< ReplData > > replacement_data
We store all the ReplacementData in a 2-dimensional array.
bool m_use_occupancy
Set to true when using WeightedLRU replacement policy, otherwise, set to false.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 51 of file CacheMemory.hh.
Member Typedef Documentation
Params
typedef RubyCacheParams CacheMemory::Params
Definition at line 54 of file CacheMemory.hh.
ReplData
typedef std::shared_ptr<ReplacementData> CacheMemory::ReplData
Definition at line 55 of file CacheMemory.hh.
Constructor & Destructor Documentation
CacheMemory() [1/2]
CacheMemory::CacheMemory (const Params * p)
Definition at line 58 of file CacheMemory.cc.
References m_block_size, m_cache_assoc, m_cache_size, m_is_instruction_only_cache, m_replacementPolicy_ptr, m_resource_stalls, m_start_index_bit, and m_use_occupancy.
Referenced by getNumBlocks().
~CacheMemory()
CacheMemory::~CacheMemory ()
Definition at line 100 of file CacheMemory.cc.
References ArmISA::i, ArmISA::j, m_cache, m_cache_assoc, m_cache_num_sets, and m_replacementPolicy_ptr.
CacheMemory() [2/2]
CacheMemory::CacheMemory (const CacheMemory & obj) private
Member Function Documentation
addressToCacheSet()
int64_t CacheMemory::addressToCacheSet (Addr address) const private
Definition at line 113 of file CacheMemory.cc.
References bitSelect(), m_cache_num_set_bits, m_start_index_bit, and makeLineAddress().
Referenced by allocate(), cacheAvail(), cacheProbe(), checkResourceAvailable(), clearLocked(), deallocate(), getNumBlocks(), isLocked(), isTagPresent(), lookup(), recordRequestType(), setLocked(), setMRU(), testCacheAccess(), and tryCacheAccess().
allocate()
AbstractCacheEntry * CacheMemory::allocate (Addr address, AbstractCacheEntry * new_entry)
Definition at line 267 of file CacheMemory.cc.
References addressToCacheSet(), cacheAvail(), curTick(), DPRINTF, ArmISA::i, isTagPresent(), AbstractCacheEntry::m_Address, m_cache, m_cache_assoc, m_replacementPolicy_ptr, m_tag_index, makeLineAddress(), panic, replacement_data, BaseReplacementPolicy::reset(), and warn_once.
Referenced by allocateVoid().
allocateVoid()
void CacheMemory::allocateVoid (Addr address, AbstractCacheEntry * new_entry) inline
Definition at line 80 of file CacheMemory.hh.
References allocate(), cacheProbe(), deallocate(), and lookup().
cacheAvail()
bool CacheMemory::cacheAvail (Addr address) const
Definition at line 245 of file CacheMemory.cc.
References addressToCacheSet(), ArmISA::i, AbstractCacheEntry::m_Address, m_cache, m_cache_assoc, AbstractCacheEntry::m_Permission, and makeLineAddress().
Referenced by allocate(), and cacheProbe().
cacheProbe()
Addr CacheMemory::cacheProbe (Addr address) const
Definition at line 322 of file CacheMemory.cc.
References addressToCacheSet(), cacheAvail(), ArmISA::i, m_cache, m_cache_assoc, m_replacementPolicy_ptr, makeLineAddress(), and replacement_data.
Referenced by allocateVoid().
checkResourceAvailable()
bool CacheMemory::checkResourceAvailable (CacheResourceType res, Addr addr)
Definition at line 643 of file CacheMemory.cc.
References addressToCacheSet(), dataArray, DPRINTF, m_resource_stalls, numDataArrayStalls, numTagArrayStalls, panic, tagArray, and BankedArray::tryAccess().
Referenced by getDataLatency().
clearLocked()
void CacheMemory::clearLocked (Addr addr)
Definition at line 495 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), m_cache, and makeLineAddress().
Referenced by getDataLatency(), and GPUCoalescer::handleLlsc().
deallocate()
void CacheMemory::deallocate (Addr address)
Definition at line 305 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), BaseReplacementPolicy::invalidate(), isTagPresent(), m_cache, m_replacementPolicy_ptr, m_tag_index, makeLineAddress(), and replacement_data.
Referenced by allocateVoid().
findTagInSet()
int CacheMemory::findTagInSet (int64_t line, Addr tag) const private
Definition at line 123 of file CacheMemory.cc.
References m_cache, m_tag_index, and makeLineAddress().
Referenced by clearLocked(), deallocate(), getNumBlocks(), isLocked(), isTagPresent(), lookup(), setLocked(), setMRU(), testCacheAccess(), and tryCacheAccess().
findTagInSetIgnorePermissions()
int CacheMemory::findTagInSetIgnorePermissions (int64_t cacheSet, Addr tag) const private
Definition at line 138 of file CacheMemory.cc.
References m_tag_index, and makeLineAddress().
Referenced by getNumBlocks().
getAddressAtIdx()
Addr CacheMemory::getAddressAtIdx (int idx) const
Definition at line 153 of file CacheMemory.cc.
References AbstractCacheEntry::m_Address, m_cache, m_cache_assoc, m_cache_num_sets, and AbstractCacheEntry::m_Permission.
Referenced by getNumBlocks(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), and VIPERCoalescer::wbL1().
getCacheAssoc()
int CacheMemory::getCacheAssoc () const inline
Definition at line 147 of file CacheMemory.hh.
References m_cache_assoc.
getCacheSize()
int CacheMemory::getCacheSize () const inline
Definition at line 146 of file CacheMemory.hh.
References m_cache_size.
getDataLatency()
Cycles CacheMemory::getDataLatency () const inline
Definition at line 96 of file CacheMemory.hh.
References addr, checkResourceAvailable(), clearLocked(), dataArray, ArmISA::e, BankedArray::getLatency(), getReplacementWeight(), isBlockInvalid(), isBlockNotBusy(), isLocked(), print(), printData(), recordCacheContents(), recordRequestType(), regStats(), setLocked(), and setMRU().
getNumBlocks()
int CacheMemory::getNumBlocks () const inline
Definition at line 148 of file CacheMemory.hh.
References addressToCacheSet(), CacheMemory(), findTagInSet(), findTagInSetIgnorePermissions(), getAddressAtIdx(), m_cache_assoc, m_cache_num_sets, and operator=().
Referenced by VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), and VIPERCoalescer::wbL1().
getReplacementWeight()
int CacheMemory::getReplacementWeight (int64_t set, int64_t loc)
Definition at line 406 of file CacheMemory.cc.
References m_cache, m_cache_assoc, and m_cache_num_sets.
Referenced by getDataLatency().
getTagLatency()
Cycles CacheMemory::getTagLatency () const inline
Definition at line 95 of file CacheMemory.hh.
References BankedArray::getLatency(), and tagArray.
init()
void CacheMemory::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 77 of file CacheMemory.cc.
References floorLog2(), RubySystem::getBlockSizeBytes(), ArmISA::i, BaseReplacementPolicy::instantiateEntry(), ArmISA::j, m_block_size, m_cache, m_cache_assoc, m_cache_num_set_bits, m_cache_num_sets, m_cache_size, m_replacementPolicy_ptr, and replacement_data.
isBlockInvalid()
bool CacheMemory::isBlockInvalid (int64_t cache_set, int64_t loc)
Definition at line 673 of file CacheMemory.cc.
References m_cache.
Referenced by getDataLatency().
isBlockNotBusy()
bool CacheMemory::isBlockNotBusy (int64_t cache_set, int64_t loc)
Definition at line 679 of file CacheMemory.cc.
References m_cache.
Referenced by getDataLatency().
isLocked()
bool CacheMemory::isLocked (Addr addr, int context)
Definition at line 506 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), m_cache, and makeLineAddress().
Referenced by getDataLatency(), and GPUCoalescer::handleLlsc().
isTagPresent()
bool CacheMemory::isTagPresent (Addr address) const
Definition at line 226 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), and makeLineAddress().
Referenced by allocate(), deallocate(), GPUCoalescer::handleLlsc(), and GPUCoalescer::hitCallback().
lookup() [1/2]
AbstractCacheEntry * CacheMemory::lookup (Addr address)
Definition at line 342 of file CacheMemory.cc.
References addressToCacheSet(), findTagInSet(), m_cache, and makeLineAddress().
Referenced by allocateVoid(), Sequencer::handleLlsc(), and Sequencer::invalidateSC().
lookup() [2/2]
const AbstractCacheEntry * CacheMemory::lookup (Addr address) const
Definition at line 353 of file CacheMemory.cc.
References addressToCacheSet(), findTagInSet(), m_cache, and makeLineAddress().
operator=()
CacheMemory& CacheMemory::operator= (const CacheMemory & obj) private
Referenced by getNumBlocks().
print()
void CacheMemory::print (std::ostream & out) const
Definition at line 459 of file CacheMemory.cc.
References ArmISA::i, ArmISA::j, m_cache, m_cache_assoc, m_cache_num_sets, and SimObject::name().
Referenced by getDataLatency(), and operator<<().
printData()
void CacheMemory::printData (std::ostream & out) const
Definition at line 478 of file CacheMemory.cc.
Referenced by getDataLatency().
recordCacheContents()
void CacheMemory::recordCacheContents (int cntrl, CacheRecorder * tr) const
Definition at line 420 of file CacheMemory.cc.
References CacheRecorder::addRecord(), DPRINTF, ArmISA::i, ArmISA::j, M5_VAR_USED, m_cache, m_cache_assoc, m_cache_num_sets, m_is_instruction_only_cache, and SimObject::name().
Referenced by getDataLatency().
recordRequestType()
void CacheMemory::recordRequestType (CacheRequestType requestType, Addr addr)
Definition at line 611 of file CacheMemory.cc.
References addressToCacheSet(), dataArray, DPRINTF, m_resource_stalls, numDataArrayReads, numDataArrayWrites, numTagArrayReads, numTagArrayWrites, BankedArray::reserve(), tagArray, and warn.
Referenced by getDataLatency().
regStats()
void CacheMemory::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 518 of file CacheMemory.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), m_accessModeType, m_demand_accesses, m_demand_hits, m_demand_misses, m_hw_prefetches, m_prefetches, m_sw_prefetches, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, numDataArrayReads, numDataArrayStalls, numDataArrayWrites, numTagArrayReads, numTagArrayStalls, numTagArrayWrites, Stats::pdf, Stats::Group::regStats(), Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and Stats::total.
Referenced by getDataLatency().
setLocked()
void CacheMemory::setLocked (Addr addr, int context)
Definition at line 484 of file CacheMemory.cc.
References addressToCacheSet(), DPRINTF, findTagInSet(), m_cache, and makeLineAddress().
Referenced by getDataLatency(), and GPUCoalescer::handleLlsc().
setMRU() [1/3]
void CacheMemory::setMRU (Addr address)
Definition at line 364 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), findTagInSet(), m_cache, m_replacementPolicy_ptr, replacement_data, and BaseReplacementPolicy::touch().
Referenced by getDataLatency(), and GPUCoalescer::hitCallback().
setMRU() [2/3]
void CacheMemory::setMRU (Addr addr, int occupancy)
Definition at line 385 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), findTagInSet(), m_cache, m_replacementPolicy_ptr, m_use_occupancy, and replacement_data.
setMRU() [3/3]
void CacheMemory::setMRU (const AbstractCacheEntry * e)
Definition at line 376 of file CacheMemory.cc.
References curTick(), ReplaceableEntry::getSet(), ReplaceableEntry::getWay(), m_cache, m_replacementPolicy_ptr, replacement_data, and BaseReplacementPolicy::touch().
testCacheAccess()
bool CacheMemory::testCacheAccess (Addr address, RubyRequestType type, DataBlock *& data_ptr)
Definition at line 201 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), DPRINTF, findTagInSet(), AbstractCacheEntry::getDataBlk(), m_cache, m_replacementPolicy_ptr, makeLineAddress(), replacement_data, and BaseReplacementPolicy::touch().
tryCacheAccess()
bool CacheMemory::tryCacheAccess (Addr address, RubyRequestType type, DataBlock *& data_ptr)
Definition at line 173 of file CacheMemory.cc.
References addressToCacheSet(), curTick(), DPRINTF, findTagInSet(), AbstractCacheEntry::getDataBlk(), m_cache, AbstractCacheEntry::m_Permission, m_replacementPolicy_ptr, makeLineAddress(), replacement_data, and BaseReplacementPolicy::touch().
Member Data Documentation
dataArray
BankedArray CacheMemory::dataArray private
Definition at line 179 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), getDataLatency(), and recordRequestType().
m_accessModeType
Stats::Vector CacheMemory::m_accessModeType
Definition at line 136 of file CacheMemory.hh.
Referenced by regStats().
m_block_size
int CacheMemory::m_block_size private
Definition at line 188 of file CacheMemory.hh.
Referenced by CacheMemory(), and init().
m_cache
std::vector<std::vector<AbstractCacheEntry*> > CacheMemory::m_cache private
Definition at line 171 of file CacheMemory.hh.
Referenced by allocate(), cacheAvail(), cacheProbe(), clearLocked(), deallocate(), findTagInSet(), getAddressAtIdx(), getReplacementWeight(), init(), isBlockInvalid(), isBlockNotBusy(), isLocked(), lookup(), print(), recordCacheContents(), setLocked(), setMRU(), testCacheAccess(), tryCacheAccess(), and ~CacheMemory().
m_cache_assoc
int CacheMemory::m_cache_assoc private
Definition at line 185 of file CacheMemory.hh.
Referenced by allocate(), cacheAvail(), CacheMemory(), cacheProbe(), getAddressAtIdx(), getCacheAssoc(), getNumBlocks(), getReplacementWeight(), init(), print(), recordCacheContents(), and ~CacheMemory().
m_cache_num_set_bits
int CacheMemory::m_cache_num_set_bits private
Definition at line 184 of file CacheMemory.hh.
Referenced by addressToCacheSet(), and init().
m_cache_num_sets
int CacheMemory::m_cache_num_sets private
Definition at line 183 of file CacheMemory.hh.
Referenced by getAddressAtIdx(), getNumBlocks(), getReplacementWeight(), init(), print(), recordCacheContents(), and ~CacheMemory().
m_cache_size
int CacheMemory::m_cache_size private
Definition at line 182 of file CacheMemory.hh.
Referenced by CacheMemory(), getCacheSize(), and init().
m_demand_accesses
Stats::Formula CacheMemory::m_demand_accesses
Definition at line 130 of file CacheMemory.hh.
Referenced by regStats().
m_demand_hits
Stats::Scalar CacheMemory::m_demand_hits
Definition at line 128 of file CacheMemory.hh.
Referenced by regStats().
m_demand_misses
Stats::Scalar CacheMemory::m_demand_misses
Definition at line 129 of file CacheMemory.hh.
Referenced by regStats().
m_hw_prefetches
Stats::Scalar CacheMemory::m_hw_prefetches
Definition at line 133 of file CacheMemory.hh.
Referenced by regStats().
m_is_instruction_only_cache
bool CacheMemory::m_is_instruction_only_cache private
Definition at line 166 of file CacheMemory.hh.
Referenced by CacheMemory(), and recordCacheContents().
m_prefetches
Stats::Formula CacheMemory::m_prefetches
Definition at line 134 of file CacheMemory.hh.
Referenced by regStats().
m_replacementPolicy_ptr
BaseReplacementPolicy* CacheMemory::m_replacementPolicy_ptr private
We use BaseReplacementPolicy from Classic system here, hence we can use different replacement policies from Classic system in Ruby system.
Definition at line 177 of file CacheMemory.hh.
Referenced by allocate(), CacheMemory(), cacheProbe(), deallocate(), init(), setMRU(), testCacheAccess(), tryCacheAccess(), and ~CacheMemory().
m_resource_stalls
bool CacheMemory::m_resource_stalls private
Definition at line 187 of file CacheMemory.hh.
Referenced by CacheMemory(), checkResourceAvailable(), and recordRequestType().
m_start_index_bit
int CacheMemory::m_start_index_bit private
Definition at line 186 of file CacheMemory.hh.
Referenced by addressToCacheSet(), and CacheMemory().
m_sw_prefetches
Stats::Scalar CacheMemory::m_sw_prefetches
Definition at line 132 of file CacheMemory.hh.
Referenced by regStats().
m_tag_index
std::unordered_map<Addr, int> CacheMemory::m_tag_index private
Definition at line 170 of file CacheMemory.hh.
Referenced by allocate(), deallocate(), findTagInSet(), and findTagInSetIgnorePermissions().
m_use_occupancy
bool CacheMemory::m_use_occupancy private
Set to true when using WeightedLRU replacement policy, otherwise, set to false.
Definition at line 204 of file CacheMemory.hh.
Referenced by CacheMemory(), and setMRU().
numDataArrayReads
Stats::Scalar CacheMemory::numDataArrayReads
Definition at line 138 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
numDataArrayStalls
Stats::Scalar CacheMemory::numDataArrayStalls
Definition at line 144 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), and regStats().
numDataArrayWrites
Stats::Scalar CacheMemory::numDataArrayWrites
Definition at line 139 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
numTagArrayReads
Stats::Scalar CacheMemory::numTagArrayReads
Definition at line 140 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
numTagArrayStalls
Stats::Scalar CacheMemory::numTagArrayStalls
Definition at line 143 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), and regStats().
numTagArrayWrites
Stats::Scalar CacheMemory::numTagArrayWrites
Definition at line 141 of file CacheMemory.hh.
Referenced by recordRequestType(), and regStats().
replacement_data
std::vector<std::vector<ReplData> > CacheMemory::replacement_data private
We store all the ReplacementData in a 2-dimensional array.
By doing this, we can use all replacement policies from Classic system. Ruby cache will deallocate cache entry every time we evict the cache block so we cannot store the ReplacementData inside the cache entry. Instantiate ReplacementData for multiple times will break replacement policy like TreePLRU.
Definition at line 198 of file CacheMemory.hh.
Referenced by allocate(), cacheProbe(), deallocate(), init(), setMRU(), testCacheAccess(), and tryCacheAccess().
tagArray
BankedArray CacheMemory::tagArray private
Definition at line 180 of file CacheMemory.hh.
Referenced by checkResourceAvailable(), getTagLatency(), and recordRequestType().
The documentation for this class was generated from the following files:
mem/ruby/structures/CacheMemory.hh
mem/ruby/structures/CacheMemory.cc