gem5: ArmKvmCPU Class Reference
ArmKvmCPU Class Reference
ARM implementation of a KVM-based hardware virtualized CPU.
#include <arm_cpu.hh>
Classes
struct KvmCoreMiscRegInfo
struct KvmIntRegInfo
Public Member Functions
ArmKvmCPU (ArmKvmCPUParams *params)
virtual ~ArmKvmCPU ()
void startup ()
startup() is the final initialization call before simulation.
void dump ()
Public Member Functions inherited from BaseKvmCPU
BaseKvmCPU (BaseKvmCPUParams *params)
virtual ~BaseKvmCPU ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void startup () override
startup() is the final initialization call before simulation.
void regStats () override
Callback to set stat parameters.
void serializeThread (CheckpointOut &cp, ThreadID tid) const override
Serialize a single thread.
void unserializeThread (CheckpointIn &cp, ThreadID tid) override
Unserialize one thread.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void notifyFork () override
Notify a child process of a fork.
void switchOut () override
Prepare for another CPU to take over execution.
void takeOverFrom (BaseCPU *cpu) override
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void verifyMemoryMode () const override
Verify that the system is in a memory mode supported by the CPU.
Port & getDataPort () override
Purely virtual method that returns a reference to the data port.
Port & getInstPort () override
Purely virtual method that returns a reference to the instruction port.
void wakeup (ThreadID tid=0) override
void activateContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now active.
void suspendContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now suspended.
void deallocateContext (ThreadID thread_num)
void haltContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now halted.
long getVCpuID () const
ThreadContext * getContext (int tn) override
Given a thread num get tho thread context for it.
Counter totalInsts () const override
Counter totalOps () const override
void finishMMIOPending ()
Callback from KvmCPUPort to transition the CPU out of RunningMMIOPending when all timing requests have completed.
virtual void dump () const
Dump the internal state to the terminal.
void kick () const
Force an exit from KVM.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void regProbePoints () override
Register probe points for this object.
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
typedef std::vector< uint64_t > RegIndexVector
Protected Types inherited from BaseKvmCPU
enum Status {
Idle, Running, RunningService, RunningMMIOPending,
RunningServiceCompletion
}
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Protected Member Functions
Tick kvmRun (Tick ticks)
Request KVM to run the guest for a given number of ticks.
void updateKvmState ()
Update the KVM state from the current thread context.
void updateThreadContext ()
Update the current thread context with the KVM state.
Tick onKvmExitHypercall ()
const RegIndexVector & getRegList () const
Get a list of registers supported by getOneReg() and setOneReg().
void kvmArmVCpuInit (uint32_t target)
void kvmArmVCpuInit (const struct kvm_vcpu_init &init)
ArmISA::MiscRegIndex decodeCoProcReg (uint64_t id) const
ArmISA::MiscRegIndex decodeVFPCtrlReg (uint64_t id) const
bool isInvariantReg (uint64_t id)
Determine if a register is invariant.
Protected Member Functions inherited from BaseKvmCPU
void tick ()
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
virtual uint64_t getHostCycles () const
Get the value of the hardware cycle counter in the guest.
virtual Tick kvmRunDrain ()
Request the CPU to run until draining completes.
struct kvm_run * getKvmRunState ()
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
uint8_t * getGuestData (uint64_t offset) const
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
void kvmNonMaskableInterrupt ()
Send a non-maskable interrupt to the guest.
void kvmInterrupt (const struct kvm_interrupt &interrupt)
Send a normal interrupt to the guest.
std::string getAndFormatOneReg (uint64_t id) const
Get and format one register for printout.
virtual bool archIsDrained () const
Is the architecture specific code in a state that prevents draining?
Tick doMMIOAccess (Addr paddr, void *data, int size, bool write)
Inject a memory mapped IO request into gem5.
int ioctl (int request, long p1) const
vCPU ioctl interface.
int ioctl (int request, void *p1) const
int ioctl (int request) const
void getRegisters (struct kvm_regs &regs) const
Get/Set the register state of the guest vCPU.
void setRegisters (const struct kvm_regs &regs)
void getSpecialRegisters (struct kvm_sregs &regs) const
void setSpecialRegisters (const struct kvm_sregs &regs)
void getFPUState (struct kvm_fpu &state) const
Get/Set the guest FPU/vector state.
void setFPUState (const struct kvm_fpu &state)
void setOneReg (uint64_t id, const void *addr)
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
void setOneReg (uint64_t id, uint64_t value)
void setOneReg (uint64_t id, uint32_t value)
void getOneReg (uint64_t id, void *addr) const
uint64_t getOneRegU64 (uint64_t id) const
uint32_t getOneRegU32 (uint64_t id) const
void syncThreadContext ()
Update a thread context if the KVM state is dirty with respect to the cached thread context.
EventQueue * deviceEventQueue ()
Get a pointer to the event queue owning devices.
void syncKvmState ()
Update the KVM if the thread context is dirty.
virtual Tick handleKvmExit ()
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
virtual Tick handleKvmExitIO ()
The guest performed a legacy IO request (out/inp on x86)
virtual Tick handleKvmExitHypercall ()
The guest requested a monitor service using a hypercall.
virtual Tick handleKvmExitIRQWindowOpen ()
The guest exited because an interrupt window was requested.
virtual Tick handleKvmExitUnknown ()
An unknown architecture dependent error occurred when starting the vCPU.
virtual Tick handleKvmExitException ()
An unhandled virtualization exception occured.
virtual Tick handleKvmExitFailEntry ()
KVM failed to start the virtualized CPU.
void setSignalMask (const sigset_t *mask)
Set the signal mask used in kvmRun()
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Static Protected Attributes
static KvmIntRegInfo kvmIntRegs []
static KvmCoreMiscRegInfo kvmCoreMiscRegs []
Private Member Functions
bool getRegList (struct kvm_reg_list &regs) const
Get a list of registers supported by getOneReg() and setOneReg().
void dumpKvmStateCore ()
void dumpKvmStateMisc ()
void dumpKvmStateCoProc (uint64_t id)
void dumpKvmStateVFP (uint64_t id)
void updateKvmStateCore ()
void updateKvmStateMisc ()
void updateKvmStateCoProc (uint64_t id, bool show_warnings)
void updateKvmStateVFP (uint64_t id, bool show_warnings)
void updateTCStateCore ()
void updateTCStateMisc ()
void updateTCStateCoProc (uint64_t id, bool show_warnings)
void updateTCStateVFP (uint64_t id, bool show_warnings)
Private Attributes
bool irqAsserted
Cached state of the IRQ line.
bool fiqAsserted
Cached state of the FIQ line.
RegIndexVector _regIndexList
Cached copy of the list of co-processor registers supported by KVM.
Static Private Attributes
static const std::set< uint64_t > invariant_regs
List of co-processor registers that KVM requires to be identical on both the host and the guest.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BaseKvmCPU
SimpleThread * thread
A cached copy of a thread's state in the form of a SimpleThread object.
ThreadContext * tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
KvmVM & vm
Counter ctrInsts
Number of instructions executed by the CPU.
Stats::Scalar numInsts
Stats::Scalar numVMExits
Stats::Scalar numVMHalfEntries
Stats::Scalar numExitSignal
Stats::Scalar numMMIO
Stats::Scalar numCoalescedMMIO
Stats::Scalar numIO
Stats::Scalar numHalt
Stats::Scalar numInterrupts
Stats::Scalar numHypercalls
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from BaseKvmCPU
Status _status
CPU run state.
KVMCpuPort dataPort
Port for data requests.
KVMCpuPort instPort
Unused dummy port for the instruction interface.
const bool alwaysSyncTC
Be conservative and always synchronize the thread context on KVM entry/exit.
bool threadContextDirty
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
bool kvmStateDirty
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
const long vcpuID
KVM internal ID of the vCPU.
pthread_t vcpuThread
ID of the vCPU thread.
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
ARM implementation of a KVM-based hardware virtualized CPU.
Architecture specific limitations:
LPAE is currently not supported by gem5. We therefore panic if LPAE is enabled when returning to gem5.
The co-processor based interface to the architected timer is unsupported. We can't support this due to limitations in the KVM API on ARM.
M5 ops are currently not supported. This requires either a kernel hack or a memory mapped device that handles the guest<->m5 interface.
Definition at line 61 of file arm_cpu.hh.
Member Typedef Documentation
RegIndexVector
typedef std::vector<uint64_t> ArmKvmCPU::RegIndexVector protected
Definition at line 90 of file arm_cpu.hh.
Constructor & Destructor Documentation
ArmKvmCPU()
ArmKvmCPU::ArmKvmCPU (ArmKvmCPUParams * params)
Definition at line 245 of file arm_cpu.cc.
Referenced by updateTCStateVFP().
~ArmKvmCPU()
ArmKvmCPU::~ArmKvmCPU () virtual
Definition at line 251 of file arm_cpu.cc.
Member Function Documentation
decodeCoProcReg()
MiscRegIndex ArmKvmCPU::decodeCoProcReg (uint64_t id) const protected
Definition at line 376 of file arm_cpu.cc.
References ArmISA::decodeCP14Reg(), ArmISA::decodeCP15Reg(), AlphaISA::NUM_MISCREGS, ArmISA::opc2, REG_CP, REG_CRM, REG_CRN, REG_IS_32BIT, REG_IS_64BIT, REG_OPC1, REG_OPC2, and warn.
Referenced by dumpKvmStateCoProc(), updateKvmStateCoProc(), and updateTCStateCoProc().
decodeVFPCtrlReg()
ArmISA::MiscRegIndex ArmKvmCPU::decodeVFPCtrlReg (uint64_t id) const protected
Definition at line 411 of file arm_cpu.cc.
References ArmISA::MISCREG_FPEXC, ArmISA::MISCREG_FPSCR, ArmISA::MISCREG_FPSID, ArmISA::MISCREG_MVFR0, ArmISA::MISCREG_MVFR1, AlphaISA::NUM_MISCREGS, REG_IS_ARM, REG_IS_VFP, REG_IS_VFP_CTRL, REG_VFP_REG, and warn_once.
Referenced by dumpKvmStateVFP(), updateKvmStateVFP(), and updateTCStateVFP().
dump()
void ArmKvmCPU::dump ()
Definition at line 291 of file arm_cpu.cc.
References dumpKvmStateCore(), and dumpKvmStateMisc().
dumpKvmStateCoProc()
void ArmKvmCPU::dumpKvmStateCoProc (uint64_t id) private
Definition at line 523 of file arm_cpu.cc.
References decodeCoProcReg(), EXTRACT_FIELD, BaseKvmCPU::getAndFormatOneReg(), BaseKvmCPU::getOneRegU32(), inform, isInvariantReg(), ArmISA::miscRegName, SimObject::name(), AlphaISA::NUM_MISCREGS, ThreadContext::readMiscReg(), ThreadContext::readMiscRegNoEffect(), REG_CP, REG_CRM, REG_CRN, REG_IS_32BIT, REG_IS_ARM, REG_OPC1, REG_OPC2, and BaseKvmCPU::tc.
Referenced by dumpKvmStateMisc().
dumpKvmStateCore()
void ArmKvmCPU::dumpKvmStateCore () private
Definition at line 462 of file arm_cpu.cc.
References BaseKvmCPU::getOneRegU32(), ArmKvmCPU::KvmIntRegInfo::idx, ArmKvmCPU::KvmCoreMiscRegInfo::idx, inform, kvmCoreMiscRegs, kvmIntRegs, ArmISA::miscRegName, ArmISA::NUM_INTREGS, AlphaISA::NUM_MISCREGS, MipsISA::pc, and REG_CORE32.
Referenced by dump(), updateKvmStateCore(), and updateTCStateCore().
dumpKvmStateMisc()
void ArmKvmCPU::dumpKvmStateMisc () private
Definition at line 484 of file arm_cpu.cc.
References dumpKvmStateCoProc(), dumpKvmStateVFP(), EXTRACT_FIELD, BaseKvmCPU::getAndFormatOneReg(), getRegList(), ArmISA::id, inform, REG_CP, REG_IS_ARM, REG_IS_CORE, REG_IS_DEMUX, and REG_IS_VFP.
Referenced by dump(), updateKvmStateMisc(), and updateTCStateMisc().
dumpKvmStateVFP()
void ArmKvmCPU::dumpKvmStateVFP (uint64_t id) private
Definition at line 565 of file arm_cpu.cc.
References decodeVFPCtrlReg(), BaseKvmCPU::getAndFormatOneReg(), inform, ArmISA::miscRegName, AlphaISA::NUM_MISCREGS, REG_IS_ARM, REG_IS_VFP, REG_IS_VFP_CTRL, and REG_IS_VFP_REG.
Referenced by dumpKvmStateMisc().
getRegList() [1/2]
const ArmKvmCPU::RegIndexVector & ArmKvmCPU::getRegList () const protected
Get a list of registers supported by getOneReg() and setOneReg().
Definition at line 336 of file arm_cpu.cc.
References _regIndexList, and ArmISA::i.
Referenced by dumpKvmStateMisc(), updateKvmStateMisc(), and updateTCStateMisc().
getRegList() [2/2]
bool ArmKvmCPU::getRegList (struct kvm_reg_list & regs) const private
Get a list of registers supported by getOneReg() and setOneReg().
Returns
False if the number of elements allocated in the list is too small to hold the complete register list (the required value is written into n in this case). True on success.
Definition at line 447 of file arm_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
isInvariantReg()
bool ArmKvmCPU::isInvariantReg (uint64_t id) protected
Determine if a register is invariant.
Some registers must have the same value in both the host and the guest. Such registers are referred to as "invariant" registers in KVM. This is a restriction imposed by KVM as having different values in ID registers (e.g., the cache identification registers) would confuse the guest kernel.
Definition at line 435 of file arm_cpu.cc.
References invariant_regs, REG_IS_ARM, and REG_IS_DEMUX.
Referenced by dumpKvmStateCoProc(), and updateKvmStateMisc().
kvmArmVCpuInit() [1/2]
void ArmKvmCPU::kvmArmVCpuInit (uint32_t target) protected
Definition at line 357 of file arm_cpu.cc.
Referenced by startup().
kvmArmVCpuInit() [2/2]
void ArmKvmCPU::kvmArmVCpuInit (const struct kvm_vcpu_init & init) protected
Definition at line 369 of file arm_cpu.cc.
References BaseKvmCPU::ioctl(), and panic.
kvmRun()
Tick ArmKvmCPU::kvmRun (Tick ticks) protected virtual
Request KVM to run the guest for a given number of ticks.
The method returns the approximate number of ticks executed.
Note
The returned number of ticks can be both larger or smaller than the requested number of ticks. A smaller number can, for example, occur when the guest executes MMIO. A larger number is typically due to performance counter inaccuracies.
This method is virtual in order to allow implementations to check for architecture specific events (e.g., interrupts) before entering the VM.
It is the response of the caller (normally tick()) to make sure that the KVM state is synchronized and that the TC is invalidated after entering KVM.
This method does not normally cause any state transitions. However, if it may suspend the CPU by suspending the thread, which leads to a transition to the Idle state. In such a case, kvm must not be entered.
Parameters
ticks Number of ticks to execute, set to 0 to exit immediately after finishing pending operations.
Returns
Number of ticks executed (see note)
Reimplemented from BaseKvmCPU.
Definition at line 271 of file arm_cpu.cc.
References DPRINTF, fiqAsserted, ArmISA::INT_FIQ, ArmISA::INT_IRQ, INTERRUPT_VCPU_FIQ, INTERRUPT_VCPU_IRQ, BaseCPU::interrupts, irqAsserted, BaseKvmCPU::kvmRun(), KvmVM::setIRQLine(), BaseKvmCPU::vcpuID, and BaseKvmCPU::vm.
onKvmExitHypercall()
Tick ArmKvmCPU::onKvmExitHypercall () protected
Definition at line 316 of file arm_cpu.cc.
References DPRINTF, BaseKvmCPU::getContext(), ArmISA::INTREG_R12, PseudoInst::pseudoInst(), ThreadContext::readIntRegFlat(), REG_CORE32, BaseKvmCPU::setOneReg(), and BaseKvmCPU::tc.
startup()
void ArmKvmCPU::startup () virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 256 of file arm_cpu.cc.
References kvmArmVCpuInit(), and BaseKvmCPU::startup().
updateKvmState()
void ArmKvmCPU::updateKvmState () protected virtual
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implements BaseKvmCPU.
Definition at line 298 of file arm_cpu.cc.
References DPRINTF, updateKvmStateCore(), and updateKvmStateMisc().
updateKvmStateCoProc()
void ArmKvmCPU::updateKvmStateCoProc (uint64_t id, bool show_warnings) private
Definition at line 650 of file arm_cpu.cc.
References decodeCoProcReg(), hack, KVM_REG64_TTBR0(), KVM_REG64_TTBR1(), ArmISA::MISCREG_TTBR0, ArmISA::MISCREG_TTBR1, ArmISA::miscRegName, AlphaISA::NUM_MISCREGS, ThreadContext::readMiscRegNoEffect(), X86ISA::reg, REG_CP, REG_CRM, REG_CRN, REG_IS_64BIT, REG_IS_ARM, REG_OPC1, REG_OPC2, BaseKvmCPU::setOneReg(), BaseKvmCPU::tc, and warn.
Referenced by updateKvmStateMisc().
updateKvmStateCore()
void ArmKvmCPU::updateKvmStateCore () private
Definition at line 586 of file arm_cpu.cc.
References DPRINTF, DTRACE, dumpKvmStateCore(), ArmKvmCPU::KvmIntRegInfo::idx, ArmKvmCPU::KvmCoreMiscRegInfo::idx, ThreadContext::instAddr(), kvmCoreMiscRegs, kvmIntRegs, ArmISA::NUM_INTREGS, AlphaISA::NUM_MISCREGS, ThreadContext::readIntRegFlat(), ThreadContext::readMiscReg(), REG_CORE32, BaseKvmCPU::setOneReg(), and BaseKvmCPU::tc.
Referenced by updateKvmState().
updateKvmStateMisc()
void ArmKvmCPU::updateKvmStateMisc () private
Definition at line 612 of file arm_cpu.cc.
References DPRINTF, DTRACE, dumpKvmStateMisc(), getRegList(), isInvariantReg(), REG_CP, REG_IS_ARM, REG_IS_CORE, REG_IS_VFP, updateKvmStateCoProc(), updateKvmStateVFP(), and warn.
Referenced by updateKvmState().
updateKvmStateVFP()
void ArmKvmCPU::updateKvmStateVFP (uint64_t id, bool show_warnings) private
Definition at line 684 of file arm_cpu.cc.
References decodeVFPCtrlReg(), ArmISA::miscRegName, AlphaISA::NUM_MISCREGS, ThreadContext::readFloatRegFlat(), ThreadContext::readMiscReg(), REG_IS_32BIT, REG_IS_64BIT, REG_IS_ARM, REG_IS_VFP, REG_IS_VFP_CTRL, REG_IS_VFP_REG, BaseKvmCPU::setOneReg(), BaseKvmCPU::tc, and warn.
Referenced by updateKvmStateMisc().
updateTCStateCoProc()
void ArmKvmCPU::updateTCStateCoProc (uint64_t id, bool show_warnings) private
Definition at line 789 of file arm_cpu.cc.
References decodeCoProcReg(), BaseKvmCPU::getOneRegU32(), BaseKvmCPU::getOneRegU64(), hack_once, KVM_REG64_TTBR0(), KVM_REG64_TTBR1(), ArmISA::MISCREG_TTBCR, ArmISA::MISCREG_TTBR0, ArmISA::MISCREG_TTBR1, ArmISA::miscRegName, AlphaISA::NUM_MISCREGS, panic, X86ISA::reg, REG_CP, REG_CRM, REG_CRN, REG_IS_64BIT, REG_IS_ARM, REG_OPC1, REG_OPC2, ThreadContext::setMiscRegNoEffect(), BaseKvmCPU::tc, warn, and warn_once.
Referenced by updateTCStateMisc().
updateTCStateCore()
void ArmKvmCPU::updateTCStateCore () private
Definition at line 726 of file arm_cpu.cc.
References DTRACE, dumpKvmStateCore(), BaseKvmCPU::getOneRegU32(), ArmKvmCPU::KvmIntRegInfo::idx, ArmKvmCPU::KvmCoreMiscRegInfo::idx, kvmCoreMiscRegs, kvmIntRegs, ArmISA::MISCREG_CPSR, ArmISA::NUM_INTREGS, AlphaISA::NUM_MISCREGS, MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), REG_CORE32, ThreadContext::setIntRegFlat(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), and BaseKvmCPU::tc.
Referenced by updateThreadContext().
updateTCStateMisc()
void ArmKvmCPU::updateTCStateMisc () private
Definition at line 756 of file arm_cpu.cc.
References DTRACE, dumpKvmStateMisc(), getRegList(), REG_CP, REG_IS_ARM, REG_IS_CORE, REG_IS_VFP, updateTCStateCoProc(), updateTCStateVFP(), and warn.
Referenced by updateThreadContext().
updateTCStateVFP()
void ArmKvmCPU::updateTCStateVFP (uint64_t id, bool show_warnings) private
Definition at line 825 of file arm_cpu.cc.
References ArmKvmCPU(), decodeVFPCtrlReg(), BaseKvmCPU::getOneRegU64(), ArmISA::miscRegName, AlphaISA::NUM_MISCREGS, REG_IS_32BIT, REG_IS_64BIT, REG_IS_ARM, REG_IS_VFP, REG_IS_VFP_CTRL, REG_IS_VFP_REG, ThreadContext::setFloatRegFlat(), ThreadContext::setMiscReg(), BaseKvmCPU::tc, and warn.
Referenced by updateTCStateMisc().
updateThreadContext()
void ArmKvmCPU::updateThreadContext () protected virtual
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implements BaseKvmCPU.
Definition at line 307 of file arm_cpu.cc.
References DPRINTF, updateTCStateCore(), and updateTCStateMisc().
Member Data Documentation
_regIndexList
RegIndexVector ArmKvmCPU::_regIndexList mutable private
Cached copy of the list of co-processor registers supported by KVM.
Definition at line 160 of file arm_cpu.hh.
Referenced by getRegList().
fiqAsserted
bool ArmKvmCPU::fiqAsserted private
Cached state of the FIQ line.
Definition at line 154 of file arm_cpu.hh.
Referenced by kvmRun().
invariant_regs
const std::set< uint64_t > ArmKvmCPU::invariant_regs static private
List of co-processor registers that KVM requires to be identical on both the host and the guest.
KVM does not allow writes to these registers.
Definition at line 167 of file arm_cpu.hh.
Referenced by isInvariantReg().
irqAsserted
bool ArmKvmCPU::irqAsserted private
Cached state of the IRQ line.
Definition at line 152 of file arm_cpu.hh.
Referenced by kvmRun().
kvmCoreMiscRegs
ArmKvmCPU::KvmCoreMiscRegInfo ArmKvmCPU::kvmCoreMiscRegs static protected
Initial value:
= {
    { REG_CORE32(usr_regs.ARM_cpsr), MISCREG_CPSR, "CPSR" },
    { REG_CORE32(svc_regs[2]), MISCREG_SPSR_SVC, "SPSR(SVC)" },
    { REG_CORE32(abt_regs[2]), MISCREG_SPSR_ABT, "SPSR(ABT)" },
    { REG_CORE32(und_regs[2]), MISCREG_SPSR_UND, "SPSR(UND)" },
    { REG_CORE32(irq_regs[2]), MISCREG_SPSR_IRQ, "SPSR(IRQ)" },
    { REG_CORE32(fiq_regs[2]), MISCREG_SPSR_FIQ, "SPSR(FIQ)" },
    { 0, NUM_MISCREGS }
}
Definition at line 123 of file arm_cpu.hh.
Referenced by dumpKvmStateCore(), updateKvmStateCore(), and updateTCStateCore().
kvmIntRegs
ArmKvmCPU::KvmIntRegInfo ArmKvmCPU::kvmIntRegs static protected
Definition at line 122 of file arm_cpu.hh.
Referenced by dumpKvmStateCore(), updateKvmStateCore(), and updateTCStateCore().
The documentation for this class was generated from the following files:
arch/arm/kvm/arm_cpu.hh
arch/arm/kvm/arm_cpu.cc