gem5: MuxingKvmGic Class Reference
MuxingKvmGic Class Reference
#include <gic.hh>
Public Member Functions
MuxingKvmGic (const MuxingKvmGicParams *p)
~MuxingKvmGic ()
void startup () override
startup() is the final initialization call before simulation.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void sendInt (uint32_t num) override
Post an interrupt from a device that is connected to the GIC.
void clearInt (uint32_t num) override
Clear an interrupt from a device that is connected to the GIC.
void sendPPInt (uint32_t num, uint32_t cpu) override
Interface call for private peripheral interrupts.
void clearPPInt (uint32_t num, uint32_t cpu) override
Public Member Functions inherited from GicV2
const Params * params () const
GicV2 (const Params *p)
~GicV2 ()
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
A PIO read to the device, immediately split up into readDistributor() or readCpu()
Tick write (PacketPtr pkt) override
A PIO read to the device, immediately split up into writeDistributor() or writeCpu()
void sendInt (uint32_t number) override
Post an interrupt from a device that is connected to the GIC.
void clearInt (uint32_t number) override
Clear an interrupt from a device that is connected to the GIC.
void sendPPInt (uint32_t num, uint32_t cpu) override
Interface call for private peripheral interrupts.
void clearPPInt (uint32_t num, uint32_t cpu) override
bool supportsVersion (GicVersion version) override
Check if version supported.
Public Member Functions inherited from BaseGic
BaseGic (const Params *p)
virtual ~BaseGic ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
const Params * params () const
ArmSystem * getSystem () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void updateIntState (int hint) override
See if some processor interrupt flags need to be enabled/disabled.
Protected Member Functions inherited from GicV2
BitUnion32 (SWI) Bitfield< 3
EndBitUnion (SWI) BitUnion32(IAR) Bitfield< 9
EndBitUnion (IAR) BitUnion32(CTLR) Bitfield< 3 > fiqEn
BankedRegs & getBankedRegs (ContextID)
uint32_t & getIntEnabled (ContextID ctx, uint32_t ix)
uint32_t & getPendingInt (ContextID ctx, uint32_t ix)
uint32_t & getActiveInt (ContextID ctx, uint32_t ix)
uint32_t & getIntGroup (ContextID ctx, uint32_t ix)
uint8_t & getIntPriority (ContextID ctx, uint32_t ix)
uint8_t getIntConfig (ContextID ctx, uint32_t ix)
GICD_ICFGRn get 2 bit config associated to an interrupt.
uint8_t getCpuTarget (ContextID ctx, uint32_t ix)
bool isLevelSensitive (ContextID ctx, uint32_t ix)
bool isGroup0 (ContextID ctx, uint32_t int_num)
bool isFiq (ContextID ctx, uint32_t int_num)
This method checks if an interrupt ID must be signaled or has been signaled as a FIQ to the cpu.
bool cpuEnabled (ContextID ctx) const
CPU enabled: Checks if GICC_CTLR.EnableGrp0 or EnableGrp1 are set.
uint8_t getCpuPriority (unsigned cpu)
void softInt (ContextID ctx, SWI swi)
software generated interrupt
void updateRunPri ()
Update the register that records priority of the highest priority active interrupt.
uint64_t genSwiMask (int cpu)
generate a bit mask to check cpuSgi for an interrupt.
int intNumToWord (int num) const
int intNumToBit (int num) const
void clearInt (ContextID ctx, uint32_t int_num)
Clears a cpu IRQ or FIQ signal.
void postInt (uint32_t cpu, Tick when)
Post an interrupt to a CPU with a delay.
void postFiq (uint32_t cpu, Tick when)
void postDelayedInt (uint32_t cpu)
Deliver a delayed interrupt to the target CPU.
void postDelayedFiq (uint32_t cpu)
Tick readDistributor (PacketPtr pkt)
Handle a read to the distributor portion of the GIC.
uint32_t readDistributor (ContextID ctx, Addr daddr, size_t resp_sz)
uint32_t readDistributor (ContextID ctx, Addr daddr) override
Tick readCpu (PacketPtr pkt)
Handle a read to the cpu portion of the GIC.
uint32_t readCpu (ContextID ctx, Addr daddr) override
Tick writeDistributor (PacketPtr pkt)
Handle a write to the distributor portion of the GIC.
void writeDistributor (ContextID ctx, Addr daddr, uint32_t data, size_t data_sz)
void writeDistributor (ContextID ctx, Addr daddr, uint32_t data) override
Tick writeCpu (PacketPtr pkt)
Handle a write to the cpu portion of the GIC.
void writeCpu (ContextID ctx, Addr daddr, uint32_t data) override
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
System & system
System this interrupt controller belongs to.
KvmKernelGicV2 * kernelGic
Kernel GIC device.
Protected Attributes inherited from GicV2
const uint32_t gicdPIDR
const uint32_t gicdIIDR
const uint32_t giccIIDR
sgi_id
Bitfield< 23, 16 > cpu_list
Bitfield< 25, 24 > list_type
ack_id
Bitfield< 12, 10 > cpu_id
Bitfield< 1 > enableGrp1
Bitfield< 0 > enableGrp0
EndBitUnion(CTLR) protected const AddrRange cpuRange
Address range for the distributor interface.
const AddrRangeList addrRanges
All address ranges used by this GIC.
const Tick distPioDelay
Latency for a distributor operation.
const Tick cpuPioDelay
Latency for a cpu operation.
const Tick intLatency
Latency for a interrupt to get to CPU.
bool enabled
Gic enabled.
const bool haveGem5Extensions
Are gem5 extensions available?
bool gem5ExtensionsEnabled
gem5 many-core extension enabled by driver
uint32_t itLines
Number of itLines enabled.
std::vector< BankedRegs * > bankedRegs
uint32_t intEnabled [INT_BITS_MAX-1]
GICD_I{S,C}ENABLER{1..31} interrupt enable bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t pendingInt [INT_BITS_MAX-1]
GICD_I{S,C}PENDR{1..31} interrupt pending bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t activeInt [INT_BITS_MAX-1]
GICD_I{S,C}ACTIVER{1..31} interrupt active bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t intGroup [INT_BITS_MAX-1]
GICD_IGROUPR{1..31} interrupt group bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t iccrpr [CPU_MAX]
read only running priority register, 1 per cpu
uint8_t intPriority [GLOBAL_INT_LINES]
GICD_IPRIORITYR{8..255} an 8 bit priority (lower is higher priority) for each of the global (not replicated per CPU) interrupts.
uint8_t cpuTarget [GLOBAL_INT_LINES]
GICD_ITARGETSR{8..255} an 8 bit cpu target id for each global interrupt.
uint32_t intConfig [INT_BITS_MAX *2]
2 bit per interrupt signaling if it's level or edge sensitive and if it is 1:N or N:N
CTLR cpuControl [CPU_MAX]
GICC_CTLR: CPU interface control register.
uint8_t cpuPriority [CPU_MAX]
CPU priority.
uint8_t cpuBpr [CPU_MAX]
Binary point registers.
uint32_t cpuHighestInt [CPU_MAX]
highest interrupt that is interrupting CPU
uint64_t cpuSgiPending [SGI_MAX]
One bit per cpu per software interrupt that is pending for each possible sgi source.
uint64_t cpuSgiActive [SGI_MAX]
uint32_t cpuSgiPendingExt [CPU_MAX]
SGI pending arrays for gem5 GIC extension mode, which instead keeps 16 SGI pending bits for each of the (large number of) CPUs.
uint32_t cpuSgiActiveExt [CPU_MAX]
uint32_t cpuPpiPending [CPU_MAX]
One bit per private peripheral interrupt.
uint32_t cpuPpiActive [CPU_MAX]
EventFunctionWrapper * postIntEvent [CPU_MAX]
EventFunctionWrapper * postFiqEvent [CPU_MAX]
int pendingDelayedInterrupts
Protected Attributes inherited from BaseGic
Platform * platform
Platform this GIC belongs to.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
void fromGicV2ToKvm ()
Multiplexing implementation.
void fromKvmToGicV2 ()
void copyGicState (BaseGicRegisters *from, BaseGicRegisters *to)
void copyDistRegister (BaseGicRegisters *from, BaseGicRegisters *to, ContextID ctx, Addr daddr)
void copyCpuRegister (BaseGicRegisters *from, BaseGicRegisters *to, ContextID ctx, Addr daddr)
void copyBankedDistRange (BaseGicRegisters *from, BaseGicRegisters *to, Addr daddr, size_t size)
void clearBankedDistRange (BaseGicRegisters *to, Addr daddr, size_t size)
void copyDistRange (BaseGicRegisters *from, BaseGicRegisters *to, Addr daddr, size_t size)
void clearDistRange (BaseGicRegisters *to, Addr daddr, size_t size)
Private Attributes
bool usingKvm
Additional Inherited Members
Public Types inherited from GicV2
typedef GicV2Params Params
Public Types inherited from BaseGic
enum GicVersion { GicVersion::GIC_V2, GicVersion::GIC_V3, GicVersion::GIC_V4 }
typedef BaseGicParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from GicV2
enum {
GICD_CTLR = 0x000, GICD_TYPER = 0x004, GICD_IIDR = 0x008, GICD_SGIR = 0xf00,
GICD_PIDR0 = 0xfe0, GICD_PIDR1 = 0xfe4, GICD_PIDR2 = 0xfe8, GICD_PIDR3 = 0xfec,
DIST_SIZE = 0x1000
}
enum {
GICC_CTLR = 0x00, GICC_PMR = 0x04, GICC_BPR = 0x08, GICC_IAR = 0x0C,
GICC_EOIR = 0x10, GICC_RPR = 0x14, GICC_HPPIR = 0x18, GICC_ABPR = 0x1c,
GICC_APR0 = 0xd0, GICC_APR1 = 0xd4, GICC_APR2 = 0xd8, GICC_APR3 = 0xdc,
GICC_IIDR = 0xfc, GICC_DIR = 0x1000
}
Static Protected Attributes inherited from GicV2
static const AddrRange GICD_IGROUPR
static const AddrRange GICD_ISENABLER
static const AddrRange GICD_ICENABLER
static const AddrRange GICD_ISPENDR
static const AddrRange GICD_ICPENDR
static const AddrRange GICD_ISACTIVER
static const AddrRange GICD_ICACTIVER
static const AddrRange GICD_IPRIORITYR
static const AddrRange GICD_ITARGETSR
static const AddrRange GICD_ICFGR
static const int SGI_MAX = 16
static const int PPI_MAX = 16
static const int SGI_MASK = 0xFFFF0000
Mask off SGI's when setting/clearing pending bits.
static const int NN_CONFIG_MASK = 0x55555555
Mask for bits that config N:N mode in GICD_ICFGR's.
static const int CPU_MAX = 256
static const int SPURIOUS_INT = 1023
static const int INT_BITS_MAX = 32
static const int INT_LINES_MAX = 1020
static const int GLOBAL_INT_LINES = INT_LINES_MAX - SGI_MAX - PPI_MAX
static const int GICC_BPR_MINIMUM = 2
minimum value for Binary Point Register ("IMPLEMENTATION DEFINED"); chosen for consistency with Linux's in-kernel KVM GIC model
Detailed Description
Definition at line 171 of file gic.hh.
Constructor & Destructor Documentation
MuxingKvmGic()
MuxingKvmGic::MuxingKvmGic (const MuxingKvmGicParams * p)
Definition at line 170 of file gic.cc.
References System::getKvmVM(), kernelGic, system, and ArmISA::vm.
Referenced by fromKvmToGicV2().
~MuxingKvmGic()
MuxingKvmGic::~MuxingKvmGic ()
Definition at line 182 of file gic.cc.
Member Function Documentation
clearBankedDistRange()
void MuxingKvmGic::clearBankedDistRange (BaseGicRegisters * to, Addr daddr, size_t size) private
Definition at line 314 of file gic.cc.
References ArmISA::a, System::numContexts(), system, and BaseGicRegisters::writeDistributor().
Referenced by copyGicState().
clearDistRange()
void MuxingKvmGic::clearDistRange (BaseGicRegisters * to, Addr daddr, size_t size) private
Definition at line 331 of file gic.cc.
References ArmISA::a, and BaseGicRegisters::writeDistributor().
Referenced by copyGicState().
clearInt()
void MuxingKvmGic::clearInt (uint32_t num) override virtual
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 247 of file gic.cc.
References GicV2::clearInt(), KvmKernelGicV2::clearSPI(), DPRINTF, kernelGic, and usingKvm.
clearPPInt()
void MuxingKvmGic::clearPPInt (uint32_t num, uint32_t cpu) override virtual
Implements BaseGic.
Definition at line 266 of file gic.cc.
References KvmKernelGicV2::clearPPI(), GicV2::clearPPInt(), DPRINTF, kernelGic, and usingKvm.
copyBankedDistRange()
void MuxingKvmGic::copyBankedDistRange (BaseGicRegisters * from, BaseGicRegisters * to, Addr daddr, size_t size) private
Definition at line 305 of file gic.cc.
References ArmISA::a, copyDistRegister(), System::numContexts(), and system.
Referenced by copyGicState().
copyCpuRegister()
void MuxingKvmGic::copyCpuRegister (BaseGicRegisters * from, BaseGicRegisters * to, ContextID ctx, Addr daddr) private
Definition at line 296 of file gic.cc.
References DPRINTF, BaseGicRegisters::readCpu(), X86ISA::val, and BaseGicRegisters::writeCpu().
Referenced by copyGicState().
copyDistRange()
void MuxingKvmGic::copyDistRange (BaseGicRegisters * from, BaseGicRegisters * to, Addr daddr, size_t size) private
Definition at line 323 of file gic.cc.
References ArmISA::a, and copyDistRegister().
Referenced by copyGicState().
copyDistRegister()
void MuxingKvmGic::copyDistRegister (BaseGicRegisters * from, BaseGicRegisters * to, ContextID ctx, Addr daddr) private
Definition at line 287 of file gic.cc.
References DPRINTF, BaseGicRegisters::readDistributor(), X86ISA::val, and BaseGicRegisters::writeDistributor().
Referenced by copyBankedDistRange(), copyDistRange(), and copyGicState().
copyGicState()
void MuxingKvmGic::copyGicState (BaseGicRegisters * from, BaseGicRegisters * to) private
CPU state (GICC_*)
Distributor state (GICD_*)
Definition at line 339 of file gic.cc.
References clearBankedDistRange(), clearDistRange(), copyBankedDistRange(), copyCpuRegister(), copyDistRange(), copyDistRegister(), GicV2::GICC_BPR, GicV2::GICC_CTLR, GicV2::GICC_PMR, GicV2::GICD_CTLR, GicV2::GICD_ICACTIVER, GicV2::GICD_ICENABLER, GicV2::GICD_ICFGR, GicV2::GICD_ICPENDR, GicV2::GICD_IPRIORITYR, GicV2::GICD_ISACTIVER, GicV2::GICD_ISENABLER, GicV2::GICD_ISPENDR, GicV2::GICD_ITARGETSR, GicV2::itLines, System::numContexts(), AddrRange::start(), and system.
Referenced by fromGicV2ToKvm(), and fromKvmToGicV2().
drain()
DrainState MuxingKvmGic::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 196 of file gic.cc.
References GicV2::drain(), fromKvmToGicV2(), and usingKvm.
drainResume()
void MuxingKvmGic::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 204 of file gic.cc.
References GicV2::drainResume(), fromGicV2ToKvm(), kernelGic, system, usingKvm, and System::validKvmEnvironment().
fromGicV2ToKvm()
void MuxingKvmGic::fromGicV2ToKvm () private
Multiplexing implementation.
Definition at line 412 of file gic.cc.
References copyGicState(), and kernelGic.
Referenced by drainResume(), and startup().
fromKvmToGicV2()
void MuxingKvmGic::fromKvmToGicV2 () private
Definition at line 418 of file gic.cc.
References copyGicState(), GicV2::cpuPriority, kernelGic, MuxingKvmGic(), System::numContexts(), and system.
Referenced by drain().
read()
Tick MuxingKvmGic::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 219 of file gic.cc.
References panic, GicV2::read(), and usingKvm.
sendInt()
void MuxingKvmGic::sendInt (uint32_t num) override virtual
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 237 of file gic.cc.
References DPRINTF, kernelGic, GicV2::sendInt(), KvmKernelGicV2::setSPI(), and usingKvm.
sendPPInt()
void MuxingKvmGic::sendPPInt (uint32_t num, uint32_t cpu) override virtual
Interface call for private peripheral interrupts.
Parameters
num number of interrupt to send
cpu CPU to forward interrupt to
Implements BaseGic.
Definition at line 257 of file gic.cc.
References DPRINTF, kernelGic, GicV2::sendPPInt(), KvmKernelGicV2::setPPI(), and usingKvm.
startup()
void MuxingKvmGic::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 187 of file gic.cc.
References fromGicV2ToKvm(), kernelGic, SimObject::startup(), system, usingKvm, and System::validKvmEnvironment().
updateIntState()
void MuxingKvmGic::updateIntState (int hint) override protected virtual
See if some processor interrupt flags need to be enabled/disabled.
Parameters
hint which set of interrupts needs to be checked
Reimplemented from GicV2.
Definition at line 276 of file gic.cc.
References GicV2::updateIntState(), and usingKvm.
write()
Tick MuxingKvmGic::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 228 of file gic.cc.
References panic, usingKvm, and GicV2::write().
Member Data Documentation
kernelGic
KvmKernelGicV2* MuxingKvmGic::kernelGic protected
Kernel GIC device.
Definition at line 200 of file gic.hh.
Referenced by clearInt(), clearPPInt(), drainResume(), fromGicV2ToKvm(), fromKvmToGicV2(), MuxingKvmGic(), sendInt(), sendPPInt(), and startup().
system
System& MuxingKvmGic::system protected
System this interrupt controller belongs to.
Definition at line 197 of file gic.hh.
Referenced by clearBankedDistRange(), copyBankedDistRange(), copyGicState(), drainResume(), fromKvmToGicV2(), MuxingKvmGic(), and startup().
usingKvm
bool MuxingKvmGic::usingKvm private
Definition at line 203 of file gic.hh.
Referenced by clearInt(), clearPPInt(), drain(), drainResume(), read(), sendInt(), sendPPInt(), startup(), updateIntState(), and write().
The documentation for this class was generated from the following files:
arch/arm/kvm/gic.hh
arch/arm/kvm/gic.cc