gem5: Callback Class Reference
Callback Class Reference abstract
Generic callback class.
#include <callback.hh>
Public Member Functions
virtual ~Callback ()
virtualize the destructor to make sure that the correct one gets called.
virtual void process ()=0
virtual process function that is invoked when the callback queue is executed.
Protected Member Functions
virtual void autoDestruct ()
Friends
class CallbackQueue
Detailed Description
Generic callback class.
This base class provides a virtual process function that gets called when the callback queue is processed.
Definition at line 41 of file callback.hh.
Constructor & Destructor Documentation
~Callback()
virtual Callback::~Callback () inline virtual
virtualize the destructor to make sure that the correct one gets called.
Definition at line 52 of file callback.hh.
References process().
Member Function Documentation
autoDestruct()
virtual void Callback::autoDestruct () inline protected virtual
Reimplemented in MakeCallback< T, F >, MakeCallback< PciVirtIO, &PciVirtIO::kick >, MakeCallback< MmioVirtIO, &MmioVirtIO::kick >, MakeCallback< VirtIOConsole::TermRecvQueue, &VirtIOConsole::TermRecvQueue::trySend >, MakeCallback< Uart, &Uart::dataAvailable >, and MemBackdoor::Callback.
Definition at line 45 of file callback.hh.
process()
virtual void Callback::process () pure virtual
virtual process function that is invoked when the callback queue is executed.
Implemented in ComputeUnit::CUExitCallback, BaseTagsCallback, AbstractController::StatsCallback, CowDiskCallback, Network::StatsCallback, RubyStatsCallback, AnnotateDumpCallback, MakeCallback< T, F >, MakeCallback< PciVirtIO, &PciVirtIO::kick >, MakeCallback< MmioVirtIO, &MmioVirtIO::kick >, MakeCallback< VirtIOConsole::TermRecvQueue, &VirtIOConsole::TermRecvQueue::trySend >, MakeCallback< Uart, &Uart::dataAvailable >, Stats::SimTicksReset, MemBackdoor::Callback, and CallbackImpl.
Referenced by FlashDevice::actionComplete(), SerialDevice::notifyInterface(), and ~Callback().
Friends And Related Function Documentation
CallbackQueue
friend class CallbackQueue friend
Definition at line 44 of file callback.hh.
Referenced by MemBackdoor::invalidate().
The documentation for this class was generated from the following file:
base/callback.hh