gem5: MSHRQueue Class Reference
MSHRQueue Class Reference
A Class for maintaining a list of pending and allocated memory requests.
#include <mshr_queue.hh>
Public Member Functions
MSHRQueue (const std::string &_label, int num_entries, int reserve, int demand_reserve)
Create a queue with a given number of entries.
MSHR * allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order, bool alloc_on_fill)
Allocates a new MSHR for the request and size.
void moveToFront (MSHR *mshr)
Moves the MSHR to the front of the pending list if it is not in service.
void delay (MSHR *mshr, Tick delay_ticks)
Adds a delay to the provided MSHR and moves MSHRs that will be ready earlier than this entry to the top of the list.
void markInService (MSHR *mshr, bool pending_modified_resp)
Mark the given MSHR as in service.
void markPending (MSHR *mshr)
Mark an in service entry as pending, used to resend a request.
bool forceDeallocateTarget (MSHR *mshr)
Deallocate top target, possibly freeing the MSHR.
bool havePending () const
Returns true if the pending list is not empty.
bool canPrefetch () const
Returns true if sufficient mshrs for prefetch.
Public Member Functions inherited from Queue< MSHR >
Queue (const std::string &_label, int num_entries, int reserve)
Create a queue with a given number of entries.
bool isEmpty () const
bool isFull () const
int numInService () const
MSHR * findMatch (Addr blk_addr, bool is_secure, bool ignore_uncacheable=true) const
Find the first entry that matches the provided address.
bool trySatisfyFunctional (PacketPtr pkt)
MSHR * findPending (const QueueEntry *entry) const
Find any pending requests that overlap the given request of a different queue.
MSHR * getNext () const
Returns the WriteQueueEntry at the head of the readyList.
Tick nextReadyTime () const
void deallocate (MSHR *entry)
Removes the given entry from the queue.
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Private Attributes
const int demandReserve
The number of entries to reserve for future demand accesses.
Additional Inherited Members
Protected Member Functions inherited from Queue< MSHR >
MSHR ::Iterator addToReadyList (MSHR *entry)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from Queue< MSHR >
const std::string label
Local label (for functional print requests)
const int numEntries
The total number of entries in this queue.
const int numReserve
The number of entries to hold as a temporary overflow space.
std::vector< MSHR > entries
Actual storage.
MSHR ::List allocatedList
Holds pointers to all allocated entries.
MSHR ::List readyList
Holds pointers to entries that haven't been sent downstream.
MSHR ::List freeList
Holds non allocated entries.
int _numInService
The number of entries that are in service.
int allocated
The number of currently allocated entries.
Detailed Description
A Class for maintaining a list of pending and allocated memory requests.
Definition at line 61 of file mshr_queue.hh.
Constructor & Destructor Documentation
MSHRQueue()
MSHRQueue::MSHRQueue (const std::string & _label, int num_entries, int reserve, int demand_reserve)
Create a queue with a given number of entries.
Parameters
num_entrys The number of entries in this queue.
reserve The minimum number of entries needed to satisfy any access.
demand_reserve The minimum number of entries needed to satisfy demand accesses.
Definition at line 54 of file mshr_queue.cc.
Member Function Documentation
allocate()
MSHR * MSHRQueue::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order, bool alloc_on_fill)
Allocates a new MSHR for the request and size.
This places the request as the first target in the MSHR.
Parameters
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original miss.
when_ready When should the MSHR be ready to act upon.
order The logical order of this MSHR
alloc_on_fill Should the cache allocate a block on fill
Returns
The a pointer to the MSHR allocated.
Precondition
There are free entries.
Definition at line 61 of file mshr_queue.cc.
References Queue< MSHR >::addToReadyList(), MSHR::allocate(), Queue< MSHR >::allocated, Queue< MSHR >::allocatedList, Queue< MSHR >::freeList, and MSHR::readyIter.
Referenced by BaseCache::allocateMissBuffer().
canPrefetch()
bool MSHRQueue::canPrefetch () const inline
Returns true if sufficient mshrs for prefetch.
Returns
True if sufficient mshrs for prefetch.
Definition at line 153 of file mshr_queue.hh.
References Queue< MSHR >::allocated, Queue< MSHR >::numEntries, and Queue< MSHR >::numReserve.
Referenced by BaseCache::getNextQueueEntry(), BaseCache::nextQueueReadyTime(), and BaseCache::recvTimingResp().
delay()
void MSHRQueue::delay (MSHR * mshr, Tick delay_ticks)
Adds a delay to the provided MSHR and moves MSHRs that will be ready earlier than this entry to the top of the list.
Parameters
mshr that needs to be delayed
delay_ticks ticks of the desired delay
Definition at line 88 of file mshr_queue.cc.
References MSHR::delay(), MSHR::readyIter, Queue< MSHR >::readyList, and QueueEntry::readyTime.
Referenced by BaseCache::sendMSHRQueuePacket().
forceDeallocateTarget()
bool MSHRQueue::forceDeallocateTarget (MSHR * mshr)
Deallocate top target, possibly freeing the MSHR.
Returns
if MSHR queue is no longer full
Definition at line 120 of file mshr_queue.cc.
References Queue< MSHR >::deallocate(), MSHR::hasTargets(), Queue< MSHR >::isFull(), MSHR::popTarget(), and MSHR::promoteDeferredTargets().
Referenced by Cache::sendMSHRQueuePacket().
havePending()
bool MSHRQueue::havePending () const inline
Returns true if the pending list is not empty.
Returns
True if there are outstanding requests.
Definition at line 144 of file mshr_queue.hh.
References Queue< MSHR >::readyList.
markInService()
void MSHRQueue::markInService (MSHR * mshr, bool pending_modified_resp)
Mark the given MSHR as in service.
This removes the MSHR from the readyList or deallocates the MSHR if it does not expect a response.
Parameters
mshr The MSHR to mark in service.
pending_modified_resp Whether we expect a modified response from another cache
Definition at line 99 of file mshr_queue.cc.
References Queue< MSHR >::_numInService, MSHR::markInService(), MSHR::readyIter, and Queue< MSHR >::readyList.
Referenced by BaseCache::markInService().
markPending()
void MSHRQueue::markPending (MSHR * mshr)
Mark an in service entry as pending, used to resend a request.
Parameters
mshr The MSHR to resend.
@ todo might want to add rerequests to front of pending list for performance.
Definition at line 107 of file mshr_queue.cc.
References Queue< MSHR >::_numInService, Queue< MSHR >::addToReadyList(), QueueEntry::inService, and MSHR::readyIter.
Referenced by BaseCache::recvTimingResp().
moveToFront()
void MSHRQueue::moveToFront (MSHR * mshr)
Moves the MSHR to the front of the pending list if it is not in service.
Parameters
mshr The entry to move.
Definition at line 78 of file mshr_queue.cc.
References QueueEntry::inService, MSHR::readyIter, and Queue< MSHR >::readyList.
Member Data Documentation
demandReserve
const int MSHRQueue::demandReserve private
The number of entries to reserve for future demand accesses.
Prevent prefetcher from taking all mshr entries
Definition at line 69 of file mshr_queue.hh.
The documentation for this class was generated from the following files:
mem/cache/mshr_queue.hh
mem/cache/mshr_queue.cc