gem5: WaitClass Class Reference
WaitClass Class Reference
#include <misc.hh>
Public Member Functions
WaitClass ()
void init (uint64_t *_tcnt, uint32_t _numStages=0)
void set (uint32_t i)
void preset (uint32_t delay)
bool rdy () const
bool prerdy () const
Private Attributes
uint64_t nxtAvail
uint64_t lookAheadAvail
uint64_t * tcnt
uint32_t numStages
Detailed Description
Definition at line 50 of file misc.hh.
Constructor & Destructor Documentation
WaitClass()
WaitClass::WaitClass () inline
Definition at line 53 of file misc.hh.
Member Function Documentation
init()
void WaitClass::init (uint64_t * _tcnt, uint32_t _numStages = 0) inline
Definition at line 54 of file misc.hh.
References numStages, and tcnt.
Referenced by ComputeUnit::init().
prerdy()
bool WaitClass::prerdy () const inline
Definition at line 71 of file misc.hh.
References lookAheadAvail, and tcnt.
preset()
void WaitClass::preset (uint32_t delay) inline
Definition at line 66 of file misc.hh.
References lookAheadAvail, numStages, and tcnt.
rdy()
bool WaitClass::rdy () const inline
Definition at line 70 of file misc.hh.
References nxtAvail, and tcnt.
Referenced by LocalMemPipeline::exec(), GlobalMemPipeline::exec(), and ComputeUnit::isDone().
set()
void WaitClass::set (uint32_t i) inline
Definition at line 60 of file misc.hh.
References fatal_if, ArmISA::i, nxtAvail, and tcnt.
Referenced by LocalMemPipeline::exec(), and GlobalMemPipeline::exec().
Member Data Documentation
lookAheadAvail
uint64_t WaitClass::lookAheadAvail private
Definition at line 79 of file misc.hh.
Referenced by prerdy(), and preset().
numStages
uint32_t WaitClass::numStages private
Definition at line 84 of file misc.hh.
Referenced by init(), and preset().
nxtAvail
uint64_t WaitClass::nxtAvail private
Definition at line 75 of file misc.hh.
Referenced by rdy(), and set().
tcnt
uint64_t* WaitClass::tcnt private
Definition at line 81 of file misc.hh.
Referenced by init(), prerdy(), preset(), rdy(), and set().
The documentation for this class was generated from the following file:
gpu-compute/misc.hh