gem5: ArmISA::TableWalker::L2Descriptor Class Reference
ArmISA::TableWalker::L2Descriptor Class Reference
Level 2 page table descriptor.
#include <table_walker.hh>
Public Member Functions
L2Descriptor ()
Default ctor.
L2Descriptor (L1Descriptor &parent)
virtual uint64_t getRawData () const
virtual std::string dbgHeader () const
virtual TlbEntry::DomainType domain () const
bool secure (bool have_security, WalkerState *currState) const
virtual uint8_t offsetBits () const
bool invalid () const
Is the entry invalid.
bool large () const
What is the size of the mapping?
bool xn () const
Is execution allowed on this mapping?
bool global (WalkerState *currState) const
Is the translation global (no asid used)?
uint8_t ap () const
Three bit access protection flags.
uint8_t texcb () const
Memory region attributes: ARM DDI 0406B: B3-32.
Addr pfn () const
Return the physical frame, bits shifted right.
Addr paddr (Addr va) const
Return complete physical address given a VA.
bool shareable () const
If the section is shareable.
void setAp0 ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
Public Member Functions inherited from ArmISA::TableWalker::DescriptorBase
DescriptorBase ()
Public Attributes
uint32_t data
The raw bits of the entry.
L1Descriptor * l1Parent
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Public Attributes inherited from ArmISA::TableWalker::DescriptorBase
LookupLevel lookupLevel
Current lookup level for this descriptor.
Detailed Description
Level 2 page table descriptor.
Definition at line 246 of file table_walker.hh.
Constructor & Destructor Documentation
L2Descriptor() [1/2]
ArmISA::TableWalker::L2Descriptor::L2Descriptor () inline
Default ctor.
Definition at line 257 of file table_walker.hh.
References ArmISA::L2, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
L2Descriptor() [2/2]
ArmISA::TableWalker::L2Descriptor::L2Descriptor (L1Descriptor & parent) inline
Definition at line 262 of file table_walker.hh.
References ArmISA::L2, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
Member Function Documentation
ap()
uint8_t ArmISA::TableWalker::L2Descriptor::ap () const inline virtual
Three bit access protection flags.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 318 of file table_walker.hh.
References bits().
Referenced by ArmISA::TableWalker::doL2Descriptor().
dbgHeader()
virtual std::string ArmISA::TableWalker::L2Descriptor::dbgHeader () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 273 of file table_walker.hh.
dirty()
bool ArmISA::TableWalker::L2Descriptor::dirty () const inline
This entry needs to be written back to memory.
Definition at line 362 of file table_walker.hh.
domain()
virtual TlbEntry::DomainType ArmISA::TableWalker::L2Descriptor::domain () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 278 of file table_walker.hh.
References ArmISA::TableWalker::L1Descriptor::domain().
getRawData()
virtual uint64_t ArmISA::TableWalker::L2Descriptor::getRawData () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 268 of file table_walker.hh.
global()
bool ArmISA::TableWalker::L2Descriptor::global (WalkerState * currState) const inline virtual
Is the translation global (no asid used)?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 312 of file table_walker.hh.
References bits().
invalid()
bool ArmISA::TableWalker::L2Descriptor::invalid () const inline
Is the entry invalid.
Definition at line 294 of file table_walker.hh.
References bits().
Referenced by ArmISA::TableWalker::doL2Descriptor().
large()
bool ArmISA::TableWalker::L2Descriptor::large () const inline
What is the size of the mapping?
Definition at line 300 of file table_walker.hh.
References bits().
offsetBits()
virtual uint8_t ArmISA::TableWalker::L2Descriptor::offsetBits () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 288 of file table_walker.hh.
paddr()
Addr ArmISA::TableWalker::L2Descriptor::paddr (Addr va) const inline
Return complete physical address given a VA.
Definition at line 338 of file table_walker.hh.
References mbits().
pfn()
Addr ArmISA::TableWalker::L2Descriptor::pfn () const inline virtual
Return the physical frame, bits shifted right.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 332 of file table_walker.hh.
References bits().
secure()
bool ArmISA::TableWalker::L2Descriptor::secure (bool have_security, WalkerState * currState) const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 283 of file table_walker.hh.
References ArmISA::TableWalker::L1Descriptor::secure().
setAp0()
void ArmISA::TableWalker::L2Descriptor::setAp0 () inline
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 355 of file table_walker.hh.
shareable()
bool ArmISA::TableWalker::L2Descriptor::shareable () const inline virtual
If the section is shareable.
See texcb() comment.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 347 of file table_walker.hh.
References bits().
texcb()
uint8_t ArmISA::TableWalker::L2Descriptor::texcb () const inline virtual
Memory region attributes: ARM DDI 0406B: B3-32.
Reimplemented from ArmISA::TableWalker::DescriptorBase.
Definition at line 324 of file table_walker.hh.
References bits().
xn()
bool ArmISA::TableWalker::L2Descriptor::xn () const inline virtual
Is execution allowed on this mapping?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 306 of file table_walker.hh.
References bits().
Member Data Documentation
_dirty
bool ArmISA::TableWalker::L2Descriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 254 of file table_walker.hh.
data
uint32_t ArmISA::TableWalker::L2Descriptor::data
The raw bits of the entry.
Definition at line 249 of file table_walker.hh.
Referenced by ArmISA::TableWalker::doL1Descriptor(), and ArmISA::TableWalker::doL2Descriptor().
l1Parent
L1Descriptor* ArmISA::TableWalker::L2Descriptor::l1Parent
Definition at line 250 of file table_walker.hh.
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh