gem5: ClDriver Class Reference
ClDriver Class Reference final
#include <cl_driver.hh>
Public Member Functions
ClDriver (ClDriverParams *p)
void handshake (GpuDispatcher *_dispatcher)
int open (ThreadContext *tc, int mode, int flags)
Abstract method, invoked when the user program calls open() on the device driver.
int ioctl (ThreadContext *tc, unsigned req)
Abstract method, invoked when the user program calls ioctl() on the file descriptor returned by a previous open().
const char * codeOffToKernelName (uint64_t code_ptr)
Public Member Functions inherited from EmulatedDriver
EmulatedDriver (EmulatedDriverParams *p)
bool match (const std::string &s) const
Check for a match with this driver's filename.
virtual Addr mmap (ThreadContext *tc, Addr start, uint64_t length, int prot, int tgtFlags, int tgtFd, int offset)
Virtual method, invoked when the user program calls mmap() on the file descriptor returned by a previous open().
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Attributes
GpuDispatcher * dispatcher
std::vector< const std::string * > codeFiles
std::vector< HsaCode * > kernels
std::vector< HsaCode * > functions
std::vector< HsaKernelInfo > kernelInfo
int maxFuncArgsSize
uint64_t hsaCode
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from EmulatedDriver
const std::string & filename
filename for opening this driver (under /dev)
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 51 of file cl_driver.hh.
Constructor & Destructor Documentation
ClDriver()
ClDriver::ClDriver (ClDriverParams * p)
Definition at line 50 of file cl_driver.cc.
References codeFiles, HsaObject::createHsaObject(), HsaCode::generateHsaKernelInfo(), HsaObject::getKernel(), ArmISA::i, MipsISA::k, kernelInfo, kernels, maxFuncArgsSize, HsaCode::name(), HsaCode::numInsts(), HsaObject::numKernels(), and HsaObject::readonlyData.
Referenced by codeOffToKernelName().
Member Function Documentation
codeOffToKernelName()
const char * ClDriver::codeOffToKernelName (uint64_t code_ptr)
Definition at line 265 of file cl_driver.cc.
References ClDriver(), hsaCode, ArmISA::i, kernelInfo, and kernels.
handshake()
void ClDriver::handshake (GpuDispatcher * _dispatcher)
Definition at line 89 of file cl_driver.cc.
References dispatcher, maxFuncArgsSize, and GpuDispatcher::setFuncargsSize().
Referenced by GpuDispatcher::GpuDispatcher().
ioctl()
int ClDriver::ioctl (ThreadContext * tc, unsigned req) virtual
Abstract method, invoked when the user program calls ioctl() on the file descriptor returned by a previous open().
The parameters are the same as those passed in to ioctlFunc() (q.v.).
Returns
The return code for the ioctl, or the negation of the errno (see the SyscallReturn class).
Implements EmulatedDriver.
Definition at line 106 of file cl_driver.cc.
References BufferArg::bufferPtr(), HsaKernelInfo::code_offs, HsaDriverSizes::code_size, BaseBufferArg::copyOut(), HsaKernelInfo::cRegCount, data, dispatcher, HsaKernelInfo::dRegCount, fatal, GpuDispatcher::getNumCUs(), ThreadContext::getProcessPtr(), GpuDispatcher::getStaticContextSize(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), HSA_GET_CODE, HSA_GET_CU_CNT, HSA_GET_HW_STATIC_CONTEXT_SIZE, HSA_GET_KINFO, HSA_GET_READONLY_DATA, HSA_GET_SIZES, HSA_GET_STRINGS, HSA_GET_VSZ, hsaCode, ArmISA::i, MipsISA::index, HsaCode::insts(), ArmISA::j, MipsISA::k, kernelInfo, kernels, ArmISA::n, HsaCode::name(), HsaKernelInfo::name_offs, HsaDriverSizes::num_kernels, HsaCode::numInsts(), HsaKernelInfo::private_mem_size, HsaCode::READONLY, HsaDriverSizes::readonly_size, HsaKernelInfo::spill_mem_size, HsaKernelInfo::sRegCount, HsaKernelInfo::static_lds_size, HsaDriverSizes::string_table_size, and GpuDispatcher::wfSize().
open()
int ClDriver::open (ThreadContext * tc, int mode, int flags) virtual
Abstract method, invoked when the user program calls open() on the device driver.
The parameters are the same as those passed to openFunc() (q.v.).
Returns
A newly allocated target fd, or -1 on error.
Implements EmulatedDriver.
Definition at line 96 of file cl_driver.cc.
References EmulatedDriver::filename, ThreadContext::getProcessPtr(), and MipsISA::p.
Member Data Documentation
codeFiles
std::vector<const std::string*> ClDriver::codeFiles private
Definition at line 63 of file cl_driver.hh.
Referenced by ClDriver().
dispatcher
GpuDispatcher* ClDriver::dispatcher private
Definition at line 61 of file cl_driver.hh.
Referenced by handshake(), and ioctl().
functions
std::vector<HsaCode*> ClDriver::functions private
Definition at line 67 of file cl_driver.hh.
hsaCode
uint64_t ClDriver::hsaCode private
Definition at line 74 of file cl_driver.hh.
Referenced by codeOffToKernelName(), and ioctl().
kernelInfo
std::vector<HsaKernelInfo> ClDriver::kernelInfo private
Definition at line 69 of file cl_driver.hh.
Referenced by ClDriver(), codeOffToKernelName(), and ioctl().
kernels
std::vector<HsaCode*> ClDriver::kernels private
Definition at line 66 of file cl_driver.hh.
Referenced by ClDriver(), codeOffToKernelName(), and ioctl().
maxFuncArgsSize
int ClDriver::maxFuncArgsSize private
Definition at line 72 of file cl_driver.hh.
Referenced by ClDriver(), and handshake().
The documentation for this class was generated from the following files:
gpu-compute/cl_driver.hh
gpu-compute/cl_driver.cc