gem5: SlimAMPMPrefetcher Class Reference
SlimAMPMPrefetcher Class Reference
#include <slim_ampm.hh>
Public Member Functions
SlimAMPMPrefetcher (const SlimAMPMPrefetcherParams *p)
Copyright (c) 2018 Metempsy Technology Consulting All rights reserved.
~SlimAMPMPrefetcher ()
void calculatePrefetch (const PrefetchInfo &pfi, std::vector< AddrPriority > &addresses) override
Public Member Functions inherited from QueuedPrefetcher
QueuedPrefetcher (const QueuedPrefetcherParams *p)
virtual ~QueuedPrefetcher ()
void notify (const PacketPtr &pkt, const PrefetchInfo &pfi) override
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.)
void insert (const PacketPtr &pkt, PrefetchInfo &new_pfi, int32_t priority)
PacketPtr getPacket () override
Tick nextPrefetchReadyTime () const override
void regStats () override
Register local statistics.
Public Member Functions inherited from BasePrefetcher
BasePrefetcher (const BasePrefetcherParams *p)
virtual ~BasePrefetcher ()
virtual void setCache (BaseCache *_cache)
virtual void notifyFill (const PacketPtr &pkt)
Notify prefetcher of cache fill.
void regProbeListeners () override
Register probe points for this object.
void probeNotify (const PacketPtr &pkt, bool miss)
Process a notification event from the ProbeListener.
void addEventProbe (SimObject *obj, const char *name)
Add a SimObject and a probe name to listen events from.
void addTLB (BaseTLB *tlb)
Add a BaseTLB object to be used whenever a translation is needed.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Attributes
AccessMapPatternMatching & ampm
AMPM prefetcher object.
DeltaCorrelatingPredictionTables & dcpt
DCPT prefetcher object.
Additional Inherited Members
Public Types inherited from QueuedPrefetcher
using AddrPriority = std::pair< Addr, int32_t >
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from QueuedPrefetcher
using const_iterator = std::list< DeferredPacket >::const_iterator
using iterator = std::list< DeferredPacket >::iterator
Protected Member Functions inherited from BasePrefetcher
bool observeAccess (const PacketPtr &pkt, bool miss) const
Determine if this access should be observed.
bool inCache (Addr addr, bool is_secure) const
Determine if address is in cache.
bool inMissQueue (Addr addr, bool is_secure) const
Determine if address is in cache miss queue.
bool hasBeenPrefetched (Addr addr, bool is_secure) const
bool samePage (Addr a, Addr b) const
Determine if addresses are on the same page.
Addr blockAddress (Addr a) const
Determine the address of the block in which a lays.
Addr blockIndex (Addr a) const
Determine the address of a at block granularity.
Addr pageAddress (Addr a) const
Determine the address of the page in which a lays.
Addr pageOffset (Addr a) const
Determine the page-offset of a.
Addr pageIthBlockAddress (Addr page, uint32_t i) const
Build the address of the i-th block inside the page.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from QueuedPrefetcher
std::list< DeferredPacket > pfq
std::list< DeferredPacket > pfqMissingTranslation
const unsigned queueSize
Maximum size of the prefetch queue.
const unsigned missingTranslationQueueSize
Maximum size of the queue holding prefetch requests with missing address translations.
const Cycles latency
Cycles after generation when a prefetch can first be issued.
const bool queueSquash
Squash queued prefetch if demand access observed.
const bool queueFilter
Filter prefetches if already queued.
const bool cacheSnoop
Snoop the cache before generating prefetch (cheating basically)
const bool tagPrefetch
Tag prefetch with PC of generating access?
const unsigned int throttleControlPct
Percentage of requests that can be throttled.
Stats::Scalar pfIdentified
Stats::Scalar pfBufferHit
Stats::Scalar pfInCache
Stats::Scalar pfRemovedFull
Stats::Scalar pfSpanPage
Protected Attributes inherited from BasePrefetcher
BaseCache * cache
Pointr to the parent cache.
unsigned blkSize
The block size of the parent cache.
unsigned lBlkSize
log_2(block size of the parent cache).
const bool onMiss
Only consult prefetcher on cache misses?
const bool onRead
Consult prefetcher on reads?
const bool onWrite
Consult prefetcher on reads?
const bool onData
Consult prefetcher on data accesses?
const bool onInst
Consult prefetcher on instruction accesses?
const MasterID masterId
Request id for prefetches.
const Addr pageBytes
const bool prefetchOnAccess
Prefetch on every access, not just misses.
const bool useVirtualAddresses
Use Virtual Addresses for prefetching.
Stats::Scalar pfIssued
uint64_t issuedPrefetches
Total prefetches issued.
uint64_t usefulPrefetches
Total prefetches that has been useful.
BaseTLB * tlb
Registered tlb for address translations.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 50 of file slim_ampm.hh.
Constructor & Destructor Documentation
SlimAMPMPrefetcher()
SlimAMPMPrefetcher::SlimAMPMPrefetcher (const SlimAMPMPrefetcherParams * p)
Copyright (c) 2018 Metempsy Technology Consulting All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer; redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution; neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Authors: Javier Bueno
Definition at line 35 of file slim_ampm.cc.
Referenced by calculatePrefetch().
~SlimAMPMPrefetcher()
SlimAMPMPrefetcher::~SlimAMPMPrefetcher () inline
Definition at line 58 of file slim_ampm.hh.
References calculatePrefetch().
Member Function Documentation
calculatePrefetch()
void SlimAMPMPrefetcher::calculatePrefetch (const PrefetchInfo & pfi, std::vector< AddrPriority > & addresses) override virtual
Implements QueuedPrefetcher.
Definition at line 41 of file slim_ampm.cc.
References ampm, DeltaCorrelatingPredictionTables::calculatePrefetch(), AccessMapPatternMatching::calculatePrefetch(), dcpt, and SlimAMPMPrefetcher().
Referenced by ~SlimAMPMPrefetcher().
Member Data Documentation
ampm
AccessMapPatternMatching& SlimAMPMPrefetcher::ampm private
AMPM prefetcher object.
Definition at line 53 of file slim_ampm.hh.
Referenced by calculatePrefetch().
dcpt
DeltaCorrelatingPredictionTables& SlimAMPMPrefetcher::dcpt private
DCPT prefetcher object.
Definition at line 55 of file slim_ampm.hh.
Referenced by calculatePrefetch().
The documentation for this class was generated from the following files:
mem/cache/prefetch/slim_ampm.hh
mem/cache/prefetch/slim_ampm.cc