gem5: MinorCPU Class Reference
MinorCPU Class Reference
MinorCPU is an in-order CPU model with four fixed pipeline stages:
#include <cpu.hh>
Classes
class MinorCPUPort
Provide a non-protected base class for Minor's Ports as derived classes are created by Fetch1 and Execute.
Public Member Functions
MinorCPU (MinorCPUParams *params)
~MinorCPU ()
void init () override
Starting, waking and initialisation.
void startup () override
startup() is the final initialization call before simulation.
void wakeup (ThreadID tid) override
Addr dbg_vtophys (Addr addr)
void regStats () override
Stats interface from SimObject (by way of BaseCPU)
Counter totalInsts () const override
Simple inst count interface from BaseCPU.
Counter totalOps () const override
void serializeThread (CheckpointOut &cp, ThreadID tid) const override
Serialize a single thread.
void unserializeThread (CheckpointIn &cp, ThreadID tid) override
Unserialize one thread.
void serialize (CheckpointOut &cp) const override
Serialize pipeline data.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
DrainState drain () override
Drain interface.
void drainResume () override
Resume execution after a successful drain.
void signalDrainDone ()
Signal from Pipeline that MinorCPU should signal that a drain is complete and set its drainState.
void memWriteback () override
Write back dirty buffers to memory using functional writes.
void switchOut () override
Switching interface from BaseCPU.
void takeOverFrom (BaseCPU *old_cpu) override
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void activateContext (ThreadID thread_id) override
Thread activation interface from BaseCPU.
void suspendContext (ThreadID thread_id) override
Notify the CPU that the indicated context is now suspended.
std::vector< ThreadID > roundRobinPriority (ThreadID priority)
Thread scheduling utility functions.
std::vector< ThreadID > randomPriority ()
void wakeupOnEvent (unsigned int stage_id)
Interface for stages to signal that they have become active after a callback or eventq event where the pipeline itself may have already been idled.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
virtual void haltContext (ThreadID thread_num)
Notify the CPU that the indicated context is now halted.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
virtual ThreadContext * getContext (int tn)
Given a thread num get tho thread context for it.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void regProbePoints () override
Register probe points for this object.
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
virtual void verifyMemoryMode () const
Verify that the system is in a memory mode supported by the CPU.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
Minor::MinorActivityRecorder * activityRecorder
Activity recording for pipeline.
std::vector< Minor::MinorThread * > threads
These are thread state-representing objects for this CPU.
Enums::ThreadPolicy threadPolicy
Thread Scheduling Policy (RoundRobin, Random, etc)
Minor::MinorStats stats
Processor-specific statistics.
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Protected Member Functions
Port & getDataPort () override
Return a reference to the data port.
Port & getInstPort () override
Return a reference to the instruction port.
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
Minor::Pipeline * pipeline
pipeline is a container for the clockable pipeline stage objects.
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Detailed Description
MinorCPU is an in-order CPU model with four fixed pipeline stages:
Fetch1 - fetches lines from memory Fetch2 - decomposes lines into macro-op instructions Decode - decomposes macro-ops into micro-ops Execute - executes those micro-ops
This pipeline is carried in the MinorCPU::pipeline object. The exec_context interface is not carried by MinorCPU but by Minor::ExecContext objects created by Minor::Execute.
Definition at line 79 of file cpu.hh.
Constructor & Destructor Documentation
MinorCPU()
MinorCPU::MinorCPU (MinorCPUParams * params)
Definition at line 50 of file cpu.cc.
References activityRecorder, fatal, FullSystem, SimpleThread::getTC(), ThreadContext::Halted, ArmISA::i, Minor::MinorDynInst::init(), BaseCPU::numThreads, SimpleThread::setStatus(), BaseCPU::threadContexts, and threads.
Referenced by wakeupOnEvent().
~MinorCPU()
MinorCPU::~MinorCPU ()
Definition at line 84 of file cpu.cc.
References pipeline, and threads.
Member Function Documentation
activateContext()
void MinorCPU::activateContext (ThreadID thread_id) override virtual
Thread activation interface from BaseCPU.
Reimplemented from BaseCPU.
Definition at line 280 of file cpu.cc.
References BaseCPU::activateContext(), Minor::Pipeline::CPUStageId, DPRINTF, Minor::MinorStats::quiesceCycles, stats, threads, and wakeupOnEvent().
dbg_vtophys()
Addr MinorCPU::dbg_vtophys (Addr addr)
Definition at line 160 of file cpu.cc.
References panic.
drain()
DrainState MinorCPU::drain () override virtual
Drain interface.
Implements Drainable.
Definition at line 193 of file cpu.cc.
References BaseCPU::deschedulePowerGatingEvent(), DPRINTF, Drained, Draining, and BaseCPU::switchedOut().
drainResume()
void MinorCPU::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 224 of file cpu.cc.
References DPRINTF, fatal, System::isTimingMode(), BaseCPU::numThreads, BaseCPU::schedulePowerGatingEvent(), BaseCPU::switchedOut(), BaseCPU::system, and wakeup().
getDataPort()
Port & MinorCPU::getDataPort () override protected virtual
Return a reference to the data port.
Implements BaseCPU.
Definition at line 331 of file cpu.cc.
getInstPort()
Port & MinorCPU::getInstPort () override protected virtual
Return a reference to the instruction port.
Implements BaseCPU.
Definition at line 325 of file cpu.cc.
init()
void MinorCPU::init () override virtual
Starting, waking and initialisation.
Reimplemented from BaseCPU.
Definition at line 94 of file cpu.cc.
References BaseCPU::cpuId(), fatal, FullSystem, BaseCPU::getContext(), System::getMemoryMode(), BaseCPU::init(), AlphaISA::initCPU(), ThreadContext::initMemProxies(), BaseCPU::params(), BaseCPU::system, and threads.
memWriteback()
void MinorCPU::memWriteback () override virtual
Write back dirty buffers to memory using functional writes.
After returning, an object implementing this method should have written all its dirty data back to memory. This method is typically used to prepare a system with caches for checkpointing.
Reimplemented from SimObject.
Definition at line 254 of file cpu.cc.
References DPRINTF.
randomPriority()
std::vector<ThreadID> MinorCPU::randomPriority () inline
Definition at line 178 of file cpu.hh.
References ArmISA::i.
Referenced by Minor::Execute::getCommittingThread(), Minor::Execute::getIssuingThread(), Minor::Decode::getScheduledThread(), Minor::Fetch2::getScheduledThread(), and Minor::Fetch1::getScheduledThread().
regStats()
void MinorCPU::regStats () override virtual
Stats interface from SimObject (by way of BaseCPU)
Reimplemented from BaseCPU.
Definition at line 126 of file cpu.cc.
References SimObject::name(), Minor::MinorStats::regStats(), BaseCPU::regStats(), and stats.
roundRobinPriority()
std::vector<ThreadID> MinorCPU::roundRobinPriority (ThreadID priority) inline
Thread scheduling utility functions.
Definition at line 169 of file cpu.hh.
References ArmISA::i.
Referenced by Minor::Execute::getCommittingThread(), Minor::Execute::getIssuingThread(), Minor::Decode::getScheduledThread(), Minor::Fetch2::getScheduledThread(), and Minor::Fetch1::getScheduledThread().
serialize()
void MinorCPU::serialize (CheckpointOut & cp) const override virtual
Serialize pipeline data.
Reimplemented from BaseCPU.
Definition at line 146 of file cpu.cc.
References BaseCPU::serialize().
serializeThread()
void MinorCPU::serializeThread (CheckpointOut & cp, ThreadID tid) const override virtual
Serialize a single thread.
Parameters
cp The stream to serialize to.
tid ID of the current thread.
Reimplemented from BaseCPU.
Definition at line 134 of file cpu.cc.
References threads.
signalDrainDone()
void MinorCPU::signalDrainDone ()
Signal from Pipeline that MinorCPU should signal that a drain is complete and set its drainState.
Definition at line 217 of file cpu.cc.
References DPRINTF, and Drainable::signalDrainDone().
Referenced by Minor::Pipeline::evaluate().
startup()
void MinorCPU::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from BaseCPU.
Definition at line 180 of file cpu.cc.
References DPRINTF, BaseCPU::numThreads, BaseCPU::startup(), and threads.
suspendContext()
void MinorCPU::suspendContext (ThreadID thread_num) override virtual
Notify the CPU that the indicated context is now suspended.
Check if possible to enter a lower power state
Reimplemented from BaseCPU.
Definition at line 299 of file cpu.cc.
References DPRINTF, BaseCPU::suspendContext(), and threads.
switchOut()
void MinorCPU::switchOut () override virtual
Switching interface from BaseCPU.
Reimplemented from BaseCPU.
Definition at line 260 of file cpu.cc.
References activityRecorder, DPRINTF, ActivityRecorder::reset(), BaseCPU::switchedOut(), and BaseCPU::switchOut().
takeOverFrom()
void MinorCPU::takeOverFrom (BaseCPU * cpu) override virtual
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
A CPU model implementing this method is expected to initialize its state from the old CPU and connect its memory (unless they are already connected) to the memories connected to the old CPU.
Parameters
cpu CPU to initialize read state from.
Reimplemented from BaseCPU.
Definition at line 272 of file cpu.cc.
References DPRINTF, and BaseCPU::takeOverFrom().
totalInsts()
Counter MinorCPU::totalInsts () const override virtual
Simple inst count interface from BaseCPU.
Implements BaseCPU.
Definition at line 337 of file cpu.cc.
References ArmISA::i, and threads.
totalOps()
Counter MinorCPU::totalOps () const override virtual
Implements BaseCPU.
Definition at line 348 of file cpu.cc.
References ArmISA::i, and threads.
unserialize()
void MinorCPU::unserialize (CheckpointIn & cp) override virtual
Reconstruct the state of this object from a checkpoint.
Note
CPU models should normally overload the unserializeThread() method instead of the unserialize() method as this provides a uniform data format for all CPU models and promotes better code reuse.
Parameters
cp The checkpoint use.
Reimplemented from BaseCPU.
Definition at line 153 of file cpu.cc.
References BaseCPU::unserialize().
unserializeThread()
void MinorCPU::unserializeThread (CheckpointIn & cp, ThreadID tid) override virtual
Unserialize one thread.
Parameters
cp The checkpoint use.
tid ID of the current thread.
Reimplemented from BaseCPU.
Definition at line 140 of file cpu.cc.
References threads.
wakeup()
void MinorCPU::wakeup (ThreadID tid) override virtual
Implements BaseCPU.
Definition at line 169 of file cpu.cc.
References DPRINTF, BaseCPU::numThreads, ArmISA::status, ThreadContext::Suspended, and threads.
Referenced by drainResume(), Minor::LSQ::recvTimingSnoopReq(), and Minor::LSQ::threadSnoop().
wakeupOnEvent()
void MinorCPU::wakeupOnEvent (unsigned int stage_id)
Interface for stages to signal that they have become active after a callback or eventq event where the pipeline itself may have already been idled.
The stage argument should be from the enumeration Pipeline::StageId
Definition at line 309 of file cpu.cc.
References ActivityRecorder::activateStage(), activityRecorder, DPRINTF, and MinorCPU().
Referenced by activateContext(), Minor::Execute::drain(), Minor::Execute::drainResume(), Minor::Execute::evaluate(), Minor::Fetch1::evaluate(), Minor::LSQ::SingleDataRequest::finish(), Minor::LSQ::SplitDataRequest::finish(), Minor::Fetch1::recvTimingResp(), Minor::LSQ::recvTimingResp(), Minor::Fetch1::tryToSendToTransfers(), and Minor::Fetch1::wakeupFetch().
Member Data Documentation
activityRecorder
Minor::MinorActivityRecorder* MinorCPU::activityRecorder
Activity recording for pipeline.
This belongs to Pipeline but stages will access it through the CPU as the MinorCPU object actually mediates idling behaviour
Definition at line 90 of file cpu.hh.
Referenced by Minor::Decode::evaluate(), Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), Minor::Fetch1::evaluate(), Minor::Execute::issue(), MinorCPU(), switchOut(), and wakeupOnEvent().
pipeline
Minor::Pipeline* MinorCPU::pipeline protected
pipeline is a container for the clockable pipeline stage objects.
Elements of pipeline call TheISA to implement the model.
Definition at line 84 of file cpu.hh.
Referenced by ~MinorCPU().
stats
Minor::MinorStats MinorCPU::stats
Processor-specific statistics.
Definition at line 136 of file cpu.hh.
Referenced by activateContext(), Minor::Execute::commit(), Minor::Execute::commitInst(), Minor::Execute::doInstCommitAccounting(), and regStats().
threadPolicy
Enums::ThreadPolicy MinorCPU::threadPolicy
Thread Scheduling Policy (RoundRobin, Random, etc)
Definition at line 114 of file cpu.hh.
Referenced by Minor::Execute::getCommittingThread(), Minor::Execute::getIssuingThread(), Minor::Decode::getScheduledThread(), Minor::Fetch2::getScheduledThread(), and Minor::Fetch1::getScheduledThread().
threads
std::vector<Minor::MinorThread *> MinorCPU::threads
These are thread state-representing objects for this CPU.
If you need a ThreadContext for any reason, use threads[threadId]->getTC()
Definition at line 95 of file cpu.hh.
Referenced by activateContext(), Minor::Execute::commitInst(), Minor::LSQ::LSQRequest::completeDisabledMemAccess(), Minor::LSQ::LSQRequest::disableMemAccess(), Minor::Execute::doInstCommitAccounting(), Minor::Execute::executeMemRefInst(), Minor::Fetch1::fetchLine(), Minor::Execute::handleMemResponse(), init(), MinorCPU(), Minor::LSQ::pushRequest(), serializeThread(), startup(), suspendContext(), totalInsts(), totalOps(), Minor::Execute::tryPCEvents(), Minor::LSQ::tryToSendToTransfers(), Minor::LSQ::LSQRequest::tryToSuppressFault(), unserializeThread(), wakeup(), and ~MinorCPU().
The documentation for this class was generated from the following files:
cpu/minor/cpu.hh
cpu/minor/cpu.cc