gem5: ArmISA::TableWalker::LongDescriptor Class Reference
ArmISA::TableWalker::LongDescriptor Class Reference
Long-descriptor format (LPAE)
#include <table_walker.hh>
Public Types
enum EntryType { Invalid, Table, Block, Page }
Descriptor type.
Public Member Functions
LongDescriptor ()
virtual uint64_t getRawData () const
virtual std::string dbgHeader () const
bool secure (bool have_security, WalkerState *currState) const
Returns true if this entry targets the secure physical address map.
EntryType type () const
Return the descriptor type.
uint8_t offsetBits () const
Return the bit width of the page/block offset.
Addr pfn () const
Return the physical frame, bits shifted right.
Addr paddr (Addr va) const
Return the complete physical address given a VA.
Addr paddr () const
Return the physical address of the entry.
Addr nextTableAddr () const
Return the address of the next page table.
Addr nextDescAddr (Addr va) const
Return the address of the next descriptor.
bool xn () const
Is execution allowed on this mapping?
bool pxn () const
Is privileged execution allowed on this mapping? (LPAE only)
bool contiguousHint () const
Contiguous hint bit.
bool global (WalkerState *currState) const
Is the translation global (no asid used)?
bool af () const
Returns true if the access flag (AF) is set.
uint8_t sh () const
2-bit shareability field
uint8_t ap () const
2-bit access protection flags
bool rw () const
Read/write access protection flag.
bool user () const
User/privileged level access protection flag.
TlbEntry::DomainType domain () const
uint8_t attrIndx () const
Attribute index.
uint8_t memAttr () const
Memory attributes, only used by stage 2 translations.
void setAf ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
bool secureTable () const
Whether the subsequent levels of lookup are secure.
uint8_t apTable () const
Two bit access protection flags for subsequent levels of lookup.
uint8_t rwTable () const
R/W protection flag for subsequent levels of lookup.
uint8_t userTable () const
User/privileged mode protection flag for subsequent levels of lookup.
bool xnTable () const
Is execution allowed on subsequent lookup levels?
bool pxnTable () const
Is privileged execution allowed on subsequent lookup levels?
Public Member Functions inherited from ArmISA::TableWalker::DescriptorBase
DescriptorBase ()
virtual uint8_t texcb () const
virtual bool shareable () const
Static Public Member Functions
static uint8_t ap (bool rw, bool user)
Return the AP bits as compatible with the AP[2:0] format.
Public Attributes
uint64_t data
The raw bits of the entry.
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
bool aarch64
True if the current lookup is performed in AArch64 state.
GrainSize grainSize
Width of the granule size in bits.
Public Attributes inherited from ArmISA::TableWalker::DescriptorBase
LookupLevel lookupLevel
Current lookup level for this descriptor.
Detailed Description
Long-descriptor format (LPAE)
Definition at line 378 of file table_walker.hh.
Member Enumeration Documentation
EntryType
enum ArmISA::TableWalker::LongDescriptor::EntryType
Descriptor type.
Enumerator
Invalid
Table
Block
Page
Definition at line 381 of file table_walker.hh.
Constructor & Destructor Documentation
LongDescriptor()
ArmISA::TableWalker::LongDescriptor::LongDescriptor () inline
Definition at line 388 of file table_walker.hh.
Member Function Documentation
af()
bool ArmISA::TableWalker::LongDescriptor::af () const inline
Returns true if the access flag (AF) is set.
Definition at line 569 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
ap() [1/2]
uint8_t ArmISA::TableWalker::LongDescriptor::ap () const inline virtual
2-bit access protection flags
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 583 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor(), and ArmISA::TableWalker::insertTableEntry().
ap() [2/2]
static uint8_t ArmISA::TableWalker::LongDescriptor::ap (bool rw, bool user) inline static
Return the AP bits as compatible with the AP[2:0] format.
Utility function used to simplify the code in the TLB for performing permission checks.
Definition at line 607 of file table_walker.hh.
apTable()
uint8_t ArmISA::TableWalker::LongDescriptor::apTable () const inline
Two bit access protection flags for subsequent levels of lookup.
Definition at line 655 of file table_walker.hh.
References bits(), and type.
attrIndx()
uint8_t ArmISA::TableWalker::LongDescriptor::attrIndx () const inline
Attribute index.
Definition at line 620 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::memAttrsAArch64(), and ArmISA::TableWalker::memAttrsLPAE().
contiguousHint()
bool ArmISA::TableWalker::LongDescriptor::contiguousHint () const inline
Contiguous hint bit.
Definition at line 544 of file table_walker.hh.
References bits(), and type.
dbgHeader()
virtual std::string ArmISA::TableWalker::LongDescriptor::dbgHeader () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 402 of file table_walker.hh.
References ArmISA::L3, ArmISA::TableWalker::DescriptorBase::lookupLevel, Page, and type.
dirty()
bool ArmISA::TableWalker::LongDescriptor::dirty () const inline
This entry needs to be written back to memory.
Definition at line 642 of file table_walker.hh.
domain()
TlbEntry::DomainType ArmISA::TableWalker::LongDescriptor::domain () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 612 of file table_walker.hh.
References ArmISA::TlbEntry::Client, and type.
getRawData()
virtual uint64_t ArmISA::TableWalker::LongDescriptor::getRawData () const inline virtual
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 397 of file table_walker.hh.
global()
bool ArmISA::TableWalker::LongDescriptor::global (WalkerState * currState) const inline virtual
Is the translation global (no asid used)?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 551 of file table_walker.hh.
References ArmISA::TableWalker::WalkerState::aarch64, bits(), ArmISA::TableWalker::WalkerState::el, ArmISA::EL2, ArmISA::EL3, ArmISA::TableWalker::WalkerState::isSecure, ArmISA::TableWalker::WalkerState::secureLookup, and type.
memAttr()
uint8_t ArmISA::TableWalker::LongDescriptor::memAttr () const inline
Memory attributes, only used by stage 2 translations.
Definition at line 627 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::memAttrsAArch64(), and ArmISA::TableWalker::memAttrsLPAE().
nextDescAddr()
Addr ArmISA::TableWalker::LongDescriptor::nextDescAddr (Addr va) const inline
Return the address of the next descriptor.
Definition at line 511 of file table_walker.hh.
References bits(), ArmISA::L1, ArmISA::TableWalker::DescriptorBase::lookupLevel, ArmISA::pa, ArmISA::stride, and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
nextTableAddr()
Addr ArmISA::TableWalker::LongDescriptor::nextTableAddr () const inline
Return the address of the next page table.
Definition at line 501 of file table_walker.hh.
References mbits(), and type.
offsetBits()
uint8_t ArmISA::TableWalker::LongDescriptor::offsetBits () const inline virtual
Return the bit width of the page/block offset.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 447 of file table_walker.hh.
References ArmISA::TableWalker::Grain16KB, ArmISA::TableWalker::Grain4KB, ArmISA::TableWalker::Grain64KB, ArmISA::L1, ArmISA::TableWalker::DescriptorBase::lookupLevel, panic, and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
paddr() [1/2]
Addr ArmISA::TableWalker::LongDescriptor::paddr (Addr va) const inline
Return the complete physical address given a VA.
Definition at line 484 of file table_walker.hh.
References mbits(), ArmISA::n, and ArmISA::TableWalker::DescriptorBase::offsetBits().
paddr() [2/2]
Addr ArmISA::TableWalker::LongDescriptor::paddr () const inline
Return the physical address of the entry.
Definition at line 493 of file table_walker.hh.
References mbits(), and ArmISA::TableWalker::DescriptorBase::offsetBits().
pfn()
Addr ArmISA::TableWalker::LongDescriptor::pfn () const inline virtual
Return the physical frame, bits shifted right.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 476 of file table_walker.hh.
References bits(), and ArmISA::TableWalker::DescriptorBase::offsetBits().
pxn()
bool ArmISA::TableWalker::LongDescriptor::pxn () const inline
Is privileged execution allowed on this mapping? (LPAE only)
Definition at line 537 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor(), and ArmISA::TableWalker::insertTableEntry().
pxnTable()
bool ArmISA::TableWalker::LongDescriptor::pxnTable () const inline
Is privileged execution allowed on subsequent lookup levels?
Definition at line 684 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
rw()
bool ArmISA::TableWalker::LongDescriptor::rw () const inline
Read/write access protection flag.
Definition at line 591 of file table_walker.hh.
References bits(), and type.
rwTable()
uint8_t ArmISA::TableWalker::LongDescriptor::rwTable () const inline
R/W protection flag for subsequent levels of lookup.
Definition at line 662 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
secure()
bool ArmISA::TableWalker::LongDescriptor::secure (bool have_security, WalkerState * currState) const inline virtual
Returns true if this entry targets the secure physical address map.
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 417 of file table_walker.hh.
References bits(), ArmISA::TableWalker::WalkerState::secureLookup, and type.
secureTable()
bool ArmISA::TableWalker::LongDescriptor::secureTable () const inline
Whether the subsequent levels of lookup are secure.
Definition at line 648 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
setAf()
void ArmISA::TableWalker::LongDescriptor::setAf () inline
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 635 of file table_walker.hh.
sh()
uint8_t ArmISA::TableWalker::LongDescriptor::sh () const inline
2-bit shareability field
Definition at line 576 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::memAttrsAArch64(), and ArmISA::TableWalker::memAttrsLPAE().
type()
EntryType ArmISA::TableWalker::LongDescriptor::type () const inline
Return the descriptor type.
Definition at line 430 of file table_walker.hh.
References bits(), ArmISA::TableWalker::Grain4KB, MipsISA::Invalid, ArmISA::L0, ArmISA::L2, ArmISA::L3, and ArmISA::TableWalker::DescriptorBase::lookupLevel.
Referenced by ArmISA::TableWalker::doLongDescriptor().
user()
bool ArmISA::TableWalker::LongDescriptor::user () const inline
User/privileged level access protection flag.
Definition at line 598 of file table_walker.hh.
References bits(), and type.
userTable()
uint8_t ArmISA::TableWalker::LongDescriptor::userTable () const inline
User/privileged mode protection flag for subsequent levels of lookup.
Definition at line 670 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
xn()
bool ArmISA::TableWalker::LongDescriptor::xn () const inline virtual
Is execution allowed on this mapping?
Implements ArmISA::TableWalker::DescriptorBase.
Definition at line 530 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
xnTable()
bool ArmISA::TableWalker::LongDescriptor::xnTable () const inline
Is execution allowed on subsequent lookup levels?
Definition at line 677 of file table_walker.hh.
References bits(), and type.
Referenced by ArmISA::TableWalker::doLongDescriptor().
Member Data Documentation
_dirty
bool ArmISA::TableWalker::LongDescriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 395 of file table_walker.hh.
aarch64
bool ArmISA::TableWalker::LongDescriptor::aarch64
True if the current lookup is performed in AArch64 state.
Definition at line 424 of file table_walker.hh.
Referenced by ArmISA::TableWalker::processWalkAArch64(), and ArmISA::TableWalker::processWalkLPAE().
data
uint64_t ArmISA::TableWalker::LongDescriptor::data
The raw bits of the entry.
Definition at line 391 of file table_walker.hh.
Referenced by ArmISA::TableWalker::doLongDescriptor(), ArmISA::TableWalker::processWalkAArch64(), and ArmISA::TableWalker::processWalkLPAE().
grainSize
GrainSize ArmISA::TableWalker::LongDescriptor::grainSize
Width of the granule size in bits.
Definition at line 427 of file table_walker.hh.
Referenced by ArmISA::TableWalker::processWalkAArch64(), and ArmISA::TableWalker::processWalkLPAE().
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh