gem5: PowerISA::IntOp Class Reference
PowerISA::IntOp Class Reference
We provide a base class for integer operations and then inherit for several other classes.
#include <integer.hh>
Protected Member Functions
IntOp (const char *mnem, MachInst _machInst, OpClass __opClass)
Constructor.
uint32_t makeCRField (int32_t a, int32_t b, uint32_t xerSO) const
uint32_t makeCRField (uint32_t a, uint32_t b, uint32_t xerSO) const
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const override
Internal function to generate disassembly string.
Protected Member Functions inherited from PowerISA::PowerStaticInst
PowerStaticInst (const char *mnem, MachInst _machInst, OpClass __opClass)
uint32_t insertCRField (uint32_t cr, uint32_t bf, uint32_t value) const
void printReg (std::ostream &os, RegId reg) const
Print a register name for disassembly given the unique dependence tag number (FP or int).
std::string generateDisassembly (Addr pc, const SymbolTable *symtab) const override
Internal function to generate disassembly string.
void advancePC (PowerISA::PCState &pcState) const override
size_t asBytes (void *buf, size_t max_size) override
Instruction classes can override this function to return a a representation of themselves as a blob of bytes, generally assumed to be that instructions ExtMachInst.
Protected Member Functions inherited from StaticInst
StaticInst (const char *_mnemonic, ExtMachInst _machInst, OpClass __opClass)
Constructor.
template<typename T >
size_t simpleAsBytes (void *buf, size_t max_size, const T &t)
Protected Attributes
bool rcSet
bool oeSet
uint32_t sh
Protected Attributes inherited from StaticInst
std::bitset< Num_Flags > flags
Flag values for this instruction.
OpClass _opClass
See opClass().
int8_t _numSrcRegs
See numSrcRegs().
int8_t _numDestRegs
See numDestRegs().
RegId _destRegIdx [MaxInstDestRegs]
See destRegIdx().
RegId _srcRegIdx [MaxInstSrcRegs]
See srcRegIdx().
const char * mnemonic
Base mnemonic (e.g., "add").
std::string * cachedDisassembly
String representation of disassembly (lazily evaluated via disassemble()).
int8_t _numFPDestRegs
The following are used to track physical register usage for machines with separate int & FP reg files.
int8_t _numIntDestRegs
int8_t _numCCDestRegs
int8_t _numVecDestRegs
To use in architectures with vector register file.
int8_t _numVecElemDestRegs
int8_t _numVecPredDestRegs
Additional Inherited Members
Public Types inherited from StaticInst
enum { MaxInstSrcRegs = TheISA::MaxInstSrcRegs, MaxInstDestRegs = TheISA::MaxInstDestRegs }
typedef TheISA::ExtMachInst ExtMachInst
Binary extended machine instruction type.
Public Member Functions inherited from StaticInst
void setFirstMicroop ()
void setLastMicroop ()
void setDelayedCommit ()
void setFlag (Flags f)
OpClass opClass () const
Operation class. Used to select appropriate function unit in issue.
const RegId & destRegIdx (int i) const
Return logical index (architectural reg num) of i'th destination reg.
const RegId & srcRegIdx (int i) const
Return logical index (architectural reg num) of i'th source reg.
virtual ~StaticInst ()
virtual Fault execute (ExecContext *xc, Trace::InstRecord *traceData) const =0
virtual Fault initiateAcc (ExecContext *xc, Trace::InstRecord *traceData) const
virtual Fault completeAcc (Packet *pkt, ExecContext *xc, Trace::InstRecord *traceData) const
virtual void advancePC (TheISA::PCState &pcState) const =0
virtual StaticInstPtr fetchMicroop (MicroPC upc) const
Return the microop that goes with a particular micropc.
virtual TheISA::PCState branchTarget (const TheISA::PCState &pc) const
Return the target address for a PC-relative branch.
virtual TheISA::PCState branchTarget (ThreadContext *tc) const
Return the target address for an indirect branch (jump).
bool hasBranchTarget (const TheISA::PCState &pc, ThreadContext *tc, TheISA::PCState &tgt) const
Return true if the instruction is a control transfer, and if so, return the target address as well.
virtual const std::string & disassemble (Addr pc, const SymbolTable *symtab=0) const
Return string representation of disassembled instruction.
void printFlags (std::ostream &outs, const std::string &separator) const
Print a separator separated list of this instruction's set flag names on the given stream.
std::string getName ()
Return name of machine instruction.
int8_t numSrcRegs () const
Number of source registers.
int8_t numDestRegs () const
Number of destination registers.
int8_t numFPDestRegs () const
Number of floating-point destination regs.
int8_t numIntDestRegs () const
Number of integer destination regs.
int8_t numVecDestRegs () const
Number of vector destination regs.
int8_t numVecElemDestRegs () const
Number of vector element destination regs.
int8_t numVecPredDestRegs () const
Number of predicate destination regs.
int8_t numCCDestRegs () const
Number of coprocesor destination regs.
bool isNop () const
bool isMemRef () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isStoreConditional () const
bool isInstPrefetch () const
bool isDataPrefetch () const
bool isPrefetch () const
bool isInteger () const
bool isFloating () const
bool isVector () const
bool isCC () const
bool isControl () const
bool isCall () const
bool isReturn () const
bool isDirectCtrl () const
bool isIndirectCtrl () const
bool isCondCtrl () const
bool isUncondCtrl () const
bool isCondDelaySlot () const
bool isThreadSync () const
bool isSerializing () const
bool isSerializeBefore () const
bool isSerializeAfter () const
bool isSquashAfter () const
bool isMemBarrier () const
bool isWriteBarrier () const
bool isNonSpeculative () const
bool isQuiesce () const
bool isIprAccess () const
bool isUnverifiable () const
bool isSyscall () const
bool isMacroop () const
bool isMicroop () const
bool isDelayedCommit () const
bool isLastMicroop () const
bool isFirstMicroop () const
bool isMicroBranch () const
Public Member Functions inherited from RefCounted
RefCounted ()
We initialize the reference count to zero and the first object to take ownership of it must increment it to one.
virtual ~RefCounted ()
We make the destructor virtual because we're likely to have virtual functions on reference counted objects.
void incref () const
Increment the reference count.
void decref () const
Decrement the reference count and destroy the object if all references are gone.
Public Attributes inherited from StaticInst
const ExtMachInst machInst
The binary machine instruction.
Static Public Attributes inherited from StaticInst
static StaticInstPtr nullStaticInstPtr
Pointer to a statically allocated "null" instruction object.
static StaticInstPtr nopStaticInstPtr = new NopStaticInst
Pointer to a statically allocated generic "nop" instruction object.
Detailed Description
We provide a base class for integer operations and then inherit for several other classes.
These specialise for instructions using immediate values and also rotate instructions. We also need to have versions that consider the Rc and OE bits. Base class for integer operations.
Definition at line 51 of file integer.hh.
Constructor & Destructor Documentation
IntOp()
PowerISA::IntOp::IntOp (const char * mnem, MachInst _machInst, OpClass __opClass) inline protected
Constructor.
Definition at line 62 of file integer.hh.
Member Function Documentation
generateDisassembly()
string IntOp::generateDisassembly (Addr pc, const SymbolTable * symtab) const override protected virtual
Internal function to generate disassembly string.
Implements StaticInst.
Reimplemented in PowerISA::IntRotateOp, PowerISA::IntShiftOp, and PowerISA::IntImmOp.
Definition at line 37 of file integer.cc.
References ccprintf(), and ArmISA::ss.
Referenced by PowerISA::IntImmOp::IntImmOp(), PowerISA::IntShiftOp::IntShiftOp(), makeCRField(), and PowerISA::IntRotateOp::rotateValue().
makeCRField() [1/2]
uint32_t PowerISA::IntOp::makeCRField (int32_t a, int32_t b, uint32_t xerSO) const inline protected
Definition at line 70 of file integer.hh.
References ArmISA::c.
makeCRField() [2/2]
uint32_t PowerISA::IntOp::makeCRField (uint32_t a, uint32_t b, uint32_t xerSO) const inline protected
Definition at line 83 of file integer.hh.
References ArmISA::c, generateDisassembly(), and MipsISA::pc.
Member Data Documentation
oeSet
bool PowerISA::IntOp::oeSet protected
Definition at line 56 of file integer.hh.
rcSet
bool PowerISA::IntOp::rcSet protected
Definition at line 55 of file integer.hh.
sh
uint32_t PowerISA::IntOp::sh protected
Definition at line 59 of file integer.hh.
The documentation for this class was generated from the following files:
arch/power/insts/integer.hh
arch/power/insts/integer.cc