gem5: DistEtherLink::LocalIface Class Reference
DistEtherLink::LocalIface Class Reference
Interface to the local simulated system.
#include <dist_etherlink.hh>
Public Member Functions
LocalIface (const std::string &name, TxLink *tx, RxLink *rx, DistIface *m)
bool recvPacket (EthPacketPtr pkt)
void sendDone ()
bool isBusy ()
Public Member Functions inherited from EtherInt
EtherInt (const std::string &name, int idx=InvalidPortID)
virtual ~EtherInt ()
const std::string & name () const
Return port name (for DPRINTF).
void bind (Port &peer) override
Attach to a peer port.
void unbind () override
Dettach from a peer port.
void setPeer (EtherInt *p)
EtherInt * getPeer ()
void recvDone ()
bool sendPacket (EthPacketPtr packet)
bool askBusy ()
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Private Attributes
TxLink * txLink
Additional Inherited Members
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes inherited from EtherInt
std::string portName
EtherInt * peer
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Interface to the local simulated system.
Definition at line 183 of file dist_etherlink.hh.
Constructor & Destructor Documentation
LocalIface()
DistEtherLink::LocalIface::LocalIface (const std::string & name, TxLink * tx, RxLink * rx, DistIface * m)
Definition at line 246 of file dist_etherlink.cc.
References DistEtherLink::DistEtherLink(), DistEtherLink::TxLink::setDistInt(), DistEtherLink::RxLink::setDistInt(), and DistEtherLink::Link::setLocalInt().
Member Function Documentation
isBusy()
bool DistEtherLink::LocalIface::isBusy () inline virtual
Reimplemented from EtherInt.
Definition at line 194 of file dist_etherlink.hh.
References DistEtherLink::Link::busy().
recvPacket()
bool DistEtherLink::LocalIface::recvPacket (EthPacketPtr pkt) inline virtual
Implements EtherInt.
Definition at line 192 of file dist_etherlink.hh.
References DistEtherLink::TxLink::transmit().
sendDone()
void DistEtherLink::LocalIface::sendDone () inline virtual
Implements EtherInt.
Definition at line 193 of file dist_etherlink.hh.
Referenced by DistEtherLink::TxLink::txDone().
Member Data Documentation
txLink
TxLink* DistEtherLink::LocalIface::txLink private
Definition at line 186 of file dist_etherlink.hh.
The documentation for this class was generated from the following files:
dev/net/dist_etherlink.hh
dev/net/dist_etherlink.cc