gem5: AlphaISA::Kernel::Statistics Class Reference
AlphaISA::Kernel::Statistics Class Reference
#include <kernel_stats.hh>
Public Member Functions
Statistics ()
void regStats (const std::string &name)
void mode (cpu_mode newmode, ThreadContext *tc)
void context (Addr oldpcbb, Addr newpcbb, ThreadContext *tc)
void callpal (int code, ThreadContext *tc)
void hwrei ()
void swpipl (int ipl)
void setIdleProcess (Addr idle, ThreadContext *tc)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Kernel::Statistics
virtual ~Statistics ()
const std::string name () const
void arm ()
void quiesce ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Member Functions
void changeMode (cpu_mode newmode, ThreadContext *tc)
Protected Attributes
Addr idleProcess
cpu_mode themode
Tick lastModeTick
Protected Attributes inherited from Kernel::Statistics
std::string myname
Stats::Scalar _arm
Stats::Scalar _quiesce
Private Attributes
Stats::Vector _callpal
Stats::Scalar _hwrei
Stats::Vector _mode
Stats::Vector _modeGood
Stats::Formula _modeFraction
Stats::Vector _modeTicks
Stats::Scalar _swap_context
Stats::Vector _iplCount
Stats::Vector _iplGood
Stats::Vector _iplTicks
Stats::Formula _iplUsed
int iplLast
Tick iplLastTick
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 51 of file kernel_stats.hh.
Constructor & Destructor Documentation
Statistics()
AlphaISA::Kernel::Statistics::Statistics ()
Definition at line 53 of file kernel_stats.cc.
References _callpal, _hwrei, _iplCount, _iplGood, _iplTicks, _iplUsed, _mode, _modeFraction, _modeGood, _modeTicks, _swap_context, AlphaISA::Kernel::cpu_mode_num, Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), Kernel::Statistics::name(), PAL::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nonan, Stats::nozero, PAL::NumCodes, Stats::pdf, regStats(), Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and Stats::total.
Member Function Documentation
callpal()
void AlphaISA::Kernel::Statistics::callpal (int code, ThreadContext * tc)
Definition at line 208 of file kernel_stats.cc.
References _callpal, and PAL::name().
changeMode()
void AlphaISA::Kernel::Statistics::changeMode (cpu_mode newmode, ThreadContext * tc) protected
Definition at line 165 of file kernel_stats.cc.
References _mode, _modeGood, _modeTicks, curTick(), DPRINTF, lastModeTick, and themode.
Referenced by context(), mode(), and setIdleProcess().
context()
void AlphaISA::Kernel::Statistics::context (Addr oldpcbb, Addr newpcbb, ThreadContext * tc)
Definition at line 195 of file kernel_stats.cc.
References _swap_context, changeMode(), DPRINTF, AlphaISA::Kernel::idle, idleProcess, AlphaISA::Kernel::kernel, themode, and AlphaISA::Kernel::user.
hwrei()
void AlphaISA::Kernel::Statistics::hwrei () inline
Definition at line 90 of file kernel_stats.hh.
References AlphaISA::Kernel::idle, MipsISA::ipl, serialize(), setIdleProcess(), swpipl(), and unserialize().
mode()
void AlphaISA::Kernel::Statistics::mode (cpu_mode newmode, ThreadContext * tc)
Definition at line 184 of file kernel_stats.cc.
References changeMode(), AlphaISA::Kernel::idle, idleProcess, AlphaISA::IPR_PALtemp23, AlphaISA::Kernel::kernel, and ThreadContext::readMiscRegNoEffect().
regStats()
void AlphaISA::Kernel::Statistics::regStats (const std::string & name) virtual
Reimplemented from Kernel::Statistics.
Referenced by Statistics().
serialize()
void AlphaISA::Kernel::Statistics::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 233 of file kernel_stats.cc.
References idleProcess, iplLast, iplLastTick, lastModeTick, SERIALIZE_SCALAR, and themode.
Referenced by hwrei().
setIdleProcess()
void AlphaISA::Kernel::Statistics::setIdleProcess (Addr idle, ThreadContext * tc)
Definition at line 156 of file kernel_stats.cc.
References changeMode(), AlphaISA::Kernel::idle, idleProcess, AlphaISA::Kernel::kernel, and themode.
Referenced by hwrei().
swpipl()
void AlphaISA::Kernel::Statistics::swpipl (int ipl)
Definition at line 217 of file kernel_stats.cc.
References _iplCount, _iplGood, _iplTicks, curTick(), MipsISA::ipl, iplLast, and iplLastTick.
Referenced by hwrei().
unserialize()
void AlphaISA::Kernel::Statistics::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 245 of file kernel_stats.cc.
References idleProcess, iplLast, iplLastTick, lastModeTick, themode, and UNSERIALIZE_SCALAR.
Referenced by hwrei().
Member Data Documentation
_callpal
Stats::Vector AlphaISA::Kernel::Statistics::_callpal private
Definition at line 61 of file kernel_stats.hh.
Referenced by callpal(), and Statistics().
_hwrei
Stats::Scalar AlphaISA::Kernel::Statistics::_hwrei private
Definition at line 63 of file kernel_stats.hh.
Referenced by Statistics().
_iplCount
Stats::Vector AlphaISA::Kernel::Statistics::_iplCount private
Definition at line 72 of file kernel_stats.hh.
Referenced by Statistics(), and swpipl().
_iplGood
Stats::Vector AlphaISA::Kernel::Statistics::_iplGood private
Definition at line 73 of file kernel_stats.hh.
Referenced by Statistics(), and swpipl().
_iplTicks
Stats::Vector AlphaISA::Kernel::Statistics::_iplTicks private
Definition at line 74 of file kernel_stats.hh.
Referenced by Statistics(), and swpipl().
_iplUsed
Stats::Formula AlphaISA::Kernel::Statistics::_iplUsed private
Definition at line 75 of file kernel_stats.hh.
Referenced by Statistics().
_mode
Stats::Vector AlphaISA::Kernel::Statistics::_mode private
Definition at line 65 of file kernel_stats.hh.
Referenced by changeMode(), and Statistics().
_modeFraction
Stats::Formula AlphaISA::Kernel::Statistics::_modeFraction private
Definition at line 67 of file kernel_stats.hh.
Referenced by Statistics().
_modeGood
Stats::Vector AlphaISA::Kernel::Statistics::_modeGood private
Definition at line 66 of file kernel_stats.hh.
Referenced by changeMode(), and Statistics().
_modeTicks
Stats::Vector AlphaISA::Kernel::Statistics::_modeTicks private
Definition at line 68 of file kernel_stats.hh.
Referenced by changeMode(), and Statistics().
_swap_context
Stats::Scalar AlphaISA::Kernel::Statistics::_swap_context private
Definition at line 70 of file kernel_stats.hh.
Referenced by context(), and Statistics().
idleProcess
Addr AlphaISA::Kernel::Statistics::idleProcess protected
Definition at line 54 of file kernel_stats.hh.
Referenced by context(), mode(), serialize(), setIdleProcess(), and unserialize().
iplLast
int AlphaISA::Kernel::Statistics::iplLast private
Definition at line 78 of file kernel_stats.hh.
Referenced by serialize(), swpipl(), and unserialize().
iplLastTick
Tick AlphaISA::Kernel::Statistics::iplLastTick private
Definition at line 79 of file kernel_stats.hh.
Referenced by serialize(), swpipl(), and unserialize().
lastModeTick
Tick AlphaISA::Kernel::Statistics::lastModeTick protected
Definition at line 56 of file kernel_stats.hh.
Referenced by changeMode(), serialize(), and unserialize().
themode
cpu_mode AlphaISA::Kernel::Statistics::themode protected
Definition at line 55 of file kernel_stats.hh.
Referenced by changeMode(), context(), serialize(), setIdleProcess(), and unserialize().
The documentation for this class was generated from the following files:
arch/alpha/kernel_stats.hh
arch/alpha/kernel_stats.cc