gem5: X86ISA::I82094AA Class Reference
X86ISA::I82094AA Class Reference
#include <i82094aa.hh>
Public Types
typedef I82094AAParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BitUnion64 (RedirTableEntry) Bitfield< 63
const Params * params () const
I82094AA (Params *p)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void writeReg (uint8_t offset, uint32_t value)
uint32_t readReg (uint8_t offset)
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
bool recvResponse (PacketPtr pkt)
void signalInterrupt (int line)
void raiseInterruptPin (int number)
void lowerInterruptPin (int number)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
topDW
Bitfield< 55, 32 > topReserved
Bitfield< 31, 0 > bottomDW
Bitfield< 31, 17 > bottomReserved
Bitfield< 63, 56 > dest
Bitfield< 16 > mask
Bitfield< 15 > trigger
Bitfield< 14 > remoteIRR
Bitfield< 13 > polarity
Bitfield< 12 > deliveryStatus
Bitfield< 11 > destMode
Bitfield< 10, 8 > deliveryMode
Bitfield< 7, 0 > vector
EndBitUnion(RedirTableEntry) protected uint8_t regSel
uint8_t initialApicId
uint8_t id
uint8_t arbId
uint64_t lowestPriorityOffset
RedirTableEntry redirTable [TableSize]
bool pinStates [TableSize]
std::vector< IntSinkPin< I82094AA > * > inputs
IntMasterPort< I82094AA > intMasterPort
Static Public Attributes
static const uint8_t TableSize = 24
static const uint8_t APICVersion = 0x14
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 48 of file i82094aa.hh.
Member Typedef Documentation
Params
typedef I82094AAParams X86ISA::I82094AA::Params
Definition at line 90 of file i82094aa.hh.
Constructor & Destructor Documentation
I82094AA()
X86ISA::I82094AA::I82094AA (Params * p)
Definition at line 44 of file i82094aa.cc.
References arbId, csprintf(), ArmISA::i, id, initialApicId, inputs, SimObject::name(), pinStates, redirTable, regSel, and TableSize.
Referenced by params().
Member Function Documentation
BitUnion64()
X86ISA::I82094AA::BitUnion64 (RedirTableEntry)
getPort()
Port & X86ISA::I82094AA::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from PioDevice.
Definition at line 82 of file i82094aa.cc.
References PioDevice::getPort(), inputs, and intMasterPort.
Referenced by params().
init()
void X86ISA::I82094AA::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from PioDevice.
Definition at line 70 of file i82094aa.cc.
References PioDevice::init(), intMasterPort, and panic_if.
Referenced by params().
lowerInterruptPin()
void X86ISA::I82094AA::lowerInterruptPin (int number)
Definition at line 262 of file i82094aa.cc.
References pinStates, and TableSize.
Referenced by params().
params()
const Params* X86ISA::I82094AA::params () const inline
Definition at line 93 of file i82094aa.hh.
References SimObject::_params, getPort(), I82094AA(), init(), InvalidPortID, lowerInterruptPin(), X86ISA::offset, X86ISA::p, raiseInterruptPin(), read(), readReg(), recvResponse(), serialize(), signalInterrupt(), unserialize(), write(), and writeReg().
raiseInterruptPin()
void X86ISA::I82094AA::raiseInterruptPin (int number)
Definition at line 253 of file i82094aa.cc.
References pinStates, signalInterrupt(), and TableSize.
Referenced by params().
read()
Tick X86ISA::I82094AA::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 93 of file i82094aa.cc.
References Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, readReg(), regSel, and Packet::setLE().
Referenced by params().
readReg()
uint32_t X86ISA::I82094AA::readReg (uint8_t offset)
Definition at line 156 of file i82094aa.cc.
References APICVersion, arbId, DPRINTF, X86ISA::index, redirTable, TableSize, and warn.
Referenced by params(), and read().
recvResponse()
bool X86ISA::I82094AA::recvResponse (PacketPtr pkt)
Referenced by params().
serialize()
void X86ISA::I82094AA::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 269 of file i82094aa.cc.
References arbId, initialApicId, lowestPriorityOffset, pinStates, redirTable, regSel, SERIALIZE_ARRAY, SERIALIZE_SCALAR, and TableSize.
Referenced by params().
signalInterrupt()
void X86ISA::I82094AA::signalInterrupt (int line)
Definition at line 181 of file i82094aa.cc.
References X86ISA::APIC_LOGICAL_DESTINATION, X86ISA::buildIntTriggerPacket(), DPRINTF, System::getThreadContext(), ArmISA::i, intMasterPort, System::isTimingMode(), lowestPriorityOffset, System::numContexts(), panic, redirTable, PioDevice::sys, and TableSize.
Referenced by params(), Pc::postConsoleInt(), Pc::postPciInt(), and raiseInterruptPin().
unserialize()
void X86ISA::I82094AA::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 282 of file i82094aa.cc.
References arbId, ArmISA::i, initialApicId, lowestPriorityOffset, pinStates, redirTable, regSel, TableSize, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by params().
write()
Tick X86ISA::I82094AA::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 112 of file i82094aa.cc.
References Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, regSel, and writeReg().
Referenced by params().
writeReg()
void X86ISA::I82094AA::writeReg (uint8_t offset, uint32_t value)
Definition at line 131 of file i82094aa.cc.
References arbId, bits(), DPRINTF, X86ISA::index, redirTable, TableSize, and warn.
Referenced by Pc::init(), params(), and write().
Member Data Documentation
APICVersion
const uint8_t X86ISA::I82094AA::APICVersion = 0x14 static
Definition at line 80 of file i82094aa.hh.
Referenced by readReg().
arbId
uint8_t X86ISA::I82094AA::arbId
Definition at line 73 of file i82094aa.hh.
Referenced by I82094AA(), readReg(), serialize(), unserialize(), and writeReg().
bottomDW
Bitfield<31, 0> X86ISA::I82094AA::bottomDW
Definition at line 54 of file i82094aa.hh.
bottomReserved
Bitfield<31, 17> X86ISA::I82094AA::bottomReserved
Definition at line 55 of file i82094aa.hh.
deliveryMode
Bitfield<10, 8> X86ISA::I82094AA::deliveryMode
Definition at line 63 of file i82094aa.hh.
Referenced by Pc::init().
deliveryStatus
Bitfield<12> X86ISA::I82094AA::deliveryStatus
Definition at line 61 of file i82094aa.hh.
dest
Bitfield<63, 56> X86ISA::I82094AA::dest
Definition at line 56 of file i82094aa.hh.
destMode
Bitfield<11> X86ISA::I82094AA::destMode
Definition at line 62 of file i82094aa.hh.
id
uint8_t X86ISA::I82094AA::id
Definition at line 72 of file i82094aa.hh.
Referenced by I82094AA().
initialApicId
uint8_t X86ISA::I82094AA::initialApicId
Definition at line 71 of file i82094aa.hh.
Referenced by I82094AA(), serialize(), and unserialize().
inputs
std::vector<IntSinkPin<I82094AA> *> X86ISA::I82094AA::inputs
Definition at line 85 of file i82094aa.hh.
Referenced by getPort(), and I82094AA().
intMasterPort
IntMasterPort<I82094AA> X86ISA::I82094AA::intMasterPort
Definition at line 87 of file i82094aa.hh.
Referenced by getPort(), init(), and signalInterrupt().
lowestPriorityOffset
uint64_t X86ISA::I82094AA::lowestPriorityOffset
Definition at line 75 of file i82094aa.hh.
Referenced by serialize(), signalInterrupt(), and unserialize().
mask
Bitfield<16> X86ISA::I82094AA::mask
Definition at line 57 of file i82094aa.hh.
pinStates
bool X86ISA::I82094AA::pinStates[TableSize]
Definition at line 83 of file i82094aa.hh.
Referenced by I82094AA(), lowerInterruptPin(), raiseInterruptPin(), serialize(), and unserialize().
polarity
Bitfield<13> X86ISA::I82094AA::polarity
Definition at line 60 of file i82094aa.hh.
redirTable
RedirTableEntry X86ISA::I82094AA::redirTable[TableSize]
Definition at line 82 of file i82094aa.hh.
Referenced by I82094AA(), readReg(), serialize(), signalInterrupt(), unserialize(), and writeReg().
regSel
EndBitUnion (RedirTableEntry) protected uint8_t X86ISA::I82094AA::regSel
Definition at line 65 of file i82094aa.hh.
Referenced by I82094AA(), read(), serialize(), unserialize(), and write().
remoteIRR
Bitfield<14> X86ISA::I82094AA::remoteIRR
Definition at line 59 of file i82094aa.hh.
TableSize
const uint8_t X86ISA::I82094AA::TableSize = 24 static
Definition at line 77 of file i82094aa.hh.
Referenced by I82094AA(), lowerInterruptPin(), raiseInterruptPin(), readReg(), serialize(), signalInterrupt(), unserialize(), and writeReg().
topDW
X86ISA::I82094AA::topDW
Definition at line 52 of file i82094aa.hh.
topReserved
Bitfield<55, 32> X86ISA::I82094AA::topReserved
Definition at line 53 of file i82094aa.hh.
trigger
Bitfield<15> X86ISA::I82094AA::trigger
Definition at line 58 of file i82094aa.hh.
vector
Bitfield<7, 0> X86ISA::I82094AA::vector
Definition at line 64 of file i82094aa.hh.
The documentation for this class was generated from the following files:
dev/x86/i82094aa.hh
dev/x86/i82094aa.cc