gem5: CrossbarSwitch Class Reference
CrossbarSwitch Class Reference
#include <CrossbarSwitch.hh>
Public Member Functions
CrossbarSwitch (Router *router)
~CrossbarSwitch ()
void wakeup ()
void init ()
void print (std::ostream &out) const
void update_sw_winner (int inport, flit *t_flit)
double get_crossbar_activity ()
uint32_t functionalWrite (Packet *pkt)
void resetStats ()
Public Member Functions inherited from Consumer
Consumer (ClockedObject *_em)
virtual ~Consumer ()
virtual void storeEventInfo (int info)
bool alreadyScheduled (Tick time)
void insertScheduledWakeupTime (Tick time)
void scheduleEventAbsolute (Tick timeAbs)
Private Attributes
int m_num_vcs
int m_num_inports
double m_crossbar_activity
Router * m_router
std::vector< flitBuffer * > m_switch_buffer
std::vector< OutputUnit * > m_output_unit
Additional Inherited Members
Protected Member Functions inherited from Consumer
void scheduleEvent (Cycles timeDelta)
Detailed Description
Definition at line 47 of file CrossbarSwitch.hh.
Constructor & Destructor Documentation
CrossbarSwitch()
CrossbarSwitch::CrossbarSwitch (Router * router)
Definition at line 43 of file CrossbarSwitch.cc.
References Router::get_num_vcs(), m_crossbar_activity, m_num_vcs, and m_router.
~CrossbarSwitch()
CrossbarSwitch::~CrossbarSwitch ()
Definition at line 51 of file CrossbarSwitch.cc.
References m5::stl_helpers::deletePointers(), and m_switch_buffer.
Member Function Documentation
functionalWrite()
uint32_t CrossbarSwitch::functionalWrite (Packet * pkt)
Definition at line 103 of file CrossbarSwitch.cc.
References ArmISA::i, and m_switch_buffer.
Referenced by Router::functionalWrite(), and get_crossbar_activity().
get_crossbar_activity()
double CrossbarSwitch::get_crossbar_activity () inline
Definition at line 59 of file CrossbarSwitch.hh.
References functionalWrite(), m_crossbar_activity, and resetStats().
Referenced by Router::collateStats().
init()
void CrossbarSwitch::init ()
Definition at line 57 of file CrossbarSwitch.cc.
References Router::get_num_inports(), Router::get_outputUnit_ref(), ArmISA::i, m_num_inports, m_output_unit, m_router, and m_switch_buffer.
Referenced by Router::init().
print()
void CrossbarSwitch::print (std::ostream & out) const inline virtual
Implements Consumer.
Definition at line 54 of file CrossbarSwitch.hh.
resetStats()
void CrossbarSwitch::resetStats ()
Definition at line 115 of file CrossbarSwitch.cc.
References m_crossbar_activity.
Referenced by get_crossbar_activity(), and Router::resetStats().
update_sw_winner()
void CrossbarSwitch::update_sw_winner (int inport, flit * t_flit) inline
Definition at line 56 of file CrossbarSwitch.hh.
References m_switch_buffer.
Referenced by Router::grant_switch().
wakeup()
void CrossbarSwitch::wakeup () virtual
Implements Consumer.
Definition at line 75 of file CrossbarSwitch.cc.
References flit::advance_stage(), Clocked::curCycle(), DPRINTF, Router::get_id(), flit::get_outport(), flit::is_stage(), LT_, m_crossbar_activity, m_num_inports, m_output_unit, m_router, m_switch_buffer, flit::set_time(), and ST_.
Referenced by Router::wakeup().
Member Data Documentation
m_crossbar_activity
double CrossbarSwitch::m_crossbar_activity private
Definition at line 67 of file CrossbarSwitch.hh.
Referenced by CrossbarSwitch(), get_crossbar_activity(), resetStats(), and wakeup().
m_num_inports
int CrossbarSwitch::m_num_inports private
Definition at line 66 of file CrossbarSwitch.hh.
Referenced by init(), and wakeup().
m_num_vcs
int CrossbarSwitch::m_num_vcs private
Definition at line 65 of file CrossbarSwitch.hh.
Referenced by CrossbarSwitch().
m_output_unit
std::vector<OutputUnit *> CrossbarSwitch::m_output_unit private
Definition at line 70 of file CrossbarSwitch.hh.
Referenced by init(), and wakeup().
m_router
Router* CrossbarSwitch::m_router private
Definition at line 68 of file CrossbarSwitch.hh.
Referenced by CrossbarSwitch(), init(), and wakeup().
m_switch_buffer
std::vector<flitBuffer *> CrossbarSwitch::m_switch_buffer private
Definition at line 69 of file CrossbarSwitch.hh.
Referenced by functionalWrite(), init(), update_sw_winner(), wakeup(), and ~CrossbarSwitch().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/CrossbarSwitch.hh
mem/ruby/network/garnet2.0/CrossbarSwitch.cc