gem5: QoS::MemSinkCtrl Class Reference
QoS::MemSinkCtrl Class Reference
QoS Memory Sink.
#include <mem_sink.hh>
Classes
class MemoryPort
Public Member Functions
MemSinkCtrl (const QoSMemSinkCtrlParams *)
QoS Memory Sink Constructor.
virtual ~MemSinkCtrl ()
DrainState drain () override
Checks and return the Drain state of this SimObject.
Port & getPort (const std::string &if_name, PortID=InvalidPortID) override
Getter method to access this memory's slave port.
void init () override
Initializes this object.
Public Member Functions inherited from QoS::MemCtrl
MemCtrl (const QoSMemCtrlParams *)
QoS Memory base class.
virtual ~MemCtrl ()
BusState getBusState () const
Gets the current bus state.
BusState getBusStateNext () const
Gets the next bus state.
bool hasMaster (MasterID m_id) const
hasMaster returns true if the selected master(ID) has been registered in the memory controller, which happens if the memory controller has received at least a packet from that master.
uint64_t getReadQueueSize (const uint8_t prio) const
Gets a READ queue size.
uint64_t getWriteQueueSize (const uint8_t prio) const
Gets a WRITE queue size.
uint64_t getTotalReadQueueSize () const
Gets the total combined READ queues size.
uint64_t getTotalWriteQueueSize () const
Gets the total combined WRITE queues size.
Tick getServiceTick (const uint8_t prio) const
Gets the last service tick related to a QoS Priority.
uint8_t numPriorities () const
Gets the total number of priority levels in the QoS memory controller.
Public Member Functions inherited from AbstractMemory
AbstractMemory (const Params *p)
virtual ~AbstractMemory ()
bool isNull () const
See if this is a null memory that should never store data and always return zero.
void setBackingStore (uint8_t *pmem_addr)
Set the host memory backing store to be used by this memory controller.
const std::list< LockedAddr > & getLockedAddrList () const
Get the list of locked addresses to allow checkpointing.
void addLockedAddr (LockedAddr addr)
Add a locked address to allow for checkpointing.
System * system () const
read the system pointer Implemented for completeness with the setter
void system (System *sys)
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
const Params * params () const
AddrRange getAddrRange () const
Get the address range.
uint64_t size () const
Get the memory size.
Addr start () const
Get the start address.
bool isConfReported () const
Should this memory be passed to the kernel and part of the OS physical memory layout.
bool isInAddrMap () const
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
bool isKvmMap () const
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
using PacketQueue = std::deque< PacketPtr >
The Request packets are store in a multiple dequeue structure, based on their QoS priority.
Protected Member Functions
void processNextReqEvent ()
Processes the next Request event according to configured request latency.
bool readQueueFull (const uint64_t packets) const
Check if the read queue has room for more entries.
bool writeQueueFull (const uint64_t packets) const
Check if the write queue has room for more entries.
Tick recvAtomic (PacketPtr pkt)
Receive a Packet in Atomic mode.
void recvFunctional (PacketPtr pkt)
Receive a Packet in Functional mode.
bool recvTimingReq (PacketPtr pkt)
Receive a Packet in Timing mode.
void regStats () override
Registers statistics.
Protected Member Functions inherited from QoS::MemCtrl
void addMaster (const MasterID m_id)
Initializes dynamically counters and statistics for a given Master.
void logRequest (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries)
Called upon receiving a request or updates statistics and updates queues status.
void logResponse (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries, double delay)
Called upon receiving a response, updates statistics and updates queues status.
template<typename Queues >
uint8_t qosSchedule (std::initializer_list< Queues *> queues_ptr, uint64_t queue_entry_size, const PacketPtr pkt)
Assign priority to a packet by executing the configured QoS policy.
uint8_t schedule (MasterID m_id, uint64_t data)
uint8_t schedule (const PacketPtr pkt)
BusState selectNextBusState ()
Returns next bus direction (READ or WRITE) based on configured policy.
void setCurrentBusState ()
Set current bus direction (READ or WRITE) from next selected one.
void recordTurnaroundStats ()
Record statistics on turnarounds based on busStateNext and busState values.
template<typename Queues >
void escalate (std::initializer_list< Queues *> queues, uint64_t queue_entry_size, MasterID m_id, uint8_t tgt_prio)
Escalates/demotes priority of all packets belonging to the passed master to given priority value.
template<typename Queues >
void escalateQueues (Queues &queues, uint64_t queue_entry_size, MasterID m_id, uint8_t curr_prio, uint8_t tgt_prio)
Escalates/demotes priority of all packets belonging to the passed master to given priority value in a specified cluster of queues (e.g.
Protected Member Functions inherited from AbstractMemory
bool checkLockedAddrList (PacketPtr pkt)
void trackLoadLocked (PacketPtr pkt)
bool writeOK (PacketPtr pkt)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const Tick requestLatency
Memory between requests latency (ticks)
const Tick responseLatency
Memory response latency (ticks)
const uint64_t memoryPacketSize
Memory packet size in bytes.
const uint64_t readBufferSize
Read request packets queue buffer size in #packets.
const uint64_t writeBufferSize
Write request packets queue buffer size in #packets.
MemoryPort port
Memory slave port.
bool retryRdReq
Read request pending.
bool retryWrReq
Write request pending.
Tick nextRequest
Next request service time.
Stats::Scalar numReadRetries
Count the number of read retries.
Stats::Scalar numWriteRetries
Count the number of write retries.
std::vector< PacketQueue > readQueue
QoS-aware (per priority) incoming read requests packets queue.
std::vector< PacketQueue > writeQueue
QoS-aware (per priority) incoming read requests packets queue.
EventWrapper< MemSinkCtrl, &MemSinkCtrl::processNextReqEvent > nextReqEvent
Event wrapper to schedule next request handler function.
Protected Attributes inherited from QoS::MemCtrl
const std::unique_ptr< Policy > policy
QoS Policy, assigns QoS priority to the incoming packets.
const std::unique_ptr< TurnaroundPolicy > turnPolicy
QoS Bus Turnaround Policy: selects the bus direction (READ/WRITE)
const std::unique_ptr< QueuePolicy > queuePolicy
QoS Queue Policy: selects packet among same-priority queue.
const uint8_t _numPriorities
Number of configured QoS priorities.
const bool qosPriorityEscalation
Enables QoS priority escalation.
const bool qosSyncroScheduler
Enables QoS synchronized scheduling invokes the QoS scheduler on all masters, at every packet arrival.
std::unordered_map< MasterID, const std::string > masters
Hash of master ID - master name.
std::unordered_map< MasterID, std::vector< uint64_t > > packetPriorities
Hash of masters - number of packets queued per priority.
std::unordered_map< MasterID, std::unordered_map< uint64_t, std::deque< uint64_t > > > requestTimes
Hash of masters - address of request - queue of times of request.
std::vector< Tick > serviceTick
Vector of QoS priorities/last service time.
std::vector< uint64_t > readQueueSizes
Read request packets queue length in #packets, per QoS priority.
std::vector< uint64_t > writeQueueSizes
Write request packets queue length in #packets, per QoS priority.
uint64_t totalReadQueueSize
Total read request packets queue length in #packets.
uint64_t totalWriteQueueSize
Total write request packets queue length in #packets.
BusState busState
Bus state used to control the read/write switching and drive the scheduling of the next request.
BusState busStateNext
bus state for next request event triggered
QoS::MemCtrl::MemCtrlStats stats
Protected Attributes inherited from AbstractMemory
AddrRange range
uint8_t * pmemAddr
MemBackdoor backdoor
const bool confTableReported
const bool inAddrMap
const bool kvmMap
std::list< LockedAddr > lockedAddrList
System * _system
Pointer to the System object.
AbstractMemory::MemStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from QoS::MemCtrl
enum BusState { READ, WRITE }
Bus Direction.
Public Types inherited from AbstractMemory
typedef AbstractMemoryParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
QoS Memory Sink.
The QoS Memory Sink is a lightweight memory controller with QoS support. It is meant to provide a QoS aware simple memory system without the need of using a complex DRAM memory controller
Definition at line 57 of file mem_sink.hh.
Member Typedef Documentation
PacketQueue
using QoS::MemSinkCtrl::PacketQueue = std::deque<PacketPtr> protected
The Request packets are store in a multiple dequeue structure, based on their QoS priority.
Definition at line 64 of file mem_sink.hh.
Constructor & Destructor Documentation
MemSinkCtrl()
QoS::MemSinkCtrl::MemSinkCtrl (const QoSMemSinkCtrlParams * p)
QoS Memory Sink Constructor.
Parameters
p QoS Memory Sink configuration parameters
Definition at line 47 of file mem_sink.cc.
References QoS::MemCtrl::numPriorities(), readQueue, and writeQueue.
~MemSinkCtrl()
QoS::MemSinkCtrl::~MemSinkCtrl () virtual
Definition at line 61 of file mem_sink.cc.
Member Function Documentation
drain()
DrainState QoS::MemSinkCtrl::drain () override virtual
Checks and return the Drain state of this SimObject.
Returns
current Drain state
Implements Drainable.
Definition at line 319 of file mem_sink.cc.
References DPRINTF, Drained, Draining, QoS::MemCtrl::totalReadQueueSize, and QoS::MemCtrl::totalWriteQueueSize.
getPort()
Port & QoS::MemSinkCtrl::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Getter method to access this memory's slave port.
Parameters
if_name interface name
idx port ID number
Returns
reference to this memory's slave port
Reimplemented from SimObject.
Definition at line 110 of file mem_sink.cc.
References SimObject::getPort(), and port.
init()
void QoS::MemSinkCtrl::init () override virtual
Initializes this object.
Reimplemented from QoS::MemCtrl.
Definition at line 65 of file mem_sink.cc.
References QoS::MemCtrl::init(), Port::isConnected(), port, and SlavePort::sendRangeChange().
processNextReqEvent()
void QoS::MemSinkCtrl::processNextReqEvent () protected
Processes the next Request event according to configured request latency.
Definition at line 199 of file mem_sink.cc.
References AbstractMemory::_system, AbstractMemory::access(), QoS::MemCtrl::busState, QoS::MemCtrl::busStateNext, curTick(), divCeil(), DPRINTF, DTRACE, ArmISA::e, Packet::getAddr(), System::getMasterName(), Packet::getSize(), ArmISA::i, Packet::isRead(), QoS::MemCtrl::logResponse(), memoryPacketSize, Packet::needsResponse(), nextReqEvent, nextRequest, QoS::MemCtrl::numPriorities(), panic_if, port, Packet::qosValue(), QoS::MemCtrl::queuePolicy, QoS::MemCtrl::READ, readQueue, QoS::MemCtrl::readQueueSizes, QoS::MemCtrl::recordTurnaroundStats(), Packet::req, requestLatency, responseLatency, retryRdReq, retryWrReq, QueuedSlavePort::schedTimingResp(), QoS::MemCtrl::schedule(), QoS::MemCtrl::selectNextBusState(), SlavePort::sendRetryReq(), QoS::MemCtrl::setCurrentBusState(), sc_dt::to_string(), QoS::MemCtrl::totalReadQueueSize, QoS::MemCtrl::totalWriteQueueSize, QoS::MemCtrl::WRITE, writeQueue, and QoS::MemCtrl::writeQueueSizes.
readQueueFull()
bool QoS::MemSinkCtrl::readQueueFull (const uint64_t packets) const inline protected
Check if the read queue has room for more entries.
Parameters
packets The number of entries needed in the read queue
Returns
true if read queue is full, false otherwise
Definition at line 77 of file mem_sink.cc.
References readBufferSize, and QoS::MemCtrl::totalReadQueueSize.
Referenced by recvTimingReq().
recvAtomic()
Tick QoS::MemSinkCtrl::recvAtomic (PacketPtr pkt) protected
Receive a Packet in Atomic mode.
Parameters
pkt pointer to memory packet
Returns
packet access latency in ticks
Definition at line 89 of file mem_sink.cc.
References AbstractMemory::access(), Packet::cacheResponding(), panic_if, and responseLatency.
recvFunctional()
void QoS::MemSinkCtrl::recvFunctional (PacketPtr pkt) protected
Receive a Packet in Functional mode.
Parameters
pkt pointer to memory packet
Definition at line 100 of file mem_sink.cc.
References AbstractMemory::functionalAccess(), SimObject::name(), Packet::popLabel(), and Packet::pushLabel().
recvTimingReq()
bool QoS::MemSinkCtrl::recvTimingReq (PacketPtr pkt) protected
Receive a Packet in Timing mode.
Parameters
pkt pointer to memory packet
Returns
true if the request was accepted
Definition at line 120 of file mem_sink.cc.
References AbstractMemory::_system, Packet::cacheResponding(), Packet::cmdString(), curTick(), divCeil(), DPRINTF, Packet::getAddr(), System::getMasterName(), Packet::getSize(), Packet::isRead(), Packet::isWrite(), QoS::MemCtrl::logRequest(), memoryPacketSize, nextReqEvent, nextRequest, numReadRetries, numWriteRetries, panic_if, QoS::MemCtrl::qosSchedule(), Packet::qosValue(), QoS::MemCtrl::queuePolicy, QoS::MemCtrl::READ, readQueue, readQueueFull(), Packet::req, retryRdReq, retryWrReq, QoS::MemCtrl::schedule(), QoS::MemCtrl::WRITE, writeQueue, and writeQueueFull().
regStats()
void QoS::MemSinkCtrl::regStats () override protected virtual
Registers statistics.
Reimplemented from Stats::Group.
Definition at line 332 of file mem_sink.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numReadRetries, numWriteRetries, and Stats::Group::regStats().
writeQueueFull()
bool QoS::MemSinkCtrl::writeQueueFull (const uint64_t packets) const inline protected
Check if the write queue has room for more entries.
Parameters
packets The number of entries needed in the write queue
Returns
true if write queue is full, false otherwise
Definition at line 83 of file mem_sink.cc.
References QoS::MemCtrl::totalWriteQueueSize, and writeBufferSize.
Referenced by recvTimingReq().
Member Data Documentation
memoryPacketSize
const uint64_t QoS::MemSinkCtrl::memoryPacketSize protected
Memory packet size in bytes.
Definition at line 155 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvTimingReq().
nextReqEvent
EventWrapper< MemSinkCtrl, &MemSinkCtrl::processNextReqEvent> QoS::MemSinkCtrl::nextReqEvent protected
Event wrapper to schedule next request handler function.
Definition at line 200 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvTimingReq().
nextRequest
Tick QoS::MemSinkCtrl::nextRequest protected
Next request service time.
Definition at line 173 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvTimingReq().
numReadRetries
Stats::Scalar QoS::MemSinkCtrl::numReadRetries protected
Count the number of read retries.
Definition at line 176 of file mem_sink.hh.
Referenced by recvTimingReq(), and regStats().
numWriteRetries
Stats::Scalar QoS::MemSinkCtrl::numWriteRetries protected
Count the number of write retries.
Definition at line 179 of file mem_sink.hh.
Referenced by recvTimingReq(), and regStats().
port
MemoryPort QoS::MemSinkCtrl::port protected
Memory slave port.
Definition at line 164 of file mem_sink.hh.
Referenced by getPort(), init(), and processNextReqEvent().
readBufferSize
const uint64_t QoS::MemSinkCtrl::readBufferSize protected
Read request packets queue buffer size in #packets.
Definition at line 158 of file mem_sink.hh.
Referenced by readQueueFull().
readQueue
std::vector<PacketQueue> QoS::MemSinkCtrl::readQueue protected
QoS-aware (per priority) incoming read requests packets queue.
Definition at line 184 of file mem_sink.hh.
Referenced by MemSinkCtrl(), processNextReqEvent(), and recvTimingReq().
requestLatency
const Tick QoS::MemSinkCtrl::requestLatency protected
Memory between requests latency (ticks)
Definition at line 149 of file mem_sink.hh.
Referenced by processNextReqEvent().
responseLatency
const Tick QoS::MemSinkCtrl::responseLatency protected
Memory response latency (ticks)
Definition at line 152 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvAtomic().
retryRdReq
bool QoS::MemSinkCtrl::retryRdReq protected
Read request pending.
Definition at line 167 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvTimingReq().
retryWrReq
bool QoS::MemSinkCtrl::retryWrReq protected
Write request pending.
Definition at line 170 of file mem_sink.hh.
Referenced by processNextReqEvent(), and recvTimingReq().
writeBufferSize
const uint64_t QoS::MemSinkCtrl::writeBufferSize protected
Write request packets queue buffer size in #packets.
Definition at line 161 of file mem_sink.hh.
Referenced by writeQueueFull().
writeQueue
std::vector<PacketQueue> QoS::MemSinkCtrl::writeQueue protected
QoS-aware (per priority) incoming read requests packets queue.
Definition at line 189 of file mem_sink.hh.
Referenced by MemSinkCtrl(), processNextReqEvent(), and recvTimingReq().
The documentation for this class was generated from the following files:
mem/qos/mem_sink.hh
mem/qos/mem_sink.cc