gem5: Stats::ScalarProxyNode< Stat > Class Template Reference
Stats::ScalarProxyNode< Stat > Class Template Reference
#include <statistics.hh>
Public Member Functions
ScalarProxyNode (const ScalarProxy< Stat > &p)
const VResult & result () const
Return the result vector of this subtree.
Result total () const
Return the total of the result vector.
size_type size () const
Return the number of nodes in the subtree starting at this node.
std::string str () const
Public Member Functions inherited from Stats::Node
virtual ~Node ()
Private Attributes
const ScalarProxy< Stat > proxy
VResult vresult
Detailed Description
template<class Stat>
class Stats::ScalarProxyNode< Stat >
Definition at line 2160 of file statistics.hh.
Constructor & Destructor Documentation
ScalarProxyNode()
template<class Stat > Stats::ScalarProxyNode< Stat >::ScalarProxyNode (const ScalarProxy< Stat > & p) inline
Definition at line 2167 of file statistics.hh.
Member Function Documentation
result()
template<class Stat > const VResult& Stats::ScalarProxyNode< Stat >::result () const inline virtual
Return the result vector of this subtree.
Returns
The result vector of this subtree.
Implements Stats::Node.
Definition at line 2172 of file statistics.hh.
References Stats::ScalarProxy< Stat >::result().
size()
template<class Stat > size_type Stats::ScalarProxyNode< Stat >::size () const inline virtual
Return the number of nodes in the subtree starting at this node.
Returns
the number of nodes in this subtree.
Implements Stats::Node.
Definition at line 2185 of file statistics.hh.
str()
template<class Stat > std::string Stats::ScalarProxyNode< Stat >::str () const inline virtual
Implements Stats::Node.
Definition at line 2194 of file statistics.hh.
References Stats::ScalarProxy< Stat >::str().
total()
template<class Stat > Result Stats::ScalarProxyNode< Stat >::total () const inline virtual
Return the total of the result vector.
Returns
The total of the result vector.
Implements Stats::Node.
Definition at line 2179 of file statistics.hh.
References Stats::ScalarProxy< Stat >::result().
Member Data Documentation
proxy
template<class Stat > const ScalarProxy<Stat> Stats::ScalarProxyNode< Stat >::proxy private
Definition at line 2163 of file statistics.hh.
vresult
template<class Stat > VResult Stats::ScalarProxyNode< Stat >::vresult mutable private
Definition at line 2164 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh