gem5: VirtIOBlock::RequestQueue Class Reference
VirtIOBlock::RequestQueue Class Reference
Virtqueue for disk requests.
#include <block.hh>
Public Member Functions
RequestQueue (PortProxy &proxy, ByteOrder bo, uint16_t size, VirtIOBlock &_parent)
virtual ~RequestQueue ()
void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
std::string name () const
Public Member Functions inherited from VirtQueue
virtual ~VirtQueue ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void setAddress (Addr address)
Set the base address of this queue.
Addr getAddress () const
Get the guest physical address of this queue.
uint16_t getSize () const
Get the number of descriptors available in this queue.
VirtDescriptor * getDescriptor (VirtDescriptor::Index index)
Get a pointer to a specific descriptor in the queue.
VirtDescriptor * consumeDescriptor ()
Get an incoming descriptor chain from the queue.
void produceDescriptor (VirtDescriptor *desc, uint32_t len)
Send a descriptor chain to the guest.
virtual void onNotify ()
Notify queue of pending events.
void dump () const
Dump the contents of a queue.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
VirtIOBlock & parent
Protected Attributes inherited from VirtQueue
ByteOrder byteOrder
Byte order in this queue.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from VirtQueue
static const Addr ALIGN_BITS = 12
Page size used by VirtIO. It's hard-coded to 4096 bytes in the spec for historical reasons.
static const Addr ALIGN_SIZE = 1 << ALIGN_BITS
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from VirtQueue
VirtQueue (PortProxy &proxy, ByteOrder bo, uint16_t size)
Instantiate a new virtqueue.
Detailed Description
Virtqueue for disk requests.
Definition at line 162 of file block.hh.
Constructor & Destructor Documentation
RequestQueue()
VirtIOBlock::RequestQueue::RequestQueue (PortProxy & proxy, ByteOrder bo, uint16_t size, VirtIOBlock & _parent) inline
Definition at line 166 of file block.hh.
~RequestQueue()
virtual VirtIOBlock::RequestQueue::~RequestQueue () inline virtual
Definition at line 169 of file block.hh.
Member Function Documentation
name()
std::string VirtIOBlock::RequestQueue::name () const inline
Definition at line 173 of file block.hh.
onNotifyDescriptor()
void VirtIOBlock::RequestQueue::onNotifyDescriptor (VirtDescriptor * desc) virtual
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented from VirtQueue.
Definition at line 126 of file block.cc.
References VirtIODeviceBase::byteOrder, VirtDescriptor::chainRead(), VirtDescriptor::chainSize(), VirtDescriptor::chainWrite(), DPRINTF, htog(), VirtIOBlock::S_OK, VirtIOBlock::S_UNSUPP, VirtDescriptor::size(), ArmISA::status, VirtIOBlock::T_FLUSH, VirtIOBlock::T_IN, VirtIOBlock::T_OUT, VirtIOBlock::VirtIOBlock(), and warn.
Member Data Documentation
parent
VirtIOBlock& VirtIOBlock::RequestQueue::parent protected
Definition at line 176 of file block.hh.
The documentation for this class was generated from the following files:
dev/virtio/block.hh
dev/virtio/block.cc