gem5: MemBackdoor Class Reference
MemBackdoor Class Reference
#include <backdoor.hh>
Classes
class Callback
Public Types
enum Flags { NoAccess = 0x0, Readable = 0x1, Writeable = 0x2 }
typedef std::function< void(const MemBackdoor &backdoor)> CbFunction
Public Member Functions
const AddrRange & range () const
void range (const AddrRange &r)
uint8_t * ptr () const
void ptr (uint8_t *p)
bool readable () const
void readable (bool r)
bool writeable () const
void writeable (bool w)
Flags flags () const
void flags (Flags f)
MemBackdoor (AddrRange r, uint8_t *p, Flags flags)
MemBackdoor ()
void addInvalidationCallback (CbFunction func)
void invalidate ()
Private Attributes
std::unique_ptr< CallbackQueue > invalidationCallbacks
AddrRange _range
uint8_t * _ptr
Flags _flags
Detailed Description
Definition at line 40 of file backdoor.hh.
Member Typedef Documentation
CbFunction
typedef std::function<void(const MemBackdoor &backdoor)> MemBackdoor::CbFunction
Definition at line 45 of file backdoor.hh.
Member Enumeration Documentation
Flags
enum MemBackdoor::Flags
Enumerator
NoAccess
Readable
Writeable
Definition at line 70 of file backdoor.hh.
Constructor & Destructor Documentation
MemBackdoor() [1/2]
MemBackdoor::MemBackdoor (AddrRange r, uint8_t * p, Flags flags) inline
Definition at line 112 of file backdoor.hh.
MemBackdoor() [2/2]
MemBackdoor::MemBackdoor () inline
Definition at line 117 of file backdoor.hh.
Member Function Documentation
addInvalidationCallback()
void MemBackdoor::addInvalidationCallback (CbFunction func) inline
Definition at line 124 of file backdoor.hh.
References invalidationCallbacks.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr().
flags() [1/2]
Flags MemBackdoor::flags () const inline
Definition at line 109 of file backdoor.hh.
References _flags.
flags() [2/2]
void MemBackdoor::flags (Flags f) inline
Definition at line 110 of file backdoor.hh.
References _flags, and ArmISA::f.
invalidate()
void MemBackdoor::invalidate () inline
Definition at line 136 of file backdoor.hh.
References Callback::CallbackQueue, and invalidationCallbacks.
Referenced by AbstractMemory::setBackingStore().
ptr() [1/2]
uint8_t* MemBackdoor::ptr () const inline
Definition at line 82 of file backdoor.hh.
References _ptr.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), SimpleMemory::recvAtomicBackdoor(), and AbstractMemory::setBackingStore().
ptr() [2/2]
void MemBackdoor::ptr (uint8_t * p) inline
Definition at line 83 of file backdoor.hh.
References _ptr, and MipsISA::p.
range() [1/2]
const AddrRange& MemBackdoor::range () const inline
Definition at line 78 of file backdoor.hh.
References _range.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr().
range() [2/2]
void MemBackdoor::range (const AddrRange & r) inline
Definition at line 79 of file backdoor.hh.
References _range, and MipsISA::r.
readable() [1/2]
bool MemBackdoor::readable () const inline
Definition at line 89 of file backdoor.hh.
References _flags, and Readable.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getBackdoor().
readable() [2/2]
void MemBackdoor::readable (bool r) inline
Definition at line 91 of file backdoor.hh.
References _flags, and Readable.
writeable() [1/2]
bool MemBackdoor::writeable () const inline
Definition at line 99 of file backdoor.hh.
References _flags, and Writeable.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr().
writeable() [2/2]
void MemBackdoor::writeable (bool w) inline
Definition at line 101 of file backdoor.hh.
References _flags, and Writeable.
Member Data Documentation
_flags
Flags MemBackdoor::_flags private
Definition at line 149 of file backdoor.hh.
Referenced by flags(), readable(), and writeable().
_ptr
uint8_t* MemBackdoor::_ptr private
Definition at line 148 of file backdoor.hh.
Referenced by ptr().
_range
AddrRange MemBackdoor::_range private
Definition at line 147 of file backdoor.hh.
Referenced by range().
invalidationCallbacks
std::unique_ptr<CallbackQueue> MemBackdoor::invalidationCallbacks private
Definition at line 145 of file backdoor.hh.
Referenced by addInvalidationCallback(), and invalidate().
The documentation for this class was generated from the following file:
mem/backdoor.hh