gem5: CheckpointIn Class Reference
CheckpointIn Class Reference
#include <serialize.hh>
Public Member Functions
CheckpointIn (const std::string &cpt_dir, SimObjectResolver &resolver)
~CheckpointIn ()
bool find (const std::string &section, const std::string &entry, std::string &value)
bool findObj (const std::string &section, const std::string &entry, SimObject *&value)
bool entryExists (const std::string &section, const std::string &entry)
bool sectionExists (const std::string &section)
Static Public Member Functions
static std::string setDir (const std::string &base_name)
static std::string dir ()
Public Attributes
const std::string cptDir
Static Public Attributes
static const char * baseFilename = "m5.cpt"
Private Attributes
IniFile * db
SimObjectResolver & objNameResolver
Static Private Attributes
static std::string currentDirectory
Detailed Description
Definition at line 72 of file serialize.hh.
Constructor & Destructor Documentation
CheckpointIn()
CheckpointIn::CheckpointIn (const std::string & cpt_dir, SimObjectResolver & resolver)
Definition at line 273 of file serialize.cc.
References baseFilename, cptDir, db, fatal, and IniFile::load().
~CheckpointIn()
CheckpointIn::~CheckpointIn ()
Definition at line 282 of file serialize.cc.
References db.
Member Function Documentation
dir()
string CheckpointIn::dir () static
Definition at line 268 of file serialize.cc.
Referenced by CowDiskImage::serialize(), PhysicalMemory::serializeStore(), and RubySystem::writeCompressedTrace().
entryExists()
bool CheckpointIn::entryExists (const std::string & section, const std::string & entry)
Definition at line 288 of file serialize.cc.
References db, and IniFile::entryExists().
Referenced by GicV2::unserialize().
find()
bool CheckpointIn::find (const std::string & section, const std::string & entry, std::string & value)
Definition at line 294 of file serialize.cc.
References db, and IniFile::find().
Referenced by arrayParamIn(), optParamIn(), paramIn(), and Globals::unserialize().
findObj()
bool CheckpointIn::findObj (const std::string & section, const std::string & entry, SimObject *& value)
Definition at line 300 of file serialize.cc.
References db, IniFile::find(), objNameResolver, and SimObjectResolver::resolveSimObject().
Referenced by objParamIn().
sectionExists()
bool CheckpointIn::sectionExists (const std::string & section)
Definition at line 313 of file serialize.cc.
References db, and IniFile::sectionExists().
Referenced by ArmSemihosting::FileBase::create(), SimObject::loadState(), HDLcd::unserialize(), and GicV2::unserialize().
setDir()
string CheckpointIn::setDir (const std::string & base_name) static
Definition at line 256 of file serialize.cc.
References csprintf(), and curTick().
Referenced by Serializable::serializeAll().
Member Data Documentation
baseFilename
const char * CheckpointIn::baseFilename = "m5.cpt" static
Definition at line 120 of file serialize.hh.
Referenced by CheckpointIn(), Serializable::currentSection(), and Serializable::serializeAll().
cptDir
const std::string CheckpointIn::cptDir
Definition at line 84 of file serialize.hh.
Referenced by CheckpointIn(), RubySystem::unserialize(), CowDiskImage::unserialize(), and PhysicalMemory::unserializeStore().
currentDirectory
string CheckpointIn::currentDirectory static private
Definition at line 105 of file serialize.hh.
Referenced by Serializable::currentSection().
db
IniFile* CheckpointIn::db private
Definition at line 76 of file serialize.hh.
Referenced by CheckpointIn(), entryExists(), find(), findObj(), sectionExists(), and ~CheckpointIn().
objNameResolver
SimObjectResolver& CheckpointIn::objNameResolver private
Definition at line 78 of file serialize.hh.
Referenced by findObj().
The documentation for this class was generated from the following files:
sim/serialize.hh
sim/serialize.cc