gem5: AmbaDevice Class Reference
AmbaDevice Class Reference
#include <amba_device.hh>
Protected Member Functions
bool readId (PacketPtr pkt, uint64_t amba_id, Addr pio_addr)
Static Protected Attributes
static const int AMBA_PER_ID0 = 0xFE0
static const int AMBA_PER_ID1 = 0xFE4
static const int AMBA_PER_ID2 = 0xFE8
static const int AMBA_PER_ID3 = 0xFEC
static const int AMBA_CEL_ID0 = 0xFF0
static const int AMBA_CEL_ID1 = 0xFF4
static const int AMBA_CEL_ID2 = 0xFF8
static const int AMBA_CEL_ID3 = 0xFFC
Detailed Description
Definition at line 62 of file amba_device.hh.
Member Function Documentation
readId()
bool AmbaDevice::readId (PacketPtr pkt, uint64_t amba_id, Addr pio_addr) protected
Definition at line 74 of file amba_device.cc.
References AMBA_CEL_ID3, AMBA_PER_ID0, DPRINTF, Packet::getAddr(), Packet::getSize(), and Packet::setLE().
Referenced by Pl011::read(), AmbaFake::read(), PL031::read(), Pl050::read(), Sp804::read(), Pl111::read(), PL031::write(), and Sp804::write().
Member Data Documentation
AMBA_CEL_ID0
const int AmbaDevice::AMBA_CEL_ID0 = 0xFF0 static protected
Definition at line 69 of file amba_device.hh.
AMBA_CEL_ID1
const int AmbaDevice::AMBA_CEL_ID1 = 0xFF4 static protected
Definition at line 70 of file amba_device.hh.
AMBA_CEL_ID2
const int AmbaDevice::AMBA_CEL_ID2 = 0xFF8 static protected
Definition at line 71 of file amba_device.hh.
AMBA_CEL_ID3
const int AmbaDevice::AMBA_CEL_ID3 = 0xFFC static protected
Definition at line 72 of file amba_device.hh.
Referenced by readId().
AMBA_PER_ID0
const int AmbaDevice::AMBA_PER_ID0 = 0xFE0 static protected
Definition at line 65 of file amba_device.hh.
Referenced by readId().
AMBA_PER_ID1
const int AmbaDevice::AMBA_PER_ID1 = 0xFE4 static protected
Definition at line 66 of file amba_device.hh.
AMBA_PER_ID2
const int AmbaDevice::AMBA_PER_ID2 = 0xFE8 static protected
Definition at line 67 of file amba_device.hh.
AMBA_PER_ID3
const int AmbaDevice::AMBA_PER_ID3 = 0xFEC static protected
Definition at line 68 of file amba_device.hh.
The documentation for this class was generated from the following files:
dev/arm/amba_device.hh
dev/arm/amba_device.cc