gem5: BaseBufferArg Class Reference
BaseBufferArg Class Reference
Base class for BufferArg and TypedBufferArg, Not intended to be used directly.
#include <syscall_emul_buf.hh>
Public Member Functions
BaseBufferArg (Addr _addr, int _size)
Allocate a buffer of size 'size' representing the memory at target address 'addr'.
~BaseBufferArg ()
bool copyIn (PortProxy &memproxy)
copy data into simulator space (read from target memory)
bool copyOut (PortProxy &memproxy)
copy data out of simulator space (write to target memory)
Protected Attributes
const Addr addr
address of buffer in target address space
const int size
buffer size
uint8_t *const bufPtr
pointer to buffer in simulator space
Detailed Description
Base class for BufferArg and TypedBufferArg, Not intended to be used directly.
The BufferArg classes represent buffers in target user space that are passed by reference to an (emulated) system call. Each instance provides an internal (simulator-space) buffer of the appropriate size and tracks the user-space address. The copyIn() and copyOut() methods copy the user-space buffer to and from the simulator-space buffer, respectively.
Definition at line 56 of file syscall_emul_buf.hh.
Constructor & Destructor Documentation
BaseBufferArg()
BaseBufferArg::BaseBufferArg (Addr _addr, int _size) inline
Allocate a buffer of size 'size' representing the memory at target address 'addr'.
Definition at line 64 of file syscall_emul_buf.hh.
References bufPtr, and size.
~BaseBufferArg()
BaseBufferArg::~BaseBufferArg () inline
Definition at line 73 of file syscall_emul_buf.hh.
References bufPtr.
Member Function Documentation
copyIn()
bool BaseBufferArg::copyIn (PortProxy & memproxy) inline
copy data into simulator space (read from target memory)
Definition at line 79 of file syscall_emul_buf.hh.
References addr, bufPtr, PortProxy::readBlob(), and size.
Referenced by acceptFunc(), bindFunc(), connectFunc(), execveFunc(), futexFunc(), getpeernameFunc(), getsocknameFunc(), ioctlFunc(), osf_setsysinfoFunc(), pollFunc(), pwrite64Func(), recvfromFunc(), recvmsgFunc(), selectFunc(), sendmsgFunc(), sendtoFunc(), setsockoptFunc(), sys_setsysinfoFunc(), sysctlFunc(), utimesFunc(), and writeFunc().
copyOut()
bool BaseBufferArg::copyOut (PortProxy & memproxy) inline
copy data out of simulator space (write to target memory)
Definition at line 89 of file syscall_emul_buf.hh.
References addr, bufPtr, size, and PortProxy::writeBlob().
Referenced by _llseekFunc(), acceptFunc(), clock_getresFunc(), cloneFunc(), copyOutStatfsBuf(), exitFutexWake(), futexFunc(), getcwdFunc(), gethostnameFunc(), getpeernameFunc(), SparcISA::getresuidFunc(), getsocknameFunc(), getsockoptFunc(), ClDriver::ioctl(), ioctlFunc(), osf_getsysinfoFunc(), pipeImpl(), pollFunc(), prlimitFunc(), readFunc(), readlinkFunc(), recvfromFunc(), recvmsgFunc(), rmdirFunc(), selectFunc(), socketpairFunc(), sys_getsysinfoFunc(), sysctlFunc(), and wait4Func().
Member Data Documentation
addr
const Addr BaseBufferArg::addr protected
address of buffer in target address space
Definition at line 96 of file syscall_emul_buf.hh.
Referenced by copyIn(), and copyOut().
bufPtr
uint8_t* const BaseBufferArg::bufPtr protected
pointer to buffer in simulator space
Definition at line 98 of file syscall_emul_buf.hh.
Referenced by BaseBufferArg(), BufferArg::bufferPtr(), copyIn(), copyOut(), TypedBufferArg< T >::operator T*(), TypedBufferArg< T >::operator*(), TypedBufferArg< T >::operator->(), TypedBufferArg< T >::operator[](), and ~BaseBufferArg().
size
const int BaseBufferArg::size protected
buffer size
Definition at line 97 of file syscall_emul_buf.hh.
Referenced by BaseBufferArg(), copyIn(), and copyOut().
The documentation for this class was generated from the following file:
sim/syscall_emul_buf.hh