gem5: FunctionalResponseProtocol Class Reference
FunctionalResponseProtocol Class Reference abstract
#include <functional.hh>
Protected Member Functions
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
virtual void recvFunctional (PacketPtr pkt)=0
Receive a functional request packet from the peer.
Friends
class FunctionalRequestProtocol
Detailed Description
Definition at line 72 of file functional.hh.
Member Function Documentation
recvFunctional()
virtual void FunctionalResponseProtocol::recvFunctional (PacketPtr pkt) protected pure virtual
Receive a functional request packet from the peer.
Implemented in BaseCache::CpuSidePort, X86ISA::GpuTLB::CpuSidePort, Bridge::BridgeSlavePort, CommMonitor::MonitorSlavePort, SerialLink::SerialLinkSlavePort, LdsState::CuSidePort, TLBCoalescer::CpuSidePort, AddrMapper::MapperSlavePort, MemCheckerMonitor::MonitorSlavePort, CoherentXBar::CoherentXBarSlavePort, RubyPort::PioSlavePort, SMMUATSSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, DRAMCtrl::MemoryPort, SimpleCache::CPUSidePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, SimpleMemobj::CPUSidePort, MemDelay::SlavePort, QoS::MemSinkCtrl::MemoryPort, SimpleMemory::MemoryPort, RubyPort::MemSlavePort, SMMUSlavePort, DRAMSim2::MemoryPort, SimpleTimingPort, and StubSlavePort.
Referenced by FunctionalRequestProtocol::send().
sendSnoop()
void FunctionalResponseProtocol::sendSnoop (FunctionalRequestProtocol * peer, PacketPtr pkt) const protected
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters
pkt Snoop packet to send.
Definition at line 60 of file functional.cc.
References Packet::isRequest(), and FunctionalRequestProtocol::recvFunctionalSnoop().
Referenced by SlavePort::sendFunctionalSnoop().
Friends And Related Function Documentation
FunctionalRequestProtocol
friend class FunctionalRequestProtocol friend
Definition at line 74 of file functional.hh.
The documentation for this class was generated from the following files:
mem/protocol/functional.hh
mem/protocol/functional.cc