gem5: System Class Reference
System Class Reference
#include <system.hh>
Classes
class SystemPort
Private class for the system port which is only used as a master for debug access and for non-structural entities that do not have a port of their own.
Public Types
typedef SystemParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void init () override
After all objects have been created and all ports are connected, check that the system port is connected.
MasterPort & getSystemPort ()
Get a reference to the system port that can be used by non-structural simulation objects like processes or threads, or external entities like loaders and debuggers, etc, to access the memory system.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Additional function to return the Port of a memory object.
unsigned int cacheLineSize () const
Get the cache line size of the system.
bool schedule (PCEvent *event) override
bool remove (PCEvent *event) override
ThreadContext * getThreadContext (ContextID tid) const
unsigned numContexts () const
int numRunningContexts ()
Return number of running (non-halted) thread contexts in system.
KvmVM * getKvmVM ()
Get a pointer to the Kernel Virtual Machine (KVM) SimObject, if present.
bool validKvmEnvironment () const
Verify gem5 configuration will support KVM emulation.
PhysicalMemory & getPhysMem ()
Get a pointer to access the physical memory of the system.
Addr freeMemSize () const
Amount of physical memory that is still free.
Addr memSize () const
Amount of physical memory that exists.
bool isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
Arch getArch () const
Get the architecture.
ByteOrder getGuestByteOrder () const
Get the guest byte order.
Addr getPageBytes () const
Get the page bytes for the ISA.
Addr getPageShift () const
Get the number of bits worth of in-page address for the ISA.
ThermalModel * getThermalModel () const
The thermal model used for this system (if any).
MasterID getMasterId (const SimObject *master, std::string submaster=std::string())
Request an id used to create a request object in the system.
MasterID getGlobalMasterId (const std::string &master_name)
Registers a GLOBAL MasterID, which is a MasterID not related to any particular SimObject; since no SimObject is passed, the master gets registered by providing the full master name.
std::string getMasterName (MasterID master_id)
Get the name of an object for a given request id.
MasterID lookupMasterId (const SimObject *obj) const
Looks up the MasterID for a given SimObject returns an invalid MasterID (invldMasterId) if not found.
MasterID lookupMasterId (const std::string &name) const
Looks up the MasterID for a given object name string returns an invalid MasterID (invldMasterId) if not found.
MasterID maxMasters ()
Get the number of masters registered in the system.
void regStats () override
Callback to set stat parameters.
uint64_t incWorkItemsBegin ()
Called by pseudo_inst to track the number of work items started by this system.
uint64_t incWorkItemsEnd ()
Called by pseudo_inst to track the number of work items completed by this system.
int markWorkItem (int index)
Called by pseudo_inst to mark the cpus actively executing work items.
void workItemBegin (uint32_t tid, uint32_t workid)
void workItemEnd (uint32_t tid, uint32_t workid)
virtual Addr fixFuncEventAddr (Addr addr)
Fix up an address used to match PCs for hooking simulator events on to target function executions.
bool breakpoint ()
System (Params *p)
~System ()
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
const Params * params () const
Addr getKernelStart () const
Returns the address the kernel starts at.
Addr getKernelEnd () const
Returns the address the kernel ends at.
Addr getKernelEntry () const
Returns the address the entry point to the kernel code.
Addr allocPhysPages (int npages)
Allocate npages contiguous unused physical pages.
ContextID registerThreadContext (ThreadContext *tc, ContextID assigned=InvalidContextID)
void replaceThreadContext (ThreadContext *tc, ContextID context_id)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
bool isAtomicMode () const
Is the system in atomic mode?
bool isTimingMode () const
Is the system in timing mode?
bool bypassCaches () const
Should caches be bypassed?
Enums::MemoryMode getMemoryMode () const
Get the memory mode of the system.
void setMemoryMode (Enums::MemoryMode mode)
Change the memory mode of the system.
template<class T , typename... Args>
T * addFuncEvent (const SymbolTable *symtab, const char *lbl, const std::string &desc, Args... args)
Add a function-based event to the given function, to be looked up in the specified symbol table.
template<class T >
T * addFuncEvent (const SymbolTable *symtab, const char *lbl)
template<class T , typename... Args>
T * addFuncEventOrPanic (const SymbolTable *symtab, const char *lbl, Args... args)
template<class T , typename... Args>
T * addKernelFuncEvent (const char *lbl, Args... args)
Add a function-based event to a kernel symbol.
template<class T , typename... Args>
T * addKernelFuncEventOrPanic (const char *lbl, Args... args)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static void printSystems ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
std::vector< ThreadContext * > threadContexts
const bool multiThread
Addr pagePtr
uint64_t init_param
PortProxy physProxy
Port to physical memory used for writing object files into ram at boot.
SymbolTable * kernelSymtab
kernel symbol table
ObjectFile * kernel
Object pointer for the kernel code.
MemoryImage kernelImage
std::vector< ObjectFile * > kernelExtras
Additional object files.
Addr kernelStart
Beginning of kernel code.
Addr kernelEnd
End of kernel code.
Addr kernelEntry
Entry point in the kernel to start at.
Addr loadAddrMask
Mask that should be anded for binary/symbol loading.
Addr loadAddrOffset
Offset that should be used for binary/symbol loading.
std::vector< BaseRemoteGDB * > remoteGDB
Counter totalNumInsts
std::map< std::pair< uint32_t, uint32_t >, Tick > lastWorkItemStarted
std::map< uint32_t, Stats::Histogram * > workItemStats
FutexMap futexMap
std::set< int > PIDs
Process set to track which PIDs have already been allocated.
std::list< BasicSignal > signalList
std::vector< RedirectPath * > redirectPaths
Static Public Attributes
static std::vector< System * > systemList
static int numSystemsRunning = 0
static const int maxPID = 32768
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions
std::string stripSystemName (const std::string &master_name) const
Strips off the system name from a master name.
MasterID _getMasterId (const SimObject *master, const std::string &master_name)
helper function for getMasterId
std::string leafMasterName (const SimObject *master, const std::string &submaster)
Helper function for constructing the full (sub)master name by providing the root master and the relative submaster name.
virtual void serializeSymtab (CheckpointOut &os) const
If needed, serialize additional symbol table entries for a specific subclass of this system.
virtual void unserializeSymtab (CheckpointIn &cp)
If needed, unserialize additional symbol table entries for a specific subclass of this system.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
KvmVM *const kvmVM
PhysicalMemory physmem
Enums::MemoryMode memoryMode
const unsigned int _cacheLineSize
uint64_t workItemsBegin
uint64_t workItemsEnd
uint32_t numWorkIds
std::vector< bool > activeCpus
std::vector< MasterInfo > masters
This array is a per-system list of all devices capable of issuing a memory system request and an associated string for each master id.
ThermalModel * thermalModel
Params * _params
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
std::list< PCEvent * > liveEvents
SystemPort _systemPort
Detailed Description
Definition at line 77 of file system.hh.
Member Typedef Documentation
Params
typedef SystemParams System::Params
Definition at line 565 of file system.hh.
Constructor & Destructor Documentation
System()
System::System (Params * p)
Definition at line 91 of file system.cc.
References _cacheLineSize, ArmISA::a, ImageFile::buildImage(), createObjectFile(), debugSymbolTable, ObjectFile::entryPoint(), fatal, fatal_if, findMsbSet(), FullSystem, Request::funcMasterId, getMasterId(), inform, Request::intMasterId, kernel, kernelEnd, kernelEntry, kernelExtras, kernelImage, kernelStart, kernelSymtab, kvmVM, loadAddrMask, loadAddrOffset, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), M5_VAR_USED, MemoryImage::maxAddr(), MemoryImage::minAddr(), MemoryImage::move(), numSystemsRunning, params(), KvmVM::setSystem(), systemList, warn_once, Request::wbMasterId, and X86ISA::x.
Referenced by getMasterName().
~System()
System::~System ()
Definition at line 212 of file system.cc.
References ArmISA::j, kernel, kernelSymtab, numWorkIds, and workItemStats.
Member Function Documentation
_getMasterId()
MasterID System::_getMasterId (const SimObject * master, const std::string & master_name) protected
helper function for getMasterId
Definition at line 587 of file system.cc.
References Stats::enabled(), fatal, ArmISA::i, masters, SimObject::name(), and stripSystemName().
Referenced by getGlobalMasterId(), getMasterId(), and maxMasters().
addFuncEvent() [1/2]
template<class T , typename... Args> T* System::addFuncEvent (const SymbolTable * symtab, const char * lbl, const std::string & desc, Args... args) inline
Add a function-based event to the given function, to be looked up in the specified symbol table.
The ...OrPanic flavor of the method causes the simulator to panic if the symbol can't be found.
Parameters
symtab Symbol table to use for look up.
lbl Function to hook the event to.
desc Description to be passed to the event.
args Arguments to be forwarded to the event constructor.
Definition at line 496 of file system.hh.
References SymbolTable::findAddress(), fixFuncEventAddr(), and M5_VAR_USED.
addFuncEvent() [2/2]
template<class T > T* System::addFuncEvent (const SymbolTable * symtab, const char * lbl) inline
Definition at line 511 of file system.hh.
addFuncEventOrPanic()
template<class T , typename... Args> T* System::addFuncEventOrPanic (const SymbolTable * symtab, const char * lbl, Args... args) inline
Definition at line 517 of file system.hh.
References ArmISA::e, and panic.
addKernelFuncEvent()
template<class T , typename... Args> T* System::addKernelFuncEvent (const char * lbl, Args... args) inline
Add a function-based event to a kernel symbol.
These functions work like their addFuncEvent() and addFuncEventOrPanic() counterparts. The only difference is that they automatically use the kernel symbol table. All arguments are forwarded to the underlying method.
See also
addFuncEvent()
addFuncEventOrPanic()
Parameters
lbl Function to hook the event to.
args Arguments to be passed to addFuncEvent
Definition at line 543 of file system.hh.
References kernelSymtab.
Referenced by breakAtKernelFunction().
addKernelFuncEventOrPanic()
template<class T , typename... Args> T* System::addKernelFuncEventOrPanic (const char * lbl, Args... args) inline
Definition at line 550 of file system.hh.
References ArmISA::e, and panic.
allocPhysPages()
Addr System::allocPhysPages (int npages)
Allocate npages contiguous unused physical pages.
Returns
Starting address of first page
Definition at line 404 of file system.cc.
References AddrRange::contains(), fatal, pagePtr, AlphaISA::PageShift, physmem, PhysicalMemory::totalSize(), and warn.
Referenced by Process::allocateMem(), getKernelEntry(), X86ISA::X86_64Process::initState(), and Process::replicatePage().
breakpoint()
bool System::breakpoint ()
Definition at line 243 of file system.cc.
References remoteGDB.
bypassCaches()
bool System::bypassCaches () const inline
Should caches be bypassed?
Some CPUs need to bypass caches to allow direct memory accesses, which is required for hardware virtualization.
Definition at line 160 of file system.hh.
References memoryMode.
Referenced by HDLcd::cmdDisable(), HDLcd::cmdEnable(), HDLcd::drainResume(), CoherentXBar::forwardAtomic(), CoherentXBar::forwardFunctional(), CoherentXBar::forwardTiming(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::PioSlavePort::recvAtomic(), BaseCache::CpuSidePort::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), BaseCache::MemSidePort::recvAtomicSnoop(), BaseCache::CpuSidePort::recvFunctional(), CoherentXBar::recvFunctional(), BaseCache::MemSidePort::recvFunctionalSnoop(), BaseCache::CpuSidePort::recvTimingReq(), CoherentXBar::recvTimingReq(), CoherentXBar::recvTimingResp(), BaseCache::MemSidePort::recvTimingSnoopReq(), BaseCache::CpuSidePort::recvTimingSnoopResp(), DmaReadFifo::resumeFill(), BaseCache::CpuSidePort::tryTiming(), NonCachingSimpleCPU::verifyMemoryMode(), and BaseKvmCPU::verifyMemoryMode().
cacheLineSize()
unsigned int System::cacheLineSize () const inline
Get the cache line size of the system.
Definition at line 188 of file system.hh.
References _cacheLineSize.
Referenced by DmaDevice::cacheBlockSize(), BaseTrafficGen::createDram(), BaseTrafficGen::createDramRot(), BaseTrafficGen::createLinear(), BaseTrafficGen::createRandom(), DmaPort::dmaAction(), DRAMSim2::init(), MemFootprintProbe::MemFootprintProbe(), ArmSemihosting::physProxy(), ArmISA::ISA::readMiscReg(), and DmaReadFifo::resumeFillFunctional().
drainResume()
void System::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 442 of file system.cc.
References totalNumInsts.
Referenced by getKernelEntry().
fixFuncEventAddr()
virtual Addr System::fixFuncEventAddr (Addr addr) inline virtual
Fix up an address used to match PCs for hooking simulator events on to target function executions.
See comment in system.cc for details.
Reimplemented in ArmSystem, SparcSystem, AlphaSystem, X86System, RiscvSystem, and MipsSystem.
Definition at line 477 of file system.hh.
References panic.
Referenced by addFuncEvent().
freeMemSize()
Addr System::freeMemSize () const
Amount of physical memory that is still free.
Definition at line 430 of file system.cc.
References pagePtr, AlphaISA::PageShift, physmem, and PhysicalMemory::totalSize().
Referenced by getPhysMem(), and Linux::procMeminfo().
getArch()
Arch System::getArch () const inline
Get the architecture.
Definition at line 284 of file system.hh.
Referenced by Sequencer::makeRequest().
getGlobalMasterId()
MasterID System::getGlobalMasterId (const std::string & master_name)
Registers a GLOBAL MasterID, which is a MasterID not related to any particular SimObject; since no SimObject is passed, the master gets registered by providing the full master name.
Parameters
masterName full name of the master
Returns
the master's ID.
Definition at line 574 of file system.cc.
References _getMasterId().
getGuestByteOrder()
ByteOrder System::getGuestByteOrder () const inline
Get the guest byte order.
Definition at line 290 of file system.hh.
References AlphaISA::GuestByteOrder, and panic.
Referenced by _llseekFunc(), dumpDmesgEntry(), and rmdirFunc().
getKernelEnd()
Addr System::getKernelEnd () const inline
Returns the address the kernel ends at.
Returns
address the kernel ends at
Definition at line 590 of file system.hh.
References kernelEnd.
Referenced by AlphaBackdoor::startup().
getKernelEntry()
Addr System::getKernelEntry () const inline
Returns the address the entry point to the kernel code.
Returns
entry point of the kernel code
Definition at line 596 of file system.hh.
References allocPhysPages(), drainResume(), InvalidContextID, kernelEntry, registerThreadContext(), replaceThreadContext(), serialize(), and unserialize().
Referenced by AlphaBackdoor::startup().
getKernelStart()
Addr System::getKernelStart () const inline
Returns the address the kernel starts at.
Returns
address the kernel starts at
Definition at line 584 of file system.hh.
References kernelStart.
Referenced by AlphaBackdoor::startup().
getKvmVM()
KvmVM* System::getKvmVM () inline
Get a pointer to the Kernel Virtual Machine (KVM) SimObject, if present.
Definition at line 256 of file system.hh.
References kvmVM, and validKvmEnvironment().
Referenced by MuxingKvmGic::MuxingKvmGic().
getMasterId()
MasterID System::getMasterId (const SimObject * master, std::string submaster = std::string())
Request an id used to create a request object in the system.
All objects that intend to issues requests into the memory system must request an id in the init() phase of startup. All master ids must be fixed by the regStats() phase that immediately precedes it. This allows objects in the memory system to understand how many masters may exist and appropriately name the bins of their per-master stats before the stats are finalized.
Registers a MasterID: This method takes two parameters, one of which is optional. The first one is the master object, and it is compulsory; in case a object has multiple (sub)masters, a second parameter must be provided and it contains the name of the submaster. The method will create a master's name by concatenating the SimObject name with the eventual submaster string, separated by a dot.
As an example: For a cpu having two masters: a data master and an instruction master, the method must be called twice:
instMasterId = getMasterId(cpu, "inst"); dataMasterId = getMasterId(cpu, "data");
and the masters' names will be:
"cpu.inst"
"cpu.data"
Parameters
master SimObject related to the master
submaster String containing the submaster's name
Returns
the master's ID.
Definition at line 580 of file system.cc.
References _getMasterId(), and leafMasterName().
Referenced by BaseTrafficGen::BaseTrafficGen(), and System().
getMasterName()
std::string System::getMasterName (MasterID master_id)
Get the name of an object for a given request id.
Definition at line 629 of file system.cc.
References fatal, masters, and System().
Referenced by QoS::MemCtrl::addMaster(), AbstractMemory::checkLockedAddrList(), QoS::MemSinkCtrl::processNextReqEvent(), QoS::MemCtrl::qosSchedule(), QoS::MemSinkCtrl::recvTimingReq(), BaseTags::BaseTagStats::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), AbstractMemory::MemStats::regStats(), BaseCache::CacheStats::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), QoS::FixedPriorityPolicy::schedule(), and MemTraceProbe::startup().
getMemoryMode()
Enums::MemoryMode System::getMemoryMode () const inline
Get the memory mode of the system.
This should only be used by the Python world. The C++ world should use one of the query functions above (isAtomicMode(), isTimingMode(), bypassCaches()).
Definition at line 173 of file system.hh.
References memoryMode, ArmISA::mode, and setMemoryMode().
Referenced by MinorCPU::init().
getPageBytes()
Addr System::getPageBytes () const inline
Get the page bytes for the ISA.
Definition at line 302 of file system.hh.
References AlphaISA::PageBytes.
Referenced by IdeController::IdeController(), and AbstractMemory::init().
getPageShift()
Addr System::getPageShift () const inline
Get the number of bits worth of in-page address for the ISA.
Definition at line 307 of file system.hh.
References AlphaISA::PageShift.
getPhysMem()
PhysicalMemory& System::getPhysMem () inline
Get a pointer to access the physical memory of the system.
Definition at line 264 of file system.hh.
References addr, freeMemSize(), isMemAddr(), memSize(), and physmem.
Referenced by KvmVM::delayedStartup(), ArmSemihosting::readString(), and NonCachingSimpleCPU::sendPacket().
getPort()
Port & System::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Additional function to return the Port of a memory object.
Reimplemented from SimObject.
Definition at line 230 of file system.cc.
References _systemPort.
Referenced by getSystemPort().
getSystemPort()
MasterPort& System::getSystemPort () inline
Get a reference to the system port that can be used by non-structural simulation objects like processes or threads, or external entities like loaders and debuggers, etc, to access the memory system.
Returns
a reference to the system port we own
Definition at line 121 of file system.hh.
References _systemPort, getPort(), and InvalidPortID.
Referenced by ArmSemihosting::physProxy().
getThermalModel()
ThermalModel* System::getThermalModel () const inline
The thermal model used for this system (if any).
Definition at line 312 of file system.hh.
References thermalModel.
getThreadContext()
ThreadContext* System::getThreadContext (ContextID tid) const inline
Definition at line 198 of file system.hh.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), ArmProcess64::armHwcapImpl(), ArmISA::TLBIOp::broadcast(), AbstractMemory::checkLockedAddrList(), KvmVM::contextIdToVCpuId(), GenericTimer::createTimers(), LinuxArmSystem::dumpDmesg(), Gicv3Redistributor::getAffinity(), CpuLocalTimer::init(), AlphaProcess::initState(), SparcProcess::initState(), RiscvProcess64::initState(), ArmLinuxProcess32::initState(), Process::initState(), RiscvProcess32::initState(), ArmProcess32::initState(), Sparc32Process::initState(), ArmProcess64::initState(), X86ISA::X86_64Process::initState(), Sparc64Process::initState(), X86ISA::I386Process::initState(), QueuedPrefetcher::insert(), DistIface::SyncEvent::process(), AlphaProcess::setupASNReg(), X86ISA::I82094AA::signalInterrupt(), and DistIface::toggleSync().
incWorkItemsBegin()
uint64_t System::incWorkItemsBegin () inline
Called by pseudo_inst to track the number of work items started by this system.
Definition at line 431 of file system.hh.
References workItemsBegin.
Referenced by PseudoInst::workbegin().
incWorkItemsEnd()
uint64_t System::incWorkItemsEnd () inline
Called by pseudo_inst to track the number of work items completed by this system.
Definition at line 441 of file system.hh.
References workItemsEnd.
Referenced by PseudoInst::workend().
init()
void System::init () override virtual
After all objects have been created and all ports are connected, check that the system port is connected.
Reimplemented from SimObject.
Definition at line 222 of file system.cc.
References _systemPort, Port::isConnected(), SimObject::name(), and panic.
initState()
void System::initState () override virtual
initState() is called on each SimObject when not restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Load the kernel code into memory
Reimplemented from SimObject.
Definition at line 331 of file system.cc.
References ArmISA::a, DPRINTF, fatal, FullSystem, ArmISA::i, isMemAddr(), kernelEnd, kernelEntry, kernelExtras, kernelImage, kernelStart, loadAddrMask, loadAddrOffset, params(), physProxy, AlphaISA::startupCPU(), threadContexts, and MemoryImage::write().
Referenced by BareMetalRiscvSystem::initState(), SparcSystem::initState(), AlphaSystem::initState(), X86System::initState(), and ArmSystem::initState().
isAtomicMode()
bool System::isAtomicMode () const inline
Is the system in atomic mode?
There are currently two different atomic memory modes: 'atomic', which supports caches; and 'atomic_noncaching', which bypasses caches. The latter is used by hardware virtualized CPUs. SimObjects are expected to use Port::sendAtomic() and Port::recvAtomic() when accessing memory in this mode.
Definition at line 139 of file system.hh.
References ArmISA::atomic, and memoryMode.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration(), SMMUTranslationProcess::completeTransaction(), SMMUv3::processCommands(), SMMUv3::runProcess(), Gicv3Its::runProcess(), DmaPort::sendDma(), NonCachingSimpleCPU::verifyMemoryMode(), and AtomicSimpleCPU::verifyMemoryMode().
isMemAddr()
bool System::isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
Parameters
addr A physical address
Returns
Whether the address corresponds to a memory
Definition at line 436 of file system.cc.
References PhysicalMemory::isMemAddr(), and physmem.
Referenced by getPhysMem(), MemFootprintProbe::handleRequest(), initState(), RubyPort::MemSlavePort::isPhysMemAddress(), RubyPort::ruby_hit_callback(), NonCachingSimpleCPU::sendPacket(), and BaseTrafficGen::update().
isTimingMode()
bool System::isTimingMode () const inline
Is the system in timing mode?
SimObjects are expected to use Port::sendTiming() and Port::recvTiming() when accessing memory in this mode.
Definition at line 150 of file system.hh.
References memoryMode.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration(), SMMUTranslationProcess::completeTransaction(), SMMUProcess::doDelay(), MinorCPU::drainResume(), DRAMCtrl::drainResume(), TrafficGen::initState(), SMMUTranslationProcess::issuePrefetch(), SMMUv3::processCommands(), SMMUTranslationProcess::resumeTransaction(), SMMUv3::runProcess(), Gicv3Its::runProcess(), DmaPort::sendDma(), X86ISA::I82094AA::signalInterrupt(), X86ISA::Walker::start(), DRAMCtrl::startup(), TimingSimpleCPU::verifyMemoryMode(), and FullO3CPU< O3CPUImpl >::verifyMemoryMode().
leafMasterName()
std::string System::leafMasterName (const SimObject * master, const std::string & submaster) protected
Helper function for constructing the full (sub)master name by providing the root master and the relative submaster name.
Definition at line 617 of file system.cc.
References SimObject::name().
Referenced by getMasterId(), and maxMasters().
lookupMasterId() [1/2]
MasterID System::lookupMasterId (const SimObject * obj) const
Looks up the MasterID for a given SimObject returns an invalid MasterID (invldMasterId) if not found.
Definition at line 537 of file system.cc.
References fatal_if, ArmISA::i, ArmISA::id, Request::invldMasterId, and masters.
Referenced by QoS::PropFairPolicy::initMaster(), and QoS::Policy::pair().
lookupMasterId() [2/2]
MasterID System::lookupMasterId (const std::string & name) const
Looks up the MasterID for a given object name string returns an invalid MasterID (invldMasterId) if not found.
Definition at line 560 of file system.cc.
References ArmISA::i, Request::invldMasterId, masters, SimObject::name(), and stripSystemName().
markWorkItem()
int System::markWorkItem (int index) inline
Called by pseudo_inst to mark the cpus actively executing work items.
Returns the total number of cpus that have executed work item begin or ends.
Definition at line 452 of file system.hh.
References X86ISA::count, ArmISA::i, and MipsISA::index.
Referenced by PseudoInst::workbegin(), and PseudoInst::workend().
maxMasters()
MasterID System::maxMasters () inline
Get the number of masters registered in the system.
Definition at line 409 of file system.hh.
References _getMasterId(), leafMasterName(), and regStats().
Referenced by BaseCache::getNextQueueEntry(), BaseCache::handleTimingReqMiss(), BaseCache::incHitCount(), BaseCache::incMissCount(), BaseCache::recvTimingResp(), BaseTags::BaseTagStats::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), AbstractMemory::MemStats::regStats(), BaseCache::CacheStats::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), and MemTraceProbe::startup().
memSize()
Addr System::memSize () const
Amount of physical memory that exists.
Definition at line 424 of file system.cc.
References physmem, and PhysicalMemory::totalSize().
Referenced by getPhysMem(), Linux::procMeminfo(), and AlphaBackdoor::startup().
numContexts()
unsigned System::numContexts () const inline
Definition at line 203 of file system.hh.
References numRunningContexts().
Referenced by ArmISA::TLBIOp::broadcast(), MuxingKvmGic::clearBankedDistRange(), MuxingKvmGic::copyBankedDistRange(), MuxingKvmGic::copyGicState(), exitImpl(), MuxingKvmGic::fromKvmToGicV2(), Iob::generateIpi(), Gicv3CPUInterface::generateSGI(), GicV2::genSwiMask(), getrlimitFunc(), Gicv3::init(), CpuLocalTimer::init(), DistIface::SyncEvent::process(), A9SCU::read(), Gicv3Redistributor::read(), SparcISA::ISA::readFSReg(), ArmISA::ISA::readMiscReg(), Gicv3Distributor::route(), CpuLocalTimer::serialize(), setpgidFunc(), X86ISA::I82094AA::signalInterrupt(), GicV2::softInt(), AlphaBackdoor::startup(), tgkillFunc(), DistIface::toggleSync(), CpuLocalTimer::unserialize(), Gicv3Distributor::update(), GicV2::updateIntState(), GicV2::updateRunPri(), and PseudoInst::wakeCPU().
numRunningContexts()
int System::numRunningContexts ()
Return number of running (non-halted) thread contexts in system.
These threads could be Active or Suspended.
Definition at line 318 of file system.cc.
References ThreadContext::Halted, ThreadContext::Halting, and threadContexts.
Referenced by numContexts(), GicV2::readCpu(), GicV2::readDistributor(), VGic::updateIntState(), GicV2::updateIntState(), and VGic::VGic().
params()
const Params* System::params () const inline
Definition at line 576 of file system.hh.
References _params.
Referenced by initState(), PseudoInst::loadsymbol(), PseudoInst::readfile(), System(), PseudoInst::workbegin(), and PseudoInst::workend().
printSystems()
void System::printSystems () static
Definition at line 506 of file system.cc.
References ArmISA::i, SimObject::name(), and systemList.
Referenced by printSystems(), and unserializeSymtab().
registerThreadContext()
ContextID System::registerThreadContext (ThreadContext * tc, ContextID assigned = InvalidContextID)
Definition at line 251 of file system.cc.
References activeCpus, ArmISA::e, fatal_if, ThreadContext::getCpuPtr(), getRemoteGDBPort(), ArmISA::id, inform, InvalidContextID, liveEvents, SimObject::name(), remoteGDB, PCEventScope::schedule(), threadContexts, and BaseCPU::waitForRemoteGDB().
Referenced by getKernelEntry(), and BaseCPU::registerThreadContexts().
regStats()
void System::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 473 of file system.cc.
References ccprintf(), ArmISA::j, SimObject::name(), numWorkIds, Stats::Group::regStats(), and workItemStats.
Referenced by maxMasters().
remove()
bool System::remove (PCEvent * event) override virtual
Implements PCEventScope.
Definition at line 308 of file system.cc.
References liveEvents, and threadContexts.
replaceThreadContext()
void System::replaceThreadContext (ThreadContext * tc, ContextID context_id)
Definition at line 369 of file system.cc.
References ArmISA::e, liveEvents, panic, remoteGDB, PCEventScope::schedule(), and threadContexts.
Referenced by getKernelEntry(), and BaseCPU::takeOverFrom().
schedule()
bool System::schedule (PCEvent * event) override virtual
Implements PCEventScope.
Definition at line 298 of file system.cc.
References liveEvents, and threadContexts.
serialize()
void System::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from SimObject.
Definition at line 448 of file system.cc.
References FullSystem, kernelSymtab, pagePtr, physmem, SymbolTable::serialize(), SERIALIZE_SCALAR, Serializable::serializeSection(), and serializeSymtab().
Referenced by getKernelEntry().
serializeSymtab()
virtual void System::serializeSymtab (CheckpointOut & os) const inline protected virtual
If needed, serialize additional symbol table entries for a specific subclass of this system.
Currently this is used by Alpha and MIPS.
Parameters
os stream to serialize to
Reimplemented in AlphaSystem, and SparcSystem.
Definition at line 652 of file system.hh.
Referenced by serialize().
setMemoryMode()
void System::setMemoryMode (Enums::MemoryMode mode)
Change the memory mode of the system.
This should only be called by the Python!
Parameters
mode Mode to change to (atomic/timing/...)
Definition at line 237 of file system.cc.
References Drained, Drainable::drainState(), memoryMode, and ArmISA::mode.
Referenced by getMemoryMode().
stripSystemName()
std::string System::stripSystemName (const std::string & master_name) const protected
Strips off the system name from a master name.
Definition at line 527 of file system.cc.
References SimObject::name(), and startswith().
Referenced by _getMasterId(), and lookupMasterId().
unserialize()
void System::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from SimObject.
Definition at line 461 of file system.cc.
References FullSystem, kernelSymtab, pagePtr, physmem, SymbolTable::unserialize(), UNSERIALIZE_SCALAR, Serializable::unserializeSection(), and unserializeSymtab().
Referenced by getKernelEntry().
unserializeSymtab()
virtual void System::unserializeSymtab (CheckpointIn & cp) inline protected virtual
If needed, unserialize additional symbol table entries for a specific subclass of this system.
Parameters
cp checkpoint to unserialize from
section relevant section in the checkpoint
Reimplemented in AlphaSystem, and SparcSystem.
Definition at line 661 of file system.hh.
References printSystems().
Referenced by unserialize().
validKvmEnvironment()
bool System::validKvmEnvironment () const
Verify gem5 configuration will support KVM emulation.
Definition at line 386 of file system.cc.
References threadContexts.
Referenced by MuxingKvmGic::drainResume(), getKvmVM(), ArchTimerKvm::scheduleEvents(), and MuxingKvmGic::startup().
workItemBegin()
void System::workItemBegin (uint32_t tid, uint32_t workid) inline
Definition at line 464 of file system.hh.
References curTick(), lastWorkItemStarted, MipsISA::p, and workItemEnd().
Referenced by PseudoInst::workbegin().
workItemEnd()
void System::workItemEnd (uint32_t tid, uint32_t workid)
Definition at line 489 of file system.cc.
References curTick(), DPRINTF, fatal, lastWorkItemStarted, numWorkIds, MipsISA::p, and workItemStats.
Referenced by PseudoInst::workend(), and workItemBegin().
Member Data Documentation
_cacheLineSize
const unsigned int System::_cacheLineSize protected
Definition at line 322 of file system.hh.
Referenced by cacheLineSize(), and System().
_params
Params* System::_params protected
Definition at line 568 of file system.hh.
Referenced by FreebsdArmSystem::params(), LinuxArmSystem::params(), MipsSystem::params(), RiscvSystem::params(), SparcSystem::params(), AlphaSystem::params(), LinuxAlphaSystem::params(), ArmSystem::params(), GenericArmSystem::params(), and params().
_systemPort
SystemPort System::_systemPort private
Definition at line 103 of file system.hh.
Referenced by getPort(), getSystemPort(), and init().
activeCpus
std::vector<bool> System::activeCpus protected
Definition at line 327 of file system.hh.
Referenced by registerThreadContext().
futexMap
FutexMap System::futexMap
Definition at line 627 of file system.hh.
Referenced by exitFutexWake(), and futexFunc().
init_param
uint64_t System::init_param
Definition at line 211 of file system.hh.
Referenced by PseudoInst::initParam().
kernel
ObjectFile* System::kernel
Object pointer for the kernel code.
Definition at line 221 of file system.hh.
Referenced by ArmSystem::ArmSystem(), FreebsdArmSystem::initState(), X86System::initState(), LinuxArmSystem::initState(), System(), and ~System().
kernelEnd
Addr System::kernelEnd
End of kernel code.
Definition at line 231 of file system.hh.
Referenced by getKernelEnd(), initState(), System(), and AlphaISA::StackTrace::trace().
kernelEntry
Addr System::kernelEntry
Entry point in the kernel to start at.
Definition at line 234 of file system.hh.
Referenced by getKernelEntry(), X86System::initState(), ArmSystem::initState(), initState(), and System().
kernelExtras
std::vector<ObjectFile *> System::kernelExtras
Additional object files.
Definition at line 225 of file system.hh.
Referenced by initState(), and System().
kernelImage
MemoryImage System::kernelImage
Definition at line 222 of file system.hh.
Referenced by initState(), and System().
kernelStart
Addr System::kernelStart
Beginning of kernel code.
Definition at line 228 of file system.hh.
Referenced by getKernelStart(), initState(), System(), and AlphaISA::StackTrace::trace().
kernelSymtab
SymbolTable* System::kernelSymtab
kernel symbol table
Definition at line 218 of file system.hh.
Referenced by addKernelFuncEvent(), PseudoInst::addsymbol(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), dumpDmesgEntry(), Linux::ThreadInfo::get_data(), FreebsdArmSystem::initState(), LinuxArmSystem::initState(), LinuxAlphaSystem::initState(), PseudoInst::loadsymbol(), AlphaISA::ProcessInfo::ProcessInfo(), X86ISA::readSymbol(), ArmISA::readSymbol(), serialize(), LinuxAlphaSystem::setDelayLoop(), LinuxAlphaSystem::setupFuncEvents(), SimpleThread::SimpleThread(), System(), AlphaISA::StackTrace::trace(), unserialize(), and ~System().
kvmVM
KvmVM* const System::kvmVM protected
Definition at line 316 of file system.hh.
Referenced by getKvmVM(), and System().
lastWorkItemStarted
std::map<std::pair<uint32_t,uint32_t>, Tick> System::lastWorkItemStarted
Definition at line 613 of file system.hh.
Referenced by workItemBegin(), and workItemEnd().
liveEvents
std::list<PCEvent *> System::liveEvents private
Definition at line 102 of file system.hh.
Referenced by registerThreadContext(), remove(), replaceThreadContext(), and schedule().
loadAddrMask
Addr System::loadAddrMask
Mask that should be anded for binary/symbol loading.
This allows one two different OS requirements for the same ISA to be handled. Some OSes are compiled for a virtual address and need to be loaded into physical memory that starts at address 0, while other bare metal tools generate images that start at address 0.
Definition at line 242 of file system.hh.
Referenced by AlphaSystem::initState(), FreebsdArmSystem::initState(), LinuxArmSystem::initState(), ArmSystem::initState(), initState(), and System().
loadAddrOffset
Addr System::loadAddrOffset
Offset that should be used for binary/symbol loading.
This further allows more flexibility than the loadAddrMask allows alone in loading kernels and similar. The loadAddrOffset is applied after the loadAddrMask.
Definition at line 249 of file system.hh.
Referenced by FreebsdArmSystem::initState(), LinuxArmSystem::initState(), ArmSystem::initState(), initState(), and System().
masters
std::vector<MasterInfo> System::masters protected
This array is a per-system list of all devices capable of issuing a memory system request and an associated string for each master id.
It's used to uniquely id any master in the system by name for things like cache statistics.
Definition at line 334 of file system.hh.
Referenced by _getMasterId(), getMasterName(), and lookupMasterId().
maxPID
const int System::maxPID = 32768 static
Definition at line 629 of file system.hh.
Referenced by cloneFunc(), and Process::Process().
memoryMode
Enums::MemoryMode System::memoryMode protected
Definition at line 320 of file system.hh.
Referenced by bypassCaches(), getMemoryMode(), isAtomicMode(), isTimingMode(), and setMemoryMode().
multiThread
const bool System::multiThread
Definition at line 191 of file system.hh.
Referenced by ArmISA::getMPIDR(), and BaseCPU::registerThreadContexts().
numSystemsRunning
int System::numSystemsRunning = 0 static
Definition at line 623 of file system.hh.
Referenced by IGbE::ethRxPkt(), and System().
numWorkIds
uint32_t System::numWorkIds protected
Definition at line 326 of file system.hh.
Referenced by regStats(), workItemEnd(), and ~System().
pagePtr
Addr System::pagePtr
Definition at line 209 of file system.hh.
Referenced by allocPhysPages(), freeMemSize(), serialize(), and unserialize().
physmem
PhysicalMemory System::physmem protected
Definition at line 318 of file system.hh.
Referenced by allocPhysPages(), freeMemSize(), getPhysMem(), LinuxArmSystem::initState(), isMemAddr(), memSize(), serialize(), and unserialize().
physProxy
PortProxy System::physProxy
Port to physical memory used for writing object files into ram at boot.
Definition at line 215 of file system.hh.
Referenced by TsunamiPChip::dmaAddr(), Gicv3Redistributor::init(), BareMetalRiscvSystem::initState(), SparcSystem::initState(), AlphaSystem::initState(), LinuxX86System::initState(), FreebsdArmSystem::initState(), X86System::initState(), LinuxArmSystem::initState(), X86ISA::X86_64Process::initState(), ArmSystem::initState(), initState(), MultiLevelPageTable< EntryTypes >::map(), SimpleDisk::read(), MultiLevelPageTable< EntryTypes >::remap(), DmaReadFifo::resumeFillFunctional(), MultiLevelPageTable< EntryTypes >::unmap(), X86System::writeOutMPTable(), and X86System::writeOutSMBiosTable().
PIDs
std::set<int> System::PIDs
Process set to track which PIDs have already been allocated.
Definition at line 632 of file system.hh.
Referenced by Process::Process().
redirectPaths
std::vector<RedirectPath*> System::redirectPaths
Definition at line 641 of file system.hh.
Referenced by Process::checkPathRedirect().
remoteGDB
std::vector<BaseRemoteGDB *> System::remoteGDB
Definition at line 561 of file system.hh.
Referenced by breakpoint(), registerThreadContext(), and replaceThreadContext().
signalList
std::list<BasicSignal> System::signalList
Definition at line 636 of file system.hh.
Referenced by exitImpl(), pollFunc(), selectFunc(), and wait4Func().
systemList
vector< System * > System::systemList static
Definition at line 622 of file system.hh.
Referenced by breakAtKernelFunction(), IGbE::ethRxPkt(), exitImpl(), printSystems(), and System().
thermalModel
ThermalModel* System::thermalModel protected
Definition at line 336 of file system.hh.
Referenced by getThermalModel().
threadContexts
std::vector<ThreadContext *> System::threadContexts
Definition at line 190 of file system.hh.
Referenced by IntrControl::clear(), TsunamiCChip::clearDRIR(), MaltaCChip::clearIntr(), TsunamiCChip::clearIPI(), TsunamiCChip::clearITI(), SparcISA::TLB::doMmuRegWrite(), exitImpl(), Process::findFreeContext(), Iob::generateIpi(), LinuxX86System::initState(), FreebsdArmSystem::initState(), X86System::initState(), LinuxArmSystem::initState(), ArmSystem::initState(), initState(), FullO3CPU< O3CPUImpl >::insertThread(), numRunningContexts(), IntrControl::post(), TsunamiCChip::postDRIR(), MaltaCChip::postIntr(), TsunamiCChip::postRTC(), SparcISA::ISA::readFSReg(), registerThreadContext(), remove(), replaceThreadContext(), TsunamiCChip::reqIPI(), schedule(), setpgidFunc(), LinuxArmSystem::startup(), tgkillFunc(), validKvmEnvironment(), and PseudoInst::wakeCPU().
totalNumInsts
Counter System::totalNumInsts
Definition at line 612 of file system.hh.
Referenced by BaseSimpleCPU::countInst(), Minor::Execute::doInstCommitAccounting(), TimingSimpleCPU::drainResume(), drainResume(), FullO3CPU< O3CPUImpl >::instDone(), and BaseKvmCPU::kvmRun().
workItemsBegin
uint64_t System::workItemsBegin protected
Definition at line 324 of file system.hh.
Referenced by incWorkItemsBegin().
workItemsEnd
uint64_t System::workItemsEnd protected
Definition at line 325 of file system.hh.
Referenced by incWorkItemsEnd().
workItemStats
std::map<uint32_t, Stats::Histogram*> System::workItemStats
Definition at line 614 of file system.hh.
Referenced by regStats(), workItemEnd(), and ~System().
The documentation for this class was generated from the following files:
sim/system.hh
sim/system.cc