gem5: BaseCacheCompressor Class Reference
BaseCacheCompressor Class Reference abstract
Base cache compressor interface.
#include <base.hh>
Classes
class CompressionData
Public Types
typedef BaseCacheCompressorParams Params
Convenience typedef.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BaseCacheCompressor (const Params *p)
Default constructor.
virtual ~BaseCacheCompressor ()
Default destructor.
void compress (const uint64_t *data, Cycles &comp_lat, Cycles &decomp_lat, std::size_t &comp_size_bits)
Apply the compression process to the cache line.
Cycles getDecompressionLatency (const CacheBlk *blk) const
Get the decompression latency if the block is compressed.
void regStats () override
Register local statistics.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static void setDecompressionLatency (CacheBlk *blk, const Cycles lat)
Set the decompression latency of compressed block.
static void setSizeBits (CacheBlk *blk, const std::size_t size_bits)
Set the size of the compressed block, in bits.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions
virtual std::unique_ptr< CompressionData > compress (const uint64_t *cache_line, Cycles &comp_lat, Cycles &decomp_lat)=0
Apply the compression process to the cache line.
virtual void decompress (const CompressionData *comp_data, uint64_t *cache_line)=0
Apply the decompression process to the compressed data.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const std::size_t blkSize
Uncompressed cache line size (in bytes).
const std::size_t sizeThreshold
Size in bytes at which a compression is classified as bad and therefore the compressed block is restored to its uncompressed format.
Stats::Vector compressionSize
Number of blocks that were compressed to this power of two size.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class MultiCompressor
This compressor must be able to access the protected functions of its sub-compressors.
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Base cache compressor interface.
Every cache compressor must implement a compression and a decompression method.
Definition at line 54 of file base.hh.
Member Typedef Documentation
Params
typedef BaseCacheCompressorParams BaseCacheCompressor::Params
Convenience typedef.
Definition at line 117 of file base.hh.
Constructor & Destructor Documentation
BaseCacheCompressor()
BaseCacheCompressor::BaseCacheCompressor (const Params * p)
Default constructor.
Definition at line 75 of file base.cc.
References blkSize, fatal_if, and sizeThreshold.
~BaseCacheCompressor()
virtual BaseCacheCompressor::~BaseCacheCompressor () inline virtual
Default destructor.
Definition at line 127 of file base.hh.
References compress(), data, getDecompressionLatency(), regStats(), setDecompressionLatency(), and setSizeBits().
Member Function Documentation
compress() [1/2]
virtual std::unique_ptr<CompressionData> BaseCacheCompressor::compress (const uint64_t * cache_line, Cycles & comp_lat, Cycles & decomp_lat) protected pure virtual
Apply the compression process to the cache line.
Returns the number of cycles used by the compressor, however it is usually covered by a good pipelined execution, and is currently ignored. The decompression latency is also returned, in order to avoid increasing simulation time and memory consumption.
Parameters
cache_line The cache line to be compressed.
comp_lat Compression latency in number of cycles.
decomp_lat Decompression latency in number of cycles.
Returns
Cache line after compression.
Implemented in FPCD, BaseDelta< BaseType, DeltaSizeBits >, BaseDelta< uint64_t, 32 >, BaseDelta< uint32_t, 16 >, BaseDelta< uint32_t, 8 >, BaseDelta< uint64_t, 8 >, BaseDelta< uint16_t, 8 >, BaseDelta< uint64_t, 16 >, CPack, RepeatedQwordsCompressor, ZeroCompressor, MultiCompressor, and PerfectCompressor.
Referenced by BaseCache::allocateBlock(), compress(), BaseCache::updateCompressionData(), and ~BaseCacheCompressor().
compress() [2/2]
void BaseCacheCompressor::compress (const uint64_t * data, Cycles & comp_lat, Cycles & decomp_lat, std::size_t & comp_size_bits)
Apply the compression process to the cache line.
Ignores compression cycles.
Parameters
data The cache line to be compressed.
comp_lat Compression latency in number of cycles.
decomp_lat Decompression latency in number of cycles.
comp_size_bits Compressed data size (in bits).
Definition at line 82 of file base.cc.
References blkSize, compress(), compressionSize, decompress(), DPRINTF, fatal_if, and sizeThreshold.
decompress()
virtual void BaseCacheCompressor::decompress (const CompressionData * comp_data, uint64_t * cache_line) protected pure virtual
Apply the decompression process to the compressed data.
Parameters
comp_data Compressed cache line.
cache_line The cache line to be decompressed.
Implemented in DictionaryCompressor< T >, DictionaryCompressor< uint32_t >, DictionaryCompressor< uint16_t >, DictionaryCompressor< BaseType >, DictionaryCompressor< uint64_t >, MultiCompressor, and PerfectCompressor.
Referenced by compress(), and DictionaryCompressor< T >::Pattern::print().
getDecompressionLatency()
Cycles BaseCacheCompressor::getDecompressionLatency (const CacheBlk * blk) const
Get the decompression latency if the block is compressed.
Latency is 0 otherwise.
Parameters
blk The compressed block.
Definition at line 119 of file base.cc.
References DPRINTF, CompressionBlk::getDecompressionLatency(), CompressionBlk::isCompressed(), and CompressionBlk::print().
Referenced by BaseCache::access(), Cache::handleSnoop(), BaseCache::writebackBlk(), BaseCache::writecleanBlk(), and ~BaseCacheCompressor().
regStats()
void BaseCacheCompressor::regStats () override virtual
Register local statistics.
Reimplemented from Stats::Group.
Reimplemented in BaseDictionaryCompressor, and MultiCompressor.
Definition at line 156 of file base.cc.
References blkSize, compressionSize, Stats::DataWrap< Derived, InfoProxyType >::desc(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::Group::regStats(), Stats::DataWrapVec< Derived, InfoProxyType >::subdesc(), Stats::DataWrapVec< Derived, InfoProxyType >::subname(), and sc_dt::to_string().
Referenced by MultiCompressor::regStats(), BaseDictionaryCompressor::regStats(), and ~BaseCacheCompressor().
setDecompressionLatency()
void BaseCacheCompressor::setDecompressionLatency (CacheBlk * blk, const Cycles lat) static
Set the decompression latency of compressed block.
Parameters
blk The compressed block.
lat The decompression latency.
Definition at line 136 of file base.cc.
Referenced by BaseCache::allocateBlock(), and ~BaseCacheCompressor().
setSizeBits()
void BaseCacheCompressor::setSizeBits (CacheBlk * blk, const std::size_t size_bits) static
Set the size of the compressed block, in bits.
Parameters
blk The compressed block.
size_bits The block size.
Definition at line 146 of file base.cc.
Referenced by DictionaryCompressor< T >::CompData::addEntry(), BaseCache::allocateBlock(), BaseDelta< uint64_t, 16 >::compress(), and ~BaseCacheCompressor().
Friends And Related Function Documentation
MultiCompressor
friend class MultiCompressor friend
This compressor must be able to access the protected functions of its sub-compressors.
Definition at line 60 of file base.hh.
Member Data Documentation
blkSize
const std::size_t BaseCacheCompressor::blkSize protected
Uncompressed cache line size (in bytes).
Definition at line 66 of file base.hh.
Referenced by BaseCacheCompressor(), PerfectCompressor::compress(), MultiCompressor::compress(), RepeatedQwordsCompressor::compress(), ZeroCompressor::compress(), CPack::compress(), compress(), FPCD::compress(), DictionaryCompressor< uint64_t >::compress(), PerfectCompressor::decompress(), DictionaryCompressor< uint64_t >::decompress(), and regStats().
sizeThreshold
const std::size_t BaseCacheCompressor::sizeThreshold protected
Size in bytes at which a compression is classified as bad and therefore the compressed block is restored to its uncompressed format.
Definition at line 77 of file base.hh.
Referenced by BaseCacheCompressor(), and compress().
The documentation for this class was generated from the following files:
mem/cache/compressors/base.hh
mem/cache/compressors/base.cc