gem5: ArmV8KvmCPU Class Reference
ArmV8KvmCPU Class Reference
This is an implementation of a KVM-based ARMv8-compatible CPU.
#include <armv8_cpu.hh>
Classes
struct IntRegInfo
Mapping between integer registers in gem5 and KVM.
struct MiscRegInfo
Mapping between misc registers in gem5 and registers in KVM.
Public Member Functions
ArmV8KvmCPU (ArmV8KvmCPUParams *params)
virtual ~ArmV8KvmCPU ()
void startup () override
startup() is the final initialization call before simulation.
void dump () const override
Dump the internal state to the terminal.
Public Member Functions inherited from BaseArmKvmCPU
BaseArmKvmCPU (BaseArmKvmCPUParams *params)
virtual ~BaseArmKvmCPU ()
void startup () override
startup() is the final initialization call before simulation.
Public Member Functions inherited from BaseKvmCPU
BaseKvmCPU (BaseKvmCPUParams *params)
virtual ~BaseKvmCPU ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void startup () override
startup() is the final initialization call before simulation.
void regStats () override
Callback to set stat parameters.
void serializeThread (CheckpointOut &cp, ThreadID tid) const override
Serialize a single thread.
void unserializeThread (CheckpointIn &cp, ThreadID tid) override
Unserialize one thread.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void notifyFork () override
Notify a child process of a fork.
void switchOut () override
Prepare for another CPU to take over execution.
void takeOverFrom (BaseCPU *cpu) override
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void verifyMemoryMode () const override
Verify that the system is in a memory mode supported by the CPU.
Port & getDataPort () override
Purely virtual method that returns a reference to the data port.
Port & getInstPort () override
Purely virtual method that returns a reference to the instruction port.
void wakeup (ThreadID tid=0) override
void activateContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now active.
void suspendContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now suspended.
void deallocateContext (ThreadID thread_num)
void haltContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now halted.
long getVCpuID () const
ThreadContext * getContext (int tn) override
Given a thread num get tho thread context for it.
Counter totalInsts () const override
Counter totalOps () const override
void finishMMIOPending ()
Callback from KvmCPUPort to transition the CPU out of RunningMMIOPending when all timing requests have completed.
void kick () const
Force an exit from KVM.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void regProbePoints () override
Register probe points for this object.
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void updateKvmState () override
Update the KVM state from the current thread context.
void updateThreadContext () override
Update the current thread context with the KVM state.
const std::vector< ArmV8KvmCPU::MiscRegInfo > & getSysRegMap () const
Get a map between system registers in kvm and gem5 registers.
Protected Member Functions inherited from BaseArmKvmCPU
Tick kvmRun (Tick ticks) override
Request KVM to run the guest for a given number of ticks.
const RegIndexVector & getRegList () const
Get a list of registers supported by getOneReg() and setOneReg().
void kvmArmVCpuInit (const struct kvm_vcpu_init &init)
Tell the kernel to initialize this CPU.
Protected Member Functions inherited from BaseKvmCPU
void tick ()
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
virtual uint64_t getHostCycles () const
Get the value of the hardware cycle counter in the guest.
virtual Tick kvmRunDrain ()
Request the CPU to run until draining completes.
struct kvm_run * getKvmRunState ()
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
uint8_t * getGuestData (uint64_t offset) const
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
void kvmNonMaskableInterrupt ()
Send a non-maskable interrupt to the guest.
void kvmInterrupt (const struct kvm_interrupt &interrupt)
Send a normal interrupt to the guest.
std::string getAndFormatOneReg (uint64_t id) const
Get and format one register for printout.
virtual bool archIsDrained () const
Is the architecture specific code in a state that prevents draining?
Tick doMMIOAccess (Addr paddr, void *data, int size, bool write)
Inject a memory mapped IO request into gem5.
int ioctl (int request, long p1) const
vCPU ioctl interface.
int ioctl (int request, void *p1) const
int ioctl (int request) const
void getRegisters (struct kvm_regs &regs) const
Get/Set the register state of the guest vCPU.
void setRegisters (const struct kvm_regs &regs)
void getSpecialRegisters (struct kvm_sregs &regs) const
void setSpecialRegisters (const struct kvm_sregs &regs)
void getFPUState (struct kvm_fpu &state) const
Get/Set the guest FPU/vector state.
void setFPUState (const struct kvm_fpu &state)
void setOneReg (uint64_t id, const void *addr)
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
void setOneReg (uint64_t id, uint64_t value)
void setOneReg (uint64_t id, uint32_t value)
void getOneReg (uint64_t id, void *addr) const
uint64_t getOneRegU64 (uint64_t id) const
uint32_t getOneRegU32 (uint64_t id) const
void syncThreadContext ()
Update a thread context if the KVM state is dirty with respect to the cached thread context.
EventQueue * deviceEventQueue ()
Get a pointer to the event queue owning devices.
void syncKvmState ()
Update the KVM if the thread context is dirty.
virtual Tick handleKvmExit ()
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
virtual Tick handleKvmExitIO ()
The guest performed a legacy IO request (out/inp on x86)
virtual Tick handleKvmExitHypercall ()
The guest requested a monitor service using a hypercall.
virtual Tick handleKvmExitIRQWindowOpen ()
The guest exited because an interrupt window was requested.
virtual Tick handleKvmExitUnknown ()
An unknown architecture dependent error occurred when starting the vCPU.
virtual Tick handleKvmExitException ()
An unhandled virtualization exception occured.
virtual Tick handleKvmExitFailEntry ()
KVM failed to start the virtualized CPU.
void setSignalMask (const sigset_t *mask)
Set the signal mask used in kvmRun()
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
std::vector< ArmV8KvmCPU::MiscRegInfo > sysRegMap
Cached mapping between system registers in kvm and misc regs in gem5.
Protected Attributes inherited from BaseArmKvmCPU
bool irqAsserted
Cached state of the IRQ line.
bool fiqAsserted
Cached state of the FIQ line.
Protected Attributes inherited from BaseKvmCPU
Status _status
CPU run state.
KVMCpuPort dataPort
Port for data requests.
KVMCpuPort instPort
Unused dummy port for the instruction interface.
const bool alwaysSyncTC
Be conservative and always synchronize the thread context on KVM entry/exit.
bool threadContextDirty
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
bool kvmStateDirty
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
const long vcpuID
KVM internal ID of the vCPU.
pthread_t vcpuThread
ID of the vCPU thread.
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const std::vector< ArmV8KvmCPU::IntRegInfo > intRegMap
Mapping between gem5 integer registers and integer registers in kvm.
static const std::vector< ArmV8KvmCPU::MiscRegInfo > miscRegMap
Mapping between gem5 misc registers and registers in kvm.
static const std::set< MiscRegIndex > deviceRegSet
Device registers (needing "effectful" MiscReg writes)
static const std::vector< ArmV8KvmCPU::MiscRegInfo > miscRegIdMap
Mapping between gem5 ID misc registers and registers in kvm.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BaseKvmCPU
SimpleThread * thread
A cached copy of a thread's state in the form of a SimpleThread object.
ThreadContext * tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
KvmVM & vm
Counter ctrInsts
Number of instructions executed by the CPU.
Stats::Scalar numInsts
Stats::Scalar numVMExits
Stats::Scalar numVMHalfEntries
Stats::Scalar numExitSignal
Stats::Scalar numMMIO
Stats::Scalar numCoalescedMMIO
Stats::Scalar numIO
Stats::Scalar numHalt
Stats::Scalar numInterrupts
Stats::Scalar numHypercalls
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from BaseArmKvmCPU
typedef std::vector< uint64_t > RegIndexVector
Protected Types inherited from BaseKvmCPU
enum Status {
Idle, Running, RunningService, RunningMMIOPending,
RunningServiceCompletion
}
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Detailed Description
This is an implementation of a KVM-based ARMv8-compatible CPU.
Known limitations:
The system-register-based generic timer can only be simulated by the host kernel. Workaround: Use a memory mapped timer instead to simulate the timer in gem5.
Simulating devices (e.g., the generic timer) in the host kernel requires that the host kernel also simulates the GIC.
ID registers in the host and in gem5 must match for switching between simulated CPUs and KVM. This is particularly important for ID registers describing memory system capabilities (e.g., ASID size, physical address size).
Switching between a virtualized CPU and a simulated CPU is currently not supported if in-kernel device emulation is used. This could be worked around by adding support for switching to the gem5 (e.g., the KvmGic) side of the device models. A simpler workaround is to avoid in-kernel device models altogether.
Definition at line 81 of file armv8_cpu.hh.
Constructor & Destructor Documentation
ArmV8KvmCPU()
ArmV8KvmCPU::ArmV8KvmCPU (ArmV8KvmCPUParams * params)
Definition at line 126 of file armv8_cpu.cc.
Referenced by getSysRegMap().
~ArmV8KvmCPU()
ArmV8KvmCPU::~ArmV8KvmCPU () virtual
Definition at line 131 of file armv8_cpu.cc.
Member Function Documentation
dump()
void ArmV8KvmCPU::dump () const override virtual
Dump the internal state to the terminal.
Reimplemented from BaseKvmCPU.
Definition at line 149 of file armv8_cpu.cc.
References ArmISA::decodeAArch64SysReg(), EXTRACT_FIELD, BaseKvmCPU::getAndFormatOneReg(), BaseArmKvmCPU::getRegList(), ArmISA::i, ArmISA::id, inform, INT_REG, intRegMap, kvmFPReg(), kvmXReg(), miscRegIdMap, miscRegMap, ArmISA::miscRegName, NUM_QREGS, NUM_XREGS, X86ISA::reg, type, and X86ISA::val.
getSysRegMap()
const std::vector< ArmV8KvmCPU::MiscRegInfo > & ArmV8KvmCPU::getSysRegMap () const protected
Get a map between system registers in kvm and gem5 registers.
This method returns a mapping between system registers in kvm and misc regs in gem5. The actual mapping is only created the first time the method is called and stored in a cache (ArmV8KvmCPU::sysRegMap).
Returns
Vector of kvm<->misc reg mappings.
Definition at line 359 of file armv8_cpu.cc.
References ArmV8KvmCPU(), ArmISA::decodeAArch64SysReg(), deviceRegSet, EXTRACT_FIELD, BaseArmKvmCPU::getRegList(), ArmISA::MISCREG_HYP_WR, ArmISA::MISCREG_IMPLEMENTED, ArmISA::MISCREG_MON_NS0_WR, ArmISA::MISCREG_MON_NS1_WR, ArmISA::MISCREG_PRI_NS_WR, ArmISA::MISCREG_PRI_S_WR, ArmISA::MISCREG_USR_NS_WR, ArmISA::MISCREG_USR_S_WR, ArmISA::MISCREG_WARN_NOT_FAIL, ArmISA::miscRegInfo, ArmISA::miscRegName, X86ISA::reg, sysRegMap, and type.
Referenced by updateKvmState(), and updateThreadContext().
startup()
void ArmV8KvmCPU::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 136 of file armv8_cpu.cc.
References DPRINTF, miscRegIdMap, ThreadContext::readMiscReg(), BaseKvmCPU::setOneReg(), BaseArmKvmCPU::startup(), and BaseKvmCPU::tc.
updateKvmState()
void ArmV8KvmCPU::updateKvmState () override protected virtual
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implements BaseKvmCPU.
Definition at line 216 of file armv8_cpu.cc.
References ArmISA::CCREG_C, ArmISA::CCREG_GE, ArmISA::CCREG_NZ, ArmISA::CCREG_V, KvmFPReg::data, BaseKvmCPU::deviceEventQueue(), DPRINTF, FP_REGS_PER_VFP_REG, BaseKvmCPU::getAndFormatOneReg(), getSysRegMap(), ArmISA::i, KvmFPReg::i, ThreadContext::instAddr(), INT_REG, ArmISA::INTREG_X0, intRegMap, ArmISA::j, kvmFPReg(), kvmXReg(), ArmISA::MISCREG_CPSR, miscRegMap, NUM_QREGS, NUM_XREGS, ThreadContext::readCCReg(), ThreadContext::readFloatReg(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), X86ISA::reg, KvmFPReg::s, BaseKvmCPU::setOneReg(), and BaseKvmCPU::tc.
updateThreadContext()
void ArmV8KvmCPU::updateThreadContext () override protected virtual
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implements BaseKvmCPU.
Definition at line 282 of file armv8_cpu.cc.
References ArmISA::CCREG_C, ArmISA::CCREG_GE, ArmISA::CCREG_NZ, ArmISA::CCREG_V, KvmFPReg::data, BaseKvmCPU::deviceEventQueue(), DPRINTF, FP_REGS_PER_VFP_REG, BaseKvmCPU::getAndFormatOneReg(), BaseKvmCPU::getOneReg(), BaseKvmCPU::getOneRegU64(), getSysRegMap(), ArmISA::i, KvmFPReg::i, ArmISA::inAArch64(), INT_REG, ArmISA::IntReg64Map, ArmISA::INTREG_X0, intRegMap, ArmISA::j, kvmFPReg(), kvmXReg(), ArmISA::MISCREG_CPSR, miscRegMap, NUM_QREGS, NUM_XREGS, MipsISA::pc, ThreadContext::pcState(), X86ISA::reg, KvmFPReg::s, ThreadContext::setCCReg(), ThreadContext::setFloatReg(), ThreadContext::setIntReg(), ThreadContext::setIntRegFlat(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), and BaseKvmCPU::tc.
Member Data Documentation
deviceRegSet
const std::set< MiscRegIndex > ArmV8KvmCPU::deviceRegSet static protected
Initial value:
= {
    MISCREG_CNTV_CTL_EL0,
    MISCREG_CNTV_CVAL_EL0,
    MISCREG_CNTKCTL_EL1,
}
Device registers (needing "effectful" MiscReg writes)
Definition at line 142 of file armv8_cpu.hh.
Referenced by getSysRegMap().
intRegMap
const std::vector< ArmV8KvmCPU::IntRegInfo > ArmV8KvmCPU::intRegMap static protected
Initial value:
= {
    { INT_REG(regs.sp), INTREG_SP0, "SP(EL0)" },
    { INT_REG(sp_el1), INTREG_SP1, "SP(EL1)" },
}
Mapping between gem5 integer registers and integer registers in kvm.
Definition at line 138 of file armv8_cpu.hh.
Referenced by dump(), updateKvmState(), and updateThreadContext().
miscRegIdMap
const std::vector< ArmV8KvmCPU::MiscRegInfo > ArmV8KvmCPU::miscRegIdMap static protected
Initial value:
= {
    MiscRegInfo(SYS_MPIDR_EL1, MISCREG_MPIDR_EL1, "MPIDR(EL1)"),
}
Mapping between gem5 ID misc registers and registers in kvm.
Definition at line 144 of file armv8_cpu.hh.
Referenced by dump(), and startup().
miscRegMap
const std::vector< ArmV8KvmCPU::MiscRegInfo > ArmV8KvmCPU::miscRegMap static protected
Initial value:
= {
    MiscRegInfo(INT_REG(elr_el1), MISCREG_ELR_EL1, "ELR(EL1)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_EL1]), MISCREG_SPSR_EL1, "SPSR(EL1)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_ABT]), MISCREG_SPSR_ABT, "SPSR(ABT)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_UND]), MISCREG_SPSR_UND, "SPSR(UND)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_IRQ]), MISCREG_SPSR_IRQ, "SPSR(IRQ)"),
    MiscRegInfo(INT_REG(spsr[KVM_SPSR_FIQ]), MISCREG_SPSR_FIQ, "SPSR(FIQ)"),
    MiscRegInfo(CORE_REG(fp_regs.fpsr, U32), MISCREG_FPSR, "FPSR"),
    MiscRegInfo(CORE_REG(fp_regs.fpcr, U32), MISCREG_FPCR, "FPCR"),
}
Mapping between gem5 misc registers and registers in kvm.
Definition at line 140 of file armv8_cpu.hh.
Referenced by dump(), updateKvmState(), and updateThreadContext().
sysRegMap
std::vector<ArmV8KvmCPU::MiscRegInfo> ArmV8KvmCPU::sysRegMap mutable protected
Cached mapping between system registers in kvm and misc regs in gem5.
Definition at line 147 of file armv8_cpu.hh.
Referenced by getSysRegMap().
The documentation for this class was generated from the following files:
arch/arm/kvm/armv8_cpu.hh
arch/arm/kvm/armv8_cpu.cc