gem5: sc_core::sc_event Class Reference
sc_core::sc_event Class Reference
#include <sc_event.hh>
Public Member Functions
sc_event ()
sc_event (const char *)
~sc_event ()
const char * name () const
const char * basename () const
bool in_hierarchy () const
sc_object * get_parent_object () const
void notify ()
void notify (const sc_time &)
void notify (double, sc_time_unit)
void cancel ()
bool triggered () const
void notify_delayed ()
void notify_delayed (const sc_time &)
sc_event_and_expr operator& (const sc_event &) const
sc_event_and_expr operator& (const sc_event_and_list &) const
sc_event_or_expr operator| (const sc_event &) const
sc_event_or_expr operator| (const sc_event_or_list &) const
Protected Member Functions
sc_event (bool)
sc_event (bool, const char *)
Private Member Functions
sc_event (const sc_event &)
sc_event & operator= (const sc_event &)
Private Attributes
::sc_gem5::Event * _gem5_event
Friends
class ::sc_gem5::Event
Detailed Description
Definition at line 171 of file sc_event.hh.
Constructor & Destructor Documentation
sc_event() [1/5]
sc_core::sc_event::sc_event ()
Definition at line 314 of file sc_event.cc.
sc_event() [2/5]
sc_core::sc_event::sc_event (const char * _name) explicit
Definition at line 319 of file sc_event.cc.
~sc_event()
sc_core::sc_event::~sc_event ()
Definition at line 323 of file sc_event.cc.
References _gem5_event.
sc_event() [3/5]
sc_core::sc_event::sc_event (bool) explicit protected
Definition at line 391 of file sc_event.cc.
sc_event() [4/5]
sc_core::sc_event::sc_event (bool , const char * _name) explicit protected
Definition at line 397 of file sc_event.cc.
sc_event() [5/5]
sc_core::sc_event::sc_event (const sc_event &) inline private
Definition at line 207 of file sc_event.hh.
Member Function Documentation
basename()
const char * sc_core::sc_event::basename () const
Definition at line 327 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::basename().
cancel()
void sc_core::sc_event::cancel ()
Definition at line 342 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::cancel().
Referenced by sc_core::sc_event_queue::cancel_all(), and tlm_utils::peq_with_get< transaction_type >::cancel_all().
get_parent_object()
sc_object * sc_core::sc_event::get_parent_object () const
Definition at line 334 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::getParentObject().
in_hierarchy()
bool sc_core::sc_event::in_hierarchy () const
Definition at line 331 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::inHierarchy().
name()
const char * sc_core::sc_event::name () const
Definition at line 325 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::name().
notify() [1/3]
void sc_core::sc_event::notify ()
Definition at line 339 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::notify().
Referenced by sc_gem5::ScSignalBase::_signalChange(), sc_core::sc_event_queue::_trigger(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), Iris::BaseCPU::clockPeriodUpdated(), SimpleATTarget1::endRequest(), SimpleATTarget2::endResponse(), SimpleATTarget1::endResponse(), SimpleATInitiator1::endResponse(), MultiSocketSimpleSwitchAT::free(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), MultiSocketSimpleSwitchAT::fwPEQcb(), SimpleLTTarget1::get_direct_mem_ptr(), tlm_utils::peq_with_get< transaction_type >::get_next_transaction(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorNBTransport(), SimpleLTTarget_ext::myGetDMIPtr(), ExplicitATTarget::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), SimpleLTInitiator_ext::myNBTransport(), SimpleATInitiator2::myNBTransport(), SimpleATInitiator1::myNBTransport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::peq_with_get< transaction_type >::notify(), sc_core::sc_event_queue::notify(), sc_core::sc_semaphore::post(), SimpleATInitiator1::run(), sc_core::sc_join::signal(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::targetNBTransport(), sc_gem5::Process::terminate(), sc_core::sc_mutex::unlock(), tlm::tlm_fifo< T >::update(), sc_core::sc_fifo< T >::update(), and sc_gem5::Scheduler::yield().
notify() [2/3]
void sc_core::sc_event::notify (const sc_time & t)
Definition at line 340 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::notify().
notify() [3/3]
void sc_core::sc_event::notify (double d, sc_time_unit u)
Definition at line 341 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::notify().
notify_delayed() [1/2]
void sc_core::sc_event::notify_delayed ()
Definition at line 345 of file sc_event.cc.
References _gem5_event, sc_gem5::Event::notifyDelayed(), and sc_core::SC_ZERO_TIME.
notify_delayed() [2/2]
void sc_core::sc_event::notify_delayed (const sc_time & t)
Definition at line 350 of file sc_event.cc.
References _gem5_event, sc_core::sc_event_and_expr::insert(), sc_gem5::Event::notifyDelayed(), and operator&().
operator&() [1/2]
sc_event_and_expr sc_core::sc_event::operator & (const sc_event &) const
Referenced by notify_delayed().
operator&() [2/2]
sc_event_and_expr sc_core::sc_event::operator & (const sc_event_and_list &) const
operator=()
sc_event& sc_core::sc_event::operator= (const sc_event &) inline private
Definition at line 208 of file sc_event.hh.
operator|() [1/2]
sc_event_or_expr sc_core::sc_event::operator| (const sc_event & e) const
Definition at line 374 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
operator|() [2/2]
sc_event_or_expr sc_core::sc_event::operator| (const sc_event_or_list & eol) const
Definition at line 383 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
triggered()
bool sc_core::sc_event::triggered () const
Definition at line 343 of file sc_event.cc.
References _gem5_event, and sc_gem5::Event::triggered().
Friends And Related Function Documentation
::sc_gem5::Event
friend class ::sc_gem5::Event friend
Definition at line 210 of file sc_event.hh.
Member Data Documentation
_gem5_event
::sc_gem5::Event* sc_core::sc_event::_gem5_event private
Definition at line 211 of file sc_event.hh.
Referenced by basename(), cancel(), get_parent_object(), sc_gem5::Event::getFromScEvent(), in_hierarchy(), name(), notify(), notify_delayed(), triggered(), and ~sc_event().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_event.hh
systemc/core/sc_event.cc