gem5: PhysRegFile Class Reference
PhysRegFile Class Reference
Simple physical register file class.
#include <regfile.hh>
Public Types
using IdRange = std::pair< PhysIds::iterator, PhysIds::iterator >
Public Member Functions
PhysRegFile (unsigned _numPhysicalIntRegs, unsigned _numPhysicalFloatRegs, unsigned _numPhysicalVecRegs, unsigned _numPhysicalVecPredRegs, unsigned _numPhysicalCCRegs, VecMode vmode)
Constructs a physical register file with the specified amount of integer and floating point registers.
~PhysRegFile ()
Destructor to free resources.
void initFreeList (UnifiedFreeList *freeList)
Initialize the free list.
unsigned numIntPhysRegs () const
unsigned numFloatPhysRegs () const
unsigned numVecPhysRegs () const
unsigned numPredPhysRegs () const
unsigned numVecElemPhysRegs () const
unsigned numCCPhysRegs () const
unsigned totalNumPhysRegs () const
PhysRegIdPtr getMiscRegId (RegIndex reg_idx)
Gets a misc register PhysRegIdPtr.
RegVal readIntReg (PhysRegIdPtr phys_reg) const
Reads an integer register.
RegVal readFloatReg (PhysRegIdPtr phys_reg) const
const VecRegContainer & readVecReg (PhysRegIdPtr phys_reg) const
Reads a vector register.
VecRegContainer & getWritableVecReg (PhysRegIdPtr phys_reg)
Reads a vector register for modification.
template<typename VecElem , int LaneIdx>
VecLaneT< VecElem, true > readVecLane (PhysRegIdPtr phys_reg) const
Reads a vector register lane.
template<typename VecElem >
VecLaneT< VecElem, true > readVecLane (PhysRegIdPtr phys_reg) const
Reads a vector register lane.
template<typename LD >
void setVecLane (PhysRegIdPtr phys_reg, const LD &val)
Get a vector register lane for modification.
const VecElem & readVecElem (PhysRegIdPtr phys_reg) const
Reads a vector element.
const VecPredRegContainer & readVecPredReg (PhysRegIdPtr phys_reg) const
Reads a predicate register.
VecPredRegContainer & getWritableVecPredReg (PhysRegIdPtr phys_reg)
RegVal readCCReg (PhysRegIdPtr phys_reg)
Reads a condition-code register.
void setIntReg (PhysRegIdPtr phys_reg, RegVal val)
Sets an integer register to the given value.
void setFloatReg (PhysRegIdPtr phys_reg, RegVal val)
void setVecReg (PhysRegIdPtr phys_reg, const VecRegContainer &val)
Sets a vector register to the given value.
void setVecElem (PhysRegIdPtr phys_reg, const VecElem val)
Sets a vector register to the given value.
void setVecPredReg (PhysRegIdPtr phys_reg, const VecPredRegContainer &val)
Sets a predicate register to the given value.
void setCCReg (PhysRegIdPtr phys_reg, RegVal val)
Sets a condition-code register to the given value.
IdRange getRegElemIds (PhysRegIdPtr reg)
Get the PhysRegIds of the elems of a vector register.
IdRange getRegIds (RegClass cls)
Get the PhysRegIds of the elems of all vector registers.
PhysRegIdPtr getTrueId (PhysRegIdPtr reg)
Get the true physical register id.
Private Types
using VecElem = TheISA::VecElem
using VecRegContainer = TheISA::VecRegContainer
using PhysIds = std::vector< PhysRegId >
using VecMode = Enums::VecRegRenameMode
using VecPredRegContainer = TheISA::VecPredRegContainer
Private Attributes
std::vector< RegVal > intRegFile
Integer register file.
std::vector< PhysRegId > intRegIds
std::vector< RegVal > floatRegFile
Floating point register file.
std::vector< PhysRegId > floatRegIds
std::vector< VecRegContainer > vectorRegFile
Vector register file.
std::vector< PhysRegId > vecRegIds
std::vector< PhysRegId > vecElemIds
std::vector< VecPredRegContainer > vecPredRegFile
Predicate register file.
std::vector< PhysRegId > vecPredRegIds
std::vector< RegVal > ccRegFile
Condition-code register file.
std::vector< PhysRegId > ccRegIds
std::vector< PhysRegId > miscRegIds
Misc Reg Ids.
unsigned numPhysicalIntRegs
Number of physical general purpose registers.
unsigned numPhysicalFloatRegs
Number of physical floating point registers.
unsigned numPhysicalVecRegs
Number of physical vector registers.
unsigned numPhysicalVecElemRegs
Number of physical vector element registers.
unsigned numPhysicalVecPredRegs
Number of physical predicate registers.
unsigned numPhysicalCCRegs
Number of physical CC registers.
unsigned totalNumRegs
Total number of physical registers.
VecMode vecMode
Mode in which vector registers are addressed.
Static Private Attributes
static constexpr auto NumVecElemPerVecReg = TheISA::NumVecElemPerVecReg
Detailed Description
Simple physical register file class.
Definition at line 63 of file regfile.hh.
Member Typedef Documentation
IdRange
using PhysRegFile::IdRange = std::pair<PhysIds::iterator, PhysIds::iterator>
Definition at line 74 of file regfile.hh.
PhysIds
using PhysRegFile::PhysIds = std::vector<PhysRegId> private
Definition at line 69 of file regfile.hh.
VecElem
using PhysRegFile::VecElem = TheISA::VecElem private
Definition at line 67 of file regfile.hh.
VecMode
using PhysRegFile::VecMode = Enums::VecRegRenameMode private
Definition at line 70 of file regfile.hh.
VecPredRegContainer
using PhysRegFile::VecPredRegContainer = TheISA::VecPredRegContainer private
Definition at line 71 of file regfile.hh.
VecRegContainer
using PhysRegFile::VecRegContainer = TheISA::VecRegContainer private
Definition at line 68 of file regfile.hh.
Constructor & Destructor Documentation
PhysRegFile()
PhysRegFile::PhysRegFile (unsigned _numPhysicalIntRegs, unsigned _numPhysicalFloatRegs, unsigned _numPhysicalVecRegs, unsigned _numPhysicalVecPredRegs, unsigned _numPhysicalCCRegs, VecMode vmode)
Constructs a physical register file with the specified amount of integer and floating point registers.
Definition at line 52 of file regfile.cc.
References CCRegClass, ccRegIds, FloatRegClass, floatRegIds, IntRegClass, intRegIds, MiscRegClass, miscRegIds, AlphaISA::NumCCRegs, AlphaISA::NumMiscRegs, numPhysicalCCRegs, numPhysicalFloatRegs, numPhysicalIntRegs, numPhysicalVecPredRegs, numPhysicalVecRegs, NumVecElemPerVecReg, VecElemClass, vecElemIds, VecPredRegClass, vecPredRegIds, VecRegClass, vecRegIds, vectorRegFile, and warn.
~PhysRegFile()
PhysRegFile::~PhysRegFile () inline
Destructor to free resources.
Definition at line 154 of file regfile.hh.
References initFreeList().
Member Function Documentation
getMiscRegId()
PhysRegIdPtr PhysRegFile::getMiscRegId (RegIndex reg_idx) inline
Gets a misc register PhysRegIdPtr.
Definition at line 179 of file regfile.hh.
Referenced by UnifiedRenameMap::lookup().
getRegElemIds()
auto PhysRegFile::getRegElemIds (PhysRegIdPtr reg)
Get the PhysRegIds of the elems of a vector register.
Auxiliary function to transition from Full vector mode to Elem mode.
Definition at line 188 of file regfile.cc.
References NumVecElemPerVecReg, panic_if, X86ISA::reg, and vecElemIds.
Referenced by setCCReg().
getRegIds()
auto PhysRegFile::getRegIds (RegClass cls)
Get the PhysRegIds of the elems of all vector registers.
Auxiliary function to transition from Full vector mode to Elem mode and to initialise the rename map.
Definition at line 199 of file regfile.cc.
References CCRegClass, ccRegIds, FloatRegClass, floatRegIds, IntRegClass, intRegIds, MiscRegClass, miscRegIds, VecElemClass, vecElemIds, VecPredRegClass, vecPredRegIds, VecRegClass, and vecRegIds.
Referenced by setCCReg().
getTrueId()
PhysRegIdPtr PhysRegFile::getTrueId (PhysRegIdPtr reg)
Get the true physical register id.
As many parts work with PhysRegIdPtr, we need to be able to produce the pointer out of just class and register idx.
Definition at line 224 of file regfile.cc.
References RegId::className(), RegId::classValue(), RegId::elemIndex(), RegId::index(), PhysRegId::isVectorPhysElem(), NumVecElemPerVecReg, panic_if, VecElemClass, vecElemIds, VecRegClass, and vecRegIds.
Referenced by setCCReg().
getWritableVecPredReg()
VecPredRegContainer& PhysRegFile::getWritableVecPredReg (PhysRegIdPtr phys_reg) inline
Definition at line 284 of file regfile.hh.
References readVecPredReg().
Referenced by FullO3CPU< O3CPUImpl >::getWritableVecPredReg().
getWritableVecReg()
VecRegContainer& PhysRegFile::getWritableVecReg (PhysRegIdPtr phys_reg) inline
Reads a vector register for modification.
Definition at line 222 of file regfile.hh.
References readVecReg().
Referenced by FullO3CPU< O3CPUImpl >::getWritableVecReg().
initFreeList()
void PhysRegFile::initFreeList (UnifiedFreeList * freeList)
Initialize the free list.
Definition at line 135 of file regfile.cc.
References UnifiedFreeList::addRegs(), ccRegIds, floatRegIds, MipsISA::index, intRegIds, numPhysicalCCRegs, numPhysicalFloatRegs, numPhysicalIntRegs, numPhysicalVecPredRegs, numPhysicalVecRegs, NumVecElemPerVecReg, vecElemIds, vecMode, vecPredRegIds, and vecRegIds.
Referenced by UnifiedFreeList::UnifiedFreeList(), and ~PhysRegFile().
numCCPhysRegs()
unsigned PhysRegFile::numCCPhysRegs () const inline
Returns
the number of condition-code physical registers.
Definition at line 173 of file regfile.hh.
References numPhysicalCCRegs.
numFloatPhysRegs()
unsigned PhysRegFile::numFloatPhysRegs () const inline
Returns
the number of floating-point physical registers.
Definition at line 163 of file regfile.hh.
References numPhysicalFloatRegs.
numIntPhysRegs()
unsigned PhysRegFile::numIntPhysRegs () const inline
Returns
the number of integer physical registers.
Definition at line 160 of file regfile.hh.
References numPhysicalIntRegs.
numPredPhysRegs()
unsigned PhysRegFile::numPredPhysRegs () const inline
Returns
the number of predicate physical registers.
Definition at line 167 of file regfile.hh.
References numPhysicalVecPredRegs.
numVecElemPhysRegs()
unsigned PhysRegFile::numVecElemPhysRegs () const inline
Returns
the number of vector physical registers.
Definition at line 170 of file regfile.hh.
References numPhysicalVecElemRegs.
numVecPhysRegs()
unsigned PhysRegFile::numVecPhysRegs () const inline
Returns
the number of vector physical registers.
Definition at line 165 of file regfile.hh.
References numPhysicalVecRegs.
readCCReg()
RegVal PhysRegFile::readCCReg (PhysRegIdPtr phys_reg) inline
Reads a condition-code register.
Definition at line 292 of file regfile.hh.
References DPRINTF, RegId::index(), and PhysRegId::isCCPhysReg().
Referenced by FullO3CPU< O3CPUImpl >::readArchCCReg(), and FullO3CPU< O3CPUImpl >::readCCReg().
readFloatReg()
RegVal PhysRegFile::readFloatReg (PhysRegIdPtr phys_reg) const inline
Definition at line 195 of file regfile.hh.
References DPRINTF, RegId::index(), and PhysRegId::isFloatPhysReg().
Referenced by FullO3CPU< O3CPUImpl >::readArchFloatReg(), and FullO3CPU< O3CPUImpl >::readFloatReg().
readIntReg()
RegVal PhysRegFile::readIntReg (PhysRegIdPtr phys_reg) const inline
Reads an integer register.
Definition at line 185 of file regfile.hh.
References DPRINTF, RegId::index(), and PhysRegId::isIntPhysReg().
Referenced by FullO3CPU< O3CPUImpl >::readArchIntReg(), and FullO3CPU< O3CPUImpl >::readIntReg().
readVecElem()
const VecElem& PhysRegFile::readVecElem (PhysRegIdPtr phys_reg) const inline
Reads a vector element.
Definition at line 260 of file regfile.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), PhysRegId::isVectorPhysElem(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::readVecElem().
readVecLane() [1/2]
template<typename VecElem , int LaneIdx> VecLaneT<VecElem, true> PhysRegFile::readVecLane (PhysRegIdPtr phys_reg) const inline
Reads a vector register lane.
Definition at line 231 of file regfile.hh.
References VecRegContainer< Sz >::laneView(), and readVecReg().
readVecLane() [2/2]
template<typename VecElem > VecLaneT<VecElem, true> PhysRegFile::readVecLane (PhysRegIdPtr phys_reg) const inline
Reads a vector register lane.
Definition at line 239 of file regfile.hh.
References RegId::elemIndex(), VecRegContainer< Sz >::laneView(), and readVecReg().
readVecPredReg()
const VecPredRegContainer& PhysRegFile::readVecPredReg (PhysRegIdPtr phys_reg) const inline
Reads a predicate register.
Definition at line 273 of file regfile.hh.
References DPRINTF, RegId::index(), and PhysRegId::isVecPredPhysReg().
Referenced by getWritableVecPredReg(), and FullO3CPU< O3CPUImpl >::readVecPredReg().
readVecReg()
const VecRegContainer& PhysRegFile::readVecReg (PhysRegIdPtr phys_reg) const inline
Reads a vector register.
Definition at line 209 of file regfile.hh.
References DPRINTF, RegId::index(), and PhysRegId::isVectorPhysReg().
Referenced by getWritableVecReg(), readVecLane(), and FullO3CPU< O3CPUImpl >::readVecReg().
setCCReg()
void PhysRegFile::setCCReg (PhysRegIdPtr phys_reg, RegVal val) inline
Sets a condition-code register to the given value.
Definition at line 366 of file regfile.hh.
References DPRINTF, getRegElemIds(), getRegIds(), getTrueId(), RegId::index(), PhysRegId::isCCPhysReg(), X86ISA::reg, and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setArchCCReg(), and FullO3CPU< O3CPUImpl >::setCCReg().
setFloatReg()
void PhysRegFile::setFloatReg (PhysRegIdPtr phys_reg, RegVal val) inline
Definition at line 317 of file regfile.hh.
References DPRINTF, RegId::index(), PhysRegId::isFloatPhysReg(), RegId::isZeroReg(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setArchFloatReg(), and FullO3CPU< O3CPUImpl >::setFloatReg().
setIntReg()
void PhysRegFile::setIntReg (PhysRegIdPtr phys_reg, RegVal val) inline
Sets an integer register to the given value.
Definition at line 305 of file regfile.hh.
References DPRINTF, RegId::index(), PhysRegId::isIntPhysReg(), RegId::isZeroReg(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setArchIntReg(), and FullO3CPU< O3CPUImpl >::setIntReg().
setVecElem()
void PhysRegFile::setVecElem (PhysRegIdPtr phys_reg, const VecElem val) inline
Sets a vector register to the given value.
Definition at line 342 of file regfile.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), PhysRegId::isVectorPhysElem(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setVecElem().
setVecLane()
template<typename LD > void PhysRegFile::setVecLane (PhysRegIdPtr phys_reg, const LD & val) inline
Get a vector register lane for modification.
Definition at line 247 of file regfile.hh.
References DPRINTF, RegId::elemIndex(), RegId::index(), PhysRegId::isVectorPhysReg(), and X86ISA::val.
setVecPredReg()
void PhysRegFile::setVecPredReg (PhysRegIdPtr phys_reg, const VecPredRegContainer & val) inline
Sets a predicate register to the given value.
Definition at line 354 of file regfile.hh.
References DPRINTF, RegId::index(), PhysRegId::isVecPredPhysReg(), VecPredRegContainer< NumBits, Packed >::print(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setVecPredReg().
setVecReg()
void PhysRegFile::setVecReg (PhysRegIdPtr phys_reg, const VecRegContainer & val) inline
Sets a vector register to the given value.
Definition at line 330 of file regfile.hh.
References DPRINTF, RegId::index(), PhysRegId::isVectorPhysReg(), VecRegContainer< Sz >::print(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setVecReg().
totalNumPhysRegs()
unsigned PhysRegFile::totalNumPhysRegs () const inline
Returns
the total number of physical registers.
Definition at line 176 of file regfile.hh.
References totalNumRegs.
Referenced by FullO3CPU< O3CPUImpl >::FullO3CPU().
Member Data Documentation
ccRegFile
std::vector<RegVal> PhysRegFile::ccRegFile private
Condition-code register file.
Definition at line 96 of file regfile.hh.
ccRegIds
std::vector<PhysRegId> PhysRegFile::ccRegIds private
Definition at line 97 of file regfile.hh.
Referenced by getRegIds(), initFreeList(), and PhysRegFile().
floatRegFile
std::vector<RegVal> PhysRegFile::floatRegFile private
Floating point register file.
Definition at line 83 of file regfile.hh.
floatRegIds
std::vector<PhysRegId> PhysRegFile::floatRegIds private
Definition at line 84 of file regfile.hh.
Referenced by getRegIds(), initFreeList(), and PhysRegFile().
intRegFile
std::vector<RegVal> PhysRegFile::intRegFile private
Integer register file.
Definition at line 79 of file regfile.hh.
intRegIds
std::vector<PhysRegId> PhysRegFile::intRegIds private
Definition at line 80 of file regfile.hh.
Referenced by getRegIds(), initFreeList(), and PhysRegFile().
miscRegIds
std::vector<PhysRegId> PhysRegFile::miscRegIds private
Misc Reg Ids.
Definition at line 100 of file regfile.hh.
Referenced by getRegIds(), and PhysRegFile().
numPhysicalCCRegs
unsigned PhysRegFile::numPhysicalCCRegs private
Number of physical CC registers.
Definition at line 130 of file regfile.hh.
Referenced by initFreeList(), numCCPhysRegs(), and PhysRegFile().
numPhysicalFloatRegs
unsigned PhysRegFile::numPhysicalFloatRegs private
Number of physical floating point registers.
Definition at line 110 of file regfile.hh.
Referenced by initFreeList(), numFloatPhysRegs(), and PhysRegFile().
numPhysicalIntRegs
unsigned PhysRegFile::numPhysicalIntRegs private
Number of physical general purpose registers.
Definition at line 105 of file regfile.hh.
Referenced by initFreeList(), numIntPhysRegs(), and PhysRegFile().
numPhysicalVecElemRegs
unsigned PhysRegFile::numPhysicalVecElemRegs private
Number of physical vector element registers.
Definition at line 120 of file regfile.hh.
Referenced by numVecElemPhysRegs().
numPhysicalVecPredRegs
unsigned PhysRegFile::numPhysicalVecPredRegs private
Number of physical predicate registers.
Definition at line 125 of file regfile.hh.
Referenced by initFreeList(), numPredPhysRegs(), and PhysRegFile().
numPhysicalVecRegs
unsigned PhysRegFile::numPhysicalVecRegs private
Number of physical vector registers.
Definition at line 115 of file regfile.hh.
Referenced by initFreeList(), numVecPhysRegs(), and PhysRegFile().
NumVecElemPerVecReg
constexpr auto PhysRegFile::NumVecElemPerVecReg = TheISA::NumVecElemPerVecReg static private
Definition at line 76 of file regfile.hh.
Referenced by getRegElemIds(), getTrueId(), initFreeList(), and PhysRegFile().
totalNumRegs
unsigned PhysRegFile::totalNumRegs private
Total number of physical registers.
Definition at line 133 of file regfile.hh.
Referenced by totalNumPhysRegs().
vecElemIds
std::vector<PhysRegId> PhysRegFile::vecElemIds private
Definition at line 89 of file regfile.hh.
Referenced by getRegElemIds(), getRegIds(), getTrueId(), initFreeList(), and PhysRegFile().
vecMode
VecMode PhysRegFile::vecMode private
Mode in which vector registers are addressed.
Definition at line 136 of file regfile.hh.
Referenced by initFreeList().
vecPredRegFile
std::vector<VecPredRegContainer> PhysRegFile::vecPredRegFile private
Predicate register file.
Definition at line 92 of file regfile.hh.
vecPredRegIds
std::vector<PhysRegId> PhysRegFile::vecPredRegIds private
Definition at line 93 of file regfile.hh.
Referenced by getRegIds(), initFreeList(), and PhysRegFile().
vecRegIds
std::vector<PhysRegId> PhysRegFile::vecRegIds private
Definition at line 88 of file regfile.hh.
Referenced by getRegIds(), getTrueId(), initFreeList(), and PhysRegFile().
vectorRegFile
std::vector<VecRegContainer> PhysRegFile::vectorRegFile private
Vector register file.
Definition at line 87 of file regfile.hh.
Referenced by PhysRegFile().
The documentation for this class was generated from the following files:
cpu/o3/regfile.hh
cpu/o3/regfile.cc