gem5: BasePixelPump::PixelEvent Class Reference
BasePixelPump::PixelEvent Class Reference
Callback helper class with suspend support.
Public Member Functions
PixelEvent (const char *name, BasePixelPump *parent, CallbackType func)
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
const std::string name () const override
void process () override
bool active () const
Public Member Functions inherited from Event
Event (Priority p=Default_Pri, Flags f=0)
virtual ~Event ()
virtual const char * description () const
Return a C string describing the event.
void dump () const
Dump the current event data.
bool scheduled () const
Determine if the current event is scheduled.
void squash ()
Squash the current event.
bool squashed () const
Check whether the event is squashed.
bool isExitEvent () const
See if this is a SimExitEvent (without resorting to RTTI)
bool isManaged () const
Check whether this event will auto-delete.
bool isAutoDelete () const
Tick when () const
Get the time that the event is scheduled.
Priority priority () const
Get the event priority.
virtual BaseGlobalEvent * globalEvent ()
If this is part of a GlobalEvent, return the pointer to the Global Event.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Private Types
typedef void(BasePixelPump::* CallbackType) ()
Private Member Functions
void suspend ()
void resume ()
Private Attributes
const std::string _name
BasePixelPump & parent
const CallbackType func
bool suspended
Tick relativeTick
Additional Inherited Members
Public Types inherited from EventBase
typedef int8_t Priority
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from EventBase
static const Priority Minimum_Pri = SCHAR_MIN
Event priorities, to provide tie-breakers for events scheduled at the same cycle.
static const Priority Debug_Enable_Pri = -101
If we enable tracing on a particular cycle, do that as the very first thing so we don't miss any of the events on that cycle (even if we enter the debugger).
static const Priority Debug_Break_Pri = -100
Breakpoints should happen before anything else (except enabling trace output), so we don't miss any action when debugging.
static const Priority CPU_Switch_Pri = -31
CPU switches schedule the new CPU's tick event for the same cycle (after unscheduling the old CPU's tick event).
static const Priority Delayed_Writeback_Pri = -1
For some reason "delayed" inter-cluster writebacks are scheduled before regular writebacks (which have default priority).
static const Priority Default_Pri = 0
Default is zero for historical reasons.
static const Priority DVFS_Update_Pri = 31
DVFS update event leads to stats dump therefore given a lower priority to ensure all relevant states have been updated.
static const Priority Serialize_Pri = 32
Serailization needs to occur before tick events also, so that a serialize/unserialize is identical to an on-line CPU switch.
static const Priority CPU_Tick_Pri = 50
CPU ticks must come after other associated CPU events (such as writebacks).
static const Priority CPU_Exit_Pri = 64
If we want to exit a thread in a CPU, it comes after CPU_Tick_Pri.
static const Priority Stat_Event_Pri = 90
Statistics events (dump, reset, etc.) come after everything else, but before exit.
static const Priority Progress_Event_Pri = 95
Progress events come at the end.
static const Priority Sim_Exit_Pri = 100
If we want to exit on this cycle, it's the very last thing we do.
static const Priority Maximum_Pri = SCHAR_MAX
Maximum priority.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from EventBase
typedef unsigned short FlagsType
typedef ::Flags< FlagsType > Flags
Protected Member Functions inherited from Event
Flags getFlags () const
Accessor for flags.
bool isFlagSet (Flags _flags) const
void setFlags (Flags _flags)
Accessor for flags.
void clearFlags (Flags _flags)
void clearFlags ()
virtual void trace (const char *action)
trace event activity
void acquire ()
Memory management hooks for events that have the Managed flag set.
void release ()
Managed event removed from the event queue.
virtual void acquireImpl ()
virtual void releaseImpl ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Static Protected Attributes inherited from EventBase
static const FlagsType PublicRead = 0x003f
static const FlagsType PublicWrite = 0x001d
static const FlagsType Squashed = 0x0001
static const FlagsType Scheduled = 0x0002
static const FlagsType Managed = 0x0004
static const FlagsType AutoDelete = Managed
static const FlagsType Reserved0 = 0x0008
This used to be AutoSerialize.
static const FlagsType IsExitEvent = 0x0010
static const FlagsType IsMainQueue = 0x0020
static const FlagsType Initialized = 0x7a40
static const FlagsType InitMask = 0xffc0
Detailed Description
Callback helper class with suspend support.
Unlike a normal EventWrapper, this class suspends an event on drain() and restarts it at drainResume(). The suspend operation stores the tick relative to curTick() and then deschedules the event. The resume operation schedules the event at curTick() plus the relative tick stored when the event was suspended.
Definition at line 260 of file pixelpump.hh.
Member Typedef Documentation
CallbackType
typedef void(BasePixelPump::* BasePixelPump::PixelEvent::CallbackType) () private
Definition at line 262 of file pixelpump.hh.
Constructor & Destructor Documentation
PixelEvent()
BasePixelPump::PixelEvent::PixelEvent (const char * name, BasePixelPump * parent, CallbackType func)
Definition at line 299 of file pixelpump.cc.
References parent, and BasePixelPump::pixelEvents.
Member Function Documentation
active()
bool BasePixelPump::PixelEvent::active () const inline
Definition at line 278 of file pixelpump.hh.
drain()
DrainState BasePixelPump::PixelEvent::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 310 of file pixelpump.cc.
References Drained, Event::scheduled(), and suspend().
drainResume()
void BasePixelPump::PixelEvent::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 318 of file pixelpump.cc.
References resume(), and suspended.
name()
const std::string BasePixelPump::PixelEvent::name () const inline override virtual
Reimplemented from Event.
Definition at line 273 of file pixelpump.hh.
process()
void BasePixelPump::PixelEvent::process () inline override virtual
Implements Event.
Definition at line 274 of file pixelpump.hh.
resume()
void BasePixelPump::PixelEvent::resume () private
Definition at line 354 of file pixelpump.cc.
References curTick(), parent, relativeTick, EventManager::schedule(), Event::scheduled(), and suspended.
Referenced by drainResume().
serialize()
void BasePixelPump::PixelEvent::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 325 of file pixelpump.cc.
References relativeTick, Event::scheduled(), Event::serialize(), SERIALIZE_SCALAR, and suspended.
suspend()
void BasePixelPump::PixelEvent::suspend () private
Definition at line 343 of file pixelpump.cc.
References curTick(), EventManager::deschedule(), parent, relativeTick, Event::scheduled(), suspended, and Event::when().
Referenced by drain().
unserialize()
void BasePixelPump::PixelEvent::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 334 of file pixelpump.cc.
References relativeTick, Event::scheduled(), suspended, Event::unserialize(), and UNSERIALIZE_SCALAR.
Member Data Documentation
_name
const std::string BasePixelPump::PixelEvent::_name private
Definition at line 284 of file pixelpump.hh.
func
const CallbackType BasePixelPump::PixelEvent::func private
Definition at line 286 of file pixelpump.hh.
parent
BasePixelPump& BasePixelPump::PixelEvent::parent private
Definition at line 285 of file pixelpump.hh.
Referenced by PixelEvent(), resume(), and suspend().
relativeTick
Tick BasePixelPump::PixelEvent::relativeTick private
Definition at line 289 of file pixelpump.hh.
Referenced by resume(), serialize(), suspend(), and unserialize().
suspended
bool BasePixelPump::PixelEvent::suspended private
Definition at line 288 of file pixelpump.hh.
Referenced by drainResume(), resume(), serialize(), suspend(), and unserialize().
The documentation for this class was generated from the following files:
dev/pixelpump.hh
dev/pixelpump.cc