gem5: sc_dt::scfx_ieee_float Class Reference
sc_dt::scfx_ieee_float Class Reference
#include <scfx_ieee.hh>
Public Member Functions
scfx_ieee_float ()
scfx_ieee_float (float)
scfx_ieee_float (const scfx_ieee_float &)
scfx_ieee_float & operator= (float)
scfx_ieee_float & operator= (const scfx_ieee_float &)
operator float () const
unsigned int negative () const
void negative (unsigned int)
int exponent () const
void exponent (int)
unsigned int mantissa () const
void mantissa (unsigned int)
bool is_zero () const
bool is_subnormal () const
bool is_normal () const
bool is_inf () const
bool is_nan () const
void set_inf ()
void set_nan ()
Private Attributes
ieee_float m_if
Detailed Description
Definition at line 407 of file scfx_ieee.hh.
Constructor & Destructor Documentation
scfx_ieee_float() [1/3]
sc_dt::scfx_ieee_float::scfx_ieee_float () inline
Definition at line 441 of file scfx_ieee.hh.
References sc_dt::ieee_float::f, and m_if.
scfx_ieee_float() [2/3]
sc_dt::scfx_ieee_float::scfx_ieee_float (float f) inline
Definition at line 446 of file scfx_ieee.hh.
References ArmISA::f, sc_dt::ieee_float::f, and m_if.
scfx_ieee_float() [3/3]
sc_dt::scfx_ieee_float::scfx_ieee_float (const scfx_ieee_float & a) inline
Definition at line 451 of file scfx_ieee.hh.
Member Function Documentation
exponent() [1/2]
int sc_dt::scfx_ieee_float::exponent () const inline
Definition at line 490 of file scfx_ieee.hh.
References m_if, sc_dt::ieee_float::s, and sc_dt::SCFX_IEEE_FLOAT_BIAS.
Referenced by is_inf(), is_nan(), is_normal(), is_subnormal(), is_zero(), set_inf(), and set_nan().
exponent() [2/2]
void sc_dt::scfx_ieee_float::exponent (int a) inline
Definition at line 496 of file scfx_ieee.hh.
References ArmISA::a, m_if, sc_dt::ieee_float::s, and SCFX_MASK_.
is_inf()
bool sc_dt::scfx_ieee_float::is_inf () const inline
Definition at line 535 of file scfx_ieee.hh.
References exponent(), and mantissa().
is_nan()
bool sc_dt::scfx_ieee_float::is_nan () const inline
Definition at line 541 of file scfx_ieee.hh.
References exponent(), and mantissa().
is_normal()
bool sc_dt::scfx_ieee_float::is_normal () const inline
Definition at line 528 of file scfx_ieee.hh.
References exponent().
is_subnormal()
bool sc_dt::scfx_ieee_float::is_subnormal () const inline
Definition at line 522 of file scfx_ieee.hh.
References exponent(), and mantissa().
is_zero()
bool sc_dt::scfx_ieee_float::is_zero () const inline
Definition at line 516 of file scfx_ieee.hh.
References exponent(), and mantissa().
mantissa() [1/2]
unsigned int sc_dt::scfx_ieee_float::mantissa () const inline
Definition at line 503 of file scfx_ieee.hh.
References m_if, and sc_dt::ieee_float::s.
Referenced by is_inf(), is_nan(), is_subnormal(), is_zero(), set_inf(), and set_nan().
mantissa() [2/2]
void sc_dt::scfx_ieee_float::mantissa (unsigned int a) inline
Definition at line 509 of file scfx_ieee.hh.
References m_if, sc_dt::ieee_float::s, and SCFX_MASK_.
negative() [1/2]
unsigned int sc_dt::scfx_ieee_float::negative () const inline
Definition at line 478 of file scfx_ieee.hh.
References m_if, and sc_dt::ieee_float::s.
negative() [2/2]
void sc_dt::scfx_ieee_float::negative (unsigned int a) inline
Definition at line 484 of file scfx_ieee.hh.
References m_if, sc_dt::ieee_float::s, and SCFX_MASK_.
operator float()
sc_dt::scfx_ieee_float::operator float () const inline
Definition at line 472 of file scfx_ieee.hh.
References sc_dt::ieee_float::f, and m_if.
operator=() [1/2]
scfx_ieee_float & sc_dt::scfx_ieee_float::operator= (float f) inline
Definition at line 459 of file scfx_ieee.hh.
References ArmISA::f, sc_dt::ieee_float::f, and m_if.
operator=() [2/2]
scfx_ieee_float & sc_dt::scfx_ieee_float::operator= (const scfx_ieee_float & a) inline
Definition at line 466 of file scfx_ieee.hh.
References sc_dt::ieee_float::f, and m_if.
set_inf()
void sc_dt::scfx_ieee_float::set_inf () inline
Definition at line 547 of file scfx_ieee.hh.
References exponent(), and mantissa().
set_nan()
void sc_dt::scfx_ieee_float::set_nan () inline
Definition at line 554 of file scfx_ieee.hh.
References exponent(), and mantissa().
Member Data Documentation
m_if
ieee_float sc_dt::scfx_ieee_float::m_if private
Definition at line 409 of file scfx_ieee.hh.
Referenced by exponent(), mantissa(), negative(), operator float(), operator=(), and scfx_ieee_float().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/scfx_ieee.hh