gem5: sc_dt::sc_uint_subref_r Class Reference
sc_dt::sc_uint_subref_r Class Reference
#include <sc_uint_base.hh>
Public Member Functions
sc_uint_subref_r (const sc_uint_subref_r &init)
virtual ~sc_uint_subref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_uint_subref_r ()
void initialize (const sc_uint_base *obj_p, int left_i, int right_i)
Protected Attributes
int m_left
sc_uint_base * m_obj_p
int m_right
Private Member Functions
sc_uint_subref_r & operator= (const sc_uint_subref_r &)
Friends
class sc_uint_base
class sc_uint_subref
Detailed Description
Definition at line 275 of file sc_uint_base.hh.
Constructor & Destructor Documentation
sc_uint_subref_r() [1/2]
sc_dt::sc_uint_subref_r::sc_uint_subref_r (const sc_uint_subref_r & init) inline
Definition at line 282 of file sc_uint_base.hh.
sc_uint_subref_r() [2/2]
sc_dt::sc_uint_subref_r::sc_uint_subref_r () inline protected
Definition at line 288 of file sc_uint_base.hh.
~sc_uint_subref_r()
virtual sc_dt::sc_uint_subref_r::~sc_uint_subref_r () inline virtual
Definition at line 301 of file sc_uint_base.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_uint_subref_r::and_reduce () const inline
Definition at line 984 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::and_reduce().
Referenced by sc_dt::and_reduce().
concat_get_ctrl()
bool sc_dt::sc_uint_subref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 163 of file sc_uint_base.cc.
References BITS_PER_DIGIT, ArmISA::mask, and sc_dt::UINT_ZERO.
concat_get_data()
bool sc_dt::sc_uint_subref_r::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 185 of file sc_uint_base.cc.
References BITS_PER_DIGIT, DIGIT_MASK, ArmISA::mask, sc_dt::mask_int, sc_dt::UINT_ZERO, and X86ISA::val.
concat_get_uint64()
virtual uint64 sc_dt::sc_uint_subref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 317 of file sc_uint_base.hh.
References sc_dt::and_reduce().
concat_length()
virtual int sc_dt::sc_uint_subref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 308 of file sc_uint_base.hh.
References length.
initialize()
void sc_dt::sc_uint_subref_r::initialize (const sc_uint_base * obj_p, int left_i, int right_i) inline protected
Definition at line 292 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_base::operator()(), and sc_dt::sc_uint_base::range().
length()
int sc_dt::sc_uint_subref_r::length () const inline
Definition at line 304 of file sc_uint_base.hh.
nand_reduce()
bool sc_dt::sc_uint_subref_r::nand_reduce () const inline
Definition at line 324 of file sc_uint_base.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
Referenced by sc_dt::nand_reduce().
nor_reduce()
bool sc_dt::sc_uint_subref_r::nor_reduce () const inline
Definition at line 326 of file sc_uint_base.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
Referenced by sc_dt::nor_reduce().
operator uint_type()
sc_dt::sc_uint_subref_r::operator uint_type () const inline
Definition at line 974 of file sc_uint_base.hh.
References SC_INTWIDTH, sc_dt::UINT_ZERO, and X86ISA::val.
operator=()
sc_uint_subref_r& sc_dt::sc_uint_subref_r::operator= (const sc_uint_subref_r &) private
or_reduce()
bool sc_dt::sc_uint_subref_r::or_reduce () const inline
Definition at line 990 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::or_reduce().
Referenced by sc_dt::or_reduce().
print()
void sc_dt::sc_uint_subref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 350 of file sc_uint_base.hh.
References X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
to_double()
double sc_dt::sc_uint_subref_r::to_double () const inline
Definition at line 1040 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_double().
to_int()
int sc_dt::sc_uint_subref_r::to_int () const inline
Definition at line 1004 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_int().
to_int64()
int64 sc_dt::sc_uint_subref_r::to_int64 () const inline
Definition at line 1028 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_int64().
to_long()
long sc_dt::sc_uint_subref_r::to_long () const inline
Definition at line 1016 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_long().
to_string() [1/2]
const std::string sc_dt::sc_uint_subref_r::to_string (sc_numrep numrep = SC_DEC) const inline
Definition at line 1048 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_string().
to_string() [2/2]
const std::string sc_dt::sc_uint_subref_r::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 1055 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_string().
to_uint()
unsigned int sc_dt::sc_uint_subref_r::to_uint () const inline
Definition at line 1010 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_uint().
to_uint64()
uint64 sc_dt::sc_uint_subref_r::to_uint64 () const inline
Definition at line 1034 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_uint64().
Referenced by sc_dt::sc_int_base::sc_int_base().
to_ulong()
unsigned long sc_dt::sc_uint_subref_r::to_ulong () const inline
Definition at line 1022 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::to_ulong().
value()
uint_type sc_dt::sc_uint_subref_r::value () const inline
Definition at line 334 of file sc_uint_base.hh.
References sc_dt::SC_DEC, and sc_dt::to_string().
xnor_reduce()
bool sc_dt::sc_uint_subref_r::xnor_reduce () const inline
Definition at line 328 of file sc_uint_base.hh.
References sc_dt::xor_reduce().
Referenced by sc_dt::xnor_reduce().
xor_reduce()
bool sc_dt::sc_uint_subref_r::xor_reduce () const inline
Definition at line 996 of file sc_uint_base.hh.
References ArmISA::a, and sc_dt::sc_uint_base::xor_reduce().
Referenced by sc_dt::xor_reduce().
Friends And Related Function Documentation
sc_uint_base
friend class sc_uint_base friend
Definition at line 277 of file sc_uint_base.hh.
sc_uint_subref
friend class sc_uint_subref friend
Definition at line 278 of file sc_uint_base.hh.
Member Data Documentation
m_left
int sc_dt::sc_uint_subref_r::m_left protected
Definition at line 356 of file sc_uint_base.hh.
m_obj_p
sc_uint_base* sc_dt::sc_uint_subref_r::m_obj_p protected
Definition at line 357 of file sc_uint_base.hh.
m_right
int sc_dt::sc_uint_subref_r::m_right protected
Definition at line 358 of file sc_uint_base.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_uint_base.hh
systemc/dt/int/sc_uint_base.cc