gem5: ChannelAddrRange Class Reference
ChannelAddrRange Class Reference
The ChanneelAddrRange class describes a contiguous range of addresses in a contiguous channel-local address space.
#include <channel_addr.hh>
Public Member Functions
constexpr ChannelAddrRange ()
constexpr ChannelAddrRange (ChannelAddr start, ChannelAddr end)
ChannelAddrRange (AddrRange ch_range, Addr start, Addr end)
ChannelAddrRange (AddrRange ch_range, AddrRange range)
constexpr ChannelAddrRange (const ChannelAddrRange &)=default
constexpr ChannelAddr size () const
constexpr bool valid () const
constexpr ChannelAddr start () const
constexpr ChannelAddr end () const
constexpr bool contains (ChannelAddr a) const
Protected Attributes
ChannelAddr _start
ChannelAddr _end
Detailed Description
The ChanneelAddrRange class describes a contiguous range of addresses in a contiguous channel-local address space.
Definition at line 145 of file channel_addr.hh.
Constructor & Destructor Documentation
ChannelAddrRange() [1/5]
constexpr ChannelAddrRange::ChannelAddrRange () inline
Definition at line 148 of file channel_addr.hh.
ChannelAddrRange() [2/5]
constexpr ChannelAddrRange::ChannelAddrRange (ChannelAddr start, ChannelAddr end) inline
Definition at line 151 of file channel_addr.hh.
ChannelAddrRange() [3/5]
ChannelAddrRange::ChannelAddrRange (AddrRange ch_range, Addr start, Addr end)
Definition at line 44 of file channel_addr.cc.
References panic_if, and AddrRange::valid().
ChannelAddrRange() [4/5]
ChannelAddrRange::ChannelAddrRange (AddrRange ch_range, AddrRange range)
Definition at line 51 of file channel_addr.cc.
References AddrRange::interleaved(), and panic_if.
ChannelAddrRange() [5/5]
constexpr ChannelAddrRange::ChannelAddrRange (const ChannelAddrRange &) default
Member Function Documentation
contains()
constexpr bool ChannelAddrRange::contains (ChannelAddr a) const inline
Definition at line 166 of file channel_addr.hh.
Referenced by TEST().
end()
constexpr ChannelAddr ChannelAddrRange::end () const inline
Definition at line 164 of file channel_addr.hh.
Referenced by TEST().
size()
constexpr ChannelAddr ChannelAddrRange::size () const inline
Definition at line 159 of file channel_addr.hh.
Referenced by TEST().
start()
constexpr ChannelAddr ChannelAddrRange::start () const inline
Definition at line 163 of file channel_addr.hh.
Referenced by TEST().
valid()
constexpr bool ChannelAddrRange::valid () const inline
Definition at line 161 of file channel_addr.hh.
Referenced by TEST().
Member Data Documentation
_end
ChannelAddr ChannelAddrRange::_end protected
Definition at line 172 of file channel_addr.hh.
_start
ChannelAddr ChannelAddrRange::_start protected
Definition at line 171 of file channel_addr.hh.
The documentation for this class was generated from the following files:
base/channel_addr.hh
base/channel_addr.cc