gem5: MemCheckerMonitor Class Reference
MemCheckerMonitor Class Reference
Implements a MemChecker monitor, to be inserted between two ports.
#include <mem_checker_monitor.hh>
Classes
struct MemCheckerMonitorSenderState
class MonitorMasterPort
This is the master port of the communication monitor.
class MonitorSlavePort
This is the slave port of the communication monitor.
Public Types
typedef MemCheckerMonitorParams Params
Parameters of memchecker monitor.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
MemCheckerMonitor (Params *params)
Constructor based on the Python params.
~MemCheckerMonitor ()
Destructor.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
void recvFunctional (PacketPtr pkt)
void recvFunctionalSnoop (PacketPtr pkt)
Tick recvAtomic (PacketPtr pkt)
Tick recvAtomicSnoop (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
bool recvTimingResp (PacketPtr pkt)
void recvTimingSnoopReq (PacketPtr pkt)
bool recvTimingSnoopResp (PacketPtr pkt)
AddrRangeList getAddrRanges () const
bool isSnooping () const
void recvReqRetry ()
void recvRespRetry ()
void recvRangeChange ()
Private Attributes
MonitorMasterPort masterPort
Instance of master port, facing the memory side.
MonitorSlavePort slavePort
Instance of slave port, i.e.
bool warnOnly
MemChecker * memchecker
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Implements a MemChecker monitor, to be inserted between two ports.
Definition at line 54 of file mem_checker_monitor.hh.
Member Typedef Documentation
Params
typedef MemCheckerMonitorParams MemCheckerMonitor::Params
Parameters of memchecker monitor.
Definition at line 59 of file mem_checker_monitor.hh.
Constructor & Destructor Documentation
MemCheckerMonitor()
MemCheckerMonitor::MemCheckerMonitor (Params * params)
Constructor based on the Python params.
Parameters
params Python parameters
Definition at line 51 of file mem_checker_monitor.cc.
Referenced by params(), and ~MemCheckerMonitor().
~MemCheckerMonitor()
MemCheckerMonitor::~MemCheckerMonitor ()
Destructor.
Definition at line 59 of file mem_checker_monitor.cc.
References MemCheckerMonitor().
Referenced by params().
Member Function Documentation
getAddrRanges()
AddrRangeList MemCheckerMonitor::getAddrRanges () const private
Definition at line 342 of file mem_checker_monitor.cc.
References MasterPort::getAddrRanges(), and masterPort.
getPort()
Port & MemCheckerMonitor::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 77 of file mem_checker_monitor.cc.
References SimObject::getPort(), masterPort, and slavePort.
Referenced by params().
init()
void MemCheckerMonitor::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 69 of file mem_checker_monitor.cc.
References fatal, Port::isConnected(), masterPort, and slavePort.
Referenced by params().
isSnooping()
bool MemCheckerMonitor::isSnooping () const private
Definition at line 335 of file mem_checker_monitor.cc.
References SlavePort::isSnooping(), and slavePort.
params()
const Params* MemCheckerMonitor::params () const inline
Definition at line 60 of file mem_checker_monitor.hh.
References SimObject::_params, getPort(), init(), InvalidPortID, MemCheckerMonitor(), and ~MemCheckerMonitor().
recvAtomic()
Tick MemCheckerMonitor::recvAtomic (PacketPtr pkt) private
Definition at line 123 of file mem_checker_monitor.cc.
References panic.
recvAtomicSnoop()
Tick MemCheckerMonitor::recvAtomicSnoop (PacketPtr pkt) private
Definition at line 129 of file mem_checker_monitor.cc.
References panic.
recvFunctional()
void MemCheckerMonitor::recvFunctional (PacketPtr pkt) private
Definition at line 89 of file mem_checker_monitor.cc.
References addr, DPRINTF, Packet::getAddr(), Packet::getSize(), masterPort, memchecker, MemChecker::reset(), and MasterPort::sendFunctional().
recvFunctionalSnoop()
void MemCheckerMonitor::recvFunctionalSnoop (PacketPtr pkt) private
Definition at line 107 of file mem_checker_monitor.cc.
References addr, DPRINTF, Packet::getAddr(), Packet::getSize(), memchecker, MemChecker::reset(), SlavePort::sendFunctionalSnoop(), and slavePort.
recvRangeChange()
void MemCheckerMonitor::recvRangeChange () private
Definition at line 361 of file mem_checker_monitor.cc.
References SlavePort::sendRangeChange(), and slavePort.
recvReqRetry()
void MemCheckerMonitor::recvReqRetry () private
Definition at line 349 of file mem_checker_monitor.cc.
References SlavePort::sendRetryReq(), and slavePort.
recvRespRetry()
void MemCheckerMonitor::recvRespRetry () private
Definition at line 355 of file mem_checker_monitor.cc.
References masterPort, and MasterPort::sendRetryResp().
recvTimingReq()
bool MemCheckerMonitor::recvTimingReq (PacketPtr pkt) private
Definition at line 135 of file mem_checker_monitor.cc.
References addr, Packet::cacheResponding(), curTick(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::isRead(), Packet::isRequest(), Packet::isWrite(), masterPort, memchecker, Packet::needsResponse(), Packet::popSenderState(), Packet::pushSenderState(), Packet::req, MasterPort::sendTimingReq(), MemCheckerMonitor::MemCheckerMonitorSenderState::serial, MemChecker::startRead(), MemChecker::startWrite(), and Packet::writeData().
recvTimingResp()
bool MemCheckerMonitor::recvTimingResp (PacketPtr pkt) private
Definition at line 227 of file mem_checker_monitor.cc.
References MemChecker::abortWrite(), addr, MemChecker::completeRead(), MemChecker::completeWrite(), curTick(), DPRINTF, Packet::getAddr(), MemChecker::getErrorMessage(), Packet::getSize(), Packet::isLLSC(), Packet::isRead(), Packet::isResponse(), Packet::isWrite(), memchecker, SimObject::name(), panic_if, Packet::SenderState::predecessor, Packet::req, Packet::senderState, SlavePort::sendTimingResp(), MemCheckerMonitor::MemCheckerMonitorSenderState::serial, slavePort, warn, warnOnly, and Packet::writeData().
recvTimingSnoopReq()
void MemCheckerMonitor::recvTimingSnoopReq (PacketPtr pkt) private
Definition at line 323 of file mem_checker_monitor.cc.
References SlavePort::sendTimingSnoopReq(), and slavePort.
recvTimingSnoopResp()
bool MemCheckerMonitor::recvTimingSnoopResp (PacketPtr pkt) private
Definition at line 329 of file mem_checker_monitor.cc.
References masterPort, and MasterPort::sendTimingSnoopResp().
Member Data Documentation
masterPort
MonitorMasterPort MemCheckerMonitor::masterPort private
Instance of master port, facing the memory side.
Definition at line 148 of file mem_checker_monitor.hh.
Referenced by getAddrRanges(), getPort(), init(), recvFunctional(), recvRespRetry(), recvTimingReq(), and recvTimingSnoopResp().
memchecker
MemChecker* MemCheckerMonitor::memchecker private
Definition at line 234 of file mem_checker_monitor.hh.
Referenced by recvFunctional(), recvFunctionalSnoop(), recvTimingReq(), and recvTimingResp().
slavePort
MonitorSlavePort MemCheckerMonitor::slavePort private
Instance of slave port, i.e.
on the CPU side
Definition at line 204 of file mem_checker_monitor.hh.
Referenced by getPort(), init(), isSnooping(), recvFunctionalSnoop(), recvRangeChange(), recvReqRetry(), recvTimingResp(), and recvTimingSnoopReq().
warnOnly
bool MemCheckerMonitor::warnOnly private
Definition at line 232 of file mem_checker_monitor.hh.
Referenced by recvTimingResp().
The documentation for this class was generated from the following files:
mem/mem_checker_monitor.hh
mem/mem_checker_monitor.cc