gem5: PosixKvmTimer Class Reference
PosixKvmTimer Class Reference
Timer based on standard POSIX timers.
#include <timer.hh>
Public Member Functions
PosixKvmTimer (int signo, clockid_t clockID, float hostFactor, Tick hostFreq)
~PosixKvmTimer ()
void arm (Tick ticks)
Arm the timer so that it fires after a certain number of ticks.
void disarm ()
Disarm the timer.
Public Member Functions inherited from BaseKvmTimer
BaseKvmTimer (int signo, float hostFactor, Tick hostFreq)
Setup basic timer functionality shared by all timer implementations.
virtual ~BaseKvmTimer ()
Tick resolution ()
Determine the resolution of the timer in ticks.
Tick ticksFromHostCycles (uint64_t cycles)
Convert cycles executed on the host into Ticks executed in the simulator.
Tick ticksFromHostNs (uint64_t ns)
Convert nanoseconds executed on the host into Ticks executed in the simulator.
Protected Member Functions
Tick calcResolution ()
Calculate the timer resolution, used by resolution() which caches the result.
Protected Member Functions inherited from BaseKvmTimer
uint64_t hostNs (Tick ticks)
Convert a time in simulator ticks to host nanoseconds.
uint64_t hostCycles (Tick ticks)
Convert a time in simulator ticks to host cycles.
Private Attributes
clockid_t clockID
timer_t timer
Additional Inherited Members
Protected Attributes inherited from BaseKvmTimer
int signo
Signal to deliver when the timer times out.
Detailed Description
Timer based on standard POSIX timers.
The POSIX timer API supports several different clock with different characteristics.
Note
It might be tempting to use CLOCK_(THREAD|PROCESS)_CPUTIME_ID, however, this clock usually has much lower resolution than the real-time clocks.
Definition at line 183 of file timer.hh.
Constructor & Destructor Documentation
PosixKvmTimer()
PosixKvmTimer::PosixKvmTimer (int signo, clockid_t clockID, float hostFactor, Tick hostFreq)
Parameters
signo Signal to deliver
clockID ID of the clock to use
hostFactor Performance scaling factor
hostFreq Clock frequency of the host
Definition at line 78 of file timer.cc.
References panic, BaseKvmTimer::signo, sysGettid(), and timer.
~PosixKvmTimer()
PosixKvmTimer::~PosixKvmTimer ()
Definition at line 96 of file timer.cc.
References timer.
Member Function Documentation
arm()
void PosixKvmTimer::arm (Tick ticks) virtual
Arm the timer so that it fires after a certain number of ticks.
Note
A timer implementation is free to convert between simulation ticks and virtualized time using any method it chooses. The accuracy of the timer therefore depends on what it measures, an accurate timer implementation should measure the number of cycles or instructions executed in the guest. If such counters are unavailable, it may fallback to wall clock time.
Parameters
ticks Number of ticks until the timer fires
Implements BaseKvmTimer.
Definition at line 102 of file timer.cc.
References DPRINTF, BaseKvmTimer::hostNs(), panic, timer, and ULL.
calcResolution()
Tick PosixKvmTimer::calcResolution () protected virtual
Calculate the timer resolution, used by resolution() which caches the result.
Returns
Minimum number of ticks the timer can resolve
Implements BaseKvmTimer.
Definition at line 134 of file timer.cc.
References clockID, MIN_HOST_CYCLES, panic, BaseKvmTimer::resolution(), BaseKvmTimer::ticksFromHostCycles(), BaseKvmTimer::ticksFromHostNs(), and ULL.
disarm()
void PosixKvmTimer::disarm () virtual
Disarm the timer.
When this method has returned, the timer may no longer deliver signals upon timeout.
Implements BaseKvmTimer.
Definition at line 122 of file timer.cc.
References DPRINTF, panic, and timer.
Member Data Documentation
clockID
clockid_t PosixKvmTimer::clockID private
Definition at line 203 of file timer.hh.
Referenced by calcResolution().
timer
timer_t PosixKvmTimer::timer private
Definition at line 204 of file timer.hh.
Referenced by arm(), disarm(), PosixKvmTimer(), and ~PosixKvmTimer().
The documentation for this class was generated from the following files:
cpu/kvm/timer.hh
cpu/kvm/timer.cc