gem5: PortProxy Class Reference
PortProxy Class Reference
This object is a proxy for a port or other object which implements the functional response protocol, to be used for debug accesses.
#include <port_proxy.hh>
Public Types
typedef std::function< void(PacketPtr pkt)> SendFunctionalFunc
Public Member Functions
PortProxy (SendFunctionalFunc func, unsigned int cacheLineSize)
PortProxy (const MasterPort &port, unsigned int cacheLineSize)
virtual ~PortProxy ()
void readBlobPhys (Addr addr, Request::Flags flags, void *p, int size) const
Fixed functionality for use in base classes.
void writeBlobPhys (Addr addr, Request::Flags flags, const void *p, int size) const
Write size bytes from p to physical address.
void memsetBlobPhys (Addr addr, Request::Flags flags, uint8_t v, int size) const
Fill size bytes starting at physical addr with byte value val.
virtual bool tryReadBlob (Addr addr, void *p, int size) const
Methods to override in base classes.
virtual bool tryWriteBlob (Addr addr, const void *p, int size) const
Write size bytes from p to address.
virtual bool tryMemsetBlob (Addr addr, uint8_t val, int size) const
Fill size bytes starting at addr with byte value val.
void readBlob (Addr addr, void *p, int size) const
Higher level interfaces based on the above.
void writeBlob (Addr addr, const void *p, int size) const
Same as tryWriteBlob, but insists on success.
void memsetBlob (Addr addr, uint8_t v, int size) const
Same as tryMemsetBlob, but insists on success.
template<typename T >
T read (Addr address) const
Read sizeof(T) bytes from address and return as object T.
template<typename T >
void write (Addr address, const T &data) const
Write object T to address.
template<typename T >
T read (Addr address, ByteOrder guest_byte_order) const
Read sizeof(T) bytes from address and return as object T.
template<typename T >
void write (Addr address, T data, ByteOrder guest_byte_order) const
Write object T to address.
bool tryWriteString (Addr addr, const char *str) const
Write the string str into guest memory at address addr.
void writeString (Addr addr, const char *str) const
Same as tryWriteString, but insists on success.
bool tryReadString (std::string &str, Addr addr) const
Reads the string at guest address addr into the std::string str.
void readString (std::string &str, Addr addr) const
Same as tryReadString, but insists on success.
bool tryReadString (char *str, Addr addr, size_t maxlen) const
Reads the string at guest address addr into the char * str, reading up to maxlen characters.
void readString (char *str, Addr addr, size_t maxlen) const
Same as tryReadString, but insists on success.
Private Member Functions
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
Private Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Attributes
SendFunctionalFunc sendFunctional
const unsigned int _cacheLineSize
Granularity of any transactions issued through this proxy.
Detailed Description
This object is a proxy for a port or other object which implements the functional response protocol, to be used for debug accesses.
This proxy object is used when non structural entities (e.g. thread contexts, object file loaders) need access to the memory system. It calls the corresponding functions on the underlying protocol, and provides templatized convenience access functions.
The addresses are interpreted as physical addresses.
See also
SETranslatingProxy
FSTranslatingProxy
Definition at line 82 of file port_proxy.hh.
Member Typedef Documentation
SendFunctionalFunc
typedef std::function<void(PacketPtr pkt)> PortProxy::SendFunctionalFunc
Definition at line 85 of file port_proxy.hh.
Constructor & Destructor Documentation
PortProxy() [1/2]
PortProxy::PortProxy (SendFunctionalFunc func, unsigned int cacheLineSize) inline
Definition at line 102 of file port_proxy.hh.
PortProxy() [2/2]
PortProxy::PortProxy (const MasterPort & port, unsigned int cacheLineSize) inline
Definition at line 105 of file port_proxy.hh.
References _cacheLineSize, and MasterPort::sendFunctional().
~PortProxy()
virtual PortProxy::~PortProxy () inline virtual
Definition at line 110 of file port_proxy.hh.
References addr, memsetBlobPhys(), MipsISA::p, readBlobPhys(), ArmISA::v, and writeBlobPhys().
Member Function Documentation
memsetBlob()
void PortProxy::memsetBlob (Addr addr, uint8_t v, int size) const inline
Same as tryMemsetBlob, but insists on success.
Definition at line 199 of file port_proxy.hh.
References data, fatal, read(), tryMemsetBlob(), tryWriteString(), and write().
Referenced by brkFunc(), Gicv3Its::moveAllPendingState(), and MemoryImage::writeSegment().
memsetBlobPhys()
void PortProxy::memsetBlobPhys (Addr addr, Request::Flags flags, uint8_t v, int size) const
Fill size bytes starting at physical addr with byte value val.
Definition at line 79 of file port_proxy.cc.
References writeBlobPhys().
Referenced by SecurePortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryMemsetBlob(), FSTranslatingPortProxy::tryMemsetBlob(), tryMemsetBlob(), and ~PortProxy().
read() [1/2]
template<typename T > T PortProxy::read (Addr address) const
Read sizeof(T) bytes from address and return as object T.
Definition at line 284 of file port_proxy.hh.
References data, and readBlob().
Referenced by ArmSemihosting::call32(), ArmSemihosting::call64(), Linux::ThreadInfo::curTaskInfo(), Linux::ThreadInfo::curTaskMmFromTaskStruct(), Linux::ThreadInfo::curTaskPIDFromTaskStruct(), Linux::ThreadInfo::curTaskStartFromTaskStruct(), Linux::ThreadInfo::curTaskTGIDFromTaskStruct(), MipsISA::StackTrace::decodePrologue(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), dumpDmesgEntry(), AlphaSystem::fixFuncEventAddr(), Linux::ThreadInfo::get_data(), AlphaISA::getArgument(), SparcISA::getArgument(), ArmISA::getArgument(), AlphaISA::kernel_pte_lookup(), memsetBlob(), MipsISA::ProcessInfo::pid(), X86ISA::ProcessInfo::pid(), ArmISA::ProcessInfo::pid(), AlphaISA::ProcessInfo::pid(), AlphaISA::ProcessInfo::ProcessInfo(), X86ISA::LongModePTE::read(), ArmSemihosting::readString(), ArmISA::readSymbol(), X86ISA::readSymbol(), MipsISA::ProcessInfo::task(), X86ISA::ProcessInfo::task(), ArmISA::ProcessInfo::task(), AlphaISA::ProcessInfo::task(), and SparcISA::vtophys().
read() [2/2]
template<typename T > T PortProxy::read (Addr address, ByteOrder guest_byte_order) const
Read sizeof(T) bytes from address and return as object T.
Performs endianness conversion from the selected guest to host order.
Definition at line 300 of file port_proxy.hh.
References data, gtoh(), and readBlob().
readBlob()
void PortProxy::readBlob (Addr addr, void * p, int size) const inline
Higher level interfaces based on the above.
Same as tryReadBlob, but insists on success.
Definition at line 179 of file port_proxy.hh.
References fatal, and tryReadBlob().
Referenced by BaseBufferArg::copyIn(), Linux::ThreadInfo::curThreadInfo(), TsunamiPChip::dmaAddr(), dumpDmesgEntry(), X86ISA::m5PageFault(), Gicv3Its::moveAllPendingState(), Arguments::operator T*(), VirtDescriptor::read(), read(), BaseRemoteGDB::read(), Gicv3Redistributor::readEntryLPI(), Trace::TarmacParserRecord::readMemNoEffect(), ArmSemihosting::readString(), readvFunc(), VPtr< T >::refresh(), Process::replicatePage(), DmaReadFifo::resumeFillFunctional(), VirtDescriptor::update(), Gicv3Redistributor::update(), PseudoInst::writefile(), and writevFunc().
readBlobPhys()
void PortProxy::readBlobPhys (Addr addr, Request::Flags flags, void * p, int size) const
Fixed functionality for use in base classes.
Read size bytes memory at physical address and store in p.
Definition at line 45 of file port_proxy.cc.
References _cacheLineSize, ChunkGenerator::done(), Request::funcMasterId, MipsISA::p, MemCmd::ReadReq, and sendFunctional.
Referenced by SecurePortProxy::tryReadBlob(), SETranslatingPortProxy::tryReadBlob(), FSTranslatingPortProxy::tryReadBlob(), tryReadBlob(), and ~PortProxy().
readString() [1/2]
void PortProxy::readString (std::string & str, Addr addr) const inline
Same as tryReadString, but insists on success.
Definition at line 257 of file port_proxy.hh.
References fatal, and tryReadString().
Referenced by PseudoInst::addsymbol(), RiscvProcess::argsInit(), Linux::ThreadInfo::curTaskNameFromTaskStruct(), MipsISA::ProcessInfo::name(), X86ISA::ProcessInfo::name(), AlphaISA::ProcessInfo::name(), ArmISA::ProcessInfo::name(), Arguments::operator char *(), AnnotateDumpCallback::process(), and PseudoInst::writefile().
readString() [2/2]
void PortProxy::readString (char * str, Addr addr, size_t maxlen) const inline
Same as tryReadString, but insists on success.
Definition at line 274 of file port_proxy.hh.
References fatal, and tryReadString().
recvFunctionalSnoop()
void PortProxy::recvFunctionalSnoop (PacketPtr pkt) inline override private virtual
Receive a functional snoop request packet from the peer.
Implements FunctionalRequestProtocol.
Definition at line 94 of file port_proxy.hh.
References panic.
tryMemsetBlob()
virtual bool PortProxy::tryMemsetBlob (Addr addr, uint8_t val, int size) const inline virtual
Fill size bytes starting at addr with byte value val.
Returns true on success and false on failure.
Reimplemented in FSTranslatingPortProxy, SETranslatingPortProxy, and SecurePortProxy.
Definition at line 165 of file port_proxy.hh.
References memsetBlobPhys().
Referenced by memsetBlob().
tryReadBlob()
virtual bool PortProxy::tryReadBlob (Addr addr, void * p, int size) const inline virtual
Methods to override in base classes.
Read size bytes memory at address and store in p. Returns true on success and false on failure.
Reimplemented in FSTranslatingPortProxy, SETranslatingPortProxy, and SecurePortProxy.
Definition at line 143 of file port_proxy.hh.
References readBlobPhys().
Referenced by readBlob(), and tryReadString().
tryReadString() [1/2]
bool PortProxy::tryReadString (std::string & str, Addr addr) const
Reads the string at guest address addr into the std::string str.
Returns true on success and false on failure.
Definition at line 102 of file port_proxy.cc.
References ArmISA::c, and tryReadBlob().
Referenced by accessFunc(), chdirFunc(), chmodFunc(), chownFunc(), execveFunc(), fstatat64Func(), lstat64Func(), lstatFunc(), mkdirFunc(), mknodFunc(), openImpl(), readlinkFunc(), readString(), renameatFunc(), renameFunc(), rmdirFunc(), stat64Func(), statfsFunc(), statFunc(), truncate64Func(), truncateFunc(), unlinkHelper(), utimesFunc(), and writeString().
tryReadString() [2/2]
bool PortProxy::tryReadString (char * str, Addr addr, size_t maxlen) const
Reads the string at guest address addr into the char * str, reading up to maxlen characters.
The last character read is always a nul terminator. Returns true on success and false on failure.
Definition at line 115 of file port_proxy.cc.
References tryReadBlob().
tryWriteBlob()
virtual bool PortProxy::tryWriteBlob (Addr addr, const void * p, int size) const inline virtual
Write size bytes from p to address.
Returns true on success and false on failure.
Reimplemented in FSTranslatingPortProxy, SETranslatingPortProxy, and SecurePortProxy.
Definition at line 154 of file port_proxy.hh.
References writeBlobPhys().
Referenced by Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), tryWriteString(), and writeBlob().
tryWriteString()
bool PortProxy::tryWriteString (Addr addr, const char * str) const
Write the string str into guest memory at address addr.
Returns true on success and false on failure.
Definition at line 92 of file port_proxy.cc.
References tryWriteBlob().
Referenced by memsetBlob(), and writeString().
write() [1/2]
template<typename T > void PortProxy::write (Addr address, const T & data) const
Write object T to address.
Writes sizeof(T) bytes.
Definition at line 293 of file port_proxy.hh.
References writeBlob().
Referenced by archPrctlFunc(), AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), FreebsdAlphaSystem::doCalibrateClocks(), AlphaSystem::initState(), LinuxAlphaSystem::initState(), X86ISA::I386Process::initState(), memsetBlob(), ArmSemihosting::readString(), ArmSemihosting::semiExit(), AlphaSystem::setAlphaAccess(), LinuxAlphaSystem::setDelayLoop(), and X86ISA::LongModePTE::write().
write() [2/2]
template<typename T > void PortProxy::write (Addr address, T data, ByteOrder guest_byte_order) const
Write object T to address.
Writes sizeof(T) bytes. Performs endianness conversion from host to the selected guest order.
Definition at line 309 of file port_proxy.hh.
References htog(), and writeBlob().
writeBlob()
void PortProxy::writeBlob (Addr addr, const void * p, int size) const inline
Same as tryWriteBlob, but insists on success.
Definition at line 189 of file port_proxy.hh.
References fatal, and tryWriteBlob().
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), Sparc32Process::argsInit(), Sparc64Process::argsInit(), BaseBufferArg::copyOut(), copyStringArray(), AlphaSystem::initState(), LinuxX86System::initState(), ArmLinuxProcess32::initState(), X86System::initState(), LinuxArmSystem::initState(), X86ISA::X86_64Process::initState(), LinuxAlphaSystem::initState(), X86ISA::I386Process::initState(), mmapImpl(), Gicv3Its::moveAllPendingState(), SimpleDisk::read(), PseudoInst::readfile(), ArmSemihosting::readString(), readvFunc(), Process::replicatePage(), setTLSFunc32(), timeFunc(), VirtDescriptor::write(), write(), BaseRemoteGDB::write(), Gicv3Redistributor::writeEntryLPI(), X86ISA::SMBios::SMBiosStructure::writeOut(), X86ISA::IntelMP::FloatingPointer::writeOut(), X86ISA::IntelMP::BaseConfigEntry::writeOut(), X86ISA::IntelMP::ExtConfigEntry::writeOut(), X86ISA::SMBios::BiosInformation::writeOut(), X86ISA::IntelMP::ConfigTable::writeOut(), X86ISA::IntelMP::Processor::writeOut(), X86ISA::SMBios::SMBiosTable::writeOut(), X86ISA::IntelMP::BusHierarchy::writeOut(), writeOutField(), writeOutString(), X86ISA::SMBios::SMBiosStructure::writeOutStrings(), MemoryImage::writeSegment(), X86ISA::E820Table::writeTo(), and writeVal().
writeBlobPhys()
void PortProxy::writeBlobPhys (Addr addr, Request::Flags flags, const void * p, int size) const
Write size bytes from p to physical address.
Definition at line 62 of file port_proxy.cc.
References _cacheLineSize, ChunkGenerator::done(), Request::funcMasterId, MipsISA::p, sendFunctional, and MemCmd::WriteReq.
Referenced by memsetBlobPhys(), SecurePortProxy::tryWriteBlob(), SETranslatingPortProxy::tryWriteBlob(), FSTranslatingPortProxy::tryWriteBlob(), tryWriteBlob(), and ~PortProxy().
writeString()
void PortProxy::writeString (Addr addr, const char * str) const inline
Same as tryWriteString, but insists on success.
Definition at line 241 of file port_proxy.hh.
References fatal, tryReadString(), and tryWriteString().
Referenced by RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and copyStringArray().
Member Data Documentation
_cacheLineSize
const unsigned int PortProxy::_cacheLineSize private
Granularity of any transactions issued through this proxy.
Definition at line 91 of file port_proxy.hh.
Referenced by PortProxy(), readBlobPhys(), and writeBlobPhys().
sendFunctional
SendFunctionalFunc PortProxy::sendFunctional private
Definition at line 88 of file port_proxy.hh.
Referenced by readBlobPhys(), and writeBlobPhys().
The documentation for this class was generated from the following files:
mem/port_proxy.hh
mem/port_proxy.cc