gem5: VecPredRegContainer< NumBits, Packed > Class Template Reference
VecPredRegContainer< NumBits, Packed > Class Template Reference
Generic predicate register container.
#include <vec_pred_reg.hh>
Public Types
using Container = std::array< bool, NumBits >
Public Member Functions
VecPredRegContainer ()
MyClass & operator= (const MyClass &that)
MyClass & operator= (const std::vector< uint8_t > &that)
Required for de-serialization.
void reset ()
Resets the predicate register to an all-false register.
void set ()
Sets the predicate register to an all-true value.
template<size_t N2, bool P2>
bool operator== (const VecPredRegContainer< N2, P2 > &that) const
Equality operator, required to compare thread contexts.
template<size_t N2, bool P2>
bool operator!= (const VecPredRegContainer< N2, P2 > &that) const
Inequality operator, required to compare thread contexts.
bool & operator[] (size_t idx)
Returns a reference to a specific element of the internal container.
const bool & operator[] (size_t idx) const
Returns a const reference to a specific element of the internal container.
uint8_t get_bits (size_t idx, uint8_t nbits) const
Returns a subset of bits starting from a specific element in the container.
void set_bits (size_t idx, uint8_t nbits, uint8_t bval)
Set a subset of bits starting from a specific element in the container.
const std::string print () const
Returns a string representation of the register content.
template<typename VecElem , size_t NumElems = (Packed ? NumBits : NumBits / sizeof(VecElem))>
VecPredRegT< VecElem, NumElems, Packed, true > as () const
Create a view of this container.
template<typename VecElem , size_t NumElems = (Packed ? NumBits : NumBits / sizeof(VecElem))>
VecPredRegT< VecElem, NumElems, Packed, false > as ()
Static Public Attributes
static constexpr size_t NUM_BITS = NumBits
Private Types
using MyClass = VecPredRegContainer< NumBits, Packed >
Private Attributes
Container container
Friends
std::ostream & operator<< (std::ostream &os, const MyClass &v)
Detailed Description
template<size_t NumBits, bool Packed>
class VecPredRegContainer< NumBits, Packed >
Generic predicate register container.
This generic class implements the Model in an MVC pattern, similarly to
See also
VecRegContainer.
Template Parameters
NumBits Size of the container in bits.
Packed See .
Definition at line 51 of file vec_pred_reg.hh.
Member Typedef Documentation
Container
template<size_t NumBits, bool Packed> using VecPredRegContainer< NumBits, Packed >::Container = std::array<bool, NumBits>
Definition at line 242 of file vec_pred_reg.hh.
MyClass
template<size_t NumBits, bool Packed> using VecPredRegContainer< NumBits, Packed >::MyClass = VecPredRegContainer<NumBits, Packed> private
Definition at line 247 of file vec_pred_reg.hh.
Constructor & Destructor Documentation
VecPredRegContainer()
template<size_t NumBits, bool Packed> VecPredRegContainer< NumBits, Packed >::VecPredRegContainer () inline
Definition at line 250 of file vec_pred_reg.hh.
Member Function Documentation
as() [1/2]
template<size_t NumBits, bool Packed> template<typename VecElem , size_t NumElems = (Packed ? NumBits : NumBits / sizeof(VecElem))> VecPredRegT<VecElem, NumElems, Packed, true> VecPredRegContainer< NumBits, Packed >::as () const inline
Create a view of this container.
If NumElems is provided, the size of the container is bounds-checked, otherwise the size is inferred from the container size.
Template Parameters
VecElem Type of the vector elements.
NumElems Number of vector elements making up the view.
Definition at line 355 of file vec_pred_reg.hh.
as() [2/2]
template<size_t NumBits, bool Packed> template<typename VecElem , size_t NumElems = (Packed ? NumBits : NumBits / sizeof(VecElem))> VecPredRegT<VecElem, NumElems, Packed, false> VecPredRegContainer< NumBits, Packed >::as () inline
Definition at line 367 of file vec_pred_reg.hh.
get_bits()
template<size_t NumBits, bool Packed> uint8_t VecPredRegContainer< NumBits, Packed >::get_bits (size_t idx, uint8_t nbits) const inline
Returns a subset of bits starting from a specific element in the container.
Definition at line 310 of file vec_pred_reg.hh.
operator!=()
template<size_t NumBits, bool Packed> template<size_t N2, bool P2> bool VecPredRegContainer< NumBits, Packed >::operator!= (const VecPredRegContainer< N2, P2 > & that) const inline
Inequality operator, required to compare thread contexts.
Definition at line 295 of file vec_pred_reg.hh.
operator=() [1/2]
template<size_t NumBits, bool Packed> MyClass& VecPredRegContainer< NumBits, Packed >::operator= (const MyClass & that) inline
Definition at line 253 of file vec_pred_reg.hh.
operator=() [2/2]
template<size_t NumBits, bool Packed> MyClass& VecPredRegContainer< NumBits, Packed >::operator= (const std::vector< uint8_t > & that) inline
Required for de-serialization.
Definition at line 263 of file vec_pred_reg.hh.
operator==()
template<size_t NumBits, bool Packed> template<size_t N2, bool P2> bool VecPredRegContainer< NumBits, Packed >::operator== (const VecPredRegContainer< N2, P2 > & that) const inline
Equality operator, required to compare thread contexts.
Definition at line 287 of file vec_pred_reg.hh.
operator[]() [1/2]
template<size_t NumBits, bool Packed> bool& VecPredRegContainer< NumBits, Packed >::operator[] (size_t idx) inline
Returns a reference to a specific element of the internal container.
Definition at line 301 of file vec_pred_reg.hh.
operator[]() [2/2]
template<size_t NumBits, bool Packed> const bool& VecPredRegContainer< NumBits, Packed >::operator[] (size_t idx) const inline
Returns a const reference to a specific element of the internal container.
Definition at line 305 of file vec_pred_reg.hh.
print()
template<size_t NumBits, bool Packed> const std::string VecPredRegContainer< NumBits, Packed >::print () const inline
Returns a string representation of the register content.
Definition at line 335 of file vec_pred_reg.hh.
Referenced by SimpleThread::getWritableVecPredReg(), SimpleThread::readVecPredReg(), PhysRegFile::setVecPredReg(), and SimpleThread::setVecPredReg().
reset()
template<size_t NumBits, bool Packed> void VecPredRegContainer< NumBits, Packed >::reset () inline
Resets the predicate register to an all-false register.
Definition at line 272 of file vec_pred_reg.hh.
set()
template<size_t NumBits, bool Packed> void VecPredRegContainer< NumBits, Packed >::set () inline
Sets the predicate register to an all-true value.
Definition at line 279 of file vec_pred_reg.hh.
set_bits()
template<size_t NumBits, bool Packed> void VecPredRegContainer< NumBits, Packed >::set_bits (size_t idx, uint8_t nbits, uint8_t bval) inline
Set a subset of bits starting from a specific element in the container.
Definition at line 325 of file vec_pred_reg.hh.
Friends And Related Function Documentation
operator<<
template<size_t NumBits, bool Packed> std::ostream& operator<< (std::ostream & os, const MyClass & v) friend
Definition at line 338 of file vec_pred_reg.hh.
Member Data Documentation
container
template<size_t NumBits, bool Packed> Container VecPredRegContainer< NumBits, Packed >::container private
Definition at line 245 of file vec_pred_reg.hh.
Referenced by VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::operator=(), and VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::operator==().
NUM_BITS
template<size_t NumBits, bool Packed> constexpr size_t VecPredRegContainer< NumBits, Packed >::NUM_BITS = NumBits static
Definition at line 241 of file vec_pred_reg.hh.
The documentation for this class was generated from the following file:
arch/generic/vec_pred_reg.hh