gem5: BaseGic Class Reference
BaseGic Class Reference abstract
#include <base_gic.hh>
Public Types
enum GicVersion { GicVersion::GIC_V2, GicVersion::GIC_V3, GicVersion::GIC_V4 }
typedef BaseGicParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BaseGic (const Params *p)
virtual ~BaseGic ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
const Params * params () const
virtual void sendInt (uint32_t num)=0
Post an interrupt from a device that is connected to the GIC.
virtual void sendPPInt (uint32_t num, uint32_t cpu)=0
Interface call for private peripheral interrupts.
virtual void clearPPInt (uint32_t num, uint32_t cpu)=0
virtual void clearInt (uint32_t num)=0
Clear an interrupt from a device that is connected to the GIC.
ArmSystem * getSystem () const
virtual bool supportsVersion (GicVersion version)=0
Check if version supported.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
Platform * platform
Platform this GIC belongs to.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from PioDevice
virtual AddrRangeList getAddrRanges () const =0
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
virtual Tick read (PacketPtr pkt)=0
Pure virtual function that the device must implement.
virtual Tick write (PacketPtr pkt)=0
Pure virtual function that the device must implement.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 64 of file base_gic.hh.
Member Typedef Documentation
Params
typedef BaseGicParams BaseGic::Params
Definition at line 67 of file base_gic.hh.
Member Enumeration Documentation
GicVersion
enum BaseGic::GicVersion strong
Enumerator
GIC_V2
GIC_V3
GIC_V4
Definition at line 68 of file base_gic.hh.
Constructor & Destructor Documentation
BaseGic()
BaseGic::BaseGic (const Params * p)
Definition at line 49 of file base_gic.cc.
References fatal_if, and RealView::setGic().
~BaseGic()
BaseGic::~BaseGic () virtual
Definition at line 63 of file base_gic.cc.
Member Function Documentation
clearInt()
virtual void BaseGic::clearInt (uint32_t num) pure virtual
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters
num number of interrupt to send
Implemented in GicV2, MuxingKvmGic, FastModel::GIC, and Gicv3.
Referenced by ArmSPI::clear(), UFSHostDevice::clearInterrupt(), RealView::clearPciInt(), NoMaliGpu::onInterrupt(), Pl011::setInterrupts(), HDLcd::setInterrupts(), Pl050::updateIntCtrl(), Sp804::Timer::write(), A9GlobalTimer::Timer::write(), and Pl111::write().
clearPPInt()
virtual void BaseGic::clearPPInt (uint32_t num, uint32_t cpu) pure virtual
Implemented in GicV2, MuxingKvmGic, FastModel::GIC, and Gicv3.
Referenced by ArmPPI::clear(), and VGic::unPostMaintInt().
getSystem()
ArmSystem* BaseGic::getSystem () const inline
Definition at line 106 of file base_gic.hh.
References supportsVersion(), and PioDevice::sys.
Referenced by Gicv3CPUInterface::generateSGI(), Gicv3Redistributor::getAffinity(), Gicv3Distributor::Gicv3Distributor(), Gicv3CPUInterface::haveEL(), init(), Gicv3Redistributor::init(), Gicv3CPUInterface::inSecureState(), Gicv3Redistributor::read(), Gicv3Distributor::route(), Gicv3::unserialize(), and Gicv3Distributor::update().
init()
void BaseGic::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in Gicv3.
Definition at line 68 of file base_gic.cc.
References getSystem(), PioDevice::init(), and ArmSystem::setGIC().
Referenced by Gicv3::init().
params()
const BaseGic::Params * BaseGic::params () const
Definition at line 75 of file base_gic.cc.
References SimObject::_params.
sendInt()
virtual void BaseGic::sendInt (uint32_t num) pure virtual
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters
num number of interrupt to send
Implemented in GicV2, MuxingKvmGic, FastModel::GIC, and Gicv3.
Referenced by Sp804::Timer::counterAtZero(), PL031::counterMatch(), Pl011::generateInterrupt(), Pl111::generateInterrupt(), UFSHostDevice::generateInterrupt(), NoMaliGpu::onInterrupt(), RealView::postPciInt(), ArmSPI::raise(), HDLcd::setInterrupts(), Pl050::updateIntCtrl(), and Gicv2m::write().
sendPPInt()
virtual void BaseGic::sendPPInt (uint32_t num, uint32_t cpu) pure virtual
Interface call for private peripheral interrupts.
Parameters
num number of interrupt to send
cpu CPU to forward interrupt to
Implemented in GicV2, MuxingKvmGic, FastModel::GIC, and Gicv3.
Referenced by A9GlobalTimer::Timer::counterAtCmpVal(), VGic::postMaintInt(), and ArmPPI::raise().
supportsVersion()
virtual bool BaseGic::supportsVersion (GicVersion version) pure virtual
Check if version supported.
Implemented in GicV2, FastModel::GIC, and Gicv3.
Referenced by getSystem(), and ArmSystem::initState().
Member Data Documentation
platform
Platform* BaseGic::platform protected
Platform this GIC belongs to.
Definition at line 116 of file base_gic.hh.
Referenced by GicV2::clearInt(), Gicv3::deassertInt(), GicV2::postDelayedFiq(), GicV2::postDelayedInt(), and Gicv3::postInt().
The documentation for this class was generated from the following files:
dev/arm/base_gic.hh
dev/arm/base_gic.cc