gem5: sc_dt::sc_unsigned Class Reference
sc_dt::sc_unsigned Class Reference
#include <sc_unsigned.hh>
Public Member Functions
sc_unsigned (int nb=sc_length_param().len())
sc_unsigned (const sc_unsigned &v)
sc_unsigned (const sc_signed &v)
template<class T >
sc_unsigned (const sc_generic_base< T > &v)
sc_unsigned (const sc_bv_base &v)
sc_unsigned (const sc_lv_base &v)
sc_unsigned (const sc_int_subref_r &v)
sc_unsigned (const sc_uint_subref_r &v)
sc_unsigned (const sc_signed_subref_r &v)
sc_unsigned (const sc_unsigned_subref_r &v)
const sc_unsigned & operator= (const sc_unsigned &v)
const sc_unsigned & operator= (const sc_unsigned_subref_r &a)
template<class T >
const sc_unsigned & operator= (const sc_generic_base< T > &a)
const sc_unsigned & operator= (const sc_signed &v)
const sc_unsigned & operator= (const sc_signed_subref_r &a)
const sc_unsigned & operator= (const char *v)
const sc_unsigned & operator= (int64 v)
const sc_unsigned & operator= (uint64 v)
const sc_unsigned & operator= (long v)
const sc_unsigned & operator= (unsigned long v)
const sc_unsigned & operator= (int v)
const sc_unsigned & operator= (unsigned int v)
const sc_unsigned & operator= (double v)
const sc_unsigned & operator= (const sc_int_base &v)
const sc_unsigned & operator= (const sc_uint_base &v)
const sc_unsigned & operator= (const sc_bv_base &)
const sc_unsigned & operator= (const sc_lv_base &)
const sc_unsigned & operator= (const sc_fxval &)
const sc_unsigned & operator= (const sc_fxval_fast &)
const sc_unsigned & operator= (const sc_fxnum &)
const sc_unsigned & operator= (const sc_fxnum_fast &)
virtual ~sc_unsigned ()
sc_digit * get_raw () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
sc_unsigned & operator++ ()
const sc_unsigned operator++ (int)
sc_unsigned & operator-- ()
const sc_unsigned operator-- (int)
void check_index (int i) const
void invalid_index (int i) const
sc_unsigned_bitref & operator[] (int i)
const sc_unsigned_bitref_r & operator[] (int i) const
sc_unsigned_bitref & bit (int i)
const sc_unsigned_bitref_r & bit (int i) const
void check_range (int l, int r) const
void invalid_range (int l, int r) const
sc_unsigned_subref & range (int i, int j)
const sc_unsigned_subref_r & range (int i, int j) const
sc_unsigned_subref & operator() (int i, int j)
const sc_unsigned_subref_r & operator() (int i, int j) const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
void dump (::std::ostream &os=::std::cout) const
int length () const
bool iszero () const
bool sign () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
bool test (int i) const
void set (int i)
void clear (int i)
void set (int i, bool v)
void invert (int i)
void reverse ()
void get_packed_rep (sc_digit *buf) const
void set_packed_rep (sc_digit *buf)
const sc_unsigned & operator+= (const sc_signed &v)
const sc_unsigned & operator+= (const sc_unsigned &v)
const sc_unsigned & operator+= (int64 v)
const sc_unsigned & operator+= (uint64 v)
const sc_unsigned & operator+= (long v)
const sc_unsigned & operator+= (unsigned long v)
const sc_unsigned & operator+= (int v)
const sc_unsigned & operator+= (unsigned int v)
const sc_unsigned & operator+= (const sc_int_base &v)
const sc_unsigned & operator+= (const sc_uint_base &v)
const sc_unsigned & operator-= (const sc_signed &v)
const sc_unsigned & operator-= (const sc_unsigned &v)
const sc_unsigned & operator-= (int64 v)
const sc_unsigned & operator-= (uint64 v)
const sc_unsigned & operator-= (long v)
const sc_unsigned & operator-= (unsigned long v)
const sc_unsigned & operator-= (int v)
const sc_unsigned & operator-= (unsigned int v)
const sc_unsigned & operator-= (const sc_int_base &v)
const sc_unsigned & operator-= (const sc_uint_base &v)
const sc_unsigned & operator*= (const sc_signed &v)
const sc_unsigned & operator*= (const sc_unsigned &v)
const sc_unsigned & operator*= (int64 v)
const sc_unsigned & operator*= (uint64 v)
const sc_unsigned & operator*= (long v)
const sc_unsigned & operator*= (unsigned long v)
const sc_unsigned & operator*= (int v)
const sc_unsigned & operator*= (unsigned int v)
const sc_unsigned & operator*= (const sc_int_base &v)
const sc_unsigned & operator*= (const sc_uint_base &v)
const sc_unsigned & operator/= (const sc_signed &v)
const sc_unsigned & operator/= (const sc_unsigned &v)
const sc_unsigned & operator/= (int64 v)
const sc_unsigned & operator/= (uint64 v)
const sc_unsigned & operator/= (long v)
const sc_unsigned & operator/= (unsigned long v)
const sc_unsigned & operator/= (int v)
const sc_unsigned & operator/= (unsigned int v)
const sc_unsigned & operator/= (const sc_int_base &v)
const sc_unsigned & operator/= (const sc_uint_base &v)
const sc_unsigned & operator%= (const sc_signed &v)
const sc_unsigned & operator%= (const sc_unsigned &v)
const sc_unsigned & operator%= (int64 v)
const sc_unsigned & operator%= (uint64 v)
const sc_unsigned & operator%= (long v)
const sc_unsigned & operator%= (unsigned long v)
const sc_unsigned & operator%= (int v)
const sc_unsigned & operator%= (unsigned int v)
const sc_unsigned & operator%= (const sc_int_base &v)
const sc_unsigned & operator%= (const sc_uint_base &v)
const sc_unsigned & operator&= (const sc_signed &v)
const sc_unsigned & operator&= (const sc_unsigned &v)
const sc_unsigned & operator&= (int64 v)
const sc_unsigned & operator&= (uint64 v)
const sc_unsigned & operator&= (long v)
const sc_unsigned & operator&= (unsigned long v)
const sc_unsigned & operator&= (int v)
const sc_unsigned & operator&= (unsigned int v)
const sc_unsigned & operator&= (const sc_int_base &v)
const sc_unsigned & operator&= (const sc_uint_base &v)
const sc_unsigned & operator|= (const sc_signed &v)
const sc_unsigned & operator|= (const sc_unsigned &v)
const sc_unsigned & operator|= (int64 v)
const sc_unsigned & operator|= (uint64 v)
const sc_unsigned & operator|= (long v)
const sc_unsigned & operator|= (unsigned long v)
const sc_unsigned & operator|= (int v)
const sc_unsigned & operator|= (unsigned int v)
const sc_unsigned & operator|= (const sc_int_base &v)
const sc_unsigned & operator|= (const sc_uint_base &v)
const sc_unsigned & operator^= (const sc_signed &v)
const sc_unsigned & operator^= (const sc_unsigned &v)
const sc_unsigned & operator^= (int64 v)
const sc_unsigned & operator^= (uint64 v)
const sc_unsigned & operator^= (long v)
const sc_unsigned & operator^= (unsigned long v)
const sc_unsigned & operator^= (int v)
const sc_unsigned & operator^= (unsigned int v)
const sc_unsigned & operator^= (const sc_int_base &v)
const sc_unsigned & operator^= (const sc_uint_base &v)
const sc_unsigned & operator<<= (const sc_signed &v)
const sc_unsigned & operator<<= (const sc_unsigned &v)
const sc_unsigned & operator<<= (int64 v)
const sc_unsigned & operator<<= (uint64 v)
const sc_unsigned & operator<<= (long v)
const sc_unsigned & operator<<= (unsigned long v)
const sc_unsigned & operator<<= (int v)
const sc_unsigned & operator<<= (unsigned int v)
const sc_unsigned & operator<<= (const sc_int_base &v)
const sc_unsigned & operator<<= (const sc_uint_base &v)
const sc_unsigned & operator>>= (const sc_signed &v)
const sc_unsigned & operator>>= (const sc_unsigned &v)
const sc_unsigned & operator>>= (int64 v)
const sc_unsigned & operator>>= (uint64 v)
const sc_unsigned & operator>>= (long v)
const sc_unsigned & operator>>= (unsigned long v)
const sc_unsigned & operator>>= (int v)
const sc_unsigned & operator>>= (unsigned int v)
const sc_unsigned & operator>>= (const sc_int_base &v)
const sc_unsigned & operator>>= (const sc_uint_base &v)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Attributes
static sc_core::sc_vpool< sc_unsigned > m_pool
Private Types
typedef bool elemtype
Private Member Functions
void invalid_init (const char *type_name, int nb) const
sc_unsigned (const sc_unsigned &v, small_type s)
sc_unsigned (const sc_signed &v, small_type s)
sc_unsigned (small_type s, int nb, int nd, sc_digit *d, bool alloc=true)
sc_unsigned (const sc_signed *u, int l, int r)
sc_unsigned (const sc_unsigned *u, int l, int r)
small_type default_sign () const
int num_bits (int nb) const
bool check_if_outside (int bit_num) const
void copy_digits (int nb, int nd, const sc_digit *d)
void makezero ()
void convert_2C_to_SM ()
void convert_SM_to_2C_to_SM ()
void convert_SM_to_2C ()
Private Attributes
small_type sgn
int nbits
int ndigits
sc_digit * digit
Friends
class sc_concatref
class sc_unsigned_bitref_r
class sc_unsigned_bitref
class sc_unsigned_subref_r
class sc_unsigned_subref
class sc_signed
class sc_signed_subref
class sc_signed_subref_r
sc_signed operator+ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator+ (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator+ (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator+ (const sc_unsigned &u, int64 v)
sc_unsigned operator+ (const sc_unsigned &u, uint64 v)
sc_signed operator+ (const sc_unsigned &u, long v)
sc_unsigned operator+ (const sc_unsigned &u, unsigned long v)
sc_signed operator+ (const sc_unsigned &u, int v)
sc_unsigned operator+ (const sc_unsigned &u, unsigned int v)
sc_signed operator+ (int64 u, const sc_unsigned &v)
sc_unsigned operator+ (uint64 u, const sc_unsigned &v)
sc_signed operator+ (long u, const sc_unsigned &v)
sc_unsigned operator+ (unsigned long u, const sc_unsigned &v)
sc_signed operator+ (int u, const sc_unsigned &v)
sc_unsigned operator+ (unsigned int u, const sc_unsigned &v)
sc_unsigned operator+ (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator+ (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator+ (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator+ (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, const sc_signed &v)
sc_signed operator- (const sc_signed &u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, int64 v)
sc_signed operator- (const sc_unsigned &u, uint64 v)
sc_signed operator- (const sc_unsigned &u, long v)
sc_signed operator- (const sc_unsigned &u, unsigned long v)
sc_signed operator- (const sc_unsigned &u, int v)
sc_signed operator- (const sc_unsigned &u, unsigned int v)
sc_signed operator- (int64 u, const sc_unsigned &v)
sc_signed operator- (uint64 u, const sc_unsigned &v)
sc_signed operator- (long u, const sc_unsigned &v)
sc_signed operator- (unsigned long u, const sc_unsigned &v)
sc_signed operator- (int u, const sc_unsigned &v)
sc_signed operator- (unsigned int u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator- (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator- (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator- (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator* (const sc_unsigned &u, const sc_signed &v)
sc_signed operator* (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator* (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator* (const sc_unsigned &u, int64 v)
sc_unsigned operator* (const sc_unsigned &u, uint64 v)
sc_signed operator* (const sc_unsigned &u, long v)
sc_unsigned operator* (const sc_unsigned &u, unsigned long v)
sc_signed operator* (const sc_unsigned &u, int v)
sc_unsigned operator* (const sc_unsigned &u, unsigned int v)
sc_signed operator* (int64 u, const sc_unsigned &v)
sc_unsigned operator* (uint64 u, const sc_unsigned &v)
sc_signed operator* (long u, const sc_unsigned &v)
sc_unsigned operator* (unsigned long u, const sc_unsigned &v)
sc_signed operator* (int u, const sc_unsigned &v)
sc_unsigned operator* (unsigned int u, const sc_unsigned &v)
sc_unsigned operator* (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator* (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator* (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator* (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator/ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator/ (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator/ (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator/ (const sc_unsigned &u, int64 v)
sc_unsigned operator/ (const sc_unsigned &u, uint64 v)
sc_signed operator/ (const sc_unsigned &u, long v)
sc_unsigned operator/ (const sc_unsigned &u, unsigned long v)
sc_signed operator/ (const sc_unsigned &u, int v)
sc_unsigned operator/ (const sc_unsigned &u, unsigned int v)
sc_signed operator/ (int64 u, const sc_unsigned &v)
sc_unsigned operator/ (uint64 u, const sc_unsigned &v)
sc_signed operator/ (long u, const sc_unsigned &v)
sc_unsigned operator/ (unsigned long u, const sc_unsigned &v)
sc_signed operator/ (int u, const sc_unsigned &v)
sc_unsigned operator/ (unsigned int u, const sc_unsigned &v)
sc_unsigned operator/ (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator/ (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator/ (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator/ (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator% (const sc_unsigned &u, const sc_signed &v)
sc_signed operator% (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator% (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator% (const sc_unsigned &u, int64 v)
sc_unsigned operator% (const sc_unsigned &u, uint64 v)
sc_signed operator% (const sc_unsigned &u, long v)
sc_unsigned operator% (const sc_unsigned &u, unsigned long v)
sc_signed operator% (const sc_unsigned &u, int v)
sc_unsigned operator% (const sc_unsigned &u, unsigned int v)
sc_signed operator% (int64 u, const sc_unsigned &v)
sc_unsigned operator% (uint64 u, const sc_unsigned &v)
sc_signed operator% (long u, const sc_unsigned &v)
sc_unsigned operator% (unsigned long u, const sc_unsigned &v)
sc_signed operator% (int u, const sc_unsigned &v)
sc_unsigned operator% (unsigned int u, const sc_unsigned &v)
sc_unsigned operator% (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator% (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator% (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator% (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator& (const sc_unsigned &u, const sc_signed &v)
sc_signed operator& (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator& (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator& (const sc_unsigned &u, int64 v)
sc_unsigned operator& (const sc_unsigned &u, uint64 v)
sc_signed operator& (const sc_unsigned &u, long v)
sc_unsigned operator& (const sc_unsigned &u, unsigned long v)
sc_signed operator& (const sc_unsigned &u, int v)
sc_unsigned operator& (const sc_unsigned &u, unsigned int v)
sc_signed operator& (int64 u, const sc_unsigned &v)
sc_unsigned operator& (uint64 u, const sc_unsigned &v)
sc_signed operator& (long u, const sc_unsigned &v)
sc_unsigned operator& (unsigned long u, const sc_unsigned &v)
sc_signed operator& (int u, const sc_unsigned &v)
sc_unsigned operator& (unsigned int u, const sc_unsigned &v)
sc_unsigned operator& (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator& (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator& (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator& (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator| (const sc_unsigned &u, const sc_signed &v)
sc_signed operator| (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator| (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator| (const sc_unsigned &u, int64 v)
sc_unsigned operator| (const sc_unsigned &u, uint64 v)
sc_signed operator| (const sc_unsigned &u, long v)
sc_unsigned operator| (const sc_unsigned &u, unsigned long v)
sc_signed operator| (const sc_unsigned &u, int v)
sc_unsigned operator| (const sc_unsigned &u, unsigned int v)
sc_signed operator| (int64 u, const sc_unsigned &v)
sc_unsigned operator| (uint64 u, const sc_unsigned &v)
sc_signed operator| (long u, const sc_unsigned &v)
sc_unsigned operator| (unsigned long u, const sc_unsigned &v)
sc_signed operator| (int u, const sc_unsigned &v)
sc_unsigned operator| (unsigned int u, const sc_unsigned &v)
sc_unsigned operator| (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator| (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator| (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator| (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator^ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator^ (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator^ (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator^ (const sc_unsigned &u, int64 v)
sc_unsigned operator^ (const sc_unsigned &u, uint64 v)
sc_signed operator^ (const sc_unsigned &u, long v)
sc_unsigned operator^ (const sc_unsigned &u, unsigned long v)
sc_signed operator^ (const sc_unsigned &u, int v)
sc_unsigned operator^ (const sc_unsigned &u, unsigned int v)
sc_signed operator^ (int64 u, const sc_unsigned &v)
sc_unsigned operator^ (uint64 u, const sc_unsigned &v)
sc_signed operator^ (long u, const sc_unsigned &v)
sc_unsigned operator^ (unsigned long u, const sc_unsigned &v)
sc_signed operator^ (int u, const sc_unsigned &v)
sc_unsigned operator^ (unsigned int u, const sc_unsigned &v)
sc_unsigned operator^ (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator^ (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator^ (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator^ (const sc_int_base &u, const sc_unsigned &v)
sc_unsigned operator<< (const sc_unsigned &u, const sc_signed &v)
sc_signed operator<< (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator<< (const sc_unsigned &u, const sc_unsigned &v)
sc_unsigned operator<< (const sc_unsigned &u, int64 v)
sc_unsigned operator<< (const sc_unsigned &u, uint64 v)
sc_unsigned operator<< (const sc_unsigned &u, long v)
sc_unsigned operator<< (const sc_unsigned &u, unsigned long v)
sc_unsigned operator<< (const sc_unsigned &u, int v)
sc_unsigned operator<< (const sc_unsigned &u, unsigned int v)
sc_unsigned operator<< (const sc_unsigned &u, const sc_uint_base &v)
sc_unsigned operator<< (const sc_unsigned &u, const sc_int_base &v)
sc_unsigned operator>> (const sc_unsigned &u, const sc_signed &v)
sc_signed operator>> (const sc_signed &u, const sc_unsigned &v)
sc_unsigned operator>> (const sc_unsigned &u, const sc_unsigned &v)
sc_unsigned operator>> (const sc_unsigned &u, int64 v)
sc_unsigned operator>> (const sc_unsigned &u, uint64 v)
sc_unsigned operator>> (const sc_unsigned &u, long v)
sc_unsigned operator>> (const sc_unsigned &u, unsigned long v)
sc_unsigned operator>> (const sc_unsigned &u, int v)
sc_unsigned operator>> (const sc_unsigned &u, unsigned int v)
sc_unsigned operator>> (const sc_unsigned &, const sc_uint_base &)
sc_unsigned operator>> (const sc_unsigned &, const sc_int_base &)
sc_unsigned operator+ (const sc_unsigned &u)
sc_signed operator- (const sc_unsigned &u)
bool operator== (const sc_unsigned &u, const sc_signed &v)
bool operator== (const sc_signed &u, const sc_unsigned &v)
bool operator== (const sc_unsigned &u, const sc_unsigned &v)
bool operator== (const sc_unsigned &u, int64 v)
bool operator== (const sc_unsigned &u, uint64 v)
bool operator== (const sc_unsigned &u, long v)
bool operator== (const sc_unsigned &u, unsigned long v)
bool operator== (const sc_unsigned &u, int v)
bool operator== (const sc_unsigned &u, unsigned int v)
bool operator== (int64 u, const sc_unsigned &v)
bool operator== (uint64 u, const sc_unsigned &v)
bool operator== (long u, const sc_unsigned &v)
bool operator== (unsigned long u, const sc_unsigned &v)
bool operator== (int u, const sc_unsigned &v)
bool operator== (unsigned int u, const sc_unsigned &v)
bool operator== (const sc_unsigned &u, const sc_uint_base &v)
bool operator== (const sc_unsigned &u, const sc_int_base &v)
bool operator== (const sc_uint_base &u, const sc_unsigned &v)
bool operator== (const sc_int_base &u, const sc_unsigned &v)
bool operator!= (const sc_unsigned &u, const sc_signed &v)
bool operator!= (const sc_signed &u, const sc_unsigned &v)
bool operator!= (const sc_unsigned &u, const sc_unsigned &v)
bool operator!= (const sc_unsigned &u, int64 v)
bool operator!= (const sc_unsigned &u, uint64 v)
bool operator!= (const sc_unsigned &u, long v)
bool operator!= (const sc_unsigned &u, unsigned long v)
bool operator!= (const sc_unsigned &u, int v)
bool operator!= (const sc_unsigned &u, unsigned int v)
bool operator!= (int64 u, const sc_unsigned &v)
bool operator!= (uint64 u, const sc_unsigned &v)
bool operator!= (long u, const sc_unsigned &v)
bool operator!= (unsigned long u, const sc_unsigned &v)
bool operator!= (int u, const sc_unsigned &v)
bool operator!= (unsigned int u, const sc_unsigned &v)
bool operator!= (const sc_unsigned &u, const sc_uint_base &v)
bool operator!= (const sc_unsigned &u, const sc_int_base &v)
bool operator!= (const sc_uint_base &u, const sc_unsigned &v)
bool operator!= (const sc_int_base &u, const sc_unsigned &v)
bool operator< (const sc_unsigned &u, const sc_signed &v)
bool operator< (const sc_signed &u, const sc_unsigned &v)
bool operator< (const sc_unsigned &u, const sc_unsigned &v)
bool operator< (const sc_unsigned &u, int64 v)
bool operator< (const sc_unsigned &u, uint64 v)
bool operator< (const sc_unsigned &u, long v)
bool operator< (const sc_unsigned &u, unsigned long v)
bool operator< (const sc_unsigned &u, int v)
bool operator< (const sc_unsigned &u, unsigned int v)
bool operator< (int64 u, const sc_unsigned &v)
bool operator< (uint64 u, const sc_unsigned &v)
bool operator< (long u, const sc_unsigned &v)
bool operator< (unsigned long u, const sc_unsigned &v)
bool operator< (int u, const sc_unsigned &v)
bool operator< (unsigned int u, const sc_unsigned &v)
bool operator< (const sc_unsigned &u, const sc_uint_base &v)
bool operator< (const sc_unsigned &u, const sc_int_base &v)
bool operator< (const sc_uint_base &u, const sc_unsigned &v)
bool operator< (const sc_int_base &u, const sc_unsigned &v)
bool operator<= (const sc_unsigned &u, const sc_signed &v)
bool operator<= (const sc_signed &u, const sc_unsigned &v)
bool operator<= (const sc_unsigned &u, const sc_unsigned &v)
bool operator<= (const sc_unsigned &u, int64 v)
bool operator<= (const sc_unsigned &u, uint64 v)
bool operator<= (const sc_unsigned &u, long v)
bool operator<= (const sc_unsigned &u, unsigned long v)
bool operator<= (const sc_unsigned &u, int v)
bool operator<= (const sc_unsigned &u, unsigned int v)
bool operator<= (int64 u, const sc_unsigned &v)
bool operator<= (uint64 u, const sc_unsigned &v)
bool operator<= (long u, const sc_unsigned &v)
bool operator<= (unsigned long u, const sc_unsigned &v)
bool operator<= (int u, const sc_unsigned &v)
bool operator<= (unsigned int u, const sc_unsigned &v)
bool operator<= (const sc_unsigned &u, const sc_uint_base &v)
bool operator<= (const sc_unsigned &u, const sc_int_base &v)
bool operator<= (const sc_uint_base &u, const sc_unsigned &v)
bool operator<= (const sc_int_base &u, const sc_unsigned &v)
bool operator> (const sc_unsigned &u, const sc_signed &v)
bool operator> (const sc_signed &u, const sc_unsigned &v)
bool operator> (const sc_unsigned &u, const sc_unsigned &v)
bool operator> (const sc_unsigned &u, int64 v)
bool operator> (const sc_unsigned &u, uint64 v)
bool operator> (const sc_unsigned &u, long v)
bool operator> (const sc_unsigned &u, unsigned long v)
bool operator> (const sc_unsigned &u, int v)
bool operator> (const sc_unsigned &u, unsigned int v)
bool operator> (int64 u, const sc_unsigned &v)
bool operator> (uint64 u, const sc_unsigned &v)
bool operator> (long u, const sc_unsigned &v)
bool operator> (unsigned long u, const sc_unsigned &v)
bool operator> (int u, const sc_unsigned &v)
bool operator> (unsigned int u, const sc_unsigned &v)
bool operator> (const sc_unsigned &u, const sc_uint_base &v)
bool operator> (const sc_unsigned &u, const sc_int_base &v)
bool operator> (const sc_uint_base &u, const sc_unsigned &v)
bool operator> (const sc_int_base &u, const sc_unsigned &v)
bool operator>= (const sc_unsigned &u, const sc_signed &v)
bool operator>= (const sc_signed &u, const sc_unsigned &v)
bool operator>= (const sc_unsigned &u, const sc_unsigned &v)
bool operator>= (const sc_unsigned &u, int64 v)
bool operator>= (const sc_unsigned &u, uint64 v)
bool operator>= (const sc_unsigned &u, long v)
bool operator>= (const sc_unsigned &u, unsigned long v)
bool operator>= (const sc_unsigned &u, int v)
bool operator>= (const sc_unsigned &u, unsigned int v)
bool operator>= (int64 u, const sc_unsigned &v)
bool operator>= (uint64 u, const sc_unsigned &v)
bool operator>= (long u, const sc_unsigned &v)
bool operator>= (unsigned long u, const sc_unsigned &v)
bool operator>= (int u, const sc_unsigned &v)
bool operator>= (unsigned int u, const sc_unsigned &v)
bool operator>= (const sc_unsigned &u, const sc_uint_base &v)
bool operator>= (const sc_unsigned &u, const sc_int_base &v)
bool operator>= (const sc_uint_base &u, const sc_unsigned &v)
bool operator>= (const sc_int_base &u, const sc_unsigned &v)
sc_unsigned operator~ (const sc_unsigned &u)
int compare_unsigned (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd, small_type if_u_signed, small_type if_v_signed)
sc_unsigned add_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_unsigned sub_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_unsigned mul_unsigned_friend (small_type s, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_unsigned div_unsigned_friend (small_type s, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_unsigned mod_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_unsigned and_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_unsigned or_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_unsigned xor_unsigned_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
Detailed Description
Definition at line 890 of file sc_unsigned.hh.
Member Typedef Documentation
elemtype
typedef bool sc_dt::sc_unsigned::elemtype private
Definition at line 902 of file sc_unsigned.hh.
Constructor & Destructor Documentation
sc_unsigned() [1/15]
sc_dt::sc_unsigned::sc_unsigned (int nb = sc_length_param().len()) explicit
sc_unsigned() [2/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_unsigned & v)
sc_unsigned() [3/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_signed & v)
sc_unsigned() [4/15]
template<class T > sc_dt::sc_unsigned::sc_unsigned (const sc_generic_base< T > & v) explicit
Definition at line 2159 of file sc_unsigned.hh.
References DIV_CEIL, and sc_core::sc_abort().
sc_unsigned() [5/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_bv_base & v) explicit
sc_unsigned() [6/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_lv_base & v) explicit
sc_unsigned() [7/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_int_subref_r & v) explicit
sc_unsigned() [8/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_uint_subref_r & v) explicit
sc_unsigned() [9/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_signed_subref_r & v) explicit
sc_unsigned() [10/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_unsigned_subref_r & v) explicit
~sc_unsigned()
virtual sc_dt::sc_unsigned::~sc_unsigned () inline virtual
Definition at line 966 of file sc_unsigned.hh.
sc_unsigned() [11/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_unsigned & v, small_type s) private
sc_unsigned() [12/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_signed & v, small_type s) private
sc_unsigned() [13/15]
sc_dt::sc_unsigned::sc_unsigned (small_type s, int nb, int nd, sc_digit * d, bool alloc = true) private
sc_unsigned() [14/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_signed * u, int l, int r) private
sc_unsigned() [15/15]
sc_dt::sc_unsigned::sc_unsigned (const sc_unsigned * u, int l, int r) private
Member Function Documentation
and_reduce()
bool sc_dt::sc_unsigned::and_reduce () const
Definition at line 397 of file sc_unsigned.cc.
References DIGIT_MASK, ArmISA::i, and SC_ZERO.
bit() [1/2]
sc_unsigned_bitref& sc_dt::sc_unsigned::bit (int i) inline
Definition at line 1027 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_bitref_r::initialize(), and sc_dt::sc_unsigned_bitref::m_pool.
bit() [2/2]
const sc_unsigned_bitref_r& sc_dt::sc_unsigned::bit (int i) const inline
Definition at line 1036 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_bitref_r::initialize(), and sc_dt::sc_unsigned_bitref::m_pool.
check_if_outside()
bool sc_dt::sc_unsigned::check_if_outside (int bit_num) const private
check_index()
void sc_dt::sc_unsigned::check_index (int i) const inline
Definition at line 1000 of file sc_unsigned.hh.
References ArmISA::i.
check_range()
void sc_dt::sc_unsigned::check_range (int l, int r) const inline
Definition at line 1053 of file sc_unsigned.hh.
References MipsISA::l, and MipsISA::r.
clear()
void sc_dt::sc_unsigned::clear (int i)
concat_get_ctrl()
bool sc_dt::sc_unsigned::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 166 of file sc_unsigned.cc.
References ArmISA::mask.
concat_get_data()
bool sc_dt::sc_unsigned::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 195 of file sc_unsigned.cc.
References ArmISA::mask.
concat_get_uint64()
uint64 sc_dt::sc_unsigned::concat_get_uint64 () const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 340 of file sc_unsigned.cc.
References SC_POS.
concat_length()
virtual int sc_dt::sc_unsigned::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 976 of file sc_unsigned.hh.
concat_set() [1/4]
void sc_dt::sc_unsigned::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 362 of file sc_unsigned.cc.
Referenced by sc_dt::sc_concatref::operator=().
concat_set() [2/4]
void sc_dt::sc_unsigned::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 368 of file sc_unsigned.cc.
References sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_unsigned::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 377 of file sc_unsigned.cc.
References length().
concat_set() [4/4]
void sc_dt::sc_unsigned::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 386 of file sc_unsigned.cc.
convert_2C_to_SM()
void sc_dt::sc_unsigned::convert_2C_to_SM () inline private
Definition at line 2008 of file sc_unsigned.hh.
References sc_dt::convert_unsigned_2C_to_SM().
convert_SM_to_2C()
void sc_dt::sc_unsigned::convert_SM_to_2C () inline private
Definition at line 2019 of file sc_unsigned.hh.
References sc_dt::convert_unsigned_SM_to_2C(), sc_dt::operator<<(), and sc_dt::operator>>().
convert_SM_to_2C_to_SM()
void sc_dt::sc_unsigned::convert_SM_to_2C_to_SM () inline private
Definition at line 2014 of file sc_unsigned.hh.
References sc_dt::convert_unsigned_SM_to_2C_to_SM().
copy_digits()
void sc_dt::sc_unsigned::copy_digits (int nb, int nd, const sc_digit * d) inline private
Definition at line 1998 of file sc_unsigned.hh.
References sc_dt::copy_digits_unsigned().
default_sign()
small_type sc_dt::sc_unsigned::default_sign () const inline private
Definition at line 1991 of file sc_unsigned.hh.
References SC_POS.
dump()
void sc_dt::sc_unsigned::dump (::std::ostream & os = ::std::cout) const
get_packed_rep()
void sc_dt::sc_unsigned::get_packed_rep (sc_digit * buf) const
get_raw()
sc_digit* sc_dt::sc_unsigned::get_raw () const inline
Definition at line 974 of file sc_unsigned.hh.
invalid_index()
void sc_dt::sc_unsigned::invalid_index (int i) const
Definition at line 131 of file sc_unsigned.cc.
invalid_init()
void sc_dt::sc_unsigned::invalid_init (const char * type_name, int nb) const private
Definition at line 118 of file sc_unsigned.cc.
References sc_core::SC_ID_INIT_FAILED_, and SC_REPORT_ERROR.
invalid_range()
void sc_dt::sc_unsigned::invalid_range (int l, int r) const
Definition at line 141 of file sc_unsigned.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
invert()
void sc_dt::sc_unsigned::invert (int i) inline
Definition at line 1151 of file sc_unsigned.hh.
References ArmISA::i, sc_dt::operator+(), sc_dt::reverse(), and ArmISA::u.
iszero()
bool sc_dt::sc_unsigned::iszero () const
Definition at line 2164 of file sc_unsigned.cc.
References sc_dt::check_for_zero(), ArmISA::d, SC_NEG, SC_ZERO, sc_dt::trim_unsigned(), sc_dt::vec_complement(), and sc_dt::vec_copy().
Referenced by sc_dt::scfx_rep::scfx_rep().
length()
int sc_dt::sc_unsigned::length () const inline
Definition at line 1126 of file sc_unsigned.hh.
Referenced by sc_dt::assign_v_(), sc_core::sc_int_sigref::concat_set(), sc_dt::sc_uint_bitref::concat_set(), sc_dt::sc_int_bitref::concat_set(), sc_core::sc_uint_sigref::concat_set(), sc_dt::sc_uint_subref::concat_set(), sc_dt::sc_int_subref::concat_set(), sc_dt::sc_uint_base::concat_set(), sc_dt::sc_int_base::concat_set(), concat_set(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), and sc_dt::scfx_rep::scfx_rep().
makezero()
void sc_dt::sc_unsigned::makezero () inline private
Definition at line 2003 of file sc_unsigned.hh.
References sc_dt::make_zero().
nand_reduce()
bool sc_dt::sc_unsigned::nand_reduce () const inline
Definition at line 1132 of file sc_unsigned.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
nor_reduce()
bool sc_dt::sc_unsigned::nor_reduce () const inline
Definition at line 1134 of file sc_unsigned.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
num_bits()
int sc_dt::sc_unsigned::num_bits (int nb) const inline private
Definition at line 1993 of file sc_unsigned.hh.
Referenced by sc_dt::sc_concatref::value().
operator%=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (const sc_signed & v)
operator%=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (const sc_unsigned & v)
operator%=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (int64 v)
operator%=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (uint64 v)
operator%=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (long v)
operator%=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (unsigned long v)
operator%=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (int v) inline
Definition at line 1424 of file sc_unsigned.hh.
operator%=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator%= (unsigned int v) inline
Definition at line 1426 of file sc_unsigned.hh.
References sc_dt::operator%(), and sc_dt::operator&().
operator%=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator%= (const sc_int_base & v)
Definition at line 616 of file sc_unsigned.cc.
References sc_dt::operator&=(), and ArmISA::v.
operator%=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator%= (const sc_uint_base & v)
Definition at line 803 of file sc_unsigned.cc.
operator&=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (const sc_signed & v)
operator&=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (const sc_unsigned & v)
operator&=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (int64 v)
operator&=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (uint64 v)
operator&=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (long v)
operator&=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (unsigned long v)
operator&=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (int v) inline
Definition at line 1475 of file sc_unsigned.hh.
References operator&=().
Referenced by operator&=().
operator&=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (unsigned int v) inline
Definition at line 1477 of file sc_unsigned.hh.
References sc_dt::operator&(), sc_dt::operator&=(), and sc_dt::operator|().
operator&=() [9/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (const sc_int_base & v)
operator&=() [10/10]
const sc_unsigned& sc_dt::sc_unsigned::operator &= (const sc_uint_base & v)
operator()() [1/2]
sc_unsigned_subref& sc_dt::sc_unsigned::operator() (int i, int j) inline
Definition at line 1085 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_subref_r::initialize(), and sc_dt::sc_unsigned_subref::m_pool.
operator()() [2/2]
const sc_unsigned_subref_r& sc_dt::sc_unsigned::operator() (int i, int j) const inline
Definition at line 1094 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_subref_r::initialize(), sc_dt::sc_unsigned_subref::m_pool, sc_dt::SC_DEC, and sc_dt::to_string().
operator*=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (const sc_signed & v)
operator*=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (const sc_unsigned & v)
operator*=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (int64 v)
operator*=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (uint64 v)
operator*=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (long v)
operator*=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (unsigned long v)
operator*=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (int v) inline
Definition at line 1326 of file sc_unsigned.hh.
operator*=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator*= (unsigned int v) inline
Definition at line 1328 of file sc_unsigned.hh.
References sc_dt::operator*(), and sc_dt::operator/().
operator*=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator*= (const sc_int_base & v)
Definition at line 604 of file sc_unsigned.cc.
operator*=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator*= (const sc_uint_base & v)
Definition at line 771 of file sc_unsigned.cc.
operator++() [1/2]
sc_unsigned& sc_dt::sc_unsigned::operator++ ()
operator++() [2/2]
const sc_unsigned sc_dt::sc_unsigned::operator++ (int)
operator+=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (const sc_signed & v)
operator+=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (const sc_unsigned & v)
operator+=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (int64 v)
operator+=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (uint64 v)
operator+=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (long v)
operator+=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (unsigned long v)
operator+=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (int v) inline
Definition at line 1231 of file sc_unsigned.hh.
operator+=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator+= (unsigned int v) inline
Definition at line 1236 of file sc_unsigned.hh.
References sc_dt::operator+(), and sc_dt::operator-().
operator+=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator+= (const sc_int_base & v)
Definition at line 592 of file sc_unsigned.cc.
operator+=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator+= (const sc_uint_base & v)
Definition at line 749 of file sc_unsigned.cc.
operator--() [1/2]
sc_unsigned& sc_dt::sc_unsigned::operator-- ()
operator--() [2/2]
const sc_unsigned sc_dt::sc_unsigned::operator-- (int)
operator-=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (const sc_signed & v)
operator-=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (const sc_unsigned & v)
operator-=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (int64 v)
operator-=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (uint64 v)
operator-=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (long v)
operator-=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (unsigned long v)
operator-=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (int v) inline
Definition at line 1276 of file sc_unsigned.hh.
operator-=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator-= (unsigned int v) inline
Definition at line 1281 of file sc_unsigned.hh.
References sc_dt::operator*(), and sc_dt::operator-().
operator-=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator-= (const sc_int_base & v)
Definition at line 598 of file sc_unsigned.cc.
operator-=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator-= (const sc_uint_base & v)
Definition at line 755 of file sc_unsigned.cc.
operator/=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (const sc_signed & v)
operator/=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (const sc_unsigned & v)
operator/=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (int64 v)
operator/=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (uint64 v)
operator/=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (long v)
operator/=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (unsigned long v)
operator/=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (int v) inline
Definition at line 1375 of file sc_unsigned.hh.
operator/=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator/= (unsigned int v) inline
Definition at line 1377 of file sc_unsigned.hh.
References sc_dt::operator%(), and sc_dt::operator/().
operator/=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator/= (const sc_int_base & v)
Definition at line 610 of file sc_unsigned.cc.
operator/=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator/= (const sc_uint_base & v)
Definition at line 787 of file sc_unsigned.cc.
operator<<=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (const sc_signed & v)
operator<<=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (const sc_unsigned & v)
operator<<=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (int64 v)
operator<<=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (uint64 v)
operator<<=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (long v)
operator<<=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (unsigned long v)
operator<<=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (int v) inline
Definition at line 1622 of file sc_unsigned.hh.
operator<<=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator<<= (unsigned int v) inline
Definition at line 1624 of file sc_unsigned.hh.
References sc_dt::operator<<(), and sc_dt::operator>>().
operator<<=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator<<= (const sc_int_base & v)
Definition at line 645 of file sc_unsigned.cc.
operator<<=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator<<= (const sc_uint_base & v)
Definition at line 862 of file sc_unsigned.cc.
operator=() [1/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (const sc_unsigned & v)
Referenced by sc_dt::sc_biguint< W >::operator=(), and sc_core::sc_signal< sc_dt::sc_biguint< W > >::update().
operator=() [2/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (const sc_unsigned_subref_r & a)
operator=() [3/21]
template<class T > const sc_unsigned& sc_dt::sc_unsigned::operator= (const sc_generic_base< T > & a) inline
Definition at line 926 of file sc_unsigned.hh.
References ArmISA::a, and ArmISA::v.
operator=() [4/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (const sc_signed & v)
operator=() [5/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (const sc_signed_subref_r & a)
operator=() [6/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const char * v)
Definition at line 439 of file sc_unsigned.cc.
References PowerISA::aa, ArmISA::len, length, sc_core::SC_ID_CONVERSION_FAILED_, sc_dt::SC_ON, SC_REPORT_ERROR, sc_dt::SC_TRN, and sc_dt::SC_WRAP.
operator=() [7/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (int64 v)
Definition at line 460 of file sc_unsigned.cc.
References sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [8/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (uint64 v)
Definition at line 473 of file sc_unsigned.cc.
References sc_dt::from_uint(), SC_POS, SC_ZERO, and sc_dt::vec_zero().
operator=() [9/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (long v)
Definition at line 487 of file sc_unsigned.cc.
References sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [10/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (unsigned long v)
Definition at line 500 of file sc_unsigned.cc.
References sc_dt::from_uint(), SC_POS, SC_ZERO, and sc_dt::vec_zero().
operator=() [11/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (int v) inline
Definition at line 942 of file sc_unsigned.hh.
operator=() [12/21]
const sc_unsigned& sc_dt::sc_unsigned::operator= (unsigned int v) inline
Definition at line 948 of file sc_unsigned.hh.
operator=() [13/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (double v)
Definition at line 514 of file sc_unsigned.cc.
References DIGIT_MASK, DIGIT_RADIX, ArmISA::i, sc_dt::is_bad_double(), sc_dt::remainder, SC_POS, and sc_dt::vec_zero().
operator=() [14/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_int_base & v)
Definition at line 586 of file sc_unsigned.cc.
operator=() [15/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_uint_base & v)
Definition at line 733 of file sc_unsigned.cc.
operator=() [16/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_bv_base & v)
Definition at line 533 of file sc_unsigned.cc.
References sc_dt::sc_bv_base::get_bit(), ArmISA::i, sc_dt::sc_bv_base::length(), sc_dt::safe_set(), and sc_dt::sc_min().
operator=() [17/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_lv_base & v)
Definition at line 548 of file sc_unsigned.cc.
References sc_dt::sc_lv_base::get_bit(), ArmISA::i, sc_dt::sc_lv_base::length(), sc_dt::safe_set(), sc_dt::sc_min(), and to_bool().
operator=() [18/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_fxval & v) inline
Definition at line 131 of file scfx_other_defs.hh.
References sc_dt::sc_fxval::get_bit(), ArmISA::i, sc_dt::sc_fxval::is_normal(), sc_dt::sc_signed::length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [19/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_fxval_fast & v) inline
Definition at line 146 of file scfx_other_defs.hh.
References sc_dt::sc_fxval_fast::get_bit(), ArmISA::i, sc_dt::sc_fxval_fast::is_normal(), sc_dt::sc_signed::length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [20/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_fxnum & v) inline
Definition at line 161 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::is_normal(), sc_dt::sc_signed::length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [21/21]
const sc_unsigned & sc_dt::sc_unsigned::operator= (const sc_fxnum_fast & v) inline
Definition at line 176 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::is_normal(), sc_dt::sc_signed::length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator>>=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (const sc_signed & v)
operator>>=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (const sc_unsigned & v)
operator>>=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (int64 v)
operator>>=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (uint64 v)
operator>>=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (long v)
operator>>=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (unsigned long v)
operator>>=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (int v) inline
Definition at line 1663 of file sc_unsigned.hh.
operator>>=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator>>= (unsigned int v) inline
Definition at line 1665 of file sc_unsigned.hh.
References sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator==(), and sc_dt::operator>>().
operator>>=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator>>= (const sc_int_base & v)
Definition at line 656 of file sc_unsigned.cc.
operator>>=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator>>= (const sc_uint_base & v)
Definition at line 873 of file sc_unsigned.cc.
operator[]() [1/2]
sc_unsigned_bitref& sc_dt::sc_unsigned::operator[] (int i) inline
Definition at line 1009 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_bitref_r::initialize(), and sc_dt::sc_unsigned_bitref::m_pool.
operator[]() [2/2]
const sc_unsigned_bitref_r& sc_dt::sc_unsigned::operator[] (int i) const inline
Definition at line 1018 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_bitref_r::initialize(), and sc_dt::sc_unsigned_bitref::m_pool.
operator^=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (const sc_signed & v)
operator^=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (const sc_unsigned & v)
operator^=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (int64 v)
operator^=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (uint64 v)
operator^=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (long v)
operator^=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (unsigned long v)
operator^=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (int v) inline
Definition at line 1574 of file sc_unsigned.hh.
References sc_dt::operator^=().
operator^=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator^= (unsigned int v) inline
Definition at line 1579 of file sc_unsigned.hh.
References sc_dt::operator<<(), sc_dt::operator^(), and sc_dt::operator^=().
operator^=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator^= (const sc_int_base & v)
Definition at line 634 of file sc_unsigned.cc.
References sc_dt::operator^=().
operator^=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator^= (const sc_uint_base & v)
Definition at line 851 of file sc_unsigned.cc.
References sc_dt::operator^=().
operator|=() [1/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (const sc_signed & v)
operator|=() [2/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (const sc_unsigned & v)
operator|=() [3/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (int64 v)
operator|=() [4/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (uint64 v)
operator|=() [5/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (long v)
operator|=() [6/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (unsigned long v)
operator|=() [7/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (int v) inline
Definition at line 1524 of file sc_unsigned.hh.
References operator|=().
Referenced by operator|=().
operator|=() [8/10]
const sc_unsigned& sc_dt::sc_unsigned::operator|= (unsigned int v) inline
Definition at line 1526 of file sc_unsigned.hh.
References sc_dt::operator^(), sc_dt::operator|(), and sc_dt::operator|=().
operator|=() [9/10]
const sc_unsigned & sc_dt::sc_unsigned::operator|= (const sc_int_base & v)
Definition at line 628 of file sc_unsigned.cc.
References sc_dt::operator|=().
operator|=() [10/10]
const sc_unsigned & sc_dt::sc_unsigned::operator|= (const sc_uint_base & v)
Definition at line 835 of file sc_unsigned.cc.
References sc_dt::operator|=().
or_reduce()
bool sc_dt::sc_unsigned::or_reduce () const
Definition at line 414 of file sc_unsigned.cc.
References SC_ZERO.
print()
void sc_dt::sc_unsigned::print (::std::ostream & os = ::std::cout) const inline
Definition at line 1117 of file sc_unsigned.hh.
References Stats::dump(), MipsISA::is, X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
range() [1/2]
sc_unsigned_subref& sc_dt::sc_unsigned::range (int i, int j) inline
Definition at line 1067 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_subref_r::initialize(), and sc_dt::sc_unsigned_subref::m_pool.
range() [2/2]
const sc_unsigned_subref_r& sc_dt::sc_unsigned::range (int i, int j) const inline
Definition at line 1076 of file sc_unsigned.hh.
References sc_dt::sc_unsigned_subref_r::initialize(), and sc_dt::sc_unsigned_subref::m_pool.
reverse()
void sc_dt::sc_unsigned::reverse ()
scan()
void sc_dt::sc_unsigned::scan (::std::istream & is = ::std::cin)
Referenced by sc_dt::operator>>().
set() [1/2]
void sc_dt::sc_unsigned::set (int i)
set() [2/2]
void sc_dt::sc_unsigned::set (int i, bool v) inline
Definition at line 1143 of file sc_unsigned.hh.
References ArmISA::i.
set_packed_rep()
void sc_dt::sc_unsigned::set_packed_rep (sc_digit * buf)
sign()
bool sc_dt::sc_unsigned::sign () const inline
Definition at line 1128 of file sc_unsigned.hh.
References sc_dt::and_reduce().
test()
bool sc_dt::sc_unsigned::test (int i) const
Referenced by sc_dt::sc_unsigned_subref_r::and_reduce(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_unsigned_subref_r::or_reduce(), and sc_dt::sc_unsigned_subref_r::xor_reduce().
to_double()
double sc_dt::sc_unsigned::to_double () const
to_int()
int sc_dt::sc_unsigned::to_int () const
to_int64()
int64 sc_dt::sc_unsigned::to_int64 () const
Referenced by sc_dt::sc_int_base::sc_int_base().
to_long()
long sc_dt::sc_unsigned::to_long () const
to_string() [1/2]
const std::string sc_dt::sc_unsigned::to_string (sc_numrep numrep = SC_DEC) const
Definition at line 565 of file sc_unsigned.cc.
References PowerISA::aa, ArmISA::len, length, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_string() [2/2]
const std::string sc_dt::sc_unsigned::to_string (sc_numrep numrep, bool w_prefix) const
Definition at line 573 of file sc_unsigned.cc.
References PowerISA::aa, ArmISA::len, length, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_uint()
unsigned int sc_dt::sc_unsigned::to_uint () const
to_uint64()
uint64 sc_dt::sc_unsigned::to_uint64 () const
Referenced by sc_core::sc_int_sigref::operator=(), sc_core::sc_uint_sigref::operator=(), sc_core::sc_inout< sc_dt::sc_int< W > >::operator=(), sc_core::sc_inout< sc_dt::sc_uint< W > >::operator=(), and sc_dt::sc_uint_base::sc_uint_base().
to_ulong()
unsigned long sc_dt::sc_unsigned::to_ulong () const
Referenced by sc_dt::operator<<(), and sc_dt::operator>>().
xnor_reduce()
bool sc_dt::sc_unsigned::xnor_reduce () const inline
Definition at line 1136 of file sc_unsigned.hh.
References ArmISA::i, and sc_dt::xor_reduce().
xor_reduce()
bool sc_dt::sc_unsigned::xor_reduce () const
Definition at line 420 of file sc_unsigned.cc.
References ArmISA::i.
Friends And Related Function Documentation
add_unsigned_friend
sc_unsigned add_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
and_unsigned_friend
sc_unsigned and_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
compare_unsigned
int compare_unsigned (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd, small_type if_u_signed, small_type if_v_signed) friend
Definition at line 2109 of file sc_unsigned.cc.
div_unsigned_friend
sc_unsigned div_unsigned_friend (small_type s, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
mod_unsigned_friend
sc_unsigned mod_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
mul_unsigned_friend
sc_unsigned mul_unsigned_friend (small_type s, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
operator!= [1/19]
bool operator!= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1877 of file sc_unsigned.cc.
operator!= [2/19]
bool operator!= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1884 of file sc_unsigned.cc.
operator!= [3/19]
bool operator!= (const sc_unsigned & u, const sc_unsigned & v) friend
operator!= [4/19]
bool operator!= (const sc_unsigned & u, int64 v) friend
operator!= [5/19]
bool operator!= (const sc_unsigned & u, uint64 v) friend
operator!= [6/19]
bool operator!= (const sc_unsigned & u, long v) friend
operator!= [7/19]
bool operator!= (const sc_unsigned & u, unsigned long v) friend
operator!= [8/19]
bool operator!= (const sc_unsigned & u, int v) friend
Definition at line 1731 of file sc_unsigned.hh.
operator!= [9/19]
bool operator!= (const sc_unsigned & u, unsigned int v) friend
Definition at line 1736 of file sc_unsigned.hh.
operator!= [10/19]
bool operator!= (int64 u, const sc_unsigned & v) friend
operator!= [11/19]
bool operator!= (uint64 u, const sc_unsigned & v) friend
operator!= [12/19]
bool operator!= (long u, const sc_unsigned & v) friend
operator!= [13/19]
bool operator!= (unsigned long u, const sc_unsigned & v) friend
operator!= [14/19]
bool operator!= (int u, const sc_unsigned & v) friend
Definition at line 1746 of file sc_unsigned.hh.
operator!= [15/19]
bool operator!= (unsigned int u, const sc_unsigned & v) friend
Definition at line 1751 of file sc_unsigned.hh.
operator!= [16/19]
bool operator!= (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 890 of file sc_unsigned.cc.
operator!= [17/19]
bool operator!= (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 673 of file sc_unsigned.cc.
operator!= [18/19]
bool operator!= (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 895 of file sc_unsigned.cc.
operator!= [19/19]
bool operator!= (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 678 of file sc_unsigned.cc.
operator% [1/19]
sc_signed operator% (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2439 of file sc_signed.cc.
operator% [2/19]
sc_signed operator% (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2453 of file sc_signed.cc.
operator% [3/19]
sc_unsigned operator% (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1319 of file sc_unsigned.cc.
operator% [4/19]
sc_signed operator% (const sc_unsigned & u, int64 v) friend
Definition at line 2517 of file sc_signed.cc.
operator% [5/19]
sc_unsigned operator% (const sc_unsigned & u, uint64 v) friend
Definition at line 1333 of file sc_unsigned.cc.
operator% [6/19]
sc_signed operator% (const sc_unsigned & u, long v) friend
Definition at line 2621 of file sc_signed.cc.
operator% [7/19]
sc_unsigned operator% (const sc_unsigned & u, unsigned long v) friend
Definition at line 1366 of file sc_unsigned.cc.
operator% [8/19]
sc_signed operator% (const sc_unsigned & u, int v) friend
Definition at line 1624 of file sc_signed.hh.
operator% [9/19]
sc_unsigned operator% (const sc_unsigned & u, unsigned int v) friend
Definition at line 1402 of file sc_unsigned.hh.
operator% [10/19]
sc_signed operator% (int64 u, const sc_unsigned & v) friend
Definition at line 2535 of file sc_signed.cc.
operator% [11/19]
sc_unsigned operator% (uint64 u, const sc_unsigned & v) friend
Definition at line 1350 of file sc_unsigned.cc.
operator% [12/19]
sc_signed operator% (long u, const sc_unsigned & v) friend
Definition at line 2640 of file sc_signed.cc.
operator% [13/19]
sc_unsigned operator% (unsigned long u, const sc_unsigned & v) friend
Definition at line 1382 of file sc_unsigned.cc.
operator% [14/19]
sc_signed operator% (int u, const sc_unsigned & v) friend
Definition at line 1632 of file sc_signed.hh.
operator% [15/19]
sc_unsigned operator% (unsigned int u, const sc_unsigned & v) friend
Definition at line 1413 of file sc_unsigned.hh.
operator% [16/19]
sc_unsigned operator% (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 793 of file sc_unsigned.cc.
operator% [17/19]
sc_signed operator% (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 729 of file sc_signed.cc.
operator% [18/19]
sc_unsigned operator% (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 798 of file sc_unsigned.cc.
operator% [19/19]
sc_signed operator% (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 735 of file sc_signed.cc.
operator& [1/19]
sc_signed operator & (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2704 of file sc_signed.cc.
operator& [2/19]
sc_signed operator & (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2716 of file sc_signed.cc.
operator& [3/19]
sc_unsigned operator & (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1412 of file sc_unsigned.cc.
operator& [4/19]
sc_signed operator & (const sc_unsigned & u, int64 v) friend
Definition at line 2768 of file sc_signed.cc.
operator& [5/19]
sc_unsigned operator & (const sc_unsigned & u, uint64 v) friend
Definition at line 1424 of file sc_unsigned.cc.
operator& [6/19]
sc_signed operator & (const sc_unsigned & u, long v) friend
Definition at line 2852 of file sc_signed.cc.
operator& [7/19]
sc_unsigned operator & (const sc_unsigned & u, unsigned long v) friend
Definition at line 1452 of file sc_unsigned.cc.
operator& [8/19]
sc_signed operator & (const sc_unsigned & u, int v) friend
Definition at line 1703 of file sc_signed.hh.
operator& [9/19]
sc_unsigned operator & (const sc_unsigned & u, unsigned int v) friend
Definition at line 1453 of file sc_unsigned.hh.
operator& [10/19]
sc_signed operator & (int64 u, const sc_unsigned & v) friend
Definition at line 2782 of file sc_signed.cc.
operator& [11/19]
sc_unsigned operator & (uint64 u, const sc_unsigned & v) friend
Definition at line 1438 of file sc_unsigned.cc.
operator& [12/19]
sc_signed operator & (long u, const sc_unsigned & v) friend
Definition at line 2866 of file sc_signed.cc.
operator& [13/19]
sc_unsigned operator & (unsigned long u, const sc_unsigned & v) friend
Definition at line 1466 of file sc_unsigned.cc.
operator& [14/19]
sc_signed operator & (int u, const sc_unsigned & v) friend
Definition at line 1711 of file sc_signed.hh.
operator& [15/19]
sc_unsigned operator & (unsigned int u, const sc_unsigned & v) friend
Definition at line 1464 of file sc_unsigned.hh.
operator& [16/19]
sc_unsigned operator & (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 809 of file sc_unsigned.cc.
operator& [17/19]
sc_signed operator & (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 760 of file sc_signed.cc.
operator& [18/19]
sc_unsigned operator & (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 814 of file sc_unsigned.cc.
operator& [19/19]
sc_signed operator & (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 766 of file sc_signed.cc.
operator* [1/19]
sc_signed operator* (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1910 of file sc_signed.cc.
operator* [2/19]
sc_signed operator* (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1924 of file sc_signed.cc.
operator* [3/19]
sc_unsigned operator* (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1122 of file sc_unsigned.cc.
operator* [4/19]
sc_signed operator* (const sc_unsigned & u, int64 v) friend
Definition at line 1984 of file sc_signed.cc.
operator* [5/19]
sc_unsigned operator* (const sc_unsigned & u, uint64 v) friend
Definition at line 1136 of file sc_unsigned.cc.
operator* [6/19]
sc_signed operator* (const sc_unsigned & u, long v) friend
Definition at line 2080 of file sc_signed.cc.
operator* [7/19]
sc_unsigned operator* (const sc_unsigned & u, unsigned long v) friend
Definition at line 1168 of file sc_unsigned.cc.
operator* [8/19]
sc_signed operator* (const sc_unsigned & u, int v) friend
Definition at line 1470 of file sc_signed.hh.
operator* [9/19]
sc_unsigned operator* (const sc_unsigned & u, unsigned int v) friend
Definition at line 1304 of file sc_unsigned.hh.
operator* [10/19]
sc_signed operator* (int64 u, const sc_unsigned & v) friend
Definition at line 2000 of file sc_signed.cc.
operator* [11/19]
sc_unsigned operator* (uint64 u, const sc_unsigned & v) friend
Definition at line 1152 of file sc_unsigned.cc.
operator* [12/19]
sc_signed operator* (long u, const sc_unsigned & v) friend
Definition at line 2096 of file sc_signed.cc.
operator* [13/19]
sc_unsigned operator* (unsigned long u, const sc_unsigned & v) friend
Definition at line 1183 of file sc_unsigned.cc.
operator* [14/19]
sc_signed operator* (int u, const sc_unsigned & v) friend
Definition at line 1478 of file sc_signed.hh.
operator* [15/19]
sc_unsigned operator* (unsigned int u, const sc_unsigned & v) friend
Definition at line 1315 of file sc_unsigned.hh.
operator* [16/19]
sc_unsigned operator* (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 761 of file sc_unsigned.cc.
operator* [17/19]
sc_signed operator* (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 667 of file sc_signed.cc.
operator* [18/19]
sc_unsigned operator* (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 766 of file sc_unsigned.cc.
operator* [19/19]
sc_signed operator* (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 673 of file sc_signed.cc.
operator+ [1/20]
sc_signed operator+ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1294 of file sc_signed.cc.
operator+ [2/20]
sc_signed operator+ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1309 of file sc_signed.cc.
operator+ [3/20]
sc_unsigned operator+ (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1004 of file sc_unsigned.cc.
operator+ [4/20]
sc_signed operator+ (const sc_unsigned & u, int64 v) friend
Definition at line 1373 of file sc_signed.cc.
operator+ [5/20]
sc_unsigned operator+ (const sc_unsigned & u, uint64 v) friend
Definition at line 1019 of file sc_unsigned.cc.
operator+ [6/20]
sc_signed operator+ (const sc_unsigned & u, long v) friend
Definition at line 1475 of file sc_signed.cc.
operator+ [7/20]
sc_unsigned operator+ (const sc_unsigned & u, unsigned long v) friend
Definition at line 1053 of file sc_unsigned.cc.
operator+ [8/20]
sc_signed operator+ (const sc_unsigned & u, int v) friend
Definition at line 1299 of file sc_signed.hh.
operator+ [9/20]
sc_unsigned operator+ (const sc_unsigned & u, unsigned int v) friend
Definition at line 1208 of file sc_unsigned.hh.
operator+ [10/20]
sc_signed operator+ (int64 u, const sc_unsigned & v) friend
Definition at line 1390 of file sc_signed.cc.
operator+ [11/20]
sc_unsigned operator+ (uint64 u, const sc_unsigned & v) friend
Definition at line 1036 of file sc_unsigned.cc.
operator+ [12/20]
sc_signed operator+ (long u, const sc_unsigned & v) friend
Definition at line 1492 of file sc_signed.cc.
operator+ [13/20]
sc_unsigned operator+ (unsigned long u, const sc_unsigned & v) friend
Definition at line 1070 of file sc_unsigned.cc.
operator+ [14/20]
sc_signed operator+ (int u, const sc_unsigned & v) friend
Definition at line 1307 of file sc_signed.hh.
operator+ [15/20]
sc_unsigned operator+ (unsigned int u, const sc_unsigned & v) friend
Definition at line 1219 of file sc_unsigned.hh.
operator+ [16/20]
sc_unsigned operator+ (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 739 of file sc_unsigned.cc.
operator+ [17/20]
sc_signed operator+ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 605 of file sc_signed.cc.
operator+ [18/20]
sc_unsigned operator+ (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 744 of file sc_unsigned.cc.
operator+ [19/20]
sc_signed operator+ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 611 of file sc_signed.cc.
operator+ [20/20]
sc_unsigned operator+ (const sc_unsigned & u) friend
Definition at line 1725 of file sc_unsigned.cc.
operator- [1/20]
sc_signed operator- (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1579 of file sc_signed.cc.
operator- [2/20]
sc_signed operator- (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1594 of file sc_signed.cc.
operator- [3/20]
sc_signed operator- (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1564 of file sc_signed.cc.
operator- [4/20]
sc_signed operator- (const sc_unsigned & u, int64 v) friend
Definition at line 1658 of file sc_signed.cc.
operator- [5/20]
sc_signed operator- (const sc_unsigned & u, uint64 v) friend
Definition at line 1727 of file sc_signed.cc.
operator- [6/20]
sc_signed operator- (const sc_unsigned & u, long v) friend
Definition at line 1795 of file sc_signed.cc.
operator- [7/20]
sc_signed operator- (const sc_unsigned & u, unsigned long v) friend
Definition at line 1863 of file sc_signed.cc.
operator- [8/20]
sc_signed operator- (const sc_unsigned & u, int v) friend
Definition at line 1379 of file sc_signed.hh.
operator- [9/20]
sc_signed operator- (const sc_unsigned & u, unsigned int v) friend
Definition at line 1384 of file sc_signed.hh.
operator- [10/20]
sc_signed operator- (int64 u, const sc_unsigned & v) friend
Definition at line 1675 of file sc_signed.cc.
operator- [11/20]
sc_signed operator- (uint64 u, const sc_unsigned & v) friend
Definition at line 1744 of file sc_signed.cc.
operator- [12/20]
sc_signed operator- (long u, const sc_unsigned & v) friend
Definition at line 1812 of file sc_signed.cc.
operator- [13/20]
sc_signed operator- (unsigned long u, const sc_unsigned & v) friend
Definition at line 1880 of file sc_signed.cc.
operator- [14/20]
sc_signed operator- (int u, const sc_unsigned & v) friend
Definition at line 1394 of file sc_signed.hh.
operator- [15/20]
sc_signed operator- (unsigned int u, const sc_unsigned & v) friend
Definition at line 1399 of file sc_signed.hh.
operator- [16/20]
sc_signed operator- (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 987 of file sc_signed.cc.
operator- [17/20]
sc_signed operator- (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 636 of file sc_signed.cc.
operator- [18/20]
sc_signed operator- (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 993 of file sc_signed.cc.
operator- [19/20]
sc_signed operator- (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 642 of file sc_signed.cc.
operator- [20/20]
sc_signed operator- (const sc_unsigned & u) friend
Definition at line 3497 of file sc_signed.cc.
operator/ [1/19]
sc_signed operator/ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2158 of file sc_signed.cc.
operator/ [2/19]
sc_signed operator/ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2174 of file sc_signed.cc.
operator/ [3/19]
sc_unsigned operator/ (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1214 of file sc_unsigned.cc.
operator/ [4/19]
sc_signed operator/ (const sc_unsigned & u, int64 v) friend
Definition at line 2242 of file sc_signed.cc.
operator/ [5/19]
sc_unsigned operator/ (const sc_unsigned & u, uint64 v) friend
Definition at line 1230 of file sc_unsigned.cc.
operator/ [6/19]
sc_signed operator/ (const sc_unsigned & u, long v) friend
Definition at line 2351 of file sc_signed.cc.
operator/ [7/19]
sc_unsigned operator/ (const sc_unsigned & u, unsigned long v) friend
Definition at line 1267 of file sc_unsigned.cc.
operator/ [8/19]
sc_signed operator/ (const sc_unsigned & u, int v) friend
Definition at line 1547 of file sc_signed.hh.
operator/ [9/19]
sc_unsigned operator/ (const sc_unsigned & u, unsigned int v) friend
Definition at line 1353 of file sc_unsigned.hh.
operator/ [10/19]
sc_signed operator/ (int64 u, const sc_unsigned & v) friend
Definition at line 2260 of file sc_signed.cc.
operator/ [11/19]
sc_unsigned operator/ (uint64 u, const sc_unsigned & v) friend
Definition at line 1248 of file sc_unsigned.cc.
operator/ [12/19]
sc_signed operator/ (long u, const sc_unsigned & v) friend
Definition at line 2369 of file sc_signed.cc.
operator/ [13/19]
sc_unsigned operator/ (unsigned long u, const sc_unsigned & v) friend
Definition at line 1285 of file sc_unsigned.cc.
operator/ [14/19]
sc_signed operator/ (int u, const sc_unsigned & v) friend
Definition at line 1555 of file sc_signed.hh.
operator/ [15/19]
sc_unsigned operator/ (unsigned int u, const sc_unsigned & v) friend
Definition at line 1364 of file sc_unsigned.hh.
operator/ [16/19]
sc_unsigned operator/ (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 777 of file sc_unsigned.cc.
operator/ [17/19]
sc_signed operator/ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 698 of file sc_signed.cc.
operator/ [18/19]
sc_unsigned operator/ (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 782 of file sc_unsigned.cc.
operator/ [19/19]
sc_signed operator/ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 704 of file sc_signed.cc.
operator< [1/19]
bool operator< (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1910 of file sc_unsigned.cc.
operator< [2/19]
bool operator< (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1923 of file sc_unsigned.cc.
operator< [3/19]
bool operator< (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1897 of file sc_unsigned.cc.
operator< [4/19]
bool operator< (const sc_unsigned & u, int64 v) friend
Definition at line 1936 of file sc_unsigned.cc.
operator< [5/19]
bool operator< (const sc_unsigned & u, uint64 v) friend
Definition at line 1964 of file sc_unsigned.cc.
operator< [6/19]
bool operator< (const sc_unsigned & u, long v) friend
Definition at line 1988 of file sc_unsigned.cc.
operator< [7/19]
bool operator< (const sc_unsigned & u, unsigned long v) friend
Definition at line 2016 of file sc_unsigned.cc.
operator< [8/19]
bool operator< (const sc_unsigned & u, int v) friend
Definition at line 1771 of file sc_unsigned.hh.
operator< [9/19]
bool operator< (const sc_unsigned & u, unsigned int v) friend
Definition at line 1776 of file sc_unsigned.hh.
operator< [10/19]
bool operator< (int64 u, const sc_unsigned & v) friend
Definition at line 1950 of file sc_unsigned.cc.
operator< [11/19]
bool operator< (uint64 u, const sc_unsigned & v) friend
Definition at line 1976 of file sc_unsigned.cc.
operator< [12/19]
bool operator< (long u, const sc_unsigned & v) friend
Definition at line 2002 of file sc_unsigned.cc.
operator< [13/19]
bool operator< (unsigned long u, const sc_unsigned & v) friend
Definition at line 2028 of file sc_unsigned.cc.
operator< [14/19]
bool operator< (int u, const sc_unsigned & v) friend
Definition at line 1786 of file sc_unsigned.hh.
operator< [15/19]
bool operator< (unsigned int u, const sc_unsigned & v) friend
Definition at line 1791 of file sc_unsigned.hh.
operator< [16/19]
bool operator< (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 901 of file sc_unsigned.cc.
operator< [17/19]
bool operator< (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 684 of file sc_unsigned.cc.
operator< [18/19]
bool operator< (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 906 of file sc_unsigned.cc.
operator< [19/19]
bool operator< (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 689 of file sc_unsigned.cc.
operator<< [1/11]
sc_unsigned operator<< (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1689 of file sc_unsigned.cc.
operator<< [2/11]
sc_signed operator<< (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3451 of file sc_signed.cc.
operator<< [3/11]
sc_unsigned operator<< (const sc_unsigned & u, const sc_unsigned & v) friend
operator<< [4/11]
sc_unsigned operator<< (const sc_unsigned & u, int64 v) friend
operator<< [5/11]
sc_unsigned operator<< (const sc_unsigned & u, uint64 v) friend
operator<< [6/11]
sc_unsigned operator<< (const sc_unsigned & u, long v) friend
operator<< [7/11]
sc_unsigned operator<< (const sc_unsigned & u, unsigned long v) friend
operator<< [8/11]
sc_unsigned operator<< (const sc_unsigned & u, int v) friend
Definition at line 1606 of file sc_unsigned.hh.
operator<< [9/11]
sc_unsigned operator<< (const sc_unsigned & u, unsigned int v) friend
Definition at line 1611 of file sc_unsigned.hh.
operator<< [10/11]
sc_unsigned operator<< (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 857 of file sc_unsigned.cc.
operator<< [11/11]
sc_unsigned operator<< (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 640 of file sc_unsigned.cc.
operator<= [1/19]
bool operator<= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2044 of file sc_unsigned.cc.
operator<= [2/19]
bool operator<= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2051 of file sc_unsigned.cc.
operator<= [3/19]
bool operator<= (const sc_unsigned & u, const sc_unsigned & v) friend
operator<= [4/19]
bool operator<= (const sc_unsigned & u, int64 v) friend
operator<= [5/19]
bool operator<= (const sc_unsigned & u, uint64 v) friend
operator<= [6/19]
bool operator<= (const sc_unsigned & u, long v) friend
operator<= [7/19]
bool operator<= (const sc_unsigned & u, unsigned long v) friend
operator<= [8/19]
bool operator<= (const sc_unsigned & u, int v) friend
Definition at line 1811 of file sc_unsigned.hh.
operator<= [9/19]
bool operator<= (const sc_unsigned & u, unsigned int v) friend
Definition at line 1816 of file sc_unsigned.hh.
operator<= [10/19]
bool operator<= (int64 u, const sc_unsigned & v) friend
operator<= [11/19]
bool operator<= (uint64 u, const sc_unsigned & v) friend
operator<= [12/19]
bool operator<= (long u, const sc_unsigned & v) friend
operator<= [13/19]
bool operator<= (unsigned long u, const sc_unsigned & v) friend
operator<= [14/19]
bool operator<= (int u, const sc_unsigned & v) friend
Definition at line 1826 of file sc_unsigned.hh.
operator<= [15/19]
bool operator<= (unsigned int u, const sc_unsigned & v) friend
Definition at line 1831 of file sc_unsigned.hh.
operator<= [16/19]
bool operator<= (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 912 of file sc_unsigned.cc.
operator<= [17/19]
bool operator<= (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 695 of file sc_unsigned.cc.
operator<= [18/19]
bool operator<= (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 917 of file sc_unsigned.cc.
operator<= [19/19]
bool operator<= (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 700 of file sc_unsigned.cc.
operator== [1/19]
bool operator== (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1749 of file sc_unsigned.cc.
operator== [2/19]
bool operator== (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1762 of file sc_unsigned.cc.
operator== [3/19]
bool operator== (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1736 of file sc_unsigned.cc.
operator== [4/19]
bool operator== (const sc_unsigned & u, int64 v) friend
Definition at line 1775 of file sc_unsigned.cc.
operator== [5/19]
bool operator== (const sc_unsigned & u, uint64 v) friend
Definition at line 1803 of file sc_unsigned.cc.
operator== [6/19]
bool operator== (const sc_unsigned & u, long v) friend
Definition at line 1825 of file sc_unsigned.cc.
operator== [7/19]
bool operator== (const sc_unsigned & u, unsigned long v) friend
Definition at line 1851 of file sc_unsigned.cc.
operator== [8/19]
bool operator== (const sc_unsigned & u, int v) friend
Definition at line 1691 of file sc_unsigned.hh.
operator== [9/19]
bool operator== (const sc_unsigned & u, unsigned int v) friend
Definition at line 1696 of file sc_unsigned.hh.
operator== [10/19]
bool operator== (int64 u, const sc_unsigned & v) friend
Definition at line 1789 of file sc_unsigned.cc.
operator== [11/19]
bool operator== (uint64 u, const sc_unsigned & v) friend
Definition at line 1814 of file sc_unsigned.cc.
operator== [12/19]
bool operator== (long u, const sc_unsigned & v) friend
Definition at line 1838 of file sc_unsigned.cc.
operator== [13/19]
bool operator== (unsigned long u, const sc_unsigned & v) friend
Definition at line 1862 of file sc_unsigned.cc.
operator== [14/19]
bool operator== (int u, const sc_unsigned & v) friend
Definition at line 1706 of file sc_unsigned.hh.
operator== [15/19]
bool operator== (unsigned int u, const sc_unsigned & v) friend
Definition at line 1711 of file sc_unsigned.hh.
operator== [16/19]
bool operator== (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 879 of file sc_unsigned.cc.
operator== [17/19]
bool operator== (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 662 of file sc_unsigned.cc.
operator== [18/19]
bool operator== (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 884 of file sc_unsigned.cc.
operator== [19/19]
bool operator== (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 667 of file sc_unsigned.cc.
operator> [1/19]
bool operator> (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2064 of file sc_unsigned.cc.
operator> [2/19]
bool operator> (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2071 of file sc_unsigned.cc.
operator> [3/19]
bool operator> (const sc_unsigned & u, const sc_unsigned & v) friend
operator> [4/19]
bool operator> (const sc_unsigned & u, int64 v) friend
operator> [5/19]
bool operator> (const sc_unsigned & u, uint64 v) friend
operator> [6/19]
bool operator> (const sc_unsigned & u, long v) friend
operator> [7/19]
bool operator> (const sc_unsigned & u, unsigned long v) friend
operator> [8/19]
bool operator> (const sc_unsigned & u, int v) friend
Definition at line 1851 of file sc_unsigned.hh.
operator> [9/19]
bool operator> (const sc_unsigned & u, unsigned int v) friend
Definition at line 1856 of file sc_unsigned.hh.
operator> [10/19]
bool operator> (int64 u, const sc_unsigned & v) friend
operator> [11/19]
bool operator> (uint64 u, const sc_unsigned & v) friend
operator> [12/19]
bool operator> (long u, const sc_unsigned & v) friend
operator> [13/19]
bool operator> (unsigned long u, const sc_unsigned & v) friend
operator> [14/19]
bool operator> (int u, const sc_unsigned & v) friend
Definition at line 1866 of file sc_unsigned.hh.
operator> [15/19]
bool operator> (unsigned int u, const sc_unsigned & v) friend
Definition at line 1871 of file sc_unsigned.hh.
operator> [16/19]
bool operator> (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 923 of file sc_unsigned.cc.
operator> [17/19]
bool operator> (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 706 of file sc_unsigned.cc.
operator> [18/19]
bool operator> (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 928 of file sc_unsigned.cc.
operator> [19/19]
bool operator> (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 711 of file sc_unsigned.cc.
operator>= [1/19]
bool operator>= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2084 of file sc_unsigned.cc.
operator>= [2/19]
bool operator>= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2091 of file sc_unsigned.cc.
operator>= [3/19]
bool operator>= (const sc_unsigned & u, const sc_unsigned & v) friend
operator>= [4/19]
bool operator>= (const sc_unsigned & u, int64 v) friend
operator>= [5/19]
bool operator>= (const sc_unsigned & u, uint64 v) friend
operator>= [6/19]
bool operator>= (const sc_unsigned & u, long v) friend
operator>= [7/19]
bool operator>= (const sc_unsigned & u, unsigned long v) friend
operator>= [8/19]
bool operator>= (const sc_unsigned & u, int v) friend
Definition at line 1891 of file sc_unsigned.hh.
operator>= [9/19]
bool operator>= (const sc_unsigned & u, unsigned int v) friend
Definition at line 1896 of file sc_unsigned.hh.
operator>= [10/19]
bool operator>= (int64 u, const sc_unsigned & v) friend
operator>= [11/19]
bool operator>= (uint64 u, const sc_unsigned & v) friend
operator>= [12/19]
bool operator>= (long u, const sc_unsigned & v) friend
operator>= [13/19]
bool operator>= (unsigned long u, const sc_unsigned & v) friend
operator>= [14/19]
bool operator>= (int u, const sc_unsigned & v) friend
Definition at line 1906 of file sc_unsigned.hh.
operator>= [15/19]
bool operator>= (unsigned int u, const sc_unsigned & v) friend
Definition at line 1911 of file sc_unsigned.hh.
operator>= [16/19]
bool operator>= (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 934 of file sc_unsigned.cc.
operator>= [17/19]
bool operator>= (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 717 of file sc_unsigned.cc.
operator>= [18/19]
bool operator>= (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 939 of file sc_unsigned.cc.
operator>= [19/19]
bool operator>= (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 722 of file sc_unsigned.cc.
operator>> [1/11]
sc_unsigned operator>> (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1706 of file sc_unsigned.cc.
operator>> [2/11]
sc_signed operator>> (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3468 of file sc_signed.cc.
operator>> [3/11]
sc_unsigned operator>> (const sc_unsigned & u, const sc_unsigned & v) friend
operator>> [4/11]
sc_unsigned operator>> (const sc_unsigned & u, int64 v) friend
operator>> [5/11]
sc_unsigned operator>> (const sc_unsigned & u, uint64 v) friend
operator>> [6/11]
sc_unsigned operator>> (const sc_unsigned & u, long v) friend
operator>> [7/11]
sc_unsigned operator>> (const sc_unsigned & u, unsigned long v) friend
operator>> [8/11]
sc_unsigned operator>> (const sc_unsigned & u, int v) friend
Definition at line 1647 of file sc_unsigned.hh.
operator>> [9/11]
sc_unsigned operator>> (const sc_unsigned & u, unsigned int v) friend
Definition at line 1652 of file sc_unsigned.hh.
operator>> [10/11]
sc_unsigned operator>> (const sc_unsigned & , const sc_uint_base &) friend
Definition at line 868 of file sc_unsigned.cc.
operator>> [11/11]
sc_unsigned operator>> (const sc_unsigned & , const sc_int_base &) friend
Definition at line 651 of file sc_unsigned.cc.
operator^ [1/19]
sc_signed operator^ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 3188 of file sc_signed.cc.
operator^ [2/19]
sc_signed operator^ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3205 of file sc_signed.cc.
operator^ [3/19]
sc_unsigned operator^ (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1594 of file sc_unsigned.cc.
operator^ [4/19]
sc_signed operator^ (const sc_unsigned & u, int64 v) friend
Definition at line 3269 of file sc_signed.cc.
operator^ [5/19]
sc_unsigned operator^ (const sc_unsigned & u, uint64 v) friend
Definition at line 1609 of file sc_unsigned.cc.
operator^ [6/19]
sc_signed operator^ (const sc_unsigned & u, long v) friend
Definition at line 3370 of file sc_signed.cc.
operator^ [7/19]
sc_unsigned operator^ (const sc_unsigned & u, unsigned long v) friend
Definition at line 1642 of file sc_unsigned.cc.
operator^ [8/19]
sc_signed operator^ (const sc_unsigned & u, int v) friend
Definition at line 1851 of file sc_signed.hh.
operator^ [9/19]
sc_unsigned operator^ (const sc_unsigned & u, unsigned int v) friend
Definition at line 1551 of file sc_unsigned.hh.
operator^ [10/19]
sc_signed operator^ (int64 u, const sc_unsigned & v) friend
Definition at line 3286 of file sc_signed.cc.
operator^ [11/19]
sc_unsigned operator^ (uint64 u, const sc_unsigned & v) friend
Definition at line 1625 of file sc_unsigned.cc.
operator^ [12/19]
sc_signed operator^ (long u, const sc_unsigned & v) friend
Definition at line 3387 of file sc_signed.cc.
operator^ [13/19]
sc_unsigned operator^ (unsigned long u, const sc_unsigned & v) friend
Definition at line 1658 of file sc_unsigned.cc.
operator^ [14/19]
sc_signed operator^ (int u, const sc_unsigned & v) friend
Definition at line 1859 of file sc_signed.hh.
operator^ [15/19]
sc_unsigned operator^ (unsigned int u, const sc_unsigned & v) friend
Definition at line 1562 of file sc_unsigned.hh.
operator^ [16/19]
sc_unsigned operator^ (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 841 of file sc_unsigned.cc.
operator^ [17/19]
sc_signed operator^ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 822 of file sc_signed.cc.
operator^ [18/19]
sc_unsigned operator^ (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 846 of file sc_unsigned.cc.
operator^ [19/19]
sc_signed operator^ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 828 of file sc_signed.cc.
operator| [1/19]
sc_signed operator| (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2923 of file sc_signed.cc.
operator| [2/19]
sc_signed operator| (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2938 of file sc_signed.cc.
operator| [3/19]
sc_unsigned operator| (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1495 of file sc_unsigned.cc.
operator| [4/19]
sc_signed operator| (const sc_unsigned & u, int64 v) friend
Definition at line 3002 of file sc_signed.cc.
operator| [5/19]
sc_unsigned operator| (const sc_unsigned & u, uint64 v) friend
Definition at line 1510 of file sc_unsigned.cc.
operator| [6/19]
sc_signed operator| (const sc_unsigned & u, long v) friend
Definition at line 3104 of file sc_signed.cc.
operator| [7/19]
sc_unsigned operator| (const sc_unsigned & u, unsigned long v) friend
Definition at line 1544 of file sc_unsigned.cc.
operator| [8/19]
sc_signed operator| (const sc_unsigned & u, int v) friend
Definition at line 1774 of file sc_signed.hh.
operator| [9/19]
sc_unsigned operator| (const sc_unsigned & u, unsigned int v) friend
Definition at line 1502 of file sc_unsigned.hh.
operator| [10/19]
sc_signed operator| (int64 u, const sc_unsigned & v) friend
Definition at line 3019 of file sc_signed.cc.
operator| [11/19]
sc_unsigned operator| (uint64 u, const sc_unsigned & v) friend
Definition at line 1527 of file sc_unsigned.cc.
operator| [12/19]
sc_signed operator| (long u, const sc_unsigned & v) friend
Definition at line 3121 of file sc_signed.cc.
operator| [13/19]
sc_unsigned operator| (unsigned long u, const sc_unsigned & v) friend
Definition at line 1561 of file sc_unsigned.cc.
operator| [14/19]
sc_signed operator| (int u, const sc_unsigned & v) friend
Definition at line 1782 of file sc_signed.hh.
operator| [15/19]
sc_unsigned operator| (unsigned int u, const sc_unsigned & v) friend
Definition at line 1513 of file sc_unsigned.hh.
operator| [16/19]
sc_unsigned operator| (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 825 of file sc_unsigned.cc.
operator| [17/19]
sc_signed operator| (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 791 of file sc_signed.cc.
operator| [18/19]
sc_unsigned operator| (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 830 of file sc_unsigned.cc.
operator| [19/19]
sc_signed operator| (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 797 of file sc_signed.cc.
operator~
sc_unsigned operator~ (const sc_unsigned & u) friend
or_unsigned_friend
sc_unsigned or_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
sc_concatref
friend class sc_concatref friend
Definition at line 892 of file sc_unsigned.hh.
sc_signed
friend class sc_signed friend
Definition at line 897 of file sc_unsigned.hh.
sc_signed_subref
friend class sc_signed_subref friend
Definition at line 898 of file sc_unsigned.hh.
sc_signed_subref_r
friend class sc_signed_subref_r friend
Definition at line 899 of file sc_unsigned.hh.
sc_unsigned_bitref
friend class sc_unsigned_bitref friend
Definition at line 894 of file sc_unsigned.hh.
sc_unsigned_bitref_r
friend class sc_unsigned_bitref_r friend
Definition at line 893 of file sc_unsigned.hh.
sc_unsigned_subref
friend class sc_unsigned_subref friend
Definition at line 896 of file sc_unsigned.hh.
sc_unsigned_subref_r
friend class sc_unsigned_subref_r friend
Definition at line 895 of file sc_unsigned.hh.
sub_unsigned_friend
sc_unsigned sub_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
xor_unsigned_friend
sc_unsigned xor_unsigned_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
Member Data Documentation
digit
sc_digit* sc_dt::sc_unsigned::digit private
Definition at line 1973 of file sc_unsigned.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), sc_dt::operator|(), and sc_dt::sc_concatref::value().
m_pool
sc_core::sc_vpool< sc_unsigned > sc_dt::sc_unsigned::m_pool static
Definition at line 1963 of file sc_unsigned.hh.
Referenced by sc_dt::sc_concatref::value().
nbits
int sc_dt::sc_unsigned::nbits private
Definition at line 1967 of file sc_unsigned.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), sc_dt::operator|(), and sc_dt::sc_concatref::value().
ndigits
int sc_dt::sc_unsigned::ndigits private
Definition at line 1968 of file sc_unsigned.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), sc_dt::operator|(), and sc_dt::sc_concatref::value().
sgn
small_type sc_dt::sc_unsigned::sgn private
Definition at line 1966 of file sc_unsigned.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator<<(), sc_dt::operator==(), sc_dt::operator>(), sc_dt::operator>=(), sc_dt::operator>>(), sc_dt::operator^(), sc_dt::operator|(), and sc_dt::sc_concatref::value().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_unsigned.hh
systemc/dt/int/sc_unsigned.cc
systemc/ext/dt/fx/scfx_other_defs.hh