gem5: Minor::LSQ Class Reference
Minor::LSQ Class Reference
#include <lsq.hh>
Classes
class BarrierDataRequest
Request for doing barrier accounting in the store buffer.
class DcachePort
Exposable data port.
class FailedDataRequest
FailedDataRequest represents requests from instructions that failed their predicates but need to ride the requests/transfers queues to maintain trace ordering.
class LSQRequest
Derived SenderState to carry data access info.
class SingleDataRequest
SingleDataRequest is used for requests that don't fragment.
class SpecialDataRequest
Special request types that don't actually issue memory requests.
class SplitDataRequest
class StoreBuffer
Store buffer.
Public Types
typedef LSQRequest * LSQRequestPtr
typedef Queue< LSQRequestPtr, ReportTraitsPtrAdaptor< LSQRequestPtr >, NoBubbleTraits< LSQRequestPtr > > LSQQueue
The LSQ consists of three queues: requests, transfers and the store buffer storeBuffer.
Public Member Functions
LSQ (std::string name_, std::string dcache_port_name_, MinorCPU &cpu_, Execute &execute_, unsigned int max_accesses_in_memory_system, unsigned int line_width, unsigned int requests_queue_size, unsigned int transfers_queue_size, unsigned int store_buffer_size, unsigned int store_buffer_cycle_store_limit)
virtual ~LSQ ()
void step ()
Step checks the queues to see if their are issuable transfers which were not otherwise picked up by tests at the end of other events.
bool canRequest ()
Is their space in the request queue to be able to push a request by issuing an isMemRef instruction.
LSQRequestPtr findResponse (MinorDynInstPtr inst)
Returns a response if it's at the head of the transfers queue and it's either complete or can be sent on to the store buffer.
void popResponse (LSQRequestPtr response)
Sanity check and pop the head response.
bool canPushIntoStoreBuffer () const
Must check this before trying to insert into the store buffer.
void sendStoreToStoreBuffer (LSQRequestPtr request)
A store has been committed, please move it to the store buffer.
bool accessesInFlight () const
Are there any accesses other than normal cached loads in the memory system or having received responses which need to be handled for their instruction's to be completed.
void issuedMemBarrierInst (MinorDynInstPtr inst)
A memory barrier instruction has been issued, remember its execSeqNum that we can avoid issuing memory ops until it is committed.
InstSeqNum getLastMemBarrier (ThreadID thread_id) const
Get the execSeqNum of the last issued memory barrier.
bool isDrained ()
Is there nothing left in the LSQ.
bool needsToTick ()
May need to be ticked next cycle as one of the queues contains an actionable transfers or address translation.
void completeMemBarrierInst (MinorDynInstPtr inst, bool committed)
Complete a barrier instruction.
Fault pushRequest (MinorDynInstPtr inst, bool isLoad, uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, AtomicOpFunctorPtr amo_op, const std::vector< bool > &byteEnable=std::vector< bool >())
Single interface for readMem/writeMem/amoMem to issue requests into the LSQ.
void pushFailedRequest (MinorDynInstPtr inst)
Push a predicate failed-representing request into the queues just to maintain commit order.
bool recvTimingResp (PacketPtr pkt)
Memory interface.
void recvReqRetry ()
void recvTimingSnoopReq (PacketPtr pkt)
MinorCPU::MinorCPUPort & getDcachePort ()
Return the raw-bindable port.
void minorTrace () const
Public Member Functions inherited from Named
Named (const std::string &name_)
const std::string & name () const
Public Attributes
MemoryState state
Retry state of last issued memory transfer.
const unsigned int inMemorySystemLimit
Maximum number of in-flight accesses issued to the memory system.
const unsigned int lineWidth
Memory system access width (and snap) in bytes.
LSQQueue requests
requests contains LSQRequests which have been issued to the TLB by calling ExecContext::readMem/writeMem (which in turn calls LSQ::pushRequest and LSQRequest::startAddrTranslation).
LSQQueue transfers
Once issued to memory (or, for stores, just had their state changed to StoreToStoreBuffer) LSQRequests pass through transfers waiting for memory responses.
StoreBuffer storeBuffer
Protected Types
enum MemoryState { MemoryRunning, MemoryNeedsRetry }
State of memory access for head access.
enum AddrRangeCoverage { PartialAddrRangeCoverage, FullAddrRangeCoverage, NoAddrRangeCoverage }
Coverage of one address range with another.
Protected Member Functions
void tryToSendToTransfers (LSQRequestPtr request)
Try and issue a memory access for a translated request at the head of the requests queue.
bool tryToSend (LSQRequestPtr request)
Try to send (or resend) a memory request's next/only packet to the memory system.
void clearMemBarrier (MinorDynInstPtr inst)
Clear a barrier (if it's the last one marked up in lastMemBarrier)
void moveFromRequestsToTransfers (LSQRequestPtr request)
Move a request between queues.
bool canSendToMemorySystem ()
Can a request be sent to the memory system.
void threadSnoop (LSQRequestPtr request)
Snoop other threads monitors on memory system accesses.
Protected Attributes
MinorCPU & cpu
My owner(s)
Execute & execute
DcachePort dcachePort
std::vector< InstSeqNum > lastMemBarrier
Most recent execSeqNum of a memory barrier instruction or 0 if there are no in-flight barriers.
unsigned int numAccessesInMemorySystem
Count of the number of mem.
unsigned int numAccessesInDTLB
Number of requests in the DTLB in the requests queue.
unsigned int numStoresInTransfers
The number of stores in the transfers queue.
unsigned int numAccessesIssuedToMemory
The number of accesses which have been issued to the memory system but have not been committed/discarded excluding cacheable normal loads which don't need to be tracked.
LSQRequestPtr retryRequest
The request (from either requests or the store buffer) which is currently waiting have its memory access retried.
Addr cacheBlockMask
Address Mask for a cache block (e.g.
Protected Attributes inherited from Named
const std::string _name
Friends
std::ostream & operator<< (std::ostream &os, MemoryState state)
Print MemoryState values as shown in the enum definition.
std::ostream & operator<< (std::ostream &os, AddrRangeCoverage state)
std::ostream & operator<< (std::ostream &os, LSQRequest::LSQRequestState state)
Detailed Description
Definition at line 61 of file lsq.hh.
Member Typedef Documentation
LSQQueue
typedef Queue<LSQRequestPtr, ReportTraitsPtrAdaptor<LSQRequestPtr>, NoBubbleTraits<LSQRequestPtr> > Minor::LSQ::LSQQueue
The LSQ consists of three queues: requests, transfers and the store buffer storeBuffer.
Definition at line 554 of file lsq.hh.
LSQRequestPtr
typedef LSQRequest* Minor::LSQ::LSQRequestPtr
Definition at line 268 of file lsq.hh.
Member Enumeration Documentation
AddrRangeCoverage
enum Minor::LSQ::AddrRangeCoverage protected
Coverage of one address range with another.
Enumerator
PartialAddrRangeCoverage
FullAddrRangeCoverage
NoAddrRangeCoverage
Definition at line 81 of file lsq.hh.
MemoryState
enum Minor::LSQ::MemoryState protected
State of memory access for head access.
Enumerator
MemoryRunning
MemoryNeedsRetry
Definition at line 70 of file lsq.hh.
Constructor & Destructor Documentation
LSQ()
LSQ< Impl >::LSQ (std::string name_, std::string dcache_port_name_, MinorCPU & cpu_, Execute & execute_, unsigned int max_accesses_in_memory_system, unsigned int line_width, unsigned int requests_queue_size, unsigned int transfers_queue_size, unsigned int store_buffer_size, unsigned int store_buffer_cycle_store_limit)
Definition at line 1393 of file lsq.cc.
References fatal, lineWidth, and Named::name().
~LSQ()
LSQ< Impl >::~LSQ () virtual
Definition at line 1448 of file lsq.cc.
Member Function Documentation
accessesInFlight()
bool Minor::LSQ::accessesInFlight () const inline
Are there any accesses other than normal cached loads in the memory system or having received responses which need to be handled for their instruction's to be completed.
Definition at line 683 of file lsq.hh.
References issuedMemBarrierInst().
Referenced by Minor::Execute::isInbetweenInsts(), and Minor::Execute::takeInterrupt().
canPushIntoStoreBuffer()
bool Minor::LSQ::canPushIntoStoreBuffer () const inline
Must check this before trying to insert into the store buffer.
Definition at line 675 of file lsq.hh.
References Minor::LSQ::StoreBuffer::canInsert(), and sendStoreToStoreBuffer().
Referenced by Minor::Execute::commitInst().
canRequest()
bool Minor::LSQ::canRequest () inline
Is their space in the request queue to be able to push a request by issuing an isMemRef instruction.
Definition at line 663 of file lsq.hh.
References findResponse(), popResponse(), and Minor::Queue< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace().
Referenced by Minor::Execute::commit(), Minor::Execute::executeMemRefInst(), and Minor::Execute::getCommittingThread().
canSendToMemorySystem()
bool LSQ< Impl >::canSendToMemorySystem () protected
Can a request be sent to the memory system.
Definition at line 1280 of file lsq.cc.
References inMemorySystemLimit, MemoryRunning, numAccessesInMemorySystem, and Minor::LSQ::LSQRequest::state.
Referenced by needsToTick(), tryToSend(), and tryToSendToTransfers().
clearMemBarrier()
void LSQ< Impl >::clearMemBarrier (MinorDynInstPtr inst) protected
Clear a barrier (if it's the last one marked up in lastMemBarrier)
Definition at line 250 of file lsq.cc.
References DPRINTF, and lastMemBarrier.
Referenced by completeMemBarrierInst().
completeMemBarrierInst()
void LSQ< Impl >::completeMemBarrierInst (MinorDynInstPtr inst, bool committed)
Complete a barrier instruction.
Where committed, makes a BarrierDataRequest and pushed it into the store buffer
Definition at line 913 of file lsq.cc.
References clearMemBarrier(), Minor::LSQ::StoreBuffer::insert(), and storeBuffer.
Referenced by Minor::Execute::commit(), and getLastMemBarrier().
findResponse()
LSQ::LSQRequestPtr LSQ< Impl >::findResponse (MinorDynInstPtr inst)
Returns a response if it's at the head of the transfers queue and it's either complete or can be sent on to the store buffer.
After calling, the request still remains on the transfer queue until popResponse is called
Definition at line 1477 of file lsq.cc.
References Minor::LSQ::StoreBuffer::canInsert(), DPRINTF, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isBarrier(), Minor::LSQ::LSQRequest::isComplete(), Minor::LSQ::LSQRequest::state, storeBuffer, Minor::LSQ::LSQRequest::StoreToStoreBuffer, and transfers.
Referenced by canRequest(), Minor::Execute::commit(), Minor::Execute::evaluate(), and Minor::Execute::getCommittingThread().
getDcachePort()
MinorCPU::MinorCPUPort& Minor::LSQ::getDcachePort () inline
Return the raw-bindable port.
Definition at line 725 of file lsq.hh.
References data, dcachePort, Minor::makePacketForRequest(), and minorTrace().
Referenced by Minor::Execute::getDcachePort().
getLastMemBarrier()
InstSeqNum Minor::LSQ::getLastMemBarrier (ThreadID thread_id) const inline
Get the execSeqNum of the last issued memory barrier.
Definition at line 692 of file lsq.hh.
References addr, completeMemBarrierInst(), data, isDrained(), needsToTick(), pushFailedRequest(), pushRequest(), Minor::LSQ::DcachePort::recvReqRetry(), Minor::LSQ::DcachePort::recvTimingResp(), and Minor::LSQ::DcachePort::recvTimingSnoopReq().
Referenced by Minor::Execute::commit(), and Minor::Execute::issue().
isDrained()
bool LSQ< Impl >::isDrained ()
Is there nothing left in the LSQ.
Definition at line 1547 of file lsq.cc.
References Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::LSQ::StoreBuffer::isDrained(), requests, storeBuffer, and transfers.
Referenced by getLastMemBarrier(), and Minor::Execute::isDrained().
issuedMemBarrierInst()
void LSQ< Impl >::issuedMemBarrierInst (MinorDynInstPtr inst)
A memory barrier instruction has been issued, remember its execSeqNum that we can avoid issuing memory ops until it is committed.
Definition at line 1700 of file lsq.cc.
References lastMemBarrier.
Referenced by accessesInFlight(), and Minor::Execute::issue().
minorTrace()
void LSQ< Impl >::minorTrace () const
Definition at line 1656 of file lsq.cc.
References lastMemBarrier, MINORTRACE, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::minorTrace(), Minor::LSQ::StoreBuffer::minorTrace(), numAccessesInDTLB, numAccessesInMemorySystem, numStoresInTransfers, requests, state, storeBuffer, and transfers.
Referenced by getDcachePort(), Minor::LSQ::StoreBuffer::isDrained(), and Minor::Execute::minorTrace().
moveFromRequestsToTransfers()
void LSQ< Impl >::moveFromRequestsToTransfers (LSQRequestPtr request) protected
Move a request between queues.
Definition at line 1263 of file lsq.cc.
References Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), Minor::LSQ::LSQRequest::isLoad, numStoresInTransfers, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::pop(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::push(), Minor::LSQ::LSQRequest::request, requests, transfers, and Minor::Queue< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace().
Referenced by recvReqRetry(), and tryToSendToTransfers().
needsToTick()
bool LSQ< Impl >::needsToTick ()
May need to be ticked next cycle as one of the queues contains an actionable transfers or address translation.
Definition at line 1554 of file lsq.cc.
References canSendToMemorySystem(), DPRINTF, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), Minor::LSQ::LSQRequest::InTranslation, Minor::LSQ::StoreBuffer::numUnissuedStores(), requests, Minor::LSQ::LSQRequest::state, storeBuffer, transfers, and Minor::Queue< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace().
Referenced by Minor::Execute::evaluate(), and getLastMemBarrier().
popResponse()
void LSQ< Impl >::popResponse (LSQ::LSQRequestPtr response)
Sanity check and pop the head response.
Definition at line 1512 of file lsq.cc.
References DPRINTF, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isLoad, Minor::LSQ::LSQRequest::issuedToMemory, numAccessesIssuedToMemory, numStoresInTransfers, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::pop(), Minor::LSQ::LSQRequest::state, Minor::LSQ::LSQRequest::StoreInStoreBuffer, and transfers.
Referenced by canRequest(), Minor::Execute::commit(), and Minor::Execute::handleMemResponse().
pushFailedRequest()
void LSQ< Impl >::pushFailedRequest (MinorDynInstPtr inst)
Push a predicate failed-representing request into the queues just to maintain commit order.
Definition at line 1649 of file lsq.cc.
References Minor::Queue< ElemType, ReportTraits, BubbleTraits >::push(), and requests.
Referenced by Minor::Execute::executeMemRefInst(), and getLastMemBarrier().
pushRequest()
Fault LSQ< Impl >::pushRequest (MinorDynInstPtr inst, bool isLoad, uint8_t * data, unsigned int size, Addr addr, Request::Flags flags, uint64_t * res, AtomicOpFunctorPtr amo_op, const std::vector< bool > & byteEnable = std::vector<bool>())
Single interface for readMem/writeMem/amoMem to issue requests into the LSQ.
Definition at line 1574 of file lsq.cc.
References cpu, BaseCPU::dataMasterId(), DPRINTF, lineWidth, NoFault, panic, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::push(), Minor::LSQ::LSQRequest::request, requests, Minor::LSQ::LSQRequest::startAddrTranslation(), Request::STORE_NO_DATA, MinorCPU::threads, and transferNeedsBurst().
Referenced by getLastMemBarrier(), Minor::ExecContext::initiateMemAMO(), Minor::ExecContext::initiateMemRead(), and Minor::ExecContext::writeMem().
recvReqRetry()
void LSQ< Impl >::recvReqRetry ()
Definition at line 1347 of file lsq.cc.
References Minor::LSQ::StoreBuffer::countIssuedStore(), DPRINTF, MemoryNeedsRetry, MemoryRunning, moveFromRequestsToTransfers(), panic, Minor::LSQ::LSQRequest::RequestIssuing, Minor::LSQ::LSQRequest::RequestNeedsRetry, retryRequest, Minor::LSQ::LSQRequest::setState(), Minor::LSQ::LSQRequest::state, storeBuffer, Minor::LSQ::LSQRequest::StoreBufferIssuing, Minor::LSQ::LSQRequest::StoreBufferNeedsRetry, Minor::LSQ::LSQRequest::StoreInStoreBuffer, Minor::LSQ::LSQRequest::Translated, and tryToSend().
Referenced by Minor::LSQ::DcachePort::recvReqRetry().
recvTimingResp()
bool LSQ< Impl >::recvTimingResp (PacketPtr pkt)
Memory interface.
Definition at line 1287 of file lsq.cc.
References Packet::cmd, cpu, Minor::LSQ::StoreBuffer::deleteRequest(), DPRINTF, Minor::Pipeline::ExecuteStageId, Packet::getAddr(), Minor::LSQ::LSQRequest::hasPacketsInMemSystem(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isBarrier(), Minor::LSQ::LSQRequest::isComplete(), Packet::isError(), numAccessesInMemorySystem, panic, Packet::popSenderState(), Minor::LSQ::LSQRequest::request, Minor::LSQ::LSQRequest::RequestIssuing, Minor::LSQ::LSQRequest::RequestNeedsRetry, Minor::LSQ::LSQRequest::retireResponse(), safe_cast(), Minor::LSQ::LSQRequest::state, storeBuffer, Minor::LSQ::LSQRequest::StoreBufferIssuing, Minor::LSQ::LSQRequest::StoreBufferNeedsRetry, MemCmd::toString(), and MinorCPU::wakeupOnEvent().
Referenced by Minor::LSQ::DcachePort::recvTimingResp().
recvTimingSnoopReq()
void LSQ< Impl >::recvTimingSnoopReq (PacketPtr pkt)
Definition at line 1745 of file lsq.cc.
References cacheBlockMask, cpu, AddressMonitor::doMonitor(), BaseCPU::getContext(), BaseCPU::getCpuAddrMonitor(), TheISA::handleLockedSnoop(), Packet::isInvalidate(), Packet::isWrite(), BaseCPU::numThreads, and MinorCPU::wakeup().
Referenced by Minor::LSQ::DcachePort::recvTimingSnoopReq().
sendStoreToStoreBuffer()
void LSQ< Impl >::sendStoreToStoreBuffer (LSQRequestPtr request)
A store has been committed, please move it to the store buffer.
Definition at line 1534 of file lsq.cc.
References DPRINTF, Minor::LSQ::StoreBuffer::insert(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::state, storeBuffer, and Minor::LSQ::LSQRequest::StoreToStoreBuffer.
Referenced by canPushIntoStoreBuffer(), and Minor::Execute::handleMemResponse().
step()
void LSQ< Impl >::step ()
Step checks the queues to see if their are issuable transfers which were not otherwise picked up by tests at the end of other events.
Step the memory access mechanism on to its next state.
Steppable actions include deferred actions which couldn't be cascaded on the end of a memory response/TLB response event because of resource congestion.
In reality, most of the stepping is done by the callbacks on the LSQ but this function is responsible for issuing memory requests lodged in the requests queue.
Definition at line 1466 of file lsq.cc.
References Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), requests, Minor::LSQ::StoreBuffer::step(), storeBuffer, and tryToSendToTransfers().
Referenced by Minor::Execute::evaluate(), and Minor::LSQ::StoreBuffer::isDrained().
threadSnoop()
void LSQ< Impl >::threadSnoop (LSQRequestPtr request) protected
Snoop other threads monitors on memory system accesses.
Definition at line 1765 of file lsq.cc.
References cacheBlockMask, cpu, AddressMonitor::doMonitor(), BaseCPU::getContext(), BaseCPU::getCpuAddrMonitor(), TheISA::handleLockedSnoop(), Minor::LSQ::LSQRequest::inst, Packet::isInvalidate(), Packet::isWrite(), BaseCPU::numThreads, Minor::LSQ::LSQRequest::packet, and MinorCPU::wakeup().
Referenced by tryToSend().
tryToSend()
bool LSQ< Impl >::tryToSend (LSQRequestPtr request) protected
Try to send (or resend) a memory request's next/only packet to the memory system.
Returns true if the request was successfully sent to memory (and was also the last packet in a transfer)
Definition at line 1164 of file lsq.cc.
References canSendToMemorySystem(), Minor::LSQ::LSQRequest::Complete, BaseCPU::contextToThread(), cpu, dcachePort, DPRINTF, Packet::findNextSenderState(), BaseCPU::getContext(), Minor::LSQ::LSQRequest::getHeadPacket(), GenericISA::handleIprRead(), GenericISA::handleIprWrite(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isLoad, MemoryNeedsRetry, MemoryRunning, numAccessesInMemorySystem, Minor::LSQ::LSQRequest::packet, panic, Packet::req, Minor::LSQ::LSQRequest::request, Minor::LSQ::LSQRequest::RequestIssuing, Minor::LSQ::LSQRequest::RequestNeedsRetry, retryRequest, MasterPort::sendTimingReq(), Minor::LSQ::LSQRequest::sentAllPackets(), Minor::LSQ::LSQRequest::setState(), Minor::LSQ::LSQRequest::state, Minor::LSQ::LSQRequest::stepToNextPacket(), Minor::LSQ::LSQRequest::StoreBufferIssuing, Minor::LSQ::LSQRequest::StoreBufferNeedsRetry, Minor::LSQ::LSQRequest::StoreInStoreBuffer, threadSnoop(), and Minor::LSQ::LSQRequest::Translated.
Referenced by recvReqRetry(), and tryToSendToTransfers().
tryToSendToTransfers()
void LSQ< Impl >::tryToSendToTransfers (LSQRequestPtr request) protected
Try and issue a memory access for a translated request at the head of the requests queue.
Also tries to move the request between queues
Definition at line 959 of file lsq.cc.
References cacheBlockMask, Minor::LSQ::StoreBuffer::canForwardDataToLoad(), canSendToMemorySystem(), Minor::LSQ::LSQRequest::Complete, cpu, DPRINTF, Minor::Queue< ElemType, ReportTraits, BubbleTraits >::empty(), execute, Minor::LSQ::LSQRequest::Failed, Minor::LSQ::StoreBuffer::forwardStoreData(), Minor::Queue< ElemType, ReportTraits, BubbleTraits >::front(), FullAddrRangeCoverage, TheISA::handleLockedRead(), TheISA::handleLockedWrite(), Minor::LSQ::LSQRequest::hasPacketsInMemSystem(), Minor::LSQ::LSQRequest::inst, Minor::Execute::instIsHeadInst(), Minor::Execute::instIsRightStream(), Minor::LSQ::LSQRequest::InTranslation, Minor::LSQ::LSQRequest::isComplete(), Minor::LSQ::LSQRequest::isLoad, Minor::LSQ::LSQRequest::issuedToMemory, Packet::makeResponse(), MemoryNeedsRetry, moveFromRequestsToTransfers(), NoAddrRangeCoverage, NoFault, numAccessesIssuedToMemory, numStoresInTransfers, Minor::LSQ::LSQRequest::packet, PartialAddrRangeCoverage, SimpleThread::pcState(), Minor::LSQ::LSQRequest::request, Minor::LSQ::LSQRequest::RequestIssuing, requests, Minor::LSQ::LSQRequest::setSkipped(), Minor::LSQ::LSQRequest::setState(), Minor::LSQ::LSQRequest::state, storeBuffer, Minor::LSQ::LSQRequest::StoreToStoreBuffer, MinorCPU::threads, transfers, Minor::LSQ::LSQRequest::Translated, tryToSend(), and Minor::Queue< ElemType, ReportTraits, BubbleTraits >::unreservedRemainingSpace().
Referenced by Minor::LSQ::SingleDataRequest::finish(), Minor::LSQ::SplitDataRequest::finish(), and step().
Friends And Related Function Documentation
operator<< [1/3]
std::ostream& operator<< (std::ostream & os, LSQ::MemoryState state) friend
Print MemoryState values as shown in the enum definition.
Definition at line 1728 of file lsq.cc.
operator<< [2/3]
std::ostream& operator<< (std::ostream & os, LSQ::AddrRangeCoverage coverage) friend
Definition at line 186 of file lsq.cc.
operator<< [3/3]
std::ostream& operator<< (std::ostream & os, LSQRequest::LSQRequestState state) friend
Definition at line 206 of file lsq.cc.
Member Data Documentation
cacheBlockMask
Addr Minor::LSQ::cacheBlockMask protected
Address Mask for a cache block (e.g.
~(cache_block_size-1))
Definition at line 616 of file lsq.hh.
Referenced by recvTimingSnoopReq(), threadSnoop(), and tryToSendToTransfers().
cpu
MinorCPU& Minor::LSQ::cpu protected
My owner(s)
Definition at line 65 of file lsq.hh.
Referenced by Minor::LSQ::LSQRequest::completeDisabledMemAccess(), Minor::LSQ::LSQRequest::disableMemAccess(), Minor::LSQ::SingleDataRequest::finish(), Minor::LSQ::SplitDataRequest::finish(), pushRequest(), recvTimingResp(), recvTimingSnoopReq(), Minor::LSQ::SplitDataRequest::sendNextFragmentToTranslation(), Minor::LSQ::SingleDataRequest::startAddrTranslation(), threadSnoop(), tryToSend(), tryToSendToTransfers(), and Minor::LSQ::LSQRequest::tryToSuppressFault().
dcachePort
DcachePort Minor::LSQ::dcachePort protected
Definition at line 114 of file lsq.hh.
Referenced by getDcachePort(), and tryToSend().
execute
Execute& Minor::LSQ::execute protected
Definition at line 66 of file lsq.hh.
Referenced by Minor::LSQ::LSQRequest::completeDisabledMemAccess(), tryToSendToTransfers(), and Minor::LSQ::LSQRequest::tryToSuppressFault().
inMemorySystemLimit
const unsigned int Minor::LSQ::inMemorySystemLimit
Maximum number of in-flight accesses issued to the memory system.
Definition at line 542 of file lsq.hh.
Referenced by canSendToMemorySystem().
lastMemBarrier
std::vector<InstSeqNum> Minor::LSQ::lastMemBarrier protected
Most recent execSeqNum of a memory barrier instruction or 0 if there are no in-flight barriers.
Useful as a dependency for early-issued memory operations
Definition at line 535 of file lsq.hh.
Referenced by clearMemBarrier(), issuedMemBarrierInst(), and minorTrace().
lineWidth
const unsigned int Minor::LSQ::lineWidth
Memory system access width (and snap) in bytes.
Definition at line 545 of file lsq.hh.
Referenced by LSQ(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), and pushRequest().
numAccessesInDTLB
unsigned int Minor::LSQ::numAccessesInDTLB protected
Number of requests in the DTLB in the requests queue.
Definition at line 600 of file lsq.hh.
Referenced by Minor::LSQ::SingleDataRequest::finish(), Minor::LSQ::SplitDataRequest::finish(), minorTrace(), Minor::LSQ::SplitDataRequest::sendNextFragmentToTranslation(), and Minor::LSQ::SingleDataRequest::startAddrTranslation().
numAccessesInMemorySystem
unsigned int Minor::LSQ::numAccessesInMemorySystem protected
Count of the number of mem.
accesses which have left the requests queue and are in the 'wild' in the memory system and who must not be interrupted as they are not normal cacheable accesses. This is a count of the number of in-flight requests with issuedToMemory set who have visited tryToSendRequest at least once
Definition at line 597 of file lsq.hh.
Referenced by canSendToMemorySystem(), minorTrace(), recvTimingResp(), and tryToSend().
numAccessesIssuedToMemory
unsigned int Minor::LSQ::numAccessesIssuedToMemory protected
The number of accesses which have been issued to the memory system but have not been committed/discarded excluding cacheable normal loads which don't need to be tracked.
Definition at line 609 of file lsq.hh.
Referenced by popResponse(), and tryToSendToTransfers().
numStoresInTransfers
unsigned int Minor::LSQ::numStoresInTransfers protected
The number of stores in the transfers queue.
Useful when testing if the store buffer contains all the forwardable stores
Definition at line 604 of file lsq.hh.
Referenced by minorTrace(), moveFromRequestsToTransfers(), popResponse(), and tryToSendToTransfers().
requests
LSQQueue Minor::LSQ::requests
requests contains LSQRequests which have been issued to the TLB by calling ExecContext::readMem/writeMem (which in turn calls LSQ::pushRequest and LSQRequest::startAddrTranslation).
Once they have a physical address, requests at the head of requests can be issued to the memory system. At this stage, it cannot be clear that memory accesses must happen (that there are no preceding faults or changes of flow of control) and so only cacheable reads are issued to memory. Cacheable stores are not issued at all (and just pass through 'transfers' in order) and all other transfers are stalled in requests until their corresponding instructions are at the head of the inMemInsts instruction queue and have the right streamSeqNum.
Definition at line 568 of file lsq.hh.
Referenced by isDrained(), minorTrace(), moveFromRequestsToTransfers(), needsToTick(), pushFailedRequest(), pushRequest(), step(), and tryToSendToTransfers().
retryRequest
LSQRequestPtr Minor::LSQ::retryRequest protected
The request (from either requests or the store buffer) which is currently waiting have its memory access retried.
Definition at line 613 of file lsq.hh.
Referenced by recvReqRetry(), and tryToSend().
state
MemoryState Minor::LSQ::state
Retry state of last issued memory transfer.
Definition at line 539 of file lsq.hh.
Referenced by Minor::LSQ::BarrierDataRequest::BarrierDataRequest(), Minor::LSQ::FailedDataRequest::FailedDataRequest(), minorTrace(), and Minor::operator<<().
storeBuffer
StoreBuffer Minor::LSQ::storeBuffer
Definition at line 588 of file lsq.hh.
Referenced by completeMemBarrierInst(), findResponse(), isDrained(), minorTrace(), needsToTick(), recvReqRetry(), recvTimingResp(), sendStoreToStoreBuffer(), step(), and tryToSendToTransfers().
transfers
LSQQueue Minor::LSQ::transfers
Once issued to memory (or, for stores, just had their state changed to StoreToStoreBuffer) LSQRequests pass through transfers waiting for memory responses.
At the head of transfers, Execute::commitInst can pick up the memory response for a request using LSQ::findResponse. Responses to be committed can then have ExecContext::completeAcc on them. Stores can then be pushed into the store buffer. All other transfers will then be complete.
Definition at line 577 of file lsq.hh.
Referenced by findResponse(), isDrained(), minorTrace(), moveFromRequestsToTransfers(), needsToTick(), popResponse(), and tryToSendToTransfers().
The documentation for this class was generated from the following files:
cpu/minor/lsq.hh
cpu/minor/lsq.cc