gem5: Stats::Histogram Class Reference
Stats::Histogram Class Reference
"Statistic Types"
A simple histogram stat.
#include <statistics.hh>
Public Member Functions
Histogram (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
Histogram & init (size_type size)
Set the parameters of this histogram.
Public Member Functions inherited from Stats::DistBase< Histogram, HistStor >
DistBase (Group *parent, const char *name, const char *desc)
void sample (const U &v, int n=1)
Add a value to the distribtion n times.
size_type size () const
Return the number of entries in this stat.
bool zero () const
Return true if no samples have been added.
void prepare ()
void reset ()
Reset stat value to default.
void add (DistBase &d)
Add the argument distribution to the this distribution.
Public Member Functions inherited from Stats::DataWrap< Histogram, DistInfoProxy >
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
DataWrap & operator= (const DataWrap &)=delete
Histogram & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Histogram & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Histogram & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Histogram & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Histogram & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
Histogram & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Additional Inherited Members
Public Types inherited from Stats::DistBase< Histogram, HistStor >
typedef DistInfoProxy< Histogram > Info
typedef HistStor Storage
typedef HistStor ::Params Params
Public Types inherited from Stats::DataWrap< Histogram, DistInfoProxy >
typedef DistInfoProxy< Histogram > Info
Protected Member Functions inherited from Stats::DistBase< Histogram, HistStor >
char storage [sizeof(Storage)] __attribute__ ((aligned(8)))
The storage for this stat.
Storage * data ()
Retrieve the storage.
const Storage * data () const
Retrieve a const pointer to the storage.
void doInit ()
Protected Member Functions inherited from Stats::DataWrap< Histogram, DistInfoProxy >
Histogram & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Detailed Description
A simple histogram stat.
See also
Stat, DistBase, HistStor
Definition at line 2631 of file statistics.hh.
Constructor & Destructor Documentation
Histogram()
Stats::Histogram::Histogram (Group * parent = nullptr, const char * name = nullptr, const char * desc = nullptr) inline
Definition at line 2634 of file statistics.hh.
Member Function Documentation
init()
Histogram& Stats::Histogram::init (size_type size) inline
Set the parameters of this histogram.
See also
HistStor::Params
Parameters
size The number of buckets in the histogram
Returns
A reference to this histogram.
Definition at line 2646 of file statistics.hh.
References Stats::HistStor::Params::buckets.
Referenced by AbstractController::init(), CommMonitor::MonitorStats::MonitorStats(), StackDistProbe::regStats(), Sequencer::regStats(), Profiler::regStats(), GPUCoalescer::regStats(), FlashDevice::regStats(), SimpleCache::regStats(), ArmISA::TableWalker::regStats(), UFSHostDevice::regStats(), and DRAMCtrl::DRAMStats::regStats().
The documentation for this class was generated from the following file:
base/statistics.hh