gem5: IGbE::TxDescCache Class Reference
IGbE::TxDescCache Class Reference
Public Member Functions
TxDescCache (IGbE *i, std::string n, int s)
unsigned getPacketSize (EthPacketPtr p)
Tell the cache to DMA a packet from main memory into its buffer and return the size the of the packet to reserve space in tx fifo.
void getPacketData (EthPacketPtr p)
void processContextDesc ()
unsigned descInBlock (unsigned num_desc)
Return the number of dsecriptors in a cache block for threshold operations.
bool packetAvailable ()
Ask if the packet has been transfered so the state machine can give it to the fifo.
bool packetWaiting ()
Ask if we are still waiting for the packet to be transfered.
bool packetMultiDesc ()
Ask if this packet is composed of multiple descriptors so even if we've got data, we need to wait for more before we can send it out.
void pktComplete ()
Called by event when dma to write packet is completed.
void headerComplete ()
void completionWriteback (Addr a, bool enabled)
bool hasOutstandingEvents () override
void nullCallback ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from IGbE::DescCache< iGbReg::TxDesc >
DescCache (IGbE *i, const std::string n, int s)
virtual ~DescCache ()
std::string name ()
void areaChanged ()
If the address/len/head change when we've got descriptors that are dirty that is very bad.
void writeback (Addr aMask)
void writeback1 ()
void fetchDescriptors ()
Fetch a chunk of descriptors into the descriptor cache.
void fetchDescriptors1 ()
void fetchComplete ()
Called by event when dma to read descriptors is completed.
void wbComplete ()
Called by event when dma to writeback descriptors is completed.
unsigned descLeft () const
unsigned descUsed () const
unsigned descUnused () const
void reset ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
EventFunctionWrapper pktEvent
EventFunctionWrapper headerEvent
EventFunctionWrapper nullEvent
Public Attributes inherited from IGbE::DescCache< iGbReg::TxDesc >
std::string annSmFetch
Annotate sm.
std::string annSmWb
std::string annUnusedDescQ
std::string annUsedCacheQ
std::string annUsedDescQ
std::string annUnusedCacheQ
std::string annDescQ
EventFunctionWrapper wbDelayEvent
EventFunctionWrapper fetchDelayEvent
EventFunctionWrapper fetchEvent
EventFunctionWrapper wbEvent
Protected Member Functions
Addr descBase () const override
long descHead () const override
long descTail () const override
long descLen () const override
void updateHead (long h) override
void enableSm () override
void actionAfterWb () override
void fetchAfterWb () override
Protected Member Functions inherited from IGbE::DescCache< iGbReg::TxDesc >
Addr pciToDma (Addr a)
Shortcut for DMA address translation.
Protected Attributes
bool pktDone
bool isTcp
bool pktWaiting
bool pktMultiDesc
Addr completionAddress
bool completionEnabled
uint32_t descEnd
bool useTso
Addr tsoHeaderLen
Addr tsoMss
Addr tsoTotalLen
Addr tsoUsedLen
Addr tsoPrevSeq
Addr tsoPktPayloadBytes
bool tsoLoadedHeader
bool tsoPktHasHeader
uint8_t tsoHeader [256]
Addr tsoDescBytesUsed
Addr tsoCopyBytes
int tsoPkts
Protected Attributes inherited from IGbE::DescCache< iGbReg::TxDesc >
CacheType usedCache
CacheType unusedCache
iGbReg::TxDesc * fetchBuf
iGbReg::TxDesc * wbBuf
IGbE * igbe
std::string _name
int cachePnt
int size
int curFetching
int wbOut
bool moreToWb
Addr wbAlignment
EthPacketPtr pktPtr
The packet that is currently being dmad to memory if any.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from IGbE::DescCache< iGbReg::TxDesc >
typedef std::deque< iGbReg::TxDesc *> CacheType
Detailed Description
Definition at line 399 of file i8254xGBe.hh.
Constructor & Destructor Documentation
TxDescCache()
IGbE::TxDescCache::TxDescCache (IGbE * i, std::string n, int s)
Definition at line 1555 of file i8254xGBe.cc.
References IGbE::DescCache< iGbReg::TxDesc >::annDescQ, IGbE::DescCache< iGbReg::TxDesc >::annSmFetch, IGbE::DescCache< iGbReg::TxDesc >::annSmWb, IGbE::DescCache< iGbReg::TxDesc >::annUnusedCacheQ, IGbE::DescCache< iGbReg::TxDesc >::annUnusedDescQ, IGbE::DescCache< iGbReg::TxDesc >::annUsedCacheQ, IGbE::DescCache< iGbReg::TxDesc >::annUsedDescQ, headerComplete(), headerEvent, ArmISA::n, nullCallback(), nullEvent, and pktComplete().
Member Function Documentation
actionAfterWb()
void IGbE::TxDescCache::actionAfterWb () override protected virtual
Reimplemented from IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 1970 of file i8254xGBe.cc.
References completionAddress, completionEnabled, descEnd, DmaDevice::dmaWrite(), DPRINTF, IGbE::DescCache< iGbReg::TxDesc >::igbe, iGbReg::IT_TXDW, mbits(), nullEvent, IGbE::DescCache< iGbReg::TxDesc >::pciToDma(), IGbE::postInterrupt(), IGbE::regs, and iGbReg::Regs::tdh.
completionWriteback()
void IGbE::TxDescCache::completionWriteback (Addr a, bool enabled) inline
Definition at line 488 of file i8254xGBe.hh.
References ArmISA::a, DPRINTF, Stats::enabled(), and IGbE::DescCache< T >::hasOutstandingEvents().
Referenced by IGbE::write().
descBase()
Addr IGbE::TxDescCache::descBase () const inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 402 of file i8254xGBe.hh.
References IGbE::DescCache< T >::igbe, IGbE::regs, and iGbReg::Regs::tdba.
descHead()
long IGbE::TxDescCache::descHead () const inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 403 of file i8254xGBe.hh.
References IGbE::DescCache< T >::igbe, IGbE::regs, and iGbReg::Regs::tdh.
descInBlock()
unsigned IGbE::TxDescCache::descInBlock (unsigned num_desc) inline
Return the number of dsecriptors in a cache block for threshold operations.
Definition at line 455 of file i8254xGBe.hh.
References DmaDevice::cacheBlockSize(), and IGbE::DescCache< T >::igbe.
Referenced by pktComplete().
descLen()
long IGbE::TxDescCache::descLen () const inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 405 of file i8254xGBe.hh.
References IGbE::DescCache< T >::igbe, IGbE::regs, and iGbReg::Regs::tdlen.
descTail()
long IGbE::TxDescCache::descTail () const inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 404 of file i8254xGBe.hh.
References IGbE::DescCache< T >::igbe, IGbE::regs, and iGbReg::Regs::tdt.
enableSm()
void IGbE::TxDescCache::enableSm () override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 2054 of file i8254xGBe.cc.
References Draining, Drainable::drainState(), IGbE::DescCache< iGbReg::TxDesc >::igbe, IGbE::restartClock(), and IGbE::txTick.
Referenced by headerComplete(), and pktComplete().
fetchAfterWb()
void IGbE::TxDescCache::fetchAfterWb () inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 409 of file i8254xGBe.hh.
References Drainable::drainState(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::igbe, Running, and IGbE::txTick.
getPacketData()
void IGbE::TxDescCache::getPacketData (EthPacketPtr p)
Definition at line 1718 of file i8254xGBe.cc.
References DmaDevice::dmaRead(), DPRINTF, iGbReg::TxdOp::getBuf(), iGbReg::TxdOp::getLen(), IGbE::DescCache< iGbReg::TxDesc >::igbe, iGbReg::TxdOp::isData(), iGbReg::TxdOp::isLegacy(), MipsISA::p, IGbE::DescCache< iGbReg::TxDesc >::pciToDma(), pktEvent, IGbE::DescCache< iGbReg::TxDesc >::pktPtr, pktWaiting, tsoCopyBytes, tsoDescBytesUsed, tsoHeader, tsoHeaderLen, tsoLoadedHeader, tsoPktHasHeader, IGbE::txReadDelay, IGbE::DescCache< iGbReg::TxDesc >::unusedCache, and useTso.
Referenced by IGbE::txStateMachine().
getPacketSize()
unsigned IGbE::TxDescCache::getPacketSize (EthPacketPtr p)
Tell the cache to DMA a packet from main memory into its buffer and return the size the of the packet to reserve space in tx fifo.
Returns
size of the packet
Definition at line 1678 of file i8254xGBe.cc.
References iGbReg::TxDesc::d1, iGbReg::TxDesc::d2, DPRINTF, iGbReg::TxdOp::getLen(), tsoCopyBytes, tsoDescBytesUsed, tsoHeaderLen, tsoLoadedHeader, tsoMss, tsoPktHasHeader, tsoTotalLen, tsoUsedLen, IGbE::DescCache< iGbReg::TxDesc >::unusedCache, and useTso.
Referenced by IGbE::txStateMachine().
hasOutstandingEvents()
bool IGbE::TxDescCache::hasOutstandingEvents () override virtual
Reimplemented from IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 2063 of file i8254xGBe.cc.
References IGbE::DescCache< iGbReg::TxDesc >::fetchEvent, pktEvent, Event::scheduled(), and IGbE::DescCache< iGbReg::TxDesc >::wbEvent.
Referenced by IGbE::checkDrain(), and IGbE::drain().
headerComplete()
void IGbE::TxDescCache::headerComplete ()
Definition at line 1653 of file i8254xGBe.cc.
References IGbE::checkDrain(), DPRINTF, enableSm(), iGbReg::TxdOp::getLen(), IGbE::DescCache< iGbReg::TxDesc >::igbe, pktWaiting, tsoDescBytesUsed, tsoHeaderLen, tsoLoadedHeader, IGbE::DescCache< iGbReg::TxDesc >::unusedCache, and IGbE::DescCache< iGbReg::TxDesc >::usedCache.
Referenced by TxDescCache().
nullCallback()
void IGbE::TxDescCache::nullCallback () inline
Definition at line 498 of file i8254xGBe.hh.
References DPRINTF.
Referenced by TxDescCache().
packetAvailable()
bool IGbE::TxDescCache::packetAvailable ()
Ask if the packet has been transfered so the state machine can give it to the fifo.
Returns
packet available in descriptor cache
Definition at line 2044 of file i8254xGBe.cc.
References pktDone.
Referenced by IGbE::txStateMachine().
packetMultiDesc()
bool IGbE::TxDescCache::packetMultiDesc () inline
Ask if this packet is composed of multiple descriptors so even if we've got data, we need to wait for more before we can send it out.
Returns
packet can't be sent out because it's a multi-descriptor packet
Definition at line 477 of file i8254xGBe.hh.
Referenced by IGbE::txStateMachine().
packetWaiting()
bool IGbE::TxDescCache::packetWaiting () inline
Ask if we are still waiting for the packet to be transfered.
Returns
packet still in transit.
Definition at line 469 of file i8254xGBe.hh.
Referenced by IGbE::txStateMachine().
pktComplete()
void IGbE::TxDescCache::pktComplete ()
Called by event when dma to write packet is completed.
Definition at line 1766 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::anDq(), IGbE::DescCache< iGbReg::TxDesc >::annUnusedCacheQ, IGbE::DescCache< iGbReg::TxDesc >::annUsedCacheQ, IGbE::anQ(), DmaDevice::cacheBlockSize(), IGbE::checkDrain(), Net::cksum(), curTick(), iGbReg::TxDesc::d1, iGbReg::TxDesc::d2, descInBlock(), DPRINTF, DTRACE, enableSm(), iGbReg::TxdOp::eop(), Net::TcpHdr::flags(), iGbReg::TxdOp::getLen(), Net::IpHdr::id(), ArmISA::ide, IGbE::DescCache< iGbReg::TxDesc >::igbe, IGbE::intClock(), iGbReg::TxdOp::ip(), MipsISA::ip6, iGbReg::TxdOp::isData(), iGbReg::TxdOp::isLegacy(), iGbReg::TxdOp::ixsm(), Net::IpHdr::len(), Net::UdpHdr::len(), panic, pktDone, pktMultiDesc, IGbE::DescCache< iGbReg::TxDesc >::pktPtr, pktWaiting, Net::Ip6Hdr::plen(), IGbE::regs, EventManager::reschedule(), ArmISA::rs, EventManager::schedule(), Event::scheduled(), Net::TcpHdr::seq(), iGbReg::TxdOp::setDd(), IGbE::DescCache< iGbReg::TxDesc >::size, Net::IpHdr::sum(), Net::TcpHdr::sum(), Net::UdpHdr::sum(), iGbReg::Regs::tadv, IGbE::tadvEvent, iGbReg::TxdOp::tcp(), iGbReg::Regs::tidv, IGbE::tidvEvent, tsoCopyBytes, tsoDescBytesUsed, tsoHeaderLen, tsoLoadedHeader, tsoMss, tsoPktHasHeader, tsoPkts, tsoPrevSeq, tsoTotalLen, tsoUsedLen, iGbReg::Regs::txdctl, EtherDevice::txIpChecksums, iGbReg::TxdOp::txsm(), EtherDevice::txTcpChecksums, EtherDevice::txUdpChecksums, IGbE::DescCache< iGbReg::TxDesc >::unusedCache, IGbE::DescCache< iGbReg::TxDesc >::usedCache, useTso, iGbReg::TxdOp::vle(), and IGbE::DescCache< iGbReg::TxDesc >::writeback().
Referenced by TxDescCache().
processContextDesc()
void IGbE::TxDescCache::processContextDesc ()
Definition at line 1576 of file i8254xGBe.cc.
References IGbE::anDq(), IGbE::DescCache< iGbReg::TxDesc >::annUnusedCacheQ, IGbE::DescCache< iGbReg::TxDesc >::annUsedCacheQ, IGbE::anQ(), DmaDevice::dmaRead(), DPRINTF, iGbReg::TxdOp::getBuf(), iGbReg::TxdOp::getLen(), iGbReg::TxdOp::getTsoLen(), iGbReg::TxdOp::hdrlen(), headerEvent, IGbE::DescCache< iGbReg::TxDesc >::igbe, iGbReg::TxdOp::isContext(), iGbReg::TxdOp::isData(), isTcp, iGbReg::TxdOp::isType(), iGbReg::TxdOp::mss(), IGbE::DescCache< iGbReg::TxDesc >::pciToDma(), pktWaiting, iGbReg::TxdOp::setDd(), iGbReg::TxdOp::tcp(), iGbReg::TxdOp::tse(), tsoCopyBytes, tsoDescBytesUsed, tsoHeader, tsoHeaderLen, tsoLoadedHeader, tsoMss, tsoPktHasHeader, tsoPkts, tsoPrevSeq, tsoTotalLen, tsoUsedLen, iGbReg::TxdOp::TXD_ADVDATA, iGbReg::TxdOp::TXD_CNXT, IGbE::DescCache< iGbReg::TxDesc >::unusedCache, IGbE::DescCache< iGbReg::TxDesc >::usedCache, and useTso.
Referenced by IGbE::txStateMachine().
serialize()
void IGbE::TxDescCache::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1986 of file i8254xGBe.cc.
References completionAddress, completionEnabled, descEnd, isTcp, pktDone, pktMultiDesc, pktWaiting, IGbE::DescCache< T >::serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, tsoCopyBytes, tsoDescBytesUsed, tsoHeader, tsoHeaderLen, tsoLoadedHeader, tsoMss, tsoPktHasHeader, tsoPktPayloadBytes, tsoPkts, tsoPrevSeq, tsoTotalLen, tsoUsedLen, and useTso.
unserialize()
void IGbE::TxDescCache::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2015 of file i8254xGBe.cc.
References completionAddress, completionEnabled, descEnd, isTcp, pktDone, pktMultiDesc, pktWaiting, tsoCopyBytes, tsoDescBytesUsed, tsoHeader, tsoHeaderLen, tsoLoadedHeader, tsoMss, tsoPktHasHeader, tsoPktPayloadBytes, tsoPkts, tsoPrevSeq, tsoTotalLen, tsoUsedLen, IGbE::DescCache< T >::unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, and useTso.
updateHead()
void IGbE::TxDescCache::updateHead (long h) inline override protected virtual
Implements IGbE::DescCache< iGbReg::TxDesc >.
Definition at line 406 of file i8254xGBe.hh.
References IGbE::DescCache< T >::actionAfterWb(), IGbE::DescCache< T >::enableSm(), IGbE::DescCache< T >::igbe, IGbE::regs, and iGbReg::Regs::tdh.
Member Data Documentation
completionAddress
Addr IGbE::TxDescCache::completionAddress protected
Definition at line 420 of file i8254xGBe.hh.
Referenced by actionAfterWb(), serialize(), and unserialize().
completionEnabled
bool IGbE::TxDescCache::completionEnabled protected
Definition at line 421 of file i8254xGBe.hh.
Referenced by actionAfterWb(), serialize(), and unserialize().
descEnd
uint32_t IGbE::TxDescCache::descEnd protected
Definition at line 422 of file i8254xGBe.hh.
Referenced by actionAfterWb(), serialize(), and unserialize().
headerEvent
EventFunctionWrapper IGbE::TxDescCache::headerEvent
Definition at line 485 of file i8254xGBe.hh.
Referenced by processContextDesc(), and TxDescCache().
isTcp
bool IGbE::TxDescCache::isTcp protected
Definition at line 417 of file i8254xGBe.hh.
Referenced by processContextDesc(), serialize(), and unserialize().
nullEvent
EventFunctionWrapper IGbE::TxDescCache::nullEvent
Definition at line 501 of file i8254xGBe.hh.
Referenced by actionAfterWb(), and TxDescCache().
pktDone
bool IGbE::TxDescCache::pktDone protected
Definition at line 416 of file i8254xGBe.hh.
Referenced by packetAvailable(), pktComplete(), serialize(), and unserialize().
pktEvent
EventFunctionWrapper IGbE::TxDescCache::pktEvent
Definition at line 482 of file i8254xGBe.hh.
Referenced by getPacketData(), and hasOutstandingEvents().
pktMultiDesc
bool IGbE::TxDescCache::pktMultiDesc protected
Definition at line 419 of file i8254xGBe.hh.
Referenced by pktComplete(), serialize(), and unserialize().
pktWaiting
bool IGbE::TxDescCache::pktWaiting protected
Definition at line 418 of file i8254xGBe.hh.
Referenced by getPacketData(), headerComplete(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoCopyBytes
Addr IGbE::TxDescCache::tsoCopyBytes protected
Definition at line 437 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoDescBytesUsed
Addr IGbE::TxDescCache::tsoDescBytesUsed protected
Definition at line 436 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), headerComplete(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoHeader
uint8_t IGbE::TxDescCache::tsoHeader[256] protected
Definition at line 435 of file i8254xGBe.hh.
Referenced by getPacketData(), processContextDesc(), serialize(), and unserialize().
tsoHeaderLen
Addr IGbE::TxDescCache::tsoHeaderLen protected
Definition at line 427 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), headerComplete(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoLoadedHeader
bool IGbE::TxDescCache::tsoLoadedHeader protected
Definition at line 433 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), headerComplete(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoMss
Addr IGbE::TxDescCache::tsoMss protected
Definition at line 428 of file i8254xGBe.hh.
Referenced by getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoPktHasHeader
bool IGbE::TxDescCache::tsoPktHasHeader protected
Definition at line 434 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoPktPayloadBytes
Addr IGbE::TxDescCache::tsoPktPayloadBytes protected
Definition at line 432 of file i8254xGBe.hh.
Referenced by serialize(), and unserialize().
tsoPkts
int IGbE::TxDescCache::tsoPkts protected
Definition at line 438 of file i8254xGBe.hh.
Referenced by pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoPrevSeq
Addr IGbE::TxDescCache::tsoPrevSeq protected
Definition at line 431 of file i8254xGBe.hh.
Referenced by pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoTotalLen
Addr IGbE::TxDescCache::tsoTotalLen protected
Definition at line 429 of file i8254xGBe.hh.
Referenced by getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
tsoUsedLen
Addr IGbE::TxDescCache::tsoUsedLen protected
Definition at line 430 of file i8254xGBe.hh.
Referenced by getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
useTso
bool IGbE::TxDescCache::useTso protected
Definition at line 426 of file i8254xGBe.hh.
Referenced by getPacketData(), getPacketSize(), pktComplete(), processContextDesc(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/net/i8254xGBe.hh
dev/net/i8254xGBe.cc