gem5: GlobalMemPipeline Class Reference
GlobalMemPipeline Class Reference
#include <global_memory_pipeline.hh>
Public Member Functions
GlobalMemPipeline (const ComputeUnitParams *params)
void init (ComputeUnit *cu)
void exec ()
std::queue< GPUDynInstPtr > & getGMStRespFIFO ()
std::queue< GPUDynInstPtr > & getGMLdRespFIFO ()
GPUDynInstPtr getNextReadyResp ()
find the next ready response to service.
void completeRequest (GPUDynInstPtr gpuDynInst)
once a memory request is finished we remove it from the buffer.
void issueRequest (GPUDynInstPtr gpuDynInst)
issues a request to the pipeline - i.e., enqueue it in the request buffer.
void handleResponse (GPUDynInstPtr gpuDynInst)
this method handles responses sent to this GM pipeline by the CU.
bool isGMLdRespFIFOWrRdy () const
bool isGMStRespFIFOWrRdy () const
bool isGMReqFIFOWrRdy (uint32_t pendReqs=0) const
const std::string & name () const
void regStats ()
void incLoadVRFBankConflictCycles (int num_cycles)
Private Attributes
ComputeUnit * computeUnit
std::string _name
int gmQueueSize
bool outOfOrderDataDelivery
Stats::Scalar loadVrfBankConflictCycles
int inflightStores
int inflightLoads
int globalMemSize
std::map< uint64_t, std::pair< GPUDynInstPtr, bool > > gmOrderedRespBuffer
std::queue< GPUDynInstPtr > gmIssuedRequests
std::queue< GPUDynInstPtr > gmReturnedStores
std::queue< GPUDynInstPtr > gmReturnedLoads
Detailed Description
Definition at line 59 of file global_memory_pipeline.hh.
Constructor & Destructor Documentation
GlobalMemPipeline()
GlobalMemPipeline::GlobalMemPipeline (const ComputeUnitParams * params)
Definition at line 47 of file global_memory_pipeline.cc.
Member Function Documentation
completeRequest()
void GlobalMemPipeline::completeRequest (GPUDynInstPtr gpuDynInst)
once a memory request is finished we remove it from the buffer.
this method determines which response buffer we're using based on the mode (in-order vs. OoO).
Definition at line 176 of file global_memory_pipeline.cc.
References gmOrderedRespBuffer, gmReturnedLoads, gmReturnedStores, inflightLoads, inflightStores, and outOfOrderDataDelivery.
Referenced by exec(), and getGMLdRespFIFO().
exec()
void GlobalMemPipeline::exec ()
if we are not in out-of-order data delivery mode then we keep the responses sorted in program order. in order to do so we must reserve an entry in the resp buffer before we issue the request to the mem system. mem fence requests will not be stored here because once they are issued from the GM pipeline, they do not send any response back to it.
Definition at line 63 of file global_memory_pipeline.cc.
References Shader::coissue_return, completeRequest(), computeUnit, Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, getNextReadyResp(), ComputeUnit::glbMemToVrfBus, gmIssuedRequests, gmOrderedRespBuffer, gmQueueSize, inflightLoads, inflightStores, ArmISA::m, X86ISA::mp, outOfOrderDataDelivery, Wavefront::outstandingReqs, Wavefront::outstandingReqsRdGm, Wavefront::outstandingReqsWrGm, WaitClass::rdy(), Shader::ScheduleAdd(), WaitClass::set(), ComputeUnit::shader, Wavefront::simdId, ComputeUnit::vrf, MipsISA::w, ComputeUnit::wfWait, and WRITE.
Referenced by ComputeUnit::exec().
getGMLdRespFIFO()
std::queue<GPUDynInstPtr>& GlobalMemPipeline::getGMLdRespFIFO () inline
Definition at line 67 of file global_memory_pipeline.hh.
References completeRequest(), getNextReadyResp(), gmReturnedLoads, handleResponse(), and issueRequest().
getGMStRespFIFO()
std::queue<GPUDynInstPtr>& GlobalMemPipeline::getGMStRespFIFO () inline
Definition at line 66 of file global_memory_pipeline.hh.
References gmReturnedStores.
getNextReadyResp()
GPUDynInstPtr GlobalMemPipeline::getNextReadyResp ()
find the next ready response to service.
for OoO mode we simply pop the oldest (based on when the response was received) response in the response FIFOs. for in-order mode we pop the oldest (in program order) response, and only if it is marked as done.
Definition at line 154 of file global_memory_pipeline.cc.
References gmOrderedRespBuffer, gmReturnedLoads, gmReturnedStores, and outOfOrderDataDelivery.
Referenced by exec(), and getGMLdRespFIFO().
handleResponse()
void GlobalMemPipeline::handleResponse (GPUDynInstPtr gpuDynInst)
this method handles responses sent to this GM pipeline by the CU.
in the case of in-order delivery it simply marks the reqeust as done in the ordered buffer to indicate that the requst is finished. for out-of-order data delivery, the requests are enqueued (in the order in which they are received) in the response FIFOs.
Definition at line 213 of file global_memory_pipeline.cc.
References gmOrderedRespBuffer, gmReturnedLoads, gmReturnedStores, isGMLdRespFIFOWrRdy(), isGMStRespFIFOWrRdy(), and outOfOrderDataDelivery.
Referenced by getGMLdRespFIFO(), and ComputeUnit::DataPort::processMemRespEvent().
incLoadVRFBankConflictCycles()
void GlobalMemPipeline::incLoadVRFBankConflictCycles (int num_cycles) inline
Definition at line 122 of file global_memory_pipeline.hh.
References loadVrfBankConflictCycles.
init()
void GlobalMemPipeline::init (ComputeUnit * cu)
Definition at line 55 of file global_memory_pipeline.cc.
References _name, computeUnit, Shader::globalMemSize, globalMemSize, SimObject::name(), and ComputeUnit::shader.
Referenced by ComputeUnit::init().
isGMLdRespFIFOWrRdy()
bool GlobalMemPipeline::isGMLdRespFIFOWrRdy () const inline
Definition at line 101 of file global_memory_pipeline.hh.
References gmQueueSize, and gmReturnedLoads.
Referenced by handleResponse(), and ComputeUnit::isDone().
isGMReqFIFOWrRdy()
bool GlobalMemPipeline::isGMReqFIFOWrRdy (uint32_t pendReqs = 0) const inline
Definition at line 113 of file global_memory_pipeline.hh.
References gmIssuedRequests, and gmQueueSize.
Referenced by ComputeUnit::isDone().
isGMStRespFIFOWrRdy()
bool GlobalMemPipeline::isGMStRespFIFOWrRdy () const inline
Definition at line 107 of file global_memory_pipeline.hh.
References gmQueueSize, and gmReturnedStores.
Referenced by handleResponse(), and ComputeUnit::isDone().
issueRequest()
void GlobalMemPipeline::issueRequest (GPUDynInstPtr gpuDynInst)
issues a request to the pipeline - i.e., enqueue it in the request buffer.
Definition at line 207 of file global_memory_pipeline.cc.
References gmIssuedRequests.
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::MemFence::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), getGMLdRespFIFO(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), and HsailISA::Call::MagicLoadGlobalU32Reg().
name()
const std::string& GlobalMemPipeline::name () const inline
Definition at line 118 of file global_memory_pipeline.hh.
References _name, and regStats().
Referenced by regStats().
regStats()
void GlobalMemPipeline::regStats ()
Definition at line 234 of file global_memory_pipeline.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), loadVrfBankConflictCycles, name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
Referenced by name(), and ComputeUnit::regStats().
Member Data Documentation
_name
std::string GlobalMemPipeline::_name private
Definition at line 129 of file global_memory_pipeline.hh.
Referenced by init(), and name().
computeUnit
ComputeUnit* GlobalMemPipeline::computeUnit private
Definition at line 128 of file global_memory_pipeline.hh.
Referenced by exec(), and init().
globalMemSize
int GlobalMemPipeline::globalMemSize private
Definition at line 144 of file global_memory_pipeline.hh.
Referenced by init().
gmIssuedRequests
std::queue<GPUDynInstPtr> GlobalMemPipeline::gmIssuedRequests private
Definition at line 164 of file global_memory_pipeline.hh.
Referenced by exec(), isGMReqFIFOWrRdy(), and issueRequest().
gmOrderedRespBuffer
std::map<uint64_t, std::pair<GPUDynInstPtr, bool> > GlobalMemPipeline::gmOrderedRespBuffer private
Definition at line 160 of file global_memory_pipeline.hh.
Referenced by completeRequest(), exec(), getNextReadyResp(), and handleResponse().
gmQueueSize
int GlobalMemPipeline::gmQueueSize private
Definition at line 130 of file global_memory_pipeline.hh.
Referenced by exec(), isGMLdRespFIFOWrRdy(), isGMReqFIFOWrRdy(), and isGMStRespFIFOWrRdy().
gmReturnedLoads
std::queue<GPUDynInstPtr> GlobalMemPipeline::gmReturnedLoads private
Definition at line 172 of file global_memory_pipeline.hh.
Referenced by completeRequest(), getGMLdRespFIFO(), getNextReadyResp(), handleResponse(), and isGMLdRespFIFOWrRdy().
gmReturnedStores
std::queue<GPUDynInstPtr> GlobalMemPipeline::gmReturnedStores private
Definition at line 168 of file global_memory_pipeline.hh.
Referenced by completeRequest(), getGMStRespFIFO(), getNextReadyResp(), handleResponse(), and isGMStRespFIFOWrRdy().
inflightLoads
int GlobalMemPipeline::inflightLoads private
Definition at line 141 of file global_memory_pipeline.hh.
Referenced by completeRequest(), and exec().
inflightStores
int GlobalMemPipeline::inflightStores private
Definition at line 140 of file global_memory_pipeline.hh.
Referenced by completeRequest(), and exec().
loadVrfBankConflictCycles
Stats::Scalar GlobalMemPipeline::loadVrfBankConflictCycles private
Definition at line 136 of file global_memory_pipeline.hh.
Referenced by incLoadVRFBankConflictCycles(), and regStats().
outOfOrderDataDelivery
bool GlobalMemPipeline::outOfOrderDataDelivery private
Definition at line 131 of file global_memory_pipeline.hh.
Referenced by completeRequest(), exec(), getNextReadyResp(), and handleResponse().
The documentation for this class was generated from the following files:
gpu-compute/global_memory_pipeline.hh
gpu-compute/global_memory_pipeline.cc