gem5: SparcISA::RemoteGDB::SPARCGdbRegCache Class Reference
SparcISA::RemoteGDB::SPARCGdbRegCache Class Reference
#include <remote_gdb.hh>
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct {
uint32_t gpr [32]
uint32_t hole [32]
uint32_t y
uint32_t psr
uint32_t wim
uint32_t tbr
uint32_t pc
uint32_t npc
uint32_t fsr
uint32_t csr
} r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 51 of file remote_gdb.hh.
Member Function Documentation
data()
char* SparcISA::RemoteGDB::SPARCGdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 68 of file remote_gdb.hh.
References r.
getRegs()
void RemoteGDB::SPARCGdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 175 of file remote_gdb.cc.
References DPRINTF, htobe(), ArmISA::i, SparcISA::MISCREG_FSR, SparcISA::MISCREG_PSTATE, GenericISA::SimplePCState< MachInst >::npc(), SparcISA::NumIntArchRegs, GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), MipsISA::r, ThreadContext::readIntReg(), and ThreadContext::readMiscReg().
Referenced by size(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::size().
name()
const std::string SparcISA::RemoteGDB::SPARCGdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 73 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::SPARCGdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 210 of file remote_gdb.cc.
References ArmISA::i, GenericISA::DelaySlotPCState< MachInst >::nnpc(), GenericISA::SimplePCState< MachInst >::npc(), GenericISA::DelaySlotUPCState< MachInst >::nupc(), GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), MipsISA::r, ThreadContext::setIntReg(), and GenericISA::DelaySlotUPCState< MachInst >::upc().
Referenced by size(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::size().
size()
size_t SparcISA::RemoteGDB::SPARCGdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 69 of file remote_gdb.hh.
References getRegs(), r, and setRegs().
Member Data Documentation
csr
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::csr
Definition at line 65 of file remote_gdb.hh.
fsr
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::fsr
Definition at line 64 of file remote_gdb.hh.
gpr
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::gpr[32]
Definition at line 56 of file remote_gdb.hh.
hole
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::hole[32]
Definition at line 57 of file remote_gdb.hh.
npc
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::npc
Definition at line 63 of file remote_gdb.hh.
pc
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::pc
Definition at line 62 of file remote_gdb.hh.
psr
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::psr
Definition at line 59 of file remote_gdb.hh.
r
struct { ... } SparcISA::RemoteGDB::SPARCGdbRegCache::r
Referenced by data(), SparcISA::RemoteGDB::SPARC64GdbRegCache::data(), size(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::size().
tbr
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::tbr
Definition at line 61 of file remote_gdb.hh.
wim
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::wim
Definition at line 60 of file remote_gdb.hh.
y
uint32_t SparcISA::RemoteGDB::SPARCGdbRegCache::y
Definition at line 58 of file remote_gdb.hh.
The documentation for this class was generated from the following files:
arch/sparc/remote_gdb.hh
arch/sparc/remote_gdb.cc