gem5: AbstractMemory Class Reference
AbstractMemory Class Reference
An abstract memory represents a contiguous block of physical memory, with an associated address range, and also provides basic functionality for reading and writing this memory without any timing information.
#include <abstract_mem.hh>
Classes
struct MemStats
Public Types
typedef AbstractMemoryParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
AbstractMemory (const Params *p)
virtual ~AbstractMemory ()
void init () override
Initialise this memory.
bool isNull () const
See if this is a null memory that should never store data and always return zero.
void setBackingStore (uint8_t *pmem_addr)
Set the host memory backing store to be used by this memory controller.
const std::list< LockedAddr > & getLockedAddrList () const
Get the list of locked addresses to allow checkpointing.
void addLockedAddr (LockedAddr addr)
Add a locked address to allow for checkpointing.
System * system () const
read the system pointer Implemented for completeness with the setter
void system (System *sys)
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
const Params * params () const
AddrRange getAddrRange () const
Get the address range.
uint64_t size () const
Get the memory size.
Addr start () const
Get the start address.
bool isConfReported () const
Should this memory be passed to the kernel and part of the OS physical memory layout.
bool isInAddrMap () const
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
bool isKvmMap () const
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool checkLockedAddrList (PacketPtr pkt)
void trackLoadLocked (PacketPtr pkt)
bool writeOK (PacketPtr pkt)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
AddrRange range
uint8_t * pmemAddr
MemBackdoor backdoor
const bool confTableReported
const bool inAddrMap
const bool kvmMap
std::list< LockedAddr > lockedAddrList
System * _system
Pointer to the System object.
AbstractMemory::MemStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
AbstractMemory (const AbstractMemory &)
AbstractMemory & operator= (const AbstractMemory &)
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
An abstract memory represents a contiguous block of physical memory, with an associated address range, and also provides basic functionality for reading and writing this memory without any timing information.
It is a ClockedObject since subclasses may need timing information.
Definition at line 107 of file abstract_mem.hh.
Member Typedef Documentation
Params
typedef AbstractMemoryParams AbstractMemory::Params
Definition at line 210 of file abstract_mem.hh.
Constructor & Destructor Documentation
AbstractMemory() [1/2]
AbstractMemory::AbstractMemory (const AbstractMemory &) private
AbstractMemory() [2/2]
AbstractMemory::AbstractMemory (const Params * p)
Definition at line 59 of file abstract_mem.cc.
~AbstractMemory()
virtual AbstractMemory::~AbstractMemory () inline virtual
Definition at line 213 of file abstract_mem.hh.
References Stats::init.
Member Function Documentation
access()
void AbstractMemory::access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
locked addresses) and statistics accordingly. The packet is turned into a response if required.
Parameters
pkt Packet performing the access
Definition at line 348 of file abstract_mem.cc.
References Packet::cacheResponding(), MemCmd::CleanEvict, Packet::cmd, DPRINTF, Packet::fromCache(), Packet::getAddr(), Packet::getAddrRange(), Packet::getAtomicOp(), Packet::getSize(), Packet::isAtomicOp(), Packet::isClean(), Packet::isInvalidate(), Packet::isLLSC(), Packet::isRead(), AddrRange::isSubset(), Packet::isWrite(), Packet::makeResponse(), Packet::needsResponse(), panic, panic_if, pmemAddr, Packet::print(), range, Packet::req, Packet::setData(), AddrRange::start(), Stats::Group::stats, MemCmd::SwapReq, TRACE_PACKET, trackLoadLocked(), MemCmd::WritebackClean, Packet::writeData(), and writeOK().
Referenced by DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), RubyPort::MemSlavePort::hitCallback(), QoS::MemSinkCtrl::processNextReqEvent(), SimpleMemory::recvAtomic(), DRAMSim2::recvAtomic(), QoS::MemSinkCtrl::recvAtomic(), and DRAMCtrl::recvAtomic().
addLockedAddr()
void AbstractMemory::addLockedAddr (LockedAddr addr) inline
Add a locked address to allow for checkpointing.
Definition at line 245 of file abstract_mem.hh.
checkLockedAddrList()
bool AbstractMemory::checkLockedAddrList (PacketPtr pkt) protected
Definition at line 258 of file abstract_mem.cc.
References DDUMP, DPRINTF, Packet::getAddr(), Packet::getConstPtr(), System::getMasterName(), Packet::getSize(), System::getThreadContext(), Packet::getUintX(), TheISA::globalClearExclusive(), AlphaISA::GuestByteOrder, ArmISA::i, InvalidContextID, Packet::isLLSC(), lockedAddrList, LockedAddr::mask(), Packet::req, size(), and system().
functionalAccess()
void AbstractMemory::functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
No stats are affected by this access. In addition to normal accesses this also facilitates print requests.
Parameters
pkt Packet performing the access
Definition at line 450 of file abstract_mem.cc.
References ccprintf(), Packet::cmdString(), Packet::PrintReqState::curPrefix(), Packet::getAddr(), Packet::getAddrRange(), Packet::isPrint(), Packet::isRead(), AddrRange::isSubset(), Packet::isWrite(), Packet::makeResponse(), Packet::PrintReqState::os, panic, pmemAddr, Packet::PrintReqState::printLabels(), range, Packet::senderState, Packet::setData(), AddrRange::start(), TRACE_PACKET, and Packet::writeData().
Referenced by RubyPort::MemSlavePort::recvFunctional(), SimpleMemory::recvFunctional(), DRAMSim2::recvFunctional(), QoS::MemSinkCtrl::recvFunctional(), and DRAMCtrl::recvFunctional().
getAddrRange()
AddrRange AbstractMemory::getAddrRange () const
Get the address range.
Returns
a single contigous address range
Definition at line 219 of file abstract_mem.cc.
References range.
getLockedAddrList()
const std::list<LockedAddr>& AbstractMemory::getLockedAddrList () const inline
Get the list of locked addresses to allow checkpointing.
Definition at line 239 of file abstract_mem.hh.
init()
void AbstractMemory::init () override virtual
Initialise this memory.
Reimplemented from SimObject.
Reimplemented in DRAMCtrl, QoS::MemCtrl, DRAMSim2, SimpleMemory, and QoS::MemSinkCtrl.
Definition at line 71 of file abstract_mem.cc.
References _system, System::getPageBytes(), panic, size(), and system().
Referenced by SimpleMemory::init(), DRAMSim2::init(), and QoS::MemCtrl::init().
isConfReported()
bool AbstractMemory::isConfReported () const inline
Should this memory be passed to the kernel and part of the OS physical memory layout.
Returns
if this memory is reported
Definition at line 293 of file abstract_mem.hh.
isInAddrMap()
bool AbstractMemory::isInAddrMap () const inline
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
Returns
if this memory is part of the address map
Definition at line 301 of file abstract_mem.hh.
isKvmMap()
bool AbstractMemory::isKvmMap () const inline
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
Returns
if this memory should be mapped into the KVM guest address space
Definition at line 309 of file abstract_mem.hh.
isNull()
bool AbstractMemory::isNull () const inline
See if this is a null memory that should never store data and always return zero.
Returns
true if null
Definition at line 226 of file abstract_mem.hh.
operator=()
AbstractMemory& AbstractMemory::operator= (const AbstractMemory &) private
params()
const Params* AbstractMemory::params () const inline
Definition at line 261 of file abstract_mem.hh.
setBackingStore()
void AbstractMemory::setBackingStore (uint8_t * pmem_addr)
Set the host memory backing store to be used by this memory controller.
Parameters
pmem_addr Pointer to a segment of host memory
Definition at line 80 of file abstract_mem.cc.
References backdoor, AddrRange::interleaved(), MemBackdoor::invalidate(), pmemAddr, MemBackdoor::ptr(), and range.
size()
uint64_t AbstractMemory::size () const inline
Get the memory size.
Returns
the size of the memory
Definition at line 278 of file abstract_mem.hh.
References AddrRange::size().
Referenced by DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), checkLockedAddrList(), DRAMCtrl::DRAMCtrl(), DRAMCtrl::DRAMPacket::getSize(), init(), and DRAMCtrl::recvTimingReq().
start()
Addr AbstractMemory::start () const inline
Get the start address.
Returns
the start address of the memory
Definition at line 285 of file abstract_mem.hh.
References AddrRange::start().
system() [1/2]
System* AbstractMemory::system () const inline
read the system pointer Implemented for completeness with the setter
Returns
pointer to the system object
Definition at line 250 of file abstract_mem.hh.
Referenced by checkLockedAddrList(), DRAMCtrl::drainResume(), DRAMSim2::init(), init(), DRAMCtrl::init(), QoS::PropFairPolicy::initMaster(), QoS::Policy::pair(), QoS::MemCtrl::MemCtrlStats::regStats(), AbstractMemory::MemStats::regStats(), QoS::FixedPriorityPolicy::schedule(), and DRAMCtrl::startup().
system() [2/2]
void AbstractMemory::system (System * sys) inline
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
An init() this is set.
Parameters
sys system pointer to set
Definition at line 258 of file abstract_mem.hh.
trackLoadLocked()
void AbstractMemory::trackLoadLocked (PacketPtr pkt) protected
Definition at line 227 of file abstract_mem.cc.
References DPRINTF, ArmISA::i, lockedAddrList, LockedAddr::mask(), and Packet::req.
Referenced by access().
writeOK()
bool AbstractMemory::writeOK (PacketPtr pkt) inline protected
Definition at line 149 of file abstract_mem.hh.
References Packet::isLLSC(), and Packet::req.
Referenced by access().
Member Data Documentation
_system
System* AbstractMemory::_system protected
Pointer to the System object.
This is used for getting the number of masters in the system which is needed when registering stats
Definition at line 168 of file abstract_mem.hh.
Referenced by QoS::MemCtrl::addMaster(), init(), QoS::MemSinkCtrl::processNextReqEvent(), QoS::MemCtrl::qosSchedule(), QoS::MemSinkCtrl::recvTimingReq(), QoS::MemCtrl::MemCtrlStats::regStats(), and DRAMCtrl::DRAMStats::regStats().
backdoor
MemBackdoor AbstractMemory::backdoor protected
Definition at line 118 of file abstract_mem.hh.
Referenced by SimpleMemory::recvAtomicBackdoor(), and setBackingStore().
confTableReported
const bool AbstractMemory::confTableReported protected
Definition at line 121 of file abstract_mem.hh.
inAddrMap
const bool AbstractMemory::inAddrMap protected
Definition at line 124 of file abstract_mem.hh.
kvmMap
const bool AbstractMemory::kvmMap protected
Definition at line 127 of file abstract_mem.hh.
lockedAddrList
std::list<LockedAddr> AbstractMemory::lockedAddrList protected
Definition at line 129 of file abstract_mem.hh.
Referenced by checkLockedAddrList(), and trackLoadLocked().
pmemAddr
uint8_t* AbstractMemory::pmemAddr protected
Definition at line 115 of file abstract_mem.hh.
Referenced by access(), functionalAccess(), and setBackingStore().
range
AddrRange AbstractMemory::range protected
Definition at line 112 of file abstract_mem.hh.
Referenced by access(), DRAMCtrl::DRAMCtrl(), functionalAccess(), getAddrRange(), DRAMCtrl::getCtrlAddr(), DRAMCtrl::init(), and setBackingStore().
stats
AbstractMemory::MemStats AbstractMemory::stats protected
The documentation for this class was generated from the following files:
mem/abstract_mem.hh
mem/abstract_mem.cc