gem5: TraceCPU::FixedRetryGen Class Reference
TraceCPU::FixedRetryGen Class Reference
Generator to read protobuf trace containing memory requests at fixed timestamps, perform flow control and issue memory requests.
#include <trace_cpu.hh>
Classes
class InputStream
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
struct TraceElement
This struct stores a line in the trace file.
Public Member Functions
FixedRetryGen (TraceCPU &_owner, const std::string &_name, MasterPort &_port, MasterID master_id, const std::string &trace_file)
Tick init ()
Called from TraceCPU init().
bool tryNext ()
This tries to send current or retry packet and returns true if successfull.
const std::string & name () const
Returns name of the FixedRetryGen instance.
bool send (Addr addr, unsigned size, const MemCmd &cmd, Request::FlagsType flags, Addr pc)
Creates a new request assigning the request parameters passed by the arguments.
void exit ()
Exit the FixedRetryGen.
bool nextExecute ()
Reads a line of the trace file.
bool isTraceComplete ()
Returns the traceComplete variable which is set when end of the input trace file is reached.
int64_t tickDelta ()
void regStats ()
Private Attributes
TraceCPU & owner
Reference of the TraceCPU.
MasterPort & port
Reference of the port to be used to issue memory requests.
const MasterID masterID
MasterID used for the requests being sent.
InputStream trace
Input stream used for reading the input trace file.
std::string genName
String to store the name of the FixedRetryGen.
PacketPtr retryPkt
PacketPtr used to store the packet to retry.
int64_t delta
Stores the difference in the send ticks of the current and last packets.
bool traceComplete
Set to true when end of trace is reached.
TraceElement currElement
Store an element read from the trace to send as the next packet.
Stats::Scalar numSendAttempted
Stats for instruction accesses replayed.
Stats::Scalar numSendSucceeded
Stats::Scalar numSendFailed
Stats::Scalar numRetrySucceeded
Stats::Scalar instLastTick
Last simulated tick by the FixedRetryGen.
Detailed Description
Generator to read protobuf trace containing memory requests at fixed timestamps, perform flow control and issue memory requests.
If L1 cache port sends packet succesfully, determine the tick to send the next packet else wait for retry from cache.
Definition at line 343 of file trace_cpu.hh.
Constructor & Destructor Documentation
FixedRetryGen()
TraceCPU::FixedRetryGen::FixedRetryGen (TraceCPU & _owner, const std::string & _name, MasterPort & _port, MasterID master_id, const std::string & trace_file) inline
Definition at line 429 of file trace_cpu.hh.
References TraceCPU::init().
Member Function Documentation
exit()
void TraceCPU::FixedRetryGen::exit ()
Exit the FixedRetryGen.
Definition at line 1112 of file trace_cpu.cc.
References TraceCPU::ElasticDataGen::InputStream::reset(), and TraceCPU::ElasticDataGen::trace.
init()
Tick TraceCPU::FixedRetryGen::init ()
Called from TraceCPU init().
Reads the first message from the input trace file and returns the send tick.
Returns
Tick when first packet must be sent
Definition at line 1048 of file trace_cpu.cc.
References DPRINTF, MaxTick, and panic.
Referenced by TraceCPU::init().
isTraceComplete()
bool TraceCPU::FixedRetryGen::isTraceComplete () inline
Returns the traceComplete variable which is set when end of the input trace file is reached.
Returns
bool true if traceComplete is set, false otherwise.
Definition at line 496 of file trace_cpu.hh.
Referenced by TraceCPU::schedIcacheNext().
name()
const std::string& TraceCPU::FixedRetryGen::name () const inline
Returns name of the FixedRetryGen instance.
Definition at line 460 of file trace_cpu.hh.
References addr, X86ISA::exit, MipsISA::pc, and AtomicRequestProtocol::send().
nextExecute()
bool TraceCPU::FixedRetryGen::nextExecute ()
Reads a line of the trace file.
Returns the tick when the next request should be generated. If the end of the file has been reached, it returns false.
Returns
bool false id end of file has been reached
Definition at line 1118 of file trace_cpu.cc.
References curTick(), DPRINTF, TraceCPU::ElasticDataGen::InputStream::read(), TraceCPU::ElasticDataGen::trace, and TraceCPU::ElasticDataGen::traceComplete.
regStats()
void TraceCPU::FixedRetryGen::regStats ()
Definition at line 1017 of file trace_cpu.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::name(), TraceCPU::ElasticDataGen::name(), TraceCPU::ElasticDataGen::numRetrySucceeded, TraceCPU::ElasticDataGen::numSendAttempted, TraceCPU::ElasticDataGen::numSendFailed, and TraceCPU::ElasticDataGen::numSendSucceeded.
Referenced by TraceCPU::regStats().
send()
bool TraceCPU::FixedRetryGen::send (Addr addr, unsigned size, const MemCmd & cmd, Request::FlagsType flags, Addr pc)
Creates a new request assigning the request parameters passed by the arguments.
Calls the port's sendTimingReq() and returns true if the packet was sent succesfully. It is called by tryNext()
Parameters
addr address of request
size size of request
cmd if it is a read or write request
flags associated request flags
pc instruction PC that generated the request
Returns
true if packet was sent successfully
Definition at line 1149 of file trace_cpu.cc.
References addr, Packet::dataDynamic(), MemCmd::isWrite(), TraceCPU::ElasticDataGen::masterID, TraceCPU::ElasticDataGen::port, TraceCPU::ElasticDataGen::retryPkt, and MasterPort::sendTimingReq().
tickDelta()
int64_t TraceCPU::FixedRetryGen::tickDelta () inline
Definition at line 498 of file trace_cpu.hh.
References TraceCPU::regStats().
Referenced by TraceCPU::schedIcacheNext().
tryNext()
bool TraceCPU::FixedRetryGen::tryNext ()
This tries to send current or retry packet and returns true if successfull.
It calls nextExecute() to read next message.
Returns
bool true if packet is sent successfully
Definition at line 1063 of file trace_cpu.cc.
References DPRINTF, TraceCPU::ElasticDataGen::numRetrySucceeded, TraceCPU::ElasticDataGen::numSendAttempted, TraceCPU::ElasticDataGen::numSendFailed, TraceCPU::ElasticDataGen::numSendSucceeded, TraceCPU::ElasticDataGen::port, TraceCPU::ElasticDataGen::retryPkt, MasterPort::sendTimingReq(), and TraceCPU::ElasticDataGen::traceComplete.
Referenced by TraceCPU::schedIcacheNext().
Member Data Documentation
currElement
TraceElement TraceCPU::FixedRetryGen::currElement private
Store an element read from the trace to send as the next packet.
Definition at line 535 of file trace_cpu.hh.
delta
int64_t TraceCPU::FixedRetryGen::delta private
Stores the difference in the send ticks of the current and last packets.
Keeping this signed to check overflow to a negative value which will be caught by assert(delta > 0)
Definition at line 527 of file trace_cpu.hh.
genName
std::string TraceCPU::FixedRetryGen::genName private
String to store the name of the FixedRetryGen.
Definition at line 517 of file trace_cpu.hh.
instLastTick
Stats::Scalar TraceCPU::FixedRetryGen::instLastTick private
Last simulated tick by the FixedRetryGen.
Definition at line 543 of file trace_cpu.hh.
masterID
const MasterID TraceCPU::FixedRetryGen::masterID private
MasterID used for the requests being sent.
Definition at line 511 of file trace_cpu.hh.
numRetrySucceeded
Stats::Scalar TraceCPU::FixedRetryGen::numRetrySucceeded private
Definition at line 541 of file trace_cpu.hh.
numSendAttempted
Stats::Scalar TraceCPU::FixedRetryGen::numSendAttempted private
Stats for instruction accesses replayed.
Definition at line 538 of file trace_cpu.hh.
numSendFailed
Stats::Scalar TraceCPU::FixedRetryGen::numSendFailed private
Definition at line 540 of file trace_cpu.hh.
numSendSucceeded
Stats::Scalar TraceCPU::FixedRetryGen::numSendSucceeded private
Definition at line 539 of file trace_cpu.hh.
owner
TraceCPU& TraceCPU::FixedRetryGen::owner private
Reference of the TraceCPU.
Definition at line 505 of file trace_cpu.hh.
port
MasterPort& TraceCPU::FixedRetryGen::port private
Reference of the port to be used to issue memory requests.
Definition at line 508 of file trace_cpu.hh.
retryPkt
PacketPtr TraceCPU::FixedRetryGen::retryPkt private
PacketPtr used to store the packet to retry.
Definition at line 520 of file trace_cpu.hh.
trace
InputStream TraceCPU::FixedRetryGen::trace private
Input stream used for reading the input trace file.
Definition at line 514 of file trace_cpu.hh.
traceComplete
bool TraceCPU::FixedRetryGen::traceComplete private
Set to true when end of trace is reached.
Definition at line 532 of file trace_cpu.hh.
The documentation for this class was generated from the following files:
cpu/trace/trace_cpu.hh
cpu/trace/trace_cpu.cc