gem5: DistEtherLink::Link Class Reference
DistEtherLink::Link Class Reference
Model base class for a single uni-directional link.
#include <dist_etherlink.hh>
Public Member Functions
Link (const std::string &name, DistEtherLink *p, EtherDump *d, Event *e)
~Link ()
const std::string name () const
bool busy () const
void setLocalInt (LocalIface *i)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
std::string objName
DistEtherLink * parent
LocalIface * localIface
EtherDump * dump
DistIface * distIface
Event * event
EthPacketPtr packet
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Model base class for a single uni-directional link.
The link will encapsulate and transfer Ethernet packets to/from the message server.
Definition at line 75 of file dist_etherlink.hh.
Constructor & Destructor Documentation
Link()
DistEtherLink::Link::Link (const std::string & name, DistEtherLink * p, EtherDump * d, Event * e) inline
Definition at line 87 of file dist_etherlink.hh.
~Link()
DistEtherLink::Link::~Link () inline
Definition at line 92 of file dist_etherlink.hh.
Member Function Documentation
busy()
bool DistEtherLink::Link::busy () const inline
Definition at line 95 of file dist_etherlink.hh.
References packet.
Referenced by DistEtherLink::LocalIface::isBusy().
name()
const std::string DistEtherLink::Link::name () const inline
Definition at line 94 of file dist_etherlink.hh.
References objName.
Referenced by DistEtherLink::RxLink::RxLink(), and DistEtherLink::TxLink::TxLink().
serialize()
void DistEtherLink::Link::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 212 of file dist_etherlink.cc.
References SERIALIZE_SCALAR.
Referenced by DistEtherLink::params(), and setLocalInt().
setLocalInt()
void DistEtherLink::Link::setLocalInt (LocalIface * i) inline
Definition at line 96 of file dist_etherlink.hh.
References ArmISA::i, serialize(), and unserialize().
Referenced by DistEtherLink::LocalIface::LocalIface().
unserialize()
void DistEtherLink::Link::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 228 of file dist_etherlink.cc.
References MipsISA::event, and UNSERIALIZE_SCALAR.
Referenced by DistEtherLink::params(), and setLocalInt().
Member Data Documentation
distIface
DistIface* DistEtherLink::Link::distIface protected
Definition at line 82 of file dist_etherlink.hh.
Referenced by DistEtherLink::TxLink::setDistInt().
dump
EtherDump* DistEtherLink::Link::dump protected
Definition at line 81 of file dist_etherlink.hh.
event
Event* DistEtherLink::Link::event protected
Definition at line 83 of file dist_etherlink.hh.
localIface
LocalIface* DistEtherLink::Link::localIface protected
Definition at line 80 of file dist_etherlink.hh.
objName
std::string DistEtherLink::Link::objName protected
Definition at line 78 of file dist_etherlink.hh.
Referenced by name().
packet
EthPacketPtr DistEtherLink::Link::packet protected
Definition at line 84 of file dist_etherlink.hh.
Referenced by busy(), and DistEtherLink::TxLink::setDistInt().
parent
DistEtherLink* DistEtherLink::Link::parent protected
Definition at line 79 of file dist_etherlink.hh.
The documentation for this class was generated from the following files:
dev/net/dist_etherlink.hh
dev/net/dist_etherlink.cc