gem5: X86ISA::Walker::WalkerState Class Reference
X86ISA::Walker::WalkerState Class Reference
#include <pagetable_walker.hh>
Public Member Functions
WalkerState (Walker *_walker, BaseTLB::Translation *_translation, const RequestPtr &_req, bool _isFunctional=false)
void initState (ThreadContext *_tc, BaseTLB::Mode _mode, bool _isTiming=false)
Fault startWalk ()
Fault startFunctional (Addr &addr, unsigned &logBytes)
bool recvPacket (PacketPtr pkt)
unsigned numInflight () const
bool isRetrying ()
bool wasStarted ()
bool isTiming ()
void retry ()
void squash ()
std::string name () const
Protected Attributes
Walker * walker
ThreadContext * tc
RequestPtr req
State state
State nextState
int dataSize
bool enableNX
unsigned inflight
TlbEntry entry
PacketPtr read
std::vector< PacketPtr > writes
Fault timingFault
TLB::Translation * translation
BaseTLB::Mode mode
bool functional
bool timing
bool retrying
bool started
bool squashed
Private Types
enum State {
Ready, Waiting, LongPML4, LongPDP,
LongPD, LongPTE, PAEPDP, PAEPD,
PAEPTE, PSEPD, PD, PTE
}
Private Member Functions
void setupWalk (Addr vaddr)
Fault stepWalk (PacketPtr &write)
void sendPackets ()
void endWalk ()
Fault pageFault (bool present)
Friends
class Walker
Detailed Description
Definition at line 80 of file pagetable_walker.hh.
Member Enumeration Documentation
State
enum X86ISA::Walker::WalkerState::State private
Enumerator
Ready
Waiting
LongPML4
LongPDP
LongPD
LongPTE
PAEPDP
PAEPD
PAEPTE
PSEPD
PD
PTE
Definition at line 84 of file pagetable_walker.hh.
Constructor & Destructor Documentation
WalkerState()
X86ISA::Walker::WalkerState::WalkerState (Walker * _walker, BaseTLB::Translation * _translation, const RequestPtr & _req, bool _isFunctional = false) inline
Definition at line 116 of file pagetable_walker.hh.
References X86ISA::addr, SimObject::initState(), and X86ISA::Walker::startFunctional().
Member Function Documentation
endWalk()
void X86ISA::Walker::WalkerState::endWalk () private
Definition at line 543 of file pagetable_walker.cc.
initState()
void X86ISA::Walker::WalkerState::initState (ThreadContext * _tc, BaseTLB::Mode _mode, bool _isTiming = false)
Definition at line 181 of file pagetable_walker.cc.
References ArmISA::mode.
Referenced by X86ISA::Walker::start(), and X86ISA::Walker::startFunctional().
isRetrying()
bool X86ISA::Walker::WalkerState::isRetrying ()
Definition at line 700 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::recvReqRetry().
isTiming()
bool X86ISA::Walker::WalkerState::isTiming ()
Definition at line 706 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::start().
name()
std::string X86ISA::Walker::WalkerState::name () const inline
Definition at line 136 of file pagetable_walker.hh.
References SimObject::name(), X86ISA::present, and MipsISA::vaddr.
numInflight()
unsigned X86ISA::Walker::WalkerState::numInflight () const
Definition at line 694 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::startWalkWrapper().
pageFault()
Fault X86ISA::Walker::WalkerState::pageFault (bool present) private
Definition at line 731 of file pagetable_walker.cc.
References DPRINTF, BaseTLB::Execute, X86ISA::MISCREG_M5_REG, ArmISA::mode, X86ISA::present, and BaseTLB::Read.
recvPacket()
bool X86ISA::Walker::WalkerState::recvPacket (PacketPtr pkt)
Definition at line 601 of file pagetable_walker.cc.
References Packet::headerDelay, Packet::isRead(), Packet::isResponse(), ArmISA::mode, NoFault, and Packet::payloadDelay.
Referenced by X86ISA::Walker::recvTimingResp().
retry()
void X86ISA::Walker::WalkerState::retry ()
Definition at line 724 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::recvReqRetry().
sendPackets()
void X86ISA::Walker::WalkerState::sendPackets () private
Definition at line 661 of file pagetable_walker.cc.
setupWalk()
void X86ISA::Walker::WalkerState::setupWalk (Addr vaddr) private
Definition at line 551 of file pagetable_walker.cc.
References X86ISA::addr, X86ISA::MISCREG_CR3, X86ISA::MISCREG_CR4, X86ISA::MISCREG_EFER, Request::PHYSICAL, MemCmd::ReadReq, Flags< T >::set(), Request::UNCACHEABLE, and MipsISA::vaddr.
squash()
void X86ISA::Walker::WalkerState::squash ()
Definition at line 718 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::startWalkWrapper().
startFunctional()
Fault X86ISA::Walker::WalkerState::startFunctional (Addr & addr, unsigned & logBytes)
Definition at line 258 of file pagetable_walker.cc.
References NoFault.
Referenced by X86ISA::Walker::startFunctional().
startWalk()
Fault X86ISA::Walker::WalkerState::startWalk ()
Definition at line 229 of file pagetable_walker.cc.
References NoFault.
Referenced by X86ISA::Walker::start(), and X86ISA::Walker::startWalkWrapper().
stepWalk()
Fault X86ISA::Walker::WalkerState::stepWalk (PacketPtr & write) private
Definition at line 282 of file pagetable_walker.cc.
References bits(), Packet::cmd, DPRINTF, BaseTLB::Execute, Packet::getLE(), Packet::getSize(), X86ISA::mask, ArmISA::mode, NoFault, panic, MemCmd::ReadReq, Packet::req, Flags< T >::set(), Packet::setLE(), Request::UNCACHEABLE, MipsISA::vaddr, and MemCmd::WriteReq.
wasStarted()
bool X86ISA::Walker::WalkerState::wasStarted ()
Definition at line 712 of file pagetable_walker.cc.
Referenced by X86ISA::Walker::startWalkWrapper().
Friends And Related Function Documentation
Walker
friend class Walker friend
Definition at line 82 of file pagetable_walker.hh.
Member Data Documentation
dataSize
int X86ISA::Walker::WalkerState::dataSize protected
Definition at line 101 of file pagetable_walker.hh.
enableNX
bool X86ISA::Walker::WalkerState::enableNX protected
Definition at line 102 of file pagetable_walker.hh.
entry
TlbEntry X86ISA::Walker::WalkerState::entry protected
Definition at line 104 of file pagetable_walker.hh.
functional
bool X86ISA::Walker::WalkerState::functional protected
Definition at line 110 of file pagetable_walker.hh.
inflight
unsigned X86ISA::Walker::WalkerState::inflight protected
Definition at line 103 of file pagetable_walker.hh.
mode
BaseTLB::Mode X86ISA::Walker::WalkerState::mode protected
Definition at line 109 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::startWalkWrapper().
nextState
State X86ISA::Walker::WalkerState::nextState protected
Definition at line 100 of file pagetable_walker.hh.
read
PacketPtr X86ISA::Walker::WalkerState::read protected
Definition at line 105 of file pagetable_walker.hh.
req
RequestPtr X86ISA::Walker::WalkerState::req protected
Definition at line 98 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::startWalkWrapper().
retrying
bool X86ISA::Walker::WalkerState::retrying protected
Definition at line 112 of file pagetable_walker.hh.
squashed
bool X86ISA::Walker::WalkerState::squashed protected
Definition at line 114 of file pagetable_walker.hh.
started
bool X86ISA::Walker::WalkerState::started protected
Definition at line 113 of file pagetable_walker.hh.
state
State X86ISA::Walker::WalkerState::state protected
Definition at line 99 of file pagetable_walker.hh.
tc
ThreadContext* X86ISA::Walker::WalkerState::tc protected
Definition at line 97 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::startWalkWrapper().
timing
bool X86ISA::Walker::WalkerState::timing protected
Definition at line 111 of file pagetable_walker.hh.
timingFault
Fault X86ISA::Walker::WalkerState::timingFault protected
Definition at line 107 of file pagetable_walker.hh.
translation
TLB::Translation* X86ISA::Walker::WalkerState::translation protected
Definition at line 108 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::startWalkWrapper().
walker
Walker* X86ISA::Walker::WalkerState::walker protected
Definition at line 96 of file pagetable_walker.hh.
writes
std::vector<PacketPtr> X86ISA::Walker::WalkerState::writes protected
Definition at line 106 of file pagetable_walker.hh.
The documentation for this class was generated from the following files:
arch/x86/pagetable_walker.hh
arch/x86/pagetable_walker.cc