gem5: ArmSystem Class Reference
ArmSystem Class Reference
#include <system.hh>
Public Types
typedef ArmSystemParams Params
Public Types inherited from System
typedef SystemParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
ArmSystem (Params *p)
~ArmSystem ()
virtual void initState ()
Initialise the system.
virtual Addr fixFuncEventAddr (Addr addr)
Fix up an address used to match PCs for hooking simulator events on to target function executions.
bool haveSecurity () const
Returns true if this system implements the Security Extensions.
bool haveLPAE () const
Returns true if this system implements the Large Physical Address Extension.
bool haveVirtualization () const
Returns true if this system implements the virtualization Extensions.
bool haveCrypto () const
Returns true if this system implements the Crypto Extension.
void setGenericTimer (GenericTimer *generic_timer)
Sets the pointer to the Generic Timer.
void setGIC (BaseGic *gic)
Sets the pointer to the GIC.
GenericTimer * getGenericTimer () const
Get a pointer to the system's generic timer model.
BaseGic * getGIC () const
Get a pointer to the system's GIC.
bool highestELIs64 () const
Returns true if the register width of the highest implemented exception level is 64 bits (ARMv8)
ExceptionLevel highestEL () const
Returns the highest implemented exception level.
Addr resetAddr () const
Returns the reset address if the highest implemented exception level is 64 bits (ARMv8)
bool haveLargeAsid64 () const
Returns true if ASID is 16 bits in AArch64 (ARMv8)
bool haveSVE () const
Returns true if SVE is implemented (ARMv8)
unsigned sveVL () const
Returns the SVE vector length at reset, in quadwords.
bool haveLSE () const
Returns true if LSE is implemented (ARMv8.1)
bool havePAN () const
Returns true if Priviledge Access Never is implemented.
uint8_t physAddrRange64 () const
Returns the supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8)
uint8_t physAddrRange () const
Returns the supported physical address range in bits.
Addr physAddrMask () const
Returns the physical address mask.
const AddrRange & m5opRange () const
Range used by memory-mapped m5 pseudo-ops if enabled.
bool haveSemihosting () const
Is Arm Semihosting support enabled?
Public Member Functions inherited from System
void init () override
After all objects have been created and all ports are connected, check that the system port is connected.
MasterPort & getSystemPort ()
Get a reference to the system port that can be used by non-structural simulation objects like processes or threads, or external entities like loaders and debuggers, etc, to access the memory system.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Additional function to return the Port of a memory object.
unsigned int cacheLineSize () const
Get the cache line size of the system.
bool schedule (PCEvent *event) override
bool remove (PCEvent *event) override
ThreadContext * getThreadContext (ContextID tid) const
unsigned numContexts () const
int numRunningContexts ()
Return number of running (non-halted) thread contexts in system.
KvmVM * getKvmVM ()
Get a pointer to the Kernel Virtual Machine (KVM) SimObject, if present.
bool validKvmEnvironment () const
Verify gem5 configuration will support KVM emulation.
PhysicalMemory & getPhysMem ()
Get a pointer to access the physical memory of the system.
Addr freeMemSize () const
Amount of physical memory that is still free.
Addr memSize () const
Amount of physical memory that exists.
bool isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
Arch getArch () const
Get the architecture.
ByteOrder getGuestByteOrder () const
Get the guest byte order.
Addr getPageBytes () const
Get the page bytes for the ISA.
Addr getPageShift () const
Get the number of bits worth of in-page address for the ISA.
ThermalModel * getThermalModel () const
The thermal model used for this system (if any).
MasterID getMasterId (const SimObject *master, std::string submaster=std::string())
Request an id used to create a request object in the system.
MasterID getGlobalMasterId (const std::string &master_name)
Registers a GLOBAL MasterID, which is a MasterID not related to any particular SimObject; since no SimObject is passed, the master gets registered by providing the full master name.
std::string getMasterName (MasterID master_id)
Get the name of an object for a given request id.
MasterID lookupMasterId (const SimObject *obj) const
Looks up the MasterID for a given SimObject returns an invalid MasterID (invldMasterId) if not found.
MasterID lookupMasterId (const std::string &name) const
Looks up the MasterID for a given object name string returns an invalid MasterID (invldMasterId) if not found.
MasterID maxMasters ()
Get the number of masters registered in the system.
void regStats () override
Callback to set stat parameters.
uint64_t incWorkItemsBegin ()
Called by pseudo_inst to track the number of work items started by this system.
uint64_t incWorkItemsEnd ()
Called by pseudo_inst to track the number of work items completed by this system.
int markWorkItem (int index)
Called by pseudo_inst to mark the cpus actively executing work items.
void workItemBegin (uint32_t tid, uint32_t workid)
void workItemEnd (uint32_t tid, uint32_t workid)
bool breakpoint ()
System (Params *p)
~System ()
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
const Params * params () const
Addr getKernelStart () const
Returns the address the kernel starts at.
Addr getKernelEnd () const
Returns the address the kernel ends at.
Addr getKernelEntry () const
Returns the address the entry point to the kernel code.
Addr allocPhysPages (int npages)
Allocate npages contiguous unused physical pages.
ContextID registerThreadContext (ThreadContext *tc, ContextID assigned=InvalidContextID)
void replaceThreadContext (ThreadContext *tc, ContextID context_id)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
bool isAtomicMode () const
Is the system in atomic mode?
bool isTimingMode () const
Is the system in timing mode?
bool bypassCaches () const
Should caches be bypassed?
Enums::MemoryMode getMemoryMode () const
Get the memory mode of the system.
void setMemoryMode (Enums::MemoryMode mode)
Change the memory mode of the system.
template<class T , typename... Args>
T * addFuncEvent (const SymbolTable *symtab, const char *lbl, const std::string &desc, Args... args)
Add a function-based event to the given function, to be looked up in the specified symbol table.
template<class T >
T * addFuncEvent (const SymbolTable *symtab, const char *lbl)
template<class T , typename... Args>
T * addFuncEventOrPanic (const SymbolTable *symtab, const char *lbl, Args... args)
template<class T , typename... Args>
T * addKernelFuncEvent (const char *lbl, Args... args)
Add a function-based event to a kernel symbol.
template<class T , typename... Args>
T * addKernelFuncEventOrPanic (const char *lbl, Args... args)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static ArmSystem * getArmSystem (System *sys)
Casts the provided System object into a valid ArmSystem, it fails otherwise.
static ArmSystem * getArmSystem (ThreadContext *tc)
Returns a valid ArmSystem pointer if using ARM ISA, it fails otherwise.
static bool haveSecurity (ThreadContext *tc)
Returns true if the system of a specific thread context implements the Security Extensions.
static bool haveVirtualization (ThreadContext *tc)
Returns true if the system of a specific thread context implements the virtualization Extensions.
static bool haveLPAE (ThreadContext *tc)
Returns true if the system of a specific thread context implements the Large Physical Address Extension.
static bool highestELIs64 (ThreadContext *tc)
Returns true if the register width of the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8)
static ExceptionLevel highestEL (ThreadContext *tc)
Returns the highest implemented exception level for the system of a specific thread context.
static bool haveEL (ThreadContext *tc, ExceptionLevel el)
Return true if the system implements a specific exception level.
static Addr resetAddr (ThreadContext *tc)
Returns the reset address if the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8)
static uint8_t physAddrRange (ThreadContext *tc)
Returns the supported physical address range in bits for the system of a specific thread context.
static Addr physAddrMask (ThreadContext *tc)
Returns the physical address mask for the system of a specific thread context.
static bool haveLargeAsid64 (ThreadContext *tc)
Returns true if ASID is 16 bits for the system of a specific thread context while in AArch64 (ARMv8)
static bool haveSemihosting (ThreadContext *tc)
Is Arm Semihosting support enabled?
static uint64_t callSemihosting64 (ThreadContext *tc, uint32_t op, uint64_t param)
Make a Semihosting call from aarch64.
static uint32_t callSemihosting32 (ThreadContext *tc, uint32_t op, uint32_t param)
Make a Semihosting call from aarch32.
Static Public Member Functions inherited from System
static void printSystems ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
bool multiProc
true if this a multiprocessor system
Public Attributes inherited from System
std::vector< ThreadContext * > threadContexts
const bool multiThread
Addr pagePtr
uint64_t init_param
PortProxy physProxy
Port to physical memory used for writing object files into ram at boot.
SymbolTable * kernelSymtab
kernel symbol table
ObjectFile * kernel
Object pointer for the kernel code.
MemoryImage kernelImage
std::vector< ObjectFile * > kernelExtras
Additional object files.
Addr kernelStart
Beginning of kernel code.
Addr kernelEnd
End of kernel code.
Addr kernelEntry
Entry point in the kernel to start at.
Addr loadAddrMask
Mask that should be anded for binary/symbol loading.
Addr loadAddrOffset
Offset that should be used for binary/symbol loading.
std::vector< BaseRemoteGDB * > remoteGDB
Counter totalNumInsts
std::map< std::pair< uint32_t, uint32_t >, Tick > lastWorkItemStarted
std::map< uint32_t, Stats::Histogram * > workItemStats
FutexMap futexMap
std::set< int > PIDs
Process set to track which PIDs have already been allocated.
std::list< BasicSignal > signalList
std::vector< RedirectPath * > redirectPaths
Protected Member Functions
ObjectFile * getBootLoader (ObjectFile *const obj)
Get a boot loader that matches the kernel.
Protected Member Functions inherited from System
std::string stripSystemName (const std::string &master_name) const
Strips off the system name from a master name.
MasterID _getMasterId (const SimObject *master, const std::string &master_name)
helper function for getMasterId
std::string leafMasterName (const SimObject *master, const std::string &submaster)
Helper function for constructing the full (sub)master name by providing the root master and the relative submaster name.
virtual void serializeSymtab (CheckpointOut &os) const
If needed, serialize additional symbol table entries for a specific subclass of this system.
virtual void unserializeSymtab (CheckpointIn &cp)
If needed, unserialize additional symbol table entries for a specific subclass of this system.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
Linux::DebugPrintkEvent * debugPrintkEvent
PC based event to skip the dprink() call and emulate its functionality.
std::vector< std::unique_ptr< ObjectFile > > bootLoaders
Bootloaders.
ObjectFile * bootldr
Pointer to the bootloader object.
const bool _haveSecurity
True if this system implements the Security Extensions.
const bool _haveLPAE
True if this system implements the Large Physical Address Extension.
const bool _haveVirtualization
True if this system implements the virtualization Extensions.
const bool _haveCrypto
True if this system implements the Crypto Extension.
GenericTimer * _genericTimer
Pointer to the Generic Timer wrapper.
BaseGic * _gic
const Addr _resetAddr
Reset address (ARMv8)
bool _highestELIs64
True if the register width of the highest implemented exception level is 64 bits (ARMv8)
const uint8_t _physAddrRange64
Supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8)
const bool _haveLargeAsid64
True if ASID is 16 bits in AArch64 (ARMv8)
const bool _haveSVE
True if SVE is implemented (ARMv8)
const unsigned _sveVL
SVE vector length at reset, in quadwords.
const bool _haveLSE
True if LSE is implemented (ARMv8.1)
const unsigned _havePAN
True if Priviledge Access Never is implemented.
const AddrRange _m5opRange
Range for memory-mapped m5 pseudo ops.
ArmSemihosting *const semihosting
True if the Semihosting interface is enabled.
Protected Attributes inherited from System
KvmVM *const kvmVM
PhysicalMemory physmem
Enums::MemoryMode memoryMode
const unsigned int _cacheLineSize
uint64_t workItemsBegin
uint64_t workItemsEnd
uint32_t numWorkIds
std::vector< bool > activeCpus
std::vector< MasterInfo > masters
This array is a per-system list of all devices capable of issuing a memory system request and an associated string for each master id.
ThermalModel * thermalModel
Params * _params
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Attributes inherited from System
static std::vector< System * > systemList
static int numSystemsRunning = 0
static const int maxPID = 32768
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 60 of file system.hh.
Member Typedef Documentation
Params
typedef ArmSystemParams ArmSystem::Params
Definition at line 163 of file system.hh.
Constructor & Destructor Documentation
ArmSystem()
ArmSystem::ArmSystem (Params * p)
Definition at line 59 of file system.cc.
References _highestELIs64, _physAddrRange64, _resetAddr, ObjectFile::Arm, ObjectFile::Arm64, bootldr, bootLoaders, createObjectFile(), debugPrintkEvent, debugSymbolTable, ObjectFile::entryPoint(), fatal, fatal_if, ObjectFile::getArch(), getBootLoader(), System::kernel, ObjectFile::loadGlobalSymbols(), warn, and warn_if.
Referenced by callSemihosting32(), and params().
~ArmSystem()
ArmSystem::~ArmSystem ()
Definition at line 201 of file system.cc.
References debugPrintkEvent.
Referenced by params().
Member Function Documentation
callSemihosting32()
uint32_t ArmSystem::callSemihosting32 (ThreadContext * tc, uint32_t op, uint32_t param) static
Make a Semihosting call from aarch32.
Definition at line 298 of file system.cc.
References ArmSystem(), ArmSemihosting::call32(), getArmSystem(), and semihosting.
Referenced by haveSemihosting().
callSemihosting64()
uint64_t ArmSystem::callSemihosting64 (ThreadContext * tc, uint32_t op, uint64_t param) static
Make a Semihosting call from aarch64.
Definition at line 290 of file system.cc.
References ArmSemihosting::call64(), getArmSystem(), and semihosting.
Referenced by haveSemihosting().
fixFuncEventAddr()
virtual Addr ArmSystem::fixFuncEventAddr (Addr addr) inline virtual
Fix up an address used to match PCs for hooking simulator events on to target function executions.
See comment in system.cc for details.
Reimplemented from System.
Definition at line 178 of file system.hh.
References addr.
getArmSystem() [1/2]
ArmSystem * ArmSystem::getArmSystem (System * sys) static
Casts the provided System object into a valid ArmSystem, it fails otherwise.
Parameters
sys System object to cast
Definition at line 179 of file system.cc.
Referenced by callSemihosting32(), callSemihosting64(), haveLargeAsid64(), haveLPAE(), haveSecurity(), haveSemihosting(), haveVirtualization(), highestEL(), highestELIs64(), physAddrMask(), physAddrRange(), and resetAddr().
getArmSystem() [2/2]
ArmSystem * ArmSystem::getArmSystem (ThreadContext * tc) static
Returns a valid ArmSystem pointer if using ARM ISA, it fails otherwise.
Definition at line 187 of file system.cc.
References ThreadContext::getSystemPtr().
getBootLoader()
ObjectFile * ArmSystem::getBootLoader (ObjectFile *const obj) protected
Get a boot loader that matches the kernel.
Parameters
obj Kernel binary
Returns
Pointer to boot loader ObjectFile or nullptr if there is no matching boot loader.
Definition at line 208 of file system.cc.
References bootLoaders, and ObjectFile::getArch().
Referenced by ArmSystem().
getGenericTimer()
GenericTimer* ArmSystem::getGenericTimer () const inline
Get a pointer to the system's generic timer model.
Definition at line 220 of file system.hh.
References _genericTimer.
Referenced by ArmISA::ISA::getGenericTimer(), and ArmISA::ISA::readMiscReg().
getGIC()
BaseGic* ArmSystem::getGIC () const inline
Get a pointer to the system's GIC.
Definition at line 223 of file system.hh.
References _gic.
Referenced by initState(), and ArmISA::ISA::startup().
haveCrypto()
bool ArmSystem::haveCrypto () const inline
Returns true if this system implements the Crypto Extension.
Definition at line 205 of file system.hh.
References _haveCrypto.
Referenced by ArmISA::ISA::ISA().
haveEL()
bool ArmSystem::haveEL (ThreadContext * tc, ExceptionLevel el) static
Return true if the system implements a specific exception level.
Definition at line 243 of file system.cc.
References ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, haveSecurity(), haveVirtualization(), and warn.
Referenced by ArmISA::badMode(), ArmISA::badMode32(), ArmISA::ArmStaticInst::checkForWFxTrap32(), ArmISA::ArmStaticInst::checkForWFxTrap64(), ArmISA::ArmStaticInst::generalExceptionsToAArch64(), haveSemihosting(), ArmISA::illegalExceptionReturn(), ArmISA::isSecureBelowEL3(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), ArmISA::readMPIDR(), ArmISA::ArmStaticInst::softwareBreakpoint32(), and ArmISA::ArmStaticInst::trapWFx().
haveLargeAsid64() [1/2]
bool ArmSystem::haveLargeAsid64 () const inline
Returns true if ASID is 16 bits in AArch64 (ARMv8)
Definition at line 244 of file system.hh.
References _haveLargeAsid64.
Referenced by haveLargeAsid64(), haveSemihosting(), ArmISA::ISA::ISA(), and ArmISA::TableWalker::TableWalker().
haveLargeAsid64() [2/2]
bool ArmSystem::haveLargeAsid64 (ThreadContext * tc) static
Returns true if ASID is 16 bits for the system of a specific thread context while in AArch64 (ARMv8)
Definition at line 278 of file system.cc.
References getArmSystem(), and haveLargeAsid64().
haveLPAE() [1/2]
bool ArmSystem::haveLPAE () const inline
Returns true if this system implements the Large Physical Address Extension.
Definition at line 195 of file system.hh.
References _haveLPAE.
Referenced by haveLPAE(), haveSemihosting(), ArmISA::ISA::ISA(), ArmISA::longDescFormatInUse(), and ArmISA::TableWalker::TableWalker().
haveLPAE() [2/2]
bool ArmSystem::haveLPAE (ThreadContext * tc) static
Returns true if the system of a specific thread context implements the Large Physical Address Extension.
Definition at line 219 of file system.cc.
References FullSystem, getArmSystem(), and haveLPAE().
haveLSE()
bool ArmSystem::haveLSE () const inline
Returns true if LSE is implemented (ARMv8.1)
Definition at line 253 of file system.hh.
References _haveLSE.
Referenced by ArmISA::ISA::ISA().
havePAN()
bool ArmSystem::havePAN () const inline
Returns true if Priviledge Access Never is implemented.
Definition at line 256 of file system.hh.
References _havePAN.
Referenced by ArmISA::ISA::ISA().
haveSecurity() [1/2]
bool ArmSystem::haveSecurity () const inline
Returns true if this system implements the Security Extensions.
Definition at line 191 of file system.hh.
References _haveSecurity.
Referenced by ArmISA::AbortFault< DataAbort >::abortDisable(), ArmISA::Interrupt::abortDisable(), ArmISA::FastInterrupt::abortDisable(), ArmISA::canReadAArch64SysReg(), ArmISA::canWriteAArch64SysReg(), ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), ArmISA::ArmStaticInst::checkFPAdvSIMDTrap64(), ArmISA::ArmStaticInst::checkSveTrap(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), ArmISA::ELUsingAArch32K(), ArmISA::FastInterrupt::fiqDisable(), ArmISA::ArmFault::getVector(), ArmISA::Reset::getVector(), ArmISA::ArmFault::getVector64(), Gicv3Distributor::Gicv3Distributor(), Gicv3CPUInterface::haveEL(), haveEL(), haveSecurity(), haveSemihosting(), ArmISA::inSecureState(), Gicv3CPUInterface::inSecureState(), ArmISA::ArmFault::invoke(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::ISA::ISA(), ArmISA::purifyTaggedAddr(), ArmISA::Interrupt::routeToMonitor(), ArmISA::FastInterrupt::routeToMonitor(), ArmISA::SystemError::routeToMonitor(), ArmISA::snsBankedIndex(), ArmISA::TableWalker::TableWalker(), MiscRegOp64::trap(), and ArmISA::ArmFault::update().
haveSecurity() [2/2]
bool ArmSystem::haveSecurity (ThreadContext * tc) static
Returns true if the system of a specific thread context implements the Security Extensions.
Definition at line 195 of file system.cc.
References FullSystem, getArmSystem(), and haveSecurity().
haveSemihosting() [1/2]
bool ArmSystem::haveSemihosting () const inline
Is Arm Semihosting support enabled?
Definition at line 285 of file system.hh.
References callSemihosting32(), callSemihosting64(), ArmISA::el, getArmSystem(), haveEL(), haveLargeAsid64(), haveLPAE(), haveSecurity(), haveVirtualization(), highestEL(), highestELIs64(), X86ISA::op, physAddrMask(), physAddrRange(), and resetAddr().
Referenced by haveSemihosting().
haveSemihosting() [2/2]
bool ArmSystem::haveSemihosting (ThreadContext * tc) static
Is Arm Semihosting support enabled?
Definition at line 284 of file system.cc.
References FullSystem, getArmSystem(), and haveSemihosting().
haveSVE()
bool ArmSystem::haveSVE () const inline
Returns true if SVE is implemented (ARMv8)
Definition at line 247 of file system.hh.
References _haveSVE.
Referenced by ArmISA::ISA::ISA().
haveVirtualization() [1/2]
bool ArmSystem::haveVirtualization () const inline
Returns true if this system implements the virtualization Extensions.
Definition at line 200 of file system.hh.
References _haveVirtualization.
Referenced by ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), ArmISA::ArmStaticInst::checkFPAdvSIMDTrap64(), ArmISA::TLB::checkPermissions64(), ArmISA::ArmStaticInst::checkSveTrap(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), ArmISA::ELIsInHost(), ArmISA::ELUsingAArch32K(), ArmISA::FastInterrupt::fiqDisable(), ArmISA::ArmFault::getVector(), ArmISA::Reset::getVector(), ArmISA::ArmFault::getVector64(), Gicv3CPUInterface::haveEL(), haveEL(), haveSemihosting(), haveVirtualization(), ArmISA::ArmFault::invoke(), ArmISA::Reset::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::ISA::ISA(), ArmISA::purifyTaggedAddr(), ArmISA::SoftwareBreakpoint::routeToHyp(), ArmISA::TableWalker::TableWalker(), MiscRegOp64::trap(), and ArmISA::ArmFault::update().
haveVirtualization() [2/2]
bool ArmSystem::haveVirtualization (ThreadContext * tc) static
Returns true if the system of a specific thread context implements the virtualization Extensions.
Definition at line 225 of file system.cc.
References FullSystem, getArmSystem(), and haveVirtualization().
highestEL() [1/2]
ExceptionLevel ArmSystem::highestEL () const inline
Returns the highest implemented exception level.
Definition at line 230 of file system.hh.
References ArmISA::EL1, ArmISA::EL2, and ArmISA::EL3.
Referenced by ArmISA::canReadAArch64SysReg(), ArmISA::ISA::clear64(), ArmISA::ELUsingAArch32K(), haveSemihosting(), and highestEL().
highestEL() [2/2]
ExceptionLevel ArmSystem::highestEL (ThreadContext * tc) static
Returns the highest implemented exception level for the system of a specific thread context.
Definition at line 237 of file system.cc.
References ArmISA::EL1, FullSystem, getArmSystem(), and highestEL().
highestELIs64() [1/2]
bool ArmSystem::highestELIs64 () const inline
Returns true if the register width of the highest implemented exception level is 64 bits (ARMv8)
Definition at line 227 of file system.hh.
References _highestELIs64.
Referenced by ArmISA::ISA::clear(), ArmISA::ELUsingAArch32K(), Trace::TarmacTracer::getInstRecord(), haveSemihosting(), highestELIs64(), ArmISA::illegalExceptionReturn(), ArmISA::Reset::invoke(), ArmISA::ISA::ISA(), ArmISA::ArmFault::setSyndrome(), ArmISA::snsBankedIndex(), LinuxArmSystem::startup(), and ArmISA::Interrupts::takeInt().
highestELIs64() [2/2]
bool ArmSystem::highestELIs64 (ThreadContext * tc) static
Returns true if the register width of the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8)
Definition at line 231 of file system.cc.
References FullSystem, getArmSystem(), and highestELIs64().
initState()
void ArmSystem::initState () virtual
Initialise the system.
Reimplemented from SimObject.
Reimplemented in GenericArmSystem, LinuxArmSystem, and FreebsdArmSystem.
Definition at line 134 of file system.cc.
References _highestELIs64, bootldr, ImageFile::buildImage(), ObjectFile::entryPoint(), fatal, getGIC(), BaseGic::GIC_V2, ArmISA::i, inform, System::initState(), System::kernelEntry, System::loadAddrMask, System::loadAddrOffset, MipsISA::p, params(), System::physProxy, BaseGic::supportsVersion(), System::threadContexts, and MemoryImage::write().
Referenced by GenericArmSystem::initState(), params(), and GenericArmSystem::~GenericArmSystem().
m5opRange()
const AddrRange& ArmSystem::m5opRange () const inline
Range used by memory-mapped m5 pseudo-ops if enabled.
Returns an invalid/empty range if disabled.
Definition at line 282 of file system.hh.
References _m5opRange.
Referenced by ArmISA::TLB::TLB().
params()
const Params* ArmSystem::params () const inline
Definition at line 165 of file system.hh.
References System::_params, ArmSystem(), initState(), MipsISA::p, and ~ArmSystem().
Referenced by initState().
physAddrMask() [1/2]
Addr ArmSystem::physAddrMask () const inline
Returns the physical address mask.
Definition at line 273 of file system.hh.
References ArmISA::mask, and physAddrRange().
Referenced by haveSemihosting(), and physAddrMask().
physAddrMask() [2/2]
Addr ArmSystem::physAddrMask (ThreadContext * tc) static
Returns the physical address mask for the system of a specific thread context.
Definition at line 272 of file system.cc.
References getArmSystem(), and physAddrMask().
physAddrRange() [1/2]
uint8_t ArmSystem::physAddrRange () const inline
Returns the supported physical address range in bits.
Definition at line 263 of file system.hh.
References _physAddrRange64.
Referenced by haveSemihosting(), ArmISA::ISA::ISA(), physAddrMask(), physAddrRange(), and ArmISA::TableWalker::TableWalker().
physAddrRange() [2/2]
uint8_t ArmSystem::physAddrRange (ThreadContext * tc) static
Returns the supported physical address range in bits for the system of a specific thread context.
Definition at line 266 of file system.cc.
References getArmSystem(), and physAddrRange().
physAddrRange64()
uint8_t ArmSystem::physAddrRange64 () const inline
Returns the supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8)
Definition at line 260 of file system.hh.
References _physAddrRange64.
resetAddr() [1/2]
Addr ArmSystem::resetAddr () const inline
Returns the reset address if the highest implemented exception level is 64 bits (ARMv8)
Definition at line 241 of file system.hh.
References _resetAddr.
Referenced by ArmISA::ISA::clear32(), ArmISA::ISA::clear64(), haveSemihosting(), ArmISA::Reset::invoke(), and resetAddr().
resetAddr() [2/2]
Addr ArmSystem::resetAddr (ThreadContext * tc) static
Returns the reset address if the highest implemented exception level for the system of a specific thread context is 64 bits (ARMv8)
Definition at line 260 of file system.cc.
References getArmSystem(), and resetAddr().
setGenericTimer()
void ArmSystem::setGenericTimer (GenericTimer * generic_timer) inline
Sets the pointer to the Generic Timer.
Definition at line 208 of file system.hh.
Referenced by GenericTimer::GenericTimer().
setGIC()
void ArmSystem::setGIC (BaseGic * gic) inline
Sets the pointer to the GIC.
Definition at line 214 of file system.hh.
References ArmISA::gic.
Referenced by BaseGic::init(), and Gicv3::unserialize().
sveVL()
unsigned ArmSystem::sveVL () const inline
Returns the SVE vector length at reset, in quadwords.
Definition at line 250 of file system.hh.
References _sveVL.
Referenced by ArmISA::ISA::ISA().
Member Data Documentation
_genericTimer
GenericTimer* ArmSystem::_genericTimer protected
Pointer to the Generic Timer wrapper.
Definition at line 100 of file system.hh.
Referenced by getGenericTimer().
_gic
BaseGic* ArmSystem::_gic protected
Definition at line 101 of file system.hh.
Referenced by getGIC().
_haveCrypto
const bool ArmSystem::_haveCrypto protected
True if this system implements the Crypto Extension.
Definition at line 95 of file system.hh.
Referenced by haveCrypto().
_haveLargeAsid64
const bool ArmSystem::_haveLargeAsid64 protected
True if ASID is 16 bits in AArch64 (ARMv8)
Definition at line 123 of file system.hh.
Referenced by haveLargeAsid64().
_haveLPAE
const bool ArmSystem::_haveLPAE protected
True if this system implements the Large Physical Address Extension.
Definition at line 85 of file system.hh.
Referenced by haveLPAE().
_haveLSE
const bool ArmSystem::_haveLSE protected
True if LSE is implemented (ARMv8.1)
Definition at line 136 of file system.hh.
Referenced by haveLSE().
_havePAN
const unsigned ArmSystem::_havePAN protected
True if Priviledge Access Never is implemented.
Definition at line 139 of file system.hh.
Referenced by havePAN().
_haveSecurity
const bool ArmSystem::_haveSecurity protected
True if this system implements the Security Extensions.
Definition at line 80 of file system.hh.
Referenced by haveSecurity().
_haveSVE
const bool ArmSystem::_haveSVE protected
True if SVE is implemented (ARMv8)
Definition at line 128 of file system.hh.
Referenced by haveSVE().
_haveVirtualization
const bool ArmSystem::_haveVirtualization protected
True if this system implements the virtualization Extensions.
Definition at line 90 of file system.hh.
Referenced by haveVirtualization().
_highestELIs64
bool ArmSystem::_highestELIs64 protected
True if the register width of the highest implemented exception level is 64 bits (ARMv8)
Definition at line 112 of file system.hh.
Referenced by ArmSystem(), highestELIs64(), and initState().
_m5opRange
const AddrRange ArmSystem::_m5opRange protected
Range for memory-mapped m5 pseudo ops.
The range will be invalid/empty if disabled.
Definition at line 145 of file system.hh.
Referenced by m5opRange().
_physAddrRange64
const uint8_t ArmSystem::_physAddrRange64 protected
Supported physical address range in bits if the highest implemented exception level is 64 bits (ARMv8)
Definition at line 118 of file system.hh.
Referenced by ArmSystem(), physAddrRange(), and physAddrRange64().
_resetAddr
const Addr ArmSystem::_resetAddr protected
Reset address (ARMv8)
Definition at line 106 of file system.hh.
Referenced by ArmSystem(), and resetAddr().
_sveVL
const unsigned ArmSystem::_sveVL protected
SVE vector length at reset, in quadwords.
Definition at line 131 of file system.hh.
Referenced by sveVL().
bootldr
ObjectFile* ArmSystem::bootldr protected
Pointer to the bootloader object.
Definition at line 75 of file system.hh.
Referenced by ArmSystem(), and initState().
bootLoaders
std::vector<std::unique_ptr<ObjectFile> > ArmSystem::bootLoaders protected
Bootloaders.
Definition at line 70 of file system.hh.
Referenced by ArmSystem(), and getBootLoader().
debugPrintkEvent
Linux::DebugPrintkEvent* ArmSystem::debugPrintkEvent protected
PC based event to skip the dprink() call and emulate its functionality.
Definition at line 67 of file system.hh.
Referenced by ArmSystem(), and ~ArmSystem().
multiProc
bool ArmSystem::multiProc
true if this a multiprocessor system
Definition at line 188 of file system.hh.
Referenced by ArmISA::getMPIDR().
semihosting
ArmSemihosting* const ArmSystem::semihosting protected
True if the Semihosting interface is enabled.
Definition at line 150 of file system.hh.
Referenced by callSemihosting32(), and callSemihosting64().
The documentation for this class was generated from the following files:
arch/arm/system.hh
arch/arm/system.cc