gem5: tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF > Class Template Reference abstract
#include <initiator_socket.hh>
Public Member Functions
virtual ~tlm_base_initiator_socket_b ()
virtual sc_core::sc_port_b< FW_IF > & get_base_port ()=0
virtual sc_core::sc_port_b< FW_IF > const & get_base_port () const =0
virtual BW_IF & get_base_interface ()=0
virtual BW_IF const & get_base_interface () const =0
virtual sc_core::sc_export< BW_IF > & get_base_export ()=0
virtual sc_core::sc_export< BW_IF > const & get_base_export () const =0
Detailed Description
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>>
class tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >
Definition at line 34 of file initiator_socket.hh.
Constructor & Destructor Documentation
~tlm_base_initiator_socket_b()
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::~tlm_base_initiator_socket_b () inline virtual
Definition at line 37 of file initiator_socket.hh.
References tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_export(), tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_interface(), and tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_port().
Member Function Documentation
get_base_export() [1/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_export<BW_IF>& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_export () pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), and tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::~tlm_base_initiator_socket_b().
get_base_export() [2/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_export<BW_IF> const& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_export () const pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
get_base_interface() [1/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual BW_IF& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_interface () pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::~tlm_base_initiator_socket_b().
get_base_interface() [2/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual BW_IF const& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_interface () const pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >.
get_base_port() [1/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_port_b<FW_IF>& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_port () pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Referenced by tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), and tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::~tlm_base_initiator_socket_b().
get_base_port() [2/2]
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_port_b<FW_IF> const& tlm::tlm_base_initiator_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_port () const pure virtual
Implemented in tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
The documentation for this class was generated from the following file:
systemc/ext/tlm_core/2/sockets/initiator_socket.hh