gem5: Net::Ip6Ptr Class Reference
Net::Ip6Ptr Class Reference
#include <inet.hh>
Public Member Functions
Ip6Ptr ()
Ip6Ptr (const EthPacketPtr &ptr)
Ip6Ptr (const EthPtr &ptr)
Ip6Ptr (const Ip6Ptr &ptr)
Ip6Hdr * get ()
Ip6Hdr * operator-> ()
Ip6Hdr & operator* ()
const Ip6Hdr * get () const
const Ip6Hdr * operator-> () const
const Ip6Hdr & operator* () const
const Ip6Ptr & operator= (const EthPacketPtr &ptr)
const Ip6Ptr & operator= (const EthPtr &ptr)
const Ip6Ptr & operator= (const Ip6Ptr &ptr)
const EthPacketPtr packet () const
EthPacketPtr packet ()
bool operator! () const
operator bool () const
int off () const
int pstart () const
Protected Member Functions
void set (const EthPacketPtr &ptr)
Protected Attributes
EthPacketPtr p
bool eth_hdr_vlan
Friends
class TcpPtr
class UdpPtr
Detailed Description
Definition at line 394 of file inet.hh.
Constructor & Destructor Documentation
Ip6Ptr() [1/4]
Net::Ip6Ptr::Ip6Ptr () inline
Definition at line 417 of file inet.hh.
Ip6Ptr() [2/4]
Net::Ip6Ptr::Ip6Ptr (const EthPacketPtr & ptr) inline
Definition at line 418 of file inet.hh.
Ip6Ptr() [3/4]
Net::Ip6Ptr::Ip6Ptr (const EthPtr & ptr) inline
Definition at line 419 of file inet.hh.
References Net::EthPtr::p.
Ip6Ptr() [4/4]
Net::Ip6Ptr::Ip6Ptr (const Ip6Ptr & ptr) inline
Definition at line 420 of file inet.hh.
Member Function Documentation
get() [1/2]
Ip6Hdr* Net::Ip6Ptr::get () inline
Definition at line 422 of file inet.hh.
get() [2/2]
const Ip6Hdr* Net::Ip6Ptr::get () const inline
Definition at line 427 of file inet.hh.
off()
int Net::Ip6Ptr::off () const inline
Definition at line 444 of file inet.hh.
operator bool()
Net::Ip6Ptr::operator bool () const inline
Definition at line 443 of file inet.hh.
operator!()
bool Net::Ip6Ptr::operator! () const inline
Definition at line 442 of file inet.hh.
References MipsISA::p.
operator*() [1/2]
Ip6Hdr& Net::Ip6Ptr::operator* () inline
Definition at line 425 of file inet.hh.
operator*() [2/2]
const Ip6Hdr& Net::Ip6Ptr::operator* () const inline
Definition at line 431 of file inet.hh.
operator->() [1/2]
Ip6Hdr* Net::Ip6Ptr::operator-> () inline
Definition at line 424 of file inet.hh.
operator->() [2/2]
const Ip6Hdr* Net::Ip6Ptr::operator-> () const inline
Definition at line 430 of file inet.hh.
operator=() [1/3]
const Ip6Ptr& Net::Ip6Ptr::operator= (const EthPacketPtr & ptr) inline
Definition at line 433 of file inet.hh.
operator=() [2/3]
const Ip6Ptr& Net::Ip6Ptr::operator= (const EthPtr & ptr) inline
Definition at line 435 of file inet.hh.
References Net::EthPtr::p.
operator=() [3/3]
const Ip6Ptr& Net::Ip6Ptr::operator= (const Ip6Ptr & ptr) inline
Definition at line 437 of file inet.hh.
References p.
packet() [1/2]
const EthPacketPtr Net::Ip6Ptr::packet () const inline
Definition at line 440 of file inet.hh.
References MipsISA::p.
packet() [2/2]
EthPacketPtr Net::Ip6Ptr::packet () inline
Definition at line 441 of file inet.hh.
References MipsISA::p.
pstart()
int Net::Ip6Ptr::pstart () const inline
Definition at line 445 of file inet.hh.
References Net::EthAddr::size().
Referenced by Net::hsplit().
set()
void Net::Ip6Ptr::set (const EthPacketPtr & ptr) inline protected
Definition at line 402 of file inet.hh.
References Net::EthHdr::isVlan(), and Net::EthHdr::type().
Friends And Related Function Documentation
TcpPtr
friend class TcpPtr friend
Definition at line 397 of file inet.hh.
UdpPtr
friend class UdpPtr friend
Definition at line 398 of file inet.hh.
Member Data Documentation
eth_hdr_vlan
bool Net::Ip6Ptr::eth_hdr_vlan protected
Definition at line 400 of file inet.hh.
p
EthPacketPtr Net::Ip6Ptr::p protected
Definition at line 399 of file inet.hh.
Referenced by operator=().
The documentation for this class was generated from the following file:
base/inet.hh