gem5: sc_gem5::ScEvent Class Reference
sc_gem5::ScEvent Class Reference
#include <sched_event.hh>
Public Member Functions
ScEvent (std::function< void()> work)
~ScEvent ()
bool scheduled ()
ScEvents * scheduledOn ()
void when (Tick w)
Tick when ()
void run ()
Private Member Functions
void schedule (ScEvents &events, Tick w)
void deschedule ()
Private Attributes
std::function< void()> work
Tick _when
ScEvents * _events
ScEvents::iterator _it
Friends
class Scheduler
Detailed Description
Definition at line 45 of file sched_event.hh.
Constructor & Destructor Documentation
ScEvent()
sc_gem5::ScEvent::ScEvent (std::function< void()> work) inline
Definition at line 74 of file sched_event.hh.
References ~ScEvent().
~ScEvent()
sc_gem5::ScEvent::~ScEvent ()
Definition at line 37 of file sched_event.cc.
References sc_gem5::Scheduler::deschedule(), scheduled(), and sc_gem5::scheduler.
Referenced by ScEvent().
Member Function Documentation
deschedule()
void sc_gem5::ScEvent::deschedule () inline private
Definition at line 67 of file sched_event.hh.
References scheduled().
Referenced by run().
run()
void sc_gem5::ScEvent::run () inline
Definition at line 86 of file sched_event.hh.
References deschedule(), and work.
schedule()
void sc_gem5::ScEvent::schedule (ScEvents & events, Tick w) inline private
Definition at line 56 of file sched_event.hh.
References scheduled(), and when().
scheduled()
bool sc_gem5::ScEvent::scheduled () inline
Definition at line 80 of file sched_event.hh.
Referenced by sc_gem5::Event::cancel(), deschedule(), sc_gem5::Event::notify(), sc_gem5::Event::notifyDelayed(), schedule(), sc_gem5::ClockTick::~ClockTick(), sc_gem5::Event::~Event(), sc_core::sc_clock::~sc_clock(), and ~ScEvent().
scheduledOn()
ScEvents* sc_gem5::ScEvent::scheduledOn () inline
Definition at line 81 of file sched_event.hh.
References _events.
when() [1/2]
void sc_gem5::ScEvent::when (Tick w) inline
Definition at line 83 of file sched_event.hh.
References MipsISA::w.
Referenced by sc_gem5::Scheduler::deschedule(), and sc_gem5::Event::notify().
when() [2/2]
Tick sc_gem5::ScEvent::when () inline
Definition at line 84 of file sched_event.hh.
References _when.
Referenced by schedule().
Friends And Related Function Documentation
Scheduler
friend class Scheduler friend
Definition at line 53 of file sched_event.hh.
Member Data Documentation
_events
ScEvents* sc_gem5::ScEvent::_events private
Definition at line 50 of file sched_event.hh.
Referenced by scheduledOn().
_it
ScEvents::iterator sc_gem5::ScEvent::_it private
Definition at line 51 of file sched_event.hh.
_when
Tick sc_gem5::ScEvent::_when private
Definition at line 49 of file sched_event.hh.
Referenced by when().
work
std::function<void()> sc_gem5::ScEvent::work private
Definition at line 48 of file sched_event.hh.
Referenced by run().
The documentation for this class was generated from the following files:
systemc/core/sched_event.hh
systemc/core/sched_event.cc