gem5: sc_core::sc_in< sc_dt::sc_biguint< W > > Class Reference
sc_core::sc_in< sc_dt::sc_biguint< W > > Class Reference
#include <scx_signal_unsigned.h>
Public Types
typedef sc_dt::sc_biguint< W > data_type
typedef sc_signal_in_if< sc_dt::sc_biguint< W > > if_type
typedef sc_port< if_type, 1, SC_ONE_OR_MORE_BOUND > base_type
typedef sc_in< sc_dt::sc_biguint< W > > this_type
typedef if_type in_if_type
typedef base_type in_port_type
typedef sc_signal_inout_if< sc_dt::sc_biguint< W > > inout_if_type
typedef sc_inout< sc_dt::sc_biguint< W > > inout_port_type
Public Member Functions
void bind (const in_if_type &interface_)
void operator() (const in_if_type &interface_)
void bind (in_port_type &parent_)
void operator() (in_port_type &parent_)
void bind (inout_port_type &parent_)
void operator() (inout_port_type &parent_)
sc_in ()
sc_in (const char *name_)
sc_in (const in_if_type &interface_)
sc_in (const char *name_, const in_if_type &interface_)
sc_in (in_port_type &parent_)
sc_in (const char *name_, in_port_type &parent_)
sc_in (inout_port_type &parent_)
sc_in (const char *name_, inout_port_type &parent_)
sc_in (this_type &parent_)
sc_in (const char *name_, this_type &parent_)
virtual ~sc_in ()
sc_dt::sc_unsigned_bitref_r operator[] (int i) const
sc_dt::sc_unsigned_bitref_r bit (int i) const
sc_dt::sc_unsigned_subref_r operator() (int left, int right) const
sc_dt::sc_unsigned_subref_r range (int left, int right) const
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_dt::sc_biguint< W > & read () const
operator const sc_dt::sc_biguint< W > & () const
bool event () const
sc_event_finder & value_changed () const
bool and_reduce () const
bool nand_reduce () const
bool nor_reduce () const
bool or_reduce () const
bool xnor_reduce () const
bool xor_reduce () const
virtual void end_of_elaboration ()
virtual const char * kind () const
void add_trace (sc_trace_file *tf_, const std::string &name_) const
virtual int concat_length (bool *xz_present_p) const
virtual sc_dt::uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_dt::sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_dt::sc_digit *dst_p, int low_i) const
Public Member Functions inherited from sc_core::sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_in_if< sc_dt::sc_biguint< W > > &interface)
sc_port (const char *name, const sc_signal_in_if< sc_dt::sc_biguint< W > > &interface)
sc_port (sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > > &parent)
sc_port (sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, N, P > &parent)
sc_port (const char *name, sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, N, P > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >
void operator() (sc_signal_in_if< sc_dt::sc_biguint< W > > &i)
void operator() (sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > > &p)
virtual void bind (sc_signal_in_if< sc_dt::sc_biguint< W > > &i)
virtual void bind (sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > > &p)
sc_signal_in_if< sc_dt::sc_biguint< W > > * operator-> ()
const sc_signal_in_if< sc_dt::sc_biguint< W > > * operator-> () const
sc_signal_in_if< sc_dt::sc_biguint< W > > * operator[] (int n)
const sc_signal_in_if< sc_dt::sc_biguint< W > > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
virtual int vbind (sc_interface &interface_)
virtual int vbind (sc_port_base &parent_)
void remove_traces () const
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
sc_trace_params_vec * m_traces
Private Member Functions
sc_in (const sc_in< sc_dt::sc_biguint< W > > &)
sc_in< sc_dt::sc_biguint< W > > & operator= (const sc_in< sc_dt::sc_biguint< W > > &)
Detailed Description
Definition at line 925 of file scx_signal_unsigned.h.
Member Typedef Documentation
base_type
typedef sc_port<if_type,1,SC_ONE_OR_MORE_BOUND> sc_core::sc_in< sc_dt::sc_biguint< W > >::base_type
Definition at line 936 of file scx_signal_unsigned.h.
data_type
typedef sc_dt::sc_biguint<W> sc_core::sc_in< sc_dt::sc_biguint< W > >::data_type
Definition at line 934 of file scx_signal_unsigned.h.
if_type
typedef sc_signal_in_if<sc_dt::sc_biguint<W> > sc_core::sc_in< sc_dt::sc_biguint< W > >::if_type
Definition at line 935 of file scx_signal_unsigned.h.
in_if_type
typedef if_type sc_core::sc_in< sc_dt::sc_biguint< W > >::in_if_type
Definition at line 939 of file scx_signal_unsigned.h.
in_port_type
typedef base_type sc_core::sc_in< sc_dt::sc_biguint< W > >::in_port_type
Definition at line 940 of file scx_signal_unsigned.h.
inout_if_type
typedef sc_signal_inout_if<sc_dt::sc_biguint<W> > sc_core::sc_in< sc_dt::sc_biguint< W > >::inout_if_type
Definition at line 941 of file scx_signal_unsigned.h.
inout_port_type
typedef sc_inout<sc_dt::sc_biguint<W> > sc_core::sc_in< sc_dt::sc_biguint< W > >::inout_port_type
Definition at line 942 of file scx_signal_unsigned.h.
this_type
typedef sc_in<sc_dt::sc_biguint<W> > sc_core::sc_in< sc_dt::sc_biguint< W > >::this_type
Definition at line 937 of file scx_signal_unsigned.h.
Constructor & Destructor Documentation
sc_in() [1/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in () inline
Definition at line 987 of file scx_signal_unsigned.h.
sc_in() [2/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const char * name_) inline explicit
Definition at line 991 of file scx_signal_unsigned.h.
sc_in() [3/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const in_if_type & interface_) inline explicit
Definition at line 995 of file scx_signal_unsigned.h.
sc_in() [4/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const char * name_, const in_if_type & interface_) inline
Definition at line 999 of file scx_signal_unsigned.h.
sc_in() [5/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (in_port_type & parent_) inline explicit
Definition at line 1003 of file scx_signal_unsigned.h.
sc_in() [6/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const char * name_, in_port_type & parent_) inline
Definition at line 1007 of file scx_signal_unsigned.h.
sc_in() [7/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (inout_port_type & parent_) inline explicit
Definition at line 1011 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
sc_in() [8/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const char * name_, inout_port_type & parent_) inline
Definition at line 1015 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
sc_in() [9/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (this_type & parent_) inline
Definition at line 1019 of file scx_signal_unsigned.h.
sc_in() [10/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const char * name_, this_type & parent_) inline
Definition at line 1023 of file scx_signal_unsigned.h.
~sc_in()
virtual sc_core::sc_in< sc_dt::sc_biguint< W > >::~sc_in () inline virtual
Definition at line 1030 of file scx_signal_unsigned.h.
sc_in() [11/11]
sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in (const sc_in< sc_dt::sc_biguint< W > > &) private
Member Function Documentation
add_trace()
void sc_core::sc_in< sc_dt::sc_biguint< W > >::add_trace (sc_trace_file * tf_, const std::string & name_) const inline
Definition at line 1121 of file scx_signal_unsigned.h.
and_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::and_reduce () const inline
Definition at line 1087 of file scx_signal_unsigned.h.
bind() [1/3]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::bind (const in_if_type & interface_) inline
Definition at line 948 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
bind() [2/3]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::bind (in_port_type & parent_) inline
Definition at line 952 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
bind() [3/3]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::bind (inout_port_type & parent_) inline
Definition at line 956 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
bit()
sc_dt::sc_unsigned_bitref_r sc_core::sc_in< sc_dt::sc_biguint< W > >::bit (int i) const inline
Definition at line 1039 of file scx_signal_unsigned.h.
References ArmISA::i.
concat_get_ctrl()
virtual bool sc_core::sc_in< sc_dt::sc_biguint< W > >::concat_get_ctrl (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1138 of file scx_signal_unsigned.h.
concat_get_data()
virtual bool sc_core::sc_in< sc_dt::sc_biguint< W > >::concat_get_data (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1140 of file scx_signal_unsigned.h.
concat_get_uint64()
virtual sc_dt::uint64 sc_core::sc_in< sc_dt::sc_biguint< W > >::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1136 of file scx_signal_unsigned.h.
concat_length()
virtual int sc_core::sc_in< sc_dt::sc_biguint< W > >::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1134 of file scx_signal_unsigned.h.
default_event()
const sc_event& sc_core::sc_in< sc_dt::sc_biguint< W > >::default_event () const inline
Definition at line 1051 of file scx_signal_unsigned.h.
end_of_elaboration()
virtual void sc_core::sc_in< sc_dt::sc_biguint< W > >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Definition at line 1105 of file scx_signal_unsigned.h.
References ArmISA::i, sc_core::sc_trace_params::name, MipsISA::p, sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::read(), sc_core::sc_trace(), and sc_core::sc_trace_params::tf.
event()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::event () const inline
Definition at line 1071 of file scx_signal_unsigned.h.
kind()
virtual const char* sc_core::sc_in< sc_dt::sc_biguint< W > >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >.
Definition at line 1116 of file scx_signal_unsigned.h.
nand_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::nand_reduce () const inline
Definition at line 1089 of file scx_signal_unsigned.h.
nor_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::nor_reduce () const inline
Definition at line 1091 of file scx_signal_unsigned.h.
operator const sc_dt::sc_biguint< W > &()
sc_core::sc_in< sc_dt::sc_biguint< W > >::operator const sc_dt::sc_biguint< W > & () const inline
Definition at line 1066 of file scx_signal_unsigned.h.
operator()() [1/4]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::operator() (const in_if_type & interface_) inline
Definition at line 950 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
operator()() [2/4]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::operator() (in_port_type & parent_) inline
Definition at line 954 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
operator()() [3/4]
void sc_core::sc_in< sc_dt::sc_biguint< W > >::operator() (inout_port_type & parent_) inline
Definition at line 958 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
operator()() [4/4]
sc_dt::sc_unsigned_subref_r sc_core::sc_in< sc_dt::sc_biguint< W > >::operator() (int left, int right) const inline
Definition at line 1041 of file scx_signal_unsigned.h.
operator=()
sc_in<sc_dt::sc_biguint<W> >& sc_core::sc_in< sc_dt::sc_biguint< W > >::operator= (const sc_in< sc_dt::sc_biguint< W > > &) private
operator[]()
sc_dt::sc_unsigned_bitref_r sc_core::sc_in< sc_dt::sc_biguint< W > >::operator[] (int i) const inline
Definition at line 1037 of file scx_signal_unsigned.h.
References ArmISA::i.
or_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::or_reduce () const inline
Definition at line 1093 of file scx_signal_unsigned.h.
range()
sc_dt::sc_unsigned_subref_r sc_core::sc_in< sc_dt::sc_biguint< W > >::range (int left, int right) const inline
Definition at line 1043 of file scx_signal_unsigned.h.
read()
const sc_dt::sc_biguint<W>& sc_core::sc_in< sc_dt::sc_biguint< W > >::read () const inline
Definition at line 1063 of file scx_signal_unsigned.h.
remove_traces()
void sc_core::sc_in< sc_dt::sc_biguint< W > >::remove_traces () const inline protected
Definition at line 1144 of file scx_signal_unsigned.h.
References ArmISA::i.
value_changed()
sc_event_finder& sc_core::sc_in< sc_dt::sc_biguint< W > >::value_changed () const inline
Definition at line 1077 of file scx_signal_unsigned.h.
value_changed_event()
const sc_event& sc_core::sc_in< sc_dt::sc_biguint< W > >::value_changed_event () const inline
Definition at line 1057 of file scx_signal_unsigned.h.
vbind() [1/2]
virtual int sc_core::sc_in< sc_dt::sc_biguint< W > >::vbind (sc_interface & interface_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 963 of file scx_signal_unsigned.h.
References sc_core::sc_port_b< IF >::vbind().
vbind() [2/2]
virtual int sc_core::sc_in< sc_dt::sc_biguint< W > >::vbind (sc_port_base & parent_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 967 of file scx_signal_unsigned.h.
References sc_core::sc_port_base::bind().
xnor_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::xnor_reduce () const inline
Definition at line 1095 of file scx_signal_unsigned.h.
xor_reduce()
bool sc_core::sc_in< sc_dt::sc_biguint< W > >::xor_reduce () const inline
Definition at line 1097 of file scx_signal_unsigned.h.
Member Data Documentation
m_traces
sc_trace_params_vec* sc_core::sc_in< sc_dt::sc_biguint< W > >::m_traces mutable protected
Definition at line 1155 of file scx_signal_unsigned.h.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_unsigned.h