gem5: RiscvISA::Interrupts Class Reference
RiscvISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef RiscvInterruptsParams Params
Public Types inherited from BaseInterrupts
typedef BaseInterruptsParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
Interrupts (Params *p)
void setCPU (BaseCPU *_cpu)
std::bitset< NumInterruptTypes > globalMask (ThreadContext *tc) const
bool checkInterrupt (int num) const
bool checkInterrupts (ThreadContext *tc) const
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
uint64_t readIP () const
uint64_t readIE () const
void setIP (const uint64_t &val)
void setIE (const uint64_t &val)
void serialize (CheckpointOut &cp) const
Serialize an object.
void unserialize (CheckpointIn &cp)
Unserialize an object.
Public Member Functions inherited from BaseInterrupts
BaseInterrupts (Params *p)
const Params * params () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Attributes
BaseCPU * cpu
std::bitset< NumInterruptTypes > ip
std::bitset< NumInterruptTypes > ie
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from BaseInterrupts
BaseCPU * cpu
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 55 of file interrupts.hh.
Member Typedef Documentation
Params
typedef RiscvInterruptsParams RiscvISA::Interrupts::Params
Definition at line 63 of file interrupts.hh.
Constructor & Destructor Documentation
Interrupts()
RiscvISA::Interrupts::Interrupts (Params * p) inline
Definition at line 71 of file interrupts.hh.
Member Function Documentation
checkInterrupt()
bool RiscvISA::Interrupts::checkInterrupt (int num) const inline
Definition at line 89 of file interrupts.hh.
Referenced by getInterrupt().
checkInterrupts()
bool RiscvISA::Interrupts::checkInterrupts (ThreadContext * tc) const inline virtual
Implements BaseInterrupts.
Definition at line 90 of file interrupts.hh.
References globalMask().
Referenced by getInterrupt().
clear()
void RiscvISA::Interrupts::clear (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 116 of file interrupts.hh.
References DPRINTF.
clearAll()
void RiscvISA::Interrupts::clearAll () inline virtual
Reimplemented from BaseInterrupts.
Definition at line 123 of file interrupts.hh.
References DPRINTF.
getInterrupt()
Fault RiscvISA::Interrupts::getInterrupt (ThreadContext * tc) inline virtual
Implements BaseInterrupts.
Definition at line 96 of file interrupts.hh.
References RiscvISA::c, checkInterrupt(), checkInterrupts(), globalMask(), RiscvISA::mask, NoFault, and RiscvISA::NumInterruptTypes.
globalMask()
std::bitset<NumInterruptTypes> RiscvISA::Interrupts::globalMask (ThreadContext * tc) const inline
Definition at line 76 of file interrupts.hh.
References RiscvISA::mask, RiscvISA::MISCREG_STATUS, ThreadContext::readMiscReg(), and ArmISA::status.
Referenced by checkInterrupts(), and getInterrupt().
params()
const Params* RiscvISA::Interrupts::params () const inline
Definition at line 66 of file interrupts.hh.
References SimObject::_params.
post()
void RiscvISA::Interrupts::post (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 109 of file interrupts.hh.
References DPRINTF.
readIE()
uint64_t RiscvISA::Interrupts::readIE () const inline
Definition at line 130 of file interrupts.hh.
readIP()
uint64_t RiscvISA::Interrupts::readIP () const inline
Definition at line 129 of file interrupts.hh.
serialize()
void RiscvISA::Interrupts::serialize (CheckpointOut & cp) const inline virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 135 of file interrupts.hh.
References SERIALIZE_SCALAR.
setCPU()
void RiscvISA::Interrupts::setCPU (BaseCPU * _cpu) inline virtual
Implements BaseInterrupts.
Definition at line 73 of file interrupts.hh.
setIE()
void RiscvISA::Interrupts::setIE (const uint64_t & val) inline
Definition at line 132 of file interrupts.hh.
References X86ISA::val.
setIP()
void RiscvISA::Interrupts::setIP (const uint64_t & val) inline
Definition at line 131 of file interrupts.hh.
References X86ISA::val.
unserialize()
void RiscvISA::Interrupts::unserialize (CheckpointIn & cp) inline virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 144 of file interrupts.hh.
References UNSERIALIZE_SCALAR.
updateIntrInfo()
void RiscvISA::Interrupts::updateIntrInfo (ThreadContext * tc) inline virtual
Implements BaseInterrupts.
Definition at line 106 of file interrupts.hh.
Member Data Documentation
cpu
BaseCPU* RiscvISA::Interrupts::cpu private
Definition at line 58 of file interrupts.hh.
ie
std::bitset<NumInterruptTypes> RiscvISA::Interrupts::ie private
Definition at line 60 of file interrupts.hh.
ip
std::bitset<NumInterruptTypes> RiscvISA::Interrupts::ip private
Definition at line 59 of file interrupts.hh.
The documentation for this class was generated from the following file:
arch/riscv/interrupts.hh