gem5: NonCachingSimpleCPU Class Reference
NonCachingSimpleCPU Class Reference
The NonCachingSimpleCPU is an AtomicSimpleCPU using the 'atomic_noncaching' memory mode instead of just 'atomic'.
#include <noncaching.hh>
Public Member Functions
NonCachingSimpleCPU (NonCachingSimpleCPUParams *p)
void verifyMemoryMode () const override
Verify that the system is in a memory mode supported by the CPU.
Public Member Functions inherited from AtomicSimpleCPU
AtomicSimpleCPU (AtomicSimpleCPUParams *params)
virtual ~AtomicSimpleCPU ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void switchOut () override
Prepare for another CPU to take over execution.
void takeOverFrom (BaseCPU *oldCPU) override
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void activateContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now active.
void suspendContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now suspended.
bool genMemFragmentRequest (const RequestPtr &req, Addr frag_addr, int size, Request::Flags flags, const std::vector< bool > &byte_enable, int &frag_size, int &size_left) const
Helper function used to set up the request for a single fragment of a memory access.
Fault readMem (Addr addr, uint8_t *data, unsigned size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >()) override
Fault writeMem (uint8_t *data, unsigned size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >()) override
Fault amoMem (Addr addr, uint8_t *data, unsigned size, Request::Flags flags, AtomicOpFunctorPtr amo_op) override
void regProbePoints () override
Register probe points for this object.
void printAddr (Addr a)
Print state of address in memory system via PrintReq (for debugging).
Public Member Functions inherited from BaseSimpleCPU
BaseSimpleCPU (BaseSimpleCPUParams *params)
virtual ~BaseSimpleCPU ()
void wakeup (ThreadID tid) override
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Addr dbg_vtophys (Addr addr)
void checkForInterrupts ()
void setupFetchRequest (const RequestPtr &req)
void preExecute ()
void postExecute ()
void advancePC (const Fault &fault)
void haltContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now halted.
void regStats () override
Callback to set stat parameters.
void resetStats () override
Callback to reset stats.
void startup () override
startup() is the final initialization call before simulation.
virtual Fault initiateMemRead (Addr addr, unsigned size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
virtual Fault initiateMemAMO (Addr addr, unsigned size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
void countInst ()
Counter totalInsts () const override
Counter totalOps () const override
void serializeThread (CheckpointOut &cp, ThreadID tid) const override
Serialize a single thread.
void unserializeThread (CheckpointIn &cp, ThreadID tid) override
Unserialize one thread.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
virtual ThreadContext * getContext (int tn)
Given a thread num get tho thread context for it.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
Tick sendPacket (MasterPort &port, const PacketPtr &pkt) override
Protected Member Functions inherited from AtomicSimpleCPU
void tick ()
bool isCpuDrained () const
Check if a system is in a drained state.
bool tryCompleteDrain ()
Try to complete a drain request.
Port & getDataPort () override
Return a reference to the data port.
Port & getInstPort () override
Return a reference to the instruction port.
void threadSnoop (PacketPtr pkt, ThreadID sender)
Perform snoop for other cpu-local thread contexts.
Protected Member Functions inherited from BaseSimpleCPU
void checkPcEventQueue ()
void swapActiveThread ()
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BaseSimpleCPU
Trace::InstRecord * traceData
CheckerCPU * checker
std::vector< SimpleExecContext * > threadInfo
std::list< ThreadID > activeThreads
TheISA::MachInst inst
Current instruction.
StaticInstPtr curStaticInst
StaticInstPtr curMacroStaticInst
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from BaseSimpleCPU
enum Status {
Idle, Running, Faulting, ITBWaitResponse,
IcacheRetry, IcacheWaitResponse, IcacheWaitSwitch, DTBWaitResponse,
DcacheRetry, DcacheWaitResponse, DcacheWaitSwitch
}
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Protected Attributes inherited from AtomicSimpleCPU
EventFunctionWrapper tickEvent
const int width
bool locked
const bool simulate_data_stalls
const bool simulate_inst_stalls
AtomicCPUPort icachePort
AtomicCPUDPort dcachePort
RequestPtr ifetch_req
RequestPtr data_read_req
RequestPtr data_write_req
RequestPtr data_amo_req
bool dcache_access
Tick dcache_latency
ProbePointArg< std::pair< SimpleThread *, const StaticInstPtr > > * ppCommit
Probe Points.
Protected Attributes inherited from BaseSimpleCPU
ThreadID curThread
BPredUnit * branchPred
Status _status
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
The NonCachingSimpleCPU is an AtomicSimpleCPU using the 'atomic_noncaching' memory mode instead of just 'atomic'.
Definition at line 50 of file noncaching.hh.
Constructor & Destructor Documentation
NonCachingSimpleCPU()
NonCachingSimpleCPU::NonCachingSimpleCPU (NonCachingSimpleCPUParams * p)
Definition at line 42 of file noncaching.cc.
Referenced by sendPacket().
Member Function Documentation
sendPacket()
Tick NonCachingSimpleCPU::sendPacket (MasterPort & port, const PacketPtr & pkt) override protected virtual
Reimplemented from AtomicSimpleCPU.
Definition at line 57 of file noncaching.cc.
References PhysicalMemory::access(), fatal, FullSystem, Packet::getAddr(), System::getPhysMem(), System::isMemAddr(), NonCachingSimpleCPU(), BaseCPU::numThreads, MasterPort::sendAtomic(), and BaseCPU::system.
verifyMemoryMode()
void NonCachingSimpleCPU::verifyMemoryMode () const override virtual
Verify that the system is in a memory mode supported by the CPU.
Implementations are expected to query the system for the current memory mode and ensure that it is what the CPU model expects. If the check fails, the implementation should terminate the simulation using fatal().
Reimplemented from AtomicSimpleCPU.
Definition at line 48 of file noncaching.cc.
References System::bypassCaches(), fatal, System::isAtomicMode(), and BaseCPU::system.
The documentation for this class was generated from the following files:
cpu/simple/noncaching.hh
cpu/simple/noncaching.cc