gem5: SMMUv3 Class Reference
SMMUv3 Class Reference
#include <smmu_v3.hh>
Public Member Functions
SMMUv3 (SMMUv3Params *p)
virtual ~SMMUv3 ()
virtual void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void regStats () override
Callback to set stat parameters.
Tick slaveRecvAtomic (PacketPtr pkt, PortID id)
bool slaveRecvTimingReq (PacketPtr pkt, PortID id)
bool masterRecvTimingResp (PacketPtr pkt)
void masterRecvReqRetry ()
bool masterTableWalkRecvTimingResp (PacketPtr pkt)
void masterTableWalkRecvReqRetry ()
Tick readControl (PacketPtr pkt)
Tick writeControl (PacketPtr pkt)
DrainState drain () override
Notify an object that it needs to drain its state.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
virtual Port & getPort (const std::string &name, PortID id=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool inSecureBlock (uint32_t offs) const
void scheduleSlaveRetries ()
SMMUAction runProcess (SMMUProcess *proc, PacketPtr pkt)
SMMUAction runProcessAtomic (SMMUProcess *proc, PacketPtr pkt)
SMMUAction runProcessTiming (SMMUProcess *proc, PacketPtr pkt)
void processCommands ()
void processCommand (const SMMUCommand &cmd)
const PageTableOps * getPageTableOps (uint8_t trans_granule)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const System & system
const MasterID masterId
SMMUMasterPort masterPort
SMMUMasterTableWalkPort masterTableWalkPort
SMMUControlPort controlPort
ARMArchTLB tlb
ConfigCache configCache
IPACache ipaCache
WalkCache walkCache
const bool tlbEnable
const bool configCacheEnable
const bool ipaCacheEnable
const bool walkCacheEnable
bool tableWalkPortEnable
const bool walkCacheNonfinalEnable
const unsigned walkCacheS1Levels
const unsigned walkCacheS2Levels
const unsigned masterPortWidth
SMMUSemaphore tlbSem
SMMUSemaphore ifcSmmuSem
SMMUSemaphore smmuIfcSem
SMMUSemaphore configSem
SMMUSemaphore ipaSem
SMMUSemaphore walkSem
SMMUSemaphore masterPortSem
SMMUSemaphore transSem
SMMUSemaphore ptwSem
SMMUSemaphore cycleSem
const Cycles tlbLat
const Cycles ifcSmmuLat
const Cycles smmuIfcLat
const Cycles configLat
const Cycles ipaLat
const Cycles walkLat
Stats::Scalar steL1Fetches
Stats::Scalar steFetches
Stats::Scalar cdL1Fetches
Stats::Scalar cdFetches
Stats::Distribution translationTimeDist
Stats::Distribution ptwTimeDist
std::vector< SMMUv3SlaveInterface * > slaveInterfaces
SMMUCommandExecProcess commandExecutor
const AddrRange regsMap
SMMURegs regs
std::queue< SMMUAction > packetsToRetry
std::queue< SMMUAction > packetsTableWalkToRetry
EventWrapper< SMMUv3, &SMMUv3::processCommands > processCommandsEvent
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class SMMUProcess
class SMMUTranslationProcess
class SMMUCommandExecProcess
class SMMUv3SlaveInterface
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 83 of file smmu_v3.hh.
Constructor & Destructor Documentation
SMMUv3()
SMMUv3::SMMUv3 (SMMUv3Params * p)
Definition at line 56 of file smmu_v3.cc.
References SMMURegs::aidr, commandExecutor, configCacheEnable, configLat, configSem, cycleSem, fatal_if, SMMURegs::idr0, SMMURegs::idr1, SMMURegs::idr2, SMMURegs::idr3, SMMURegs::idr4, SMMURegs::idr5, ifcSmmuLat, ifcSmmuSem, SMMURegs::iidr, ipaCacheEnable, ipaLat, ipaSem, masterPortSem, masterPortWidth, SimObject::name(), ClockedObject::params(), processCommandsEvent, ptwSem, regs, regsMap, AddrRange::size(), slaveInterfaces, SMMU_REG_SIZE, smmuIfcLat, smmuIfcSem, tableWalkPortEnable, tlbEnable, tlbLat, tlbSem, transSem, walkCacheEnable, walkCacheNonfinalEnable, walkCacheS1Levels, walkCacheS2Levels, walkLat, walkSem, and warn.
Referenced by getPort().
~SMMUv3()
virtual SMMUv3::~SMMUv3 () inline virtual
Definition at line 171 of file smmu_v3.hh.
References drain(), getPort(), init(), InvalidPortID, masterRecvReqRetry(), masterRecvTimingResp(), masterTableWalkRecvReqRetry(), masterTableWalkRecvTimingResp(), SimObject::name(), readControl(), regStats(), serialize(), slaveRecvAtomic(), slaveRecvTimingReq(), unserialize(), and writeControl().
Member Function Documentation
drain()
DrainState SMMUv3::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 792 of file smmu_v3.cc.
References commandExecutor, Drained, Draining, and SMMUCommandExecProcess::isBusy().
Referenced by ~SMMUv3().
getPageTableOps()
const PageTableOps * SMMUv3::getPageTableOps (uint8_t trans_granule) protected
Definition at line 566 of file smmu_v3.cc.
References panic, TRANS_GRANULE_16K, TRANS_GRANULE_4K, and TRANS_GRANULE_64K.
Referenced by SMMUTranslationProcess::translateStage1And2(), SMMUTranslationProcess::translateStage2(), and SMMUTranslationProcess::walkCacheLookup().
getPort()
Port & SMMUv3::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 818 of file smmu_v3.cc.
References controlPort, SimObject::getPort(), masterPort, masterTableWalkPort, and SMMUv3().
Referenced by ~SMMUv3().
init()
void SMMUv3::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 719 of file smmu_v3.cc.
References controlPort, fatal, Port::isConnected(), masterPort, masterTableWalkPort, SlavePort::sendRangeChange(), slaveInterfaces, and tableWalkPortEnable.
Referenced by ~SMMUv3().
inSecureBlock()
bool SMMUv3::inSecureBlock (uint32_t offs) const protected
Definition at line 710 of file smmu_v3.cc.
References SMMU_SECURE_SZ.
Referenced by readControl(), and writeControl().
masterRecvReqRetry()
void SMMUv3::masterRecvReqRetry ()
Definition at line 146 of file smmu_v3.cc.
References ArmISA::a, ACTION_SEND_REQ, ACTION_SEND_REQ_FINAL, DPRINTF, Packet::getAddr(), Packet::getSize(), masterPort, packetsToRetry, SMMUAction::pkt, scheduleSlaveRetries(), MasterPort::sendTimingReq(), and SMMUAction::type.
Referenced by SMMUMasterPort::recvReqRetry(), and ~SMMUv3().
masterRecvTimingResp()
bool SMMUv3::masterRecvTimingResp (PacketPtr pkt)
Definition at line 129 of file smmu_v3.cc.
References DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::headerDelay, Packet::payloadDelay, Packet::popSenderState(), runProcessTiming(), and safe_cast().
Referenced by SMMUMasterPort::recvTimingResp(), and ~SMMUv3().
masterTableWalkRecvReqRetry()
void SMMUv3::masterTableWalkRecvReqRetry ()
Definition at line 192 of file smmu_v3.cc.
References ArmISA::a, ACTION_SEND_REQ, DPRINTF, Packet::getAddr(), Packet::getSize(), masterTableWalkPort, packetsTableWalkToRetry, SMMUAction::pkt, MasterPort::sendTimingReq(), tableWalkPortEnable, and SMMUAction::type.
Referenced by SMMUMasterTableWalkPort::recvReqRetry(), and ~SMMUv3().
masterTableWalkRecvTimingResp()
bool SMMUv3::masterTableWalkRecvTimingResp (PacketPtr pkt)
Definition at line 175 of file smmu_v3.cc.
References DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::headerDelay, Packet::payloadDelay, Packet::popSenderState(), runProcessTiming(), and safe_cast().
Referenced by SMMUMasterTableWalkPort::recvTimingResp(), and ~SMMUv3().
processCommand()
void SMMUv3::processCommand (const SMMUCommand & cmd) protected
Definition at line 384 of file smmu_v3.cc.
References addr, SMMUCommand::addr(), SMMUCommand::asid, CMD_CFGI_CD, CMD_CFGI_CD_ALL, CMD_CFGI_STE, CMD_CFGI_STE_RANGE, CMD_PRF_ADDR, CMD_PRF_CONFIG, CMD_RESUME, CMD_TLBI_NH_ALL, CMD_TLBI_NH_ASID, CMD_TLBI_NH_VA, CMD_TLBI_NH_VAA, CMD_TLBI_NSNH_ALL, CMD_TLBI_S12_VMALL, CMD_TLBI_S2_IPA, configCache, DPRINTF, ARMArchTLB::invalidateAll(), IPACache::invalidateAll(), ConfigCache::invalidateAll(), WalkCache::invalidateAll(), ARMArchTLB::invalidateASID(), WalkCache::invalidateASID(), IPACache::invalidateIPA(), ConfigCache::invalidateSID(), ConfigCache::invalidateSSID(), ARMArchTLB::invalidateVA(), WalkCache::invalidateVA(), ARMArchTLB::invalidateVAA(), WalkCache::invalidateVAA(), ARMArchTLB::invalidateVMID(), IPACache::invalidateVMID(), WalkCache::invalidateVMID(), ipaCache, panic, SMMUCommand::range, SMMUCommand::sid, slaveInterfaces, SMMUCommand::ssid, tlb, SMMUCommand::type, SMMUCommand::vmid, walkCache, and warn.
Referenced by SMMUCommandExecProcess::main().
processCommands()
void SMMUv3::processCommands () protected
Definition at line 368 of file smmu_v3.cc.
References ArmISA::a, commandExecutor, DPRINTF, System::isAtomicMode(), SMMUCommandExecProcess::isBusy(), System::isTimingMode(), panic, runProcessAtomic(), runProcessTiming(), and system.
readControl()
Tick SMMUv3::readControl (PacketPtr pkt)
Definition at line 582 of file smmu_v3.cc.
References SMMURegs::data, DPRINTF, Packet::getAddr(), Packet::getSize(), inSecureBlock(), Packet::makeAtomicResponse(), ArmISA::offset, panic, regs, regsMap, Packet::setLE(), SMMU_REG_SIZE, AddrRange::start(), and warn.
Referenced by SMMUControlPort::recvAtomic(), and ~SMMUv3().
regStats()
void SMMUv3::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 740 of file smmu_v3.cc.
References cdFetches, cdL1Fetches, configCache, csprintf(), Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), ArmISA::i, Stats::Distribution::init(), ipaCache, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::pdf, ptwTimeDist, SMMUv3BaseCache::regStats(), Stats::Group::regStats(), WalkCache::regStats(), slaveInterfaces, steFetches, steL1Fetches, tlb, translationTimeDist, and walkCache.
Referenced by ~SMMUv3().
runProcess()
SMMUAction SMMUv3::runProcess (SMMUProcess * proc, PacketPtr pkt) protected
Definition at line 221 of file smmu_v3.cc.
References System::isAtomicMode(), System::isTimingMode(), panic, runProcessAtomic(), runProcessTiming(), and system.
Referenced by SMMUProcess::wakeup().
runProcessAtomic()
SMMUAction SMMUv3::runProcessAtomic (SMMUProcess * proc, PacketPtr pkt) protected
Definition at line 233 of file smmu_v3.cc.
References ACTION_DELAY, ACTION_SEND_REQ, ACTION_SEND_REQ_FINAL, ACTION_SEND_RESP, ACTION_SEND_RESP_ATS, ACTION_SLEEP, ACTION_TERMINATE, SMMUAction::delay, M5_FALLTHROUGH, masterPort, masterTableWalkPort, panic, SMMUAction::pkt, SMMUProcess::run(), MasterPort::sendAtomic(), tableWalkPortEnable, and SMMUAction::type.
Referenced by SMMUv3SlaveInterface::atsSlaveRecvAtomic(), processCommands(), SMMUv3SlaveInterface::recvAtomic(), and runProcess().
runProcessTiming()
SMMUAction SMMUv3::runProcessTiming (SMMUProcess * proc, PacketPtr pkt) protected
Definition at line 282 of file smmu_v3.cc.
References ACTION_DELAY, ACTION_SEND_REQ, ACTION_SEND_REQ_FINAL, ACTION_SEND_RESP, ACTION_SEND_RESP_ATS, ACTION_SLEEP, ACTION_TERMINATE, DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::headerDelay, SMMUAction::ifc, M5_FALLTHROUGH, masterPort, masterTableWalkPort, packetsTableWalkToRetry, packetsToRetry, panic, Packet::payloadDelay, SMMUAction::pkt, Packet::pushSenderState(), SMMUProcess::run(), SMMUv3SlaveInterface::schedAtsTimingResp(), SMMUv3SlaveInterface::schedTimingResp(), scheduleSlaveRetries(), MasterPort::sendTimingReq(), tableWalkPortEnable, and SMMUAction::type.
Referenced by SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), masterRecvTimingResp(), masterTableWalkRecvTimingResp(), processCommands(), SMMUv3SlaveInterface::recvTimingReq(), SMMUTranslationProcess::resumeTransaction(), and runProcess().
scheduleSlaveRetries()
void SMMUv3::scheduleSlaveRetries () protected
Definition at line 213 of file smmu_v3.cc.
References slaveInterfaces.
Referenced by SMMUTranslationProcess::completeTransaction(), masterRecvReqRetry(), and runProcessTiming().
serialize()
void SMMUv3::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 802 of file smmu_v3.cc.
References SMMURegs::data, DPRINTF, regs, and SERIALIZE_ARRAY.
Referenced by ~SMMUv3().
slaveRecvAtomic()
Tick SMMUv3::slaveRecvAtomic (PacketPtr pkt, PortID id)
Referenced by ~SMMUv3().
slaveRecvTimingReq()
bool SMMUv3::slaveRecvTimingReq (PacketPtr pkt, PortID id)
Referenced by ~SMMUv3().
unserialize()
void SMMUv3::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 810 of file smmu_v3.cc.
References SMMURegs::data, DPRINTF, regs, and UNSERIALIZE_ARRAY.
Referenced by ~SMMUv3().
writeControl()
Tick SMMUv3::writeControl (PacketPtr pkt)
Definition at line 615 of file smmu_v3.cc.
References SMMURegs::cmdq_cons, SMMURegs::cmdq_prod, SMMURegs::cr0, CR0_CMDQEN_MASK, SMMURegs::cr0ack, PowerISA::cr1, SMMURegs::data, DPRINTF, SMMURegs::eventq_cons, SMMURegs::eventq_prod, Packet::getAddr(), Packet::getLE(), Packet::getSize(), inSecureBlock(), Packet::makeAtomicResponse(), Clocked::nextCycle(), ArmISA::offset, SMMURegs::priq_cons, SMMURegs::priq_prod, processCommandsEvent, regs, regsMap, EventManager::schedule(), SMMU_REG_SIZE, AddrRange::start(), and warn.
Referenced by SMMUControlPort::recvAtomic(), and ~SMMUv3().
Friends And Related Function Documentation
SMMUCommandExecProcess
friend class SMMUCommandExecProcess friend
Definition at line 89 of file smmu_v3.hh.
SMMUProcess
friend class SMMUProcess friend
Definition at line 87 of file smmu_v3.hh.
SMMUTranslationProcess
friend class SMMUTranslationProcess friend
Definition at line 88 of file smmu_v3.hh.
SMMUv3SlaveInterface
friend class SMMUv3SlaveInterface friend
Definition at line 90 of file smmu_v3.hh.
Member Data Documentation
cdFetches
Stats::Scalar SMMUv3::cdFetches protected
Definition at line 139 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::doReadCD(), and regStats().
cdL1Fetches
Stats::Scalar SMMUv3::cdL1Fetches protected
Definition at line 138 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::doReadCD(), and regStats().
commandExecutor
SMMUCommandExecProcess SMMUv3::commandExecutor protected
Definition at line 145 of file smmu_v3.hh.
Referenced by drain(), processCommands(), and SMMUv3().
configCache
ConfigCache SMMUv3::configCache protected
Definition at line 100 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), processCommand(), and regStats().
configCacheEnable
const bool SMMUv3::configCacheEnable protected
Definition at line 105 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), and SMMUv3().
configLat
const Cycles SMMUv3::configLat protected
Definition at line 131 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::configCacheLookup(), and SMMUv3().
configSem
SMMUSemaphore SMMUv3::configSem protected
Definition at line 118 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), and SMMUv3().
controlPort
SMMUControlPort SMMUv3::controlPort protected
Definition at line 97 of file smmu_v3.hh.
Referenced by getPort(), and init().
cycleSem
SMMUSemaphore SMMUv3::cycleSem protected
Definition at line 125 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
ifcSmmuLat
const Cycles SMMUv3::ifcSmmuLat protected
Definition at line 129 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
ifcSmmuSem
SMMUSemaphore SMMUv3::ifcSmmuSem protected
Definition at line 116 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
ipaCache
IPACache SMMUv3::ipaCache protected
Definition at line 101 of file smmu_v3.hh.
Referenced by processCommand(), regStats(), and SMMUTranslationProcess::translateStage2().
ipaCacheEnable
const bool SMMUv3::ipaCacheEnable protected
Definition at line 106 of file smmu_v3.hh.
Referenced by SMMUv3(), and SMMUTranslationProcess::translateStage2().
ipaLat
const Cycles SMMUv3::ipaLat protected
Definition at line 132 of file smmu_v3.hh.
Referenced by SMMUv3(), and SMMUTranslationProcess::translateStage2().
ipaSem
SMMUSemaphore SMMUv3::ipaSem protected
Definition at line 119 of file smmu_v3.hh.
Referenced by SMMUv3(), and SMMUTranslationProcess::translateStage2().
masterId
const MasterID SMMUv3::masterId protected
Definition at line 93 of file smmu_v3.hh.
Referenced by SMMUProcess::doRead(), and SMMUProcess::doWrite().
masterPort
SMMUMasterPort SMMUv3::masterPort protected
Definition at line 95 of file smmu_v3.hh.
Referenced by getPort(), init(), masterRecvReqRetry(), runProcessAtomic(), and runProcessTiming().
masterPortSem
SMMUSemaphore SMMUv3::masterPortSem protected
Definition at line 121 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUProcess::doRead(), SMMUProcess::doWrite(), and SMMUv3().
masterPortWidth
const unsigned SMMUv3::masterPortWidth protected
Definition at line 113 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUProcess::doWrite(), and SMMUv3().
masterTableWalkPort
SMMUMasterTableWalkPort SMMUv3::masterTableWalkPort protected
Definition at line 96 of file smmu_v3.hh.
Referenced by getPort(), init(), masterTableWalkRecvReqRetry(), runProcessAtomic(), and runProcessTiming().
packetsTableWalkToRetry
std::queue<SMMUAction> SMMUv3::packetsTableWalkToRetry protected
Definition at line 153 of file smmu_v3.hh.
Referenced by masterTableWalkRecvReqRetry(), and runProcessTiming().
packetsToRetry
std::queue<SMMUAction> SMMUv3::packetsToRetry protected
Definition at line 152 of file smmu_v3.hh.
Referenced by masterRecvReqRetry(), and runProcessTiming().
processCommandsEvent
EventWrapper<SMMUv3, &SMMUv3::processCommands> SMMUv3::processCommandsEvent protected
Definition at line 163 of file smmu_v3.hh.
Referenced by SMMUv3(), and writeControl().
ptwSem
SMMUSemaphore SMMUv3::ptwSem protected
Definition at line 124 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
ptwTimeDist
Stats::Distribution SMMUv3::ptwTimeDist protected
Definition at line 141 of file smmu_v3.hh.
Referenced by regStats(), and SMMUTranslationProcess::smmuTranslation().
regs
SMMURegs SMMUv3::regs protected
Definition at line 148 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::doReadSTE(), SMMUCommandExecProcess::main(), SMMUTranslationProcess::main(), readControl(), SMMUTranslationProcess::sendEvent(), serialize(), SMMUv3(), unserialize(), and writeControl().
regsMap
const AddrRange SMMUv3::regsMap protected
Definition at line 147 of file smmu_v3.hh.
Referenced by readControl(), SMMUv3(), and writeControl().
slaveInterfaces
std::vector<SMMUv3SlaveInterface *> SMMUv3::slaveInterfaces protected
Definition at line 143 of file smmu_v3.hh.
Referenced by init(), processCommand(), regStats(), scheduleSlaveRetries(), and SMMUv3().
smmuIfcLat
const Cycles SMMUv3::smmuIfcLat protected
Definition at line 130 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
smmuIfcSem
SMMUSemaphore SMMUv3::smmuIfcSem protected
Definition at line 117 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
steFetches
Stats::Scalar SMMUv3::steFetches protected
Definition at line 137 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::doReadSTE(), and regStats().
steL1Fetches
Stats::Scalar SMMUv3::steL1Fetches protected
Definition at line 136 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::doReadSTE(), and regStats().
system
const System& SMMUv3::system protected
Definition at line 92 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUProcess::doDelay(), SMMUTranslationProcess::issuePrefetch(), processCommands(), SMMUTranslationProcess::resumeTransaction(), and runProcess().
tableWalkPortEnable
bool SMMUv3::tableWalkPortEnable protected
Definition at line 108 of file smmu_v3.hh.
Referenced by init(), masterTableWalkRecvReqRetry(), runProcessAtomic(), runProcessTiming(), and SMMUv3().
tlb
ARMArchTLB SMMUv3::tlb protected
Definition at line 99 of file smmu_v3.hh.
Referenced by processCommand(), regStats(), SMMUTranslationProcess::smmuTLBLookup(), and SMMUTranslationProcess::smmuTLBUpdate().
tlbEnable
const bool SMMUv3::tlbEnable protected
Definition at line 104 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), and SMMUv3().
tlbLat
const Cycles SMMUv3::tlbLat protected
Definition at line 128 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTLBLookup(), and SMMUv3().
tlbSem
SMMUSemaphore SMMUv3::tlbSem protected
Definition at line 115 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), and SMMUv3().
translationTimeDist
Stats::Distribution SMMUv3::translationTimeDist protected
Definition at line 140 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), and regStats().
transSem
SMMUSemaphore SMMUv3::transSem protected
Definition at line 123 of file smmu_v3.hh.
Referenced by SMMUTranslationProcess::smmuTranslation(), and SMMUv3().
walkCache
WalkCache SMMUv3::walkCache protected
Definition at line 102 of file smmu_v3.hh.
Referenced by processCommand(), regStats(), SMMUTranslationProcess::walkCacheLookup(), and SMMUTranslationProcess::walkCacheUpdate().
walkCacheEnable
const bool SMMUv3::walkCacheEnable protected
Definition at line 107 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::walkCacheLookup(), and SMMUTranslationProcess::walkCacheUpdate().
walkCacheNonfinalEnable
const bool SMMUv3::walkCacheNonfinalEnable protected
Definition at line 110 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::translateStage2(), and SMMUTranslationProcess::walkStage2().
walkCacheS1Levels
const unsigned SMMUv3::walkCacheS1Levels protected
Definition at line 111 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::walkCacheLookup(), and SMMUTranslationProcess::walkCacheUpdate().
walkCacheS2Levels
const unsigned SMMUv3::walkCacheS2Levels protected
Definition at line 112 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::walkCacheLookup(), and SMMUTranslationProcess::walkCacheUpdate().
walkLat
const Cycles SMMUv3::walkLat protected
Definition at line 133 of file smmu_v3.hh.
Referenced by SMMUv3(), and SMMUTranslationProcess::walkCacheLookup().
walkSem
SMMUSemaphore SMMUv3::walkSem protected
Definition at line 120 of file smmu_v3.hh.
Referenced by SMMUv3(), SMMUTranslationProcess::walkCacheLookup(), and SMMUTranslationProcess::walkCacheUpdate().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3.hh
dev/arm/smmu_v3.cc