gem5: LocalBP Class Reference
LocalBP Class Reference
Implements a local predictor that uses the PC to index into a table of counters.
#include <2bit_local.hh>
Public Member Functions
LocalBP (const LocalBPParams *params)
Default branch predictor constructor.
virtual void uncondBranch (ThreadID tid, Addr pc, void *&bp_history)
bool lookup (ThreadID tid, Addr branch_addr, void *&bp_history)
Looks up the given address in the branch predictor and returns a true/false value as to whether it is taken.
void btbUpdate (ThreadID tid, Addr branch_addr, void *&bp_history)
Updates the branch predictor to Not Taken if a BTB entry is invalid or not found.
void update (ThreadID tid, Addr branch_addr, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst, Addr corrTarget)
Updates the branch predictor with the actual result of a branch.
void squash (ThreadID tid, void *bp_history)
Public Member Functions inherited from BPredUnit
BPredUnit (const Params *p)
void regStats () override
Registers statistics.
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
bool getPrediction (uint8_t &count)
Returns the taken/not taken prediction given the value of the counter.
unsigned getLocalIndex (Addr &PC)
Calculates the local index based on the PC.
Private Attributes
const unsigned localPredictorSize
Size of the local predictor.
const unsigned localCtrBits
Number of bits of the local predictor's counters.
const unsigned localPredictorSets
Number of sets.
std::vector< SatCounter > localCtrs
Array of counters that make up the local predictor.
const unsigned indexMask
Mask to get index bits.
Additional Inherited Members
Public Types inherited from BPredUnit
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from BPredUnit
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from BPredUnit
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Implements a local predictor that uses the PC to index into a table of counters.
Note that any time a pointer to the bp_history is given, it should be NULL using this predictor because it does not have any branch predictor state that needs to be recorded or updated; the update can be determined solely by the branch being taken or not taken.
Definition at line 61 of file 2bit_local.hh.
Constructor & Destructor Documentation
LocalBP()
LocalBP::LocalBP (const LocalBPParams * params)
Default branch predictor constructor.
Definition at line 38 of file 2bit_local.cc.
References DPRINTF, fatal, indexMask, BPredUnit::instShiftAmt, isPowerOf2(), localCtrBits, localPredictorSets, and localPredictorSize.
Referenced by uncondBranch().
Member Function Documentation
btbUpdate()
void LocalBP::btbUpdate (ThreadID tid, Addr branch_addr, void *& bp_history) virtual
Updates the branch predictor to Not Taken if a BTB entry is invalid or not found.
Parameters
branch_addr The address of the branch to look up.
bp_history Pointer to any bp history state.
Returns
Whether or not the branch is taken.
Implements BPredUnit.
Definition at line 66 of file 2bit_local.cc.
getLocalIndex()
unsigned LocalBP::getLocalIndex (Addr & PC) inline private
Calculates the local index based on the PC.
Definition at line 129 of file 2bit_local.cc.
References indexMask, and BPredUnit::instShiftAmt.
Referenced by lookup(), squash(), and update().
getPrediction()
bool LocalBP::getPrediction (uint8_t & count) inline private
Returns the taken/not taken prediction given the value of the counter.
Parameters
count The value of the counter.
Returns
The prediction based on the counter value.
Definition at line 121 of file 2bit_local.cc.
References localCtrBits.
Referenced by lookup(), and squash().
lookup()
bool LocalBP::lookup (ThreadID tid, Addr branch_addr, void *& bp_history) virtual
Looks up the given address in the branch predictor and returns a true/false value as to whether it is taken.
Parameters
branch_addr The address of the branch to look up.
bp_history Pointer to any bp history state.
Returns
Whether or not the branch is taken.
Implements BPredUnit.
Definition at line 74 of file 2bit_local.cc.
References DPRINTF, getLocalIndex(), getPrediction(), and localCtrs.
squash()
void LocalBP::squash (ThreadID tid, void * bp_history) inline virtual
Parameters
bp_history Pointer to the history object. The predictor will need to update any state and delete the object.
Implements BPredUnit.
Definition at line 97 of file 2bit_local.hh.
References X86ISA::count, getLocalIndex(), and getPrediction().
uncondBranch()
void LocalBP::uncondBranch (ThreadID tid, Addr pc, void *& bp_history) virtual
Implements BPredUnit.
Definition at line 135 of file 2bit_local.cc.
References LocalBP().
update()
void LocalBP::update (ThreadID tid, Addr branch_addr, bool taken, void * bp_history, bool squashed, const StaticInstPtr & inst, Addr corrTarget) virtual
Updates the branch predictor with the actual result of a branch.
Parameters
branch_addr The address of the branch to update.
taken Whether or not the branch was taken.
Implements BPredUnit.
Definition at line 93 of file 2bit_local.cc.
References DPRINTF, getLocalIndex(), and localCtrs.
Member Data Documentation
indexMask
const unsigned LocalBP::indexMask private
Mask to get index bits.
Definition at line 125 of file 2bit_local.hh.
Referenced by getLocalIndex(), and LocalBP().
localCtrBits
const unsigned LocalBP::localCtrBits private
Number of bits of the local predictor's counters.
Definition at line 116 of file 2bit_local.hh.
Referenced by getPrediction(), and LocalBP().
localCtrs
std::vector<SatCounter> LocalBP::localCtrs private
Array of counters that make up the local predictor.
Definition at line 122 of file 2bit_local.hh.
Referenced by lookup(), and update().
localPredictorSets
const unsigned LocalBP::localPredictorSets private
Number of sets.
Definition at line 119 of file 2bit_local.hh.
Referenced by LocalBP().
localPredictorSize
const unsigned LocalBP::localPredictorSize private
Size of the local predictor.
Definition at line 113 of file 2bit_local.hh.
Referenced by LocalBP().
The documentation for this class was generated from the following files:
cpu/pred/2bit_local.hh
cpu/pred/2bit_local.cc