gem5: PCEventScope Class Reference
PCEventScope Class Reference abstract
#include <pc_event.hh>
Public Member Functions
virtual bool remove (PCEvent *event)=0
virtual bool schedule (PCEvent *event)=0
Detailed Description
Definition at line 67 of file pc_event.hh.
Member Function Documentation
remove()
virtual bool PCEventScope::remove (PCEvent * event) pure virtual
Implemented in SimpleThread, System, PCEventQueue, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by PCEvent::remove().
schedule()
virtual bool PCEventScope::schedule (PCEvent * event) pure virtual
Implemented in SimpleThread, System, PCEventQueue, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by PCEvent::PCEvent(), System::registerThreadContext(), and System::replaceThreadContext().
The documentation for this class was generated from the following file:
cpu/pc_event.hh