gem5: OutVcState Class Reference
OutVcState Class Reference
#include <OutVcState.hh>
Public Member Functions
OutVcState (int id, GarnetNetwork *network_ptr)
int get_credit_count ()
bool has_credit ()
void increment_credit ()
void decrement_credit ()
bool isInState (VC_state_type state, Cycles request_time)
void setState (VC_state_type state, Cycles time)
Private Attributes
int m_id
Cycles m_time
VC_state_type m_vc_state
int m_credit_count
int m_max_credit_count
Detailed Description
Definition at line 40 of file OutVcState.hh.
Constructor & Destructor Documentation
OutVcState()
OutVcState::OutVcState (int id, GarnetNetwork * network_ptr)
Definition at line 38 of file OutVcState.cc.
References DATA_VNET_, GarnetNetwork::get_vnet_type(), GarnetNetwork::getBuffersPerCtrlVC(), GarnetNetwork::getBuffersPerDataVC(), ArmISA::id, IDLE_, m_credit_count, m_id, m_max_credit_count, and m_vc_state.
Member Function Documentation
decrement_credit()
void OutVcState::decrement_credit ()
Definition at line 61 of file OutVcState.cc.
References m_credit_count.
Referenced by has_credit().
get_credit_count()
int OutVcState::get_credit_count () inline
Definition at line 45 of file OutVcState.hh.
References m_credit_count.
has_credit()
bool OutVcState::has_credit () inline
Definition at line 46 of file OutVcState.hh.
References decrement_credit(), increment_credit(), and m_credit_count.
increment_credit()
void OutVcState::increment_credit ()
Definition at line 54 of file OutVcState.cc.
References m_credit_count, and m_max_credit_count.
Referenced by has_credit().
isInState()
bool OutVcState::isInState (VC_state_type state, Cycles request_time) inline
Definition at line 51 of file OutVcState.hh.
References m_time, and m_vc_state.
setState()
void OutVcState::setState (VC_state_type state, Cycles time) inline
Definition at line 56 of file OutVcState.hh.
References m_time, and m_vc_state.
Member Data Documentation
m_credit_count
int OutVcState::m_credit_count private
Definition at line 66 of file OutVcState.hh.
Referenced by decrement_credit(), get_credit_count(), has_credit(), increment_credit(), and OutVcState().
m_id
int OutVcState::m_id private
Definition at line 63 of file OutVcState.hh.
Referenced by OutVcState().
m_max_credit_count
int OutVcState::m_max_credit_count private
Definition at line 67 of file OutVcState.hh.
Referenced by increment_credit(), and OutVcState().
m_time
Cycles OutVcState::m_time private
Definition at line 64 of file OutVcState.hh.
Referenced by isInState(), and setState().
m_vc_state
VC_state_type OutVcState::m_vc_state private
Definition at line 65 of file OutVcState.hh.
Referenced by isInState(), OutVcState(), and setState().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/OutVcState.hh
mem/ruby/network/garnet2.0/OutVcState.cc