gem5: X86ISA::I8042 Class Reference
X86ISA::I8042 Class Reference
#include <i8042.hh>
Public Types
typedef I8042Params Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
I8042 (Params *p)
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum Command {
GetCommandByte = 0x20, ReadControllerRamBase = 0x20, WriteCommandByte = 0x60, WriteControllerRamBase = 0x60,
CheckForPassword = 0xA4, LoadPassword = 0xA5, CheckPassword = 0xA6, DisableMouse = 0xA7,
EnableMouse = 0xA8, TestMouse = 0xA9, SelfTest = 0xAA, InterfaceTest = 0xAB,
DiagnosticDump = 0xAC, DisableKeyboard = 0xAD, EnableKeyboard = 0xAE, ReadInputPort = 0xC0,
ContinuousPollLow = 0xC1, ContinuousPollHigh = 0xC2, ReadOutputPort = 0xD0, WriteOutputPort = 0xD1,
WriteKeyboardOutputBuff = 0xD2, WriteMouseOutputBuff = 0xD3, WriteToMouse = 0xD4, DisableA20 = 0xDD,
EnableA20 = 0xDF, ReadTestInputs = 0xE0, PulseOutputBitBase = 0xF0, SystemReset = 0xFE
}
Protected Member Functions
BitUnion8 (StatusReg) Bitfield< 7 > parityError
EndBitUnion (StatusReg) BitUnion8(CommandByte) Bitfield< 6 > convertScanCodes
EndBitUnion (CommandByte) Tick latency
void writeData (uint8_t newData, bool mouse=false)
uint8_t readDataOut ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
Bitfield< 6 > timeout
Bitfield< 5 > mouseOutputFull
Bitfield< 4 > keyboardUnlocked
Bitfield< 3 > commandLast
Bitfield< 2 > passedSelfTest
Bitfield< 1 > inputFull
Bitfield< 0 > outputFull
Bitfield< 5 > disableMouse
Bitfield< 4 > disableKeyboard
Bitfield< 1 > mouseFullInt
Bitfield< 0 > keyboardFullInt
Addr dataPort
Addr commandPort
StatusReg statusReg
CommandByte commandByte
uint8_t dataReg
uint16_t lastCommand
std::vector< IntSourcePin< I8042 > * > mouseIntPin
std::vector< IntSourcePin< I8042 > * > keyboardIntPin
PS2Device * mouse
PS2Device * keyboard
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const uint16_t NoCommand = (uint16_t)(-1)
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 44 of file i8042.hh.
Member Typedef Documentation
Params
typedef I8042Params X86ISA::I8042::Params
Definition at line 121 of file i8042.hh.
Member Enumeration Documentation
Command
enum X86ISA::I8042::Command protected
Enumerator
GetCommandByte
ReadControllerRamBase
WriteCommandByte
WriteControllerRamBase
CheckForPassword
LoadPassword
CheckPassword
DisableMouse
EnableMouse
TestMouse
SelfTest
InterfaceTest
DiagnosticDump
DisableKeyboard
EnableKeyboard
ReadInputPort
ContinuousPollLow
ContinuousPollHigh
ReadOutputPort
WriteOutputPort
WriteKeyboardOutputBuff
WriteMouseOutputBuff
WriteToMouse
DisableA20
EnableA20
ReadTestInputs
PulseOutputBitBase
SystemReset
Definition at line 47 of file i8042.hh.
Constructor & Destructor Documentation
I8042()
X86ISA::I8042::I8042 (Params * p)
Definition at line 48 of file i8042.cc.
References commandByte, csprintf(), fatal_if, ArmISA::i, keyboard, keyboardIntPin, mouse, mouseIntPin, SimObject::name(), and statusReg.
Referenced by params().
Member Function Documentation
BitUnion8()
X86ISA::I8042::BitUnion8 (StatusReg) protected
EndBitUnion() [1/2]
X86ISA::I8042::EndBitUnion (StatusReg) protected
EndBitUnion() [2/2]
X86ISA::I8042::EndBitUnion (CommandByte) protected
getAddrRanges()
AddrRangeList X86ISA::I8042::getAddrRanges () const override virtual
Determine the address ranges that this device responds to.
Returns
a list of non-overlapping address ranges
Reimplemented from BasicPioDevice.
Definition at line 78 of file i8042.cc.
References commandPort, dataPort, and RangeSize().
Referenced by getPort().
getPort()
Port& X86ISA::I8042::getPort (const std::string & if_name, PortID idx = InvalidPortID) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from PioDevice.
Definition at line 132 of file i8042.hh.
References getAddrRanges(), PioDevice::getPort(), read(), serialize(), unserialize(), and write().
params()
const Params* X86ISA::I8042::params () const inline
Definition at line 124 of file i8042.hh.
References SimObject::_params, I8042(), and X86ISA::p.
read()
Tick X86ISA::I8042::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 126 of file i8042.cc.
References X86ISA::addr, commandPort, data, dataPort, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, readDataOut(), Packet::setLE(), and statusReg.
Referenced by getPort().
readDataOut()
uint8_t X86ISA::I8042::readDataOut () protected
Definition at line 112 of file i8042.cc.
References data, dataReg, PS2Device::hostDataAvailable(), PS2Device::hostRead(), keyboard, mouse, statusReg, and writeData().
Referenced by read().
serialize()
void X86ISA::I8042::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 289 of file i8042.cc.
References commandByte, commandPort, dataPort, dataReg, lastCommand, SERIALIZE_SCALAR, and statusReg.
Referenced by getPort().
unserialize()
void X86ISA::I8042::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 300 of file i8042.cc.
References commandByte, commandPort, dataPort, dataReg, lastCommand, statusReg, and UNSERIALIZE_SCALAR.
Referenced by getPort().
write()
Tick X86ISA::I8042::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 145 of file i8042.cc.
References X86ISA::addr, bits(), CheckForPassword, CheckPassword, commandByte, commandPort, ContinuousPollHigh, ContinuousPollLow, data, dataPort, DiagnosticDump, DisableA20, DisableKeyboard, DisableMouse, DPRINTF, EnableA20, EnableKeyboard, EnableMouse, Packet::getAddr(), GetCommandByte, Packet::getLE(), Packet::getSize(), PS2Device::hostDataAvailable(), PS2Device::hostRead(), PS2Device::hostWrite(), InterfaceTest, keyboard, lastCommand, LoadPassword, Packet::makeAtomicResponse(), mouse, NoCommand, NumOutputBits, panic, panic_if, PulseOutputBitBase, RamSize, ReadControllerRamBase, ReadInputPort, ReadOutputPort, ReadTestInputs, SelfTest, statusReg, SystemReset, TestMouse, warn, WriteCommandByte, WriteControllerRamBase, writeData(), WriteKeyboardOutputBuff, WriteMouseOutputBuff, WriteOutputPort, and WriteToMouse.
Referenced by getPort().
writeData()
void X86ISA::I8042::writeData (uint8_t newData, bool mouse = false) protected
Definition at line 88 of file i8042.cc.
References commandByte, dataReg, DPRINTF, keyboardIntPin, mouseIntPin, and statusReg.
Referenced by readDataOut(), and write().
Member Data Documentation
commandByte
CommandByte X86ISA::I8042::commandByte protected
Definition at line 104 of file i8042.hh.
Referenced by I8042(), serialize(), unserialize(), write(), and writeData().
commandLast
Bitfield<3> X86ISA::I8042::commandLast protected
Definition at line 84 of file i8042.hh.
commandPort
Addr X86ISA::I8042::commandPort protected
Definition at line 101 of file i8042.hh.
Referenced by getAddrRanges(), read(), serialize(), unserialize(), and write().
dataPort
Addr X86ISA::I8042::dataPort protected
Definition at line 100 of file i8042.hh.
Referenced by getAddrRanges(), read(), serialize(), unserialize(), and write().
dataReg
uint8_t X86ISA::I8042::dataReg protected
Definition at line 106 of file i8042.hh.
Referenced by readDataOut(), serialize(), unserialize(), and writeData().
disableKeyboard
Bitfield<4> X86ISA::I8042::disableKeyboard protected
Definition at line 93 of file i8042.hh.
disableMouse
Bitfield<5> X86ISA::I8042::disableMouse protected
Definition at line 92 of file i8042.hh.
inputFull
Bitfield<1> X86ISA::I8042::inputFull protected
Definition at line 86 of file i8042.hh.
keyboard
PS2Device* X86ISA::I8042::keyboard protected
Definition at line 115 of file i8042.hh.
Referenced by I8042(), readDataOut(), and write().
keyboardFullInt
Bitfield<0> X86ISA::I8042::keyboardFullInt protected
Definition at line 96 of file i8042.hh.
keyboardIntPin
std::vector<IntSourcePin<I8042> *> X86ISA::I8042::keyboardIntPin protected
Definition at line 112 of file i8042.hh.
Referenced by I8042(), and writeData().
keyboardUnlocked
Bitfield<4> X86ISA::I8042::keyboardUnlocked protected
Definition at line 83 of file i8042.hh.
lastCommand
uint16_t X86ISA::I8042::lastCommand protected
Definition at line 109 of file i8042.hh.
Referenced by serialize(), unserialize(), and write().
mouse
PS2Device* X86ISA::I8042::mouse protected
Definition at line 114 of file i8042.hh.
Referenced by I8042(), readDataOut(), and write().
mouseFullInt
Bitfield<1> X86ISA::I8042::mouseFullInt protected
Definition at line 95 of file i8042.hh.
mouseIntPin
std::vector<IntSourcePin<I8042> *> X86ISA::I8042::mouseIntPin protected
Definition at line 111 of file i8042.hh.
Referenced by I8042(), and writeData().
mouseOutputFull
Bitfield<5> X86ISA::I8042::mouseOutputFull protected
Definition at line 82 of file i8042.hh.
NoCommand
const uint16_t X86ISA::I8042::NoCommand = (uint16_t)(-1) static protected
Definition at line 108 of file i8042.hh.
Referenced by write().
outputFull
Bitfield<0> X86ISA::I8042::outputFull protected
Definition at line 87 of file i8042.hh.
passedSelfTest
Bitfield< 2 > X86ISA::I8042::passedSelfTest protected
Definition at line 85 of file i8042.hh.
statusReg
StatusReg X86ISA::I8042::statusReg protected
Definition at line 103 of file i8042.hh.
Referenced by I8042(), read(), readDataOut(), serialize(), unserialize(), write(), and writeData().
timeout
Bitfield<6> X86ISA::I8042::timeout protected
Definition at line 81 of file i8042.hh.
The documentation for this class was generated from the following files:
dev/x86/i8042.hh
dev/x86/i8042.cc