gem5: AlphaISA::StackTrace Class Reference
AlphaISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Types
enum { user = 1, console = 2, unknown = 3 }
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 63 of file stacktrace.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
user
console
unknown
Definition at line 95 of file stacktrace.hh.
Constructor & Destructor Documentation
StackTrace() [1/2]
AlphaISA::StackTrace::StackTrace ()
Definition at line 121 of file stacktrace.cc.
StackTrace() [2/2]
AlphaISA::StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 126 of file stacktrace.cc.
References trace().
~StackTrace()
AlphaISA::StackTrace::~StackTrace ()
Definition at line 132 of file stacktrace.cc.
Member Function Documentation
clear()
void AlphaISA::StackTrace::clear () inline
Definition at line 83 of file stacktrace.hh.
decodePrologue()
bool AlphaISA::StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) private
Definition at line 307 of file stacktrace.cc.
References addr, console, decodeSave(), decodeStack(), DPRINTFN, Stats::dump(), ThreadContext::getCpuPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), ArmISA::i, System::kernelSymtab, name(), SimObject::name(), MipsISA::pc, PortProxy::read(), X86ISA::reg, AlphaISA::ReturnAddressReg, stack, tc, unknown, and user.
Referenced by trace().
decodeSave()
bool AlphaISA::StackTrace::decodeSave (MachInst inst, int & reg, int & disp) private
Definition at line 278 of file stacktrace.cc.
Referenced by decodePrologue().
decodeStack()
bool AlphaISA::StackTrace::decodeStack (MachInst inst, int & disp) private
Definition at line 237 of file stacktrace.cc.
Referenced by decodePrologue().
dprintf()
void AlphaISA::StackTrace::dprintf () inline
Definition at line 109 of file stacktrace.hh.
getstack()
const std::vector<Addr>& AlphaISA::StackTrace::getstack () const inline
Definition at line 93 of file stacktrace.hh.
References X86ISA::stack.
isEntry()
bool AlphaISA::StackTrace::isEntry (Addr addr) private
Definition at line 213 of file stacktrace.cc.
References AlphaISA::IPR_PALtemp11, AlphaISA::IPR_PALtemp12, AlphaISA::IPR_PALtemp2, AlphaISA::IPR_PALtemp21, AlphaISA::IPR_PALtemp7, AlphaISA::IPR_PALtemp9, ThreadContext::readMiscRegNoEffect(), and tc.
Referenced by trace().
trace() [1/2]
void AlphaISA::StackTrace::trace (ThreadContext * tc, bool is_call) private
Definition at line 137 of file stacktrace.cc.
References addr, console, decodePrologue(), SymbolTable::findNearestAddr(), ThreadContext::getSystemPtr(), AlphaISA::IPR_DTB_CM, isEntry(), AlphaISA::Kernel::kernel, System::kernelEnd, System::kernelStart, System::kernelSymtab, panic, MipsISA::pc, ThreadContext::pcState(), PowerISA::ra, ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), stack, AlphaISA::StackPointerReg, tc, unknown, and user.
Referenced by StackTrace().
trace() [2/2]
bool AlphaISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 114 of file stacktrace.hh.
References StaticInst::isCall(), and StaticInst::isReturn().
valid()
bool AlphaISA::StackTrace::valid () const inline
Definition at line 89 of file stacktrace.hh.
Member Data Documentation
stack
std::vector<Addr> AlphaISA::StackTrace::stack private
Definition at line 67 of file stacktrace.hh.
Referenced by decodePrologue(), and trace().
tc
ThreadContext* AlphaISA::StackTrace::tc private
Definition at line 66 of file stacktrace.hh.
Referenced by decodePrologue(), isEntry(), and trace().
The documentation for this class was generated from the following files:
arch/alpha/stacktrace.hh
arch/alpha/stacktrace.cc