gem5: PacketQueue Class Reference
PacketQueue Class Reference abstract
A packet queue is a class that holds deferred packets and later sends them using the associated slave port or master port.
#include <packet_queue.hh>
Classes
class DeferredPacket
A deferred packet, buffered to transmit later.
Public Member Functions
virtual const std::string name () const =0
Provide a name to simplify debugging.
size_t size () const
Get the size of the queue.
Tick deferredPacketReadyTime () const
Get the next packet ready time.
bool checkConflict (const PacketPtr pkt, const int blk_size) const
Check if a packet corresponding to the same address exists in the queue.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
void schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
void schedSendTiming (PacketPtr pkt, Tick when)
Add a packet to the transmit list, and schedule a send event.
void retry ()
Retry sending a packet from the queue.
void disableSanityCheck ()
This allows a user to explicitly disable the sanity check on the size of the transmitList, which is enabled by default.
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Protected Member Functions
bool deferredPacketReady () const
Check whether we have a packet ready to go on the transmit list.
virtual void sendDeferredPacket ()
Attempt to send a packet.
virtual bool sendTiming (PacketPtr pkt)=0
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
PacketQueue (EventManager &_em, const std::string &_label, const std::string &_sendEventName, bool force_order=false, bool disable_sanity_check=false)
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
virtual ~PacketQueue ()
Virtual desctructor since the class may be used as a base class.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const std::string label
Label to use for print request packets label stack.
bool waitingOnRetry
Remember whether we're awaiting a retry.
Private Types
typedef std::list< DeferredPacket > DeferredPacketList
Private Member Functions
void processSendEvent ()
Used to schedule sending of deferred packets.
Private Attributes
DeferredPacketList transmitList
A list of outgoing packets.
EventManager & em
The manager which is used for the event queue.
EventFunctionWrapper sendEvent
Event used to call processSendEvent.
bool _disableSanityCheck
bool forceOrder
if true, inserted packets have to be unconditionally scheduled after the last packet in the queue that references the same address
Detailed Description
A packet queue is a class that holds deferred packets and later sends them using the associated slave port or master port.
Definition at line 65 of file packet_queue.hh.
Member Typedef Documentation
DeferredPacketList
typedef std::list<DeferredPacket> PacketQueue::DeferredPacketList private
Definition at line 78 of file packet_queue.hh.
Constructor & Destructor Documentation
PacketQueue()
PacketQueue::PacketQueue (EventManager & _em, const std::string & _label, const std::string & _sendEventName, bool force_order = false, bool disable_sanity_check = false) protected
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
Parameters
_em Event manager used for scheduling this queue
_label Label to push on the label stack for print request packets
force_order Force insertion order for packets with same address
disable_sanity_check Flag used to disable the sanity check on the size of the transmitList. The check is enabled by default.
Definition at line 50 of file packet_queue.cc.
References _disableSanityCheck, forceOrder, label, processSendEvent(), and waitingOnRetry.
Referenced by deferredPacketReady().
~PacketQueue()
PacketQueue::~PacketQueue () protected virtual
Virtual desctructor since the class may be used as a base class.
Definition at line 61 of file packet_queue.cc.
Referenced by deferredPacketReady().
Member Function Documentation
checkConflict()
bool PacketQueue::checkConflict (const PacketPtr pkt, const int blk_size) const
Check if a packet corresponding to the same address exists in the queue.
Parameters
pkt The packet to compare against.
blk_size Block size in bytes.
Returns
Whether a corresponding packet is found.
Definition at line 75 of file packet_queue.cc.
References MipsISA::p, and transmitList.
Referenced by BaseCache::CacheReqPacketQueue::checkConflictingSnoop(), and deferredPacketReadyTime().
deferredPacketReady()
bool PacketQueue::deferredPacketReady () const inline protected
Check whether we have a packet ready to go on the transmit list.
Definition at line 115 of file packet_queue.hh.
References curTick(), name(), PacketQueue(), PacketQueue::DeferredPacket::pkt, sendDeferredPacket(), sendTiming(), and ~PacketQueue().
Referenced by sendDeferredPacket().
deferredPacketReadyTime()
Tick PacketQueue::deferredPacketReadyTime () const inline
Get the next packet ready time.
Definition at line 171 of file packet_queue.hh.
References checkConflict(), MaxTick, retry(), schedSendEvent(), schedSendTiming(), and trySatisfyFunctional().
Referenced by BaseCache::CacheReqPacketQueue::checkConflictingSnoop(), and sendDeferredPacket().
disableSanityCheck()
void PacketQueue::disableSanityCheck () inline
This allows a user to explicitly disable the sanity check on the size of the transmitList, which is enabled by default.
Users must use this function to explicitly disable the sanity check.
Definition at line 220 of file packet_queue.hh.
References drain().
drain()
DrainState PacketQueue::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 228 of file packet_queue.cc.
References DPRINTF, Drained, Draining, and transmitList.
Referenced by disableSanityCheck().
name()
virtual const std::string PacketQueue::name () const pure virtual
Provide a name to simplify debugging.
Returns
A complete name, appended to module and port
Implemented in RespPacketQueue, SnoopRespPacketQueue, and ReqPacketQueue.
Referenced by deferredPacketReady(), ReqPacketQueue::name(), SnoopRespPacketQueue::name(), RespPacketQueue::name(), retry(), and schedSendTiming().
processSendEvent()
void PacketQueue::processSendEvent () private
Used to schedule sending of deferred packets.
Definition at line 221 of file packet_queue.cc.
References sendDeferredPacket(), and waitingOnRetry.
Referenced by PacketQueue().
retry()
void PacketQueue::retry ()
Retry sending a packet from the queue.
Note that this is not necessarily the same packet if something has been added with an earlier time stamp.
Definition at line 66 of file packet_queue.cc.
References DPRINTF, name(), sendDeferredPacket(), and waitingOnRetry.
Referenced by deferredPacketReadyTime(), QueuedMasterPort::recvReqRetry(), QueuedSlavePort::recvRespRetry(), and QueuedMasterPort::recvRetrySnoopResp().
schedSendEvent()
void PacketQueue::schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
If the requested time is before an already scheduled send event, the event will be rescheduled. If MaxTick is passed, no event is scheduled. Instead, if we are idle and asked to drain then check and signal drained.
Parameters
when time to schedule an event
Definition at line 155 of file packet_queue.cc.
References curTick(), DPRINTF, Draining, Drainable::drainState(), em, MaxTick, EventManager::reschedule(), EventManager::schedule(), Event::scheduled(), sendEvent, Drainable::signalDrainDone(), transmitList, waitingOnRetry, and Event::when().
Referenced by deferredPacketReadyTime(), BaseCache::CacheMasterPort::schedSendEvent(), schedSendTiming(), and sendDeferredPacket().
schedSendTiming()
void PacketQueue::schedSendTiming (PacketPtr pkt, Tick when)
Add a packet to the transmit list, and schedule a send event.
Parameters
pkt Packet to send
when Absolute time (in ticks) to send packet
Definition at line 107 of file packet_queue.cc.
References _disableSanityCheck, Packet::cmdString(), curTick(), DPRINTF, forceOrder, Packet::getAddr(), Packet::getSize(), Packet::isExpressSnoop(), name(), panic, schedSendEvent(), and transmitList.
Referenced by deferredPacketReadyTime(), QueuedMasterPort::schedTimingReq(), QueuedSlavePort::schedTimingResp(), and QueuedMasterPort::schedTimingSnoopResp().
sendDeferredPacket()
void PacketQueue::sendDeferredPacket () protected virtual
Attempt to send a packet.
Note that a subclass of the PacketQueue can override this method and thus change the behaviour (as done by the cache for the request queue). The default implementation sends the head of the transmit list. The caller must guarantee that the list is non-empty and that the head packet is scheduled for curTick() (or earlier).
Reimplemented in BaseCache::CacheReqPacketQueue.
Definition at line 191 of file packet_queue.cc.
References deferredPacketReady(), deferredPacketReadyTime(), ArmISA::dp, PacketQueue::DeferredPacket::pkt, schedSendEvent(), sendTiming(), transmitList, and waitingOnRetry.
Referenced by deferredPacketReady(), processSendEvent(), and retry().
sendTiming()
virtual bool PacketQueue::sendTiming (PacketPtr pkt) protected pure virtual
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
Implemented in RespPacketQueue, SnoopRespPacketQueue, and ReqPacketQueue.
Referenced by deferredPacketReady(), ReqPacketQueue::name(), SnoopRespPacketQueue::name(), RespPacketQueue::name(), and sendDeferredPacket().
size()
size_t PacketQueue::size () const inline
Get the size of the queue.
Definition at line 166 of file packet_queue.hh.
trySatisfyFunctional()
bool PacketQueue::trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Definition at line 87 of file packet_queue.cc.
References ArmISA::i, label, Packet::popLabel(), Packet::pushLabel(), transmitList, and Packet::trySatisfyFunctional().
Referenced by deferredPacketReadyTime(), SimpleTimingPort::recvFunctional(), SMMUSlavePort::recvFunctional(), QoS::MemSinkCtrl::MemoryPort::recvFunctional(), DRAMCtrl::MemoryPort::recvFunctional(), QueuedSlavePort::trySatisfyFunctional(), and QueuedMasterPort::trySatisfyFunctional().
Member Data Documentation
_disableSanityCheck
bool PacketQueue::_disableSanityCheck private
Definition at line 97 of file packet_queue.hh.
Referenced by PacketQueue(), and schedSendTiming().
em
EventManager& PacketQueue::em private
The manager which is used for the event queue.
Definition at line 84 of file packet_queue.hh.
Referenced by schedSendEvent().
forceOrder
bool PacketQueue::forceOrder private
if true, inserted packets have to be unconditionally scheduled after the last packet in the queue that references the same address
Definition at line 104 of file packet_queue.hh.
Referenced by PacketQueue(), and schedSendTiming().
label
const std::string PacketQueue::label protected
Label to use for print request packets label stack.
Definition at line 109 of file packet_queue.hh.
Referenced by ReqPacketQueue::name(), SnoopRespPacketQueue::name(), RespPacketQueue::name(), PacketQueue(), and trySatisfyFunctional().
sendEvent
EventFunctionWrapper PacketQueue::sendEvent private
Event used to call processSendEvent.
Definition at line 90 of file packet_queue.hh.
Referenced by schedSendEvent().
transmitList
DeferredPacketList PacketQueue::transmitList private
A list of outgoing packets.
Definition at line 81 of file packet_queue.hh.
Referenced by checkConflict(), drain(), schedSendEvent(), schedSendTiming(), sendDeferredPacket(), and trySatisfyFunctional().
waitingOnRetry
bool PacketQueue::waitingOnRetry protected
Remember whether we're awaiting a retry.
Definition at line 112 of file packet_queue.hh.
Referenced by PacketQueue(), processSendEvent(), retry(), schedSendEvent(), and sendDeferredPacket().
The documentation for this class was generated from the following files:
mem/packet_queue.hh
mem/packet_queue.cc