gem5: EtherInt Class Reference
EtherInt Class Reference abstract
#include <etherint.hh>
Public Member Functions
EtherInt (const std::string &name, int idx=InvalidPortID)
virtual ~EtherInt ()
const std::string & name () const
Return port name (for DPRINTF).
void bind (Port &peer) override
Attach to a peer port.
void unbind () override
Dettach from a peer port.
void setPeer (EtherInt *p)
EtherInt * getPeer ()
void recvDone ()
virtual void sendDone ()=0
bool sendPacket (EthPacketPtr packet)
virtual bool recvPacket (EthPacketPtr packet)=0
bool askBusy ()
virtual bool isBusy ()
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Attributes
std::string portName
EtherInt * peer
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Additional Inherited Members
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Detailed Description
Definition at line 49 of file etherint.hh.
Constructor & Destructor Documentation
EtherInt()
EtherInt::EtherInt (const std::string & name, int idx = InvalidPortID) inline
Definition at line 56 of file etherint.hh.
~EtherInt()
virtual EtherInt::~EtherInt () inline virtual
Definition at line 58 of file etherint.hh.
Member Function Documentation
askBusy()
bool EtherInt::askBusy () inline
Definition at line 76 of file etherint.hh.
bind()
void EtherInt::bind (Port & peer) override virtual
Attach to a peer port.
Reimplemented from Port.
Definition at line 37 of file etherint.cc.
References Port::_connected, fatal, name(), Port::name(), MipsISA::p, peer, and setPeer().
Referenced by name().
getPeer()
EtherInt* EtherInt::getPeer () inline
Definition at line 67 of file etherint.hh.
References peer.
isBusy()
virtual bool EtherInt::isBusy () inline virtual
Reimplemented in DistEtherLink::LocalIface, and EtherLink::Interface.
Definition at line 77 of file etherint.hh.
name()
const std::string& EtherInt::name () const inline
Return port name (for DPRINTF).
Definition at line 61 of file etherint.hh.
References bind(), MipsISA::p, portName, setPeer(), and unbind().
Referenced by bind(), EtherSwitch::Interface::Interface(), EtherSwitch::Interface::learnSenderAddr(), EtherSwitch::Interface::recvPacket(), and setPeer().
recvDone()
void EtherInt::recvDone () inline
Definition at line 69 of file etherint.hh.
References sendDone().
Referenced by EtherTapBase::recvSimulated().
recvPacket()
virtual bool EtherInt::recvPacket (EthPacketPtr packet) pure virtual
Implemented in IGbEInt, NSGigEInt, Sinic::Interface, DistEtherLink::LocalIface, EtherLink::Interface, EtherTapInt, and EtherSwitch::Interface.
Referenced by sendPacket().
sendDone()
virtual void EtherInt::sendDone () pure virtual
Implemented in IGbEInt, NSGigEInt, Sinic::Interface, DistEtherLink::LocalIface, EtherLink::Interface, EtherTapInt, and EtherSwitch::Interface.
Referenced by recvDone(), and EtherBus::txDone().
sendPacket()
bool EtherInt::sendPacket (EthPacketPtr packet) inline
Definition at line 72 of file etherint.hh.
References recvPacket().
Referenced by EtherTapBase::retransmit(), DistEtherLink::RxLink::rxDone(), EtherTapBase::sendSimulated(), EtherSwitch::Interface::transmit(), Sinic::Device::transmit(), NSGigE::transmit(), EtherLink::Link::txComplete(), and IGbE::txWire().
setPeer()
void EtherInt::setPeer (EtherInt * p)
Definition at line 56 of file etherint.cc.
References name(), MipsISA::p, panic, and peer.
Referenced by bind(), and name().
unbind()
void EtherInt::unbind () override virtual
Dettach from a peer port.
Reimplemented from Port.
Definition at line 49 of file etherint.cc.
References Port::_connected, and peer.
Referenced by name().
Member Data Documentation
peer
EtherInt* EtherInt::peer protected
Definition at line 53 of file etherint.hh.
Referenced by bind(), getPeer(), setPeer(), and unbind().
portName
std::string EtherInt::portName mutable protected
Definition at line 52 of file etherint.hh.
Referenced by name().
The documentation for this class was generated from the following files:
dev/net/etherint.hh
dev/net/etherint.cc