gem5: BaseGdbRegCache Class Reference
BaseGdbRegCache Class Reference abstract
Concrete subclasses of this abstract class represent how the register values are transmitted on the wire.
#include <remote_gdb.hh>
Public Member Functions
virtual char * data () const =0
Return the pointer to the raw bytes buffer containing the register values.
virtual size_t size () const =0
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
virtual void getRegs (ThreadContext *)=0
Fill the raw buffer from the registers in the ThreadContext.
virtual void setRegs (ThreadContext *) const =0
Set the ThreadContext's registers from the values in the raw buffer.
virtual const std::string name () const =0
Return the name to use in places like DPRINTF.
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Protected Attributes
BaseRemoteGDB * gdb
Detailed Description
Concrete subclasses of this abstract class represent how the register values are transmitted on the wire.
Usually each architecture should define one subclass, but there can be more if there is more than one possible wire format. For example, ARM defines both AArch32GdbRegCache and AArch64GdbRegCache.
Definition at line 73 of file remote_gdb.hh.
Constructor & Destructor Documentation
BaseGdbRegCache()
BaseGdbRegCache::BaseGdbRegCache (BaseRemoteGDB * g) inline
Definition at line 109 of file remote_gdb.hh.
~BaseGdbRegCache()
virtual BaseGdbRegCache::~BaseGdbRegCache () inline virtual
Definition at line 111 of file remote_gdb.hh.
Member Function Documentation
data()
virtual char* BaseGdbRegCache::data () const pure virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implemented in X86ISA::RemoteGDB::AMD64GdbRegCache, ArmISA::RemoteGDB::AArch64GdbRegCache, SparcISA::RemoteGDB::SPARC64GdbRegCache, X86ISA::RemoteGDB::X86GdbRegCache, ArmISA::RemoteGDB::AArch32GdbRegCache, MipsISA::RemoteGDB::MipsGdbRegCache, RiscvISA::RemoteGDB::RiscvGdbRegCache, PowerISA::RemoteGDB::PowerGdbRegCache, SparcISA::RemoteGDB::SPARCGdbRegCache, and AlphaISA::RemoteGDB::AlphaGdbRegCache.
Referenced by BaseRemoteGDB::cmd_reg_r(), BaseRemoteGDB::cmd_reg_w(), and BaseRemoteGDB::TrapEvent::process().
getRegs()
virtual void BaseGdbRegCache::getRegs (ThreadContext *) pure virtual
Fill the raw buffer from the registers in the ThreadContext.
Implemented in X86ISA::RemoteGDB::AMD64GdbRegCache, ArmISA::RemoteGDB::AArch64GdbRegCache, SparcISA::RemoteGDB::SPARC64GdbRegCache, X86ISA::RemoteGDB::X86GdbRegCache, ArmISA::RemoteGDB::AArch32GdbRegCache, MipsISA::RemoteGDB::MipsGdbRegCache, RiscvISA::RemoteGDB::RiscvGdbRegCache, PowerISA::RemoteGDB::PowerGdbRegCache, SparcISA::RemoteGDB::SPARCGdbRegCache, and AlphaISA::RemoteGDB::AlphaGdbRegCache.
Referenced by BaseRemoteGDB::trap().
name()
virtual const std::string BaseGdbRegCache::name () const pure virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implemented in X86ISA::RemoteGDB::AMD64GdbRegCache, ArmISA::RemoteGDB::AArch64GdbRegCache, SparcISA::RemoteGDB::SPARC64GdbRegCache, X86ISA::RemoteGDB::X86GdbRegCache, ArmISA::RemoteGDB::AArch32GdbRegCache, RiscvISA::RemoteGDB::RiscvGdbRegCache, MipsISA::RemoteGDB::MipsGdbRegCache, PowerISA::RemoteGDB::PowerGdbRegCache, SparcISA::RemoteGDB::SPARCGdbRegCache, and AlphaISA::RemoteGDB::AlphaGdbRegCache.
setRegs()
virtual void BaseGdbRegCache::setRegs (ThreadContext *) const pure virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implemented in X86ISA::RemoteGDB::AMD64GdbRegCache, ArmISA::RemoteGDB::AArch64GdbRegCache, SparcISA::RemoteGDB::SPARC64GdbRegCache, X86ISA::RemoteGDB::X86GdbRegCache, ArmISA::RemoteGDB::AArch32GdbRegCache, MipsISA::RemoteGDB::MipsGdbRegCache, RiscvISA::RemoteGDB::RiscvGdbRegCache, PowerISA::RemoteGDB::PowerGdbRegCache, SparcISA::RemoteGDB::SPARCGdbRegCache, and AlphaISA::RemoteGDB::AlphaGdbRegCache.
Referenced by BaseRemoteGDB::cmd_reg_w().
size()
virtual size_t BaseGdbRegCache::size () const pure virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implemented in X86ISA::RemoteGDB::AMD64GdbRegCache, ArmISA::RemoteGDB::AArch64GdbRegCache, SparcISA::RemoteGDB::SPARC64GdbRegCache, X86ISA::RemoteGDB::X86GdbRegCache, ArmISA::RemoteGDB::AArch32GdbRegCache, MipsISA::RemoteGDB::MipsGdbRegCache, RiscvISA::RemoteGDB::RiscvGdbRegCache, PowerISA::RemoteGDB::PowerGdbRegCache, SparcISA::RemoteGDB::SPARCGdbRegCache, and AlphaISA::RemoteGDB::AlphaGdbRegCache.
Referenced by BaseRemoteGDB::cmd_reg_r(), BaseRemoteGDB::cmd_reg_w(), and BaseRemoteGDB::TrapEvent::process().
Member Data Documentation
gdb
BaseRemoteGDB* BaseGdbRegCache::gdb protected
Definition at line 115 of file remote_gdb.hh.
Referenced by AlphaISA::RemoteGDB::AlphaGdbRegCache::name(), PowerISA::RemoteGDB::PowerGdbRegCache::name(), SparcISA::RemoteGDB::SPARCGdbRegCache::name(), MipsISA::RemoteGDB::MipsGdbRegCache::name(), RiscvISA::RemoteGDB::RiscvGdbRegCache::name(), ArmISA::RemoteGDB::AArch32GdbRegCache::name(), X86ISA::RemoteGDB::X86GdbRegCache::name(), SparcISA::RemoteGDB::SPARC64GdbRegCache::name(), ArmISA::RemoteGDB::AArch64GdbRegCache::name(), and X86ISA::RemoteGDB::AMD64GdbRegCache::name().
The documentation for this class was generated from the following file:
base/remote_gdb.hh