gem5: PowerISA::Decoder Class Reference
PowerISA::Decoder Class Reference
#include <decoder.hh>
Public Member Functions
Decoder (ISA *isa=nullptr)
void process ()
void reset ()
void moreBytes (const PCState &pc, Addr fetchPC, MachInst inst)
void moreBytes (MachInst machInst)
bool needMoreBytes ()
bool instReady ()
void takeOverFrom (Decoder *old)
StaticInstPtr decodeInst (ExtMachInst mach_inst)
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
StaticInstPtr decode (PowerISA::PCState &nextPC)
Protected Attributes
ExtMachInst emi
bool instDone
Static Protected Attributes
static GenericISA::BasicDecodeCache defaultCache
A cache of decoded instruction objects.
Detailed Description
Definition at line 42 of file decoder.hh.
Constructor & Destructor Documentation
Decoder()
PowerISA::Decoder::Decoder (ISA * isa = nullptr) inline
Definition at line 50 of file decoder.hh.
Member Function Documentation
decode() [1/2]
StaticInstPtr PowerISA::Decoder::decode (ExtMachInst mach_inst, Addr addr) inline
Decode a machine instruction.
Parameters
mach_inst The binary instruction to decode.
Return values
A pointer to the corresponding StaticInst object.
Definition at line 107 of file decoder.hh.
References GenericISA::BasicDecodeCache::decode().
Referenced by decode().
decode() [2/2]
StaticInstPtr PowerISA::Decoder::decode (PowerISA::PCState & nextPC) inline
Definition at line 113 of file decoder.hh.
References decode().
decodeInst()
StaticInstPtr PowerISA::Decoder::decodeInst (ExtMachInst mach_inst)
instReady()
bool PowerISA::Decoder::instReady () inline
Definition at line 89 of file decoder.hh.
References instDone.
moreBytes() [1/2]
void PowerISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst inst) inline
Definition at line 68 of file decoder.hh.
References betoh().
Referenced by moreBytes().
moreBytes() [2/2]
void PowerISA::Decoder::moreBytes (MachInst machInst) inline
Definition at line 77 of file decoder.hh.
References moreBytes().
needMoreBytes()
bool PowerISA::Decoder::needMoreBytes () inline
Definition at line 83 of file decoder.hh.
process()
void PowerISA::Decoder::process () inline
Definition at line 55 of file decoder.hh.
reset()
void PowerISA::Decoder::reset () inline
Definition at line 60 of file decoder.hh.
takeOverFrom()
void PowerISA::Decoder::takeOverFrom (Decoder * old) inline
Definition at line 94 of file decoder.hh.
Member Data Documentation
defaultCache
GenericISA::BasicDecodeCache PowerISA::Decoder::defaultCache static protected
A cache of decoded instruction objects.
Definition at line 98 of file decoder.hh.
emi
ExtMachInst PowerISA::Decoder::emi protected
Definition at line 46 of file decoder.hh.
instDone
bool PowerISA::Decoder::instDone protected
Definition at line 47 of file decoder.hh.
Referenced by instReady().
The documentation for this class was generated from the following files:
arch/power/decoder.hh
arch/power/decoder.cc