gem5: BmpWriter Class Reference
BmpWriter Class Reference
#include <bmpwriter.hh>
Classes
struct BmpPixel32
struct CompleteV1Header
struct FileHeader
struct InfoHeaderV1
Public Member Functions
BmpWriter (const FrameBuffer *fb)
Create a bitmap that takes data in a given mode & size and outputs to an ostream.
~BmpWriter ()
const char * getImgExtension () const override
void write (std::ostream &bmp) const override
Write the frame buffer data into the provided ostream.
Public Member Functions inherited from ImgWriter
ImgWriter (const FrameBuffer *_fb)
virtual ~ImgWriter ()
Private Types
typedef BmpPixel32 PixelType
Private Member Functions
const CompleteV1Header getCompleteHeader () const
Private Attributes
struct BmpWriter::FileHeader M5_ATTR_PACKED
struct BmpWriter::InfoHeaderV1 M5_ATTR_PACKED
struct BmpWriter::CompleteV1Header M5_ATTR_PACKED
struct BmpWriter::BmpPixel32 M5_ATTR_PACKED
Static Private Attributes
static const char * _imgExtension = "bmp"
Additional Inherited Members
Protected Attributes inherited from ImgWriter
const FrameBuffer & fb
Detailed Description
Definition at line 56 of file bmpwriter.hh.
Member Typedef Documentation
PixelType
typedef BmpPixel32 BmpWriter::PixelType private
Definition at line 125 of file bmpwriter.hh.
Constructor & Destructor Documentation
BmpWriter()
BmpWriter::BmpWriter (const FrameBuffer * fb)
Create a bitmap that takes data in a given mode & size and outputs to an ostream.
Definition at line 52 of file bmpwriter.cc.
~BmpWriter()
BmpWriter::~BmpWriter () inline
Definition at line 65 of file bmpwriter.hh.
Member Function Documentation
getCompleteHeader()
const BmpWriter::CompleteV1Header BmpWriter::getCompleteHeader () const private
Definition at line 58 of file bmpwriter.cc.
References FrameBuffer::area(), ImgWriter::fb, header, FrameBuffer::height(), and FrameBuffer::width().
Referenced by write().
getImgExtension()
const char* BmpWriter::getImgExtension () const inline override virtual
Implements ImgWriter.
Definition at line 72 of file bmpwriter.hh.
References _imgExtension, and write().
write()
void BmpWriter::write (std::ostream & bmp) const override virtual
Write the frame buffer data into the provided ostream.
Parameters
bmp stream to write to
Implements ImgWriter.
Definition at line 91 of file bmpwriter.cc.
References ImgWriter::fb, getCompleteHeader(), header, FrameBuffer::height(), FrameBuffer::pixel(), FrameBuffer::width(), and X86ISA::x.
Referenced by Pl111::dmaDone(), and getImgExtension().
Member Data Documentation
_imgExtension
const char * BmpWriter::_imgExtension = "bmp" static private
Definition at line 127 of file bmpwriter.hh.
Referenced by getImgExtension().
M5_ATTR_PACKED [1/4]
struct BmpWriter::FileHeader BmpWriter::M5_ATTR_PACKED private
M5_ATTR_PACKED [2/4]
struct BmpWriter::InfoHeaderV1 BmpWriter::M5_ATTR_PACKED private
M5_ATTR_PACKED [3/4]
struct BmpWriter::CompleteV1Header BmpWriter::M5_ATTR_PACKED private
M5_ATTR_PACKED [4/4]
struct BmpWriter::BmpPixel32 BmpWriter::M5_ATTR_PACKED private
The documentation for this class was generated from the following files:
base/bmpwriter.hh
base/bmpwriter.cc