gem5: FunctionalRequestProtocol Class Reference
FunctionalRequestProtocol Class Reference abstract
#include <functional.hh>
Protected Member Functions
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
virtual void recvFunctionalSnoop (PacketPtr pkt)=0
Receive a functional snoop request packet from the peer.
Friends
class FunctionalResponseProtocol
Detailed Description
Definition at line 52 of file functional.hh.
Member Function Documentation
recvFunctionalSnoop()
virtual void FunctionalRequestProtocol::recvFunctionalSnoop (PacketPtr pkt) protected pure virtual
Receive a functional snoop request packet from the peer.
Implemented in TraceCPU::DcachePort, TimingSimpleCPU::DcachePort, BaseCache::MemSidePort, MasterPort, CoherentXBar::CoherentXBarMasterPort, AtomicSimpleCPU::AtomicCPUDPort, BaseTrafficGen::TrafficGenPort, LSQ< Impl >::DcachePort, CommMonitor::MonitorMasterPort, MemTest::CpuPort, AddrMapper::MapperMasterPort, Minor::LSQ::DcachePort, MemCheckerMonitor::MonitorMasterPort, PortProxy, and MemDelay::MasterPort.
Referenced by FunctionalResponseProtocol::sendSnoop().
send()
void FunctionalRequestProtocol::send (FunctionalResponseProtocol * peer, PacketPtr pkt) const protected
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters
pkt Packet to send.
Definition at line 50 of file functional.cc.
References Packet::isRequest(), and FunctionalResponseProtocol::recvFunctional().
Referenced by MasterPort::sendFunctional().
Friends And Related Function Documentation
FunctionalResponseProtocol
friend class FunctionalResponseProtocol friend
Definition at line 54 of file functional.hh.
The documentation for this class was generated from the following files:
mem/protocol/functional.hh
mem/protocol/functional.cc