gem5: SparcISA::RemoteGDB::SPARC64GdbRegCache Class Reference
SparcISA::RemoteGDB::SPARC64GdbRegCache Class Reference
#include <remote_gdb.hh>
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct {
uint64_t gpr [32]
uint64_t fpr [32]
uint64_t pc
uint64_t npc
uint64_t state
uint64_t fsr
uint64_t fprs
uint64_t y
} r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 79 of file remote_gdb.hh.
Member Function Documentation
data()
char* SparcISA::RemoteGDB::SPARC64GdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 94 of file remote_gdb.hh.
References SparcISA::RemoteGDB::SPARCGdbRegCache::r.
getRegs()
void RemoteGDB::SPARC64GdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 190 of file remote_gdb.cc.
References DPRINTF, htobe(), ArmISA::i, SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_FPRS, SparcISA::MISCREG_FSR, SparcISA::MISCREG_PSTATE, SparcISA::NumIntArchRegs, MipsISA::pc, ThreadContext::pcState(), MipsISA::r, ThreadContext::readIntReg(), and ThreadContext::readMiscReg().
name()
const std::string SparcISA::RemoteGDB::SPARC64GdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 99 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::SPARC64GdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 226 of file remote_gdb.cc.
References ArmISA::i, GenericISA::DelaySlotPCState< MachInst >::nnpc(), GenericISA::SimplePCState< MachInst >::npc(), GenericISA::DelaySlotUPCState< MachInst >::nupc(), GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), MipsISA::r, ThreadContext::setIntReg(), and GenericISA::DelaySlotUPCState< MachInst >::upc().
size()
size_t SparcISA::RemoteGDB::SPARC64GdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 95 of file remote_gdb.hh.
References SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::r, and SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs().
Member Data Documentation
fpr
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::fpr[32]
Definition at line 85 of file remote_gdb.hh.
fprs
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::fprs
Definition at line 90 of file remote_gdb.hh.
fsr
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::fsr
Definition at line 89 of file remote_gdb.hh.
gpr
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::gpr[32]
Definition at line 84 of file remote_gdb.hh.
npc
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::npc
Definition at line 87 of file remote_gdb.hh.
pc
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::pc
Definition at line 86 of file remote_gdb.hh.
r
struct { ... } SparcISA::RemoteGDB::SPARC64GdbRegCache::r
state
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::state
Definition at line 88 of file remote_gdb.hh.
y
uint64_t SparcISA::RemoteGDB::SPARC64GdbRegCache::y
Definition at line 91 of file remote_gdb.hh.
The documentation for this class was generated from the following files:
arch/sparc/remote_gdb.hh
arch/sparc/remote_gdb.cc