gem5: Message Class Reference
Message Class Reference abstract
#include <Message.hh>
Public Member Functions
Message (Tick curTime)
Message (const Message &other)
virtual ~Message ()
virtual MsgPtr clone () const =0
virtual void print (std::ostream &out) const =0
virtual const MessageSizeType & getMessageSize () const
virtual MessageSizeType & getMessageSize ()
virtual bool functionalRead (Packet *pkt)=0
The two functions below are used for reading / writing the message functionally.
virtual bool functionalWrite (Packet *pkt)=0
void updateDelayedTicks (Tick curTime)
Update the delay this message has experienced so far.
Tick getDelayedTicks () const
void setLastEnqueueTime (const Tick &time)
Tick getLastEnqueueTime () const
Tick getTime () const
void setMsgCounter (uint64_t c)
uint64_t getMsgCounter () const
virtual const NetDest & getDestination () const
virtual NetDest & getDestination ()
int getIncomingLink () const
void setIncomingLink (int link)
int getVnet () const
void setVnet (int net)
Private Attributes
const Tick m_time
Tick m_LastEnqueueTime
Tick m_DelayedTicks
uint64_t m_msg_counter
int incoming_link
int vnet
Detailed Description
Definition at line 43 of file Message.hh.
Constructor & Destructor Documentation
Message() [1/2]
Message::Message (Tick curTime) inline
Definition at line 46 of file Message.hh.
Message() [2/2]
Message::Message (const Message & other) inline
Definition at line 52 of file Message.hh.
~Message()
virtual Message::~Message () inline virtual
Definition at line 59 of file Message.hh.
References clone(), and print().
Member Function Documentation
clone()
virtual MsgPtr Message::clone () const pure virtual
Implemented in RubyRequest.
Referenced by ~Message().
functionalRead()
virtual bool Message::functionalRead (Packet * pkt) pure virtual
The two functions below are used for reading / writing the message functionally.
The methods return true if the address in the packet matches the address / address range in the message. Each message class that can be potentially searched for the address needs to implement these methods.
Implemented in RubyRequest.
Referenced by getMessageSize().
functionalWrite()
virtual bool Message::functionalWrite (Packet * pkt) pure virtual
Implemented in RubyRequest.
Referenced by flit::functionalWrite(), MessageBuffer::functionalWrite(), and getMessageSize().
getDelayedTicks()
Tick Message::getDelayedTicks () const inline
Definition at line 86 of file Message.hh.
References m_DelayedTicks.
getDestination() [1/2]
virtual const NetDest& Message::getDestination () const inline virtual
Definition at line 96 of file Message.hh.
References panic.
Referenced by NetworkInterface::flitisizeMessage(), network_message_to_size(), and PerfectSwitch::operateMessageBuffer().
getDestination() [2/2]
virtual NetDest& Message::getDestination () inline virtual
Definition at line 98 of file Message.hh.
References panic.
getIncomingLink()
int Message::getIncomingLink () const inline
Definition at line 101 of file Message.hh.
References incoming_link.
getLastEnqueueTime()
Tick Message::getLastEnqueueTime () const inline
Definition at line 89 of file Message.hh.
References m_LastEnqueueTime.
Referenced by MessageBuffer::enqueue(), and operator>().
getMessageSize() [1/2]
virtual const MessageSizeType& Message::getMessageSize () const inline virtual
Definition at line 64 of file Message.hh.
References panic.
Referenced by NetworkInterface::flitisizeMessage(), network_message_to_size(), and Throttle::operateVnet().
getMessageSize() [2/2]
virtual MessageSizeType& Message::getMessageSize () inline virtual
Definition at line 66 of file Message.hh.
References functionalRead(), functionalWrite(), and panic.
getMsgCounter()
uint64_t Message::getMsgCounter () const inline
Definition at line 93 of file Message.hh.
References m_msg_counter.
Referenced by operator>().
getTime()
Tick Message::getTime () const inline
Definition at line 91 of file Message.hh.
References m_time.
getVnet()
int Message::getVnet () const inline
Definition at line 103 of file Message.hh.
References vnet.
print()
virtual void Message::print (std::ostream & out) const pure virtual
Implemented in RubyRequest.
Referenced by operator<<(), and ~Message().
setIncomingLink()
void Message::setIncomingLink (int link) inline
Definition at line 102 of file Message.hh.
References incoming_link.
setLastEnqueueTime()
void Message::setLastEnqueueTime (const Tick & time) inline
Definition at line 88 of file Message.hh.
References m_LastEnqueueTime.
Referenced by WireBuffer::enqueue(), and MessageBuffer::enqueue().
setMsgCounter()
void Message::setMsgCounter (uint64_t c) inline
Definition at line 92 of file Message.hh.
References ArmISA::c, and m_msg_counter.
Referenced by MessageBuffer::enqueue().
setVnet()
void Message::setVnet (int net) inline
Definition at line 104 of file Message.hh.
References vnet.
updateDelayedTicks()
void Message::updateDelayedTicks (Tick curTime) inline
Update the delay this message has experienced so far.
Definition at line 80 of file Message.hh.
References m_DelayedTicks, and m_LastEnqueueTime.
Referenced by MessageBuffer::enqueue().
Member Data Documentation
incoming_link
int Message::incoming_link private
Definition at line 113 of file Message.hh.
Referenced by getIncomingLink(), and setIncomingLink().
m_DelayedTicks
Tick Message::m_DelayedTicks private
Definition at line 109 of file Message.hh.
Referenced by getDelayedTicks(), and updateDelayedTicks().
m_LastEnqueueTime
Tick Message::m_LastEnqueueTime private
Definition at line 108 of file Message.hh.
Referenced by getLastEnqueueTime(), setLastEnqueueTime(), and updateDelayedTicks().
m_msg_counter
uint64_t Message::m_msg_counter private
Definition at line 110 of file Message.hh.
Referenced by getMsgCounter(), and setMsgCounter().
m_time
const Tick Message::m_time private
Definition at line 107 of file Message.hh.
Referenced by getTime().
vnet
int Message::vnet private
Definition at line 114 of file Message.hh.
Referenced by getVnet(), and setVnet().
The documentation for this class was generated from the following file:
mem/ruby/slicc_interface/Message.hh