gem5: StorageMap Class Reference
StorageMap Class Reference
#include <hsail_code.hh>
Public Member Functions
StorageMap (StorageMap *outerScope=nullptr)
StorageElement * addSymbol (const Brig::BrigDirectiveVariable *sym, const BrigObject *obj)
StorageElement * findSymbol (Brig::BrigSegment segment, std::string name)
StorageElement * findSymbol (Brig::BrigSegment segment, uint64_t addr)
StorageElement * findSymbol (Brig::BrigSegment segment, const Brig::BrigDirectiveVariable *brigptr)
StorageElement * findSymbol (Brig::BrigSegment8_t segment, std::string name)
int getSize (Brig::BrigSegment segment)
void resetOffset (Brig::BrigSegment segment)
Private Attributes
StorageMap * outerScopeMap
StorageSpace * space [NumSegments]
Detailed Description
Definition at line 265 of file hsail_code.hh.
Constructor & Destructor Documentation
StorageMap()
StorageMap::StorageMap (StorageMap * outerScope = nullptr)
Definition at line 359 of file hsail_code.cc.
References ArmISA::i, NumSegments, and space.
Member Function Documentation
addSymbol()
StorageElement * StorageMap::addSymbol (const Brig::BrigDirectiveVariable * sym, const BrigObject * obj)
Definition at line 367 of file hsail_code.cc.
References StorageSpace::addSymbol(), Brig::BRIG_SEGMENT_FLAT, NumSegments, Brig::BrigDirectiveVariable::segment, and space.
Referenced by HsailCode::init(), and BrigObject::processDirectives().
findSymbol() [1/4]
StorageElement * StorageMap::findSymbol (Brig::BrigSegment segment, std::string name)
Definition at line 404 of file hsail_code.cc.
References StorageSpace::findSymbol(), findSymbol(), outerScopeMap, and space.
Referenced by findSymbol(), HsailCode::findSymbol(), and AddrOperandBase::parseAddr().
findSymbol() [2/4]
StorageElement * StorageMap::findSymbol (Brig::BrigSegment segment, uint64_t addr)
Definition at line 418 of file hsail_code.cc.
References StorageSpace::findSymbol(), findSymbol(), outerScopeMap, ArmISA::sp, and space.
findSymbol() [3/4]
StorageElement * StorageMap::findSymbol (Brig::BrigSegment segment, const Brig::BrigDirectiveVariable * brigptr)
Definition at line 440 of file hsail_code.cc.
References StorageSpace::findSymbol(), findSymbol(), outerScopeMap, ArmISA::sp, and space.
findSymbol() [4/4]
StorageElement* StorageMap::findSymbol (Brig::BrigSegment8_t segment, std::string name) inline
Definition at line 284 of file hsail_code.hh.
getSize()
int StorageMap::getSize (Brig::BrigSegment segment)
Definition at line 378 of file hsail_code.cc.
References Brig::BRIG_SEGMENT_GLOBAL, Brig::BRIG_SEGMENT_GROUP, Brig::BRIG_SEGMENT_READONLY, StorageSpace::getSize(), getSize(), NumSegments, outerScopeMap, and space.
Referenced by getSize(), HsailCode::getSize(), and BrigObject::processDirectives().
resetOffset()
void StorageMap::resetOffset (Brig::BrigSegment segment)
Definition at line 398 of file hsail_code.cc.
References StorageSpace::resetOffset(), and space.
Referenced by HsailCode::init().
Member Data Documentation
outerScopeMap
StorageMap* StorageMap::outerScopeMap private
Definition at line 267 of file hsail_code.hh.
Referenced by findSymbol(), and getSize().
space
StorageSpace* StorageMap::space[NumSegments] private
Definition at line 268 of file hsail_code.hh.
Referenced by addSymbol(), findSymbol(), getSize(), resetOffset(), and StorageMap().
The documentation for this class was generated from the following files:
gpu-compute/hsail_code.hh
gpu-compute/hsail_code.cc