gem5: EtherDump Class Reference
EtherDump Class Reference
#include <etherdump.hh>
Public Types
typedef EtherDumpParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
EtherDump (const Params *p)
void dump (EthPacketPtr &pkt)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
void dumpPacket (EthPacketPtr &packet)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
Private Attributes
std::ostream * stream
const unsigned maxlen
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 47 of file etherdump.hh.
Member Typedef Documentation
Params
typedef EtherDumpParams EtherDump::Params
Definition at line 56 of file etherdump.hh.
Constructor & Destructor Documentation
EtherDump()
EtherDump::EtherDump (const Params * p)
Definition at line 47 of file etherdump.cc.
Referenced by dumpPacket().
Member Function Documentation
dump()
void EtherDump::dump (EthPacketPtr & pkt) inline
Definition at line 59 of file etherdump.hh.
References dumpPacket().
Referenced by EtherTapBase::recvSimulated(), EtherTapBase::retransmit(), EtherTapBase::sendSimulated(), EtherBus::txDone(), and EtherLink::Link::txDone().
dumpPacket()
void EtherDump::dumpPacket (EthPacketPtr & packet) private
Definition at line 94 of file etherdump.cc.
References pcap_pkthdr::caplen, curTick(), EtherDump(), pcap_pkthdr::len, maxlen, pcap_pkthdr::microseconds, SimClock::Int::s, pcap_pkthdr::seconds, stream, ULL, and SimClock::Int::us.
Referenced by dump().
init()
void EtherDump::init () private virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 76 of file etherdump.cc.
References DLT_EN10MB, pcap_file_header::linktype, pcap_file_header::magic, PCAP_VERSION_MAJOR, PCAP_VERSION_MINOR, pcap_file_header::sigfigs, pcap_file_header::snaplen, stream, TCPDUMP_MAGIC, pcap_file_header::thiszone, pcap_file_header::version_major, and pcap_file_header::version_minor.
Member Data Documentation
maxlen
const unsigned EtherDump::maxlen private
Definition at line 51 of file etherdump.hh.
Referenced by dumpPacket().
stream
std::ostream* EtherDump::stream private
Definition at line 50 of file etherdump.hh.
Referenced by dumpPacket(), and init().
The documentation for this class was generated from the following files:
dev/net/etherdump.hh
dev/net/etherdump.cc