gem5: SatCounter Class Reference
SatCounter Class Reference
Implements an n bit saturating counter and provides methods to increment, decrement, and read it.
#include <sat_counter.hh>
Public Member Functions
SatCounter ()=delete
The default constructor should never be used.
SatCounter (unsigned bits, uint8_t initial_val=0)
Constructor for the counter.
SatCounter (const SatCounter &other)
Copy constructor.
SatCounter & operator= (const SatCounter &other)
Copy assignment.
SatCounter (SatCounter &&other)
Move constructor.
SatCounter & operator= (SatCounter &&other)
Move assignment.
void swap (SatCounter &other)
Swap the contents of every member of the class.
SatCounter & operator++ ()
Pre-increment operator.
SatCounter operator++ (int)
Post-increment operator.
SatCounter & operator-- ()
Pre-decrement operator.
SatCounter operator-- (int)
Post-decrement operator.
SatCounter & operator>>= (const int &shift)
Shift-right-assignment.
SatCounter & operator<<= (const int &shift)
Shift-left-assignment.
SatCounter & operator+= (const int &value)
Add-assignment.
SatCounter & operator-= (const int &value)
Subtract-assignment.
operator uint8_t () const
Read the counter's value.
void reset ()
Reset the counter to its initial value.
double calcSaturation () const
Calculate saturation percentile of the current counter's value with regard to its maximum possible value.
bool isSaturated () const
Whether the counter has achieved its maximum value or not.
uint8_t saturate ()
Saturate the counter.
Private Attributes
uint8_t initialVal
uint8_t maxVal
uint8_t counter
Detailed Description
Implements an n bit saturating counter and provides methods to increment, decrement, and read it.
Definition at line 56 of file sat_counter.hh.
Constructor & Destructor Documentation
SatCounter() [1/4]
SatCounter::SatCounter () delete
The default constructor should never be used.
SatCounter() [2/4]
SatCounter::SatCounter (unsigned bits, uint8_t initial_val = 0) inline explicit
Constructor for the counter.
The explicit keyword is used to make sure the user does not assign a number to the counter thinking it will be used as a counter value when it is in fact used as the number of bits.
Parameters
bits How many bits the counter will have.
initial_val Starting value for the counter.
Definition at line 71 of file sat_counter.hh.
References fatal_if, and maxVal.
SatCounter() [3/4]
SatCounter::SatCounter (const SatCounter & other) inline
Copy constructor.
Definition at line 82 of file sat_counter.hh.
SatCounter() [4/4]
SatCounter::SatCounter (SatCounter && other) inline
Move constructor.
Definition at line 98 of file sat_counter.hh.
References counter, initialVal, and maxVal.
Member Function Documentation
calcSaturation()
double SatCounter::calcSaturation () const inline
Calculate saturation percentile of the current counter's value with regard to its maximum possible value.
Returns
A value between 0.0 and 1.0 to indicate which percentile of the maximum value the current value is.
Definition at line 229 of file sat_counter.hh.
References counter, and maxVal.
Referenced by SignaturePathPrefetcher::calculateLookaheadConfidence(), IndirectMemoryPrefetcher::calculatePrefetch(), SignaturePathPrefetcher::calculatePrefetchConfidence(), and TEST().
isSaturated()
bool SatCounter::isSaturated () const inline
Whether the counter has achieved its maximum value or not.
Returns
True if the counter saturated.
Definition at line 236 of file sat_counter.hh.
References counter, and maxVal.
Referenced by SignaturePathPrefetcherV2::increasePatternEntryCounter(), and TEST().
operator uint8_t()
SatCounter::operator uint8_t () const inline
Read the counter's value.
Definition at line 217 of file sat_counter.hh.
References counter.
operator++() [1/2]
SatCounter& SatCounter::operator++ () inline
Pre-increment operator.
Definition at line 135 of file sat_counter.hh.
References counter, and maxVal.
operator++() [2/2]
SatCounter SatCounter::operator++ (int) inline
Post-increment operator.
Definition at line 145 of file sat_counter.hh.
operator+=()
SatCounter& SatCounter::operator+= (const int & value) inline
Add-assignment.
Definition at line 192 of file sat_counter.hh.
References counter, and maxVal.
operator--() [1/2]
SatCounter& SatCounter::operator-- () inline
Pre-decrement operator.
Definition at line 154 of file sat_counter.hh.
References counter.
operator--() [2/2]
SatCounter SatCounter::operator-- (int) inline
Post-decrement operator.
Definition at line 164 of file sat_counter.hh.
operator-=()
SatCounter& SatCounter::operator-= (const int & value) inline
Subtract-assignment.
Definition at line 204 of file sat_counter.hh.
References counter.
operator<<=()
SatCounter& SatCounter::operator<<= (const int & shift) inline
Shift-left-assignment.
Definition at line 181 of file sat_counter.hh.
References counter, maxVal, and ArmISA::shift.
operator=() [1/2]
SatCounter& SatCounter::operator= (const SatCounter & other) inline
Copy assignment.
Definition at line 89 of file sat_counter.hh.
References swap().
operator=() [2/2]
SatCounter& SatCounter::operator= (SatCounter && other) inline
Move assignment.
Definition at line 108 of file sat_counter.hh.
References counter, initialVal, and maxVal.
operator>>=()
SatCounter& SatCounter::operator>>= (const int & shift) inline
Shift-right-assignment.
Definition at line 173 of file sat_counter.hh.
References counter, and ArmISA::shift.
reset()
void SatCounter::reset () inline
Reset the counter to its initial value.
Definition at line 220 of file sat_counter.hh.
References counter, and initialVal.
Referenced by IrregularStreamBufferPrefetcher::addStructuralToPhysicalEntry(), IrregularStreamBufferPrefetcher::calculatePrefetch(), SignaturePathPrefetcher::PatternEntry::getStrideEntry(), IndirectMemoryPrefetcher::PrefetchTableEntry::reset(), SignaturePathPrefetcher::PatternEntry::reset(), TEST(), BRRIPRP::touch(), and IndirectMemoryPrefetcher::trackMissIndex2().
saturate()
uint8_t SatCounter::saturate () inline
Saturate the counter.
Returns
The value added to the counter to reach saturation.
Definition at line 243 of file sat_counter.hh.
References counter, and maxVal.
Referenced by BRRIPRP::reset(), and TEST().
swap()
void SatCounter::swap (SatCounter & other) inline
Swap the contents of every member of the class.
Used for the default copy-assignment created by the compiler.
Parameters
other The other object to swap contents with.
Definition at line 126 of file sat_counter.hh.
References counter, initialVal, and maxVal.
Referenced by operator=().
Member Data Documentation
counter
uint8_t SatCounter::counter private
Definition at line 253 of file sat_counter.hh.
Referenced by calcSaturation(), SignaturePathPrefetcher::PatternEntry::getStrideEntry(), SignaturePathPrefetcherV2::increasePatternEntryCounter(), isSaturated(), operator uint8_t(), operator++(), operator+=(), operator--(), operator-=(), operator<<=(), operator=(), operator>>=(), reset(), SatCounter(), saturate(), and swap().
initialVal
uint8_t SatCounter::initialVal private
Definition at line 251 of file sat_counter.hh.
Referenced by operator=(), reset(), SatCounter(), and swap().
maxVal
uint8_t SatCounter::maxVal private
Definition at line 252 of file sat_counter.hh.
Referenced by calcSaturation(), isSaturated(), operator++(), operator+=(), operator<<=(), operator=(), SatCounter(), saturate(), and swap().
The documentation for this class was generated from the following file:
base/sat_counter.hh