gem5: AbstractCacheEntry Class Reference
AbstractCacheEntry Class Reference abstract
#include <AbstractCacheEntry.hh>
Public Member Functions
AbstractCacheEntry ()
virtual ~AbstractCacheEntry ()=0
AccessPermission getPermission () const
void changePermission (AccessPermission new_perm)
virtual void print (std::ostream &out) const =0
virtual DataBlock & getDataBlk ()
virtual int & getNumValidBlocks ()
void setLocked (int context)
void clearLocked ()
bool isLocked (int context) const
Tick getLastAccess ()
void setLastAccess (Tick tick)
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
int validBlocks
Addr m_Address
int m_locked
AccessPermission m_Permission
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Private Attributes
Tick m_last_touch_tick
Additional Inherited Members
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
Definition at line 45 of file AbstractCacheEntry.hh.
Constructor & Destructor Documentation
AbstractCacheEntry()
AbstractCacheEntry::AbstractCacheEntry ()
Definition at line 34 of file AbstractCacheEntry.cc.
References m_Address, m_last_touch_tick, m_locked, and m_Permission.
~AbstractCacheEntry()
AbstractCacheEntry::~AbstractCacheEntry () pure virtual
Definition at line 42 of file AbstractCacheEntry.cc.
Member Function Documentation
changePermission()
void AbstractCacheEntry::changePermission (AccessPermission new_perm)
Definition at line 54 of file AbstractCacheEntry.cc.
References m_locked, and m_Permission.
Referenced by DirectoryMemory::allocate().
clearLocked()
void AbstractCacheEntry::clearLocked ()
Definition at line 71 of file AbstractCacheEntry.cc.
References DPRINTF, m_Address, and m_locked.
Referenced by getNumValidBlocks(), Sequencer::handleLlsc(), and Sequencer::invalidateSC().
getDataBlk()
virtual DataBlock& AbstractCacheEntry::getDataBlk () inline virtual
Definition at line 63 of file AbstractCacheEntry.hh.
References panic.
Referenced by CacheMemory::testCacheAccess(), and CacheMemory::tryCacheAccess().
getLastAccess()
Tick AbstractCacheEntry::getLastAccess () inline
Definition at line 88 of file AbstractCacheEntry.hh.
References m_last_touch_tick.
getNumValidBlocks()
virtual int& AbstractCacheEntry::getNumValidBlocks () inline virtual
Definition at line 67 of file AbstractCacheEntry.hh.
References clearLocked(), isLocked(), setLocked(), and validBlocks.
getPermission()
AccessPermission AbstractCacheEntry::getPermission () const
Definition at line 48 of file AbstractCacheEntry.cc.
References m_Permission.
isLocked()
bool AbstractCacheEntry::isLocked (int context) const
Definition at line 78 of file AbstractCacheEntry.cc.
References DPRINTF, m_Address, and m_locked.
Referenced by getNumValidBlocks(), Sequencer::handleLlsc(), and Sequencer::invalidateSC().
print()
virtual void AbstractCacheEntry::print (std::ostream & out) const pure virtual
Referenced by operator<<().
setLastAccess()
void AbstractCacheEntry::setLastAccess (Tick tick) inline
Definition at line 91 of file AbstractCacheEntry.hh.
setLocked()
void AbstractCacheEntry::setLocked (int context)
Definition at line 64 of file AbstractCacheEntry.cc.
References DPRINTF, m_Address, and m_locked.
Referenced by getNumValidBlocks(), and Sequencer::handleLlsc().
Member Data Documentation
m_Address
Addr AbstractCacheEntry::m_Address
Definition at line 79 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), CacheMemory::allocate(), CacheMemory::cacheAvail(), clearLocked(), CacheMemory::getAddressAtIdx(), isLocked(), and setLocked().
m_last_touch_tick
Tick AbstractCacheEntry::m_last_touch_tick private
Definition at line 49 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), and getLastAccess().
m_locked
int AbstractCacheEntry::m_locked
Definition at line 82 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), changePermission(), clearLocked(), isLocked(), and setLocked().
m_Permission
AccessPermission AbstractCacheEntry::m_Permission
Definition at line 84 of file AbstractCacheEntry.hh.
Referenced by AbstractCacheEntry(), CacheMemory::cacheAvail(), changePermission(), CacheMemory::getAddressAtIdx(), getPermission(), and CacheMemory::tryCacheAccess().
validBlocks
int AbstractCacheEntry::validBlocks
Definition at line 66 of file AbstractCacheEntry.hh.
Referenced by getNumValidBlocks().
The documentation for this class was generated from the following files:
mem/ruby/slicc_interface/AbstractCacheEntry.hh
mem/ruby/slicc_interface/AbstractCacheEntry.cc