gem5: ArchTimer Class Reference
ArchTimer Class Reference
Per-CPU architected timer.
#include <generic_timer.hh>
Public Member Functions
ArchTimer (const std::string &name, SimObject &parent, SystemCounter &sysctr, ArmInterruptPin *interrupt)
std::string name () const
Returns the timer name.
uint64_t compareValue () const
Returns the CompareValue view of the timer.
void setCompareValue (uint64_t val)
Sets the CompareValue view of the timer.
uint32_t timerValue () const
Returns the TimerValue view of the timer.
void setTimerValue (uint32_t val)
Sets the TimerValue view of the timer.
uint32_t control () const
Sets the control register.
void setControl (uint32_t val)
uint64_t offset () const
void setOffset (uint64_t val)
uint64_t value () const
Returns the value of the counter which this timer relies on.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Protected Member Functions
BitUnion32 (ArchTimerCtrl) Bitfield< 0 > enable
Control register.
void updateCounter ()
Timer settings or the offset has changed, re-evaluate trigger condition and raise interrupt if necessary.
void counterLimitReached ()
Called when the upcounter reaches the programmed value.
virtual bool scheduleEvents ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
Bitfield< 1 > imask
Bitfield< 2 > istatus
EndBitUnion(ArchTimerCtrl) const std SimObject & _parent
Name of this timer.
SystemCounter & _systemCounter
ArmInterruptPin *const _interrupt
ArchTimerCtrl _control
Value of the control register ({CNTP/CNTHP/CNTV}_CTL).
uint64_t _counterLimit
Programmed limit value for the upcounter ({CNTP/CNTHP/CNTV}_CVAL).
uint64_t _offset
Offset relative to the physical timer (CNTVOFF)
EventFunctionWrapper _counterLimitReachedEvent
Private Member Functions
ArchTimer (const ArchTimer &t)
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Per-CPU architected timer.
Definition at line 112 of file generic_timer.hh.
Constructor & Destructor Documentation
ArchTimer() [1/2]
ArchTimer::ArchTimer (const std::string & name, SimObject & parent, SystemCounter & sysctr, ArmInterruptPin * interrupt)
Definition at line 94 of file generic_timer.cc.
References counterLimitReached(), and name().
ArchTimer() [2/2]
ArchTimer::ArchTimer (const ArchTimer & t) private
Member Function Documentation
BitUnion32()
ArchTimer::BitUnion32 (ArchTimerCtrl) protected
Control register.
compareValue()
uint64_t ArchTimer::compareValue () const inline
Returns the CompareValue view of the timer.
Definition at line 161 of file generic_timer.hh.
References X86ISA::val.
Referenced by GenericTimer::readMiscReg(), GenericTimerMem::timerRead(), and GenericTimerMem::timerWrite().
control()
uint32_t ArchTimer::control () const inline
Sets the control register.
Definition at line 171 of file generic_timer.hh.
Referenced by GenericTimer::readMiscReg(), and GenericTimerMem::timerRead().
counterLimitReached()
void ArchTimer::counterLimitReached () protected
Called when the upcounter reaches the programmed value.
Definition at line 106 of file generic_timer.cc.
References _control, _interrupt, DPRINTF, ArmInterruptPin::raise(), and scheduleEvents().
Referenced by ArchTimer(), and updateCounter().
drain()
DrainState ArchTimer::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 208 of file generic_timer.cc.
References _counterLimitReachedEvent, _parent, EventManager::deschedule(), Drained, and Event::scheduled().
drainResume()
void ArchTimer::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 217 of file generic_timer.cc.
References updateCounter().
name()
std::string ArchTimer::name () const inline
Returns the timer name.
Definition at line 158 of file generic_timer.hh.
Referenced by ArchTimer().
offset()
uint64_t ArchTimer::offset () const inline
Definition at line 174 of file generic_timer.hh.
References SystemCounter::serialize(), ArmISA::t, SystemCounter::unserialize(), and SystemCounter::value().
Referenced by GenericTimerMem::ctrlRead(), GenericTimerMem::ctrlWrite(), GenericTimer::readMiscReg(), and GenericTimerMem::timerRead().
scheduleEvents()
virtual bool ArchTimer::scheduleEvents () inline protected virtual
Reimplemented in ArchTimerKvm.
Definition at line 149 of file generic_timer.hh.
References name().
Referenced by counterLimitReached(), and updateCounter().
serialize()
void ArchTimer::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 186 of file generic_timer.cc.
References _control, _counterLimit, _offset, paramOut(), and SERIALIZE_SCALAR.
setCompareValue()
void ArchTimer::setCompareValue (uint64_t val)
Sets the CompareValue view of the timer.
Definition at line 142 of file generic_timer.cc.
References _counterLimit, updateCounter(), and X86ISA::val.
Referenced by GenericTimer::setMiscReg(), setTimerValue(), and GenericTimerMem::timerWrite().
setControl()
void ArchTimer::setControl (uint32_t val)
Definition at line 155 of file generic_timer.cc.
References _control, _counterLimit, DPRINTF, X86ISA::val, and value().
Referenced by GenericTimer::setMiscReg(), and GenericTimerMem::timerWrite().
setOffset()
void ArchTimer::setOffset (uint64_t val)
Definition at line 173 of file generic_timer.cc.
References _offset, updateCounter(), and X86ISA::val.
Referenced by GenericTimerMem::ctrlWrite(), and GenericTimer::setMiscReg().
setTimerValue()
void ArchTimer::setTimerValue (uint32_t val)
Sets the TimerValue view of the timer.
Definition at line 149 of file generic_timer.cc.
References setCompareValue(), and value().
Referenced by GenericTimer::setMiscReg(), and GenericTimerMem::timerWrite().
timerValue()
uint32_t ArchTimer::timerValue () const inline
Returns the TimerValue view of the timer.
Definition at line 166 of file generic_timer.hh.
References SystemCounter::value().
Referenced by GenericTimer::readMiscReg(), and GenericTimerMem::timerRead().
unserialize()
void ArchTimer::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 194 of file generic_timer.cc.
References _control, _offset, paramIn(), and UNSERIALIZE_OPT_SCALAR.
updateCounter()
void ArchTimer::updateCounter () protected
Timer settings or the offset has changed, re-evaluate trigger condition and raise interrupt if necessary.
Definition at line 125 of file generic_timer.cc.
References _control, _counterLimit, _counterLimitReachedEvent, _parent, _systemCounter, counterLimitReached(), curTick(), EventManager::deschedule(), SystemCounter::period(), EventManager::schedule(), Event::scheduled(), scheduleEvents(), and value().
Referenced by drainResume(), setCompareValue(), and setOffset().
value()
uint64_t ArchTimer::value () const
Returns the value of the counter which this timer relies on.
Definition at line 180 of file generic_timer.cc.
References _offset, _systemCounter, and SystemCounter::value().
Referenced by GenericTimer::readMiscReg(), setControl(), setTimerValue(), GenericTimerMem::timerRead(), and updateCounter().
Member Data Documentation
_control
ArchTimerCtrl ArchTimer::_control protected
Value of the control register ({CNTP/CNTHP/CNTV}_CTL).
Definition at line 133 of file generic_timer.hh.
Referenced by counterLimitReached(), serialize(), setControl(), unserialize(), and updateCounter().
_counterLimit
uint64_t ArchTimer::_counterLimit protected
Programmed limit value for the upcounter ({CNTP/CNTHP/CNTV}_CVAL).
Definition at line 135 of file generic_timer.hh.
Referenced by serialize(), setCompareValue(), setControl(), and updateCounter().
_counterLimitReachedEvent
EventFunctionWrapper ArchTimer::_counterLimitReachedEvent protected
Definition at line 147 of file generic_timer.hh.
Referenced by drain(), and updateCounter().
_interrupt
ArmInterruptPin* const ArchTimer::_interrupt protected
Definition at line 130 of file generic_timer.hh.
Referenced by counterLimitReached().
_offset
uint64_t ArchTimer::_offset protected
Offset relative to the physical timer (CNTVOFF)
Definition at line 137 of file generic_timer.hh.
Referenced by serialize(), setOffset(), unserialize(), and value().
_parent
EndBitUnion (ArchTimerCtrl) const std SimObject& ArchTimer::_parent protected
Name of this timer.
Pointer to parent class.
Definition at line 120 of file generic_timer.hh.
Referenced by drain(), and updateCounter().
_systemCounter
SystemCounter& ArchTimer::_systemCounter protected
Definition at line 128 of file generic_timer.hh.
Referenced by updateCounter(), and value().
imask
Bitfield<1> ArchTimer::imask protected
Definition at line 118 of file generic_timer.hh.
istatus
Bitfield<2> ArchTimer::istatus protected
Definition at line 119 of file generic_timer.hh.
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc