gem5: sc_core::sc_event_and_list Class Reference
sc_core::sc_event_and_list Class Reference
#include <sc_event.hh>
Public Member Functions
sc_event_and_list ()
sc_event_and_list (const sc_event_and_list &)
sc_event_and_list (const sc_event &)
sc_event_and_list & operator= (const sc_event_and_list &)
~sc_event_and_list ()
int size () const
void swap (sc_event_and_list &)
sc_event_and_list & operator&= (const sc_event &)
sc_event_and_list & operator&= (const sc_event_and_list &)
sc_event_and_expr operator& (const sc_event &) const
sc_event_and_expr operator& (const sc_event_and_list &) const
Private Member Functions
sc_event_and_list (bool auto_delete)
void insert (sc_event const &e)
void insert (sc_event_and_list const &eal)
Private Attributes
std::set< const sc_event * > events
bool autoDelete
unsigned busy
Friends
class sc_event_and_expr
class sc_gem5::DynamicSensitivityEventAndList
Detailed Description
Definition at line 63 of file sc_event.hh.
Constructor & Destructor Documentation
sc_event_and_list() [1/4]
sc_core::sc_event_and_list::sc_event_and_list ()
Definition at line 42 of file sc_event.cc.
sc_event_and_list() [2/4]
sc_core::sc_event_and_list::sc_event_and_list (const sc_event_and_list & eal)
Definition at line 44 of file sc_event.cc.
sc_event_and_list() [3/4]
sc_core::sc_event_and_list::sc_event_and_list (const sc_event & e)
Definition at line 48 of file sc_event.cc.
References insert().
~sc_event_and_list()
sc_core::sc_event_and_list::~sc_event_and_list ()
Definition at line 57 of file sc_event.cc.
sc_event_and_list() [4/4]
sc_core::sc_event_and_list::sc_event_and_list (bool auto_delete) explicit private
Definition at line 53 of file sc_event.cc.
Member Function Documentation
insert() [1/2]
void sc_core::sc_event_and_list::insert (sc_event const & e) private
Definition at line 111 of file sc_event.cc.
References events.
Referenced by sc_core::sc_event_and_expr::insert(), sc_event_and_list(), and swap().
insert() [2/2]
void sc_core::sc_event_and_list::insert (sc_event_and_list const & eal) private
Definition at line 117 of file sc_event.cc.
References events.
operator&() [1/2]
sc_event_and_expr sc_core::sc_event_and_list::operator & (const sc_event &) const
Referenced by swap().
operator&() [2/2]
sc_event_and_expr sc_core::sc_event_and_list::operator & (const sc_event_and_list &) const
operator&=() [1/2]
sc_event_and_list& sc_core::sc_event_and_list::operator &= (const sc_event &)
Referenced by swap().
operator&=() [2/2]
sc_event_and_list& sc_core::sc_event_and_list::operator &= (const sc_event_and_list &)
operator=()
sc_event_and_list & sc_core::sc_event_and_list::operator= (const sc_event_and_list & eal)
Definition at line 60 of file sc_event.cc.
References events.
size()
int sc_core::sc_event_and_list::size () const
Definition at line 67 of file sc_event.cc.
References events.
swap()
void sc_core::sc_event_and_list::swap (sc_event_and_list & eal)
Definition at line 73 of file sc_event.cc.
References ArmISA::e, events, insert(), sc_core::sc_event_and_expr::insert(), operator&(), and operator&=().
Friends And Related Function Documentation
sc_event_and_expr
friend class sc_event_and_expr friend
Definition at line 82 of file sc_event.hh.
sc_gem5::DynamicSensitivityEventAndList
friend class sc_gem5::DynamicSensitivityEventAndList friend
Definition at line 83 of file sc_event.hh.
Member Data Documentation
autoDelete
bool sc_core::sc_event_and_list::autoDelete private
Definition at line 91 of file sc_event.hh.
busy
unsigned sc_core::sc_event_and_list::busy mutable private
Definition at line 92 of file sc_event.hh.
events
std::set<const sc_event *> sc_core::sc_event_and_list::events private
Definition at line 90 of file sc_event.hh.
Referenced by insert(), operator=(), size(), and swap().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_event.hh
systemc/core/sc_event.cc