gem5: LSQ< Impl >::SingleDataRequest Class Reference
LSQ< Impl >::SingleDataRequest Class Reference
#include <lsq.hh>
Public Member Functions
SingleDataRequest (LSQUnit *port, const DynInstPtr &inst, bool isLoad, const Addr &addr, const uint32_t &size, const Request::Flags &flags_, PacketDataPtr data=nullptr, uint64_t *res=nullptr, AtomicOpFunctorPtr amo_op=nullptr)
virtual ~SingleDataRequest ()
virtual void initiateTranslation ()
virtual void finish (const Fault &fault, const RequestPtr &req, ThreadContext *tc, BaseTLB::Mode mode)
virtual bool recvTimingResp (PacketPtr pkt)
virtual void sendPacketToCache ()
virtual void buildPackets ()
virtual void handleIprWrite (ThreadContext *thread, PacketPtr pkt)
Memory mapped IPR accesses.
virtual Cycles handleIprRead (ThreadContext *thread, PacketPtr pkt)
virtual bool isCacheBlockHit (Addr blockAddr, Addr cacheBlockMask)
Test if the request accesses a particular cache line.
Public Member Functions inherited from LSQ< Impl >::LSQRequest
void packetSent ()
Update the status to reflect that a packet was sent.
void packetNotSent ()
Update the status to reflect that a packet was not sent.
void sendFragmentToTranslation (int i)
bool isComplete ()
bool isInTranslation ()
bool isTranslationComplete ()
bool isTranslationBlocked ()
bool isSent ()
bool isPartialFault ()
bool isMemAccessRequired ()
void setStateToFault ()
void freeLSQEntry ()
The LSQ entry is cleared.
void discard ()
The request is discarded (e.g.
void packetReplied ()
void writebackScheduled ()
void writebackDone ()
void squashTranslation ()
void complete ()
void setContext (const ContextID &context_id)
Convenience getters/setters.
const DynInstPtr & instruction ()
void setVirt (int asid, Addr vaddr, unsigned size, Request::Flags flags_, MasterID mid, Addr pc)
Set up virtual request.
void taskId (const uint32_t &v)
uint32_t taskId () const
RequestPtr request (int idx=0)
const RequestPtr request (int idx=0) const
Addr getVaddr (int idx=0) const
PacketPtr packet (int idx=0)
virtual PacketPtr mainPacket ()
virtual RequestPtr mainRequest ()
void senderState (LSQSenderState *st)
const LSQSenderState * senderState () const
void discardSenderState ()
Mark senderState as discarded.
bool isAnyOutstandingRequest ()
Test if there is any in-flight translation or mem access request.
bool isSplit () const
Public Member Functions inherited from BaseTLB::Translation
virtual ~Translation ()
Protected Types
using Flag = typename LSQRequest::Flag
using State = typename LSQRequest::State
Protected Types inherited from LSQ< Impl >::LSQRequest
enum Flag : FlagsStorage {
IsLoad = 0x00000001, WbStore = 0x00000002, Delayed = 0x00000004, IsSplit = 0x00000008,
TranslationStarted = 0x00000010, TranslationFinished = 0x00000020, Sent = 0x00000040, Retry = 0x00000080,
Complete = 0x00000100, TranslationSquashed = 0x00000200, Discarded = 0x00000400, LSQEntryFreed = 0x00000800,
WritebackScheduled = 0x00001000, WritebackDone = 0x00002000, IsAtomic = 0x00004000
}
enum State {
State::NotIssued, State::Translation, State::Request, State::Fault,
State::PartialFault
}
typedef uint32_t FlagsStorage
typedef ::Flags< FlagsStorage > FlagsType
Additional Inherited Members
Public Attributes inherited from LSQ< Impl >::LSQRequest
LSQUnit & _port
const DynInstPtr _inst
uint32_t _taskId
PacketDataPtr _data
std::vector< PacketPtr > _packets
std::vector< RequestPtr > _requests
std::vector< Fault > _fault
uint64_t * _res
const Addr _addr
const uint32_t _size
const Request::Flags _flags
std::vector< bool > _byteEnable
uint32_t _numOutstandingPackets
AtomicOpFunctorPtr _amo_op
Protected Member Functions inherited from LSQ< Impl >::LSQRequest
void setState (const State &newState)
void markDelayed () override
Signal that the translation has been delayed due to a hw page table walk.
bool isDelayed ()
LSQUnit * lsqUnit ()
LSQRequest (LSQUnit *port, const DynInstPtr &inst, bool isLoad)
LSQRequest (LSQUnit *port, const DynInstPtr &inst, bool isLoad, const Addr &addr, const uint32_t &size, const Request::Flags &flags_, PacketDataPtr data=nullptr, uint64_t *res=nullptr, AtomicOpFunctorPtr amo_op=nullptr)
bool isLoad () const
bool isAtomic () const
void install ()
Install the request in the LQ/SQ.
virtual bool squashed () const override
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
bool isReleased ()
Test if the LSQRequest has been released, i.e.
void release (Flag reason)
Release the LSQRequest.
void addRequest (Addr addr, unsigned size, const std::vector< bool > &byteEnable)
Helper function used to add a (sub)request, given its address addr, size size and byte-enable mask byteEnable.
virtual ~LSQRequest ()
Destructor.
Protected Attributes inherited from LSQ< Impl >::LSQRequest
FlagsType flags
State _state
LSQSenderState * _senderState
uint32_t numTranslatedFragments
uint32_t numInTranslationFragments
uint32_t _entryIdx
LQ/SQ entry idx.
Detailed Description
template<class Impl>
class LSQ< Impl >::SingleDataRequest
Definition at line 694 of file lsq.hh.
Member Typedef Documentation
Flag
template<class Impl> using LSQ< Impl >::SingleDataRequest::Flag = typename LSQRequest::Flag protected
Definition at line 699 of file lsq.hh.
State
template<class Impl> using LSQ< Impl >::SingleDataRequest::State = typename LSQRequest::State protected
Definition at line 700 of file lsq.hh.
Constructor & Destructor Documentation
SingleDataRequest()
template<class Impl> LSQ< Impl >::SingleDataRequest::SingleDataRequest (LSQUnit * port, const DynInstPtr & inst, bool isLoad, const Addr & addr, const uint32_t & size, const Request::Flags & flags_, PacketDataPtr data = nullptr, uint64_t * res = nullptr, AtomicOpFunctorPtr amo_op = nullptr) inline
Definition at line 726 of file lsq.hh.
~SingleDataRequest()
template<class Impl> virtual LSQ< Impl >::SingleDataRequest::~SingleDataRequest () inline virtual
Definition at line 735 of file lsq.hh.
References GenericISA::handleIprRead(), GenericISA::handleIprWrite(), ArmISA::mode, LSQ< Impl >::recvTimingResp(), and LSQ< Impl >::thread.
Member Function Documentation
buildPackets()
template<class Impl > void LSQ< Impl >::SingleDataRequest::buildPackets () virtual
Implements LSQ< Impl >::LSQRequest.
Definition at line 1027 of file lsq_impl.hh.
References Packet::createRead(), and Packet::createWrite().
finish()
template<class Impl > void LSQ< Impl >::SingleDataRequest::finish (const Fault & fault, const RequestPtr & req, ThreadContext * tc, BaseTLB::Mode mode) virtual
Implements BaseTLB::Translation.
Definition at line 773 of file lsq_impl.hh.
References LSQ< Impl >::LSQRequest::_inst, and NoFault.
handleIprRead()
template<class Impl > Cycles LSQ< Impl >::SingleDataRequest::handleIprRead (ThreadContext * thread, PacketPtr pkt) virtual
Implements LSQ< Impl >::LSQRequest.
Definition at line 1122 of file lsq_impl.hh.
References GenericISA::handleIprRead().
handleIprWrite()
template<class Impl > void LSQ< Impl >::SingleDataRequest::handleIprWrite (ThreadContext * thread, PacketPtr pkt) virtual
Memory mapped IPR accesses.
Implements LSQ< Impl >::LSQRequest.
Definition at line 1099 of file lsq_impl.hh.
References GenericISA::handleIprWrite().
initiateTranslation()
template<class Impl > void LSQ< Impl >::SingleDataRequest::initiateTranslation () virtual
Implements LSQ< Impl >::LSQRequest.
Definition at line 855 of file lsq_impl.hh.
isCacheBlockHit()
template<class Impl > bool LSQ< Impl >::SingleDataRequest::isCacheBlockHit (Addr blockAddr, Addr cacheBlockMask) virtual
Test if the request accesses a particular cache line.
Implements LSQ< Impl >::LSQRequest.
Definition at line 1150 of file lsq_impl.hh.
References LSQ< Impl >::LSQRequest::_requests.
recvTimingResp()
template<class Impl > bool LSQ< Impl >::SingleDataRequest::recvTimingResp (PacketPtr pkt) virtual
Implements LSQ< Impl >::LSQRequest.
Definition at line 986 of file lsq_impl.hh.
References LSQ< Impl >::LSQSenderState::outstanding, and Packet::senderState.
sendPacketToCache()
template<class Impl > void LSQ< Impl >::SingleDataRequest::sendPacketToCache () virtual
Implements LSQ< Impl >::LSQRequest.
Definition at line 1078 of file lsq_impl.hh.
The documentation for this class was generated from the following files:
cpu/o3/lsq.hh
cpu/o3/lsq_impl.hh