gem5: GPUDynInst Class Reference
GPUDynInst Class Reference
#include <gpu_dyn_inst.hh>
Public Types
typedef std::unordered_map< Addr, std::vector< int > > StatusVector
Public Member Functions
GPUDynInst (ComputeUnit *_cu, Wavefront *_wf, GPUStaticInst *static_inst, uint64_t instSeqNum)
~GPUDynInst ()
void execute (GPUDynInstPtr gpuDynInst)
int numSrcRegOperands ()
int numDstRegOperands ()
int getNumOperands ()
bool isVectorRegister (int operandIdx)
bool isScalarRegister (int operandIdx)
bool isCondRegister (int operandIdx)
int getRegisterIndex (int operandIdx, GPUDynInstPtr gpuDynInst)
int getOperandSize (int operandIdx)
bool isDstOperand (int operandIdx)
bool isSrcOperand (int operandIdx)
const std::string & disassemble () const
uint64_t seqNum () const
Enums::StorageClassType executedAs ()
void initiateAcc (GPUDynInstPtr gpuDynInst)
void completeAcc (GPUDynInstPtr gpuDynInst)
void updateStats ()
GPUStaticInst * staticInstruction ()
bool isALU () const
accessor methods for the attributes of the underlying GPU static instruction
bool isBranch () const
bool isNop () const
bool isReturn () const
bool isUnconditionalJump () const
bool isSpecialOp () const
bool isWaitcnt () const
bool isBarrier () const
bool isMemFence () const
bool isMemRef () const
bool isFlat () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isAtomicNoRet () const
bool isAtomicRet () const
bool isScalar () const
bool readsSCC () const
bool writesSCC () const
bool readsVCC () const
bool writesVCC () const
bool isAtomicAnd () const
bool isAtomicOr () const
bool isAtomicXor () const
bool isAtomicCAS () const
bool isAtomicExch () const
bool isAtomicAdd () const
bool isAtomicSub () const
bool isAtomicInc () const
bool isAtomicDec () const
bool isAtomicMax () const
bool isAtomicMin () const
bool isArgLoad () const
bool isGlobalMem () const
bool isLocalMem () const
bool isArgSeg () const
bool isGlobalSeg () const
bool isGroupSeg () const
bool isKernArgSeg () const
bool isPrivateSeg () const
bool isReadOnlySeg () const
bool isSpillSeg () const
bool isWorkitemScope () const
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isNoScope () const
bool isRelaxedOrder () const
bool isAcquire () const
bool isRelease () const
bool isAcquireRelease () const
bool isNoOrder () const
bool isGloballyCoherent () const
bool isSystemCoherent () const
template<typename c0 >
AtomicOpFunctor * makeAtomicOpFunctor (c0 *reg0, c0 *reg1)
void setRequestFlags (RequestPtr req, bool setMemOrder=true)
Public Member Functions inherited from GPUExecContext
GPUExecContext (ComputeUnit *_cu, Wavefront *_wf)
Wavefront * wavefront ()
ComputeUnit * computeUnit ()
RegVal readMiscReg (int opIdx) const
void writeMiscReg (int opIdx, RegVal operandVal)
Public Attributes
std::vector< Addr > addr
Addr pAddr
uint8_t * d_data
uint8_t * a_data
uint8_t * x_data
VectorMask exec_mask
Enums::MemType m_type
int equiv
vgpr_type v_type
int n_reg
int dst_reg
int dst_reg_vec [4]
int simdId
int wfDynId
int kern_id
int cu_id
int wfSlotId
int pipeId
Tick time
WaitClass latency
uint32_t bc [4]
uint8_t * rom
int sz_rom
std::function< void(GPUStaticInst *, GPUDynInstPtr)> execContinuation
bool useContinuation
StatusVector memStatusVector
VectorMask statusBitVector
std::vector< int > statusVector
std::vector< int > tlbHitLevel
Private Attributes
GPUStaticInst * _staticInst
uint64_t _seqNum
Additional Inherited Members
Protected Attributes inherited from GPUExecContext
ComputeUnit * cu
Wavefront * wf
TheGpuISA::GPUISA * gpuISA
Detailed Description
Definition at line 197 of file gpu_dyn_inst.hh.
Member Typedef Documentation
StatusVector
typedef std::unordered_map<Addr, std::vector<int> > GPUDynInst::StatusVector
Definition at line 457 of file gpu_dyn_inst.hh.
Constructor & Destructor Documentation
GPUDynInst()
GPUDynInst::GPUDynInst (ComputeUnit * _cu, Wavefront * _wf, GPUStaticInst * static_inst, uint64_t instSeqNum)
Definition at line 43 of file gpu_dyn_inst.cc.
References a_data, GPUExecContext::computeUnit(), d_data, ArmISA::i, tlbHitLevel, ComputeUnit::wfSize(), and x_data.
~GPUDynInst()
GPUDynInst::~GPUDynInst ()
Definition at line 62 of file gpu_dyn_inst.cc.
References a_data, d_data, and x_data.
Member Function Documentation
completeAcc()
void GPUDynInst::completeAcc (GPUDynInstPtr gpuDynInst)
Definition at line 165 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::completeAcc().
disassemble()
const std::string & GPUDynInst::disassemble () const
Definition at line 136 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::disassemble().
execute()
void GPUDynInst::execute (GPUDynInstPtr gpuDynInst)
Definition at line 70 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::execute().
executedAs()
Enums::StorageClassType GPUDynInst::executedAs ()
Definition at line 148 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::executed_as.
getNumOperands()
int GPUDynInst::getNumOperands ()
Definition at line 88 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::getNumOperands().
getOperandSize()
int GPUDynInst::getOperandSize (int operandIdx)
Definition at line 118 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::getOperandSize().
getRegisterIndex()
int GPUDynInst::getRegisterIndex (int operandIdx, GPUDynInstPtr gpuDynInst)
Definition at line 112 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::getRegisterIndex().
initiateAcc()
void GPUDynInst::initiateAcc (GPUDynInstPtr gpuDynInst)
Definition at line 155 of file gpu_dyn_inst.cc.
References _staticInst, GPUExecContext::cu, ComputeUnit::cu_id, DPRINTF, exec_mask, GPUStaticInst::initiateAcc(), simdId, time, and wfSlotId.
isAcquire()
bool GPUDynInst::isAcquire () const
Definition at line 468 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAcquire().
isAcquireRelease()
bool GPUDynInst::isAcquireRelease () const
Definition at line 480 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAcquireRelease().
isALU()
bool GPUDynInst::isALU () const
accessor methods for the attributes of the underlying GPU static instruction
Definition at line 175 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isALU().
isArgLoad()
bool GPUDynInst::isArgLoad () const
Definition at line 366 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isArgLoad().
isArgSeg()
bool GPUDynInst::isArgSeg () const
Definition at line 384 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isArgSeg().
isAtomic()
bool GPUDynInst::isAtomic () const
Definition at line 253 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomic().
isAtomicAdd()
bool GPUDynInst::isAtomicAdd () const
Definition at line 330 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicAdd().
isAtomicAnd()
bool GPUDynInst::isAtomicAnd () const
Definition at line 301 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicAnd().
isAtomicCAS()
bool GPUDynInst::isAtomicCAS () const
Definition at line 319 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicCAS().
isAtomicDec()
bool GPUDynInst::isAtomicDec () const
Definition at line 348 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicDec().
isAtomicExch()
bool GPUDynInst::isAtomicExch () const
Definition at line 324 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicExch().
isAtomicInc()
bool GPUDynInst::isAtomicInc () const
Definition at line 342 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicInc().
isAtomicMax()
bool GPUDynInst::isAtomicMax () const
Definition at line 354 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicMax().
isAtomicMin()
bool GPUDynInst::isAtomicMin () const
Definition at line 360 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicMin().
isAtomicNoRet()
bool GPUDynInst::isAtomicNoRet () const
Definition at line 259 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicNoRet().
isAtomicOr()
bool GPUDynInst::isAtomicOr () const
Definition at line 307 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicOr().
isAtomicRet()
bool GPUDynInst::isAtomicRet () const
Definition at line 265 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicRet().
isAtomicSub()
bool GPUDynInst::isAtomicSub () const
Definition at line 336 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicSub().
isAtomicXor()
bool GPUDynInst::isAtomicXor () const
Definition at line 313 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isAtomicXor().
isBarrier()
bool GPUDynInst::isBarrier () const
Definition at line 217 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isBarrier().
isBranch()
bool GPUDynInst::isBranch () const
Definition at line 181 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isBranch().
isCondRegister()
bool GPUDynInst::isCondRegister (int operandIdx)
Definition at line 106 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isCondRegister().
isDeviceScope()
bool GPUDynInst::isDeviceScope () const
Definition at line 444 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isDeviceScope().
isDstOperand()
bool GPUDynInst::isDstOperand (int operandIdx)
Definition at line 124 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isDstOperand().
isFlat()
bool GPUDynInst::isFlat () const
Definition at line 235 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isFlat().
isGloballyCoherent()
bool GPUDynInst::isGloballyCoherent () const
Definition at line 492 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isGloballyCoherent().
isGlobalMem()
bool GPUDynInst::isGlobalMem () const
Definition at line 372 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isGlobalMem().
isGlobalSeg()
bool GPUDynInst::isGlobalSeg () const
Definition at line 390 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isGlobalSeg().
isGroupSeg()
bool GPUDynInst::isGroupSeg () const
Definition at line 396 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isGroupSeg().
isKernArgSeg()
bool GPUDynInst::isKernArgSeg () const
Definition at line 402 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isKernArgSeg().
isLoad()
bool GPUDynInst::isLoad () const
Definition at line 241 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isLoad().
isLocalMem()
bool GPUDynInst::isLocalMem () const
Definition at line 378 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isLocalMem().
isMemFence()
bool GPUDynInst::isMemFence () const
Definition at line 223 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isMemFence().
isMemRef()
bool GPUDynInst::isMemRef () const
Definition at line 229 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isMemRef().
isNoOrder()
bool GPUDynInst::isNoOrder () const
Definition at line 486 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isNoOrder().
isNop()
bool GPUDynInst::isNop () const
Definition at line 187 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isNop().
isNoScope()
bool GPUDynInst::isNoScope () const
Definition at line 456 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isNoScope().
isPrivateSeg()
bool GPUDynInst::isPrivateSeg () const
Definition at line 408 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isPrivateSeg().
isReadOnlySeg()
bool GPUDynInst::isReadOnlySeg () const
Definition at line 414 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isReadOnlySeg().
isRelaxedOrder()
bool GPUDynInst::isRelaxedOrder () const
Definition at line 462 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isRelaxedOrder().
isRelease()
bool GPUDynInst::isRelease () const
Definition at line 474 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isRelease().
isReturn()
bool GPUDynInst::isReturn () const
Definition at line 193 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isReturn().
isScalar()
bool GPUDynInst::isScalar () const
Definition at line 271 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isScalar().
isScalarRegister()
bool GPUDynInst::isScalarRegister (int operandIdx)
Definition at line 100 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isScalarRegister().
isSpecialOp()
bool GPUDynInst::isSpecialOp () const
Definition at line 205 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isSpecialOp().
isSpillSeg()
bool GPUDynInst::isSpillSeg () const
Definition at line 420 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isSpillSeg().
isSrcOperand()
bool GPUDynInst::isSrcOperand (int operandIdx)
Definition at line 130 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isSrcOperand().
isStore()
bool GPUDynInst::isStore () const
Definition at line 247 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isStore().
isSystemCoherent()
bool GPUDynInst::isSystemCoherent () const
Definition at line 498 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isSystemCoherent().
isSystemScope()
bool GPUDynInst::isSystemScope () const
Definition at line 450 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isSystemScope().
isUnconditionalJump()
bool GPUDynInst::isUnconditionalJump () const
Definition at line 199 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isUnconditionalJump().
isVectorRegister()
bool GPUDynInst::isVectorRegister (int operandIdx)
Definition at line 94 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isVectorRegister().
isWaitcnt()
bool GPUDynInst::isWaitcnt () const
Definition at line 211 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isWaitcnt().
isWavefrontScope()
bool GPUDynInst::isWavefrontScope () const
Definition at line 432 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isWavefrontScope().
isWorkgroupScope()
bool GPUDynInst::isWorkgroupScope () const
Definition at line 438 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isWorkgroupScope().
isWorkitemScope()
bool GPUDynInst::isWorkitemScope () const
Definition at line 426 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::isWorkitemScope().
makeAtomicOpFunctor()
template<typename c0 > AtomicOpFunctor* GPUDynInst::makeAtomicOpFunctor (c0 * reg0, c0 * reg1) inline
Definition at line 367 of file gpu_dyn_inst.hh.
References fatal.
numDstRegOperands()
int GPUDynInst::numDstRegOperands ()
Definition at line 82 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::numDstRegOperands().
numSrcRegOperands()
int GPUDynInst::numSrcRegOperands ()
Definition at line 76 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::numSrcRegOperands().
readsSCC()
bool GPUDynInst::readsSCC () const
Definition at line 277 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::readsSCC().
readsVCC()
bool GPUDynInst::readsVCC () const
Definition at line 289 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::readsVCC().
seqNum()
uint64_t GPUDynInst::seqNum () const
Definition at line 142 of file gpu_dyn_inst.cc.
References _seqNum.
setRequestFlags()
void GPUDynInst::setRequestFlags (RequestPtr req, bool setMemOrder = true) inline
Definition at line 397 of file gpu_dyn_inst.hh.
References Request::ACQUIRE, Request::ATOMIC_NO_RETURN_OP, Request::ATOMIC_RETURN_OP, Request::DEVICE_SCOPE, fatal, Request::GLOBAL_SEGMENT, Request::GROUP_SEGMENT, panic, Request::PRIVATE_SEGMENT, Request::READONLY_SEGMENT, Request::RELEASE, Request::SCOPE_VALID, Request::SPILL_SEGMENT, Request::SYSTEM_SCOPE, Request::WAVEFRONT_SCOPE, and Request::WORKGROUP_SCOPE.
staticInstruction()
GPUStaticInst* GPUDynInst::staticInstruction () inline
Definition at line 281 of file gpu_dyn_inst.hh.
updateStats()
void GPUDynInst::updateStats ()
Definition at line 504 of file gpu_dyn_inst.cc.
References _staticInst, GPUExecContext::cu, ComputeUnit::dynamicGMemInstrCnt, ComputeUnit::dynamicLMemInstrCnt, GPUStaticInst::isLocalMem(), ComputeUnit::pageAccesses, ComputeUnit::pageDivergenceDist, ComputeUnit::pagesTouched, and Stats::DistBase< Derived, Stor >::sample().
writesSCC()
bool GPUDynInst::writesSCC () const
Definition at line 283 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::writesSCC().
writesVCC()
bool GPUDynInst::writesVCC () const
Definition at line 295 of file gpu_dyn_inst.cc.
References _staticInst, and GPUStaticInst::writesVCC().
Member Data Documentation
_seqNum
uint64_t GPUDynInst::_seqNum private
Definition at line 468 of file gpu_dyn_inst.hh.
Referenced by seqNum().
_staticInst
GPUStaticInst* GPUDynInst::_staticInst private
Definition at line 467 of file gpu_dyn_inst.hh.
Referenced by completeAcc(), disassemble(), execute(), executedAs(), getNumOperands(), getOperandSize(), getRegisterIndex(), initiateAcc(), isAcquire(), isAcquireRelease(), isALU(), isArgLoad(), isArgSeg(), isAtomic(), isAtomicAdd(), isAtomicAnd(), isAtomicCAS(), isAtomicDec(), isAtomicExch(), isAtomicInc(), isAtomicMax(), isAtomicMin(), isAtomicNoRet(), isAtomicOr(), isAtomicRet(), isAtomicSub(), isAtomicXor(), isBarrier(), isBranch(), isCondRegister(), isDeviceScope(), isDstOperand(), isFlat(), isGloballyCoherent(), isGlobalMem(), isGlobalSeg(), isGroupSeg(), isKernArgSeg(), isLoad(), isLocalMem(), isMemFence(), isMemRef(), isNoOrder(), isNop(), isNoScope(), isPrivateSeg(), isReadOnlySeg(), isRelaxedOrder(), isRelease(), isReturn(), isScalar(), isScalarRegister(), isSpecialOp(), isSpillSeg(), isSrcOperand(), isStore(), isSystemCoherent(), isSystemScope(), isUnconditionalJump(), isVectorRegister(), isWaitcnt(), isWavefrontScope(), isWorkgroupScope(), isWorkitemScope(), numDstRegOperands(), numSrcRegOperands(), readsSCC(), readsVCC(), updateStats(), writesSCC(), and writesVCC().
a_data
uint8_t* GPUDynInst::a_data
Definition at line 228 of file gpu_dyn_inst.hh.
Referenced by GPUDynInst(), and ~GPUDynInst().
addr
std::vector<Addr> GPUDynInst::addr
Definition at line 222 of file gpu_dyn_inst.hh.
bc
uint32_t GPUDynInst::bc[4]
Definition at line 264 of file gpu_dyn_inst.hh.
cu_id
int GPUDynInst::cu_id
Definition at line 254 of file gpu_dyn_inst.hh.
d_data
uint8_t* GPUDynInst::d_data
Definition at line 226 of file gpu_dyn_inst.hh.
Referenced by GPUDynInst(), and ~GPUDynInst().
dst_reg
int GPUDynInst::dst_reg
Definition at line 244 of file gpu_dyn_inst.hh.
dst_reg_vec
int GPUDynInst::dst_reg_vec[4]
Definition at line 246 of file gpu_dyn_inst.hh.
equiv
int GPUDynInst::equiv
Definition at line 238 of file gpu_dyn_inst.hh.
exec_mask
VectorMask GPUDynInst::exec_mask
Definition at line 232 of file gpu_dyn_inst.hh.
Referenced by initiateAcc().
execContinuation
std::function<void(GPUStaticInst*, GPUDynInstPtr)> GPUDynInst::execContinuation
Definition at line 361 of file gpu_dyn_inst.hh.
kern_id
int GPUDynInst::kern_id
Definition at line 252 of file gpu_dyn_inst.hh.
latency
WaitClass GPUDynInst::latency
Definition at line 262 of file gpu_dyn_inst.hh.
m_type
Enums::MemType GPUDynInst::m_type
Definition at line 235 of file gpu_dyn_inst.hh.
memStatusVector
StatusVector GPUDynInst::memStatusVector
Definition at line 458 of file gpu_dyn_inst.hh.
n_reg
int GPUDynInst::n_reg
Definition at line 242 of file gpu_dyn_inst.hh.
pAddr
Addr GPUDynInst::pAddr
Definition at line 223 of file gpu_dyn_inst.hh.
pipeId
int GPUDynInst::pipeId
Definition at line 258 of file gpu_dyn_inst.hh.
rom
uint8_t* GPUDynInst::rom
Definition at line 267 of file gpu_dyn_inst.hh.
simdId
int GPUDynInst::simdId
Definition at line 248 of file gpu_dyn_inst.hh.
Referenced by initiateAcc().
statusBitVector
VectorMask GPUDynInst::statusBitVector
Definition at line 461 of file gpu_dyn_inst.hh.
statusVector
std::vector<int> GPUDynInst::statusVector
Definition at line 463 of file gpu_dyn_inst.hh.
sz_rom
int GPUDynInst::sz_rom
Definition at line 269 of file gpu_dyn_inst.hh.
time
Tick GPUDynInst::time
Definition at line 260 of file gpu_dyn_inst.hh.
Referenced by initiateAcc().
tlbHitLevel
std::vector<int> GPUDynInst::tlbHitLevel
Definition at line 464 of file gpu_dyn_inst.hh.
Referenced by GPUDynInst().
useContinuation
bool GPUDynInst::useContinuation
Definition at line 364 of file gpu_dyn_inst.hh.
v_type
vgpr_type GPUDynInst::v_type
Definition at line 240 of file gpu_dyn_inst.hh.
wfDynId
int GPUDynInst::wfDynId
Definition at line 250 of file gpu_dyn_inst.hh.
wfSlotId
int GPUDynInst::wfSlotId
Definition at line 256 of file gpu_dyn_inst.hh.
Referenced by initiateAcc().
x_data
uint8_t* GPUDynInst::x_data
Definition at line 230 of file gpu_dyn_inst.hh.
Referenced by GPUDynInst(), and ~GPUDynInst().
The documentation for this class was generated from the following files:
gpu-compute/gpu_dyn_inst.hh
gpu-compute/gpu_dyn_inst.cc