gem5: FuncUnit Class Reference
FuncUnit Class Reference
#include <func_unit.hh>
Public Member Functions
FuncUnit ()
FuncUnit (const FuncUnit &fu)
void addCapability (OpClass cap, unsigned oplat, bool pipelined)
bool provides (OpClass capability)
std::bitset< Num_OpClasses > capabilities ()
unsigned & opLatency (OpClass capability)
bool isPipelined (OpClass capability)
Public Attributes
std::string name
Private Attributes
std::array< unsigned, Num_OpClasses > opLatencies
std::array< bool, Num_OpClasses > pipelined
std::bitset< Num_OpClasses > capabilityList
Detailed Description
Definition at line 85 of file func_unit.hh.
Constructor & Destructor Documentation
FuncUnit() [1/2]
FuncUnit::FuncUnit ()
Definition at line 44 of file func_unit.cc.
FuncUnit() [2/2]
FuncUnit::FuncUnit (const FuncUnit & fu)
Definition at line 53 of file func_unit.cc.
References capabilityList, ArmISA::i, Num_OpClasses, opLatencies, and pipelined.
Member Function Documentation
addCapability()
void FuncUnit::addCapability (OpClass cap, unsigned oplat, bool pipelined)
Definition at line 66 of file func_unit.cc.
References panic.
Referenced by Minor::FUPipeline::FUPipeline(), and FUPool::FUPool().
capabilities()
bitset< Num_OpClasses > FuncUnit::capabilities ()
Definition at line 84 of file func_unit.cc.
isPipelined()
bool FuncUnit::isPipelined (OpClass capability)
Definition at line 96 of file func_unit.cc.
opLatency()
unsigned & FuncUnit::opLatency (OpClass capability)
Definition at line 90 of file func_unit.cc.
provides()
bool FuncUnit::provides (OpClass capability)
Definition at line 78 of file func_unit.cc.
Referenced by Minor::Execute::evaluate(), and Minor::Execute::issue().
Member Data Documentation
capabilityList
std::bitset<Num_OpClasses> FuncUnit::capabilityList private
Definition at line 90 of file func_unit.hh.
Referenced by FuncUnit().
name
std::string FuncUnit::name
Definition at line 96 of file func_unit.hh.
Referenced by FUPool::FUPool().
opLatencies
std::array<unsigned, Num_OpClasses> FuncUnit::opLatencies private
Definition at line 88 of file func_unit.hh.
Referenced by FuncUnit().
pipelined
std::array<bool, Num_OpClasses> FuncUnit::pipelined private
Definition at line 89 of file func_unit.hh.
Referenced by FuncUnit().
The documentation for this class was generated from the following files:
cpu/func_unit.hh
cpu/func_unit.cc