gem5: Stats::ScalarInfo Class Reference
Stats::ScalarInfo Class Reference abstract
#include <info.hh>
Public Member Functions
virtual Counter value () const =0
virtual Result result () const =0
virtual Result total () const =0
Public Member Functions inherited from Stats::Info
Info ()
virtual ~Info ()
void setName (const std::string &name)
Set the name of this statistic.
void setName (const Group *parent, const std::string &name)
void setSeparator (std::string _sep)
virtual bool check () const =0
Check that this stat has been set up properly and is ready for use.
bool baseCheck () const
virtual void enable ()
Enable the stat for use.
virtual void prepare ()=0
Prepare the stat for dumping.
virtual void reset ()=0
Reset the stat to the default state.
virtual bool zero () const =0
virtual void visit (Output &visitor)=0
Visitor entry for outputing statistics data.
Additional Inherited Members
Static Public Member Functions inherited from Stats::Info
static bool less (Info *stat1, Info *stat2)
Checks if the first stat's name is alphabetically less than the second.
Public Attributes inherited from Stats::Info
std::string name
The name of the stat.
std::string desc
The description of the stat.
Flags flags
The formatting flags.
int precision
The display precision.
const Info * prereq
A pointer to a prerequisite Stat.
int id
const StorageParams * storageParams
Static Public Attributes inherited from Stats::Info
static std::string separatorString = "::"
The separator string used for vectors, dist, etc.
static int id_count = 0
A unique stat ID for each stat in the simulator.
Detailed Description
Definition at line 150 of file info.hh.
Member Function Documentation
result()
virtual Result Stats::ScalarInfo::result () const pure virtual
Implemented in Stats::MethodProxy< T, V >, Stats::FunctorProxy< T >, Stats::ValueProxy< T >, and Stats::ScalarInfoProxy< Stat >.
Referenced by Stats::ValueBase< Value >::result(), Stats::ScalarStatNode::result(), Stats::ScalarStatNode::total(), Stats::Hdf5::visit(), and Stats::Text::visit().
total()
virtual Result Stats::ScalarInfo::total () const pure virtual
Implemented in Stats::MethodProxy< T, V >, Stats::FunctorProxy< T >, Stats::ValueProxy< T >, and Stats::ScalarInfoProxy< Stat >.
Referenced by Stats::ValueBase< Value >::total().
value()
virtual Counter Stats::ScalarInfo::value () const pure virtual
Implemented in Stats::MethodProxy< T, V >, Stats::FunctorProxy< T >, Stats::ValueProxy< T >, and Stats::ScalarInfoProxy< Stat >.
Referenced by Stats::ValueBase< Value >::value().
The documentation for this class was generated from the following file:
base/stats/info.hh