gem5: FUPool Class Reference
FUPool Class Reference
Pool of FU's, specific to the new CPU model.
#include <fu_pool.hh>
Classes
class FUIdxQueue
Class that implements a circular queue to hold FU indices.
Public Types
typedef FUPoolParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
FUPool (const Params *p)
Constructs a FU pool.
~FUPool ()
int getUnit (OpClass capability)
Gets a FU providing the requested capability.
void freeUnitNextCycle (int fu_idx)
Frees a FU at the end of this cycle.
void processFreeUnits ()
Frees all FUs on the list.
int size ()
Returns the total number of FUs.
void dump ()
Debugging function used to dump FU information.
Cycles getOpLatency (OpClass capability)
Returns the operation execution latency of the given capability.
bool isPipelined (OpClass capability)
Returns the issue latency of the given capability.
bool isDrained () const
Have all the FUs drained?
void takeOverFrom ()
Takes over from another CPU's thread.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Attributes
static constexpr auto NoCapableFU = -2
static constexpr auto NoFreeFU = -1
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Private Types
typedef std::vector< FuncUnit * >::iterator fuListIterator
Private Attributes
std::array< Cycles, Num_OpClasses > maxOpLatencies
Maximum op execution latencies, per op class.
std::array< bool, Num_OpClasses > pipelined
Whether op is pipelined or not.
std::bitset< Num_OpClasses > capabilityList
Bitvector listing capabilities of this FU pool.
std::vector< bool > unitBusy
Bitvector listing which FUs are busy.
std::vector< int > unitsToBeFreed
List of units to be freed at the end of this cycle.
FUIdxQueue fuPerCapList [Num_OpClasses]
Per op class queues of FUs that provide that capability.
int numFU
Number of FUs.
std::vector< FuncUnit * > funcUnits
Functional units.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Pool of FU's, specific to the new CPU model.
The old FU pool had lists of free units and busy units, and whenever a FU was needed it would iterate through the free units to find a FU that provided the capability. This pool has lists of units specific to each of the capabilities, and whenever a FU is needed, it iterates through that list to find a free unit. The previous FU pool would have to be ticked each cycle to update which units became free. This FU pool lets the IEW stage handle freeing units, which frees them as their scheduled execution events complete. This limits units in this model to either have identical issue and op latencies, or 1 cycle issue latencies.
Definition at line 71 of file fu_pool.hh.
Member Typedef Documentation
fuListIterator
typedef std::vector<FuncUnit *>::iterator FUPool::fuListIterator private
Definition at line 129 of file fu_pool.hh.
Params
typedef FUPoolParams FUPool::Params
Definition at line 132 of file fu_pool.hh.
Constructor & Destructor Documentation
FUPool()
FUPool::FUPool (const Params * p)
Constructs a FU pool.
Definition at line 84 of file fu_pool.cc.
References FuncUnit::addCapability(), FUPool::FUIdxQueue::addFU(), ArmISA::c, capabilityList, PowerISA::fu, funcUnits, fuPerCapList, ArmISA::i, ArmISA::j, MipsISA::k, maxOpLatencies, FuncUnit::name, numFU, pipelined, ArmISA::s, and unitBusy.
Referenced by isDrained().
~FUPool()
FUPool::~FUPool ()
Definition at line 74 of file fu_pool.cc.
References ArmISA::i.
Member Function Documentation
dump()
void FUPool::dump ()
Debugging function used to dump FU information.
Definition at line 208 of file fu_pool.cc.
References funcUnits, ArmISA::i, SimObject::name(), numFU, and unitBusy.
Referenced by size().
freeUnitNextCycle()
void FUPool::freeUnitNextCycle (int fu_idx)
Frees a FU at the end of this cycle.
Definition at line 188 of file fu_pool.cc.
References unitBusy, and unitsToBeFreed.
Referenced by InstructionQueue< Impl >::processFUCompletion(), and InstructionQueue< Impl >::scheduleReadyInsts().
getOpLatency()
Cycles FUPool::getOpLatency (OpClass capability) inline
Returns the operation execution latency of the given capability.
Definition at line 164 of file fu_pool.hh.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
getUnit()
int FUPool::getUnit (OpClass capability)
Gets a FU providing the requested capability.
Will mark the unit as busy, but leaves the freeing of the unit up to the IEW stage.
Parameters
capability The capability requested.
Returns
Returns NoCapableFU if the FU pool does not have the capability, NoFreeFU if there is no free FU, and the FU's index otherwise.
Definition at line 160 of file fu_pool.cc.
References capabilityList, fuPerCapList, FUPool::FUIdxQueue::getFU(), numFU, and unitBusy.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
isDrained()
bool FUPool::isDrained () const
Have all the FUs drained?
Definition at line 242 of file fu_pool.cc.
References FUPool(), ArmISA::i, numFU, and unitBusy.
Referenced by DefaultIEW< Impl >::isDrained(), and isPipelined().
isPipelined()
bool FUPool::isPipelined (OpClass capability) inline
Returns the issue latency of the given capability.
Definition at line 169 of file fu_pool.hh.
References isDrained().
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
processFreeUnits()
void FUPool::processFreeUnits ()
Frees all FUs on the list.
Definition at line 195 of file fu_pool.cc.
References unitBusy, and unitsToBeFreed.
Referenced by DefaultIEW< Impl >::tick().
size()
int FUPool::size () inline
Returns the total number of FUs.
Definition at line 158 of file fu_pool.hh.
References dump(), and numFU.
takeOverFrom()
void FUPool::takeOverFrom () inline
Takes over from another CPU's thread.
Definition at line 177 of file fu_pool.hh.
Referenced by DefaultIEW< Impl >::takeOverFrom().
Member Data Documentation
capabilityList
std::bitset<Num_OpClasses> FUPool::capabilityList private
Bitvector listing capabilities of this FU pool.
Definition at line 80 of file fu_pool.hh.
Referenced by FUPool(), and getUnit().
funcUnits
std::vector<FuncUnit *> FUPool::funcUnits private
Functional units.
Definition at line 127 of file fu_pool.hh.
Referenced by dump(), and FUPool().
fuPerCapList
FUIdxQueue FUPool::fuPerCapList[Num_OpClasses] private
Per op class queues of FUs that provide that capability.
Definition at line 121 of file fu_pool.hh.
Referenced by FUPool(), and getUnit().
maxOpLatencies
std::array<Cycles, Num_OpClasses> FUPool::maxOpLatencies private
Maximum op execution latencies, per op class.
Definition at line 75 of file fu_pool.hh.
Referenced by FUPool().
NoCapableFU
constexpr auto FUPool::NoCapableFU = -2 static
Definition at line 137 of file fu_pool.hh.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
NoFreeFU
constexpr auto FUPool::NoFreeFU = -1 static
Definition at line 138 of file fu_pool.hh.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
numFU
int FUPool::numFU private
Number of FUs.
Definition at line 124 of file fu_pool.hh.
Referenced by dump(), FUPool(), getUnit(), isDrained(), and size().
pipelined
std::array<bool, Num_OpClasses> FUPool::pipelined private
Whether op is pipelined or not.
Definition at line 77 of file fu_pool.hh.
Referenced by FUPool().
unitBusy
std::vector<bool> FUPool::unitBusy private
Bitvector listing which FUs are busy.
Definition at line 83 of file fu_pool.hh.
Referenced by dump(), freeUnitNextCycle(), FUPool(), getUnit(), isDrained(), and processFreeUnits().
unitsToBeFreed
std::vector<int> FUPool::unitsToBeFreed private
List of units to be freed at the end of this cycle.
Definition at line 86 of file fu_pool.hh.
Referenced by freeUnitNextCycle(), and processFreeUnits().
The documentation for this class was generated from the following files:
cpu/o3/fu_pool.hh
cpu/o3/fu_pool.cc