gem5: tlm::tlm_nonblocking_get_if< T > Class Template Reference
tlm::tlm_nonblocking_get_if< T > Class Template Reference abstract
#include <core_ifs.hh>
Public Member Functions
virtual bool nb_get (T &t)=0
virtual bool nb_can_get (tlm_tag< T > *t=nullptr) const =0
virtual const sc_core::sc_event & ok_to_get (tlm_tag< T > *t=nullptr) const =0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Detailed Description
template<typename T>
class tlm::tlm_nonblocking_get_if< T >
Definition at line 61 of file core_ifs.hh.
Member Function Documentation
nb_can_get()
template<typename T> virtual bool tlm::tlm_nonblocking_get_if< T >::nb_can_get (tlm_tag< T > * t = nullptr) const pure virtual
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_can_get().
nb_get()
template<typename T> virtual bool tlm::tlm_nonblocking_get_if< T >::nb_get (T & t) pure virtual
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_get().
ok_to_get()
template<typename T> virtual const sc_core::sc_event& tlm::tlm_nonblocking_get_if< T >::ok_to_get (tlm_tag< T > * t = nullptr) const pure virtual
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_nonblocking_get_port< T >::ok_to_get(), and tlm::tlm_put_get_imp< RSP, REQ >::ok_to_get().
The documentation for this class was generated from the following file:
systemc/ext/tlm_core/1/req_rsp/interfaces/core_ifs.hh