gem5: X86ISA::RemoteGDB Class Reference
X86ISA::RemoteGDB Class Reference
#include <remote_gdb.hh>
Classes
class AMD64GdbRegCache
class X86GdbRegCache
Public Member Functions
RemoteGDB (System *system, ThreadContext *context, int _port)
BaseGdbRegCache * gdbRegs ()
Public Member Functions inherited from BaseRemoteGDB
bool breakpoint ()
void replaceThreadContext (ThreadContext *tc)
virtual ~BaseRemoteGDB ()
BaseRemoteGDB (System *system, ThreadContext *context, int _port)
virtual ~BaseRemoteGDB ()
std::string name ()
void listen ()
void connect ()
int port () const
void attach (int fd)
void detach ()
bool isAttached ()
void replaceThreadContext (ThreadContext *_tc)
bool trap (int type)
bool breakpoint ()
Protected Member Functions
bool acc (Addr addr, size_t len)
bool checkBpLen (size_t len)
Protected Member Functions inherited from BaseRemoteGDB
ThreadContext * context ()
System * system ()
void encodeBinaryData (const std::string &unencoded, std::string &encoded) const
void encodeXferResponse (const std::string &unencoded, std::string &encoded, size_t offset, size_t unencoded_length) const
virtual std::vector< std::string > availableFeatures () const
virtual bool getXferFeaturesRead (const std::string &annex, std::string &output)
Get an XML target description.
Protected Attributes
X86GdbRegCache regCache32
AMD64GdbRegCache regCache64
Detailed Description
Definition at line 56 of file remote_gdb.hh.
Constructor & Destructor Documentation
RemoteGDB()
RemoteGDB::RemoteGDB (System * system, ThreadContext * context, int _port)
Definition at line 67 of file remote_gdb.cc.
Member Function Documentation
acc()
bool RemoteGDB::acc (Addr addr, size_t len) protected virtual
Implements BaseRemoteGDB.
Definition at line 72 of file remote_gdb.cc.
References BaseRemoteGDB::context(), FullSystem, ThreadContext::getDTBPtr(), ThreadContext::getProcessPtr(), EmulationPageTable::lookup(), X86ISA::mask, NoFault, Process::pTable, BaseTLB::Read, and X86ISA::Walker::startFunctional().
checkBpLen()
bool X86ISA::RemoteGDB::checkBpLen (size_t len) inline protected virtual
Reimplemented from BaseRemoteGDB.
Definition at line 60 of file remote_gdb.hh.
gdbRegs()
BaseGdbRegCache * RemoteGDB::gdbRegs () virtual
Implements BaseRemoteGDB.
Definition at line 96 of file remote_gdb.cc.
References BaseRemoteGDB::context(), X86ISA::MISCREG_M5_REG, ThreadContext::readMiscRegNoEffect(), regCache32, regCache64, and X86ISA::SixtyFourBitMode.
Member Data Documentation
regCache32
X86GdbRegCache X86ISA::RemoteGDB::regCache32 protected
Definition at line 142 of file remote_gdb.hh.
Referenced by gdbRegs().
regCache64
AMD64GdbRegCache X86ISA::RemoteGDB::regCache64 protected
Definition at line 143 of file remote_gdb.hh.
Referenced by gdbRegs().
The documentation for this class was generated from the following files:
arch/x86/remote_gdb.hh
arch/x86/remote_gdb.cc