gem5: MipsISA::ISA Class Reference
MipsISA::ISA Class Reference
#include <isa.hh>
Public Types
enum CP0EventType { UpdateCP0 }
typedef ISA CP0
typedef MipsISAParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void clear ()
void configCP ()
unsigned getVPENum (ThreadID tid) const
void updateCP0ReadView (int misc_reg, ThreadID tid)
RegVal readMiscRegNoEffect (int misc_reg, ThreadID tid=0) const
RegVal readMiscReg (int misc_reg, ThreadContext *tc, ThreadID tid=0)
RegVal filterCP0Write (int misc_reg, int reg_sel, RegVal val)
This method doesn't need to adjust the Control Register Offset since it has already been done in the calling method (setRegWithEffect)
void setRegMask (int misc_reg, RegVal val, ThreadID tid=0)
void setMiscRegNoEffect (int misc_reg, RegVal val, ThreadID tid=0)
void setMiscReg (int misc_reg, RegVal val, ThreadContext *tc, ThreadID tid=0)
void processCP0Event (BaseCPU *cpu, CP0EventType)
Process a CP0 event.
void scheduleCP0Update (BaseCPU *cpu, Cycles delay=Cycles(0))
void updateCPU (BaseCPU *cpu)
void startup (ThreadContext *tc)
const Params * params () const
ISA (Params *p)
RegId flattenRegId (const RegId &regId) const
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenVecIndex (int reg) const
int flattenVecElemIndex (int reg) const
int flattenVecPredIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
bool cp0Updated
Static Public Attributes
static std::string miscRegNames [NumMiscRegs]
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
enum BankType { perProcessor, perThreadContext, perVirtProcessor }
Protected Attributes
uint8_t numThreads
uint8_t numVpes
std::vector< std::vector< RegVal > > miscRegFile
std::vector< std::vector< RegVal > > miscRegFile_WriteMask
std::vector< BankType > bankType
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 52 of file isa.hh.
Member Typedef Documentation
CP0
typedef ISA MipsISA::ISA::CP0
Definition at line 56 of file isa.hh.
Params
typedef MipsISAParams MipsISA::ISA::Params
Definition at line 58 of file isa.hh.
Member Enumeration Documentation
BankType
enum MipsISA::ISA::BankType protected
Enumerator
perProcessor
perThreadContext
perVirtProcessor
Definition at line 65 of file isa.hh.
CP0EventType
enum MipsISA::ISA::CP0EventType
Enumerator
UpdateCP0
Definition at line 115 of file isa.hh.
Constructor & Destructor Documentation
ISA()
MipsISA::ISA::ISA (Params * p)
Definition at line 92 of file isa.cc.
References bankType, clear(), MipsISA::i, MipsISA::MISCREG_DEBUG, MipsISA::MISCREG_EBASE, MipsISA::MISCREG_LLADDR, MipsISA::MISCREG_SRS_CONF0, MipsISA::MISCREG_SRS_CONF1, MipsISA::MISCREG_SRS_CONF2, MipsISA::MISCREG_SRS_CONF3, MipsISA::MISCREG_SRS_CONF4, MipsISA::MISCREG_STATUS, MipsISA::MISCREG_TC_BIND, MipsISA::MISCREG_TC_CONTEXT, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_RESTART, MipsISA::MISCREG_TC_SCHEDULE, MipsISA::MISCREG_TC_SCHEFBACK, MipsISA::MISCREG_TC_STATUS, MipsISA::MISCREG_VPE_CONF0, MipsISA::MISCREG_VPE_CONF1, MipsISA::MISCREG_VPE_CONTROL, MipsISA::MISCREG_VPE_OPT, MipsISA::MISCREG_VPE_SCHEDULE, MipsISA::MISCREG_VPE_SCHEFBACK, MipsISA::MISCREG_YQMASK, miscRegFile, miscRegFile_WriteMask, MipsISA::NumMiscRegs, numThreads, numVpes, perProcessor, perThreadContext, and perVirtProcessor.
Referenced by startup().
Member Function Documentation
clear()
void MipsISA::ISA::clear ()
Definition at line 152 of file isa.cc.
References MipsISA::i, ArmISA::j, MipsISA::k, miscRegFile, miscRegFile_WriteMask, and MipsISA::NumMiscRegs.
Referenced by ISA().
configCP()
void MipsISA::ISA::configCP ()
Definition at line 165 of file isa.cc.
References MipsISA::CoreSpecific::CP0_Config1_C2, MipsISA::CoreSpecific::CP0_Config1_DA, MipsISA::CoreSpecific::CP0_Config1_DL, MipsISA::CoreSpecific::CP0_Config1_DS, MipsISA::CoreSpecific::CP0_Config1_EP, MipsISA::CoreSpecific::CP0_Config1_FP, MipsISA::CoreSpecific::CP0_Config1_IA, MipsISA::CoreSpecific::CP0_Config1_IL, MipsISA::CoreSpecific::CP0_Config1_IS, MipsISA::CoreSpecific::CP0_Config1_M, MipsISA::CoreSpecific::CP0_Config1_MD, MipsISA::CoreSpecific::CP0_Config1_MMU, MipsISA::CoreSpecific::CP0_Config1_PC, MipsISA::CoreSpecific::CP0_Config1_WR, MipsISA::CoreSpecific::CP0_Config2_M, MipsISA::CoreSpecific::CP0_Config2_SA, MipsISA::CoreSpecific::CP0_Config2_SL, MipsISA::CoreSpecific::CP0_Config2_SS, MipsISA::CoreSpecific::CP0_Config2_SU, MipsISA::CoreSpecific::CP0_Config2_TA, MipsISA::CoreSpecific::CP0_Config2_TL, MipsISA::CoreSpecific::CP0_Config2_TS, MipsISA::CoreSpecific::CP0_Config2_TU, MipsISA::CoreSpecific::CP0_Config3_DSPP, MipsISA::CoreSpecific::CP0_Config3_LPA, MipsISA::CoreSpecific::CP0_Config3_MT, MipsISA::CoreSpecific::CP0_Config3_SM, MipsISA::CoreSpecific::CP0_Config3_SP, MipsISA::CoreSpecific::CP0_Config3_TL, MipsISA::CoreSpecific::CP0_Config3_VEIC, MipsISA::CoreSpecific::CP0_Config3_VInt, MipsISA::CoreSpecific::CP0_Config_AR, MipsISA::CoreSpecific::CP0_Config_AT, MipsISA::CoreSpecific::CP0_Config_BE, MipsISA::CoreSpecific::CP0_Config_MT, MipsISA::CoreSpecific::CP0_Config_VI, MipsISA::CoreSpecific::CP0_EBase_CPUNum, MipsISA::CoreSpecific::CP0_IntCtl_IPPCI, MipsISA::CoreSpecific::CP0_IntCtl_IPTI, MipsISA::CoreSpecific::CP0_PerfCtr_M, MipsISA::CoreSpecific::CP0_PerfCtr_W, MipsISA::CoreSpecific::CP0_PRId_CompanyID, MipsISA::CoreSpecific::CP0_PRId_CompanyOptions, MipsISA::CoreSpecific::CP0_PRId_ProcessorID, MipsISA::CoreSpecific::CP0_PRId_Revision, MipsISA::CoreSpecific::CP0_SrsCtl_HSS, MipsISA::CoreSpecific::CP0_WatchHi_M, DPRINTF, MipsISA::mask, MipsISA::MISCREG_BADVADDR, MipsISA::MISCREG_CAUSE, MipsISA::MISCREG_CONFIG, MipsISA::MISCREG_CONFIG1, MipsISA::MISCREG_CONFIG2, MipsISA::MISCREG_CONFIG3, MipsISA::MISCREG_CONTEXT, MipsISA::MISCREG_CP0_RANDOM, MipsISA::MISCREG_EBASE, MipsISA::MISCREG_ENTRYLO0, MipsISA::MISCREG_ENTRYLO1, MipsISA::MISCREG_INDEX, MipsISA::MISCREG_INTCTL, MipsISA::MISCREG_LLADDR, MipsISA::MISCREG_MVP_CONF0, MipsISA::MISCREG_PAGEGRAIN, MipsISA::MISCREG_PAGEMASK, MipsISA::MISCREG_PERFCNT0, MipsISA::MISCREG_PRID, MipsISA::MISCREG_SRSCTL, MipsISA::MISCREG_STATUS, MipsISA::MISCREG_TC_BIND, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_STATUS, MipsISA::MISCREG_VPE_CONF0, MipsISA::MISCREG_WATCHHI0, numThreads, numVpes, panic, MipsISA::procId, readMiscRegNoEffect(), replaceBits(), setMiscRegNoEffect(), setRegMask(), and ArmISA::status.
filterCP0Write()
RegVal MipsISA::ISA::filterCP0Write (int misc_reg, int reg_sel, RegVal val)
This method doesn't need to adjust the Control Register Offset since it has already been done in the calling method (setRegWithEffect)
Definition at line 499 of file isa.cc.
References DPRINTF, miscRegFile, miscRegFile_WriteMask, and X86ISA::val.
Referenced by setMiscReg(), and updateCP0ReadView().
flattenCCIndex()
int MipsISA::ISA::flattenCCIndex (int reg) const inline
Definition at line 175 of file isa.hh.
References X86ISA::reg.
flattenFloatIndex()
int MipsISA::ISA::flattenFloatIndex (int reg) const inline
Definition at line 150 of file isa.hh.
References X86ISA::reg.
flattenIntIndex()
int MipsISA::ISA::flattenIntIndex (int reg) const inline
Definition at line 144 of file isa.hh.
References X86ISA::reg.
flattenMiscIndex()
int MipsISA::ISA::flattenMiscIndex (int reg) const inline
Definition at line 181 of file isa.hh.
References X86ISA::reg.
flattenRegId()
RegId MipsISA::ISA::flattenRegId (const RegId & regId) const inline
Definition at line 141 of file isa.hh.
flattenVecElemIndex()
int MipsISA::ISA::flattenVecElemIndex (int reg) const inline
Definition at line 162 of file isa.hh.
References X86ISA::reg.
flattenVecIndex()
int MipsISA::ISA::flattenVecIndex (int reg) const inline
Definition at line 156 of file isa.hh.
References X86ISA::reg.
flattenVecPredIndex()
int MipsISA::ISA::flattenVecPredIndex (int reg) const inline
Definition at line 168 of file isa.hh.
References X86ISA::reg.
getVPENum()
unsigned MipsISA::ISA::getVPENum (ThreadID tid) const inline
Definition at line 414 of file isa.cc.
References MipsISA::MISCREG_TC_BIND, and miscRegFile.
Referenced by readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
params()
const MipsISAParams * MipsISA::ISA::params () const
Definition at line 146 of file isa.cc.
References SimObject::_params.
Referenced by startup().
processCP0Event()
void MipsISA::ISA::processCP0Event (BaseCPU * cpu, CP0EventType cp0EventType)
Process a CP0 event.
Definition at line 562 of file isa.cc.
References UpdateCP0, and updateCPU().
Referenced by scheduleCP0Update().
readMiscReg()
RegVal MipsISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc, ThreadID tid = 0)
Definition at line 435 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, and perThreadContext.
Referenced by updateCP0ReadView().
readMiscRegNoEffect()
RegVal MipsISA::ISA::readMiscRegNoEffect (int misc_reg, ThreadID tid = 0) const
Definition at line 421 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, and perThreadContext.
Referenced by configCP(), updateCP0ReadView(), and updateCPU().
scheduleCP0Update()
void MipsISA::ISA::scheduleCP0Update (BaseCPU * cpu, Cycles delay = Cycles(0))
Definition at line 519 of file isa.cc.
References Clocked::clockEdge(), cp0Updated, EventBase::CPU_Tick_Pri, processCP0Event(), EventManager::schedule(), and UpdateCP0.
Referenced by setMiscReg().
setMiscReg()
void MipsISA::ISA::setMiscReg (int misc_reg, RegVal val, ThreadContext * tc, ThreadID tid = 0)
Definition at line 476 of file isa.cc.
References bankType, DPRINTF, filterCP0Write(), ThreadContext::getCpuPtr(), getVPENum(), miscRegFile, miscRegNames, perThreadContext, and scheduleCP0Update().
Referenced by updateCP0ReadView().
setMiscRegNoEffect()
void MipsISA::ISA::setMiscRegNoEffect (int misc_reg, RegVal val, ThreadID tid = 0)
Definition at line 448 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile, miscRegNames, perThreadContext, and X86ISA::val.
Referenced by configCP(), and updateCP0ReadView().
setRegMask()
void MipsISA::ISA::setRegMask (int misc_reg, RegVal val, ThreadID tid = 0)
Definition at line 461 of file isa.cc.
References bankType, DPRINTF, getVPENum(), miscRegFile_WriteMask, miscRegNames, perThreadContext, and X86ISA::val.
Referenced by configCP(), and updateCP0ReadView().
startup()
void MipsISA::ISA::startup (ThreadContext * tc) inline
Definition at line 132 of file isa.hh.
References ISA(), MipsISA::p, params(), and SimObject::startup().
updateCP0ReadView()
void MipsISA::ISA::updateCP0ReadView (int misc_reg, ThreadID tid) inline
Definition at line 90 of file isa.hh.
References filterCP0Write(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), setRegMask(), and X86ISA::val.
updateCPU()
void MipsISA::ISA::updateCPU (BaseCPU * cpu)
Definition at line 533 of file isa.cc.
References cp0Updated, BaseCPU::getContext(), MipsISA::haltThread(), MipsISA::MISCREG_MVP_CONF0, MipsISA::MISCREG_TC_HALT, MipsISA::MISCREG_TC_STATUS, readMiscRegNoEffect(), and MipsISA::restoreThread().
Referenced by processCP0Event().
Member Data Documentation
bankType
std::vector<BankType> MipsISA::ISA::bankType protected
Definition at line 73 of file isa.hh.
Referenced by ISA(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
cp0Updated
bool MipsISA::ISA::cp0Updated
Definition at line 112 of file isa.hh.
Referenced by scheduleCP0Update(), and updateCPU().
miscRegFile
std::vector<std::vector<RegVal> > MipsISA::ISA::miscRegFile protected
Definition at line 71 of file isa.hh.
Referenced by clear(), filterCP0Write(), getVPENum(), ISA(), readMiscReg(), readMiscRegNoEffect(), setMiscReg(), and setMiscRegNoEffect().
miscRegFile_WriteMask
std::vector<std::vector<RegVal> > MipsISA::ISA::miscRegFile_WriteMask protected
Definition at line 72 of file isa.hh.
Referenced by clear(), filterCP0Write(), ISA(), and setRegMask().
miscRegNames
std::string MipsISA::ISA::miscRegNames static
Definition at line 129 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), setMiscReg(), setMiscRegNoEffect(), and setRegMask().
numThreads
uint8_t MipsISA::ISA::numThreads protected
Definition at line 62 of file isa.hh.
Referenced by configCP(), and ISA().
numVpes
uint8_t MipsISA::ISA::numVpes protected
Definition at line 63 of file isa.hh.
Referenced by configCP(), and ISA().
The documentation for this class was generated from the following files:
arch/mips/isa.hh
arch/mips/isa.cc