gem5: sc_gem5::VcdTraceValTime Class Reference
sc_gem5::VcdTraceValTime Class Reference
Public Member Functions
std::string vcdType () override
void finalize () override
void output (std::ostream &os) override
Public Member Functions inherited from sc_gem5::VcdTraceVal<::sc_core::sc_time >
VcdTraceVal (const ::sc_core::sc_time *t, const std::string &vcd_name, int width)
Public Member Functions inherited from sc_gem5::TraceVal< ::sc_core::sc_time, VcdTraceValBase >
TraceVal (const ::sc_core::sc_time *_t, int _width)
~TraceVal ()
void finalize () override
const ::sc_core::sc_time & value ()
bool check () override
Public Member Functions inherited from sc_gem5::VcdTraceValBase
VcdTraceValBase (int width)
~VcdTraceValBase ()
void vcdName (const std::string &vcd_name)
const std::string & vcdName ()
Public Member Functions inherited from sc_gem5::TraceValBase
TraceValBase (int _width)
virtual ~TraceValBase ()
int width ()
Static Private Attributes
static const int TimeWidth = 64
Additional Inherited Members
Public Types inherited from sc_gem5::VcdTraceVal<::sc_core::sc_time >
typedef ::sc_core::sc_time TracedType
Protected Member Functions inherited from sc_gem5::VcdTraceValBase
const char * stripLeadingBits (const char *orig)
char scLogicToVcdState (char in)
void printVal (std::ostream &os, const std::string &rep)
Protected Attributes inherited from sc_gem5::VcdTraceValBase
std::string _vcdName
Protected Attributes inherited from sc_gem5::TraceValBase
int _width
Detailed Description
Definition at line 557 of file vcd.cc.
Member Function Documentation
finalize()
void sc_gem5::VcdTraceValTime::finalize () inline override virtual
Reimplemented from sc_gem5::TraceValBase.
Definition at line 568 of file vcd.cc.
References sc_gem5::TraceValBase::_width, and sc_gem5::TraceVal< T, VcdTraceValBase >::finalize().
output()
void sc_gem5::VcdTraceValTime::output (std::ostream & os) inline override virtual
Implements sc_gem5::VcdTraceValBase.
Definition at line 575 of file vcd.cc.
References bits(), ArmISA::i, sc_gem5::VcdTraceValBase::printVal(), and X86ISA::val.
vcdType()
std::string sc_gem5::VcdTraceValTime::vcdType () inline override virtual
Reimplemented from sc_gem5::VcdTraceValBase.
Definition at line 565 of file vcd.cc.
Member Data Documentation
TimeWidth
const int sc_gem5::VcdTraceValTime::TimeWidth = 64 static private
Definition at line 560 of file vcd.cc.
The documentation for this class was generated from the following file:
systemc/utils/vcd.cc