gem5: DistIface::RecvScheduler Class Reference
DistIface::RecvScheduler Class Reference
Class to encapsulate information about data packets received.
Classes
struct Desc
Received packet descriptor.
Public Member Functions
RecvScheduler (EventManager *em)
Scheduler for the incoming data packets.
void init (Event *recv_done, Tick link_delay)
Initialize network link parameters.
EthPacketPtr popPacket ()
Fetch the next packet that is to be received by the simulated network link.
void pushPacket (EthPacketPtr new_packet, Tick send_tick, Tick send_delay)
Push a newly arrived packet into the desc queue.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void resumeRecvTicks ()
Adjust receive ticks for pending packets when restoring from a checkpoint.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Member Functions
Tick calcReceiveTick (Tick send_tick, Tick send_delay, Tick prev_recv_tick)
Calculate the tick to schedule the next receive done event.
Private Attributes
std::queue< Desc > descQueue
The queue to store the receive descriptors.
Tick prevRecvTick
The tick when the most recent receive event was processed.
Event * recvDone
The receive done event for the simulated Ethernet link.
Tick linkDelay
The link delay in ticks for the simulated Ethernet link.
EventManager * eventManager
The event manager associated with the simulated Ethernet link.
bool ckptRestore
Flag to set if receive ticks for pending packets need to be recalculated due to changed link latencies at a resume.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Class to encapsulate information about data packets received.
Note
The main purpose of the class to take care of scheduling receive done events for the simulated network link and store incoming packets until they can be received by the simulated network link.
Definition at line 333 of file dist_iface.hh.
Constructor & Destructor Documentation
RecvScheduler()
DistIface::RecvScheduler::RecvScheduler (EventManager * em) inline
Scheduler for the incoming data packets.
Parameters
em The event manager associated with the simulated Ethernet link.
Definition at line 418 of file dist_iface.hh.
References DistIface::Sync::init(), DistIface::Sync::serialize(), and DistIface::Sync::unserialize().
Member Function Documentation
calcReceiveTick()
Tick DistIface::RecvScheduler::calcReceiveTick (Tick send_tick, Tick send_delay, Tick prev_recv_tick) private
Calculate the tick to schedule the next receive done event.
Parameters
send_tick The tick the packet was sent.
send_delay The simulated delay at the sender side.
prev_recv_tick Tick when the last receive event was processed.
Note
This method tries to take into account possible receiver link contention and adjust receive tick for the incoming packets accordingly.
Definition at line 445 of file dist_iface.cc.
References curTick(), and panic_if.
init()
void DistIface::RecvScheduler::init (Event * recv_done, Tick link_delay)
Initialize network link parameters.
Note
This method is called from the receiver thread (see recvThreadFunc()).
Definition at line 433 of file dist_iface.cc.
References curEventQueue().
Referenced by DistIface::recvThreadFunc().
popPacket()
EthPacketPtr DistIface::RecvScheduler::popPacket ()
Fetch the next packet that is to be received by the simulated network link.
Note
This method is called from the process() method of the receive done event associated with the network link.
Definition at line 536 of file dist_iface.cc.
References curTick().
Referenced by DistIface::packetIn().
pushPacket()
void DistIface::RecvScheduler::pushPacket (EthPacketPtr new_packet, Tick send_tick, Tick send_delay)
Push a newly arrived packet into the desc queue.
Definition at line 498 of file dist_iface.cc.
References curEventQueue(), DPRINTF, EventQueue::lock(), panic_if, and EventQueue::unlock().
Referenced by DistIface::recvThreadFunc().
resumeRecvTicks()
void DistIface::RecvScheduler::resumeRecvTicks ()
Adjust receive ticks for pending packets when restoring from a checkpoint.
Note
Link speed and delay parameters may change at resume.
Definition at line 465 of file dist_iface.cc.
References curTick(), ArmISA::d, DistIface::RecvScheduler::Desc::packet, DistIface::RecvScheduler::Desc::sendDelay, DistIface::RecvScheduler::Desc::sendTick, and ArmISA::v.
Referenced by DistIface::drainResume().
serialize()
void DistIface::RecvScheduler::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 572 of file dist_iface.cc.
References csprintf(), ArmISA::i, and SERIALIZE_SCALAR.
unserialize()
void DistIface::RecvScheduler::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 588 of file dist_iface.cc.
References csprintf(), ArmISA::i, UNSERIALIZE_SCALAR, and Serializable::unserializeSection().
Member Data Documentation
ckptRestore
bool DistIface::RecvScheduler::ckptRestore private
Flag to set if receive ticks for pending packets need to be recalculated due to changed link latencies at a resume.
Definition at line 409 of file dist_iface.hh.
descQueue
std::queue<Desc> DistIface::RecvScheduler::descQueue private
The queue to store the receive descriptors.
Definition at line 359 of file dist_iface.hh.
eventManager
EventManager* DistIface::RecvScheduler::eventManager private
The event manager associated with the simulated Ethernet link.
Note
It is used to access the event queue for scheduling receive done events for the link.
Definition at line 388 of file dist_iface.hh.
linkDelay
Tick DistIface::RecvScheduler::linkDelay private
The link delay in ticks for the simulated Ethernet link.
Note
This value is used for calculating the receive ticks for incoming data packets.
Definition at line 381 of file dist_iface.hh.
prevRecvTick
Tick DistIface::RecvScheduler::prevRecvTick private
The tick when the most recent receive event was processed.
Note
This information is necessary to simulate possible receiver link contention when calculating the receive tick for the next incoming data packet (see the calcReceiveTick() method)
Definition at line 367 of file dist_iface.hh.
recvDone
Event* DistIface::RecvScheduler::recvDone private
The receive done event for the simulated Ethernet link.
Note
This object is constructed by the simulated network link. We schedule this object for each incoming data packet.
Definition at line 374 of file dist_iface.hh.
The documentation for this class was generated from the following files:
dev/net/dist_iface.hh
dev/net/dist_iface.cc