gem5: Stats::Info Class Reference
Stats::Info Class Reference abstract
#include <info.hh>
Public Member Functions
Info ()
virtual ~Info ()
void setName (const std::string &name)
Set the name of this statistic.
void setName (const Group *parent, const std::string &name)
void setSeparator (std::string _sep)
virtual bool check () const =0
Check that this stat has been set up properly and is ready for use.
bool baseCheck () const
virtual void enable ()
Enable the stat for use.
virtual void prepare ()=0
Prepare the stat for dumping.
virtual void reset ()=0
Reset the stat to the default state.
virtual bool zero () const =0
virtual void visit (Output &visitor)=0
Visitor entry for outputing statistics data.
Static Public Member Functions
static bool less (Info *stat1, Info *stat2)
Checks if the first stat's name is alphabetically less than the second.
Public Attributes
std::string name
The name of the stat.
std::string desc
The description of the stat.
Flags flags
The formatting flags.
int precision
The display precision.
const Info * prereq
A pointer to a prerequisite Stat.
int id
const StorageParams * storageParams
Static Public Attributes
static std::string separatorString = "::"
The separator string used for vectors, dist, etc.
static int id_count = 0
A unique stat ID for each stat in the simulator.
Detailed Description
Definition at line 71 of file info.hh.
Constructor & Destructor Documentation
Info()
Stats::Info::Info ()
Definition at line 160 of file statistics.cc.
References Debug::breakpoint(), and id_count.
~Info()
Stats::Info::~Info () virtual
Definition at line 168 of file statistics.cc.
Member Function Documentation
baseCheck()
bool Stats::Info::baseCheck () const
Definition at line 257 of file statistics.cc.
References cprintf(), Stats::display, flags, Stats::init, and panic.
Referenced by pybind_init_stats(), and setSeparator().
check()
virtual bool Stats::Info::check () const pure virtual
Check that this stat has been set up properly and is ready for use.
Returns
true for success
Implemented in Stats::ProxyInfo, Stats::InfoProxy< Stat, VectorDistInfo >, Stats::InfoProxy< Stat, ScalarInfo >, Stats::InfoProxy< Stat, SparseHistInfo >, Stats::InfoProxy< Stat, Vector2dInfo >, Stats::InfoProxy< Stat, DistInfo >, Stats::InfoProxy< Stat, VectorInfo >, and Stats::InfoProxy< Stat, FormulaInfo >.
Referenced by pybind_init_stats(), and setSeparator().
enable()
void Stats::Info::enable () virtual
Enable the stat for use.
Reimplemented in Stats::Vector2dInfo, Stats::VectorDistInfo, and Stats::VectorInfo.
Definition at line 279 of file statistics.cc.
Referenced by pybind_init_stats(), and setSeparator().
less()
bool Stats::Info::less (Info * stat1, Info * stat2) static
Checks if the first stat's name is alphabetically less than the second.
This function breaks names up at periods and considers each subname separately.
Parameters
stat1 The first stat.
stat2 The second stat.
Returns
stat1's name is alphabetically before stat2's
Definition at line 231 of file statistics.cc.
References ArmISA::i, name, and tokenize().
Referenced by setSeparator().
prepare()
virtual void Stats::Info::prepare () pure virtual
Prepare the stat for dumping.
Implemented in Stats::ProxyInfo, Stats::InfoProxy< Stat, VectorDistInfo >, Stats::InfoProxy< Stat, ScalarInfo >, Stats::InfoProxy< Stat, SparseHistInfo >, Stats::InfoProxy< Stat, Vector2dInfo >, Stats::InfoProxy< Stat, DistInfo >, Stats::InfoProxy< Stat, VectorInfo >, and Stats::InfoProxy< Stat, FormulaInfo >.
Referenced by pybind_init_stats(), and setSeparator().
reset()
virtual void Stats::Info::reset () pure virtual
Reset the stat to the default state.
Implemented in Stats::ProxyInfo, Stats::InfoProxy< Stat, VectorDistInfo >, Stats::InfoProxy< Stat, ScalarInfo >, Stats::InfoProxy< Stat, SparseHistInfo >, Stats::InfoProxy< Stat, Vector2dInfo >, Stats::InfoProxy< Stat, DistInfo >, Stats::InfoProxy< Stat, VectorInfo >, and Stats::InfoProxy< Stat, FormulaInfo >.
Referenced by pybind_init_stats(), and setSeparator().
setName() [1/2]
void Stats::Info::setName (const std::string & name)
Set the name of this statistic.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::name(), and Stats::validateStatName().
setName() [2/2]
void Stats::Info::setName (const Group * parent, const std::string & name)
setSeparator()
void Stats::Info::setSeparator (std::string _sep) inline
Definition at line 103 of file info.hh.
References baseCheck(), check(), enable(), less(), prepare(), reset(), visit(), and zero().
visit()
virtual void Stats::Info::visit (Output & visitor) pure virtual
Visitor entry for outputing statistics data.
Implemented in Stats::ProxyInfo, Stats::InfoProxy< Stat, VectorDistInfo >, Stats::InfoProxy< Stat, ScalarInfo >, Stats::InfoProxy< Stat, SparseHistInfo >, Stats::InfoProxy< Stat, Vector2dInfo >, Stats::InfoProxy< Stat, DistInfo >, Stats::InfoProxy< Stat, VectorInfo >, and Stats::InfoProxy< Stat, FormulaInfo >.
Referenced by pybind_init_stats(), and setSeparator().
zero()
virtual bool Stats::Info::zero () const pure virtual
Returns
true if this stat has a value and satisfies its requirement as a prereq
Implemented in Stats::ProxyInfo, Stats::InfoProxy< Stat, VectorDistInfo >, Stats::InfoProxy< Stat, ScalarInfo >, Stats::InfoProxy< Stat, SparseHistInfo >, Stats::InfoProxy< Stat, Vector2dInfo >, Stats::InfoProxy< Stat, DistInfo >, Stats::InfoProxy< Stat, VectorInfo >, and Stats::InfoProxy< Stat, FormulaInfo >.
Referenced by Stats::HistStor::grow_out(), Stats::Text::noOutput(), pybind_init_stats(), and setSeparator().
Member Data Documentation
desc
std::string Stats::Info::desc
The description of the stat.
Definition at line 79 of file info.hh.
Referenced by Stats::Hdf5::appendStat(), Stats::DistPrint::init(), Stats::SparseHistPrint::init(), pybind_init_stats(), and Stats::Text::visit().
flags
Flags Stats::Info::flags
The formatting flags.
Definition at line 81 of file info.hh.
Referenced by baseCheck(), Stats::DistPrint::init(), Stats::SparseHistPrint::init(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::name(), Stats::Text::noOutput(), pybind_init_stats(), and Stats::Text::visit().
id
int Stats::Info::id
Definition at line 91 of file info.hh.
Referenced by pybind_init_stats().
id_count
int Stats::Info::id_count = 0 static
A unique stat ID for each stat in the simulator.
Can be used externally for lookups as well as for debugging.
Definition at line 90 of file info.hh.
Referenced by Info().
name
std::string Stats::Info::name
The name of the stat.
Definition at line 75 of file info.hh.
Referenced by Stats::Hdf5::appendStat(), Stats::DistPrint::DistPrint(), Stats::DistPrint::init(), Stats::SparseHistPrint::init(), less(), pybind_init_stats(), Stats::ScalarStatNode::str(), Stats::VectorStatNode::str(), Stats::validateStatName(), and Stats::Text::visit().
precision
int Stats::Info::precision
The display precision.
Definition at line 83 of file info.hh.
Referenced by Stats::DistPrint::init(), Stats::SparseHistPrint::init(), and Stats::Text::visit().
prereq
const Info* Stats::Info::prereq
A pointer to a prerequisite Stat.
Definition at line 85 of file info.hh.
Referenced by Stats::Text::noOutput().
separatorString
std::string Stats::Info::separatorString = "::" static
The separator string used for vectors, dist, etc.
Definition at line 77 of file info.hh.
Referenced by Stats::DistPrint::init(), Stats::SparseHistPrint::init(), and Stats::Text::visit().
storageParams
const StorageParams* Stats::Info::storageParams
Definition at line 94 of file info.hh.
Referenced by Stats::DistStor::prepare(), Stats::HistStor::prepare(), Stats::SampleStor::prepare(), Stats::AvgSampleStor::prepare(), Stats::DistStor::reset(), and Stats::HistStor::reset().
The documentation for this class was generated from the following files:
base/stats/info.hh
base/statistics.cc