gem5: ClockDomain Class Reference
ClockDomain Class Reference
The ClockDomain provides clock to group of clocked objects bundled under the same clock domain.
#include <clock_domain.hh>
Classes
struct ClockDomainStats
Public Types
typedef ClockDomainParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
ClockDomain (const Params *p, VoltageDomain *voltage_domain)
Tick clockPeriod () const
Get the clock period.
void registerWithClockDomain (Clocked *c)
Register a Clocked object with this ClockDomain.
VoltageDomain * voltageDomain () const
Get the voltage domain.
double voltage () const
Get the current voltage this clock domain operates at.
void addDerivedDomain (DerivedClockDomain *clock_domain)
Add a derived domain.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
Tick _clockPeriod
Pre-computed clock period in ticks.
VoltageDomain * _voltageDomain
Voltage domain this clock domain belongs to.
std::vector< DerivedClockDomain * > children
Pointers to potential derived clock domains so we can propagate changes.
std::vector< Clocked * > members
Pointers to members of this clock domain, so that when the clock period changes, we can update each member's tick.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
ClockDomain::ClockDomainStats stats
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
The ClockDomain provides clock to group of clocked objects bundled under the same clock domain.
The clock domains, in turn, are grouped into voltage domains. The clock domains provide support for a hierarchial structure with source and derived domains.
Definition at line 73 of file clock_domain.hh.
Member Typedef Documentation
Params
typedef ClockDomainParams ClockDomain::Params
Definition at line 102 of file clock_domain.hh.
Constructor & Destructor Documentation
ClockDomain()
ClockDomain::ClockDomain (const Params * p, VoltageDomain * voltage_domain)
Definition at line 67 of file clock_domain.cc.
Member Function Documentation
addDerivedDomain()
void ClockDomain::addDerivedDomain (DerivedClockDomain * clock_domain) inline
Add a derived domain.
Parameters
Derived domain to add as a child
Definition at line 144 of file clock_domain.hh.
Referenced by DerivedClockDomain::DerivedClockDomain().
clockPeriod()
Tick ClockDomain::clockPeriod () const inline
Get the clock period.
Returns
Clock period in ticks
Definition at line 110 of file clock_domain.hh.
References _clockPeriod.
Referenced by X86ISA::Interrupts::clockPeriod(), Clocked::clockPeriod(), SrcClockDomain::signalPerfLevelUpdate(), SrcClockDomain::SrcClockDomain(), DerivedClockDomain::updateClockPeriod(), and RealViewOsc::write().
registerWithClockDomain()
void ClockDomain::registerWithClockDomain (Clocked * c) inline
Register a Clocked object with this ClockDomain.
Parameters
Clocked to add as a member
Definition at line 117 of file clock_domain.hh.
References ArmISA::c.
Referenced by Clocked::Clocked().
voltage()
double ClockDomain::voltage () const
Get the current voltage this clock domain operates at.
Returns
Voltage applied to the clock domain
Definition at line 76 of file clock_domain.cc.
References _voltageDomain, and VoltageDomain::voltage().
Referenced by Clocked::voltage(), and voltageDomain().
voltageDomain()
VoltageDomain* ClockDomain::voltageDomain () const inline
Get the voltage domain.
Returns
Voltage domain this clock domain belongs to
Definition at line 129 of file clock_domain.hh.
References _voltageDomain, and voltage().
Referenced by VoltageDomain::registerSrcClockDom(), VoltageDomain::sanitiseVoltages(), SrcClockDomain::signalPerfLevelUpdate(), and DVFSHandler::voltageAtPerfLevel().
Member Data Documentation
_clockPeriod
Tick ClockDomain::_clockPeriod protected
Pre-computed clock period in ticks.
This is populated by the inheriting classes based on how their period is determined.
Definition at line 81 of file clock_domain.hh.
Referenced by ClockDomain::ClockDomainStats::ClockDomainStats(), clockPeriod(), SrcClockDomain::clockPeriod(), RealViewOsc::clockPeriod(), RealViewOsc::read(), RealViewOsc::RealViewOsc(), RealViewOsc::serialize(), RealViewOsc::unserialize(), and DerivedClockDomain::updateClockPeriod().
_voltageDomain
VoltageDomain* ClockDomain::_voltageDomain protected
Voltage domain this clock domain belongs to.
Definition at line 86 of file clock_domain.hh.
Referenced by voltage(), and voltageDomain().
children
std::vector<DerivedClockDomain*> ClockDomain::children protected
Pointers to potential derived clock domains so we can propagate changes.
Definition at line 92 of file clock_domain.hh.
Referenced by SrcClockDomain::clockPeriod(), RealViewOsc::clockPeriod(), and DerivedClockDomain::updateClockPeriod().
members
std::vector<Clocked *> ClockDomain::members protected
Pointers to members of this clock domain, so that when the clock period changes, we can update each member's tick.
Definition at line 98 of file clock_domain.hh.
Referenced by SrcClockDomain::clockPeriod(), RealViewOsc::clockPeriod(), RealViewOsc::startup(), and DerivedClockDomain::updateClockPeriod().
stats
ClockDomain::ClockDomainStats ClockDomain::stats private
The documentation for this class was generated from the following files:
sim/clock_domain.hh
sim/clock_domain.cc