gem5: OutputStream Class Reference
OutputStream Class Reference
#include <output.hh>
Public Member Functions
virtual ~OutputStream ()
std::ostream * stream () const
Get the output underlying output stream.
virtual bool recreateable () const
Can the file be recreated if the output directory is moved?
const std::string & name () const
Get the file name in the output directory.
Protected Member Functions
OutputStream (const std::string &name, std::ostream *stream)
Wrap an existing stream.
OutputStream (const OutputStream &f)
virtual void relocate (const OutputDirectory &dir)
Re-create the in a new location if recreateable.
Protected Attributes
const std::string _name
Name in output directory.
std::ostream *const _stream
Underlying output stream.
Friends
class OutputDirectory
Detailed Description
Definition at line 58 of file output.hh.
Constructor & Destructor Documentation
~OutputStream()
OutputStream::~OutputStream () virtual
Definition at line 73 of file output.cc.
OutputStream() [1/2]
OutputStream::OutputStream (const std::string & name, std::ostream * stream) protected
Wrap an existing stream.
Definition at line 68 of file output.cc.
OutputStream() [2/2]
OutputStream::OutputStream (const OutputStream & f) protected
Member Function Documentation
name()
const std::string& OutputStream::name () const inline
Get the file name in the output directory.
Definition at line 75 of file output.hh.
References _name.
Referenced by OutputDirectory::close(), OutputDirectory::createSubdirectory(), OutputDirectory::isAbsolute(), OutputDirectory::open(), OutputDirectory::resolve(), and sc_gem5::TraceFile::set_time_unit().
recreateable()
virtual bool OutputStream::recreateable () const inline virtual
Can the file be recreated if the output directory is moved?
Returns
true if the file will be created in the new location, false otherwise.
Reimplemented in OutputFile< StreamType >.
Definition at line 72 of file output.hh.
relocate()
void OutputStream::relocate (const OutputDirectory & dir) protected virtual
Re-create the in a new location if recreateable.
Reimplemented in OutputFile< StreamType >.
Definition at line 78 of file output.cc.
stream()
std::ostream* OutputStream::stream () const inline
Get the output underlying output stream.
Definition at line 64 of file output.hh.
References _stream.
Referenced by BaseCPU::BaseCPU(), Pl111::dmaDone(), X86ISA::GpuTLB::exitCallback(), Stats::initText(), output(), Linux::DmesgDumpEvent::process(), Linux::KernelPanicEvent::process(), DumpStatsPCEvent::process(), SimPoint::profile(), HDLcd::pxlFrameDone(), sc_gem5::TraceFile::stream(), Terminal::Terminal(), Terminal::writeData(), and PseudoInst::writefile().
Friends And Related Function Documentation
OutputDirectory
friend class OutputDirectory friend
Definition at line 78 of file output.hh.
Member Data Documentation
_name
const std::string OutputStream::_name protected
Name in output directory.
Definition at line 91 of file output.hh.
Referenced by name(), OutputFile< StreamType >::OutputFile(), and OutputFile< StreamType >::relocate().
_stream
std::ostream* const OutputStream::_stream protected
Underlying output stream.
Definition at line 94 of file output.hh.
Referenced by stream().
The documentation for this class was generated from the following files:
base/output.hh
base/output.cc