gem5: sc_core::sc_inout_rv< W > Class Template Reference
sc_core::sc_inout_rv< W > Class Template Reference
#include <sc_inout_rv.hh>
Public Member Functions
sc_inout_rv ()
sc_inout_rv (const char *name)
virtual ~sc_inout_rv ()
sc_inout_rv< W > & operator= (const sc_dt::sc_lv< W > &l)
sc_inout_rv< W > & operator= (const sc_signal_in_if< sc_dt::sc_lv< W >> &i)
sc_inout_rv< W > & operator= (const sc_port< sc_signal_in_if< sc_dt::sc_lv< W >>, 1 > &p)
sc_inout_rv< W > & operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_lv< W >>, 1 > &p)
sc_inout_rv< W > & operator= (const sc_inout_rv< W > &p)
virtual void end_of_elaboration ()
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_inout< sc_dt::sc_lv< W > >
sc_inout ()
sc_inout (const char *name)
sc_inout (const sc_signal_inout_if< sc_dt::sc_lv< W > > &interface)
sc_inout (const char *name, const sc_signal_inout_if< sc_dt::sc_lv< W > > &interface)
sc_inout (sc_port_b< sc_signal_inout_if< sc_dt::sc_lv< W > > > &parent)
sc_inout (const char *name, sc_port_b< sc_signal_inout_if< sc_dt::sc_lv< W > > > &parent)
sc_inout (sc_port< sc_signal_inout_if< sc_dt::sc_lv< W > >, 1 > &parent)
sc_inout (const char *name, sc_port< sc_signal_inout_if< sc_dt::sc_lv< W > >, 1 > &parent)
virtual ~sc_inout ()
void initialize (const sc_dt::sc_lv< W > &t)
void initialize (const sc_signal_in_if< sc_dt::sc_lv< W > > &i)
const sc_dt::sc_lv< W > & read () const
operator const sc_dt::sc_lv< W > & () const
void write (const sc_dt::sc_lv< W > &t)
sc_inout< sc_dt::sc_lv< W > > & operator= (const sc_dt::sc_lv< W > &t)
sc_inout< sc_dt::sc_lv< W > > & operator= (const sc_signal_in_if< sc_dt::sc_lv< W > > &i)
sc_inout< sc_dt::sc_lv< W > > & operator= (const sc_port< sc_signal_in_if< sc_dt::sc_lv< W > >, 1 > &p)
sc_inout< sc_dt::sc_lv< W > > & operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_lv< W > >, 1 > &p)
sc_inout< sc_dt::sc_lv< W > > & operator= (const sc_inout< sc_dt::sc_lv< W > > &p)
const sc_event & default_event () const
const sc_event & value_changed_event () const
bool event () const
sc_event_finder & value_changed () const
void add_trace (sc_trace_file *tf, const std::string &name) const
Public Member Functions inherited from sc_core::sc_port< IF, N, P >
sc_port ()
sc_port (const char *name)
virtual ~sc_port ()
sc_port (const IF &interface)
sc_port (const char *name, const IF &interface)
sc_port (sc_port_b< IF > &parent)
sc_port (const char *name, sc_port_b< IF > &parent)
sc_port (sc_port< IF, N, P > &parent)
sc_port (const char *name, sc_port< IF, N, P > &parent)
Public Member Functions inherited from sc_core::sc_port_b< IF >
void operator() (IF &i)
void operator() (sc_port_b< IF > &p)
virtual void bind (IF &i)
virtual void bind (sc_port_b< IF > &p)
IF * operator-> ()
const IF * operator-> () const
IF * operator[] (int n)
const IF * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_port_b< IF >
void before_end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
template<int W>
class sc_core::sc_inout_rv< W >
Definition at line 53 of file sc_inout_rv.hh.
Constructor & Destructor Documentation
sc_inout_rv() [1/2]
template<int W> sc_core::sc_inout_rv< W >::sc_inout_rv () inline
Definition at line 56 of file sc_inout_rv.hh.
sc_inout_rv() [2/2]
template<int W> sc_core::sc_inout_rv< W >::sc_inout_rv (const char * name) inline explicit
Definition at line 57 of file sc_inout_rv.hh.
~sc_inout_rv()
template<int W> virtual sc_core::sc_inout_rv< W >::~sc_inout_rv () inline virtual
Definition at line 58 of file sc_inout_rv.hh.
Member Function Documentation
end_of_elaboration()
template<int W> virtual void sc_core::sc_inout_rv< W >::end_of_elaboration () inline virtual
Reimplemented from sc_core::sc_inout< sc_dt::sc_lv< W > >.
Definition at line 92 of file sc_inout_rv.hh.
References name(), sc_core::SC_ID_RESOLVED_PORT_NOT_BOUND_, SC_REPORT_ERROR, and ArmISA::ss.
kind()
template<int W> virtual const char* sc_core::sc_inout_rv< W >::kind () const inline virtual
Reimplemented from sc_core::sc_inout< sc_dt::sc_lv< W > >.
Reimplemented in sc_core::sc_out_rv< W >.
Definition at line 102 of file sc_inout_rv.hh.
operator=() [1/5]
template<int W> sc_inout_rv<W>& sc_core::sc_inout_rv< W >::operator= (const sc_dt::sc_lv< W > & l) inline
Definition at line 61 of file sc_inout_rv.hh.
References sc_core::sc_inout< T >::write().
operator=() [2/5]
template<int W> sc_inout_rv<W>& sc_core::sc_inout_rv< W >::operator= (const sc_signal_in_if< sc_dt::sc_lv< W >> & i) inline
Definition at line 67 of file sc_inout_rv.hh.
References ArmISA::i, and sc_core::sc_inout< T >::write().
operator=() [3/5]
template<int W> sc_inout_rv<W>& sc_core::sc_inout_rv< W >::operator= (const sc_port< sc_signal_in_if< sc_dt::sc_lv< W >>, 1 > & p) inline
Definition at line 73 of file sc_inout_rv.hh.
References MipsISA::p, and sc_core::sc_inout< T >::write().
operator=() [4/5]
template<int W> sc_inout_rv<W>& sc_core::sc_inout_rv< W >::operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_lv< W >>, 1 > & p) inline
Definition at line 79 of file sc_inout_rv.hh.
References MipsISA::p, and sc_core::sc_inout< T >::write().
operator=() [5/5]
template<int W> sc_inout_rv<W>& sc_core::sc_inout_rv< W >::operator= (const sc_inout_rv< W > & p) inline
Definition at line 85 of file sc_inout_rv.hh.
References sc_core::sc_inout< sc_dt::sc_lv< W > >::read(), and sc_core::sc_inout< T >::write().
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_inout_rv.hh