gem5: LdsChunk Class Reference
LdsChunk Class Reference
this represents a slice of the overall LDS, intended to be associated with an individual workgroup
#include <lds_state.hh>
Public Member Functions
LdsChunk (const uint32_t x_size)
LdsChunk ()
template<class T >
T read (const uint32_t index)
a read operation
template<class T >
void write (const uint32_t index, const T value)
a write operation
std::vector< uint8_t >::size_type size () const
get the size of this chunk
Protected Attributes
std::vector< uint8_t > chunk
Detailed Description
this represents a slice of the overall LDS, intended to be associated with an individual workgroup
Definition at line 59 of file lds_state.hh.
Constructor & Destructor Documentation
LdsChunk() [1/2]
LdsChunk::LdsChunk (const uint32_t x_size) inline
Definition at line 62 of file lds_state.hh.
LdsChunk() [2/2]
LdsChunk::LdsChunk () inline
Definition at line 67 of file lds_state.hh.
Referenced by LdsState::reserveSpace().
Member Function Documentation
read()
template<class T > T LdsChunk::read (const uint32_t index) inline
a read operation
Definition at line 74 of file lds_state.hh.
References chunk, and fatal_if.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), and Wavefront::getContext().
size()
std::vector<uint8_t>::size_type LdsChunk::size () const inline
get the size of this chunk
Definition at line 99 of file lds_state.hh.
References chunk.
Referenced by Wavefront::getContext(), LdsState::releaseSpace(), LdsState::reserveSpace(), and Wavefront::setContext().
write()
template<class T > void LdsChunk::write (const uint32_t index, const T value) inline
a write operation
Definition at line 87 of file lds_state.hh.
References chunk, and fatal_if.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), and Wavefront::setContext().
Member Data Documentation
chunk
std::vector<uint8_t> LdsChunk::chunk protected
Definition at line 106 of file lds_state.hh.
Referenced by read(), size(), and write().
The documentation for this class was generated from the following file:
gpu-compute/lds_state.hh