gem5: WriteQueue Class Reference
WriteQueue Class Reference
A write queue for all eviction packets, i.e.
#include <write_queue.hh>
Public Member Functions
WriteQueue (const std::string &_label, int num_entries, int reserve)
Create a write queue with a given number of entries.
WriteQueueEntry * allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order)
Allocates a new WriteQueueEntry for the request and size.
void markInService (WriteQueueEntry *entry)
Mark the given entry as in service.
Public Member Functions inherited from Queue< WriteQueueEntry >
Queue (const std::string &_label, int num_entries, int reserve)
Create a queue with a given number of entries.
bool isEmpty () const
bool isFull () const
int numInService () const
WriteQueueEntry * findMatch (Addr blk_addr, bool is_secure, bool ignore_uncacheable=true) const
Find the first entry that matches the provided address.
bool trySatisfyFunctional (PacketPtr pkt)
WriteQueueEntry * findPending (const QueueEntry *entry) const
Find any pending requests that overlap the given request of a different queue.
WriteQueueEntry * getNext () const
Returns the WriteQueueEntry at the head of the readyList.
Tick nextReadyTime () const
void deallocate (WriteQueueEntry *entry)
Removes the given entry from the queue.
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Additional Inherited Members
Protected Member Functions inherited from Queue< WriteQueueEntry >
WriteQueueEntry ::Iterator addToReadyList (WriteQueueEntry *entry)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from Queue< WriteQueueEntry >
const std::string label
Local label (for functional print requests)
const int numEntries
The total number of entries in this queue.
const int numReserve
The number of entries to hold as a temporary overflow space.
std::vector< WriteQueueEntry > entries
Actual storage.
WriteQueueEntry ::List allocatedList
Holds pointers to all allocated entries.
WriteQueueEntry ::List readyList
Holds pointers to entries that haven't been sent downstream.
WriteQueueEntry ::List freeList
Holds non allocated entries.
int _numInService
The number of entries that are in service.
int allocated
The number of currently allocated entries.
Detailed Description
A write queue for all eviction packets, i.e.
writebacks and clean evictions, as well as uncacheable writes.
Definition at line 59 of file write_queue.hh.
Constructor & Destructor Documentation
WriteQueue()
WriteQueue::WriteQueue (const std::string & _label, int num_entries, int reserve)
Create a write queue with a given number of entries.
Parameters
num_entries The number of entries in this queue.
reserve The maximum number of entries needed to satisfy any access.
Definition at line 55 of file write_queue.cc.
Member Function Documentation
allocate()
WriteQueueEntry * WriteQueue::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter order)
Allocates a new WriteQueueEntry for the request and size.
This places the request as the first target in the WriteQueueEntry.
Parameters
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original write.
when_ready When is the WriteQueueEntry be ready to act upon.
order The logical order of this WriteQueueEntry
Returns
The a pointer to the WriteQueueEntry allocated.
Precondition
There are free entries.
Definition at line 61 of file write_queue.cc.
References Queue< WriteQueueEntry >::addToReadyList(), WriteQueueEntry::allocate(), Queue< WriteQueueEntry >::allocated, Queue< WriteQueueEntry >::allocatedList, Queue< WriteQueueEntry >::freeList, and WriteQueueEntry::readyIter.
Referenced by BaseCache::allocateWriteBuffer().
markInService()
void WriteQueue::markInService (WriteQueueEntry * entry)
Mark the given entry as in service.
This removes the entry from the readyList or deallocates the entry if it does not expect a response (writeback/eviction rather than an uncacheable write).
Parameters
entry The entry to mark in service.
Definition at line 78 of file write_queue.cc.
References Queue< WriteQueueEntry >::deallocate(), and WriteQueueEntry::popTarget().
Referenced by BaseCache::markInService().
The documentation for this class was generated from the following files:
mem/cache/write_queue.hh
mem/cache/write_queue.cc