gem5: RiscvISA::Reset Class Reference
RiscvISA::Reset Class Reference
#include <faults.hh>
Public Member Functions
Reset ()
FaultName name () const override
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr) override
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Private Attributes
const FaultName _name
Detailed Description
Definition at line 115 of file faults.hh.
Constructor & Destructor Documentation
Reset()
RiscvISA::Reset::Reset () inline
Definition at line 121 of file faults.hh.
Member Function Documentation
invoke()
void RiscvISA::Reset::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) override virtual
Reimplemented from FaultBase.
Definition at line 141 of file faults.cc.
References ThreadContext::getSystemPtr(), RiscvISA::MISCREG_MCAUSE, RiscvISA::MISCREG_PRV, RiscvISA::MISCREG_STATUS, RiscvISA::pc, ThreadContext::pcState(), RiscvISA::PRV_M, ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), and ArmISA::status.
name()
FaultName RiscvISA::Reset::name () const inline override virtual
Implements FaultBase.
Definition at line 122 of file faults.hh.
References RiscvISA::RiscvFault::_name, RiscvISA::RiscvFault::invoke(), and StaticInst::nullStaticInstPtr.
Member Data Documentation
_name
const FaultName RiscvISA::Reset::_name private
Definition at line 118 of file faults.hh.
The documentation for this class was generated from the following files:
arch/riscv/faults.hh
arch/riscv/faults.cc