gem5: O3ThreadContext< Impl > Class Template Reference
O3ThreadContext< Impl > Class Template Reference
Derived ThreadContext class for use with the O3CPU.
#include <cpu.hh>
Public Types
typedef Impl::O3CPU O3CPU
Public Types inherited from ThreadContext
enum Status { Active, Suspended, Halting, Halted }
Public Member Functions
bool schedule (PCEvent *e) override
bool remove (PCEvent *e) override
void scheduleInstCountEvent (Event *event, Tick count) override
void descheduleInstCountEvent (Event *event) override
Tick getCurrentInstCount () override
BaseTLB * getITBPtr () override
Returns a pointer to the ITB.
BaseTLB * getDTBPtr () override
Returns a pointer to the DTB.
CheckerCPU * getCheckerCpuPtr () override
TheISA::ISA * getIsaPtr () override
TheISA::Decoder * getDecoderPtr () override
BaseCPU * getCpuPtr () override
Returns a pointer to this CPU.
int cpuId () const override
Reads this CPU's ID.
uint32_t socketId () const override
Reads this CPU's Socket ID.
ContextID contextId () const override
void setContextId (ContextID id) override
int threadId () const override
Returns this thread's ID number.
void setThreadId (int id) override
System * getSystemPtr () override
Returns a pointer to the system.
::Kernel::Statistics * getKernelStats () override
Returns a pointer to this thread's kernel statistics.
Process * getProcessPtr () override
Returns a pointer to this thread's process.
void setProcessPtr (Process *p) override
PortProxy & getPhysProxy () override
PortProxy & getVirtProxy () override
void initMemProxies (ThreadContext *tc) override
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
Status status () const override
Returns this thread's status.
void setStatus (Status new_status) override
Sets this thread's status.
void activate () override
Set the status to Active.
void suspend () override
Set the status to Suspended.
void halt () override
Set the status to Halted.
void dumpFuncProfile () override
Dumps the function profiling information.
void takeOverFrom (ThreadContext *old_context) override
Takes over execution of a thread from another CPU.
void regStats (const std::string &name) override
Registers statistics associated with this TC.
Tick readLastActivate () override
Reads the last tick that this thread was activated on.
Tick readLastSuspend () override
Reads the last tick that this thread was suspended on.
void profileClear () override
Clears the function profiling information.
void profileSample () override
Samples the function profiling information.
void copyArchRegs (ThreadContext *tc) override
Copies the architectural registers from another TC into this TC.
void clearArchRegs () override
Resets all architectural registers to 0.
RegVal readReg (RegIndex reg_idx)
Reads an integer register.
RegVal readIntReg (RegIndex reg_idx) const override
RegVal readFloatReg (RegIndex reg_idx) const override
const VecRegContainer & readVecReg (const RegId &id) const override
VecRegContainer & getWritableVecReg (const RegId &id) override
Read vector register operand for modification, hierarchical indexing.
const VecElem & readVecElem (const RegId &reg) const override
const VecPredRegContainer & readVecPredReg (const RegId &id) const override
VecPredRegContainer & getWritableVecPredReg (const RegId &id) override
RegVal readCCReg (RegIndex reg_idx) const override
void setIntReg (RegIndex reg_idx, RegVal val) override
Sets an integer register to a value.
void setFloatReg (RegIndex reg_idx, RegVal val) override
void setVecReg (const RegId &reg, const VecRegContainer &val) override
void setVecElem (const RegId &reg, const VecElem &val) override
void setVecPredReg (const RegId &reg, const VecPredRegContainer &val) override
void setCCReg (RegIndex reg_idx, RegVal val) override
TheISA::PCState pcState () const override
Reads this thread's PC state.
void pcState (const TheISA::PCState &val) override
Sets this thread's PC state.
void pcStateNoRecord (const TheISA::PCState &val) override
Addr instAddr () const override
Reads this thread's PC.
Addr nextInstAddr () const override
Reads this thread's next PC.
MicroPC microPC () const override
Reads this thread's next PC.
RegVal readMiscRegNoEffect (RegIndex misc_reg) const override
Reads a miscellaneous register.
RegVal readMiscReg (RegIndex misc_reg) override
Reads a misc.
void setMiscRegNoEffect (RegIndex misc_reg, RegVal val) override
Sets a misc.
void setMiscReg (RegIndex misc_reg, RegVal val) override
Sets a misc.
RegId flattenRegId (const RegId &regId) const override
unsigned readStCondFailures () const override
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned sc_failures) override
Sets the number of consecutive store conditional failures.
void syscall (int64_t callnum, Fault *fault) override
Executes a syscall in SE mode.
Counter readFuncExeInst () const override
Reads the funcExeInst counter.
EndQuiesceEvent * getQuiesceEvent () override
Returns pointer to the quiesce event.
void conditionalSquash ()
check if the cpu is currently in state update mode and squash if not.
RegVal readIntRegFlat (RegIndex idx) const override
Flat register interfaces.
void setIntRegFlat (RegIndex idx, RegVal val) override
RegVal readFloatRegFlat (RegIndex idx) const override
void setFloatRegFlat (RegIndex idx, RegVal val) override
const VecRegContainer & readVecRegFlat (RegIndex idx) const override
VecRegContainer & getWritableVecRegFlat (RegIndex idx) override
Read vector register operand for modification, flat indexing.
void setVecRegFlat (RegIndex idx, const VecRegContainer &val) override
template<typename VecElem >
VecLaneT< VecElem, true > readVecLaneFlat (RegIndex idx, int lId) const
template<typename LD >
void setVecLaneFlat (int idx, int lId, const LD &val)
const VecElem & readVecElemFlat (RegIndex idx, const ElemIndex &elemIndex) const override
void setVecElemFlat (RegIndex idx, const ElemIndex &elemIdx, const VecElem &val) override
const VecPredRegContainer & readVecPredRegFlat (RegIndex idx) const override
VecPredRegContainer & getWritableVecPredRegFlat (RegIndex idx) override
void setVecPredRegFlat (RegIndex idx, const VecPredRegContainer &val) override
RegVal readCCRegFlat (RegIndex idx) const override
void setCCRegFlat (RegIndex idx, RegVal val) override
ConstVecLane8 readVec8BitLaneReg (const RegId &id) const override
Vector Register Lane Interfaces.
ConstVecLane16 readVec16BitLaneReg (const RegId &id) const override
Reads source vector 16bit operand.
ConstVecLane32 readVec32BitLaneReg (const RegId &id) const override
Reads source vector 32bit operand.
ConstVecLane64 readVec64BitLaneReg (const RegId &id) const override
Reads source vector 64bit operand.
void setVecLane (const RegId &reg, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector register.
void setVecLane (const RegId &reg, const LaneData< LaneSize::TwoByte > &val) override
void setVecLane (const RegId &reg, const LaneData< LaneSize::FourByte > &val) override
void setVecLane (const RegId &reg, const LaneData< LaneSize::EightByte > &val) override
Public Member Functions inherited from ThreadContext
virtual ~ThreadContext ()
void quiesce ()
Quiesce thread context.
void quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
void setNPC (Addr val)
virtual int exit ()
Public Attributes
O3CPU * cpu
Pointer to the CPU.
O3ThreadState< Impl > * thread
Pointer to the thread state that this TC corrseponds to.
Additional Inherited Members
Static Public Member Functions inherited from ThreadContext
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Protected Types inherited from ThreadContext
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
template<class Impl>
class O3ThreadContext< Impl >
Derived ThreadContext class for use with the O3CPU.
It provides the interface for any external objects to access a single thread's state and some general CPU state. Any time external objects try to update state through this interface, the CPU will create an event to squash all in-flight instructions in order to ensure state is maintained correctly. It must be defined specifically for the O3CPU because not all architectural state is located within the O3ThreadState (such as the commit PC, and registers), and specific actions must be taken when using this interface (such as squashing all in-flight instructions when doing a write to this interface).
Definition at line 76 of file cpu.hh.
Member Typedef Documentation
O3CPU
template<class Impl> typedef Impl::O3CPU O3ThreadContext< Impl >::O3CPU
Definition at line 73 of file thread_context.hh.
Member Function Documentation
activate()
template<class Impl > void O3ThreadContext< Impl >::activate () override virtual
Set the status to Active.
Implements ThreadContext.
Definition at line 88 of file thread_context_impl.hh.
References ThreadContext::Active, curTick(), and DPRINTF.
clearArchRegs()
template<class Impl > void O3ThreadContext< Impl >::clearArchRegs () override virtual
Resets all architectural registers to 0.
Implements ThreadContext.
Definition at line 201 of file thread_context_impl.hh.
conditionalSquash()
template<class Impl> void O3ThreadContext< Impl >::conditionalSquash () inline
check if the cpu is currently in state update mode and squash if not.
This function will return true if a trap is pending or if a fault or similar is currently writing to the thread context and doesn't want reset all the state (see noSquashFromTC).
Definition at line 471 of file thread_context.hh.
References O3ThreadState< Impl >::noSquashFromTC, ThreadState::threadId(), and O3ThreadState< Impl >::trapPending.
contextId()
template<class Impl> ContextID O3ThreadContext< Impl >::contextId () const inline override virtual
Implements ThreadContext.
Definition at line 137 of file thread_context.hh.
References ThreadState::contextId().
copyArchRegs()
template<class Impl > void O3ThreadContext< Impl >::copyArchRegs (ThreadContext * tc) override virtual
Copies the architectural registers from another TC into this TC.
Implements ThreadContext.
Definition at line 185 of file thread_context_impl.hh.
References AlphaISA::copyRegs(), FullSystem, ThreadContext::pcState(), and ThreadContext::readFuncExeInst().
cpuId()
template<class Impl> int O3ThreadContext< Impl >::cpuId () const inline override virtual
Reads this CPU's ID.
Implements ThreadContext.
Definition at line 132 of file thread_context.hh.
descheduleInstCountEvent()
template<class Impl> void O3ThreadContext< Impl >::descheduleInstCountEvent (Event * event) inline override virtual
Implements ThreadContext.
Definition at line 95 of file thread_context.hh.
dumpFuncProfile()
template<class Impl > void O3ThreadContext< Impl >::dumpFuncProfile () override virtual
Dumps the function profiling information.
Todo:
: Implement.
Implements ThreadContext.
Definition at line 65 of file thread_context_impl.hh.
flattenRegId()
template<class Impl > RegId O3ThreadContext< Impl >::flattenRegId (const RegId & regId) const override virtual
Implements ThreadContext.
Definition at line 339 of file thread_context_impl.hh.
getCheckerCpuPtr()
template<class Impl> CheckerCPU* O3ThreadContext< Impl >::getCheckerCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 114 of file thread_context.hh.
getCpuPtr()
template<class Impl> BaseCPU* O3ThreadContext< Impl >::getCpuPtr () inline override virtual
Returns a pointer to this CPU.
Implements ThreadContext.
Definition at line 129 of file thread_context.hh.
getCurrentInstCount()
template<class Impl> Tick O3ThreadContext< Impl >::getCurrentInstCount () inline override virtual
Implements ThreadContext.
Definition at line 100 of file thread_context.hh.
getDecoderPtr()
template<class Impl> TheISA::Decoder* O3ThreadContext< Impl >::getDecoderPtr () inline override virtual
Implements ThreadContext.
Definition at line 123 of file thread_context.hh.
References ThreadState::threadId().
getDTBPtr()
template<class Impl> BaseTLB* O3ThreadContext< Impl >::getDTBPtr () inline override virtual
Returns a pointer to the DTB.
Implements ThreadContext.
Definition at line 112 of file thread_context.hh.
getIsaPtr()
template<class Impl> TheISA::ISA* O3ThreadContext< Impl >::getIsaPtr () inline override virtual
Implements ThreadContext.
Definition at line 117 of file thread_context.hh.
References ThreadState::threadId().
getITBPtr()
template<class Impl> BaseTLB* O3ThreadContext< Impl >::getITBPtr () inline override virtual
Returns a pointer to the ITB.
Implements ThreadContext.
Definition at line 109 of file thread_context.hh.
getKernelStats()
template<class Impl> ::Kernel::Statistics* O3ThreadContext< Impl >::getKernelStats () inline override virtual
Returns a pointer to this thread's kernel statistics.
Implements ThreadContext.
Definition at line 150 of file thread_context.hh.
References ThreadState::kernelStats.
getPhysProxy()
template<class Impl> PortProxy& O3ThreadContext< Impl >::getPhysProxy () inline override virtual
Implements ThreadContext.
Definition at line 160 of file thread_context.hh.
References ThreadState::getPhysProxy().
getProcessPtr()
template<class Impl> Process* O3ThreadContext< Impl >::getProcessPtr () inline override virtual
Returns a pointer to this thread's process.
Implements ThreadContext.
Definition at line 156 of file thread_context.hh.
References ThreadState::getProcessPtr().
getQuiesceEvent()
template<class Impl> EndQuiesceEvent* O3ThreadContext< Impl >::getQuiesceEvent () inline override virtual
Returns pointer to the quiesce event.
Implements ThreadContext.
Definition at line 461 of file thread_context.hh.
References ThreadState::quiesceEvent.
getSystemPtr()
template<class Impl> System* O3ThreadContext< Impl >::getSystemPtr () inline override virtual
Returns a pointer to the system.
Implements ThreadContext.
Definition at line 146 of file thread_context.hh.
getVirtProxy()
template<class Impl > PortProxy & O3ThreadContext< Impl >::getVirtProxy () override virtual
Implements ThreadContext.
Definition at line 58 of file thread_context_impl.hh.
getWritableVecPredReg()
template<class Impl> VecPredRegContainer& O3ThreadContext< Impl >::getWritableVecPredReg (const RegId & id) inline override virtual
Implements ThreadContext.
Definition at line 326 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
getWritableVecPredRegFlat()
template<class Impl > TheISA::VecPredRegContainer & O3ThreadContext< Impl >::getWritableVecPredRegFlat (RegIndex idx) override virtual
Implements ThreadContext.
Definition at line 251 of file thread_context_impl.hh.
getWritableVecReg()
template<class Impl> VecRegContainer& O3ThreadContext< Impl >::getWritableVecReg (const RegId & id) inline override virtual
Read vector register operand for modification, hierarchical indexing.
Implements ThreadContext.
Definition at line 247 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::halt().
getWritableVecRegFlat()
template<class Impl > TheISA::VecRegContainer & O3ThreadContext< Impl >::getWritableVecRegFlat (RegIndex idx) override virtual
Read vector register operand for modification, flat indexing.
Implements ThreadContext.
Definition at line 229 of file thread_context_impl.hh.
halt()
template<class Impl > void O3ThreadContext< Impl >::halt () override virtual
Set the status to Halted.
Implements ThreadContext.
Definition at line 127 of file thread_context_impl.hh.
References DPRINTF, ThreadContext::Halted, and ThreadContext::Halting.
initMemProxies()
template<class Impl> void O3ThreadContext< Impl >::initMemProxies (ThreadContext * tc) inline override virtual
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
tc ThreadContext for the virtual-to-physical translation
Implements ThreadContext.
Definition at line 165 of file thread_context.hh.
References ThreadState::initMemProxies().
instAddr()
template<class Impl> Addr O3ThreadContext< Impl >::instAddr () const inline override virtual
Reads this thread's PC.
Implements ThreadContext.
Definition at line 391 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::setArchVecLane().
microPC()
template<class Impl> MicroPC O3ThreadContext< Impl >::microPC () const inline override virtual
Reads this thread's next PC.
Implements ThreadContext.
Definition at line 405 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::setArchVecLane().
nextInstAddr()
template<class Impl> Addr O3ThreadContext< Impl >::nextInstAddr () const inline override virtual
Reads this thread's next PC.
Implements ThreadContext.
Definition at line 398 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::setArchVecLane().
pcState() [1/2]
template<class Impl> TheISA::PCState O3ThreadContext< Impl >::pcState () const inline override virtual
Reads this thread's PC state.
Implements ThreadContext.
Definition at line 379 of file thread_context.hh.
References ThreadState::threadId(), and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setArchVecLane().
pcState() [2/2]
template<class Impl > void O3ThreadContext< Impl >::pcState (const TheISA::PCState & val) override virtual
Sets this thread's PC state.
Implements ThreadContext.
Definition at line 321 of file thread_context_impl.hh.
pcStateNoRecord()
template<class Impl > void O3ThreadContext< Impl >::pcStateNoRecord (const TheISA::PCState & val) override virtual
Implements ThreadContext.
Definition at line 330 of file thread_context_impl.hh.
profileClear()
template<class Impl > void O3ThreadContext< Impl >::profileClear () override virtual
Clears the function profiling information.
Implements ThreadContext.
Definition at line 171 of file thread_context_impl.hh.
profileSample()
template<class Impl > void O3ThreadContext< Impl >::profileSample () override virtual
Samples the function profiling information.
Implements ThreadContext.
Definition at line 178 of file thread_context_impl.hh.
readCCReg()
template<class Impl> RegVal O3ThreadContext< Impl >::readCCReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 332 of file thread_context.hh.
References CCRegClass, and MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
readCCRegFlat()
template<class Impl > RegVal O3ThreadContext< Impl >::readCCRegFlat (RegIndex idx) const override virtual
Implements ThreadContext.
Definition at line 258 of file thread_context_impl.hh.
readFloatReg()
template<class Impl> RegVal O3ThreadContext< Impl >::readFloatReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 231 of file thread_context.hh.
References FloatRegClass, and MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::halt().
readFloatRegFlat()
template<class Impl > RegVal O3ThreadContext< Impl >::readFloatRegFlat (RegIndex idx) const override virtual
Implements ThreadContext.
Definition at line 215 of file thread_context_impl.hh.
readFuncExeInst()
template<class Impl> Counter O3ThreadContext< Impl >::readFuncExeInst () const inline override virtual
Reads the funcExeInst counter.
Implements ThreadContext.
Definition at line 457 of file thread_context.hh.
References ThreadState::funcExeInst.
readIntReg()
template<class Impl> RegVal O3ThreadContext< Impl >::readIntReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 224 of file thread_context.hh.
References MipsISA::index, and IntRegClass.
Referenced by FullO3CPU< O3CPUImpl >::halt().
readIntRegFlat()
template<class Impl > RegVal O3ThreadContext< Impl >::readIntRegFlat (RegIndex idx) const override virtual
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenRegId()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implements ThreadContext.
Definition at line 208 of file thread_context_impl.hh.
readLastActivate()
template<class Impl > Tick O3ThreadContext< Impl >::readLastActivate () override virtual
Reads the last tick that this thread was activated on.
Implements ThreadContext.
Definition at line 157 of file thread_context_impl.hh.
readLastSuspend()
template<class Impl > Tick O3ThreadContext< Impl >::readLastSuspend () override virtual
Reads the last tick that this thread was suspended on.
Implements ThreadContext.
Definition at line 164 of file thread_context_impl.hh.
readMiscReg()
template<class Impl> RegVal O3ThreadContext< Impl >::readMiscReg (RegIndex misc_reg) inline override virtual
Reads a misc.
register, including any side-effects the read might have as defined by the architecture.
Implements ThreadContext.
Definition at line 420 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::halt().
readMiscRegNoEffect()
template<class Impl> RegVal O3ThreadContext< Impl >::readMiscRegNoEffect (RegIndex misc_reg) const inline override virtual
Reads a miscellaneous register.
Implements ThreadContext.
Definition at line 412 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::halt().
readReg()
template<class Impl> RegVal O3ThreadContext< Impl >::readReg (RegIndex reg_idx) inline
Reads an integer register.
Definition at line 218 of file thread_context.hh.
References MipsISA::index, and IntRegClass.
readStCondFailures()
template<class Impl> unsigned O3ThreadContext< Impl >::readStCondFailures () const inline override virtual
Returns the number of consecutive store conditional failures.
Implements ThreadContext.
Definition at line 437 of file thread_context.hh.
References ThreadState::storeCondFailures.
readVec16BitLaneReg()
template<class Impl> ConstVecLane16 O3ThreadContext< Impl >::readVec16BitLaneReg (const RegId & id) const inline override virtual
Reads source vector 16bit operand.
Implements ThreadContext.
Definition at line 264 of file thread_context.hh.
readVec32BitLaneReg()
template<class Impl> ConstVecLane32 O3ThreadContext< Impl >::readVec32BitLaneReg (const RegId & id) const inline override virtual
Reads source vector 32bit operand.
Implements ThreadContext.
Definition at line 272 of file thread_context.hh.
readVec64BitLaneReg()
template<class Impl> ConstVecLane64 O3ThreadContext< Impl >::readVec64BitLaneReg (const RegId & id) const inline override virtual
Reads source vector 64bit operand.
Implements ThreadContext.
Definition at line 280 of file thread_context.hh.
readVec8BitLaneReg()
template<class Impl> ConstVecLane8 O3ThreadContext< Impl >::readVec8BitLaneReg (const RegId & id) const inline override virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implements ThreadContext.
Definition at line 256 of file thread_context.hh.
readVecElem()
template<class Impl> const VecElem& O3ThreadContext< Impl >::readVecElem (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 314 of file thread_context.hh.
References RegId::elemIndex(), and MipsISA::index.
readVecElemFlat()
template<class Impl > const TheISA::VecElem & O3ThreadContext< Impl >::readVecElemFlat (RegIndex idx, const ElemIndex & elemIndex) const override virtual
Implements ThreadContext.
Definition at line 236 of file thread_context_impl.hh.
readVecLaneFlat()
template<class Impl> template<typename VecElem > VecLaneT<VecElem, true> O3ThreadContext< Impl >::readVecLaneFlat (RegIndex idx, int lId) const inline
Definition at line 490 of file thread_context.hh.
References ThreadState::threadId().
readVecPredReg()
template<class Impl> const VecPredRegContainer& O3ThreadContext< Impl >::readVecPredReg (const RegId & id) const inline override virtual
Implements ThreadContext.
Definition at line 320 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
readVecPredRegFlat()
template<class Impl > const TheISA::VecPredRegContainer & O3ThreadContext< Impl >::readVecPredRegFlat (RegIndex idx) const override virtual
Implements ThreadContext.
Definition at line 244 of file thread_context_impl.hh.
readVecReg()
template<class Impl> const VecRegContainer& O3ThreadContext< Impl >::readVecReg (const RegId & id) const inline override virtual
Implements ThreadContext.
Definition at line 238 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::halt().
readVecRegFlat()
template<class Impl > const TheISA::VecRegContainer & O3ThreadContext< Impl >::readVecRegFlat (RegIndex idx) const override virtual
Implements ThreadContext.
Definition at line 222 of file thread_context_impl.hh.
regStats()
template<class Impl > void O3ThreadContext< Impl >::regStats (const std::string & name) override virtual
Registers statistics associated with this TC.
Implements ThreadContext.
Definition at line 147 of file thread_context_impl.hh.
References FullSystem.
remove()
template<class Impl> bool O3ThreadContext< Impl >::remove (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 84 of file thread_context.hh.
References ArmISA::e.
schedule()
template<class Impl> bool O3ThreadContext< Impl >::schedule (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 79 of file thread_context.hh.
scheduleInstCountEvent()
template<class Impl> void O3ThreadContext< Impl >::scheduleInstCountEvent (Event * event, Tick count) inline override virtual
Implements ThreadContext.
Definition at line 90 of file thread_context.hh.
setCCReg()
template<class Impl> void O3ThreadContext< Impl >::setCCReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 372 of file thread_context.hh.
References CCRegClass, and MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setCCRegFlat()
template<class Impl > void O3ThreadContext< Impl >::setCCRegFlat (RegIndex idx, RegVal val) override virtual
Implements ThreadContext.
Definition at line 312 of file thread_context_impl.hh.
setContextId()
template<class Impl> void O3ThreadContext< Impl >::setContextId (ContextID id) inline override virtual
Implements ThreadContext.
Definition at line 139 of file thread_context.hh.
References ThreadState::setContextId().
setFloatReg()
template<class Impl> void O3ThreadContext< Impl >::setFloatReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 346 of file thread_context.hh.
References FloatRegClass, and MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setFloatRegFlat()
template<class Impl > void O3ThreadContext< Impl >::setFloatRegFlat (RegIndex idx, RegVal val) override virtual
Implements ThreadContext.
Definition at line 274 of file thread_context_impl.hh.
setIntReg()
template<class Impl> void O3ThreadContext< Impl >::setIntReg (RegIndex reg_idx, RegVal val) inline override virtual
Sets an integer register to a value.
Implements ThreadContext.
Definition at line 340 of file thread_context.hh.
References MipsISA::index, and IntRegClass.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setIntRegFlat()
template<class Impl > void O3ThreadContext< Impl >::setIntRegFlat (RegIndex idx, RegVal val) override virtual
Implements ThreadContext.
Definition at line 265 of file thread_context_impl.hh.
setMiscReg()
template<class Impl > void O3ThreadContext< Impl >::setMiscReg (RegIndex misc_reg, RegVal val) override virtual
Sets a misc.
register, including any side-effects the write might have as defined by the architecture.
Implements ThreadContext.
Definition at line 355 of file thread_context_impl.hh.
Referenced by FullO3CPU< O3CPUImpl >::halt().
setMiscRegNoEffect()
template<class Impl > void O3ThreadContext< Impl >::setMiscRegNoEffect (RegIndex misc_reg, RegVal val) override virtual
Sets a misc.
register.
Implements ThreadContext.
Definition at line 346 of file thread_context_impl.hh.
Referenced by FullO3CPU< O3CPUImpl >::halt().
setProcessPtr()
template<class Impl> void O3ThreadContext< Impl >::setProcessPtr (Process * p) inline override virtual
Implements ThreadContext.
Definition at line 158 of file thread_context.hh.
References ThreadState::setProcessPtr().
setStatus()
template<class Impl> void O3ThreadContext< Impl >::setStatus (Status new_status) inline override virtual
Sets this thread's status.
Implements ThreadContext.
Definition at line 175 of file thread_context.hh.
References MipsISA::halt, name(), ThreadState::setStatus(), and takeOverFrom().
setStCondFailures()
template<class Impl> void O3ThreadContext< Impl >::setStCondFailures (unsigned sc_failures) inline override virtual
Sets the number of consecutive store conditional failures.
Implements ThreadContext.
Definition at line 444 of file thread_context.hh.
References ThreadState::storeCondFailures.
setThreadId()
template<class Impl> void O3ThreadContext< Impl >::setThreadId (int id) inline override virtual
Implements ThreadContext.
Definition at line 143 of file thread_context.hh.
References ThreadState::setThreadId().
setVecElem()
template<class Impl> void O3ThreadContext< Impl >::setVecElem (const RegId & reg, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 359 of file thread_context.hh.
References RegId::elemIndex(), MipsISA::index, and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setVecElemFlat()
template<class Impl > void O3ThreadContext< Impl >::setVecElemFlat (RegIndex idx, const ElemIndex & elemIdx, const VecElem & val) override virtual
Implements ThreadContext.
Definition at line 293 of file thread_context_impl.hh.
setVecLane() [1/4]
template<class Impl> void O3ThreadContext< Impl >::setVecLane (const RegId & reg, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector register.
Implements ThreadContext.
Definition at line 288 of file thread_context.hh.
References RegId::elemIndex(), MipsISA::index, and X86ISA::val.
Referenced by FullO3CPU< O3CPUImpl >::setArchVecLane().
setVecLane() [2/4]
template<class Impl> void O3ThreadContext< Impl >::setVecLane (const RegId & reg, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 294 of file thread_context.hh.
References RegId::elemIndex(), MipsISA::index, and X86ISA::val.
setVecLane() [3/4]
template<class Impl> void O3ThreadContext< Impl >::setVecLane (const RegId & reg, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 300 of file thread_context.hh.
References RegId::elemIndex(), MipsISA::index, and X86ISA::val.
setVecLane() [4/4]
template<class Impl> void O3ThreadContext< Impl >::setVecLane (const RegId & reg, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 306 of file thread_context.hh.
References RegId::elemIndex(), MipsISA::index, and X86ISA::val.
setVecLaneFlat()
template<class Impl> template<typename LD > void O3ThreadContext< Impl >::setVecLaneFlat (int idx, int lId, const LD & val) inline
Definition at line 498 of file thread_context.hh.
References ThreadState::threadId(), and X86ISA::val.
setVecPredReg()
template<class Impl> void O3ThreadContext< Impl >::setVecPredReg (const RegId & reg, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 365 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setVecPredRegFlat()
template<class Impl > void O3ThreadContext< Impl >::setVecPredRegFlat (RegIndex idx, const VecPredRegContainer & val) override virtual
Implements ThreadContext.
Definition at line 302 of file thread_context_impl.hh.
setVecReg()
template<class Impl> void O3ThreadContext< Impl >::setVecReg (const RegId & reg, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 353 of file thread_context.hh.
References MipsISA::index.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane().
setVecRegFlat()
template<class Impl > void O3ThreadContext< Impl >::setVecRegFlat (RegIndex idx, const VecRegContainer & val) override virtual
Implements ThreadContext.
Definition at line 283 of file thread_context_impl.hh.
socketId()
template<class Impl> uint32_t O3ThreadContext< Impl >::socketId () const inline override virtual
Reads this CPU's Socket ID.
Implements ThreadContext.
Definition at line 135 of file thread_context.hh.
status()
template<class Impl> Status O3ThreadContext< Impl >::status () const inline override virtual
Returns this thread's status.
Implements ThreadContext.
Definition at line 171 of file thread_context.hh.
References ThreadState::status().
suspend()
template<class Impl > void O3ThreadContext< Impl >::suspend () override virtual
Set the status to Suspended.
Implements ThreadContext.
Definition at line 105 of file thread_context_impl.hh.
References curTick(), DPRINTF, and ThreadContext::Suspended.
syscall()
template<class Impl> void O3ThreadContext< Impl >::syscall (int64_t callnum, Fault * fault) inline override virtual
Executes a syscall in SE mode.
Implements ThreadContext.
Definition at line 451 of file thread_context.hh.
References ThreadState::threadId().
Referenced by FullO3CPU< O3CPUImpl >::isDraining().
takeOverFrom()
template<class Impl > void O3ThreadContext< Impl >::takeOverFrom (ThreadContext * old_context) override virtual
Takes over execution of a thread from another CPU.
Implements ThreadContext.
Definition at line 72 of file thread_context_impl.hh.
References ThreadContext::getDecoderPtr(), ThreadContext::getKernelStats(), ThreadContext::readFuncExeInst(), and takeOverFrom().
threadId()
template<class Impl> int O3ThreadContext< Impl >::threadId () const inline override virtual
Returns this thread's ID number.
Implements ThreadContext.
Definition at line 142 of file thread_context.hh.
References ThreadState::threadId().
Member Data Documentation
cpu
template<class Impl> O3CPU* O3ThreadContext< Impl >::cpu
Pointer to the CPU.
Definition at line 76 of file thread_context.hh.
Referenced by FullO3CPU< O3CPUImpl >::FullO3CPU().
thread
template<class Impl> O3ThreadState<Impl>* O3ThreadContext< Impl >::thread
Pointer to the thread state that this TC corrseponds to.
Definition at line 106 of file thread_context.hh.
Referenced by FullO3CPU< O3CPUImpl >::FullO3CPU(), and FullO3CPU< O3CPUImpl >::tcBase().
The documentation for this class was generated from the following files:
cpu/o3/cpu.hh
cpu/o3/thread_context.hh
cpu/o3/thread_context_impl.hh