gem5: CheckerThreadContext< TC > Class Template Reference
CheckerThreadContext< TC > Class Template Reference
Derived ThreadContext class for use with the Checker.
#include <thread_context.hh>
Public Member Functions
CheckerThreadContext (TC *actual_tc, CheckerCPU *checker_cpu)
bool schedule (PCEvent *e) override
bool remove (PCEvent *e) override
void scheduleInstCountEvent (Event *event, Tick count) override
void descheduleInstCountEvent (Event *event) override
Tick getCurrentInstCount () override
BaseCPU * getCpuPtr () override
uint32_t socketId () const override
int cpuId () const override
ContextID contextId () const override
void setContextId (ContextID id) override
int threadId () const override
Returns this thread's ID number.
void setThreadId (int id) override
BaseTLB * getITBPtr () override
BaseTLB * getDTBPtr () override
CheckerCPU * getCheckerCpuPtr () override
TheISA::ISA * getIsaPtr () override
TheISA::Decoder * getDecoderPtr () override
System * getSystemPtr () override
::Kernel::Statistics * getKernelStats () override
Process * getProcessPtr () override
void setProcessPtr (Process *p) override
PortProxy & getPhysProxy () override
PortProxy & getVirtProxy () override
void initMemProxies (ThreadContext *tc) override
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
void connectMemPorts (ThreadContext *tc)
void syscall (int64_t callnum, Fault *fault) override
Executes a syscall in SE mode.
Status status () const override
void setStatus (Status new_status) override
void activate () override
Set the status to Active.
void suspend () override
Set the status to Suspended.
void halt () override
Set the status to Halted.
void dumpFuncProfile () override
void takeOverFrom (ThreadContext *oldContext) override
void regStats (const std::string &name) override
EndQuiesceEvent * getQuiesceEvent () override
Tick readLastActivate () override
Tick readLastSuspend () override
void profileClear () override
void profileSample () override
void copyArchRegs (ThreadContext *tc) override
void clearArchRegs () override
RegVal readIntReg (RegIndex reg_idx) const override
RegVal readFloatReg (RegIndex reg_idx) const override
const VecRegContainer & readVecReg (const RegId &reg) const override
VecRegContainer & getWritableVecReg (const RegId &reg) override
Read vector register for modification, hierarchical indexing.
const VecElem & readVecElem (const RegId &reg) const override
const VecPredRegContainer & readVecPredReg (const RegId &reg) const override
VecPredRegContainer & getWritableVecPredReg (const RegId &reg) override
RegVal readCCReg (RegIndex reg_idx) const override
void setIntReg (RegIndex reg_idx, RegVal val) override
void setFloatReg (RegIndex reg_idx, RegVal val) override
void setVecReg (const RegId &reg, const VecRegContainer &val) override
void setVecElem (const RegId &reg, const VecElem &val) override
void setVecPredReg (const RegId &reg, const VecPredRegContainer &val) override
void setCCReg (RegIndex reg_idx, RegVal val) override
TheISA::PCState pcState () const override
Reads this thread's PC state.
void pcState (const TheISA::PCState &val) override
Sets this thread's PC state.
void setNPC (Addr val)
void pcStateNoRecord (const TheISA::PCState &val) override
Addr instAddr () const override
Reads this thread's PC.
Addr nextInstAddr () const override
Reads this thread's next PC.
MicroPC microPC () const override
Reads this thread's next PC.
RegVal readMiscRegNoEffect (RegIndex misc_reg) const override
RegVal readMiscReg (RegIndex misc_reg) override
void setMiscRegNoEffect (RegIndex misc_reg, RegVal val) override
void setMiscReg (RegIndex misc_reg, RegVal val) override
RegId flattenRegId (const RegId &regId) const override
unsigned readStCondFailures () const override
void setStCondFailures (unsigned sc_failures) override
Counter readFuncExeInst () const override
RegVal readIntRegFlat (RegIndex idx) const override
Flat register interfaces.
void setIntRegFlat (RegIndex idx, RegVal val) override
RegVal readFloatRegFlat (RegIndex idx) const override
void setFloatRegFlat (RegIndex idx, RegVal val) override
const VecRegContainer & readVecRegFlat (RegIndex idx) const override
VecRegContainer & getWritableVecRegFlat (RegIndex idx) override
Read vector register for modification, flat indexing.
void setVecRegFlat (RegIndex idx, const VecRegContainer &val) override
const VecElem & readVecElemFlat (RegIndex idx, const ElemIndex &elem_idx) const override
void setVecElemFlat (RegIndex idx, const ElemIndex &elem_idx, const VecElem &val) override
const VecPredRegContainer & readVecPredRegFlat (RegIndex idx) const override
VecPredRegContainer & getWritableVecPredRegFlat (RegIndex idx) override
void setVecPredRegFlat (RegIndex idx, const VecPredRegContainer &val) override
RegVal readCCRegFlat (RegIndex idx) const override
void setCCRegFlat (RegIndex idx, RegVal val) override
ConstVecLane8 readVec8BitLaneReg (const RegId &reg) const override
Vector Register Lane Interfaces.
ConstVecLane16 readVec16BitLaneReg (const RegId &reg) const override
Reads source vector 16bit operand.
ConstVecLane32 readVec32BitLaneReg (const RegId &reg) const override
Reads source vector 32bit operand.
ConstVecLane64 readVec64BitLaneReg (const RegId &reg) const override
Reads source vector 64bit operand.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector register.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::TwoByte > &val) override
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::FourByte > &val) override
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::EightByte > &val) override
Public Member Functions inherited from ThreadContext
virtual ~ThreadContext ()
void quiesce ()
Quiesce thread context.
void quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
void setNPC (Addr val)
virtual int exit ()
Private Attributes
TC * actualTC
The main CPU's ThreadContext, or class that implements the ThreadContext interface.
SimpleThread * checkerTC
The checker's own SimpleThread.
CheckerCPU * checkerCPU
Pointer to the checker CPU.
Additional Inherited Members
Public Types inherited from ThreadContext
enum Status { Active, Suspended, Halting, Halted }
Static Public Member Functions inherited from ThreadContext
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Protected Types inherited from ThreadContext
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
template<class TC>
class CheckerThreadContext< TC >
Derived ThreadContext class for use with the Checker.
The template parameter is the ThreadContext class used by the specific CPU being verified. This CheckerThreadContext is then used by the main CPU in place of its usual ThreadContext class. It handles updating the checker's state any time state is updated externally through the ThreadContext.
Definition at line 71 of file thread_context.hh.
Constructor & Destructor Documentation
CheckerThreadContext()
template<class TC> CheckerThreadContext< TC >::CheckerThreadContext (TC * actual_tc, CheckerCPU * checker_cpu) inline
Definition at line 74 of file thread_context.hh.
Member Function Documentation
activate()
template<class TC> void CheckerThreadContext< TC >::activate () inline override virtual
Set the status to Active.
Implements ThreadContext.
Definition at line 202 of file thread_context.hh.
clearArchRegs()
template<class TC> void CheckerThreadContext< TC >::clearArchRegs () inline override virtual
Implements ThreadContext.
Definition at line 247 of file thread_context.hh.
References SimpleThread::clearArchRegs().
connectMemPorts()
template<class TC> void CheckerThreadContext< TC >::connectMemPorts (ThreadContext * tc) inline
Definition at line 180 of file thread_context.hh.
contextId()
template<class TC> ContextID CheckerThreadContext< TC >::contextId () const inline override virtual
Implements ThreadContext.
Definition at line 117 of file thread_context.hh.
copyArchRegs()
template<class TC> void CheckerThreadContext< TC >::copyArchRegs (ThreadContext * tc) inline override virtual
Implements ThreadContext.
Definition at line 240 of file thread_context.hh.
References SimpleThread::copyArchRegs().
cpuId()
template<class TC> int CheckerThreadContext< TC >::cpuId () const inline override virtual
Implements ThreadContext.
Definition at line 115 of file thread_context.hh.
descheduleInstCountEvent()
template<class TC> void CheckerThreadContext< TC >::descheduleInstCountEvent (Event * event) inline override virtual
Implements ThreadContext.
Definition at line 101 of file thread_context.hh.
dumpFuncProfile()
template<class TC> void CheckerThreadContext< TC >::dumpFuncProfile () inline override virtual
Implements ThreadContext.
Definition at line 210 of file thread_context.hh.
flattenRegId()
template<class TC> RegId CheckerThreadContext< TC >::flattenRegId (const RegId & regId) const inline override virtual
Implements ThreadContext.
Definition at line 473 of file thread_context.hh.
getCheckerCpuPtr()
template<class TC> CheckerCPU* CheckerThreadContext< TC >::getCheckerCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 140 of file thread_context.hh.
getCpuPtr()
template<class TC> BaseCPU* CheckerThreadContext< TC >::getCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 111 of file thread_context.hh.
getCurrentInstCount()
template<class TC> Tick CheckerThreadContext< TC >::getCurrentInstCount () inline override virtual
Implements ThreadContext.
Definition at line 106 of file thread_context.hh.
getDecoderPtr()
template<class TC> TheISA::Decoder* CheckerThreadContext< TC >::getDecoderPtr () inline override virtual
Implements ThreadContext.
Definition at line 148 of file thread_context.hh.
getDTBPtr()
template<class TC> BaseTLB* CheckerThreadContext< TC >::getDTBPtr () inline override virtual
Implements ThreadContext.
Definition at line 137 of file thread_context.hh.
getIsaPtr()
template<class TC> TheISA::ISA* CheckerThreadContext< TC >::getIsaPtr () inline override virtual
Implements ThreadContext.
Definition at line 145 of file thread_context.hh.
getITBPtr()
template<class TC> BaseTLB* CheckerThreadContext< TC >::getITBPtr () inline override virtual
Implements ThreadContext.
Definition at line 135 of file thread_context.hh.
getKernelStats()
template<class TC> ::Kernel::Statistics* CheckerThreadContext< TC >::getKernelStats () inline override virtual
Implements ThreadContext.
Definition at line 156 of file thread_context.hh.
getPhysProxy()
template<class TC> PortProxy& CheckerThreadContext< TC >::getPhysProxy () inline override virtual
Implements ThreadContext.
Definition at line 165 of file thread_context.hh.
getProcessPtr()
template<class TC> Process* CheckerThreadContext< TC >::getProcessPtr () inline override virtual
Implements ThreadContext.
Definition at line 161 of file thread_context.hh.
getQuiesceEvent()
template<class TC> EndQuiesceEvent* CheckerThreadContext< TC >::getQuiesceEvent () inline override virtual
Implements ThreadContext.
Definition at line 227 of file thread_context.hh.
getSystemPtr()
template<class TC> System* CheckerThreadContext< TC >::getSystemPtr () inline override virtual
Implements ThreadContext.
Definition at line 153 of file thread_context.hh.
getVirtProxy()
template<class TC> PortProxy& CheckerThreadContext< TC >::getVirtProxy () inline override virtual
Implements ThreadContext.
Definition at line 168 of file thread_context.hh.
getWritableVecPredReg()
template<class TC> VecPredRegContainer& CheckerThreadContext< TC >::getWritableVecPredReg (const RegId & reg) inline override virtual
Implements ThreadContext.
Definition at line 353 of file thread_context.hh.
getWritableVecPredRegFlat()
template<class TC> VecPredRegContainer& CheckerThreadContext< TC >::getWritableVecPredRegFlat (RegIndex idx) inline override virtual
Implements ThreadContext.
Definition at line 561 of file thread_context.hh.
getWritableVecReg()
template<class TC> VecRegContainer& CheckerThreadContext< TC >::getWritableVecReg (const RegId & reg) inline override virtual
Read vector register for modification, hierarchical indexing.
Implements ThreadContext.
Definition at line 278 of file thread_context.hh.
getWritableVecRegFlat()
template<class TC> VecRegContainer& CheckerThreadContext< TC >::getWritableVecRegFlat (RegIndex idx) inline override virtual
Read vector register for modification, flat indexing.
Implements ThreadContext.
Definition at line 530 of file thread_context.hh.
halt()
template<class TC> void CheckerThreadContext< TC >::halt () inline override virtual
Set the status to Halted.
Implements ThreadContext.
Definition at line 208 of file thread_context.hh.
initMemProxies()
template<class TC> void CheckerThreadContext< TC >::initMemProxies (ThreadContext * tc) inline override virtual
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
tc ThreadContext for the virtual-to-physical translation
Implements ThreadContext.
Definition at line 174 of file thread_context.hh.
instAddr()
template<class TC> Addr CheckerThreadContext< TC >::instAddr () const inline override virtual
Reads this thread's PC.
Implements ThreadContext.
Definition at line 434 of file thread_context.hh.
microPC()
template<class TC> MicroPC CheckerThreadContext< TC >::microPC () const inline override virtual
Reads this thread's next PC.
Implements ThreadContext.
Definition at line 440 of file thread_context.hh.
nextInstAddr()
template<class TC> Addr CheckerThreadContext< TC >::nextInstAddr () const inline override virtual
Reads this thread's next PC.
Implements ThreadContext.
Definition at line 437 of file thread_context.hh.
pcState() [1/2]
template<class TC> TheISA::PCState CheckerThreadContext< TC >::pcState () const inline override virtual
Reads this thread's PC state.
Implements ThreadContext.
Definition at line 407 of file thread_context.hh.
pcState() [2/2]
template<class TC> void CheckerThreadContext< TC >::pcState (const TheISA::PCState & val) inline override virtual
Sets this thread's PC state.
Implements ThreadContext.
Definition at line 411 of file thread_context.hh.
References DPRINTF, SimpleThread::pcState(), and CheckerCPU::recordPCChange().
pcStateNoRecord()
template<class TC> void CheckerThreadContext< TC >::pcStateNoRecord (const TheISA::PCState & val) inline override virtual
Implements ThreadContext.
Definition at line 428 of file thread_context.hh.
profileClear()
template<class TC> void CheckerThreadContext< TC >::profileClear () inline override virtual
Implements ThreadContext.
Definition at line 235 of file thread_context.hh.
profileSample()
template<class TC> void CheckerThreadContext< TC >::profileSample () inline override virtual
Implements ThreadContext.
Definition at line 236 of file thread_context.hh.
readCCReg()
template<class TC> RegVal CheckerThreadContext< TC >::readCCReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 359 of file thread_context.hh.
readCCRegFlat()
template<class TC> RegVal CheckerThreadContext< TC >::readCCRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 573 of file thread_context.hh.
readFloatReg()
template<class TC> RegVal CheckerThreadContext< TC >::readFloatReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 263 of file thread_context.hh.
readFloatRegFlat()
template<class TC> RegVal CheckerThreadContext< TC >::readFloatRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 509 of file thread_context.hh.
readFuncExeInst()
template<class TC> Counter CheckerThreadContext< TC >::readFuncExeInst () const inline override virtual
Implements ThreadContext.
Definition at line 491 of file thread_context.hh.
readIntReg()
template<class TC> RegVal CheckerThreadContext< TC >::readIntReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 257 of file thread_context.hh.
readIntRegFlat()
template<class TC> RegVal CheckerThreadContext< TC >::readIntRegFlat (RegIndex idx) const inline override virtual
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenRegId()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implements ThreadContext.
Definition at line 497 of file thread_context.hh.
readLastActivate()
template<class TC> Tick CheckerThreadContext< TC >::readLastActivate () inline override virtual
Implements ThreadContext.
Definition at line 232 of file thread_context.hh.
readLastSuspend()
template<class TC> Tick CheckerThreadContext< TC >::readLastSuspend () inline override virtual
Implements ThreadContext.
Definition at line 233 of file thread_context.hh.
readMiscReg()
template<class TC> RegVal CheckerThreadContext< TC >::readMiscReg (RegIndex misc_reg) inline override virtual
Implements ThreadContext.
Definition at line 449 of file thread_context.hh.
readMiscRegNoEffect()
template<class TC> RegVal CheckerThreadContext< TC >::readMiscRegNoEffect (RegIndex misc_reg) const inline override virtual
Implements ThreadContext.
Definition at line 443 of file thread_context.hh.
readStCondFailures()
template<class TC> unsigned CheckerThreadContext< TC >::readStCondFailures () const inline override virtual
Implements ThreadContext.
Definition at line 479 of file thread_context.hh.
readVec16BitLaneReg()
template<class TC> ConstVecLane16 CheckerThreadContext< TC >::readVec16BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 16bit operand.
Implements ThreadContext.
Definition at line 294 of file thread_context.hh.
readVec32BitLaneReg()
template<class TC> ConstVecLane32 CheckerThreadContext< TC >::readVec32BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 32bit operand.
Implements ThreadContext.
Definition at line 301 of file thread_context.hh.
readVec64BitLaneReg()
template<class TC> ConstVecLane64 CheckerThreadContext< TC >::readVec64BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 64bit operand.
Implements ThreadContext.
Definition at line 308 of file thread_context.hh.
readVec8BitLaneReg()
template<class TC> ConstVecLane8 CheckerThreadContext< TC >::readVec8BitLaneReg (const RegId & reg) const inline override virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implements ThreadContext.
Definition at line 287 of file thread_context.hh.
readVecElem()
template<class TC> const VecElem& CheckerThreadContext< TC >::readVecElem (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 341 of file thread_context.hh.
readVecElemFlat()
template<class TC> const VecElem& CheckerThreadContext< TC >::readVecElemFlat (RegIndex idx, const ElemIndex & elem_idx) const inline override virtual
Implements ThreadContext.
Definition at line 542 of file thread_context.hh.
readVecPredReg()
template<class TC> const VecPredRegContainer& CheckerThreadContext< TC >::readVecPredReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 347 of file thread_context.hh.
readVecPredRegFlat()
template<class TC> const VecPredRegContainer& CheckerThreadContext< TC >::readVecPredRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 555 of file thread_context.hh.
readVecReg()
template<class TC> const VecRegContainer& CheckerThreadContext< TC >::readVecReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 269 of file thread_context.hh.
readVecRegFlat()
template<class TC> const VecRegContainer& CheckerThreadContext< TC >::readVecRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 521 of file thread_context.hh.
regStats()
template<class TC> void CheckerThreadContext< TC >::regStats (const std::string & name) inline override virtual
Implements ThreadContext.
Definition at line 220 of file thread_context.hh.
References SimpleThread::regStats().
remove()
template<class TC> bool CheckerThreadContext< TC >::remove (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 93 of file thread_context.hh.
References ArmISA::e.
schedule()
template<class TC> bool CheckerThreadContext< TC >::schedule (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 92 of file thread_context.hh.
scheduleInstCountEvent()
template<class TC> void CheckerThreadContext< TC >::scheduleInstCountEvent (Event * event, Tick count) inline override virtual
Implements ThreadContext.
Definition at line 96 of file thread_context.hh.
setCCReg()
template<class TC> void CheckerThreadContext< TC >::setCCReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 400 of file thread_context.hh.
References SimpleThread::setCCReg().
setCCRegFlat()
template<class TC> void CheckerThreadContext< TC >::setCCRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 579 of file thread_context.hh.
setContextId()
template<class TC> void CheckerThreadContext< TC >::setContextId (ContextID id) inline override virtual
Implements ThreadContext.
Definition at line 120 of file thread_context.hh.
References SimpleThread::setContextId().
setFloatReg()
template<class TC> void CheckerThreadContext< TC >::setFloatReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 372 of file thread_context.hh.
References SimpleThread::setFloatReg().
setFloatRegFlat()
template<class TC> void CheckerThreadContext< TC >::setFloatRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 515 of file thread_context.hh.
setIntReg()
template<class TC> void CheckerThreadContext< TC >::setIntReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 365 of file thread_context.hh.
References SimpleThread::setIntReg().
setIntRegFlat()
template<class TC> void CheckerThreadContext< TC >::setIntRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 503 of file thread_context.hh.
setMiscReg()
template<class TC> void CheckerThreadContext< TC >::setMiscReg (RegIndex misc_reg, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 464 of file thread_context.hh.
References DPRINTF, and SimpleThread::setMiscReg().
setMiscRegNoEffect()
template<class TC> void CheckerThreadContext< TC >::setMiscRegNoEffect (RegIndex misc_reg, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 455 of file thread_context.hh.
References DPRINTF, and SimpleThread::setMiscRegNoEffect().
setNPC()
template<class TC> void CheckerThreadContext< TC >::setNPC (Addr val) inline
Definition at line 421 of file thread_context.hh.
References ThreadContext::setNPC().
setProcessPtr()
template<class TC> void CheckerThreadContext< TC >::setProcessPtr (Process * p) inline override virtual
Implements ThreadContext.
Definition at line 163 of file thread_context.hh.
setStatus()
template<class TC> void CheckerThreadContext< TC >::setStatus (Status new_status) inline override virtual
Implements ThreadContext.
Definition at line 195 of file thread_context.hh.
References SimpleThread::setStatus().
setStCondFailures()
template<class TC> void CheckerThreadContext< TC >::setStCondFailures (unsigned sc_failures) inline override virtual
Implements ThreadContext.
Definition at line 485 of file thread_context.hh.
setThreadId()
template<class TC> void CheckerThreadContext< TC >::setThreadId (int id) inline override virtual
Implements ThreadContext.
Definition at line 129 of file thread_context.hh.
References SimpleThread::setThreadId().
setVecElem()
template<class TC> void CheckerThreadContext< TC >::setVecElem (const RegId & reg, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 386 of file thread_context.hh.
References SimpleThread::setVecElem().
setVecElemFlat()
template<class TC> void CheckerThreadContext< TC >::setVecElemFlat (RegIndex idx, const ElemIndex & elem_idx, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 548 of file thread_context.hh.
setVecLane() [1/4]
template<class TC> virtual void CheckerThreadContext< TC >::setVecLane (const RegId & reg, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector register.
Implements ThreadContext.
Definition at line 315 of file thread_context.hh.
setVecLane() [2/4]
template<class TC> virtual void CheckerThreadContext< TC >::setVecLane (const RegId & reg, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 321 of file thread_context.hh.
setVecLane() [3/4]
template<class TC> virtual void CheckerThreadContext< TC >::setVecLane (const RegId & reg, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 327 of file thread_context.hh.
setVecLane() [4/4]
template<class TC> virtual void CheckerThreadContext< TC >::setVecLane (const RegId & reg, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 333 of file thread_context.hh.
setVecPredReg()
template<class TC> void CheckerThreadContext< TC >::setVecPredReg (const RegId & reg, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 393 of file thread_context.hh.
References SimpleThread::setVecPredReg().
setVecPredRegFlat()
template<class TC> void CheckerThreadContext< TC >::setVecPredRegFlat (RegIndex idx, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 567 of file thread_context.hh.
setVecReg()
template<class TC> void CheckerThreadContext< TC >::setVecReg (const RegId & reg, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 379 of file thread_context.hh.
References SimpleThread::setVecReg().
setVecRegFlat()
template<class TC> void CheckerThreadContext< TC >::setVecRegFlat (RegIndex idx, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 536 of file thread_context.hh.
socketId()
template<class TC> uint32_t CheckerThreadContext< TC >::socketId () const inline override virtual
Implements ThreadContext.
Definition at line 113 of file thread_context.hh.
status()
template<class TC> Status CheckerThreadContext< TC >::status () const inline override virtual
Implements ThreadContext.
Definition at line 192 of file thread_context.hh.
suspend()
template<class TC> void CheckerThreadContext< TC >::suspend () inline override virtual
Set the status to Suspended.
Implements ThreadContext.
Definition at line 205 of file thread_context.hh.
syscall()
template<class TC> void CheckerThreadContext< TC >::syscall (int64_t callnum, Fault * fault) inline override virtual
Executes a syscall in SE mode.
Implements ThreadContext.
Definition at line 187 of file thread_context.hh.
takeOverFrom()
template<class TC> void CheckerThreadContext< TC >::takeOverFrom (ThreadContext * oldContext) inline override virtual
Implements ThreadContext.
Definition at line 213 of file thread_context.hh.
References SimpleThread::copyState().
threadId()
template<class TC> int CheckerThreadContext< TC >::threadId () const inline override virtual
Returns this thread's ID number.
Implements ThreadContext.
Definition at line 127 of file thread_context.hh.
Member Data Documentation
actualTC
template<class TC> TC* CheckerThreadContext< TC >::actualTC private
The main CPU's ThreadContext, or class that implements the ThreadContext interface.
Definition at line 83 of file thread_context.hh.
checkerCPU
template<class TC> CheckerCPU* CheckerThreadContext< TC >::checkerCPU private
Pointer to the checker CPU.
Definition at line 89 of file thread_context.hh.
checkerTC
template<class TC> SimpleThread* CheckerThreadContext< TC >::checkerTC private
The checker's own SimpleThread.
Will be updated any time anything uses this ThreadContext to externally update a thread's state.
Definition at line 87 of file thread_context.hh.
The documentation for this class was generated from the following file:
cpu/checker/thread_context.hh