gem5: Iris::ThreadContext Class Reference
Iris::ThreadContext Class Reference
#include <thread_context.hh>
Public Types
typedef std::map< std::string, iris::ResourceInfo > ResourceMap
typedef std::vector< iris::ResourceId > ResourceIds
typedef std::map< int, std::string > IdxNameMap
Public Types inherited from ThreadContext
enum Status { Active, Suspended, Halting, Halted }
Public Member Functions
ThreadContext (::BaseCPU *cpu, int id, System *system, ::BaseTLB *dtb, ::BaseTLB *itb, iris::IrisConnectionInterface *iris_if, const std::string &iris_path)
virtual ~ThreadContext ()
bool schedule (PCEvent *e) override
bool remove (PCEvent *e) override
void scheduleInstCountEvent (Event *event, Tick count) override
void descheduleInstCountEvent (Event *event) override
Tick getCurrentInstCount () override
::BaseCPU * getCpuPtr () override
int cpuId () const override
uint32_t socketId () const override
int threadId () const override
void setThreadId (int id) override
int contextId () const override
void setContextId (int id) override
BaseTLB * getITBPtr () override
BaseTLB * getDTBPtr () override
CheckerCPU * getCheckerCpuPtr () override
TheISA::Decoder * getDecoderPtr () override
System * getSystemPtr () override
Kernel::Statistics * getKernelStats () override
PortProxy & getPhysProxy () override
PortProxy & getVirtProxy () override
void initMemProxies (::ThreadContext *tc) override
Process * getProcessPtr () override
void setProcessPtr (Process *p) override
Status status () const override
void setStatus (Status new_status) override
void activate () override
Set the status to Active.
void suspend () override
Set the status to Suspended.
void halt () override
Set the status to Halted.
void dumpFuncProfile () override
void takeOverFrom (::ThreadContext *old_context) override
void regStats (const std::string &name) override
EndQuiesceEvent * getQuiesceEvent () override
Tick readLastActivate () override
Tick readLastSuspend () override
void profileClear () override
void profileSample () override
void copyArchRegs (::ThreadContext *tc) override
void clearArchRegs () override
RegVal readIntReg (RegIndex reg_idx) const override
RegVal readFloatReg (RegIndex reg_idx) const override
const VecRegContainer & readVecReg (const RegId &reg) const override
VecRegContainer & getWritableVecReg (const RegId &reg) override
const VecElem & readVecElem (const RegId &reg) const override
const VecPredRegContainer & readVecPredReg (const RegId &reg) const override
VecPredRegContainer & getWritableVecPredReg (const RegId &reg) override
RegVal readCCReg (RegIndex reg_idx) const override
void setIntReg (RegIndex reg_idx, RegVal val) override
void setFloatReg (RegIndex reg_idx, RegVal val) override
void setVecReg (const RegId &reg, const VecRegContainer &val) override
void setVecElem (const RegId &reg, const VecElem &val) override
void setVecPredReg (const RegId &reg, const VecPredRegContainer &val) override
void setCCReg (RegIndex reg_idx, RegVal val) override
void pcStateNoRecord (const TheISA::PCState &val) override
MicroPC microPC () const override
RegVal readMiscRegNoEffect (RegIndex misc_reg) const override
RegVal readMiscReg (RegIndex misc_reg) override
void setMiscRegNoEffect (RegIndex misc_reg, const RegVal val) override
void setMiscReg (RegIndex misc_reg, const RegVal val) override
RegId flattenRegId (const RegId &regId) const override
unsigned readStCondFailures () const override
void setStCondFailures (unsigned sc_failures) override
Counter readFuncExeInst () const override
void syscall (int64_t callnum, Fault *fault) override
ConstVecLane8 readVec8BitLaneReg (const RegId &reg) const override
Vector Register Lane Interfaces.
ConstVecLane16 readVec16BitLaneReg (const RegId &reg) const override
Reads source vector 16bit operand.
ConstVecLane32 readVec32BitLaneReg (const RegId &reg) const override
Reads source vector 32bit operand.
ConstVecLane64 readVec64BitLaneReg (const RegId &reg) const override
Reads source vector 64bit operand.
void setVecLane (const RegId &reg, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector register.
void setVecLane (const RegId &reg, const LaneData< LaneSize::TwoByte > &val) override
void setVecLane (const RegId &reg, const LaneData< LaneSize::FourByte > &val) override
void setVecLane (const RegId &reg, const LaneData< LaneSize::EightByte > &val) override
uint64_t readIntRegFlat (RegIndex idx) const override
Flat register interfaces.
void setIntRegFlat (RegIndex idx, uint64_t val) override
RegVal readFloatRegFlat (RegIndex idx) const override
void setFloatRegFlat (RegIndex idx, RegVal val) override
const VecRegContainer & readVecRegFlat (RegIndex idx) const override
VecRegContainer & getWritableVecRegFlat (RegIndex idx) override
void setVecRegFlat (RegIndex idx, const VecRegContainer &val) override
const VecElem & readVecElemFlat (RegIndex idx, const ElemIndex &elemIdx) const override
void setVecElemFlat (RegIndex idx, const ElemIndex &elemIdx, const VecElem &val) override
const VecPredRegContainer & readVecPredRegFlat (RegIndex idx) const override
VecPredRegContainer & getWritableVecPredRegFlat (RegIndex idx) override
void setVecPredRegFlat (RegIndex idx, const VecPredRegContainer &val) override
RegVal readCCRegFlat (RegIndex idx) const override
void setCCRegFlat (RegIndex idx, RegVal val) override
Public Member Functions inherited from ThreadContext
virtual TheISA::ISA * getIsaPtr ()=0
virtual void initMemProxies (ThreadContext *tc)=0
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
virtual void setStatus (Status new_status)=0
void quiesce ()
Quiesce thread context.
void quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
virtual void takeOverFrom (ThreadContext *old_context)=0
virtual void copyArchRegs (ThreadContext *tc)=0
virtual TheISA::PCState pcState () const =0
virtual void pcState (const TheISA::PCState &val)=0
void setNPC (Addr val)
virtual Addr instAddr () const =0
virtual Addr nextInstAddr () const =0
virtual int exit ()
Protected Member Functions
virtual void initFromIrisInstance (const ResourceMap &resources)
iris::ResourceId extractResourceId (const ResourceMap &resources, const std::string &name)
void extractResourceMap (ResourceIds &ids, const ResourceMap &resources, const IdxNameMap &idx_names)
void maintainStepping ()
iris::IrisErrorCode instanceRegistryChanged (uint64_t esId, const iris::IrisValueMap &fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string &error_message_out)
iris::IrisErrorCode phaseInitLeave (uint64_t esId, const iris::IrisValueMap &fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string &error_message_out)
iris::IrisErrorCode simulationTimeEvent (uint64_t esId, const iris::IrisValueMap &fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string &error_message_out)
iris::IrisCppAdapter & call () const
iris::IrisCppAdapter & noThrow () const
Protected Attributes
::BaseCPU * _cpu
int _threadId
ContextID _contextId
System * _system
::BaseTLB * _dtb
::BaseTLB * _itb
std::string _irisPath
iris::InstanceId _instId
Status _status
ResourceIds miscRegIds
ResourceIds intRegIds
EventQueue comInstEventQueue
iris::EventStreamId regEventStreamId
iris::EventStreamId initEventStreamId
iris::EventStreamId timeEventStreamId
iris::IrisInstance client
Additional Inherited Members
Static Public Member Functions inherited from ThreadContext
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Protected Types inherited from ThreadContext
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
Definition at line 45 of file thread_context.hh.
Member Typedef Documentation
IdxNameMap
typedef std::map<int, std::string> Iris::ThreadContext::IdxNameMap
Definition at line 51 of file thread_context.hh.
ResourceIds
typedef std::vector<iris::ResourceId> Iris::ThreadContext::ResourceIds
Definition at line 50 of file thread_context.hh.
ResourceMap
typedef std::map<std::string, iris::ResourceInfo> Iris::ThreadContext::ResourceMap
Definition at line 48 of file thread_context.hh.
Constructor & Destructor Documentation
ThreadContext()
ThreadContext::ThreadContext (::BaseCPU * cpu, int id, System * system, ::BaseTLB * dtb, ::BaseTLB * itb, iris::IrisConnectionInterface * iris_if, const std::string & iris_path)
Definition at line 161 of file thread_context.cc.
References _instId, call(), client, initEventStreamId, noThrow(), regEventStreamId, and timeEventStreamId.
Referenced by noThrow().
~ThreadContext()
ThreadContext::~ThreadContext () virtual
Reimplemented from ThreadContext.
Definition at line 216 of file thread_context.cc.
References call(), client, initEventStreamId, regEventStreamId, and timeEventStreamId.
Referenced by noThrow().
Member Function Documentation
activate()
void Iris::ThreadContext::activate () inline override virtual
Set the status to Active.
Implements ThreadContext.
Definition at line 184 of file thread_context.hh.
References ThreadContext::Active, and setStatus().
call()
iris::IrisCppAdapter& Iris::ThreadContext::call () const inline protected
Definition at line 101 of file thread_context.hh.
Referenced by getCurrentInstCount(), initFromIrisInstance(), maintainStepping(), Iris::ArmThreadContext::pcState(), phaseInitLeave(), Iris::ArmThreadContext::readIntReg(), readIntReg(), readMiscRegNoEffect(), Iris::ArmThreadContext::readVecReg(), scheduleInstCountEvent(), Iris::ArmThreadContext::setIntReg(), setIntReg(), setMiscRegNoEffect(), simulationTimeEvent(), status(), ThreadContext(), and ~ThreadContext().
clearArchRegs()
void Iris::ThreadContext::clearArchRegs () inline override virtual
Implements ThreadContext.
Definition at line 238 of file thread_context.hh.
References panic, and readIntReg().
contextId()
int Iris::ThreadContext::contextId () const inline override virtual
Implements ThreadContext.
Definition at line 125 of file thread_context.hh.
References _contextId.
copyArchRegs()
void Iris::ThreadContext::copyArchRegs (::ThreadContext * tc) inline override
Definition at line 232 of file thread_context.hh.
References panic.
cpuId()
int Iris::ThreadContext::cpuId () const inline override virtual
Implements ThreadContext.
Definition at line 119 of file thread_context.hh.
References BaseCPU::cpuId().
descheduleInstCountEvent()
void ThreadContext::descheduleInstCountEvent (Event * event) override virtual
Implements ThreadContext.
Definition at line 246 of file thread_context.cc.
References comInstEventQueue, EventQueue::deschedule(), and maintainStepping().
Referenced by remove().
dumpFuncProfile()
void Iris::ThreadContext::dumpFuncProfile () inline override virtual
Implements ThreadContext.
Definition at line 189 of file thread_context.hh.
References panic.
extractResourceId()
iris::ResourceId ThreadContext::extractResourceId (const ResourceMap & resources, const std::string & name) protected
Definition at line 49 of file thread_context.cc.
Referenced by extractResourceMap(), and Iris::ArmThreadContext::initFromIrisInstance().
extractResourceMap()
void ThreadContext::extractResourceMap (ResourceIds & ids, const ResourceMap & resources, const IdxNameMap & idx_names) protected
Definition at line 56 of file thread_context.cc.
References extractResourceId(), and name().
Referenced by Iris::ArmThreadContext::initFromIrisInstance().
flattenRegId()
RegId Iris::ThreadContext::flattenRegId (const RegId & regId) const inline override virtual
Implements ThreadContext.
Definition at line 395 of file thread_context.hh.
References panic.
getCheckerCpuPtr()
CheckerCPU* Iris::ThreadContext::getCheckerCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 139 of file thread_context.hh.
References panic.
getCpuPtr()
::BaseCPU* Iris::ThreadContext::getCpuPtr () inline override virtual
Implements ThreadContext.
Definition at line 118 of file thread_context.hh.
References _cpu.
getCurrentInstCount()
Tick ThreadContext::getCurrentInstCount () override virtual
Implements ThreadContext.
Definition at line 253 of file thread_context.cc.
References _instId, call(), X86ISA::count, and panic_if.
Referenced by maintainStepping(), remove(), and scheduleInstCountEvent().
getDecoderPtr()
TheISA::Decoder* Iris::ThreadContext::getDecoderPtr () inline override virtual
Implements ThreadContext.
Definition at line 144 of file thread_context.hh.
References panic.
getDTBPtr()
BaseTLB* Iris::ThreadContext::getDTBPtr () inline override virtual
Implements ThreadContext.
Definition at line 134 of file thread_context.hh.
References _dtb.
getITBPtr()
BaseTLB* Iris::ThreadContext::getITBPtr () inline override virtual
Implements ThreadContext.
Definition at line 129 of file thread_context.hh.
References _itb.
getKernelStats()
Kernel::Statistics* Iris::ThreadContext::getKernelStats () inline override virtual
Implements ThreadContext.
Definition at line 152 of file thread_context.hh.
References panic.
getPhysProxy()
PortProxy& Iris::ThreadContext::getPhysProxy () inline override virtual
Implements ThreadContext.
Definition at line 157 of file thread_context.hh.
References panic.
getProcessPtr()
Process* Iris::ThreadContext::getProcessPtr () inline override virtual
Implements ThreadContext.
Definition at line 172 of file thread_context.hh.
References panic.
getQuiesceEvent()
EndQuiesceEvent* Iris::ThreadContext::getQuiesceEvent () inline override virtual
Implements ThreadContext.
Definition at line 203 of file thread_context.hh.
References panic.
getSystemPtr()
System* Iris::ThreadContext::getSystemPtr () inline override virtual
Implements ThreadContext.
Definition at line 149 of file thread_context.hh.
References BaseCPU::system.
getVirtProxy()
PortProxy& Iris::ThreadContext::getVirtProxy () inline override virtual
Implements ThreadContext.
Definition at line 162 of file thread_context.hh.
References panic.
getWritableVecPredReg()
VecPredRegContainer& Iris::ThreadContext::getWritableVecPredReg (const RegId & reg) inline override virtual
Implements ThreadContext.
Definition at line 333 of file thread_context.hh.
References panic.
getWritableVecPredRegFlat()
VecPredRegContainer& Iris::ThreadContext::getWritableVecPredRegFlat (RegIndex idx) inline override virtual
Implements ThreadContext.
Definition at line 495 of file thread_context.hh.
References panic.
getWritableVecReg()
VecRegContainer& Iris::ThreadContext::getWritableVecReg (const RegId & reg) inline override virtual
Implements ThreadContext.
Definition at line 260 of file thread_context.hh.
References panic.
getWritableVecRegFlat()
VecRegContainer& Iris::ThreadContext::getWritableVecRegFlat (RegIndex idx) inline override virtual
Implements ThreadContext.
Definition at line 467 of file thread_context.hh.
References panic.
halt()
void Iris::ThreadContext::halt () inline override virtual
Set the status to Halted.
Implements ThreadContext.
Definition at line 186 of file thread_context.hh.
References ThreadContext::Halted, and setStatus().
initFromIrisInstance()
void ThreadContext::initFromIrisInstance (const ResourceMap & resources) protected virtual
Reimplemented in Iris::ArmThreadContext.
Definition at line 39 of file thread_context.cc.
References _instId, _status, ThreadContext::Active, call(), Stats::enabled(), suspend(), and ThreadContext::Suspended.
Referenced by Iris::ArmThreadContext::initFromIrisInstance(), and phaseInitLeave().
initMemProxies()
void Iris::ThreadContext::initMemProxies (::ThreadContext * tc) inline override
Definition at line 167 of file thread_context.hh.
References panic.
instanceRegistryChanged()
iris::IrisErrorCode ThreadContext::instanceRegistryChanged (uint64_t esId, const iris::IrisValueMap & fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string & error_message_out) protected
Definition at line 101 of file thread_context.cc.
References _instId, _irisPath, MipsISA::event, ArmISA::id, name(), and panic.
maintainStepping()
void ThreadContext::maintainStepping () protected
Definition at line 72 of file thread_context.cc.
References _instId, call(), comInstEventQueue, EventQueue::empty(), getCurrentInstCount(), EventQueue::nextTick(), and EventQueue::serviceEvents().
Referenced by descheduleInstCountEvent(), scheduleInstCountEvent(), and simulationTimeEvent().
microPC()
MicroPC Iris::ThreadContext::microPC () const inline override virtual
Implements ThreadContext.
Definition at line 378 of file thread_context.hh.
References readMiscRegNoEffect().
noThrow()
iris::IrisCppAdapter& Iris::ThreadContext::noThrow () const inline protected
Definition at line 102 of file thread_context.hh.
References X86ISA::system, ThreadContext(), and ~ThreadContext().
Referenced by ThreadContext().
pcStateNoRecord()
void Iris::ThreadContext::pcStateNoRecord (const TheISA::PCState & val) inline override virtual
Implements ThreadContext.
Definition at line 377 of file thread_context.hh.
References ThreadContext::pcState().
phaseInitLeave()
iris::IrisErrorCode ThreadContext::phaseInitLeave (uint64_t esId, const iris::IrisValueMap & fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string & error_message_out) protected
Definition at line 123 of file thread_context.cc.
References _instId, call(), and initFromIrisInstance().
profileClear()
void Iris::ThreadContext::profileClear () inline override virtual
Implements ThreadContext.
Definition at line 221 of file thread_context.hh.
References panic.
profileSample()
void Iris::ThreadContext::profileSample () inline override virtual
Implements ThreadContext.
Definition at line 226 of file thread_context.hh.
References panic.
readCCReg()
RegVal Iris::ThreadContext::readCCReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 339 of file thread_context.hh.
References panic, setIntReg(), and X86ISA::val.
readCCRegFlat()
RegVal Iris::ThreadContext::readCCRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 506 of file thread_context.hh.
References panic.
readFloatReg()
RegVal Iris::ThreadContext::readFloatReg (RegIndex reg_idx) const inline override virtual
Implements ThreadContext.
Definition at line 249 of file thread_context.hh.
References panic.
readFloatRegFlat()
RegVal Iris::ThreadContext::readFloatRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 451 of file thread_context.hh.
References panic.
readFuncExeInst()
Counter Iris::ThreadContext::readFuncExeInst () const inline override virtual
Implements ThreadContext.
Definition at line 416 of file thread_context.hh.
References panic.
readIntReg()
RegVal ThreadContext::readIntReg (RegIndex reg_idx) const override virtual
Implements ThreadContext.
Definition at line 296 of file thread_context.cc.
References _instId, call(), and intRegIds.
Referenced by clearArchRegs().
readIntRegFlat()
uint64_t Iris::ThreadContext::readIntRegFlat (RegIndex idx) const inline override virtual
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenRegId()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implements ThreadContext.
Definition at line 440 of file thread_context.hh.
References panic.
readLastActivate()
Tick Iris::ThreadContext::readLastActivate () inline override virtual
Implements ThreadContext.
Definition at line 211 of file thread_context.hh.
References panic.
readLastSuspend()
Tick Iris::ThreadContext::readLastSuspend () inline override virtual
Implements ThreadContext.
Definition at line 215 of file thread_context.hh.
References panic.
readMiscReg()
RegVal Iris::ThreadContext::readMiscReg (RegIndex misc_reg) inline override virtual
Implements ThreadContext.
Definition at line 382 of file thread_context.hh.
References readMiscRegNoEffect(), and setMiscRegNoEffect().
readMiscRegNoEffect()
RegVal ThreadContext::readMiscRegNoEffect (RegIndex misc_reg) const override virtual
Implements ThreadContext.
Definition at line 281 of file thread_context.cc.
References _instId, call(), and miscRegIds.
Referenced by microPC(), Iris::ArmThreadContext::pcState(), Iris::ArmThreadContext::readIntReg(), readMiscReg(), and Iris::ArmThreadContext::setIntReg().
readStCondFailures()
unsigned Iris::ThreadContext::readStCondFailures () const inline override virtual
Implements ThreadContext.
Definition at line 403 of file thread_context.hh.
References panic.
readVec16BitLaneReg()
ConstVecLane16 Iris::ThreadContext::readVec16BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 16bit operand.
Implements ThreadContext.
Definition at line 276 of file thread_context.hh.
References panic.
readVec32BitLaneReg()
ConstVecLane32 Iris::ThreadContext::readVec32BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 32bit operand.
Implements ThreadContext.
Definition at line 283 of file thread_context.hh.
References panic.
readVec64BitLaneReg()
ConstVecLane64 Iris::ThreadContext::readVec64BitLaneReg (const RegId & reg) const inline override virtual
Reads source vector 64bit operand.
Implements ThreadContext.
Definition at line 290 of file thread_context.hh.
References panic.
readVec8BitLaneReg()
ConstVecLane8 Iris::ThreadContext::readVec8BitLaneReg (const RegId & reg) const inline override virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implements ThreadContext.
Definition at line 269 of file thread_context.hh.
References panic.
readVecElem()
const VecElem& Iris::ThreadContext::readVecElem (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 322 of file thread_context.hh.
References panic.
readVecElemFlat()
const VecElem& Iris::ThreadContext::readVecElemFlat (RegIndex idx, const ElemIndex & elemIdx) const inline override virtual
Implements ThreadContext.
Definition at line 478 of file thread_context.hh.
References panic.
readVecPredReg()
const VecPredRegContainer& Iris::ThreadContext::readVecPredReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 328 of file thread_context.hh.
References panic.
readVecPredRegFlat()
const VecPredRegContainer& Iris::ThreadContext::readVecPredRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 490 of file thread_context.hh.
References panic.
readVecReg()
const VecRegContainer& Iris::ThreadContext::readVecReg (const RegId & reg) const inline override virtual
Implements ThreadContext.
Definition at line 255 of file thread_context.hh.
References panic.
readVecRegFlat()
const VecRegContainer& Iris::ThreadContext::readVecRegFlat (RegIndex idx) const inline override virtual
Implements ThreadContext.
Definition at line 462 of file thread_context.hh.
References panic.
regStats()
void Iris::ThreadContext::regStats (const std::string & name) inline override virtual
Implements ThreadContext.
Definition at line 200 of file thread_context.hh.
remove()
bool Iris::ThreadContext::remove (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 112 of file thread_context.hh.
References X86ISA::count, descheduleInstCountEvent(), MipsISA::event, getCurrentInstCount(), and scheduleInstCountEvent().
schedule()
bool Iris::ThreadContext::schedule (PCEvent * e) inline override virtual
Implements PCEventScope.
Definition at line 111 of file thread_context.hh.
scheduleInstCountEvent()
void ThreadContext::scheduleInstCountEvent (Event * event, Tick count) override virtual
Implements ThreadContext.
Definition at line 235 of file thread_context.cc.
References call(), comInstEventQueue, getCurrentInstCount(), maintainStepping(), and EventQueue::schedule().
Referenced by remove().
setCCReg()
void Iris::ThreadContext::setCCReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 372 of file thread_context.hh.
References panic.
setCCRegFlat()
void Iris::ThreadContext::setCCRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 511 of file thread_context.hh.
References panic.
setContextId()
void Iris::ThreadContext::setContextId (int id) inline override virtual
Implements ThreadContext.
Definition at line 126 of file thread_context.hh.
References ArmISA::id.
setFloatReg()
void Iris::ThreadContext::setFloatReg (RegIndex reg_idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 347 of file thread_context.hh.
References panic.
setFloatRegFlat()
void Iris::ThreadContext::setFloatRegFlat (RegIndex idx, RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 456 of file thread_context.hh.
References panic.
setIntReg()
void ThreadContext::setIntReg (RegIndex reg_idx, RegVal val) override virtual
Implements ThreadContext.
Definition at line 304 of file thread_context.cc.
References _instId, call(), intRegIds, and X86ISA::val.
Referenced by readCCReg().
setIntRegFlat()
void Iris::ThreadContext::setIntRegFlat (RegIndex idx, uint64_t val) inline override virtual
Implements ThreadContext.
Definition at line 445 of file thread_context.hh.
References panic.
setMiscReg()
void Iris::ThreadContext::setMiscReg (RegIndex misc_reg, const RegVal val) inline override virtual
Implements ThreadContext.
Definition at line 389 of file thread_context.hh.
References setMiscRegNoEffect().
setMiscRegNoEffect()
void ThreadContext::setMiscRegNoEffect (RegIndex misc_reg, const RegVal val) override virtual
Implements ThreadContext.
Definition at line 289 of file thread_context.cc.
References _instId, call(), miscRegIds, and X86ISA::val.
Referenced by readMiscReg(), and setMiscReg().
setProcessPtr()
void Iris::ThreadContext::setProcessPtr (Process * p) inline override virtual
Implements ThreadContext.
Definition at line 177 of file thread_context.hh.
References panic, setStatus(), and status().
setStatus()
void Iris::ThreadContext::setStatus (Status new_status) override
Referenced by activate(), halt(), setProcessPtr(), status(), and suspend().
setStCondFailures()
void Iris::ThreadContext::setStCondFailures (unsigned sc_failures) inline override virtual
Implements ThreadContext.
Definition at line 409 of file thread_context.hh.
References panic.
setThreadId()
void Iris::ThreadContext::setThreadId (int id) inline override virtual
Implements ThreadContext.
Definition at line 123 of file thread_context.hh.
References ArmISA::id.
setVecElem()
void Iris::ThreadContext::setVecElem (const RegId & reg, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 359 of file thread_context.hh.
References panic.
setVecElemFlat()
void Iris::ThreadContext::setVecElemFlat (RegIndex idx, const ElemIndex & elemIdx, const VecElem & val) inline override virtual
Implements ThreadContext.
Definition at line 483 of file thread_context.hh.
References panic.
setVecLane() [1/4]
void Iris::ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector register.
Implements ThreadContext.
Definition at line 297 of file thread_context.hh.
References panic.
setVecLane() [2/4]
void Iris::ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 302 of file thread_context.hh.
References panic.
setVecLane() [3/4]
void Iris::ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 308 of file thread_context.hh.
References panic.
setVecLane() [4/4]
void Iris::ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ThreadContext.
Definition at line 314 of file thread_context.hh.
References panic.
setVecPredReg()
void Iris::ThreadContext::setVecPredReg (const RegId & reg, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 365 of file thread_context.hh.
References panic.
setVecPredRegFlat()
void Iris::ThreadContext::setVecPredRegFlat (RegIndex idx, const VecPredRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 500 of file thread_context.hh.
References panic.
setVecReg()
void Iris::ThreadContext::setVecReg (const RegId & reg, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 353 of file thread_context.hh.
References panic.
setVecRegFlat()
void Iris::ThreadContext::setVecRegFlat (RegIndex idx, const VecRegContainer & val) inline override virtual
Implements ThreadContext.
Definition at line 472 of file thread_context.hh.
References panic.
simulationTimeEvent()
iris::IrisErrorCode ThreadContext::simulationTimeEvent (uint64_t esId, const iris::IrisValueMap & fields, uint64_t time, uint64_t sInstId, bool syncEc, std::string & error_message_out) protected
Definition at line 140 of file thread_context.cc.
References call(), and maintainStepping().
socketId()
uint32_t Iris::ThreadContext::socketId () const inline override virtual
Implements ThreadContext.
Definition at line 120 of file thread_context.hh.
References BaseCPU::socketId().
status()
ThreadContext::Status ThreadContext::status () const override virtual
Implements ThreadContext.
Definition at line 262 of file thread_context.cc.
References _instId, _status, ThreadContext::Active, call(), and setStatus().
Referenced by setProcessPtr().
suspend()
void Iris::ThreadContext::suspend () inline override virtual
Set the status to Suspended.
Implements ThreadContext.
Definition at line 185 of file thread_context.hh.
References setStatus(), and ThreadContext::Suspended.
Referenced by initFromIrisInstance().
syscall()
void Iris::ThreadContext::syscall (int64_t callnum, Fault * fault) inline override virtual
Implements ThreadContext.
Definition at line 422 of file thread_context.hh.
References panic.
takeOverFrom()
void Iris::ThreadContext::takeOverFrom (::ThreadContext * old_context) inline override
Definition at line 195 of file thread_context.hh.
References panic.
threadId()
int Iris::ThreadContext::threadId () const inline override virtual
Implements ThreadContext.
Definition at line 122 of file thread_context.hh.
References _threadId.
Member Data Documentation
_contextId
ContextID Iris::ThreadContext::_contextId protected
Definition at line 56 of file thread_context.hh.
Referenced by contextId().
_cpu
::BaseCPU* Iris::ThreadContext::_cpu protected
Definition at line 54 of file thread_context.hh.
Referenced by getCpuPtr().
_dtb
::BaseTLB* Iris::ThreadContext::_dtb protected
Definition at line 58 of file thread_context.hh.
Referenced by getDTBPtr().
_instId
iris::InstanceId Iris::ThreadContext::_instId protected
Definition at line 62 of file thread_context.hh.
Referenced by getCurrentInstCount(), initFromIrisInstance(), instanceRegistryChanged(), maintainStepping(), Iris::ArmThreadContext::pcState(), phaseInitLeave(), Iris::ArmThreadContext::readIntReg(), readIntReg(), readMiscRegNoEffect(), Iris::ArmThreadContext::readVecReg(), Iris::ArmThreadContext::setIntReg(), setIntReg(), setMiscRegNoEffect(), status(), and ThreadContext().
_irisPath
std::string Iris::ThreadContext::_irisPath protected
Definition at line 61 of file thread_context.hh.
Referenced by instanceRegistryChanged().
_itb
::BaseTLB* Iris::ThreadContext::_itb protected
Definition at line 59 of file thread_context.hh.
Referenced by getITBPtr().
_status
Status Iris::ThreadContext::_status protected
Definition at line 64 of file thread_context.hh.
Referenced by initFromIrisInstance(), and status().
_system
System* Iris::ThreadContext::_system protected
Definition at line 57 of file thread_context.hh.
_threadId
int Iris::ThreadContext::_threadId protected
Definition at line 55 of file thread_context.hh.
Referenced by threadId().
client
iris::IrisInstance Iris::ThreadContext::client mutable protected
Definition at line 100 of file thread_context.hh.
Referenced by ThreadContext(), and ~ThreadContext().
comInstEventQueue
EventQueue Iris::ThreadContext::comInstEventQueue protected
Definition at line 79 of file thread_context.hh.
Referenced by descheduleInstCountEvent(), maintainStepping(), and scheduleInstCountEvent().
initEventStreamId
iris::EventStreamId Iris::ThreadContext::initEventStreamId protected
Definition at line 97 of file thread_context.hh.
Referenced by ThreadContext(), and ~ThreadContext().
intRegIds
ResourceIds Iris::ThreadContext::intRegIds protected
Definition at line 75 of file thread_context.hh.
Referenced by readIntReg(), and setIntReg().
miscRegIds
ResourceIds Iris::ThreadContext::miscRegIds protected
Definition at line 74 of file thread_context.hh.
Referenced by Iris::ArmThreadContext::initFromIrisInstance(), readMiscRegNoEffect(), and setMiscRegNoEffect().
regEventStreamId
iris::EventStreamId Iris::ThreadContext::regEventStreamId protected
Definition at line 96 of file thread_context.hh.
Referenced by ThreadContext(), and ~ThreadContext().
timeEventStreamId
iris::EventStreamId Iris::ThreadContext::timeEventStreamId protected
Definition at line 98 of file thread_context.hh.
Referenced by ThreadContext(), and ~ThreadContext().
The documentation for this class was generated from the following files:
arch/arm/fastmodel/iris/thread_context.hh
arch/arm/fastmodel/iris/thread_context.cc