gem5: AbstractNVM Class Reference
AbstractNVM Class Reference abstract
This is an interface between the disk interface (which will handle the disk data transactions) and the timing model.
#include <abstract_nvm.hh>
Public Member Functions
AbstractNVM (const AbstractNVMParams *p)
virtual ~AbstractNVM ()
virtual void initializeMemory (uint64_t disk_size, uint32_t sector_size)=0
Initialize Memory.
virtual void readMemory (uint64_t address, uint32_t amount, Callback *event)=0
Access functions Access function to simulate a read/write access to the memory.
virtual void writeMemory (uint64_t address, uint32_t amount, Callback *event)=0
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
This is an interface between the disk interface (which will handle the disk data transactions) and the timing model.
The timing model only takes care of calculating the appropriate delay to the disk, and calling back a function when the action has completed. All the other associated actions (such as getting data from A to B) should be taken care of by the disk interface.
Definition at line 55 of file abstract_nvm.hh.
Constructor & Destructor Documentation
AbstractNVM()
AbstractNVM::AbstractNVM (const AbstractNVMParams * p) inline
Definition at line 59 of file abstract_nvm.hh.
~AbstractNVM()
virtual AbstractNVM::~AbstractNVM () inline virtual
Definition at line 60 of file abstract_nvm.hh.
References MipsISA::event, initializeMemory(), readMemory(), and writeMemory().
Member Function Documentation
initializeMemory()
virtual void AbstractNVM::initializeMemory (uint64_t disk_size, uint32_t sector_size) pure virtual
Initialize Memory.
This function is used to set the memory device dimensions to the dimensions that it controls. For instance, One can imagine that the memory is one disk, e.g. the /data partition of Android, which means that the data handling part will have an image of /data. On the other hand one might want to set up a Raid like configuration, without wanting to create multiple disk images. In that case one can choose to devide the image over multiple memory devices in any way he wants (i.e. higher layers can implement some division based on logical addresses, or intelligent file system interpretation analysis; to effectively devide the disk over the devices; enabling object oriented storage devices). Moving this function outside of the constructor allows you the flexibility to make this decision once the image is loaded.
Parameters
disk_size disksize in sectors; value can be obtained from the disk image
sector_size size of one sector in bytes; value is defined in disk_image.hh
Implemented in FlashDevice.
Referenced by UFSHostDevice::UFSSCSIDevice::UFSSCSIDevice(), and ~AbstractNVM().
readMemory()
virtual void AbstractNVM::readMemory (uint64_t address, uint32_t amount, Callback * event) pure virtual
Access functions Access function to simulate a read/write access to the memory.
Once the action has completed, the Callback event should be called. Putting a NULL pointer as callback is valid syntax, and should result in the simulation of the access, but with no callback to the higher layer. This may be used to occupy the device, such that next actions will be delayed. The read/write function will schedule the incoming requests on a first come first serve basis.
Parameters
address The logical address to a location in the Non-volatile memory.
amount The amount of data transfered from the NVM in bytes
event A pointer to a callback function that will perform the actions taken by the disk controller on successfull completion of the data transfer between the disk and the disk controller.
Implemented in FlashDevice.
Referenced by ~AbstractNVM().
writeMemory()
virtual void AbstractNVM::writeMemory (uint64_t address, uint32_t amount, Callback * event) pure virtual
Implemented in FlashDevice.
Referenced by ~AbstractNVM().
The documentation for this class was generated from the following file:
dev/arm/abstract_nvm.hh