gem5: HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType > Class Template Reference
HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType > Class Template Reference
#include <mem.hh>
Public Member Functions
void generateDisassembly () override
StInst (const Brig::BrigInstBase *ib, const BrigObject *obj, const char *_opcode, int srcIdx)
void initiateAcc (GPUDynInstPtr gpuDynInst) override
void completeAcc (GPUDynInstPtr gpuDynInst) override
bool isVectorRegister (int operandIndex) override
bool isCondRegister (int operandIndex) override
bool isScalarRegister (int operandIndex) override
bool isSrcOperand (int operandIndex) override
bool isDstOperand (int operandIndex) override
int getOperandSize (int operandIndex) override
int getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) override
int getNumOperands () override
void execute (GPUDynInstPtr gpuDynInst) override
Public Member Functions inherited from HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >
StInstBase (const Brig::BrigInstBase *ib, const BrigObject *obj, const char *_opcode)
int numDstRegOperands () override
int numSrcRegOperands () override
int getNumOperands () override
bool isVectorRegister (int operandIndex) override
bool isCondRegister (int operandIndex) override
bool isScalarRegister (int operandIndex) override
bool isSrcOperand (int operandIndex) override
bool isDstOperand (int operandIndex) override
int getOperandSize (int operandIndex) override
int getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) override
Public Member Functions inherited from HsailISA::HsailGPUStaticInst
HsailGPUStaticInst (const BrigObject *obj, const std::string &opcode)
int instSize () const override
bool isValid () const override
Public Member Functions inherited from GPUStaticInst
GPUStaticInst (const std::string &opcode)
void instAddr (int inst_addr)
int instAddr () const
int nextInstAddr () const
void instNum (int num)
int instNum ()
void ipdInstNum (int num)
int ipdInstNum () const
const std::string & disassemble ()
bool isALU () const
bool isBranch () const
bool isNop () const
bool isReturn () const
bool isUnconditionalJump () const
bool isSpecialOp () const
bool isWaitcnt () const
bool isBarrier () const
bool isMemFence () const
bool isMemRef () const
bool isFlat () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isAtomicNoRet () const
bool isAtomicRet () const
bool isScalar () const
bool readsSCC () const
bool writesSCC () const
bool readsVCC () const
bool writesVCC () const
bool isAtomicAnd () const
bool isAtomicOr () const
bool isAtomicXor () const
bool isAtomicCAS () const
bool isAtomicExch () const
bool isAtomicAdd () const
bool isAtomicSub () const
bool isAtomicInc () const
bool isAtomicDec () const
bool isAtomicMax () const
bool isAtomicMin () const
bool isArgLoad () const
bool isGlobalMem () const
bool isLocalMem () const
bool isArgSeg () const
bool isGlobalSeg () const
bool isGroupSeg () const
bool isKernArgSeg () const
bool isPrivateSeg () const
bool isReadOnlySeg () const
bool isSpillSeg () const
bool isWorkitemScope () const
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isNoScope () const
bool isRelaxedOrder () const
bool isAcquire () const
bool isRelease () const
bool isAcquireRelease () const
bool isNoOrder () const
bool isGloballyCoherent () const
Coherence domain of a memory instruction.
bool isSystemCoherent () const
virtual uint32_t getTargetPc ()
void setFlag (Flags flag)
virtual void execLdAcq (GPUDynInstPtr gpuDynInst)
virtual void execAtomic (GPUDynInstPtr gpuDynInst)
virtual void execAtomicAcq (GPUDynInstPtr gpuDynInst)
Public Member Functions inherited from HsailISA::MemInst
MemInst ()
MemInst (Enums::MemType m_type)
void init_addr (AddrOperandBase *_addr_operand)
int getMemOperandSize ()
AddrOperandBase * getAddressOperand ()
Public Attributes
SrcDataType::OperandType::SrcOperand src_vect [4]
uint16_t num_src_operands
Public Attributes inherited from HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >
SrcDataType::OperandType ::SrcOperand src
AddrOperandType addr
Brig::BrigSegment segment
Brig::BrigMemoryScope memoryScope
Brig::BrigMemoryOrder memoryOrder
unsigned int equivClass
Public Attributes inherited from GPUStaticInst
Enums::StorageClassType executed_as
Private Member Functions
void execSt (GPUDynInstPtr gpuDynInst) override
Additional Inherited Members
Static Public Attributes inherited from GPUStaticInst
static uint64_t dynamic_id_count
Protected Attributes inherited from HsailISA::HsailGPUStaticInst
HsailCode * hsailCode
Protected Attributes inherited from GPUStaticInst
const std::string opcode
std::string disassembly
int _instNum
int _instAddr
int _ipdInstNum
Identifier of the immediate post-dominator instruction.
std::bitset< Num_Flags > _flags
Detailed Description
template<typename MemDataType, typename SrcDataType, typename AddrOperandType>
class HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >
Definition at line 952 of file mem.hh.
Constructor & Destructor Documentation
StInst()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::StInst (const Brig::BrigInstBase * ib, const BrigObject * obj, const char * _opcode, int srcIdx) inline
Definition at line 962 of file mem.hh.
References addr, Brig::BrigOperandConstantBytes::base, Brig::BRIG_KIND_OPERAND_CONSTANT_BYTES, Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_TYPE_NONE, Brig::BrigOperandOperandList::elements, findRegDataType(), BrigObject::getData(), BrigObject::getOperand(), BrigObject::getOperandPtr(), ArmISA::i, HsailISA::MemInst::init_addr(), Brig::BrigBase::kind, X86ISA::op, and Brig::BrigInstBase::operands.
Member Function Documentation
completeAcc()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > void HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::completeAcc (GPUDynInstPtr gpuDynInst) inline override virtual
Reimplemented from GPUStaticInst.
Definition at line 1035 of file mem.hh.
execSt()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > void HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execSt (GPUDynInstPtr gpuDynInst) inline override private virtual
Reimplemented from GPUStaticInst.
Definition at line 1042 of file mem.hh.
References ArmISA::d, Packet::dataStatic(), ArmISA::i, MipsISA::k, MipsISA::vaddr, and MemCmd::WriteReq.
execute()
template<typename OperationType , typename SrcDataType , typename AddrRegOperandType > void HsailISA::StInst< OperationType, SrcDataType, AddrRegOperandType >::execute (GPUDynInstPtr gpuDynInst) override virtual
Implements GPUStaticInst.
Definition at line 351 of file mem_impl.hh.
References addr, Brig::BRIG_SEGMENT_ARG, Brig::BRIG_SEGMENT_GLOBAL, Brig::BRIG_SEGMENT_GROUP, Brig::BRIG_SEGMENT_PRIVATE, Brig::BRIG_SEGMENT_SPILL, HsailISA::calcPrivAddr(), Wavefront::computeUnit, ComputeUnit::cu_id, data, DPRINTF, Wavefront::execMask(), fatal, LocalMemPipeline::getLMReqFIFO(), Wavefront::getPred(), GLBMEM_PIPE, ComputeUnit::globalMemoryPipe, GlobalMemPipeline::issueRequest(), MipsISA::k, Wavefront::kernId, LDSMEM_PIPE, ComputeUnit::localMemoryPipe, ArmISA::m, ArmISA::mask, Wavefront::memReqsInPipe, Wavefront::outstandingReqs, Wavefront::outstandingReqsWrGm, Wavefront::outstandingReqsWrLm, Wavefront::privBase, Wavefront::privSizePerItem, ComputeUnit::shader, Wavefront::simdId, Wavefront::spillBase, Wavefront::spillSizePerItem, Wavefront::spillWidth, Shader::tick_cnt, Shader::ticks(), MipsISA::w, Wavefront::wfDynId, ComputeUnit::wfSize(), Wavefront::wfSlotId, Wavefront::wrGmReqsInPipe, and Wavefront::wrLmReqsInPipe.
generateDisassembly()
template<typename OperationType , typename SrcDataType , typename AddrRegOperandType > void HsailISA::StInst< OperationType, SrcDataType, AddrRegOperandType >::generateDisassembly () override virtual
Reimplemented from HsailISA::HsailGPUStaticInst.
Definition at line 506 of file mem_impl.hh.
References addr, csprintf(), fatal, ArmISA::opcode, and segmentNames.
getNumOperands()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > int HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::getNumOperands () inline override virtual
Implements GPUStaticInst.
Definition at line 1166 of file mem.hh.
References addr.
getOperandSize()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > int HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::getOperandSize (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1139 of file mem.hh.
References addr.
getRegisterIndex()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > int HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) inline override virtual
Implements GPUStaticInst.
Definition at line 1153 of file mem.hh.
References addr.
initiateAcc()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > void HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::initiateAcc (GPUDynInstPtr gpuDynInst) inline override virtual
Reimplemented from GPUStaticInst.
Definition at line 1006 of file mem.hh.
References GPUStaticInst::execSt(), and Request::RELEASE.
isCondRegister()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > bool HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::isCondRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1107 of file mem.hh.
References addr, and HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >::isCondRegister().
isDstOperand()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > bool HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::isDstOperand (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1138 of file mem.hh.
isScalarRegister()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > bool HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::isScalarRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1120 of file mem.hh.
References addr, and HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >::isScalarRegister().
isSrcOperand()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > bool HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::isSrcOperand (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1133 of file mem.hh.
isVectorRegister()
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > bool HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::isVectorRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 1094 of file mem.hh.
References addr, and HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >::isVectorRegister().
Member Data Documentation
num_src_operands
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > uint16_t HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::num_src_operands
Definition at line 959 of file mem.hh.
src_vect
template<typename MemDataType , typename SrcDataType , typename AddrOperandType > SrcDataType::OperandType::SrcOperand HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::src_vect[4]
Definition at line 958 of file mem.hh.
The documentation for this class was generated from the following files:
arch/hsail/insts/mem.hh
arch/hsail/insts/mem_impl.hh