gem5: ChunkGenerator Class Reference
ChunkGenerator Class Reference
This class takes an arbitrary memory region (address/length pair) and generates a series of appropriately (e.g.
#include <chunk_generator.hh>
Public Member Functions
ChunkGenerator (Addr _startAddr, unsigned totalSize, unsigned _chunkSize)
Constructor.
Addr addr () const
Return starting address of current chunk.
unsigned size () const
Return size in bytes of current chunk.
unsigned complete () const
Number of bytes we have already chunked up.
bool done () const
Are we done? That is, did the last call to next() advance past the end of the region?
bool last () const
Is this the last chunk?
bool next ()
Advance generator to next chunk.
Private Attributes
Addr curAddr
The starting address of the current chunk.
Addr nextAddr
The starting address of the next chunk (after the current one).
unsigned curSize
The size of the current chunk (in bytes).
unsigned sizeLeft
The number of bytes remaining in the region after the current chunk.
const Addr startAddr
The start address so we can calculate offset in writing block.
const unsigned chunkSize
The maximum chunk size, e.g., the cache block size or page size.
Detailed Description
This class takes an arbitrary memory region (address/length pair) and generates a series of appropriately (e.g.
block- or page-) aligned chunks covering the same region.
Example usage:
for (ChunkGenerator gen(addr, size, chunkSize); !gen.done(); gen.next()) {
    doSomethingChunky(gen.addr(), gen.size());
}
Definition at line 57 of file chunk_generator.hh.
Constructor & Destructor Documentation
ChunkGenerator()
ChunkGenerator::ChunkGenerator (Addr _startAddr, unsigned totalSize, unsigned _chunkSize) inline
Constructor.
Parameters
_startAddr The starting address of the region.
totalSize The total size of the region.
_chunkSize The size/alignment of chunks into which the region should be decomposed.
Definition at line 81 of file chunk_generator.hh.
References chunkSize, curAddr, curSize, isPowerOf2(), roundUp(), and startAddr.
Member Function Documentation
addr()
Addr ChunkGenerator::addr () const inline
Return starting address of current chunk.
Definition at line 111 of file chunk_generator.hh.
References curAddr.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), and TEST().
complete()
unsigned ChunkGenerator::complete () const inline
Number of bytes we have already chunked up.
Definition at line 116 of file chunk_generator.hh.
References startAddr.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), and TEST().
done()
bool ChunkGenerator::done () const inline
Are we done? That is, did the last call to next() advance past the end of the region?
Returns
True if yes, false if more to go.
Definition at line 123 of file chunk_generator.hh.
Referenced by ArmISA::RemoteGDB::acc(), Shader::AccessMem(), brkFunc(), DmaPort::dmaAction(), IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), PortProxy::readBlobPhys(), TEST(), SETranslatingPortProxy::tryMemsetBlob(), FSTranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryReadBlob(), FSTranslatingPortProxy::tryReadBlob(), SETranslatingPortProxy::tryWriteBlob(), FSTranslatingPortProxy::tryWriteBlob(), and PortProxy::writeBlobPhys().
last()
bool ChunkGenerator::last () const inline
Is this the last chunk?
Returns
True if yes, false if more to go.
Definition at line 129 of file chunk_generator.hh.
Referenced by TEST().
next()
bool ChunkGenerator::next () inline
Advance generator to next chunk.
Returns
True if successful, false if unsuccessful (because we were at the last chunk).
Definition at line 137 of file chunk_generator.hh.
References curSize, and nextAddr.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), and TEST().
size()
unsigned ChunkGenerator::size () const inline
Return size in bytes of current chunk.
Definition at line 113 of file chunk_generator.hh.
References curSize.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), and TEST().
Member Data Documentation
chunkSize
const unsigned ChunkGenerator::chunkSize private
The maximum chunk size, e.g., the cache block size or page size.
Definition at line 71 of file chunk_generator.hh.
Referenced by ChunkGenerator().
curAddr
Addr ChunkGenerator::curAddr private
The starting address of the current chunk.
Definition at line 61 of file chunk_generator.hh.
Referenced by addr(), and ChunkGenerator().
curSize
unsigned ChunkGenerator::curSize private
The size of the current chunk (in bytes).
Definition at line 65 of file chunk_generator.hh.
Referenced by ChunkGenerator(), next(), and size().
nextAddr
Addr ChunkGenerator::nextAddr private
The starting address of the next chunk (after the current one).
Definition at line 63 of file chunk_generator.hh.
Referenced by next().
sizeLeft
unsigned ChunkGenerator::sizeLeft private
The number of bytes remaining in the region after the current chunk.
Definition at line 67 of file chunk_generator.hh.
startAddr
const Addr ChunkGenerator::startAddr private
The start address so we can calculate offset in writing block.
Definition at line 69 of file chunk_generator.hh.
Referenced by ChunkGenerator(), and complete().
The documentation for this class was generated from the following file:
base/chunk_generator.hh