gem5: Minor::ForwardInstData Class Reference
Minor::ForwardInstData Class Reference
Forward flowing data between Fetch2,Decode,Execute carrying a packet of instructions of a width appropriate to the configured stage widths.
#include <pipe_data.hh>
Public Member Functions
ForwardInstData (unsigned int width=0, ThreadID tid=InvalidThreadID)
ForwardInstData (const ForwardInstData &src)
unsigned int width () const
Number of instructions carried by this object.
ForwardInstData & operator= (const ForwardInstData &src)
Copy the inst array only as far as numInsts.
void resize (unsigned int width)
Resize a bubble/empty ForwardInstData and fill with bubbles.
void bubbleFill ()
Fill with bubbles from 0 to width() - 1.
bool isBubble () const
BubbleIF interface.
void reportData (std::ostream &os) const
ReportIF interface.
Public Attributes
MinorDynInstPtr insts [MAX_FORWARD_INSTS]
Array of carried insts, ref counted.
unsigned int numInsts
The number of insts slots that can be expected to be valid insts.
ThreadID threadId
Thread associated with these instructions.
Detailed Description
Forward flowing data between Fetch2,Decode,Execute carrying a packet of instructions of a width appropriate to the configured stage widths.
Also carries exception information where instructions are not valid
Definition at line 255 of file pipe_data.hh.
Constructor & Destructor Documentation
ForwardInstData() [1/2]
Minor::ForwardInstData::ForwardInstData (unsigned int width = 0, ThreadID tid = InvalidThreadID) explicit
Definition at line 226 of file pipe_data.cc.
References bubbleFill().
ForwardInstData() [2/2]
Minor::ForwardInstData::ForwardInstData (const ForwardInstData & src)
Definition at line 232 of file pipe_data.cc.
Member Function Documentation
bubbleFill()
void Minor::ForwardInstData::bubbleFill ()
Fill with bubbles from 0 to width() - 1.
Definition at line 255 of file pipe_data.cc.
References Minor::MinorDynInst::bubble(), ArmISA::i, insts, and numInsts.
Referenced by ForwardInstData(), and resize().
isBubble()
bool Minor::ForwardInstData::isBubble () const
BubbleIF interface.
Definition at line 249 of file pipe_data.cc.
References insts, and numInsts.
Referenced by Minor::Decode::evaluate(), Minor::Fetch2::evaluate(), Minor::Decode::getInput(), Minor::Execute::getInput(), and reportData().
operator=()
ForwardInstData & Minor::ForwardInstData::operator= (const ForwardInstData & src)
Copy the inst array only as far as numInsts.
Definition at line 238 of file pipe_data.cc.
References ArmISA::i, insts, and numInsts.
reportData()
void Minor::ForwardInstData::reportData (std::ostream & os) const
ReportIF interface.
Definition at line 271 of file pipe_data.cc.
References ArmISA::i, insts, isBubble(), and numInsts.
resize()
void Minor::ForwardInstData::resize (unsigned int width)
Resize a bubble/empty ForwardInstData and fill with bubbles.
Definition at line 262 of file pipe_data.cc.
References bubbleFill(), Minor::MAX_FORWARD_INSTS, numInsts, and width().
Referenced by Minor::Decode::evaluate(), and Minor::Fetch2::evaluate().
width()
unsigned int Minor::ForwardInstData::width () const inline
Number of instructions carried by this object.
Definition at line 275 of file pipe_data.hh.
References Minor::BranchData::isBubble(), Minor::BranchData::reportData(), and ArmISA::width.
Referenced by Minor::Decode::evaluate(), Minor::Execute::issue(), and resize().
Member Data Documentation
insts
MinorDynInstPtr Minor::ForwardInstData::insts[MAX_FORWARD_INSTS]
Array of carried insts, ref counted.
Definition at line 259 of file pipe_data.hh.
Referenced by bubbleFill(), Minor::Execute::commit(), Minor::Decode::evaluate(), Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), isBubble(), Minor::Execute::issue(), operator=(), and reportData().
numInsts
unsigned int Minor::ForwardInstData::numInsts
The number of insts slots that can be expected to be valid insts.
Definition at line 262 of file pipe_data.hh.
Referenced by bubbleFill(), isBubble(), operator=(), reportData(), and resize().
threadId
ThreadID Minor::ForwardInstData::threadId
Thread associated with these instructions.
Definition at line 265 of file pipe_data.hh.
Referenced by Minor::Decode::evaluate(), and Minor::Fetch2::evaluate().
The documentation for this class was generated from the following files:
cpu/minor/pipe_data.hh
cpu/minor/pipe_data.cc