gem5: sc_dt::sc_signed Class Reference
sc_dt::sc_signed Class Reference
#include <sc_signed.hh>
Public Member Functions
sc_signed (int nb=sc_length_param().len())
sc_signed (const sc_signed &v)
sc_signed (const sc_unsigned &v)
template<class T >
sc_signed (const sc_generic_base< T > &v)
sc_signed (const sc_bv_base &v)
sc_signed (const sc_lv_base &v)
sc_signed (const sc_int_subref_r &v)
sc_signed (const sc_uint_subref_r &v)
sc_signed (const sc_signed_subref_r &v)
sc_signed (const sc_unsigned_subref_r &v)
const sc_signed & operator= (const sc_signed &v)
const sc_signed & operator= (const sc_signed_subref_r &a)
template<class T >
const sc_signed & operator= (const sc_generic_base< T > &a)
const sc_signed & operator= (const sc_unsigned &v)
const sc_signed & operator= (const sc_unsigned_subref_r &a)
const sc_signed & operator= (const char *v)
const sc_signed & operator= (int64 v)
const sc_signed & operator= (uint64 v)
const sc_signed & operator= (long v)
const sc_signed & operator= (unsigned long v)
const sc_signed & operator= (int v)
const sc_signed & operator= (unsigned int v)
const sc_signed & operator= (double v)
const sc_signed & operator= (const sc_int_base &v)
const sc_signed & operator= (const sc_uint_base &v)
const sc_signed & operator= (const sc_bv_base &)
const sc_signed & operator= (const sc_lv_base &)
const sc_signed & operator= (const sc_fxval &)
const sc_signed & operator= (const sc_fxval_fast &)
const sc_signed & operator= (const sc_fxnum &)
const sc_signed & operator= (const sc_fxnum_fast &)
virtual ~sc_signed ()
sc_digit * get_raw () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
sc_signed & operator++ ()
const sc_signed operator++ (int)
sc_signed & operator-- ()
const sc_signed operator-- (int)
void check_index (int i) const
void invalid_index (int i) const
sc_signed_bitref & operator[] (int i)
const sc_signed_bitref_r & operator[] (int i) const
sc_signed_bitref & bit (int i)
const sc_signed_bitref_r & bit (int i) const
void check_range (int l, int r) const
void invalid_range (int l, int r) const
sc_signed_subref & range (int i, int j)
const sc_signed_subref_r & range (int i, int j) const
sc_signed_subref & operator() (int i, int j)
const sc_signed_subref_r & operator() (int i, int j) const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
void dump (::std::ostream &os=::std::cout) const
int length () const
bool iszero () const
bool sign () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
bool test (int i) const
void set (int i)
void clear (int i)
void set (int i, bool v)
void invert (int i)
void reverse ()
void get_packed_rep (sc_digit *buf) const
void set_packed_rep (sc_digit *buf)
const sc_signed & operator+= (const sc_signed &v)
const sc_signed & operator+= (const sc_unsigned &v)
const sc_signed & operator+= (int64 v)
const sc_signed & operator+= (uint64 v)
const sc_signed & operator+= (long v)
const sc_signed & operator+= (unsigned long v)
const sc_signed & operator+= (int v)
const sc_signed & operator+= (unsigned int v)
const sc_signed & operator+= (const sc_int_base &v)
const sc_signed & operator+= (const sc_uint_base &v)
const sc_signed & operator-= (const sc_signed &v)
const sc_signed & operator-= (const sc_unsigned &v)
const sc_signed & operator-= (int64 v)
const sc_signed & operator-= (uint64 v)
const sc_signed & operator-= (long v)
const sc_signed & operator-= (unsigned long v)
const sc_signed & operator-= (int v)
const sc_signed & operator-= (unsigned int v)
const sc_signed & operator-= (const sc_int_base &v)
const sc_signed & operator-= (const sc_uint_base &v)
const sc_signed & operator*= (const sc_signed &v)
const sc_signed & operator*= (const sc_unsigned &v)
const sc_signed & operator*= (int64 v)
const sc_signed & operator*= (uint64 v)
const sc_signed & operator*= (long v)
const sc_signed & operator*= (unsigned long v)
const sc_signed & operator*= (int v)
const sc_signed & operator*= (unsigned int v)
const sc_signed & operator*= (const sc_int_base &v)
const sc_signed & operator*= (const sc_uint_base &v)
const sc_signed & operator/= (const sc_signed &v)
const sc_signed & operator/= (const sc_unsigned &v)
const sc_signed & operator/= (int64 v)
const sc_signed & operator/= (uint64 v)
const sc_signed & operator/= (long v)
const sc_signed & operator/= (unsigned long v)
const sc_signed & operator/= (int v)
const sc_signed & operator/= (unsigned int v)
const sc_signed & operator/= (const sc_int_base &v)
const sc_signed & operator/= (const sc_uint_base &v)
const sc_signed & operator%= (const sc_signed &v)
const sc_signed & operator%= (const sc_unsigned &v)
const sc_signed & operator%= (int64 v)
const sc_signed & operator%= (uint64 v)
const sc_signed & operator%= (long v)
const sc_signed & operator%= (unsigned long v)
const sc_signed & operator%= (int v)
const sc_signed & operator%= (unsigned int v)
const sc_signed & operator%= (const sc_int_base &v)
const sc_signed & operator%= (const sc_uint_base &v)
const sc_signed & operator&= (const sc_signed &v)
const sc_signed & operator&= (const sc_unsigned &v)
const sc_signed & operator&= (int64 v)
const sc_signed & operator&= (uint64 v)
const sc_signed & operator&= (long v)
const sc_signed & operator&= (unsigned long v)
const sc_signed & operator&= (int v)
const sc_signed & operator&= (unsigned int v)
const sc_signed & operator&= (const sc_int_base &v)
const sc_signed & operator&= (const sc_uint_base &v)
const sc_signed & operator|= (const sc_signed &v)
const sc_signed & operator|= (const sc_unsigned &v)
const sc_signed & operator|= (int64 v)
const sc_signed & operator|= (uint64 v)
const sc_signed & operator|= (long v)
const sc_signed & operator|= (unsigned long v)
const sc_signed & operator|= (int v)
const sc_signed & operator|= (unsigned int v)
const sc_signed & operator|= (const sc_int_base &v)
const sc_signed & operator|= (const sc_uint_base &v)
const sc_signed & operator^= (const sc_signed &v)
const sc_signed & operator^= (const sc_unsigned &v)
const sc_signed & operator^= (int64 v)
const sc_signed & operator^= (uint64 v)
const sc_signed & operator^= (long v)
const sc_signed & operator^= (unsigned long v)
const sc_signed & operator^= (int v)
const sc_signed & operator^= (unsigned int v)
const sc_signed & operator^= (const sc_int_base &v)
const sc_signed & operator^= (const sc_uint_base &v)
const sc_signed & operator<<= (const sc_signed &v)
const sc_signed & operator<<= (const sc_unsigned &v)
const sc_signed & operator<<= (int64 v)
const sc_signed & operator<<= (uint64 v)
const sc_signed & operator<<= (long v)
const sc_signed & operator<<= (unsigned long v)
const sc_signed & operator<<= (int v)
const sc_signed & operator<<= (unsigned int v)
const sc_signed & operator<<= (const sc_int_base &v)
const sc_signed & operator<<= (const sc_uint_base &v)
const sc_signed & operator>>= (const sc_signed &v)
const sc_signed & operator>>= (const sc_unsigned &v)
const sc_signed & operator>>= (int64 v)
const sc_signed & operator>>= (uint64 v)
const sc_signed & operator>>= (long v)
const sc_signed & operator>>= (unsigned long v)
const sc_signed & operator>>= (int v)
const sc_signed & operator>>= (unsigned int v)
const sc_signed & operator>>= (const sc_int_base &v)
const sc_signed & operator>>= (const sc_uint_base &v)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Private Types
typedef bool elemtype
Private Member Functions
void invalid_init (const char *type_name, int nb) const
sc_signed (const sc_signed &v, small_type s)
sc_signed (const sc_unsigned &v, small_type s)
sc_signed (small_type s, int nb, int nd, sc_digit *d, bool alloc=true)
sc_signed (const sc_signed *u, int l, int r)
sc_signed (const sc_unsigned *u, int l, int r)
small_type default_sign () const
int num_bits (int nb) const
bool check_if_outside (int bit_num) const
void copy_digits (int nb, int nd, const sc_digit *d)
void makezero ()
void convert_2C_to_SM ()
void convert_SM_to_2C_to_SM ()
void convert_SM_to_2C ()
Private Attributes
small_type sgn
int nbits
int ndigits
sc_digit * digit
Friends
class sc_concatref
class sc_signed_bitref_r
class sc_signed_bitref
class sc_signed_subref_r
class sc_signed_subref
class sc_unsigned
class sc_unsigned_subref
sc_signed operator+ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator+ (const sc_signed &u, const sc_unsigned &v)
sc_signed operator+ (const sc_unsigned &u, int64 v)
sc_signed operator+ (const sc_unsigned &u, long v)
sc_signed operator+ (const sc_unsigned &u, int v)
sc_signed operator+ (int64 u, const sc_unsigned &v)
sc_signed operator+ (long u, const sc_unsigned &v)
sc_signed operator+ (int u, const sc_unsigned &v)
sc_signed operator+ (const sc_signed &u, const sc_signed &v)
sc_signed operator+ (const sc_signed &u, int64 v)
sc_signed operator+ (const sc_signed &u, uint64 v)
sc_signed operator+ (const sc_signed &u, long v)
sc_signed operator+ (const sc_signed &u, unsigned long v)
sc_signed operator+ (const sc_signed &u, int v)
sc_signed operator+ (const sc_signed &u, unsigned int v)
sc_signed operator+ (int64 u, const sc_signed &v)
sc_signed operator+ (uint64 u, const sc_signed &v)
sc_signed operator+ (long u, const sc_signed &v)
sc_signed operator+ (unsigned long u, const sc_signed &v)
sc_signed operator+ (int u, const sc_signed &v)
sc_signed operator+ (unsigned int u, const sc_signed &v)
sc_signed operator+ (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator+ (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator+ (const sc_signed &u, const sc_int_base &v)
sc_signed operator+ (const sc_signed &u, const sc_uint_base &v)
sc_signed operator+ (const sc_int_base &u, const sc_signed &v)
sc_signed operator+ (const sc_uint_base &u, const sc_signed &v)
sc_signed operator- (const sc_unsigned &u, const sc_signed &v)
sc_signed operator- (const sc_signed &u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, const sc_unsigned &v)
sc_signed operator- (const sc_unsigned &u, int64 v)
sc_signed operator- (const sc_unsigned &u, uint64 v)
sc_signed operator- (const sc_unsigned &u, long v)
sc_signed operator- (const sc_unsigned &u, unsigned long v)
sc_signed operator- (const sc_unsigned &u, int v)
sc_signed operator- (const sc_unsigned &u, unsigned int v)
sc_signed operator- (int64 u, const sc_unsigned &v)
sc_signed operator- (uint64 u, const sc_unsigned &v)
sc_signed operator- (long u, const sc_unsigned &v)
sc_signed operator- (unsigned long u, const sc_unsigned &v)
sc_signed operator- (int u, const sc_unsigned &v)
sc_signed operator- (unsigned int u, const sc_unsigned &v)
sc_signed operator- (const sc_signed &u, const sc_signed &v)
sc_signed operator- (const sc_signed &u, int64 v)
sc_signed operator- (const sc_signed &u, uint64 v)
sc_signed operator- (const sc_signed &u, long v)
sc_signed operator- (const sc_signed &u, unsigned long v)
sc_signed operator- (const sc_signed &u, int v)
sc_signed operator- (const sc_signed &u, unsigned int v)
sc_signed operator- (int64 u, const sc_signed &v)
sc_signed operator- (uint64 u, const sc_signed &v)
sc_signed operator- (long u, const sc_signed &v)
sc_signed operator- (unsigned long u, const sc_signed &v)
sc_signed operator- (int u, const sc_signed &v)
sc_signed operator- (unsigned int u, const sc_signed &v)
sc_signed operator- (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator- (const sc_unsigned &u, const sc_uint_base &v)
sc_signed operator- (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator- (const sc_uint_base &u, const sc_unsigned &v)
sc_signed operator- (const sc_signed &u, const sc_int_base &v)
sc_signed operator- (const sc_signed &u, const sc_uint_base &v)
sc_signed operator- (const sc_int_base &u, const sc_signed &v)
sc_signed operator- (const sc_uint_base &u, const sc_signed &v)
sc_signed operator* (const sc_unsigned &u, const sc_signed &v)
sc_signed operator* (const sc_signed &u, const sc_unsigned &v)
sc_signed operator* (const sc_unsigned &u, int64 v)
sc_signed operator* (const sc_unsigned &u, long v)
sc_signed operator* (const sc_unsigned &u, int v)
sc_signed operator* (int64 u, const sc_unsigned &v)
sc_signed operator* (long u, const sc_unsigned &v)
sc_signed operator* (int u, const sc_unsigned &v)
sc_signed operator* (const sc_signed &u, const sc_signed &v)
sc_signed operator* (const sc_signed &u, int64 v)
sc_signed operator* (const sc_signed &u, uint64 v)
sc_signed operator* (const sc_signed &u, long v)
sc_signed operator* (const sc_signed &u, unsigned long v)
sc_signed operator* (const sc_signed &u, int v)
sc_signed operator* (const sc_signed &u, unsigned int v)
sc_signed operator* (int64 u, const sc_signed &v)
sc_signed operator* (uint64 u, const sc_signed &v)
sc_signed operator* (long u, const sc_signed &v)
sc_signed operator* (unsigned long u, const sc_signed &v)
sc_signed operator* (int u, const sc_signed &v)
sc_signed operator* (unsigned int u, const sc_signed &v)
sc_signed operator* (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator* (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator* (const sc_signed &u, const sc_int_base &v)
sc_signed operator* (const sc_signed &u, const sc_uint_base &v)
sc_signed operator* (const sc_int_base &u, const sc_signed &v)
sc_signed operator* (const sc_uint_base &u, const sc_signed &v)
sc_signed operator/ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator/ (const sc_signed &u, const sc_unsigned &v)
sc_signed operator/ (const sc_unsigned &u, int64 v)
sc_signed operator/ (const sc_unsigned &u, long v)
sc_signed operator/ (const sc_unsigned &u, int v)
sc_signed operator/ (int64 u, const sc_unsigned &v)
sc_signed operator/ (long u, const sc_unsigned &v)
sc_signed operator/ (int u, const sc_unsigned &v)
sc_signed operator/ (const sc_signed &u, const sc_signed &v)
sc_signed operator/ (const sc_signed &u, int64 v)
sc_signed operator/ (const sc_signed &u, uint64 v)
sc_signed operator/ (const sc_signed &u, long v)
sc_signed operator/ (const sc_signed &u, unsigned long v)
sc_signed operator/ (const sc_signed &u, int v)
sc_signed operator/ (const sc_signed &u, unsigned int v)
sc_signed operator/ (int64 u, const sc_signed &v)
sc_signed operator/ (uint64 u, const sc_signed &v)
sc_signed operator/ (long u, const sc_signed &v)
sc_signed operator/ (unsigned long u, const sc_signed &v)
sc_signed operator/ (int u, const sc_signed &v)
sc_signed operator/ (unsigned int u, const sc_signed &v)
sc_signed operator/ (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator/ (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator/ (const sc_signed &u, const sc_int_base &v)
sc_signed operator/ (const sc_signed &u, const sc_uint_base &v)
sc_signed operator/ (const sc_int_base &u, const sc_signed &v)
sc_signed operator/ (const sc_uint_base &u, const sc_signed &v)
sc_signed operator% (const sc_unsigned &u, const sc_signed &v)
sc_signed operator% (const sc_signed &u, const sc_unsigned &v)
sc_signed operator% (const sc_unsigned &u, int64 v)
sc_signed operator% (const sc_unsigned &u, long v)
sc_signed operator% (const sc_unsigned &u, int v)
sc_signed operator% (int64 u, const sc_unsigned &v)
sc_signed operator% (long u, const sc_unsigned &v)
sc_signed operator% (int u, const sc_unsigned &v)
sc_signed operator% (const sc_signed &u, const sc_signed &v)
sc_signed operator% (const sc_signed &u, int64 v)
sc_signed operator% (const sc_signed &u, uint64 v)
sc_signed operator% (const sc_signed &u, long v)
sc_signed operator% (const sc_signed &u, unsigned long v)
sc_signed operator% (const sc_signed &u, int v)
sc_signed operator% (const sc_signed &u, unsigned int v)
sc_signed operator% (int64 u, const sc_signed &v)
sc_signed operator% (uint64 u, const sc_signed &v)
sc_signed operator% (long u, const sc_signed &v)
sc_signed operator% (unsigned long u, const sc_signed &v)
sc_signed operator% (int u, const sc_signed &v)
sc_signed operator% (unsigned int u, const sc_signed &v)
sc_signed operator% (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator% (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator% (const sc_signed &u, const sc_int_base &v)
sc_signed operator% (const sc_signed &u, const sc_uint_base &v)
sc_signed operator% (const sc_int_base &u, const sc_signed &v)
sc_signed operator% (const sc_uint_base &u, const sc_signed &v)
sc_signed operator& (const sc_unsigned &u, const sc_signed &v)
sc_signed operator& (const sc_signed &u, const sc_unsigned &v)
sc_signed operator& (const sc_unsigned &u, int64 v)
sc_signed operator& (const sc_unsigned &u, long v)
sc_signed operator& (const sc_unsigned &u, int v)
sc_signed operator& (int64 u, const sc_unsigned &v)
sc_signed operator& (long u, const sc_unsigned &v)
sc_signed operator& (int u, const sc_unsigned &v)
sc_signed operator& (const sc_signed &u, const sc_signed &v)
sc_signed operator& (const sc_signed &u, int64 v)
sc_signed operator& (const sc_signed &u, uint64 v)
sc_signed operator& (const sc_signed &u, long v)
sc_signed operator& (const sc_signed &u, unsigned long v)
sc_signed operator& (const sc_signed &u, int v)
sc_signed operator& (const sc_signed &u, unsigned int v)
sc_signed operator& (int64 u, const sc_signed &v)
sc_signed operator& (uint64 u, const sc_signed &v)
sc_signed operator& (long u, const sc_signed &v)
sc_signed operator& (unsigned long u, const sc_signed &v)
sc_signed operator& (int u, const sc_signed &v)
sc_signed operator& (unsigned int u, const sc_signed &v)
sc_signed operator& (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator& (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator& (const sc_signed &u, const sc_int_base &v)
sc_signed operator& (const sc_signed &u, const sc_uint_base &v)
sc_signed operator& (const sc_int_base &u, const sc_signed &v)
sc_signed operator& (const sc_uint_base &u, const sc_signed &v)
sc_signed operator| (const sc_unsigned &u, const sc_signed &v)
sc_signed operator| (const sc_signed &u, const sc_unsigned &v)
sc_signed operator| (const sc_unsigned &u, int64 v)
sc_signed operator| (const sc_unsigned &u, long v)
sc_signed operator| (const sc_unsigned &u, int v)
sc_signed operator| (int64 u, const sc_unsigned &v)
sc_signed operator| (long u, const sc_unsigned &v)
sc_signed operator| (int u, const sc_unsigned &v)
sc_signed operator| (const sc_signed &u, const sc_signed &v)
sc_signed operator| (const sc_signed &u, int64 v)
sc_signed operator| (const sc_signed &u, uint64 v)
sc_signed operator| (const sc_signed &u, long v)
sc_signed operator| (const sc_signed &u, unsigned long v)
sc_signed operator| (const sc_signed &u, int v)
sc_signed operator| (const sc_signed &u, unsigned int v)
sc_signed operator| (int64 u, const sc_signed &v)
sc_signed operator| (uint64 u, const sc_signed &v)
sc_signed operator| (long u, const sc_signed &v)
sc_signed operator| (unsigned long u, const sc_signed &v)
sc_signed operator| (int u, const sc_signed &v)
sc_signed operator| (unsigned int u, const sc_signed &v)
sc_signed operator| (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator| (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator| (const sc_signed &u, const sc_int_base &v)
sc_signed operator| (const sc_signed &u, const sc_uint_base &v)
sc_signed operator| (const sc_int_base &u, const sc_signed &v)
sc_signed operator| (const sc_uint_base &u, const sc_signed &v)
sc_signed operator^ (const sc_unsigned &u, const sc_signed &v)
sc_signed operator^ (const sc_signed &u, const sc_unsigned &v)
sc_signed operator^ (const sc_unsigned &u, int64 v)
sc_signed operator^ (const sc_unsigned &u, long v)
sc_signed operator^ (const sc_unsigned &u, int v)
sc_signed operator^ (int64 u, const sc_unsigned &v)
sc_signed operator^ (long u, const sc_unsigned &v)
sc_signed operator^ (int u, const sc_unsigned &v)
sc_signed operator^ (const sc_signed &u, const sc_signed &v)
sc_signed operator^ (const sc_signed &u, int64 v)
sc_signed operator^ (const sc_signed &u, uint64 v)
sc_signed operator^ (const sc_signed &u, long v)
sc_signed operator^ (const sc_signed &u, unsigned long v)
sc_signed operator^ (const sc_signed &u, int v)
sc_signed operator^ (const sc_signed &u, unsigned int v)
sc_signed operator^ (int64 u, const sc_signed &v)
sc_signed operator^ (uint64 u, const sc_signed &v)
sc_signed operator^ (long u, const sc_signed &v)
sc_signed operator^ (unsigned long u, const sc_signed &v)
sc_signed operator^ (int u, const sc_signed &v)
sc_signed operator^ (unsigned int u, const sc_signed &v)
sc_signed operator^ (const sc_unsigned &u, const sc_int_base &v)
sc_signed operator^ (const sc_int_base &u, const sc_unsigned &v)
sc_signed operator^ (const sc_signed &u, const sc_int_base &v)
sc_signed operator^ (const sc_signed &u, const sc_uint_base &v)
sc_signed operator^ (const sc_int_base &u, const sc_signed &v)
sc_signed operator^ (const sc_uint_base &u, const sc_signed &v)
sc_unsigned operator<< (const sc_unsigned &u, const sc_signed &v)
sc_signed operator<< (const sc_signed &u, const sc_unsigned &v)
sc_signed operator<< (const sc_signed &u, const sc_signed &v)
sc_signed operator<< (const sc_signed &u, int64 v)
sc_signed operator<< (const sc_signed &u, uint64 v)
sc_signed operator<< (const sc_signed &u, long v)
sc_signed operator<< (const sc_signed &u, unsigned long v)
sc_signed operator<< (const sc_signed &u, int v)
sc_signed operator<< (const sc_signed &u, unsigned int v)
sc_signed operator<< (const sc_signed &u, const sc_int_base &v)
sc_signed operator<< (const sc_signed &u, const sc_uint_base &v)
sc_unsigned operator>> (const sc_unsigned &u, const sc_signed &v)
sc_signed operator>> (const sc_signed &u, const sc_unsigned &v)
sc_signed operator>> (const sc_signed &u, const sc_signed &v)
sc_signed operator>> (const sc_signed &u, int64 v)
sc_signed operator>> (const sc_signed &u, uint64 v)
sc_signed operator>> (const sc_signed &u, long v)
sc_signed operator>> (const sc_signed &u, unsigned long v)
sc_signed operator>> (const sc_signed &u, int v)
sc_signed operator>> (const sc_signed &u, unsigned int v)
sc_signed operator>> (const sc_signed &u, const sc_int_base &v)
sc_signed operator>> (const sc_signed &u, const sc_uint_base &v)
sc_signed operator+ (const sc_signed &u)
sc_signed operator- (const sc_signed &u)
sc_signed operator- (const sc_unsigned &u)
bool operator== (const sc_unsigned &u, const sc_signed &v)
bool operator== (const sc_signed &u, const sc_unsigned &v)
bool operator== (const sc_signed &u, const sc_signed &v)
bool operator== (const sc_signed &u, int64 v)
bool operator== (const sc_signed &u, uint64 v)
bool operator== (const sc_signed &u, long v)
bool operator== (const sc_signed &u, unsigned long v)
bool operator== (const sc_signed &u, int v)
bool operator== (const sc_signed &u, unsigned int v)
bool operator== (int64 u, const sc_signed &v)
bool operator== (uint64 u, const sc_signed &v)
bool operator== (long u, const sc_signed &v)
bool operator== (unsigned long u, const sc_signed &v)
bool operator== (int u, const sc_signed &v)
bool operator== (unsigned int u, const sc_signed &v)
bool operator== (const sc_signed &u, const sc_int_base &v)
bool operator== (const sc_signed &u, const sc_uint_base &v)
bool operator== (const sc_int_base &u, const sc_signed &v)
bool operator== (const sc_uint_base &u, const sc_signed &v)
bool operator!= (const sc_unsigned &u, const sc_signed &v)
bool operator!= (const sc_signed &u, const sc_unsigned &v)
bool operator!= (const sc_signed &u, const sc_signed &v)
bool operator!= (const sc_signed &u, int64 v)
bool operator!= (const sc_signed &u, uint64 v)
bool operator!= (const sc_signed &u, long v)
bool operator!= (const sc_signed &u, unsigned long v)
bool operator!= (const sc_signed &u, int v)
bool operator!= (const sc_signed &u, unsigned int v)
bool operator!= (int64 u, const sc_signed &v)
bool operator!= (uint64 u, const sc_signed &v)
bool operator!= (long u, const sc_signed &v)
bool operator!= (unsigned long u, const sc_signed &v)
bool operator!= (int u, const sc_signed &v)
bool operator!= (unsigned int u, const sc_signed &v)
bool operator!= (const sc_signed &u, const sc_int_base &v)
bool operator!= (const sc_signed &u, const sc_uint_base &v)
bool operator!= (const sc_int_base &u, const sc_signed &v)
bool operator!= (const sc_uint_base &u, const sc_signed &v)
bool operator< (const sc_unsigned &u, const sc_signed &v)
bool operator< (const sc_signed &u, const sc_unsigned &v)
bool operator< (const sc_signed &u, const sc_signed &v)
bool operator< (const sc_signed &u, int64 v)
bool operator< (const sc_signed &u, uint64 v)
bool operator< (const sc_signed &u, long v)
bool operator< (const sc_signed &u, unsigned long v)
bool operator< (const sc_signed &u, int v)
bool operator< (const sc_signed &u, unsigned int v)
bool operator< (int64 u, const sc_signed &v)
bool operator< (uint64 u, const sc_signed &v)
bool operator< (long u, const sc_signed &v)
bool operator< (unsigned long u, const sc_signed &v)
bool operator< (int u, const sc_signed &v)
bool operator< (unsigned int u, const sc_signed &v)
bool operator< (const sc_signed &u, const sc_int_base &v)
bool operator< (const sc_signed &u, const sc_uint_base &v)
bool operator< (const sc_int_base &u, const sc_signed &v)
bool operator< (const sc_uint_base &u, const sc_signed &v)
bool operator<= (const sc_unsigned &u, const sc_signed &v)
bool operator<= (const sc_signed &u, const sc_unsigned &v)
bool operator<= (const sc_signed &u, const sc_signed &v)
bool operator<= (const sc_signed &u, int64 v)
bool operator<= (const sc_signed &u, uint64 v)
bool operator<= (const sc_signed &u, long v)
bool operator<= (const sc_signed &u, unsigned long v)
bool operator<= (const sc_signed &u, int v)
bool operator<= (const sc_signed &u, unsigned int v)
bool operator<= (int64 u, const sc_signed &v)
bool operator<= (uint64 u, const sc_signed &v)
bool operator<= (long u, const sc_signed &v)
bool operator<= (unsigned long u, const sc_signed &v)
bool operator<= (int u, const sc_signed &v)
bool operator<= (unsigned int u, const sc_signed &v)
bool operator<= (const sc_signed &u, const sc_int_base &v)
bool operator<= (const sc_signed &u, const sc_uint_base &v)
bool operator<= (const sc_int_base &u, const sc_signed &v)
bool operator<= (const sc_uint_base &u, const sc_signed &v)
bool operator> (const sc_unsigned &u, const sc_signed &v)
bool operator> (const sc_signed &u, const sc_unsigned &v)
bool operator> (const sc_signed &u, const sc_signed &v)
bool operator> (const sc_signed &u, int64 v)
bool operator> (const sc_signed &u, uint64 v)
bool operator> (const sc_signed &u, long v)
bool operator> (const sc_signed &u, unsigned long v)
bool operator> (const sc_signed &u, int v)
bool operator> (const sc_signed &u, unsigned int v)
bool operator> (int64 u, const sc_signed &v)
bool operator> (uint64 u, const sc_signed &v)
bool operator> (long u, const sc_signed &v)
bool operator> (unsigned long u, const sc_signed &v)
bool operator> (int u, const sc_signed &v)
bool operator> (unsigned int u, const sc_signed &v)
bool operator> (const sc_signed &u, const sc_int_base &v)
bool operator> (const sc_signed &u, const sc_uint_base &v)
bool operator> (const sc_int_base &u, const sc_signed &v)
bool operator> (const sc_uint_base &u, const sc_signed &v)
bool operator>= (const sc_unsigned &u, const sc_signed &v)
bool operator>= (const sc_signed &u, const sc_unsigned &v)
bool operator>= (const sc_signed &u, const sc_signed &v)
bool operator>= (const sc_signed &u, int64 v)
bool operator>= (const sc_signed &u, uint64 v)
bool operator>= (const sc_signed &u, long v)
bool operator>= (const sc_signed &u, unsigned long v)
bool operator>= (const sc_signed &u, int v)
bool operator>= (const sc_signed &u, unsigned int v)
bool operator>= (int64 u, const sc_signed &v)
bool operator>= (uint64 u, const sc_signed &v)
bool operator>= (long u, const sc_signed &v)
bool operator>= (unsigned long u, const sc_signed &v)
bool operator>= (int u, const sc_signed &v)
bool operator>= (unsigned int u, const sc_signed &v)
bool operator>= (const sc_signed &u, const sc_int_base &v)
bool operator>= (const sc_signed &u, const sc_uint_base &v)
bool operator>= (const sc_int_base &u, const sc_signed &v)
bool operator>= (const sc_uint_base &u, const sc_signed &v)
sc_signed operator~ (const sc_signed &u)
sc_signed add_signed_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_signed sub_signed_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_signed mul_signed_friend (small_type s, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_signed div_signed_friend (small_type s, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_signed mod_signed_friend (small_type us, int unb, int und, const sc_digit *ud, int vnb, int vnd, const sc_digit *vd)
sc_signed and_signed_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_signed or_signed_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
sc_signed xor_signed_friend (small_type us, int unb, int und, const sc_digit *ud, small_type vs, int vnb, int vnd, const sc_digit *vd)
Detailed Description
Definition at line 984 of file sc_signed.hh.
Member Typedef Documentation
elemtype
typedef bool sc_dt::sc_signed::elemtype private
Definition at line 995 of file sc_signed.hh.
Constructor & Destructor Documentation
sc_signed() [1/15]
sc_dt::sc_signed::sc_signed (int nb = sc_length_param().len()) explicit
sc_signed() [2/15]
sc_dt::sc_signed::sc_signed (const sc_signed & v)
sc_signed() [3/15]
sc_dt::sc_signed::sc_signed (const sc_unsigned & v)
sc_signed() [4/15]
template<class T > sc_dt::sc_signed::sc_signed (const sc_generic_base< T > & v) explicit
Definition at line 2466 of file sc_signed.hh.
References DIV_CEIL, and sc_core::sc_abort().
sc_signed() [5/15]
sc_dt::sc_signed::sc_signed (const sc_bv_base & v) explicit
sc_signed() [6/15]
sc_dt::sc_signed::sc_signed (const sc_lv_base & v) explicit
sc_signed() [7/15]
sc_dt::sc_signed::sc_signed (const sc_int_subref_r & v) explicit
sc_signed() [8/15]
sc_dt::sc_signed::sc_signed (const sc_uint_subref_r & v) explicit
sc_signed() [9/15]
sc_dt::sc_signed::sc_signed (const sc_signed_subref_r & v) explicit
sc_signed() [10/15]
sc_dt::sc_signed::sc_signed (const sc_unsigned_subref_r & v) explicit
~sc_signed()
virtual sc_dt::sc_signed::~sc_signed () inline virtual
Definition at line 1055 of file sc_signed.hh.
sc_signed() [11/15]
sc_dt::sc_signed::sc_signed (const sc_signed & v, small_type s) private
sc_signed() [12/15]
sc_dt::sc_signed::sc_signed (const sc_unsigned & v, small_type s) private
sc_signed() [13/15]
sc_dt::sc_signed::sc_signed (small_type s, int nb, int nd, sc_digit * d, bool alloc = true) private
sc_signed() [14/15]
sc_dt::sc_signed::sc_signed (const sc_signed * u, int l, int r) private
sc_signed() [15/15]
sc_dt::sc_signed::sc_signed (const sc_unsigned * u, int l, int r) private
Member Function Documentation
and_reduce()
bool sc_dt::sc_signed::and_reduce () const
Definition at line 393 of file sc_signed.cc.
References ArmISA::i.
bit() [1/2]
sc_signed_bitref& sc_dt::sc_signed::bit (int i) inline
Definition at line 1116 of file sc_signed.hh.
References sc_dt::sc_signed_bitref_r::initialize(), and sc_dt::sc_signed_bitref::m_pool.
bit() [2/2]
const sc_signed_bitref_r& sc_dt::sc_signed::bit (int i) const inline
Definition at line 1125 of file sc_signed.hh.
References sc_dt::sc_signed_bitref_r::initialize(), and sc_dt::sc_signed_bitref::m_pool.
check_if_outside()
bool sc_dt::sc_signed::check_if_outside (int bit_num) const private
check_index()
void sc_dt::sc_signed::check_index (int i) const inline
Definition at line 1089 of file sc_signed.hh.
References ArmISA::i.
check_range()
void sc_dt::sc_signed::check_range (int l, int r) const inline
Definition at line 1144 of file sc_signed.hh.
References MipsISA::l, and MipsISA::r.
clear()
void sc_dt::sc_signed::clear (int i)
concat_get_ctrl()
bool sc_dt::sc_signed::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 158 of file sc_signed.cc.
concat_get_data()
bool sc_dt::sc_signed::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 182 of file sc_signed.cc.
concat_get_uint64()
uint64 sc_dt::sc_signed::concat_get_uint64 () const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 325 of file sc_signed.cc.
References SC_POS.
concat_length()
virtual int sc_dt::sc_signed::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1065 of file sc_signed.hh.
concat_set() [1/4]
void sc_dt::sc_signed::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 359 of file sc_signed.cc.
concat_set() [2/4]
void sc_dt::sc_signed::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 365 of file sc_signed.cc.
References length().
concat_set() [3/4]
void sc_dt::sc_signed::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 374 of file sc_signed.cc.
concat_set() [4/4]
void sc_dt::sc_signed::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >.
Definition at line 383 of file sc_signed.cc.
convert_2C_to_SM()
void sc_dt::sc_signed::convert_2C_to_SM () inline private
Definition at line 2328 of file sc_signed.hh.
References sc_dt::convert_signed_2C_to_SM().
convert_SM_to_2C()
void sc_dt::sc_signed::convert_SM_to_2C () inline private
Definition at line 2340 of file sc_signed.hh.
References sc_dt::convert_signed_SM_to_2C(), sc_dt::operator<<(), and sc_dt::operator>>().
convert_SM_to_2C_to_SM()
void sc_dt::sc_signed::convert_SM_to_2C_to_SM () inline private
Definition at line 2334 of file sc_signed.hh.
References sc_dt::convert_signed_SM_to_2C_to_SM().
copy_digits()
void sc_dt::sc_signed::copy_digits (int nb, int nd, const sc_digit * d) inline private
Definition at line 2318 of file sc_signed.hh.
References sc_dt::copy_digits_signed().
default_sign()
small_type sc_dt::sc_signed::default_sign () const inline private
Definition at line 2312 of file sc_signed.hh.
References SC_NOSIGN.
dump()
void sc_dt::sc_signed::dump (::std::ostream & os = ::std::cout) const
get_packed_rep()
void sc_dt::sc_signed::get_packed_rep (sc_digit * buf) const
get_raw()
sc_digit* sc_dt::sc_signed::get_raw () const inline
Definition at line 1063 of file sc_signed.hh.
invalid_index()
void sc_dt::sc_signed::invalid_index (int i) const
Definition at line 122 of file sc_signed.cc.
invalid_init()
void sc_dt::sc_signed::invalid_init (const char * type_name, int nb) const private
Definition at line 110 of file sc_signed.cc.
References sc_core::SC_ID_INIT_FAILED_, and SC_REPORT_ERROR.
invalid_range()
void sc_dt::sc_signed::invalid_range (int l, int r) const
Definition at line 132 of file sc_signed.cc.
invert()
void sc_dt::sc_signed::invert (int i) inline
Definition at line 1247 of file sc_signed.hh.
References ArmISA::i, sc_dt::operator+(), sc_dt::reverse(), and ArmISA::u.
iszero()
bool sc_dt::sc_signed::iszero () const
Definition at line 3895 of file sc_signed.cc.
References sc_dt::check_for_zero(), SC_NOSIGN, and SC_ZERO.
Referenced by sc_dt::scfx_rep::scfx_rep().
length()
int sc_dt::sc_signed::length () const inline
Definition at line 1222 of file sc_signed.hh.
References sc_dt::and_reduce().
Referenced by sc_dt::assign_v_(), sc_core::sc_int_sigref::concat_set(), sc_dt::sc_uint_bitref::concat_set(), sc_dt::sc_int_bitref::concat_set(), sc_core::sc_uint_sigref::concat_set(), sc_dt::sc_uint_subref::concat_set(), sc_dt::sc_int_subref::concat_set(), sc_dt::sc_uint_base::concat_set(), sc_dt::sc_int_base::concat_set(), sc_dt::sc_unsigned::concat_set(), concat_set(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_unsigned::operator=(), operator=(), and sc_dt::scfx_rep::scfx_rep().
makezero()
void sc_dt::sc_signed::makezero () inline private
Definition at line 2323 of file sc_signed.hh.
References sc_dt::make_zero().
nand_reduce()
bool sc_dt::sc_signed::nand_reduce () const inline
Definition at line 1228 of file sc_signed.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
nor_reduce()
bool sc_dt::sc_signed::nor_reduce () const inline
Definition at line 1230 of file sc_signed.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
num_bits()
int sc_dt::sc_signed::num_bits (int nb) const inline private
Definition at line 2313 of file sc_signed.hh.
operator%=() [1/10]
const sc_signed& sc_dt::sc_signed::operator%= (const sc_signed & v)
operator%=() [2/10]
const sc_signed& sc_dt::sc_signed::operator%= (const sc_unsigned & v)
operator%=() [3/10]
const sc_signed& sc_dt::sc_signed::operator%= (int64 v)
operator%=() [4/10]
const sc_signed& sc_dt::sc_signed::operator%= (uint64 v)
operator%=() [5/10]
const sc_signed& sc_dt::sc_signed::operator%= (long v)
operator%=() [6/10]
const sc_signed& sc_dt::sc_signed::operator%= (unsigned long v)
operator%=() [7/10]
const sc_signed& sc_dt::sc_signed::operator%= (int v) inline
Definition at line 1675 of file sc_signed.hh.
operator%=() [8/10]
const sc_signed& sc_dt::sc_signed::operator%= (unsigned int v) inline
Definition at line 1680 of file sc_signed.hh.
References sc_dt::operator%(), and sc_dt::operator&().
operator%=() [9/10]
const sc_signed & sc_dt::sc_signed::operator%= (const sc_int_base & v)
Definition at line 753 of file sc_signed.cc.
operator%=() [10/10]
const sc_signed & sc_dt::sc_signed::operator%= (const sc_uint_base & v)
Definition at line 1068 of file sc_signed.cc.
operator&=() [1/10]
const sc_signed& sc_dt::sc_signed::operator &= (const sc_signed & v)
operator&=() [2/10]
const sc_signed& sc_dt::sc_signed::operator &= (const sc_unsigned & v)
operator&=() [3/10]
const sc_signed& sc_dt::sc_signed::operator &= (int64 v)
operator&=() [4/10]
const sc_signed& sc_dt::sc_signed::operator &= (uint64 v)
operator&=() [5/10]
const sc_signed& sc_dt::sc_signed::operator &= (long v)
operator&=() [6/10]
const sc_signed& sc_dt::sc_signed::operator &= (unsigned long v)
operator&=() [7/10]
const sc_signed& sc_dt::sc_signed::operator &= (int v) inline
Definition at line 1748 of file sc_signed.hh.
References sc_dt::operator&=().
operator&=() [8/10]
const sc_signed& sc_dt::sc_signed::operator &= (unsigned int v) inline
Definition at line 1753 of file sc_signed.hh.
References sc_dt::operator&(), sc_dt::operator&=(), and sc_dt::operator|().
operator&=() [9/10]
const sc_signed& sc_dt::sc_signed::operator &= (const sc_int_base & v)
operator&=() [10/10]
const sc_signed& sc_dt::sc_signed::operator &= (const sc_uint_base & v)
operator()() [1/2]
sc_signed_subref& sc_dt::sc_signed::operator() (int i, int j) inline
Definition at line 1177 of file sc_signed.hh.
References sc_dt::sc_signed_subref_r::initialize(), and sc_dt::sc_signed_subref::m_pool.
Referenced by sc_core::sc_signal< sc_dt::sc_bigint< W > >::read_part().
operator()() [2/2]
const sc_signed_subref_r& sc_dt::sc_signed::operator() (int i, int j) const inline
Definition at line 1186 of file sc_signed.hh.
References sc_dt::sc_signed_subref_r::initialize(), sc_dt::sc_signed_subref::m_pool, sc_dt::SC_DEC, and sc_dt::to_string().
operator*=() [1/10]
const sc_signed& sc_dt::sc_signed::operator*= (const sc_signed & v)
operator*=() [2/10]
const sc_signed& sc_dt::sc_signed::operator*= (const sc_unsigned & v)
operator*=() [3/10]
const sc_signed& sc_dt::sc_signed::operator*= (int64 v)
operator*=() [4/10]
const sc_signed& sc_dt::sc_signed::operator*= (uint64 v)
operator*=() [5/10]
const sc_signed& sc_dt::sc_signed::operator*= (long v)
operator*=() [6/10]
const sc_signed& sc_dt::sc_signed::operator*= (unsigned long v)
operator*=() [7/10]
const sc_signed& sc_dt::sc_signed::operator*= (int v) inline
Definition at line 1521 of file sc_signed.hh.
operator*=() [8/10]
const sc_signed& sc_dt::sc_signed::operator*= (unsigned int v) inline
Definition at line 1526 of file sc_signed.hh.
References sc_dt::operator*(), and sc_dt::operator/().
operator*=() [9/10]
const sc_signed & sc_dt::sc_signed::operator*= (const sc_int_base & v)
Definition at line 691 of file sc_signed.cc.
operator*=() [10/10]
const sc_signed & sc_dt::sc_signed::operator*= (const sc_uint_base & v)
Definition at line 1030 of file sc_signed.cc.
operator++() [1/2]
sc_signed& sc_dt::sc_signed::operator++ ()
operator++() [2/2]
const sc_signed sc_dt::sc_signed::operator++ (int)
operator+=() [1/10]
const sc_signed& sc_dt::sc_signed::operator+= (const sc_signed & v)
operator+=() [2/10]
const sc_signed& sc_dt::sc_signed::operator+= (const sc_unsigned & v)
operator+=() [3/10]
const sc_signed& sc_dt::sc_signed::operator+= (int64 v)
operator+=() [4/10]
const sc_signed& sc_dt::sc_signed::operator+= (uint64 v)
operator+=() [5/10]
const sc_signed& sc_dt::sc_signed::operator+= (long v)
operator+=() [6/10]
const sc_signed& sc_dt::sc_signed::operator+= (unsigned long v)
operator+=() [7/10]
const sc_signed& sc_dt::sc_signed::operator+= (int v) inline
Definition at line 1350 of file sc_signed.hh.
operator+=() [8/10]
const sc_signed& sc_dt::sc_signed::operator+= (unsigned int v) inline
Definition at line 1355 of file sc_signed.hh.
References sc_dt::operator+(), and sc_dt::operator-().
operator+=() [9/10]
const sc_signed & sc_dt::sc_signed::operator+= (const sc_int_base & v)
Definition at line 629 of file sc_signed.cc.
operator+=() [10/10]
const sc_signed & sc_dt::sc_signed::operator+= (const sc_uint_base & v)
Definition at line 980 of file sc_signed.cc.
operator--() [1/2]
sc_signed& sc_dt::sc_signed::operator-- ()
operator--() [2/2]
const sc_signed sc_dt::sc_signed::operator-- (int)
operator-=() [1/10]
const sc_signed& sc_dt::sc_signed::operator-= (const sc_signed & v)
operator-=() [2/10]
const sc_signed& sc_dt::sc_signed::operator-= (const sc_unsigned & v)
operator-=() [3/10]
const sc_signed& sc_dt::sc_signed::operator-= (int64 v)
operator-=() [4/10]
const sc_signed& sc_dt::sc_signed::operator-= (uint64 v)
operator-=() [5/10]
const sc_signed& sc_dt::sc_signed::operator-= (long v)
operator-=() [6/10]
const sc_signed& sc_dt::sc_signed::operator-= (unsigned long v)
operator-=() [7/10]
const sc_signed& sc_dt::sc_signed::operator-= (int v) inline
Definition at line 1442 of file sc_signed.hh.
operator-=() [8/10]
const sc_signed& sc_dt::sc_signed::operator-= (unsigned int v) inline
Definition at line 1447 of file sc_signed.hh.
References sc_dt::operator*(), and sc_dt::operator-().
operator-=() [9/10]
const sc_signed & sc_dt::sc_signed::operator-= (const sc_int_base & v)
Definition at line 660 of file sc_signed.cc.
operator-=() [10/10]
const sc_signed & sc_dt::sc_signed::operator-= (const sc_uint_base & v)
Definition at line 1011 of file sc_signed.cc.
operator/=() [1/10]
const sc_signed& sc_dt::sc_signed::operator/= (const sc_signed & v)
operator/=() [2/10]
const sc_signed& sc_dt::sc_signed::operator/= (const sc_unsigned & v)
operator/=() [3/10]
const sc_signed& sc_dt::sc_signed::operator/= (int64 v)
operator/=() [4/10]
const sc_signed& sc_dt::sc_signed::operator/= (uint64 v)
operator/=() [5/10]
const sc_signed& sc_dt::sc_signed::operator/= (long v)
operator/=() [6/10]
const sc_signed& sc_dt::sc_signed::operator/= (unsigned long v)
operator/=() [7/10]
const sc_signed& sc_dt::sc_signed::operator/= (int v) inline
Definition at line 1598 of file sc_signed.hh.
operator/=() [8/10]
const sc_signed& sc_dt::sc_signed::operator/= (unsigned int v) inline
Definition at line 1603 of file sc_signed.hh.
References sc_dt::operator%(), and sc_dt::operator/().
operator/=() [9/10]
const sc_signed & sc_dt::sc_signed::operator/= (const sc_int_base & v)
Definition at line 722 of file sc_signed.cc.
operator/=() [10/10]
const sc_signed & sc_dt::sc_signed::operator/= (const sc_uint_base & v)
Definition at line 1049 of file sc_signed.cc.
operator<<=() [1/10]
const sc_signed& sc_dt::sc_signed::operator<<= (const sc_signed & v)
operator<<=() [2/10]
const sc_signed& sc_dt::sc_signed::operator<<= (const sc_unsigned & v)
operator<<=() [3/10]
const sc_signed& sc_dt::sc_signed::operator<<= (int64 v)
operator<<=() [4/10]
const sc_signed& sc_dt::sc_signed::operator<<= (uint64 v)
operator<<=() [5/10]
const sc_signed& sc_dt::sc_signed::operator<<= (long v)
operator<<=() [6/10]
const sc_signed& sc_dt::sc_signed::operator<<= (unsigned long v)
operator<<=() [7/10]
const sc_signed& sc_dt::sc_signed::operator<<= (int v) inline
Definition at line 1950 of file sc_signed.hh.
operator<<=() [8/10]
const sc_signed& sc_dt::sc_signed::operator<<= (unsigned int v) inline
Definition at line 1955 of file sc_signed.hh.
References sc_dt::operator<<(), and sc_dt::operator>>().
operator<<=() [9/10]
const sc_signed & sc_dt::sc_signed::operator<<= (const sc_int_base & v)
Definition at line 859 of file sc_signed.cc.
operator<<=() [10/10]
const sc_signed & sc_dt::sc_signed::operator<<= (const sc_uint_base & v)
Definition at line 1138 of file sc_signed.cc.
operator=() [1/21]
const sc_signed& sc_dt::sc_signed::operator= (const sc_signed & v)
Referenced by sc_dt::sc_bigint< W >::operator=(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::update().
operator=() [2/21]
const sc_signed& sc_dt::sc_signed::operator= (const sc_signed_subref_r & a)
operator=() [3/21]
template<class T > const sc_signed& sc_dt::sc_signed::operator= (const sc_generic_base< T > & a) inline
Definition at line 1019 of file sc_signed.hh.
References ArmISA::a, and ArmISA::v.
operator=() [4/21]
const sc_signed& sc_dt::sc_signed::operator= (const sc_unsigned & v)
operator=() [5/21]
const sc_signed& sc_dt::sc_signed::operator= (const sc_unsigned_subref_r & a)
operator=() [6/21]
const sc_signed & sc_dt::sc_signed::operator= (const char * v)
Definition at line 441 of file sc_signed.cc.
References PowerISA::aa, ArmISA::len, length, sc_core::SC_ID_CONVERSION_FAILED_, sc_dt::SC_ON, SC_REPORT_ERROR, sc_dt::SC_TRN, and sc_dt::SC_WRAP.
operator=() [7/21]
const sc_signed & sc_dt::sc_signed::operator= (int64 v)
Definition at line 462 of file sc_signed.cc.
References BITS_PER_INT64, sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [8/21]
const sc_signed & sc_dt::sc_signed::operator= (uint64 v)
Definition at line 477 of file sc_signed.cc.
References BITS_PER_INT64, sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [9/21]
const sc_signed & sc_dt::sc_signed::operator= (long v)
Definition at line 491 of file sc_signed.cc.
References BITS_PER_LONG, sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [10/21]
const sc_signed & sc_dt::sc_signed::operator= (unsigned long v)
Definition at line 506 of file sc_signed.cc.
References BITS_PER_LONG, sc_dt::from_uint(), sc_dt::get_sign(), SC_ZERO, and sc_dt::vec_zero().
operator=() [11/21]
const sc_signed& sc_dt::sc_signed::operator= (int v) inline
Definition at line 1034 of file sc_signed.hh.
References operator=().
Referenced by operator=().
operator=() [12/21]
const sc_signed& sc_dt::sc_signed::operator= (unsigned int v) inline
Definition at line 1037 of file sc_signed.hh.
operator=() [13/21]
const sc_signed & sc_dt::sc_signed::operator= (double v)
Definition at line 520 of file sc_signed.cc.
References DIGIT_MASK, DIGIT_RADIX, sc_dt::is_bad_double(), sc_dt::remainder, SC_NEG, SC_POS, ArmISA::v, and sc_dt::vec_zero().
operator=() [14/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_int_base & v)
Definition at line 598 of file sc_signed.cc.
operator=() [15/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_uint_base & v)
Definition at line 961 of file sc_signed.cc.
operator=() [16/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_bv_base & v)
Definition at line 545 of file sc_signed.cc.
References sc_dt::sc_bv_base::get_bit(), ArmISA::i, sc_dt::sc_bv_base::length(), sc_dt::safe_set(), and sc_dt::sc_min().
operator=() [17/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_lv_base & v)
Definition at line 560 of file sc_signed.cc.
References sc_dt::sc_lv_base::get_bit(), ArmISA::i, sc_dt::sc_lv_base::length(), sc_dt::safe_set(), sc_dt::sc_min(), and to_bool().
operator=() [18/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_fxval & v) inline
Definition at line 65 of file scfx_other_defs.hh.
References sc_dt::sc_fxval::get_bit(), ArmISA::i, sc_dt::sc_fxval::is_normal(), length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [19/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_fxval_fast & v) inline
Definition at line 79 of file scfx_other_defs.hh.
References sc_dt::sc_fxval_fast::get_bit(), ArmISA::i, sc_dt::sc_fxval_fast::is_normal(), length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [20/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_fxnum & v) inline
Definition at line 94 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::is_normal(), length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [21/21]
const sc_signed & sc_dt::sc_signed::operator= (const sc_fxnum_fast & v) inline
Definition at line 109 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::is_normal(), length(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator>>=() [1/10]
const sc_signed& sc_dt::sc_signed::operator>>= (const sc_signed & v)
operator>>=() [2/10]
const sc_signed& sc_dt::sc_signed::operator>>= (const sc_unsigned & v)
operator>>=() [3/10]
const sc_signed& sc_dt::sc_signed::operator>>= (int64 v)
operator>>=() [4/10]
const sc_signed& sc_dt::sc_signed::operator>>= (uint64 v)
operator>>=() [5/10]
const sc_signed& sc_dt::sc_signed::operator>>= (long v)
operator>>=() [6/10]
const sc_signed& sc_dt::sc_signed::operator>>= (unsigned long v)
operator>>=() [7/10]
const sc_signed& sc_dt::sc_signed::operator>>= (int v) inline
Definition at line 1992 of file sc_signed.hh.
operator>>=() [8/10]
const sc_signed& sc_dt::sc_signed::operator>>= (unsigned int v) inline
Definition at line 1997 of file sc_signed.hh.
References sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator==(), and sc_dt::operator>>().
operator>>=() [9/10]
const sc_signed & sc_dt::sc_signed::operator>>= (const sc_int_base & v)
Definition at line 872 of file sc_signed.cc.
operator>>=() [10/10]
const sc_signed & sc_dt::sc_signed::operator>>= (const sc_uint_base & v)
Definition at line 1151 of file sc_signed.cc.
operator[]() [1/2]
sc_signed_bitref& sc_dt::sc_signed::operator[] (int i) inline
Definition at line 1098 of file sc_signed.hh.
References sc_dt::sc_signed_bitref_r::initialize(), and sc_dt::sc_signed_bitref::m_pool.
operator[]() [2/2]
const sc_signed_bitref_r& sc_dt::sc_signed::operator[] (int i) const inline
Definition at line 1107 of file sc_signed.hh.
References sc_dt::sc_signed_bitref_r::initialize(), and sc_dt::sc_signed_bitref::m_pool.
operator^=() [1/10]
const sc_signed& sc_dt::sc_signed::operator^= (const sc_signed & v)
operator^=() [2/10]
const sc_signed& sc_dt::sc_signed::operator^= (const sc_unsigned & v)
operator^=() [3/10]
const sc_signed& sc_dt::sc_signed::operator^= (int64 v)
operator^=() [4/10]
const sc_signed& sc_dt::sc_signed::operator^= (uint64 v)
operator^=() [5/10]
const sc_signed& sc_dt::sc_signed::operator^= (long v)
operator^=() [6/10]
const sc_signed& sc_dt::sc_signed::operator^= (unsigned long v)
operator^=() [7/10]
const sc_signed& sc_dt::sc_signed::operator^= (int v) inline
Definition at line 1902 of file sc_signed.hh.
References sc_dt::operator^=().
operator^=() [8/10]
const sc_signed& sc_dt::sc_signed::operator^= (unsigned int v) inline
Definition at line 1907 of file sc_signed.hh.
References sc_dt::operator<<(), sc_dt::operator^(), and sc_dt::operator^=().
operator^=() [9/10]
const sc_signed & sc_dt::sc_signed::operator^= (const sc_int_base & v)
Definition at line 846 of file sc_signed.cc.
References sc_dt::operator^=().
operator^=() [10/10]
const sc_signed & sc_dt::sc_signed::operator^= (const sc_uint_base & v)
Definition at line 1125 of file sc_signed.cc.
References sc_dt::operator^=().
operator|=() [1/10]
const sc_signed& sc_dt::sc_signed::operator|= (const sc_signed & v)
operator|=() [2/10]
const sc_signed& sc_dt::sc_signed::operator|= (const sc_unsigned & v)
operator|=() [3/10]
const sc_signed& sc_dt::sc_signed::operator|= (int64 v)
operator|=() [4/10]
const sc_signed& sc_dt::sc_signed::operator|= (uint64 v)
operator|=() [5/10]
const sc_signed& sc_dt::sc_signed::operator|= (long v)
operator|=() [6/10]
const sc_signed& sc_dt::sc_signed::operator|= (unsigned long v)
operator|=() [7/10]
const sc_signed& sc_dt::sc_signed::operator|= (int v) inline
Definition at line 1825 of file sc_signed.hh.
References sc_dt::operator|=().
operator|=() [8/10]
const sc_signed& sc_dt::sc_signed::operator|= (unsigned int v) inline
Definition at line 1830 of file sc_signed.hh.
References sc_dt::operator^(), sc_dt::operator|(), and sc_dt::operator|=().
operator|=() [9/10]
const sc_signed & sc_dt::sc_signed::operator|= (const sc_int_base & v)
Definition at line 815 of file sc_signed.cc.
References sc_dt::operator|=().
operator|=() [10/10]
const sc_signed & sc_dt::sc_signed::operator|= (const sc_uint_base & v)
Definition at line 1106 of file sc_signed.cc.
References sc_dt::operator|=().
or_reduce()
bool sc_dt::sc_signed::or_reduce () const
Definition at line 414 of file sc_signed.cc.
References SC_ZERO.
print()
void sc_dt::sc_signed::print (::std::ostream & os = ::std::cout) const inline
Definition at line 1212 of file sc_signed.hh.
References Stats::dump(), MipsISA::is, X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
range() [1/2]
sc_signed_subref& sc_dt::sc_signed::range (int i, int j) inline
Definition at line 1159 of file sc_signed.hh.
References sc_dt::sc_signed_subref_r::initialize(), and sc_dt::sc_signed_subref::m_pool.
range() [2/2]
const sc_signed_subref_r& sc_dt::sc_signed::range (int i, int j) const inline
Definition at line 1168 of file sc_signed.hh.
References sc_dt::sc_signed_subref_r::initialize(), and sc_dt::sc_signed_subref::m_pool.
reverse()
void sc_dt::sc_signed::reverse ()
scan()
void sc_dt::sc_signed::scan (::std::istream & is = ::std::cin)
Referenced by sc_dt::operator>>().
set() [1/2]
void sc_dt::sc_signed::set (int i)
set() [2/2]
void sc_dt::sc_signed::set (int i, bool v) inline
Definition at line 1239 of file sc_signed.hh.
References ArmISA::i.
set_packed_rep()
void sc_dt::sc_signed::set_packed_rep (sc_digit * buf)
sign()
bool sc_dt::sc_signed::sign () const
Definition at line 3907 of file sc_signed.cc.
References sc_dt::bit_ord(), sc_dt::one_and_zeros(), SC_NEG, and SC_NOSIGN.
Referenced by sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), and sc_dt::scfx_rep::scfx_rep().
test()
bool sc_dt::sc_signed::test (int i) const
Referenced by sc_dt::sc_signed_subref_r::and_reduce(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_signed_subref_r::or_reduce(), and sc_dt::sc_signed_subref_r::xor_reduce().
to_double()
double sc_dt::sc_signed::to_double () const
to_int()
int sc_dt::sc_signed::to_int () const
to_int64()
int64 sc_dt::sc_signed::to_int64 () const
Referenced by sc_dt::sc_int_base::sc_int_base().
to_long()
long sc_dt::sc_signed::to_long () const
Referenced by sc_dt::operator>>().
to_string() [1/2]
const std::string sc_dt::sc_signed::to_string (sc_numrep numrep = SC_DEC) const
Definition at line 577 of file sc_signed.cc.
References PowerISA::aa, ArmISA::len, length, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_string() [2/2]
const std::string sc_dt::sc_signed::to_string (sc_numrep numrep, bool w_prefix) const
Definition at line 585 of file sc_signed.cc.
References PowerISA::aa, ArmISA::len, length, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_uint()
unsigned int sc_dt::sc_signed::to_uint () const
to_uint64()
uint64 sc_dt::sc_signed::to_uint64 () const
Referenced by sc_core::sc_int_sigref::operator=(), sc_core::sc_uint_sigref::operator=(), sc_core::sc_inout< sc_dt::sc_int< W > >::operator=(), sc_core::sc_inout< sc_dt::sc_uint< W > >::operator=(), and sc_dt::sc_uint_base::sc_uint_base().
to_ulong()
unsigned long sc_dt::sc_signed::to_ulong () const
Referenced by sc_dt::operator<<().
xnor_reduce()
bool sc_dt::sc_signed::xnor_reduce () const inline
Definition at line 1232 of file sc_signed.hh.
References ArmISA::i, and sc_dt::xor_reduce().
xor_reduce()
bool sc_dt::sc_signed::xor_reduce () const
Definition at line 420 of file sc_signed.cc.
References ArmISA::i.
Friends And Related Function Documentation
add_signed_friend
sc_signed add_signed_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
and_signed_friend
sc_signed and_signed_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
div_signed_friend
sc_signed div_signed_friend (small_type s, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
mod_signed_friend
sc_signed mod_signed_friend (small_type us, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
mul_signed_friend
sc_signed mul_signed_friend (small_type s, int unb, int und, const sc_digit * ud, int vnb, int vnd, const sc_digit * vd) friend
operator!= [1/19]
bool operator!= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1877 of file sc_unsigned.cc.
operator!= [2/19]
bool operator!= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1884 of file sc_unsigned.cc.
operator!= [3/19]
bool operator!= (const sc_signed & u, const sc_signed & v) friend
operator!= [4/19]
bool operator!= (const sc_signed & u, int64 v) friend
operator!= [5/19]
bool operator!= (const sc_signed & u, uint64 v) friend
operator!= [6/19]
bool operator!= (const sc_signed & u, long v) friend
operator!= [7/19]
bool operator!= (const sc_signed & u, unsigned long v) friend
operator!= [8/19]
bool operator!= (const sc_signed & u, int v) friend
Definition at line 2064 of file sc_signed.hh.
operator!= [9/19]
bool operator!= (const sc_signed & u, unsigned int v) friend
Definition at line 2069 of file sc_signed.hh.
operator!= [10/19]
bool operator!= (int64 u, const sc_signed & v) friend
operator!= [11/19]
bool operator!= (uint64 u, const sc_signed & v) friend
operator!= [12/19]
bool operator!= (long u, const sc_signed & v) friend
operator!= [13/19]
bool operator!= (unsigned long u, const sc_signed & v) friend
operator!= [14/19]
bool operator!= (int u, const sc_signed & v) friend
Definition at line 2079 of file sc_signed.hh.
operator!= [15/19]
bool operator!= (unsigned int u, const sc_signed & v) friend
Definition at line 2084 of file sc_signed.hh.
operator!= [16/19]
bool operator!= (const sc_signed & u, const sc_int_base & v) friend
Definition at line 892 of file sc_signed.cc.
operator!= [17/19]
bool operator!= (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1171 of file sc_signed.cc.
operator!= [18/19]
bool operator!= (const sc_int_base & u, const sc_signed & v) friend
Definition at line 898 of file sc_signed.cc.
operator!= [19/19]
bool operator!= (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1177 of file sc_signed.cc.
operator% [1/27]
sc_signed operator% (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2439 of file sc_signed.cc.
operator% [2/27]
sc_signed operator% (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2453 of file sc_signed.cc.
operator% [3/27]
sc_signed operator% (const sc_unsigned & u, int64 v) friend
Definition at line 2517 of file sc_signed.cc.
operator% [4/27]
sc_signed operator% (const sc_unsigned & u, long v) friend
Definition at line 2621 of file sc_signed.cc.
operator% [5/27]
sc_signed operator% (const sc_unsigned & u, int v) friend
Definition at line 1624 of file sc_signed.hh.
operator% [6/27]
sc_signed operator% (int64 u, const sc_unsigned & v) friend
Definition at line 2535 of file sc_signed.cc.
operator% [7/27]
sc_signed operator% (long u, const sc_unsigned & v) friend
Definition at line 2640 of file sc_signed.cc.
operator% [8/27]
sc_signed operator% (int u, const sc_unsigned & v) friend
Definition at line 1632 of file sc_signed.hh.
operator% [9/27]
sc_signed operator% (const sc_signed & u, const sc_signed & v) friend
Definition at line 2467 of file sc_signed.cc.
operator% [10/27]
sc_signed operator% (const sc_signed & u, int64 v) friend
Definition at line 2481 of file sc_signed.cc.
operator% [11/27]
sc_signed operator% (const sc_signed & u, uint64 v) friend
Definition at line 2553 of file sc_signed.cc.
operator% [12/27]
sc_signed operator% (const sc_signed & u, long v) friend
Definition at line 2585 of file sc_signed.cc.
operator% [13/27]
sc_signed operator% (const sc_signed & u, unsigned long v) friend
Definition at line 2658 of file sc_signed.cc.
operator% [14/27]
sc_signed operator% (const sc_signed & u, int v) friend
Definition at line 1643 of file sc_signed.hh.
operator% [15/27]
sc_signed operator% (const sc_signed & u, unsigned int v) friend
Definition at line 1648 of file sc_signed.hh.
operator% [16/27]
sc_signed operator% (int64 u, const sc_signed & v) friend
Definition at line 2499 of file sc_signed.cc.
operator% [17/27]
sc_signed operator% (uint64 u, const sc_signed & v) friend
Definition at line 2569 of file sc_signed.cc.
operator% [18/27]
sc_signed operator% (long u, const sc_signed & v) friend
Definition at line 2603 of file sc_signed.cc.
operator% [19/27]
sc_signed operator% (unsigned long u, const sc_signed & v) friend
Definition at line 2674 of file sc_signed.cc.
operator% [20/27]
sc_signed operator% (int u, const sc_signed & v) friend
Definition at line 1658 of file sc_signed.hh.
operator% [21/27]
sc_signed operator% (unsigned int u, const sc_signed & v) friend
Definition at line 1663 of file sc_signed.hh.
operator% [22/27]
sc_signed operator% (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 729 of file sc_signed.cc.
operator% [23/27]
sc_signed operator% (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 735 of file sc_signed.cc.
operator% [24/27]
sc_signed operator% (const sc_signed & u, const sc_int_base & v) friend
Definition at line 741 of file sc_signed.cc.
operator% [25/27]
sc_signed operator% (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1056 of file sc_signed.cc.
operator% [26/27]
sc_signed operator% (const sc_int_base & u, const sc_signed & v) friend
Definition at line 747 of file sc_signed.cc.
operator% [27/27]
sc_signed operator% (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1062 of file sc_signed.cc.
operator& [1/27]
sc_signed operator & (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2704 of file sc_signed.cc.
operator& [2/27]
sc_signed operator & (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2716 of file sc_signed.cc.
operator& [3/27]
sc_signed operator & (const sc_unsigned & u, int64 v) friend
Definition at line 2768 of file sc_signed.cc.
operator& [4/27]
sc_signed operator & (const sc_unsigned & u, long v) friend
Definition at line 2852 of file sc_signed.cc.
operator& [5/27]
sc_signed operator & (const sc_unsigned & u, int v) friend
Definition at line 1703 of file sc_signed.hh.
operator& [6/27]
sc_signed operator & (int64 u, const sc_unsigned & v) friend
Definition at line 2782 of file sc_signed.cc.
operator& [7/27]
sc_signed operator & (long u, const sc_unsigned & v) friend
Definition at line 2866 of file sc_signed.cc.
operator& [8/27]
sc_signed operator & (int u, const sc_unsigned & v) friend
Definition at line 1711 of file sc_signed.hh.
operator& [9/27]
sc_signed operator & (const sc_signed & u, const sc_signed & v) friend
Definition at line 2728 of file sc_signed.cc.
operator& [10/27]
sc_signed operator & (const sc_signed & u, int64 v) friend
Definition at line 2740 of file sc_signed.cc.
operator& [11/27]
sc_signed operator & (const sc_signed & u, uint64 v) friend
Definition at line 2796 of file sc_signed.cc.
operator& [12/27]
sc_signed operator & (const sc_signed & u, long v) friend
Definition at line 2824 of file sc_signed.cc.
operator& [13/27]
sc_signed operator & (const sc_signed & u, unsigned long v) friend
Definition at line 2880 of file sc_signed.cc.
operator& [14/27]
sc_signed operator & (const sc_signed & u, int v) friend
Definition at line 1722 of file sc_signed.hh.
operator& [15/27]
sc_signed operator & (const sc_signed & u, unsigned int v) friend
Definition at line 1727 of file sc_signed.hh.
operator& [16/27]
sc_signed operator & (int64 u, const sc_signed & v) friend
Definition at line 2754 of file sc_signed.cc.
operator& [17/27]
sc_signed operator & (uint64 u, const sc_signed & v) friend
Definition at line 2810 of file sc_signed.cc.
operator& [18/27]
sc_signed operator & (long u, const sc_signed & v) friend
Definition at line 2838 of file sc_signed.cc.
operator& [19/27]
sc_signed operator & (unsigned long u, const sc_signed & v) friend
Definition at line 2894 of file sc_signed.cc.
operator& [20/27]
sc_signed operator & (int u, const sc_signed & v) friend
Definition at line 1736 of file sc_signed.hh.
operator& [21/27]
sc_signed operator & (unsigned int u, const sc_signed & v) friend
Definition at line 1738 of file sc_signed.hh.
operator& [22/27]
sc_signed operator & (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 760 of file sc_signed.cc.
operator& [23/27]
sc_signed operator & (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 766 of file sc_signed.cc.
operator& [24/27]
sc_signed operator & (const sc_signed & u, const sc_int_base & v) friend
Definition at line 772 of file sc_signed.cc.
operator& [25/27]
sc_signed operator & (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1075 of file sc_signed.cc.
operator& [26/27]
sc_signed operator & (const sc_int_base & u, const sc_signed & v) friend
Definition at line 778 of file sc_signed.cc.
operator& [27/27]
sc_signed operator & (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1081 of file sc_signed.cc.
operator* [1/27]
sc_signed operator* (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1910 of file sc_signed.cc.
operator* [2/27]
sc_signed operator* (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1924 of file sc_signed.cc.
operator* [3/27]
sc_signed operator* (const sc_unsigned & u, int64 v) friend
Definition at line 1984 of file sc_signed.cc.
operator* [4/27]
sc_signed operator* (const sc_unsigned & u, long v) friend
Definition at line 2080 of file sc_signed.cc.
operator* [5/27]
sc_signed operator* (const sc_unsigned & u, int v) friend
Definition at line 1470 of file sc_signed.hh.
operator* [6/27]
sc_signed operator* (int64 u, const sc_unsigned & v) friend
Definition at line 2000 of file sc_signed.cc.
operator* [7/27]
sc_signed operator* (long u, const sc_unsigned & v) friend
Definition at line 2096 of file sc_signed.cc.
operator* [8/27]
sc_signed operator* (int u, const sc_unsigned & v) friend
Definition at line 1478 of file sc_signed.hh.
operator* [9/27]
sc_signed operator* (const sc_signed & u, const sc_signed & v) friend
Definition at line 1938 of file sc_signed.cc.
operator* [10/27]
sc_signed operator* (const sc_signed & u, int64 v) friend
Definition at line 1952 of file sc_signed.cc.
operator* [11/27]
sc_signed operator* (const sc_signed & u, uint64 v) friend
Definition at line 2016 of file sc_signed.cc.
operator* [12/27]
sc_signed operator* (const sc_signed & u, long v) friend
Definition at line 2048 of file sc_signed.cc.
operator* [13/27]
sc_signed operator* (const sc_signed & u, unsigned long v) friend
Definition at line 2112 of file sc_signed.cc.
operator* [14/27]
sc_signed operator* (const sc_signed & u, int v) friend
Definition at line 1489 of file sc_signed.hh.
operator* [15/27]
sc_signed operator* (const sc_signed & u, unsigned int v) friend
Definition at line 1494 of file sc_signed.hh.
operator* [16/27]
sc_signed operator* (int64 u, const sc_signed & v) friend
Definition at line 1968 of file sc_signed.cc.
operator* [17/27]
sc_signed operator* (uint64 u, const sc_signed & v) friend
Definition at line 2032 of file sc_signed.cc.
operator* [18/27]
sc_signed operator* (long u, const sc_signed & v) friend
Definition at line 2064 of file sc_signed.cc.
operator* [19/27]
sc_signed operator* (unsigned long u, const sc_signed & v) friend
Definition at line 2127 of file sc_signed.cc.
operator* [20/27]
sc_signed operator* (int u, const sc_signed & v) friend
Definition at line 1504 of file sc_signed.hh.
operator* [21/27]
sc_signed operator* (unsigned int u, const sc_signed & v) friend
Definition at line 1509 of file sc_signed.hh.
operator* [22/27]
sc_signed operator* (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 667 of file sc_signed.cc.
operator* [23/27]
sc_signed operator* (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 673 of file sc_signed.cc.
operator* [24/27]
sc_signed operator* (const sc_signed & u, const sc_int_base & v) friend
Definition at line 679 of file sc_signed.cc.
operator* [25/27]
sc_signed operator* (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1018 of file sc_signed.cc.
operator* [26/27]
sc_signed operator* (const sc_int_base & u, const sc_signed & v) friend
Definition at line 685 of file sc_signed.cc.
operator* [27/27]
sc_signed operator* (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1024 of file sc_signed.cc.
operator+ [1/28]
sc_signed operator+ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1294 of file sc_signed.cc.
operator+ [2/28]
sc_signed operator+ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1309 of file sc_signed.cc.
operator+ [3/28]
sc_signed operator+ (const sc_unsigned & u, int64 v) friend
Definition at line 1373 of file sc_signed.cc.
operator+ [4/28]
sc_signed operator+ (const sc_unsigned & u, long v) friend
Definition at line 1475 of file sc_signed.cc.
operator+ [5/28]
sc_signed operator+ (const sc_unsigned & u, int v) friend
Definition at line 1299 of file sc_signed.hh.
operator+ [6/28]
sc_signed operator+ (int64 u, const sc_unsigned & v) friend
Definition at line 1390 of file sc_signed.cc.
operator+ [7/28]
sc_signed operator+ (long u, const sc_unsigned & v) friend
Definition at line 1492 of file sc_signed.cc.
operator+ [8/28]
sc_signed operator+ (int u, const sc_unsigned & v) friend
Definition at line 1307 of file sc_signed.hh.
operator+ [9/28]
sc_signed operator+ (const sc_signed & u, const sc_signed & v) friend
Definition at line 1324 of file sc_signed.cc.
operator+ [10/28]
sc_signed operator+ (const sc_signed & u, int64 v) friend
Definition at line 1339 of file sc_signed.cc.
operator+ [11/28]
sc_signed operator+ (const sc_signed & u, uint64 v) friend
Definition at line 1407 of file sc_signed.cc.
operator+ [12/28]
sc_signed operator+ (const sc_signed & u, long v) friend
Definition at line 1441 of file sc_signed.cc.
operator+ [13/28]
sc_signed operator+ (const sc_signed & u, unsigned long v) friend
Definition at line 1509 of file sc_signed.cc.
operator+ [14/28]
sc_signed operator+ (const sc_signed & u, int v) friend
Definition at line 1318 of file sc_signed.hh.
operator+ [15/28]
sc_signed operator+ (const sc_signed & u, unsigned int v) friend
Definition at line 1323 of file sc_signed.hh.
operator+ [16/28]
sc_signed operator+ (int64 u, const sc_signed & v) friend
Definition at line 1356 of file sc_signed.cc.
operator+ [17/28]
sc_signed operator+ (uint64 u, const sc_signed & v) friend
Definition at line 1424 of file sc_signed.cc.
operator+ [18/28]
sc_signed operator+ (long u, const sc_signed & v) friend
Definition at line 1458 of file sc_signed.cc.
operator+ [19/28]
sc_signed operator+ (unsigned long u, const sc_signed & v) friend
Definition at line 1526 of file sc_signed.cc.
operator+ [20/28]
sc_signed operator+ (int u, const sc_signed & v) friend
Definition at line 1333 of file sc_signed.hh.
operator+ [21/28]
sc_signed operator+ (unsigned int u, const sc_signed & v) friend
Definition at line 1338 of file sc_signed.hh.
operator+ [22/28]
sc_signed operator+ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 605 of file sc_signed.cc.
operator+ [23/28]
sc_signed operator+ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 611 of file sc_signed.cc.
operator+ [24/28]
sc_signed operator+ (const sc_signed & u, const sc_int_base & v) friend
Definition at line 617 of file sc_signed.cc.
operator+ [25/28]
sc_signed operator+ (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 968 of file sc_signed.cc.
operator+ [26/28]
sc_signed operator+ (const sc_int_base & u, const sc_signed & v) friend
Definition at line 623 of file sc_signed.cc.
operator+ [27/28]
sc_signed operator+ (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 974 of file sc_signed.cc.
operator+ [28/28]
sc_signed operator+ (const sc_signed & u) friend
Definition at line 3485 of file sc_signed.cc.
operator- [1/38]
sc_signed operator- (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1579 of file sc_signed.cc.
operator- [2/38]
sc_signed operator- (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1594 of file sc_signed.cc.
operator- [3/38]
sc_signed operator- (const sc_unsigned & u, const sc_unsigned & v) friend
Definition at line 1564 of file sc_signed.cc.
operator- [4/38]
sc_signed operator- (const sc_unsigned & u, int64 v) friend
Definition at line 1658 of file sc_signed.cc.
operator- [5/38]
sc_signed operator- (const sc_unsigned & u, uint64 v) friend
Definition at line 1727 of file sc_signed.cc.
operator- [6/38]
sc_signed operator- (const sc_unsigned & u, long v) friend
Definition at line 1795 of file sc_signed.cc.
operator- [7/38]
sc_signed operator- (const sc_unsigned & u, unsigned long v) friend
Definition at line 1863 of file sc_signed.cc.
operator- [8/38]
sc_signed operator- (const sc_unsigned & u, int v) friend
Definition at line 1379 of file sc_signed.hh.
operator- [9/38]
sc_signed operator- (const sc_unsigned & u, unsigned int v) friend
Definition at line 1384 of file sc_signed.hh.
operator- [10/38]
sc_signed operator- (int64 u, const sc_unsigned & v) friend
Definition at line 1675 of file sc_signed.cc.
operator- [11/38]
sc_signed operator- (uint64 u, const sc_unsigned & v) friend
Definition at line 1744 of file sc_signed.cc.
operator- [12/38]
sc_signed operator- (long u, const sc_unsigned & v) friend
Definition at line 1812 of file sc_signed.cc.
operator- [13/38]
sc_signed operator- (unsigned long u, const sc_unsigned & v) friend
Definition at line 1880 of file sc_signed.cc.
operator- [14/38]
sc_signed operator- (int u, const sc_unsigned & v) friend
Definition at line 1394 of file sc_signed.hh.
operator- [15/38]
sc_signed operator- (unsigned int u, const sc_unsigned & v) friend
Definition at line 1399 of file sc_signed.hh.
operator- [16/38]
sc_signed operator- (const sc_signed & u, const sc_signed & v) friend
Definition at line 1609 of file sc_signed.cc.
operator- [17/38]
sc_signed operator- (const sc_signed & u, int64 v) friend
Definition at line 1624 of file sc_signed.cc.
operator- [18/38]
sc_signed operator- (const sc_signed & u, uint64 v) friend
Definition at line 1692 of file sc_signed.cc.
operator- [19/38]
sc_signed operator- (const sc_signed & u, long v) friend
Definition at line 1761 of file sc_signed.cc.
operator- [20/38]
sc_signed operator- (const sc_signed & u, unsigned long v) friend
Definition at line 1829 of file sc_signed.cc.
operator- [21/38]
sc_signed operator- (const sc_signed & u, int v) friend
Definition at line 1410 of file sc_signed.hh.
operator- [22/38]
sc_signed operator- (const sc_signed & u, unsigned int v) friend
Definition at line 1415 of file sc_signed.hh.
operator- [23/38]
sc_signed operator- (int64 u, const sc_signed & v) friend
Definition at line 1641 of file sc_signed.cc.
operator- [24/38]
sc_signed operator- (uint64 u, const sc_signed & v) friend
Definition at line 1710 of file sc_signed.cc.
operator- [25/38]
sc_signed operator- (long u, const sc_signed & v) friend
Definition at line 1778 of file sc_signed.cc.
operator- [26/38]
sc_signed operator- (unsigned long u, const sc_signed & v) friend
Definition at line 1846 of file sc_signed.cc.
operator- [27/38]
sc_signed operator- (int u, const sc_signed & v) friend
Definition at line 1425 of file sc_signed.hh.
operator- [28/38]
sc_signed operator- (unsigned int u, const sc_signed & v) friend
Definition at line 1430 of file sc_signed.hh.
operator- [29/38]
sc_signed operator- (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 636 of file sc_signed.cc.
operator- [30/38]
sc_signed operator- (const sc_unsigned & u, const sc_uint_base & v) friend
Definition at line 987 of file sc_signed.cc.
operator- [31/38]
sc_signed operator- (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 642 of file sc_signed.cc.
operator- [32/38]
sc_signed operator- (const sc_uint_base & u, const sc_unsigned & v) friend
Definition at line 993 of file sc_signed.cc.
operator- [33/38]
sc_signed operator- (const sc_signed & u, const sc_int_base & v) friend
Definition at line 648 of file sc_signed.cc.
operator- [34/38]
sc_signed operator- (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 999 of file sc_signed.cc.
operator- [35/38]
sc_signed operator- (const sc_int_base & u, const sc_signed & v) friend
Definition at line 654 of file sc_signed.cc.
operator- [36/38]
sc_signed operator- (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1005 of file sc_signed.cc.
operator- [37/38]
sc_signed operator- (const sc_signed & u) friend
Definition at line 3491 of file sc_signed.cc.
operator- [38/38]
sc_signed operator- (const sc_unsigned & u) friend
Definition at line 3497 of file sc_signed.cc.
operator/ [1/27]
sc_signed operator/ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2158 of file sc_signed.cc.
operator/ [2/27]
sc_signed operator/ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2174 of file sc_signed.cc.
operator/ [3/27]
sc_signed operator/ (const sc_unsigned & u, int64 v) friend
Definition at line 2242 of file sc_signed.cc.
operator/ [4/27]
sc_signed operator/ (const sc_unsigned & u, long v) friend
Definition at line 2351 of file sc_signed.cc.
operator/ [5/27]
sc_signed operator/ (const sc_unsigned & u, int v) friend
Definition at line 1547 of file sc_signed.hh.
operator/ [6/27]
sc_signed operator/ (int64 u, const sc_unsigned & v) friend
Definition at line 2260 of file sc_signed.cc.
operator/ [7/27]
sc_signed operator/ (long u, const sc_unsigned & v) friend
Definition at line 2369 of file sc_signed.cc.
operator/ [8/27]
sc_signed operator/ (int u, const sc_unsigned & v) friend
Definition at line 1555 of file sc_signed.hh.
operator/ [9/27]
sc_signed operator/ (const sc_signed & u, const sc_signed & v) friend
Definition at line 2190 of file sc_signed.cc.
operator/ [10/27]
sc_signed operator/ (const sc_signed & u, int64 v) friend
Definition at line 2206 of file sc_signed.cc.
operator/ [11/27]
sc_signed operator/ (const sc_signed & u, uint64 v) friend
Definition at line 2278 of file sc_signed.cc.
operator/ [12/27]
sc_signed operator/ (const sc_signed & u, long v) friend
Definition at line 2315 of file sc_signed.cc.
operator/ [13/27]
sc_signed operator/ (const sc_signed & u, unsigned long v) friend
Definition at line 2387 of file sc_signed.cc.
operator/ [14/27]
sc_signed operator/ (const sc_signed & u, int v) friend
Definition at line 1566 of file sc_signed.hh.
operator/ [15/27]
sc_signed operator/ (const sc_signed & u, unsigned int v) friend
Definition at line 1571 of file sc_signed.hh.
operator/ [16/27]
sc_signed operator/ (int64 u, const sc_signed & v) friend
Definition at line 2224 of file sc_signed.cc.
operator/ [17/27]
sc_signed operator/ (uint64 u, const sc_signed & v) friend
Definition at line 2296 of file sc_signed.cc.
operator/ [18/27]
sc_signed operator/ (long u, const sc_signed & v) friend
Definition at line 2333 of file sc_signed.cc.
operator/ [19/27]
sc_signed operator/ (unsigned long u, const sc_signed & v) friend
Definition at line 2405 of file sc_signed.cc.
operator/ [20/27]
sc_signed operator/ (int u, const sc_signed & v) friend
Definition at line 1581 of file sc_signed.hh.
operator/ [21/27]
sc_signed operator/ (unsigned int u, const sc_signed & v) friend
Definition at line 1586 of file sc_signed.hh.
operator/ [22/27]
sc_signed operator/ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 698 of file sc_signed.cc.
operator/ [23/27]
sc_signed operator/ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 704 of file sc_signed.cc.
operator/ [24/27]
sc_signed operator/ (const sc_signed & u, const sc_int_base & v) friend
Definition at line 710 of file sc_signed.cc.
operator/ [25/27]
sc_signed operator/ (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1037 of file sc_signed.cc.
operator/ [26/27]
sc_signed operator/ (const sc_int_base & u, const sc_signed & v) friend
Definition at line 716 of file sc_signed.cc.
operator/ [27/27]
sc_signed operator/ (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1043 of file sc_signed.cc.
operator< [1/19]
bool operator< (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1910 of file sc_unsigned.cc.
operator< [2/19]
bool operator< (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1923 of file sc_unsigned.cc.
operator< [3/19]
bool operator< (const sc_signed & u, const sc_signed & v) friend
Definition at line 3655 of file sc_signed.cc.
operator< [4/19]
bool operator< (const sc_signed & u, int64 v) friend
Definition at line 3681 of file sc_signed.cc.
operator< [5/19]
bool operator< (const sc_signed & u, uint64 v) friend
Definition at line 3731 of file sc_signed.cc.
operator< [6/19]
bool operator< (const sc_signed & u, long v) friend
Definition at line 3775 of file sc_signed.cc.
operator< [7/19]
bool operator< (const sc_signed & u, unsigned long v) friend
Definition at line 3826 of file sc_signed.cc.
operator< [8/19]
bool operator< (const sc_signed & u, int v) friend
Definition at line 2103 of file sc_signed.hh.
operator< [9/19]
bool operator< (const sc_signed & u, unsigned int v) friend
Definition at line 2105 of file sc_signed.hh.
operator< [10/19]
bool operator< (int64 u, const sc_signed & v) friend
Definition at line 3706 of file sc_signed.cc.
operator< [11/19]
bool operator< (uint64 u, const sc_signed & v) friend
Definition at line 3753 of file sc_signed.cc.
operator< [12/19]
bool operator< (long u, const sc_signed & v) friend
Definition at line 3801 of file sc_signed.cc.
operator< [13/19]
bool operator< (unsigned long u, const sc_signed & v) friend
Definition at line 3848 of file sc_signed.cc.
operator< [14/19]
bool operator< (int u, const sc_signed & v) friend
Definition at line 2113 of file sc_signed.hh.
operator< [15/19]
bool operator< (unsigned int u, const sc_signed & v) friend
Definition at line 2118 of file sc_signed.hh.
operator< [16/19]
bool operator< (const sc_signed & u, const sc_int_base & v) friend
Definition at line 905 of file sc_signed.cc.
operator< [17/19]
bool operator< (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1184 of file sc_signed.cc.
operator< [18/19]
bool operator< (const sc_int_base & u, const sc_signed & v) friend
Definition at line 911 of file sc_signed.cc.
operator< [19/19]
bool operator< (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1190 of file sc_signed.cc.
operator<< [1/11]
sc_unsigned operator<< (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1689 of file sc_unsigned.cc.
operator<< [2/11]
sc_signed operator<< (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3451 of file sc_signed.cc.
operator<< [3/11]
sc_signed operator<< (const sc_signed & u, const sc_signed & v) friend
operator<< [4/11]
sc_signed operator<< (const sc_signed & u, int64 v) friend
operator<< [5/11]
sc_signed operator<< (const sc_signed & u, uint64 v) friend
operator<< [6/11]
sc_signed operator<< (const sc_signed & u, long v) friend
operator<< [7/11]
sc_signed operator<< (const sc_signed & u, unsigned long v) friend
operator<< [8/11]
sc_signed operator<< (const sc_signed & u, int v) friend
Definition at line 1933 of file sc_signed.hh.
operator<< [9/11]
sc_signed operator<< (const sc_signed & u, unsigned int v) friend
Definition at line 1938 of file sc_signed.hh.
operator<< [10/11]
sc_signed operator<< (const sc_signed & u, const sc_int_base & v) friend
Definition at line 853 of file sc_signed.cc.
operator<< [11/11]
sc_signed operator<< (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1132 of file sc_signed.cc.
operator<= [1/19]
bool operator<= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2044 of file sc_unsigned.cc.
operator<= [2/19]
bool operator<= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2051 of file sc_unsigned.cc.
operator<= [3/19]
bool operator<= (const sc_signed & u, const sc_signed & v) friend
operator<= [4/19]
bool operator<= (const sc_signed & u, int64 v) friend
operator<= [5/19]
bool operator<= (const sc_signed & u, uint64 v) friend
operator<= [6/19]
bool operator<= (const sc_signed & u, long v) friend
operator<= [7/19]
bool operator<= (const sc_signed & u, unsigned long v) friend
operator<= [8/19]
bool operator<= (const sc_signed & u, int v) friend
Definition at line 2138 of file sc_signed.hh.
operator<= [9/19]
bool operator<= (const sc_signed & u, unsigned int v) friend
Definition at line 2143 of file sc_signed.hh.
operator<= [10/19]
bool operator<= (int64 u, const sc_signed & v) friend
operator<= [11/19]
bool operator<= (uint64 u, const sc_signed & v) friend
operator<= [12/19]
bool operator<= (long u, const sc_signed & v) friend
operator<= [13/19]
bool operator<= (unsigned long u, const sc_signed & v) friend
operator<= [14/19]
bool operator<= (int u, const sc_signed & v) friend
Definition at line 2153 of file sc_signed.hh.
operator<= [15/19]
bool operator<= (unsigned int u, const sc_signed & v) friend
Definition at line 2158 of file sc_signed.hh.
operator<= [16/19]
bool operator<= (const sc_signed & u, const sc_int_base & v) friend
Definition at line 918 of file sc_signed.cc.
operator<= [17/19]
bool operator<= (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1197 of file sc_signed.cc.
operator<= [18/19]
bool operator<= (const sc_int_base & u, const sc_signed & v) friend
Definition at line 924 of file sc_signed.cc.
operator<= [19/19]
bool operator<= (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1203 of file sc_signed.cc.
operator== [1/19]
bool operator== (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1749 of file sc_unsigned.cc.
operator== [2/19]
bool operator== (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 1762 of file sc_unsigned.cc.
operator== [3/19]
bool operator== (const sc_signed & u, const sc_signed & v) friend
Definition at line 3508 of file sc_signed.cc.
operator== [4/19]
bool operator== (const sc_signed & u, int64 v) friend
Definition at line 3524 of file sc_signed.cc.
operator== [5/19]
bool operator== (const sc_signed & u, uint64 v) friend
Definition at line 3554 of file sc_signed.cc.
operator== [6/19]
bool operator== (const sc_signed & u, long v) friend
Definition at line 3584 of file sc_signed.cc.
operator== [7/19]
bool operator== (const sc_signed & u, unsigned long v) friend
Definition at line 3614 of file sc_signed.cc.
operator== [8/19]
bool operator== (const sc_signed & u, int v) friend
Definition at line 2024 of file sc_signed.hh.
operator== [9/19]
bool operator== (const sc_signed & u, unsigned int v) friend
Definition at line 2029 of file sc_signed.hh.
operator== [10/19]
bool operator== (int64 u, const sc_signed & v) friend
Definition at line 3539 of file sc_signed.cc.
operator== [11/19]
bool operator== (uint64 u, const sc_signed & v) friend
Definition at line 3569 of file sc_signed.cc.
operator== [12/19]
bool operator== (long u, const sc_signed & v) friend
Definition at line 3599 of file sc_signed.cc.
operator== [13/19]
bool operator== (unsigned long u, const sc_signed & v) friend
Definition at line 3629 of file sc_signed.cc.
operator== [14/19]
bool operator== (int u, const sc_signed & v) friend
Definition at line 2039 of file sc_signed.hh.
operator== [15/19]
bool operator== (unsigned int u, const sc_signed & v) friend
Definition at line 2044 of file sc_signed.hh.
operator== [16/19]
bool operator== (const sc_signed & u, const sc_int_base & v) friend
Definition at line 879 of file sc_signed.cc.
operator== [17/19]
bool operator== (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1158 of file sc_signed.cc.
operator== [18/19]
bool operator== (const sc_int_base & u, const sc_signed & v) friend
Definition at line 885 of file sc_signed.cc.
operator== [19/19]
bool operator== (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1164 of file sc_signed.cc.
operator> [1/19]
bool operator> (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2064 of file sc_unsigned.cc.
operator> [2/19]
bool operator> (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2071 of file sc_unsigned.cc.
operator> [3/19]
bool operator> (const sc_signed & u, const sc_signed & v) friend
operator> [4/19]
bool operator> (const sc_signed & u, int64 v) friend
operator> [5/19]
bool operator> (const sc_signed & u, uint64 v) friend
operator> [6/19]
bool operator> (const sc_signed & u, long v) friend
operator> [7/19]
bool operator> (const sc_signed & u, unsigned long v) friend
operator> [8/19]
bool operator> (const sc_signed & u, int v) friend
Definition at line 2178 of file sc_signed.hh.
operator> [9/19]
bool operator> (const sc_signed & u, unsigned int v) friend
Definition at line 2183 of file sc_signed.hh.
operator> [10/19]
bool operator> (int64 u, const sc_signed & v) friend
operator> [11/19]
bool operator> (uint64 u, const sc_signed & v) friend
operator> [12/19]
bool operator> (long u, const sc_signed & v) friend
operator> [13/19]
bool operator> (unsigned long u, const sc_signed & v) friend
operator> [14/19]
bool operator> (int u, const sc_signed & v) friend
Definition at line 2193 of file sc_signed.hh.
operator> [15/19]
bool operator> (unsigned int u, const sc_signed & v) friend
Definition at line 2198 of file sc_signed.hh.
operator> [16/19]
bool operator> (const sc_signed & u, const sc_int_base & v) friend
Definition at line 931 of file sc_signed.cc.
operator> [17/19]
bool operator> (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1210 of file sc_signed.cc.
operator> [18/19]
bool operator> (const sc_int_base & u, const sc_signed & v) friend
Definition at line 937 of file sc_signed.cc.
operator> [19/19]
bool operator> (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1216 of file sc_signed.cc.
operator>= [1/19]
bool operator>= (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2084 of file sc_unsigned.cc.
operator>= [2/19]
bool operator>= (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2091 of file sc_unsigned.cc.
operator>= [3/19]
bool operator>= (const sc_signed & u, const sc_signed & v) friend
operator>= [4/19]
bool operator>= (const sc_signed & u, int64 v) friend
operator>= [5/19]
bool operator>= (const sc_signed & u, uint64 v) friend
operator>= [6/19]
bool operator>= (const sc_signed & u, long v) friend
operator>= [7/19]
bool operator>= (const sc_signed & u, unsigned long v) friend
operator>= [8/19]
bool operator>= (const sc_signed & u, int v) friend
Definition at line 2218 of file sc_signed.hh.
operator>= [9/19]
bool operator>= (const sc_signed & u, unsigned int v) friend
Definition at line 2223 of file sc_signed.hh.
operator>= [10/19]
bool operator>= (int64 u, const sc_signed & v) friend
operator>= [11/19]
bool operator>= (uint64 u, const sc_signed & v) friend
operator>= [12/19]
bool operator>= (long u, const sc_signed & v) friend
operator>= [13/19]
bool operator>= (unsigned long u, const sc_signed & v) friend
operator>= [14/19]
bool operator>= (int u, const sc_signed & v) friend
Definition at line 2233 of file sc_signed.hh.
operator>= [15/19]
bool operator>= (unsigned int u, const sc_signed & v) friend
Definition at line 2238 of file sc_signed.hh.
operator>= [16/19]
bool operator>= (const sc_signed & u, const sc_int_base & v) friend
Definition at line 944 of file sc_signed.cc.
operator>= [17/19]
bool operator>= (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1223 of file sc_signed.cc.
operator>= [18/19]
bool operator>= (const sc_int_base & u, const sc_signed & v) friend
Definition at line 950 of file sc_signed.cc.
operator>= [19/19]
bool operator>= (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1229 of file sc_signed.cc.
operator>> [1/11]
sc_unsigned operator>> (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 1706 of file sc_unsigned.cc.
operator>> [2/11]
sc_signed operator>> (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3468 of file sc_signed.cc.
operator>> [3/11]
sc_signed operator>> (const sc_signed & u, const sc_signed & v) friend
operator>> [4/11]
sc_signed operator>> (const sc_signed & u, int64 v) friend
operator>> [5/11]
sc_signed operator>> (const sc_signed & u, uint64 v) friend
operator>> [6/11]
sc_signed operator>> (const sc_signed & u, long v) friend
operator>> [7/11]
sc_signed operator>> (const sc_signed & u, unsigned long v) friend
operator>> [8/11]
sc_signed operator>> (const sc_signed & u, int v) friend
Definition at line 1975 of file sc_signed.hh.
operator>> [9/11]
sc_signed operator>> (const sc_signed & u, unsigned int v) friend
Definition at line 1980 of file sc_signed.hh.
operator>> [10/11]
sc_signed operator>> (const sc_signed & u, const sc_int_base & v) friend
Definition at line 866 of file sc_signed.cc.
operator>> [11/11]
sc_signed operator>> (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1145 of file sc_signed.cc.
operator^ [1/27]
sc_signed operator^ (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 3188 of file sc_signed.cc.
operator^ [2/27]
sc_signed operator^ (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 3205 of file sc_signed.cc.
operator^ [3/27]
sc_signed operator^ (const sc_unsigned & u, int64 v) friend
Definition at line 3269 of file sc_signed.cc.
operator^ [4/27]
sc_signed operator^ (const sc_unsigned & u, long v) friend
Definition at line 3370 of file sc_signed.cc.
operator^ [5/27]
sc_signed operator^ (const sc_unsigned & u, int v) friend
Definition at line 1851 of file sc_signed.hh.
operator^ [6/27]
sc_signed operator^ (int64 u, const sc_unsigned & v) friend
Definition at line 3286 of file sc_signed.cc.
operator^ [7/27]
sc_signed operator^ (long u, const sc_unsigned & v) friend
Definition at line 3387 of file sc_signed.cc.
operator^ [8/27]
sc_signed operator^ (int u, const sc_unsigned & v) friend
Definition at line 1859 of file sc_signed.hh.
operator^ [9/27]
sc_signed operator^ (const sc_signed & u, const sc_signed & v) friend
Definition at line 3220 of file sc_signed.cc.
operator^ [10/27]
sc_signed operator^ (const sc_signed & u, int64 v) friend
Definition at line 3235 of file sc_signed.cc.
operator^ [11/27]
sc_signed operator^ (const sc_signed & u, uint64 v) friend
Definition at line 3303 of file sc_signed.cc.
operator^ [12/27]
sc_signed operator^ (const sc_signed & u, long v) friend
Definition at line 3336 of file sc_signed.cc.
operator^ [13/27]
sc_signed operator^ (const sc_signed & u, unsigned long v) friend
Definition at line 3404 of file sc_signed.cc.
operator^ [14/27]
sc_signed operator^ (const sc_signed & u, int v) friend
Definition at line 1870 of file sc_signed.hh.
operator^ [15/27]
sc_signed operator^ (const sc_signed & u, unsigned int v) friend
Definition at line 1875 of file sc_signed.hh.
operator^ [16/27]
sc_signed operator^ (int64 u, const sc_signed & v) friend
Definition at line 3252 of file sc_signed.cc.
operator^ [17/27]
sc_signed operator^ (uint64 u, const sc_signed & v) friend
Definition at line 3319 of file sc_signed.cc.
operator^ [18/27]
sc_signed operator^ (long u, const sc_signed & v) friend
Definition at line 3353 of file sc_signed.cc.
operator^ [19/27]
sc_signed operator^ (unsigned long u, const sc_signed & v) friend
Definition at line 3420 of file sc_signed.cc.
operator^ [20/27]
sc_signed operator^ (int u, const sc_signed & v) friend
Definition at line 1885 of file sc_signed.hh.
operator^ [21/27]
sc_signed operator^ (unsigned int u, const sc_signed & v) friend
Definition at line 1890 of file sc_signed.hh.
operator^ [22/27]
sc_signed operator^ (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 822 of file sc_signed.cc.
operator^ [23/27]
sc_signed operator^ (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 828 of file sc_signed.cc.
operator^ [24/27]
sc_signed operator^ (const sc_signed & u, const sc_int_base & v) friend
Definition at line 834 of file sc_signed.cc.
operator^ [25/27]
sc_signed operator^ (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1113 of file sc_signed.cc.
operator^ [26/27]
sc_signed operator^ (const sc_int_base & u, const sc_signed & v) friend
Definition at line 840 of file sc_signed.cc.
operator^ [27/27]
sc_signed operator^ (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1119 of file sc_signed.cc.
operator| [1/27]
sc_signed operator| (const sc_unsigned & u, const sc_signed & v) friend
Definition at line 2923 of file sc_signed.cc.
operator| [2/27]
sc_signed operator| (const sc_signed & u, const sc_unsigned & v) friend
Definition at line 2938 of file sc_signed.cc.
operator| [3/27]
sc_signed operator| (const sc_unsigned & u, int64 v) friend
Definition at line 3002 of file sc_signed.cc.
operator| [4/27]
sc_signed operator| (const sc_unsigned & u, long v) friend
Definition at line 3104 of file sc_signed.cc.
operator| [5/27]
sc_signed operator| (const sc_unsigned & u, int v) friend
Definition at line 1774 of file sc_signed.hh.
operator| [6/27]
sc_signed operator| (int64 u, const sc_unsigned & v) friend
Definition at line 3019 of file sc_signed.cc.
operator| [7/27]
sc_signed operator| (long u, const sc_unsigned & v) friend
Definition at line 3121 of file sc_signed.cc.
operator| [8/27]
sc_signed operator| (int u, const sc_unsigned & v) friend
Definition at line 1782 of file sc_signed.hh.
operator| [9/27]
sc_signed operator| (const sc_signed & u, const sc_signed & v) friend
Definition at line 2953 of file sc_signed.cc.
operator| [10/27]
sc_signed operator| (const sc_signed & u, int64 v) friend
Definition at line 2968 of file sc_signed.cc.
operator| [11/27]
sc_signed operator| (const sc_signed & u, uint64 v) friend
Definition at line 3036 of file sc_signed.cc.
operator| [12/27]
sc_signed operator| (const sc_signed & u, long v) friend
Definition at line 3070 of file sc_signed.cc.
operator| [13/27]
sc_signed operator| (const sc_signed & u, unsigned long v) friend
Definition at line 3138 of file sc_signed.cc.
operator| [14/27]
sc_signed operator| (const sc_signed & u, int v) friend
Definition at line 1793 of file sc_signed.hh.
operator| [15/27]
sc_signed operator| (const sc_signed & u, unsigned int v) friend
Definition at line 1798 of file sc_signed.hh.
operator| [16/27]
sc_signed operator| (int64 u, const sc_signed & v) friend
Definition at line 2985 of file sc_signed.cc.
operator| [17/27]
sc_signed operator| (uint64 u, const sc_signed & v) friend
Definition at line 3053 of file sc_signed.cc.
operator| [18/27]
sc_signed operator| (long u, const sc_signed & v) friend
Definition at line 3087 of file sc_signed.cc.
operator| [19/27]
sc_signed operator| (unsigned long u, const sc_signed & v) friend
Definition at line 3155 of file sc_signed.cc.
operator| [20/27]
sc_signed operator| (int u, const sc_signed & v) friend
Definition at line 1808 of file sc_signed.hh.
operator| [21/27]
sc_signed operator| (unsigned int u, const sc_signed & v) friend
Definition at line 1813 of file sc_signed.hh.
operator| [22/27]
sc_signed operator| (const sc_unsigned & u, const sc_int_base & v) friend
Definition at line 791 of file sc_signed.cc.
operator| [23/27]
sc_signed operator| (const sc_int_base & u, const sc_unsigned & v) friend
Definition at line 797 of file sc_signed.cc.
operator| [24/27]
sc_signed operator| (const sc_signed & u, const sc_int_base & v) friend
Definition at line 803 of file sc_signed.cc.
operator| [25/27]
sc_signed operator| (const sc_signed & u, const sc_uint_base & v) friend
Definition at line 1094 of file sc_signed.cc.
operator| [26/27]
sc_signed operator| (const sc_int_base & u, const sc_signed & v) friend
Definition at line 809 of file sc_signed.cc.
operator| [27/27]
sc_signed operator| (const sc_uint_base & u, const sc_signed & v) friend
Definition at line 1100 of file sc_signed.cc.
operator~
sc_signed operator~ (const sc_signed & u) friend
or_signed_friend
sc_signed or_signed_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
sc_concatref
friend class sc_concatref friend
Definition at line 986 of file sc_signed.hh.
sc_signed_bitref
friend class sc_signed_bitref friend
Definition at line 988 of file sc_signed.hh.
sc_signed_bitref_r
friend class sc_signed_bitref_r friend
Definition at line 987 of file sc_signed.hh.
sc_signed_subref
friend class sc_signed_subref friend
Definition at line 990 of file sc_signed.hh.
sc_signed_subref_r
friend class sc_signed_subref_r friend
Definition at line 989 of file sc_signed.hh.
sc_unsigned
friend class sc_unsigned friend
Definition at line 991 of file sc_signed.hh.
sc_unsigned_subref
friend class sc_unsigned_subref friend
Definition at line 992 of file sc_signed.hh.
sub_signed_friend
sc_signed sub_signed_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
xor_signed_friend
sc_signed xor_signed_friend (small_type us, int unb, int und, const sc_digit * ud, small_type vs, int vnb, int vnd, const sc_digit * vd) friend
Member Data Documentation
digit
sc_digit* sc_dt::sc_signed::digit private
Definition at line 2293 of file sc_signed.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), and sc_dt::operator|().
nbits
int sc_dt::sc_signed::nbits private
Definition at line 2287 of file sc_signed.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), and sc_dt::operator|().
ndigits
int sc_dt::sc_signed::ndigits private
Definition at line 2288 of file sc_signed.hh.
Referenced by sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator==(), sc_dt::operator^(), and sc_dt::operator|().
sgn
small_type sc_dt::sc_signed::sgn private
Definition at line 2286 of file sc_signed.hh.
Referenced by sc_dt::operator!=(), sc_dt::operator%(), sc_dt::operator&(), sc_dt::operator*(), sc_dt::operator+(), sc_dt::operator-(), sc_dt::operator/(), sc_dt::operator<(), sc_dt::operator<<(), sc_dt::operator==(), sc_dt::operator>>(), sc_dt::operator^(), and sc_dt::operator|().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_signed.hh
systemc/dt/int/sc_signed.cc
systemc/ext/dt/fx/scfx_other_defs.hh