gem5: sc_dt::scfx_pow10 Class Reference
sc_dt::scfx_pow10 Class Reference
#include <scfx_pow10.hh>
Public Member Functions
scfx_pow10 ()
~scfx_pow10 ()
const scfx_rep operator() (int)
Private Member Functions
scfx_rep * pos (int)
scfx_rep * neg (int)
Private Attributes
scfx_rep m_pos [SCFX_POW10_TABLE_SIZE]
scfx_rep m_neg [SCFX_POW10_TABLE_SIZE]
Detailed Description
Definition at line 68 of file scfx_pow10.hh.
Constructor & Destructor Documentation
scfx_pow10()
sc_dt::scfx_pow10::scfx_pow10 ()
Definition at line 60 of file scfx_pow10.cc.
References ArmISA::i, m_neg, m_pos, sc_dt::SCFX_POW10_TABLE_SIZE, and sc_dt::scfx_rep::set_nan().
~scfx_pow10()
sc_dt::scfx_pow10::~scfx_pow10 ()
Definition at line 71 of file scfx_pow10.cc.
Member Function Documentation
neg()
scfx_rep * sc_dt::scfx_pow10::neg (int i) private
Definition at line 121 of file scfx_pow10.cc.
References ArmISA::i, m_neg, and sc_dt::multiply().
Referenced by operator()().
operator()()
const scfx_rep sc_dt::scfx_pow10::operator() (int i)
Definition at line 74 of file scfx_pow10.cc.
References ArmISA::i, sc_dt::mult_scfx_rep(), neg(), pos(), and sc_dt::scfx_find_msb().
pos()
scfx_rep * sc_dt::scfx_pow10::pos (int i) private
Definition at line 112 of file scfx_pow10.cc.
References ArmISA::i, m_pos, and sc_dt::multiply().
Referenced by operator()().
Member Data Documentation
m_neg
scfx_rep sc_dt::scfx_pow10::m_neg[SCFX_POW10_TABLE_SIZE] private
Definition at line 81 of file scfx_pow10.hh.
Referenced by neg(), and scfx_pow10().
m_pos
scfx_rep sc_dt::scfx_pow10::m_pos[SCFX_POW10_TABLE_SIZE] private
Definition at line 80 of file scfx_pow10.hh.
Referenced by pos(), and scfx_pow10().
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/scfx_pow10.hh
systemc/dt/fx/scfx_pow10.cc