gem5: OutputDirectory Class Reference
OutputDirectory Class Reference
Interface for creating files in a gem5 output directory.
#include <output.hh>
Public Member Functions
OutputDirectory ()
Constructor.
OutputDirectory (const std::string &name)
Constructor.
~OutputDirectory ()
Destructor.
std::string resolve (const std::string &name) const
Returns relative file names prepended with name of this directory.
void setDirectory (const std::string &dir)
Sets name of this directory.
const std::string & directory () const
Gets name of this directory.
OutputStream * create (const std::string &name, bool binary=false, bool no_gz=false)
Creates a file in this directory (optionally compressed).
OutputStream * open (const std::string &name, std::ios_base::openmode mode, bool recreateable=true, bool no_gz=false)
Open a file in this directory (optionally compressed).
void close (OutputStream *file)
Closes an output file and free the corresponding OutputFile.
OutputStream * find (const std::string &name) const
Finds stream associated with an open file or stdout/stderr.
OutputStream * findOrCreate (const std::string &name, bool binary=false)
bool isFile (const std::string &name) const
Determines whether a file name corresponds to a file in this directory.
OutputDirectory * createSubdirectory (const std::string &name)
Creates a subdirectory within this directory.
void remove (const std::string &name, bool recursive=false)
Removes a specified file or subdirectory.
Static Public Member Functions
static bool isAbsolute (const std::string &name)
Test if a path is absolute.
Static Protected Member Functions
static OutputStream * checkForStdio (const std::string &name)
Determines whether given file name corresponds to standard output streams.
Private Types
typedef std::map< std::string, OutputStream * > file_map_t
File names and associated stream handles.
typedef std::map< std::string, OutputDirectory * > dir_map_t
Output subdirectories.
Private Attributes
file_map_t files
Open file streams within this directory.
dir_map_t dirs
Output sub-directories.
std::string dir
Name of this directory.
Static Private Attributes
static const char PATH_SEPARATOR = '/'
System-specific path separator character.
static OutputStream stdout
static OutputStream stderr
Detailed Description
Interface for creating files in a gem5 output directory.
Definition at line 139 of file output.hh.
Member Typedef Documentation
dir_map_t
typedef std::map<std::string, OutputDirectory *> OutputDirectory::dir_map_t private
Output subdirectories.
Definition at line 146 of file output.hh.
file_map_t
typedef std::map<std::string, OutputStream *> OutputDirectory::file_map_t private
File names and associated stream handles.
Definition at line 143 of file output.hh.
Constructor & Destructor Documentation
OutputDirectory() [1/2]
OutputDirectory::OutputDirectory ()
Constructor.
Definition at line 119 of file output.cc.
OutputDirectory() [2/2]
OutputDirectory::OutputDirectory (const std::string & name)
Constructor.
Definition at line 122 of file output.cc.
~OutputDirectory()
OutputDirectory::~OutputDirectory ()
Destructor.
Definition at line 127 of file output.cc.
References ArmISA::f.
Member Function Documentation
checkForStdio()
OutputStream * OutputDirectory::checkForStdio (const std::string & name) static protected
Determines whether given file name corresponds to standard output streams.
Parameters
name name of file to check
Returns
output stream for standard output or error stream if name corresponds to one or the other; NULL otherwise
Definition at line 136 of file output.cc.
close()
void OutputDirectory::close (OutputStream * file)
Closes an output file and free the corresponding OutputFile.
The output file must have been opened by the same OutputDirectory instance as the one closing it, or sim will fail.
Parameters
file OutputStream instance in this OutputDirectory.
Definition at line 148 of file output.cc.
References fatal, ArmISA::i, and OutputStream::name().
Referenced by VncInput::captureFrameBuffer(), O3ThreadState< Impl >::dumpFuncProfile(), SimpleThread::dumpFuncProfile(), Linux::DmesgDumpEvent::process(), Linux::KernelPanicEvent::process(), PseudoInst::writefile(), SimPoint::~SimPoint(), and sc_gem5::TraceFile::~TraceFile().
create()
OutputStream * OutputDirectory::create (const std::string & name, bool binary = false, bool no_gz = false)
Creates a file in this directory (optionally compressed).
Will open a file as a compressed stream if filename ends in .gz, unless explicitly disabled.
Relative output paths will result in the creation of a recreateable (see OutputFile) output file in the current output directory. Files created with an absolute path will not be recreateable.
Parameters
name name of file to create (without this directory's name leading it)
binary true to create a binary file; false otherwise
no_gz true to disable opening the file as a gzip compressed output stream; false otherwise
Returns
OutputStream instance representing the created file
Definition at line 206 of file output.cc.
References ArmISA::mode, and OutputFile< StreamType >::recreateable().
Referenced by VncInput::captureFrameBuffer(), Pl111::dmaDone(), O3ThreadState< Impl >::dumpFuncProfile(), SimpleThread::dumpFuncProfile(), X86ISA::GpuTLB::exitCallback(), output(), Linux::DmesgDumpEvent::process(), AnnotateDumpCallback::process(), Linux::KernelPanicEvent::process(), ComputeUnit::CUExitCallback::process(), HDLcd::pxlFrameDone(), SimPoint::SimPoint(), LinuxArmSystem::startup(), and PseudoInst::writefile().
createSubdirectory()
OutputDirectory * OutputDirectory::createSubdirectory (const std::string & name)
Creates a subdirectory within this directory.
Parameters
name name of subdirectory
Returns
the new subdirectory's name suffixed with a path separator
Definition at line 279 of file output.cc.
References fatal, OutputStream::name(), and OutputFile< StreamType >::OutputDirectory.
Referenced by VncInput::VncInput().
directory()
const string & OutputDirectory::directory () const
Gets name of this directory.
Returns
name of this directory
Definition at line 191 of file output.cc.
References panic.
find()
OutputStream * OutputDirectory::find (const std::string & name) const
Finds stream associated with an open file or stdout/stderr.
Parameters
name of file
Returns
stream to specified file or NULL if file does not exist
Definition at line 243 of file output.cc.
References ArmISA::i.
Referenced by output().
findOrCreate()
OutputStream * OutputDirectory::findOrCreate (const std::string & name, bool binary = false)
Definition at line 258 of file output.cc.
References X86ISA::os.
Referenced by BaseCPU::BaseCPU(), Stats::initText(), and Terminal::terminalDump().
isAbsolute()
static bool OutputDirectory::isAbsolute (const std::string & name) inline static
Test if a path is absolute.
Definition at line 279 of file output.hh.
References OutputStream::name(), and simout.
Referenced by VirtIO9PDiod::startDiod().
isFile()
bool OutputDirectory::isFile (const std::string & name) const
Determines whether a file name corresponds to a file in this directory.
Parameters
name name of file to evaluate
Returns
true iff file has been opened in this directory or exists on the file system within this directory
Definition at line 268 of file output.cc.
References ArmISA::st.
open()
OutputStream * OutputDirectory::open (const std::string & name, std::ios_base::openmode mode, bool recreateable = true, bool no_gz = false)
Open a file in this directory (optionally compressed).
Will open a file as a compressed stream if filename ends in .gz, unless explicitly disabled.
Parameters
filename file to open
mode attributes to open file with
recreateable Set to true if the file can be recreated in a new location.
no_gz true to disable opening the file as a gzip compressed output stream; false otherwise
Returns
OutputStream instance representing the opened file
Definition at line 220 of file output.cc.
References ArmISA::mode, OutputStream::name(), X86ISA::os, and OutputFile< StreamType >::recreateable().
Referenced by PseudoInst::writefile().
remove()
void OutputDirectory::remove (const std::string & name, bool recursive = false)
Removes a specified file or subdirectory.
Will cause sim to fail for most errors. However, it will only warn the user if a directory could not be removed. This is in place to accommodate slow file systems where file deletions within a subdirectory may not be recognized quickly enough thereby causing the subsequent call to remove the directory to fail (seemingly unempty directory).
Parameters
name name of file or subdirectory to remove; name should not be prepended with the name of this directory object
recursive set to true to attempt to recursively delete a subdirectory and its contents
Definition at line 292 of file output.cc.
References X86ISA::de, fatal, and ArmISA::i.
Referenced by VncInput::VncInput().
resolve()
string OutputDirectory::resolve (const std::string & name) const
Returns relative file names prepended with name of this directory.
Returns absolute file names unaltered.
Parameters
name file name to prepend with directory name
Returns
file name prepended with base directory name or unaltered absolute file name
Definition at line 200 of file output.cc.
References OutputStream::name().
Referenced by Trace::InstPBTrace::createTraceFile(), ElasticTrace::ElasticTrace(), Stats::initHDF5(), MemTraceProbe::MemTraceProbe(), FDArray::openOutputFile(), OutputFile< StreamType >::OutputFile(), OutputFile< StreamType >::relocate(), and VirtIO9PDiod::startDiod().
setDirectory()
void OutputDirectory::setDirectory (const std::string & dir)
Sets name of this directory.
Parameters
dir name of this directory
Definition at line 160 of file output.cc.
References ArmISA::d, fatal, and ArmISA::i.
Referenced by setOutputDir().
Member Data Documentation
dir
std::string OutputDirectory::dir private
Name of this directory.
Definition at line 155 of file output.hh.
dirs
dir_map_t OutputDirectory::dirs private
Output sub-directories.
Definition at line 152 of file output.hh.
files
file_map_t OutputDirectory::files private
Open file streams within this directory.
Definition at line 149 of file output.hh.
PATH_SEPARATOR
const char OutputDirectory::PATH_SEPARATOR = '/' static private
System-specific path separator character.
Definition at line 158 of file output.hh.
stderr
OutputStream OutputDirectory::stderr static private
Definition at line 161 of file output.hh.
Referenced by OutputFile< StreamType >::relocate().
stdout
OutputStream OutputDirectory::stdout static private
Definition at line 160 of file output.hh.
Referenced by OutputFile< StreamType >::relocate().
The documentation for this class was generated from the following files:
base/output.hh
base/output.cc