gem5: CRegOperand Class Reference
CRegOperand Class Reference
#include <operand.hh>
Public Member Functions
bool init (unsigned opOffset, const BrigObject *obj)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj)
template<typename OperandType >
OperandType get (Wavefront *w, int lane)
template<typename OperandType >
void set (Wavefront *w, int lane, OperandType &val)
std::string disassemble ()
Public Member Functions inherited from BaseRegOperand
bool init (unsigned opOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at, unsigned &maxRegIdx, char _regFileChar)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
unsigned int regIndex ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Static Public Attributes
static unsigned maxRegIdx
Additional Inherited Members
Public Attributes inherited from BaseRegOperand
unsigned regIdx
char regFileChar
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 289 of file operand.hh.
Member Function Documentation
disassemble()
std::string CRegOperand::disassemble ()
Definition at line 207 of file operand.cc.
References csprintf().
get()
template<typename OperandType > OperandType CRegOperand::get (Wavefront * w, int lane) inline
Definition at line 325 of file operand.hh.
References Wavefront::condRegState, and ConditionRegisterState::read().
init()
bool CRegOperand::init (unsigned opOffset, const BrigObject * obj) inline
Definition at line 295 of file operand.hh.
References BaseRegOperand::init(), BaseOperand::registerType, and BaseOperand::regOperandSize.
Referenced by HsailISA::CbrInstBase< SRegOperand >::CbrInstBase().
init_from_vect()
bool CRegOperand::init_from_vect (unsigned opOffset, const BrigObject * obj, int at) inline
Definition at line 304 of file operand.hh.
References BaseRegOperand::init_from_vect(), BaseOperand::registerType, and BaseOperand::regOperandSize.
initWithStrOffset()
void CRegOperand::initWithStrOffset (unsigned strOffset, const BrigObject * obj) inline
Definition at line 314 of file operand.hh.
References BaseRegOperand::initWithStrOffset(), BaseOperand::registerType, and BaseOperand::regOperandSize.
set()
template<typename OperandType > void CRegOperand::set (Wavefront * w, int lane, OperandType & val) inline
Definition at line 334 of file operand.hh.
References Wavefront::computeUnit, Wavefront::condRegState, ComputeUnit::cu_id, DPRINTF, Wavefront::simdId, X86ISA::val, Wavefront::wfSlotId, and ConditionRegisterState::write().
Member Data Documentation
maxRegIdx
unsigned CRegOperand::maxRegIdx static
Definition at line 292 of file operand.hh.
Referenced by HsailCode::init(), and BaseRegOperand::initWithStrOffset().
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc