gem5: BPredUnit Class Reference
BPredUnit Class Reference abstract
Basically a wrapper class to hold both the branch predictor and the BTB.
#include <bpred_unit.hh>
Classes
struct PredictorHistory
Public Types
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BPredUnit (const Params *p)
void regStats () override
Registers statistics.
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
virtual void uncondBranch (ThreadID tid, Addr pc, void *&bp_history)=0
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
virtual void squash (ThreadID tid, void *bp_history)=0
virtual bool lookup (ThreadID tid, Addr instPC, void *&bp_history)=0
Looks up a given PC in the BP to see if it is taken or not taken.
virtual void btbUpdate (ThreadID tid, Addr instPC, void *&bp_history)=0
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
virtual void update (ThreadID tid, Addr instPC, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr, Addr corrTarget=MaxAddr)=0
Updates the BP with taken/not taken information.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Types
typedef std::deque< PredictorHistory > History
Private Attributes
const unsigned numThreads
Number of the threads for which the branch history is maintained.
std::vector< History > predHist
The per-thread predictor history.
DefaultBTB BTB
The BTB.
std::vector< ReturnAddrStack > RAS
The per-thread return address stack.
IndirectPredictor * iPred
The indirect target predictor.
Stats::Scalar lookups
Stat for number of BP lookups.
Stats::Scalar condPredicted
Stat for number of conditional branches predicted.
Stats::Scalar condIncorrect
Stat for number of conditional branches predicted incorrectly.
Stats::Scalar BTBLookups
Stat for number of BTB lookups.
Stats::Scalar BTBHits
Stat for number of BTB hits.
Stats::Scalar BTBCorrect
Stat for number of times the BTB is correct.
Stats::Formula BTBHitPct
Stat for percent times an entry in BTB found.
Stats::Scalar usedRAS
Stat for number of times the RAS is used to get a target.
Stats::Scalar RASIncorrect
Stat for number of times the RAS is incorrect.
Stats::Scalar indirectLookups
Stat for the number of indirect target lookups.
Stats::Scalar indirectHits
Stat for the number of indirect target hits.
Stats::Scalar indirectMisses
Stat for the number of indirect target misses.
Stats::Scalar indirectMispredicted
Stat for the number of indirect target mispredictions.
PMU Probe points.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Basically a wrapper class to hold both the branch predictor and the BTB.
Definition at line 67 of file bpred_unit.hh.
Member Typedef Documentation
History
typedef std::deque<PredictorHistory> BPredUnit::History private
Definition at line 269 of file bpred_unit.hh.
Params
typedef BranchPredictorParams BPredUnit::Params
Definition at line 70 of file bpred_unit.hh.
Constructor & Destructor Documentation
BPredUnit()
BPredUnit::BPredUnit (const Params * p)
Parameters
params The params object, that has the size of the BP and BTB.
Definition at line 56 of file bpred_unit.cc.
References MipsISA::r, and RAS.
Member Function Documentation
BTBLookup()
TheISA::PCState BPredUnit::BTBLookup (Addr instPC) inline
Looks up a given PC in the BTB to get the predicted target.
Parameters
inst_PC The PC to look up.
Returns
The address of the target of the branch.
Definition at line 167 of file bpred_unit.hh.
References BTB, DefaultBTB::lookup(), MaxAddr, StaticInst::nullStaticInstPtr, and update().
btbUpdate()
virtual void BPredUnit::btbUpdate (ThreadID tid, Addr instPC, void *& bp_history) pure virtual
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Parameters
inst_PC The PC to look up the local predictor.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Implemented in MultiperspectivePerceptron, TournamentBP, TAGE, LocalBP, and BiModeBP.
Referenced by predict().
BTBUpdate()
void BPredUnit::BTBUpdate (Addr instPC, const TheISA::PCState & target) inline
Updates the BTB with the target of a branch.
Parameters
inst_PC The branch's PC that will be updated.
target_PC The branch's target that will be added to the BTB.
Definition at line 192 of file bpred_unit.hh.
References BTB, dump(), and DefaultBTB::update().
BTBValid()
bool BPredUnit::BTBValid (Addr instPC) inline
Looks up a given PC in the BTB to see if a matching entry exists.
Parameters
inst_PC The PC to look up.
Returns
Whether the BTB contains the given PC.
Definition at line 159 of file bpred_unit.hh.
References BTB, and DefaultBTB::valid().
drainSanityCheck()
void BPredUnit::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 163 of file bpred_unit.cc.
References M5_VAR_USED, and predHist.
Referenced by DefaultFetch< Impl >::drainSanityCheck().
dump()
void BPredUnit::dump ()
Definition at line 544 of file bpred_unit.cc.
References cprintf(), ArmISA::i, and predHist.
Referenced by BTBUpdate().
lookup()
virtual bool BPredUnit::lookup (ThreadID tid, Addr instPC, void *& bp_history) pure virtual
Looks up a given PC in the BP to see if it is taken or not taken.
Parameters
inst_PC The PC to look up.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Returns
Whether the branch is taken or not taken.
Implemented in MultiperspectivePerceptron, MultiperspectivePerceptronTAGE, TAGE, TournamentBP, LocalBP, and BiModeBP.
Referenced by predict().
pmuProbePoint()
ProbePoints::PMUUPtr BPredUnit::pmuProbePoint (const char * name) protected
Helper method to instantiate probe points belonging to this object.
Parameters
name Name of the probe point.
Returns
A unique_ptr to the new probe point.
Definition at line 147 of file bpred_unit.cc.
References SimObject::getProbeManager().
Referenced by regProbePoints().
predict()
bool BPredUnit::predict (const StaticInstPtr & inst, const InstSeqNum & seqNum, TheISA::PCState & pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
Parameters
inst The branch instruction.
PC The predicted PC is passed back through this parameter.
tid The thread id.
Returns
Returns if the branch is taken or not.
Definition at line 172 of file bpred_unit.cc.
References AlphaISA::advancePC(), BTB, BTBHits, BTBLookups, btbUpdate(), AlphaISA::buildRetPC(), condPredicted, DPRINTF, IndirectPredictor::genIndirectInfo(), indirectHits, indirectLookups, indirectMisses, iPred, StaticInst::isCall(), StaticInst::isDirectCtrl(), StaticInst::isReturn(), StaticInst::isUncondCtrl(), IndirectPredictor::lookup(), DefaultBTB::lookup(), lookup(), lookups, MipsISA::pc, ppBranches, predHist, RAS, IndirectPredictor::recordIndirect(), uncondBranch(), IndirectPredictor::updateDirectionInfo(), usedRAS, and DefaultBTB::valid().
Referenced by DefaultFetch< Impl >::lookupAndUpdateNextPC(), Minor::Fetch2::predictBranch(), and BaseSimpleCPU::preExecute().
regProbePoints()
void BPredUnit::regProbePoints () override virtual
Register probe points for this object.
No probe points by default, so do nothing in base.
Reimplemented from SimObject.
Definition at line 156 of file bpred_unit.cc.
References pmuProbePoint(), ppBranches, and ppMisses.
regStats()
void BPredUnit::regStats () override virtual
Registers statistics.
Reimplemented from Stats::Group.
Reimplemented in TAGE_SC_L, and LTAGE.
Definition at line 73 of file bpred_unit.cc.
References BTBCorrect, BTBHitPct, BTBHits, BTBLookups, condIncorrect, condPredicted, Stats::DataWrap< Derived, InfoProxyType >::desc(), indirectHits, indirectLookups, indirectMispredicted, indirectMisses, lookups, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::DataWrap< Derived, InfoProxyType >::precision(), RASIncorrect, Stats::Group::regStats(), and usedRAS.
Referenced by LTAGE::regStats().
squash() [1/3]
void BPredUnit::squash (const InstSeqNum & squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
Parameters
squashed_sn The sequence number to squash any younger updates up until.
tid The thread id.
Definition at line 368 of file bpred_unit.cc.
References IndirectPredictor::deleteIndirectInfo(), DPRINTF, iPred, predHist, RAS, and IndirectPredictor::squash().
Referenced by BaseSimpleCPU::advancePC(), DefaultFetch< Impl >::checkSignalsAndUpdate(), squash(), and Minor::Fetch2::updateBranchPrediction().
squash() [2/3]
void BPredUnit::squash (const InstSeqNum & squashed_sn, const TheISA::PCState & corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
Parameters
squashed_sn The sequence number to squash any younger updates up until.
corr_target The correct branch target.
actually_taken The correct branch direction.
tid The thread id.
Definition at line 413 of file bpred_unit.cc.
References BTB, IndirectPredictor::changeDirectionPrediction(), condIncorrect, DPRINTF, indirectMispredicted, iPred, ppMisses, predHist, RAS, RASIncorrect, IndirectPredictor::recordTarget(), squash(), DefaultBTB::update(), and update().
squash() [3/3]
virtual void BPredUnit::squash (ThreadID tid, void * bp_history) pure virtual
Parameters
bp_history Pointer to the history object. The predictor will need to update any state and delete the object.
Implemented in MultiperspectivePerceptron, MultiperspectivePerceptronTAGE, TournamentBP, LocalBP, TAGE, LTAGE, and BiModeBP.
uncondBranch()
virtual void BPredUnit::uncondBranch (ThreadID tid, Addr pc, void *& bp_history) pure virtual
Implemented in MultiperspectivePerceptron, MultiperspectivePerceptronTAGE, TournamentBP, TAGE, LocalBP, and BiModeBP.
Referenced by predict().
update() [1/2]
void BPredUnit::update (const InstSeqNum & done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
Parameters
done_sn The sequence number to commit any older updates up until.
tid The thread id.
Definition at line 345 of file bpred_unit.cc.
References IndirectPredictor::commit(), DPRINTF, iPred, MipsISA::pc, and predHist.
Referenced by BaseSimpleCPU::advancePC(), BTBLookup(), DefaultFetch< Impl >::checkSignalsAndUpdate(), squash(), and Minor::Fetch2::updateBranchPrediction().
update() [2/2]
virtual void BPredUnit::update (ThreadID tid, Addr instPC, bool taken, void * bp_history, bool squashed, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr, Addr corrTarget = MaxAddr) pure virtual
Updates the BP with taken/not taken information.
Parameters
inst_PC The branch's PC that will be updated.
taken Whether the branch was taken or not taken.
bp_history Pointer to the branch predictor state that is associated with the branch lookup that is being updated.
squashed Set to true when this function is called during a squash operation.
inst Static instruction information
corrTarget The resolved target of the branch (only needed for squashed branches)
Todo:
Make this update flexible enough to handle a global predictor.
Implemented in MultiperspectivePerceptron, MultiperspectivePerceptronTAGE, TAGE_SC_L, TournamentBP, LocalBP, TAGE, LTAGE, and BiModeBP.
Member Data Documentation
BTB
DefaultBTB BPredUnit::BTB private
The BTB.
Definition at line 283 of file bpred_unit.hh.
Referenced by BTBLookup(), BTBUpdate(), BTBValid(), predict(), and squash().
BTBCorrect
Stats::Scalar BPredUnit::BTBCorrect private
Stat for number of times the BTB is correct.
Definition at line 302 of file bpred_unit.hh.
Referenced by regStats().
BTBHitPct
Stats::Formula BPredUnit::BTBHitPct private
Stat for percent times an entry in BTB found.
Definition at line 304 of file bpred_unit.hh.
Referenced by regStats().
BTBHits
Stats::Scalar BPredUnit::BTBHits private
Stat for number of BTB hits.
Definition at line 300 of file bpred_unit.hh.
Referenced by predict(), and regStats().
BTBLookups
Stats::Scalar BPredUnit::BTBLookups private
Stat for number of BTB lookups.
Definition at line 298 of file bpred_unit.hh.
Referenced by predict(), and regStats().
condIncorrect
Stats::Scalar BPredUnit::condIncorrect private
Stat for number of conditional branches predicted incorrectly.
Definition at line 296 of file bpred_unit.hh.
Referenced by regStats(), and squash().
condPredicted
Stats::Scalar BPredUnit::condPredicted private
Stat for number of conditional branches predicted.
Definition at line 294 of file bpred_unit.hh.
Referenced by predict(), and regStats().
indirectHits
Stats::Scalar BPredUnit::indirectHits private
Stat for the number of indirect target hits.
Definition at line 313 of file bpred_unit.hh.
Referenced by predict(), and regStats().
indirectLookups
Stats::Scalar BPredUnit::indirectLookups private
Stat for the number of indirect target lookups.
Definition at line 311 of file bpred_unit.hh.
Referenced by predict(), and regStats().
indirectMispredicted
Stats::Scalar BPredUnit::indirectMispredicted private
Stat for the number of indirect target mispredictions.
Definition at line 317 of file bpred_unit.hh.
Referenced by regStats(), and squash().
indirectMisses
Stats::Scalar BPredUnit::indirectMisses private
Stat for the number of indirect target misses.
Definition at line 315 of file bpred_unit.hh.
Referenced by predict(), and regStats().
instShiftAmt
const unsigned BPredUnit::instShiftAmt protected
Number of bits to shift instructions by for predictor addresses.
Definition at line 321 of file bpred_unit.hh.
Referenced by TAGE_SC_L_TAGE::bindex(), TournamentBP::calcLocHistIdx(), LocalBP::getLocalIndex(), TAGE_SC_L_TAGE_8KB::gtag(), LocalBP::LocalBP(), BiModeBP::lookup(), MultiperspectivePerceptronTAGE::lookup(), LTAGE::predict(), TAGE_SC_L::predict(), BiModeBP::update(), LTAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), and TAGE_SC_L_TAGE::updatePathAndGlobalHistory().
iPred
IndirectPredictor* BPredUnit::iPred private
The indirect target predictor.
Definition at line 289 of file bpred_unit.hh.
Referenced by predict(), squash(), and update().
lookups
Stats::Scalar BPredUnit::lookups private
Stat for number of BP lookups.
Definition at line 292 of file bpred_unit.hh.
Referenced by predict(), and regStats().
numThreads
const unsigned BPredUnit::numThreads private
Number of the threads for which the branch history is maintained.
Definition at line 272 of file bpred_unit.hh.
ppBranches
ProbePoints::PMUUPtr BPredUnit::ppBranches protected
Branches seen by the branch predictor.
Note
This counter includes speculative branches.
Definition at line 343 of file bpred_unit.hh.
Referenced by predict(), and regProbePoints().
ppMisses
ProbePoints::PMUUPtr BPredUnit::ppMisses protected
Miss-predicted branches.
Definition at line 346 of file bpred_unit.hh.
Referenced by regProbePoints(), and squash().
predHist
std::vector<History> BPredUnit::predHist private
The per-thread predictor history.
This is used to update the predictor as instructions are committed, or restore it to the proper state after a squash.
Definition at line 280 of file bpred_unit.hh.
Referenced by drainSanityCheck(), dump(), predict(), squash(), and update().
RAS
std::vector<ReturnAddrStack> BPredUnit::RAS private
The per-thread return address stack.
Definition at line 286 of file bpred_unit.hh.
Referenced by BPredUnit(), predict(), and squash().
RASIncorrect
Stats::Scalar BPredUnit::RASIncorrect private
Stat for number of times the RAS is incorrect.
Definition at line 308 of file bpred_unit.hh.
Referenced by regStats(), and squash().
usedRAS
Stats::Scalar BPredUnit::usedRAS private
Stat for number of times the RAS is used to get a target.
Definition at line 306 of file bpred_unit.hh.
Referenced by predict(), and regStats().
The documentation for this class was generated from the following files:
cpu/pred/bpred_unit.hh
cpu/pred/bpred_unit.cc