gem5: WalkCache Class Reference
WalkCache Class Reference
#include <smmu_v3_caches.hh>
Classes
struct Entry
Public Member Functions
WalkCache (const std::array< unsigned, 2 *WALK_CACHE_LEVELS > &_sizes, unsigned _associativity, const std::string &policy)
virtual ~WalkCache ()
const Entry * lookup (Addr va, Addr vaMask, uint16_t asid, uint16_t vmid, unsigned stage, unsigned level, bool updStats=true)
void store (const Entry &incoming)
void invalidateVA (Addr va, uint16_t asid, uint16_t vmid, const bool leaf_only)
void invalidateVAA (Addr va, uint16_t vmid, const bool leaf_only)
void invalidateASID (uint16_t asid, uint16_t vmid)
void invalidateVMID (uint16_t vmid)
void invalidateAll ()
void regStats (const std::string &name) override
Public Member Functions inherited from SMMUv3BaseCache
SMMUv3BaseCache (const std::string &policy_name, uint32_t seed)
virtual ~SMMUv3BaseCache ()
Protected Attributes
unsigned int lookupsByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Formula averageLookupsByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Scalar totalLookupsByStageLevel [2][WALK_CACHE_LEVELS]
unsigned int missesByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Formula averageMissesByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Scalar totalMissesByStageLevel [2][WALK_CACHE_LEVELS]
unsigned int updatesByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Formula averageUpdatesByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Scalar totalUpdatesByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Formula averageHitRateByStageLevel [2][WALK_CACHE_LEVELS]
Stats::Scalar insertionsByStageLevel [2][WALK_CACHE_LEVELS]
Protected Attributes inherited from SMMUv3BaseCache
int replacementPolicy
size_t nextToReplace
Random random
uint32_t useStamp
Stats::Formula averageLookups
Stats::Scalar totalLookups
Stats::Formula averageMisses
Stats::Scalar totalMisses
Stats::Formula averageUpdates
Stats::Scalar totalUpdates
Stats::Formula averageHitRate
Stats::Scalar insertions
Private Types
typedef std::vector< Entry > Set
Private Member Functions
size_t pickSetIdx (Addr va, Addr vaMask, unsigned stage, unsigned level) const
size_t pickEntryIdxToReplace (const Set &set, unsigned stage, unsigned level)
Private Attributes
std::vector< Set > sets
size_t associativity
std::array< unsigned, 2 *WALK_CACHE_LEVELS > sizes
std::array< unsigned, 2 *WALK_CACHE_LEVELS > offsets
Additional Inherited Members
Static Protected Member Functions inherited from SMMUv3BaseCache
static int decodePolicyName (const std::string &policy_name)
Detailed Description
Definition at line 283 of file smmu_v3_caches.hh.
Member Typedef Documentation
Set
typedef std::vector<Entry> WalkCache::Set private
Definition at line 340 of file smmu_v3_caches.hh.
Constructor & Destructor Documentation
WalkCache()
WalkCache::WalkCache (const std::array< unsigned, 2 *WALK_CACHE_LEVELS > & _sizes, unsigned _associativity, const std::string & policy)
Definition at line 972 of file smmu_v3_caches.cc.
References associativity, ArmISA::e, fatal, ArmISA::i, offsets, sets, sizes, WalkCache::Entry::valid, and WALK_CACHE_LEVELS.
~WalkCache()
virtual WalkCache::~WalkCache () inline virtual
Definition at line 307 of file smmu_v3_caches.hh.
References ArmISA::asid, X86ISA::level, name(), SMMUv3BaseCache::regStats(), and ArmISA::va.
Member Function Documentation
invalidateAll()
void WalkCache::invalidateAll ()
Definition at line 1153 of file smmu_v3_caches.cc.
References ArmISA::i, ArmISA::s, and sets.
Referenced by SMMUv3::processCommand().
invalidateASID()
void WalkCache::invalidateASID (uint16_t asid, uint16_t vmid)
Definition at line 1123 of file smmu_v3_caches.cc.
References WalkCache::Entry::asid, ArmISA::e, ArmISA::i, ArmISA::s, sets, WalkCache::Entry::valid, and WalkCache::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVA()
void WalkCache::invalidateVA (Addr va, uint16_t asid, uint16_t vmid, const bool leaf_only)
Definition at line 1086 of file smmu_v3_caches.cc.
References WalkCache::Entry::asid, ArmISA::e, ArmISA::i, WalkCache::Entry::leaf, ArmISA::s, sets, WalkCache::Entry::va, WalkCache::Entry::valid, WalkCache::Entry::vaMask, and WalkCache::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVAA()
void WalkCache::invalidateVAA (Addr va, uint16_t vmid, const bool leaf_only)
Definition at line 1105 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, WalkCache::Entry::leaf, ArmISA::s, sets, WalkCache::Entry::va, WalkCache::Entry::valid, WalkCache::Entry::vaMask, and WalkCache::Entry::vmid.
Referenced by SMMUv3::processCommand().
invalidateVMID()
void WalkCache::invalidateVMID (uint16_t vmid)
Definition at line 1138 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ArmISA::s, sets, WalkCache::Entry::valid, and WalkCache::Entry::vmid.
Referenced by SMMUv3::processCommand().
lookup()
const WalkCache::Entry * WalkCache::lookup (Addr va, Addr vaMask, uint16_t asid, uint16_t vmid, unsigned stage, unsigned level, bool updStats = true)
Definition at line 1014 of file smmu_v3_caches.cc.
References WalkCache::Entry::asid, ArmISA::e, ArmISA::i, WalkCache::Entry::lastUsed, X86ISA::level, WalkCache::Entry::level, lookupsByStageLevel, missesByStageLevel, panic, pickSetIdx(), sets, WalkCache::Entry::stage, SMMUv3BaseCache::totalLookups, totalLookupsByStageLevel, SMMUv3BaseCache::totalMisses, totalMissesByStageLevel, SMMUv3BaseCache::useStamp, WalkCache::Entry::va, WalkCache::Entry::valid, WalkCache::Entry::vaMask, and WalkCache::Entry::vmid.
Referenced by store(), and SMMUTranslationProcess::walkCacheLookup().
pickEntryIdxToReplace()
size_t WalkCache::pickEntryIdxToReplace (const Set & set, unsigned stage, unsigned level) private
Definition at line 1192 of file smmu_v3_caches.cc.
References associativity, ArmISA::i, SMMUv3BaseCache::insertions, insertionsByStageLevel, X86ISA::level, SMMUv3BaseCache::nextToReplace, panic, SMMUv3BaseCache::random, Random::random(), SMMUv3BaseCache::replacementPolicy, SMMU_CACHE_REPL_LRU, SMMU_CACHE_REPL_RANDOM, and SMMU_CACHE_REPL_ROUND_ROBIN.
Referenced by store().
pickSetIdx()
size_t WalkCache::pickSetIdx (Addr va, Addr vaMask, unsigned stage, unsigned level) const private
Definition at line 1164 of file smmu_v3_caches.cc.
References findLsbSet(), X86ISA::level, ArmISA::offset, offsets, panic, sizes, and WALK_CACHE_LEVELS.
Referenced by lookup(), and store().
regStats()
void WalkCache::regStats (const std::string & name) override virtual
Reimplemented from SMMUv3BaseCache.
Definition at line 1228 of file smmu_v3_caches.cc.
References averageHitRateByStageLevel, averageLookupsByStageLevel, averageMissesByStageLevel, averageUpdatesByStageLevel, csprintf(), Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), insertionsByStageLevel, MipsISA::l, Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::pdf, SMMUv3BaseCache::regStats(), ArmISA::s, simSeconds, totalLookupsByStageLevel, totalMissesByStageLevel, totalUpdatesByStageLevel, and WALK_CACHE_LEVELS.
Referenced by SMMUv3::regStats().
store()
void WalkCache::store (const Entry & incoming)
Definition at line 1057 of file smmu_v3_caches.cc.
References WalkCache::Entry::asid, WalkCache::Entry::lastUsed, WalkCache::Entry::level, lookup(), panic, pickEntryIdxToReplace(), pickSetIdx(), sets, WalkCache::Entry::stage, SMMUv3BaseCache::totalUpdates, totalUpdatesByStageLevel, updatesByStageLevel, WalkCache::Entry::va, WalkCache::Entry::valid, WalkCache::Entry::vaMask, WalkCache::Entry::vmid, and WALK_CACHE_LEVELS.
Referenced by SMMUTranslationProcess::walkCacheUpdate().
Member Data Documentation
associativity
size_t WalkCache::associativity private
Definition at line 343 of file smmu_v3_caches.hh.
Referenced by pickEntryIdxToReplace(), and WalkCache().
averageHitRateByStageLevel
Stats::Formula WalkCache::averageHitRateByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 335 of file smmu_v3_caches.hh.
Referenced by regStats().
averageLookupsByStageLevel
Stats::Formula WalkCache::averageLookupsByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 324 of file smmu_v3_caches.hh.
Referenced by regStats().
averageMissesByStageLevel
Stats::Formula WalkCache::averageMissesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 328 of file smmu_v3_caches.hh.
Referenced by regStats().
averageUpdatesByStageLevel
Stats::Formula WalkCache::averageUpdatesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 332 of file smmu_v3_caches.hh.
Referenced by regStats().
insertionsByStageLevel
Stats::Scalar WalkCache::insertionsByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 337 of file smmu_v3_caches.hh.
Referenced by pickEntryIdxToReplace(), and regStats().
lookupsByStageLevel
unsigned int WalkCache::lookupsByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 323 of file smmu_v3_caches.hh.
Referenced by lookup().
missesByStageLevel
unsigned int WalkCache::missesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 327 of file smmu_v3_caches.hh.
Referenced by lookup().
offsets
std::array<unsigned, 2*WALK_CACHE_LEVELS> WalkCache::offsets private
Definition at line 345 of file smmu_v3_caches.hh.
Referenced by pickSetIdx(), and WalkCache().
sets
std::vector<Set> WalkCache::sets private
Definition at line 341 of file smmu_v3_caches.hh.
Referenced by invalidateAll(), invalidateASID(), invalidateVA(), invalidateVAA(), invalidateVMID(), lookup(), store(), and WalkCache().
sizes
std::array<unsigned, 2*WALK_CACHE_LEVELS> WalkCache::sizes private
Definition at line 344 of file smmu_v3_caches.hh.
Referenced by pickSetIdx(), and WalkCache().
totalLookupsByStageLevel
Stats::Scalar WalkCache::totalLookupsByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 325 of file smmu_v3_caches.hh.
Referenced by lookup(), and regStats().
totalMissesByStageLevel
Stats::Scalar WalkCache::totalMissesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 329 of file smmu_v3_caches.hh.
Referenced by lookup(), and regStats().
totalUpdatesByStageLevel
Stats::Scalar WalkCache::totalUpdatesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 333 of file smmu_v3_caches.hh.
Referenced by regStats(), and store().
updatesByStageLevel
unsigned int WalkCache::updatesByStageLevel[2][WALK_CACHE_LEVELS] protected
Definition at line 331 of file smmu_v3_caches.hh.
Referenced by store().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_caches.hh
dev/arm/smmu_v3_caches.cc