gem5: ArmISA::ITLBIALL Class Reference
ArmISA::ITLBIALL Class Reference
Instruction TLB Invalidate All.
#include <tlbi_op.hh>
Public Member Functions
ITLBIALL (ExceptionLevel _targetEL, bool _secure)
void broadcast (ThreadContext *tc)=delete
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Additional Inherited Members
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
Instruction TLB Invalidate All.
Definition at line 97 of file tlbi_op.hh.
Constructor & Destructor Documentation
ITLBIALL()
ArmISA::ITLBIALL::ITLBIALL (ExceptionLevel _targetEL, bool _secure) inline
Definition at line 100 of file tlbi_op.hh.
References ArmISA::TLBIOp::broadcast(), and ArmISA::TLBIOp::operator()().
Member Function Documentation
broadcast()
void ArmISA::ITLBIALL::broadcast (ThreadContext * tc) delete
operator()()
void ArmISA::ITLBIALL::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 64 of file tlbi_op.cc.
References ArmISA::TLB::flushAllSecurity(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc