gem5: PciHost::DeviceInterface Class Reference
PciHost::DeviceInterface Class Reference
Callback interface from PCI devices to the host.
#include <host.hh>
Public Member Functions
DeviceInterface ()=delete
void operator= (const DeviceInterface &)=delete
const std::string name () const
void postInt ()
Post a PCI interrupt to the CPU.
void clearInt ()
Clear a posted PCI interrupt.
Addr pioAddr (Addr addr) const
Calculate the physical address of an IO location on the PCI bus.
Addr memAddr (Addr addr) const
Calculate the physical address of a non-prefetchable memory location in the PCI address space.
Addr dmaAddr (Addr addr) const
Calculate the physical address of a prefetchable memory location in the PCI address space.
Protected Member Functions
DeviceInterface (PciHost &host, PciBusAddr &bus_addr, PciIntPin pin)
Instantiate a device interface.
Protected Attributes
PciHost & host
const PciBusAddr busAddr
const PciIntPin interruptPin
Friends
class ::PciHost
Detailed Description
Callback interface from PCI devices to the host.
Devices get an instance of this object when they register themselves with the host using the PciHost::registerDevice() call.
Definition at line 93 of file host.hh.
Constructor & Destructor Documentation
DeviceInterface() [1/2]
PciHost::DeviceInterface::DeviceInterface (PciHost & host, PciBusAddr & bus_addr, PciIntPin pin) protected
Instantiate a device interface.
Parameters
host PCI host that this device belongs to.
bus_addr The device's position on the PCI bus
pin Interrupt pin
Definition at line 88 of file host.cc.
DeviceInterface() [2/2]
PciHost::DeviceInterface::DeviceInterface () delete
Member Function Documentation
clearInt()
void PciHost::DeviceInterface::clearInt ()
Clear a posted PCI interrupt.
Definition at line 112 of file host.cc.
References busAddr, PciHost::clearInt(), DPRINTF, host, and interruptPin.
Referenced by GenericPciHost::dmaAddr(), and PciDevice::intrClear().
dmaAddr()
Addr PciHost::DeviceInterface::dmaAddr (Addr addr) const inline
Calculate the physical address of a prefetchable memory location in the PCI address space.
Parameters
addr Address in the PCI DMA memory address space
Returns
Address in the system's physical address space.
Definition at line 148 of file host.hh.
References busAddr, PciHost::dmaAddr(), and host.
Referenced by PciDevice::pciToDma().
memAddr()
Addr PciHost::DeviceInterface::memAddr (Addr addr) const inline
Calculate the physical address of a non-prefetchable memory location in the PCI address space.
Parameters
addr Address in the PCI memory address space
Returns
Address in the system's physical address space.
Definition at line 139 of file host.hh.
References busAddr, host, and PciHost::memAddr().
Referenced by PciDevice::writeConfig().
name()
const std::string PciHost::DeviceInterface::name () const
Definition at line 97 of file host.cc.
References PciBusAddr::bus, busAddr, csprintf(), PciBusAddr::dev, PciBusAddr::func, host, and SimObject::name().
operator=()
void PciHost::DeviceInterface::operator= (const DeviceInterface &) delete
pioAddr()
Addr PciHost::DeviceInterface::pioAddr (Addr addr) const inline
Calculate the physical address of an IO location on the PCI bus.
Parameters
addr Address in the PCI IO address space
Returns
Address in the system's physical address space.
Definition at line 130 of file host.hh.
References busAddr, host, and PciHost::pioAddr().
Referenced by PciDevice::writeConfig().
postInt()
void PciHost::DeviceInterface::postInt ()
Post a PCI interrupt to the CPU.
Definition at line 104 of file host.cc.
References busAddr, DPRINTF, host, interruptPin, and PciHost::postInt().
Referenced by GenericPciHost::dmaAddr(), and PciDevice::intrPost().
Friends And Related Function Documentation
::PciHost
friend class ::PciHost friend
Definition at line 95 of file host.hh.
Member Data Documentation
busAddr
const PciBusAddr PciHost::DeviceInterface::busAddr protected
Definition at line 153 of file host.hh.
Referenced by clearInt(), dmaAddr(), memAddr(), name(), pioAddr(), and postInt().
host
PciHost& PciHost::DeviceInterface::host protected
Definition at line 151 of file host.hh.
Referenced by clearInt(), dmaAddr(), memAddr(), name(), pioAddr(), and postInt().
interruptPin
const PciIntPin PciHost::DeviceInterface::interruptPin protected
Definition at line 154 of file host.hh.
Referenced by clearInt(), and postInt().
The documentation for this class was generated from the following files:
dev/pci/host.hh
dev/pci/host.cc