gem5: SimpleATInitiator2::MyTransaction< DT > Class Template Reference
SimpleATInitiator2::MyTransaction< DT > Class Template Reference
#include <SimpleATInitiator2.h>
Public Member Functions
MyTransaction ()
MyTransaction (tlm::tlm_mm_interface *mm)
void setData (DT &data)
DT getData () const
Public Member Functions inherited from tlm::tlm_generic_payload
tlm_generic_payload ()
tlm_generic_payload (tlm_mm_interface *mm)
void acquire ()
void release ()
int get_ref_count () const
void set_mm (tlm_mm_interface *mm)
bool has_mm () const
void reset ()
void deep_copy_from (const tlm_generic_payload &other)
void update_original_from (const tlm_generic_payload &other, bool use_byte_enable_on_read=true)
void update_extensions_from (const tlm_generic_payload &other)
void free_all_extensions ()
virtual ~tlm_generic_payload ()
bool is_read () const
void set_read ()
bool is_write () const
void set_write ()
tlm_command get_command () const
void set_command (const tlm_command command)
sc_dt::uint64 get_address () const
void set_address (const sc_dt::uint64 address)
unsigned char * get_data_ptr () const
void set_data_ptr (unsigned char *data)
unsigned int get_data_length () const
void set_data_length (const unsigned int length)
bool is_response_ok () const
bool is_response_error () const
tlm_response_status get_response_status () const
void set_response_status (const tlm_response_status response_status)
std::string get_response_string () const
unsigned int get_streaming_width () const
void set_streaming_width (const unsigned int streaming_width)
unsigned char * get_byte_enable_ptr () const
void set_byte_enable_ptr (unsigned char *byte_enable)
unsigned int get_byte_enable_length () const
void set_byte_enable_length (const unsigned int byte_enable_length)
void set_dmi_allowed (bool dmi_allowed)
bool is_dmi_allowed () const
tlm_gp_option get_gp_option () const
void set_gp_option (const tlm_gp_option gp_opt)
template<typename T >
T * set_extension (T *ext)
tlm_extension_base * set_extension (unsigned int index, tlm_extension_base *ext)
template<typename T >
T * set_auto_extension (T *ext)
tlm_extension_base * set_auto_extension (unsigned int index, tlm_extension_base *ext)
template<typename T >
void get_extension (T *&ext) const
template<typename T >
T * get_extension () const
tlm_extension_base * get_extension (unsigned int index) const
template<typename T >
void clear_extension (const T *ext)
template<typename T >
void clear_extension ()
template<typename T >
void release_extension (T *ext)
template<typename T >
void release_extension ()
void resize_extensions ()
Private Attributes
DT mData
Detailed Description
template<typename DT>
class SimpleATInitiator2::MyTransaction< DT >
Definition at line 53 of file SimpleATInitiator2.h.
Constructor & Destructor Documentation
MyTransaction() [1/2]
template<typename DT > SimpleATInitiator2::MyTransaction< DT >::MyTransaction () inline
Definition at line 56 of file SimpleATInitiator2.h.
References SimpleATInitiator2::MyTransaction< DT >::mData, and tlm::tlm_generic_payload::set_data_ptr().
MyTransaction() [2/2]
template<typename DT > SimpleATInitiator2::MyTransaction< DT >::MyTransaction (tlm::tlm_mm_interface * mm) inline
Definition at line 60 of file SimpleATInitiator2.h.
References SimpleATInitiator2::MyTransaction< DT >::mData, and tlm::tlm_generic_payload::set_data_ptr().
Member Function Documentation
getData()
template<typename DT > DT SimpleATInitiator2::MyTransaction< DT >::getData () const inline
Definition at line 66 of file SimpleATInitiator2.h.
References SimpleATInitiator2::MyTransaction< DT >::mData.
Referenced by SimpleATInitiator2::logEndTransaction(), and SimpleATInitiator2::logStartTransation().
setData()
template<typename DT > void SimpleATInitiator2::MyTransaction< DT >::setData (DT & data) inline
Definition at line 65 of file SimpleATInitiator2.h.
References data, and SimpleATInitiator2::MyTransaction< DT >::mData.
Referenced by SimpleATInitiator2::initTransaction().
Member Data Documentation
mData
template<typename DT > DT SimpleATInitiator2::MyTransaction< DT >::mData private
Definition at line 69 of file SimpleATInitiator2.h.
Referenced by SimpleATInitiator2::MyTransaction< DT >::getData(), SimpleATInitiator2::MyTransaction< DT >::MyTransaction(), and SimpleATInitiator2::MyTransaction< DT >::setData().
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleATInitiator2.h