gem5: ConditionRegisterState Class Reference
ConditionRegisterState Class Reference
#include <condition_register_state.hh>
Public Member Functions
ConditionRegisterState ()
void init (uint32_t _size)
const std::string name () const
void setParent (ComputeUnit *_computeUnit)
void regStats ()
template<typename T >
T read (int regIdx, int threadId)
template<typename T >
void write (int regIdx, int threadId, T value)
void markReg (int regIdx, uint8_t value)
uint8_t regBusy (int idx)
int numRegs ()
void exec (GPUDynInstPtr ii, Wavefront *w)
Private Attributes
ComputeUnit * computeUnit
std::string _name
std::vector< VectorMask > c_reg
std::vector< uint8_t > busy
Detailed Description
Definition at line 50 of file condition_register_state.hh.
Constructor & Destructor Documentation
ConditionRegisterState()
ConditionRegisterState::ConditionRegisterState ()
Definition at line 43 of file condition_register_state.cc.
References busy, c_reg, and computeUnit.
Member Function Documentation
exec()
void ConditionRegisterState::exec (GPUDynInstPtr ii, Wavefront * w)
Definition at line 65 of file condition_register_state.cc.
References Wavefront::computeUnit, ArmISA::i, markReg(), ComputeUnit::shader, Wavefront::simdId, ComputeUnit::spBypassLength(), Shader::tick_cnt, and Shader::ticks().
Referenced by numRegs(), and Wavefront::setParent().
init()
void ConditionRegisterState::init (uint32_t _size)
Definition at line 58 of file condition_register_state.cc.
References busy, and c_reg.
Referenced by Wavefront::resizeRegFiles().
markReg()
void ConditionRegisterState::markReg (int regIdx, uint8_t value) inline
Definition at line 77 of file condition_register_state.hh.
References busy.
Referenced by exec().
name()
const std::string ConditionRegisterState::name () const inline
Definition at line 55 of file condition_register_state.hh.
References _name, and setParent().
numRegs()
int ConditionRegisterState::numRegs () inline
Definition at line 89 of file condition_register_state.hh.
References c_reg, exec(), and MipsISA::w.
Referenced by Wavefront::getContext(), and Wavefront::setContext().
read()
template<typename T > T ConditionRegisterState::read (int regIdx, int threadId) inline
Definition at line 61 of file condition_register_state.hh.
References c_reg.
Referenced by CRegOperand::get(), and Wavefront::getContext().
regBusy()
uint8_t ConditionRegisterState::regBusy (int idx) inline
Definition at line 83 of file condition_register_state.hh.
References busy, and ArmISA::status.
regStats()
void ConditionRegisterState::regStats () inline
Definition at line 57 of file condition_register_state.hh.
Referenced by Wavefront::setParent().
setParent()
void ConditionRegisterState::setParent (ComputeUnit * _computeUnit)
Definition at line 51 of file condition_register_state.cc.
References _name, computeUnit, and SimObject::name().
Referenced by name().
write()
template<typename T > void ConditionRegisterState::write (int regIdx, int threadId, T value) inline
Definition at line 71 of file condition_register_state.hh.
References c_reg.
Referenced by CRegOperand::set(), and Wavefront::setContext().
Member Data Documentation
_name
std::string ConditionRegisterState::_name private
Definition at line 94 of file condition_register_state.hh.
Referenced by name(), and setParent().
busy
std::vector<uint8_t> ConditionRegisterState::busy private
Definition at line 98 of file condition_register_state.hh.
Referenced by ConditionRegisterState(), init(), markReg(), and regBusy().
c_reg
std::vector<VectorMask> ConditionRegisterState::c_reg private
Definition at line 96 of file condition_register_state.hh.
Referenced by ConditionRegisterState(), init(), numRegs(), read(), and write().
computeUnit
ComputeUnit* ConditionRegisterState::computeUnit private
Definition at line 93 of file condition_register_state.hh.
Referenced by ConditionRegisterState(), and setParent().
The documentation for this class was generated from the following files:
gpu-compute/condition_register_state.hh
gpu-compute/condition_register_state.cc