gem5: sc_dt::sc_fxnum_subref Class Reference
sc_dt::sc_fxnum_subref Class Reference
#include <sc_fxnum.hh>
Public Member Functions
sc_fxnum_subref (const sc_fxnum_subref &)
~sc_fxnum_subref ()
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
int length () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
operator sc_bv_base () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
Private Member Functions
bool get () const
bool set ()
sc_fxnum_subref (sc_fxnum &, int, int)
sc_fxnum_subref ()
Private Attributes
sc_fxnum & m_num
int m_from
int m_to
sc_bv_base & m_bv
Friends
class sc_fxnum
class sc_fxnum_fast_subref
Detailed Description
Definition at line 213 of file sc_fxnum.hh.
Constructor & Destructor Documentation
sc_fxnum_subref() [1/3]
sc_dt::sc_fxnum_subref::sc_fxnum_subref (sc_fxnum & num_, int from_, int to_) inline private
Definition at line 1592 of file sc_fxnum.hh.
sc_fxnum_subref() [2/3]
sc_dt::sc_fxnum_subref::sc_fxnum_subref (const sc_fxnum_subref & a) inline
Definition at line 1598 of file sc_fxnum.hh.
~sc_fxnum_subref()
sc_dt::sc_fxnum_subref::~sc_fxnum_subref () inline
Definition at line 1604 of file sc_fxnum.hh.
References ArmISA::a, and_reduce(), DEFN_ASN_OP, DEFN_ASN_OP_T, DEFN_RED_FNC, DEFN_REL_OP, m_bv, m_num, nand_reduce(), nor_reduce(), or_reduce(), SC_FXNUM_OBSERVER_WRITE_, xnor_reduce(), and xor_reduce().
sc_fxnum_subref() [3/3]
sc_dt::sc_fxnum_subref::sc_fxnum_subref () private
Member Function Documentation
and_reduce()
bool sc_dt::sc_fxnum_subref::and_reduce () const
Referenced by ~sc_fxnum_subref().
dump()
void sc_dt::sc_fxnum_subref::dump (::std::ostream & os = ::std::cout) const
Definition at line 160 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::dump(), and sc_dt::sc_fxnum_bitref::m_num.
get()
bool sc_dt::sc_fxnum_subref::get () const private
Definition at line 133 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::get_slice(), and sc_dt::sc_fxnum_bitref::m_num.
length()
int sc_dt::sc_fxnum_subref::length () const inline
Definition at line 1770 of file sc_fxnum.hh.
References sc_dt::sc_bv_base::length(), and m_bv.
nand_reduce()
bool sc_dt::sc_fxnum_subref::nand_reduce () const
Referenced by ~sc_fxnum_subref().
nor_reduce()
bool sc_dt::sc_fxnum_subref::nor_reduce () const
Referenced by ~sc_fxnum_subref().
operator sc_bv_base()
sc_dt::sc_fxnum_subref::operator sc_bv_base () const inline
Definition at line 1848 of file sc_fxnum.hh.
References m_bv, m_num, and SC_FXNUM_OBSERVER_READ_.
or_reduce()
bool sc_dt::sc_fxnum_subref::or_reduce () const
Referenced by ~sc_fxnum_subref().
print()
void sc_dt::sc_fxnum_subref::print (::std::ostream & os = ::std::cout) const
Definition at line 146 of file sc_fxnum.cc.
Referenced by sc_dt::operator<<().
scan()
void sc_dt::sc_fxnum_subref::scan (::std::istream & is = ::std::cin)
Definition at line 153 of file sc_fxnum.cc.
Referenced by sc_dt::operator>>().
set()
bool sc_dt::sc_fxnum_subref::set () private
Definition at line 139 of file sc_fxnum.cc.
References sc_dt::sc_fxnum_bitref::m_num, and sc_dt::sc_fxnum::set_slice().
to_int()
int sc_dt::sc_fxnum_subref::to_int () const inline
Definition at line 1777 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_int().
to_int64()
int64 sc_dt::sc_fxnum_subref::to_int64 () const inline
Definition at line 1785 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_int64().
to_long()
long sc_dt::sc_fxnum_subref::to_long () const inline
Definition at line 1809 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_long().
to_string() [1/3]
const std::string sc_dt::sc_fxnum_subref::to_string () const inline
Definition at line 1826 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_string() [2/3]
const std::string sc_dt::sc_fxnum_subref::to_string (sc_numrep numrep) const inline
Definition at line 1833 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_string() [3/3]
const std::string sc_dt::sc_fxnum_subref::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 1840 of file sc_fxnum.hh.
References m_bv, and sc_dt::sc_proxy< X >::to_string().
to_uint()
unsigned int sc_dt::sc_fxnum_subref::to_uint () const inline
Definition at line 1793 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_uint().
to_uint64()
uint64 sc_dt::sc_fxnum_subref::to_uint64 () const inline
Definition at line 1801 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_uint64().
to_ulong()
unsigned long sc_dt::sc_fxnum_subref::to_ulong () const inline
Definition at line 1817 of file sc_fxnum.hh.
References m_bv, m_num, SC_FXNUM_OBSERVER_READ_, and sc_dt::sc_proxy< X >::to_ulong().
xnor_reduce()
bool sc_dt::sc_fxnum_subref::xnor_reduce () const
Referenced by ~sc_fxnum_subref().
xor_reduce()
bool sc_dt::sc_fxnum_subref::xor_reduce () const
Referenced by ~sc_fxnum_subref().
Friends And Related Function Documentation
sc_fxnum
friend class sc_fxnum friend
Definition at line 215 of file sc_fxnum.hh.
sc_fxnum_fast_subref
friend class sc_fxnum_fast_subref friend
Definition at line 216 of file sc_fxnum.hh.
Member Data Documentation
m_bv
sc_bv_base& sc_dt::sc_fxnum_subref::m_bv private
Definition at line 334 of file sc_fxnum.hh.
Referenced by length(), operator sc_bv_base(), to_int(), to_int64(), to_long(), to_string(), to_uint(), to_uint64(), to_ulong(), and ~sc_fxnum_subref().
m_from
int sc_dt::sc_fxnum_subref::m_from private
Definition at line 331 of file sc_fxnum.hh.
m_num
sc_fxnum& sc_dt::sc_fxnum_subref::m_num private
Definition at line 330 of file sc_fxnum.hh.
Referenced by operator sc_bv_base(), to_int(), to_int64(), to_long(), to_uint(), to_uint64(), to_ulong(), and ~sc_fxnum_subref().
m_to
int sc_dt::sc_fxnum_subref::m_to private
Definition at line 332 of file sc_fxnum.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum.hh
systemc/dt/fx/sc_fxnum.cc