gem5: PciVirtIO Class Reference
PciVirtIO Class Reference
#include <pci.hh>
Public Types
typedef PciVirtIOParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
PciVirtIO (const Params *params)
virtual ~PciVirtIO ()
Tick read (PacketPtr pkt)
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt)
Pure virtual function that the device must implement.
void kick ()
Public Member Functions inherited from PciDevice
virtual Tick writeConfig (PacketPtr pkt)
Write to the PCI config space data that is stored locally.
virtual Tick readConfig (PacketPtr pkt)
Read from the PCI config space data that is stored locally.
Addr pciToDma (Addr pci_addr) const
void intrPost ()
void intrClear ()
uint8_t interruptLine () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
PciDevice (const PciDeviceParams *params)
Constructor for PCI Dev.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
const PciBusAddr & busAddr () const
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
VirtIODeviceBase::QueueID queueNotify
bool interruptDeliveryPending
VirtIODeviceBase & vio
MakeCallback< PciVirtIO, &PciVirtIO::kick > callbackKick
Protected Attributes inherited from PciDevice
const PciBusAddr _busAddr
PCIConfig config
The current config space.
std::vector< MSIXTable > msix_table
MSIX Table and PBA Structures.
std::vector< MSIXPbaEntry > msix_pba
uint32_t BARSize [6]
The size of the BARs.
Addr BARAddrs [6]
The current address mapping of the BARs.
bool legacyIO [6]
Whether the BARs are really hardwired legacy IO locations.
PciHost::DeviceInterface hostInterface
Tick pioDelay
Tick configDelay
const int PMCAP_BASE
The capability list structures and base addresses.
const int PMCAP_ID_OFFSET
const int PMCAP_PC_OFFSET
const int PMCAP_PMCS_OFFSET
PMCAP pmcap
const int MSICAP_BASE
MSICAP msicap
const int MSIXCAP_BASE
const int MSIXCAP_ID_OFFSET
const int MSIXCAP_MXC_OFFSET
const int MSIXCAP_MTAB_OFFSET
const int MSIXCAP_MPBA_OFFSET
int MSIX_TABLE_OFFSET
int MSIX_TABLE_END
int MSIX_PBA_OFFSET
int MSIX_PBA_END
MSIXCAP msixcap
const int PXCAP_BASE
PXCAP pxcap
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const Addr BAR0_SIZE_BASE = OFF_VIO_DEVICE
static const Addr OFF_DEVICE_FEATURES = 0x00
Offsets into VirtIO header (BAR0 relative).
static const Addr OFF_GUEST_FEATURES = 0x04
static const Addr OFF_QUEUE_ADDRESS = 0x08
static const Addr OFF_QUEUE_SIZE = 0x0C
static const Addr OFF_QUEUE_SELECT = 0x0E
static const Addr OFF_QUEUE_NOTIFY = 0x10
static const Addr OFF_DEVICE_STATUS = 0x12
static const Addr OFF_ISR_STATUS = 0x13
static const Addr OFF_VIO_DEVICE = 0x14
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from PciDevice
bool isLargeBAR (int bar) const
Does the given BAR represent 32 lower bits of a 64-bit address?
bool isBAR (Addr addr, int bar) const
Does the given address lie within the space mapped by the given base address register?
int getBAR (Addr addr)
Which base address register (if any) maps the given address?
bool getBAR (Addr addr, int &bar, Addr &offs)
Which base address register (if any) maps the given address?
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 49 of file pci.hh.
Member Typedef Documentation
Params
typedef PciVirtIOParams PciVirtIO::Params
Definition at line 52 of file pci.hh.
Constructor & Destructor Documentation
PciVirtIO()
PciVirtIO::PciVirtIO (const Params * params)
Definition at line 47 of file pci.cc.
References alignToPowerOfTwo(), BAR0_SIZE_BASE, PciDevice::BARSize, callbackKick, PciDevice::config, VirtIODeviceBase::configSize, VirtIODeviceBase::deviceId, htole(), VirtIODeviceBase::registerKickCallback(), PCIConfig::subsystemID, and vio.
Referenced by kick().
~PciVirtIO()
PciVirtIO::~PciVirtIO () virtual
Definition at line 63 of file pci.cc.
Member Function Documentation
kick()
void PciVirtIO::kick ()
Definition at line 221 of file pci.cc.
References DPRINTF, interruptDeliveryPending, PciDevice::intrPost(), and PciVirtIO().
read()
Tick PciVirtIO::read (PacketPtr pkt) virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 68 of file pci.cc.
References VirtIODeviceBase::deviceFeatures, DPRINTF, Packet::getAddr(), PciDevice::getBAR(), VirtIODeviceBase::getDeviceStatus(), VirtIODeviceBase::getGuestFeatures(), VirtIODeviceBase::getQueueAddress(), VirtIODeviceBase::getQueueSelect(), VirtIODeviceBase::getQueueSize(), Packet::getSize(), interruptDeliveryPending, PciDevice::intrClear(), M5_VAR_USED, Packet::makeResponse(), OFF_DEVICE_FEATURES, OFF_DEVICE_STATUS, OFF_GUEST_FEATURES, OFF_ISR_STATUS, OFF_QUEUE_ADDRESS, OFF_QUEUE_NOTIFY, OFF_QUEUE_SELECT, OFF_QUEUE_SIZE, OFF_VIO_DEVICE, ArmISA::offset, panic, queueNotify, VirtIODeviceBase::readConfig(), Packet::setLE(), and vio.
write()
Tick PciVirtIO::write (PacketPtr pkt) virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 149 of file pci.cc.
References DPRINTF, Packet::getAddr(), PciDevice::getBAR(), Packet::getLE(), Packet::getSize(), M5_VAR_USED, Packet::makeResponse(), OFF_DEVICE_FEATURES, OFF_DEVICE_STATUS, OFF_GUEST_FEATURES, OFF_ISR_STATUS, OFF_QUEUE_ADDRESS, OFF_QUEUE_NOTIFY, OFF_QUEUE_SELECT, OFF_QUEUE_SIZE, OFF_VIO_DEVICE, ArmISA::offset, VirtIODeviceBase::onNotify(), panic, queueNotify, VirtIODeviceBase::setDeviceStatus(), VirtIODeviceBase::setGuestFeatures(), VirtIODeviceBase::setQueueAddress(), VirtIODeviceBase::setQueueSelect(), ArmISA::status, vio, warn, and VirtIODeviceBase::writeConfig().
Member Data Documentation
BAR0_SIZE_BASE
const Addr PciVirtIO::BAR0_SIZE_BASE = OFF_VIO_DEVICE static protected
Definition at line 77 of file pci.hh.
Referenced by PciVirtIO().
callbackKick
MakeCallback<PciVirtIO, &PciVirtIO::kick> PciVirtIO::callbackKick protected
Definition at line 86 of file pci.hh.
Referenced by PciVirtIO().
interruptDeliveryPending
bool PciVirtIO::interruptDeliveryPending protected
Definition at line 82 of file pci.hh.
Referenced by kick(), and read().
OFF_DEVICE_FEATURES
const Addr PciVirtIO::OFF_DEVICE_FEATURES = 0x00 static protected
Offsets into VirtIO header (BAR0 relative).
Definition at line 65 of file pci.hh.
Referenced by read(), and write().
OFF_DEVICE_STATUS
const Addr PciVirtIO::OFF_DEVICE_STATUS = 0x12 static protected
Definition at line 71 of file pci.hh.
Referenced by read(), and write().
OFF_GUEST_FEATURES
const Addr PciVirtIO::OFF_GUEST_FEATURES = 0x04 static protected
Definition at line 66 of file pci.hh.
Referenced by read(), and write().
OFF_ISR_STATUS
const Addr PciVirtIO::OFF_ISR_STATUS = 0x13 static protected
Definition at line 72 of file pci.hh.
Referenced by read(), and write().
OFF_QUEUE_ADDRESS
const Addr PciVirtIO::OFF_QUEUE_ADDRESS = 0x08 static protected
Definition at line 67 of file pci.hh.
Referenced by read(), and write().
OFF_QUEUE_NOTIFY
const Addr PciVirtIO::OFF_QUEUE_NOTIFY = 0x10 static protected
Definition at line 70 of file pci.hh.
Referenced by read(), and write().
OFF_QUEUE_SELECT
const Addr PciVirtIO::OFF_QUEUE_SELECT = 0x0E static protected
Definition at line 69 of file pci.hh.
Referenced by read(), and write().
OFF_QUEUE_SIZE
const Addr PciVirtIO::OFF_QUEUE_SIZE = 0x0C static protected
Definition at line 68 of file pci.hh.
Referenced by read(), and write().
OFF_VIO_DEVICE
const Addr PciVirtIO::OFF_VIO_DEVICE = 0x14 static protected
Definition at line 73 of file pci.hh.
Referenced by read(), and write().
queueNotify
VirtIODeviceBase::QueueID PciVirtIO::queueNotify protected
Definition at line 80 of file pci.hh.
Referenced by read(), and write().
vio
VirtIODeviceBase& PciVirtIO::vio protected
Definition at line 84 of file pci.hh.
Referenced by PciVirtIO(), read(), and write().
The documentation for this class was generated from the following files:
dev/virtio/pci.hh
dev/virtio/pci.cc