gem5: TsunamiPChip Class Reference
TsunamiPChip Class Reference
A very simple implementation of the Tsunami PCI interface chips.
#include <tsunami_pchip.hh>
Public Types
typedef TsunamiPChipParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TsunamiPChip (const Params *p)
Register the PChip with the mmu and init all wsba, wsm, and tba to 0.
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Addr dmaAddr (const PciBusAddr &addr, Addr pci_addr) const override
Translate a PCI bus address to a memory address for DMA.
Public Member Functions inherited from GenericPciHost
GenericPciHost (const GenericPciHostParams *p)
virtual ~GenericPciHost ()
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Public Member Functions inherited from PciHost
PciHost (const PciHostParams *p)
virtual ~PciHost ()
virtual DeviceInterface registerDevice (PciDevice *device, PciBusAddr bus_addr, PciIntPin pin)
Register a PCI device with the host.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
uint64_t pctl
Pchip control register.
uint64_t wsba [4]
Window Base addresses.
uint64_t wsm [4]
Window masks.
uint64_t tba [4]
Translated Base Addresses.
const AddrRange pioRange
const Tick pioDelay
Protected Attributes inherited from GenericPciHost
Platform & platform
const Addr confBase
const Addr confSize
const uint8_t confDeviceBits
const Addr pciPioBase
const Addr pciMemBase
const Addr pciDmaBase
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from GenericPciHost
Addr pioAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of an IO location on the PCI bus.
Addr memAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of a non-prefetchable memory location in the PCI address space.
Addr dmaAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of a prefetchable memory location in the PCI address space.
virtual std::pair< PciBusAddr, Addr > decodeAddress (Addr address)
Decode a configuration space address.
void postInt (const PciBusAddr &addr, PciIntPin pin) override
Post an interrupt to the CPU.
void clearInt (const PciBusAddr &addr, PciIntPin pin) override
Post an interrupt to the CPU.
virtual uint32_t mapPciInterrupt (const PciBusAddr &bus_addr, PciIntPin pin) const
Protected Member Functions inherited from PciHost
PciDevice * getDevice (const PciBusAddr &addr)
Retrieve a PCI device from its bus address.
const PciDevice * getDevice (const PciBusAddr &addr) const
Retrieve a PCI device from its bus address.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
A very simple implementation of the Tsunami PCI interface chips.
Definition at line 45 of file tsunami_pchip.hh.
Member Typedef Documentation
Params
typedef TsunamiPChipParams TsunamiPChip::Params
Definition at line 62 of file tsunami_pchip.hh.
Constructor & Destructor Documentation
TsunamiPChip()
TsunamiPChip::TsunamiPChip (const Params * p)
Register the PChip with the mmu and init all wsba, wsm, and tba to 0.
Parameters
p pointer to the parameters struct
Definition at line 53 of file tsunami_pchip.cc.
References ArmISA::i, pctl, tba, ULL, wsba, and wsm.
Referenced by unserialize().
Member Function Documentation
dmaAddr()
Addr TsunamiPChip::dmaAddr (const PciBusAddr & addr, Addr pci_addr) const override virtual
Translate a PCI bus address to a memory address for DMA.
Todo:
Andrew says this needs to be fixed. What's wrong with it?
Parameters
pci_addr PCI address to translate.
Returns
memory system address
Todo:
This currently is faked by just doing a direct read from memory, however, to be realistic, this needs to actually do a bus transaction. The process is explained in the tsunami documentation on page 10-12 and basically munges the address to look up a PTE from a table in memory and then uses that mapping to create an address for the SG page
Implements PciHost.
Definition at line 250 of file tsunami_pchip.cc.
References DMA_ADDR_MASK, ArmISA::i, System::physProxy, PortProxy::readBlob(), PioDevice::sys, tba, ULL, wsba, and wsm.
Referenced by params().
getAddrRanges()
AddrRangeList TsunamiPChip::getAddrRanges () const override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 238 of file tsunami_pchip.cc.
References GenericPciHost::confBase, GenericPciHost::confSize, pioRange, and RangeSize().
Referenced by params().
params()
const Params* TsunamiPChip::params () const inline
Definition at line 70 of file tsunami_pchip.hh.
References SimObject::_params, addr, dmaAddr(), getAddrRanges(), read(), serialize(), unserialize(), and write().
read()
Tick TsunamiPChip::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 72 of file tsunami_pchip.cc.
References AddrRange::contains(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, pctl, pioDelay, pioRange, GenericPciHost::read(), Packet::setLE(), AddrRange::start(), tba, TSDEV_PC_PCTL, TSDEV_PC_PERRMASK, TSDEV_PC_PERROR, TSDEV_PC_PERRSET, TSDEV_PC_PLAT, TSDEV_PC_PMONCNT, TSDEV_PC_PMONCTL, TSDEV_PC_RES, TSDEV_PC_TBA0, TSDEV_PC_TBA1, TSDEV_PC_TBA2, TSDEV_PC_TBA3, TSDEV_PC_TLBIA, TSDEV_PC_TLBIV, TSDEV_PC_WSBA0, TSDEV_PC_WSBA1, TSDEV_PC_WSBA2, TSDEV_PC_WSBA3, TSDEV_PC_WSM0, TSDEV_PC_WSM1, TSDEV_PC_WSM2, TSDEV_PC_WSM3, wsba, and wsm.
Referenced by params().
serialize()
void TsunamiPChip::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 310 of file tsunami_pchip.cc.
References pctl, SERIALIZE_ARRAY, SERIALIZE_SCALAR, tba, wsba, and wsm.
Referenced by params().
unserialize()
void TsunamiPChip::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 319 of file tsunami_pchip.cc.
References pctl, tba, TsunamiPChip(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, wsba, and wsm.
Referenced by params().
write()
Tick TsunamiPChip::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 156 of file tsunami_pchip.cc.
References AddrRange::contains(), DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeAtomicResponse(), panic, pctl, pioDelay, pioRange, AddrRange::start(), tba, TSDEV_PC_PCTL, TSDEV_PC_PERRMASK, TSDEV_PC_PERROR, TSDEV_PC_PERRSET, TSDEV_PC_PLAT, TSDEV_PC_PMONCNT, TSDEV_PC_PMONCTL, TSDEV_PC_RES, TSDEV_PC_TBA0, TSDEV_PC_TBA1, TSDEV_PC_TBA2, TSDEV_PC_TBA3, TSDEV_PC_TLBIA, TSDEV_PC_TLBIV, TSDEV_PC_WSBA0, TSDEV_PC_WSBA1, TSDEV_PC_WSBA2, TSDEV_PC_WSBA3, TSDEV_PC_WSM0, TSDEV_PC_WSM1, TSDEV_PC_WSM2, TSDEV_PC_WSM3, GenericPciHost::write(), wsba, and wsm.
Referenced by params().
Member Data Documentation
pctl
uint64_t TsunamiPChip::pctl protected
Pchip control register.
Definition at line 50 of file tsunami_pchip.hh.
Referenced by read(), serialize(), TsunamiPChip(), unserialize(), and write().
pioDelay
const Tick TsunamiPChip::pioDelay protected
Definition at line 95 of file tsunami_pchip.hh.
Referenced by read(), and write().
pioRange
const AddrRange TsunamiPChip::pioRange protected
Definition at line 94 of file tsunami_pchip.hh.
Referenced by getAddrRanges(), read(), and write().
tba
uint64_t TsunamiPChip::tba[4] protected
Translated Base Addresses.
Definition at line 59 of file tsunami_pchip.hh.
Referenced by dmaAddr(), read(), serialize(), TsunamiPChip(), unserialize(), and write().
wsba
uint64_t TsunamiPChip::wsba[4] protected
Window Base addresses.
Definition at line 53 of file tsunami_pchip.hh.
Referenced by dmaAddr(), read(), serialize(), TsunamiPChip(), unserialize(), and write().
wsm
uint64_t TsunamiPChip::wsm[4] protected
Window masks.
Definition at line 56 of file tsunami_pchip.hh.
Referenced by dmaAddr(), read(), serialize(), TsunamiPChip(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/alpha/tsunami_pchip.hh
dev/alpha/tsunami_pchip.cc