gem5: SparcISA::TlbMap Class Reference
SparcISA::TlbMap Class Reference
#include <tlb_map.hh>
Public Types
typedef RangeMap::iterator iterator
Public Member Functions
iterator find (const TlbRange &r)
bool intersect (const TlbRange &r)
iterator insert (TlbRange &r, TlbEntry *d)
size_t erase (TlbRange k)
void erase (iterator p)
void erase (iterator p, iterator q)
void clear ()
iterator begin ()
iterator end ()
size_t size ()
bool empty ()
void print ()
Private Types
typedef std::map< TlbRange, TlbEntry * > RangeMap
Private Attributes
RangeMap tree
Detailed Description
Definition at line 41 of file tlb_map.hh.
Member Typedef Documentation
iterator
typedef RangeMap::iterator SparcISA::TlbMap::iterator
Definition at line 48 of file tlb_map.hh.
RangeMap
typedef std::map<TlbRange, TlbEntry*> SparcISA::TlbMap::RangeMap private
Definition at line 44 of file tlb_map.hh.
Member Function Documentation
begin()
iterator SparcISA::TlbMap::begin () inline
Definition at line 129 of file tlb_map.hh.
Referenced by SparcISA::TLB::clearUsedBits().
clear()
void SparcISA::TlbMap::clear () inline
Definition at line 123 of file tlb_map.hh.
Referenced by SparcISA::TLB::flushAll(), and SparcISA::TLB::unserialize().
empty()
bool SparcISA::TlbMap::empty () inline
Definition at line 147 of file tlb_map.hh.
end()
iterator SparcISA::TlbMap::end () inline
Definition at line 135 of file tlb_map.hh.
Referenced by SparcISA::TLB::clearUsedBits(), SparcISA::TLB::demapPage(), SparcISA::TLB::insert(), and SparcISA::TLB::lookup().
erase() [1/3]
size_t SparcISA::TlbMap::erase (TlbRange k) inline
Definition at line 105 of file tlb_map.hh.
Referenced by SparcISA::TLB::demapAll(), SparcISA::TLB::demapContext(), SparcISA::TLB::demapPage(), and SparcISA::TLB::insert().
erase() [2/3]
void SparcISA::TlbMap::erase (iterator p) inline
Definition at line 111 of file tlb_map.hh.
erase() [3/3]
void SparcISA::TlbMap::erase (iterator p, iterator q) inline
Definition at line 117 of file tlb_map.hh.
find()
iterator SparcISA::TlbMap::find (const TlbRange & r) inline
Definition at line 51 of file tlb_map.hh.
References SparcISA::TlbRange::contextId, ArmISA::i, SparcISA::TlbRange::partitionId, SparcISA::TlbRange::real, SparcISA::TlbRange::size, and SparcISA::TlbRange::va.
Referenced by SparcISA::TLB::demapPage(), intersect(), and SparcISA::TLB::lookup().
insert()
iterator SparcISA::TlbMap::insert (TlbRange & r, TlbEntry * d) inline
Definition at line 96 of file tlb_map.hh.
References intersect().
Referenced by SparcISA::TLB::insert(), and SparcISA::TLB::unserialize().
intersect()
bool SparcISA::TlbMap::intersect (const TlbRange & r) inline
Definition at line 85 of file tlb_map.hh.
References find(), and ArmISA::i.
Referenced by insert().
print()
void SparcISA::TlbMap::print () inline
Definition at line 153 of file tlb_map.hh.
References ArmISA::i.
size()
size_t SparcISA::TlbMap::size () inline
Definition at line 141 of file tlb_map.hh.
Referenced by SparcISA::TLB::translateData().
Member Data Documentation
tree
RangeMap SparcISA::TlbMap::tree private
Definition at line 45 of file tlb_map.hh.
The documentation for this class was generated from the following file:
arch/sparc/tlb_map.hh