gem5: LSQ< Impl >::LSQSenderState Class Reference
LSQ< Impl >::LSQSenderState Class Reference abstract
Derived class to hold any sender state the LSQ needs.
#include <lsq.hh>
Public Member Functions
ContextID contextId ()
bool isComplete ()
Completes a packet and returns whether the access is finished.
void deleteRequest ()
bool alive ()
LSQRequest * request ()
virtual void complete ()=0
void writebackDone ()
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Public Attributes
DynInstPtr inst
Instruction which initiated the access to memory.
PacketPtr mainPkt
The main packet from a split load, used during writeback.
PacketPtr pendingPacket
A second packet from a split store that needs sending.
uint8_t outstanding
Number of outstanding packets to complete.
bool isLoad
Whether or not it is a load.
bool needWB
Whether or not the instruction will need to writeback.
bool isSplit
Whether or not this access is split in two.
bool pktToSend
Whether or not there is a packet that needs sending.
bool deleted
Has the request been deleted? LSQ entries can be squashed before the response comes back.
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Protected Member Functions
LSQSenderState (LSQRequest *request, bool isLoad_)
Default constructor.
Protected Attributes
LSQRequest * _request
The senderState needs to know the LSQRequest who owns it.
Detailed Description
template<class Impl>
class LSQ< Impl >::LSQSenderState
Derived class to hold any sender state the LSQ needs.
Definition at line 75 of file lsq.hh.
Constructor & Destructor Documentation
LSQSenderState()
template<class Impl> LSQ< Impl >::LSQSenderState::LSQSenderState (LSQRequest * request, bool isLoad_) inline protected
Default constructor.
Definition at line 82 of file lsq.hh.
Member Function Documentation
alive()
template<class Impl> bool LSQ< Impl >::LSQSenderState::alive () inline
Definition at line 115 of file lsq.hh.
References LSQ< Impl >::LSQSenderState::deleted.
complete()
template<class Impl> virtual void LSQ< Impl >::LSQSenderState::complete () pure virtual
Referenced by LSQ< Impl >::LSQSenderState::request().
contextId()
template<class Impl> ContextID LSQ< Impl >::LSQSenderState::contextId () inline
Definition at line 110 of file lsq.hh.
deleteRequest()
template<class Impl> void LSQ< Impl >::LSQSenderState::deleteRequest () inline
Definition at line 114 of file lsq.hh.
Referenced by LSQ< Impl >::LSQRequest::discardSenderState(), and LSQ< Impl >::LSQRequest::release().
isComplete()
template<class Impl> bool LSQ< Impl >::LSQSenderState::isComplete () inline
Completes a packet and returns whether the access is finished.
Definition at line 113 of file lsq.hh.
request()
template<class Impl> LSQRequest* LSQ< Impl >::LSQSenderState::request () inline
Definition at line 116 of file lsq.hh.
References LSQ< Impl >::LSQSenderState::_request, and LSQ< Impl >::LSQSenderState::complete().
Referenced by LSQ< Impl >::LSQRequest::addRequest(), LSQ< Impl >::LSQRequest::getVaddr(), LSQ< Impl >::LSQRequest::mainRequest(), LSQ< Impl >::LSQRequest::setContext(), and LSQ< Impl >::LSQRequest::setVirt().
writebackDone()
template<class Impl> void LSQ< Impl >::LSQSenderState::writebackDone () inline
Definition at line 118 of file lsq.hh.
References LSQ< Impl >::LSQRequest::writebackDone().
Member Data Documentation
_request
template<class Impl> LSQRequest* LSQ< Impl >::LSQSenderState::_request protected
The senderState needs to know the LSQRequest who owns it.
Definition at line 79 of file lsq.hh.
Referenced by LSQ< Impl >::LSQSenderState::request().
deleted
template<class Impl> bool LSQ< Impl >::LSQSenderState::deleted
Has the request been deleted? LSQ entries can be squashed before the response comes back.
in that case the SenderState knows.
Definition at line 109 of file lsq.hh.
Referenced by LSQ< Impl >::LSQSenderState::alive().
inst
template<class Impl> DynInstPtr LSQ< Impl >::LSQSenderState::inst
Instruction which initiated the access to memory.
Definition at line 90 of file lsq.hh.
Referenced by LSQ< Impl >::~LSQ().
isLoad
template<class Impl> bool LSQ< Impl >::LSQSenderState::isLoad
Whether or not it is a load.
Definition at line 98 of file lsq.hh.
Referenced by LSQ< Impl >::dumpInsts(), LSQ< Impl >::LSQRequest::install(), and LSQ< Impl >::LSQRequest::isMemAccessRequired().
isSplit
template<class Impl> bool LSQ< Impl >::LSQSenderState::isSplit
Whether or not this access is split in two.
Definition at line 102 of file lsq.hh.
mainPkt
template<class Impl> PacketPtr LSQ< Impl >::LSQSenderState::mainPkt
The main packet from a split load, used during writeback.
Definition at line 92 of file lsq.hh.
needWB
template<class Impl> bool LSQ< Impl >::LSQSenderState::needWB
Whether or not the instruction will need to writeback.
Definition at line 100 of file lsq.hh.
outstanding
template<class Impl> uint8_t LSQ< Impl >::LSQSenderState::outstanding
Number of outstanding packets to complete.
Definition at line 96 of file lsq.hh.
Referenced by LSQ< Impl >::SingleDataRequest::recvTimingResp(), and LSQ< Impl >::SplitDataRequest::recvTimingResp().
pendingPacket
template<class Impl> PacketPtr LSQ< Impl >::LSQSenderState::pendingPacket
A second packet from a split store that needs sending.
Definition at line 94 of file lsq.hh.
pktToSend
template<class Impl> bool LSQ< Impl >::LSQSenderState::pktToSend
Whether or not there is a packet that needs sending.
Definition at line 104 of file lsq.hh.
The documentation for this class was generated from the following file:
cpu/o3/lsq.hh