gem5: sc_gem5::VcdTraceFile Class Reference
sc_gem5::VcdTraceFile Class Reference
#include <vcd.hh>
Public Member Functions
VcdTraceFile (const std::string &name)
~VcdTraceFile ()
void trace (bool delta) override
template<typename TV >
void addNewTraceVal (const typename TV::TracedType *v, const std::string &name, int width=1)
void addTraceVal (const bool *v, const std::string &name) override
void addTraceVal (const float *v, const std::string &name) override
void addTraceVal (const double *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_logic *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_int_base *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_uint_base *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_signed *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_unsigned *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_bv_base *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_lv_base *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_fxval *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_fxval_fast *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_fxnum *v, const std::string &name) override
void addTraceVal (const sc_dt::sc_fxnum_fast *v, const std::string &name) override
void addTraceVal (const sc_core::sc_event *v, const std::string &name) override
void addTraceVal (const sc_core::sc_time *v, const std::string &name) override
void addTraceVal (const unsigned char *v, const std::string &name, int width) override
void addTraceVal (const char *v, const std::string &name, int width) override
void addTraceVal (const unsigned short *v, const std::string &name, int width) override
void addTraceVal (const short *v, const std::string &name, int width) override
void addTraceVal (const unsigned int *v, const std::string &name, int width) override
void addTraceVal (const int *v, const std::string &name, int width) override
void addTraceVal (const unsigned long *v, const std::string &name, int width) override
void addTraceVal (const long *v, const std::string &name, int width) override
void addTraceVal (const sc_dt::int64 *v, const std::string &name, int width) override
void addTraceVal (const sc_dt::uint64 *v, const std::string &name, int width) override
void addTraceVal (const unsigned int *, const std::string &name, const char **literals) override
void writeComment (const std::string &comment) override
Public Member Functions inherited from sc_gem5::TraceFile
~TraceFile ()
void traceDeltas (bool on)
void set_time_unit (double, ::sc_core::sc_time_unit) override
void finalizeTime ()
Public Member Functions inherited from sc_core::sc_trace_file
virtual ~sc_trace_file ()
virtual void set_time_unit (double, sc_time_unit)=0
Private Member Functions
std::string nextSignalName ()
void initialize ()
Private Attributes
Tick lastPrintedTime
uint64_t deltasAtNow
char _nextName [NextNameChars+1]
bool initialized
std::vector< VcdTraceValBase * > traceVals
VcdTraceScope topScope
Static Private Attributes
static const int NextNameChars = 5
Additional Inherited Members
Protected Member Functions inherited from sc_gem5::TraceFile
TraceFile (const std::string &name)
std::ostream & stream ()
Protected Member Functions inherited from sc_core::sc_trace_file
sc_trace_file ()
Protected Attributes inherited from sc_gem5::TraceFile
OutputStream * _os
uint64_t timeUnitTicks
double timeUnitValue
::sc_core::sc_time_unit timeUnitUnit
bool _traceDeltas
Detailed Description
Definition at line 53 of file vcd.hh.
Constructor & Destructor Documentation
VcdTraceFile()
sc_gem5::VcdTraceFile::VcdTraceFile (const std::string & name) inline
Definition at line 70 of file vcd.hh.
References ArmISA::i.
~VcdTraceFile()
sc_gem5::VcdTraceFile::~VcdTraceFile ()
Definition at line 273 of file vcd.cc.
References ccprintf(), sc_gem5::Scheduler::getCurTick(), and sc_gem5::scheduler.
Member Function Documentation
addNewTraceVal()
template<typename TV > void sc_gem5::VcdTraceFile::addNewTraceVal (const typename TV::TracedType * v, const std::string & name, int width = 1) inline
Definition at line 84 of file vcd.hh.
References sc_gem5::VcdTraceScope::addValue(), name(), ArmISA::v, and ArmISA::width.
addTraceVal() [1/27]
void sc_gem5::VcdTraceFile::addTraceVal (const bool * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 338 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [2/27]
void sc_gem5::VcdTraceFile::addTraceVal (const float * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 359 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [3/27]
void sc_gem5::VcdTraceFile::addTraceVal (const double * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 364 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [4/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_logic * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 386 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [5/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_int_base * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 419 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [6/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_uint_base * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 425 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [7/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_signed * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 432 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [8/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_unsigned * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 437 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [9/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_bv_base * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 464 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [10/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_lv_base * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 469 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [11/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_fxval * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 491 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [12/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_fxval_fast * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 496 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [13/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_fxnum * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 523 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [14/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::sc_fxnum_fast * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 528 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [15/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_core::sc_event * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 552 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [16/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_core::sc_time * v, const std::string & name) override virtual
Implements sc_gem5::TraceFile.
Definition at line 588 of file vcd.cc.
References name(), and ArmISA::v.
addTraceVal() [17/27]
void sc_gem5::VcdTraceFile::addTraceVal (const unsigned char * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 622 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [18/27]
void sc_gem5::VcdTraceFile::addTraceVal (const char * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 628 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [19/27]
void sc_gem5::VcdTraceFile::addTraceVal (const unsigned short * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 633 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [20/27]
void sc_gem5::VcdTraceFile::addTraceVal (const short * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 639 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [21/27]
void sc_gem5::VcdTraceFile::addTraceVal (const unsigned int * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 644 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [22/27]
void sc_gem5::VcdTraceFile::addTraceVal (const int * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 650 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [23/27]
void sc_gem5::VcdTraceFile::addTraceVal (const unsigned long * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 655 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [24/27]
void sc_gem5::VcdTraceFile::addTraceVal (const long * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 661 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [25/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::int64 * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 667 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [26/27]
void sc_gem5::VcdTraceFile::addTraceVal (const sc_dt::uint64 * v, const std::string & name, int width) override virtual
Implements sc_gem5::TraceFile.
Definition at line 673 of file vcd.cc.
References name(), ArmISA::v, and sc_gem5::TraceValBase::width().
addTraceVal() [27/27]
void sc_gem5::VcdTraceFile::addTraceVal (const unsigned int * v, const std::string & name, const char ** literals) override virtual
Implements sc_gem5::TraceFile.
Definition at line 680 of file vcd.cc.
References bits(), X86ISA::count, name(), and ArmISA::v.
initialize()
void sc_gem5::VcdTraceFile::initialize () private
Definition at line 224 of file vcd.cc.
References csprintf(), sc_core::sc_time::from_value(), sc_gem5::Scheduler::getCurTick(), SimClock::Float::s, sc_core::sc_version(), and sc_gem5::scheduler.
nextSignalName()
std::string sc_gem5::VcdTraceFile::nextSignalName () private
Definition at line 206 of file vcd.cc.
References name().
trace()
void sc_gem5::VcdTraceFile::trace (bool delta) override virtual
Implements sc_gem5::TraceFile.
Definition at line 284 of file vcd.cc.
References ccprintf(), sc_gem5::Scheduler::getCurTick(), and sc_gem5::scheduler.
writeComment()
void sc_gem5::VcdTraceFile::writeComment (const std::string & comment) override virtual
Implements sc_gem5::TraceFile.
Definition at line 695 of file vcd.cc.
Member Data Documentation
_nextName
char sc_gem5::VcdTraceFile::_nextName[NextNameChars+1] private
Definition at line 60 of file vcd.hh.
deltasAtNow
uint64_t sc_gem5::VcdTraceFile::deltasAtNow private
Definition at line 57 of file vcd.hh.
initialized
bool sc_gem5::VcdTraceFile::initialized private
Definition at line 63 of file vcd.hh.
lastPrintedTime
Tick sc_gem5::VcdTraceFile::lastPrintedTime private
Definition at line 56 of file vcd.hh.
NextNameChars
const int sc_gem5::VcdTraceFile::NextNameChars = 5 static private
Definition at line 59 of file vcd.hh.
topScope
VcdTraceScope sc_gem5::VcdTraceFile::topScope private
Definition at line 67 of file vcd.hh.
traceVals
std::vector<VcdTraceValBase *> sc_gem5::VcdTraceFile::traceVals private
Definition at line 66 of file vcd.hh.
The documentation for this class was generated from the following files:
systemc/utils/vcd.hh
systemc/utils/vcd.cc