gem5: tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process Class Reference
tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process Class Reference
Classes
struct mm_end_event_ext
class process_handle_class
class process_handle_list
Public Types
typedef sync_enum_type(MODULE::* NBTransportPtr) (int id, transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* BTransportPtr) (int id, transaction_type &, sc_core::sc_time &)
typedef unsigned int(MODULE::* TransportDbgPtr) (int id, transaction_type &)
typedef bool(MODULE::* GetDirectMemPtr) (int id, transaction_type &, tlm::tlm_dmi &)
Public Member Functions
fw_process (simple_target_socket_tagged_b *p_own)
void start_of_simulation ()
void set_nb_transport_user_id (int id)
void set_b_transport_user_id (int id)
void set_transport_dbg_user_id (int id)
void set_get_dmi_user_id (int id)
void set_nb_transport_ptr (MODULE *mod, NBTransportPtr p)
void set_b_transport_ptr (MODULE *mod, BTransportPtr p)
void set_transport_dbg_ptr (MODULE *mod, TransportDbgPtr p)
void set_get_direct_mem_ptr (MODULE *mod, GetDirectMemPtr p)
sync_enum_type nb_transport_fw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void b_transport (transaction_type &trans, sc_core::sc_time &t)
unsigned int transport_dbg (transaction_type &trans)
bool get_direct_mem_ptr (transaction_type &trans, tlm::tlm_dmi &dmi_data)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Public Member Functions inherited from tlm::tlm_mm_interface
virtual ~tlm_mm_interface ()
Private Member Functions
void nb2b_thread (process_handle_class *h)
void b2nb_thread ()
void free (tlm::tlm_generic_payload *trans)
Private Attributes
process_handle_list m_process_handle
simple_target_socket_tagged_b * m_owner
MODULE * m_mod
NBTransportPtr m_nb_transport_ptr
BTransportPtr m_b_transport_ptr
TransportDbgPtr m_transport_dbg_ptr
GetDirectMemPtr m_get_direct_mem_ptr
int m_nb_transport_user_id
int m_b_transport_user_id
int m_transport_dbg_user_id
int m_get_dmi_user_id
peq_with_get< transaction_type > m_peq
bool m_response_in_progress
sc_core::sc_event m_end_response
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process
Definition at line 757 of file simple_target_socket.h.
Member Typedef Documentation
BTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::BTransportPtr) (int id, transaction_type &, sc_core::sc_time &)
Definition at line 764 of file simple_target_socket.h.
GetDirectMemPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef bool(MODULE::* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::GetDirectMemPtr) (int id, transaction_type &, tlm::tlm_dmi &)
Definition at line 768 of file simple_target_socket.h.
NBTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::NBTransportPtr) (int id, transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 761 of file simple_target_socket.h.
TransportDbgPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef unsigned int(MODULE::* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::TransportDbgPtr) (int id, transaction_type &)
Definition at line 766 of file simple_target_socket.h.
Constructor & Destructor Documentation
fw_process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::fw_process (simple_target_socket_tagged_b * p_own) inline
Definition at line 771 of file simple_target_socket.h.
Member Function Documentation
b2nb_thread()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread () inline private
Definition at line 1067 of file simple_target_socket.h.
References tlm::BEGIN_REQ, tlm::BEGIN_RESP, tlm_utils::convenience_socket_base::display_error(), tlm::END_REQ, tlm::END_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_current_transaction, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_end_request, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans, sc_assert, sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, tlm::TLM_UPDATED, and sc_core::wait().
b_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport (transaction_type & trans, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_blocking_transport_if< TYPES::tlm_payload_type >.
Definition at line 906 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_error(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext::done, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans, sc_assert, sc_core::SC_ZERO_TIME, and sc_core::wait().
free()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free (tlm::tlm_generic_payload * trans) inline private virtual
Implements tlm::tlm_mm_interface.
Definition at line 1140 of file simple_target_socket.h.
References tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext::done, ArmISA::ext, sc_core::sc_event::notify(), tlm::tlm_generic_payload::reset(), and sc_assert.
get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::get_direct_mem_ptr (transaction_type & trans, tlm::tlm_dmi & dmi_data) inline virtual
Implements tlm::tlm_fw_direct_mem_if< TYPES::tlm_payload_type >.
Definition at line 963 of file simple_target_socket.h.
References tlm::tlm_dmi::allow_read_write(), sc_assert, tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
nb2b_thread()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread (process_handle_class * h) inline private
Definition at line 1032 of file simple_target_socket.h.
References tlm::BEGIN_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_nb_transport(), tlm::END_RESP, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_suspend, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_trans, sc_assert, sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_COMPLETED, tlm::TLM_UPDATED, and sc_core::wait().
nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_fw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 856 of file simple_target_socket.h.
References tlm::BEGIN_REQ, tlm_utils::convenience_socket_base::display_error(), sc_core::sc_spawn_options::dont_initialize(), tlm::END_RESP, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_class::m_e, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), sc_core::sc_event::notify(), sc_assert, sc_core::sc_bind(), sc_core::sc_gen_unique_name(), sc_core::sc_spawn(), sc_core::sc_spawn_options::set_sensitivity(), ArmISA::t, tlm::TLM_ACCEPTED, and tlm::TLM_COMPLETED.
set_b_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr (MODULE * mod, BTransportPtr p) inline
Definition at line 817 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
set_b_transport_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_user_id (int id) inline
Definition at line 795 of file simple_target_socket.h.
References ArmISA::id.
set_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr (MODULE * mod, GetDirectMemPtr p) inline
Definition at line 843 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
set_get_dmi_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_dmi_user_id (int id) inline
Definition at line 801 of file simple_target_socket.h.
References ArmISA::id.
set_nb_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr (MODULE * mod, NBTransportPtr p) inline
Definition at line 804 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
set_nb_transport_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_user_id (int id) inline
Definition at line 794 of file simple_target_socket.h.
References ArmISA::id.
set_transport_dbg_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr (MODULE * mod, TransportDbgPtr p) inline
Definition at line 830 of file simple_target_socket.h.
References tlm_utils::convenience_socket_base::display_warning(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::m_owner, mod(), MipsISA::p, and sc_assert.
set_transport_dbg_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_user_id (int id) inline
Definition at line 797 of file simple_target_socket.h.
References ArmISA::id.
start_of_simulation()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation () inline
Definition at line 782 of file simple_target_socket.h.
References tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), sc_core::sc_spawn_options::dont_initialize(), sc_core::sc_bind(), sc_core::sc_gen_unique_name(), sc_core::sc_spawn(), and sc_core::sc_spawn_options::set_sensitivity().
transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::transport_dbg (transaction_type & trans) inline virtual
Implements tlm::tlm_transport_dbg_if< TYPES::tlm_payload_type >.
Definition at line 950 of file simple_target_socket.h.
References sc_assert.
Member Data Documentation
m_b_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> BTransportPtr tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_b_transport_ptr private
Definition at line 1163 of file simple_target_socket.h.
m_b_transport_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_b_transport_user_id private
Definition at line 1167 of file simple_target_socket.h.
m_end_response
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sc_core::sc_event tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_end_response private
Definition at line 1172 of file simple_target_socket.h.
m_get_direct_mem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> GetDirectMemPtr tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_get_direct_mem_ptr private
Definition at line 1165 of file simple_target_socket.h.
m_get_dmi_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_get_dmi_user_id private
Definition at line 1169 of file simple_target_socket.h.
m_mod
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> MODULE* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_mod private
Definition at line 1161 of file simple_target_socket.h.
m_nb_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> NBTransportPtr tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_nb_transport_ptr private
Definition at line 1162 of file simple_target_socket.h.
m_nb_transport_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_nb_transport_user_id private
Definition at line 1166 of file simple_target_socket.h.
m_owner
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> simple_target_socket_tagged_b* tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_owner private
Definition at line 1160 of file simple_target_socket.h.
m_peq
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> peq_with_get<transaction_type> tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_peq private
Definition at line 1170 of file simple_target_socket.h.
m_process_handle
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> process_handle_list tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_process_handle private
Definition at line 1029 of file simple_target_socket.h.
m_response_in_progress
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_response_in_progress private
Definition at line 1171 of file simple_target_socket.h.
m_transport_dbg_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> TransportDbgPtr tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_transport_dbg_ptr private
Definition at line 1164 of file simple_target_socket.h.
m_transport_dbg_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::m_transport_dbg_user_id private
Definition at line 1168 of file simple_target_socket.h.
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/simple_target_socket.h