gem5: SystemCounter Class Reference
SystemCounter Class Reference
Global system counter.
#include <generic_timer.hh>
Public Member Functions
SystemCounter ()
uint64_t value () const
Returns the current value of the physical counter.
uint64_t freq () const
Returns the counter frequency.
void setFreq (uint32_t freq)
Sets the counter frequency.
Tick period () const
Returns the counter period.
void setKernelControl (uint32_t val)
uint32_t getKernelControl ()
void setHypControl (uint32_t val)
uint32_t getHypControl ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
uint64_t _freq
Counter frequency (as specified by CNTFRQ).
Tick _period
Cached copy of the counter period (inverse of the frequency).
Tick _resetTick
Tick when the counter was reset.
uint32_t _regCntkctl
Kernel event stream control register.
uint32_t _regCnthctl
Hypervisor event stream control register.
Private Member Functions
SystemCounter (const SystemCounter &c)
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Global system counter.
It is shared by the architected timers.
Todo:
: implement memory-mapped controls
Definition at line 62 of file generic_timer.hh.
Constructor & Destructor Documentation
SystemCounter() [1/2]
SystemCounter::SystemCounter ()
Definition at line 50 of file generic_timer.cc.
References setFreq().
Referenced by getHypControl().
SystemCounter() [2/2]
SystemCounter::SystemCounter (const SystemCounter & c) private
Member Function Documentation
freq()
uint64_t SystemCounter::freq () const inline
Returns the counter frequency.
Definition at line 89 of file generic_timer.hh.
References _freq, and setFreq().
Referenced by GenericTimerMem::ctrlRead(), GenericTimer::readMiscReg(), setFreq(), and GenericTimerMem::timerRead().
getHypControl()
uint32_t SystemCounter::getHypControl () inline
Definition at line 101 of file generic_timer.hh.
References _regCnthctl, ArmISA::c, serialize(), SystemCounter(), and unserialize().
Referenced by GenericTimer::readMiscReg().
getKernelControl()
uint32_t SystemCounter::getKernelControl () inline
Definition at line 98 of file generic_timer.hh.
References _regCntkctl.
Referenced by GenericTimer::readMiscReg().
period()
Tick SystemCounter::period () const inline
Returns the counter period.
Definition at line 95 of file generic_timer.hh.
References _period.
Referenced by ArchTimer::updateCounter().
serialize()
void SystemCounter::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 69 of file generic_timer.cc.
References _freq, _period, _regCnthctl, _regCntkctl, _resetTick, and SERIALIZE_SCALAR.
Referenced by getHypControl(), and ArchTimer::offset().
setFreq()
void SystemCounter::setFreq (uint32_t freq)
Sets the counter frequency.
Parameters
freq frequency in Hz.
Definition at line 57 of file generic_timer.cc.
References _freq, _period, _resetTick, curTick(), freq(), SimClock::Frequency, and warn_once.
Referenced by freq(), GenericTimer::setMiscReg(), and SystemCounter().
setHypControl()
void SystemCounter::setHypControl (uint32_t val) inline
Definition at line 100 of file generic_timer.hh.
References X86ISA::val.
Referenced by GenericTimer::setMiscReg().
setKernelControl()
void SystemCounter::setKernelControl (uint32_t val) inline
Definition at line 97 of file generic_timer.hh.
References X86ISA::val.
Referenced by GenericTimer::setMiscReg().
unserialize()
void SystemCounter::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 79 of file generic_timer.cc.
References _freq, _period, _regCnthctl, _regCntkctl, _resetTick, UNSERIALIZE_OPT_SCALAR, and UNSERIALIZE_SCALAR.
Referenced by getHypControl(), and ArchTimer::offset().
value()
uint64_t SystemCounter::value () const inline
Returns the current value of the physical counter.
Definition at line 81 of file generic_timer.hh.
References _period, and curTick().
Referenced by GenericTimerMem::getAddrRanges(), ArchTimer::offset(), ArchTimer::timerValue(), and ArchTimer::value().
Member Data Documentation
_freq
uint64_t SystemCounter::_freq protected
Counter frequency (as specified by CNTFRQ).
Definition at line 66 of file generic_timer.hh.
Referenced by freq(), serialize(), setFreq(), and unserialize().
_period
Tick SystemCounter::_period protected
Cached copy of the counter period (inverse of the frequency).
Definition at line 68 of file generic_timer.hh.
Referenced by period(), serialize(), setFreq(), unserialize(), and value().
_regCnthctl
uint32_t SystemCounter::_regCnthctl protected
Hypervisor event stream control register.
Definition at line 75 of file generic_timer.hh.
Referenced by getHypControl(), serialize(), and unserialize().
_regCntkctl
uint32_t SystemCounter::_regCntkctl protected
Kernel event stream control register.
Definition at line 73 of file generic_timer.hh.
Referenced by getKernelControl(), serialize(), and unserialize().
_resetTick
Tick SystemCounter::_resetTick protected
Tick when the counter was reset.
Definition at line 70 of file generic_timer.hh.
Referenced by serialize(), setFreq(), and unserialize().
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc