gem5: SimPoint Class Reference
SimPoint Class Reference
#include <simpoint.hh>
Classes
struct BBInfo
Basic Block information.
Public Member Functions
SimPoint (const SimPointParams *params)
virtual ~SimPoint ()
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void regProbeListeners ()
Register probe listeners for this object.
void profile (const std::pair< SimpleThread *, StaticInstPtr > &)
Profile basic blocks for SimPoints.
Public Member Functions inherited from ProbeListenerObject
ProbeListenerObject (const ProbeListenerObjectParams *params)
virtual ~ProbeListenerObject ()
ProbeManager * getProbeManager ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Attributes
const uint64_t intervalSize
SimPoint profiling interval size in instructions.
uint64_t intervalCount
Inst count in current basic block.
uint64_t intervalDrift
Excess inst count from previous interval.
OutputStream * simpointStream
Pointer to SimPoint BBV output stream.
std::unordered_map< BasicBlockRange, BBInfo > bbMap
Hash table containing all previously seen basic blocks.
BasicBlockRange currentBBV
Currently executing basic block.
uint64_t currentBBVInstCount
inst count in current basic block
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from ProbeListenerObject
ProbeManager * manager
std::vector< ProbeListener * > listeners
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 75 of file simpoint.hh.
Constructor & Destructor Documentation
SimPoint()
SimPoint::SimPoint (const SimPointParams * params)
Definition at line 45 of file simpoint.cc.
References OutputDirectory::create(), fatal, simout, and simpointStream.
Referenced by profile().
~SimPoint()
SimPoint::~SimPoint () virtual
Definition at line 59 of file simpoint.cc.
References OutputDirectory::close(), simout, and simpointStream.
Member Function Documentation
init()
void SimPoint::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 65 of file simpoint.cc.
profile()
void SimPoint::profile (const std::pair< SimpleThread *, StaticInstPtr > & p)
Profile basic blocks for SimPoints.
Called at every macro inst to increment basic block inst counts and to profile block if end of block.
Definition at line 78 of file simpoint.cc.
References bbMap, SimPoint::BBInfo::count, currentBBV, currentBBVInstCount, SimPoint::BBInfo::id, SimPoint::BBInfo::insts, intervalCount, intervalDrift, intervalSize, StaticInst::isControl(), StaticInst::isLastMicroop(), StaticInst::isMicroop(), SimpleThread::pcState(), SimPoint(), simpointStream, and OutputStream::stream().
Referenced by regProbeListeners().
regProbeListeners()
void SimPoint::regProbeListeners () virtual
Register probe listeners for this object.
No probe listeners by default, so do nothing in base.
Reimplemented from SimObject.
Definition at line 69 of file simpoint.cc.
References ProbeListenerObject::listeners, and profile().
Member Data Documentation
bbMap
std::unordered_map<BasicBlockRange, BBInfo> SimPoint::bbMap private
Hash table containing all previously seen basic blocks.
Definition at line 114 of file simpoint.hh.
Referenced by profile().
currentBBV
BasicBlockRange SimPoint::currentBBV private
Currently executing basic block.
Definition at line 116 of file simpoint.hh.
Referenced by profile().
currentBBVInstCount
uint64_t SimPoint::currentBBVInstCount private
inst count in current basic block
Definition at line 118 of file simpoint.hh.
Referenced by profile().
intervalCount
uint64_t SimPoint::intervalCount private
Inst count in current basic block.
Definition at line 97 of file simpoint.hh.
Referenced by profile().
intervalDrift
uint64_t SimPoint::intervalDrift private
Excess inst count from previous interval.
Definition at line 99 of file simpoint.hh.
Referenced by profile().
intervalSize
const uint64_t SimPoint::intervalSize private
SimPoint profiling interval size in instructions.
Definition at line 94 of file simpoint.hh.
Referenced by profile().
simpointStream
OutputStream* SimPoint::simpointStream private
Pointer to SimPoint BBV output stream.
Definition at line 101 of file simpoint.hh.
Referenced by profile(), SimPoint(), and ~SimPoint().
The documentation for this class was generated from the following files:
cpu/simple/probes/simpoint.hh
cpu/simple/probes/simpoint.cc