gem5: sc_gem5::TlmToGem5Bridge< BITWIDTH > Class Template Reference
sc_gem5::TlmToGem5Bridge< BITWIDTH > Class Template Reference
#include <tlm_to_gem5.hh>
Classes
class BridgeMasterPort
struct TlmSenderState
Public Types
typedef TlmToGem5BridgeBaseParams Params
Public Member Functions
::Port & gem5_getPort (const std::string &if_name, int idx=-1) override
TlmToGem5Bridge (Params *p, const sc_core::sc_module_name &mn)
tlm_utils::simple_target_socket< TlmToGem5Bridge< BITWIDTH >, BITWIDTH > & getSocket ()
void before_end_of_elaboration () override
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Attributes
const MasterID masterId
Protected Member Functions
void peq_cb (tlm::tlm_generic_payload &trans, const tlm::tlm_phase &phase)
tlm::tlm_sync_enum nb_transport_fw (tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_core::sc_time &t)
void b_transport (tlm::tlm_generic_payload &trans, sc_core::sc_time &t)
unsigned int transport_dbg (tlm::tlm_generic_payload &trans)
bool get_direct_mem_ptr (tlm::tlm_generic_payload &trans, tlm::tlm_dmi &dmi_data)
bool recvTimingResp (PacketPtr pkt)
void recvReqRetry ()
void recvRangeChange ()
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Member Functions
void sendEndReq (tlm::tlm_generic_payload &trans)
void sendBeginResp (tlm::tlm_generic_payload &trans, sc_core::sc_time &delay)
void handleBeginReq (tlm::tlm_generic_payload &trans)
void handleEndResp (tlm::tlm_generic_payload &trans)
void destroyPacket (PacketPtr pkt)
void checkTransaction (tlm::tlm_generic_payload &trans)
void invalidateDmi (const ::MemBackdoor &backdoor)
Private Attributes
tlm_utils::peq_with_cb_and_phase< TlmToGem5Bridge< BITWIDTH > > peq
bool waitForRetry
tlm::tlm_generic_payload * pendingRequest
PacketPtr pendingPacket
bool needToSendRetry
bool responseInProgress
BridgeMasterPort bmp
tlm_utils::simple_target_socket< TlmToGem5Bridge< BITWIDTH >, BITWIDTH > socket
sc_gem5::TlmTargetWrapper< BITWIDTH > wrapper
System * system
Additional Inherited Members
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
template<unsigned int BITWIDTH>
class sc_gem5::TlmToGem5Bridge< BITWIDTH >
Definition at line 86 of file tlm_to_gem5.hh.
Member Typedef Documentation
Params
template<unsigned int BITWIDTH> typedef TlmToGem5BridgeBaseParams sc_gem5::TlmToGem5Bridge< BITWIDTH >::Params
Definition at line 166 of file tlm_to_gem5.hh.
Constructor & Destructor Documentation
TlmToGem5Bridge()
template<unsigned int BITWIDTH> sc_gem5::TlmToGem5Bridge< BITWIDTH >::TlmToGem5Bridge (Params * p, const sc_core::sc_module_name & mn)
Definition at line 468 of file tlm_to_gem5.cc.
Member Function Documentation
b_transport()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport (tlm::tlm_generic_payload & trans, sc_core::sc_time & t) protected
Definition at line 266 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::get_extension(), Gem5SystemC::Gem5Extension::getPacket(), Packet::isResponse(), Packet::needsResponse(), panic_if, sc_gem5::payload2packet(), SimClock::Int::ps, sc_core::SC_PS, tlm::tlm_generic_payload::set_dmi_allowed(), tlm::tlm_generic_payload::set_response_status(), Gem5SystemC::Gem5Extension::setPipeThrough(), and tlm::TLM_OK_RESPONSE.
before_end_of_elaboration()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration () override virtual
Reimplemented from sc_core::sc_module.
Definition at line 483 of file tlm_to_gem5.cc.
References sc_core::sc_module::before_end_of_elaboration(), System::isAtomicMode(), System::isTimingMode(), sc_core::sc_object::name(), panic, SC_REPORT_INFO, sc_gem5::TlmToGem5Bridge< BITWIDTH >::socket, and sc_gem5::TlmToGem5Bridge< BITWIDTH >::system.
checkTransaction()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::checkTransaction (tlm::tlm_generic_payload & trans) private
Definition at line 203 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::get_response_string(), tlm::tlm_generic_payload::is_response_error(), SC_REPORT_ERROR, and ArmISA::ss.
destroyPacket()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::destroyPacket (PacketPtr pkt) private
Definition at line 196 of file tlm_to_gem5.cc.
gem5_getPort()
template<unsigned int BITWIDTH> Port & sc_gem5::TlmToGem5Bridge< BITWIDTH >::gem5_getPort (const std::string & if_name, int idx = -1) override
Definition at line 457 of file tlm_to_gem5.cc.
References sc_core::sc_module::gem5_getPort().
get_direct_mem_ptr()
template<unsigned int BITWIDTH> bool sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr (tlm::tlm_generic_payload & trans, tlm::tlm_dmi & dmi_data) protected
Definition at line 329 of file tlm_to_gem5.cc.
References MemBackdoor::addInvalidationCallback(), tlm::tlm_dmi::DMI_ACCESS_NONE, tlm::tlm_dmi::DMI_ACCESS_READ, tlm::tlm_dmi::DMI_ACCESS_WRITE, AddrRange::end(), tlm::tlm_generic_payload::get_extension(), Gem5SystemC::Gem5Extension::getPacket(), Request::NO_ACCESS, sc_gem5::payload2packet(), MemBackdoor::ptr(), MemBackdoor::range(), MemBackdoor::readable(), Packet::req, tlm::tlm_generic_payload::set_dmi_allowed(), tlm::tlm_dmi::set_dmi_ptr(), tlm::tlm_dmi::set_end_address(), tlm::tlm_dmi::set_granted_access(), tlm::tlm_generic_payload::set_response_status(), tlm::tlm_dmi::set_start_address(), Gem5SystemC::Gem5Extension::setPipeThrough(), AddrRange::start(), tlm::TLM_OK_RESPONSE, and MemBackdoor::writeable().
getSocket()
template<unsigned int BITWIDTH> tlm_utils::simple_target_socket<TlmToGem5Bridge<BITWIDTH>, BITWIDTH>& sc_gem5::TlmToGem5Bridge< BITWIDTH >::getSocket () inline
Definition at line 170 of file tlm_to_gem5.hh.
References sc_core::sc_module::before_end_of_elaboration().
handleBeginReq()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq (tlm::tlm_generic_payload & trans) private
Definition at line 142 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::acquire(), tlm::tlm_generic_payload::get_extension(), Gem5SystemC::Gem5Extension::getPacket(), sc_gem5::payload2packet(), Packet::pushSenderState(), tlm::tlm_generic_payload::release(), sc_assert, and Gem5SystemC::Gem5Extension::setPipeThrough().
handleEndResp()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleEndResp (tlm::tlm_generic_payload & trans) private
Definition at line 180 of file tlm_to_gem5.cc.
References sc_assert.
invalidateDmi()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::invalidateDmi (const ::MemBackdoor & backdoor) private
Definition at line 215 of file tlm_to_gem5.cc.
nb_transport_fw()
template<unsigned int BITWIDTH> tlm::tlm_sync_enum sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw (tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_core::sc_time & t) protected
Definition at line 240 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::acquire(), tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_streaming_width(), ArmISA::len, tlm::tlm_generic_payload::set_response_status(), tlm::TLM_ACCEPTED, tlm::TLM_BURST_ERROR_RESPONSE, tlm::TLM_BYTE_ENABLE_ERROR_RESPONSE, tlm::TLM_COMPLETED, and ArmISA::width.
peq_cb()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::peq_cb (tlm::tlm_generic_payload & trans, const tlm::tlm_phase & phase) protected
Definition at line 223 of file tlm_to_gem5.cc.
References tlm::BEGIN_REQ, tlm::END_RESP, and panic.
recvRangeChange()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvRangeChange () protected
Definition at line 449 of file tlm_to_gem5.cc.
References SC_REPORT_WARNING.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::BridgeMasterPort::recvRangeChange().
recvReqRetry()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvReqRetry () protected
Definition at line 429 of file tlm_to_gem5.cc.
References sc_assert.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::BridgeMasterPort::recvReqRetry().
recvTimingResp()
template<unsigned int BITWIDTH> bool sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp (PacketPtr pkt) protected
Definition at line 381 of file tlm_to_gem5.cc.
References sc_core::sc_time::from_value(), Packet::headerDelay, Gem5SystemC::Gem5Extension::isPipeThrough(), Packet::isResponse(), Packet::payloadDelay, Packet::popSenderState(), and sc_assert.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::BridgeMasterPort::recvTimingResp().
sendBeginResp()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendBeginResp (tlm::tlm_generic_payload & trans, sc_core::sc_time & delay) private
Definition at line 119 of file tlm_to_gem5.cc.
References tlm::BEGIN_RESP, tlm::END_RESP, panic, tlm::tlm_generic_payload::set_response_status(), ArmISA::status, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, tlm::TLM_OK_RESPONSE, and tlm::TLM_UPDATED.
sendEndReq()
template<unsigned int BITWIDTH> void sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendEndReq (tlm::tlm_generic_payload & trans) private
Definition at line 107 of file tlm_to_gem5.cc.
References tlm::END_REQ, panic_if, sc_core::SC_ZERO_TIME, ArmISA::status, and tlm::TLM_ACCEPTED.
transport_dbg()
template<unsigned int BITWIDTH> unsigned int sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg (tlm::tlm_generic_payload & trans) protected
Definition at line 306 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_extension(), Gem5SystemC::Gem5Extension::getPacket(), sc_gem5::payload2packet(), and Gem5SystemC::Gem5Extension::setPipeThrough().
Member Data Documentation
bmp
template<unsigned int BITWIDTH> BridgeMasterPort sc_gem5::TlmToGem5Bridge< BITWIDTH >::bmp private
Definition at line 125 of file tlm_to_gem5.hh.
masterId
template<unsigned int BITWIDTH> const MasterID sc_gem5::TlmToGem5Bridge< BITWIDTH >::masterId
Definition at line 177 of file tlm_to_gem5.hh.
needToSendRetry
template<unsigned int BITWIDTH> bool sc_gem5::TlmToGem5Bridge< BITWIDTH >::needToSendRetry private
Definition at line 121 of file tlm_to_gem5.hh.
pendingPacket
template<unsigned int BITWIDTH> PacketPtr sc_gem5::TlmToGem5Bridge< BITWIDTH >::pendingPacket private
Definition at line 119 of file tlm_to_gem5.hh.
pendingRequest
template<unsigned int BITWIDTH> tlm::tlm_generic_payload* sc_gem5::TlmToGem5Bridge< BITWIDTH >::pendingRequest private
Definition at line 118 of file tlm_to_gem5.hh.
peq
template<unsigned int BITWIDTH> tlm_utils::peq_with_cb_and_phase<TlmToGem5Bridge<BITWIDTH> > sc_gem5::TlmToGem5Bridge< BITWIDTH >::peq private
Definition at line 115 of file tlm_to_gem5.hh.
responseInProgress
template<unsigned int BITWIDTH> bool sc_gem5::TlmToGem5Bridge< BITWIDTH >::responseInProgress private
Definition at line 123 of file tlm_to_gem5.hh.
socket
template<unsigned int BITWIDTH> tlm_utils::simple_target_socket< TlmToGem5Bridge<BITWIDTH>, BITWIDTH> sc_gem5::TlmToGem5Bridge< BITWIDTH >::socket private
Definition at line 127 of file tlm_to_gem5.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration().
system
template<unsigned int BITWIDTH> System* sc_gem5::TlmToGem5Bridge< BITWIDTH >::system private
Definition at line 130 of file tlm_to_gem5.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration().
waitForRetry
template<unsigned int BITWIDTH> bool sc_gem5::TlmToGem5Bridge< BITWIDTH >::waitForRetry private
Definition at line 117 of file tlm_to_gem5.hh.
wrapper
template<unsigned int BITWIDTH> sc_gem5::TlmTargetWrapper<BITWIDTH> sc_gem5::TlmToGem5Bridge< BITWIDTH >::wrapper private
Definition at line 128 of file tlm_to_gem5.hh.
The documentation for this class was generated from the following files:
systemc/tlm_bridge/tlm_to_gem5.hh
systemc/tlm_bridge/tlm_to_gem5.cc