gem5: CxxConfigParams Class Reference
CxxConfigParams Class Reference
Base for peer classes of SimObjectParams derived classes with parameter modifying member functions.
#include <cxx_config.hh>
Public Types
typedef uint32_t FlagsType
Flags passable to setParam...
typedef ::Flags< FlagsType > Flags
Public Member Functions
virtual void setName (const std::string &name_)
Example flag.
virtual const std::string & getName ()
Get full path name string.
virtual bool setSimObject (const std::string &name, SimObject *simObject)
Set a SimObject valued parameter with a reference to the given SimObject.
virtual bool setSimObjectVector (const std::string &name, const std::vector< SimObject *> &simObjects)
As setSimObjectVector but set a whole vector of references.
virtual bool setParam (const std::string &name, const std::string &value, const Flags flags)
Set a parameter with a value parsed from the given string.
virtual bool setParamVector (const std::string &name, const std::vector< std::string > &values, const Flags flags)
As setParamVector but for parameters given as vectors pre-separated into elements.
virtual bool setPortConnectionCount (const std::string &name, unsigned int count)
Set the number of connections expected for the named port.
virtual SimObject * simObjectCreate ()
Create the associated SimObject.
CxxConfigParams ()
virtual ~CxxConfigParams ()
Static Private Attributes
static const std::string invalidName = "<invalid>"
Detailed Description
Base for peer classes of SimObjectParams derived classes with parameter modifying member functions.
C++ configuration will offer objects of these classes to SimObjects as params rather than SimObjectParams objects
Definition at line 125 of file cxx_config.hh.
Member Typedef Documentation
Flags
typedef ::Flags<FlagsType> CxxConfigParams::Flags
Definition at line 134 of file cxx_config.hh.
FlagsType
typedef uint32_t CxxConfigParams::FlagsType
Flags passable to setParam...
to smooth over any parsing difference between different config files
Definition at line 133 of file cxx_config.hh.
Constructor & Destructor Documentation
CxxConfigParams()
CxxConfigParams::CxxConfigParams () inline
Definition at line 181 of file cxx_config.hh.
~CxxConfigParams()
virtual CxxConfigParams::~CxxConfigParams () inline virtual
Definition at line 183 of file cxx_config.hh.
Member Function Documentation
getName()
virtual const std::string& CxxConfigParams::getName () inline virtual
Get full path name string.
Definition at line 144 of file cxx_config.hh.
Referenced by CxxConfigManager::deleteObjects().
setName()
virtual void CxxConfigParams::setName (const std::string & name_) inline virtual
Example flag.
Set future object's full path name
Definition at line 141 of file cxx_config.hh.
Referenced by CxxConfigManager::findObjectParams().
setParam()
virtual bool CxxConfigParams::setParam (const std::string & name, const std::string & value, const Flags flags) inline virtual
Set a parameter with a value parsed from the given string.
The parsing regime matches the format of .ini config files. Returns false if the parameter name is not valid or the string cannot be parsed as the type of the parameter
Definition at line 162 of file cxx_config.hh.
Referenced by CxxConfigManager::findObjectParams(), and CxxConfigManager::setParam().
setParamVector()
virtual bool CxxConfigParams::setParamVector (const std::string & name, const std::vector< std::string > & values, const Flags flags) inline virtual
As setParamVector but for parameters given as vectors pre-separated into elements.
Definition at line 168 of file cxx_config.hh.
Referenced by CxxConfigManager::findObjectParams(), and CxxConfigManager::setParamVector().
setPortConnectionCount()
virtual bool CxxConfigParams::setPortConnectionCount (const std::string & name, unsigned int count) inline virtual
Set the number of connections expected for the named port.
Returns false if the port name is not valid
Definition at line 174 of file cxx_config.hh.
Referenced by CxxConfigManager::findObjectParams().
setSimObject()
virtual bool CxxConfigParams::setSimObject (const std::string & name, SimObject * simObject) inline virtual
Set a SimObject valued parameter with a reference to the given SimObject.
This will return false if the parameter name is not valid or the object is of the wrong type
Definition at line 149 of file cxx_config.hh.
Referenced by CxxConfigManager::findObject(), and CxxConfigManager::findObjectParams().
setSimObjectVector()
virtual bool CxxConfigParams::setSimObjectVector (const std::string & name, const std::vector< SimObject *> & simObjects) inline virtual
As setSimObjectVector but set a whole vector of references.
Definition at line 154 of file cxx_config.hh.
Referenced by CxxConfigManager::findObject(), and CxxConfigManager::findObjectParams().
simObjectCreate()
virtual SimObject* CxxConfigParams::simObjectCreate () inline virtual
Create the associated SimObject.
Definition at line 179 of file cxx_config.hh.
Referenced by CxxConfigManager::findObject().
Member Data Documentation
invalidName
const std::string CxxConfigParams::invalidName = "<invalid>" static private
Definition at line 128 of file cxx_config.hh.
The documentation for this class was generated from the following files:
sim/cxx_config.hh
sim/cxx_config.cc