gem5: MemTest Class Reference
MemTest Class Reference
The MemTest class tests a cache coherent memory system by generating false sharing and verifying the read data against a reference updated on the completion of writes.
#include <memtest.hh>
Classes
class CpuPort
Public Types
typedef MemTestParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MemTest (const Params *p)
void regStats () override
Callback to set stat parameters.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void tick ()
void noRequest ()
void noResponse ()
Addr blockAlign (Addr addr) const
Get the block aligned address.
void completeRequest (PacketPtr pkt, bool functional=false)
Complete a request by checking the response.
bool sendPkt (PacketPtr pkt)
void recvRetry ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
EventFunctionWrapper tickEvent
EventFunctionWrapper noRequestEvent
EventFunctionWrapper noResponseEvent
CpuPort port
PacketPtr retryPkt
const unsigned size
const Cycles interval
const unsigned percentReads
const unsigned percentFunctional
const unsigned percentUncacheable
MasterID masterId
Request id for all generated traffic.
unsigned int id
std::set< Addr > outstandingAddrs
std::unordered_map< Addr, uint8_t > referenceData
const unsigned blockSize
const Addr blockAddrMask
Addr baseAddr1
Addr baseAddr2
Addr uncacheAddr
const unsigned progressInterval
const Cycles progressCheck
Tick nextProgressMessage
uint64_t numReads
uint64_t numWrites
const uint64_t maxLoads
const bool atomic
const bool suppressFuncWarnings
Stats::Scalar numReadsStat
Stats::Scalar numWritesStat
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
The MemTest class tests a cache coherent memory system by generating false sharing and verifying the read data against a reference updated on the completion of writes.
Each tester reads and writes a specific byte in a cache line, as determined by its unique id. Thus, all requests issued by the MemTest instance are a single byte and a specific address is only ever touched by a single tester.
In addition to verifying the data, the tester also has timeouts for both requests and responses, thus checking that the memory-system is making progress.
Definition at line 71 of file memtest.hh.
Member Typedef Documentation
Params
typedef MemTestParams MemTest::Params
Definition at line 76 of file memtest.hh.
Constructor & Destructor Documentation
MemTest()
MemTest::MemTest (const Params * p)
Definition at line 86 of file memtest.cc.
References atomic, baseAddr1, baseAddr2, blockAddrMask, blockSize, Clocked::clockEdge(), curTick(), fatal_if, interval, masterId, maxLoads, SimObject::name(), nextProgressMessage, noRequest(), noRequestEvent, noResponse(), noResponseEvent, numReads, numWrites, MipsISA::p, percentFunctional, percentReads, percentUncacheable, port, progressCheck, progressInterval, retryPkt, EventManager::schedule(), size, suppressFuncWarnings, TESTER_ALLOCATOR, tick(), tickEvent, and uncacheAddr.
Referenced by recvRetry().
Member Function Documentation
blockAlign()
Addr MemTest::blockAlign (Addr addr) const inline protected
Get the block aligned address.
Parameters
addr Address to align
Returns
The block aligned address
Definition at line 153 of file memtest.hh.
Referenced by completeRequest(), and tick().
completeRequest()
void MemTest::completeRequest (PacketPtr pkt, bool functional = false) protected
Complete a request by checking the response.
Parameters
pkt Response packet
functional Whether the access was functional or not
Definition at line 135 of file memtest.cc.
References blockAlign(), ccprintf(), Clocked::clockEdge(), curTick(), EventManager::deschedule(), DPRINTF, exitSimLoop(), Packet::getConstPtr(), Packet::isError(), Packet::isRead(), Packet::isWrite(), maxLoads, SimObject::name(), nextProgressMessage, noResponseEvent, numReads, numReadsStat, numWrites, numWritesStat, outstandingAddrs, panic, progressCheck, progressInterval, referenceData, Packet::req, EventManager::reschedule(), Event::scheduled(), suppressFuncWarnings, and warn.
Referenced by tick().
getPort()
Port & MemTest::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 126 of file memtest.cc.
References SimObject::getPort(), and port.
noRequest()
void MemTest::noRequest () protected
Definition at line 316 of file memtest.cc.
References SimObject::name(), panic, and progressCheck.
Referenced by MemTest().
noResponse()
void MemTest::noResponse () protected
Definition at line 322 of file memtest.cc.
References SimObject::name(), panic, and progressCheck.
Referenced by MemTest().
recvRetry()
void MemTest::recvRetry () protected
Definition at line 328 of file memtest.cc.
References Clocked::clockEdge(), DPRINTF, interval, MemTest(), noRequestEvent, port, progressCheck, EventManager::reschedule(), retryPkt, EventManager::schedule(), MasterPort::sendTimingReq(), and tickEvent.
regStats()
void MemTest::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 200 of file memtest.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numReadsStat, numWritesStat, and Stats::Group::regStats().
sendPkt()
bool MemTest::sendPkt (PacketPtr pkt) protected
Definition at line 73 of file memtest.cc.
References ArmISA::atomic.
Referenced by tick().
tick()
void MemTest::tick () protected
Definition at line 218 of file memtest.cc.
References X86ISA::base, baseAddr1, baseAddr2, blockAlign(), Clocked::clockEdge(), completeRequest(), data, DPRINTF, id, interval, M5_VAR_USED, masterId, SimObject::name(), noRequestEvent, noResponseEvent, ArmISA::offset, outstandingAddrs, panic_if, percentFunctional, percentReads, percentUncacheable, port, progressCheck, Random::random(), random_mt, MemCmd::ReadReq, referenceData, EventManager::reschedule(), retryPkt, EventManager::schedule(), Event::scheduled(), MasterPort::sendFunctional(), sendPkt(), Flags< T >::set(), size, tickEvent, Request::UNCACHEABLE, uncacheAddr, and MemCmd::WriteReq.
Referenced by MemTest().
Member Data Documentation
atomic
const bool MemTest::atomic protected
Definition at line 170 of file memtest.hh.
Referenced by MemTest().
baseAddr1
Addr MemTest::baseAddr1 protected
Definition at line 158 of file memtest.hh.
Referenced by MemTest(), and tick().
baseAddr2
Addr MemTest::baseAddr2 protected
Definition at line 159 of file memtest.hh.
Referenced by MemTest(), and tick().
blockAddrMask
const Addr MemTest::blockAddrMask protected
Definition at line 145 of file memtest.hh.
Referenced by MemTest().
blockSize
const unsigned MemTest::blockSize protected
Definition at line 143 of file memtest.hh.
Referenced by MemTest().
id
unsigned int MemTest::id protected
Definition at line 136 of file memtest.hh.
Referenced by tick().
interval
const Cycles MemTest::interval protected
Definition at line 127 of file memtest.hh.
Referenced by MemTest(), recvRetry(), and tick().
masterId
MasterID MemTest::masterId protected
Request id for all generated traffic.
Definition at line 134 of file memtest.hh.
Referenced by MemTest(), and tick().
maxLoads
const uint64_t MemTest::maxLoads protected
Definition at line 168 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
nextProgressMessage
Tick MemTest::nextProgressMessage protected
Definition at line 164 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
noRequestEvent
EventFunctionWrapper MemTest::noRequestEvent protected
Definition at line 92 of file memtest.hh.
Referenced by MemTest(), recvRetry(), and tick().
noResponseEvent
EventFunctionWrapper MemTest::noResponseEvent protected
Definition at line 96 of file memtest.hh.
Referenced by completeRequest(), MemTest(), and tick().
numReads
uint64_t MemTest::numReads protected
Definition at line 166 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
numReadsStat
Stats::Scalar MemTest::numReadsStat protected
Definition at line 174 of file memtest.hh.
Referenced by completeRequest(), and regStats().
numWrites
uint64_t MemTest::numWrites protected
Definition at line 167 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
numWritesStat
Stats::Scalar MemTest::numWritesStat protected
Definition at line 175 of file memtest.hh.
Referenced by completeRequest(), and regStats().
outstandingAddrs
std::set<Addr> MemTest::outstandingAddrs protected
Definition at line 138 of file memtest.hh.
Referenced by completeRequest(), and tick().
percentFunctional
const unsigned MemTest::percentFunctional protected
Definition at line 130 of file memtest.hh.
Referenced by MemTest(), and tick().
percentReads
const unsigned MemTest::percentReads protected
Definition at line 129 of file memtest.hh.
Referenced by MemTest(), and tick().
percentUncacheable
const unsigned MemTest::percentUncacheable protected
Definition at line 131 of file memtest.hh.
Referenced by MemTest(), and tick().
port
CpuPort MemTest::port protected
Definition at line 121 of file memtest.hh.
Referenced by getPort(), MemTest(), recvRetry(), and tick().
progressCheck
const Cycles MemTest::progressCheck protected
Definition at line 163 of file memtest.hh.
Referenced by completeRequest(), MemTest(), noRequest(), noResponse(), recvRetry(), and tick().
progressInterval
const unsigned MemTest::progressInterval protected
Definition at line 162 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
referenceData
std::unordered_map<Addr, uint8_t> MemTest::referenceData protected
Definition at line 141 of file memtest.hh.
Referenced by completeRequest(), and tick().
retryPkt
PacketPtr MemTest::retryPkt protected
Definition at line 123 of file memtest.hh.
Referenced by MemTest(), recvRetry(), and tick().
size
const unsigned MemTest::size protected
Definition at line 125 of file memtest.hh.
Referenced by MemTest(), and tick().
suppressFuncWarnings
const bool MemTest::suppressFuncWarnings protected
Definition at line 172 of file memtest.hh.
Referenced by completeRequest(), and MemTest().
tickEvent
EventFunctionWrapper MemTest::tickEvent protected
Definition at line 88 of file memtest.hh.
Referenced by MemTest(), recvRetry(), and tick().
uncacheAddr
Addr MemTest::uncacheAddr protected
Definition at line 160 of file memtest.hh.
Referenced by MemTest(), and tick().
The documentation for this class was generated from the following files:
cpu/testers/memtest/memtest.hh
cpu/testers/memtest/memtest.cc