gem5: sc_gem5::UniqueNameGen Class Reference
sc_gem5::UniqueNameGen Class Reference
#include <module.hh>
Public Member Functions
const char * gen (std::string seed)
Private Attributes
std::map< std::string, int > counts
std::string buf
Detailed Description
Definition at line 54 of file module.hh.
Member Function Documentation
gen()
const char* sc_gem5::UniqueNameGen::gen (std::string seed) inline
Definition at line 62 of file module.hh.
References sc_gem5::globalNameGen, and X86ISA::os.
Referenced by sc_gem5::Event::Event(), sc_core::sc_gen_unique_name(), and sc_gem5::Module::uniqueName().
Member Data Documentation
buf
std::string sc_gem5::UniqueNameGen::buf private
Definition at line 58 of file module.hh.
counts
std::map<std::string, int> sc_gem5::UniqueNameGen::counts private
Definition at line 57 of file module.hh.
The documentation for this class was generated from the following file:
systemc/core/module.hh