gem5: StackDistProbe Class Reference
StackDistProbe Class Reference
#include <stack_dist.hh>
Public Member Functions
StackDistProbe (StackDistProbeParams *params)
void regStats () override
Callback to set stat parameters.
Public Member Functions inherited from BaseMemProbe
BaseMemProbe (BaseMemProbeParams *params)
void regProbeListeners () override
Register probe listeners for this object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void handleRequest (const ProbePoints::PacketInfo &pkt_info) override
Callback to analyse intercepted Packets.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const unsigned lineSize
const bool disableLinearHists
const bool disableLogHists
Stats::Histogram readLinearHist
Stats::SparseHistogram readLogHist
Stats::Histogram writeLinearHist
Stats::SparseHistogram writeLogHist
Stats::Scalar infiniteSD
StackDistCalc calc
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 50 of file stack_dist.hh.
Constructor & Destructor Documentation
StackDistProbe()
StackDistProbe::StackDistProbe (StackDistProbeParams * params)
Definition at line 45 of file stack_dist.cc.
References fatal_if.
Referenced by handleRequest().
Member Function Documentation
handleRequest()
void StackDistProbe::handleRequest (const ProbePoints::PacketInfo & pkt_info) override protected virtual
Callback to analyse intercepted Packets.
Implements BaseMemProbe.
Definition at line 99 of file stack_dist.cc.
References ProbePoints::PacketInfo::addr, calc, StackDistCalc::calcStackDistAndUpdate(), ProbePoints::PacketInfo::cmd, disableLinearHists, disableLogHists, floorLog2(), infiniteSD, StackDistCalc::Infinity, MemCmd::isRead(), MemCmd::isWrite(), lineSize, readLinearHist, readLogHist, roundDown(), Stats::DistBase< Derived, Stor >::sample(), Stats::SparseHistBase< Derived, Stor >::sample(), StackDistProbe(), writeLinearHist, and writeLogHist.
regStats()
void StackDistProbe::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 58 of file stack_dist.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), disableLinearHists, disableLogHists, Stats::DataWrap< Derived, InfoProxyType >::flags(), infiniteSD, Stats::Histogram::init(), Stats::SparseHistogram::init(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, MipsISA::p, SimObject::params(), Stats::pdf, readLinearHist, readLogHist, Stats::Group::regStats(), writeLinearHist, and writeLogHist.
Member Data Documentation
calc
StackDistCalc StackDistProbe::calc protected
Definition at line 87 of file stack_dist.hh.
Referenced by handleRequest().
disableLinearHists
const bool StackDistProbe::disableLinearHists protected
Definition at line 65 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
disableLogHists
const bool StackDistProbe::disableLogHists protected
Definition at line 68 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
infiniteSD
Stats::Scalar StackDistProbe::infiniteSD protected
Definition at line 84 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
lineSize
const unsigned StackDistProbe::lineSize protected
Definition at line 62 of file stack_dist.hh.
Referenced by handleRequest().
readLinearHist
Stats::Histogram StackDistProbe::readLinearHist protected
Definition at line 72 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
readLogHist
Stats::SparseHistogram StackDistProbe::readLogHist protected
Definition at line 75 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
writeLinearHist
Stats::Histogram StackDistProbe::writeLinearHist protected
Definition at line 78 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
writeLogHist
Stats::SparseHistogram StackDistProbe::writeLogHist protected
Definition at line 81 of file stack_dist.hh.
Referenced by handleRequest(), and regStats().
The documentation for this class was generated from the following files:
mem/probes/stack_dist.hh
mem/probes/stack_dist.cc