gem5: QoS::MemCtrl Class Reference
QoS::MemCtrl Class Reference
The QoS::MemCtrl is a base class for Memory objects which support QoS - it provides access to a set of QoS scheduling policies.
#include <mem_ctrl.hh>
Classes
struct MemCtrlStats
Public Types
enum BusState { READ, WRITE }
Bus Direction.
Public Types inherited from AbstractMemory
typedef AbstractMemoryParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MemCtrl (const QoSMemCtrlParams *)
QoS Memory base class.
virtual ~MemCtrl ()
void init () override
Initializes this object.
BusState getBusState () const
Gets the current bus state.
BusState getBusStateNext () const
Gets the next bus state.
bool hasMaster (MasterID m_id) const
hasMaster returns true if the selected master(ID) has been registered in the memory controller, which happens if the memory controller has received at least a packet from that master.
uint64_t getReadQueueSize (const uint8_t prio) const
Gets a READ queue size.
uint64_t getWriteQueueSize (const uint8_t prio) const
Gets a WRITE queue size.
uint64_t getTotalReadQueueSize () const
Gets the total combined READ queues size.
uint64_t getTotalWriteQueueSize () const
Gets the total combined WRITE queues size.
Tick getServiceTick (const uint8_t prio) const
Gets the last service tick related to a QoS Priority.
uint8_t numPriorities () const
Gets the total number of priority levels in the QoS memory controller.
Public Member Functions inherited from AbstractMemory
AbstractMemory (const Params *p)
virtual ~AbstractMemory ()
bool isNull () const
See if this is a null memory that should never store data and always return zero.
void setBackingStore (uint8_t *pmem_addr)
Set the host memory backing store to be used by this memory controller.
const std::list< LockedAddr > & getLockedAddrList () const
Get the list of locked addresses to allow checkpointing.
void addLockedAddr (LockedAddr addr)
Add a locked address to allow for checkpointing.
System * system () const
read the system pointer Implemented for completeness with the setter
void system (System *sys)
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
const Params * params () const
AddrRange getAddrRange () const
Get the address range.
uint64_t size () const
Get the memory size.
Addr start () const
Get the start address.
bool isConfReported () const
Should this memory be passed to the kernel and part of the OS physical memory layout.
bool isInAddrMap () const
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
bool isKvmMap () const
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void addMaster (const MasterID m_id)
Initializes dynamically counters and statistics for a given Master.
void logRequest (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries)
Called upon receiving a request or updates statistics and updates queues status.
void logResponse (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries, double delay)
Called upon receiving a response, updates statistics and updates queues status.
template<typename Queues >
uint8_t qosSchedule (std::initializer_list< Queues *> queues_ptr, uint64_t queue_entry_size, const PacketPtr pkt)
Assign priority to a packet by executing the configured QoS policy.
uint8_t schedule (MasterID m_id, uint64_t data)
uint8_t schedule (const PacketPtr pkt)
BusState selectNextBusState ()
Returns next bus direction (READ or WRITE) based on configured policy.
void setCurrentBusState ()
Set current bus direction (READ or WRITE) from next selected one.
void recordTurnaroundStats ()
Record statistics on turnarounds based on busStateNext and busState values.
template<typename Queues >
void escalate (std::initializer_list< Queues *> queues, uint64_t queue_entry_size, MasterID m_id, uint8_t tgt_prio)
Escalates/demotes priority of all packets belonging to the passed master to given priority value.
template<typename Queues >
void escalateQueues (Queues &queues, uint64_t queue_entry_size, MasterID m_id, uint8_t curr_prio, uint8_t tgt_prio)
Escalates/demotes priority of all packets belonging to the passed master to given priority value in a specified cluster of queues (e.g.
Protected Member Functions inherited from AbstractMemory
bool checkLockedAddrList (PacketPtr pkt)
void trackLoadLocked (PacketPtr pkt)
bool writeOK (PacketPtr pkt)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const std::unique_ptr< Policy > policy
QoS Policy, assigns QoS priority to the incoming packets.
const std::unique_ptr< TurnaroundPolicy > turnPolicy
QoS Bus Turnaround Policy: selects the bus direction (READ/WRITE)
const std::unique_ptr< QueuePolicy > queuePolicy
QoS Queue Policy: selects packet among same-priority queue.
const uint8_t _numPriorities
Number of configured QoS priorities.
const bool qosPriorityEscalation
Enables QoS priority escalation.
const bool qosSyncroScheduler
Enables QoS synchronized scheduling invokes the QoS scheduler on all masters, at every packet arrival.
std::unordered_map< MasterID, const std::string > masters
Hash of master ID - master name.
std::unordered_map< MasterID, std::vector< uint64_t > > packetPriorities
Hash of masters - number of packets queued per priority.
std::unordered_map< MasterID, std::unordered_map< uint64_t, std::deque< uint64_t > > > requestTimes
Hash of masters - address of request - queue of times of request.
std::vector< Tick > serviceTick
Vector of QoS priorities/last service time.
std::vector< uint64_t > readQueueSizes
Read request packets queue length in #packets, per QoS priority.
std::vector< uint64_t > writeQueueSizes
Write request packets queue length in #packets, per QoS priority.
uint64_t totalReadQueueSize
Total read request packets queue length in #packets.
uint64_t totalWriteQueueSize
Total write request packets queue length in #packets.
BusState busState
Bus state used to control the read/write switching and drive the scheduling of the next request.
BusState busStateNext
bus state for next request event triggered
QoS::MemCtrl::MemCtrlStats stats
Protected Attributes inherited from AbstractMemory
AddrRange range
uint8_t * pmemAddr
MemBackdoor backdoor
const bool confTableReported
const bool inAddrMap
const bool kvmMap
std::list< LockedAddr > lockedAddrList
System * _system
Pointer to the System object.
AbstractMemory::MemStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
The QoS::MemCtrl is a base class for Memory objects which support QoS - it provides access to a set of QoS scheduling policies.
Definition at line 61 of file mem_ctrl.hh.
Member Enumeration Documentation
BusState
enum QoS::MemCtrl::BusState
Bus Direction.
Enumerator
READ
WRITE
Definition at line 65 of file mem_ctrl.hh.
Constructor & Destructor Documentation
MemCtrl()
QoS::MemCtrl::MemCtrl (const QoSMemCtrlParams * p)
QoS Memory base class.
Parameters
p pointer to QoSMemCtrl parameters
Definition at line 46 of file mem_ctrl.cc.
References _numPriorities, policy, queuePolicy, READ, readQueueSizes, serviceTick, turnPolicy, and writeQueueSizes.
Referenced by setCurrentBusState().
~MemCtrl()
QoS::MemCtrl::~MemCtrl () virtual
Definition at line 78 of file mem_ctrl.cc.
Referenced by setCurrentBusState().
Member Function Documentation
addMaster()
void QoS::MemCtrl::addMaster (const MasterID m_id) protected
Initializes dynamically counters and statistics for a given Master.
Parameters
m_id the master ID
Definition at line 271 of file mem_ctrl.cc.
References AbstractMemory::_system, DPRINTF, System::getMasterName(), hasMaster(), masters, numPriorities(), and packetPriorities.
Referenced by escalate(), and logRequest().
escalate()
template<typename Queues > void QoS::MemCtrl::escalate (std::initializer_list< Queues *> queues, uint64_t queue_entry_size, MasterID m_id, uint8_t tgt_prio) protected
Escalates/demotes priority of all packets belonging to the passed master to given priority value.
Parameters
queues list of pointers to packet queues
queue_entry_size size of an entry in the queue
m_id master whose packets priority will change
tgt_prio target priority value
Definition at line 427 of file mem_ctrl.hh.
References addMaster(), DPRINTF, escalateQueues(), masters, numPriorities(), packetPriorities, ArmISA::q, readQueueSizes, and writeQueueSizes.
Referenced by qosSchedule(), and setCurrentBusState().
escalateQueues()
template<typename Queues > void QoS::MemCtrl::escalateQueues (Queues & queues, uint64_t queue_entry_size, MasterID m_id, uint8_t curr_prio, uint8_t tgt_prio) protected
Escalates/demotes priority of all packets belonging to the passed master to given priority value in a specified cluster of queues (e.g.
read queues or write queues) which is passed as an argument to the function. The curr_prio/tgt_prio parameters are queue selectors in the queue cluster.
Parameters
queues reference to packet queues
queue_entry_size size of an entry in the queue
m_id master whose packets priority will change
curr_prio source queue priority value
tgt_prio target queue priority value
Definition at line 355 of file mem_ctrl.hh.
References divCeil(), DPRINTF, masters, packetPriorities, panic_if, readQueueSizes, and writeQueueSizes.
Referenced by escalate(), and setCurrentBusState().
getBusState()
BusState QoS::MemCtrl::getBusState () const inline
Gets the current bus state.
Returns
current bus state
Definition at line 280 of file mem_ctrl.hh.
References busState.
Referenced by QoS::TurnaroundPolicyIdeal::selectBusState(), and selectNextBusState().
getBusStateNext()
BusState QoS::MemCtrl::getBusStateNext () const inline
Gets the next bus state.
Returns
next bus state
Definition at line 287 of file mem_ctrl.hh.
References busStateNext.
getReadQueueSize()
uint64_t QoS::MemCtrl::getReadQueueSize (const uint8_t prio) const inline
Gets a READ queue size.
Parameters
prio QoS Priority of the queue
Returns
queue size in packets
Definition at line 310 of file mem_ctrl.hh.
Referenced by QoS::TurnaroundPolicyIdeal::selectBusState().
getServiceTick()
Tick QoS::MemCtrl::getServiceTick (const uint8_t prio) const inline
Gets the last service tick related to a QoS Priority.
Parameters
prio QoS Priority
Returns
tick
Definition at line 342 of file mem_ctrl.hh.
getTotalReadQueueSize()
uint64_t QoS::MemCtrl::getTotalReadQueueSize () const inline
Gets the total combined READ queues size.
Returns
total queues size in packets
Definition at line 327 of file mem_ctrl.hh.
References totalReadQueueSize.
Referenced by selectNextBusState().
getTotalWriteQueueSize()
uint64_t QoS::MemCtrl::getTotalWriteQueueSize () const inline
Gets the total combined WRITE queues size.
Returns
total queues size in packets
Definition at line 334 of file mem_ctrl.hh.
References totalWriteQueueSize.
Referenced by selectNextBusState().
getWriteQueueSize()
uint64_t QoS::MemCtrl::getWriteQueueSize (const uint8_t prio) const inline
Gets a WRITE queue size.
Parameters
prio QoS Priority of the queue
Returns
queue size in packets
Definition at line 319 of file mem_ctrl.hh.
Referenced by QoS::TurnaroundPolicyIdeal::selectBusState().
hasMaster()
bool QoS::MemCtrl::hasMaster (MasterID m_id) const inline
hasMaster returns true if the selected master(ID) has been registered in the memory controller, which happens if the memory controller has received at least a packet from that master.
Parameters
m_id master id to lookup
Returns
true if the memory controller has received a packet from the master, false otherwise.
Definition at line 299 of file mem_ctrl.hh.
Referenced by addMaster(), QoS::LrgQueuePolicy::enqueuePacket(), logResponse(), and QoS::LrgQueuePolicy::selectPacket().
init()
void QoS::MemCtrl::init () override virtual
Initializes this object.
Reimplemented from AbstractMemory.
Reimplemented in QoS::MemSinkCtrl.
Definition at line 82 of file mem_ctrl.cc.
References AbstractMemory::init().
Referenced by QoS::MemSinkCtrl::init(), and setCurrentBusState().
logRequest()
void QoS::MemCtrl::logRequest (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries) protected
Called upon receiving a request or updates statistics and updates queues status.
Parameters
dir request direction
m_id master id
qos packet qos value
addr packet address
entries number of entries to record
Definition at line 88 of file mem_ctrl.cc.
References addMaster(), addr, QoS::MemCtrl::MemCtrlStats::avgPriority, QoS::MemCtrl::MemCtrlStats::avgPriorityDistance, curTick(), DPRINTF, ArmISA::i, ArmISA::j, masters, packetPriorities, READ, readQueueSizes, requestTimes, stats, totalReadQueueSize, totalWriteQueueSize, WRITE, and writeQueueSizes.
Referenced by DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), and QoS::MemSinkCtrl::recvTimingReq().
logResponse()
void QoS::MemCtrl::logResponse (BusState dir, MasterID m_id, uint8_t qos, Addr addr, uint64_t entries, double delay) protected
Called upon receiving a response, updates statistics and updates queues status.
Parameters
dir response direction
m_id master id
qos packet qos value
addr packet address
entries number of entries to record
delay response delay
Definition at line 145 of file mem_ctrl.cc.
References curTick(), DPRINTF, hasMaster(), ArmISA::j, masters, packetPriorities, panic_if, QoS::MemCtrl::MemCtrlStats::priorityMaxLatency, QoS::MemCtrl::MemCtrlStats::priorityMinLatency, READ, readQueueSizes, requestTimes, SimClock::Float::s, stats, totalReadQueueSize, totalWriteQueueSize, Stats::VectorBase< Derived, Stor >::value(), WRITE, and writeQueueSizes.
Referenced by QoS::MemSinkCtrl::processNextReqEvent(), and DRAMCtrl::processNextReqEvent().
numPriorities()
uint8_t QoS::MemCtrl::numPriorities () const inline
Gets the total number of priority levels in the QoS memory controller.
Returns
total number of priority levels
Definition at line 350 of file mem_ctrl.hh.
References _numPriorities.
Referenced by addMaster(), DRAMCtrl::doDRAMAccess(), escalate(), QoS::PropFairPolicy::initMaster(), QoS::MemSinkCtrl::MemSinkCtrl(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), qosSchedule(), QoS::MemCtrl::MemCtrlStats::regStats(), and QoS::TurnaroundPolicyIdeal::selectBusState().
qosSchedule()
template<typename Queues > uint8_t QoS::MemCtrl::qosSchedule (std::initializer_list< Queues *> queues_ptr, uint64_t queue_entry_size, const PacketPtr pkt) protected
Assign priority to a packet by executing the configured QoS policy.
Parameters
queues_ptr list of pointers to packet queues
queue_entry_size size in bytes per each packet in the queue
pkt pointer to the Packet
Returns
a QoS priority value
Definition at line 475 of file mem_ctrl.hh.
References AbstractMemory::_system, curTick(), DPRINTF, escalate(), System::getMasterName(), ArmISA::m, Packet::masterId(), masters, numPriorities(), qosPriorityEscalation, qosSyncroScheduler, Packet::qosValue(), schedule(), and serviceTick.
Referenced by QoS::MemSinkCtrl::recvTimingReq(), and DRAMCtrl::recvTimingReq().
recordTurnaroundStats()
void QoS::MemCtrl::recordTurnaroundStats () protected
Record statistics on turnarounds based on busStateNext and busState values.
Definition at line 355 of file mem_ctrl.cc.
References busState, busStateNext, READ, Stats::Group::stats, and WRITE.
Referenced by QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), and setCurrentBusState().
schedule() [1/2]
uint8_t QoS::MemCtrl::schedule (MasterID m_id, uint64_t data) protected
Definition at line 214 of file mem_ctrl.cc.
References DPRINTF, and policy.
Referenced by DRAMCtrl::activateBank(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), DRAMCtrl::drain(), DRAMCtrl::prechargeBank(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), qosSchedule(), QoS::MemSinkCtrl::recvTimingReq(), and schedule().
schedule() [2/2]
uint8_t QoS::MemCtrl::schedule (const PacketPtr pkt) protected
Definition at line 228 of file mem_ctrl.cc.
References DPRINTF, Packet::getSize(), policy, Packet::qosValue(), Packet::req, and schedule().
selectNextBusState()
MemCtrl::BusState QoS::MemCtrl::selectNextBusState () protected
Returns next bus direction (READ or WRITE) based on configured policy.
Definition at line 243 of file mem_ctrl.cc.
References DPRINTF, getBusState(), getTotalReadQueueSize(), getTotalWriteQueueSize(), READ, turnPolicy, and WRITE.
Referenced by QoS::MemSinkCtrl::processNextReqEvent(), and DRAMCtrl::processNextReqEvent().
setCurrentBusState()
void QoS::MemCtrl::setCurrentBusState () inline protected
Set current bus direction (READ or WRITE) from next selected one.
Definition at line 218 of file mem_ctrl.hh.
References busStateNext, escalate(), escalateQueues(), init(), MemCtrl(), recordTurnaroundStats(), and ~MemCtrl().
Referenced by QoS::MemSinkCtrl::processNextReqEvent().
Member Data Documentation
_numPriorities
const uint8_t QoS::MemCtrl::_numPriorities protected
Number of configured QoS priorities.
Definition at line 78 of file mem_ctrl.hh.
Referenced by MemCtrl(), and numPriorities().
busState
BusState QoS::MemCtrl::busState protected
Bus state used to control the read/write switching and drive the scheduling of the next request.
Definition at line 121 of file mem_ctrl.hh.
Referenced by getBusState(), DRAMCtrl::minBankPrep(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), and recordTurnaroundStats().
busStateNext
BusState QoS::MemCtrl::busStateNext protected
bus state for next request event triggered
Definition at line 124 of file mem_ctrl.hh.
Referenced by DRAMCtrl::Rank::forceSelfRefreshExit(), getBusStateNext(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), recordTurnaroundStats(), and setCurrentBusState().
masters
std::unordered_map<MasterID, const std::string> QoS::MemCtrl::masters protected
Hash of master ID - master name.
Definition at line 90 of file mem_ctrl.hh.
Referenced by addMaster(), escalate(), escalateQueues(), logRequest(), logResponse(), and qosSchedule().
packetPriorities
std::unordered_map<MasterID, std::vector<uint64_t> > QoS::MemCtrl::packetPriorities protected
Hash of masters - number of packets queued per priority.
Definition at line 93 of file mem_ctrl.hh.
Referenced by addMaster(), escalate(), escalateQueues(), logRequest(), and logResponse().
policy
const std::unique_ptr<Policy> QoS::MemCtrl::policy protected
QoS Policy, assigns QoS priority to the incoming packets.
Definition at line 69 of file mem_ctrl.hh.
Referenced by MemCtrl(), and schedule().
qosPriorityEscalation
const bool QoS::MemCtrl::qosPriorityEscalation protected
Enables QoS priority escalation.
Definition at line 81 of file mem_ctrl.hh.
Referenced by qosSchedule().
qosSyncroScheduler
const bool QoS::MemCtrl::qosSyncroScheduler protected
Enables QoS synchronized scheduling invokes the QoS scheduler on all masters, at every packet arrival.
Definition at line 87 of file mem_ctrl.hh.
Referenced by qosSchedule().
queuePolicy
const std::unique_ptr<QueuePolicy> QoS::MemCtrl::queuePolicy protected
QoS Queue Policy: selects packet among same-priority queue.
Definition at line 75 of file mem_ctrl.hh.
Referenced by MemCtrl(), QoS::MemSinkCtrl::processNextReqEvent(), and QoS::MemSinkCtrl::recvTimingReq().
readQueueSizes
std::vector<uint64_t> QoS::MemCtrl::readQueueSizes protected
Read request packets queue length in #packets, per QoS priority.
Definition at line 106 of file mem_ctrl.hh.
Referenced by escalate(), escalateQueues(), logRequest(), logResponse(), MemCtrl(), and QoS::MemSinkCtrl::processNextReqEvent().
requestTimes
std::unordered_map<MasterID, std::unordered_map<uint64_t, std::deque<uint64_t> > > QoS::MemCtrl::requestTimes protected
Hash of masters - address of request - queue of times of request.
Definition at line 97 of file mem_ctrl.hh.
Referenced by logRequest(), and logResponse().
serviceTick
std::vector<Tick> QoS::MemCtrl::serviceTick protected
Vector of QoS priorities/last service time.
Refreshed at every qosSchedule call.
Definition at line 103 of file mem_ctrl.hh.
Referenced by MemCtrl(), and qosSchedule().
stats
QoS::MemCtrl::MemCtrlStats QoS::MemCtrl::stats protected
Referenced by logRequest(), and logResponse().
totalReadQueueSize
uint64_t QoS::MemCtrl::totalReadQueueSize protected
Total read request packets queue length in #packets.
Definition at line 112 of file mem_ctrl.hh.
Referenced by DRAMCtrl::addToReadQueue(), QoS::MemSinkCtrl::drain(), DRAMCtrl::drain(), getTotalReadQueueSize(), logRequest(), logResponse(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), QoS::MemSinkCtrl::readQueueFull(), and DRAMCtrl::readQueueFull().
totalWriteQueueSize
uint64_t QoS::MemCtrl::totalWriteQueueSize protected
Total write request packets queue length in #packets.
Definition at line 115 of file mem_ctrl.hh.
Referenced by DRAMCtrl::addToWriteQueue(), QoS::MemSinkCtrl::drain(), DRAMCtrl::drain(), getTotalWriteQueueSize(), logRequest(), logResponse(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), QoS::MemSinkCtrl::writeQueueFull(), and DRAMCtrl::writeQueueFull().
turnPolicy
const std::unique_ptr<TurnaroundPolicy> QoS::MemCtrl::turnPolicy protected
QoS Bus Turnaround Policy: selects the bus direction (READ/WRITE)
Definition at line 72 of file mem_ctrl.hh.
Referenced by MemCtrl(), DRAMCtrl::processNextReqEvent(), and selectNextBusState().
writeQueueSizes
std::vector<uint64_t> QoS::MemCtrl::writeQueueSizes protected
Write request packets queue length in #packets, per QoS priority.
Definition at line 109 of file mem_ctrl.hh.
Referenced by escalate(), escalateQueues(), logRequest(), logResponse(), MemCtrl(), and QoS::MemSinkCtrl::processNextReqEvent().
The documentation for this class was generated from the following files:
mem/qos/mem_ctrl.hh
mem/qos/mem_ctrl.cc