gem5: VIPERCoalescer Class Reference
VIPERCoalescer Class Reference
#include <VIPERCoalescer.hh>
Public Types
typedef VIPERCoalescerParams Params
Public Types inherited from GPUCoalescer
typedef RubyGPUCoalescerParams Params
Public Types inherited from RubyPort
typedef RubyPortParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
VIPERCoalescer (const Params *)
~VIPERCoalescer ()
void wbCallback (Addr address)
void invCallback (Addr address)
RequestStatus makeRequest (PacketPtr pkt)
Public Member Functions inherited from GPUCoalescer
GPUCoalescer (const Params *)
~GPUCoalescer ()
void wakeup ()
void printProgress (std::ostream &out) const
void resetStats ()
Callback to reset stats.
void collateStats ()
void regStats ()
Callback to set stat parameters.
void writeCallback (Addr address, DataBlock &data)
void writeCallback (Addr address, MachineType mach, DataBlock &data)
void writeCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void writeCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
void readCallback (Addr address, DataBlock &data)
void readCallback (Addr address, MachineType mach, DataBlock &data)
void readCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
void readCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void atomicCallback (Addr address, MachineType mach, const DataBlock &data)
void recordCPReadCallBack (MachineID myMachID, MachineID senderMachID)
void recordCPWriteCallBack (MachineID myMachID, MachineID senderMachID)
int outstandingCount () const
bool isDeadlockEventScheduled () const
void descheduleDeadlockEvent ()
bool empty () const
void print (std::ostream &out) const
void checkCoherence (Addr address)
void markRemoved ()
void removeRequest (GPUCoalescerRequest *request)
void evictionCallback (Addr address)
void completeIssue ()
void insertKernel (int wavefront_id, PacketPtr pkt)
void recordRequestType (SequencerRequestType requestType)
Stats::Histogram & getOutstandReqHist ()
Stats::Histogram & getLatencyHist ()
Stats::Histogram & getTypeLatencyHist (uint32_t t)
Stats::Histogram & getMissLatencyHist ()
Stats::Histogram & getMissTypeLatencyHist (uint32_t t)
Stats::Histogram & getMissMachLatencyHist (uint32_t t) const
Stats::Histogram & getMissTypeMachLatencyHist (uint32_t r, uint32_t t) const
Stats::Histogram & getIssueToInitialDelayHist (uint32_t t) const
Stats::Histogram & getInitialToForwardDelayHist (const MachineType t) const
Stats::Histogram & getForwardRequestToFirstResponseHist (const MachineType t) const
Stats::Histogram & getFirstResponseToCompletionDelayHist (const MachineType t) const
Public Member Functions inherited from RubyPort
RubyPort (const Params *p)
virtual ~RubyPort ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void setController (AbstractController *_cntrl)
uint32_t getId ()
DrainState drain () override
Notify an object that it needs to drain its state.
bool isCPUSequencer ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
void invL1 ()
Invalidate L1 cache (Acquire)
void wbL1 ()
Writeback L1 cache (Release)
void invwbL1 ()
Invalidate and Writeback L1 cache (Acquire&Release)
Private Attributes
uint64_t m_outstanding_inv
uint64_t m_outstanding_wb
uint64_t m_max_inv_per_cycle
uint64_t m_max_wb_per_cycle
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from GPUCoalescer
typedef std::unordered_map< Addr, std::vector< RequestDesc > > CoalescingTable
typedef std::unordered_map< Addr, GPUCoalescerRequest * > RequestTable
Protected Member Functions inherited from GPUCoalescer
bool tryCacheAccess (Addr addr, RubyRequestType type, Addr pc, RubyAccessMode access_mode, int size, DataBlock *&data_ptr)
virtual void issueRequest (PacketPtr pkt, RubyRequestType type)
void kernelCallback (int wavfront_id)
void hitCallback (GPUCoalescerRequest *request, MachineType mach, DataBlock &data, bool success, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void recordMissLatency (GPUCoalescerRequest *request, MachineType mach, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool success, bool isRegion)
void completeHitCallback (std::vector< PacketPtr > &mylist, int len)
PacketPtr mapAddrToPkt (Addr address)
RequestStatus getRequestStatus (PacketPtr pkt, RubyRequestType request_type)
bool insertRequest (PacketPtr pkt, RubyRequestType request_type)
bool handleLlsc (Addr address, GPUCoalescerRequest *request)
Protected Member Functions inherited from RubyPort
void trySendRetries ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (Addr address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from GPUCoalescer
EventFunctionWrapper issueEvent
int m_max_outstanding_requests
int m_deadlock_threshold
CacheMemory * m_dataCache_ptr
CacheMemory * m_instCache_ptr
CoalescingTable reqCoalescer
std::vector< Addr > newRequests
RequestTable m_writeRequestTable
RequestTable m_readRequestTable
int m_outstanding_count
bool m_deadlock_check_scheduled
std::unordered_map< int, PacketPtr > kernelEndList
std::vector< int > newKernelEnds
int m_store_waiting_on_load_cycles
int m_store_waiting_on_store_cycles
int m_load_waiting_on_store_cycles
int m_load_waiting_on_load_cycles
bool m_runningGarnetStandalone
EventFunctionWrapper deadlockCheckEvent
bool assumingRfOCoherence
Stats::Scalar GPU_TCPLdHits
Stats::Scalar GPU_TCPLdTransfers
Stats::Scalar GPU_TCCLdHits
Stats::Scalar GPU_LdMiss
Stats::Scalar GPU_TCPStHits
Stats::Scalar GPU_TCPStTransfers
Stats::Scalar GPU_TCCStHits
Stats::Scalar GPU_StMiss
Stats::Scalar CP_TCPLdHits
Stats::Scalar CP_TCPLdTransfers
Stats::Scalar CP_TCCLdHits
Stats::Scalar CP_LdMiss
Stats::Scalar CP_TCPStHits
Stats::Scalar CP_TCPStTransfers
Stats::Scalar CP_TCCStHits
Stats::Scalar CP_StMiss
Stats::Histogram m_outstandReqHist
Histogram for number of outstanding requests per cycle.
Stats::Histogram m_latencyHist
Histogram for holding latency profile of all requests.
std::vector< Stats::Histogram * > m_typeLatencyHist
Stats::Histogram m_missLatencyHist
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_missTypeLatencyHist
std::vector< Stats::Histogram * > m_missMachLatencyHist
Histograms for profiling the latencies for requests that required external messages.
std::vector< std::vector< Stats::Histogram * > > m_missTypeMachLatencyHist
std::vector< Stats::Histogram * > m_IssueToInitialDelayHist
Histograms for recording the breakdown of miss latency.
std::vector< Stats::Histogram * > m_InitialToForwardDelayHist
std::vector< Stats::Histogram * > m_ForwardToFirstResponseDelayHist
std::vector< Stats::Histogram * > m_FirstResponseToCompletionDelayHist
Protected Attributes inherited from RubyPort
RubySystem * m_ruby_system
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
std::vector< MemSlavePort * > slave_ports
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 56 of file VIPERCoalescer.hh.
Member Typedef Documentation
Params
typedef VIPERCoalescerParams VIPERCoalescer::Params
Definition at line 59 of file VIPERCoalescer.hh.
Constructor & Destructor Documentation
VIPERCoalescer()
VIPERCoalescer::VIPERCoalescer (const Params * p)
Definition at line 68 of file VIPERCoalescer.cc.
References m_max_inv_per_cycle, m_max_wb_per_cycle, m_outstanding_inv, and m_outstanding_wb.
~VIPERCoalescer()
VIPERCoalescer::~VIPERCoalescer ()
Definition at line 77 of file VIPERCoalescer.cc.
Member Function Documentation
invCallback()
void VIPERCoalescer::invCallback (Addr address)
Definition at line 186 of file VIPERCoalescer.cc.
References GPUCoalescer::completeIssue(), GPUCoalescer::kernelEndList, m_outstanding_inv, m_outstanding_wb, GPUCoalescer::newKernelEnds, and RubyPort::trySendRetries().
invL1()
void VIPERCoalescer::invL1 () private
Invalidate L1 cache (Acquire)
Definition at line 206 of file VIPERCoalescer.cc.
References addr, Clocked::clockEdge(), Clocked::cyclesToTicks(), DPRINTF, MessageBuffer::enqueue(), CacheMemory::getAddressAtIdx(), CacheMemory::getNumBlocks(), ArmISA::i, RubyPort::m_controller, GPUCoalescer::m_dataCache_ptr, RubyPort::m_mandatory_q_ptr, m_outstanding_inv, and AbstractController::mandatoryQueueLatency().
Referenced by makeRequest().
invwbL1()
void VIPERCoalescer::invwbL1 () private
Invalidate and Writeback L1 cache (Acquire&Release)
Definition at line 268 of file VIPERCoalescer.cc.
References addr, Clocked::clockEdge(), Clocked::cyclesToTicks(), MessageBuffer::enqueue(), CacheMemory::getAddressAtIdx(), CacheMemory::getNumBlocks(), ArmISA::i, RubyPort::m_controller, GPUCoalescer::m_dataCache_ptr, RubyPort::m_mandatory_q_ptr, m_outstanding_inv, m_outstanding_wb, and AbstractController::mandatoryQueueLatency().
Referenced by makeRequest().
makeRequest()
RequestStatus VIPERCoalescer::makeRequest (PacketPtr pkt) virtual
Reimplemented from GPUCoalescer.
Definition at line 91 of file VIPERCoalescer.cc.
References GPUCoalescer::completeIssue(), curTick(), EventManager::deschedule(), DPRINTF, GPUCoalescer::insertKernel(), invL1(), invwbL1(), GPUCoalescer::issueEvent, GPUCoalescer::kernelEndList, m_outstanding_inv, m_outstanding_wb, GPUCoalescer::makeRequest(), GPUCoalescer::newKernelEnds, Packet::req, EventManager::schedule(), Event::scheduled(), and wbL1().
wbCallback()
void VIPERCoalescer::wbCallback (Addr address)
Definition at line 170 of file VIPERCoalescer.cc.
References GPUCoalescer::completeIssue(), GPUCoalescer::kernelEndList, m_outstanding_wb, GPUCoalescer::newKernelEnds, and RubyPort::trySendRetries().
wbL1()
void VIPERCoalescer::wbL1 () private
Writeback L1 cache (Release)
Definition at line 237 of file VIPERCoalescer.cc.
References addr, Clocked::clockEdge(), Clocked::cyclesToTicks(), DPRINTF, MessageBuffer::enqueue(), CacheMemory::getAddressAtIdx(), CacheMemory::getNumBlocks(), ArmISA::i, RubyPort::m_controller, GPUCoalescer::m_dataCache_ptr, RubyPort::m_mandatory_q_ptr, m_outstanding_wb, and AbstractController::mandatoryQueueLatency().
Referenced by makeRequest().
Member Data Documentation
m_max_inv_per_cycle
uint64_t VIPERCoalescer::m_max_inv_per_cycle private
Definition at line 71 of file VIPERCoalescer.hh.
Referenced by VIPERCoalescer().
m_max_wb_per_cycle
uint64_t VIPERCoalescer::m_max_wb_per_cycle private
Definition at line 72 of file VIPERCoalescer.hh.
Referenced by VIPERCoalescer().
m_outstanding_inv
uint64_t VIPERCoalescer::m_outstanding_inv private
Definition at line 69 of file VIPERCoalescer.hh.
Referenced by invCallback(), invL1(), invwbL1(), makeRequest(), and VIPERCoalescer().
m_outstanding_wb
uint64_t VIPERCoalescer::m_outstanding_wb private
Definition at line 70 of file VIPERCoalescer.hh.
Referenced by invCallback(), invwbL1(), makeRequest(), VIPERCoalescer(), wbCallback(), and wbL1().
The documentation for this class was generated from the following files:
mem/ruby/system/VIPERCoalescer.hh
mem/ruby/system/VIPERCoalescer.cc