gem5: sc_dt::sc_uint< W > Class Template Reference
sc_dt::sc_uint< W > Class Template Reference
#include <sc_uint.hh>
Public Member Functions
sc_uint ()
sc_uint (uint_type v)
sc_uint (const sc_uint< W > &a)
sc_uint (const sc_uint_base &a)
sc_uint (const sc_uint_subref_r &a)
template<class T >
sc_uint (const sc_generic_base< T > &a)
sc_uint (const sc_signed &a)
sc_uint (const sc_unsigned &a)
sc_uint (const sc_fxval &a)
sc_uint (const sc_fxval_fast &a)
sc_uint (const sc_fxnum &a)
sc_uint (const sc_fxnum_fast &a)
sc_uint (const sc_bv_base &a)
sc_uint (const sc_lv_base &a)
sc_uint (const char *a)
sc_uint (unsigned long a)
sc_uint (long a)
sc_uint (unsigned int a)
sc_uint (int a)
sc_uint (int64 a)
sc_uint (double a)
sc_uint< W > & operator= (uint_type v)
sc_uint< W > & operator= (const sc_uint_base &a)
sc_uint< W > & operator= (const sc_uint_subref_r &a)
sc_uint< W > & operator= (const sc_uint< W > &a)
template<class T >
sc_uint< W > & operator= (const sc_generic_base< T > &a)
sc_uint< W > & operator= (const sc_signed &a)
sc_uint< W > & operator= (const sc_unsigned &a)
sc_uint< W > & operator= (const sc_fxval &a)
sc_uint< W > & operator= (const sc_fxval_fast &a)
sc_uint< W > & operator= (const sc_fxnum &a)
sc_uint< W > & operator= (const sc_fxnum_fast &a)
sc_uint< W > & operator= (const sc_bv_base &a)
sc_uint< W > & operator= (const sc_lv_base &a)
sc_uint< W > & operator= (const char *a)
sc_uint< W > & operator= (unsigned long a)
sc_uint< W > & operator= (long a)
sc_uint< W > & operator= (unsigned int a)
sc_uint< W > & operator= (int a)
sc_uint< W > & operator= (int64 a)
sc_uint< W > & operator= (double a)
sc_uint< W > & operator+= (uint_type v)
sc_uint< W > & operator-= (uint_type v)
sc_uint< W > & operator*= (uint_type v)
sc_uint< W > & operator/= (uint_type v)
sc_uint< W > & operator%= (uint_type v)
sc_uint< W > & operator&= (uint_type v)
sc_uint< W > & operator|= (uint_type v)
sc_uint< W > & operator^= (uint_type v)
sc_uint< W > & operator<<= (uint_type v)
sc_uint< W > & operator>>= (uint_type v)
sc_uint< W > & operator++ ()
const sc_uint< W > operator++ (int)
sc_uint< W > & operator-- ()
const sc_uint< W > operator-- (int)
Public Member Functions inherited from sc_dt::sc_uint_base
sc_uint_base (int w=sc_length_param().len())
sc_uint_base (uint_type v, int w)
sc_uint_base (const sc_uint_base &a)
sc_uint_base (const sc_uint_subref_r &a)
template<class T >
sc_uint_base (const sc_generic_base< T > &a)
sc_uint_base (const sc_bv_base &v)
sc_uint_base (const sc_lv_base &v)
sc_uint_base (const sc_int_subref_r &v)
sc_uint_base (const sc_signed_subref_r &v)
sc_uint_base (const sc_unsigned_subref_r &v)
sc_uint_base (const sc_signed &a)
sc_uint_base (const sc_unsigned &a)
virtual ~sc_uint_base ()
sc_uint_base & operator= (uint_type v)
sc_uint_base & operator= (const sc_uint_base &a)
sc_uint_base & operator= (const sc_uint_subref_r &a)
template<class T >
sc_uint_base & operator= (const sc_generic_base< T > &a)
sc_uint_base & operator= (const sc_signed &a)
sc_uint_base & operator= (const sc_unsigned &a)
sc_uint_base & operator= (const sc_fxval &a)
sc_uint_base & operator= (const sc_fxval_fast &a)
sc_uint_base & operator= (const sc_fxnum &a)
sc_uint_base & operator= (const sc_fxnum_fast &a)
sc_uint_base & operator= (const sc_bv_base &a)
sc_uint_base & operator= (const sc_lv_base &a)
sc_uint_base & operator= (const char *a)
sc_uint_base & operator= (unsigned long a)
sc_uint_base & operator= (long a)
sc_uint_base & operator= (unsigned int a)
sc_uint_base & operator= (int a)
sc_uint_base & operator= (int64 a)
sc_uint_base & operator= (double a)
sc_uint_base & operator+= (uint_type v)
sc_uint_base & operator-= (uint_type v)
sc_uint_base & operator*= (uint_type v)
sc_uint_base & operator/= (uint_type v)
sc_uint_base & operator%= (uint_type v)
sc_uint_base & operator&= (uint_type v)
sc_uint_base & operator|= (uint_type v)
sc_uint_base & operator^= (uint_type v)
sc_uint_base & operator<<= (uint_type v)
sc_uint_base & operator>>= (uint_type v)
sc_uint_base & operator++ ()
const sc_uint_base operator++ (int)
sc_uint_base & operator-- ()
const sc_uint_base operator-- (int)
sc_uint_bitref & operator[] (int i)
const sc_uint_bitref_r & operator[] (int i) const
sc_uint_bitref & bit (int i)
const sc_uint_bitref_r & bit (int i) const
sc_uint_subref & operator() (int left, int right)
const sc_uint_subref_r & operator() (int left, int right) const
sc_uint_subref & range (int left, int right)
const sc_uint_subref_r & range (int left, int right) const
bool test (int i) const
void set (int i)
void set (int i, bool v)
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
long long_low () const
long long_high () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_uint_base
uint_type m_val
int m_len
int m_ulen
Detailed Description
template<int W>
class sc_dt::sc_uint< W >
Definition at line 72 of file sc_uint.hh.
Constructor & Destructor Documentation
sc_uint() [1/21]
template<int W> sc_dt::sc_uint< W >::sc_uint () inline
Definition at line 90 of file sc_uint.hh.
sc_uint() [2/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (uint_type v) inline
Definition at line 91 of file sc_uint.hh.
sc_uint() [3/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_uint< W > & a) inline
Definition at line 92 of file sc_uint.hh.
sc_uint() [4/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_uint_base & a) inline
Definition at line 93 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [5/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_uint_subref_r & a) inline
Definition at line 97 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [6/21]
template<int W> template<class T > sc_dt::sc_uint< W >::sc_uint (const sc_generic_base< T > & a) inline
Definition at line 102 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [7/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_signed & a) inline
Definition at line 106 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [8/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_unsigned & a) inline
Definition at line 110 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [9/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_fxval & a) inline explicit
Definition at line 114 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [10/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_fxval_fast & a) inline explicit
Definition at line 118 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [11/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_fxnum & a) inline explicit
Definition at line 122 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [12/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_fxnum_fast & a) inline explicit
Definition at line 126 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [13/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_bv_base & a) inline
Definition at line 130 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [14/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const sc_lv_base & a) inline
Definition at line 134 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [15/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (const char * a) inline
Definition at line 138 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [16/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (unsigned long a) inline
Definition at line 142 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [17/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (long a) inline
Definition at line 146 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [18/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (unsigned int a) inline
Definition at line 150 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [19/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (int a) inline
Definition at line 154 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [20/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (int64 a) inline
Definition at line 158 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
sc_uint() [21/21]
template<int W> sc_dt::sc_uint< W >::sc_uint (double a) inline
Definition at line 162 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
Member Function Documentation
operator%=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator%= (uint_type v) inline
Definition at line 316 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator%=().
operator&=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator &= (uint_type v) inline
Definition at line 324 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator&=().
operator*=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator*= (uint_type v) inline
Definition at line 304 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator*=().
operator++() [1/2]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator++ () inline
Definition at line 357 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator++().
operator++() [2/2]
template<int W> const sc_uint<W> sc_dt::sc_uint< W >::operator++ (int) inline
Definition at line 363 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator++().
operator+=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator+= (uint_type v) inline
Definition at line 292 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator+=().
operator--() [1/2]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator-- () inline
Definition at line 368 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator--().
operator--() [2/2]
template<int W> const sc_uint<W> sc_dt::sc_uint< W >::operator-- (int) inline
Definition at line 374 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator--().
operator-=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator-= (uint_type v) inline
Definition at line 298 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator-=().
operator/=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator/= (uint_type v) inline
Definition at line 310 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator/=().
operator<<=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator<<= (uint_type v) inline
Definition at line 343 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator<<=().
operator=() [1/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (uint_type v) inline
Definition at line 169 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [2/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_uint_base & a) inline
Definition at line 175 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [3/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_uint_subref_r & a) inline
Definition at line 181 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [4/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_uint< W > & a) inline
Definition at line 187 of file sc_uint.hh.
References sc_dt::sc_uint_base::m_val.
operator=() [5/20]
template<int W> template<class T > sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_generic_base< T > & a) inline
Definition at line 194 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [6/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_signed & a) inline
Definition at line 200 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [7/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_unsigned & a) inline
Definition at line 206 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [8/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_fxval & a) inline
Definition at line 212 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [9/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_fxval_fast & a) inline
Definition at line 218 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [10/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_fxnum & a) inline
Definition at line 224 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [11/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_fxnum_fast & a) inline
Definition at line 230 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [12/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_bv_base & a) inline
Definition at line 236 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [13/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const sc_lv_base & a) inline
Definition at line 242 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [14/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (const char * a) inline
Definition at line 248 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [15/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (unsigned long a) inline
Definition at line 254 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [16/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (long a) inline
Definition at line 260 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [17/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (unsigned int a) inline
Definition at line 266 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [18/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (int a) inline
Definition at line 272 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [19/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (int64 a) inline
Definition at line 278 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator=() [20/20]
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator= (double a) inline
Definition at line 284 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator=().
operator>>=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator>>= (uint_type v) inline
Definition at line 349 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator>>=().
operator^=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator^= (uint_type v) inline
Definition at line 336 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator^=().
operator|=()
template<int W> sc_uint<W>& sc_dt::sc_uint< W >::operator|= (uint_type v) inline
Definition at line 330 of file sc_uint.hh.
References sc_dt::sc_uint_base::operator|=().
The documentation for this class was generated from the following file:
systemc/ext/dt/int/sc_uint.hh