gem5: ImmOperand< T > Class Template Reference
ImmOperand< T > Class Template Reference
#include <operand.hh>
Public Member Functions
bool init (unsigned opOffset, const BrigObject *obj)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at)
std::string disassemble ()
template<typename OperandType >
OperandType get (Wavefront *w)
template<typename OperandType >
OperandType get (Wavefront *w, int lane)
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Public Attributes
T bits
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Private Attributes
uint16_t kind
Detailed Description
template<typename T>
class ImmOperand< T >
Definition at line 348 of file operand.hh.
Member Function Documentation
disassemble()
template<typename T > std::string ImmOperand< T >::disassemble ()
Definition at line 450 of file operand.hh.
Referenced by HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >::generateDisassembly().
get() [1/2]
template<typename T> template<typename OperandType > OperandType ImmOperand< T >::get (Wavefront * w) inline
Definition at line 361 of file operand.hh.
get() [2/2]
template<typename T> template<typename OperandType > OperandType ImmOperand< T >::get (Wavefront * w, int lane) inline
Definition at line 382 of file operand.hh.
init()
template<typename T > bool ImmOperand< T >::init (unsigned opOffset, const BrigObject * obj)
Definition at line 390 of file operand.hh.
Referenced by HsailISA::BrInstBase< SRegOperand >::BrInstBase(), and HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >::SpecialInst1SrcBase().
init_from_vect()
template<typename T > bool ImmOperand< T >::init_from_vect (unsigned opOffset, const BrigObject * obj, int at)
Definition at line 422 of file operand.hh.
Member Data Documentation
bits
template<typename T> T ImmOperand< T >::bits
Definition at line 353 of file operand.hh.
kind
template<typename T> uint16_t ImmOperand< T >::kind private
Definition at line 351 of file operand.hh.
The documentation for this class was generated from the following file:
arch/hsail/operand.hh