gem5: sc_dt::sc_unsigned_bitref_r Class Reference
sc_dt::sc_unsigned_bitref_r Class Reference
#include <sc_unsigned.hh>
Public Member Functions
virtual ~sc_unsigned_bitref_r ()
sc_unsigned_bitref_r (const sc_unsigned_bitref_r &a)
int length () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
virtual int concat_length (bool *xz_present_p) const
virtual uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_unsigned_bitref_r ()
void initialize (const sc_unsigned *obj_p, int index_)
Protected Attributes
int m_index
sc_unsigned * m_obj_p
Private Member Functions
const sc_unsigned_bitref_r & operator= (const sc_unsigned_bitref_r &)
Friends
class sc_unsigned
Detailed Description
Definition at line 581 of file sc_unsigned.hh.
Constructor & Destructor Documentation
sc_unsigned_bitref_r() [1/2]
sc_dt::sc_unsigned_bitref_r::sc_unsigned_bitref_r () inline protected
Definition at line 587 of file sc_unsigned.hh.
~sc_unsigned_bitref_r()
virtual sc_dt::sc_unsigned_bitref_r::~sc_unsigned_bitref_r () inline virtual
Definition at line 598 of file sc_unsigned.hh.
sc_unsigned_bitref_r() [2/2]
sc_dt::sc_unsigned_bitref_r::sc_unsigned_bitref_r (const sc_unsigned_bitref_r & a) inline
Definition at line 601 of file sc_unsigned.hh.
Member Function Documentation
concat_get_ctrl()
virtual bool sc_dt::sc_unsigned_bitref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 631 of file sc_unsigned.hh.
References BITS_PER_DIGIT.
concat_get_data()
virtual bool sc_dt::sc_unsigned_bitref_r::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 639 of file sc_unsigned.hh.
References BITS_PER_DIGIT.
concat_get_uint64()
virtual uint64 sc_dt::sc_unsigned_bitref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 626 of file sc_unsigned.hh.
concat_length()
virtual int sc_dt::sc_unsigned_bitref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 619 of file sc_unsigned.hh.
initialize()
void sc_dt::sc_unsigned_bitref_r::initialize (const sc_unsigned * obj_p, int index_) inline protected
Definition at line 590 of file sc_unsigned.hh.
Referenced by sc_dt::sc_unsigned::bit(), and sc_dt::sc_unsigned::operator[]().
length()
int sc_dt::sc_unsigned_bitref_r::length () const inline
Definition at line 606 of file sc_unsigned.hh.
References sc_dt::operator~().
operator uint64()
sc_dt::sc_unsigned_bitref_r::operator uint64 () const
Definition at line 48 of file sc_unsigned.cc.
operator!()
bool sc_dt::sc_unsigned_bitref_r::operator! () const
Definition at line 54 of file sc_unsigned.cc.
operator=()
const sc_unsigned_bitref_r& sc_dt::sc_unsigned_bitref_r::operator= (const sc_unsigned_bitref_r &) private
operator~()
bool sc_dt::sc_unsigned_bitref_r::operator~ () const
Definition at line 60 of file sc_unsigned.cc.
print()
void sc_dt::sc_unsigned_bitref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 656 of file sc_unsigned.hh.
References X86ISA::os, and to_bool().
Referenced by sc_dt::operator<<().
to_bool()
bool sc_dt::sc_unsigned_bitref_r::to_bool () const inline
Definition at line 615 of file sc_unsigned.hh.
value()
uint64 sc_dt::sc_unsigned_bitref_r::value () const inline
Definition at line 614 of file sc_unsigned.hh.
Friends And Related Function Documentation
sc_unsigned
friend class sc_unsigned friend
Definition at line 583 of file sc_unsigned.hh.
Member Data Documentation
m_index
int sc_dt::sc_unsigned_bitref_r::m_index protected
Definition at line 659 of file sc_unsigned.hh.
m_obj_p
sc_unsigned* sc_dt::sc_unsigned_bitref_r::m_obj_p protected
Definition at line 660 of file sc_unsigned.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_unsigned.hh
systemc/dt/int/sc_unsigned.cc