gem5: LdsState Class Reference
LdsState Class Reference
#include <lds_state.hh>
Classes
class CuSidePort
CuSidePort is the LDS Port closer to the CU side.
class TickEvent
an event to allow event-driven execution
Public Types
typedef LdsStateParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
LdsState (const Params *params)
the default constructor that works with SWIG
LdsState (const LdsState &)=delete
~LdsState ()
const Params * params () const
bool isRetryResp () const
void setRetryResp (const bool value)
LdsState & operator= (const LdsState &)=delete
int increaseRefCounter (const uint32_t dispatchId, const uint32_t wgId)
use the dynamic wave id to create or just increase the reference count
int decreaseRefCounter (const uint32_t dispatchId, const uint32_t wgId)
decrease the reference count after making sure it is in the list give back this chunk if the ref counter has reached 0
int getRefCounter (const uint32_t dispatchId, const uint32_t wgId) const
return the current reference count for this workgroup id
LdsChunk * reserveSpace (const uint32_t dispatchId, const uint32_t wgId, const uint32_t size)
assign a parent and request this amount of space be set aside for this wgid
bool returnQueuePush (std::pair< Tick, PacketPtr > thePair)
add this to the queue of packets to be returned
Tick earliestReturnTime () const
void setParent (ComputeUnit *x_parent)
set the parent and name based on the parent
ComputeUnit * getParent () const
std::string getName ()
int getBanks () const
ComputeUnit * getComputeUnit () const
int getBankConflictPenalty () const
std::size_t ldsSize (const uint32_t x_wgId)
get the allocated size for this workgroup
AddrRange getAddrRange () const
Port & getPort (const std::string &if_name, PortID idx)
Get a port with a given name and index.
bool canReserve (uint32_t x_size) const
can this much space be reserved for a workgroup?
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool process ()
look for packets to return at this time
GPUDynInstPtr getDynInstr (PacketPtr packet)
bool processPacket (PacketPtr packet)
process an incoming packet, add it to the return queue
unsigned countBankConflicts (PacketPtr packet, unsigned *bankAccesses)
derive the gpu mem packet from the packet and then count the bank conflicts
unsigned countBankConflicts (GPUDynInstPtr gpuDynInst, unsigned *numBankAccesses)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
std::unordered_map< uint32_t, std::unordered_map< uint32_t, int32_t > > refCounter
std::unordered_map< uint32_t, std::unordered_map< uint32_t, LdsChunk > > chunkMap
TickEvent tickEvent
std::queue< std::pair< Tick, PacketPtr > > returnQueue
bool retryResp = false
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
bool releaseSpace (const uint32_t x_dispatchId, const uint32_t x_wgId)
give back the space
Private Attributes
CuSidePort cuPort
ComputeUnit * parent = nullptr
std::string _name
int bytesAllocated = 0
int maximumSize
AddrRange range
int bankConflictPenalty = 0
int banks = 0
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 111 of file lds_state.hh.
Member Typedef Documentation
Params
typedef LdsStateParams LdsState::Params
Definition at line 252 of file lds_state.hh.
Constructor & Destructor Documentation
LdsState() [1/2]
LdsState::LdsState (const Params * params)
the default constructor that works with SWIG
Definition at line 50 of file lds_state.cc.
References fatal_if.
LdsState() [2/2]
LdsState::LdsState (const LdsState &) delete
~LdsState()
LdsState::~LdsState () inline
Definition at line 259 of file lds_state.hh.
Member Function Documentation
canReserve()
bool LdsState::canReserve (uint32_t x_size) const inline
can this much space be reserved for a workgroup?
Definition at line 454 of file lds_state.hh.
Referenced by ComputeUnit::ReadyWorkgroup().
countBankConflicts() [1/2]
unsigned LdsState::countBankConflicts (PacketPtr packet, unsigned * bankAccesses) protected
derive the gpu mem packet from the packet and then count the bank conflicts
Definition at line 97 of file lds_state.cc.
References fatal_if, ComputeUnit::LDSPort::SenderState::getMemInst(), Packet::SenderState::predecessor, and Packet::senderState.
Referenced by processPacket().
countBankConflicts() [2/2]
unsigned LdsState::countBankConflicts (GPUDynInstPtr gpuDynInst, unsigned * numBankAccesses) protected
Definition at line 116 of file lds_state.cc.
References banks, ArmISA::i, ArmISA::j, panic_if, parent, and ComputeUnit::wfSize().
decreaseRefCounter()
int LdsState::decreaseRefCounter (const uint32_t dispatchId, const uint32_t wgId) inline
decrease the reference count after making sure it is in the list give back this chunk if the ref counter has reached 0
Definition at line 303 of file lds_state.hh.
References fatal_if.
earliestReturnTime()
Tick LdsState::earliestReturnTime () const inline
Definition at line 384 of file lds_state.hh.
References curTick().
Referenced by processPacket().
getAddrRange()
AddrRange LdsState::getAddrRange () const inline
Definition at line 434 of file lds_state.hh.
Referenced by LdsState::CuSidePort::getAddrRanges().
getBankConflictPenalty()
int LdsState::getBankConflictPenalty () const inline
Definition at line 419 of file lds_state.hh.
getBanks()
int LdsState::getBanks () const inline
Definition at line 407 of file lds_state.hh.
getComputeUnit()
ComputeUnit* LdsState::getComputeUnit () const inline
Definition at line 413 of file lds_state.hh.
getDynInstr()
GPUDynInstPtr LdsState::getDynInstr (PacketPtr packet) protected
Definition at line 186 of file lds_state.cc.
References ComputeUnit::LDSPort::SenderState::getMemInst(), Packet::senderState, and ArmISA::ss.
Referenced by processPacket().
getName()
std::string LdsState::getName () inline
Definition at line 401 of file lds_state.hh.
getParent()
ComputeUnit* LdsState::getParent () const inline
Definition at line 395 of file lds_state.hh.
getPort()
Port& LdsState::getPort (const std::string & if_name, PortID idx) inline virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 440 of file lds_state.hh.
References fatal.
getRefCounter()
int LdsState::getRefCounter (const uint32_t dispatchId, const uint32_t wgId) const inline
return the current reference count for this workgroup id
Definition at line 325 of file lds_state.hh.
References fatal, and fatal_if.
Referenced by ComputeUnit::getRefCounter().
increaseRefCounter()
int LdsState::increaseRefCounter (const uint32_t dispatchId, const uint32_t wgId) inline
use the dynamic wave id to create or just increase the reference count
Definition at line 290 of file lds_state.hh.
References fatal_if.
Referenced by ComputeUnit::startWavefront().
isRetryResp()
bool LdsState::isRetryResp () const inline
Definition at line 271 of file lds_state.hh.
ldsSize()
std::size_t LdsState::ldsSize (const uint32_t x_wgId) inline
get the allocated size for this workgroup
Definition at line 428 of file lds_state.hh.
operator=()
LdsState& LdsState::operator= (const LdsState &) delete
params()
const Params* LdsState::params () const inline
Definition at line 265 of file lds_state.hh.
process()
bool LdsState::process () protected
look for packets to return at this time
Definition at line 277 of file lds_state.cc.
References Clocked::clockEdge(), cuPort, LdsState::TickEvent::deschedule(), ComputeUnit::LDSPort::SenderState::getMemInst(), Packet::makeTimingResponse(), panic, retryResp, returnQueue, LdsState::TickEvent::schedule(), Event::scheduled(), Packet::senderState, SlavePort::sendTimingResp(), ArmISA::ss, tickEvent, and Event::when().
Referenced by returnQueuePush().
processPacket()
bool LdsState::processPacket (PacketPtr packet) protected
process an incoming packet, add it to the return queue
Definition at line 198 of file lds_state.cc.
References bankConflictPenalty, countBankConflicts(), earliestReturnTime(), getDynInstr(), ComputeUnit::ldsBankAccesses, ComputeUnit::ldsBankConflictDist, ComputeUnit::loadBusLength(), parent, returnQueuePush(), Stats::DistBase< Derived, Stor >::sample(), ComputeUnit::shader, ComputeUnit::storeBusLength(), and Shader::ticks().
releaseSpace()
bool LdsState::releaseSpace (const uint32_t x_dispatchId, const uint32_t x_wgId) inline private
give back the space
Definition at line 464 of file lds_state.hh.
References fatal, fatal_if, and LdsChunk::size().
reserveSpace()
LdsChunk* LdsState::reserveSpace (const uint32_t dispatchId, const uint32_t wgId, const uint32_t size) inline
assign a parent and request this amount of space be set aside for this wgid
Definition at line 358 of file lds_state.hh.
References fatal_if, LdsChunk::LdsChunk(), and LdsChunk::size().
Referenced by ComputeUnit::StartWorkgroup().
returnQueuePush()
bool LdsState::returnQueuePush (std::pair< Tick, PacketPtr > thePair)
add this to the queue of packets to be returned
Definition at line 229 of file lds_state.cc.
References process(), returnQueue, Event::scheduled(), and tickEvent.
Referenced by processPacket().
setParent()
void LdsState::setParent (ComputeUnit * x_parent)
set the parent and name based on the parent
Definition at line 82 of file lds_state.cc.
References _name, fatal_if, SimObject::name(), and parent.
Referenced by ComputeUnit::ComputeUnit().
setRetryResp()
void LdsState::setRetryResp (const bool value) inline
Definition at line 277 of file lds_state.hh.
Member Data Documentation
_name
std::string LdsState::_name private
Definition at line 491 of file lds_state.hh.
Referenced by setParent().
bankConflictPenalty
int LdsState::bankConflictPenalty = 0 private
Definition at line 503 of file lds_state.hh.
Referenced by processPacket().
banks
int LdsState::banks = 0 private
Definition at line 506 of file lds_state.hh.
Referenced by countBankConflicts().
bytesAllocated
int LdsState::bytesAllocated = 0 private
Definition at line 494 of file lds_state.hh.
chunkMap
std::unordered_map<uint32_t, std::unordered_map<uint32_t, LdsChunk> > LdsState::chunkMap protected
Definition at line 222 of file lds_state.hh.
cuPort
CuSidePort LdsState::cuPort private
Definition at line 487 of file lds_state.hh.
Referenced by process().
maximumSize
int LdsState::maximumSize private
Definition at line 497 of file lds_state.hh.
parent
ComputeUnit* LdsState::parent = nullptr private
Definition at line 489 of file lds_state.hh.
Referenced by countBankConflicts(), processPacket(), and setParent().
range
AddrRange LdsState::range private
Definition at line 500 of file lds_state.hh.
refCounter
std::unordered_map<uint32_t, std::unordered_map<uint32_t, int32_t> > LdsState::refCounter protected
Definition at line 218 of file lds_state.hh.
retryResp
bool LdsState::retryResp = false protected
Definition at line 233 of file lds_state.hh.
Referenced by process().
returnQueue
std::queue<std::pair<Tick, PacketPtr> > LdsState::returnQueue protected
Definition at line 230 of file lds_state.hh.
Referenced by process(), and returnQueuePush().
tickEvent
TickEvent LdsState::tickEvent protected
Definition at line 225 of file lds_state.hh.
Referenced by process(), and returnQueuePush().
The documentation for this class was generated from the following files:
gpu-compute/lds_state.hh
gpu-compute/lds_state.cc