gem5: Stats::AvgStor Class Reference
Stats::AvgStor Class Reference
Templatized storage and interface to a per-tick average stat.
#include <statistics.hh>
Classes
struct Params
Public Member Functions
AvgStor (Info *info)
Build and initializes this stat storage.
void set (Counter val)
Set the current count to the one provided, update the total and last set values.
void inc (Counter val)
Increment the current count by the provided value, calls set.
void dec (Counter val)
Deccrement the current count by the provided value, calls set.
Counter value () const
Return the current count.
Result result () const
Return the current average.
bool zero () const
void prepare (Info *info)
Prepare stat data for dumping or serialization.
void reset (Info *info)
Reset stat value to default.
Private Attributes
Counter current
The current count.
Tick lastReset
The tick of the last reset.
Result total
The total count for all tick.
Tick last
The tick that current last changed.
Detailed Description
Templatized storage and interface to a per-tick average stat.
This keeps a current count and updates a total (count * ticks) when this count changes. This allows the quick calculation of a per tick count of the item being watched. This is good for keeping track of residencies in structures among other things.
Definition at line 559 of file statistics.hh.
Constructor & Destructor Documentation
AvgStor()
Stats::AvgStor::AvgStor (Info * info) inline
Build and initializes this stat storage.
Definition at line 578 of file statistics.hh.
Member Function Documentation
dec()
void Stats::AvgStor::dec (Counter val) inline
Deccrement the current count by the provided value, calls set.
Parameters
val The amount to decrement.
Definition at line 605 of file statistics.hh.
References X86ISA::val.
inc()
void Stats::AvgStor::inc (Counter val) inline
Increment the current count by the provided value, calls set.
Parameters
val The amount to increment.
Definition at line 599 of file statistics.hh.
References X86ISA::val.
prepare()
void Stats::AvgStor::prepare (Info * info) inline
Prepare stat data for dumping or serialization.
Definition at line 633 of file statistics.hh.
References curTick().
reset()
void Stats::AvgStor::reset (Info * info) inline
Reset stat value to default.
Definition at line 643 of file statistics.hh.
References curTick().
result()
Result Stats::AvgStor::result () const inline
Return the current average.
Returns
The current average.
Definition at line 618 of file statistics.hh.
References curTick().
set()
void Stats::AvgStor::set (Counter val) inline
Set the current count to the one provided, update the total and last set values.
Parameters
val The new count.
Definition at line 588 of file statistics.hh.
References curTick(), and X86ISA::val.
value()
Counter Stats::AvgStor::value () const inline
Return the current count.
Returns
The current count.
Definition at line 611 of file statistics.hh.
zero()
bool Stats::AvgStor::zero () const inline
Returns
true if zero value
Definition at line 627 of file statistics.hh.
Member Data Documentation
current
Counter Stats::AvgStor::current private
The current count.
Definition at line 563 of file statistics.hh.
last
Tick Stats::AvgStor::last mutable private
The tick that current last changed.
Definition at line 569 of file statistics.hh.
lastReset
Tick Stats::AvgStor::lastReset private
The tick of the last reset.
Definition at line 565 of file statistics.hh.
total
Result Stats::AvgStor::total mutable private
The total count for all tick.
Definition at line 567 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh