gem5: FetchUnit Class Reference
FetchUnit Class Reference
#include <fetch_unit.hh>
Public Member Functions
FetchUnit (const ComputeUnitParams *params)
~FetchUnit ()
void init (ComputeUnit *cu)
void exec ()
void bindWaveList (std::vector< Wavefront *> *list)
void initiateFetch (Wavefront *wavefront)
void fetch (PacketPtr pkt, Wavefront *wavefront)
void processFetchReturn (PacketPtr pkt)
Static Public Attributes
static uint32_t globalFetchUnitID
Private Attributes
bool timingSim
ComputeUnit * computeUnit
TheGpuISA::Decoder decoder
Scheduler fetchScheduler
std::vector< Wavefront * > fetchQueue
std::vector< std::pair< Wavefront *, bool > > fetchStatusQueue
std::vector< Wavefront * > * waveList
Detailed Description
Definition at line 54 of file fetch_unit.hh.
Constructor & Destructor Documentation
FetchUnit()
FetchUnit::FetchUnit (const ComputeUnitParams * params)
Definition at line 52 of file fetch_unit.cc.
~FetchUnit()
FetchUnit::~FetchUnit ()
Definition at line 60 of file fetch_unit.cc.
References fetchQueue, and fetchStatusQueue.
Member Function Documentation
bindWaveList()
void FetchUnit::bindWaveList (std::vector< Wavefront *> * list)
Definition at line 314 of file fetch_unit.cc.
References waveList.
exec()
void FetchUnit::exec ()
Definition at line 82 of file fetch_unit.cc.
References Scheduler::chooseWave(), computeUnit, fetchQueue, fetchScheduler, fetchStatusQueue, initiateFetch(), Wavefront::instructionBuffer, Wavefront::instructionBufferHasBranch(), ArmISA::j, Shader::n_wf, Wavefront::pendingFetch, Wavefront::S_RUNNING, ComputeUnit::shader, Wavefront::status, and Wavefront::wfSlotId.
fetch()
void FetchUnit::fetch (PacketPtr pkt, Wavefront * wavefront)
Definition at line 208 of file fetch_unit.cc.
References computeUnit, ComputeUnit::cu_id, data, Packet::dataDynamic(), DPRINTF, processFetchReturn(), Packet::req, ComputeUnit::SQCPort::retries, Packet::senderState, MasterPort::sendFunctional(), MasterPort::sendTimingReq(), Wavefront::simdId, ComputeUnit::sqcPort, timingSim, and Wavefront::wfSlotId.
Referenced by initiateFetch().
init()
void FetchUnit::init (ComputeUnit * cu)
Definition at line 67 of file fetch_unit.cc.
References Scheduler::bindList(), computeUnit, fetchQueue, fetchScheduler, fetchStatusQueue, ArmISA::j, Shader::n_wf, ComputeUnit::shader, timingSim, Shader::timingSim, and waveList.
initiateFetch()
void FetchUnit::initiateFetch (Wavefront * wavefront)
the instruction buffer holds one instruction per entry, regardless of the underlying instruction's size. the PC, however, addresses instrutions on a 32b granularity so we must account for that here.
Definition at line 116 of file fetch_unit.cc.
References Wavefront::basePtr, ComputeUnit::cacheLineSize(), computeUnit, ComputeUnit::cu_id, DPRINTF, BaseTLB::Execute, fetch(), Shader::gpuTc, ArmISA::i, Request::INST_FETCH, Wavefront::instructionBuffer, ComputeUnit::ITLBPort::isStalled(), ComputeUnit::masterId(), Wavefront::pc(), MemCmd::ReadReq, ComputeUnit::ITLBPort::retries, roundDown(), safe_cast(), MasterPort::sendFunctional(), MasterPort::sendTimingReq(), ComputeUnit::shader, Wavefront::simdId, ComputeUnit::sqcTLBPort, ComputeUnit::ITLBPort::stallPort(), timingSim, MipsISA::vaddr, and Wavefront::wfSlotId.
Referenced by exec().
processFetchReturn()
void FetchUnit::processFetchReturn (PacketPtr pkt)
this instruction occupies 2 consecutive entries in the instruction array, the second of which contains a nullptr. so if this inst is 8 bytes we advance two entries instead of 1
Definition at line 256 of file fetch_unit.cc.
References computeUnit, ComputeUnit::cu_id, decoder, GPUStaticInst::disassemble(), DPRINTF, Packet::getPtr(), ArmISA::i, GPUStaticInst::instSize(), Packet::req, safe_cast(), Packet::senderState, and ComputeUnit::SQCPort::SenderState::wavefront.
Referenced by fetch().
Member Data Documentation
computeUnit
ComputeUnit* FetchUnit::computeUnit private
Definition at line 69 of file fetch_unit.hh.
Referenced by exec(), fetch(), init(), initiateFetch(), and processFetchReturn().
decoder
TheGpuISA::Decoder FetchUnit::decoder private
Definition at line 70 of file fetch_unit.hh.
Referenced by processFetchReturn().
fetchQueue
std::vector<Wavefront*> FetchUnit::fetchQueue private
Definition at line 80 of file fetch_unit.hh.
Referenced by exec(), init(), and ~FetchUnit().
fetchScheduler
Scheduler FetchUnit::fetchScheduler private
Definition at line 76 of file fetch_unit.hh.
Referenced by exec(), and init().
fetchStatusQueue
std::vector<std::pair<Wavefront*, bool> > FetchUnit::fetchStatusQueue private
Definition at line 85 of file fetch_unit.hh.
Referenced by exec(), init(), and ~FetchUnit().
globalFetchUnitID
uint32_t FetchUnit::globalFetchUnitID static
Definition at line 65 of file fetch_unit.hh.
timingSim
bool FetchUnit::timingSim private
Definition at line 68 of file fetch_unit.hh.
Referenced by fetch(), init(), and initiateFetch().
waveList
std::vector<Wavefront*>* FetchUnit::waveList private
Definition at line 88 of file fetch_unit.hh.
Referenced by bindWaveList(), and init().
The documentation for this class was generated from the following files:
gpu-compute/fetch_unit.hh
gpu-compute/fetch_unit.cc