gem5: TraceCPU::ElasticDataGen::HardwareResource Class Reference
TraceCPU::ElasticDataGen::HardwareResource Class Reference
The HardwareResource class models structures that hold the in-flight nodes.
Public Member Functions
HardwareResource (uint16_t max_rob, uint16_t max_stores, uint16_t max_loads)
Constructor that initializes the sizes of the structures.
void occupy (const GraphNode *new_node)
Occupy appropriate structures for an issued node.
void release (const GraphNode *done_node)
Release appropriate structures for a completed node.
void releaseStoreBuffer ()
Release store buffer entry for a completed store.
bool isAvailable (const GraphNode *new_node) const
Check if structures required to issue a node are free.
bool awaitingResponse () const
Check if there are any outstanding requests, i.e.
void printOccupancy ()
Print resource occupancy for debugging.
Private Attributes
const uint16_t sizeROB
The size of the ROB used to throttle the max.
const uint16_t sizeStoreBuffer
The size of store buffer.
const uint16_t sizeLoadBuffer
The size of load buffer.
std::map< NodeSeqNum, NodeRobNum > inFlightNodes
A map from the sequence number to the ROB number of the in- flight nodes.
NodeRobNum oldestInFlightRobNum
The ROB number of the oldest in-flight node.
uint16_t numInFlightLoads
Number of ready loads for which request may or may not be sent.
uint16_t numInFlightStores
Number of ready stores for which request may or may not be sent.
Detailed Description
The HardwareResource class models structures that hold the in-flight nodes.
When a node becomes dependency free, first check if resources are available to issue it.
Definition at line 699 of file trace_cpu.hh.
Constructor & Destructor Documentation
HardwareResource()
TraceCPU::ElasticDataGen::HardwareResource::HardwareResource (uint16_t max_rob, uint16_t max_stores, uint16_t max_loads)
Constructor that initializes the sizes of the structures.
Parameters
max_rob size of the Reorder Buffer
max_stores size of Store Buffer
max_loads size of Load Buffer
Definition at line 880 of file trace_cpu.cc.
Member Function Documentation
awaitingResponse()
bool TraceCPU::ElasticDataGen::HardwareResource::awaitingResponse () const
Check if there are any outstanding requests, i.e.
requests for which we are yet to receive a response.
Returns
true if there is at least one read or write request outstanding
Definition at line 1002 of file trace_cpu.cc.
References numInFlightLoads, and numInFlightStores.
isAvailable()
bool TraceCPU::ElasticDataGen::HardwareResource::isAvailable (const GraphNode * new_node) const
Check if structures required to issue a node are free.
Parameters
node_ptr pointer to the node ready to issue
Returns
true if resources are available
Definition at line 958 of file trace_cpu.cc.
References DPRINTFR, inFlightNodes, TraceCPU::ElasticDataGen::GraphNode::isLoad(), TraceCPU::ElasticDataGen::GraphNode::isStore(), numInFlightLoads, numInFlightStores, oldestInFlightRobNum, TraceCPU::ElasticDataGen::GraphNode::robNum, TraceCPU::ElasticDataGen::GraphNode::seqNum, sizeLoadBuffer, sizeROB, and sizeStoreBuffer.
occupy()
void TraceCPU::ElasticDataGen::HardwareResource::occupy (const GraphNode * new_node)
Occupy appropriate structures for an issued node.
Parameters
node_ptr pointer to the issued node
Definition at line 891 of file trace_cpu.cc.
References inFlightNodes, TraceCPU::ElasticDataGen::GraphNode::isLoad(), TraceCPU::ElasticDataGen::GraphNode::isStore(), numInFlightLoads, numInFlightStores, oldestInFlightRobNum, printOccupancy(), TraceCPU::ElasticDataGen::GraphNode::robNum, and TraceCPU::ElasticDataGen::GraphNode::seqNum.
printOccupancy()
void TraceCPU::ElasticDataGen::HardwareResource::printOccupancy ()
Print resource occupancy for debugging.
Definition at line 1008 of file trace_cpu.cc.
References DPRINTFR, numInFlightLoads, numInFlightStores, oldestInFlightRobNum, sizeLoadBuffer, and sizeStoreBuffer.
Referenced by occupy().
release()
void TraceCPU::ElasticDataGen::HardwareResource::release (const GraphNode * done_node)
Release appropriate structures for a completed node.
Parameters
node_ptr pointer to the completed node
Definition at line 910 of file trace_cpu.cc.
References DPRINTFR, inFlightNodes, TraceCPU::ElasticDataGen::GraphNode::isLoad(), TraceCPU::ElasticDataGen::GraphNode::isStore(), TraceCPU::ElasticDataGen::GraphNode::isStrictlyOrdered(), numInFlightLoads, oldestInFlightRobNum, releaseStoreBuffer(), and TraceCPU::ElasticDataGen::GraphNode::seqNum.
releaseStoreBuffer()
void TraceCPU::ElasticDataGen::HardwareResource::releaseStoreBuffer ()
Release store buffer entry for a completed store.
Definition at line 951 of file trace_cpu.cc.
References numInFlightStores.
Referenced by release().
Member Data Documentation
inFlightNodes
std::map<NodeSeqNum, NodeRobNum> TraceCPU::ElasticDataGen::HardwareResource::inFlightNodes private
A map from the sequence number to the ROB number of the in- flight nodes.
This includes all nodes that are in the readyList plus the loads for which a request has been sent which are not present in the readyList. But such loads are not yet complete and thus occupy resources. We need to query the oldest in-flight node and since a map container keeps all its keys sorted using the less than criterion, the first element is the in-flight node with the least sequence number, i.e. the oldest in-flight node.
Definition at line 778 of file trace_cpu.hh.
Referenced by isAvailable(), occupy(), and release().
numInFlightLoads
uint16_t TraceCPU::ElasticDataGen::HardwareResource::numInFlightLoads private
Number of ready loads for which request may or may not be sent.
Definition at line 784 of file trace_cpu.hh.
Referenced by awaitingResponse(), isAvailable(), occupy(), printOccupancy(), and release().
numInFlightStores
uint16_t TraceCPU::ElasticDataGen::HardwareResource::numInFlightStores private
Number of ready stores for which request may or may not be sent.
Definition at line 787 of file trace_cpu.hh.
Referenced by awaitingResponse(), isAvailable(), occupy(), printOccupancy(), and releaseStoreBuffer().
oldestInFlightRobNum
NodeRobNum TraceCPU::ElasticDataGen::HardwareResource::oldestInFlightRobNum private
The ROB number of the oldest in-flight node.
Definition at line 781 of file trace_cpu.hh.
Referenced by isAvailable(), occupy(), printOccupancy(), and release().
sizeLoadBuffer
const uint16_t TraceCPU::ElasticDataGen::HardwareResource::sizeLoadBuffer private
The size of load buffer.
This is used to throttle the max. number of in-flight loads.
Definition at line 766 of file trace_cpu.hh.
Referenced by isAvailable(), and printOccupancy().
sizeROB
const uint16_t TraceCPU::ElasticDataGen::HardwareResource::sizeROB private
The size of the ROB used to throttle the max.
number of in-flight nodes.
Definition at line 754 of file trace_cpu.hh.
Referenced by isAvailable().
sizeStoreBuffer
const uint16_t TraceCPU::ElasticDataGen::HardwareResource::sizeStoreBuffer private
The size of store buffer.
This is used to throttle the max. number of in-flight stores.
Definition at line 760 of file trace_cpu.hh.
Referenced by isAvailable(), and printOccupancy().
The documentation for this class was generated from the following files:
cpu/trace/trace_cpu.hh
cpu/trace/trace_cpu.cc