gem5: ArmISA::ArmFault Class Reference
ArmISA::ArmFault Class Reference abstract
#include <faults.hh>
Classes
struct FaultVals
Public Types
enum FaultSource {
AlignmentFault = 0, InstructionCacheMaintenance, SynchExtAbtOnTranslTableWalkLL, SynchPtyErrOnTranslTableWalkLL = SynchExtAbtOnTranslTableWalkLL + 4,
TranslationLL = SynchPtyErrOnTranslTableWalkLL + 4, AccessFlagLL = TranslationLL + 4, DomainLL = AccessFlagLL + 4, PermissionLL = DomainLL + 4,
DebugEvent = PermissionLL + 4, SynchronousExternalAbort, TLBConflictAbort, SynchPtyErrOnMemoryAccess,
AsynchronousExternalAbort, AsynchPtyErrOnMemoryAccess, AddressSizeLL, PrefetchTLBMiss = AddressSizeLL + 4,
PrefetchUncacheable, NumFaultSources, FaultSourceInvalid = 0xff
}
Generic fault source enums used to index into {short/long/aarch64}DescFaultSources[] to get the actual encodings based on the current register width state and the translation table format in use.
enum AnnotationIDs {
S1PTW, OVA, SAS, SSE,
SRT, CM, OFA, SF,
AR
}
enum TranMethod { LpaeTran, VmsaTran, UnknownTran }
Public Member Functions
ArmFault (ExtMachInst _machInst=0, uint32_t _iss=0)
MiscRegIndex getSyndromeReg64 () const
MiscRegIndex getFaultAddrReg64 () const
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr) override
void invoke64 (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
void update (ThreadContext *tc)
ArmStaticInst * instrAnnotate (const StaticInstPtr &inst)
virtual void annotate (AnnotationIDs id, uint64_t val)
virtual FaultStat & countStat ()=0
virtual FaultOffset offset (ThreadContext *tc)=0
virtual FaultOffset offset64 (ThreadContext *tc)=0
virtual OperatingMode nextMode ()=0
virtual bool routeToMonitor (ThreadContext *tc) const =0
virtual bool routeToHyp (ThreadContext *tc) const
virtual uint8_t armPcOffset (bool isHyp)=0
virtual uint8_t thumbPcOffset (bool isHyp)=0
virtual uint8_t armPcElrOffset ()=0
virtual uint8_t thumbPcElrOffset ()=0
virtual bool abortDisable (ThreadContext *tc)=0
virtual bool fiqDisable (ThreadContext *tc)=0
virtual ExceptionClass ec (ThreadContext *tc) const =0
virtual uint32_t iss () const =0
virtual bool isStage2 () const
virtual FSR getFsr (ThreadContext *tc) const
virtual void setSyndrome (ThreadContext *tc, MiscRegIndex syndrome_reg)
virtual bool getFaultVAddr (Addr &va) const
Public Member Functions inherited from FaultBase
virtual FaultName name () const =0
virtual ~FaultBase ()
Static Public Attributes
static uint8_t shortDescFaultSources [NumFaultSources]
Encodings of the fault sources when the short-desc.
static uint8_t longDescFaultSources [NumFaultSources]
Encodings of the fault sources when the long-desc.
static uint8_t aarch64FaultSources [NumFaultSources]
Encodings of the fault sources in AArch64 state.
Protected Member Functions
virtual Addr getVector (ThreadContext *tc)
Addr getVector64 (ThreadContext *tc)
Protected Attributes
ExtMachInst machInst
uint32_t issRaw
bool from64
bool to64
ExceptionLevel fromEL
ExceptionLevel toEL
OperatingMode fromMode
OperatingMode toMode
bool faultUpdated
bool hypRouted
bool span
Detailed Description
Definition at line 65 of file faults.hh.
Member Enumeration Documentation
AnnotationIDs
enum ArmISA::ArmFault::AnnotationIDs
Enumerator
S1PTW
OVA
SAS
SSE
SRT
CM
OFA
SF
AR
Definition at line 132 of file faults.hh.
FaultSource
enum ArmISA::ArmFault::FaultSource
Generic fault source enums used to index into {short/long/aarch64}DescFaultSources[] to get the actual encodings based on the current register width state and the translation table format in use.
Enumerator
AlignmentFault
InstructionCacheMaintenance
SynchExtAbtOnTranslTableWalkLL
SynchPtyErrOnTranslTableWalkLL
TranslationLL
AccessFlagLL
DomainLL
PermissionLL
DebugEvent
SynchronousExternalAbort
TLBConflictAbort
SynchPtyErrOnMemoryAccess
AsynchronousExternalAbort
AsynchPtyErrOnMemoryAccess
AddressSizeLL
PrefetchTLBMiss
PrefetchUncacheable
NumFaultSources
FaultSourceInvalid
Definition at line 95 of file faults.hh.
TranMethod
enum ArmISA::ArmFault::TranMethod
Enumerator
LpaeTran
VmsaTran
UnknownTran
Definition at line 150 of file faults.hh.
Constructor & Destructor Documentation
ArmFault()
ArmISA::ArmFault::ArmFault (ExtMachInst _machInst = 0, uint32_t _iss = 0) inline
Definition at line 206 of file faults.hh.
References getFaultAddrReg64(), getSyndromeReg64(), instrAnnotate(), invoke(), invoke64(), StaticInst::nullStaticInstPtr, and update().
Member Function Documentation
abortDisable()
virtual bool ArmISA::ArmFault::abortDisable (ThreadContext * tc) pure virtual
Implemented in ArmISA::FastInterrupt, ArmISA::Interrupt, ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, ArmISA::AbortFault< DataAbort >, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke().
annotate()
virtual void ArmISA::ArmFault::annotate (AnnotationIDs id, uint64_t val) inline virtual
Reimplemented in ArmISA::DataAbort, ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 225 of file faults.hh.
References countStat(), ArmISA::ArmFault::FaultVals::nextMode, ArmISA::ArmFault::FaultVals::offset, offset64(), and routeToMonitor().
Referenced by ArmISA::DataAbort::DataAbort(), ArmISA::Stage2MMU::Stage2Translation::finish(), ArmISA::TLB::getResultTe(), ArmISA::AbortFault< DataAbort >::isStage2(), and ArmISA::Stage2MMU::readDataUntimed().
armPcElrOffset()
virtual uint8_t ArmISA::ArmFault::armPcElrOffset () pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke64().
armPcOffset()
virtual uint8_t ArmISA::ArmFault::armPcOffset (bool isHyp) pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke().
countStat()
virtual FaultStat& ArmISA::ArmFault::countStat () pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by annotate(), and invoke().
ec()
virtual ExceptionClass ArmISA::ArmFault::ec (ThreadContext * tc) const pure virtual
Implemented in ArmISA::SoftwareBreakpoint, ArmISA::DataAbort, ArmISA::PrefetchAbort, ArmISA::HypervisorTrap, ArmISA::HypervisorCall, ArmISA::SecureMonitorTrap, ArmISA::SupervisorTrap, ArmISA::SecureMonitorCall, ArmISA::SupervisorCall, ArmISA::UndefinedInstruction, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke(), and setSyndrome().
fiqDisable()
virtual bool ArmISA::ArmFault::fiqDisable (ThreadContext * tc) pure virtual
Implemented in ArmISA::FastInterrupt, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke().
getFaultAddrReg64()
MiscRegIndex ArmISA::ArmFault::getFaultAddrReg64 () const
Definition at line 367 of file faults.cc.
References ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmISA::MISCREG_FAR_EL1, ArmISA::MISCREG_FAR_EL2, ArmISA::MISCREG_FAR_EL3, panic, and toEL.
Referenced by ArmFault(), and ArmISA::PCAlignmentFault::invoke().
getFaultVAddr()
virtual bool ArmISA::ArmFault::getFaultVAddr (Addr & va) const inline virtual
Reimplemented in ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 243 of file faults.hh.
Referenced by ArmISA::AbortFault< DataAbort >::AbortFault(), and ArmISA::getFaultVAddr().
getFsr()
virtual FSR ArmISA::ArmFault::getFsr (ThreadContext * tc) const inline virtual
Reimplemented in ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 241 of file faults.hh.
References setSyndrome().
Referenced by ArmISA::AbortFault< DataAbort >::AbortFault(), ArmISA::AbortFault< DataAbort >::invoke(), and ArmISA::ISA::setMiscReg().
getSyndromeReg64()
MiscRegIndex ArmISA::ArmFault::getSyndromeReg64 () const
Definition at line 351 of file faults.cc.
References ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmISA::MISCREG_ESR_EL1, ArmISA::MISCREG_ESR_EL2, ArmISA::MISCREG_ESR_EL3, panic, and toEL.
Referenced by ArmFault(), and invoke64().
getVector()
Addr ArmISA::ArmFault::getVector (ThreadContext * tc) protected virtual
Reimplemented in ArmISA::Reset.
Definition at line 296 of file faults.cc.
References X86ISA::base, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmISA::HighVecs, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HVBAR, ArmISA::MISCREG_MVBAR, ArmISA::MISCREG_SCTLR, ArmISA::MISCREG_VBAR, ArmISA::MODE_HYP, ArmISA::MODE_MON, offset(), ThreadContext::readMiscReg(), and ThreadContext::readMiscRegNoEffect().
Referenced by invoke().
getVector64()
Addr ArmISA::ArmFault::getVector64 (ThreadContext * tc) protected
Definition at line 328 of file faults.cc.
References ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmISA::MISCREG_VBAR_EL1, ArmISA::MISCREG_VBAR_EL2, ArmISA::MISCREG_VBAR_EL3, offset64(), panic, ThreadContext::readMiscReg(), and toEL.
Referenced by invoke64().
instrAnnotate()
ArmStaticInst * ArmISA::ArmFault::instrAnnotate (const StaticInstPtr & inst)
Definition at line 713 of file faults.cc.
References ArmISA::ArmStaticInst::annotateFault(), and RefCountingPtr< T >::get().
Referenced by ArmFault(), invoke(), and invoke64().
invoke()
void ArmISA::ArmFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) override virtual
Reimplemented from FaultBase.
Reimplemented in ArmISA::ArmSev, ArmISA::SystemError, ArmISA::PCAlignmentFault, ArmISA::VirtualDataAbort, ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, ArmISA::AbortFault< DataAbort >, ArmISA::SecureMonitorCall, ArmISA::SupervisorCall, ArmISA::UndefinedInstruction, and ArmISA::Reset.
Definition at line 474 of file faults.cc.
References abortDisable(), armPcOffset(), ArmISA::CCREG_C, ArmISA::CCREG_GE, ArmISA::CCREG_NZ, ArmISA::CCREG_V, countStat(), csprintf(), DPRINTF, ec(), ArmISA::EC_UNKNOWN, fiqDisable(), FullSystem, getVector(), ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), instrAnnotate(), ArmISA::INTREG_LR, FaultBase::invoke(), invoke64(), M5_VAR_USED, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_ELR_HYP, ArmISA::MISCREG_HSCTLR, ArmISA::MISCREG_HSR, ArmISA::MISCREG_LOCKFLAG, ArmISA::MISCREG_SCR, ArmISA::MISCREG_SCTLR, ArmISA::MISCREG_SEV_MAILBOX, ArmISA::MISCREG_SPSR_ABT, ArmISA::MISCREG_SPSR_FIQ, ArmISA::MISCREG_SPSR_HYP, ArmISA::MISCREG_SPSR_IRQ, ArmISA::MISCREG_SPSR_MON, ArmISA::MISCREG_SPSR_SVC, ArmISA::MISCREG_SPSR_UND, ArmISA::MODE_ABORT, ArmISA::MODE_FIQ, ArmISA::MODE_HYP, ArmISA::MODE_IRQ, ArmISA::MODE_MON, ArmISA::MODE_SVC, ArmISA::MODE_UNDEFINED, FaultBase::name(), panic, MipsISA::pc, ThreadContext::pcState(), ThreadContext::readCCReg(), ThreadContext::readIntReg(), ThreadContext::readMiscReg(), ThreadContext::readMiscRegNoEffect(), ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), setSyndrome(), span, thumbPcOffset(), to64, toMode, and update().
Referenced by ArmISA::AbortFault< DataAbort >::AbortFault(), ArmFault(), ArmISA::ArmSev::ArmSev(), ArmISA::Reset::invoke(), ArmISA::UndefinedInstruction::invoke(), ArmISA::SupervisorCall::invoke(), ArmISA::SecureMonitorCall::invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::PCAlignmentFault::invoke(), ArmISA::SystemError::invoke(), ArmISA::PCAlignmentFault::PCAlignmentFault(), ArmISA::SecureMonitorCall::SecureMonitorCall(), ArmISA::SupervisorCall::SupervisorCall(), ArmISA::UndefinedInstruction::UndefinedInstruction(), and ArmISA::VirtualDataAbort::VirtualDataAbort().
invoke64()
void ArmISA::ArmFault::invoke64 (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr)
Definition at line 619 of file faults.cc.
References armPcElrOffset(), ArmISA::CCREG_C, ArmISA::CCREG_GE, ArmISA::CCREG_NZ, ArmISA::CCREG_V, csprintf(), DPRINTF, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, from64, getSyndromeReg64(), getVector64(), ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), instrAnnotate(), M5_VAR_USED, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_ELR_EL1, ArmISA::MISCREG_ELR_EL2, ArmISA::MISCREG_ELR_EL3, ArmISA::MISCREG_SPSR_EL1, ArmISA::MISCREG_SPSR_EL2, ArmISA::MISCREG_SPSR_EL3, ArmISA::mode, ArmISA::MODE_FIQ, ArmISA::MODE_IRQ, FaultBase::name(), nextMode(), panic, MipsISA::pc, ThreadContext::pcState(), ArmISA::purifyTaggedAddr(), ThreadContext::readCCReg(), ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), setSyndrome(), span, thumbPcElrOffset(), and toEL.
Referenced by ArmFault(), and invoke().
iss()
virtual uint32_t ArmISA::ArmFault::iss () const pure virtual
Implemented in ArmISA::DataAbort, ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, ArmISA::AbortFault< DataAbort >, ArmISA::SupervisorTrap, ArmISA::SecureMonitorCall, ArmISA::SupervisorCall, ArmISA::UndefinedInstruction, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by ArmISA::AbortFault< DataAbort >::AbortFault(), ArmISA::DataAbort::DataAbort(), routeToHyp(), ArmISA::SecureMonitorCall::SecureMonitorCall(), ArmISA::ISA::setMiscReg(), setSyndrome(), ArmISA::SupervisorCall::SupervisorCall(), ArmISA::SupervisorTrap::SupervisorTrap(), and ArmISA::UndefinedInstruction::UndefinedInstruction().
isStage2()
virtual bool ArmISA::ArmFault::isStage2 () const inline virtual
Reimplemented in ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 240 of file faults.hh.
Referenced by ArmISA::ISA::setMiscReg().
nextMode()
virtual OperatingMode ArmISA::ArmFault::nextMode () pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke64(), and update().
offset()
virtual FaultOffset ArmISA::ArmFault::offset (ThreadContext * tc) pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by getVector(), and ArmISA::Reset::getVector().
offset64()
virtual FaultOffset ArmISA::ArmFault::offset64 (ThreadContext * tc) pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by annotate(), ArmISA::ArmFaultVals< FastInterrupt >::countStat(), and getVector64().
routeToHyp()
virtual bool ArmISA::ArmFault::routeToHyp (ThreadContext * tc) const inline virtual
Reimplemented in ArmISA::SoftwareBreakpoint, ArmISA::SystemError, ArmISA::PCAlignmentFault, ArmISA::FastInterrupt, ArmISA::Interrupt, ArmISA::DataAbort, ArmISA::PrefetchAbort, ArmISA::SupervisorTrap, ArmISA::SupervisorCall, and ArmISA::UndefinedInstruction.
Definition at line 231 of file faults.hh.
References ArmISA::ArmFault::FaultVals::abortDisable, ArmISA::ArmFault::FaultVals::armPcElrOffset, ArmISA::ArmFault::FaultVals::armPcOffset, ArmISA::ArmFault::FaultVals::ec, ArmISA::ArmFault::FaultVals::fiqDisable, iss(), ArmISA::ArmFault::FaultVals::thumbPcElrOffset, and ArmISA::ArmFault::FaultVals::thumbPcOffset.
Referenced by ArmISA::DataAbort::DataAbort(), ArmISA::PCAlignmentFault::PCAlignmentFault(), ArmISA::PrefetchAbort::PrefetchAbort(), ArmISA::SupervisorCall::SupervisorCall(), ArmISA::SupervisorTrap::SupervisorTrap(), ArmISA::UndefinedInstruction::UndefinedInstruction(), and update().
routeToMonitor()
virtual bool ArmISA::ArmFault::routeToMonitor (ThreadContext * tc) const pure virtual
Implemented in ArmISA::SystemError, ArmISA::FastInterrupt, ArmISA::Interrupt, ArmISA::DataAbort, ArmISA::PrefetchAbort, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by annotate(), ArmISA::DataAbort::DataAbort(), ArmISA::PrefetchAbort::PrefetchAbort(), and update().
setSyndrome()
void ArmISA::ArmFault::setSyndrome (ThreadContext * tc, MiscRegIndex syndrome_reg) virtual
Reimplemented in ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, and ArmISA::AbortFault< DataAbort >.
Definition at line 383 of file faults.cc.
References bits(), ArmISA::cond, ArmISA::COND_AL, ArmISA::COND_UC, ArmISA::condCode, ec(), from64, ArmSystem::highestELIs64(), iss(), machInst, ThreadContext::setMiscReg(), and to64.
Referenced by getFsr(), invoke(), invoke64(), ArmISA::AbortFault< DataAbort >::isStage2(), and ArmISA::AbortFault< DataAbort >::setSyndrome().
thumbPcElrOffset()
virtual uint8_t ArmISA::ArmFault::thumbPcElrOffset () pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke64().
thumbPcOffset()
virtual uint8_t ArmISA::ArmFault::thumbPcOffset (bool isHyp) pure virtual
Implemented in ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, and ArmISA::ArmFaultVals< FastInterrupt >.
Referenced by invoke().
update()
void ArmISA::ArmFault::update (ThreadContext * tc)
Definition at line 424 of file faults.cc.
References ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmISA::ELIs64(), faultUpdated, from64, fromEL, fromMode, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), hypRouted, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR_EL2, ArmISA::MISCREG_ID_AA64MMFR1_EL1, ArmISA::MISCREG_SCTLR_EL1, ArmISA::MISCREG_SCTLR_EL2, ArmISA::MODE_HYP, ArmISA::MODE_MON, nextMode(), ArmISA::opModeToEL(), ThreadContext::readMiscReg(), ThreadContext::readMiscRegNoEffect(), routeToHyp(), routeToMonitor(), span, to64, toEL, and toMode.
Referenced by ArmFault(), invoke(), and ArmISA::ISA::setMiscReg().
Member Data Documentation
aarch64FaultSources
uint8_t ArmISA::ArmFault::aarch64FaultSources static
Encodings of the fault sources in AArch64 state.
Definition at line 130 of file faults.hh.
faultUpdated
bool ArmISA::ArmFault::faultUpdated protected
Definition at line 82 of file faults.hh.
Referenced by ArmISA::AbortFault< DataAbort >::getFaultStatusCode(), and update().
from64
bool ArmISA::ArmFault::from64 protected
Definition at line 72 of file faults.hh.
Referenced by ArmISA::SupervisorCall::ec(), ArmISA::SecureMonitorCall::ec(), ArmISA::SecureMonitorTrap::ec(), ArmISA::HypervisorCall::ec(), ArmISA::SoftwareBreakpoint::ec(), ArmISA::PCAlignmentFault::invoke(), invoke64(), ArmISA::SecureMonitorCall::iss(), ArmISA::SystemError::routeToHyp(), ArmISA::PrefetchAbort::routeToMonitor(), ArmISA::DataAbort::routeToMonitor(), ArmISA::Interrupt::routeToMonitor(), ArmISA::FastInterrupt::routeToMonitor(), ArmISA::SystemError::routeToMonitor(), setSyndrome(), and update().
fromEL
ExceptionLevel ArmISA::ArmFault::fromEL protected
Definition at line 74 of file faults.hh.
Referenced by ArmISA::PrefetchAbort::ec(), ArmISA::DataAbort::ec(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), ArmISA::SoftwareBreakpoint::routeToHyp(), and update().
fromMode
OperatingMode ArmISA::ArmFault::fromMode protected
Definition at line 76 of file faults.hh.
Referenced by ArmISA::ArmFaultVals< FastInterrupt >::offset64(), and update().
hypRouted
bool ArmISA::ArmFault::hypRouted protected
Definition at line 84 of file faults.hh.
Referenced by ArmISA::UndefinedInstruction::ec(), ArmISA::SupervisorTrap::ec(), ArmISA::UndefinedInstruction::iss(), ArmISA::SupervisorTrap::iss(), and update().
issRaw
uint32_t ArmISA::ArmFault::issRaw protected
Definition at line 69 of file faults.hh.
Referenced by ArmISA::ArmFaultVals< FastInterrupt >::iss(), ArmISA::UndefinedInstruction::iss(), ArmISA::SupervisorCall::iss(), and ArmISA::SupervisorTrap::iss().
longDescFaultSources
uint8_t ArmISA::ArmFault::longDescFaultSources static
Encodings of the fault sources when the long-desc.
translation table format is in use (ARM ARM Issue C B3.13.3)
Definition at line 128 of file faults.hh.
machInst
ExtMachInst ArmISA::ArmFault::machInst protected
Definition at line 68 of file faults.hh.
Referenced by ArmISA::SupervisorCall::invoke(), ArmISA::UndefinedInstruction::iss(), ArmISA::SecureMonitorCall::iss(), and setSyndrome().
shortDescFaultSources
uint8_t ArmISA::ArmFault::shortDescFaultSources static
Encodings of the fault sources when the short-desc.
translation table format is in use (ARM ARM Issue C B3.13.3)
Definition at line 125 of file faults.hh.
span
bool ArmISA::ArmFault::span protected
Definition at line 85 of file faults.hh.
Referenced by invoke(), invoke64(), and update().
to64
bool ArmISA::ArmFault::to64 protected
Definition at line 73 of file faults.hh.
Referenced by ArmISA::PrefetchAbort::ec(), ArmISA::DataAbort::ec(), ArmISA::AbortFault< DataAbort >::getFaultStatusCode(), invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::DataAbort::iss(), setSyndrome(), and update().
toEL
ExceptionLevel ArmISA::ArmFault::toEL protected
Definition at line 75 of file faults.hh.
Referenced by ArmISA::PrefetchAbort::ec(), ArmISA::DataAbort::ec(), getFaultAddrReg64(), getSyndromeReg64(), getVector64(), invoke64(), ArmISA::DataAbort::iss(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), and update().
toMode
OperatingMode ArmISA::ArmFault::toMode protected
Definition at line 77 of file faults.hh.
Referenced by invoke(), and update().
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc