gem5: TBETable< ENTRY > Class Template Reference
TBETable< ENTRY > Class Template Reference
#include <TBETable.hh>
Public Member Functions
TBETable (int number_of_TBEs)
bool isPresent (Addr address) const
void allocate (Addr address)
void deallocate (Addr address)
bool areNSlotsAvailable (int n, Tick current_time) const
ENTRY * lookup (Addr address)
void print (std::ostream &out) const
Private Member Functions
TBETable (const TBETable &obj)
TBETable & operator= (const TBETable &obj)
Private Attributes
std::unordered_map< Addr, ENTRY > m_map
int m_number_of_TBEs
Detailed Description
template<class ENTRY>
class TBETable< ENTRY >
Definition at line 38 of file TBETable.hh.
Constructor & Destructor Documentation
TBETable() [1/2]
template<class ENTRY > TBETable< ENTRY >::TBETable (int number_of_TBEs) inline
Definition at line 41 of file TBETable.hh.
References TBETable< ENTRY >::allocate(), TBETable< ENTRY >::deallocate(), and TBETable< ENTRY >::isPresent().
Referenced by TBETable< ENTRY >::areNSlotsAvailable().
TBETable() [2/2]
template<class ENTRY > TBETable< ENTRY >::TBETable (const TBETable< ENTRY > & obj) private
Member Function Documentation
allocate()
template<class ENTRY > void TBETable< ENTRY >::allocate (Addr address) inline
Definition at line 92 of file TBETable.hh.
References TBETable< ENTRY >::isPresent(), TBETable< ENTRY >::m_map, and TBETable< ENTRY >::m_number_of_TBEs.
Referenced by TBETable< ENTRY >::TBETable().
areNSlotsAvailable()
template<class ENTRY > bool TBETable< ENTRY >::areNSlotsAvailable (int n, Tick current_time) const inline
Definition at line 50 of file TBETable.hh.
References TBETable< ENTRY >::lookup(), TBETable< ENTRY >::m_map, TBETable< ENTRY >::m_number_of_TBEs, TBETable< ENTRY >::operator=(), TBETable< ENTRY >::print(), and TBETable< ENTRY >::TBETable().
deallocate()
template<class ENTRY > void TBETable< ENTRY >::deallocate (Addr address) inline
Definition at line 101 of file TBETable.hh.
References TBETable< ENTRY >::isPresent(), and TBETable< ENTRY >::m_map.
Referenced by TBETable< ENTRY >::TBETable().
isPresent()
template<class ENTRY > bool TBETable< ENTRY >::isPresent (Addr address) const inline
Definition at line 83 of file TBETable.hh.
References TBETable< ENTRY >::m_map, TBETable< ENTRY >::m_number_of_TBEs, and makeLineAddress().
Referenced by TBETable< ENTRY >::allocate(), TBETable< ENTRY >::deallocate(), and TBETable< ENTRY >::TBETable().
lookup()
template<class ENTRY > ENTRY * TBETable< ENTRY >::lookup (Addr address) inline
Definition at line 111 of file TBETable.hh.
References TBETable< ENTRY >::m_map.
Referenced by TBETable< ENTRY >::areNSlotsAvailable().
operator=()
template<class ENTRY > TBETable& TBETable< ENTRY >::operator= (const TBETable< ENTRY > & obj) private
Referenced by TBETable< ENTRY >::areNSlotsAvailable().
print()
template<class ENTRY > void TBETable< ENTRY >::print (std::ostream & out) const inline
Definition at line 120 of file TBETable.hh.
Referenced by TBETable< ENTRY >::areNSlotsAvailable().
Member Data Documentation
m_map
template<class ENTRY > std::unordered_map<Addr, ENTRY> TBETable< ENTRY >::m_map private
Definition at line 66 of file TBETable.hh.
Referenced by TBETable< ENTRY >::allocate(), TBETable< ENTRY >::areNSlotsAvailable(), TBETable< ENTRY >::deallocate(), TBETable< ENTRY >::isPresent(), and TBETable< ENTRY >::lookup().
m_number_of_TBEs
template<class ENTRY > int TBETable< ENTRY >::m_number_of_TBEs private
Definition at line 69 of file TBETable.hh.
Referenced by TBETable< ENTRY >::allocate(), TBETable< ENTRY >::areNSlotsAvailable(), and TBETable< ENTRY >::isPresent().
The documentation for this class was generated from the following file:
mem/ruby/structures/TBETable.hh