gem5: SMMUTranslationProcess Class Reference
SMMUTranslationProcess Class Reference
#include <smmu_v3_transl.hh>
Classes
struct TranslContext
struct TranslResult
Public Member Functions
SMMUTranslationProcess (const std::string &name, SMMUv3 &_smmu, SMMUv3SlaveInterface &_ifc)
virtual ~SMMUTranslationProcess ()
void beginTransaction (const SMMUTranslRequest &req)
void resumeTransaction ()
Public Member Functions inherited from SMMUProcess
SMMUProcess (const std::string &name, SMMUv3 &_smmu)
virtual ~SMMUProcess ()
SMMUAction run (PacketPtr pkt)
const std::string name () const
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Private Types
enum FaultType { FAULT_NONE, FAULT_TRANSLATION, FAULT_PERMISSION }
Private Member Functions
virtual void main (Yield &yield)
TranslResult bypass (Addr addr) const
TranslResult smmuTranslation (Yield &yield)
bool microTLBLookup (Yield &yield, TranslResult &tr)
bool ifcTLBLookup (Yield &yield, TranslResult &tr, bool &wasPrefetched)
bool smmuTLBLookup (Yield &yield, TranslResult &tr)
void microTLBUpdate (Yield &yield, const TranslResult &tr)
void ifcTLBUpdate (Yield &yield, const TranslResult &tr)
void smmuTLBUpdate (Yield &yield, const TranslResult &tr)
bool configCacheLookup (Yield &yield, TranslContext &tc)
void configCacheUpdate (Yield &yield, const TranslContext &tc)
bool findConfig (Yield &yield, TranslContext &tc, TranslResult &tr)
void walkCacheLookup (Yield &yield, const WalkCache::Entry *&walkEntry, Addr addr, uint16_t asid, uint16_t vmid, unsigned stage, unsigned level)
void walkCacheUpdate (Yield &yield, Addr va, Addr vaMask, Addr pa, unsigned stage, unsigned level, bool leaf, uint8_t permissions)
TranslResult walkStage1And2 (Yield &yield, Addr addr, const PageTableOps *pt_ops, unsigned level, Addr walkPtr)
TranslResult walkStage2 (Yield &yield, Addr addr, bool final_tr, const PageTableOps *pt_ops, unsigned level, Addr walkPtr)
TranslResult translateStage1And2 (Yield &yield, Addr addr)
TranslResult translateStage2 (Yield &yield, Addr addr, bool final_tr)
TranslResult combineTranslations (const TranslResult &s1tr, const TranslResult &s2tr) const
bool hazard4kCheck ()
Used to force ordering on transactions with same (SID, SSID, 4k page) to avoid multiple identical page-table walks.
void hazard4kRegister ()
void hazard4kHold (Yield &yield)
void hazard4kRelease ()
void hazardIdRegister ()
Used to force ordering on transactions with the same orderId.
void hazardIdHold (Yield &yield)
void hazardIdRelease ()
void issuePrefetch (Addr addr)
void completeTransaction (Yield &yield, const TranslResult &tr)
void completePrefetch (Yield &yield)
void sendEvent (Yield &yield, const SMMUEvent &ev)
void doReadSTE (Yield &yield, StreamTableEntry &ste, uint32_t sid)
void doReadCD (Yield &yield, ContextDescriptor &cd, const StreamTableEntry &ste, uint32_t sid, uint32_t ssid)
void doReadConfig (Yield &yield, Addr addr, void *ptr, size_t size, uint32_t sid, uint32_t ssid)
void doReadPTE (Yield &yield, Addr va, Addr addr, void *ptr, unsigned stage, unsigned level)
Private Attributes
SMMUv3SlaveInterface & ifc
SMMUTranslRequest request
TranslContext context
Tick recvTick
Tick faultTick
Additional Inherited Members
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Protected Types inherited from SMMUProcess
typedef Coroutine::CallerType Yield
Protected Member Functions inherited from SMMUProcess
void reinit ()
void doRead (Yield &yield, Addr addr, void *ptr, size_t size)
void doWrite (Yield &yield, Addr addr, const void *ptr, size_t size)
void doDelay (Yield &yield, Cycles cycles)
void doSleep (Yield &yield)
void doSemaphoreDown (Yield &yield, SMMUSemaphore &sem)
void doSemaphoreUp (SMMUSemaphore &sem)
void doWaitForSignal (Yield &yield, SMMUSignal &sig)
void doBroadcastSignal (SMMUSignal &sig)
void scheduleWakeup (Tick when)
Protected Attributes inherited from SMMUProcess
SMMUv3 & smmu
Detailed Description
Definition at line 64 of file smmu_v3_transl.hh.
Member Enumeration Documentation
FaultType
enum SMMUTranslationProcess::FaultType private
Enumerator
FAULT_NONE
FAULT_TRANSLATION
FAULT_PERMISSION
Definition at line 80 of file smmu_v3_transl.hh.
Constructor & Destructor Documentation
SMMUTranslationProcess()
SMMUTranslationProcess::SMMUTranslationProcess (const std::string & name, SMMUv3 & _smmu, SMMUv3SlaveInterface & _ifc)
Definition at line 81 of file smmu_v3_transl.cc.
References ifc, SMMUv3SlaveInterface::pendingMemAccesses, SMMUProcess::reinit(), and SMMUv3SlaveInterface::xlateSlotsRemaining.
Referenced by issuePrefetch().
~SMMUTranslationProcess()
SMMUTranslationProcess::~SMMUTranslationProcess () virtual
Definition at line 95 of file smmu_v3_transl.cc.
References ifc, SMMUv3SlaveInterface::pendingMemAccesses, and Drainable::signalDrainDone().
Member Function Documentation
beginTransaction()
void SMMUTranslationProcess::beginTransaction (const SMMUTranslRequest & req)
Definition at line 109 of file smmu_v3_transl.cc.
References SMMUProcess::reinit(), and request.
Referenced by SMMUv3SlaveInterface::atsSlaveRecvAtomic(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), issuePrefetch(), SMMUv3SlaveInterface::recvAtomic(), SMMUv3SlaveInterface::recvTimingReq(), and resumeTransaction().
bypass()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::bypass (Addr addr) const private
Definition at line 239 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, and SMMUTranslationProcess::TranslResult::writable.
Referenced by main(), and smmuTranslation().
combineTranslations()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::combineTranslations (const TranslResult & s1tr, const TranslResult & s2tr) const private
Definition at line 1027 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, and SMMUTranslationProcess::TranslResult::writable.
Referenced by walkStage1And2().
completePrefetch()
void SMMUTranslationProcess::completePrefetch (Yield & yield) private
Definition at line 1288 of file smmu_v3_transl.cc.
References ArmISA::a, ACTION_TERMINATE, SMMUAction::delay, SMMUAction::ifc, ifc, SMMUAction::pkt, SMMUAction::type, and SMMUv3SlaveInterface::xlateSlotsRemaining.
Referenced by main().
completeTransaction()
void SMMUTranslationProcess::completeTransaction (Yield & yield, const TranslResult & tr) private
Definition at line 1226 of file smmu_v3_transl.cc.
References ArmISA::a, ACTION_SEND_REQ_FINAL, ACTION_SEND_RESP, ACTION_SEND_RESP_ATS, SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, curTick(), SMMUAction::delay, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, m5::Coroutine< Arg, Ret >::CallerType::get(), SMMUAction::ifc, ifc, System::isAtomicMode(), SMMUTranslRequest::isAtsRequest, System::isTimingMode(), SMMUTranslRequest::isWrite, Packet::makeAtomicResponse(), Packet::makeTimingResponse(), SMMUv3::masterPortSem, SMMUv3::masterPortWidth, panic, SMMUTranslRequest::pkt, SMMUAction::pkt, SMMUv3SlaveInterface::portWidth, recvTick, Packet::req, request, Stats::DistBase< Derived, Stor >::sample(), SMMUv3::scheduleSlaveRetries(), Packet::setAddr(), SMMUTranslRequest::size, SMMUProcess::smmu, SMMUv3::system, SMMUv3::translationTimeDist, SMMUAction::type, SMMUv3SlaveInterface::wrBufSlotsRemaining, and SMMUv3SlaveInterface::xlateSlotsRemaining.
Referenced by main().
configCacheLookup()
bool SMMUTranslationProcess::configCacheLookup (Yield & yield, TranslContext & tc) private
Definition at line 508 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslContext::asid, ConfigCache::Entry::asid, SMMUv3::configCache, SMMUv3::configCacheEnable, SMMUv3::configLat, SMMUv3::configSem, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslContext::httb, ConfigCache::Entry::httb, ConfigCache::lookup(), request, SMMUTranslationProcess::TranslContext::s2t0sz, ConfigCache::Entry::s2t0sz, SMMUTranslRequest::sid, SMMUProcess::smmu, SMMUTranslRequest::ssid, ConfigCache::Entry::stage1_en, ConfigCache::Entry::stage1_tg, SMMUTranslationProcess::TranslContext::stage1Enable, SMMUTranslationProcess::TranslContext::stage1TranslGranule, ConfigCache::Entry::stage2_en, ConfigCache::Entry::stage2_tg, SMMUTranslationProcess::TranslContext::stage2Enable, SMMUTranslationProcess::TranslContext::stage2TranslGranule, SMMUTranslationProcess::TranslContext::t0sz, ConfigCache::Entry::t0sz, SMMUTranslationProcess::TranslContext::ttb0, ConfigCache::Entry::ttb0, SMMUTranslationProcess::TranslContext::ttb1, ConfigCache::Entry::ttb1, SMMUTranslationProcess::TranslContext::vmid, and ConfigCache::Entry::vmid.
Referenced by smmuTranslation().
configCacheUpdate()
void SMMUTranslationProcess::configCacheUpdate (Yield & yield, const TranslContext & tc) private
Definition at line 548 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslContext::asid, ConfigCache::Entry::asid, SMMUv3::configCache, SMMUv3::configCacheEnable, SMMUv3::configSem, SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslContext::httb, ConfigCache::Entry::httb, request, SMMUTranslationProcess::TranslContext::s2t0sz, ConfigCache::Entry::s2t0sz, SMMUTranslRequest::sid, ConfigCache::Entry::sid, SMMUProcess::smmu, SMMUTranslRequest::ssid, ConfigCache::Entry::ssid, ConfigCache::Entry::stage1_en, ConfigCache::Entry::stage1_tg, SMMUTranslationProcess::TranslContext::stage1Enable, SMMUTranslationProcess::TranslContext::stage1TranslGranule, ConfigCache::Entry::stage2_en, ConfigCache::Entry::stage2_tg, SMMUTranslationProcess::TranslContext::stage2Enable, SMMUTranslationProcess::TranslContext::stage2TranslGranule, ConfigCache::store(), SMMUTranslationProcess::TranslContext::t0sz, ConfigCache::Entry::t0sz, SMMUTranslationProcess::TranslContext::ttb0, ConfigCache::Entry::ttb0, SMMUTranslationProcess::TranslContext::ttb1, ConfigCache::Entry::ttb1, ConfigCache::Entry::valid, SMMUTranslationProcess::TranslContext::vmid, and ConfigCache::Entry::vmid.
Referenced by smmuTranslation().
doReadCD()
void SMMUTranslationProcess::doReadCD (Yield & yield, ContextDescriptor & cd, const StreamTableEntry & ste, uint32_t sid, uint32_t ssid) private
Definition at line 1398 of file smmu_v3_transl.cc.
References ContextDescriptor::_pad, SMMUTranslationProcess::TranslResult::addr, ContextDescriptor::amair, bits(), ArmISA::cd, SMMUv3::cdFetches, SMMUv3::cdL1Fetches, context, doReadConfig(), DPRINTF, ContextDescriptor::mair, panic, StreamTableEntry::s1cdmax, StreamTableEntry::s1ctxptr, StreamTableEntry::s1fmt, SMMUProcess::smmu, ST_CD_ADDR_SHIFT, STAGE1_CFG_1L, STAGE1_CFG_2L_4K, STAGE1_CFG_2L_64K, SMMUTranslationProcess::TranslContext::stage2Enable, translateStage2(), and ContextDescriptor::valid.
Referenced by findConfig().
doReadConfig()
void SMMUTranslationProcess::doReadConfig (Yield & yield, Addr addr, void * ptr, size_t size, uint32_t sid, uint32_t ssid) private
Definition at line 1462 of file smmu_v3_transl.cc.
References SMMUProcess::doRead().
Referenced by doReadCD(), and doReadSTE().
doReadPTE()
void SMMUTranslationProcess::doReadPTE (Yield & yield, Addr va, Addr addr, void * ptr, unsigned stage, unsigned level) private
Definition at line 1470 of file smmu_v3_transl.cc.
References X86ISA::base, SMMUProcess::doRead(), and ArmISA::mask.
Referenced by walkStage1And2(), and walkStage2().
doReadSTE()
void SMMUTranslationProcess::doReadSTE (Yield & yield, StreamTableEntry & ste, uint32_t sid) private
Definition at line 1331 of file smmu_v3_transl.cc.
References StreamTableEntry::_pad, bits(), doReadConfig(), DPRINTF, MipsISA::index, panic, SMMUv3::regs, SMMUProcess::smmu, ArmISA::span, ST_CFG_FMT_2LEVEL, ST_CFG_FMT_LINEAR, ST_CFG_FMT_MASK, ST_CFG_SIZE_MASK, ST_CFG_SPLIT_MASK, ST_CFG_SPLIT_SHIFT, ST_L2_ADDR_MASK, ST_L2_SPAN_MASK, SMMUv3::steFetches, SMMUv3::steL1Fetches, SMMURegs::strtab_base, SMMURegs::strtab_base_cfg, and VMT_BASE_ADDR_MASK.
Referenced by findConfig().
findConfig()
bool SMMUTranslationProcess::findConfig (Yield & yield, TranslContext & tc, TranslResult & tr) private
Definition at line 580 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslContext::asid, ContextDescriptor::asid, ArmISA::cd, CD_TTB_SHIFT, StreamTableEntry::config, context, doReadCD(), doReadSTE(), SMMUTranslationProcess::TranslContext::httb, panic, request, SMMUTranslationProcess::TranslContext::s2t0sz, StreamTableEntry::s2t0sz, StreamTableEntry::s2tg, StreamTableEntry::s2ttb, StreamTableEntry::s2vmid, SMMUTranslRequest::sid, SMMUTranslRequest::ssid, SMMUTranslationProcess::TranslContext::stage1Enable, SMMUTranslationProcess::TranslContext::stage1TranslGranule, SMMUTranslationProcess::TranslContext::stage2Enable, SMMUTranslationProcess::TranslContext::stage2TranslGranule, STE_CONFIG_BYPASS, STE_CONFIG_STAGE1_AND_2, STE_CONFIG_STAGE1_ONLY, STE_CONFIG_STAGE2_ONLY, STE_S2TTB_SHIFT, SMMUTranslationProcess::TranslContext::t0sz, ContextDescriptor::t0sz, ContextDescriptor::tg0, TRANS_GRANULE_INVALID, SMMUTranslationProcess::TranslContext::ttb0, ContextDescriptor::ttb0, SMMUTranslationProcess::TranslContext::ttb1, ContextDescriptor::ttb1, and SMMUTranslationProcess::TranslContext::vmid.
Referenced by smmuTranslation().
hazard4kCheck()
bool SMMUTranslationProcess::hazard4kCheck () private
Used to force ordering on transactions with same (SID, SSID, 4k page) to avoid multiple identical page-table walks.
Definition at line 1045 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUv3SlaveInterface::duplicateReqs, ifc, request, and ULL.
Referenced by main().
hazard4kHold()
void SMMUTranslationProcess::hazard4kHold (Yield & yield) private
Definition at line 1071 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUProcess::doWaitForSignal(), DPRINTF, SMMUv3SlaveInterface::duplicateReqRemoved, SMMUv3SlaveInterface::duplicateReqs, ifc, request, and ULL.
Referenced by main().
hazard4kRegister()
void SMMUTranslationProcess::hazard4kRegister () private
Definition at line 1062 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, DPRINTF, SMMUv3SlaveInterface::duplicateReqs, ifc, and request.
Referenced by main().
hazard4kRelease()
void SMMUTranslationProcess::hazard4kRelease () private
Definition at line 1109 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUProcess::doBroadcastSignal(), DPRINTF, SMMUv3SlaveInterface::duplicateReqRemoved, SMMUv3SlaveInterface::duplicateReqs, ifc, panic, and request.
Referenced by main().
hazardIdHold()
void SMMUTranslationProcess::hazardIdHold (Yield & yield) private
Definition at line 1144 of file smmu_v3_transl.cc.
References SMMUv3SlaveInterface::dependentReads, SMMUv3SlaveInterface::dependentReqRemoved, SMMUv3SlaveInterface::dependentWrites, SMMUProcess::doWaitForSignal(), DPRINTF, ifc, SMMUTranslRequest::isWrite, AMBA::orderId(), SMMUTranslRequest::pkt, and request.
Referenced by main().
hazardIdRegister()
void SMMUTranslationProcess::hazardIdRegister () private
Used to force ordering on transactions with the same orderId.
This attempts to model AXI IDs.
Definition at line 1129 of file smmu_v3_transl.cc.
References SMMUv3SlaveInterface::dependentReads, SMMUv3SlaveInterface::dependentWrites, DPRINTF, ifc, SMMUTranslRequest::isWrite, AMBA::orderId(), SMMUTranslRequest::pkt, request, and SMMU_MAX_TRANS_ID.
Referenced by main().
hazardIdRelease()
void SMMUTranslationProcess::hazardIdRelease () private
Definition at line 1183 of file smmu_v3_transl.cc.
References SMMUv3SlaveInterface::dependentReads, SMMUv3SlaveInterface::dependentReqRemoved, SMMUv3SlaveInterface::dependentWrites, SMMUProcess::doBroadcastSignal(), DPRINTF, ifc, SMMUTranslRequest::isWrite, AMBA::orderId(), panic, SMMUTranslRequest::pkt, and request.
Referenced by main().
ifcTLBLookup()
bool SMMUTranslationProcess::ifcTLBLookup (Yield & yield, TranslResult & tr, bool & wasPrefetched) private
Definition at line 344 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ifc, SMMUTLB::lookup(), SMMUv3SlaveInterface::mainTLB, SMMUv3SlaveInterface::mainTLBEnable, SMMUv3SlaveInterface::mainTLBLat, SMMUv3SlaveInterface::mainTLBSem, SMMUTLB::Entry::pa, SMMUTLB::Entry::permissions, SMMUTLB::Entry::prefetched, request, SMMUTranslRequest::sid, SMMUTranslRequest::ssid, SMMUTLB::Entry::vaMask, and SMMUTranslationProcess::TranslResult::writable.
Referenced by main().
ifcTLBUpdate()
void SMMUTranslationProcess::ifcTLBUpdate (Yield & yield, const TranslResult & tr) private
Definition at line 442 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTLB::ALLOC_ANY_BUT_LAST_WAY, SMMUTLB::ALLOC_ANY_WAY, SMMUTLB::ALLOC_LAST_WAY, SMMUTranslationProcess::TranslContext::asid, SMMUTLB::Entry::asid, context, SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ifc, SMMUTranslRequest::isPrefetch, SMMUv3SlaveInterface::mainTLB, SMMUv3SlaveInterface::mainTLBEnable, SMMUv3SlaveInterface::mainTLBSem, SMMUTLB::Entry::pa, SMMUTLB::Entry::permissions, SMMUTLB::Entry::prefetched, SMMUv3SlaveInterface::prefetchEnable, SMMUv3SlaveInterface::prefetchReserveLastWay, request, SMMUTranslRequest::sid, SMMUTLB::Entry::sid, SMMUTranslRequest::ssid, SMMUTLB::Entry::ssid, SMMUTLB::store(), SMMUTLB::Entry::va, SMMUTLB::Entry::valid, SMMUTLB::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, SMMUTLB::Entry::vmid, and SMMUTranslationProcess::TranslResult::writable.
Referenced by main().
issuePrefetch()
void SMMUTranslationProcess::issuePrefetch (Addr addr) private
Definition at line 1208 of file smmu_v3_transl.cc.
References beginTransaction(), Clocked::clockEdge(), csprintf(), ifc, System::isTimingMode(), SMMUProcess::name(), SMMUTranslRequest::prefetch(), SMMUv3SlaveInterface::prefetchEnable, request, SMMUProcess::scheduleWakeup(), SMMUTranslRequest::sid, SMMUProcess::smmu, SMMUTranslationProcess(), SMMUTranslRequest::ssid, SMMUv3::system, and SMMUv3SlaveInterface::xlateSlotsRemaining.
Referenced by main().
main()
void SMMUTranslationProcess::main (Yield & yield) private virtual
Implements SMMUProcess.
Definition at line 135 of file smmu_v3_transl.cc.
References ArmISA::a, ACTION_INITIAL_NOP, SMMUTranslRequest::addr, bypass(), completePrefetch(), completeTransaction(), SMMURegs::cr0, CR0_SMMUEN_MASK, curTick(), SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, hazard4kCheck(), hazard4kHold(), hazard4kRegister(), hazard4kRelease(), hazardIdHold(), hazardIdRegister(), hazardIdRelease(), ifc, ifcTLBLookup(), ifcTLBUpdate(), SMMUTranslRequest::isAtsRequest, SMMUTranslRequest::isPrefetch, issuePrefetch(), SMMUTranslRequest::isWrite, microTLBLookup(), microTLBUpdate(), panic, SMMUAction::pkt, SMMUv3SlaveInterface::portWidth, recvTick, SMMUv3::regs, request, SMMUTranslRequest::sid, SMMUTranslRequest::size, SMMUv3SlaveInterface::slavePortSem, SMMUProcess::smmu, smmuTranslation(), SMMUTranslRequest::ssid, SMMUAction::type, and ULL.
microTLBLookup()
bool SMMUTranslationProcess::microTLBLookup (Yield & yield, TranslResult & tr) private
Definition at line 313 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ifc, SMMUTLB::lookup(), SMMUv3SlaveInterface::microTLB, SMMUv3SlaveInterface::microTLBEnable, SMMUv3SlaveInterface::microTLBLat, SMMUv3SlaveInterface::microTLBSem, SMMUTLB::Entry::pa, SMMUTLB::Entry::permissions, request, SMMUTranslRequest::sid, SMMUTranslRequest::ssid, SMMUTLB::Entry::vaMask, and SMMUTranslationProcess::TranslResult::writable.
Referenced by main().
microTLBUpdate()
void SMMUTranslationProcess::microTLBUpdate (Yield & yield, const TranslResult & tr) private
Definition at line 410 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTLB::ALLOC_ANY_WAY, SMMUTranslationProcess::TranslContext::asid, SMMUTLB::Entry::asid, context, SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ifc, SMMUv3SlaveInterface::microTLB, SMMUv3SlaveInterface::microTLBEnable, SMMUv3SlaveInterface::microTLBSem, SMMUTLB::Entry::pa, SMMUTLB::Entry::permissions, SMMUTLB::Entry::prefetched, request, SMMUTranslRequest::sid, SMMUTLB::Entry::sid, SMMUTranslRequest::ssid, SMMUTLB::Entry::ssid, SMMUTLB::store(), SMMUTLB::Entry::va, SMMUTLB::Entry::valid, SMMUTLB::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, SMMUTLB::Entry::vmid, and SMMUTranslationProcess::TranslResult::writable.
Referenced by main().
resumeTransaction()
void SMMUTranslationProcess::resumeTransaction ()
Definition at line 117 of file smmu_v3_transl.cc.
References beginTransaction(), curTick(), DPRINTF, faultTick, System::isTimingMode(), SMMUTranslRequest::pkt, request, SMMUv3::runProcessTiming(), SMMUProcess::smmu, and SMMUv3::system.
sendEvent()
void SMMUTranslationProcess::sendEvent (Yield & yield, const SMMUEvent & ev) private
Definition at line 1301 of file smmu_v3_transl.cc.
References SMMUProcess::doWrite(), DPRINTF, E_BASE_ADDR_MASK, E_BASE_ENABLE_MASK, SMMURegs::eventq_base, SMMURegs::eventq_cons, SMMURegs::eventq_irq_cfg0, SMMURegs::eventq_irq_cfg1, SMMURegs::eventq_prod, SMMUEvent::flags, SMMUEvent::ipa, ArmISA::mask, panic, Q_BASE_ADDR_MASK, Q_BASE_SIZE_MASK, SMMUv3::regs, SMMUProcess::smmu, SMMUEvent::stag, SMMUEvent::streamId, SMMUEvent::substreamId, SMMUEvent::type, and SMMUEvent::va.
smmuTLBLookup()
bool SMMUTranslationProcess::smmuTLBLookup (Yield & yield, TranslResult & tr) private
Definition at line 379 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTranslationProcess::TranslContext::asid, context, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ARMArchTLB::lookup(), ARMArchTLB::Entry::pa, ARMArchTLB::Entry::permissions, request, SMMUProcess::smmu, SMMUv3::tlb, SMMUv3::tlbEnable, SMMUv3::tlbLat, SMMUv3::tlbSem, ARMArchTLB::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, and SMMUTranslationProcess::TranslResult::writable.
Referenced by smmuTranslation().
smmuTLBUpdate()
void SMMUTranslationProcess::smmuTLBUpdate (Yield & yield, const TranslResult & tr) private
Definition at line 479 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTranslationProcess::TranslContext::asid, ARMArchTLB::Entry::asid, context, SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, ARMArchTLB::Entry::pa, ARMArchTLB::Entry::permissions, request, SMMUProcess::smmu, ARMArchTLB::store(), SMMUv3::tlb, SMMUv3::tlbEnable, SMMUv3::tlbSem, ARMArchTLB::Entry::va, ARMArchTLB::Entry::valid, ARMArchTLB::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, ARMArchTLB::Entry::vmid, and SMMUTranslationProcess::TranslResult::writable.
Referenced by smmuTranslation().
smmuTranslation()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::smmuTranslation (Yield & yield) private
Definition at line 251 of file smmu_v3_transl.cc.
References SMMUTranslRequest::addr, bypass(), configCacheLookup(), configCacheUpdate(), context, curTick(), SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, findConfig(), SMMUv3::ifcSmmuLat, SMMUv3::ifcSmmuSem, SMMUv3::ptwSem, SMMUv3::ptwTimeDist, request, Stats::DistBase< Derived, Stor >::sample(), SMMUProcess::smmu, SMMUv3::smmuIfcLat, SMMUv3::smmuIfcSem, smmuTLBLookup(), smmuTLBUpdate(), SMMUTranslationProcess::TranslContext::stage1Enable, SMMUTranslationProcess::TranslContext::stage2Enable, translateStage1And2(), translateStage2(), and SMMUv3::transSem.
Referenced by main().
translateStage1And2()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::translateStage1And2 (Yield & yield, Addr addr) private
Definition at line 882 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUTranslationProcess::TranslContext::asid, context, DPRINTF, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, PageTableOps::firstLevel(), SMMUv3::getPageTableOps(), PageTableOps::lastLevel(), WalkCache::Entry::leaf, X86ISA::level, WalkCache::Entry::pa, WalkCache::Entry::permissions, SMMUProcess::smmu, SMMUTranslationProcess::TranslContext::stage1TranslGranule, SMMUTranslationProcess::TranslContext::stage2Enable, SMMUTranslationProcess::TranslContext::t0sz, translateStage2(), SMMUTranslationProcess::TranslContext::ttb0, WalkCache::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, walkCacheLookup(), walkStage1And2(), and SMMUTranslationProcess::TranslResult::writable.
Referenced by smmuTranslation().
translateStage2()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::translateStage2 (Yield & yield, Addr addr, bool final_tr) private
Definition at line 938 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, context, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, PageTableOps::firstLevel(), SMMUv3::getPageTableOps(), SMMUTranslationProcess::TranslContext::httb, IPACache::Entry::ipa, SMMUv3::ipaCache, SMMUv3::ipaCacheEnable, SMMUv3::ipaLat, IPACache::Entry::ipaMask, SMMUv3::ipaSem, PageTableOps::lastLevel(), WalkCache::Entry::leaf, X86ISA::level, IPACache::lookup(), IPACache::Entry::pa, WalkCache::Entry::pa, IPACache::Entry::permissions, WalkCache::Entry::permissions, SMMUTranslationProcess::TranslContext::s2t0sz, SMMUProcess::smmu, SMMUTranslationProcess::TranslContext::stage1Enable, SMMUTranslationProcess::TranslContext::stage2TranslGranule, IPACache::store(), IPACache::Entry::valid, WalkCache::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, IPACache::Entry::vmid, walkCacheLookup(), SMMUv3::walkCacheNonfinalEnable, walkStage2(), and SMMUTranslationProcess::TranslResult::writable.
Referenced by doReadCD(), smmuTranslation(), translateStage1And2(), and walkStage1And2().
walkCacheLookup()
void SMMUTranslationProcess::walkCacheLookup (Yield & yield, const WalkCache::Entry *& walkEntry, Addr addr, uint16_t asid, uint16_t vmid, unsigned stage, unsigned level) private
Definition at line 650 of file smmu_v3_transl.cc.
References ArmISA::asid, context, SMMUProcess::doDelay(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, SMMUv3::getPageTableOps(), X86ISA::level, WalkCache::lookup(), WalkCache::Entry::pa, SMMUProcess::smmu, SMMUTranslationProcess::TranslContext::stage1TranslGranule, SMMUTranslationProcess::TranslContext::stage2TranslGranule, SMMUv3::walkCache, SMMUv3::walkCacheEnable, SMMUv3::walkCacheS1Levels, SMMUv3::walkCacheS2Levels, SMMUv3::walkLat, PageTableOps::walkMask(), and SMMUv3::walkSem.
Referenced by translateStage1And2(), and translateStage2().
walkCacheUpdate()
void SMMUTranslationProcess::walkCacheUpdate (Yield & yield, Addr va, Addr vaMask, Addr pa, unsigned stage, unsigned level, bool leaf, uint8_t permissions) private
Definition at line 691 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslContext::asid, WalkCache::Entry::asid, context, SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, ArmISA::e, WalkCache::Entry::leaf, X86ISA::level, WalkCache::Entry::level, WalkCache::Entry::pa, ArmISA::pa, WalkCache::Entry::permissions, SMMUProcess::smmu, WalkCache::Entry::stage, WalkCache::store(), ArmISA::va, WalkCache::Entry::va, WalkCache::Entry::valid, WalkCache::Entry::vaMask, SMMUTranslationProcess::TranslContext::vmid, WalkCache::Entry::vmid, SMMUv3::walkCache, SMMUv3::walkCacheEnable, SMMUv3::walkCacheS1Levels, SMMUv3::walkCacheS2Levels, and SMMUv3::walkSem.
Referenced by walkStage1And2(), and walkStage2().
walkStage1And2()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::walkStage1And2 (Yield & yield, Addr addr, const PageTableOps * pt_ops, unsigned level, Addr walkPtr) private
Definition at line 732 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, combineTranslations(), context, SMMUv3::cycleSem, SMMUProcess::doDelay(), doReadPTE(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, FAULT_PERMISSION, FAULT_TRANSLATION, PageTableOps::index(), PageTableOps::isLeaf(), PageTableOps::isValid(), PageTableOps::isWritable(), SMMUTranslRequest::isWrite, PageTableOps::lastLevel(), X86ISA::level, PageTableOps::nextLevelPointer(), PageTableOps::pageMask(), request, SMMUProcess::smmu, SMMUTranslationProcess::TranslContext::stage2Enable, translateStage2(), walkCacheUpdate(), and PageTableOps::walkMask().
Referenced by translateStage1And2().
walkStage2()
SMMUTranslationProcess::TranslResult SMMUTranslationProcess::walkStage2 (Yield & yield, Addr addr, bool final_tr, const PageTableOps * pt_ops, unsigned level, Addr walkPtr) private
Definition at line 816 of file smmu_v3_transl.cc.
References SMMUTranslationProcess::TranslResult::addr, SMMUTranslationProcess::TranslResult::addrMask, SMMUv3::cycleSem, SMMUProcess::doDelay(), doReadPTE(), SMMUProcess::doSemaphoreDown(), SMMUProcess::doSemaphoreUp(), DPRINTF, SMMUTranslationProcess::TranslResult::fault, FAULT_NONE, FAULT_PERMISSION, FAULT_TRANSLATION, PageTableOps::index(), PageTableOps::isLeaf(), PageTableOps::isValid(), PageTableOps::isWritable(), SMMUTranslRequest::isWrite, PageTableOps::lastLevel(), X86ISA::level, PageTableOps::nextLevelPointer(), PageTableOps::pageMask(), request, SMMUProcess::smmu, SMMUv3::walkCacheNonfinalEnable, walkCacheUpdate(), PageTableOps::walkMask(), and SMMUTranslationProcess::TranslResult::writable.
Referenced by translateStage2().
Member Data Documentation
context
TranslContext SMMUTranslationProcess::context private
Definition at line 98 of file smmu_v3_transl.hh.
Referenced by doReadCD(), findConfig(), ifcTLBUpdate(), microTLBUpdate(), smmuTLBLookup(), smmuTLBUpdate(), smmuTranslation(), translateStage1And2(), translateStage2(), walkCacheLookup(), walkCacheUpdate(), and walkStage1And2().
faultTick
Tick SMMUTranslationProcess::faultTick private
Definition at line 101 of file smmu_v3_transl.hh.
Referenced by resumeTransaction().
ifc
SMMUv3SlaveInterface& SMMUTranslationProcess::ifc private
Definition at line 95 of file smmu_v3_transl.hh.
Referenced by completePrefetch(), completeTransaction(), hazard4kCheck(), hazard4kHold(), hazard4kRegister(), hazard4kRelease(), hazardIdHold(), hazardIdRegister(), hazardIdRelease(), ifcTLBLookup(), ifcTLBUpdate(), issuePrefetch(), main(), microTLBLookup(), microTLBUpdate(), SMMUTranslationProcess(), and ~SMMUTranslationProcess().
recvTick
Tick SMMUTranslationProcess::recvTick private
Definition at line 100 of file smmu_v3_transl.hh.
Referenced by completeTransaction(), and main().
request
SMMUTranslRequest SMMUTranslationProcess::request private
Definition at line 97 of file smmu_v3_transl.hh.
Referenced by beginTransaction(), completeTransaction(), configCacheLookup(), configCacheUpdate(), findConfig(), hazard4kCheck(), hazard4kHold(), hazard4kRegister(), hazard4kRelease(), hazardIdHold(), hazardIdRegister(), hazardIdRelease(), ifcTLBLookup(), ifcTLBUpdate(), issuePrefetch(), main(), microTLBLookup(), microTLBUpdate(), resumeTransaction(), smmuTLBLookup(), smmuTLBUpdate(), smmuTranslation(), walkStage1And2(), and walkStage2().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_transl.hh
dev/arm/smmu_v3_transl.cc