gem5: Kernel::Statistics Class Reference
Kernel::Statistics Class Reference
#include <kernel_stats.hh>
Public Member Functions
virtual ~Statistics ()
const std::string name () const
virtual void regStats (const std::string &name)
void arm ()
void quiesce ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
std::string myname
Stats::Scalar _arm
Stats::Scalar _quiesce
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 43 of file kernel_stats.hh.
Constructor & Destructor Documentation
~Statistics()
virtual Kernel::Statistics::~Statistics () inline virtual
Definition at line 53 of file kernel_stats.hh.
Member Function Documentation
arm()
void Kernel::Statistics::arm () inline
Definition at line 59 of file kernel_stats.hh.
Referenced by PseudoInst::arm().
name()
const std::string Kernel::Statistics::name () const inline
Definition at line 55 of file kernel_stats.hh.
References myname, and regStats().
Referenced by AlphaISA::Kernel::Statistics::Statistics().
quiesce()
void Kernel::Statistics::quiesce () inline
Definition at line 60 of file kernel_stats.hh.
Referenced by ThreadContext::quiesce(), ThreadContext::quiesceTick(), and SparcISA::ISA::setFSReg().
regStats()
virtual void Kernel::Statistics::regStats (const std::string & name) virtual
Reimplemented in AlphaISA::Kernel::Statistics.
Referenced by name(), and SimpleThread::regStats().
serialize()
void Kernel::Statistics::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 63 of file kernel_stats.hh.
Referenced by ThreadState::serialize().
unserialize()
void Kernel::Statistics::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 64 of file kernel_stats.hh.
Referenced by ThreadState::unserialize().
Member Data Documentation
_arm
Stats::Scalar Kernel::Statistics::_arm protected
Definition at line 49 of file kernel_stats.hh.
_quiesce
Stats::Scalar Kernel::Statistics::_quiesce protected
Definition at line 50 of file kernel_stats.hh.
myname
std::string Kernel::Statistics::myname protected
Definition at line 46 of file kernel_stats.hh.
Referenced by name().
The documentation for this class was generated from the following file:
kern/kernel_stats.hh