gem5: BaseCache::CacheReqPacketQueue Class Reference
BaseCache::CacheReqPacketQueue Class Reference
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
#include <base.hh>
Public Member Functions
CacheReqPacketQueue (BaseCache &cache, MasterPort &port, SnoopRespPacketQueue &snoop_resp_queue, const std::string &label)
virtual void sendDeferredPacket ()
Override the normal sendDeferredPacket and do not only consider the transmit list (used for responses), but also requests.
bool checkConflictingSnoop (const PacketPtr pkt)
Check if there is a conflicting snoop response about to be send out, and if so simply stall any requests, and schedule a send event at the same time as the next snoop response is being sent out.
Public Member Functions inherited from ReqPacketQueue
ReqPacketQueue (EventManager &_em, MasterPort &_masterPort, const std::string _label="ReqPacketQueue")
Create a request packet queue, linked to an event manager, a master port, and a label that will be used for functional print request packets.
virtual ~ReqPacketQueue ()
const std::string name () const
Provide a name to simplify debugging.
bool sendTiming (PacketPtr pkt)
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
Public Member Functions inherited from PacketQueue
size_t size () const
Get the size of the queue.
Tick deferredPacketReadyTime () const
Get the next packet ready time.
bool checkConflict (const PacketPtr pkt, const int blk_size) const
Check if a packet corresponding to the same address exists in the queue.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
void schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
void schedSendTiming (PacketPtr pkt, Tick when)
Add a packet to the transmit list, and schedule a send event.
void retry ()
Retry sending a packet from the queue.
void disableSanityCheck ()
This allows a user to explicitly disable the sanity check on the size of the transmitList, which is enabled by default.
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Protected Attributes
BaseCache & cache
SnoopRespPacketQueue & snoopRespQueue
Protected Attributes inherited from ReqPacketQueue
MasterPort & masterPort
Protected Attributes inherited from PacketQueue
const std::string label
Label to use for print request packets label stack.
bool waitingOnRetry
Remember whether we're awaiting a retry.
Additional Inherited Members
Protected Member Functions inherited from PacketQueue
bool deferredPacketReady () const
Check whether we have a packet ready to go on the transmit list.
PacketQueue (EventManager &_em, const std::string &_label, const std::string &_sendEventName, bool force_order=false, bool disable_sanity_check=false)
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
virtual ~PacketQueue ()
Virtual desctructor since the class may be used as a base class.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Static Protected Member Functions inherited from ReqPacketQueue
static const std::string name (const MasterPort &masterPort, const std::string &label)
Detailed Description
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
This queue has a pointer to our specific cache implementation and is used by the MemSidePort.
Definition at line 163 of file base.hh.
Constructor & Destructor Documentation
CacheReqPacketQueue()
BaseCache::CacheReqPacketQueue::CacheReqPacketQueue (BaseCache & cache, MasterPort & port, SnoopRespPacketQueue & snoop_resp_queue, const std::string & label) inline
Definition at line 173 of file base.hh.
Member Function Documentation
checkConflictingSnoop()
bool BaseCache::CacheReqPacketQueue::checkConflictingSnoop (const PacketPtr pkt) inline
Check if there is a conflicting snoop response about to be send out, and if so simply stall any requests, and schedule a send event at the same time as the next snoop response is being sent out.
Parameters
pkt The packet to check for conflicts against.
Definition at line 194 of file base.hh.
References BaseCache::blkSize, PacketQueue::checkConflict(), PacketQueue::deferredPacketReadyTime(), DPRINTF, and BaseCache::CacheMasterPort::schedSendEvent().
sendDeferredPacket()
void BaseCache::CacheReqPacketQueue::sendDeferredPacket () virtual
Override the normal sendDeferredPacket and do not only consider the transmit list (used for responses), but also requests.
Reimplemented from PacketQueue.
Definition at line 2442 of file base.cc.
References BaseCache::CpuSidePort::cache, BaseCache::getNextQueueEntry(), QueueEntry::getTarget(), MaxTick, BaseCache::nextQueueReadyTime(), QueueEntry::Target::pkt, and QueueEntry::sendPacket().
Member Data Documentation
cache
BaseCache& BaseCache::CacheReqPacketQueue::cache protected
Definition at line 168 of file base.hh.
snoopRespQueue
SnoopRespPacketQueue& BaseCache::CacheReqPacketQueue::snoopRespQueue protected
Definition at line 169 of file base.hh.
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc