gem5: sc_core::sc_mempool Class Reference
sc_core::sc_mempool Class Reference
#include <sc_mempool.hh>
Static Public Member Functions
static void * allocate (std::size_t sz)
static void release (void *p, std::size_t sz)
static void display_statistics ()
Detailed Description
Definition at line 41 of file sc_mempool.hh.
Member Function Documentation
allocate()
void * sc_core::sc_mempool::allocate (std::size_t sz) static
Definition at line 37 of file sc_mempool.cc.
Referenced by sc_core::sc_mpobject::operator new(), sc_dt::sc_logic::operator new(), sc_core::sc_mpobject::operator new [](), and sc_dt::sc_logic::operator new []().
display_statistics()
void sc_core::sc_mempool::display_statistics () static
Definition at line 47 of file sc_mempool.cc.
References warn.
release()
void sc_core::sc_mempool::release (void * p, std::size_t sz) static
Definition at line 42 of file sc_mempool.cc.
References MipsISA::p.
Referenced by sc_core::sc_mpobject::operator delete(), sc_dt::sc_logic::operator delete(), sc_core::sc_mpobject::operator delete [](), and sc_dt::sc_logic::operator delete []().
The documentation for this class was generated from the following files:
systemc/ext/dt/sc_mempool.hh
systemc/dt/sc_mempool.cc