gem5: ArmISA::Decoder Class Reference
ArmISA::Decoder Class Reference
#include <decoder.hh>
Public Member Functions
Decoder (ISA *isa=nullptr)
void reset ()
Reset the decoders internal state.
bool needMoreBytes () const
Can the decoder accept more data?
bool instReady () const
Is an instruction ready to be decoded?
void moreBytes (const PCState &pc, Addr fetchPC, MachInst inst)
Feed data to the decoder.
StaticInstPtr decode (ArmISA::PCState &pc)
Decode an instruction or fetch it from the code cache.
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a pre-decoded machine instruction.
StaticInstPtr decodeInst (ExtMachInst mach_inst)
Decode a machine instruction without calling the cache.
void takeOverFrom (Decoder *old)
Take over the state from an old decoder when switching CPUs.
void setContext (FPSCR fpscr)
void setSveLen (uint8_t len)
Protected Member Functions
void process ()
Pre-decode an instruction from the current state of the decoder.
void consumeBytes (int numBytes)
Consume bytes by moving the offset into the data word and sanity check the results.
Protected Attributes
ExtMachInst emi
MachInst data
bool bigThumb
bool instDone
bool outOfBytes
int offset
bool foundIt
ITSTATE itBits
int fpscrLen
int fpscrStride
int sveLen
SVE vector length, encoded in the same format as the ZCR_EL<x>.LEN bitfields.
Enums::DecoderFlavour decoderFlavour
Static Protected Attributes
static GenericISA::BasicDecodeCache defaultCache
A cache of decoded instruction objects.
Detailed Description
Definition at line 59 of file decoder.hh.
Constructor & Destructor Documentation
Decoder()
ArmISA::Decoder::Decoder (ISA * isa = nullptr)
Definition at line 57 of file decoder.cc.
References ArmISA::ISA::getCurSveVecLenInBitsAtReset(), reset(), and sveLen.
Member Function Documentation
consumeBytes()
void ArmISA::Decoder::consumeBytes (int numBytes) protected
Consume bytes by moving the offset into the data word and sanity check the results.
Definition at line 146 of file decoder.cc.
References emi, offset, and outOfBytes.
Referenced by process().
decode() [1/2]
StaticInstPtr ArmISA::Decoder::decode (ArmISA::PCState & pc)
Decode an instruction or fetch it from the code cache.
This method decodes the currently pending pre-decoded instruction. Data must be fed to the decoder using moreBytes() until instReady() is true before calling this method.
Parameters
pc Instruction pointer that we are decoding.
Returns
A pointer to a static instruction or NULL if the decoder isn't ready (see instReady()).
Definition at line 174 of file decoder.cc.
References emi, foundIt, instDone, and itBits.
Referenced by instReady().
decode() [2/2]
StaticInstPtr ArmISA::Decoder::decode (ExtMachInst mach_inst, Addr addr) inline
Decode a pre-decoded machine instruction.
This method takes a pre-decoded instruction as its argument. It should typically not be called directly.
Parameters
mach_inst A pre-decoded instruction
Return values
A pointer to the corresponding StaticInst object.
Definition at line 173 of file decoder.hh.
References GenericISA::BasicDecodeCache::decode(), and decodeInst().
decodeInst()
StaticInstPtr ArmISA::Decoder::decodeInst (ExtMachInst mach_inst)
Decode a machine instruction without calling the cache.
Note
The implementation of this method is generated by the ISA parser script.
This method takes a pre-decoded instruction as its argument. It should typically not be called directly.
Parameters
mach_inst The binary instruction to decode.
Return values
A pointer to the corresponding StaticInst object.
Referenced by decode().
instReady()
bool ArmISA::Decoder::instReady () const inline
Is an instruction ready to be decoded?
CPU models call this method to determine if decode() will return a new instruction on the next call. It typically only returns false if the decoder hasn't received enough data to decode a full instruction.
Definition at line 121 of file decoder.hh.
References decode(), instDone, moreBytes(), and MipsISA::pc.
moreBytes()
void ArmISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst inst)
Feed data to the decoder.
A CPU model uses this interface to load instruction data into the decoder. Once enough data has been loaded (check with instReady()), a decoded instruction can be retrieved using decode(ArmISA::PCState).
This method is intended to support both fixed-length and variable-length instructions. Instruction data is fetch in MachInst blocks (which correspond to the size of a typical insturction). The method might need to be called multiple times if the instruction spans multiple blocks, in that case needMoreBytes() will return true and instReady() will return false.
The fetchPC parameter is used to indicate where in memory the instruction was fetched from. This is should be the same address as the pc. If fetching multiple blocks, it indicates where subsequent blocks are fetched from (pc + n * sizeof(MachInst)).
Parameters
pc Instruction pointer that we are decoding.
fetchPC The address this chunk was fetched from.
inst Raw instruction data.
Definition at line 155 of file decoder.cc.
References data, emi, fpscrLen, fpscrStride, letoh(), offset, ArmISA::OK, outOfBytes, process(), sveLen, and ArmISA::UNALIGNED.
Referenced by instReady().
needMoreBytes()
bool ArmISA::Decoder::needMoreBytes () const inline
Can the decoder accept more data?
A CPU model uses this method to determine if the decoder can accept more data. Note that an instruction can be ready (see instReady() even if this method returns true.
Definition at line 111 of file decoder.hh.
References outOfBytes.
process()
void ArmISA::Decoder::process () protected
Pre-decode an instruction from the current state of the decoder.
Definition at line 79 of file decoder.cc.
References bigThumb, bits(), ArmISA::COND_UC, consumeBytes(), data, DPRINTF, emi, foundIt, instDone, itBits, and offset.
Referenced by moreBytes().
reset()
void ArmISA::Decoder::reset ()
Reset the decoders internal state.
Definition at line 68 of file decoder.cc.
References bigThumb, emi, foundIt, instDone, offset, and outOfBytes.
Referenced by Decoder().
setContext()
void ArmISA::Decoder::setContext (FPSCR fpscr) inline
Definition at line 201 of file decoder.hh.
setSveLen()
void ArmISA::Decoder::setSveLen (uint8_t len) inline
Definition at line 207 of file decoder.hh.
References ArmISA::len.
takeOverFrom()
void ArmISA::Decoder::takeOverFrom (Decoder * old) inline
Take over the state from an old decoder when switching CPUs.
Parameters
old Decoder used in old CPU
Definition at line 197 of file decoder.hh.
Member Data Documentation
bigThumb
bool ArmISA::Decoder::bigThumb protected
Definition at line 65 of file decoder.hh.
Referenced by process(), and reset().
data
MachInst ArmISA::Decoder::data protected
Definition at line 64 of file decoder.hh.
Referenced by moreBytes(), and process().
decoderFlavour
Enums::DecoderFlavour ArmISA::Decoder::decoderFlavour protected
Definition at line 81 of file decoder.hh.
defaultCache
GenericISA::BasicDecodeCache ArmISA::Decoder::defaultCache static protected
A cache of decoded instruction objects.
Definition at line 84 of file decoder.hh.
emi
ExtMachInst ArmISA::Decoder::emi protected
Definition at line 63 of file decoder.hh.
Referenced by consumeBytes(), decode(), moreBytes(), process(), and reset().
foundIt
bool ArmISA::Decoder::foundIt protected
Definition at line 69 of file decoder.hh.
Referenced by decode(), process(), and reset().
fpscrLen
int ArmISA::Decoder::fpscrLen protected
Definition at line 72 of file decoder.hh.
Referenced by moreBytes().
fpscrStride
int ArmISA::Decoder::fpscrStride protected
Definition at line 73 of file decoder.hh.
Referenced by moreBytes().
instDone
bool ArmISA::Decoder::instDone protected
Definition at line 66 of file decoder.hh.
Referenced by decode(), instReady(), process(), and reset().
itBits
ITSTATE ArmISA::Decoder::itBits protected
Definition at line 70 of file decoder.hh.
Referenced by decode(), and process().
offset
int ArmISA::Decoder::offset protected
Definition at line 68 of file decoder.hh.
Referenced by consumeBytes(), moreBytes(), process(), and reset().
outOfBytes
bool ArmISA::Decoder::outOfBytes protected
Definition at line 67 of file decoder.hh.
Referenced by consumeBytes(), moreBytes(), needMoreBytes(), and reset().
sveLen
int ArmISA::Decoder::sveLen protected
SVE vector length, encoded in the same format as the ZCR_EL<x>.LEN bitfields.
Definition at line 79 of file decoder.hh.
Referenced by Decoder(), and moreBytes().
The documentation for this class was generated from the following files:
arch/arm/decoder.hh
arch/arm/decoder.cc