gem5: sc_core::sc_event_or_expr Class Reference
sc_core::sc_event_or_expr Class Reference
#include <sc_event.hh>
Public Member Functions
sc_event_or_expr (sc_event_or_expr const &e)
operator const sc_event_or_list & () const
void insert (sc_event const &e) const
void insert (sc_event_or_list const &eol) const
~sc_event_or_expr ()
Private Member Functions
sc_event_or_expr ()
Private Attributes
sc_event_or_list * list
Friends
class sc_event_or_list
class sc_event
Detailed Description
Definition at line 149 of file sc_event.hh.
Constructor & Destructor Documentation
sc_event_or_expr() [1/2]
sc_core::sc_event_or_expr::sc_event_or_expr (sc_event_or_expr const & e)
Definition at line 264 of file sc_event.cc.
References list.
~sc_event_or_expr()
sc_core::sc_event_or_expr::~sc_event_or_expr ()
Definition at line 291 of file sc_event.cc.
References list.
sc_event_or_expr() [2/2]
sc_core::sc_event_or_expr::sc_event_or_expr () private
Definition at line 293 of file sc_event.cc.
Member Function Documentation
insert() [1/2]
void sc_core::sc_event_or_expr::insert (sc_event const & e) const
Definition at line 278 of file sc_event.cc.
References sc_core::sc_event_or_list::insert(), and list.
Referenced by sc_core::sc_event_or_list::operator|(), sc_core::sc_event::operator|(), and sc_core::operator|().
insert() [2/2]
void sc_core::sc_event_or_expr::insert (sc_event_or_list const & eol) const
Definition at line 285 of file sc_event.cc.
References sc_core::sc_event_or_list::insert(), and list.
operator const sc_event_or_list &()
sc_core::sc_event_or_expr::operator const sc_event_or_list & () const
Definition at line 270 of file sc_event.cc.
References list.
Friends And Related Function Documentation
sc_event
friend class sc_event friend
Definition at line 162 of file sc_event.hh.
sc_event_or_list
friend class sc_event_or_list friend
Definition at line 161 of file sc_event.hh.
Member Data Documentation
list
sc_event_or_list* sc_core::sc_event_or_expr::list mutable private
Definition at line 165 of file sc_event.hh.
Referenced by insert(), operator const sc_event_or_list &(), sc_event_or_expr(), and ~sc_event_or_expr().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_event.hh
systemc/core/sc_event.cc