gem5: ArmISA::Stage2LookUp Class Reference
ArmISA::Stage2LookUp Class Reference
#include <stage2_lookup.hh>
Public Member Functions
Stage2LookUp (TLB *s1Tlb, TLB *s2Tlb, TlbEntry s1Te, const RequestPtr &_req, TLB::Translation *_transState, BaseTLB::Mode _mode, bool _timing, bool _functional, TLB::ArmTranslationType _tranType)
Fault getTe (ThreadContext *tc, TlbEntry *destTe)
void mergeTe (const RequestPtr &req, BaseTLB::Mode mode)
void setSelfDelete ()
bool isComplete () const
void markDelayed ()
Signal that the translation has been delayed due to a hw page table walk.
void finish (const Fault &fault, const RequestPtr &req, ThreadContext *tc, BaseTLB::Mode mode)
Public Member Functions inherited from BaseTLB::Translation
virtual ~Translation ()
virtual bool squashed () const
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
Private Attributes
TLB * stage1Tlb
TLB * stage2Tlb
TlbEntry stage1Te
RequestPtr s1Req
TLB::Translation * transState
BaseTLB::Mode mode
bool timing
bool functional
TLB::ArmTranslationType tranType
TlbEntry * stage2Te
RequestPtr req
Fault fault
bool complete
bool selfDelete
Detailed Description
Definition at line 58 of file stage2_lookup.hh.
Constructor & Destructor Documentation
Stage2LookUp()
ArmISA::Stage2LookUp::Stage2LookUp (TLB * s1Tlb, TLB * s2Tlb, TlbEntry s1Te, const RequestPtr & _req, TLB::Translation * _transState, BaseTLB::Mode _mode, bool _timing, bool _functional, TLB::ArmTranslationType _tranType) inline
Definition at line 77 of file stage2_lookup.hh.
References getTe(), mergeTe(), and ArmISA::TlbEntry::pAddr().
Member Function Documentation
finish()
void Stage2LookUp::finish (const Fault & fault, const RequestPtr & req, ThreadContext * tc, BaseTLB::Mode mode) virtual
Implements BaseTLB::Translation.
Definition at line 179 of file stage2_lookup.cc.
References fault, BaseTLB::Translation::finish(), functional, ArmISA::TLB::getTE(), mergeTe(), NoFault, s1Req, selfDelete, stage1Tlb, stage2Te, stage2Tlb, timing, ArmISA::TLB::translateComplete(), transState, and tranType.
Referenced by markDelayed().
getTe()
Fault Stage2LookUp::getTe (ThreadContext * tc, TlbEntry * destTe)
Definition at line 57 of file stage2_lookup.cc.
References ArmISA::TLB::checkPermissions(), ArmISA::TLB::checkPermissions64(), ArmISA::EL2, ArmISA::ELIs64(), fault, functional, ArmISA::TLB::getTE(), mergeTe(), mode, NoFault, req, stage1Te, stage2Te, stage2Tlb, timing, and tranType.
Referenced by ArmISA::TLB::getResultTe(), and Stage2LookUp().
isComplete()
bool ArmISA::Stage2LookUp::isComplete () const inline
Definition at line 96 of file stage2_lookup.hh.
References complete.
Referenced by ArmISA::TLB::getResultTe().
markDelayed()
void ArmISA::Stage2LookUp::markDelayed () inline virtual
Signal that the translation has been delayed due to a hw page table walk.
Implements BaseTLB::Translation.
Definition at line 98 of file stage2_lookup.hh.
References finish().
mergeTe()
void Stage2LookUp::mergeTe (const RequestPtr & req, BaseTLB::Mode mode)
Definition at line 82 of file stage2_lookup.cc.
References complete, ArmISA::TlbEntry::Device, fault, ArmISA::TlbEntry::innerAttrs, ArmISA::mask, ArmISA::TlbEntry::mtype, ArmISA::TlbEntry::N, NoFault, ArmISA::TlbEntry::nonCacheable, ArmISA::TlbEntry::Normal, ArmISA::TlbEntry::outerAttrs, ArmISA::TlbEntry::outerShareable, ArmISA::ArmFault::OVA, ArmISA::pa, ArmISA::TlbEntry::pfn, s1Req, ArmISA::TlbEntry::shareable, ArmISA::TlbEntry::size, stage1Te, stage2Te, ArmISA::TlbEntry::StronglyOrdered, ArmISA::TlbEntry::updateAttributes(), ArmISA::TlbEntry::vpn, and ArmISA::TlbEntry::xn.
Referenced by finish(), getTe(), and Stage2LookUp().
setSelfDelete()
void ArmISA::Stage2LookUp::setSelfDelete () inline
Definition at line 94 of file stage2_lookup.hh.
Referenced by ArmISA::TLB::getResultTe().
Member Data Documentation
complete
bool ArmISA::Stage2LookUp::complete private
Definition at line 73 of file stage2_lookup.hh.
Referenced by isComplete(), and mergeTe().
fault
Fault ArmISA::Stage2LookUp::fault private
Definition at line 72 of file stage2_lookup.hh.
Referenced by finish(), getTe(), and mergeTe().
functional
bool ArmISA::Stage2LookUp::functional private
Definition at line 68 of file stage2_lookup.hh.
Referenced by finish(), and getTe().
mode
BaseTLB::Mode ArmISA::Stage2LookUp::mode private
Definition at line 66 of file stage2_lookup.hh.
Referenced by getTe().
req
RequestPtr ArmISA::Stage2LookUp::req private
Definition at line 71 of file stage2_lookup.hh.
Referenced by getTe().
s1Req
RequestPtr ArmISA::Stage2LookUp::s1Req private
Definition at line 64 of file stage2_lookup.hh.
Referenced by finish(), and mergeTe().
selfDelete
bool ArmISA::Stage2LookUp::selfDelete private
Definition at line 74 of file stage2_lookup.hh.
Referenced by finish().
stage1Te
TlbEntry ArmISA::Stage2LookUp::stage1Te private
Definition at line 63 of file stage2_lookup.hh.
Referenced by getTe(), and mergeTe().
stage1Tlb
TLB* ArmISA::Stage2LookUp::stage1Tlb private
Definition at line 61 of file stage2_lookup.hh.
Referenced by finish().
stage2Te
TlbEntry* ArmISA::Stage2LookUp::stage2Te private
Definition at line 70 of file stage2_lookup.hh.
Referenced by finish(), getTe(), and mergeTe().
stage2Tlb
TLB* ArmISA::Stage2LookUp::stage2Tlb private
Definition at line 62 of file stage2_lookup.hh.
Referenced by finish(), and getTe().
timing
bool ArmISA::Stage2LookUp::timing private
Definition at line 67 of file stage2_lookup.hh.
Referenced by finish(), and getTe().
transState
TLB::Translation* ArmISA::Stage2LookUp::transState private
Definition at line 65 of file stage2_lookup.hh.
Referenced by finish().
tranType
TLB::ArmTranslationType ArmISA::Stage2LookUp::tranType private
Definition at line 69 of file stage2_lookup.hh.
Referenced by finish(), and getTe().
The documentation for this class was generated from the following files:
arch/arm/stage2_lookup.hh
arch/arm/stage2_lookup.cc