gem5: ElfObject Class Reference
ElfObject Class Reference
#include <elf_object.hh>
Public Member Functions
ElfObject (ImageFileDataPtr ifd)
~ElfObject ()
MemoryImage buildImage () const override
bool loadAllSymbols (SymbolTable *symtab, Addr base=0, Addr offset=0, Addr addr_mask=MaxAddr) override
bool loadGlobalSymbols (SymbolTable *symtab, Addr base=0, Addr offset=0, Addr addr_mask=MaxAddr) override
bool loadLocalSymbols (SymbolTable *symtab, Addr base=0, Addr offset=0, Addr addr_mask=MaxAddr) override
bool loadWeakSymbols (SymbolTable *symtab, Addr base=0, Addr offset=0, Addr addr_mask=MaxAddr) override
ObjectFile * getInterpreter () const override
Addr bias () const override
bool relocatable () const override
Addr mapSize () const override
void updateBias (Addr bias_addr) override
bool hasTLS () override
Addr programHeaderTable ()
uint16_t programHeaderSize ()
uint16_t programHeaderCount ()
Public Member Functions inherited from ObjectFile
virtual ~ObjectFile ()
Arch getArch () const
OpSys getOpSys () const
Addr entryPoint () const
Protected Member Functions
void determineArch ()
void determineOpSys ()
void handleLoadableSegment (GElf_Phdr phdr, int seg_num)
bool loadSomeSymbols (SymbolTable *symtab, int binding, Addr mask, Addr base, Addr offset)
Helper functions for loadGlobalSymbols() and loadLocalSymbols().
void getSections ()
bool sectionExists (std::string sec)
Protected Member Functions inherited from ObjectFile
ObjectFile (ImageFileDataPtr ifd)
Protected Member Functions inherited from ImageFile
ImageFile (ImageFileDataPtr data)
virtual ~ImageFile ()
Protected Attributes
Elf * elf
GElf_Ehdr ehdr
Addr _programHeaderTable = 0
uint16_t _programHeaderSize = 0
uint16_t _programHeaderCount = 0
std::set< std::string > sectionNames
ElfObject * interpreter = nullptr
Addr ldBias = 0
bool relocate = true
Addr ldMin = MaxAddr
Addr ldMax = MaxAddr
MemoryImage image
Protected Attributes inherited from ObjectFile
Arch arch = UnknownArch
OpSys opSys = UnknownOpSys
Addr entry = 0
Protected Attributes inherited from ImageFile
ImageFileDataPtr imageData
Additional Inherited Members
Public Types inherited from ObjectFile
enum Arch {
UnknownArch, Alpha, SPARC64, SPARC32,
Mips, X86_64, I386, Arm64,
Arm, Thumb, Power, Riscv64,
Riscv32
}
enum OpSys {
UnknownOpSys, Tru64, Linux, Solaris,
LinuxArmOABI, FreeBSD
}
Detailed Description
Definition at line 58 of file elf_object.hh.
Constructor & Destructor Documentation
ElfObject()
ElfObject::ElfObject (ImageFileDataPtr ifd)
Definition at line 96 of file elf_object.cc.
References _programHeaderCount, _programHeaderSize, createObjectFile(), determineArch(), determineOpSys(), DPRINTFR, ehdr, elf, ObjectFile::entry, handleLoadableSegment(), ArmISA::i, image, ImageFile::imageData, interpreter, M5_VAR_USED, panic, X86ISA::seg, MemoryImage::segments(), and warn_if.
~ElfObject()
ElfObject::~ElfObject ()
Definition at line 283 of file elf_object.cc.
References elf.
Member Function Documentation
bias()
Addr ElfObject::bias () const inline override virtual
Reimplemented from ObjectFile.
Definition at line 119 of file elf_object.hh.
buildImage()
MemoryImage ElfObject::buildImage () const inline override virtual
Implements ImageFile.
Definition at line 106 of file elf_object.hh.
References X86ISA::base, MaxAddr, and ArmISA::offset.
determineArch()
void ElfObject::determineArch () protected
Definition at line 141 of file elf_object.cc.
References ObjectFile::Alpha, ObjectFile::arch, ObjectFile::Arm, ObjectFile::Arm64, bits(), ehdr, fatal, ObjectFile::I386, ObjectFile::Mips, ObjectFile::Power, ObjectFile::Riscv32, ObjectFile::Riscv64, ObjectFile::SPARC32, ObjectFile::SPARC64, ObjectFile::Thumb, warn, and ObjectFile::X86_64.
Referenced by ElfObject().
determineOpSys()
void ElfObject::determineOpSys () protected
Definition at line 193 of file elf_object.cc.
References ehdr, elf, fatal, ObjectFile::FreeBSD, htobe(), htole(), ObjectFile::Linux, ObjectFile::LinuxArmOABI, ObjectFile::opSys, ObjectFile::Solaris, ObjectFile::Tru64, and ObjectFile::UnknownOpSys.
Referenced by ElfObject().
getInterpreter()
ObjectFile* ElfObject::getInterpreter () const inline override virtual
Reimplemented from ObjectFile.
Definition at line 118 of file elf_object.hh.
getSections()
void ElfObject::getSections () protected
Definition at line 389 of file elf_object.cc.
References ehdr, elf, ImageFile::imageData, panic, and sectionNames.
Referenced by sectionExists().
handleLoadableSegment()
void ElfObject::handleLoadableSegment (GElf_Phdr phdr, int seg_num) protected
Definition at line 256 of file elf_object.cc.
References _programHeaderTable, MemoryImage::addSegment(), ehdr, image, ImageFile::imageData, name(), and sc_dt::to_string().
Referenced by ElfObject().
hasTLS()
bool ElfObject::hasTLS () inline override virtual
Reimplemented from ObjectFile.
Definition at line 124 of file elf_object.hh.
loadAllSymbols()
bool ElfObject::loadAllSymbols (SymbolTable * symtab, Addr base = 0, Addr offset = 0, Addr addr_mask = MaxAddr) override virtual
Reimplemented from ObjectFile.
Definition at line 347 of file elf_object.cc.
References loadGlobalSymbols(), loadLocalSymbols(), and loadWeakSymbols().
loadGlobalSymbols()
bool ElfObject::loadGlobalSymbols (SymbolTable * symtab, Addr base = 0, Addr offset = 0, Addr addr_mask = MaxAddr) override virtual
Reimplemented from ObjectFile.
Definition at line 356 of file elf_object.cc.
References interpreter, and loadSomeSymbols().
Referenced by loadAllSymbols().
loadLocalSymbols()
bool ElfObject::loadLocalSymbols (SymbolTable * symtab, Addr base = 0, Addr offset = 0, Addr addr_mask = MaxAddr) override virtual
Reimplemented from ObjectFile.
Definition at line 367 of file elf_object.cc.
References interpreter, and loadSomeSymbols().
Referenced by loadAllSymbols().
loadSomeSymbols()
bool ElfObject::loadSomeSymbols (SymbolTable * symtab, int binding, Addr mask, Addr base, Addr offset) protected
Helper functions for loadGlobalSymbols() and loadLocalSymbols().
Definition at line 289 of file elf_object.cc.
References X86ISA::count, data, DPRINTF, elf, ArmISA::i, ImageFile::imageData, SymbolTable::insert(), ArmISA::offset, and panic.
Referenced by loadGlobalSymbols(), loadLocalSymbols(), and loadWeakSymbols().
loadWeakSymbols()
bool ElfObject::loadWeakSymbols (SymbolTable * symtab, Addr base = 0, Addr offset = 0, Addr addr_mask = MaxAddr) override virtual
Reimplemented from ObjectFile.
Definition at line 378 of file elf_object.cc.
References interpreter, and loadSomeSymbols().
Referenced by loadAllSymbols().
mapSize()
Addr ElfObject::mapSize () const inline override virtual
Reimplemented from ObjectFile.
Definition at line 121 of file elf_object.hh.
programHeaderCount()
uint16_t ElfObject::programHeaderCount () inline
Definition at line 128 of file elf_object.hh.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), and X86ISA::X86Process::argsInit().
programHeaderSize()
uint16_t ElfObject::programHeaderSize () inline
Definition at line 127 of file elf_object.hh.
Referenced by MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), and X86ISA::X86Process::argsInit().
programHeaderTable()
Addr ElfObject::programHeaderTable () inline
Definition at line 126 of file elf_object.hh.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), and X86ISA::X86Process::argsInit().
relocatable()
bool ElfObject::relocatable () const inline override virtual
Reimplemented from ObjectFile.
Definition at line 120 of file elf_object.hh.
sectionExists()
bool ElfObject::sectionExists (std::string sec) protected
Definition at line 425 of file elf_object.cc.
References getSections(), and sectionNames.
updateBias()
void ElfObject::updateBias (Addr bias_addr) override virtual
Reimplemented from ObjectFile.
Definition at line 435 of file elf_object.cc.
References ObjectFile::entry, image, ldBias, and MemoryImage::offset().
Member Data Documentation
_programHeaderCount
uint16_t ElfObject::_programHeaderCount = 0 protected
Definition at line 72 of file elf_object.hh.
Referenced by ElfObject().
_programHeaderSize
uint16_t ElfObject::_programHeaderSize = 0 protected
Definition at line 71 of file elf_object.hh.
Referenced by ElfObject().
_programHeaderTable
Addr ElfObject::_programHeaderTable = 0 protected
Definition at line 70 of file elf_object.hh.
Referenced by handleLoadableSegment().
ehdr
GElf_Ehdr ElfObject::ehdr protected
Definition at line 62 of file elf_object.hh.
Referenced by determineArch(), determineOpSys(), ElfObject(), getSections(), and handleLoadableSegment().
elf
Elf* ElfObject::elf protected
Definition at line 61 of file elf_object.hh.
Referenced by determineOpSys(), ElfObject(), getSections(), loadSomeSymbols(), and ~ElfObject().
image
MemoryImage ElfObject::image protected
Definition at line 100 of file elf_object.hh.
Referenced by ElfObject(), handleLoadableSegment(), and updateBias().
interpreter
ElfObject* ElfObject::interpreter = nullptr protected
Definition at line 75 of file elf_object.hh.
Referenced by ElfObject(), loadGlobalSymbols(), loadLocalSymbols(), and loadWeakSymbols().
ldBias
Addr ElfObject::ldBias = 0 protected
Definition at line 80 of file elf_object.hh.
Referenced by updateBias().
ldMax
Addr ElfObject::ldMax = MaxAddr protected
Definition at line 91 of file elf_object.hh.
ldMin
Addr ElfObject::ldMin = MaxAddr protected
Definition at line 90 of file elf_object.hh.
relocate
bool ElfObject::relocate = true protected
Definition at line 86 of file elf_object.hh.
sectionNames
std::set<std::string> ElfObject::sectionNames protected
Definition at line 73 of file elf_object.hh.
Referenced by getSections(), and sectionExists().
The documentation for this class was generated from the following files:
base/loader/elf_object.hh
base/loader/elf_object.cc