gem5: FALRU Class Reference
FALRU Class Reference
A fully associative LRU cache.
#include <fa_lru.hh>
Classes
class CacheTracking
Mechanism that allows us to simultaneously collect miss statistics for multiple caches.
struct PairHash
Hash table type mapping addresses to cache block pointers.
Public Types
typedef FALRUBlk BlkType
Typedef the block type used in this class.
typedef FALRUParams Params
Public Types inherited from BaseTags
typedef BaseTagsParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
FALRU (const Params *p)
Construct and initialize this cache tagstore.
~FALRU ()
void tagsInit () override
Initialize blocks as FALRUBlk instances.
void regStats () override
Register the stats for this object.
void invalidate (CacheBlk *blk) override
Invalidate a cache block.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat, CachesMask *in_cache_mask)
Access block and update replacement data.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat) override
Just a wrapper of above function to conform with the base interface.
CacheBlk * findBlock (Addr addr, bool is_secure) const override
Find the block in the cache, do not update the replacement data.
ReplaceableEntry * findBlockBySetAndWay (int set, int way) const override
Find a block given set and way.
CacheBlk * findVictim (Addr addr, const bool is_secure, const std::size_t size, std::vector< CacheBlk *> &evict_blks) const override
Find replacement victim based on address.
void insertBlock (const PacketPtr pkt, CacheBlk *blk) override
Insert the new block into the cache and update replacement data.
Addr extractTag (Addr addr) const override
Generate the tag from the addres.
Addr regenerateBlkAddr (const CacheBlk *blk) const override
Regenerate the block address from the tag.
void forEachBlk (std::function< void(CacheBlk &)> visitor) override
Visit each block in the tags and apply a visitor.
bool anyBlk (std::function< bool(CacheBlk &)> visitor) override
Find if any of the blocks satisfies a condition.
Public Member Functions inherited from BaseTags
BaseTags (const Params *p)
virtual ~BaseTags ()
Destructor.
void cleanupRefs ()
Average in the reference count for valid blocks when the simulation exits.
void computeStats ()
Computes stats just prior to dump event.
std::string print ()
Print all tags used.
Addr blkAlign (Addr addr) const
Align an address to the block size.
int extractBlkOffset (Addr addr) const
Calculate the block offset of an address.
virtual void setWayAllocationMax (int ways)
Limit the allocation for the cache ways.
virtual int getWayAllocationMax () const
Get the way allocation mask limit.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
typedef std::pair< Addr, bool > TagHashKey
typedef std::unordered_map< TagHashKey, FALRUBlk *, PairHash > TagHash
Protected Member Functions
void moveToHead (FALRUBlk *blk)
Move a cache block to the MRU position.
void moveToTail (FALRUBlk *blk)
Move a cache block to the LRU position.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
FALRUBlk * blks
The cache blocks.
FALRUBlk * head
The MRU block.
FALRUBlk * tail
The LRU block.
TagHash tagHash
The address hash table.
Protected Attributes inherited from BaseTags
const unsigned blkSize
The block size of the cache.
const Addr blkMask
Mask out all bits that aren't part of the block offset.
const unsigned size
The size of the cache.
const Cycles lookupLatency
The tag lookup latency of the cache.
System * system
System we are currently operating in.
BaseIndexingPolicy * indexingPolicy
Indexing policy.
const unsigned warmupBound
The number of tags that need to be touched to meet the warmup percentage.
bool warmedUp
Marked true when the cache is warmed up.
const unsigned numBlocks
the number of blocks in the cache
std::unique_ptr< uint8_t[]> dataBlks
The data blocks, 1 per cache block.
BaseTags::BaseTagStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
CacheTracking cacheTracking
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
A fully associative LRU cache.
Keeps statistics for accesses to a number of cache sizes at once.
Definition at line 109 of file fa_lru.hh.
Member Typedef Documentation
BlkType
typedef FALRUBlk FALRU::BlkType
Typedef the block type used in this class.
Definition at line 113 of file fa_lru.hh.
Params
typedef FALRUParams FALRU::Params
Definition at line 154 of file fa_lru.hh.
TagHash
typedef std::unordered_map<TagHashKey, FALRUBlk *, PairHash> FALRU::TagHash protected
Definition at line 134 of file fa_lru.hh.
TagHashKey
typedef std::pair<Addr, bool> FALRU::TagHashKey protected
Definition at line 133 of file fa_lru.hh.
Constructor & Destructor Documentation
FALRU()
FALRU::FALRU (const Params * p)
Construct and initialize this cache tagstore.
Definition at line 67 of file fa_lru.cc.
References blks, BaseTags::blkSize, fatal, isPowerOf2(), BaseTags::numBlocks, and BaseTags::size.
Referenced by moveToTail().
~FALRU()
FALRU::~FALRU ()
Definition at line 81 of file fa_lru.cc.
References blks.
Member Function Documentation
accessBlock() [1/2]
CacheBlk * FALRU::accessBlock (Addr addr, bool is_secure, Cycles & lat, CachesMask * in_cache_mask)
Access block and update replacement data.
May not succeed, in which case nullptr pointer is returned. This has all the implications of a cache access and should only be used as such. Returns tag lookup latency and the inCachesMask flags as a side effect.
Parameters
addr The address to look for.
is_secure True if the target memory space is secure.
lat The latency of the tag lookup.
in_cache_mask Mask indicating the caches in which the blk fits.
Returns
Pointer to the cache block.
Definition at line 147 of file fa_lru.cc.
References cacheTracking, findBlock(), FALRUBlk::inCachesMask, CacheBlk::isValid(), BaseTags::lookupLatency, ArmISA::mask, moveToHead(), and FALRU::CacheTracking::recordAccess().
Referenced by accessBlock().
accessBlock() [2/2]
CacheBlk * FALRU::accessBlock (Addr addr, bool is_secure, Cycles & lat) override virtual
Just a wrapper of above function to conform with the base interface.
Implements BaseTags.
Definition at line 141 of file fa_lru.cc.
References accessBlock().
anyBlk()
bool FALRU::anyBlk (std::function< bool(CacheBlk &)> visitor) inline override virtual
Find if any of the blocks satisfies a condition.
The visitor should be a std::function that takes a cache block reference as its parameter. The visitor will terminate the traversal early if the condition is satisfied.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 266 of file fa_lru.hh.
References ArmISA::i.
extractTag()
Addr FALRU::extractTag (Addr addr) const inline override virtual
Generate the tag from the addres.
For fully associative this is just the block address.
Parameters
addr The address to get the tag from.
Returns
The tag.
Reimplemented from BaseTags.
Definition at line 244 of file fa_lru.hh.
Referenced by findBlock().
findBlock()
CacheBlk * FALRU::findBlock (Addr addr, bool is_secure) const override virtual
Find the block in the cache, do not update the replacement data.
Parameters
addr The address to look for.
is_secure True if the target memory space is secure.
asid The address space ID.
Returns
Pointer to the cache block.
Reimplemented from BaseTags.
Definition at line 173 of file fa_lru.cc.
References extractTag(), CacheBlk::isSecure(), CacheBlk::isValid(), CacheBlk::tag, and tagHash.
Referenced by accessBlock().
findBlockBySetAndWay()
ReplaceableEntry * FALRU::findBlockBySetAndWay (int set, int way) const override virtual
Find a block given set and way.
Parameters
set The set of the block.
way The way of the block.
Returns
The block.
Reimplemented from BaseTags.
Definition at line 192 of file fa_lru.cc.
References blks.
findVictim()
CacheBlk * FALRU::findVictim (Addr addr, const bool is_secure, const std::size_t size, std::vector< CacheBlk *> & evict_blks) const override virtual
Find replacement victim based on address.
The list of evicted blocks only contains the victim.
Parameters
addr Address to find a victim for.
is_secure True if the target memory space is secure.
size Size, in bits, of new block to allocate.
evict_blks Cache blocks to be evicted.
Returns
Cache block to be replaced.
Implements BaseTags.
Definition at line 199 of file fa_lru.cc.
References tail.
forEachBlk()
void FALRU::forEachBlk (std::function< void(CacheBlk &)> visitor) inline override virtual
Visit each block in the tags and apply a visitor.
The visitor should be a std::function that takes a cache block reference as its parameter.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 260 of file fa_lru.hh.
References ArmISA::i.
insertBlock()
void FALRU::insertBlock (const PacketPtr pkt, CacheBlk * blk) override virtual
Insert the new block into the cache and update replacement data.
Parameters
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BaseTags.
Definition at line 212 of file fa_lru.cc.
References FALRUBlk::inCachesMask, BaseTags::insertBlock(), CacheBlk::isSecure(), moveToHead(), BaseTags::stats, CacheBlk::tag, tagHash, and BaseTags::BaseTagStats::tagsInUse.
invalidate()
void FALRU::invalidate (CacheBlk * blk) override virtual
Invalidate a cache block.
Parameters
blk The block to invalidate.
Reimplemented from BaseTags.
Definition at line 121 of file fa_lru.cc.
References BaseTags::invalidate(), CacheBlk::isSecure(), M5_VAR_USED, moveToTail(), BaseTags::stats, CacheBlk::tag, tagHash, and BaseTags::BaseTagStats::tagsInUse.
moveToHead()
void FALRU::moveToHead (FALRUBlk * blk) protected
Move a cache block to the MRU position.
Parameters
blk The block to promote.
Definition at line 233 of file fa_lru.cc.
References cacheTracking, FALRU::CacheTracking::check(), head, FALRU::CacheTracking::moveBlockToHead(), FALRUBlk::next, FALRUBlk::prev, and tail.
Referenced by accessBlock(), and insertBlock().
moveToTail()
void FALRU::moveToTail (FALRUBlk * blk) protected
Move a cache block to the LRU position.
Parameters
blk The block to demote.
Definition at line 260 of file fa_lru.cc.
References cacheTracking, FALRU::CacheTracking::check(), FALRU(), head, FALRU::CacheTracking::moveBlockToTail(), FALRUBlk::next, FALRUBlk::prev, and tail.
Referenced by invalidate().
regenerateBlkAddr()
Addr FALRU::regenerateBlkAddr (const CacheBlk * blk) const inline override virtual
Regenerate the block address from the tag.
Parameters
block The block.
Returns
the block address.
Implements BaseTags.
Definition at line 255 of file fa_lru.hh.
References CacheBlk::tag.
regStats()
void FALRU::regStats () override virtual
Register the stats for this object.
Reimplemented from Stats::Group.
Definition at line 114 of file fa_lru.cc.
References cacheTracking, SimObject::name(), Stats::Group::regStats(), and FALRU::CacheTracking::regStats().
tagsInit()
void FALRU::tagsInit () override virtual
Initialize blocks as FALRUBlk instances.
Implements BaseTags.
Definition at line 87 of file fa_lru.cc.
References blks, BaseTags::blkSize, cacheTracking, CacheBlk::data, BaseTags::dataBlks, head, ArmISA::i, FALRU::CacheTracking::init(), FALRUBlk::next, BaseTags::numBlocks, FALRUBlk::prev, ReplaceableEntry::setPosition(), and tail.
Member Data Documentation
blks
FALRUBlk* FALRU::blks protected
The cache blocks.
Definition at line 117 of file fa_lru.hh.
Referenced by FALRU(), findBlockBySetAndWay(), tagsInit(), and ~FALRU().
cacheTracking
CacheTracking FALRU::cacheTracking private
Definition at line 392 of file fa_lru.hh.
Referenced by accessBlock(), moveToHead(), moveToTail(), regStats(), and tagsInit().
head
FALRUBlk* FALRU::head protected
The MRU block.
Definition at line 120 of file fa_lru.hh.
Referenced by FALRU::CacheTracking::check(), FALRU::CacheTracking::init(), moveToHead(), moveToTail(), and tagsInit().
tagHash
TagHash FALRU::tagHash protected
The address hash table.
Definition at line 137 of file fa_lru.hh.
Referenced by findBlock(), insertBlock(), and invalidate().
tail
FALRUBlk* FALRU::tail protected
The LRU block.
Definition at line 122 of file fa_lru.hh.
Referenced by findVictim(), moveToHead(), moveToTail(), and tagsInit().
The documentation for this class was generated from the following files:
mem/cache/tags/fa_lru.hh
mem/cache/tags/fa_lru.cc