gem5: GPUStaticInst Class Reference
GPUStaticInst Class Reference abstract
#include <gpu_static_inst.hh>
Public Member Functions
GPUStaticInst (const std::string &opcode)
void instAddr (int inst_addr)
int instAddr () const
int nextInstAddr () const
void instNum (int num)
int instNum ()
void ipdInstNum (int num)
int ipdInstNum () const
virtual void execute (GPUDynInstPtr gpuDynInst)=0
virtual void generateDisassembly ()=0
const std::string & disassemble ()
virtual int getNumOperands ()=0
virtual bool isCondRegister (int operandIndex)=0
virtual bool isScalarRegister (int operandIndex)=0
virtual bool isVectorRegister (int operandIndex)=0
virtual bool isSrcOperand (int operandIndex)=0
virtual bool isDstOperand (int operandIndex)=0
virtual int getOperandSize (int operandIndex)=0
virtual int getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst)=0
virtual int numDstRegOperands ()=0
virtual int numSrcRegOperands ()=0
virtual bool isValid () const =0
bool isALU () const
bool isBranch () const
bool isNop () const
bool isReturn () const
bool isUnconditionalJump () const
bool isSpecialOp () const
bool isWaitcnt () const
bool isBarrier () const
bool isMemFence () const
bool isMemRef () const
bool isFlat () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isAtomicNoRet () const
bool isAtomicRet () const
bool isScalar () const
bool readsSCC () const
bool writesSCC () const
bool readsVCC () const
bool writesVCC () const
bool isAtomicAnd () const
bool isAtomicOr () const
bool isAtomicXor () const
bool isAtomicCAS () const
bool isAtomicExch () const
bool isAtomicAdd () const
bool isAtomicSub () const
bool isAtomicInc () const
bool isAtomicDec () const
bool isAtomicMax () const
bool isAtomicMin () const
bool isArgLoad () const
bool isGlobalMem () const
bool isLocalMem () const
bool isArgSeg () const
bool isGlobalSeg () const
bool isGroupSeg () const
bool isKernArgSeg () const
bool isPrivateSeg () const
bool isReadOnlySeg () const
bool isSpillSeg () const
bool isWorkitemScope () const
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isNoScope () const
bool isRelaxedOrder () const
bool isAcquire () const
bool isRelease () const
bool isAcquireRelease () const
bool isNoOrder () const
bool isGloballyCoherent () const
Coherence domain of a memory instruction.
bool isSystemCoherent () const
virtual int instSize () const =0
virtual void initiateAcc (GPUDynInstPtr gpuDynInst)
virtual void completeAcc (GPUDynInstPtr gpuDynInst)
virtual uint32_t getTargetPc ()
void setFlag (Flags flag)
virtual void execLdAcq (GPUDynInstPtr gpuDynInst)
virtual void execSt (GPUDynInstPtr gpuDynInst)
virtual void execAtomic (GPUDynInstPtr gpuDynInst)
virtual void execAtomicAcq (GPUDynInstPtr gpuDynInst)
Public Attributes
Enums::StorageClassType executed_as
Static Public Attributes
static uint64_t dynamic_id_count
Protected Attributes
const std::string opcode
std::string disassembly
int _instNum
int _instAddr
int _ipdInstNum
Identifier of the immediate post-dominator instruction.
std::bitset< Num_Flags > _flags
Detailed Description
Definition at line 60 of file gpu_static_inst.hh.
Constructor & Destructor Documentation
GPUStaticInst()
GPUStaticInst::GPUStaticInst (const std::string & opcode)
Definition at line 38 of file gpu_static_inst.cc.
References setFlag().
Member Function Documentation
completeAcc()
virtual void GPUStaticInst::completeAcc (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, and HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >.
Definition at line 210 of file gpu_static_inst.hh.
References fatal.
Referenced by GPUDynInst::completeAcc().
disassemble()
const std::string & GPUStaticInst::disassemble ()
Definition at line 46 of file gpu_static_inst.cc.
References disassembly, and generateDisassembly().
Referenced by GPUDynInst::disassemble(), ipdInstNum(), HsailISA::Call::MagicPrintLane(), HsailISA::Call::MagicPrintLane64(), HsailISA::Call::MagicPrintWF32(), HsailISA::Call::MagicPrintWF32ID(), HsailISA::Call::MagicPrintWF64(), HsailISA::Call::MagicPrintWFFloat(), HsailISA::Call::MagicPrintWFID64(), and FetchUnit::processFetchReturn().
execAtomic()
virtual void GPUStaticInst::execAtomic (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >.
Definition at line 237 of file gpu_static_inst.hh.
References fatal.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::initiateAcc().
execAtomicAcq()
virtual void GPUStaticInst::execAtomicAcq (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >.
Definition at line 243 of file gpu_static_inst.hh.
References fatal.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic().
execLdAcq()
virtual void GPUStaticInst::execLdAcq (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >.
Definition at line 225 of file gpu_static_inst.hh.
References fatal.
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::initiateAcc().
execSt()
virtual void GPUStaticInst::execSt (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >.
Definition at line 231 of file gpu_static_inst.hh.
References fatal.
Referenced by HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::initiateAcc().
execute()
virtual void GPUStaticInst::execute (GPUDynInstPtr gpuDynInst) pure virtual
Implemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::MemFence, HsailISA::Barrier, HsailISA::Ret, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::LdaInst< DestDataType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by GPUDynInst::execute(), and ipdInstNum().
generateDisassembly()
virtual void GPUStaticInst::generateDisassembly () pure virtual
Implemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::Stub, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, KernelLaunchStaticInst, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::LdaInst< DestDataType, AddrOperandType >, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::HsailGPUStaticInst, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by disassemble(), and ipdInstNum().
getNumOperands()
virtual int GPUStaticInst::getNumOperands () pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by GPUDynInst::getNumOperands(), and ipdInstNum().
getOperandSize()
virtual int GPUStaticInst::getOperandSize (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by GPUDynInst::getOperandSize(), and ipdInstNum().
getRegisterIndex()
virtual int GPUStaticInst::getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by GPUDynInst::getRegisterIndex(), and ipdInstNum().
getTargetPc()
virtual uint32_t GPUStaticInst::getTargetPc () inline virtual
Reimplemented in HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Definition at line 215 of file gpu_static_inst.hh.
Referenced by ControlFlowInfo::connectBasicBlocks().
initiateAcc()
virtual void GPUStaticInst::initiateAcc (GPUDynInstPtr gpuDynInst) inline virtual
Reimplemented in HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::MemFence, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, and HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >.
Definition at line 203 of file gpu_static_inst.hh.
References fatal.
Referenced by GPUDynInst::initiateAcc().
instAddr() [1/2]
void GPUStaticInst::instAddr (int inst_addr) inline
Definition at line 64 of file gpu_static_inst.hh.
References _instAddr.
Referenced by ControlFlowInfo::basicBlock(), ControlFlowInfo::findImmediatePostDominators(), and HsailCode::init().
instAddr() [2/2]
int GPUStaticInst::instAddr () const inline
Definition at line 65 of file gpu_static_inst.hh.
References _instAddr.
instNum() [1/2]
void GPUStaticInst::instNum (int num) inline
Definition at line 68 of file gpu_static_inst.hh.
References _instNum.
Referenced by HsailCode::init(), and ControlFlowInfo::lastInstruction().
instNum() [2/2]
int GPUStaticInst::instNum () inline
Definition at line 70 of file gpu_static_inst.hh.
References _instNum.
instSize()
virtual int GPUStaticInst::instSize () const pure virtual
Implemented in KernelLaunchStaticInst, and HsailISA::HsailGPUStaticInst.
Referenced by isSystemCoherent(), nextInstAddr(), and FetchUnit::processFetchReturn().
ipdInstNum() [1/2]
void GPUStaticInst::ipdInstNum (int num) inline
Definition at line 72 of file gpu_static_inst.hh.
References _ipdInstNum.
Referenced by ControlFlowInfo::findImmediatePostDominators().
ipdInstNum() [2/2]
int GPUStaticInst::ipdInstNum () const inline
Definition at line 74 of file gpu_static_inst.hh.
References _ipdInstNum, disassemble(), execute(), generateDisassembly(), getNumOperands(), getOperandSize(), getRegisterIndex(), isCondRegister(), isDstOperand(), isScalarRegister(), isSrcOperand(), isValid(), isVectorRegister(), numDstRegOperands(), and numSrcRegOperands().
Referenced by HsailISA::CbrInstBase< SRegOperand >::execute().
isAcquire()
bool GPUStaticInst::isAcquire () const inline
Definition at line 179 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAcquire().
isAcquireRelease()
bool GPUStaticInst::isAcquireRelease () const inline
Definition at line 181 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAcquireRelease().
isALU()
bool GPUStaticInst::isALU () const inline
Definition at line 95 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isALU().
isArgLoad()
bool GPUStaticInst::isArgLoad () const inline
Definition at line 144 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isArgLoad().
isArgSeg()
bool GPUStaticInst::isArgSeg () const inline
Definition at line 163 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isArgSeg().
isAtomic()
bool GPUStaticInst::isAtomic () const inline
Definition at line 117 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomic().
isAtomicAdd()
bool GPUStaticInst::isAtomicAdd () const inline
Definition at line 136 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicAdd().
isAtomicAnd()
bool GPUStaticInst::isAtomicAnd () const inline
Definition at line 131 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicAnd().
isAtomicCAS()
bool GPUStaticInst::isAtomicCAS () const inline
Definition at line 134 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicCAS().
isAtomicDec()
bool GPUStaticInst::isAtomicDec () const inline
Definition at line 139 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicDec().
isAtomicExch()
bool GPUStaticInst::isAtomicExch () const inline
Definition at line 135 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicExch().
isAtomicInc()
bool GPUStaticInst::isAtomicInc () const inline
Definition at line 138 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicInc().
isAtomicMax()
bool GPUStaticInst::isAtomicMax () const inline
Definition at line 140 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicMax().
isAtomicMin()
bool GPUStaticInst::isAtomicMin () const inline
Definition at line 141 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicMin().
isAtomicNoRet()
bool GPUStaticInst::isAtomicNoRet () const inline
Definition at line 122 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicNoRet().
isAtomicOr()
bool GPUStaticInst::isAtomicOr () const inline
Definition at line 132 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicOr().
isAtomicRet()
bool GPUStaticInst::isAtomicRet () const inline
Definition at line 123 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicRet().
isAtomicSub()
bool GPUStaticInst::isAtomicSub () const inline
Definition at line 137 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicSub().
isAtomicXor()
bool GPUStaticInst::isAtomicXor () const inline
Definition at line 133 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isAtomicXor().
isBarrier()
bool GPUStaticInst::isBarrier () const inline
Definition at line 109 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isBarrier().
isBranch()
bool GPUStaticInst::isBranch () const inline
Definition at line 96 of file gpu_static_inst.hh.
References _flags.
Referenced by ControlFlowInfo::connectBasicBlocks(), and GPUDynInst::isBranch().
isCondRegister()
virtual bool GPUStaticInst::isCondRegister (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, KernelLaunchStaticInst, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by ipdInstNum(), and GPUDynInst::isCondRegister().
isDeviceScope()
bool GPUStaticInst::isDeviceScope () const inline
Definition at line 174 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isDeviceScope().
isDstOperand()
virtual bool GPUStaticInst::isDstOperand (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by ipdInstNum(), and GPUDynInst::isDstOperand().
isFlat()
bool GPUStaticInst::isFlat () const inline
Definition at line 112 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isFlat().
isGloballyCoherent()
bool GPUStaticInst::isGloballyCoherent () const inline
Coherence domain of a memory instruction.
Only valid for machine ISA. The coherence domain specifies where it is possible to perform memory synchronization, e.g., acquire or release, from the shader kernel.
isGloballyCoherent(): returns true if kernel is sharing memory with other work-items on the same device (GPU)
isSystemCoherent(): returns true if kernel is sharing memory with other work-items on a different device (GPU) or the host (CPU)
Definition at line 196 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isGloballyCoherent().
isGlobalMem()
bool GPUStaticInst::isGlobalMem () const inline
Definition at line 150 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isGlobalMem().
isGlobalSeg()
bool GPUStaticInst::isGlobalSeg () const inline
Definition at line 164 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isGlobalSeg().
isGroupSeg()
bool GPUStaticInst::isGroupSeg () const inline
Definition at line 165 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isGroupSeg().
isKernArgSeg()
bool GPUStaticInst::isKernArgSeg () const inline
Definition at line 166 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isKernArgSeg().
isLoad()
bool GPUStaticInst::isLoad () const inline
Definition at line 113 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isLoad().
isLocalMem()
bool GPUStaticInst::isLocalMem () const inline
Definition at line 158 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isLocalMem(), and GPUDynInst::updateStats().
isMemFence()
bool GPUStaticInst::isMemFence () const inline
Definition at line 110 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isMemFence().
isMemRef()
bool GPUStaticInst::isMemRef () const inline
Definition at line 111 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isMemRef().
isNoOrder()
bool GPUStaticInst::isNoOrder () const inline
Definition at line 182 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isNoOrder().
isNop()
bool GPUStaticInst::isNop () const inline
Definition at line 97 of file gpu_static_inst.hh.
References _flags, and Nop().
Referenced by GPUDynInst::isNop().
isNoScope()
bool GPUStaticInst::isNoScope () const inline
Definition at line 176 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isNoScope().
isPrivateSeg()
bool GPUStaticInst::isPrivateSeg () const inline
Definition at line 167 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isPrivateSeg().
isReadOnlySeg()
bool GPUStaticInst::isReadOnlySeg () const inline
Definition at line 168 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isReadOnlySeg().
isRelaxedOrder()
bool GPUStaticInst::isRelaxedOrder () const inline
Definition at line 178 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isRelaxedOrder().
isRelease()
bool GPUStaticInst::isRelease () const inline
Definition at line 180 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isRelease().
isReturn()
bool GPUStaticInst::isReturn () const inline
Definition at line 98 of file gpu_static_inst.hh.
References _flags.
Referenced by ControlFlowInfo::connectBasicBlocks(), and GPUDynInst::isReturn().
isScalar()
bool GPUStaticInst::isScalar () const inline
Definition at line 125 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isScalar().
isScalarRegister()
virtual bool GPUStaticInst::isScalarRegister (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, KernelLaunchStaticInst, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by ipdInstNum(), and GPUDynInst::isScalarRegister().
isSpecialOp()
bool GPUStaticInst::isSpecialOp () const inline
Definition at line 106 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isSpecialOp().
isSpillSeg()
bool GPUStaticInst::isSpillSeg () const inline
Definition at line 169 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isSpillSeg().
isSrcOperand()
virtual bool GPUStaticInst::isSrcOperand (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, KernelLaunchStaticInst, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by ipdInstNum(), and GPUDynInst::isSrcOperand().
isStore()
bool GPUStaticInst::isStore () const inline
Definition at line 114 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isStore().
isSystemCoherent()
bool GPUStaticInst::isSystemCoherent () const inline
Definition at line 197 of file gpu_static_inst.hh.
References _flags, and instSize().
Referenced by GPUDynInst::isSystemCoherent().
isSystemScope()
bool GPUStaticInst::isSystemScope () const inline
Definition at line 175 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isSystemScope().
isUnconditionalJump()
bool GPUStaticInst::isUnconditionalJump () const inline
Definition at line 101 of file gpu_static_inst.hh.
References _flags.
Referenced by ControlFlowInfo::connectBasicBlocks(), and GPUDynInst::isUnconditionalJump().
isValid()
virtual bool GPUStaticInst::isValid () const pure virtual
Implemented in KernelLaunchStaticInst, and HsailISA::HsailGPUStaticInst.
Referenced by ipdInstNum().
isVectorRegister()
virtual bool GPUStaticInst::isVectorRegister (int operandIndex) pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrInstBase< TargetType >, HsailISA::BrInstBase< LabelOperand >, HsailISA::BrInstBase< SRegOperand >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, KernelLaunchStaticInst, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::CbrInstBase< TargetType >, HsailISA::CbrInstBase< LabelOperand >, HsailISA::CbrInstBase< SRegOperand >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >, HsailISA::BrnInstBase< TargetType >, HsailISA::BrnInstBase< LabelOperand >, and HsailISA::BrnInstBase< SRegOperand >.
Referenced by ipdInstNum(), and GPUDynInst::isVectorRegister().
isWaitcnt()
bool GPUStaticInst::isWaitcnt () const inline
Definition at line 107 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isWaitcnt().
isWavefrontScope()
bool GPUStaticInst::isWavefrontScope () const inline
Definition at line 172 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isWavefrontScope().
isWorkgroupScope()
bool GPUStaticInst::isWorkgroupScope () const inline
Definition at line 173 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isWorkgroupScope().
isWorkitemScope()
bool GPUStaticInst::isWorkitemScope () const inline
Definition at line 171 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::isWorkitemScope().
nextInstAddr()
int GPUStaticInst::nextInstAddr () const inline
Definition at line 66 of file gpu_static_inst.hh.
References _instAddr, and instSize().
Referenced by ControlFlowInfo::connectBasicBlocks(), and HsailISA::CbrInstBase< SRegOperand >::execute().
numDstRegOperands()
virtual int GPUStaticInst::numDstRegOperands () pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrIndirectInst, HsailISA::BrDirectInst, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::CbrIndirectInst, HsailISA::CbrDirectInst, KernelLaunchStaticInst, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::BrnIndirectInst, HsailISA::BrnDirectInst, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, and HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >.
Referenced by ipdInstNum(), and GPUDynInst::numDstRegOperands().
numSrcRegOperands()
virtual int GPUStaticInst::numSrcRegOperands () pure virtual
Implemented in HsailISA::AtomicInstBase< OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >, HsailISA::Call, HsailISA::SpecialInst1SrcBase< DestOperandType >, HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >, HsailISA::StInstBase< MemDataType, SrcOperandType, AddrOperandType >, HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >, HsailISA::SpecialInstNoSrcBase< DestOperandType >, HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >, HsailISA::SpecialInstNoSrcNoDest, HsailISA::Stub, HsailISA::TwoNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType >, HsailISA::TwoNonUniformSourceInstBase< B1 ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType >, HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >, HsailISA::BrIndirectInst, HsailISA::BrDirectInst, HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >, HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestOperandType, Src0OperandType, Src1OperandType, Src2OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, B1 ::OperandType, DataType ::OperandType, DataType ::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DestDataType::OperandType, Src0DataType::OperandType, Src1DataType::OperandType, Src2DataType::OperandType >, HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >, HsailISA::CbrIndirectInst, HsailISA::CbrDirectInst, KernelLaunchStaticInst, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 2 >, HsailISA::CommonInstBase< DestOperandType, SrcOperandType, 2 >, HsailISA::CommonInstBase< DataType::OperandType, DataType::OperandType, NumSrcOperands >, HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >, HsailISA::BrnIndirectInst, HsailISA::BrnDirectInst, HsailISA::LdaInstBase< DestOperandType, AddrOperandType >, and HsailISA::LdaInstBase< DestDataType::OperandType, AddrOperandType >.
Referenced by ipdInstNum(), and GPUDynInst::numSrcRegOperands().
readsSCC()
bool GPUStaticInst::readsSCC () const inline
Definition at line 126 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::readsSCC().
readsVCC()
bool GPUStaticInst::readsVCC () const inline
Definition at line 128 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::readsVCC().
setFlag()
void GPUStaticInst::setFlag (Flags flag) inline
Definition at line 222 of file gpu_static_inst.hh.
References _flags.
Referenced by HsailISA::BrInstBase< SRegOperand >::BrInstBase(), HsailISA::BrnInstBase< SRegOperand >::BrnInstBase(), HsailISA::CbrInstBase< SRegOperand >::CbrInstBase(), GPUStaticInst(), KernelLaunchStaticInst::KernelLaunchStaticInst(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), and HsailISA::Call::MagicLoadGlobalU32Reg().
writesSCC()
bool GPUStaticInst::writesSCC () const inline
Definition at line 127 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::writesSCC().
writesVCC()
bool GPUStaticInst::writesVCC () const inline
Definition at line 129 of file gpu_static_inst.hh.
References _flags.
Referenced by GPUDynInst::writesVCC().
Member Data Documentation
_flags
std::bitset<Num_Flags> GPUStaticInst::_flags protected
Definition at line 258 of file gpu_static_inst.hh.
Referenced by isAcquire(), isAcquireRelease(), isALU(), isArgLoad(), isArgSeg(), isAtomic(), isAtomicAdd(), isAtomicAnd(), isAtomicCAS(), isAtomicDec(), isAtomicExch(), isAtomicInc(), isAtomicMax(), isAtomicMin(), isAtomicNoRet(), isAtomicOr(), isAtomicRet(), isAtomicSub(), isAtomicXor(), isBarrier(), isBranch(), isDeviceScope(), isFlat(), isGloballyCoherent(), isGlobalMem(), isGlobalSeg(), isGroupSeg(), isKernArgSeg(), isLoad(), isLocalMem(), isMemFence(), isMemRef(), isNoOrder(), isNop(), isNoScope(), isPrivateSeg(), isReadOnlySeg(), isRelaxedOrder(), isRelease(), isReturn(), isScalar(), isSpecialOp(), isSpillSeg(), isStore(), isSystemCoherent(), isSystemScope(), isUnconditionalJump(), isWaitcnt(), isWavefrontScope(), isWorkgroupScope(), isWorkitemScope(), readsSCC(), readsVCC(), setFlag(), writesSCC(), and writesVCC().
_instAddr
int GPUStaticInst::_instAddr protected
Definition at line 252 of file gpu_static_inst.hh.
Referenced by instAddr(), and nextInstAddr().
_instNum
int GPUStaticInst::_instNum protected
Definition at line 251 of file gpu_static_inst.hh.
Referenced by instNum().
_ipdInstNum
int GPUStaticInst::_ipdInstNum protected
Identifier of the immediate post-dominator instruction.
Definition at line 256 of file gpu_static_inst.hh.
Referenced by ipdInstNum().
disassembly
std::string GPUStaticInst::disassembly protected
Definition at line 250 of file gpu_static_inst.hh.
Referenced by disassemble(), HsailISA::BrnInstBase< SRegOperand >::generateDisassembly(), HsailISA::HsailGPUStaticInst::generateDisassembly(), HsailISA::CbrInstBase< SRegOperand >::generateDisassembly(), KernelLaunchStaticInst::generateDisassembly(), and HsailISA::BrInstBase< SRegOperand >::generateDisassembly().
dynamic_id_count
uint64_t GPUStaticInst::dynamic_id_count static
Definition at line 217 of file gpu_static_inst.hh.
executed_as
Enums::StorageClassType GPUStaticInst::executed_as
Definition at line 220 of file gpu_static_inst.hh.
Referenced by GPUDynInst::executedAs().
opcode
const std::string GPUStaticInst::opcode protected
Definition at line 249 of file gpu_static_inst.hh.
Referenced by HsailISA::BrnInstBase< SRegOperand >::generateDisassembly(), HsailISA::HsailGPUStaticInst::generateDisassembly(), HsailISA::CbrInstBase< SRegOperand >::generateDisassembly(), KernelLaunchStaticInst::generateDisassembly(), and HsailISA::BrInstBase< SRegOperand >::generateDisassembly().
The documentation for this class was generated from the following files:
gpu-compute/gpu_static_inst.hh
gpu-compute/gpu_static_inst.cc