gem5: tlm_utils::multi_target_base_if< TYPES > Class Template Reference
tlm_utils::multi_target_base_if< TYPES > Class Template Reference abstract
#include <multi_socket_bases.h>
Public Member Functions
virtual std::vector< callback_binder_fw< TYPES > * > & get_binders ()=0
virtual std::map< unsigned int, tlm::tlm_bw_transport_if< TYPES > * > & get_multi_binds ()=0
Protected Member Functions
virtual ~multi_target_base_if ()
Detailed Description
template<typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::multi_target_base_if< TYPES >
Definition at line 411 of file multi_socket_bases.h.
Constructor & Destructor Documentation
~multi_target_base_if()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual tlm_utils::multi_target_base_if< TYPES >::~multi_target_base_if () inline protected virtual
Definition at line 426 of file multi_socket_bases.h.
Member Function Documentation
get_binders()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual std::vector<callback_binder_fw<TYPES> *>& tlm_utils::multi_target_base_if< TYPES >::get_binders () pure virtual
Implemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::size().
get_multi_binds()
template<typename TYPES = tlm::tlm_base_protocol_types> virtual std::map<unsigned int, tlm::tlm_bw_transport_if<TYPES>*>& tlm_utils::multi_target_base_if< TYPES >::get_multi_binds () pure virtual
Implemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/multi_socket_bases.h