gem5: MmioVirtIO Class Reference
MmioVirtIO Class Reference
#include <vio_mmio.hh>
Public Member Functions
MmioVirtIO (const MmioVirtIOParams *params)
virtual ~MmioVirtIO ()
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum { INT_USED_RING = 1 << 0, INT_CONFIG = 1 << 1 }
enum : Addr {
OFF_MAGIC = 0x00, OFF_VERSION = 0x04, OFF_DEVICE_ID = 0x08, OFF_VENDOR_ID = 0x0C,
OFF_HOST_FEATURES = 0x10, OFF_HOST_FEATURES_SELECT = 0x14, OFF_GUEST_FEATURES = 0x20, OFF_GUEST_FEATURES_SELECT = 0x24,
OFF_GUEST_PAGE_SIZE = 0x28, OFF_QUEUE_SELECT = 0x30, OFF_QUEUE_NUM_MAX = 0x34, OFF_QUEUE_NUM = 0x38,
OFF_QUEUE_ALIGN = 0x3C, OFF_QUEUE_PFN = 0x40, OFF_QUEUE_NOTIFY = 0x50, OFF_INTERRUPT_STATUS = 0x60,
OFF_INTERRUPT_ACK = 0x64, OFF_STATUS = 0x70, OFF_CONFIG = 0x100
}
Offsets into VirtIO MMIO space.
Protected Member Functions
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
uint32_t read (Addr offset)
void write (Addr offset, uint32_t value)
void kick ()
void setInterrupts (uint32_t value)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
uint32_t hostFeaturesSelect
uint32_t guestFeaturesSelect
uint32_t pageSize
uint32_t interruptStatus
MakeCallback< MmioVirtIO, &MmioVirtIO::kick > callbackKick
VirtIODeviceBase & vio
ArmInterruptPin *const interrupt
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const uint32_t MAGIC = 0x74726976
static const uint32_t VERSION = 1
static const uint32_t VENDOR_ID = 0x1AF4
Additional Inherited Members
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 49 of file vio_mmio.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum : Addr protected
Offsets into VirtIO MMIO space.
Enumerator
OFF_MAGIC
OFF_VERSION
OFF_DEVICE_ID
OFF_VENDOR_ID
OFF_HOST_FEATURES
OFF_HOST_FEATURES_SELECT
OFF_GUEST_FEATURES
OFF_GUEST_FEATURES_SELECT
OFF_GUEST_PAGE_SIZE
OFF_QUEUE_SELECT
OFF_QUEUE_NUM_MAX
OFF_QUEUE_NUM
OFF_QUEUE_ALIGN
OFF_QUEUE_PFN
OFF_QUEUE_NOTIFY
OFF_INTERRUPT_STATUS
OFF_INTERRUPT_ACK
OFF_STATUS
OFF_CONFIG
Definition at line 63 of file vio_mmio.hh.
anonymous enum
anonymous enum protected
Enumerator
INT_USED_RING
INT_CONFIG
Definition at line 87 of file vio_mmio.hh.
Constructor & Destructor Documentation
MmioVirtIO()
MmioVirtIO::MmioVirtIO (const MmioVirtIOParams * params)
Definition at line 47 of file vio_mmio.cc.
References callbackKick, fatal_if, interrupt, VirtIODeviceBase::registerKickCallback(), and vio.
Referenced by setInterrupts().
~MmioVirtIO()
MmioVirtIO::~MmioVirtIO () virtual
Definition at line 59 of file vio_mmio.cc.
Member Function Documentation
kick()
void MmioVirtIO::kick () protected
Definition at line 261 of file vio_mmio.cc.
References DPRINTF, INT_USED_RING, interruptStatus, and setInterrupts().
read() [1/2]
Tick MmioVirtIO::read (PacketPtr pkt) override protected virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 64 of file vio_mmio.cc.
References DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeResponse(), OFF_CONFIG, ArmISA::offset, panic_if, BasicPioDevice::pioAddr, VirtIODeviceBase::readConfig(), Packet::setLE(), and vio.
read() [2/2]
uint32_t MmioVirtIO::read (Addr offset) protected
Definition at line 88 of file vio_mmio.cc.
References VirtQueue::ALIGN_SIZE, VirtIODeviceBase::deviceFeatures, VirtIODeviceBase::deviceId, VirtIODeviceBase::getDeviceStatus(), VirtIODeviceBase::getGuestFeatures(), VirtIODeviceBase::getQueueAddress(), VirtIODeviceBase::getQueueSelect(), VirtIODeviceBase::getQueueSize(), guestFeaturesSelect, hostFeaturesSelect, interruptStatus, MAGIC, OFF_DEVICE_ID, OFF_GUEST_FEATURES, OFF_GUEST_FEATURES_SELECT, OFF_GUEST_PAGE_SIZE, OFF_HOST_FEATURES, OFF_HOST_FEATURES_SELECT, OFF_INTERRUPT_ACK, OFF_INTERRUPT_STATUS, OFF_MAGIC, OFF_QUEUE_ALIGN, OFF_QUEUE_NOTIFY, OFF_QUEUE_NUM, OFF_QUEUE_NUM_MAX, OFF_QUEUE_PFN, OFF_QUEUE_SELECT, OFF_STATUS, OFF_VENDOR_ID, OFF_VERSION, pageSize, panic, VENDOR_ID, VERSION, vio, and warn.
setInterrupts()
void MmioVirtIO::setInterrupts (uint32_t value) protected
Definition at line 268 of file vio_mmio.cc.
References ArmInterruptPin::clear(), interrupt, interruptStatus, MmioVirtIO(), and ArmInterruptPin::raise().
Referenced by kick(), and write().
write() [1/2]
Tick MmioVirtIO::write (PacketPtr pkt) override protected virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 162 of file vio_mmio.cc.
References DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeResponse(), OFF_CONFIG, ArmISA::offset, panic_if, BasicPioDevice::pioAddr, vio, and VirtIODeviceBase::writeConfig().
write() [2/2]
void MmioVirtIO::write (Addr offset, uint32_t value) protected
Definition at line 183 of file vio_mmio.cc.
References VirtQueue::ALIGN_SIZE, guestFeaturesSelect, hostFeaturesSelect, interruptStatus, OFF_DEVICE_ID, OFF_GUEST_FEATURES, OFF_GUEST_FEATURES_SELECT, OFF_GUEST_PAGE_SIZE, OFF_HOST_FEATURES, OFF_HOST_FEATURES_SELECT, OFF_INTERRUPT_ACK, OFF_INTERRUPT_STATUS, OFF_MAGIC, OFF_QUEUE_ALIGN, OFF_QUEUE_NOTIFY, OFF_QUEUE_NUM, OFF_QUEUE_NUM_MAX, OFF_QUEUE_PFN, OFF_QUEUE_SELECT, OFF_STATUS, OFF_VENDOR_ID, OFF_VERSION, VirtIODeviceBase::onNotify(), pageSize, panic, panic_if, VirtIODeviceBase::setDeviceStatus(), VirtIODeviceBase::setGuestFeatures(), setInterrupts(), VirtIODeviceBase::setQueueAddress(), VirtIODeviceBase::setQueueSelect(), vio, warn, and warn_once.
Member Data Documentation
callbackKick
MakeCallback<MmioVirtIO, &MmioVirtIO::kick> MmioVirtIO::callbackKick protected
Definition at line 108 of file vio_mmio.hh.
Referenced by MmioVirtIO().
guestFeaturesSelect
uint32_t MmioVirtIO::guestFeaturesSelect protected
Definition at line 104 of file vio_mmio.hh.
Referenced by read(), and write().
hostFeaturesSelect
uint32_t MmioVirtIO::hostFeaturesSelect protected
Definition at line 103 of file vio_mmio.hh.
Referenced by read(), and write().
interrupt
ArmInterruptPin* const MmioVirtIO::interrupt protected
Definition at line 112 of file vio_mmio.hh.
Referenced by MmioVirtIO(), and setInterrupts().
interruptStatus
uint32_t MmioVirtIO::interruptStatus protected
Definition at line 106 of file vio_mmio.hh.
Referenced by kick(), read(), setInterrupts(), and write().
MAGIC
const uint32_t MmioVirtIO::MAGIC = 0x74726976 static protected
Definition at line 92 of file vio_mmio.hh.
Referenced by read().
pageSize
uint32_t MmioVirtIO::pageSize protected
Definition at line 105 of file vio_mmio.hh.
Referenced by read(), and write().
VENDOR_ID
const uint32_t MmioVirtIO::VENDOR_ID = 0x1AF4 static protected
Definition at line 94 of file vio_mmio.hh.
Referenced by read().
VERSION
const uint32_t MmioVirtIO::VERSION = 1 static protected
Definition at line 93 of file vio_mmio.hh.
Referenced by read().
vio
VirtIODeviceBase& MmioVirtIO::vio protected
Definition at line 111 of file vio_mmio.hh.
Referenced by MmioVirtIO(), read(), and write().
The documentation for this class was generated from the following files:
dev/arm/vio_mmio.hh
dev/arm/vio_mmio.cc