gem5: SecurePortProxy Class Reference
SecurePortProxy Class Reference
This object is a proxy for a structural port, to be used for debug accesses to secure memory.
#include <secure_port_proxy.hh>
Public Member Functions
bool tryReadBlob (Addr addr, void *p, int size) const override
Methods to override in base classes.
bool tryWriteBlob (Addr addr, const void *p, int size) const override
Write size bytes from p to address.
bool tryMemsetBlob (Addr addr, uint8_t val, int size) const override
Fill size bytes starting at addr with byte value val.
Public Member Functions inherited from PortProxy
PortProxy (SendFunctionalFunc func, unsigned int cacheLineSize)
PortProxy (const MasterPort &port, unsigned int cacheLineSize)
virtual ~PortProxy ()
void readBlobPhys (Addr addr, Request::Flags flags, void *p, int size) const
Fixed functionality for use in base classes.
void writeBlobPhys (Addr addr, Request::Flags flags, const void *p, int size) const
Write size bytes from p to physical address.
void memsetBlobPhys (Addr addr, Request::Flags flags, uint8_t v, int size) const
Fill size bytes starting at physical addr with byte value val.
void readBlob (Addr addr, void *p, int size) const
Higher level interfaces based on the above.
void writeBlob (Addr addr, const void *p, int size) const
Same as tryWriteBlob, but insists on success.
void memsetBlob (Addr addr, uint8_t v, int size) const
Same as tryMemsetBlob, but insists on success.
template<typename T >
T read (Addr address) const
Read sizeof(T) bytes from address and return as object T.
template<typename T >
void write (Addr address, const T &data) const
Write object T to address.
template<typename T >
T read (Addr address, ByteOrder guest_byte_order) const
Read sizeof(T) bytes from address and return as object T.
template<typename T >
void write (Addr address, T data, ByteOrder guest_byte_order) const
Write object T to address.
bool tryWriteString (Addr addr, const char *str) const
Write the string str into guest memory at address addr.
void writeString (Addr addr, const char *str) const
Same as tryWriteString, but insists on success.
bool tryReadString (std::string &str, Addr addr) const
Reads the string at guest address addr into the std::string str.
void readString (std::string &str, Addr addr) const
Same as tryReadString, but insists on success.
bool tryReadString (char *str, Addr addr, size_t maxlen) const
Reads the string at guest address addr into the char * str, reading up to maxlen characters.
void readString (char *str, Addr addr, size_t maxlen) const
Same as tryReadString, but insists on success.
Additional Inherited Members
Public Types inherited from PortProxy
typedef std::function< void(PacketPtr pkt)> SendFunctionalFunc
Detailed Description
This object is a proxy for a structural port, to be used for debug accesses to secure memory.
The addresses are interpreted as physical addresses to secure memory.
Definition at line 70 of file secure_port_proxy.hh.
Member Function Documentation
tryMemsetBlob()
bool SecurePortProxy::tryMemsetBlob (Addr addr, uint8_t val, int size) const override virtual
Fill size bytes starting at addr with byte value val.
Returns true on success and false on failure.
Reimplemented from PortProxy.
Definition at line 57 of file secure_port_proxy.cc.
References PortProxy::memsetBlobPhys(), and Request::SECURE.
tryReadBlob()
bool SecurePortProxy::tryReadBlob (Addr addr, void * p, int size) const override virtual
Methods to override in base classes.
Read size bytes memory at address and store in p. Returns true on success and false on failure.
Reimplemented from PortProxy.
Definition at line 43 of file secure_port_proxy.cc.
References PortProxy::readBlobPhys(), and Request::SECURE.
tryWriteBlob()
bool SecurePortProxy::tryWriteBlob (Addr addr, const void * p, int size) const override virtual
Write size bytes from p to address.
Returns true on success and false on failure.
Reimplemented from PortProxy.
Definition at line 50 of file secure_port_proxy.cc.
References Request::SECURE, and PortProxy::writeBlobPhys().
The documentation for this class was generated from the following files:
mem/secure_port_proxy.hh
mem/secure_port_proxy.cc