gem5: CowDiskImage Class Reference
CowDiskImage Class Reference
Specialization for accessing a copy-on-write disk image layer.
#include <disk_image.hh>
Classes
struct Sector
Public Types
typedef CowDiskImageParams Params
Public Types inherited from DiskImage
typedef DiskImageParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
CowDiskImage (const Params *p)
~CowDiskImage ()
void notifyFork () override
Notify a child process of a fork.
void initSectorTable (int hash_size)
bool open (const std::string &file)
void save () const
void save (const std::string &file) const
void writeback ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
std::streampos size () const override
std::streampos read (uint8_t *data, std::streampos offset) const override
std::streampos write (const uint8_t *data, std::streampos offset) override
Public Member Functions inherited from DiskImage
DiskImage (const Params *p)
virtual ~DiskImage ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Attributes
static const uint32_t VersionMajor = 1
static const uint32_t VersionMinor = 0
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
typedef std::unordered_map< uint64_t, Sector * > SectorTable
Protected Attributes
std::string filename
DiskImage * child
SectorTable * table
Protected Attributes inherited from DiskImage
bool initialized
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Specialization for accessing a copy-on-write disk image layer.
A copy-on-write(COW) layer must be stacked on top of another disk image layer this layer can be another CowDiskImage, or a RawDiskImage.
This object is designed to provide a mechanism for persistant changes to a main disk image, or to provide a place for temporary changes to the image to take place that later may be thrown away.
Definition at line 106 of file disk_image.hh.
Member Typedef Documentation
Params
typedef CowDiskImageParams CowDiskImage::Params
Definition at line 124 of file disk_image.hh.
SectorTable
typedef std::unordered_map<uint64_t, Sector *> CowDiskImage::SectorTable protected
Definition at line 116 of file disk_image.hh.
Constructor & Destructor Documentation
CowDiskImage()
CowDiskImage::CowDiskImage (const Params * p)
Definition at line 183 of file disk_image.cc.
References fatal, filename, initSectorTable(), open(), and registerExitCallback().
Referenced by unserialize().
~CowDiskImage()
CowDiskImage::~CowDiskImage ()
Definition at line 200 of file disk_image.cc.
References ArmISA::i, and table.
Member Function Documentation
initSectorTable()
void CowDiskImage::initSectorTable (int hash_size)
Definition at line 297 of file disk_image.cc.
References DiskImage::initialized, and table.
Referenced by CowDiskImage().
notifyFork()
void CowDiskImage::notifyFork () override virtual
Notify a child process of a fork.
When calling fork in gem5, we need to ensure that resources shared between the parent and the child are consistent. This method is intended to be overloaded to handle that. For example, an object could use this method to re-open input files to get a separate file description with a private file offset.
This method is only called in the child of the fork. The call takes place in a drained system.
Reimplemented from Drainable.
Definition at line 212 of file disk_image.cc.
References filename, inform, and SimObject::params().
open()
bool CowDiskImage::open (const std::string & file)
Definition at line 251 of file disk_image.cc.
References ArmISA::i, DiskImage::initialized, ArmISA::offset, panic, SafeRead(), SafeReadSwap(), table, VersionMajor, and VersionMinor.
Referenced by CowDiskImage(), and unserialize().
read()
std::streampos CowDiskImage::read (uint8_t * data, std::streampos offset) const override virtual
Implements DiskImage.
Definition at line 393 of file disk_image.cc.
References child, DDUMP, DPRINTF, ArmISA::i, DiskImage::initialized, panic, DiskImage::read(), SectorSize, size(), and table.
save() [1/2]
void CowDiskImage::save () const
Definition at line 333 of file disk_image.cc.
References filename, ArmISA::i, DiskImage::initialized, panic, SafeWrite(), SafeWriteSwap(), size(), table, VersionMajor, and VersionMinor.
Referenced by CowDiskCallback::process(), and serialize().
save() [2/2]
void CowDiskImage::save (const std::string & file) const
serialize()
void CowDiskImage::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 437 of file disk_image.cc.
References CheckpointIn::dir(), SimObject::name(), save(), and SERIALIZE_SCALAR.
size()
std::streampos CowDiskImage::size () const override virtual
Implements DiskImage.
Definition at line 389 of file disk_image.cc.
References child, and DiskImage::size().
Referenced by read(), save(), and write().
unserialize()
void CowDiskImage::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 445 of file disk_image.cc.
References CowDiskImage(), CheckpointIn::cptDir, open(), and UNSERIALIZE_SCALAR.
write()
std::streampos CowDiskImage::write (const uint8_t * data, std::streampos offset) override virtual
Implements DiskImage.
Definition at line 413 of file disk_image.cc.
References DDUMP, DPRINTF, ArmISA::i, DiskImage::initialized, panic, SectorSize, size(), and table.
writeback()
void CowDiskImage::writeback ()
Definition at line 377 of file disk_image.cc.
References child, ArmISA::i, table, and DiskImage::write().
Member Data Documentation
child
DiskImage* CowDiskImage::child protected
Definition at line 120 of file disk_image.hh.
Referenced by read(), size(), and writeback().
filename
std::string CowDiskImage::filename protected
Definition at line 119 of file disk_image.hh.
Referenced by CowDiskImage(), notifyFork(), and save().
table
SectorTable* CowDiskImage::table protected
Definition at line 121 of file disk_image.hh.
Referenced by initSectorTable(), open(), read(), save(), write(), writeback(), and ~CowDiskImage().
VersionMajor
const uint32_t CowDiskImage::VersionMajor = 1 static
Definition at line 109 of file disk_image.hh.
Referenced by open(), save(), and RawDiskImage::write().
VersionMinor
const uint32_t CowDiskImage::VersionMinor = 0 static
Definition at line 110 of file disk_image.hh.
Referenced by open(), save(), and RawDiskImage::write().
The documentation for this class was generated from the following files:
dev/storage/disk_image.hh
dev/storage/disk_image.cc