gem5: sc_core::sc_unsigned_part_if Class Reference
sc_core::sc_unsigned_part_if Class Reference
#include <scx_signal_unsigned.h>
Public Member Functions
virtual sc_dt::sc_unsigned * part_read_target ()
virtual sc_dt::sc_unsigned read_part (int left, int right) const
virtual sc_unsigned_sigref & select_part (int left, int right)
virtual void write_part (sc_dt::int64 v, int left, int right)
virtual void write_part (sc_dt::uint64 v, int left, int right)
virtual void write_part (const sc_dt::sc_signed &v, int left, int right)
virtual void write_part (const sc_dt::sc_unsigned &v, int left, int right)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_unsigned_part_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_unsigned_part_if (const sc_unsigned_part_if &)
sc_unsigned_part_if & operator= (const sc_unsigned_part_if &)
Detailed Description
Definition at line 199 of file scx_signal_unsigned.h.
Constructor & Destructor Documentation
sc_unsigned_part_if() [1/2]
sc_core::sc_unsigned_part_if::sc_unsigned_part_if () inline protected
Definition at line 202 of file scx_signal_unsigned.h.
References operator=(), part_read_target(), read_part(), select_part(), ArmISA::v, and write_part().
sc_unsigned_part_if() [2/2]
sc_core::sc_unsigned_part_if::sc_unsigned_part_if (const sc_unsigned_part_if &) private
Member Function Documentation
operator=()
sc_unsigned_part_if& sc_core::sc_unsigned_part_if::operator= (const sc_unsigned_part_if &) private
Referenced by sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >::sc_signal_in_if(), sc_unsigned_part_if(), and sc_core::sc_unsigned_sigref::~sc_unsigned_sigref().
part_read_target()
sc_dt::sc_unsigned * sc_core::sc_unsigned_part_if::part_read_target () virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1744 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_core::sc_unsigned_sigref::initialize(), and sc_unsigned_part_if().
read_part()
sc_dt::sc_unsigned sc_core::sc_unsigned_part_if::read_part (int left, int right) const virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1749 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_unsigned_part_if().
select_part()
sc_unsigned_sigref & sc_core::sc_unsigned_part_if::select_part (int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1754 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_unsigned_part_if().
write_part() [1/4]
void sc_core::sc_unsigned_part_if::write_part (sc_dt::int64 v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1759 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
Referenced by sc_unsigned_part_if().
write_part() [2/4]
void sc_core::sc_unsigned_part_if::write_part (sc_dt::uint64 v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1763 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
write_part() [3/4]
void sc_core::sc_unsigned_part_if::write_part (const sc_dt::sc_signed & v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1767 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
write_part() [4/4]
void sc_core::sc_unsigned_part_if::write_part (const sc_dt::sc_unsigned & v, int left, int right) virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_biguint< W > >.
Definition at line 1772 of file scx_signal_unsigned.h.
References sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_, and SC_REPORT_ERROR.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_unsigned.h