gem5: SparcISA::SparcFaultBase Class Reference
SparcISA::SparcFaultBase Class Reference abstract
#include <faults.hh>
Classes
struct FaultVals
Public Types
enum PrivilegeLevel {
U, User = U, P, Privileged = P,
H, Hyperprivileged = H, NumLevels, SH = -1,
ShouldntHappen = SH
}
using PrivilegeLevelSpec = std::array< PrivilegeLevel, NumLevels >
Public Member Functions
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
virtual TrapType trapType ()=0
virtual FaultPriority priority ()=0
virtual FaultStat & countStat ()=0
virtual PrivilegeLevel getNextLevel (PrivilegeLevel current)=0
Public Member Functions inherited from FaultBase
virtual FaultName name () const =0
virtual ~FaultBase ()
Detailed Description
Definition at line 48 of file faults.hh.
Member Typedef Documentation
PrivilegeLevelSpec
using SparcISA::SparcFaultBase::PrivilegeLevelSpec = std::array<PrivilegeLevel, NumLevels>
Definition at line 60 of file faults.hh.
Member Enumeration Documentation
PrivilegeLevel
enum SparcISA::SparcFaultBase::PrivilegeLevel
Enumerator
U
User
P
Privileged
H
Hyperprivileged
NumLevels
SH
ShouldntHappen
Definition at line 51 of file faults.hh.
Member Function Documentation
countStat()
virtual FaultStat& SparcISA::SparcFaultBase::countStat () pure virtual
Implemented in SparcISA::SparcFault< T >, SparcISA::SparcFault< TagOverflow >, SparcISA::SparcFault< InstructionInvalidTSBEntry >, SparcISA::SparcFault< REDStateException >, SparcISA::SparcFault< HstickMatch >, SparcISA::SparcFault< PrivilegedOpcode >, SparcISA::SparcFault< VecDisabled >, SparcISA::SparcFault< InstructionBreakpoint >, SparcISA::SparcFault< FpDisabled >, SparcISA::SparcFault< StoreError >, SparcISA::SparcFault< InterruptLevelN >, SparcISA::SparcFault< FpExceptionIEEE754 >, SparcISA::SparcFault< DataRealTranslationMiss >, SparcISA::SparcFault< PrivilegedAction >, SparcISA::SparcFault< MemAddressNotAligned >, SparcISA::SparcFault< InstructionAccessException >, SparcISA::SparcFault< FastInstructionAccessMMUMiss >, SparcISA::SparcFault< InstructionRealTranslationMiss >, SparcISA::SparcFault< TrapInstruction >, SparcISA::SparcFault< ExternallyInitiatedReset >, SparcISA::SparcFault< CleanWindow >, SparcISA::SparcFault< LDQFMemAddressNotAligned >, SparcISA::SparcFault< DevMondo >, SparcISA::SparcFault< STDFMemAddressNotAligned >, SparcISA::SparcFault< FastDataAccessProtection >, SparcISA::SparcFault< DivisionByZero >, SparcISA::SparcFault< IllegalInstruction >, SparcISA::SparcFault< DataAccessError >, SparcISA::SparcFault< SpillNNormal >, SparcISA::SparcFault< SoftwareInitiatedReset >, SparcISA::SparcFault< FillNOther >, SparcISA::SparcFault< FpExceptionOther >, SparcISA::SparcFault< DataInvalidTSBEntry >, SparcISA::SparcFault< InstructionAccessError >, SparcISA::SparcFault< PowerOnReset >, SparcISA::SparcFault< DataAccessProtection >, SparcISA::SparcFault< InternalProcessorError >, SparcISA::SparcFault< ResumableError >, SparcISA::SparcFault< DataAccessException >, SparcISA::SparcFault< InterruptVector >, SparcISA::SparcFault< SpillNOther >, SparcISA::SparcFault< TrapLevelZero >, SparcISA::SparcFault< PAWatchpoint >, SparcISA::SparcFault< FastDataAccessMMUMiss >, SparcISA::SparcFault< FillNNormal >, SparcISA::SparcFault< VAWatchpoint >, SparcISA::SparcFault< STQFMemAddressNotAligned >, SparcISA::SparcFault< WatchDogReset >, SparcISA::SparcFault< LDDFMemAddressNotAligned >, and SparcISA::SparcFault< CpuMondo >.
Referenced by SparcISA::SparcFaultBase::FaultVals::FaultVals().
getNextLevel()
virtual PrivilegeLevel SparcISA::SparcFaultBase::getNextLevel (PrivilegeLevel current) pure virtual
Implemented in SparcISA::SparcFault< T >, SparcISA::SparcFault< TagOverflow >, SparcISA::SparcFault< InstructionInvalidTSBEntry >, SparcISA::SparcFault< REDStateException >, SparcISA::SparcFault< HstickMatch >, SparcISA::SparcFault< PrivilegedOpcode >, SparcISA::SparcFault< VecDisabled >, SparcISA::SparcFault< InstructionBreakpoint >, SparcISA::SparcFault< FpDisabled >, SparcISA::SparcFault< StoreError >, SparcISA::SparcFault< InterruptLevelN >, SparcISA::SparcFault< FpExceptionIEEE754 >, SparcISA::SparcFault< DataRealTranslationMiss >, SparcISA::SparcFault< PrivilegedAction >, SparcISA::SparcFault< MemAddressNotAligned >, SparcISA::SparcFault< InstructionAccessException >, SparcISA::SparcFault< FastInstructionAccessMMUMiss >, SparcISA::SparcFault< InstructionRealTranslationMiss >, SparcISA::SparcFault< TrapInstruction >, SparcISA::SparcFault< ExternallyInitiatedReset >, SparcISA::SparcFault< CleanWindow >, SparcISA::SparcFault< LDQFMemAddressNotAligned >, SparcISA::SparcFault< DevMondo >, SparcISA::SparcFault< STDFMemAddressNotAligned >, SparcISA::SparcFault< FastDataAccessProtection >, SparcISA::SparcFault< DivisionByZero >, SparcISA::SparcFault< IllegalInstruction >, SparcISA::SparcFault< DataAccessError >, SparcISA::SparcFault< SpillNNormal >, SparcISA::SparcFault< SoftwareInitiatedReset >, SparcISA::SparcFault< FillNOther >, SparcISA::SparcFault< FpExceptionOther >, SparcISA::SparcFault< DataInvalidTSBEntry >, SparcISA::SparcFault< InstructionAccessError >, SparcISA::SparcFault< PowerOnReset >, SparcISA::SparcFault< DataAccessProtection >, SparcISA::SparcFault< InternalProcessorError >, SparcISA::SparcFault< ResumableError >, SparcISA::SparcFault< DataAccessException >, SparcISA::SparcFault< InterruptVector >, SparcISA::SparcFault< SpillNOther >, SparcISA::SparcFault< TrapLevelZero >, SparcISA::SparcFault< PAWatchpoint >, SparcISA::SparcFault< FastDataAccessMMUMiss >, SparcISA::SparcFault< FillNNormal >, SparcISA::SparcFault< VAWatchpoint >, SparcISA::SparcFault< STQFMemAddressNotAligned >, SparcISA::SparcFault< WatchDogReset >, SparcISA::SparcFault< LDDFMemAddressNotAligned >, and SparcISA::SparcFault< CpuMondo >.
Referenced by SparcISA::SparcFaultBase::FaultVals::FaultVals().
invoke()
void SparcISA::SparcFaultBase::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from FaultBase.
Reimplemented in SparcISA::TrapInstruction, SparcISA::FillNNormal, SparcISA::SpillNNormal, SparcISA::FastDataAccessMMUMiss, SparcISA::FastInstructionAccessMMUMiss, and SparcISA::PowerOnReset.
Definition at line 500 of file faults.cc.
References SparcISA::doNormalFault(), SparcISA::doREDFault(), SparcISA::enterREDState(), FullSystem, SparcISA::getHyperVector(), SparcISA::getPrivVector(), SparcISA::getREDVector(), FaultBase::invoke(), X86ISA::level, SparcISA::MaxPTL, SparcISA::MaxTL, SparcISA::MISCREG_HPSTATE, SparcISA::MISCREG_PSTATE, SparcISA::MISCREG_TL, SparcISA::MISCREG_TT, GenericISA::DelaySlotPCState< MachInst >::nnpc(), GenericISA::SimplePCState< MachInst >::npc(), GenericISA::DelaySlotUPCState< MachInst >::nupc(), panic, GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), MipsISA::tl, and GenericISA::DelaySlotUPCState< MachInst >::upc().
Referenced by SparcISA::FastDataAccessMMUMiss::FastDataAccessMMUMiss(), SparcISA::FastInstructionAccessMMUMiss::FastInstructionAccessMMUMiss(), SparcISA::SparcFaultBase::FaultVals::FaultVals(), SparcISA::FillNNormal::FillNNormal(), Iob::generateIpi(), SparcISA::SpillNNormal::SpillNNormal(), and SparcISA::TrapInstruction::TrapInstruction().
priority()
virtual FaultPriority SparcISA::SparcFaultBase::priority () pure virtual
Implemented in SparcISA::InterruptLevelN, SparcISA::SparcFault< T >, SparcISA::SparcFault< TagOverflow >, SparcISA::SparcFault< InstructionInvalidTSBEntry >, SparcISA::SparcFault< REDStateException >, SparcISA::SparcFault< HstickMatch >, SparcISA::SparcFault< PrivilegedOpcode >, SparcISA::SparcFault< VecDisabled >, SparcISA::SparcFault< InstructionBreakpoint >, SparcISA::SparcFault< FpDisabled >, SparcISA::SparcFault< StoreError >, SparcISA::SparcFault< InterruptLevelN >, SparcISA::SparcFault< FpExceptionIEEE754 >, SparcISA::SparcFault< DataRealTranslationMiss >, SparcISA::SparcFault< PrivilegedAction >, SparcISA::SparcFault< MemAddressNotAligned >, SparcISA::SparcFault< InstructionAccessException >, SparcISA::SparcFault< FastInstructionAccessMMUMiss >, SparcISA::SparcFault< InstructionRealTranslationMiss >, SparcISA::SparcFault< TrapInstruction >, SparcISA::SparcFault< ExternallyInitiatedReset >, SparcISA::SparcFault< CleanWindow >, SparcISA::SparcFault< LDQFMemAddressNotAligned >, SparcISA::SparcFault< DevMondo >, SparcISA::SparcFault< STDFMemAddressNotAligned >, SparcISA::SparcFault< FastDataAccessProtection >, SparcISA::SparcFault< DivisionByZero >, SparcISA::SparcFault< IllegalInstruction >, SparcISA::SparcFault< DataAccessError >, SparcISA::SparcFault< SpillNNormal >, SparcISA::SparcFault< SoftwareInitiatedReset >, SparcISA::SparcFault< FillNOther >, SparcISA::SparcFault< FpExceptionOther >, SparcISA::SparcFault< DataInvalidTSBEntry >, SparcISA::SparcFault< InstructionAccessError >, SparcISA::SparcFault< PowerOnReset >, SparcISA::SparcFault< DataAccessProtection >, SparcISA::SparcFault< InternalProcessorError >, SparcISA::SparcFault< ResumableError >, SparcISA::SparcFault< DataAccessException >, SparcISA::SparcFault< InterruptVector >, SparcISA::SparcFault< SpillNOther >, SparcISA::SparcFault< TrapLevelZero >, SparcISA::SparcFault< PAWatchpoint >, SparcISA::SparcFault< FastDataAccessMMUMiss >, SparcISA::SparcFault< FillNNormal >, SparcISA::SparcFault< VAWatchpoint >, SparcISA::SparcFault< STQFMemAddressNotAligned >, SparcISA::SparcFault< WatchDogReset >, SparcISA::SparcFault< LDDFMemAddressNotAligned >, and SparcISA::SparcFault< CpuMondo >.
trapType()
virtual TrapType SparcISA::SparcFaultBase::trapType () pure virtual
Implemented in SparcISA::EnumeratedFault< T >, SparcISA::EnumeratedFault< InterruptLevelN >, SparcISA::EnumeratedFault< TrapInstruction >, SparcISA::EnumeratedFault< SpillNNormal >, SparcISA::EnumeratedFault< FillNOther >, SparcISA::EnumeratedFault< SpillNOther >, SparcISA::EnumeratedFault< FillNNormal >, SparcISA::SparcFault< T >, SparcISA::SparcFault< TagOverflow >, SparcISA::SparcFault< InstructionInvalidTSBEntry >, SparcISA::SparcFault< REDStateException >, SparcISA::SparcFault< HstickMatch >, SparcISA::SparcFault< PrivilegedOpcode >, SparcISA::SparcFault< VecDisabled >, SparcISA::SparcFault< InstructionBreakpoint >, SparcISA::SparcFault< FpDisabled >, SparcISA::SparcFault< StoreError >, SparcISA::SparcFault< InterruptLevelN >, SparcISA::SparcFault< FpExceptionIEEE754 >, SparcISA::SparcFault< DataRealTranslationMiss >, SparcISA::SparcFault< PrivilegedAction >, SparcISA::SparcFault< MemAddressNotAligned >, SparcISA::SparcFault< InstructionAccessException >, SparcISA::SparcFault< FastInstructionAccessMMUMiss >, SparcISA::SparcFault< InstructionRealTranslationMiss >, SparcISA::SparcFault< TrapInstruction >, SparcISA::SparcFault< ExternallyInitiatedReset >, SparcISA::SparcFault< CleanWindow >, SparcISA::SparcFault< LDQFMemAddressNotAligned >, SparcISA::SparcFault< DevMondo >, SparcISA::SparcFault< STDFMemAddressNotAligned >, SparcISA::SparcFault< FastDataAccessProtection >, SparcISA::SparcFault< DivisionByZero >, SparcISA::SparcFault< IllegalInstruction >, SparcISA::SparcFault< DataAccessError >, SparcISA::SparcFault< SpillNNormal >, SparcISA::SparcFault< SoftwareInitiatedReset >, SparcISA::SparcFault< FillNOther >, SparcISA::SparcFault< FpExceptionOther >, SparcISA::SparcFault< DataInvalidTSBEntry >, SparcISA::SparcFault< InstructionAccessError >, SparcISA::SparcFault< PowerOnReset >, SparcISA::SparcFault< DataAccessProtection >, SparcISA::SparcFault< InternalProcessorError >, SparcISA::SparcFault< ResumableError >, SparcISA::SparcFault< DataAccessException >, SparcISA::SparcFault< InterruptVector >, SparcISA::SparcFault< SpillNOther >, SparcISA::SparcFault< TrapLevelZero >, SparcISA::SparcFault< PAWatchpoint >, SparcISA::SparcFault< FastDataAccessMMUMiss >, SparcISA::SparcFault< FillNNormal >, SparcISA::SparcFault< VAWatchpoint >, SparcISA::SparcFault< STQFMemAddressNotAligned >, SparcISA::SparcFault< WatchDogReset >, SparcISA::SparcFault< LDDFMemAddressNotAligned >, and SparcISA::SparcFault< CpuMondo >.
The documentation for this class was generated from the following files:
arch/sparc/faults.hh
arch/sparc/faults.cc