gem5: MultiperspectivePerceptron::MPPBranchInfo Class Reference
MultiperspectivePerceptron::MPPBranchInfo Class Reference
Branch information data.
#include <multiperspective_perceptron.hh>
Public Member Functions
MPPBranchInfo (Addr _pc, int pcshift, bool cb)
unsigned int getPC () const
unsigned short int getPC2 () const
unsigned short int getHPC () const
unsigned int getHashFilter (bool last_ghist_bit) const
bool isUnconditional () const
Public Attributes
bool filtered
Whether this branch has been filtered by the prefetcher.
bool prediction
Result of the prediction (true is taken)
int yout
Score of the perceptron.
Static Private Member Functions
static unsigned int hash1 (unsigned int a)
PC Hash functions.
static unsigned int hash2 (unsigned int key)
static unsigned int hash (unsigned int key, unsigned int i)
static unsigned int hashPC (unsigned int pc, int pcshift)
Private Attributes
const unsigned int pc
pc of the branch
const unsigned short int pc2
pc of the branch, shifted 2 bits to the right
const unsigned short int hpc
pc of the branch, hashed
const bool condBranch
Whether this is a conditional branch.
Detailed Description
Branch information data.
Definition at line 54 of file multiperspective_perceptron.hh.
Constructor & Destructor Documentation
MPPBranchInfo()
MultiperspectivePerceptron::MPPBranchInfo::MPPBranchInfo (Addr _pc, int pcshift, bool cb) inline
Definition at line 113 of file multiperspective_perceptron.hh.
Member Function Documentation
getHashFilter()
unsigned int MultiperspectivePerceptron::MPPBranchInfo::getHashFilter (bool last_ghist_bit) const inline
Definition at line 130 of file multiperspective_perceptron.hh.
References hpc.
Referenced by MultiperspectivePerceptron::lookup(), and MultiperspectivePerceptron::update().
getHPC()
unsigned short int MultiperspectivePerceptron::MPPBranchInfo::getHPC () const inline
Definition at line 126 of file multiperspective_perceptron.hh.
References hpc.
Referenced by MultiperspectivePerceptron::computeOutput(), MultiperspectivePerceptron::getIndex(), MultiperspectivePerceptron::train(), and MultiperspectivePerceptron::update().
getPC()
unsigned int MultiperspectivePerceptron::MPPBranchInfo::getPC () const inline
Definition at line 118 of file multiperspective_perceptron.hh.
References pc.
Referenced by MultiperspectivePerceptron::computeOutput(), MultiperspectivePerceptronTAGE::getIndex(), MultiperspectivePerceptron::getIndex(), MultiperspectivePerceptron::update(), and MultiperspectivePerceptronTAGE::updateHistories().
getPC2()
unsigned short int MultiperspectivePerceptron::MPPBranchInfo::getPC2 () const inline
Definition at line 122 of file multiperspective_perceptron.hh.
References pc2.
Referenced by MultiperspectivePerceptron::getIndex(), and MultiperspectivePerceptron::update().
hash()
static unsigned int MultiperspectivePerceptron::MPPBranchInfo::hash (unsigned int key, unsigned int i) inline static private
Definition at line 87 of file multiperspective_perceptron.hh.
References hash1(), and hash2().
Referenced by MultiperspectivePerceptron::GHIST::getHash(), MultiperspectivePerceptron::RECENCYPOS::getHash(), and hashPC().
hash1()
static unsigned int MultiperspectivePerceptron::MPPBranchInfo::hash1 (unsigned int a) inline static private
PC Hash functions.
Definition at line 67 of file multiperspective_perceptron.hh.
References ArmISA::a.
Referenced by hash().
hash2()
static unsigned int MultiperspectivePerceptron::MPPBranchInfo::hash2 (unsigned int key) inline static private
Definition at line 76 of file multiperspective_perceptron.hh.
References MipsISA::c2.
Referenced by hash().
hashPC()
static unsigned int MultiperspectivePerceptron::MPPBranchInfo::hashPC (unsigned int pc, int pcshift) inline static private
Definition at line 92 of file multiperspective_perceptron.hh.
References hash(), pc, MultiperspectivePerceptron::pcshift, and X86ISA::x.
isUnconditional()
bool MultiperspectivePerceptron::MPPBranchInfo::isUnconditional () const inline
Definition at line 134 of file multiperspective_perceptron.hh.
References condBranch.
Referenced by MultiperspectivePerceptronTAGE::update(), and MultiperspectivePerceptron::update().
Member Data Documentation
condBranch
const bool MultiperspectivePerceptron::MPPBranchInfo::condBranch private
Whether this is a conditional branch.
Definition at line 62 of file multiperspective_perceptron.hh.
Referenced by isUnconditional().
filtered
bool MultiperspectivePerceptron::MPPBranchInfo::filtered
Whether this branch has been filtered by the prefetcher.
Definition at line 107 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::lookup(), and MultiperspectivePerceptron::update().
hpc
const unsigned short int MultiperspectivePerceptron::MPPBranchInfo::hpc private
pc of the branch, hashed
Definition at line 60 of file multiperspective_perceptron.hh.
Referenced by getHashFilter(), and getHPC().
pc
const unsigned int MultiperspectivePerceptron::MPPBranchInfo::pc private
pc of the branch
Definition at line 56 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::LOCAL::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), getPC(), hashPC(), MultiperspectivePerceptron::HistorySpec::HistorySpec(), and MultiperspectivePerceptron::ThreadData::insertRecency().
pc2
const unsigned short int MultiperspectivePerceptron::MPPBranchInfo::pc2 private
pc of the branch, shifted 2 bits to the right
Definition at line 58 of file multiperspective_perceptron.hh.
Referenced by getPC2(), and MultiperspectivePerceptron::HistorySpec::HistorySpec().
prediction
bool MultiperspectivePerceptron::MPPBranchInfo::prediction
Result of the prediction (true is taken)
Definition at line 109 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::lookup().
yout
int MultiperspectivePerceptron::MPPBranchInfo::yout
Score of the perceptron.
Definition at line 111 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::computeOutput(), MultiperspectivePerceptron::lookup(), and MultiperspectivePerceptron::train().
The documentation for this class was generated from the following file:
cpu/pred/multiperspective_perceptron.hh