gem5: GenericISA::DelaySlotUPCState< MachInst > Class Template Reference
GenericISA::DelaySlotUPCState< MachInst > Class Template Reference
#include <types.hh>
Public Member Functions
MicroPC upc () const
void upc (MicroPC val)
MicroPC nupc () const
void nupc (MicroPC val)
MicroPC microPC () const
void set (Addr val)
DelaySlotUPCState ()
DelaySlotUPCState (Addr val)
bool branching () const
void uAdvance ()
void uEnd ()
bool operator== (const DelaySlotUPCState< MachInst > &opc) const
bool operator!= (const DelaySlotUPCState< MachInst > &opc) const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from GenericISA::DelaySlotPCState< MachInst >
Addr nnpc () const
void nnpc (Addr val)
void set (Addr val)
DelaySlotPCState ()
DelaySlotPCState (Addr val)
bool branching () const
void advance ()
bool operator== (const DelaySlotPCState< MachInst > &opc) const
bool operator!= (const DelaySlotPCState< MachInst > &opc) const
Public Member Functions inherited from GenericISA::SimplePCState< MachInst >
Addr pc () const
void pc (Addr val)
Addr npc () const
void npc (Addr val)
void set (Addr val)
void setNPC (Addr val)
SimplePCState ()
SimplePCState (Addr val)
bool branching () const
void advance ()
Public Member Functions inherited from GenericISA::PCStateBase
Addr instAddr () const
Returns the memory address the bytes of this instruction came from.
Addr nextInstAddr () const
Returns the memory address the bytes of the next instruction came from.
MicroPC microPC () const
Returns the current micropc.
void set (Addr val)
Force this PC to reflect a particular value, resetting all its other fields around it.
bool operator== (const PCStateBase &opc) const
bool operator!= (const PCStateBase &opc) const
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Types
typedef DelaySlotPCState< MachInst > Base
Protected Types inherited from GenericISA::DelaySlotPCState< MachInst >
typedef SimplePCState< MachInst > Base
Protected Types inherited from GenericISA::SimplePCState< MachInst >
typedef PCStateBase Base
Protected Attributes
MicroPC _upc
MicroPC _nupc
Protected Attributes inherited from GenericISA::DelaySlotPCState< MachInst >
Addr _nnpc
Protected Attributes inherited from GenericISA::PCStateBase
Addr _pc
Addr _npc
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from GenericISA::PCStateBase
PCStateBase ()
PCStateBase (Addr val)
Detailed Description
template<class MachInst>
class GenericISA::DelaySlotUPCState< MachInst >
Definition at line 373 of file types.hh.
Member Typedef Documentation
Base
template<class MachInst> typedef DelaySlotPCState<MachInst> GenericISA::DelaySlotUPCState< MachInst >::Base protected
Definition at line 376 of file types.hh.
Constructor & Destructor Documentation
DelaySlotUPCState() [1/2]
template<class MachInst> GenericISA::DelaySlotUPCState< MachInst >::DelaySlotUPCState () inline
Definition at line 403 of file types.hh.
DelaySlotUPCState() [2/2]
template<class MachInst> GenericISA::DelaySlotUPCState< MachInst >::DelaySlotUPCState (Addr val) inline
Definition at line 404 of file types.hh.
References X86ISA::val.
Member Function Documentation
branching()
template<class MachInst> bool GenericISA::DelaySlotUPCState< MachInst >::branching () const inline
Definition at line 407 of file types.hh.
microPC()
template<class MachInst> MicroPC GenericISA::DelaySlotUPCState< MachInst >::microPC () const inline
Definition at line 390 of file types.hh.
nupc() [1/2]
template<class MachInst> MicroPC GenericISA::DelaySlotUPCState< MachInst >::nupc () const inline
Definition at line 386 of file types.hh.
Referenced by SparcISA::SparcFaultBase::invoke(), SparcISA::PowerOnReset::invoke(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs().
nupc() [2/2]
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::nupc (MicroPC val) inline
Definition at line 387 of file types.hh.
References X86ISA::val.
operator!=()
template<class MachInst> bool GenericISA::DelaySlotUPCState< MachInst >::operator!= (const DelaySlotUPCState< MachInst > & opc) const inline
Definition at line 439 of file types.hh.
operator==()
template<class MachInst> bool GenericISA::DelaySlotUPCState< MachInst >::operator== (const DelaySlotUPCState< MachInst > & opc) const inline
Definition at line 430 of file types.hh.
References GenericISA::DelaySlotPCState< MachInst >::_nnpc, GenericISA::PCStateBase::_npc, GenericISA::DelaySlotUPCState< MachInst >::_nupc, GenericISA::PCStateBase::_pc, and GenericISA::DelaySlotUPCState< MachInst >::_upc.
serialize()
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from GenericISA::DelaySlotPCState< MachInst >.
Definition at line 445 of file types.hh.
References serialize(), and SERIALIZE_SCALAR.
set()
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::set (Addr val) inline
Definition at line 396 of file types.hh.
References X86ISA::val.
Referenced by SparcISA::skipFunction().
uAdvance()
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::uAdvance () inline
Definition at line 414 of file types.hh.
Referenced by SparcISA::SparcMicroInst::advancePC().
uEnd()
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::uEnd () inline
Definition at line 422 of file types.hh.
Referenced by SparcISA::SparcMicroInst::advancePC(), and SparcISA::buildRetPC().
unserialize()
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from GenericISA::DelaySlotPCState< MachInst >.
Definition at line 453 of file types.hh.
References unserialize(), and UNSERIALIZE_SCALAR.
upc() [1/2]
template<class MachInst> MicroPC GenericISA::DelaySlotUPCState< MachInst >::upc () const inline
Definition at line 383 of file types.hh.
Referenced by SparcISA::SparcFaultBase::invoke(), SparcISA::PowerOnReset::invoke(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), and SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs().
upc() [2/2]
template<class MachInst> void GenericISA::DelaySlotUPCState< MachInst >::upc (MicroPC val) inline
Definition at line 384 of file types.hh.
References X86ISA::val.
Member Data Documentation
_nupc
template<class MachInst> MicroPC GenericISA::DelaySlotUPCState< MachInst >::_nupc protected
Definition at line 379 of file types.hh.
Referenced by GenericISA::DelaySlotUPCState< MachInst >::operator==().
_upc
template<class MachInst> MicroPC GenericISA::DelaySlotUPCState< MachInst >::_upc protected
Definition at line 378 of file types.hh.
Referenced by GenericISA::DelaySlotUPCState< MachInst >::operator==().
The documentation for this class was generated from the following file:
arch/generic/types.hh