gem5: Linux::ThreadInfo Class Reference
Linux::ThreadInfo Class Reference
#include <threadinfo.hh>
Public Member Functions
ThreadInfo (ThreadContext *_tc, Addr _pcbb=0)
~ThreadInfo ()
Addr curThreadInfo ()
Addr curTaskInfo (Addr thread_info=0)
int32_t curTaskPIDFromTaskStruct (Addr task_struct)
int32_t curTaskPID (Addr thread_info=0)
int32_t curTaskTGIDFromTaskStruct (Addr task_struct)
int32_t curTaskTGID (Addr thread_info=0)
int64_t curTaskStartFromTaskStruct (Addr task_struct)
int64_t curTaskStart (Addr thread_info=0)
std::string curTaskNameFromTaskStruct (Addr task_struct)
std::string curTaskName (Addr thread_info=0)
int32_t curTaskMmFromTaskStruct (Addr task_struct)
int32_t curTaskMm (Addr thread_info=0)
Private Member Functions
template<typename T >
bool get_data (const char *symbol, T &data)
Private Attributes
ThreadContext * tc
System * sys
Addr pcbb
Detailed Description
Definition at line 42 of file threadinfo.hh.
Constructor & Destructor Documentation
ThreadInfo()
Linux::ThreadInfo::ThreadInfo (ThreadContext * _tc, Addr _pcbb = 0) inline
Definition at line 67 of file threadinfo.hh.
~ThreadInfo()
Linux::ThreadInfo::~ThreadInfo () inline
Definition at line 72 of file threadinfo.hh.
Member Function Documentation
curTaskInfo()
Addr Linux::ThreadInfo::curTaskInfo (Addr thread_info = 0) inline
Definition at line 94 of file threadinfo.hh.
References curThreadInfo(), get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::read().
Referenced by curTaskMm(), curTaskName(), curTaskPID(), curTaskStart(), and curTaskTGID().
curTaskMm()
int32_t Linux::ThreadInfo::curTaskMm (Addr thread_info = 0) inline
Definition at line 193 of file threadinfo.hh.
References curTaskInfo(), and curTaskMmFromTaskStruct().
Referenced by DumpStatsPCEvent::getTaskDetails().
curTaskMmFromTaskStruct()
int32_t Linux::ThreadInfo::curTaskMmFromTaskStruct (Addr task_struct) inline
Definition at line 183 of file threadinfo.hh.
References get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::read().
Referenced by curTaskMm(), and DumpStatsPCEvent64::getTaskDetails().
curTaskName()
std::string Linux::ThreadInfo::curTaskName (Addr thread_info = 0) inline
Definition at line 177 of file threadinfo.hh.
References curTaskInfo(), and curTaskNameFromTaskStruct().
Referenced by DumpStatsPCEvent::getTaskDetails(), LinuxAlphaSystem::PrintThreadInfo::process(), LinuxMipsSystem::PrintThreadInfo::process(), and AnnotateDumpCallback::process().
curTaskNameFromTaskStruct()
std::string Linux::ThreadInfo::curTaskNameFromTaskStruct (Addr task_struct) inline
Definition at line 159 of file threadinfo.hh.
References get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::readString().
Referenced by curTaskName(), and DumpStatsPCEvent64::getTaskDetails().
curTaskPID()
int32_t Linux::ThreadInfo::curTaskPID (Addr thread_info = 0) inline
Definition at line 119 of file threadinfo.hh.
References curTaskInfo(), and curTaskPIDFromTaskStruct().
Referenced by DumpStatsPCEvent::getTaskDetails(), LinuxAlphaSystem::PrintThreadInfo::process(), and LinuxMipsSystem::PrintThreadInfo::process().
curTaskPIDFromTaskStruct()
int32_t Linux::ThreadInfo::curTaskPIDFromTaskStruct (Addr task_struct) inline
Definition at line 110 of file threadinfo.hh.
References get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::read().
Referenced by curTaskPID(), and DumpStatsPCEvent64::getTaskDetails().
curTaskStart()
int64_t Linux::ThreadInfo::curTaskStart (Addr thread_info = 0) inline
Definition at line 153 of file threadinfo.hh.
References curTaskInfo(), and curTaskStartFromTaskStruct().
Referenced by LinuxAlphaSystem::PrintThreadInfo::process(), and LinuxMipsSystem::PrintThreadInfo::process().
curTaskStartFromTaskStruct()
int64_t Linux::ThreadInfo::curTaskStartFromTaskStruct (Addr task_struct) inline
Definition at line 141 of file threadinfo.hh.
References get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::read().
Referenced by curTaskStart().
curTaskTGID()
int32_t Linux::ThreadInfo::curTaskTGID (Addr thread_info = 0) inline
Definition at line 135 of file threadinfo.hh.
References curTaskInfo(), and curTaskTGIDFromTaskStruct().
Referenced by DumpStatsPCEvent::getTaskDetails().
curTaskTGIDFromTaskStruct()
int32_t Linux::ThreadInfo::curTaskTGIDFromTaskStruct (Addr task_struct) inline
Definition at line 125 of file threadinfo.hh.
References get_data(), ThreadContext::getVirtProxy(), ArmISA::offset, and PortProxy::read().
Referenced by curTaskTGID(), and DumpStatsPCEvent64::getTaskDetails().
curThreadInfo()
Addr Linux::ThreadInfo::curThreadInfo () inline
Definition at line 76 of file threadinfo.hh.
References addr, AlphaISA::CurThreadInfoImplemented, AlphaISA::CurThreadInfoReg, ThreadContext::getPhysProxy(), MipsISA::p, panic, pcbb, PortProxy::readBlob(), ThreadContext::readMiscRegNoEffect(), ArmISA::sp, and ULL.
Referenced by curTaskInfo().
get_data()
template<typename T > bool Linux::ThreadInfo::get_data (const char * symbol, T & data) inline private
Definition at line 51 of file threadinfo.hh.
References addr, SymbolTable::findAddress(), ThreadContext::getVirtProxy(), AlphaISA::GuestByteOrder, System::kernelSymtab, PortProxy::read(), and warn_once.
Referenced by curTaskInfo(), curTaskMmFromTaskStruct(), curTaskNameFromTaskStruct(), curTaskPIDFromTaskStruct(), curTaskStartFromTaskStruct(), and curTaskTGIDFromTaskStruct().
Member Data Documentation
pcbb
Addr Linux::ThreadInfo::pcbb private
Definition at line 47 of file threadinfo.hh.
Referenced by curThreadInfo().
sys
System* Linux::ThreadInfo::sys private
Definition at line 46 of file threadinfo.hh.
tc
ThreadContext* Linux::ThreadInfo::tc private
Definition at line 45 of file threadinfo.hh.
The documentation for this class was generated from the following file:
arch/generic/linux/threadinfo.hh