gem5: sc_dt::sc_int_base Class Reference
sc_dt::sc_int_base Class Reference
#include <sc_int_base.hh>
Public Member Functions
sc_int_base (int w=sc_length_param().len())
sc_int_base (int_type v, int w)
sc_int_base (const sc_int_base &a)
sc_int_base (const sc_int_subref_r &a)
template<class T >
sc_int_base (const sc_generic_base< T > &a)
sc_int_base (const sc_signed &a)
sc_int_base (const sc_unsigned &a)
sc_int_base (const sc_bv_base &v)
sc_int_base (const sc_lv_base &v)
sc_int_base (const sc_uint_subref_r &v)
sc_int_base (const sc_signed_subref_r &v)
sc_int_base (const sc_unsigned_subref_r &v)
virtual ~sc_int_base ()
sc_int_base & operator= (int_type v)
sc_int_base & operator= (const sc_int_base &a)
sc_int_base & operator= (const sc_int_subref_r &a)
template<class T >
sc_int_base & operator= (const sc_generic_base< T > &a)
sc_int_base & operator= (const sc_signed &a)
sc_int_base & operator= (const sc_unsigned &a)
sc_int_base & operator= (const sc_fxval &a)
sc_int_base & operator= (const sc_fxval_fast &a)
sc_int_base & operator= (const sc_fxnum &a)
sc_int_base & operator= (const sc_fxnum_fast &a)
sc_int_base & operator= (const sc_bv_base &a)
sc_int_base & operator= (const sc_lv_base &a)
sc_int_base & operator= (const char *a)
sc_int_base & operator= (unsigned long a)
sc_int_base & operator= (long a)
sc_int_base & operator= (unsigned int a)
sc_int_base & operator= (int a)
sc_int_base & operator= (uint64 a)
sc_int_base & operator= (double a)
sc_int_base & operator+= (int_type v)
sc_int_base & operator-= (int_type v)
sc_int_base & operator*= (int_type v)
sc_int_base & operator/= (int_type v)
sc_int_base & operator%= (int_type v)
sc_int_base & operator&= (int_type v)
sc_int_base & operator|= (int_type v)
sc_int_base & operator^= (int_type v)
sc_int_base & operator<<= (int_type v)
sc_int_base & operator>>= (int_type v)
sc_int_base & operator++ ()
const sc_int_base operator++ (int)
sc_int_base & operator-- ()
const sc_int_base operator-- (int)
sc_int_bitref & operator[] (int i)
const sc_int_bitref_r & operator[] (int i) const
sc_int_bitref & bit (int i)
const sc_int_bitref_r & bit (int i) const
sc_int_subref & operator() (int left, int right)
const sc_int_subref_r & operator() (int left, int right) const
sc_int_subref & range (int left, int right)
const sc_int_subref_r & range (int left, int right) const
bool test (int i) const
void set (int i)
void set (int i, bool v)
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator int_type () const
int_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
long long_low () const
long long_high () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Attributes
int_type m_val
int m_len
int m_ulen
Private Member Functions
void invalid_length () const
void invalid_index (int i) const
void invalid_range (int l, int r) const
void check_length () const
void check_index (int i) const
void check_range (int l, int r) const
void check_value () const
void extend_sign ()
Friends
class sc_int_bitref_r
class sc_int_bitref
class sc_int_subref_r
class sc_int_subref
bool operator== (const sc_int_base &a, const sc_int_base &b)
bool operator!= (const sc_int_base &a, const sc_int_base &b)
bool operator< (const sc_int_base &a, const sc_int_base &b)
bool operator<= (const sc_int_base &a, const sc_int_base &b)
bool operator> (const sc_int_base &a, const sc_int_base &b)
bool operator>= (const sc_int_base &a, const sc_int_base &b)
Detailed Description
Definition at line 494 of file sc_int_base.hh.
Constructor & Destructor Documentation
sc_int_base() [1/12]
sc_dt::sc_int_base::sc_int_base (int w = sc_length_param().len()) inline explicit
Definition at line 545 of file sc_int_base.hh.
sc_int_base() [2/12]
sc_dt::sc_int_base::sc_int_base (int_type v, int w) inline
Definition at line 551 of file sc_int_base.hh.
sc_int_base() [3/12]
sc_dt::sc_int_base::sc_int_base (const sc_int_base & a) inline
Definition at line 558 of file sc_int_base.hh.
sc_int_base() [4/12]
sc_dt::sc_int_base::sc_int_base (const sc_int_subref_r & a) inline explicit
Definition at line 562 of file sc_int_base.hh.
sc_int_base() [5/12]
template<class T > sc_dt::sc_int_base::sc_int_base (const sc_generic_base< T > & a) inline explicit
Definition at line 569 of file sc_int_base.hh.
References ArmISA::a, and ArmISA::v.
sc_int_base() [6/12]
sc_dt::sc_int_base::sc_int_base (const sc_signed & a) explicit
Definition at line 434 of file sc_int_base.cc.
References check_length(), and sc_dt::sc_signed::to_int64().
sc_int_base() [7/12]
sc_dt::sc_int_base::sc_int_base (const sc_unsigned & a) explicit
Definition at line 441 of file sc_int_base.cc.
References check_length(), and sc_dt::sc_unsigned::to_int64().
sc_int_base() [8/12]
sc_dt::sc_int_base::sc_int_base (const sc_bv_base & v) explicit
Definition at line 403 of file sc_int_base.cc.
References check_length(), and ArmISA::v.
sc_int_base() [9/12]
sc_dt::sc_int_base::sc_int_base (const sc_lv_base & v) explicit
Definition at line 409 of file sc_int_base.cc.
References check_length(), and ArmISA::v.
sc_int_base() [10/12]
sc_dt::sc_int_base::sc_int_base (const sc_uint_subref_r & v) explicit
Definition at line 415 of file sc_int_base.cc.
References check_length(), and sc_dt::sc_uint_subref_r::to_uint64().
sc_int_base() [11/12]
sc_dt::sc_int_base::sc_int_base (const sc_signed_subref_r & v) explicit
Definition at line 421 of file sc_int_base.cc.
References check_length(), and sc_dt::sc_signed_subref_r::to_uint64().
sc_int_base() [12/12]
sc_dt::sc_int_base::sc_int_base (const sc_unsigned_subref_r & v) explicit
Definition at line 427 of file sc_int_base.cc.
References check_length(), and sc_dt::sc_unsigned_subref_r::to_uint64().
~sc_int_base()
virtual sc_dt::sc_int_base::~sc_int_base () inline virtual
Definition at line 586 of file sc_int_base.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_int_base::and_reduce () const
Definition at line 556 of file sc_int_base.cc.
References m_val.
Referenced by sc_dt::sc_int_subref_r::and_reduce(), and sc_dt::and_reduce().
bit() [1/2]
sc_int_bitref & sc_dt::sc_int_base::bit (int i) inline
Definition at line 1272 of file sc_int_base.hh.
References sc_dt::sc_int_bitref_r::initialize(), and sc_dt::sc_int_bitref::m_pool.
bit() [2/2]
const sc_int_bitref_r & sc_dt::sc_int_base::bit (int i) const inline
Definition at line 1281 of file sc_int_base.hh.
References sc_dt::sc_int_bitref_r::initialize(), and sc_dt::sc_int_bitref::m_pool.
check_index()
void sc_dt::sc_int_base::check_index (int i) const inline private
Definition at line 516 of file sc_int_base.hh.
check_length()
void sc_dt::sc_int_base::check_length () const inline private
Definition at line 508 of file sc_int_base.hh.
References SC_INTWIDTH.
Referenced by sc_int_base().
check_range()
void sc_dt::sc_int_base::check_range (int l, int r) const inline private
Definition at line 524 of file sc_int_base.hh.
check_value()
void sc_dt::sc_int_base::check_value () const private
Definition at line 391 of file sc_int_base.cc.
References X86ISA::limit, sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_WARNING.
concat_get_ctrl()
bool sc_dt::sc_int_base::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 574 of file sc_int_base.cc.
References BITS_PER_DIGIT, m_len, ArmISA::mask, and sc_dt::UINT_ZERO.
concat_get_data()
bool sc_dt::sc_int_base::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 609 of file sc_int_base.cc.
References BITS_PER_DIGIT, DIGIT_MASK, m_len, m_val, ArmISA::mask, sc_dt::UINT_ZERO, and X86ISA::val.
concat_get_uint64()
virtual uint64 sc_dt::sc_int_base::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 883 of file sc_int_base.hh.
References sc_dt::and_reduce().
concat_length()
virtual int sc_dt::sc_int_base::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 874 of file sc_int_base.hh.
References length.
concat_set() [1/4]
void sc_dt::sc_int_base::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 669 of file sc_int_base.cc.
concat_set() [2/4]
void sc_dt::sc_int_base::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 675 of file sc_int_base.cc.
References sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_int_base::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 684 of file sc_int_base.cc.
References sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_int_base::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_int< W > >.
Definition at line 693 of file sc_int_base.cc.
extend_sign()
void sc_dt::sc_int_base::extend_sign () inline private
Definition at line 534 of file sc_int_base.hh.
Referenced by operator=().
invalid_index()
void sc_dt::sc_int_base::invalid_index (int i) const private
Definition at line 370 of file sc_int_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
invalid_length()
void sc_dt::sc_int_base::invalid_length () const private
Definition at line 360 of file sc_int_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, SC_INTWIDTH, and SC_REPORT_ERROR.
invalid_range()
void sc_dt::sc_int_base::invalid_range (int l, int r) const private
Definition at line 380 of file sc_int_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
length()
int sc_dt::sc_int_base::length () const inline
Definition at line 870 of file sc_int_base.hh.
Referenced by sc_dt::assign_v_().
long_high()
long sc_dt::sc_int_base::long_high () const inline
Definition at line 919 of file sc_int_base.hh.
References sc_dt::SC_DEC, sc_dt::to_string(), and sc_dt::UINT64_32ONES.
long_low()
long sc_dt::sc_int_base::long_low () const inline
Definition at line 918 of file sc_int_base.hh.
References sc_dt::UINT64_32ONES.
nand_reduce()
bool sc_dt::sc_int_base::nand_reduce () const inline
Definition at line 898 of file sc_int_base.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
Referenced by sc_dt::nand_reduce().
nor_reduce()
bool sc_dt::sc_int_base::nor_reduce () const inline
Definition at line 900 of file sc_int_base.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
Referenced by sc_dt::nor_reduce().
operator int_type()
sc_dt::sc_int_base::operator int_type () const inline
Definition at line 906 of file sc_int_base.hh.
operator%=()
sc_int_base& sc_dt::sc_int_base::operator%= (int_type v) inline
Definition at line 717 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator%=().
operator&=()
sc_int_base& sc_dt::sc_int_base::operator &= (int_type v) inline
Definition at line 727 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator&=().
operator()() [1/2]
sc_int_subref & sc_dt::sc_int_base::operator() (int left, int right) inline
Definition at line 1293 of file sc_int_base.hh.
References sc_dt::sc_int_subref_r::initialize(), and sc_dt::sc_int_subref::m_pool.
operator()() [2/2]
const sc_int_subref_r & sc_dt::sc_int_base::operator() (int left, int right) const inline
Definition at line 1302 of file sc_int_base.hh.
References sc_dt::sc_int_subref_r::initialize(), and sc_dt::sc_int_subref::m_pool.
operator*=()
sc_int_base& sc_dt::sc_int_base::operator*= (int_type v) inline
Definition at line 701 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator*=().
operator++() [1/2]
sc_int_base& sc_dt::sc_int_base::operator++ () inline
Definition at line 770 of file sc_int_base.hh.
Referenced by sc_dt::sc_int< W >::operator++().
operator++() [2/2]
const sc_int_base sc_dt::sc_int_base::operator++ (int) inline
Definition at line 778 of file sc_int_base.hh.
operator+=()
sc_int_base& sc_dt::sc_int_base::operator+= (int_type v) inline
Definition at line 685 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator+=().
operator--() [1/2]
sc_int_base& sc_dt::sc_int_base::operator-- () inline
Definition at line 787 of file sc_int_base.hh.
Referenced by sc_dt::sc_int< W >::operator--().
operator--() [2/2]
const sc_int_base sc_dt::sc_int_base::operator-- (int) inline
Definition at line 795 of file sc_int_base.hh.
operator-=()
sc_int_base& sc_dt::sc_int_base::operator-= (int_type v) inline
Definition at line 693 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator-=().
operator/=()
sc_int_base& sc_dt::sc_int_base::operator/= (int_type v) inline
Definition at line 709 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator/=().
operator<<=()
sc_int_base& sc_dt::sc_int_base::operator<<= (int_type v) inline
Definition at line 752 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator<<=().
operator=() [1/19]
sc_int_base& sc_dt::sc_int_base::operator= (int_type v) inline
Definition at line 590 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator=(), operator=(), sc_dt::sc_int< W >::sc_int(), and sc_core::sc_signal< sc_dt::sc_int< W > >::update().
operator=() [2/19]
sc_int_base& sc_dt::sc_int_base::operator= (const sc_int_base & a) inline
Definition at line 598 of file sc_int_base.hh.
References m_val.
operator=() [3/19]
sc_int_base& sc_dt::sc_int_base::operator= (const sc_int_subref_r & a) inline
Definition at line 606 of file sc_int_base.hh.
References ArmISA::a.
operator=() [4/19]
template<class T > sc_int_base& sc_dt::sc_int_base::operator= (const sc_generic_base< T > & a) inline
Definition at line 615 of file sc_int_base.hh.
operator=() [5/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_signed & a)
Definition at line 451 of file sc_int_base.cc.
References extend_sign(), ArmISA::i, sc_dt::sc_signed::length(), m_len, sc_dt::sc_min(), sc_dt::sc_signed::sign(), and sc_dt::sc_signed::test().
operator=() [6/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_unsigned & a)
Definition at line 468 of file sc_int_base.cc.
References extend_sign(), ArmISA::i, sc_dt::sc_unsigned::length(), m_len, sc_dt::sc_min(), and sc_dt::sc_unsigned::test().
operator=() [7/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_fxval & a) inline
Definition at line 198 of file scfx_other_defs.hh.
References sc_dt::sc_fxval::get_bit(), ArmISA::i, sc_dt::sc_fxval::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [8/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_fxval_fast & a) inline
Definition at line 213 of file scfx_other_defs.hh.
References sc_dt::sc_fxval_fast::get_bit(), ArmISA::i, sc_dt::sc_fxval_fast::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [9/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_fxnum & a) inline
Definition at line 228 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [10/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_fxnum_fast & a) inline
Definition at line 243 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [11/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_bv_base & a)
Definition at line 485 of file sc_int_base.cc.
References extend_sign(), sc_dt::sc_bv_base::get_bit(), ArmISA::i, sc_dt::sc_bv_base::length(), m_len, and sc_dt::sc_min().
operator=() [12/19]
sc_int_base & sc_dt::sc_int_base::operator= (const sc_lv_base & a)
Definition at line 501 of file sc_int_base.cc.
References extend_sign(), sc_dt::sc_lv_base::get_bit(), ArmISA::i, sc_dt::sc_lv_base::length(), m_len, sc_dt::sc_min(), and to_bool().
operator=() [13/19]
sc_int_base & sc_dt::sc_int_base::operator= (const char * a)
Definition at line 517 of file sc_int_base.cc.
References PowerISA::aa, ArmISA::len, m_len, operator=(), sc_core::SC_ID_CONVERSION_FAILED_, sc_dt::SC_ON, SC_REPORT_ERROR, sc_dt::SC_TRN, and sc_dt::SC_WRAP.
operator=() [14/19]
sc_int_base& sc_dt::sc_int_base::operator= (unsigned long a) inline
Definition at line 636 of file sc_int_base.hh.
References ArmISA::a.
operator=() [15/19]
sc_int_base& sc_dt::sc_int_base::operator= (long a) inline
Definition at line 644 of file sc_int_base.hh.
References ArmISA::a.
operator=() [16/19]
sc_int_base& sc_dt::sc_int_base::operator= (unsigned int a) inline
Definition at line 652 of file sc_int_base.hh.
References ArmISA::a.
operator=() [17/19]
sc_int_base& sc_dt::sc_int_base::operator= (int a) inline
Definition at line 660 of file sc_int_base.hh.
References ArmISA::a.
operator=() [18/19]
sc_int_base& sc_dt::sc_int_base::operator= (uint64 a) inline
Definition at line 668 of file sc_int_base.hh.
References ArmISA::a.
operator=() [19/19]
sc_int_base& sc_dt::sc_int_base::operator= (double a) inline
Definition at line 676 of file sc_int_base.hh.
operator>>=()
sc_int_base& sc_dt::sc_int_base::operator>>= (int_type v) inline
Definition at line 760 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator>>=().
operator[]() [1/2]
sc_int_bitref & sc_dt::sc_int_base::operator[] (int i) inline
Definition at line 1253 of file sc_int_base.hh.
References sc_dt::sc_int_bitref_r::initialize(), and sc_dt::sc_int_bitref::m_pool.
operator[]() [2/2]
const sc_int_bitref_r & sc_dt::sc_int_base::operator[] (int i) const inline
Definition at line 1262 of file sc_int_base.hh.
References sc_dt::sc_int_bitref_r::initialize(), and sc_dt::sc_int_bitref::m_pool.
operator^=()
sc_int_base& sc_dt::sc_int_base::operator^= (int_type v) inline
Definition at line 743 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator^=().
operator|=()
sc_int_base& sc_dt::sc_int_base::operator|= (int_type v) inline
Definition at line 735 of file sc_int_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_int< W >::operator|=().
or_reduce()
bool sc_dt::sc_int_base::or_reduce () const
Definition at line 557 of file sc_int_base.cc.
References m_val.
Referenced by sc_dt::sc_int_subref_r::or_reduce(), and sc_dt::or_reduce().
print()
void sc_dt::sc_int_base::print (::std::ostream & os = ::std::cout) const inline
Definition at line 929 of file sc_int_base.hh.
References MipsISA::is, X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
range() [1/2]
sc_int_subref & sc_dt::sc_int_base::range (int left, int right) inline
Definition at line 1312 of file sc_int_base.hh.
References sc_dt::sc_int_subref_r::initialize(), and sc_dt::sc_int_subref::m_pool.
range() [2/2]
const sc_int_subref_r & sc_dt::sc_int_base::range (int left, int right) const inline
Definition at line 1321 of file sc_int_base.hh.
References sc_dt::sc_int_subref_r::initialize(), and sc_dt::sc_int_subref::m_pool.
scan()
void sc_dt::sc_int_base::scan (::std::istream & is = ::std::cin)
Definition at line 700 of file sc_int_base.cc.
References ArmISA::s.
Referenced by sc_dt::operator>>().
set() [1/2]
void sc_dt::sc_int_base::set (int i) inline
Definition at line 861 of file sc_int_base.hh.
References ArmISA::i, and sc_dt::UINT_ONE.
set() [2/2]
void sc_dt::sc_int_base::set (int i, bool v) inline
Definition at line 864 of file sc_int_base.hh.
References ArmISA::i, and sc_dt::UINT_ONE.
test()
bool sc_dt::sc_int_base::test (int i) const inline
Definition at line 859 of file sc_int_base.hh.
References sc_dt::UINT_ONE.
to_double()
double sc_dt::sc_int_base::to_double () const inline
Definition at line 917 of file sc_int_base.hh.
to_int()
int sc_dt::sc_int_base::to_int () const inline
Definition at line 911 of file sc_int_base.hh.
to_int64()
int64 sc_dt::sc_int_base::to_int64 () const inline
Definition at line 915 of file sc_int_base.hh.
to_long()
long sc_dt::sc_int_base::to_long () const inline
Definition at line 913 of file sc_int_base.hh.
to_string() [1/2]
const std::string sc_dt::sc_int_base::to_string (sc_numrep numrep = SC_DEC) const
Definition at line 539 of file sc_int_base.cc.
References PowerISA::aa, ArmISA::len, m_len, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_string() [2/2]
const std::string sc_dt::sc_int_base::to_string (sc_numrep numrep, bool w_prefix) const
Definition at line 547 of file sc_int_base.cc.
References PowerISA::aa, ArmISA::len, m_len, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_uint()
unsigned int sc_dt::sc_int_base::to_uint () const inline
Definition at line 912 of file sc_int_base.hh.
to_uint64()
uint64 sc_dt::sc_int_base::to_uint64 () const inline
Definition at line 916 of file sc_int_base.hh.
to_ulong()
unsigned long sc_dt::sc_int_base::to_ulong () const inline
Definition at line 914 of file sc_int_base.hh.
value()
int_type sc_dt::sc_int_base::value () const inline
Definition at line 910 of file sc_int_base.hh.
xnor_reduce()
bool sc_dt::sc_int_base::xnor_reduce () const inline
Definition at line 902 of file sc_int_base.hh.
References sc_dt::xor_reduce().
Referenced by sc_dt::xnor_reduce().
xor_reduce()
bool sc_dt::sc_int_base::xor_reduce () const
Definition at line 560 of file sc_int_base.cc.
References m_ulen, m_val, ArmISA::mask, ArmISA::n, SC_INTWIDTH, sc_dt::UINT_ZERO, and X86ISA::val.
Referenced by sc_dt::sc_int_subref_r::xor_reduce(), and sc_dt::xor_reduce().
Friends And Related Function Documentation
operator!=
bool operator!= (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 812 of file sc_int_base.hh.
operator<
bool operator< (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 818 of file sc_int_base.hh.
operator<=
bool operator<= (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 824 of file sc_int_base.hh.
operator==
bool operator== (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 806 of file sc_int_base.hh.
operator>
bool operator> (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 830 of file sc_int_base.hh.
operator>=
bool operator>= (const sc_int_base & a, const sc_int_base & b) friend
Definition at line 836 of file sc_int_base.hh.
sc_int_bitref
friend class sc_int_bitref friend
Definition at line 497 of file sc_int_base.hh.
sc_int_bitref_r
friend class sc_int_bitref_r friend
Definition at line 496 of file sc_int_base.hh.
sc_int_subref
friend class sc_int_subref friend
Definition at line 499 of file sc_int_base.hh.
sc_int_subref_r
friend class sc_int_subref_r friend
Definition at line 498 of file sc_int_base.hh.
Member Data Documentation
m_len
int sc_dt::sc_int_base::m_len protected
Definition at line 938 of file sc_int_base.hh.
Referenced by concat_get_ctrl(), concat_get_data(), operator=(), and to_string().
m_ulen
int sc_dt::sc_int_base::m_ulen protected
Definition at line 939 of file sc_int_base.hh.
Referenced by xor_reduce().
m_val
int_type sc_dt::sc_int_base::m_val protected
Definition at line 937 of file sc_int_base.hh.
Referenced by and_reduce(), concat_get_data(), sc_dt::operator!=(), sc_dt::operator<(), sc_dt::operator<=(), sc_dt::sc_int< W >::operator=(), operator=(), sc_dt::operator==(), sc_dt::operator>(), sc_dt::operator>=(), or_reduce(), and xor_reduce().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_int_base.hh
systemc/dt/int/sc_int_base.cc
systemc/ext/dt/fx/scfx_other_defs.hh