gem5: Trace::TarmacBaseRecord Class Reference
Trace::TarmacBaseRecord Class Reference abstract
#include <tarmac_base.hh>
Classes
struct InstEntry
TARMAC instruction trace record.
struct MemEntry
TARMAC memory access trace record (stores only).
struct RegEntry
TARMAC register trace record.
Public Types
enum TarmacRecordType { TARMAC_INST, TARMAC_REG, TARMAC_MEM, TARMAC_UNSUPPORTED }
TARMAC trace record type.
enum ISetState { ISET_ARM, ISET_THUMB, ISET_A64, ISET_UNSUPPORTED }
ARM instruction set state.
enum RegType {
REG_R, REG_X, REG_S, REG_D,
REG_P, REG_Q, REG_Z, REG_MISC
}
ARM register type.
Public Member Functions
TarmacBaseRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, ArmISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual void dump ()=0
Public Member Functions inherited from Trace::InstRecord
InstRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual ~InstRecord ()
void setWhen (Tick new_when)
void setMem (Addr a, Addr s, unsigned f)
template<typename T , size_t N>
void setData (std::array< T, N > d)
void setData (uint64_t d)
void setData (uint32_t d)
void setData (uint16_t d)
void setData (uint8_t d)
void setData (int64_t d)
void setData (int32_t d)
void setData (int16_t d)
void setData (int8_t d)
void setData (double d)
void setData (::VecRegContainer< TheISA::VecRegSizeBytes > &d)
void setData (::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > &d)
void setFetchSeq (InstSeqNum seq)
void setCPSeq (InstSeqNum seq)
void setPredicate (bool val)
Tick getWhen () const
ThreadContext * getThread () const
StaticInstPtr getStaticInst () const
TheISA::PCState getPCState () const
StaticInstPtr getMacroStaticInst () const
Addr getAddr () const
Addr getSize () const
unsigned getFlags () const
bool getMemValid () const
uint64_t getIntData () const
double getFloatData () const
int getDataStatus () const
InstSeqNum getFetchSeq () const
bool getFetchSeqValid () const
InstSeqNum getCpSeq () const
bool getCpSeqValid () const
Static Public Member Functions
static ISetState pcToISetState (ArmISA::PCState pc)
Returns the Instruction Set State according to the current PCState.
Additional Inherited Members
Protected Types inherited from Trace::InstRecord
enum DataStatus {
DataInvalid = 0, DataInt8 = 1, DataInt16 = 2, DataInt32 = 4,
DataInt64 = 8, DataDouble = 3, DataVec = 5, DataVecPred = 6
}
What size of data was written?
Protected Attributes inherited from Trace::InstRecord
Tick when
ThreadContext * thread
StaticInstPtr staticInst
TheISA::PCState pc
StaticInstPtr macroStaticInst
Addr addr
The address that was accessed.
Addr size
The size of the memory request.
unsigned flags
The flags that were assigned to the request.
union {
uint64_t as_int
double as_double
::VecRegContainer< TheISA::VecRegSizeBytes > * as_vec
::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > * as_pred
} data
InstSeqNum fetch_seq
InstSeqNum cp_seq
enum Trace::InstRecord::DataStatus data_status
bool mem_valid
Are the memory fields in the record valid?
bool fetch_seq_valid
Are the fetch sequence number fields valid?
bool cp_seq_valid
Are the commit sequence number fields valid?
bool predicate
is the predicate for execution this inst true or false (not execed)?
Detailed Description
Definition at line 65 of file tarmac_base.hh.
Member Enumeration Documentation
ISetState
enum Trace::TarmacBaseRecord::ISetState
ARM instruction set state.
Enumerator
ISET_ARM
ISET_THUMB
ISET_A64
ISET_UNSUPPORTED
Definition at line 77 of file tarmac_base.hh.
RegType
enum Trace::TarmacBaseRecord::RegType
ARM register type.
Enumerator
REG_R
REG_X
REG_S
REG_D
REG_P
REG_Q
REG_Z
REG_MISC
Definition at line 81 of file tarmac_base.hh.
TarmacRecordType
enum Trace::TarmacBaseRecord::TarmacRecordType
TARMAC trace record type.
Enumerator
TARMAC_INST
TARMAC_REG
TARMAC_MEM
TARMAC_UNSUPPORTED
Definition at line 69 of file tarmac_base.hh.
Constructor & Destructor Documentation
TarmacBaseRecord()
Trace::TarmacBaseRecord::TarmacBaseRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, ArmISA::PCState _pc, const StaticInstPtr _macroStaticInst = NULL)
Definition at line 54 of file tarmac_base.cc.
References Trace::InstRecord::addr, ArmISA::c, StaticInst::disassemble(), Trace::TarmacBaseRecord::InstEntry::InstEntry(), StaticInst::machInst, ArmISA::MISCREG_CPSR, ArmISA::mode, ArmISA::MODE_USER, ArmISA::opcode, Trace::InstRecord::pc, pcToISetState(), Trace::InstRecord::predicate, ThreadContext::readMiscRegNoEffect(), Trace::TarmacBaseRecord::RegEntry::RegEntry(), Trace::InstRecord::staticInst, and Trace::InstRecord::thread.
Member Function Documentation
dump()
virtual void Trace::TarmacBaseRecord::dump () pure virtual
Implements Trace::InstRecord.
Implemented in Trace::TarmacTracerRecord, and Trace::TarmacParserRecord.
pcToISetState()
TarmacBaseRecord::ISetState Trace::TarmacBaseRecord::pcToISetState (ArmISA::PCState pc) static
Returns the Instruction Set State according to the current PCState.
Parameters
pc program counter (PCState) variable
Returns
Instruction Set State for the given PCState
Definition at line 102 of file tarmac_base.cc.
References ISET_A64, ISET_ARM, ISET_THUMB, and ISET_UNSUPPORTED.
Referenced by Trace::TarmacParserRecord::dump(), and TarmacBaseRecord().
The documentation for this class was generated from the following files:
arch/arm/tracers/tarmac_base.hh
arch/arm/tracers/tarmac_base.cc