gem5: BasePrefetcher::PrefetchInfo Class Reference
BasePrefetcher::PrefetchInfo Class Reference
Class containing the information needed by the prefetch to train and generate new prefetch requests.
#include <base.hh>
Public Member Functions
Addr getAddr () const
Obtains the address value of this Prefetcher address.
bool isSecure () const
Returns true if the address targets the secure memory space.
Addr getPC () const
Returns the program counter that generated this request.
bool hasPC () const
Returns true if the associated program counter is valid.
MasterID getMasterId () const
Gets the requestor ID that generated this address.
unsigned int getSize () const
Gets the size of the request triggering this event.
bool isWrite () const
Checks if the request that caused this prefetch event was a write request.
Addr getPaddr () const
Gets the physical address of the request.
bool isCacheMiss () const
Check if this event comes from a cache miss.
template<typename T >
T get (ByteOrder endian) const
Gets the associated data of the request triggering the event.
bool sameAddr (PrefetchInfo const &pfi) const
Check for equality.
PrefetchInfo (PacketPtr pkt, Addr addr, bool miss)
Constructs a PrefetchInfo using a PacketPtr.
PrefetchInfo (PrefetchInfo const &pfi, Addr addr)
Constructs a PrefetchInfo using a new address value and another PrefetchInfo as a reference.
~PrefetchInfo ()
Private Attributes
Addr address
The address used to train and generate prefetches.
Addr pc
The program counter that generated this address.
MasterID masterId
The requestor ID that generated this address.
bool validPC
Validity bit for the PC of this address.
bool secure
Whether this address targets the secure memory space.
unsigned int size
Size in bytes of the request triggering this event.
bool write
Whether this event comes from a write request.
Addr paddress
Physical address, needed because address can be virtual.
bool cacheMiss
Whether this event comes from a cache miss.
uint8_t * data
Pointer to the associated request data.
Detailed Description
Class containing the information needed by the prefetch to train and generate new prefetch requests.
Definition at line 92 of file base.hh.
Constructor & Destructor Documentation
PrefetchInfo() [1/2]
BasePrefetcher::PrefetchInfo::PrefetchInfo (PacketPtr pkt, Addr addr, bool miss)
Constructs a PrefetchInfo using a PacketPtr.
Parameters
pkt PacketPtr used to generate the PrefetchInfo
addr the address value of the new object, this address is used to train the prefetcher
miss whether this event comes from a cache miss
Definition at line 59 of file base.cc.
References data, Packet::getAddr(), Packet::getConstPtr(), ArmISA::offset, Packet::req, and write.
PrefetchInfo() [2/2]
BasePrefetcher::PrefetchInfo::PrefetchInfo (PrefetchInfo const & pfi, Addr addr)
Constructs a PrefetchInfo using a new address value and another PrefetchInfo as a reference.
Parameters
pfi PrefetchInfo used to generate this new object
addr the address value of the new object
Definition at line 75 of file base.cc.
~PrefetchInfo()
BasePrefetcher::PrefetchInfo::~PrefetchInfo () inline
Definition at line 250 of file base.hh.
References data.
Member Function Documentation
get()
template<typename T > T BasePrefetcher::PrefetchInfo::get (ByteOrder endian) const inline
Gets the associated data of the request triggering the event.
Parameters
Byte ordering of the stored data
Returns
the data
Definition at line 205 of file base.hh.
References betoh(), BigEndianByteOrder, letoh(), LittleEndianByteOrder, and panic.
Referenced by IndirectMemoryPrefetcher::calculatePrefetch().
getAddr()
Addr BasePrefetcher::PrefetchInfo::getAddr () const inline
Obtains the address value of this Prefetcher address.
Returns
the addres value.
Definition at line 119 of file base.hh.
Referenced by TaggedPrefetcher::calculatePrefetch(), DeltaCorrelatingPredictionTables::calculatePrefetch(), IrregularStreamBufferPrefetcher::calculatePrefetch(), BOPPrefetcher::calculatePrefetch(), SBOOEPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), PIFPrefetcher::calculatePrefetch(), AccessMapPatternMatching::calculatePrefetch(), IndirectMemoryPrefetcher::calculatePrefetch(), STeMSPrefetcher::calculatePrefetch(), SignaturePathPrefetcher::calculatePrefetch(), QueuedPrefetcher::insert(), QueuedPrefetcher::notify(), and sameAddr().
getMasterId()
MasterID BasePrefetcher::PrefetchInfo::getMasterId () const inline
Gets the requestor ID that generated this address.
Returns
the requestor ID that generated this address
Definition at line 156 of file base.hh.
References BasePrefetcher::masterId.
Referenced by StridePrefetcher::calculatePrefetch().
getPaddr()
Addr BasePrefetcher::PrefetchInfo::getPaddr () const inline
Gets the physical address of the request.
Returns
physical address of the request
Definition at line 184 of file base.hh.
Referenced by STeMSPrefetcher::calculatePrefetch().
getPC()
Addr BasePrefetcher::PrefetchInfo::getPC () const inline
Returns the program counter that generated this request.
Returns
the pc value
Definition at line 137 of file base.hh.
References MipsISA::pc.
Referenced by DeltaCorrelatingPredictionTables::calculatePrefetch(), IrregularStreamBufferPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), IndirectMemoryPrefetcher::calculatePrefetch(), STeMSPrefetcher::calculatePrefetch(), QueuedPrefetcher::DeferredPacket::createPkt(), and QueuedPrefetcher::createPrefetchRequest().
getSize()
unsigned int BasePrefetcher::PrefetchInfo::getSize () const inline
Gets the size of the request triggering this event.
Returns
the size in bytes of the request triggering this event
Definition at line 165 of file base.hh.
Referenced by IndirectMemoryPrefetcher::calculatePrefetch().
hasPC()
bool BasePrefetcher::PrefetchInfo::hasPC () const inline
Returns true if the associated program counter is valid.
Returns
true if the program counter has a valid value
Definition at line 147 of file base.hh.
Referenced by DeltaCorrelatingPredictionTables::calculatePrefetch(), IrregularStreamBufferPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), IndirectMemoryPrefetcher::calculatePrefetch(), STeMSPrefetcher::calculatePrefetch(), and QueuedPrefetcher::DeferredPacket::createPkt().
isCacheMiss()
bool BasePrefetcher::PrefetchInfo::isCacheMiss () const inline
Check if this event comes from a cache miss.
Returns
true if this event comes from a cache miss
Definition at line 193 of file base.hh.
Referenced by IndirectMemoryPrefetcher::calculatePrefetch(), and STeMSPrefetcher::calculatePrefetch().
isSecure()
bool BasePrefetcher::PrefetchInfo::isSecure () const inline
Returns true if the address targets the secure memory space.
Returns
true if the address targets the secure memory space.
Definition at line 128 of file base.hh.
Referenced by IrregularStreamBufferPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), AccessMapPatternMatching::calculatePrefetch(), IndirectMemoryPrefetcher::calculatePrefetch(), STeMSPrefetcher::calculatePrefetch(), SignaturePathPrefetcher::calculatePrefetch(), QueuedPrefetcher::DeferredPacket::createPkt(), QueuedPrefetcher::insert(), QueuedPrefetcher::notify(), and sameAddr().
isWrite()
bool BasePrefetcher::PrefetchInfo::isWrite () const inline
Checks if the request that caused this prefetch event was a write request.
Returns
true if the request causing this event is a write request
Definition at line 175 of file base.hh.
Referenced by IndirectMemoryPrefetcher::calculatePrefetch().
sameAddr()
bool BasePrefetcher::PrefetchInfo::sameAddr (PrefetchInfo const & pfi) const inline
Check for equality.
Parameters
pfi PrefetchInfo to compare against
Returns
True if this object and the provided one are equal
Definition at line 227 of file base.hh.
References addr, getAddr(), isSecure(), and BasePrefetcher::PrefetchListener::miss.
Member Data Documentation
address
Addr BasePrefetcher::PrefetchInfo::address private
The address used to train and generate prefetches.
Definition at line 94 of file base.hh.
cacheMiss
bool BasePrefetcher::PrefetchInfo::cacheMiss private
Whether this event comes from a cache miss.
Definition at line 110 of file base.hh.
data
uint8_t* BasePrefetcher::PrefetchInfo::data private
Pointer to the associated request data.
Definition at line 112 of file base.hh.
Referenced by PrefetchInfo().
masterId
MasterID BasePrefetcher::PrefetchInfo::masterId private
The requestor ID that generated this address.
Definition at line 98 of file base.hh.
paddress
Addr BasePrefetcher::PrefetchInfo::paddress private
Physical address, needed because address can be virtual.
Definition at line 108 of file base.hh.
pc
Addr BasePrefetcher::PrefetchInfo::pc private
The program counter that generated this address.
Definition at line 96 of file base.hh.
secure
bool BasePrefetcher::PrefetchInfo::secure private
Whether this address targets the secure memory space.
Definition at line 102 of file base.hh.
size
unsigned int BasePrefetcher::PrefetchInfo::size private
Size in bytes of the request triggering this event.
Definition at line 104 of file base.hh.
validPC
bool BasePrefetcher::PrefetchInfo::validPC private
Validity bit for the PC of this address.
Definition at line 100 of file base.hh.
write
bool BasePrefetcher::PrefetchInfo::write private
Whether this event comes from a write request.
Definition at line 106 of file base.hh.
Referenced by PrefetchInfo().
The documentation for this class was generated from the following files:
mem/cache/prefetch/base.hh
mem/cache/prefetch/base.cc