gem5: X86ISA::Cmos::X86RTC Class Reference
X86ISA::Cmos::X86RTC Class Reference
#include <cmos.hh>
Public Member Functions
X86RTC (EventManager *em, const std::string &n, const struct tm time, bool bcd, Tick frequency, int int_pin_count)
Public Member Functions inherited from MC146818
MC146818 (EventManager *em, const std::string &name, const struct tm time, bool bcd, Tick frequency)
virtual ~MC146818 ()
virtual void startup ()
Start ticking.
void writeData (const uint8_t addr, const uint8_t data)
RTC write data.
uint8_t readData (const uint8_t addr)
RTC read data.
void tickClock ()
void serialize (const std::string &base, CheckpointOut &cp) const
Serialize this object to the given output stream.
void unserialize (const std::string &base, CheckpointIn &cp)
Reconstruct the state of this object from a checkpoint.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Attributes
std::vector< IntSourcePin< X86RTC > * > intPin
Protected Member Functions
void handleEvent ()
Additional Inherited Members
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 56 of file cmos.hh.
Constructor & Destructor Documentation
X86RTC()
X86ISA::Cmos::X86RTC::X86RTC (EventManager * em, const std::string & n, const struct tm time, bool bcd, Tick frequency, int int_pin_count) inline
Definition at line 61 of file cmos.hh.
References csprintf(), handleEvent(), ArmISA::i, and X86ISA::Cmos::rtc.
Member Function Documentation
handleEvent()
void X86ISA::Cmos::X86RTC::handleEvent () protected virtual
Reimplemented from MC146818.
Definition at line 38 of file cmos.cc.
References intPin.
Referenced by X86RTC().
Member Data Documentation
intPin
std::vector<IntSourcePin<X86RTC> *> X86ISA::Cmos::X86RTC::intPin
Definition at line 59 of file cmos.hh.
Referenced by X86ISA::Cmos::getPort(), and handleEvent().
The documentation for this class was generated from the following files:
dev/x86/cmos.hh
dev/x86/cmos.cc