gem5: Minor::Decode Class Reference
Minor::Decode Class Reference
#include <decode.hh>
Classes
struct DecodeThreadInfo
Data members after this line are cycle-to-cycle state.
Public Member Functions
Decode (const std::string &name, MinorCPU &cpu_, MinorCPUParams &params, Latch< ForwardInstData >::Output inp_, Latch< ForwardInstData >::Input out_, std::vector< InputBuffer< ForwardInstData >> &next_stage_input_buffer)
void evaluate ()
Pass on input/buffer data to the output if you can.
void minorTrace () const
bool isDrained ()
Is this stage drained? For Decoed, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain into Decode and on to Execute which is responsible for actually killing instructions.
Public Member Functions inherited from Named
Named (const std::string &name_)
const std::string & name () const
Public Attributes
std::vector< InputBuffer< ForwardInstData > > inputBuffer
Protected Member Functions
const ForwardInstData * getInput (ThreadID tid)
Get a piece of data to work on, or 0 if there is no data.
void popInput (ThreadID tid)
Pop an element off the input buffer, if there are any.
ThreadID getScheduledThread ()
Use the current threading policy to determine the next thread to decode from.
Protected Attributes
MinorCPU & cpu
Pointer back to the containing CPU.
Latch< ForwardInstData >::Output inp
Input port carrying macro instructions from Fetch2.
Latch< ForwardInstData >::Input out
Output port carrying micro-op decomposed instructions to Execute.
std::vector< InputBuffer< ForwardInstData > > & nextStageReserve
Interface to reserve space in the next stage.
unsigned int outputWidth
Width of output of this stage/input of next in instructions.
bool processMoreThanOneInput
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
std::vector< DecodeThreadInfo > decodeInfo
ThreadID threadPriority
Protected Attributes inherited from Named
const std::string _name
Detailed Description
Definition at line 62 of file decode.hh.
Constructor & Destructor Documentation
Decode()
Minor::Decode::Decode (const std::string & name, MinorCPU & cpu_, MinorCPUParams & params, Latch< ForwardInstData >::Output inp_, Latch< ForwardInstData >::Input out_, std::vector< InputBuffer< ForwardInstData >> & next_stage_input_buffer)
Definition at line 48 of file decode.cc.
References fatal, inputBuffer, outputWidth, and sc_dt::to_string().
Member Function Documentation
evaluate()
void Minor::Decode::evaluate ()
Pass on input/buffer data to the output if you can.
Definition at line 124 of file decode.cc.
References ActivityRecorder::activateStage(), ActivityRecorder::activity(), MinorCPU::activityRecorder, StaticInst::advancePC(), decodeInfo, Minor::Pipeline::DecodeStageId, DPRINTF, Minor::Decode::DecodeThreadInfo::execSeqNum, StaticInst::fetchMicroop(), getInput(), getScheduledThread(), ArmISA::i, Minor::Decode::DecodeThreadInfo::inMacroop, inp, inputBuffer, Minor::Decode::DecodeThreadInfo::inputIndex, Minor::ForwardInstData::insts, InvalidThreadID, Minor::ForwardInstData::isBubble(), StaticInst::isLastMicroop(), StaticInst::isMacroop(), Minor::Decode::DecodeThreadInfo::microopPC, nextStageReserve, NoFault, BaseCPU::numThreads, out, outputWidth, popInput(), processMoreThanOneInput, Minor::ForwardInstData::resize(), Minor::ForwardInstData::threadId, and Minor::ForwardInstData::width().
Referenced by Minor::Pipeline::evaluate().
getInput()
const ForwardInstData * Minor::Decode::getInput (ThreadID tid) protected
Get a piece of data to work on, or 0 if there is no data.
Definition at line 82 of file decode.cc.
References inputBuffer, and Minor::ForwardInstData::isBubble().
Referenced by evaluate(), and getScheduledThread().
getScheduledThread()
ThreadID Minor::Decode::getScheduledThread () inline protected
Use the current threading policy to determine the next thread to decode from.
Definition at line 297 of file decode.cc.
References decodeInfo, getInput(), InvalidThreadID, panic, MinorCPU::randomPriority(), MinorCPU::roundRobinPriority(), MinorCPU::threadPolicy, and threadPriority.
Referenced by evaluate().
isDrained()
bool Minor::Decode::isDrained ()
Is this stage drained? For Decoed, draining is initiated by Execute halting Fetch1 causing Fetch2 to naturally drain into Decode and on to Execute which is responsible for actually killing instructions.
Definition at line 327 of file decode.cc.
References inp, and inputBuffer.
Referenced by Minor::Pipeline::isDrained().
minorTrace()
void Minor::Decode::minorTrace () const
Definition at line 338 of file decode.cc.
References data, decodeInfo, inputBuffer, MINORTRACE, and out.
Referenced by Minor::Pipeline::minorTrace().
popInput()
void Minor::Decode::popInput (ThreadID tid) protected
Pop an element off the input buffer, if there are any.
Definition at line 95 of file decode.cc.
References cpu, curTick(), decodeInfo, BaseCPU::getContext(), Trace::InstTracer::getInstRecord(), BaseCPU::getTracer(), and inputBuffer.
Referenced by evaluate().
Member Data Documentation
cpu
MinorCPU& Minor::Decode::cpu protected
Pointer back to the containing CPU.
Definition at line 66 of file decode.hh.
Referenced by popInput().
decodeInfo
std::vector<DecodeThreadInfo> Minor::Decode::decodeInfo protected
Definition at line 127 of file decode.hh.
Referenced by evaluate(), getScheduledThread(), minorTrace(), and popInput().
inp
Latch<ForwardInstData>::Output Minor::Decode::inp protected
Input port carrying macro instructions from Fetch2.
Definition at line 69 of file decode.hh.
Referenced by evaluate(), and isDrained().
inputBuffer
std::vector<InputBuffer<ForwardInstData> > Minor::Decode::inputBuffer
Definition at line 85 of file decode.hh.
Referenced by Decode(), evaluate(), getInput(), isDrained(), minorTrace(), and popInput().
nextStageReserve
std::vector<InputBuffer<ForwardInstData> >& Minor::Decode::nextStageReserve protected
Interface to reserve space in the next stage.
Definition at line 74 of file decode.hh.
Referenced by evaluate().
out
Latch<ForwardInstData>::Input Minor::Decode::out protected
Output port carrying micro-op decomposed instructions to Execute.
Definition at line 71 of file decode.hh.
Referenced by evaluate(), and minorTrace().
outputWidth
unsigned int Minor::Decode::outputWidth protected
Width of output of this stage/input of next in instructions.
Definition at line 77 of file decode.hh.
Referenced by Decode(), and evaluate().
processMoreThanOneInput
bool Minor::Decode::processMoreThanOneInput protected
If true, more than one input word can be processed each cycle if there is room in the output to contain its processed data.
Definition at line 81 of file decode.hh.
Referenced by evaluate().
threadPriority
ThreadID Minor::Decode::threadPriority protected
Definition at line 128 of file decode.hh.
Referenced by getScheduledThread().
The documentation for this class was generated from the following files:
cpu/minor/decode.hh
cpu/minor/decode.cc