gem5: NoRegAddrOperand Class Reference
NoRegAddrOperand Class Reference
#include <operand.hh>
Public Member Functions
void init (unsigned opOffset, const BrigObject *obj)
uint64_t calcUniform ()
void calcVector (Wavefront *w, std::vector< Addr > &addrVec)
uint64_t calcLane (Wavefront *w, int lane=0)
std::string disassemble ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Additional Inherited Members
Public Attributes inherited from AddrOperandBase
int64_t offset
const char * name = nullptr
StorageElement * storageElement
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Protected Member Functions inherited from AddrOperandBase
void parseAddr (const Brig::BrigOperandAddress *op, const BrigObject *obj)
std::string disassemble (std::string reg_disassembly)
uint64_t calcUniformBase ()
Detailed Description
Definition at line 706 of file operand.hh.
Member Function Documentation
calcLane()
uint64_t NoRegAddrOperand::calcLane (Wavefront * w, int lane = 0) inline virtual
Implements AddrOperandBase.
Definition at line 723 of file operand.hh.
calcUniform()
uint64_t NoRegAddrOperand::calcUniform () inline
Definition at line 717 of file operand.hh.
References AddrOperandBase::calcUniformBase().
calcVector()
void NoRegAddrOperand::calcVector (Wavefront * w, std::vector< Addr > & addrVec) inline virtual
Implements AddrOperandBase.
Definition at line 729 of file operand.hh.
References Wavefront::computeUnit, and ComputeUnit::wfSize().
disassemble()
std::string NoRegAddrOperand::disassemble ()
Definition at line 438 of file operand.cc.
References AddrOperandBase::disassemble().
init()
void NoRegAddrOperand::init (unsigned opOffset, const BrigObject * obj)
Definition at line 422 of file operand.cc.
References Brig::BRIG_KIND_OPERAND_ADDRESS, fatal, BrigObject::getOperand(), Brig::BrigUInt64::hi, Brig::BrigBase::kind, Brig::BrigUInt64::lo, ArmISA::offset, and Brig::BrigOperandAddress::offset.
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc