gem5: BaseCache::MemSidePort Class Reference
BaseCache::MemSidePort Class Reference
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
#include <base.hh>
Public Member Functions
MemSidePort (const std::string &_name, BaseCache *_cache, const std::string &_label)
Public Member Functions inherited from BaseCache::CacheMasterPort
void schedSendEvent (Tick time)
Schedule a send of a request packet (from the MSHR).
Public Member Functions inherited from QueuedMasterPort
QueuedMasterPort (const std::string &name, SimObject *owner, ReqPacketQueue &req_queue, SnoopRespPacketQueue &snoop_resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of two packet queues.
virtual ~QueuedMasterPort ()
void schedTimingReq (PacketPtr pkt, Tick when)
Schedule the sending of a timing request.
void schedTimingSnoopResp (PacketPtr pkt, Tick when)
Schedule the sending of a timing snoop response.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
virtual void recvTimingSnoopReq (PacketPtr pkt)
Receive a timing snoop request from the peer.
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the peer.
virtual Tick recvAtomicSnoop (PacketPtr pkt)
Receive an atomic snoop request packet from our peer.
virtual void recvFunctionalSnoop (PacketPtr pkt)
Receive a functional snoop request packet from the peer.
Protected Member Functions inherited from BaseCache::CacheMasterPort
CacheMasterPort (const std::string &_name, BaseCache *_cache, ReqPacketQueue &_reqQueue, SnoopRespPacketQueue &_snoopRespQueue)
virtual bool isSnooping () const
Memory-side port always snoops.
Protected Member Functions inherited from QueuedMasterPort
void recvReqRetry ()
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
void recvRetrySnoopResp ()
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from MasterPort
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Attributes
CacheReqPacketQueue _reqQueue
The cache-specific queue.
SnoopRespPacketQueue _snoopRespQueue
BaseCache * cache
Additional Inherited Members
Protected Attributes inherited from QueuedMasterPort
ReqPacketQueue & reqQueue
Packet queue used to store outgoing requests.
SnoopRespPacketQueue & snoopRespQueue
Packet queue used to store outgoing snoop responses.
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
Definition at line 212 of file base.hh.
Constructor & Destructor Documentation
MemSidePort()
BaseCache::MemSidePort::MemSidePort (const std::string & _name, BaseCache * _cache, const std::string & _label)
Definition at line 2477 of file base.cc.
Member Function Documentation
recvAtomicSnoop()
Tick BaseCache::MemSidePort::recvAtomicSnoop (PacketPtr pkt) protected virtual
Receive an atomic snoop request packet from our peer.
Implements AtomicRequestProtocol.
Definition at line 2421 of file base.cc.
References System::bypassCaches(), BaseCache::CpuSidePort::cache, BaseCache::recvAtomicSnoop(), and BaseCache::system.
recvFunctionalSnoop()
void BaseCache::MemSidePort::recvFunctionalSnoop (PacketPtr pkt) protected virtual
Receive a functional snoop request packet from the peer.
Implements FunctionalRequestProtocol.
Definition at line 2430 of file base.cc.
References System::bypassCaches(), BaseCache::CpuSidePort::cache, BaseCache::functionalAccess(), and BaseCache::system.
recvTimingResp()
bool BaseCache::MemSidePort::recvTimingResp (PacketPtr pkt) protected virtual
Receive a timing response from the peer.
Implements TimingRequestProtocol.
Definition at line 2403 of file base.cc.
References BaseCache::CpuSidePort::cache, and BaseCache::recvTimingResp().
recvTimingSnoopReq()
void BaseCache::MemSidePort::recvTimingSnoopReq (PacketPtr pkt) protected virtual
Receive a timing snoop request from the peer.
Implements TimingRequestProtocol.
Definition at line 2411 of file base.cc.
References System::bypassCaches(), BaseCache::CpuSidePort::cache, BaseCache::recvTimingSnoopReq(), and BaseCache::system.
Member Data Documentation
_reqQueue
CacheReqPacketQueue BaseCache::MemSidePort::_reqQueue private
The cache-specific queue.
Definition at line 217 of file base.hh.
_snoopRespQueue
SnoopRespPacketQueue BaseCache::MemSidePort::_snoopRespQueue private
Definition at line 219 of file base.hh.
cache
BaseCache* BaseCache::MemSidePort::cache private
Definition at line 222 of file base.hh.
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc