gem5: sc_dt::sc_fix_fast Class Reference
sc_dt::sc_fix_fast Class Reference
#include <sc_fix.hh>
Public Member Functions
sc_fix_fast (sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, sc_fxnum_fast_observer *=0)
sc_fix_fast (sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_fix_fast (sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_fix_fast (const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (int, int, sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (const sc_fxtype_params &, sc_fxnum_fast_observer *=0)
sc_fix_fast (const sc_fxtype_params &, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_fix_fast (const sc_fix_fast &)
const sc_fix_fast operator~ () const
sc_fix_fast & operator= (const sc_fix_fast &)
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_fix_fast & operator++ ()
sc_fix_fast & operator-- ()
Public Member Functions inherited from sc_dt::sc_fxnum_fast
const sc_fxval_fast operator- () const
const sc_fxval_fast operator+ () const
DECL_BIN_OP_T (/, int64) DECL_BIN_OP_T(/
uint64 DECL_BIN_OP_T (/, const sc_int_base &) DECL_BIN_OP_T(/
uint64 const sc_uint_base & DECL_BIN_OP_T (/, const sc_signed &) friend const sc_fxval_fast operator<<(const sc_fxnum_fast &
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_fxnum_fast & operator++ ()
sc_fxnum_fast & operator-- ()
const sc_fxnum_fast_bitref operator[] (int) const
sc_fxnum_fast_bitref operator[] (int)
const sc_fxnum_fast_bitref bit (int) const
sc_fxnum_fast_bitref bit (int)
const sc_fxnum_fast_subref operator() (int, int) const
sc_fxnum_fast_subref operator() (int, int)
const sc_fxnum_fast_subref range (int, int) const
sc_fxnum_fast_subref range (int, int)
const sc_fxnum_fast_subref operator() () const
sc_fxnum_fast_subref operator() ()
const sc_fxnum_fast_subref range () const
sc_fxnum_fast_subref range ()
operator double () const
short to_short () const
unsigned short to_ushort () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
float to_float () const
double to_double () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
const std::string to_string (sc_fmt) const
const std::string to_string (sc_numrep, sc_fmt) const
const std::string to_string (sc_numrep, bool, sc_fmt) const
const std::string to_dec () const
const std::string to_bin () const
const std::string to_oct () const
const std::string to_hex () const
bool is_neg () const
bool is_zero () const
bool is_normal () const
bool quantization_flag () const
bool overflow_flag () const
const sc_fxval_fast value () const
int wl () const
int iwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
const sc_fxtype_params & type_params () const
const sc_fxcast_switch & cast_switch () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
void observer_read () const
bool get_bit (int) const
Friends
void b_not (sc_fix_fast &, const sc_fix_fast &)
const sc_fix_fast operator& (const sc_fix_fast &, const sc_fix_fast &)
const sc_fix_fast operator^ (const sc_fix_fast &, const sc_fix_fast &)
const sc_fix_fast operator| (const sc_fix_fast &, const sc_fix_fast &)
void b_and (sc_fix_fast &, const sc_fix_fast &, const sc_fix_fast &)
void b_or (sc_fix_fast &, const sc_fix_fast &, const sc_fix_fast &)
void b_xor (sc_fix_fast &, const sc_fix_fast &, const sc_fix_fast &)
Additional Inherited Members
Public Attributes inherited from sc_dt::sc_fxnum_fast
uint64 const sc_uint_base int
Protected Member Functions inherited from sc_dt::sc_fxnum_fast
sc_fxnum_fast_observer * observer () const
void cast ()
sc_fxnum_fast (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &, sc_fxnum_fast_observer *)
~sc_fxnum_fast ()
double get_val () const
bool set_bit (int, bool)
bool get_slice (int, int, sc_bv_base &) const
bool set_slice (int, int, const sc_bv_base &)
sc_fxnum_fast_observer * lock_observer () const
void unlock_observer (sc_fxnum_fast_observer *) const
Detailed Description
Definition at line 238 of file sc_fix.hh.
Constructor & Destructor Documentation
sc_fix_fast() [1/15]
sc_dt::sc_fix_fast::sc_fix_fast (sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 879 of file sc_fix.hh.
Referenced by operator~().
sc_fix_fast() [2/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 884 of file sc_fix.hh.
sc_fix_fast() [3/15]
sc_dt::sc_fix_fast::sc_fix_fast (sc_q_mode qm, sc_o_mode om, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 890 of file sc_fix.hh.
sc_fix_fast() [4/15]
sc_dt::sc_fix_fast::sc_fix_fast (sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 896 of file sc_fix.hh.
sc_fix_fast() [5/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 902 of file sc_fix.hh.
sc_fix_fast() [6/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 908 of file sc_fix.hh.
sc_fix_fast() [7/15]
sc_dt::sc_fix_fast::sc_fix_fast (const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 914 of file sc_fix.hh.
sc_fix_fast() [8/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 919 of file sc_fix.hh.
sc_fix_fast() [9/15]
sc_dt::sc_fix_fast::sc_fix_fast (sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 925 of file sc_fix.hh.
sc_fix_fast() [10/15]
sc_dt::sc_fix_fast::sc_fix_fast (sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 931 of file sc_fix.hh.
sc_fix_fast() [11/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 937 of file sc_fix.hh.
sc_fix_fast() [12/15]
sc_dt::sc_fix_fast::sc_fix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 944 of file sc_fix.hh.
sc_fix_fast() [13/15]
sc_dt::sc_fix_fast::sc_fix_fast (const sc_fxtype_params & type_params_, sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 951 of file sc_fix.hh.
sc_fix_fast() [14/15]
sc_dt::sc_fix_fast::sc_fix_fast (const sc_fxtype_params & type_params_, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 956 of file sc_fix.hh.
sc_fix_fast() [15/15]
sc_dt::sc_fix_fast::sc_fix_fast (const sc_fix_fast & a) inline
Definition at line 1167 of file sc_fix.hh.
Member Function Documentation
operator++() [1/2]
const sc_fxval_fast sc_dt::sc_fix_fast::operator++ (int) inline
Definition at line 1316 of file sc_fix.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator++() [2/2]
sc_fix_fast & sc_dt::sc_fix_fast::operator++ () inline
Definition at line 1328 of file sc_fix.hh.
References sc_dt::sc_fxnum_fast::operator++().
Referenced by sc_dt::sc_fixed_fast< W, I, Q, O, N >::operator++().
operator--() [1/2]
const sc_fxval_fast sc_dt::sc_fix_fast::operator-- (int) inline
Definition at line 1322 of file sc_fix.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator--() [2/2]
sc_fix_fast & sc_dt::sc_fix_fast::operator-- () inline
Definition at line 1335 of file sc_fix.hh.
References sc_dt::sc_fxnum_fast::operator--().
Referenced by sc_dt::sc_fixed_fast< W, I, Q, O, N >::operator--().
operator=()
sc_fix_fast & sc_dt::sc_fix_fast::operator= (const sc_fix_fast & a) inline
Definition at line 1241 of file sc_fix.hh.
Referenced by sc_dt::sc_fixed_fast< W, I, Q, O, N >::operator=().
operator~()
const sc_fix_fast sc_dt::sc_fix_fast::operator~ () const inline
Definition at line 1173 of file sc_fix.hh.
References ArmISA::c, sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::iwl(), sc_fix_fast(), SC_FXNUM_FAST_OBSERVER_READ_, sc_dt::sc_fxnum_fast::set_bit(), and sc_dt::sc_fxnum_fast::wl().
Friends And Related Function Documentation
b_and
void b_and (sc_fix_fast & , const sc_fix_fast & , const sc_fix_fast &) friend
b_not
void b_not (sc_fix_fast & c, const sc_fix_fast & a) friend
Definition at line 1186 of file sc_fix.hh.
b_or
void b_or (sc_fix_fast & , const sc_fix_fast & , const sc_fix_fast &) friend
b_xor
void b_xor (sc_fix_fast & , const sc_fix_fast & , const sc_fix_fast &) friend
operator&
const sc_fix_fast operator & (const sc_fix_fast & , const sc_fix_fast &) friend
operator^
const sc_fix_fast operator^ (const sc_fix_fast & , const sc_fix_fast &) friend
operator|
const sc_fix_fast operator| (const sc_fix_fast & , const sc_fix_fast &) friend
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_fix.hh