gem5: ArmISA::PCAlignmentFault Class Reference
ArmISA::PCAlignmentFault Class Reference
PC alignment fault (AArch64 only)
#include <faults.hh>
Public Member Functions
PCAlignmentFault (Addr _faultPC)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr) override
bool routeToHyp (ThreadContext *tc) const override
Public Member Functions inherited from ArmISA::ArmFaultVals< PCAlignmentFault >
ArmFaultVals (ExtMachInst _machInst=0, uint32_t _iss=0)
FaultName name () const override
FaultStat & countStat () override
FaultOffset offset (ThreadContext *tc) override
FaultOffset offset64 (ThreadContext *tc) override
OperatingMode nextMode () override
virtual bool routeToMonitor (ThreadContext *tc) const override
uint8_t armPcOffset (bool isHyp) override
uint8_t thumbPcOffset (bool isHyp) override
uint8_t armPcElrOffset () override
uint8_t thumbPcElrOffset () override
bool abortDisable (ThreadContext *tc) override
bool fiqDisable (ThreadContext *tc) override
ExceptionClass ec (ThreadContext *tc) const override
uint32_t iss () const override
Public Member Functions inherited from ArmISA::ArmFault
ArmFault (ExtMachInst _machInst=0, uint32_t _iss=0)
MiscRegIndex getSyndromeReg64 () const
MiscRegIndex getFaultAddrReg64 () const
void invoke64 (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
void update (ThreadContext *tc)
ArmStaticInst * instrAnnotate (const StaticInstPtr &inst)
virtual void annotate (AnnotationIDs id, uint64_t val)
virtual bool isStage2 () const
virtual FSR getFsr (ThreadContext *tc) const
virtual void setSyndrome (ThreadContext *tc, MiscRegIndex syndrome_reg)
virtual bool getFaultVAddr (Addr &va) const
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Protected Attributes
Addr faultPC
The unaligned value of the PC.
Protected Attributes inherited from ArmISA::ArmFault
ExtMachInst machInst
uint32_t issRaw
bool from64
bool to64
ExceptionLevel fromEL
ExceptionLevel toEL
OperatingMode fromMode
OperatingMode toMode
bool faultUpdated
bool hypRouted
bool span
Additional Inherited Members
Public Types inherited from ArmISA::ArmFault
enum FaultSource {
AlignmentFault = 0, InstructionCacheMaintenance, SynchExtAbtOnTranslTableWalkLL, SynchPtyErrOnTranslTableWalkLL = SynchExtAbtOnTranslTableWalkLL + 4,
TranslationLL = SynchPtyErrOnTranslTableWalkLL + 4, AccessFlagLL = TranslationLL + 4, DomainLL = AccessFlagLL + 4, PermissionLL = DomainLL + 4,
DebugEvent = PermissionLL + 4, SynchronousExternalAbort, TLBConflictAbort, SynchPtyErrOnMemoryAccess,
AsynchronousExternalAbort, AsynchPtyErrOnMemoryAccess, AddressSizeLL, PrefetchTLBMiss = AddressSizeLL + 4,
PrefetchUncacheable, NumFaultSources, FaultSourceInvalid = 0xff
}
Generic fault source enums used to index into {short/long/aarch64}DescFaultSources[] to get the actual encodings based on the current register width state and the translation table format in use.
enum AnnotationIDs {
S1PTW, OVA, SAS, SSE,
SRT, CM, OFA, SF,
AR
}
enum TranMethod { LpaeTran, VmsaTran, UnknownTran }
Static Public Attributes inherited from ArmISA::ArmFault
static uint8_t shortDescFaultSources [NumFaultSources]
Encodings of the fault sources when the short-desc.
static uint8_t longDescFaultSources [NumFaultSources]
Encodings of the fault sources when the long-desc.
static uint8_t aarch64FaultSources [NumFaultSources]
Encodings of the fault sources in AArch64 state.
Protected Member Functions inherited from ArmISA::ArmFaultVals< PCAlignmentFault >
ArmFault::FaultVals vals ("Reset", 0x000, 0x000, 0x000, 0x000, 0x000, MODE_SVC, 0, 0, 0, 0, false, true, true, EC_UNKNOWN)
ArmFault::FaultVals vals ("Undefined Instruction", 0x004, 0x000, 0x200, 0x400, 0x600, MODE_UNDEFINED, 4, 2, 0, 0, true, false, false, EC_UNKNOWN)
ArmFault::FaultVals vals ("Supervisor Call", 0x008, 0x000, 0x200, 0x400, 0x600, MODE_SVC, 4, 2, 4, 2, true, false, false, EC_SVC_TO_HYP)
ArmFault::FaultVals vals ("Secure Monitor Call", 0x008, 0x000, 0x200, 0x400, 0x600, MODE_MON, 4, 4, 4, 4, false, true, true, EC_SMC_TO_HYP)
ArmFault::FaultVals vals ("Hypervisor Call", 0x008, 0x000, 0x200, 0x400, 0x600, MODE_HYP, 4, 4, 4, 4, true, false, false, EC_HVC)
ArmFault::FaultVals vals ("Prefetch Abort", 0x00C, 0x000, 0x200, 0x400, 0x600, MODE_ABORT, 4, 4, 0, 0, true, true, false, EC_PREFETCH_ABORT_TO_HYP)
ArmFault::FaultVals vals ("Data Abort", 0x010, 0x000, 0x200, 0x400, 0x600, MODE_ABORT, 8, 8, 0, 0, true, true, false, EC_DATA_ABORT_TO_HYP)
ArmFault::FaultVals vals ("Virtual Data Abort", 0x010, 0x000, 0x200, 0x400, 0x600, MODE_ABORT, 8, 8, 0, 0, true, true, false, EC_INVALID)
ArmFault::FaultVals vals ("Hypervisor Trap", 0x014, 0x000, 0x200, 0x400, 0x600, MODE_HYP, 0, 0, 0, 0, false, false, false, EC_UNKNOWN)
ArmFault::FaultVals vals ("Secure Monitor Trap", 0x004, 0x000, 0x200, 0x400, 0x600, MODE_MON, 4, 2, 0, 0, false, false, false, EC_UNKNOWN)
ArmFault::FaultVals vals ("IRQ", 0x018, 0x080, 0x280, 0x480, 0x680, MODE_IRQ, 4, 4, 0, 0, false, true, false, EC_UNKNOWN)
ArmFault::FaultVals vals ("Virtual IRQ", 0x018, 0x080, 0x280, 0x480, 0x680, MODE_IRQ, 4, 4, 0, 0, false, true, false, EC_INVALID)
ArmFault::FaultVals vals ("FIQ", 0x01C, 0x100, 0x300, 0x500, 0x700, MODE_FIQ, 4, 4, 0, 0, false, true, true, EC_UNKNOWN)
ArmFault::FaultVals vals ("Virtual FIQ", 0x01C, 0x100, 0x300, 0x500, 0x700, MODE_FIQ, 4, 4, 0, 0, false, true, true, EC_INVALID)
ArmFault::FaultVals vals ("Illegal Inst Set State Fault", 0x004, 0x000, 0x200, 0x400, 0x600, MODE_UNDEFINED, 4, 2, 0, 0, true, false, false, EC_ILLEGAL_INST)
ArmFault::FaultVals vals ("Supervisor Trap", 0x014, 0x000, 0x200, 0x400, 0x600, MODE_SVC, 0, 0, 0, 0, false, false, false, EC_UNKNOWN)
ArmFault::FaultVals vals ("PC Alignment Fault", 0x000, 0x000, 0x200, 0x400, 0x600, MODE_SVC, 0, 0, 0, 0, true, false, false, EC_PC_ALIGNMENT)
ArmFault::FaultVals vals ("SP Alignment Fault", 0x000, 0x000, 0x200, 0x400, 0x600, MODE_SVC, 0, 0, 0, 0, true, false, false, EC_STACK_PTR_ALIGNMENT)
ArmFault::FaultVals vals ("SError", 0x000, 0x180, 0x380, 0x580, 0x780, MODE_SVC, 0, 0, 0, 0, false, true, true, EC_SERROR)
ArmFault::FaultVals vals ("Software Breakpoint", 0x000, 0x000, 0x200, 0x400, 0x600, MODE_SVC, 0, 0, 0, 0, true, false, false, EC_SOFTWARE_BREAKPOINT)
ArmFault::FaultVals vals ("ArmSev Flush", 0x000, 0x000, 0x000, 0x000, 0x000, MODE_SVC, 0, 0, 0, 0, false, true, true, EC_UNKNOWN)
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
ArmFault::FaultVals vals
Protected Member Functions inherited from ArmISA::ArmFault
virtual Addr getVector (ThreadContext *tc)
Addr getVector64 (ThreadContext *tc)
Static Protected Attributes inherited from ArmISA::ArmFaultVals< PCAlignmentFault >
static FaultVals vals
Detailed Description
PC alignment fault (AArch64 only)
Definition at line 556 of file faults.hh.
Constructor & Destructor Documentation
PCAlignmentFault()
ArmISA::PCAlignmentFault::PCAlignmentFault (Addr _faultPC) inline
Definition at line 562 of file faults.hh.
References ArmISA::ArmFault::invoke(), StaticInst::nullStaticInstPtr, and ArmISA::ArmFault::routeToHyp().
Member Function Documentation
invoke()
void ArmISA::PCAlignmentFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) override virtual
Reimplemented from ArmISA::ArmFault.
Definition at line 1526 of file faults.cc.
References ArmISA::ArmFault::from64, ArmISA::ArmFault::getFaultAddrReg64(), ArmISA::ArmFault::invoke(), and ThreadContext::setMiscReg().
routeToHyp()
bool ArmISA::PCAlignmentFault::routeToHyp (ThreadContext * tc) const override virtual
Reimplemented from ArmISA::ArmFault.
Definition at line 1535 of file faults.cc.
References ArmISA::currEL(), ArmISA::EL0, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_HCR_EL2, ArmISA::MISCREG_SCR_EL3, and ThreadContext::readMiscRegNoEffect().
Member Data Documentation
faultPC
Addr ArmISA::PCAlignmentFault::faultPC protected
The unaligned value of the PC.
Definition at line 560 of file faults.hh.
The documentation for this class was generated from the following files:
arch/arm/faults.hh
arch/arm/faults.cc