gem5: PCEventQueue::MapCompare Class Reference
PCEventQueue::MapCompare Class Reference
#include <pc_event.hh>
Public Member Functions
bool operator() (PCEvent *const &l, PCEvent *const &r) const
bool operator() (PCEvent *const &l, Addr pc) const
bool operator() (Addr pc, PCEvent *const &r) const
Detailed Description
Definition at line 77 of file pc_event.hh.
Member Function Documentation
operator()() [1/3]
bool PCEventQueue::MapCompare::operator() (PCEvent *const & l, PCEvent *const & r) const inline
Definition at line 80 of file pc_event.hh.
References PCEvent::pc().
operator()() [2/3]
bool PCEventQueue::MapCompare::operator() (PCEvent *const & l, Addr pc) const inline
Definition at line 85 of file pc_event.hh.
References PCEvent::pc().
operator()() [3/3]
bool PCEventQueue::MapCompare::operator() (Addr pc, PCEvent *const & r) const inline
Definition at line 90 of file pc_event.hh.
References PCEvent::pc().
The documentation for this class was generated from the following file:
cpu/pc_event.hh