gem5: ListenSocket Class Reference
ListenSocket Class Reference
#include <socket.hh>
Public Member Functions
ListenSocket ()
virtual ~ListenSocket ()
virtual int accept (bool nodelay=false)
virtual bool listen (int port, bool reuse=true)
int getfd () const
bool islistening () const
Static Public Member Functions
static void disableAll ()
static bool allDisabled ()
static void loopbackOnly ()
Protected Attributes
bool listening
int fd
Static Protected Attributes
static bool listeningDisabled = false
static bool anyListening = false
static bool bindToLoopback = false
Detailed Description
Definition at line 34 of file socket.hh.
Constructor & Destructor Documentation
ListenSocket()
ListenSocket::ListenSocket ()
Definition at line 78 of file socket.cc.
~ListenSocket()
ListenSocket::~ListenSocket () virtual
Definition at line 82 of file socket.cc.
References fd.
Member Function Documentation
accept()
int ListenSocket::accept (bool nodelay = false) virtual
Definition at line 136 of file socket.cc.
References fd, ArmISA::i, and warn.
Referenced by Terminal::accept(), VncServer::accept(), BaseRemoteGDB::connect(), and Trace::NativeTrace::NativeTrace().
allDisabled()
bool ListenSocket::allDisabled () static
Definition at line 61 of file socket.cc.
Referenced by EtherTapStub::EtherTapStub(), Terminal::listen(), BaseRemoteGDB::listen(), VncServer::listen(), Trace::NativeTrace::NativeTrace(), and pybind_init_core().
disableAll()
void ListenSocket::disableAll () static
Definition at line 53 of file socket.cc.
References panic.
Referenced by pybind_init_core().
getfd()
int ListenSocket::getfd () const inline
Definition at line 59 of file socket.hh.
References fd.
Referenced by Terminal::listen(), BaseRemoteGDB::listen(), and VncServer::listen().
islistening()
bool ListenSocket::islistening () const inline
Definition at line 60 of file socket.hh.
References listening.
Referenced by Terminal::accept(), VncServer::accept(), BaseRemoteGDB::connect(), and BaseRemoteGDB::port().
listen()
bool ListenSocket::listen (int port, bool reuse = true) virtual
Definition at line 90 of file socket.cc.
References anyListening, bindToLoopback, fd, ArmISA::i, listening, and panic.
Referenced by Terminal::listen(), BaseRemoteGDB::listen(), VncServer::listen(), and Trace::NativeTrace::NativeTrace().
loopbackOnly()
void ListenSocket::loopbackOnly () static
Definition at line 67 of file socket.cc.
References panic.
Referenced by pybind_init_core().
Member Data Documentation
anyListening
bool ListenSocket::anyListening = false static protected
Definition at line 38 of file socket.hh.
Referenced by listen().
bindToLoopback
bool ListenSocket::bindToLoopback = false static protected
Definition at line 40 of file socket.hh.
Referenced by listen().
fd
int ListenSocket::fd protected
Definition at line 50 of file socket.hh.
Referenced by accept(), getfd(), listen(), and ~ListenSocket().
listening
bool ListenSocket::listening protected
Definition at line 49 of file socket.hh.
Referenced by islistening(), and listen().
listeningDisabled
bool ListenSocket::listeningDisabled = false static protected
Definition at line 37 of file socket.hh.
The documentation for this class was generated from the following files:
base/socket.hh
base/socket.cc