gem5: sc_gem5::Module Class Reference
sc_gem5::Module Class Reference
#include <module.hh>
Public Member Functions
Module (const char *name)
~Module ()
void finish (Object *this_obj)
const char * name () const
void endModule ()
void deprecatedConstructor ()
sc_core::sc_module * sc_mod () const
void sc_mod (sc_core::sc_module *sc_mod)
Object * obj ()
void pop ()
const char * uniqueName (const char *seed)
void bindPorts (std::vector< const ::sc_core::sc_bind_proxy *> &proxies)
void beforeEndOfElaboration ()
void endOfElaboration ()
void startOfSimulation ()
void endOfSimulation ()
Static Public Member Functions
static Module * fromScModule (::sc_core::sc_module *mod)
Public Attributes
std::vector<::sc_core::sc_port_base * > ports
std::vector<::sc_core::sc_export_base * > exports
int bindingIndex
Private Attributes
const char * _name
sc_core::sc_module * _sc_mod
Object * _obj
bool _ended
bool _deprecatedConstructor
UniqueNameGen nameGen
Detailed Description
Definition at line 73 of file module.hh.
Constructor & Destructor Documentation
Module()
sc_gem5::Module::Module (const char * name)
Definition at line 53 of file module.cc.
References panic_if.
~Module()
sc_gem5::Module::~Module ()
Definition at line 61 of file module.cc.
References sc_gem5::allModules, and pop().
Member Function Documentation
beforeEndOfElaboration()
void sc_gem5::Module::beforeEndOfElaboration ()
Definition at line 128 of file module.cc.
References _sc_mod, sc_core::sc_module::before_end_of_elaboration(), ArmISA::e, exports, sc_gem5::popParentModule(), and sc_gem5::pushParentModule().
bindPorts()
void sc_gem5::Module::bindPorts (std::vector< const ::sc_core::sc_bind_proxy *> & proxies)
Definition at line 107 of file module.cc.
References bindingIndex, panic_if, and ports.
deprecatedConstructor()
void sc_gem5::Module::deprecatedConstructor () inline
Definition at line 98 of file module.hh.
Referenced by sc_core::sc_module::sc_module().
endModule()
void sc_gem5::Module::endModule () inline
Definition at line 97 of file module.hh.
Referenced by sc_core::sc_module::end_module().
endOfElaboration()
void sc_gem5::Module::endOfElaboration ()
Definition at line 143 of file module.cc.
References _deprecatedConstructor, _ended, _sc_mod, csprintf(), ArmISA::e, sc_core::sc_module::end_of_elaboration(), exports, name(), sc_gem5::popParentModule(), sc_gem5::pushParentModule(), sc_core::SC_ID_END_MODULE_NOT_CALLED_, and SC_REPORT_WARNING.
endOfSimulation()
void sc_gem5::Module::endOfSimulation ()
Definition at line 177 of file module.cc.
References _sc_mod, ArmISA::e, sc_core::sc_module::end_of_simulation(), exports, sc_gem5::popParentModule(), and sc_gem5::pushParentModule().
finish()
void sc_gem5::Module::finish (Object * this_obj)
Definition at line 76 of file module.cc.
References _obj, sc_gem5::allModules, sc_gem5::popParentModule(), sc_gem5::pushParentModule(), sc_mod(), and sc_gem5::Object::sc_obj().
Referenced by sc_gem5::Object::Object().
fromScModule()
static Module* sc_gem5::Module::fromScModule (::sc_core::sc_module * mod) inline static
Definition at line 89 of file module.hh.
References sc_core::sc_module::_gem5_module.
name()
const char* sc_gem5::Module::name () const inline
Definition at line 96 of file module.hh.
Referenced by endOfElaboration().
obj()
Object* sc_gem5::Module::obj () inline
Definition at line 115 of file module.hh.
Referenced by sc_gem5::pushParentModule().
pop()
void sc_gem5::Module::pop ()
Definition at line 95 of file module.cc.
References panic_if, and sc_gem5::popParentModule().
Referenced by ~Module(), and sc_core::sc_module_name::~sc_module_name().
sc_mod() [1/2]
sc_core::sc_module* sc_gem5::Module::sc_mod () const inline
Definition at line 101 of file module.hh.
Referenced by finish().
sc_mod() [2/2]
void sc_gem5::Module::sc_mod (sc_core::sc_module * sc_mod) inline
Definition at line 108 of file module.hh.
startOfSimulation()
void sc_gem5::Module::startOfSimulation ()
Definition at line 162 of file module.cc.
References _sc_mod, ArmISA::e, exports, sc_gem5::popParentModule(), sc_gem5::pushParentModule(), and sc_core::sc_module::start_of_simulation().
uniqueName()
const char* sc_gem5::Module::uniqueName (const char * seed) inline
Definition at line 123 of file module.hh.
References sc_gem5::UniqueNameGen::gen().
Member Data Documentation
_deprecatedConstructor
bool sc_gem5::Module::_deprecatedConstructor private
Definition at line 80 of file module.hh.
Referenced by endOfElaboration().
_ended
bool sc_gem5::Module::_ended private
Definition at line 79 of file module.hh.
Referenced by endOfElaboration().
_name
const char* sc_gem5::Module::_name private
Definition at line 76 of file module.hh.
_obj
Object* sc_gem5::Module::_obj private
Definition at line 78 of file module.hh.
Referenced by finish().
_sc_mod
sc_core::sc_module* sc_gem5::Module::_sc_mod private
Definition at line 77 of file module.hh.
Referenced by beforeEndOfElaboration(), endOfElaboration(), endOfSimulation(), and startOfSimulation().
bindingIndex
int sc_gem5::Module::bindingIndex
Definition at line 130 of file module.hh.
Referenced by bindPorts().
exports
std::vector<::sc_core::sc_export_base *> sc_gem5::Module::exports
Definition at line 128 of file module.hh.
Referenced by beforeEndOfElaboration(), endOfElaboration(), endOfSimulation(), and startOfSimulation().
nameGen
UniqueNameGen sc_gem5::Module::nameGen private
Definition at line 82 of file module.hh.
ports
std::vector<::sc_core::sc_port_base *> sc_gem5::Module::ports
Definition at line 127 of file module.hh.
Referenced by bindPorts().
The documentation for this class was generated from the following files:
systemc/core/module.hh
systemc/core/module.cc