gem5: Trace::Logger Class Reference
Trace::Logger Class Reference abstract
Debug logging base class.
#include <trace.hh>
Public Member Functions
template<typename ... Args>
void dprintf (Tick when, const std::string &name, const char *fmt, const Args &...args)
Log a single message.
virtual void dump (Tick when, const std::string &name, const void *d, int len)
Dump a block of data of length len.
virtual void logMessage (Tick when, const std::string &name, const std::string &message)=0
Log formatted message.
virtual std::ostream & getOstream ()=0
Return an ostream that can be used to send messages to the 'same place' as formatted logMessage messages.
void setIgnore (ObjectMatch &ignore_)
Set objects to ignore.
void addIgnore (const ObjectMatch &ignore_)
Add objects to ignore.
virtual ~Logger ()
Protected Attributes
ObjectMatch ignore
Name match for objects to ignore.
Detailed Description
Debug logging base class.
Handles formatting and outputting time/name/message messages
Definition at line 51 of file trace.hh.
Constructor & Destructor Documentation
~Logger()
virtual Trace::Logger::~Logger () inline virtual
Definition at line 92 of file trace.hh.
Member Function Documentation
addIgnore()
void Trace::Logger::addIgnore (const ObjectMatch & ignore_) inline
Add objects to ignore.
Definition at line 90 of file trace.hh.
References ObjectMatch::add().
Referenced by ignore().
dprintf()
template<typename ... Args> void Trace::Logger::dprintf (Tick when, const std::string & name, const char * fmt, const Args &... args) inline
Log a single message.
Definition at line 60 of file trace.hh.
References ccprintf(), ArmISA::d, dump(), getOstream(), ArmISA::len, logMessage(), ObjectMatch::match(), and name().
dump()
void Logger::dump (Tick when, const std::string & name, const void * d, int len) virtual
Dump a block of data of length len.
Definition at line 105 of file trace.cc.
References ArmISA::c, ccprintf(), ArmISA::d, data, ArmISA::i, ArmISA::j, ArmISA::len, logMessage(), and ObjectMatch::match().
Referenced by dprintf().
getOstream()
virtual std::ostream& Trace::Logger::getOstream () pure virtual
Return an ostream that can be used to send messages to the 'same place' as formatted logMessage messages.
This can be implemented to use a logger's underlying ostream, to provide an ostream which formats the output in some way, or just set to one of std::cout, std::cerr
Implemented in Trace::OstreamLogger.
Referenced by dprintf(), and Trace::output().
logMessage()
virtual void Trace::Logger::logMessage (Tick when, const std::string & name, const std::string & message) pure virtual
Log formatted message.
Implemented in Trace::OstreamLogger.
Referenced by dprintf(), dump(), and Trace::OstreamLogger::OstreamLogger().
setIgnore()
void Trace::Logger::setIgnore (ObjectMatch & ignore_) inline
Set objects to ignore.
Definition at line 87 of file trace.hh.
Member Data Documentation
ignore
ObjectMatch Trace::Logger::ignore protected
Name match for objects to ignore.
Definition at line 55 of file trace.hh.
The documentation for this class was generated from the following files:
base/trace.hh
base/trace.cc