gem5: sc_core::sc_unsigned_sigref Class Reference
sc_core::sc_unsigned_sigref Class Reference
#include <scx_signal_unsigned.h>
Public Member Functions
sc_unsigned_sigref ()
virtual ~sc_unsigned_sigref ()
virtual void concat_set (sc_dt::int64 src, int low_i)
virtual void concat_set (const sc_dt::sc_signed &src, int low_i)
virtual void concat_set (const sc_dt::sc_unsigned &src, int low_i)
virtual void concat_set (const sc_dt::sc_lv_base &src, int low_i)
virtual void concat_set (sc_dt::uint64 src, int low_i)
void initialize (sc_unsigned_part_if *if_p, int left_, int right_)
void operator= (sc_dt::uint64 v)
void operator= (const char *v)
void operator= (unsigned long v)
void operator= (long v)
void operator= (unsigned int v)
void operator= (int v)
void operator= (sc_dt::int64 v)
void operator= (double v)
void operator= (const sc_unsigned_sigref &v)
template<typename T >
void operator= (const sc_dt::sc_generic_base< T > &v)
void operator= (const sc_dt::sc_signed &v)
void operator= (const sc_dt::sc_unsigned &v)
void operator= (const sc_dt::sc_bv_base &v)
void operator= (const sc_dt::sc_lv_base &v)
Public Member Functions inherited from sc_dt::sc_unsigned_subref_r
virtual ~sc_unsigned_subref_r ()
sc_unsigned_subref_r (const sc_unsigned_subref_r &a)
int length () const
operator sc_unsigned () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
virtual int concat_length (bool *xz_present_p) const
virtual uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Attributes
static sc_vpool< sc_unsigned_sigref > m_pool
Protected Attributes
sc_unsigned_part_if * m_if_p
Protected Attributes inherited from sc_dt::sc_unsigned_subref_r
int m_left
sc_unsigned * m_obj_p
int m_right
Private Member Functions
sc_unsigned_sigref (const sc_unsigned_sigref &a)
Additional Inherited Members
Protected Member Functions inherited from sc_dt::sc_unsigned_subref_r
sc_unsigned_subref_r ()
void initialize (const sc_unsigned *obj_p, int left_, int right_)
Detailed Description
Definition at line 269 of file scx_signal_unsigned.h.
Constructor & Destructor Documentation
sc_unsigned_sigref() [1/2]
sc_core::sc_unsigned_sigref::sc_unsigned_sigref () inline
Definition at line 272 of file scx_signal_unsigned.h.
~sc_unsigned_sigref()
virtual sc_core::sc_unsigned_sigref::~sc_unsigned_sigref () inline virtual
Definition at line 273 of file scx_signal_unsigned.h.
References sc_core::sc_unsigned_part_if::operator=(), and ArmISA::v.
sc_unsigned_sigref() [2/2]
sc_core::sc_unsigned_sigref::sc_unsigned_sigref (const sc_unsigned_sigref & a) private
Member Function Documentation
concat_set() [1/5]
void sc_core::sc_unsigned_sigref::concat_set (sc_dt::int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1789 of file scx_signal_unsigned.h.
concat_set() [2/5]
void sc_core::sc_unsigned_sigref::concat_set (const sc_dt::sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1800 of file scx_signal_unsigned.h.
concat_set() [3/5]
void sc_core::sc_unsigned_sigref::concat_set (const sc_dt::sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1814 of file scx_signal_unsigned.h.
concat_set() [4/5]
void sc_core::sc_unsigned_sigref::concat_set (const sc_dt::sc_lv_base & src, int low_i) virtual
Definition at line 1806 of file scx_signal_unsigned.h.
References sc_dt::sc_lv_base::length().
concat_set() [5/5]
void sc_core::sc_unsigned_sigref::concat_set (sc_dt::uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1820 of file scx_signal_unsigned.h.
initialize()
void sc_core::sc_unsigned_sigref::initialize (sc_unsigned_part_if * if_p, int left_, int right_) inline
Definition at line 1639 of file scx_signal_unsigned.h.
References sc_core::sc_unsigned_part_if::part_read_target().
Referenced by sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator()(), and sc_core::sc_signal< sc_dt::sc_biguint< W > >::select_part().
operator=() [1/14]
void sc_core::sc_unsigned_sigref::operator= (sc_dt::uint64 v) inline
Definition at line 1655 of file scx_signal_unsigned.h.
operator=() [2/14]
void sc_core::sc_unsigned_sigref::operator= (const char * v) inline
Definition at line 1660 of file scx_signal_unsigned.h.
References length, and ArmISA::v.
operator=() [3/14]
void sc_core::sc_unsigned_sigref::operator= (unsigned long v) inline
Definition at line 1687 of file scx_signal_unsigned.h.
operator=() [4/14]
void sc_core::sc_unsigned_sigref::operator= (long v) inline
Definition at line 1677 of file scx_signal_unsigned.h.
operator=() [5/14]
void sc_core::sc_unsigned_sigref::operator= (unsigned int v) inline
Definition at line 1682 of file scx_signal_unsigned.h.
operator=() [6/14]
void sc_core::sc_unsigned_sigref::operator= (int v) inline
Definition at line 1672 of file scx_signal_unsigned.h.
operator=() [7/14]
void sc_core::sc_unsigned_sigref::operator= (sc_dt::int64 v) inline
Definition at line 1667 of file scx_signal_unsigned.h.
operator=() [8/14]
void sc_core::sc_unsigned_sigref::operator= (double v) inline
operator=() [9/14]
void sc_core::sc_unsigned_sigref::operator= (const sc_unsigned_sigref & v) inline
Definition at line 1692 of file scx_signal_unsigned.h.
operator=() [10/14]
template<typename T > void sc_core::sc_unsigned_sigref::operator= (const sc_dt::sc_generic_base< T > & v) inline
Definition at line 1709 of file scx_signal_unsigned.h.
References sc_gem5::ScSignalBase::kind(), m_pool, sc_core::sc_object::name(), and sc_core::sc_signal_invalid_writer().
operator=() [11/14]
void sc_core::sc_unsigned_sigref::operator= (const sc_dt::sc_signed & v) inline
Definition at line 1698 of file scx_signal_unsigned.h.
operator=() [12/14]
void sc_core::sc_unsigned_sigref::operator= (const sc_dt::sc_unsigned & v) inline
Definition at line 1703 of file scx_signal_unsigned.h.
operator=() [13/14]
void sc_core::sc_unsigned_sigref::operator= (const sc_dt::sc_bv_base & v) inline
operator=() [14/14]
void sc_core::sc_unsigned_sigref::operator= (const sc_dt::sc_lv_base & v) inline
Member Data Documentation
m_if_p
sc_unsigned_part_if* sc_core::sc_unsigned_sigref::m_if_p protected
Definition at line 304 of file scx_signal_unsigned.h.
m_pool
sc_vpool< sc_unsigned_sigref > sc_core::sc_unsigned_sigref::m_pool static
Definition at line 301 of file scx_signal_unsigned.h.
Referenced by sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator()(), operator=(), and sc_core::sc_signal< sc_dt::sc_biguint< W > >::select_part().
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_unsigned.h