gem5: sc_dt::sc_concat_bool Class Reference
sc_dt::sc_concat_bool Class Reference
#include <sc_concatref.hh>
Public Member Functions
sc_concat_bool ()
virtual ~sc_concat_bool ()
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Member Functions
static sc_concat_bool * allocate (bool v)
Protected Attributes
bool m_value
Static Protected Attributes
static sc_core::sc_vpool< sc_concat_bool > m_pool
Detailed Description
Definition at line 562 of file sc_concatref.hh.
Constructor & Destructor Documentation
sc_concat_bool()
sc_dt::sc_concat_bool::sc_concat_bool () inline
Definition at line 570 of file sc_concatref.hh.
~sc_concat_bool()
virtual sc_dt::sc_concat_bool::~sc_concat_bool () inline virtual
Definition at line 573 of file sc_concatref.hh.
Member Function Documentation
allocate()
static sc_concat_bool* sc_dt::sc_concat_bool::allocate (bool v) inline static
Definition at line 577 of file sc_concatref.hh.
References sc_core::sc_vpool< T >::allocate(), m_value, and ArmISA::v.
Referenced by sc_dt::concat(), and sc_dt::operator,().
concat_get_ctrl()
virtual bool sc_dt::sc_concat_bool::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 594 of file sc_concatref.hh.
References BITS_PER_DIGIT.
concat_get_data()
virtual bool sc_dt::sc_concat_bool::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 603 of file sc_concatref.hh.
References BITS_PER_DIGIT.
concat_get_uint64()
virtual uint64 sc_dt::sc_concat_bool::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 615 of file sc_concatref.hh.
concat_length()
virtual int sc_dt::sc_concat_bool::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 586 of file sc_concatref.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_concat_bool > sc_dt::sc_concat_bool::m_pool static protected
Definition at line 565 of file sc_concatref.hh.
m_value
bool sc_dt::sc_concat_bool::m_value protected
Definition at line 566 of file sc_concatref.hh.
Referenced by allocate().
The documentation for this class was generated from the following files:
systemc/ext/dt/misc/sc_concatref.hh
systemc/dt/misc/sc_concatref.cc