gem5: SlavePort Class Reference
SlavePort Class Reference abstract
A SlavePort is a specialisation of a port.
#include <port.hh>
Public Member Functions
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
virtual AddrRangeList getAddrRanges () const =0
Get a list of the non-overlapping address ranges the owner is responsible for.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
virtual Tick recvAtomic (PacketPtr pkt)=0
Receive an atomic request packet from the peer.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
virtual bool recvTimingReq (PacketPtr pkt)=0
Receive a timing request from the peer.
virtual void recvRespRetry ()=0
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
virtual void recvFunctional (PacketPtr pkt)=0
Receive a functional request packet from the peer.
Protected Attributes
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Private Attributes
MasterPort * _masterPort
bool defaultBackdoorWarned
Friends
class MasterPort
Detailed Description
A SlavePort is a specialisation of a port.
In addition to the basic functionality of sending packets to its master peer, it also has functions specific to a slave, e.g. to send range changes and get the address ranges that the port responds to.
The three protocols are atomic, timing, and functional, each with its own header file.
Definition at line 258 of file port.hh.
Constructor & Destructor Documentation
SlavePort()
SlavePort::SlavePort (const std::string & name, SimObject * _owner, PortID id = InvalidPortID)
Slave port.
Definition at line 114 of file port.cc.
~SlavePort()
SlavePort::~SlavePort () virtual
Definition at line 120 of file port.cc.
Member Function Documentation
bind()
void SlavePort::bind (Port & peer) inline override virtual
Attach to a peer port.
Reimplemented from Port.
Definition at line 306 of file port.hh.
getAddrRanges()
virtual AddrRangeList SlavePort::getAddrRanges () const pure virtual
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns
a list of ranges responded to
Implemented in BaseCache::CpuSidePort, X86ISA::GpuTLB::CpuSidePort, CommMonitor::MonitorSlavePort, Bridge::BridgeSlavePort, SerialLink::SerialLinkSlavePort, AddrMapper::MapperSlavePort, LdsState::CuSidePort, MemCheckerMonitor::MonitorSlavePort, TLBCoalescer::CpuSidePort, CoherentXBar::CoherentXBarSlavePort, SMMUATSSlavePort, RubyPort::PioSlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, DRAMCtrl::MemoryPort, MemDelay::SlavePort, QoS::MemSinkCtrl::MemoryPort, SMMUControlPort, SimpleMemory::MemoryPort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, SimpleCache::CPUSidePort, RubyPort::MemSlavePort, SMMUSlavePort, SimpleMemobj::CPUSidePort, ExternalSlave::ExternalPort, DRAMSim2::MemoryPort, PioPort< Device >, PioPort< PioDevice >, PioPort< X86ISA::Interrupts >, X86ISA::IntSlavePort< Device >, and X86ISA::IntSlavePort< X86ISA::Interrupts >.
Referenced by MasterPort::getAddrRanges().
isSnooping()
bool SlavePort::isSnooping () const inline
Find out if the peer master port is snooping or not.
Returns
true if the peer master port is snooping
Definition at line 280 of file port.hh.
References MasterPort::isSnooping().
Referenced by BaseCache::functionalAccess(), BaseCache::init(), MemDelay::MasterPort::isSnooping(), MemCheckerMonitor::isSnooping(), AddrMapper::isSnooping(), CommMonitor::isSnooping(), SnoopFilter::lookupRequest(), SnoopFilter::portToMask(), SnoopFilter::updateResponse(), and SnoopFilter::updateSnoopResponse().
recvAtomicBackdoor()
Tick SlavePort::recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & backdoor) override protected virtual
Default implementations.
Implements AtomicResponseProtocol.
Reimplemented in sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, and SimpleMemory::MemoryPort.
Definition at line 139 of file port.cc.
References defaultBackdoorWarned, Port::name(), AtomicResponseProtocol::recvAtomic(), and warn.
recvTimingSnoopResp()
bool SlavePort::recvTimingSnoopResp (PacketPtr pkt) inline override protected virtual
Receive a timing snoop response from the peer.
Implements TimingResponseProtocol.
Reimplemented in sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort.
Definition at line 420 of file port.hh.
References Port::name(), and panic.
sendAtomicSnoop()
Tick SlavePort::sendAtomicSnoop (PacketPtr pkt) inline
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters
pkt Snoop packet to send.
Returns
Estimated latency of access.
Definition at line 321 of file port.hh.
References AtomicResponseProtocol::sendSnoop().
Referenced by Cache::handleSnoop(), Cache::isCachedAbove(), MemDelay::MasterPort::recvAtomicSnoop(), AddrMapper::recvAtomicSnoop(), and CommMonitor::recvAtomicSnoop().
sendFunctionalSnoop()
void SlavePort::sendFunctionalSnoop (PacketPtr pkt) const inline
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters
pkt Snoop packet to send.
Definition at line 337 of file port.hh.
References FunctionalResponseProtocol::sendSnoop().
Referenced by BaseCache::functionalAccess(), MemDelay::MasterPort::recvFunctionalSnoop(), MemCheckerMonitor::recvFunctionalSnoop(), AddrMapper::recvFunctionalSnoop(), and CommMonitor::recvFunctionalSnoop().
sendRangeChange()
void SlavePort::sendRangeChange () const inline
Called by the owner to send a range change.
Definition at line 286 of file port.hh.
References fatal_if, MasterPort::getAddrRanges(), Port::name(), and MasterPort::recvRangeChange().
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration(), ExternalSlave::init(), PioDevice::init(), QoS::MemSinkCtrl::init(), SMMUv3::init(), SimpleMemory::init(), DRAMSim2::init(), SerialLink::init(), Bridge::init(), BaseCache::init(), DRAMCtrl::init(), SimpleMemobj::MemSidePort::MemSidePort(), SimpleCache::MemSidePort::MemSidePort(), MemDelay::MasterPort::recvRangeChange(), RubyPort::PioMasterPort::recvRangeChange(), MemCheckerMonitor::recvRangeChange(), AddrMapper::recvRangeChange(), CommMonitor::recvRangeChange(), SMMUv3SlaveInterface::sendRange(), SimpleMemobj::sendRangeChange(), PciDevice::unserialize(), Sinic::Device::unserialize(), and PciDevice::writeConfig().
sendRetryReq()
void SlavePort::sendRetryReq () inline
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
Definition at line 380 of file port.hh.
References TimingResponseProtocol::sendRetryReq().
Referenced by SMMUv3SlaveInterface::atsSendDeviceRetry(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::processRespondEvent(), StubSlavePort::processResponseEvent(), MemCheckerMonitor::recvReqRetry(), AddrMapper::recvReqRetry(), CommMonitor::recvReqRetry(), SimpleMemory::release(), SMMUv3SlaveInterface::sendDeviceRetry(), BaseXBar::ReqLayer::sendRetry(), and DRAMSim2::tick().
sendRetrySnoopResp()
void SlavePort::sendRetrySnoopResp () inline
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Definition at line 390 of file port.hh.
References TimingResponseProtocol::sendRetrySnoopResp().
Referenced by CommMonitor::recvRetrySnoopResp(), BaseXBar::SnoopRespLayer::sendRetry(), and CoherentXBar::SnoopRespPort::sendRetryResp().
sendTimingResp()
bool SlavePort::sendTimingResp (PacketPtr pkt) inline
Attempt to send a timing response to the master port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvRespRetry at which point it can re-issue a sendTimingResp.
Parameters
pkt Packet to send.
Returns
If the send was succesful or not.
Definition at line 357 of file port.hh.
References TimingResponseProtocol::sendResp().
Referenced by SimpleMemory::dequeue(), LdsState::process(), StubSlavePort::processResponseEvent(), MemCheckerMonitor::recvTimingResp(), AddrMapper::recvTimingResp(), CommMonitor::recvTimingResp(), DRAMSim2::sendResponse(), RespPacketQueue::sendTiming(), and TLBCoalescer::updatePhysAddresses().
sendTimingSnoopReq()
void SlavePort::sendTimingSnoopReq (PacketPtr pkt) inline
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
Snoop requests always succeed and hence no return value is needed.
Parameters
pkt Packet to send.
Definition at line 370 of file port.hh.
References TimingResponseProtocol::sendSnoopReq().
Referenced by Cache::handleSnoop(), Cache::isCachedAbove(), MemDelay::MasterPort::recvTimingSnoopReq(), MemCheckerMonitor::recvTimingSnoopReq(), AddrMapper::recvTimingSnoopReq(), CommMonitor::recvTimingSnoopReq(), and Cache::sendMSHRQueuePacket().
slaveBind()
void SlavePort::slaveBind (MasterPort & master_port) protected
Called by the master port to bind.
Should never be called directly.
Definition at line 132 of file port.cc.
References _masterPort, and Port::bind().
slaveUnbind()
void SlavePort::slaveUnbind () protected
Called by the master port to unbind.
Should never be called directly.
Definition at line 125 of file port.cc.
References _masterPort, and Port::unbind().
Referenced by MasterPort::unbind().
tryTiming()
bool SlavePort::tryTiming (PacketPtr pkt) inline override protected virtual
Availability request from the peer.
Implements TimingResponseProtocol.
Reimplemented in sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort.
Definition at line 414 of file port.hh.
References Port::name(), and panic.
unbind()
void SlavePort::unbind () inline override virtual
We let the master port do the work, so these don't do anything.
Reimplemented from Port.
Definition at line 305 of file port.hh.
Friends And Related Function Documentation
MasterPort
friend class MasterPort friend
Definition at line 261 of file port.hh.
Member Data Documentation
_masterPort
MasterPort* SlavePort::_masterPort private
Definition at line 264 of file port.hh.
Referenced by slaveBind(), and slaveUnbind().
defaultBackdoorWarned
bool SlavePort::defaultBackdoorWarned private
Definition at line 265 of file port.hh.
Referenced by recvAtomicBackdoor().
owner
SimObject& SlavePort::owner protected
Definition at line 268 of file port.hh.
Referenced by RubyPort::MemSlavePort::addToRetryList(), RubyPort::PioSlavePort::getAddrRanges(), RubyPort::MemSlavePort::hitCallback(), RubyPort::MemSlavePort::isPhysMemAddress(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::PioSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvFunctional(), RubyPort::PioMasterPort::recvRangeChange(), RubyPort::MemSlavePort::recvTimingReq(), RubyPort::PioSlavePort::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), and RubyPort::PioMasterPort::recvTimingResp().
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc