gem5: CPA Class Reference
CPA Class Reference
#include <cp_annotate.hh>
Public Types
enum flags {
FL_NONE = 0x00, FL_HW = 0x01, FL_BAD = 0x02, FL_QOPP = 0x04,
FL_WAIT = 0x08, FL_LINK = 0x10, FL_RESET = 0x20
}
Public Member Functions
bool enabled ()
void swSmBegin (ThreadContext *tc)
void swSmEnd (ThreadContext *tc)
void swExplictBegin (ThreadContext *tc)
void swAutoBegin (ThreadContext *tc, Addr next_pc)
void swEnd (ThreadContext *tc)
void swQ (ThreadContext *tc)
void swDq (ThreadContext *tc)
void swPq (ThreadContext *tc)
void swRq (ThreadContext *tc)
void swWf (ThreadContext *tc)
void swWe (ThreadContext *tc)
void swSq (ThreadContext *tc)
void swAq (ThreadContext *tc)
void swLink (ThreadContext *tc)
void swIdentify (ThreadContext *tc)
uint64_t swGetId (ThreadContext *tc)
void swSyscallLink (ThreadContext *tc)
void hwBegin (flags f, System *sys, uint64_t frame, std::string sm, std::string st)
void hwQ (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
void hwDq (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
void hwPq (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
void hwRq (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
void hwWf (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
void hwWe (flags f, System *sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System *q_sys=NULL, int32_t count=1)
Static Public Member Functions
static CPA * cpa ()
static bool available ()
Detailed Description
Definition at line 71 of file cp_annotate.hh.
Member Enumeration Documentation
flags
enum CPA::flags
Enumerator
FL_NONE
FL_HW
FL_BAD
FL_QOPP
FL_WAIT
FL_LINK
FL_RESET
Definition at line 74 of file cp_annotate.hh.
Member Function Documentation
available()
static bool CPA::available () inline static
Definition at line 85 of file cp_annotate.hh.
Referenced by DefaultCommit< Impl >::commitHead(), IGbE::ethRxPkt(), hwWe(), and BaseSimpleCPU::postExecute().
cpa()
static CPA* CPA::cpa () inline static
Definition at line 84 of file cp_annotate.hh.
Referenced by CopyEngine::CopyEngineChannel::anBegin(), CopyEngine::CopyEngineChannel::anDq(), CopyEngine::CopyEngineChannel::anPq(), CopyEngine::CopyEngineChannel::anQ(), CopyEngine::CopyEngineChannel::anWait(), DefaultCommit< Impl >::commitHead(), hwWe(), IGbE::init(), and BaseSimpleCPU::postExecute().
enabled()
bool CPA::enabled () inline
Definition at line 86 of file cp_annotate.hh.
Referenced by IGbE::ethRxPkt(), and hwWe().
hwBegin()
void CPA::hwBegin (flags f, System * sys, uint64_t frame, std::string sm, std::string st) inline
Definition at line 104 of file cp_annotate.hh.
Referenced by CopyEngine::CopyEngineChannel::anBegin(), IGbE::anBegin(), and hwWe().
hwDq()
void CPA::hwDq (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 109 of file cp_annotate.hh.
Referenced by CopyEngine::CopyEngineChannel::anDq(), IGbE::anDq(), CopyEngine::CopyEngineChannel::anPq(), IGbE::ethRxPkt(), and hwWe().
hwPq()
void CPA::hwPq (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 112 of file cp_annotate.hh.
Referenced by IGbE::anPq(), and hwWe().
hwQ()
void CPA::hwQ (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 106 of file cp_annotate.hh.
Referenced by CopyEngine::CopyEngineChannel::anQ(), IGbE::anQ(), and hwWe().
hwRq()
void CPA::hwRq (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 115 of file cp_annotate.hh.
Referenced by IGbE::anRq(), and hwWe().
hwWe()
void CPA::hwWe (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 121 of file cp_annotate.hh.
References Stats::_enabled, available(), ArmISA::c, X86ISA::count, cpa(), MipsISA::cpuid, curTick(), data, DPRINTFS, Stats::dump(), enabled(), ArmISA::f, FL_BAD, FL_HW, FL_LINK, FL_NONE, FL_QOPP, FL_RESET, FL_WAIT, hwBegin(), hwDq(), hwPq(), hwQ(), hwRq(), hwWf(), ArmISA::i, SimObject::name(), X86ISA::op, MipsISA::p, ArmISA::q, ArmISA::s, serialize(), PowerISA::si, MipsISA::sm, ArmISA::st, RiscvISA::sti, swAq(), swAutoBegin(), swDq(), swEnd(), swExplictBegin(), swGetId(), swIdentify(), swLink(), swPq(), swQ(), swRq(), swSmBegin(), swSmEnd(), swSq(), swSyscallLink(), swWe(), swWf(), ArmISA::t, unserialize(), warn, and X86ISA::x.
Referenced by CopyEngine::CopyEngineChannel::anWait(), IGbE::anWe(), and IGbE::ethRxPkt().
hwWf()
void CPA::hwWf (flags f, System * sys, uint64_t frame, std::string sm, std::string q, uint64_t qid, System * q_sys = NULL, int32_t count = 1) inline
Definition at line 118 of file cp_annotate.hh.
Referenced by IGbE::anWf(), and hwWe().
swAq()
void CPA::swAq (ThreadContext * tc) inline
Definition at line 99 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swAutoBegin()
void CPA::swAutoBegin (ThreadContext * tc, Addr next_pc) inline
Definition at line 90 of file cp_annotate.hh.
Referenced by DefaultCommit< Impl >::commitHead(), hwWe(), BaseSimpleCPU::postExecute(), and AnnotateDumpCallback::process().
swDq()
void CPA::swDq (ThreadContext * tc) inline
Definition at line 93 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swEnd()
void CPA::swEnd (ThreadContext * tc) inline
Definition at line 91 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swExplictBegin()
void CPA::swExplictBegin (ThreadContext * tc) inline
Definition at line 89 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swGetId()
uint64_t CPA::swGetId (ThreadContext * tc) inline
Definition at line 102 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swIdentify()
void CPA::swIdentify (ThreadContext * tc) inline
Definition at line 101 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swLink()
void CPA::swLink (ThreadContext * tc) inline
Definition at line 100 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swPq()
void CPA::swPq (ThreadContext * tc) inline
Definition at line 94 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swQ()
void CPA::swQ (ThreadContext * tc) inline
Definition at line 92 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swRq()
void CPA::swRq (ThreadContext * tc) inline
Definition at line 95 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swSmBegin()
void CPA::swSmBegin (ThreadContext * tc) inline
Definition at line 87 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swSmEnd()
void CPA::swSmEnd (ThreadContext * tc) inline
Definition at line 88 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swSq()
void CPA::swSq (ThreadContext * tc) inline
Definition at line 98 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swSyscallLink()
void CPA::swSyscallLink (ThreadContext * tc) inline
Definition at line 103 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swWe()
void CPA::swWe (ThreadContext * tc) inline
Definition at line 97 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
swWf()
void CPA::swWf (ThreadContext * tc) inline
Definition at line 96 of file cp_annotate.hh.
Referenced by hwWe(), and AnnotateDumpCallback::process().
The documentation for this class was generated from the following files:
base/cp_annotate.hh
base/cp_annotate.cc