gem5: WriteQueueEntry::TargetList Class Reference
WriteQueueEntry::TargetList Class Reference
#include <write_queue_entry.hh>
Public Member Functions
TargetList ()
void add (PacketPtr pkt, Tick readyTime, Counter order)
bool trySatisfyFunctional (PacketPtr pkt)
void print (std::ostream &os, int verbosity, const std::string &prefix) const
Additional Inherited Members
Public Attributes inherited from std::list< Target >
Target item
Dummy Item.
Detailed Description
Definition at line 79 of file write_queue_entry.hh.
Constructor & Destructor Documentation
TargetList()
WriteQueueEntry::TargetList::TargetList () inline
Definition at line 83 of file write_queue_entry.hh.
References add(), QueueEntry::order, X86ISA::os, print(), QueueEntry::readyTime, and trySatisfyFunctional().
Member Function Documentation
add()
void WriteQueueEntry::TargetList::add (PacketPtr pkt, Tick readyTime, Counter order) inline
Definition at line 62 of file write_queue_entry.cc.
Referenced by WriteQueueEntry::allocate(), and TargetList().
print()
void WriteQueueEntry::TargetList::print (std::ostream & os, int verbosity, const std::string & prefix) const
Definition at line 81 of file write_queue_entry.cc.
References ccprintf(), and ArmISA::t.
Referenced by WriteQueueEntry::popTarget(), WriteQueueEntry::print(), and TargetList().
trySatisfyFunctional()
bool WriteQueueEntry::TargetList::trySatisfyFunctional (PacketPtr pkt)
Definition at line 69 of file write_queue_entry.cc.
References ArmISA::t, and Packet::trySatisfyFunctional().
Referenced by WriteQueueEntry::popTarget(), TargetList(), and WriteQueueEntry::trySatisfyFunctional().
The documentation for this class was generated from the following files:
mem/cache/write_queue_entry.hh
mem/cache/write_queue_entry.cc