gem5: FaultBase Class Reference
FaultBase Class Reference abstract
#include <faults.hh>
Public Member Functions
virtual FaultName name () const =0
virtual void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
virtual ~FaultBase ()
Detailed Description
Definition at line 44 of file faults.hh.
Constructor & Destructor Documentation
~FaultBase()
virtual FaultBase::~FaultBase () inline virtual
Definition at line 51 of file faults.hh.
Member Function Documentation
invoke()
void FaultBase::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented in ArmISA::ArmSev, ArmISA::SystemError, ArmISA::PCAlignmentFault, ArmISA::VirtualDataAbort, ArmISA::AbortFault< T >, ArmISA::AbortFault< VirtualDataAbort >, ArmISA::AbortFault< PrefetchAbort >, ArmISA::AbortFault< DataAbort >, X86ISA::StartupInterrupt, X86ISA::InitInterrupt, ArmISA::SecureMonitorCall, X86ISA::PageFault, ArmISA::SupervisorCall, ArmISA::UndefinedInstruction, ArmISA::Reset, SparcISA::TrapInstruction, SparcISA::FillNNormal, AlphaISA::ItbPageFault, MipsISA::TlbFault< T >, MipsISA::TlbFault< TlbRefillFault >, MipsISA::TlbFault< TlbModifiedFault >, MipsISA::TlbFault< TlbInvalidFault >, X86ISA::InvalidOpcode, SparcISA::SpillNNormal, AlphaISA::ItbFault, SparcISA::FastDataAccessMMUMiss, ArmISA::ArmFault, SparcISA::FastInstructionAccessMMUMiss, MipsISA::AddressFault< T >, MipsISA::AddressFault< AddressErrorFault >, MipsISA::AddressFault< TlbRefillFault >, MipsISA::AddressFault< TlbModifiedFault >, MipsISA::AddressFault< TlbInvalidFault >, MipsISA::CoprocessorUnusableFault, AlphaISA::NDtbMissFault, X86ISA::UnimpInstFault, MipsISA::NonMaskableInterrupt, AlphaISA::DtbFault, MipsISA::SoftResetFault, MipsISA::ResetFault, X86ISA::X86Abort, RiscvISA::Reset, X86ISA::X86Trap, AlphaISA::ArithmeticFault, RiscvISA::RiscvFault, GenericAlignmentFault, GenericISA::M5DebugOnceFault< Flavor >, MipsISA::MipsFaultBase, SparcISA::PowerOnReset, GenericPageTableFault, SyscallRetryFault, X86ISA::X86FaultBase, GenericISA::M5DebugFault, SparcISA::SparcFaultBase, ReExec, UnimpFault, and AlphaISA::AlphaFault.
Definition at line 43 of file faults.cc.
References DPRINTF, FullSystem, name(), panic, and ThreadContext::pcState().
Referenced by GenericAlignmentFault::GenericAlignmentFault(), GenericPageTableFault::GenericPageTableFault(), AlphaISA::AlphaFault::invoke(), SparcISA::SparcFaultBase::invoke(), X86ISA::X86FaultBase::invoke(), AlphaISA::ArithmeticFault::invoke(), ArmISA::ArmFault::invoke(), UnimpFault::name(), ReExec::ReExec(), and SyscallRetryFault::SyscallRetryFault().
name()
virtual FaultName FaultBase::name () const pure virtual
Implemented in AlphaISA::IntegerOverflowFault, AlphaISA::PalFault, AlphaISA::VectorEnableFault, AlphaISA::FloatEnableFault, AlphaISA::UnimplementedOpcodeFault, AlphaISA::ItbAcvFault, ArmISA::ArmFaultVals< T >, ArmISA::ArmFaultVals< VirtualDataAbort >, ArmISA::ArmFaultVals< PrefetchAbort >, ArmISA::ArmFaultVals< Interrupt >, ArmISA::ArmFaultVals< SoftwareBreakpoint >, ArmISA::ArmFaultVals< SupervisorCall >, ArmISA::ArmFaultVals< IllegalInstSetStateFault >, ArmISA::ArmFaultVals< HypervisorCall >, ArmISA::ArmFaultVals< Reset >, ArmISA::ArmFaultVals< UndefinedInstruction >, ArmISA::ArmFaultVals< HypervisorTrap >, ArmISA::ArmFaultVals< VirtualFastInterrupt >, ArmISA::ArmFaultVals< DataAbort >, ArmISA::ArmFaultVals< PCAlignmentFault >, ArmISA::ArmFaultVals< SupervisorTrap >, ArmISA::ArmFaultVals< SecureMonitorCall >, ArmISA::ArmFaultVals< SecureMonitorTrap >, ArmISA::ArmFaultVals< SPAlignmentFault >, ArmISA::ArmFaultVals< VirtualInterrupt >, ArmISA::ArmFaultVals< SystemError >, ArmISA::ArmFaultVals< ArmSev >, ArmISA::ArmFaultVals< FastInterrupt >, AlphaISA::ItbPageFault, AlphaISA::ItbFault, AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, AlphaISA::NDtbMissFault, X86ISA::UnimpInstFault, AlphaISA::DtbFault, GenericISA::M5FatalFault, AlphaISA::InterruptFault, GenericISA::M5PanicFault, RiscvISA::Reset, MipsISA::MipsFault< T >, MipsISA::MipsFault< IntegerOverflowFault >, MipsISA::MipsFault< SoftResetFault >, MipsISA::MipsFault< TrapFault >, MipsISA::MipsFault< DspStateDisabledFault >, MipsISA::MipsFault< NonMaskableInterrupt >, MipsISA::MipsFault< MachineCheckFault >, MipsISA::MipsFault< AddressErrorFault >, MipsISA::MipsFault< ThreadFault >, MipsISA::MipsFault< CoprocessorUnusableFault >, MipsISA::MipsFault< ResetFault >, MipsISA::MipsFault< TlbRefillFault >, MipsISA::MipsFault< ReservedInstructionFault >, MipsISA::MipsFault< BreakpointFault >, MipsISA::MipsFault< TlbModifiedFault >, MipsISA::MipsFault< InterruptFault >, MipsISA::MipsFault< TlbInvalidFault >, MipsISA::MipsFault< SystemCallFault >, GenericAlignmentFault, AlphaISA::ArithmeticFault, RiscvISA::RiscvFault, GenericPageTableFault, AlphaISA::ResetFault, SparcISA::SparcFault< T >, SparcISA::SparcFault< TagOverflow >, SparcISA::SparcFault< InstructionInvalidTSBEntry >, SparcISA::SparcFault< REDStateException >, SparcISA::SparcFault< HstickMatch >, SparcISA::SparcFault< PrivilegedOpcode >, SparcISA::SparcFault< VecDisabled >, SparcISA::SparcFault< InstructionBreakpoint >, SparcISA::SparcFault< FpDisabled >, SparcISA::SparcFault< StoreError >, SparcISA::SparcFault< InterruptLevelN >, SparcISA::SparcFault< FpExceptionIEEE754 >, SparcISA::SparcFault< DataRealTranslationMiss >, SparcISA::SparcFault< PrivilegedAction >, SparcISA::SparcFault< MemAddressNotAligned >, SparcISA::SparcFault< InstructionAccessException >, SparcISA::SparcFault< FastInstructionAccessMMUMiss >, SparcISA::SparcFault< InstructionRealTranslationMiss >, SparcISA::SparcFault< TrapInstruction >, SparcISA::SparcFault< ExternallyInitiatedReset >, SparcISA::SparcFault< CleanWindow >, SparcISA::SparcFault< LDQFMemAddressNotAligned >, SparcISA::SparcFault< DevMondo >, SparcISA::SparcFault< STDFMemAddressNotAligned >, SparcISA::SparcFault< FastDataAccessProtection >, SparcISA::SparcFault< DivisionByZero >, SparcISA::SparcFault< IllegalInstruction >, SparcISA::SparcFault< DataAccessError >, SparcISA::SparcFault< SpillNNormal >, SparcISA::SparcFault< SoftwareInitiatedReset >, SparcISA::SparcFault< FillNOther >, SparcISA::SparcFault< FpExceptionOther >, SparcISA::SparcFault< DataInvalidTSBEntry >, SparcISA::SparcFault< InstructionAccessError >, SparcISA::SparcFault< PowerOnReset >, SparcISA::SparcFault< DataAccessProtection >, SparcISA::SparcFault< InternalProcessorError >, SparcISA::SparcFault< ResumableError >, SparcISA::SparcFault< DataAccessException >, SparcISA::SparcFault< InterruptVector >, SparcISA::SparcFault< SpillNOther >, SparcISA::SparcFault< TrapLevelZero >, SparcISA::SparcFault< PAWatchpoint >, SparcISA::SparcFault< FastDataAccessMMUMiss >, SparcISA::SparcFault< FillNNormal >, SparcISA::SparcFault< VAWatchpoint >, SparcISA::SparcFault< STQFMemAddressNotAligned >, SparcISA::SparcFault< WatchDogReset >, SparcISA::SparcFault< LDDFMemAddressNotAligned >, SparcISA::SparcFault< CpuMondo >, SyscallRetryFault, AlphaISA::AlignmentFault, ReExec, X86ISA::X86FaultBase, AlphaISA::MachineCheckFault, UnimpFault, and PowerISA::PowerFault.
Referenced by AlphaISA::DtbFault::DtbFault(), invoke(), MipsISA::MipsFaultBase::invoke(), MipsISA::ResetFault::invoke(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), and AlphaISA::ItbFault::ItbFault().
The documentation for this class was generated from the following files:
sim/faults.hh
sim/faults.cc