gem5: sc_gem5::SensitivityEvents Class Reference
sc_gem5::SensitivityEvents Class Reference
#include <sensitivity.hh>
Public Member Functions
void clear () override
void addEvent (const ::sc_core::sc_event *event)
Public Member Functions inherited from sc_gem5::Sensitivity
void satisfy ()
virtual bool notifyWork (Event *e)
bool notify (Event *e)
virtual Category category ()=0
bool ofMethod ()
Protected Member Functions
SensitivityEvents (Process *p)
SensitivityEvents (Process *p, const std::set< const ::sc_core::sc_event *> &s)
Protected Member Functions inherited from sc_gem5::Sensitivity
Sensitivity (Process *p)
virtual ~Sensitivity ()
virtual void addToEvent (const ::sc_core::sc_event *e)=0
virtual void delFromEvent (const ::sc_core::sc_event *e)=0
Protected Attributes
std::set< const ::sc_core::sc_event * > events
Protected Attributes inherited from sc_gem5::Sensitivity
Process * process
Additional Inherited Members
Public Types inherited from sc_gem5::Sensitivity
enum Category { Static, Dynamic }
Detailed Description
Definition at line 145 of file sensitivity.hh.
Constructor & Destructor Documentation
SensitivityEvents() [1/2]
sc_gem5::SensitivityEvents::SensitivityEvents (Process * p) inline protected
Definition at line 150 of file sensitivity.hh.
SensitivityEvents() [2/2]
sc_gem5::SensitivityEvents::SensitivityEvents (Process * p, const std::set< const ::sc_core::sc_event *> & s) inline protected
Definition at line 151 of file sensitivity.hh.
Member Function Documentation
addEvent()
void sc_gem5::SensitivityEvents::addEvent (const ::sc_core::sc_event * event) inline
Definition at line 165 of file sensitivity.hh.
References ArmISA::e, ArmISA::f, ArmISA::i, sc_gem5::newStaticSensitivityEvent(), sc_gem5::newStaticSensitivityExport(), sc_gem5::newStaticSensitivityFinder(), sc_gem5::newStaticSensitivityInterface(), sc_gem5::newStaticSensitivityPort(), and MipsISA::p.
Referenced by sc_gem5::Port::finalizeFinder(), and sc_gem5::Port::finalizePort().
clear()
void sc_gem5::SensitivityEvents::clear () inline override virtual
Implements sc_gem5::Sensitivity.
Definition at line 158 of file sensitivity.hh.
References MipsISA::event.
Member Data Documentation
events
std::set<const ::sc_core::sc_event *> sc_gem5::SensitivityEvents::events protected
Definition at line 148 of file sensitivity.hh.
Referenced by sc_gem5::DynamicSensitivityEventOrList::notifyWork(), and sc_gem5::DynamicSensitivityEventAndList::notifyWork().
The documentation for this class was generated from the following file:
systemc/core/sensitivity.hh