gem5: DistIface::SyncEvent Class Reference
DistIface::SyncEvent Class Reference
The global event to schedule periodic dist sync.
Public Member Functions
SyncEvent ()
Only the firstly instantiated DistIface object will call this constructor.
~SyncEvent ()
void start ()
Schedule the first periodic sync event.
void process () override
This is a global event so process() will only be called by exactly one simulation thread.
bool draining () const
void draining (bool fl)
Public Member Functions inherited from GlobalSyncEvent
GlobalSyncEvent (Priority p, Flags f)
GlobalSyncEvent (Tick when, Tick _repeat, Priority p, Flags f)
void process ()
const char * description () const
Public Member Functions inherited from BaseGlobalEvent
BaseGlobalEvent (Priority p, Flags f)
virtual ~BaseGlobalEvent ()
void schedule (Tick when)
bool scheduled () const
Tick when () const
void deschedule ()
void reschedule (Tick when)
Private Attributes
bool _draining
Flag to set when the system is draining.
Additional Inherited Members
Public Types inherited from GlobalSyncEvent
typedef BaseGlobalEventTemplate< GlobalSyncEvent > Base
Public Types inherited from EventBase
typedef int8_t Priority
Public Attributes inherited from GlobalSyncEvent
Tick repeat
Static Public Attributes inherited from EventBase
static const Priority Minimum_Pri = SCHAR_MIN
Event priorities, to provide tie-breakers for events scheduled at the same cycle.
static const Priority Debug_Enable_Pri = -101
If we enable tracing on a particular cycle, do that as the very first thing so we don't miss any of the events on that cycle (even if we enter the debugger).
static const Priority Debug_Break_Pri = -100
Breakpoints should happen before anything else (except enabling trace output), so we don't miss any action when debugging.
static const Priority CPU_Switch_Pri = -31
CPU switches schedule the new CPU's tick event for the same cycle (after unscheduling the old CPU's tick event).
static const Priority Delayed_Writeback_Pri = -1
For some reason "delayed" inter-cluster writebacks are scheduled before regular writebacks (which have default priority).
static const Priority Default_Pri = 0
Default is zero for historical reasons.
static const Priority DVFS_Update_Pri = 31
DVFS update event leads to stats dump therefore given a lower priority to ensure all relevant states have been updated.
static const Priority Serialize_Pri = 32
Serailization needs to occur before tick events also, so that a serialize/unserialize is identical to an on-line CPU switch.
static const Priority CPU_Tick_Pri = 50
CPU ticks must come after other associated CPU events (such as writebacks).
static const Priority CPU_Exit_Pri = 64
If we want to exit a thread in a CPU, it comes after CPU_Tick_Pri.
static const Priority Stat_Event_Pri = 90
Statistics events (dump, reset, etc.) come after everything else, but before exit.
static const Priority Progress_Event_Pri = 95
Progress events come at the end.
static const Priority Sim_Exit_Pri = 100
If we want to exit on this cycle, it's the very last thing we do.
static const Priority Maximum_Pri = SCHAR_MAX
Maximum priority.
Protected Types inherited from EventBase
typedef unsigned short FlagsType
typedef ::Flags< FlagsType > Flags
Protected Member Functions inherited from BaseGlobalEventTemplate< GlobalSyncEvent >
BaseGlobalEventTemplate (Priority p, Flags f)
Protected Attributes inherited from BaseGlobalEvent
Barrier barrier
The barrier that all threads wait on before performing the global event.
std::vector< BarrierEvent * > barrierEvent
The individual local event instances (one per thread/event queue).
Static Protected Attributes inherited from EventBase
static const FlagsType PublicRead = 0x003f
static const FlagsType PublicWrite = 0x001d
static const FlagsType Squashed = 0x0001
static const FlagsType Scheduled = 0x0002
static const FlagsType Managed = 0x0004
static const FlagsType AutoDelete = Managed
static const FlagsType Reserved0 = 0x0008
This used to be AutoSerialize.
static const FlagsType IsExitEvent = 0x0010
static const FlagsType IsMainQueue = 0x0020
static const FlagsType Initialized = 0x7a40
static const FlagsType InitMask = 0xffc0
Detailed Description
The global event to schedule periodic dist sync.
It is used as a singleton object.
The periodic synchronisation works as follows.
A SyncEvent is scheduled as a global event when startup() is called.
The process() method of the SyncEvent initiates a new barrier for each simulated Ethernet link.
Simulation thread(s) then waits until all receiver threads complete the ongoing barrier. The global sync event is done.
Definition at line 297 of file dist_iface.hh.
Constructor & Destructor Documentation
SyncEvent()
DistIface::SyncEvent::SyncEvent () inline
Only the firstly instantiated DistIface object will call this constructor.
Definition at line 309 of file dist_iface.hh.
~SyncEvent()
DistIface::SyncEvent::~SyncEvent () inline
Definition at line 311 of file dist_iface.hh.
Member Function Documentation
draining() [1/2]
bool DistIface::SyncEvent::draining () const inline
Definition at line 323 of file dist_iface.hh.
Referenced by DistIface::drain(), and DistIface::drainResume().
draining() [2/2]
void DistIface::SyncEvent::draining (bool fl) inline
Definition at line 324 of file dist_iface.hh.
process()
void DistIface::SyncEvent::process () override virtual
This is a global event so process() will only be called by exactly one simulation thread.
(See further comments in the .cc file.)
Implements BaseGlobalEvent.
Definition at line 367 of file dist_iface.cc.
References ThreadContext::activate(), curEventQueue(), curTick(), DistIface::Sync::doStopSync, exitSimLoop(), System::getThreadContext(), ArmISA::i, inform, DistIface::isSwitch, DistIface::Sync::nextRepeat, System::numContexts(), panic_if, MipsISA::sr, ThreadContext::status(), ThreadContext::Suspended, DistIface::sys, and warn_once.
start()
void DistIface::SyncEvent::start ()
Schedule the first periodic sync event.
Definition at line 333 of file dist_iface.cc.
References curTick(), inform, DistIface::Sync::nextRepeat, and panic.
Referenced by DistIface::readyToExit(), DistIface::startup(), and DistIface::toggleSync().
Member Data Documentation
_draining
bool DistIface::SyncEvent::_draining private
Flag to set when the system is draining.
Definition at line 303 of file dist_iface.hh.
The documentation for this class was generated from the following files:
dev/net/dist_iface.hh
dev/net/dist_iface.cc