gem5: sc_core::sc_inout_resolved Class Reference
sc_core::sc_inout_resolved Class Reference
#include <sc_inout_resolved.hh>
Public Member Functions
sc_inout_resolved ()
sc_inout_resolved (const char *name)
virtual ~sc_inout_resolved ()
virtual void end_of_elaboration ()
sc_inout_resolved & operator= (const sc_dt::sc_logic &)
sc_inout_resolved & operator= (const sc_signal_in_if< sc_dt::sc_logic > &)
sc_inout_resolved & operator= (const sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 > &)
sc_inout_resolved & operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 > &)
sc_inout_resolved & operator= (const sc_inout_resolved &)
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_inout< sc_dt::sc_logic >
sc_inout ()
sc_inout (const char *name)
virtual ~sc_inout ()
sc_inout (const sc_signal_inout_if< sc_dt::sc_logic > &interface)
sc_inout (const char *name, const sc_signal_inout_if< sc_dt::sc_logic > &interface)
sc_inout (sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &parent)
sc_inout (const char *name, sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &parent)
sc_inout (sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 > &parent)
sc_inout (const char *name, sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 > &parent)
void initialize (const sc_dt::sc_logic &l)
void initialize (const sc_signal_in_if< sc_dt::sc_logic > &i)
const sc_dt::sc_logic & read () const
operator const sc_dt::sc_logic & () const
void write (const sc_dt::sc_logic &l)
sc_inout< sc_dt::sc_logic > & operator= (const sc_dt::sc_logic &l)
sc_inout< sc_dt::sc_logic > & operator= (const sc_signal_in_if< sc_dt::sc_logic > &i)
sc_inout< sc_dt::sc_logic > & operator= (const sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 > &p)
sc_inout< sc_dt::sc_logic > & operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 > &p)
sc_inout< sc_dt::sc_logic > & operator= (const sc_inout< sc_dt::sc_logic > &p)
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_event & posedge_event () const
const sc_event & negedge_event () const
bool event () const
bool posedge () const
bool negedge () const
sc_event_finder & value_changed () const
sc_event_finder & pos () const
sc_event_finder & neg () const
void add_trace (sc_trace_file *tf, const std::string &name) const
Public Member Functions inherited from sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_inout_if< sc_dt::sc_logic > &interface)
sc_port (const char *name, const sc_signal_inout_if< sc_dt::sc_logic > &interface)
sc_port (sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &parent)
sc_port (sc_port< sc_signal_inout_if< sc_dt::sc_logic >, N, SC_ONE_OR_MORE_BOUND > &parent)
sc_port (const char *name, sc_port< sc_signal_inout_if< sc_dt::sc_logic >, N, SC_ONE_OR_MORE_BOUND > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >
void operator() (sc_signal_inout_if< sc_dt::sc_logic > &i)
void operator() (sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &p)
virtual void bind (sc_signal_inout_if< sc_dt::sc_logic > &i)
virtual void bind (sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > > &p)
sc_signal_inout_if< sc_dt::sc_logic > * operator-> ()
const sc_signal_inout_if< sc_dt::sc_logic > * operator-> () const
sc_signal_inout_if< sc_dt::sc_logic > * operator[] (int n)
const sc_signal_inout_if< sc_dt::sc_logic > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Member Functions
sc_inout_resolved (const sc_inout_resolved &)
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
Definition at line 47 of file sc_inout_resolved.hh.
Constructor & Destructor Documentation
sc_inout_resolved() [1/3]
sc_core::sc_inout_resolved::sc_inout_resolved ()
Definition at line 39 of file sc_inout_resolved.cc.
sc_inout_resolved() [2/3]
sc_core::sc_inout_resolved::sc_inout_resolved (const char * name) explicit
Definition at line 41 of file sc_inout_resolved.cc.
~sc_inout_resolved()
sc_core::sc_inout_resolved::~sc_inout_resolved () virtual
Definition at line 45 of file sc_inout_resolved.cc.
sc_inout_resolved() [3/3]
sc_core::sc_inout_resolved::sc_inout_resolved (const sc_inout_resolved &) inline private
Definition at line 68 of file sc_inout_resolved.hh.
Member Function Documentation
end_of_elaboration()
void sc_core::sc_inout_resolved::end_of_elaboration () virtual
Reimplemented from sc_core::sc_inout< sc_dt::sc_logic >.
Definition at line 48 of file sc_inout_resolved.cc.
References csprintf(), sc_core::sc_inout< T >::end_of_elaboration(), sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >::get_interface(), kind(), sc_core::sc_object::name(), sc_core::SC_ID_RESOLVED_PORT_NOT_BOUND_, and SC_REPORT_ERROR.
kind()
virtual const char* sc_core::sc_inout_resolved::kind () const inline virtual
Reimplemented from sc_core::sc_inout< sc_dt::sc_logic >.
Reimplemented in sc_core::sc_out_resolved.
Definition at line 64 of file sc_inout_resolved.hh.
Referenced by end_of_elaboration().
operator=() [1/5]
sc_inout_resolved & sc_core::sc_inout_resolved::operator= (const sc_dt::sc_logic & l)
Definition at line 58 of file sc_inout_resolved.cc.
References sc_core::sc_inout< sc_dt::sc_logic >::write().
operator=() [2/5]
sc_inout_resolved & sc_core::sc_inout_resolved::operator= (const sc_signal_in_if< sc_dt::sc_logic > & i)
Definition at line 65 of file sc_inout_resolved.cc.
References sc_core::sc_signal_in_if< sc_dt::sc_logic >::read(), and sc_core::sc_inout< sc_dt::sc_logic >::write().
operator=() [3/5]
sc_inout_resolved & sc_core::sc_inout_resolved::operator= (const sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 > & p)
Definition at line 72 of file sc_inout_resolved.cc.
References MipsISA::p, and sc_core::sc_inout< sc_dt::sc_logic >::write().
operator=() [4/5]
sc_inout_resolved & sc_core::sc_inout_resolved::operator= (const sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 > & p)
Definition at line 80 of file sc_inout_resolved.cc.
References MipsISA::p, and sc_core::sc_inout< sc_dt::sc_logic >::write().
operator=() [5/5]
sc_inout_resolved & sc_core::sc_inout_resolved::operator= (const sc_inout_resolved & p)
Definition at line 88 of file sc_inout_resolved.cc.
References sc_core::sc_inout< sc_dt::sc_logic >::read(), and sc_core::sc_inout< sc_dt::sc_logic >::write().
The documentation for this class was generated from the following files:
systemc/ext/channel/sc_inout_resolved.hh
systemc/channel/sc_inout_resolved.cc