gem5: NetworkInterface Class Reference
NetworkInterface Class Reference
#include <NetworkInterface.hh>
Public Types
typedef GarnetNetworkInterfaceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
NetworkInterface (const Params *p)
~NetworkInterface ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void addInPort (NetworkLink *in_link, CreditLink *credit_link)
void addOutPort (NetworkLink *out_link, CreditLink *credit_link, SwitchID router_id)
void dequeueCallback ()
void wakeup ()
void addNode (std::vector< MessageBuffer *> &inNode, std::vector< MessageBuffer *> &outNode)
void print (std::ostream &out) const
int get_vnet (int vc)
int get_router_id ()
void init_net_ptr (GarnetNetwork *net_ptr)
uint32_t functionalWrite (Packet *)
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Member Functions inherited from Consumer
Consumer (ClockedObject *_em)
virtual ~Consumer ()
virtual void storeEventInfo (int info)
bool alreadyScheduled (Tick time)
void insertScheduledWakeupTime (Tick time)
void scheduleEventAbsolute (Tick timeAbs)
Private Member Functions
bool checkStallQueue ()
bool flitisizeMessage (MsgPtr msg_ptr, int vnet)
int calculateVC (int vnet)
void scheduleOutputLink ()
This function looks at the NI buffers if some buffer has flits which are ready to traverse the link in the next cycle, and the downstream output vc associated with this flit has buffers left, the link is scheduled for the next cycle.
void checkReschedule ()
void sendCredit (flit *t_flit, bool is_free)
void incrementStats (flit *t_flit)
Private Attributes
GarnetNetwork * m_net_ptr
const NodeID m_id
const int m_virtual_networks
const int m_vc_per_vnet
const int m_num_vcs
int m_router_id
std::vector< OutVcState * > m_out_vc_state
std::vector< int > m_vc_allocator
int m_vc_round_robin
flitBuffer * outFlitQueue
flitBuffer * outCreditQueue
int m_deadlock_threshold
NetworkLink * inNetLink
NetworkLink * outNetLink
CreditLink * inCreditLink
CreditLink * outCreditLink
std::deque< flit * > m_stall_queue
std::vector< int > m_stall_count
std::vector< flitBuffer * > m_ni_out_vcs
std::vector< Cycles > m_ni_out_vcs_enqueue_time
std::vector< MessageBuffer * > inNode_ptr
std::vector< MessageBuffer * > outNode_ptr
std::vector< int > vc_busy_counter
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Member Functions inherited from Consumer
void scheduleEvent (Cycles timeDelta)
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 52 of file NetworkInterface.hh.
Member Typedef Documentation
Params
typedef GarnetNetworkInterfaceParams NetworkInterface::Params
Definition at line 55 of file NetworkInterface.hh.
Constructor & Destructor Documentation
NetworkInterface()
NetworkInterface::NetworkInterface (const Params * p)
Definition at line 50 of file NetworkInterface.cc.
References ArmISA::i, INFINITE_, m_ni_out_vcs, m_ni_out_vcs_enqueue_time, m_num_vcs, m_router_id, m_stall_count, m_vc_allocator, m_vc_round_robin, m_virtual_networks, and outCreditQueue.
Referenced by functionalWrite().
~NetworkInterface()
NetworkInterface::~NetworkInterface ()
Definition at line 85 of file NetworkInterface.cc.
References m5::stl_helpers::deletePointers(), m_ni_out_vcs, m_out_vc_state, outCreditQueue, and outFlitQueue.
Member Function Documentation
addInPort()
void NetworkInterface::addInPort (NetworkLink * in_link, CreditLink * credit_link)
Definition at line 94 of file NetworkInterface.cc.
References inNetLink, outCreditLink, outCreditQueue, NetworkLink::setLinkConsumer(), and NetworkLink::setSourceQueue().
addNode()
void NetworkInterface::addNode (std::vector< MessageBuffer *> & inNode, std::vector< MessageBuffer *> & outNode)
Definition at line 119 of file NetworkInterface.cc.
References inNode_ptr, and outNode_ptr.
addOutPort()
void NetworkInterface::addOutPort (NetworkLink * out_link, CreditLink * credit_link, SwitchID router_id)
Definition at line 104 of file NetworkInterface.cc.
References inCreditLink, m_router_id, outFlitQueue, outNetLink, NetworkLink::setLinkConsumer(), and NetworkLink::setSourceQueue().
calculateVC()
int NetworkInterface::calculateVC (int vnet) private
Definition at line 406 of file NetworkInterface.cc.
References Clocked::curCycle(), curTick(), ArmISA::i, IDLE_, m_deadlock_threshold, m_out_vc_state, m_vc_allocator, m_vc_per_vnet, SimObject::name(), panic_if, and vc_busy_counter.
Referenced by flitisizeMessage().
checkReschedule()
void NetworkInterface::checkReschedule () private
Definition at line 505 of file NetworkInterface.cc.
References Clocked::clockEdge(), Clocked::curCycle(), inNode_ptr, m_ni_out_vcs, m_num_vcs, and Consumer::scheduleEvent().
Referenced by wakeup().
checkStallQueue()
bool NetworkInterface::checkStallQueue () private
Definition at line 281 of file NetworkInterface.cc.
References Clocked::clockEdge(), Clocked::cyclesToTicks(), flit::get_msg_ptr(), flit::get_vnet(), incrementStats(), m_stall_count, m_stall_queue, outNode_ptr, and sendCredit().
Referenced by wakeup().
dequeueCallback()
void NetworkInterface::dequeueCallback ()
Definition at line 133 of file NetworkInterface.cc.
References Clocked::clockEdge(), and Consumer::scheduleEventAbsolute().
Referenced by wakeup().
flitisizeMessage()
bool NetworkInterface::flitisizeMessage (MsgPtr msg_ptr, int vnet) private
Definition at line 327 of file NetworkInterface.cc.
References ACTIVE_, NetDest::add(), calculateVC(), NetDest::clear(), Clocked::curCycle(), RouteInfo::dest_ni, RouteInfo::dest_router, GarnetNetwork::get_router_id(), NetDest::getAllDest(), Message::getDestination(), Message::getMessageSize(), GarnetNetwork::getNiFlitSize(), RouteInfo::hops_traversed, ArmISA::i, GarnetNetwork::increment_injected_flits(), GarnetNetwork::increment_injected_packets(), ArmISA::m, m_id, m_net_ptr, m_ni_out_vcs, m_ni_out_vcs_enqueue_time, m_out_vc_state, m_router_id, Network::MessageSizeType_to_int(), RouteInfo::net_dest, NetDest::removeNetDest(), flit::set_src_delay(), RouteInfo::src_ni, RouteInfo::src_router, Clocked::ticksToCycles(), and RouteInfo::vnet.
Referenced by wakeup().
functionalWrite()
uint32_t NetworkInterface::functionalWrite (Packet * pkt)
Definition at line 533 of file NetworkInterface.cc.
References flitBuffer::functionalWrite(), ArmISA::i, m_ni_out_vcs, m_num_vcs, NetworkInterface(), and outFlitQueue.
Referenced by init_net_ptr().
get_router_id()
int NetworkInterface::get_router_id () inline
Definition at line 72 of file NetworkInterface.hh.
References m_router_id.
get_vnet()
int NetworkInterface::get_vnet (int vc)
Definition at line 490 of file NetworkInterface.cc.
References fatal, ArmISA::i, m_vc_per_vnet, and m_virtual_networks.
Referenced by scheduleOutputLink().
incrementStats()
void NetworkInterface::incrementStats (flit * t_flit) private
Definition at line 143 of file NetworkInterface.cc.
References Clocked::curCycle(), flit::get_dequeue_time(), flit::get_enqueue_time(), flit::get_route(), flit::get_src_delay(), flit::get_type(), flit::get_vnet(), HEAD_TAIL_, RouteInfo::hops_traversed, GarnetNetwork::increment_flit_network_latency(), GarnetNetwork::increment_flit_queueing_latency(), GarnetNetwork::increment_packet_network_latency(), GarnetNetwork::increment_packet_queueing_latency(), GarnetNetwork::increment_received_flits(), GarnetNetwork::increment_received_packets(), GarnetNetwork::increment_total_hops(), m_net_ptr, and TAIL_.
Referenced by checkStallQueue(), and wakeup().
init()
void NetworkInterface::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 78 of file NetworkInterface.cc.
References ArmISA::i, m_net_ptr, m_num_vcs, and m_out_vc_state.
init_net_ptr()
void NetworkInterface::init_net_ptr (GarnetNetwork * net_ptr) inline
Definition at line 73 of file NetworkInterface.hh.
References functionalWrite(), and m_net_ptr.
Referenced by GarnetNetwork::GarnetNetwork().
print()
void NetworkInterface::print (std::ostream & out) const virtual
Implements Consumer.
Definition at line 527 of file NetworkInterface.cc.
scheduleOutputLink()
void NetworkInterface::scheduleOutputLink () private
This function looks at the NI buffers if some buffer has flits which are ready to traverse the link in the next cycle, and the downstream output vc associated with this flit has buffers left, the link is scheduled for the next cycle.
Definition at line 437 of file NetworkInterface.cc.
References Clocked::clockEdge(), Clocked::curCycle(), flit::get_type(), get_vnet(), HEAD_TAIL_, ArmISA::i, INFINITE_, flitBuffer::insert(), GarnetNetwork::isVNetOrdered(), m_net_ptr, m_ni_out_vcs, m_ni_out_vcs_enqueue_time, m_num_vcs, m_out_vc_state, m_vc_per_vnet, m_vc_round_robin, outFlitQueue, outNetLink, Consumer::scheduleEventAbsolute(), flit::set_time(), and TAIL_.
Referenced by wakeup().
sendCredit()
void NetworkInterface::sendCredit (flit * t_flit, bool is_free) private
Definition at line 274 of file NetworkInterface.cc.
References Clocked::curCycle(), flit::get_vc(), flitBuffer::insert(), and outCreditQueue.
Referenced by checkStallQueue(), and wakeup().
wakeup()
void NetworkInterface::wakeup () virtual
Implements Consumer.
Definition at line 179 of file NetworkInterface.cc.
References ArmISA::b, checkReschedule(), checkStallQueue(), Clocked::clockEdge(), NetworkLink::consumeLink(), Clocked::curCycle(), Clocked::cyclesToTicks(), MessageBuffer::dequeue(), dequeueCallback(), DPRINTF, flitisizeMessage(), flit::get_msg_ptr(), flit::get_type(), flit::get_vc(), flit::get_vnet(), flitBuffer::getSize(), HEAD_TAIL_, IDLE_, inCreditLink, incrementStats(), inNetLink, inNode_ptr, Credit::is_free_signal(), MessageBuffer::isReady(), NetworkLink::isReady(), m_id, m_out_vc_state, m_router_id, m_stall_count, m_stall_queue, outCreditLink, outCreditQueue, outNode_ptr, MessageBuffer::peekMsgPtr(), Consumer::scheduleEventAbsolute(), scheduleOutputLink(), sendCredit(), flit::set_dequeue_time(), and TAIL_.
Member Data Documentation
inCreditLink
CreditLink* NetworkInterface::inCreditLink private
Definition at line 91 of file NetworkInterface.hh.
Referenced by addOutPort(), and wakeup().
inNetLink
NetworkLink* NetworkInterface::inNetLink private
Definition at line 89 of file NetworkInterface.hh.
Referenced by addInPort(), and wakeup().
inNode_ptr
std::vector<MessageBuffer *> NetworkInterface::inNode_ptr private
Definition at line 104 of file NetworkInterface.hh.
Referenced by addNode(), checkReschedule(), and wakeup().
m_deadlock_threshold
int NetworkInterface::m_deadlock_threshold private
Definition at line 87 of file NetworkInterface.hh.
Referenced by calculateVC().
m_id
const NodeID NetworkInterface::m_id private
Definition at line 79 of file NetworkInterface.hh.
Referenced by flitisizeMessage(), and wakeup().
m_net_ptr
GarnetNetwork* NetworkInterface::m_net_ptr private
Definition at line 78 of file NetworkInterface.hh.
Referenced by flitisizeMessage(), incrementStats(), init(), init_net_ptr(), and scheduleOutputLink().
m_ni_out_vcs
std::vector<flitBuffer *> NetworkInterface::m_ni_out_vcs private
Definition at line 100 of file NetworkInterface.hh.
Referenced by checkReschedule(), flitisizeMessage(), functionalWrite(), NetworkInterface(), scheduleOutputLink(), and ~NetworkInterface().
m_ni_out_vcs_enqueue_time
std::vector<Cycles> NetworkInterface::m_ni_out_vcs_enqueue_time private
Definition at line 101 of file NetworkInterface.hh.
Referenced by flitisizeMessage(), NetworkInterface(), and scheduleOutputLink().
m_num_vcs
const int NetworkInterface::m_num_vcs private
Definition at line 80 of file NetworkInterface.hh.
Referenced by checkReschedule(), functionalWrite(), init(), NetworkInterface(), and scheduleOutputLink().
m_out_vc_state
std::vector<OutVcState *> NetworkInterface::m_out_vc_state private
Definition at line 82 of file NetworkInterface.hh.
Referenced by calculateVC(), flitisizeMessage(), init(), scheduleOutputLink(), wakeup(), and ~NetworkInterface().
m_router_id
int NetworkInterface::m_router_id private
Definition at line 81 of file NetworkInterface.hh.
Referenced by addOutPort(), flitisizeMessage(), get_router_id(), NetworkInterface(), and wakeup().
m_stall_count
std::vector<int> NetworkInterface::m_stall_count private
Definition at line 96 of file NetworkInterface.hh.
Referenced by checkStallQueue(), NetworkInterface(), and wakeup().
m_stall_queue
std::deque<flit *> NetworkInterface::m_stall_queue private
Definition at line 95 of file NetworkInterface.hh.
Referenced by checkStallQueue(), and wakeup().
m_vc_allocator
std::vector<int> NetworkInterface::m_vc_allocator private
Definition at line 83 of file NetworkInterface.hh.
Referenced by calculateVC(), and NetworkInterface().
m_vc_per_vnet
const int NetworkInterface::m_vc_per_vnet private
Definition at line 80 of file NetworkInterface.hh.
Referenced by calculateVC(), get_vnet(), and scheduleOutputLink().
m_vc_round_robin
int NetworkInterface::m_vc_round_robin private
Definition at line 84 of file NetworkInterface.hh.
Referenced by NetworkInterface(), and scheduleOutputLink().
m_virtual_networks
const int NetworkInterface::m_virtual_networks private
Definition at line 80 of file NetworkInterface.hh.
Referenced by get_vnet(), and NetworkInterface().
outCreditLink
CreditLink* NetworkInterface::outCreditLink private
Definition at line 92 of file NetworkInterface.hh.
Referenced by addInPort(), and wakeup().
outCreditQueue
flitBuffer* NetworkInterface::outCreditQueue private
Definition at line 86 of file NetworkInterface.hh.
Referenced by addInPort(), NetworkInterface(), sendCredit(), wakeup(), and ~NetworkInterface().
outFlitQueue
flitBuffer* NetworkInterface::outFlitQueue private
Definition at line 85 of file NetworkInterface.hh.
Referenced by addOutPort(), functionalWrite(), scheduleOutputLink(), and ~NetworkInterface().
outNetLink
NetworkLink* NetworkInterface::outNetLink private
Definition at line 90 of file NetworkInterface.hh.
Referenced by addOutPort(), and scheduleOutputLink().
outNode_ptr
std::vector<MessageBuffer *> NetworkInterface::outNode_ptr private
Definition at line 106 of file NetworkInterface.hh.
Referenced by addNode(), checkStallQueue(), and wakeup().
vc_busy_counter
std::vector<int> NetworkInterface::vc_busy_counter private
Definition at line 108 of file NetworkInterface.hh.
Referenced by calculateVC().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/NetworkInterface.hh
mem/ruby/network/garnet2.0/NetworkInterface.cc