gem5: LoopPredictor Class Reference
LoopPredictor Class Reference
#include <loop_predictor.hh>
Classes
struct BranchInfo
struct LoopEntry
Public Member Functions
int lindex (Addr pc_in, unsigned instShiftAmt) const
Computes the index used to access the loop predictor.
int finallindex (int lindex, int lowPcBits, int way) const
Computes the index used to access the ltable structures.
bool getLoop (Addr pc, BranchInfo *bi, bool speculative, unsigned instShiftAmt) const
Get a branch prediction from the loop predictor.
void loopUpdate (Addr pc, bool Taken, BranchInfo *bi, bool tage_pred)
Updates the loop predictor.
void specLoopUpdate (bool taken, BranchInfo *bi)
Speculatively updates the loop predictor iteration count (only for useSpeculation).
void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, bool tage_pred, BranchInfo *bi, unsigned instShiftAmt)
Update LTAGE for conditional branches.
bool loopPredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo *bi, bool prev_pred_taken, unsigned instShiftAmt)
Get the loop prediction.
void updateStats (bool taken, BranchInfo *bi)
Update the stats.
void squashLoop (BranchInfo *bi)
void squash (ThreadID tid, BranchInfo *bi)
virtual bool calcConf (int index) const
virtual bool optionalAgeInc () const
virtual BranchInfo * makeBranchInfo ()
int8_t getLoopUseCounter () const
Gets the value of the loop use counter.
void init () override
Initialize the loop predictor.
void regStats () override
Register stats for this object.
LoopPredictor (LoopPredictorParams *p)
size_t getSizeInBits () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Protected Member Functions
static void unsignedCtrUpdate (uint8_t &ctr, bool up, unsigned nbits)
Updates an unsigned counter based on up/down parameter.
static void signedCtrUpdate (int8_t &ctr, bool up, unsigned nbits)
Protected Attributes
const unsigned logSizeLoopPred
const unsigned loopTableAgeBits
const unsigned loopTableConfidenceBits
const unsigned loopTableTagBits
const unsigned loopTableIterBits
const unsigned logLoopTableAssoc
const uint8_t confidenceThreshold
const uint16_t loopTagMask
const uint16_t loopNumIterMask
const int loopSetMask
LoopEntry * ltable
int8_t loopUseCounter
unsigned withLoopBits
const bool useDirectionBit
const bool useSpeculation
const bool useHashing
const bool restrictAllocation
const unsigned initialLoopIter
const unsigned initialLoopAge
const bool optionalAgeReset
Stats::Scalar loopPredictorCorrect
Stats::Scalar loopPredictorWrong
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 46 of file loop_predictor.hh.
Constructor & Destructor Documentation
LoopPredictor()
LoopPredictor::LoopPredictor (LoopPredictorParams * p)
Definition at line 43 of file loop_predictor.cc.
References initialLoopAge, and loopTableAgeBits.
Referenced by getLoopUseCounter(), and getSizeInBits().
Member Function Documentation
calcConf()
bool LoopPredictor::calcConf (int index) const virtual
Reimplemented in TAGE_SC_L_LoopPredictor, and MPP_LoopPredictor.
Definition at line 151 of file loop_predictor.cc.
References LoopPredictor::LoopEntry::confidence, confidenceThreshold, MipsISA::index, and ltable.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), MPP_LoopPredictor::calcConf(), TAGE_SC_L_LoopPredictor::calcConf(), and getLoop().
condBranchUpdate()
void LoopPredictor::condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, bool tage_pred, BranchInfo * bi, unsigned instShiftAmt)
Update LTAGE for conditional branches.
Parameters
branch_pc The unshifted branch PC.
taken Actual branch outcome.
tage_pred Prediction from TAGE
bi Pointer to information on the prediction recorded at prediction time.
instShiftAmt Number of bits to shift instructions
Definition at line 326 of file loop_predictor.cc.
References getLoop(), LoopPredictor::BranchInfo::loopPred, LoopPredictor::BranchInfo::loopPredValid, loopUpdate(), loopUseCounter, LoopPredictor::BranchInfo::predTaken, signedCtrUpdate(), useSpeculation, and withLoopBits.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), LTAGE::update(), TAGE_SC_L::update(), and MultiperspectivePerceptronTAGE::update().
finallindex()
int LoopPredictor::finallindex (int lindex, int lowPcBits, int way) const
Computes the index used to access the ltable structures.
It may take hashing into account
Parameters
index Result of lindex function
lowPcBits PC bits masked with set size
way Way to be used
Definition at line 104 of file loop_predictor.cc.
References logLoopTableAssoc, and useHashing.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), getLoop(), loopUpdate(), specLoopUpdate(), squash(), and squashLoop().
getLoop()
bool LoopPredictor::getLoop (Addr pc, BranchInfo * bi, bool speculative, unsigned instShiftAmt) const
Get a branch prediction from the loop predictor.
Parameters
pc The unshifted branch PC.
bi Pointer to information on the prediction.
speculative Use speculative number of iterations
instShiftAmt Shift the pc by as many bits (if hashing is not used)
Returns
the result of the prediction, if it could be predicted
Definition at line 113 of file loop_predictor.cc.
References calcConf(), LoopPredictor::LoopEntry::currentIter, LoopPredictor::LoopEntry::currentIterSpec, LoopPredictor::LoopEntry::dir, finallindex(), ArmISA::i, lindex(), logLoopTableAssoc, logSizeLoopPred, LoopPredictor::BranchInfo::loopHit, LoopPredictor::BranchInfo::loopIndex, LoopPredictor::BranchInfo::loopIndexB, LoopPredictor::BranchInfo::loopPredValid, loopSetMask, loopTableTagBits, LoopPredictor::BranchInfo::loopTag, loopTagMask, ltable, useDirectionBit, and useHashing.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), condBranchUpdate(), and loopPredict().
getLoopUseCounter()
int8_t LoopPredictor::getLoopUseCounter () const inline
Gets the value of the loop use counter.
Returns
the loop use counter value
Definition at line 246 of file loop_predictor.hh.
References getSizeInBits(), init(), LoopPredictor(), loopUseCounter, MipsISA::p, and regStats().
Referenced by LTAGE::predict().
getSizeInBits()
size_t LoopPredictor::getSizeInBits () const
Definition at line 364 of file loop_predictor.cc.
References logSizeLoopPred, LoopPredictor(), loopTableAgeBits, loopTableConfidenceBits, loopTableIterBits, loopTableTagBits, ULL, useDirectionBit, and useSpeculation.
Referenced by getLoopUseCounter(), and MultiperspectivePerceptronTAGE::init().
init()
void LoopPredictor::init () override virtual
Initialize the loop predictor.
Reimplemented from SimObject.
Definition at line 68 of file loop_predictor.cc.
References logLoopTableAssoc, logSizeLoopPred, loopTableIterBits, loopTableTagBits, ltable, and ULL.
Referenced by getLoopUseCounter().
lindex()
int LoopPredictor::lindex (Addr pc_in, unsigned instShiftAmt) const
Computes the index used to access the loop predictor.
Parameters
pc_in The unshifted branch PC.
instShiftAmt Shift the pc by as many bits
Definition at line 87 of file loop_predictor.cc.
References logLoopTableAssoc, loopSetMask, MipsISA::pc, and useHashing.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), and getLoop().
loopPredict()
bool LoopPredictor::loopPredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo * bi, bool prev_pred_taken, unsigned instShiftAmt)
Get the loop prediction.
Parameters
tid The thread ID to select the global histories to use.
branch_pc The unshifted branch PC.
cond_branch True if the branch is conditional.
bi Reference to wrapping pointer to allow storing derived class prediction information in the base class.
prev_pred_taken Result of the TAGE prediction
instShiftAmt Shift the pc by as many bits
instShiftAmt Shift the pc by as many bits
Returns
the prediction, true if taken
Definition at line 272 of file loop_predictor.cc.
References getLoop(), LoopPredictor::BranchInfo::loopPred, LoopPredictor::BranchInfo::loopPredUsed, LoopPredictor::BranchInfo::loopPredValid, loopUseCounter, specLoopUpdate(), and useSpeculation.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), MultiperspectivePerceptronTAGE::lookup(), LTAGE::predict(), and TAGE_SC_L::predict().
loopUpdate()
void LoopPredictor::loopUpdate (Addr pc, bool Taken, BranchInfo * bi, bool tage_pred)
Updates the loop predictor.
Parameters
pc The unshifted branch PC.
taken The actual branch outcome.
bi Pointer to information on the prediction recorded at prediction time.
tage_pred tage prediction of the branch
Definition at line 177 of file loop_predictor.cc.
References LoopPredictor::LoopEntry::age, LoopPredictor::LoopEntry::confidence, LoopPredictor::LoopEntry::currentIter, LoopPredictor::LoopEntry::dir, DPRINTF, finallindex(), ArmISA::i, initialLoopAge, initialLoopIter, logLoopTableAssoc, LoopPredictor::BranchInfo::loopHit, LoopPredictor::BranchInfo::loopIndex, LoopPredictor::BranchInfo::loopIndexB, loopNumIterMask, LoopPredictor::BranchInfo::loopPred, LoopPredictor::BranchInfo::loopPredValid, loopTableAgeBits, loopTableConfidenceBits, LoopPredictor::BranchInfo::loopTag, ltable, LoopPredictor::LoopEntry::numIter, optionalAgeInc(), optionalAgeReset, LoopPredictor::BranchInfo::predTaken, Random::random(), random_mt, restrictAllocation, LoopPredictor::LoopEntry::tag, unsignedCtrUpdate(), and useDirectionBit.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), and condBranchUpdate().
makeBranchInfo()
LoopPredictor::BranchInfo * LoopPredictor::makeBranchInfo () virtual
Definition at line 81 of file loop_predictor.cc.
Referenced by LoopPredictor::BranchInfo::BranchInfo().
optionalAgeInc()
bool LoopPredictor::optionalAgeInc () const virtual
Reimplemented in TAGE_SC_L_LoopPredictor, and MPP_LoopPredictor.
Definition at line 171 of file loop_predictor.cc.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), and loopUpdate().
regStats()
void LoopPredictor::regStats () override virtual
Register stats for this object.
Reimplemented from Stats::Group.
Definition at line 350 of file loop_predictor.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), loopPredictorCorrect, loopPredictorWrong, SimObject::name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
Referenced by getLoopUseCounter().
signedCtrUpdate()
static void LoopPredictor::signedCtrUpdate (int8_t & ctr, bool up, unsigned nbits) inline static protected
Definition at line 111 of file loop_predictor.hh.
Referenced by condBranchUpdate().
specLoopUpdate()
void LoopPredictor::specLoopUpdate (bool taken, BranchInfo * bi)
Speculatively updates the loop predictor iteration count (only for useSpeculation).
Parameters
taken The predicted branch outcome.
bi Pointer to information on the prediction recorded at prediction time.
Definition at line 157 of file loop_predictor.cc.
References LoopPredictor::LoopEntry::currentIterSpec, finallindex(), MipsISA::index, LoopPredictor::BranchInfo::loopHit, LoopPredictor::BranchInfo::loopIndex, LoopPredictor::BranchInfo::loopIndexB, loopNumIterMask, and ltable.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), and loopPredict().
squash()
void LoopPredictor::squash (ThreadID tid, BranchInfo * bi)
Definition at line 294 of file loop_predictor.cc.
References LoopPredictor::BranchInfo::currentIter, LoopPredictor::LoopEntry::currentIterSpec, finallindex(), LoopPredictor::BranchInfo::loopHit, LoopPredictor::BranchInfo::loopIndex, LoopPredictor::BranchInfo::loopIndexB, and ltable.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), and LTAGE::squash().
squashLoop()
void LoopPredictor::squashLoop (BranchInfo * bi)
Definition at line 305 of file loop_predictor.cc.
References LoopPredictor::BranchInfo::currentIter, LoopPredictor::LoopEntry::currentIterSpec, finallindex(), LoopPredictor::BranchInfo::loopHit, LoopPredictor::BranchInfo::loopIndex, LoopPredictor::BranchInfo::loopIndexB, and ltable.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), LTAGE::update(), TAGE_SC_L::update(), and MultiperspectivePerceptronTAGE::update().
unsignedCtrUpdate()
static void LoopPredictor::unsignedCtrUpdate (uint8_t & ctr, bool up, unsigned nbits) inline static protected
Updates an unsigned counter based on up/down parameter.
Parameters
ctr Reference to counter to update.
up Boolean indicating if the counter is incremented/decremented If true it is incremented, if false it is decremented
nbits Counter width.
Definition at line 100 of file loop_predictor.hh.
Referenced by loopUpdate().
updateStats()
void LoopPredictor::updateStats (bool taken, BranchInfo * bi)
Update the stats.
Parameters
taken Actual branch outcome
bi Pointer to information on the prediction recorded at prediction time.
Definition at line 316 of file loop_predictor.cc.
References LoopPredictor::BranchInfo::loopPred, loopPredictorCorrect, and loopPredictorWrong.
Referenced by LoopPredictor::BranchInfo::BranchInfo(), LTAGE::update(), TAGE_SC_L::update(), and MultiperspectivePerceptronTAGE::update().
Member Data Documentation
confidenceThreshold
const uint8_t LoopPredictor::confidenceThreshold protected
Definition at line 55 of file loop_predictor.hh.
Referenced by calcConf().
initialLoopAge
const unsigned LoopPredictor::initialLoopAge protected
Definition at line 86 of file loop_predictor.hh.
Referenced by LoopPredictor(), and loopUpdate().
initialLoopIter
const unsigned LoopPredictor::initialLoopIter protected
Definition at line 85 of file loop_predictor.hh.
Referenced by loopUpdate().
logLoopTableAssoc
const unsigned LoopPredictor::logLoopTableAssoc protected
Definition at line 54 of file loop_predictor.hh.
Referenced by finallindex(), getLoop(), init(), lindex(), and loopUpdate().
logSizeLoopPred
const unsigned LoopPredictor::logSizeLoopPred protected
Definition at line 49 of file loop_predictor.hh.
Referenced by getLoop(), getSizeInBits(), and init().
loopNumIterMask
const uint16_t LoopPredictor::loopNumIterMask protected
Definition at line 57 of file loop_predictor.hh.
Referenced by loopUpdate(), and specLoopUpdate().
loopPredictorCorrect
Stats::Scalar LoopPredictor::loopPredictorCorrect protected
Definition at line 90 of file loop_predictor.hh.
Referenced by regStats(), and updateStats().
loopPredictorWrong
Stats::Scalar LoopPredictor::loopPredictorWrong protected
Definition at line 91 of file loop_predictor.hh.
Referenced by regStats(), and updateStats().
loopSetMask
const int LoopPredictor::loopSetMask protected
Definition at line 58 of file loop_predictor.hh.
Referenced by getLoop(), and lindex().
loopTableAgeBits
const unsigned LoopPredictor::loopTableAgeBits protected
Definition at line 50 of file loop_predictor.hh.
Referenced by getSizeInBits(), LoopPredictor(), and loopUpdate().
loopTableConfidenceBits
const unsigned LoopPredictor::loopTableConfidenceBits protected
Definition at line 51 of file loop_predictor.hh.
Referenced by getSizeInBits(), and loopUpdate().
loopTableIterBits
const unsigned LoopPredictor::loopTableIterBits protected
Definition at line 53 of file loop_predictor.hh.
Referenced by getSizeInBits(), and init().
loopTableTagBits
const unsigned LoopPredictor::loopTableTagBits protected
Definition at line 52 of file loop_predictor.hh.
Referenced by getLoop(), getSizeInBits(), and init().
loopTagMask
const uint16_t LoopPredictor::loopTagMask protected
Definition at line 56 of file loop_predictor.hh.
Referenced by getLoop().
loopUseCounter
int8_t LoopPredictor::loopUseCounter protected
Definition at line 78 of file loop_predictor.hh.
Referenced by condBranchUpdate(), getLoopUseCounter(), and loopPredict().
ltable
LoopEntry* LoopPredictor::ltable protected
Definition at line 76 of file loop_predictor.hh.
Referenced by TAGE_SC_L_LoopPredictor::calcConf(), calcConf(), getLoop(), init(), loopUpdate(), specLoopUpdate(), squash(), and squashLoop().
optionalAgeReset
const bool LoopPredictor::optionalAgeReset protected
Definition at line 87 of file loop_predictor.hh.
Referenced by loopUpdate().
restrictAllocation
const bool LoopPredictor::restrictAllocation protected
Definition at line 84 of file loop_predictor.hh.
Referenced by loopUpdate().
useDirectionBit
const bool LoopPredictor::useDirectionBit protected
Definition at line 81 of file loop_predictor.hh.
Referenced by getLoop(), getSizeInBits(), and loopUpdate().
useHashing
const bool LoopPredictor::useHashing protected
Definition at line 83 of file loop_predictor.hh.
Referenced by finallindex(), getLoop(), and lindex().
useSpeculation
const bool LoopPredictor::useSpeculation protected
Definition at line 82 of file loop_predictor.hh.
Referenced by condBranchUpdate(), getSizeInBits(), and loopPredict().
withLoopBits
unsigned LoopPredictor::withLoopBits protected
Definition at line 79 of file loop_predictor.hh.
Referenced by condBranchUpdate().
The documentation for this class was generated from the following files:
cpu/pred/loop_predictor.hh
cpu/pred/loop_predictor.cc