gem5: CxxIniFile Class Reference
CxxIniFile Class Reference
CxxConfigManager interface for using .ini files.
#include <cxx_config_ini.hh>
Public Member Functions
CxxIniFile ()
bool getParam (const std::string &object_name, const std::string &param_name, std::string &value) const
Get a single parameter value as a string returned in value.
bool getParamVector (const std::string &object_name, const std::string &param_name, std::vector< std::string > &values) const
Get a list/vector parameter.
bool getPortPeers (const std::string &object_name, const std::string &port_name, std::vector< std::string > &peers) const
Get the peer (connected) ports of the named ports.
bool objectExists (const std::string &object_name) const
Does an object with this path exist?
void getAllObjectNames (std::vector< std::string > &list) const
Get all SimObjects in the config.
void getObjectChildren (const std::string &object_name, std::vector< std::string > &children, bool return_paths=false) const
Get the names or paths of all the children SimObjects of this SimObject.
bool load (const std::string &filename)
Load config file.
Public Member Functions inherited from CxxConfigFileBase
CxxConfigFileBase ()
virtual ~CxxConfigFileBase ()
virtual CxxConfigParams::Flags getFlags () const
Get the flags which should be used to modify parameter parsing behaviour.
Protected Attributes
IniFile iniFile
Detailed Description
CxxConfigManager interface for using .ini files.
Definition at line 53 of file cxx_config_ini.hh.
Constructor & Destructor Documentation
CxxIniFile()
CxxIniFile::CxxIniFile () inline
Definition at line 59 of file cxx_config_ini.hh.
References getAllObjectNames(), getObjectChildren(), getParam(), getParamVector(), getPortPeers(), sc_dt::list, load(), and objectExists().
Member Function Documentation
getAllObjectNames()
void CxxIniFile::getAllObjectNames (std::vector< std::string > & list) const virtual
Get all SimObjects in the config.
Implements CxxConfigFileBase.
Definition at line 84 of file cxx_config_ini.cc.
References IniFile::getSectionNames(), and iniFile.
Referenced by CxxIniFile().
getObjectChildren()
void CxxIniFile::getObjectChildren (const std::string & object_name, std::vector< std::string > & children, bool return_paths = false) const virtual
Get the names or paths of all the children SimObjects of this SimObject.
If return_paths is true then full paths are returned. If false, only the last name component for each object is returned
Implements CxxConfigFileBase.
Definition at line 90 of file cxx_config_ini.cc.
References getParamVector(), and ArmISA::i.
Referenced by CxxIniFile().
getParam()
bool CxxIniFile::getParam (const std::string & object_name, const std::string & param_name, std::string & value) const virtual
Get a single parameter value as a string returned in value.
For booleans, the function expects "true" or "false" in value. For NULL SimObjects, it expects "Null"
Implements CxxConfigFileBase.
Definition at line 45 of file cxx_config_ini.cc.
References IniFile::find(), and iniFile.
Referenced by CxxIniFile().
getParamVector()
bool CxxIniFile::getParamVector (const std::string & object_name, const std::string & param_name, std::vector< std::string > & values) const virtual
Get a list/vector parameter.
Implements CxxConfigFileBase.
Definition at line 53 of file cxx_config_ini.cc.
References IniFile::find(), iniFile, and tokenize().
Referenced by CxxIniFile(), getObjectChildren(), and getPortPeers().
getPortPeers()
bool CxxIniFile::getPortPeers (const std::string & object_name, const std::string & port_name, std::vector< std::string > & peers) const virtual
Get the peer (connected) ports of the named ports.
Implements CxxConfigFileBase.
Definition at line 70 of file cxx_config_ini.cc.
References getParamVector().
Referenced by CxxIniFile().
load()
bool CxxIniFile::load (const std::string & filename) virtual
Load config file.
Implements CxxConfigFileBase.
Definition at line 103 of file cxx_config_ini.cc.
References iniFile, and IniFile::load().
Referenced by CxxIniFile().
objectExists()
bool CxxIniFile::objectExists (const std::string & object_name) const virtual
Does an object with this path exist?
Implements CxxConfigFileBase.
Definition at line 78 of file cxx_config_ini.cc.
References iniFile, and IniFile::sectionExists().
Referenced by CxxIniFile().
Member Data Documentation
iniFile
IniFile CxxIniFile::iniFile protected
Definition at line 56 of file cxx_config_ini.hh.
Referenced by getAllObjectNames(), getParam(), getParamVector(), load(), and objectExists().
The documentation for this class was generated from the following files:
sim/cxx_config_ini.hh
sim/cxx_config_ini.cc