gem5: sc_core::sc_time Class Reference
sc_core::sc_time Class Reference
#include <sc_time.hh>
Public Member Functions
sc_time ()
sc_time (double, sc_time_unit)
sc_time (const sc_time &)
sc_time (double, const char *)
sc_time (double, bool)
sc_time (sc_dt::uint64, bool)
sc_time & operator= (const sc_time &)
sc_dt::uint64 value () const
double to_double () const
double to_seconds () const
const std::string to_string () const
bool operator== (const sc_time &) const
bool operator!= (const sc_time &) const
bool operator< (const sc_time &) const
bool operator<= (const sc_time &) const
bool operator> (const sc_time &) const
bool operator>= (const sc_time &) const
sc_time & operator+= (const sc_time &)
sc_time & operator-= (const sc_time &)
sc_time & operator*= (double)
sc_time & operator/= (double)
void print (std::ostream &=std::cout) const
Static Public Member Functions
static sc_time from_value (sc_dt::uint64)
static sc_time from_seconds (double)
static sc_time from_string (const char *str)
Private Attributes
uint64_t val
Detailed Description
Definition at line 51 of file sc_time.hh.
Constructor & Destructor Documentation
sc_time() [1/6]
sc_core::sc_time::sc_time ()
Definition at line 66 of file sc_time.cc.
Referenced by from_string(), sc_core::sc_time_tuple::operator sc_time(), and sc_core::sc_get_default_time_unit().
sc_time() [2/6]
sc_core::sc_time::sc_time (double d, sc_time_unit tu)
Definition at line 68 of file sc_time.cc.
References ArmISA::d, MipsISA::tu, and val.
sc_time() [3/6]
sc_core::sc_time::sc_time (const sc_time & t)
Definition at line 74 of file sc_time.cc.
References val.
sc_time() [4/6]
sc_core::sc_time::sc_time (double d, const char * unit)
Definition at line 79 of file sc_time.cc.
References ArmISA::d, sc_core::SC_FS, sc_core::SC_ID_TIME_CONVERSION_FAILED_, SC_REPORT_ERROR, sc_core::SC_SEC, sc_gem5::TimeUnitConstantNames, sc_gem5::TimeUnitNames, MipsISA::tu, and val.
sc_time() [5/6]
sc_core::sc_time::sc_time (double d, bool scale)
Definition at line 97 of file sc_time.cc.
References SimClock::Float::Hz, and sc_core::SC_SEC.
sc_time() [6/6]
sc_core::sc_time::sc_time (sc_dt::uint64 v, bool scale)
Definition at line 103 of file sc_time.cc.
References SimClock::Float::Hz, sc_core::SC_SEC, and ArmISA::v.
Member Function Documentation
from_seconds()
sc_time sc_core::sc_time::from_seconds (double d) static
Definition at line 222 of file sc_time.cc.
References ArmISA::d, sc_core::SC_SEC, and ArmISA::t.
from_string()
sc_time sc_core::sc_time::from_string (const char * str) static
Definition at line 230 of file sc_time.cc.
References sc_core::SC_ID_TIME_CONVERSION_FAILED_, SC_REPORT_ERROR, sc_time(), and sc_core::SC_ZERO_TIME.
from_value()
sc_time sc_core::sc_time::from_value (sc_dt::uint64 u) static
Definition at line 212 of file sc_time.cc.
References fixClockFrequency(), ArmISA::t, ArmISA::u, and val.
Referenced by tlm::tlm_global_quantum::compute_local_quantum(), sc_gem5::VcdTraceFile::initialize(), sc_core::operator*(), sc_core::operator+(), sc_core::operator-(), sc_core::operator/(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp(), sc_core::sc_report_handler::report(), sc_core::sc_get_time_resolution(), sc_core::sc_max_time(), sc_core::sc_start(), sc_core::sc_time_stamp(), and sc_core::sc_time_to_pending_activity().
operator!=()
bool sc_core::sc_time::operator!= (const sc_time & t) const
Definition at line 148 of file sc_time.cc.
References val.
operator*=()
sc_time & sc_core::sc_time::operator*= (double d)
Definition at line 192 of file sc_time.cc.
References val.
operator+=()
sc_time & sc_core::sc_time::operator+= (const sc_time & t)
Definition at line 178 of file sc_time.cc.
References val.
operator-=()
sc_time & sc_core::sc_time::operator-= (const sc_time & t)
Definition at line 185 of file sc_time.cc.
References val.
operator/=()
sc_time & sc_core::sc_time::operator/= (double d)
Definition at line 199 of file sc_time.cc.
References val.
operator<()
bool sc_core::sc_time::operator< (const sc_time & t) const
Definition at line 154 of file sc_time.cc.
References val.
operator<=()
bool sc_core::sc_time::operator<= (const sc_time & t) const
Definition at line 160 of file sc_time.cc.
References val.
operator=()
sc_time & sc_core::sc_time::operator= (const sc_time & t)
Definition at line 110 of file sc_time.cc.
References val.
operator==()
bool sc_core::sc_time::operator== (const sc_time & t) const
Definition at line 142 of file sc_time.cc.
References val.
operator>()
bool sc_core::sc_time::operator> (const sc_time & t) const
Definition at line 166 of file sc_time.cc.
References val.
operator>=()
bool sc_core::sc_time::operator>= (const sc_time & t) const
Definition at line 172 of file sc_time.cc.
References val.
print()
void sc_core::sc_time::print (std::ostream & os = std::cout) const
Definition at line 206 of file sc_time.cc.
References sc_core::sc_time_tuple::to_string().
Referenced by sc_core::operator<<(), and to_string().
to_double()
double sc_core::sc_time::to_double () const
Definition at line 123 of file sc_time.cc.
References val.
Referenced by sc_core::sc_time_tuple::operator sc_time(), sc_core::operator/(), and to_seconds().
to_seconds()
double sc_core::sc_time::to_seconds () const
Definition at line 128 of file sc_time.cc.
References SimClock::Float::Hz, and to_double().
to_string()
const std::string sc_core::sc_time::to_string () const
Definition at line 134 of file sc_time.cc.
References print(), and ArmISA::ss.
Referenced by sc_core::sc_report_handler::default_handler(), sc_core::sc_time_tuple::operator sc_time(), and sc_core::sc_report_compose_message().
value()
sc_dt::uint64 sc_core::sc_time::value () const
Definition at line 117 of file sc_time.cc.
References val.
Referenced by tlm::tlm_global_quantum::compute_local_quantum(), sc_gem5::TraceFile::finalizeTime(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::nb_transport_bw(), Gem5SystemC::PayloadEvent< OWNER >::notify(), sc_core::operator*(), sc_core::operator+(), sc_core::operator-(), sc_core::operator/(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), sc_core::sc_start(), and sc_core::sc_time_tuple::sc_time_tuple().
Member Data Documentation
val
uint64_t sc_core::sc_time::val private
Definition at line 92 of file sc_time.hh.
Referenced by from_value(), operator!=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), sc_time(), to_double(), and value().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_time.hh
systemc/core/sc_time.cc