gem5: Stats::VectorBase< Derived, Stor > Class Template Reference
Stats::VectorBase< Derived, Stor > Class Template Reference
Implementation of a vector of stats.
#include <statistics.hh>
Public Types
typedef Stor Storage
typedef Stor::Params Params
typedef ScalarProxy< Derived > Proxy
Proxy type.
Public Types inherited from Stats::DataWrapVec< Derived, VectorInfoProxy >
typedef VectorInfoProxy< Derived > Info
Public Types inherited from Stats::DataWrap< Derived, VectorInfoProxy >
typedef VectorInfoProxy< Derived > Info
Public Member Functions
void value (VCounter &vec) const
void result (VResult &vec) const
Copy the values to a local vector and return a reference to it.
Result total () const
Return a total of all entries in this vector.
size_type size () const
bool zero () const
bool check () const
VectorBase (Group *parent, const char *name, const char *desc)
~VectorBase ()
Derived & init (size_type size)
Set this vector to have the given size.
Proxy operator[] (off_type index)
Return a reference (ScalarProxy) to the stat at the given index.
Public Member Functions inherited from Stats::DataWrapVec< Derived, VectorInfoProxy >
DataWrapVec (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
Derived & subname (off_type index, const std::string &name)
Set the subfield name for the given index, and marks this stat to print at the end of simulation.
Derived & subdesc (off_type index, const std::string &desc)
Set the subfield description for the given index and marks this stat to print at the end of simulation.
void prepare ()
void reset ()
Public Member Functions inherited from Stats::DataWrap< Derived, VectorInfoProxy >
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
DataWrap & operator= (const DataWrap &)=delete
Derived & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Derived & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Derived & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Derived & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Derived & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
Derived & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Member Functions
Storage * data (off_type index)
Retrieve the storage.
const Storage * data (off_type index) const
Retrieve a const pointer to the storage.
void doInit (size_type s)
Protected Member Functions inherited from Stats::DataWrap< Derived, VectorInfoProxy >
Derived & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Protected Attributes
Storage * storage
The storage of this stat.
size_type _size
Friends
class ScalarProxy< Derived >
class DataWrapVec< Derived, VectorInfoProxy >
Detailed Description
template<class Derived, class Stor>
class Stats::VectorBase< Derived, Stor >
Implementation of a vector of stats.
The type of stat is determined by the Storage class.
See also
ScalarBase
Definition at line 1029 of file statistics.hh.
Member Typedef Documentation
Params
template<class Derived, class Stor> typedef Stor::Params Stats::VectorBase< Derived, Stor >::Params
Definition at line 1033 of file statistics.hh.
Proxy
template<class Derived, class Stor> typedef ScalarProxy<Derived> Stats::VectorBase< Derived, Stor >::Proxy
Proxy type.
Definition at line 1036 of file statistics.hh.
Storage
template<class Derived, class Stor> typedef Stor Stats::VectorBase< Derived, Stor >::Storage
Definition at line 1032 of file statistics.hh.
Constructor & Destructor Documentation
VectorBase()
template<class Derived, class Stor> Stats::VectorBase< Derived, Stor >::VectorBase (Group * parent, const char * name, const char * desc) inline
Definition at line 1131 of file statistics.hh.
~VectorBase()
template<class Derived, class Stor> Stats::VectorBase< Derived, Stor >::~VectorBase () inline
Definition at line 1136 of file statistics.hh.
Member Function Documentation
check()
template<class Derived, class Stor> bool Stats::VectorBase< Derived, Stor >::check () const inline
Definition at line 1125 of file statistics.hh.
data() [1/2]
template<class Derived, class Stor> Storage* Stats::VectorBase< Derived, Stor >::data (off_type index) inline protected
Retrieve the storage.
Parameters
index The vector index to access.
Returns
The storage object at the given index.
Definition at line 1051 of file statistics.hh.
data() [2/2]
template<class Derived, class Stor> const Storage* Stats::VectorBase< Derived, Stor >::data (off_type index) const inline protected
Retrieve a const pointer to the storage.
Parameters
index The vector index to access.
Returns
A const pointer to the storage object at the given index.
Definition at line 1058 of file statistics.hh.
doInit()
template<class Derived, class Stor> void Stats::VectorBase< Derived, Stor >::doInit (size_type s) inline protected
Definition at line 1061 of file statistics.hh.
Referenced by Stats::VectorBase< Vector, StatStor >::init().
init()
template<class Derived, class Stor> Derived& Stats::VectorBase< Derived, Stor >::init (size_type size) inline
Set this vector to have the given size.
Parameters
size The new size.
Returns
A reference to this stat.
Definition at line 1152 of file statistics.hh.
Referenced by TAGEBase::regStats(), ExecStage::regStats(), BaseDictionaryCompressor::regStats(), GarnetNetwork::regStats(), BaseTags::BaseTagStats::regStats(), CacheMemory::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), InstructionQueue< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultIEW< Impl >::regStats(), DefaultCommit< Impl >::regStats(), BaseCacheCompressor::regStats(), AbstractMemory::MemStats::regStats(), FullO3CPU< O3CPUImpl >::regStats(), CopyEngine::regStats(), DRAMCtrl::RankStats::regStats(), ClockedObject::ClockedObjectStats::regStats(), ComputeUnit::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), and AlphaISA::Kernel::Statistics::Statistics().
operator[]()
template<class Derived, class Stor> Proxy Stats::VectorBase< Derived, Stor >::operator[] (off_type index) inline
Return a reference (ScalarProxy) to the stat at the given index.
Parameters
index The vector index to access.
Returns
A reference of the stat.
Definition at line 1165 of file statistics.hh.
result()
template<class Derived, class Stor> void Stats::VectorBase< Derived, Stor >::result (VResult & vec) const inline
Copy the values to a local vector and return a reference to it.
Returns
A reference to a vector of the stat values.
Definition at line 1090 of file statistics.hh.
size()
template<class Derived, class Stor> size_type Stats::VectorBase< Derived, Stor >::size () const inline
Returns
the number of elements in this vector.
Definition at line 1113 of file statistics.hh.
total()
template<class Derived, class Stor> Result Stats::VectorBase< Derived, Stor >::total () const inline
Return a total of all entries in this vector.
Returns
The total of all vector entries.
Definition at line 1102 of file statistics.hh.
Referenced by ClockedObject::pwrStateWeights().
value()
template<class Derived, class Stor> void Stats::VectorBase< Derived, Stor >::value (VCounter & vec) const inline
Definition at line 1078 of file statistics.hh.
Referenced by QoS::MemCtrl::logResponse(), and ClockedObject::pwrStateWeights().
zero()
template<class Derived, class Stor> bool Stats::VectorBase< Derived, Stor >::zero () const inline
Definition at line 1116 of file statistics.hh.
Friends And Related Function Documentation
DataWrapVec< Derived, VectorInfoProxy >
template<class Derived, class Stor> friend class DataWrapVec< Derived, VectorInfoProxy > friend
Definition at line 1038 of file statistics.hh.
ScalarProxy< Derived >
template<class Derived, class Stor> friend class ScalarProxy< Derived > friend
Definition at line 1037 of file statistics.hh.
Member Data Documentation
_size
template<class Derived, class Stor> size_type Stats::VectorBase< Derived, Stor >::_size protected
Definition at line 1043 of file statistics.hh.
storage
template<class Derived, class Stor> Storage* Stats::VectorBase< Derived, Stor >::storage protected
The storage of this stat.
Definition at line 1042 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh