gem5: mm Class Reference
mm Class Reference
#include <mm.h>
Classes
struct access
Public Member Functions
mm ()
virtual ~mm ()
gp_t * allocate ()
void free (gp_t *trans)
mm ()
virtual ~mm ()
gp_t * allocate ()
void free (gp_t *trans)
Public Member Functions inherited from tlm::tlm_mm_interface
virtual ~tlm_mm_interface ()
Private Types
typedef tlm::tlm_generic_payload gp_t
typedef tlm::tlm_generic_payload gp_t
Private Attributes
access * free_list
access * empties
Detailed Description
Definition at line 8 of file mm.h.
Member Typedef Documentation
gp_t [1/2]
typedef tlm::tlm_generic_payload mm::gp_t private
Definition at line 10 of file mm.h.
gp_t [2/2]
typedef tlm::tlm_generic_payload mm::gp_t private
Definition at line 10 of file mm.h.
Constructor & Destructor Documentation
mm() [1/2]
mm::mm () inline
Definition at line 13 of file mm.h.
~mm() [1/2]
virtual mm::~mm () inline virtual
Definition at line 15 of file mm.h.
References allocate(), empties, free(), free_list, mm::access::next, sc_assert, mm::access::trans, and X86ISA::x.
mm() [2/2]
mm::mm () inline
Definition at line 13 of file mm.h.
~mm() [2/2]
virtual mm::~mm () inline virtual
Definition at line 15 of file mm.h.
References allocate(), empties, free(), free_list, mm::access::next, mm::access::prev, tlm::tlm_generic_payload::reset(), sc_assert, mm::access::trans, and X86ISA::x.
Member Function Documentation
allocate() [1/2]
mm::gp_t * mm::allocate ()
Definition at line 55 of file mm.h.
References empties, free_list, mm::access::next, and mm::access::trans.
Referenced by ~mm().
allocate() [2/2]
gp_t* mm::allocate ()
free() [1/2]
void mm::free (gp_t * trans) virtual
Implements tlm::tlm_mm_interface.
free() [2/2]
void mm::free (gp_t * trans) virtual
Implements tlm::tlm_mm_interface.
Definition at line 71 of file mm.h.
References empties, free_list, mm::access::next, mm::access::prev, tlm::tlm_generic_payload::reset(), and mm::access::trans.
Referenced by ~mm().
Member Data Documentation
empties
access * mm::empties private
Definition at line 52 of file mm.h.
Referenced by allocate(), free(), and ~mm().
free_list
access * mm::free_list private
Definition at line 51 of file mm.h.
Referenced by allocate(), free(), and ~mm().
The documentation for this class was generated from the following file:
systemc/tests/tlm/nb2b_adapter/mm.h