gem5: Gicv3CPUInterface Class Reference
Gicv3CPUInterface Class Reference abstract
#include <gic_v3_cpu_interface.hh>
Classes
struct hppi_t
Public Member Functions
Gicv3CPUInterface (Gicv3 *gic, uint32_t cpu_id)
void init ()
RegVal readMiscReg (int misc_reg) override
Read a system register belonging to this device.
void setMiscReg (int misc_reg, RegVal val) override
Write to a system register belonging to this device.
void setThreadContext (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::BaseISADevice
BaseISADevice ()
virtual ~BaseISADevice ()
virtual void setISA (ISA *isa)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Types
enum {
GICC_CTLR = 0x0000, GICC_PMR = 0x0004, GICC_BPR = 0x0008, GICC_IAR = 0x000C,
GICC_EOIR = 0x0010, GICC_RPR = 0x0014, GICC_HPPI = 0x0018, GICC_ABPR = 0x001C,
GICC_AIAR = 0x0020, GICC_AEOIR = 0x0024, GICC_AHPPIR = 0x0028, GICC_STATUSR = 0x002C,
GICC_IIDR = 0x00FC
}
enum {
GICH_HCR = 0x0000, GICH_VTR = 0x0004, GICH_VMCR = 0x0008, GICH_MISR = 0x0010,
GICH_EISR = 0x0020, GICH_ELRSR = 0x0030
}
Protected Member Functions
BitUnion64 (ICC_CTLR_EL1) Bitfield< 63
EndBitUnion (ICC_CTLR_EL1) BitUnion64(ICC_CTLR_EL3) Bitfield< 63
EndBitUnion (ICC_CTLR_EL3) BitUnion64(ICC_IGRPEN0_EL1) Bitfield< 63
EndBitUnion (ICC_IGRPEN0_EL1) BitUnion64(ICC_IGRPEN1_EL1) Bitfield< 63
EndBitUnion (ICC_IGRPEN1_EL1) BitUnion64(ICC_IGRPEN1_EL3) Bitfield< 63
EndBitUnion (ICC_IGRPEN1_EL3) BitUnion64(ICC_SRE_EL1) Bitfield< 63
EndBitUnion (ICC_SRE_EL1) BitUnion64(ICC_SRE_EL2) Bitfield< 63
EndBitUnion (ICC_SRE_EL2) BitUnion64(ICC_SRE_EL3) Bitfield< 63
EndBitUnion (ICC_SRE_EL3) static const uint8_t PRIORITY_BITS
BitUnion64 (ICH_HCR_EL2) Bitfield< 63
EndBitUnion (ICH_HCR_EL2) BitUnion64(ICH_LR_EL2) Bitfield< 63
EndBitUnion (ICH_LR_EL2) static const uint64_t ICH_LR_EL2_STATE_INVALID=0
BitUnion32 (ICH_LRC) Bitfield< 31
EndBitUnion (ICH_LRC) BitUnion64(ICH_MISR_EL2) Bitfield< 63
EndBitUnion (ICH_MISR_EL2) BitUnion64(ICH_VMCR_EL2) Bitfield< 63
EndBitUnion (ICH_VMCR_EL2) BitUnion64(ICH_VTR_EL2) Bitfield< 63
EndBitUnion (ICH_VTR_EL2) BitUnion64(ICV_CTLR_EL1) Bitfield< 63
EndBitUnion(ICV_CTLR_EL1) protected void generateSGI (RegVal val, Gicv3::GroupId group)
int currEL () const
void deactivateIRQ (uint32_t intid, Gicv3::GroupId group)
void dropPriority (Gicv3::GroupId group)
uint64_t eoiMaintenanceInterruptStatus () const
bool getHCREL2FMO () const
bool getHCREL2IMO () const
uint32_t getHPPIR0 () const
uint32_t getHPPIR1 () const
int getHPPVILR () const
bool groupEnabled (Gicv3::GroupId group) const
uint32_t groupPriorityMask (Gicv3::GroupId group)
bool haveEL (ArmISA::ExceptionLevel el) const
int highestActiveGroup () const
uint8_t highestActivePriority () const
bool hppiCanPreempt ()
bool hppviCanPreempt (int lrIdx) const
bool inSecureState () const
ArmISA::InterruptTypes intSignalType (Gicv3::GroupId group) const
bool isAA64 () const
bool isEL3OrMon () const
bool isEOISplitMode () const
bool isSecureBelowEL3 () const
ICH_MISR_EL2 maintenanceInterruptStatus () const
void resetHppi (uint32_t intid)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void update ()
void updateDistributor ()
void virtualActivateIRQ (uint32_t lrIdx)
void virtualDeactivateIRQ (int lrIdx)
uint8_t virtualDropPriority ()
int virtualFindActive (uint32_t intid) const
uint32_t virtualGroupPriorityMask (Gicv3::GroupId group) const
uint8_t virtualHighestActivePriority () const
void virtualIncrementEOICount ()
bool virtualIsEOISplitMode () const
void virtualUpdate ()
RegVal bpr1 (Gicv3::GroupId group)
RegVal readBankedMiscReg (MiscRegIndex misc_reg) const
void setBankedMiscReg (MiscRegIndex misc_reg, RegVal val) const
Protected Attributes
Gicv3 * gic
Gicv3Redistributor * redistributor
Gicv3Distributor * distributor
uint32_t cpuId
ArmInterruptPin * maintenanceInterrupt
res0_3
Bitfield< 19 > ExtRange
Bitfield< 18 > RSS
Bitfield< 17, 16 > res0_2
Bitfield< 15 > A3V
Bitfield< 14 > SEIS
Bitfield< 13, 11 > IDbits
Bitfield< 10, 8 > PRIbits
Bitfield< 7 > res0_1
Bitfield< 6 > PMHE
Bitfield< 5, 2 > res0_0
Bitfield< 1 > EOImode
Bitfield< 0 > CBPR
res0_2
Bitfield< 17 > nDS
Bitfield< 16 > res0_1
Bitfield< 7 > res0_0
Bitfield< 5 > RM
Bitfield< 4 > EOImode_EL1NS
Bitfield< 3 > EOImode_EL1S
Bitfield< 2 > EOImode_EL3
Bitfield< 1 > CBPR_EL1NS
Bitfield< 0 > CBPR_EL1S
res0
Bitfield< 0 > Enable
Bitfield< 1 > EnableGrp1S
Bitfield< 0 > EnableGrp1NS
Bitfield< 2 > DIB
Bitfield< 1 > DFB
Bitfield< 0 > SRE
Bitfield< 3 > Enable
hppi_t hppi
Bitfield< 31, 27 > EOIcount
Bitfield< 26, 15 > res0_1
Bitfield< 14 > TDIR
Bitfield< 13 > TSEI
Bitfield< 12 > TALL1
Bitfield< 11 > TALL0
Bitfield< 10 > TC
Bitfield< 9, 8 > res0_0
Bitfield< 7 > VGrp1DIE
Bitfield< 6 > VGrp1EIE
Bitfield< 5 > VGrp0DIE
Bitfield< 4 > VGrp0EIE
Bitfield< 3 > NPIE
Bitfield< 2 > LRENPIE
Bitfield< 1 > UIE
Bitfield< 0 > En
State
Bitfield< 61 > HW
Bitfield< 60 > Group
Bitfield< 59, 56 > res0_1
Bitfield< 55, 48 > Priority
Bitfield< 47, 45 > res0_0
Bitfield< 44, 32 > pINTID
Bitfield< 41 > EOI
Bitfield< 31, 0 > vINTID
Bitfield< 29 > HW
Bitfield< 28 > Group
Bitfield< 27, 24 > res0_1
Bitfield< 23, 16 > Priority
Bitfield< 15, 13 > res0_0
Bitfield< 12, 0 > pINTID
Bitfield< 9 > EOI
Bitfield< 7 > VGrp1D
Bitfield< 6 > VGrp1E
Bitfield< 5 > VGrp0D
Bitfield< 4 > VGrp0E
Bitfield< 3 > NP
Bitfield< 2 > LRENP
Bitfield< 1 > U
Bitfield< 0 > EOI
Bitfield< 31, 24 > VPMR
Bitfield< 23, 21 > VBPR0
Bitfield< 20, 18 > VBPR1
Bitfield< 17, 10 > res0_1
Bitfield< 9 > VEOIM
Bitfield< 8, 5 > res0_0
Bitfield< 4 > VCBPR
Bitfield< 3 > VFIQEn
Bitfield< 2 > VAckCtl
Bitfield< 1 > VENG1
Bitfield< 0 > VENG0
res0_1
Bitfield< 31, 29 > PRIbits
Bitfield< 28, 26 > PREbits
Bitfield< 25, 23 > IDbits
Bitfield< 22 > SEIS
Bitfield< 21 > A3V
Bitfield< 20 > res1
Bitfield< 19 > TDS
Bitfield< 18, 5 > res0_0
Bitfield< 4, 0 > ListRegs
Bitfield< 17, 16 > res0_1
Bitfield< 7, 2 > res0_0
Protected Attributes inherited from ArmISA::BaseISADevice
ISA * isa
Static Protected Attributes
static const uint8_t GIC_MIN_BPR = 2
static const uint8_t GIC_MIN_BPR_NS = GIC_MIN_BPR + 1
static const uint8_t VIRTUAL_PRIORITY_BITS = 5
static const uint8_t VIRTUAL_PREEMPTION_BITS = 5
static const uint8_t VIRTUAL_NUM_LIST_REGS = 16
static const uint8_t GIC_MIN_VBPR = 7 - VIRTUAL_PREEMPTION_BITS
static const AddrRange GICC_APR
static const AddrRange GICC_NSAPR
static const AddrRange GICH_APR
static const AddrRange GICH_LR
static const uint64_t ICH_LR_EL2_STATE_PENDING = 1
static const uint64_t ICH_LR_EL2_STATE_ACTIVE = 2
static const uint64_t ICH_LR_EL2_STATE_ACTIVE_PENDING = 3
Friends
class Gicv3Distributor
class Gicv3Redistributor
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 52 of file gic_v3_cpu_interface.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GICC_CTLR
GICC_PMR
GICC_BPR
GICC_IAR
GICC_EOIR
GICC_RPR
GICC_HPPI
GICC_ABPR
GICC_AIAR
GICC_AEOIR
GICC_AHPPIR
GICC_STATUSR
GICC_IIDR
Definition at line 165 of file gic_v3_cpu_interface.hh.
anonymous enum
anonymous enum protected
Enumerator
GICH_HCR
GICH_VTR
GICH_VMCR
GICH_MISR
GICH_EISR
GICH_ELRSR
Definition at line 185 of file gic_v3_cpu_interface.hh.
Constructor & Destructor Documentation
Gicv3CPUInterface()
Gicv3CPUInterface::Gicv3CPUInterface (Gicv3 * gic, uint32_t cpu_id)
Definition at line 54 of file gic_v3_cpu_interface.cc.
References hppi, Gicv3CPUInterface::hppi_t::intid, Gicv3::INTID_SPURIOUS, and Gicv3CPUInterface::hppi_t::prio.
Member Function Documentation
BitUnion32()
Gicv3CPUInterface::BitUnion32 (ICH_LRC) protected
BitUnion64() [1/2]
Gicv3CPUInterface::BitUnion64 (ICC_CTLR_EL1) protected
BitUnion64() [2/2]
Gicv3CPUInterface::BitUnion64 (ICH_HCR_EL2) protected
bpr1()
RegVal Gicv3CPUInterface::bpr1 (Gicv3::GroupId group) protected
Definition at line 2535 of file gic_v3_cpu_interface.cc.
References currEL(), ArmISA::EL1, ArmISA::EL3, Gicv3::G1NS, Gicv3::G1S, getHCREL2IMO(), GIC_MIN_BPR, GIC_MIN_BPR_NS, haveEL(), inSecureState(), ArmISA::BaseISADevice::isa, isEL3OrMon(), ArmISA::MISCREG_ICC_BPR0_EL1, ArmISA::MISCREG_ICC_BPR1_EL1_NS, ArmISA::MISCREG_ICC_BPR1_EL1_S, ArmISA::MISCREG_ICC_CTLR_EL1_NS, ArmISA::MISCREG_ICC_CTLR_EL1_S, ArmISA::MISCREG_ICV_BPR1_EL1, panic, readMiscReg(), and ArmISA::ISA::readMiscRegNoEffect().
Referenced by groupPriorityMask(), and readMiscReg().
currEL()
int Gicv3CPUInterface::currEL () const protected
Definition at line 2337 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_CPSR, ArmISA::MODE_HYP, ArmISA::MODE_MON, ArmISA::MODE_USER, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by bpr1(), getHPPIR1(), intSignalType(), readMiscReg(), and setMiscReg().
deactivateIRQ()
void Gicv3CPUInterface::deactivateIRQ (uint32_t intid, Gicv3::GroupId group) protected
Definition at line 1879 of file gic_v3_cpu_interface.cc.
References Gicv3Distributor::deactivateIRQ(), Gicv3Redistributor::deactivateIRQ(), distributor, Gicv3::INTID_SECURE, Gicv3::PPI_MAX, redistributor, Gicv3::SGI_MAX, and updateDistributor().
Referenced by setMiscReg(), and virtualDeactivateIRQ().
dropPriority()
void Gicv3CPUInterface::dropPriority (Gicv3::GroupId group) protected
Definition at line 1709 of file gic_v3_cpu_interface.cc.
References Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP1R0_EL1_NS, ArmISA::MISCREG_ICC_AP1R0_EL1_S, panic, ArmISA::ISA::readMiscRegNoEffect(), ArmISA::ISA::setMiscRegNoEffect(), and update().
Referenced by setMiscReg().
EndBitUnion() [1/14]
Gicv3CPUInterface::EndBitUnion (ICC_CTLR_EL1) protected
EndBitUnion() [2/14]
Gicv3CPUInterface::EndBitUnion (ICC_CTLR_EL3) protected
EndBitUnion() [3/14]
Gicv3CPUInterface::EndBitUnion (ICC_IGRPEN0_EL1) protected
EndBitUnion() [4/14]
Gicv3CPUInterface::EndBitUnion (ICC_IGRPEN1_EL1) protected
EndBitUnion() [5/14]
Gicv3CPUInterface::EndBitUnion (ICC_IGRPEN1_EL3) protected
EndBitUnion() [6/14]
Gicv3CPUInterface::EndBitUnion (ICC_SRE_EL1) protected
EndBitUnion() [7/14]
Gicv3CPUInterface::EndBitUnion (ICC_SRE_EL2) protected
EndBitUnion() [8/14]
Gicv3CPUInterface::EndBitUnion (ICC_SRE_EL3) const protected
EndBitUnion() [9/14]
Gicv3CPUInterface::EndBitUnion (ICH_HCR_EL2) protected
EndBitUnion() [10/14]
Gicv3CPUInterface::EndBitUnion (ICH_LR_EL2) const protected pure virtual
EndBitUnion() [11/14]
Gicv3CPUInterface::EndBitUnion (ICH_LRC) protected
EndBitUnion() [12/14]
Gicv3CPUInterface::EndBitUnion (ICH_MISR_EL2) protected
EndBitUnion() [13/14]
Gicv3CPUInterface::EndBitUnion (ICH_VMCR_EL2) protected
EndBitUnion() [14/14]
Gicv3CPUInterface::EndBitUnion (ICH_VTR_EL2) protected
eoiMaintenanceInterruptStatus()
uint64_t Gicv3CPUInterface::eoiMaintenanceInterruptStatus () const protected
Definition at line 2414 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::ISA::readMiscRegNoEffect(), and VIRTUAL_NUM_LIST_REGS.
Referenced by maintenanceInterruptStatus(), and readMiscReg().
generateSGI()
void Gicv3CPUInterface::generateSGI (RegVal val, Gicv3::GroupId group) protected
Definition at line 1768 of file gic_v3_cpu_interface.cc.
References Gicv3Distributor::activateIRQ(), Gicv3Redistributor::activateIRQ(), bits(), distributor, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, Gicv3Redistributor::getAffinity(), Gicv3::getRedistributor(), BaseGic::getSystem(), gic, hppi, ArmISA::i, inSecureState(), Gicv3::INTID_SECURE, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP1R0_EL1_NS, ArmISA::MISCREG_ICC_AP1R0_EL1_S, ArmISA::ns, System::numContexts(), panic, Gicv3::PPI_MAX, Gicv3CPUInterface::hppi_t::prio, ArmISA::ISA::readMiscRegNoEffect(), redistributor, resetHppi(), ArmISA::rs, Gicv3Redistributor::sendSGI(), Gicv3Redistributor::setClrLPI(), ArmISA::ISA::setMiscRegNoEffect(), Gicv3::SGI_MAX, Gicv3Redistributor::SMALLEST_LPI_ID, and updateDistributor().
Referenced by setMiscReg().
getHCREL2FMO()
bool Gicv3CPUInterface::getHCREL2FMO () const protected
Definition at line 86 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_HCR_EL2, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readMiscReg(), and setMiscReg().
getHCREL2IMO()
bool Gicv3CPUInterface::getHCREL2IMO () const protected
Definition at line 100 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_HCR_EL2, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by bpr1(), readMiscReg(), and setMiscReg().
getHPPIR0()
uint32_t Gicv3CPUInterface::getHPPIR0 () const protected
Definition at line 1648 of file gic_v3_cpu_interface.cc.
References distributor, Gicv3Distributor::DS, Gicv3::G0S, Gicv3::G1NS, Gicv3CPUInterface::hppi_t::group, groupEnabled(), hppi, inSecureState(), Gicv3CPUInterface::hppi_t::intid, Gicv3::INTID_NONSECURE, Gicv3::INTID_SECURE, Gicv3::INTID_SPURIOUS, isEL3OrMon(), and Gicv3CPUInterface::hppi_t::prio.
Referenced by readMiscReg().
getHPPIR1()
uint32_t Gicv3CPUInterface::getHPPIR1 () const protected
Definition at line 1674 of file gic_v3_cpu_interface.cc.
References currEL(), distributor, Gicv3Distributor::DS, ArmISA::EL3, Gicv3::G0S, Gicv3::G1NS, Gicv3CPUInterface::hppi_t::group, groupEnabled(), hppi, inSecureState(), Gicv3CPUInterface::hppi_t::intid, Gicv3::INTID_NONSECURE, Gicv3::INTID_SECURE, Gicv3::INTID_SPURIOUS, ArmISA::BaseISADevice::isa, isEL3OrMon(), ArmISA::MISCREG_ICC_CTLR_EL3, Gicv3CPUInterface::hppi_t::prio, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readMiscReg().
getHPPVILR()
int Gicv3CPUInterface::getHPPVILR () const protected
Definition at line 2107 of file gic_v3_cpu_interface.cc.
References ArmISA::i, Gicv3::INT_PENDING, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::MISCREG_ICH_VMCR_EL2, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readMiscReg(), and virtualUpdate().
groupEnabled()
bool Gicv3CPUInterface::groupEnabled (Gicv3::GroupId group) const protected
Definition at line 2298 of file gic_v3_cpu_interface.cc.
References distributor, Gicv3Distributor::EnableGrp0, Gicv3Distributor::EnableGrp1NS, Gicv3Distributor::EnableGrp1S, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_IGRPEN0_EL1, ArmISA::MISCREG_ICC_IGRPEN1_EL1_NS, ArmISA::MISCREG_ICC_IGRPEN1_EL1_S, panic, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by getHPPIR0(), getHPPIR1(), and hppiCanPreempt().
groupPriorityMask()
uint32_t Gicv3CPUInterface::groupPriorityMask (Gicv3::GroupId group) protected
Definition at line 1918 of file gic_v3_cpu_interface.cc.
References bpr1(), Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_BPR0_EL1, ArmISA::MISCREG_ICC_CTLR_EL1_NS, ArmISA::MISCREG_ICC_CTLR_EL1_S, readMiscReg(), ArmISA::ISA::readMiscRegNoEffect(), and U.
Referenced by hppiCanPreempt().
haveEL()
bool Gicv3CPUInterface::haveEL (ArmISA::ExceptionLevel el) const protected
Definition at line 2362 of file gic_v3_cpu_interface.cc.
References ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, BaseGic::getSystem(), gic, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), and warn.
Referenced by bpr1(), isEL3OrMon(), isSecureBelowEL3(), readMiscReg(), setMiscReg(), and update().
highestActiveGroup()
int Gicv3CPUInterface::highestActiveGroup () const protected
Definition at line 1999 of file gic_v3_cpu_interface.cc.
References ctz32(), Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP1R0_EL1_NS, ArmISA::MISCREG_ICC_AP1R0_EL1_S, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by setMiscReg().
highestActivePriority()
uint8_t Gicv3CPUInterface::highestActivePriority () const protected
Definition at line 2283 of file gic_v3_cpu_interface.cc.
References ctz32(), GIC_MIN_BPR, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP1R0_EL1_NS, ArmISA::MISCREG_ICC_AP1R0_EL1_S, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by hppiCanPreempt(), and readMiscReg().
hppiCanPreempt()
bool Gicv3CPUInterface::hppiCanPreempt () protected
Definition at line 2250 of file gic_v3_cpu_interface.cc.
References Gicv3CPUInterface::hppi_t::group, groupEnabled(), groupPriorityMask(), highestActivePriority(), hppi, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICC_PMR_EL1, Gicv3CPUInterface::hppi_t::prio, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readMiscReg(), and update().
hppviCanPreempt()
bool Gicv3CPUInterface::hppviCanPreempt (int lrIdx) const protected
Definition at line 2151 of file gic_v3_cpu_interface.cc.
References bits(), Gicv3::G0S, Gicv3::G1NS, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::MISCREG_ICH_VMCR_EL2, ArmISA::ISA::readMiscRegNoEffect(), virtualGroupPriorityMask(), and virtualHighestActivePriority().
Referenced by readMiscReg(), and virtualUpdate().
init()
void Gicv3CPUInterface::init ()
Definition at line 66 of file gic_v3_cpu_interface.cc.
References cpuId, distributor, Gicv3::getDistributor(), Gicv3::getRedistributor(), gic, and redistributor.
inSecureState()
bool Gicv3CPUInterface::inSecureState () const protected
Definition at line 2325 of file gic_v3_cpu_interface.cc.
References BaseGic::getSystem(), gic, ArmSystem::haveSecurity(), ArmISA::inSecureState(), ArmISA::BaseISADevice::isa, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_SCR, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by bpr1(), generateSGI(), getHPPIR0(), getHPPIR1(), intSignalType(), isEOISplitMode(), readMiscReg(), and setMiscReg().
intSignalType()
ArmISA::InterruptTypes Gicv3CPUInterface::intSignalType (Gicv3::GroupId group) const protected
Definition at line 2220 of file gic_v3_cpu_interface.cc.
References currEL(), distributor, Gicv3Distributor::DS, ArmISA::EL3, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, inSecureState(), ArmISA::INT_FIQ, ArmISA::INT_IRQ, isAA64(), and panic.
Referenced by update().
isAA64()
bool Gicv3CPUInterface::isAA64 () const protected
Definition at line 2389 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_CPSR, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by intSignalType().
isEL3OrMon()
bool Gicv3CPUInterface::isEL3OrMon () const protected
Definition at line 2396 of file gic_v3_cpu_interface.cc.
References ArmISA::EL3, haveEL(), ArmISA::BaseISADevice::isa, ArmISA::MISCREG_CPSR, ArmISA::MODE_MON, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by bpr1(), getHPPIR0(), getHPPIR1(), isEOISplitMode(), and setMiscReg().
isEOISplitMode()
bool Gicv3CPUInterface::isEOISplitMode () const protected
Definition at line 1975 of file gic_v3_cpu_interface.cc.
References inSecureState(), ArmISA::BaseISADevice::isa, isEL3OrMon(), ArmISA::MISCREG_ICC_CTLR_EL1_NS, ArmISA::MISCREG_ICC_CTLR_EL1_S, ArmISA::MISCREG_ICC_CTLR_EL3, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by setMiscReg().
isSecureBelowEL3()
bool Gicv3CPUInterface::isSecureBelowEL3 () const protected
Definition at line 2382 of file gic_v3_cpu_interface.cc.
References ArmISA::EL3, haveEL(), ArmISA::BaseISADevice::isa, ArmISA::MISCREG_SCR_EL3, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readBankedMiscReg(), readMiscReg(), setBankedMiscReg(), and setMiscReg().
maintenanceInterruptStatus()
Gicv3CPUInterface::ICH_MISR_EL2 Gicv3CPUInterface::maintenanceInterruptStatus () const protected
Definition at line 2447 of file gic_v3_cpu_interface.cc.
References eoiMaintenanceInterruptStatus(), ICH_LR_EL2_STATE_PENDING, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::MISCREG_ICH_VMCR_EL2, ArmISA::ISA::readMiscRegNoEffect(), and VIRTUAL_NUM_LIST_REGS.
Referenced by readMiscReg(), and virtualUpdate().
readBankedMiscReg()
RegVal Gicv3CPUInterface::readBankedMiscReg (MiscRegIndex misc_reg) const protected
Definition at line 1617 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, isSecureBelowEL3(), ArmISA::ISA::readMiscRegNoEffect(), and ArmISA::ISA::snsBankedIndex64().
Referenced by readMiscReg(), and setMiscReg().
readMiscReg()
RegVal Gicv3CPUInterface::readMiscReg (int misc_reg) override virtual
Read a system register belonging to this device.
Parameters
misc_reg Register number (see miscregs.hh)
Returns
Register value.
Implements ArmISA::BaseISADevice.
Definition at line 114 of file gic_v3_cpu_interface.cc.
References Gicv3Redistributor::activateIRQ(), bpr1(), currEL(), DPRINTF, ArmISA::EL1, ArmISA::EL3, Enable, eoiMaintenanceInterruptStatus(), Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, getHCREL2FMO(), getHCREL2IMO(), getHPPIR0(), getHPPIR1(), getHPPVILR(), Gicv3CPUInterface::hppi_t::group, haveEL(), highestActivePriority(), hppi, hppiCanPreempt(), hppviCanPreempt(), inSecureState(), Gicv3::INTID_SECURE, Gicv3::INTID_SPURIOUS, ArmISA::BaseISADevice::isa, isSecureBelowEL3(), maintenanceInterruptStatus(), ArmISA::MISCREG_ICC_AP0R0, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP0R1, ArmISA::MISCREG_ICC_AP0R1_EL1, ArmISA::MISCREG_ICC_AP0R2, ArmISA::MISCREG_ICC_AP0R2_EL1, ArmISA::MISCREG_ICC_AP0R3, ArmISA::MISCREG_ICC_AP0R3_EL1, ArmISA::MISCREG_ICC_AP1R0, ArmISA::MISCREG_ICC_AP1R0_EL1, ArmISA::MISCREG_ICC_AP1R1, ArmISA::MISCREG_ICC_AP1R1_EL1, ArmISA::MISCREG_ICC_AP1R2, ArmISA::MISCREG_ICC_AP1R2_EL1, ArmISA::MISCREG_ICC_AP1R3, ArmISA::MISCREG_ICC_AP1R3_EL1, ArmISA::MISCREG_ICC_BPR0, ArmISA::MISCREG_ICC_BPR0_EL1, ArmISA::MISCREG_ICC_BPR1, ArmISA::MISCREG_ICC_BPR1_EL1, ArmISA::MISCREG_ICC_CTLR, ArmISA::MISCREG_ICC_CTLR_EL1, ArmISA::MISCREG_ICC_CTLR_EL3, ArmISA::MISCREG_ICC_HPPIR0, ArmISA::MISCREG_ICC_HPPIR0_EL1, ArmISA::MISCREG_ICC_HPPIR1, ArmISA::MISCREG_ICC_HPPIR1_EL1, ArmISA::MISCREG_ICC_HSRE, ArmISA::MISCREG_ICC_IAR0, ArmISA::MISCREG_ICC_IAR0_EL1, ArmISA::MISCREG_ICC_IAR1, ArmISA::MISCREG_ICC_IAR1_EL1, ArmISA::MISCREG_ICC_IGRPEN0, ArmISA::MISCREG_ICC_IGRPEN0_EL1, ArmISA::MISCREG_ICC_IGRPEN1, ArmISA::MISCREG_ICC_IGRPEN1_EL1, ArmISA::MISCREG_ICC_IGRPEN1_EL1_NS, ArmISA::MISCREG_ICC_IGRPEN1_EL1_S, ArmISA::MISCREG_ICC_IGRPEN1_EL3, ArmISA::MISCREG_ICC_MCTLR, ArmISA::MISCREG_ICC_MGRPEN1, ArmISA::MISCREG_ICC_MSRE, ArmISA::MISCREG_ICC_PMR, ArmISA::MISCREG_ICC_PMR_EL1, ArmISA::MISCREG_ICC_RPR, ArmISA::MISCREG_ICC_RPR_EL1, ArmISA::MISCREG_ICC_SRE, ArmISA::MISCREG_ICC_SRE_EL1, ArmISA::MISCREG_ICC_SRE_EL2, ArmISA::MISCREG_ICC_SRE_EL3, ArmISA::MISCREG_ICH_AP0R0, ArmISA::MISCREG_ICH_AP0R0_EL2, ArmISA::MISCREG_ICH_AP0R1, ArmISA::MISCREG_ICH_AP0R1_EL2, ArmISA::MISCREG_ICH_AP0R2, ArmISA::MISCREG_ICH_AP0R2_EL2, ArmISA::MISCREG_ICH_AP0R3, ArmISA::MISCREG_ICH_AP0R3_EL2, ArmISA::MISCREG_ICH_AP1R0, ArmISA::MISCREG_ICH_AP1R0_EL2, ArmISA::MISCREG_ICH_AP1R1, ArmISA::MISCREG_ICH_AP1R1_EL2, ArmISA::MISCREG_ICH_AP1R2, ArmISA::MISCREG_ICH_AP1R2_EL2, ArmISA::MISCREG_ICH_AP1R3, ArmISA::MISCREG_ICH_AP1R3_EL2, ArmISA::MISCREG_ICH_EISR, ArmISA::MISCREG_ICH_EISR_EL2, ArmISA::MISCREG_ICH_ELRSR, ArmISA::MISCREG_ICH_ELRSR_EL2, ArmISA::MISCREG_ICH_HCR, ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::MISCREG_ICH_LR0, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::MISCREG_ICH_LR15, ArmISA::MISCREG_ICH_LR15_EL2, ArmISA::MISCREG_ICH_LRC0, ArmISA::MISCREG_ICH_LRC15, ArmISA::MISCREG_ICH_MISR, ArmISA::MISCREG_ICH_MISR_EL2, ArmISA::MISCREG_ICH_VMCR, ArmISA::MISCREG_ICH_VMCR_EL2, ArmISA::MISCREG_ICH_VTR, ArmISA::MISCREG_ICH_VTR_EL2, ArmISA::MISCREG_ICV_AP0R0_EL1, ArmISA::MISCREG_ICV_AP1R0_EL1, ArmISA::MISCREG_ICV_BPR0_EL1, ArmISA::MISCREG_ICV_BPR1_EL1, ArmISA::MISCREG_ICV_CTLR_EL1, ArmISA::MISCREG_ICV_HPPIR0_EL1, ArmISA::MISCREG_ICV_HPPIR1_EL1, ArmISA::MISCREG_ICV_IAR0_EL1, ArmISA::MISCREG_ICV_IAR1_EL1, ArmISA::MISCREG_ICV_IGRPEN0_EL1, ArmISA::MISCREG_ICV_IGRPEN1_EL1, ArmISA::MISCREG_ICV_PMR_EL1, ArmISA::MISCREG_ICV_RPR_EL1, ArmISA::MISCREG_SCR_EL3, ArmISA::miscRegName, panic, readBankedMiscReg(), ArmISA::ISA::readMiscRegNoEffect(), ArmISA::ISA::setMiscRegNoEffect(), Gicv3Redistributor::SMALLEST_LPI_ID, U, VIRTUAL_NUM_LIST_REGS, VIRTUAL_PREEMPTION_BITS, VIRTUAL_PRIORITY_BITS, virtualActivateIRQ(), virtualHighestActivePriority(), and virtualUpdate().
Referenced by bpr1(), and groupPriorityMask().
resetHppi()
void Gicv3CPUInterface::resetHppi (uint32_t intid) protected
Definition at line 73 of file gic_v3_cpu_interface.cc.
References hppi, Gicv3CPUInterface::hppi_t::intid, and Gicv3CPUInterface::hppi_t::prio.
Referenced by generateSGI(), and Gicv3Redistributor::setClrLPI().
serialize()
void Gicv3CPUInterface::serialize (CheckpointOut & cp) const override protected virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2576 of file gic_v3_cpu_interface.cc.
References Gicv3CPUInterface::hppi_t::group, hppi, Gicv3CPUInterface::hppi_t::intid, Gicv3CPUInterface::hppi_t::prio, SERIALIZE_ENUM, and SERIALIZE_SCALAR.
setBankedMiscReg()
void Gicv3CPUInterface::setBankedMiscReg (MiscRegIndex misc_reg, RegVal val) const protected
Definition at line 1624 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, isSecureBelowEL3(), ArmISA::ISA::setMiscRegNoEffect(), ArmISA::ISA::snsBankedIndex64(), and X86ISA::val.
Referenced by setMiscReg().
setMiscReg()
void Gicv3CPUInterface::setMiscReg (int misc_reg, RegVal val) override virtual
Write to a system register belonging to this device.
Parameters
misc_reg Register number (see miscregs.hh)
val Value to store
Implements ArmISA::BaseISADevice.
Definition at line 734 of file gic_v3_cpu_interface.cc.
References currEL(), deactivateIRQ(), distributor, DPRINTF, dropPriority(), Gicv3Distributor::DS, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, X86ISA::enable, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, generateSGI(), getHCREL2FMO(), getHCREL2IMO(), Gicv3Distributor::getIntGroup(), Gicv3Redistributor::getIntGroup(), GIC_MIN_BPR, GIC_MIN_BPR_NS, haveEL(), highestActiveGroup(), inSecureState(), Gicv3::INTID_SECURE, Gicv3::INTID_SPURIOUS, ArmISA::BaseISADevice::isa, isEL3OrMon(), isEOISplitMode(), isSecureBelowEL3(), ArmISA::MISCREG_ICC_AP0R0, ArmISA::MISCREG_ICC_AP0R0_EL1, ArmISA::MISCREG_ICC_AP0R1, ArmISA::MISCREG_ICC_AP0R1_EL1, ArmISA::MISCREG_ICC_AP0R2, ArmISA::MISCREG_ICC_AP0R2_EL1, ArmISA::MISCREG_ICC_AP0R3, ArmISA::MISCREG_ICC_AP0R3_EL1, ArmISA::MISCREG_ICC_AP1R0, ArmISA::MISCREG_ICC_AP1R0_EL1, ArmISA::MISCREG_ICC_AP1R1, ArmISA::MISCREG_ICC_AP1R1_EL1, ArmISA::MISCREG_ICC_AP1R2, ArmISA::MISCREG_ICC_AP1R2_EL1, ArmISA::MISCREG_ICC_AP1R3, ArmISA::MISCREG_ICC_AP1R3_EL1, ArmISA::MISCREG_ICC_ASGI1R, ArmISA::MISCREG_ICC_ASGI1R_EL1, ArmISA::MISCREG_ICC_BPR0, ArmISA::MISCREG_ICC_BPR0_EL1, ArmISA::MISCREG_ICC_BPR1, ArmISA::MISCREG_ICC_BPR1_EL1, ArmISA::MISCREG_ICC_BPR1_EL1_NS, ArmISA::MISCREG_ICC_BPR1_EL1_S, ArmISA::MISCREG_ICC_CTLR, ArmISA::MISCREG_ICC_CTLR_EL1, ArmISA::MISCREG_ICC_CTLR_EL1_NS, ArmISA::MISCREG_ICC_CTLR_EL1_S, ArmISA::MISCREG_ICC_CTLR_EL3, ArmISA::MISCREG_ICC_DIR, ArmISA::MISCREG_ICC_DIR_EL1, ArmISA::MISCREG_ICC_EOIR0, ArmISA::MISCREG_ICC_EOIR0_EL1, ArmISA::MISCREG_ICC_EOIR1, ArmISA::MISCREG_ICC_EOIR1_EL1, ArmISA::MISCREG_ICC_HSRE, ArmISA::MISCREG_ICC_IGRPEN0, ArmISA::MISCREG_ICC_IGRPEN0_EL1, ArmISA::MISCREG_ICC_IGRPEN1, ArmISA::MISCREG_ICC_IGRPEN1_EL1, ArmISA::MISCREG_ICC_IGRPEN1_EL1_NS, ArmISA::MISCREG_ICC_IGRPEN1_EL1_S, ArmISA::MISCREG_ICC_IGRPEN1_EL3, ArmISA::MISCREG_ICC_MCTLR, ArmISA::MISCREG_ICC_MGRPEN1, ArmISA::MISCREG_ICC_MSRE, ArmISA::MISCREG_ICC_PMR, ArmISA::MISCREG_ICC_PMR_EL1, ArmISA::MISCREG_ICC_SGI0R, ArmISA::MISCREG_ICC_SGI0R_EL1, ArmISA::MISCREG_ICC_SGI1R, ArmISA::MISCREG_ICC_SGI1R_EL1, ArmISA::MISCREG_ICC_SRE, ArmISA::MISCREG_ICC_SRE_EL1, ArmISA::MISCREG_ICC_SRE_EL2, ArmISA::MISCREG_ICC_SRE_EL3, ArmISA::MISCREG_ICH_AP0R0, ArmISA::MISCREG_ICH_AP0R0_EL2, ArmISA::MISCREG_ICH_AP0R1, ArmISA::MISCREG_ICH_AP0R1_EL2, ArmISA::MISCREG_ICH_AP0R2, ArmISA::MISCREG_ICH_AP0R2_EL2, ArmISA::MISCREG_ICH_AP0R3, ArmISA::MISCREG_ICH_AP0R3_EL2, ArmISA::MISCREG_ICH_AP1R0, ArmISA::MISCREG_ICH_AP1R0_EL2, ArmISA::MISCREG_ICH_AP1R1, ArmISA::MISCREG_ICH_AP1R1_EL2, ArmISA::MISCREG_ICH_AP1R2, ArmISA::MISCREG_ICH_AP1R2_EL2, ArmISA::MISCREG_ICH_AP1R3, ArmISA::MISCREG_ICH_AP1R3_EL2, ArmISA::MISCREG_ICH_HCR, ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::MISCREG_ICH_LR0, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::MISCREG_ICH_LR15, ArmISA::MISCREG_ICH_LR15_EL2, ArmISA::MISCREG_ICH_LRC0, ArmISA::MISCREG_ICH_LRC15, ArmISA::MISCREG_ICH_VMCR, ArmISA::MISCREG_ICH_VMCR_EL2, ArmISA::MISCREG_ICV_AP0R0_EL1, ArmISA::MISCREG_ICV_AP1R0_EL1, ArmISA::MISCREG_ICV_BPR0_EL1, ArmISA::MISCREG_ICV_BPR1_EL1, ArmISA::MISCREG_ICV_CTLR_EL1, ArmISA::MISCREG_ICV_DIR_EL1, ArmISA::MISCREG_ICV_EOIR0_EL1, ArmISA::MISCREG_ICV_EOIR1_EL1, ArmISA::MISCREG_ICV_IGRPEN0_EL1, ArmISA::MISCREG_ICV_IGRPEN1_EL1, ArmISA::MISCREG_ICV_PMR_EL1, ArmISA::MISCREG_SCR_EL3, ArmISA::miscRegName, panic, readBankedMiscReg(), ArmISA::ISA::readMiscRegNoEffect(), redistributor, setBankedMiscReg(), ArmISA::ISA::setMiscRegNoEffect(), U, updateDistributor(), X86ISA::val, VIRTUAL_PREEMPTION_BITS, virtualDeactivateIRQ(), virtualDropPriority(), virtualFindActive(), virtualIncrementEOICount(), virtualIsEOISplitMode(), and virtualUpdate().
setThreadContext()
void Gicv3CPUInterface::setThreadContext (ThreadContext * tc) override virtual
Reimplemented from ArmISA::BaseISADevice.
Definition at line 80 of file gic_v3_cpu_interface.cc.
References gic, maintenanceInterrupt, and Gicv3::params().
unserialize()
void Gicv3CPUInterface::unserialize (CheckpointIn & cp) override protected virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2584 of file gic_v3_cpu_interface.cc.
References Gicv3CPUInterface::hppi_t::group, hppi, Gicv3CPUInterface::hppi_t::intid, Gicv3CPUInterface::hppi_t::prio, UNSERIALIZE_ENUM, and UNSERIALIZE_SCALAR.
update()
void Gicv3CPUInterface::update () protected
Definition at line 2027 of file gic_v3_cpu_interface.cc.
References cpuId, Gicv3::deassertInt(), DPRINTF, ArmISA::EL3, Gicv3::G0S, Gicv3::G1S, gic, Gicv3CPUInterface::hppi_t::group, haveEL(), hppi, hppiCanPreempt(), ArmISA::INT_FIQ, ArmISA::INT_IRQ, intSignalType(), and Gicv3::postInt().
Referenced by dropPriority(), and Gicv3Redistributor::update().
updateDistributor()
void Gicv3CPUInterface::updateDistributor () protected
Definition at line 2021 of file gic_v3_cpu_interface.cc.
References distributor, and Gicv3Distributor::update().
Referenced by deactivateIRQ(), generateSGI(), and setMiscReg().
virtualActivateIRQ()
void Gicv3CPUInterface::virtualActivateIRQ (uint32_t lrIdx) protected
Definition at line 1858 of file gic_v3_cpu_interface.cc.
References Gicv3::G0S, Gicv3::G1NS, ICH_LR_EL2_STATE_ACTIVE, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_AP0R0_EL2, ArmISA::MISCREG_ICH_AP1R0_EL2, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::ISA::readMiscRegNoEffect(), ArmISA::ISA::setMiscRegNoEffect(), and VIRTUAL_PREEMPTION_BITS.
Referenced by readMiscReg().
virtualDeactivateIRQ()
void Gicv3CPUInterface::virtualDeactivateIRQ (int lrIdx) protected
Definition at line 1893 of file gic_v3_cpu_interface.cc.
References deactivateIRQ(), distributor, Gicv3Distributor::getIntGroup(), Gicv3Redistributor::getIntGroup(), ICH_LR_EL2_STATE_ACTIVE, Gicv3::INTID_SECURE, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::ISA::readMiscRegNoEffect(), redistributor, and ArmISA::ISA::setMiscRegNoEffect().
Referenced by setMiscReg().
virtualDropPriority()
uint8_t Gicv3CPUInterface::virtualDropPriority () protected
Definition at line 1738 of file gic_v3_cpu_interface.cc.
References ctz32(), GIC_MIN_VBPR, ArmISA::i, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_AP0R0_EL2, ArmISA::MISCREG_ICH_AP1R0_EL2, ArmISA::ISA::readMiscRegNoEffect(), ArmISA::ISA::setMiscRegNoEffect(), and VIRTUAL_PREEMPTION_BITS.
Referenced by setMiscReg().
virtualFindActive()
int Gicv3CPUInterface::virtualFindActive (uint32_t intid) const protected
Definition at line 1631 of file gic_v3_cpu_interface.cc.
References ICH_LR_EL2_STATE_ACTIVE, ICH_LR_EL2_STATE_ACTIVE_PENDING, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_LR0_EL2, ArmISA::ISA::readMiscRegNoEffect(), and VIRTUAL_NUM_LIST_REGS.
Referenced by setMiscReg().
virtualGroupPriorityMask()
uint32_t Gicv3CPUInterface::virtualGroupPriorityMask (Gicv3::GroupId group) const protected
Definition at line 1949 of file gic_v3_cpu_interface.cc.
References Gicv3::G0S, Gicv3::G1NS, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_VMCR_EL2, ArmISA::ISA::readMiscRegNoEffect(), and U.
Referenced by hppviCanPreempt().
virtualHighestActivePriority()
uint8_t Gicv3CPUInterface::virtualHighestActivePriority () const protected
Definition at line 2187 of file gic_v3_cpu_interface.cc.
References ctz32(), GIC_MIN_VBPR, ArmISA::i, ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_AP0R0_EL2, ArmISA::MISCREG_ICH_AP1R0_EL2, ArmISA::ISA::readMiscRegNoEffect(), and VIRTUAL_PRIORITY_BITS.
Referenced by hppviCanPreempt(), and readMiscReg().
virtualIncrementEOICount()
void Gicv3CPUInterface::virtualIncrementEOICount () protected
Definition at line 2208 of file gic_v3_cpu_interface.cc.
References bits(), insertBits(), ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::ISA::readMiscRegNoEffect(), and ArmISA::ISA::setMiscRegNoEffect().
Referenced by setMiscReg().
virtualIsEOISplitMode()
bool Gicv3CPUInterface::virtualIsEOISplitMode () const protected
Definition at line 1992 of file gic_v3_cpu_interface.cc.
References ArmISA::BaseISADevice::isa, ArmISA::MISCREG_ICH_VMCR_EL2, and ArmISA::ISA::readMiscRegNoEffect().
Referenced by setMiscReg().
virtualUpdate()
void Gicv3CPUInterface::virtualUpdate () protected
Definition at line 2061 of file gic_v3_cpu_interface.cc.
References cpuId, Gicv3::deassertInt(), DPRINTF, getHPPVILR(), gic, hppviCanPreempt(), ArmISA::INT_VIRT_FIQ, ArmISA::INT_VIRT_IRQ, ArmISA::BaseISADevice::isa, maintenanceInterrupt, maintenanceInterruptStatus(), ArmISA::MISCREG_ICH_HCR_EL2, ArmISA::MISCREG_ICH_LR0_EL2, Gicv3::postInt(), ArmInterruptPin::raise(), and ArmISA::ISA::readMiscRegNoEffect().
Referenced by readMiscReg(), and setMiscReg().
Friends And Related Function Documentation
Gicv3Distributor
friend class Gicv3Distributor friend
Definition at line 56 of file gic_v3_cpu_interface.hh.
Gicv3Redistributor
friend class Gicv3Redistributor friend
Definition at line 57 of file gic_v3_cpu_interface.hh.
Member Data Documentation
A3V [1/2]
Bitfield< 15 > Gicv3CPUInterface::A3V protected
Definition at line 73 of file gic_v3_cpu_interface.hh.
A3V [2/2]
Bitfield<21> Gicv3CPUInterface::A3V protected
Definition at line 278 of file gic_v3_cpu_interface.hh.
CBPR
Bitfield< 0 > Gicv3CPUInterface::CBPR protected
Definition at line 81 of file gic_v3_cpu_interface.hh.
CBPR_EL1NS
Bitfield<1> Gicv3CPUInterface::CBPR_EL1NS protected
Definition at line 100 of file gic_v3_cpu_interface.hh.
CBPR_EL1S
Bitfield<0> Gicv3CPUInterface::CBPR_EL1S protected
Definition at line 101 of file gic_v3_cpu_interface.hh.
cpuId
uint32_t Gicv3CPUInterface::cpuId protected
Definition at line 64 of file gic_v3_cpu_interface.hh.
Referenced by init(), update(), and virtualUpdate().
DFB
Bitfield< 1 > Gicv3CPUInterface::DFB protected
Definition at line 123 of file gic_v3_cpu_interface.hh.
DIB
Bitfield< 2 > Gicv3CPUInterface::DIB protected
Definition at line 122 of file gic_v3_cpu_interface.hh.
distributor
Gicv3Distributor* Gicv3CPUInterface::distributor protected
Definition at line 63 of file gic_v3_cpu_interface.hh.
Referenced by deactivateIRQ(), generateSGI(), getHPPIR0(), getHPPIR1(), groupEnabled(), init(), intSignalType(), setMiscReg(), updateDistributor(), and virtualDeactivateIRQ().
En
Bitfield<0> Gicv3CPUInterface::En protected
Definition at line 214 of file gic_v3_cpu_interface.hh.
Enable [1/2]
Bitfield< 3 > Gicv3CPUInterface::Enable protected
Definition at line 106 of file gic_v3_cpu_interface.hh.
Referenced by readMiscReg().
Enable [2/2]
Bitfield<3> Gicv3CPUInterface::Enable protected
Definition at line 129 of file gic_v3_cpu_interface.hh.
EnableGrp1NS
Bitfield<0> Gicv3CPUInterface::EnableGrp1NS protected
Definition at line 117 of file gic_v3_cpu_interface.hh.
EnableGrp1S
Bitfield<1> Gicv3CPUInterface::EnableGrp1S protected
Definition at line 116 of file gic_v3_cpu_interface.hh.
EOI [1/3]
Bitfield<41> Gicv3CPUInterface::EOI protected
Definition at line 225 of file gic_v3_cpu_interface.hh.
EOI [2/3]
Bitfield<9> Gicv3CPUInterface::EOI protected
Definition at line 242 of file gic_v3_cpu_interface.hh.
EOI [3/3]
Bitfield<0> Gicv3CPUInterface::EOI protected
Definition at line 254 of file gic_v3_cpu_interface.hh.
EOIcount
Bitfield<31, 27> Gicv3CPUInterface::EOIcount protected
Definition at line 199 of file gic_v3_cpu_interface.hh.
EOImode
Bitfield< 1 > Gicv3CPUInterface::EOImode protected
Definition at line 80 of file gic_v3_cpu_interface.hh.
EOImode_EL1NS
Bitfield<4> Gicv3CPUInterface::EOImode_EL1NS protected
Definition at line 97 of file gic_v3_cpu_interface.hh.
EOImode_EL1S
Bitfield<3> Gicv3CPUInterface::EOImode_EL1S protected
Definition at line 98 of file gic_v3_cpu_interface.hh.
EOImode_EL3
Bitfield<2> Gicv3CPUInterface::EOImode_EL3 protected
Definition at line 99 of file gic_v3_cpu_interface.hh.
ExtRange
Bitfield< 19 > Gicv3CPUInterface::ExtRange protected
Definition at line 70 of file gic_v3_cpu_interface.hh.
gic
Gicv3* Gicv3CPUInterface::gic protected
Definition at line 61 of file gic_v3_cpu_interface.hh.
Referenced by generateSGI(), haveEL(), init(), inSecureState(), setThreadContext(), update(), and virtualUpdate().
GIC_MIN_BPR
const uint8_t Gicv3CPUInterface::GIC_MIN_BPR = 2 static protected
Definition at line 146 of file gic_v3_cpu_interface.hh.
Referenced by bpr1(), highestActivePriority(), and setMiscReg().
GIC_MIN_BPR_NS
const uint8_t Gicv3CPUInterface::GIC_MIN_BPR_NS = GIC_MIN_BPR + 1 static protected
Definition at line 148 of file gic_v3_cpu_interface.hh.
Referenced by bpr1(), and setMiscReg().
GIC_MIN_VBPR
const uint8_t Gicv3CPUInterface::GIC_MIN_VBPR = 7 - VIRTUAL_PREEMPTION_BITS static protected
Definition at line 154 of file gic_v3_cpu_interface.hh.
Referenced by virtualDropPriority(), and virtualHighestActivePriority().
GICC_APR
const AddrRange Gicv3CPUInterface::GICC_APR static protected
Definition at line 181 of file gic_v3_cpu_interface.hh.
GICC_NSAPR
const AddrRange Gicv3CPUInterface::GICC_NSAPR static protected
Definition at line 182 of file gic_v3_cpu_interface.hh.
GICH_APR
const AddrRange Gicv3CPUInterface::GICH_APR static protected
Definition at line 194 of file gic_v3_cpu_interface.hh.
GICH_LR
const AddrRange Gicv3CPUInterface::GICH_LR static protected
Definition at line 195 of file gic_v3_cpu_interface.hh.
Group [1/2]
Bitfield<60> Gicv3CPUInterface::Group protected
Definition at line 220 of file gic_v3_cpu_interface.hh.
Group [2/2]
Bitfield<28> Gicv3CPUInterface::Group protected
Definition at line 237 of file gic_v3_cpu_interface.hh.
hppi
hppi_t Gicv3CPUInterface::hppi protected
Definition at line 162 of file gic_v3_cpu_interface.hh.
Referenced by generateSGI(), getHPPIR0(), getHPPIR1(), Gicv3CPUInterface(), hppiCanPreempt(), readMiscReg(), resetHppi(), serialize(), unserialize(), Gicv3Redistributor::update(), Gicv3Distributor::update(), and update().
HW [1/2]
Bitfield<61> Gicv3CPUInterface::HW protected
Definition at line 219 of file gic_v3_cpu_interface.hh.
HW [2/2]
Bitfield<29> Gicv3CPUInterface::HW protected
Definition at line 236 of file gic_v3_cpu_interface.hh.
ICH_LR_EL2_STATE_ACTIVE
const uint64_t Gicv3CPUInterface::ICH_LR_EL2_STATE_ACTIVE = 2 static protected
Definition at line 231 of file gic_v3_cpu_interface.hh.
Referenced by virtualActivateIRQ(), virtualDeactivateIRQ(), and virtualFindActive().
ICH_LR_EL2_STATE_ACTIVE_PENDING
const uint64_t Gicv3CPUInterface::ICH_LR_EL2_STATE_ACTIVE_PENDING = 3 static protected
Definition at line 232 of file gic_v3_cpu_interface.hh.
Referenced by virtualFindActive().
ICH_LR_EL2_STATE_PENDING
const uint64_t Gicv3CPUInterface::ICH_LR_EL2_STATE_PENDING = 1 static protected
Definition at line 230 of file gic_v3_cpu_interface.hh.
Referenced by maintenanceInterruptStatus().
IDbits [1/2]
Bitfield< 13, 11 > Gicv3CPUInterface::IDbits protected
Definition at line 75 of file gic_v3_cpu_interface.hh.
IDbits [2/2]
Bitfield<25, 23> Gicv3CPUInterface::IDbits protected
Definition at line 276 of file gic_v3_cpu_interface.hh.
ListRegs
Bitfield<4, 0> Gicv3CPUInterface::ListRegs protected
Definition at line 282 of file gic_v3_cpu_interface.hh.
LRENP
Bitfield<2> Gicv3CPUInterface::LRENP protected
Definition at line 252 of file gic_v3_cpu_interface.hh.
LRENPIE
Bitfield<2> Gicv3CPUInterface::LRENPIE protected
Definition at line 212 of file gic_v3_cpu_interface.hh.
maintenanceInterrupt
ArmInterruptPin* Gicv3CPUInterface::maintenanceInterrupt protected
Definition at line 66 of file gic_v3_cpu_interface.hh.
Referenced by setThreadContext(), and virtualUpdate().
nDS
Bitfield<17> Gicv3CPUInterface::nDS protected
Definition at line 88 of file gic_v3_cpu_interface.hh.
NP
Bitfield<3> Gicv3CPUInterface::NP protected
Definition at line 251 of file gic_v3_cpu_interface.hh.
NPIE
Bitfield<3> Gicv3CPUInterface::NPIE protected
Definition at line 211 of file gic_v3_cpu_interface.hh.
pINTID [1/2]
Bitfield<44, 32> Gicv3CPUInterface::pINTID protected
Definition at line 224 of file gic_v3_cpu_interface.hh.
pINTID [2/2]
Bitfield<12, 0> Gicv3CPUInterface::pINTID protected
Definition at line 241 of file gic_v3_cpu_interface.hh.
PMHE
Bitfield< 6 > Gicv3CPUInterface::PMHE protected
Definition at line 78 of file gic_v3_cpu_interface.hh.
PREbits
Bitfield<28, 26> Gicv3CPUInterface::PREbits protected
Definition at line 275 of file gic_v3_cpu_interface.hh.
PRIbits [1/2]
Bitfield< 10, 8 > Gicv3CPUInterface::PRIbits protected
Definition at line 76 of file gic_v3_cpu_interface.hh.
PRIbits [2/2]
Bitfield<31, 29> Gicv3CPUInterface::PRIbits protected
Definition at line 274 of file gic_v3_cpu_interface.hh.
Priority [1/2]
Bitfield<55, 48> Gicv3CPUInterface::Priority protected
Definition at line 222 of file gic_v3_cpu_interface.hh.
Priority [2/2]
Bitfield<23, 16> Gicv3CPUInterface::Priority protected
Definition at line 239 of file gic_v3_cpu_interface.hh.
redistributor
Gicv3Redistributor* Gicv3CPUInterface::redistributor protected
Definition at line 62 of file gic_v3_cpu_interface.hh.
Referenced by deactivateIRQ(), generateSGI(), init(), setMiscReg(), and virtualDeactivateIRQ().
res0
Gicv3CPUInterface::res0 protected
Definition at line 105 of file gic_v3_cpu_interface.hh.
res0_0 [1/8]
Bitfield<5, 2> Gicv3CPUInterface::res0_0 protected
Definition at line 79 of file gic_v3_cpu_interface.hh.
res0_0 [2/8]
Bitfield<7> Gicv3CPUInterface::res0_0 protected
Definition at line 94 of file gic_v3_cpu_interface.hh.
res0_0 [3/8]
Bitfield<9, 8> Gicv3CPUInterface::res0_0 protected
Definition at line 206 of file gic_v3_cpu_interface.hh.
res0_0 [4/8]
Bitfield<47, 45> Gicv3CPUInterface::res0_0 protected
Definition at line 223 of file gic_v3_cpu_interface.hh.
res0_0 [5/8]
Bitfield<15, 13> Gicv3CPUInterface::res0_0 protected
Definition at line 240 of file gic_v3_cpu_interface.hh.
res0_0 [6/8]
Bitfield<8, 5> Gicv3CPUInterface::res0_0 protected
Definition at line 264 of file gic_v3_cpu_interface.hh.
res0_0 [7/8]
Bitfield<18, 5> Gicv3CPUInterface::res0_0 protected
Definition at line 281 of file gic_v3_cpu_interface.hh.
res0_0 [8/8]
Bitfield<7, 2> Gicv3CPUInterface::res0_0 protected
Definition at line 293 of file gic_v3_cpu_interface.hh.
res0_1 [1/8]
Bitfield<7> Gicv3CPUInterface::res0_1 protected
Definition at line 77 of file gic_v3_cpu_interface.hh.
res0_1 [2/8]
Bitfield<16> Gicv3CPUInterface::res0_1 protected
Definition at line 89 of file gic_v3_cpu_interface.hh.
res0_1 [3/8]
Bitfield<26, 15> Gicv3CPUInterface::res0_1 protected
Definition at line 200 of file gic_v3_cpu_interface.hh.
res0_1 [4/8]
Bitfield<59, 56> Gicv3CPUInterface::res0_1 protected
Definition at line 221 of file gic_v3_cpu_interface.hh.
res0_1 [5/8]
Bitfield<27, 24> Gicv3CPUInterface::res0_1 protected
Definition at line 238 of file gic_v3_cpu_interface.hh.
res0_1 [6/8]
Bitfield<17, 10> Gicv3CPUInterface::res0_1 protected
Definition at line 262 of file gic_v3_cpu_interface.hh.
res0_1 [7/8]
Gicv3CPUInterface::res0_1 protected
Definition at line 273 of file gic_v3_cpu_interface.hh.
res0_1 [8/8]
Bitfield<17, 16> Gicv3CPUInterface::res0_1 protected
Definition at line 288 of file gic_v3_cpu_interface.hh.
res0_2 [1/2]
Bitfield<17, 16> Gicv3CPUInterface::res0_2 protected
Definition at line 72 of file gic_v3_cpu_interface.hh.
res0_2 [2/2]
Gicv3CPUInterface::res0_2 protected
Definition at line 85 of file gic_v3_cpu_interface.hh.
res0_3
Gicv3CPUInterface::res0_3 protected
Definition at line 69 of file gic_v3_cpu_interface.hh.
res1
Bitfield<20> Gicv3CPUInterface::res1 protected
Definition at line 279 of file gic_v3_cpu_interface.hh.
RM
Bitfield<5> Gicv3CPUInterface::RM protected
Definition at line 96 of file gic_v3_cpu_interface.hh.
RSS
Bitfield< 18 > Gicv3CPUInterface::RSS protected
Definition at line 71 of file gic_v3_cpu_interface.hh.
SEIS [1/2]
Bitfield< 14 > Gicv3CPUInterface::SEIS protected
Definition at line 74 of file gic_v3_cpu_interface.hh.
SEIS [2/2]
Bitfield<22> Gicv3CPUInterface::SEIS protected
Definition at line 277 of file gic_v3_cpu_interface.hh.
SRE
Bitfield< 0 > Gicv3CPUInterface::SRE protected
Definition at line 124 of file gic_v3_cpu_interface.hh.
State
Gicv3CPUInterface::State protected
Definition at line 218 of file gic_v3_cpu_interface.hh.
TALL0
Bitfield<11> Gicv3CPUInterface::TALL0 protected
Definition at line 204 of file gic_v3_cpu_interface.hh.
TALL1
Bitfield<12> Gicv3CPUInterface::TALL1 protected
Definition at line 203 of file gic_v3_cpu_interface.hh.
TC
Bitfield<10> Gicv3CPUInterface::TC protected
Definition at line 205 of file gic_v3_cpu_interface.hh.
TDIR
Bitfield<14> Gicv3CPUInterface::TDIR protected
Definition at line 201 of file gic_v3_cpu_interface.hh.
TDS
Bitfield<19> Gicv3CPUInterface::TDS protected
Definition at line 280 of file gic_v3_cpu_interface.hh.
TSEI
Bitfield<13> Gicv3CPUInterface::TSEI protected
Definition at line 202 of file gic_v3_cpu_interface.hh.
U
Bitfield<1> Gicv3CPUInterface::U protected
Definition at line 253 of file gic_v3_cpu_interface.hh.
Referenced by groupPriorityMask(), readMiscReg(), setMiscReg(), and virtualGroupPriorityMask().
UIE
Bitfield<1> Gicv3CPUInterface::UIE protected
Definition at line 213 of file gic_v3_cpu_interface.hh.
VAckCtl
Bitfield<2> Gicv3CPUInterface::VAckCtl protected
Definition at line 267 of file gic_v3_cpu_interface.hh.
VBPR0
Bitfield<23, 21> Gicv3CPUInterface::VBPR0 protected
Definition at line 260 of file gic_v3_cpu_interface.hh.
VBPR1
Bitfield<20, 18> Gicv3CPUInterface::VBPR1 protected
Definition at line 261 of file gic_v3_cpu_interface.hh.
VCBPR
Bitfield<4> Gicv3CPUInterface::VCBPR protected
Definition at line 265 of file gic_v3_cpu_interface.hh.
VENG0
Bitfield<0> Gicv3CPUInterface::VENG0 protected
Definition at line 269 of file gic_v3_cpu_interface.hh.
VENG1
Bitfield<1> Gicv3CPUInterface::VENG1 protected
Definition at line 268 of file gic_v3_cpu_interface.hh.
VEOIM
Bitfield<9> Gicv3CPUInterface::VEOIM protected
Definition at line 263 of file gic_v3_cpu_interface.hh.
VFIQEn
Bitfield<3> Gicv3CPUInterface::VFIQEn protected
Definition at line 266 of file gic_v3_cpu_interface.hh.
VGrp0D
Bitfield<5> Gicv3CPUInterface::VGrp0D protected
Definition at line 249 of file gic_v3_cpu_interface.hh.
VGrp0DIE
Bitfield<5> Gicv3CPUInterface::VGrp0DIE protected
Definition at line 209 of file gic_v3_cpu_interface.hh.
VGrp0E
Bitfield<4> Gicv3CPUInterface::VGrp0E protected
Definition at line 250 of file gic_v3_cpu_interface.hh.
VGrp0EIE
Bitfield<4> Gicv3CPUInterface::VGrp0EIE protected
Definition at line 210 of file gic_v3_cpu_interface.hh.
VGrp1D
Bitfield<7> Gicv3CPUInterface::VGrp1D protected
Definition at line 247 of file gic_v3_cpu_interface.hh.
VGrp1DIE
Bitfield<7> Gicv3CPUInterface::VGrp1DIE protected
Definition at line 207 of file gic_v3_cpu_interface.hh.
VGrp1E
Bitfield<6> Gicv3CPUInterface::VGrp1E protected
Definition at line 248 of file gic_v3_cpu_interface.hh.
VGrp1EIE
Bitfield<6> Gicv3CPUInterface::VGrp1EIE protected
Definition at line 208 of file gic_v3_cpu_interface.hh.
vINTID
Bitfield<31, 0> Gicv3CPUInterface::vINTID protected
Definition at line 226 of file gic_v3_cpu_interface.hh.
VIRTUAL_NUM_LIST_REGS
const uint8_t Gicv3CPUInterface::VIRTUAL_NUM_LIST_REGS = 16 static protected
Definition at line 152 of file gic_v3_cpu_interface.hh.
Referenced by eoiMaintenanceInterruptStatus(), maintenanceInterruptStatus(), readMiscReg(), and virtualFindActive().
VIRTUAL_PREEMPTION_BITS
const uint8_t Gicv3CPUInterface::VIRTUAL_PREEMPTION_BITS = 5 static protected
Definition at line 151 of file gic_v3_cpu_interface.hh.
Referenced by readMiscReg(), setMiscReg(), virtualActivateIRQ(), and virtualDropPriority().
VIRTUAL_PRIORITY_BITS
const uint8_t Gicv3CPUInterface::VIRTUAL_PRIORITY_BITS = 5 static protected
Definition at line 150 of file gic_v3_cpu_interface.hh.
Referenced by readMiscReg(), and virtualHighestActivePriority().
VPMR
Bitfield<31, 24> Gicv3CPUInterface::VPMR protected
Definition at line 259 of file gic_v3_cpu_interface.hh.
The documentation for this class was generated from the following files:
dev/arm/gic_v3_cpu_interface.hh
dev/arm/gic_v3_cpu_interface.cc