gem5: BreakPCEvent Class Reference
BreakPCEvent Class Reference
#include <pc_event.hh>
Public Member Functions
BreakPCEvent (PCEventScope *s, const std::string &desc, Addr addr, bool del=false)
virtual void process (ThreadContext *tc)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Protected Attributes
bool remove
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 147 of file pc_event.hh.
Constructor & Destructor Documentation
BreakPCEvent()
BreakPCEvent::BreakPCEvent (PCEventScope * s, const std::string & desc, Addr addr, bool del = false)
Definition at line 119 of file pc_event.cc.
Member Function Documentation
process()
void BreakPCEvent::process (ThreadContext * tc) virtual
Implements PCEvent.
Definition at line 126 of file pc_event.cc.
References Debug::breakpoint(), PCEvent::descr(), DPRINTFN, and PCEvent::name().
Member Data Documentation
remove
bool BreakPCEvent::remove protected
Definition at line 150 of file pc_event.hh.
The documentation for this class was generated from the following files:
cpu/pc_event.hh
cpu/pc_event.cc