gem5: tlm_utils::peq_with_get< PAYLOAD > Class Template Reference
tlm_utils::peq_with_get< PAYLOAD > Class Template Reference
#include <peq_with_get.h>
Public Types
typedef PAYLOAD transaction_type
typedef std::pair< const sc_core::sc_time, transaction_type * > pair_type
Public Member Functions
peq_with_get (const char *name)
void notify (transaction_type &trans, const sc_core::sc_time &t)
void notify (transaction_type &trans)
transaction_type * get_next_transaction ()
sc_core::sc_event & get_event ()
void cancel_all ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual const char * kind () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Attributes
std::multimap< const sc_core::sc_time, transaction_type * > m_scheduled_events
sc_core::sc_event m_event
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
template<class PAYLOAD>
class tlm_utils::peq_with_get< PAYLOAD >
Definition at line 38 of file peq_with_get.h.
Member Typedef Documentation
pair_type
template<class PAYLOAD> typedef std::pair<const sc_core::sc_time, transaction_type *> tlm_utils::peq_with_get< PAYLOAD >::pair_type
Definition at line 42 of file peq_with_get.h.
transaction_type
template<class PAYLOAD> typedef PAYLOAD tlm_utils::peq_with_get< PAYLOAD >::transaction_type
Definition at line 41 of file peq_with_get.h.
Constructor & Destructor Documentation
peq_with_get()
template<class PAYLOAD> tlm_utils::peq_with_get< PAYLOAD >::peq_with_get (const char * name) inline
Definition at line 45 of file peq_with_get.h.
Member Function Documentation
cancel_all()
template<class PAYLOAD> void tlm_utils::peq_with_get< PAYLOAD >::cancel_all () inline
Definition at line 86 of file peq_with_get.h.
get_event()
template<class PAYLOAD> sc_core::sc_event& tlm_utils::peq_with_get< PAYLOAD >::get_event () inline
Definition at line 82 of file peq_with_get.h.
Referenced by SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::ResponseThread().
get_next_transaction()
template<class PAYLOAD> transaction_type* tlm_utils::peq_with_get< PAYLOAD >::get_next_transaction () inline
Definition at line 64 of file peq_with_get.h.
Referenced by SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::ResponseThread().
notify() [1/2]
template<class PAYLOAD> void tlm_utils::peq_with_get< PAYLOAD >::notify (transaction_type & trans, const sc_core::sc_time & t) inline
Definition at line 48 of file peq_with_get.h.
Referenced by SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorNBTransport(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::targetNBTransport().
notify() [2/2]
template<class PAYLOAD> void tlm_utils::peq_with_get< PAYLOAD >::notify (transaction_type & trans) inline
Definition at line 56 of file peq_with_get.h.
Member Data Documentation
m_event
template<class PAYLOAD> sc_core::sc_event tlm_utils::peq_with_get< PAYLOAD >::m_event private
Definition at line 95 of file peq_with_get.h.
Referenced by tlm_utils::peq_with_get< transaction_type >::cancel_all(), tlm_utils::peq_with_get< transaction_type >::get_event(), tlm_utils::peq_with_get< transaction_type >::get_next_transaction(), and tlm_utils::peq_with_get< transaction_type >::notify().
m_scheduled_events
template<class PAYLOAD> std::multimap<const sc_core::sc_time, transaction_type *> tlm_utils::peq_with_get< PAYLOAD >::m_scheduled_events private
Definition at line 94 of file peq_with_get.h.
Referenced by tlm_utils::peq_with_get< transaction_type >::cancel_all(), tlm_utils::peq_with_get< transaction_type >::get_next_transaction(), and tlm_utils::peq_with_get< transaction_type >::notify().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/peq_with_get.h