gem5: Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits > Class Template Reference
Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits > Class Template Reference
A pipeline simulating class that will stall (not advance when advance() is called) if a non-bubble value lies at the far end of the pipeline.
#include <buffers.hh>
Public Member Functions
SelfStallingPipeline (const std::string &name, const std::string &data_name, unsigned depth)
void push (ElemType &elem)
Write an element to the back of the pipeline.
ElemType & front ()
Peek at the end element of the pipe.
const ElemType & front () const
bool alreadyPushed ()
Have we already pushed onto this pipe without advancing.
bool isPopable ()
There's data (not a bubble) at the end of the pipe.
void advance ()
Try to advance the pipeline.
Public Member Functions inherited from Minor::MinorBuffer< ElemType, ReportTraits >
MinorBuffer (const std::string &name, const std::string &data_name, int num_past, int num_future, int report_left=-1, int report_right=-1)
bool empty () const
void minorTrace () const
Report buffer states from 'slot' 'from' to 'to'.
Public Member Functions inherited from Named
Named (const std::string &name_)
const std::string & name () const
Public Member Functions inherited from TimeBuffer< ElemType >
TimeBuffer (int p, int f)
TimeBuffer ()
~TimeBuffer ()
void id (int id)
int id ()
void advance ()
ElemType * access (int idx)
ElemType & operator[] (int idx)
const ElemType & operator[] (int idx) const
wire getWire (int idx)
wire zero ()
unsigned getSize ()
Public Attributes
bool stalled
If true, advance will not advance the pipeline.
unsigned int occupancy
The number of slots with non-bubbles in them.
Protected Attributes
TimeBuffer< ElemType >::wire pushWire
Wire at the input end of the pipeline (for convenience)
TimeBuffer< ElemType >::wire popWire
Wire at the output end of the pipeline (for convenience)
Protected Attributes inherited from Minor::MinorBuffer< ElemType, ReportTraits >
int reportLeft
The range of elements that should appear in trace lines.
int reportRight
std::string dataName
Name to use for the data in a MinorTrace line.
Protected Attributes inherited from Named
const std::string _name
Protected Attributes inherited from TimeBuffer< ElemType >
int past
int future
unsigned size
int _id
char * data
std::vector< char *> index
unsigned base
Additional Inherited Members
Protected Member Functions inherited from TimeBuffer< ElemType >
void valid (int idx) const
int calculateVectorIndex (int idx) const
Detailed Description
template<typename ElemType, typename ReportTraits, typename BubbleTraits = BubbleTraitsAdaptor<ElemType>>
class Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >
A pipeline simulating class that will stall (not advance when advance() is called) if a non-bubble value lies at the far end of the pipeline.
The user can clear the stall before calling advance to unstall the pipeline.
Definition at line 289 of file buffers.hh.
Constructor & Destructor Documentation
SelfStallingPipeline()
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::SelfStallingPipeline (const std::string & name, const std::string & data_name, unsigned depth) inline
Definition at line 305 of file buffers.hh.
References ArmISA::i.
Member Function Documentation
advance()
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::advance () inline
Try to advance the pipeline.
If we're stalled, don't advance. If we're not stalled, advance then check to see if we become stalled (a non-bubble at the end of the pipe)
Definition at line 351 of file buffers.hh.
References TimeBuffer< T >::advance().
Referenced by Minor::FUPipeline::advance().
alreadyPushed()
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::alreadyPushed () inline
Have we already pushed onto this pipe without advancing.
Definition at line 342 of file buffers.hh.
Referenced by Minor::FUPipeline::advance(), and Minor::Execute::issue().
front() [1/2]
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> ElemType& Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::front () inline
Peek at the end element of the pipe.
Definition at line 337 of file buffers.hh.
Referenced by Minor::Execute::commit(), Minor::Execute::evaluate(), and Minor::Execute::getCommittingThread().
front() [2/2]
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> const ElemType& Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::front () const inline
Definition at line 339 of file buffers.hh.
isPopable()
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::isPopable () inline
There's data (not a bubble) at the end of the pipe.
Definition at line 345 of file buffers.hh.
push()
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> void Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::push (ElemType & elem) inline
Write an element to the back of the pipeline.
This doesn't cause the pipeline to advance until advance is called. Pushing twice without advance-ing will just cause an overwrite of the last push's data.
Definition at line 328 of file buffers.hh.
Referenced by Minor::Execute::issue().
Member Data Documentation
occupancy
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> unsigned int Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::occupancy
The number of slots with non-bubbles in them.
Definition at line 302 of file buffers.hh.
Referenced by Minor::Execute::evaluate().
popWire
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> TimeBuffer<ElemType>::wire Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::popWire protected
Wire at the output end of the pipeline (for convenience)
Definition at line 295 of file buffers.hh.
pushWire
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> TimeBuffer<ElemType>::wire Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::pushWire protected
Wire at the input end of the pipeline (for convenience)
Definition at line 293 of file buffers.hh.
stalled
template<typename ElemType , typename ReportTraits , typename BubbleTraits = BubbleTraitsAdaptor<ElemType>> bool Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::stalled
If true, advance will not advance the pipeline.
Definition at line 299 of file buffers.hh.
Referenced by Minor::FUPipeline::advance(), Minor::Execute::evaluate(), and Minor::Execute::issue().
The documentation for this class was generated from the following file:
cpu/minor/buffers.hh