gem5: SetAssociative Class Reference
SetAssociative Class Reference
A set associative indexing policy.
#include <set_associative.hh>
Public Types
typedef SetAssociativeParams Params
Convenience typedef.
Public Types inherited from BaseIndexingPolicy
typedef BaseIndexingPolicyParams Params
Convenience typedef.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
SetAssociative (const Params *p)
Construct and initialize this policy.
~SetAssociative ()
Destructor.
std::vector< ReplaceableEntry * > getPossibleEntries (const Addr addr) const override
Find all possible entries for insertion and replacement of an address.
Addr regenerateAddr (const Addr tag, const ReplaceableEntry *entry) const override
Regenerate an entry's address from its tag and assigned set and way.
Public Member Functions inherited from BaseIndexingPolicy
BaseIndexingPolicy (const Params *p)
Construct and initialize this policy.
~BaseIndexingPolicy ()
Destructor.
void setEntry (ReplaceableEntry *entry, const uint64_t index)
Associate a pointer to an entry to its physical counterpart.
ReplaceableEntry * getEntry (const uint32_t set, const uint32_t way) const
Get an entry based on its set and way.
Addr extractTag (const Addr addr) const
Generate the tag from the given address.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
uint32_t extractSet (const Addr addr) const
Apply a hash function to calculate address set.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from BaseIndexingPolicy
const unsigned assoc
The associativity.
const uint32_t numSets
The number of sets in the cache.
const int setShift
The amount to shift the address to get the set.
const unsigned setMask
Mask out all bits that aren't part of the set index.
std::vector< std::vector< ReplaceableEntry * > > sets
The cache sets.
const int tagShift
The amount to shift the address to get the tag.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
A set associative indexing policy.
See also
gem5 Memory System
The set associative indexing policy has an immutable/identity mapping, so a value x is always mapped to set x, independent of the way, that is, Hash(A, 0) = Hash(A, 1) = Hash(A, N-1), where N is the number of ways.
For example, let's assume address A maps to set 3 on way 0. This policy makes so that A is also mappable to set 3 on every other way. Visually, the possible locations of A are, for a table with 4 ways and 8 sets: Way 0 1 2 3 Set _ _ _ _ 0 |_| |_| |_| |_| 1 |_| |_| |_| |_| 2 |_| |_| |_| |_| 3 |X| |X| |X| |X| 4 |_| |_| |_| |_| 5 |_| |_| |_| |_| 6 |_| |_| |_| |_| 7 |_| |_| |_| |_|
Definition at line 82 of file set_associative.hh.
Member Typedef Documentation
Params
typedef SetAssociativeParams SetAssociative::Params
Convenience typedef.
Definition at line 97 of file set_associative.hh.
Constructor & Destructor Documentation
SetAssociative()
SetAssociative::SetAssociative (const Params * p)
Construct and initialize this policy.
Definition at line 54 of file set_associative.cc.
Referenced by getPossibleEntries().
~SetAssociative()
SetAssociative::~SetAssociative () inline
Destructor.
Definition at line 107 of file set_associative.hh.
References getPossibleEntries(), and regenerateAddr().
Member Function Documentation
extractSet()
uint32_t SetAssociative::extractSet (const Addr addr) const private
Apply a hash function to calculate address set.
Parameters
addr The address to calculate the set for.
Returns
The set index for given combination of address and way.
Definition at line 60 of file set_associative.cc.
References BaseIndexingPolicy::setMask, and BaseIndexingPolicy::setShift.
Referenced by getPossibleEntries().
getPossibleEntries()
std::vector< ReplaceableEntry * > SetAssociative::getPossibleEntries (const Addr addr) const override virtual
Find all possible entries for insertion and replacement of an address.
Should be called immediately before ReplacementPolicy's findVictim() not to break cache resizing. Returns entries in all ways belonging to the set of the address.
Parameters
addr The addr to a find possible entries for.
Returns
The possible entries.
Implements BaseIndexingPolicy.
Definition at line 73 of file set_associative.cc.
References extractSet(), SetAssociative(), and BaseIndexingPolicy::sets.
Referenced by ~SetAssociative().
regenerateAddr()
Addr SetAssociative::regenerateAddr (const Addr tag, const ReplaceableEntry * entry) const override virtual
Regenerate an entry's address from its tag and assigned set and way.
Parameters
tag The tag bits.
entry The entry.
Returns
the entry's original addr value.
Implements BaseIndexingPolicy.
Definition at line 66 of file set_associative.cc.
References ReplaceableEntry::getSet(), BaseIndexingPolicy::setShift, and BaseIndexingPolicy::tagShift.
Referenced by ~SetAssociative().
The documentation for this class was generated from the following files:
mem/cache/tags/indexing_policies/set_associative.hh
mem/cache/tags/indexing_policies/set_associative.cc