gem5: EtherTapBase Class Reference
EtherTapBase Class Reference abstract
#include <ethertap.hh>
Public Types
typedef EtherTapBaseParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
EtherTapBase (const Params *p)
virtual ~EtherTapBase ()
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
bool recvSimulated (EthPacketPtr packet)
void sendSimulated (void *data, size_t len)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void pollFd (int fd)
void stopPolling ()
virtual void recvReal (int revent)=0
virtual bool sendReal (const void *data, size_t len)=0
void retransmit ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
uint8_t * buffer
int buflen
EtherDump * dump
TapEvent * event
EtherTapInt * interface
std::queue< EthPacketPtr > packetBuffer
EventFunctionWrapper txEvent
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class TapEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 58 of file ethertap.hh.
Member Typedef Documentation
Params
typedef EtherTapBaseParams EtherTapBase::Params
Definition at line 61 of file ethertap.hh.
Constructor & Destructor Documentation
EtherTapBase()
EtherTapBase::EtherTapBase (const Params * p)
Definition at line 94 of file ethertap.cc.
References buffer, buflen, and retransmit().
Referenced by EtherTapStub::sendReal().
~EtherTapBase()
EtherTapBase::~EtherTapBase () virtual
Definition at line 103 of file ethertap.cc.
References buffer, event, and interface.
Member Function Documentation
getPort()
Port & EtherTapBase::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 163 of file ethertap.cc.
References SimObject::getPort(), and interface.
params()
const Params* EtherTapBase::params () const inline
Definition at line 66 of file ethertap.hh.
References SimObject::_params, serialize(), and unserialize().
pollFd()
void EtherTapBase::pollFd (int fd) protected
Definition at line 146 of file ethertap.cc.
References event, pollQueue, PollQueue::schedule(), and TapEvent.
Referenced by EtherTapStub::attach(), and EtherTapStub::sendReal().
recvReal()
virtual void EtherTapBase::recvReal (int revent) protected pure virtual
Implemented in EtherTapStub.
Referenced by TapEvent::process().
recvSimulated()
bool EtherTapBase::recvSimulated (EthPacketPtr packet)
Definition at line 171 of file ethertap.cc.
References DDUMP, DPRINTF, EtherDump::dump(), dump, interface, EtherInt::recvDone(), and sendReal().
Referenced by EtherTapInt::recvPacket().
retransmit()
void EtherTapBase::retransmit () protected
Definition at line 208 of file ethertap.cc.
References curTick(), DPRINTF, EtherDump::dump(), dump, interface, packetBuffer, retryTime, EventManager::schedule(), Event::scheduled(), EtherInt::sendPacket(), and txEvent.
Referenced by EtherTapBase().
sendReal()
virtual bool EtherTapBase::sendReal (const void * data, size_t len) protected pure virtual
Implemented in EtherTapStub.
Referenced by recvSimulated().
sendSimulated()
void EtherTapBase::sendSimulated (void * data, size_t len)
Definition at line 187 of file ethertap.cc.
References curTick(), DDUMP, DPRINTF, EtherDump::dump(), dump, interface, ArmISA::len, packetBuffer, retryTime, EventManager::schedule(), Event::scheduled(), EtherInt::sendPacket(), and txEvent.
Referenced by EtherTapStub::recvReal(), and EtherTapStub::sendReal().
serialize()
void EtherTapBase::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in EtherTapStub.
Definition at line 111 of file ethertap.cc.
References buffer, buflen, event, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
Referenced by params(), EtherTapStub::params(), and EtherTapStub::serialize().
stopPolling()
void EtherTapBase::stopPolling () protected
Definition at line 154 of file ethertap.cc.
References event.
Referenced by EtherTapStub::detach(), and EtherTapStub::sendReal().
unserialize()
void EtherTapBase::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in EtherTapStub.
Definition at line 128 of file ethertap.cc.
References buffer, buflen, event, pollQueue, PollEvent::queued(), PollQueue::schedule(), TapEvent, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by params(), EtherTapStub::params(), and EtherTapStub::unserialize().
Friends And Related Function Documentation
TapEvent
friend class TapEvent friend
Definition at line 85 of file ethertap.hh.
Referenced by pollFd(), and unserialize().
Member Data Documentation
buffer
uint8_t* EtherTapBase::buffer protected
Definition at line 75 of file ethertap.hh.
Referenced by EtherTapBase(), EtherTapStub::recvReal(), EtherTapStub::sendReal(), serialize(), unserialize(), and ~EtherTapBase().
buflen
int EtherTapBase::buflen protected
Definition at line 76 of file ethertap.hh.
Referenced by EtherTapBase(), EtherTapStub::recvReal(), EtherTapStub::sendReal(), serialize(), and unserialize().
dump
EtherDump* EtherTapBase::dump protected
Definition at line 78 of file ethertap.hh.
Referenced by recvSimulated(), retransmit(), and sendSimulated().
event
TapEvent* EtherTapBase::event protected
Definition at line 86 of file ethertap.hh.
Referenced by TapListener::listen(), pollFd(), serialize(), stopPolling(), unserialize(), ~EtherTapBase(), and TapListener::~TapListener().
interface
EtherTapInt* EtherTapBase::interface protected
Definition at line 100 of file ethertap.hh.
Referenced by getPort(), recvSimulated(), retransmit(), sendSimulated(), and ~EtherTapBase().
packetBuffer
std::queue<EthPacketPtr> EtherTapBase::packetBuffer protected
Definition at line 110 of file ethertap.hh.
Referenced by retransmit(), and sendSimulated().
txEvent
EventFunctionWrapper EtherTapBase::txEvent protected
Definition at line 112 of file ethertap.hh.
Referenced by retransmit(), and sendSimulated().
The documentation for this class was generated from the following files:
dev/net/ethertap.hh
dev/net/ethertap.cc