gem5: ArmSemihosting::File Class Reference
ArmSemihosting::File Class Reference
#include <semihosting.hh>
Public Member Functions
File (ArmSemihosting &_parent, const char *name, const char *mode)
~File ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
int64_t open () override
Open the the file.
int64_t close () override
Close the file.
bool isTTY () const override
Check if a file corresponds to a TTY device.
int64_t read (uint8_t *buffer, uint64_t size) override
Read data from file.
int64_t write (const uint8_t *buffer, uint64_t size) override
Write data to file.
int64_t seek (uint64_t pos) override
Seek to an absolute position in the file.
int64_t flen () override
Get the length of a file in bytes.
Public Member Functions inherited from ArmSemihosting::FileBase
FileBase (ArmSemihosting &_parent, const char *name, const char *_mode)
virtual ~FileBase ()
FileBase ()=delete
FileBase (FileBase &)=delete
const std::string & fileName ()
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Member Functions
int64_t openImpl (bool unserialize)
bool needClose () const
Protected Attributes
FILE * file
Protected Attributes inherited from ArmSemihosting::FileBase
ArmSemihosting & parent
std::string _name
std::string mode
Additional Inherited Members
Static Public Member Functions inherited from ArmSemihosting::FileBase
static std::unique_ptr< FileBase > create (ArmSemihosting &parent, const std::string &fname, const char *mode)
static std::unique_ptr< FileBase > create (ArmSemihosting &parent, CheckpointIn &cp, const std::string &sec)
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 222 of file semihosting.hh.
Constructor & Destructor Documentation
File()
ArmSemihosting::File::File (ArmSemihosting & _parent, const char * name, const char * mode)
Definition at line 829 of file semihosting.cc.
~File()
ArmSemihosting::File::~File ()
Definition at line 836 of file semihosting.cc.
References close(), and file.
Member Function Documentation
close()
int64_t ArmSemihosting::File::close () override virtual
Close the file.
Returns
<0 on error (-errno), 0 on success.
Reimplemented from ArmSemihosting::FileBase.
Definition at line 872 of file semihosting.cc.
References file, needClose(), and panic_if.
Referenced by ~File().
flen()
int64_t ArmSemihosting::File::flen () override virtual
Get the length of a file in bytes.
Returns
<0 on error (-errno), length on success
Reimplemented from ArmSemihosting::FileBase.
Definition at line 936 of file semihosting.cc.
References file, and ArmISA::len.
isTTY()
bool ArmSemihosting::File::isTTY () const override virtual
Check if a file corresponds to a TTY device.
Returns
True if the file is a TTY, false otherwise.
Reimplemented from ArmSemihosting::FileBase.
Definition at line 885 of file semihosting.cc.
References file, ArmSemihosting::FileBase::parent, ArmSemihosting::stderr, ArmSemihosting::stdin, and ArmSemihosting::stdout.
Referenced by serialize(), and unserialize().
needClose()
bool ArmSemihosting::File::needClose () const inline protected
Definition at line 241 of file semihosting.hh.
References ArmSemihosting::FileBase::isTTY().
Referenced by close().
open()
int64_t ArmSemihosting::File::open () inline override virtual
Open the the file.
Semihosting file IO interfaces
These interfaces implement common IO functionality in the Semihosting interface.
All functions return a negative value that corresponds to a UNIX errno value when they fail and >=0 on success.
Returns
<0 on error (-errno), 0 on success.
Reimplemented from ArmSemihosting::FileBase.
Definition at line 231 of file semihosting.hh.
References ArmSemihosting::FileBase::close(), ArmSemihosting::FileBase::flen(), ArmSemihosting::FileBase::isTTY(), openImpl(), ArmSemihosting::FileBase::read(), ArmSemihosting::FileBase::seek(), and ArmSemihosting::FileBase::write().
openImpl()
int64_t ArmSemihosting::File::openImpl (bool unserialize) protected
Definition at line 843 of file semihosting.cc.
References ArmSemihosting::FileBase::_name, file, ArmSemihosting::FileBase::mode, panic_if, ArmSemihosting::FileBase::parent, ArmSemihosting::stderr, ArmSemihosting::stdin, ArmSemihosting::stdout, and warn.
Referenced by unserialize().
read()
int64_t ArmSemihosting::File::read (uint8_t * buffer, uint64_t size) override virtual
Read data from file.
Returns
<0 on error (-errno), bytes read on success (0 for EOF).
Reimplemented from ArmSemihosting::FileBase.
Definition at line 893 of file semihosting.cc.
References file, and panic_if.
seek()
int64_t ArmSemihosting::File::seek (uint64_t pos) override virtual
Seek to an absolute position in the file.
Parameters
pos Byte offset from start of file.
Returns
<0 on error (-errno), 0 on success.
Reimplemented from ArmSemihosting::FileBase.
Definition at line 924 of file semihosting.cc.
References file, and panic_if.
serialize()
void ArmSemihosting::File::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from ArmSemihosting::FileBase.
Definition at line 958 of file semihosting.cc.
References file, isTTY(), panic_if, ArmSemihosting::FileBase::serialize(), and SERIALIZE_SCALAR.
unserialize()
void ArmSemihosting::File::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from ArmSemihosting::FileBase.
Definition at line 970 of file semihosting.cc.
References ArmSemihosting::FileBase::_name, ArmSemihosting::ArmSemihosting(), fatal, file, isTTY(), openImpl(), ArmSemihosting::FileBase::unserialize(), and UNSERIALIZE_SCALAR.
write()
int64_t ArmSemihosting::File::write (const uint8_t * buffer, uint64_t size) override virtual
Write data to file.
Returns
<0 on error (-errno), bytes written on success.
Reimplemented from ArmSemihosting::FileBase.
Definition at line 908 of file semihosting.cc.
References file, and panic_if.
Member Data Documentation
file
FILE* ArmSemihosting::File::file protected
Definition at line 243 of file semihosting.hh.
Referenced by close(), flen(), isTTY(), openImpl(), read(), seek(), serialize(), unserialize(), write(), and ~File().
The documentation for this class was generated from the following files:
arch/arm/semihosting.hh
arch/arm/semihosting.cc