gem5: sc_dt::scfx_mant_ref Class Reference
sc_dt::scfx_mant_ref Class Reference
#include <scfx_mant.hh>
Public Member Functions
scfx_mant_ref ()
scfx_mant_ref (const scfx_mant &)
scfx_mant_ref (scfx_mant *)
scfx_mant_ref & operator= (const scfx_mant &)
scfx_mant_ref & operator= (scfx_mant *)
~scfx_mant_ref ()
operator scfx_mant & ()
word operator[] (int)
Private Member Functions
void remove_it ()
scfx_mant_ref (const scfx_mant_ref &)
scfx_mant_ref & operator= (const scfx_mant_ref &)
void * operator new (std::size_t sz)
Private Attributes
scfx_mant * m_mant
bool m_not_const
Detailed Description
Definition at line 324 of file scfx_mant.hh.
Constructor & Destructor Documentation
scfx_mant_ref() [1/4]
sc_dt::scfx_mant_ref::scfx_mant_ref () inline
Definition at line 363 of file scfx_mant.hh.
scfx_mant_ref() [2/4]
sc_dt::scfx_mant_ref::scfx_mant_ref (const scfx_mant & mant) inline
Definition at line 365 of file scfx_mant.hh.
scfx_mant_ref() [3/4]
sc_dt::scfx_mant_ref::scfx_mant_ref (scfx_mant * mant) inline
Definition at line 369 of file scfx_mant.hh.
~scfx_mant_ref()
sc_dt::scfx_mant_ref::~scfx_mant_ref () inline
Definition at line 395 of file scfx_mant.hh.
References remove_it().
scfx_mant_ref() [4/4]
sc_dt::scfx_mant_ref::scfx_mant_ref (const scfx_mant_ref &) private
Member Function Documentation
operator new()
void* sc_dt::scfx_mant_ref::operator new (std::size_t sz) inline private
Definition at line 349 of file scfx_mant.hh.
operator scfx_mant &()
sc_dt::scfx_mant_ref::operator scfx_mant & () inline
Definition at line 400 of file scfx_mant.hh.
References m_mant.
operator=() [1/3]
scfx_mant_ref & sc_dt::scfx_mant_ref::operator= (const scfx_mant & mant) inline
Definition at line 374 of file scfx_mant.hh.
References m_mant, m_not_const, and remove_it().
operator=() [2/3]
scfx_mant_ref & sc_dt::scfx_mant_ref::operator= (scfx_mant * mant) inline
Definition at line 385 of file scfx_mant.hh.
References m_mant, m_not_const, and remove_it().
operator=() [3/3]
scfx_mant_ref& sc_dt::scfx_mant_ref::operator= (const scfx_mant_ref &) private
operator[]()
word sc_dt::scfx_mant_ref::operator[] (int i) inline
Definition at line 407 of file scfx_mant.hh.
References ArmISA::i, and m_mant.
remove_it()
void sc_dt::scfx_mant_ref::remove_it () inline private
Definition at line 356 of file scfx_mant.hh.
Referenced by operator=(), and ~scfx_mant_ref().
Member Data Documentation
m_mant
scfx_mant* sc_dt::scfx_mant_ref::m_mant private
Definition at line 326 of file scfx_mant.hh.
Referenced by operator scfx_mant &(), operator=(), and operator[]().
m_not_const
bool sc_dt::scfx_mant_ref::m_not_const private
Definition at line 327 of file scfx_mant.hh.
Referenced by operator=().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/scfx_mant.hh