gem5: sc_core::sc_signal_in_if< bool > Class Template Reference
sc_core::sc_signal_in_if< bool > Class Template Reference abstract
#include <sc_signal_in_if.hh>
Public Member Functions
virtual const bool & read () const =0
virtual const sc_event & value_changed_event () const =0
virtual const sc_event & posedge_event () const =0
virtual const sc_event & negedge_event () const =0
virtual bool event () const =0
virtual bool posedge () const =0
virtual bool negedge () const =0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
virtual bool _addReset (sc_gem5::Reset *reset) const
sc_signal_in_if (const sc_signal_in_if< bool > &)
sc_signal_in_if< bool > & operator= (const sc_signal_in_if< bool > &)
Friends
class sc_gem5::Reset
Detailed Description
template<>
class sc_core::sc_signal_in_if< bool >
Definition at line 76 of file sc_signal_in_if.hh.
Constructor & Destructor Documentation
sc_signal_in_if() [1/2]
sc_core::sc_signal_in_if< bool >::sc_signal_in_if () inline protected
Definition at line 90 of file sc_signal_in_if.hh.
sc_signal_in_if() [2/2]
sc_core::sc_signal_in_if< bool >::sc_signal_in_if (const sc_signal_in_if< bool > &) inline private
Definition at line 101 of file sc_signal_in_if.hh.
Member Function Documentation
_addReset()
virtual bool sc_core::sc_signal_in_if< bool >::_addReset (sc_gem5::Reset * reset) const inline private virtual
Reimplemented in sc_core::sc_signal< bool, WRITER_POLICY >.
Definition at line 95 of file sc_signal_in_if.hh.
event()
virtual bool sc_core::sc_signal_in_if< bool >::event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, and sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >.
negedge()
virtual bool sc_core::sc_signal_in_if< bool >::negedge () const pure virtual
Implemented in sc_gem5::ScSignalBinary< bool, WRITER_POLICY >.
negedge_event()
virtual const sc_event& sc_core::sc_signal_in_if< bool >::negedge_event () const pure virtual
Implemented in sc_gem5::ScSignalBinary< bool, WRITER_POLICY >.
operator=()
sc_signal_in_if<bool>& sc_core::sc_signal_in_if< bool >::operator= (const sc_signal_in_if< bool > &) inline private
Definition at line 103 of file sc_signal_in_if.hh.
posedge()
virtual bool sc_core::sc_signal_in_if< bool >::posedge () const pure virtual
Implemented in sc_gem5::ScSignalBinary< bool, WRITER_POLICY >.
posedge_event()
virtual const sc_event& sc_core::sc_signal_in_if< bool >::posedge_event () const pure virtual
Implemented in sc_gem5::ScSignalBinary< bool, WRITER_POLICY >.
Referenced by sc_core::sc_sensitive::operator()().
read()
virtual const bool& sc_core::sc_signal_in_if< bool >::read () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, and sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >.
Referenced by sc_core::at_negedge(), sc_core::at_posedge(), sc_core::sc_inout< bool >::initialize(), and sc_core::sc_inout< bool >::operator=().
value_changed_event()
virtual const sc_event& sc_core::sc_signal_in_if< bool >::value_changed_event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, and sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >.
Friends And Related Function Documentation
sc_gem5::Reset
friend class sc_gem5::Reset friend
Definition at line 93 of file sc_signal_in_if.hh.
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_signal_in_if.hh