gem5: sc_gem5::Reset Class Reference
sc_gem5::Reset Class Reference
#include <process.hh>
Public Member Functions
Reset (Process *p, bool s, bool v)
bool install (const sc_core::sc_signal_in_if< bool > *s)
void update ()
Process * process ()
const sc_core::sc_signal_in_if< bool > * signal ()
bool sync ()
bool value ()
Private Attributes
Process * _process
const sc_core::sc_signal_in_if< bool > * _signal
bool _sync
bool _value
Detailed Description
Definition at line 208 of file process.hh.
Constructor & Destructor Documentation
Reset()
sc_gem5::Reset::Reset (Process * p, bool s, bool v) inline
Definition at line 211 of file process.hh.
Member Function Documentation
install()
bool sc_gem5::Reset::install (const sc_core::sc_signal_in_if< bool > * s) inline
Definition at line 216 of file process.hh.
References ArmISA::s.
Referenced by sc_gem5::Port::finalizeReset(), and sc_gem5::newReset().
process()
Process* sc_gem5::Reset::process () inline
Definition at line 230 of file process.hh.
signal()
const sc_core::sc_signal_in_if<bool>* sc_gem5::Reset::signal () inline
Definition at line 231 of file process.hh.
sync()
bool sc_gem5::Reset::sync () inline
Definition at line 232 of file process.hh.
update()
void sc_gem5::Reset::update () inline
Definition at line 228 of file process.hh.
Referenced by sc_gem5::ScSignalBaseBinary::_signalReset().
value()
bool sc_gem5::Reset::value () inline
Definition at line 233 of file process.hh.
Member Data Documentation
_process
Process* sc_gem5::Reset::_process private
Definition at line 236 of file process.hh.
_signal
const sc_core::sc_signal_in_if<bool>* sc_gem5::Reset::_signal private
Definition at line 237 of file process.hh.
_sync
bool sc_gem5::Reset::_sync private
Definition at line 238 of file process.hh.
_value
bool sc_gem5::Reset::_value private
Definition at line 239 of file process.hh.
The documentation for this class was generated from the following file:
systemc/core/process.hh