gem5: sc_core::sc_sensitive Class Reference
sc_core::sc_sensitive Class Reference
#include <sc_sensitive.hh>
Public Member Functions
sc_sensitive & operator<< (const sc_event &)
sc_sensitive & operator<< (const sc_interface &)
sc_sensitive & operator<< (const sc_port_base &)
sc_sensitive & operator<< (sc_event_finder &)
sc_sensitive & operator<< (::sc_gem5::Process *p)
void operator() (::sc_gem5::Process *p, const sc_signal_in_if< bool > &)
void operator() (::sc_gem5::Process *p, const sc_signal_in_if< sc_dt::sc_logic > &)
void operator() (::sc_gem5::Process *p, const sc_in< bool > &)
void operator() (::sc_gem5::Process *p, const sc_in< sc_dt::sc_logic > &)
void operator() (::sc_gem5::Process *p, const sc_inout< bool > &)
void operator() (::sc_gem5::Process *p, const sc_inout< sc_dt::sc_logic > &)
void operator() (::sc_gem5::Process *p, sc_event_finder &)
Private Member Functions
void finalize ()
sc_sensitive ()
Private Attributes
::sc_gem5::Process * currentProcess
Friends
class sc_module
Detailed Description
Definition at line 65 of file sc_sensitive.hh.
Constructor & Destructor Documentation
sc_sensitive()
sc_core::sc_sensitive::sc_sensitive () private
Definition at line 55 of file sc_sensitive.cc.
Member Function Documentation
finalize()
void sc_core::sc_sensitive::finalize () private
operator()() [1/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_signal_in_if< bool > & i)
Definition at line 98 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityEvent(), and sc_core::sc_signal_in_if< bool >::posedge_event().
operator()() [2/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_signal_in_if< sc_dt::sc_logic > & i)
Definition at line 106 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityEvent(), and sc_core::sc_signal_in_if< sc_dt::sc_logic >::posedge_event().
operator()() [3/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_in< bool > & port)
Definition at line 114 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityFinder(), and sc_core::sc_in< bool >::pos().
operator()() [4/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_in< sc_dt::sc_logic > & port)
Definition at line 121 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityFinder(), and sc_core::sc_in< sc_dt::sc_logic >::pos().
operator()() [5/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_inout< bool > & port)
Definition at line 129 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityFinder(), and sc_core::sc_inout< bool >::pos().
operator()() [6/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, const sc_inout< sc_dt::sc_logic > & port)
Definition at line 136 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityFinder(), and sc_core::sc_inout< sc_dt::sc_logic >::pos().
operator()() [7/7]
void sc_core::sc_sensitive::operator() (::sc_gem5::Process * p, sc_event_finder & f)
Definition at line 144 of file sc_sensitive.cc.
References sc_gem5::newStaticSensitivityFinder().
operator<<() [1/5]
sc_sensitive & sc_core::sc_sensitive::operator<< (const sc_event & e)
Definition at line 58 of file sc_sensitive.cc.
References currentProcess, and sc_gem5::newStaticSensitivityEvent().
operator<<() [2/5]
sc_sensitive & sc_core::sc_sensitive::operator<< (const sc_interface & i)
Definition at line 66 of file sc_sensitive.cc.
References currentProcess, and sc_gem5::newStaticSensitivityInterface().
operator<<() [3/5]
sc_sensitive & sc_core::sc_sensitive::operator<< (const sc_port_base & b)
Definition at line 74 of file sc_sensitive.cc.
References currentProcess, and sc_gem5::newStaticSensitivityPort().
operator<<() [4/5]
sc_sensitive & sc_core::sc_sensitive::operator<< (sc_event_finder & f)
Definition at line 82 of file sc_sensitive.cc.
References currentProcess, and sc_gem5::newStaticSensitivityFinder().
operator<<() [5/5]
sc_sensitive & sc_core::sc_sensitive::operator<< (::sc_gem5::Process * p)
Definition at line 90 of file sc_sensitive.cc.
References currentProcess, and MipsISA::p.
Friends And Related Function Documentation
sc_module
friend class sc_module friend
Definition at line 87 of file sc_sensitive.hh.
Member Data Documentation
currentProcess
::sc_gem5::Process* sc_core::sc_sensitive::currentProcess private
Definition at line 96 of file sc_sensitive.hh.
Referenced by operator<<().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_sensitive.hh
systemc/core/sc_sensitive.cc