gem5: MultiperspectivePerceptron64KB Class Reference
MultiperspectivePerceptron64KB Class Reference
#include <multiperspective_perceptron_64KB.hh>
Public Member Functions
MultiperspectivePerceptron64KB (const MultiperspectivePerceptron64KBParams *p)
Public Member Functions inherited from MultiperspectivePerceptron
MultiperspectivePerceptron (const MultiperspectivePerceptronParams *params)
void setExtraBits (int bits)
Sets the starting number of storage bits to compute the number of table entries.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void uncondBranch (ThreadID tid, Addr pc, void *&bp_history) override
void squash (ThreadID tid, void *bp_history) override
bool lookup (ThreadID tid, Addr instPC, void *&bp_history) override
Looks up a given PC in the BP to see if it is taken or not taken.
void update (ThreadID tid, Addr instPC, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst, Addr corrTarget=MaxAddr) override
Updates the BP with taken/not taken information.
void btbUpdate (ThreadID tid, Addr branch_addr, void *&bp_history) override
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Public Member Functions inherited from BPredUnit
BPredUnit (const Params *p)
void regStats () override
Registers statistics.
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
void createSpecs () override
Creates the tables of the predictor.
Additional Inherited Members
Public Types inherited from BPredUnit
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from MultiperspectivePerceptron
void insertModhistSpec (int p1, int p2)
Auxiliary function for MODHIST and GHISTMODPATH features.
void insertModpathSpec (int p1, int p2)
Auxiliary function for MODPATH and GHISTMODPATH features.
int insert (std::vector< int > &v, int x)
Auxiliary function used by insertModhistSpec and insertModpathSpec.
void computeBits (int num_filter_entries, int nlocal_histories, int local_history_length, bool ignore_path_size)
Computes the size in bits of the structures needed to keep track of the history and the predictor tables and assigns the sizes of those tables that did not had their size specified.
unsigned int getIndex (ThreadID tid, const MPPBranchInfo &bi, const HistorySpec &spec, int index) const
Get the position index of a predictor table.
void findBest (ThreadID tid, std::vector< int > &best_preds) const
Finds the best subset of features to use in case of a low-confidence branch, returns the result as an ordered vector of the indices to the predictor tables.
int computeOutput (ThreadID tid, MPPBranchInfo &bi)
Computes the output of the predictor for a given branch and the resulting best value in case the prediction has low confidence.
void train (ThreadID tid, MPPBranchInfo &bi, bool taken)
Trains the branch predictor with the given branch and direction.
void satIncDec (bool taken, bool &sign, int &c, int max_weight) const
Auxiliary function to increase a table counter depending on the direction of the branch.
void addSpec (HistorySpec *spec)
Add a table spec to the prefetcher.
Protected Member Functions inherited from BPredUnit
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from MultiperspectivePerceptron
const int blockSize
Predictor parameters.
const int pcshift
const int threshold
const int bias0
const int bias1
const int biasmostly0
const int biasmostly1
const int nbest
const int tunebits
const int hshift
const unsigned long long int imli_mask1
const unsigned long long int imli_mask4
const unsigned long long int recencypos_mask
const double fudge
const int n_sign_bits
const int pcbit
const int decay
const unsigned int record_mask
const bool hash_taken
const bool tuneonly
const int extra_rounds
const int speed
const int budgetbits
const bool speculative_update
std::vector< ThreadData * > threadData
std::vector< HistorySpec * > specs
Predictor tables.
std::vector< int > table_sizes
bool doing_local
runtime values and data used to count the size in bits
bool doing_recency
int assoc
int ghist_length
int modghist_length
int path_length
int thresholdCounter
int theta
int extrabits
std::vector< int > imli_counter_bits
std::vector< int > modhist_indices
std::vector< int > modhist_lengths
std::vector< int > modpath_indices
std::vector< int > modpath_lengths
std::vector< std::vector< int > > blurrypath_bits
std::vector< std::vector< std::vector< bool > > > acyclic_bits
Protected Attributes inherited from BPredUnit
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes inherited from MultiperspectivePerceptron
static int xlat []
Transfer function for 6-width tables.
static int xlat4 []
Transfer function for 5-width tables.
Detailed Description
Definition at line 46 of file multiperspective_perceptron_64KB.hh.
Constructor & Destructor Documentation
MultiperspectivePerceptron64KB()
MultiperspectivePerceptron64KB::MultiperspectivePerceptron64KB (const MultiperspectivePerceptron64KBParams * p)
Definition at line 42 of file multiperspective_perceptron_64KB.cc.
Referenced by createSpecs().
Member Function Documentation
createSpecs()
void MultiperspectivePerceptron64KB::createSpecs () override private virtual
Creates the tables of the predictor.
Implements MultiperspectivePerceptron.
Definition at line 49 of file multiperspective_perceptron_64KB.cc.
References MultiperspectivePerceptron::addSpec(), and MultiperspectivePerceptron64KB().
The documentation for this class was generated from the following files:
cpu/pred/multiperspective_perceptron_64KB.hh
cpu/pred/multiperspective_perceptron_64KB.cc