gem5: BaseInterrupts Class Reference
BaseInterrupts Class Reference abstract
#include <interrupts.hh>
Public Types
typedef BaseInterruptsParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BaseInterrupts (Params *p)
virtual void setCPU (BaseCPU *newCPU)=0
const Params * params () const
virtual bool checkInterrupts (ThreadContext *tc) const =0
virtual Fault getInterrupt (ThreadContext *tc)=0
virtual void updateIntrInfo (ThreadContext *tc)=0
virtual void post (int int_num, int index)
virtual void clear (int int_num, int index)
virtual void clearAll ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
BaseCPU * cpu
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 39 of file interrupts.hh.
Member Typedef Documentation
Params
typedef BaseInterruptsParams BaseInterrupts::Params
Definition at line 45 of file interrupts.hh.
Constructor & Destructor Documentation
BaseInterrupts()
BaseInterrupts::BaseInterrupts (Params * p) inline
Definition at line 47 of file interrupts.hh.
References setCPU().
Member Function Documentation
checkInterrupts()
virtual bool BaseInterrupts::checkInterrupts (ThreadContext * tc) const pure virtual
Implemented in X86ISA::Interrupts, AlphaISA::Interrupts, ArmISA::Interrupts, SparcISA::Interrupts, MipsISA::Interrupts, RiscvISA::Interrupts, and PowerISA::Interrupts.
Referenced by params().
clear()
virtual void BaseInterrupts::clear (int int_num, int index) inline virtual
Reimplemented in X86ISA::Interrupts, RiscvISA::Interrupts, SparcISA::Interrupts, ArmISA::Interrupts, AlphaISA::Interrupts, MipsISA::Interrupts, and PowerISA::Interrupts.
Definition at line 86 of file interrupts.hh.
References panic.
clearAll()
virtual void BaseInterrupts::clearAll () inline virtual
Reimplemented in X86ISA::Interrupts, SparcISA::Interrupts, RiscvISA::Interrupts, ArmISA::Interrupts, AlphaISA::Interrupts, MipsISA::Interrupts, and PowerISA::Interrupts.
Definition at line 92 of file interrupts.hh.
References panic.
getInterrupt()
virtual Fault BaseInterrupts::getInterrupt (ThreadContext * tc) pure virtual
Implemented in X86ISA::Interrupts, ArmISA::Interrupts, SparcISA::Interrupts, AlphaISA::Interrupts, MipsISA::Interrupts, RiscvISA::Interrupts, and PowerISA::Interrupts.
Referenced by params(), and Minor::Execute::takeInterrupt().
params()
const Params* BaseInterrupts::params () const inline
Definition at line 52 of file interrupts.hh.
References SimObject::_params, checkInterrupts(), getInterrupt(), and updateIntrInfo().
post()
virtual void BaseInterrupts::post (int int_num, int index) inline virtual
Reimplemented in X86ISA::Interrupts, RiscvISA::Interrupts, SparcISA::Interrupts, ArmISA::Interrupts, AlphaISA::Interrupts, MipsISA::Interrupts, and PowerISA::Interrupts.
Definition at line 80 of file interrupts.hh.
References panic.
setCPU()
virtual void BaseInterrupts::setCPU (BaseCPU * newCPU) pure virtual
Implemented in X86ISA::Interrupts, AlphaISA::Interrupts, RiscvISA::Interrupts, ArmISA::Interrupts, SparcISA::Interrupts, MipsISA::Interrupts, and PowerISA::Interrupts.
Referenced by BaseInterrupts().
updateIntrInfo()
virtual void BaseInterrupts::updateIntrInfo (ThreadContext * tc) pure virtual
Implemented in X86ISA::Interrupts, ArmISA::Interrupts, SparcISA::Interrupts, AlphaISA::Interrupts, MipsISA::Interrupts, RiscvISA::Interrupts, and PowerISA::Interrupts.
Referenced by params(), and Minor::Execute::takeInterrupt().
Member Data Documentation
cpu
BaseCPU* BaseInterrupts::cpu protected
Definition at line 42 of file interrupts.hh.
The documentation for this class was generated from the following file:
arch/generic/interrupts.hh