gem5: sc_core::sc_signal_write_if< T > Class Template Reference
sc_core::sc_signal_write_if< T > Class Template Reference abstract
#include <sc_signal_inout_if.hh>
Public Member Functions
virtual sc_writer_policy get_writer_policy () const
virtual void write (const T &)=0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_signal_write_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_signal_write_if (const sc_signal_write_if< T > &)
sc_signal_write_if< T > & operator= (const sc_signal_write_if< T > &)
Detailed Description
template<class T>
class sc_core::sc_signal_write_if< T >
Definition at line 46 of file sc_signal_inout_if.hh.
Constructor & Destructor Documentation
sc_signal_write_if() [1/2]
template<class T> sc_core::sc_signal_write_if< T >::sc_signal_write_if () inline protected
Definition at line 57 of file sc_signal_inout_if.hh.
sc_signal_write_if() [2/2]
template<class T> sc_core::sc_signal_write_if< T >::sc_signal_write_if (const sc_signal_write_if< T > &) inline private
Definition at line 61 of file sc_signal_inout_if.hh.
Member Function Documentation
get_writer_policy()
template<class T> virtual sc_writer_policy sc_core::sc_signal_write_if< T >::get_writer_policy () const inline virtual
Reimplemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >, and sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >.
Definition at line 50 of file sc_signal_inout_if.hh.
operator=()
template<class T> sc_signal_write_if<T>& sc_core::sc_signal_write_if< T >::operator= (const sc_signal_write_if< T > &) inline private
Definition at line 63 of file sc_signal_inout_if.hh.
write()
template<class T> virtual void sc_core::sc_signal_write_if< T >::write (const T &) pure virtual
Implemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >, sc_core::sc_signal< sc_dt::sc_biguint< W > >, sc_core::sc_signal< sc_dt::sc_uint< W > >, sc_core::sc_signal< sc_dt::sc_int< W > >, sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >, sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >, sc_core::sc_clock, sc_core::sc_signal_rv< W >, sc_core::sc_signal_resolved, and sc_core::sc_buffer< T, WRITER_POLICY >.
Referenced by sc_core::sc_signal_write_if< sc_dt::sc_uint< W > >::get_writer_policy(), sc_core::sc_inout< sc_dt::sc_int< W > >::initialize(), sc_core::sc_inout< sc_dt::sc_uint< W > >::initialize(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::initialize(), and sc_core::sc_inout< sc_dt::sc_bigint< W > >::initialize().
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_signal_inout_if.hh