gem5: ROB< Impl > Class Template Reference
ROB< Impl > Class Template Reference
ROB class.
#include <rob.hh>
Public Types
enum Status { Running, Idle, ROBSquashing }
Possible ROB statuses.
typedef Impl::O3CPU O3CPU
typedef Impl::DynInstPtr DynInstPtr
typedef std::pair< RegIndex, PhysRegIndex > UnmapInfo
typedef std::list< DynInstPtr >::iterator InstIt
Public Member Functions
ROB (O3CPU *_cpu, DerivO3CPUParams *params)
ROB constructor.
std::string name () const
void setActiveThreads (std::list< ThreadID > *at_ptr)
Sets pointer to the list of active threads.
void drainSanityCheck () const
Perform sanity checks after a drain.
void takeOverFrom ()
Takes over another CPU's thread.
void insertInst (const DynInstPtr &inst)
Function to insert an instruction into the ROB.
const DynInstPtr & readHeadInst (ThreadID tid)
Returns pointer to the head instruction within the ROB.
DynInstPtr findInst (ThreadID tid, InstSeqNum squash_inst)
Returns a pointer to the instruction with the given sequence if it is in the ROB.
DynInstPtr readTailInst (ThreadID tid)
Returns pointer to the tail instruction within the ROB.
void retireHead (ThreadID tid)
Retires the head instruction, removing it from the ROB.
bool isHeadReady (ThreadID tid)
Is the oldest instruction across all threads ready.
bool canCommit ()
Is there any commitable head instruction across all threads ready.
void resetEntries ()
Re-adjust ROB partitioning.
int entryAmount (ThreadID num_threads)
Number of entries needed For 'num_threads' amount of threads.
unsigned numFreeEntries ()
Returns the number of total free entries in the ROB.
unsigned numFreeEntries (ThreadID tid)
Returns the number of free entries in a specific ROB paritition.
unsigned getMaxEntries (ThreadID tid)
Returns the maximum number of entries for a specific thread.
unsigned getThreadEntries (ThreadID tid)
Returns the number of entries being used by a specific thread.
bool isFull ()
Returns if the ROB is full.
bool isFull (ThreadID tid)
Returns if a specific thread's partition is full.
bool isEmpty () const
Returns if the ROB is empty.
bool isEmpty (ThreadID tid) const
Returns if a specific thread's partition is empty.
void doSquash (ThreadID tid)
Executes the squash, marking squashed instructions.
void squash (InstSeqNum squash_num, ThreadID tid)
Squashes all instructions younger than the given sequence number for the specific thread.
void updateHead ()
Updates the head instruction with the new oldest instruction.
void updateTail ()
Updates the tail instruction with the new youngest instruction.
bool isDoneSquashing (ThreadID tid) const
Reads the PC of the oldest head instruction.
bool isDoneSquashing ()
Checks if the ROB is still in the process of squashing instructions for any thread.
int countInsts ()
This is more of a debugging function than anything.
size_t countInsts (ThreadID tid)
This is more of a debugging function than anything.
void regStats ()
Registers statistics.
Public Attributes
InstIt tail
Iterator pointing to the instruction which is the last instruction in the ROB.
InstIt head
Iterator pointing to the instruction which is the first instruction in in the ROB.
int numInstsInROB
Number of instructions in the ROB.
DynInstPtr dummyInst
Dummy instruction returned if there are no insts left.
Private Member Functions
void resetState ()
Reset the ROB state.
Private Attributes
Status robStatus [Impl::MaxThreads]
Per-thread ROB status.
SMTQueuePolicy robPolicy
ROB resource sharing policy for SMT mode.
O3CPU * cpu
Pointer to the CPU.
std::list< ThreadID > * activeThreads
Active Threads in CPU.
unsigned numEntries
Number of instructions in the ROB.
unsigned threadEntries [Impl::MaxThreads]
Entries Per Thread.
unsigned maxEntries [Impl::MaxThreads]
Max Insts a Thread Can Have in the ROB.
std::list< DynInstPtr > instList [Impl::MaxThreads]
ROB List of Instructions.
unsigned squashWidth
Number of instructions that can be squashed in a single cycle.
InstIt squashIt [Impl::MaxThreads]
Iterator used for walking through the list of instructions when squashing.
InstSeqNum squashedSeqNum [Impl::MaxThreads]
The sequence number of the squashed instruction.
bool doneSquashing [Impl::MaxThreads]
Is the ROB done squashing.
ThreadID numThreads
Number of active threads.
Stats::Scalar robReads
Stats::Scalar robWrites
Detailed Description
template<class Impl>
class ROB< Impl >
ROB class.
The ROB is largely what drives squashing.
Definition at line 62 of file rob.hh.
Member Typedef Documentation
DynInstPtr
template<class Impl > typedef Impl::DynInstPtr ROB< Impl >::DynInstPtr
Definition at line 67 of file rob.hh.
InstIt
template<class Impl > typedef std::list<DynInstPtr>::iterator ROB< Impl >::InstIt
Definition at line 70 of file rob.hh.
O3CPU
template<class Impl > typedef Impl::O3CPU ROB< Impl >::O3CPU
Definition at line 66 of file rob.hh.
UnmapInfo
template<class Impl > typedef std::pair<RegIndex, PhysRegIndex> ROB< Impl >::UnmapInfo
Definition at line 69 of file rob.hh.
Member Enumeration Documentation
Status
template<class Impl > enum ROB::Status
Possible ROB statuses.
Enumerator
Running
Idle
ROBSquashing
Definition at line 73 of file rob.hh.
Constructor & Destructor Documentation
ROB()
template<class Impl > ROB< Impl >::ROB (O3CPU * _cpu, DerivO3CPUParams * params)
ROB constructor.
Parameters
_cpu The cpu object pointer.
params The cpu params including several ROB-specific parameters.
Definition at line 58 of file rob_impl.hh.
References DPRINTF, ROB< Impl >::maxEntries, ROB< Impl >::numEntries, ROB< Impl >::numThreads, ROB< Impl >::resetState(), and ROB< Impl >::robPolicy.
Member Function Documentation
canCommit()
template<class Impl > bool ROB< Impl >::canCommit ()
Is there any commitable head instruction across all threads ready.
Definition at line 290 of file rob_impl.hh.
References ROB< Impl >::activeThreads, and ROB< Impl >::isHeadReady().
countInsts() [1/2]
template<class Impl > int ROB< Impl >::countInsts ()
This is more of a debugging function than anything.
Use numInstsInROB to get the instructions in the ROB unless you are double checking that variable.
Definition at line 187 of file rob_impl.hh.
References ROB< Impl >::numThreads, and Stats::total.
Referenced by ROB< Impl >::isDoneSquashing(), and DefaultCommit< Impl >::tick().
countInsts() [2/2]
template<class Impl > size_t ROB< Impl >::countInsts (ThreadID tid)
This is more of a debugging function than anything.
Use threadEntries to get the instructions in the ROB unless you are double checking that variable.
Definition at line 199 of file rob_impl.hh.
References ROB< Impl >::instList.
doSquash()
template<class Impl > void ROB< Impl >::doSquash (ThreadID tid)
Executes the squash, marking squashed instructions.
Definition at line 323 of file rob_impl.hh.
References ROB< Impl >::doneSquashing, DPRINTF, ROB< Impl >::instList, ROB< Impl >::robWrites, ROB< Impl >::squashedSeqNum, ROB< Impl >::squashIt, ROB< Impl >::squashWidth, and ROB< Impl >::updateTail().
Referenced by ROB< Impl >::isEmpty(), ROB< Impl >::squash(), and DefaultCommit< Impl >::tick().
drainSanityCheck()
template<class Impl > void ROB< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 137 of file rob_impl.hh.
References ROB< Impl >::instList, ROB< Impl >::isEmpty(), and ROB< Impl >::numThreads.
Referenced by DefaultCommit< Impl >::drainSanityCheck().
entryAmount()
template<class Impl > int ROB< Impl >::entryAmount (ThreadID num_threads)
Number of entries needed For 'num_threads' amount of threads.
Definition at line 176 of file rob_impl.hh.
References ROB< Impl >::numEntries, and ROB< Impl >::robPolicy.
findInst()
template<class Impl > Impl::DynInstPtr ROB< Impl >::findInst (ThreadID tid, InstSeqNum squash_inst)
Returns a pointer to the instruction with the given sequence if it is in the ROB.
Definition at line 549 of file rob_impl.hh.
References ROB< Impl >::instList.
Referenced by DefaultCommit< Impl >::commit().
getMaxEntries()
template<class Impl > unsigned ROB< Impl >::getMaxEntries (ThreadID tid) inline
Returns the maximum number of entries for a specific thread.
Definition at line 172 of file rob.hh.
References ROB< Impl >::maxEntries.
Referenced by DefaultCommit< Impl >::getInsts().
getThreadEntries()
template<class Impl > unsigned ROB< Impl >::getThreadEntries (ThreadID tid) inline
Returns the number of entries being used by a specific thread.
Definition at line 176 of file rob.hh.
References ROB< Impl >::threadEntries.
Referenced by DefaultCommit< Impl >::getInsts().
insertInst()
template<class Impl > void ROB< Impl >::insertInst (const DynInstPtr & inst)
Function to insert an instruction into the ROB.
Note that whatever calls this function must ensure that there is enough space within the ROB for the new instruction.
Parameters
inst The instruction being inserted into the ROB.
Definition at line 206 of file rob_impl.hh.
References DPRINTF, ROB< Impl >::head, ROB< Impl >::instList, ROB< Impl >::numEntries, ROB< Impl >::numInstsInROB, ROB< Impl >::robWrites, ROB< Impl >::tail, and ROB< Impl >::threadEntries.
Referenced by DefaultCommit< Impl >::getInsts().
isDoneSquashing() [1/2]
template<class Impl > bool ROB< Impl >::isDoneSquashing (ThreadID tid) const inline
Reads the PC of the oldest head instruction.
Reads the PC of the head instruction of a specific thread. Reads the next PC of the oldest head instruction. Reads the next PC of the head instruction of a specific thread. Reads the sequence number of the oldest head instruction. Reads the sequence number of the head instruction of a specific thread.Reads the PC of the youngest tail instruction. Reads the PC of the tail instruction of a specific thread. Reads the sequence number of the youngest tail instruction. Reads the sequence number of tail instruction of a specific thread. Checks if the ROB is still in the process of squashing instructions.
Return values
Whether or not the ROB is done squashing.
Definition at line 243 of file rob.hh.
References ROB< Impl >::countInsts(), ROB< Impl >::doneSquashing, ROB< Impl >::isDoneSquashing(), ROB< Impl >::regStats(), and ROB< Impl >::resetState().
Referenced by DefaultCommit< Impl >::tick().
isDoneSquashing() [2/2]
template<class Impl > bool ROB< Impl >::isDoneSquashing ()
Checks if the ROB is still in the process of squashing instructions for any thread.
Referenced by ROB< Impl >::isDoneSquashing().
isEmpty() [1/2]
template<class Impl > bool ROB< Impl >::isEmpty () const inline
Returns if the ROB is empty.
Definition at line 188 of file rob.hh.
References ROB< Impl >::numInstsInROB.
Referenced by DefaultCommit< Impl >::commit(), ROB< Impl >::drainSanityCheck(), DefaultCommit< Impl >::isDrained(), DefaultCommit< Impl >::oldestReady(), ROB< Impl >::squash(), DefaultCommit< Impl >::squashAll(), and DefaultCommit< Impl >::tick().
isEmpty() [2/2]
template<class Impl > bool ROB< Impl >::isEmpty (ThreadID tid) const inline
Returns if a specific thread's partition is empty.
Definition at line 192 of file rob.hh.
References ROB< Impl >::doSquash(), ROB< Impl >::squash(), ROB< Impl >::threadEntries, ROB< Impl >::updateHead(), and ROB< Impl >::updateTail().
isFull() [1/2]
template<class Impl > bool ROB< Impl >::isFull () inline
Returns if the ROB is full.
Definition at line 180 of file rob.hh.
References ROB< Impl >::numEntries, and ROB< Impl >::numInstsInROB.
isFull() [2/2]
template<class Impl > bool ROB< Impl >::isFull (ThreadID tid) inline
Returns if a specific thread's partition is full.
Definition at line 184 of file rob.hh.
References ROB< Impl >::numEntries, and ROB< Impl >::threadEntries.
isHeadReady()
template<class Impl > bool ROB< Impl >::isHeadReady (ThreadID tid)
Is the oldest instruction across all threads ready.
Is the oldest instruction across a particular thread ready.
Definition at line 278 of file rob_impl.hh.
References ROB< Impl >::instList, ROB< Impl >::robReads, and ROB< Impl >::threadEntries.
Referenced by ROB< Impl >::canCommit(), DefaultCommit< Impl >::commitInsts(), DefaultCommit< Impl >::oldestReady(), and DefaultCommit< Impl >::roundRobin().
name()
template<class Impl > std::string ROB< Impl >::name () const
Definition at line 122 of file rob_impl.hh.
References ROB< Impl >::cpu.
Referenced by ROB< Impl >::regStats().
numFreeEntries() [1/2]
template<class Impl > unsigned ROB< Impl >::numFreeEntries ()
Returns the number of total free entries in the ROB.
Definition at line 309 of file rob_impl.hh.
References ROB< Impl >::numEntries, and ROB< Impl >::numInstsInROB.
Referenced by DefaultCommit< Impl >::commit(), DefaultCommit< Impl >::numROBFreeEntries(), DefaultCommit< Impl >::startupStage(), and DefaultCommit< Impl >::tick().
numFreeEntries() [2/2]
template<class Impl > unsigned ROB< Impl >::numFreeEntries (ThreadID tid)
Returns the number of free entries in a specific ROB paritition.
Definition at line 316 of file rob_impl.hh.
References ROB< Impl >::maxEntries, and ROB< Impl >::threadEntries.
readHeadInst()
template<class Impl > const Impl::DynInstPtr & ROB< Impl >::readHeadInst (ThreadID tid)
Returns pointer to the head instruction within the ROB.
There is no guarantee as to the return value if the ROB is empty.
Return values
Pointer to the DynInst that is at the head of the ROB.Returns a pointer to the head instruction of a specific thread within the ROB.
Returns
Pointer to the DynInst that is at the head of the ROB.
Definition at line 510 of file rob_impl.hh.
References ROB< Impl >::dummyInst, ROB< Impl >::instList, and ROB< Impl >::threadEntries.
Referenced by DefaultCommit< Impl >::commitInsts(), DefaultCommit< Impl >::oldestReady(), DefaultCommit< Impl >::squashAll(), and DefaultCommit< Impl >::tick().
readTailInst()
template<class Impl > Impl::DynInstPtr ROB< Impl >::readTailInst (ThreadID tid)
Returns pointer to the tail instruction within the ROB.
There is no guarantee as to the return value if the ROB is empty.
Return values
Pointer to the DynInst that is at the tail of the ROB.Returns a pointer to the tail instruction of a specific thread within the ROB.
Returns
Pointer to the DynInst that is at the tail of the ROB.
Definition at line 525 of file rob_impl.hh.
References ROB< Impl >::instList.
regStats()
template<class Impl > void ROB< Impl >::regStats ()
Registers statistics.
Definition at line 535 of file rob_impl.hh.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), ROB< Impl >::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), ROB< Impl >::robReads, and ROB< Impl >::robWrites.
Referenced by ROB< Impl >::isDoneSquashing().
resetEntries()
template<class Impl > void ROB< Impl >::resetEntries ()
Re-adjust ROB partitioning.
Definition at line 153 of file rob_impl.hh.
References ROB< Impl >::activeThreads, ROB< Impl >::maxEntries, ROB< Impl >::numEntries, ROB< Impl >::numThreads, and ROB< Impl >::robPolicy.
Referenced by DefaultCommit< Impl >::startupStage().
resetState()
template<class Impl > void ROB< Impl >::resetState () private
Reset the ROB state.
Definition at line 104 of file rob_impl.hh.
References ROB< Impl >::doneSquashing, ROB< Impl >::head, ROB< Impl >::instList, ROB< Impl >::numInstsInROB, ROB< Impl >::squashedSeqNum, ROB< Impl >::squashIt, ROB< Impl >::tail, and ROB< Impl >::threadEntries.
Referenced by ROB< Impl >::isDoneSquashing(), ROB< Impl >::ROB(), and ROB< Impl >::takeOverFrom().
retireHead()
template<class Impl > void ROB< Impl >::retireHead (ThreadID tid)
Retires the head instruction, removing it from the ROB.
Retires the head instruction of a specific thread, removing it from the ROB.
Definition at line 243 of file rob_impl.hh.
References ROB< Impl >::cpu, DPRINTF, ROB< Impl >::instList, ROB< Impl >::numInstsInROB, ROB< Impl >::robWrites, ROB< Impl >::threadEntries, and ROB< Impl >::updateHead().
Referenced by DefaultCommit< Impl >::commitHead(), and DefaultCommit< Impl >::commitInsts().
setActiveThreads()
template<class Impl > void ROB< Impl >::setActiveThreads (std::list< ThreadID > * at_ptr)
Sets pointer to the list of active threads.
Parameters
at_ptr Pointer to the list of active threads.
Definition at line 129 of file rob_impl.hh.
References ROB< Impl >::activeThreads, and DPRINTF.
Referenced by DefaultCommit< Impl >::startupStage().
squash()
template<class Impl > void ROB< Impl >::squash (InstSeqNum squash_num, ThreadID tid)
Squashes all instructions younger than the given sequence number for the specific thread.
Definition at line 480 of file rob_impl.hh.
References ROB< Impl >::doneSquashing, ROB< Impl >::doSquash(), DPRINTF, ROB< Impl >::instList, ROB< Impl >::isEmpty(), ROB< Impl >::ROBSquashing, ROB< Impl >::robStatus, ROB< Impl >::squashedSeqNum, and ROB< Impl >::squashIt.
Referenced by DefaultCommit< Impl >::commit(), ROB< Impl >::isEmpty(), and DefaultCommit< Impl >::squashAll().
takeOverFrom()
template<class Impl > void ROB< Impl >::takeOverFrom ()
Takes over another CPU's thread.
Definition at line 146 of file rob_impl.hh.
References ROB< Impl >::resetState().
Referenced by DefaultCommit< Impl >::takeOverFrom().
updateHead()
template<class Impl > void ROB< Impl >::updateHead ()
Updates the head instruction with the new oldest instruction.
Definition at line 400 of file rob_impl.hh.
References ROB< Impl >::activeThreads, ROB< Impl >::head, and ROB< Impl >::instList.
Referenced by ROB< Impl >::isEmpty(), and ROB< Impl >::retireHead().
updateTail()
template<class Impl > void ROB< Impl >::updateTail ()
Updates the tail instruction with the new youngest instruction.
Definition at line 442 of file rob_impl.hh.
References ROB< Impl >::activeThreads, ROB< Impl >::instList, and ROB< Impl >::tail.
Referenced by ROB< Impl >::doSquash(), and ROB< Impl >::isEmpty().
Member Data Documentation
activeThreads
template<class Impl > std::list<ThreadID>* ROB< Impl >::activeThreads private
Active Threads in CPU.
Definition at line 274 of file rob.hh.
Referenced by ROB< Impl >::canCommit(), ROB< Impl >::resetEntries(), ROB< Impl >::setActiveThreads(), ROB< Impl >::updateHead(), and ROB< Impl >::updateTail().
cpu
template<class Impl > O3CPU* ROB< Impl >::cpu private
Pointer to the CPU.
Definition at line 271 of file rob.hh.
Referenced by ROB< Impl >::name(), and ROB< Impl >::retireHead().
doneSquashing
template<class Impl > bool ROB< Impl >::doneSquashing[Impl::MaxThreads] private
Is the ROB done squashing.
Definition at line 324 of file rob.hh.
Referenced by ROB< Impl >::doSquash(), ROB< Impl >::isDoneSquashing(), ROB< Impl >::resetState(), and ROB< Impl >::squash().
dummyInst
template<class Impl > DynInstPtr ROB< Impl >::dummyInst
Dummy instruction returned if there are no insts left.
Definition at line 317 of file rob.hh.
Referenced by ROB< Impl >::readHeadInst().
head
template<class Impl > InstIt ROB< Impl >::head
Iterator pointing to the instruction which is the first instruction in in the ROB.
Definition at line 300 of file rob.hh.
Referenced by ROB< Impl >::insertInst(), ROB< Impl >::resetState(), and ROB< Impl >::updateHead().
instList
template<class Impl > std::list<DynInstPtr> ROB< Impl >::instList[Impl::MaxThreads] private
ROB List of Instructions.
Definition at line 286 of file rob.hh.
Referenced by ROB< Impl >::countInsts(), ROB< Impl >::doSquash(), ROB< Impl >::drainSanityCheck(), ROB< Impl >::findInst(), ROB< Impl >::insertInst(), ROB< Impl >::isHeadReady(), ROB< Impl >::readHeadInst(), ROB< Impl >::readTailInst(), ROB< Impl >::resetState(), ROB< Impl >::retireHead(), ROB< Impl >::squash(), ROB< Impl >::updateHead(), and ROB< Impl >::updateTail().
maxEntries
template<class Impl > unsigned ROB< Impl >::maxEntries[Impl::MaxThreads] private
Max Insts a Thread Can Have in the ROB.
Definition at line 283 of file rob.hh.
Referenced by ROB< Impl >::getMaxEntries(), ROB< Impl >::numFreeEntries(), ROB< Impl >::resetEntries(), and ROB< Impl >::ROB().
numEntries
template<class Impl > unsigned ROB< Impl >::numEntries private
Number of instructions in the ROB.
Definition at line 277 of file rob.hh.
Referenced by ROB< Impl >::entryAmount(), ROB< Impl >::insertInst(), ROB< Impl >::isFull(), ROB< Impl >::numFreeEntries(), ROB< Impl >::resetEntries(), and ROB< Impl >::ROB().
numInstsInROB
template<class Impl > int ROB< Impl >::numInstsInROB
Number of instructions in the ROB.
Definition at line 314 of file rob.hh.
Referenced by ROB< Impl >::insertInst(), ROB< Impl >::isEmpty(), ROB< Impl >::isFull(), ROB< Impl >::numFreeEntries(), ROB< Impl >::resetState(), and ROB< Impl >::retireHead().
numThreads
template<class Impl > ThreadID ROB< Impl >::numThreads private
Number of active threads.
Definition at line 327 of file rob.hh.
Referenced by ROB< Impl >::countInsts(), ROB< Impl >::drainSanityCheck(), ROB< Impl >::resetEntries(), and ROB< Impl >::ROB().
robPolicy
template<class Impl > SMTQueuePolicy ROB< Impl >::robPolicy private
ROB resource sharing policy for SMT mode.
Definition at line 84 of file rob.hh.
Referenced by ROB< Impl >::entryAmount(), ROB< Impl >::resetEntries(), and ROB< Impl >::ROB().
robReads
template<class Impl > Stats::Scalar ROB< Impl >::robReads private
Definition at line 330 of file rob.hh.
Referenced by ROB< Impl >::isHeadReady(), and ROB< Impl >::regStats().
robStatus
template<class Impl > Status ROB< Impl >::robStatus[Impl::MaxThreads] private
Per-thread ROB status.
Definition at line 81 of file rob.hh.
Referenced by ROB< Impl >::squash().
robWrites
template<class Impl > Stats::Scalar ROB< Impl >::robWrites private
Definition at line 332 of file rob.hh.
Referenced by ROB< Impl >::doSquash(), ROB< Impl >::insertInst(), ROB< Impl >::regStats(), and ROB< Impl >::retireHead().
squashedSeqNum
template<class Impl > InstSeqNum ROB< Impl >::squashedSeqNum[Impl::MaxThreads] private
The sequence number of the squashed instruction.
Definition at line 321 of file rob.hh.
Referenced by ROB< Impl >::doSquash(), ROB< Impl >::resetState(), and ROB< Impl >::squash().
squashIt
template<class Impl > InstIt ROB< Impl >::squashIt[Impl::MaxThreads] private
Iterator used for walking through the list of instructions when squashing.
Used so that there is persistent state between cycles; when squashing, the instructions are marked as squashed but not immediately removed, meaning the tail iterator remains the same before and after a squash. This will always be set to cpu->instList.end() if it is invalid.
Definition at line 310 of file rob.hh.
Referenced by ROB< Impl >::doSquash(), ROB< Impl >::resetState(), and ROB< Impl >::squash().
squashWidth
template<class Impl > unsigned ROB< Impl >::squashWidth private
Number of instructions that can be squashed in a single cycle.
Definition at line 289 of file rob.hh.
Referenced by ROB< Impl >::doSquash().
tail
template<class Impl > InstIt ROB< Impl >::tail
Iterator pointing to the instruction which is the last instruction in the ROB.
This may at times be invalid (ie when the ROB is empty), however it should never be incorrect.
Definition at line 296 of file rob.hh.
Referenced by ROB< Impl >::insertInst(), ROB< Impl >::resetState(), and ROB< Impl >::updateTail().
threadEntries
template<class Impl > unsigned ROB< Impl >::threadEntries[Impl::MaxThreads] private
Entries Per Thread.
Definition at line 280 of file rob.hh.
Referenced by ROB< Impl >::getThreadEntries(), ROB< Impl >::insertInst(), ROB< Impl >::isEmpty(), ROB< Impl >::isFull(), ROB< Impl >::isHeadReady(), ROB< Impl >::numFreeEntries(), ROB< Impl >::readHeadInst(), ROB< Impl >::resetState(), and ROB< Impl >::retireHead().
The documentation for this class was generated from the following files:
cpu/o3/rob.hh
cpu/o3/rob_impl.hh