gem5: sc_dt::sc_logic Class Reference
sc_dt::sc_logic Class Reference
#include <sc_logic.hh>
Public Member Functions
sc_logic ()
sc_logic (const sc_logic &a)
sc_logic (sc_logic_value_t v)
sc_logic (bool a)
sc_logic (char a)
sc_logic (int a)
sc_logic (const sc_bit &a)
~sc_logic ()
sc_logic & operator= (const sc_logic &a)
sc_logic & operator&= (const sc_logic &b)
sc_logic & operator|= (const sc_logic &b)
sc_logic & operator^= (const sc_logic &b)
const sc_logic operator~ () const
sc_logic & b_not ()
sc_logic_value_t value () const
bool is_01 () const
bool to_bool () const
char to_char () const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Static Public Member Functions
static void * operator new (std::size_t, void *p)
static void * operator new (std::size_t sz)
static void operator delete (void *p, std::size_t sz)
static void * operator new [] (std::size_t sz)
static void operator delete [] (void *p, std::size_t sz)
Static Public Attributes
static const sc_logic_value_t char_to_logic [128]
static const char logic_to_char [4] = { '0', '1', 'Z', 'X' }
static const sc_logic_value_t and_table [4][4]
static const sc_logic_value_t or_table [4][4]
static const sc_logic_value_t xor_table [4][4]
static const sc_logic_value_t not_table [4]
Private Member Functions
void invalid_01 () const
sc_logic (const char *)
sc_logic & operator= (const char *)
Static Private Member Functions
static void invalid_value (sc_logic_value_t)
static void invalid_value (char)
static void invalid_value (int)
static sc_logic_value_t to_value (sc_logic_value_t v)
static sc_logic_value_t to_value (bool b)
static sc_logic_value_t to_value (char c)
static sc_logic_value_t to_value (int i)
Private Attributes
sc_logic_value_t m_val
Friends
const sc_logic operator& (const sc_logic &, const sc_logic &)
const sc_logic operator| (const sc_logic &, const sc_logic &)
const sc_logic operator^ (const sc_logic &, const sc_logic &)
bool operator== (const sc_logic &, const sc_logic &)
bool operator!= (const sc_logic &, const sc_logic &)
Detailed Description
Definition at line 98 of file sc_logic.hh.
Constructor & Destructor Documentation
sc_logic() [1/8]
sc_dt::sc_logic::sc_logic () inline
Definition at line 154 of file sc_logic.hh.
Referenced by sc_dt::operator&(), sc_dt::operator^(), sc_dt::operator|(), and operator~().
sc_logic() [2/8]
sc_dt::sc_logic::sc_logic (const sc_logic & a) inline
Definition at line 155 of file sc_logic.hh.
sc_logic() [3/8]
sc_dt::sc_logic::sc_logic (sc_logic_value_t v) inline
Definition at line 156 of file sc_logic.hh.
sc_logic() [4/8]
sc_dt::sc_logic::sc_logic (bool a) inline explicit
Definition at line 157 of file sc_logic.hh.
sc_logic() [5/8]
sc_dt::sc_logic::sc_logic (char a) inline explicit
Definition at line 158 of file sc_logic.hh.
sc_logic() [6/8]
sc_dt::sc_logic::sc_logic (int a) inline explicit
Definition at line 159 of file sc_logic.hh.
sc_logic() [7/8]
sc_dt::sc_logic::sc_logic (const sc_bit & a) inline explicit
Definition at line 160 of file sc_logic.hh.
~sc_logic()
sc_dt::sc_logic::~sc_logic () inline
Definition at line 163 of file sc_logic.hh.
sc_logic() [8/8]
sc_dt::sc_logic::sc_logic (const char *) explicit private
Member Function Documentation
b_not()
sc_logic& sc_dt::sc_logic::b_not () inline
Definition at line 229 of file sc_logic.hh.
References m_val.
invalid_01()
void sc_dt::sc_logic::invalid_01 () const private
Definition at line 89 of file sc_logic.cc.
References and_table, char_to_logic, sc_dt::Log_0, sc_dt::Log_1, sc_dt::Log_X, sc_dt::Log_Z, logic_to_char, m_val, not_table, or_table, sc_core::SC_ID_LOGIC_X_TO_BOOL_, sc_core::SC_ID_LOGIC_Z_TO_BOOL_, SC_REPORT_WARNING, and xor_table.
Referenced by to_bool(), and to_value().
invalid_value() [1/3]
void sc_dt::sc_logic::invalid_value (sc_logic_value_t v) static private
Definition at line 66 of file sc_logic.cc.
Referenced by to_value().
invalid_value() [2/3]
void sc_dt::sc_logic::invalid_value (char c) static private
Definition at line 72 of file sc_logic.cc.
References sc_core::SC_ID_VALUE_NOT_VALID_, and SC_REPORT_ERROR.
invalid_value() [3/3]
void sc_dt::sc_logic::invalid_value (int i) static private
Definition at line 80 of file sc_logic.cc.
References sc_core::SC_ID_VALUE_NOT_VALID_, and SC_REPORT_ERROR.
is_01()
bool sc_dt::sc_logic::is_01 () const inline
Definition at line 238 of file sc_logic.hh.
References sc_dt::Log_0, sc_dt::Log_1, and m_val.
Referenced by sc_dt::sc_bitref_r< X >::is_01(), and to_bool().
operator delete()
static void sc_dt::sc_logic::operator delete (void * p, std::size_t sz) inline static
Definition at line 263 of file sc_logic.hh.
References sc_core::sc_mempool::release().
operator delete []()
static void sc_dt::sc_logic::operator delete [] (void * p, std::size_t sz) inline static
Definition at line 273 of file sc_logic.hh.
References sc_core::sc_mempool::release().
operator new() [1/2]
static void* sc_dt::sc_logic::operator new (std::size_t , void * p) inline static
Definition at line 256 of file sc_logic.hh.
References MipsISA::p.
operator new() [2/2]
static void* sc_dt::sc_logic::operator new (std::size_t sz) inline static
Definition at line 258 of file sc_logic.hh.
References sc_core::sc_mempool::allocate().
operator new []()
static void* sc_dt::sc_logic::operator new [] (std::size_t sz) inline static
Definition at line 268 of file sc_logic.hh.
References sc_core::sc_mempool::allocate().
operator&=()
sc_logic& sc_dt::sc_logic::operator &= (const sc_logic & b) inline
Definition at line 189 of file sc_logic.hh.
References m_val.
operator=() [1/2]
sc_logic& sc_dt::sc_logic::operator= (const sc_logic & a) inline
Definition at line 182 of file sc_logic.hh.
References m_val.
operator=() [2/2]
sc_logic& sc_dt::sc_logic::operator= (const char *) private
operator^=()
sc_logic& sc_dt::sc_logic::operator^= (const sc_logic & b) inline
Definition at line 203 of file sc_logic.hh.
References DEFN_ASN_OP, m_val, operator!=, operator&, operator==, operator^, and operator|.
operator|=()
sc_logic& sc_dt::sc_logic::operator|= (const sc_logic & b) inline
Definition at line 196 of file sc_logic.hh.
References m_val.
operator~()
const sc_logic sc_dt::sc_logic::operator~ () const inline
Definition at line 227 of file sc_logic.hh.
References m_val, and sc_logic().
print()
void sc_dt::sc_logic::print (::std::ostream & os = ::std::cout) const inline
Definition at line 251 of file sc_logic.hh.
References MipsISA::is, X86ISA::os, scan(), and to_char().
Referenced by sc_dt::operator<<().
scan()
void sc_dt::sc_logic::scan (::std::istream & is = ::std::cin)
Definition at line 147 of file sc_logic.cc.
References ArmISA::c, sc_dt::Log_0, sc_dt::Log_1, sc_dt::Log_Z, sc_dt::sc_logic_0, sc_dt::SC_LOGIC_0, sc_dt::sc_logic_1, sc_dt::SC_LOGIC_1, sc_dt::sc_logic_X, sc_dt::SC_LOGIC_X, sc_dt::sc_logic_Z, and sc_dt::SC_LOGIC_Z.
Referenced by sc_dt::operator>>(), and print().
to_bool()
bool sc_dt::sc_logic::to_bool () const inline
Definition at line 240 of file sc_logic.hh.
References invalid_01(), is_01(), sc_dt::Log_0, and m_val.
Referenced by sc_dt::sc_bitref_r< X >::to_bool().
to_char()
char sc_dt::sc_logic::to_char () const inline
Definition at line 248 of file sc_logic.hh.
References m_val.
Referenced by print(), and sc_dt::sc_bitref_r< X >::to_char().
to_value() [1/4]
static sc_logic_value_t sc_dt::sc_logic::to_value (sc_logic_value_t v) inline static private
Definition at line 107 of file sc_logic.hh.
References invalid_value(), sc_dt::Log_X, and ArmISA::v.
to_value() [2/4]
static sc_logic_value_t sc_dt::sc_logic::to_value (bool b) inline static private
Definition at line 117 of file sc_logic.hh.
References sc_dt::Log_0, and sc_dt::Log_1.
to_value() [3/4]
static sc_logic_value_t sc_dt::sc_logic::to_value (char c) inline static private
Definition at line 120 of file sc_logic.hh.
References char_to_logic, MipsISA::index, and invalid_value().
to_value() [4/4]
static sc_logic_value_t sc_dt::sc_logic::to_value (int i) inline static private
Definition at line 132 of file sc_logic.hh.
References invalid_01(), invalid_value(), and sc_dt::Log_X.
value()
sc_logic_value_t sc_dt::sc_logic::value () const inline
Definition at line 236 of file sc_logic.hh.
References m_val.
Referenced by sc_dt::sc_lv_base::init(), sc_dt::sc_bitref< X >::operator=(), sc_dt::sc_bitref< X >::operator^=(), sc_dt::sc_bitref< X >::operator|=(), and sc_core::sc_signal_resolved::update().
Friends And Related Function Documentation
operator!=
bool operator!= (const sc_logic & a, const sc_logic & b) friend
Definition at line 339 of file sc_logic.hh.
Referenced by operator^=().
operator&
const sc_logic operator & (const sc_logic & a, const sc_logic & b) friend
Definition at line 291 of file sc_logic.hh.
Referenced by operator^=().
operator==
bool operator== (const sc_logic & a, const sc_logic & b) friend
Definition at line 333 of file sc_logic.hh.
Referenced by operator^=().
operator^
const sc_logic operator^ (const sc_logic & a, const sc_logic & b) friend
Definition at line 303 of file sc_logic.hh.
Referenced by operator^=().
operator|
const sc_logic operator| (const sc_logic & a, const sc_logic & b) friend
Definition at line 297 of file sc_logic.hh.
Referenced by operator^=().
Member Data Documentation
and_table
const sc_logic_value_t sc_dt::sc_logic::and_table static
Initial value:
= {
    { Log_0, Log_0, Log_0, Log_0 },
    { Log_0, Log_1, Log_X, Log_X },
    { Log_0, Log_X, Log_X, Log_X },
    { Log_0, Log_X, Log_X, Log_X }
}
Definition at line 148 of file sc_logic.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::and_reduce(), invalid_01(), sc_dt::operator&(), and sc_dt::sc_bitref< X >::operator=().
char_to_logic
const sc_logic_value_t sc_dt::sc_logic::char_to_logic static
Initial value:
= {
    Log_0, Log_1, Log_Z, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_0, Log_1, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_Z, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X, Log_X,
    Log_X, Log_X, Log_Z, Log_X, Log_X, Log_X, Log_X, Log_X
}
Definition at line 146 of file sc_logic.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::sc_lv_base::assign_from_string(), invalid_01(), and to_value().
logic_to_char
const char sc_dt::sc_logic::logic_to_char = { '0', '1', 'Z', 'X' } static
Definition at line 147 of file sc_logic.hh.
Referenced by invalid_01(), and sc_dt::sc_proxy< sc_subref_r< X > >::to_string().
m_val
sc_logic_value_t sc_dt::sc_logic::m_val private
Definition at line 279 of file sc_logic.hh.
Referenced by b_not(), invalid_01(), is_01(), sc_dt::operator!=(), sc_dt::operator&(), operator&=(), operator=(), sc_dt::operator^(), operator^=(), sc_dt::operator|(), operator|=(), operator~(), to_bool(), to_char(), and value().
not_table
const sc_logic_value_t sc_dt::sc_logic::not_table static
Initial value:
= {
    Log_1, Log_0, Log_X, Log_X
}
Definition at line 151 of file sc_logic.hh.
Referenced by sc_dt::sc_bitref< X >::b_not(), invalid_01(), sc_dt::sc_proxy< sc_subref_r< X > >::nand_reduce(), sc_dt::sc_proxy< sc_subref_r< X > >::nor_reduce(), sc_dt::sc_bitref_r< X >::operator~(), and sc_dt::sc_proxy< sc_subref_r< X > >::xnor_reduce().
or_table
const sc_logic_value_t sc_dt::sc_logic::or_table static
Initial value:
= {
    { Log_0, Log_1, Log_X, Log_X },
    { Log_1, Log_1, Log_1, Log_1 },
    { Log_X, Log_1, Log_X, Log_X },
    { Log_X, Log_1, Log_X, Log_X }
}
Definition at line 149 of file sc_logic.hh.
Referenced by invalid_01(), sc_dt::operator|(), sc_dt::sc_bitref< X >::operator|=(), and sc_dt::sc_proxy< sc_subref_r< X > >::or_reduce().
xor_table
const sc_logic_value_t sc_dt::sc_logic::xor_table static
Initial value:
= {
    { Log_0, Log_1, Log_X, Log_X },
    { Log_1, Log_0, Log_X, Log_X },
    { Log_X, Log_X, Log_X, Log_X },
    { Log_X, Log_X, Log_X, Log_X }
}
Definition at line 150 of file sc_logic.hh.
Referenced by invalid_01(), sc_dt::operator^(), sc_dt::sc_bitref< X >::operator^=(), and sc_dt::sc_proxy< sc_subref_r< X > >::xor_reduce().
The documentation for this class was generated from the following files:
systemc/ext/dt/bit/sc_logic.hh
systemc/dt/bit/sc_logic.cc