gem5: MultiLevelPageTable< EntryTypes > Class Template Reference
MultiLevelPageTable< EntryTypes > Class Template Reference
#include <multi_level_page_table.hh>
Public Member Functions
MultiLevelPageTable (const std::string &__name, uint64_t _pid, System *_sys, Addr pageSize)
~MultiLevelPageTable ()
void initState () override
Addr basePtr ()
void map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags=0) override
Maps a virtual memory region to a physical memory region.
void remap (Addr vaddr, int64_t size, Addr new_vaddr) override
void unmap (Addr vaddr, int64_t size) override
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EmulationPageTable
EmulationPageTable (const std::string &__name, uint64_t _pid, Addr _pageSize)
uint64_t pid () const
virtual ~EmulationPageTable ()
const std::string name () const
Addr pageAlign (Addr a)
Addr pageOffset (Addr a)
virtual bool isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
const Entry * lookup (Addr vaddr)
Lookup function.
bool translate (Addr vaddr, Addr &paddr)
Translate function.
bool translate (Addr vaddr)
Simplified translate function (just check for translation)
Fault translate (const RequestPtr &req)
Perform a translation on the memory request, fills in paddr field of req.
void getMappings (std::vector< std::pair< Addr, Addr >> *addr_mappings)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Types
typedef LastType< EntryTypes... >::type Final
Private Attributes
System * system
Pointer to System object.
Addr _basePtr
Physical address to the last level of the page table.
Additional Inherited Members
Public Types inherited from EmulationPageTable
enum MappingFlags : uint32_t { Clobber = 1, Uncacheable = 4, ReadOnly = 8 }
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from EmulationPageTable
bool shared
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from EmulationPageTable
typedef std::unordered_map< Addr, Entry > PTable
typedef PTable::iterator PTableItr
Protected Attributes inherited from EmulationPageTable
PTable pTable
const Addr pageSize
const Addr offsetMask
const uint64_t _pid
const std::string _name
Detailed Description
template<class ... EntryTypes>
class MultiLevelPageTable< EntryTypes >
Definition at line 182 of file multi_level_page_table.hh.
Member Typedef Documentation
Final
template<class ... EntryTypes> typedef LastType<EntryTypes...>::type MultiLevelPageTable< EntryTypes >::Final private
Definition at line 184 of file multi_level_page_table.hh.
Constructor & Destructor Documentation
MultiLevelPageTable()
template<class ... EntryTypes> MultiLevelPageTable< EntryTypes >::MultiLevelPageTable (const std::string & __name, uint64_t _pid, System * _sys, Addr pageSize) inline
Definition at line 197 of file multi_level_page_table.hh.
~MultiLevelPageTable()
template<class ... EntryTypes> MultiLevelPageTable< EntryTypes >::~MultiLevelPageTable () inline
Definition at line 202 of file multi_level_page_table.hh.
Member Function Documentation
basePtr()
template<class ... EntryTypes> Addr MultiLevelPageTable< EntryTypes >::basePtr () inline
Definition at line 213 of file multi_level_page_table.hh.
initState()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::initState () inline override virtual
Reimplemented from EmulationPageTable.
Definition at line 205 of file multi_level_page_table.hh.
References X86ISA::system.
map()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags = 0) inline override virtual
Maps a virtual memory region to a physical memory region.
Parameters
vaddr The starting virtual address of the region.
paddr The starting physical address where the region is mapped.
size The length of the region.
flags Generic mapping flags that can be set by or-ing values from MappingFlags enum.
Reimplemented from EmulationPageTable.
Definition at line 216 of file multi_level_page_table.hh.
References DPRINTF, EmulationPageTable::map(), ArmISA::offset, System::physProxy, and X86ISA::system.
remap()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::remap (Addr vaddr, int64_t size, Addr new_vaddr) inline override virtual
Reimplemented from EmulationPageTable.
Definition at line 236 of file multi_level_page_table.hh.
References ArmISA::offset, System::physProxy, EmulationPageTable::remap(), and X86ISA::system.
serialize()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Since, the page table is stored in system memory which is serialized separately, we will serialize just the base pointer
Implements Serializable.
Definition at line 277 of file multi_level_page_table.hh.
References paramOut(), and EmulationPageTable::serialize().
unmap()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::unmap (Addr vaddr, int64_t size) inline override virtual
Reimplemented from EmulationPageTable.
Definition at line 259 of file multi_level_page_table.hh.
References DPRINTF, fatal_if, ArmISA::offset, System::physProxy, X86ISA::system, EmulationPageTable::unmap(), and MipsISA::vaddr.
unserialize()
template<class ... EntryTypes> void MultiLevelPageTable< EntryTypes >::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 288 of file multi_level_page_table.hh.
References paramIn(), and EmulationPageTable::unserialize().
Member Data Documentation
_basePtr
template<class ... EntryTypes> Addr MultiLevelPageTable< EntryTypes >::_basePtr private
Physical address to the last level of the page table.
Definition at line 194 of file multi_level_page_table.hh.
system
template<class ... EntryTypes> System* MultiLevelPageTable< EntryTypes >::system private
Pointer to System object.
Definition at line 189 of file multi_level_page_table.hh.
The documentation for this class was generated from the following file:
mem/multi_level_page_table.hh