gem5: X86ISA::LongModePTE Class Reference
X86ISA::LongModePTE Class Reference
#include <pagetable.hh>
Public Member Functions
Addr paddr ()
void paddr (Addr addr)
bool present ()
void present (bool p)
bool uncacheable ()
void uncacheable (bool u)
bool readonly ()
void readonly (bool r)
void read (PortProxy &p, Addr table, Addr vaddr)
void reset (Addr _paddr, bool _present=true, bool _uncacheable=false, bool _readonly=false)
void write (PortProxy &p)
Static Public Member Functions
static int tableSize ()
Protected Attributes
PageTableEntry pte
Addr entryAddr
Detailed Description
Definition at line 156 of file pagetable.hh.
Member Function Documentation
paddr() [1/2]
Addr X86ISA::LongModePTE::paddr () inline
Definition at line 159 of file pagetable.hh.
References X86ISA::PageShift.
paddr() [2/2]
void X86ISA::LongModePTE::paddr (Addr addr) inline
Definition at line 160 of file pagetable.hh.
References X86ISA::PageShift.
present() [1/2]
bool X86ISA::LongModePTE::present () inline
Definition at line 162 of file pagetable.hh.
present() [2/2]
void X86ISA::LongModePTE::present (bool p) inline
Definition at line 163 of file pagetable.hh.
read()
void X86ISA::LongModePTE::read (PortProxy & p, Addr table, Addr vaddr) inline
Definition at line 172 of file pagetable.hh.
References bits(), and PortProxy::read().
readonly() [1/2]
bool X86ISA::LongModePTE::readonly () inline
Definition at line 168 of file pagetable.hh.
readonly() [2/2]
void X86ISA::LongModePTE::readonly (bool r) inline
Definition at line 169 of file pagetable.hh.
reset()
void X86ISA::LongModePTE::reset (Addr _paddr, bool _present = true, bool _uncacheable = false, bool _readonly = false) inline
Definition at line 180 of file pagetable.hh.
References X86ISA::TlbEntry::paddr, X86ISA::present, and X86ISA::TlbEntry::uncacheable.
tableSize()
static int X86ISA::LongModePTE::tableSize () inline static
Definition at line 194 of file pagetable.hh.
References X86ISA::PageShift.
uncacheable() [1/2]
bool X86ISA::LongModePTE::uncacheable () inline
Definition at line 165 of file pagetable.hh.
uncacheable() [2/2]
void X86ISA::LongModePTE::uncacheable (bool u) inline
Definition at line 166 of file pagetable.hh.
write()
void X86ISA::LongModePTE::write (PortProxy & p) inline
Definition at line 191 of file pagetable.hh.
References PortProxy::write().
Member Data Documentation
entryAddr
Addr X86ISA::LongModePTE::entryAddr protected
Definition at line 201 of file pagetable.hh.
pte
PageTableEntry X86ISA::LongModePTE::pte protected
Definition at line 200 of file pagetable.hh.
The documentation for this class was generated from the following file:
arch/x86/pagetable.hh