gem5: GenericTimerMem Class Reference
GenericTimerMem Class Reference
#include <generic_timer.hh>
Public Member Functions
GenericTimerMem (GenericTimerMemParams *p)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
uint64_t ctrlRead (Addr addr, size_t size) const
void ctrlWrite (Addr addr, size_t size, uint64_t value)
uint64_t timerRead (Addr addr, size_t size) const
void timerWrite (Addr addr, size_t size, uint64_t value)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const AddrRange ctrlRange
const AddrRange timerRange
const AddrRangeList addrRanges
SystemCounter systemCounter
System counter.
ArchTimer physTimer
ArchTimer virtTimer
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const Addr CTRL_CNTFRQ = 0x000
static const Addr CTRL_CNTNSAR = 0x004
static const Addr CTRL_CNTTIDR = 0x008
static const Addr CTRL_CNTACR_BASE = 0x040
static const Addr CTRL_CNTVOFF_LO_BASE = 0x080
static const Addr CTRL_CNTVOFF_HI_BASE = 0x084
static const Addr TIMER_CNTPCT_LO = 0x000
static const Addr TIMER_CNTPCT_HI = 0x004
static const Addr TIMER_CNTVCT_LO = 0x008
static const Addr TIMER_CNTVCT_HI = 0x00C
static const Addr TIMER_CNTFRQ = 0x010
static const Addr TIMER_CNTEL0ACR = 0x014
static const Addr TIMER_CNTVOFF_LO = 0x018
static const Addr TIMER_CNTVOFF_HI = 0x01C
static const Addr TIMER_CNTP_CVAL_LO = 0x020
static const Addr TIMER_CNTP_CVAL_HI = 0x024
static const Addr TIMER_CNTP_TVAL = 0x028
static const Addr TIMER_CNTP_CTL = 0x02C
static const Addr TIMER_CNTV_CVAL_LO = 0x030
static const Addr TIMER_CNTV_CVAL_HI = 0x034
static const Addr TIMER_CNTV_TVAL = 0x038
static const Addr TIMER_CNTV_CTL = 0x03C
Additional Inherited Members
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 297 of file generic_timer.hh.
Constructor & Destructor Documentation
GenericTimerMem()
GenericTimerMem::GenericTimerMem (GenericTimerMemParams * p)
Definition at line 525 of file generic_timer.cc.
References csprintf(), ctrlRange, SimObject::name(), MipsISA::p, physTimer, systemCounter, timerRange, and virtTimer.
Referenced by timerWrite().
Member Function Documentation
ctrlRead()
uint64_t GenericTimerMem::ctrlRead (Addr addr, size_t size) const protected
Definition at line 622 of file generic_timer.cc.
References CTRL_CNTACR_BASE, CTRL_CNTFRQ, CTRL_CNTNSAR, CTRL_CNTTIDR, CTRL_CNTVOFF_HI_BASE, CTRL_CNTVOFF_LO_BASE, SystemCounter::freq(), ArchTimer::offset(), panic, systemCounter, virtTimer, and warn.
Referenced by read().
ctrlWrite()
void GenericTimerMem::ctrlWrite (Addr addr, size_t size, uint64_t value) protected
Definition at line 662 of file generic_timer.cc.
References CTRL_CNTACR_BASE, CTRL_CNTFRQ, CTRL_CNTNSAR, CTRL_CNTTIDR, CTRL_CNTVOFF_HI_BASE, CTRL_CNTVOFF_LO_BASE, insertBits(), ArchTimer::offset(), panic, ArchTimer::setOffset(), virtTimer, and warn.
Referenced by write().
getAddrRanges()
AddrRangeList GenericTimerMem::getAddrRanges () const inline override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 306 of file generic_timer.hh.
References addr, and SystemCounter::value().
read()
Tick GenericTimerMem::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 569 of file generic_timer.cc.
References addr, AddrRange::contains(), ctrlRange, ctrlRead(), DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeResponse(), panic, Packet::setLE(), AddrRange::start(), timerRange, and timerRead().
serialize()
void GenericTimerMem::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 542 of file generic_timer.cc.
References paramOut(), physTimer, Serializable::serializeSection(), systemCounter, and virtTimer.
timerRead()
uint64_t GenericTimerMem::timerRead (Addr addr, size_t size) const protected
Definition at line 705 of file generic_timer.cc.
References ArchTimer::compareValue(), ArchTimer::control(), CTRL_CNTVOFF_HI_BASE, CTRL_CNTVOFF_LO_BASE, SystemCounter::freq(), ArchTimer::offset(), panic, physTimer, systemCounter, TIMER_CNTEL0ACR, TIMER_CNTFRQ, TIMER_CNTP_CTL, TIMER_CNTP_CVAL_HI, TIMER_CNTP_CVAL_LO, TIMER_CNTP_TVAL, TIMER_CNTPCT_HI, TIMER_CNTPCT_LO, TIMER_CNTV_CTL, TIMER_CNTV_CVAL_HI, TIMER_CNTV_CVAL_LO, TIMER_CNTV_TVAL, TIMER_CNTVCT_HI, TIMER_CNTVCT_LO, ArchTimer::timerValue(), ArchTimer::value(), virtTimer, and warn.
Referenced by read().
timerWrite()
void GenericTimerMem::timerWrite (Addr addr, size_t size, uint64_t value) protected
Definition at line 789 of file generic_timer.cc.
References ArchTimer::compareValue(), GenericTimerMem(), insertBits(), panic, physTimer, ArchTimer::setCompareValue(), ArchTimer::setControl(), ArchTimer::setTimerValue(), TIMER_CNTEL0ACR, TIMER_CNTP_CTL, TIMER_CNTP_CVAL_HI, TIMER_CNTP_CVAL_LO, TIMER_CNTP_TVAL, TIMER_CNTV_CTL, TIMER_CNTV_CVAL_HI, TIMER_CNTV_CVAL_LO, TIMER_CNTV_TVAL, virtTimer, and warn.
Referenced by write().
unserialize()
void GenericTimerMem::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 553 of file generic_timer.cc.
References panic, physTimer, systemCounter, UNSERIALIZE_SCALAR, Serializable::unserializeSection(), and virtTimer.
write()
Tick GenericTimerMem::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 598 of file generic_timer.cc.
References addr, AddrRange::contains(), ctrlRange, ctrlWrite(), DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeResponse(), panic, AddrRange::start(), timerRange, and timerWrite().
Member Data Documentation
addrRanges
const AddrRangeList GenericTimerMem::addrRanges protected
Definition at line 345 of file generic_timer.hh.
CTRL_CNTACR_BASE
const Addr GenericTimerMem::CTRL_CNTACR_BASE = 0x040 static protected
Definition at line 321 of file generic_timer.hh.
Referenced by ctrlRead(), and ctrlWrite().
CTRL_CNTFRQ
const Addr GenericTimerMem::CTRL_CNTFRQ = 0x000 static protected
Definition at line 318 of file generic_timer.hh.
Referenced by ctrlRead(), and ctrlWrite().
CTRL_CNTNSAR
const Addr GenericTimerMem::CTRL_CNTNSAR = 0x004 static protected
Definition at line 319 of file generic_timer.hh.
Referenced by ctrlRead(), and ctrlWrite().
CTRL_CNTTIDR
const Addr GenericTimerMem::CTRL_CNTTIDR = 0x008 static protected
Definition at line 320 of file generic_timer.hh.
Referenced by ctrlRead(), and ctrlWrite().
CTRL_CNTVOFF_HI_BASE
const Addr GenericTimerMem::CTRL_CNTVOFF_HI_BASE = 0x084 static protected
Definition at line 323 of file generic_timer.hh.
Referenced by ctrlRead(), ctrlWrite(), and timerRead().
CTRL_CNTVOFF_LO_BASE
const Addr GenericTimerMem::CTRL_CNTVOFF_LO_BASE = 0x080 static protected
Definition at line 322 of file generic_timer.hh.
Referenced by ctrlRead(), ctrlWrite(), and timerRead().
ctrlRange
const AddrRange GenericTimerMem::ctrlRange protected
Definition at line 343 of file generic_timer.hh.
Referenced by GenericTimerMem(), read(), and write().
physTimer
ArchTimer GenericTimerMem::physTimer protected
Definition at line 350 of file generic_timer.hh.
Referenced by GenericTimerMem(), serialize(), timerRead(), timerWrite(), and unserialize().
systemCounter
SystemCounter GenericTimerMem::systemCounter protected
System counter.
Definition at line 349 of file generic_timer.hh.
Referenced by ctrlRead(), GenericTimerMem(), serialize(), timerRead(), and unserialize().
TIMER_CNTEL0ACR
const Addr GenericTimerMem::TIMER_CNTEL0ACR = 0x014 static protected
Definition at line 330 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTFRQ
const Addr GenericTimerMem::TIMER_CNTFRQ = 0x010 static protected
Definition at line 329 of file generic_timer.hh.
Referenced by timerRead().
TIMER_CNTP_CTL
const Addr GenericTimerMem::TIMER_CNTP_CTL = 0x02C static protected
Definition at line 336 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTP_CVAL_HI
const Addr GenericTimerMem::TIMER_CNTP_CVAL_HI = 0x024 static protected
Definition at line 334 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTP_CVAL_LO
const Addr GenericTimerMem::TIMER_CNTP_CVAL_LO = 0x020 static protected
Definition at line 333 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTP_TVAL
const Addr GenericTimerMem::TIMER_CNTP_TVAL = 0x028 static protected
Definition at line 335 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTPCT_HI
const Addr GenericTimerMem::TIMER_CNTPCT_HI = 0x004 static protected
Definition at line 326 of file generic_timer.hh.
Referenced by timerRead().
TIMER_CNTPCT_LO
const Addr GenericTimerMem::TIMER_CNTPCT_LO = 0x000 static protected
Definition at line 325 of file generic_timer.hh.
Referenced by timerRead().
TIMER_CNTV_CTL
const Addr GenericTimerMem::TIMER_CNTV_CTL = 0x03C static protected
Definition at line 340 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTV_CVAL_HI
const Addr GenericTimerMem::TIMER_CNTV_CVAL_HI = 0x034 static protected
Definition at line 338 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTV_CVAL_LO
const Addr GenericTimerMem::TIMER_CNTV_CVAL_LO = 0x030 static protected
Definition at line 337 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTV_TVAL
const Addr GenericTimerMem::TIMER_CNTV_TVAL = 0x038 static protected
Definition at line 339 of file generic_timer.hh.
Referenced by timerRead(), and timerWrite().
TIMER_CNTVCT_HI
const Addr GenericTimerMem::TIMER_CNTVCT_HI = 0x00C static protected
Definition at line 328 of file generic_timer.hh.
Referenced by timerRead().
TIMER_CNTVCT_LO
const Addr GenericTimerMem::TIMER_CNTVCT_LO = 0x008 static protected
Definition at line 327 of file generic_timer.hh.
Referenced by timerRead().
TIMER_CNTVOFF_HI
const Addr GenericTimerMem::TIMER_CNTVOFF_HI = 0x01C static protected
Definition at line 332 of file generic_timer.hh.
TIMER_CNTVOFF_LO
const Addr GenericTimerMem::TIMER_CNTVOFF_LO = 0x018 static protected
Definition at line 331 of file generic_timer.hh.
timerRange
const AddrRange GenericTimerMem::timerRange protected
Definition at line 344 of file generic_timer.hh.
Referenced by GenericTimerMem(), read(), and write().
virtTimer
ArchTimer GenericTimerMem::virtTimer protected
Definition at line 351 of file generic_timer.hh.
Referenced by ctrlRead(), ctrlWrite(), GenericTimerMem(), serialize(), timerRead(), timerWrite(), and unserialize().
The documentation for this class was generated from the following files:
dev/arm/generic_timer.hh
dev/arm/generic_timer.cc