gem5: ArmISA::ITLBIMVA Class Reference
ArmISA::ITLBIMVA Class Reference
Instruction TLB Invalidate by VA.
#include <tlbi_op.hh>
Public Member Functions
ITLBIMVA (ExceptionLevel _targetEL, bool _secure, Addr _addr, uint16_t _asid)
void broadcast (ThreadContext *tc)=delete
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
Addr addr
uint16_t asid
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
Instruction TLB Invalidate by VA.
Definition at line 211 of file tlbi_op.hh.
Constructor & Destructor Documentation
ITLBIMVA()
ArmISA::ITLBIMVA::ITLBIMVA (ExceptionLevel _targetEL, bool _secure, Addr _addr, uint16_t _asid) inline
Definition at line 214 of file tlbi_op.hh.
References ArmISA::TLBIOp::broadcast(), and ArmISA::TLBIOp::operator()().
Member Function Documentation
broadcast()
void ArmISA::ITLBIMVA::broadcast (ThreadContext * tc) delete
operator()()
void ArmISA::ITLBIMVA::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 143 of file tlbi_op.cc.
References addr, ArmISA::asid, ArmISA::TLB::flushMvaAsid(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
Member Data Documentation
addr
Addr ArmISA::ITLBIMVA::addr protected
Definition at line 224 of file tlbi_op.hh.
asid
uint16_t ArmISA::ITLBIMVA::asid protected
Definition at line 225 of file tlbi_op.hh.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc