gem5: sc_gem5::TraceFile Class Reference
sc_gem5::TraceFile Class Reference abstract
#include <tracefile.hh>
Public Member Functions
~TraceFile ()
void traceDeltas (bool on)
void set_time_unit (double, ::sc_core::sc_time_unit) override
void finalizeTime ()
virtual void trace (bool delta)=0
virtual void addTraceVal (const bool *v, const std::string &name)=0
virtual void addTraceVal (const float *v, const std::string &name)=0
virtual void addTraceVal (const double *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_logic *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_int_base *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_uint_base *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_signed *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_unsigned *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_bv_base *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_lv_base *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_fxval *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_fxval_fast *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_fxnum *v, const std::string &name)=0
virtual void addTraceVal (const sc_dt::sc_fxnum_fast *v, const std::string &name)=0
virtual void addTraceVal (const sc_core::sc_event *v, const std::string &name)=0
virtual void addTraceVal (const sc_core::sc_time *v, const std::string &name)=0
virtual void addTraceVal (const unsigned char *v, const std::string &name, int width)=0
virtual void addTraceVal (const char *v, const std::string &name, int width)=0
virtual void addTraceVal (const unsigned short *v, const std::string &name, int width)=0
virtual void addTraceVal (const short *v, const std::string &name, int width)=0
virtual void addTraceVal (const unsigned int *v, const std::string &name, int width)=0
virtual void addTraceVal (const int *v, const std::string &name, int width)=0
virtual void addTraceVal (const unsigned long *v, const std::string &name, int width)=0
virtual void addTraceVal (const long *v, const std::string &name, int width)=0
virtual void addTraceVal (const sc_dt::int64 *v, const std::string &name, int width)=0
virtual void addTraceVal (const sc_dt::uint64 *v, const std::string &name, int width)=0
virtual void addTraceVal (const unsigned int *, const std::string &name, const char **literals)=0
virtual void writeComment (const std::string &comment)=0
Public Member Functions inherited from sc_core::sc_trace_file
virtual ~sc_trace_file ()
virtual void set_time_unit (double, sc_time_unit)=0
Protected Member Functions
TraceFile (const std::string &name)
std::ostream & stream ()
Protected Member Functions inherited from sc_core::sc_trace_file
sc_trace_file ()
Protected Attributes
OutputStream * _os
uint64_t timeUnitTicks
double timeUnitValue
::sc_core::sc_time_unit timeUnitUnit
bool _traceDeltas
Detailed Description
Definition at line 192 of file tracefile.hh.
Constructor & Destructor Documentation
TraceFile()
sc_gem5::TraceFile::TraceFile (const std::string & name) protected
Definition at line 45 of file tracefile.cc.
~TraceFile()
sc_gem5::TraceFile::~TraceFile ()
Definition at line 50 of file tracefile.cc.
References _os, OutputDirectory::close(), and simout.
Member Function Documentation
addTraceVal() [1/27]
virtual void sc_gem5::TraceFile::addTraceVal (const bool * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [2/27]
virtual void sc_gem5::TraceFile::addTraceVal (const float * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [3/27]
virtual void sc_gem5::TraceFile::addTraceVal (const double * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [4/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_logic * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [5/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_int_base * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [6/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_uint_base * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [7/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_signed * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [8/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_unsigned * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [9/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_bv_base * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [10/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_lv_base * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [11/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_fxval * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [12/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_fxval_fast * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [13/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_fxnum * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [14/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::sc_fxnum_fast * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [15/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_core::sc_event * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [16/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_core::sc_time * v, const std::string & name) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [17/27]
virtual void sc_gem5::TraceFile::addTraceVal (const unsigned char * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [18/27]
virtual void sc_gem5::TraceFile::addTraceVal (const char * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [19/27]
virtual void sc_gem5::TraceFile::addTraceVal (const unsigned short * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [20/27]
virtual void sc_gem5::TraceFile::addTraceVal (const short * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [21/27]
virtual void sc_gem5::TraceFile::addTraceVal (const unsigned int * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [22/27]
virtual void sc_gem5::TraceFile::addTraceVal (const int * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [23/27]
virtual void sc_gem5::TraceFile::addTraceVal (const unsigned long * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [24/27]
virtual void sc_gem5::TraceFile::addTraceVal (const long * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [25/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::int64 * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [26/27]
virtual void sc_gem5::TraceFile::addTraceVal (const sc_dt::uint64 * v, const std::string & name, int width) pure virtual
Implemented in sc_gem5::VcdTraceFile.
addTraceVal() [27/27]
virtual void sc_gem5::TraceFile::addTraceVal (const unsigned int * , const std::string & name, const char ** literals) pure virtual
Implemented in sc_gem5::VcdTraceFile.
finalizeTime()
void sc_gem5::TraceFile::finalizeTime ()
Definition at line 77 of file tracefile.cc.
References sc_core::sc_get_time_resolution(), timeUnitTicks, timeUnitUnit, timeUnitValue, and sc_core::sc_time::value().
set_time_unit()
void sc_gem5::TraceFile::set_time_unit (double d, ::sc_core::sc_time_unit tu) override
Definition at line 58 of file tracefile.cc.
References _os, ArmISA::d, ArmISA::i, OutputStream::name(), sc_core::SC_FS, SC_REPORT_INFO, sc_core::SC_SEC, ArmISA::ss, sc_gem5::TimeUnitNames, sc_gem5::TimeUnitScale, timeUnitUnit, timeUnitValue, and MipsISA::tu.
stream()
std::ostream & sc_gem5::TraceFile::stream () protected
Definition at line 55 of file tracefile.cc.
References _os, and OutputStream::stream().
trace()
virtual void sc_gem5::TraceFile::trace (bool delta) pure virtual
Implemented in sc_gem5::VcdTraceFile.
traceDeltas()
void sc_gem5::TraceFile::traceDeltas (bool on) inline
Definition at line 209 of file tracefile.hh.
References name(), MipsISA::on, ArmISA::v, and sc_gem5::TraceValBase::width().
writeComment()
virtual void sc_gem5::TraceFile::writeComment (const std::string & comment) pure virtual
Implemented in sc_gem5::VcdTraceFile.
Member Data Documentation
_os
OutputStream* sc_gem5::TraceFile::_os protected
Definition at line 195 of file tracefile.hh.
Referenced by set_time_unit(), stream(), and ~TraceFile().
_traceDeltas
bool sc_gem5::TraceFile::_traceDeltas protected
Definition at line 200 of file tracefile.hh.
timeUnitTicks
uint64_t sc_gem5::TraceFile::timeUnitTicks protected
Definition at line 196 of file tracefile.hh.
Referenced by finalizeTime().
timeUnitUnit
::sc_core::sc_time_unit sc_gem5::TraceFile::timeUnitUnit protected
Definition at line 198 of file tracefile.hh.
Referenced by finalizeTime(), and set_time_unit().
timeUnitValue
double sc_gem5::TraceFile::timeUnitValue protected
Definition at line 197 of file tracefile.hh.
Referenced by finalizeTime(), and set_time_unit().
The documentation for this class was generated from the following files:
systemc/utils/tracefile.hh
systemc/utils/tracefile.cc