gem5: OutputFile< StreamType > Class Template Reference
OutputFile< StreamType > Class Template Reference
#include <output.hh>
Public Types
typedef StreamType stream_type_t
Public Member Functions
virtual ~OutputFile ()
bool recreateable () const override
Can the file be recreated if the output directory is moved?
Public Member Functions inherited from OutputStream
virtual ~OutputStream ()
std::ostream * stream () const
Get the output underlying output stream.
const std::string & name () const
Get the file name in the output directory.
Protected Member Functions
OutputFile (const OutputDirectory &dir, const std::string &name, std::ios_base::openmode mode, bool recreateable)
OutputFile (const OutputFile< StreamType > &f)
void relocate (const OutputDirectory &dir) override
Re-create the file in a new location if it is relocatable.
Protected Member Functions inherited from OutputStream
OutputStream (const std::string &name, std::ostream *stream)
Wrap an existing stream.
OutputStream (const OutputStream &f)
Protected Attributes
const std::ios_base::openmode _mode
File mode when opened.
const bool _recreateable
Can the file be recreated in a new location?
stream_type_t *const _fstream
Pointer to the file stream.
Protected Attributes inherited from OutputStream
const std::string _name
Name in output directory.
std::ostream *const _stream
Underlying output stream.
Friends
class OutputDirectory
Detailed Description
template<class StreamType>
class OutputFile< StreamType >
Definition at line 98 of file output.hh.
Member Typedef Documentation
stream_type_t
template<class StreamType> typedef StreamType OutputFile< StreamType >::stream_type_t
Definition at line 102 of file output.hh.
Constructor & Destructor Documentation
~OutputFile()
template<class StreamType > OutputFile< StreamType >::~OutputFile () virtual
Definition at line 97 of file output.cc.
References OutputFile< StreamType >::_fstream.
OutputFile() [1/2]
template<class StreamType > OutputFile< StreamType >::OutputFile (const OutputDirectory & dir, const std::string & name, std::ios_base::openmode mode, bool recreateable) protected
Definition at line 83 of file output.cc.
References OutputFile< StreamType >::_fstream, OutputFile< StreamType >::_mode, OutputStream::_name, and OutputDirectory::resolve().
OutputFile() [2/2]
template<class StreamType> OutputFile< StreamType >::OutputFile (const OutputFile< StreamType > & f) protected
Member Function Documentation
recreateable()
template<class StreamType> bool OutputFile< StreamType >::recreateable () const inline override virtual
Can the file be recreated if the output directory is moved?
Returns
true if the file will be created in the new location, false otherwise.
Reimplemented from OutputStream.
Definition at line 112 of file output.hh.
Referenced by OutputDirectory::create(), and OutputDirectory::open().
relocate()
template<class StreamType > void OutputFile< StreamType >::relocate (const OutputDirectory & dir) override protected virtual
Re-create the file in a new location if it is relocatable.
Reimplemented from OutputStream.
Definition at line 105 of file output.cc.
References OutputFile< StreamType >::_fstream, OutputFile< StreamType >::_mode, OutputStream::_name, OutputFile< StreamType >::_recreateable, OutputDirectory::resolve(), OutputDirectory::stderr, and OutputDirectory::stdout.
Friends And Related Function Documentation
OutputDirectory
template<class StreamType> friend class OutputDirectory friend
Definition at line 115 of file output.hh.
Referenced by OutputDirectory::createSubdirectory().
Member Data Documentation
_fstream
template<class StreamType> stream_type_t* const OutputFile< StreamType >::_fstream protected
Pointer to the file stream.
Definition at line 135 of file output.hh.
Referenced by OutputFile< StreamType >::OutputFile(), OutputFile< StreamType >::relocate(), and OutputFile< StreamType >::~OutputFile().
_mode
template<class StreamType> const std::ios_base::openmode OutputFile< StreamType >::_mode protected
File mode when opened.
Definition at line 129 of file output.hh.
Referenced by OutputFile< StreamType >::OutputFile(), and OutputFile< StreamType >::relocate().
_recreateable
template<class StreamType> const bool OutputFile< StreamType >::_recreateable protected
Can the file be recreated in a new location?
Definition at line 132 of file output.hh.
Referenced by OutputFile< StreamType >::relocate().
The documentation for this class was generated from the following files:
base/output.hh
base/output.cc