gem5: MaltaIO Class Reference
MaltaIO Class Reference
Malta I/O device is a catch all for all the south bridge stuff we care to implement.
#include <malta_io.hh>
Classes
class RTC
Public Types
typedef MaltaIOParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Tick frequency () const
Return the freqency of the RTC.
const Params * params () const
MaltaIO (const Params *p)
Initialize all the data for devices supported by Malta I/O.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void postIntr (uint8_t interrupt)
Post an Interrupt to the CPU.
void clearIntr (uint8_t interrupt)
Clear an Interrupt to the CPU.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup () override
Start running.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
uint8_t mask1
Mask of the PIC1.
uint8_t mask2
Mask of the PIC2.
uint8_t mode1
Mode of PIC1.
uint8_t mode2
Mode of PIC2.
uint8_t picr
Raw PIC interrupt register before masking.
bool picInterrupting
Is the pic interrupting right now or not.
Malta * malta
A pointer to the Malta device which be belong to.
Intel8254Timer pitimer
Intel 8253 Periodic Interval Timer.
RTC rtc
uint16_t timerData
The interval is set via two writes to the PIT.
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Malta I/O device is a catch all for all the south bridge stuff we care to implement.
Definition at line 52 of file malta_io.hh.
Member Typedef Documentation
Params
typedef MaltaIOParams MaltaIO::Params
Definition at line 109 of file malta_io.hh.
Constructor & Destructor Documentation
MaltaIO()
MaltaIO::MaltaIO (const Params * p)
Initialize all the data for devices supported by Malta I/O.
Parameters
p pointer to Params struct
Definition at line 66 of file malta_io.cc.
References Malta::io, malta, picInterrupting, picr, and timerData.
Referenced by params(), and startup().
Member Function Documentation
clearIntr()
void MaltaIO::clearIntr (uint8_t interrupt)
Clear an Interrupt to the CPU.
Definition at line 106 of file malta_io.cc.
References Malta::cchip, MaltaCChip::clearIntr(), DPRINTF, and malta.
Referenced by Malta::clearConsoleInt(), and params().
frequency()
Tick MaltaIO::frequency () const
Return the freqency of the RTC.
Returns
interrupt rate of the RTC
Definition at line 79 of file malta_io.cc.
References SimClock::Frequency, and params().
params()
const Params* MaltaIO::params () const inline
Definition at line 112 of file malta_io.hh.
References SimObject::_params, clearIntr(), MaltaIO(), MipsISA::p, postIntr(), read(), MC146818::serialize(), MC146818::startup(), MC146818::unserialize(), and write().
Referenced by frequency().
postIntr()
void MaltaIO::postIntr (uint8_t interrupt)
Post an Interrupt to the CPU.
Definition at line 99 of file malta_io.cc.
References Malta::cchip, DPRINTF, malta, and MaltaCChip::postIntr().
Referenced by params(), and Malta::postConsoleInt().
read()
Tick MaltaIO::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 85 of file malta_io.cc.
References panic, and BasicPioDevice::pioDelay.
Referenced by params().
serialize()
void MaltaIO::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 113 of file malta_io.cc.
References mask1, mask2, mode1, mode2, picInterrupting, picr, pitimer, rtc, MC146818::serialize(), Intel8254Timer::serialize(), SERIALIZE_SCALAR, and timerData.
startup()
void MaltaIO::startup () override virtual
Start running.
Reimplemented from SimObject.
Definition at line 145 of file malta_io.cc.
References MaltaIO(), pitimer, rtc, MC146818::startup(), and Intel8254Timer::startup().
unserialize()
void MaltaIO::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 129 of file malta_io.cc.
References mask1, mask2, mode1, mode2, picInterrupting, picr, pitimer, rtc, timerData, MC146818::unserialize(), Intel8254Timer::unserialize(), and UNSERIALIZE_SCALAR.
write()
Tick MaltaIO::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 92 of file malta_io.cc.
References panic, and BasicPioDevice::pioDelay.
Referenced by params().
Member Data Documentation
malta
Malta* MaltaIO::malta protected
A pointer to the Malta device which be belong to.
Definition at line 89 of file malta_io.hh.
Referenced by clearIntr(), MaltaIO(), and postIntr().
mask1
uint8_t MaltaIO::mask1 protected
Mask of the PIC1.
Definition at line 71 of file malta_io.hh.
Referenced by serialize(), and unserialize().
mask2
uint8_t MaltaIO::mask2 protected
Mask of the PIC2.
Definition at line 74 of file malta_io.hh.
Referenced by serialize(), and unserialize().
mode1
uint8_t MaltaIO::mode1 protected
Mode of PIC1.
Not used for anything
Definition at line 77 of file malta_io.hh.
Referenced by serialize(), and unserialize().
mode2
uint8_t MaltaIO::mode2 protected
Mode of PIC2.
Not used for anything
Definition at line 80 of file malta_io.hh.
Referenced by serialize(), and unserialize().
picInterrupting
bool MaltaIO::picInterrupting protected
Is the pic interrupting right now or not.
Definition at line 86 of file malta_io.hh.
Referenced by MaltaIO(), serialize(), and unserialize().
picr
uint8_t MaltaIO::picr protected
Raw PIC interrupt register before masking.
Definition at line 83 of file malta_io.hh.
Referenced by MaltaIO(), serialize(), and unserialize().
pitimer
Intel8254Timer MaltaIO::pitimer protected
Intel 8253 Periodic Interval Timer.
Definition at line 92 of file malta_io.hh.
Referenced by serialize(), startup(), and unserialize().
rtc
RTC MaltaIO::rtc protected
Definition at line 94 of file malta_io.hh.
Referenced by serialize(), startup(), and unserialize().
timerData
uint16_t MaltaIO::timerData protected
The interval is set via two writes to the PIT.
This variable contains a flag as to how many writes have happened, and the time so far.
Definition at line 100 of file malta_io.hh.
Referenced by MaltaIO(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/mips/malta_io.hh
dev/mips/malta_io.cc