gem5: HsailISA::MemInst Class Reference
HsailISA::MemInst Class Reference
#include <mem.hh>
Public Member Functions
MemInst ()
MemInst (Enums::MemType m_type)
void init_addr (AddrOperandBase *_addr_operand)
int getMemOperandSize ()
AddrOperandBase * getAddressOperand ()
Private Attributes
int size
AddrOperandBase * addr_operand
Detailed Description
Definition at line 48 of file mem.hh.
Constructor & Destructor Documentation
MemInst() [1/2]
HsailISA::MemInst::MemInst () inline
Definition at line 51 of file mem.hh.
MemInst() [2/2]
HsailISA::MemInst::MemInst (Enums::MemType m_type) inline
Definition at line 53 of file mem.hh.
References addr_operand, and size.
Member Function Documentation
getAddressOperand()
AddrOperandBase* HsailISA::MemInst::getAddressOperand () inline
Definition at line 86 of file mem.hh.
References addr_operand.
getMemOperandSize()
int HsailISA::MemInst::getMemOperandSize () inline
Definition at line 85 of file mem.hh.
References size.
init_addr()
void HsailISA::MemInst::init_addr (AddrOperandBase * _addr_operand) inline
Definition at line 75 of file mem.hh.
References addr_operand.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::AtomicInst(), HsailISA::LdaInst< DestDataType, AddrOperandType >::LdaInst(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::LdInst(), and HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::StInst().
Member Data Documentation
addr_operand
AddrOperandBase* HsailISA::MemInst::addr_operand private
Definition at line 82 of file mem.hh.
Referenced by getAddressOperand(), init_addr(), and MemInst().
size
int HsailISA::MemInst::size private
Definition at line 81 of file mem.hh.
Referenced by getMemOperandSize(), and MemInst().
The documentation for this class was generated from the following file:
arch/hsail/insts/mem.hh