gem5: SchedulingPolicy Class Reference
SchedulingPolicy Class Reference abstract
Interface class for the wave scheduling policy.
#include <scheduling_policy.hh>
Public Member Functions
SchedulingPolicy ()
virtual Wavefront * chooseWave (std::vector< Wavefront *> *sched_list)=0
Detailed Description
Interface class for the wave scheduling policy.
Definition at line 47 of file scheduling_policy.hh.
Constructor & Destructor Documentation
SchedulingPolicy()
SchedulingPolicy::SchedulingPolicy () inline
Definition at line 50 of file scheduling_policy.hh.
References chooseWave().
Member Function Documentation
chooseWave()
virtual Wavefront* SchedulingPolicy::chooseWave (std::vector< Wavefront *> * sched_list) pure virtual
Implemented in __SchedulingPolicy< Policy >, __SchedulingPolicy< OFSchedulingPolicy >, and __SchedulingPolicy< RRSchedulingPolicy >.
Referenced by Scheduler::chooseWave(), and SchedulingPolicy().
The documentation for this class was generated from the following file:
gpu-compute/scheduling_policy.hh