gem5: SMMUProcess Class Reference
SMMUProcess Class Reference abstract
#include <smmu_v3_proc.hh>
Public Member Functions
SMMUProcess (const std::string &name, SMMUv3 &_smmu)
virtual ~SMMUProcess ()
SMMUAction run (PacketPtr pkt)
const std::string name () const
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Protected Types
typedef Coroutine::CallerType Yield
Protected Member Functions
void reinit ()
virtual void main (Yield &yield)=0
void doRead (Yield &yield, Addr addr, void *ptr, size_t size)
void doWrite (Yield &yield, Addr addr, const void *ptr, size_t size)
void doDelay (Yield &yield, Cycles cycles)
void doSleep (Yield &yield)
void doSemaphoreDown (Yield &yield, SMMUSemaphore &sem)
void doSemaphoreUp (SMMUSemaphore &sem)
void doWaitForSignal (Yield &yield, SMMUSignal &sig)
void doBroadcastSignal (SMMUSignal &sig)
void scheduleWakeup (Tick when)
Protected Attributes
SMMUv3 & smmu
Private Types
typedef m5::Coroutine< PacketPtr, SMMUAction > Coroutine
Private Member Functions
void wakeup ()
Private Attributes
Coroutine * coroutine
std::string myName
Additional Inherited Members
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Detailed Description
Definition at line 95 of file smmu_v3_proc.hh.
Member Typedef Documentation
Coroutine
typedef m5::Coroutine<PacketPtr, SMMUAction> SMMUProcess::Coroutine private
Definition at line 98 of file smmu_v3_proc.hh.
Yield
typedef Coroutine::CallerType SMMUProcess::Yield protected
Definition at line 106 of file smmu_v3_proc.hh.
Constructor & Destructor Documentation
SMMUProcess()
SMMUProcess::SMMUProcess (const std::string & name, SMMUv3 & _smmu)
Definition at line 45 of file smmu_v3_proc.cc.
Referenced by scheduleWakeup().
~SMMUProcess()
SMMUProcess::~SMMUProcess () virtual
Definition at line 51 of file smmu_v3_proc.cc.
References coroutine.
Member Function Documentation
doBroadcastSignal()
void SMMUProcess::doBroadcastSignal (SMMUSignal & sig) protected
Definition at line 180 of file smmu_v3_proc.cc.
References curTick(), and SMMUSignal::waiting.
Referenced by SMMUTranslationProcess::hazard4kRelease(), and SMMUTranslationProcess::hazardIdRelease().
doDelay()
void SMMUProcess::doDelay (Yield & yield, Cycles cycles) protected
Definition at line 126 of file smmu_v3_proc.cc.
References ArmISA::a, ACTION_DELAY, Clocked::clockEdge(), Clocked::clockPeriod(), SMMUAction::delay, System::isTimingMode(), scheduleWakeup(), smmu, SMMUv3::system, and SMMUAction::type.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUTranslationProcess::configCacheLookup(), doRead(), doWrite(), SMMUTranslationProcess::ifcTLBLookup(), SMMUTranslationProcess::main(), SMMUTranslationProcess::microTLBLookup(), SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTranslation(), SMMUTranslationProcess::translateStage2(), SMMUTranslationProcess::walkCacheLookup(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
doRead()
void SMMUProcess::doRead (Yield & yield, Addr addr, void * ptr, size_t size) protected
Definition at line 71 of file smmu_v3_proc.cc.
References ArmISA::a, ACTION_SEND_REQ, addr, Packet::dataStatic(), SMMUAction::delay, ContextSwitchTaskId::DMA, doDelay(), doSemaphoreDown(), doSemaphoreUp(), m5::Coroutine< Arg, Ret >::CallerType::get(), Packet::getSize(), SMMUv3::masterId, SMMUv3::masterPortSem, SMMUAction::pkt, MemCmd::ReadReq, smmu, and SMMUAction::type.
Referenced by SMMUTranslationProcess::doReadConfig(), SMMUTranslationProcess::doReadPTE(), and SMMUCommandExecProcess::main().
doSemaphoreDown()
void SMMUProcess::doSemaphoreDown (Yield & yield, SMMUSemaphore & sem) protected
Definition at line 146 of file smmu_v3_proc.cc.
References SMMUSemaphore::count, doSleep(), and SMMUSemaphore::queue.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), doRead(), doWrite(), SMMUTranslationProcess::ifcTLBLookup(), SMMUTranslationProcess::ifcTLBUpdate(), SMMUTranslationProcess::main(), SMMUTranslationProcess::microTLBLookup(), SMMUTranslationProcess::microTLBUpdate(), SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), SMMUTranslationProcess::smmuTranslation(), SMMUTranslationProcess::translateStage2(), SMMUTranslationProcess::walkCacheLookup(), SMMUTranslationProcess::walkCacheUpdate(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
doSemaphoreUp()
void SMMUProcess::doSemaphoreUp (SMMUSemaphore & sem) protected
Definition at line 158 of file smmu_v3_proc.cc.
References SMMUSemaphore::count, curTick(), SMMUSemaphore::queue, and scheduleWakeup().
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), doRead(), doWrite(), SMMUTranslationProcess::ifcTLBLookup(), SMMUTranslationProcess::ifcTLBUpdate(), SMMUTranslationProcess::main(), SMMUTranslationProcess::microTLBLookup(), SMMUTranslationProcess::microTLBUpdate(), SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), SMMUTranslationProcess::smmuTranslation(), SMMUTranslationProcess::translateStage2(), SMMUTranslationProcess::walkCacheLookup(), SMMUTranslationProcess::walkCacheUpdate(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
doSleep()
void SMMUProcess::doSleep (Yield & yield) protected
Definition at line 138 of file smmu_v3_proc.cc.
References ArmISA::a, ACTION_SLEEP, and SMMUAction::type.
Referenced by doSemaphoreDown(), doWaitForSignal(), and SMMUCommandExecProcess::main().
doWaitForSignal()
void SMMUProcess::doWaitForSignal (Yield & yield, SMMUSignal & sig) protected
Definition at line 173 of file smmu_v3_proc.cc.
References doSleep(), and SMMUSignal::waiting.
Referenced by SMMUTranslationProcess::hazard4kHold(), and SMMUTranslationProcess::hazardIdHold().
doWrite()
void SMMUProcess::doWrite (Yield & yield, Addr addr, const void * ptr, size_t size) protected
Definition at line 100 of file smmu_v3_proc.cc.
References ArmISA::a, ACTION_SEND_REQ, addr, Packet::dataStatic(), ContextSwitchTaskId::DMA, doDelay(), doSemaphoreDown(), doSemaphoreUp(), m5::Coroutine< Arg, Ret >::CallerType::get(), SMMUv3::masterId, SMMUv3::masterPortSem, SMMUv3::masterPortWidth, SMMUAction::pkt, smmu, SMMUAction::type, and MemCmd::WriteReq.
Referenced by SMMUTranslationProcess::sendEvent().
main()
virtual void SMMUProcess::main (Yield & yield) protected pure virtual
Implemented in SMMUTranslationProcess, and SMMUCommandExecProcess.
Referenced by reinit().
name()
const std::string SMMUProcess::name () const inline
Definition at line 133 of file smmu_v3_proc.hh.
Referenced by SMMUTranslationProcess::issuePrefetch().
reinit()
void SMMUProcess::reinit () protected
Definition at line 63 of file smmu_v3_proc.cc.
References coroutine, and main().
Referenced by SMMUTranslationProcess::beginTransaction(), SMMUCommandExecProcess::SMMUCommandExecProcess(), and SMMUTranslationProcess::SMMUTranslationProcess().
run()
SMMUAction SMMUProcess::run (PacketPtr pkt)
Definition at line 204 of file smmu_v3_proc.cc.
References coroutine.
Referenced by SMMUv3::runProcessAtomic(), and SMMUv3::runProcessTiming().
scheduleWakeup()
void SMMUProcess::scheduleWakeup (Tick when) protected
Definition at line 195 of file smmu_v3_proc.cc.
References MipsISA::ep, EventManager::schedule(), smmu, SMMUProcess(), and wakeup().
Referenced by doDelay(), doSemaphoreUp(), and SMMUTranslationProcess::issuePrefetch().
wakeup()
void SMMUProcess::wakeup () private
Definition at line 57 of file smmu_v3_proc.cc.
References SMMUv3::runProcess(), and smmu.
Referenced by scheduleWakeup().
Member Data Documentation
coroutine
Coroutine* SMMUProcess::coroutine private
Definition at line 100 of file smmu_v3_proc.hh.
Referenced by reinit(), run(), and ~SMMUProcess().
myName
std::string SMMUProcess::myName private
Definition at line 101 of file smmu_v3_proc.hh.
smmu
SMMUv3& SMMUProcess::smmu protected
Definition at line 108 of file smmu_v3_proc.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), doDelay(), doRead(), SMMUTranslationProcess::doReadCD(), SMMUTranslationProcess::doReadSTE(), doWrite(), SMMUTranslationProcess::issuePrefetch(), SMMUCommandExecProcess::main(), SMMUTranslationProcess::main(), SMMUTranslationProcess::resumeTransaction(), scheduleWakeup(), SMMUTranslationProcess::sendEvent(), SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), SMMUTranslationProcess::smmuTranslation(), SMMUTranslationProcess::translateStage1And2(), SMMUTranslationProcess::translateStage2(), wakeup(), SMMUTranslationProcess::walkCacheLookup(), SMMUTranslationProcess::walkCacheUpdate(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_proc.hh
dev/arm/smmu_v3_proc.cc