gem5: FunctionProfile Class Reference
FunctionProfile Class Reference
#include <profile.hh>
Public Member Functions
FunctionProfile (const SymbolTable *symtab)
~FunctionProfile ()
ProfileNode * consume (ThreadContext *tc, const StaticInstPtr &inst)
ProfileNode * consume (const std::vector< Addr > &stack)
void clear ()
void dump (ThreadContext *tc, std::ostream &out) const
void sample (ProfileNode *node, Addr pc)
Private Attributes
Callback * reset
const SymbolTable * symtab
ProfileNode top
std::map< Addr, Counter > pc_count
TheISA::StackTrace trace
Detailed Description
Definition at line 63 of file profile.hh.
Constructor & Destructor Documentation
FunctionProfile()
FunctionProfile::FunctionProfile (const SymbolTable * symtab)
Definition at line 88 of file profile.cc.
References Stats::registerResetCallback(), and reset.
~FunctionProfile()
FunctionProfile::~FunctionProfile ()
Definition at line 95 of file profile.cc.
References reset.
Member Function Documentation
clear()
void FunctionProfile::clear ()
Definition at line 117 of file profile.cc.
References pc_count.
Referenced by ThreadState::profileClear().
consume() [1/2]
ProfileNode * FunctionProfile::consume (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 84 of file profile.hh.
Referenced by BaseSimpleCPU::postExecute().
consume() [2/2]
ProfileNode * FunctionProfile::consume (const std::vector< Addr > & stack)
Definition at line 102 of file profile.cc.
References ProfileNode::children, ArmISA::i, and top.
dump()
void FunctionProfile::dump (ThreadContext * tc, std::ostream & out) const
Definition at line 124 of file profile.cc.
References ccprintf(), X86ISA::count, SymbolTable::findSymbol(), ArmISA::i, MipsISA::pc, pc_count, and symtab.
Referenced by O3ThreadState< Impl >::dumpFuncProfile(), and SimpleThread::dumpFuncProfile().
sample()
void FunctionProfile::sample (ProfileNode * node, Addr pc)
Definition at line 146 of file profile.cc.
References ProfileNode::count, SymbolTable::findNearestAddr(), MipsISA::pc, pc_count, and symtab.
Referenced by ThreadState::profileSample().
Member Data Documentation
pc_count
std::map<Addr, Counter> FunctionProfile::pc_count private
Definition at line 69 of file profile.hh.
Referenced by clear(), dump(), and sample().
reset
Callback* FunctionProfile::reset private
Definition at line 66 of file profile.hh.
Referenced by FunctionProfile(), and ~FunctionProfile().
symtab
const SymbolTable* FunctionProfile::symtab private
Definition at line 67 of file profile.hh.
Referenced by dump(), and sample().
top
ProfileNode FunctionProfile::top private
Definition at line 68 of file profile.hh.
Referenced by consume().
trace
TheISA::StackTrace FunctionProfile::trace private
Definition at line 70 of file profile.hh.
The documentation for this class was generated from the following files:
cpu/profile.hh
cpu/profile.cc