gem5: IdleGen Class Reference
IdleGen Class Reference
The idle generator does nothing.
#include <idle_gen.hh>
Public Member Functions
IdleGen (SimObject &obj, MasterID master_id, Tick _duration)
void enter ()
Enter this generator state.
PacketPtr getNextPacket ()
Get the next generated packet.
Tick nextPacketTick (bool elastic, Tick delay) const
Determine the tick when the next packet is available.
Public Member Functions inherited from BaseGen
BaseGen (SimObject &obj, MasterID master_id, Tick _duration)
Create a base generator.
virtual ~BaseGen ()
std::string name () const
Get the name, useful for DPRINTFs.
virtual void exit ()
Exit this generator state.
Additional Inherited Members
Public Attributes inherited from BaseGen
const Tick duration
Time to spend in this state.
Protected Member Functions inherited from BaseGen
PacketPtr getPacket (Addr addr, unsigned size, const MemCmd &cmd, Request::FlagsType flags=0)
Generate a new request and associated packet.
Protected Attributes inherited from BaseGen
const std::string _name
Name to use for status and debug printing.
const MasterID masterID
The MasterID used for generating requests.
Detailed Description
The idle generator does nothing.
Definition at line 59 of file idle_gen.hh.
Constructor & Destructor Documentation
IdleGen()
IdleGen::IdleGen (SimObject & obj, MasterID master_id, Tick _duration) inline
Definition at line 64 of file idle_gen.hh.
References enter(), getNextPacket(), and nextPacketTick().
Member Function Documentation
enter()
void IdleGen::enter () virtual
Enter this generator state.
Implements BaseGen.
Definition at line 52 of file idle_gen.cc.
Referenced by IdleGen().
getNextPacket()
PacketPtr IdleGen::getNextPacket () virtual
Get the next generated packet.
Returns
A packet to be sent at the current tick
Implements BaseGen.
Definition at line 55 of file idle_gen.cc.
Referenced by IdleGen().
nextPacketTick()
Tick IdleGen::nextPacketTick (bool elastic, Tick delay) const virtual
Determine the tick when the next packet is available.
MaxTick means that there will not be any further packets in the current activation cycle of the generator.
Parameters
elastic should the injection respond to flow control or not
delay time the previous packet spent waiting
Returns
next tick when a packet is available
Implements BaseGen.
Definition at line 61 of file idle_gen.cc.
References MaxTick.
Referenced by IdleGen().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/idle_gen.hh
cpu/testers/traffic_gen/idle_gen.cc