gem5: GenericArmPciHost Class Reference
GenericArmPciHost Class Reference
#include <pci_host.hh>
Public Member Functions
GenericArmPciHost (const GenericArmPciHostParams *p)
virtual ~GenericArmPciHost ()
Public Member Functions inherited from GenericPciHost
GenericPciHost (const GenericPciHostParams *p)
virtual ~GenericPciHost ()
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Public Member Functions inherited from PciHost
PciHost (const PciHostParams *p)
virtual ~PciHost ()
virtual DeviceInterface registerDevice (PciDevice *device, PciBusAddr bus_addr, PciIntPin pin)
Register a PCI device with the host.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
uint32_t mapPciInterrupt (const PciBusAddr &addr, PciIntPin pin) const override
Protected Member Functions inherited from GenericPciHost
Addr pioAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of an IO location on the PCI bus.
Addr memAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of a non-prefetchable memory location in the PCI address space.
Addr dmaAddr (const PciBusAddr &bus_addr, Addr pci_addr) const override
Calculate the physical address of a prefetchable memory location in the PCI address space.
virtual std::pair< PciBusAddr, Addr > decodeAddress (Addr address)
Decode a configuration space address.
void postInt (const PciBusAddr &addr, PciIntPin pin) override
Post an interrupt to the CPU.
void clearInt (const PciBusAddr &addr, PciIntPin pin) override
Post an interrupt to the CPU.
Protected Member Functions inherited from PciHost
PciDevice * getDevice (const PciBusAddr &addr)
Retrieve a PCI device from its bus address.
const PciDevice * getDevice (const PciBusAddr &addr) const
Retrieve a PCI device from its bus address.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const Enums::ArmPciIntRouting intPolicy
const uint32_t intBase
const uint32_t intCount
Protected Attributes inherited from GenericPciHost
Platform & platform
const Addr confBase
const Addr confSize
const uint8_t confDeviceBits
const Addr pciPioBase
const Addr pciMemBase
const Addr pciDmaBase
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 49 of file pci_host.hh.
Constructor & Destructor Documentation
GenericArmPciHost()
GenericArmPciHost::GenericArmPciHost (const GenericArmPciHostParams * p)
Definition at line 44 of file pci_host.cc.
Referenced by mapPciInterrupt().
~GenericArmPciHost()
virtual GenericArmPciHost::~GenericArmPciHost () inline virtual
Definition at line 54 of file pci_host.hh.
References addr, and mapPciInterrupt().
Member Function Documentation
mapPciInterrupt()
uint32_t GenericArmPciHost::mapPciInterrupt (const PciBusAddr & addr, PciIntPin pin) const override protected virtual
Reimplemented from GenericPciHost.
Definition at line 53 of file pci_host.cc.
References PciBusAddr::bus, PciBusAddr::dev, fatal, fatal_if, PciBusAddr::func, GenericArmPciHost(), intBase, intCount, intPolicy, GenericPciHost::mapPciInterrupt(), and NO_INT.
Referenced by ~GenericArmPciHost().
Member Data Documentation
intBase
const uint32_t GenericArmPciHost::intBase protected
Definition at line 62 of file pci_host.hh.
Referenced by mapPciInterrupt().
intCount
const uint32_t GenericArmPciHost::intCount protected
Definition at line 63 of file pci_host.hh.
Referenced by mapPciInterrupt().
intPolicy
const Enums::ArmPciIntRouting GenericArmPciHost::intPolicy protected
Definition at line 61 of file pci_host.hh.
Referenced by mapPciInterrupt().
The documentation for this class was generated from the following files:
dev/arm/pci_host.hh
dev/arm/pci_host.cc