gem5: Stats::ScalarBase< Derived, Stor > Class Template Reference
Stats::ScalarBase< Derived, Stor > Class Template Reference
Implementation of a scalar stat.
#include <statistics.hh>
Public Types
typedef Stor Storage
typedef Stor::Params Params
Public Types inherited from Stats::DataWrap< Derived, ScalarInfoProxy >
typedef ScalarInfoProxy< Derived > Info
Public Member Functions
Counter value () const
Return the current value of this stat as its base type.
ScalarBase (Group *parent=nullptr, const char *name=nullptr, const char *desc=nullptr)
void operator++ ()
Increment the stat by 1.
void operator-- ()
Decrement the stat by 1.
void operator++ (int)
Increment the stat by 1.
void operator-- (int)
Decrement the stat by 1.
template<typename U >
void operator= (const U &v)
Set the data value to the given value.
template<typename U >
void operator+= (const U &v)
Increment the stat by the given value.
template<typename U >
void operator-= (const U &v)
Decrement the stat by the given value.
size_type size () const
Return the number of elements, always 1 for a scalar.
Counter value ()
Result result ()
Result total ()
bool zero ()
void reset ()
void prepare ()
Public Member Functions inherited from Stats::DataWrap< Derived, ScalarInfoProxy >
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
DataWrap & operator= (const DataWrap &)=delete
Derived & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Derived & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Derived & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Derived & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Derived & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
Derived & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Member Functions
char storage [sizeof(Storage)] __attribute__ ((aligned(8)))
The storage of this stat.
Storage * data ()
Retrieve the storage.
const Storage * data () const
Retrieve a const pointer to the storage.
void doInit ()
Protected Member Functions inherited from Stats::DataWrap< Derived, ScalarInfoProxy >
Derived & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Detailed Description
template<class Derived, class Stor>
class Stats::ScalarBase< Derived, Stor >
Implementation of a scalar stat.
The type of stat is determined by the Storage template.
Definition at line 657 of file statistics.hh.
Member Typedef Documentation
Params
template<class Derived, class Stor> typedef Stor::Params Stats::ScalarBase< Derived, Stor >::Params
Definition at line 661 of file statistics.hh.
Storage
template<class Derived, class Stor> typedef Stor Stats::ScalarBase< Derived, Stor >::Storage
Definition at line 660 of file statistics.hh.
Constructor & Destructor Documentation
ScalarBase()
template<class Derived, class Stor> Stats::ScalarBase< Derived, Stor >::ScalarBase (Group * parent = nullptr, const char * name = nullptr, const char * desc = nullptr) inline
Definition at line 706 of file statistics.hh.
Member Function Documentation
__attribute__()
template<class Derived, class Stor> char storage [sizeof(Storage)] Stats::ScalarBase< Derived, Stor >::__attribute__ ((aligned(8))) protected
The storage of this stat.
data() [1/2]
template<class Derived, class Stor> Storage* Stats::ScalarBase< Derived, Stor >::data () inline protected
Retrieve the storage.
Parameters
index The vector index to access.
Returns
The storage object at the given index.
Definition at line 674 of file statistics.hh.
data() [2/2]
template<class Derived, class Stor> const Storage* Stats::ScalarBase< Derived, Stor >::data () const inline protected
Retrieve a const pointer to the storage.
for the given index.
Parameters
index The vector index to access.
Returns
A const pointer to the storage object at the given index.
Definition at line 686 of file statistics.hh.
doInit()
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::doInit () inline protected
Definition at line 692 of file statistics.hh.
operator++() [1/2]
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::operator++ () inline
Increment the stat by 1.
This calls the associated storage object inc function.
Definition at line 719 of file statistics.hh.
operator++() [2/2]
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::operator++ (int) inline
Increment the stat by 1.
Definition at line 727 of file statistics.hh.
operator+=()
template<class Derived, class Stor> template<typename U > void Stats::ScalarBase< Derived, Stor >::operator+= (const U & v) inline
Increment the stat by the given value.
This calls the associated storage object inc function.
Parameters
v The value to add.
Definition at line 745 of file statistics.hh.
operator--() [1/2]
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::operator-- () inline
Decrement the stat by 1.
This calls the associated storage object dec function.
Definition at line 724 of file statistics.hh.
operator--() [2/2]
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::operator-- (int) inline
Decrement the stat by 1.
Definition at line 729 of file statistics.hh.
operator-=()
template<class Derived, class Stor> template<typename U > void Stats::ScalarBase< Derived, Stor >::operator-= (const U & v) inline
Decrement the stat by the given value.
This calls the associated storage object dec function.
Parameters
v The value to substract.
Definition at line 753 of file statistics.hh.
operator=()
template<class Derived, class Stor> template<typename U > void Stats::ScalarBase< Derived, Stor >::operator= (const U & v) inline
Set the data value to the given value.
This calls the associated storage object set function.
Parameters
v The new value.
Definition at line 737 of file statistics.hh.
prepare()
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::prepare () inline
Definition at line 770 of file statistics.hh.
reset()
template<class Derived, class Stor> void Stats::ScalarBase< Derived, Stor >::reset () inline
Definition at line 769 of file statistics.hh.
result()
template<class Derived, class Stor> Result Stats::ScalarBase< Derived, Stor >::result () inline
Definition at line 763 of file statistics.hh.
size()
template<class Derived, class Stor> size_type Stats::ScalarBase< Derived, Stor >::size () const inline
Return the number of elements, always 1 for a scalar.
Returns
1.
Definition at line 759 of file statistics.hh.
total()
template<class Derived, class Stor> Result Stats::ScalarBase< Derived, Stor >::total () inline
Definition at line 765 of file statistics.hh.
value() [1/2]
template<class Derived, class Stor> Counter Stats::ScalarBase< Derived, Stor >::value () const inline
Return the current value of this stat as its base type.
Returns
The current value.
Definition at line 703 of file statistics.hh.
Referenced by ElasticTrace::assignRobDep(), Wavefront::exec(), UFSHostDevice::finalUTP(), BaseTags::insertBlock(), ElasticTrace::recordExecTick(), UFSHostDevice::requestHandler(), TraceCPU::totalOps(), BaseTrafficGen::update(), TraceCPU::updateNumOps(), X86ISA::GpuTLB::updatePageFootprint(), DRAMCtrl::Rank::updatePowerStats(), and ElasticTrace::updateRegDep().
value() [2/2]
template<class Derived, class Stor> Counter Stats::ScalarBase< Derived, Stor >::value () inline
Definition at line 761 of file statistics.hh.
zero()
template<class Derived, class Stor> bool Stats::ScalarBase< Derived, Stor >::zero () inline
Definition at line 767 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh