gem5: sc_dt::sc_length_param Class Reference
sc_dt::sc_length_param Class Reference
#include <sc_length_param.hh>
Public Member Functions
sc_length_param ()
sc_length_param (int)
sc_length_param (const sc_length_param &)
sc_length_param (sc_without_context)
sc_length_param & operator= (const sc_length_param &)
int len () const
void len (int)
const std::string to_string () const
void print (::std::ostream &=::std::cout) const
void dump (::std::ostream &=::std::cout) const
Private Attributes
int m_len
Friends
bool operator== (const sc_length_param &, const sc_length_param &)
bool operator!= (const sc_length_param &, const sc_length_param &)
Detailed Description
Definition at line 82 of file sc_length_param.hh.
Constructor & Destructor Documentation
sc_length_param() [1/4]
sc_dt::sc_length_param::sc_length_param () inline
Definition at line 126 of file sc_length_param.hh.
References sc_dt::sc_context< T >::default_value().
sc_length_param() [2/4]
sc_dt::sc_length_param::sc_length_param (int len_) inline
Definition at line 131 of file sc_length_param.hh.
References SC_CHECK_WL_.
sc_length_param() [3/4]
sc_dt::sc_length_param::sc_length_param (const sc_length_param & a) inline
Definition at line 136 of file sc_length_param.hh.
sc_length_param() [4/4]
sc_dt::sc_length_param::sc_length_param (sc_without_context) inline explicit
Definition at line 140 of file sc_length_param.hh.
Member Function Documentation
dump()
void sc_dt::sc_length_param::dump (::std::ostream & os = ::std::cout) const
Definition at line 83 of file sc_length_param.cc.
References m_len.
len() [1/2]
int sc_dt::sc_length_param::len () const inline
Definition at line 169 of file sc_length_param.hh.
References m_len.
len() [2/2]
void sc_dt::sc_length_param::len (int len_) inline
Definition at line 175 of file sc_length_param.hh.
References m_len, and SC_CHECK_WL_.
operator=()
sc_length_param & sc_dt::sc_length_param::operator= (const sc_length_param & a) inline
Definition at line 146 of file sc_length_param.hh.
References m_len.
print()
void sc_dt::sc_length_param::print (::std::ostream & os = ::std::cout) const
Definition at line 77 of file sc_length_param.cc.
References m_len.
Referenced by sc_dt::operator<<(), and to_string().
to_string()
const std::string sc_dt::sc_length_param::to_string () const
Definition at line 69 of file sc_length_param.cc.
References print(), and ArmISA::ss.
Friends And Related Function Documentation
operator!=
bool operator!= (const sc_length_param & a, const sc_length_param & b) friend
Definition at line 162 of file sc_length_param.hh.
operator==
bool operator== (const sc_length_param & a, const sc_length_param & b) friend
Definition at line 156 of file sc_length_param.hh.
Member Data Documentation
m_len
int sc_dt::sc_length_param::m_len private
Definition at line 104 of file sc_length_param.hh.
Referenced by dump(), len(), sc_dt::operator!=(), operator=(), sc_dt::operator==(), and print().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_length_param.hh
systemc/dt/int/sc_length_param.cc