gem5: X86ISA::GpuTLB::CpuSidePort Class Reference
X86ISA::GpuTLB::CpuSidePort Class Reference
#include <gpu_tlb.hh>
Public Member Functions
CpuSidePort (const std::string &_name, GpuTLB *gpu_TLB, PortID _index)
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
virtual bool recvTimingReq (PacketPtr pkt)
Receive a timing request from the peer.
virtual Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the peer.
virtual void recvFunctional (PacketPtr pkt)
Receive a functional request packet from the peer.
virtual void recvRangeChange ()
virtual void recvReqRetry ()
virtual void recvRespRetry ()
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
GpuTLB * tlb
int index
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Definition at line 259 of file gpu_tlb.hh.
Constructor & Destructor Documentation
CpuSidePort()
X86ISA::GpuTLB::CpuSidePort::CpuSidePort (const std::string & _name, GpuTLB * gpu_TLB, PortID _index) inline
Definition at line 262 of file gpu_tlb.hh.
Member Function Documentation
getAddrRanges()
AddrRangeList X86ISA::GpuTLB::CpuSidePort::getAddrRanges () const protected virtual
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns
a list of ranges responded to
Implements SlavePort.
Definition at line 1601 of file gpu_tlb.cc.
recvAtomic()
virtual Tick X86ISA::GpuTLB::CpuSidePort::recvAtomic (PacketPtr pkt) inline protected virtual
Receive an atomic request packet from the peer.
Implements AtomicResponseProtocol.
Definition at line 271 of file gpu_tlb.hh.
recvFunctional()
void X86ISA::GpuTLB::CpuSidePort::recvFunctional (PacketPtr pkt) protected virtual
Receive a functional request packet from the peer.
Implements FunctionalResponseProtocol.
Definition at line 1480 of file gpu_tlb.cc.
References DPRINTF, BaseTLB::Execute, Process::fixupStackFault(), ThreadContext::getProcessPtr(), X86ISA::GpuTLB::globalNumTLBAccesses, X86ISA::GpuTLB::globalNumTLBHits, X86ISA::GpuTLB::globalNumTLBMisses, X86ISA::GpuTLB::handleFuncTranslationReturn(), X86ISA::GpuTLB::hasMemSidePort, X86ISA::GpuTLB::TranslationState::hitLevel, X86ISA::GpuTLB::lookup(), EmulationPageTable::lookup(), X86ISA::GpuTLB::memSidePort, X86ISA::p, EmulationPageTable::Entry::paddr, X86ISA::TlbEntry::paddr, EmulationPageTable::pageAlign(), AlphaISA::PageBytes, Process::pid(), X86ISA::GpuTLB::TranslationState::prefetch, Process::pTable, Packet::req, X86ISA::GpuTLB::TranslationState::reqCnt, roundDown(), safe_cast(), Packet::senderState, X86ISA::GpuTLB::TranslationState::tc, X86ISA::GpuTLB::TLBEvent::tlb, X86ISA::GpuTLB::TLB_HIT, X86ISA::GpuTLB::TLB_MISS, X86ISA::GpuTLB::TranslationState::tlbEntry, X86ISA::GpuTLB::tlbLookup(), X86ISA::GpuTLB::TranslationState::tlbMode, X86ISA::GpuTLB::updatePageFootprint(), X86ISA::TlbEntry::vaddr, and MipsISA::vaddr.
recvRangeChange()
virtual void X86ISA::GpuTLB::CpuSidePort::recvRangeChange () inline protected virtual
Definition at line 273 of file gpu_tlb.hh.
recvReqRetry()
void X86ISA::GpuTLB::CpuSidePort::recvReqRetry () protected virtual
Definition at line 1593 of file gpu_tlb.cc.
References panic.
recvRespRetry()
virtual void X86ISA::GpuTLB::CpuSidePort::recvRespRetry () inline protected virtual
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Implements TimingResponseProtocol.
Definition at line 275 of file gpu_tlb.hh.
References panic.
recvTimingReq()
bool X86ISA::GpuTLB::CpuSidePort::recvTimingReq (PacketPtr pkt) protected virtual
Receive a timing request from the peer.
Implements TimingResponseProtocol.
Definition at line 1387 of file gpu_tlb.cc.
References DPRINTF, X86ISA::GpuTLB::issueTLBLookup(), X86ISA::GpuTLB::maxCoalescedReqs, X86ISA::GpuTLB::outstandingReqs, and X86ISA::GpuTLB::TLBEvent::tlb.
Member Data Documentation
index
int X86ISA::GpuTLB::CpuSidePort::index protected
Definition at line 268 of file gpu_tlb.hh.
tlb
GpuTLB* X86ISA::GpuTLB::CpuSidePort::tlb protected
Definition at line 267 of file gpu_tlb.hh.
The documentation for this class was generated from the following files:
gpu-compute/gpu_tlb.hh
gpu-compute/gpu_tlb.cc