gem5: Check Class Reference
Check Class Reference
#include <Check.hh>
Public Member Functions
Check (Addr address, Addr pc, int _num_writers, int _num_readers, RubyTester *_tester)
void initiate ()
void performCallback (NodeID proc, SubBlock *data, Cycles curTime)
Addr getAddress () const
void changeAddress (Addr address)
void print (std::ostream &out) const
Private Member Functions
void initiateFlush ()
void initiatePrefetch ()
void initiateAction ()
void initiateCheck ()
void pickValue ()
void pickInitiatingNode ()
void debugPrint ()
Private Attributes
TesterStatus m_status
uint8_t m_value
int m_store_count
NodeID m_initiatingNode
Addr m_address
Addr m_pc
RubyAccessMode m_access_mode
int m_num_writers
int m_num_readers
RubyTester * m_tester_ptr
Detailed Description
Definition at line 45 of file Check.hh.
Constructor & Destructor Documentation
Check()
Check::Check (Addr address, Addr pc, int _num_writers, int _num_readers, RubyTester * _tester)
Definition at line 39 of file Check.cc.
References changeAddress(), m_access_mode, m_pc, m_status, m_store_count, MipsISA::pc, pickInitiatingNode(), pickValue(), Random::random(), and random_mt.
Member Function Documentation
changeAddress()
void Check::changeAddress (Addr address)
Definition at line 344 of file Check.cc.
References DPRINTF, m_address, m_status, and m_store_count.
Referenced by Check(), and getAddress().
debugPrint()
void Check::debugPrint () private
Definition at line 385 of file Check.cc.
References DPRINTF, m_address, m_initiatingNode, m_status, m_store_count, and m_value.
Referenced by getAddress(), initiate(), and performCallback().
getAddress()
Addr Check::getAddress () const inline
Definition at line 53 of file Check.hh.
References changeAddress(), debugPrint(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), m_address, pickInitiatingNode(), pickValue(), and print().
initiate()
void Check::initiate ()
Definition at line 56 of file Check.cc.
References debugPrint(), DPRINTF, RubyTester::getCheckFlush(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), m_status, m_tester_ptr, Random::random(), and random_mt.
Referenced by RubyTester::wakeup().
initiateAction()
void Check::initiateAction () private
Definition at line 167 of file Check.cc.
References curTick(), Packet::dataDynamic(), DPRINTF, Packet::getConstPtr(), RubyTester::getWritableCpuPort(), MipsISA::index, m_address, m_num_writers, m_pc, m_status, m_store_count, m_tester_ptr, m_value, RubyTester::masterId(), Random::random(), random_mt, Packet::senderState, MasterPort::sendTimingReq(), and MemCmd::WriteReq.
Referenced by getAddress(), and initiate().
initiateCheck()
void Check::initiateCheck () private
Definition at line 227 of file Check.cc.
References CHECK_SIZE, curTick(), Packet::dataDynamic(), DPRINTF, RubyTester::getReadableCpuPort(), MipsISA::index, Request::INST_FETCH, RubyTester::isInstDataCpuPort(), RubyTester::isInstOnlyCpuPort(), m_address, m_num_readers, m_pc, m_status, m_tester_ptr, RubyTester::masterId(), Random::random(), random_mt, MemCmd::ReadReq, Packet::senderState, MasterPort::sendTimingReq(), and Flags< T >::set().
Referenced by getAddress(), and initiate().
initiateFlush()
void Check::initiateFlush () private
Definition at line 138 of file Check.cc.
References CHECK_SIZE, curTick(), DPRINTF, MemCmd::FlushReq, RubyTester::getWritableCpuPort(), MipsISA::index, m_address, m_num_writers, m_pc, m_tester_ptr, RubyTester::masterId(), Random::random(), random_mt, Packet::senderState, and MasterPort::sendTimingReq().
Referenced by getAddress(), and initiate().
initiatePrefetch()
void Check::initiatePrefetch () private
Definition at line 82 of file Check.cc.
References curTick(), data, Packet::dataDynamic(), DPRINTF, RubyTester::getReadableCpuPort(), MipsISA::index, Request::INST_FETCH, RubyTester::isInstDataCpuPort(), RubyTester::isInstOnlyCpuPort(), m_address, m_num_readers, m_pc, m_tester_ptr, RubyTester::masterId(), Request::PF_EXCLUSIVE, Request::PREFETCH, Random::random(), random_mt, MemCmd::ReadReq, Packet::senderState, MasterPort::sendTimingReq(), Flags< T >::set(), and MemCmd::WriteReq.
Referenced by getAddress(), and initiate().
performCallback()
void Check::performCallback (NodeID proc, SubBlock * data, Cycles curTime)
Definition at line 280 of file Check.cc.
References CHECK_SIZE, debugPrint(), DPRINTF, SubBlock::getAddress(), SubBlock::getByte(), RubyTester::incrementCheckCompletions(), m_address, m_status, m_store_count, m_tester_ptr, m_value, makeLineAddress(), panic, pickValue(), and SubBlock::setByte().
Referenced by RubyTester::hitCallback().
pickInitiatingNode()
void Check::pickInitiatingNode () private
Definition at line 362 of file Check.cc.
References DPRINTF, m_address, m_initiatingNode, m_num_writers, m_status, m_store_count, Random::random(), and random_mt.
Referenced by Check(), and getAddress().
pickValue()
void Check::pickValue () private
Definition at line 354 of file Check.cc.
References m_status, m_store_count, m_value, Random::random(), and random_mt.
Referenced by Check(), getAddress(), and performCallback().
print()
void Check::print (std::ostream & out) const
Definition at line 373 of file Check.cc.
References m_address, m_initiatingNode, m_status, m_store_count, and m_value.
Referenced by getAddress(), and operator<<().
Member Data Documentation
m_access_mode
RubyAccessMode Check::m_access_mode private
Definition at line 75 of file Check.hh.
Referenced by Check().
m_address
Addr Check::m_address private
Definition at line 73 of file Check.hh.
Referenced by changeAddress(), debugPrint(), getAddress(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), performCallback(), pickInitiatingNode(), and print().
m_initiatingNode
NodeID Check::m_initiatingNode private
Definition at line 72 of file Check.hh.
Referenced by debugPrint(), pickInitiatingNode(), and print().
m_num_readers
int Check::m_num_readers private
Definition at line 77 of file Check.hh.
Referenced by initiateCheck(), and initiatePrefetch().
m_num_writers
int Check::m_num_writers private
Definition at line 76 of file Check.hh.
Referenced by initiateAction(), initiateFlush(), and pickInitiatingNode().
m_pc
Addr Check::m_pc private
Definition at line 74 of file Check.hh.
Referenced by Check(), initiateAction(), initiateCheck(), initiateFlush(), and initiatePrefetch().
m_status
TesterStatus Check::m_status private
Definition at line 69 of file Check.hh.
Referenced by changeAddress(), Check(), debugPrint(), initiate(), initiateAction(), initiateCheck(), performCallback(), pickInitiatingNode(), pickValue(), and print().
m_store_count
int Check::m_store_count private
Definition at line 71 of file Check.hh.
Referenced by changeAddress(), Check(), debugPrint(), initiateAction(), performCallback(), pickInitiatingNode(), pickValue(), and print().
m_tester_ptr
RubyTester* Check::m_tester_ptr private
Definition at line 78 of file Check.hh.
Referenced by initiate(), initiateAction(), initiateCheck(), initiateFlush(), initiatePrefetch(), and performCallback().
m_value
uint8_t Check::m_value private
Definition at line 70 of file Check.hh.
Referenced by debugPrint(), initiateAction(), performCallback(), pickValue(), and print().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/Check.hh
cpu/testers/rubytest/Check.cc