gem5: sc_dt::sc_int_bitref_r Class Reference
sc_dt::sc_int_bitref_r Class Reference
#include <sc_int_base.hh>
Public Member Functions
sc_int_bitref_r (const sc_int_bitref_r &a)
virtual ~sc_int_bitref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_int_bitref_r ()
void initialize (const sc_int_base *obj_p, int index_)
Protected Attributes
int m_index
sc_int_base * m_obj_p
Private Member Functions
sc_int_bitref_r & operator= (const sc_int_bitref_r &)
Friends
class sc_int_base
Detailed Description
Definition at line 138 of file sc_int_base.hh.
Constructor & Destructor Documentation
sc_int_bitref_r() [1/2]
sc_dt::sc_int_bitref_r::sc_int_bitref_r () inline protected
Definition at line 144 of file sc_int_base.hh.
sc_int_bitref_r() [2/2]
sc_dt::sc_int_bitref_r::sc_int_bitref_r (const sc_int_bitref_r & a) inline
Definition at line 155 of file sc_int_base.hh.
~sc_int_bitref_r()
virtual sc_dt::sc_int_bitref_r::~sc_int_bitref_r () inline virtual
Definition at line 160 of file sc_int_base.hh.
Member Function Documentation
concat_get_ctrl()
virtual bool sc_dt::sc_int_bitref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 178 of file sc_int_base.hh.
References BITS_PER_DIGIT.
concat_get_data()
virtual bool sc_dt::sc_int_bitref_r::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 187 of file sc_int_base.hh.
References BITS_PER_DIGIT.
concat_get_uint64()
virtual uint64 sc_dt::sc_int_bitref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 203 of file sc_int_base.hh.
References sc_dt::operator~().
concat_length()
virtual int sc_dt::sc_int_bitref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 171 of file sc_int_base.hh.
initialize()
void sc_dt::sc_int_bitref_r::initialize (const sc_int_base * obj_p, int index_) inline protected
Definition at line 147 of file sc_int_base.hh.
Referenced by sc_dt::sc_int_base::bit(), and sc_dt::sc_int_base::operator[]().
length()
int sc_dt::sc_int_bitref_r::length () const inline
Definition at line 163 of file sc_int_base.hh.
References length.
operator uint64()
sc_dt::sc_int_bitref_r::operator uint64 () const inline
Definition at line 954 of file sc_int_base.hh.
operator!()
bool sc_dt::sc_int_bitref_r::operator! () const inline
Definition at line 960 of file sc_int_base.hh.
operator=()
sc_int_bitref_r& sc_dt::sc_int_bitref_r::operator= (const sc_int_bitref_r &) private
operator~()
bool sc_dt::sc_int_bitref_r::operator~ () const inline
Definition at line 966 of file sc_int_base.hh.
print()
void sc_dt::sc_int_bitref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 222 of file sc_int_base.hh.
References X86ISA::os, and to_bool().
Referenced by sc_dt::operator<<().
to_bool()
bool sc_dt::sc_int_bitref_r::to_bool () const inline
Definition at line 218 of file sc_int_base.hh.
value()
uint64 sc_dt::sc_int_bitref_r::value () const inline
Definition at line 216 of file sc_int_base.hh.
Friends And Related Function Documentation
sc_int_base
friend class sc_int_base friend
Definition at line 140 of file sc_int_base.hh.
Member Data Documentation
m_index
int sc_dt::sc_int_bitref_r::m_index protected
Definition at line 225 of file sc_int_base.hh.
m_obj_p
sc_int_base* sc_dt::sc_int_bitref_r::m_obj_p protected
Definition at line 226 of file sc_int_base.hh.
The documentation for this class was generated from the following file:
systemc/ext/dt/int/sc_int_base.hh