gem5: RefCountingPtr< T > Class Template Reference
RefCountingPtr< T > Class Template Reference
If you want a reference counting pointer to a mutable object, create it like this:
#include <refcnt.hh>
Public Types
using PtrType = T *
Public Member Functions
RefCountingPtr ()
Create an empty reference counting pointer.
RefCountingPtr (T *data)
Create a new reference counting pointer to some object (probably something newly created).
RefCountingPtr (const RefCountingPtr &r)
Create a new reference counting pointer by copying another one.
RefCountingPtr (RefCountingPtr &&r)
Move-constructor.
template<bool B = TisConst>
RefCountingPtr (const NonConstT &r)
~RefCountingPtr ()
Destroy the pointer and any reference it may hold.
T * operator-> () const
Access a member variable.
T & operator* () const
Dereference the pointer.
T * get () const
Directly access the pointer itself without taking a reference.
template<bool B = TisConst>
operator RefCountingPtr< typename std::enable_if<!B, ConstT >::type > ()
const RefCountingPtr & operator= (T *p)
Assign a new value to the pointer.
const RefCountingPtr & operator= (const RefCountingPtr &r)
Copy the pointer from another RefCountingPtr.
const RefCountingPtr & operator= (RefCountingPtr &&r)
Move-assign the pointer from another RefCountingPtr.
bool operator! () const
Check if the pointer is empty.
operator bool () const
Check if the pointer is non-empty.
Protected Member Functions
void copy (T *d)
Copy a new pointer value and increment the reference count if it is a valid pointer.
void del ()
Delete the reference to any existing object if it is non NULL.
void set (T *d)
Drop the old reference and change it to something new.
Protected Attributes
T * data
The stored pointer.
using ConstT = typename std::conditional< TisConst, RefCountingPtr< T >, RefCountingPtr< typename std::add_const< T >::type > >::type
using NonConstT = typename std::conditional< TisConst, RefCountingPtr< typename std::remove_const< T >::type >, RefCountingPtr< T > >::type
static constexpr auto TisConst = std::is_const<T>::value
Convenience aliases for const/non-const versions of T w/ friendship.
friend ConstT
friend NonConstT
Detailed Description
template<class T>
class RefCountingPtr< T >
If you want a reference counting pointer to a mutable object, create it like this:
typedef RefCountingPtr<Foo> FooPtr;
Attention
Do not use "const FooPtr" To create a reference counting pointer to a const object, use this:
typedef RefCountingPtr<const Foo> ConstFooPtr;
These two usages are analogous to iterator and const_iterator in the stl.
Definition at line 120 of file refcnt.hh.
Member Typedef Documentation
ConstT
template<class T> using RefCountingPtr< T >::ConstT = typename std::conditional<TisConst, RefCountingPtr<T>, RefCountingPtr<typename std::add_const<T>::type> >::type protected
Definition at line 131 of file refcnt.hh.
NonConstT
template<class T> using RefCountingPtr< T >::NonConstT = typename std::conditional<TisConst, RefCountingPtr<typename std::remove_const<T>::type>, RefCountingPtr<T> >::type protected
Definition at line 135 of file refcnt.hh.
PtrType
template<class T> using RefCountingPtr< T >::PtrType = T*
Definition at line 123 of file refcnt.hh.
Constructor & Destructor Documentation
RefCountingPtr() [1/5]
template<class T> RefCountingPtr< T >::RefCountingPtr () inline
Create an empty reference counting pointer.
Definition at line 185 of file refcnt.hh.
RefCountingPtr() [2/5]
template<class T> RefCountingPtr< T >::RefCountingPtr (T * data) inline
Create a new reference counting pointer to some object (probably something newly created).
Adds a reference.
Definition at line 189 of file refcnt.hh.
RefCountingPtr() [3/5]
template<class T> RefCountingPtr< T >::RefCountingPtr (const RefCountingPtr< T > & r) inline
Create a new reference counting pointer by copying another one.
Adds a reference.
Definition at line 193 of file refcnt.hh.
RefCountingPtr() [4/5]
template<class T> RefCountingPtr< T >::RefCountingPtr (RefCountingPtr< T > && r) inline
Move-constructor.
Does not add a reference.
Definition at line 198 of file refcnt.hh.
RefCountingPtr() [5/5]
template<class T> template<bool B = TisConst> RefCountingPtr< T >::RefCountingPtr (const NonConstT & r) inline
Definition at line 205 of file refcnt.hh.
~RefCountingPtr()
template<class T> RefCountingPtr< T >::~RefCountingPtr () inline
Destroy the pointer and any reference it may hold.
Definition at line 208 of file refcnt.hh.
Member Function Documentation
copy()
template<class T> void RefCountingPtr< T >::copy (T * d) inline protected
Copy a new pointer value and increment the reference count if it is a valid pointer.
Note, this does not delete the reference any existing object.
Parameters
d Pointer to store.
Definition at line 149 of file refcnt.hh.
del()
template<class T> void RefCountingPtr< T >::del () inline protected
Delete the reference to any existing object if it is non NULL.
Attention
this doesn't clear the pointer value, so a double decref could happen if not careful.
Definition at line 162 of file refcnt.hh.
get()
template<class T> T* RefCountingPtr< T >::get () const inline
Directly access the pointer itself without taking a reference.
Definition at line 221 of file refcnt.hh.
Referenced by Trace::TarmacParserRecord::dump(), BaseO3DynInst< Impl >::forwardOldRegs(), ArmISA::ArmFault::instrAnnotate(), ArmISA::UndefinedInstruction::invoke(), operator!=(), operator==(), Trace::TarmacTracerRecord::TraceInstEntry::TraceInstEntry(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateInt(), ArmISA::VldMultOp::VldMultOp(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VstMultOp::VstMultOp(), and ArmISA::VstSingleOp::VstSingleOp().
operator bool()
template<class T> RefCountingPtr< T >::operator bool () const inline
Check if the pointer is non-empty.
Definition at line 252 of file refcnt.hh.
operator RefCountingPtr< typename std::enable_if::type >()
template<class T> template<bool B = TisConst> RefCountingPtr< T >::operator RefCountingPtr< typename std::enable_if<!B, ConstT >::type > () inline
Definition at line 224 of file refcnt.hh.
operator!()
template<class T> bool RefCountingPtr< T >::operator! () const inline
Check if the pointer is empty.
Definition at line 249 of file refcnt.hh.
operator*()
template<class T> T& RefCountingPtr< T >::operator* () const inline
Dereference the pointer.
Definition at line 218 of file refcnt.hh.
operator->()
template<class T> T* RefCountingPtr< T >::operator-> () const inline
Access a member variable.
Definition at line 215 of file refcnt.hh.
operator=() [1/3]
template<class T> const RefCountingPtr& RefCountingPtr< T >::operator= (T * p) inline
Assign a new value to the pointer.
Definition at line 230 of file refcnt.hh.
operator=() [2/3]
template<class T> const RefCountingPtr& RefCountingPtr< T >::operator= (const RefCountingPtr< T > & r) inline
Copy the pointer from another RefCountingPtr.
Definition at line 233 of file refcnt.hh.
operator=() [3/3]
template<class T> const RefCountingPtr& RefCountingPtr< T >::operator= (RefCountingPtr< T > && r) inline
Move-assign the pointer from another RefCountingPtr.
Definition at line 237 of file refcnt.hh.
set()
template<class T> void RefCountingPtr< T >::set (T * d) inline protected
Drop the old reference and change it to something new.
Definition at line 172 of file refcnt.hh.
Member Data Documentation
ConstT
template<class T> friend RefCountingPtr< T >::ConstT protected
Definition at line 132 of file refcnt.hh.
data
template<class T> T* RefCountingPtr< T >::data protected
The stored pointer.
Arguably this should be private.
Definition at line 140 of file refcnt.hh.
Referenced by RefCountingPtr< MinorDynInst >::operator=(), and RefCountingPtr< MinorDynInst >::RefCountingPtr().
NonConstT
template<class T> friend RefCountingPtr< T >::NonConstT protected
Definition at line 136 of file refcnt.hh.
TisConst
template<class T> constexpr auto RefCountingPtr< T >::TisConst = std::is_const<T>::value static protected
Convenience aliases for const/non-const versions of T w/ friendship.
Definition at line 128 of file refcnt.hh.
The documentation for this class was generated from the following file:
base/refcnt.hh