gem5: RiscvISA::BreakpointFault Class Reference
RiscvISA::BreakpointFault Class Reference
#include <faults.hh>
Public Member Functions
BreakpointFault (const PCState &pc)
RegVal trap_value () const override
void invokeSE (ThreadContext *tc, const StaticInstPtr &inst) override
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Private Attributes
const PCState pcState
Additional Inherited Members
Protected Member Functions inherited from RiscvISA::RiscvFault
RiscvFault (FaultName n, bool i, ExceptionCode c)
FaultName name () const override
bool isInterrupt () const
ExceptionCode exception () const
void invoke (ThreadContext *tc, const StaticInstPtr &inst) override
Protected Attributes inherited from RiscvISA::RiscvFault
const FaultName _name
const bool _interrupt
ExceptionCode _code
Detailed Description
Definition at line 212 of file faults.hh.
Constructor & Destructor Documentation
BreakpointFault()
RiscvISA::BreakpointFault::BreakpointFault (const PCState & pc) inline
Definition at line 218 of file faults.hh.
Member Function Documentation
invokeSE()
void RiscvISA::BreakpointFault::invokeSE (ThreadContext * tc, const StaticInstPtr & inst) override virtual
Reimplemented from RiscvISA::RiscvFault.
Definition at line 185 of file faults.cc.
References schedRelBreak().
trap_value()
RegVal RiscvISA::BreakpointFault::trap_value () const inline override virtual
Reimplemented from RiscvISA::RiscvFault.
Definition at line 222 of file faults.hh.
References RiscvISA::RiscvFault::invokeSE(), and GenericISA::SimplePCState< MachInst >::pc().
Member Data Documentation
pcState
const PCState RiscvISA::BreakpointFault::pcState private
Definition at line 215 of file faults.hh.
The documentation for this class was generated from the following files:
arch/riscv/faults.hh
arch/riscv/faults.cc