gem5: ArmPPI Class Reference
ArmPPI Class Reference
#include <base_gic.hh>
Public Member Functions
void raise () override
Signal an interrupt.
void clear () override
Clear a signalled interrupt.
Public Member Functions inherited from ArmInterruptPin
void setThreadContext (ThreadContext *tc)
Set the thread context owning this interrupt.
uint32_t num () const
Get interrupt number.
Private Member Functions
ArmPPI (Platform *platform, ThreadContext *tc, uint32_t int_num)
Friends
class ArmPPIGen
Additional Inherited Members
Protected Member Functions inherited from ArmInterruptPin
ArmInterruptPin (Platform *platform, ThreadContext *tc, uint32_t int_num)
ContextID targetContext () const
Get the target context ID of this interrupt.
Protected Attributes inherited from ArmInterruptPin
const ThreadContext * threadContext
Pointer to the thread context that owns this interrupt in case it is a thread-/CPU-private interrupt.
RealView *const platform
Arm platform to use for interrupt generation.
const uint32_t intNum
Interrupt number to generate.
Detailed Description
Definition at line 236 of file base_gic.hh.
Constructor & Destructor Documentation
ArmPPI()
ArmPPI::ArmPPI (Platform * platform, ThreadContext * tc, uint32_t int_num) private
Definition at line 166 of file base_gic.cc.
Member Function Documentation
clear()
void ArmPPI::clear () override virtual
Clear a signalled interrupt.
Implements ArmInterruptPin.
Definition at line 179 of file base_gic.cc.
References ArmPPIGen, BaseGic::clearPPInt(), RealView::gic, ArmInterruptPin::intNum, ArmInterruptPin::platform, and ArmInterruptPin::targetContext().
raise()
void ArmPPI::raise () override virtual
Signal an interrupt.
Implements ArmInterruptPin.
Definition at line 173 of file base_gic.cc.
References RealView::gic, ArmInterruptPin::intNum, ArmInterruptPin::platform, BaseGic::sendPPInt(), and ArmInterruptPin::targetContext().
Friends And Related Function Documentation
ArmPPIGen
friend class ArmPPIGen friend
Definition at line 238 of file base_gic.hh.
Referenced by clear().
The documentation for this class was generated from the following files:
dev/arm/base_gic.hh
dev/arm/base_gic.cc