gem5: SimpleMemory Class Reference
SimpleMemory Class Reference
The simple memory is a basic single-ported memory controller with a configurable throughput and latency.
#include <simple_mem.hh>
Classes
class DeferredPacket
A deferred packet stores a packet along with its scheduled transmission time.
class MemoryPort
Public Member Functions
SimpleMemory (const SimpleMemoryParams *p)
DrainState drain () override
Notify an object that it needs to drain its state.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void init () override
Initialise this memory.
Public Member Functions inherited from AbstractMemory
AbstractMemory (const Params *p)
virtual ~AbstractMemory ()
bool isNull () const
See if this is a null memory that should never store data and always return zero.
void setBackingStore (uint8_t *pmem_addr)
Set the host memory backing store to be used by this memory controller.
const std::list< LockedAddr > & getLockedAddrList () const
Get the list of locked addresses to allow checkpointing.
void addLockedAddr (LockedAddr addr)
Add a locked address to allow for checkpointing.
System * system () const
read the system pointer Implemented for completeness with the setter
void system (System *sys)
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
const Params * params () const
AddrRange getAddrRange () const
Get the address range.
uint64_t size () const
Get the memory size.
Addr start () const
Get the start address.
bool isConfReported () const
Should this memory be passed to the kernel and part of the OS physical memory layout.
bool isInAddrMap () const
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
bool isKvmMap () const
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &_backdoor)
void recvFunctional (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
void recvRespRetry ()
Protected Member Functions inherited from AbstractMemory
bool checkLockedAddrList (PacketPtr pkt)
void trackLoadLocked (PacketPtr pkt)
bool writeOK (PacketPtr pkt)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Private Member Functions
void release ()
Release the memory after being busy and send a retry if a request was rejected in the meanwhile.
void dequeue ()
Dequeue a packet from our internal packet queue and move it to the port where it will be sent as soon as possible.
Tick getLatency () const
Detemine the latency.
Private Attributes
MemoryPort port
const Tick latency
Latency from that a request is accepted until the response is ready to be sent.
const Tick latency_var
Fudge factor added to the latency.
std::list< DeferredPacket > packetQueue
Internal (unbounded) storage to mimic the delay caused by the actual memory access.
const double bandwidth
Bandwidth in ticks per byte.
bool isBusy
Track the state of the memory as either idle or busy, no need for an enum with only two states.
bool retryReq
Remember if we have to retry an outstanding request that arrived while we were busy.
bool retryResp
Remember if we failed to send a response and are awaiting a retry.
EventFunctionWrapper releaseEvent
EventFunctionWrapper dequeueEvent
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Additional Inherited Members
Public Types inherited from AbstractMemory
typedef AbstractMemoryParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from AbstractMemory
AddrRange range
uint8_t * pmemAddr
MemBackdoor backdoor
const bool confTableReported
const bool inAddrMap
const bool kvmMap
std::list< LockedAddr > lockedAddrList
System * _system
Pointer to the System object.
AbstractMemory::MemStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
The simple memory is a basic single-ported memory controller with a configurable throughput and latency.
See also
gem5 Memory System
Definition at line 64 of file simple_mem.hh.
Constructor & Destructor Documentation
SimpleMemory()
SimpleMemory::SimpleMemory (const SimpleMemoryParams * p)
Definition at line 51 of file simple_mem.cc.
References dequeue(), dequeueEvent, SimObject::name(), and release().
Referenced by SimpleMemory::MemoryPort::recvRespRetry().
Member Function Documentation
dequeue()
void SimpleMemory::dequeue () private
Dequeue a packet from our internal packet queue and move it to the port where it will be sent as soon as possible.
Definition at line 205 of file simple_mem.cc.
References curTick(), dequeueEvent, DPRINTF, Draining, Drainable::drainState(), packetQueue, port, EventManager::reschedule(), retryResp, SlavePort::sendTimingResp(), and Drainable::signalDrainDone().
Referenced by recvRespRetry(), and SimpleMemory().
drain()
DrainState SimpleMemory::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 255 of file simple_mem.cc.
References DPRINTF, Drained, Draining, and packetQueue.
getLatency()
Tick SimpleMemory::getLatency () const private
Detemine the latency.
Returns
the latency seen by the current packet
Definition at line 230 of file simple_mem.cc.
References latency, latency_var, Random::random(), and random_mt.
Referenced by recvAtomic(), and recvTimingReq().
getPort()
Port & SimpleMemory::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 245 of file simple_mem.cc.
References SimObject::getPort(), and port.
init()
void SimpleMemory::init () override virtual
Initialise this memory.
Reimplemented from AbstractMemory.
Definition at line 62 of file simple_mem.cc.
References AbstractMemory::init(), Port::isConnected(), port, and SlavePort::sendRangeChange().
recvAtomic()
Tick SimpleMemory::recvAtomic (PacketPtr pkt) protected
Definition at line 74 of file simple_mem.cc.
References AbstractMemory::access(), Packet::cacheResponding(), getLatency(), and panic_if.
Referenced by recvAtomicBackdoor(), and recvTimingReq().
recvAtomicBackdoor()
Tick SimpleMemory::recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & _backdoor) protected
Definition at line 84 of file simple_mem.cc.
References AbstractMemory::backdoor, latency, MemBackdoor::ptr(), and recvAtomic().
recvFunctional()
void SimpleMemory::recvFunctional (PacketPtr pkt) protected
Definition at line 94 of file simple_mem.cc.
References AbstractMemory::functionalAccess(), SimObject::name(), MipsISA::p, packetQueue, Packet::popLabel(), Packet::pushLabel(), and Packet::trySatisfyFunctional().
recvRespRetry()
void SimpleMemory::recvRespRetry () protected
Definition at line 237 of file simple_mem.cc.
References dequeue(), and retryResp.
recvTimingReq()
bool SimpleMemory::recvTimingReq (PacketPtr pkt) protected
Definition at line 112 of file simple_mem.cc.
References bandwidth, Packet::cacheResponding(), Packet::cmdString(), curTick(), dequeueEvent, Packet::getAddr(), getLatency(), Packet::getSize(), Packet::headerDelay, ArmISA::i, isBusy, Packet::isRead(), Packet::isResponse(), Packet::isWrite(), Packet::needsResponse(), packetQueue, panic_if, Packet::payloadDelay, pendingDelete, recvAtomic(), releaseEvent, retryReq, retryResp, EventManager::schedule(), and Event::scheduled().
release()
void SimpleMemory::release () private
Release the memory after being busy and send a retry if a request was rejected in the meanwhile.
Definition at line 194 of file simple_mem.cc.
References isBusy, port, retryReq, and SlavePort::sendRetryReq().
Referenced by SimpleMemory().
Member Data Documentation
bandwidth
const double SimpleMemory::bandwidth private
Bandwidth in ticks per byte.
The regulation affects the acceptance rate of requests and the queueing takes place after the regulation.
Definition at line 128 of file simple_mem.hh.
Referenced by recvTimingReq().
dequeueEvent
EventFunctionWrapper SimpleMemory::dequeueEvent private
Definition at line 162 of file simple_mem.hh.
Referenced by dequeue(), recvTimingReq(), and SimpleMemory().
isBusy
bool SimpleMemory::isBusy private
Track the state of the memory as either idle or busy, no need for an enum with only two states.
Definition at line 134 of file simple_mem.hh.
Referenced by recvTimingReq(), and release().
latency
const Tick SimpleMemory::latency private
Latency from that a request is accepted until the response is ready to be sent.
Definition at line 109 of file simple_mem.hh.
Referenced by getLatency(), and recvAtomicBackdoor().
latency_var
const Tick SimpleMemory::latency_var private
Fudge factor added to the latency.
Definition at line 114 of file simple_mem.hh.
Referenced by getLatency().
packetQueue
std::list<DeferredPacket> SimpleMemory::packetQueue private
Internal (unbounded) storage to mimic the delay caused by the actual memory access.
Note that this is where the packet spends the memory latency.
Definition at line 121 of file simple_mem.hh.
Referenced by dequeue(), drain(), recvFunctional(), and recvTimingReq().
pendingDelete
std::unique_ptr<Packet> SimpleMemory::pendingDelete private
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Definition at line 175 of file simple_mem.hh.
Referenced by recvTimingReq().
port
MemoryPort SimpleMemory::port private
Definition at line 103 of file simple_mem.hh.
Referenced by dequeue(), getPort(), init(), and release().
releaseEvent
EventFunctionWrapper SimpleMemory::releaseEvent private
Definition at line 154 of file simple_mem.hh.
Referenced by recvTimingReq().
retryReq
bool SimpleMemory::retryReq private
Remember if we have to retry an outstanding request that arrived while we were busy.
Definition at line 140 of file simple_mem.hh.
Referenced by recvTimingReq(), and release().
retryResp
bool SimpleMemory::retryResp private
Remember if we failed to send a response and are awaiting a retry.
This is only used as a check.
Definition at line 146 of file simple_mem.hh.
Referenced by dequeue(), recvRespRetry(), and recvTimingReq().
The documentation for this class was generated from the following files:
mem/simple_mem.hh
mem/simple_mem.cc