gem5: ArmInterruptPin Class Reference
ArmInterruptPin Class Reference abstract
Generic representation of an Arm interrupt pin.
#include <base_gic.hh>
Public Member Functions
void setThreadContext (ThreadContext *tc)
Set the thread context owning this interrupt.
uint32_t num () const
Get interrupt number.
virtual void raise ()=0
Signal an interrupt.
virtual void clear ()=0
Clear a signalled interrupt.
Protected Member Functions
ArmInterruptPin (Platform *platform, ThreadContext *tc, uint32_t int_num)
ContextID targetContext () const
Get the target context ID of this interrupt.
Protected Attributes
const ThreadContext * threadContext
Pointer to the thread context that owns this interrupt in case it is a thread-/CPU-private interrupt.
RealView *const platform
Arm platform to use for interrupt generation.
const uint32_t intNum
Interrupt number to generate.
Friends
class ArmInterruptPinGen
Detailed Description
Generic representation of an Arm interrupt pin.
Definition at line 178 of file base_gic.hh.
Constructor & Destructor Documentation
ArmInterruptPin()
ArmInterruptPin::ArmInterruptPin (Platform * platform, ThreadContext * tc, uint32_t int_num) protected
Definition at line 123 of file base_gic.cc.
References fatal_if, and platform.
Member Function Documentation
clear()
virtual void ArmInterruptPin::clear () pure virtual
Clear a signalled interrupt.
Implemented in ArmPPI, and ArmSPI.
Referenced by ArmISA::PMU::clearInterrupt(), and MmioVirtIO::setInterrupts().
num()
uint32_t ArmInterruptPin::num () const inline
Get interrupt number.
Definition at line 196 of file base_gic.hh.
raise()
virtual void ArmInterruptPin::raise () pure virtual
Signal an interrupt.
Implemented in ArmPPI, and ArmSPI.
Referenced by ArchTimer::counterLimitReached(), ArmISA::PMU::raiseInterrupt(), MmioVirtIO::setInterrupts(), CpuLocalTimer::Timer::timerAtZero(), Gicv3CPUInterface::virtualUpdate(), and CpuLocalTimer::Timer::watchdogAtZero().
setThreadContext()
void ArmInterruptPin::setThreadContext (ThreadContext * tc)
Set the thread context owning this interrupt.
This method is used to set the thread context for interrupts that are thread/CPU-specific. Only devices that are used in such a context are expected to call this method.
Definition at line 132 of file base_gic.cc.
References panic_if, and threadContext.
targetContext()
ContextID ArmInterruptPin::targetContext () const protected
Get the target context ID of this interrupt.
Precondition
setThreadContext() must have been called prior to calling this method.
Definition at line 141 of file base_gic.cc.
References ThreadContext::contextId(), panic_if, and threadContext.
Referenced by ArmPPI::clear(), and ArmPPI::raise().
Friends And Related Function Documentation
ArmInterruptPinGen
friend class ArmInterruptPinGen friend
Definition at line 180 of file base_gic.hh.
Member Data Documentation
intNum
const uint32_t ArmInterruptPin::intNum protected
Interrupt number to generate.
Definition at line 222 of file base_gic.hh.
Referenced by ArmSPI::clear(), ArmPPI::clear(), ArmSPI::raise(), and ArmPPI::raise().
platform
RealView* const ArmInterruptPin::platform protected
Arm platform to use for interrupt generation.
Definition at line 219 of file base_gic.hh.
Referenced by ArmInterruptPin(), ArmSPI::clear(), ArmPPI::clear(), ArmSPI::raise(), and ArmPPI::raise().
threadContext
const ThreadContext* ArmInterruptPin::threadContext protected
Pointer to the thread context that owns this interrupt in case it is a thread-/CPU-private interrupt.
Definition at line 216 of file base_gic.hh.
Referenced by setThreadContext(), and targetContext().
The documentation for this class was generated from the following files:
dev/arm/base_gic.hh
dev/arm/base_gic.cc