gem5: SerialDevice Class Reference
SerialDevice Class Reference abstract
Base class for serial devices such as terminals.
#include <serial.hh>
Public Member Functions
SerialDevice (const SerialDeviceParams *p)
~SerialDevice ()
void regInterfaceCallback (Callback *c)
Register a data available callback into the host interface layer.
virtual bool dataAvailable () const =0
Check if there is pending data from the serial device.
virtual void writeData (uint8_t c)=0
Transmit a character from the host interface to the device.
virtual uint8_t readData ()=0
Read a character from the device.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void notifyInterface ()
Notify the host interface of pending data.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Attributes
Callback * interfaceCallback
Currently regisxtered host interface layer callback.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Base class for serial devices such as terminals.
This class provides a unified interface that all serial (RS232 or similar) devices must implement. A device can be wired to exactly one host serial interface (serial port model).
SerialDevices are passive devices that are driven by the serial interface using the writeData(c) (the interface sends a character) and readData() (the interface reads a character) methods. Serial devices need to override these methods to communicate with the host interface layer.
To implement basic flow control, serial devices must implement the dataAvailable() method. This method returns true if a valid character can be read using the readData() method. When data becomes available, the serial device must call the notifyInterface() method to send a callback to the interface layer.
To send a character (host to device), the interface layer calls writeData(char) to send a character to the serial device.
To read a character (device to host), the interface layer calls dataAvailable() to determine if there is a character pending. If there is data available, it immediately calls readData() to get the character. The receive loop in the serial device typically looks like this:
while (device.dataAvailable()) {
   printf("%c", (int)device.readData());
}
To avoid polling, the interface layer may register a data available callback using the regInterfaceCallback() method. The device uses this callback to notify the interface layer whenever there is new data pending. Note that devices will normally only notify the interface layer when there is a state transition in the device. E.g., the dataAvailable() transitions from false to true. This means that there can be multiple pending characters when the interface layer receives the callback.
Definition at line 92 of file serial.hh.
Constructor & Destructor Documentation
SerialDevice()
SerialDevice::SerialDevice (const SerialDeviceParams * p)
Definition at line 46 of file serial.cc.
~SerialDevice()
SerialDevice::~SerialDevice ()
Definition at line 51 of file serial.cc.
Member Function Documentation
dataAvailable()
virtual bool SerialDevice::dataAvailable () const pure virtual
Check if there is pending data from the serial device.
Returns
true if there is data pending that can be read using the readData() method.
Implemented in SerialNullDevice, and Terminal.
Referenced by notifyInterface(), SimpleUart::read(), Pl011::read(), Uart8250::read(), Pl011::write(), and Uart8250::write().
notifyInterface()
void SerialDevice::notifyInterface () protected
Notify the host interface of pending data.
Definition at line 67 of file serial.cc.
References dataAvailable(), interfaceCallback, and Callback::process().
Referenced by Terminal::data().
readData()
virtual uint8_t SerialDevice::readData () pure virtual
Read a character from the device.
Returns
Character from the device's output buffer, undefined if no data is pending.
Implemented in SerialNullDevice, and Terminal.
Referenced by SimpleUart::read(), Pl011::read(), Uart8250::read(), and SerialNullDevice::writeData().
regInterfaceCallback()
void SerialDevice::regInterfaceCallback (Callback * c)
Register a data available callback into the host interface layer.
Serial devices need to call the underlying host interface layer to inform it of state change such as pending data that can be read from the device by the interface layer using the readData() method. The interface layer may use this method to register a callback that informs it of pending data.
Parameters
c Callback instance from interface layer.
Definition at line 56 of file serial.cc.
References ArmISA::c, fatal, and interfaceCallback.
Referenced by Uart::Uart(), and VirtIOConsole::VirtIOConsole().
writeData()
virtual void SerialDevice::writeData (uint8_t c) pure virtual
Transmit a character from the host interface to the device.
Parameters
c Received data.
Implemented in SerialNullDevice, and Terminal.
Referenced by SimpleUart::write(), Pl011::write(), and Uart8250::write().
Member Data Documentation
interfaceCallback
Callback* SerialDevice::interfaceCallback private
Currently regisxtered host interface layer callback.
Definition at line 141 of file serial.hh.
Referenced by notifyInterface(), and regInterfaceCallback().
The documentation for this class was generated from the following files:
dev/serial/serial.hh
dev/serial/serial.cc