gem5: EthPacketData Class Reference
EthPacketData Class Reference
#include <etherpkt.hh>
Public Member Functions
EthPacketData ()
EthPacketData (unsigned size)
~EthPacketData ()
void serialize (const std::string &base, CheckpointOut &cp) const
void unserialize (const std::string &base, CheckpointIn &cp)
Public Attributes
uint8_t * data
Pointer to packet data will be deleted.
unsigned bufLength
Total size of the allocated data buffer.
unsigned length
Amount of space occupied by the payload in the data buffer.
unsigned simLength
Effective length, used for modeling timing in the simulator.
Detailed Description
Definition at line 49 of file etherpkt.hh.
Constructor & Destructor Documentation
EthPacketData() [1/2]
EthPacketData::EthPacketData () inline
Definition at line 76 of file etherpkt.hh.
EthPacketData() [2/2]
EthPacketData::EthPacketData (unsigned size) inline explicit
Definition at line 80 of file etherpkt.hh.
~EthPacketData()
EthPacketData::~EthPacketData () inline
Definition at line 84 of file etherpkt.hh.
References X86ISA::base, data, serialize(), and unserialize().
Member Function Documentation
serialize()
void EthPacketData::serialize (const std::string & base, CheckpointOut & cp) const
Definition at line 42 of file etherpkt.cc.
References arrayParamOut(), data, length, and paramOut().
Referenced by ~EthPacketData().
unserialize()
void EthPacketData::unserialize (const std::string & base, CheckpointIn & cp)
Definition at line 51 of file etherpkt.cc.
References arrayParamIn(), data, length, optParamIn(), and paramIn().
Referenced by ~EthPacketData().
Member Data Documentation
bufLength
unsigned EthPacketData::bufLength
Total size of the allocated data buffer.
Definition at line 60 of file etherpkt.hh.
data
uint8_t* EthPacketData::data
Pointer to packet data will be deleted.
Definition at line 55 of file etherpkt.hh.
Referenced by ~EthPacketData().
length
unsigned EthPacketData::length
Amount of space occupied by the payload in the data buffer.
Definition at line 65 of file etherpkt.hh.
simLength
unsigned EthPacketData::simLength
Effective length, used for modeling timing in the simulator.
This could be different from length if the packets are assumed to use a tightly packed or compressed format, but it's not worth the performance/complexity hit to perform that packing or compression in the simulation.
Definition at line 74 of file etherpkt.hh.
The documentation for this class was generated from the following files:
dev/net/etherpkt.hh
dev/net/etherpkt.cc