gem5: Net::UdpPtr Class Reference
Net::UdpPtr Class Reference
#include <inet.hh>
Public Member Functions
UdpPtr ()
UdpPtr (const IpPtr &ptr)
UdpPtr (const Ip6Ptr &ptr)
UdpPtr (const UdpPtr &ptr)
UdpHdr * get ()
UdpHdr * operator-> ()
UdpHdr & operator* ()
const UdpHdr * get () const
const UdpHdr * operator-> () const
const UdpHdr & operator* () const
const UdpPtr & operator= (const IpPtr &i)
const UdpPtr & operator= (const UdpPtr &t)
const EthPacketPtr packet () const
EthPacketPtr packet ()
bool operator! () const
operator bool () const
int off () const
int pstart () const
Protected Member Functions
void set (const EthPacketPtr &ptr, int offset)
void set (const IpPtr &ptr)
void set (const Ip6Ptr &ptr)
Protected Attributes
EthPacketPtr p
int _off
Detailed Description
Definition at line 631 of file inet.hh.
Constructor & Destructor Documentation
UdpPtr() [1/4]
Net::UdpPtr::UdpPtr () inline
Definition at line 654 of file inet.hh.
UdpPtr() [2/4]
Net::UdpPtr::UdpPtr (const IpPtr & ptr) inline
Definition at line 655 of file inet.hh.
UdpPtr() [3/4]
Net::UdpPtr::UdpPtr (const Ip6Ptr & ptr) inline
Definition at line 656 of file inet.hh.
UdpPtr() [4/4]
Net::UdpPtr::UdpPtr (const UdpPtr & ptr) inline
Definition at line 657 of file inet.hh.
Member Function Documentation
get() [1/2]
UdpHdr* Net::UdpPtr::get () inline
Definition at line 659 of file inet.hh.
get() [2/2]
const UdpHdr* Net::UdpPtr::get () const inline
Definition at line 663 of file inet.hh.
off()
int Net::UdpPtr::off () const inline
Definition at line 675 of file inet.hh.
operator bool()
Net::UdpPtr::operator bool () const inline
Definition at line 674 of file inet.hh.
operator!()
bool Net::UdpPtr::operator! () const inline
Definition at line 673 of file inet.hh.
References MipsISA::p.
operator*() [1/2]
UdpHdr& Net::UdpPtr::operator* () inline
Definition at line 661 of file inet.hh.
operator*() [2/2]
const UdpHdr& Net::UdpPtr::operator* () const inline
Definition at line 665 of file inet.hh.
operator->() [1/2]
UdpHdr* Net::UdpPtr::operator-> () inline
Definition at line 660 of file inet.hh.
operator->() [2/2]
const UdpHdr* Net::UdpPtr::operator-> () const inline
Definition at line 664 of file inet.hh.
operator=() [1/2]
const UdpPtr& Net::UdpPtr::operator= (const IpPtr & i) inline
Definition at line 667 of file inet.hh.
References ArmISA::i.
operator=() [2/2]
const UdpPtr& Net::UdpPtr::operator= (const UdpPtr & t) inline
Definition at line 668 of file inet.hh.
References _off, and p.
packet() [1/2]
const EthPacketPtr Net::UdpPtr::packet () const inline
Definition at line 671 of file inet.hh.
References MipsISA::p.
Referenced by Net::cksum().
packet() [2/2]
EthPacketPtr Net::UdpPtr::packet () inline
Definition at line 672 of file inet.hh.
References MipsISA::p.
pstart()
int Net::UdpPtr::pstart () const inline
Definition at line 676 of file inet.hh.
References Net::__tu_cksum(), Net::__tu_cksum6(), Net::cksum(), Net::hsplit(), iGbReg::TxdOp::ip(), MipsISA::ip6, and Net::EthAddr::size().
Referenced by Net::hsplit().
set() [1/3]
void Net::UdpPtr::set (const EthPacketPtr & ptr, int offset) inline protected
Definition at line 637 of file inet.hh.
References ArmISA::offset.
set() [2/3]
void Net::UdpPtr::set (const IpPtr & ptr) inline protected
Definition at line 638 of file inet.hh.
set() [3/3]
void Net::UdpPtr::set (const Ip6Ptr & ptr) inline protected
Definition at line 645 of file inet.hh.
Member Data Documentation
_off
int Net::UdpPtr::_off protected
Definition at line 635 of file inet.hh.
Referenced by operator=().
p
EthPacketPtr Net::UdpPtr::p protected
Definition at line 634 of file inet.hh.
Referenced by operator=().
The documentation for this class was generated from the following file:
base/inet.hh