gem5: tlm_utils::instance_specific_extension_accessor Class Reference
tlm_utils::instance_specific_extension_accessor Class Reference
#include <instance_specific_extensions_int.h>
Public Member Functions
instance_specific_extension_accessor ()
template<typename T >
instance_specific_extensions_per_accessor & operator() (T &txn)
Static Protected Member Functions
template<typename T >
static void release_carrier (instance_specific_extension_carrier *, void *txn)
Protected Attributes
unsigned int m_index
Detailed Description
Definition at line 165 of file instance_specific_extensions_int.h.
Constructor & Destructor Documentation
instance_specific_extension_accessor()
tlm_utils::instance_specific_extension_accessor::instance_specific_extension_accessor ()
Definition at line 261 of file instance_specific_extensions.cc.
Member Function Documentation
operator()()
template<typename T > instance_specific_extensions_per_accessor & tlm_utils::instance_specific_extension_accessor::operator() (T & txn) inline
Definition at line 102 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extension_container::attach_carrier(), tlm_utils::instance_specific_extension_container::create(), tlm_utils::instance_specific_extension_container::get_accessor(), and tlm_utils::instance_specific_extension_carrier::m_container.
release_carrier()
template<typename T > void tlm_utils::instance_specific_extension_accessor::release_carrier (instance_specific_extension_carrier * carrier, void * txn) static protected
Definition at line 118 of file instance_specific_extensions.h.
Member Data Documentation
m_index
unsigned int tlm_utils::instance_specific_extension_accessor::m_index protected
Definition at line 179 of file instance_specific_extensions_int.h.
The documentation for this class was generated from the following files:
systemc/ext/tlm_utils/instance_specific_extensions_int.h
systemc/ext/tlm_utils/instance_specific_extensions.h
systemc/tlm_utils/instance_specific_extensions.cc