gem5: TAGE_SC_L_LoopPredictor Class Reference
TAGE_SC_L_LoopPredictor Class Reference
#include <tage_sc_l.hh>
Public Member Functions
TAGE_SC_L_LoopPredictor (TAGE_SC_L_LoopPredictorParams *p)
virtual bool calcConf (int index) const override
virtual bool optionalAgeInc () const override
Public Member Functions inherited from LoopPredictor
int lindex (Addr pc_in, unsigned instShiftAmt) const
Computes the index used to access the loop predictor.
int finallindex (int lindex, int lowPcBits, int way) const
Computes the index used to access the ltable structures.
bool getLoop (Addr pc, BranchInfo *bi, bool speculative, unsigned instShiftAmt) const
Get a branch prediction from the loop predictor.
void loopUpdate (Addr pc, bool Taken, BranchInfo *bi, bool tage_pred)
Updates the loop predictor.
void specLoopUpdate (bool taken, BranchInfo *bi)
Speculatively updates the loop predictor iteration count (only for useSpeculation).
void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, bool tage_pred, BranchInfo *bi, unsigned instShiftAmt)
Update LTAGE for conditional branches.
bool loopPredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo *bi, bool prev_pred_taken, unsigned instShiftAmt)
Get the loop prediction.
void updateStats (bool taken, BranchInfo *bi)
Update the stats.
void squashLoop (BranchInfo *bi)
void squash (ThreadID tid, BranchInfo *bi)
virtual BranchInfo * makeBranchInfo ()
int8_t getLoopUseCounter () const
Gets the value of the loop use counter.
void init () override
Initialize the loop predictor.
void regStats () override
Register stats for this object.
LoopPredictor (LoopPredictorParams *p)
size_t getSizeInBits () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Static Protected Member Functions inherited from LoopPredictor
static void unsignedCtrUpdate (uint8_t &ctr, bool up, unsigned nbits)
Updates an unsigned counter based on up/down parameter.
static void signedCtrUpdate (int8_t &ctr, bool up, unsigned nbits)
Protected Attributes inherited from LoopPredictor
const unsigned logSizeLoopPred
const unsigned loopTableAgeBits
const unsigned loopTableConfidenceBits
const unsigned loopTableTagBits
const unsigned loopTableIterBits
const unsigned logLoopTableAssoc
const uint8_t confidenceThreshold
const uint16_t loopTagMask
const uint16_t loopNumIterMask
const int loopSetMask
LoopEntry * ltable
int8_t loopUseCounter
unsigned withLoopBits
const bool useDirectionBit
const bool useSpeculation
const bool useHashing
const bool restrictAllocation
const unsigned initialLoopIter
const unsigned initialLoopAge
const bool optionalAgeReset
Stats::Scalar loopPredictorCorrect
Stats::Scalar loopPredictorWrong
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 137 of file tage_sc_l.hh.
Constructor & Destructor Documentation
TAGE_SC_L_LoopPredictor()
TAGE_SC_L_LoopPredictor::TAGE_SC_L_LoopPredictor (TAGE_SC_L_LoopPredictorParams * p) inline
Definition at line 140 of file tage_sc_l.hh.
References MipsISA::index.
Referenced by optionalAgeInc().
Member Function Documentation
calcConf()
bool TAGE_SC_L_LoopPredictor::calcConf (int index) const override virtual
Reimplemented from LoopPredictor.
Definition at line 49 of file tage_sc_l.cc.
References LoopPredictor::calcConf(), LoopPredictor::LoopEntry::confidence, MipsISA::index, LoopPredictor::ltable, and LoopPredictor::LoopEntry::numIter.
optionalAgeInc()
bool TAGE_SC_L_LoopPredictor::optionalAgeInc () const override virtual
Reimplemented from LoopPredictor.
Definition at line 56 of file tage_sc_l.cc.
References Random::random(), random_mt, and TAGE_SC_L_LoopPredictor().
The documentation for this class was generated from the following files:
cpu/pred/tage_sc_l.hh
cpu/pred/tage_sc_l.cc