gem5: TraceCPU Class Reference
TraceCPU Class Reference
The trace cpu replays traces generated using the elastic trace probe attached to the O3 CPU model.
#include <trace_cpu.hh>
Classes
class DcachePort
DcachePort class that interfaces with L1 Data Cache.
class ElasticDataGen
The elastic data memory request generator to read protobuf trace containing execution trace annotated with data and ordering dependencies.
class FixedRetryGen
Generator to read protobuf trace containing memory requests at fixed timestamps, perform flow control and issue memory requests.
class IcachePort
IcachePort class that interfaces with L1 Instruction Cache.
Public Member Functions
TraceCPU (TraceCPUParams *params)
~TraceCPU ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
Counter totalInsts () const
This is a pure virtual function in BaseCPU.
Counter totalOps () const
Return totalOps as the number of committed micro-ops plus the speculatively issued loads that are modelled in the TraceCPU replay.
void updateNumOps (uint64_t rob_num)
void wakeup (ThreadID tid=0)
void takeOverFrom (BaseCPU *oldCPU)
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void icacheRetryRecvd ()
When instruction cache port receives a retry, schedule event icacheNextEvent.
void dcacheRetryRecvd ()
When data cache port receives a retry, schedule event dcacheNextEvent.
void dcacheRecvTimingResp (PacketPtr pkt)
When data cache port receives a response, this calls the dcache generator method handle to complete the load writeback.
void schedDcacheNextEvent (Tick when)
Schedule event dcacheNextEvent at the given tick.
Port & getInstPort ()
Used to get a reference to the icache port.
Port & getDataPort ()
Used to get a reference to the dcache port.
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
virtual void activateContext (ThreadID thread_num)
Notify the CPU that the indicated context is now active.
virtual void suspendContext (ThreadID thread_num)
Notify the CPU that the indicated context is now suspended.
virtual void haltContext (ThreadID thread_num)
Notify the CPU that the indicated context is now halted.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
virtual ThreadContext * getContext (int tn)
Given a thread num get tho thread context for it.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void startup () override
startup() is the final initialization call before simulation.
void regProbePoints () override
Register probe points for this object.
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
virtual void switchOut ()
Prepare for another CPU to take over execution.
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
virtual void verifyMemoryMode () const
Verify that the system is in a memory mode supported by the CPU.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
virtual void serializeThread (CheckpointOut &cp, ThreadID tid) const
Serialize a single thread.
virtual void unserializeThread (CheckpointIn &cp, ThreadID tid)
Unserialize one thread.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void schedIcacheNext ()
This is the control flow that uses the functionality of the icacheGen to replay the trace.
void schedDcacheNext ()
This is the control flow that uses the functionality of the dcacheGen to replay the trace.
void checkAndSchedExitEvent ()
This is called when either generator finishes executing from the trace.
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
IcachePort icachePort
Port to connect to L1 instruction cache.
DcachePort dcachePort
Port to connect to L1 data cache.
const MasterID instMasterID
Master id for instruction read requests.
const MasterID dataMasterID
Master id for data read and write requests.
std::string instTraceFile
File names for input instruction and data traces.
std::string dataTraceFile
FixedRetryGen icacheGen
Instance of FixedRetryGen to replay instruction read requests.
ElasticDataGen dcacheGen
Instance of ElasticDataGen to replay data read and write requests.
EventFunctionWrapper icacheNextEvent
Event for the control flow method schedIcacheNext()
EventFunctionWrapper dcacheNextEvent
Event for the control flow method schedDcacheNext()
bool oneTraceComplete
Set to true when one of the generators finishes replaying its trace.
Tick traceOffset
This stores the time offset in the trace, which is taken away from the ready times of requests.
CountedExitEvent * execCompleteEvent
A CountedExitEvent which when serviced decrements the counter.
const bool enableEarlyExit
Exit when any one Trace CPU completes its execution.
const uint64_t progressMsgInterval
Interval of committed instructions specified by the user at which a progress info message is printed.
uint64_t progressMsgThreshold
Stats::Scalar numSchedDcacheEvent
Stats::Scalar numSchedIcacheEvent
Stats::Scalar numOps
Stat for number of simulated micro-ops.
Stats::Formula cpi
Stat for the CPI.
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static int numTraceCPUs = 0
Number of Trace CPUs in the system used as a shared variable and passed to the CountedExitEvent event used for counting down exit events.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Detailed Description
The trace cpu replays traces generated using the elastic trace probe attached to the O3 CPU model.
The elastic trace is an execution trace with register data dependencies and ordering dependencies annotated to it. The trace cpu also replays a fixed timestamp fetch trace that is also generated by the elastic trace probe. This trace cpu model aims at achieving faster simulation compared to the detailed cpu model and good correlation when the same trace is used for playback on different memory sub-systems.
The TraceCPU inherits from BaseCPU so some virtual methods need to be defined. It has two port subclasses inherited from MasterPort for instruction and data ports. It issues the memory requests deducing the timing from the trace and without performing real execution of micro-ops. As soon as the last dependency for an instruction is complete, its computational delay, also provided in the input trace is added. The dependency-free nodes are maintained in a list, called 'ReadyList', ordered by ready time. Instructions which depend on load stall until the responses for read requests are received thus achieving elastic replay. If the dependency is not found when adding a new node, it is assumed complete. Thus, if this node is found to be completely dependency-free its issue time is calculated and it is added to the ready list immediately. This is encapsulated in the subclass ElasticDataGen.
If ready nodes are issued in an unconstrained way there can be more nodes outstanding which results in divergence in timing compared to the O3CPU. Therefore, the Trace CPU also models hardware resources. A sub-class to model hardware resources contains the maximum sizes of load buffer, store buffer and ROB. If resources are not available, the node is not issued. Such nodes that are pending issue are held in the 'depFreeQueue' structure.
Modeling the ROB size in the Trace CPU as a resource limitation is arguably the most important parameter of all resources. The ROB occupancy is estimated using the newly added field 'robNum'. We need to use ROB number as sequence number is at times much higher due to squashing and trace replay is focused on correct path modeling.
A map called 'inFlightNodes' is added to track nodes that are not only in the readyList but also load nodes that are executed (and thus removed from readyList) but are not complete. ReadyList handles what and when to execute next node while the inFlightNodes is used for resource modelling. The oldest ROB number is updated when any node occupies the ROB or when an entry in the ROB is released. The ROB occupancy is equal to the difference in the ROB number of the newly dependency-free node and the oldest ROB number in flight.
If no node depends on a non load/store node then there is no reason to track it in the dependency graph. We filter out such nodes but count them and add a weight field to the subsequent node that we do include in the trace. The weight field is used to model ROB occupancy during replay.
The depFreeQueue is chosen to be FIFO so that child nodes which are in program order get pushed into it in that order and thus issued in program order, like in the O3CPU. This is also why the dependents is made a sequential container, std::set to std::vector. We only check head of the depFreeQueue as nodes are issued in order and blocking on head models that better than looping the entire queue. An alternative choice would be to inspect top N pending nodes where N is the issue-width. This is left for future as the timing correlation looks good as it is.
At the start of an execution event, first we attempt to issue such pending nodes by checking if appropriate resources have become available. If yes, we compute the execute tick with respect to the time then. Then we proceed to complete nodes from the readyList.
When a read response is received, sometimes a dependency on it that was supposed to be released when it was issued is still not released. This occurs because the dependent gets added to the graph after the read was sent. So the check is made less strict and the dependency is marked complete on read response instead of insisting that it should have been removed on read sent.
There is a check for requests spanning two cache lines as this condition triggers an assert fail in the L1 cache. If it does then truncate the size to access only until the end of that line and ignore the remainder. Strictly-ordered requests are skipped and the dependencies on such requests are handled by simply marking them complete immediately.
A CountedExitEvent that contains a static int belonging to the Trace CPU class as a down counter is used to implement multi Trace CPU simulation exit.
Definition at line 144 of file trace_cpu.hh.
Constructor & Destructor Documentation
TraceCPU()
TraceCPU::TraceCPU (TraceCPUParams * params)
Definition at line 49 of file trace_cpu.cc.
References dcacheNextEvent, enableEarlyExit, execCompleteEvent, fatal_if, SimObject::name(), numTraceCPUs, oneTraceComplete, BaseCPU::params(), progressMsgInterval, progressMsgThreshold, schedDcacheNext(), schedIcacheNext(), and traceOffset.
Referenced by ~TraceCPU().
~TraceCPU()
TraceCPU::~TraceCPU ()
Definition at line 84 of file trace_cpu.cc.
References TraceCPU().
Member Function Documentation
checkAndSchedExitEvent()
void TraceCPU::checkAndSchedExitEvent () protected
This is called when either generator finishes executing from the trace.
Definition at line 196 of file trace_cpu.cc.
References curTick(), enableEarlyExit, execCompleteEvent, exitSimLoop(), inform, SimObject::name(), oneTraceComplete, and EventManager::schedule().
Referenced by schedDcacheNext(), and schedIcacheNext().
dcacheRecvTimingResp()
void TraceCPU::dcacheRecvTimingResp (PacketPtr pkt)
When data cache port receives a response, this calls the dcache generator method handle to complete the load writeback.
Parameters
pkt Pointer to packet received
Definition at line 1233 of file trace_cpu.cc.
References TraceCPU::ElasticDataGen::completeMemAccess(), dcacheGen, and DPRINTF.
Referenced by TraceCPU::DcachePort::recvTimingResp(), and wakeup().
dcacheRetryRecvd()
void TraceCPU::dcacheRetryRecvd ()
When data cache port receives a retry, schedule event dcacheNextEvent.
Definition at line 1191 of file trace_cpu.cc.
References curTick(), dcacheNextEvent, DPRINTF, and EventManager::schedule().
Referenced by TraceCPU::DcachePort::recvReqRetry(), and wakeup().
getDataPort()
Port& TraceCPU::getDataPort () inline virtual
Used to get a reference to the dcache port.
Implements BaseCPU.
Definition at line 1152 of file trace_cpu.hh.
References dcachePort, and regStats().
Referenced by takeOverFrom().
getInstPort()
Port& TraceCPU::getInstPort () inline virtual
Used to get a reference to the icache port.
Implements BaseCPU.
Definition at line 1149 of file trace_cpu.hh.
References icachePort.
Referenced by takeOverFrom().
icacheRetryRecvd()
void TraceCPU::icacheRetryRecvd ()
When instruction cache port receives a retry, schedule event icacheNextEvent.
Definition at line 1181 of file trace_cpu.cc.
References curTick(), DPRINTF, icacheNextEvent, and EventManager::schedule().
Referenced by TraceCPU::IcachePort::recvReqRetry(), and wakeup().
init()
void TraceCPU::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseCPU.
Definition at line 114 of file trace_cpu.cc.
References TraceCPU::ElasticDataGen::adjustInitTraceOffset(), dataTraceFile, dcacheGen, dcacheNextEvent, DPRINTF, enableEarlyExit, execCompleteEvent, icacheGen, icacheNextEvent, inform, BaseCPU::init(), TraceCPU::FixedRetryGen::init(), TraceCPU::ElasticDataGen::init(), instTraceFile, SimObject::name(), numTraceCPUs, EventManager::schedule(), and traceOffset.
Referenced by TraceCPU::ElasticDataGen::ElasticDataGen(), and TraceCPU::FixedRetryGen::FixedRetryGen().
regStats()
void TraceCPU::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from BaseCPU.
Definition at line 217 of file trace_cpu.cc.
References cpi, dcacheGen, Stats::DataWrap< Derived, InfoProxyType >::desc(), icacheGen, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), BaseCPU::numCycles, numOps, numSchedDcacheEvent, numSchedIcacheEvent, Stats::DataWrap< Derived, InfoProxyType >::precision(), BaseCPU::regStats(), TraceCPU::FixedRetryGen::regStats(), and TraceCPU::ElasticDataGen::regStats().
Referenced by getDataPort(), TraceCPU::ElasticDataGen::getMicroOpCount(), and TraceCPU::FixedRetryGen::tickDelta().
schedDcacheNext()
void TraceCPU::schedDcacheNext () protected
This is the control flow that uses the functionality of the dcacheGen to replay the trace.
It calls execute(). It checks if execution is complete and schedules an event to exit simulation accordingly.
Definition at line 182 of file trace_cpu.cc.
References checkAndSchedExitEvent(), Clocked::clockEdge(), Clocked::clockPeriod(), dcacheGen, DPRINTF, TraceCPU::ElasticDataGen::execute(), TraceCPU::ElasticDataGen::isExecComplete(), and BaseCPU::numCycles.
Referenced by TraceCPU().
schedDcacheNextEvent()
void TraceCPU::schedDcacheNextEvent (Tick when)
Schedule event dcacheNextEvent at the given tick.
Parameters
when Tick at which to schedule event
Definition at line 1201 of file trace_cpu.cc.
References dcacheNextEvent, DPRINTF, numSchedDcacheEvent, EventManager::reschedule(), EventManager::schedule(), Event::scheduled(), and Event::when().
Referenced by wakeup().
schedIcacheNext()
void TraceCPU::schedIcacheNext () protected
This is the control flow that uses the functionality of the icacheGen to replay the trace.
It calls tryNext(). If it returns true then next event is scheduled at curTick() plus delta. If it returns false then delta is ignored and control is brought back via recvRetry().
Definition at line 157 of file trace_cpu.cc.
References checkAndSchedExitEvent(), curTick(), DPRINTF, icacheGen, icacheNextEvent, TraceCPU::FixedRetryGen::isTraceComplete(), numSchedIcacheEvent, EventManager::schedule(), TraceCPU::FixedRetryGen::tickDelta(), and TraceCPU::FixedRetryGen::tryNext().
Referenced by TraceCPU().
takeOverFrom()
void TraceCPU::takeOverFrom (BaseCPU * cpu) virtual
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
A CPU model implementing this method is expected to initialize its state from the old CPU and connect its memory (unless they are already connected) to the memories connected to the old CPU.
Parameters
cpu CPU to initialize read state from.
Reimplemented from BaseCPU.
Definition at line 106 of file trace_cpu.cc.
References BaseCPU::getDataPort(), getDataPort(), BaseCPU::getInstPort(), getInstPort(), and Port::takeOverFrom().
Referenced by wakeup().
totalInsts()
Counter TraceCPU::totalInsts () const inline virtual
This is a pure virtual function in BaseCPU.
As we don't know how many insts are in the trace but only know how how many micro-ops are we cannot count this stat.
Returns
0
Implements BaseCPU.
Definition at line 160 of file trace_cpu.hh.
totalOps()
Counter TraceCPU::totalOps () const inline virtual
Return totalOps as the number of committed micro-ops plus the speculatively issued loads that are modelled in the TraceCPU replay.
Returns
number of micro-ops i.e. nodes in the elastic data generator
Implements BaseCPU.
Definition at line 171 of file trace_cpu.hh.
References numOps, updateNumOps(), and Stats::ScalarBase< Derived, Stor >::value().
updateNumOps()
void TraceCPU::updateNumOps (uint64_t rob_num)
Definition at line 96 of file trace_cpu.cc.
References inform, SimObject::name(), numOps, progressMsgInterval, progressMsgThreshold, and Stats::ScalarBase< Derived, Stor >::value().
Referenced by totalOps().
wakeup()
void TraceCPU::wakeup (ThreadID tid = 0) inline virtual
Implements BaseCPU.
Definition at line 183 of file trace_cpu.hh.
References dcacheRecvTimingResp(), dcacheRetryRecvd(), icacheRetryRecvd(), schedDcacheNextEvent(), and takeOverFrom().
Member Data Documentation
cpi
Stats::Formula TraceCPU::cpi protected
Stat for the CPI.
This is really cycles per micro-op and not inst.
Definition at line 1144 of file trace_cpu.hh.
Referenced by regStats().
dataMasterID
const MasterID TraceCPU::dataMasterID protected
Master id for data read and write requests.
Definition at line 332 of file trace_cpu.hh.
dataTraceFile
std::string TraceCPU::dataTraceFile protected
Definition at line 335 of file trace_cpu.hh.
Referenced by init().
dcacheGen
ElasticDataGen TraceCPU::dcacheGen protected
Instance of ElasticDataGen to replay data read and write requests.
Definition at line 1067 of file trace_cpu.hh.
Referenced by dcacheRecvTimingResp(), init(), regStats(), and schedDcacheNext().
dcacheNextEvent
EventFunctionWrapper TraceCPU::dcacheNextEvent protected
Event for the control flow method schedDcacheNext()
Definition at line 1088 of file trace_cpu.hh.
Referenced by dcacheRetryRecvd(), init(), schedDcacheNextEvent(), and TraceCPU().
dcachePort
DcachePort TraceCPU::dcachePort protected
Port to connect to L1 data cache.
Definition at line 326 of file trace_cpu.hh.
Referenced by getDataPort().
enableEarlyExit
const bool TraceCPU::enableEarlyExit protected
Exit when any one Trace CPU completes its execution.
If this is configured true then the execCompleteEvent is not scheduled.
Definition at line 1123 of file trace_cpu.hh.
Referenced by checkAndSchedExitEvent(), init(), and TraceCPU().
execCompleteEvent
CountedExitEvent* TraceCPU::execCompleteEvent protected
A CountedExitEvent which when serviced decrements the counter.
A sim exit event is scheduled when the counter equals zero, that is all instances of Trace CPU have had their execCompleteEvent serviced.
Definition at line 1117 of file trace_cpu.hh.
Referenced by checkAndSchedExitEvent(), init(), and TraceCPU().
icacheGen
FixedRetryGen TraceCPU::icacheGen protected
Instance of FixedRetryGen to replay instruction read requests.
Definition at line 1064 of file trace_cpu.hh.
Referenced by init(), regStats(), and schedIcacheNext().
icacheNextEvent
EventFunctionWrapper TraceCPU::icacheNextEvent protected
Event for the control flow method schedIcacheNext()
Definition at line 1085 of file trace_cpu.hh.
Referenced by icacheRetryRecvd(), init(), and schedIcacheNext().
icachePort
IcachePort TraceCPU::icachePort protected
Port to connect to L1 instruction cache.
Definition at line 323 of file trace_cpu.hh.
Referenced by getInstPort().
instMasterID
const MasterID TraceCPU::instMasterID protected
Master id for instruction read requests.
Definition at line 329 of file trace_cpu.hh.
instTraceFile
std::string TraceCPU::instTraceFile protected
File names for input instruction and data traces.
Definition at line 335 of file trace_cpu.hh.
Referenced by init().
numOps
Stats::Scalar TraceCPU::numOps protected
Stat for number of simulated micro-ops.
Definition at line 1142 of file trace_cpu.hh.
Referenced by regStats(), totalOps(), and updateNumOps().
numSchedDcacheEvent
Stats::Scalar TraceCPU::numSchedDcacheEvent protected
Definition at line 1138 of file trace_cpu.hh.
Referenced by regStats(), and schedDcacheNextEvent().
numSchedIcacheEvent
Stats::Scalar TraceCPU::numSchedIcacheEvent protected
Definition at line 1139 of file trace_cpu.hh.
Referenced by regStats(), and schedIcacheNext().
numTraceCPUs
int TraceCPU::numTraceCPUs = 0 static protected
Number of Trace CPUs in the system used as a shared variable and passed to the CountedExitEvent event used for counting down exit events.
It is incremented in the constructor call so that the total is arrived at automatically.
Definition at line 1110 of file trace_cpu.hh.
Referenced by init(), and TraceCPU().
oneTraceComplete
bool TraceCPU::oneTraceComplete protected
Set to true when one of the generators finishes replaying its trace.
Definition at line 1094 of file trace_cpu.hh.
Referenced by checkAndSchedExitEvent(), and TraceCPU().
progressMsgInterval
const uint64_t TraceCPU::progressMsgInterval protected
Interval of committed instructions specified by the user at which a progress info message is printed.
Definition at line 1129 of file trace_cpu.hh.
Referenced by TraceCPU(), and updateNumOps().
progressMsgThreshold
uint64_t TraceCPU::progressMsgThreshold protected
Definition at line 1136 of file trace_cpu.hh.
Referenced by TraceCPU(), and updateNumOps().
traceOffset
Tick TraceCPU::traceOffset protected
This stores the time offset in the trace, which is taken away from the ready times of requests.
This is specially useful because the time offset can be very large if the traces are generated from the middle of a program.
Definition at line 1102 of file trace_cpu.hh.
Referenced by init(), and TraceCPU().
The documentation for this class was generated from the following files:
cpu/trace/trace_cpu.hh
cpu/trace/trace_cpu.cc