gem5: sc_dt::sc_uint_bitref Class Reference
sc_dt::sc_uint_bitref Class Reference
#include <sc_uint_base.hh>
Public Member Functions
sc_uint_bitref (const sc_uint_bitref &init)
sc_uint_bitref & operator= (const sc_uint_bitref_r &b)
sc_uint_bitref & operator= (const sc_uint_bitref &b)
sc_uint_bitref & operator= (bool b)
sc_uint_bitref & operator&= (bool b)
sc_uint_bitref & operator|= (bool b)
sc_uint_bitref & operator^= (bool b)
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_uint_bitref_r
sc_uint_bitref_r (const sc_uint_bitref_r &init)
virtual ~sc_uint_bitref_r ()
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
int length () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_uint_bitref ()
Protected Member Functions inherited from sc_dt::sc_uint_bitref_r
sc_uint_bitref_r ()
void initialize (const sc_uint_base *obj_p, int index_)
Static Protected Attributes
static sc_core::sc_vpool< sc_uint_bitref > m_pool
Friends
class sc_uint_base
class sc_core::sc_vpool< sc_uint_bitref >
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_uint_bitref_r
int m_index
sc_uint_base * m_obj_p
Detailed Description
Definition at line 231 of file sc_uint_base.hh.
Constructor & Destructor Documentation
sc_uint_bitref() [1/2]
sc_dt::sc_uint_bitref::sc_uint_bitref () inline protected
Definition at line 238 of file sc_uint_base.hh.
sc_uint_bitref() [2/2]
sc_dt::sc_uint_bitref::sc_uint_bitref (const sc_uint_bitref & init) inline
Definition at line 241 of file sc_uint_base.hh.
References ArmISA::b, MipsISA::is, sc_dt::operator&=(), sc_dt::operator^=(), and sc_dt::operator|=().
Member Function Documentation
concat_set() [1/4]
void sc_dt::sc_uint_bitref::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 112 of file sc_uint_base.cc.
References PowerISA::aa.
concat_set() [2/4]
void sc_dt::sc_uint_bitref::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 119 of file sc_uint_base.cc.
References PowerISA::aa, and sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_uint_bitref::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 129 of file sc_uint_base.cc.
References PowerISA::aa, and sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_uint_bitref::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 139 of file sc_uint_base.cc.
References PowerISA::aa.
operator&=()
sc_uint_bitref& sc_dt::sc_uint_bitref::operator &= (bool b)
Referenced by operator=().
operator=() [1/3]
sc_uint_bitref & sc_dt::sc_uint_bitref::operator= (const sc_uint_bitref_r & b) inline
Definition at line 911 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::to_bool().
operator=() [2/3]
sc_uint_bitref & sc_dt::sc_uint_bitref::operator= (const sc_uint_bitref & b) inline
Definition at line 918 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::to_bool().
operator=() [3/3]
sc_uint_bitref & sc_dt::sc_uint_bitref::operator= (bool b) inline
Definition at line 925 of file sc_uint_base.hh.
References ArmISA::b, and operator&=().
operator^=()
sc_uint_bitref & sc_dt::sc_uint_bitref::operator^= (bool b) inline
Definition at line 950 of file sc_uint_base.hh.
References sc_dt::UINT_ONE.
operator|=()
sc_uint_bitref & sc_dt::sc_uint_bitref::operator|= (bool b) inline
Definition at line 941 of file sc_uint_base.hh.
scan()
void sc_dt::sc_uint_bitref::scan (::std::istream & is = ::std::cin)
Definition at line 148 of file sc_uint_base.cc.
References ArmISA::b.
Referenced by sc_dt::operator>>().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_uint_bitref >
friend class sc_core::sc_vpool< sc_uint_bitref > friend
Definition at line 234 of file sc_uint_base.hh.
sc_uint_base
friend class sc_uint_base friend
Definition at line 233 of file sc_uint_base.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_uint_bitref > sc_dt::sc_uint_bitref::m_pool static protected
Definition at line 263 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_base::bit(), and sc_dt::sc_uint_base::operator[]().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_uint_base.hh
systemc/dt/int/sc_uint_base.cc