gem5: CacheBlk Class Reference
CacheBlk Class Reference
A Basic Cache block.
#include <cache_blk.hh>
Classes
class Lock
Represents that the indicated thread context has a "lock" on the block, in the LL/SC sense.
Public Types
typedef unsigned State
block state: OR of CacheBlkStatusBit
Public Member Functions
CacheBlk ()
CacheBlk (const CacheBlk &)=delete
CacheBlk & operator= (const CacheBlk &)=delete
virtual ~CacheBlk ()
bool isWritable () const
Checks the write permissions of this block.
bool isReadable () const
Checks the read permissions of this block.
bool isValid () const
Checks that a block is valid.
virtual void invalidate ()
Invalidate the block and clear all state.
bool isDirty () const
Check to see if a block has been written.
bool wasPrefetched () const
Check if this block was the result of a hardware prefetch, yet to be touched.
bool isSecure () const
Check if this block holds data from the secure memory space.
virtual void setValid ()
Set valid bit.
virtual void setSecure ()
Set secure bit.
Tick getWhenReady () const
Get tick at which block's data will be available for access.
void setWhenReady (const Tick tick)
Set tick at which block's data will be available for access.
virtual void insert (const Addr tag, const bool is_secure, const int src_master_ID, const uint32_t task_ID)
Set member variables when a block insertion occurs.
void trackLoadLocked (PacketPtr pkt)
Track the fact that a local locked was issued to the block.
void clearLoadLocks (const RequestPtr &req)
Clear the any load lock that intersect the request, and is from a different context.
virtual std::string print () const
Pretty-print tag, set and way, and interpret state bits to readable form including mapping to a MOESI state.
bool checkWrite (PacketPtr pkt)
Handle interaction of load-locked operations and stores.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
uint32_t task_id
Task Id associated with this block.
Addr tag
Data block tag value.
uint8_t * data
Contains a copy of the data in this block for easy access.
State status
The current status of this block.
Tick whenReady
Which curTick() will this block be accessible.
unsigned refCount
Number of references to this block since it was brought in.
int srcMasterId
holds the source requestor ID for this block.
Tick tickInserted
Tick on which the block was inserted in the cache.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Protected Attributes
std::list< Lock > lockList
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
A Basic Cache block.
Contains the tag, status, and a pointer to data.
Definition at line 87 of file cache_blk.hh.
Member Typedef Documentation
State
typedef unsigned CacheBlk::State
block state: OR of CacheBlkStatusBit
Definition at line 105 of file cache_blk.hh.
Constructor & Destructor Documentation
CacheBlk() [1/2]
CacheBlk::CacheBlk () inline
Definition at line 171 of file cache_blk.hh.
References invalidate(), and operator=().
CacheBlk() [2/2]
CacheBlk::CacheBlk (const CacheBlk &) delete
~CacheBlk()
virtual CacheBlk::~CacheBlk () inline virtual
Definition at line 178 of file cache_blk.hh.
Member Function Documentation
checkWrite()
bool CacheBlk::checkWrite (PacketPtr pkt) inline
Handle interaction of load-locked operations and stores.
Returns
True if write should proceed, false otherwise. Returns false only in the case of a failed store conditional.
Definition at line 395 of file cache_blk.hh.
References clearLoadLocks(), Packet::isLLSC(), Packet::isWrite(), MipsISA::l, and Packet::req.
Referenced by BaseCache::satisfyRequest().
clearLoadLocks()
void CacheBlk::clearLoadLocks (const RequestPtr & req) inline
Clear the any load lock that intersect the request, and is from a different context.
Definition at line 330 of file cache_blk.hh.
References MipsISA::l.
Referenced by checkWrite().
getWhenReady()
Tick CacheBlk::getWhenReady () const inline
Get tick at which block's data will be available for access.
Returns
Data ready tick.
Definition at line 275 of file cache_blk.hh.
References MaxTick, and whenReady.
Referenced by BaseCache::calculateAccessLatency().
insert()
void CacheBlk::insert (const Addr tag, const bool is_secure, const int src_master_ID, const uint32_t task_ID) virtual
Set member variables when a block insertion occurs.
Resets reference count to 1 (the insertion counts as a reference), and touch block if it hadn't been touched previously. Sets the insertion tick to the current tick. Marks the block valid.
Parameters
tag Block address tag.
is_secure Whether the block is in secure space or not.
src_master_ID The source requestor ID.
task_ID The new task ID.
Reimplemented in TempCacheBlk, and SectorSubBlk.
Definition at line 46 of file cache_blk.cc.
References curTick(), refCount, setSecure(), setValid(), srcMasterId, status, tag, task_id, and tickInserted.
Referenced by SectorSubBlk::insert(), BaseTags::insertBlock(), and setWhenReady().
invalidate()
virtual void CacheBlk::invalidate () inline virtual
Invalidate the block and clear all state.
Reimplemented in TempCacheBlk, and SectorSubBlk.
Definition at line 214 of file cache_blk.hh.
References Request::invldMasterId, MaxAddr, MaxTick, and ContextSwitchTaskId::Unknown.
Referenced by CacheBlk(), SectorSubBlk::invalidate(), BaseTags::invalidate(), and TempCacheBlk::invalidate().
isDirty()
bool CacheBlk::isDirty () const inline
Check to see if a block has been written.
Returns
True if the block is dirty.
Definition at line 229 of file cache_blk.hh.
References BlkDirty.
Referenced by Cache::cleanEvictBlk(), NoncoherentCache::evictBlock(), Cache::evictBlock(), BaseCache::functionalAccess(), Cache::handleSnoop(), BaseCache::invalidateVisitor(), BaseCache::isDirty(), BaseCache::maintainClusivity(), print(), BaseCache::recvAtomic(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), BaseCache::sendMSHRQueuePacket(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), and BaseCache::writecleanBlk().
isReadable()
bool CacheBlk::isReadable () const inline
Checks the read permissions of this block.
Note that a block can be valid but not readable if there is an outstanding write upgrade miss.
Returns
True if the block is readable.
Definition at line 196 of file cache_blk.hh.
References BlkReadable, and BlkValid.
Referenced by BaseCache::access(), and print().
isSecure()
bool CacheBlk::isSecure () const inline
Check if this block holds data from the secure memory space.
Returns
True if the block holds data from the secure memory space.
Definition at line 248 of file cache_blk.hh.
References BlkSecure.
Referenced by Cache::cleanEvictBlk(), BaseTags::findBlock(), FALRU::findBlock(), BaseCache::handleFill(), FALRU::insertBlock(), FALRU::invalidate(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), BaseCache::writecleanBlk(), and SectorBlk::~SectorBlk().
isValid()
bool CacheBlk::isValid () const inline
Checks that a block is valid.
Returns
True if the block is valid.
Definition at line 206 of file cache_blk.hh.
References BlkValid.
Referenced by NoncoherentCache::access(), FALRU::accessBlock(), Cache::cleanEvictBlk(), BaseTags::cleanupRefsVisitor(), BaseTags::computeStatsVisitor(), NoncoherentCache::createMissPacket(), Cache::createMissPacket(), BaseTags::findBlock(), FALRU::findBlock(), CompressedTags::findVictim(), SectorTags::findVictim(), BaseCache::functionalAccess(), Cache::handleAtomicReqMiss(), BaseCache::handleFill(), Cache::handleSnoop(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), BaseTags::insertBlock(), BaseTags::invalidate(), BaseCache::invalidateVisitor(), BaseCache::maintainClusivity(), print(), FALRU::CacheTracking::recordAccess(), BaseCache::recvAtomic(), BaseCache::recvTimingResp(), BaseCache::satisfyRequest(), Cache::serviceMSHRTargets(), setValid(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), and SectorBlk::~SectorBlk().
isWritable()
bool CacheBlk::isWritable () const inline
Checks the write permissions of this block.
Returns
True if the block is writable.
Definition at line 184 of file cache_blk.hh.
References BlkValid, and BlkWritable.
Referenced by BaseCache::access(), Cache::createMissPacket(), Cache::handleSnoop(), BaseCache::handleTimingReqMiss(), print(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), Cache::serviceMSHRTargets(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
operator=()
CacheBlk& CacheBlk::operator= (const CacheBlk &) delete
Referenced by CacheBlk(), and TempCacheBlk::TempCacheBlk().
print()
virtual std::string CacheBlk::print () const inline virtual
Pretty-print tag, set and way, and interpret state bits to readable form including mapping to a MOESI state.
Returns
string with basic state information
state M O E S I writable 1 0 1 0 0 dirty 1 1 0 0 0 valid 1 1 1 1 0
state writable dirty valid M 1 1 1 O 0 1 1 E 1 0 1 S 0 0 1 I 0 0 0
Note that only one cache ever has a block in Modified or Owned state, i.e., only one cache owns the block, or equivalently has the BlkDirty bit set. However, multiple caches on the same path to memory can have a block in the Exclusive state (despite the name). Exclusive means this cache has the only copy at this level of the hierarchy, i.e., there may be copies in caches above this cache (in various states), but there are no peers that have copies on this branch of the hierarchy, and no caches at or above this level on any other branch have copies either.
Reimplemented in SectorSubBlk, CompressionBlk, and FALRUBlk.
Definition at line 348 of file cache_blk.hh.
References csprintf(), ReplaceableEntry::getSet(), ReplaceableEntry::getWay(), isDirty(), isReadable(), isValid(), isWritable(), and ArmISA::s.
Referenced by BaseCache::access(), BaseCache::allocateBlock(), BaseCache::handleFill(), Cache::handleSnoop(), FALRUBlk::print(), SectorSubBlk::print(), BaseCache::recvAtomic(), BaseCache::sendMSHRQueuePacket(), BaseCache::updateCompressionData(), and CacheBlkPrintWrapper::~CacheBlkPrintWrapper().
setSecure()
virtual void CacheBlk::setSecure () inline virtual
Set secure bit.
Reimplemented in SectorSubBlk.
Definition at line 265 of file cache_blk.hh.
References BlkSecure.
Referenced by insert(), TempCacheBlk::insert(), and SectorSubBlk::setSecure().
setValid()
virtual void CacheBlk::setValid () inline virtual
Set valid bit.
Reimplemented in SectorSubBlk.
Definition at line 256 of file cache_blk.hh.
References BlkValid, and isValid().
Referenced by insert(), TempCacheBlk::insert(), and SectorSubBlk::setValid().
setWhenReady()
void CacheBlk::setWhenReady (const Tick tick) inline
Set tick at which block's data will be available for access.
The new tick must be chronologically sequential with respect to previous accesses.
Parameters
tick New data ready tick.
Definition at line 288 of file cache_blk.hh.
References insert().
Referenced by BaseCache::access(), and BaseCache::handleFill().
trackLoadLocked()
void CacheBlk::trackLoadLocked (PacketPtr pkt) inline
Track the fact that a local locked was issued to the block.
Invalidate any previous LL to the same address.
Definition at line 312 of file cache_blk.hh.
References Packet::isLLSC(), MipsISA::l, and Packet::req.
Referenced by BaseCache::satisfyRequest().
wasPrefetched()
bool CacheBlk::wasPrefetched () const inline
Check if this block was the result of a hardware prefetch, yet to be touched.
Returns
True if the block was a hardware prefetch, unaccesed.
Definition at line 239 of file cache_blk.hh.
References BlkHWPrefetched.
Referenced by BaseCache::hasBeenPrefetched(), and BaseCache::recvTimingReq().
Member Data Documentation
data
uint8_t* CacheBlk::data
Contains a copy of the data in this block for easy access.
This is used for efficient execution when the data could be actually stored in another format (COW, compressed, sub-blocked, etc). In all cases the data stored here should be kept consistant with the actual data referenced by this block.
Definition at line 102 of file cache_blk.hh.
Referenced by BaseCache::access(), BaseCache::cmpAndSwap(), BaseCache::functionalAccess(), BaseCache::handleFill(), Cache::handleSnoop(), BaseCache::satisfyRequest(), CompressedTags::tagsInit(), BaseSetAssoc::tagsInit(), SectorTags::tagsInit(), FALRU::tagsInit(), TempCacheBlk::TempCacheBlk(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), BaseCache::writecleanBlk(), and TempCacheBlk::~TempCacheBlk().
lockList
std::list<Lock> CacheBlk::lockList protected
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Definition at line 168 of file cache_blk.hh.
refCount
unsigned CacheBlk::refCount
Number of references to this block since it was brought in.
Definition at line 117 of file cache_blk.hh.
Referenced by BaseSetAssoc::accessBlock(), SectorTags::accessBlock(), BaseTags::cleanupRefsVisitor(), insert(), and BaseTags::invalidate().
srcMasterId
int CacheBlk::srcMasterId
holds the source requestor ID for this block.
Definition at line 120 of file cache_blk.hh.
Referenced by insert(), and BaseTags::invalidate().
status
State CacheBlk::status
The current status of this block.
See also
CacheBlockStatusBits
Definition at line 108 of file cache_blk.hh.
Referenced by NoncoherentCache::access(), BaseCache::access(), BaseCache::cmpAndSwap(), Cache::handleAtomicReqMiss(), BaseCache::handleFill(), Cache::handleSnoop(), BaseCache::handleTimingReqMiss(), insert(), TempCacheBlk::insert(), CompressionBlk::isCompressed(), BaseCache::recvTimingReq(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), CompressionBlk::setCompressed(), CompressionBlk::setUncompressed(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), and BaseCache::writecleanBlk().
tag
Addr CacheBlk::tag
Data block tag value.
Definition at line 94 of file cache_blk.hh.
Referenced by BaseTags::findBlock(), FALRU::findBlock(), SectorSubBlk::insert(), insert(), FALRU::insertBlock(), FALRU::invalidate(), SectorTags::regenerateBlkAddr(), BaseSetAssoc::regenerateBlkAddr(), FALRU::regenerateBlkAddr(), SectorBlk::~SectorBlk(), and SectorSubBlk::~SectorSubBlk().
task_id
uint32_t CacheBlk::task_id
Task Id associated with this block.
Definition at line 91 of file cache_blk.hh.
Referenced by Cache::cleanEvictBlk(), BaseTags::computeStatsVisitor(), insert(), BaseCache::writebackBlk(), BaseCache::writebackVisitor(), and BaseCache::writecleanBlk().
tickInserted
Tick CacheBlk::tickInserted
Tick on which the block was inserted in the cache.
Its value is only meaningful if the block is valid.
Definition at line 126 of file cache_blk.hh.
Referenced by BaseTags::computeStatsVisitor(), and insert().
whenReady
Tick CacheBlk::whenReady
Which curTick() will this block be accessible.
Its value is only meaningful if the block is valid.
Definition at line 114 of file cache_blk.hh.
Referenced by getWhenReady().
The documentation for this class was generated from the following files:
mem/cache/cache_blk.hh
mem/cache/cache_blk.cc