gem5: InputUnit Class Reference
InputUnit Class Reference
#include <InputUnit.hh>
Public Member Functions
InputUnit (int id, PortDirection direction, Router *router)
~InputUnit ()
void wakeup ()
void print (std::ostream &out) const
PortDirection get_direction ()
void set_vc_idle (int vc, Cycles curTime)
void set_vc_active (int vc, Cycles curTime)
void grant_outport (int vc, int outport)
void grant_outvc (int vc, int outvc)
int get_outport (int invc)
int get_outvc (int invc)
Cycles get_enqueue_time (int invc)
void increment_credit (int in_vc, bool free_signal, Cycles curTime)
flit * peekTopFlit (int vc)
flit * getTopFlit (int vc)
bool need_stage (int vc, flit_stage stage, Cycles time)
bool isReady (int invc, Cycles curTime)
flitBuffer * getCreditQueue ()
void set_in_link (NetworkLink *link)
int get_inlink_id ()
void set_credit_link (CreditLink *credit_link)
double get_buf_read_activity (unsigned int vnet) const
double get_buf_write_activity (unsigned int vnet) const
uint32_t functionalWrite (Packet *pkt)
void resetStats ()
Public Member Functions inherited from Consumer
Consumer (ClockedObject *_em)
virtual ~Consumer ()
virtual void storeEventInfo (int info)
bool alreadyScheduled (Tick time)
void insertScheduledWakeupTime (Tick time)
void scheduleEventAbsolute (Tick timeAbs)
Private Attributes
int m_id
PortDirection m_direction
int m_num_vcs
int m_vc_per_vnet
Router * m_router
NetworkLink * m_in_link
CreditLink * m_credit_link
flitBuffer * creditQueue
std::vector< VirtualChannel * > m_vcs
std::vector< double > m_num_buffer_writes
std::vector< double > m_num_buffer_reads
Additional Inherited Members
Protected Member Functions inherited from Consumer
void scheduleEvent (Cycles timeDelta)
Detailed Description
Definition at line 48 of file InputUnit.hh.
Constructor & Destructor Documentation
InputUnit()
InputUnit::InputUnit (int id, PortDirection direction, Router * router)
Definition at line 44 of file InputUnit.cc.
References creditQueue, Router::get_num_vcs(), Router::get_vc_per_vnet(), ArmISA::i, ArmISA::id, m_direction, m_id, m_num_buffer_reads, m_num_buffer_writes, m_num_vcs, m_router, m_vc_per_vnet, and m_vcs.
~InputUnit()
InputUnit::~InputUnit ()
Definition at line 68 of file InputUnit.cc.
References creditQueue, m5::stl_helpers::deletePointers(), and m_vcs.
Member Function Documentation
functionalWrite()
uint32_t InputUnit::functionalWrite (Packet * pkt)
Definition at line 154 of file InputUnit.cc.
References ArmISA::i, m_num_vcs, and m_vcs.
Referenced by get_buf_write_activity().
get_buf_read_activity()
double InputUnit::get_buf_read_activity (unsigned int vnet) const inline
Definition at line 143 of file InputUnit.hh.
References m_num_buffer_reads.
get_buf_write_activity()
double InputUnit::get_buf_write_activity (unsigned int vnet) const inline
Definition at line 145 of file InputUnit.hh.
References functionalWrite(), m_num_buffer_writes, and resetStats().
get_direction()
PortDirection InputUnit::get_direction () inline
Definition at line 57 of file InputUnit.hh.
References m_direction.
get_enqueue_time()
Cycles InputUnit::get_enqueue_time (int invc) inline
Definition at line 96 of file InputUnit.hh.
References increment_credit(), and m_vcs.
get_inlink_id()
int InputUnit::get_inlink_id () inline
Definition at line 135 of file InputUnit.hh.
References NetworkLink::get_id(), and m_in_link.
get_outport()
int InputUnit::get_outport (int invc) inline
Definition at line 84 of file InputUnit.hh.
References m_vcs.
get_outvc()
int InputUnit::get_outvc (int invc) inline
Definition at line 90 of file InputUnit.hh.
References m_vcs.
getCreditQueue()
flitBuffer* InputUnit::getCreditQueue () inline
Definition at line 127 of file InputUnit.hh.
References creditQueue.
Referenced by Router::addInPort().
getTopFlit()
flit* InputUnit::getTopFlit (int vc) inline
Definition at line 110 of file InputUnit.hh.
References m_vcs.
grant_outport()
void InputUnit::grant_outport (int vc, int outport) inline
Definition at line 72 of file InputUnit.hh.
References m_vcs.
Referenced by wakeup().
grant_outvc()
void InputUnit::grant_outvc (int vc, int outvc) inline
Definition at line 78 of file InputUnit.hh.
References m_vcs.
increment_credit()
void InputUnit::increment_credit (int in_vc, bool free_signal, Cycles curTime)
Definition at line 145 of file InputUnit.cc.
References Clocked::clockEdge(), creditQueue, flitBuffer::insert(), m_credit_link, m_router, and Consumer::scheduleEventAbsolute().
Referenced by get_enqueue_time().
isReady()
bool InputUnit::isReady (int invc, Cycles curTime) inline
Definition at line 122 of file InputUnit.hh.
References m_vcs.
need_stage()
bool InputUnit::need_stage (int vc, flit_stage stage, Cycles time) inline
Definition at line 116 of file InputUnit.hh.
References m_vcs.
peekTopFlit()
flit* InputUnit::peekTopFlit (int vc) inline
Definition at line 104 of file InputUnit.hh.
References m_vcs.
print()
void InputUnit::print (std::ostream & out) const inline virtual
Implements Consumer.
Definition at line 55 of file InputUnit.hh.
resetStats()
void InputUnit::resetStats ()
Definition at line 165 of file InputUnit.cc.
References ArmISA::j, m_num_buffer_reads, and m_num_buffer_writes.
Referenced by get_buf_write_activity().
set_credit_link()
void InputUnit::set_credit_link (CreditLink * credit_link) inline
Definition at line 138 of file InputUnit.hh.
References m_credit_link.
Referenced by Router::addInPort().
set_in_link()
void InputUnit::set_in_link (NetworkLink * link) inline
Definition at line 130 of file InputUnit.hh.
References m_in_link.
Referenced by Router::addInPort().
set_vc_active()
void InputUnit::set_vc_active (int vc, Cycles curTime) inline
Definition at line 66 of file InputUnit.hh.
References m_vcs.
Referenced by wakeup().
set_vc_idle()
void InputUnit::set_vc_idle (int vc, Cycles curTime) inline
Definition at line 60 of file InputUnit.hh.
References m_vcs.
wakeup()
void InputUnit::wakeup () virtual
Implements Consumer.
Definition at line 85 of file InputUnit.cc.
References ACTIVE_, flit::advance_stage(), NetworkLink::consumeLink(), Clocked::curCycle(), Router::get_pipe_stages(), flit::get_route(), flit::get_type(), flit::get_vc(), grant_outport(), HEAD_, HEAD_TAIL_, IDLE_, flit::increment_hops(), NetworkLink::isReady(), m_direction, m_id, m_in_link, m_num_buffer_reads, m_num_buffer_writes, m_router, m_vc_per_vnet, m_vcs, Router::route_compute(), SA_, Router::schedule_wakeup(), and set_vc_active().
Member Data Documentation
creditQueue
flitBuffer* InputUnit::creditQueue private
Definition at line 160 of file InputUnit.hh.
Referenced by getCreditQueue(), increment_credit(), InputUnit(), and ~InputUnit().
m_credit_link
CreditLink* InputUnit::m_credit_link private
Definition at line 159 of file InputUnit.hh.
Referenced by increment_credit(), and set_credit_link().
m_direction
PortDirection InputUnit::m_direction private
Definition at line 153 of file InputUnit.hh.
Referenced by get_direction(), InputUnit(), and wakeup().
m_id
int InputUnit::m_id private
Definition at line 152 of file InputUnit.hh.
Referenced by InputUnit(), and wakeup().
m_in_link
NetworkLink* InputUnit::m_in_link private
Definition at line 158 of file InputUnit.hh.
Referenced by get_inlink_id(), set_in_link(), and wakeup().
m_num_buffer_reads
std::vector<double> InputUnit::m_num_buffer_reads private
Definition at line 167 of file InputUnit.hh.
Referenced by get_buf_read_activity(), InputUnit(), resetStats(), and wakeup().
m_num_buffer_writes
std::vector<double> InputUnit::m_num_buffer_writes private
Definition at line 166 of file InputUnit.hh.
Referenced by get_buf_write_activity(), InputUnit(), resetStats(), and wakeup().
m_num_vcs
int InputUnit::m_num_vcs private
Definition at line 154 of file InputUnit.hh.
Referenced by functionalWrite(), and InputUnit().
m_router
Router* InputUnit::m_router private
Definition at line 157 of file InputUnit.hh.
Referenced by increment_credit(), InputUnit(), and wakeup().
m_vc_per_vnet
int InputUnit::m_vc_per_vnet private
Definition at line 155 of file InputUnit.hh.
Referenced by InputUnit(), and wakeup().
m_vcs
std::vector<VirtualChannel *> InputUnit::m_vcs private
Definition at line 163 of file InputUnit.hh.
Referenced by functionalWrite(), get_enqueue_time(), get_outport(), get_outvc(), getTopFlit(), grant_outport(), grant_outvc(), InputUnit(), isReady(), need_stage(), peekTopFlit(), set_vc_active(), set_vc_idle(), wakeup(), and ~InputUnit().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/InputUnit.hh
mem/ruby/network/garnet2.0/InputUnit.cc