gem5: sc_gem5::Thread::Context Class Reference
sc_gem5::Thread::Context Class Reference
Public Member Functions
Context (Thread *thread, size_t size)
Public Member Functions inherited from Fiber
Fiber (size_t stack_size=DefaultStackSize)
stack_size is the size of the stack available to this fiber.
Fiber (Fiber *link, size_t stack_size=DefaultStackSize)
virtual ~Fiber ()
void run ()
Start executing the fiber represented by this object.
bool finished () const
Returns whether the "main" function of this fiber has finished.
bool started () const
Returns whether the "main" function of this fiber has started.
Private Member Functions
void main () override
This method is called when this fiber is first run.
Private Attributes
Thread * thread
Additional Inherited Members
Static Public Member Functions inherited from Fiber
static Fiber * currentFiber ()
Get a pointer to the current running Fiber.
static Fiber * primaryFiber ()
Get a pointer to the primary Fiber.
Static Public Attributes inherited from Fiber
static const size_t DefaultStackSize = 0x50000
Protected Member Functions inherited from Fiber
void setStarted ()
Detailed Description
Definition at line 81 of file process_types.hh.
Constructor & Destructor Documentation
Context()
sc_gem5::Thread::Context::Context (Thread * thread, size_t size) inline
Definition at line 84 of file process_types.hh.
Member Function Documentation
main()
void sc_gem5::Thread::Context::main () inline override private virtual
This method is called when this fiber is first run.
Override it to give your fiber something to do. When main returns, the fiber will mark itself as finished and switch to its link fiber.
Implements Fiber.
Definition at line 90 of file process_types.hh.
References sc_gem5::Process::_needsStart, sc_gem5::Process::run(), sc_gem5::scheduler, sc_gem5::Process::terminate(), sc_gem5::Scheduler::throwUp(), and sc_gem5::Scheduler::yield().
Member Data Documentation
thread
Thread* sc_gem5::Thread::Context::thread private
Definition at line 87 of file process_types.hh.
The documentation for this class was generated from the following file:
systemc/core/process_types.hh