gem5: SrcClockDomain Class Reference
SrcClockDomain Class Reference
The source clock domains provides the notion of a clock domain that is connected to a tunable clock source.
#include <clock_domain.hh>
Public Types
typedef SrcClockDomainParams Params
typedef int32_t DomainID
typedef uint32_t PerfLevel
Public Types inherited from ClockDomain
typedef ClockDomainParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
SrcClockDomain (const Params *p)
void clockPeriod (Tick clock_period)
Set new clock value.
uint32_t domainID () const
bool validPerfLevel (PerfLevel perf_level) const
Checks whether the performance level requested exists in the current domain configuration.
void perfLevel (PerfLevel perf_level)
Sets the current performance level of the domain.
PerfLevel perfLevel () const
PerfLevel numPerfLevels () const
Get the number of available performance levels for this clock domain.
Tick clkPeriodAtPerfLevel () const
Tick clkPeriodAtPerfLevel (PerfLevel perf_level) const
void startup () override
startup() is the final initialization call before simulation.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from ClockDomain
ClockDomain (const Params *p, VoltageDomain *voltage_domain)
Tick clockPeriod () const
Get the clock period.
void registerWithClockDomain (Clocked *c)
Register a Clocked object with this ClockDomain.
VoltageDomain * voltageDomain () const
Get the voltage domain.
double voltage () const
Get the current voltage this clock domain operates at.
void addDerivedDomain (DerivedClockDomain *clock_domain)
Add a derived domain.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Attributes
static const DomainID emptyDomainID = -1
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Private Member Functions
void signalPerfLevelUpdate ()
Inform other components about the changed performance level.
Private Attributes
const std::vector< Tick > freqOpPoints
List of possible frequency operational points, should be in descending order An empty list corresponds to default frequency specified for its clock domain, overall implying NO DVFS.
const uint32_t _domainID
Software recognizable id number for the domain, should be unique for each domain.
PerfLevel _perfLevel
Current performance level the domain is set to.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from ClockDomain
Tick _clockPeriod
Pre-computed clock period in ticks.
VoltageDomain * _voltageDomain
Voltage domain this clock domain belongs to.
std::vector< DerivedClockDomain * > children
Pointers to potential derived clock domains so we can propagate changes.
std::vector< Clocked * > members
Pointers to members of this clock domain, so that when the clock period changes, we can update each member's tick.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
The source clock domains provides the notion of a clock domain that is connected to a tunable clock source.
It maintains the clock period and provides methods for setting/getting the clock and configuration parameters for clock domain that handler is going to manage. This includes frequency values at various performance levels, domain id, and current performance level. Note that a performance level as requested by the software corresponds to one of the frequency operational points the domain can operate at.
Definition at line 168 of file clock_domain.hh.
Member Typedef Documentation
DomainID
typedef int32_t SrcClockDomain::DomainID
Definition at line 185 of file clock_domain.hh.
Params
typedef SrcClockDomainParams SrcClockDomain::Params
Definition at line 173 of file clock_domain.hh.
PerfLevel
typedef uint32_t SrcClockDomain::PerfLevel
Definition at line 193 of file clock_domain.hh.
Constructor & Destructor Documentation
SrcClockDomain()
SrcClockDomain::SrcClockDomain (const Params * p)
Definition at line 81 of file clock_domain.cc.
References _domainID, _perfLevel, ClockDomain::clockPeriod(), fatal_if, freqOpPoints, SimObject::name(), VoltageDomain::numVoltages(), and VoltageDomain::registerSrcClockDom().
Referenced by startup().
Member Function Documentation
clkPeriodAtPerfLevel() [1/2]
Tick SrcClockDomain::clkPeriodAtPerfLevel () const inline
Returns
the clock period (expressed in ticks) for the current performance level
Definition at line 229 of file clock_domain.hh.
Referenced by DVFSHandler::clkPeriodAtPerfLevel(), and signalPerfLevelUpdate().
clkPeriodAtPerfLevel() [2/2]
Tick SrcClockDomain::clkPeriodAtPerfLevel (PerfLevel perf_level) const inline
Definition at line 231 of file clock_domain.hh.
References SimObject::serialize(), SimObject::startup(), and SimObject::unserialize().
clockPeriod()
void SrcClockDomain::clockPeriod (Tick clock_period)
Set new clock value.
Parameters
clock The new clock period in ticks
Definition at line 116 of file clock_domain.cc.
References ClockDomain::_clockPeriod, ArmISA::c, ClockDomain::children, DPRINTF, fatal, ArmISA::m, ClockDomain::members, and SimObject::name().
domainID()
uint32_t SrcClockDomain::domainID () const inline
Returns
the domainID of the domain
Definition at line 191 of file clock_domain.hh.
Referenced by DVFSHandler::DVFSHandler(), perfLevel(), and VoltageDomain::sanitiseVoltages().
numPerfLevels()
PerfLevel SrcClockDomain::numPerfLevels () const inline
Get the number of available performance levels for this clock domain.
Returns
Number of perf levels configured for this domain.
Definition at line 223 of file clock_domain.hh.
Referenced by DVFSHandler::clkPeriodAtPerfLevel(), and DVFSHandler::numPerfLevels().
perfLevel() [1/2]
void SrcClockDomain::perfLevel (PerfLevel perf_level)
Sets the current performance level of the domain.
Parameters
perf_level the target performance level
Definition at line 140 of file clock_domain.cc.
References _perfLevel, domainID(), DPRINTF, SimObject::name(), signalPerfLevelUpdate(), and validPerfLevel().
Referenced by DVFSHandler::perfLevel(), and VoltageDomain::sanitiseVoltages().
perfLevel() [2/2]
PerfLevel SrcClockDomain::perfLevel () const inline
Returns
the current performance level of the domain
Definition at line 216 of file clock_domain.hh.
serialize()
void SrcClockDomain::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 169 of file clock_domain.cc.
References _perfLevel, SimObject::serialize(), and SERIALIZE_SCALAR.
signalPerfLevelUpdate()
void SrcClockDomain::signalPerfLevelUpdate () private
Inform other components about the changed performance level.
Definition at line 158 of file clock_domain.cc.
References clkPeriodAtPerfLevel(), ClockDomain::clockPeriod(), VoltageDomain::sanitiseVoltages(), and ClockDomain::voltageDomain().
Referenced by perfLevel(), and startup().
startup()
void SrcClockDomain::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 183 of file clock_domain.cc.
References signalPerfLevelUpdate(), and SrcClockDomain().
unserialize()
void SrcClockDomain::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 176 of file clock_domain.cc.
References _perfLevel, SimObject::unserialize(), and UNSERIALIZE_SCALAR.
validPerfLevel()
bool SrcClockDomain::validPerfLevel (PerfLevel perf_level) const inline
Checks whether the performance level requested exists in the current domain configuration.
Parameters
the target performance level of the domain
Returns
validity status of the given performance level
Definition at line 202 of file clock_domain.hh.
Referenced by perfLevel().
Member Data Documentation
_domainID
const uint32_t SrcClockDomain::_domainID private
Software recognizable id number for the domain, should be unique for each domain.
Definition at line 260 of file clock_domain.hh.
Referenced by SrcClockDomain().
_perfLevel
PerfLevel SrcClockDomain::_perfLevel private
Current performance level the domain is set to.
The performance level corresponds to one selected frequency (and related voltage) from the supplied list of frequencies, with perfLevel = 0 being the fastest performance state.
Definition at line 268 of file clock_domain.hh.
Referenced by perfLevel(), serialize(), SrcClockDomain(), and unserialize().
emptyDomainID
const DomainID SrcClockDomain::emptyDomainID = -1 static
Definition at line 186 of file clock_domain.hh.
Referenced by DVFSHandler::DVFSHandler().
freqOpPoints
const std::vector<Tick> SrcClockDomain::freqOpPoints private
List of possible frequency operational points, should be in descending order An empty list corresponds to default frequency specified for its clock domain, overall implying NO DVFS.
Definition at line 254 of file clock_domain.hh.
Referenced by SrcClockDomain().
The documentation for this class was generated from the following files:
sim/clock_domain.hh
sim/clock_domain.cc