gem5: base/condcodes.test.cc File Reference
condcodes.test.cc File Reference
#include <gtest/gtest.h>
#include "base/condcodes.hh"
Functions
TEST (CondCodes, FindCarryWithNoCarryIn8Bit)
TEST (CondCodes, FindNoCarryWithNoCarryIn8Bit)
TEST (CondCodes, FindCarryWithCarryIn8Bit)
TEST (CondCodes, FindNoCarryWithCarryIn8Bit)
TEST (CondCodes, FindCarryWithNoCarryIn32Bit)
TEST (CondCodes, FindNoCarryWithNoCarryIn32Bit)
TEST (CondCodes, FindCarryWithCarryIn32Bit)
TEST (CondCodes, FindCarryWithNoCarryIn64Bit)
TEST (CondCodes, FindCarryWithCarryIn64Bit)
TEST (CondCodes, FindOverflow8Bit)
TEST (CondCodes, FindOverflow32Bit)
TEST (CondCodes, FindOverflow64Bit)
TEST (CondCodes, OddParity)
TEST (CondCodes, EvenParity)
TEST (CondCodes, OddParityOverflow)
TEST (CondCodes, EvenParityOverflow)
TEST (CondCodes, IsNegative)
TEST (CondCodes, IsNotNegative)
TEST (CondCodes, IsZero)
TEST (CondCodes, IsNotZero)
TEST (CondCodes, IsZeroOverflow)
Function Documentation
TEST() [1/21]
TEST (CondCodes , FindCarryWithNoCarryIn8Bit)
Definition at line 40 of file condcodes.test.cc.
References EXPECT_TRUE, and findCarry().
TEST() [2/21]
TEST (CondCodes , FindNoCarryWithNoCarryIn8Bit)
Definition at line 49 of file condcodes.test.cc.
References EXPECT_FALSE, and findCarry().
TEST() [3/21]
TEST (CondCodes , FindCarryWithCarryIn8Bit)
Definition at line 58 of file condcodes.test.cc.
References EXPECT_TRUE, and findCarry().
TEST() [4/21]
TEST (CondCodes , FindNoCarryWithCarryIn8Bit)
Definition at line 67 of file condcodes.test.cc.
References EXPECT_FALSE, and findCarry().
TEST() [5/21]
TEST (CondCodes , FindCarryWithNoCarryIn32Bit)
Definition at line 76 of file condcodes.test.cc.
References EXPECT_TRUE, and findCarry().
TEST() [6/21]
TEST (CondCodes , FindNoCarryWithNoCarryIn32Bit)
Definition at line 85 of file condcodes.test.cc.
References EXPECT_FALSE, and findCarry().
TEST() [7/21]
TEST (CondCodes , FindCarryWithCarryIn32Bit)
Definition at line 90 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findCarry().
TEST() [8/21]
TEST (CondCodes , FindCarryWithNoCarryIn64Bit)
Definition at line 105 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findCarry().
TEST() [9/21]
TEST (CondCodes , FindCarryWithCarryIn64Bit)
Definition at line 137 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findCarry().
TEST() [10/21]
TEST (CondCodes , FindOverflow8Bit)
Definition at line 173 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findOverflow().
TEST() [11/21]
TEST (CondCodes , FindOverflow32Bit)
Definition at line 187 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findOverflow().
TEST() [12/21]
TEST (CondCodes , FindOverflow64Bit)
Definition at line 201 of file condcodes.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and findOverflow().
TEST() [13/21]
TEST (CondCodes , OddParity)
Definition at line 220 of file condcodes.test.cc.
References EXPECT_EQ, and findParity().
TEST() [14/21]
TEST (CondCodes , EvenParity)
Definition at line 225 of file condcodes.test.cc.
References EXPECT_EQ, and findParity().
TEST() [15/21]
TEST (CondCodes , OddParityOverflow)
Definition at line 230 of file condcodes.test.cc.
References EXPECT_EQ, and findParity().
TEST() [16/21]
TEST (CondCodes , EvenParityOverflow)
Definition at line 235 of file condcodes.test.cc.
References EXPECT_EQ, and findParity().
TEST() [17/21]
TEST (CondCodes , IsNegative)
Definition at line 240 of file condcodes.test.cc.
References EXPECT_EQ, and findNegative().
TEST() [18/21]
TEST (CondCodes , IsNotNegative)
Definition at line 245 of file condcodes.test.cc.
References EXPECT_EQ, and findNegative().
TEST() [19/21]
TEST (CondCodes , IsZero)
Definition at line 250 of file condcodes.test.cc.
References EXPECT_EQ, and findZero().
TEST() [20/21]
TEST (CondCodes , IsNotZero)
Definition at line 255 of file condcodes.test.cc.
References EXPECT_EQ, and findZero().
TEST() [21/21]
TEST (CondCodes , IsZeroOverflow)
Definition at line 260 of file condcodes.test.cc.
References EXPECT_EQ, and findZero().