gem5: unittest/cprintftime.cc File Reference
cprintftime.cc File Reference
#include <iostream>
#include <list>
#include <sstream>
#include <string>
#include "base/cprintf.hh"
Functions
void handle_alarm (int signal)
void do_test (int seconds)
int main ()
Variables
volatile int stop = false
Function Documentation
do_test()
void do_test (int seconds)
Definition at line 49 of file cprintftime.cc.
References stop.
Referenced by main().
handle_alarm()
void handle_alarm (int signal)
Definition at line 43 of file cprintftime.cc.
References stop.
Referenced by main().
main()
int main ()
Definition at line 56 of file cprintftime.cc.
References ccprintf(), cprintf(), do_test(), handle_alarm(), and stop.
Variable Documentation
stop
volatile int stop = false
Definition at line 40 of file cprintftime.cc.
Referenced by PerfKvmCounter::attached(), do_test(), handle_alarm(), and main().