gem5: base/cprintf.hh File Reference
cprintf.hh File Reference
#include <ios>
#include <iostream>
#include <list>
#include <string>
#include "base/cprintf_formats.hh"
Classes
struct cp::Print
Namespaces
cp
Functions
void ccprintf (cp::Print &print)
template<typename T , typename ... Args>
void ccprintf (cp::Print &print, const T &value, const Args &...args)
template<typename ... Args>
void ccprintf (std::ostream &stream, const char *format, const Args &...args)
template<typename ... Args>
void cprintf (const char *format, const Args &...args)
template<typename ... Args>
std::string csprintf (const char *format, const Args &...args)
template<typename ... Args>
void ccprintf (std::ostream &stream, const std::string &format, const Args &...args)
template<typename ... Args>
void cprintf (const std::string &format, const Args &...args)
template<typename ... Args>
std::string csprintf (const std::string &format, const Args &...args)
Function Documentation
ccprintf() [1/4]
void ccprintf (cp::Print & print) inline
Definition at line 131 of file cprintf.hh.
References cp::Print::end_args().
Referenced by abortHandler(), Terminal::accept(), Stats::Text::begin(), ccprintf(), sc_core::sc_vector_base::checkIndex(), MemTest::completeRequest(), cprintf(), csprintf(), sc_core::sc_report_handler::default_handler(), X86ISA::X86FaultBase::describe(), X86ISA::PageFault::describe(), Trace::Logger::dprintf(), Trace::IntelTraceRecord::dump(), ProfileNode::dump(), Trace::Logger::dump(), FunctionProfile::dump(), Trie< Key, Value >::Node::dump(), Trie< Addr, uint32_t >::dump(), dumpDmesgEntry(), Trace::ExeTracerRecord::dumpTicks(), Stats::Text::end(), AbstractMemory::functionalAccess(), PowerISA::MiscOp::generateDisassembly(), SparcISA::Mem::generateDisassembly(), ImmOp64::generateDisassembly(), SparcISA::Trap::generateDisassembly(), PowerISA::CondLogicOp::generateDisassembly(), ArmISA::SysDC64::generateDisassembly(), PowerISA::PowerStaticInst::generateDisassembly(), SparcISA::BranchDisp::generateDisassembly(), SparcISA::BlockMemMicro::generateDisassembly(), SparcISA::MemImm::generateDisassembly(), SparcISA::RdPriv::generateDisassembly(), ArmISA::SveIndexIIOp::generateDisassembly(), ArmISA::SveMemVecFillSpill::generateDisassembly(), SparcISA::IntOpImm::generateDisassembly(), RegRegImmImmOp64::generateDisassembly(), ArmISA::DataXImmOnlyOp::generateDisassembly(), PowerISA::MemDispOp::generateDisassembly(), SparcISA::WrPriv::generateDisassembly(), PowerISA::CondMoveOp::generateDisassembly(), MsrImmOp::generateDisassembly(), SparcISA::BlockMemImmMicro::generateDisassembly(), ArmISA::SveIndexIROp::generateDisassembly(), PowerISA::BranchPCRel::generateDisassembly(), PowerISA::IntOp::generateDisassembly(), RegRegRegImmOp64::generateDisassembly(), ArmISA::SveMemPredFillSpill::generateDisassembly(), ArmISA::SveLdStructSS< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), ArmISA::SveIndexRIOp::generateDisassembly(), SparcISA::WrPrivImm::generateDisassembly(), X86ISA::X86MicroopBase::generateDisassembly(), ArmISA::SveIndexRROp::generateDisassembly(), SparcISA::BranchImm13::generateDisassembly(), PowerISA::IntImmOp::generateDisassembly(), X86ISA::RegOpImm::generateDisassembly(), ArmISA::BranchRegReg::generateDisassembly(), ArmISA::SveContigMemSS::generateDisassembly(), PowerISA::BranchNonPCRel::generateDisassembly(), SparcISA::SetHi::generateDisassembly(), ArmISA::DataX1RegOp::generateDisassembly(), X86ISA::MediaOpImm::generateDisassembly(), ArmISA::SvePredCountOp::generateDisassembly(), PowerISA::IntShiftOp::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), ArmISA::DataX1RegImmOp::generateDisassembly(), ArmISA::MemoryImm64::generateDisassembly(), ArmISA::SveContigMemSI::generateDisassembly(), PowerISA::FloatOp::generateDisassembly(), ImmOp::generateDisassembly(), ArmISA::SvePredCountPredOp::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), ArmISA::DataX1Reg2ImmOp::generateDisassembly(), RegImmOp::generateDisassembly(), ArmISA::SveWhileOp::generateDisassembly(), MiscRegImmOp64::generateDisassembly(), ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::SveStStructSS< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), PowerISA::IntRotateOp::generateDisassembly(), ArmISA::DataX2RegOp::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::SveCompTermOp::generateDisassembly(), ArmISA::MemoryPreIndex64::generateDisassembly(), ArmISA::SveUnaryPredOp::generateDisassembly(), ArmISA::DataX2RegImmOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), ArmISA::MemoryPostIndex64::generateDisassembly(), PowerISA::BranchPCRelCond::generateDisassembly(), ArmISA::SveUnaryUnpredOp::generateDisassembly(), ArmISA::DataX3RegOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), ArmISA::SveUnaryWideImmUnpredOp::generateDisassembly(), ArmISA::MemoryReg64::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), PowerISA::BranchNonPCRelCond::generateDisassembly(), ArmISA::MemoryRaw64::generateDisassembly(), ArmISA::SveUnaryWideImmPredOp::generateDisassembly(), ArmISA::SveLdStructSI< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), PowerISA::BranchRegCond::generateDisassembly(), ArmISA::SveBinImmUnpredConstrOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), RegRegImmOp::generateDisassembly(), ArmISA::SveBinImmPredOp::generateDisassembly(), ArmISA::SveBinWideImmUnpredOp::generateDisassembly(), ArmISA::SveBinDestrPredOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::SveStStructSI< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), ArmISA::SveBinConstrPredOp::generateDisassembly(), RegImmImmOp::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), ArmISA::SveBinUnpredOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), ArmISA::SveBinIdxUnpredOp::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), ArmISA::MicroIntRegXOp::generateDisassembly(), ArmISA::SvePredLogicalOp::generateDisassembly(), ArmISA::PredMacroOp::generateDisassembly(), ArmISA::SvePredBinPermOp::generateDisassembly(), ArmISA::SveCmpOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::SveCmpImmOp::generateDisassembly(), ArmISA::SveIndexedMemVI< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::SveTerPredOp::generateDisassembly(), ArmISA::SveTerImmUnpredOp::generateDisassembly(), ArmISA::SveReducOp::generateDisassembly(), ArmISA::SveOrdReducOp::generateDisassembly(), ArmISA::SvePtrueOp::generateDisassembly(), ArmISA::SveIntCmpOp::generateDisassembly(), ArmISA::SveIndexedMemSV< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::generateDisassembly(), ArmISA::SveIntCmpImmOp::generateDisassembly(), ArmISA::SveAdrOp::generateDisassembly(), ArmISA::SveElemCountOp::generateDisassembly(), ArmISA::SvePartBrkOp::generateDisassembly(), ArmISA::SvePartBrkPropOp::generateDisassembly(), ArmISA::SveSelectOp::generateDisassembly(), ArmISA::SveUnaryPredPredOp::generateDisassembly(), ArmISA::SveTblOp::generateDisassembly(), ArmISA::SveUnpackOp::generateDisassembly(), ArmISA::SvePredTestOp::generateDisassembly(), ArmISA::SvePredUnaryWImplicitSrcPredOp::generateDisassembly(), ArmISA::SveBinImmUnpredDestrOp::generateDisassembly(), ArmISA::SveBinImmIdxUnpredOp::generateDisassembly(), ArmISA::SveUnarySca2VecUnpredOp::generateDisassembly(), ArmISA::SveDotProdIdxOp::generateDisassembly(), ArmISA::SveDotProdOp::generateDisassembly(), ArmISA::SveComplexOp::generateDisassembly(), ArmISA::SveComplexIdxOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegRegImmOp::generateDisassembly(), Terminal::listen(), BaseRemoteGDB::listen(), VncServer::listen(), TapListener::listen(), Trace::OstreamLogger::logMessage(), main(), Trace::NativeTrace::NativeTrace(), Stats::ScalarPrint::operator()(), Stats::VectorPrint::operator()(), Stats::DistPrint::operator()(), Net::operator<<(), operator<<(), sc_core::operator<<(), GenericISA::operator<<(), X86ISA::operator<<(), sc_gem5::VcdTraceScope::output(), sc_gem5::VcdTraceValFloat< T >::output(), sc_gem5::VcdTraceValFxval< T >::output(), Throttle::print(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), WriteQueueEntry::TargetList::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::print(), Logger::print(), MessageBuffer::print(), Trace::TarmacTracerRecord::TraceRegEntry::print(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::print(), WriteQueueEntry::print(), Trace::TarmacTracerRecord::TraceMemEntry::print(), MSHR::TargetList::print(), CacheBlkPrintWrapper::print(), MSHR::print(), Packet::print(), ArmISA::ArmStaticInst::printCCReg(), ArmISA::ArmStaticInst::printDataInst(), ArmISA::ArmStaticInst::printExtendOperand(), ArmISA::ArmStaticInst::printFloatReg(), ArmISA::ArmStaticInst::printIntReg(), Packet::PrintReqState::printLabels(), X86ISA::X86StaticInst::printMem(), ArmISA::ArmStaticInst::printMemSymbol(), ArmISA::ArmStaticInst::printMiscReg(), X86ISA::X86StaticInst::printMnemonic(), SparcISA::SparcStaticInst::printMnemonic(), ArmISA::MemoryImm::printOffset(), ArmISA::MemoryReg::printOffset(), ArmISA::ArmStaticInst::printPFflags(), SparcISA::IntOp::printPseudoOps(), SparcISA::IntOpImm::printPseudoOps(), PowerISA::PowerStaticInst::printReg(), SparcISA::SparcStaticInst::printReg(), X86ISA::X86StaticInst::printReg(), X86ISA::X86StaticInst::printSegment(), ArmISA::ArmStaticInst::printTarget(), ArmISA::ArmStaticInst::printVecPredReg(), ArmISA::ArmStaticInst::printVecReg(), DumpStatsPCEvent::process(), BaseCPU::regStats(), System::regStats(), sc_core::sc_report_compose_message(), ArmISA::ArmStaticInst::shift_carry_imm(), ArmISA::ArmStaticInst::shift_carry_rs(), ArmISA::ArmStaticInst::shift_rm_imm(), ArmISA::ArmStaticInst::shift_rm_rs(), ArmISA::ArmStaticInst::shiftReg64(), ArmISA::Memory64::startDisassembly(), TEST(), sc_gem5::VcdTraceFile::trace(), BaseCPU::traceFunctionsInternal(), Trace::ExeTracerRecord::traceInst(), and sc_gem5::VcdTraceFile::~VcdTraceFile().
ccprintf() [2/4]
template<typename T , typename ... Args> void ccprintf (cp::Print & print, const T & value, const Args &... args)
Definition at line 138 of file cprintf.hh.
References cp::Print::add_arg(), and ccprintf().
ccprintf() [3/4]
template<typename ... Args> void ccprintf (std::ostream & stream, const char * format, const Args &... args)
Definition at line 147 of file cprintf.hh.
References ccprintf().
ccprintf() [4/4]
template<typename ... Args> void ccprintf (std::ostream & stream, const std::string & format, const Args &... args)
Definition at line 175 of file cprintf.hh.
References ccprintf().
cprintf() [1/2]
template<typename ... Args> void cprintf (const char * format, const Args &... args)
Definition at line 156 of file cprintf.hh.
References ccprintf().
Referenced by Stats::Info::baseCheck(), Debug::breakpoint(), UnitTest::checkVal(), EventQueue::debugVerify(), sc_core::sc_report_handler::default_handler(), ActivityRecorder::dump(), StoreSet::dump(), DependencyGraph< DynInstPtr >::dump(), PCEventQueue::dump(), BPredUnit::dump(), Event::dump(), BaseDynInst< Impl >::dump(), EventQueue::dump(), Checker< O3CPUImpl >::dumpAndExit(), dumpDebugFlags(), DefaultRename< Impl >::dumpHistory(), LSQUnit< Impl >::dumpInsts(), InstructionQueue< Impl >::dumpInsts(), FullO3CPU< O3CPUImpl >::dumpInsts(), Checker< O3CPUImpl >::dumpInsts(), MemDepUnit< MemDepPred, Impl >::dumpLists(), InstructionQueue< Impl >::dumpLists(), fixClockFrequency(), X86ISA::GpuTLB::GpuTLB(), EmbeddedPyBind::init(), StatTest::init(), main(), UnitTest::printResults(), CPUProgressEvent::process(), BaseDynInst< Impl >::~BaseDynInst(), and InstructionQueue< Impl >::~InstructionQueue().
cprintf() [2/2]
template<typename ... Args> void cprintf (const std::string & format, const Args &... args)
Definition at line 181 of file cprintf.hh.
References ccprintf().
csprintf() [1/2]
template<typename ... Args> std::string csprintf (const char * format, const Args &... args)
Definition at line 162 of file cprintf.hh.
References ccprintf(), and cp::Print::stream.
Referenced by SMMUv3SlaveInterface::atsSlaveRecvAtomic(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), BaseCPU::BaseCPU(), Stats::Text::beginGroup(), CxxConfigManager::bindMasterPort(), CxxConfigManager::bindObjectPorts(), CxxConfigManager::bindPort(), BaseRemoteGDB::cmd_signal(), CoherentXBar::CoherentXBar(), MemChecker::completeRead(), csprintf(), ArmISA::PMU::CounterState::debugCounter(), SRegOperand::disassemble(), DRegOperand::disassemble(), CRegOperand::disassemble(), ImmOperand< SrcCType >::disassemble(), AddrOperandBase::disassemble(), ListOperand::disassemble(), FunctionRefOperand::disassemble(), Pl111::dmaDone(), O3ThreadState< Impl >::dumpFuncProfile(), SimpleThread::dumpFuncProfile(), sc_core::sc_in_resolved::end_of_elaboration(), sc_core::sc_inout_resolved::end_of_elaboration(), sc_gem5::Module::endOfElaboration(), Linux::etcPasswd(), EtherSwitch::EtherSwitch(), CxxConfigManager::findObject(), CxxConfigManager::findObjectParams(), CxxConfigManager::findObjectType(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::formatReg(), HsailISA::BrnInstBase< SRegOperand >::generateDisassembly(), RiscvISA::MemFenceMicro::generateDisassembly(), PowerISA::MemOp::generateDisassembly(), DecoderFaultInst::generateDisassembly(), RiscvISA::Unknown::generateDisassembly(), SparcISA::FailUnimplemented::generateDisassembly(), FailUnimplemented::generateDisassembly(), UnknownOp64::generateDisassembly(), HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >::generateDisassembly(), SparcISA::WarnUnimplemented::generateDisassembly(), WarnUnimplemented::generateDisassembly(), HsailISA::CbrInstBase< SRegOperand >::generateDisassembly(), HsailISA::LdaInst< DestDataType, AddrOperandType >::generateDisassembly(), MiscRegImplDefined64::generateDisassembly(), HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >::generateDisassembly(), HsailISA::BrInstBase< SRegOperand >::generateDisassembly(), UnknownOp::generateDisassembly(), McrMrcMiscInst::generateDisassembly(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::generateDisassembly(), HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >::generateDisassembly(), McrMrcImplDefined::generateDisassembly(), HsailISA::Stub::generateDisassembly(), HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >::generateDisassembly(), HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >::generateDisassembly(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::generateDisassembly(), HsailISA::Call::generateDisassembly(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::generateDisassembly(), GenericTimerMem::GenericTimerMem(), getEventQueue(), CxxConfigManager::getObject(), FastModel::GIC::getPort(), ComputeUnit::getPort(), GpuDispatcher::GpuDispatcher(), X86ISA::GpuTLB::GpuTLB(), X86ISA::I8042::I8042(), X86ISA::I82094AA::I82094AA(), X86ISA::I8254::I8254(), X86ISA::I8259::I8259(), MemDepUnit< MemDepPred, Impl >::init(), sc_gem5::VcdTraceFile::initialize(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), SMMUTranslationProcess::issuePrefetch(), MachineIDToString(), HsailISA::Call::MagicPrintWF32(), HsailISA::Call::MagicPrintWF32ID(), HsailISA::Call::MagicPrintWF64(), HsailISA::Call::MagicPrintWFFloat(), HsailISA::Call::MagicPrintWFID64(), HsailISA::Call::MagicSimBreak(), Throttle::name(), PerfectSwitch::name(), CopyEngine::CopyEngineChannel::name(), PciHost::DeviceInterface::name(), SimpleThread::name(), Event::name(), DRAMCtrl::Rank::name(), NoncoherentXBar::NoncoherentXBar(), HsailISA::ArithInst< DataType, NumSrcOperands >::opcode_suffix(), HsailISA::CmpInst< DestDataType, SrcDataType >::opcode_suffix(), HsailISA::CvtInst< DestDataType, SrcDataType >::opcode_suffix(), HsailISA::PopcountInst< DestDataType, SrcDataType >::opcode_suffix(), operator<<(), sc_gem5::VcdTraceScope::output(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), FALRUBlk::print(), CompressionBlk::print(), SectorSubBlk::print(), VecPredRegT< VecElem, NumElems, Packed, Const >::print(), BaseTags::print(), VecRegT< VecElem, NumElems, Const >::print(), ArmISA::TlbEntry::print(), VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::print(), CacheBlk::print(), DictionaryCompressor< T >::Pattern::print(), VecRegContainer< TheISA::VecRegSizeBytes >::print(), AnnotateDumpCallback::process(), Linux::procMeminfo(), Serializable::ScopedCheckpointSection::pushName(), HDLcd::pxlFrameDone(), SMMUv3SlaveInterface::recvAtomic(), SMMUv3SlaveInterface::recvTimingReq(), Profiler::regStats(), ExecStage::regStats(), Throttle::regStats(), GarnetNetwork::regStats(), SMMUv3::regStats(), WalkCache::regStats(), ComputeUnit::regStats(), TrafficGen::resolveFile(), RubyDirectedTester::RubyDirectedTester(), RubyPort::RubyPort(), RubyTester::RubyTester(), FastModel::ScxEvsCortexA76< Types >::ScxEvsCortexA76(), ArmSemihosting::semiExit(), FlashDevice::serialize(), SymbolTable::serialize(), ArmSemihosting::serialize(), ArmISA::PMU::serialize(), RiscvISA::TLB::serialize(), MipsISA::TLB::serialize(), AlphaISA::TLB::serialize(), EtherLink::Link::serialize(), Gicv3::serialize(), Iob::serialize(), X86ISA::TLB::serialize(), EmulationPageTable::serialize(), EtherSwitch::Interface::PortFifo::serialize(), PowerISA::TLB::serialize(), SparcISA::TLB::serialize(), CpuLocalTimer::serialize(), CopyEngine::serialize(), VGic::serialize(), PacketFifo::serialize(), GenericTimer::serialize(), PciDevice::serialize(), PhysicalMemory::serialize(), Sinic::Device::serialize(), IGbE::DescCache< iGbReg::RxDesc >::serialize(), ArmISA::TLB::serialize(), BaseCPU::serialize(), DistIface::RecvScheduler::serialize(), GicV2::serialize(), VirtIODeviceBase::serialize(), CheckpointIn::setDir(), CxxConfigManager::setParam(), CxxConfigManager::setParamVector(), SimpleCache::SimpleCache(), Stats::Text::statName(), Stats::ScalarProxy< Stat >::str(), Stats::ConstVectorNode< T >::str(), Stats::BinaryNode< Op >::str(), Stats::SumNode< Op >::str(), TLBCoalescer::TLBCoalescer(), AddrRange::to_string(), BaseCPU::traceFunctionsInternal(), Trace::ExeTracerRecord::traceInst(), BaseRemoteGDB::trap(), FlashDevice::unserialize(), SymbolTable::unserialize(), ArmSemihosting::unserialize(), ArmISA::PMU::unserialize(), RiscvISA::TLB::unserialize(), MipsISA::TLB::unserialize(), AlphaISA::TLB::unserialize(), EtherLink::Link::unserialize(), Gicv3::unserialize(), Iob::unserialize(), X86ISA::TLB::unserialize(), EmulationPageTable::unserialize(), EtherSwitch::Interface::PortFifo::unserialize(), PowerISA::TLB::unserialize(), SparcISA::TLB::unserialize(), CpuLocalTimer::unserialize(), CopyEngine::unserialize(), VGic::unserialize(), PacketFifo::unserialize(), GenericTimer::unserialize(), PciDevice::unserialize(), PhysicalMemory::unserialize(), Sinic::Device::unserialize(), IGbE::DescCache< iGbReg::RxDesc >::unserialize(), ArmISA::TLB::unserialize(), BaseCPU::unserialize(), DistIface::RecvScheduler::unserialize(), GicV2::unserialize(), VirtIODeviceBase::unserialize(), sc_core::wait(), and X86ISA::Cmos::X86RTC::X86RTC().
csprintf() [2/2]
template<typename ... Args> std::string csprintf (const std::string & format, const Args &... args)
Definition at line 187 of file cprintf.hh.
References csprintf().