gem5: dev/storage/disk_image.cc File Reference
disk_image.cc File Reference
Disk Image Definitions.
#include "dev/storage/disk_image.hh"
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <string>
#include "base/callback.hh"
#include "base/logging.hh"
#include "base/trace.hh"
#include "debug/DiskImageRead.hh"
#include "debug/DiskImageWrite.hh"
#include "sim/byteswap.hh"
#include "sim/sim_exit.hh"
Classes
class CowDiskCallback
Functions
void SafeRead (ifstream &stream, void *data, int count)
template<class T >
void SafeRead (ifstream &stream, T &data)
template<class T >
void SafeReadSwap (ifstream &stream, T &data)
void SafeWrite (ofstream &stream, const void *data, int count)
template<class T >
void SafeWrite (ofstream &stream, const T &data)
template<class T >
void SafeWriteSwap (ofstream &stream, const T &data)
Detailed Description
Disk Image Definitions.
Definition in file disk_image.cc.
Function Documentation
SafeRead() [1/2]
void SafeRead (ifstream & stream, void * data, int count)
Definition at line 222 of file disk_image.cc.
References panic.
Referenced by CowDiskImage::open(), SafeRead(), and SafeReadSwap().
SafeRead() [2/2]
template<class T > void SafeRead (ifstream & stream, T & data)
Definition at line 237 of file disk_image.cc.
References SafeRead().
SafeReadSwap()
template<class T > void SafeReadSwap (ifstream & stream, T & data)
Definition at line 244 of file disk_image.cc.
References letoh(), and SafeRead().
Referenced by CowDiskImage::open().
SafeWrite() [1/2]
void SafeWrite (ofstream & stream, const void * data, int count)
Definition at line 305 of file disk_image.cc.
References panic.
Referenced by SafeWrite(), SafeWriteSwap(), and CowDiskImage::save().
SafeWrite() [2/2]
template<class T > void SafeWrite (ofstream & stream, const T & data)
Definition at line 320 of file disk_image.cc.
References SafeWrite().
SafeWriteSwap()
template<class T > void SafeWriteSwap (ofstream & stream, const T & data)
Definition at line 327 of file disk_image.cc.
References letoh(), and SafeWrite().
Referenced by CowDiskImage::save().