gem5: arch/x86/bios/e820.cc File Reference
e820.cc File Reference
#include "arch/x86/bios/e820.hh"
#include "arch/x86/isa_traits.hh"
#include "mem/port_proxy.hh"
#include "sim/byteswap.hh"
Functions
template<class T >
void writeVal (T val, PortProxy &proxy, Addr &addr)
Function Documentation
writeVal()
template<class T > void writeVal (T val, PortProxy & proxy, Addr & addr)
Definition at line 50 of file e820.cc.
References htole(), and PortProxy::writeBlob().
Referenced by X86ISA::E820Table::writeTo().