gem5: base/hostinfo.hh File Reference
hostinfo.hh File Reference
#include <string>
#include "base/types.hh"
Functions
std::string __get_hostname ()
std::string & hostname ()
uint64_t procInfo (const char *filename, const char *target)
uint64_t memUsage ()
Determine the simulator process' total virtual memory usage.
Function Documentation
__get_hostname()
std::string __get_hostname ()
Definition at line 57 of file hostinfo.cc.
References warn.
Referenced by hostname().
hostname()
std::string& hostname ()
Definition at line 66 of file hostinfo.cc.
References __get_hostname(), and hostname().
Referenced by hostname().
memUsage()
uint64_t memUsage ()
Determine the simulator process' total virtual memory usage.
Returns
virtual memory usage in kilobytes
Definition at line 101 of file hostinfo.cc.
References procInfo().
Referenced by Stats::Global::Global().
procInfo()
uint64_t procInfo (const char * filename, const char * target)
Definition at line 73 of file hostinfo.cc.
References ArmISA::format, ArmISA::fp, startswith(), and usage().
Referenced by memUsage().