gem5: gpu-compute/hsail_code.hh File Reference
hsail_code.hh File Reference
#include <cassert>
#include <list>
#include <map>
#include <string>
#include <vector>
#include "arch/gpu_decoder.hh"
#include "arch/hsail/Brig.h"
#include "base/addr_range_map.hh"
#include "base/intmath.hh"
#include "config/the_gpu_isa.hh"
#include "gpu-compute/hsa_code.hh"
#include "gpu-compute/hsa_kernel_info.hh"
#include "gpu-compute/misc.hh"
Classes
class Label
class LabelMap
class StorageElement
class StorageSpace
class StorageMap
class HsailCode
Enumerations
enum base_type_e {
BT_DEFAULT, BT_B8, BT_U8, BT_U16,
BT_U32, BT_U64, BT_S8, BT_S16,
BT_S32, BT_S64, BT_F16, BT_F32,
BT_F64, BT_NULL
}
Functions
int popcount (uint64_t src, int sz)
int firstbit (uint64_t src, int sz)
int lastbit (uint64_t src, int sz)
int signbit (uint64_t src, int sz)
uint64_t bitrev (uint64_t src, int sz)
uint64_t mul_hi (uint32_t a, uint32_t b)
uint64_t mul_hi (int32_t a, int32_t b)
uint64_t mul_hi (uint64_t a, uint64_t b)
uint64_t mul_hi (int64_t a, int64_t b)
uint64_t mul_hi (double a, double b)
Variables
const int NumSegments = Brig::BRIG_SEGMENT_AMD_GCN
const char * segmentNames []
Enumeration Type Documentation
base_type_e
enum base_type_e
Enumerator
BT_DEFAULT
BT_B8
BT_U8
BT_U16
BT_U32
BT_U64
BT_S8
BT_S16
BT_S32
BT_S64
BT_F16
BT_F32
BT_F64
BT_NULL
Definition at line 293 of file hsail_code.hh.
Function Documentation
bitrev()
uint64_t bitrev (uint64_t src, int sz) inline
Definition at line 122 of file hsail_code.hh.
References ArmISA::i, and MipsISA::r.
firstbit()
int firstbit (uint64_t src, int sz) inline
Definition at line 72 of file hsail_code.hh.
References ArmISA::i.
lastbit()
int lastbit (uint64_t src, int sz) inline
Definition at line 86 of file hsail_code.hh.
References ArmISA::i.
mul_hi() [1/5]
uint64_t mul_hi (uint32_t a, uint32_t b) inline
Definition at line 137 of file hsail_code.hh.
mul_hi() [2/5]
uint64_t mul_hi (int32_t a, int32_t b) inline
Definition at line 143 of file hsail_code.hh.
mul_hi() [3/5]
uint64_t mul_hi (uint64_t a, uint64_t b) inline
Definition at line 149 of file hsail_code.hh.
mul_hi() [4/5]
uint64_t mul_hi (int64_t a, int64_t b) inline
Definition at line 155 of file hsail_code.hh.
mul_hi() [5/5]
uint64_t mul_hi (double a, double b) inline
Definition at line 161 of file hsail_code.hh.
popcount()
int popcount (uint64_t src, int sz) inline
Definition at line 58 of file hsail_code.hh.
References ArmISA::i.
signbit()
int signbit (uint64_t src, int sz) inline
Definition at line 100 of file hsail_code.hh.
References ArmISA::i.
Referenced by ArmISA::fpMaxNum(), ArmISA::fpMinNum(), ArmISA::fpRecipEstimate(), and ArmISA::fprSqrtEstimate().
Variable Documentation
NumSegments
const int NumSegments = Brig::BRIG_SEGMENT_AMD_GCN
Definition at line 219 of file hsail_code.hh.
Referenced by StorageMap::addSymbol(), StorageMap::getSize(), and StorageMap::StorageMap().
segmentNames
const char* segmentNames[]
Definition at line 69 of file brig_object.cc.