gem5: sim/init_signals.hh File Reference
init_signals.hh File Reference
Functions
void dumpStatsHandler (int sigtype)
Stats signal handler.
void dumprstStatsHandler (int sigtype)
void exitNowHandler (int sigtype)
Exit signal handler.
void abortHandler (int sigtype)
Abort signal handler.
void initSignals ()
Function Documentation
abortHandler()
void abortHandler (int sigtype)
Abort signal handler.
Definition at line 147 of file init_signals.cc.
References ccprintf(), curEventQueue(), PowerISA::eq, EventQueue::getCurTick(), print_backtrace(), raiseFatalSignal(), and STATIC_ERR.
Referenced by initSignals().
dumprstStatsHandler()
void dumprstStatsHandler (int sigtype)
Definition at line 126 of file init_signals.cc.
References async_event, async_statdump, async_statreset, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
dumpStatsHandler()
void dumpStatsHandler (int sigtype)
Stats signal handler.
Definition at line 117 of file init_signals.cc.
References async_event, async_statdump, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
exitNowHandler()
void exitNowHandler (int sigtype)
Exit signal handler.
Definition at line 137 of file init_signals.cc.
References async_event, async_exit, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
initSignals()
void initSignals ()
Definition at line 185 of file init_signals.cc.
References abortHandler(), dumprstStatsHandler(), dumpStatsHandler(), exitNowHandler(), installSignalHandler(), ioHandler(), segvHandler(), setupAltStack(), and warn.
Referenced by main().