gem5: base/match.test.cc File Reference
match.test.cc File Reference
#include <gtest/gtest.h>
#include "base/match.hh"
Functions
TEST (MatchTest, Add)
TEST (MatchTest, SetExpression)
TEST (MatchTest, SetExpressionVector)
TEST (MatchTest, SimpleMatch)
TEST (MatchTest, SimpleMismatch)
TEST (MatchTest, MultipleExpressionsMatch)
TEST (MatchTest, MultipleExpressionsMismatch)
TEST (MatchTest, WildCardMatch)
TEST (MatchTest, WildCardMismatch)
TEST (MatchTest, TokensEmptyNoMatch)
Function Documentation
TEST() [1/10]
TEST (MatchTest , Add)
Definition at line 35 of file match.test.cc.
References ObjectMatch::add(), EXPECT_EQ, and ObjectMatch::getExpressions().
TEST() [2/10]
TEST (MatchTest , SetExpression)
Definition at line 60 of file match.test.cc.
References EXPECT_EQ, ObjectMatch::getExpressions(), and ObjectMatch::setExpression().
TEST() [3/10]
TEST (MatchTest , SetExpressionVector)
Definition at line 77 of file match.test.cc.
References EXPECT_EQ, ObjectMatch::getExpressions(), and ObjectMatch::setExpression().
TEST() [4/10]
TEST (MatchTest , SimpleMatch)
Definition at line 103 of file match.test.cc.
References EXPECT_TRUE, and ObjectMatch::match().
TEST() [5/10]
TEST (MatchTest , SimpleMismatch)
Definition at line 109 of file match.test.cc.
References EXPECT_FALSE, and ObjectMatch::match().
TEST() [6/10]
TEST (MatchTest , MultipleExpressionsMatch)
Definition at line 115 of file match.test.cc.
References EXPECT_TRUE, ObjectMatch::match(), and ObjectMatch::setExpression().
TEST() [7/10]
TEST (MatchTest , MultipleExpressionsMismatch)
Definition at line 127 of file match.test.cc.
References EXPECT_FALSE, ObjectMatch::match(), and ObjectMatch::setExpression().
TEST() [8/10]
TEST (MatchTest , WildCardMatch)
Definition at line 139 of file match.test.cc.
References EXPECT_TRUE, and ObjectMatch::match().
TEST() [9/10]
TEST (MatchTest , WildCardMismatch)
Definition at line 151 of file match.test.cc.
References EXPECT_FALSE, and ObjectMatch::match().
TEST() [10/10]
TEST (MatchTest , TokensEmptyNoMatch)
Definition at line 159 of file match.test.cc.
References EXPECT_FALSE, and ObjectMatch::match().