gem5: mem/ruby/network/MessageBuffer.hh File Reference
MessageBuffer.hh File Reference
#include <algorithm>
#include <cassert>
#include <functional>
#include <iostream>
#include <string>
#include <vector>
#include "base/trace.hh"
#include "debug/RubyQueue.hh"
#include "mem/packet.hh"
#include "mem/port.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Consumer.hh"
#include "mem/ruby/network/dummy_port.hh"
#include "mem/ruby/slicc_interface/Message.hh"
#include "params/MessageBuffer.hh"
#include "sim/sim_object.hh"
Classes
class MessageBuffer
Functions
Tick random_time ()
std::ostream & operator<< (std::ostream &out, const MessageBuffer &obj)
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & out, const MessageBuffer & obj) inline
Definition at line 217 of file MessageBuffer.hh.
References MessageBuffer::print().
random_time()
Tick random_time ()
Definition at line 139 of file MessageBuffer.cc.
References Random::random(), and random_mt.
Referenced by MessageBuffer::enqueue().