gem5: Debug Namespace Reference
Debug Namespace Reference
Classes
struct AllFlags
class CompoundFlag
class Flag
class SimpleFlag
Typedefs
typedef std::map< std::string, Flag * > FlagsMap
Functions
void breakpoint ()
FlagsMap & allFlags ()
Flag * findFlag (const std::string &name)
bool changeFlag (const char *s, bool value)
Variables
int allFlagsVersion = 0
AllFlags theAllFlags
Flag *const All = &theAllFlags
Typedef Documentation
FlagsMap
typedef std::map<std::string, Flag *> Debug::FlagsMap
Definition at line 125 of file debug.hh.
Function Documentation
allFlags()
FlagsMap & Debug::allFlags ()
Definition at line 66 of file debug.cc.
Referenced by Debug::AllFlags::disable(), Debug::SimpleFlag::disableAll(), dumpDebugFlags(), Debug::AllFlags::enable(), Debug::SimpleFlag::enableAll(), findFlag(), Debug::Flag::Flag(), and pybind_init_debug().
breakpoint()
void Debug::breakpoint ()
Definition at line 52 of file debug.cc.
References cprintf().
Referenced by PseudoInst::debugbreak(), Stats::Info::Info(), DebugBreakEvent::process(), BreakPCEvent::process(), and NSGigE::txKick().
changeFlag()
bool Debug::changeFlag (const char * s, bool value)
Definition at line 161 of file debug.cc.
References Debug::Flag::disable(), Debug::Flag::enable(), ArmISA::f, and findFlag().
Referenced by clearDebugFlag(), and setDebugFlag().
findFlag()
Flag * Debug::findFlag (const std::string & name)
Definition at line 75 of file debug.cc.
References allFlags(), and ArmISA::i.
Referenced by changeFlag(), and pybind_init_debug().
Variable Documentation
All
Flag *const Debug::All = &theAllFlags
Definition at line 158 of file debug.cc.
allFlagsVersion
int Debug::allFlagsVersion = 0
Definition at line 64 of file debug.cc.
Referenced by Debug::Flag::Flag(), and pybind_init_debug().
theAllFlags
AllFlags Debug::theAllFlags
Definition at line 157 of file debug.cc.