gem5: HsailISA Namespace Reference
HsailISA Namespace Reference
Classes
class ArithInst
class AtomicInst
class AtomicInstBase
class Barrier
class BrDirectInst
class BrIndirectInst
class BrInstBase
class BrnDirectInst
class BrnIndirectInst
class BrnInstBase
class Call
class CbrDirectInst
class CbrIndirectInst
class CbrInstBase
class ClassInst
class CmovInst
class CmpInst
class CmpInstBase
class CommonInstBase
class CvtInst
class Decoder
class ExtractInsertInst
class GPUISA
class HsailDataType
class HsailGPUStaticInst
class HsailOperandType
class LdaInst
class LdaInstBase
class LdInst
class LdInstBase
struct MachInst
class MemFence
class MemInst
class PopcountInst
class Ret
class ShiftInst
class SpecialInst1Src
class SpecialInst1SrcBase
class SpecialInstNoSrc
class SpecialInstNoSrcBase
class SpecialInstNoSrcNoDest
class StInst
class StInstBase
class Stub
class ThreeNonUniformSourceInst
class ThreeNonUniformSourceInstBase
class TwoNonUniformSourceInst
class TwoNonUniformSourceInstBase
Typedefs
typedef uint32_t RawMachInst
typedef HsailOperandType< CRegOperand, CRegOrImmOperand > CRegOperandType
typedef HsailOperandType< SRegOperand, SRegOrImmOperand > SRegOperandType
typedef HsailOperandType< DRegOperand, DRegOrImmOperand > DRegOperandType
typedef HsailDataType< CRegOperandType, bool, Enums::M_U8, VT_32, 1 > B1
typedef HsailDataType< SRegOperandType, uint8_t, Enums::M_U8, VT_32, 1 > B8
typedef HsailDataType< SRegOperandType, uint16_t, Enums::M_U16, VT_32, 1 > B16
typedef HsailDataType< SRegOperandType, uint32_t, Enums::M_U32, VT_32, 1 > B32
typedef HsailDataType< DRegOperandType, uint64_t, Enums::M_U64, VT_64, 1 > B64
typedef HsailDataType< SRegOperandType, int8_t, Enums::M_S8, VT_32 > S8
typedef HsailDataType< SRegOperandType, int16_t, Enums::M_S16, VT_32 > S16
typedef HsailDataType< SRegOperandType, int32_t, Enums::M_S32, VT_32 > S32
typedef HsailDataType< DRegOperandType, int64_t, Enums::M_S64, VT_64 > S64
typedef HsailDataType< SRegOperandType, uint8_t, Enums::M_U8, VT_32 > U8
typedef HsailDataType< SRegOperandType, uint16_t, Enums::M_U16, VT_32 > U16
typedef HsailDataType< SRegOperandType, uint32_t, Enums::M_U32, VT_32 > U32
typedef HsailDataType< DRegOperandType, uint64_t, Enums::M_U64, VT_64 > U64
typedef HsailDataType< SRegOperandType, float, Enums::M_F32, VT_32 > F32
typedef HsailDataType< DRegOperandType, double, Enums::M_F64, VT_64 > F64
Enumerations
enum {
MAGIC_PRINT_WF_32 = 0, MAGIC_PRINT_WF_64, MAGIC_PRINT_LANE, MAGIC_PRINT_LANE_64,
MAGIC_PRINT_WF_FLOAT, MAGIC_SIM_BREAK, MAGIC_PREF_SUM, MAGIC_REDUCTION,
MAGIC_MASKLANE_LOWER, MAGIC_MASKLANE_UPPER, MAGIC_JOIN_WF_BAR, MAGIC_WAIT_WF_BAR,
MAGIC_PANIC, MAGIC_ATOMIC_NR_ADD_GLOBAL_U32_REG, MAGIC_ATOMIC_NR_ADD_GROUP_U32_REG, MAGIC_LOAD_GLOBAL_U32_REG,
MAGIC_XACT_CAS_LD, MAGIC_MOST_SIG_THD, MAGIC_MOST_SIG_BROADCAST, MAGIC_PRINT_WFID_32,
MAGIC_PRINT_WFID_64
}
Functions
GPUStaticInst * decodeBrn (const Brig::BrigInstBase *ib, const BrigObject *obj)
GPUStaticInst * decodeCbr (const Brig::BrigInstBase *ib, const BrigObject *obj)
GPUStaticInst * decodeBr (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename T >
bool fpclassify (T src0, uint32_t src1)
template<typename T >
bool compare (T src0, T src1, Brig::BrigCompareOperation cmpOp)
template<typename T >
int32_t firstbit (T src0)
const char * cmpOpToString (Brig::BrigCompareOperation cmpOp)
template<typename T >
T heynot (T arg)
template<>
bool heynot< bool > (bool arg)
const char * atomicOpToString (BrigAtomicOperation brigOp)
template<typename DataType >
GPUStaticInst * decodeLda (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename MemDT , typename DestDT >
GPUStaticInst * decodeLd2 (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename MemDT >
GPUStaticInst * decodeLd (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename DataType , typename SrcDataType >
GPUStaticInst * decodeSt (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename DataType , typename AddrOperandType , int NumSrcOperands>
GPUStaticInst * constructAtomic (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename DataType , int NumSrcOperands>
GPUStaticInst * decodeAtomicHelper (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename DataType >
GPUStaticInst * decodeAtomic (const Brig::BrigInstBase *ib, const BrigObject *obj)
template<typename DataType >
GPUStaticInst * decodeAtomicNoRet (const Brig::BrigInstBase *ib, const BrigObject *obj)
static Addr calcPrivAddr (Addr addr, Wavefront *w, int lane, GPUStaticInst *i)
Typedef Documentation
B1
typedef HsailDataType<CRegOperandType, bool, Enums::M_U8, VT_32, 1> HsailISA::B1
Definition at line 76 of file decl.hh.
B16
typedef HsailDataType<SRegOperandType, uint16_t, Enums::M_U16, VT_32, 1> HsailISA::B16
Definition at line 80 of file decl.hh.
B32
typedef HsailDataType<SRegOperandType, uint32_t, Enums::M_U32, VT_32, 1> HsailISA::B32
Definition at line 83 of file decl.hh.
B64
typedef HsailDataType<DRegOperandType, uint64_t, Enums::M_U64, VT_64, 1> HsailISA::B64
Definition at line 86 of file decl.hh.
B8
typedef HsailDataType<SRegOperandType, uint8_t, Enums::M_U8, VT_32, 1> HsailISA::B8
Definition at line 77 of file decl.hh.
CRegOperandType
typedef HsailOperandType<CRegOperand, CRegOrImmOperand> HsailISA::CRegOperandType
Definition at line 57 of file decl.hh.
DRegOperandType
typedef HsailOperandType<DRegOperand, DRegOrImmOperand> HsailISA::DRegOperandType
Definition at line 59 of file decl.hh.
F32
typedef HsailDataType<SRegOperandType, float, Enums::M_F32, VT_32> HsailISA::F32
Definition at line 98 of file decl.hh.
F64
typedef HsailDataType<DRegOperandType, double, Enums::M_F64, VT_64> HsailISA::F64
Definition at line 99 of file decl.hh.
RawMachInst
typedef uint32_t HsailISA::RawMachInst
Definition at line 54 of file gpu_types.hh.
S16
typedef HsailDataType<SRegOperandType, int16_t, Enums::M_S16, VT_32> HsailISA::S16
Definition at line 89 of file decl.hh.
S32
typedef HsailDataType<SRegOperandType, int32_t, Enums::M_S32, VT_32> HsailISA::S32
Definition at line 90 of file decl.hh.
S64
typedef HsailDataType<DRegOperandType, int64_t, Enums::M_S64, VT_64> HsailISA::S64
Definition at line 91 of file decl.hh.
S8
typedef HsailDataType<SRegOperandType, int8_t, Enums::M_S8, VT_32> HsailISA::S8
Definition at line 88 of file decl.hh.
SRegOperandType
typedef HsailOperandType<SRegOperand, SRegOrImmOperand> HsailISA::SRegOperandType
Definition at line 58 of file decl.hh.
U16
typedef HsailDataType<SRegOperandType, uint16_t, Enums::M_U16, VT_32> HsailISA::U16
Definition at line 94 of file decl.hh.
U32
typedef HsailDataType<SRegOperandType, uint32_t, Enums::M_U32, VT_32> HsailISA::U32
Definition at line 95 of file decl.hh.
U64
typedef HsailDataType<DRegOperandType, uint64_t, Enums::M_U64, VT_64> HsailISA::U64
Definition at line 96 of file decl.hh.
U8
typedef HsailDataType<SRegOperandType, uint8_t, Enums::M_U8, VT_32> HsailISA::U8
Definition at line 93 of file decl.hh.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAGIC_PRINT_WF_32
MAGIC_PRINT_WF_64
MAGIC_PRINT_LANE
MAGIC_PRINT_LANE_64
MAGIC_PRINT_WF_FLOAT
MAGIC_SIM_BREAK
MAGIC_PREF_SUM
MAGIC_REDUCTION
MAGIC_MASKLANE_LOWER
MAGIC_MASKLANE_UPPER
MAGIC_JOIN_WF_BAR
MAGIC_WAIT_WF_BAR
MAGIC_PANIC
MAGIC_ATOMIC_NR_ADD_GLOBAL_U32_REG
MAGIC_ATOMIC_NR_ADD_GROUP_U32_REG
MAGIC_LOAD_GLOBAL_U32_REG
MAGIC_XACT_CAS_LD
MAGIC_MOST_SIG_THD
MAGIC_MOST_SIG_BROADCAST
MAGIC_PRINT_WFID_32
MAGIC_PRINT_WFID_64
Definition at line 54 of file pseudo_inst.cc.
Function Documentation
atomicOpToString()
const char * HsailISA::atomicOpToString (BrigAtomicOperation brigOp)
Definition at line 47 of file mem.cc.
References Brig::BRIG_ATOMIC_ADD, Brig::BRIG_ATOMIC_AND, Brig::BRIG_ATOMIC_CAS, Brig::BRIG_ATOMIC_EXCH, Brig::BRIG_ATOMIC_MAX, Brig::BRIG_ATOMIC_MIN, Brig::BRIG_ATOMIC_OR, Brig::BRIG_ATOMIC_SUB, Brig::BRIG_ATOMIC_WRAPDEC, Brig::BRIG_ATOMIC_WRAPINC, and Brig::BRIG_ATOMIC_XOR.
Referenced by HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), and HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::generateDisassembly().
calcPrivAddr()
static Addr HsailISA::calcPrivAddr (Addr addr, Wavefront * w, int lane, GPUStaticInst * i) static
Definition at line 123 of file mem_impl.hh.
References Wavefront::computeUnit, Wavefront::privBase, Wavefront::privSizePerItem, and ComputeUnit::wfSize().
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), and HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute().
cmpOpToString()
const char * HsailISA::cmpOpToString (Brig::BrigCompareOperation cmpOp)
Definition at line 63 of file main.cc.
References Brig::BRIG_COMPARE_EQ, Brig::BRIG_COMPARE_EQU, Brig::BRIG_COMPARE_GE, Brig::BRIG_COMPARE_GEU, Brig::BRIG_COMPARE_GT, Brig::BRIG_COMPARE_GTU, Brig::BRIG_COMPARE_LE, Brig::BRIG_COMPARE_LEU, Brig::BRIG_COMPARE_LT, Brig::BRIG_COMPARE_LTU, Brig::BRIG_COMPARE_NAN, Brig::BRIG_COMPARE_NE, Brig::BRIG_COMPARE_NEU, Brig::BRIG_COMPARE_NUM, Brig::BRIG_COMPARE_SEQ, Brig::BRIG_COMPARE_SEQU, Brig::BRIG_COMPARE_SGE, Brig::BRIG_COMPARE_SGEU, Brig::BRIG_COMPARE_SGT, Brig::BRIG_COMPARE_SGTU, Brig::BRIG_COMPARE_SLE, Brig::BRIG_COMPARE_SLEU, Brig::BRIG_COMPARE_SLT, Brig::BRIG_COMPARE_SLTU, Brig::BRIG_COMPARE_SNAN, Brig::BRIG_COMPARE_SNE, Brig::BRIG_COMPARE_SNEU, and Brig::BRIG_COMPARE_SNUM.
Referenced by firstbit(), and HsailISA::CmpInst< DestDataType, SrcDataType >::opcode_suffix().
compare()
template<typename T > bool HsailISA::compare (T src0, T src1, Brig::BrigCompareOperation cmpOp)
Definition at line 592 of file decl.hh.
References Brig::BRIG_COMPARE_EQ, Brig::BRIG_COMPARE_EQU, Brig::BRIG_COMPARE_GE, Brig::BRIG_COMPARE_GEU, Brig::BRIG_COMPARE_GT, Brig::BRIG_COMPARE_GTU, Brig::BRIG_COMPARE_LE, Brig::BRIG_COMPARE_LEU, Brig::BRIG_COMPARE_LT, Brig::BRIG_COMPARE_LTU, Brig::BRIG_COMPARE_NAN, Brig::BRIG_COMPARE_NE, Brig::BRIG_COMPARE_NEU, Brig::BRIG_COMPARE_NUM, Brig::BRIG_COMPARE_SEQ, Brig::BRIG_COMPARE_SEQU, Brig::BRIG_COMPARE_SGE, Brig::BRIG_COMPARE_SGEU, Brig::BRIG_COMPARE_SGT, Brig::BRIG_COMPARE_SGTU, Brig::BRIG_COMPARE_SLE, Brig::BRIG_COMPARE_SLEU, Brig::BRIG_COMPARE_SLT, Brig::BRIG_COMPARE_SLTU, Brig::BRIG_COMPARE_SNAN, Brig::BRIG_COMPARE_SNE, Brig::BRIG_COMPARE_SNEU, Brig::BRIG_COMPARE_SNUM, and fatal.
Referenced by ThreadContext::exit(), and MipsISA::Interrupts::onCpuTimerInterrupt().
constructAtomic()
template<typename DataType , typename AddrOperandType , int NumSrcOperands> GPUStaticInst* HsailISA::constructAtomic (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 1691 of file mem.hh.
References ArmISA::at, Brig::BrigInstAtomic::atomicOperation, Brig::BRIG_ATOMIC_LD, Brig::BRIG_ATOMIC_ST, Brig::BRIG_OPCODE_ATOMICNORET, Brig::BRIG_TYPE_B16, Brig::BRIG_TYPE_B32, Brig::BRIG_TYPE_B64, Brig::BRIG_TYPE_B8, fatal, Brig::BrigInstBase::opcode, and Brig::BrigInstBase::type.
Referenced by decodeAtomicHelper().
decodeAtomic()
template<typename DataType > GPUStaticInst* HsailISA::decodeAtomic (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 1753 of file mem.hh.
References ArmISA::at, Brig::BrigInstAtomic::atomicOperation, and Brig::BRIG_ATOMIC_CAS.
decodeAtomicHelper()
template<typename DataType , int NumSrcOperands> GPUStaticInst* HsailISA::decodeAtomicHelper (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 1721 of file mem.hh.
References Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_OPCODE_ATOMICNORET, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, constructAtomic(), fatal, findRegDataType(), BrigObject::getOperandPtr(), BrigRegOperandInfo::kind, Brig::BrigInstBase::opcode, Brig::BrigInstBase::operands, BrigRegOperandInfo::regKind, and BrigRegOperandInfo::type.
decodeAtomicNoRet()
template<typename DataType > GPUStaticInst* HsailISA::decodeAtomicNoRet (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 1766 of file mem.hh.
References ArmISA::at, Brig::BrigInstAtomic::atomicOperation, and Brig::BRIG_ATOMIC_CAS.
decodeBr()
GPUStaticInst * HsailISA::decodeBr (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 73 of file branch.cc.
References Brig::BRIG_KIND_OPERAND_REGISTER, BrigObject::getOperand(), BrigObject::getOperandPtr(), Brig::BrigBase::kind, Brig::BrigInstBase::operands, and X86ISA::reg.
Referenced by HsailISA::BrIndirectInst::numDstRegOperands().
decodeBrn()
GPUStaticInst * HsailISA::decodeBrn (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 43 of file branch.cc.
References Brig::BRIG_KIND_OPERAND_REGISTER, BrigObject::getOperand(), BrigObject::getOperandPtr(), Brig::BrigBase::kind, Brig::BrigInstBase::operands, and X86ISA::reg.
Referenced by HsailISA::BrnIndirectInst::numDstRegOperands().
decodeCbr()
GPUStaticInst * HsailISA::decodeCbr (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 58 of file branch.cc.
References Brig::BRIG_KIND_OPERAND_REGISTER, BrigObject::getOperand(), BrigObject::getOperandPtr(), Brig::BrigBase::kind, Brig::BrigInstBase::operands, and X86ISA::reg.
Referenced by HsailISA::CbrIndirectInst::numDstRegOperands().
decodeLd()
template<typename MemDT > GPUStaticInst* HsailISA::decodeLd (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 729 of file mem.hh.
References Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, Brig::BRIG_TYPE_B16, Brig::BRIG_TYPE_B32, Brig::BRIG_TYPE_B64, Brig::BRIG_TYPE_B8, Brig::BRIG_TYPE_F16, Brig::BRIG_TYPE_F32, Brig::BRIG_TYPE_F64, Brig::BRIG_TYPE_S16, Brig::BRIG_TYPE_S32, Brig::BRIG_TYPE_S64, Brig::BRIG_TYPE_S8, Brig::BRIG_TYPE_U16, Brig::BRIG_TYPE_U32, Brig::BRIG_TYPE_U64, Brig::BRIG_TYPE_U8, fatal, findRegDataType(), BrigObject::getOperandPtr(), BrigRegOperandInfo::kind, Brig::BrigInstBase::operands, BrigRegOperandInfo::regKind, and Brig::BrigInstBase::type.
decodeLd2()
template<typename MemDT , typename DestDT > GPUStaticInst* HsailISA::decodeLd2 (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 703 of file mem.hh.
References Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, fatal, findRegDataType(), BrigObject::getOperandPtr(), BrigRegOperandInfo::kind, Brig::BrigInstBase::operands, and BrigRegOperandInfo::regKind.
decodeLda()
template<typename DataType > GPUStaticInst* HsailISA::decodeLda (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 185 of file mem.hh.
References Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, fatal, findRegDataType(), BrigObject::getOperandPtr(), BrigRegOperandInfo::kind, Brig::BrigInstBase::operands, BrigRegOperandInfo::regKind, and BrigRegOperandInfo::type.
decodeSt()
template<typename DataType , typename SrcDataType > GPUStaticInst* HsailISA::decodeSt (const Brig::BrigInstBase * ib, const BrigObject * obj)
Definition at line 1178 of file mem.hh.
References Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_OPCODE_ATOMIC, Brig::BRIG_OPCODE_ATOMICNORET, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, fatal, findRegDataType(), BrigObject::getOperandPtr(), BrigRegOperandInfo::kind, Brig::BrigInstBase::opcode, Brig::BrigInstBase::operands, BrigRegOperandInfo::regKind, and BrigRegOperandInfo::type.
firstbit()
template<typename T > int32_t HsailISA::firstbit (T src0)
Definition at line 648 of file decl.hh.
References cmpOpToString().
fpclassify()
template<typename T > bool HsailISA::fpclassify (T src0, uint32_t src1)
Definition at line 537 of file decl.hh.
Referenced by ArmISA::fixDest(), ArmISA::flushToZero(), ArmISA::fpMulX(), ArmISA::fpRecipEstimate(), ArmISA::fpRecps(), ArmISA::fpRecpsS(), ArmISA::fprSqrtEstimate(), ArmISA::fpRSqrts(), ArmISA::fpRSqrtsS(), ArmISA::FpOp::ternaryOp(), and ArmISA::vfpFpToFixed().
heynot()
template<typename T > T HsailISA::heynot (T arg)
Definition at line 1273 of file decl.hh.
heynot< bool >()
template<> bool HsailISA::heynot< bool > (bool arg) inline
Definition at line 1274 of file decl.hh.
References HsailISA::HsailDataType< _OperandType, _CType, _memType, _vgprType, IsBits >::label.