gem5: cp Namespace Reference
cp Namespace Reference
Classes
struct Format
struct Print
Functions
template<typename T >
void _format_char (std::ostream &out, const T &data, Format &fmt)
template<typename T >
void _format_integer (std::ostream &out, const T &data, Format &fmt)
template<typename T >
void _format_float (std::ostream &out, const T &data, Format &fmt)
template<typename T >
void _format_string (std::ostream &out, const T &data, Format &fmt)
template<typename T >
void format_char (std::ostream &out, const T &data, Format &fmt)
void format_char (std::ostream &out, char data, Format &fmt)
void format_char (std::ostream &out, unsigned char data, Format &fmt)
void format_char (std::ostream &out, signed char data, Format &fmt)
void format_char (std::ostream &out, short data, Format &fmt)
void format_char (std::ostream &out, unsigned short data, Format &fmt)
void format_char (std::ostream &out, int data, Format &fmt)
void format_char (std::ostream &out, unsigned int data, Format &fmt)
void format_char (std::ostream &out, long data, Format &fmt)
void format_char (std::ostream &out, unsigned long data, Format &fmt)
void format_char (std::ostream &out, long long data, Format &fmt)
void format_char (std::ostream &out, unsigned long long data, Format &fmt)
template<typename T >
void format_integer (std::ostream &out, const T &data, Format &fmt)
void format_integer (std::ostream &out, char data, Format &fmt)
void format_integer (std::ostream &out, unsigned char data, Format &fmt)
void format_integer (std::ostream &out, signed char data, Format &fmt)
void format_integer (std::ostream &out, const unsigned char *data, Format &fmt)
void format_integer (std::ostream &out, const signed char *data, Format &fmt)
template<typename T >
void format_float (std::ostream &out, const T &data, Format &fmt)
void format_float (std::ostream &out, float data, Format &fmt)
void format_float (std::ostream &out, double data, Format &fmt)
template<typename T >
void format_string (std::ostream &out, const T &data, Format &fmt)
Function Documentation
_format_char()
template<typename T > void cp::_format_char (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 78 of file cprintf_formats.hh.
References data.
Referenced by format_char().
_format_float()
template<typename T > void cp::_format_float (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 148 of file cprintf_formats.hh.
References data, cp::Format::fill_zero, cp::Format::fixed, cp::Format::float_format, cp::Format::precision, cp::Format::scientific, cp::Format::uppercase, and cp::Format::width.
Referenced by format_float().
_format_integer()
template<typename T > void cp::_format_integer (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 87 of file cprintf_formats.hh.
References cp::Format::alternate_form, cp::Format::base, data, cp::Format::dec, cp::Format::fill_zero, cp::Format::flush_left, cp::Format::hex, cp::Format::oct, cp::Format::print_sign, cp::Format::uppercase, and cp::Format::width.
Referenced by format_integer().
_format_string()
template<typename T > void cp::_format_string (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 207 of file cprintf_formats.hh.
References data, cp::Format::flush_left, and cp::Format::width.
Referenced by format_string().
format_char() [1/12]
template<typename T > void cp::format_char (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 252 of file cprintf_formats.hh.
Referenced by cp::Print::add_arg().
format_char() [2/12]
void cp::format_char (std::ostream & out, char data, Format & fmt) inline
Definition at line 256 of file cprintf_formats.hh.
References _format_char().
format_char() [3/12]
void cp::format_char (std::ostream & out, unsigned char data, Format & fmt) inline
Definition at line 260 of file cprintf_formats.hh.
References _format_char().
format_char() [4/12]
void cp::format_char (std::ostream & out, signed char data, Format & fmt) inline
Definition at line 264 of file cprintf_formats.hh.
References _format_char().
format_char() [5/12]
void cp::format_char (std::ostream & out, short data, Format & fmt) inline
Definition at line 268 of file cprintf_formats.hh.
References _format_char().
format_char() [6/12]
void cp::format_char (std::ostream & out, unsigned short data, Format & fmt) inline
Definition at line 272 of file cprintf_formats.hh.
References _format_char().
format_char() [7/12]
void cp::format_char (std::ostream & out, int data, Format & fmt) inline
Definition at line 276 of file cprintf_formats.hh.
References _format_char().
format_char() [8/12]
void cp::format_char (std::ostream & out, unsigned int data, Format & fmt) inline
Definition at line 280 of file cprintf_formats.hh.
References _format_char().
format_char() [9/12]
void cp::format_char (std::ostream & out, long data, Format & fmt) inline
Definition at line 284 of file cprintf_formats.hh.
References _format_char().
format_char() [10/12]
void cp::format_char (std::ostream & out, unsigned long data, Format & fmt) inline
Definition at line 288 of file cprintf_formats.hh.
References _format_char().
format_char() [11/12]
void cp::format_char (std::ostream & out, long long data, Format & fmt) inline
Definition at line 292 of file cprintf_formats.hh.
References _format_char().
format_char() [12/12]
void cp::format_char (std::ostream & out, unsigned long long data, Format & fmt) inline
Definition at line 296 of file cprintf_formats.hh.
References _format_char().
format_float() [1/3]
template<typename T > void cp::format_float (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 327 of file cprintf_formats.hh.
Referenced by cp::Print::add_arg().
format_float() [2/3]
void cp::format_float (std::ostream & out, float data, Format & fmt) inline
Definition at line 331 of file cprintf_formats.hh.
References _format_float().
format_float() [3/3]
void cp::format_float (std::ostream & out, double data, Format & fmt) inline
Definition at line 335 of file cprintf_formats.hh.
References _format_float().
format_integer() [1/6]
template<typename T > void cp::format_integer (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 304 of file cprintf_formats.hh.
References _format_integer().
Referenced by cp::Print::add_arg().
format_integer() [2/6]
void cp::format_integer (std::ostream & out, char data, Format & fmt) inline
Definition at line 307 of file cprintf_formats.hh.
References _format_integer().
format_integer() [3/6]
void cp::format_integer (std::ostream & out, unsigned char data, Format & fmt) inline
Definition at line 310 of file cprintf_formats.hh.
References _format_integer().
format_integer() [4/6]
void cp::format_integer (std::ostream & out, signed char data, Format & fmt) inline
Definition at line 313 of file cprintf_formats.hh.
References _format_integer().
format_integer() [5/6]
void cp::format_integer (std::ostream & out, const unsigned char * data, Format & fmt) inline
Definition at line 316 of file cprintf_formats.hh.
References _format_integer().
format_integer() [6/6]
void cp::format_integer (std::ostream & out, const signed char * data, Format & fmt) inline
Definition at line 319 of file cprintf_formats.hh.
References _format_integer().
format_string()
template<typename T > void cp::format_string (std::ostream & out, const T & data, Format & fmt) inline
Definition at line 343 of file cprintf_formats.hh.
References _format_string().
Referenced by cp::Print::add_arg().