gem5: tlm Namespace Reference
tlm Namespace Reference
Classes
class circular_buffer
class tlm_analysis_fifo
class tlm_analysis_if
class tlm_analysis_port
struct tlm_analysis_triple
class tlm_array
class tlm_base_initiator_socket
class tlm_base_initiator_socket_b
struct tlm_base_protocol_types
class tlm_base_socket_if
class tlm_base_target_socket
class tlm_base_target_socket_b
class tlm_blocking_get_if
class tlm_blocking_get_peek_if
class tlm_blocking_master_if
class tlm_blocking_peek_if
class tlm_blocking_put_if
class tlm_blocking_slave_if
class tlm_blocking_transport_if
class tlm_bool
class tlm_bw_direct_mem_if
class tlm_bw_nonblocking_transport_if
class tlm_bw_transport_if
class tlm_delayed_analysis_if
class tlm_delayed_write_if
class tlm_dmi
class tlm_endian_context
class tlm_endian_context_pool
class tlm_event_finder_t
class tlm_extension
class tlm_extension_base
class tlm_fifo
class tlm_fifo_config_size_if
class tlm_fifo_debug_if
class tlm_fifo_get_if
class tlm_fifo_put_if
class tlm_fw_direct_mem_if
class tlm_fw_nonblocking_transport_if
class tlm_fw_transport_if
class tlm_generic_payload
class tlm_get_if
class tlm_get_peek_if
class tlm_global_quantum
class tlm_initiator_socket
class tlm_master_if
class tlm_master_imp
class tlm_mm_interface
class tlm_nonblocking_get_if
class tlm_nonblocking_get_peek_if
class tlm_nonblocking_get_port
class tlm_nonblocking_master_if
class tlm_nonblocking_peek_if
class tlm_nonblocking_peek_port
class tlm_nonblocking_put_if
class tlm_nonblocking_put_port
class tlm_nonblocking_slave_if
class tlm_peek_if
class tlm_phase
class tlm_put_get_imp
class tlm_put_if
class tlm_req_rsp_channel
class tlm_slave_if
class tlm_slave_imp
class tlm_slave_to_transport
class tlm_tag
class tlm_target_socket
class tlm_transport_channel
class tlm_transport_dbg_if
class tlm_transport_if
class tlm_transport_to_master
class tlm_write_if
Enumerations
enum tlm_command { TLM_READ_COMMAND, TLM_WRITE_COMMAND, TLM_IGNORE_COMMAND }
enum tlm_response_status {
TLM_OK_RESPONSE = 1, TLM_INCOMPLETE_RESPONSE = 0, TLM_GENERIC_ERROR_RESPONSE = -1, TLM_ADDRESS_ERROR_RESPONSE = -2,
TLM_COMMAND_ERROR_RESPONSE = -3, TLM_BURST_ERROR_RESPONSE = -4, TLM_BYTE_ENABLE_ERROR_RESPONSE = -5
}
enum tlm_gp_option { TLM_MIN_PAYLOAD, TLM_FULL_PAYLOAD, TLM_FULL_PAYLOAD_ACCEPTED }
enum tlm_endianness { TLM_UNKNOWN_ENDIAN, TLM_LITTLE_ENDIAN, TLM_BIG_ENDIAN }
enum tlm_phase_enum {
UNINITIALIZED_PHASE = 0, BEGIN_REQ = 1, END_REQ, BEGIN_RESP,
END_RESP
}
enum tlm_sync_enum { TLM_ACCEPTED, TLM_UPDATED, TLM_COMPLETED }
enum tlm_socket_category {
TLM_UNKNOWN_SOCKET = 0, TLM_INITIATOR_SOCKET = 0x1, TLM_TARGET_SOCKET = 0x2, TLM_MULTI_SOCKET = 0x10,
TLM_MULTI_INITIATOR_SOCKET = TLM_INITIATOR_SOCKET | TLM_MULTI_SOCKET, TLM_MULTI_TARGET_SOCKET = TLM_TARGET_SOCKET | TLM_MULTI_SOCKET
}
Functions
tlm_endian_context * establish_context (tlm_generic_payload *txn)
void copy_db0 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
void copy_dbtrue0 (unsigned char *src1, unsigned char *, unsigned char *dest1, unsigned char *dest2)
void copy_btrue0 (unsigned char *, unsigned char *, unsigned char *, unsigned char *dest2)
void copy_b0 (unsigned char *, unsigned char *src2, unsigned char *, unsigned char *dest2)
void copy_dbyb0 (unsigned char *src1, unsigned char *, unsigned char *dest1, unsigned char *dest2)
template<class D , void COPY>
void loop_generic0 (int new_len, int new_stream_width, int orig_stream_width, int sizeof_databus, sc_dt::uint64 orig_start_address, sc_dt::uint64 new_start_address, int be_length, unsigned char *ie_data, unsigned char *ie_be, unsigned char *he_data, unsigned char *he_be)
template<class DATAWORD >
void tlm_from_hostendian_generic (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class DATAWORD >
void tlm_to_hostendian_generic (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class D >
void copy_d1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void copy_db1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void true_b1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void copy_b1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void copy_dbyb1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void copy_dbytrue1 (unsigned char *src1, unsigned char *src2, unsigned char *dest1, unsigned char *dest2)
template<class D >
void false_b1 (unsigned char *dest1)
template<class D >
void no_b1 (unsigned char *dest1)
template<class D , void COPY, void COPYuchar, void FILLFALSE, void FILLFALSEuchar>
int loop_word1 (int bytes_left, int len0, int lenN, int sizeof_databus, unsigned char *start, unsigned char *end, unsigned char *src, unsigned char *bsrc, unsigned char *dest, unsigned char *bdest)
template<class DATAWORD >
void tlm_from_hostendian_word (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class DATAWORD >
void tlm_to_hostendian_word (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class D >
void copy_d2 (D *src1, D *src2, D *dest1, D *dest2)
template<class D >
void copy_db2 (D *src1, D *src2, D *dest1, D *dest2)
template<class D >
void copy_dbyb2 (D *src1, D *src2, D *dest1, D *dest2)
template<class D , void COPY>
void loop_aligned2 (D *src1, D *src2, D *dest1, D *dest2, int words, int words_per_bus)
template<class DATAWORD >
void tlm_from_hostendian_aligned (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class DATAWORD >
void tlm_to_hostendian_aligned (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class DATAWORD >
void tlm_from_hostendian_single (tlm_generic_payload *txn, unsigned int sizeof_databus)
template<class DATAWORD >
void tlm_to_hostendian_single (tlm_generic_payload *txn, unsigned int sizeof_databus)
void tlm_from_hostendian (tlm_generic_payload *txn)
unsigned int max_num_extensions ()
tlm_endianness get_host_endianness ()
bool host_has_little_endianness ()
bool has_host_endianness (tlm_endianness endianness)
std::ostream & operator<< (std::ostream &s, const tlm_phase &p)
const unsigned int tlm_version_major (TLM_VERSION_MAJOR)
const unsigned int tlm_version_minor (TLM_VERSION_MINOR)
const unsigned int tlm_version_patch (TLM_VERSION_PATCH)
const bool tlm_is_prerelease (TLM_IS_PRERELEASE)
const std::string tlm_version_string (TLM_VERSION_STRING)
const std::string tlm_version_originator (TLM_VERSION_ORIGINATOR)
const std::string tlm_version_prerelease (TLM_VERSION_PRERELEASE)
const std::string tlm_version_release_date (TLM_VERSION_STRING_RELEASE_DATE)
const std::string tlm_copyright_string (TLM_COPYRIGHT)
const std::string tlm_version_string_2 (TLM_VERSION_STRING_2)
const char * tlm_release ()
const char * tlm_version ()
const char * tlm_copyright ()
Variables
static tlm_endian_context_pool global_tlm_endian_context_pool
Enumeration Type Documentation
tlm_command
enum tlm::tlm_command
Enumerator
TLM_READ_COMMAND
TLM_WRITE_COMMAND
TLM_IGNORE_COMMAND
Definition at line 82 of file gp.hh.
tlm_endianness
enum tlm::tlm_endianness
Enumerator
TLM_UNKNOWN_ENDIAN
TLM_LITTLE_ENDIAN
TLM_BIG_ENDIAN
Definition at line 26 of file helpers.hh.
tlm_gp_option
enum tlm::tlm_gp_option
Enumerator
TLM_MIN_PAYLOAD
TLM_FULL_PAYLOAD
TLM_FULL_PAYLOAD_ACCEPTED
Definition at line 100 of file gp.hh.
tlm_phase_enum
enum tlm::tlm_phase_enum
Enumerator
UNINITIALIZED_PHASE
BEGIN_REQ
END_REQ
BEGIN_RESP
END_RESP
Definition at line 38 of file phase.hh.
tlm_response_status
enum tlm::tlm_response_status
Enumerator
TLM_OK_RESPONSE
TLM_INCOMPLETE_RESPONSE
TLM_GENERIC_ERROR_RESPONSE
TLM_ADDRESS_ERROR_RESPONSE
TLM_COMMAND_ERROR_RESPONSE
TLM_BURST_ERROR_RESPONSE
TLM_BYTE_ENABLE_ERROR_RESPONSE
Definition at line 89 of file gp.hh.
tlm_socket_category
enum tlm::tlm_socket_category
Enumerator
TLM_UNKNOWN_SOCKET
TLM_INITIATOR_SOCKET
TLM_TARGET_SOCKET
TLM_MULTI_SOCKET
TLM_MULTI_INITIATOR_SOCKET
TLM_MULTI_TARGET_SOCKET
Definition at line 31 of file base_socket_if.hh.
tlm_sync_enum
enum tlm::tlm_sync_enum
Enumerator
TLM_ACCEPTED
TLM_UPDATED
TLM_COMPLETED
Definition at line 31 of file fw_bw_ifs.hh.
Function Documentation
copy_b0()
void tlm::copy_b0 (unsigned char * , unsigned char * src2, unsigned char * , unsigned char * dest2) inline
Definition at line 330 of file endian_conv.hh.
copy_b1()
template<class D > void tlm::copy_b1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 504 of file endian_conv.hh.
copy_btrue0()
void tlm::copy_btrue0 (unsigned char * , unsigned char * , unsigned char * , unsigned char * dest2) inline
Definition at line 323 of file endian_conv.hh.
References TLM_BYTE_ENABLED.
copy_d1()
template<class D > void tlm::copy_d1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 478 of file endian_conv.hh.
copy_d2()
template<class D > void tlm::copy_d2 (D * src1, D * src2, D * dest1, D * dest2) inline
Definition at line 751 of file endian_conv.hh.
copy_db0()
void tlm::copy_db0 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 307 of file endian_conv.hh.
copy_db1()
template<class D > void tlm::copy_db1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 487 of file endian_conv.hh.
copy_db2()
template<class D > void tlm::copy_db2 (D * src1, D * src2, D * dest1, D * dest2) inline
Definition at line 755 of file endian_conv.hh.
copy_dbtrue0()
void tlm::copy_dbtrue0 (unsigned char * src1, unsigned char * , unsigned char * dest1, unsigned char * dest2) inline
Definition at line 315 of file endian_conv.hh.
References TLM_BYTE_ENABLED.
copy_dbyb0()
void tlm::copy_dbyb0 (unsigned char * src1, unsigned char * , unsigned char * dest1, unsigned char * dest2) inline
Definition at line 337 of file endian_conv.hh.
References TLM_BYTE_ENABLED.
copy_dbyb1()
template<class D > void tlm::copy_dbyb1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 512 of file endian_conv.hh.
References TLM_BYTE_DISABLED.
copy_dbyb2()
template<class D > void tlm::copy_dbyb2 (D * src1, D * src2, D * dest1, D * dest2) inline
Definition at line 763 of file endian_conv.hh.
copy_dbytrue1()
template<class D > void tlm::copy_dbytrue1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 521 of file endian_conv.hh.
establish_context()
tlm_endian_context* tlm::establish_context (tlm_generic_payload * txn) inline
Definition at line 236 of file endian_conv.hh.
References tlm::tlm_generic_payload::get_extension(), tlm::tlm_endian_context_pool::pop(), and tlm::tlm_generic_payload::set_extension().
Referenced by tlm_to_hostendian_aligned(), tlm_to_hostendian_generic(), tlm_to_hostendian_single(), and tlm_to_hostendian_word().
false_b1()
template<class D > void tlm::false_b1 (unsigned char * dest1) inline
Definition at line 529 of file endian_conv.hh.
get_host_endianness()
tlm_endianness tlm::get_host_endianness () inline
Definition at line 29 of file helpers.hh.
References TLM_LITTLE_ENDIAN, and TLM_UNKNOWN_ENDIAN.
has_host_endianness()
bool tlm::has_host_endianness (tlm_endianness endianness) inline
Definition at line 59 of file helpers.hh.
References host_has_little_endianness(), TLM_BIG_ENDIAN, and TLM_LITTLE_ENDIAN.
host_has_little_endianness()
bool tlm::host_has_little_endianness () inline
Definition at line 43 of file helpers.hh.
References TLM_UNKNOWN_ENDIAN.
Referenced by SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), and has_host_endianness().
loop_aligned2()
template<class D , void COPY> void tlm::loop_aligned2 (D * src1, D * src2, D * dest1, D * dest2, int words, int words_per_bus) inline
Definition at line 771 of file endian_conv.hh.
loop_generic0()
template<class D , void COPY> void tlm::loop_generic0 (int new_len, int new_stream_width, int orig_stream_width, int sizeof_databus, sc_dt::uint64 orig_start_address, sc_dt::uint64 new_start_address, int be_length, unsigned char * ie_data, unsigned char * ie_be, unsigned char * he_data, unsigned char * he_be) inline
Definition at line 349 of file endian_conv.hh.
loop_word1()
template<class D , void COPY, void COPYuchar, void FILLFALSE, void FILLFALSEuchar> int tlm::loop_word1 (int bytes_left, int len0, int lenN, int sizeof_databus, unsigned char * start, unsigned char * end, unsigned char * src, unsigned char * bsrc, unsigned char * dest, unsigned char * bdest) inline
Definition at line 547 of file endian_conv.hh.
References ArmISA::i, and X86ISA::len0.
Referenced by tlm_to_hostendian_word().
max_num_extensions()
unsigned int tlm::max_num_extensions ()
Definition at line 85 of file gp.cc.
Referenced by tlm_utils::instance_specific_extensions_per_accessor::resize_extensions(), tlm::tlm_generic_payload::resize_extensions(), and tlm::tlm_mm_interface::~tlm_mm_interface().
no_b1()
template<class D > void tlm::no_b1 (unsigned char * dest1) inline
Definition at line 536 of file endian_conv.hh.
operator<<()
std::ostream& tlm::operator<< (std::ostream & s, const tlm_phase & p) inline
Definition at line 79 of file phase.hh.
References tlm::tlm_phase::get_name(), and ArmISA::s.
tlm_copyright()
const char* tlm::tlm_copyright () inline
Definition at line 151 of file version.hh.
References tlm_copyright_string().
tlm_copyright_string()
const std::string tlm::tlm_copyright_string (TLM_COPYRIGHT)
Referenced by tlm_copyright().
tlm_from_hostendian()
void tlm::tlm_from_hostendian (tlm_generic_payload * txn) inline
Definition at line 933 of file endian_conv.hh.
References tlm::tlm_endian_context::from_f, tlm::tlm_generic_payload::get_extension(), and tlm::tlm_endian_context::sizeof_databus.
tlm_from_hostendian_aligned()
template<class DATAWORD > void tlm::tlm_from_hostendian_aligned (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 803 of file endian_conv.hh.
References tlm::tlm_endian_context::data_ptr, tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), and tlm::tlm_generic_payload::is_read().
tlm_from_hostendian_generic()
template<class DATAWORD > void tlm::tlm_from_hostendian_generic (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 381 of file endian_conv.hh.
References tlm::tlm_endian_context::address, tlm::tlm_endian_context::data_ptr, tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), tlm::tlm_generic_payload::get_streaming_width(), tlm::tlm_generic_payload::is_read(), tlm::tlm_endian_context::new_address, and tlm::tlm_endian_context::stream_width.
tlm_from_hostendian_single()
template<class DATAWORD > void tlm::tlm_from_hostendian_single (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 902 of file endian_conv.hh.
tlm_from_hostendian_word()
template<class DATAWORD > void tlm::tlm_from_hostendian_word (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 618 of file endian_conv.hh.
References tlm::tlm_endian_context::address, tlm::tlm_endian_context::byte_enable, ArmISA::d, tlm::tlm_endian_context::data_ptr, tlm::tlm_generic_payload::get_data_ptr(), tlm::tlm_generic_payload::is_read(), X86ISA::len0, and tlm::tlm_endian_context::length.
tlm_is_prerelease()
const bool tlm::tlm_is_prerelease (TLM_IS_PRERELEASE)
tlm_release()
const char* tlm::tlm_release () inline
Definition at line 149 of file version.hh.
References tlm_version_string().
tlm_to_hostendian_aligned()
template<class DATAWORD > void tlm::tlm_to_hostendian_aligned (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 839 of file endian_conv.hh.
References tlm::tlm_endian_context::data_ptr, tlm::tlm_endian_context::establish_bebuf(), establish_context(), tlm::tlm_endian_context::establish_dbuf(), tlm::tlm_endian_context::from_f, tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), tlm::tlm_generic_payload::is_write(), tlm::tlm_endian_context::new_bebuf, tlm::tlm_endian_context::new_dbuf, tlm::tlm_generic_payload::set_byte_enable_length(), tlm::tlm_generic_payload::set_byte_enable_ptr(), tlm::tlm_generic_payload::set_data_ptr(), and tlm::tlm_endian_context::sizeof_databus.
tlm_to_hostendian_generic()
template<class DATAWORD > void tlm::tlm_to_hostendian_generic (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 400 of file endian_conv.hh.
References tlm::tlm_endian_context::address, tlm::tlm_endian_context::data_ptr, tlm::tlm_endian_context::establish_bebuf(), establish_context(), tlm::tlm_endian_context::establish_dbuf(), tlm::tlm_endian_context::from_f, tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_byte_enable_length(), tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), tlm::tlm_generic_payload::get_streaming_width(), tlm::tlm_generic_payload::is_write(), length, tlm::tlm_endian_context::new_address, tlm::tlm_endian_context::new_bebuf, tlm::tlm_endian_context::new_dbuf, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_byte_enable_length(), tlm::tlm_generic_payload::set_byte_enable_ptr(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), tlm::tlm_generic_payload::set_streaming_width(), tlm::tlm_endian_context::sizeof_databus, tlm::tlm_endian_context::stream_width, and TLM_BYTE_DISABLED.
tlm_to_hostendian_single()
template<class DATAWORD > void tlm::tlm_to_hostendian_single (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 913 of file endian_conv.hh.
References ArmISA::a, establish_context(), tlm::tlm_endian_context::from_f, tlm::tlm_generic_payload::get_address(), ArmISA::mask, tlm::tlm_generic_payload::set_address(), and tlm::tlm_endian_context::sizeof_databus.
tlm_to_hostendian_word()
template<class DATAWORD > void tlm::tlm_to_hostendian_word (tlm_generic_payload * txn, unsigned int sizeof_databus) inline
Definition at line 661 of file endian_conv.hh.
References tlm::tlm_endian_context::address, tlm::tlm_endian_context::byte_enable, ArmISA::d, tlm::tlm_endian_context::data_ptr, tlm::tlm_endian_context::establish_bebuf(), establish_context(), tlm::tlm_endian_context::establish_dbuf(), tlm::tlm_endian_context::from_f, tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_byte_enable_ptr(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), tlm::tlm_generic_payload::is_read(), X86ISA::len0, tlm::tlm_endian_context::length, loop_word1(), tlm::tlm_endian_context::new_bebuf, tlm::tlm_endian_context::new_dbuf, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_byte_enable_length(), tlm::tlm_generic_payload::set_byte_enable_ptr(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), tlm::tlm_generic_payload::set_streaming_width(), and tlm::tlm_endian_context::sizeof_databus.
tlm_version()
const char* tlm::tlm_version () inline
Definition at line 150 of file version.hh.
References tlm_version_string_2().
tlm_version_major()
const unsigned int tlm::tlm_version_major (TLM_VERSION_MAJOR)
tlm_version_minor()
const unsigned int tlm::tlm_version_minor (TLM_VERSION_MINOR)
tlm_version_originator()
const std::string tlm::tlm_version_originator (TLM_VERSION_ORIGINATOR)
tlm_version_patch()
const unsigned int tlm::tlm_version_patch (TLM_VERSION_PATCH)
tlm_version_prerelease()
const std::string tlm::tlm_version_prerelease (TLM_VERSION_PRERELEASE)
tlm_version_release_date()
const std::string tlm::tlm_version_release_date (TLM_VERSION_STRING_RELEASE_DATE)
tlm_version_string()
const std::string tlm::tlm_version_string (TLM_VERSION_STRING)
Referenced by tlm_release().
tlm_version_string_2()
const std::string tlm::tlm_version_string_2 (TLM_VERSION_STRING_2)
Referenced by tlm_version().
true_b1()
template<class D > void tlm::true_b1 (unsigned char * src1, unsigned char * src2, unsigned char * dest1, unsigned char * dest2) inline
Definition at line 496 of file endian_conv.hh.
Variable Documentation
global_tlm_endian_context_pool
tlm_endian_context_pool tlm::global_tlm_endian_context_pool static
Definition at line 159 of file endian_conv.hh.