gem5: m5::stl_helpers Namespace Reference
m5::stl_helpers Namespace Reference
Classes
class ContainerPrint
Functions
template<typename T >
void deletePointer (T &ptr)
template<template< typename T, typename A > class C, typename T , typename A >
void deletePointers (C< T, A > &container)
template<template< typename T, typename A > class C, typename T , typename A >
std::ostream & operator<< (std::ostream &out, const C< T, A > &vec)
Function Documentation
deletePointer()
template<typename T > void m5::stl_helpers::deletePointer (T & ptr)
Definition at line 42 of file stl_helpers.hh.
deletePointers()
template<template< typename T, typename A > class C, typename T , typename A > void m5::stl_helpers::deletePointers (C< T, A > & container)
Definition at line 77 of file stl_helpers.hh.
Referenced by CrossbarSwitch::~CrossbarSwitch(), GarnetNetwork::~GarnetNetwork(), InputUnit::~InputUnit(), NetworkInterface::~NetworkInterface(), OutputUnit::~OutputUnit(), Router::~Router(), SimpleNetwork::~SimpleNetwork(), and Switch::~Switch().
operator<<()
template<template< typename T, typename A > class C, typename T , typename A > std::ostream& m5::stl_helpers::operator<< (std::ostream & out, const C< T, A > & vec)
Definition at line 86 of file stl_helpers.hh.
References m5::stl_helpers::ContainerPrint< T >::out.