gem5: Trace Namespace Reference
Trace Namespace Reference
Classes
class ArmNativeTrace
class ExeTracer
class ExeTracerRecord
class InstPBTrace
class InstPBTraceRecord
This in an instruction tracer that records the flow of instructions through multiple cpus and systems to a protobuf file specified by proto/inst.proto for further analysis.
class InstRecord
class InstTracer
class IntelTrace
class IntelTraceRecord
class Logger
Debug logging base class.
class NativeTrace
class NativeTraceRecord
class OstreamLogger
Logging wrapper for ostreams with the format: <when>: <name>: <message-body>
class SparcNativeTrace
class TarmacBaseRecord
class TarmacContext
This object type is encapsulating the informations needed by a Tarmac record to generate it's own entries.
class TarmacParser
Tarmac Parser: this tracer parses an existing Tarmac trace and it diffs it with gem5 simulation status, comparing results and reporting architectural mismatches if any.
class TarmacParserRecord
class TarmacTracer
Tarmac Tracer: this tracer generates a new Tarmac Record for every instruction being executed in gem5.
class TarmacTracerRecord
TarmacTracer Record: Record generated by the TarmacTracer for every executed instruction.
class TarmacTracerRecordV8
TarmacTracer record for ARMv8 CPUs: The record is adding some data to the base TarmacTracer record.
class X86NativeTrace
Functions
std::string iSetStateToStr (TarmacBaseRecord::ISetState isetstate)
Returns the string representation of the instruction set being currently run according to the Tarmac format.
std::string opModeToStr (ArmISA::OperatingMode opMode)
Returns the string representation of the ARM Operating Mode (CPSR.M[3:0] field) according to the Tarmac format.
Logger * getDebugLogger ()
Get the current global debug logger.
std::ostream & output ()
Get the ostream from the current global logger.
void setDebugLogger (Logger *logger)
Delete the current global logger and assign a new one.
void enable ()
Enable/disable debug logging.
void disable ()
Variables
static const char * intRegNames [SparcISA::NumIntArchRegs]
Logger * debug_logger = NULL
ObjectMatch ignore
Function Documentation
disable()
void Trace::disable ()
Definition at line 97 of file trace.cc.
References Debug::SimpleFlag::disableAll().
Referenced by ArmISA::PMU::PMUEvent::detachEvent(), sc_gem5::Process::disabled(), Trace::OstreamLogger::getOstream(), sc_core::sc_process_handle::operator=(), pybind_init_debug(), Gicv3Redistributor::write(), and Gicv3Distributor::write().
enable()
void Trace::enable ()
Enable/disable debug logging.
Definition at line 91 of file trace.cc.
References Debug::SimpleFlag::enableAll().
Referenced by Trace::OstreamLogger::getOstream(), and pybind_init_debug().
getDebugLogger()
Logger * Trace::getDebugLogger ()
Get the current global debug logger.
This takes ownership of the given logger which should be allocated using 'new'
Definition at line 66 of file trace.cc.
References debug_logger.
Referenced by Trace::OstreamLogger::getOstream(), ignore(), and output().
iSetStateToStr()
std::string Trace::iSetStateToStr (TarmacBaseRecord::ISetState isetstate)
Returns the string representation of the instruction set being currently run according to the Tarmac format.
Parameters
isetstate enum variable (ISetState) specifying an ARM instruction set.
Returns
instruction set in string format.
Definition at line 51 of file tarmac_record.cc.
References Trace::TarmacBaseRecord::ISET_A64, Trace::TarmacBaseRecord::ISET_ARM, and Trace::TarmacBaseRecord::ISET_THUMB.
Referenced by Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), and Trace::TarmacTracerRecord::TraceInstEntry::print().
opModeToStr()
std::string Trace::opModeToStr (ArmISA::OperatingMode opMode)
Returns the string representation of the ARM Operating Mode (CPSR.M[3:0] field) according to the Tarmac format.
Parameters
opMode ARM operating mode.
Returns
operating mode in string format.
Definition at line 66 of file tarmac_record.cc.
References ArmISA::MODE_ABORT, ArmISA::MODE_EL0T, ArmISA::MODE_EL1H, ArmISA::MODE_EL1T, ArmISA::MODE_EL2H, ArmISA::MODE_EL2T, ArmISA::MODE_EL3H, ArmISA::MODE_EL3T, ArmISA::MODE_FIQ, ArmISA::MODE_HYP, ArmISA::MODE_IRQ, ArmISA::MODE_MON, ArmISA::MODE_SVC, ArmISA::MODE_SYSTEM, ArmISA::MODE_UNDEFINED, and ArmISA::MODE_USER.
Referenced by Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), and Trace::TarmacTracerRecord::TraceRegEntry::updateInt().
output()
std::ostream & Trace::output ()
Get the ostream from the current global logger.
Definition at line 76 of file trace.cc.
References getDebugLogger(), and Trace::Logger::getOstream().
Referenced by Trace::IntelTraceRecord::dump(), Trace::TarmacParserRecord::dump(), Trace::TarmacTracerRecord::flushQueues(), Trace::OstreamLogger::getOstream(), Trace::TarmacParserRecord::printMismatchHeader(), Trace::TarmacParserRecord::TarmacParserRecordEvent::process(), and Trace::ExeTracerRecord::traceInst().
setDebugLogger()
void Trace::setDebugLogger (Logger * logger)
Delete the current global logger and assign a new one.
Definition at line 82 of file trace.cc.
References warn.
Referenced by Trace::OstreamLogger::getOstream(), and output().
Variable Documentation
debug_logger
Logger* Trace::debug_logger = NULL
Definition at line 63 of file trace.cc.
Referenced by getDebugLogger().
ignore
ObjectMatch Trace::ignore
Definition at line 102 of file trace.cc.
intRegNames
const char* Trace::intRegNames[SparcISA::NumIntArchRegs] static
Initial value:
= {
    "g0", "g1", "g2", "g3", "g4", "g5", "g6", "g7",
    "o0", "o1", "o2", "o3", "o4", "o5", "o6", "o7",
    "l0", "l1", "l2", "l3", "l4", "l5", "l6", "l7",
    "i0", "i1", "i2", "i3", "i4", "i5", "i6", "i7",
}
Definition at line 41 of file nativetrace.cc.
Referenced by Trace::SparcNativeTrace::check().