gem5: AMBA Namespace Reference
AMBA Namespace Reference
Typedefs
typedef MasterID OrderID
Functions
static OrderID orderId (PacketPtr pkt)
Typedef Documentation
OrderID
typedef MasterID AMBA::OrderID
Definition at line 48 of file amba.hh.
Function Documentation
orderId()
static OrderID AMBA::orderId (PacketPtr pkt) static
Definition at line 51 of file amba.hh.
References Packet::req.
Referenced by SMMUTranslationProcess::hazardIdHold(), SMMUTranslationProcess::hazardIdRegister(), and SMMUTranslationProcess::hazardIdRelease().