gem5: Net Namespace Reference
Net Namespace Reference
Classes
struct EthAddr
struct EthHdr
class EthPtr
struct ip6_opt_dstopts
struct ip6_opt_fragment
struct ip6_opt_hdr
struct ip6_opt_routing_type2
struct Ip6Hdr
struct Ip6Opt
class Ip6Ptr
struct IpAddress
struct IpHdr
struct IpNetmask
struct IpOpt
class IpPtr
struct IpWithPort
struct TcpHdr
struct TcpOpt
class TcpPtr
struct UdpHdr
class UdpPtr
Functions
bool operator== (const EthAddr &left, const EthAddr &right)
ostream & operator<< (ostream &stream, const EthAddr &ea)
bool operator== (const IpAddress &left, const IpAddress &right)
ostream & operator<< (ostream &stream, const IpAddress &ia)
bool operator== (const IpNetmask &left, const IpNetmask &right)
ostream & operator<< (ostream &stream, const IpNetmask &in)
bool operator== (const IpWithPort &left, const IpWithPort &right)
ostream & operator<< (ostream &stream, const IpWithPort &iwp)
uint16_t cksum (const IpPtr &ptr)
uint16_t __tu_cksum (const IpPtr &ip)
uint16_t __tu_cksum6 (const Ip6Ptr &ip6)
uint16_t cksum (const TcpPtr &tcp)
uint16_t cksum (const UdpPtr &udp)
int hsplit (const EthPacketPtr &ptr)
std::ostream & operator<< (std::ostream &stream, const EthAddr &ea)
std::ostream & operator<< (std::ostream &stream, const IpAddress &ia)
std::ostream & operator<< (std::ostream &stream, const IpNetmask &in)
std::ostream & operator<< (std::ostream &stream, const IpWithPort &iwp)
struct Net::ip6_opt_dstopts __attribute__ ((packed))
Variables
Net::Ip6Opt __attribute__
Function Documentation
__attribute__()
struct Net::ip6_opt_dstopts Net::__attribute__ ((packed))
__tu_cksum()
uint16_t Net::__tu_cksum (const IpPtr & ip)
Definition at line 215 of file inet.cc.
References Net::IpHdr::hlen(), Net::IpHdr::len(), Net::IpHdr::payload(), and RiscvISA::sum.
Referenced by cksum(), and Net::UdpPtr::pstart().
__tu_cksum6()
uint16_t Net::__tu_cksum6 (const Ip6Ptr & ip6)
Definition at line 225 of file inet.cc.
References Net::Ip6Hdr::extensionLength(), Net::Ip6Hdr::payload(), Net::Ip6Hdr::plen(), Net::Ip6Hdr::proto(), Net::Ip6Hdr::src(), and RiscvISA::sum.
Referenced by cksum(), and Net::UdpPtr::pstart().
cksum() [1/3]
uint16_t Net::cksum (const IpPtr & ptr)
Definition at line 208 of file inet.cc.
References Net::IpHdr::bytes(), Net::IpHdr::hlen(), and RiscvISA::sum.
Referenced by IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), Net::IpPtr::pstart(), Net::TcpPtr::pstart(), Net::UdpPtr::pstart(), Sinic::Device::rxKick(), NSGigE::rxKick(), Sinic::Device::txKick(), and NSGigE::txKick().
cksum() [2/3]
uint16_t Net::cksum (const TcpPtr & tcp)
Definition at line 235 of file inet.cc.
References __tu_cksum(), __tu_cksum6(), Net::TcpPtr::packet(), and panic.
cksum() [3/3]
uint16_t Net::cksum (const UdpPtr & udp)
Definition at line 249 of file inet.cc.
References __tu_cksum(), __tu_cksum6(), Net::UdpPtr::packet(), and panic.
hsplit()
int Net::hsplit (const EthPacketPtr & ptr)
Definition at line 380 of file inet.cc.
References iGbReg::TxdOp::ip(), MipsISA::ip6, Net::IpPtr::pstart(), Net::Ip6Ptr::pstart(), Net::TcpPtr::pstart(), Net::UdpPtr::pstart(), and iGbReg::TxdOp::tcp().
Referenced by Net::UdpPtr::pstart(), and IGbE::RxDescCache::writePacket().
operator<<() [1/8]
std::ostream& Net::operator<< (std::ostream & stream, const EthAddr & ea)
operator<<() [2/8]
ostream& Net::operator<< (ostream & stream, const EthAddr & ea)
Definition at line 133 of file inet.cc.
References ArmISA::a, Net::EthAddr::addr(), and ccprintf().
Referenced by Net::IpAddress::ip(), Net::IpNetmask::netmask(), Net::EthAddr::operator uint64_t(), and Net::IpWithPort::port().
operator<<() [3/8]
ostream& Net::operator<< (ostream & stream, const IpAddress & ia)
Definition at line 155 of file inet.cc.
References ccprintf(), Net::IpAddress::ip(), and iGbReg::TxdOp::ip().
operator<<() [4/8]
ostream& Net::operator<< (ostream & stream, const IpNetmask & in)
Definition at line 180 of file inet.cc.
References ccprintf().
operator<<() [5/8]
ostream& Net::operator<< (ostream & stream, const IpWithPort & iwp)
Definition at line 201 of file inet.cc.
References ccprintf().
operator<<() [6/8]
std::ostream& Net::operator<< (std::ostream & stream, const IpAddress & ia)
operator<<() [7/8]
std::ostream& Net::operator<< (std::ostream & stream, const IpNetmask & in)
operator<<() [8/8]
std::ostream& Net::operator<< (std::ostream & stream, const IpWithPort & iwp)
operator==() [1/4]
bool Net::operator== (const EthAddr & left, const EthAddr & right)
Definition at line 127 of file inet.cc.
References Net::EthAddr::bytes().
Referenced by Net::IpAddress::ip(), Net::IpNetmask::netmask(), Net::EthAddr::operator uint64_t(), and Net::IpWithPort::port().
operator==() [2/4]
bool Net::operator== (const IpAddress & left, const IpAddress & right)
Definition at line 149 of file inet.cc.
References Net::IpAddress::ip().
operator==() [3/4]
bool Net::operator== (const IpNetmask & left, const IpNetmask & right)
Definition at line 173 of file inet.cc.
References Net::IpAddress::ip(), and Net::IpNetmask::netmask().
operator==() [4/4]
bool Net::operator== (const IpWithPort & left, const IpWithPort & right)
Definition at line 195 of file inet.cc.
References Net::IpAddress::ip(), and Net::IpWithPort::port().
Variable Documentation
__attribute__
struct Net::ip6_opt_hdr Net::__attribute__