gem5: Minor Namespace Reference
Minor Namespace Reference
Minor contains all the definitions within the MinorCPU apart from the CPU class itself.
Classes
class BranchData
Forward data betwen Execute and Fetch1 carrying change-of-address/stream information.
class BubbleIF
Interface class for data with 'bubble' values.
class BubbleTraitsAdaptor
Pass on call to the element.
class BubbleTraitsPtrAdaptor
Pass on call to the element where the element is a pointer.
class Decode
class ExecContext
ExecContext bears the exec_context interface for Minor.
class Execute
Execute stage.
class Fetch1
A stage responsible for fetching "lines" from memory and passing them to Fetch2.
class Fetch2
This stage receives lines of data from Fetch1, separates them into instructions and passes them to Decode.
class ForwardInstData
Forward flowing data between Fetch2,Decode,Execute carrying a packet of instructions of a width appropriate to the configured stage widths.
class ForwardLineData
Line fetch data in the forward direction.
class FUPipeline
A functional unit configured from a MinorFU object.
class InputBuffer
Like a Queue but with a restricted interface and a setTail function which, when the queue is empty, just takes a reference to the pushed item as the single element.
class InstId
Id for lines and instructions.
class Latch
Wraps a MinorBuffer with Input/Output interfaces to ensure that units within the model can only see the right end of buffers between them.
class LSQ
class MinorActivityRecorder
ActivityRecorder with a Ticked interface.
class MinorBuffer
TimeBuffer with MinorTrace and Named interfaces.
class MinorDynInst
Dynamic instruction for Minor.
class MinorStats
Currently unused stats class.
class NoBubbleTraits
...
class Pipeline
The constructed pipeline.
class Queue
Wrapper for a queue type to act as a pipeline stage input queue.
class QueuedInst
Container class to box instructions in the FUs to make those queues have correct bubble behaviour when stepped.
class ReportIF
Interface class for data with reporting/tracing facilities.
class ReportTraitsAdaptor
...ReportTraits are trait classes with the same functionality as ReportIF, but with elements explicitly passed into the report...
class ReportTraitsPtrAdaptor
A similar adaptor but for elements held by pointer ElemType should implement ReportIF.
class Reservable
Base class for space reservation requestable objects.
class Scoreboard
A scoreboard of register dependencies including, for each register: The number of in-flight instructions which will generate a result for this register.
class SelfStallingPipeline
A pipeline simulating class that will stall (not advance when advance() is called) if a non-bubble value lies at the far end of the pipeline.
Typedefs
typedef SimpleThread MinorThread
Minor will use the SimpleThread state for now.
typedef RefCountingPtr< MinorDynInst > MinorDynInstPtr
MinorDynInsts are currently reference counted.
typedef SelfStallingPipeline< QueuedInst, ReportTraitsAdaptor< QueuedInst > > FUPipelineBase
Functional units have pipelines which stall when an inst gets to their ends allowing Execute::commit to pick up timing-completed insts when it feels like it.
Functions
std::ostream & operator<< (std::ostream &os, const InstId &id)
Print this id in the usual slash-separated format expected by MinorTrace.
std::ostream & operator<< (std::ostream &os, const MinorDynInst &inst)
Print a short reference to this instruction.
static void printRegName (std::ostream &os, const RegId &reg)
Print a register in the form r<n>, f<n>, m<n>(<name>), z for integer, float, misc and zero registers given an 'architectural register number'.
unsigned int cyclicIndexInc (unsigned int index, unsigned int cycle_size)
Increment a cyclic buffer index for indices [0, cycle_size-1].
unsigned int cyclicIndexDec (unsigned int index, unsigned int cycle_size)
Decrement a cyclic buffer index for indices [0, cycle_size-1].
std::ostream & operator<< (std::ostream &os, Execute::DrainState state)
std::ostream & operator<< (std::ostream &os, Fetch1::IcacheState state)
std::ostream & operator<< (std::ostream &os, Fetch1::FetchState state)
std::ostream & operator<< (std::ostream &os, LSQ::AddrRangeCoverage coverage)
std::ostream & operator<< (std::ostream &os, LSQ::LSQRequest::LSQRequestState state)
PacketPtr makePacketForRequest (const RequestPtr &request, bool isLoad, Packet::SenderState *sender_state=NULL, PacketDataPtr data=NULL)
Make a suitable packet for the given request.
std::ostream & operator<< (std::ostream &os, LSQ::MemoryState state)
std::ostream & operator<< (std::ostream &os, BranchData::Reason reason)
Print a branch reason enum.
std::ostream & operator<< (std::ostream &os, const BranchData &branch)
Print BranchData contents in a format suitable for DPRINTF comments, not for MinorTrace.
static RegId flattenRegIndex (const RegId &reg, ThreadContext *thread_context)
Flatten a RegId, irrespective of what reg type it's pointing to.
Variables
const unsigned int MAX_FORWARD_INSTS = 16
Maximum number of instructions that can be carried by the pipeline.
Detailed Description
Minor contains all the definitions within the MinorCPU apart from the CPU class itself.
Typedef Documentation
FUPipelineBase
typedef SelfStallingPipeline<QueuedInst, ReportTraitsAdaptor<QueuedInst> > Minor::FUPipelineBase
Functional units have pipelines which stall when an inst gets to their ends allowing Execute::commit to pick up timing-completed insts when it feels like it.
Definition at line 221 of file func_unit.hh.
MinorDynInstPtr
typedef RefCountingPtr<MinorDynInst> Minor::MinorDynInstPtr
MinorDynInsts are currently reference counted.
Definition at line 63 of file dyn_inst.hh.
MinorThread
typedef SimpleThread Minor::MinorThread
Minor will use the SimpleThread state for now.
Definition at line 60 of file cpu.hh.
Function Documentation
cyclicIndexDec()
unsigned int Minor::cyclicIndexDec (unsigned int index, unsigned int cycle_size) inline
Decrement a cyclic buffer index for indices [0, cycle_size-1].
Definition at line 532 of file execute.cc.
cyclicIndexInc()
unsigned int Minor::cyclicIndexInc (unsigned int index, unsigned int cycle_size) inline
Increment a cyclic buffer index for indices [0, cycle_size-1].
Definition at line 520 of file execute.cc.
flattenRegIndex()
static RegId Minor::flattenRegIndex (const RegId & reg, ThreadContext * thread_context) static
Flatten a RegId, irrespective of what reg type it's pointing to.
Definition at line 104 of file scoreboard.cc.
References ThreadContext::flattenRegId().
Referenced by Minor::Scoreboard::canInstIssue(), Minor::Scoreboard::execSeqNumToWaitFor(), and Minor::Scoreboard::markupInstDests().
makePacketForRequest()
PacketPtr Minor::makePacketForRequest (const RequestPtr & request, bool isLoad, Packet::SenderState * sender_state = NULL, PacketDataPtr data = NULL)
Make a suitable packet for the given request.
If the request is a store, data will be the payload data. If sender_state is NULL, it won't be pushed into the packet as senderState
Definition at line 1679 of file lsq.cc.
References Packet::allocate(), Packet::createRead(), Packet::createWrite(), Packet::dataDynamic(), and Packet::pushSenderState().
Referenced by Minor::LSQ::getDcachePort(), Minor::LSQ::SplitDataRequest::makeFragmentPackets(), and Minor::LSQ::LSQRequest::makePacket().
operator<<() [1/10]
std::ostream & Minor::operator<< (std::ostream & os, BranchData::Reason reason)
Print a branch reason enum.
Definition at line 46 of file pipe_data.cc.
References Minor::BranchData::BadlyPredictedBranch, Minor::BranchData::BadlyPredictedBranchTarget, Minor::BranchData::BranchPrediction, Minor::BranchData::CorrectlyPredictedBranch, Minor::BranchData::HaltFetch, Minor::BranchData::Interrupt, Minor::BranchData::NoBranch, X86ISA::os, Minor::BranchData::SuspendThread, and Minor::BranchData::UnpredictedBranch.
operator<<() [2/10]
std::ostream & Minor::operator<< (std::ostream & os, const InstId & id)
Print this id in the usual slash-separated format expected by MinorTrace.
Definition at line 63 of file dyn_inst.cc.
References Minor::MinorDynInst::bubbleInst, and X86ISA::os.
Referenced by Minor::BranchData::isBranch(), Minor::InstId::operator==(), and Minor::MinorDynInst::setMemAccPredicate().
operator<<() [3/10]
std::ostream & Minor::operator<< (std::ostream & os, const MinorDynInst & inst)
Print a short reference to this instruction.
Print a summary of the instruction.
'-' for a bubble and a series of '/' separated sequence numbers for other instructions. The sequence numbers will be in the order: stream, prediction, line, fetch, exec with exec absent if it is 0. This is used by MinorTrace.
Definition at line 118 of file dyn_inst.cc.
References Minor::MinorDynInst::fault, StaticInst::getName(), Minor::MinorDynInst::id, Minor::MinorDynInst::isFault(), NoFault, X86ISA::os, Minor::MinorDynInst::pc, Minor::MinorDynInst::staticInst, and Minor::MinorDynInst::translationFault.
operator<<() [4/10]
std::ostream & Minor::operator<< (std::ostream & os, const BranchData & branch)
Print BranchData contents in a format suitable for DPRINTF comments, not for MinorTrace.
Definition at line 153 of file pipe_data.cc.
References Minor::BranchData::inst, Minor::BranchData::newPredictionSeqNum, Minor::BranchData::newStreamSeqNum, X86ISA::os, Minor::BranchData::reason, and Minor::BranchData::target.
operator<<() [5/10]
std::ostream& Minor::operator<< (std::ostream & os, LSQ::AddrRangeCoverage coverage)
Definition at line 186 of file lsq.cc.
References Minor::LSQ::FullAddrRangeCoverage, Minor::LSQ::NoAddrRangeCoverage, X86ISA::os, and Minor::LSQ::PartialAddrRangeCoverage.
operator<<() [6/10]
std::ostream& Minor::operator<< (std::ostream & os, LSQ::LSQRequest::LSQRequestState state)
Definition at line 206 of file lsq.cc.
References Minor::LSQ::LSQRequest::Complete, Minor::LSQ::LSQRequest::Failed, Minor::LSQ::LSQRequest::InTranslation, Minor::LSQ::LSQRequest::NotIssued, X86ISA::os, Minor::LSQ::LSQRequest::RequestIssuing, Minor::LSQ::LSQRequest::RequestNeedsRetry, Minor::LSQ::LSQRequest::state, Minor::LSQ::LSQRequest::StoreBufferIssuing, Minor::LSQ::LSQRequest::StoreBufferNeedsRetry, Minor::LSQ::LSQRequest::StoreInStoreBuffer, Minor::LSQ::LSQRequest::StoreToStoreBuffer, and Minor::LSQ::LSQRequest::Translated.
operator<<() [7/10]
std::ostream& Minor::operator<< (std::ostream & os, Fetch1::IcacheState state)
Definition at line 211 of file fetch1.cc.
References Minor::Fetch1::IcacheNeedsRetry, Minor::Fetch1::IcacheRunning, and X86ISA::os.
operator<<() [8/10]
std::ostream& Minor::operator<< (std::ostream & os, Fetch1::FetchState state)
Definition at line 469 of file fetch1.cc.
References Minor::Fetch1::FetchHalted, Minor::Fetch1::FetchRunning, Minor::Fetch1::FetchWaitingForPC, and X86ISA::os.
operator<<() [9/10]
std::ostream& Minor::operator<< (std::ostream & os, LSQ::MemoryState state)
Definition at line 1728 of file lsq.cc.
References Minor::LSQ::MemoryNeedsRetry, Minor::LSQ::MemoryRunning, X86ISA::os, and Minor::LSQ::state.
operator<<() [10/10]
std::ostream& Minor::operator<< (std::ostream & os, Execute::DrainState state)
Definition at line 1783 of file execute.cc.
References Minor::Execute::DrainAllInsts, Minor::Execute::DrainCurrentInst, Minor::Execute::DrainHaltFetch, Minor::Execute::NotDraining, and X86ISA::os.
printRegName()
static void Minor::printRegName (std::ostream & os, const RegId & reg) static
Print a register in the form r<n>, f<n>, m<n>(<name>), z for integer, float, misc and zero registers given an 'architectural register number'.
Definition at line 140 of file dyn_inst.cc.
References CCRegClass, RegId::classValue(), RegId::elemIndex(), FloatRegClass, RegId::index(), IntRegClass, RegId::isZeroReg(), MiscRegClass, ArmISA::miscRegName, panic, VecElemClass, and VecRegClass.
Referenced by Minor::MinorDynInst::minorTraceInst().
Variable Documentation
MAX_FORWARD_INSTS
const unsigned int Minor::MAX_FORWARD_INSTS = 16
Maximum number of instructions that can be carried by the pipeline.
Definition at line 250 of file pipe_data.hh.
Referenced by Minor::ForwardInstData::resize().