gem5: sc_core Namespace Reference
sc_core Namespace Reference
Classes
class sc_attr_base
class sc_attr_cltn
class sc_attribute
class sc_bind_proxy
class sc_buffer
class sc_byte_heap
class sc_clock
struct sc_curr_proc_info
class sc_direct_access
class sc_event
class sc_event_and_expr
class sc_event_and_list
class sc_event_finder
class sc_event_finder_t
class sc_event_or_expr
class sc_event_or_list
class sc_event_queue
class sc_event_queue_if
class sc_export
class sc_export_base
class sc_fifo
class sc_fifo_blocking_in_if
class sc_fifo_blocking_out_if
class sc_fifo_in
class sc_fifo_in_if
class sc_fifo_nonblocking_in_if
class sc_fifo_nonblocking_out_if
class sc_fifo_out
class sc_fifo_out_if
class sc_in
class sc_in< bool >
class sc_in< sc_dt::sc_bigint< W > >
class sc_in< sc_dt::sc_biguint< W > >
class sc_in< sc_dt::sc_int< W > >
class sc_in< sc_dt::sc_logic >
class sc_in< sc_dt::sc_uint< W > >
class sc_in_resolved
class sc_in_rv
class sc_inout
class sc_inout< bool >
class sc_inout< sc_dt::sc_bigint< W > >
class sc_inout< sc_dt::sc_biguint< W > >
class sc_inout< sc_dt::sc_int< W > >
class sc_inout< sc_dt::sc_logic >
class sc_inout< sc_dt::sc_uint< W > >
class sc_inout_resolved
class sc_inout_rv
class sc_int_part_if
class sc_int_sigref
class sc_interface
class sc_join
class sc_member_access
class sc_mempool
class sc_module
class sc_module_name
class sc_mpobject
class sc_mutex
class sc_mutex_if
class sc_object
class sc_out
class sc_out< sc_dt::sc_bigint< W > >
class sc_out< sc_dt::sc_biguint< W > >
class sc_out< sc_dt::sc_int< W > >
class sc_out< sc_dt::sc_uint< W > >
class sc_out_resolved
class sc_out_rv
class sc_port
class sc_port_b
class sc_port_base
class sc_prim_channel
class sc_process_b
class sc_process_handle
class sc_report
class sc_report_handler
class sc_semaphore
class sc_semaphore_if
class sc_sensitive
class sc_signal
class sc_signal< bool, WRITER_POLICY >
class sc_signal< sc_dt::sc_bigint< W > >
class sc_signal< sc_dt::sc_biguint< W > >
class sc_signal< sc_dt::sc_int< W > >
class sc_signal< sc_dt::sc_logic, WRITER_POLICY >
class sc_signal< sc_dt::sc_uint< W > >
class sc_signal_in_if
class sc_signal_in_if< bool >
class sc_signal_in_if< sc_dt::sc_bigint< W > >
class sc_signal_in_if< sc_dt::sc_biguint< W > >
class sc_signal_in_if< sc_dt::sc_int< W > >
class sc_signal_in_if< sc_dt::sc_logic >
class sc_signal_in_if< sc_dt::sc_uint< W > >
class sc_signal_inout_if
class sc_signal_resolved
class sc_signal_rv
class sc_signal_write_if
class sc_signed_part_if
class sc_signed_sigref
class sc_simcontext
class sc_spawn_options
class sc_time
class sc_time_tuple
class sc_trace_file
struct sc_trace_params
class sc_uint_part_if
class sc_uint_sigref
class sc_unsigned_part_if
class sc_unsigned_sigref
class sc_unwind_exception
class sc_user
class sc_vector
class sc_vector_assembly
class sc_vector_base
class sc_vector_iter
class sc_vpool
Typedefs
typedef sc_in< bool > sc_in_clk
typedef sc_inout< bool > sc_inout_clk
typedef sc_out< bool > sc_out_clk
typedef sc_port< sc_event_queue_if, 1, SC_ONE_OR_MORE_BOUND > sc_event_queue_port
template<class T >
using sc_signal_out_if = sc_signal_inout_if< T >
typedef sc_process_b * sc_thread_handle
typedef sc_module sc_behavior
typedef sc_module sc_channel
typedef std::vector< sc_trace_params * > sc_trace_params_vec
typedef const sc_curr_proc_info * sc_curr_proc_handle
typedef std::exception sc_exception
typedef unsigned sc_actions
typedef void(* sc_report_handler_proc) (const sc_report &, const sc_actions &)
Enumerations
enum sc_writer_policy { SC_ONE_WRITER, SC_MANY_WRITERS }
enum sc_starvation_policy { SC_RUN_TO_TIME, SC_EXIT_ON_STARVATION }
enum sc_stop_mode { SC_STOP_FINISH_DELTA, SC_STOP_IMMEDIATE }
enum sc_status {
SC_ELABORATION = 0x1, SC_BEFORE_END_OF_ELABORATION = 0x02, SC_END_OF_ELABORATION = 0x04, SC_START_OF_SIMULATION = 0x08,
SC_RUNNING = 0x10, SC_PAUSED = 0x20, SC_STOPPED = 0x40, SC_END_OF_SIMULATION = 0x80,
SC_END_OF_INITIALIZATION = 0x100, SC_END_OF_UPDATE = 0x400, SC_BEFORE_TIMESTEP = 0x800, SC_STATUS_ANY = 0xdff
}
enum sc_port_policy { SC_ONE_OR_MORE_BOUND, SC_ZERO_OR_MORE_BOUND, SC_ALL_BOUND }
enum sc_curr_proc_kind { SC_NO_PROC_, SC_METHOD_PROC_, SC_THREAD_PROC_, SC_CTHREAD_PROC_ }
enum sc_descendent_inclusion_info { SC_NO_DESCENDANTS, SC_INCLUDE_DESCENDANTS }
enum sc_time_unit {
SC_FS = 0, SC_PS, SC_NS, SC_US,
SC_MS, SC_SEC
}
enum sc_severity {
SC_INFO = 0, SC_WARNING, SC_ERROR, SC_FATAL,
SC_MAX_SEVERITY
}
enum sc_verbosity {
SC_NONE = 0, SC_LOW = 100, SC_MEDIUM = 200, SC_HIGH = 300,
SC_FULL = 400, SC_DEBUG = 500
}
enum {
SC_UNSPECIFIED = 0x0000, SC_DO_NOTHING = 0x0001, SC_THROW = 0x0002, SC_LOG = 0x0004,
SC_DISPLAY = 0x0008, SC_CACHE_REPORT = 0x0010, SC_INTERRUPT = 0x0020, SC_STOP = 0x0040,
SC_ABORT = 0x0080, SC_DEFAULT_INFO_ACTIONS = SC_LOG | SC_DISPLAY, SC_DEFAULT_WARNING_ACTIONS = SC_LOG | SC_DISPLAY, SC_DEFAULT_ERROR_ACTIONS = SC_LOG | SC_CACHE_REPORT | SC_THROW,
SC_DEFAULT_FATAL_ACTIONS = SC_LOG | SC_DISPLAY | SC_CACHE_REPORT | SC_ABORT
}
Functions
sc_event_and_expr operator& (sc_event_and_expr expr, sc_event const &e)
sc_event_and_expr operator& (sc_event_and_expr expr, sc_event_and_list const &eal)
sc_event_or_expr operator| (sc_event_or_expr expr, sc_event const &e)
sc_event_or_expr operator| (sc_event_or_expr expr, sc_event_or_list const &eol)
const std::vector< sc_event * > & sc_get_top_level_events ()
sc_event * sc_find_event (const char *name)
int sc_argc ()
const char *const * sc_argv ()
void sc_start ()
void sc_pause ()
void sc_start (const sc_time &time, sc_starvation_policy p)
void sc_set_stop_mode (sc_stop_mode mode)
sc_stop_mode sc_get_stop_mode ()
void sc_stop ()
const sc_time & sc_time_stamp ()
sc_dt::uint64 sc_delta_count ()
bool sc_is_running ()
bool sc_pending_activity_at_current_time ()
bool sc_pending_activity_at_future_time ()
bool sc_pending_activity ()
sc_time sc_time_to_pending_activity ()
sc_status sc_get_status ()
std::ostream & operator<< (std::ostream &os, sc_status s)
void next_trigger ()
void next_trigger (const sc_event &e)
void next_trigger (const sc_event_or_list &eol)
void next_trigger (const sc_event_and_list &eal)
void next_trigger (const sc_time &t)
void next_trigger (double d, sc_time_unit u)
void next_trigger (const sc_time &t, const sc_event &e)
void next_trigger (double d, sc_time_unit u, const sc_event &e)
void next_trigger (const sc_time &t, const sc_event_or_list &eol)
void next_trigger (double d, sc_time_unit u, const sc_event_or_list &eol)
void next_trigger (const sc_time &t, const sc_event_and_list &eal)
void next_trigger (double d, sc_time_unit u, const sc_event_and_list &eal)
bool timed_out ()
void wait ()
void wait (int n)
void wait (const sc_event &e)
void wait (const sc_event_or_list &eol)
void wait (const sc_event_and_list &eal)
void wait (const sc_time &t)
void wait (double d, sc_time_unit u)
void wait (const sc_time &t, const sc_event &e)
void wait (double d, sc_time_unit u, const sc_event &e)
void wait (const sc_time &t, const sc_event_or_list &eol)
void wait (double d, sc_time_unit u, const sc_event_or_list &eol)
void wait (const sc_time &t, const sc_event_and_list &eal)
void wait (double d, sc_time_unit u, const sc_event_and_list &eal)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &s)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &s)
void at_negedge (const sc_signal_in_if< bool > &s)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &s)
const char * sc_gen_unique_name (const char *seed)
bool sc_hierarchical_name_exists (const char *name)
bool sc_start_of_simulation_invoked ()
bool sc_end_of_simulation_invoked ()
sc_module * sc_module_sc_new (sc_module *mod)
const std::vector< sc_object * > & sc_get_top_level_objects ()
sc_object * sc_find_object (const char *name)
void sc_set_location (const char *file, int lineno)
sc_process_b * sc_get_curr_process_handle ()
sc_process_handle sc_get_current_process_handle ()
bool sc_is_unwinding ()
sc_simcontext * sc_get_curr_simcontext ()
const sc_time operator+ (const sc_time &a, const sc_time &b)
const sc_time operator- (const sc_time &a, const sc_time &b)
const sc_time operator* (const sc_time &t, double d)
const sc_time operator* (double d, const sc_time &t)
const sc_time operator/ (const sc_time &t, double d)
double operator/ (const sc_time &t1, const sc_time &t2)
std::ostream & operator<< (std::ostream &os, const sc_time &t)
void sc_set_time_resolution (double d, sc_time_unit tu)
sc_time sc_get_time_resolution ()
const sc_time & sc_max_time ()
void sc_set_default_time_unit (double d, sc_time_unit tu)
sc_time sc_get_default_time_unit ()
template<class T >
std::ostream & operator<< (std::ostream &os, const sc_fifo< T > &f)
template<class T >
void sc_trace (sc_trace_file *tf, const sc_in< T > &i, const std::string &name)
template<>
void sc_trace< bool > (sc_trace_file *tf, const sc_in< bool > &i, const std::string &name)
template<>
void sc_trace< sc_dt::sc_logic > (sc_trace_file *tf, const sc_in< sc_dt::sc_logic > &i, const std::string &name)
template<class T >
void sc_trace (sc_trace_file *tf, const sc_inout< T > &i, const std::string &name)
template<>
void sc_trace< bool > (sc_trace_file *tf, const sc_inout< bool > &i, const std::string &name)
template<>
void sc_trace< sc_dt::sc_logic > (sc_trace_file *tf, const sc_inout< sc_dt::sc_logic > &i, const std::string &name)
template<class T , sc_writer_policy WRITER_POLICY>
std::ostream & operator<< (std::ostream &os, const sc_signal< T, WRITER_POLICY > &s)
sc_event_and_expr operator& (sc_event_and_expr, sc_event const &)
sc_event_and_expr operator& (sc_event_and_expr, sc_event_and_list const &)
static void sc_start (double d, sc_time_unit t, sc_starvation_policy p=SC_RUN_TO_TIME)
static sc_process_b * sc_get_current_process_b ()
template<typename T >
sc_process_handle sc_spawn (T object, const char *name_p=nullptr, const sc_spawn_options *opt_p=nullptr)
template<typename T >
sc_process_handle sc_spawn (typename T::result_type *r_p, T object, const char *name_p=nullptr, const sc_spawn_options *opt_p=nullptr)
template<typename F , typename... Args>
auto sc_bind (F &&f, Args &&...args) -> decltype(std::bind(std::forward< F >(f), std::forward< Args >(args)...))
template<typename T >
auto sc_ref (T &&v) -> decltype(std::ref(std::forward< T >(v)))
template<typename T >
auto sc_cref (T &&v) -> decltype(std::cref(std::forward< T >(v)))
static const char * sc_release ()
static const char * sc_copyright ()
const char * sc_version ()
void sc_abort ()
void sc_interrupt_here (const char *msg_type, sc_severity)
void sc_stop_here (const char *msg_type, sc_severity)
const std::string sc_report_compose_message (const sc_report &)
bool sc_report_close_default_log ()
sc_trace_file * sc_create_vcd_trace_file (const char *name)
void sc_close_vcd_trace_file (sc_trace_file *tf)
void sc_write_comment (sc_trace_file *tf, const std::string &comment)
void sc_trace (sc_trace_file *, const bool &, const std::string &)
void sc_trace (sc_trace_file *, const bool *, const std::string &)
void sc_trace (sc_trace_file *, const float &, const std::string &)
void sc_trace (sc_trace_file *, const float *, const std::string &)
void sc_trace (sc_trace_file *, const double &, const std::string &)
void sc_trace (sc_trace_file *, const double *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_logic &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_logic *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_int_base &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_int_base *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_uint_base &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_uint_base *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_signed &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_signed *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_unsigned &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_unsigned *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_bv_base &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_bv_base *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_lv_base &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_lv_base *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxval &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxval *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxval_fast &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxval_fast *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxnum &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxnum *, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxnum_fast &, const std::string &)
void sc_trace (sc_trace_file *, const sc_dt::sc_fxnum_fast *, const std::string &)
void sc_trace (sc_trace_file *, const sc_event &, const std::string &)
void sc_trace (sc_trace_file *, const sc_event *, const std::string &)
void sc_trace (sc_trace_file *, const sc_time &, const std::string &)
void sc_trace (sc_trace_file *, const sc_time *, const std::string &)
void sc_trace (sc_trace_file *, const unsigned char &, const std::string &, int width=(8 *sizeof(unsigned char)))
void sc_trace (sc_trace_file *, const unsigned char *, const std::string &, int width=(8 *sizeof(unsigned char)))
void sc_trace (sc_trace_file *, const unsigned short &, const std::string &, int width=(8 *sizeof(unsigned short)))
void sc_trace (sc_trace_file *, const unsigned short *, const std::string &, int width=(8 *sizeof(unsigned short)))
void sc_trace (sc_trace_file *, const unsigned int &, const std::string &, int width=(8 *sizeof(unsigned int)))
void sc_trace (sc_trace_file *, const unsigned int *, const std::string &, int width=(8 *sizeof(unsigned int)))
void sc_trace (sc_trace_file *, const unsigned long &, const std::string &, int width=(8 *sizeof(unsigned long)))
void sc_trace (sc_trace_file *, const unsigned long *, const std::string &, int width=(8 *sizeof(unsigned long)))
void sc_trace (sc_trace_file *, const char &, const std::string &, int width=(8 *sizeof(char)))
void sc_trace (sc_trace_file *, const char *, const std::string &, int width=(8 *sizeof(char)))
void sc_trace (sc_trace_file *, const short &, const std::string &, int width=(8 *sizeof(short)))
void sc_trace (sc_trace_file *, const short *, const std::string &, int width=(8 *sizeof(short)))
void sc_trace (sc_trace_file *, const int &, const std::string &, int width=(8 *sizeof(int)))
void sc_trace (sc_trace_file *, const int *, const std::string &, int width=(8 *sizeof(int)))
void sc_trace (sc_trace_file *, const long &, const std::string &, int width=(8 *sizeof(long)))
void sc_trace (sc_trace_file *, const long *, const std::string &, int width=(8 *sizeof(long)))
void sc_trace (sc_trace_file *, const sc_dt::int64 &, const std::string &, int width=(8 *sizeof(sc_dt::int64)))
void sc_trace (sc_trace_file *, const sc_dt::int64 *, const std::string &, int width=(8 *sizeof(sc_dt::int64)))
void sc_trace (sc_trace_file *, const sc_dt::uint64 &, const std::string &, int width=(8 *sizeof(sc_dt::uint64)))
void sc_trace (sc_trace_file *, const sc_dt::uint64 *, const std::string &, int width=(8 *sizeof(sc_dt::uint64)))
void sc_trace (sc_trace_file *, const unsigned int &, const std::string &, const char **enum_literals)
void sc_trace_delta_cycles (sc_trace_file *, bool on=true)
template<class T >
void sc_trace (sc_trace_file *tf, const sc_signal_in_if< T > &iface, const std::string &name)
void sc_trace (sc_trace_file *, const sc_signal_in_if< char > &, const std::string &, int width)
void sc_trace (sc_trace_file *, const sc_signal_in_if< short > &, const std::string &, int width)
void sc_trace (sc_trace_file *, const sc_signal_in_if< int > &, const std::string &, int width)
void sc_trace (sc_trace_file *, const sc_signal_in_if< long > &, const std::string &, int width)
template<typename T , typename MT >
sc_vector_assembly< T, MT > sc_assemble_vector (sc_vector< T > &, MT(T::*member_ptr))
template<typename T , typename MT >
sc_vector_assembly< T, MT > sc_assemble_vector (sc_vector< T > &v, MT(T::*ptr))
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_in< sc_dt::sc_int< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_inout< sc_dt::sc_int< W > > &a)
void sc_signal_invalid_writer (const char *name, const char *kind, const char *first_writer, const char *second_writer)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_in< sc_dt::sc_bigint< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_inout< sc_dt::sc_bigint< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_in< sc_dt::sc_uint< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_inout< sc_dt::sc_uint< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_in< sc_dt::sc_biguint< W > > &a)
SC_TEMPLATE std::ostream & operator<< (std::ostream &os, const sc_inout< sc_dt::sc_biguint< W > > &a)
Variables
const char SC_ID_PORT_OUTSIDE_MODULE_ [] = "port specified outside of module"
const char SC_ID_CLOCK_PERIOD_ZERO_ [] = "sc_clock period is zero"
const char SC_ID_CLOCK_HIGH_TIME_ZERO_ [] = "sc_clock high time is zero"
const char SC_ID_CLOCK_LOW_TIME_ZERO_ [] = "sc_clock low time is zero"
const char SC_ID_MORE_THAN_ONE_FIFO_READER_ []
const char SC_ID_MORE_THAN_ONE_FIFO_WRITER_ []
const char SC_ID_INVALID_FIFO_SIZE_ []
const char SC_ID_BIND_IF_TO_PORT_ [] = "bind interface to port failed"
const char SC_ID_BIND_PORT_TO_PORT_ [] = "bind parent port to port failed"
const char SC_ID_COMPLETE_BINDING_ [] = "complete binding failed"
const char SC_ID_INSERT_PORT_ [] = "insert port failed"
const char SC_ID_REMOVE_PORT_ [] = "remove port failed"
const char SC_ID_GET_IF_ [] = "get interface failed"
const char SC_ID_INSERT_PRIM_CHANNEL_ [] = "insert primitive channel failed"
const char SC_ID_REMOVE_PRIM_CHANNEL_ [] = "remove primitive channel failed"
const char SC_ID_MORE_THAN_ONE_SIGNAL_DRIVER_ []
const char SC_ID_NO_DEFAULT_EVENT_ [] = "channel doesn't have a default event"
const char SC_ID_RESOLVED_PORT_NOT_BOUND_ []
const char SC_ID_FIND_EVENT_ [] = "find event failed"
const char SC_ID_INVALID_SEMAPHORE_VALUE_ []
const char SC_ID_SC_EXPORT_HAS_NO_INTERFACE_ []
const char SC_ID_INSERT_EXPORT_ [] = "insert sc_export failed"
const char SC_ID_EXPORT_OUTSIDE_MODULE_ []
const char SC_ID_SC_EXPORT_NOT_REGISTERED_ []
const char SC_ID_SC_EXPORT_NOT_BOUND_AFTER_CONSTRUCTION_ []
const char SC_ID_ATTEMPT_TO_WRITE_TO_CLOCK_ []
const char SC_ID_SC_EXPORT_ALREADY_BOUND_ []
const char SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_ []
const char SC_ID_ATTEMPT_TO_BIND_CLOCK_TO_OUTPUT_ []
const char SC_ID_NO_ASYNC_UPDATE_ []
const char SC_ID_NO_BOOL_RETURNED_ [] = "operator does not return boolean"
const char SC_ID_NO_INT_RETURNED_ [] = "operator does not return int"
const char SC_ID_NO_SC_LOGIC_RETURNED_ [] = "operator does not return sc_logic"
const char SC_ID_OPERAND_NOT_SC_LOGIC_ [] = "operand is not sc_logic"
const char SC_ID_OPERAND_NOT_BOOL_ [] = "operand is not bool"
const char SC_ID_INSTANCE_EXISTS_ [] = "object already exists"
const char SC_ID_ILLEGAL_CHARACTERS_ [] = "illegal characters"
const char SC_ID_VC6_PROCESS_HELPER_ []
const char SC_ID_VC6_MAX_PROCESSES_EXCEEDED_ []
const char SC_ID_END_MODULE_NOT_CALLED_ []
const char SC_ID_HIER_NAME_INCORRECT_ []
const char SC_ID_SET_STACK_SIZE_ []
const char SC_ID_SC_MODULE_NAME_USE_ [] = "incorrect use of sc_module_name"
const char SC_ID_SC_MODULE_NAME_REQUIRED_ []
const char SC_ID_SET_TIME_RESOLUTION_ [] = "set time resolution failed"
const char SC_ID_SET_DEFAULT_TIME_UNIT_ [] = "set default time unit failed"
const char SC_ID_DEFAULT_TIME_UNIT_CHANGED_ []
const char SC_ID_INCONSISTENT_API_CONFIG_ []
const char SC_ID_WAIT_NOT_ALLOWED_ []
const char SC_ID_NEXT_TRIGGER_NOT_ALLOWED_ []
const char SC_ID_IMMEDIATE_NOTIFICATION_ []
const char SC_ID_HALT_NOT_ALLOWED_ [] = "halt() is only allowed in SC_CTHREADs"
const char SC_ID_WATCHING_NOT_ALLOWED_ []
const char SC_ID_DONT_INITIALIZE_ []
const char SC_ID_WAIT_N_INVALID_ [] = "wait(n) is only valid for n > 0"
const char SC_ID_MAKE_SENSITIVE_ [] = "make sensitive failed"
const char SC_ID_MAKE_SENSITIVE_POS_ [] = "make sensitive pos failed"
const char SC_ID_MAKE_SENSITIVE_NEG_ [] = "make sensitive neg failed"
const char SC_ID_INSERT_MODULE_ [] = "insert module failed"
const char SC_ID_REMOVE_MODULE_ [] = "remove module failed"
const char SC_ID_NOTIFY_DELAYED_ []
const char SC_ID_GEN_UNIQUE_NAME_ []
const char SC_ID_MODULE_NAME_STACK_EMPTY_ []
const char SC_ID_NAME_EXISTS_ [] = "name already exists"
const char SC_ID_IMMEDIATE_SELF_NOTIFICATION_ []
const char SC_ID_WAIT_DURING_UNWINDING_ []
const char SC_ID_CYCLE_MISSES_EVENTS_ []
const char SC_ID_RETHROW_UNWINDING_ []
const char SC_ID_PROCESS_ALREADY_UNWINDING_ []
const char SC_ID_MODULE_METHOD_AFTER_START_ []
const char SC_ID_MODULE_THREAD_AFTER_START_ []
const char SC_ID_MODULE_CTHREAD_AFTER_START_ []
const char SC_ID_SIMULATION_TIME_OVERFLOW_ []
const char SC_ID_SIMULATION_STOP_CALLED_TWICE_ []
const char SC_ID_SIMULATION_START_AFTER_STOP_ []
const char SC_ID_STOP_MODE_AFTER_START_ []
const char SC_ID_SIMULATION_START_AFTER_ERROR_ []
const char SC_ID_SIMULATION_UNCAUGHT_EXCEPTION_ [] = "uncaught exception"
const char SC_ID_PHASE_CALLBACKS_UNSUPPORTED_ []
const char SC_ID_PHASE_CALLBACK_NOT_IMPLEMENTED_ []
const char SC_ID_PHASE_CALLBACK_REGISTER_ []
const char SC_ID_PHASE_CALLBACK_FORBIDDEN_ []
const char SC_ID_SIMULATION_START_UNEXPECTED_ []
const char SC_ID_THROW_IT_IGNORED_ []
const char SC_ID_NOT_EXPECTING_DYNAMIC_EVENT_NOTIFY_ []
const char SC_ID_DISABLE_WILL_ORPHAN_PROCESS_ []
const char SC_ID_PROCESS_CONTROL_CORNER_CASE_ []
const char SC_ID_METHOD_TERMINATION_EVENT_ []
const char SC_ID_JOIN_ON_METHOD_HANDLE_ []
const char SC_ID_NO_PROCESS_SEMANTICS_ []
const char SC_ID_EVENT_ON_NULL_PROCESS_ []
const char SC_ID_EVENT_LIST_FAILED_ []
const char SC_ID_UNKNOWN_PROCESS_TYPE_ [] = "Unknown process type"
const char SC_ID_TIME_CONVERSION_FAILED_ [] = "sc_time conversion failed"
const char SC_ID_NEGATIVE_SIMULATION_TIME_ []
const char SC_ID_BAD_SC_MODULE_CONSTRUCTOR_ []
const char SC_ID_EMPTY_PROCESS_HANDLE_ []
const char SC_ID_NO_SC_START_ACTIVITY_ []
const char SC_ID_KILL_PROCESS_WHILE_UNITIALIZED_ []
const char SC_ID_RESET_PROCESS_WHILE_NOT_RUNNING_ []
const char SC_ID_THROW_IT_WHILE_NOT_RUNNING_ []
const sc_bind_proxy SC_BIND_PROXY_NIL
bool sc_allow_process_control_corners
const sc_time SC_ZERO_TIME
const char SC_ID_LENGTH_MISMATCH_ []
const char SC_ID_INCOMPATIBLE_TYPES_ [] = "incompatible types"
const char SC_ID_CANNOT_CONVERT_ [] = "cannot perform conversion"
const char SC_ID_INCOMPATIBLE_VECTORS_ [] = "incompatible vectors"
const char SC_ID_VALUE_NOT_VALID_ [] = "value is not valid"
const char SC_ID_ZERO_LENGTH_ [] = "zero length"
const char SC_ID_VECTOR_CONTAINS_LOGIC_VALUE_ []
const char SC_ID_SC_BV_CANNOT_CONTAIN_X_AND_Z_ []
const char SC_ID_VECTOR_TOO_LONG_ [] = "vector is too long: truncated"
const char SC_ID_VECTOR_TOO_SHORT_ [] = "vector is too short: 0-padded"
const char SC_ID_WRONG_VALUE_ [] = "wrong value"
const char SC_ID_LOGIC_Z_TO_BOOL_ []
const char SC_ID_LOGIC_X_TO_BOOL_ []
const char SC_ID_INVALID_WL_ [] = "total wordlength <= 0 is not valid"
const char SC_ID_INVALID_N_BITS_ [] = "number of bits < 0 is not valid"
const char SC_ID_INVALID_DIV_WL_ [] = "division wordlength <= 0 is not valid"
const char SC_ID_INVALID_CTE_WL_ [] = "constant wordlength <= 0 is not valid"
const char SC_ID_INVALID_MAX_WL_ []
const char SC_ID_INVALID_FX_VALUE_ [] = "invalid fixed-point value"
const char SC_ID_INVALID_O_MODE_ [] = "invalid overflow mode"
const char SC_ID_OUT_OF_RANGE_ [] = "index out of range"
const char SC_ID_CONTEXT_BEGIN_FAILED_ [] = "context begin failed"
const char SC_ID_CONTEXT_END_FAILED_ [] = "context end failed"
const char SC_ID_WRAP_SM_NOT_DEFINED_ []
const char SC_ID_INIT_FAILED_ [] = "initialization failed"
const char SC_ID_ASSIGNMENT_FAILED_ [] = "assignment failed"
const char SC_ID_OPERATION_FAILED_ [] = "operation failed"
const char SC_ID_CONVERSION_FAILED_ [] = "conversion failed"
sc_byte_heap sc_temp_heap (0x300000)
const unsigned int sc_version_major = SC_VERSION_MAJOR
const unsigned int sc_version_minor = SC_VERSION_MINOR
const unsigned int sc_version_patch = SC_VERSION_PATCH
const std::string sc_version_originator = SC_VERSION_ORIGINATOR
const std::string sc_version_release_date = SC_VERSION_RELEASE_DATE
const std::string sc_version_prerelease = SC_VERSION_PRERELEASE
const bool sc_is_prerelease = SC_IS_PRERELEASE
const std::string sc_version_string = SC_VERSION
const std::string sc_copyright_string = SC_COPYRIGHT
const char SC_ID_UNKNOWN_ERROR_ [] = "unknown error"
const char SC_ID_WITHOUT_MESSAGE_ [] = ""
const char SC_ID_NOT_IMPLEMENTED_ [] = "not implemented"
const char SC_ID_INTERNAL_ERROR_ [] = "internal error"
const char SC_ID_ASSERTION_FAILED_ [] = "assertion failed"
const char SC_ID_OUT_OF_BOUNDS_ [] = "out of bounds"
const char SC_ID_ABORT_ [] = "simulation aborted"
const char SC_ID_REGISTER_ID_FAILED_ [] = "register_id failed"
const char SC_ID_STRING_TOO_LONG_ [] = "string is too long"
const char SC_ID_FRONT_ON_EMPTY_LIST_ []
const char SC_ID_BACK_ON_EMPTY_LIST_ []
const char SC_ID_IEEE_1666_DEPRECATION_ []
const char SC_ID_VECTOR_INIT_CALLED_TWICE_ []
const char SC_ID_VECTOR_BIND_EMPTY_ []
const char SC_ID_VECTOR_NONOBJECT_ELEMENTS_ []
Typedef Documentation
sc_actions
typedef unsigned sc_core::sc_actions
Definition at line 41 of file sc_report_handler.hh.
sc_behavior
typedef sc_module sc_core::sc_behavior
Definition at line 347 of file sc_module.hh.
sc_channel
typedef sc_module sc_core::sc_channel
Definition at line 348 of file sc_module.hh.
sc_curr_proc_handle
typedef const sc_curr_proc_info* sc_core::sc_curr_proc_handle
Definition at line 149 of file sc_process_handle.hh.
sc_event_queue_port
typedef sc_port<sc_event_queue_if, 1, SC_ONE_OR_MORE_BOUND> sc_core::sc_event_queue_port
Definition at line 82 of file sc_event_queue.hh.
sc_exception
typedef std::exception sc_core::sc_exception
Definition at line 38 of file sc_exception.hh.
sc_in_clk
typedef sc_in<bool> sc_core::sc_in_clk
Definition at line 118 of file sc_clock.hh.
sc_inout_clk
typedef sc_inout<bool> sc_core::sc_inout_clk
Definition at line 121 of file sc_clock.hh.
sc_out_clk
typedef sc_out<bool> sc_core::sc_out_clk
Definition at line 122 of file sc_clock.hh.
sc_report_handler_proc
typedef void(* sc_core::sc_report_handler_proc) (const sc_report &, const sc_actions &)
Definition at line 64 of file sc_report_handler.hh.
sc_signal_out_if
template<class T > using sc_core::sc_signal_out_if = typedef sc_signal_inout_if<T>
Definition at line 90 of file sc_signal_inout_if.hh.
sc_thread_handle
typedef sc_process_b* sc_core::sc_thread_handle
Definition at line 40 of file sc_join.hh.
sc_trace_params_vec
typedef std::vector<sc_trace_params *> sc_core::sc_trace_params_vec
Definition at line 67 of file sc_port.hh.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SC_UNSPECIFIED
SC_DO_NOTHING
SC_THROW
SC_LOG
SC_DISPLAY
SC_CACHE_REPORT
SC_INTERRUPT
SC_STOP
SC_ABORT
SC_DEFAULT_INFO_ACTIONS
SC_DEFAULT_WARNING_ACTIONS
SC_DEFAULT_ERROR_ACTIONS
SC_DEFAULT_FATAL_ACTIONS
Definition at line 43 of file sc_report_handler.hh.
sc_curr_proc_kind
enum sc_core::sc_curr_proc_kind
Enumerator
SC_NO_PROC_
SC_METHOD_PROC_
SC_THREAD_PROC_
SC_CTHREAD_PROC_
Definition at line 86 of file sc_process_handle.hh.
sc_descendent_inclusion_info
enum sc_core::sc_descendent_inclusion_info
Enumerator
SC_NO_DESCENDANTS
SC_INCLUDE_DESCENDANTS
Definition at line 94 of file sc_process_handle.hh.
sc_port_policy
enum sc_core::sc_port_policy
Enumerator
SC_ONE_OR_MORE_BOUND
SC_ZERO_OR_MORE_BOUND
SC_ALL_BOUND
Definition at line 69 of file sc_port.hh.
sc_severity
enum sc_core::sc_severity
Enumerator
SC_INFO
SC_WARNING
SC_ERROR
SC_FATAL
SC_MAX_SEVERITY
Definition at line 41 of file sc_report.hh.
sc_starvation_policy
enum sc_core::sc_starvation_policy
Enumerator
SC_RUN_TO_TIME
SC_EXIT_ON_STARVATION
Definition at line 48 of file sc_main.hh.
sc_status
enum sc_core::sc_status
Enumerator
SC_ELABORATION
SC_BEFORE_END_OF_ELABORATION
SC_END_OF_ELABORATION
SC_START_OF_SIMULATION
SC_RUNNING
SC_PAUSED
SC_STOPPED
SC_END_OF_SIMULATION
SC_END_OF_INITIALIZATION
SC_END_OF_UPDATE
SC_BEFORE_TIMESTEP
SC_STATUS_ANY
Definition at line 83 of file sc_main.hh.
sc_stop_mode
enum sc_core::sc_stop_mode
Enumerator
SC_STOP_FINISH_DELTA
SC_STOP_IMMEDIATE
Definition at line 64 of file sc_main.hh.
sc_time_unit
enum sc_core::sc_time_unit
Enumerator
SC_FS
SC_PS
SC_NS
SC_US
SC_MS
SC_SEC
Definition at line 42 of file sc_time.hh.
sc_verbosity
enum sc_core::sc_verbosity
Enumerator
SC_NONE
SC_LOW
SC_MEDIUM
SC_HIGH
SC_FULL
SC_DEBUG
Definition at line 50 of file sc_report.hh.
sc_writer_policy
enum sc_core::sc_writer_policy
Enumerator
SC_ONE_WRITER
SC_MANY_WRITERS
Definition at line 39 of file sc_signal_inout_if.hh.
Function Documentation
at_negedge() [1/2]
void sc_core::at_negedge (const sc_signal_in_if< bool > & s)
Definition at line 804 of file sc_module.cc.
References sc_core::sc_signal_in_if< bool >::read(), and sc_core::sc_module::wait().
at_negedge() [2/2]
void sc_core::at_negedge (const sc_signal_in_if< sc_dt::sc_logic > & s)
Definition at line 813 of file sc_module.cc.
References sc_dt::Log_0, sc_dt::Log_1, sc_core::sc_signal_in_if< sc_dt::sc_logic >::read(), and sc_core::sc_module::wait().
Referenced by sc_core::sc_module::at_negedge().
at_posedge() [1/2]
void sc_core::at_posedge (const sc_signal_in_if< bool > & s)
Definition at line 786 of file sc_module.cc.
References sc_core::sc_signal_in_if< bool >::read(), and sc_core::sc_module::wait().
Referenced by SC_MODULE().
at_posedge() [2/2]
void sc_core::at_posedge (const sc_signal_in_if< sc_dt::sc_logic > & s)
Definition at line 795 of file sc_module.cc.
References sc_dt::Log_0, sc_dt::Log_1, sc_core::sc_signal_in_if< sc_dt::sc_logic >::read(), and sc_core::sc_module::wait().
Referenced by sc_core::sc_module::at_posedge().
halt()
void sc_core::halt ()
Definition at line 779 of file sc_module.cc.
References wait().
Referenced by sc_core::sc_module::halt().
next_trigger() [1/12]
void sc_core::next_trigger ()
Definition at line 540 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Process::clearDynamic(), sc_gem5::Scheduler::current(), MipsISA::p, and sc_gem5::scheduler.
Referenced by sc_core::sc_prim_channel::next_trigger(), sc_core::sc_module::operator=(), and sc_core::sc_prim_channel::update().
next_trigger() [2/12]
void sc_core::next_trigger (const sc_event & e)
Definition at line 548 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEvent(), MipsISA::p, and sc_gem5::scheduler.
next_trigger() [3/12]
void sc_core::next_trigger (const sc_event_or_list & eol)
Definition at line 556 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventOrList(), MipsISA::p, and sc_gem5::scheduler.
next_trigger() [4/12]
void sc_core::next_trigger (const sc_event_and_list & eal)
Definition at line 564 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventAndList(), MipsISA::p, and sc_gem5::scheduler.
next_trigger() [5/12]
void sc_core::next_trigger (const sc_time & t)
Definition at line 572 of file sc_module.cc.
References sc_gem5::Process::clearDynamic(), sc_gem5::Scheduler::current(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Process::setTimeout().
next_trigger() [6/12]
void sc_core::next_trigger (double d, sc_time_unit u)
Definition at line 580 of file sc_module.cc.
References sc_core::sc_module::next_trigger().
next_trigger() [7/12]
void sc_core::next_trigger (const sc_time & t, const sc_event & e)
Definition at line 586 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEvent(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Process::setTimeout().
next_trigger() [8/12]
void sc_core::next_trigger (double d, sc_time_unit u, const sc_event & e)
Definition at line 594 of file sc_module.cc.
References sc_core::sc_module::next_trigger().
next_trigger() [9/12]
void sc_core::next_trigger (const sc_time & t, const sc_event_or_list & eol)
Definition at line 600 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventOrList(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Process::setTimeout().
next_trigger() [10/12]
void sc_core::next_trigger (double d, sc_time_unit u, const sc_event_or_list & eol)
Definition at line 608 of file sc_module.cc.
References sc_core::sc_module::next_trigger().
next_trigger() [11/12]
void sc_core::next_trigger (const sc_time & t, const sc_event_and_list & eal)
Definition at line 614 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventAndList(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Process::setTimeout().
next_trigger() [12/12]
void sc_core::next_trigger (double d, sc_time_unit u, const sc_event_and_list & eal)
Definition at line 622 of file sc_module.cc.
References sc_core::sc_module::next_trigger().
Referenced by sc_core::sc_module::next_trigger().
operator&() [1/4]
sc_event_and_expr sc_core::operator & (sc_event_and_expr , sc_event const &)
Definition at line 245 of file sc_event.cc.
References sc_core::sc_event_and_expr::insert().
Referenced by sc_dt::operator&().
operator&() [2/4]
sc_event_and_expr sc_core::operator & (sc_event_and_expr , sc_event_and_list const &)
Definition at line 252 of file sc_event.cc.
References sc_core::sc_event_and_expr::insert().
operator&() [3/4]
sc_event_and_expr sc_core::operator & (sc_event_and_expr expr, sc_event const & e)
Definition at line 245 of file sc_event.cc.
References sc_core::sc_event_and_expr::insert().
Referenced by sc_dt::operator&().
operator&() [4/4]
sc_event_and_expr sc_core::operator & (sc_event_and_expr expr, sc_event_and_list const & eal)
Definition at line 252 of file sc_event.cc.
References sc_core::sc_event_and_expr::insert().
operator*() [1/2]
const sc_time sc_core::operator* (const sc_time & t, double d)
Definition at line 259 of file sc_time.cc.
References sc_core::sc_time::from_value(), and sc_core::sc_time::value().
Referenced by sc_dt::operator*().
operator*() [2/2]
const sc_time sc_core::operator* (double d, const sc_time & t)
Definition at line 266 of file sc_time.cc.
References sc_core::sc_time::from_value(), and sc_core::sc_time::value().
operator+()
const sc_time sc_core::operator+ (const sc_time & a, const sc_time & b)
Definition at line 247 of file sc_time.cc.
References sc_core::sc_time::from_value(), and sc_core::sc_time::value().
Referenced by sc_dt::operator+().
operator-()
const sc_time sc_core::operator- (const sc_time & a, const sc_time & b)
Definition at line 253 of file sc_time.cc.
References sc_core::sc_time::from_value(), and sc_core::sc_time::value().
Referenced by sc_dt::operator-().
operator/() [1/2]
const sc_time sc_core::operator/ (const sc_time & t, double d)
Definition at line 273 of file sc_time.cc.
References sc_core::sc_time::from_value(), and sc_core::sc_time::value().
Referenced by sc_dt::operator/().
operator/() [2/2]
double sc_core::operator/ (const sc_time & t1, const sc_time & t2)
Definition at line 280 of file sc_time.cc.
References sc_core::sc_time::to_double().
operator<<() [1/12]
std::ostream & sc_core::operator<< (std::ostream & os, sc_status s)
Definition at line 181 of file sc_main.cc.
References ccprintf(), ArmISA::m, X86ISA::os, SC_BEFORE_END_OF_ELABORATION, SC_BEFORE_TIMESTEP, SC_ELABORATION, SC_END_OF_ELABORATION, SC_END_OF_INITIALIZATION, SC_END_OF_SIMULATION, SC_END_OF_UPDATE, SC_PAUSED, SC_RUNNING, SC_START_OF_SIMULATION, SC_STATUS_ANY, and SC_STOPPED.
Referenced by sc_dt::operator<<().
operator<<() [2/12]
template<class T > std::ostream& sc_core::operator<< (std::ostream & os, const sc_fifo< T > & f) inline
Definition at line 219 of file sc_fifo.hh.
References ArmISA::f, and X86ISA::os.
operator<<() [3/12]
std::ostream & sc_core::operator<< (std::ostream & os, const sc_time & t)
Definition at line 286 of file sc_time.cc.
References X86ISA::os, and sc_core::sc_time::print().
operator<<() [4/12]
template<class T , sc_writer_policy WRITER_POLICY> std::ostream& sc_core::operator<< (std::ostream & os, const sc_signal< T, WRITER_POLICY > & s) inline
Definition at line 319 of file sc_signal.hh.
References X86ISA::os, and ArmISA::s.
operator<<() [5/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_in< sc_dt::sc_int< W > > & a) inline
Definition at line 1001 of file scx_signal_int.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [6/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_in< sc_dt::sc_uint< W > > & a) inline
Definition at line 1057 of file scx_signal_uint.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [7/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_in< sc_dt::sc_biguint< W > > & a) inline
Definition at line 1177 of file scx_signal_unsigned.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [8/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_in< sc_dt::sc_bigint< W > > & a) inline
Definition at line 1181 of file scx_signal_signed.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [9/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_inout< sc_dt::sc_int< W > > & a) inline
Definition at line 1335 of file scx_signal_int.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [10/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_inout< sc_dt::sc_uint< W > > & a) inline
Definition at line 1391 of file scx_signal_uint.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [11/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_inout< sc_dt::sc_biguint< W > > & a) inline
Definition at line 1513 of file scx_signal_unsigned.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator<<() [12/12]
SC_TEMPLATE std::ostream& sc_core::operator<< (std::ostream & os, const sc_inout< sc_dt::sc_bigint< W > > & a) inline
Definition at line 1516 of file scx_signal_signed.h.
References ArmISA::a, X86ISA::os, and SC_TEMPLATE.
operator|() [1/2]
sc_event_or_expr sc_core::operator| (sc_event_or_expr expr, sc_event const & e)
Definition at line 296 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
Referenced by sc_dt::operator|().
operator|() [2/2]
sc_event_or_expr sc_core::operator| (sc_event_or_expr expr, sc_event_or_list const & eol)
Definition at line 303 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
sc_abort()
void sc_core::sc_abort ()
Definition at line 180 of file sc_report.cc.
References panic.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::check_bounds(), sc_dt::sc_subref_r< X >::check_bounds(), sc_dt::sc_proxy< sc_subref_r< X > >::check_wbounds(), sc_core::sc_vector_base::checkIndex(), sc_core::sc_report_handler::default_handler(), sc_dt::div_by_zero(), sc_dt::sc_bv_base::init(), sc_dt::sc_lv_base::init(), sc_dt::sc_uint_base::invalid_index(), sc_dt::sc_int_base::invalid_index(), sc_dt::sc_uint_base::invalid_length(), sc_dt::sc_int_base::invalid_length(), sc_dt::sc_uint_base::invalid_range(), sc_dt::sc_int_base::invalid_range(), sc_dt::sc_unsigned::invalid_range(), sc_dt::sc_bit::invalid_value(), sc_dt::mul_signs(), sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::operator->(), sc_dt::print_other(), sc_dt::sc_int_concref_invalid_length(), sc_dt::sc_signed::sc_signed(), sc_dt::sc_uint_concref_invalid_length(), sc_dt::sc_unsigned::sc_unsigned(), and sc_dt::sc_unsigned_subref_r::to_string().
sc_argc()
int sc_core::sc_argc ()
Definition at line 51 of file sc_main.cc.
References sc_gem5::ScMainFiber::argc(), and sc_gem5::scMainFiber.
sc_argv()
const char *const * sc_core::sc_argv ()
Definition at line 57 of file sc_main.cc.
References sc_gem5::ScMainFiber::argv(), and sc_gem5::scMainFiber.
sc_assemble_vector() [1/2]
template<typename T , typename MT > sc_vector_assembly<T, MT> sc_core::sc_assemble_vector (sc_vector< T > & , MTT::* member_ptr)
sc_assemble_vector() [2/2]
template<typename T , typename MT > sc_vector_assembly<T, MT> sc_core::sc_assemble_vector (sc_vector< T > & v, MT T::* ptr)
Definition at line 781 of file sc_vector.hh.
References ArmISA::v.
sc_bind()
template<typename F , typename... Args> auto sc_core::sc_bind (F && f, Args &&... args) -> decltype(std::bind(std::forward<F>(f), std::forward<Args>(args)...))
Definition at line 200 of file sc_spawn.hh.
References ArmISA::f.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase(), sc_cref(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
sc_close_vcd_trace_file()
void sc_core::sc_close_vcd_trace_file (sc_trace_file * tf)
Definition at line 63 of file sc_trace_file.cc.
References sc_gem5::scheduler, X86ISA::tf, and sc_gem5::Scheduler::unregisterTraceFile().
sc_copyright()
static const char* sc_core::sc_copyright () inline static
Definition at line 96 of file functions.hh.
References sc_version().
sc_create_vcd_trace_file()
sc_trace_file * sc_core::sc_create_vcd_trace_file (const char * name)
Definition at line 55 of file sc_trace_file.cc.
References sc_gem5::Scheduler::registerTraceFile(), sc_gem5::scheduler, and X86ISA::tf.
sc_cref()
template<typename T > auto sc_core::sc_cref (T && v) -> decltype(std::cref(std::forward<T>(v)))
Definition at line 213 of file sc_spawn.hh.
References sc_bind(), sc_ref(), and ArmISA::v.
sc_delta_count()
sc_dt::uint64 sc_core::sc_delta_count ()
Definition at line 138 of file sc_main.cc.
References sc_gem5::Scheduler::numCycles(), and sc_gem5::scheduler.
Referenced by sc_gem5::ScSignalBaseBinary::_signalNegedge(), sc_core::sc_simcontext::delta_count(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::fec(), tlm_utils::time_ordered_list< std::pair >::insert(), and tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::notify().
sc_end_of_simulation_invoked()
bool sc_core::sc_end_of_simulation_invoked ()
Definition at line 854 of file sc_module.cc.
References AlphaISA::Kernel::kernel.
sc_find_event()
sc_event * sc_core::sc_find_event (const char * name)
Definition at line 411 of file sc_event.cc.
References sc_gem5::allEvents, and sc_gem5::findEvent().
sc_find_object()
sc_object * sc_core::sc_find_object (const char * name)
Definition at line 169 of file sc_object.cc.
References sc_gem5::findObject().
sc_gen_unique_name()
const char * sc_core::sc_gen_unique_name (const char * seed)
Definition at line 822 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::UniqueNameGen::gen(), sc_gem5::globalNameGen, mod(), MipsISA::p, sc_gem5::pickParentModule(), SC_ID_GEN_UNIQUE_NAME_, SC_REPORT_ERROR, sc_gem5::scheduler, and sc_gem5::Process::uniqueName().
Referenced by sc_gem5::ClockTick::ClockTick(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::default_name(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::default_name(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::default_name(), sc_gem5::Event::Event(), sc_core::sc_vector< svp_gicv3_comms::gicv3_comms_target_socket<> >::init(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), sc_gem5::Object::Object(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase(), sc_gem5::Object::pickUniqueName(), sc_gem5::pickUniqueName(), sc_gem5::spawnWork(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
sc_get_curr_process_handle()
sc_process_b * sc_core::sc_get_curr_process_handle ()
Definition at line 71 of file sc_process_handle.cc.
References sc_gem5::Scheduler::current(), and sc_gem5::scheduler.
Referenced by sc_core::sc_signal< sc_dt::sc_int< W > >::check_writer(), and sc_get_current_process_b().
sc_get_curr_simcontext()
sc_simcontext * sc_core::sc_get_curr_simcontext ()
Definition at line 87 of file sc_simcontext.cc.
Referenced by tlm_utils::simple_socket_base::elaboration_check(), and sc_gem5::Object::simcontext().
sc_get_current_process_b()
static sc_process_b* sc_core::sc_get_current_process_b () inline static
Definition at line 137 of file sc_process_handle.hh.
References sc_get_curr_process_handle().
Referenced by sc_core::sc_signal< sc_dt::sc_uint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::check_writer(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::check_writer().
sc_get_current_process_handle()
sc_process_handle sc_core::sc_get_current_process_handle ()
Definition at line 314 of file sc_process_handle.cc.
References sc_gem5::Process::newest(), sc_is_running(), sc_core::sc_process_handle::sc_process_handle(), and sc_gem5::scheduler.
Referenced by sc_is_unwinding(), sc_core::sc_process_handle::throw_it(), and sc_dt::sc_global< T >::update().
sc_get_default_time_unit()
sc_time sc_core::sc_get_default_time_unit ()
Definition at line 392 of file sc_time.cc.
References SC_SEC, and sc_core::sc_time::sc_time().
sc_get_status()
sc_status sc_core::sc_get_status ()
Definition at line 175 of file sc_main.cc.
References AlphaISA::Kernel::kernel, and SC_ELABORATION.
Referenced by sc_gem5::Process::kill(), sc_gem5::Process::Process(), sc_gem5::Process::reset(), sc_is_running(), sc_stop(), sc_trace(), sc_trace< bool >(), sc_trace< sc_dt::sc_logic >(), and sc_gem5::Process::throw_it().
sc_get_stop_mode()
sc_stop_mode sc_core::sc_get_stop_mode ()
Definition at line 100 of file sc_main.cc.
sc_get_time_resolution()
sc_time sc_core::sc_get_time_resolution ()
Definition at line 341 of file sc_time.cc.
References sc_core::sc_time::from_value().
Referenced by sc_gem5::TraceFile::finalizeTime().
sc_get_top_level_events()
const std::vector< sc_event * > & sc_core::sc_get_top_level_events ()
Definition at line 405 of file sc_event.cc.
References sc_gem5::topLevelEvents.
sc_get_top_level_objects()
const std::vector< sc_object * > & sc_core::sc_get_top_level_objects ()
Definition at line 163 of file sc_object.cc.
References sc_gem5::topLevelObjects.
sc_hierarchical_name_exists()
bool sc_core::sc_hierarchical_name_exists (const char * name)
Definition at line 841 of file sc_module.cc.
References sc_gem5::allEvents, sc_gem5::allObjects, sc_gem5::findEvent(), and sc_gem5::findObject().
sc_interrupt_here()
void sc_core::sc_interrupt_here (const char * msg_type, sc_severity)
Definition at line 360 of file sc_report_handler.cc.
Referenced by sc_core::sc_report_handler::default_handler().
sc_is_running()
bool sc_core::sc_is_running ()
Definition at line 144 of file sc_main.cc.
References sc_get_status(), SC_PAUSED, and SC_RUNNING.
Referenced by sc_gem5::Event::Event(), sc_gem5::newCThreadProcess(), sc_gem5::newMethodProcess(), sc_gem5::newThreadProcess(), sc_core::sc_export_base::sc_export_base(), sc_get_current_process_handle(), sc_core::sc_module::sc_module(), sc_core::sc_module_name::sc_module_name(), sc_core::sc_port_base::sc_port_base(), sc_core::sc_prim_channel::sc_prim_channel(), sc_report_compose_message(), sc_set_default_time_unit(), sc_set_stop_mode(), and sc_set_time_resolution().
sc_is_unwinding()
bool sc_core::sc_is_unwinding ()
Definition at line 323 of file sc_process_handle.cc.
References sc_core::sc_process_handle::is_unwinding(), and sc_get_current_process_handle().
Referenced by sc_core::sc_process_handle::throw_it().
sc_max_time()
const sc_time & sc_core::sc_max_time ()
Definition at line 347 of file sc_time.cc.
References sc_core::sc_time::from_value(), and MaxTick.
sc_module_sc_new()
sc_module * sc_core::sc_module_sc_new (sc_module * mod)
Definition at line 860 of file sc_module.cc.
References mod().
sc_pause()
void sc_core::sc_pause ()
Definition at line 70 of file sc_main.cc.
References SC_RUNNING, sc_gem5::Scheduler::schedulePause(), sc_gem5::scheduler, and sc_gem5::Kernel::status().
Referenced by sc_start().
sc_pending_activity()
bool sc_core::sc_pending_activity ()
Definition at line 162 of file sc_main.cc.
References sc_pending_activity_at_current_time(), and sc_pending_activity_at_future_time().
sc_pending_activity_at_current_time()
bool sc_core::sc_pending_activity_at_current_time ()
Definition at line 150 of file sc_main.cc.
References sc_gem5::Scheduler::pendingCurr(), and sc_gem5::scheduler.
Referenced by sc_pending_activity().
sc_pending_activity_at_future_time()
bool sc_core::sc_pending_activity_at_future_time ()
Definition at line 156 of file sc_main.cc.
References sc_gem5::Scheduler::pendingFuture(), and sc_gem5::scheduler.
Referenced by sc_pending_activity().
sc_ref()
template<typename T > auto sc_core::sc_ref (T && v) -> decltype(std::ref(std::forward<T>(v)))
Definition at line 207 of file sc_spawn.hh.
References ArmISA::v.
Referenced by sc_cref().
sc_release()
static const char* sc_core::sc_release () inline static
Definition at line 91 of file functions.hh.
sc_report_close_default_log()
bool sc_core::sc_report_close_default_log ()
Definition at line 405 of file sc_report_handler.cc.
sc_report_compose_message()
const std::string sc_core::sc_report_compose_message (const sc_report & report)
Definition at line 372 of file sc_report_handler.cc.
References ccprintf(), sc_gem5::Scheduler::current(), sc_core::sc_report::get_file_name(), sc_core::sc_report::get_id(), sc_core::sc_report::get_line_number(), sc_core::sc_report::get_msg(), sc_core::sc_report::get_msg_type(), sc_core::sc_report::get_process_name(), sc_core::sc_report::get_severity(), sc_core::sc_report::get_time(), name(), sc_gem5::reportSeverityNames, SC_INFO, sc_is_running(), sc_gem5::scheduler, and sc_core::sc_time::to_string().
Referenced by sc_core::sc_report_handler::default_handler(), and sc_core::sc_report::sc_report().
sc_set_default_time_unit()
void sc_core::sc_set_default_time_unit (double d, sc_time_unit tu)
Definition at line 354 of file sc_time.cc.
References clockFrequencyFixed(), SimClock::Float::Hz, SC_ID_SET_DEFAULT_TIME_UNIT_, sc_is_running(), SC_PS, SC_REPORT_ERROR, sc_gem5::TimeUnitScale, and MipsISA::tu.
sc_set_location()
void sc_core::sc_set_location (const char * file, int lineno)
Definition at line 60 of file sc_process_handle.cc.
References sc_gem5::Scheduler::current(), sc_core::sc_process_b::file, sc_core::sc_process_b::lineno, and sc_gem5::scheduler.
sc_set_stop_mode()
void sc_core::sc_set_stop_mode (sc_stop_mode mode)
Definition at line 90 of file sc_main.cc.
References ArmISA::mode, SC_ID_STOP_MODE_AFTER_START_, sc_is_running(), and SC_REPORT_ERROR.
sc_set_time_resolution()
void sc_core::sc_set_time_resolution (double d, sc_time_unit tu)
Definition at line 295 of file sc_time.cc.
References clockFrequencyFixed(), ArmISA::d, SC_FS, SC_ID_DEFAULT_TIME_UNIT_CHANGED_, SC_ID_SET_TIME_RESOLUTION_, sc_is_running(), SC_REPORT_ERROR, SC_REPORT_WARNING, setClockFrequency(), sc_gem5::TimeUnitFrequency, sc_gem5::TimeUnitScale, and MipsISA::tu.
sc_signal_invalid_writer()
void sc_core::sc_signal_invalid_writer (const char * name, const char * kind, const char * first_writer, const char * second_writer)
Referenced by sc_core::sc_signal< sc_dt::sc_int< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_uint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::check_writer(), sc_core::sc_int_sigref::operator=(), sc_core::sc_unsigned_sigref::operator=(), sc_core::sc_signed_sigref::operator=(), sc_core::sc_signal< sc_dt::sc_int< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_uint< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::register_port(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::register_port().
sc_spawn() [1/2]
template<typename T > sc_process_handle sc_core::sc_spawn (T object, const char * name_p = nullptr, const sc_spawn_options * opt_p = nullptr)
Definition at line 156 of file sc_spawn.hh.
References MipsISA::p, and sc_gem5::spawnWork().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
sc_spawn() [2/2]
template<typename T > sc_process_handle sc_core::sc_spawn (typename T::result_type * r_p, T object, const char * name_p = nullptr, const sc_spawn_options * opt_p = nullptr)
Definition at line 166 of file sc_spawn.hh.
References MipsISA::p, and sc_gem5::spawnWork().
sc_start() [1/3]
static void sc_core::sc_start (double d, sc_time_unit t, sc_starvation_policy p = SC_RUN_TO_TIME) inline static
Definition at line 57 of file sc_main.hh.
References MipsISA::p, sc_pause(), and sc_start().
sc_start() [2/3]
void sc_core::sc_start ()
Definition at line 63 of file sc_main.cc.
References sc_core::sc_time::from_value(), sc_gem5::Scheduler::getCurTick(), MaxTick, SC_EXIT_ON_STARVATION, and sc_gem5::scheduler.
Referenced by sc_start().
sc_start() [3/3]
void sc_core::sc_start (const sc_time & time, sc_starvation_policy p)
Definition at line 77 of file sc_main.cc.
References sc_gem5::Scheduler::getCurTick(), MaxTick, sc_gem5::Scheduler::oneCycle(), SC_ID_SIMULATION_TIME_OVERFLOW_, SC_REPORT_ERROR, SC_RUN_TO_TIME, sc_gem5::scheduler, sc_gem5::Scheduler::start(), and sc_core::sc_time::value().
sc_start_of_simulation_invoked()
bool sc_core::sc_start_of_simulation_invoked ()
Definition at line 848 of file sc_module.cc.
References AlphaISA::Kernel::kernel.
sc_stop()
void sc_core::sc_stop ()
Definition at line 106 of file sc_main.cc.
References sc_get_status(), SC_ID_SIMULATION_STOP_CALLED_TWICE_, SC_REPORT_WARNING, SC_RUNNING, SC_STOP_FINISH_DELTA, SC_STOPPED, sc_gem5::scheduler, sc_gem5::Scheduler::scheduleStop(), sc_gem5::Kernel::status(), and sc_gem5::Kernel::stop().
Referenced by sc_core::sc_report_handler::default_handler(), and SC_MODULE().
sc_stop_here()
void sc_core::sc_stop_here (const char * msg_type, sc_severity)
Definition at line 366 of file sc_report_handler.cc.
Referenced by sc_core::sc_report_handler::default_handler().
sc_time_stamp()
const sc_time & sc_core::sc_time_stamp ()
Definition at line 130 of file sc_main.cc.
References sc_core::sc_time::from_value(), SC_SEC, and sc_gem5::scheduler.
Referenced by sc_core::sc_event_queue::_trigger(), SimpleLTTarget1::b_transport(), tlm::tlm_global_quantum::compute_local_quantum(), MultiSocketSimpleSwitchAT::dump_status(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::fec(), tlm_utils::tlm_quantumkeeper::get_current_time(), tlm_utils::peq_with_get< transaction_type >::get_next_transaction(), SimpleLTInitiator1_dmi::invalidate_direct_mem_ptr(), SimpleLTInitiator_ext::invalidate_direct_mem_ptr(), SimpleLTInitiator2::logEndTransaction(), SimpleLTInitiator3::logEndTransaction(), SimpleLTInitiator1::logEndTransaction(), CoreDecouplingLTInitiator::logEndTransaction(), SimpleLTInitiator3_dmi::logEndTransaction(), SimpleLTInitiator_ext::logEndTransaction(), SimpleLTInitiator1_dmi::logEndTransaction(), SimpleLTInitiator2_dmi::logEndTransaction(), SimpleATInitiator2::logEndTransaction(), SimpleATInitiator1::logEndTransaction(), SimpleLTInitiator2::logStartTransation(), SimpleLTInitiator3::logStartTransation(), CoreDecouplingLTInitiator::logStartTransation(), SimpleLTInitiator1::logStartTransation(), SimpleLTInitiator_ext::logStartTransation(), SimpleLTInitiator3_dmi::logStartTransation(), SimpleLTInitiator1_dmi::logStartTransation(), SimpleLTInitiator2_dmi::logStartTransation(), SimpleATInitiator2::logStartTransation(), SimpleATInitiator1::logStartTransation(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), tlm_utils::tlm_quantumkeeper::need_sync(), tlm_utils::peq_with_get< transaction_type >::notify(), sc_core::sc_event_queue::notify(), Gem5SystemC::PayloadEvent< OWNER >::notify(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::notify(), tlm_utils::tlm_quantumkeeper::reset(), SC_MODULE(), and sc_core::sc_clock::time_stamp().
sc_time_to_pending_activity()
sc_time sc_core::sc_time_to_pending_activity ()
Definition at line 169 of file sc_main.cc.
References sc_core::sc_time::from_value(), and sc_gem5::scheduler.
sc_trace() [1/60]
void sc_core::sc_trace (sc_trace_file * tf, const bool & v, const std::string & name)
Definition at line 77 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [2/60]
void sc_core::sc_trace (sc_trace_file * tf, const bool * v, const std::string & name)
Definition at line 83 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [3/60]
void sc_core::sc_trace (sc_trace_file * tf, const float & v, const std::string & name)
Definition at line 89 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [4/60]
void sc_core::sc_trace (sc_trace_file * tf, const float * v, const std::string & name)
Definition at line 95 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [5/60]
void sc_core::sc_trace (sc_trace_file * tf, const double & v, const std::string & name)
Definition at line 101 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [6/60]
void sc_core::sc_trace (sc_trace_file * tf, const double * v, const std::string & name)
Definition at line 107 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [7/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_logic & v, const std::string & name)
Definition at line 113 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [8/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_logic * v, const std::string & name)
Definition at line 119 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [9/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_int_base & v, const std::string & name)
Definition at line 125 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [10/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_int_base * v, const std::string & name)
Definition at line 132 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [11/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_uint_base & v, const std::string & name)
Definition at line 139 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [12/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_uint_base * v, const std::string & name)
Definition at line 146 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [13/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_signed & v, const std::string & name)
Definition at line 153 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [14/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_signed * v, const std::string & name)
Definition at line 160 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [15/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_unsigned & v, const std::string & name)
Definition at line 167 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [16/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_unsigned * v, const std::string & name)
Definition at line 174 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [17/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_bv_base & v, const std::string & name)
Definition at line 181 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [18/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_bv_base * v, const std::string & name)
Definition at line 188 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [19/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_lv_base & v, const std::string & name)
Definition at line 195 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [20/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_lv_base * v, const std::string & name)
Definition at line 202 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [21/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxval & v, const std::string & name)
Definition at line 209 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [22/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxval * v, const std::string & name)
Definition at line 215 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [23/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxval_fast & v, const std::string & name)
Definition at line 221 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [24/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxval_fast * v, const std::string & name)
Definition at line 228 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [25/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxnum & v, const std::string & name)
Definition at line 235 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [26/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxnum * v, const std::string & name)
Definition at line 241 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [27/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxnum_fast & v, const std::string & name)
Definition at line 247 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [28/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::sc_fxnum_fast * v, const std::string & name)
Definition at line 254 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [29/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_event & v, const std::string & name)
Definition at line 261 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [30/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_event * v, const std::string & name)
Definition at line 267 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [31/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_time & v, const std::string & name)
Definition at line 273 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [32/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_time * v, const std::string & name)
Definition at line 279 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [33/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned char & v, const std::string & name, int width = (8 * sizeof(unsigned char)))
Definition at line 285 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [34/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned char * v, const std::string & name, int width = (8 * sizeof(unsigned char)))
Definition at line 292 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [35/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned short & v, const std::string & name, int width = (8 * sizeof(unsigned short)))
Definition at line 299 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [36/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned short * v, const std::string & name, int width = (8 * sizeof(unsigned short)))
Definition at line 306 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [37/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned int & v, const std::string & name, int width = (8 * sizeof(unsigned int)))
Definition at line 313 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [38/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned int * v, const std::string & name, int width = (8 * sizeof(unsigned int)))
Definition at line 320 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [39/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned long & v, const std::string & name, int width = (8 * sizeof(unsigned long)))
Definition at line 327 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [40/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned long * v, const std::string & name, int width = (8 * sizeof(unsigned long)))
Definition at line 334 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [41/60]
void sc_core::sc_trace (sc_trace_file * tf, const char & v, const std::string & name, int width = (8 * sizeof(char)))
Definition at line 341 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [42/60]
void sc_core::sc_trace (sc_trace_file * tf, const char * v, const std::string & name, int width = (8 * sizeof(char)))
Definition at line 347 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [43/60]
void sc_core::sc_trace (sc_trace_file * tf, const short & v, const std::string & name, int width = (8 * sizeof(short)))
Definition at line 353 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [44/60]
void sc_core::sc_trace (sc_trace_file * tf, const short * v, const std::string & name, int width = (8 * sizeof(short)))
Definition at line 360 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [45/60]
void sc_core::sc_trace (sc_trace_file * tf, const int & v, const std::string & name, int width = (8 * sizeof(int)))
Definition at line 367 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [46/60]
void sc_core::sc_trace (sc_trace_file * tf, const int * v, const std::string & name, int width = (8 * sizeof(int)))
Definition at line 373 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [47/60]
void sc_core::sc_trace (sc_trace_file * tf, const long & v, const std::string & name, int width = (8 * sizeof(long)))
Definition at line 379 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [48/60]
template<class T > void sc_core::sc_trace (sc_trace_file * tf, const sc_in< T > & i, const std::string & name) inline
Definition at line 158 of file sc_in.hh.
References sc_core::sc_object::name(), sc_get_status(), and SC_START_OF_SIMULATION.
Referenced by sc_core::sc_in< sc_dt::sc_lv< W > >::end_of_elaboration(), sc_core::sc_in< bool >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_logic >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_bigint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::end_of_elaboration(), sc_trace< bool >(), and sc_trace< sc_dt::sc_logic >().
sc_trace() [49/60]
void sc_core::sc_trace (sc_trace_file * tf, const long * v, const std::string & name, int width = (8 * sizeof(long)))
Definition at line 385 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [50/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::int64 & v, const std::string & name, int width = (8 * sizeof(sc_dt::int64)))
Definition at line 391 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [51/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::int64 * v, const std::string & name, int width = (8 * sizeof(sc_dt::int64)))
Definition at line 398 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [52/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::uint64 & v, const std::string & name, int width = (8 * sizeof(sc_dt::uint64)))
Definition at line 405 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [53/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_dt::uint64 * v, const std::string & name, int width = (8 * sizeof(sc_dt::uint64)))
Definition at line 412 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [54/60]
void sc_core::sc_trace (sc_trace_file * tf, const unsigned int & v, const std::string & name, const char ** enum_literals)
Definition at line 451 of file sc_trace_file.cc.
References X86ISA::tf.
sc_trace() [55/60]
template<class T > void sc_core::sc_trace (sc_trace_file * tf, const sc_signal_in_if< T > & iface, const std::string & name)
Definition at line 179 of file sc_trace_file.hh.
References name(), sc_core::sc_signal_in_if< T >::read(), sc_trace(), and ArmISA::width.
sc_trace() [56/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_signal_in_if< char > & v, const std::string & name, int width)
Definition at line 419 of file sc_trace_file.cc.
References name(), sc_core::sc_signal_in_if< T >::read(), X86ISA::tf, and ArmISA::width.
sc_trace() [57/60]
template<class T > void sc_core::sc_trace (sc_trace_file * tf, const sc_inout< T > & i, const std::string & name) inline
Definition at line 186 of file sc_inout.hh.
References sc_core::sc_inout< T >::add_trace(), name(), sc_core::sc_inout< T >::read(), sc_get_status(), and SC_START_OF_SIMULATION.
Referenced by sc_core::sc_inout< sc_dt::sc_lv< W > >::end_of_elaboration(), sc_core::sc_inout< bool >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_logic >::end_of_elaboration(), sc_trace< bool >(), and sc_trace< sc_dt::sc_logic >().
sc_trace() [58/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_signal_in_if< short > & v, const std::string & name, int width)
Definition at line 427 of file sc_trace_file.cc.
References name(), sc_core::sc_signal_in_if< T >::read(), X86ISA::tf, and ArmISA::width.
sc_trace() [59/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_signal_in_if< int > & v, const std::string & name, int width)
Definition at line 435 of file sc_trace_file.cc.
References name(), sc_core::sc_signal_in_if< T >::read(), X86ISA::tf, and ArmISA::width.
sc_trace() [60/60]
void sc_core::sc_trace (sc_trace_file * tf, const sc_signal_in_if< long > & v, const std::string & name, int width)
Definition at line 443 of file sc_trace_file.cc.
References name(), sc_core::sc_signal_in_if< T >::read(), X86ISA::tf, and ArmISA::width.
Referenced by sc_trace().
sc_trace< bool >() [1/2]
template<> void sc_core::sc_trace< bool > (sc_trace_file * tf, const sc_in< bool > & i, const std::string & name) inline
Definition at line 320 of file sc_in.hh.
References sc_core::sc_object::name(), sc_get_status(), SC_START_OF_SIMULATION, and sc_trace().
sc_trace< bool >() [2/2]
template<> void sc_core::sc_trace< bool > (sc_trace_file * tf, const sc_inout< bool > & i, const std::string & name) inline
Definition at line 358 of file sc_inout.hh.
References name(), sc_get_status(), SC_START_OF_SIMULATION, and sc_trace().
sc_trace< sc_dt::sc_logic >() [1/2]
template<> void sc_core::sc_trace< sc_dt::sc_logic > (sc_trace_file * tf, const sc_in< sc_dt::sc_logic > & i, const std::string & name) inline
Definition at line 481 of file sc_in.hh.
References sc_core::sc_object::name(), sc_get_status(), SC_START_OF_SIMULATION, and sc_trace().
sc_trace< sc_dt::sc_logic >() [2/2]
template<> void sc_core::sc_trace< sc_dt::sc_logic > (sc_trace_file * tf, const sc_inout< sc_dt::sc_logic > & i, const std::string & name) inline
Definition at line 550 of file sc_inout.hh.
References name(), sc_get_status(), SC_START_OF_SIMULATION, and sc_trace().
sc_trace_delta_cycles()
void sc_core::sc_trace_delta_cycles (sc_trace_file * tf, bool on = true)
Definition at line 459 of file sc_trace_file.cc.
References X86ISA::tf.
sc_version()
const char * sc_core::sc_version ()
Definition at line 46 of file functions.cc.
References SC_VERSION.
Referenced by sc_gem5::VcdTraceFile::initialize(), and sc_copyright().
sc_write_comment()
void sc_core::sc_write_comment (sc_trace_file * tf, const std::string & comment)
Definition at line 71 of file sc_trace_file.cc.
References X86ISA::tf.
timed_out()
bool sc_core::timed_out ()
Definition at line 628 of file sc_module.cc.
References sc_gem5::Scheduler::current(), MipsISA::p, sc_gem5::Process::procKind(), SC_ID_WAIT_NOT_ALLOWED_, SC_METHOD_PROC_, SC_REPORT_ERROR, sc_gem5::scheduler, and sc_gem5::Process::timedOut().
Referenced by sc_core::sc_module::operator=(), sc_core::sc_prim_channel::timed_out(), sc_core::sc_module::timed_out(), and sc_core::sc_prim_channel::update().
wait() [1/13]
void sc_core::wait ()
Definition at line 655 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Process::clearDynamic(), sc_gem5::Scheduler::current(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Scheduler::yield().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm::tlm_fifo< T >::get(), sc_core::sc_mutex::lock(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), RandomGen::nextPacketTick(), LinearGen::nextPacketTick(), sc_core::sc_module::operator=(), tlm::tlm_fifo< T >::peek(), tlm::tlm_fifo< T >::put(), sc_core::sc_fifo< T >::read(), SC_MODULE(), tlm_utils::tlm_quantumkeeper::sync(), sc_core::sc_prim_channel::update(), sc_core::sc_semaphore::wait(), sc_core::sc_join::wait(), sc_dp::sc_barrier::wait(), sc_core::sc_prim_channel::wait(), sc_core::sc_join::wait_clocked(), and sc_core::sc_fifo< T >::write().
wait() [2/13]
void sc_core::wait (int n)
Definition at line 666 of file sc_module.cc.
References csprintf(), sc_gem5::Scheduler::current(), MipsISA::p, SC_ID_WAIT_N_INVALID_, SC_REPORT_ERROR, sc_gem5::scheduler, sc_core::sc_module::wait(), and sc_gem5::Process::waitCount().
wait() [3/13]
void sc_core::wait (const sc_event & e)
Definition at line 678 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEvent(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Scheduler::yield().
wait() [4/13]
void sc_core::wait (const sc_event_or_list & eol)
Definition at line 689 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventOrList(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Scheduler::yield().
wait() [5/13]
void sc_core::wait (const sc_event_and_list & eal)
Definition at line 700 of file sc_module.cc.
References sc_gem5::Process::cancelTimeout(), sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventAndList(), MipsISA::p, sc_gem5::scheduler, and sc_gem5::Scheduler::yield().
wait() [6/13]
void sc_core::wait (const sc_time & t)
Definition at line 711 of file sc_module.cc.
References sc_gem5::Process::clearDynamic(), sc_gem5::Scheduler::current(), MipsISA::p, sc_gem5::scheduler, sc_gem5::Process::setTimeout(), and sc_gem5::Scheduler::yield().
wait() [7/13]
void sc_core::wait (double d, sc_time_unit u)
Definition at line 722 of file sc_module.cc.
References sc_core::sc_module::wait().
wait() [8/13]
void sc_core::wait (const sc_time & t, const sc_event & e)
Definition at line 728 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEvent(), MipsISA::p, sc_gem5::scheduler, sc_gem5::Process::setTimeout(), and sc_gem5::Scheduler::yield().
wait() [9/13]
void sc_core::wait (double d, sc_time_unit u, const sc_event & e)
Definition at line 739 of file sc_module.cc.
References sc_core::sc_module::wait().
wait() [10/13]
void sc_core::wait (const sc_time & t, const sc_event_or_list & eol)
Definition at line 745 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventOrList(), MipsISA::p, sc_gem5::scheduler, sc_gem5::Process::setTimeout(), and sc_gem5::Scheduler::yield().
wait() [11/13]
void sc_core::wait (double d, sc_time_unit u, const sc_event_or_list & eol)
Definition at line 756 of file sc_module.cc.
References sc_core::sc_module::wait().
wait() [12/13]
void sc_core::wait (const sc_time & t, const sc_event_and_list & eal)
Definition at line 762 of file sc_module.cc.
References sc_gem5::Scheduler::current(), sc_gem5::newDynamicSensitivityEventAndList(), MipsISA::p, sc_gem5::scheduler, sc_gem5::Process::setTimeout(), and sc_gem5::Scheduler::yield().
wait() [13/13]
void sc_core::wait (double d, sc_time_unit u, const sc_event_and_list & eal)
Definition at line 773 of file sc_module.cc.
References sc_core::sc_module::wait().
Referenced by halt(), and sc_core::sc_module::wait().
Variable Documentation
sc_allow_process_control_corners
bool sc_core::sc_allow_process_control_corners
Definition at line 328 of file sc_process_handle.cc.
Referenced by sc_gem5::Process::disable(), and sc_core::sc_process_handle::throw_it().
SC_BIND_PROXY_NIL
const sc_bind_proxy sc_core::SC_BIND_PROXY_NIL
Definition at line 116 of file sc_module.cc.
Referenced by sc_core::sc_bind_proxy::port().
sc_copyright_string
const std::string sc_core::sc_copyright_string = SC_COPYRIGHT
Definition at line 43 of file functions.cc.
SC_ID_ABORT_
const char sc_core::SC_ID_ABORT_ = "simulation aborted"
Definition at line 43 of file messages.cc.
SC_ID_ASSERTION_FAILED_
const char sc_core::SC_ID_ASSERTION_FAILED_ = "assertion failed"
Definition at line 41 of file messages.cc.
Referenced by sc_dt::print_other().
SC_ID_ASSIGNMENT_FAILED_
const char sc_core::SC_ID_ASSIGNMENT_FAILED_ = "assignment failed"
Definition at line 37 of file messages.cc.
SC_ID_ATTEMPT_TO_BIND_CLOCK_TO_OUTPUT_
const char sc_core::SC_ID_ATTEMPT_TO_BIND_CLOCK_TO_OUTPUT_
Initial value:
=
    "attempted to bind sc_clock instance to sc_inout or sc_out"
Definition at line 77 of file messages.cc.
SC_ID_ATTEMPT_TO_WRITE_TO_CLOCK_
const char sc_core::SC_ID_ATTEMPT_TO_WRITE_TO_CLOCK_
Initial value:
=
    "attempt to write the value of an sc_clock instance"
Definition at line 71 of file messages.cc.
SC_ID_BACK_ON_EMPTY_LIST_
const char sc_core::SC_ID_BACK_ON_EMPTY_LIST_
Initial value:
=
    "attempt to take back() on an empty list"
Definition at line 48 of file messages.cc.
SC_ID_BAD_SC_MODULE_CONSTRUCTOR_
const char sc_core::SC_ID_BAD_SC_MODULE_CONSTRUCTOR_
Initial value:
=
    "sc_module(const char*), sc_module(const std::string&) "
    "have been deprecated, use sc_module(const sc_module_name&)"
Definition at line 153 of file messages.cc.
Referenced by sc_core::sc_module::sc_module().
SC_ID_BIND_IF_TO_PORT_
const char sc_core::SC_ID_BIND_IF_TO_PORT_ = "bind interface to port failed"
Definition at line 46 of file messages.cc.
Referenced by sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::_gem5AddInterface(), and sc_core::sc_fifo< T >::register_port().
SC_ID_BIND_PORT_TO_PORT_
const char sc_core::SC_ID_BIND_PORT_TO_PORT_ = "bind parent port to port failed"
Definition at line 47 of file messages.cc.
SC_ID_CANNOT_CONVERT_
const char sc_core::SC_ID_CANNOT_CONVERT_ = "cannot perform conversion"
Definition at line 39 of file messages.cc.
Referenced by sc_dt::sc_bv_base::assign_from_string(), and sc_dt::convert_to_bin().
SC_ID_CLOCK_HIGH_TIME_ZERO_
const char sc_core::SC_ID_CLOCK_HIGH_TIME_ZERO_ = "sc_clock high time is zero"
Definition at line 38 of file messages.cc.
Referenced by sc_core::sc_clock::sc_clock().
SC_ID_CLOCK_LOW_TIME_ZERO_
const char sc_core::SC_ID_CLOCK_LOW_TIME_ZERO_ = "sc_clock low time is zero"
Definition at line 39 of file messages.cc.
Referenced by sc_core::sc_clock::sc_clock().
SC_ID_CLOCK_PERIOD_ZERO_
const char sc_core::SC_ID_CLOCK_PERIOD_ZERO_ = "sc_clock period is zero"
Definition at line 37 of file messages.cc.
Referenced by sc_core::sc_clock::sc_clock().
SC_ID_COMPLETE_BINDING_
const char sc_core::SC_ID_COMPLETE_BINDING_ = "complete binding failed"
Definition at line 48 of file messages.cc.
Referenced by sc_gem5::Port::finalize().
SC_ID_CONTEXT_BEGIN_FAILED_
const char sc_core::SC_ID_CONTEXT_BEGIN_FAILED_ = "context begin failed"
Definition at line 45 of file messages.cc.
Referenced by sc_dt::sc_context< T >::begin().
SC_ID_CONTEXT_END_FAILED_
const char sc_core::SC_ID_CONTEXT_END_FAILED_ = "context end failed"
Definition at line 46 of file messages.cc.
Referenced by sc_dt::sc_context< T >::end().
SC_ID_CONVERSION_FAILED_
const char sc_core::SC_ID_CONVERSION_FAILED_ = "conversion failed"
Definition at line 39 of file messages.cc.
Referenced by sc_dt::get_base_and_sign(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), sc_dt::parse_binary_bits(), sc_dt::parse_hex_bits(), sc_dt::vec_from_str(), and sc_dt::vec_reverse().
SC_ID_CYCLE_MISSES_EVENTS_
const char sc_core::SC_ID_CYCLE_MISSES_EVENTS_
Initial value:
=
    "the simulation contains timed-events but they are "
    "ignored by sc_cycle() ==> the simulation will be "
    "incorrect"
Definition at line 95 of file messages.cc.
SC_ID_DEFAULT_TIME_UNIT_CHANGED_
const char sc_core::SC_ID_DEFAULT_TIME_UNIT_CHANGED_
Initial value:
=
    "default time unit changed to time resolution"
Definition at line 60 of file messages.cc.
Referenced by sc_set_time_resolution().
SC_ID_DISABLE_WILL_ORPHAN_PROCESS_
const char sc_core::SC_ID_DISABLE_WILL_ORPHAN_PROCESS_
Initial value:
=
    "disable() or dont_initialize() called on process with no static "
    "sensitivity, it will be orphaned"
Definition at line 134 of file messages.cc.
Referenced by sc_gem5::Scheduler::initPhase(), and sc_gem5::spawnWork().
SC_ID_DONT_INITIALIZE_
const char sc_core::SC_ID_DONT_INITIALIZE_
Initial value:
=
    "dont_initialize() has no effect for SC_CTHREADs"
Definition at line 73 of file messages.cc.
Referenced by sc_core::sc_module::dont_initialize().
SC_ID_EMPTY_PROCESS_HANDLE_
const char sc_core::SC_ID_EMPTY_PROCESS_HANDLE_
Initial value:
=
    "attempt to use an empty process handle ignored"
Definition at line 156 of file messages.cc.
Referenced by sc_core::sc_process_handle::disable(), sc_core::sc_process_handle::enable(), sc_core::sc_process_handle::is_unwinding(), sc_core::sc_process_handle::kill(), sc_core::sc_process_handle::reset(), sc_core::sc_process_handle::reset_event(), sc_core::sc_process_handle::resume(), sc_core::sc_process_handle::suspend(), sc_core::sc_process_handle::sync_reset_off(), sc_core::sc_process_handle::sync_reset_on(), sc_core::sc_process_handle::terminated_event(), and sc_core::sc_process_handle::throw_it().
SC_ID_END_MODULE_NOT_CALLED_
const char sc_core::SC_ID_END_MODULE_NOT_CALLED_
Initial value:
=
    "module construction not properly completed: did "
    "you forget to add a sc_module_name parameter to "
    "your module constructor?"
Definition at line 47 of file messages.cc.
Referenced by sc_gem5::Module::endOfElaboration().
SC_ID_EVENT_LIST_FAILED_
const char sc_core::SC_ID_EVENT_LIST_FAILED_
Initial value:
=
    "invalid use of sc_(and|or)_event list"
Definition at line 147 of file messages.cc.
SC_ID_EVENT_ON_NULL_PROCESS_
const char sc_core::SC_ID_EVENT_ON_NULL_PROCESS_
Initial value:
=
    "Attempt to get an event for non-existent process"
Definition at line 145 of file messages.cc.
SC_ID_EXPORT_OUTSIDE_MODULE_
const char sc_core::SC_ID_EXPORT_OUTSIDE_MODULE_
Initial value:
=
    "sc_export specified outside of module"
Definition at line 65 of file messages.cc.
Referenced by sc_core::sc_export_base::sc_export_base().
SC_ID_FIND_EVENT_
const char sc_core::SC_ID_FIND_EVENT_ = "find event failed"
Definition at line 59 of file messages.cc.
Referenced by tlm::tlm_event_finder_t< IF, T >::find_event(), and sc_core::sc_event_finder_t< sc_core::sc_signal_inout_if< bool > >::find_event().
SC_ID_FRONT_ON_EMPTY_LIST_
const char sc_core::SC_ID_FRONT_ON_EMPTY_LIST_
Initial value:
=
    "attempt to take front() on an empty list"
Definition at line 46 of file messages.cc.
SC_ID_GEN_UNIQUE_NAME_
const char sc_core::SC_ID_GEN_UNIQUE_NAME_
Initial value:
=
    "cannot generate unique name from null string"
Definition at line 84 of file messages.cc.
Referenced by sc_gen_unique_name().
SC_ID_GET_IF_
const char sc_core::SC_ID_GET_IF_ = "get interface failed"
Definition at line 51 of file messages.cc.
Referenced by sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::_gem5Interface(), sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::operator->(), and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::operator[]().
SC_ID_HALT_NOT_ALLOWED_
const char sc_core::SC_ID_HALT_NOT_ALLOWED_ = "halt() is only allowed in SC_CTHREADs"
Definition at line 70 of file messages.cc.
SC_ID_HIER_NAME_INCORRECT_
const char sc_core::SC_ID_HIER_NAME_INCORRECT_
Initial value:
=
    "hierarchical name as shown may be incorrect due to previous errors"
Definition at line 51 of file messages.cc.
SC_ID_IEEE_1666_DEPRECATION_
const char sc_core::SC_ID_IEEE_1666_DEPRECATION_
Initial value:
=
    "/IEEE_Std_1666/deprecated"
Definition at line 50 of file messages.cc.
Referenced by sc_dt::sc_deprecated_sc_bit(), and sc_core::sc_port_base::warn_port_constructor().
SC_ID_ILLEGAL_CHARACTERS_
const char sc_core::SC_ID_ILLEGAL_CHARACTERS_ = "illegal characters"
Definition at line 42 of file messages.cc.
SC_ID_IMMEDIATE_NOTIFICATION_
const char sc_core::SC_ID_IMMEDIATE_NOTIFICATION_
Initial value:
=
    "immediate notification is not allowed during update phase or elaboration"
Definition at line 68 of file messages.cc.
Referenced by sc_gem5::Event::notify().
SC_ID_IMMEDIATE_SELF_NOTIFICATION_
const char sc_core::SC_ID_IMMEDIATE_SELF_NOTIFICATION_
Initial value:
=
    "immediate self-notification ignored as of IEEE 1666-2011"
Definition at line 91 of file messages.cc.
Referenced by sc_gem5::Sensitivity::notify().
SC_ID_INCOMPATIBLE_TYPES_
const char sc_core::SC_ID_INCOMPATIBLE_TYPES_ = "incompatible types"
Definition at line 38 of file messages.cc.
SC_ID_INCOMPATIBLE_VECTORS_
const char sc_core::SC_ID_INCOMPATIBLE_VECTORS_ = "incompatible vectors"
Definition at line 40 of file messages.cc.
SC_ID_INCONSISTENT_API_CONFIG_
const char sc_core::SC_ID_INCONSISTENT_API_CONFIG_
Initial value:
=
    "inconsistent library configuration detected"
Definition at line 62 of file messages.cc.
SC_ID_INIT_FAILED_
const char sc_core::SC_ID_INIT_FAILED_ = "initialization failed"
Definition at line 36 of file messages.cc.
Referenced by sc_dt::sc_unsigned::invalid_init(), and sc_dt::sc_signed::invalid_init().
SC_ID_INSERT_EXPORT_
const char sc_core::SC_ID_INSERT_EXPORT_ = "insert sc_export failed"
Definition at line 64 of file messages.cc.
Referenced by sc_core::sc_export_base::sc_export_base().
SC_ID_INSERT_MODULE_
const char sc_core::SC_ID_INSERT_MODULE_ = "insert module failed"
Definition at line 79 of file messages.cc.
Referenced by sc_core::sc_module::sc_module(), and sc_core::sc_module_name::sc_module_name().
SC_ID_INSERT_PORT_
const char sc_core::SC_ID_INSERT_PORT_ = "insert port failed"
Definition at line 49 of file messages.cc.
Referenced by sc_core::sc_port_base::sc_port_base().
SC_ID_INSERT_PRIM_CHANNEL_
const char sc_core::SC_ID_INSERT_PRIM_CHANNEL_ = "insert primitive channel failed"
Definition at line 52 of file messages.cc.
Referenced by sc_core::sc_prim_channel::sc_prim_channel().
SC_ID_INSTANCE_EXISTS_
const char sc_core::SC_ID_INSTANCE_EXISTS_ = "object already exists"
Definition at line 41 of file messages.cc.
Referenced by sc_gem5::Event::Event(), and sc_gem5::Object::Object().
SC_ID_INTERNAL_ERROR_
const char sc_core::SC_ID_INTERNAL_ERROR_ = "internal error"
Definition at line 40 of file messages.cc.
SC_ID_INVALID_CTE_WL_
const char sc_core::SC_ID_INVALID_CTE_WL_ = "constant wordlength <= 0 is not valid"
Definition at line 39 of file messages.cc.
SC_ID_INVALID_DIV_WL_
const char sc_core::SC_ID_INVALID_DIV_WL_ = "division wordlength <= 0 is not valid"
Definition at line 38 of file messages.cc.
SC_ID_INVALID_FIFO_SIZE_
const char sc_core::SC_ID_INVALID_FIFO_SIZE_
Initial value:
=
    "sc_fifo<T> must have a size of at least 1"
Definition at line 44 of file messages.cc.
SC_ID_INVALID_FX_VALUE_
const char sc_core::SC_ID_INVALID_FX_VALUE_ = "invalid fixed-point value"
Definition at line 42 of file messages.cc.
Referenced by sc_dt::sc_fxnum::cast(), sc_dt::sc_fxnum_fast::cast(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_unsigned::operator=(), and sc_dt::sc_signed::operator=().
SC_ID_INVALID_MAX_WL_
const char sc_core::SC_ID_INVALID_MAX_WL_
Initial value:
=
    "maximum wordlength <= 0 and != -1 is not valid"
Definition at line 40 of file messages.cc.
SC_ID_INVALID_N_BITS_
const char sc_core::SC_ID_INVALID_N_BITS_ = "number of bits < 0 is not valid"
Definition at line 37 of file messages.cc.
SC_ID_INVALID_O_MODE_
const char sc_core::SC_ID_INVALID_O_MODE_ = "invalid overflow mode"
Definition at line 43 of file messages.cc.
Referenced by sc_dt::scfx_params::scfx_params().
SC_ID_INVALID_SEMAPHORE_VALUE_
const char sc_core::SC_ID_INVALID_SEMAPHORE_VALUE_
Initial value:
=
    "sc_semaphore requires an initial value >= 0"
Definition at line 60 of file messages.cc.
Referenced by sc_core::sc_semaphore::sc_semaphore().
SC_ID_INVALID_WL_
const char sc_core::SC_ID_INVALID_WL_ = "total wordlength <= 0 is not valid"
Definition at line 36 of file messages.cc.
SC_ID_JOIN_ON_METHOD_HANDLE_
const char sc_core::SC_ID_JOIN_ON_METHOD_HANDLE_
Initial value:
=
    "Attempt to register method process with sc_join object"
Definition at line 141 of file messages.cc.
Referenced by sc_core::sc_join::add_process().
SC_ID_KILL_PROCESS_WHILE_UNITIALIZED_
const char sc_core::SC_ID_KILL_PROCESS_WHILE_UNITIALIZED_
Initial value:
=
    "a process may not be killed before it is initialized"
Definition at line 160 of file messages.cc.
Referenced by sc_gem5::Process::kill().
SC_ID_LENGTH_MISMATCH_
const char sc_core::SC_ID_LENGTH_MISMATCH_
Initial value:
=
    "length mismatch in bit/logic vector assignment"
Definition at line 36 of file messages.cc.
SC_ID_LOGIC_X_TO_BOOL_
const char sc_core::SC_ID_LOGIC_X_TO_BOOL_
Initial value:
=
    "sc_logic value 'X' cannot be converted to bool"
Definition at line 52 of file messages.cc.
Referenced by sc_dt::sc_logic::invalid_01().
SC_ID_LOGIC_Z_TO_BOOL_
const char sc_core::SC_ID_LOGIC_Z_TO_BOOL_
Initial value:
=
    "sc_logic value 'Z' cannot be converted to bool"
Definition at line 50 of file messages.cc.
Referenced by sc_dt::sc_logic::invalid_01().
SC_ID_MAKE_SENSITIVE_
const char sc_core::SC_ID_MAKE_SENSITIVE_ = "make sensitive failed"
Definition at line 76 of file messages.cc.
SC_ID_MAKE_SENSITIVE_NEG_
const char sc_core::SC_ID_MAKE_SENSITIVE_NEG_ = "make sensitive neg failed"
Definition at line 78 of file messages.cc.
SC_ID_MAKE_SENSITIVE_POS_
const char sc_core::SC_ID_MAKE_SENSITIVE_POS_ = "make sensitive pos failed"
Definition at line 77 of file messages.cc.
SC_ID_METHOD_TERMINATION_EVENT_
const char sc_core::SC_ID_METHOD_TERMINATION_EVENT_
Initial value:
=
    "Attempt to get terminated event for a method process"
Definition at line 139 of file messages.cc.
SC_ID_MODULE_CTHREAD_AFTER_START_
const char sc_core::SC_ID_MODULE_CTHREAD_AFTER_START_
Initial value:
=
    "call to SC_CTHREAD in sc_module while simulation running"
Definition at line 107 of file messages.cc.
Referenced by sc_gem5::newCThreadProcess().
SC_ID_MODULE_METHOD_AFTER_START_
const char sc_core::SC_ID_MODULE_METHOD_AFTER_START_
Initial value:
=
    "call to SC_METHOD in sc_module while simulation running"
Definition at line 103 of file messages.cc.
Referenced by sc_gem5::newMethodProcess().
SC_ID_MODULE_NAME_STACK_EMPTY_
const char sc_core::SC_ID_MODULE_NAME_STACK_EMPTY_
Initial value:
=
    "module name stack is empty: did you forget to "
    "add a sc_module_name parameter to your module "
    "constructor?"
Definition at line 86 of file messages.cc.
Referenced by sc_gem5::newModuleChecked().
SC_ID_MODULE_THREAD_AFTER_START_
const char sc_core::SC_ID_MODULE_THREAD_AFTER_START_
Initial value:
=
    "call to SC_THREAD in sc_module while simulation running"
Definition at line 105 of file messages.cc.
Referenced by sc_gem5::newThreadProcess().
SC_ID_MORE_THAN_ONE_FIFO_READER_
const char sc_core::SC_ID_MORE_THAN_ONE_FIFO_READER_
Initial value:
=
    "sc_fifo<T> cannot have more than one reader"
Definition at line 40 of file messages.cc.
Referenced by sc_core::sc_fifo< T >::register_port().
SC_ID_MORE_THAN_ONE_FIFO_WRITER_
const char sc_core::SC_ID_MORE_THAN_ONE_FIFO_WRITER_
Initial value:
=
    "sc_fifo<T> cannot have more than one writer"
Definition at line 42 of file messages.cc.
Referenced by sc_core::sc_fifo< T >::register_port().
SC_ID_MORE_THAN_ONE_SIGNAL_DRIVER_
const char sc_core::SC_ID_MORE_THAN_ONE_SIGNAL_DRIVER_
Initial value:
=
    "sc_signal<T> cannot have more than one driver"
Definition at line 54 of file messages.cc.
Referenced by sc_gem5::ScSignalBaseBinary::_signalNegedge().
SC_ID_NAME_EXISTS_
const char sc_core::SC_ID_NAME_EXISTS_ = "name already exists"
Definition at line 90 of file messages.cc.
SC_ID_NEGATIVE_SIMULATION_TIME_
const char sc_core::SC_ID_NEGATIVE_SIMULATION_TIME_
Initial value:
=
    "negative simulation interval specified in sc_start call"
Definition at line 151 of file messages.cc.
SC_ID_NEXT_TRIGGER_NOT_ALLOWED_
const char sc_core::SC_ID_NEXT_TRIGGER_NOT_ALLOWED_
Initial value:
=
    "next_trigger() is only allowed in SC_METHODs"
Definition at line 66 of file messages.cc.
SC_ID_NO_ASYNC_UPDATE_
const char sc_core::SC_ID_NO_ASYNC_UPDATE_
Initial value:
=
    "this build has no asynchronous update support"
Definition at line 79 of file messages.cc.
SC_ID_NO_BOOL_RETURNED_
const char sc_core::SC_ID_NO_BOOL_RETURNED_ = "operator does not return boolean"
Definition at line 36 of file messages.cc.
SC_ID_NO_DEFAULT_EVENT_
const char sc_core::SC_ID_NO_DEFAULT_EVENT_ = "channel doesn't have a default event"
Definition at line 56 of file messages.cc.
Referenced by sc_core::sc_interface::default_event().
SC_ID_NO_INT_RETURNED_
const char sc_core::SC_ID_NO_INT_RETURNED_ = "operator does not return int"
Definition at line 37 of file messages.cc.
SC_ID_NO_PROCESS_SEMANTICS_
const char sc_core::SC_ID_NO_PROCESS_SEMANTICS_
Initial value:
=
    "Attempt to invoke process with no semantics() method"
Definition at line 143 of file messages.cc.
SC_ID_NO_SC_LOGIC_RETURNED_
const char sc_core::SC_ID_NO_SC_LOGIC_RETURNED_ = "operator does not return sc_logic"
Definition at line 38 of file messages.cc.
SC_ID_NO_SC_START_ACTIVITY_
const char sc_core::SC_ID_NO_SC_START_ACTIVITY_
Initial value:
=
    "no activity or clock movement for sc_start() invocation"
Definition at line 158 of file messages.cc.
SC_ID_NOT_EXPECTING_DYNAMIC_EVENT_NOTIFY_
const char sc_core::SC_ID_NOT_EXPECTING_DYNAMIC_EVENT_NOTIFY_
Initial value:
=
    "dynamic event notification encountered when sensitivity is static"
Definition at line 132 of file messages.cc.
SC_ID_NOT_IMPLEMENTED_
const char sc_core::SC_ID_NOT_IMPLEMENTED_ = "not implemented"
Definition at line 39 of file messages.cc.
SC_ID_NOTIFY_DELAYED_
const char sc_core::SC_ID_NOTIFY_DELAYED_
Initial value:
=
    "notify_delayed() cannot be called on events "
    "that have pending notifications"
Definition at line 81 of file messages.cc.
Referenced by sc_gem5::Event::notifyDelayed().
SC_ID_OPERAND_NOT_BOOL_
const char sc_core::SC_ID_OPERAND_NOT_BOOL_ = "operand is not bool"
Definition at line 40 of file messages.cc.
SC_ID_OPERAND_NOT_SC_LOGIC_
const char sc_core::SC_ID_OPERAND_NOT_SC_LOGIC_ = "operand is not sc_logic"
Definition at line 39 of file messages.cc.
SC_ID_OPERATION_FAILED_
const char sc_core::SC_ID_OPERATION_FAILED_ = "operation failed"
Definition at line 38 of file messages.cc.
Referenced by sc_dt::sc_value_base::concat_clear_data(), sc_dt::sc_value_base::concat_get_ctrl(), sc_dt::sc_value_base::concat_get_data(), sc_dt::sc_value_base::concat_get_uint64(), sc_dt::sc_value_base::concat_length(), sc_dt::sc_value_base::concat_set(), and sc_dt::div_by_zero().
SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_
const char sc_core::SC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_
Initial value:
=
    "attempted specalized signal operation on non-specialized signal"
Definition at line 75 of file messages.cc.
Referenced by sc_core::sc_int_part_if::part_read_target(), sc_core::sc_uint_part_if::part_read_target(), sc_core::sc_unsigned_part_if::part_read_target(), sc_core::sc_signed_part_if::part_read_target(), sc_core::sc_int_part_if::read_part(), sc_core::sc_uint_part_if::read_part(), sc_core::sc_unsigned_part_if::read_part(), sc_core::sc_signed_part_if::read_part(), sc_core::sc_int_part_if::select_part(), sc_core::sc_uint_part_if::select_part(), sc_core::sc_unsigned_part_if::select_part(), sc_core::sc_signed_part_if::select_part(), sc_core::sc_int_part_if::write_part(), sc_core::sc_uint_part_if::write_part(), sc_core::sc_unsigned_part_if::write_part(), and sc_core::sc_signed_part_if::write_part().
SC_ID_OUT_OF_BOUNDS_
const char sc_core::SC_ID_OUT_OF_BOUNDS_ = "out of bounds"
Definition at line 42 of file messages.cc.
Referenced by sc_dt::sc_subref_r< X >::check_bounds(), sc_dt::sc_uint_base::check_value(), sc_dt::sc_int_base::check_value(), sc_core::sc_vector_base::checkIndex(), sc_dt::sc_bitref_r< X >::get_bit(), sc_dt::sc_concref_r< X, Y >::get_bit(), sc_dt::sc_bitref_r< X >::get_cword(), sc_dt::sc_concref_r< X, Y >::get_cword(), sc_dt::sc_bitref_r< X >::get_word(), sc_dt::sc_concref_r< X, Y >::get_word(), sc_dt::sc_uint_base::invalid_index(), sc_dt::sc_int_base::invalid_index(), sc_dt::sc_uint_base::invalid_length(), sc_dt::sc_int_base::invalid_length(), sc_dt::sc_uint_base::invalid_range(), sc_dt::sc_int_base::invalid_range(), sc_dt::sc_unsigned::invalid_range(), sc_dt::MUL_HELPER(), sc_dt::sc_int_concref_invalid_length(), sc_dt::sc_proxy_out_of_bounds(), sc_dt::sc_uint_concref_invalid_length(), sc_dt::sc_bitref< X >::set_bit(), sc_dt::sc_concref_r< X, Y >::set_bit(), sc_dt::sc_bitref< X >::set_cword(), sc_dt::sc_concref_r< X, Y >::set_cword(), sc_dt::sc_bitref< X >::set_word(), sc_dt::sc_concref_r< X, Y >::set_word(), sc_dt::sc_unsigned_subref_r::to_string(), and sc_dt::vec_reverse().
SC_ID_OUT_OF_RANGE_
const char sc_core::SC_ID_OUT_OF_RANGE_ = "index out of range"
Definition at line 44 of file messages.cc.
Referenced by sc_dt::sc_fxnum::bit(), sc_dt::sc_fxnum_fast::bit(), sc_dt::sc_fxnum::operator()(), sc_dt::sc_fxnum_fast::operator()(), sc_dt::sc_fxnum::operator[](), sc_dt::sc_fxnum_fast::operator[](), sc_dt::sc_fxnum::range(), and sc_dt::sc_fxnum_fast::range().
SC_ID_PHASE_CALLBACK_FORBIDDEN_
const char sc_core::SC_ID_PHASE_CALLBACK_FORBIDDEN_
Initial value:
=
    "forbidden action in simulation phase callback"
Definition at line 126 of file messages.cc.
SC_ID_PHASE_CALLBACK_NOT_IMPLEMENTED_
const char sc_core::SC_ID_PHASE_CALLBACK_NOT_IMPLEMENTED_
Initial value:
=
    "empty simulation phase callback called"
Definition at line 122 of file messages.cc.
SC_ID_PHASE_CALLBACK_REGISTER_
const char sc_core::SC_ID_PHASE_CALLBACK_REGISTER_
Initial value:
=
    "register simulation phase callback"
Definition at line 124 of file messages.cc.
SC_ID_PHASE_CALLBACKS_UNSUPPORTED_
const char sc_core::SC_ID_PHASE_CALLBACKS_UNSUPPORTED_
Initial value:
=
    "simulation phase callbacks not enabled"
Definition at line 120 of file messages.cc.
SC_ID_PORT_OUTSIDE_MODULE_
const char sc_core::SC_ID_PORT_OUTSIDE_MODULE_ = "port specified outside of module"
Definition at line 36 of file messages.cc.
Referenced by sc_core::sc_port_base::sc_port_base().
SC_ID_PROCESS_ALREADY_UNWINDING_
const char sc_core::SC_ID_PROCESS_ALREADY_UNWINDING_
Initial value:
=
    "kill/reset ignored during unwinding"
Definition at line 101 of file messages.cc.
SC_ID_PROCESS_CONTROL_CORNER_CASE_
const char sc_core::SC_ID_PROCESS_CONTROL_CORNER_CASE_
Initial value:
=
    "Undefined process control interaction"
Definition at line 137 of file messages.cc.
Referenced by sc_gem5::Process::disable().
SC_ID_REGISTER_ID_FAILED_
const char sc_core::SC_ID_REGISTER_ID_FAILED_ = "register_id failed"
Definition at line 36 of file messages.cc.
Referenced by sc_core::sc_report::register_id().
SC_ID_REMOVE_MODULE_
const char sc_core::SC_ID_REMOVE_MODULE_ = "remove module failed"
Definition at line 80 of file messages.cc.
SC_ID_REMOVE_PORT_
const char sc_core::SC_ID_REMOVE_PORT_ = "remove port failed"
Definition at line 50 of file messages.cc.
SC_ID_REMOVE_PRIM_CHANNEL_
const char sc_core::SC_ID_REMOVE_PRIM_CHANNEL_ = "remove primitive channel failed"
Definition at line 53 of file messages.cc.
SC_ID_RESET_PROCESS_WHILE_NOT_RUNNING_
const char sc_core::SC_ID_RESET_PROCESS_WHILE_NOT_RUNNING_
Initial value:
=
    "a process may not be asynchronously reset while the "
    "simulation is not running"
Definition at line 162 of file messages.cc.
Referenced by sc_gem5::Process::reset().
SC_ID_RESOLVED_PORT_NOT_BOUND_
const char sc_core::SC_ID_RESOLVED_PORT_NOT_BOUND_
Initial value:
=
    "resolved port not bound to resolved signal"
Definition at line 57 of file messages.cc.
Referenced by sc_core::sc_inout_resolved::end_of_elaboration(), sc_core::sc_in_rv< W >::end_of_elaboration(), and sc_core::sc_inout_rv< W >::end_of_elaboration().
SC_ID_RETHROW_UNWINDING_
const char sc_core::SC_ID_RETHROW_UNWINDING_
Initial value:
=
    "sc_unwind_exception not re-thrown during kill/reset"
Definition at line 99 of file messages.cc.
SC_ID_SC_BV_CANNOT_CONTAIN_X_AND_Z_
const char sc_core::SC_ID_SC_BV_CANNOT_CONTAIN_X_AND_Z_
Initial value:
=
    "sc_bv cannot contain values X and Z"
Definition at line 45 of file messages.cc.
Referenced by sc_dt::sc_bv_base::set_cword().
SC_ID_SC_EXPORT_ALREADY_BOUND_
const char sc_core::SC_ID_SC_EXPORT_ALREADY_BOUND_
Initial value:
=
    "sc_export instance already bound"
Definition at line 73 of file messages.cc.
Referenced by sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::bind().
SC_ID_SC_EXPORT_HAS_NO_INTERFACE_
const char sc_core::SC_ID_SC_EXPORT_HAS_NO_INTERFACE_
Initial value:
=
    "sc_export instance has no interface"
Definition at line 62 of file messages.cc.
Referenced by sc_core::sc_export< tlm_fw_transport_if< TYPES > >::operator tlm_fw_transport_if< TYPES > &(), and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::operator->().
SC_ID_SC_EXPORT_NOT_BOUND_AFTER_CONSTRUCTION_
const char sc_core::SC_ID_SC_EXPORT_NOT_BOUND_AFTER_CONSTRUCTION_
Initial value:
=
    "sc_export instance not bound to interface at end of construction"
Definition at line 69 of file messages.cc.
SC_ID_SC_EXPORT_NOT_REGISTERED_
const char sc_core::SC_ID_SC_EXPORT_NOT_REGISTERED_
Initial value:
=
    "remove sc_export failed, sc_export not registered"
Definition at line 67 of file messages.cc.
SC_ID_SC_MODULE_NAME_REQUIRED_
const char sc_core::SC_ID_SC_MODULE_NAME_REQUIRED_
Initial value:
=
    "an sc_module_name parameter for your constructor is required"
Definition at line 56 of file messages.cc.
SC_ID_SC_MODULE_NAME_USE_
const char sc_core::SC_ID_SC_MODULE_NAME_USE_ = "incorrect use of sc_module_name"
Definition at line 55 of file messages.cc.
SC_ID_SET_DEFAULT_TIME_UNIT_
const char sc_core::SC_ID_SET_DEFAULT_TIME_UNIT_ = "set default time unit failed"
Definition at line 59 of file messages.cc.
Referenced by sc_set_default_time_unit().
SC_ID_SET_STACK_SIZE_
const char sc_core::SC_ID_SET_STACK_SIZE_
Initial value:
=
    "set_stack_size() is only allowed for SC_THREADs and SC_CTHREADs"
Definition at line 53 of file messages.cc.
SC_ID_SET_TIME_RESOLUTION_
const char sc_core::SC_ID_SET_TIME_RESOLUTION_ = "set time resolution failed"
Definition at line 58 of file messages.cc.
Referenced by sc_set_time_resolution().
SC_ID_SIMULATION_START_AFTER_ERROR_
const char sc_core::SC_ID_SIMULATION_START_AFTER_ERROR_
Initial value:
=
    "attempt to restart simulation after error"
Definition at line 117 of file messages.cc.
SC_ID_SIMULATION_START_AFTER_STOP_
const char sc_core::SC_ID_SIMULATION_START_AFTER_STOP_
Initial value:
=
    "sc_start called after sc_stop has been called"
Definition at line 113 of file messages.cc.
SC_ID_SIMULATION_START_UNEXPECTED_
const char sc_core::SC_ID_SIMULATION_START_UNEXPECTED_
Initial value:
=
    "sc_start called unexpectedly"
Definition at line 128 of file messages.cc.
SC_ID_SIMULATION_STOP_CALLED_TWICE_
const char sc_core::SC_ID_SIMULATION_STOP_CALLED_TWICE_
Initial value:
=
    "sc_stop has already been called"
Definition at line 111 of file messages.cc.
Referenced by sc_stop().
SC_ID_SIMULATION_TIME_OVERFLOW_
const char sc_core::SC_ID_SIMULATION_TIME_OVERFLOW_
Initial value:
=
    "simulation time value overflow, simulation aborted"
Definition at line 109 of file messages.cc.
Referenced by sc_start().
SC_ID_SIMULATION_UNCAUGHT_EXCEPTION_
const char sc_core::SC_ID_SIMULATION_UNCAUGHT_EXCEPTION_ = "uncaught exception"
Definition at line 119 of file messages.cc.
Referenced by sc_gem5::reportifyException().
SC_ID_STOP_MODE_AFTER_START_
const char sc_core::SC_ID_STOP_MODE_AFTER_START_
Initial value:
=
    "attempt to set sc_stop mode  after start will be ignored"
Definition at line 115 of file messages.cc.
Referenced by sc_set_stop_mode().
SC_ID_STRING_TOO_LONG_
const char sc_core::SC_ID_STRING_TOO_LONG_ = "string is too long"
Definition at line 45 of file messages.cc.
SC_ID_THROW_IT_IGNORED_
const char sc_core::SC_ID_THROW_IT_IGNORED_
Initial value:
=
    "throw_it on method/non-running process is being ignored "
Definition at line 130 of file messages.cc.
Referenced by sc_gem5::Process::throw_it().
SC_ID_THROW_IT_WHILE_NOT_RUNNING_
const char sc_core::SC_ID_THROW_IT_WHILE_NOT_RUNNING_
Initial value:
=
    "throw_it not allowed unless simulation is running "
Definition at line 165 of file messages.cc.
Referenced by sc_gem5::Process::throw_it().
SC_ID_TIME_CONVERSION_FAILED_
const char sc_core::SC_ID_TIME_CONVERSION_FAILED_ = "sc_time conversion failed"
Definition at line 150 of file messages.cc.
Referenced by sc_core::sc_time::from_string(), and sc_core::sc_time::sc_time().
SC_ID_UNKNOWN_ERROR_
const char sc_core::SC_ID_UNKNOWN_ERROR_ = "unknown error"
Definition at line 37 of file messages.cc.
Referenced by sc_core::sc_report_handler::get_count(), sc_core::sc_report_handler::report(), sc_core::sc_report_handler::set_actions(), and sc_core::sc_report_handler::stop_after().
SC_ID_UNKNOWN_PROCESS_TYPE_
const char sc_core::SC_ID_UNKNOWN_PROCESS_TYPE_ = "Unknown process type"
Definition at line 149 of file messages.cc.
SC_ID_VALUE_NOT_VALID_
const char sc_core::SC_ID_VALUE_NOT_VALID_ = "value is not valid"
Definition at line 41 of file messages.cc.
Referenced by sc_dt::sc_bit::invalid_value(), sc_dt::sc_logic::invalid_value(), sc_dt::is_bad_double(), and sc_dt::is_valid_base().
SC_ID_VC6_MAX_PROCESSES_EXCEEDED_
const char sc_core::SC_ID_VC6_MAX_PROCESSES_EXCEEDED_
Initial value:
=
    "maximum number of processes per module exceeded (VC6)"
Definition at line 45 of file messages.cc.
SC_ID_VC6_PROCESS_HELPER_
const char sc_core::SC_ID_VC6_PROCESS_HELPER_
Initial value:
=
    "internal error: sc_vc6_process_helper"
Definition at line 43 of file messages.cc.
SC_ID_VECTOR_BIND_EMPTY_
const char sc_core::SC_ID_VECTOR_BIND_EMPTY_
Initial value:
=
    "sc_vector::bind called with empty range"
Definition at line 54 of file messages.cc.
Referenced by sc_core::sc_vector_base::reportEmpty().
SC_ID_VECTOR_CONTAINS_LOGIC_VALUE_
const char sc_core::SC_ID_VECTOR_CONTAINS_LOGIC_VALUE_
Initial value:
=
    "vector contains 4-value logic"
Definition at line 43 of file messages.cc.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::to_anything_signed(), sc_dt::sc_proxy< sc_subref_r< X > >::to_anything_unsigned(), and sc_dt::sc_proxy< sc_subref_r< X > >::to_uint64().
SC_ID_VECTOR_INIT_CALLED_TWICE_
const char sc_core::SC_ID_VECTOR_INIT_CALLED_TWICE_
Initial value:
=
    "sc_vector::init has already been called"
Definition at line 52 of file messages.cc.
SC_ID_VECTOR_NONOBJECT_ELEMENTS_
const char sc_core::SC_ID_VECTOR_NONOBJECT_ELEMENTS_
Initial value:
=
    "sc_vector::get_elements called for element type "
    "not derived from sc_object"
Definition at line 56 of file messages.cc.
Referenced by sc_core::sc_vector_base::implicitCast().
SC_ID_VECTOR_TOO_LONG_
const char sc_core::SC_ID_VECTOR_TOO_LONG_ = "vector is too long: truncated"
Definition at line 47 of file messages.cc.
SC_ID_VECTOR_TOO_SHORT_
const char sc_core::SC_ID_VECTOR_TOO_SHORT_ = "vector is too short: 0-padded"
Definition at line 48 of file messages.cc.
SC_ID_WAIT_DURING_UNWINDING_
const char sc_core::SC_ID_WAIT_DURING_UNWINDING_
Initial value:
=
    "wait() not allowed during unwinding"
Definition at line 93 of file messages.cc.
SC_ID_WAIT_N_INVALID_
const char sc_core::SC_ID_WAIT_N_INVALID_ = "wait(n) is only valid for n > 0"
Definition at line 75 of file messages.cc.
Referenced by wait().
SC_ID_WAIT_NOT_ALLOWED_
const char sc_core::SC_ID_WAIT_NOT_ALLOWED_
Initial value:
=
    "wait() is only allowed in SC_THREADs and SC_CTHREADs"
Definition at line 64 of file messages.cc.
Referenced by timed_out().
SC_ID_WATCHING_NOT_ALLOWED_
const char sc_core::SC_ID_WATCHING_NOT_ALLOWED_
Initial value:
=
    "watching() has been deprecated, use reset_signal_is()"
Definition at line 71 of file messages.cc.
SC_ID_WITHOUT_MESSAGE_
const char sc_core::SC_ID_WITHOUT_MESSAGE_ = ""
Definition at line 38 of file messages.cc.
Referenced by sc_dt::vec_add_on(), sc_dt::vec_add_on2(), sc_dt::vec_add_small_on(), sc_dt::vec_mul_small_on(), and sc_dt::vec_sub_on2().
SC_ID_WRAP_SM_NOT_DEFINED_
const char sc_core::SC_ID_WRAP_SM_NOT_DEFINED_
Initial value:
=
    "SC_WRAP_SM not defined for unsigned numbers"
Definition at line 47 of file messages.cc.
Referenced by sc_dt::scfx_rep::overflow(), sc_dt::overflow(), and sc_dt::scfx_params::scfx_params().
SC_ID_WRONG_VALUE_
const char sc_core::SC_ID_WRONG_VALUE_ = "wrong value"
Definition at line 49 of file messages.cc.
SC_ID_ZERO_LENGTH_
const char sc_core::SC_ID_ZERO_LENGTH_ = "zero length"
Definition at line 42 of file messages.cc.
Referenced by sc_dt::sc_bv_base::init(), and sc_dt::sc_lv_base::init().
sc_is_prerelease
const bool sc_core::sc_is_prerelease = SC_IS_PRERELEASE
Definition at line 41 of file functions.cc.
sc_temp_heap
sc_byte_heap sc_core::sc_temp_heap
Definition at line 103 of file sc_concatref.hh.
Referenced by sc_dt::sc_concatref::value().
sc_version_major
const unsigned int sc_core::sc_version_major = SC_VERSION_MAJOR
Definition at line 35 of file functions.cc.
sc_version_minor
const unsigned int sc_core::sc_version_minor = SC_VERSION_MINOR
Definition at line 36 of file functions.cc.
sc_version_originator
const std::string sc_core::sc_version_originator = SC_VERSION_ORIGINATOR
Definition at line 38 of file functions.cc.
sc_version_patch
const unsigned int sc_core::sc_version_patch = SC_VERSION_PATCH
Definition at line 37 of file functions.cc.
sc_version_prerelease
const std::string sc_core::sc_version_prerelease = SC_VERSION_PRERELEASE
Definition at line 40 of file functions.cc.
sc_version_release_date
const std::string sc_core::sc_version_release_date = SC_VERSION_RELEASE_DATE
Definition at line 39 of file functions.cc.
sc_version_string
const std::string sc_core::sc_version_string = SC_VERSION
Definition at line 42 of file functions.cc.
SC_ZERO_TIME
const sc_time sc_core::SC_ZERO_TIME
Definition at line 292 of file sc_time.cc.
Referenced by sc_gem5::ScSignalBase::_signalChange(), sc_gem5::ScSignalBaseBinary::_signalNegedge(), sc_gem5::ScSignalBaseBinary::_signalPosedge(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), MultiSocketSimpleSwitchAT::bwPEQcb(), tlm::tlm_global_quantum::compute_local_quantum(), SimpleATTarget1::endRequest(), SimpleATInitiator1::endResponse(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::fec(), sc_core::sc_time::from_string(), MultiSocketSimpleSwitchAT::fwPEQcb(), tlm::tlm_dmi::init(), ExplicitLTTarget::myBTransport(), SimpleLTInitiator_ext::myNBTransport(), SimpleATInitiator2::myNBTransport(), SimpleATInitiator1::myNBTransport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::notify(), sc_core::sc_event::notify_delayed(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvRespRetry(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), tlm_utils::tlm_quantumkeeper::reset(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::ResponseThread(), SimpleLTInitiator2::run(), SimpleLTInitiator3::run(), SimpleLTInitiator1::run(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), SimpleATInitiator2::run(), SimpleATInitiator1::run(), sc_core::sc_clock::sc_clock(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendEndReq(), tlm::tlm_fifo< T >::update(), sc_core::sc_fifo< T >::update(), and sc_dp::sc_barrier::wait().