gem5: ArmISA Namespace Reference
ArmISA Namespace Reference
Namespaces
Kernel
Classes
class AbortFault
class ArmFault
class ArmFaultVals
class ArmSev
class ArmStaticInst
class AtomicGeneric2Op
A generic atomic op class.
class AtomicGeneric3Op
class AtomicGenericPair3Op
class BaseISADevice
Base class for devices that use the MiscReg interfaces.
class BigFpMemImmOp
class BigFpMemLitOp
class BigFpMemPostOp
class BigFpMemPreOp
class BigFpMemRegOp
class BranchEret64
class BranchImm
class BranchImm64
class BranchImmCond
class BranchImmCond64
class BranchImmImmReg64
class BranchImmReg
class BranchImmReg64
class BranchReg
class BranchReg64
class BranchRegCond
class BranchRegReg
class BranchRet64
class Crypto
class DataAbort
class DataImmOp
class DataRegOp
class DataRegRegOp
class DataX1Reg2ImmOp
class DataX1RegImmOp
class DataX1RegOp
class DataX2RegImmOp
class DataX2RegOp
class DataX3RegOp
class DataXCondCompImmOp
class DataXCondCompRegOp
class DataXCondSelOp
class DataXERegOp
class DataXImmOnlyOp
class DataXImmOp
class DataXSRegOp
class Decoder
class DTLBIALL
Data TLB Invalidate All.
class DTLBIASID
Data TLB Invalidate by ASID match.
class DTLBIMVA
Data TLB Invalidate by VA.
class DummyISADevice
Dummy device that prints a warning when it is accessed.
class FastInterrupt
class FpCondCompRegOp
class FpCondSelOp
class FpOp
class FpRegImmOp
class FpRegRegImmOp
class FpRegRegOp
class FpRegRegRegCondOp
class FpRegRegRegImmOp
class FpRegRegRegOp
class FpRegRegRegRegOp
class HypervisorCall
class HypervisorTrap
class IllegalInstSetStateFault
Illegal Instruction Set State fault (AArch64 only)
class Interrupt
class Interrupts
class ISA
class ITLBIALL
Instruction TLB Invalidate All.
class ITLBIASID
Instruction TLB Invalidate by ASID match.
class ITLBIMVA
Instruction TLB Invalidate by VA.
class MacroMemOp
Base class for microcoded integer memory instructions.
class MacroVFPMemOp
Base class for microcoded floating point memory instructions.
class Memory
class Memory64
class MemoryDImm
class MemoryDImm64
class MemoryDImmEx64
class MemoryDReg
class MemoryEx64
class MemoryExDImm
class MemoryExImm
class MemoryImm
class MemoryImm64
class MemoryLiteral64
class MemoryOffset
class MemoryPostIndex
class MemoryPostIndex64
class MemoryPreIndex
class MemoryPreIndex64
class MemoryRaw64
class MemoryReg
class MemoryReg64
class MicroIntImmOp
Microops of the form IntRegA = IntRegB op Imm.
class MicroIntImmXOp
class MicroIntMov
Microops of the form IntRegA = IntRegB.
class MicroIntOp
Microops of the form IntRegA = IntRegB op IntRegC.
class MicroIntRegOp
Microops of the form IntRegA = IntRegB op shifted IntRegC.
class MicroIntRegXOp
class MicroMemOp
Memory microops which use IntReg + Imm addressing.
class MicroMemPairOp
class MicroNeonMemOp
Microops for Neon loads/stores.
class MicroNeonMixLaneOp
class MicroNeonMixLaneOp64
class MicroNeonMixOp
Microops for Neon load/store (de)interleaving.
class MicroNeonMixOp64
Microops for AArch64 NEON load/store (de)interleaving.
class MicroOp
Base class for Memory microops.
class MicroOpX
class MicroSetPCCPSR
Microops of the form PC = IntRegA CPSR = IntRegB.
class MightBeMicro
class MightBeMicro64
class Mult3
Base class for multipy instructions using three registers.
class Mult4
Base class for multipy instructions using four registers.
class PairMemOp
Base class for pair load/store instructions.
class PCAlignmentFault
PC alignment fault (AArch64 only)
class PMU
Model of an ARM PMU version 3.
class PredImmOp
Base class for predicated immediate operations.
class PredIntOp
Base class for predicated integer operations.
class PredMacroOp
Base class for predicated macro-operations.
class PredMicroop
Base class for predicated micro-operations.
class PredOp
Base class for predicated integer operations.
class PrefetchAbort
class ProcessInfo
struct PTE
class RemoteGDB
class Reset
class RfeOp
class SecureMonitorCall
class SecureMonitorTrap
class SoftwareBreakpoint
System error (AArch64 only)
class SPAlignmentFault
Stack pointer alignment fault (AArch64 only)
class SrsOp
class StackTrace
class Stage2LookUp
class Stage2MMU
class SupervisorCall
class SupervisorTrap
class SveAdrOp
ADR.
class SveBinConstrPredOp
Binary, constructive, predicated SVE instruction.
class SveBinDestrPredOp
Binary, destructive, predicated (merging) SVE instruction.
class SveBinIdxUnpredOp
Binary, unpredicated SVE instruction.
class SveBinImmIdxUnpredOp
Binary with immediate index, destructive, unpredicated SVE instruction.
class SveBinImmPredOp
Binary with immediate, destructive, predicated (merging) SVE instruction.
class SveBinImmUnpredConstrOp
Binary with immediate, destructive, unpredicated SVE instruction.
class SveBinImmUnpredDestrOp
SVE vector - immediate binary operation.
class SveBinUnpredOp
Binary, unpredicated SVE instruction with indexed operand.
class SveBinWideImmUnpredOp
Binary with wide immediate, destructive, unpredicated SVE instruction.
class SveCmpImmOp
SVE compare-with-immediate instructions, predicated (zeroing).
class SveCmpOp
SVE compare instructions, predicated (zeroing).
class SveComplexIdxOp
SVE Complex Instructions (indexed)
class SveComplexOp
SVE Complex Instructions (vectors)
class SveCompTermOp
Compare and terminate loop SVE instruction.
class SveContigMemSI
class SveContigMemSS
class SveDotProdIdxOp
SVE dot product instruction (indexed)
class SveDotProdOp
SVE dot product instruction (vectors)
class SveElemCountOp
Element count SVE instruction.
class SveIndexedMemSV
class SveIndexedMemVI
class SveIndexIIOp
Index generation instruction, immediate operands.
class SveIndexIROp
class SveIndexRIOp
class SveIndexRROp
class SveIntCmpImmOp
Integer compare with immediate SVE instruction.
class SveIntCmpOp
Integer compare SVE instruction.
class SveLdStructSI
class SveLdStructSS
class SveMemPredFillSpill
class SveMemVecFillSpill
class SveOrdReducOp
SVE ordered reductions.
class SvePartBrkOp
Partition break SVE instruction.
class SvePartBrkPropOp
Partition break with propagation SVE instruction.
class SvePredBinPermOp
Predicate binary permute instruction.
class SvePredCountOp
class SvePredCountPredOp
class SvePredLogicalOp
Predicate logical instruction.
class SvePredTestOp
SVE predicate test.
class SvePredUnaryWImplicitDstOp
SVE unary predicate instructions with implicit destination operand.
class SvePredUnaryWImplicitSrcOp
SVE unary predicate instructions with implicit source operand.
class SvePredUnaryWImplicitSrcPredOp
SVE unary predicate instructions, predicated, with implicit source operand.
class SvePtrueOp
PTRUE, PTRUES.
class SveReducOp
SVE reductions.
class SveSelectOp
Scalar element select SVE instruction.
class SveStStructSI
class SveStStructSS
class SveTblOp
SVE table lookup/permute using vector of element indices (TBL)
class SveTerImmUnpredOp
Ternary with immediate, destructive, unpredicated SVE instruction.
class SveTerPredOp
Ternary, destructive, predicated (merging) SVE instruction.
class SveUnaryPredOp
Unary, constructive, predicated (merging) SVE instruction.
class SveUnaryPredPredOp
SVE unary operation on predicate (predicated)
class SveUnarySca2VecUnpredOp
Unary unpredicated scalar to vector instruction.
class SveUnaryUnpredOp
Unary, constructive, unpredicated SVE instruction.
class SveUnaryWideImmPredOp
Unary with wide immediate, constructive, predicated SVE instruction.
class SveUnaryWideImmUnpredOp
Unary with wide immediate, constructive, unpredicated SVE instruction.
class SveUnpackOp
SVE unpack and widen predicate.
class SveWhileOp
While predicate generation SVE instruction.
class SveWImplicitSrcDstOp
SVE unary predicate instructions with implicit destination operand.
class SysDC64
class SystemError
System error (AArch64 only)
class TableWalker
class TLB
struct TlbEntry
class TLBIALL
TLB Invalidate All.
class TLBIALLN
TLB Invalidate All, Non-Secure.
class TLBIASID
TLB Invalidate by ASID match.
class TLBIIPA
TLB Invalidate by Intermediate Physical Address.
class TLBIMVA
TLB Invalidate by VA.
class TLBIMVAA
TLB Invalidate by VA, All ASID.
class TLBIOp
class TlbTestInterface
class UndefinedInstruction
struct VAddr
class VfpMacroOp
class VirtualDataAbort
class VirtualFastInterrupt
class VirtualInterrupt
class VldMultOp
Base classes for microcoded integer memory instructions.
class VldMultOp64
Base classes for microcoded AArch64 NEON memory instructions.
class VldSingleOp
class VldSingleOp64
struct VReg
128-bit NEON vector register.
class VstMultOp
Base class for microcoded integer memory instructions.
class VstMultOp64
class VstSingleOp
class VstSingleOp64
Typedefs
typedef Addr FaultOffset
typedef uint64_t XReg
typedef int VfpSavedState
typedef IntRegIndex IntRegMap[NUM_ARCH_INTREGS]
using VecElem = uint32_t
using VecReg = ::VecRegT< VecElem, NumVecElemPerVecReg, false >
using ConstVecReg = ::VecRegT< VecElem, NumVecElemPerVecReg, true >
using VecRegContainer = VecReg::Container
using VecPredReg = ::VecPredRegT< VecElem, NumVecElemPerVecReg, VecPredRegHasPackedRepr, false >
using ConstVecPredReg = ::VecPredRegT< VecElem, NumVecElemPerVecReg, VecPredRegHasPackedRepr, true >
using VecPredRegContainer = VecPredReg::Container
typedef uint32_t MachInst
typedef int RegContextParam
typedef int RegContextVal
Enumerations
enum ccRegIndex {
CCREG_NZ, CCREG_C, CCREG_V, CCREG_GE,
CCREG_FP, CCREG_ZERO, NUM_CCREGS
}
enum ConditionCode {
COND_EQ = 0, COND_NE, COND_CS, COND_CC,
COND_MI, COND_PL, COND_VS, COND_VC,
COND_HI, COND_LS, COND_GE, COND_LT,
COND_GT, COND_LE, COND_AL, COND_UC
}
enum FPRounding {
FPRounding_TIEEVEN = 0, FPRounding_POSINF = 1, FPRounding_NEGINF = 2, FPRounding_ZERO = 3,
FPRounding_TIEAWAY = 4, FPRounding_ODD = 5
}
enum FpDataType { FpDataType::Fp16, FpDataType::Fp32, FpDataType::Fp64 }
Floating point data types.
enum SvePredType { SvePredType::NONE, SvePredType::MERGE, SvePredType::ZERO, SvePredType::SELECT }
enum VfpMicroMode { VfpNotAMicroop, VfpMicroop, VfpFirstMicroop, VfpLastMicroop }
enum FeExceptionBit {
FeDivByZero = FE_DIVBYZERO, FeInexact = FE_INEXACT, FeInvalid = FE_INVALID, FeOverflow = FE_OVERFLOW,
FeUnderflow = FE_UNDERFLOW, FeAllExceptions = FE_ALL_EXCEPT
}
enum FeRoundingMode { FeRoundDown = FE_DOWNWARD, FeRoundNearest = FE_TONEAREST, FeRoundZero = FE_TOWARDZERO, FeRoundUpward = FE_UPWARD }
enum VfpRoundingMode {
VfpRoundNearest = 0, VfpRoundUpward = 1, VfpRoundDown = 2, VfpRoundZero = 3,
VfpRoundAway = 4
}
enum IntRegIndex {
INTREG_R0, INTREG_R1, INTREG_R2, INTREG_R3,
INTREG_R4, INTREG_R5, INTREG_R6, INTREG_R7,
INTREG_R8, INTREG_R9, INTREG_R10, INTREG_R11,
INTREG_R12, INTREG_R13, INTREG_SP = INTREG_R13, INTREG_R14,
INTREG_LR = INTREG_R14, INTREG_R15, INTREG_PC = INTREG_R15, INTREG_R13_SVC,
INTREG_SP_SVC = INTREG_R13_SVC, INTREG_R14_SVC, INTREG_LR_SVC = INTREG_R14_SVC, INTREG_R13_MON,
INTREG_SP_MON = INTREG_R13_MON, INTREG_R14_MON, INTREG_LR_MON = INTREG_R14_MON, INTREG_R13_HYP,
INTREG_SP_HYP = INTREG_R13_HYP, INTREG_R13_ABT, INTREG_SP_ABT = INTREG_R13_ABT, INTREG_R14_ABT,
INTREG_LR_ABT = INTREG_R14_ABT, INTREG_R13_UND, INTREG_SP_UND = INTREG_R13_UND, INTREG_R14_UND,
INTREG_LR_UND = INTREG_R14_UND, INTREG_R13_IRQ, INTREG_SP_IRQ = INTREG_R13_IRQ, INTREG_R14_IRQ,
INTREG_LR_IRQ = INTREG_R14_IRQ, INTREG_R8_FIQ, INTREG_R9_FIQ, INTREG_R10_FIQ,
INTREG_R11_FIQ, INTREG_R12_FIQ, INTREG_R13_FIQ, INTREG_SP_FIQ = INTREG_R13_FIQ,
INTREG_R14_FIQ, INTREG_LR_FIQ = INTREG_R14_FIQ, INTREG_ZERO, INTREG_UREG0,
INTREG_UREG1, INTREG_UREG2, INTREG_DUMMY, INTREG_SP0,
INTREG_SP1, INTREG_SP2, INTREG_SP3, NUM_INTREGS,
NUM_ARCH_INTREGS = 32, INTREG_X0 = 0, INTREG_X1, INTREG_X2,
INTREG_X3, INTREG_X4, INTREG_X5, INTREG_X6,
INTREG_X7, INTREG_X8, INTREG_X9, INTREG_X10,
INTREG_X11, INTREG_X12, INTREG_X13, INTREG_X14,
INTREG_X15, INTREG_X16, INTREG_X17, INTREG_X18,
INTREG_X19, INTREG_X20, INTREG_X21, INTREG_X22,
INTREG_X23, INTREG_X24, INTREG_X25, INTREG_X26,
INTREG_X27, INTREG_X28, INTREG_X29, INTREG_X30,
INTREG_X31, INTREG_SPX = NUM_INTREGS, INTREG_R0_USR = INTREG_R0, INTREG_R1_USR = INTREG_R1,
INTREG_R2_USR = INTREG_R2, INTREG_R3_USR = INTREG_R3, INTREG_R4_USR = INTREG_R4, INTREG_R5_USR = INTREG_R5,
INTREG_R6_USR = INTREG_R6, INTREG_R7_USR = INTREG_R7, INTREG_R8_USR = INTREG_R8, INTREG_R9_USR = INTREG_R9,
INTREG_R10_USR = INTREG_R10, INTREG_R11_USR = INTREG_R11, INTREG_R12_USR = INTREG_R12, INTREG_R13_USR = INTREG_R13,
INTREG_SP_USR = INTREG_SP, INTREG_R14_USR = INTREG_R14, INTREG_LR_USR = INTREG_LR, INTREG_R15_USR = INTREG_R15,
INTREG_PC_USR = INTREG_PC, INTREG_R0_SVC = INTREG_R0, INTREG_R1_SVC = INTREG_R1, INTREG_R2_SVC = INTREG_R2,
INTREG_R3_SVC = INTREG_R3, INTREG_R4_SVC = INTREG_R4, INTREG_R5_SVC = INTREG_R5, INTREG_R6_SVC = INTREG_R6,
INTREG_R7_SVC = INTREG_R7, INTREG_R8_SVC = INTREG_R8, INTREG_R9_SVC = INTREG_R9, INTREG_R10_SVC = INTREG_R10,
INTREG_R11_SVC = INTREG_R11, INTREG_R12_SVC = INTREG_R12, INTREG_PC_SVC = INTREG_PC, INTREG_R15_SVC = INTREG_R15,
INTREG_R0_MON = INTREG_R0, INTREG_R1_MON = INTREG_R1, INTREG_R2_MON = INTREG_R2, INTREG_R3_MON = INTREG_R3,
INTREG_R4_MON = INTREG_R4, INTREG_R5_MON = INTREG_R5, INTREG_R6_MON = INTREG_R6, INTREG_R7_MON = INTREG_R7,
INTREG_R8_MON = INTREG_R8, INTREG_R9_MON = INTREG_R9, INTREG_R10_MON = INTREG_R10, INTREG_R11_MON = INTREG_R11,
INTREG_R12_MON = INTREG_R12, INTREG_PC_MON = INTREG_PC, INTREG_R15_MON = INTREG_R15, INTREG_R0_ABT = INTREG_R0,
INTREG_R1_ABT = INTREG_R1, INTREG_R2_ABT = INTREG_R2, INTREG_R3_ABT = INTREG_R3, INTREG_R4_ABT = INTREG_R4,
INTREG_R5_ABT = INTREG_R5, INTREG_R6_ABT = INTREG_R6, INTREG_R7_ABT = INTREG_R7, INTREG_R8_ABT = INTREG_R8,
INTREG_R9_ABT = INTREG_R9, INTREG_R10_ABT = INTREG_R10, INTREG_R11_ABT = INTREG_R11, INTREG_R12_ABT = INTREG_R12,
INTREG_PC_ABT = INTREG_PC, INTREG_R15_ABT = INTREG_R15, INTREG_R0_HYP = INTREG_R0, INTREG_R1_HYP = INTREG_R1,
INTREG_R2_HYP = INTREG_R2, INTREG_R3_HYP = INTREG_R3, INTREG_R4_HYP = INTREG_R4, INTREG_R5_HYP = INTREG_R5,
INTREG_R6_HYP = INTREG_R6, INTREG_R7_HYP = INTREG_R7, INTREG_R8_HYP = INTREG_R8, INTREG_R9_HYP = INTREG_R9,
INTREG_R10_HYP = INTREG_R10, INTREG_R11_HYP = INTREG_R11, INTREG_R12_HYP = INTREG_R12, INTREG_LR_HYP = INTREG_LR,
INTREG_R14_HYP = INTREG_R14, INTREG_PC_HYP = INTREG_PC, INTREG_R15_HYP = INTREG_R15, INTREG_R0_UND = INTREG_R0,
INTREG_R1_UND = INTREG_R1, INTREG_R2_UND = INTREG_R2, INTREG_R3_UND = INTREG_R3, INTREG_R4_UND = INTREG_R4,
INTREG_R5_UND = INTREG_R5, INTREG_R6_UND = INTREG_R6, INTREG_R7_UND = INTREG_R7, INTREG_R8_UND = INTREG_R8,
INTREG_R9_UND = INTREG_R9, INTREG_R10_UND = INTREG_R10, INTREG_R11_UND = INTREG_R11, INTREG_R12_UND = INTREG_R12,
INTREG_PC_UND = INTREG_PC, INTREG_R15_UND = INTREG_R15, INTREG_R0_IRQ = INTREG_R0, INTREG_R1_IRQ = INTREG_R1,
INTREG_R2_IRQ = INTREG_R2, INTREG_R3_IRQ = INTREG_R3, INTREG_R4_IRQ = INTREG_R4, INTREG_R5_IRQ = INTREG_R5,
INTREG_R6_IRQ = INTREG_R6, INTREG_R7_IRQ = INTREG_R7, INTREG_R8_IRQ = INTREG_R8, INTREG_R9_IRQ = INTREG_R9,
INTREG_R10_IRQ = INTREG_R10, INTREG_R11_IRQ = INTREG_R11, INTREG_R12_IRQ = INTREG_R12, INTREG_PC_IRQ = INTREG_PC,
INTREG_R15_IRQ = INTREG_R15, INTREG_R0_FIQ = INTREG_R0, INTREG_R1_FIQ = INTREG_R1, INTREG_R2_FIQ = INTREG_R2,
INTREG_R3_FIQ = INTREG_R3, INTREG_R4_FIQ = INTREG_R4, INTREG_R5_FIQ = INTREG_R5, INTREG_R6_FIQ = INTREG_R6,
INTREG_R7_FIQ = INTREG_R7, INTREG_PC_FIQ = INTREG_PC, INTREG_R15_FIQ = INTREG_R15
}
enum InterruptTypes {
INT_RST, INT_ABT, INT_IRQ, INT_FIQ,
INT_SEV, INT_VIRT_IRQ, INT_VIRT_FIQ, NumInterruptTypes
}
enum MiscRegIndex {
MISCREG_CPSR = 0, MISCREG_SPSR, MISCREG_SPSR_FIQ, MISCREG_SPSR_IRQ,
MISCREG_SPSR_SVC, MISCREG_SPSR_MON, MISCREG_SPSR_ABT, MISCREG_SPSR_HYP,
MISCREG_SPSR_UND, MISCREG_ELR_HYP, MISCREG_FPSID, MISCREG_FPSCR,
MISCREG_MVFR1, MISCREG_MVFR0, MISCREG_FPEXC, MISCREG_CPSR_MODE,
MISCREG_CPSR_Q, MISCREG_FPSCR_EXC, MISCREG_FPSCR_QC, MISCREG_LOCKADDR,
MISCREG_LOCKFLAG, MISCREG_PRRR_MAIR0, MISCREG_PRRR_MAIR0_NS, MISCREG_PRRR_MAIR0_S,
MISCREG_NMRR_MAIR1, MISCREG_NMRR_MAIR1_NS, MISCREG_NMRR_MAIR1_S, MISCREG_PMXEVTYPER_PMCCFILTR,
MISCREG_SCTLR_RST, MISCREG_SEV_MAILBOX, MISCREG_DBGDIDR, MISCREG_DBGDSCRint,
MISCREG_DBGDCCINT, MISCREG_DBGDTRTXint, MISCREG_DBGDTRRXint, MISCREG_DBGWFAR,
MISCREG_DBGVCR, MISCREG_DBGDTRRXext, MISCREG_DBGDSCRext, MISCREG_DBGDTRTXext,
MISCREG_DBGOSECCR, MISCREG_DBGBVR0, MISCREG_DBGBVR1, MISCREG_DBGBVR2,
MISCREG_DBGBVR3, MISCREG_DBGBVR4, MISCREG_DBGBVR5, MISCREG_DBGBCR0,
MISCREG_DBGBCR1, MISCREG_DBGBCR2, MISCREG_DBGBCR3, MISCREG_DBGBCR4,
MISCREG_DBGBCR5, MISCREG_DBGWVR0, MISCREG_DBGWVR1, MISCREG_DBGWVR2,
MISCREG_DBGWVR3, MISCREG_DBGWCR0, MISCREG_DBGWCR1, MISCREG_DBGWCR2,
MISCREG_DBGWCR3, MISCREG_DBGDRAR, MISCREG_DBGBXVR4, MISCREG_DBGBXVR5,
MISCREG_DBGOSLAR, MISCREG_DBGOSLSR, MISCREG_DBGOSDLR, MISCREG_DBGPRCR,
MISCREG_DBGDSAR, MISCREG_DBGCLAIMSET, MISCREG_DBGCLAIMCLR, MISCREG_DBGAUTHSTATUS,
MISCREG_DBGDEVID2, MISCREG_DBGDEVID1, MISCREG_DBGDEVID0, MISCREG_TEECR,
MISCREG_JIDR, MISCREG_TEEHBR, MISCREG_JOSCR, MISCREG_JMCR,
MISCREG_MIDR, MISCREG_CTR, MISCREG_TCMTR, MISCREG_TLBTR,
MISCREG_MPIDR, MISCREG_REVIDR, MISCREG_ID_PFR0, MISCREG_ID_PFR1,
MISCREG_ID_DFR0, MISCREG_ID_AFR0, MISCREG_ID_MMFR0, MISCREG_ID_MMFR1,
MISCREG_ID_MMFR2, MISCREG_ID_MMFR3, MISCREG_ID_ISAR0, MISCREG_ID_ISAR1,
MISCREG_ID_ISAR2, MISCREG_ID_ISAR3, MISCREG_ID_ISAR4, MISCREG_ID_ISAR5,
MISCREG_CCSIDR, MISCREG_CLIDR, MISCREG_AIDR, MISCREG_CSSELR,
MISCREG_CSSELR_NS, MISCREG_CSSELR_S, MISCREG_VPIDR, MISCREG_VMPIDR,
MISCREG_SCTLR, MISCREG_SCTLR_NS, MISCREG_SCTLR_S, MISCREG_ACTLR,
MISCREG_ACTLR_NS, MISCREG_ACTLR_S, MISCREG_CPACR, MISCREG_SCR,
MISCREG_SDER, MISCREG_NSACR, MISCREG_HSCTLR, MISCREG_HACTLR,
MISCREG_HCR, MISCREG_HCR2, MISCREG_HDCR, MISCREG_HCPTR,
MISCREG_HSTR, MISCREG_HACR, MISCREG_TTBR0, MISCREG_TTBR0_NS,
MISCREG_TTBR0_S, MISCREG_TTBR1, MISCREG_TTBR1_NS, MISCREG_TTBR1_S,
MISCREG_TTBCR, MISCREG_TTBCR_NS, MISCREG_TTBCR_S, MISCREG_HTCR,
MISCREG_VTCR, MISCREG_DACR, MISCREG_DACR_NS, MISCREG_DACR_S,
MISCREG_DFSR, MISCREG_DFSR_NS, MISCREG_DFSR_S, MISCREG_IFSR,
MISCREG_IFSR_NS, MISCREG_IFSR_S, MISCREG_ADFSR, MISCREG_ADFSR_NS,
MISCREG_ADFSR_S, MISCREG_AIFSR, MISCREG_AIFSR_NS, MISCREG_AIFSR_S,
MISCREG_HADFSR, MISCREG_HAIFSR, MISCREG_HSR, MISCREG_DFAR,
MISCREG_DFAR_NS, MISCREG_DFAR_S, MISCREG_IFAR, MISCREG_IFAR_NS,
MISCREG_IFAR_S, MISCREG_HDFAR, MISCREG_HIFAR, MISCREG_HPFAR,
MISCREG_ICIALLUIS, MISCREG_BPIALLIS, MISCREG_PAR, MISCREG_PAR_NS,
MISCREG_PAR_S, MISCREG_ICIALLU, MISCREG_ICIMVAU, MISCREG_CP15ISB,
MISCREG_BPIALL, MISCREG_BPIMVA, MISCREG_DCIMVAC, MISCREG_DCISW,
MISCREG_ATS1CPR, MISCREG_ATS1CPW, MISCREG_ATS1CUR, MISCREG_ATS1CUW,
MISCREG_ATS12NSOPR, MISCREG_ATS12NSOPW, MISCREG_ATS12NSOUR, MISCREG_ATS12NSOUW,
MISCREG_DCCMVAC, MISCREG_DCCSW, MISCREG_CP15DSB, MISCREG_CP15DMB,
MISCREG_DCCMVAU, MISCREG_DCCIMVAC, MISCREG_DCCISW, MISCREG_ATS1HR,
MISCREG_ATS1HW, MISCREG_TLBIALLIS, MISCREG_TLBIMVAIS, MISCREG_TLBIASIDIS,
MISCREG_TLBIMVAAIS, MISCREG_TLBIMVALIS, MISCREG_TLBIMVAALIS, MISCREG_ITLBIALL,
MISCREG_ITLBIMVA, MISCREG_ITLBIASID, MISCREG_DTLBIALL, MISCREG_DTLBIMVA,
MISCREG_DTLBIASID, MISCREG_TLBIALL, MISCREG_TLBIMVA, MISCREG_TLBIASID,
MISCREG_TLBIMVAA, MISCREG_TLBIMVAL, MISCREG_TLBIMVAAL, MISCREG_TLBIIPAS2IS,
MISCREG_TLBIIPAS2LIS, MISCREG_TLBIALLHIS, MISCREG_TLBIMVAHIS, MISCREG_TLBIALLNSNHIS,
MISCREG_TLBIMVALHIS, MISCREG_TLBIIPAS2, MISCREG_TLBIIPAS2L, MISCREG_TLBIALLH,
MISCREG_TLBIMVAH, MISCREG_TLBIALLNSNH, MISCREG_TLBIMVALH, MISCREG_PMCR,
MISCREG_PMCNTENSET, MISCREG_PMCNTENCLR, MISCREG_PMOVSR, MISCREG_PMSWINC,
MISCREG_PMSELR, MISCREG_PMCEID0, MISCREG_PMCEID1, MISCREG_PMCCNTR,
MISCREG_PMXEVTYPER, MISCREG_PMCCFILTR, MISCREG_PMXEVCNTR, MISCREG_PMUSERENR,
MISCREG_PMINTENSET, MISCREG_PMINTENCLR, MISCREG_PMOVSSET, MISCREG_L2CTLR,
MISCREG_L2ECTLR, MISCREG_PRRR, MISCREG_PRRR_NS, MISCREG_PRRR_S,
MISCREG_MAIR0, MISCREG_MAIR0_NS, MISCREG_MAIR0_S, MISCREG_NMRR,
MISCREG_NMRR_NS, MISCREG_NMRR_S, MISCREG_MAIR1, MISCREG_MAIR1_NS,
MISCREG_MAIR1_S, MISCREG_AMAIR0, MISCREG_AMAIR0_NS, MISCREG_AMAIR0_S,
MISCREG_AMAIR1, MISCREG_AMAIR1_NS, MISCREG_AMAIR1_S, MISCREG_HMAIR0,
MISCREG_HMAIR1, MISCREG_HAMAIR0, MISCREG_HAMAIR1, MISCREG_VBAR,
MISCREG_VBAR_NS, MISCREG_VBAR_S, MISCREG_MVBAR, MISCREG_RMR,
MISCREG_ISR, MISCREG_HVBAR, MISCREG_FCSEIDR, MISCREG_CONTEXTIDR,
MISCREG_CONTEXTIDR_NS, MISCREG_CONTEXTIDR_S, MISCREG_TPIDRURW, MISCREG_TPIDRURW_NS,
MISCREG_TPIDRURW_S, MISCREG_TPIDRURO, MISCREG_TPIDRURO_NS, MISCREG_TPIDRURO_S,
MISCREG_TPIDRPRW, MISCREG_TPIDRPRW_NS, MISCREG_TPIDRPRW_S, MISCREG_HTPIDR,
MISCREG_CNTFRQ, MISCREG_CNTKCTL, MISCREG_CNTP_TVAL, MISCREG_CNTP_TVAL_NS,
MISCREG_CNTP_TVAL_S, MISCREG_CNTP_CTL, MISCREG_CNTP_CTL_NS, MISCREG_CNTP_CTL_S,
MISCREG_CNTV_TVAL, MISCREG_CNTV_CTL, MISCREG_CNTHCTL, MISCREG_CNTHP_TVAL,
MISCREG_CNTHP_CTL, MISCREG_IL1DATA0, MISCREG_IL1DATA1, MISCREG_IL1DATA2,
MISCREG_IL1DATA3, MISCREG_DL1DATA0, MISCREG_DL1DATA1, MISCREG_DL1DATA2,
MISCREG_DL1DATA3, MISCREG_DL1DATA4, MISCREG_RAMINDEX, MISCREG_L2ACTLR,
MISCREG_CBAR, MISCREG_HTTBR, MISCREG_VTTBR, MISCREG_CNTPCT,
MISCREG_CNTVCT, MISCREG_CNTP_CVAL, MISCREG_CNTP_CVAL_NS, MISCREG_CNTP_CVAL_S,
MISCREG_CNTV_CVAL, MISCREG_CNTVOFF, MISCREG_CNTHP_CVAL, MISCREG_CPUMERRSR,
MISCREG_L2MERRSR, MISCREG_MDCCINT_EL1, MISCREG_OSDTRRX_EL1, MISCREG_MDSCR_EL1,
MISCREG_OSDTRTX_EL1, MISCREG_OSECCR_EL1, MISCREG_DBGBVR0_EL1, MISCREG_DBGBVR1_EL1,
MISCREG_DBGBVR2_EL1, MISCREG_DBGBVR3_EL1, MISCREG_DBGBVR4_EL1, MISCREG_DBGBVR5_EL1,
MISCREG_DBGBCR0_EL1, MISCREG_DBGBCR1_EL1, MISCREG_DBGBCR2_EL1, MISCREG_DBGBCR3_EL1,
MISCREG_DBGBCR4_EL1, MISCREG_DBGBCR5_EL1, MISCREG_DBGWVR0_EL1, MISCREG_DBGWVR1_EL1,
MISCREG_DBGWVR2_EL1, MISCREG_DBGWVR3_EL1, MISCREG_DBGWCR0_EL1, MISCREG_DBGWCR1_EL1,
MISCREG_DBGWCR2_EL1, MISCREG_DBGWCR3_EL1, MISCREG_MDCCSR_EL0, MISCREG_MDDTR_EL0,
MISCREG_MDDTRTX_EL0, MISCREG_MDDTRRX_EL0, MISCREG_DBGVCR32_EL2, MISCREG_MDRAR_EL1,
MISCREG_OSLAR_EL1, MISCREG_OSLSR_EL1, MISCREG_OSDLR_EL1, MISCREG_DBGPRCR_EL1,
MISCREG_DBGCLAIMSET_EL1, MISCREG_DBGCLAIMCLR_EL1, MISCREG_DBGAUTHSTATUS_EL1, MISCREG_TEECR32_EL1,
MISCREG_TEEHBR32_EL1, MISCREG_MIDR_EL1, MISCREG_MPIDR_EL1, MISCREG_REVIDR_EL1,
MISCREG_ID_PFR0_EL1, MISCREG_ID_PFR1_EL1, MISCREG_ID_DFR0_EL1, MISCREG_ID_AFR0_EL1,
MISCREG_ID_MMFR0_EL1, MISCREG_ID_MMFR1_EL1, MISCREG_ID_MMFR2_EL1, MISCREG_ID_MMFR3_EL1,
MISCREG_ID_ISAR0_EL1, MISCREG_ID_ISAR1_EL1, MISCREG_ID_ISAR2_EL1, MISCREG_ID_ISAR3_EL1,
MISCREG_ID_ISAR4_EL1, MISCREG_ID_ISAR5_EL1, MISCREG_MVFR0_EL1, MISCREG_MVFR1_EL1,
MISCREG_MVFR2_EL1, MISCREG_ID_AA64PFR0_EL1, MISCREG_ID_AA64PFR1_EL1, MISCREG_ID_AA64DFR0_EL1,
MISCREG_ID_AA64DFR1_EL1, MISCREG_ID_AA64AFR0_EL1, MISCREG_ID_AA64AFR1_EL1, MISCREG_ID_AA64ISAR0_EL1,
MISCREG_ID_AA64ISAR1_EL1, MISCREG_ID_AA64MMFR0_EL1, MISCREG_ID_AA64MMFR1_EL1, MISCREG_CCSIDR_EL1,
MISCREG_CLIDR_EL1, MISCREG_AIDR_EL1, MISCREG_CSSELR_EL1, MISCREG_CTR_EL0,
MISCREG_DCZID_EL0, MISCREG_VPIDR_EL2, MISCREG_VMPIDR_EL2, MISCREG_SCTLR_EL1,
MISCREG_ACTLR_EL1, MISCREG_CPACR_EL1, MISCREG_SCTLR_EL2, MISCREG_ACTLR_EL2,
MISCREG_HCR_EL2, MISCREG_MDCR_EL2, MISCREG_CPTR_EL2, MISCREG_HSTR_EL2,
MISCREG_HACR_EL2, MISCREG_SCTLR_EL3, MISCREG_ACTLR_EL3, MISCREG_SCR_EL3,
MISCREG_SDER32_EL3, MISCREG_CPTR_EL3, MISCREG_MDCR_EL3, MISCREG_TTBR0_EL1,
MISCREG_TTBR1_EL1, MISCREG_TCR_EL1, MISCREG_TTBR0_EL2, MISCREG_TCR_EL2,
MISCREG_VTTBR_EL2, MISCREG_VTCR_EL2, MISCREG_TTBR0_EL3, MISCREG_TCR_EL3,
MISCREG_DACR32_EL2, MISCREG_SPSR_EL1, MISCREG_ELR_EL1, MISCREG_SP_EL0,
MISCREG_SPSEL, MISCREG_CURRENTEL, MISCREG_NZCV, MISCREG_DAIF,
MISCREG_FPCR, MISCREG_FPSR, MISCREG_DSPSR_EL0, MISCREG_DLR_EL0,
MISCREG_SPSR_EL2, MISCREG_ELR_EL2, MISCREG_SP_EL1, MISCREG_SPSR_IRQ_AA64,
MISCREG_SPSR_ABT_AA64, MISCREG_SPSR_UND_AA64, MISCREG_SPSR_FIQ_AA64, MISCREG_SPSR_EL3,
MISCREG_ELR_EL3, MISCREG_SP_EL2, MISCREG_AFSR0_EL1, MISCREG_AFSR1_EL1,
MISCREG_ESR_EL1, MISCREG_IFSR32_EL2, MISCREG_AFSR0_EL2, MISCREG_AFSR1_EL2,
MISCREG_ESR_EL2, MISCREG_FPEXC32_EL2, MISCREG_AFSR0_EL3, MISCREG_AFSR1_EL3,
MISCREG_ESR_EL3, MISCREG_FAR_EL1, MISCREG_FAR_EL2, MISCREG_HPFAR_EL2,
MISCREG_FAR_EL3, MISCREG_IC_IALLUIS, MISCREG_PAR_EL1, MISCREG_IC_IALLU,
MISCREG_DC_IVAC_Xt, MISCREG_DC_ISW_Xt, MISCREG_AT_S1E1R_Xt, MISCREG_AT_S1E1W_Xt,
MISCREG_AT_S1E0R_Xt, MISCREG_AT_S1E0W_Xt, MISCREG_DC_CSW_Xt, MISCREG_DC_CISW_Xt,
MISCREG_DC_ZVA_Xt, MISCREG_IC_IVAU_Xt, MISCREG_DC_CVAC_Xt, MISCREG_DC_CVAU_Xt,
MISCREG_DC_CIVAC_Xt, MISCREG_AT_S1E2R_Xt, MISCREG_AT_S1E2W_Xt, MISCREG_AT_S12E1R_Xt,
MISCREG_AT_S12E1W_Xt, MISCREG_AT_S12E0R_Xt, MISCREG_AT_S12E0W_Xt, MISCREG_AT_S1E3R_Xt,
MISCREG_AT_S1E3W_Xt, MISCREG_TLBI_VMALLE1IS, MISCREG_TLBI_VAE1IS_Xt, MISCREG_TLBI_ASIDE1IS_Xt,
MISCREG_TLBI_VAAE1IS_Xt, MISCREG_TLBI_VALE1IS_Xt, MISCREG_TLBI_VAALE1IS_Xt, MISCREG_TLBI_VMALLE1,
MISCREG_TLBI_VAE1_Xt, MISCREG_TLBI_ASIDE1_Xt, MISCREG_TLBI_VAAE1_Xt, MISCREG_TLBI_VALE1_Xt,
MISCREG_TLBI_VAALE1_Xt, MISCREG_TLBI_IPAS2E1IS_Xt, MISCREG_TLBI_IPAS2LE1IS_Xt, MISCREG_TLBI_ALLE2IS,
MISCREG_TLBI_VAE2IS_Xt, MISCREG_TLBI_ALLE1IS, MISCREG_TLBI_VALE2IS_Xt, MISCREG_TLBI_VMALLS12E1IS,
MISCREG_TLBI_IPAS2E1_Xt, MISCREG_TLBI_IPAS2LE1_Xt, MISCREG_TLBI_ALLE2, MISCREG_TLBI_VAE2_Xt,
MISCREG_TLBI_ALLE1, MISCREG_TLBI_VALE2_Xt, MISCREG_TLBI_VMALLS12E1, MISCREG_TLBI_ALLE3IS,
MISCREG_TLBI_VAE3IS_Xt, MISCREG_TLBI_VALE3IS_Xt, MISCREG_TLBI_ALLE3, MISCREG_TLBI_VAE3_Xt,
MISCREG_TLBI_VALE3_Xt, MISCREG_PMINTENSET_EL1, MISCREG_PMINTENCLR_EL1, MISCREG_PMCR_EL0,
MISCREG_PMCNTENSET_EL0, MISCREG_PMCNTENCLR_EL0, MISCREG_PMOVSCLR_EL0, MISCREG_PMSWINC_EL0,
MISCREG_PMSELR_EL0, MISCREG_PMCEID0_EL0, MISCREG_PMCEID1_EL0, MISCREG_PMCCNTR_EL0,
MISCREG_PMXEVTYPER_EL0, MISCREG_PMCCFILTR_EL0, MISCREG_PMXEVCNTR_EL0, MISCREG_PMUSERENR_EL0,
MISCREG_PMOVSSET_EL0, MISCREG_MAIR_EL1, MISCREG_AMAIR_EL1, MISCREG_MAIR_EL2,
MISCREG_AMAIR_EL2, MISCREG_MAIR_EL3, MISCREG_AMAIR_EL3, MISCREG_L2CTLR_EL1,
MISCREG_L2ECTLR_EL1, MISCREG_VBAR_EL1, MISCREG_RVBAR_EL1, MISCREG_ISR_EL1,
MISCREG_VBAR_EL2, MISCREG_RVBAR_EL2, MISCREG_VBAR_EL3, MISCREG_RVBAR_EL3,
MISCREG_RMR_EL3, MISCREG_CONTEXTIDR_EL1, MISCREG_TPIDR_EL1, MISCREG_TPIDR_EL0,
MISCREG_TPIDRRO_EL0, MISCREG_TPIDR_EL2, MISCREG_TPIDR_EL3, MISCREG_CNTKCTL_EL1,
MISCREG_CNTFRQ_EL0, MISCREG_CNTPCT_EL0, MISCREG_CNTVCT_EL0, MISCREG_CNTP_TVAL_EL0,
MISCREG_CNTP_CTL_EL0, MISCREG_CNTP_CVAL_EL0, MISCREG_CNTV_TVAL_EL0, MISCREG_CNTV_CTL_EL0,
MISCREG_CNTV_CVAL_EL0, MISCREG_PMEVCNTR0_EL0, MISCREG_PMEVCNTR1_EL0, MISCREG_PMEVCNTR2_EL0,
MISCREG_PMEVCNTR3_EL0, MISCREG_PMEVCNTR4_EL0, MISCREG_PMEVCNTR5_EL0, MISCREG_PMEVTYPER0_EL0,
MISCREG_PMEVTYPER1_EL0, MISCREG_PMEVTYPER2_EL0, MISCREG_PMEVTYPER3_EL0, MISCREG_PMEVTYPER4_EL0,
MISCREG_PMEVTYPER5_EL0, MISCREG_CNTVOFF_EL2, MISCREG_CNTHCTL_EL2, MISCREG_CNTHP_TVAL_EL2,
MISCREG_CNTHP_CTL_EL2, MISCREG_CNTHP_CVAL_EL2, MISCREG_CNTPS_TVAL_EL1, MISCREG_CNTPS_CTL_EL1,
MISCREG_CNTPS_CVAL_EL1, MISCREG_IL1DATA0_EL1, MISCREG_IL1DATA1_EL1, MISCREG_IL1DATA2_EL1,
MISCREG_IL1DATA3_EL1, MISCREG_DL1DATA0_EL1, MISCREG_DL1DATA1_EL1, MISCREG_DL1DATA2_EL1,
MISCREG_DL1DATA3_EL1, MISCREG_DL1DATA4_EL1, MISCREG_L2ACTLR_EL1, MISCREG_CPUACTLR_EL1,
MISCREG_CPUECTLR_EL1, MISCREG_CPUMERRSR_EL1, MISCREG_L2MERRSR_EL1, MISCREG_CBAR_EL1,
MISCREG_CONTEXTIDR_EL2, MISCREG_TTBR1_EL2, MISCREG_CNTHV_CTL_EL2, MISCREG_CNTHV_CVAL_EL2,
MISCREG_CNTHV_TVAL_EL2, MISCREG_ID_AA64MMFR2_EL1, MISCREG_ICC_PMR_EL1, MISCREG_ICC_IAR0_EL1,
MISCREG_ICC_EOIR0_EL1, MISCREG_ICC_HPPIR0_EL1, MISCREG_ICC_BPR0_EL1, MISCREG_ICC_AP0R0_EL1,
MISCREG_ICC_AP0R1_EL1, MISCREG_ICC_AP0R2_EL1, MISCREG_ICC_AP0R3_EL1, MISCREG_ICC_AP1R0_EL1,
MISCREG_ICC_AP1R0_EL1_NS, MISCREG_ICC_AP1R0_EL1_S, MISCREG_ICC_AP1R1_EL1, MISCREG_ICC_AP1R1_EL1_NS,
MISCREG_ICC_AP1R1_EL1_S, MISCREG_ICC_AP1R2_EL1, MISCREG_ICC_AP1R2_EL1_NS, MISCREG_ICC_AP1R2_EL1_S,
MISCREG_ICC_AP1R3_EL1, MISCREG_ICC_AP1R3_EL1_NS, MISCREG_ICC_AP1R3_EL1_S, MISCREG_ICC_DIR_EL1,
MISCREG_ICC_RPR_EL1, MISCREG_ICC_SGI1R_EL1, MISCREG_ICC_ASGI1R_EL1, MISCREG_ICC_SGI0R_EL1,
MISCREG_ICC_IAR1_EL1, MISCREG_ICC_EOIR1_EL1, MISCREG_ICC_HPPIR1_EL1, MISCREG_ICC_BPR1_EL1,
MISCREG_ICC_BPR1_EL1_NS, MISCREG_ICC_BPR1_EL1_S, MISCREG_ICC_CTLR_EL1, MISCREG_ICC_CTLR_EL1_NS,
MISCREG_ICC_CTLR_EL1_S, MISCREG_ICC_SRE_EL1, MISCREG_ICC_SRE_EL1_NS, MISCREG_ICC_SRE_EL1_S,
MISCREG_ICC_IGRPEN0_EL1, MISCREG_ICC_IGRPEN1_EL1, MISCREG_ICC_IGRPEN1_EL1_NS, MISCREG_ICC_IGRPEN1_EL1_S,
MISCREG_ICC_SRE_EL2, MISCREG_ICC_CTLR_EL3, MISCREG_ICC_SRE_EL3, MISCREG_ICC_IGRPEN1_EL3,
MISCREG_ICH_AP0R0_EL2, MISCREG_ICH_AP0R1_EL2, MISCREG_ICH_AP0R2_EL2, MISCREG_ICH_AP0R3_EL2,
MISCREG_ICH_AP1R0_EL2, MISCREG_ICH_AP1R1_EL2, MISCREG_ICH_AP1R2_EL2, MISCREG_ICH_AP1R3_EL2,
MISCREG_ICH_HCR_EL2, MISCREG_ICH_VTR_EL2, MISCREG_ICH_MISR_EL2, MISCREG_ICH_EISR_EL2,
MISCREG_ICH_ELRSR_EL2, MISCREG_ICH_VMCR_EL2, MISCREG_ICH_LR0_EL2, MISCREG_ICH_LR1_EL2,
MISCREG_ICH_LR2_EL2, MISCREG_ICH_LR3_EL2, MISCREG_ICH_LR4_EL2, MISCREG_ICH_LR5_EL2,
MISCREG_ICH_LR6_EL2, MISCREG_ICH_LR7_EL2, MISCREG_ICH_LR8_EL2, MISCREG_ICH_LR9_EL2,
MISCREG_ICH_LR10_EL2, MISCREG_ICH_LR11_EL2, MISCREG_ICH_LR12_EL2, MISCREG_ICH_LR13_EL2,
MISCREG_ICH_LR14_EL2, MISCREG_ICH_LR15_EL2, MISCREG_ICV_PMR_EL1, MISCREG_ICV_IAR0_EL1,
MISCREG_ICV_EOIR0_EL1, MISCREG_ICV_HPPIR0_EL1, MISCREG_ICV_BPR0_EL1, MISCREG_ICV_AP0R0_EL1,
MISCREG_ICV_AP0R1_EL1, MISCREG_ICV_AP0R2_EL1, MISCREG_ICV_AP0R3_EL1, MISCREG_ICV_AP1R0_EL1,
MISCREG_ICV_AP1R0_EL1_NS, MISCREG_ICV_AP1R0_EL1_S, MISCREG_ICV_AP1R1_EL1, MISCREG_ICV_AP1R1_EL1_NS,
MISCREG_ICV_AP1R1_EL1_S, MISCREG_ICV_AP1R2_EL1, MISCREG_ICV_AP1R2_EL1_NS, MISCREG_ICV_AP1R2_EL1_S,
MISCREG_ICV_AP1R3_EL1, MISCREG_ICV_AP1R3_EL1_NS, MISCREG_ICV_AP1R3_EL1_S, MISCREG_ICV_DIR_EL1,
MISCREG_ICV_RPR_EL1, MISCREG_ICV_SGI1R_EL1, MISCREG_ICV_ASGI1R_EL1, MISCREG_ICV_SGI0R_EL1,
MISCREG_ICV_IAR1_EL1, MISCREG_ICV_EOIR1_EL1, MISCREG_ICV_HPPIR1_EL1, MISCREG_ICV_BPR1_EL1,
MISCREG_ICV_BPR1_EL1_NS, MISCREG_ICV_BPR1_EL1_S, MISCREG_ICV_CTLR_EL1, MISCREG_ICV_CTLR_EL1_NS,
MISCREG_ICV_CTLR_EL1_S, MISCREG_ICV_SRE_EL1, MISCREG_ICV_SRE_EL1_NS, MISCREG_ICV_SRE_EL1_S,
MISCREG_ICV_IGRPEN0_EL1, MISCREG_ICV_IGRPEN1_EL1, MISCREG_ICV_IGRPEN1_EL1_NS, MISCREG_ICV_IGRPEN1_EL1_S,
MISCREG_ICC_AP0R0, MISCREG_ICC_AP0R1, MISCREG_ICC_AP0R2, MISCREG_ICC_AP0R3,
MISCREG_ICC_AP1R0, MISCREG_ICC_AP1R0_NS, MISCREG_ICC_AP1R0_S, MISCREG_ICC_AP1R1,
MISCREG_ICC_AP1R1_NS, MISCREG_ICC_AP1R1_S, MISCREG_ICC_AP1R2, MISCREG_ICC_AP1R2_NS,
MISCREG_ICC_AP1R2_S, MISCREG_ICC_AP1R3, MISCREG_ICC_AP1R3_NS, MISCREG_ICC_AP1R3_S,
MISCREG_ICC_ASGI1R, MISCREG_ICC_BPR0, MISCREG_ICC_BPR1, MISCREG_ICC_BPR1_NS,
MISCREG_ICC_BPR1_S, MISCREG_ICC_CTLR, MISCREG_ICC_CTLR_NS, MISCREG_ICC_CTLR_S,
MISCREG_ICC_DIR, MISCREG_ICC_EOIR0, MISCREG_ICC_EOIR1, MISCREG_ICC_HPPIR0,
MISCREG_ICC_HPPIR1, MISCREG_ICC_HSRE, MISCREG_ICC_IAR0, MISCREG_ICC_IAR1,
MISCREG_ICC_IGRPEN0, MISCREG_ICC_IGRPEN1, MISCREG_ICC_IGRPEN1_NS, MISCREG_ICC_IGRPEN1_S,
MISCREG_ICC_MCTLR, MISCREG_ICC_MGRPEN1, MISCREG_ICC_MSRE, MISCREG_ICC_PMR,
MISCREG_ICC_RPR, MISCREG_ICC_SGI0R, MISCREG_ICC_SGI1R, MISCREG_ICC_SRE,
MISCREG_ICC_SRE_NS, MISCREG_ICC_SRE_S, MISCREG_ICH_AP0R0, MISCREG_ICH_AP0R1,
MISCREG_ICH_AP0R2, MISCREG_ICH_AP0R3, MISCREG_ICH_AP1R0, MISCREG_ICH_AP1R1,
MISCREG_ICH_AP1R2, MISCREG_ICH_AP1R3, MISCREG_ICH_HCR, MISCREG_ICH_VTR,
MISCREG_ICH_MISR, MISCREG_ICH_EISR, MISCREG_ICH_ELRSR, MISCREG_ICH_VMCR,
MISCREG_ICH_LR0, MISCREG_ICH_LR1, MISCREG_ICH_LR2, MISCREG_ICH_LR3,
MISCREG_ICH_LR4, MISCREG_ICH_LR5, MISCREG_ICH_LR6, MISCREG_ICH_LR7,
MISCREG_ICH_LR8, MISCREG_ICH_LR9, MISCREG_ICH_LR10, MISCREG_ICH_LR11,
MISCREG_ICH_LR12, MISCREG_ICH_LR13, MISCREG_ICH_LR14, MISCREG_ICH_LR15,
MISCREG_ICH_LRC0, MISCREG_ICH_LRC1, MISCREG_ICH_LRC2, MISCREG_ICH_LRC3,
MISCREG_ICH_LRC4, MISCREG_ICH_LRC5, MISCREG_ICH_LRC6, MISCREG_ICH_LRC7,
MISCREG_ICH_LRC8, MISCREG_ICH_LRC9, MISCREG_ICH_LRC10, MISCREG_ICH_LRC11,
MISCREG_ICH_LRC12, MISCREG_ICH_LRC13, MISCREG_ICH_LRC14, MISCREG_ICH_LRC15,
MISCREG_ID_AA64ZFR0_EL1, MISCREG_ZCR_EL3, MISCREG_ZCR_EL2, MISCREG_ZCR_EL12,
MISCREG_ZCR_EL1, NUM_PHYS_MISCREGS, MISCREG_NOP, MISCREG_RAZ,
MISCREG_CP14_UNIMPL, MISCREG_CP15_UNIMPL, MISCREG_UNKNOWN, MISCREG_IMPDEF_UNIMPL,
MISCREG_ERRIDR_EL1, MISCREG_ERRSELR_EL1, MISCREG_ERXFR_EL1, MISCREG_ERXCTLR_EL1,
MISCREG_ERXSTATUS_EL1, MISCREG_ERXADDR_EL1, MISCREG_ERXMISC0_EL1, MISCREG_ERXMISC1_EL1,
MISCREG_DISR_EL1, MISCREG_VSESR_EL2, MISCREG_VDISR_EL2, MISCREG_PAN,
NUM_MISCREGS
}
enum MiscRegInfo {
MISCREG_IMPLEMENTED, MISCREG_UNVERIFIABLE, MISCREG_WARN_NOT_FAIL, MISCREG_MUTEX,
MISCREG_BANKED, MISCREG_BANKED64, MISCREG_BANKED_CHILD, MISCREG_USR_NS_RD,
MISCREG_USR_NS_WR, MISCREG_USR_S_RD, MISCREG_USR_S_WR, MISCREG_PRI_NS_RD,
MISCREG_PRI_NS_WR, MISCREG_PRI_S_RD, MISCREG_PRI_S_WR, MISCREG_HYP_RD,
MISCREG_HYP_WR, MISCREG_MON_NS0_RD, MISCREG_MON_NS0_WR, MISCREG_MON_NS1_RD,
MISCREG_MON_NS1_WR, NUM_MISCREG_INFOS
}
enum LookupLevel {
L0 = 0, L1, L2, L3,
MAX_LOOKUP_LEVELS
}
enum ArmShiftType { LSL = 0, LSR, ASR, ROR }
enum ArmExtendType {
UXTB = 0, UXTH = 1, UXTW = 2, UXTX = 3,
SXTB = 4, SXTH = 5, SXTW = 6, SXTX = 7
}
enum ConvertType {
SINGLE_TO_DOUBLE, SINGLE_TO_WORD, SINGLE_TO_LONG, DOUBLE_TO_SINGLE,
DOUBLE_TO_WORD, DOUBLE_TO_LONG, LONG_TO_SINGLE, LONG_TO_DOUBLE,
LONG_TO_WORD, LONG_TO_PS, WORD_TO_SINGLE, WORD_TO_DOUBLE,
WORD_TO_LONG, WORD_TO_PS, PL_TO_SINGLE, PU_TO_SINGLE
}
enum RoundMode { RND_ZERO, RND_DOWN, RND_UP, RND_NEAREST }
enum ExceptionLevel { EL0 = 0, EL1, EL2, EL3 }
enum OperatingMode {
MODE_EL0T = 0x0, MODE_EL1T = 0x4, MODE_EL1H = 0x5, MODE_EL2T = 0x8,
MODE_EL2H = 0x9, MODE_EL3T = 0xC, MODE_EL3H = 0xD, MODE_USER = 16,
MODE_FIQ = 17, MODE_IRQ = 18, MODE_SVC = 19, MODE_MON = 22,
MODE_ABORT = 23, MODE_HYP = 26, MODE_UNDEFINED = 27, MODE_SYSTEM = 31,
MODE_MAXMODE = MODE_SYSTEM
}
enum ExceptionClass {
EC_INVALID = -1, EC_UNKNOWN = 0x0, EC_TRAPPED_WFI_WFE = 0x1, EC_TRAPPED_CP15_MCR_MRC = 0x3,
EC_TRAPPED_CP15_MCRR_MRRC = 0x4, EC_TRAPPED_CP14_MCR_MRC = 0x5, EC_TRAPPED_CP14_LDC_STC = 0x6, EC_TRAPPED_HCPTR = 0x7,
EC_TRAPPED_SIMD_FP = 0x7, EC_TRAPPED_CP10_MRC_VMRS = 0x8, EC_TRAPPED_BXJ = 0xA, EC_TRAPPED_CP14_MCRR_MRRC = 0xC,
EC_ILLEGAL_INST = 0xE, EC_SVC_TO_HYP = 0x11, EC_SVC = 0x11, EC_HVC = 0x12,
EC_SMC_TO_HYP = 0x13, EC_SMC = 0x13, EC_SVC_64 = 0x15, EC_HVC_64 = 0x16,
EC_SMC_64 = 0x17, EC_TRAPPED_MSR_MRS_64 = 0x18, EC_TRAPPED_SVE = 0x19, EC_PREFETCH_ABORT_TO_HYP = 0x20,
EC_PREFETCH_ABORT_LOWER_EL = 0x20, EC_PREFETCH_ABORT_FROM_HYP = 0x21, EC_PREFETCH_ABORT_CURR_EL = 0x21, EC_PC_ALIGNMENT = 0x22,
EC_DATA_ABORT_TO_HYP = 0x24, EC_DATA_ABORT_LOWER_EL = 0x24, EC_DATA_ABORT_FROM_HYP = 0x25, EC_DATA_ABORT_CURR_EL = 0x25,
EC_STACK_PTR_ALIGNMENT = 0x26, EC_FP_EXCEPTION = 0x28, EC_FP_EXCEPTION_64 = 0x2C, EC_SERROR = 0x2F,
EC_SOFTWARE_BREAKPOINT = 0x38, EC_SOFTWARE_BREAKPOINT_64 = 0x3C
}
enum DecoderFault : std::uint8_t { OK = 0x0, UNALIGNED = 0x1, PANIC = 0x3 }
Instruction decoder fault codes in ExtMachInst.
Functions
bool getFaultVAddr (Fault fault, Addr &va)
Returns true if the fault passed as a first argument was triggered by a memory access, false otherwise.
static uint16_t lsl16 (uint16_t x, uint32_t shift)
static uint16_t lsr16 (uint16_t x, uint32_t shift)
static uint32_t lsl32 (uint32_t x, uint32_t shift)
static uint32_t lsr32 (uint32_t x, uint32_t shift)
static uint64_t lsl64 (uint64_t x, uint32_t shift)
static uint64_t lsr64 (uint64_t x, uint32_t shift)
static void lsl128 (uint64_t *r0, uint64_t *r1, uint64_t x0, uint64_t x1, uint32_t shift)
static void lsr128 (uint64_t *r0, uint64_t *r1, uint64_t x0, uint64_t x1, uint32_t shift)
static void mul62x62 (uint64_t *x0, uint64_t *x1, uint64_t a, uint64_t b)
static void mul64x32 (uint64_t *x0, uint64_t *x1, uint64_t a, uint32_t b)
static void add128 (uint64_t *x0, uint64_t *x1, uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1)
static void sub128 (uint64_t *x0, uint64_t *x1, uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1)
static int cmp128 (uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1)
static uint16_t fp16_normalise (uint16_t mnt, int *exp)
static uint32_t fp32_normalise (uint32_t mnt, int *exp)
static uint64_t fp64_normalise (uint64_t mnt, int *exp)
static void fp128_normalise (uint64_t *mnt0, uint64_t *mnt1, int *exp)
static uint16_t fp16_pack (uint16_t sgn, uint16_t exp, uint16_t mnt)
static uint32_t fp32_pack (uint32_t sgn, uint32_t exp, uint32_t mnt)
static uint64_t fp64_pack (uint64_t sgn, uint64_t exp, uint64_t mnt)
static uint16_t fp16_zero (int sgn)
static uint32_t fp32_zero (int sgn)
static uint64_t fp64_zero (int sgn)
static uint16_t fp16_max_normal (int sgn)
static uint32_t fp32_max_normal (int sgn)
static uint64_t fp64_max_normal (int sgn)
static uint16_t fp16_infinity (int sgn)
static uint32_t fp32_infinity (int sgn)
static uint64_t fp64_infinity (int sgn)
static uint16_t fp16_defaultNaN ()
static uint32_t fp32_defaultNaN ()
static uint64_t fp64_defaultNaN ()
static void fp16_unpack (int *sgn, int *exp, uint16_t *mnt, uint16_t x, int mode, int *flags)
static void fp32_unpack (int *sgn, int *exp, uint32_t *mnt, uint32_t x, int mode, int *flags)
static void fp64_unpack (int *sgn, int *exp, uint64_t *mnt, uint64_t x, int mode, int *flags)
static int fp16_is_NaN (int exp, uint16_t mnt)
static int fp32_is_NaN (int exp, uint32_t mnt)
static int fp64_is_NaN (int exp, uint64_t mnt)
static int fp16_is_signalling_NaN (int exp, uint16_t mnt)
static int fp32_is_signalling_NaN (int exp, uint32_t mnt)
static int fp64_is_signalling_NaN (int exp, uint64_t mnt)
static int fp16_is_quiet_NaN (int exp, uint16_t mnt)
static int fp32_is_quiet_NaN (int exp, uint32_t mnt)
static int fp64_is_quiet_NaN (int exp, uint64_t mnt)
static int fp16_is_infinity (int exp, uint16_t mnt)
static int fp32_is_infinity (int exp, uint32_t mnt)
static int fp64_is_infinity (int exp, uint64_t mnt)
static uint16_t fp16_process_NaN (uint16_t a, int mode, int *flags)
static uint32_t fp32_process_NaN (uint32_t a, int mode, int *flags)
static uint64_t fp64_process_NaN (uint64_t a, int mode, int *flags)
static uint16_t fp16_process_NaNs (uint16_t a, uint16_t b, int mode, int *flags)
static uint32_t fp32_process_NaNs (uint32_t a, uint32_t b, int mode, int *flags)
static uint64_t fp64_process_NaNs (uint64_t a, uint64_t b, int mode, int *flags)
static uint16_t fp16_process_NaNs3 (uint16_t a, uint16_t b, uint16_t c, int mode, int *flags)
static uint32_t fp32_process_NaNs3 (uint32_t a, uint32_t b, uint32_t c, int mode, int *flags)
static uint64_t fp64_process_NaNs3 (uint64_t a, uint64_t b, uint64_t c, int mode, int *flags)
static uint16_t fp16_round_ (int sgn, int exp, uint16_t mnt, int rm, int mode, int *flags)
static uint16_t fp16_round (int sgn, int exp, uint16_t mnt, int mode, int *flags)
static uint32_t fp32_round_ (int sgn, int exp, uint32_t mnt, int rm, int mode, int *flags)
static uint32_t fp32_round (int sgn, int exp, uint32_t mnt, int mode, int *flags)
static uint64_t fp64_round_ (int sgn, int exp, uint64_t mnt, int rm, int mode, int *flags)
static uint64_t fp64_round (int sgn, int exp, uint64_t mnt, int mode, int *flags)
static int fp16_compare_eq (uint16_t a, uint16_t b, int mode, int *flags)
static int fp16_compare_ge (uint16_t a, uint16_t b, int mode, int *flags)
static int fp16_compare_gt (uint16_t a, uint16_t b, int mode, int *flags)
static int fp16_compare_un (uint16_t a, uint16_t b, int mode, int *flags)
static int fp32_compare_eq (uint32_t a, uint32_t b, int mode, int *flags)
static int fp32_compare_ge (uint32_t a, uint32_t b, int mode, int *flags)
static int fp32_compare_gt (uint32_t a, uint32_t b, int mode, int *flags)
static int fp32_compare_un (uint32_t a, uint32_t b, int mode, int *flags)
static int fp64_compare_eq (uint64_t a, uint64_t b, int mode, int *flags)
static int fp64_compare_ge (uint64_t a, uint64_t b, int mode, int *flags)
static int fp64_compare_gt (uint64_t a, uint64_t b, int mode, int *flags)
static int fp64_compare_un (uint64_t a, uint64_t b, int mode, int *flags)
static uint16_t fp16_add (uint16_t a, uint16_t b, int neg, int mode, int *flags)
static uint32_t fp32_add (uint32_t a, uint32_t b, int neg, int mode, int *flags)
static uint64_t fp64_add (uint64_t a, uint64_t b, int neg, int mode, int *flags)
static uint16_t fp16_mul (uint16_t a, uint16_t b, int mode, int *flags)
static uint32_t fp32_mul (uint32_t a, uint32_t b, int mode, int *flags)
static uint64_t fp64_mul (uint64_t a, uint64_t b, int mode, int *flags)
static uint16_t fp16_muladd (uint16_t a, uint16_t b, uint16_t c, int scale, int mode, int *flags)
static uint32_t fp32_muladd (uint32_t a, uint32_t b, uint32_t c, int scale, int mode, int *flags)
static uint64_t fp64_muladd (uint64_t a, uint64_t b, uint64_t c, int scale, int mode, int *flags)
static uint16_t fp16_div (uint16_t a, uint16_t b, int mode, int *flags)
static uint32_t fp32_div (uint32_t a, uint32_t b, int mode, int *flags)
static uint64_t fp64_div (uint64_t a, uint64_t b, int mode, int *flags)
static void set_fpscr0 (FPSCR &fpscr, int flags)
static uint16_t fp16_scale (uint16_t a, int16_t b, int mode, int *flags)
static uint32_t fp32_scale (uint32_t a, int32_t b, int mode, int *flags)
static uint64_t fp64_scale (uint64_t a, int64_t b, int mode, int *flags)
static uint16_t fp16_sqrt (uint16_t a, int mode, int *flags)
static uint32_t fp32_sqrt (uint32_t a, int mode, int *flags)
static uint64_t fp64_sqrt (uint64_t a, int mode, int *flags)
static int modeConv (FPSCR fpscr)
static void set_fpscr (FPSCR &fpscr, int flags)
template<>
bool fplibCompareEQ (uint16_t a, uint16_t b, FPSCR &fpscr)
template<>
bool fplibCompareGE (uint16_t a, uint16_t b, FPSCR &fpscr)
template<>
bool fplibCompareGT (uint16_t a, uint16_t b, FPSCR &fpscr)
template<>
bool fplibCompareUN (uint16_t a, uint16_t b, FPSCR &fpscr)
template<>
bool fplibCompareEQ (uint32_t a, uint32_t b, FPSCR &fpscr)
template<>
bool fplibCompareGE (uint32_t a, uint32_t b, FPSCR &fpscr)
template<>
bool fplibCompareGT (uint32_t a, uint32_t b, FPSCR &fpscr)
template<>
bool fplibCompareUN (uint32_t a, uint32_t b, FPSCR &fpscr)
template<>
bool fplibCompareEQ (uint64_t a, uint64_t b, FPSCR &fpscr)
template<>
bool fplibCompareGE (uint64_t a, uint64_t b, FPSCR &fpscr)
template<>
bool fplibCompareGT (uint64_t a, uint64_t b, FPSCR &fpscr)
template<>
bool fplibCompareUN (uint64_t a, uint64_t b, FPSCR &fpscr)
template<>
uint16_t fplibAbs (uint16_t op)
template<>
uint32_t fplibAbs (uint32_t op)
template<>
uint64_t fplibAbs (uint64_t op)
template<>
uint16_t fplibAdd (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibAdd (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibAdd (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
int fplibCompare (uint16_t op1, uint16_t op2, bool signal_nans, FPSCR &fpscr)
template<>
int fplibCompare (uint32_t op1, uint32_t op2, bool signal_nans, FPSCR &fpscr)
template<>
int fplibCompare (uint64_t op1, uint64_t op2, bool signal_nans, FPSCR &fpscr)
static uint16_t fp16_FPConvertNaN_32 (uint32_t op)
static uint16_t fp16_FPConvertNaN_64 (uint64_t op)
static uint32_t fp32_FPConvertNaN_16 (uint16_t op)
static uint32_t fp32_FPConvertNaN_64 (uint64_t op)
static uint64_t fp64_FPConvertNaN_16 (uint16_t op)
static uint64_t fp64_FPConvertNaN_32 (uint32_t op)
static uint16_t fp16_FPOnePointFive (int sgn)
static uint32_t fp32_FPOnePointFive (int sgn)
static uint64_t fp64_FPOnePointFive (int sgn)
static uint16_t fp16_FPThree (int sgn)
static uint32_t fp32_FPThree (int sgn)
static uint64_t fp64_FPThree (int sgn)
static uint16_t fp16_FPTwo (int sgn)
static uint32_t fp32_FPTwo (int sgn)
static uint64_t fp64_FPTwo (int sgn)
template<>
uint16_t fplibConvert (uint32_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint16_t fplibConvert (uint64_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint32_t fplibConvert (uint16_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint32_t fplibConvert (uint64_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint64_t fplibConvert (uint16_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint64_t fplibConvert (uint32_t op, FPRounding rounding, FPSCR &fpscr)
template<>
uint16_t fplibMulAdd (uint16_t addend, uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMulAdd (uint32_t addend, uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMulAdd (uint64_t addend, uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibDiv (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibDiv (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibDiv (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibExpA (uint16_t op)
template<>
uint32_t fplibExpA (uint32_t op)
template<>
uint64_t fplibExpA (uint64_t op)
static uint16_t fp16_repack (int sgn, int exp, uint16_t mnt)
static uint32_t fp32_repack (int sgn, int exp, uint32_t mnt)
static uint64_t fp64_repack (int sgn, int exp, uint64_t mnt)
static void fp16_minmaxnum (uint16_t *op1, uint16_t *op2, int sgn)
static void fp32_minmaxnum (uint32_t *op1, uint32_t *op2, int sgn)
static void fp64_minmaxnum (uint64_t *op1, uint64_t *op2, int sgn)
template<>
uint16_t fplibMax (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMax (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMax (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibMaxNum (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMaxNum (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMaxNum (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibMin (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMin (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMin (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibMinNum (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMinNum (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMinNum (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibMul (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMul (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMul (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibMulX (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibMulX (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibMulX (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibNeg (uint16_t op)
template<>
uint32_t fplibNeg (uint32_t op)
template<>
uint64_t fplibNeg (uint64_t op)
template<>
uint16_t fplibRSqrtEstimate (uint16_t op, FPSCR &fpscr)
template<>
uint32_t fplibRSqrtEstimate (uint32_t op, FPSCR &fpscr)
template<>
uint64_t fplibRSqrtEstimate (uint64_t op, FPSCR &fpscr)
template<>
uint16_t fplibRSqrtStepFused (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibRSqrtStepFused (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibRSqrtStepFused (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibRecipEstimate (uint16_t op, FPSCR &fpscr)
template<>
uint32_t fplibRecipEstimate (uint32_t op, FPSCR &fpscr)
template<>
uint64_t fplibRecipEstimate (uint64_t op, FPSCR &fpscr)
template<>
uint16_t fplibRecipStepFused (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibRecipStepFused (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibRecipStepFused (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibRecpX (uint16_t op, FPSCR &fpscr)
template<>
uint32_t fplibRecpX (uint32_t op, FPSCR &fpscr)
template<>
uint64_t fplibRecpX (uint64_t op, FPSCR &fpscr)
template<>
uint16_t fplibRoundInt (uint16_t op, FPRounding rounding, bool exact, FPSCR &fpscr)
template<>
uint32_t fplibRoundInt (uint32_t op, FPRounding rounding, bool exact, FPSCR &fpscr)
template<>
uint64_t fplibRoundInt (uint64_t op, FPRounding rounding, bool exact, FPSCR &fpscr)
template<>
uint16_t fplibScale (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibScale (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibScale (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibSqrt (uint16_t op, FPSCR &fpscr)
template<>
uint32_t fplibSqrt (uint32_t op, FPSCR &fpscr)
template<>
uint64_t fplibSqrt (uint64_t op, FPSCR &fpscr)
template<>
uint16_t fplibSub (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibSub (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibSub (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibTrigMulAdd (uint8_t coeff_index, uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibTrigMulAdd (uint8_t coeff_index, uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibTrigMulAdd (uint8_t coeff_index, uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibTrigSMul (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibTrigSMul (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibTrigSMul (uint64_t op1, uint64_t op2, FPSCR &fpscr)
template<>
uint16_t fplibTrigSSel (uint16_t op1, uint16_t op2, FPSCR &fpscr)
template<>
uint32_t fplibTrigSSel (uint32_t op1, uint32_t op2, FPSCR &fpscr)
template<>
uint64_t fplibTrigSSel (uint64_t op1, uint64_t op2, FPSCR &fpscr)
static uint64_t FPToFixed_64 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int *flags)
static uint32_t FPToFixed_32 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int *flags)
static uint16_t FPToFixed_16 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int *flags)
template<>
uint16_t fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint32_t fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint32_t fplibFPToFixed (uint32_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint32_t fplibFPToFixed (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint64_t fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint64_t fplibFPToFixed (uint32_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
template<>
uint64_t fplibFPToFixed (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
static uint16_t fp16_cvtf (uint64_t a, int fbits, int u, int mode, int *flags)
static uint32_t fp32_cvtf (uint64_t a, int fbits, int u, int mode, int *flags)
static uint64_t fp64_cvtf (uint64_t a, int fbits, int u, int mode, int *flags)
template<>
uint16_t fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
Floating-point convert from fixed-point.
template<>
uint32_t fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
Floating-point convert from fixed-point.
template<>
uint64_t fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
Floating-point convert from fixed-point.
template<>
uint16_t fplibInfinity (int sgn)
Floating-point value for +/- infinity.
template<>
uint32_t fplibInfinity (int sgn)
Floating-point value for +/- infinity.
template<>
uint64_t fplibInfinity (int sgn)
Floating-point value for +/- infinity.
template<>
uint16_t fplibDefaultNaN ()
Foating-point value for default NaN.
template<>
uint32_t fplibDefaultNaN ()
Foating-point value for default NaN.
template<>
uint64_t fplibDefaultNaN ()
Foating-point value for default NaN.
static FPRounding FPCRRounding (FPSCR &fpscr)
template<class T >
T fplibAbs (T op)
Floating-point absolute value.
template<class T >
T fplibAdd (T op1, T op2, FPSCR &fpscr)
Floating-point add.
template<class T >
int fplibCompare (T op1, T op2, bool signal_nans, FPSCR &fpscr)
Floating-point compare (quiet and signaling).
template<class T >
bool fplibCompareEQ (T op1, T op2, FPSCR &fpscr)
Floating-point compare equal.
template<class T >
bool fplibCompareGE (T op1, T op2, FPSCR &fpscr)
Floating-point compare greater than or equal.
template<class T >
bool fplibCompareGT (T op1, T op2, FPSCR &fpscr)
Floating-point compare greater than.
template<class T >
bool fplibCompareUN (T op1, T op2, FPSCR &fpscr)
Floating-point compare unordered.
template<class T1 , class T2 >
T2 fplibConvert (T1 op, FPRounding rounding, FPSCR &fpscr)
Floating-point convert precision.
template<class T >
T fplibDiv (T op1, T op2, FPSCR &fpscr)
Floating-point division.
template<class T >
T fplibExpA (T op)
Floating-point exponential accelerator.
template<class T >
T fplibMax (T op1, T op2, FPSCR &fpscr)
Floating-point maximum.
template<class T >
T fplibMaxNum (T op1, T op2, FPSCR &fpscr)
Floating-point maximum number.
template<class T >
T fplibMin (T op1, T op2, FPSCR &fpscr)
Floating-point minimum.
template<class T >
T fplibMinNum (T op1, T op2, FPSCR &fpscr)
Floating-point minimum number.
template<class T >
T fplibMul (T op1, T op2, FPSCR &fpscr)
Floating-point multiply.
template<class T >
T fplibMulAdd (T addend, T op1, T op2, FPSCR &fpscr)
Floating-point multiply-add.
template<class T >
T fplibMulX (T op1, T op2, FPSCR &fpscr)
Floating-point multiply extended.
template<class T >
T fplibNeg (T op)
Floating-point negate.
template<class T >
T fplibRSqrtEstimate (T op, FPSCR &fpscr)
Floating-point reciprocal square root estimate.
template<class T >
T fplibRSqrtStepFused (T op1, T op2, FPSCR &fpscr)
Floating-point reciprocal square root step.
template<class T >
T fplibRecipEstimate (T op, FPSCR &fpscr)
Floating-point reciprocal estimate.
template<class T >
T fplibRecipStepFused (T op1, T op2, FPSCR &fpscr)
Floating-point reciprocal step.
template<class T >
T fplibRecpX (T op, FPSCR &fpscr)
Floating-point reciprocal exponent.
template<class T >
T fplibRoundInt (T op, FPRounding rounding, bool exact, FPSCR &fpscr)
Floating-point convert to integer.
template<class T >
T fplibScale (T op1, T op2, FPSCR &fpscr)
Floating-point adjust exponent.
template<class T >
T fplibSqrt (T op, FPSCR &fpscr)
Floating-point square root.
template<class T >
T fplibSub (T op1, T op2, FPSCR &fpscr)
Floating-point subtract.
template<class T >
T fplibTrigMulAdd (uint8_t coeff_index, T op1, T op2, FPSCR &fpscr)
Floating-point trigonometric multiply-add coefficient.
template<class T >
T fplibTrigSMul (T op1, T op2, FPSCR &fpscr)
Floating-point trigonometric starting value.
template<class T >
T fplibTrigSSel (T op1, T op2, FPSCR &fpscr)
Floating-point trigonometric select coefficient.
template<class T1 , class T2 >
T2 fplibFPToFixed (T1 op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
Floating-point convert to fixed-point.
template<class T >
T fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR &fpscr)
Floating-point convert from fixed-point.
template<class T >
T fplibInfinity (int sgn)
Floating-point value for +/- infinity.
template<class T >
T fplibDefaultNaN ()
Foating-point value for default NaN.
static unsigned int number_of_ones (int32_t val)
void writeVecElem (VReg *dest, XReg src, int index, int eSize)
Write a single NEON vector element leaving the others untouched.
XReg readVecElem (VReg src, int index, int eSize)
Read a single NEON vector element.
static uint32_t rotate_imm (uint32_t immValue, uint32_t rotateValue)
static uint32_t modified_imm (uint8_t ctrlImm, uint8_t dataImm)
static uint64_t simd_modified_imm (bool op, uint8_t cmode, uint8_t data, bool &immValid, bool isAarch64=false)
static uint64_t vfp_modified_imm (uint8_t data, FpDataType dtype)
static FpDataType decode_fp_data_type (uint8_t encoding)
static uint8_t getRestoredITBits (ThreadContext *tc, CPSR spsr)
static bool illegalExceptionReturn (ThreadContext *tc, CPSR cpsr, CPSR spsr)
const char * svePredTypeToStr (SvePredType pt)
Returns the specifier for the predication type pt as a string.
std::string sveDisasmPredCountImm (uint8_t imm)
Returns the symbolic name associated with pattern imm for PTRUE(S) instructions.
unsigned int sveDecodePredCount (uint8_t imm, unsigned int num_elems)
Returns the actual number of elements active for PTRUE(S) instructions.
uint64_t sveExpandFpImmAddSub (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.5 or 1.0 (FADD, FSUB, FSUBR).
uint64_t sveExpandFpImmMaxMin (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.0 or 1.0 (FMAX, FMAXNM, FMIN, FMINNM).
uint64_t sveExpandFpImmMul (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.5 or 2.0 (FMUL).
VfpSavedState prepFpState (uint32_t rMode)
void finishVfp (FPSCR &fpscr, VfpSavedState state, bool flush, FPSCR mask)
template<class fpType >
fpType fixDest (bool flush, bool defaultNan, fpType val, fpType op1)
template float fixDest< float > (bool flush, bool defaultNan, float val, float op1)
template double fixDest< double > (bool flush, bool defaultNan, double val, double op1)
template<class fpType >
fpType fixDest (bool flush, bool defaultNan, fpType val, fpType op1, fpType op2)
template float fixDest< float > (bool flush, bool defaultNan, float val, float op1, float op2)
template double fixDest< double > (bool flush, bool defaultNan, double val, double op1, double op2)
template<class fpType >
fpType fixDivDest (bool flush, bool defaultNan, fpType val, fpType op1, fpType op2)
template float fixDivDest< float > (bool flush, bool defaultNan, float val, float op1, float op2)
template double fixDivDest< double > (bool flush, bool defaultNan, double val, double op1, double op2)
float fixFpDFpSDest (FPSCR fpscr, double val)
double fixFpSFpDDest (FPSCR fpscr, float val)
static uint16_t vcvtFpFpH (FPSCR &fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, uint64_t opBits, bool isDouble)
uint16_t vcvtFpSFpH (FPSCR &fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, float op)
uint16_t vcvtFpDFpH (FPSCR &fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, double op)
static uint64_t vcvtFpHFp (FPSCR &fpscr, bool defaultNan, bool ahp, uint16_t op, bool isDouble)
double vcvtFpHFpD (FPSCR &fpscr, bool defaultNan, bool ahp, uint16_t op)
float vcvtFpHFpS (FPSCR &fpscr, bool defaultNan, bool ahp, uint16_t op)
float vfpUFixedToFpS (bool flush, bool defaultNan, uint64_t val, uint8_t width, uint8_t imm)
float vfpSFixedToFpS (bool flush, bool defaultNan, int64_t val, uint8_t width, uint8_t imm)
double vfpUFixedToFpD (bool flush, bool defaultNan, uint64_t val, uint8_t width, uint8_t imm)
double vfpSFixedToFpD (bool flush, bool defaultNan, int64_t val, uint8_t width, uint8_t imm)
static double recipSqrtEstimate (double a)
float fprSqrtEstimate (FPSCR &fpscr, float op)
uint32_t unsignedRSqrtEstimate (uint32_t op)
static double recipEstimate (double a)
float fpRecipEstimate (FPSCR &fpscr, float op)
uint32_t unsignedRecipEstimate (uint32_t op)
FPSCR fpStandardFPSCRValue (const FPSCR &fpscr)
template<class T >
static void setVfpMicroFlags (VfpMicroMode mode, T &flags)
static float bitsToFp (uint64_t, float)
static double bitsToFp (uint64_t, double)
static uint32_t fpToBits (float)
static uint64_t fpToBits (double)
template<class fpType >
static bool flushToZero (fpType &op)
template<class fpType >
static bool flushToZero (fpType &op1, fpType &op2)
template<class fpType >
static void vfpFlushToZero (FPSCR &fpscr, fpType &op)
template<class fpType >
static void vfpFlushToZero (FPSCR &fpscr, fpType &op1, fpType &op2)
template<class fpType >
static bool isSnan (fpType val)
template<class fpType >
fpType fixDest (FPSCR fpscr, fpType val, fpType op1)
template<class fpType >
fpType fixDest (FPSCR fpscr, fpType val, fpType op1, fpType op2)
template<class fpType >
fpType fixDivDest (FPSCR fpscr, fpType val, fpType op1, fpType op2)
static double makeDouble (uint32_t low, uint32_t high)
static uint32_t lowFromDouble (double val)
static uint32_t highFromDouble (double val)
static void setFPExceptions (int exceptions)
template<typename T >
uint64_t vfpFpToFixed (T val, bool isSigned, uint8_t width, uint8_t imm, bool useRmode=true, VfpRoundingMode roundMode=VfpRoundZero, bool aarch64=false)
template<typename T >
static T fpAdd (T a, T b)
template<typename T >
static T fpSub (T a, T b)
static float fpAddS (float a, float b)
static double fpAddD (double a, double b)
static float fpSubS (float a, float b)
static double fpSubD (double a, double b)
static float fpDivS (float a, float b)
static double fpDivD (double a, double b)
template<typename T >
static T fpDiv (T a, T b)
template<typename T >
static T fpMulX (T a, T b)
template<typename T >
static T fpMul (T a, T b)
static float fpMulS (float a, float b)
static double fpMulD (double a, double b)
template<typename T >
static T fpMulAdd (T op1, T op2, T addend)
template<typename T >
static T fpRIntX (T a, FPSCR &fpscr)
template<typename T >
static T fpMaxNum (T a, T b)
template<typename T >
static T fpMax (T a, T b)
template<typename T >
static T fpMinNum (T a, T b)
template<typename T >
static T fpMin (T a, T b)
template<typename T >
static T fpRSqrts (T a, T b)
template<typename T >
static T fpRecps (T a, T b)
static float fpRSqrtsS (float a, float b)
static float fpRecpsS (float a, float b)
template<typename T >
static T roundNEven (T a)
static IntRegIndex INTREG_USR (unsigned index)
static IntRegIndex INTREG_HYP (unsigned index)
static IntRegIndex INTREG_SVC (unsigned index)
static IntRegIndex INTREG_MON (unsigned index)
static IntRegIndex INTREG_ABT (unsigned index)
static IntRegIndex INTREG_UND (unsigned index)
static IntRegIndex INTREG_IRQ (unsigned index)
static IntRegIndex INTREG_FIQ (unsigned index)
static int intRegInMode (OperatingMode mode, int reg)
static int flattenIntRegModeIndex (int reg)
static IntRegIndex makeSP (IntRegIndex reg)
static IntRegIndex makeZero (IntRegIndex reg)
static bool isSP (IntRegIndex reg)
Addr VAddrImpl (Addr a)
Addr VAddrVPN (Addr a)
Addr VAddrOffset (Addr a)
template<class XC >
void handleLockedSnoop (XC *xc, PacketPtr pkt, Addr cacheBlockMask)
template<class XC >
void handleLockedRead (XC *xc, const RequestPtr &req)
template<class XC >
void handleLockedSnoopHit (XC *xc)
template<class XC >
bool handleLockedWrite (XC *xc, const RequestPtr &req, Addr cacheBlockMask)
template<class XC >
void globalClearExclusive (XC *xc)
MiscRegIndex decodeCP14Reg (unsigned crn, unsigned opc1, unsigned crm, unsigned opc2)
MiscRegIndex decodeCP15Reg (unsigned crn, unsigned opc1, unsigned crm, unsigned opc2)
MiscRegIndex decodeCP15Reg64 (unsigned crm, unsigned opc1)
std::tuple< bool, bool > canReadCoprocReg (MiscRegIndex reg, SCR scr, CPSR cpsr)
Check for permission to read coprocessor registers.
std::tuple< bool, bool > canWriteCoprocReg (MiscRegIndex reg, SCR scr, CPSR cpsr)
Check for permission to write coprocessor registers.
int snsBankedIndex (MiscRegIndex reg, ThreadContext *tc)
int snsBankedIndex (MiscRegIndex reg, ThreadContext *tc, bool ns)
int snsBankedIndex64 (MiscRegIndex reg, ThreadContext *tc)
void preUnflattenMiscReg ()
int unflattenMiscReg (int reg)
bool canReadAArch64SysReg (MiscRegIndex reg, SCR scr, CPSR cpsr, ThreadContext *tc)
bool canWriteAArch64SysReg (MiscRegIndex reg, SCR scr, CPSR cpsr, ThreadContext *tc)
MiscRegIndex decodeAArch64SysReg (unsigned op0, unsigned op1, unsigned crn, unsigned crm, unsigned op2)
bool aarch64SysRegReadOnly (MiscRegIndex miscReg)
BitUnion32 (CPSR) Bitfield< 31
EndBitUnion (CPSR) BitUnion64(AA64DFR0) Bitfield< 43
EndBitUnion (AA64DFR0) BitUnion64(AA64ISAR0) Bitfield< 63
EndBitUnion (AA64ISAR0) BitUnion64(AA64ISAR1) Bitfield< 43
EndBitUnion (AA64ISAR1) BitUnion64(AA64MMFR0) Bitfield< 47
EndBitUnion (AA64MMFR0) BitUnion64(AA64MMFR1) Bitfield< 31
EndBitUnion (AA64MMFR1) BitUnion64(AA64MMFR2) Bitfield< 63
EndBitUnion (AA64MMFR2) BitUnion64(AA64PFR0) Bitfield< 63
EndBitUnion (AA64PFR0) BitUnion32(HDCR) Bitfield< 11 > tdra
EndBitUnion (HDCR) BitUnion32(HCPTR) Bitfield< 31 > tcpac
EndBitUnion (HCPTR) BitUnion32(HSTR) Bitfield< 17 > tjdbx
EndBitUnion (HSTR) BitUnion64(HCR) Bitfield< 34 > e2h
EndBitUnion (HCR) BitUnion32(NSACR) Bitfield< 20 > nstrcdis
EndBitUnion (NSACR) BitUnion32(SCR) Bitfield< 13 > twe
EndBitUnion (SCR) BitUnion32(SCTLR) Bitfield< 30 > te
EndBitUnion (SCTLR) BitUnion32(CPACR) Bitfield< 1
EndBitUnion (CPACR) BitUnion32(FSR) Bitfield< 3
EndBitUnion (FSR) BitUnion32(FPSCR) Bitfield< 0 > ioc
EndBitUnion (FPSCR) BitUnion32(FPEXC) Bitfield< 31 > ex
EndBitUnion (FPEXC) BitUnion32(MVFR0) Bitfield< 3
EndBitUnion (MVFR0) BitUnion32(MVFR1) Bitfield< 3
EndBitUnion (MVFR1) BitUnion64(TTBCR) Bitfield< 2
EndBitUnion (TTBCR) BitUnion64(TCR) Bitfield< 5
EndBitUnion (TCR) BitUnion32(HTCR) Bitfield< 2
EndBitUnion (HTCR) BitUnion32(VTCR_t) Bitfield< 3
EndBitUnion (VTCR_t) BitUnion32(PRRR) Bitfield< 1
EndBitUnion (PRRR) BitUnion32(NMRR) Bitfield< 1
EndBitUnion (NMRR) BitUnion32(CONTEXTIDR) Bitfield< 7
EndBitUnion (CONTEXTIDR) BitUnion32(L2CTLR) Bitfield< 2
EndBitUnion (L2CTLR) BitUnion32(CTR) Bitfield< 3
EndBitUnion (CTR) BitUnion32(PMSELR) Bitfield< 4
EndBitUnion (PMSELR) BitUnion64(PAR) Bitfield< 63
EndBitUnion (PAR) BitUnion32(ESR) Bitfield< 31
EndBitUnion (ESR) BitUnion32(CPTR) Bitfield< 31 > tcpac
EndBitUnion (CPTR) BitUnion64(ZCR) Bitfield< 3
static int32_t readSymbol (ThreadContext *tc, const std::string name)
template<typename T >
TLB * getITBPtr (T *tc)
template<typename T >
TLB * getDTBPtr (T *tc)
BitUnion8 (ITSTATE) Bitfield< 7
EndBitUnion (ITSTATE) BitUnion64(ExtMachInst) Bitfield< 63
SubBitUnion (puswl, 24, 20) Bitfield< 24 > prepost
EndSubBitUnion (puswl) Bitfield< 24
EndBitUnion (ExtMachInst) class PCState
BitUnion8 (OperatingMode64) Bitfield< 0 > spX
EndBitUnion (OperatingMode64) static bool inline opModeIs64(OperatingMode mode)
static bool opModeIsH (OperatingMode mode)
static bool opModeIsT (OperatingMode mode)
static ExceptionLevel opModeToEL (OperatingMode mode)
static bool unknownMode (OperatingMode mode)
static bool unknownMode32 (OperatingMode mode)
void initCPU (ThreadContext *tc, int cpuId)
uint64_t getArgument (ThreadContext *tc, int &number, uint16_t size, bool fp)
void skipFunction (ThreadContext *tc)
static void copyVecRegs (ThreadContext *src, ThreadContext *dest)
void copyRegs (ThreadContext *src, ThreadContext *dest)
void sendEvent (ThreadContext *tc)
Send an event (SEV) to a specific PE if there isn't already a pending event.
bool inSecureState (ThreadContext *tc)
bool isSecureBelowEL3 (ThreadContext *tc)
Return TRUE if an Exception level below EL3 is in Secure state.
bool inAArch64 (ThreadContext *tc)
bool longDescFormatInUse (ThreadContext *tc)
RegVal readMPIDR (ArmSystem *arm_sys, ThreadContext *tc)
This helper function is either returing the value of MPIDR_EL1 (by calling getMPIDR), or it is issuing a read to VMPIDR_EL2 (as it happens in virtualized systems)
RegVal getMPIDR (ArmSystem *arm_sys, ThreadContext *tc)
This helper function is returing the value of MPIDR_EL1.
bool ELIs64 (ThreadContext *tc, ExceptionLevel el)
bool ELIs32 (ThreadContext *tc, ExceptionLevel el)
bool ELIsInHost (ThreadContext *tc, ExceptionLevel el)
Returns true if the current exception level el is executing a Host OS or an application of a Host OS (Armv8.1 Virtualization Host Extensions).
std::pair< bool, bool > ELUsingAArch32K (ThreadContext *tc, ExceptionLevel el)
This function checks whether selected EL provided as an argument is using the AArch32 ISA.
bool isBigEndian64 (ThreadContext *tc)
bool badMode32 (ThreadContext *tc, OperatingMode mode)
badMode is checking if the execution mode provided as an argument is valid and implemented for AArch32
bool badMode (ThreadContext *tc, OperatingMode mode)
badMode is checking if the execution mode provided as an argument is valid and implemented.
Addr purifyTaggedAddr (Addr addr, ThreadContext *tc, ExceptionLevel el, TTBCR tcr)
Removes the tag from tagged addresses if that mode is enabled.
Addr purifyTaggedAddr (Addr addr, ThreadContext *tc, ExceptionLevel el)
Addr truncPage (Addr addr)
Addr roundPage (Addr addr)
bool mcrMrc15TrapToHyp (const MiscRegIndex miscReg, ThreadContext *tc, uint32_t iss)
bool mcrMrc14TrapToHyp (const MiscRegIndex miscReg, HCR hcr, CPSR cpsr, SCR scr, HDCR hdcr, HSTR hstr, HCPTR hcptr, uint32_t iss)
bool mcrrMrrc15TrapToHyp (const MiscRegIndex miscReg, CPSR cpsr, SCR scr, HSTR hstr, HCR hcr, uint32_t iss)
bool decodeMrsMsrBankedReg (uint8_t sysM, bool r, bool &isIntReg, int &regIdx, CPSR cpsr, SCR scr, NSACR nsacr, bool checkSecurity)
bool SPAlignmentCheckEnabled (ThreadContext *tc)
int decodePhysAddrRange64 (uint8_t pa_enc)
Returns the n.
uint8_t encodePhysAddrRange64 (int pa_size)
Returns the encoding corresponding to the specified n.
PCState buildRetPC (const PCState &curPC, const PCState &callPC)
bool testPredicate (uint32_t nz, uint32_t c, uint32_t v, ConditionCode code)
template<class TC >
void zeroRegisters (TC *tc)
Function to insure ISA semantics about 0 registers.
void startupCPU (ThreadContext *tc, int cpuId)
static void copyMiscRegs (ThreadContext *src, ThreadContext *dest)
static bool inUserMode (CPSR cpsr)
static bool inUserMode (ThreadContext *tc)
static bool inPrivilegedMode (CPSR cpsr)
static bool inPrivilegedMode (ThreadContext *tc)
static OperatingMode currOpMode (ThreadContext *tc)
static ExceptionLevel currEL (ThreadContext *tc)
ExceptionLevel currEL (CPSR cpsr)
static uint8_t itState (CPSR psr)
static bool inSecureState (SCR scr, CPSR cpsr)
static uint32_t mcrMrcIssBuild (bool isRead, uint32_t crm, IntRegIndex rt, uint32_t crn, uint32_t opc1, uint32_t opc2)
static void mcrMrcIssExtract (uint32_t iss, bool &isRead, uint32_t &crm, IntRegIndex &rt, uint32_t &crn, uint32_t &opc1, uint32_t &opc2)
static uint32_t mcrrMrrcIssBuild (bool isRead, uint32_t crm, IntRegIndex rt, IntRegIndex rt2, uint32_t opc1)
static uint32_t msrMrs64IssBuild (bool isRead, uint32_t op0, uint32_t op1, uint32_t crn, uint32_t crm, uint32_t op2, IntRegIndex rt)
void advancePC (PCState &pc, const StaticInstPtr &inst)
uint64_t getExecutingAsid (ThreadContext *tc)
static int decodeMrsMsrBankedIntRegIndex (uint8_t sysM, bool r)
ByteOrder byteOrder (ThreadContext *tc)
Addr PteAddr (Addr a)
Addr vtophys (Addr vaddr)
Addr vtophys (ThreadContext *tc, Addr vaddr)
bool virtvalid (ThreadContext *tc, Addr vaddr)
Variables
const char *const ccRegName [NUM_CCREGS]
static const uint8_t recip_sqrt_estimate [256]
const IntRegMap IntReg64Map
const IntRegMap IntRegUsrMap
const IntRegMap IntRegHypMap
const IntRegMap IntRegSvcMap
const IntRegMap IntRegMonMap
const IntRegMap IntRegAbtMap
const IntRegMap IntRegUndMap
const IntRegMap IntRegIrqMap
const IntRegMap IntRegFiqMap
static const unsigned intRegsPerMode = NUM_INTREGS
const ByteOrder GuestByteOrder = LittleEndianByteOrder
StaticInstPtr decodeInst (ExtMachInst)
const Addr PageShift = 12
const Addr PageBytes = ULL(1) << PageShift
const Addr Page_Mask = ~(PageBytes - 1)
const Addr PageOffset = PageBytes - 1
const Addr PteShift = 3
const Addr NPtePageShift = PageShift - PteShift
const Addr NPtePage = ULL(1) << NPtePageShift
const Addr PteMask = NPtePage - 1
const Addr USegBase = ULL(0x0)
const Addr USegEnd = ULL(0x7FFFFFFF)
const unsigned VABits = 32
const unsigned PABits = 32
const Addr VAddrImplMask = (ULL(1) << VABits) - 1
const Addr VAddrUnImplMask = ~VAddrImplMask
const Addr PAddrImplMask = (ULL(1) << PABits) - 1
const unsigned MaxPhysAddrRange = 48
const int MachineBytes = 4
const uint32_t HighVecs = 0xFFFF0000
const bool HasUnalignedMemAcc = true
const bool CurThreadInfoImplemented = false
const int CurThreadInfoReg = -1
int unflattenResultMiscReg [NUM_MISCREGS]
If the reg is a child reg of a banked set, then the parent is the last banked one in the list.
bitset< NUM_MISCREG_INFOS > miscRegInfo [NUM_MISCREGS]
const char *const miscRegName []
static const uint32_t CondCodesMask = 0xF00F0000
static const uint32_t CpsrMaskQ = 0x08000000
static const uint32_t ApsrMask = CpsrMaskQ | CondCodesMask | 0x000001D0
static const uint32_t CpsrMask = ApsrMask | 0x00F003DF
static const uint32_t FpCondCodesMask = 0xF0000000
static const uint32_t FpscrExcMask = 0x0000009F
static const uint32_t FpscrQcMask = 0x08000000
nz
Bitfield< 29 > c
Bitfield< 28 > v
Bitfield< 27 > q
Bitfield< 26, 25 > it1
Bitfield< 24 > j
Bitfield< 22 > pan
Bitfield< 21 > ss
Bitfield< 20 > il
Bitfield< 19, 16 > ge
Bitfield< 15, 10 > it2
Bitfield< 9 > d
Bitfield< 9 > e
Bitfield< 8 > a
Bitfield< 7 > i
Bitfield< 6 > f
Bitfield< 8, 6 > aif
Bitfield< 9, 6 > daif
Bitfield< 5 > t
Bitfield< 4 > width
Bitfield< 3, 2 > el
Bitfield< 4, 0 > mode
Bitfield< 0 > sp
tracefilt
Bitfield< 39, 36 > doublelock
Bitfield< 35, 32 > pmsver
Bitfield< 31, 28 > ctx_cmps
Bitfield< 23, 20 > wrps
Bitfield< 15, 12 > brps
Bitfield< 11, 8 > pmuver
Bitfield< 7, 4 > tracever
Bitfield< 3, 0 > debugver
rndr
Bitfield< 59, 56 > tlb
Bitfield< 55, 52 > ts
Bitfield< 51, 48 > fhm
Bitfield< 47, 44 > dp
Bitfield< 43, 40 > sm4
Bitfield< 39, 36 > sm3
Bitfield< 35, 32 > sha3
Bitfield< 31, 28 > rdm
Bitfield< 23, 20 > atomic
Bitfield< 19, 16 > crc32
Bitfield< 15, 12 > sha2
Bitfield< 11, 8 > sha1
Bitfield< 3, 0 > aes
specres
Bitfield< 39, 36 > sb
Bitfield< 35, 32 > frintts
Bitfield< 31, 28 > gpi
Bitfield< 27, 24 > gpa
Bitfield< 23, 20 > lrcpc
Bitfield< 19, 16 > fcma
Bitfield< 15, 12 > jscvt
Bitfield< 11, 8 > api
Bitfield< 7, 4 > apa
Bitfield< 3, 0 > dpb
exs
Bitfield< 43, 40 > tgran4_2
Bitfield< 39, 36 > tgran64_2
Bitfield< 35, 32 > tgran16_2
Bitfield< 31, 28 > tgran4
Bitfield< 27, 24 > tgran64
Bitfield< 23, 20 > tgran16
Bitfield< 19, 16 > bigendEL0
Bitfield< 15, 12 > snsmem
Bitfield< 11, 8 > bigend
Bitfield< 7, 4 > asidbits
Bitfield< 3, 0 > parange
xnx
Bitfield< 27, 24 > specsei
Bitfield< 19, 16 > lo
Bitfield< 15, 12 > hpds
Bitfield< 11, 8 > vh
Bitfield< 7, 4 > vmidbits
Bitfield< 3, 0 > hafdbs
e0pd
Bitfield< 59, 56 > evt
Bitfield< 55, 52 > bbm
Bitfield< 51, 48 > ttl
Bitfield< 43, 40 > fwb
Bitfield< 39, 36 > ids
Bitfield< 35, 32 > at
Bitfield< 31, 28 > st
Bitfield< 27, 24 > nv
Bitfield< 23, 20 > ccidx
Bitfield< 19, 16 > varange
Bitfield< 15, 12 > iesb
Bitfield< 11, 8 > lsm
Bitfield< 7, 4 > uao
Bitfield< 3, 0 > cnp
csv3
Bitfield< 59, 56 > csv2
Bitfield< 51, 48 > dit
Bitfield< 47, 44 > amu
Bitfield< 43, 40 > mpam
Bitfield< 39, 36 > sel2
Bitfield< 35, 32 > sve
Bitfield< 31, 28 > ras
Bitfield< 27, 24 > gic
Bitfield< 23, 20 > advsimd
Bitfield< 19, 16 > fp
Bitfield< 15, 12 > el3
Bitfield< 11, 8 > el2
Bitfield< 7, 4 > el1
Bitfield< 3, 0 > el0
Bitfield< 10 > tdosa
Bitfield< 9 > tda
Bitfield< 8 > tde
Bitfield< 7 > hpme
Bitfield< 6 > tpm
Bitfield< 5 > tpmcr
Bitfield< 4, 0 > hpmn
Bitfield< 20 > tta
Bitfield< 15 > tase
Bitfield< 13 > tcp13
Bitfield< 12 > tcp12
Bitfield< 11 > tcp11
Bitfield< 10 > tcp10
Bitfield< 10 > tfp
Bitfield< 9 > tcp9
Bitfield< 8 > tcp8
Bitfield< 8 > tz
Bitfield< 7 > tcp7
Bitfield< 6 > tcp6
Bitfield< 5 > tcp5
Bitfield< 4 > tcp4
Bitfield< 3 > tcp3
Bitfield< 2 > tcp2
Bitfield< 1 > tcp1
Bitfield< 0 > tcp0
Bitfield< 16 > ttee
Bitfield< 15 > t15
Bitfield< 13 > t13
Bitfield< 12 > t12
Bitfield< 11 > t11
Bitfield< 10 > t10
Bitfield< 9 > t9
Bitfield< 8 > t8
Bitfield< 7 > t7
Bitfield< 6 > t6
Bitfield< 5 > t5
Bitfield< 4 > t4
Bitfield< 3 > t3
Bitfield< 2 > t2
Bitfield< 1 > t1
Bitfield< 0 > t0
Bitfield< 33 > id
Bitfield< 32 > cd
Bitfield< 31 > rw
Bitfield< 30 > trvm
Bitfield< 29 > hcd
Bitfield< 28 > tdz
Bitfield< 27 > tge
Bitfield< 26 > tvm
Bitfield< 25 > ttlb
Bitfield< 24 > tpu
Bitfield< 23 > tpc
Bitfield< 22 > tsw
Bitfield< 21 > tac
Bitfield< 21 > tacr
Bitfield< 20 > tidcp
Bitfield< 19 > tsc
Bitfield< 18 > tid3
Bitfield< 17 > tid2
Bitfield< 16 > tid1
Bitfield< 15 > tid0
Bitfield< 14 > twe
Bitfield< 13 > twi
Bitfield< 12 > dc
Bitfield< 11, 10 > bsu
Bitfield< 9 > fb
Bitfield< 8 > va
Bitfield< 8 > vse
Bitfield< 7 > vi
Bitfield< 6 > vf
Bitfield< 5 > amo
Bitfield< 4 > imo
Bitfield< 3 > fmo
Bitfield< 2 > ptw
Bitfield< 1 > swio
Bitfield< 0 > vm
Bitfield< 19 > rfr
Bitfield< 15 > nsasedis
Bitfield< 14 > nsd32dis
Bitfield< 13 > cp13
Bitfield< 12 > cp12
Bitfield< 11 > cp11
Bitfield< 10 > cp10
Bitfield< 9 > cp9
Bitfield< 8 > cp8
Bitfield< 7 > cp7
Bitfield< 6 > cp6
Bitfield< 5 > cp5
Bitfield< 4 > cp4
Bitfield< 3 > cp3
Bitfield< 2 > cp2
Bitfield< 1 > cp1
Bitfield< 0 > cp0
Bitfield< 9 > sif
Bitfield< 8 > hce
Bitfield< 7 > scd
Bitfield< 7 > smd
Bitfield< 6 > nEt
Bitfield< 5 > aw
Bitfield< 4 > fw
Bitfield< 3 > ea
Bitfield< 2 > fiq
Bitfield< 1 > irq
Bitfield< 0 > ns
Bitfield< 29 > afe
Bitfield< 28 > tre
Bitfield< 27 > nmfi
Bitfield< 26 > uci
Bitfield< 25 > ee
Bitfield< 24 > e0e
Bitfield< 23 > span
Bitfield< 23 > xp
Bitfield< 22 > u
Bitfield< 21 > fi
Bitfield< 20 > uwxn
Bitfield< 19 > dz
Bitfield< 19 > wxn
Bitfield< 18 > ntwe
Bitfield< 18 > rao2
Bitfield< 16 > ntwi
Bitfield< 16 > rao3
Bitfield< 15 > uct
Bitfield< 14 > rr
Bitfield< 14 > dze
Bitfield< 11 > z
Bitfield< 10 > sw
Bitfield< 9, 8 > rs
Bitfield< 9 > uma
Bitfield< 8 > sed
Bitfield< 7 > b
Bitfield< 7 > itd
Bitfield< 6, 3 > rao4
Bitfield< 6 > thee
Bitfield< 5 > cp15ben
Bitfield< 4 > sa0
Bitfield< 3 > sa
Bitfield< 0 > m
Bitfield< 17, 16 > zen
Bitfield< 21, 20 > fpen
Bitfield< 29, 28 > rsvd
Bitfield< 30 > d32dis
Bitfield< 31 > asedis
fsLow
Bitfield< 5, 0 > status
Bitfield< 7, 4 > domain
Bitfield< 9 > lpae
Bitfield< 10 > fsHigh
Bitfield< 11 > wnr
Bitfield< 12 > ext
Bitfield< 13 > cm
Bitfield< 1 > dzc
Bitfield< 2 > ofc
Bitfield< 3 > ufc
Bitfield< 4 > ixc
Bitfield< 7 > idc
Bitfield< 8 > ioe
Bitfield< 10 > ofe
Bitfield< 11 > ufe
Bitfield< 12 > ixe
Bitfield< 15 > ide
Bitfield< 18, 16 > len
Bitfield< 19 > fz16
Bitfield< 21, 20 > stride
Bitfield< 23, 22 > rMode
Bitfield< 24 > fz
Bitfield< 25 > dn
Bitfield< 26 > ahp
Bitfield< 27 > qc
Bitfield< 31 > n
Bitfield< 30 > en
Bitfield< 29, 0 > subArchDefined
advSimdRegisters
Bitfield< 7, 4 > singlePrecision
Bitfield< 11, 8 > doublePrecision
Bitfield< 15, 12 > vfpExceptionTrapping
Bitfield< 19, 16 > divide
Bitfield< 23, 20 > squareRoot
Bitfield< 27, 24 > shortVectors
Bitfield< 31, 28 > roundingModes
flushToZero
Bitfield< 7, 4 > defaultNaN
Bitfield< 11, 8 > advSimdLoadStore
Bitfield< 15, 12 > advSimdInteger
Bitfield< 19, 16 > advSimdSinglePrecision
Bitfield< 23, 20 > advSimdHalfPrecision
Bitfield< 27, 24 > vfpHalfPrecision
Bitfield< 31, 28 > raz
Bitfield< 4 > pd0
Bitfield< 5 > pd1
Bitfield< 2, 0 > t0sz
Bitfield< 6 > t2e
Bitfield< 7 > epd0
Bitfield< 9, 8 > irgn0
Bitfield< 11, 10 > orgn0
Bitfield< 13, 12 > sh0
Bitfield< 14 > tg0
Bitfield< 18, 16 > t1sz
Bitfield< 22 > a1
Bitfield< 23 > epd1
Bitfield< 25, 24 > irgn1
Bitfield< 27, 26 > orgn1
Bitfield< 29, 28 > sh1
Bitfield< 30 > tg1
Bitfield< 34, 32 > ips
Bitfield< 36 > as
Bitfield< 37 > tbi0
Bitfield< 38 > tbi1
Bitfield< 31 > eae
Bitfield< 18, 16 > ps
Bitfield< 20 > tbi
Bitfield< 41 > hpd0
Bitfield< 42 > hpd1
Bitfield< 24 > hpd
Bitfield< 39 > ha
Bitfield< 40 > hd
Bitfield< 4 > s
Bitfield< 5, 0 > t0sz64
Bitfield< 7, 6 > sl0
tr0
Bitfield< 3, 2 > tr1
Bitfield< 5, 4 > tr2
Bitfield< 7, 6 > tr3
Bitfield< 9, 8 > tr4
Bitfield< 11, 10 > tr5
Bitfield< 13, 12 > tr6
Bitfield< 15, 14 > tr7
Bitfield< 16 > ds0
Bitfield< 17 > ds1
Bitfield< 18 > ns0
Bitfield< 19 > ns1
Bitfield< 24 > nos0
Bitfield< 25 > nos1
Bitfield< 26 > nos2
Bitfield< 27 > nos3
Bitfield< 28 > nos4
Bitfield< 29 > nos5
Bitfield< 30 > nos6
Bitfield< 31 > nos7
ir0
Bitfield< 3, 2 > ir1
Bitfield< 5, 4 > ir2
Bitfield< 7, 6 > ir3
Bitfield< 9, 8 > ir4
Bitfield< 11, 10 > ir5
Bitfield< 13, 12 > ir6
Bitfield< 15, 14 > ir7
Bitfield< 17, 16 > or0
Bitfield< 19, 18 > or1
Bitfield< 21, 20 > or2
Bitfield< 23, 22 > or3
Bitfield< 25, 24 > or4
Bitfield< 27, 26 > or5
Bitfield< 29, 28 > or6
Bitfield< 31, 30 > or7
asid
Bitfield< 31, 8 > procid
sataRAMLatency
Bitfield< 4, 3 > reserved_4_3
Bitfield< 5 > dataRAMSetup
Bitfield< 8, 6 > tagRAMLatency
Bitfield< 9 > tagRAMSetup
Bitfield< 11, 10 > dataRAMSlice
Bitfield< 12 > tagRAMSlice
Bitfield< 20, 13 > reserved_20_13
Bitfield< 21 > eccandParityEnable
Bitfield< 22 > reserved_22
Bitfield< 23 > interptCtrlPresent
Bitfield< 25, 24 > numCPUs
Bitfield< 30, 26 > reserved_30_26
Bitfield< 31 > l2rstDISABLE_monitor
iCacheLineSize
Bitfield< 13, 4 > raz_13_4
Bitfield< 15, 14 > l1IndexPolicy
Bitfield< 19, 16 > dCacheLineSize
Bitfield< 23, 20 > erg
Bitfield< 27, 24 > cwg
Bitfield< 28 > raz_28
Bitfield< 31, 29 > format
sel
attr
Bitfield< 39, 12 > pa
Bitfield< 8, 7 > sh
ec
Bitfield< 15, 0 > imm16
Bitfield< 13, 12 > res1_13_12_el2
Bitfield< 9 > res1_9_el2
Bitfield< 8 > res1_8_el2
Bitfield< 8 > ez
Bitfield< 7, 0 > res1_7_0_el2
const int MaxInstSrcRegs
constexpr unsigned NumVecElemPerNeonVecReg = 4
constexpr unsigned NumVecElemPerVecReg = MaxSveVecLenInWords
const int NumIntArchRegs = NUM_ARCH_INTREGS
const int NumFloatV7ArchRegs = 64
const int NumFloatV8ArchRegs = 128
const int NumVecV7ArchRegs = 64
const int NumVecV8ArchRegs = 32
const int NumVecSpecialRegs = 8
const int NumVecIntrlvRegs = 4
const int NumIntRegs = NUM_INTREGS
const int NumFloatRegs = 0
const int NumVecRegs = NumVecV8ArchRegs + NumVecSpecialRegs + NumVecIntrlvRegs
const int VECREG_UREG0 = 32
const int NumVecPredRegs = 18
const int PREDREG_FFR = 16
const int PREDREG_UREG0 = 17
const int NumCCRegs = NUM_CCREGS
const int NumMiscRegs = NUM_MISCREGS
const int INTRLVREG0 = NumVecV8ArchRegs + NumVecSpecialRegs
const int INTRLVREG1 = INTRLVREG0 + 1
const int INTRLVREG2 = INTRLVREG0 + 2
const int INTRLVREG3 = INTRLVREG0 + 3
const int TotalNumRegs
const int ReturnValueReg = 0
const int ReturnValueReg1 = 1
const int ReturnValueReg2 = 2
const int NumArgumentRegs = 4
const int NumArgumentRegs64 = 8
const int ArgumentReg0 = 0
const int ArgumentReg1 = 1
const int ArgumentReg2 = 2
const int ArgumentReg3 = 3
const int FramePointerReg = 11
const int StackPointerReg = INTREG_SP
const int ReturnAddressReg = INTREG_LR
const int PCReg = INTREG_PC
const int ZeroReg = INTREG_ZERO
const int SyscallNumReg = ReturnValueReg
const int SyscallPseudoReturnReg = ReturnValueReg
const int SyscallSuccessReg = ReturnValueReg
cond
Bitfield< 3, 0 > mask
Bitfield< 7, 2 > top6
Bitfield< 1, 0 > bottom2
decoderFault
Bitfield< 61 > illegalExecution
Bitfield< 59, 56 > sveLen
Bitfield< 55, 48 > itstate
Bitfield< 55, 52 > itstateCond
Bitfield< 51, 48 > itstateMask
Bitfield< 41, 40 > fpscrStride
Bitfield< 39, 37 > fpscrLen
Bitfield< 36 > thumb
Bitfield< 35 > bigThumb
Bitfield< 34 > aarch64
Bitfield< 33 > sevenAndFour
Bitfield< 32 > isMisc
uint32_t instBits
Bitfield< 27, 25 > encoding
Bitfield< 25 > useImm
Bitfield< 24, 21 > opcode
Bitfield< 24, 20 > mediaOpcode
Bitfield< 24 > opcode24
Bitfield< 24, 23 > opcode24_23
Bitfield< 23, 20 > opcode23_20
Bitfield< 23, 21 > opcode23_21
Bitfield< 20 > opcode20
Bitfield< 22 > opcode22
Bitfield< 19, 16 > opcode19_16
Bitfield< 19 > opcode19
Bitfield< 18 > opcode18
Bitfield< 15, 12 > opcode15_12
Bitfield< 15 > opcode15
Bitfield< 7, 4 > miscOpcode
Bitfield< 7, 5 > opc2
Bitfield< 7 > opcode7
Bitfield< 6 > opcode6
Bitfield< 4 > opcode4
Bitfield< 31, 28 > condCode
Bitfield< 20 > sField
Bitfield< 19, 16 > rn
Bitfield< 15, 12 > rd
Bitfield< 15, 12 > rt
Bitfield< 11, 7 > shiftSize
Bitfield< 6, 5 > shift
Bitfield< 3, 0 > rm
Bitfield< 23 > up
Bitfield< 22 > psruser
Bitfield< 21 > writeback
Bitfield< 20 > loadOp
pubwl
Bitfield< 7, 0 > imm
Bitfield< 11, 8 > rotate
Bitfield< 11, 0 > immed11_0
Bitfield< 7, 0 > immed7_0
Bitfield< 11, 8 > immedHi11_8
Bitfield< 3, 0 > immedLo3_0
Bitfield< 15, 0 > regList
Bitfield< 23, 0 > offset
Bitfield< 23, 0 > immed23_0
Bitfield< 11, 8 > cpNum
Bitfield< 18, 16 > fn
Bitfield< 14, 12 > fd
Bitfield< 3 > fpRegImm
Bitfield< 3, 0 > fm
Bitfield< 2, 0 > fpImm
Bitfield< 24, 20 > punwl
Bitfield< 15, 8 > m5Func
Bitfield< 15, 13 > topcode15_13
Bitfield< 13, 11 > topcode13_11
Bitfield< 12, 11 > topcode12_11
Bitfield< 12, 10 > topcode12_10
Bitfield< 11, 9 > topcode11_9
Bitfield< 11, 8 > topcode11_8
Bitfield< 10, 9 > topcode10_9
Bitfield< 10, 8 > topcode10_8
Bitfield< 9, 6 > topcode9_6
Bitfield< 7 > topcode7
Bitfield< 7, 6 > topcode7_6
Bitfield< 7, 5 > topcode7_5
Bitfield< 7, 4 > topcode7_4
Bitfield< 3, 0 > topcode3_0
Bitfield< 28, 27 > htopcode12_11
Bitfield< 26, 25 > htopcode10_9
Bitfield< 25 > htopcode9
Bitfield< 25, 24 > htopcode9_8
Bitfield< 25, 21 > htopcode9_5
Bitfield< 25, 20 > htopcode9_4
Bitfield< 24 > htopcode8
Bitfield< 24, 23 > htopcode8_7
Bitfield< 24, 22 > htopcode8_6
Bitfield< 24, 21 > htopcode8_5
Bitfield< 23 > htopcode7
Bitfield< 23, 21 > htopcode7_5
Bitfield< 22 > htopcode6
Bitfield< 22, 21 > htopcode6_5
Bitfield< 21, 20 > htopcode5_4
Bitfield< 20 > htopcode4
Bitfield< 19, 16 > htrn
Bitfield< 20 > hts
Bitfield< 15 > ltopcode15
Bitfield< 11, 8 > ltopcode11_8
Bitfield< 7, 6 > ltopcode7_6
Bitfield< 7, 4 > ltopcode7_4
Bitfield< 4 > ltopcode4
Bitfield< 11, 8 > ltrd
Bitfield< 11, 8 > ltcoproc
constexpr unsigned MaxSveVecLenInBits = 2048
constexpr unsigned MaxSveVecLenInBytes = MaxSveVecLenInBits >> 3
constexpr unsigned MaxSveVecLenInWords = MaxSveVecLenInBits >> 5
constexpr unsigned MaxSveVecLenInDWords = MaxSveVecLenInBits >> 6
constexpr unsigned VecRegSizeBytes = MaxSveVecLenInBytes
constexpr unsigned VecPredRegSizeBits = MaxSveVecLenInBytes
constexpr unsigned VecPredRegHasPackedRepr = false
Typedef Documentation
ConstVecPredReg
using ArmISA::ConstVecPredReg = typedef ::VecPredRegT<VecElem, NumVecElemPerVecReg, VecPredRegHasPackedRepr, true>
Definition at line 78 of file registers.hh.
ConstVecReg
using ArmISA::ConstVecReg = typedef ::VecRegT<VecElem, NumVecElemPerVecReg, true>
Definition at line 72 of file registers.hh.
FaultOffset
typedef Addr ArmISA::FaultOffset
Definition at line 61 of file faults.hh.
IntRegMap
typedef IntRegIndex ArmISA::IntRegMap[NUM_ARCH_INTREGS]
Definition at line 304 of file intregs.hh.
MachInst
typedef uint32_t ArmISA::MachInst
Definition at line 54 of file types.hh.
RegContextParam
typedef int ArmISA::RegContextParam
Definition at line 550 of file types.hh.
RegContextVal
typedef int ArmISA::RegContextVal
Definition at line 551 of file types.hh.
VecElem
using ArmISA::VecElem = typedef uint32_t
Definition at line 70 of file registers.hh.
VecPredReg
using ArmISA::VecPredReg = typedef ::VecPredRegT<VecElem, NumVecElemPerVecReg, VecPredRegHasPackedRepr, false>
Definition at line 76 of file registers.hh.
VecPredRegContainer
using ArmISA::VecPredRegContainer = typedef VecPredReg::Container
Definition at line 79 of file registers.hh.
VecReg
using ArmISA::VecReg = typedef ::VecRegT<VecElem, NumVecElemPerVecReg, false>
Definition at line 71 of file registers.hh.
VecRegContainer
using ArmISA::VecRegContainer = typedef VecReg::Container
Definition at line 73 of file registers.hh.
VfpSavedState
typedef int ArmISA::VfpSavedState
Definition at line 213 of file vfp.hh.
XReg
typedef uint64_t ArmISA::XReg
Definition at line 50 of file neon64_mem.hh.
Enumeration Type Documentation
ArmExtendType
enum ArmISA::ArmExtendType
Enumerator
UXTB
UXTH
UXTW
UXTX
SXTB
SXTH
SXTW
SXTX
Definition at line 539 of file types.hh.
ArmShiftType
enum ArmISA::ArmShiftType
Enumerator
LSL
LSR
ASR
ROR
Definition at line 531 of file types.hh.
ccRegIndex
enum ArmISA::ccRegIndex
Enumerator
CCREG_NZ
CCREG_C
CCREG_V
CCREG_GE
CCREG_FP
CCREG_ZERO
NUM_CCREGS
Definition at line 45 of file ccregs.hh.
ConditionCode
enum ArmISA::ConditionCode
Enumerator
COND_EQ
COND_NE
COND_CS
COND_CC
COND_MI
COND_PL
COND_VS
COND_VC
COND_HI
COND_LS
COND_GE
COND_LT
COND_GT
COND_LE
COND_AL
COND_UC
Definition at line 64 of file ccregs.hh.
ConvertType
enum ArmISA::ConvertType
Enumerator
SINGLE_TO_DOUBLE
SINGLE_TO_WORD
SINGLE_TO_LONG
DOUBLE_TO_SINGLE
DOUBLE_TO_WORD
DOUBLE_TO_LONG
LONG_TO_SINGLE
LONG_TO_DOUBLE
LONG_TO_WORD
LONG_TO_PS
WORD_TO_SINGLE
WORD_TO_DOUBLE
WORD_TO_LONG
WORD_TO_PS
PL_TO_SINGLE
PU_TO_SINGLE
Definition at line 554 of file types.hh.
DecoderFault
enum ArmISA::DecoderFault : std::uint8_t
Instruction decoder fault codes in ExtMachInst.
Enumerator
OK
No fault.
UNALIGNED
Unaligned instruction fault.
PANIC
Internal gem5 error.
Definition at line 656 of file types.hh.
ExceptionClass
enum ArmISA::ExceptionClass
Enumerator
EC_INVALID
EC_UNKNOWN
EC_TRAPPED_WFI_WFE
EC_TRAPPED_CP15_MCR_MRC
EC_TRAPPED_CP15_MCRR_MRRC
EC_TRAPPED_CP14_MCR_MRC
EC_TRAPPED_CP14_LDC_STC
EC_TRAPPED_HCPTR
EC_TRAPPED_SIMD_FP
EC_TRAPPED_CP10_MRC_VMRS
EC_TRAPPED_BXJ
EC_TRAPPED_CP14_MCRR_MRRC
EC_ILLEGAL_INST
EC_SVC_TO_HYP
EC_SVC
EC_HVC
EC_SMC_TO_HYP
EC_SMC
EC_SVC_64
EC_HVC_64
EC_SMC_64
EC_TRAPPED_MSR_MRS_64
EC_TRAPPED_SVE
EC_PREFETCH_ABORT_TO_HYP
EC_PREFETCH_ABORT_LOWER_EL
EC_PREFETCH_ABORT_FROM_HYP
EC_PREFETCH_ABORT_CURR_EL
EC_PC_ALIGNMENT
EC_DATA_ABORT_TO_HYP
EC_DATA_ABORT_LOWER_EL
EC_DATA_ABORT_FROM_HYP
EC_DATA_ABORT_CURR_EL
EC_STACK_PTR_ALIGNMENT
EC_FP_EXCEPTION
EC_FP_EXCEPTION_64
EC_SERROR
EC_SOFTWARE_BREAKPOINT
EC_SOFTWARE_BREAKPOINT_64
Definition at line 612 of file types.hh.
ExceptionLevel
enum ArmISA::ExceptionLevel
Enumerator
EL0
EL1
EL2
EL3
Definition at line 585 of file types.hh.
FeExceptionBit
enum ArmISA::FeExceptionBit
Enumerator
FeDivByZero
FeInexact
FeInvalid
FeOverflow
FeUnderflow
FeAllExceptions
Definition at line 84 of file vfp.hh.
FeRoundingMode
enum ArmISA::FeRoundingMode
Enumerator
FeRoundDown
FeRoundNearest
FeRoundZero
FeRoundUpward
Definition at line 94 of file vfp.hh.
FpDataType
enum ArmISA::FpDataType strong
Floating point data types.
Enumerator
Fp16
Fp32
Fp64
Definition at line 163 of file pred_inst.hh.
FPRounding
enum ArmISA::FPRounding
Enumerator
FPRounding_TIEEVEN
FPRounding_POSINF
FPRounding_NEGINF
FPRounding_ZERO
FPRounding_TIEAWAY
FPRounding_ODD
Definition at line 59 of file fplib.hh.
InterruptTypes
enum ArmISA::InterruptTypes
Enumerator
INT_RST
INT_ABT
INT_IRQ
INT_FIQ
INT_SEV
INT_VIRT_IRQ
INT_VIRT_FIQ
NumInterruptTypes
Definition at line 104 of file isa_traits.hh.
IntRegIndex
enum ArmISA::IntRegIndex
Enumerator
INTREG_R0
INTREG_R1
INTREG_R2
INTREG_R3
INTREG_R4
INTREG_R5
INTREG_R6
INTREG_R7
INTREG_R8
INTREG_R9
INTREG_R10
INTREG_R11
INTREG_R12
INTREG_R13
INTREG_SP
INTREG_R14
INTREG_LR
INTREG_R15
INTREG_PC
INTREG_R13_SVC
INTREG_SP_SVC
INTREG_R14_SVC
INTREG_LR_SVC
INTREG_R13_MON
INTREG_SP_MON
INTREG_R14_MON
INTREG_LR_MON
INTREG_R13_HYP
INTREG_SP_HYP
INTREG_R13_ABT
INTREG_SP_ABT
INTREG_R14_ABT
INTREG_LR_ABT
INTREG_R13_UND
INTREG_SP_UND
INTREG_R14_UND
INTREG_LR_UND
INTREG_R13_IRQ
INTREG_SP_IRQ
INTREG_R14_IRQ
INTREG_LR_IRQ
INTREG_R8_FIQ
INTREG_R9_FIQ
INTREG_R10_FIQ
INTREG_R11_FIQ
INTREG_R12_FIQ
INTREG_R13_FIQ
INTREG_SP_FIQ
INTREG_R14_FIQ
INTREG_LR_FIQ
INTREG_ZERO
INTREG_UREG0
INTREG_UREG1
INTREG_UREG2
INTREG_DUMMY
INTREG_SP0
INTREG_SP1
INTREG_SP2
INTREG_SP3
NUM_INTREGS
NUM_ARCH_INTREGS
INTREG_X0
INTREG_X1
INTREG_X2
INTREG_X3
INTREG_X4
INTREG_X5
INTREG_X6
INTREG_X7
INTREG_X8
INTREG_X9
INTREG_X10
INTREG_X11
INTREG_X12
INTREG_X13
INTREG_X14
INTREG_X15
INTREG_X16
INTREG_X17
INTREG_X18
INTREG_X19
INTREG_X20
INTREG_X21
INTREG_X22
INTREG_X23
INTREG_X24
INTREG_X25
INTREG_X26
INTREG_X27
INTREG_X28
INTREG_X29
INTREG_X30
INTREG_X31
INTREG_SPX
INTREG_R0_USR
INTREG_R1_USR
INTREG_R2_USR
INTREG_R3_USR
INTREG_R4_USR
INTREG_R5_USR
INTREG_R6_USR
INTREG_R7_USR
INTREG_R8_USR
INTREG_R9_USR
INTREG_R10_USR
INTREG_R11_USR
INTREG_R12_USR
INTREG_R13_USR
INTREG_SP_USR
INTREG_R14_USR
INTREG_LR_USR
INTREG_R15_USR
INTREG_PC_USR
INTREG_R0_SVC
INTREG_R1_SVC
INTREG_R2_SVC
INTREG_R3_SVC
INTREG_R4_SVC
INTREG_R5_SVC
INTREG_R6_SVC
INTREG_R7_SVC
INTREG_R8_SVC
INTREG_R9_SVC
INTREG_R10_SVC
INTREG_R11_SVC
INTREG_R12_SVC
INTREG_PC_SVC
INTREG_R15_SVC
INTREG_R0_MON
INTREG_R1_MON
INTREG_R2_MON
INTREG_R3_MON
INTREG_R4_MON
INTREG_R5_MON
INTREG_R6_MON
INTREG_R7_MON
INTREG_R8_MON
INTREG_R9_MON
INTREG_R10_MON
INTREG_R11_MON
INTREG_R12_MON
INTREG_PC_MON
INTREG_R15_MON
INTREG_R0_ABT
INTREG_R1_ABT
INTREG_R2_ABT
INTREG_R3_ABT
INTREG_R4_ABT
INTREG_R5_ABT
INTREG_R6_ABT
INTREG_R7_ABT
INTREG_R8_ABT
INTREG_R9_ABT
INTREG_R10_ABT
INTREG_R11_ABT
INTREG_R12_ABT
INTREG_PC_ABT
INTREG_R15_ABT
INTREG_R0_HYP
INTREG_R1_HYP
INTREG_R2_HYP
INTREG_R3_HYP
INTREG_R4_HYP
INTREG_R5_HYP
INTREG_R6_HYP
INTREG_R7_HYP
INTREG_R8_HYP
INTREG_R9_HYP
INTREG_R10_HYP
INTREG_R11_HYP
INTREG_R12_HYP
INTREG_LR_HYP
INTREG_R14_HYP
INTREG_PC_HYP
INTREG_R15_HYP
INTREG_R0_UND
INTREG_R1_UND
INTREG_R2_UND
INTREG_R3_UND
INTREG_R4_UND
INTREG_R5_UND
INTREG_R6_UND
INTREG_R7_UND
INTREG_R8_UND
INTREG_R9_UND
INTREG_R10_UND
INTREG_R11_UND
INTREG_R12_UND
INTREG_PC_UND
INTREG_R15_UND
INTREG_R0_IRQ
INTREG_R1_IRQ
INTREG_R2_IRQ
INTREG_R3_IRQ
INTREG_R4_IRQ
INTREG_R5_IRQ
INTREG_R6_IRQ
INTREG_R7_IRQ
INTREG_R8_IRQ
INTREG_R9_IRQ
INTREG_R10_IRQ
INTREG_R11_IRQ
INTREG_R12_IRQ
INTREG_PC_IRQ
INTREG_R15_IRQ
INTREG_R0_FIQ
INTREG_R1_FIQ
INTREG_R2_FIQ
INTREG_R3_FIQ
INTREG_R4_FIQ
INTREG_R5_FIQ
INTREG_R6_FIQ
INTREG_R7_FIQ
INTREG_PC_FIQ
INTREG_R15_FIQ
Definition at line 53 of file intregs.hh.
LookupLevel
enum ArmISA::LookupLevel
Enumerator
L0
L1
L2
L3
MAX_LOOKUP_LEVELS
Definition at line 77 of file pagetable.hh.
MiscRegIndex
enum ArmISA::MiscRegIndex
Enumerator
MISCREG_CPSR
MISCREG_SPSR
MISCREG_SPSR_FIQ
MISCREG_SPSR_IRQ
MISCREG_SPSR_SVC
MISCREG_SPSR_MON
MISCREG_SPSR_ABT
MISCREG_SPSR_HYP
MISCREG_SPSR_UND
MISCREG_ELR_HYP
MISCREG_FPSID
MISCREG_FPSCR
MISCREG_MVFR1
MISCREG_MVFR0
MISCREG_FPEXC
MISCREG_CPSR_MODE
MISCREG_CPSR_Q
MISCREG_FPSCR_EXC
MISCREG_FPSCR_QC
MISCREG_LOCKADDR
MISCREG_LOCKFLAG
MISCREG_PRRR_MAIR0
MISCREG_PRRR_MAIR0_NS
MISCREG_PRRR_MAIR0_S
MISCREG_NMRR_MAIR1
MISCREG_NMRR_MAIR1_NS
MISCREG_NMRR_MAIR1_S
MISCREG_PMXEVTYPER_PMCCFILTR
MISCREG_SCTLR_RST
MISCREG_SEV_MAILBOX
MISCREG_DBGDIDR
MISCREG_DBGDSCRint
MISCREG_DBGDCCINT
MISCREG_DBGDTRTXint
MISCREG_DBGDTRRXint
MISCREG_DBGWFAR
MISCREG_DBGVCR
MISCREG_DBGDTRRXext
MISCREG_DBGDSCRext
MISCREG_DBGDTRTXext
MISCREG_DBGOSECCR
MISCREG_DBGBVR0
MISCREG_DBGBVR1
MISCREG_DBGBVR2
MISCREG_DBGBVR3
MISCREG_DBGBVR4
MISCREG_DBGBVR5
MISCREG_DBGBCR0
MISCREG_DBGBCR1
MISCREG_DBGBCR2
MISCREG_DBGBCR3
MISCREG_DBGBCR4
MISCREG_DBGBCR5
MISCREG_DBGWVR0
MISCREG_DBGWVR1
MISCREG_DBGWVR2
MISCREG_DBGWVR3
MISCREG_DBGWCR0
MISCREG_DBGWCR1
MISCREG_DBGWCR2
MISCREG_DBGWCR3
MISCREG_DBGDRAR
MISCREG_DBGBXVR4
MISCREG_DBGBXVR5
MISCREG_DBGOSLAR
MISCREG_DBGOSLSR
MISCREG_DBGOSDLR
MISCREG_DBGPRCR
MISCREG_DBGDSAR
MISCREG_DBGCLAIMSET
MISCREG_DBGCLAIMCLR
MISCREG_DBGAUTHSTATUS
MISCREG_DBGDEVID2
MISCREG_DBGDEVID1
MISCREG_DBGDEVID0
MISCREG_TEECR
MISCREG_JIDR
MISCREG_TEEHBR
MISCREG_JOSCR
MISCREG_JMCR
MISCREG_MIDR
MISCREG_CTR
MISCREG_TCMTR
MISCREG_TLBTR
MISCREG_MPIDR
MISCREG_REVIDR
MISCREG_ID_PFR0
MISCREG_ID_PFR1
MISCREG_ID_DFR0
MISCREG_ID_AFR0
MISCREG_ID_MMFR0
MISCREG_ID_MMFR1
MISCREG_ID_MMFR2
MISCREG_ID_MMFR3
MISCREG_ID_ISAR0
MISCREG_ID_ISAR1
MISCREG_ID_ISAR2
MISCREG_ID_ISAR3
MISCREG_ID_ISAR4
MISCREG_ID_ISAR5
MISCREG_CCSIDR
MISCREG_CLIDR
MISCREG_AIDR
MISCREG_CSSELR
MISCREG_CSSELR_NS
MISCREG_CSSELR_S
MISCREG_VPIDR
MISCREG_VMPIDR
MISCREG_SCTLR
MISCREG_SCTLR_NS
MISCREG_SCTLR_S
MISCREG_ACTLR
MISCREG_ACTLR_NS
MISCREG_ACTLR_S
MISCREG_CPACR
MISCREG_SCR
MISCREG_SDER
MISCREG_NSACR
MISCREG_HSCTLR
MISCREG_HACTLR
MISCREG_HCR
MISCREG_HCR2
MISCREG_HDCR
MISCREG_HCPTR
MISCREG_HSTR
MISCREG_HACR
MISCREG_TTBR0
MISCREG_TTBR0_NS
MISCREG_TTBR0_S
MISCREG_TTBR1
MISCREG_TTBR1_NS
MISCREG_TTBR1_S
MISCREG_TTBCR
MISCREG_TTBCR_NS
MISCREG_TTBCR_S
MISCREG_HTCR
MISCREG_VTCR
MISCREG_DACR
MISCREG_DACR_NS
MISCREG_DACR_S
MISCREG_DFSR
MISCREG_DFSR_NS
MISCREG_DFSR_S
MISCREG_IFSR
MISCREG_IFSR_NS
MISCREG_IFSR_S
MISCREG_ADFSR
MISCREG_ADFSR_NS
MISCREG_ADFSR_S
MISCREG_AIFSR
MISCREG_AIFSR_NS
MISCREG_AIFSR_S
MISCREG_HADFSR
MISCREG_HAIFSR
MISCREG_HSR
MISCREG_DFAR
MISCREG_DFAR_NS
MISCREG_DFAR_S
MISCREG_IFAR
MISCREG_IFAR_NS
MISCREG_IFAR_S
MISCREG_HDFAR
MISCREG_HIFAR
MISCREG_HPFAR
MISCREG_ICIALLUIS
MISCREG_BPIALLIS
MISCREG_PAR
MISCREG_PAR_NS
MISCREG_PAR_S
MISCREG_ICIALLU
MISCREG_ICIMVAU
MISCREG_CP15ISB
MISCREG_BPIALL
MISCREG_BPIMVA
MISCREG_DCIMVAC
MISCREG_DCISW
MISCREG_ATS1CPR
MISCREG_ATS1CPW
MISCREG_ATS1CUR
MISCREG_ATS1CUW
MISCREG_ATS12NSOPR
MISCREG_ATS12NSOPW
MISCREG_ATS12NSOUR
MISCREG_ATS12NSOUW
MISCREG_DCCMVAC
MISCREG_DCCSW
MISCREG_CP15DSB
MISCREG_CP15DMB
MISCREG_DCCMVAU
MISCREG_DCCIMVAC
MISCREG_DCCISW
MISCREG_ATS1HR
MISCREG_ATS1HW
MISCREG_TLBIALLIS
MISCREG_TLBIMVAIS
MISCREG_TLBIASIDIS
MISCREG_TLBIMVAAIS
MISCREG_TLBIMVALIS
MISCREG_TLBIMVAALIS
MISCREG_ITLBIALL
MISCREG_ITLBIMVA
MISCREG_ITLBIASID
MISCREG_DTLBIALL
MISCREG_DTLBIMVA
MISCREG_DTLBIASID
MISCREG_TLBIALL
MISCREG_TLBIMVA
MISCREG_TLBIASID
MISCREG_TLBIMVAA
MISCREG_TLBIMVAL
MISCREG_TLBIMVAAL
MISCREG_TLBIIPAS2IS
MISCREG_TLBIIPAS2LIS
MISCREG_TLBIALLHIS
MISCREG_TLBIMVAHIS
MISCREG_TLBIALLNSNHIS
MISCREG_TLBIMVALHIS
MISCREG_TLBIIPAS2
MISCREG_TLBIIPAS2L
MISCREG_TLBIALLH
MISCREG_TLBIMVAH
MISCREG_TLBIALLNSNH
MISCREG_TLBIMVALH
MISCREG_PMCR
MISCREG_PMCNTENSET
MISCREG_PMCNTENCLR
MISCREG_PMOVSR
MISCREG_PMSWINC
MISCREG_PMSELR
MISCREG_PMCEID0
MISCREG_PMCEID1
MISCREG_PMCCNTR
MISCREG_PMXEVTYPER
MISCREG_PMCCFILTR
MISCREG_PMXEVCNTR
MISCREG_PMUSERENR
MISCREG_PMINTENSET
MISCREG_PMINTENCLR
MISCREG_PMOVSSET
MISCREG_L2CTLR
MISCREG_L2ECTLR
MISCREG_PRRR
MISCREG_PRRR_NS
MISCREG_PRRR_S
MISCREG_MAIR0
MISCREG_MAIR0_NS
MISCREG_MAIR0_S
MISCREG_NMRR
MISCREG_NMRR_NS
MISCREG_NMRR_S
MISCREG_MAIR1
MISCREG_MAIR1_NS
MISCREG_MAIR1_S
MISCREG_AMAIR0
MISCREG_AMAIR0_NS
MISCREG_AMAIR0_S
MISCREG_AMAIR1
MISCREG_AMAIR1_NS
MISCREG_AMAIR1_S
MISCREG_HMAIR0
MISCREG_HMAIR1
MISCREG_HAMAIR0
MISCREG_HAMAIR1
MISCREG_VBAR
MISCREG_VBAR_NS
MISCREG_VBAR_S
MISCREG_MVBAR
MISCREG_RMR
MISCREG_ISR
MISCREG_HVBAR
MISCREG_FCSEIDR
MISCREG_CONTEXTIDR
MISCREG_CONTEXTIDR_NS
MISCREG_CONTEXTIDR_S
MISCREG_TPIDRURW
MISCREG_TPIDRURW_NS
MISCREG_TPIDRURW_S
MISCREG_TPIDRURO
MISCREG_TPIDRURO_NS
MISCREG_TPIDRURO_S
MISCREG_TPIDRPRW
MISCREG_TPIDRPRW_NS
MISCREG_TPIDRPRW_S
MISCREG_HTPIDR
MISCREG_CNTFRQ
MISCREG_CNTKCTL
MISCREG_CNTP_TVAL
MISCREG_CNTP_TVAL_NS
MISCREG_CNTP_TVAL_S
MISCREG_CNTP_CTL
MISCREG_CNTP_CTL_NS
MISCREG_CNTP_CTL_S
MISCREG_CNTV_TVAL
MISCREG_CNTV_CTL
MISCREG_CNTHCTL
MISCREG_CNTHP_TVAL
MISCREG_CNTHP_CTL
MISCREG_IL1DATA0
MISCREG_IL1DATA1
MISCREG_IL1DATA2
MISCREG_IL1DATA3
MISCREG_DL1DATA0
MISCREG_DL1DATA1
MISCREG_DL1DATA2
MISCREG_DL1DATA3
MISCREG_DL1DATA4
MISCREG_RAMINDEX
MISCREG_L2ACTLR
MISCREG_CBAR
MISCREG_HTTBR
MISCREG_VTTBR
MISCREG_CNTPCT
MISCREG_CNTVCT
MISCREG_CNTP_CVAL
MISCREG_CNTP_CVAL_NS
MISCREG_CNTP_CVAL_S
MISCREG_CNTV_CVAL
MISCREG_CNTVOFF
MISCREG_CNTHP_CVAL
MISCREG_CPUMERRSR
MISCREG_L2MERRSR
MISCREG_MDCCINT_EL1
MISCREG_OSDTRRX_EL1
MISCREG_MDSCR_EL1
MISCREG_OSDTRTX_EL1
MISCREG_OSECCR_EL1
MISCREG_DBGBVR0_EL1
MISCREG_DBGBVR1_EL1
MISCREG_DBGBVR2_EL1
MISCREG_DBGBVR3_EL1
MISCREG_DBGBVR4_EL1
MISCREG_DBGBVR5_EL1
MISCREG_DBGBCR0_EL1
MISCREG_DBGBCR1_EL1
MISCREG_DBGBCR2_EL1
MISCREG_DBGBCR3_EL1
MISCREG_DBGBCR4_EL1
MISCREG_DBGBCR5_EL1
MISCREG_DBGWVR0_EL1
MISCREG_DBGWVR1_EL1
MISCREG_DBGWVR2_EL1
MISCREG_DBGWVR3_EL1
MISCREG_DBGWCR0_EL1
MISCREG_DBGWCR1_EL1
MISCREG_DBGWCR2_EL1
MISCREG_DBGWCR3_EL1
MISCREG_MDCCSR_EL0
MISCREG_MDDTR_EL0
MISCREG_MDDTRTX_EL0
MISCREG_MDDTRRX_EL0
MISCREG_DBGVCR32_EL2
MISCREG_MDRAR_EL1
MISCREG_OSLAR_EL1
MISCREG_OSLSR_EL1
MISCREG_OSDLR_EL1
MISCREG_DBGPRCR_EL1
MISCREG_DBGCLAIMSET_EL1
MISCREG_DBGCLAIMCLR_EL1
MISCREG_DBGAUTHSTATUS_EL1
MISCREG_TEECR32_EL1
MISCREG_TEEHBR32_EL1
MISCREG_MIDR_EL1
MISCREG_MPIDR_EL1
MISCREG_REVIDR_EL1
MISCREG_ID_PFR0_EL1
MISCREG_ID_PFR1_EL1
MISCREG_ID_DFR0_EL1
MISCREG_ID_AFR0_EL1
MISCREG_ID_MMFR0_EL1
MISCREG_ID_MMFR1_EL1
MISCREG_ID_MMFR2_EL1
MISCREG_ID_MMFR3_EL1
MISCREG_ID_ISAR0_EL1
MISCREG_ID_ISAR1_EL1
MISCREG_ID_ISAR2_EL1
MISCREG_ID_ISAR3_EL1
MISCREG_ID_ISAR4_EL1
MISCREG_ID_ISAR5_EL1
MISCREG_MVFR0_EL1
MISCREG_MVFR1_EL1
MISCREG_MVFR2_EL1
MISCREG_ID_AA64PFR0_EL1
MISCREG_ID_AA64PFR1_EL1
MISCREG_ID_AA64DFR0_EL1
MISCREG_ID_AA64DFR1_EL1
MISCREG_ID_AA64AFR0_EL1
MISCREG_ID_AA64AFR1_EL1
MISCREG_ID_AA64ISAR0_EL1
MISCREG_ID_AA64ISAR1_EL1
MISCREG_ID_AA64MMFR0_EL1
MISCREG_ID_AA64MMFR1_EL1
MISCREG_CCSIDR_EL1
MISCREG_CLIDR_EL1
MISCREG_AIDR_EL1
MISCREG_CSSELR_EL1
MISCREG_CTR_EL0
MISCREG_DCZID_EL0
MISCREG_VPIDR_EL2
MISCREG_VMPIDR_EL2
MISCREG_SCTLR_EL1
MISCREG_ACTLR_EL1
MISCREG_CPACR_EL1
MISCREG_SCTLR_EL2
MISCREG_ACTLR_EL2
MISCREG_HCR_EL2
MISCREG_MDCR_EL2
MISCREG_CPTR_EL2
MISCREG_HSTR_EL2
MISCREG_HACR_EL2
MISCREG_SCTLR_EL3
MISCREG_ACTLR_EL3
MISCREG_SCR_EL3
MISCREG_SDER32_EL3
MISCREG_CPTR_EL3
MISCREG_MDCR_EL3
MISCREG_TTBR0_EL1
MISCREG_TTBR1_EL1
MISCREG_TCR_EL1
MISCREG_TTBR0_EL2
MISCREG_TCR_EL2
MISCREG_VTTBR_EL2
MISCREG_VTCR_EL2
MISCREG_TTBR0_EL3
MISCREG_TCR_EL3
MISCREG_DACR32_EL2
MISCREG_SPSR_EL1
MISCREG_ELR_EL1
MISCREG_SP_EL0
MISCREG_SPSEL
MISCREG_CURRENTEL
MISCREG_NZCV
MISCREG_DAIF
MISCREG_FPCR
MISCREG_FPSR
MISCREG_DSPSR_EL0
MISCREG_DLR_EL0
MISCREG_SPSR_EL2
MISCREG_ELR_EL2
MISCREG_SP_EL1
MISCREG_SPSR_IRQ_AA64
MISCREG_SPSR_ABT_AA64
MISCREG_SPSR_UND_AA64
MISCREG_SPSR_FIQ_AA64
MISCREG_SPSR_EL3
MISCREG_ELR_EL3
MISCREG_SP_EL2
MISCREG_AFSR0_EL1
MISCREG_AFSR1_EL1
MISCREG_ESR_EL1
MISCREG_IFSR32_EL2
MISCREG_AFSR0_EL2
MISCREG_AFSR1_EL2
MISCREG_ESR_EL2
MISCREG_FPEXC32_EL2
MISCREG_AFSR0_EL3
MISCREG_AFSR1_EL3
MISCREG_ESR_EL3
MISCREG_FAR_EL1
MISCREG_FAR_EL2
MISCREG_HPFAR_EL2
MISCREG_FAR_EL3
MISCREG_IC_IALLUIS
MISCREG_PAR_EL1
MISCREG_IC_IALLU
MISCREG_DC_IVAC_Xt
MISCREG_DC_ISW_Xt
MISCREG_AT_S1E1R_Xt
MISCREG_AT_S1E1W_Xt
MISCREG_AT_S1E0R_Xt
MISCREG_AT_S1E0W_Xt
MISCREG_DC_CSW_Xt
MISCREG_DC_CISW_Xt
MISCREG_DC_ZVA_Xt
MISCREG_IC_IVAU_Xt
MISCREG_DC_CVAC_Xt
MISCREG_DC_CVAU_Xt
MISCREG_DC_CIVAC_Xt
MISCREG_AT_S1E2R_Xt
MISCREG_AT_S1E2W_Xt
MISCREG_AT_S12E1R_Xt
MISCREG_AT_S12E1W_Xt
MISCREG_AT_S12E0R_Xt
MISCREG_AT_S12E0W_Xt
MISCREG_AT_S1E3R_Xt
MISCREG_AT_S1E3W_Xt
MISCREG_TLBI_VMALLE1IS
MISCREG_TLBI_VAE1IS_Xt
MISCREG_TLBI_ASIDE1IS_Xt
MISCREG_TLBI_VAAE1IS_Xt
MISCREG_TLBI_VALE1IS_Xt
MISCREG_TLBI_VAALE1IS_Xt
MISCREG_TLBI_VMALLE1
MISCREG_TLBI_VAE1_Xt
MISCREG_TLBI_ASIDE1_Xt
MISCREG_TLBI_VAAE1_Xt
MISCREG_TLBI_VALE1_Xt
MISCREG_TLBI_VAALE1_Xt
MISCREG_TLBI_IPAS2E1IS_Xt
MISCREG_TLBI_IPAS2LE1IS_Xt
MISCREG_TLBI_ALLE2IS
MISCREG_TLBI_VAE2IS_Xt
MISCREG_TLBI_ALLE1IS
MISCREG_TLBI_VALE2IS_Xt
MISCREG_TLBI_VMALLS12E1IS
MISCREG_TLBI_IPAS2E1_Xt
MISCREG_TLBI_IPAS2LE1_Xt
MISCREG_TLBI_ALLE2
MISCREG_TLBI_VAE2_Xt
MISCREG_TLBI_ALLE1
MISCREG_TLBI_VALE2_Xt
MISCREG_TLBI_VMALLS12E1
MISCREG_TLBI_ALLE3IS
MISCREG_TLBI_VAE3IS_Xt
MISCREG_TLBI_VALE3IS_Xt
MISCREG_TLBI_ALLE3
MISCREG_TLBI_VAE3_Xt
MISCREG_TLBI_VALE3_Xt
MISCREG_PMINTENSET_EL1
MISCREG_PMINTENCLR_EL1
MISCREG_PMCR_EL0
MISCREG_PMCNTENSET_EL0
MISCREG_PMCNTENCLR_EL0
MISCREG_PMOVSCLR_EL0
MISCREG_PMSWINC_EL0
MISCREG_PMSELR_EL0
MISCREG_PMCEID0_EL0
MISCREG_PMCEID1_EL0
MISCREG_PMCCNTR_EL0
MISCREG_PMXEVTYPER_EL0
MISCREG_PMCCFILTR_EL0
MISCREG_PMXEVCNTR_EL0
MISCREG_PMUSERENR_EL0
MISCREG_PMOVSSET_EL0
MISCREG_MAIR_EL1
MISCREG_AMAIR_EL1
MISCREG_MAIR_EL2
MISCREG_AMAIR_EL2
MISCREG_MAIR_EL3
MISCREG_AMAIR_EL3
MISCREG_L2CTLR_EL1
MISCREG_L2ECTLR_EL1
MISCREG_VBAR_EL1
MISCREG_RVBAR_EL1
MISCREG_ISR_EL1
MISCREG_VBAR_EL2
MISCREG_RVBAR_EL2
MISCREG_VBAR_EL3
MISCREG_RVBAR_EL3
MISCREG_RMR_EL3
MISCREG_CONTEXTIDR_EL1
MISCREG_TPIDR_EL1
MISCREG_TPIDR_EL0
MISCREG_TPIDRRO_EL0
MISCREG_TPIDR_EL2
MISCREG_TPIDR_EL3
MISCREG_CNTKCTL_EL1
MISCREG_CNTFRQ_EL0
MISCREG_CNTPCT_EL0
MISCREG_CNTVCT_EL0
MISCREG_CNTP_TVAL_EL0
MISCREG_CNTP_CTL_EL0
MISCREG_CNTP_CVAL_EL0
MISCREG_CNTV_TVAL_EL0
MISCREG_CNTV_CTL_EL0
MISCREG_CNTV_CVAL_EL0
MISCREG_PMEVCNTR0_EL0
MISCREG_PMEVCNTR1_EL0
MISCREG_PMEVCNTR2_EL0
MISCREG_PMEVCNTR3_EL0
MISCREG_PMEVCNTR4_EL0
MISCREG_PMEVCNTR5_EL0
MISCREG_PMEVTYPER0_EL0
MISCREG_PMEVTYPER1_EL0
MISCREG_PMEVTYPER2_EL0
MISCREG_PMEVTYPER3_EL0
MISCREG_PMEVTYPER4_EL0
MISCREG_PMEVTYPER5_EL0
MISCREG_CNTVOFF_EL2
MISCREG_CNTHCTL_EL2
MISCREG_CNTHP_TVAL_EL2
MISCREG_CNTHP_CTL_EL2
MISCREG_CNTHP_CVAL_EL2
MISCREG_CNTPS_TVAL_EL1
MISCREG_CNTPS_CTL_EL1
MISCREG_CNTPS_CVAL_EL1
MISCREG_IL1DATA0_EL1
MISCREG_IL1DATA1_EL1
MISCREG_IL1DATA2_EL1
MISCREG_IL1DATA3_EL1
MISCREG_DL1DATA0_EL1
MISCREG_DL1DATA1_EL1
MISCREG_DL1DATA2_EL1
MISCREG_DL1DATA3_EL1
MISCREG_DL1DATA4_EL1
MISCREG_L2ACTLR_EL1
MISCREG_CPUACTLR_EL1
MISCREG_CPUECTLR_EL1
MISCREG_CPUMERRSR_EL1
MISCREG_L2MERRSR_EL1
MISCREG_CBAR_EL1
MISCREG_CONTEXTIDR_EL2
MISCREG_TTBR1_EL2
MISCREG_CNTHV_CTL_EL2
MISCREG_CNTHV_CVAL_EL2
MISCREG_CNTHV_TVAL_EL2
MISCREG_ID_AA64MMFR2_EL1
MISCREG_ICC_PMR_EL1
MISCREG_ICC_IAR0_EL1
MISCREG_ICC_EOIR0_EL1
MISCREG_ICC_HPPIR0_EL1
MISCREG_ICC_BPR0_EL1
MISCREG_ICC_AP0R0_EL1
MISCREG_ICC_AP0R1_EL1
MISCREG_ICC_AP0R2_EL1
MISCREG_ICC_AP0R3_EL1
MISCREG_ICC_AP1R0_EL1
MISCREG_ICC_AP1R0_EL1_NS
MISCREG_ICC_AP1R0_EL1_S
MISCREG_ICC_AP1R1_EL1
MISCREG_ICC_AP1R1_EL1_NS
MISCREG_ICC_AP1R1_EL1_S
MISCREG_ICC_AP1R2_EL1
MISCREG_ICC_AP1R2_EL1_NS
MISCREG_ICC_AP1R2_EL1_S
MISCREG_ICC_AP1R3_EL1
MISCREG_ICC_AP1R3_EL1_NS
MISCREG_ICC_AP1R3_EL1_S
MISCREG_ICC_DIR_EL1
MISCREG_ICC_RPR_EL1
MISCREG_ICC_SGI1R_EL1
MISCREG_ICC_ASGI1R_EL1
MISCREG_ICC_SGI0R_EL1
MISCREG_ICC_IAR1_EL1
MISCREG_ICC_EOIR1_EL1
MISCREG_ICC_HPPIR1_EL1
MISCREG_ICC_BPR1_EL1
MISCREG_ICC_BPR1_EL1_NS
MISCREG_ICC_BPR1_EL1_S
MISCREG_ICC_CTLR_EL1
MISCREG_ICC_CTLR_EL1_NS
MISCREG_ICC_CTLR_EL1_S
MISCREG_ICC_SRE_EL1
MISCREG_ICC_SRE_EL1_NS
MISCREG_ICC_SRE_EL1_S
MISCREG_ICC_IGRPEN0_EL1
MISCREG_ICC_IGRPEN1_EL1
MISCREG_ICC_IGRPEN1_EL1_NS
MISCREG_ICC_IGRPEN1_EL1_S
MISCREG_ICC_SRE_EL2
MISCREG_ICC_CTLR_EL3
MISCREG_ICC_SRE_EL3
MISCREG_ICC_IGRPEN1_EL3
MISCREG_ICH_AP0R0_EL2
MISCREG_ICH_AP0R1_EL2
MISCREG_ICH_AP0R2_EL2
MISCREG_ICH_AP0R3_EL2
MISCREG_ICH_AP1R0_EL2
MISCREG_ICH_AP1R1_EL2
MISCREG_ICH_AP1R2_EL2
MISCREG_ICH_AP1R3_EL2
MISCREG_ICH_HCR_EL2
MISCREG_ICH_VTR_EL2
MISCREG_ICH_MISR_EL2
MISCREG_ICH_EISR_EL2
MISCREG_ICH_ELRSR_EL2
MISCREG_ICH_VMCR_EL2
MISCREG_ICH_LR0_EL2
MISCREG_ICH_LR1_EL2
MISCREG_ICH_LR2_EL2
MISCREG_ICH_LR3_EL2
MISCREG_ICH_LR4_EL2
MISCREG_ICH_LR5_EL2
MISCREG_ICH_LR6_EL2
MISCREG_ICH_LR7_EL2
MISCREG_ICH_LR8_EL2
MISCREG_ICH_LR9_EL2
MISCREG_ICH_LR10_EL2
MISCREG_ICH_LR11_EL2
MISCREG_ICH_LR12_EL2
MISCREG_ICH_LR13_EL2
MISCREG_ICH_LR14_EL2
MISCREG_ICH_LR15_EL2
MISCREG_ICV_PMR_EL1
MISCREG_ICV_IAR0_EL1
MISCREG_ICV_EOIR0_EL1
MISCREG_ICV_HPPIR0_EL1
MISCREG_ICV_BPR0_EL1
MISCREG_ICV_AP0R0_EL1
MISCREG_ICV_AP0R1_EL1
MISCREG_ICV_AP0R2_EL1
MISCREG_ICV_AP0R3_EL1
MISCREG_ICV_AP1R0_EL1
MISCREG_ICV_AP1R0_EL1_NS
MISCREG_ICV_AP1R0_EL1_S
MISCREG_ICV_AP1R1_EL1
MISCREG_ICV_AP1R1_EL1_NS
MISCREG_ICV_AP1R1_EL1_S
MISCREG_ICV_AP1R2_EL1
MISCREG_ICV_AP1R2_EL1_NS
MISCREG_ICV_AP1R2_EL1_S
MISCREG_ICV_AP1R3_EL1
MISCREG_ICV_AP1R3_EL1_NS
MISCREG_ICV_AP1R3_EL1_S
MISCREG_ICV_DIR_EL1
MISCREG_ICV_RPR_EL1
MISCREG_ICV_SGI1R_EL1
MISCREG_ICV_ASGI1R_EL1
MISCREG_ICV_SGI0R_EL1
MISCREG_ICV_IAR1_EL1
MISCREG_ICV_EOIR1_EL1
MISCREG_ICV_HPPIR1_EL1
MISCREG_ICV_BPR1_EL1
MISCREG_ICV_BPR1_EL1_NS
MISCREG_ICV_BPR1_EL1_S
MISCREG_ICV_CTLR_EL1
MISCREG_ICV_CTLR_EL1_NS
MISCREG_ICV_CTLR_EL1_S
MISCREG_ICV_SRE_EL1
MISCREG_ICV_SRE_EL1_NS
MISCREG_ICV_SRE_EL1_S
MISCREG_ICV_IGRPEN0_EL1
MISCREG_ICV_IGRPEN1_EL1
MISCREG_ICV_IGRPEN1_EL1_NS
MISCREG_ICV_IGRPEN1_EL1_S
MISCREG_ICC_AP0R0
MISCREG_ICC_AP0R1
MISCREG_ICC_AP0R2
MISCREG_ICC_AP0R3
MISCREG_ICC_AP1R0
MISCREG_ICC_AP1R0_NS
MISCREG_ICC_AP1R0_S
MISCREG_ICC_AP1R1
MISCREG_ICC_AP1R1_NS
MISCREG_ICC_AP1R1_S
MISCREG_ICC_AP1R2
MISCREG_ICC_AP1R2_NS
MISCREG_ICC_AP1R2_S
MISCREG_ICC_AP1R3
MISCREG_ICC_AP1R3_NS
MISCREG_ICC_AP1R3_S
MISCREG_ICC_ASGI1R
MISCREG_ICC_BPR0
MISCREG_ICC_BPR1
MISCREG_ICC_BPR1_NS
MISCREG_ICC_BPR1_S
MISCREG_ICC_CTLR
MISCREG_ICC_CTLR_NS
MISCREG_ICC_CTLR_S
MISCREG_ICC_DIR
MISCREG_ICC_EOIR0
MISCREG_ICC_EOIR1
MISCREG_ICC_HPPIR0
MISCREG_ICC_HPPIR1
MISCREG_ICC_HSRE
MISCREG_ICC_IAR0
MISCREG_ICC_IAR1
MISCREG_ICC_IGRPEN0
MISCREG_ICC_IGRPEN1
MISCREG_ICC_IGRPEN1_NS
MISCREG_ICC_IGRPEN1_S
MISCREG_ICC_MCTLR
MISCREG_ICC_MGRPEN1
MISCREG_ICC_MSRE
MISCREG_ICC_PMR
MISCREG_ICC_RPR
MISCREG_ICC_SGI0R
MISCREG_ICC_SGI1R
MISCREG_ICC_SRE
MISCREG_ICC_SRE_NS
MISCREG_ICC_SRE_S
MISCREG_ICH_AP0R0
MISCREG_ICH_AP0R1
MISCREG_ICH_AP0R2
MISCREG_ICH_AP0R3
MISCREG_ICH_AP1R0
MISCREG_ICH_AP1R1
MISCREG_ICH_AP1R2
MISCREG_ICH_AP1R3
MISCREG_ICH_HCR
MISCREG_ICH_VTR
MISCREG_ICH_MISR
MISCREG_ICH_EISR
MISCREG_ICH_ELRSR
MISCREG_ICH_VMCR
MISCREG_ICH_LR0
MISCREG_ICH_LR1
MISCREG_ICH_LR2
MISCREG_ICH_LR3
MISCREG_ICH_LR4
MISCREG_ICH_LR5
MISCREG_ICH_LR6
MISCREG_ICH_LR7
MISCREG_ICH_LR8
MISCREG_ICH_LR9
MISCREG_ICH_LR10
MISCREG_ICH_LR11
MISCREG_ICH_LR12
MISCREG_ICH_LR13
MISCREG_ICH_LR14
MISCREG_ICH_LR15
MISCREG_ICH_LRC0
MISCREG_ICH_LRC1
MISCREG_ICH_LRC2
MISCREG_ICH_LRC3
MISCREG_ICH_LRC4
MISCREG_ICH_LRC5
MISCREG_ICH_LRC6
MISCREG_ICH_LRC7
MISCREG_ICH_LRC8
MISCREG_ICH_LRC9
MISCREG_ICH_LRC10
MISCREG_ICH_LRC11
MISCREG_ICH_LRC12
MISCREG_ICH_LRC13
MISCREG_ICH_LRC14
MISCREG_ICH_LRC15
MISCREG_ID_AA64ZFR0_EL1
MISCREG_ZCR_EL3
MISCREG_ZCR_EL2
MISCREG_ZCR_EL12
MISCREG_ZCR_EL1
NUM_PHYS_MISCREGS
MISCREG_NOP
MISCREG_RAZ
MISCREG_CP14_UNIMPL
MISCREG_CP15_UNIMPL
MISCREG_UNKNOWN
MISCREG_IMPDEF_UNIMPL
MISCREG_ERRIDR_EL1
MISCREG_ERRSELR_EL1
MISCREG_ERXFR_EL1
MISCREG_ERXCTLR_EL1
MISCREG_ERXSTATUS_EL1
MISCREG_ERXADDR_EL1
MISCREG_ERXMISC0_EL1
MISCREG_ERXMISC1_EL1
MISCREG_DISR_EL1
MISCREG_VSESR_EL2
MISCREG_VDISR_EL2
MISCREG_PAN
NUM_MISCREGS
Definition at line 57 of file miscregs.hh.
MiscRegInfo
enum ArmISA::MiscRegInfo
Enumerator
MISCREG_IMPLEMENTED
MISCREG_UNVERIFIABLE
MISCREG_WARN_NOT_FAIL
MISCREG_MUTEX
MISCREG_BANKED
MISCREG_BANKED64
MISCREG_BANKED_CHILD
MISCREG_USR_NS_RD
MISCREG_USR_NS_WR
MISCREG_USR_S_RD
MISCREG_USR_S_WR
MISCREG_PRI_NS_RD
MISCREG_PRI_NS_WR
MISCREG_PRI_S_RD
MISCREG_PRI_S_WR
MISCREG_HYP_RD
MISCREG_HYP_WR
MISCREG_MON_NS0_RD
MISCREG_MON_NS0_WR
MISCREG_MON_NS1_RD
MISCREG_MON_NS1_WR
NUM_MISCREG_INFOS
Definition at line 941 of file miscregs.hh.
OperatingMode
enum ArmISA::OperatingMode
Enumerator
MODE_EL0T
MODE_EL1T
MODE_EL1H
MODE_EL2T
MODE_EL2H
MODE_EL3T
MODE_EL3H
MODE_USER
MODE_FIQ
MODE_IRQ
MODE_SVC
MODE_MON
MODE_ABORT
MODE_HYP
MODE_UNDEFINED
MODE_SYSTEM
MODE_MAXMODE
Definition at line 592 of file types.hh.
RoundMode
enum ArmISA::RoundMode
Enumerator
RND_ZERO
RND_DOWN
RND_UP
RND_NEAREST
Definition at line 578 of file types.hh.
SvePredType
enum ArmISA::SvePredType strong
Enumerator
NONE
MERGE
ZERO
SELECT
Definition at line 47 of file sve.hh.
VfpMicroMode
enum ArmISA::VfpMicroMode
Enumerator
VfpNotAMicroop
VfpMicroop
VfpFirstMicroop
VfpLastMicroop
Definition at line 53 of file vfp.hh.
VfpRoundingMode
enum ArmISA::VfpRoundingMode
Enumerator
VfpRoundNearest
VfpRoundUpward
VfpRoundDown
VfpRoundZero
VfpRoundAway
Definition at line 102 of file vfp.hh.
Function Documentation
aarch64SysRegReadOnly()
bool ArmISA::aarch64SysRegReadOnly (MiscRegIndex miscReg)
add128()
static void ArmISA::add128 (uint64_t * x0, uint64_t * x1, uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1) inline static
Definition at line 195 of file fplib.cc.
References MipsISA::a0.
Referenced by fp64_muladd().
advancePC()
void ArmISA::advancePC (PCState & pc, const StaticInstPtr & inst) inline
Definition at line 341 of file utility.hh.
References StaticInst::advancePC(), roundPage(), and truncPage().
badMode()
bool ArmISA::badMode (ThreadContext * tc, OperatingMode mode)
badMode is checking if the execution mode provided as an argument is valid and implemented.
Parameters
tc ThreadContext
mode OperatingMode to check
Returns
false if mode is valid and implemented, true otherwise
Definition at line 388 of file utility.cc.
References ArmSystem::haveEL(), opModeToEL(), and unknownMode().
Referenced by ArmISA::ArmStaticInst::cpsrWriteByInstr(), and currEL().
badMode32()
bool ArmISA::badMode32 (ThreadContext * tc, OperatingMode mode)
badMode is checking if the execution mode provided as an argument is valid and implemented for AArch32
Parameters
tc ThreadContext
mode OperatingMode to check
Returns
false if mode is valid and implemented, true otherwise
Definition at line 382 of file utility.cc.
References ArmSystem::haveEL(), opModeToEL(), and unknownMode32().
Referenced by currEL().
bitsToFp() [1/2]
static float ArmISA::bitsToFp (uint64_t bits, float junk) inline static
Definition at line 180 of file vfp.hh.
References bits(), fp, and X86ISA::val.
Referenced by ArmISA::FpOp::binaryOp(), ArmISA::FpOp::dbl(), fixDest(), fixDivDest(), fixFpDFpSDest(), fixFpSFpDDest(), flushToZero(), fpMulAdd(), fpRecipEstimate(), fprSqrtEstimate(), makeDouble(), ArmISA::FpOp::processNans(), ArmISA::FpOp::ternaryOp(), ArmISA::FpOp::unaryOp(), unsignedRecipEstimate(), unsignedRSqrtEstimate(), vcvtFpHFpD(), and vcvtFpHFpS().
bitsToFp() [2/2]
static double ArmISA::bitsToFp (uint64_t bits, double junk) inline static
Definition at line 192 of file vfp.hh.
References bits(), fp, and X86ISA::val.
BitUnion32()
ArmISA::BitUnion32 (CPSR)
BitUnion8() [1/2]
ArmISA::BitUnion8 (ITSTATE)
BitUnion8() [2/2]
ArmISA::BitUnion8 (OperatingMode64)
buildRetPC()
PCState ArmISA::buildRetPC (const PCState & curPC, const PCState & callPC) inline
Definition at line 62 of file utility.hh.
byteOrder()
ByteOrder ArmISA::byteOrder (ThreadContext * tc) inline
Definition at line 385 of file utility.hh.
References BigEndianByteOrder, isBigEndian64(), and LittleEndianByteOrder.
Referenced by ArmSemihosting::call32(), ArmSemihosting::call64(), clock_gettimeFunc(), copyOutStat64Buf(), copyOutStatBuf(), copyOutStatfsBuf(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), ArmISA::TableWalker::doLongDescriptor(), getrlimitFunc(), getrusageFunc(), gettimeofdayFunc(), prlimitFunc(), ArmSemihosting::readString(), readvFunc(), ArmSemihosting::semiExit(), timeFunc(), timesFunc(), utimesFunc(), and writevFunc().
canReadAArch64SysReg()
bool ArmISA::canReadAArch64SysReg (MiscRegIndex reg, SCR scr, CPSR cpsr, ThreadContext * tc)
Definition at line 1120 of file miscregs.cc.
References currEL(), EL0, EL1, EL2, EL3, ArmSystem::haveSecurity(), ArmSystem::highestEL(), MISCREG_HYP_RD, MISCREG_MON_NS0_RD, MISCREG_MON_NS1_RD, MISCREG_PRI_NS_RD, MISCREG_PRI_S_RD, MISCREG_RVBAR_EL1, MISCREG_RVBAR_EL2, MISCREG_SP_EL0, MISCREG_SPSEL, MISCREG_USR_NS_RD, MISCREG_USR_S_RD, miscRegInfo, panic, ThreadContext::readMiscReg(), and X86ISA::reg.
canReadCoprocReg()
std::tuple< bool, bool > ArmISA::canReadCoprocReg (MiscRegIndex reg, SCR scr, CPSR cpsr)
Check for permission to read coprocessor registers.
Checks whether an instruction at the current program mode has permissions to read the coprocessor registers. This function returns whether the check is undefined and if not whether the read access is permitted.
Parameters
the misc reg indicating the coprocessor
the SCR
the CPSR
Returns
a tuple of booleans: can_read, undefined
Definition at line 991 of file miscregs.cc.
References MISCREG_BANKED, MISCREG_HYP_RD, MISCREG_MON_NS0_RD, MISCREG_MON_NS1_RD, MISCREG_PRI_NS_RD, MISCREG_PRI_S_RD, MISCREG_USR_NS_RD, MISCREG_USR_S_RD, miscRegInfo, MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, MODE_USER, and X86ISA::reg.
canWriteAArch64SysReg()
bool ArmISA::canWriteAArch64SysReg (MiscRegIndex reg, SCR scr, CPSR cpsr, ThreadContext * tc)
Definition at line 1158 of file miscregs.cc.
References currEL(), el, EL0, EL1, EL2, EL3, FullSystem, ArmSystem::haveSecurity(), MISCREG_DAIF, MISCREG_DC_CIVAC_Xt, MISCREG_DC_CVAC_Xt, MISCREG_DC_ZVA_Xt, MISCREG_HYP_WR, MISCREG_MON_NS0_WR, MISCREG_MON_NS1_WR, MISCREG_PRI_NS_WR, MISCREG_PRI_S_WR, MISCREG_SCTLR_EL1, MISCREG_SP_EL0, MISCREG_SPSEL, MISCREG_USR_NS_WR, MISCREG_USR_S_WR, miscRegInfo, panic, ThreadContext::readMiscReg(), and X86ISA::reg.
canWriteCoprocReg()
std::tuple< bool, bool > ArmISA::canWriteCoprocReg (MiscRegIndex reg, SCR scr, CPSR cpsr)
Check for permission to write coprocessor registers.
Checks whether an instruction at the current program mode has permissions to write the coprocessor registers. This function returns whether the check is undefined and if not whether the write access is permitted.
Parameters
the misc reg indicating the coprocessor
the SCR
the CPSR
Returns
a tuple of booleans: can_write, undefined
Definition at line 1027 of file miscregs.cc.
References MISCREG_BANKED, MISCREG_HYP_WR, MISCREG_MON_NS0_WR, MISCREG_MON_NS1_WR, MISCREG_PRI_NS_WR, MISCREG_PRI_S_WR, MISCREG_USR_NS_WR, MISCREG_USR_S_WR, miscRegInfo, MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, MODE_USER, and X86ISA::reg.
cmp128()
static int ArmISA::cmp128 (uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1) inline static
Definition at line 211 of file fplib.cc.
Referenced by fp64_div(), fp64_muladd(), and fp64_sqrt().
copyMiscRegs()
static void ArmISA::copyMiscRegs (ThreadContext * src, ThreadContext * dest) inline static
Definition at line 113 of file utility.hh.
References initCPU(), panic, and sendEvent().
copyRegs()
void ArmISA::copyRegs (ThreadContext * src, ThreadContext * dest)
Definition at line 167 of file utility.cc.
References copyVecRegs(), ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), i, MISCREG_CPSR, NumCCRegs, NumFloatRegs, NumIntRegs, NumMiscRegs, ThreadContext::pcState(), ThreadContext::readCCReg(), ThreadContext::readFloatRegFlat(), ThreadContext::readIntRegFlat(), ThreadContext::readMiscRegNoEffect(), ThreadContext::setCCReg(), ThreadContext::setFloatRegFlat(), ThreadContext::setIntRegFlat(), ThreadContext::setMiscReg(), and ThreadContext::setMiscRegNoEffect().
Referenced by ArmLinux::archClone(), and startupCPU().
copyVecRegs()
static void ArmISA::copyVecRegs (ThreadContext * src, ThreadContext * dest) static
Definition at line 149 of file utility.cc.
References RenameMode< ISA >::mode(), NumVecElemPerVecReg, NumVecRegs, ThreadContext::pcState(), ThreadContext::readVecElemFlat(), ThreadContext::readVecRegFlat(), ThreadContext::setVecElemFlat(), and ThreadContext::setVecRegFlat().
Referenced by copyRegs().
currEL() [1/2]
static ExceptionLevel ArmISA::currEL (ThreadContext * tc) inline static
Definition at line 158 of file utility.hh.
References currOpMode(), and opModeToEL().
Referenced by canReadAArch64SysReg(), canWriteAArch64SysReg(), ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), ArmISA::ArmStaticInst::checkFPAdvSIMDEnabled64(), ArmISA::Interrupts::checkInterrupts(), ArmISA::ArmStaticInst::checkSETENDEnabled(), ELUsingAArch32K(), ArmISA::Interrupts::getInterrupt(), isBigEndian64(), ArmISA::PMU::CounterState::isFiltered(), readMPIDR(), ArmISA::UndefinedInstruction::routeToHyp(), ArmISA::SupervisorCall::routeToHyp(), ArmISA::SupervisorTrap::routeToHyp(), ArmISA::PrefetchAbort::routeToHyp(), ArmISA::DataAbort::routeToHyp(), ArmISA::PCAlignmentFault::routeToHyp(), SPAlignmentCheckEnabled(), ArmISA::Interrupts::takeInt(), ArmISA::TLB::tranTypeEL(), and ArmISA::ArmStaticInst::trapWFx().
currEL() [2/2]
ExceptionLevel ArmISA::currEL (CPSR cpsr) inline
Definition at line 164 of file utility.hh.
References badMode(), badMode32(), el, ELIs32(), ELIs64(), ELIsInHost(), ELUsingAArch32K(), isBigEndian64(), mode, and opModeToEL().
currOpMode()
static OperatingMode ArmISA::currOpMode (ThreadContext * tc) inline static
Definition at line 151 of file utility.hh.
References MISCREG_CPSR, and ThreadContext::readMiscReg().
Referenced by currEL().
decode_fp_data_type()
static FpDataType ArmISA::decode_fp_data_type (uint8_t encoding) inline static
Definition at line 196 of file pred_inst.hh.
References Fp16, Fp32, Fp64, and panic.
decodeAArch64SysReg()
MiscRegIndex ArmISA::decodeAArch64SysReg (unsigned op0, unsigned op1, unsigned crn, unsigned crm, unsigned op2)
Definition at line 1202 of file miscregs.cc.
References M5_FALLTHROUGH, MISCREG_ACTLR_EL1, MISCREG_ACTLR_EL2, MISCREG_ACTLR_EL3, MISCREG_AFSR0_EL1, MISCREG_AFSR0_EL2, MISCREG_AFSR0_EL3, MISCREG_AFSR1_EL1, MISCREG_AFSR1_EL2, MISCREG_AFSR1_EL3, MISCREG_AIDR_EL1, MISCREG_AMAIR_EL1, MISCREG_AMAIR_EL2, MISCREG_AMAIR_EL3, MISCREG_AT_S12E0R_Xt, MISCREG_AT_S12E0W_Xt, MISCREG_AT_S12E1R_Xt, MISCREG_AT_S12E1W_Xt, MISCREG_AT_S1E0R_Xt, MISCREG_AT_S1E0W_Xt, MISCREG_AT_S1E1R_Xt, MISCREG_AT_S1E1W_Xt, MISCREG_AT_S1E2R_Xt, MISCREG_AT_S1E2W_Xt, MISCREG_AT_S1E3R_Xt, MISCREG_AT_S1E3W_Xt, MISCREG_CBAR_EL1, MISCREG_CCSIDR_EL1, MISCREG_CLIDR_EL1, MISCREG_CNTFRQ_EL0, MISCREG_CNTHCTL_EL2, MISCREG_CNTHP_CTL_EL2, MISCREG_CNTHP_CVAL_EL2, MISCREG_CNTHP_TVAL_EL2, MISCREG_CNTHV_CTL_EL2, MISCREG_CNTHV_CVAL_EL2, MISCREG_CNTHV_TVAL_EL2, MISCREG_CNTKCTL_EL1, MISCREG_CNTP_CTL_EL0, MISCREG_CNTP_CVAL_EL0, MISCREG_CNTP_TVAL_EL0, MISCREG_CNTPCT_EL0, MISCREG_CNTPS_CTL_EL1, MISCREG_CNTPS_CVAL_EL1, MISCREG_CNTPS_TVAL_EL1, MISCREG_CNTV_CTL_EL0, MISCREG_CNTV_CVAL_EL0, MISCREG_CNTV_TVAL_EL0, MISCREG_CNTVCT_EL0, MISCREG_CNTVOFF_EL2, MISCREG_CONTEXTIDR_EL1, MISCREG_CONTEXTIDR_EL2, MISCREG_CPACR_EL1, MISCREG_CPTR_EL2, MISCREG_CPTR_EL3, MISCREG_CPUACTLR_EL1, MISCREG_CPUECTLR_EL1, MISCREG_CPUMERRSR_EL1, MISCREG_CSSELR_EL1, MISCREG_CTR_EL0, MISCREG_CURRENTEL, MISCREG_DACR32_EL2, MISCREG_DAIF, MISCREG_DBGAUTHSTATUS_EL1, MISCREG_DBGBCR0_EL1, MISCREG_DBGBCR1_EL1, MISCREG_DBGBCR2_EL1, MISCREG_DBGBCR3_EL1, MISCREG_DBGBCR4_EL1, MISCREG_DBGBCR5_EL1, MISCREG_DBGBVR0_EL1, MISCREG_DBGBVR1_EL1, MISCREG_DBGBVR2_EL1, MISCREG_DBGBVR3_EL1, MISCREG_DBGBVR4_EL1, MISCREG_DBGBVR5_EL1, MISCREG_DBGCLAIMCLR_EL1, MISCREG_DBGCLAIMSET_EL1, MISCREG_DBGPRCR_EL1, MISCREG_DBGVCR32_EL2, MISCREG_DBGWCR0_EL1, MISCREG_DBGWCR1_EL1, MISCREG_DBGWCR2_EL1, MISCREG_DBGWCR3_EL1, MISCREG_DBGWVR0_EL1, MISCREG_DBGWVR1_EL1, MISCREG_DBGWVR2_EL1, MISCREG_DBGWVR3_EL1, MISCREG_DC_CISW_Xt, MISCREG_DC_CIVAC_Xt, MISCREG_DC_CSW_Xt, MISCREG_DC_CVAC_Xt, MISCREG_DC_CVAU_Xt, MISCREG_DC_ISW_Xt, MISCREG_DC_IVAC_Xt, MISCREG_DC_ZVA_Xt, MISCREG_DCZID_EL0, MISCREG_DISR_EL1, MISCREG_DL1DATA0_EL1, MISCREG_DL1DATA1_EL1, MISCREG_DL1DATA2_EL1, MISCREG_DL1DATA3_EL1, MISCREG_DL1DATA4_EL1, MISCREG_DLR_EL0, MISCREG_DSPSR_EL0, MISCREG_ELR_EL1, MISCREG_ELR_EL2, MISCREG_ELR_EL3, MISCREG_ERRIDR_EL1, MISCREG_ERRSELR_EL1, MISCREG_ERXADDR_EL1, MISCREG_ERXCTLR_EL1, MISCREG_ERXFR_EL1, MISCREG_ERXMISC0_EL1, MISCREG_ERXMISC1_EL1, MISCREG_ERXSTATUS_EL1, MISCREG_ESR_EL1, MISCREG_ESR_EL2, MISCREG_ESR_EL3, MISCREG_FAR_EL1, MISCREG_FAR_EL2, MISCREG_FAR_EL3, MISCREG_FPCR, MISCREG_FPEXC32_EL2, MISCREG_FPSR, MISCREG_HACR_EL2, MISCREG_HCR_EL2, MISCREG_HPFAR_EL2, MISCREG_HSTR_EL2, MISCREG_IC_IALLU, MISCREG_IC_IALLUIS, MISCREG_IC_IVAU_Xt, MISCREG_ICC_AP0R0_EL1, MISCREG_ICC_AP0R1_EL1, MISCREG_ICC_AP0R2_EL1, MISCREG_ICC_AP0R3_EL1, MISCREG_ICC_AP1R0_EL1, MISCREG_ICC_AP1R1_EL1, MISCREG_ICC_AP1R2_EL1, MISCREG_ICC_AP1R3_EL1, MISCREG_ICC_ASGI1R_EL1, MISCREG_ICC_BPR0_EL1, MISCREG_ICC_BPR1_EL1, MISCREG_ICC_CTLR_EL1, MISCREG_ICC_CTLR_EL3, MISCREG_ICC_DIR_EL1, MISCREG_ICC_EOIR0_EL1, MISCREG_ICC_EOIR1_EL1, MISCREG_ICC_HPPIR0_EL1, MISCREG_ICC_HPPIR1_EL1, MISCREG_ICC_IAR0_EL1, MISCREG_ICC_IAR1_EL1, MISCREG_ICC_IGRPEN0_EL1, MISCREG_ICC_IGRPEN1_EL1, MISCREG_ICC_IGRPEN1_EL3, MISCREG_ICC_PMR_EL1, MISCREG_ICC_RPR_EL1, MISCREG_ICC_SGI0R_EL1, MISCREG_ICC_SGI1R_EL1, MISCREG_ICC_SRE_EL1, MISCREG_ICC_SRE_EL2, MISCREG_ICC_SRE_EL3, MISCREG_ICH_AP0R0_EL2, MISCREG_ICH_AP0R1_EL2, MISCREG_ICH_AP0R2_EL2, MISCREG_ICH_AP0R3_EL2, MISCREG_ICH_AP1R0_EL2, MISCREG_ICH_AP1R1_EL2, MISCREG_ICH_AP1R2_EL2, MISCREG_ICH_AP1R3_EL2, MISCREG_ICH_EISR_EL2, MISCREG_ICH_ELRSR_EL2, MISCREG_ICH_HCR_EL2, MISCREG_ICH_LR0_EL2, MISCREG_ICH_LR10_EL2, MISCREG_ICH_LR11_EL2, MISCREG_ICH_LR12_EL2, MISCREG_ICH_LR13_EL2, MISCREG_ICH_LR14_EL2, MISCREG_ICH_LR15_EL2, MISCREG_ICH_LR1_EL2, MISCREG_ICH_LR2_EL2, MISCREG_ICH_LR3_EL2, MISCREG_ICH_LR4_EL2, MISCREG_ICH_LR5_EL2, MISCREG_ICH_LR6_EL2, MISCREG_ICH_LR7_EL2, MISCREG_ICH_LR8_EL2, MISCREG_ICH_LR9_EL2, MISCREG_ICH_MISR_EL2, MISCREG_ICH_VMCR_EL2, MISCREG_ICH_VTR_EL2, MISCREG_ID_AA64AFR0_EL1, MISCREG_ID_AA64AFR1_EL1, MISCREG_ID_AA64DFR0_EL1, MISCREG_ID_AA64DFR1_EL1, MISCREG_ID_AA64ISAR0_EL1, MISCREG_ID_AA64ISAR1_EL1, MISCREG_ID_AA64MMFR0_EL1, MISCREG_ID_AA64MMFR1_EL1, MISCREG_ID_AA64MMFR2_EL1, MISCREG_ID_AA64PFR0_EL1, MISCREG_ID_AA64PFR1_EL1, MISCREG_ID_AA64ZFR0_EL1, MISCREG_ID_AFR0_EL1, MISCREG_ID_DFR0_EL1, MISCREG_ID_ISAR0_EL1, MISCREG_ID_ISAR1_EL1, MISCREG_ID_ISAR2_EL1, MISCREG_ID_ISAR3_EL1, MISCREG_ID_ISAR4_EL1, MISCREG_ID_ISAR5_EL1, MISCREG_ID_MMFR0_EL1, MISCREG_ID_MMFR1_EL1, MISCREG_ID_MMFR2_EL1, MISCREG_ID_MMFR3_EL1, MISCREG_ID_PFR0_EL1, MISCREG_ID_PFR1_EL1, MISCREG_IFSR32_EL2, MISCREG_IL1DATA0_EL1, MISCREG_IL1DATA1_EL1, MISCREG_IL1DATA2_EL1, MISCREG_IL1DATA3_EL1, MISCREG_IMPDEF_UNIMPL, MISCREG_ISR_EL1, MISCREG_L2ACTLR_EL1, MISCREG_L2CTLR_EL1, MISCREG_L2ECTLR_EL1, MISCREG_L2MERRSR_EL1, MISCREG_MAIR_EL1, MISCREG_MAIR_EL2, MISCREG_MAIR_EL3, MISCREG_MDCCINT_EL1, MISCREG_MDCCSR_EL0, MISCREG_MDCR_EL2, MISCREG_MDCR_EL3, MISCREG_MDDTR_EL0, MISCREG_MDDTRRX_EL0, MISCREG_MDRAR_EL1, MISCREG_MDSCR_EL1, MISCREG_MIDR_EL1, MISCREG_MPIDR_EL1, MISCREG_MVFR0_EL1, MISCREG_MVFR1_EL1, MISCREG_MVFR2_EL1, MISCREG_NZCV, MISCREG_OSDLR_EL1, MISCREG_OSDTRRX_EL1, MISCREG_OSDTRTX_EL1, MISCREG_OSECCR_EL1, MISCREG_OSLAR_EL1, MISCREG_OSLSR_EL1, MISCREG_PAN, MISCREG_PAR_EL1, MISCREG_PMCCFILTR_EL0, MISCREG_PMCCNTR_EL0, MISCREG_PMCEID0_EL0, MISCREG_PMCEID1_EL0, MISCREG_PMCNTENCLR_EL0, MISCREG_PMCNTENSET_EL0, MISCREG_PMCR_EL0, MISCREG_PMEVCNTR0_EL0, MISCREG_PMEVCNTR1_EL0, MISCREG_PMEVCNTR2_EL0, MISCREG_PMEVCNTR3_EL0, MISCREG_PMEVCNTR4_EL0, MISCREG_PMEVCNTR5_EL0, MISCREG_PMEVTYPER0_EL0, MISCREG_PMEVTYPER1_EL0, MISCREG_PMEVTYPER2_EL0, MISCREG_PMEVTYPER3_EL0, MISCREG_PMEVTYPER4_EL0, MISCREG_PMEVTYPER5_EL0, MISCREG_PMINTENCLR_EL1, MISCREG_PMINTENSET_EL1, MISCREG_PMOVSCLR_EL0, MISCREG_PMOVSSET_EL0, MISCREG_PMSELR_EL0, MISCREG_PMSWINC_EL0, MISCREG_PMUSERENR_EL0, MISCREG_PMXEVCNTR_EL0, MISCREG_PMXEVTYPER_EL0, MISCREG_RAZ, MISCREG_REVIDR_EL1, MISCREG_RMR_EL3, MISCREG_RVBAR_EL1, MISCREG_RVBAR_EL2, MISCREG_RVBAR_EL3, MISCREG_SCR_EL3, MISCREG_SCTLR_EL1, MISCREG_SCTLR_EL2, MISCREG_SCTLR_EL3, MISCREG_SDER32_EL3, MISCREG_SP_EL0, MISCREG_SP_EL1, MISCREG_SP_EL2, MISCREG_SPSEL, MISCREG_SPSR_ABT_AA64, MISCREG_SPSR_EL1, MISCREG_SPSR_EL2, MISCREG_SPSR_EL3, MISCREG_SPSR_FIQ_AA64, MISCREG_SPSR_IRQ_AA64, MISCREG_SPSR_UND_AA64, MISCREG_TCR_EL1, MISCREG_TCR_EL2, MISCREG_TCR_EL3, MISCREG_TEECR32_EL1, MISCREG_TEEHBR32_EL1, MISCREG_TLBI_ALLE1, MISCREG_TLBI_ALLE1IS, MISCREG_TLBI_ALLE2, MISCREG_TLBI_ALLE2IS, MISCREG_TLBI_ALLE3, MISCREG_TLBI_ALLE3IS, MISCREG_TLBI_ASIDE1_Xt, MISCREG_TLBI_ASIDE1IS_Xt, MISCREG_TLBI_IPAS2E1_Xt, MISCREG_TLBI_IPAS2E1IS_Xt, MISCREG_TLBI_IPAS2LE1_Xt, MISCREG_TLBI_IPAS2LE1IS_Xt, MISCREG_TLBI_VAAE1_Xt, MISCREG_TLBI_VAAE1IS_Xt, MISCREG_TLBI_VAALE1_Xt, MISCREG_TLBI_VAALE1IS_Xt, MISCREG_TLBI_VAE1_Xt, MISCREG_TLBI_VAE1IS_Xt, MISCREG_TLBI_VAE2_Xt, MISCREG_TLBI_VAE2IS_Xt, MISCREG_TLBI_VAE3_Xt, MISCREG_TLBI_VAE3IS_Xt, MISCREG_TLBI_VALE1_Xt, MISCREG_TLBI_VALE1IS_Xt, MISCREG_TLBI_VALE2_Xt, MISCREG_TLBI_VALE2IS_Xt, MISCREG_TLBI_VALE3_Xt, MISCREG_TLBI_VALE3IS_Xt, MISCREG_TLBI_VMALLE1, MISCREG_TLBI_VMALLE1IS, MISCREG_TLBI_VMALLS12E1, MISCREG_TLBI_VMALLS12E1IS, MISCREG_TPIDR_EL0, MISCREG_TPIDR_EL1, MISCREG_TPIDR_EL2, MISCREG_TPIDR_EL3, MISCREG_TPIDRRO_EL0, MISCREG_TTBR0_EL1, MISCREG_TTBR0_EL2, MISCREG_TTBR0_EL3, MISCREG_TTBR1_EL1, MISCREG_TTBR1_EL2, MISCREG_UNKNOWN, MISCREG_VBAR_EL1, MISCREG_VBAR_EL2, MISCREG_VBAR_EL3, MISCREG_VDISR_EL2, MISCREG_VMPIDR_EL2, MISCREG_VPIDR_EL2, MISCREG_VSESR_EL2, MISCREG_VTCR_EL2, MISCREG_VTTBR_EL2, MISCREG_ZCR_EL1, MISCREG_ZCR_EL12, MISCREG_ZCR_EL2, and MISCREG_ZCR_EL3.
Referenced by ArmV8KvmCPU::dump(), and ArmV8KvmCPU::getSysRegMap().
decodeCP14Reg()
MiscRegIndex ArmISA::decodeCP14Reg (unsigned crn, unsigned opc1, unsigned crm, unsigned opc2)
Definition at line 55 of file miscregs.cc.
References MISCREG_CP14_UNIMPL, MISCREG_DBGDIDR, MISCREG_DBGDSCRint, MISCREG_JIDR, MISCREG_JMCR, MISCREG_JOSCR, MISCREG_TEEHBR, and warn.
Referenced by ArmKvmCPU::decodeCoProcReg().
decodeCP15Reg()
MiscRegIndex ArmISA::decodeCP15Reg (unsigned crn, unsigned opc1, unsigned crm, unsigned opc2)
Definition at line 132 of file miscregs.cc.
References MISCREG_ACTLR, MISCREG_ADFSR, MISCREG_AIDR, MISCREG_AIFSR, MISCREG_AMAIR0, MISCREG_AMAIR1, MISCREG_ATS12NSOPR, MISCREG_ATS12NSOPW, MISCREG_ATS12NSOUR, MISCREG_ATS12NSOUW, MISCREG_ATS1CPR, MISCREG_ATS1CPW, MISCREG_ATS1CUR, MISCREG_ATS1CUW, MISCREG_ATS1HR, MISCREG_ATS1HW, MISCREG_BPIALL, MISCREG_BPIALLIS, MISCREG_BPIMVA, MISCREG_CCSIDR, MISCREG_CLIDR, MISCREG_CNTFRQ, MISCREG_CNTHCTL, MISCREG_CNTHP_CTL, MISCREG_CNTHP_TVAL, MISCREG_CNTKCTL, MISCREG_CNTP_CTL, MISCREG_CNTP_TVAL, MISCREG_CNTV_CTL, MISCREG_CNTV_TVAL, MISCREG_CONTEXTIDR, MISCREG_CP15_UNIMPL, MISCREG_CP15DMB, MISCREG_CP15DSB, MISCREG_CP15ISB, MISCREG_CPACR, MISCREG_CSSELR, MISCREG_CTR, MISCREG_DACR, MISCREG_DCCIMVAC, MISCREG_DCCISW, MISCREG_DCCMVAC, MISCREG_DCCMVAU, MISCREG_DCCSW, MISCREG_DCIMVAC, MISCREG_DCISW, MISCREG_DFAR, MISCREG_DFSR, MISCREG_DTLBIALL, MISCREG_DTLBIASID, MISCREG_DTLBIMVA, MISCREG_FCSEIDR, MISCREG_HACR, MISCREG_HACTLR, MISCREG_HADFSR, MISCREG_HAIFSR, MISCREG_HAMAIR0, MISCREG_HAMAIR1, MISCREG_HCPTR, MISCREG_HCR, MISCREG_HCR2, MISCREG_HDCR, MISCREG_HDFAR, MISCREG_HIFAR, MISCREG_HMAIR0, MISCREG_HMAIR1, MISCREG_HPFAR, MISCREG_HSCTLR, MISCREG_HSR, MISCREG_HSTR, MISCREG_HTCR, MISCREG_HTPIDR, MISCREG_HVBAR, MISCREG_ICC_AP0R0, MISCREG_ICC_AP0R1, MISCREG_ICC_AP0R2, MISCREG_ICC_AP0R3, MISCREG_ICC_AP1R0, MISCREG_ICC_AP1R1, MISCREG_ICC_AP1R2, MISCREG_ICC_AP1R3, MISCREG_ICC_BPR0, MISCREG_ICC_BPR1, MISCREG_ICC_CTLR, MISCREG_ICC_DIR, MISCREG_ICC_EOIR0, MISCREG_ICC_EOIR1, MISCREG_ICC_HPPIR0, MISCREG_ICC_HPPIR1, MISCREG_ICC_HSRE, MISCREG_ICC_IAR0, MISCREG_ICC_IAR1, MISCREG_ICC_IGRPEN0, MISCREG_ICC_IGRPEN1, MISCREG_ICC_MCTLR, MISCREG_ICC_MGRPEN1, MISCREG_ICC_MSRE, MISCREG_ICC_PMR, MISCREG_ICC_RPR, MISCREG_ICC_SRE, MISCREG_ICH_AP0R0, MISCREG_ICH_AP0R1, MISCREG_ICH_AP0R2, MISCREG_ICH_AP0R3, MISCREG_ICH_AP1R0, MISCREG_ICH_AP1R1, MISCREG_ICH_AP1R2, MISCREG_ICH_AP1R3, MISCREG_ICH_EISR, MISCREG_ICH_ELRSR, MISCREG_ICH_HCR, MISCREG_ICH_LR0, MISCREG_ICH_LR1, MISCREG_ICH_LR10, MISCREG_ICH_LR11, MISCREG_ICH_LR12, MISCREG_ICH_LR13, MISCREG_ICH_LR14, MISCREG_ICH_LR15, MISCREG_ICH_LR2, MISCREG_ICH_LR3, MISCREG_ICH_LR4, MISCREG_ICH_LR5, MISCREG_ICH_LR6, MISCREG_ICH_LR7, MISCREG_ICH_LR8, MISCREG_ICH_LR9, MISCREG_ICH_LRC0, MISCREG_ICH_LRC1, MISCREG_ICH_LRC10, MISCREG_ICH_LRC11, MISCREG_ICH_LRC12, MISCREG_ICH_LRC13, MISCREG_ICH_LRC14, MISCREG_ICH_LRC15, MISCREG_ICH_LRC2, MISCREG_ICH_LRC3, MISCREG_ICH_LRC4, MISCREG_ICH_LRC5, MISCREG_ICH_LRC6, MISCREG_ICH_LRC7, MISCREG_ICH_LRC8, MISCREG_ICH_LRC9, MISCREG_ICH_MISR, MISCREG_ICH_VMCR, MISCREG_ICH_VTR, MISCREG_ICIALLU, MISCREG_ICIALLUIS, MISCREG_ICIMVAU, MISCREG_ID_AFR0, MISCREG_ID_DFR0, MISCREG_ID_ISAR0, MISCREG_ID_ISAR1, MISCREG_ID_ISAR2, MISCREG_ID_ISAR3, MISCREG_ID_ISAR4, MISCREG_ID_ISAR5, MISCREG_ID_MMFR0, MISCREG_ID_MMFR1, MISCREG_ID_MMFR2, MISCREG_ID_MMFR3, MISCREG_ID_PFR0, MISCREG_ID_PFR1, MISCREG_IFAR, MISCREG_IFSR, MISCREG_IMPDEF_UNIMPL, MISCREG_ISR, MISCREG_ITLBIALL, MISCREG_ITLBIASID, MISCREG_ITLBIMVA, MISCREG_L2CTLR, MISCREG_L2ECTLR, MISCREG_MIDR, MISCREG_MPIDR, MISCREG_MVBAR, MISCREG_NMRR_MAIR1, MISCREG_NOP, MISCREG_NSACR, MISCREG_PAR, MISCREG_PMCCNTR, MISCREG_PMCEID0, MISCREG_PMCEID1, MISCREG_PMCNTENCLR, MISCREG_PMCNTENSET, MISCREG_PMCR, MISCREG_PMINTENCLR, MISCREG_PMINTENSET, MISCREG_PMOVSR, MISCREG_PMOVSSET, MISCREG_PMSELR, MISCREG_PMSWINC, MISCREG_PMUSERENR, MISCREG_PMXEVCNTR, MISCREG_PMXEVTYPER_PMCCFILTR, MISCREG_PRRR_MAIR0, MISCREG_RAZ, MISCREG_REVIDR, MISCREG_SCR, MISCREG_SCTLR, MISCREG_SDER, MISCREG_TCMTR, MISCREG_TLBIALL, MISCREG_TLBIALLH, MISCREG_TLBIALLHIS, MISCREG_TLBIALLIS, MISCREG_TLBIALLNSNH, MISCREG_TLBIALLNSNHIS, MISCREG_TLBIASID, MISCREG_TLBIASIDIS, MISCREG_TLBIIPAS2, MISCREG_TLBIIPAS2IS, MISCREG_TLBIIPAS2L, MISCREG_TLBIIPAS2LIS, MISCREG_TLBIMVA, MISCREG_TLBIMVAA, MISCREG_TLBIMVAAIS, MISCREG_TLBIMVAAL, MISCREG_TLBIMVAALIS, MISCREG_TLBIMVAH, MISCREG_TLBIMVAHIS, MISCREG_TLBIMVAIS, MISCREG_TLBIMVAL, MISCREG_TLBIMVALH, MISCREG_TLBIMVALHIS, MISCREG_TLBIMVALIS, MISCREG_TLBTR, MISCREG_TPIDRPRW, MISCREG_TPIDRURO, MISCREG_TPIDRURW, MISCREG_TTBCR, MISCREG_TTBR0, MISCREG_TTBR1, MISCREG_VBAR, MISCREG_VMPIDR, MISCREG_VPIDR, and MISCREG_VTCR.
Referenced by ArmKvmCPU::decodeCoProcReg().
decodeCP15Reg64()
MiscRegIndex ArmISA::decodeCP15Reg64 (unsigned crm, unsigned opc1)
Definition at line 932 of file miscregs.cc.
References MISCREG_CNTHP_CVAL, MISCREG_CNTP_CVAL, MISCREG_CNTPCT, MISCREG_CNTV_CVAL, MISCREG_CNTVCT, MISCREG_CNTVOFF, MISCREG_CP15_UNIMPL, MISCREG_CPUMERRSR, MISCREG_HTTBR, MISCREG_ICC_ASGI1R, MISCREG_ICC_SGI0R, MISCREG_ICC_SGI1R, MISCREG_L2MERRSR, MISCREG_PAR, MISCREG_TTBR0, MISCREG_TTBR1, and MISCREG_VTTBR.
decodeMrsMsrBankedIntRegIndex()
static int ArmISA::decodeMrsMsrBankedIntRegIndex (uint8_t sysM, bool r) inline static
Definition at line 365 of file utility.hh.
References decodeMrsMsrBankedReg(), decodePhysAddrRange64(), encodePhysAddrRange64(), and INTREG_DUMMY.
decodeMrsMsrBankedReg()
bool ArmISA::decodeMrsMsrBankedReg (uint8_t sysM, bool r, bool & isIntReg, int & regIdx, CPSR cpsr, SCR scr, NSACR nsacr, bool checkSecurity)
Definition at line 709 of file utility.cc.
References bits(), intRegInMode(), MISCREG_ELR_HYP, MISCREG_SPSR_ABT, MISCREG_SPSR_FIQ, MISCREG_SPSR_HYP, MISCREG_SPSR_IRQ, MISCREG_SPSR_MON, MISCREG_SPSR_SVC, MISCREG_SPSR_UND, mode, MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, MODE_USER, panic, and MipsISA::r.
Referenced by decodeMrsMsrBankedIntRegIndex(), and getExecutingAsid().
decodePhysAddrRange64()
int ArmISA::decodePhysAddrRange64 (uint8_t pa_enc)
Returns the n.
of PA bits corresponding to the specified encoding.
Definition at line 846 of file utility.cc.
References panic.
Referenced by decodeMrsMsrBankedIntRegIndex(), and ArmISA::TableWalker::processWalkAArch64().
ELIs32()
bool ArmISA::ELIs32 (ThreadContext * tc, ExceptionLevel el)
Definition at line 299 of file utility.cc.
References ELUsingAArch32K(), and panic_if.
Referenced by currEL(), ELIs64(), ELIsInHost(), ArmISA::ArmStaticInst::generalExceptionsToAArch64(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), ArmISA::ISA::readMiscReg(), ArmISA::ISA::setMiscReg(), and ArmISA::ArmStaticInst::softwareBreakpoint32().
ELIs64()
bool ArmISA::ELIs64 (ThreadContext * tc, ExceptionLevel el)
Definition at line 293 of file utility.cc.
References ELIs32().
Referenced by ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), ArmISA::ArmStaticInst::checkForWFxTrap32(), currEL(), ArmISA::Stage2LookUp::getTe(), illegalExceptionReturn(), ArmISA::ArmFault::update(), ArmISA::TLB::updateMiscReg(), and ArmISA::TableWalker::walk().
ELIsInHost()
bool ArmISA::ELIsInHost (ThreadContext * tc, ExceptionLevel el)
Returns true if the current exception level el is executing a Host OS or an application of a Host OS (Armv8.1 Virtualization Host Extensions).
Definition at line 308 of file utility.cc.
References EL0, EL2, ELIs32(), ArmSystem::haveVirtualization(), isSecureBelowEL3(), MISCREG_HCR_EL2, and ThreadContext::readMiscReg().
Referenced by currEL(), and ArmISA::ISA::getCurSveVecLenInBits().
ELUsingAArch32K()
std::pair< bool, bool > ArmISA::ELUsingAArch32K (ThreadContext * tc, ExceptionLevel el)
This function checks whether selected EL provided as an argument is using the AArch32 ISA.
This information might be unavailable at the current EL status: it hence returns a pair of boolean values: a first boolean, true if information is available (known), and a second one, true if EL is using AArch32, false for AArch64.
Parameters
tc The thread context.
el The target exception level.
Return values
known is FALSE for EL0 if the current Exception level is not EL0 and EL1 is using AArch64, since it cannot determine the state of EL0; TRUE otherwise.
aarch32 is TRUE if the specified Exception level is using AArch32; FALSE otherwise.
Definition at line 319 of file utility.cc.
References currEL(), EL0, EL1, EL2, EL3, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), ArmSystem::highestEL(), ArmSystem::highestELIs64(), isSecureBelowEL3(), MISCREG_CPSR, MISCREG_HCR_EL2, MISCREG_SCR_EL3, panic_if, and ThreadContext::readMiscReg().
Referenced by currEL(), ELIs32(), and illegalExceptionReturn().
encodePhysAddrRange64()
uint8_t ArmISA::encodePhysAddrRange64 (int pa_size)
Returns the encoding corresponding to the specified n.
of PA bits.
Definition at line 869 of file utility.cc.
References panic.
Referenced by decodeMrsMsrBankedIntRegIndex(), and ArmISA::ISA::initID64().
EndBitUnion() [1/37]
ArmISA::EndBitUnion (ITSTATE)
EndBitUnion() [2/37]
ArmISA::EndBitUnion (CPSR)
EndBitUnion() [3/37]
ArmISA::EndBitUnion (AA64DFR0)
EndBitUnion() [4/37]
ArmISA::EndBitUnion (AA64ISAR0)
EndBitUnion() [5/37]
ArmISA::EndBitUnion (AA64ISAR1)
EndBitUnion() [6/37]
ArmISA::EndBitUnion (AA64MMFR0)
EndBitUnion() [7/37]
ArmISA::EndBitUnion (AA64MMFR1)
EndBitUnion() [8/37]
ArmISA::EndBitUnion (AA64MMFR2)
EndBitUnion() [9/37]
ArmISA::EndBitUnion (AA64PFR0)
EndBitUnion() [10/37]
ArmISA::EndBitUnion (HDCR)
EndBitUnion() [11/37]
ArmISA::EndBitUnion (HCPTR)
EndBitUnion() [12/37]
ArmISA::EndBitUnion (ExtMachInst)
Definition at line 213 of file types.hh.
References aarch64, bits(), DPRINTF, itstate, mask, operator!=(), X86ISA::operator==(), MipsISA::pc, replaceBits(), s, serialize(), SERIALIZE_SCALAR, thumb, unserialize(), UNSERIALIZE_SCALAR, and X86ISA::val.
EndBitUnion() [13/37]
ArmISA::EndBitUnion (HSTR)
EndBitUnion() [14/37]
ArmISA::EndBitUnion (HCR)
EndBitUnion() [15/37]
ArmISA::EndBitUnion (NSACR)
EndBitUnion() [16/37]
ArmISA::EndBitUnion (SCR)
EndBitUnion() [17/37]
ArmISA::EndBitUnion (SCTLR)
EndBitUnion() [18/37]
ArmISA::EndBitUnion (CPACR)
EndBitUnion() [19/37]
ArmISA::EndBitUnion (FSR)
EndBitUnion() [20/37]
ArmISA::EndBitUnion (FPSCR)
EndBitUnion() [21/37]
ArmISA::EndBitUnion (FPEXC)
EndBitUnion() [22/37]
ArmISA::EndBitUnion (MVFR0)
EndBitUnion() [23/37]
ArmISA::EndBitUnion (MVFR1)
EndBitUnion() [24/37]
ArmISA::EndBitUnion (TTBCR)
EndBitUnion() [25/37]
ArmISA::EndBitUnion (TCR)
EndBitUnion() [26/37]
ArmISA::EndBitUnion (HTCR)
EndBitUnion() [27/37]
ArmISA::EndBitUnion (VTCR_t)
EndBitUnion() [28/37]
ArmISA::EndBitUnion (PRRR)
EndBitUnion() [29/37]
ArmISA::EndBitUnion (NMRR)
EndBitUnion() [30/37]
ArmISA::EndBitUnion (CONTEXTIDR)
EndBitUnion() [31/37]
ArmISA::EndBitUnion (L2CTLR)
EndBitUnion() [32/37]
ArmISA::EndBitUnion (CTR)
EndBitUnion() [33/37]
ArmISA::EndBitUnion (PMSELR)
EndBitUnion() [34/37]
ArmISA::EndBitUnion (PAR)
EndBitUnion() [35/37]
ArmISA::EndBitUnion (ESR)
EndBitUnion() [36/37]
ArmISA::EndBitUnion (CPTR)
EndBitUnion() [37/37]
ArmISA::EndBitUnion (OperatingMode64)
Definition at line 667 of file types.hh.
EndSubBitUnion()
ArmISA::EndSubBitUnion (puswl)
finishVfp()
void ArmISA::finishVfp (FPSCR & fpscr, VfpSavedState state, bool flush, FPSCR mask)
Definition at line 195 of file vfp.cc.
References FeAllExceptions, FeDivByZero, FeInexact, FeInvalid, FeOverflow, and FeUnderflow.
Referenced by ArmISA::FpOp::binaryOp(), ArmISA::FpOp::ternaryOp(), and ArmISA::FpOp::unaryOp().
fixDest() [1/4]
template<class fpType > fpType ArmISA::fixDest (FPSCR fpscr, fpType val, fpType op1)
fixDest() [2/4]
template<class fpType > fpType ArmISA::fixDest (bool flush, bool defaultNan, fpType val, fpType op1)
Definition at line 221 of file vfp.cc.
References bitsToFp(), FeInexact, FeUnderflow, fixDest< double >(), fixDest< float >(), HsailISA::fpclassify(), fpToBits(), ArmISA::FpCondCompRegOp::op1, ULL, and X86ISA::val.
Referenced by fixDivDest(), fixFpDFpSDest(), and fixFpSFpDDest().
fixDest() [3/4]
template<class fpType > fpType ArmISA::fixDest (FPSCR fpscr, fpType val, fpType op1, fpType op2)
fixDest() [4/4]
template<class fpType > fpType ArmISA::fixDest (bool flush, bool defaultNan, fpType val, fpType op1, fpType op2)
Definition at line 251 of file vfp.cc.
References bitsToFp(), FeInexact, FeUnderflow, fixDest< double >(), fixDest< float >(), HsailISA::fpclassify(), fpToBits(), ArmISA::FpCondCompRegOp::op1, ArmISA::FpCondCompRegOp::op2, ULL, and X86ISA::val.
fixDest< double >() [1/2]
template double ArmISA::fixDest< double > (bool flush, bool defaultNan, double val, double op1)
Referenced by fixDest().
fixDest< double >() [2/2]
template double ArmISA::fixDest< double > (bool flush, bool defaultNan, double val, double op1, double op2)
fixDest< float >() [1/2]
template float ArmISA::fixDest< float > (bool flush, bool defaultNan, float val, float op1)
Referenced by fixDest().
fixDest< float >() [2/2]
template float ArmISA::fixDest< float > (bool flush, bool defaultNan, float val, float op1, float op2)
fixDivDest() [1/2]
template<class fpType > fpType ArmISA::fixDivDest (FPSCR fpscr, fpType val, fpType op1, fpType op2)
fixDivDest() [2/2]
template<class fpType > fpType ArmISA::fixDivDest (bool flush, bool defaultNan, fpType val, fpType op1, fpType op2)
Definition at line 292 of file vfp.cc.
References bitsToFp(), FeInexact, FeRoundZero, FeUnderflow, fixDest(), fixDivDest< double >(), fixDivDest< float >(), flushToZero, ArmISA::FpCondCompRegOp::op1, ArmISA::FpCondCompRegOp::op2, ULL, and X86ISA::val.
Referenced by vfpSFixedToFpD(), vfpSFixedToFpS(), vfpUFixedToFpD(), and vfpUFixedToFpS().
fixDivDest< double >()
template double ArmISA::fixDivDest< double > (bool flush, bool defaultNan, double val, double op1, double op2)
Referenced by fixDivDest().
fixDivDest< float >()
template float ArmISA::fixDivDest< float > (bool flush, bool defaultNan, float val, float op1, float op2)
Referenced by fixDivDest().
fixFpDFpSDest()
float ArmISA::fixFpDFpSDest (FPSCR fpscr, double val)
Definition at line 327 of file vfp.cc.
References bits(), bitsToFp(), FeInexact, FeRoundZero, FeUnderflow, fixDest(), flushToZero, fpToBits(), mask, and X86ISA::val.
fixFpSFpDDest()
double ArmISA::fixFpSFpDDest (FPSCR fpscr, float val)
Definition at line 363 of file vfp.cc.
References bits(), bitsToFp(), FeInexact, FeRoundZero, FeUnderflow, fixDest(), flushToZero, fpToBits(), mask, ULL, and X86ISA::val.
flattenIntRegModeIndex()
static int ArmISA::flattenIntRegModeIndex (int reg) inline static
Definition at line 471 of file intregs.hh.
References curTick(), INTREG_ABT(), INTREG_FIQ(), INTREG_HYP(), INTREG_IRQ(), INTREG_MON(), INTREG_SVC(), INTREG_UND(), INTREG_USR(), intRegsPerMode, mode, MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, MODE_USER, and panic.
Referenced by ArmISA::ISA::flattenIntIndex().
flushToZero() [1/2]
template<class fpType > static bool ArmISA::flushToZero (fpType & op) inline static
Definition at line 118 of file vfp.hh.
References bitsToFp(), HsailISA::fpclassify(), fpToBits(), and ULL.
flushToZero() [2/2]
template<class fpType > static bool ArmISA::flushToZero (fpType & op1, fpType & op2) inline static
Definition at line 131 of file vfp.hh.
References flushToZero.
fp128_normalise()
static void ArmISA::fp128_normalise (uint64_t * mnt0, uint64_t * mnt1, int * exp) inline static
Definition at line 271 of file fplib.cc.
References shift.
Referenced by fp64_mul(), and fp64_muladd().
fp16_add()
static uint16_t ArmISA::fp16_add (uint16_t a, uint16_t b, int neg, int mode, int * flags) static
Definition at line 1209 of file fplib.cc.
References fp16_defaultNaN(), FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_normalise(), fp16_process_NaNs(), fp16_round(), fp16_unpack(), fp16_zero(), FPLIB_IOC, lsl16(), lsr16(), sc_dt::neg(), and X86ISA::x.
Referenced by fplibAdd(), and fplibSub().
fp16_compare_eq()
static int ArmISA::fp16_compare_eq (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 945 of file fplib.cc.
References fp16_is_NaN(), fp16_is_signalling_NaN(), fp16_unpack(), and FPLIB_IOC.
Referenced by fplibCompareEQ().
fp16_compare_ge()
static int ArmISA::fp16_compare_ge (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 964 of file fplib.cc.
References fp16_is_NaN(), fp16_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGE().
fp16_compare_gt()
static int ArmISA::fp16_compare_gt (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 989 of file fplib.cc.
References fp16_is_NaN(), fp16_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGT().
fp16_compare_un()
static int ArmISA::fp16_compare_un (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 1014 of file fplib.cc.
References fp16_is_NaN(), fp16_is_signalling_NaN(), fp16_unpack(), and FPLIB_IOC.
Referenced by fplibCompareUN().
fp16_cvtf()
static uint16_t ArmISA::fp16_cvtf (uint64_t a, int fbits, int u, int mode, int * flags) static
Definition at line 4829 of file fplib.cc.
References a, FP16_BITS, FP16_EXP_BIAS, fp16_round(), fp16_zero(), FP64_BITS, fp64_normalise(), and ULL.
Referenced by fplibFixedToFP().
fp16_defaultNaN()
static uint16_t ArmISA::fp16_defaultNaN () inline static
Definition at line 372 of file fplib.cc.
References FP16_EXP_INF, FP16_MANT_BITS, fp16_pack(), and ULL.
Referenced by fp16_add(), fp16_div(), fp16_mul(), fp16_muladd(), fp16_process_NaN(), fp16_sqrt(), fplibConvert(), fplibDefaultNaN(), and fplibRSqrtEstimate().
fp16_div()
static uint16_t ArmISA::fp16_div (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 1762 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), FP16_MANT_BITS, fp16_normalise(), fp16_process_NaNs(), fp16_round(), fp16_unpack(), fp16_zero(), fp32_normalise(), FPLIB_DZC, FPLIB_IOC, and X86ISA::x.
Referenced by fplibDiv().
fp16_FPConvertNaN_32()
static uint16_t ArmISA::fp16_FPConvertNaN_32 (uint32_t op) static
Definition at line 2510 of file fplib.cc.
References FP16_EXP_INF, FP16_MANT_BITS, fp16_pack(), FP32_BITS, FP32_MANT_BITS, and ULL.
Referenced by fplibConvert().
fp16_FPConvertNaN_64()
static uint16_t ArmISA::fp16_FPConvertNaN_64 (uint64_t op) static
Definition at line 2518 of file fplib.cc.
References FP16_EXP_INF, FP16_MANT_BITS, fp16_pack(), FP64_BITS, FP64_MANT_BITS, and ULL.
Referenced by fplibConvert().
fp16_FPOnePointFive()
static uint16_t ArmISA::fp16_FPOnePointFive (int sgn) static
Definition at line 2558 of file fplib.cc.
References FP16_EXP_BIAS, FP16_MANT_BITS, fp16_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp16_FPThree()
static uint16_t ArmISA::fp16_FPThree (int sgn) static
Definition at line 2576 of file fplib.cc.
References FP16_EXP_BIAS, FP16_MANT_BITS, fp16_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp16_FPTwo()
static uint16_t ArmISA::fp16_FPTwo (int sgn) static
Definition at line 2594 of file fplib.cc.
References FP16_EXP_BIAS, and fp16_pack().
Referenced by fplibMulX(), and fplibRecipStepFused().
fp16_infinity()
static uint16_t ArmISA::fp16_infinity (int sgn) inline static
Definition at line 354 of file fplib.cc.
References FP16_EXP_INF, and fp16_pack().
Referenced by fp16_add(), fp16_div(), fp16_minmaxnum(), fp16_mul(), fp16_muladd(), fp16_round_(), fp16_scale(), fp16_sqrt(), fplibConvert(), fplibInfinity(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibRSqrtStepFused().
fp16_is_infinity()
static int ArmISA::fp16_is_infinity (int exp, uint16_t mnt) inline static
Definition at line 503 of file fplib.cc.
References FP16_EXP_INF, and FP16_MANT.
Referenced by fp16_muladd().
fp16_is_NaN()
static int ArmISA::fp16_is_NaN (int exp, uint16_t mnt) inline static
Definition at line 449 of file fplib.cc.
References FP16_EXP_INF, and FP16_MANT.
Referenced by fp16_compare_eq(), fp16_compare_ge(), fp16_compare_gt(), fp16_compare_un(), fp16_is_signalling_NaN(), fp16_process_NaNs(), fp16_process_NaNs3(), fp16_scale(), fp16_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibTrigSMul().
fp16_is_quiet_NaN()
static int ArmISA::fp16_is_quiet_NaN (int exp, uint16_t mnt) inline static
Definition at line 485 of file fplib.cc.
References FP16_EXP_INF, and FP16_MANT_BITS.
Referenced by fp16_muladd().
fp16_is_signalling_NaN()
static int ArmISA::fp16_is_signalling_NaN (int exp, uint16_t mnt) inline static
Definition at line 467 of file fplib.cc.
References fp16_is_NaN(), and FP16_MANT_BITS.
Referenced by fp16_compare_eq(), fp16_compare_un(), fp16_process_NaNs(), fp16_process_NaNs3(), and fplibCompare().
fp16_max_normal()
static uint16_t ArmISA::fp16_max_normal (int sgn) inline static
Definition at line 336 of file fplib.cc.
References FP16_EXP_INF, and fp16_pack().
Referenced by fp16_round_(), and fplibRecipEstimate().
fp16_minmaxnum()
static void ArmISA::fp16_minmaxnum (uint16_t * op1, uint16_t * op2, int sgn) static
Definition at line 3131 of file fplib.cc.
References fp16_infinity(), and FP16_MANT_BITS.
Referenced by fplibMaxNum(), and fplibMinNum().
fp16_mul()
static uint16_t ArmISA::fp16_mul (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 1389 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_process_NaNs(), fp16_round(), fp16_unpack(), fp16_zero(), fp32_normalise(), FPLIB_IOC, lsl32(), lsr32(), and X86ISA::x.
Referenced by fplibMul(), fplibMulX(), and fplibTrigSMul().
fp16_muladd()
static uint16_t ArmISA::fp16_muladd (uint16_t a, uint16_t b, uint16_t c, int scale, int mode, int * flags) static
Definition at line 1500 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_is_infinity(), fp16_is_quiet_NaN(), FP16_MANT_BITS, fp16_process_NaNs3(), fp16_round(), fp16_unpack(), fp16_zero(), fp32_normalise(), FPLIB_IOC, lsl32(), lsr32(), and X86ISA::x.
Referenced by fplibMulAdd(), fplibRecipStepFused(), fplibRSqrtStepFused(), and fplibTrigMulAdd().
fp16_normalise()
static uint16_t ArmISA::fp16_normalise (uint16_t mnt, int * exp) inline static
Definition at line 217 of file fplib.cc.
References shift.
Referenced by fp16_add(), fp16_div(), fp16_scale(), fp16_sqrt(), fplibConvert(), fplibRecipEstimate(), fplibRoundInt(), and fplibRSqrtEstimate().
fp16_pack()
static uint16_t ArmISA::fp16_pack (uint16_t sgn, uint16_t exp, uint16_t mnt) inline static
Definition at line 300 of file fplib.cc.
References FP16_BITS, FP16_MANT, and FP16_MANT_BITS.
Referenced by fp16_defaultNaN(), fp16_FPConvertNaN_32(), fp16_FPConvertNaN_64(), fp16_FPOnePointFive(), fp16_FPThree(), fp16_FPTwo(), fp16_infinity(), fp16_max_normal(), fp16_repack(), fp16_round_(), fp16_zero(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp16_process_NaN()
static uint16_t ArmISA::fp16_process_NaN (uint16_t a, int mode, int * flags) inline static
Definition at line 521 of file fplib.cc.
References a, fp16_defaultNaN(), FP16_MANT_BITS, FPLIB_DN, FPLIB_IOC, and ULL.
Referenced by fp16_process_NaNs(), fp16_process_NaNs3(), fp16_scale(), fp16_sqrt(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp16_process_NaNs()
static uint16_t ArmISA::fp16_process_NaNs (uint16_t a, uint16_t b, int mode, int * flags) static
Definition at line 551 of file fplib.cc.
References FP16_EXP, fp16_is_NaN(), fp16_is_signalling_NaN(), FP16_MANT, and fp16_process_NaN().
Referenced by fp16_add(), fp16_div(), fp16_mul(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipStepFused(), and fplibRSqrtStepFused().
fp16_process_NaNs3()
static uint16_t ArmISA::fp16_process_NaNs3 (uint16_t a, uint16_t b, uint16_t c, int mode, int * flags) static
Definition at line 620 of file fplib.cc.
References FP16_EXP, fp16_is_NaN(), fp16_is_signalling_NaN(), FP16_MANT, and fp16_process_NaN().
Referenced by fp16_muladd().
fp16_repack()
static uint16_t ArmISA::fp16_repack (int sgn, int exp, uint16_t mnt) static
Definition at line 3113 of file fplib.cc.
References FP16_MANT_BITS, and fp16_pack().
Referenced by fplibMax(), and fplibMin().
fp16_round()
static uint16_t ArmISA::fp16_round (int sgn, int exp, uint16_t mnt, int mode, int * flags) static
Definition at line 785 of file fplib.cc.
References fp16_round_().
Referenced by fp16_add(), fp16_cvtf(), fp16_div(), fp16_mul(), fp16_muladd(), fp16_scale(), and fp16_sqrt().
fp16_round_()
static uint16_t ArmISA::fp16_round_ (int sgn, int exp, uint16_t mnt, int rm, int mode, int * flags) static
Definition at line 707 of file fplib.cc.
References FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), FP16_MANT_BITS, fp16_max_normal(), fp16_pack(), fp16_zero(), FPLIB_AHP, FPLIB_FZ16, FPLIB_IOC, FPLIB_IXC, FPLIB_OFC, FPLIB_RM, FPLIB_RN, FPLIB_RP, FPLIB_UFC, FPRounding_ODD, FPRounding_TIEAWAY, lsl16(), lsr16(), and ULL.
Referenced by fp16_round(), and fplibConvert().
fp16_scale()
static uint16_t ArmISA::fp16_scale (uint16_t a, int16_t b, int mode, int * flags) static
Definition at line 1924 of file fplib.cc.
References b, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_is_NaN(), fp16_normalise(), fp16_process_NaN(), fp16_round(), fp16_unpack(), and fp16_zero().
Referenced by fplibScale().
fp16_sqrt()
static uint16_t ArmISA::fp16_sqrt (uint16_t a, int mode, int * flags) static
Definition at line 2026 of file fplib.cc.
References fp16_defaultNaN(), FP16_EXP_INF, fp16_infinity(), fp16_is_NaN(), fp16_normalise(), fp16_process_NaN(), fp16_round(), fp16_unpack(), fp16_zero(), FPLIB_IOC, t0, t1, and X86ISA::x.
Referenced by fplibSqrt().
fp16_unpack()
static void ArmISA::fp16_unpack (int * sgn, int * exp, uint16_t * mnt, uint16_t x, int mode, int * flags) inline static
Definition at line 390 of file fplib.cc.
References FP16_BITS, FP16_EXP, FP16_MANT, FP16_MANT_BITS, FPLIB_FZ16, and ULL.
Referenced by fp16_add(), fp16_compare_eq(), fp16_compare_ge(), fp16_compare_gt(), fp16_compare_un(), fp16_div(), fp16_mul(), fp16_muladd(), fp16_scale(), fp16_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), and fplibTrigSMul().
fp16_zero()
static uint16_t ArmISA::fp16_zero (int sgn) inline static
Definition at line 318 of file fplib.cc.
References fp16_pack().
Referenced by fp16_add(), fp16_cvtf(), fp16_div(), fp16_mul(), fp16_muladd(), fp16_round_(), fp16_scale(), fp16_sqrt(), fplibConvert(), fplibMulX(), fplibRecipEstimate(), fplibRoundInt(), and fplibRSqrtEstimate().
fp32_add()
static uint32_t ArmISA::fp32_add (uint32_t a, uint32_t b, int neg, int mode, int * flags) static
Definition at line 1269 of file fplib.cc.
References fp32_defaultNaN(), FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_normalise(), fp32_process_NaNs(), fp32_round(), fp32_unpack(), fp32_zero(), FPLIB_IOC, lsl32(), lsr32(), sc_dt::neg(), and X86ISA::x.
Referenced by fplibAdd(), and fplibSub().
fp32_compare_eq()
static int ArmISA::fp32_compare_eq (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1033 of file fplib.cc.
References fp32_is_NaN(), fp32_is_signalling_NaN(), fp32_unpack(), and FPLIB_IOC.
Referenced by fplibCompareEQ().
fp32_compare_ge()
static int ArmISA::fp32_compare_ge (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1052 of file fplib.cc.
References fp32_is_NaN(), fp32_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGE().
fp32_compare_gt()
static int ArmISA::fp32_compare_gt (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1077 of file fplib.cc.
References fp32_is_NaN(), fp32_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGT().
fp32_compare_un()
static int ArmISA::fp32_compare_un (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1102 of file fplib.cc.
References fp32_is_NaN(), fp32_is_signalling_NaN(), fp32_unpack(), and FPLIB_IOC.
Referenced by fplibCompareUN().
fp32_cvtf()
static uint32_t ArmISA::fp32_cvtf (uint64_t a, int fbits, int u, int mode, int * flags) static
Definition at line 4849 of file fplib.cc.
References a, FP32_BITS, FP32_EXP_BIAS, fp32_round(), fp32_zero(), FP64_BITS, fp64_normalise(), and ULL.
Referenced by fplibFixedToFP().
fp32_defaultNaN()
static uint32_t ArmISA::fp32_defaultNaN () inline static
Definition at line 378 of file fplib.cc.
References FP32_EXP_INF, FP32_MANT_BITS, fp32_pack(), and ULL.
Referenced by fp32_add(), fp32_div(), fp32_mul(), fp32_muladd(), fp32_process_NaN(), fp32_sqrt(), fplibConvert(), fplibDefaultNaN(), and fplibRSqrtEstimate().
fp32_div()
static uint32_t ArmISA::fp32_div (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1804 of file fplib.cc.
References FP32_BITS, fp32_defaultNaN(), FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), FP32_MANT_BITS, fp32_normalise(), fp32_process_NaNs(), fp32_round(), fp32_unpack(), fp32_zero(), fp64_normalise(), FPLIB_DZC, FPLIB_IOC, and X86ISA::x.
Referenced by fplibDiv().
fp32_FPConvertNaN_16()
static uint32_t ArmISA::fp32_FPConvertNaN_16 (uint16_t op) static
Definition at line 2526 of file fplib.cc.
References FP16_BITS, FP16_MANT_BITS, FP32_EXP_INF, FP32_MANT_BITS, fp32_pack(), and ULL.
Referenced by fplibConvert().
fp32_FPConvertNaN_64()
static uint32_t ArmISA::fp32_FPConvertNaN_64 (uint64_t op) static
Definition at line 2534 of file fplib.cc.
References FP32_EXP_INF, FP32_MANT_BITS, fp32_pack(), FP64_BITS, FP64_MANT_BITS, and ULL.
Referenced by fplibConvert().
fp32_FPOnePointFive()
static uint32_t ArmISA::fp32_FPOnePointFive (int sgn) static
Definition at line 2564 of file fplib.cc.
References FP32_EXP_BIAS, FP32_MANT_BITS, fp32_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp32_FPThree()
static uint32_t ArmISA::fp32_FPThree (int sgn) static
Definition at line 2582 of file fplib.cc.
References FP32_EXP_BIAS, FP32_MANT_BITS, fp32_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp32_FPTwo()
static uint32_t ArmISA::fp32_FPTwo (int sgn) static
Definition at line 2600 of file fplib.cc.
References FP32_EXP_BIAS, and fp32_pack().
Referenced by fplibMulX(), and fplibRecipStepFused().
fp32_infinity()
static uint32_t ArmISA::fp32_infinity (int sgn) inline static
Definition at line 360 of file fplib.cc.
References FP32_EXP_INF, and fp32_pack().
Referenced by fp32_add(), fp32_div(), fp32_minmaxnum(), fp32_mul(), fp32_muladd(), fp32_round_(), fp32_scale(), fp32_sqrt(), fplibConvert(), fplibInfinity(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibRSqrtStepFused().
fp32_is_infinity()
static int ArmISA::fp32_is_infinity (int exp, uint32_t mnt) inline static
Definition at line 509 of file fplib.cc.
References FP32_EXP_INF, and FP32_MANT.
Referenced by fp32_muladd().
fp32_is_NaN()
static int ArmISA::fp32_is_NaN (int exp, uint32_t mnt) inline static
Definition at line 455 of file fplib.cc.
References FP32_EXP_INF, and FP32_MANT.
Referenced by fp32_compare_eq(), fp32_compare_ge(), fp32_compare_gt(), fp32_compare_un(), fp32_is_signalling_NaN(), fp32_process_NaNs(), fp32_process_NaNs3(), fp32_scale(), fp32_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibTrigSMul().
fp32_is_quiet_NaN()
static int ArmISA::fp32_is_quiet_NaN (int exp, uint32_t mnt) inline static
Definition at line 491 of file fplib.cc.
References FP32_EXP_INF, and FP32_MANT_BITS.
Referenced by fp32_muladd().
fp32_is_signalling_NaN()
static int ArmISA::fp32_is_signalling_NaN (int exp, uint32_t mnt) inline static
Definition at line 473 of file fplib.cc.
References fp32_is_NaN(), and FP32_MANT_BITS.
Referenced by fp32_compare_eq(), fp32_compare_un(), fp32_process_NaNs(), fp32_process_NaNs3(), and fplibCompare().
fp32_max_normal()
static uint32_t ArmISA::fp32_max_normal (int sgn) inline static
Definition at line 342 of file fplib.cc.
References FP32_EXP_INF, and fp32_pack().
Referenced by fp32_round_(), and fplibRecipEstimate().
fp32_minmaxnum()
static void ArmISA::fp32_minmaxnum (uint32_t * op1, uint32_t * op2, int sgn) static
Definition at line 3143 of file fplib.cc.
References fp32_infinity(), and FP32_MANT_BITS.
Referenced by fplibMaxNum(), and fplibMinNum().
fp32_mul()
static uint32_t ArmISA::fp32_mul (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 1426 of file fplib.cc.
References FP32_BITS, fp32_defaultNaN(), FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_process_NaNs(), fp32_round(), fp32_unpack(), fp32_zero(), fp64_normalise(), FPLIB_IOC, lsl64(), lsr64(), and X86ISA::x.
Referenced by fplibMul(), fplibMulX(), and fplibTrigSMul().
fp32_muladd()
static uint32_t ArmISA::fp32_muladd (uint32_t a, uint32_t b, uint32_t c, int scale, int mode, int * flags) static
Definition at line 1585 of file fplib.cc.
References FP32_BITS, fp32_defaultNaN(), FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_is_infinity(), fp32_is_quiet_NaN(), FP32_MANT_BITS, fp32_process_NaNs3(), fp32_round(), fp32_unpack(), fp32_zero(), fp64_normalise(), FPLIB_IOC, lsl64(), lsr64(), and X86ISA::x.
Referenced by fplibMulAdd(), fplibRecipStepFused(), fplibRSqrtStepFused(), and fplibTrigMulAdd().
fp32_normalise()
static uint32_t ArmISA::fp32_normalise (uint32_t mnt, int * exp) inline static
Definition at line 235 of file fplib.cc.
References shift.
Referenced by fp16_div(), fp16_mul(), fp16_muladd(), fp32_add(), fp32_div(), fp32_scale(), fp32_sqrt(), fplibConvert(), fplibRecipEstimate(), fplibRoundInt(), and fplibRSqrtEstimate().
fp32_pack()
static uint32_t ArmISA::fp32_pack (uint32_t sgn, uint32_t exp, uint32_t mnt) inline static
Definition at line 306 of file fplib.cc.
References FP32_BITS, FP32_MANT, and FP32_MANT_BITS.
Referenced by fp32_defaultNaN(), fp32_FPConvertNaN_16(), fp32_FPConvertNaN_64(), fp32_FPOnePointFive(), fp32_FPThree(), fp32_FPTwo(), fp32_infinity(), fp32_max_normal(), fp32_repack(), fp32_round_(), fp32_zero(), fplibConvert(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp32_process_NaN()
static uint32_t ArmISA::fp32_process_NaN (uint32_t a, int mode, int * flags) inline static
Definition at line 531 of file fplib.cc.
References a, fp32_defaultNaN(), FP32_MANT_BITS, FPLIB_DN, FPLIB_IOC, and ULL.
Referenced by fp32_process_NaNs(), fp32_process_NaNs3(), fp32_scale(), fp32_sqrt(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp32_process_NaNs()
static uint32_t ArmISA::fp32_process_NaNs (uint32_t a, uint32_t b, int mode, int * flags) static
Definition at line 574 of file fplib.cc.
References FP32_EXP, fp32_is_NaN(), fp32_is_signalling_NaN(), FP32_MANT, and fp32_process_NaN().
Referenced by fp32_add(), fp32_div(), fp32_mul(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipStepFused(), and fplibRSqrtStepFused().
fp32_process_NaNs3()
static uint32_t ArmISA::fp32_process_NaNs3 (uint32_t a, uint32_t b, uint32_t c, int mode, int * flags) static
Definition at line 649 of file fplib.cc.
References FP32_EXP, fp32_is_NaN(), fp32_is_signalling_NaN(), FP32_MANT, and fp32_process_NaN().
Referenced by fp32_muladd().
fp32_repack()
static uint32_t ArmISA::fp32_repack (int sgn, int exp, uint32_t mnt) static
Definition at line 3119 of file fplib.cc.
References FP32_MANT_BITS, and fp32_pack().
Referenced by fplibMax(), and fplibMin().
fp32_round()
static uint32_t ArmISA::fp32_round (int sgn, int exp, uint32_t mnt, int mode, int * flags) static
Definition at line 862 of file fplib.cc.
References fp32_round_().
Referenced by fp32_add(), fp32_cvtf(), fp32_div(), fp32_mul(), fp32_muladd(), fp32_scale(), and fp32_sqrt().
fp32_round_()
static uint32_t ArmISA::fp32_round_ (int sgn, int exp, uint32_t mnt, int rm, int mode, int * flags) static
Definition at line 791 of file fplib.cc.
References FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), FP32_MANT_BITS, fp32_max_normal(), fp32_pack(), fp32_zero(), FPLIB_FZ, FPLIB_IXC, FPLIB_OFC, FPLIB_RM, FPLIB_RN, FPLIB_RP, FPLIB_UFC, FPRounding_ODD, FPRounding_TIEAWAY, lsl32(), lsr32(), and ULL.
Referenced by fp32_round(), and fplibConvert().
fp32_scale()
static uint32_t ArmISA::fp32_scale (uint32_t a, int32_t b, int mode, int * flags) static
Definition at line 1958 of file fplib.cc.
References b, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_is_NaN(), fp32_normalise(), fp32_process_NaN(), fp32_round(), fp32_unpack(), and fp32_zero().
Referenced by fplibScale().
fp32_sqrt()
static uint32_t ArmISA::fp32_sqrt (uint32_t a, int mode, int * flags) static
Definition at line 2078 of file fplib.cc.
References fp32_defaultNaN(), FP32_EXP_INF, fp32_infinity(), fp32_is_NaN(), fp32_normalise(), fp32_process_NaN(), fp32_round(), fp32_unpack(), fp32_zero(), FPLIB_IOC, t0, t1, and X86ISA::x.
Referenced by fplibSqrt().
fp32_unpack()
static void ArmISA::fp32_unpack (int * sgn, int * exp, uint32_t * mnt, uint32_t x, int mode, int * flags) inline static
Definition at line 409 of file fplib.cc.
References FP32_BITS, FP32_EXP, FP32_MANT, FP32_MANT_BITS, FPLIB_FZ, FPLIB_IDC, and ULL.
Referenced by fp32_add(), fp32_compare_eq(), fp32_compare_ge(), fp32_compare_gt(), fp32_compare_un(), fp32_div(), fp32_mul(), fp32_muladd(), fp32_scale(), fp32_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), and fplibTrigSMul().
fp32_zero()
static uint32_t ArmISA::fp32_zero (int sgn) inline static
Definition at line 324 of file fplib.cc.
References fp32_pack().
Referenced by fp32_add(), fp32_cvtf(), fp32_div(), fp32_mul(), fp32_muladd(), fp32_round_(), fp32_scale(), fp32_sqrt(), fplibConvert(), fplibMulX(), fplibRecipEstimate(), fplibRoundInt(), and fplibRSqrtEstimate().
fp64_add()
static uint64_t ArmISA::fp64_add (uint64_t a, uint64_t b, int neg, int mode, int * flags) static
Definition at line 1329 of file fplib.cc.
References fp64_defaultNaN(), FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_normalise(), fp64_process_NaNs(), fp64_round(), fp64_unpack(), fp64_zero(), FPLIB_IOC, lsl64(), lsr64(), sc_dt::neg(), and X86ISA::x.
Referenced by fplibAdd(), and fplibSub().
fp64_compare_eq()
static int ArmISA::fp64_compare_eq (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1121 of file fplib.cc.
References fp64_is_NaN(), fp64_is_signalling_NaN(), fp64_unpack(), and FPLIB_IOC.
Referenced by fplibCompareEQ().
fp64_compare_ge()
static int ArmISA::fp64_compare_ge (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1140 of file fplib.cc.
References fp64_is_NaN(), fp64_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGE().
fp64_compare_gt()
static int ArmISA::fp64_compare_gt (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1165 of file fplib.cc.
References fp64_is_NaN(), fp64_unpack(), and FPLIB_IOC.
Referenced by fplibCompareGT().
fp64_compare_un()
static int ArmISA::fp64_compare_un (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1190 of file fplib.cc.
References fp64_is_NaN(), fp64_is_signalling_NaN(), fp64_unpack(), and FPLIB_IOC.
Referenced by fplibCompareUN().
fp64_cvtf()
static uint64_t ArmISA::fp64_cvtf (uint64_t a, int fbits, int u, int mode, int * flags) static
Definition at line 4869 of file fplib.cc.
References a, FP64_BITS, FP64_EXP_BIAS, fp64_normalise(), fp64_round(), and fp64_zero().
Referenced by fplibFixedToFP().
fp64_defaultNaN()
static uint64_t ArmISA::fp64_defaultNaN () inline static
Definition at line 384 of file fplib.cc.
References FP64_EXP_INF, FP64_MANT_BITS, fp64_pack(), and ULL.
Referenced by fp64_add(), fp64_div(), fp64_mul(), fp64_muladd(), fp64_process_NaN(), fp64_sqrt(), fplibConvert(), fplibDefaultNaN(), and fplibRSqrtEstimate().
fp64_div()
static uint64_t ArmISA::fp64_div (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1846 of file fplib.cc.
References c, cmp128(), fp64_defaultNaN(), FP64_EXP_BIAS, FP64_EXP_INF, fp64_infinity(), fp64_normalise(), fp64_process_NaNs(), fp64_round(), fp64_unpack(), fp64_zero(), FPLIB_DZC, FPLIB_IOC, lsr128(), mul62x62(), mul64x32(), sub128(), and X86ISA::x.
Referenced by fplibDiv().
fp64_FPConvertNaN_16()
static uint64_t ArmISA::fp64_FPConvertNaN_16 (uint16_t op) static
Definition at line 2542 of file fplib.cc.
References FP16_BITS, FP16_MANT_BITS, FP64_EXP_INF, FP64_MANT_BITS, fp64_pack(), and ULL.
Referenced by fplibConvert().
fp64_FPConvertNaN_32()
static uint64_t ArmISA::fp64_FPConvertNaN_32 (uint32_t op) static
Definition at line 2550 of file fplib.cc.
References FP32_BITS, FP32_MANT_BITS, FP64_EXP_INF, FP64_MANT_BITS, fp64_pack(), and ULL.
Referenced by fplibConvert().
fp64_FPOnePointFive()
static uint64_t ArmISA::fp64_FPOnePointFive (int sgn) static
Definition at line 2570 of file fplib.cc.
References FP64_EXP_BIAS, FP64_MANT_BITS, fp64_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp64_FPThree()
static uint64_t ArmISA::fp64_FPThree (int sgn) static
Definition at line 2588 of file fplib.cc.
References FP64_EXP_BIAS, FP64_MANT_BITS, fp64_pack(), and ULL.
Referenced by fplibRSqrtStepFused().
fp64_FPTwo()
static uint64_t ArmISA::fp64_FPTwo (int sgn) static
Definition at line 2606 of file fplib.cc.
References FP64_EXP_BIAS, and fp64_pack().
Referenced by fplibMulX(), and fplibRecipStepFused().
fp64_infinity()
static uint64_t ArmISA::fp64_infinity (int sgn) inline static
Definition at line 366 of file fplib.cc.
References FP64_EXP_INF, and fp64_pack().
Referenced by fp64_add(), fp64_div(), fp64_minmaxnum(), fp64_mul(), fp64_muladd(), fp64_round_(), fp64_scale(), fp64_sqrt(), fplibConvert(), fplibInfinity(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibRSqrtStepFused().
fp64_is_infinity()
static int ArmISA::fp64_is_infinity (int exp, uint64_t mnt) inline static
Definition at line 515 of file fplib.cc.
References FP64_EXP_INF, and FP64_MANT.
Referenced by fp64_muladd().
fp64_is_NaN()
static int ArmISA::fp64_is_NaN (int exp, uint64_t mnt) inline static
Definition at line 461 of file fplib.cc.
References FP64_EXP_INF, and FP64_MANT.
Referenced by fp64_compare_eq(), fp64_compare_ge(), fp64_compare_gt(), fp64_compare_un(), fp64_is_signalling_NaN(), fp64_process_NaNs(), fp64_process_NaNs3(), fp64_scale(), fp64_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), and fplibTrigSMul().
fp64_is_quiet_NaN()
static int ArmISA::fp64_is_quiet_NaN (int exp, uint64_t mnt) inline static
Definition at line 497 of file fplib.cc.
References FP64_EXP_INF, and FP64_MANT_BITS.
Referenced by fp64_muladd().
fp64_is_signalling_NaN()
static int ArmISA::fp64_is_signalling_NaN (int exp, uint64_t mnt) inline static
Definition at line 479 of file fplib.cc.
References fp64_is_NaN(), and FP64_MANT_BITS.
Referenced by fp64_compare_eq(), fp64_compare_un(), fp64_process_NaNs(), fp64_process_NaNs3(), and fplibCompare().
fp64_max_normal()
static uint64_t ArmISA::fp64_max_normal (int sgn) inline static
Definition at line 348 of file fplib.cc.
References FP64_EXP_INF, and fp64_pack().
Referenced by fp64_round_(), and fplibRecipEstimate().
fp64_minmaxnum()
static void ArmISA::fp64_minmaxnum (uint64_t * op1, uint64_t * op2, int sgn) static
Definition at line 3155 of file fplib.cc.
References fp64_infinity(), and FP64_MANT_BITS.
Referenced by fplibMaxNum(), and fplibMinNum().
fp64_mul()
static uint64_t ArmISA::fp64_mul (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 1463 of file fplib.cc.
References fp128_normalise(), fp64_defaultNaN(), FP64_EXP_BIAS, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_process_NaNs(), fp64_round(), fp64_unpack(), fp64_zero(), FPLIB_IOC, mul62x62(), and X86ISA::x.
Referenced by fplibMul(), fplibMulX(), and fplibTrigSMul().
fp64_muladd()
static uint64_t ArmISA::fp64_muladd (uint64_t a, uint64_t b, uint64_t c, int scale, int mode, int * flags) static
Definition at line 1670 of file fplib.cc.
References add128(), cmp128(), fp128_normalise(), fp64_defaultNaN(), FP64_EXP_BIAS, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_is_infinity(), fp64_is_quiet_NaN(), fp64_process_NaNs3(), fp64_round(), fp64_unpack(), fp64_zero(), FPLIB_IOC, lsl128(), lsr128(), mul62x62(), sub128(), t0, t1, and X86ISA::x.
Referenced by fplibMulAdd(), fplibRecipStepFused(), fplibRSqrtStepFused(), and fplibTrigMulAdd().
fp64_normalise()
static uint64_t ArmISA::fp64_normalise (uint64_t mnt, int * exp) inline static
Definition at line 253 of file fplib.cc.
References shift.
Referenced by fp16_cvtf(), fp32_cvtf(), fp32_div(), fp32_mul(), fp32_muladd(), fp64_add(), fp64_cvtf(), fp64_div(), fp64_scale(), fp64_sqrt(), fplibRecipEstimate(), fplibRoundInt(), and fplibRSqrtEstimate().
fp64_pack()
static uint64_t ArmISA::fp64_pack (uint64_t sgn, uint64_t exp, uint64_t mnt) inline static
Definition at line 312 of file fplib.cc.
References FP64_BITS, FP64_MANT, and FP64_MANT_BITS.
Referenced by fp64_defaultNaN(), fp64_FPConvertNaN_16(), fp64_FPConvertNaN_32(), fp64_FPOnePointFive(), fp64_FPThree(), fp64_FPTwo(), fp64_infinity(), fp64_max_normal(), fp64_repack(), fp64_round_(), fp64_zero(), fplibConvert(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp64_process_NaN()
static uint64_t ArmISA::fp64_process_NaN (uint64_t a, int mode, int * flags) inline static
Definition at line 541 of file fplib.cc.
References a, fp64_defaultNaN(), FP64_MANT_BITS, FPLIB_DN, FPLIB_IOC, and ULL.
Referenced by fp64_process_NaNs(), fp64_process_NaNs3(), fp64_scale(), fp64_sqrt(), fplibRecipEstimate(), fplibRecpX(), fplibRoundInt(), and fplibRSqrtEstimate().
fp64_process_NaNs()
static uint64_t ArmISA::fp64_process_NaNs (uint64_t a, uint64_t b, int mode, int * flags) static
Definition at line 597 of file fplib.cc.
References FP64_EXP, fp64_is_NaN(), fp64_is_signalling_NaN(), FP64_MANT, and fp64_process_NaN().
Referenced by fp64_add(), fp64_div(), fp64_mul(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipStepFused(), and fplibRSqrtStepFused().
fp64_process_NaNs3()
static uint64_t ArmISA::fp64_process_NaNs3 (uint64_t a, uint64_t b, uint64_t c, int mode, int * flags) static
Definition at line 678 of file fplib.cc.
References FP64_EXP, fp64_is_NaN(), fp64_is_signalling_NaN(), FP64_MANT, and fp64_process_NaN().
Referenced by fp64_muladd().
fp64_repack()
static uint64_t ArmISA::fp64_repack (int sgn, int exp, uint64_t mnt) static
Definition at line 3125 of file fplib.cc.
References FP64_MANT_BITS, and fp64_pack().
Referenced by fplibMax(), and fplibMin().
fp64_round()
static uint64_t ArmISA::fp64_round (int sgn, int exp, uint64_t mnt, int mode, int * flags) static
Definition at line 939 of file fplib.cc.
References fp64_round_().
Referenced by fp64_add(), fp64_cvtf(), fp64_div(), fp64_mul(), fp64_muladd(), fp64_scale(), and fp64_sqrt().
fp64_round_()
static uint64_t ArmISA::fp64_round_ (int sgn, int exp, uint64_t mnt, int rm, int mode, int * flags) static
Definition at line 868 of file fplib.cc.
References FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), FP64_MANT_BITS, fp64_max_normal(), fp64_pack(), fp64_zero(), FPLIB_FZ, FPLIB_IXC, FPLIB_OFC, FPLIB_RM, FPLIB_RN, FPLIB_RP, FPLIB_UFC, FPRounding_ODD, FPRounding_TIEAWAY, lsl64(), lsr64(), and ULL.
Referenced by fp64_round().
fp64_scale()
static uint64_t ArmISA::fp64_scale (uint64_t a, int64_t b, int mode, int * flags) static
Definition at line 1992 of file fplib.cc.
References b, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_is_NaN(), fp64_normalise(), fp64_process_NaN(), fp64_round(), fp64_unpack(), and fp64_zero().
Referenced by fplibScale().
fp64_sqrt()
static uint64_t ArmISA::fp64_sqrt (uint64_t a, int mode, int * flags) static
Definition at line 2133 of file fplib.cc.
References c, cmp128(), fp64_defaultNaN(), FP64_EXP_INF, fp64_infinity(), fp64_is_NaN(), fp64_normalise(), fp64_process_NaN(), fp64_round(), fp64_unpack(), fp64_zero(), FPLIB_IOC, lsl128(), lsr128(), mul62x62(), mul64x32(), MipsISA::r, and X86ISA::x.
Referenced by fplibSqrt().
fp64_unpack()
static void ArmISA::fp64_unpack (int * sgn, int * exp, uint64_t * mnt, uint64_t x, int mode, int * flags) inline static
Definition at line 429 of file fplib.cc.
References FP64_BITS, FP64_EXP, FP64_MANT, FP64_MANT_BITS, FPLIB_FZ, FPLIB_IDC, and ULL.
Referenced by fp64_add(), fp64_compare_eq(), fp64_compare_ge(), fp64_compare_gt(), fp64_compare_un(), fp64_div(), fp64_mul(), fp64_muladd(), fp64_scale(), fp64_sqrt(), fplibCompare(), fplibConvert(), fplibFPToFixed(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), and fplibTrigSMul().
fp64_zero()
static uint64_t ArmISA::fp64_zero (int sgn) inline static
Definition at line 330 of file fplib.cc.
References fp64_pack().
Referenced by fp64_add(), fp64_cvtf(), fp64_div(), fp64_mul(), fp64_muladd(), fp64_round_(), fp64_scale(), fp64_sqrt(), fplibConvert(), fplibMulX(), fplibRecipEstimate(), and fplibRoundInt().
fpAdd()
template<typename T > static T ArmISA::fpAdd (T a, T b) inline static
Definition at line 478 of file vfp.hh.
References b.
fpAddD()
static double ArmISA::fpAddD (double a, double b) inline static
Definition at line 497 of file vfp.hh.
References b.
fpAddS()
static float ArmISA::fpAddS (float a, float b) inline static
Definition at line 491 of file vfp.hh.
References b.
FPCRRounding()
static FPRounding ArmISA::FPCRRounding (FPSCR & fpscr) inline static
Definition at line 69 of file fplib.hh.
References fplibAbs(), fplibAdd(), fplibCompare(), fplibCompareEQ(), fplibCompareGE(), fplibCompareGT(), fplibCompareUN(), fplibConvert(), fplibDefaultNaN(), fplibDiv(), fplibExpA(), fplibFixedToFP(), fplibFPToFixed(), fplibInfinity(), fplibMax(), fplibMaxNum(), fplibMin(), fplibMinNum(), fplibMul(), fplibMulAdd(), fplibMulX(), fplibNeg(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), fplibScale(), fplibSqrt(), fplibSub(), fplibTrigMulAdd(), fplibTrigSMul(), fplibTrigSSel(), X86ISA::op, and u.
Referenced by fplibRecipEstimate().
fpDiv()
template<typename T > static T ArmISA::fpDiv (T a, T b) inline static
Definition at line 528 of file vfp.hh.
References b.
fpDivD()
static double ArmISA::fpDivD (double a, double b) inline static
Definition at line 521 of file vfp.hh.
References b.
fpDivS()
static float ArmISA::fpDivS (float a, float b) inline static
Definition at line 515 of file vfp.hh.
References b.
fplibAbs() [1/4]
template<class T > T ArmISA::fplibAbs (T op)
Floating-point absolute value.
fplibAbs() [2/4]
template<> uint16_t ArmISA::fplibAbs (uint16_t op)
Definition at line 2358 of file fplib.cc.
References FP16_BITS, and ULL.
Referenced by FPCRRounding(), and fplibTrigMulAdd().
fplibAbs() [3/4]
template<> uint32_t ArmISA::fplibAbs (uint32_t op)
Definition at line 2365 of file fplib.cc.
References FP32_BITS, and ULL.
fplibAbs() [4/4]
template<> uint64_t ArmISA::fplibAbs (uint64_t op)
Definition at line 2372 of file fplib.cc.
References FP64_BITS, and ULL.
fplibAdd() [1/4]
template<class T > T ArmISA::fplibAdd (T op1, T op2, FPSCR & fpscr)
Floating-point add.
fplibAdd() [2/4]
template<> uint16_t ArmISA::fplibAdd (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 2379 of file fplib.cc.
References fp16_add(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibAdd() [3/4]
template<> uint32_t ArmISA::fplibAdd (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 2389 of file fplib.cc.
References fp32_add(), modeConv(), and set_fpscr0().
fplibAdd() [4/4]
template<> uint64_t ArmISA::fplibAdd (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 2399 of file fplib.cc.
References fp64_add(), modeConv(), and set_fpscr0().
fplibCompare() [1/4]
template<class T > int ArmISA::fplibCompare (T op1, T op2, bool signal_nans, FPSCR & fpscr)
Floating-point compare (quiet and signaling).
fplibCompare() [2/4]
template<> int ArmISA::fplibCompare (uint16_t op1, uint16_t op2, bool signal_nans, FPSCR & fpscr)
Definition at line 2409 of file fplib.cc.
References fp16_is_NaN(), fp16_is_signalling_NaN(), fp16_unpack(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibCompare() [3/4]
template<> int ArmISA::fplibCompare (uint32_t op1, uint32_t op2, bool signal_nans, FPSCR & fpscr)
Definition at line 2443 of file fplib.cc.
References fp32_is_NaN(), fp32_is_signalling_NaN(), fp32_unpack(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibCompare() [4/4]
template<> int ArmISA::fplibCompare (uint64_t op1, uint64_t op2, bool signal_nans, FPSCR & fpscr)
Definition at line 2477 of file fplib.cc.
References fp64_is_NaN(), fp64_is_signalling_NaN(), fp64_unpack(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibCompareEQ() [1/4]
template<class T > bool ArmISA::fplibCompareEQ (T op1, T op2, FPSCR & fpscr)
Floating-point compare equal.
fplibCompareEQ() [2/4]
template<> bool ArmISA::fplibCompareEQ (uint16_t a, uint16_t b, FPSCR & fpscr)
Definition at line 2238 of file fplib.cc.
References fp16_compare_eq(), modeConv(), set_fpscr(), and X86ISA::x.
Referenced by FPCRRounding().
fplibCompareEQ() [3/4]
template<> bool ArmISA::fplibCompareEQ (uint32_t a, uint32_t b, FPSCR & fpscr)
Definition at line 2278 of file fplib.cc.
References fp32_compare_eq(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareEQ() [4/4]
template<> bool ArmISA::fplibCompareEQ (uint64_t a, uint64_t b, FPSCR & fpscr)
Definition at line 2318 of file fplib.cc.
References fp64_compare_eq(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareGE() [1/4]
template<class T > bool ArmISA::fplibCompareGE (T op1, T op2, FPSCR & fpscr)
Floating-point compare greater than or equal.
fplibCompareGE() [2/4]
template<> bool ArmISA::fplibCompareGE (uint16_t a, uint16_t b, FPSCR & fpscr)
Definition at line 2248 of file fplib.cc.
References fp16_compare_ge(), modeConv(), set_fpscr(), and X86ISA::x.
Referenced by FPCRRounding().
fplibCompareGE() [3/4]
template<> bool ArmISA::fplibCompareGE (uint32_t a, uint32_t b, FPSCR & fpscr)
Definition at line 2288 of file fplib.cc.
References fp32_compare_ge(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareGE() [4/4]
template<> bool ArmISA::fplibCompareGE (uint64_t a, uint64_t b, FPSCR & fpscr)
Definition at line 2328 of file fplib.cc.
References fp64_compare_ge(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareGT() [1/4]
template<class T > bool ArmISA::fplibCompareGT (T op1, T op2, FPSCR & fpscr)
Floating-point compare greater than.
fplibCompareGT() [2/4]
template<> bool ArmISA::fplibCompareGT (uint16_t a, uint16_t b, FPSCR & fpscr)
Definition at line 2258 of file fplib.cc.
References fp16_compare_gt(), modeConv(), set_fpscr(), and X86ISA::x.
Referenced by FPCRRounding().
fplibCompareGT() [3/4]
template<> bool ArmISA::fplibCompareGT (uint32_t a, uint32_t b, FPSCR & fpscr)
Definition at line 2298 of file fplib.cc.
References fp32_compare_gt(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareGT() [4/4]
template<> bool ArmISA::fplibCompareGT (uint64_t a, uint64_t b, FPSCR & fpscr)
Definition at line 2338 of file fplib.cc.
References fp64_compare_gt(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareUN() [1/4]
template<class T > bool ArmISA::fplibCompareUN (T op1, T op2, FPSCR & fpscr)
Floating-point compare unordered.
fplibCompareUN() [2/4]
template<> bool ArmISA::fplibCompareUN (uint16_t a, uint16_t b, FPSCR & fpscr)
Definition at line 2268 of file fplib.cc.
References fp16_compare_un(), modeConv(), set_fpscr(), and X86ISA::x.
Referenced by FPCRRounding().
fplibCompareUN() [3/4]
template<> bool ArmISA::fplibCompareUN (uint32_t a, uint32_t b, FPSCR & fpscr)
Definition at line 2308 of file fplib.cc.
References fp32_compare_un(), modeConv(), set_fpscr(), and X86ISA::x.
fplibCompareUN() [4/4]
template<> bool ArmISA::fplibCompareUN (uint64_t a, uint64_t b, FPSCR & fpscr)
Definition at line 2348 of file fplib.cc.
References fp64_compare_un(), modeConv(), set_fpscr(), and X86ISA::x.
fplibConvert() [1/7]
template<class T1 , class T2 > T2 ArmISA::fplibConvert (T1 op, FPRounding rounding, FPSCR & fpscr)
Floating-point convert precision.
fplibConvert() [2/7]
template<> uint16_t ArmISA::fplibConvert (uint32_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2613 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, fp16_FPConvertNaN_32(), fp16_infinity(), fp16_round_(), fp16_zero(), FP32_EXP_BIAS, FP32_EXP_INF, fp32_is_NaN(), FP32_MANT_BITS, fp32_unpack(), FPLIB_IOC, mode, modeConv(), set_fpscr0(), and ULL.
Referenced by FPCRRounding().
fplibConvert() [3/7]
template<> uint16_t ArmISA::fplibConvert (uint64_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2662 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, fp16_FPConvertNaN_64(), fp16_infinity(), fp16_round_(), fp16_zero(), FP64_EXP_BIAS, FP64_EXP_INF, fp64_is_NaN(), FP64_MANT_BITS, fp64_unpack(), FPLIB_IOC, mode, modeConv(), set_fpscr0(), and ULL.
fplibConvert() [4/7]
template<> uint32_t ArmISA::fplibConvert (uint16_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2711 of file fplib.cc.
References FP16_BITS, FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_is_NaN(), FP16_MANT_BITS, fp16_normalise(), fp16_unpack(), fp32_defaultNaN(), FP32_EXP_BIAS, fp32_FPConvertNaN_16(), fp32_infinity(), FP32_MANT_BITS, fp32_pack(), fp32_zero(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibConvert() [5/7]
template<> uint32_t ArmISA::fplibConvert (uint64_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2749 of file fplib.cc.
References FP32_BITS, fp32_defaultNaN(), FP32_EXP_BIAS, fp32_FPConvertNaN_64(), fp32_infinity(), fp32_round_(), fp32_zero(), FP64_EXP_BIAS, FP64_EXP_INF, fp64_is_NaN(), FP64_MANT_BITS, fp64_unpack(), FPLIB_IOC, mode, modeConv(), set_fpscr0(), and ULL.
fplibConvert() [6/7]
template<> uint64_t ArmISA::fplibConvert (uint16_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2788 of file fplib.cc.
References FP16_BITS, FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_is_NaN(), FP16_MANT_BITS, fp16_normalise(), fp16_unpack(), fp64_defaultNaN(), FP64_EXP_BIAS, fp64_FPConvertNaN_16(), fp64_infinity(), FP64_MANT_BITS, fp64_pack(), fp64_zero(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibConvert() [7/7]
template<> uint64_t ArmISA::fplibConvert (uint32_t op, FPRounding rounding, FPSCR & fpscr)
Definition at line 2826 of file fplib.cc.
References FP32_BITS, FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_is_NaN(), FP32_MANT_BITS, fp32_normalise(), fp32_unpack(), fp64_defaultNaN(), FP64_EXP_BIAS, fp64_FPConvertNaN_32(), fp64_infinity(), FP64_MANT_BITS, fp64_pack(), fp64_zero(), FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibDefaultNaN() [1/4]
template<class T > T ArmISA::fplibDefaultNaN ()
Foating-point value for default NaN.
Definition at line 4945 of file fplib.cc.
References fp16_defaultNaN(), fp32_defaultNaN(), and fp64_defaultNaN().
Referenced by FPCRRounding().
fplibDefaultNaN() [2/4]
template<> uint16_t ArmISA::fplibDefaultNaN ()
Foating-point value for default NaN.
Definition at line 4945 of file fplib.cc.
Referenced by FPCRRounding().
fplibDefaultNaN() [3/4]
template<> uint32_t ArmISA::fplibDefaultNaN ()
Foating-point value for default NaN.
Definition at line 4952 of file fplib.cc.
References fp32_defaultNaN().
fplibDefaultNaN() [4/4]
template<> uint64_t ArmISA::fplibDefaultNaN ()
Foating-point value for default NaN.
Definition at line 4959 of file fplib.cc.
References fp16_defaultNaN(), and fp64_defaultNaN().
fplibDiv() [1/4]
template<class T > T ArmISA::fplibDiv (T op1, T op2, FPSCR & fpscr)
Floating-point division.
fplibDiv() [2/4]
template<> uint16_t ArmISA::fplibDiv (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 2894 of file fplib.cc.
References fp16_div(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibDiv() [3/4]
template<> uint32_t ArmISA::fplibDiv (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 2904 of file fplib.cc.
References fp32_div(), modeConv(), and set_fpscr0().
fplibDiv() [4/4]
template<> uint64_t ArmISA::fplibDiv (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 2914 of file fplib.cc.
References fp64_div(), modeConv(), and set_fpscr0().
fplibExpA() [1/4]
template<class T > T ArmISA::fplibExpA (T op)
Floating-point exponential accelerator.
fplibExpA() [2/4]
template<> uint16_t ArmISA::fplibExpA (uint16_t op)
Definition at line 2924 of file fplib.cc.
References FP16_EXP_BITS, and FP16_MANT_BITS.
Referenced by FPCRRounding().
fplibExpA() [3/4]
template<> uint32_t ArmISA::fplibExpA (uint32_t op)
Definition at line 2966 of file fplib.cc.
References FP32_EXP_BITS, and FP32_MANT_BITS.
fplibExpA() [4/4]
template<> uint64_t ArmISA::fplibExpA (uint64_t op)
Definition at line 3040 of file fplib.cc.
References FP64_EXP_BITS, FP64_MANT_BITS, and ULL.
fplibFixedToFP() [1/4]
template<class T > T ArmISA::fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Floating-point convert from fixed-point.
Definition at line 4887 of file fplib.cc.
References fp16_cvtf(), fp32_cvtf(), fp64_cvtf(), and set_fpscr0().
Referenced by FPCRRounding().
fplibFixedToFP() [2/4]
template<> uint16_t ArmISA::fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Floating-point convert from fixed-point.
Definition at line 4887 of file fplib.cc.
Referenced by FPCRRounding().
fplibFixedToFP() [3/4]
template<> uint32_t ArmISA::fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Floating-point convert from fixed-point.
Definition at line 4900 of file fplib.cc.
References fp32_cvtf(), and set_fpscr0().
fplibFixedToFP() [4/4]
template<> uint64_t ArmISA::fplibFixedToFP (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Floating-point convert from fixed-point.
Definition at line 4912 of file fplib.cc.
References fp16_cvtf(), fp64_cvtf(), and set_fpscr0().
fplibFPToFixed() [1/8]
template<class T1 , class T2 > T2 ArmISA::fplibFPToFixed (T1 op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Floating-point convert to fixed-point.
fplibFPToFixed() [2/8]
template<> uint16_t ArmISA::fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4624 of file fplib.cc.
References FP16_EXP_BIAS, fp16_is_NaN(), FP16_MANT_BITS, fp16_unpack(), FP64_EXP_BIAS, FP64_MANT_BITS, FPLIB_IOC, FPToFixed_16(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibFPToFixed() [3/8]
template<> uint32_t ArmISA::fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4654 of file fplib.cc.
References FP16_EXP_BIAS, FP16_EXP_INF, fp16_is_NaN(), FP16_MANT_BITS, fp16_unpack(), FP64_EXP_BIAS, FP64_MANT_BITS, FPLIB_IOC, FPToFixed_32(), modeConv(), and set_fpscr0().
fplibFPToFixed() [4/8]
template<> uint32_t ArmISA::fplibFPToFixed (uint32_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4686 of file fplib.cc.
References FP32_EXP_BIAS, fp32_is_NaN(), FP32_MANT_BITS, fp32_unpack(), FP64_EXP_BIAS, FP64_MANT_BITS, FPLIB_IOC, FPToFixed_32(), modeConv(), and set_fpscr0().
fplibFPToFixed() [5/8]
template<> uint32_t ArmISA::fplibFPToFixed (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4715 of file fplib.cc.
References fp64_is_NaN(), fp64_unpack(), FPLIB_IOC, FPToFixed_32(), modeConv(), and set_fpscr0().
fplibFPToFixed() [6/8]
template<> uint64_t ArmISA::fplibFPToFixed (uint16_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4742 of file fplib.cc.
References FP16_EXP_BIAS, FP16_EXP_INF, fp16_is_NaN(), FP16_MANT_BITS, fp16_unpack(), FP64_EXP_BIAS, FP64_MANT_BITS, FPLIB_IOC, FPToFixed_64(), modeConv(), and set_fpscr0().
fplibFPToFixed() [7/8]
template<> uint64_t ArmISA::fplibFPToFixed (uint32_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4774 of file fplib.cc.
References FP32_EXP_BIAS, fp32_is_NaN(), FP32_MANT_BITS, fp32_unpack(), FP64_EXP_BIAS, FP64_MANT_BITS, FPLIB_IOC, FPToFixed_64(), modeConv(), and set_fpscr0().
fplibFPToFixed() [8/8]
template<> uint64_t ArmISA::fplibFPToFixed (uint64_t op, int fbits, bool u, FPRounding rounding, FPSCR & fpscr)
Definition at line 4804 of file fplib.cc.
References fp64_is_NaN(), fp64_unpack(), FPLIB_IOC, FPToFixed_64(), modeConv(), and set_fpscr0().
fplibInfinity() [1/4]
template<class T > T ArmISA::fplibInfinity (int sgn)
Floating-point value for +/- infinity.
Definition at line 4924 of file fplib.cc.
References fp16_infinity(), fp32_infinity(), and fp64_infinity().
Referenced by FPCRRounding().
fplibInfinity() [2/4]
template<> uint16_t ArmISA::fplibInfinity (int sgn)
Floating-point value for +/- infinity.
Definition at line 4924 of file fplib.cc.
Referenced by FPCRRounding().
fplibInfinity() [3/4]
template<> uint32_t ArmISA::fplibInfinity (int sgn)
Floating-point value for +/- infinity.
Definition at line 4931 of file fplib.cc.
References fp32_infinity().
fplibInfinity() [4/4]
template<> uint64_t ArmISA::fplibInfinity (int sgn)
Floating-point value for +/- infinity.
Definition at line 4938 of file fplib.cc.
References fp16_infinity(), and fp64_infinity().
fplibMax() [1/4]
template<class T > T ArmISA::fplibMax (T op1, T op2, FPSCR & fpscr)
Floating-point maximum.
fplibMax() [2/4]
template<> uint16_t ArmISA::fplibMax (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3168 of file fplib.cc.
References fp16_process_NaNs(), fp16_repack(), fp16_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
Referenced by FPCRRounding().
fplibMax() [3/4]
template<> uint32_t ArmISA::fplibMax (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3191 of file fplib.cc.
References fp32_process_NaNs(), fp32_repack(), fp32_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
fplibMax() [4/4]
template<> uint64_t ArmISA::fplibMax (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3214 of file fplib.cc.
References fp64_process_NaNs(), fp64_repack(), fp64_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
fplibMaxNum() [1/4]
template<class T > T ArmISA::fplibMaxNum (T op1, T op2, FPSCR & fpscr)
Floating-point maximum number.
fplibMaxNum() [2/4]
template<> uint16_t ArmISA::fplibMaxNum (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3237 of file fplib.cc.
References fp16_minmaxnum().
Referenced by FPCRRounding().
fplibMaxNum() [3/4]
template<> uint32_t ArmISA::fplibMaxNum (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3245 of file fplib.cc.
References fp32_minmaxnum().
fplibMaxNum() [4/4]
template<> uint64_t ArmISA::fplibMaxNum (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3253 of file fplib.cc.
References fp64_minmaxnum().
fplibMin() [1/4]
template<class T > T ArmISA::fplibMin (T op1, T op2, FPSCR & fpscr)
Floating-point minimum.
fplibMin() [2/4]
template<> uint16_t ArmISA::fplibMin (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3261 of file fplib.cc.
References fp16_process_NaNs(), fp16_repack(), fp16_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
Referenced by FPCRRounding().
fplibMin() [3/4]
template<> uint32_t ArmISA::fplibMin (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3284 of file fplib.cc.
References fp32_process_NaNs(), fp32_repack(), fp32_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
fplibMin() [4/4]
template<> uint64_t ArmISA::fplibMin (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3307 of file fplib.cc.
References fp64_process_NaNs(), fp64_repack(), fp64_unpack(), mode, modeConv(), set_fpscr0(), and X86ISA::x.
fplibMinNum() [1/4]
template<class T > T ArmISA::fplibMinNum (T op1, T op2, FPSCR & fpscr)
Floating-point minimum number.
fplibMinNum() [2/4]
template<> uint16_t ArmISA::fplibMinNum (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3330 of file fplib.cc.
References fp16_minmaxnum().
Referenced by FPCRRounding().
fplibMinNum() [3/4]
template<> uint32_t ArmISA::fplibMinNum (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3338 of file fplib.cc.
References fp32_minmaxnum().
fplibMinNum() [4/4]
template<> uint64_t ArmISA::fplibMinNum (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3346 of file fplib.cc.
References fp64_minmaxnum().
fplibMul() [1/4]
template<class T > T ArmISA::fplibMul (T op1, T op2, FPSCR & fpscr)
Floating-point multiply.
fplibMul() [2/4]
template<> uint16_t ArmISA::fplibMul (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3354 of file fplib.cc.
References fp16_mul(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibMul() [3/4]
template<> uint32_t ArmISA::fplibMul (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3364 of file fplib.cc.
References fp32_mul(), modeConv(), and set_fpscr0().
fplibMul() [4/4]
template<> uint64_t ArmISA::fplibMul (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3374 of file fplib.cc.
References fp64_mul(), modeConv(), and set_fpscr0().
fplibMulAdd() [1/4]
template<class T > T ArmISA::fplibMulAdd (T addend, T op1, T op2, FPSCR & fpscr)
Floating-point multiply-add.
fplibMulAdd() [2/4]
template<> uint16_t ArmISA::fplibMulAdd (uint16_t addend, uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 2864 of file fplib.cc.
References fp16_muladd(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibMulAdd() [3/4]
template<> uint32_t ArmISA::fplibMulAdd (uint32_t addend, uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 2874 of file fplib.cc.
References fp32_muladd(), modeConv(), and set_fpscr0().
fplibMulAdd() [4/4]
template<> uint64_t ArmISA::fplibMulAdd (uint64_t addend, uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 2884 of file fplib.cc.
References fp64_muladd(), modeConv(), and set_fpscr0().
fplibMulX() [1/4]
template<class T > T ArmISA::fplibMulX (T op1, T op2, FPSCR & fpscr)
Floating-point multiply extended.
fplibMulX() [2/4]
template<> uint16_t ArmISA::fplibMulX (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3384 of file fplib.cc.
References FP16_EXP_INF, fp16_FPTwo(), fp16_infinity(), fp16_mul(), fp16_process_NaNs(), fp16_unpack(), fp16_zero(), mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibMulX() [3/4]
template<> uint32_t ArmISA::fplibMulX (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3415 of file fplib.cc.
References FP32_EXP_INF, fp32_FPTwo(), fp32_infinity(), fp32_mul(), fp32_process_NaNs(), fp32_unpack(), fp32_zero(), mode, modeConv(), and set_fpscr0().
fplibMulX() [4/4]
template<> uint64_t ArmISA::fplibMulX (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3446 of file fplib.cc.
References FP64_EXP_INF, fp64_FPTwo(), fp64_infinity(), fp64_mul(), fp64_process_NaNs(), fp64_unpack(), fp64_zero(), mode, modeConv(), and set_fpscr0().
fplibNeg() [1/4]
template<class T > T ArmISA::fplibNeg (T op)
Floating-point negate.
fplibNeg() [2/4]
template<> uint16_t ArmISA::fplibNeg (uint16_t op)
Definition at line 3477 of file fplib.cc.
References FP16_BITS, and ULL.
Referenced by FPCRRounding().
fplibNeg() [3/4]
template<> uint32_t ArmISA::fplibNeg (uint32_t op)
Definition at line 3484 of file fplib.cc.
References FP32_BITS, and ULL.
fplibNeg() [4/4]
template<> uint64_t ArmISA::fplibNeg (uint64_t op)
Definition at line 3491 of file fplib.cc.
References FP64_BITS, and ULL.
fplibRecipEstimate() [1/4]
template<class T > T ArmISA::fplibRecipEstimate (T op, FPSCR & fpscr)
Floating-point reciprocal estimate.
fplibRecipEstimate() [2/4]
template<> uint16_t ArmISA::fplibRecipEstimate (uint16_t op, FPSCR & fpscr)
Definition at line 3712 of file fplib.cc.
References FP16_BITS, FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_is_NaN(), FP16_MANT_BITS, fp16_max_normal(), fp16_normalise(), fp16_pack(), fp16_process_NaN(), fp16_unpack(), fp16_zero(), FPCRRounding(), FPLIB_DZC, FPLIB_IXC, FPLIB_OFC, FPLIB_UFC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), panic, and set_fpscr0().
Referenced by FPCRRounding().
fplibRecipEstimate() [3/4]
template<> uint32_t ArmISA::fplibRecipEstimate (uint32_t op, FPSCR & fpscr)
Definition at line 3774 of file fplib.cc.
References FP32_BITS, FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_is_NaN(), FP32_MANT_BITS, fp32_max_normal(), fp32_normalise(), fp32_pack(), fp32_process_NaN(), fp32_unpack(), fp32_zero(), FPCRRounding(), FPLIB_DZC, FPLIB_IXC, FPLIB_OFC, FPLIB_UFC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), panic, and set_fpscr0().
fplibRecipEstimate() [4/4]
template<> uint64_t ArmISA::fplibRecipEstimate (uint64_t op, FPSCR & fpscr)
Definition at line 3836 of file fplib.cc.
References FP64_BITS, FP64_EXP_BIAS, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_is_NaN(), FP64_MANT_BITS, fp64_max_normal(), fp64_normalise(), fp64_pack(), fp64_process_NaN(), fp64_unpack(), fp64_zero(), FPCRRounding(), FPLIB_DZC, FPLIB_IXC, FPLIB_OFC, FPLIB_UFC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), panic, and set_fpscr0().
fplibRecipStepFused() [1/4]
template<class T > T ArmISA::fplibRecipStepFused (T op1, T op2, FPSCR & fpscr)
Floating-point reciprocal step.
fplibRecipStepFused() [2/4]
template<> uint16_t ArmISA::fplibRecipStepFused (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3898 of file fplib.cc.
References FP16_EXP_INF, fp16_FPTwo(), fp16_infinity(), fp16_muladd(), fp16_process_NaNs(), fp16_unpack(), mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibRecipStepFused() [3/4]
template<> uint32_t ArmISA::fplibRecipStepFused (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3928 of file fplib.cc.
References FP32_EXP_INF, fp32_FPTwo(), fp32_infinity(), fp32_muladd(), fp32_process_NaNs(), fp32_unpack(), mode, modeConv(), and set_fpscr0().
fplibRecipStepFused() [4/4]
template<> uint64_t ArmISA::fplibRecipStepFused (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3958 of file fplib.cc.
References FP64_EXP_INF, fp64_FPTwo(), fp64_infinity(), fp64_muladd(), fp64_process_NaNs(), fp64_unpack(), mode, modeConv(), and set_fpscr0().
fplibRecpX() [1/4]
template<class T > T ArmISA::fplibRecpX (T op, FPSCR & fpscr)
Floating-point reciprocal exponent.
fplibRecpX() [2/4]
template<> uint16_t ArmISA::fplibRecpX (uint16_t op, FPSCR & fpscr)
Definition at line 3988 of file fplib.cc.
References FP16_EXP_INF, fp16_is_NaN(), fp16_pack(), fp16_process_NaN(), fp16_unpack(), mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibRecpX() [3/4]
template<> uint32_t ArmISA::fplibRecpX (uint32_t op, FPSCR & fpscr)
Definition at line 4015 of file fplib.cc.
References FP32_EXP_INF, fp32_is_NaN(), fp32_pack(), fp32_process_NaN(), fp32_unpack(), mode, modeConv(), and set_fpscr0().
fplibRecpX() [4/4]
template<> uint64_t ArmISA::fplibRecpX (uint64_t op, FPSCR & fpscr)
Definition at line 4042 of file fplib.cc.
References FP64_EXP_INF, fp64_is_NaN(), fp64_pack(), fp64_process_NaN(), fp64_unpack(), mode, modeConv(), and set_fpscr0().
fplibRoundInt() [1/4]
template<class T > T ArmISA::fplibRoundInt (T op, FPRounding rounding, bool exact, FPSCR & fpscr)
Floating-point convert to integer.
fplibRoundInt() [2/4]
template<> uint16_t ArmISA::fplibRoundInt (uint16_t op, FPRounding rounding, bool exact, FPSCR & fpscr)
Definition at line 4069 of file fplib.cc.
References FP16_BITS, FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_is_NaN(), FP16_MANT_BITS, fp16_normalise(), fp16_pack(), fp16_process_NaN(), fp16_unpack(), fp16_zero(), FPLIB_IXC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEAWAY, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), X86ISA::op, panic, set_fpscr0(), and X86ISA::x.
Referenced by FPCRRounding().
fplibRoundInt() [3/4]
template<> uint32_t ArmISA::fplibRoundInt (uint32_t op, FPRounding rounding, bool exact, FPSCR & fpscr)
Definition at line 4134 of file fplib.cc.
References FP32_BITS, FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_is_NaN(), FP32_MANT_BITS, fp32_normalise(), fp32_pack(), fp32_process_NaN(), fp32_unpack(), fp32_zero(), FPLIB_IXC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEAWAY, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), X86ISA::op, panic, set_fpscr0(), and X86ISA::x.
fplibRoundInt() [4/4]
template<> uint64_t ArmISA::fplibRoundInt (uint64_t op, FPRounding rounding, bool exact, FPSCR & fpscr)
Definition at line 4199 of file fplib.cc.
References FP64_BITS, FP64_EXP_BIAS, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_is_NaN(), FP64_MANT_BITS, fp64_normalise(), fp64_pack(), fp64_process_NaN(), fp64_unpack(), fp64_zero(), FPLIB_IXC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEAWAY, FPRounding_TIEEVEN, FPRounding_ZERO, mode, modeConv(), X86ISA::op, panic, set_fpscr0(), and X86ISA::x.
fplibRSqrtEstimate() [1/4]
template<class T > T ArmISA::fplibRSqrtEstimate (T op, FPSCR & fpscr)
Floating-point reciprocal square root estimate.
fplibRSqrtEstimate() [2/4]
template<> uint16_t ArmISA::fplibRSqrtEstimate (uint16_t op, FPSCR & fpscr)
Definition at line 3517 of file fplib.cc.
References FP16_BITS, fp16_defaultNaN(), FP16_EXP_BIAS, FP16_EXP_BITS, FP16_EXP_INF, fp16_infinity(), fp16_is_NaN(), FP16_MANT_BITS, fp16_normalise(), fp16_pack(), fp16_process_NaN(), fp16_unpack(), fp16_zero(), FPLIB_DZC, FPLIB_IOC, mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibRSqrtEstimate() [3/4]
template<> uint32_t ArmISA::fplibRSqrtEstimate (uint32_t op, FPSCR & fpscr)
Definition at line 3552 of file fplib.cc.
References FP32_BITS, fp32_defaultNaN(), FP32_EXP_BIAS, FP32_EXP_BITS, FP32_EXP_INF, fp32_infinity(), fp32_is_NaN(), FP32_MANT_BITS, fp32_normalise(), fp32_pack(), fp32_process_NaN(), fp32_unpack(), fp32_zero(), FPLIB_DZC, FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibRSqrtEstimate() [4/4]
template<> uint64_t ArmISA::fplibRSqrtEstimate (uint64_t op, FPSCR & fpscr)
Definition at line 3587 of file fplib.cc.
References fp32_zero(), FP64_BITS, fp64_defaultNaN(), FP64_EXP_BIAS, FP64_EXP_BITS, FP64_EXP_INF, fp64_infinity(), fp64_is_NaN(), FP64_MANT_BITS, fp64_normalise(), fp64_pack(), fp64_process_NaN(), fp64_unpack(), FPLIB_DZC, FPLIB_IOC, mode, modeConv(), and set_fpscr0().
fplibRSqrtStepFused() [1/4]
template<class T > T ArmISA::fplibRSqrtStepFused (T op1, T op2, FPSCR & fpscr)
Floating-point reciprocal square root step.
fplibRSqrtStepFused() [2/4]
template<> uint16_t ArmISA::fplibRSqrtStepFused (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 3622 of file fplib.cc.
References FP16_EXP_INF, fp16_FPOnePointFive(), fp16_FPThree(), fp16_infinity(), fp16_muladd(), fp16_process_NaNs(), fp16_unpack(), mode, modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibRSqrtStepFused() [3/4]
template<> uint32_t ArmISA::fplibRSqrtStepFused (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 3652 of file fplib.cc.
References FP32_EXP_INF, fp32_FPOnePointFive(), fp32_FPThree(), fp32_infinity(), fp32_muladd(), fp32_process_NaNs(), fp32_unpack(), mode, modeConv(), and set_fpscr0().
fplibRSqrtStepFused() [4/4]
template<> uint64_t ArmISA::fplibRSqrtStepFused (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 3682 of file fplib.cc.
References FP64_EXP_INF, fp64_FPOnePointFive(), fp64_FPThree(), fp64_infinity(), fp64_muladd(), fp64_process_NaNs(), fp64_unpack(), mode, modeConv(), and set_fpscr0().
fplibScale() [1/4]
template<class T > T ArmISA::fplibScale (T op1, T op2, FPSCR & fpscr)
Floating-point adjust exponent.
fplibScale() [2/4]
template<> uint16_t ArmISA::fplibScale (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 4264 of file fplib.cc.
References fp16_scale(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibScale() [3/4]
template<> uint32_t ArmISA::fplibScale (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 4274 of file fplib.cc.
References fp32_scale(), modeConv(), and set_fpscr0().
fplibScale() [4/4]
template<> uint64_t ArmISA::fplibScale (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 4284 of file fplib.cc.
References fp64_scale(), modeConv(), and set_fpscr0().
fplibSqrt() [1/4]
template<class T > T ArmISA::fplibSqrt (T op, FPSCR & fpscr)
Floating-point square root.
fplibSqrt() [2/4]
template<> uint16_t ArmISA::fplibSqrt (uint16_t op, FPSCR & fpscr)
Definition at line 4294 of file fplib.cc.
References fp16_sqrt(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibSqrt() [3/4]
template<> uint32_t ArmISA::fplibSqrt (uint32_t op, FPSCR & fpscr)
Definition at line 4304 of file fplib.cc.
References fp32_sqrt(), modeConv(), and set_fpscr0().
fplibSqrt() [4/4]
template<> uint64_t ArmISA::fplibSqrt (uint64_t op, FPSCR & fpscr)
Definition at line 4314 of file fplib.cc.
References fp64_sqrt(), modeConv(), and set_fpscr0().
fplibSub() [1/4]
template<class T > T ArmISA::fplibSub (T op1, T op2, FPSCR & fpscr)
Floating-point subtract.
fplibSub() [2/4]
template<> uint16_t ArmISA::fplibSub (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 4324 of file fplib.cc.
References fp16_add(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibSub() [3/4]
template<> uint32_t ArmISA::fplibSub (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 4334 of file fplib.cc.
References fp32_add(), modeConv(), and set_fpscr0().
fplibSub() [4/4]
template<> uint64_t ArmISA::fplibSub (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 4344 of file fplib.cc.
References fp64_add(), modeConv(), and set_fpscr0().
fplibTrigMulAdd() [1/4]
template<class T > T ArmISA::fplibTrigMulAdd (uint8_t coeff_index, T op1, T op2, FPSCR & fpscr)
Floating-point trigonometric multiply-add coefficient.
fplibTrigMulAdd() [2/4]
template<> uint16_t ArmISA::fplibTrigMulAdd (uint8_t coeff_index, uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 4354 of file fplib.cc.
References FP16_BITS, fp16_muladd(), fplibAbs(), modeConv(), and set_fpscr0().
Referenced by FPCRRounding().
fplibTrigMulAdd() [3/4]
template<> uint32_t ArmISA::fplibTrigMulAdd (uint8_t coeff_index, uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 4388 of file fplib.cc.
References FP32_BITS, fp32_muladd(), fplibAbs(), modeConv(), and set_fpscr0().
fplibTrigMulAdd() [4/4]
template<> uint64_t ArmISA::fplibTrigMulAdd (uint8_t coeff_index, uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 4422 of file fplib.cc.
References FP64_BITS, fp64_muladd(), fplibAbs(), modeConv(), set_fpscr0(), and ULL.
fplibTrigSMul() [1/4]
template<class T > T ArmISA::fplibTrigSMul (T op1, T op2, FPSCR & fpscr)
Floating-point trigonometric starting value.
fplibTrigSMul() [2/4]
template<> uint16_t ArmISA::fplibTrigSMul (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 4456 of file fplib.cc.
References FP16_BITS, fp16_is_NaN(), fp16_mul(), fp16_unpack(), mode, modeConv(), set_fpscr0(), and ULL.
Referenced by FPCRRounding().
fplibTrigSMul() [3/4]
template<> uint32_t ArmISA::fplibTrigSMul (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 4476 of file fplib.cc.
References FP32_BITS, fp32_is_NaN(), fp32_mul(), fp32_unpack(), mode, modeConv(), set_fpscr0(), and ULL.
fplibTrigSMul() [4/4]
template<> uint64_t ArmISA::fplibTrigSMul (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 4495 of file fplib.cc.
References FP64_BITS, fp64_is_NaN(), fp64_mul(), fp64_unpack(), mode, modeConv(), set_fpscr0(), and ULL.
fplibTrigSSel() [1/4]
template<class T > T ArmISA::fplibTrigSSel (T op1, T op2, FPSCR & fpscr)
Floating-point trigonometric select coefficient.
fplibTrigSSel() [2/4]
template<> uint16_t ArmISA::fplibTrigSSel (uint16_t op1, uint16_t op2, FPSCR & fpscr)
Definition at line 4514 of file fplib.cc.
References FP16_BITS, FP16_EXP_BIAS, and FP16_MANT_BITS.
Referenced by FPCRRounding().
fplibTrigSSel() [3/4]
template<> uint32_t ArmISA::fplibTrigSSel (uint32_t op1, uint32_t op2, FPSCR & fpscr)
Definition at line 4525 of file fplib.cc.
References FP32_BITS, FP32_EXP_BIAS, and FP32_MANT_BITS.
fplibTrigSSel() [4/4]
template<> uint64_t ArmISA::fplibTrigSSel (uint64_t op1, uint64_t op2, FPSCR & fpscr)
Definition at line 4536 of file fplib.cc.
References FP64_BITS, FP64_EXP_BIAS, and FP64_MANT_BITS.
fpMax()
template<typename T > static T ArmISA::fpMax (T a, T b) inline static
Definition at line 639 of file vfp.hh.
References a, and b.
fpMaxNum()
template<typename T > static T ArmISA::fpMaxNum (T a, T b) inline static
Definition at line 622 of file vfp.hh.
References a, b, fpToBits(), signbit(), and ULL.
fpMin()
template<typename T > static T ArmISA::fpMin (T a, T b) inline static
Definition at line 667 of file vfp.hh.
References a, and b.
fpMinNum()
template<typename T > static T ArmISA::fpMinNum (T a, T b) inline static
Definition at line 650 of file vfp.hh.
References a, b, fpToBits(), signbit(), and ULL.
fpMul()
template<typename T > static T ArmISA::fpMul (T a, T b) inline static
Definition at line 569 of file vfp.hh.
References b.
fpMulAdd()
template<typename T > static T ArmISA::fpMulAdd (T op1, T op2, T addend) inline static
Definition at line 589 of file vfp.hh.
References bitsToFp(), fpToBits(), and ULL.
fpMulD()
static double ArmISA::fpMulD (double a, double b) inline static
Definition at line 581 of file vfp.hh.
References b.
fpMulS()
static float ArmISA::fpMulS (float a, float b) inline static
Definition at line 575 of file vfp.hh.
References b.
fpMulX()
template<typename T > static T ArmISA::fpMulX (T a, T b) inline static
Definition at line 535 of file vfp.hh.
References HsailISA::fpclassify(), and fpToBits().
fpRecipEstimate()
float ArmISA::fpRecipEstimate (FPSCR & fpscr, float op)
Definition at line 843 of file vfp.cc.
References bits(), bitsToFp(), HsailISA::fpclassify(), fpToBits(), recipEstimate(), signbit(), and ULL.
Referenced by vfpFpToFixed().
fpRecps()
template<typename T > static T ArmISA::fpRecps (T a, T b) inline static
Definition at line 700 of file vfp.hh.
References b, FeUnderflow, and HsailISA::fpclassify().
fpRecpsS()
static float ArmISA::fpRecpsS (float a, float b) inline static
Definition at line 743 of file vfp.hh.
References b, FeUnderflow, and HsailISA::fpclassify().
fpRIntX()
template<typename T > static T ArmISA::fpRIntX (T a, FPSCR & fpscr) inline static
Definition at line 610 of file vfp.hh.
fprSqrtEstimate()
float ArmISA::fprSqrtEstimate (FPSCR & fpscr, float op)
Definition at line 761 of file vfp.cc.
References bits(), bitsToFp(), HsailISA::fpclassify(), fpToBits(), recipSqrtEstimate(), signbit(), and ULL.
Referenced by vfpFpToFixed().
fpRSqrts()
template<typename T > static T ArmISA::fpRSqrts (T a, T b) inline static
Definition at line 678 of file vfp.hh.
References b, FeUnderflow, and HsailISA::fpclassify().
fpRSqrtsS()
static float ArmISA::fpRSqrtsS (float a, float b) inline static
Definition at line 722 of file vfp.hh.
References b, FeUnderflow, and HsailISA::fpclassify().
fpStandardFPSCRValue()
FPSCR ArmISA::fpStandardFPSCRValue (const FPSCR & fpscr)
Definition at line 895 of file vfp.cc.
Referenced by vfpFpToFixed().
fpSub()
template<typename T > static T ArmISA::fpSub (T a, T b) inline static
Definition at line 485 of file vfp.hh.
References b.
fpSubD()
static double ArmISA::fpSubD (double a, double b) inline static
Definition at line 509 of file vfp.hh.
References b.
fpSubS()
static float ArmISA::fpSubS (float a, float b) inline static
Definition at line 503 of file vfp.hh.
References b.
fpToBits() [1/2]
static uint32_t ArmISA::fpToBits (float fp) inline static
Definition at line 156 of file vfp.hh.
References bits(), fp, and X86ISA::val.
Referenced by ArmISA::FpOp::binaryOp(), ArmISA::FpOp::dblHi(), ArmISA::FpOp::dblLow(), fixDest(), fixFpDFpSDest(), fixFpSFpDDest(), flushToZero(), fpMaxNum(), fpMinNum(), fpMulAdd(), fpMulX(), fpRecipEstimate(), fprSqrtEstimate(), highFromDouble(), isSnan(), lowFromDouble(), ArmISA::FpOp::processNans(), ArmISA::FpOp::ternaryOp(), ArmISA::FpOp::unaryOp(), unsignedRecipEstimate(), unsignedRSqrtEstimate(), vcvtFpDFpH(), and vcvtFpSFpH().
fpToBits() [2/2]
static uint64_t ArmISA::fpToBits (double fp) inline static
Definition at line 168 of file vfp.hh.
References bits(), fp, and X86ISA::val.
FPToFixed_16()
static uint16_t ArmISA::FPToFixed_16 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int * flags) static
Definition at line 4609 of file fplib.cc.
References FP16_BITS, FPLIB_IOC, FPToFixed_64(), ULL, and X86ISA::x.
Referenced by fplibFPToFixed().
FPToFixed_32()
static uint32_t ArmISA::FPToFixed_32 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int * flags) static
Definition at line 4595 of file fplib.cc.
References FP32_BITS, FPLIB_IOC, FPToFixed_64(), ULL, and X86ISA::x.
Referenced by fplibFPToFixed().
FPToFixed_64()
static uint64_t ArmISA::FPToFixed_64 (int sgn, int exp, uint64_t mnt, bool u, FPRounding rounding, int * flags) static
Definition at line 4546 of file fplib.cc.
References FP64_BITS, FP64_EXP_BIAS, FP64_EXP_BITS, FPLIB_IOC, FPLIB_IXC, FPRounding_NEGINF, FPRounding_POSINF, FPRounding_TIEAWAY, FPRounding_TIEEVEN, FPRounding_ZERO, lsl64(), lsr64(), panic, ULL, and X86ISA::x.
Referenced by fplibFPToFixed(), FPToFixed_16(), and FPToFixed_32().
getArgument()
uint64_t ArmISA::getArgument (ThreadContext * tc, int & number, uint16_t size, bool fp)
Definition at line 69 of file utility.cc.
References FullSystem, ThreadContext::getVirtProxy(), inAArch64(), MachineBytes, NumArgumentRegs, panic, PortProxy::read(), ThreadContext::readIntReg(), sp, and StackPointerReg.
Referenced by msrMrs64IssBuild().
getDTBPtr()
template<typename T > TLB* ArmISA::getDTBPtr (T * tc)
Definition at line 477 of file tlb.hh.
References tlb.
Referenced by ArmISA::TLBIALL::operator()(), ArmISA::DTLBIALL::operator()(), ArmISA::TLBIASID::operator()(), ArmISA::DTLBIASID::operator()(), ArmISA::TLBIALLN::operator()(), ArmISA::TLBIMVAA::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::DTLBIMVA::operator()(), ArmISA::TLBIIPA::operator()(), and ArmISA::ISA::setMiscReg().
getExecutingAsid()
uint64_t ArmISA::getExecutingAsid (ThreadContext * tc) inline
Definition at line 350 of file utility.hh.
References decodeMrsMsrBankedReg(), MISCREG_CONTEXTIDR, MipsISA::r, and ThreadContext::readMiscReg().
getFaultVAddr()
bool ArmISA::getFaultVAddr (Fault fault, Addr & va)
Returns true if the fault passed as a first argument was triggered by a memory access, false otherwise.
If true it is storing the faulting address in the va argument
Parameters
fault generated fault
va function will modify this passed-by-reference parameter with the correct faulting virtual address
Returns
true if va contains a valid value, false otherwise
Definition at line 1650 of file faults.cc.
References GenericPageTableFault::getFaultVAddr(), GenericAlignmentFault::getFaultVAddr(), and ArmISA::ArmFault::getFaultVAddr().
getITBPtr()
template<typename T > TLB* ArmISA::getITBPtr (T * tc)
Definition at line 468 of file tlb.hh.
References tlb.
Referenced by ArmISA::TLBIALL::operator()(), ArmISA::ITLBIALL::operator()(), ArmISA::TLBIASID::operator()(), ArmISA::ITLBIASID::operator()(), ArmISA::TLBIALLN::operator()(), ArmISA::TLBIMVAA::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::ITLBIMVA::operator()(), ArmISA::TLBIIPA::operator()(), and ArmISA::ISA::setMiscReg().
getMPIDR()
RegVal ArmISA::getMPIDR (ArmSystem * arm_sys, ThreadContext * tc)
This helper function is returing the value of MPIDR_EL1.
Definition at line 263 of file utility.cc.
References ThreadContext::contextId(), ThreadContext::cpuId(), ArmSystem::multiProc, System::multiThread, and ThreadContext::socketId().
Referenced by Gicv3Redistributor::getAffinity(), inSecureState(), ArmISA::Reset::invoke(), and readMPIDR().
getRestoredITBits()
static uint8_t ArmISA::getRestoredITBits (ThreadContext * tc, CPSR spsr) static
Definition at line 1021 of file static_inst.cc.
References bits(), el, EL2, itd, itState(), MISCREG_HSCTLR, MISCREG_SCTLR, opModeToEL(), and ThreadContext::readMiscReg().
Referenced by ArmISA::ArmStaticInst::getPSTATEFromPSR().
globalClearExclusive()
template<class XC > void ArmISA::globalClearExclusive (XC * xc) inline
Definition at line 153 of file locked_mem.hh.
References DPRINTF, MISCREG_LOCKFLAG, and MISCREG_SEV_MAILBOX.
handleLockedRead()
template<class XC > void ArmISA::handleLockedRead (XC * xc, const RequestPtr & req) inline
Definition at line 94 of file locked_mem.hh.
References DPRINTF, MISCREG_LOCKADDR, and MISCREG_LOCKFLAG.
handleLockedSnoop()
template<class XC > void ArmISA::handleLockedSnoop (XC * xc, PacketPtr pkt, Addr cacheBlockMask) inline
Definition at line 65 of file locked_mem.hh.
References DPRINTF, Packet::getAddr(), Packet::isInvalidate(), Packet::isWrite(), MISCREG_LOCKADDR, MISCREG_LOCKFLAG, and MISCREG_SEV_MAILBOX.
handleLockedSnoopHit()
template<class XC > void ArmISA::handleLockedSnoopHit (XC * xc) inline
Definition at line 104 of file locked_mem.hh.
References DPRINTF, MISCREG_LOCKADDR, MISCREG_LOCKFLAG, and MISCREG_SEV_MAILBOX.
handleLockedWrite()
template<class XC > bool ArmISA::handleLockedWrite (XC * xc, const RequestPtr & req, Addr cacheBlockMask) inline
Definition at line 114 of file locked_mem.hh.
References DPRINTF, MISCREG_LOCKADDR, MISCREG_LOCKFLAG, and warn.
highFromDouble()
static uint32_t ArmISA::highFromDouble (double val) inline static
Definition at line 252 of file vfp.hh.
References fpToBits().
illegalExceptionReturn()
static bool ArmISA::illegalExceptionReturn (ThreadContext * tc, CPSR cpsr, CPSR spsr) static
Definition at line 1050 of file static_inst.cc.
References EL0, EL1, EL2, EL3, ELIs64(), ELUsingAArch32K(), ArmSystem::haveEL(), ArmSystem::highestELIs64(), MISCREG_HCR_EL2, MISCREG_SCR_EL3, mode, opModeToEL(), ThreadContext::readMiscReg(), unknownMode(), and unknownMode32().
Referenced by ArmISA::ArmStaticInst::getPSTATEFromPSR().
inAArch64()
bool ArmISA::inAArch64 (ThreadContext * tc)
Definition at line 221 of file utility.cc.
References MISCREG_CPSR, and ThreadContext::readMiscReg().
Referenced by ArmISA::RemoteGDB::gdbRegs(), getArgument(), ArmISA::RemoteGDB::getXferFeaturesRead(), inPrivilegedMode(), inSecureState(), skipFunction(), and ArmV8KvmCPU::updateThreadContext().
initCPU()
void ArmISA::initCPU (ThreadContext * tc, int cpuId)
Definition at line 58 of file utility.cc.
References Stats::reset().
Referenced by copyMiscRegs().
inPrivilegedMode() [1/2]
static bool ArmISA::inPrivilegedMode (CPSR cpsr) inline static
Definition at line 137 of file utility.hh.
References inUserMode().
inPrivilegedMode() [2/2]
static bool ArmISA::inPrivilegedMode (ThreadContext * tc) inline static
Definition at line 143 of file utility.hh.
References inAArch64(), and inUserMode().
inSecureState() [1/2]
bool ArmISA::inSecureState (ThreadContext * tc)
Definition at line 205 of file utility.cc.
References ArmSystem::haveSecurity(), inAArch64(), MISCREG_CPSR, MISCREG_SCR, MISCREG_SCR_EL3, and ThreadContext::readMiscReg().
Referenced by ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), MiscRegOp64::checkEL2Trap(), ArmISA::ArmStaticInst::checkFPAdvSIMDTrap64(), ArmISA::Interrupts::checkInterrupts(), ArmISA::ArmStaticInst::checkSETENDEnabled(), ArmISA::Interrupts::checkWfiWake(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), ArmISA::ISA::flattenMiscIndex(), ArmISA::ArmStaticInst::generalExceptionsToAArch64(), ArmISA::ISA::getCurSveVecLenInBits(), ArmISA::Interrupts::getInterrupt(), ArmISA::Interrupts::getISR(), ArmISA::ISA::getMiscIndices(), inSecureState(), Gicv3CPUInterface::inSecureState(), ArmISA::PMU::CounterState::isFiltered(), mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), mcrrMrrc15TrapToHyp(), ArmISA::ArmFaultVals< FastInterrupt >::offset64(), ArmSemihosting::physProxy(), ArmISA::ISA::readMiscReg(), ArmISA::UndefinedInstruction::routeToHyp(), ArmISA::SupervisorCall::routeToHyp(), ArmISA::SupervisorTrap::routeToHyp(), ArmISA::PrefetchAbort::routeToHyp(), ArmISA::DataAbort::routeToHyp(), ArmISA::Interrupt::routeToHyp(), ArmISA::FastInterrupt::routeToHyp(), ArmISA::PCAlignmentFault::routeToHyp(), ArmISA::SystemError::routeToHyp(), ArmISA::SoftwareBreakpoint::routeToHyp(), ArmISA::ISA::setMiscReg(), ArmISA::ArmStaticInst::softwareBreakpoint32(), ArmISA::Interrupts::takeInt(), Trace::TarmacTracerRecord::TraceInstEntry::TraceInstEntry(), ArmISA::ArmStaticInst::trapWFx(), and ArmISA::TLB::updateMiscReg().
inSecureState() [2/2]
static bool ArmISA::inSecureState (SCR scr, CPSR cpsr) inline static
Definition at line 241 of file utility.hh.
References getMPIDR(), inSecureState(), isSecureBelowEL3(), longDescFormatInUse(), MODE_EL2H, MODE_EL2T, MODE_EL3H, MODE_EL3T, MODE_HYP, MODE_MON, and readMPIDR().
INTREG_ABT()
static IntRegIndex ArmISA::INTREG_ABT (unsigned index) inline static
Definition at line 401 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_FIQ()
static IntRegIndex ArmISA::INTREG_FIQ (unsigned index) inline static
Definition at line 455 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_HYP()
static IntRegIndex ArmISA::INTREG_HYP (unsigned index) inline static
Definition at line 347 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_IRQ()
static IntRegIndex ArmISA::INTREG_IRQ (unsigned index) inline static
Definition at line 437 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_MON()
static IntRegIndex ArmISA::INTREG_MON (unsigned index) inline static
Definition at line 383 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_SVC()
static IntRegIndex ArmISA::INTREG_SVC (unsigned index) inline static
Definition at line 365 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_UND()
static IntRegIndex ArmISA::INTREG_UND (unsigned index) inline static
Definition at line 419 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
INTREG_USR()
static IntRegIndex ArmISA::INTREG_USR (unsigned index) inline static
Definition at line 329 of file intregs.hh.
References MipsISA::index, and NUM_ARCH_INTREGS.
Referenced by Trace::TarmacParserRecord::advanceTrace(), and flattenIntRegModeIndex().
intRegInMode()
static int ArmISA::intRegInMode (OperatingMode mode, int reg) inline static
Definition at line 464 of file intregs.hh.
References NUM_ARCH_INTREGS, and X86ISA::reg.
Referenced by decodeMrsMsrBankedReg(), and ArmISA::MacroMemOp::MacroMemOp().
inUserMode() [1/2]
static bool ArmISA::inUserMode (CPSR cpsr) inline static
Definition at line 125 of file utility.hh.
References MODE_EL0T, and MODE_USER.
Referenced by inPrivilegedMode(), and inUserMode().
inUserMode() [2/2]
static bool ArmISA::inUserMode (ThreadContext * tc) inline static
Definition at line 131 of file utility.hh.
References inUserMode(), MISCREG_CPSR, and ThreadContext::readMiscRegNoEffect().
isBigEndian64()
bool ArmISA::isBigEndian64 (ThreadContext * tc)
Definition at line 364 of file utility.cc.
References currEL(), e0e, ee, EL0, EL1, EL2, EL3, MISCREG_SCTLR_EL1, MISCREG_SCTLR_EL2, MISCREG_SCTLR_EL3, panic, and ThreadContext::readMiscReg().
Referenced by byteOrder(), and currEL().
isSecureBelowEL3()
bool ArmISA::isSecureBelowEL3 (ThreadContext * tc) inline
Return TRUE if an Exception level below EL3 is in Secure state.
Differs from inSecureState in that it ignores the current EL or Mode in considering security state.
Definition at line 214 of file utility.cc.
References EL3, ArmSystem::haveEL(), MISCREG_SCR_EL3, and ThreadContext::readMiscReg().
Referenced by ELIsInHost(), ELUsingAArch32K(), inSecureState(), and readMPIDR().
isSnan()
template<class fpType > static bool ArmISA::isSnan (fpType val) inline static
Definition at line 205 of file vfp.hh.
References fpToBits(), and ULL.
isSP()
static bool ArmISA::isSP (IntRegIndex reg) inline static
Definition at line 517 of file intregs.hh.
References INTREG_SPX.
Referenced by ArmISA::Memory64::Memory64(), ArmISA::SveContigMemSI::SveContigMemSI(), ArmISA::SveContigMemSS::SveContigMemSS(), ArmISA::SveMemPredFillSpill::SveMemPredFillSpill(), ArmISA::SveMemVecFillSpill::SveMemVecFillSpill(), ArmISA::VldMultOp64::VldMultOp64(), ArmISA::VldSingleOp64::VldSingleOp64(), ArmISA::VstMultOp64::VstMultOp64(), and ArmISA::VstSingleOp64::VstSingleOp64().
itState()
static uint8_t ArmISA::itState (CPSR psr) inline static
Definition at line 220 of file utility.hh.
References addr, and purifyTaggedAddr().
Referenced by getRestoredITBits().
longDescFormatInUse()
bool ArmISA::longDescFormatInUse (ThreadContext * tc)
Definition at line 228 of file utility.cc.
References ArmSystem::haveLPAE(), MISCREG_TTBCR, and ThreadContext::readMiscReg().
Referenced by inSecureState(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::processWalkWrapper(), ArmISA::TLB::translateFs(), ArmISA::TLB::updateMiscReg(), and ArmISA::TableWalker::walk().
lowFromDouble()
static uint32_t ArmISA::lowFromDouble (double val) inline static
Definition at line 246 of file vfp.hh.
References fpToBits().
lsl128()
static void ArmISA::lsl128 (uint64_t * r0, uint64_t * r1, uint64_t x0, uint64_t x1, uint32_t shift) inline static
Definition at line 132 of file fplib.cc.
References shift.
Referenced by fp64_muladd(), and fp64_sqrt().
lsl16()
static uint16_t ArmISA::lsl16 (uint16_t x, uint32_t shift) inline static
Definition at line 96 of file fplib.cc.
References shift.
Referenced by fp16_add(), and fp16_round_().
lsl32()
static uint32_t ArmISA::lsl32 (uint32_t x, uint32_t shift) inline static
Definition at line 108 of file fplib.cc.
References shift.
Referenced by fp16_mul(), fp16_muladd(), fp32_add(), and fp32_round_().
lsl64()
static uint64_t ArmISA::lsl64 (uint64_t x, uint32_t shift) inline static
Definition at line 120 of file fplib.cc.
References shift.
Referenced by fp32_mul(), fp32_muladd(), fp64_add(), fp64_round_(), and FPToFixed_64().
lsr128()
static void ArmISA::lsr128 (uint64_t * r0, uint64_t * r1, uint64_t x0, uint64_t x1, uint32_t shift) inline static
Definition at line 150 of file fplib.cc.
References shift.
Referenced by fp64_div(), fp64_muladd(), and fp64_sqrt().
lsr16()
static uint16_t ArmISA::lsr16 (uint16_t x, uint32_t shift) inline static
Definition at line 102 of file fplib.cc.
References shift.
Referenced by fp16_add(), and fp16_round_().
lsr32()
static uint32_t ArmISA::lsr32 (uint32_t x, uint32_t shift) inline static
Definition at line 114 of file fplib.cc.
References shift.
Referenced by fp16_mul(), fp16_muladd(), fp32_add(), and fp32_round_().
lsr64()
static uint64_t ArmISA::lsr64 (uint64_t x, uint32_t shift) inline static
Definition at line 126 of file fplib.cc.
References shift.
Referenced by fp32_mul(), fp32_muladd(), fp64_add(), fp64_round_(), and FPToFixed_64().
makeDouble()
static double ArmISA::makeDouble (uint32_t low, uint32_t high) inline static
Definition at line 239 of file vfp.hh.
References bitsToFp().
makeSP()
static IntRegIndex ArmISA::makeSP (IntRegIndex reg) inline static
Definition at line 501 of file intregs.hh.
References INTREG_SPX, INTREG_X31, and X86ISA::reg.
Referenced by ArmISA::PairMemOp::PairMemOp(), ArmISA::VldMultOp64::VldMultOp64(), ArmISA::VldSingleOp64::VldSingleOp64(), ArmISA::VstMultOp64::VstMultOp64(), and ArmISA::VstSingleOp64::VstSingleOp64().
makeZero()
static IntRegIndex ArmISA::makeZero (IntRegIndex reg) inline static
Definition at line 509 of file intregs.hh.
References INTREG_X31, INTREG_ZERO, and X86ISA::reg.
mcrMrc14TrapToHyp()
bool ArmISA::mcrMrc14TrapToHyp (const MiscRegIndex miscReg, HCR hcr, CPSR cpsr, SCR scr, HDCR hdcr, HSTR hstr, HCPTR hcptr, uint32_t iss)
Definition at line 611 of file utility.cc.
References inform, inSecureState(), mcrMrcIssExtract(), MISCREG_DBGDRAR, MISCREG_DBGDSAR, MISCREG_DBGOSDLR, MISCREG_DBGOSLAR, MISCREG_DBGOSLSR, MISCREG_DBGPRCR, MISCREG_JIDR, MISCREG_JMCR, MISCREG_JOSCR, MISCREG_TEECR, MISCREG_TEEHBR, MODE_HYP, opc2, rt, and unflattenMiscReg().
Referenced by msrMrs64IssBuild().
mcrMrc15TrapToHyp()
bool ArmISA::mcrMrc15TrapToHyp (const MiscRegIndex miscReg, ThreadContext * tc, uint32_t iss)
Definition at line 471 of file utility.cc.
References ThreadContext::getIsaPtr(), inSecureState(), mcrMrcIssExtract(), MISCREG_ACTLR, MISCREG_ADFSR, MISCREG_AIDR, MISCREG_AIFSR, MISCREG_CCSIDR, MISCREG_CLIDR, MISCREG_CONTEXTIDR, MISCREG_CPACR, MISCREG_CPSR, MISCREG_CSSELR, MISCREG_CTR, MISCREG_DACR, MISCREG_DCCIMVAC, MISCREG_DCCISW, MISCREG_DCCMVAC, MISCREG_DCCMVAU, MISCREG_DCCSW, MISCREG_DCIMVAC, MISCREG_DCISW, MISCREG_DFAR, MISCREG_DFSR, MISCREG_DTLBIALL, MISCREG_DTLBIASID, MISCREG_DTLBIMVA, MISCREG_HCPTR, MISCREG_HCR, MISCREG_HDCR, MISCREG_HSTR, MISCREG_ICC_ASGI1R, MISCREG_ICC_SGI0R, MISCREG_ICC_SGI1R, MISCREG_ICIALLU, MISCREG_ICIALLUIS, MISCREG_ICIMVAU, MISCREG_ID_AFR0, MISCREG_ID_DFR0, MISCREG_ID_ISAR0, MISCREG_ID_ISAR1, MISCREG_ID_ISAR2, MISCREG_ID_ISAR3, MISCREG_ID_ISAR4, MISCREG_ID_ISAR5, MISCREG_ID_MMFR0, MISCREG_ID_MMFR1, MISCREG_ID_MMFR2, MISCREG_ID_MMFR3, MISCREG_ID_PFR0, MISCREG_ID_PFR1, MISCREG_IFAR, MISCREG_IFSR, MISCREG_ITLBIALL, MISCREG_ITLBIASID, MISCREG_ITLBIMVA, MISCREG_MAIR0, MISCREG_MAIR1, MISCREG_NMRR, MISCREG_PMCR, MISCREG_PRRR, MISCREG_REVIDR, MISCREG_SCR, MISCREG_SCTLR, MISCREG_TCMTR, MISCREG_TLBIALL, MISCREG_TLBIALLIS, MISCREG_TLBIASID, MISCREG_TLBIASIDIS, MISCREG_TLBIMVA, MISCREG_TLBIMVAA, MISCREG_TLBIMVAAIS, MISCREG_TLBIMVAAL, MISCREG_TLBIMVAALIS, MISCREG_TLBIMVAIS, MISCREG_TLBIMVAL, MISCREG_TLBIMVALIS, MISCREG_TLBTR, MISCREG_TTBCR, MISCREG_TTBR0, MISCREG_TTBR1, MODE_HYP, opc2, ThreadContext::readMiscReg(), rt, and unflattenMiscReg().
Referenced by McrMrcMiscInst::execute(), McrMrcImplDefined::execute(), and msrMrs64IssBuild().
mcrMrcIssBuild()
static uint32_t ArmISA::mcrMrcIssBuild (bool isRead, uint32_t crm, IntRegIndex rt, uint32_t crn, uint32_t opc1, uint32_t opc2) inline static
Definition at line 277 of file utility.hh.
mcrMrcIssExtract()
static void ArmISA::mcrMrcIssExtract (uint32_t iss, bool & isRead, uint32_t & crm, IntRegIndex & rt, uint32_t & crn, uint32_t & opc1, uint32_t & opc2) inline static
Definition at line 289 of file utility.hh.
Referenced by mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), and mcrrMrrc15TrapToHyp().
mcrrMrrc15TrapToHyp()
bool ArmISA::mcrrMrrc15TrapToHyp (const MiscRegIndex miscReg, CPSR cpsr, SCR scr, HSTR hstr, HCR hcr, uint32_t iss)
Definition at line 661 of file utility.cc.
References inSecureState(), mcrMrcIssExtract(), MISCREG_ADFSR, MISCREG_AIFSR, MISCREG_CONTEXTIDR, MISCREG_DACR, MISCREG_DFAR, MISCREG_DFSR, MISCREG_IFAR, MISCREG_IFSR, MISCREG_MAIR0, MISCREG_MAIR1, MISCREG_NMRR, MISCREG_PRRR, MISCREG_SCTLR, MISCREG_TTBCR, MISCREG_TTBR0, MISCREG_TTBR1, MODE_HYP, opc2, rt, and unflattenMiscReg().
Referenced by msrMrs64IssBuild().
mcrrMrrcIssBuild()
static uint32_t ArmISA::mcrrMrrcIssBuild (bool isRead, uint32_t crm, IntRegIndex rt, IntRegIndex rt2, uint32_t opc1) inline static
Definition at line 301 of file utility.hh.
modeConv()
static int ArmISA::modeConv (FPSCR fpscr) static
Definition at line 2203 of file fplib.cc.
References FPLIB_FZ16, and X86ISA::x.
Referenced by fplibAdd(), fplibCompare(), fplibCompareEQ(), fplibCompareGE(), fplibCompareGT(), fplibCompareUN(), fplibConvert(), fplibDiv(), fplibFPToFixed(), fplibMax(), fplibMin(), fplibMul(), fplibMulAdd(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), fplibScale(), fplibSqrt(), fplibSub(), fplibTrigMulAdd(), and fplibTrigSMul().
modified_imm()
static uint32_t ArmISA::modified_imm (uint8_t ctrlImm, uint8_t dataImm) inline static
Definition at line 60 of file pred_inst.hh.
msrMrs64IssBuild()
static uint32_t ArmISA::msrMrs64IssBuild (bool isRead, uint32_t op0, uint32_t op1, uint32_t crn, uint32_t crm, uint32_t op2, IntRegIndex rt) inline static
Definition at line 312 of file utility.hh.
References fp, getArgument(), mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), mcrrMrrc15TrapToHyp(), skipFunction(), and SPAlignmentCheckEnabled().
mul62x62()
static void ArmISA::mul62x62 (uint64_t * x0, uint64_t * x1, uint64_t a, uint64_t b) inline static
Definition at line 168 of file fplib.cc.
References MipsISA::a0, a1, X86ISA::b1, and mask.
Referenced by fp64_div(), fp64_mul(), fp64_muladd(), and fp64_sqrt().
mul64x32()
static void ArmISA::mul64x32 (uint64_t * x0, uint64_t * x1, uint64_t a, uint32_t b) inline static
Definition at line 186 of file fplib.cc.
References b, t0, and t1.
Referenced by fp64_div(), and fp64_sqrt().
number_of_ones()
static unsigned int ArmISA::number_of_ones (int32_t val) inline static
Definition at line 52 of file macromem.hh.
References i.
Referenced by ArmISA::MacroMemOp::MacroMemOp().
opModeIsH()
static bool ArmISA::opModeIsH (OperatingMode mode) inline static
Definition at line 676 of file types.hh.
References MODE_EL1H, MODE_EL2H, and MODE_EL3H.
opModeIsT()
static bool ArmISA::opModeIsT (OperatingMode mode) inline static
Definition at line 682 of file types.hh.
References MODE_EL0T, MODE_EL1T, MODE_EL2T, and MODE_EL3T.
Referenced by ArmISA::ArmFaultVals< FastInterrupt >::offset64().
opModeToEL()
static ExceptionLevel ArmISA::opModeToEL (OperatingMode mode) inline static
Definition at line 689 of file types.hh.
References EL0, EL1, EL2, EL3, MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, MODE_USER, and panic.
Referenced by badMode(), badMode32(), currEL(), ArmISA::ISA::flattenIntIndex(), getRestoredITBits(), illegalExceptionReturn(), and ArmISA::ArmFault::update().
prepFpState()
VfpSavedState ArmISA::prepFpState (uint32_t rMode)
Definition at line 173 of file vfp.cc.
References FeAllExceptions, FeRoundDown, FeRoundNearest, FeRoundUpward, FeRoundZero, VfpRoundDown, VfpRoundNearest, VfpRoundUpward, and VfpRoundZero.
Referenced by ArmISA::FpOp::binaryOp(), ArmISA::FpOp::ternaryOp(), and ArmISA::FpOp::unaryOp().
preUnflattenMiscReg()
void ArmISA::preUnflattenMiscReg ()
Definition at line 1098 of file miscregs.cc.
References i, MISCREG_BANKED, MISCREG_BANKED_CHILD, miscRegInfo, NUM_MISCREGS, and X86ISA::reg.
Referenced by ArmISA::ISA::ISA().
PteAddr()
Addr ArmISA::PteAddr (Addr a) inline
Definition at line 43 of file vtophys.hh.
References PteMask, PteShift, MipsISA::vaddr, virtvalid(), and vtophys().
purifyTaggedAddr() [1/2]
Addr ArmISA::purifyTaggedAddr (Addr addr, ThreadContext * tc, ExceptionLevel el, TTBCR tcr)
Removes the tag from tagged addresses if that mode is enabled.
Parameters
addr The address to be purified.
tc The thread context.
el The controlled exception level.
Returns
The purified address.
Definition at line 394 of file utility.cc.
References addr, bits(), EL0, EL1, EL2, EL3, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), mask, MISCREG_TCR_EL2, panic, and ThreadContext::readMiscReg().
Referenced by ArmISA::TLB::checkPermissions64(), ArmISA::TLB::getTE(), ArmISA::ArmFault::invoke64(), itState(), ArmISA::TLB::translateFs(), ArmISA::TLB::translateSe(), and ArmISA::TableWalker::walk().
purifyTaggedAddr() [2/2]
Addr ArmISA::purifyTaggedAddr (Addr addr, ThreadContext * tc, ExceptionLevel el)
Definition at line 425 of file utility.cc.
References addr, bits(), EL0, EL1, EL2, EL3, ArmSystem::haveSecurity(), ArmSystem::haveVirtualization(), mask, MISCREG_TCR_EL1, MISCREG_TCR_EL2, MISCREG_TCR_EL3, panic, and ThreadContext::readMiscReg().
readMPIDR()
RegVal ArmISA::readMPIDR (ArmSystem * arm_sys, ThreadContext * tc)
This helper function is either returing the value of MPIDR_EL1 (by calling getMPIDR), or it is issuing a read to VMPIDR_EL2 (as it happens in virtualized systems)
Definition at line 235 of file utility.cc.
References currEL(), EL0, EL1, EL2, EL3, getMPIDR(), ArmSystem::haveEL(), isSecureBelowEL3(), M5_FALLTHROUGH, MISCREG_VMPIDR_EL2, panic, ThreadContext::readMiscReg(), and warn_once.
Referenced by inSecureState(), and ArmISA::ISA::readMiscReg().
readSymbol()
static int32_t ArmISA::readSymbol (ThreadContext * tc, const std::string name) static
Definition at line 48 of file stacktrace.cc.
References addr, SymbolTable::findAddress(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), GuestByteOrder, System::kernelSymtab, panic, and PortProxy::read().
Referenced by ArmISA::ProcessInfo::ProcessInfo().
readVecElem()
XReg ArmISA::readVecElem (VReg src, int index, int eSize) inline
Read a single NEON vector element.
Definition at line 94 of file neon64_mem.hh.
References data, ArmISA::VReg::hi, and ArmISA::VReg::lo.
Referenced by FullO3CPU< O3CPUImpl >::setVecLane(), and ThreadContext::~ThreadContext().
recipEstimate()
static double ArmISA::recipEstimate (double a) static
Definition at line 830 of file vfp.cc.
References q, MipsISA::r, and s.
Referenced by fpRecipEstimate(), and unsignedRecipEstimate().
recipSqrtEstimate()
static double ArmISA::recipSqrtEstimate (double a) static
Definition at line 743 of file vfp.cc.
References MipsISA::r, and s.
Referenced by fprSqrtEstimate(), and unsignedRSqrtEstimate().
rotate_imm()
static uint32_t ArmISA::rotate_imm (uint32_t immValue, uint32_t rotateValue) inline static
Definition at line 52 of file pred_inst.hh.
Referenced by ArmISA::PredImmOp::PredImmOp().
roundNEven()
template<typename T > static T ArmISA::roundNEven (T a) inline static
Definition at line 765 of file vfp.hh.
References X86ISA::val.
roundPage()
Addr ArmISA::roundPage (Addr addr)
Definition at line 465 of file utility.cc.
References PageBytes.
Referenced by advancePC().
sendEvent()
void ArmISA::sendEvent (ThreadContext * tc)
Send an event (SEV) to a specific PE if there isn't already a pending event.
Definition at line 196 of file utility.cc.
References ThreadContext::getCpuPtr(), INT_SEV, MISCREG_SEV_MAILBOX, BaseCPU::postInterrupt(), ThreadContext::readMiscReg(), and ThreadContext::threadId().
Referenced by copyMiscRegs(), SerialLink::SerialLinkMasterPort::schedTimingReq(), Bridge::BridgeMasterPort::schedTimingReq(), SerialLink::SerialLinkSlavePort::schedTimingResp(), Bridge::BridgeSlavePort::schedTimingResp(), DmaPort::sendDma(), SerialLink::SerialLinkSlavePort::trySendTiming(), Bridge::BridgeSlavePort::trySendTiming(), SerialLink::SerialLinkMasterPort::trySendTiming(), Bridge::BridgeMasterPort::trySendTiming(), and DmaPort::trySendTimingReq().
set_fpscr()
static void ArmISA::set_fpscr (FPSCR & fpscr, int flags) static
Definition at line 2211 of file fplib.cc.
References FPLIB_DZC, FPLIB_IDC, FPLIB_IOC, FPLIB_IXC, FPLIB_OFC, and FPLIB_UFC.
Referenced by fplibCompareEQ(), fplibCompareGE(), fplibCompareGT(), and fplibCompareUN().
set_fpscr0()
static void ArmISA::set_fpscr0 (FPSCR & fpscr, int flags) static
Definition at line 1901 of file fplib.cc.
References FPLIB_DZC, FPLIB_IDC, FPLIB_IOC, FPLIB_IXC, FPLIB_OFC, and FPLIB_UFC.
Referenced by fplibAdd(), fplibCompare(), fplibConvert(), fplibDiv(), fplibFixedToFP(), fplibFPToFixed(), fplibMax(), fplibMin(), fplibMul(), fplibMulAdd(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), fplibScale(), fplibSqrt(), fplibSub(), fplibTrigMulAdd(), and fplibTrigSMul().
setFPExceptions()
static void ArmISA::setFPExceptions (int exceptions) inline static
Definition at line 258 of file vfp.hh.
References FeAllExceptions.
Referenced by vfpFpToFixed().
setVfpMicroFlags()
template<class T > static void ArmISA::setVfpMicroFlags (VfpMicroMode mode, T & flags) inline static
Definition at line 62 of file vfp.hh.
References VfpFirstMicroop, VfpLastMicroop, VfpMicroop, and VfpNotAMicroop.
Referenced by ArmISA::FpRegImmOp::FpRegImmOp(), ArmISA::FpRegRegImmOp::FpRegRegImmOp(), ArmISA::FpRegRegOp::FpRegRegOp(), ArmISA::FpRegRegRegCondOp::FpRegRegRegCondOp(), ArmISA::FpRegRegRegImmOp::FpRegRegRegImmOp(), ArmISA::FpRegRegRegOp::FpRegRegRegOp(), and ArmISA::FpRegRegRegRegOp::FpRegRegRegRegOp().
simd_modified_imm()
static uint64_t ArmISA::simd_modified_imm (bool op, uint8_t cmode, uint8_t data, bool & immValid, bool isAarch64 = false) inline static
Definition at line 83 of file pred_inst.hh.
References bits(), data, i, M5_FALLTHROUGH, and ULL.
skipFunction()
void ArmISA::skipFunction (ThreadContext * tc)
Definition at line 131 of file utility.cc.
References ThreadContext::getCheckerCpuPtr(), inAArch64(), INTREG_X30, ThreadContext::pcState(), ThreadContext::pcStateNoRecord(), ThreadContext::readIntReg(), ReturnAddressReg, and ULL.
Referenced by msrMrs64IssBuild().
snsBankedIndex() [1/2]
int ArmISA::snsBankedIndex (MiscRegIndex reg, ThreadContext * tc)
Definition at line 1063 of file miscregs.cc.
References MISCREG_SCR, and ThreadContext::readMiscReg().
Referenced by ArmISA::ArmStaticInst::checkSETENDEnabled(), ArmISA::TableWalker::memAttrs(), ArmISA::TableWalker::memAttrsLPAE(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TLB::updateMiscReg(), and ArmISA::TableWalker::walk().
snsBankedIndex() [2/2]
int ArmISA::snsBankedIndex (MiscRegIndex reg, ThreadContext * tc, bool ns)
Definition at line 1070 of file miscregs.cc.
References ArmSystem::haveSecurity(), ArmSystem::highestELIs64(), MISCREG_BANKED, miscRegInfo, ns, and X86ISA::reg.
snsBankedIndex64()
int ArmISA::snsBankedIndex64 (MiscRegIndex reg, ThreadContext * tc)
Definition at line 1081 of file miscregs.cc.
References ThreadContext::getIsaPtr(), MISCREG_SCR, and ThreadContext::readMiscReg().
SPAlignmentCheckEnabled()
bool ArmISA::SPAlignmentCheckEnabled (ThreadContext * tc)
Definition at line 828 of file utility.cc.
References currEL(), EL0, EL1, EL2, EL3, MISCREG_SCTLR_EL1, MISCREG_SCTLR_EL2, MISCREG_SCTLR_EL3, panic, ThreadContext::readMiscReg(), sa, and sa0.
Referenced by msrMrs64IssBuild().
startupCPU()
void ArmISA::startupCPU (ThreadContext * tc, int cpuId) inline
Definition at line 105 of file utility.hh.
References ThreadContext::activate(), and copyRegs().
sub128()
static void ArmISA::sub128 (uint64_t * x0, uint64_t * x1, uint64_t a0, uint64_t a1, uint64_t b0, uint64_t b1) inline static
Definition at line 203 of file fplib.cc.
References MipsISA::a0.
Referenced by fp64_div(), and fp64_muladd().
SubBitUnion()
ArmISA::SubBitUnion (puswl , 24 , 20)
sveDecodePredCount()
unsigned int ArmISA::sveDecodePredCount (uint8_t imm, unsigned int num_elems)
Returns the actual number of elements active for PTRUE(S) instructions.
Parameters
imm 5-bit immediate encoding the predicate pattern.
num_elems Current number of elements per vector (depending on current vector length and element size).
Definition at line 852 of file sve.cc.
References imm.
Referenced by ArmISA::SveComplexIdxOp::SveComplexIdxOp().
sveDisasmPredCountImm()
std::string ArmISA::sveDisasmPredCountImm (uint8_t imm)
Returns the symbolic name associated with pattern imm for PTRUE(S) instructions.
Definition at line 820 of file sve.cc.
References sc_dt::to_string().
Referenced by ArmISA::SvePtrueOp::generateDisassembly(), ArmISA::SveElemCountOp::generateDisassembly(), and ArmISA::SveComplexIdxOp::SveComplexIdxOp().
sveExpandFpImmAddSub()
uint64_t ArmISA::sveExpandFpImmAddSub (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.5 or 1.0 (FADD, FSUB, FSUBR).
Parameters
imm 1-bit immediate.
size Encoding of the vector element size.
Returns
Encoding of the expanded value.
Definition at line 895 of file sve.cc.
References panic.
Referenced by ArmISA::SveComplexIdxOp::SveComplexIdxOp().
sveExpandFpImmMaxMin()
uint64_t ArmISA::sveExpandFpImmMaxMin (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.0 or 1.0 (FMAX, FMAXNM, FMIN, FMINNM).
Parameters
imm 1-bit immediate.
size Encoding of the vector element size.
Returns
Encoding of the expanded value.
Definition at line 917 of file sve.cc.
References panic.
Referenced by ArmISA::SveComplexIdxOp::SveComplexIdxOp().
sveExpandFpImmMul()
uint64_t ArmISA::sveExpandFpImmMul (uint8_t imm, uint8_t size)
Expand 1-bit floating-point immediate to 0.5 or 2.0 (FMUL).
Parameters
imm 1-bit immediate.
size Encoding of the vector element size.
Returns
Encoding of the expanded value.
Definition at line 936 of file sve.cc.
References panic.
Referenced by ArmISA::SveComplexIdxOp::SveComplexIdxOp().
svePredTypeToStr()
const char * ArmISA::svePredTypeToStr (SvePredType pt)
Returns the specifier for the predication type pt as a string.
Definition at line 47 of file sve.cc.
References MERGE, and ZERO.
Referenced by ArmISA::SveBinConstrPredOp::generateDisassembly().
testPredicate()
bool ArmISA::testPredicate (uint32_t nz, uint32_t c, uint32_t v, ConditionCode code) inline
Definition at line 70 of file utility.hh.
References c, COND_AL, COND_CC, COND_CS, COND_EQ, COND_GE, COND_GT, COND_HI, COND_LE, COND_LS, COND_LT, COND_MI, COND_NE, COND_PL, COND_UC, COND_VC, COND_VS, n, panic, v, z, and zeroRegisters().
truncPage()
Addr ArmISA::truncPage (Addr addr)
Definition at line 459 of file utility.cc.
References PageBytes.
Referenced by advancePC().
unflattenMiscReg()
int ArmISA::unflattenMiscReg (int reg)
Definition at line 1114 of file miscregs.cc.
References X86ISA::reg.
Referenced by mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), mcrrMrrc15TrapToHyp(), ArmISA::PMU::readMiscReg(), ArmISA::ISA::readMiscReg(), ArmISA::PMU::readMiscRegInt(), ArmISA::PMU::setMiscReg(), and ArmISA::ISA::setMiscReg().
unknownMode()
static bool ArmISA::unknownMode (OperatingMode mode) inline static
Definition at line 718 of file types.hh.
References MODE_ABORT, MODE_EL0T, MODE_EL1H, MODE_EL1T, MODE_EL2H, MODE_EL2T, MODE_EL3H, MODE_EL3T, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, and MODE_USER.
Referenced by badMode(), and illegalExceptionReturn().
unknownMode32()
static bool ArmISA::unknownMode32 (OperatingMode mode) inline static
Definition at line 744 of file types.hh.
References MODE_ABORT, MODE_FIQ, MODE_HYP, MODE_IRQ, MODE_MON, MODE_SVC, MODE_SYSTEM, MODE_UNDEFINED, and MODE_USER.
Referenced by badMode32(), ArmISA::ArmStaticInst::getPSTATEFromPSR(), and illegalExceptionReturn().
unsignedRecipEstimate()
uint32_t ArmISA::unsignedRecipEstimate (uint32_t op)
Definition at line 879 of file vfp.cc.
References bits(), bitsToFp(), fpToBits(), recipEstimate(), and ULL.
Referenced by vfpFpToFixed().
unsignedRSqrtEstimate()
uint32_t ArmISA::unsignedRSqrtEstimate (uint32_t op)
Definition at line 804 of file vfp.cc.
References bits(), bitsToFp(), fpToBits(), recipSqrtEstimate(), and ULL.
Referenced by vfpFpToFixed().
VAddrImpl()
Addr ArmISA::VAddrImpl (Addr a) inline
Definition at line 85 of file isa_traits.hh.
References VAddrImplMask.
VAddrOffset()
Addr ArmISA::VAddrOffset (Addr a) inline
Definition at line 87 of file isa_traits.hh.
References PageOffset.
VAddrVPN()
Addr ArmISA::VAddrVPN (Addr a) inline
Definition at line 86 of file isa_traits.hh.
References PageShift.
vcvtFpDFpH()
uint16_t ArmISA::vcvtFpDFpH (FPSCR & fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, double op)
Definition at line 575 of file vfp.cc.
References fpToBits(), and vcvtFpFpH().
vcvtFpFpH()
static uint16_t ArmISA::vcvtFpFpH (FPSCR & fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, uint64_t opBits, bool isDouble) inline static
Definition at line 395 of file vfp.cc.
References bits(), mask, mode, sc_dt::neg(), replaceBits(), rMode, VfpRoundDown, VfpRoundNearest, and VfpRoundUpward.
Referenced by vcvtFpDFpH(), and vcvtFpSFpH().
vcvtFpHFp()
static uint64_t ArmISA::vcvtFpHFp (FPSCR & fpscr, bool defaultNan, bool ahp, uint16_t op, bool isDouble) inline static
Definition at line 583 of file vfp.cc.
References bits(), mask, sc_dt::neg(), and replaceBits().
Referenced by vcvtFpHFpD(), and vcvtFpHFpS().
vcvtFpHFpD()
double ArmISA::vcvtFpHFpD (FPSCR & fpscr, bool defaultNan, bool ahp, uint16_t op)
Definition at line 645 of file vfp.cc.
References bitsToFp(), and vcvtFpHFp().
vcvtFpHFpS()
float ArmISA::vcvtFpHFpS (FPSCR & fpscr, bool defaultNan, bool ahp, uint16_t op)
Definition at line 655 of file vfp.cc.
References bitsToFp(), and vcvtFpHFp().
vcvtFpSFpH()
uint16_t ArmISA::vcvtFpSFpH (FPSCR & fpscr, bool flush, bool defaultNan, uint32_t rMode, bool ahp, float op)
Definition at line 567 of file vfp.cc.
References fpToBits(), and vcvtFpFpH().
vfp_modified_imm()
static uint64_t ArmISA::vfp_modified_imm (uint8_t data, FpDataType dtype) inline static
Definition at line 166 of file pred_inst.hh.
References bits(), data, Fp16, Fp32, Fp64, and panic.
vfpFlushToZero() [1/2]
template<class fpType > static void ArmISA::vfpFlushToZero (FPSCR & fpscr, fpType & op) inline static
Definition at line 140 of file vfp.hh.
References flushToZero.
Referenced by vfpFlushToZero().
vfpFlushToZero() [2/2]
template<class fpType > static void ArmISA::vfpFlushToZero (FPSCR & fpscr, fpType & op1, fpType & op2) inline static
Definition at line 149 of file vfp.hh.
References vfpFlushToZero().
vfpFpToFixed()
template<typename T > uint64_t ArmISA::vfpFpToFixed (T val, bool isSigned, uint8_t width, uint8_t imm, bool useRmode = true, VfpRoundingMode roundMode = VfpRoundZero, bool aarch64 = false)
Definition at line 265 of file vfp.hh.
References aarch64, FeAllExceptions, FeInexact, FeInvalid, FeRoundDown, FeRoundNearest, FeRoundUpward, FeRoundZero, HsailISA::fpclassify(), fpRecipEstimate(), fprSqrtEstimate(), fpStandardFPSCRValue(), imm, LL, mask, X86ISA::op, panic, setFPExceptions(), unsignedRecipEstimate(), unsignedRSqrtEstimate(), X86ISA::val, VfpRoundAway, VfpRoundDown, VfpRoundNearest, VfpRoundUpward, VfpRoundZero, vfpSFixedToFpD(), vfpSFixedToFpS(), vfpUFixedToFpD(), vfpUFixedToFpS(), and width.
vfpSFixedToFpD()
double ArmISA::vfpSFixedToFpD (bool flush, bool defaultNan, int64_t val, uint8_t width, uint8_t imm)
Definition at line 722 of file vfp.cc.
References FeAllExceptions, FeRoundNearest, fixDivDest(), mask, panic, and X86ISA::scale.
Referenced by vfpFpToFixed().
vfpSFixedToFpS()
float ArmISA::vfpSFixedToFpS (bool flush, bool defaultNan, int64_t val, uint8_t width, uint8_t imm)
Definition at line 683 of file vfp.cc.
References FeAllExceptions, FeRoundNearest, fixDivDest(), mask, panic, and X86ISA::scale.
Referenced by vfpFpToFixed().
vfpUFixedToFpD()
double ArmISA::vfpUFixedToFpD (bool flush, bool defaultNan, uint64_t val, uint8_t width, uint8_t imm)
Definition at line 703 of file vfp.cc.
References FeAllExceptions, FeRoundNearest, fixDivDest(), panic, and X86ISA::scale.
Referenced by vfpFpToFixed().
vfpUFixedToFpS()
float ArmISA::vfpUFixedToFpS (bool flush, bool defaultNan, uint64_t val, uint8_t width, uint8_t imm)
Definition at line 665 of file vfp.cc.
References FeAllExceptions, FeRoundNearest, fixDivDest(), panic, and X86ISA::scale.
Referenced by vfpFpToFixed().
virtvalid()
bool ArmISA::virtvalid (ThreadContext * tc, Addr vaddr)
Definition at line 108 of file vtophys.cc.
References try_translate().
Referenced by ArmISA::RemoteGDB::acc(), and PteAddr().
vtophys() [1/2]
Addr ArmISA::vtophys (Addr vaddr) inline
Definition at line 62 of file vtophys.cc.
References fatal.
Referenced by PteAddr().
vtophys() [2/2]
Addr ArmISA::vtophys (ThreadContext * tc, Addr vaddr) inline
Definition at line 97 of file vtophys.cc.
References panic, and try_translate().
writeVecElem()
void ArmISA::writeVecElem (VReg * dest, XReg src, int index, int eSize) inline
Write a single NEON vector element leaving the others untouched.
Definition at line 60 of file neon64_mem.hh.
References ArmISA::VReg::hi, and ArmISA::VReg::lo.
zeroRegisters()
template<class TC > void ArmISA::zeroRegisters (TC * tc)
Function to insure ISA semantics about 0 registers.
Parameters
tc The thread context.
Referenced by testPredicate().
Variable Documentation
a
Bitfield< 1 > ArmISA::a
Definition at line 65 of file miscregs_types.hh.
Referenced by AddrRange::addIntlvBits(), ArmISA::Crypto::aesFFMul(), sc_dt::sc_uint_subref_r::and_reduce(), sc_dt::sc_int_subref_r::and_reduce(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), SMMUv3SlaveInterface::atsSlaveRecvAtomic(), TAGE_SC_L_TAGE::calcDep(), MuxingKvmGic::clearBankedDistRange(), MuxingKvmGic::clearDistRange(), sc_dt::sc_bitref< X >::clone(), SMMUTranslationProcess::completePrefetch(), SMMUTranslationProcess::completeTransaction(), IGbE::TxDescCache::completionWriteback(), sc_dt::convert_to_bin(), sc_dt::convert_to_fmt(), MuxingKvmGic::copyBankedDistRange(), MuxingKvmGic::copyDistRange(), SparcISA::TLB::demapPage(), SMMUProcess::doDelay(), SMMUProcess::doRead(), ItsProcess::doRead(), SMMUProcess::doSleep(), SMMUProcess::doWrite(), ItsProcess::doWrite(), RiscvISA::AtomicGenericOp< T >::execute(), ArmISA::AtomicGeneric2Op< T >::execute(), ArmISA::AtomicGeneric3Op< T >::execute(), ArmISA::AtomicGenericPair3Op< T >::execute(), sc_dt::scfx_ieee_double::exponent(), sc_dt::scfx_ieee_float::exponent(), TAGE_SC_L_TAGE::F(), fp16_cvtf(), fp16_process_NaN(), fp32_cvtf(), fp32_process_NaN(), fp64_cvtf(), fp64_process_NaN(), fpMax(), fpMaxNum(), fpMin(), fpMinNum(), MultiperspectivePerceptron::ACYCLIC::getHash(), MultiperspectivePerceptron::MODHIST::getHash(), MultiperspectivePerceptron::MODPATH::getHash(), MultiperspectivePerceptron::GHISTMODPATH::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), AtomicSimpleCPU::getInstPort(), MPP_TAGE::handleAllocAndUReset(), MultiperspectivePerceptron::GHIST::hash(), MultiperspectivePerceptron::MPPBranchInfo::hash1(), System::initState(), QTIsaac< ALPHA >::isaac(), MasterPort::isSnooping(), TimingSimpleCPU::isSquashed(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), sc_dt::lrotate(), SMMUCommandExecProcess::main(), SMMUTranslationProcess::main(), ItsCommand::main(), sc_dt::scfx_ieee_double::mantissa1(), MemoryImage::mask(), SMMUv3::masterRecvReqRetry(), SMMUv3::masterTableWalkRecvReqRetry(), MathExpr::MathExpr(), MemoryImage::offset(), sc_dt::operator&(), sc_dt::operator&=(), SNHash::operator()(), Net::operator<<(), sc_dt::sc_proxy< sc_subref_r< X > >::operator<<(), sc_core::operator<<(), sc_dt::sc_bitref< X >::operator=(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_subref< X >::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator>>(), sc_dt::operator^(), sc_dt::operator^=(), sc_dt::operator|(), sc_dt::operator|=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator~(), sc_dt::sc_uint_subref_r::or_reduce(), sc_dt::sc_int_subref_r::or_reduce(), sc_dt::print_other(), MasterPort::printAddr(), StackDistCalc::printStack(), AnnotateDumpCallback::process(), SMMUv3::processCommands(), QTIsaac< ALPHA >::randinit(), SMMUv3SlaveInterface::recvAtomic(), Gicv3Its::recvReqRetry(), AddrRange::removeIntlvBits(), sc_dt::reverse(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), sc_dt::rrotate(), sc_dt::rshift(), sc_dt::sc_abs(), sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref(), sc_dt::sc_int_base::sc_int_base(), sc_dt::sc_int_subref::sc_int_subref(), SC_MODULE(), sc_dt::sc_signed_subref::sc_signed_subref(), sc_dt::sc_uint_base::sc_uint_base(), sc_dt::sc_uint_subref::sc_uint_subref(), sc_dt::sc_unsigned_subref::sc_unsigned_subref(), sc_dt::scfx_is_equal(), sc_dt::scfx_rep::scfx_rep(), tlm::tlm_dmi::set_granted_access(), Trace::InstRecord::setMem(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), swap_byte(), System::System(), ItsProcess::terminate(), TEST(), tlm::tlm_to_hostendian_single(), sc_dt::sc_bit::to_char(), sc_dt::sc_uint_subref_r::to_double(), sc_dt::sc_uint_subref_r::to_int(), sc_dt::sc_uint_subref_r::to_int64(), sc_dt::sc_uint_subref_r::to_long(), sc_dt::sc_uint_subref_r::to_string(), sc_dt::sc_int_subref_r::to_string(), sc_dt::sc_uint_subref_r::to_uint(), sc_dt::sc_uint_subref_r::to_uint64(), sc_dt::sc_uint_subref_r::to_ulong(), sc_dt::uint64_to_double(), MultiperspectivePerceptron::update(), StackDistCalc::verifyStackDist(), SparcISA::TLB::writeSfsr(), sc_dt::sc_uint_subref_r::xor_reduce(), sc_dt::sc_int_subref_r::xor_reduce(), QTIsaac< ALPHA >::randctx::~randctx(), sc_dt::sc_fxnum_fast_subref::~sc_fxnum_fast_subref(), and sc_dt::sc_fxnum_subref::~sc_fxnum_subref().
a1
Bitfield< 22 > ArmISA::a1
Definition at line 474 of file miscregs_types.hh.
Referenced by TAGE_SC_L_TAGE::F(), mul62x62(), and SC_MODULE().
aarch64
Bitfield<34> ArmISA::aarch64
Definition at line 91 of file types.hh.
Referenced by EndBitUnion(), ArmSemihosting::readString(), ArmSemihosting::semiExit(), and vfpFpToFixed().
advsimd
Bitfield<23, 20> ArmISA::advsimd
Definition at line 174 of file miscregs_types.hh.
Referenced by ArmISA::ArmStaticInst::disabledFault().
advSimdHalfPrecision
Bitfield<23, 20> ArmISA::advSimdHalfPrecision
Definition at line 455 of file miscregs_types.hh.
advSimdInteger
Bitfield<15, 12> ArmISA::advSimdInteger
Definition at line 453 of file miscregs_types.hh.
advSimdLoadStore
Bitfield<11, 8> ArmISA::advSimdLoadStore
Definition at line 452 of file miscregs_types.hh.
advSimdRegisters
ArmISA::advSimdRegisters
Definition at line 439 of file miscregs_types.hh.
advSimdSinglePrecision
Bitfield<19, 16> ArmISA::advSimdSinglePrecision
Definition at line 454 of file miscregs_types.hh.
aes
Bitfield<3, 0> ArmISA::aes
Definition at line 103 of file miscregs_types.hh.
afe
Bitfield<29> ArmISA::afe
Definition at line 316 of file miscregs_types.hh.
ahp
Bitfield<26> ArmISA::ahp
Definition at line 424 of file miscregs_types.hh.
aif
Bitfield<8, 6> ArmISA::aif
Definition at line 68 of file miscregs_types.hh.
amo
Bitfield<5> ArmISA::amo
Definition at line 267 of file miscregs_types.hh.
amu
Bitfield<47, 44> ArmISA::amu
Definition at line 168 of file miscregs_types.hh.
apa
Bitfield<7, 4> ArmISA::apa
Definition at line 116 of file miscregs_types.hh.
api
Bitfield<11, 8> ArmISA::api
Definition at line 115 of file miscregs_types.hh.
ApsrMask
const uint32_t ArmISA::ApsrMask = CpsrMaskQ | CondCodesMask | 0x000001D0 static
Definition at line 1884 of file miscregs.hh.
ArgumentReg0
const int ArmISA::ArgumentReg0 = 0
Definition at line 116 of file registers.hh.
Referenced by ArmProcess::argsInit(), PowerLinuxProcess::getSyscallArg(), PowerProcess::getSyscallArg(), ArmProcess32::getSyscallArg(), ArmProcess64::getSyscallArg(), PowerLinuxProcess::setSyscallArg(), PowerProcess::setSyscallArg(), ArmProcess32::setSyscallArg(), and ArmProcess64::setSyscallArg().
ArgumentReg1
const int ArmISA::ArgumentReg1 = 1
Definition at line 117 of file registers.hh.
Referenced by ArmProcess::argsInit().
ArgumentReg2
const int ArmISA::ArgumentReg2 = 2
Definition at line 118 of file registers.hh.
Referenced by ArmProcess::argsInit().
ArgumentReg3
const int ArmISA::ArgumentReg3 = 3
Definition at line 119 of file registers.hh.
as
Bitfield< 36 > ArmISA::as
Definition at line 481 of file miscregs_types.hh.
asedis
Bitfield<31> ArmISA::asedis
Definition at line 391 of file miscregs_types.hh.
asid
ArmISA::asid
Definition at line 587 of file miscregs_types.hh.
Referenced by ArmISA::TableWalker::haveLargeAsid64(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), ArmISA::TlbEntry::match(), ArmISA::TLBIASID::operator()(), ArmISA::ITLBIASID::operator()(), ArmISA::DTLBIASID::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::ITLBIMVA::operator()(), ArmISA::DTLBIMVA::operator()(), Request::setAsid(), ArmISA::ISA::setMiscReg(), Request::setVirt(), SMMUTranslationProcess::walkCacheLookup(), TimingSimpleCPU::writeMem(), ARMArchTLB::~ARMArchTLB(), SMMUTLB::~SMMUTLB(), and WalkCache::~WalkCache().
asidbits
Bitfield<7, 4> ArmISA::asidbits
Definition at line 131 of file miscregs_types.hh.
at
Bitfield<35, 32> ArmISA::at
Definition at line 153 of file miscregs_types.hh.
Referenced by HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >::AtomicInstBase(), HsailISA::constructAtomic(), HsailISA::decodeAtomic(), HsailISA::decodeAtomicNoRet(), HsailISA::LdInstBase< MemDataType::CType, DestDataType::OperandType, AddrOperandType >::LdInstBase(), RegOrImmOperand< RegOperand, T >::RegOrImmOperand(), HsailISA::StInstBase< MemDataType, SrcDataType::OperandType, AddrOperandType >::StInstBase(), and X86KvmCPU::updateThreadContextMSRs().
atomic
Bitfield<23, 20> ArmISA::atomic
Definition at line 99 of file miscregs_types.hh.
Referenced by System::isAtomicMode(), and MemTest::sendPkt().
attr
ArmISA::attr
Definition at line 625 of file miscregs_types.hh.
Referenced by sc_gem5::Object::get_attribute(), KvmDevice::getAttrPtr(), KvmKernelGicV2::getGicReg(), KvmDevice::hasAttr(), X86ISA::installSegDesc(), ArmISA::TableWalker::memAttrsAArch64(), ArmISA::TableWalker::memAttrsLPAE(), sc_core::sc_attr_cltn::operator[](), sc_core::sc_attr_cltn::remove(), KvmDevice::setAttr(), ArmISA::TLB::setAttr(), KvmDevice::setAttrPtr(), setContextSegment(), KvmKernelGicV2::setGicReg(), setKvmSegmentReg(), ArmISA::ISA::setMiscReg(), X86ISA::TLB::translate(), and X86ISA::GpuTLB::translate().
aw
Bitfield<5> ArmISA::aw
Definition at line 306 of file miscregs_types.hh.
b
Bitfield<7> ArmISA::b
Definition at line 355 of file miscregs_types.hh.
Referenced by ArmISA::Crypto::aesFFMul(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::b_and(), sc_dt::b_or(), sc_dt::b_xor(), divCeil(), BaseDynInst< Impl >::effAddrValid(), sc_gem5::Scheduler::elaborationDone(), execveFunc(), sc_gem5::Port::finalize(), findRegDataType(), fp16_scale(), fp32_scale(), fp64_scale(), fpAdd(), fpAddD(), fpAddS(), fpDiv(), fpDivD(), fpDivS(), fpMax(), fpMaxNum(), fpMin(), fpMinNum(), fpMul(), fpMulD(), fpMulS(), fpRecps(), fpRecpsS(), fpRSqrts(), fpRSqrtsS(), fpSub(), fpSubD(), fpSubS(), sc_dt::sc_fxnum_fast::get_slice(), PciDevice::getBAR(), BaseRemoteGDB::getbyte(), MultiperspectivePerceptron::MODHIST::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), Network::getNumNodes(), PerfectSwitch::getOutLinks(), MultiperspectivePerceptron::GHIST::hash(), sc_core::sc_inout< bool >::initialize(), MultiperspectivePerceptron::ThreadData::insertRecency(), QTIsaac< ALPHA >::isaac(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), MathExpr::MathExpr(), MPP_TAGE::MPP_TAGE(), mul64x32(), tlm::tlm_bool< D >::operator bool(), sc_dt::operator<<(), sc_dt::sc_uint_bitref::operator=(), sc_dt::sc_int_bitref::operator=(), Gicv3Its::pageAddress(), tlm::circular_buffer< T >::poke_data(), sc_dt::print_other(), AnnotateDumpCallback::process(), DRAMCtrl::Rank::processRefreshEvent(), QTIsaac< ALPHA >::randinit(), DRAMCtrl::Rank::Rank(), tlm_utils::callback_binder_fw< tlm::tlm_base_protocol_types >::register_port(), QTIsaac< ALPHA >::rngstep(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), sc_dt::rshift(), sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), sc_dt::sc_int_bitref::sc_int_bitref(), SC_MODULE(), sc_dt::sc_uint_bitref::sc_uint_bitref(), sc_dt::sc_fxnum_bitref::scan(), sc_dt::sc_fxnum_fast_bitref::scan(), sc_dt::sc_bit::scan(), sc_dt::sc_uint_bitref::scan(), sc_dt::sc_int_bitref::scan(), sc_dt::scfx_is_equal(), DRAMCtrl::Rank::scheduleWakeUpEvent(), Network::setFromNetQueue(), Network::setToNetQueue(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), TAGE_SC_L_TAGE::TAGE_SC_L_TAGE(), BitUnionData::templatedFunction(), sc_dt::sc_bit::to_char(), to_number(), sc_dt::sc_bit::to_value(), sc_dt::vec_from_str(), NetworkInterface::wakeup(), MPP_StatisticalCorrector::BranchInfo::~BranchInfo(), TAGEBase::BranchInfo::~BranchInfo(), LTAGE::LTageBranchInfo::~LTageBranchInfo(), QTIsaac< ALPHA >::randctx::~randctx(), and TAGE::TageBranchInfo::~TageBranchInfo().
bbm
Bitfield<55, 52> ArmISA::bbm
Definition at line 149 of file miscregs_types.hh.
bigend
Bitfield<11, 8> ArmISA::bigend
Definition at line 130 of file miscregs_types.hh.
bigendEL0
Bitfield<19, 16> ArmISA::bigendEL0
Definition at line 128 of file miscregs_types.hh.
bigThumb
Bitfield<35> ArmISA::bigThumb
Definition at line 90 of file types.hh.
bottom2
Bitfield<1, 0> ArmISA::bottom2
Definition at line 67 of file types.hh.
brps
Bitfield<15, 12> ArmISA::brps
Definition at line 83 of file miscregs_types.hh.
bsu
Bitfield<11, 10> ArmISA::bsu
Definition at line 261 of file miscregs_types.hh.
c
Bitfield< 29 > ArmISA::c
Definition at line 53 of file miscregs_types.hh.
Referenced by Trace::TarmacParserRecord::advanceTrace(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::sc_bv_base::assign_from_string(), sc_dt::sc_lv_base::assign_from_string(), sc_gem5::Scheduler::clear(), SrcClockDomain::clockPeriod(), sc_gem5::Scheduler::current(), Clocked::cyclesToTicks(), sc_dt::div_scfx_rep(), Trace::Logger::dump(), BaseRemoteGDB::encodeBinaryData(), ArmISA::AtomicGeneric3Op< T >::execute(), ArmISA::AtomicGenericPair3Op< T >::execute(), AddrRangeMap< AbstractMemory *, 1 >::find(), fp64_div(), fp64_sqrt(), FUPool::FUPool(), SystemCounter::getHypControl(), BloomFilter::Bulk::hash(), PS2Device::hostDataAvailable(), PS2Device::hostRegDataAvailable(), CPA::hwWe(), sc_gem5::Kernel::init(), MultiperspectivePerceptron::insert(), PS2Keyboard::keyPress(), sc_dt::lsh_scfx_rep(), PowerISA::IntOp::makeCRField(), PowerISA::FloatOp::makeCRField(), sc_dt::mult_scfx_rep(), sc_dt::neg_scfx_rep(), LinearEquation::operator*=(), sc_dt::sc_fxval::operator++(), sc_dt::sc_fxval_fast::operator++(), sc_dt::sc_fxnum::operator++(), sc_dt::sc_fxnum_fast::operator++(), sc_dt::scfx_string::operator+=(), sc_dt::sc_fxval::operator--(), sc_dt::sc_fxval_fast::operator--(), sc_dt::sc_fxnum::operator--(), sc_dt::sc_fxnum_fast::operator--(), sc_dt::operator<<(), sc_core::sc_out< bool >::operator=(), sc_dt::sc_fix::operator~(), sc_dt::sc_ufix::operator~(), sc_dt::sc_fix_fast::operator~(), sc_dt::sc_ufix_fast::operator~(), sc_dt::overflow(), sc_dt::overflow_scfx_rep(), MathExpr::parse(), SparcISA::SparcStaticInst::passesCondition(), Printk(), AnnotateDumpCallback::process(), HardBreakpoint::process(), tlm::tlm_endian_context_pool::push(), sc_dt::quantization(), sc_dt::quantization_scfx_rep(), QTIsaac< ALPHA >::randinit(), Terminal::readData(), ArmSemihosting::readString(), BaseRemoteGDB::recv(), SerialDevice::regInterfaceCallback(), VirtIODeviceBase::registerKickCallback(), ClockDomain::registerWithClockDomain(), sc_gem5::Kernel::regStats(), sc_dt::rsh_scfx_rep(), sc_dt::sc_abs(), SC_MODULE(), sc_dt::sc_logic::scan(), sc_dt::sc_bitref< X >::scan(), BaseRemoteGDB::send(), IdeDisk::setController(), Message::setMsgCounter(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), sc_gem5::Kernel::startup(), sc_gem5::Kernel::stopWork(), Trace::TarmacBaseRecord::TarmacBaseRecord(), TEST(), testPredicate(), to_lower(), to_number(), PortProxy::tryReadString(), PS2Device::unserialize(), DerivedClockDomain::updateClockPeriod(), MultiperspectivePerceptronTAGE::updatePartial(), Stats::validateStatName(), sc_dt::vec_from_str(), Terminal::write(), Terminal::writeData(), and QTIsaac< ALPHA >::randctx::~randctx().
ccidx
Bitfield<23, 20> ArmISA::ccidx
Definition at line 156 of file miscregs_types.hh.
ccRegName
const char* const ArmISA::ccRegName[NUM_CCREGS]
Initial value:
= {
    "nz",
    "c",
    "v",
    "ge",
    "fp",
    "zero"
}
Definition at line 55 of file ccregs.hh.
Referenced by ArmISA::ArmStaticInst::printCCReg(), and Trace::TarmacTracerRecord::TraceRegEntry::updateCC().
cd
Bitfield<32> ArmISA::cd
Definition at line 238 of file miscregs_types.hh.
Referenced by SMMUTranslationProcess::doReadCD(), and SMMUTranslationProcess::findConfig().
cm
Bitfield<13> ArmISA::cm
Definition at line 402 of file miscregs_types.hh.
Referenced by ArmISA::DataAbort::annotate(), and ArmISA::DataAbort::iss().
cnp
Bitfield<3, 0> ArmISA::cnp
Definition at line 161 of file miscregs_types.hh.
cond
ArmISA::cond
Definition at line 63 of file types.hh.
Referenced by TimingExprIf::eval(), HsailISA::CbrInstBase< SRegOperand >::execute(), AddrRangeMap< AbstractMemory *, 1 >::find(), HsailISA::CbrInstBase< SRegOperand >::generateDisassembly(), ArmISA::FpRegRegRegCondOp::generateDisassembly(), and ArmISA::ArmFault::setSyndrome().
condCode
Bitfield<31, 28> ArmISA::condCode
Definition at line 121 of file types.hh.
Referenced by ArmISA::BranchImmCond64::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), and ArmISA::ArmFault::setSyndrome().
CondCodesMask
const uint32_t ArmISA::CondCodesMask = 0xF00F0000 static
Definition at line 1875 of file miscregs.hh.
cp0
ArmISA::cp0
Definition at line 293 of file miscregs_types.hh.
cp1
Bitfield< 3, 2 > ArmISA::cp1
Definition at line 292 of file miscregs_types.hh.
cp10
Bitfield< 21, 20 > ArmISA::cp10
Definition at line 283 of file miscregs_types.hh.
cp11
Bitfield< 23, 22 > ArmISA::cp11
Definition at line 282 of file miscregs_types.hh.
cp12
Bitfield< 25, 24 > ArmISA::cp12
Definition at line 281 of file miscregs_types.hh.
cp13
Bitfield< 27, 26 > ArmISA::cp13
Definition at line 280 of file miscregs_types.hh.
cp15ben
Bitfield<5> ArmISA::cp15ben
Definition at line 361 of file miscregs_types.hh.
cp2
Bitfield< 5, 4 > ArmISA::cp2
Definition at line 291 of file miscregs_types.hh.
cp3
Bitfield< 7, 6 > ArmISA::cp3
Definition at line 290 of file miscregs_types.hh.
cp4
Bitfield< 9, 8 > ArmISA::cp4
Definition at line 289 of file miscregs_types.hh.
cp5
Bitfield< 11, 10 > ArmISA::cp5
Definition at line 288 of file miscregs_types.hh.
cp6
Bitfield< 13, 12 > ArmISA::cp6
Definition at line 287 of file miscregs_types.hh.
cp7
Bitfield< 15, 14 > ArmISA::cp7
Definition at line 286 of file miscregs_types.hh.
cp8
Bitfield< 17, 16 > ArmISA::cp8
Definition at line 285 of file miscregs_types.hh.
cp9
Bitfield< 19, 18 > ArmISA::cp9
Definition at line 284 of file miscregs_types.hh.
cpNum
Bitfield<11, 8> ArmISA::cpNum
Definition at line 158 of file types.hh.
CpsrMask
const uint32_t ArmISA::CpsrMask = ApsrMask | 0x00F003DF static
Definition at line 1887 of file miscregs.hh.
CpsrMaskQ
const uint32_t ArmISA::CpsrMaskQ = 0x08000000 static
Definition at line 1876 of file miscregs.hh.
Referenced by ArmISA::ISA::setMiscReg().
crc32
Bitfield<19, 16> ArmISA::crc32
Definition at line 100 of file miscregs_types.hh.
csv2
Bitfield<59, 56> ArmISA::csv2
Definition at line 166 of file miscregs_types.hh.
csv3
ArmISA::csv3
Definition at line 165 of file miscregs_types.hh.
ctx_cmps
Bitfield<31, 28> ArmISA::ctx_cmps
Definition at line 81 of file miscregs_types.hh.
CurThreadInfoImplemented
const bool ArmISA::CurThreadInfoImplemented = false
Definition at line 101 of file isa_traits.hh.
CurThreadInfoReg
const int ArmISA::CurThreadInfoReg = -1
Definition at line 102 of file isa_traits.hh.
cwg
Bitfield<27,24> ArmISA::cwg
Definition at line 614 of file miscregs_types.hh.
d
Bitfield<9> ArmISA::d
Definition at line 63 of file miscregs_types.hh.
Referenced by TaggedPrefetcher::calculatePrefetch(), IrregularStreamBufferPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), DVFSHandler::clkPeriodAtPerfLevel(), sc_dt::compare_unsigned(), Wavefront::computeActualWgSz(), VirtQueue::consumeDescriptor(), RefCountingPtr< MinorDynInst >::copy(), sc_dt::div_on_help_signed(), sc_dt::div_on_help_unsigned(), Trace::Logger::dprintf(), Trace::Logger::dump(), VirtQueue::dump(), DVFSHandler::DVFSHandler(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execSt(), Process::findDriver(), sc_core::sc_time::from_seconds(), LSQ< Impl >::SplitDataRequest::handleIprRead(), I2CBus::I2CBus(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::initiateAcc(), sc_dt::sc_unsigned::iszero(), tlm::tlm_bool< D >::make_uchar_array(), sc_dt::mod_on_help_signed(), sc_dt::mod_on_help_unsigned(), sc_dt::mul_on_help_signed(), sc_dt::mul_on_help_unsigned(), VirtQueue::onNotify(), Arguments::operator T(), CopyEngineReg::Reg< uint64_t >::operator()(), iGbReg::Regs::Reg< uint64_t >::operator()(), operator<<(), CopyEngineReg::Reg< uint64_t >::operator=(), sc_dt::scfx_ieee_double::operator=(), iGbReg::Regs::Reg< uint64_t >::operator=(), AddrOperandBase::parseAddr(), DVFSHandler::perfLevel(), AnnotateDumpCallback::process(), QTIsaac< ALPHA >::randinit(), ComputeUnit::ReadyWorkgroup(), DistIface::RecvScheduler::resumeRecvTicks(), VoltageDomain::sanitiseVoltages(), SC_MODULE(), sc_core::sc_set_time_resolution(), sc_core::sc_time::sc_time(), sc_dt::scfx_ieee_double::scfx_ieee_double(), RefCountingPtr< MinorDynInst >::set(), sc_gem5::TraceFile::set_time_unit(), Trace::InstRecord::setData(), OutputDirectory::setDirectory(), Topology::shortest_path_to_node(), QTIsaac< ALPHA >::shuffle(), tlm::tlm_from_hostendian_word(), tlm::tlm_to_hostendian_word(), VirtIOConsole::TermRecvQueue::trySend(), DVFSHandler::UpdateEvent::updatePerfLevel(), sc_dt::vec_reverse(), sc_dt::vec_to_char(), DVFSHandler::voltageAtPerfLevel(), I2CBus::write(), VGic::writeCtrl(), and QTIsaac< ALPHA >::randctx::~randctx().
d32dis
Bitfield<30> ArmISA::d32dis
Definition at line 390 of file miscregs_types.hh.
daif
Bitfield<9, 6> ArmISA::daif
Definition at line 69 of file miscregs_types.hh.
Referenced by ArmISA::ISA::readMiscReg(), and ArmISA::ISA::setMiscReg().
dataRAMSetup
Bitfield<5> ArmISA::dataRAMSetup
Definition at line 594 of file miscregs_types.hh.
dataRAMSlice
Bitfield<11,10> ArmISA::dataRAMSlice
Definition at line 597 of file miscregs_types.hh.
dc
Bitfield<12> ArmISA::dc
Definition at line 260 of file miscregs_types.hh.
dCacheLineSize
Bitfield<19,16> ArmISA::dCacheLineSize
Definition at line 612 of file miscregs_types.hh.
debugver
Bitfield<3, 0> ArmISA::debugver
Definition at line 86 of file miscregs_types.hh.
decodeInst
StaticInstPtr ArmISA::decodeInst(ExtMachInst)
decoderFault
ArmISA::decoderFault
Definition at line 72 of file types.hh.
defaultNaN
Bitfield<7, 4> ArmISA::defaultNaN
Definition at line 451 of file miscregs_types.hh.
dit
Bitfield<51, 48> ArmISA::dit
Definition at line 167 of file miscregs_types.hh.
Referenced by DVFSHandler::DVFSHandler(), and VoltageDomain::sanitiseVoltages().
divide
Bitfield<19, 16> ArmISA::divide
Definition at line 443 of file miscregs_types.hh.
Referenced by SC_MODULE().
dn
Bitfield<25> ArmISA::dn
Definition at line 423 of file miscregs_types.hh.
domain
Bitfield<7, 4> ArmISA::domain
Definition at line 397 of file miscregs_types.hh.
Referenced by ArmISA::TLB::flushAll(), ArmISA::AbortFault< DataAbort >::getFsr(), ArmISA::TlbEntry::serialize(), socketFunc(), socketpairFunc(), and ArmISA::TlbTestInterface::~TlbTestInterface().
doublelock
Bitfield<39, 36> ArmISA::doublelock
Definition at line 79 of file miscregs_types.hh.
doublePrecision
Bitfield<11, 8> ArmISA::doublePrecision
Definition at line 441 of file miscregs_types.hh.
dp
Bitfield<47, 44> ArmISA::dp
Definition at line 94 of file miscregs_types.hh.
Referenced by QueuedPrefetcher::nextPrefetchReadyTime(), QueuedPrefetcher::processMissingTranslations(), PacketQueue::sendDeferredPacket(), and QueuedPrefetcher::translationComplete().
dpb
Bitfield<3, 0> ArmISA::dpb
Definition at line 117 of file miscregs_types.hh.
ds0
Bitfield<16> ArmISA::ds0
Definition at line 553 of file miscregs_types.hh.
ds1
Bitfield<17> ArmISA::ds1
Definition at line 554 of file miscregs_types.hh.
dz
Bitfield<19> ArmISA::dz
Definition at line 333 of file miscregs_types.hh.
dzc
Bitfield<1> ArmISA::dzc
Definition at line 407 of file miscregs_types.hh.
dze
Bitfield< 9 > ArmISA::dze
Definition at line 345 of file miscregs_types.hh.
e
Bitfield<9> ArmISA::e
Definition at line 64 of file miscregs_types.hh.
Referenced by sc_gem5::Object::addChildEvent(), sc_gem5::SensitivityEvents::addEvent(), System::addFuncEventOrPanic(), System::addKernelFuncEventOrPanic(), ARMArchTLB::ARMArchTLB(), Iris::BaseCPU::BaseCPU(), sc_gem5::Module::beforeEndOfElaboration(), Stats::Hdf5::beginGroup(), SwitchingFiber::checkExpected(), BaseRemoteGDB::cmd_query_var(), ConfigCache::ConfigCache(), SMMUTranslationProcess::configCacheLookup(), SMMUTranslationProcess::configCacheUpdate(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::construct(), my_extension::copy_from(), sc_gem5::Object::delChildEvent(), tlm_utils::time_ordered_list< std::pair >::delete_top(), DmaReadFifo::DmaReadFifo(), ThermalModel::doStep(), PCEventQueue::dump(), dumpDmesgEntry(), LSQUnit< Impl >::dumpInsts(), X86KvmCPU::dumpMSRs(), sc_gem5::DynamicSensitivity::DynamicSensitivity(), sc_gem5::Module::endOfElaboration(), sc_gem5::Module::endOfSimulation(), RubySystem::enqueueRubyEvent(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::ExtensionPool(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::free(), sc_dt::scfx_rep::from_string(), sc_dt::sc_fxval_fast::from_string(), CacheMemory::getDataLatency(), Sequencer::handleLlsc(), SMMUTranslationProcess::ifcTLBLookup(), SMMUTranslationProcess::ifcTLBUpdate(), tlm_utils::time_ordered_list< std::pair >::insert(), SMMUTLB::invalidateASID(), ARMArchTLB::invalidateASID(), WalkCache::invalidateASID(), IPACache::invalidateIPA(), IPACache::invalidateIPAA(), Sequencer::invalidateSC(), SMMUTLB::invalidateSID(), ConfigCache::invalidateSID(), SMMUTLB::invalidateSSID(), ConfigCache::invalidateSSID(), SMMUTLB::invalidateVA(), ARMArchTLB::invalidateVA(), WalkCache::invalidateVA(), SMMUTLB::invalidateVAA(), ARMArchTLB::invalidateVAA(), WalkCache::invalidateVAA(), SMMUTLB::invalidateVMID(), ARMArchTLB::invalidateVMID(), IPACache::invalidateVMID(), WalkCache::invalidateVMID(), IPACache::IPACache(), SMMUTLB::lookup(), ARMArchTLB::lookup(), IPACache::lookup(), ConfigCache::lookup(), WalkCache::lookup(), SMMUTLB::lookupAnyVA(), makeKvmCpuid(), SMMUTranslationProcess::microTLBLookup(), SMMUTranslationProcess::microTLBUpdate(), Time::operator double(), SparcISA::TteTag::operator=(), AlphaISA::PageTableEntry::operator=(), SparcISA::PageTableEntry::operator=(), DistIface::packetIn(), SparcISA::SparcStaticInst::passesFpCondition(), SparcISA::PageTableEntry::populate(), power(), QoS::MemSinkCtrl::processNextReqEvent(), VirtQueue::produceDescriptor(), pybind_init_event(), QTIsaac< ALPHA >::randinit(), System::registerThreadContext(), O3ThreadContext< Impl >::remove(), CheckerThreadContext< TC >::remove(), SimpleThread::remove(), System::replaceThreadContext(), sc_gem5::reportifyException(), DmaReadFifo::resumeFillTiming(), sc_gem5::Object::sc_obj(), QTIsaac< ALPHA >::shuffle(), SMMUTLB::SMMUTLB(), SMMUTranslationProcess::smmuTLBLookup(), SMMUTranslationProcess::smmuTLBUpdate(), sc_gem5::spawnWork(), sc_gem5::Module::startOfSimulation(), sc_gem5::StaticSensitivity::StaticSensitivity(), sc_core::sc_event_and_list::swap(), SparcISA::TLB::translateData(), ArmISA::TLB::translateFunctional(), SparcISA::TLB::translateInst(), SMMUTranslationProcess::translateStage2(), BaseRemoteGDB::trap(), WalkCache::WalkCache(), SMMUTranslationProcess::walkCacheUpdate(), DmaReadFifo::~DmaReadFifo(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::~ExtensionPool(), QTIsaac< ALPHA >::randctx::~randctx(), sc_gem5::Sensitivity::~Sensitivity(), and tlm_utils::time_ordered_list< std::pair >::~time_ordered_list().
e0e
Bitfield<24> ArmISA::e0e
Definition at line 323 of file miscregs_types.hh.
Referenced by isBigEndian64().
e0pd
ArmISA::e0pd
Definition at line 147 of file miscregs_types.hh.
ea
Bitfield<3> ArmISA::ea
Definition at line 308 of file miscregs_types.hh.
Referenced by Net::EthAddr::EthAddr(), and Net::EthAddr::operator uint64_t().
eae
Bitfield<31> ArmISA::eae
Definition at line 485 of file miscregs_types.hh.
ec
ArmISA::ec
Definition at line 634 of file miscregs_types.hh.
eccandParityEnable
Bitfield<21> ArmISA::eccandParityEnable
Definition at line 600 of file miscregs_types.hh.
ee
Bitfield<25> ArmISA::ee
Definition at line 322 of file miscregs_types.hh.
Referenced by isBigEndian64().
el
Bitfield< 3, 2 > ArmISA::el
Definition at line 72 of file miscregs_types.hh.
Referenced by canWriteAArch64SysReg(), ArmISA::ArmStaticInst::checkFPAdvSIMDEnabled64(), ArmISA::ArmStaticInst::checkSveEnabled(), ArmISA::ArmStaticInst::checkSveTrap(), currEL(), ArmISA::ArmStaticInst::disabledFault(), MiscRegImplDefined64::execute(), ArmISA::ISA::flattenIntIndex(), ArmISA::ISA::getCurSveVecLenInBits(), getRestoredITBits(), ArmSystem::haveSemihosting(), ArmISA::TLB::insert(), ArmISA::PMU::CounterState::isFiltered(), MiscRegOp64::MiscRegOp64(), ArmISA::ISA::setMiscReg(), and ArmISA::Interrupts::takeInt().
el0
Bitfield<3, 0> ArmISA::el0
Definition at line 179 of file miscregs_types.hh.
el1
Bitfield<7, 4> ArmISA::el1
Definition at line 178 of file miscregs_types.hh.
el2
Bitfield<11, 8> ArmISA::el2
Definition at line 177 of file miscregs_types.hh.
el3
Bitfield<15, 12> ArmISA::el3
Definition at line 176 of file miscregs_types.hh.
en
Bitfield<30> ArmISA::en
Definition at line 434 of file miscregs_types.hh.
Referenced by Root::timeSyncEnable(), Root::timeSyncPeriod(), and Root::timeSyncSpinThreshold().
encoding
Bitfield<27, 25> ArmISA::encoding
Definition at line 100 of file types.hh.
Referenced by VncServer::setEncodings().
epd0
Bitfield< 7 > ArmISA::epd0
Definition at line 468 of file miscregs_types.hh.
epd1
Bitfield< 23 > ArmISA::epd1
Definition at line 475 of file miscregs_types.hh.
erg
Bitfield<23,20> ArmISA::erg
Definition at line 613 of file miscregs_types.hh.
evt
Bitfield<59, 56> ArmISA::evt
Definition at line 148 of file miscregs_types.hh.
Referenced by Consumer::scheduleEventAbsolute().
exs
ArmISA::exs
Definition at line 121 of file miscregs_types.hh.
ext
Bitfield<12> ArmISA::ext
Definition at line 401 of file miscregs_types.hh.
Referenced by Gem5SystemC::Gem5Extension::copy_from(), tlm::tlm_generic_payload::deep_copy_from(), Net::Ip6Hdr::dst(), Net::Ip6Hdr::extensionLength(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), Net::Ip6Hdr::proto(), tlm::tlm_generic_payload::set_auto_extension(), tlm_utils::instance_specific_extensions_per_accessor::set_extension(), and tlm::tlm_generic_payload::set_extension().
ez
Bitfield<8> ArmISA::ez
Definition at line 646 of file miscregs_types.hh.
f
Bitfield< 0 > ArmISA::f
Definition at line 67 of file miscregs_types.hh.
Referenced by __nan(), IniFile::add(), sc_gem5::SensitivityEvents::addEvent(), BaseRemoteGDB::attach(), bitsToFloat32(), bitsToFloat64(), Debug::changeFlag(), dumpDebugFlags(), Event::Event(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), MemBackdoor::flags(), floatToBits32(), floatToBits64(), PowerModel::getDynamicPower(), PowerModel::getStaticPower(), ArmSemihosting::getSTDIO(), flitBuffer::getTopFlit(), BaseDynInst< Impl >::hitExternalSnoop(), CPA::hwWe(), MultiperspectivePerceptron::lookup(), BaseDynInst< Impl >::memOpDone(), Linux::openSpecialFile(), sc_core::operator<<(), sc_dt::scfx_ieee_float::operator=(), BaseDynInst< Impl >::possibleLoadViolation(), AnnotateDumpCallback::process(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::processWalkWrapper(), QTIsaac< ALPHA >::randinit(), BaseDynInst< Impl >::recordResult(), PybindSimObjectResolver::resolveSimObject(), sc_core::sc_bind(), sc_dt::scfx_ieee_float::scfx_ieee_float(), StaticInst::setFlag(), Trace::InstRecord::setMem(), QTIsaac< ALPHA >::shuffle(), LinearSystem::solve(), sc_gem5::spawnWork(), TEST(), BaseDynInst< Impl >::translationCompleted(), BaseDynInst< Impl >::translationStarted(), MultiperspectivePerceptron::update(), IniFile::~IniFile(), OutputDirectory::~OutputDirectory(), and QTIsaac< ALPHA >::randctx::~randctx().
fb
Bitfield<9> ArmISA::fb
Definition at line 262 of file miscregs_types.hh.
Referenced by FrameBuffer::area().
fcma
Bitfield<19, 16> ArmISA::fcma
Definition at line 113 of file miscregs_types.hh.
fd
Bitfield<14, 12> ArmISA::fd
Definition at line 160 of file types.hh.
Referenced by Terminal::accept(), VncServer::accept(), EtherTapStub::attach(), PerfKvmCounter::attached(), KvmVM::createVCPU(), doGzipLoad(), DtbFile::findReleaseAddr(), ImageFileData::ImageFileData(), Linux::openSpecialFile(), pollFunc(), RubySystem::readCompressedTrace(), PseudoInst::readfile(), EtherTapStub::sendReal(), TEST(), RubySystem::writeCompressedTrace(), and PollQueue::~PollQueue().
fhm
Bitfield<51, 48> ArmISA::fhm
Definition at line 93 of file miscregs_types.hh.
fi
Bitfield<21> ArmISA::fi
Definition at line 329 of file miscregs_types.hh.
Referenced by MathExprPowerModel::getStatValue().
fiq
Bitfield<2> ArmISA::fiq
Definition at line 309 of file miscregs_types.hh.
flushToZero
ArmISA::flushToZero
Definition at line 450 of file miscregs_types.hh.
Referenced by ArmISA::FpOp::binaryOp(), fixDivDest(), fixFpDFpSDest(), fixFpSFpDDest(), flushToZero(), ArmISA::FpOp::ternaryOp(), ArmISA::FpOp::unaryOp(), and vfpFlushToZero().
fm
Bitfield<3, 0> ArmISA::fm
Definition at line 162 of file types.hh.
fmo
Bitfield<3> ArmISA::fmo
Definition at line 269 of file miscregs_types.hh.
fn
Bitfield<18, 16> ArmISA::fn
Definition at line 159 of file types.hh.
Referenced by MathExpr::eval().
format
Bitfield<31,29> ArmISA::format
Definition at line 616 of file miscregs_types.hh.
Referenced by createObjectFile(), Time::operator-=(), Printk(), and procInfo().
fp
Bitfield<19, 16> ArmISA::fp
Definition at line 175 of file miscregs_types.hh.
Referenced by PowerISA::advancePC(), bitsToFp(), AlphaISA::buildRetPC(), SparcISA::buildRetPC(), X86ISA::buildRetPC(), fpToBits(), msrMrs64IssBuild(), and procInfo().
FpCondCodesMask
const uint32_t ArmISA::FpCondCodesMask = 0xF0000000 static
Definition at line 1891 of file miscregs.hh.
fpen
Bitfield<21, 20> ArmISA::fpen
Definition at line 384 of file miscregs_types.hh.
fpImm
Bitfield<2, 0> ArmISA::fpImm
Definition at line 163 of file types.hh.
fpRegImm
Bitfield<3> ArmISA::fpRegImm
Definition at line 161 of file types.hh.
FpscrExcMask
const uint32_t ArmISA::FpscrExcMask = 0x0000009F static
Definition at line 1893 of file miscregs.hh.
Referenced by ArmISA::ISA::readMiscReg(), and ArmISA::ISA::setMiscReg().
fpscrLen
Bitfield<39, 37> ArmISA::fpscrLen
Definition at line 86 of file types.hh.
FpscrQcMask
const uint32_t ArmISA::FpscrQcMask = 0x08000000 static
Definition at line 1895 of file miscregs.hh.
Referenced by ArmISA::ISA::readMiscReg(), and ArmISA::ISA::setMiscReg().
fpscrStride
Bitfield<41, 40> ArmISA::fpscrStride
Definition at line 85 of file types.hh.
FramePointerReg
const int ArmISA::FramePointerReg = 11
Definition at line 120 of file registers.hh.
Referenced by ArmISA::ArmStaticInst::printIntReg().
frintts
Bitfield<35, 32> ArmISA::frintts
Definition at line 109 of file miscregs_types.hh.
fsHigh
Bitfield<10> ArmISA::fsHigh
Definition at line 399 of file miscregs_types.hh.
fsLow
ArmISA::fsLow
Definition at line 395 of file miscregs_types.hh.
fw
Bitfield<4> ArmISA::fw
Definition at line 307 of file miscregs_types.hh.
fwb
Bitfield<43, 40> ArmISA::fwb
Definition at line 151 of file miscregs_types.hh.
fz
Bitfield<24> ArmISA::fz
Definition at line 422 of file miscregs_types.hh.
fz16
Bitfield<19> ArmISA::fz16
Definition at line 419 of file miscregs_types.hh.
ge
Bitfield<19, 16> ArmISA::ge
Definition at line 61 of file miscregs_types.hh.
gic
Bitfield<27, 24> ArmISA::gic
Definition at line 173 of file miscregs_types.hh.
Referenced by ArmSystem::setGIC().
gpa
Bitfield<27, 24> ArmISA::gpa
Definition at line 111 of file miscregs_types.hh.
gpi
Bitfield<31, 28> ArmISA::gpi
Definition at line 110 of file miscregs_types.hh.
GuestByteOrder
const ByteOrder ArmISA::GuestByteOrder = LittleEndianByteOrder
Definition at line 54 of file isa_traits.hh.
Referenced by ArmISA::ProcessInfo::pid(), readSymbol(), and ArmISA::ProcessInfo::task().
ha
Bitfield< 21 > ArmISA::ha
Definition at line 516 of file miscregs_types.hh.
hafdbs
Bitfield<3, 0> ArmISA::hafdbs
Definition at line 143 of file miscregs_types.hh.
HasUnalignedMemAcc
const bool ArmISA::HasUnalignedMemAcc = true
Definition at line 99 of file isa_traits.hh.
hcd
Bitfield<29> ArmISA::hcd
Definition at line 241 of file miscregs_types.hh.
hce
Bitfield<8> ArmISA::hce
Definition at line 302 of file miscregs_types.hh.
hd
Bitfield< 22 > ArmISA::hd
Definition at line 517 of file miscregs_types.hh.
HighVecs
const uint32_t ArmISA::HighVecs = 0xFFFF0000
Definition at line 96 of file isa_traits.hh.
Referenced by ArmISA::ArmFault::getVector().
hpd
Bitfield< 24 > ArmISA::hpd
Definition at line 507 of file miscregs_types.hh.
hpd0
Bitfield< 41 > ArmISA::hpd0
Definition at line 489 of file miscregs_types.hh.
hpd1
Bitfield< 42 > ArmISA::hpd1
Definition at line 490 of file miscregs_types.hh.
hpds
Bitfield<15, 12> ArmISA::hpds
Definition at line 140 of file miscregs_types.hh.
hpme
Bitfield<7> ArmISA::hpme
Definition at line 187 of file miscregs_types.hh.
hpmn
Bitfield<4, 0> ArmISA::hpmn
Definition at line 190 of file miscregs_types.hh.
htopcode10_9
Bitfield<26, 25> ArmISA::htopcode10_9
Definition at line 186 of file types.hh.
htopcode12_11
Bitfield<28, 27> ArmISA::htopcode12_11
Definition at line 185 of file types.hh.
htopcode4
Bitfield<20> ArmISA::htopcode4
Definition at line 200 of file types.hh.
htopcode5_4
Bitfield<21, 20> ArmISA::htopcode5_4
Definition at line 199 of file types.hh.
htopcode6
Bitfield<22> ArmISA::htopcode6
Definition at line 197 of file types.hh.
htopcode6_5
Bitfield<22, 21> ArmISA::htopcode6_5
Definition at line 198 of file types.hh.
htopcode7
Bitfield<23> ArmISA::htopcode7
Definition at line 195 of file types.hh.
htopcode7_5
Bitfield<23, 21> ArmISA::htopcode7_5
Definition at line 196 of file types.hh.
htopcode8
Bitfield<24> ArmISA::htopcode8
Definition at line 191 of file types.hh.
htopcode8_5
Bitfield<24, 21> ArmISA::htopcode8_5
Definition at line 194 of file types.hh.
htopcode8_6
Bitfield<24, 22> ArmISA::htopcode8_6
Definition at line 193 of file types.hh.
htopcode8_7
Bitfield<24, 23> ArmISA::htopcode8_7
Definition at line 192 of file types.hh.
htopcode9
Bitfield<25> ArmISA::htopcode9
Definition at line 187 of file types.hh.
htopcode9_4
Bitfield<25, 20> ArmISA::htopcode9_4
Definition at line 190 of file types.hh.
htopcode9_5
Bitfield<25, 21> ArmISA::htopcode9_5
Definition at line 189 of file types.hh.
htopcode9_8
Bitfield<25, 24> ArmISA::htopcode9_8
Definition at line 188 of file types.hh.
htrn
Bitfield<19, 16> ArmISA::htrn
Definition at line 202 of file types.hh.
hts
Bitfield<20> ArmISA::hts
Definition at line 203 of file types.hh.
i
Bitfield< 12 > ArmISA::i
Definition at line 66 of file miscregs_types.hh.
Referenced by sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::_gem5AddInterface(), System::_getMasterId(), ArmISA::Crypto::_sha1Op(), MemChecker::abortWrite(), ListenSocket::accept(), Terminal::accept(), TCPIface::accept(), Prefetcher::accessNonunitFilter(), Prefetcher::accessUnitFilter(), DRAMCtrl::activateBank(), Histogram::add(), ObjectMatch::add(), Stats::HistStor::add(), CheckTable::addCheck(), sc_gem5::SensitivityEvents::addEvent(), PerfectSwitch::addInPort(), sc_gem5::Port::addInterfaces(), AddrRange::addIntlvBits(), Stats::Hdf5::addMetaData(), NetDest::addNetDest(), Switch::addOutPort(), AddrRange::AddrRange(), IniFile::addSection(), Queue< WriteQueueEntry >::addToReadyList(), Trace::TarmacParserRecord::advanceTrace(), ArmISA::Crypto::aesAddRoundKey(), ArmISA::Crypto::aesInvMixColumns(), ArmISA::Crypto::aesInvShiftRows(), ArmISA::Crypto::aesInvSubBytes(), ArmISA::Crypto::aesShiftRows(), ArmISA::Crypto::aesSubBytes(), CacheRecorder::aggregateRecords(), sc_dt::scfx_mant::alloc_word(), CacheMemory::allocate(), FDArray::allocFD(), NetDest::AND(), sc_dt::sc_proxy< sc_subref_r< X > >::and_reduce(), sc_dt::sc_unsigned_subref_r::and_reduce(), sc_dt::sc_signed_subref_r::and_reduce(), sc_dt::sc_unsigned::and_reduce(), sc_dt::sc_signed::and_reduce(), FALRU::anyBlk(), ScheduleStage::arbitrate(), AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), arrayParamIn(), arrayParamOut(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::sc_bv_base::assign_from_string(), sc_dt::sc_lv_base::assign_from_string(), sc_dt::assign_p_(), sc_dt::assign_v_(), GPUCoalescer::atomicCallback(), HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >::AtomicInstBase(), DataBlock::atomicPartial(), sc_dt::b_and_assign_(), sc_dt::sc_proxy< sc_subref_r< X > >::b_not(), sc_dt::b_not(), sc_dt::b_or_assign_(), sc_dt::b_xor_assign_(), BaseGlobalEventTemplate< GlobalSyncEvent >::BaseGlobalEventTemplate(), BaseIndexingPolicy::BaseIndexingPolicy(), BaseSimpleCPU::BaseSimpleCPU(), FastModel::ScxEvsCortexA76< Types >::before_end_of_elaboration(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::before_end_of_elaboration(), sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::bind(), sc_core::sc_in< sc_dt::sc_lv< W > >::bind(), CxxConfigManager::bindAllPorts(), CxxConfigManager::bindObjectPorts(), sc_dt::sc_proxy< sc_subref_r< X > >::bit(), sc_core::sc_in< sc_dt::sc_int< W > >::bit(), sc_core::sc_in< sc_dt::sc_uint< W > >::bit(), sc_core::sc_in< sc_dt::sc_biguint< W > >::bit(), sc_core::sc_in< sc_dt::sc_bigint< W > >::bit(), sc_core::sc_inout< sc_dt::sc_int< W > >::bit(), sc_core::sc_inout< sc_dt::sc_uint< W > >::bit(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::bit(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::bit(), bitrev(), bitsToFloat32(), bitsToFloat64(), BloomFilter::Block::Block(), BOPPrefetcher::BOPPrefetcher(), BrigObject::BrigObject(), broadcast(), NetDest::broadcast(), Net::EthAddr::broadcast(), TAGEBase::btbUpdate(), Minor::ForwardInstData::bubbleFill(), LSQ< Impl >::SplitDataRequest::buildPackets(), TAGE_SC_L_TAGE::buildTageTables(), TAGEBase::buildTageTables(), CacheMemory::cacheAvail(), CacheMemory::cacheProbe(), TAGE_SC_L_TAGE::calculateIndicesAndTags(), TAGEBase::calculateIndicesAndTags(), MPP_TAGE::calculateParameters(), TAGE_SC_L_TAGE::calculateParameters(), TAGEBase::calculateParameters(), IndirectMemoryPrefetcher::calculatePrefetch(), NetworkInterface::calculateVC(), ArmSemihosting::call32(), ArmSemihosting::call64(), Minor::LSQ::StoreBuffer::canForwardDataToLoad(), Kvm::capXSave(), Trace::SparcNativeTrace::check(), Trace::ArmNativeTrace::check(), PacketFifo::check(), SwitchAllocator::check_for_wakeup(), sc_dt::sc_unsigned::check_index(), sc_dt::sc_signed::check_index(), AlphaISA::Interrupts::checkInterrupts(), AbstractMemory::checkLockedAddrList(), CheckTable::CheckTable(), DRAMCtrl::chooseNext(), DRAMCtrl::chooseNextFRFCFS(), ClDriver::ClDriver(), X86ISA::GpuTLB::cleanup(), tlm::circular_buffer< T >::clear(), Histogram::clear(), NetDest::clear(), ProfileNode::clear(), sc_dt::scfx_mant::clear(), StoreSet::clear(), PacketFifo::clear(), SwitchAllocator::clear_request_vector(), SparcISA::Interrupts::clearAll(), TsunamiCChip::clearDRIR(), MaltaCChip::clearIntr(), TsunamiCChip::clearITI(), SparcISA::TLB::clearUsedBits(), OutputDirectory::close(), HsailISA::CmpInstBase< DestDataType::OperandType, SrcDataType::OperandType >::CmpInstBase(), WriteMask::cmpMask(), ClDriver::codeOffToKernelName(), CoherentXBar::CoherentXBar(), SimpleNetwork::collateStats(), Switch::collateStats(), Profiler::collateStats(), Router::collateStats(), GarnetNetwork::collateStats(), DefaultCommit< Impl >::commitHead(), HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >::CommonInstBase(), ThreadContext::compare(), sc_dt::compare_msw_ff(), sc_dt::complement(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::completeAcc(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::completeAcc(), GPUCoalescer::completeHitCallback(), GPUCoalescer::completeIssue(), MemChecker::completeRead(), MemChecker::completeWrite(), MultiCompressor::compress(), DictionaryCompressor< uint64_t >::compressValue(), MultiperspectivePerceptron::computeBits(), MultiperspectivePerceptron::computeOutput(), MultiperspectivePerceptronTAGE::computePartialSum(), BaseTags::computeStats(), ComputeUnit::ComputeUnit(), FunctionProfile::consume(), AddrRange::contains(), sc_dt::convert_to_bin(), X86ISA::convX87TagsToXTags(), X86ISA::convX87XTagsToTags(), PollQueue::copy(), AlphaISA::copyIprs(), SparcISA::copyMiscRegs(), X86ISA::copyMiscRegs(), PacketFifo::copyout(), DataBlock::copyPartial(), PowerISA::copyRegs(), AlphaISA::copyRegs(), copyRegs(), SparcISA::copyRegs(), X86ISA::copyRegs(), Checker< O3CPUImpl >::copyResult(), copyStringArray(), FastModel::CortexA76Cluster::CortexA76Cluster(), NetDest::count(), LdsState::countBankConflicts(), PersistentTable::countReadStarvingForAddress(), PersistentTable::countStarvingForAddress(), crc32(), Topology::createLinks(), GenericTimer::createTimers(), ArmISA::ArmStaticInst::cSwap(), CustomNoMaliGpu::CustomNoMaliGpu(), DMASequencer::dataCallback(), tlm::circular_buffer< T >::debug(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), DictionaryCompressor< uint64_t >::decompress(), DictionaryCompressor< T >::RepeatedValuePattern< RepT >::decompress(), tlm::tlm_generic_payload::deep_copy_from(), DefaultBTB::DefaultBTB(), DefaultFetch< Impl >::DefaultFetch(), CxxConfigManager::deleteObjects(), SparcISA::TLB::demapPage(), BaseGlobalEvent::deschedule(), SkewedAssociative::deskew(), StaticInst::destRegIdx(), Debug::AllFlags::disable(), Debug::SimpleFlag::disableAll(), sc_dt::scfx_rep::divide_by_ten(), TsunamiPChip::dmaAddr(), DRAMCtrl::doDRAMAccess(), Stats::VectorBase< Vector, StatStor >::doInit(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::doInit(), ObjectMatch::domatch(), PCEventQueue::doService(), ThermalModel::doStep(), SyscallDesc::doSyscall(), Histogram::doubleBinSize(), FullO3CPU< O3CPUImpl >::drain(), ArmISA::TableWalker::drain(), DefaultFetch< Impl >::drainResume(), FullO3CPU< O3CPUImpl >::drainResume(), MemDepUnit< MemDepPred, Impl >::drainSanityCheck(), LSQUnit< Impl >::drainSanityCheck(), DefaultFetch< Impl >::drainSanityCheck(), DRAMCtrl::DRAMCtrl(), ProfileNode::dump(), Trace::Logger::dump(), FunctionProfile::dump(), Trie< Key, Value >::Node::dump(), ArmV8KvmCPU::dump(), ActivityRecorder::dump(), DependencyGraph< DynInstPtr >::dump(), PCEventQueue::dump(), FUPool::dump(), BPredUnit::dump(), IniFile::dump(), sc_dt::scfx_rep::dump(), MultiSocketSimpleSwitchAT::dump_status(), SparcISA::TLB::dumpAll(), dumpDebugFlags(), dumpFpuCommon(), dumpKvm(), InstructionQueue< Impl >::dumpLists(), dumpMainQueue(), X86KvmCPU::dumpMSRs(), BaseDynInst< Impl >::eaSrcsReady(), ElfObject::ElfObject(), DependencyGraph< DynInstPtr >::empty(), Minor::MinorBuffer< Minor::ForwardInstData >::empty(), Debug::AllFlags::enable(), Debug::SimpleFlag::enableAll(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_bigint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::end_of_elaboration(), SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), Net::EthAddr::EthAddr(), EtherSwitch::EtherSwitch(), Minor::Decode::evaluate(), Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), eventqDump(), X86ISA::TLB::evictLRU(), ConditionRegisterState::exec(), VectorRegisterFile::exec(), Shader::exec(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execSt(), Minor::Execute::Execute(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), execveFunc(), X86ISA::GpuTLB::exitCallback(), exitImpl(), Topology::extend_shortest_path(), sc_dt::extend_sign_w_(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::ExtensionPool(), FaultModel::fault_prob(), FaultModel::fault_vector(), FaultModel::FaultModel(), WriteMask::fillMask(), sc_gem5::Port::finalizeFinder(), sc_gem5::Port::finalizePort(), SparcISA::TlbMap::find(), SimObject::find(), AddrRangeMap< AbstractMemory *, 1 >::find(), OutputDirectory::find(), sc_dt::scfx_rep::find_lsw(), sc_dt::scfx_rep::find_msw(), SymbolTable::findAddress(), MultiperspectivePerceptron::findBest(), Debug::findFlag(), VGic::findHighestPendingLR(), VGic::findLRForVIRQ(), SymbolTable::findNearestAddr(), SymbolTable::findNearestSymbol(), CxxConfigManager::findObject(), CxxConfigManager::findObjectParams(), BaseXBar::findPort(), ControlFlowInfo::findPostDominators(), IniFile::findSection(), PersistentTable::findSmallest(), SymbolTable::findSymbol(), Minor::FUPipeline::findTiming(), CxxConfigManager::findTraversalOrder(), LSQ< Impl >::SplitDataRequest::finish(), VecPredRegT< VecElem, NumElems, Packed, Const >::firstActive(), firstbit(), AtagCore::flags(), NetworkInterface::flitisizeMessage(), floatToBits32(), floatToBits64(), AlphaISA::TLB::flushAddr(), X86ISA::TLB::flushAll(), X86ISA::TLB::flushNonGlobal(), AlphaISA::TLB::flushProcesses(), BaseCPU::flushTLBs(), FALRU::forEachBlk(), CxxConfigManager::forEachObject(), formatParamList(), Gicv2m::frameFromAddr(), tlm::tlm_generic_payload::free_all_extensions(), sc_dt::scfx_rep::from_string(), sc_dt::from_uint(), DictionaryCompressor< uint64_t >::fromDictionaryEntry(), SimpleNetwork::functionalRead(), RubySystem::functionalRead(), CrossbarSwitch::functionalWrite(), SimpleNetwork::functionalWrite(), NetworkInterface::functionalWrite(), flitBuffer::functionalWrite(), Switch::functionalWrite(), RubySystem::functionalWrite(), GarnetNetwork::functionalWrite(), Router::functionalWrite(), MessageBuffer::functionalWrite(), InputUnit::functionalWrite(), RubyRequest::functionalWrite(), FuncUnit::FuncUnit(), Minor::FUPipeline::FUPipeline(), FUPool::FUPool(), GarnetNetwork::GarnetNetwork(), MrsOp::generateDisassembly(), ArmISA::SveLdStructSS< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >::generateDisassembly(), ArmISA::SveStStructSS< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), ArmISA::SveLdStructSI< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), ArmISA::SveStStructSI< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::generateDisassembly(), GarnetSyntheticTraffic::generatePkt(), Gicv3CPUInterface::generateSGI(), X86ISA::genX87Tags(), VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::get_bits(), SimpleAddressMap::get_max(), SimpleAddressMap::get_min(), NetworkInterface::get_vnet(), sc_dt::sc_bv_base::get_word(), Gicv2m::getAddrRanges(), RubyPort::PioSlavePort::getAddrRanges(), NetDest::getAllDest(), PciDevice::getBAR(), DeltaCorrelatingPredictionTables::DCPTEntry::getCandidates(), CheckTable::getCheck(), Wavefront::getContext(), BloomFilter::MultiBitSel::getCount(), PowerModel::getDynamicPower(), ArmFreebsdProcessBits::getFreebsdDesc(), BrigObject::getFunction(), TAGEBase::getGHR(), MultiperspectivePerceptron::ACYCLIC::getHash(), MultiperspectivePerceptron::MODHIST::getHash(), MultiperspectivePerceptron::RECENCY::getHash(), MultiperspectivePerceptron::PATH::getHash(), MultiperspectivePerceptron::MODPATH::getHash(), MultiperspectivePerceptron::GHISTPATH::getHash(), MultiperspectivePerceptron::GHISTMODPATH::getHash(), MultiperspectivePerceptron::BLURRYPATH::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), Gicv3CPUInterface::getHPPVILR(), AlphaISA::Interrupts::getInterrupt(), BrigObject::getKernel(), ArmLinuxProcessBits::getLinuxDesc(), LoopPredictor::getLoop(), Prefetcher::getLRUindex(), WriteMask::getMask(), CxxIniFile::getObjectChildren(), X86ISA::getPackedMem(), PIFPrefetcher::CompactorEntry::getPredictedAddresses(), Prefetcher::getPrefetchEntry(), ArmKvmCPU::getRegList(), AlphaISA::RemoteGDB::AlphaGdbRegCache::getRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), IniFile::getSectionNames(), SimpleIndirectPredictor::getSetIndex(), TAGEBase::getSizeInBits(), PowerModel::getStaticPower(), Gicv2m::Gicv2m(), StatisticalCorrector::gPredict(), GPUDynInst::GPUDynInst(), X86ISA::GpuTLB::GpuTLB(), Stats::HistStor::grow_convert(), Stats::HistStor::grow_out(), Stats::HistStor::grow_up(), MPP_StatisticalCorrector::gUpdate(), StatisticalCorrector::gUpdate(), sc_dt::scfx_mant::half_addr(), TAGE_SC_L_TAGE_8KB::handleAllocAndUReset(), TAGE_SC_L_TAGE_64KB::handleAllocAndUReset(), MPP_TAGE::handleAllocAndUReset(), TAGEBase::handleAllocAndUReset(), X86KvmCPU::handleKvmExitIO(), MPP_TAGE::handleUReset(), TAGEBase::handleUReset(), BloomFilter::H3::hash(), BloomFilter::MultiBitSel::hash(), BloomFilter::Block::hash(), MultiperspectivePerceptron::GHIST::hash(), MultiperspectivePerceptron::RECENCYPOS::hash(), InstructionQueue< Impl >::hasReadyInsts(), GPUCoalescer::hitCallback(), CPA::hwWe(), X86ISA::I8042::I8042(), X86ISA::I82094AA::I82094AA(), X86ISA::I8254::I8254(), X86ISA::I8259::I8259(), IdeController::IdeController(), sc_dt::inc(), tlm::circular_buffer< T >::increment_read_pos(), tlm::circular_buffer< T >::increment_write_pos(), Stats::InfoAccess::info(), SwitchAllocator::init(), CrossbarSwitch::init(), VecRegisterState::init(), GarnetNetwork::init(), NetworkInterface::init(), CacheMemory::init(), DirectoryMemory::init(), PerfectSwitch::init(), StoreSet::init(), AbstractController::init(), sc_dt::sc_bv_base::init(), sc_dt::sc_lv_base::init(), RubyTester::init(), Gicv3::init(), CpuLocalTimer::init(), ComputeUnit::init(), BaseCPU::init(), sc_core::sc_vector< svp_gicv3_comms::gicv3_comms_target_socket<> >::init(), ListOperand::init(), MultiperspectivePerceptron::init(), Stats::Vector2dBase< Vector2d, StatStor >::init(), EmbeddedPython::initAll(), X86ISA::initCPU(), TAGE_SC_L_TAGE_8KB::initFoldedHistories(), TAGEBase::initFoldedHistories(), StatisticalCorrector::initGEHLTable(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::initiateAcc(), FetchUnit::initiateFetch(), LSQ< Impl >::SplitDataRequest::initiateTranslation(), AlphaISA::initIPRs(), FreebsdArmSystem::initState(), ArmProcess32::initState(), LinuxArmSystem::initState(), ArmProcess64::initState(), X86ISA::X86_64Process::initState(), ArmSystem::initState(), X86ISA::I386Process::initState(), System::initState(), InputUnit::InputUnit(), AlphaISA::TLB::insert(), SparcISA::TLB::insert(), Trie< Addr, uint32_t >::insert(), ArmISA::TLB::insert(), MultiperspectivePerceptron::insert(), PowerISA::TLB::insertAt(), MultiperspectivePerceptron::ThreadData::insertRecency(), GPUCoalescer::insertRequest(), SparcISA::ISA::installGlobals(), SparcISA::ISA::installWindow(), InstResult::InstResult(), SubBlock::internalMergeFrom(), SubBlock::internalMergeTo(), SparcISA::TlbMap::intersect(), NetDest::intersectionIsNotEmpty(), X86ISA::GpuTLB::invalidateAll(), SMMUTLB::invalidateAll(), ARMArchTLB::invalidateAll(), IPACache::invalidateAll(), ConfigCache::invalidateAll(), WalkCache::invalidateAll(), SMMUTLB::invalidateASID(), ARMArchTLB::invalidateASID(), WalkCache::invalidateASID(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::invalidateDMIPointers(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::invalidateDMIPointers(), IPACache::invalidateIPA(), IPACache::invalidateIPAA(), X86ISA::GpuTLB::invalidateNonGlobal(), SMMUTLB::invalidateSID(), ConfigCache::invalidateSID(), SMMUTLB::invalidateSSID(), ConfigCache::invalidateSSID(), SMMUTLB::invalidateVA(), ARMArchTLB::invalidateVA(), WalkCache::invalidateVA(), SMMUTLB::invalidateVAA(), ARMArchTLB::invalidateVAA(), WalkCache::invalidateVAA(), SMMUTLB::invalidateVMID(), ARMArchTLB::invalidateVMID(), IPACache::invalidateVMID(), WalkCache::invalidateVMID(), sc_dt::sc_unsigned::invert(), sc_dt::sc_signed::invert(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), ClDriver::ioctl(), sc_dt::sc_lv_base::is_01(), sc_dt::sc_subref_r< X >::is_01(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::is_from(), sc_dt::scfx_rep::is_zero(), NetDest::isBroadcast(), ComputeUnit::isDone(), MemDepUnit< MemDepPred, Impl >::isDrained(), FUPool::isDrained(), DefaultFetch< Impl >::isDrained(), NetDest::isEmpty(), WriteMask::isEmpty(), NetDest::isEqual(), WriteMask::isFull(), WriteMask::isOverlap(), DictionaryCompressor< T >::RepeatedValuePattern< RepT >::isPattern(), ComputeUnit::isSimdDone(), DMASequencer::issueNext(), GPUCoalescer::issueRequest(), NetDest::isSuperset(), MSHR::TargetList::isWholeLineWrite(), KvmVM::KvmVM(), VecPredRegT< VecElem, NumElems, Packed, Const >::lastActive(), lastbit(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::LdInst(), Stats::Info::less(), LinearSystem::LinearSystem(), ListenSocket::listen(), ArmISA::Crypto::load2Reg(), ArmISA::Crypto::load3Reg(), EcoffObject::loadGlobalSymbols(), EcoffObject::loadLocalSymbols(), ElfObject::loadSomeSymbols(), CxxConfigManager::loadState(), QoS::MemCtrl::logRequest(), AlphaISA::TLB::lookup(), PowerISA::TLB::lookup(), SparcISA::TLB::lookup(), SMMUTLB::lookup(), ARMArchTLB::lookup(), ArmISA::TLB::lookup(), IPACache::lookup(), ConfigCache::lookup(), WalkCache::lookup(), SMMUTLB::lookupAnyVA(), System::lookupMasterId(), lookupTraceForAddress(), tlm::loop_word1(), LoopPredictor::loopUpdate(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), VGic::lrPending(), VGic::lrValid(), sc_dt::scfx_ieee_double::lsb(), m5Main(), ArmISA::MacroVFPMemOp::MacroVFPMemOp(), HsailISA::Call::MagicSimBreak(), main(), tlm::tlm_bool< D >::make_uchar_array(), SimpleNetwork::makeInternalLink(), Malta::Malta(), GPUCoalescer::mapAddrToPkt(), PersistentTable::markEntries(), System::markWorkItem(), MathExprPowerModel::MathExprPowerModel(), AtagMem::memSize(), AtagMem::memStart(), BloomFilter::Multi::merge(), BloomFilter::Base::merge(), DRAMCtrl::minBankPrep(), MinorCPU::MinorCPU(), MinorOpClassSet::MinorOpClassSet(), Minor::Scoreboard::minorTrace(), Minor::MinorBuffer< Minor::ForwardInstData >::minorTrace(), Minor::Execute::minorTrace(), Minor::LSQ::StoreBuffer::minorTrace(), FALRU::CacheTracking::moveBlockToHead(), FALRU::CacheTracking::moveBlockToTail(), sc_dt::scfx_ieee_double::msb(), sc_dt::scfx_pow10::neg(), Network::Network(), NetworkInterface::NetworkInterface(), TrafficGen::nextState(), NoncoherentXBar::NoncoherentXBar(), VecPredRegT< VecElem, NumElems, Packed, Const >::noneActive(), number_of_ones(), BaseCPU::numSimulatedInsts(), BaseCPU::numSimulatedOps(), HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >::numSrcRegOperands(), HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >::numSrcRegOperands(), sc_dt::scfx_rep::o_extend(), sc_dt::scfx_rep::o_invert(), sc_dt::scfx_rep::o_set(), sc_dt::scfx_rep::o_set_high(), sc_dt::scfx_rep::o_zero_left(), sc_dt::scfx_rep::o_zero_right(), PersistentTable::okToIssueStarving(), VirtIOConsole::TermTransQueue::onNotifyDescriptor(), CowDiskImage::open(), openImpl(), VectorRegisterFile::operandsReady(), PerfectSwitch::operateMessageBuffer(), sc_dt::scfx_rep::operator new(), std::hash< FutexKey >::operator()(), sc_dt::scfx_pow10::operator()(), Stats::VectorPrint::operator()(), Stats::DistPrint::operator()(), LinearEquation::operator+(), TimeBuffer< T >::wire::operator++(), TimeBuffer< T >::wire::operator--(), operator<<(), sc_dt::sc_proxy< sc_subref_r< X > >::operator<<=(), sc_core::sc_out_rv< W >::operator=(), sc_core::sc_inout_rv< W >::operator=(), sc_dt::scfx_mant::operator=(), Minor::ForwardInstData::operator=(), Net::TcpPtr::operator=(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), Net::UdpPtr::operator=(), sc_dt::sc_subref< X >::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), sc_dt::operator==(), sc_dt::operator>=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator>>=(), sc_dt::scfx_string::operator[](), sc_dt::scfx_mant::operator[](), tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::operator[](), TypedBufferArg< T >::operator[](), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::operator[](), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::operator[](), sc_dt::scfx_mant_ref::operator[](), sc_dt::sc_proxy< sc_subref_r< X > >::operator[](), sc_core::sc_vector_assembly< T, MT >::operator[](), sc_core::sc_in< sc_dt::sc_int< W > >::operator[](), sc_core::sc_in< sc_dt::sc_uint< W > >::operator[](), sc_core::sc_in< sc_dt::sc_biguint< W > >::operator[](), sc_core::sc_in< sc_dt::sc_bigint< W > >::operator[](), sc_core::sc_inout< sc_dt::sc_int< W > >::operator[](), sc_core::sc_inout< sc_dt::sc_uint< W > >::operator[](), sc_core::sc_inout< sc_dt::sc_biguint< W > >::operator[](), sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator[](), sc_dt::sc_bitref< X >::operator^=(), sc_dt::sc_fix::operator~(), sc_dt::sc_ufix::operator~(), sc_dt::sc_ufix_fast::operator~(), sc_dt::sc_fix_fast::operator~(), NetDest::OR(), sc_dt::sc_proxy< sc_subref_r< X > >::or_reduce(), sc_dt::sc_unsigned_subref_r::or_reduce(), sc_dt::sc_signed_subref_r::or_reduce(), WriteMask::orMask(), sc_gem5::VcdTraceValFinite< T >::output(), sc_gem5::VcdTraceValFxnum< T >::output(), sc_gem5::VcdTraceValTime::output(), sc_gem5::VcdTraceValInt< T >::output(), OutputUnit::OutputUnit(), LSQ< Impl >::LSQRequest::packetNotSent(), AtagCore::pagesize(), Net::EthAddr::parse(), MathExpr::parse(), TrafficGen::parseConfig(), PciDevice::PciDevice(), WriteMask::performAtomic(), PersistentTable::persistentRequestLock(), SMMUTLB::pickEntryIdxToReplace(), ARMArchTLB::pickEntryIdxToReplace(), IPACache::pickEntryIdxToReplace(), ConfigCache::pickEntryIdxToReplace(), WalkCache::pickEntryIdxToReplace(), Pl111::Pl111(), tlm::circular_buffer< T >::poke_data(), popcount(), sc_dt::scfx_pow10::pos(), TsunamiCChip::postDRIR(), MaltaCChip::postIntr(), TsunamiCChip::postRTC(), Prefetcher::Prefetcher(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::prepare(), Stats::Vector2dBase< Vector2d, StatStor >::prepare(), Stats::DistStor::prepare(), Stats::HistStor::prepare(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::prepare(), preUnflattenMiscReg(), DataBlock::print(), NetDest::print(), Prefetcher::print(), CacheMemory::print(), SparcISA::TlbMap::print(), WriteMask::print(), sc_dt::print_dec(), sc_dt::print_other(), Packet::PrintReqState::printLabels(), MsrBase::printMsrBase(), printSorted(), System::printSystems(), IniFile::printUnreferenced(), Histogram::printWithMultiplier(), PowerISA::TLB::probeEntry(), AnnotateDumpCallback::process(), Trace::TarmacParserRecord::TarmacParserRecordEvent::process(), CallbackQueue::process(), DistIface::SyncEvent::process(), BrigObject::processDirectives(), FetchUnit::processFetchReturn(), QoS::MemSinkCtrl::processNextReqEvent(), TLBCoalescer::processProbeTLBEvent(), BaseCPU::processProfileEvent(), ArmISA::TableWalker::processWalkAArch64(), PseudoInst::pseudoInst(), ClockedObject::pwrStateWeights(), sc_dt::scfx_rep::q_clear(), sc_dt::scfx_rep::q_incr(), sc_dt::scfx_rep::q_zero(), Queue< WriteQueueEntry >::Queue(), QTIsaac< ALPHA >::randinit(), MinorCPU::randomPriority(), SimpleDisk::read(), CowDiskImage::read(), Gicv3Redistributor::read(), Gicv3Distributor::read(), VirtQueue::VirtRing< struct vring_used_elem >::read(), TraceCPU::ElasticDataGen::InputStream::read(), GPUCoalescer::readCallback(), VGic::readCtrl(), X86ISA::readPackedMemAtomic(), VGic::readVCpu(), readvFunc(), PixelConverter::readWord(), ComputeUnit::ReadyWorkgroup(), STeMSPrefetcher::reconstructSequence(), FALRU::CacheTracking::recordAccess(), CacheMemory::recordCacheContents(), RubyPort::PioSlavePort::recvAtomic(), SerialLink::SerialLinkSlavePort::recvFunctional(), DRAMSim2::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), recvmsgFunc(), ComputeUnit::DataPort::recvReqRetry(), ComputeUnit::SQCPort::recvReqRetry(), ComputeUnit::DTLBPort::recvReqRetry(), ComputeUnit::ITLBPort::recvReqRetry(), RubyPort::PioSlavePort::recvTimingReq(), TLBCoalescer::CpuSidePort::recvTimingReq(), SimpleMemory::recvTimingReq(), sc_gem5::Port::regPort(), BaseMemProbe::regProbeListeners(), SimpleNetwork::regStats(), Sequencer::regStats(), Profiler::regStats(), Switch::regStats(), ExecStage::regStats(), BaseDictionaryCompressor::regStats(), GarnetNetwork::regStats(), GPUCoalescer::regStats(), BaseTags::BaseTagStats::regStats(), CacheMemory::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), InstructionQueue< Impl >::regStats(), BaseSimpleCPU::regStats(), BaseCacheCompressor::regStats(), AbstractMemory::MemStats::regStats(), SMMUv3::regStats(), ClockedObject::ClockedObjectStats::regStats(), BaseCPU::regStats(), FALRU::CacheTracking::regStats(), ComputeUnit::regStats(), BaseXBar::regStats(), BaseCache::CacheStats::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), SparcISA::ISA::reloadRegMap(), RangeAddrMapper::remapAddr(), PollQueue::remove(), PCEventQueue::remove(), PacketFifo::remove(), OutputDirectory::remove(), sc_core::sc_in< sc_dt::sc_int< W > >::remove_traces(), sc_core::sc_in< sc_dt::sc_uint< W > >::remove_traces(), sc_core::sc_in< sc_dt::sc_biguint< W > >::remove_traces(), sc_core::sc_in< sc_dt::sc_bigint< W > >::remove_traces(), sc_core::sc_inout< sc_dt::sc_int< W > >::remove_traces(), sc_core::sc_inout< sc_dt::sc_uint< W > >::remove_traces(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::remove_traces(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::remove_traces(), BaseRemoteGDB::removeHardBreak(), AddrRange::removeIntlvBits(), NetDest::removeNetDest(), CxxConfigManager::rename(), CpuEvent::replaceThreadContext(), Minor::ForwardInstData::reportData(), BaseGlobalEvent::reschedule(), ReturnAddrStack::reset(), DefaultBTB::reset(), DependencyGraph< DynInstPtr >::reset(), ActivityRecorder::reset(), Sinic::Device::reset(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::reset(), MemChecker::reset(), VirtIODeviceBase::reset(), Stats::Vector2dBase< Vector2d, StatStor >::reset(), Stats::DistStor::reset(), Stats::HistStor::reset(), InstructionQueue< Impl >::resetState(), Sequencer::resetStats(), Switch::resetStats(), NetworkLink::resetStats(), AbstractController::resetStats(), Router::resetStats(), GPUCoalescer::resetStats(), tlm::circular_buffer< T >::resize(), NetDest::resize(), tlm_utils::instance_specific_extension_container::resize(), sc_dt::scfx_mant::resize_to(), Stats::VectorBase< Vector, StatStor >::result(), Stats::VectorProxy< Stat >::result(), Stats::UnaryNode< Op >::result(), Stats::BinaryNode< Op >::result(), Stats::SumNode< Op >::result(), AtagRev::rev(), sc_dt::sc_proxy< sc_subref_r< X > >::reverse(), AtagCore::rootdev(), MinorCPU::roundRobinPriority(), Gicv3Distributor::route(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), RubyDirectedTester::RubyDirectedTester(), RubyPort::RubyPort(), RubyTester::RubyTester(), StatTest::run(), Sinic::Device::rxKick(), StackDistCalc::sanityCheckTree(), CowDiskImage::save(), SBOOEPrefetcher::SBOOEPrefetcher(), sc_dt::sc_bv_base::sc_bv_base(), sc_dt::sc_lv_base::sc_lv_base(), SC_MODULE(), sc_dt::scfx_csd2tc(), sc_dt::scfx_find_lsb(), sc_dt::scfx_find_msb(), sc_dt::scfx_mant::scfx_mant(), sc_dt::scfx_pow10::scfx_pow10(), sc_dt::scfx_rep::scfx_rep(), sc_dt::scfx_tc2csd(), BaseGlobalEvent::schedule(), BaseGlobalEvent::scheduled(), NetworkInterface::scheduleOutputLink(), FastModel::ScxEvsCortexA76< Types >::ScxEvsCortexA76(), QoS::TurnaroundPolicyIdeal::selectBusState(), selectFunc(), Minor::SelfStallingPipeline< ElemType, ReportTraits, BubbleTraits >::SelfStallingPipeline(), PS2TouchKit::sendTouchKit(), NoMaliGpu::serialize(), SymbolTable::serialize(), ArmSemihosting::serialize(), ArmISA::PMU::serialize(), AlphaISA::TLB::serialize(), EtherSwitch::Interface::PortFifo::serialize(), PowerISA::TLB::serialize(), CpuLocalTimer::serialize(), VGic::serialize(), PacketFifo::serialize(), GenericTimer::serialize(), PciDevice::serialize(), Sinic::Device::serialize(), CxxConfigManager::serialize(), serialize(), ArmISA::TLB::serialize(), BaseCPU::serialize(), DistIface::RecvScheduler::serialize(), GicV2::serialize(), VirtIODeviceBase::serialize(), SimObject::serializeAll(), PollQueue::service(), BloomFilter::MultiBitSel::set(), WaitClass::set(), sc_dt::sc_uint_base::set(), sc_dt::sc_int_base::set(), sc_dt::sc_unsigned::set(), sc_dt::sc_signed::set(), VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::set_bits(), sc_gem5::TraceFile::set_time_unit(), sc_dt::sc_bv_base::set_word(), Wavefront::setContext(), OutputDirectory::setDirectory(), DistEtherLink::Link::setLocalInt(), WriteMask::setMask(), setpgidFunc(), X86ISA::Interrupts::setReg(), AlphaISA::RemoteGDB::AlphaGdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), EtherLink::Link::setRxInt(), setThreadArea32Func(), EtherLink::Link::setTxInt(), ArmISA::Crypto::sha256Op(), Shader::Shader(), sc_dt::scfx_rep::shift_left(), sc_dt::scfx_rep::shift_right(), Topology::shortest_path_to_node(), X86ISA::I82094AA::signalInterrupt(), signbit(), simd_modified_imm(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusAT(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::SimpleBusLT(), SimpleCache::SimpleCache(), SimpleIndirectPredictor::SimpleIndirectPredictor(), SimpleNetwork::SimpleNetwork(), simulate(), sc_dt::sc_bitref_r< X >::size(), sc_dt::sc_bv_base::size(), sc_dt::sc_lv_base::size(), sc_dt::sc_subref_r< X >::size(), sc_dt::sc_concref_r< X, Y >::size(), SkewedAssociative::skew(), NetDest::smallestElement(), Set::smallestElement(), GicV2::softInt(), LinearSystem::solve(), DefaultDecode< Impl >::sortInsts(), DefaultRename< Impl >::sortInsts(), DefaultIEW< Impl >::sortInsts(), Sparc32Process::Sparc32Process(), Sparc64Process::Sparc64Process(), sc_gem5::spawnWork(), DefaultRename< Impl >::squash(), DefaultDecode< Impl >::squash(), TAGEBase::squash(), QTIsaac< ALPHA >::srand(), StaticInst::srcRegIdx(), MemChecker::startRead(), MemTraceProbe::startup(), MathExprPowerModel::startup(), ThermalModel::startup(), MemChecker::startWrite(), AlphaISA::Kernel::Statistics::Statistics(), Minor::LSQ::StoreBuffer::step(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::StInst(), StorageMap::StorageMap(), ArmISA::Crypto::store1Reg(), StoreSet::StoreSet(), Stats::ConstVectorNode< T >::str(), SubBlock::SubBlock(), ArmISA::SveIndexedMemSV< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::SveIndexedMemSV(), ArmISA::SveIndexedMemVI< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::SveIndexedMemVI(), ArmISA::SveLdStructSI< Element, MicroopLdMemType, MicroopDeIntrlvType >::SveLdStructSI(), ArmISA::SveLdStructSS< Element, MicroopLdMemType, MicroopDeIntrlvType >::SveLdStructSS(), ArmISA::SveStStructSI< Element, MicroopStMemType, MicroopIntrlvType >::SveStStructSI(), ArmISA::SveStStructSS< Element, MicroopStMemType, MicroopIntrlvType >::SveStStructSS(), UnifiedRenameMap::switchMode(), TAGEBase::tagePredict(), FALRU::tagsInit(), DefaultIEW< Impl >::takeOverFrom(), BaseCPU::takeOverFrom(), TCPIface::TCPIface(), VirtIO9PDiod::terminateDiod(), FastModel::SCGIC::Terminator::Terminator(), TEST(), testAndRead(), testAndReadMask(), testAndWrite(), tgkillFunc(), MultiperspectivePerceptron::ThreadData::ThreadData(), Trace::ArmNativeTrace::ThreadState::ThreadState(), AtomicSimpleCPU::tick(), DefaultFetch< Impl >::tick(), TimeBuffer< DecodeStruct >::TimeBuffer(), TLBCoalescer::TLBCoalescer(), to_number(), AddrRange::to_string(), sc_dt::sc_proxy< sc_subref_r< X > >::to_string(), DictionaryCompressor< uint64_t >::toDictionaryEntry(), DistIface::toggleSync(), Topology::Topology(), LinearEquation::toStr(), Stats::VectorBase< Vector, StatStor >::total(), Stats::VectorProxy< Stat >::total(), Stats::Vector2dBase< Vector2d, StatStor >::total(), Stats::ConstVectorNode< T >::total(), Stats::UnaryNode< Op >::total(), Stats::BinaryNode< Op >::total(), Stats::SumNode< Op >::total(), MinorCPU::totalInsts(), FullO3CPU< O3CPUImpl >::totalInsts(), MinorCPU::totalOps(), FullO3CPU< O3CPUImpl >::totalOps(), TournamentBP::TournamentBP(), Trace::ExeTracerRecord::traceInst(), AbstractMemory::trackLoadLocked(), MultiperspectivePerceptron::train(), ExplicitLTTarget::transport_dbg(), SimpleLTTarget1::transport_dbg(), SimpleLTTarget2::transport_dbg(), SimpleLTTarget_ext::transport_dbg(), ExplicitATTarget::transport_dbg(), PacketQueue::trySatisfyFunctional(), SerialLink::SerialLinkMasterPort::trySatisfyFunctional(), Bridge::BridgeMasterPort::trySatisfyFunctional(), Packet::trySatisfyFunctional(), RubyPort::trySendRetries(), Tsunami::Tsunami(), TsunamiPChip::TsunamiPChip(), EtherBus::txDone(), PersistentTable::typeOfSmallest(), tlm::tlm_analysis_port< T >::unbind(), MultiperspectivePerceptron::uncondBranch(), CxxConfigManager::unRename(), NoMaliGpu::unserialize(), SymbolTable::unserialize(), ArmSemihosting::unserialize(), ArmISA::PMU::unserialize(), X86ISA::I82094AA::unserialize(), AlphaISA::TLB::unserialize(), EmulationPageTable::unserialize(), EtherSwitch::Interface::PortFifo::unserialize(), PowerISA::TLB::unserialize(), DVFSHandler::unserialize(), CpuLocalTimer::unserialize(), VGic::unserialize(), PacketFifo::unserialize(), GenericTimer::unserialize(), PciDevice::unserialize(), PhysicalMemory::unserialize(), Sinic::Device::unserialize(), unserialize(), ArmISA::TLB::unserialize(), BaseCPU::unserialize(), DistIface::RecvScheduler::unserialize(), GicV2::unserialize(), VirtIODeviceBase::unserialize(), Serializable::unserializeGlobals(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), sc_core::sc_signal_rv< W >::update(), Gicv3Distributor::update(), MultiperspectivePerceptron::update(), tlm::tlm_generic_payload::update_extensions_from(), tlm::tlm_generic_payload::update_original_from(), MultiperspectivePerceptron::ThreadData::updateAcyclic(), ArmISA::PMU::updateAllCounters(), ComputeUnit::updateEvents(), TAGEBase::updateGHist(), MultiperspectivePerceptronTAGE::updateHistories(), TAGEBase::updateHistories(), VGic::updateIntState(), ArmV8KvmCPU::updateKvmState(), updateKvmStateFPUCommon(), BaseO3DynInst< Impl >::updateMiscRegs(), TimerTable::updateNext(), MultiperspectivePerceptronTAGE::updatePartial(), MPP_TAGE::updatePathAndGlobalHistory(), TAGE_SC_L_TAGE::updatePathAndGlobalHistory(), TLBCoalescer::updatePhysAddresses(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updatePred(), VectorRegisterFile::updateResources(), GicV2::updateRunPri(), ArmV8KvmCPU::updateThreadContext(), updateThreadContextFPUCommon(), X86KvmCPU::updateThreadContextMSRs(), StackDistCalc::updateTree(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateVec(), utimesFunc(), ActivityRecorder::validate(), Checker< O3CPUImpl >::validateExecution(), DefaultRename< Impl >::validInsts(), DefaultIEW< Impl >::validInstsFromRename(), Stats::VectorBase< Vector, StatStor >::value(), sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::vbind(), sc_gem5::VcdTraceFile::VcdTraceFile(), sc_dt::vec_add_small_on(), sc_dt::vec_complement(), sc_dt::vec_copy(), sc_dt::vec_div_large(), sc_dt::vec_from_char(), sc_dt::vec_mul_small_on(), sc_dt::vec_rem_large(), sc_dt::vec_reverse(), sc_dt::vec_sub_small_on(), sc_dt::vec_zero(), VirtQueue::VirtQueue(), Gicv3CPUInterface::virtualDropPriority(), Gicv3CPUInterface::virtualHighestActivePriority(), Stats::Text::visit(), ArmISA::VldMultOp::VldMultOp(), ArmISA::VldMultOp64::VldMultOp64(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VldSingleOp64::VldSingleOp64(), ArmISA::VstMultOp::VstMultOp(), ArmISA::VstMultOp64::VstMultOp64(), ArmISA::VstSingleOp::VstSingleOp(), ArmISA::VstSingleOp64::VstSingleOp64(), MemDepUnit< MemDepPred, Impl >::wakeDependents(), WalkCache::WalkCache(), Wavefront::Wavefront(), VIPERCoalescer::wbL1(), tlm::tlm_analysis_port< T >::write(), CowDiskImage::write(), GpuDispatcher::write(), Gicv3Redistributor::write(), Gicv3Distributor::write(), VirtQueue::VirtRing< struct vring_used_elem >::write(), CowDiskImage::writeback(), DefaultIEW< Impl >::writebackInsts(), GPUCoalescer::writeCallback(), Packet::writeData(), TraceCPU::ElasticDataGen::GraphNode::writeElementAsTrace(), X86ISA::IntelMP::FloatingPointer::writeOut(), X86ISA::IntelMP::ConfigTable::writeOut(), X86ISA::SMBios::SMBiosTable::writeOut(), writeOutString(), X86ISA::writePackedMem(), X86ISA::E820Table::writeTo(), VGic::writeVCpu(), writevFunc(), PixelConverter::writeWord(), X86ISA::X86MicroopBase::X86MicroopBase(), X86ISA::Cmos::X86RTC::X86RTC(), sc_dt::sc_unsigned::xnor_reduce(), sc_dt::sc_signed::xnor_reduce(), sc_dt::sc_proxy< sc_subref_r< X > >::xor_reduce(), sc_dt::sc_unsigned_subref_r::xor_reduce(), sc_dt::sc_signed_subref_r::xor_reduce(), sc_dt::sc_unsigned::xor_reduce(), sc_dt::sc_signed::xor_reduce(), Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >::ysubname(), Stats::DataWrapVec2d< Derived, Vector2dInfoProxy >::ysubnames(), Stats::VectorBase< Vector, StatStor >::zero(), Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::zero(), Stats::Formula::zero(), ArmISA::ISA::zeroSveVecRegUpperPart(), BaseGlobalEvent::~BaseGlobalEvent(), MPP_StatisticalCorrector::BranchInfo::~BranchInfo(), BrigObject::~BrigObject(), CacheMemory::~CacheMemory(), CallbackQueue::~CallbackQueue(), CheckTable::~CheckTable(), ComputeUnit::~ComputeUnit(), CowDiskImage::~CowDiskImage(), CpuEvent::~CpuEvent(), DirectoryMemory::~DirectoryMemory(), Minor::Execute::~Execute(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::~ExtensionPool(), FUPool::~FUPool(), IniFile::~IniFile(), tlm_utils::instance_specific_extension_container::~instance_specific_extension_container(), MemDepUnit< MemDepPred, Impl >::MemDepEntry::~MemDepEntry(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::~multi_passthrough_initiator_socket(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::~multi_passthrough_target_socket(), PollQueue::~PollQueue(), QTIsaac< ALPHA >::randctx::~randctx(), RubyDirectedTester::~RubyDirectedTester(), RubyTester::~RubyTester(), Minor::LSQ::SplitDataRequest::~SplitDataRequest(), TimeBuffer< DecodeStruct >::~TimeBuffer(), tlm::tlm_generic_payload::~tlm_generic_payload(), Stats::Vector2dBase< Vector2d, StatStor >::~Vector2dBase(), Stats::VectorBase< Vector, StatStor >::~VectorBase(), and Stats::VectorDistBase< VectorAverageDeviation, AvgSampleStor >::~VectorDistBase().
iCacheLineSize
ArmISA::iCacheLineSize
Definition at line 609 of file miscregs_types.hh.
id
Bitfield<33> ArmISA::id
Definition at line 237 of file miscregs_types.hh.
Referenced by Profiler::addAddressTraceSample(), ArmISA::PMU::addEventProbe(), ArmISA::PMU::addSoftwareIncrementEvent(), sc_dt::sc_fxnum_fast::cast(), ArmV8KvmCPU::dump(), ArmKvmCPU::dumpKvmStateMisc(), flit::flit(), sc_dt::sc_fxval_fast::get_bit(), sc_dt::sc_fxnum_fast::get_bit(), sc_dt::sc_fxnum_fast::get_slice(), ArmISA::PMU::getCounter(), BaseKvmCPU::getOneReg(), IDToInt(), sc_dt::scfx_ieee_double::inf(), LSQUnit< Impl >::init(), InputUnit::InputUnit(), Iris::ThreadContext::instanceRegistryChanged(), intToID(), sc_dt::sc_fxval_fast::is_inf(), sc_dt::sc_fxval_fast::is_nan(), sc_dt::sc_fxval_fast::is_neg(), sc_dt::sc_fxnum_fast::is_neg(), sc_dt::sc_fxval_fast::is_normal(), sc_dt::sc_fxnum_fast::is_normal(), sc_dt::sc_fxval_fast::is_zero(), sc_dt::sc_fxnum_fast::is_zero(), System::lookupMasterId(), sc_dt::scfx_ieee_double::nan(), OutputUnit::OutputUnit(), OutVcState::OutVcState(), QoS::Policy::pair(), TrafficGen::parseConfig(), sc_dt::print_other(), AnnotateDumpCallback::process(), sc_core::sc_report::register_id(), ArmISA::PMU::registerEvent(), System::registerThreadContext(), sc_core::sc_report_handler::report(), Minor::Fetch1::FetchRequest::reportData(), Minor::ForwardLineData::reportData(), sc_dt::scfx_rep::scfx_rep(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_user_id(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_user_id(), sc_dt::sc_fxnum_fast::set_bit(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_dmi_user_id(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_dmi_user_id(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_dmi_user_id(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_user_id(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_user_id(), sc_dt::sc_fxnum_fast::set_slice(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_user_id(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_user_id(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_user_id(), ThreadState::setContextId(), Iris::ThreadContext::setContextId(), Network::setFromNetQueue(), BaseKvmCPU::setOneReg(), ThreadState::setThreadId(), Iris::ThreadContext::setThreadId(), Network::setToNetQueue(), BaseCPU::taskId(), Request::taskId(), sc_dt::scfx_rep::to_double(), and VirtualChannel::VirtualChannel().
idc
Bitfield<7> ArmISA::idc
Definition at line 411 of file miscregs_types.hh.
ide
Bitfield<15> ArmISA::ide
Definition at line 417 of file miscregs_types.hh.
Referenced by IGbE::TxDescCache::pktComplete().
ids
Bitfield<39, 36> ArmISA::ids
Definition at line 152 of file miscregs_types.hh.
iesb
Bitfield<15, 12> ArmISA::iesb
Definition at line 158 of file miscregs_types.hh.
il
Bitfield< 25 > ArmISA::il
Definition at line 60 of file miscregs_types.hh.
illegalExecution
Bitfield<61> ArmISA::illegalExecution
Definition at line 73 of file types.hh.
imm
Bitfield<7, 0> ArmISA::imm
Definition at line 142 of file types.hh.
Referenced by ArmISA::ArmStaticInst::ArmStaticInst(), ArmISA::BranchImm::generateDisassembly(), SparcISA::MemImm::generateDisassembly(), SparcISA::IntOpImm::generateDisassembly(), MsrImmOp::generateDisassembly(), SparcISA::BlockMemImmMicro::generateDisassembly(), SparcISA::WrPrivImm::generateDisassembly(), SparcISA::BranchImm13::generateDisassembly(), PowerISA::IntImmOp::generateDisassembly(), SparcISA::SetHi::generateDisassembly(), ArmISA::MemoryImm64::generateDisassembly(), ImmOp::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), RegImmOp::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::MemoryPreIndex64::generateDisassembly(), RegImmRegOp::generateDisassembly(), ArmISA::MemoryPostIndex64::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), ArmISA::SveUnaryWideImmUnpredOp::generateDisassembly(), ArmISA::SveUnaryWideImmPredOp::generateDisassembly(), ArmISA::PredImmOp::generateDisassembly(), ArmISA::SveBinImmUnpredConstrOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), RegRegImmOp::generateDisassembly(), ArmISA::SveBinImmPredOp::generateDisassembly(), ArmISA::PredIntOp::generateDisassembly(), ArmISA::SveBinWideImmUnpredOp::generateDisassembly(), ArmISA::DataImmOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::SveCmpImmOp::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::SveTerImmUnpredOp::generateDisassembly(), ArmISA::SvePtrueOp::generateDisassembly(), ArmISA::SveIntCmpImmOp::generateDisassembly(), ArmISA::SveElemCountOp::generateDisassembly(), ArmISA::SveBinImmUnpredDestrOp::generateDisassembly(), ArmISA::SveBinImmIdxUnpredOp::generateDisassembly(), ArmISA::SveDotProdIdxOp::generateDisassembly(), ArmISA::SveComplexIdxOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegRegImmOp::generateDisassembly(), ArmISA::MemoryImm::printOffset(), SparcISA::IntOpImm::printPseudoOps(), ArmISA::ArmStaticInst::softwareBreakpoint32(), ArmISA::SveComplexIdxOp::SveComplexIdxOp(), sveDecodePredCount(), and vfpFpToFixed().
imm16
Bitfield<15, 0> ArmISA::imm16
Definition at line 636 of file miscregs_types.hh.
immed11_0
Bitfield<11, 0> ArmISA::immed11_0
Definition at line 146 of file types.hh.
immed23_0
Bitfield<23, 0> ArmISA::immed23_0
Definition at line 156 of file types.hh.
immed7_0
Bitfield<7, 0> ArmISA::immed7_0
Definition at line 147 of file types.hh.
immedHi11_8
Bitfield<11, 8> ArmISA::immedHi11_8
Definition at line 149 of file types.hh.
immedLo3_0
Bitfield<3, 0> ArmISA::immedLo3_0
Definition at line 150 of file types.hh.
imo
Bitfield<4> ArmISA::imo
Definition at line 268 of file miscregs_types.hh.
instBits
uint32_t ArmISA::instBits
Definition at line 97 of file types.hh.
interptCtrlPresent
Bitfield<23> ArmISA::interptCtrlPresent
Definition at line 602 of file miscregs_types.hh.
IntReg64Map
const IntRegMap ArmISA::IntReg64Map
Initial value:
= {
    INTREG_R0,      INTREG_R1,      INTREG_R2,      INTREG_R3,
    INTREG_R4,      INTREG_R5,      INTREG_R6,      INTREG_R7,
    INTREG_R8_USR,  INTREG_R9_USR,  INTREG_R10_USR, INTREG_R11_USR,
    INTREG_R12_USR, INTREG_R13_USR, INTREG_R14_USR, INTREG_R13_HYP,
    INTREG_R14_IRQ, INTREG_R13_IRQ, INTREG_R14_SVC, INTREG_R13_SVC,
    INTREG_R14_ABT, INTREG_R13_ABT, INTREG_R14_UND, INTREG_R13_UND,
    INTREG_R8_FIQ,  INTREG_R9_FIQ,  INTREG_R10_FIQ, INTREG_R11_FIQ,
    INTREG_R12_FIQ, INTREG_R13_FIQ, INTREG_R14_FIQ, INTREG_ZERO
}
Definition at line 306 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap(), and ArmV8KvmCPU::updateThreadContext().
IntRegAbtMap
const IntRegMap ArmISA::IntRegAbtMap
Initial value:
= {
    INTREG_R0_ABT,  INTREG_R1_ABT,  INTREG_R2_ABT,  INTREG_R3_ABT,
    INTREG_R4_ABT,  INTREG_R5_ABT,  INTREG_R6_ABT,  INTREG_R7_ABT,
    INTREG_R8_ABT,  INTREG_R9_ABT,  INTREG_R10_ABT, INTREG_R11_ABT,
    INTREG_R12_ABT, INTREG_R13_ABT, INTREG_R14_ABT, INTREG_R15_ABT,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 389 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegFiqMap
const IntRegMap ArmISA::IntRegFiqMap
Initial value:
= {
    INTREG_R0_FIQ,  INTREG_R1_FIQ,  INTREG_R2_FIQ,  INTREG_R3_FIQ,
    INTREG_R4_FIQ,  INTREG_R5_FIQ,  INTREG_R6_FIQ,  INTREG_R7_FIQ,
    INTREG_R8_FIQ,  INTREG_R9_FIQ,  INTREG_R10_FIQ, INTREG_R11_FIQ,
    INTREG_R12_FIQ, INTREG_R13_FIQ, INTREG_R14_FIQ, INTREG_R15_FIQ,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 443 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegHypMap
const IntRegMap ArmISA::IntRegHypMap
Initial value:
= {
    INTREG_R0_HYP,  INTREG_R1_HYP,  INTREG_R2_HYP,  INTREG_R3_HYP,
    INTREG_R4_HYP,  INTREG_R5_HYP,  INTREG_R6_HYP,  INTREG_R7_HYP,
    INTREG_R8_HYP,  INTREG_R9_HYP,  INTREG_R10_HYP, INTREG_R11_HYP,
    INTREG_R12_HYP, INTREG_R13_HYP, INTREG_R14_HYP, INTREG_R15_HYP,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 335 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegIrqMap
const IntRegMap ArmISA::IntRegIrqMap
Initial value:
= {
    INTREG_R0_IRQ,  INTREG_R1_IRQ,  INTREG_R2_IRQ,  INTREG_R3_IRQ,
    INTREG_R4_IRQ,  INTREG_R5_IRQ,  INTREG_R6_IRQ,  INTREG_R7_IRQ,
    INTREG_R8_IRQ,  INTREG_R9_IRQ,  INTREG_R10_IRQ, INTREG_R11_IRQ,
    INTREG_R12_IRQ, INTREG_R13_IRQ, INTREG_R14_IRQ, INTREG_R15_IRQ,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 425 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegMonMap
const IntRegMap ArmISA::IntRegMonMap
Initial value:
= {
    INTREG_R0_MON,  INTREG_R1_MON,  INTREG_R2_MON,  INTREG_R3_MON,
    INTREG_R4_MON,  INTREG_R5_MON,  INTREG_R6_MON,  INTREG_R7_MON,
    INTREG_R8_MON,  INTREG_R9_MON,  INTREG_R10_MON, INTREG_R11_MON,
    INTREG_R12_MON, INTREG_R13_MON, INTREG_R14_MON, INTREG_R15_MON,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 371 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
intRegsPerMode
const unsigned ArmISA::intRegsPerMode = NUM_INTREGS static
Definition at line 461 of file intregs.hh.
Referenced by flattenIntRegModeIndex().
IntRegSvcMap
const IntRegMap ArmISA::IntRegSvcMap
Initial value:
= {
    INTREG_R0_SVC,  INTREG_R1_SVC,  INTREG_R2_SVC,  INTREG_R3_SVC,
    INTREG_R4_SVC,  INTREG_R5_SVC,  INTREG_R6_SVC,  INTREG_R7_SVC,
    INTREG_R8_SVC,  INTREG_R9_SVC,  INTREG_R10_SVC, INTREG_R11_SVC,
    INTREG_R12_SVC, INTREG_R13_SVC, INTREG_R14_SVC, INTREG_R15_SVC,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 353 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegUndMap
const IntRegMap ArmISA::IntRegUndMap
Initial value:
= {
    INTREG_R0_UND,  INTREG_R1_UND,  INTREG_R2_UND,  INTREG_R3_UND,
    INTREG_R4_UND,  INTREG_R5_UND,  INTREG_R6_UND,  INTREG_R7_UND,
    INTREG_R8_UND,  INTREG_R9_UND,  INTREG_R10_UND, INTREG_R11_UND,
    INTREG_R12_UND, INTREG_R13_UND, INTREG_R14_UND, INTREG_R15_UND,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 407 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
IntRegUsrMap
const IntRegMap ArmISA::IntRegUsrMap
Initial value:
= {
    INTREG_R0_USR,  INTREG_R1_USR,  INTREG_R2_USR,  INTREG_R3_USR,
    INTREG_R4_USR,  INTREG_R5_USR,  INTREG_R6_USR,  INTREG_R7_USR,
    INTREG_R8_USR,  INTREG_R9_USR,  INTREG_R10_USR, INTREG_R11_USR,
    INTREG_R12_USR, INTREG_R13_USR, INTREG_R14_USR, INTREG_R15_USR,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,
    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO,    INTREG_ZERO
}
Definition at line 317 of file intregs.hh.
Referenced by ArmISA::ISA::updateRegMap().
INTRLVREG0
const int ArmISA::INTRLVREG0 = NumVecV8ArchRegs + NumVecSpecialRegs
Definition at line 100 of file registers.hh.
Referenced by ArmISA::SveLdStructSI< Element, MicroopLdMemType, MicroopDeIntrlvType >::SveLdStructSI(), ArmISA::SveLdStructSS< Element, MicroopLdMemType, MicroopDeIntrlvType >::SveLdStructSS(), ArmISA::SveStStructSI< Element, MicroopStMemType, MicroopIntrlvType >::SveStStructSI(), and ArmISA::SveStStructSS< Element, MicroopStMemType, MicroopIntrlvType >::SveStStructSS().
INTRLVREG1
const int ArmISA::INTRLVREG1 = INTRLVREG0 + 1
Definition at line 101 of file registers.hh.
INTRLVREG2
const int ArmISA::INTRLVREG2 = INTRLVREG0 + 2
Definition at line 102 of file registers.hh.
INTRLVREG3
const int ArmISA::INTRLVREG3 = INTRLVREG0 + 3
Definition at line 103 of file registers.hh.
ioe
Bitfield<8> ArmISA::ioe
Definition at line 412 of file miscregs_types.hh.
ips
Bitfield< 34, 32 > ArmISA::ips
Definition at line 480 of file miscregs_types.hh.
ir0
ArmISA::ir0
Definition at line 568 of file miscregs_types.hh.
ir1
Bitfield<3,2> ArmISA::ir1
Definition at line 569 of file miscregs_types.hh.
ir2
Bitfield<5,4> ArmISA::ir2
Definition at line 570 of file miscregs_types.hh.
ir3
Bitfield<7,6> ArmISA::ir3
Definition at line 571 of file miscregs_types.hh.
ir4
Bitfield<9,8> ArmISA::ir4
Definition at line 572 of file miscregs_types.hh.
ir5
Bitfield<11,10> ArmISA::ir5
Definition at line 573 of file miscregs_types.hh.
ir6
Bitfield<13,12> ArmISA::ir6
Definition at line 574 of file miscregs_types.hh.
ir7
Bitfield<15,14> ArmISA::ir7
Definition at line 575 of file miscregs_types.hh.
irgn0
Bitfield< 9, 8 > ArmISA::irgn0
Definition at line 469 of file miscregs_types.hh.
irgn1
Bitfield< 25, 24 > ArmISA::irgn1
Definition at line 476 of file miscregs_types.hh.
irq
Bitfield<1> ArmISA::irq
Definition at line 310 of file miscregs_types.hh.
Referenced by KvmVM::setIRQLine().
isMisc
Bitfield<32> ArmISA::isMisc
Definition at line 95 of file types.hh.
it1
Bitfield<26, 25> ArmISA::it1
Definition at line 56 of file miscregs_types.hh.
Referenced by FutexMap::requeue().
it2
Bitfield<15, 10> ArmISA::it2
Definition at line 62 of file miscregs_types.hh.
Referenced by FutexMap::requeue().
itd
Bitfield<7> ArmISA::itd
Definition at line 356 of file miscregs_types.hh.
Referenced by getRestoredITBits().
itstate
Bitfield<55, 48> ArmISA::itstate
Definition at line 80 of file types.hh.
Referenced by EndBitUnion().
itstateCond
Bitfield<55, 52> ArmISA::itstateCond
Definition at line 81 of file types.hh.
itstateMask
Bitfield<51, 48> ArmISA::itstateMask
Definition at line 82 of file types.hh.
ixc
Bitfield<4> ArmISA::ixc
Definition at line 410 of file miscregs_types.hh.
ixe
Bitfield<12> ArmISA::ixe
Definition at line 416 of file miscregs_types.hh.
j
Bitfield<24> ArmISA::j
Definition at line 57 of file miscregs_types.hh.
Referenced by DRAMCtrl::activateBank(), Histogram::add(), ArmISA::Crypto::aesInvMixColumns(), ArmISA::Crypto::aesMixColumns(), ScheduleStage::arbitrate(), Set::broadcast(), FALRU::CacheTracking::check(), SwitchAllocator::check_for_wakeup(), MipsISA::ISA::clear(), SwitchAllocator::clear_request_vector(), Profiler::collateStats(), Router::collateStats(), GarnetNetwork::collateStats(), MemChecker::completeRead(), MultiperspectivePerceptron::computeOutput(), BaseTags::computeStats(), ComputeUnit::ComputeUnit(), LdsState::countBankConflicts(), crc32(), Topology::createLinks(), DictionaryCompressor< uint64_t >::decompress(), DRAMCtrl::doDRAMAccess(), ObjectMatch::domatch(), Trace::Logger::dump(), dumpFpuCommon(), SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), FetchStage::exec(), FetchUnit::exec(), ScheduleStage::exec(), Topology::extend_shortest_path(), FetchStage::FetchStage(), sc_dt::scfx_rep::from_string(), Minor::FUPipeline::FUPipeline(), FUPool::FUPool(), sc_dt::sc_fxval_fast::get_bit(), sc_dt::sc_fxnum_fast::get_bit(), sc_dt::sc_concref_r< X, Y >::get_cword(), sc_dt::scfx_rep::get_slice(), sc_dt::sc_fxnum_fast::get_slice(), sc_dt::sc_concref_r< X, Y >::get_word(), NetDest::getAllDest(), MultiperspectivePerceptron::PATH::getHash(), MultiperspectivePerceptron::GHISTPATH::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), Prefetcher::getPrefetchEntry(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), TAGE_SC_L_TAGE_8KB::handleAllocAndUReset(), TAGE_SC_L_TAGE_64KB::handleAllocAndUReset(), MPP_TAGE::handleUReset(), TAGE_SC_L_TAGE::handleUReset(), TAGEBase::handleUReset(), SwitchAllocator::init(), FetchStage::init(), CacheMemory::init(), FetchUnit::init(), ScheduleStage::init(), ComputeUnit::init(), FALRU::CacheTracking::init(), MPP_StatisticalCorrector::initBias(), StatisticalCorrector::initBias(), StatisticalCorrector::initGEHLTable(), MultiperspectivePerceptron::insertModhistSpec(), MultiperspectivePerceptron::insertModpathSpec(), MultiperspectivePerceptron::ThreadData::insertRecency(), ClDriver::ioctl(), ComputeUnit::isDone(), GPUCoalescer::issueRequest(), EcoffObject::loadLocalSymbols(), QoS::MemCtrl::logRequest(), QoS::MemCtrl::logResponse(), ArmISA::MacroVFPMemOp::MacroVFPMemOp(), DRAMCtrl::minBankPrep(), TrafficGen::parseConfig(), NetDest::print(), CacheMemory::print(), sc_dt::print_other(), printSorted(), SimpleDisk::read(), TraceCPU::ElasticDataGen::InputStream::read(), Wavefront::ready(), ComputeUnit::ReadyWorkgroup(), CacheMemory::recordCacheContents(), Sequencer::regStats(), Profiler::regStats(), GPUCoalescer::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), BaseXBar::regStats(), System::regStats(), sc_dt::scfx_string::remove(), Sequencer::resetStats(), Router::resetStats(), GPUCoalescer::resetStats(), InputUnit::resetStats(), sc_dt::scfx_string::resize(), sc_dt::scfx_rep::resize(), sc_dt::sc_proxy< sc_subref_r< X > >::reverse(), SC_MODULE(), sc_dt::scfx_csd2tc(), sc_dt::scfx_tc2csd(), ScheduleStage::ScheduleStage(), sc_dt::sc_concref_r< X, Y >::set_cword(), sc_dt::scfx_rep::set_slice(), sc_dt::sc_fxnum_fast::set_slice(), sc_dt::sc_concref_r< X, Y >::set_word(), MultiperspectivePerceptron::ACYCLIC::setBitRequirements(), MultiperspectivePerceptron::BLURRYPATH::setBitRequirements(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), NetDest::smallestElement(), MultiperspectivePerceptron::ThreadData::ThreadData(), MultiperspectivePerceptron::train(), MultiperspectivePerceptron::update(), MultiperspectivePerceptronTAGE::updateHistories(), ArmV8KvmCPU::updateKvmState(), ArmV8KvmCPU::updateThreadContext(), sc_dt::vec_reverse(), sc_dt::vec_shift_left(), sc_dt::vec_shift_right(), Stats::Text::visit(), CacheMemory::~CacheMemory(), ComputeUnit::~ComputeUnit(), Shader::~Shader(), and System::~System().
jscvt
Bitfield<15, 12> ArmISA::jscvt
Definition at line 114 of file miscregs_types.hh.
l1IndexPolicy
Bitfield<15,14> ArmISA::l1IndexPolicy
Definition at line 611 of file miscregs_types.hh.
l2rstDISABLE_monitor
Bitfield<31> ArmISA::l2rstDISABLE_monitor
Definition at line 605 of file miscregs_types.hh.
len
ArmISA::len
Definition at line 418 of file miscregs_types.hh.
Referenced by CircularQueue< char >::advance_tail(), sc_dt::sc_proxy< sc_subref_r< X > >::and_reduce(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::sc_bv_base::assign_from_string(), sc_dt::sc_lv_base::assign_from_string(), GPUCoalescer::atomicCallback(), sc_dt::sc_subref_r< X >::check_bounds(), VncServer::checkProtocolVersion(), BaseRemoteGDB::cmd_clr_hw_bkpt(), BaseRemoteGDB::cmd_mem_r(), BaseRemoteGDB::cmd_mem_w(), BaseRemoteGDB::cmd_set_hw_bkpt(), AtagCmdline::cmdline(), GPUCoalescer::completeHitCallback(), GPUCoalescer::completeIssue(), MultiperspectivePerceptron::computeBits(), sc_dt::sc_int_subref_r::concat_get_uint64(), Terminal::data(), DMASequencer::dataCallback(), Trace::Logger::dprintf(), Trace::Logger::dump(), cp::Print::end_args(), tlm::tlm_endian_context::establish_bebuf(), tlm::tlm_endian_context::establish_dbuf(), ArmISA::ArmStaticInst::extendReg64(), Net::Ip6Hdr::extensionLength(), fallocateFunc(), DtbFile::findReleaseAddr(), ArmSemihosting::File::flen(), ArmISA::ISA::getCurSveVecLenInBits(), VirtQueue::getDescriptor(), GPUCoalescer::getFirstResponseToCompletionDelayHist(), WriteMask::getMask(), getsocknameFunc(), getsockoptFunc(), GPUCoalescer::hitCallback(), PseudoInst::initParam(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), DMASequencer::makeRequest(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_subref< X >::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), Net::IpHdr::options(), Net::TcpHdr::options(), sc_dt::sc_proxy< sc_subref_r< X > >::or_reduce(), sc_dt::print_dec(), Printk(), cp::Print::process(), HardBreakpoint::process(), BrigObject::processDirectives(), VirtQueue::produceDescriptor(), Terminal::read(), ArmSemihosting::FileFeatures::read(), PseudoInst::readfile(), ArmSemihosting::readString(), EtherTapStub::recvReal(), ComputeUnit::DataPort::recvReqRetry(), ComputeUnit::SQCPort::recvReqRetry(), ComputeUnit::DTLBPort::recvReqRetry(), ComputeUnit::ITLBPort::recvReqRetry(), PS2TouchKit::recvTouchKit(), PacketFifo::remove(), PacketFifo::reserve(), sc_dt::sc_proxy< sc_subref_r< X > >::reverse(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), sc_dt::scfx_csd2tc(), ArmSemihosting::semiTick(), VncServer::sendError(), EtherTapStub::sendReal(), EtherTapBase::sendSimulated(), WriteMask::setMask(), setsockoptFunc(), ArmISA::Decoder::setSveLen(), KvmVM::setUserMemoryRegion(), Net::TcpOpt::size(), Stats::VectorProxy< Stat >::size(), BaseRemoteGDB::system(), sc_dt::sc_proxy< sc_subref_r< X > >::to_anything_signed(), sc_dt::sc_proxy< sc_subref_r< X > >::to_anything_unsigned(), to_lower(), sc_dt::sc_proxy< sc_subref_r< X > >::to_string(), sc_dt::sc_uint_base::to_string(), sc_dt::sc_int_base::to_string(), sc_dt::sc_unsigned::to_string(), sc_dt::sc_signed::to_string(), sc_dt::sc_proxy< sc_subref_r< X > >::to_uint64(), DmaReadFifo::tryGet(), VirtIOConsole::TermRecvQueue::trySend(), PseudoInst::writefile(), sc_dt::sc_proxy< sc_subref_r< X > >::xor_reduce(), and DataBlock::~DataBlock().
lo
Bitfield<19, 16> ArmISA::lo
Definition at line 139 of file miscregs_types.hh.
Referenced by Trace::TarmacParserRecord::advanceTrace(), sc_dt::sc_proxy< sc_subref_r< X > >::operator()(), and sc_dt::sc_proxy< sc_subref_r< X > >::range().
loadOp
Bitfield<20> ArmISA::loadOp
Definition at line 137 of file types.hh.
lpae
Bitfield< 11 > ArmISA::lpae
Definition at line 398 of file miscregs_types.hh.
lrcpc
Bitfield<23, 20> ArmISA::lrcpc
Definition at line 112 of file miscregs_types.hh.
lsm
Bitfield<11, 8> ArmISA::lsm
Definition at line 159 of file miscregs_types.hh.
Referenced by AnnotateDumpCallback::process().
ltcoproc
Bitfield<11, 8> ArmISA::ltcoproc
Definition at line 212 of file types.hh.
ltopcode11_8
Bitfield<11, 8> ArmISA::ltopcode11_8
Definition at line 206 of file types.hh.
ltopcode15
Bitfield<15> ArmISA::ltopcode15
Definition at line 205 of file types.hh.
ltopcode4
Bitfield<4> ArmISA::ltopcode4
Definition at line 209 of file types.hh.
ltopcode7_4
Bitfield<7, 4> ArmISA::ltopcode7_4
Definition at line 208 of file types.hh.
ltopcode7_6
Bitfield<7, 6> ArmISA::ltopcode7_6
Definition at line 207 of file types.hh.
ltrd
Bitfield<11, 8> ArmISA::ltrd
Definition at line 211 of file types.hh.
m
Bitfield<0> ArmISA::m
Definition at line 368 of file miscregs_types.hh.
Referenced by PhysicalMemory::access(), SrcClockDomain::clockPeriod(), RealViewOsc::clockPeriod(), PhysicalMemory::createBackingStore(), MessageBuffer::delayHead(), LocalMemPipeline::exec(), GlobalMemPipeline::exec(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), NetworkInterface::flitisizeMessage(), PhysicalMemory::functionalAccess(), ArmISA::TLB::getTableWalker(), ArmISA::TableWalker::getTlb(), sc_gem5::Kernel::init(), init_drain(), init_net(), init_range(), init_serialize(), QTIsaac< ALPHA >::isaac(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), HsailISA::Call::MagicLoadGlobalU32Reg(), MemoryImage::mask(), sc_core::operator<<(), pybind_init_event(), pybind_init_stats(), pybind_init_tracers(), Stats::pythonDump(), Stats::pythonReset(), QoS::MemCtrl::qosSchedule(), QTIsaac< ALPHA >::randinit(), MessageBuffer::reanalyzeList(), sc_gem5::Kernel::regStats(), sc_gem5::reportIdToMsgMap(), sc_gem5::reportMsgInfoMap(), PybindSimObjectResolver::resolveSimObject(), QTIsaac< ALPHA >::rngstep(), sc_core::sc_export_base::sc_export_base(), sc_core::sc_port_base::sc_port_base(), PhysicalMemory::serialize(), DistEtherLink::TxLink::setDistInt(), DistEtherLink::RxLink::setDistInt(), ArmISA::TLB::setMMU(), ArmISA::TableWalker::setMMU(), KvmVM::setUserMemoryRegion(), Topology::shortest_path_to_node(), sc_gem5::Kernel::startup(), RealViewOsc::startup(), ComputeUnit::StartWorkgroup(), stattest_init_pybind(), sc_gem5::Kernel::stopWork(), PhysicalMemory::unserialize(), DerivedClockDomain::updateClockPeriod(), Gicv2m::write(), BaseXBar::~BaseXBar(), QTIsaac< ALPHA >::randctx::~randctx(), and DistEtherLink::RxLink::~RxLink().
m5Func
Bitfield<15, 8> ArmISA::m5Func
Definition at line 166 of file types.hh.
MachineBytes
const int ArmISA::MachineBytes = 4
Definition at line 94 of file isa_traits.hh.
Referenced by getArgument().
mask
Bitfield<3, 0> ArmISA::mask
Definition at line 64 of file types.hh.
Referenced by FALRU::accessBlock(), AddrRange::AddrRange(), BaseKvmCPU::archIsDrained(), ArmProcess::argsInit(), BiModeBP::BiModeBP(), MultiSocketSimpleSwitchAT::bindTargetSocket(), SparcISA::buildPstateMask(), CopyEngine::CopyEngineChannel::channelWrite(), ArmISA::TLB::checkPermissions(), ArmISA::TLB::checkPermissions64(), sc_dt::sc_lv_base::clean_tail(), sc_dt::sc_uint_subref_r::concat_get_ctrl(), sc_dt::sc_int_subref_r::concat_get_ctrl(), sc_dt::sc_uint_base::concat_get_ctrl(), sc_dt::sc_int_base::concat_get_ctrl(), sc_dt::sc_unsigned::concat_get_ctrl(), sc_dt::sc_uint_subref_r::concat_get_data(), sc_dt::sc_int_subref_r::concat_get_data(), sc_dt::sc_uint_base::concat_get_data(), sc_dt::sc_int_base::concat_get_data(), sc_dt::sc_unsigned::concat_get_data(), sc_dt::sc_unsigned_subref::concat_set(), ArmISA::ArmStaticInst::cpsrWriteByInstr(), GenericPciHost::decodeAddress(), DictionaryCompressor< T >::UncompressedPattern< BaseType >::decompress(), DictionaryCompressor< T >::MaskedPattern< mask >::decompress(), SparcISA::doNormalFault(), SMMUTranslationProcess::doReadPTE(), SparcISA::doREDFault(), HDLcd::enabled(), ArmISA::ArmStaticInst::encoding(), EndBitUnion(), HsailISA::Call::execPseudoInst(), HsailISA::LdaInst< DestDataType, AddrOperandType >::execute(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::Ret::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), ArmISA::ArmStaticInst::extendReg64(), findParity(), findZero(), fixFpDFpSDest(), fixFpSFpDDest(), PixelConverter::Channel::fromPixel(), SparcISA::getHyperVector(), SparcISA::getPrivVector(), AddrRange::granularity(), DMASequencer::init(), PowerISA::PowerStaticInst::insertCRField(), PowerISA::IntRotateOp::IntRotateOp(), DictionaryCompressor< T >::MaskedPattern< mask >::isPattern(), DictionaryCompressor< T >::MaskedValuePattern< 0, 0xFFFFFFFFFFFFFFFF >::isPattern(), DictionaryCompressor< T >::DeltaPattern< DeltaSizeBits >::isValidDelta(), HsailISA::Call::MagicJoinWFBar(), HsailISA::Call::MagicMaskLower(), HsailISA::Call::MagicMaskUpper(), HsailISA::Call::MagicMostSigBroadcast(), HsailISA::Call::MagicMostSigThread(), HsailISA::Call::MagicPanic(), HsailISA::Call::MagicPrefixSum(), HsailISA::Call::MagicPrintLane(), HsailISA::Call::MagicPrintLane64(), HsailISA::Call::MagicPrintWF32(), HsailISA::Call::MagicPrintWF32ID(), HsailISA::Call::MagicPrintWF64(), HsailISA::Call::MagicPrintWFFloat(), HsailISA::Call::MagicPrintWFID64(), HsailISA::Call::MagicReduction(), HsailISA::Call::MagicWaitWFBar(), HsailISA::Call::MagicXactCasLd(), SMMUCommandExecProcess::main(), SparcISA::TLB::MakeTsbPtr(), ArmISA::Stage2LookUp::mergeTe(), mul62x62(), BaseCPU::mwait(), BaseCPU::mwaitAtomic(), sc_dt::sc_uint_subref::operator=(), sc_dt::sc_int_subref::operator=(), sc_dt::sc_unsigned_subref::operator=(), sc_dt::sc_signed_subref::operator=(), sc_gem5::VcdTraceValInt< T >::output(), V7LPageTableOps::pageMask(), V8PageTableOps4k::pageMask(), V8PageTableOps16k::pageMask(), V8PageTableOps64k::pageMask(), ArmSystem::physAddrMask(), Printk(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), ArmISA::TableWalker::processWalkAArch64(), purifyTaggedAddr(), ArmISA::ISA::MiscRegLUTEntryInitializer::rao(), ArmISA::ISA::MiscRegLUTEntryInitializer::raz(), IGbE::read(), ArmISA::ISA::readMiscReg(), ArmISA::ISA::readMiscRegNoEffect(), Iob::receiveDeviceInterrupt(), UFSHostDevice::requestHandler(), ArmISA::ISA::MiscRegLUTEntryInitializer::res0(), ArmISA::ISA::MiscRegLUTEntryInitializer::res1(), roundDown(), roundUp(), SMMUTranslationProcess::sendEvent(), Iob::serialize(), sc_dt::sc_bv_base::set_bit(), sc_dt::sc_lv_base::set_bit(), SparcISA::ISA::setFSReg(), Pl011::setInterrupts(), HDLcd::setInterrupts(), ArmISA::ISA::setMiscReg(), ArmISA::ArmStaticInst::shiftReg64(), ArmISA::ArmStaticInst::spsrWriteByInstr(), ArmISA::Interrupts::takeInt(), TEST(), tlm::tlm_to_hostendian_single(), AddrRange::to_string(), sc_dt::sc_concatref::to_uint64(), PixelConverter::Channel::toPixel(), TournamentBP::TournamentBP(), SparcISA::PageTableEntry::translate(), ArmISA::TLB::translateFs(), ArmISA::TLB::translateSe(), Iob::unserialize(), ArmISA::TlbEntry::updateAttributes(), SignaturePathPrefetcher::updateSignature(), vcvtFpFpH(), vcvtFpHFp(), sc_dt::vec_from_char(), sc_dt::vec_shift_left(), sc_dt::vec_shift_right(), vfpFpToFixed(), vfpSFixedToFpD(), vfpSFixedToFpS(), X86ISA::vtophys(), V7LPageTableOps::walkMask(), V8PageTableOps4k::walkMask(), V8PageTableOps16k::walkMask(), V8PageTableOps64k::walkMask(), IGbE::write(), GicV2::writeDistributor(), sc_dt::sc_uint_base::xor_reduce(), sc_dt::sc_int_base::xor_reduce(), and DataBlock::~DataBlock().
MaxInstSrcRegs
const int ArmISA::MaxInstSrcRegs
Initial value:
= ArmISAInst::MaxInstDestRegs +
    ArmISAInst::MaxInstSrcRegs
Definition at line 59 of file registers.hh.
Referenced by TraceCPU::ElasticDataGen::InputStream::read(), and BaseDynInst< Impl >::renamedSrcRegIdx().
MaxPhysAddrRange
const unsigned ArmISA::MaxPhysAddrRange = 48
Definition at line 92 of file isa_traits.hh.
Referenced by ArmISA::TableWalker::checkAddrSizeFaultAArch64(), and ArmISA::TableWalker::doLongDescriptor().
MaxSveVecLenInBits
constexpr unsigned ArmISA::MaxSveVecLenInBits = 2048
Definition at line 762 of file types.hh.
MaxSveVecLenInBytes
constexpr unsigned ArmISA::MaxSveVecLenInBytes = MaxSveVecLenInBits >> 3
Definition at line 767 of file types.hh.
MaxSveVecLenInDWords
constexpr unsigned ArmISA::MaxSveVecLenInDWords = MaxSveVecLenInBits >> 6
Definition at line 769 of file types.hh.
Referenced by Trace::ArmNativeTrace::ThreadState::update().
MaxSveVecLenInWords
constexpr unsigned ArmISA::MaxSveVecLenInWords = MaxSveVecLenInBits >> 5
Definition at line 768 of file types.hh.
mediaOpcode
Bitfield<24, 20> ArmISA::mediaOpcode
Definition at line 103 of file types.hh.
miscOpcode
Bitfield<7, 4> ArmISA::miscOpcode
Definition at line 115 of file types.hh.
miscRegInfo
std::bitset< NUM_MISCREG_INFOS > ArmISA::miscRegInfo
Definition at line 2846 of file miscregs.cc.
Referenced by canReadAArch64SysReg(), canReadCoprocReg(), canWriteAArch64SysReg(), canWriteCoprocReg(), ArmISA::ISA::flattenMiscIndex(), ArmISA::ISA::getMiscIndices(), ArmV8KvmCPU::getSysRegMap(), ArmISA::ISA::InitReg(), preUnflattenMiscReg(), ArmISA::ISA::readMiscReg(), ArmISA::ISA::setMiscReg(), snsBankedIndex(), and ArmISA::ISA::snsBankedIndex64().
miscRegName
const char* const ArmISA::miscRegName[]
Definition at line 1003 of file miscregs.hh.
Referenced by ArmV8KvmCPU::dump(), ArmKvmCPU::dumpKvmStateCoProc(), ArmKvmCPU::dumpKvmStateCore(), ArmKvmCPU::dumpKvmStateVFP(), getMiscRegName(), ArmV8KvmCPU::getSysRegMap(), ArmISA::ArmStaticInst::printMiscReg(), Minor::printRegName(), ArmISA::DummyISADevice::readMiscReg(), ArmISA::PMU::readMiscReg(), GenericTimer::readMiscReg(), GenericTimerISA::readMiscReg(), Gicv3CPUInterface::readMiscReg(), ArmISA::ISA::readMiscReg(), ArmISA::PMU::readMiscRegInt(), ArmISA::ISA::readMiscRegNoEffect(), ArmISA::DummyISADevice::setMiscReg(), ArmISA::PMU::setMiscReg(), GenericTimer::setMiscReg(), GenericTimerISA::setMiscReg(), Gicv3CPUInterface::setMiscReg(), ArmISA::ISA::setMiscReg(), ArmKvmCPU::updateKvmStateCoProc(), ArmKvmCPU::updateKvmStateVFP(), Trace::TarmacTracerRecord::TraceRegEntry::updateMisc(), ArmKvmCPU::updateTCStateCoProc(), and ArmKvmCPU::updateTCStateVFP().
mode
Bitfield<4, 0> ArmISA::mode
Definition at line 73 of file miscregs_types.hh.
Referenced by accessFunc(), WriteAllocator::allocate(), chmodFunc(), WriteAllocator::coalesce(), ArmSemihosting::FileBase::create(), OutputDirectory::create(), currEL(), decodeMrsMsrBankedReg(), RiscvISA::TLB::demapPage(), PowerISA::TLB::demapPage(), SparcISA::TLB::demapPage(), X86ISA::EndBitUnion(), fallocateFunc(), fchmodFunc(), flattenIntRegModeIndex(), fplibCompare(), fplibConvert(), fplibMax(), fplibMin(), fplibMulX(), fplibRecipEstimate(), fplibRecipStepFused(), fplibRecpX(), fplibRoundInt(), fplibRSqrtEstimate(), fplibRSqrtStepFused(), fplibTrigSMul(), ArmISA::FpRegImmOp::FpRegImmOp(), ArmISA::FpRegRegImmOp::FpRegRegImmOp(), ArmISA::FpRegRegOp::FpRegRegOp(), ArmISA::FpRegRegRegCondOp::FpRegRegRegCondOp(), ArmISA::FpRegRegRegImmOp::FpRegRegRegImmOp(), ArmISA::FpRegRegRegOp::FpRegRegRegOp(), ArmISA::FpRegRegRegRegOp::FpRegRegRegRegOp(), ArmISA::RfeOp::generateDisassembly(), ArmISA::SrsOp::generateDisassembly(), System::getMemoryMode(), FDArray::getSize(), ArmISA::TLB::getsize(), ArmSemihosting::getSTDIO(), X86ISA::GpuTLB::handleFuncTranslationReturn(), X86ISA::GpuTLB::handleTranslationReturn(), ArmISA::TableWalker::haveLargeAsid64(), illegalExceptionReturn(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), X86ISA::Walker::WalkerState::initState(), ArmISA::SupervisorCall::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::Stage2MMU::Stage2Translation::markDelayed(), QueuedPrefetcher::DeferredPacket::markDelayed(), Minor::Fetch1::FetchRequest::markDelayed(), EmulatedDriver::match(), mkdirFunc(), mknodFunc(), X86ISA::TLB::nextSeq(), RawDiskImage::open(), OutputDirectory::open(), FDArray::openFile(), openImpl(), X86ISA::Walker::WalkerState::pageFault(), TrafficGen::parseConfig(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), ArmSemihosting::readString(), X86ISA::Walker::WalkerState::recvPacket(), Shader::registerCU(), WriteAllocator::reset(), SC_MODULE(), sc_core::sc_set_stop_mode(), ArmSemihosting::FileBase::serialize(), System::setMemoryMode(), ArmISA::ISA::setMiscReg(), BaseTLB::Translation::squashed(), X86ISA::Walker::WalkerState::stepWalk(), Trace::TarmacBaseRecord::TarmacBaseRecord(), X86ISA::TLB::translate(), X86ISA::GpuTLB::translate(), AlphaISA::TLB::translateData(), AlphaISA::TLB::updateCache(), Trace::TarmacTracerRecord::TraceRegEntry::updateInt(), WriteAllocator::updateMode(), vcvtFpFpH(), X86ISA::Walker::WalkerSenderState::WalkerSenderState(), TimingSimpleCPU::writeMem(), LSQ< Impl >::SingleDataRequest::~SingleDataRequest(), LSQ< Impl >::SplitDataRequest::~SplitDataRequest(), ArmISA::TlbTestInterface::~TlbTestInterface(), BaseTLB::Translation::~Translation(), and X86ISA::GpuTLB::Translation::~Translation().
mpam
Bitfield<43, 40> ArmISA::mpam
Definition at line 169 of file miscregs_types.hh.
n
ArmISA::n
Definition at line 429 of file miscregs_types.hh.
Referenced by sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::_gem5Interface(), sc_dt::scfx_string::append(), BOPPrefetcher::BOPPrefetcher(), DVFSHandler::clkPeriodAtPerfLevel(), sc_dt::convert_to_bin(), sc_dt::convert_to_fmt(), FastModel::CortexA76::CortexA76(), MessageBuffer::delayHead(), IGbE::DescCache< iGbReg::RxDesc >::DescCache(), sc_dt::scfx_string::discard(), ThermalModel::doStep(), Event::dump(), SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), CxxConfigManager::findObject(), sc_dt::sc_subref_r< X >::get_cword(), sc_dt::sc_fxnum_fast::get_slice(), sc_dt::sc_subref_r< X >::get_word(), ThermalDomain::getNode(), ThermalModel::getTemp(), StackDistCalc::getTreeDepth(), V7LPageTableOps::index(), ClDriver::ioctl(), sc_gem5::listContains(), SwitchingFiber::main(), tlm::tlm_fifo< T >::nb_expand(), tlm::tlm_fifo< T >::nb_unbound(), sc_gem5::Object::Object(), tlm::tlm_fifo< T >::ok_to_put(), sc_core::sc_vector_iter< Element, AccessPolicy >::operator+=(), sc_core::sc_vector_iter< Element, AccessPolicy >::operator-=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator>>=(), sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::operator[](), sc_dt::sc_proxy< sc_subref_r< X > >::operator^=(), sc_dt::sc_bitref< X >::operator^=(), ArmISA::TableWalker::LongDescriptor::paddr(), MathExpr::parse(), SparcISA::SparcStaticInst::passesCondition(), ArmISA::TableWalker::pendingChange(), tlm::circular_buffer< T >::poke_data(), power(), sc_dt::print_dec(), Printk(), StackDistCalc::printStack(), prlimitFunc(), HardBreakpoint::process(), ArmISA::TableWalker::processWalkLPAE(), PowerISA::IntRotateOp::rotateValue(), IGbE::RxDescCache::RxDescCache(), Stats::DistBase< Distribution, DistStor >::sample(), Stats::DistProxy< Stat >::sample(), Stats::SparseHistBase< SparseHistogram, SparseHistStor >::sample(), EtherTapStub::sendReal(), sc_dt::sc_subref_r< X >::set_cword(), FastModel::CortexA76Cluster::set_evs_param(), sc_dt::sc_subref_r< X >::set_word(), ThermalDomain::setNode(), ThermalReference::setNode(), ThermalResistor::setNodes(), sc_dt::scfx_rep::shift_left(), sc_dt::scfx_rep::shift_right(), sc_dt::sc_bitref_r< X >::size(), sc_dt::sc_subref_r< X >::size(), sc_dt::sc_concref_r< X, Y >::size(), ThermalModel::startup(), testPredicate(), IGbE::TxDescCache::TxDescCache(), sc_dt::vec_copy(), DVFSHandler::voltageAtPerfLevel(), sc_dt::sc_uint_base::xor_reduce(), and sc_dt::sc_int_base::xor_reduce().
nEt
Bitfield<6> ArmISA::nEt
Definition at line 305 of file miscregs_types.hh.
nmfi
Bitfield<27> ArmISA::nmfi
Definition at line 318 of file miscregs_types.hh.
nos0
Bitfield<24> ArmISA::nos0
Definition at line 557 of file miscregs_types.hh.
nos1
Bitfield<25> ArmISA::nos1
Definition at line 558 of file miscregs_types.hh.
nos2
Bitfield<26> ArmISA::nos2
Definition at line 559 of file miscregs_types.hh.
nos3
Bitfield<27> ArmISA::nos3
Definition at line 560 of file miscregs_types.hh.
nos4
Bitfield<28> ArmISA::nos4
Definition at line 561 of file miscregs_types.hh.
nos5
Bitfield<29> ArmISA::nos5
Definition at line 562 of file miscregs_types.hh.
nos6
Bitfield<30> ArmISA::nos6
Definition at line 563 of file miscregs_types.hh.
nos7
Bitfield<31> ArmISA::nos7
Definition at line 564 of file miscregs_types.hh.
NPtePage
const Addr ArmISA::NPtePage = ULL(1) << NPtePageShift
Definition at line 71 of file isa_traits.hh.
NPtePageShift
const Addr ArmISA::NPtePageShift = PageShift - PteShift
Definition at line 70 of file isa_traits.hh.
ns
Bitfield< 9 > ArmISA::ns
Definition at line 311 of file miscregs_types.hh.
Referenced by Gicv3CPUInterface::generateSGI(), ArmISA::TLB::insert(), sc_gem5::Process::needsStart(), Gicv3Redistributor::processorNumber(), snsBankedIndex(), and ArmISA::ISA::snsBankedIndex64().
ns0
Bitfield<18> ArmISA::ns0
Definition at line 555 of file miscregs_types.hh.
ns1
Bitfield<19> ArmISA::ns1
Definition at line 556 of file miscregs_types.hh.
nsasedis
Bitfield<15> ArmISA::nsasedis
Definition at line 278 of file miscregs_types.hh.
nsd32dis
Bitfield<14> ArmISA::nsd32dis
Definition at line 279 of file miscregs_types.hh.
ntwe
Bitfield<18> ArmISA::ntwe
Definition at line 336 of file miscregs_types.hh.
ntwi
Bitfield<16> ArmISA::ntwi
Definition at line 339 of file miscregs_types.hh.
NumArgumentRegs
const int ArmISA::NumArgumentRegs = 4
Definition at line 114 of file registers.hh.
Referenced by AlphaISA::getArgument(), SparcISA::getArgument(), getArgument(), X86ISA::X86_64Process::getSyscallArg(), X86ISA::I386Process::getSyscallArg(), X86ISA::X86_64Process::setSyscallArg(), and X86ISA::I386Process::setSyscallArg().
NumArgumentRegs64
const int ArmISA::NumArgumentRegs64 = 8
Definition at line 115 of file registers.hh.
NumCCRegs
const int ArmISA::NumCCRegs = NUM_CCREGS
Definition at line 98 of file registers.hh.
Referenced by copyRegs().
numCPUs
Bitfield<25,24> ArmISA::numCPUs
Definition at line 603 of file miscregs_types.hh.
Referenced by AlphaBackdoor::read(), AlphaBackdoor::Access::serialize(), and AlphaBackdoor::Access::unserialize().
NumFloatRegs
const int ArmISA::NumFloatRegs = 0
Definition at line 92 of file registers.hh.
Referenced by copyRegs().
NumFloatV7ArchRegs
const int ArmISA::NumFloatV7ArchRegs = 64
Definition at line 84 of file registers.hh.
Referenced by ArmISA::MacroVFPMemOp::MacroVFPMemOp(), ArmISA::VldMultOp::VldMultOp(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VstMultOp::VstMultOp(), and ArmISA::VstSingleOp::VstSingleOp().
NumFloatV8ArchRegs
const int ArmISA::NumFloatV8ArchRegs = 128
Definition at line 85 of file registers.hh.
Referenced by ArmISA::VldMultOp64::VldMultOp64(), ArmISA::VldSingleOp64::VldSingleOp64(), ArmISA::VstMultOp64::VstMultOp64(), and ArmISA::VstSingleOp64::VstSingleOp64().
NumIntArchRegs
const int ArmISA::NumIntArchRegs = NUM_ARCH_INTREGS
Definition at line 82 of file registers.hh.
NumIntRegs
const int ArmISA::NumIntRegs = NUM_INTREGS
Definition at line 91 of file registers.hh.
Referenced by copyRegs().
NumMiscRegs
const int ArmISA::NumMiscRegs = NUM_MISCREGS
Definition at line 99 of file registers.hh.
Referenced by copyRegs(), ArmISA::ISA::readMiscRegNoEffect(), and ArmISA::ISA::setMiscRegNoEffect().
NumVecElemPerNeonVecReg
constexpr unsigned ArmISA::NumVecElemPerNeonVecReg = 4
Definition at line 66 of file registers.hh.
Referenced by ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), Trace::TarmacParserRecord::TarmacParserRecordEvent::process(), and ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs().
NumVecElemPerVecReg
constexpr unsigned ArmISA::NumVecElemPerVecReg = MaxSveVecLenInWords
Definition at line 68 of file registers.hh.
Referenced by copyVecRegs().
NumVecIntrlvRegs
const int ArmISA::NumVecIntrlvRegs = 4
Definition at line 90 of file registers.hh.
NumVecPredRegs
const int ArmISA::NumVecPredRegs = 18
Definition at line 95 of file registers.hh.
NumVecRegs
const int ArmISA::NumVecRegs = NumVecV8ArchRegs + NumVecSpecialRegs + NumVecIntrlvRegs
Definition at line 93 of file registers.hh.
Referenced by copyVecRegs().
NumVecSpecialRegs
const int ArmISA::NumVecSpecialRegs = 8
Definition at line 88 of file registers.hh.
NumVecV7ArchRegs
const int ArmISA::NumVecV7ArchRegs = 64
Definition at line 86 of file registers.hh.
Referenced by Trace::ArmNativeTrace::ThreadState::update().
NumVecV8ArchRegs
const int ArmISA::NumVecV8ArchRegs = 32
Definition at line 87 of file registers.hh.
Referenced by ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), and ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs().
nv
Bitfield<27, 24> ArmISA::nv
Definition at line 155 of file miscregs_types.hh.
nz
ArmISA::nz
Definition at line 52 of file miscregs_types.hh.
ofc
Bitfield<2> ArmISA::ofc
Definition at line 408 of file miscregs_types.hh.
ofe
Bitfield<10> ArmISA::ofe
Definition at line 414 of file miscregs_types.hh.
offset
Bitfield<23, 0> ArmISA::offset
Definition at line 154 of file types.hh.
Referenced by _llseekFunc(), IniFile::Section::add(), IniFile::add(), DtbFile::addBootCmdLine(), ArmISA::VfpMacroOp::addStride(), StorageSpace::addSymbol(), TraceCPU::ElasticDataGen::adjustInitTraceOffset(), BOPPrefetcher::BOPPrefetcher(), ElfObject::buildImage(), LSQ< Impl >::SplitDataRequest::buildPackets(), BaseXBar::calcPacketTiming(), AddrOperandBase::calcUniformBase(), VirtDescriptor::chainRead(), VirtDescriptor::chainWrite(), BaseRemoteGDB::cmd_query_var(), BaseCache::cmpAndSwap(), Linux::ThreadInfo::curTaskInfo(), Linux::ThreadInfo::curTaskMmFromTaskStruct(), Linux::ThreadInfo::curTaskNameFromTaskStruct(), Linux::ThreadInfo::curTaskPIDFromTaskStruct(), Linux::ThreadInfo::curTaskStartFromTaskStruct(), Linux::ThreadInfo::curTaskTGIDFromTaskStruct(), DMASequencer::dataCallback(), GenericPciHost::decodeAddress(), AddrOperandBase::disassemble(), TraceCPU::ElasticDataGen::ElasticDataGen(), IdeController::EndBitUnion(), fallocateFunc(), SectorTags::findBlock(), findRegDataType(), DtbFile::findReleaseAddr(), CompressedTags::findVictim(), PixelConverter::Channel::fromPixel(), RiscvISA::Load::generateDisassembly(), RiscvISA::Store::generateDisassembly(), ArmISA::SveContigMemSS::generateDisassembly(), ArmISA::MemoryReg64::generateDisassembly(), SubBlock::getByte(), DataBlock::getData(), DataBlock::getDataMod(), ArmFreebsdProcessBits::SyscallTable::getDesc(), ArmLinuxProcessBits::SyscallTable::getDesc(), BaseKvmCPU::getGuestData(), LSQ< Impl >::SplitDataRequest::handleIprRead(), LSQ< Impl >::SplitDataRequest::handleIprWrite(), handlePseudoInst(), VirtDescriptor::index(), RegAddrOperand< RegOperandType >::init(), NoRegAddrOperand::init(), FreebsdArmSystem::initState(), X86System::initState(), LinuxArmSystem::initState(), SparcISA::ISA::installGlobals(), SparcISA::ISA::installWindow(), SubBlock::internalMergeFrom(), SubBlock::internalMergeTo(), EmulationPageTable::isUnmapped(), ElfObject::loadSomeSymbols(), ArmISA::MacroVFPMemOp::MacroVFPMemOp(), DMASequencer::makeRequest(), UFSHostDevice::manageWriteTransfer(), MultiLevelPageTable< EntryTypes >::map(), mmapImpl(), CowDiskImage::open(), VPtr< T >::operator+(), VPtr< T >::operator+=(), TimeBuffer< T >::wire::operator+=(), TimeBuffer< T >::wire::operator-=(), Stats::Vector2dBase< Vector2d, StatStor >::operator[](), AddrOperandBase::parseAddr(), WriteMask::performAtomic(), WalkCache::pickSetIdx(), BasePrefetcher::PrefetchInfo::PrefetchInfo(), pwrite64Func(), MmioVirtIO::read(), PciVirtIO::read(), Gicv2m::read(), VirtIOBlock::read(), GpuDispatcher::read(), IdeController::readConfig(), PciDevice::readConfig(), SMMUv3::readControl(), DRAMCtrl::recvTimingReq(), MultiLevelPageTable< EntryTypes >::remap(), RangeAddrMapper::remapAddr(), PacketFifo::remove(), BaseCache::satisfyRequest(), Net::TcpPtr::set(), Net::UdpPtr::set(), SubBlock::setByte(), IdeDisk::setController(), split_first(), split_last(), BaseRemoteGDB::system(), WriteMask::test(), MemTest::tick(), AlphaISA::TLB::translateData(), AlphaISA::TLB::translateInst(), MultiLevelPageTable< EntryTypes >::unmap(), MSHR::TargetList::updateWriteFlags(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VstSingleOp::VstSingleOp(), PciVirtIO::write(), MmioVirtIO::write(), Gicv2m::write(), GpuDispatcher::write(), VirtIOBlock::write(), IdeController::writeConfig(), PciDevice::writeConfig(), NSGigE::writeConfig(), IGbE::writeConfig(), SMMUv3::writeControl(), GicV2::writeDistributor(), DataBlock::~DataBlock(), and DiskImage::~DiskImage().
opc2
Bitfield<7,5> ArmISA::opc2
Definition at line 116 of file types.hh.
Referenced by ArmKvmCPU::decodeCoProcReg(), mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), and mcrrMrrc15TrapToHyp().
opcode
Bitfield<24, 21> ArmISA::opcode
Definition at line 102 of file types.hh.
Referenced by HsailISA::CommonInstBase< DestDataType::OperandType, SrcDataType::OperandType, 1 >::generateDisassembly(), HsailISA::LdaInst< DestDataType, AddrOperandType >::generateDisassembly(), HsailISA::ThreeNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType, U32 ::OperandType >::generateDisassembly(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::generateDisassembly(), HsailISA::TwoNonUniformSourceInstBase< DataType ::OperandType, DataType ::OperandType, U32 ::OperandType >::generateDisassembly(), HsailISA::Stub::generateDisassembly(), HsailISA::SpecialInstNoSrcBase< DestDataType::OperandType >::generateDisassembly(), HsailISA::SpecialInst1SrcBase< DestDataType::OperandType >::generateDisassembly(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::generateDisassembly(), HsailISA::Call::generateDisassembly(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::generateDisassembly(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), X86ISA::Decoder::processOpcode(), SC_MODULE(), Trace::TarmacBaseRecord::TarmacBaseRecord(), and Trace::TarmacTracerRecord::TraceInstEntry::TraceInstEntry().
opcode15
Bitfield<15> ArmISA::opcode15
Definition at line 114 of file types.hh.
opcode15_12
Bitfield<15, 12> ArmISA::opcode15_12
Definition at line 113 of file types.hh.
opcode18
Bitfield<18> ArmISA::opcode18
Definition at line 112 of file types.hh.
opcode19
Bitfield<19> ArmISA::opcode19
Definition at line 111 of file types.hh.
opcode19_16
Bitfield<19, 16> ArmISA::opcode19_16
Definition at line 110 of file types.hh.
opcode20
Bitfield<20> ArmISA::opcode20
Definition at line 108 of file types.hh.
opcode22
Bitfield<22> ArmISA::opcode22
Definition at line 109 of file types.hh.
opcode23_20
Bitfield<23, 20> ArmISA::opcode23_20
Definition at line 106 of file types.hh.
opcode23_21
Bitfield<23, 21> ArmISA::opcode23_21
Definition at line 107 of file types.hh.
opcode24
Bitfield<24> ArmISA::opcode24
Definition at line 104 of file types.hh.
opcode24_23
Bitfield<24, 23> ArmISA::opcode24_23
Definition at line 105 of file types.hh.
opcode4
Bitfield<4> ArmISA::opcode4
Definition at line 119 of file types.hh.
opcode6
Bitfield<6> ArmISA::opcode6
Definition at line 118 of file types.hh.
opcode7
Bitfield<7> ArmISA::opcode7
Definition at line 117 of file types.hh.
or0
Bitfield<17,16> ArmISA::or0
Definition at line 576 of file miscregs_types.hh.
or1
Bitfield<19,18> ArmISA::or1
Definition at line 577 of file miscregs_types.hh.
or2
Bitfield<21,20> ArmISA::or2
Definition at line 578 of file miscregs_types.hh.
or3
Bitfield<23,22> ArmISA::or3
Definition at line 579 of file miscregs_types.hh.
or4
Bitfield<25,24> ArmISA::or4
Definition at line 580 of file miscregs_types.hh.
or5
Bitfield<27,26> ArmISA::or5
Definition at line 581 of file miscregs_types.hh.
or6
Bitfield<29,28> ArmISA::or6
Definition at line 582 of file miscregs_types.hh.
or7
Bitfield<31,30> ArmISA::or7
Definition at line 583 of file miscregs_types.hh.
orgn0
Bitfield< 11, 10 > ArmISA::orgn0
Definition at line 470 of file miscregs_types.hh.
orgn1
Bitfield< 27, 26 > ArmISA::orgn1
Definition at line 477 of file miscregs_types.hh.
pa
Bitfield<39, 12> ArmISA::pa
Definition at line 626 of file miscregs_types.hh.
Referenced by ArmISA::TLB::flushAll(), ArmISA::Stage2LookUp::mergeTe(), ArmISA::TableWalker::LongDescriptor::nextDescAddr(), ArmISA::TLB::translateFs(), SMMUTranslationProcess::walkCacheUpdate(), and ArmISA::TlbTestInterface::~TlbTestInterface().
PABits
const unsigned ArmISA::PABits = 32
Definition at line 82 of file isa_traits.hh.
PAddrImplMask
const Addr ArmISA::PAddrImplMask = (ULL(1) << PABits) - 1
Definition at line 89 of file isa_traits.hh.
Page_Mask
const Addr ArmISA::Page_Mask = ~(PageBytes - 1)
Definition at line 60 of file isa_traits.hh.
PageBytes
const Addr ArmISA::PageBytes = ULL(1) << PageShift
Definition at line 59 of file isa_traits.hh.
Referenced by ArmISA::RemoteGDB::acc(), ArmProcess::argsInit(), roundPage(), and truncPage().
PageOffset
const Addr ArmISA::PageOffset = PageBytes - 1
Definition at line 61 of file isa_traits.hh.
Referenced by VAddrOffset().
PageShift
const Addr ArmISA::PageShift = 12
Definition at line 58 of file isa_traits.hh.
Referenced by ArmISA::TlbEntry::pageStart(), ArmISA::TlbEntry::updateVaddr(), and VAddrVPN().
pan
Bitfield< 23, 20 > ArmISA::pan
Definition at line 58 of file miscregs_types.hh.
Referenced by ArmISA::ISA::setMiscReg().
parange
Bitfield<3, 0> ArmISA::parange
Definition at line 132 of file miscregs_types.hh.
PCReg
const int ArmISA::PCReg = INTREG_PC
Definition at line 123 of file registers.hh.
Referenced by ArmISA::ArmStaticInst::printIntReg(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateInt(), and Trace::TarmacTracerRecord::TraceRegEntry::updateInt().
pd0
Bitfield<4> ArmISA::pd0
Definition at line 463 of file miscregs_types.hh.
pd1
Bitfield<5> ArmISA::pd1
Definition at line 464 of file miscregs_types.hh.
pmsver
Bitfield<35, 32> ArmISA::pmsver
Definition at line 80 of file miscregs_types.hh.
pmuver
Bitfield<11, 8> ArmISA::pmuver
Definition at line 84 of file miscregs_types.hh.
PREDREG_FFR
const int ArmISA::PREDREG_FFR = 16
Definition at line 96 of file registers.hh.
PREDREG_UREG0
const int ArmISA::PREDREG_UREG0 = 17
Definition at line 97 of file registers.hh.
procid
Bitfield<31,8> ArmISA::procid
Definition at line 588 of file miscregs_types.hh.
ps
Bitfield< 18, 16 > ArmISA::ps
Definition at line 487 of file miscregs_types.hh.
Referenced by SparcISA::TLB::demapPage(), and ArmISA::TableWalker::processWalkAArch64().
psruser
Bitfield<22> ArmISA::psruser
Definition at line 135 of file types.hh.
PteMask
const Addr ArmISA::PteMask = NPtePage - 1
Definition at line 72 of file isa_traits.hh.
Referenced by PteAddr().
PteShift
const Addr ArmISA::PteShift = 3
Definition at line 69 of file isa_traits.hh.
Referenced by PteAddr().
ptw
Bitfield<2> ArmISA::ptw
Definition at line 270 of file miscregs_types.hh.
pubwl
ArmISA::pubwl
Definition at line 140 of file types.hh.
punwl
Bitfield<24, 20> ArmISA::punwl
Definition at line 164 of file types.hh.
q
Bitfield<27> ArmISA::q
Definition at line 55 of file miscregs_types.hh.
Referenced by curEventQueue(), BaseGlobalEvent::deschedule(), AddrRangeMap< AbstractMemory *, 1 >::erase(), QoS::MemCtrl::escalate(), CPA::hwWe(), StatTest::init(), GpuDispatcher::notifyWgCompl(), AnnotateDumpCallback::process(), pybind_init_event(), recipEstimate(), SC_MODULE(), Event::setWhen(), sc_dt::vec_div_large(), and sc_dt::vec_div_small().
qc
Bitfield<27> ArmISA::qc
Definition at line 425 of file miscregs_types.hh.
rao2
Bitfield<18> ArmISA::rao2
Definition at line 338 of file miscregs_types.hh.
rao3
Bitfield<16> ArmISA::rao3
Definition at line 341 of file miscregs_types.hh.
rao4
Bitfield<6, 3> ArmISA::rao4
Definition at line 358 of file miscregs_types.hh.
ras
Bitfield<31, 28> ArmISA::ras
Definition at line 172 of file miscregs_types.hh.
raz
Bitfield<31, 28> ArmISA::raz
Definition at line 457 of file miscregs_types.hh.
raz_13_4
Bitfield<13,4> ArmISA::raz_13_4
Definition at line 610 of file miscregs_types.hh.
raz_28
Bitfield<28> ArmISA::raz_28
Definition at line 615 of file miscregs_types.hh.
rd
Bitfield<15, 12> ArmISA::rd
Definition at line 124 of file types.hh.
Referenced by ArmISA::ArmStaticInst::ArmStaticInst().
rdm
Bitfield<31, 28> ArmISA::rdm
Definition at line 98 of file miscregs_types.hh.
recip_sqrt_estimate
const uint8_t ArmISA::recip_sqrt_estimate[256] static
Initial value:
= {
    255, 253, 251, 249, 247, 245, 243, 242, 240, 238, 236, 234, 233, 231, 229, 228,
    226, 224, 223, 221, 219, 218, 216, 215, 213, 212, 210, 209, 207, 206, 204, 203,
    201, 200, 198, 197, 196, 194, 193, 192, 190, 189, 188, 186, 185, 184, 183, 181,
    180, 179, 178, 176, 175, 174, 173, 172, 170, 169, 168, 167, 166, 165, 164, 163,
    162, 160, 159, 158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146,
    145, 144, 143, 142, 141, 140, 140, 139, 138, 137, 136, 135, 134, 133, 132, 131,
    131, 130, 129, 128, 127, 126, 126, 125, 124, 123, 122, 121, 121, 120, 119, 118,
    118, 117, 116, 115, 114, 114, 113, 112, 111, 111, 110, 109, 109, 108, 107, 106,
    105, 104, 103, 101, 100,  99,  97,  96,  95,  93,  92,  91,  90,  88,  87,  86,
    85,  84,  82,  81,  80,  79,  78,  77,  76,  75,  74,  72,  71,  70,  69,  68,
    67,  66,  65,  64,  63,  62,  61,  60,  60,  59,  58,  57,  56,  55,  54,  53,
    52,  51,  51,  50,  49,  48,  47,  46,  46,  45,  44,  43,  42,  42,  41,  40,
    39,  38,  38,  37,  36,  35,  35,  34,  33,  33,  32,  31,  30,  30,  29,  28,
    28,  27,  26,  26,  25,  24,  24,  23,  22,  22,  21,  20,  20,  19,  19,  18,
    17,  17,  16,  16,  15,  14,  14,  13,  13,  12,  11,  11,  10,  10,   9,   9,
    8,   8,   7,   6,   6,   5,   5,   4,   4,   3,   3,   2,   2,   1,   1,   0
}
Definition at line 3496 of file fplib.cc.
regList
Bitfield<15, 0> ArmISA::regList
Definition at line 152 of file types.hh.
res1_13_12_el2
Bitfield<13, 12> ArmISA::res1_13_12_el2
Definition at line 642 of file miscregs_types.hh.
res1_7_0_el2
Bitfield<7, 0> ArmISA::res1_7_0_el2
Definition at line 648 of file miscregs_types.hh.
res1_8_el2
Bitfield<8> ArmISA::res1_8_el2
Definition at line 645 of file miscregs_types.hh.
res1_9_el2
Bitfield<9> ArmISA::res1_9_el2
Definition at line 644 of file miscregs_types.hh.
reserved_20_13
Bitfield<20,13> ArmISA::reserved_20_13
Definition at line 599 of file miscregs_types.hh.
reserved_22
Bitfield<22> ArmISA::reserved_22
Definition at line 601 of file miscregs_types.hh.
reserved_30_26
Bitfield<30,26> ArmISA::reserved_30_26
Definition at line 604 of file miscregs_types.hh.
reserved_4_3
Bitfield<4,3> ArmISA::reserved_4_3
Definition at line 593 of file miscregs_types.hh.
ReturnAddressReg
const int ArmISA::ReturnAddressReg = INTREG_LR
Definition at line 122 of file registers.hh.
Referenced by ArmISA::ArmStaticInst::printIntReg(), and skipFunction().
ReturnValueReg
const int ArmISA::ReturnValueReg = 0
Definition at line 111 of file registers.hh.
ReturnValueReg1
const int ArmISA::ReturnValueReg1 = 1
Definition at line 112 of file registers.hh.
ReturnValueReg2
const int ArmISA::ReturnValueReg2 = 2
Definition at line 113 of file registers.hh.
rfr
Bitfield<19> ArmISA::rfr
Definition at line 277 of file miscregs_types.hh.
rm
Bitfield<3, 0> ArmISA::rm
Definition at line 128 of file types.hh.
Referenced by ArmISA::ArmStaticInst::ArmStaticInst(), and m5_fegetround().
rMode
Bitfield<23, 22> ArmISA::rMode
Definition at line 421 of file miscregs_types.hh.
Referenced by ArmISA::FpOp::dblHi(), ArmISA::FpOp::ternaryOp(), and vcvtFpFpH().
rn
Bitfield<19, 16> ArmISA::rn
Definition at line 123 of file types.hh.
Referenced by ArmISA::ArmStaticInst::ArmStaticInst(), ArmISA::VldMultOp::VldMultOp(), ArmISA::VldMultOp64::VldMultOp64(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VldSingleOp64::VldSingleOp64(), ArmISA::VstMultOp::VstMultOp(), ArmISA::VstMultOp64::VstMultOp64(), ArmISA::VstSingleOp::VstSingleOp(), and ArmISA::VstSingleOp64::VstSingleOp64().
rndr
ArmISA::rndr
Definition at line 90 of file miscregs_types.hh.
rotate
Bitfield<11, 8> ArmISA::rotate
Definition at line 144 of file types.hh.
Referenced by ArmISA::PredIntOp::generateDisassembly().
roundingModes
Bitfield<31, 28> ArmISA::roundingModes
Definition at line 446 of file miscregs_types.hh.
rr
Bitfield<14> ArmISA::rr
Definition at line 344 of file miscregs_types.hh.
Referenced by Net::IpOpt::data().
rs
Bitfield< 11, 8 > ArmISA::rs
Definition at line 351 of file miscregs_types.hh.
Referenced by Switch::addOutPort(), ArmISA::ArmStaticInst::ArmStaticInst(), GarnetNetwork::collateStats(), Gicv3CPUInterface::generateSGI(), RubyPort::MemSlavePort::hitCallback(), Sequencer::hitCallback(), IGbE::TxDescCache::pktComplete(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvFunctional(), RubyPort::MemSlavePort::recvTimingReq(), and Stats::BinaryNode< Op >::size().
rsvd
Bitfield<29, 28> ArmISA::rsvd
Definition at line 388 of file miscregs_types.hh.
rt
Bitfield<15, 12> ArmISA::rt
Definition at line 125 of file types.hh.
Referenced by mcrMrc14TrapToHyp(), mcrMrc15TrapToHyp(), and mcrrMrrc15TrapToHyp().
rw
Bitfield< 10 > ArmISA::rw
Definition at line 239 of file miscregs_types.hh.
Referenced by Pl111::pixelConverter().
s
Bitfield<4> ArmISA::s
Definition at line 532 of file miscregs_types.hh.
Referenced by IniFile::add(), sc_gem5::Event::addSensitivity(), sc_dt::and_on_help(), ArmISA::ArmStaticInst::ArmStaticInst(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), atomic_read(), atomic_write(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::bind(), sc_dt::check_for_zero(), AccessMapPatternMatching::checkCandidate(), BaseRemoteGDB::cmd_query_var(), sc_dt::convert_signed_2C_to_SM(), sc_dt::convert_to_fmt(), tlm_utils::convenience_socket_base::display_error(), tlm_utils::convenience_socket_base::display_warning(), BaseDynInst< Impl >::dump(), tlm_utils::simple_socket_base::elaboration_check(), emptyStrings(), Stats::VectorInfo::enable(), Stats::VectorDistInfo::enable(), EndBitUnion(), AtomicOpCAS< T >::execute(), sc_gem5::Port::finalize(), ControlFlowInfo::findPostDominators(), sc_dt::scfx_rep::from_string(), sc_dt::sc_fxval_fast::from_string(), FUPool::FUPool(), ArmISA::TableWalker::getTlb(), CPA::hwWe(), sc_gem5::Reset::install(), SMMUTLB::invalidateAll(), ARMArchTLB::invalidateAll(), IPACache::invalidateAll(), ConfigCache::invalidateAll(), WalkCache::invalidateAll(), SMMUTLB::invalidateASID(), ARMArchTLB::invalidateASID(), WalkCache::invalidateASID(), IPACache::invalidateIPAA(), SMMUTLB::invalidateSID(), ConfigCache::invalidateSID(), WalkCache::invalidateVA(), ARMArchTLB::invalidateVAA(), WalkCache::invalidateVAA(), SMMUTLB::invalidateVMID(), ARMArchTLB::invalidateVMID(), IPACache::invalidateVMID(), WalkCache::invalidateVMID(), SMMUTLB::lookupAnyVA(), ArmISA::TableWalker::memAttrs(), sc_gem5::newDynamicSensitivityEvent(), sc_gem5::newDynamicSensitivityEventAndList(), sc_gem5::newDynamicSensitivityEventOrList(), sc_gem5::newStaticSensitivityEvent(), sc_gem5::newStaticSensitivityExport(), sc_gem5::newStaticSensitivityFinder(), sc_gem5::newStaticSensitivityInterface(), sc_gem5::newStaticSensitivityPort(), sc_gem5::Event::notify(), sc_dt::operator*(), sc_dt::operator/(), tlm::operator<<(), sc_dt::operator<<(), sc_core::operator<<(), sc_dt::operator>=(), sc_dt::or_on_help(), parseParam(), MSHR::TargetList::print(), CacheBlk::print(), Printk(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), AbstractController::queueMemoryWritePartial(), quote(), recipEstimate(), recipSqrtEstimate(), BaseXBar::recvRangeChange(), AbstractController::recvTimingResp(), WalkCache::regStats(), EventQueue::replaceHead(), Stats::Group::resetStats(), SyscallReturn::retry(), sc_dt::sc_bv_base::sc_bv_base(), sc_dt::sc_lv_base::sc_lv_base(), SC_MODULE(), sc_dt::sc_fxval::scan(), sc_dt::sc_concatref::scan(), sc_dt::sc_uint_subref::scan(), sc_dt::sc_proxy< sc_subref_r< X > >::scan(), sc_dt::sc_int_subref::scan(), sc_dt::sc_fxval_fast::scan(), sc_dt::sc_fxnum::scan(), sc_dt::sc_uint_base::scan(), sc_dt::sc_int_base::scan(), sc_dt::sc_subref< X >::scan(), sc_dt::sc_fxnum_fast::scan(), sc_dt::sc_concref< X, Y >::scan(), sc_dt::scfx_csd2tc(), sc_dt::scfx_exp_start(), sc_dt::scfx_parse_sign(), TCPIface::sendCmd(), PhysicalMemory::serialize(), sc_gem5::Process::setDynamic(), Trace::InstRecord::setMem(), TaggedEntry::setSecure(), KvmVM::setSystem(), SimpleNetwork::SimpleNetwork(), split_first(), split_last(), sc_gem5::Kernel::status(), sc_gem5::Scheduler::status(), sc_gem5::Process::terminate(), TEST(), to_bool(), to_lower(), sc_dt::scfx_rep::to_string(), sc_dt::sc_proxy< sc_subref_r< X > >::to_string(), sc_dt::to_string(), sc_dt::vec_from_str(), EventQueue::wakeup(), sc_dt::xor_on_help(), BaseXBar::~BaseXBar(), PhysicalMemory::~PhysicalMemory(), sc_gem5::Process::~Process(), and QTIsaac< ALPHA >::randctx::~randctx().
sa
Bitfield<3> ArmISA::sa
Definition at line 365 of file miscregs_types.hh.
Referenced by acceptFunc(), getsocknameFunc(), recvfromFunc(), sendtoFunc(), and SPAlignmentCheckEnabled().
sa0
Bitfield<4> ArmISA::sa0
Definition at line 363 of file miscregs_types.hh.
Referenced by SPAlignmentCheckEnabled().
sataRAMLatency
ArmISA::sataRAMLatency
Definition at line 592 of file miscregs_types.hh.
sb
Bitfield<39, 36> ArmISA::sb
Definition at line 108 of file miscregs_types.hh.
Referenced by SBOOEPrefetcher::access().
scd
Bitfield<7> ArmISA::scd
Definition at line 303 of file miscregs_types.hh.
sed
Bitfield<8> ArmISA::sed
Definition at line 353 of file miscregs_types.hh.
Referenced by ArmISA::ArmStaticInst::checkSETENDEnabled().
sel
ArmISA::sel
Definition at line 620 of file miscregs_types.hh.
Referenced by AddrRange::contains(), and Intel8254Timer::writeControl().
sel2
Bitfield<39, 36> ArmISA::sel2
Definition at line 170 of file miscregs_types.hh.
sevenAndFour
Bitfield<33> ArmISA::sevenAndFour
Definition at line 94 of file types.hh.
sField
Bitfield<20> ArmISA::sField
Definition at line 122 of file types.hh.
sh
Bitfield<8, 7> ArmISA::sh
Definition at line 629 of file miscregs_types.hh.
Referenced by PowerISA::IntShiftOp::generateDisassembly(), PowerISA::IntRotateOp::generateDisassembly(), MPP_StatisticalCorrector_8KB::gPredictions(), MPP_StatisticalCorrector_64KB::gPredictions(), TAGE_SC_L_8KB_StatisticalCorrector::gPredictions(), TAGE_SC_L_64KB_StatisticalCorrector::gPredictions(), MPP_StatisticalCorrector_8KB::gUpdates(), MPP_StatisticalCorrector_64KB::gUpdates(), TAGE_SC_L_8KB_StatisticalCorrector::gUpdates(), TAGE_SC_L_64KB_StatisticalCorrector::gUpdates(), MPP_StatisticalCorrector_8KB::makeThreadHistory(), MPP_StatisticalCorrector_64KB::makeThreadHistory(), TAGE_SC_L_8KB_StatisticalCorrector::makeThreadHistory(), TAGE_SC_L_64KB_StatisticalCorrector::makeThreadHistory(), ArmISA::TableWalker::memAttrsAArch64(), ArmISA::TableWalker::memAttrsLPAE(), MPP_StatisticalCorrector_8KB::scHistoryUpdate(), MPP_StatisticalCorrector_64KB::scHistoryUpdate(), TAGE_SC_L_8KB_StatisticalCorrector::scHistoryUpdate(), and TAGE_SC_L_64KB_StatisticalCorrector::scHistoryUpdate().
sh0
Bitfield< 13, 12 > ArmISA::sh0
Definition at line 471 of file miscregs_types.hh.
sh1
Bitfield< 29, 28 > ArmISA::sh1
Definition at line 478 of file miscregs_types.hh.
Referenced by StatTest::init(), and StatTest::run().
sha1
Bitfield<11, 8> ArmISA::sha1
Definition at line 102 of file miscregs_types.hh.
sha2
Bitfield<15, 12> ArmISA::sha2
Definition at line 101 of file miscregs_types.hh.
sha3
Bitfield<35, 32> ArmISA::sha3
Definition at line 97 of file miscregs_types.hh.
shift
Bitfield<6, 5> ArmISA::shift
Definition at line 127 of file types.hh.
Referenced by MipsISA::bitrev(), divideFromConf(), findCarry(), findOverflow(), fp128_normalise(), fp16_normalise(), fp32_normalise(), fp64_normalise(), sc_dt::sc_concref_r< X, Y >::get_cword(), sc_dt::sc_concref_r< X, Y >::get_word(), MipsISA::getCondCode(), MultiperspectivePerceptron::ACYCLIC::getHash(), MultiperspectivePerceptron::RECENCY::getHash(), MultiperspectivePerceptron::PATH::getHash(), MultiperspectivePerceptron::MODPATH::getHash(), MultiperspectivePerceptron::GHISTPATH::getHash(), MultiperspectivePerceptron::GHISTMODPATH::getHash(), MultiperspectivePerceptron::BLURRYPATH::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), StatisticalCorrector::SCThreadHistory::initLocalHistory(), Ps2::keySymToPs2(), lsl128(), lsl16(), lsl32(), lsl64(), lsr128(), lsr16(), lsr32(), lsr64(), sc_dt::scfx_rep::normalize(), sc_dt::operator<<(), SatCounter::operator<<=(), sc_dt::operator>>(), SatCounter::operator>>=(), sc_dt::scfx_rep::resize(), ArmISA::Crypto::ror(), SC_MODULE(), sc_dt::sc_concref_r< X, Y >::set_cword(), sc_dt::sc_concref_r< X, Y >::set_word(), sc_dt::scfx_rep::to_double(), sc_dt::scfx_rep::to_uint64(), IndirectMemoryPrefetcher::trackMissIndex1(), IndirectMemoryPrefetcher::trackMissIndex2(), and X86ISA::X86MicroopBase::X86MicroopBase().
shiftSize
Bitfield<11, 7> ArmISA::shiftSize
Definition at line 126 of file types.hh.
shortVectors
Bitfield<27, 24> ArmISA::shortVectors
Definition at line 445 of file miscregs_types.hh.
sif
Bitfield<9> ArmISA::sif
Definition at line 301 of file miscregs_types.hh.
singlePrecision
Bitfield<7, 4> ArmISA::singlePrecision
Definition at line 440 of file miscregs_types.hh.
sl0
Bitfield<7, 6> ArmISA::sl0
Definition at line 534 of file miscregs_types.hh.
sm3
Bitfield<39, 36> ArmISA::sm3
Definition at line 96 of file miscregs_types.hh.
sm4
Bitfield<43, 40> ArmISA::sm4
Definition at line 95 of file miscregs_types.hh.
smd
Bitfield<7> ArmISA::smd
Definition at line 304 of file miscregs_types.hh.
snsmem
Bitfield<15, 12> ArmISA::snsmem
Definition at line 129 of file miscregs_types.hh.
sp
Bitfield<0> ArmISA::sp
Definition at line 74 of file miscregs_types.hh.
Referenced by RiscvProcess::argsInit(), Linux::ThreadInfo::curThreadInfo(), StorageMap::findSymbol(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), AlphaISA::getArgument(), SparcISA::getArgument(), getArgument(), SparcISA::SpillNNormal::invoke(), SparcISA::FillNNormal::invoke(), SparcISA::TrapInstruction::invoke(), and ArmISA::ISA::setMiscReg().
span
Bitfield<23> ArmISA::span
Definition at line 325 of file miscregs_types.hh.
Referenced by SMMUTranslationProcess::doReadSTE().
specres
ArmISA::specres
Definition at line 107 of file miscregs_types.hh.
specsei
Bitfield<27, 24> ArmISA::specsei
Definition at line 137 of file miscregs_types.hh.
squareRoot
Bitfield<23, 20> ArmISA::squareRoot
Definition at line 444 of file miscregs_types.hh.
ss
Bitfield<21> ArmISA::ss
Definition at line 59 of file miscregs_types.hh.
Referenced by sc_gem5::ScSignalBaseBinary::_signalNegedge(), sc_core::sc_vector_base::checkIndex(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::checkTransaction(), LSQUnit< Impl >::completeDataAccess(), GPUCoalescer::completeHitCallback(), X86ISA::X86FaultBase::describe(), X86ISA::PageFault::describe(), TrieTestData::dumpTrie(), sc_core::sc_in_rv< W >::end_of_elaboration(), sc_core::sc_inout_rv< W >::end_of_elaboration(), sc_gem5::Port::finalize(), sc_core::sc_event_finder_t< sc_core::sc_signal_inout_if< bool > >::find_event(), PowerISA::MiscOp::generateDisassembly(), RiscvISA::RegOp::generateDisassembly(), RiscvISA::MemFenceMicro::generateDisassembly(), MrsOp::generateDisassembly(), ImmOp64::generateDisassembly(), ArmISA::DataXImmOp::generateDisassembly(), RiscvISA::Load::generateDisassembly(), PowerISA::CondLogicOp::generateDisassembly(), ArmISA::BranchImm::generateDisassembly(), ArmISA::SysDC64::generateDisassembly(), PowerISA::PowerStaticInst::generateDisassembly(), ArmISA::BranchImm64::generateDisassembly(), RiscvISA::LoadReserved::generateDisassembly(), RiscvISA::Store::generateDisassembly(), ArmISA::SveIndexIIOp::generateDisassembly(), ArmISA::SveMemVecFillSpill::generateDisassembly(), RegRegImmImmOp64::generateDisassembly(), RiscvISA::LoadReservedMicro::generateDisassembly(), ArmISA::DataXImmOnlyOp::generateDisassembly(), PowerISA::MemDispOp::generateDisassembly(), ArmISA::BranchImmCond64::generateDisassembly(), PowerISA::CondMoveOp::generateDisassembly(), MsrImmOp::generateDisassembly(), RiscvISA::StoreCond::generateDisassembly(), ArmISA::SveIndexIROp::generateDisassembly(), ArmISA::BranchReg::generateDisassembly(), X86ISA::X86StaticInst::generateDisassembly(), SparcISA::SparcStaticInst::generateDisassembly(), RegRegRegImmOp64::generateDisassembly(), PowerISA::IntOp::generateDisassembly(), PowerISA::BranchPCRel::generateDisassembly(), ArmISA::DataXSRegOp::generateDisassembly(), RiscvISA::StoreCondMicro::generateDisassembly(), ArmISA::SveMemPredFillSpill::generateDisassembly(), ArmISA::BranchReg64::generateDisassembly(), MsrRegOp::generateDisassembly(), ArmISA::SveLdStructSS< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), ArmISA::SveIndexRIOp::generateDisassembly(), RiscvISA::CSROp::generateDisassembly(), RiscvISA::AtomicMemOp::generateDisassembly(), ArmISA::BranchRet64::generateDisassembly(), ArmISA::RfeOp::generateDisassembly(), ArmISA::DataXERegOp::generateDisassembly(), X86ISA::X86MicroopBase::generateDisassembly(), RiscvISA::AtomicMemOpMicro::generateDisassembly(), ArmISA::SveIndexRROp::generateDisassembly(), MrrcOp::generateDisassembly(), PowerISA::IntImmOp::generateDisassembly(), ArmISA::BranchRegReg::generateDisassembly(), ArmISA::BranchEret64::generateDisassembly(), ArmISA::SveContigMemSS::generateDisassembly(), PowerISA::BranchNonPCRel::generateDisassembly(), ArmISA::DataX1RegOp::generateDisassembly(), ArmISA::SvePredCountOp::generateDisassembly(), McrrOp::generateDisassembly(), PowerISA::IntShiftOp::generateDisassembly(), ArmISA::BranchImmReg64::generateDisassembly(), ArmISA::DataX1RegImmOp::generateDisassembly(), ArmISA::MemoryImm64::generateDisassembly(), ArmISA::SveContigMemSI::generateDisassembly(), PowerISA::FloatOp::generateDisassembly(), ImmOp::generateDisassembly(), ArmISA::SvePredCountPredOp::generateDisassembly(), ArmISA::SrsOp::generateDisassembly(), ArmISA::DataX1Reg2ImmOp::generateDisassembly(), ArmISA::MemoryDImm64::generateDisassembly(), RegImmOp::generateDisassembly(), ArmISA::SveWhileOp::generateDisassembly(), MiscRegImmOp64::generateDisassembly(), ArmISA::BranchImmImmReg64::generateDisassembly(), ArmISA::SveStStructSS< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), PowerISA::IntRotateOp::generateDisassembly(), ArmISA::DataX2RegOp::generateDisassembly(), ArmISA::MemoryDImmEx64::generateDisassembly(), ArmISA::SveCompTermOp::generateDisassembly(), RegRegOp::generateDisassembly(), MiscRegRegImmOp64::generateDisassembly(), ArmISA::MemoryPreIndex64::generateDisassembly(), ArmISA::SveUnaryPredOp::generateDisassembly(), ArmISA::DataX2RegImmOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), ArmISA::ArmStaticInst::generateDisassembly(), RegMiscRegImmOp64::generateDisassembly(), PowerISA::BranchPCRelCond::generateDisassembly(), ArmISA::MemoryPostIndex64::generateDisassembly(), ArmISA::SveUnaryUnpredOp::generateDisassembly(), ArmISA::DataX3RegOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), ArmISA::SveUnaryWideImmUnpredOp::generateDisassembly(), ArmISA::MemoryReg64::generateDisassembly(), ArmISA::DataXCondCompImmOp::generateDisassembly(), RegRegRegRegOp::generateDisassembly(), PowerISA::BranchNonPCRelCond::generateDisassembly(), ArmISA::MemoryRaw64::generateDisassembly(), ArmISA::SveUnaryWideImmPredOp::generateDisassembly(), ArmISA::SveLdStructSI< Element, MicroopLdMemType, MicroopDeIntrlvType >::generateDisassembly(), ArmISA::DataXCondCompRegOp::generateDisassembly(), ArmISA::MemoryEx64::generateDisassembly(), RegRegRegOp::generateDisassembly(), ArmISA::PredImmOp::generateDisassembly(), PowerISA::BranchRegCond::generateDisassembly(), ArmISA::SveBinImmUnpredConstrOp::generateDisassembly(), ArmISA::MemoryLiteral64::generateDisassembly(), ArmISA::DataXCondSelOp::generateDisassembly(), ArmISA::MicroSetPCCPSR::generateDisassembly(), RegRegImmOp::generateDisassembly(), ArmISA::SveBinImmPredOp::generateDisassembly(), ArmISA::PredIntOp::generateDisassembly(), ArmISA::MicroIntMov::generateDisassembly(), MiscRegRegImmOp::generateDisassembly(), ArmISA::SveBinWideImmUnpredOp::generateDisassembly(), ArmISA::DataImmOp::generateDisassembly(), ArmISA::SveBinDestrPredOp::generateDisassembly(), RegMiscRegImmOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), ArmISA::DataRegOp::generateDisassembly(), ArmISA::SveStStructSI< Element, MicroopStMemType, MicroopIntrlvType >::generateDisassembly(), ArmISA::SveBinConstrPredOp::generateDisassembly(), RegImmImmOp::generateDisassembly(), ArmISA::MicroIntImmXOp::generateDisassembly(), ArmISA::DataRegRegOp::generateDisassembly(), ArmISA::SveBinUnpredOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), ArmISA::MicroIntOp::generateDisassembly(), ArmISA::SveBinIdxUnpredOp::generateDisassembly(), ArmISA::MicroIntRegXOp::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), ArmISA::SvePredLogicalOp::generateDisassembly(), ArmISA::PredMacroOp::generateDisassembly(), ArmISA::MemoryOffset< Base >::generateDisassembly(), ArmISA::SvePredBinPermOp::generateDisassembly(), ArmISA::SveCmpOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::SveCmpImmOp::generateDisassembly(), ArmISA::SveIndexedMemVI< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::generateDisassembly(), ArmISA::MicroMemPairOp::generateDisassembly(), ArmISA::MemoryPreIndex< Base >::generateDisassembly(), ArmISA::SveTerPredOp::generateDisassembly(), ArmISA::SveTerImmUnpredOp::generateDisassembly(), ArmISA::SveReducOp::generateDisassembly(), ArmISA::SveOrdReducOp::generateDisassembly(), ArmISA::MemoryPostIndex< Base >::generateDisassembly(), ArmISA::SvePtrueOp::generateDisassembly(), ArmISA::SveIntCmpOp::generateDisassembly(), ArmISA::SveIndexedMemSV< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::generateDisassembly(), ArmISA::SveIntCmpImmOp::generateDisassembly(), ArmISA::SveAdrOp::generateDisassembly(), ArmISA::SveElemCountOp::generateDisassembly(), ArmISA::SvePartBrkOp::generateDisassembly(), ArmISA::SvePartBrkPropOp::generateDisassembly(), ArmISA::SveSelectOp::generateDisassembly(), ArmISA::SveUnaryPredPredOp::generateDisassembly(), ArmISA::SveTblOp::generateDisassembly(), ArmISA::SveUnpackOp::generateDisassembly(), ArmISA::SvePredTestOp::generateDisassembly(), ArmISA::SvePredUnaryWImplicitSrcOp::generateDisassembly(), ArmISA::SvePredUnaryWImplicitSrcPredOp::generateDisassembly(), ArmISA::SvePredUnaryWImplicitDstOp::generateDisassembly(), ArmISA::SveWImplicitSrcDstOp::generateDisassembly(), ArmISA::SveBinImmUnpredDestrOp::generateDisassembly(), ArmISA::SveBinImmIdxUnpredOp::generateDisassembly(), ArmISA::SveUnarySca2VecUnpredOp::generateDisassembly(), ArmISA::SveDotProdIdxOp::generateDisassembly(), ArmISA::SveDotProdOp::generateDisassembly(), ArmISA::SveComplexOp::generateDisassembly(), ArmISA::SveComplexIdxOp::generateDisassembly(), ArmISA::FpCondCompRegOp::generateDisassembly(), ArmISA::FpCondSelOp::generateDisassembly(), ArmISA::FpRegRegOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegRegCondOp::generateDisassembly(), ArmISA::FpRegRegRegRegOp::generateDisassembly(), ArmISA::FpRegRegRegImmOp::generateDisassembly(), BaseKvmCPU::getAndFormatOneReg(), LdsState::getDynInstr(), ThermalDomain::getNode(), Logger::print(), Linux::DebugPrintkEvent::process(), LdsState::process(), sc_core::sc_port_base::report_error(), sc_core::sc_vector_base::reportEmpty(), sc_dt::sc_proxy_out_of_bounds(), sc_core::sc_spawn_options::set_stack_size(), sc_gem5::TraceFile::set_time_unit(), ThermalDomain::setSubSystem(), TEST(), TEST_F(), sc_core::sc_time::to_string(), sc_dt::sc_length_param::to_string(), sc_dt::sc_fxtype_params::to_string(), and sc_core::sc_time_tuple::to_string().
st
Bitfield< 11 > ArmISA::st
Definition at line 154 of file miscregs_types.hh.
Referenced by __stattest(), CPA::hwWe(), OutputDirectory::isFile(), EcoffObject::loadLocalSymbols(), EventQueue::name(), AnnotateDumpCallback::process(), and LSQ< Impl >::LSQRequest::senderState().
StackPointerReg
const int ArmISA::StackPointerReg = INTREG_SP
Definition at line 121 of file registers.hh.
Referenced by getArgument(), and ArmISA::ArmStaticInst::printIntReg().
status
Bitfield<5, 0> ArmISA::status
Definition at line 396 of file miscregs_types.hh.
Referenced by FullO3CPU< O3CPUImpl >::addThreadToExitingList(), MipsISA::MipsFaultBase::base(), FastModel::ScxEvsCortexA76< Types >::before_end_of_elaboration(), bindFunc(), MipsISA::Interrupts::checkInterrupts(), FDArray::closeFDEntry(), MipsISA::ISA::configCP(), connectFunc(), FullO3CPU< O3CPUImpl >::drainResume(), IdeController::EndBitUnion(), exitImpl(), MipsISA::forkThread(), MipsISA::Interrupts::getInterrupt(), VirtIODeviceBase::getQueueSize(), getsocknameFunc(), getsockoptFunc(), RiscvISA::Interrupts::globalMask(), RiscvISA::RiscvFault::invoke(), RiscvISA::Reset::invoke(), MipsISA::ResetFault::invoke(), ioctlFunc(), ComputeUnit::isSimdDone(), listenFunc(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), MipsISA::TlbRefillFault::offset(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), IGbE::RxDescCache::pktComplete(), pollFunc(), Uart8250::processIntrEvent(), Pl050::read(), ArmSemihosting::readString(), ComputeUnit::ReadyWorkgroup(), PS2Mouse::recv(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), ConditionRegisterState::regBusy(), VectorRegisterFile::regBusy(), VectorRegisterFile::regNxtBusy(), rmdirFunc(), Sinic::Device::rxKick(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendBeginResp(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendEndReq(), PS2Mouse::serialize(), Pl050::serialize(), IdeController::serialize(), VirtIODeviceBase::setDeviceStatus(), MipsISA::MipsFaultBase::setExceptionState(), setsockoptFunc(), socketpairFunc(), DrainManager::tryDrain(), PS2Mouse::unserialize(), Pl050::unserialize(), IdeController::unserialize(), MipsISA::updateStatusView(), MipsISA::updateTCStatusView(), MinorCPU::wakeup(), FullO3CPU< O3CPUImpl >::wakeup(), PciVirtIO::write(), and ThreadContext::~ThreadContext().
stride
Bitfield<21, 20> ArmISA::stride
Definition at line 420 of file miscregs_types.hh.
Referenced by ArmISA::VfpMacroOp::addStride(), AccessMapPatternMatching::calculatePrefetch(), SignaturePathPrefetcher::calculatePrefetch(), AccessMapPatternMatching::checkCandidate(), SignaturePathPrefetcher::PatternEntry::findStride(), SignaturePathPrefetcher::PatternEntry::getStrideEntry(), Prefetcher::initializeStream(), SBOOEPrefetcher::Sandbox::insert(), QueuedPrefetcher::insert(), makeNextStrideAddress(), ArmISA::TableWalker::LongDescriptor::nextDescAddr(), ArmISA::VfpMacroOp::nextIdxs(), Prefetcher::observeMiss(), ArmISA::TableWalker::processWalkAArch64(), ComputeUnit::DTLBPort::recvTimingResp(), Prefetcher::setController(), SignaturePathPrefetcher::updateSignature(), and ArmISA::VfpMacroOp::VfpMacroOp().
subArchDefined
Bitfield<29, 0> ArmISA::subArchDefined
Definition at line 435 of file miscregs_types.hh.
sve
Bitfield<35, 32> ArmISA::sve
Definition at line 171 of file miscregs_types.hh.
sveLen
Bitfield<59, 56> ArmISA::sveLen
Definition at line 77 of file types.hh.
sw
Bitfield<10> ArmISA::sw
Definition at line 350 of file miscregs_types.hh.
swio
Bitfield<1> ArmISA::swio
Definition at line 271 of file miscregs_types.hh.
SyscallNumReg
const int ArmISA::SyscallNumReg = ReturnValueReg
Definition at line 127 of file registers.hh.
SyscallPseudoReturnReg
const int ArmISA::SyscallPseudoReturnReg = ReturnValueReg
Definition at line 128 of file registers.hh.
SyscallSuccessReg
const int ArmISA::SyscallSuccessReg = ReturnValueReg
Definition at line 129 of file registers.hh.
t
Bitfield<5> ArmISA::t
Definition at line 70 of file miscregs_types.hh.
Referenced by BasePrefetcher::addTLB(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::callback_binder_fw< tlm::tlm_base_protocol_types >::b_transport(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), BitfieldBackend::bitfieldBackendPrinter(), MultiSocketSimpleSwitchAT::bwPEQcb(), TAGE_SC_L_TAGE::calculateIndicesAndTags(), sc_gem5::ProcessObjFuncWrapper< T >::call(), sc_gem5::ProcessObjRetFuncWrapper< T, R >::call(), sc_gem5::TraceVal< bool, VcdTraceValBase >::check(), sc_gem5::TraceValFxnumBase<::sc_dt::sc_fxnum_fast, Base >::check(), IGbE::chkInterrupt(), SimpleATInitiator1::SimplePool::claim(), SimpleATInitiator2::SimplePool::claim(), SparcISA::TLB::clearUsedBits(), QueuedPrefetcher::DeferredPacket::createPkt(), TimingSimpleCPU::TimingCPUPort::TickEvent::description(), FullO3CPU< O3CPUImpl >::drain(), HDLcd::PixelPump::dumpSettings(), SimpleATTarget1::endRequest(), SimpleATInitiator1::endResponse(), sc_gem5::TraceVal< bool, VcdTraceValBase >::finalize(), sc_gem5::TraceValFxnumBase<::sc_dt::sc_fxnum_fast, Base >::finalize(), Packet::findNextSenderState(), SimpleATInitiator1::SimplePool::free(), SimpleATInitiator2::SimplePool::free(), sc_core::sc_time::from_seconds(), sc_core::sc_time::from_value(), MultiSocketSimpleSwitchAT::fwPEQcb(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getAddrRanges(), Sequencer::getFirstResponseToCompletionDelayHist(), GPUCoalescer::getFirstResponseToCompletionDelayHist(), Sequencer::getForwardRequestToFirstResponseHist(), GPUCoalescer::getForwardRequestToFirstResponseHist(), Sequencer::getHitMachLatencyHist(), Sequencer::getHitTypeLatencyHist(), Sequencer::getHitTypeMachLatencyHist(), Sequencer::getIncompleteTimes(), Sequencer::getInitialToForwardDelayHist(), GPUCoalescer::getInitialToForwardDelayHist(), Sequencer::getIssueToInitialDelayHist(), GPUCoalescer::getIssueToInitialDelayHist(), Sequencer::getMissMachLatencyHist(), GPUCoalescer::getMissMachLatencyHist(), Sequencer::getMissTypeLatencyHist(), GPUCoalescer::getMissTypeLatencyHist(), Sequencer::getMissTypeMachLatencyHist(), GPUCoalescer::getMissTypeMachLatencyHist(), Sequencer::getTypeLatencyHist(), GPUCoalescer::getTypeLatencyHist(), MultiperspectivePerceptron::RECENCYPOS::hash(), MultiperspectivePerceptron::HistorySpec::HistorySpec(), CPA::hwWe(), tlm_utils::tlm_quantumkeeper::inc(), sc_core::sc_inout< sc_dt::sc_lv< W > >::initialize(), SparcISA::TLB::lookup(), sc_dt::multiply(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm::tlm_put_get_imp< RSP, REQ >::nb_can_get(), tlm::tlm_put_get_imp< RSP, REQ >::nb_can_peek(), tlm::tlm_put_get_imp< RSP, REQ >::nb_can_put(), tlm::tlm_fifo< T >::nb_poke(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::callback_binder_bw< tlm::tlm_base_protocol_types >::nb_transport_bw(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::callback_binder_fw< tlm::tlm_base_protocol_types >::nb_transport_fw(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), ArchTimer::offset(), tlm::tlm_put_get_imp< RSP, REQ >::ok_to_get(), tlm::tlm_put_get_imp< RSP, REQ >::ok_to_peek(), tlm::tlm_put_get_imp< RSP, REQ >::ok_to_put(), CircularQueue< T >::iterator::operator+(), CircularQueue< T >::iterator::operator++(), CircularQueue< T >::iterator::operator-(), CircularQueue< T >::iterator::operator--(), CircularQueue< T >::iterator::operator-=(), QueuedPrefetcher::DeferredPacket::operator<=(), sc_dt::sc_subref< X >::operator=(), TrafficGen::parseConfig(), tlm::circular_buffer< T >::poke_data(), BaseDynInst< Impl >::popResult(), SparcISA::PageTableEntry::populate(), MSHR::TargetList::populateFlags(), IGbE::postInterrupt(), WriteQueueEntry::TargetList::print(), MSHR::TargetList::print(), AnnotateDumpCallback::process(), MSHR::promoteDeferredTargets(), MSHR::promoteReadable(), MSHR::promoteWritable(), sc_gem5::NodeList< Process >::pushFirst(), sc_gem5::NodeList< Process >::pushLast(), pybind_init_core(), pybind_init_event(), tlm::circular_buffer< T >::read(), sc_core::sc_fifo< T >::read(), RealViewTemperatureSensor::read(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SerialLink::SerialLinkMasterPort::recvTimingResp(), EventQueue::replaceHead(), MSHR::TargetList::replaceUpgrades(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::RequestThread(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::ResponseThread(), sc_dt::sc_proxy< sc_subref_r< X > >::reverse(), SimpleLTInitiator2::run(), SimpleLTInitiator3::run(), SimpleLTInitiator1::run(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), CoreDecouplingLTInitiator::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), SimpleATInitiator2::run(), SimpleATInitiator1::run(), sc_gem5::Event::sc_event(), SC_MODULE(), Consumer::scheduleEventAbsolute(), Serializable::serializeAll(), tlm::tlm_global_quantum::set(), tlm_utils::tlm_quantumkeeper::set(), tlm_utils::tlm_quantumkeeper::set_and_sync(), tlm::tlm_dmi::set_read_latency(), tlm::tlm_dmi::set_write_latency(), CheckerCPU::setScalarResult(), BaseDynInst< Impl >::setScalarResult(), TaggedEntry::setTag(), CheckerCPU::setVecElemResult(), BaseDynInst< Impl >::setVecElemResult(), CheckerCPU::setVecPredResult(), BaseDynInst< Impl >::setVecPredResult(), CheckerCPU::setVecResult(), BaseDynInst< Impl >::setVecResult(), LinearSystem::solve(), BaseCPU::suspendContext(), sc_gem5::BuiltinExceptionWrapper< T >::throw_it(), sc_gem5::ExceptionWrapper< T >::throw_it(), timeFunc(), tlm::tlm_analysis_triple< T >::tlm_analysis_triple(), WriteQueueEntry::TargetList::trySatisfyFunctional(), MSHR::TargetList::trySatisfyFunctional(), SerialLink::SerialLinkSlavePort::trySendTiming(), SerialLink::SerialLinkMasterPort::trySendTiming(), BaseRemoteGDB::TrapEvent::type(), Globals::unserialize(), MPP_TAGE::updatePathAndGlobalHistory(), TAGE_SC_L_TAGE::updatePathAndGlobalHistory(), sc_core::sc_buffer< T, WRITER_POLICY >::write(), and sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >::write().
t0
Bitfield<0> ArmISA::t0
Definition at line 232 of file miscregs_types.hh.
Referenced by fp16_sqrt(), fp32_sqrt(), fp64_muladd(), and mul64x32().
t0sz
ArmISA::t0sz
Definition at line 466 of file miscregs_types.hh.
t0sz64
Bitfield<5, 0> ArmISA::t0sz64
Definition at line 533 of file miscregs_types.hh.
t1
Bitfield<1> ArmISA::t1
Definition at line 231 of file miscregs_types.hh.
Referenced by ArmISA::Crypto::aesMixColumns(), ThreadContext::compare(), fp16_sqrt(), fp32_sqrt(), fp64_muladd(), and mul64x32().
t10
Bitfield<10> ArmISA::t10
Definition at line 222 of file miscregs_types.hh.
t11
Bitfield<11> ArmISA::t11
Definition at line 221 of file miscregs_types.hh.
t12
Bitfield<12> ArmISA::t12
Definition at line 220 of file miscregs_types.hh.
t13
Bitfield<13> ArmISA::t13
Definition at line 219 of file miscregs_types.hh.
t15
Bitfield<15> ArmISA::t15
Definition at line 218 of file miscregs_types.hh.
t1sz
Bitfield< 21, 16 > ArmISA::t1sz
Definition at line 473 of file miscregs_types.hh.
t2
Bitfield<2> ArmISA::t2
Definition at line 230 of file miscregs_types.hh.
Referenced by ThreadContext::compare().
t2e
Bitfield<6> ArmISA::t2e
Definition at line 467 of file miscregs_types.hh.
t3
Bitfield<3> ArmISA::t3
Definition at line 229 of file miscregs_types.hh.
t4
Bitfield<4> ArmISA::t4
Definition at line 228 of file miscregs_types.hh.
t5
Bitfield<5> ArmISA::t5
Definition at line 227 of file miscregs_types.hh.
t6
Bitfield<6> ArmISA::t6
Definition at line 226 of file miscregs_types.hh.
t7
Bitfield<7> ArmISA::t7
Definition at line 225 of file miscregs_types.hh.
t8
Bitfield<8> ArmISA::t8
Definition at line 224 of file miscregs_types.hh.
t9
Bitfield<9> ArmISA::t9
Definition at line 223 of file miscregs_types.hh.
tac
Bitfield<21> ArmISA::tac
Definition at line 250 of file miscregs_types.hh.
tacr
Bitfield<21> ArmISA::tacr
Definition at line 251 of file miscregs_types.hh.
tagRAMLatency
Bitfield<8,6> ArmISA::tagRAMLatency
Definition at line 595 of file miscregs_types.hh.
tagRAMSetup
Bitfield<9> ArmISA::tagRAMSetup
Definition at line 596 of file miscregs_types.hh.
tagRAMSlice
Bitfield<12> ArmISA::tagRAMSlice
Definition at line 598 of file miscregs_types.hh.
tase
Bitfield<15> ArmISA::tase
Definition at line 196 of file miscregs_types.hh.
tbi
Bitfield< 20 > ArmISA::tbi
Definition at line 488 of file miscregs_types.hh.
Referenced by TAGE_SC_L_TAGE::getUseAltIdx().
tbi0
Bitfield< 37 > ArmISA::tbi0
Definition at line 482 of file miscregs_types.hh.
tbi1
Bitfield< 38 > ArmISA::tbi1
Definition at line 483 of file miscregs_types.hh.
tcp0
Bitfield<0> ArmISA::tcp0
Definition at line 212 of file miscregs_types.hh.
tcp1
Bitfield<1> ArmISA::tcp1
Definition at line 211 of file miscregs_types.hh.
tcp10
Bitfield<10> ArmISA::tcp10
Definition at line 200 of file miscregs_types.hh.
tcp11
Bitfield<11> ArmISA::tcp11
Definition at line 199 of file miscregs_types.hh.
tcp12
Bitfield<12> ArmISA::tcp12
Definition at line 198 of file miscregs_types.hh.
tcp13
Bitfield<13> ArmISA::tcp13
Definition at line 197 of file miscregs_types.hh.
tcp2
Bitfield<2> ArmISA::tcp2
Definition at line 210 of file miscregs_types.hh.
tcp3
Bitfield<3> ArmISA::tcp3
Definition at line 209 of file miscregs_types.hh.
tcp4
Bitfield<4> ArmISA::tcp4
Definition at line 208 of file miscregs_types.hh.
tcp5
Bitfield<5> ArmISA::tcp5
Definition at line 207 of file miscregs_types.hh.
tcp6
Bitfield<6> ArmISA::tcp6
Definition at line 206 of file miscregs_types.hh.
tcp7
Bitfield<7> ArmISA::tcp7
Definition at line 205 of file miscregs_types.hh.
tcp8
Bitfield<8> ArmISA::tcp8
Definition at line 203 of file miscregs_types.hh.
tcp9
Bitfield<9> ArmISA::tcp9
Definition at line 202 of file miscregs_types.hh.
tda
Bitfield<9> ArmISA::tda
Definition at line 185 of file miscregs_types.hh.
tde
Bitfield<8> ArmISA::tde
Definition at line 186 of file miscregs_types.hh.
tdosa
Bitfield<10> ArmISA::tdosa
Definition at line 184 of file miscregs_types.hh.
tdz
Bitfield<28> ArmISA::tdz
Definition at line 242 of file miscregs_types.hh.
tfp
Bitfield< 10 > ArmISA::tfp
Definition at line 201 of file miscregs_types.hh.
tg0
Bitfield< 15, 14 > ArmISA::tg0
Definition at line 472 of file miscregs_types.hh.
tg1
Bitfield< 31, 30 > ArmISA::tg1
Definition at line 479 of file miscregs_types.hh.
tge
Bitfield<27> ArmISA::tge
Definition at line 244 of file miscregs_types.hh.
tgran16
Bitfield<23, 20> ArmISA::tgran16
Definition at line 127 of file miscregs_types.hh.
tgran16_2
Bitfield<35, 32> ArmISA::tgran16_2
Definition at line 124 of file miscregs_types.hh.
tgran4
Bitfield<31, 28> ArmISA::tgran4
Definition at line 125 of file miscregs_types.hh.
tgran4_2
Bitfield<43, 40> ArmISA::tgran4_2
Definition at line 122 of file miscregs_types.hh.
tgran64
Bitfield<27, 24> ArmISA::tgran64
Definition at line 126 of file miscregs_types.hh.
tgran64_2
Bitfield<39, 36> ArmISA::tgran64_2
Definition at line 123 of file miscregs_types.hh.
thee
Bitfield<6> ArmISA::thee
Definition at line 359 of file miscregs_types.hh.
thumb
Bitfield<36> ArmISA::thumb
Definition at line 89 of file types.hh.
Referenced by EndBitUnion().
tid0
Bitfield<15> ArmISA::tid0
Definition at line 257 of file miscregs_types.hh.
tid1
Bitfield<16> ArmISA::tid1
Definition at line 256 of file miscregs_types.hh.
tid2
Bitfield<17> ArmISA::tid2
Definition at line 255 of file miscregs_types.hh.
tid3
Bitfield<18> ArmISA::tid3
Definition at line 254 of file miscregs_types.hh.
tidcp
Bitfield<20> ArmISA::tidcp
Definition at line 252 of file miscregs_types.hh.
tlb
Bitfield<59, 56> ArmISA::tlb
Definition at line 91 of file miscregs_types.hh.
Referenced by AlphaISA::getDTBPtr(), getDTBPtr(), AlphaISA::getITBPtr(), getITBPtr(), and try_translate().
top6
Bitfield<7, 2> ArmISA::top6
Definition at line 66 of file types.hh.
topcode10_8
Bitfield<10, 8> ArmISA::topcode10_8
Definition at line 176 of file types.hh.
topcode10_9
Bitfield<10, 9> ArmISA::topcode10_9
Definition at line 175 of file types.hh.
topcode11_8
Bitfield<11, 8> ArmISA::topcode11_8
Definition at line 174 of file types.hh.
topcode11_9
Bitfield<11, 9> ArmISA::topcode11_9
Definition at line 173 of file types.hh.
topcode12_10
Bitfield<12, 10> ArmISA::topcode12_10
Definition at line 172 of file types.hh.
topcode12_11
Bitfield<12, 11> ArmISA::topcode12_11
Definition at line 171 of file types.hh.
topcode13_11
Bitfield<13, 11> ArmISA::topcode13_11
Definition at line 170 of file types.hh.
topcode15_13
Bitfield<15, 13> ArmISA::topcode15_13
Definition at line 169 of file types.hh.
topcode3_0
Bitfield<3, 0> ArmISA::topcode3_0
Definition at line 182 of file types.hh.
topcode7
Bitfield<7> ArmISA::topcode7
Definition at line 178 of file types.hh.
topcode7_4
Bitfield<7, 4> ArmISA::topcode7_4
Definition at line 181 of file types.hh.
topcode7_5
Bitfield<7, 5> ArmISA::topcode7_5
Definition at line 180 of file types.hh.
topcode7_6
Bitfield<7, 6> ArmISA::topcode7_6
Definition at line 179 of file types.hh.
topcode9_6
Bitfield<9, 6> ArmISA::topcode9_6
Definition at line 177 of file types.hh.
TotalNumRegs
const int ArmISA::TotalNumRegs
Initial value:
= NumIntRegs + NumFloatRegs + NumVecRegs +
    NumVecPredRegs + NumMiscRegs
Definition at line 107 of file registers.hh.
tpc
Bitfield<23> ArmISA::tpc
Definition at line 248 of file miscregs_types.hh.
tpm
Bitfield<6> ArmISA::tpm
Definition at line 188 of file miscregs_types.hh.
tpmcr
Bitfield<5> ArmISA::tpmcr
Definition at line 189 of file miscregs_types.hh.
tpu
Bitfield<24> ArmISA::tpu
Definition at line 247 of file miscregs_types.hh.
tr0
ArmISA::tr0
Definition at line 545 of file miscregs_types.hh.
tr1
Bitfield<3,2> ArmISA::tr1
Definition at line 546 of file miscregs_types.hh.
tr2
Bitfield<5,4> ArmISA::tr2
Definition at line 547 of file miscregs_types.hh.
tr3
Bitfield<7,6> ArmISA::tr3
Definition at line 548 of file miscregs_types.hh.
tr4
Bitfield<9,8> ArmISA::tr4
Definition at line 549 of file miscregs_types.hh.
tr5
Bitfield<11,10> ArmISA::tr5
Definition at line 550 of file miscregs_types.hh.
tr6
Bitfield<13,12> ArmISA::tr6
Definition at line 551 of file miscregs_types.hh.
tr7
Bitfield<15,14> ArmISA::tr7
Definition at line 552 of file miscregs_types.hh.
tracefilt
ArmISA::tracefilt
Definition at line 78 of file miscregs_types.hh.
tracever
Bitfield<7, 4> ArmISA::tracever
Definition at line 85 of file miscregs_types.hh.
tre
Bitfield<28> ArmISA::tre
Definition at line 317 of file miscregs_types.hh.
trvm
Bitfield<30> ArmISA::trvm
Definition at line 240 of file miscregs_types.hh.
ts
Bitfield<55, 52> ArmISA::ts
Definition at line 92 of file miscregs_types.hh.
Referenced by sc_gem5::Scheduler::clear(), Net::IpOpt::data(), sc_gem5::Scheduler::deschedule(), sc_gem5::Scheduler::schedule(), and sleep().
tsc
Bitfield<19> ArmISA::tsc
Definition at line 253 of file miscregs_types.hh.
tsw
Bitfield<22> ArmISA::tsw
Definition at line 249 of file miscregs_types.hh.
tta
Bitfield< 20 > ArmISA::tta
Definition at line 195 of file miscregs_types.hh.
ttee
Bitfield<16> ArmISA::ttee
Definition at line 217 of file miscregs_types.hh.
ttl
Bitfield<51, 48> ArmISA::ttl
Definition at line 150 of file miscregs_types.hh.
ttlb
Bitfield<25> ArmISA::ttlb
Definition at line 246 of file miscregs_types.hh.
tvm
Bitfield<26> ArmISA::tvm
Definition at line 245 of file miscregs_types.hh.
twe
Bitfield<14> ArmISA::twe
Definition at line 258 of file miscregs_types.hh.
twi
Bitfield< 12 > ArmISA::twi
Definition at line 259 of file miscregs_types.hh.
tz
Bitfield< 8 > ArmISA::tz
Definition at line 204 of file miscregs_types.hh.
Referenced by mkutctime().
u
Bitfield<22> ArmISA::u
Definition at line 328 of file miscregs_types.hh.
Referenced by bitsToFloat32(), bitsToFloat64(), floatToBits32(), floatToBits64(), FPCRRounding(), sc_core::sc_time::from_value(), sc_dt::get_base_and_sign(), sc_dt::get_sign(), MPP_TAGE::handleUReset(), TAGE_SC_L_TAGE::handleUReset(), TAGEBase::handleUReset(), tlm_utils::callback_binder_bw< tlm::tlm_base_protocol_types >::invalidate_direct_mem_ptr(), sc_dt::sc_unsigned::invert(), sc_dt::sc_signed::invert(), ArmISA::ISA::MiscRegLUTEntryInitializer::mapsTo(), MPP_TAGE::MPP_TAGE(), sc_dt::operator<<(), SparcISA::SparcStaticInst::passesFpCondition(), TAGE_SC_L_TAGE_8KB::TAGE_SC_L_TAGE_8KB(), BitUnionData::templatedFunction(), tlm::tlm_generic_payload::update_original_from(), sc_dt::vec_add_on(), sc_dt::vec_add_on2(), sc_dt::vec_div_small(), sc_dt::vec_rem_on_small(), sc_dt::vec_rem_small(), sc_dt::vec_shift_left(), sc_dt::vec_shift_right(), sc_dt::vec_sub_on(), and sc_dt::vec_sub_on2().
uao
Bitfield<7, 4> ArmISA::uao
Definition at line 160 of file miscregs_types.hh.
uci
Bitfield<26> ArmISA::uci
Definition at line 319 of file miscregs_types.hh.
uct
Bitfield<15> ArmISA::uct
Definition at line 342 of file miscregs_types.hh.
ufc
Bitfield<3> ArmISA::ufc
Definition at line 409 of file miscregs_types.hh.
ufe
Bitfield<11> ArmISA::ufe
Definition at line 415 of file miscregs_types.hh.
uma
Bitfield<9> ArmISA::uma
Definition at line 352 of file miscregs_types.hh.
unflattenResultMiscReg
int ArmISA::unflattenResultMiscReg[NUM_MISCREGS]
If the reg is a child reg of a banked set, then the parent is the last banked one in the list.
This is messy, and the wish is to eventually have the bitmap replaced with a better data structure. the preUnflatten function initializes a lookup table to speed up the search for these banked registers.
Definition at line 1095 of file miscregs.cc.
up
Bitfield<23> ArmISA::up
Definition at line 134 of file types.hh.
Referenced by ArmISA::MacroVFPMemOp::MacroVFPMemOp(), and TAGEBase::BranchInfo::~BranchInfo().
USegBase
const Addr ArmISA::USegBase = ULL(0x0)
Definition at line 78 of file isa_traits.hh.
USegEnd
const Addr ArmISA::USegEnd = ULL(0x7FFFFFFF)
Definition at line 79 of file isa_traits.hh.
useImm
Bitfield<25> ArmISA::useImm
Definition at line 101 of file types.hh.
uwxn
Bitfield<20> ArmISA::uwxn
Definition at line 331 of file miscregs_types.hh.
v
Bitfield< 28 > ArmISA::v
Definition at line 54 of file miscregs_types.hh.
Referenced by sc_gem5::VcdTraceFile::addNewTraceVal(), sc_gem5::VcdTraceFile::addTraceVal(), Trace::TarmacParserRecord::advanceTrace(), sc_dt::sc_concat_bool::allocate(), ArmISA::ISA::MiscRegLUTEntryInitializer::allPrivileges(), IniFile::Entry::appendValue(), ArmISA::ISA::MiscRegLUTEntryInitializer::banked(), ArmISA::ISA::MiscRegLUTEntryInitializer::banked64(), ArmISA::ISA::MiscRegLUTEntryInitializer::bankedChild(), LSQ< Impl >::cacheBlocked(), CircularQueue< char >::decrease(), sc_dt::get_base_and_sign(), VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr >::get_bits(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::get_handle(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::get_handle(), Packet::getConstPtr(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), htop9(), ArmISA::ISA::MiscRegLUTEntryInitializer::hyp(), ArmISA::ISA::MiscRegLUTEntryInitializer::hypRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::hypWrite(), ArmISA::ISA::MiscRegLUTEntryInitializer::implemented(), InstResult::InstResult(), sc_dt::is_nan(), sc_gem5::Process::isUnwinding(), ArmISA::TlbEntry::match(), ArmISA::ISA::MiscRegLUTEntryInitializer::mon(), ArmISA::ISA::MiscRegLUTEntryInitializer::monNonSecure(), ArmISA::ISA::MiscRegLUTEntryInitializer::monNonSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::monNonSecureWrite(), ArmISA::ISA::MiscRegLUTEntryInitializer::monSecure(), ArmISA::ISA::MiscRegLUTEntryInitializer::monSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::monSecureWrite(), ArmISA::ISA::MiscRegLUTEntryInitializer::mutex(), ArmISA::ISA::MiscRegLUTEntryInitializer::nonSecure(), PerfectSwitch::operateMessageBuffer(), sc_dt::sc_uint_base::operator%=(), sc_dt::sc_int_base::operator%=(), sc_dt::sc_unsigned::operator%=(), sc_dt::operator&(), sc_dt::sc_uint_base::operator&=(), sc_dt::sc_int_base::operator&=(), sc_dt::sc_uint_base::operator*=(), sc_dt::sc_int_base::operator*=(), sc_dt::sc_uint_base::operator+=(), sc_dt::sc_int_base::operator+=(), sc_dt::sc_uint_base::operator-=(), sc_dt::sc_int_base::operator-=(), sc_dt::sc_uint_base::operator/=(), sc_dt::sc_int_base::operator/=(), sc_dt::operator<<(), sc_dt::sc_uint_base::operator<<=(), sc_dt::sc_int_base::operator<<=(), sc_core::sc_unsigned_sigref::operator=(), sc_core::sc_signed_sigref::operator=(), sc_dt::sc_concatref::operator=(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), sc_dt::sc_uint_base::operator>>=(), sc_dt::sc_int_base::operator>>=(), sc_dt::sc_uint_base::operator^=(), sc_dt::sc_int_base::operator^=(), sc_dt::sc_uint_base::operator|=(), sc_dt::sc_int_base::operator|=(), p9toh(), MathExpr::parse(), SparcISA::SparcStaticInst::passesCondition(), ArmISA::ISA::MiscRegLUTEntryInitializer::priv(), ArmISA::ISA::MiscRegLUTEntryInitializer::privNonSecure(), ArmISA::ISA::MiscRegLUTEntryInitializer::privNonSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::privNonSecureWrite(), ArmISA::ISA::MiscRegLUTEntryInitializer::privRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::privSecure(), ArmISA::ISA::MiscRegLUTEntryInitializer::privSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::privSecureWrite(), Trace::TarmacParserRecord::TarmacParserRecordEvent::process(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::put_handle(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::put_handle(), DistIface::RecvScheduler::resumeRecvTicks(), sc_core::sc_assemble_vector(), sc_dt::sc_bigint< W >::sc_bigint(), sc_dt::sc_biguint< W >::sc_biguint(), sc_core::sc_cref(), sc_dt::sc_int_base::sc_int_base(), sc_core::sc_int_part_if::sc_int_part_if(), sc_dt::sc_int_subref::sc_int_subref(), sc_core::sc_ref(), sc_core::sc_signed_part_if::sc_signed_part_if(), sc_core::sc_time::sc_time(), sc_dt::sc_uint_base::sc_uint_base(), sc_core::sc_uint_part_if::sc_uint_part_if(), sc_dt::sc_uint_subref::sc_uint_subref(), sc_core::sc_unsigned_part_if::sc_unsigned_part_if(), ArmISA::ISA::MiscRegLUTEntryInitializer::secure(), sc_core::sc_signed_part_if::select_part(), Packet::set(), ArmISA::ISA::setMiscRegNoEffect(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), IniFile::Entry::setValue(), swap_byte(), LSQ< Impl >::LSQRequest::taskId(), testPredicate(), sc_dt::sc_logic::to_value(), sc_gem5::TraceFile::traceDeltas(), ArmISA::ISA::MiscRegLUTEntryInitializer::unverifiable(), ArmISA::ISA::MiscRegLUTEntryInitializer::user(), ArmISA::ISA::MiscRegLUTEntryInitializer::userNonSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::userNonSecureWrite(), ArmISA::ISA::MiscRegLUTEntryInitializer::userSecureRead(), ArmISA::ISA::MiscRegLUTEntryInitializer::userSecureWrite(), sc_dt::vec_div_small(), sc_dt::vec_from_char(), sc_dt::vec_from_str(), sc_dt::vec_mul(), sc_dt::vec_rem_on_small(), sc_dt::vec_sub_small(), ArmISA::ISA::MiscRegLUTEntryInitializer::warnNotFail(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::write_part(), FSTranslatingPortProxy::~FSTranslatingPortProxy(), PortProxy::~PortProxy(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::~process_handle_list(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::process_handle_list::~process_handle_list(), sc_core::sc_int_sigref::~sc_int_sigref(), sc_core::sc_signed_sigref::~sc_signed_sigref(), sc_core::sc_uint_sigref::~sc_uint_sigref(), and sc_core::sc_unsigned_sigref::~sc_unsigned_sigref().
va
Bitfield<8> ArmISA::va
Definition at line 263 of file miscregs_types.hh.
Referenced by ArmISA::AbortFault< DataAbort >::AbortFault(), SparcISA::TLB::demapPage(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), ArmISA::TLB::flushAll(), GenericISA::handleGenericIprRead(), GenericISA::handleGenericIprWrite(), SparcISA::TLB::insert(), SparcISA::TLB::lookup(), X86ISA::TLB::takeOverFrom(), SMMUTranslationProcess::walkCacheUpdate(), ARMArchTLB::~ARMArchTLB(), SMMUTLB::~SMMUTLB(), ArmISA::TlbTestInterface::~TlbTestInterface(), X86ISA::GpuTLB::Translation::~Translation(), and WalkCache::~WalkCache().
VABits
const unsigned ArmISA::VABits = 32
Definition at line 81 of file isa_traits.hh.
VAddrImplMask
const Addr ArmISA::VAddrImplMask = (ULL(1) << VABits) - 1
Definition at line 83 of file isa_traits.hh.
Referenced by VAddrImpl().
VAddrUnImplMask
const Addr ArmISA::VAddrUnImplMask = ~VAddrImplMask
Definition at line 84 of file isa_traits.hh.
varange
Bitfield<19, 16> ArmISA::varange
Definition at line 157 of file miscregs_types.hh.
VecPredRegHasPackedRepr
constexpr unsigned ArmISA::VecPredRegHasPackedRepr = false
Definition at line 773 of file types.hh.
VecPredRegSizeBits
constexpr unsigned ArmISA::VecPredRegSizeBits = MaxSveVecLenInBytes
Definition at line 772 of file types.hh.
VECREG_UREG0
const int ArmISA::VECREG_UREG0 = 32
Definition at line 94 of file registers.hh.
Referenced by ArmISA::SveIndexedMemSV< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::SveIndexedMemSV(), and ArmISA::SveIndexedMemVI< RegElemType, MemElemType, MicroopType, FirstFaultWritebackMicroopType >::SveIndexedMemVI().
VecRegSizeBytes
constexpr unsigned ArmISA::VecRegSizeBytes = MaxSveVecLenInBytes
Definition at line 771 of file types.hh.
vf
Bitfield<6> ArmISA::vf
Definition at line 266 of file miscregs_types.hh.
vfpExceptionTrapping
Bitfield<15, 12> ArmISA::vfpExceptionTrapping
Definition at line 442 of file miscregs_types.hh.
vfpHalfPrecision
Bitfield<27, 24> ArmISA::vfpHalfPrecision
Definition at line 456 of file miscregs_types.hh.
vh
Bitfield<11, 8> ArmISA::vh
Definition at line 141 of file miscregs_types.hh.
vi
Bitfield<7> ArmISA::vi
Definition at line 265 of file miscregs_types.hh.
vm
Bitfield<0> ArmISA::vm
Definition at line 272 of file miscregs_types.hh.
Referenced by KvmVM::ioctl(), and MuxingKvmGic::MuxingKvmGic().
vmidbits
Bitfield<7, 4> ArmISA::vmidbits
Definition at line 142 of file miscregs_types.hh.
vse
Bitfield<8> ArmISA::vse
Definition at line 264 of file miscregs_types.hh.
width
Bitfield< 4 > ArmISA::width
Definition at line 71 of file miscregs_types.hh.
Referenced by sc_gem5::VcdTraceFile::addNewTraceVal(), Trie< Addr, uint32_t >::insert(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), Printk(), ArmISA::ArmStaticInst::satInt(), ArmISA::ArmStaticInst::saturateOp(), sc_core::sc_trace(), VncInput::setDirty(), ArmISA::ArmStaticInst::shiftReg64(), ArmISA::ArmStaticInst::uSatInt(), ArmISA::ArmStaticInst::uSaturateOp(), vfpFpToFixed(), Minor::ForwardInstData::width(), and PngWriter::write().
wnr
Bitfield<11> ArmISA::wnr
Definition at line 400 of file miscregs_types.hh.
writeback
Bitfield<21> ArmISA::writeback
Definition at line 136 of file types.hh.
Referenced by ArmISA::PairMemOp::PairMemOp(), and IGbE::DescCache< iGbReg::RxDesc >::wbComplete().
wrps
Bitfield<23, 20> ArmISA::wrps
Definition at line 82 of file miscregs_types.hh.
wxn
Bitfield<19> ArmISA::wxn
Definition at line 335 of file miscregs_types.hh.
xnx
ArmISA::xnx
Definition at line 136 of file miscregs_types.hh.
xp
Bitfield<23> ArmISA::xp
Definition at line 327 of file miscregs_types.hh.
z
Bitfield< 30 > ArmISA::z
Definition at line 349 of file miscregs_types.hh.
Referenced by SparcISA::SparcStaticInst::passesCondition(), sc_dt::sc_abs(), SC_MODULE(), testPredicate(), MultiperspectivePerceptron::update(), and MultiperspectivePerceptronTAGE::updateHistories().
zen
Bitfield<17, 16> ArmISA::zen
Definition at line 381 of file miscregs_types.hh.
ZeroReg
const int ArmISA::ZeroReg = INTREG_ZERO
Definition at line 125 of file registers.hh.