gem5: Linux Namespace Reference
Linux Namespace Reference
Classes
class DebugPrintkEvent
class DmesgDumpEvent
Dump the guest kernel's dmesg buffer to a file in gem5's output directory and print a warning.
class KernelPanicEvent
Dump the guest kernel's dmesg buffer to a file in gem5's output directory and panic.
struct pcb_struct
struct thread_info
class ThreadInfo
class UDelayEvent
A class to skip udelay() and related calls in the kernel.
Functions
void dumpDmesg (ThreadContext *tc, std::ostream &os)
Dump Linux's dmesg log buffer to the an output stream.
Function Documentation
dumpDmesg()
void Linux::dumpDmesg (ThreadContext * tc, std::ostream & os)
Dump Linux's dmesg log buffer to the an output stream.
This assumes that the kernel address mappings are available to the translating proxy.
Referenced by LinuxArmSystem::dumpDmesg(), dumpDmesgEntry(), Linux::DmesgDumpEvent::process(), and Linux::KernelPanicEvent::process().