gem5: Sinic Namespace Reference
Sinic Namespace Reference
Namespaces
Regs
Classes
class Base
class Device
class Interface
Functions
const Regs::Info & regInfo (Addr daddr)
bool regValid (Addr daddr)
Variables
const char * RxStateStrings []
const char * TxStateStrings []
Function Documentation
regInfo()
const Regs::Info& Sinic::regInfo (Addr daddr) inline
Definition at line 184 of file sinicreg.hh.
Referenced by Sinic::Device::read(), regValid(), ComputeUnit::updateEvents(), and Sinic::Device::write().
regValid()
bool Sinic::regValid (Addr daddr) inline
Definition at line 226 of file sinicreg.hh.
References regInfo().
Referenced by Trace::TarmacTracerRecordV8::TraceRegEntryV8::print(), Sinic::Device::read(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateInt(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updatePred(), Trace::TarmacTracerRecord::TraceRegEntry::updatePred(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateVec(), and Sinic::Device::write().
Variable Documentation
RxStateStrings
const char* Sinic::RxStateStrings[]
Initial value:
=
{
    "rxIdle",
    "rxFifoBlock",
    "rxBeginCopy",
    "rxCopy",
    "rxCopyDone"
}
Definition at line 53 of file sinic.cc.
TxStateStrings
const char* Sinic::TxStateStrings[]
Initial value:
=
{
    "txIdle",
    "txFifoBlock",
    "txBeginCopy",
    "txCopy",
    "txCopyDone"
}
Definition at line 62 of file sinic.cc.