gem5: GenericISA Namespace Reference
GenericISA Namespace Reference
Classes
class BasicDecodeCache
class DelaySlotPCState
class DelaySlotUPCState
class M5DebugFault
class M5DebugOnceFault
class M5FatalFault
class M5HackFaultBase
class M5InformFaultBase
class M5PanicFault
class M5WarnFaultBase
class PCStateBase
class SimplePCState
class UPCState
Typedefs
using M5WarnFault = M5WarnFaultBase< M5DebugFault >
using M5WarnOnceFault = M5WarnFaultBase< M5DebugOnceFault< M5WarnFault > >
using M5HackFault = M5HackFaultBase< M5DebugFault >
using M5HackOnceFault = M5HackFaultBase< M5DebugOnceFault< M5HackFault > >
using M5InformFault = M5InformFaultBase< M5DebugFault >
using M5InformOnceFault = M5InformFaultBase< M5DebugOnceFault< M5InformFault > >
Functions
Addr iprAddressPseudoInst (uint8_t func, uint8_t subfunc)
Generate a generic IPR address that emulates a pseudo inst.
bool isGenericIprAccess (const Packet *pkt)
Check if this is an platform independent IPR access.
Cycles handleGenericIprRead (ThreadContext *xc, Packet *pkt)
Handle generic IPR reads.
Cycles handleGenericIprWrite (ThreadContext *xc, Packet *pkt)
Handle generic IPR writes.
Cycles handleIprRead (ThreadContext *xc, Packet *pkt)
Helper function to handle IPRs when the target architecture doesn't need its own IPR handling.
Cycles handleIprWrite (ThreadContext *xc, Packet *pkt)
Helper function to handle IPRs when the target architecture doesn't need its own IPR handling.
void m5Syscall (ThreadContext *tc)
void m5PageFault (ThreadContext *tc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const SimplePCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const UPCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const DelaySlotPCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const DelaySlotUPCState< MachInst > &pc)
Variables
const int IPR_CLASS_SHIFT = 48
Memory requests with the MMAPPED_IPR flag are generally mapped to registers.
const Addr IPR_IN_CLASS_MASK = ULL(0x0000FFFFFFFFFFFF)
Mask to extract the offset in within a generic IPR class.
const Addr IPR_CLASS_PSEUDO_INST = 0x0
gem5 pseudo-inst emulation.
Typedef Documentation
M5HackFault
using GenericISA::M5HackFault = typedef M5HackFaultBase<M5DebugFault>
Definition at line 157 of file debugfaults.hh.
M5HackOnceFault
using GenericISA::M5HackOnceFault = typedef M5HackFaultBase<M5DebugOnceFault<M5HackFault> >
Definition at line 158 of file debugfaults.hh.
M5InformFault
using GenericISA::M5InformFault = typedef M5InformFaultBase<M5DebugFault>
Definition at line 169 of file debugfaults.hh.
M5InformOnceFault
using GenericISA::M5InformOnceFault = typedef M5InformFaultBase<M5DebugOnceFault<M5InformFault> >
Definition at line 171 of file debugfaults.hh.
M5WarnFault
using GenericISA::M5WarnFault = typedef M5WarnFaultBase<M5DebugFault>
Definition at line 145 of file debugfaults.hh.
M5WarnOnceFault
using GenericISA::M5WarnOnceFault = typedef M5WarnFaultBase<M5DebugOnceFault<M5WarnFault> >
Definition at line 146 of file debugfaults.hh.
Function Documentation
handleGenericIprRead()
Cycles GenericISA::handleGenericIprRead (ThreadContext * xc, Packet * pkt)
Handle generic IPR reads.
Parameters
xc Thread context of the current thread.
pkt Packet from the CPU
Returns
Latency in CPU cycles
Definition at line 56 of file mmapped_ipr.cc.
References Packet::getAddr(), handlePseudoInst(), IPR_CLASS_PSEUDO_INST, IPR_CLASS_SHIFT, panic, and ArmISA::va.
Referenced by SparcISA::handleIprRead(), X86ISA::handleIprRead(), handleIprRead(), and isGenericIprAccess().
handleGenericIprWrite()
Cycles GenericISA::handleGenericIprWrite (ThreadContext * xc, Packet * pkt)
Handle generic IPR writes.
Parameters
xc Thread context of the current thread.
pkt Packet from the CPU
Returns
Latency in CPU cycles
Definition at line 73 of file mmapped_ipr.cc.
References Packet::getAddr(), handlePseudoInst(), IPR_CLASS_PSEUDO_INST, IPR_CLASS_SHIFT, panic, and ArmISA::va.
Referenced by SparcISA::handleIprWrite(), X86ISA::handleIprWrite(), handleIprWrite(), and isGenericIprAccess().
handleIprRead()
Cycles GenericISA::handleIprRead (ThreadContext * xc, Packet * pkt) inline
Helper function to handle IPRs when the target architecture doesn't need its own IPR handling.
This function calls handleGenericIprRead if the accessing a generic IPR and panics otherwise.
Parameters
xc Thread context of the current thread.
pkt Packet from the CPU
Returns
Latency in CPU cycles
Definition at line 139 of file mmapped_ipr.hh.
References handleGenericIprRead(), isGenericIprAccess(), and panic.
Referenced by AtomicSimpleCPU::amoMem(), BaseKvmCPU::doMMIOAccess(), LSQ< Impl >::SingleDataRequest::handleIprRead(), LSQ< Impl >::SplitDataRequest::handleIprRead(), TimingSimpleCPU::handleReadPacket(), LSQ< Impl >::LSQRequest::isSplit(), AtomicSimpleCPU::readMem(), Minor::LSQ::tryToSend(), LSQ< Impl >::SingleDataRequest::~SingleDataRequest(), and LSQ< Impl >::SplitDataRequest::~SplitDataRequest().
handleIprWrite()
Cycles GenericISA::handleIprWrite (ThreadContext * xc, Packet * pkt) inline
Helper function to handle IPRs when the target architecture doesn't need its own IPR handling.
This function calls handleGenericIprWrite if the accessing a generic IPR and panics otherwise.
Parameters
xc Thread context of the current thread.
pkt Packet from the CPU
Returns
Latency in CPU cycles
Definition at line 160 of file mmapped_ipr.hh.
References handleGenericIprWrite(), isGenericIprAccess(), and panic.
Referenced by BaseKvmCPU::doMMIOAccess(), LSQ< Impl >::SingleDataRequest::handleIprWrite(), LSQ< Impl >::SplitDataRequest::handleIprWrite(), TimingSimpleCPU::handleWritePacket(), LSQ< Impl >::LSQRequest::isSplit(), Minor::LSQ::tryToSend(), AtomicSimpleCPU::writeMem(), LSQ< Impl >::SingleDataRequest::~SingleDataRequest(), and LSQ< Impl >::SplitDataRequest::~SplitDataRequest().
iprAddressPseudoInst()
Addr GenericISA::iprAddressPseudoInst (uint8_t func, uint8_t subfunc) inline
Generate a generic IPR address that emulates a pseudo inst.
See also
PseudoInst::pseudoInst()
Parameters
func Function ID to call.
subfunc Sub-function, usually 0.
Returns
Address in the IPR space corresponding to the call.
Definition at line 84 of file mmapped_ipr.hh.
Referenced by X86ISA::TLB::finalizePhysical(), and ArmISA::TLB::finalizePhysical().
isGenericIprAccess()
bool GenericISA::isGenericIprAccess (const Packet * pkt) inline
Check if this is an platform independent IPR access.
Accesses to internal platform independent gem5 registers are handled by handleGenericIprRead() and handleGenericIprWrite(). This method determines if a packet should be routed to those functions instead of the platform specific code.
See also
handleGenericIprRead
handleGenericIprWrite
Definition at line 103 of file mmapped_ipr.hh.
References Request::GENERIC_IPR, handleGenericIprRead(), handleGenericIprWrite(), Request::MMAPPED_IPR, and Packet::req.
Referenced by SparcISA::handleIprRead(), X86ISA::handleIprRead(), handleIprRead(), SparcISA::handleIprWrite(), X86ISA::handleIprWrite(), and handleIprWrite().
m5PageFault()
void GenericISA::m5PageFault (ThreadContext * tc)
Definition at line 46 of file pseudo_inst.cc.
References DPRINTF, Process::fixupStackFault(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::is, X86ISA::ISTVirtAddr, X86ISA::MISCREG_CR2, X86ISA::p, X86ISA::PageBytes, panic, PortProxy::readBlob(), and ThreadContext::readMiscReg().
Referenced by PseudoInst::pseudoInst().
m5Syscall()
void GenericISA::m5Syscall (ThreadContext * tc)
Definition at line 40 of file pseudo_inst.cc.
References DPRINTF, X86ISA::MISCREG_RFLAGS, panic, ThreadContext::readIntReg(), ThreadContext::readMiscReg(), ThreadContext::setMiscReg(), and ThreadContext::syscall().
Referenced by PseudoInst::pseudoInst().
operator<<() [1/4]
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const SimplePCState< MachInst > & pc)
Definition at line 187 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
operator<<() [2/4]
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const UPCState< MachInst > & pc)
Definition at line 285 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
operator<<() [3/4]
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const DelaySlotPCState< MachInst > & pc)
Definition at line 364 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
operator<<() [4/4]
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const DelaySlotUPCState< MachInst > & pc)
Definition at line 463 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
Variable Documentation
IPR_CLASS_PSEUDO_INST
const Addr GenericISA::IPR_CLASS_PSEUDO_INST = 0x0
gem5 pseudo-inst emulation.
Read and writes to this class execute gem5 pseudo-instructions. A write discards the return value of the instruction, while a read returns it.
See also
pseudoInst()
Definition at line 70 of file mmapped_ipr.hh.
Referenced by handleGenericIprRead(), and handleGenericIprWrite().
IPR_CLASS_SHIFT
const int GenericISA::IPR_CLASS_SHIFT = 48
Memory requests with the MMAPPED_IPR flag are generally mapped to registers.
There is a class of these registers that are internal to gem5, for example gem5 pseudo-ops in virtualized mode. Such IPRs always have the flag GENERIC_IPR set and are handled by this code.Shift amount when extracting the class of a generic IPR
Definition at line 57 of file mmapped_ipr.hh.
Referenced by handleGenericIprRead(), and handleGenericIprWrite().
IPR_IN_CLASS_MASK
const Addr GenericISA::IPR_IN_CLASS_MASK = ULL(0x0000FFFFFFFFFFFF)
Mask to extract the offset in within a generic IPR class.
Definition at line 60 of file mmapped_ipr.hh.
Referenced by handlePseudoInst().