gem5: unittest/nmtest.cc File Reference
nmtest.cc File Reference
#include <iostream>
#include <string>
#include <vector>
#include "base/loader/object_file.hh"
#include "base/loader/symtab.hh"
#include "base/logging.hh"
#include "base/str.hh"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 43 of file nmtest.cc.
References cprintf(), createObjectFile(), SymbolTable::findAddress(), SymbolTable::findSymbol(), SymbolTable::getAddrTable(), ArmISA::i, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), panic, and to_number().