gem5: base/pixel.test.cc File Reference
pixel.test.cc File Reference
#include <gtest/gtest.h>
#include "base/pixel.hh"
Functions
TEST (FBTest, PixelConversionRGBA8888)
TEST (FBTest, PixelConversionRGB565)
TEST (FBTest, PixelToMemRGBA8888LE)
TEST (FBTest, MemToPixelRGBA8888LE)
TEST (FBTest, MemToPixelRGBA8888BE)
Variables
static Pixel pixel_red (0xff, 0x00, 0x00)
static Pixel pixel_green (0x00, 0xff, 0x00)
static Pixel pixel_blue (0x00, 0x00, 0xff)
Function Documentation
TEST() [1/5]
TEST (FBTest , PixelConversionRGBA8888)
Definition at line 48 of file pixel.test.cc.
References EXPECT_EQ, pixel_blue, pixel_green, pixel_red, and PixelConverter::rgba8888_le.
TEST() [2/5]
TEST (FBTest , PixelConversionRGB565)
Definition at line 65 of file pixel.test.cc.
References EXPECT_EQ, pixel_blue, pixel_green, pixel_red, and PixelConverter::rgb565_le.
TEST() [3/5]
TEST (FBTest , PixelToMemRGBA8888LE)
Definition at line 76 of file pixel.test.cc.
References data, EXPECT_EQ, PixelConverter::fromPixel(), pixel_blue, pixel_green, pixel_red, and PixelConverter::rgba8888_le.
TEST() [4/5]
TEST (FBTest , MemToPixelRGBA8888LE)
Definition at line 101 of file pixel.test.cc.
References EXPECT_EQ, pixel_blue, pixel_green, pixel_red, SparcISA::red, and PixelConverter::rgba8888_le.
TEST() [5/5]
TEST (FBTest , MemToPixelRGBA8888BE)
Definition at line 112 of file pixel.test.cc.
References EXPECT_EQ, pixel_blue, pixel_green, pixel_red, SparcISA::red, and PixelConverter::rgba8888_be.
Variable Documentation
pixel_blue
Pixel pixel_blue(0x00, 0x00, 0xff) static
Referenced by TEST().
pixel_green
Pixel pixel_green(0x00, 0xff, 0x00) static
Referenced by TEST().
pixel_red
Pixel pixel_red(0xff, 0x00, 0x00) static
Referenced by TEST().