gem5: base/sat_counter.test.cc File Reference
sat_counter.test.cc File Reference
#include <gtest/gtest.h>
#include <utility>
#include "base/sat_counter.hh"
Functions
TEST (SatCounterTest, MaximumValue)
Test if the maximum value is indeed the maximum value reachable.
TEST (SatCounterTest, MinimumValue)
Test if the minimum value is indeed the mimimum value reachable.
TEST (SatCounterTest, InitialValue)
Test initializing the counter with a value, updating it and then resetting.
TEST (SatCounterTest, SaturationPercentile)
Test calculating saturation percentile.
TEST (SatCounterTest, Saturate)
Test abrupt saturation.
TEST (SatCounterTest, IntComparison)
Test back and forth against an int.
TEST (SatCounterTest, Shift)
Test shift operators.
TEST (SatCounterTest, PrePostOperators)
Test both pre and post operators.
TEST (SatCounterTest, CopyMove)
Test copy and move for both constructor and assignment.
TEST (SatCounterTest, AddSubAssignment)
Test add-assignment and subtract assignment.
Function Documentation
TEST() [1/10]
TEST (SatCounterTest , MaximumValue)
Test if the maximum value is indeed the maximum value reachable.
Definition at line 40 of file sat_counter.test.cc.
References bits(), and ArmISA::i.
TEST() [2/10]
TEST (SatCounterTest , MinimumValue)
Test if the minimum value is indeed the mimimum value reachable.
Definition at line 56 of file sat_counter.test.cc.
References bits(), and ArmISA::i.
TEST() [3/10]
TEST (SatCounterTest , InitialValue)
Test initializing the counter with a value, updating it and then resetting.
Definition at line 71 of file sat_counter.test.cc.
References bits(), and SatCounter::reset().
TEST() [4/10]
TEST (SatCounterTest , SaturationPercentile)
Test calculating saturation percentile.
Definition at line 85 of file sat_counter.test.cc.
References bits(), SatCounter::calcSaturation(), and SatCounter::isSaturated().
TEST() [5/10]
TEST (SatCounterTest , Saturate)
Test abrupt saturation.
Definition at line 102 of file sat_counter.test.cc.
References bits(), SatCounter::isSaturated(), and SatCounter::saturate().
TEST() [6/10]
TEST (SatCounterTest , IntComparison)
Test back and forth against an int.
Definition at line 119 of file sat_counter.test.cc.
References bits().
TEST() [7/10]
TEST (SatCounterTest , Shift)
Test shift operators.
Definition at line 143 of file sat_counter.test.cc.
References bits(), and SatCounter::reset().
TEST() [8/10]
TEST (SatCounterTest , PrePostOperators)
Test both pre and post operators.
Definition at line 192 of file sat_counter.test.cc.
References bits(), and ArmISA::i.
TEST() [9/10]
TEST (SatCounterTest , CopyMove)
Test copy and move for both constructor and assignment.
Definition at line 221 of file sat_counter.test.cc.
References bits(), ArmISA::i, and SatCounter::reset().
TEST() [10/10]
TEST (SatCounterTest , AddSubAssignment)
Test add-assignment and subtract assignment.
Definition at line 275 of file sat_counter.test.cc.
References bits().