gem5: sim/debug.cc File Reference
debug.cc File Reference
#include "sim/debug.hh"
#include <string>
#include <vector>
#include "base/debug.hh"
#include "cpu/pc_event.hh"
#include "sim/eventq_impl.hh"
#include "sim/global_event.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
#include "sim/system.hh"
Classes
struct DebugBreakEvent
Functions
void schedBreak (Tick when)
Cause the simulator to execute a breakpoint.
void schedRelBreak (Tick delta)
Cause the simulator to execute a breakpoint relative to the current tick.
void breakAtKernelFunction (const char *funcName)
Cause the simulator to execute a breakpoint when the given kernel function is reached.
void takeCheckpoint (Tick when)
Function to cause the simulator to take a checkpoint from the debugger.
void eventqDump ()
Dump all the events currently on the event queue.
int getRemoteGDBPort ()
void setRemoteGDBPort (int port)
Variables
int remote_gdb_base_port = 7000
Function Documentation
breakAtKernelFunction()
void breakAtKernelFunction (const char * funcName)
Cause the simulator to execute a breakpoint when the given kernel function is reached.
Parameters
funcName the name of the kernel function at which to break
Definition at line 100 of file debug.cc.
References System::addKernelFuncEvent(), and System::systemList.
eventqDump()
void eventqDump ()
Dump all the events currently on the event queue.
Definition at line 119 of file debug.cc.
References ArmISA::i, mainEventQueue, and numMainEventQueues.
getRemoteGDBPort()
int getRemoteGDBPort ()
Definition at line 129 of file debug.cc.
References remote_gdb_base_port.
Referenced by System::registerThreadContext().
schedBreak()
void schedBreak (Tick when)
Cause the simulator to execute a breakpoint.
Parameters
when the tick to break
Definition at line 87 of file debug.cc.
References DebugBreakEvent::DebugBreakEvent(), and warn.
Referenced by pybind_init_debug(), and schedRelBreak().
schedRelBreak()
void schedRelBreak (Tick delta)
Cause the simulator to execute a breakpoint relative to the current tick.
Parameters
delta the number of ticks to execute until breaking
Definition at line 94 of file debug.cc.
References curTick(), and schedBreak().
Referenced by RiscvISA::BreakpointFault::invokeSE().
setRemoteGDBPort()
void setRemoteGDBPort (int port)
Definition at line 137 of file debug.cc.
References remote_gdb_base_port.
Referenced by pybind_init_debug().
takeCheckpoint()
void takeCheckpoint (Tick when)
Function to cause the simulator to take a checkpoint from the debugger.
Cause the simulator to return to python to create a checkpoint.
Definition at line 111 of file debug.cc.
References curTick(), and exitSimLoop().
Variable Documentation
remote_gdb_base_port
int remote_gdb_base_port = 7000
Definition at line 126 of file debug.cc.
Referenced by getRemoteGDBPort(), and setRemoteGDBPort().