gem5: unittest/stattest.cc File Reference
stattest.cc File Reference
#include "pybind11/pybind11.h"
#include <iomanip>
#include <iostream>
#include <string>
#include "base/cprintf.hh"
#include "base/logging.hh"
#include "base/statistics.hh"
#include "base/types.hh"
#include "sim/core.hh"
#include "sim/init.hh"
#include "sim/stat_control.hh"
Classes
class TestClass
struct StatTest
Functions
double testfunc ()
StatTest & __stattest ()
static void stattest_init_pybind (py::module &m_internal)
Variables
const char * m5MainCommands []
static EmbeddedPyBind embed_ ("stattest", stattest_init_pybind)
Function Documentation
__stattest()
StatTest & __stattest ()
Definition at line 122 of file stattest.cc.
References ArmISA::st.
Referenced by stattest_init_pybind().
stattest_init_pybind()
static void stattest_init_pybind (py::module & m_internal) static
Definition at line 676 of file stattest.cc.
References __stattest(), embed_, StatTest::init(), ArmISA::m, and StatTest::run().
testfunc()
double testfunc ()
Definition at line 63 of file stattest.cc.
Referenced by StatTest::init().
Variable Documentation
embed_
EmbeddedPyBind embed_("stattest", stattest_init_pybind) static
Referenced by stattest_init_pybind().
m5MainCommands
const char* m5MainCommands[]
Initial value:
= {
    "import m5.stattestmain",
    "m5.stattestmain.main()",
    0
}
Definition at line 48 of file stattest.cc.
Referenced by m5Main(), and registerNativeModules().