gem5: base/statistics.hh File Reference
statistics.hh File Reference
Declaration of Statistics objects.
#include <algorithm>
#include <cassert>
#include <cmath>
#include <functional>
#include <iosfwd>
#include <list>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "base/stats/group.hh"
#include "base/stats/info.hh"
#include "base/stats/output.hh"
#include "base/stats/types.hh"
#include "base/cast.hh"
#include "base/cprintf.hh"
#include "base/intmath.hh"
#include "base/str.hh"
#include "base/types.hh"
Classes
class Stats::InfoProxy< Stat, Base >
class Stats::ScalarInfoProxy< Stat >
class Stats::VectorInfoProxy< Stat >
class Stats::DistInfoProxy< Stat >
class Stats::VectorDistInfoProxy< Stat >
class Stats::Vector2dInfoProxy< Stat >
struct Stats::StorageParams
class Stats::InfoAccess
class Stats::DataWrap< Derived, InfoProxyType >
class Stats::DataWrapVec< Derived, InfoProxyType >
class Stats::DataWrapVec2d< Derived, InfoProxyType >
class Stats::StatStor
Templatized storage and interface for a simple scalar stat.
struct Stats::StatStor::Params
class Stats::AvgStor
Templatized storage and interface to a per-tick average stat.
struct Stats::AvgStor::Params
class Stats::ScalarBase< Derived, Stor >
Implementation of a scalar stat.
class Stats::ProxyInfo
class Stats::ValueProxy< T >
class Stats::FunctorProxy< T >
class Stats::MethodProxy< T, V >
A proxy similar to the FunctorProxy, but allows calling a method of a bound object, instead of a global free-standing function.
class Stats::ValueBase< Derived >
class Stats::ScalarProxy< Stat >
A proxy class to access the stat at a given index in a VectorBase stat.
class Stats::VectorBase< Derived, Stor >
Implementation of a vector of stats.
class Stats::VectorProxy< Stat >
class Stats::Vector2dBase< Derived, Stor >
struct Stats::DistParams
The parameters for a distribution stat.
class Stats::DistStor
Templatized storage and interface for a distribution stat.
struct Stats::DistStor::Params
The parameters for a distribution stat.
class Stats::HistStor
Templatized storage and interface for a histogram stat.
struct Stats::HistStor::Params
The parameters for a distribution stat.
class Stats::SampleStor
Templatized storage and interface for a distribution that calculates mean and variance.
struct Stats::SampleStor::Params
class Stats::AvgSampleStor
Templatized storage for distribution that calculates per tick mean and variance.
struct Stats::AvgSampleStor::Params
class Stats::DistBase< Derived, Stor >
Implementation of a distribution stat.
class Stats::DistProxy< Stat >
class Stats::VectorDistBase< Derived, Stor >
class Stats::DistProxy< Stat >
class Stats::Node
Base class for formula statistic node.
class Stats::ScalarStatNode
class Stats::ScalarProxyNode< Stat >
class Stats::VectorStatNode
class Stats::ConstNode< T >
class Stats::ConstVectorNode< T >
struct Stats::OpString< Op >
struct Stats::OpString< std::plus< Result > >
struct Stats::OpString< std::minus< Result > >
struct Stats::OpString< std::multiplies< Result > >
struct Stats::OpString< std::divides< Result > >
struct Stats::OpString< std::modulus< Result > >
struct Stats::OpString< std::negate< Result > >
class Stats::UnaryNode< Op >
class Stats::BinaryNode< Op >
class Stats::SumNode< Op >
class Stats::Scalar
This is a simple scalar statistic, like a counter.
class Stats::Average
A stat that calculates the per tick average of a value.
class Stats::Value
class Stats::Vector
A vector of scalar stats.
class Stats::AverageVector
A vector of Average stats.
class Stats::Vector2d
A 2-Dimensional vecto of scalar stats.
class Stats::Distribution
A simple distribution stat.
class Stats::Histogram
A simple histogram stat.
class Stats::StandardDeviation
Calculates the mean and variance of all the samples.
class Stats::AverageDeviation
Calculates the per tick mean and variance of the samples.
class Stats::VectorDistribution
A vector of distributions.
class Stats::VectorStandardDeviation
This is a vector of StandardDeviation stats.
class Stats::VectorAverageDeviation
This is a vector of AverageDeviation stats.
class Stats::FormulaInfoProxy< Stat >
class Stats::SparseHistInfoProxy< Stat >
class Stats::SparseHistBase< Derived, Stor >
Implementation of a sparse histogram stat.
class Stats::SparseHistStor
Templatized storage and interface for a sparse histogram stat.
struct Stats::SparseHistStor::Params
The parameters for a sparse histogram stat.
class Stats::SparseHistogram
class Stats::Formula
A formula for statistics that is calculated when printed.
class Stats::FormulaNode
class Stats::Temp
Helper class to construct formula node trees.
Namespaces
Stats
Typedefs
typedef std::shared_ptr< Node > Stats::NodePtr
Shared pointer to a function Node.
typedef void(* Stats::Handler) ()
Register reset and dump handlers.
typedef std::map< const void *, Info * > Stats::MapType
typedef std::map< std::string, Info * > Stats::NameMapType
Functions
Tick curTick ()
The current simulated tick.
Temp Stats::operator+ (Temp l, Temp r)
Temp Stats::operator- (Temp l, Temp r)
Temp Stats::operator* (Temp l, Temp r)
Temp Stats::operator/ (Temp l, Temp r)
Temp Stats::operator- (Temp l)
template<typename T >
Temp Stats::constant (T val)
template<typename T >
Temp Stats::constantVector (T val)
Temp Stats::sum (Temp val)
void Stats::dump ()
Dump all statistics data to the registered outputs.
void Stats::reset ()
void Stats::enable ()
bool Stats::enabled ()
void Stats::registerHandlers (Handler reset_handler, Handler dump_handler)
void Stats::registerResetCallback (Callback *cb)
Register a callback that should be called whenever statistics are reset.
void Stats::registerDumpCallback (Callback *cb)
Register a callback that should be called whenever statistics are about to be dumped.
void Stats::processResetQueue ()
Process all the callbacks in the reset callbacks queue.
void Stats::processDumpQueue ()
Process all the callbacks in the dump callbacks queue.
list< Info * > & Stats::statsList ()
MapType & Stats::statsMap ()
NameMapType & Stats::nameMap ()
bool Stats::validateStatName (const std::string &name)
void debugDumpStats ()
Detailed Description
Declaration of Statistics objects.
Definition in file statistics.hh.
Function Documentation
curTick()
Tick curTick () inline
The current simulated tick.
The current simulated tick.
Definition at line 47 of file core.hh.
Referenced by SBOOEPrefetcher::access(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), FlashDevice::accessDevice(), SimpleCache::accessTiming(), FlashDevice::actionComplete(), O3ThreadContext< Impl >::activate(), SimpleThread::activate(), FullO3CPU< O3CPUImpl >::activateContext(), ElasticTrace::addDepTraceRecord(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), CacheMemory::allocate(), BaseTrafficGen::allocateWaitingRespSlot(), DefaultFetch< Impl >::buildInst(), BaseXBar::calcPacketTiming(), DistIface::RecvScheduler::calcReceiveTick(), BaseCache::calculateAccessLatency(), SBOOEPrefetcher::calculatePrefetch(), NetworkInterface::calculateVC(), VncInput::captureFrameBuffer(), Sinic::Device::changeConfig(), AlphaISA::Kernel::Statistics::changeMode(), TraceCPU::checkAndSchedExitEvent(), FlashDevice::checkDrain(), DRAMCtrl::Rank::checkDrainDone(), IGbE::chkInterrupt(), DRAMCtrl::chooseNextFRFCFS(), BaseCache::CacheSlavePort::clearBlocked(), UFSHostDevice::clearInterrupt(), Intel8254Timer::Counter::CounterEvent::clocksLeft(), Minor::Execute::commit(), DefaultCommit< Impl >::commitHead(), MemTest::completeRequest(), LSQUnit< Impl >::completeStore(), SMMUTranslationProcess::completeTransaction(), ClockedObject::computeStats(), DRAMCtrl::Rank::computeStats(), BaseTags::computeStatsVisitor(), Sinic::Base::cpuInterrupt(), NSGigE::cpuInterrupt(), Sinic::Base::cpuIntrPost(), NSGigE::cpuIntrPost(), IGbE::cpuPostInt(), CPUProgressEvent::CPUProgressEvent(), X86ISA::GpuTLB::curCycle(), Shader::curCycle(), TLBCoalescer::curCycle(), TraceCPU::dcacheRetryRecvd(), DefaultDecode< Impl >::decodeInsts(), PacketQueue::deferredPacketReady(), MSHR::delay(), BOPPrefetcher::delayQueueEventWrapper(), MessageBuffer::dequeue(), SimpleMemory::dequeue(), Sinic::Device::devIntrChangeMask(), NSGigE::devIntrChangeMask(), Sinic::Device::devIntrPost(), NSGigE::devIntrPost(), Shader::dispatch_workgroups(), DefaultIEW< Impl >::dispatchInsts(), Pl111::dmaDone(), SMMUProcess::doBroadcastSignal(), IdeDisk::doDmaDataRead(), IdeDisk::doDmaDataWrite(), IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), IdeDisk::doDmaWrite(), DRAMCtrl::doDRAMAccess(), ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), SMMUProcess::doSemaphoreUp(), doSimLoop(), ThermalModel::doStep(), StoreTrace::downgrade(), DRAMCtrl::drain(), PCEventQueue::dump(), Trace::TarmacParserRecord::dump(), EventQueue::dump(), CheckerCPU::dumpAndExit(), EtherDump::dumpPacket(), PseudoInst::dumpresetstats(), PseudoInst::dumpstats(), LdsState::earliestReturnTime(), EtherSwitch::Interface::enqueue(), TraceGen::enter(), Event::Event(), Shader::exec(), TraceCPU::ElasticDataGen::execute(), exitSimLoop(), DefaultFetch< Impl >::fetch(), IGbE::DescCache< iGbReg::RxDesc >::fetchDescriptors(), IGbE::DescCache< iGbReg::RxDesc >::fetchDescriptors1(), ElasticTrace::fetchReqTrace(), GoodbyeObject::fillBuffer(), UFSHostDevice::finalUTP(), Minor::LSQ::SplitDataRequest::finish(), DefaultFetch< Impl >::finishTranslation(), ArmISA::flattenIntRegModeIndex(), DRAMCtrl::Rank::flushCmdList(), getElapsedTimeMicro(), getElapsedTimeNano(), Queue< WriteQueueEntry >::getNext(), BaseCache::getNextQueueEntry(), MultiPrefetcher::getPacket(), MipsISA::haltThread(), MipsISA::handleLockedWrite(), RiscvISA::handleLockedWrite(), Checker< O3CPUImpl >::handlePendingInt(), MemTraceProbe::handleRequest(), DmaPort::handleResp(), SimpleCache::handleResponse(), MSHR::handleSnoop(), X86ISA::GpuTLB::handleTranslationReturn(), RubyPort::MemSlavePort::hitCallback(), RubyDirectedTester::hitCallback(), CPA::hwWe(), TraceCPU::icacheRetryRecvd(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), QueuedPrefetcher::insert(), CacheBlk::insert(), BaseTags::insertBlock(), BOPPrefetcher::insertIntoDelayQueue(), GPUCoalescer::insertRequest(), Minor::Execute::issue(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), X86ISA::GpuTLB::issueTLBLookup(), EtherSwitch::Interface::learnSenderAddr(), BaseRemoteGDB::listen(), QoS::MemCtrl::logRequest(), QoS::MemCtrl::logResponse(), EtherSwitch::Interface::lookupDestPort(), UFSHostDevice::LUNSignal(), PseudoInst::m5checkpoint(), PseudoInst::m5exit(), PseudoInst::m5fail(), SMMUTranslationProcess::main(), VIPERCoalescer::makeRequest(), GPUCoalescer::makeRequest(), MemTest::MemTest(), RubySystem::memWriteback(), DRAMCtrl::minBankPrep(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::nb_transport_bw(), TraceCPU::FixedRetryGen::nextExecute(), RandomGen::nextPacketTick(), LinearGen::nextPacketTick(), TraceGen::nextPacketTick(), SBOOEPrefetcher::notifyFill(), GpuDispatcher::notifyWgCompl(), BaseXBar::Layer< MasterPort, SlavePort >::occupyLayer(), Linux::openSpecialFile(), DistIface::packetOut(), ArmISA::TableWalker::pendingChange(), DVFSHandler::perfLevel(), Stats::periodicStatDump(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), Minor::Decode::popInput(), DistIface::RecvScheduler::popPacket(), IGbE::postInterrupt(), BaseSimpleCPU::preExecute(), Stats::AvgStor::prepare(), Stats::AvgSampleStor::prepare(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::print(), Trace::TarmacTracerRecord::TraceInstEntry::print(), Trace::TarmacTracerRecordV8::TraceRegEntryV8::print(), Trace::TarmacTracerRecord::TraceRegEntry::print(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::print(), Trace::TarmacTracerRecord::TraceMemEntry::print(), Trace::TarmacParserRecord::printMismatchHeader(), MC146818::RTCEvent::process(), GlobalSimLoopExitEvent::process(), Stats::SimTicksReset::process(), MC146818::RTCTickEvent::process(), AnnotateDumpCallback::process(), CPUProgressEvent::process(), DumpStatsPCEvent::process(), GlobalSyncEvent::process(), Stats::StatEvent::process(), DistIface::SyncEvent::process(), DRAMCtrl::Rank::processActivateEvent(), HelloObject::processEvent(), Uart8250::processIntrEvent(), QoS::MemSinkCtrl::processNextReqEvent(), DRAMCtrl::processNextReqEvent(), DRAMCtrl::Rank::processPowerEvent(), DRAMCtrl::Rank::processPrechargeEvent(), TLBCoalescer::processProbeTLBEvent(), BaseCPU::processProfileEvent(), DRAMCtrl::Rank::processRefreshEvent(), DRAMCtrl::processRespondEvent(), Shader::processTick(), EtherLink::Link::processTxQueue(), DRAMCtrl::Rank::processWakeUpEvent(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::TableWalker::processWalkWrapper(), MSHR::promoteDeferredTargets(), MemChecker::ByteTracker::pruneTransactions(), EtherSwitch::Interface::PortFifo::push(), ClockedObject::pwrState(), ClockedObject::pwrStateWeights(), pybind_init_core(), QoS::MemCtrl::qosSchedule(), PseudoInst::quiesceNs(), PL031::read(), Sp804::Timer::read(), A9GlobalTimer::Timer::read(), CpuLocalTimer::Timer::read(), RealViewCtrl::read(), LSQUnit< Impl >::read(), UFSHostDevice::readCallback(), DRAMSim2::readComplete(), Pl111::readFramebuffer(), CheckerCPU::readMem(), X86ISA::Interrupts::readReg(), ArmSemihosting::readString(), ElasticTrace::recordExecTick(), Sequencer::recordMissLatency(), GPUCoalescer::recordMissLatency(), ElasticTrace::recordToCommTick(), BaseCache::recvAtomic(), TLBCoalescer::MemSidePort::recvReqRetry(), StubSlavePort::recvTimingReq(), SimpleTimingPort::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), MemDelay::SlavePort::recvTimingReq(), TLBCoalescer::CpuSidePort::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SimpleMemory::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CommMonitor::recvTimingReq(), DRAMCtrl::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), MemDelay::MasterPort::recvTimingResp(), BaseTrafficGen::recvTimingResp(), RubyPort::PioMasterPort::recvTimingResp(), NoncoherentXBar::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), X86ISA::GpuTLB::MemSidePort::recvTimingResp(), CoherentXBar::recvTimingResp(), ComputeUnit::DataPort::recvTimingResp(), BaseCache::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), MemDelay::SlavePort::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), ElasticTrace::regEtraceListeners(), ElasticTrace::regProbeListeners(), Request::Request(), UFSHostDevice::requestHandler(), BankedArray::reserve(), BIPRP::reset(), WeightedLRUPolicy::reset(), LRURP::reset(), FIFORP::reset(), MRURP::reset(), Stats::AvgStor::reset(), Clocked::resetClock(), PseudoInst::resetstats(), DRAMCtrl::Rank::resetStats(), DRAMCtrl::DRAMStats::resetStats(), Sp804::Timer::restartCounter(), A9GlobalTimer::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), CpuLocalTimer::Timer::restartWatchdogCounter(), MipsISA::restoreThread(), Stats::AvgStor::result(), BasePixelPump::PixelEvent::resume(), DistIface::RecvScheduler::resumeRecvTicks(), SMMUTranslationProcess::resumeTransaction(), PL031::resyncMatch(), EtherTapBase::retransmit(), BaseTrafficGen::retryReq(), PseudoInst::rpns(), StatTest::run(), DistIface::SyncNode::run(), DistIface::SyncSwitch::run(), Sinic::Device::rxKick(), NSGigE::rxKick(), CommMonitor::samplePeriodic(), TraceCPU::schedIcacheNext(), schedRelBreak(), PacketQueue::schedSendEvent(), PacketQueue::schedSendTiming(), GpuDispatcher::scheduleDispatch(), MC146818::RTCEvent::scheduleIntr(), Uart8250::scheduleIntr(), DRAMCtrl::Rank::schedulePowerEvent(), InstructionQueue< Impl >::scheduleReadyInsts(), BaseTrafficGen::scheduleUpdate(), DRAMCtrl::Rank::scheduleWakeUpEvent(), ArmSemihosting::semiExit(), EtherBus::send(), X86ISA::IntMasterPort< X86ISA::I82094AA >::sendMessage(), ComputeUnit::sendRequest(), DRAMSim2::sendResponse(), EtherTapBase::sendSimulated(), ComputeUnit::sendSyncRequest(), Globals::serialize(), MC146818::serialize(), Intel8254Timer::Counter::serialize(), Sinic::Device::serialize(), NSGigE::serialize(), Stats::AvgStor::set(), Request::setAccessLatency(), CheckpointIn::setDir(), SystemCounter::setFreq(), Pl011::setInterrupts(), CacheMemory::setMRU(), X86ISA::Interrupts::setReg(), Intel8254Timer::Counter::CounterEvent::setTo(), Request::setTranslateLatency(), Request::setVirt(), Event::setWhen(), simulate(), SMMUTranslationProcess::smmuTranslation(), DefaultRename< Impl >::sortInsts(), DistIface::SyncEvent::start(), IdeDisk::startDma(), sc_gem5::Kernel::startup(), CommMonitor::startup(), BaseKvmCPU::startup(), RubySystem::startup(), MC146818::startup(), ThermalModel::startup(), Intel8254Timer::Counter::startup(), DRAMSim2::startup(), BaseCPU::startup(), DRAMCtrl::Rank::startup(), DRAMCtrl::startup(), Stats::statElapsedTicks(), Stats::statFinalTick(), StoreTrace::store(), O3ThreadContext< Impl >::suspend(), SimpleThread::suspend(), BasePixelPump::PixelEvent::suspend(), AlphaISA::Kernel::Statistics::swpipl(), takeCheckpoint(), BaseCPU::takeOverFrom(), CacheMemory::testCacheAccess(), GarnetSyntheticTraffic::tick(), AtomicSimpleCPU::tick(), IGbE::tick(), DRAMSim2::tick(), BaseKvmCPU::tick(), timesFunc(), Root::timeSync(), Root::timeSyncEnable(), WeightedLRUPolicy::touch(), LRURP::touch(), MRURP::touch(), BaseCPU::traceFunctionsInternal(), Trace::InstPBTrace::traceInst(), BaseTrafficGen::transition(), QueuedPrefetcher::translationComplete(), X86ISA::GpuTLB::translationReturn(), EtherLink::Link::transmit(), DistEtherLink::TxLink::transmit(), EtherSwitch::Interface::transmit(), NSGigE::transmit(), BankedArray::tryAccess(), CacheMemory::tryCacheAccess(), SerialLink::SerialLinkSlavePort::trySendTiming(), Bridge::BridgeSlavePort::trySendTiming(), SerialLink::SerialLinkMasterPort::trySendTiming(), Bridge::BridgeMasterPort::trySendTiming(), EtherLink::Link::txDone(), Sinic::Device::txKick(), NSGigE::txKick(), Sinic::Device::unserialize(), NSGigE::unserialize(), Clocked::update(), BaseTrafficGen::update(), ElasticTrace::updateCommitOrderDep(), ArchTimer::updateCounter(), Stats::updateEvents(), DefaultIEW< Impl >::updateExeInstStats(), VGic::updateIntState(), GicV2::updateIntState(), ElasticTrace::updateIssueOrderDep(), X86ISA::GpuTLB::updatePageFootprint(), TLBCoalescer::updatePhysAddresses(), DRAMCtrl::Rank::updatePowerStats(), CommMonitor::MonitorStats::updateReqStats(), Checker< O3CPUImpl >::validateExecution(), Checker< O3CPUImpl >::validateInst(), Checker< O3CPUImpl >::validateState(), SystemCounter::value(), Checker< O3CPUImpl >::verify(), HDLcd::virtRefresh(), RubyDirectedTester::wakeup(), GPUCoalescer::wakeup(), RubyTester::wakeup(), ArmISA::TableWalker::walk(), System::workItemBegin(), System::workItemEnd(), Uart8250::write(), AlphaBackdoor::write(), PL031::write(), EnergyCtrl::write(), GpuDispatcher::write(), UFSHostDevice::write(), IGbE::DescCache< iGbReg::RxDesc >::writeback(), IGbE::DescCache< iGbReg::RxDesc >::writeback1(), LSQUnit< Impl >::writebackStores(), DRAMSim2::writeComplete(), MC146818::writeData(), UFSHostDevice::writeDevice(), CheckerCPU::writeMem(), and MipsISA::yieldThread().
debugDumpStats()
void debugDumpStats ()
Definition at line 587 of file statistics.cc.
References Stats::dump().