gem5: CircularQueue< T >::iterator Struct Reference
CircularQueue< T >::iterator Struct Reference
Iterator to the circular queue.
#include <circular_queue.hh>
Public Types
using value_type = T
Iterator Traits.
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using iterator_category = std::random_access_iterator_tag
Public Member Functions
iterator (CircularQueue *cq, uint32_t idx, uint32_t round)
iterator ()
Trait reference type iterator satisfies OutputIterator, therefore reference must be T&.
iterator (const iterator &it)
iterator & operator= (const iterator &it)
~iterator ()
bool dereferenceable () const
Test dereferenceability.
bool operator== (const iterator &that) const
InputIterator.
bool operator!= (const iterator &that)
Inequality operator.
reference operator* ()
Dereference operator.
const_reference operator* () const
pointer operator-> ()
Dereference operator.
const_pointer operator-> () const
iterator & operator++ ()
Pre-increment operator.
iterator operator++ (int)
Post-increment operator.
iterator & operator-- ()
Pre-decrement operator.
iterator operator-- (int)
Post-decrement operator.
iterator & operator+= (const difference_type &t)
RandomAccessIterator requirements.
iterator & operator-= (const difference_type &t)
iterator operator+ (const difference_type &t)
Addition operator.
iterator operator- (const difference_type &t)
Substraction operator.
difference_type operator- (const iterator &that)
Difference operator.
template<typename Idx >
std::enable_if< std::is_integral< Idx >::value, reference >::type operator[] (const Idx &index)
Index operator.
bool operator< (const iterator &that) const
Comparisons.
bool operator> (const iterator &that) const
bool operator>= (const iterator &that) const
bool operator<= (const iterator &that) const
size_t idx () const
OutputIterator has no extra requirements.
Public Attributes
CircularQueue * _cq
uint32_t _idx
uint32_t _round
Private Member Functions
bool decrementable () const
ForwardIterator The multipass guarantee is provided by the reliance on _idx.
Friends
iterator operator+ (const difference_type &t, iterator &it)
iterator operator- (const difference_type &t, iterator &it)
Detailed Description
template<typename T>
struct CircularQueue< T >::iterator
Iterator to the circular queue.
iterator implementation to provide the circular-ness that the standard std::vector<T>::iterator does not implement. Iterators to a queue are represented by a pair of a character and the round counter. For the character, '*' denotes the element pointed to by the iterator if it is valid. 'x' denotes the element pointed to by the iterator when it is BTB or PTE. E.g.:
Iterator to the head of a queue of capacity 4 with 2 elems. (4,F,0,1,R): |[(*,R)|o]|-|-| (4,F,3,0): |o]|-|-|[(*,R)|
Iterator to the tail of a queue of capacity 4 with 2 elems. (4,F,0,1,R): |[o|(*,R)]|-|-| (4,F,3,0): |(*,R)]|-|-|[o|
Iterator to the end of a queue of capacity 4 with 2 elems. (4,F,0,1,R): |[o|o]|(x,R)|-| (4,F,3,0): |o]|(x,R)|-|[o|
Definition at line 153 of file circular_queue.hh.
Member Typedef Documentation
const_pointer
template<typename T> using CircularQueue< T >::iterator::const_pointer = const value_type*
Definition at line 168 of file circular_queue.hh.
const_reference
template<typename T> using CircularQueue< T >::iterator::const_reference = const value_type&
Definition at line 166 of file circular_queue.hh.
difference_type
template<typename T> using CircularQueue< T >::iterator::difference_type = std::ptrdiff_t
Definition at line 164 of file circular_queue.hh.
iterator_category
template<typename T> using CircularQueue< T >::iterator::iterator_category = std::random_access_iterator_tag
Definition at line 169 of file circular_queue.hh.
pointer
template<typename T> using CircularQueue< T >::iterator::pointer = value_type*
Definition at line 167 of file circular_queue.hh.
reference
template<typename T> using CircularQueue< T >::iterator::reference = value_type&
Definition at line 165 of file circular_queue.hh.
value_type
template<typename T> using CircularQueue< T >::iterator::value_type = T
Iterator Traits.
Definition at line 163 of file circular_queue.hh.
Constructor & Destructor Documentation
iterator() [1/3]
template<typename T> CircularQueue< T >::iterator::iterator (CircularQueue * cq, uint32_t idx, uint32_t round) inline
Definition at line 159 of file circular_queue.hh.
iterator() [2/3]
template<typename T> CircularQueue< T >::iterator::iterator () inline
Trait reference type iterator satisfies OutputIterator, therefore reference must be T&.
Definition at line 177 of file circular_queue.hh.
Referenced by CircularQueue< char >::begin(), CircularQueue< char >::end(), and CircularQueue< char >::getIterator().
iterator() [3/3]
template<typename T> CircularQueue< T >::iterator::iterator (const iterator & it) inline
Definition at line 179 of file circular_queue.hh.
~iterator()
template<typename T> CircularQueue< T >::iterator::~iterator () inline
Definition at line 191 of file circular_queue.hh.
Member Function Documentation
decrementable()
template<typename T> bool CircularQueue< T >::iterator::decrementable () const inline private
ForwardIterator The multipass guarantee is provided by the reliance on _idx.
BidirectionalIterator requirements. Test decrementability. An iterator to a non-null circular queue is not-decrementable if it is pointing to the head element, unless the queue is full and we are talking about the past-the-end iterator. In that case, the iterator round equals the cq round unless the head is at the zero position and the round is one more than the cq round.
Definition at line 294 of file circular_queue.hh.
References CircularQueue< T >::_round, CircularQueue< T >::empty(), and CircularQueue< T >::head().
Referenced by CircularQueue< T >::iterator::operator--().
dereferenceable()
template<typename T> bool CircularQueue< T >::iterator::dereferenceable () const inline
Test dereferenceability.
An iterator is dereferenceable if it is pointing to a non-null circular queue, it is not the past-the-end iterator and the index is a valid index to that queue. PTE test is required to distinguish between:
An iterator to the first element of a full queue (4,F,1,0): |o]|[*|o|o|
The end() iterator of a full queue (4,F,1,0): |o]|x[o|o|o| Sometimes, though, users will get the PTE iterator and expect it to work after growing the buffer on the tail, so we have to check if the iterator is still PTE.
Definition at line 207 of file circular_queue.hh.
References CircularQueue< T >::isValidIdx().
Referenced by LSQUnit< Impl >::willWB(), and LSQUnit< Impl >::writebackStores().
idx()
template<typename T> size_t CircularQueue< T >::iterator::idx () const inline
OutputIterator has no extra requirements.
Definition at line 407 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx.
Referenced by CircularQueue< char >::advance_tail(), LSQUnit< Impl >::completeStore(), CircularQueue< char >::isValidIdx(), and LSQUnit< Impl >::writebackStores().
operator!=()
template<typename T> bool CircularQueue< T >::iterator::operator!= (const iterator & that) inline
Inequality operator.
Conversely, two iterators are different if they both point to different circular queues or they point to different elements.
Definition at line 230 of file circular_queue.hh.
operator*() [1/2]
template<typename T> reference CircularQueue< T >::iterator::operator* () inline
Dereference operator.
Definition at line 236 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx.
operator*() [2/2]
template<typename T> const_reference CircularQueue< T >::iterator::operator* () const inline
Definition at line 242 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx.
operator+()
template<typename T> iterator CircularQueue< T >::iterator::operator+ (const difference_type & t) inline
Addition operator.
Definition at line 341 of file circular_queue.hh.
References ArmISA::t.
operator++() [1/2]
template<typename T> iterator& CircularQueue< T >::iterator::operator++ () inline
Pre-increment operator.
Definition at line 262 of file circular_queue.hh.
References CircularQueue< T >::iterator::_round, and CircularQueue< T >::increase().
operator++() [2/2]
template<typename T> iterator CircularQueue< T >::iterator::operator++ (int) inline
Post-increment operator.
Definition at line 273 of file circular_queue.hh.
References ArmISA::t.
operator+=()
template<typename T> iterator& CircularQueue< T >::iterator::operator+= (const difference_type & t) inline
RandomAccessIterator requirements.
Definition at line 318 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx, CircularQueue< T >::capacity(), and CircularQueue< T >::moduloAdd().
operator-() [1/2]
template<typename T> iterator CircularQueue< T >::iterator::operator- (const difference_type & t) inline
Substraction operator.
Definition at line 354 of file circular_queue.hh.
References ArmISA::t.
operator-() [2/2]
template<typename T> difference_type CircularQueue< T >::iterator::operator- (const iterator & that) inline
Difference operator.
that + ret == this
Definition at line 369 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx, CircularQueue< T >::iterator::_round, CircularQueue< T >::capacity(), CircularQueue< T >::sub(), and type.
operator--() [1/2]
template<typename T> iterator& CircularQueue< T >::iterator::operator-- () inline
Pre-decrement operator.
Definition at line 304 of file circular_queue.hh.
References CircularQueue< T >::iterator::_round, CircularQueue< T >::decrease(), and CircularQueue< T >::iterator::decrementable().
operator--() [2/2]
template<typename T> iterator CircularQueue< T >::iterator::operator-- (int) inline
Post-decrement operator.
Definition at line 315 of file circular_queue.hh.
References ArmISA::t.
operator-=()
template<typename T> iterator& CircularQueue< T >::iterator::operator-= (const difference_type & t) inline
Definition at line 326 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx, CircularQueue< T >::capacity(), CircularQueue< T >::moduloSub(), and ArmISA::t.
operator->() [1/2]
template<typename T> pointer CircularQueue< T >::iterator::operator-> () inline
Dereference operator.
Rely on operator* to check for dereferenceability.
Definition at line 251 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx.
operator->() [2/2]
template<typename T> const_pointer CircularQueue< T >::iterator::operator-> () const inline
Definition at line 256 of file circular_queue.hh.
References CircularQueue< T >::iterator::_idx.
operator<()
template<typename T> bool CircularQueue< T >::iterator::operator< (const iterator & that) const inline
Comparisons.
Definition at line 389 of file circular_queue.hh.
References CircularQueue< T >::iterator::_cq, CircularQueue< T >::iterator::_idx, and CircularQueue< T >::iterator::_round.
operator<=()
template<typename T> bool CircularQueue< T >::iterator::operator<= (const iterator & that) const inline
Definition at line 403 of file circular_queue.hh.
operator=()
template<typename T> iterator& CircularQueue< T >::iterator::operator= (const iterator & it) inline
Definition at line 183 of file circular_queue.hh.
References CircularQueue< T >::iterator::_cq, CircularQueue< T >::iterator::_idx, and CircularQueue< T >::iterator::_round.
operator==()
template<typename T> bool CircularQueue< T >::iterator::operator== (const iterator & that) const inline
InputIterator.
Equality operator. Two iterators must point to the same, possibly null, circular queue and the same element on it, including PTE, to be equal. In case the clients the the PTE iterator and then grow on the back and expect it to work, we have to check if the PTE is still PTE
Definition at line 220 of file circular_queue.hh.
References CircularQueue< T >::iterator::_cq, CircularQueue< T >::iterator::_idx, and CircularQueue< T >::iterator::_round.
operator>()
template<typename T> bool CircularQueue< T >::iterator::operator> (const iterator & that) const inline
Definition at line 397 of file circular_queue.hh.
operator>=()
template<typename T> bool CircularQueue< T >::iterator::operator>= (const iterator & that) const inline
Definition at line 400 of file circular_queue.hh.
operator[]()
template<typename T> template<typename Idx > std::enable_if<std::is_integral<Idx>::value,reference>::type CircularQueue< T >::iterator::operator[] (const Idx & index) inline
Index operator.
The use of * tests for dereferenceability.
Definition at line 385 of file circular_queue.hh.
References MipsISA::index.
Friends And Related Function Documentation
operator+
template<typename T> iterator operator+ (const difference_type & t, iterator & it) friend
Definition at line 347 of file circular_queue.hh.
operator-
template<typename T> iterator operator- (const difference_type & t, iterator & it) friend
Definition at line 360 of file circular_queue.hh.
Member Data Documentation
_cq
template<typename T> CircularQueue* CircularQueue< T >::iterator::_cq
Definition at line 154 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::operator<(), CircularQueue< T >::iterator::operator=(), and CircularQueue< T >::iterator::operator==().
_idx
template<typename T> uint32_t CircularQueue< T >::iterator::_idx
Definition at line 155 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::idx(), CircularQueue< T >::iterator::operator*(), CircularQueue< T >::iterator::operator+=(), CircularQueue< T >::iterator::operator-(), CircularQueue< T >::iterator::operator-=(), CircularQueue< T >::iterator::operator->(), CircularQueue< T >::iterator::operator<(), CircularQueue< T >::iterator::operator=(), and CircularQueue< T >::iterator::operator==().
_round
template<typename T> uint32_t CircularQueue< T >::iterator::_round
Definition at line 156 of file circular_queue.hh.
Referenced by CircularQueue< char >::advance_tail(), CircularQueue< char >::end(), CircularQueue< char >::getIterator(), CircularQueue< T >::iterator::operator++(), CircularQueue< T >::iterator::operator-(), CircularQueue< T >::iterator::operator--(), CircularQueue< T >::iterator::operator<(), CircularQueue< T >::iterator::operator=(), CircularQueue< T >::iterator::operator==(), and CircularQueue< char >::pop_back().
The documentation for this struct was generated from the following file:
base/circular_queue.hh