gem5: Net::IpWithPort Struct Reference
Net::IpWithPort Struct Reference
#include <inet.hh>
Public Member Functions
IpWithPort ()
IpWithPort (const uint32_t __ip, const uint16_t __port)
uint8_t port () const
std::string string () const
Public Member Functions inherited from Net::IpAddress
IpAddress ()
IpAddress (const uint32_t __ip)
uint32_t ip () const
std::string string () const
Protected Attributes
uint16_t _port
Protected Attributes inherited from Net::IpAddress
uint32_t _ip
Detailed Description
Definition at line 232 of file inet.hh.
Constructor & Destructor Documentation
IpWithPort() [1/2]
Net::IpWithPort::IpWithPort () inline
Definition at line 238 of file inet.hh.
IpWithPort() [2/2]
Net::IpWithPort::IpWithPort (const uint32_t __ip, const uint16_t __port) inline
Definition at line 240 of file inet.hh.
Member Function Documentation
port()
uint8_t Net::IpWithPort::port () const inline
Definition at line 244 of file inet.hh.
References Net::operator<<(), Net::operator==(), and Net::EthAddr::string().
Referenced by Net::operator==().
string()
string Net::IpWithPort::string () const
Definition at line 187 of file inet.cc.
Member Data Documentation
_port
uint16_t Net::IpWithPort::_port protected
Definition at line 235 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc