gem5: V8PageTableOps16k Struct Reference
V8PageTableOps16k Struct Reference
#include <smmu_v3_ptops.hh>
Public Member Functions
bool isValid (pte_t pte, unsigned level) const override
bool isLeaf (pte_t pte, unsigned level) const override
bool isWritable (pte_t pte, unsigned level, bool stage2) const override
Addr nextLevelPointer (pte_t pte, unsigned level) const override
Addr index (Addr va, unsigned level) const override
Addr pageMask (pte_t pte, unsigned level) const override
Addr walkMask (unsigned level) const override
unsigned firstLevel (uint8_t tsz) const override
unsigned lastLevel () const override
Additional Inherited Members
Public Types inherited from PageTableOps
typedef int64_t pte_t
Detailed Description
Definition at line 88 of file smmu_v3_ptops.hh.
Member Function Documentation
firstLevel()
unsigned V8PageTableOps16k::firstLevel (uint8_t tsz) const override virtual
Implements PageTableOps.
Definition at line 319 of file smmu_v3_ptops.cc.
References panic.
index()
Addr V8PageTableOps16k::index (Addr va, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 281 of file smmu_v3_ptops.cc.
References bits(), and panic.
isLeaf()
bool V8PageTableOps16k::isLeaf (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 247 of file smmu_v3_ptops.cc.
References panic.
isValid()
bool V8PageTableOps16k::isValid (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 235 of file smmu_v3_ptops.cc.
References panic.
isWritable()
bool V8PageTableOps16k::isWritable (pte_t pte, unsigned level, bool stage2) const override virtual
Implements PageTableOps.
Definition at line 259 of file smmu_v3_ptops.cc.
References bits().
lastLevel()
unsigned V8PageTableOps16k::lastLevel () const override virtual
Implements PageTableOps.
Definition at line 330 of file smmu_v3_ptops.cc.
nextLevelPointer()
Addr V8PageTableOps16k::nextLevelPointer (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 265 of file smmu_v3_ptops.cc.
References V7LPageTableOps::isLeaf(), mbits(), and panic.
pageMask()
Addr V8PageTableOps16k::pageMask (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 293 of file smmu_v3_ptops.cc.
References bits(), ArmISA::mask, and panic.
walkMask()
Addr V8PageTableOps16k::walkMask (unsigned level) const override virtual
Implements PageTableOps.
Definition at line 307 of file smmu_v3_ptops.cc.
References ArmISA::mask, and panic.
The documentation for this struct was generated from the following files:
dev/arm/smmu_v3_ptops.hh
dev/arm/smmu_v3_ptops.cc