gem5: AlphaISA::PageTableEntry Struct Reference
AlphaISA::PageTableEntry Struct Reference
#include <pagetable.hh>
Public Member Functions
PageTableEntry (uint64_t e)
operator uint64_t () const
const PageTableEntry & operator= (uint64_t e)
const PageTableEntry & operator= (const PageTableEntry &e)
Addr _pfn () const
Addr _sw () const
int _rsv0 () const
bool _uwe () const
bool _kwe () const
int _rsv1 () const
bool _ure () const
bool _kre () const
bool _nomb () const
int _gh () const
bool _asm_ () const
bool _foe () const
bool _fow () const
bool _for () const
bool valid () const
Addr paddr () const
Public Attributes
uint64_t entry
Detailed Description
Definition at line 64 of file pagetable.hh.
Constructor & Destructor Documentation
PageTableEntry()
AlphaISA::PageTableEntry::PageTableEntry (uint64_t e) inline
Definition at line 66 of file pagetable.hh.
Member Function Documentation
_asm_()
bool AlphaISA::PageTableEntry::_asm_ () const inline
Definition at line 83 of file pagetable.hh.
_foe()
bool AlphaISA::PageTableEntry::_foe () const inline
Definition at line 84 of file pagetable.hh.
_for()
bool AlphaISA::PageTableEntry::_for () const inline
Definition at line 86 of file pagetable.hh.
_fow()
bool AlphaISA::PageTableEntry::_fow () const inline
Definition at line 85 of file pagetable.hh.
_gh()
int AlphaISA::PageTableEntry::_gh () const inline
Definition at line 82 of file pagetable.hh.
_kre()
bool AlphaISA::PageTableEntry::_kre () const inline
Definition at line 80 of file pagetable.hh.
_kwe()
bool AlphaISA::PageTableEntry::_kwe () const inline
Definition at line 77 of file pagetable.hh.
_nomb()
bool AlphaISA::PageTableEntry::_nomb () const inline
Definition at line 81 of file pagetable.hh.
_pfn()
Addr AlphaISA::PageTableEntry::_pfn () const inline
Definition at line 73 of file pagetable.hh.
_rsv0()
int AlphaISA::PageTableEntry::_rsv0 () const inline
Definition at line 75 of file pagetable.hh.
_rsv1()
int AlphaISA::PageTableEntry::_rsv1 () const inline
Definition at line 78 of file pagetable.hh.
_sw()
Addr AlphaISA::PageTableEntry::_sw () const inline
Definition at line 74 of file pagetable.hh.
_ure()
bool AlphaISA::PageTableEntry::_ure () const inline
Definition at line 79 of file pagetable.hh.
_uwe()
bool AlphaISA::PageTableEntry::_uwe () const inline
Definition at line 76 of file pagetable.hh.
operator uint64_t()
AlphaISA::PageTableEntry::operator uint64_t () const inline
Definition at line 68 of file pagetable.hh.
operator=() [1/2]
const PageTableEntry& AlphaISA::PageTableEntry::operator= (uint64_t e) inline
Definition at line 69 of file pagetable.hh.
References ArmISA::e.
operator=() [2/2]
const PageTableEntry& AlphaISA::PageTableEntry::operator= (const PageTableEntry & e) inline
Definition at line 70 of file pagetable.hh.
References entry.
paddr()
Addr AlphaISA::PageTableEntry::paddr () const inline
Definition at line 89 of file pagetable.hh.
References AlphaISA::PageShift.
Referenced by AlphaISA::kernel_pte_lookup(), and AlphaISA::vtophys().
valid()
bool AlphaISA::PageTableEntry::valid () const inline
Definition at line 87 of file pagetable.hh.
Referenced by AlphaISA::RemoteGDB::acc(), AlphaISA::kernel_pte_lookup(), and AlphaISA::vtophys().
Member Data Documentation
entry
uint64_t AlphaISA::PageTableEntry::entry
Definition at line 67 of file pagetable.hh.
Referenced by operator=().
The documentation for this struct was generated from the following file:
arch/alpha/pagetable.hh