gem5: Trace::TarmacTracerRecordV8::TraceRegEntryV8 Struct Reference
Trace::TarmacTracerRecordV8::TraceRegEntryV8 Struct Reference
Register entry for v8 records.
#include <tarmac_record_v8.hh>
Public Member Functions
TraceRegEntryV8 (const TarmacContext &tarmCtx, const RegId &reg)
virtual void print (std::ostream &outs, int verbosity=0, const std::string &prefix="") const override
Public Member Functions inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
TraceEntryV8 (std::string _cpuName)
Protected Member Functions
void updateInt (const TarmacContext &tarmCtx, RegIndex regRelIdx) override
void updateMisc (const TarmacContext &tarmCtx, RegIndex regRelIdx) override
void updateVec (const TarmacContext &tarmCtx, RegIndex regRelIdx) override
void updatePred (const TarmacContext &tarmCtx, RegIndex regRelIdx) override
std::string formatReg () const
Returning a string which contains the formatted register value: transformed in hex, 0 padded or/and split in chunks separated by underscores in case of vector register.
Protected Attributes
uint16_t regWidth
Size in bits of arch register.
Protected Attributes inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
std::string cpuName
Detailed Description
Register entry for v8 records.
Definition at line 95 of file tarmac_record_v8.hh.
Constructor & Destructor Documentation
TraceRegEntryV8()
Trace::TarmacTracerRecordV8::TraceRegEntryV8::TraceRegEntryV8 (const TarmacContext & tarmCtx, const RegId & reg)
Definition at line 77 of file tarmac_record_v8.cc.
Member Function Documentation
formatReg()
std::string Trace::TarmacTracerRecordV8::TraceRegEntryV8::formatReg () const protected
Returning a string which contains the formatted register value: transformed in hex, 0 padded or/and split in chunks separated by underscores in case of vector register.
Returns
str formatted string
Definition at line 301 of file tarmac_record_v8.cc.
References csprintf(), and regWidth.
Referenced by print().
print()
void Trace::TarmacTracerRecordV8::TraceRegEntryV8::print (std::ostream & outs, int verbosity = 0, const std::string & prefix = "") const override virtual
Definition at line 284 of file tarmac_record_v8.cc.
References ccprintf(), Trace::TarmacTracerRecordV8::TraceEntryV8::cpuName, curTick(), formatReg(), and Sinic::regValid().
updateInt()
void Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateInt (const TarmacContext & tarmCtx, RegIndex regRelIdx) override protected
Definition at line 87 of file tarmac_record_v8.cc.
References AlphaISA::FramePointerReg, RefCountingPtr< T >::get(), ArmISA::NUM_ARCH_INTREGS, ArmISA::PCReg, Sinic::regValid(), regWidth, AlphaISA::ReturnAddressReg, AlphaISA::StackPointerReg, Trace::TarmacContext::staticInst, sc_dt::to_string(), and Trace::TarmacTracerRecord::TraceRegEntry::updateInt().
updateMisc()
void Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateMisc (const TarmacContext & tarmCtx, RegIndex regRelIdx) override protected
Definition at line 118 of file tarmac_record_v8.cc.
References regWidth, and Trace::TarmacTracerRecord::TraceRegEntry::updateMisc().
updatePred()
void Trace::TarmacTracerRecordV8::TraceRegEntryV8::updatePred (const TarmacContext & tarmCtx, RegIndex regRelIdx) override protected
Definition at line 154 of file tarmac_record_v8.cc.
References ArmISA::i, ThreadContext::readVecPredReg(), Sinic::regValid(), regWidth, Trace::InstRecord::thread, Trace::TarmacContext::thread, and sc_dt::to_string().
updateVec()
void Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateVec (const TarmacContext & tarmCtx, RegIndex regRelIdx) override protected
Definition at line 129 of file tarmac_record_v8.cc.
References VecRegContainer< Sz >::as(), ArmISA::i, ThreadContext::readVecReg(), Sinic::regValid(), regWidth, Trace::InstRecord::thread, Trace::TarmacContext::thread, and sc_dt::to_string().
Member Data Documentation
regWidth
uint16_t Trace::TarmacTracerRecordV8::TraceRegEntryV8::regWidth protected
Size in bits of arch register.
Definition at line 127 of file tarmac_record_v8.hh.
Referenced by formatReg(), updateInt(), updateMisc(), updatePred(), and updateVec().
The documentation for this struct was generated from the following files:
arch/arm/tracers/tarmac_record_v8.hh
arch/arm/tracers/tarmac_record_v8.cc