gem5: V8PageTableOps64k Struct Reference
V8PageTableOps64k Struct Reference
#include <smmu_v3_ptops.hh>
Public Member Functions
bool isValid (pte_t pte, unsigned level) const override
bool isLeaf (pte_t pte, unsigned level) const override
bool isWritable (pte_t pte, unsigned level, bool stage2) const override
Addr nextLevelPointer (pte_t pte, unsigned level) const override
Addr index (Addr va, unsigned level) const override
Addr pageMask (pte_t pte, unsigned level) const override
Addr walkMask (unsigned level) const override
unsigned firstLevel (uint8_t tsz) const override
unsigned lastLevel () const override
Additional Inherited Members
Public Types inherited from PageTableOps
typedef int64_t pte_t
Detailed Description
Definition at line 101 of file smmu_v3_ptops.hh.
Member Function Documentation
firstLevel()
unsigned V8PageTableOps64k::firstLevel (uint8_t tsz) const override virtual
Implements PageTableOps.
Definition at line 412 of file smmu_v3_ptops.cc.
References panic.
index()
Addr V8PageTableOps64k::index (Addr va, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 379 of file smmu_v3_ptops.cc.
References bits(), and panic.
isLeaf()
bool V8PageTableOps64k::isLeaf (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 347 of file smmu_v3_ptops.cc.
References panic.
isValid()
bool V8PageTableOps64k::isValid (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 336 of file smmu_v3_ptops.cc.
References panic.
isWritable()
bool V8PageTableOps64k::isWritable (pte_t pte, unsigned level, bool stage2) const override virtual
Implements PageTableOps.
Definition at line 358 of file smmu_v3_ptops.cc.
References bits().
lastLevel()
unsigned V8PageTableOps64k::lastLevel () const override virtual
Implements PageTableOps.
Definition at line 422 of file smmu_v3_ptops.cc.
nextLevelPointer()
Addr V8PageTableOps64k::nextLevelPointer (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 364 of file smmu_v3_ptops.cc.
References V7LPageTableOps::isLeaf(), mbits(), and panic.
pageMask()
Addr V8PageTableOps64k::pageMask (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 390 of file smmu_v3_ptops.cc.
References bits(), ArmISA::mask, and panic.
walkMask()
Addr V8PageTableOps64k::walkMask (unsigned level) const override virtual
Implements PageTableOps.
Definition at line 401 of file smmu_v3_ptops.cc.
References ArmISA::mask, and panic.
The documentation for this struct was generated from the following files:
dev/arm/smmu_v3_ptops.hh
dev/arm/smmu_v3_ptops.cc