gem5: PacketFifoEntry Struct Reference
PacketFifoEntry Struct Reference
#include <pktfifo.hh>
Public Member Functions
PacketFifoEntry ()
PacketFifoEntry (const PacketFifoEntry &s)
PacketFifoEntry (EthPacketPtr p, uint64_t n)
void clear ()
void serialize (const std::string &base, CheckpointOut &cp) const
void unserialize (const std::string &base, CheckpointIn &cp)
Public Attributes
EthPacketPtr packet
uint64_t number
unsigned slack
int priv
Detailed Description
Definition at line 44 of file pktfifo.hh.
Constructor & Destructor Documentation
PacketFifoEntry() [1/3]
PacketFifoEntry::PacketFifoEntry () inline
Definition at line 51 of file pktfifo.hh.
References clear().
PacketFifoEntry() [2/3]
PacketFifoEntry::PacketFifoEntry (const PacketFifoEntry & s) inline
Definition at line 56 of file pktfifo.hh.
PacketFifoEntry() [3/3]
PacketFifoEntry::PacketFifoEntry (EthPacketPtr p, uint64_t n) inline
Definition at line 61 of file pktfifo.hh.
Member Function Documentation
clear()
void PacketFifoEntry::clear () inline
Definition at line 66 of file pktfifo.hh.
References X86ISA::base, serialize(), and unserialize().
Referenced by PacketFifoEntry().
serialize()
void PacketFifoEntry::serialize (const std::string & base, CheckpointOut & cp) const
Definition at line 69 of file pktfifo.cc.
References paramOut(), and SparcISA::priv.
Referenced by PacketFifo::check(), and clear().
unserialize()
void PacketFifoEntry::unserialize (const std::string & base, CheckpointIn & cp)
Definition at line 78 of file pktfifo.cc.
References paramIn(), and SparcISA::priv.
Referenced by PacketFifo::check(), clear(), and PacketFifo::unserialize().
Member Data Documentation
number
uint64_t PacketFifoEntry::number
Definition at line 47 of file pktfifo.hh.
Referenced by PacketFifo::push().
packet
EthPacketPtr PacketFifoEntry::packet
Definition at line 46 of file pktfifo.hh.
Referenced by PacketFifo::push().
priv
int PacketFifoEntry::priv
Definition at line 49 of file pktfifo.hh.
slack
unsigned PacketFifoEntry::slack
Definition at line 48 of file pktfifo.hh.
The documentation for this struct was generated from the following files:
dev/net/pktfifo.hh
dev/net/pktfifo.cc