gem5: TAGEBase::FoldedHistory Struct Reference
TAGEBase::FoldedHistory Struct Reference
#include <tage_base.hh>
Public Member Functions
FoldedHistory ()
void init (int original_length, int compressed_length)
void update (uint8_t *h)
Public Attributes
unsigned comp
int compLength
int origLength
int outpoint
int bufferSize
Detailed Description
Definition at line 83 of file tage_base.hh.
Constructor & Destructor Documentation
FoldedHistory()
TAGEBase::FoldedHistory::FoldedHistory () inline
Definition at line 91 of file tage_base.hh.
Member Function Documentation
init()
void TAGEBase::FoldedHistory::init (int original_length, int compressed_length) inline
Definition at line 96 of file tage_base.hh.
Referenced by TAGE_SC_L_TAGE_8KB::initFoldedHistories(), and TAGEBase::initFoldedHistories().
update()
void TAGEBase::FoldedHistory::update (uint8_t * h) inline
Definition at line 103 of file tage_base.hh.
References ULL.
Referenced by TAGEBase::btbUpdate(), TAGEBase::squash(), TAGEBase::updateHistories(), MPP_TAGE::updatePathAndGlobalHistory(), and TAGE_SC_L_TAGE::updatePathAndGlobalHistory().
Member Data Documentation
bufferSize
int TAGEBase::FoldedHistory::bufferSize
Definition at line 89 of file tage_base.hh.
comp
unsigned TAGEBase::FoldedHistory::comp
Definition at line 85 of file tage_base.hh.
Referenced by TAGEBase::btbUpdate(), TAGEBase::squash(), and TAGEBase::updateHistories().
compLength
int TAGEBase::FoldedHistory::compLength
Definition at line 86 of file tage_base.hh.
origLength
int TAGEBase::FoldedHistory::origLength
Definition at line 87 of file tage_base.hh.
Referenced by TAGE_SC_L_TAGE_8KB::initFoldedHistories(), and TAGEBase::initFoldedHistories().
outpoint
int TAGEBase::FoldedHistory::outpoint
Definition at line 88 of file tage_base.hh.
The documentation for this struct was generated from the following file:
cpu/pred/tage_base.hh