gem5: AbstractMemory::MemStats Struct Reference
AbstractMemory::MemStats Struct Reference
#include <abstract_mem.hh>
Public Member Functions
MemStats (AbstractMemory &mem)
void regStats () override
Callback to set stat parameters.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
const AbstractMemory & mem
Stats::Vector bytesRead
Number of total bytes read from this memory.
Stats::Vector bytesInstRead
Number of instruction bytes read from this memory.
Stats::Vector bytesWritten
Number of bytes written to this memory.
Stats::Vector numReads
Number of read requests.
Stats::Vector numWrites
Number of write requests.
Stats::Vector numOther
Number of other requests.
Stats::Formula bwRead
Read bandwidth from this memory.
Stats::Formula bwInstRead
Read bandwidth from this memory.
Stats::Formula bwWrite
Write bandwidth from this memory.
Stats::Formula bwTotal
Total bandwidth from this memory.
Detailed Description
Definition at line 170 of file abstract_mem.hh.
Constructor & Destructor Documentation
MemStats()
AbstractMemory::MemStats::MemStats (AbstractMemory & mem)
Definition at line 92 of file abstract_mem.cc.
Member Function Documentation
regStats()
void AbstractMemory::MemStats::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 118 of file abstract_mem.cc.
References bwInstRead, bwRead, bwTotal, bwWrite, bytesInstRead, bytesRead, bytesWritten, Stats::DataWrap< Derived, InfoProxyType >::flags(), System::getMasterName(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), System::maxMasters(), mem, Stats::nonan, Stats::nozero, numOther, numReads, numWrites, Stats::DataWrap< Derived, InfoProxyType >::precision(), Stats::DataWrap< Derived, InfoProxyType >::prereq(), Stats::Group::regStats(), simSeconds, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), AbstractMemory::system(), and Stats::total.
Member Data Documentation
bwInstRead
Stats::Formula AbstractMemory::MemStats::bwInstRead
Read bandwidth from this memory.
Definition at line 192 of file abstract_mem.hh.
Referenced by regStats().
bwRead
Stats::Formula AbstractMemory::MemStats::bwRead
Read bandwidth from this memory.
Definition at line 190 of file abstract_mem.hh.
Referenced by regStats().
bwTotal
Stats::Formula AbstractMemory::MemStats::bwTotal
Total bandwidth from this memory.
Definition at line 196 of file abstract_mem.hh.
Referenced by regStats().
bwWrite
Stats::Formula AbstractMemory::MemStats::bwWrite
Write bandwidth from this memory.
Definition at line 194 of file abstract_mem.hh.
Referenced by regStats().
bytesInstRead
Stats::Vector AbstractMemory::MemStats::bytesInstRead
Number of instruction bytes read from this memory.
Definition at line 180 of file abstract_mem.hh.
Referenced by regStats().
bytesRead
Stats::Vector AbstractMemory::MemStats::bytesRead
Number of total bytes read from this memory.
Definition at line 178 of file abstract_mem.hh.
Referenced by regStats().
bytesWritten
Stats::Vector AbstractMemory::MemStats::bytesWritten
Number of bytes written to this memory.
Definition at line 182 of file abstract_mem.hh.
Referenced by regStats().
mem
const AbstractMemory& AbstractMemory::MemStats::mem
Definition at line 175 of file abstract_mem.hh.
Referenced by regStats().
numOther
Stats::Vector AbstractMemory::MemStats::numOther
Number of other requests.
Definition at line 188 of file abstract_mem.hh.
Referenced by regStats().
numReads
Stats::Vector AbstractMemory::MemStats::numReads
Number of read requests.
Definition at line 184 of file abstract_mem.hh.
Referenced by regStats().
numWrites
Stats::Vector AbstractMemory::MemStats::numWrites
Number of write requests.
Definition at line 186 of file abstract_mem.hh.
Referenced by regStats().
The documentation for this struct was generated from the following files:
mem/abstract_mem.hh
mem/abstract_mem.cc