gem5: ThreadState Struct Reference
ThreadState Struct Reference
Struct for holding general thread state that is needed across CPU models.
#include <thread_state.hh>
Public Types
typedef ThreadContext::Status Status
Public Member Functions
ThreadState (BaseCPU *cpu, ThreadID _tid, Process *_process)
virtual ~ThreadState ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
int cpuId () const
uint32_t socketId () const
ContextID contextId () const
void setContextId (ContextID id)
void setThreadId (ThreadID id)
ThreadID threadId () const
Tick readLastActivate () const
Tick readLastSuspend () const
void initMemProxies (ThreadContext *tc)
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
void dumpFuncProfile ()
EndQuiesceEvent * getQuiesceEvent ()
void profileClear ()
void profileSample ()
Kernel::Statistics * getKernelStats ()
PortProxy & getPhysProxy ()
PortProxy & getVirtProxy ()
Process * getProcessPtr ()
void setProcessPtr (Process *p)
Counter readFuncExeInst () const
Reads the number of instructions functionally executed and committed.
void setFuncExeInst (Counter new_val)
Sets the total number of instructions functionally executed and committed.
Status status () const
Returns the status of this thread.
void setStatus (Status new_status)
Sets the status of this thread.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
Counter numInst
Number of instructions committed.
Stats::Scalar numInsts
Stat for number instructions committed.
Counter numOp
Number of ops (including micro ops) committed.
Stats::Scalar numOps
Stat for number ops (including micro ops) committed.
Stats::Scalar numMemRefs
Stat for number of memory references.
Counter numLoad
Number of simulated loads, used for tracking events based on the number of loads committed.
Counter startNumLoad
The number of simulated loads committed prior to this run.
Tick lastActivate
Last time activate was called on this thread.
Tick lastSuspend
Last time suspend was called on this thread.
FunctionProfile * profile
ProfileNode * profileNode
Addr profilePC
EndQuiesceEvent * quiesceEvent
Kernel::Statistics * kernelStats
Counter funcExeInst
unsigned storeCondFailures
Protected Attributes
ThreadContext::Status _status
BaseCPU * baseCpu
ContextID _contextId
ThreadID _threadId
Process * process
PortProxy * physProxy
A port proxy outgoing only for functional accesses to physical addresses.
PortProxy * virtProxy
A translating port proxy, outgoing only, for functional accesse to virtual addresses.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Struct for holding general thread state that is needed across CPU models.
This includes things such as pointers to the process, memory, quiesce events, and certain stats. This can be expanded to hold more thread-specific stats within it.
Definition at line 59 of file thread_state.hh.
Member Typedef Documentation
Status
typedef ThreadContext::Status ThreadState::Status
Definition at line 60 of file thread_state.hh.
Constructor & Destructor Documentation
ThreadState()
ThreadState::ThreadState (BaseCPU * cpu, ThreadID _tid, Process * _process)
Definition at line 46 of file thread_state.cc.
~ThreadState()
ThreadState::~ThreadState () virtual
Definition at line 56 of file thread_state.cc.
References physProxy, and virtProxy.
Member Function Documentation
contextId()
ContextID ThreadState::contextId () const inline
Definition at line 74 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::contextId(), and SimpleThread::contextId().
cpuId()
int ThreadState::cpuId () const inline
Definition at line 70 of file thread_state.hh.
Referenced by SimpleThread::cpuId().
dumpFuncProfile()
void ThreadState::dumpFuncProfile ()
getKernelStats()
Kernel::Statistics* ThreadState::getKernelStats () inline
Definition at line 102 of file thread_state.hh.
Referenced by SimpleThread::getKernelStats().
getPhysProxy()
PortProxy & ThreadState::getPhysProxy ()
Definition at line 127 of file thread_state.cc.
References FullSystem, and physProxy.
Referenced by O3ThreadContext< Impl >::getPhysProxy(), and SimpleThread::getPhysProxy().
getProcessPtr()
Process* ThreadState::getProcessPtr () inline
Definition at line 108 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::getProcessPtr(), and SimpleThread::getProcessPtr().
getQuiesceEvent()
EndQuiesceEvent* ThreadState::getQuiesceEvent () inline
Definition at line 96 of file thread_state.hh.
Referenced by SimpleThread::getQuiesceEvent().
getVirtProxy()
PortProxy & ThreadState::getVirtProxy ()
Definition at line 135 of file thread_state.cc.
References virtProxy.
Referenced by SimpleThread::getVirtProxy().
initMemProxies()
void ThreadState::initMemProxies (ThreadContext * tc)
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
Parameters
tc ThreadContext for the virtual-to-physical translation
Definition at line 102 of file thread_state.cc.
References baseCpu, BaseCPU::cacheLineSize(), FullSystem, BaseCPU::getSendFunctional(), SETranslatingPortProxy::NextPage, physProxy, process, and virtProxy.
Referenced by O3ThreadContext< Impl >::initMemProxies(), and SimpleThread::initMemProxies().
profileClear()
void ThreadState::profileClear ()
Definition at line 142 of file thread_state.cc.
References FunctionProfile::clear(), and profile.
Referenced by SimpleThread::profileClear().
profileSample()
void ThreadState::profileSample ()
Definition at line 149 of file thread_state.cc.
References profile, profileNode, profilePC, and FunctionProfile::sample().
Referenced by SimpleThread::profileSample().
readFuncExeInst()
Counter ThreadState::readFuncExeInst () const inline
Reads the number of instructions functionally executed and committed.
Definition at line 128 of file thread_state.hh.
Referenced by SimpleThread::readFuncExeInst().
readLastActivate()
Tick ThreadState::readLastActivate () const inline
Definition at line 82 of file thread_state.hh.
Referenced by SimpleThread::readLastActivate().
readLastSuspend()
Tick ThreadState::readLastSuspend () const inline
Definition at line 84 of file thread_state.hh.
Referenced by SimpleThread::readLastSuspend().
serialize()
void ThreadState::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 65 of file thread_state.cc.
References _status, FullSystem, funcExeInst, kernelStats, quiesceEvent, Event::scheduled(), Kernel::Statistics::serialize(), SERIALIZE_ENUM, SERIALIZE_SCALAR, and Event::when().
Referenced by O3ThreadState< Impl >::serialize(), and SimpleThread::serialize().
setContextId()
void ThreadState::setContextId (ContextID id) inline
Definition at line 76 of file thread_state.hh.
References ArmISA::id.
Referenced by O3ThreadContext< Impl >::setContextId(), and SimpleThread::setContextId().
setFuncExeInst()
void ThreadState::setFuncExeInst (Counter new_val) inline
Sets the total number of instructions functionally executed and committed.
Definition at line 133 of file thread_state.hh.
setProcessPtr()
void ThreadState::setProcessPtr (Process * p) inline
When the process pointer changes while operating in SE Mode, the se translating port proxy needs to be reinitialized since it holds a pointer to the process class.
Definition at line 110 of file thread_state.hh.
References MipsISA::p.
Referenced by O3ThreadContext< Impl >::setProcessPtr(), and SimpleThread::setProcessPtr().
setStatus()
void ThreadState::setStatus (Status new_status) inline
Sets the status of this thread.
Definition at line 139 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::setStatus().
setThreadId()
void ThreadState::setThreadId (ThreadID id) inline
Definition at line 78 of file thread_state.hh.
References ArmISA::id.
Referenced by O3ThreadContext< Impl >::setThreadId(), and SimpleThread::setThreadId().
socketId()
uint32_t ThreadState::socketId () const inline
Definition at line 72 of file thread_state.hh.
Referenced by SimpleThread::socketId().
status()
Status ThreadState::status () const inline
Returns the status of this thread.
Definition at line 136 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::status().
threadId()
ThreadID ThreadState::threadId () const inline
Definition at line 80 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::conditionalSquash(), O3ThreadContext< Impl >::getDecoderPtr(), O3ThreadContext< Impl >::getIsaPtr(), O3ThreadContext< Impl >::instAddr(), O3ThreadContext< Impl >::microPC(), O3ThreadContext< Impl >::nextInstAddr(), O3ThreadContext< Impl >::pcState(), O3ThreadContext< Impl >::readMiscReg(), O3ThreadContext< Impl >::readMiscRegNoEffect(), O3ThreadContext< Impl >::readVecLaneFlat(), O3ThreadContext< Impl >::setVecLaneFlat(), O3ThreadContext< Impl >::syscall(), O3ThreadContext< Impl >::threadId(), and SimpleThread::threadId().
unserialize()
void ThreadState::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 83 of file thread_state.cc.
References _status, baseCpu, FullSystem, funcExeInst, kernelStats, quiesceEvent, EventManager::schedule(), Kernel::Statistics::unserialize(), UNSERIALIZE_ENUM, and UNSERIALIZE_SCALAR.
Referenced by O3ThreadState< Impl >::unserialize(), and SimpleThread::unserialize().
Member Data Documentation
_contextId
ContextID ThreadState::_contextId protected
Definition at line 169 of file thread_state.hh.
Referenced by SimpleThread::copyState().
_status
ThreadContext::Status ThreadState::_status protected
Definition at line 163 of file thread_state.hh.
Referenced by SimpleThread::activate(), SimpleThread::copyState(), SimpleThread::halt(), serialize(), SimpleThread::suspend(), and unserialize().
_threadId
ThreadID ThreadState::_threadId protected
Definition at line 172 of file thread_state.hh.
Referenced by SimpleThread::activate(), SimpleThread::copyState(), SimpleThread::halt(), and SimpleThread::suspend().
baseCpu
BaseCPU* ThreadState::baseCpu protected
Definition at line 166 of file thread_state.hh.
Referenced by SimpleThread::activate(), SimpleThread::dumpFuncProfile(), SimpleThread::halt(), initMemProxies(), SimpleThread::SimpleThread(), SimpleThread::suspend(), and unserialize().
funcExeInst
Counter ThreadState::funcExeInst
Definition at line 205 of file thread_state.hh.
Referenced by SimpleThread::copyState(), BaseSimpleCPU::countInst(), O3ThreadContext< Impl >::readFuncExeInst(), serialize(), SimpleThread::takeOverFrom(), and unserialize().
kernelStats
Kernel::Statistics* ThreadState::kernelStats
Definition at line 187 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::getKernelStats(), SimpleThread::regStats(), serialize(), CheckerCPU::setSystem(), SimpleThread::SimpleThread(), SimpleThread::takeOverFrom(), and unserialize().
lastActivate
Tick ThreadState::lastActivate
Last time activate was called on this thread.
Definition at line 176 of file thread_state.hh.
Referenced by SimpleThread::activate(), BaseKvmCPU::activateContext(), and SimpleThread::suspend().
lastSuspend
Tick ThreadState::lastSuspend
Last time suspend was called on this thread.
Definition at line 179 of file thread_state.hh.
Referenced by BaseKvmCPU::activateContext(), and SimpleThread::suspend().
numInst
Counter ThreadState::numInst
Number of instructions committed.
Definition at line 144 of file thread_state.hh.
numInsts
Stats::Scalar ThreadState::numInsts
Stat for number instructions committed.
Definition at line 146 of file thread_state.hh.
numLoad
Counter ThreadState::numLoad
Number of simulated loads, used for tracking events based on the number of loads committed.
Definition at line 157 of file thread_state.hh.
numMemRefs
Stats::Scalar ThreadState::numMemRefs
Stat for number of memory references.
Definition at line 152 of file thread_state.hh.
numOp
Counter ThreadState::numOp
Number of ops (including micro ops) committed.
Definition at line 148 of file thread_state.hh.
numOps
Stats::Scalar ThreadState::numOps
Stat for number ops (including micro ops) committed.
Definition at line 150 of file thread_state.hh.
physProxy
PortProxy* ThreadState::physProxy protected
A port proxy outgoing only for functional accesses to physical addresses.
Definition at line 194 of file thread_state.hh.
Referenced by getPhysProxy(), initMemProxies(), and ~ThreadState().
process
Process* ThreadState::process protected
Definition at line 190 of file thread_state.hh.
Referenced by initMemProxies(), and O3ThreadState< Impl >::syscall().
profile
FunctionProfile* ThreadState::profile
Definition at line 182 of file thread_state.hh.
Referenced by O3ThreadState< Impl >::dumpFuncProfile(), SimpleThread::dumpFuncProfile(), O3ThreadState< Impl >::O3ThreadState(), BaseSimpleCPU::postExecute(), profileClear(), profileSample(), and SimpleThread::SimpleThread().
profileNode
ProfileNode* ThreadState::profileNode
Definition at line 183 of file thread_state.hh.
Referenced by O3ThreadState< Impl >::O3ThreadState(), BaseSimpleCPU::postExecute(), profileSample(), and SimpleThread::SimpleThread().
profilePC
Addr ThreadState::profilePC
Definition at line 184 of file thread_state.hh.
Referenced by O3ThreadState< Impl >::O3ThreadState(), BaseSimpleCPU::postExecute(), profileSample(), and SimpleThread::SimpleThread().
quiesceEvent
EndQuiesceEvent* ThreadState::quiesceEvent
Definition at line 185 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::getQuiesceEvent(), serialize(), SimpleThread::SimpleThread(), and unserialize().
startNumLoad
Counter ThreadState::startNumLoad
The number of simulated loads committed prior to this run.
Definition at line 160 of file thread_state.hh.
storeCondFailures
unsigned ThreadState::storeCondFailures
Definition at line 210 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::readStCondFailures(), O3ThreadContext< Impl >::setStCondFailures(), and SimpleThread::takeOverFrom().
virtProxy
PortProxy* ThreadState::virtProxy protected
A translating port proxy, outgoing only, for functional accesse to virtual addresses.
Definition at line 198 of file thread_state.hh.
Referenced by getVirtProxy(), initMemProxies(), and ~ThreadState().
The documentation for this struct was generated from the following files:
cpu/thread_state.hh
cpu/thread_state.cc