gem5: ArmISA::PMU::CounterState Struct Reference
ArmISA::PMU::CounterState Struct Reference
State of a counter within the PMU.
#include <pmu.hh>
Public Member Functions
CounterState (PMU &pmuReference, uint64_t counter_id)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
uint64_t add (uint64_t delta)
Add an event count to the counter and check for overflow.
bool isFiltered () const
void detach ()
Detach the counter from its event.
void attach (PMUEvent *event)
Attach this counter to an event.
uint64_t getCounterId () const
Obtain the counter id.
uint64_t getValue () const
rReturn the counter value
void setValue (uint64_t val)
overwrite the value of the counter
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
EventTypeId eventId
Counter event ID.
PMEVTYPER_t filter
Filtering settings (evtCount is unused)
bool enabled
Is the counter enabled?
bool overflow64
Is this a 64-bit counter?
Protected Member Functions
template<typename ... Args>
void debugCounter (const char *mainString, Args &...args) const
Protected Attributes
PMUEvent * sourceEvent
PmuEvent currently in use (if any)
uint64_t counterId
id of the counter instance
uint64_t value
Current value of the counter.
bool resetValue
Flag keeping track if the counter has been reset.
PMU & pmu
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
State of a counter within the PMU.
Definition at line 412 of file pmu.hh.
Constructor & Destructor Documentation
CounterState()
ArmISA::PMU::CounterState::CounterState (PMU & pmuReference, uint64_t counter_id) inline
Definition at line 413 of file pmu.hh.
References MipsISA::event, ArmISA::PMU::isFiltered(), ArmISA::PMU::serialize(), and ArmISA::PMU::unserialize().
Member Function Documentation
add()
uint64_t ArmISA::PMU::CounterState::add (uint64_t delta)
Add an event count to the counter and check for overflow.
Parameters
delta Number of events to add to the counter.
Returns
the quantity remaining until a counter overflow occurs.
Definition at line 769 of file pmu.cc.
References ArmISA::PMU::isFiltered().
attach()
void ArmISA::PMU::CounterState::attach (PMUEvent * event)
Attach this counter to an event.
Parameters
the event to attach the counter to
Definition at line 536 of file pmu.cc.
References MipsISA::event.
Referenced by ArmISA::PMU::regProbeListeners(), and ArmISA::PMU::updateCounter().
debugCounter()
template<typename ... Args> void ArmISA::PMU::CounterState::debugCounter (const char * mainString, Args &... args) const inline protected
Definition at line 496 of file pmu.hh.
References csprintf(), and warn.
detach()
void ArmISA::PMU::CounterState::detach ()
Detach the counter from its event.
Definition at line 524 of file pmu.cc.
Referenced by ArmISA::PMU::updateCounter().
getCounterId()
uint64_t ArmISA::PMU::CounterState::getCounterId () const inline
Obtain the counter id.
Returns
the pysical counter id
Definition at line 449 of file pmu.hh.
Referenced by ArmISA::PMU::updateCounter().
getValue()
uint64_t ArmISA::PMU::CounterState::getValue () const
rReturn the counter value
Returns
the counter value
Definition at line 547 of file pmu.cc.
Referenced by ArmISA::PMU::getCounterValue(), and ArmISA::PMU::readMiscRegInt().
isFiltered()
bool ArmISA::PMU::CounterState::isFiltered () const
Definition at line 495 of file pmu.cc.
References ArmISA::currEL(), ArmISA::el, ArmISA::EL0, ArmISA::EL1, ArmISA::EL2, ArmISA::EL3, ArmISA::inSecureState(), ArmISA::MISCREG_CPSR, ArmISA::MISCREG_SCR, and panic.
serialize()
void ArmISA::PMU::CounterState::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 753 of file pmu.cc.
References SERIALIZE_SCALAR.
setValue()
void ArmISA::PMU::CounterState::setValue (uint64_t val)
overwrite the value of the counter
Parameters
the new counter value
Definition at line 559 of file pmu.cc.
References X86ISA::val.
Referenced by ArmISA::PMU::setControlReg(), ArmISA::PMU::setCounterValue(), and ArmISA::PMU::setMiscReg().
unserialize()
void ArmISA::PMU::CounterState::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 761 of file pmu.cc.
References UNSERIALIZE_SCALAR.
Member Data Documentation
counterId
uint64_t ArmISA::PMU::CounterState::counterId protected
id of the counter instance
Definition at line 485 of file pmu.hh.
enabled
bool ArmISA::PMU::CounterState::enabled
Is the counter enabled?
Definition at line 475 of file pmu.hh.
Referenced by ArmISA::PMU::regProbeListeners(), ArmISA::PMU::updateAllCounters(), and ArmISA::PMU::updateCounter().
eventId
EventTypeId ArmISA::PMU::CounterState::eventId
Counter event ID.
Definition at line 469 of file pmu.hh.
Referenced by ArmISA::PMU::getCounterTypeRegister(), ArmISA::PMU::PMU(), ArmISA::PMU::setCounterTypeRegister(), and ArmISA::PMU::updateCounter().
filter
PMEVTYPER_t ArmISA::PMU::CounterState::filter
Filtering settings (evtCount is unused)
Definition at line 472 of file pmu.hh.
Referenced by ArmISA::PMU::getCounterTypeRegister(), and ArmISA::PMU::setCounterTypeRegister().
overflow64
bool ArmISA::PMU::CounterState::overflow64
Is this a 64-bit counter?
Definition at line 478 of file pmu.hh.
pmu
PMU& ArmISA::PMU::CounterState::pmu protected
Definition at line 493 of file pmu.hh.
resetValue
bool ArmISA::PMU::CounterState::resetValue protected
Flag keeping track if the counter has been reset.
Definition at line 491 of file pmu.hh.
sourceEvent
PMUEvent* ArmISA::PMU::CounterState::sourceEvent protected
PmuEvent currently in use (if any)
Definition at line 482 of file pmu.hh.
value
uint64_t ArmISA::PMU::CounterState::value protected
Current value of the counter.
Definition at line 488 of file pmu.hh.
The documentation for this struct was generated from the following files:
arch/arm/pmu.hh
arch/arm/pmu.cc