gem5: cp::Print Struct Reference
cp::Print Struct Reference
#include <cprintf.hh>
Public Member Functions
Print (std::ostream &stream, const std::string &format)
Print (std::ostream &stream, const char *format)
~Print ()
int get_number (int data)
template<typename T >
int get_number (const T &data)
template<typename T >
void add_arg (const T &data)
void end_args ()
Protected Member Functions
void process ()
void process_flag ()
Protected Attributes
std::ostream & stream
const char * format
const char * ptr
bool cont
std::ios::fmtflags saved_flags
char saved_fill
int saved_precision
int saved_width
Format fmt
Detailed Description
Definition at line 46 of file cprintf.hh.
Constructor & Destructor Documentation
Print() [1/2]
cp::Print::Print (std::ostream & stream, const std::string & format)
Definition at line 44 of file cprintf.cc.
References saved_fill, saved_flags, saved_precision, and saved_width.
Print() [2/2]
cp::Print::Print (std::ostream & stream, const char * format)
Definition at line 53 of file cprintf.cc.
References saved_fill, saved_flags, saved_precision, and saved_width.
~Print()
cp::Print::~Print ()
Definition at line 62 of file cprintf.cc.
Member Function Documentation
add_arg()
template<typename T > void cp::Print::add_arg (const T & data) inline
Definition at line 83 of file cprintf.hh.
References cp::Format::character, end_args(), cp::Format::floating, cp::Format::format, cp::format_char(), cp::format_float(), cp::format_integer(), cp::format_string(), get_number(), cp::Format::get_precision, cp::Format::get_width, cp::Format::integer, cp::Format::precision, process(), cp::Format::string, and cp::Format::width.
Referenced by ccprintf().
end_args()
void cp::Print::end_args ()
Definition at line 280 of file cprintf.cc.
References ArmISA::len, ptr, saved_fill, saved_flags, saved_precision, saved_width, and stream.
Referenced by add_arg(), and ccprintf().
get_number() [1/2]
int cp::Print::get_number (int data) inline
Definition at line 69 of file cprintf.hh.
References data.
Referenced by add_arg().
get_number() [2/2]
template<typename T > int cp::Print::get_number (const T & data) inline
Definition at line 76 of file cprintf.hh.
process()
void cp::Print::process () protected
Definition at line 67 of file cprintf.cc.
References cp::Format::clear(), fmt, ArmISA::len, process_flag(), ptr, and stream.
Referenced by add_arg().
process_flag()
void cp::Print::process_flag () protected
Definition at line 104 of file cprintf.cc.
References cp::Format::alternate_form, cp::Format::base, cp::Format::best, cp::Format::blank_space, cp::Format::character, cp::Format::fill_zero, cp::Format::fixed, cp::Format::float_format, cp::Format::floating, cp::Format::flush_left, fmt, cp::Format::format, cp::Format::get_precision, cp::Format::get_width, cp::Format::hex, cp::Format::integer, M5_FALLTHROUGH, cp::Format::oct, cp::Format::precision, cp::Format::print_sign, ptr, cp::Format::scientific, stream, cp::Format::string, cp::Format::uppercase, and cp::Format::width.
Referenced by process().
Member Data Documentation
cont
bool cp::Print::cont protected
Definition at line 52 of file cprintf.hh.
fmt
Format cp::Print::fmt protected
Definition at line 59 of file cprintf.hh.
Referenced by process(), and process_flag().
format
const char* cp::Print::format protected
Definition at line 50 of file cprintf.hh.
ptr
const char* cp::Print::ptr protected
Definition at line 51 of file cprintf.hh.
Referenced by end_args(), process(), and process_flag().
saved_fill
char cp::Print::saved_fill protected
Definition at line 55 of file cprintf.hh.
Referenced by end_args(), and Print().
saved_flags
std::ios::fmtflags cp::Print::saved_flags protected
Definition at line 54 of file cprintf.hh.
Referenced by end_args(), and Print().
saved_precision
int cp::Print::saved_precision protected
Definition at line 56 of file cprintf.hh.
Referenced by end_args(), and Print().
saved_width
int cp::Print::saved_width protected
Definition at line 57 of file cprintf.hh.
Referenced by end_args(), and Print().
stream
std::ostream& cp::Print::stream protected
Definition at line 49 of file cprintf.hh.
Referenced by csprintf(), end_args(), process(), and process_flag().
The documentation for this struct was generated from the following files:
base/cprintf.hh
base/cprintf.cc