gem5: EmbeddedPython Struct Reference
EmbeddedPython Struct Reference
#include <init.hh>
Public Member Functions
EmbeddedPython (const char *filename, const char *abspath, const char *modpath, const uint8_t *code, int zlen, int len)
PyObject * getCode () const
bool addModule () const
Static Public Member Functions
static std::list< EmbeddedPython * > & getList ()
static int initAll ()
Public Attributes
const char * filename
const char * abspath
const char * modpath
const uint8_t * code
int zlen
int len
Static Public Attributes
static EmbeddedPython * importer = NULL
static PyObject * importerModule = NULL
Detailed Description
Definition at line 62 of file init.hh.
Constructor & Destructor Documentation
EmbeddedPython()
EmbeddedPython::EmbeddedPython (const char * filename, const char * abspath, const char * modpath, const uint8_t * code, int zlen, int len)
Definition at line 78 of file init.cc.
References getList(), and importer.
Member Function Documentation
addModule()
bool EmbeddedPython::addModule () const
Definition at line 116 of file init.cc.
References abspath, code, filename, getCode(), importerModule, modpath, and PyCC.
getCode()
PyObject * EmbeddedPython::getCode () const
Definition at line 103 of file init.cc.
References code, len, panic, and zlen.
Referenced by addModule(), and initAll().
getList()
list< EmbeddedPython * > & EmbeddedPython::getList () static
Definition at line 92 of file init.cc.
Referenced by EmbeddedPython(), and initAll().
initAll()
int EmbeddedPython::initAll () static
Definition at line 134 of file init.cc.
References X86ISA::base, code, EmbeddedPyBind::EmbeddedPyBind(), getCode(), getList(), ArmISA::i, importer, importerModule, name(), and PyCC.
Referenced by main().
Member Data Documentation
abspath
const char* EmbeddedPython::abspath
Definition at line 65 of file init.hh.
Referenced by addModule().
code
const uint8_t* EmbeddedPython::code
Definition at line 67 of file init.hh.
Referenced by addModule(), getCode(), and initAll().
filename
const char* EmbeddedPython::filename
Definition at line 64 of file init.hh.
Referenced by addModule().
importer
EmbeddedPython * EmbeddedPython::importer = NULL static
Definition at line 77 of file init.hh.
Referenced by EmbeddedPython(), and initAll().
importerModule
PyObject * EmbeddedPython::importerModule = NULL static
Definition at line 78 of file init.hh.
Referenced by addModule(), and initAll().
len
int EmbeddedPython::len
Definition at line 69 of file init.hh.
Referenced by getCode().
modpath
const char* EmbeddedPython::modpath
Definition at line 66 of file init.hh.
Referenced by addModule().
zlen
int EmbeddedPython::zlen
Definition at line 68 of file init.hh.
Referenced by getCode().
The documentation for this struct was generated from the following files:
sim/init.hh
sim/init.cc