gem5: DisplayTimings Struct Reference
DisplayTimings Struct Reference
#include <pixelpump.hh>
Public Member Functions
DisplayTimings (unsigned width, unsigned height, unsigned hbp, unsigned h_sync, unsigned hfp, unsigned vbp, unsigned v_sync, unsigned vfp)
Create a display timing configuration struct.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Cycles cyclesPerLine () const
How many pixel clocks are required for one line?
Cycles cyclesPerFrame () const
How many pixel clocks are required for one frame?
unsigned lineVSyncStart () const
Calculate the first line of the vsync signal.
unsigned lineVBackPorchStart () const
Calculate the first line of the vertical back porch.
unsigned lineFirstVisible () const
Calculate the first line of the visible region.
unsigned lineFrontPorchStart () const
Calculate the first line of the back porch.
unsigned linesPerFrame () const
Calculate the total number of lines in a frame.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
unsigned width
Display width in pixels.
unsigned height
Display height in pixels.
unsigned hBackPorch
Horizontal back porch in pixels.
unsigned hFrontPorch
Horizontal front porch in pixels.
unsigned hSync
Horizontal sync signal length in pixels.
unsigned vBackPorch
Vertical back porch in lines.
unsigned vFrontPorch
Vertical front porch in lines.
unsigned vSync
Vertical sync signal in lines.
Static Public Attributes
static const DisplayTimings vga
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Definition at line 48 of file pixelpump.hh.
Constructor & Destructor Documentation
DisplayTimings()
DisplayTimings::DisplayTimings (unsigned width, unsigned height, unsigned hbp, unsigned h_sync, unsigned hfp, unsigned vbp, unsigned v_sync, unsigned vfp)
Create a display timing configuration struct.
Parameters
width Width of the visible area of the screen.
height Height of the visible area of the screen.
hfp Horizontal front porch in pixel clocks.
h_sync Horizontal sync in pixel clocks.
hbp Horizontal back porch in pixel clocks.
vfp Vertical front porch in scan lines.
v_sync Vertical sync in scan lines.
vbp Vertical back porch in scan lines.
Definition at line 48 of file pixelpump.cc.
Member Function Documentation
cyclesPerFrame()
Cycles DisplayTimings::cyclesPerFrame () const inline
How many pixel clocks are required for one frame?
Definition at line 75 of file pixelpump.hh.
References cyclesPerLine(), and linesPerFrame().
cyclesPerLine()
Cycles DisplayTimings::cyclesPerLine () const inline
How many pixel clocks are required for one line?
Definition at line 70 of file pixelpump.hh.
References hBackPorch, and hSync.
Referenced by BasePixelPump::beginLine(), and cyclesPerFrame().
lineFirstVisible()
unsigned DisplayTimings::lineFirstVisible () const inline
Calculate the first line of the visible region.
Definition at line 90 of file pixelpump.hh.
References lineVBackPorchStart(), and vBackPorch.
Referenced by BasePixelPump::beginLine(), lineFrontPorchStart(), and BasePixelPump::renderFrame().
lineFrontPorchStart()
unsigned DisplayTimings::lineFrontPorchStart () const inline
Calculate the first line of the back porch.
Definition at line 95 of file pixelpump.hh.
References height, and lineFirstVisible().
Referenced by BasePixelPump::beginLine(), linesPerFrame(), and BasePixelPump::renderFrame().
linesPerFrame()
unsigned DisplayTimings::linesPerFrame () const inline
Calculate the total number of lines in a frame.
Definition at line 100 of file pixelpump.hh.
References lineFrontPorchStart(), and vFrontPorch.
Referenced by BasePixelPump::beginLine(), cyclesPerFrame(), and BasePixelPump::updateTimings().
lineVBackPorchStart()
unsigned DisplayTimings::lineVBackPorchStart () const inline
Calculate the first line of the vertical back porch.
Definition at line 85 of file pixelpump.hh.
References lineVSyncStart(), and vSync.
Referenced by BasePixelPump::beginLine(), lineFirstVisible(), and BasePixelPump::renderFrame().
lineVSyncStart()
unsigned DisplayTimings::lineVSyncStart () const inline
Calculate the first line of the vsync signal.
Definition at line 80 of file pixelpump.hh.
Referenced by BasePixelPump::beginLine(), lineVBackPorchStart(), and BasePixelPump::renderFrame().
serialize()
void DisplayTimings::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 58 of file pixelpump.cc.
References hBackPorch, height, hFrontPorch, hSync, SERIALIZE_SCALAR, vBackPorch, vFrontPorch, vSync, and width.
unserialize()
void DisplayTimings::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 73 of file pixelpump.cc.
References hBackPorch, height, hFrontPorch, hSync, UNSERIALIZE_SCALAR, vBackPorch, vFrontPorch, vSync, and width.
Member Data Documentation
hBackPorch
unsigned DisplayTimings::hBackPorch
Horizontal back porch in pixels.
Definition at line 110 of file pixelpump.hh.
Referenced by BasePixelPump::beginLine(), cyclesPerLine(), HDLcd::PixelPump::dumpSettings(), serialize(), and unserialize().
height
unsigned DisplayTimings::height
Display height in pixels.
Definition at line 107 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), lineFrontPorchStart(), BasePixelPump::renderPixels(), serialize(), unserialize(), and BasePixelPump::updateTimings().
hFrontPorch
unsigned DisplayTimings::hFrontPorch
Horizontal front porch in pixels.
Definition at line 112 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), serialize(), and unserialize().
hSync
unsigned DisplayTimings::hSync
Horizontal sync signal length in pixels.
Definition at line 114 of file pixelpump.hh.
Referenced by BasePixelPump::beginLine(), cyclesPerLine(), HDLcd::PixelPump::dumpSettings(), serialize(), and unserialize().
vBackPorch
unsigned DisplayTimings::vBackPorch
Vertical back porch in lines.
Definition at line 117 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), lineFirstVisible(), serialize(), and unserialize().
vFrontPorch
unsigned DisplayTimings::vFrontPorch
Vertical front porch in lines.
Definition at line 119 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), linesPerFrame(), serialize(), and unserialize().
vga
const DisplayTimings DisplayTimings::vga static
Definition at line 123 of file pixelpump.hh.
vSync
unsigned DisplayTimings::vSync
Vertical sync signal in lines.
Definition at line 121 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), lineVBackPorchStart(), serialize(), and unserialize().
width
unsigned DisplayTimings::width
Display width in pixels.
Definition at line 105 of file pixelpump.hh.
Referenced by HDLcd::PixelPump::dumpSettings(), BasePixelPump::renderLine(), BasePixelPump::renderPixels(), serialize(), unserialize(), and BasePixelPump::updateTimings().
The documentation for this struct was generated from the following files:
dev/pixelpump.hh
dev/pixelpump.cc