gem5: Net::TcpHdr Struct Reference
Net::TcpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint16_t sport () const
uint16_t dport () const
uint32_t seq () const
uint32_t ack () const
uint8_t off () const
uint8_t flags () const
uint16_t win () const
uint16_t sum () const
uint16_t urp () const
void sum (uint16_t sum)
void seq (uint32_t _seq)
void flags (uint8_t _flags)
bool options (std::vector< const TcpOpt *> &vec) const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 510 of file inet.hh.
Member Function Documentation
ack()
uint32_t Net::TcpHdr::ack () const inline
Definition at line 515 of file inet.hh.
Referenced by Sinic::Device::rxKick().
bytes() [1/2]
const uint8_t* Net::TcpHdr::bytes () const inline
Definition at line 529 of file inet.hh.
bytes() [2/2]
uint8_t* Net::TcpHdr::bytes () inline
Definition at line 531 of file inet.hh.
dport()
uint16_t Net::TcpHdr::dport () const inline
Definition at line 513 of file inet.hh.
Referenced by Sinic::Device::rxKick().
flags() [1/2]
uint8_t Net::TcpHdr::flags () const inline
Definition at line 517 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete().
flags() [2/2]
void Net::TcpHdr::flags (uint8_t _flags) inline
Definition at line 524 of file inet.hh.
off()
uint8_t Net::TcpHdr::off () const inline
Definition at line 516 of file inet.hh.
options()
bool Net::TcpHdr::options (std::vector< const TcpOpt *> & vec) const
Definition at line 359 of file inet.cc.
References data, ArmISA::len, and Net::TcpOpt::len().
payload() [1/2]
const uint8_t* Net::TcpHdr::payload () const inline
Definition at line 530 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
payload() [2/2]
uint8_t* Net::TcpHdr::payload () inline
Definition at line 532 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
seq() [1/2]
uint32_t Net::TcpHdr::seq () const inline
Definition at line 514 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete(), NSGigE::recvPacket(), and Sinic::Device::rxKick().
seq() [2/2]
void Net::TcpHdr::seq (uint32_t _seq) inline
Definition at line 523 of file inet.hh.
size()
int Net::TcpHdr::size () const inline
Definition at line 528 of file inet.hh.
sport()
uint16_t Net::TcpHdr::sport () const inline
Definition at line 512 of file inet.hh.
Referenced by Sinic::Device::rxKick().
sum() [1/2]
uint16_t Net::TcpHdr::sum () const inline
Definition at line 519 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete(), Sinic::Device::txKick(), and NSGigE::txKick().
sum() [2/2]
void Net::TcpHdr::sum (uint16_t sum) inline
Definition at line 522 of file inet.hh.
References sum().
Referenced by sum().
urp()
uint16_t Net::TcpHdr::urp () const inline
Definition at line 520 of file inet.hh.
win()
uint16_t Net::TcpHdr::win () const inline
Definition at line 518 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc