gem5: V8PageTableOps4k Struct Reference
V8PageTableOps4k Struct Reference
#include <smmu_v3_ptops.hh>
Public Member Functions
bool isValid (pte_t pte, unsigned level) const override
bool isLeaf (pte_t pte, unsigned level) const override
bool isWritable (pte_t pte, unsigned level, bool stage2) const override
Addr nextLevelPointer (pte_t pte, unsigned level) const override
Addr index (Addr va, unsigned level) const override
Addr pageMask (pte_t pte, unsigned level) const override
Addr walkMask (unsigned level) const override
unsigned firstLevel (uint8_t tsz) const override
unsigned lastLevel () const override
Additional Inherited Members
Public Types inherited from PageTableOps
typedef int64_t pte_t
Detailed Description
Definition at line 75 of file smmu_v3_ptops.hh.
Member Function Documentation
firstLevel()
unsigned V8PageTableOps4k::firstLevel (uint8_t tsz) const override virtual
Implements PageTableOps.
Definition at line 219 of file smmu_v3_ptops.cc.
References panic.
index()
Addr V8PageTableOps4k::index (Addr va, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 183 of file smmu_v3_ptops.cc.
References bits(), and panic.
isLeaf()
bool V8PageTableOps4k::isLeaf (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 149 of file smmu_v3_ptops.cc.
References panic.
isValid()
bool V8PageTableOps4k::isValid (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 137 of file smmu_v3_ptops.cc.
References panic.
isWritable()
bool V8PageTableOps4k::isWritable (pte_t pte, unsigned level, bool stage2) const override virtual
Implements PageTableOps.
Definition at line 161 of file smmu_v3_ptops.cc.
References bits().
lastLevel()
unsigned V8PageTableOps4k::lastLevel () const override virtual
Implements PageTableOps.
Definition at line 229 of file smmu_v3_ptops.cc.
nextLevelPointer()
Addr V8PageTableOps4k::nextLevelPointer (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 167 of file smmu_v3_ptops.cc.
References V7LPageTableOps::isLeaf(), mbits(), and panic.
pageMask()
Addr V8PageTableOps4k::pageMask (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 195 of file smmu_v3_ptops.cc.
References bits(), ArmISA::mask, and panic.
walkMask()
Addr V8PageTableOps4k::walkMask (unsigned level) const override virtual
Implements PageTableOps.
Definition at line 207 of file smmu_v3_ptops.cc.
References ArmISA::mask, and panic.
The documentation for this struct was generated from the following files:
dev/arm/smmu_v3_ptops.hh
dev/arm/smmu_v3_ptops.cc