gem5: MultiperspectivePerceptron::FilterEntry Struct Reference
MultiperspectivePerceptron::FilterEntry Struct Reference
Entry of the branch filter.
#include <multiperspective_perceptron.hh>
Public Member Functions
FilterEntry ()
bool alwaysNotTakenSoFar () const
Whether this branch has always been observed as not taken.
bool alwaysTakenSoFar () const
Whether this branch has always been observed as taken.
bool neverSeen () const
Whether this branch has been observed before.
Public Attributes
bool seenTaken
Has this branch been taken at least once?
bool seenUntaken
Has this branch been not taken at least once?
Detailed Description
Entry of the branch filter.
Definition at line 143 of file multiperspective_perceptron.hh.
Constructor & Destructor Documentation
FilterEntry()
MultiperspectivePerceptron::FilterEntry::FilterEntry () inline
Definition at line 149 of file multiperspective_perceptron.hh.
Member Function Documentation
alwaysNotTakenSoFar()
bool MultiperspectivePerceptron::FilterEntry::alwaysNotTakenSoFar () const inline
Whether this branch has always been observed as not taken.
Definition at line 152 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::lookup(), and MultiperspectivePerceptron::update().
alwaysTakenSoFar()
bool MultiperspectivePerceptron::FilterEntry::alwaysTakenSoFar () const inline
Whether this branch has always been observed as taken.
Definition at line 156 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::lookup(), and MultiperspectivePerceptron::update().
neverSeen()
bool MultiperspectivePerceptron::FilterEntry::neverSeen () const inline
Whether this branch has been observed before.
Definition at line 160 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::lookup().
Member Data Documentation
seenTaken
bool MultiperspectivePerceptron::FilterEntry::seenTaken
Has this branch been taken at least once?
Definition at line 145 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::update().
seenUntaken
bool MultiperspectivePerceptron::FilterEntry::seenUntaken
Has this branch been not taken at least once?
Definition at line 147 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::update().
The documentation for this struct was generated from the following file:
cpu/pred/multiperspective_perceptron.hh