gem5: PageTableOps Struct Reference
PageTableOps Struct Reference abstract
#include <smmu_v3_ptops.hh>
Public Types
typedef int64_t pte_t
Public Member Functions
virtual bool isValid (pte_t pte, unsigned level) const =0
virtual bool isLeaf (pte_t pte, unsigned level) const =0
virtual bool isWritable (pte_t pte, unsigned level, bool stage2) const =0
virtual Addr nextLevelPointer (pte_t pte, unsigned level) const =0
virtual Addr index (Addr va, unsigned level) const =0
virtual Addr pageMask (pte_t pte, unsigned level) const =0
virtual Addr walkMask (unsigned level) const =0
virtual unsigned firstLevel (uint8_t tsz) const =0
virtual unsigned lastLevel () const =0
Detailed Description
Definition at line 47 of file smmu_v3_ptops.hh.
Member Typedef Documentation
pte_t
typedef int64_t PageTableOps::pte_t
Definition at line 49 of file smmu_v3_ptops.hh.
Member Function Documentation
firstLevel()
virtual unsigned PageTableOps::firstLevel (uint8_t tsz) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::translateStage1And2(), and SMMUTranslationProcess::translateStage2().
index()
virtual Addr PageTableOps::index (Addr va, unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
isLeaf()
virtual bool PageTableOps::isLeaf (pte_t pte, unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
isValid()
virtual bool PageTableOps::isValid (pte_t pte, unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
isWritable()
virtual bool PageTableOps::isWritable (pte_t pte, unsigned level, bool stage2) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
lastLevel()
virtual unsigned PageTableOps::lastLevel () const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::translateStage1And2(), SMMUTranslationProcess::translateStage2(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
nextLevelPointer()
virtual Addr PageTableOps::nextLevelPointer (pte_t pte, unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
pageMask()
virtual Addr PageTableOps::pageMask (pte_t pte, unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
walkMask()
virtual Addr PageTableOps::walkMask (unsigned level) const pure virtual
Implemented in V8PageTableOps64k, V8PageTableOps16k, V8PageTableOps4k, and V7LPageTableOps.
Referenced by SMMUTranslationProcess::walkCacheLookup(), SMMUTranslationProcess::walkStage1And2(), and SMMUTranslationProcess::walkStage2().
The documentation for this struct was generated from the following file:
dev/arm/smmu_v3_ptops.hh