gem5: LinuxAlphaSystem::PrintThreadInfo Struct Reference
LinuxAlphaSystem::PrintThreadInfo Struct Reference
Public Member Functions
PrintThreadInfo (PCEventScope *s, const std::string &desc, Addr addr)
virtual void process (ThreadContext *tc)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 61 of file system.hh.
Constructor & Destructor Documentation
PrintThreadInfo()
LinuxAlphaSystem::PrintThreadInfo::PrintThreadInfo (PCEventScope * s, const std::string & desc, Addr addr) inline
Definition at line 63 of file system.hh.
References LinuxAlphaSystem::SkipDelayLoopEvent::process().
Member Function Documentation
process()
void LinuxAlphaSystem::PrintThreadInfo::process (ThreadContext * tc) virtual
Implements PCEvent.
Definition at line 194 of file system.cc.
References Linux::ThreadInfo::curTaskName(), Linux::ThreadInfo::curTaskPID(), Linux::ThreadInfo::curTaskStart(), DPRINTF, LinuxAlphaSystem::LinuxAlphaSystem(), and MipsISA::ti.
The documentation for this struct was generated from the following files:
arch/alpha/linux/system.hh
arch/alpha/linux/system.cc