gem5: MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo Struct Reference
MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo Struct Reference
Branch information data type.
Public Member Functions
MPPTAGEBranchInfo (Addr pc, int pcshift, bool cond, TAGEBase &tage, LoopPredictor &loopPredictor, StatisticalCorrector &statisticalCorrector)
virtual ~MPPTAGEBranchInfo ()
Public Member Functions inherited from MultiperspectivePerceptron::MPPBranchInfo
MPPBranchInfo (Addr _pc, int pcshift, bool cb)
unsigned int getPC () const
unsigned short int getPC2 () const
unsigned short int getHPC () const
unsigned int getHashFilter (bool last_ghist_bit) const
bool isUnconditional () const
Public Attributes
TAGEBase::BranchInfo * tageBranchInfo
LoopPredictor::BranchInfo * lpBranchInfo
StatisticalCorrector::BranchInfo * scBranchInfo
bool predictedTaken
Public Attributes inherited from MultiperspectivePerceptron::MPPBranchInfo
bool filtered
Whether this branch has been filtered by the prefetcher.
bool prediction
Result of the prediction (true is taken)
int yout
Score of the perceptron.
Detailed Description
Branch information data type.
Definition at line 191 of file multiperspective_perceptron_tage.hh.
Constructor & Destructor Documentation
MPPTAGEBranchInfo()
MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::MPPTAGEBranchInfo (Addr pc, int pcshift, bool cond, TAGEBase & tage, LoopPredictor & loopPredictor, StatisticalCorrector & statisticalCorrector) inline
Definition at line 197 of file multiperspective_perceptron_tage.hh.
~MPPTAGEBranchInfo()
virtual MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::~MPPTAGEBranchInfo () inline virtual
Definition at line 206 of file multiperspective_perceptron_tage.hh.
References PowerISA::bi, MipsISA::index, TAGEBase::init(), MaxAddr, MipsISA::p, MipsISA::pc, TAGEBase::squash(), TAGEBase::update(), and MPP_TAGE::updateHistories().
Member Data Documentation
lpBranchInfo
LoopPredictor::BranchInfo* MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::lpBranchInfo
Definition at line 194 of file multiperspective_perceptron_tage.hh.
Referenced by MultiperspectivePerceptronTAGE::lookup(), and MultiperspectivePerceptronTAGE::update().
predictedTaken
bool MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::predictedTaken
Definition at line 196 of file multiperspective_perceptron_tage.hh.
Referenced by MultiperspectivePerceptronTAGE::lookup(), and MultiperspectivePerceptronTAGE::update().
scBranchInfo
StatisticalCorrector::BranchInfo* MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::scBranchInfo
Definition at line 195 of file multiperspective_perceptron_tage.hh.
Referenced by MultiperspectivePerceptronTAGE::lookup(), and MultiperspectivePerceptronTAGE::update().
tageBranchInfo
TAGEBase::BranchInfo* MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::tageBranchInfo
Definition at line 193 of file multiperspective_perceptron_tage.hh.
Referenced by MultiperspectivePerceptronTAGE::lookup(), and MultiperspectivePerceptronTAGE::update().
The documentation for this struct was generated from the following file:
cpu/pred/multiperspective_perceptron_tage.hh