gem5: Net::Ip6Hdr Struct Reference
Net::Ip6Hdr Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t version () const
uint32_t flow () const
uint16_t plen () const
uint16_t hlen () const
uint8_t nxt () const
uint8_t hlim () const
const uint8_t * src () const
const uint8_t * dst () const
int extensionLength () const
const Ip6Opt * getExt (uint8_t ext) const
const Ip6Opt * fragmentExt () const
const Ip6Opt * rtTypeExt () const
const Ip6Opt * dstOptExt () const
uint8_t proto () const
void plen (uint16_t _plen)
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 364 of file inet.hh.
Member Function Documentation
bytes() [1/2]
const uint8_t* Net::Ip6Hdr::bytes () const inline
Definition at line 386 of file inet.hh.
bytes() [2/2]
uint8_t* Net::Ip6Hdr::bytes () inline
Definition at line 389 of file inet.hh.
dst()
const uint8_t* Net::Ip6Hdr::dst () const inline
Definition at line 374 of file inet.hh.
References ArmISA::ext.
dstOptExt()
const Ip6Opt* Net::Ip6Hdr::dstOptExt () const inline
Definition at line 380 of file inet.hh.
extensionLength()
int Net::Ip6Hdr::extensionLength () const
Definition at line 293 of file inet.cc.
References data, ArmISA::ext, IP6_EXTENSION, ArmISA::len, Net::Ip6Opt::len(), and Net::Ip6Opt::nxt().
Referenced by Net::__tu_cksum6().
flow()
uint32_t Net::Ip6Hdr::flow () const inline
Definition at line 367 of file inet.hh.
fragmentExt()
const Ip6Opt* Net::Ip6Hdr::fragmentExt () const inline
Definition at line 378 of file inet.hh.
getExt()
const Ip6Opt * Net::Ip6Hdr::getExt (uint8_t ext) const
Definition at line 316 of file inet.cc.
References data, IP6_EXTENSION, Net::Ip6Opt::len(), and Net::Ip6Opt::nxt().
hlen()
uint16_t Net::Ip6Hdr::hlen () const inline
Definition at line 369 of file inet.hh.
hlim()
uint8_t Net::Ip6Hdr::hlim () const inline
Definition at line 371 of file inet.hh.
nxt()
uint8_t Net::Ip6Hdr::nxt () const inline
Definition at line 370 of file inet.hh.
payload() [1/2]
const uint8_t* Net::Ip6Hdr::payload () const inline
Definition at line 387 of file inet.hh.
References Net::EthAddr::bytes().
Referenced by Net::__tu_cksum6().
payload() [2/2]
uint8_t* Net::Ip6Hdr::payload () inline
Definition at line 390 of file inet.hh.
References Net::EthAddr::bytes().
plen() [1/2]
uint16_t Net::Ip6Hdr::plen () const inline
Definition at line 368 of file inet.hh.
Referenced by Net::__tu_cksum6(), and IGbE::TxDescCache::pktComplete().
plen() [2/2]
void Net::Ip6Hdr::plen (uint16_t _plen) inline
Definition at line 383 of file inet.hh.
proto()
uint8_t Net::Ip6Hdr::proto () const
Definition at line 342 of file inet.cc.
References data, ArmISA::ext, IP6_EXTENSION, Net::Ip6Opt::len(), and Net::Ip6Opt::nxt().
Referenced by Net::__tu_cksum6().
rtTypeExt()
const Ip6Opt* Net::Ip6Hdr::rtTypeExt () const inline
Definition at line 379 of file inet.hh.
size()
int Net::Ip6Hdr::size () const inline
Definition at line 385 of file inet.hh.
src()
const uint8_t* Net::Ip6Hdr::src () const inline
Definition at line 373 of file inet.hh.
Referenced by Net::__tu_cksum6().
version()
uint8_t Net::Ip6Hdr::version () const inline
Definition at line 366 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc