gem5: SBOOEPrefetcher::Sandbox Struct Reference
SBOOEPrefetcher::Sandbox Struct Reference
Public Member Functions
Sandbox (unsigned int max_entries, int _stride)
void insert (Addr line, Tick tick)
Insert the line address being accessed to the cache into the FIFO queue of the sandbox.
unsigned int score () const
Calculate the useful score.
Public Attributes
std::vector< SandboxEntry > entries
FIFO queue.
unsigned int sandboxScore
Accesses during the eval period that were present in the sandbox.
unsigned int lateScore
Hits in the sandbox that wouldn't have been filled on time.
unsigned int index
Index of the oldest entry in the FIFO.
const int stride
Sequential stride for this prefetcher.
Detailed Description
Definition at line 94 of file sbooe.hh.
Constructor & Destructor Documentation
Sandbox()
SBOOEPrefetcher::Sandbox::Sandbox (unsigned int max_entries, int _stride) inline
Definition at line 109 of file sbooe.hh.
References QueuedPrefetcher::insert(), SBOOEPrefetcher::SandboxEntry::line, and Clocked::tick.
Member Function Documentation
insert()
void SBOOEPrefetcher::Sandbox::insert (Addr line, Tick tick)
Insert the line address being accessed to the cache into the FIFO queue of the sandbox.
Parameters
line Line address being accessed
tick Tick in which the access is expected to be filled
Definition at line 57 of file sbooe.cc.
References MipsISA::index, ArmISA::stride, and Clocked::tick.
score()
unsigned int SBOOEPrefetcher::Sandbox::score () const inline
Calculate the useful score.
Returns
Useful score of the sandbox. Sandbox score adjusted by by the late score
Definition at line 127 of file sbooe.hh.
Referenced by SBOOEPrefetcher::access(), and SBOOEPrefetcher::calculatePrefetch().
Member Data Documentation
entries
std::vector<SandboxEntry> SBOOEPrefetcher::Sandbox::entries
FIFO queue.
Max entries is 'sandboxEntries'
Definition at line 96 of file sbooe.hh.
index
unsigned int SBOOEPrefetcher::Sandbox::index
Index of the oldest entry in the FIFO.
Definition at line 105 of file sbooe.hh.
lateScore
unsigned int SBOOEPrefetcher::Sandbox::lateScore
Hits in the sandbox that wouldn't have been filled on time.
Definition at line 103 of file sbooe.hh.
sandboxScore
unsigned int SBOOEPrefetcher::Sandbox::sandboxScore
Accesses during the eval period that were present in the sandbox.
Definition at line 101 of file sbooe.hh.
stride
const int SBOOEPrefetcher::Sandbox::stride
Sequential stride for this prefetcher.
Definition at line 107 of file sbooe.hh.
Referenced by SBOOEPrefetcher::calculatePrefetch().
The documentation for this struct was generated from the following files:
mem/cache/prefetch/sbooe.hh
mem/cache/prefetch/sbooe.cc