gem5: QueuedPrefetcher::DeferredPacket Struct Reference
QueuedPrefetcher::DeferredPacket Struct Reference
#include <queued.hh>
Public Member Functions
DeferredPacket (QueuedPrefetcher *o, PrefetchInfo const &pfi, Tick t, int32_t prio)
Constructor.
bool operator> (const DeferredPacket &that) const
bool operator< (const DeferredPacket &that) const
bool operator<= (const DeferredPacket &that) const
void createPkt (Addr paddr, unsigned blk_size, MasterID mid, bool tag_prefetch, Tick t)
Create the associated memory packet.
void setTranslationRequest (const RequestPtr &req)
Sets the translation request needed to obtain the physical address of this request.
void markDelayed () override
Signal that the translation has been delayed due to a hw page table walk.
void finish (const Fault &fault, const RequestPtr &req, ThreadContext *tc, BaseTLB::Mode mode) override
void startTranslation (BaseTLB *tlb)
Issues the translation request to the provided TLB.
Public Member Functions inherited from BaseTLB::Translation
virtual ~Translation ()
virtual bool squashed () const
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
Public Attributes
QueuedPrefetcher * owner
Owner of the packet.
PrefetchInfo pfInfo
Prefetch info corresponding to this packet.
Tick tick
Time when this prefetch becomes ready.
PacketPtr pkt
The memory packet generated by this prefetch.
int32_t priority
The priority of this prefetch.
RequestPtr translationRequest
Request used when a translation is needed.
ThreadContext * tc
bool ongoingTranslation
Detailed Description
Definition at line 57 of file queued.hh.
Constructor & Destructor Documentation
DeferredPacket()
QueuedPrefetcher::DeferredPacket::DeferredPacket (QueuedPrefetcher * o, PrefetchInfo const & pfi, Tick t, int32_t prio) inline
Constructor.
Parameters
o QueuedPrefetcher in charge of this request
pfi PrefechInfo object associated to this packet
t Time when this prefetch becomes ready
p PacketPtr with the memory request of the prefetch
prio This prefetch priority
Definition at line 81 of file queued.hh.
Member Function Documentation
createPkt()
void QueuedPrefetcher::DeferredPacket::createPkt (Addr paddr, unsigned blk_size, MasterID mid, bool tag_prefetch, Tick t)
Create the associated memory packet.
Parameters
paddr physical address of this packet
blk_size block size used by the prefetcher
mid Requester ID of the access that generated this prefetch
tag_prefetch flag to indicate if the packet needs to be tagged
t time when the prefetch becomes ready
Definition at line 53 of file queued.cc.
References Packet::allocate(), BasePrefetcher::PrefetchInfo::getPC(), MemCmd::HardPFReq, BasePrefetcher::PrefetchInfo::hasPC(), BasePrefetcher::PrefetchInfo::isSecure(), pfInfo, pkt, ContextSwitchTaskId::Prefetcher, Packet::req, Request::SECURE, ArmISA::t, and tick.
Referenced by QueuedPrefetcher::insert(), and operator<=().
finish()
void QueuedPrefetcher::DeferredPacket::finish (const Fault & fault, const RequestPtr & req, ThreadContext * tc, BaseTLB::Mode mode) override virtual
Implements BaseTLB::Translation.
Definition at line 84 of file queued.cc.
References NoFault, ongoingTranslation, owner, and QueuedPrefetcher::translationComplete().
Referenced by markDelayed().
markDelayed()
void QueuedPrefetcher::DeferredPacket::markDelayed () inline override virtual
Signal that the translation has been delayed due to a hw page table walk.
Implements BaseTLB::Translation.
Definition at line 122 of file queued.hh.
References finish(), ArmISA::mode, startTranslation(), and BasePrefetcher::tlb.
operator<()
bool QueuedPrefetcher::DeferredPacket::operator< (const DeferredPacket & that) const inline
Definition at line 91 of file queued.hh.
References priority.
operator<=()
bool QueuedPrefetcher::DeferredPacket::operator<= (const DeferredPacket & that) const inline
Definition at line 95 of file queued.hh.
References createPkt(), and ArmISA::t.
operator>()
bool QueuedPrefetcher::DeferredPacket::operator> (const DeferredPacket & that) const inline
Definition at line 87 of file queued.hh.
References priority.
setTranslationRequest()
void QueuedPrefetcher::DeferredPacket::setTranslationRequest (const RequestPtr & req) inline
Sets the translation request needed to obtain the physical address of this request.
Parameters
req The Request with the virtual address of this request
Definition at line 117 of file queued.hh.
Referenced by QueuedPrefetcher::insert().
startTranslation()
void QueuedPrefetcher::DeferredPacket::startTranslation (BaseTLB * tlb)
Issues the translation request to the provided TLB.
Parameters
tlb the tlb that has to translate the address
Definition at line 73 of file queued.cc.
References ongoingTranslation, BaseTLB::Read, tc, BaseTLB::translateTiming(), and translationRequest.
Referenced by markDelayed(), and QueuedPrefetcher::processMissingTranslations().
Member Data Documentation
ongoingTranslation
bool QueuedPrefetcher::DeferredPacket::ongoingTranslation
Definition at line 71 of file queued.hh.
Referenced by finish(), and startTranslation().
owner
QueuedPrefetcher* QueuedPrefetcher::DeferredPacket::owner
Owner of the packet.
Definition at line 59 of file queued.hh.
Referenced by finish().
pfInfo
PrefetchInfo QueuedPrefetcher::DeferredPacket::pfInfo
Prefetch info corresponding to this packet.
Definition at line 61 of file queued.hh.
Referenced by createPkt().
pkt
PacketPtr QueuedPrefetcher::DeferredPacket::pkt
The memory packet generated by this prefetch.
Definition at line 65 of file queued.hh.
Referenced by createPkt(), and QueuedPrefetcher::nextPrefetchReadyTime().
priority
int32_t QueuedPrefetcher::DeferredPacket::priority
The priority of this prefetch.
Definition at line 67 of file queued.hh.
Referenced by QueuedPrefetcher::nextPrefetchReadyTime(), operator<(), and operator>().
tc
ThreadContext* QueuedPrefetcher::DeferredPacket::tc
Definition at line 70 of file queued.hh.
Referenced by QueuedPrefetcher::insert(), and startTranslation().
tick
Tick QueuedPrefetcher::DeferredPacket::tick
Time when this prefetch becomes ready.
Definition at line 63 of file queued.hh.
Referenced by createPkt().
translationRequest
RequestPtr QueuedPrefetcher::DeferredPacket::translationRequest
Request used when a translation is needed.
Definition at line 69 of file queued.hh.
Referenced by startTranslation().
The documentation for this struct was generated from the following files:
mem/cache/prefetch/queued.hh
mem/cache/prefetch/queued.cc