gem5: sc_gem5::ListNode Struct Reference
sc_gem5::ListNode Struct Reference
#include <list.hh>
Public Member Functions
ListNode ()
virtual ~ListNode ()
void popListNode ()
Public Attributes
ListNode * nextListNode
ListNode * prevListNode
Detailed Description
Definition at line 44 of file list.hh.
Constructor & Destructor Documentation
ListNode()
sc_gem5::ListNode::ListNode () inline
Definition at line 46 of file list.hh.
~ListNode()
virtual sc_gem5::ListNode::~ListNode () inline virtual
Definition at line 47 of file list.hh.
Member Function Documentation
popListNode()
void sc_gem5::ListNode::popListNode () inline
Definition at line 53 of file list.hh.
References nextListNode, and prevListNode.
Referenced by sc_gem5::Scheduler::clear(), sc_gem5::CThread::CThread(), sc_gem5::Scheduler::runUpdate(), sc_gem5::Scheduler::suspend(), sc_gem5::Scheduler::yield(), sc_gem5::Channel::~Channel(), and sc_gem5::ClockTick::~ClockTick().
Member Data Documentation
nextListNode
ListNode* sc_gem5::ListNode::nextListNode
Definition at line 49 of file list.hh.
Referenced by sc_gem5::NodeList< Process >::getNext(), sc_gem5::listContains(), sc_gem5::NodeList< Process >::NodeList(), popListNode(), sc_gem5::NodeList< Process >::pushFirst(), sc_gem5::NodeList< Process >::pushLast(), and sc_gem5::Scheduler::suspend().
prevListNode
ListNode* sc_gem5::ListNode::prevListNode
Definition at line 50 of file list.hh.
Referenced by sc_gem5::NodeList< Process >::NodeList(), popListNode(), sc_gem5::NodeList< Process >::pushFirst(), and sc_gem5::NodeList< Process >::pushLast().
The documentation for this struct was generated from the following file:
systemc/core/list.hh