gem5: Net::TcpOpt Struct Reference
Net::TcpOpt Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t type () const
uint8_t len () const
bool isopt (int opt) const
const uint8_t * data () const
uint16_t mss () const
uint8_t wscale () const
uint32_t echo () const
uint32_t tsval () const
uint32_t tsecr () const
uint32_t cc () const
uint8_t cksum () const
const uint8_t * md5 () const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 586 of file inet.hh.
Member Function Documentation
bytes() [1/2]
const uint8_t* Net::TcpOpt::bytes () const inline
Definition at line 605 of file inet.hh.
bytes() [2/2]
uint8_t* Net::TcpOpt::bytes () inline
Definition at line 607 of file inet.hh.
cc()
uint32_t Net::TcpOpt::cc () const inline
Definition at line 600 of file inet.hh.
cksum()
uint8_t Net::TcpOpt::cksum () const inline
Definition at line 601 of file inet.hh.
data()
const uint8_t* Net::TcpOpt::data () const inline
Definition at line 593 of file inet.hh.
echo()
uint32_t Net::TcpOpt::echo () const inline
Definition at line 597 of file inet.hh.
isopt()
bool Net::TcpOpt::isopt (int opt) const inline
Definition at line 591 of file inet.hh.
References type.
len()
uint8_t Net::TcpOpt::len () const inline
Definition at line 589 of file inet.hh.
References type.
Referenced by Net::TcpHdr::options().
md5()
const uint8_t* Net::TcpOpt::md5 () const inline
Definition at line 602 of file inet.hh.
mss()
uint16_t Net::TcpOpt::mss () const inline
Definition at line 595 of file inet.hh.
payload() [1/2]
const uint8_t* Net::TcpOpt::payload () const inline
Definition at line 606 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
payload() [2/2]
uint8_t* Net::TcpOpt::payload () inline
Definition at line 608 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
size()
int Net::TcpOpt::size () const inline
Definition at line 604 of file inet.hh.
References ArmISA::len.
tsecr()
uint32_t Net::TcpOpt::tsecr () const inline
Definition at line 599 of file inet.hh.
tsval()
uint32_t Net::TcpOpt::tsval () const inline
Definition at line 598 of file inet.hh.
type()
uint8_t Net::TcpOpt::type () const inline
Definition at line 588 of file inet.hh.
wscale()
uint8_t Net::TcpOpt::wscale () const inline
Definition at line 596 of file inet.hh.
The documentation for this struct was generated from the following file:
base/inet.hh