gem5: AlphaISA::VAddr Struct Reference
AlphaISA::VAddr Struct Reference
#include <pagetable.hh>
Public Member Functions
VAddr (Addr a)
operator Addr () const
const VAddr & operator= (Addr a)
Addr vpn () const
Addr page () const
Addr offset () const
Addr level3 () const
Addr level2 () const
Addr level1 () const
Public Attributes
Addr addr
Static Public Attributes
static const int ImplBits = 43
static const Addr ImplMask = (ULL(1) << ImplBits) - 1
static const Addr UnImplMask = ~ImplMask
Detailed Description
Definition at line 40 of file pagetable.hh.
Constructor & Destructor Documentation
VAddr()
AlphaISA::VAddr::VAddr (Addr a) inline
Definition at line 48 of file pagetable.hh.
Member Function Documentation
level1()
Addr AlphaISA::VAddr::level1 () const inline
Definition at line 60 of file pagetable.hh.
References AlphaISA::NPtePageShift, AlphaISA::PageShift, and AlphaISA::PteAddr().
Referenced by AlphaISA::kernel_pte_lookup().
level2()
Addr AlphaISA::VAddr::level2 () const inline
Definition at line 58 of file pagetable.hh.
References AlphaISA::NPtePageShift, AlphaISA::PageShift, and AlphaISA::PteAddr().
Referenced by AlphaISA::kernel_pte_lookup().
level3()
Addr AlphaISA::VAddr::level3 () const inline
Definition at line 56 of file pagetable.hh.
References AlphaISA::PageShift, and AlphaISA::PteAddr().
Referenced by AlphaISA::kernel_pte_lookup().
offset()
Addr AlphaISA::VAddr::offset () const inline
Definition at line 54 of file pagetable.hh.
References AlphaISA::PageOffset.
Referenced by AlphaISA::vtophys().
operator Addr()
AlphaISA::VAddr::operator Addr () const inline
Definition at line 49 of file pagetable.hh.
References addr.
operator=()
const VAddr& AlphaISA::VAddr::operator= (Addr a) inline
Definition at line 50 of file pagetable.hh.
References X86ISA::a.
page()
Addr AlphaISA::VAddr::page () const inline
Definition at line 53 of file pagetable.hh.
References AlphaISA::PageMask.
Referenced by AlphaISA::ItbPageFault::invoke().
vpn()
Addr AlphaISA::VAddr::vpn () const inline
Definition at line 52 of file pagetable.hh.
References AlphaISA::PageShift.
Referenced by AlphaISA::TLB::flushAddr(), AlphaISA::TLB::insert(), AlphaISA::ItbFault::invoke(), AlphaISA::TlbEntry::TlbEntry(), and AlphaISA::TlbEntry::updateVaddr().
Member Data Documentation
addr
Addr AlphaISA::VAddr::addr
Definition at line 46 of file pagetable.hh.
Referenced by operator Addr().
ImplBits
const int AlphaISA::VAddr::ImplBits = 43 static
Definition at line 42 of file pagetable.hh.
ImplMask
const Addr AlphaISA::VAddr::ImplMask = (ULL(1) << ImplBits) - 1 static
Definition at line 43 of file pagetable.hh.
UnImplMask
const Addr AlphaISA::VAddr::UnImplMask = ~ImplMask static
Definition at line 44 of file pagetable.hh.
The documentation for this struct was generated from the following file:
arch/alpha/pagetable.hh