gem5: V7LPageTableOps Struct Reference
V7LPageTableOps Struct Reference
#include <smmu_v3_ptops.hh>
Public Member Functions
bool isValid (pte_t pte, unsigned level) const override
bool isLeaf (pte_t pte, unsigned level) const override
bool isWritable (pte_t pte, unsigned level, bool stage2) const override
Addr nextLevelPointer (pte_t pte, unsigned level) const override
Addr index (Addr va, unsigned level) const override
Addr pageMask (pte_t pte, unsigned level) const override
Addr walkMask (unsigned level) const override
unsigned firstLevel (uint8_t tsz) const override
unsigned lastLevel () const override
Additional Inherited Members
Public Types inherited from PageTableOps
typedef int64_t pte_t
Detailed Description
Definition at line 62 of file smmu_v3_ptops.hh.
Member Function Documentation
firstLevel()
unsigned V7LPageTableOps::firstLevel (uint8_t tsz) const override virtual
Implements PageTableOps.
Definition at line 125 of file smmu_v3_ptops.cc.
index()
Addr V7LPageTableOps::index (Addr va, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 89 of file smmu_v3_ptops.cc.
References bits(), ArmISA::n, and panic.
isLeaf()
bool V7LPageTableOps::isLeaf (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 57 of file smmu_v3_ptops.cc.
References panic.
Referenced by nextLevelPointer(), V8PageTableOps4k::nextLevelPointer(), V8PageTableOps16k::nextLevelPointer(), and V8PageTableOps64k::nextLevelPointer().
isValid()
bool V7LPageTableOps::isValid (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 46 of file smmu_v3_ptops.cc.
References panic.
isWritable()
bool V7LPageTableOps::isWritable (pte_t pte, unsigned level, bool stage2) const override virtual
Implements PageTableOps.
Definition at line 68 of file smmu_v3_ptops.cc.
References bits().
lastLevel()
unsigned V7LPageTableOps::lastLevel () const override virtual
Implements PageTableOps.
Definition at line 131 of file smmu_v3_ptops.cc.
nextLevelPointer()
Addr V7LPageTableOps::nextLevelPointer (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 74 of file smmu_v3_ptops.cc.
References isLeaf(), mbits(), and panic.
pageMask()
Addr V7LPageTableOps::pageMask (pte_t pte, unsigned level) const override virtual
Implements PageTableOps.
Definition at line 103 of file smmu_v3_ptops.cc.
References bits(), ArmISA::mask, and panic.
walkMask()
Addr V7LPageTableOps::walkMask (unsigned level) const override virtual
Implements PageTableOps.
Definition at line 114 of file smmu_v3_ptops.cc.
References ArmISA::mask, and panic.
The documentation for this struct was generated from the following files:
dev/arm/smmu_v3_ptops.hh
dev/arm/smmu_v3_ptops.cc