gem5: unittest/symtest.cc File Reference
symtest.cc File Reference
#include <iostream>
#include "base/loader/symtab.hh"
#include "base/str.hh"
Functions
void usage (const char *progname)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 49 of file symtest.cc.
References X86ISA::exit, SymbolTable::findAddress(), SymbolTable::findSymbol(), SymbolTable::load(), to_number(), and usage().
usage()
void usage (const char * progname)
Definition at line 41 of file symtest.cc.
References X86ISA::exit.
Referenced by main(), and procInfo().