gem5: sim/syscall_desc.hh File Reference
syscall_desc.hh File Reference
#include <string>
#include "base/types.hh"
Classes
class SyscallDesc
This class provides the wrapper interface for the system call implementations which are defined in the sim/syscall_emul files and bound to the ISAs in the architecture specific code (i.e.
Functions
SyscallReturn unimplementedFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Function Documentation
unimplementedFunc()
SyscallReturn unimplementedFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 67 of file syscall_emul.cc.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().