gem5: sim/syscall_emul.cc File Reference
syscall_emul.cc File Reference
#include "sim/syscall_emul.hh"
#include <fcntl.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <csignal>
#include <iostream>
#include <mutex>
#include <string>
#include "arch/utility.hh"
#include "base/chunk_generator.hh"
#include "base/trace.hh"
#include "config/the_isa.hh"
#include "cpu/thread_context.hh"
#include "dev/net/dist_iface.hh"
#include "mem/page_table.hh"
#include "sim/byteswap.hh"
#include "sim/process.hh"
#include "sim/sim_exit.hh"
#include "sim/syscall_debug_macros.hh"
#include "sim/syscall_desc.hh"
#include "sim/system.hh"
Functions
void warnUnsupportedOS (std::string syscall_name)
SyscallReturn unimplementedFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Handler for unimplemented syscalls that we haven't thought about.
SyscallReturn ignoreFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.) and should not affect the correct behavior of the program.
static void exitFutexWake (ThreadContext *tc, Addr addr, uint64_t tgid)
static SyscallReturn exitImpl (SyscallDesc *desc, int callnum, ThreadContext *tc, bool group)
SyscallReturn exitFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target exit() handler: terminate current context.
SyscallReturn exitGroupFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target exit_group() handler: terminate simulation. (exit all threads)
SyscallReturn getpagesizeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getpagesize() handler.
SyscallReturn brkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target brk() handler: set brk address.
SyscallReturn setTidAddressFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target set_tid_address() handler.
SyscallReturn closeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target close() handler.
SyscallReturn lseekFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target lseek() handler.
SyscallReturn _llseekFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target _llseek() handler.
SyscallReturn munmapFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target munmap() handler.
SyscallReturn gethostnameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target gethostname() handler.
SyscallReturn getcwdFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getcwd() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc, int index)
Target readlink() handler.
SyscallReturn unlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn unlinkHelper (SyscallDesc *desc, int num, ThreadContext *tc, int index)
Target unlink() handler.
SyscallReturn linkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target link() handler.
SyscallReturn symlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target symlink() handler.
SyscallReturn mkdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target mkdir() handler.
SyscallReturn renameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target rename() handler.
SyscallReturn truncateFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target truncate() handler.
SyscallReturn ftruncateFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target ftruncate() handler.
SyscallReturn truncate64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target truncate64() handler.
SyscallReturn ftruncate64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target ftruncate64() handler.
SyscallReturn umaskFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target umask() handler.
SyscallReturn chownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target chown() handler.
SyscallReturn fchownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target fchown() handler.
SyscallReturn dupFunc (SyscallDesc *desc, int num, ThreadContext *tc)
FIXME: The file description is not shared among file descriptors created with dup.
SyscallReturn dup2Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target dup2() handler.
SyscallReturn fcntlFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target fcntl() handler.
SyscallReturn fcntl64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target fcntl64() handler.
SyscallReturn pipeImpl (SyscallDesc *desc, int callnum, ThreadContext *tc, bool pseudo_pipe, bool is_pipe2)
Internal pipe() handler.
SyscallReturn pipePseudoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
SyscallReturn pipeFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target pipe() handler.
SyscallReturn pipe2Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target pipe() handler.
SyscallReturn getpgrpFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getpgrpFunc() handler.
SyscallReturn setpgidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target setpgid() handler.
SyscallReturn getpidPseudoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getpidPseudo() handler.
SyscallReturn getuidPseudoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getuidPseudo() handler.
SyscallReturn getgidPseudoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getgidPseudo() handler.
SyscallReturn setuidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target setuid() handler.
SyscallReturn getpidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getpid() handler.
SyscallReturn gettidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target gettid() handler.
SyscallReturn getppidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getppid() handler.
SyscallReturn getuidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
SyscallReturn geteuidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target geteuid() handler.
SyscallReturn getgidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getgid() handler.
SyscallReturn getegidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getegid() handler.
SyscallReturn fallocateFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
SyscallReturn accessFunc (SyscallDesc *desc, int callnum, ThreadContext *tc, int index)
SyscallReturn accessFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target access() handler.
SyscallReturn mknodFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target mknod() handler.
SyscallReturn chdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target chdir() handler.
SyscallReturn rmdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn shutdownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target shutdown() handler.
SyscallReturn bindFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn listenFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn connectFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn recvfromFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn sendtoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn recvmsgFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn sendmsgFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getsockoptFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getsocknameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getpeernameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn setsockoptFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Variables
const char * hostname = "m5.eecs.umich.edu"
Function Documentation
_llseekFunc()
SyscallReturn _llseekFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target _llseek() handler.
Definition at line 332 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), System::getGuestByteOrder(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, ArmISA::offset, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), and unameFunc().
accessFunc() [1/2]
SyscallReturn accessFunc (SyscallDesc * desc, int callnum, ThreadContext * tc, int index)
Definition at line 1150 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
Referenced by accessFunc(), and unameFunc32().
accessFunc() [2/2]
SyscallReturn accessFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target access() handler.
Definition at line 1167 of file syscall_emul.cc.
References accessFunc().
Referenced by faccessatFunc().
bindFunc()
SyscallReturn bindFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1327 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::status.
brkFunc()
SyscallReturn brkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target brk() handler: set brk address.
Definition at line 242 of file syscall_emul.cc.
References ChunkGenerator::done(), DPRINTF_SYSCALL, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, PortProxy::memsetBlob(), MipsISA::p, AlphaISA::PageBytes, roundDown(), and roundUp().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
chdirFunc()
SyscallReturn chdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target chdir() handler.
Definition at line 1190 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, startswith(), and PortProxy::tryReadString().
chownFunc()
SyscallReturn chownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target chown() handler.
Definition at line 688 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
closeFunc()
SyscallReturn closeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target close() handler.
Definition at line 302 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
connectFunc()
SyscallReturn connectFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1369 of file syscall_emul.cc.
References addr, BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::status.
dup2Func()
SyscallReturn dup2Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target dup2() handler.
We need a valid host file descriptor number to be able to pass into the second parameter for dup2 (newfd), but we don't know what the viable numbers are; we execute the open call to retrieve one.
Definition at line 761 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by unameFunc32().
dupFunc()
SyscallReturn dupFunc (SyscallDesc * desc, int num, ThreadContext * tc)
FIXME: The file description is not shared among file descriptors created with dup.
Target dup() handler.
Really, it's difficult to maintain fields like file offset or flags since an update to such a field won't be reflected in the metadata for the fd entries that we maintain for checkpoint restoration.
Definition at line 739 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), unameFunc(), and unameFunc32().
exitFunc()
SyscallReturn exitFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target exit() handler: terminate current context.
Definition at line 223 of file syscall_emul.cc.
References exitImpl().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
exitFutexWake()
static void exitFutexWake (ThreadContext * tc, Addr addr, uint64_t tgid) static
Definition at line 87 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), System::futexMap, ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), and FutexMap::wakeup().
Referenced by exitImpl().
exitGroupFunc()
SyscallReturn exitGroupFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target exit_group() handler: terminate simulation. (exit all threads)
Definition at line 229 of file syscall_emul.cc.
References exitImpl().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), tgkillFunc(), unameFunc(), and unameFunc32().
exitImpl()
static SyscallReturn exitImpl (SyscallDesc * desc, int callnum, ThreadContext * tc, bool group) static
Threads in a thread group require special handing. For instance, we send the SIGCHLD signal so that it appears that it came from the head of the group. We also only delete file descriptors if we are the last thread in the thread group.
Check if we share thread group with the pointer; this denotes that we are not the last thread active in the thread group. Note that setting this to false also prevents further iterations of the loop.
If p is trying to exit_group and both walk and p are in the same thread group (i.e., sharing the same tgid), we need to halt walk's thread context. After all threads except p are halted, p becomes the last thread in the group.
If p is not doing exit_group and there exists another active thread context in the group, last_thread is set to false to prevent the parent thread from killing all threads in the group.
A corner case exists which involves execve(). After execve(), the execve will enable SIGCHLD in the process. The problem occurs when the exiting process is the root process in the system; there is no parent to receive the signal. We obviate this problem by setting the root process' ppid to zero in the Python configuration files. We really should handle the root/execve specific case more gracefully.
Run though FD array of the exiting process and close all file descriptors except for the standard file descriptors. (The standard file descriptors are shared with gem5.)
check to see if there is no more active thread in the system. If so, exit the simulation loop
Even though we are terminating the final thread context, dist-gem5 requires the simulation to remain active and provide synchronization messages to the switch process. So we just halt the last thread context and return. The simulation will be terminated by dist-gem5 in a coordinated manner once all nodes have signaled their readiness to exit. For non dist-gem5 simulations, readyToExit() always returns true.
Definition at line 101 of file syscall_emul.cc.
References exitFutexWake(), exitSimLoop(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::halt(), ThreadContext::Halted, ThreadContext::Halting, ArmISA::i, MipsISA::index, System::numContexts(), MipsISA::p, Process::pid(), DistIface::readyToExit(), System::signalList, ArmISA::status, X86ISA::system, System::systemList, Process::tgid(), and System::threadContexts.
Referenced by exitFunc(), and exitGroupFunc().
fallocateFunc()
SyscallReturn fallocateFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Definition at line 1124 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, ArmISA::len, ArmISA::mode, ArmISA::offset, MipsISA::p, and warnUnsupportedOS().
Referenced by unameFunc32().
fchownFunc()
SyscallReturn fchownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target fchown() handler.
Definition at line 711 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
fcntl64Func()
SyscallReturn fcntl64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target fcntl64() handler.
Definition at line 837 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and warn.
Referenced by setThreadAreaFunc(), unameFunc(), and unameFunc32().
fcntlFunc()
SyscallReturn fcntlFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target fcntl() handler.
Definition at line 792 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and warn.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
ftruncate64Func()
SyscallReturn ftruncate64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target ftruncate64() handler.
Definition at line 656 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, length, and MipsISA::p.
Referenced by unameFunc(), and unameFunc32().
ftruncateFunc()
SyscallReturn ftruncateFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target ftruncate() handler.
Definition at line 614 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, length, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getcwdFunc()
SyscallReturn getcwdFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getcwd() handler.
Definition at line 391 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
getegidFunc()
SyscallReturn getegidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getegid() handler.
Definition at line 1117 of file syscall_emul.cc.
References Process::egid(), and ThreadContext::getProcessPtr().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
geteuidFunc()
SyscallReturn geteuidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target geteuid() handler.
Definition at line 1103 of file syscall_emul.cc.
References Process::euid(), and ThreadContext::getProcessPtr().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getgidFunc()
SyscallReturn getgidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getgid() handler.
Definition at line 1110 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::gid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getgidPseudoFunc()
SyscallReturn getgidPseudoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getgidPseudo() handler.
Definition at line 1055 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
gethostnameFunc()
SyscallReturn gethostnameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target gethostname() handler.
Definition at line 375 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), hostname, MipsISA::index, name(), and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
getpagesizeFunc()
SyscallReturn getpagesizeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getpagesize() handler.
Definition at line 235 of file syscall_emul.cc.
References AlphaISA::PageBytes.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
getpeernameFunc()
SyscallReturn getpeernameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1789 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
getpgrpFunc()
SyscallReturn getpgrpFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getpgrpFunc() handler.
Definition at line 986 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::pgid().
getpidFunc()
SyscallReturn getpidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getpid() handler.
Definition at line 1075 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::tgid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getpidPseudoFunc()
SyscallReturn getpidPseudoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getpidPseudo() handler.
Definition at line 1029 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
getppidFunc()
SyscallReturn getppidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getppid() handler.
Definition at line 1089 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::ppid().
Referenced by SparcISA::getresuidFunc(), and unameFunc32().
getsocknameFunc()
SyscallReturn getsocknameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1749 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, MipsISA::p, ArmISA::sa, and ArmISA::status.
getsockoptFunc()
SyscallReturn getsockoptFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1706 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, X86ISA::level, MipsISA::p, ArmISA::status, and X86ISA::val.
gettidFunc()
SyscallReturn gettidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target gettid() handler.
Definition at line 1082 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::pid().
Referenced by unameFunc32().
getuidFunc()
SyscallReturn getuidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Definition at line 1096 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::uid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getuidPseudoFunc()
SyscallReturn getuidPseudoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getuidPseudo() handler.
Definition at line 1042 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
ignoreFunc()
SyscallReturn ignoreFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.) and should not affect the correct behavior of the program.
Print a warning only if the appropriate trace flag is enabled. Return success to the target program.
Definition at line 76 of file syscall_emul.cc.
References SyscallDesc::name(), SyscallDesc::needWarning(), warn, and SyscallDesc::warnOnce().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
linkFunc()
SyscallReturn linkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target link() handler.
Definition at line 510 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
listenFunc()
SyscallReturn listenFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1351 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and ArmISA::status.
lseekFunc()
SyscallReturn lseekFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target lseek() handler.
Definition at line 312 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
mkdirFunc()
SyscallReturn mkdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target mkdir() handler.
Definition at line 552 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
mknodFunc()
SyscallReturn mknodFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target mknod() handler.
Definition at line 1173 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
munmapFunc()
SyscallReturn munmapFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target munmap() handler.
Definition at line 363 of file syscall_emul.cc.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
pipe2Func()
SyscallReturn pipe2Func (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target pipe() handler.
Definition at line 978 of file syscall_emul.cc.
References pipeImpl().
pipeFunc()
SyscallReturn pipeFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target pipe() handler.
Definition at line 972 of file syscall_emul.cc.
References pipeImpl().
Referenced by unameFunc32().
pipeImpl()
SyscallReturn pipeImpl (SyscallDesc * desc, int callnum, ThreadContext * tc, bool pseudo_pipe, bool is_pipe2)
Internal pipe() handler.
Now patch the read object to record the target file descriptor chosen as the write end of the pipe.
Alpha Linux convention for pipe() is that fd[0] is returned as the return value of the function, and fd[1] is returned in r20.
Copy the target file descriptors into buffer space and then copy the buffer space back into the target address space.
Definition at line 869 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by pipe2Func(), pipeFunc(), and pipePseudoFunc().
pipePseudoFunc()
SyscallReturn pipePseudoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
Definition at line 966 of file syscall_emul.cc.
References pipeImpl().
Referenced by futexFunc(), SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
readlinkFunc() [1/2]
SyscallReturn readlinkFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Definition at line 423 of file syscall_emul.cc.
References readlinkFunc().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), readlinkFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
readlinkFunc() [2/2]
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc, int index)
Target readlink() handler.
Definition at line 429 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), fatal, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::p, PortProxy::tryReadString(), and warn_once.
Referenced by readlinkatFunc().
recvfromFunc()
SyscallReturn recvfromFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1393 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::sa.
recvmsgFunc()
SyscallReturn recvmsgFunc (SyscallDesc * desc, int num, ThreadContext * tc)
struct msghdr { void *msg_name; // optional address socklen_t msg_namelen; // size of address struct iovec *msg_iov; // iovec array size_t msg_iovlen; // number entries in msg_iov i // entries correspond to buffer void *msg_control; // ancillary data size_t msg_controllen; // ancillary data buffer len int msg_flags; // flags on received message };
struct iovec { void *iov_base; // starting address size_t iov_len; // number of bytes to transfer };
The plan with this system call is to replace all of the pointers in the structure and the substructure with BufferArg class pointers. We will copy every field from the structures into our BufferArg classes.
We will use these address place holders to retain the pointers which we are going to replace with our own buffers in our simulator address space.
Record msg_name pointer then replace with buffer pointer.
Record msg_iov pointer then replace with buffer pointer. Also, setup an array of buffer pointers for the iovec structs record and replace their pointers with buffer pointers.
Record msg_control pointer then replace with buffer pointer.
Definition at line 1495 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::i, MipsISA::index, and MipsISA::p.
renameFunc()
SyscallReturn renameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target rename() handler.
Definition at line 568 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), unameFunc(), and unameFunc32().
rmdirFunc()
SyscallReturn rmdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1218 of file syscall_emul.cc.
References PowerISA::bo, BufferArg::bufferPtr(), BaseBufferArg::copyOut(), X86ISA::count, System::getGuestByteOrder(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, MipsISA::p, ArmISA::status, and PortProxy::tryReadString().
sendmsgFunc()
SyscallReturn sendmsgFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Reserve buffer space.
Assuming msgHdr.msg_iovlen >= 1, then there is no point calling recvmsg without a buffer.
Cannot instantiate buffers till inside the loop. Create array to hold buffer addresses, to be used during copyIn of send data.
Iterate through the iovec structures: Get the base buffer addreses, reserve iov_len amount of space for each. Put the buf address into the bufferArray for later retrieval.
Free dynamically allocated memory.
Malloced above.
Definition at line 1636 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
sendtoFunc()
SyscallReturn sendtoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1458 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::sa.
setpgidFunc()
SyscallReturn setpgidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target setpgid() handler.
Definition at line 993 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getSystemPtr(), ThreadContext::Halted, ArmISA::i, MipsISA::index, System::numContexts(), Process::pgid(), Process::pid(), and System::threadContexts.
Referenced by unameFunc32().
setsockoptFunc()
SyscallReturn setsockoptFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1819 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, X86ISA::level, MipsISA::p, and ArmISA::status.
setTidAddressFunc()
SyscallReturn setTidAddressFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target set_tid_address() handler.
Definition at line 291 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), and MipsISA::index.
Referenced by unameFunc32().
setuidFunc()
SyscallReturn setuidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target setuid() handler.
Definition at line 1065 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and warn.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
shutdownFunc()
SyscallReturn shutdownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target shutdown() handler.
Definition at line 1309 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
symlinkFunc()
SyscallReturn symlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target symlink() handler.
Definition at line 531 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
truncate64Func()
SyscallReturn truncate64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target truncate64() handler.
Definition at line 631 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, length, and PortProxy::tryReadString().
Referenced by unameFunc32().
truncateFunc()
SyscallReturn truncateFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target truncate() handler.
Definition at line 595 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, length, MipsISA::p, and PortProxy::tryReadString().
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
umaskFunc()
SyscallReturn umaskFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target umask() handler.
Definition at line 677 of file syscall_emul.cc.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
unimplementedFunc()
SyscallReturn unimplementedFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Handler for unimplemented syscalls that we haven't thought about.
Definition at line 67 of file syscall_emul.cc.
References fatal, and SyscallDesc::name().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
unlinkFunc()
SyscallReturn unlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 489 of file syscall_emul.cc.
References unlinkHelper().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
unlinkHelper()
SyscallReturn unlinkHelper (SyscallDesc * desc, int num, ThreadContext * tc, int index)
Target unlink() handler.
Definition at line 495 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::p, and PortProxy::tryReadString().
Referenced by unlinkatFunc(), and unlinkFunc().
warnUnsupportedOS()
void warnUnsupportedOS (std::string syscall_name)
Definition at line 61 of file syscall_emul.cc.
References warn.
Referenced by eventfdFunc(), fallocateFunc(), and statfsFunc().
Variable Documentation
hostname
const char* hostname = "m5.eecs.umich.edu"
Definition at line 372 of file syscall_emul.cc.
Referenced by gethostnameFunc().