gem5: base/trace.cc File Reference
trace.cc File Reference
#include "base/trace.hh"
#include <cctype>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include "base/debug.hh"
#include "base/logging.hh"
#include "base/output.hh"
#include "base/str.hh"
Namespaces
Trace
Functions
const std::string & name ()
Logger * Trace::getDebugLogger ()
Get the current global debug logger.
std::ostream & Trace::output ()
Get the ostream from the current global logger.
void Trace::setDebugLogger (Logger *logger)
Delete the current global logger and assign a new one.
void Trace::enable ()
Enable/disable debug logging.
void Trace::disable ()
Variables
Logger * Trace::debug_logger = NULL
ObjectMatch Trace::ignore
Function Documentation
name()
const std::string& name ()
Definition at line 49 of file trace.cc.
Referenced by sc_core::sc_port_b< tlm_nonblocking_put_if< T > >::_ifTypeName(), sc_gem5::VcdTraceFile::addNewTraceVal(), Stats::Group::addStatGroup(), sc_gem5::VcdTraceFile::addTraceVal(), arrayParamIn(), Stats::Text::beginGroup(), FALRU::CacheTracking::CacheTracking(), sc_gem5::ProcessObjRetFuncWrapper< T, R >::call(), sc_core::sc_signal< sc_dt::sc_int< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_uint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::check_writer(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), sc_gem5::Process::disable(), AddrOperandBase::disassemble(), Trace::Logger::dprintf(), sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >::dump(), Event::dump(), sc_core::sc_in_rv< W >::end_of_elaboration(), sc_core::sc_inout_rv< W >::end_of_elaboration(), Event::Event(), Iris::ThreadContext::extractResourceMap(), BaseXBar::findPort(), FastModel::AmbaFromTlmBridge64::gem5_getPort(), FastModel::AmbaToTlmBridge64::gem5_getPort(), FastModel::ScxEvsCortexA76< Types >::gem5_getPort(), sc_core::sc_module::gem5_getPort(), BrigObject::getFunction(), gethostnameFunc(), ProbePoint::getName(), MathExprPowerModel::getStaticPower(), ElfObject::handleLoadableSegment(), MSHR::handleSnoop(), sc_core::sc_vector_base::implicitCast(), EmbeddedPyBind::init(), X86ISA::Interrupts::init(), EmbeddedPython::initAll(), BaseRegOperand::initWithStrOffset(), Iris::ThreadContext::instanceRegistryChanged(), sc_gem5::Process::kill(), BaseXBar::Layer< MasterPort, SlavePort >::Layer(), Serializable::ScopedCheckpointSection::nameOut(), sc_gem5::VcdTraceFile::nextSignalName(), Nop(), tlm::tlm_phase::operator unsigned int(), StringWrap::operator()(), Stats::ScalarPrint::operator()(), Stats::VectorPrint::operator()(), std::hash< X86ISA::ExtMachInst >::operator()(), sc_core::sc_process_handle::operator=(), sc_core::sc_attr_cltn::operator[](), Trace::OstreamLogger::OstreamLogger(), AddrOperandBase::parseAddr(), AnnotateDumpCallback::process(), BrigObject::processDirectives(), Minor::Queue< Minor::ForwardInstData, ReportTraitsAdaptor< Minor::ForwardInstData >, BubbleTraitsAdaptor< Minor::ForwardInstData > >::push(), ThreadContext::quiesce(), BaseXBar::recvRangeChange(), sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >::register_port(), sc_core::sc_signal< sc_dt::sc_int< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_uint< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::register_port(), Ticked::regStats(), BaseXBar::regStats(), sc_core::sc_attr_cltn::remove(), Minor::Queue< Minor::ForwardInstData, ReportTraitsAdaptor< Minor::ForwardInstData >, BubbleTraitsAdaptor< Minor::ForwardInstData > >::reserve(), sc_gem5::Process::reset(), sc_gem5::Process::run(), sc_gem5::Event::sc_event(), SC_MODULE(), sc_core::sc_report_compose_message(), sc_core::sc_trace(), sc_core::sc_trace< bool >(), sc_core::sc_trace< sc_dt::sc_logic >(), ArchTimer::scheduleEvents(), Serializable::ScopedCheckpointSection::ScopedCheckpointSection(), FastModel::ScxEvsCortexA76< Types >::ScxEvsCortexA76(), TimerTable::setDescription(), O3ThreadContext< Impl >::setStatus(), Stats::Text::statName(), Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::subname(), sc_gem5::Process::throw_it(), Ticked::Ticked(), sc_gem5::TraceFile::traceDeltas(), SparcISA::unameFunc(), unameFunc(), unameFunc32(), unameFunc64(), sc_gem5::Process::uniqueName(), Event::unserialize(), BaseCPU::unserializeThread(), Stats::Output::~Output(), SimpleThread::~SimpleThread(), SMMUv3BaseCache::~SMMUv3BaseCache(), ThreadContext::~ThreadContext(), and WalkCache::~WalkCache().