gem5: base/trie.test.cc File Reference
trie.test.cc File Reference
#include <gtest/gtest.h>
#include <iostream>
#include <sstream>
#include <string>
#include "base/trie.hh"
#include "base/types.hh"
Classes
class TrieTestData
Functions
TEST_F (TrieTestData, Empty)
TEST_F (TrieTestData, SingleEntry)
TEST_F (TrieTestData, TwoOverlappingEntries)
TEST_F (TrieTestData, TwoOverlappingEntriesReversed)
TEST_F (TrieTestData, TwoIndependentEntries)
TEST_F (TrieTestData, TwoEntries)
TEST_F (TrieTestData, RemovingEntries)
Function Documentation
TEST_F() [1/7]
TEST_F (TrieTestData , Empty)
Definition at line 64 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [2/7]
TEST_F (TrieTestData , SingleEntry)
Definition at line 69 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [3/7]
TEST_F (TrieTestData , TwoOverlappingEntries)
Definition at line 76 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [4/7]
TEST_F (TrieTestData , TwoOverlappingEntriesReversed)
Definition at line 84 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [5/7]
TEST_F (TrieTestData , TwoIndependentEntries)
Definition at line 92 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [6/7]
TEST_F (TrieTestData , TwoEntries)
Definition at line 101 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), and TrieTestData::trie.
TEST_F() [7/7]
TEST_F (TrieTestData , RemovingEntries)
Definition at line 114 of file trie.test.cc.
References TrieTestData::dumpTrie(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), Trie< Key, Value >::remove(), and TrieTestData::trie.