gem5: systemc/tests/systemc/misc/user_guide/chpt4.3/clocks.h File Reference
clocks.h File Reference
#include "systemc.h"
Functions
SC_MODULE (clk_pos)
SC_MODULE (clk_neg)
SC_MODULE (clk2_pos)
SC_MODULE (clk2_neg)
Function Documentation
SC_MODULE() [1/4]
SC_MODULE (clk_pos)
Definition at line 45 of file clocks.h.
References SC_CTHREAD, SC_HAS_PROCESS, and sc_core::wait().
SC_MODULE() [2/4]
SC_MODULE (clk_neg)
Definition at line 76 of file clocks.h.
References SC_CTHREAD, SC_HAS_PROCESS, and sc_core::wait().
SC_MODULE() [3/4]
SC_MODULE (clk2_pos)
Definition at line 107 of file clocks.h.
References SC_CTHREAD, SC_HAS_PROCESS, and sc_core::wait().
SC_MODULE() [4/4]
SC_MODULE (clk2_neg)
Definition at line 138 of file clocks.h.
References SC_CTHREAD, SC_HAS_PROCESS, and sc_core::wait().