gem5: cpu/utils.hh File Reference
utils.hh File Reference
#include "base/types.hh"
Functions
Addr addrBlockOffset (Addr addr, Addr block_size)
Calculates the offset of a given address wrt aligned fixed-size blocks.
Addr addrBlockAlign (Addr addr, Addr block_size)
Returns the address of the closest aligned fixed-size block to the given address.
bool transferNeedsBurst (Addr addr, unsigned int size, unsigned int block_size)
Returns true if the given memory access (address, size) needs to be fragmented across aligned fixed-size blocks.
bool isAnyActiveElement (const std::vector< bool >::const_iterator &it_start, const std::vector< bool >::const_iterator &it_end)
Test if there is any active element in an enablement range.
Function Documentation
addrBlockAlign()
Addr addrBlockAlign (Addr addr, Addr block_size) inline
Returns the address of the closest aligned fixed-size block to the given address.
Parameters
addr Input address.
block_size Block size in bytes.
Returns
Address of the closest aligned block.
Definition at line 65 of file utils.hh.
Referenced by LSQ< Impl >::SplitDataRequest::initiateTranslation().
addrBlockOffset()
Addr addrBlockOffset (Addr addr, Addr block_size) inline
Calculates the offset of a given address wrt aligned fixed-size blocks.
Parameters
addr Input address.
block_size Block size in bytes.
Returns
Offset of the given address in bytes.
Definition at line 52 of file utils.hh.
Referenced by AtomicSimpleCPU::genMemFragmentRequest(), CheckerCPU::genMemFragmentRequest(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), and transferNeedsBurst().
isAnyActiveElement()
bool isAnyActiveElement (const std::vector< bool >::const_iterator & it_start, const std::vector< bool >::const_iterator & it_end) inline
Test if there is any active element in an enablement range.
Definition at line 88 of file utils.hh.
Referenced by LSQ< Impl >::LSQRequest::addRequest(), AtomicSimpleCPU::genMemFragmentRequest(), CheckerCPU::genMemFragmentRequest(), Minor::LSQ::SplitDataRequest::makeFragmentRequests(), and Minor::LSQ::SingleDataRequest::startAddrTranslation().
transferNeedsBurst()
bool transferNeedsBurst (Addr addr, unsigned int size, unsigned int block_size) inline
Returns true if the given memory access (address, size) needs to be fragmented across aligned fixed-size blocks.
Parameters
addr Address of the memory access.
size Size of the memory access.
block_size Block size in bytes.
Returns
True if the memory access needs to be fragmented.
Definition at line 79 of file utils.hh.
References addrBlockOffset().
Referenced by Minor::LSQ::pushRequest(), and LSQ< Impl >::pushRequest().