var searchData=
[
  ['radv',['RADV',['../structiGbReg_1_1Regs_1_1RADV.html',1,'iGbReg::Regs']]],
  ['randctx',['randctx',['../structQTIsaac_1_1randctx.html',1,'QTIsaac']]],
  ['random',['Random',['../classRandom.html',1,'']]],
  ['randomgen',['RandomGen',['../classRandomGen.html',1,'']]],
  ['randomrepldata',['RandomReplData',['../structRandomRP_1_1RandomReplData.html',1,'RandomRP']]],
  ['randomrp',['RandomRP',['../classRandomRP.html',1,'']]],
  ['randomstreamgen',['RandomStreamGen',['../classRandomStreamGen.html',1,'']]],
  ['rangeaddrmapper',['RangeAddrMapper',['../classRangeAddrMapper.html',1,'']]],
  ['rank',['Rank',['../classDRAMCtrl_1_1Rank.html',1,'DRAMCtrl']]],
  ['rankstats',['RankStats',['../structDRAMCtrl_1_1RankStats.html',1,'DRAMCtrl']]],
  ['rawdiskimage',['RawDiskImage',['../classRawDiskImage.html',1,'']]],
  ['rawimage',['RawImage',['../classRawImage.html',1,'']]],
  ['rctl',['RCTL',['../structiGbReg_1_1Regs_1_1RCTL.html',1,'iGbReg::Regs']]],
  ['rdba',['RDBA',['../structiGbReg_1_1Regs_1_1RDBA.html',1,'iGbReg::Regs']]],
  ['rdh',['RDH',['../structiGbReg_1_1Regs_1_1RDH.html',1,'iGbReg::Regs']]],
  ['rdlen',['RDLEN',['../structiGbReg_1_1Regs_1_1RDLEN.html',1,'iGbReg::Regs']]],
  ['rdpriv',['RdPriv',['../classSparcISA_1_1RdPriv.html',1,'SparcISA']]],
  ['rdt',['RDT',['../structiGbReg_1_1Regs_1_1RDT.html',1,'iGbReg::Regs']]],
  ['rdtr',['RDTR',['../structiGbReg_1_1Regs_1_1RDTR.html',1,'iGbReg::Regs']]],
  ['readynode',['ReadyNode',['../structTraceCPU_1_1ElasticDataGen_1_1ReadyNode.html',1,'TraceCPU::ElasticDataGen']]],
  ['realview',['RealView',['../classRealView.html',1,'']]],
  ['realviewctrl',['RealViewCtrl',['../classRealViewCtrl.html',1,'']]],
  ['realviewosc',['RealViewOsc',['../classRealViewOsc.html',1,'']]],
  ['realviewtemperaturesensor',['RealViewTemperatureSensor',['../classRealViewTemperatureSensor.html',1,'']]],
  ['recency',['RECENCY',['../classMultiperspectivePerceptron_1_1RECENCY.html',1,'MultiperspectivePerceptron']]],
  ['recencypos',['RECENCYPOS',['../classMultiperspectivePerceptron_1_1RECENCYPOS.html',1,'MultiperspectivePerceptron']]],
  ['reconvergencestackentry',['ReconvergenceStackEntry',['../structReconvergenceStackEntry.html',1,'']]],
  ['recvscheduler',['RecvScheduler',['../classDistIface_1_1RecvScheduler.html',1,'DistIface']]],
  ['redirectpath',['RedirectPath',['../classRedirectPath.html',1,'']]],
  ['redstateexception',['REDStateException',['../classSparcISA_1_1REDStateException.html',1,'SparcISA']]],
  ['reexec',['ReExec',['../classReExec.html',1,'']]],
  ['refcounted',['RefCounted',['../classRefCounted.html',1,'']]],
  ['refcountingptr',['RefCountingPtr',['../classRefCountingPtr.html',1,'']]],
  ['refcountingptr_3c_20minordyninst_20_3e',['RefCountingPtr&lt; MinorDynInst &gt;',['../classRefCountingPtr.html',1,'']]],
  ['refcountingptr_3c_20staticinst_20_3e',['RefCountingPtr&lt; StaticInst &gt;',['../classRefCountingPtr.html',1,'']]],
  ['reg',['Reg',['../structiGbReg_1_1Regs_1_1Reg.html',1,'iGbReg::Regs::Reg&lt; T &gt;'],['../structCopyEngineReg_1_1Reg.html',1,'CopyEngineReg::Reg&lt; T &gt;']]],
  ['reg_3c_20uint16_5ft_20_3e',['Reg&lt; uint16_t &gt;',['../structCopyEngineReg_1_1Reg.html',1,'CopyEngineReg']]],
  ['reg_3c_20uint32_5ft_20_3e',['Reg&lt; uint32_t &gt;',['../structiGbReg_1_1Regs_1_1Reg.html',1,'iGbReg::Regs::Reg&lt; uint32_t &gt;'],['../structCopyEngineReg_1_1Reg.html',1,'CopyEngineReg::Reg&lt; uint32_t &gt;']]],
  ['reg_3c_20uint64_5ft_20_3e',['Reg&lt; uint64_t &gt;',['../structiGbReg_1_1Regs_1_1Reg.html',1,'iGbReg::Regs::Reg&lt; uint64_t &gt;'],['../structCopyEngineReg_1_1Reg.html',1,'CopyEngineReg::Reg&lt; uint64_t &gt;']]],
  ['reg_3c_20uint8_5ft_20_3e',['Reg&lt; uint8_t &gt;',['../structCopyEngineReg_1_1Reg.html',1,'CopyEngineReg']]],
  ['regaddroperand',['RegAddrOperand',['../classRegAddrOperand.html',1,'']]],
  ['regentry',['RegEntry',['../structTrace_1_1TarmacBaseRecord_1_1RegEntry.html',1,'Trace::TarmacBaseRecord']]],
  ['regid',['RegId',['../classRegId.html',1,'']]],
  ['regimmimmop',['RegImmImmOp',['../classRegImmImmOp.html',1,'']]],
  ['regimmop',['RegImmOp',['../classRegImmOp.html',1,'']]],
  ['regimmregop',['RegImmRegOp',['../classRegImmRegOp.html',1,'']]],
  ['regimmregshiftop',['RegImmRegShiftOp',['../classRegImmRegShiftOp.html',1,'']]],
  ['regionmissorderbufferentry',['RegionMissOrderBufferEntry',['../structSTeMSPrefetcher_1_1RegionMissOrderBufferEntry.html',1,'STeMSPrefetcher']]],
  ['regmiscregimmop',['RegMiscRegImmOp',['../classRegMiscRegImmOp.html',1,'']]],
  ['regmiscregimmop64',['RegMiscRegImmOp64',['../classRegMiscRegImmOp64.html',1,'']]],
  ['regop',['RegOp',['../classRiscvISA_1_1RegOp.html',1,'RiscvISA::RegOp'],['../classX86ISA_1_1RegOp.html',1,'X86ISA::RegOp']]],
  ['regopbase',['RegOpBase',['../classX86ISA_1_1RegOpBase.html',1,'X86ISA']]],
  ['regopimm',['RegOpImm',['../classX86ISA_1_1RegOpImm.html',1,'X86ISA']]],
  ['regorimmoperand',['RegOrImmOperand',['../classRegOrImmOperand.html',1,'']]],
  ['regregimmimmop',['RegRegImmImmOp',['../classRegRegImmImmOp.html',1,'']]],
  ['regregimmimmop64',['RegRegImmImmOp64',['../classRegRegImmImmOp64.html',1,'']]],
  ['regregimmop',['RegRegImmOp',['../classRegRegImmOp.html',1,'']]],
  ['regregop',['RegRegOp',['../classRegRegOp.html',1,'']]],
  ['regregregimmop',['RegRegRegImmOp',['../classRegRegRegImmOp.html',1,'']]],
  ['regregregimmop64',['RegRegRegImmOp64',['../classRegRegRegImmOp64.html',1,'']]],
  ['regregregop',['RegRegRegOp',['../classRegRegRegOp.html',1,'']]],
  ['regregregregop',['RegRegRegRegOp',['../classRegRegRegRegOp.html',1,'']]],
  ['regs',['Regs',['../structiGbReg_1_1Regs.html',1,'iGbReg::Regs'],['../structCopyEngineReg_1_1Regs.html',1,'CopyEngineReg::Regs']]],
  ['regularevent',['RegularEvent',['../structArmISA_1_1PMU_1_1RegularEvent.html',1,'ArmISA::PMU']]],
  ['regularprobe',['RegularProbe',['../structArmISA_1_1PMU_1_1RegularEvent_1_1RegularProbe.html',1,'ArmISA::PMU::RegularEvent']]],
  ['rejectexception',['RejectException',['../classRejectException.html',1,'']]],
  ['remotegdb',['RemoteGDB',['../classMipsISA_1_1RemoteGDB.html',1,'MipsISA::RemoteGDB'],['../classAlphaISA_1_1RemoteGDB.html',1,'AlphaISA::RemoteGDB'],['../classPowerISA_1_1RemoteGDB.html',1,'PowerISA::RemoteGDB'],['../classRiscvISA_1_1RemoteGDB.html',1,'RiscvISA::RemoteGDB'],['../classArmISA_1_1RemoteGDB.html',1,'ArmISA::RemoteGDB'],['../classSparcISA_1_1RemoteGDB.html',1,'SparcISA::RemoteGDB'],['../classX86ISA_1_1RemoteGDB.html',1,'X86ISA::RemoteGDB']]],
  ['remove_5fconst',['remove_const',['../structsc__gem5_1_1remove__const.html',1,'sc_gem5']]],
  ['remove_5fconst_3c_20const_20t_20_3e',['remove_const&lt; const T &gt;',['../structsc__gem5_1_1remove__const_3_01const_01T_01_4.html',1,'sc_gem5']]],
  ['remove_5fspecial_5ffptr',['remove_special_fptr',['../structsc__gem5_1_1remove__special__fptr.html',1,'sc_gem5']]],
  ['remove_5fspecial_5ffptr_3c_20special_5fresult_20_26_28_2a_29_28t_29_3e',['remove_special_fptr&lt; special_result &amp;(*)(T)&gt;',['../structsc__gem5_1_1remove__special__fptr_3_01special__result_01_6_07_5_08_07T_08_4.html',1,'sc_gem5']]],
  ['renamecomm',['renameComm',['../structTimeBufStruct_1_1renameComm.html',1,'TimeBufStruct']]],
  ['renamehistory',['RenameHistory',['../structDefaultRename_1_1RenameHistory.html',1,'DefaultRename']]],
  ['renamemode',['RenameMode',['../structRenameMode.html',1,'']]],
  ['renamemode_3c_20armisa_3a_3aisa_20_3e',['RenameMode&lt; ArmISA::ISA &gt;',['../structRenameMode_3_01ArmISA_1_1ISA_01_4.html',1,'']]],
  ['renaming',['Renaming',['../structCxxConfigManager_1_1Renaming.html',1,'CxxConfigManager']]],
  ['repeatedqwordscompressor',['RepeatedQwordsCompressor',['../classRepeatedQwordsCompressor.html',1,'']]],
  ['repeatedvaluepattern',['RepeatedValuePattern',['../classDictionaryCompressor_1_1RepeatedValuePattern.html',1,'DictionaryCompressor']]],
  ['replaceableentry',['ReplaceableEntry',['../classReplaceableEntry.html',1,'']]],
  ['replacementdata',['ReplacementData',['../structReplacementData.html',1,'']]],
  ['reportif',['ReportIF',['../classMinor_1_1ReportIF.html',1,'Minor']]],
  ['reportmsginfo',['ReportMsgInfo',['../structsc__gem5_1_1ReportMsgInfo.html',1,'sc_gem5']]],
  ['reportsevinfo',['ReportSevInfo',['../structsc__gem5_1_1ReportSevInfo.html',1,'sc_gem5']]],
  ['reporttraitsadaptor',['ReportTraitsAdaptor',['../classMinor_1_1ReportTraitsAdaptor.html',1,'Minor']]],
  ['reporttraitsptradaptor',['ReportTraitsPtrAdaptor',['../classMinor_1_1ReportTraitsPtrAdaptor.html',1,'Minor']]],
  ['reqlayer',['ReqLayer',['../classBaseXBar_1_1ReqLayer.html',1,'BaseXBar']]],
  ['reqlookupresult',['ReqLookupResult',['../structSnoopFilter_1_1ReqLookupResult.html',1,'SnoopFilter']]],
  ['reqpacketqueue',['ReqPacketQueue',['../classReqPacketQueue.html',1,'']]],
  ['request',['Request',['../classRequest.html',1,'']]],
  ['requestdesc',['RequestDesc',['../classRequestDesc.html',1,'']]],
  ['requestdescheader',['RequestDescHeader',['../structUFSHostDevice_1_1UTPTransferReqDesc_1_1RequestDescHeader.html',1,'UFSHostDevice::UTPTransferReqDesc']]],
  ['requestqueue',['RequestQueue',['../classVirtIOBlock_1_1RequestQueue.html',1,'VirtIOBlock']]],
  ['reservable',['Reservable',['../classMinor_1_1Reservable.html',1,'Minor']]],
  ['reservedinstructionfault',['ReservedInstructionFault',['../classMipsISA_1_1ReservedInstructionFault.html',1,'MipsISA']]],
  ['reset',['Reset',['../classArmISA_1_1Reset.html',1,'ArmISA::Reset'],['../structsc__core_1_1sc__spawn__options_1_1Reset.html',1,'sc_core::sc_spawn_options::Reset&lt; T &gt;'],['../classRiscvISA_1_1Reset.html',1,'RiscvISA::Reset'],['../classsc__gem5_1_1Reset.html',1,'sc_gem5::Reset']]],
  ['reset_3c_20const_20sc_5fcore_3a_3asc_5fin_3c_20bool_20_3e_20_3e',['Reset&lt; const sc_core::sc_in&lt; bool &gt; &gt;',['../structsc__core_1_1sc__spawn__options_1_1Reset.html',1,'sc_core::sc_spawn_options']]],
  ['reset_3c_20const_20sc_5fcore_3a_3asc_5finout_3c_20bool_20_3e_20_3e',['Reset&lt; const sc_core::sc_inout&lt; bool &gt; &gt;',['../structsc__core_1_1sc__spawn__options_1_1Reset.html',1,'sc_core::sc_spawn_options']]],
  ['reset_3c_20const_20sc_5fcore_3a_3asc_5fout_3c_20bool_20_3e_20_3e',['Reset&lt; const sc_core::sc_out&lt; bool &gt; &gt;',['../structsc__core_1_1sc__spawn__options_1_1Reset.html',1,'sc_core::sc_spawn_options']]],
  ['reset_3c_20const_20sc_5fcore_3a_3asc_5fsignal_5fin_5fif_3c_20bool_20_3e_20_3e',['Reset&lt; const sc_core::sc_signal_in_if&lt; bool &gt; &gt;',['../structsc__core_1_1sc__spawn__options_1_1Reset.html',1,'sc_core::sc_spawn_options']]],
  ['resetfault',['ResetFault',['../classMipsISA_1_1ResetFault.html',1,'MipsISA::ResetFault'],['../classAlphaISA_1_1ResetFault.html',1,'AlphaISA::ResetFault']]],
  ['resplayer',['RespLayer',['../classBaseXBar_1_1RespLayer.html',1,'BaseXBar']]],
  ['resppacketqueue',['RespPacketQueue',['../classRespPacketQueue.html',1,'']]],
  ['resumableerror',['ResumableError',['../classSparcISA_1_1ResumableError.html',1,'SparcISA']]],
  ['ret',['Ret',['../classHsailISA_1_1Ret.html',1,'HsailISA']]],
  ['returnaddrstack',['ReturnAddrStack',['../classReturnAddrStack.html',1,'']]],
  ['rfctl',['RFCTL',['../structiGbReg_1_1Regs_1_1RFCTL.html',1,'iGbReg::Regs']]],
  ['rfeop',['RfeOp',['../classArmISA_1_1RfeOp.html',1,'ArmISA']]],
  ['rgb_5ft',['rgb_t',['../structrgb__t.html',1,'']]],
  ['riscvfault',['RiscvFault',['../classRiscvISA_1_1RiscvFault.html',1,'RiscvISA']]],
  ['riscvgdbregcache',['RiscvGdbRegCache',['../classRiscvISA_1_1RemoteGDB_1_1RiscvGdbRegCache.html',1,'RiscvISA::RemoteGDB']]],
  ['riscvlinux',['RiscvLinux',['../classRiscvLinux.html',1,'']]],
  ['riscvlinux32',['RiscvLinux32',['../classRiscvLinux32.html',1,'']]],
  ['riscvlinux64',['RiscvLinux64',['../classRiscvLinux64.html',1,'']]],
  ['riscvlinuxprocess32',['RiscvLinuxProcess32',['../classRiscvLinuxProcess32.html',1,'']]],
  ['riscvlinuxprocess64',['RiscvLinuxProcess64',['../classRiscvLinuxProcess64.html',1,'']]],
  ['riscvmacroinst',['RiscvMacroInst',['../classRiscvISA_1_1RiscvMacroInst.html',1,'RiscvISA']]],
  ['riscvmicroinst',['RiscvMicroInst',['../classRiscvISA_1_1RiscvMicroInst.html',1,'RiscvISA']]],
  ['riscvprocess',['RiscvProcess',['../classRiscvProcess.html',1,'']]],
  ['riscvprocess32',['RiscvProcess32',['../classRiscvProcess32.html',1,'']]],
  ['riscvprocess64',['RiscvProcess64',['../classRiscvProcess64.html',1,'']]],
  ['riscvstaticinst',['RiscvStaticInst',['../classRiscvISA_1_1RiscvStaticInst.html',1,'RiscvISA']]],
  ['riscvsystem',['RiscvSystem',['../classRiscvSystem.html',1,'']]],
  ['rlimit',['rlimit',['../structLinux_1_1rlimit.html',1,'Linux::rlimit'],['../structOperatingSystem_1_1rlimit.html',1,'OperatingSystem::rlimit'],['../structArmLinux64_1_1rlimit.html',1,'ArmLinux64::rlimit'],['../structArmLinux32_1_1rlimit.html',1,'ArmLinux32::rlimit'],['../structRiscvLinux32_1_1rlimit.html',1,'RiscvLinux32::rlimit'],['../structArmFreebsd32_1_1rlimit.html',1,'ArmFreebsd32::rlimit'],['../structArmFreebsd64_1_1rlimit.html',1,'ArmFreebsd64::rlimit']]],
  ['rndxr',['RNDXR',['../structRNDXR.html',1,'']]],
  ['rob',['ROB',['../classROB.html',1,'']]],
  ['root',['Root',['../classRoot.html',1,'']]],
  ['routeinfo',['RouteInfo',['../structRouteInfo.html',1,'']]],
  ['router',['Router',['../classRouter.html',1,'']]],
  ['routingunit',['RoutingUnit',['../classRoutingUnit.html',1,'']]],
  ['rrschedulingpolicy',['RRSchedulingPolicy',['../classRRSchedulingPolicy.html',1,'']]],
  ['rsdp',['RSDP',['../classX86ISA_1_1ACPI_1_1RSDP.html',1,'X86ISA::ACPI']]],
  ['rsdt',['RSDT',['../classX86ISA_1_1ACPI_1_1RSDT.html',1,'X86ISA::ACPI']]],
  ['rsrpd',['RSRPD',['../structiGbReg_1_1Regs_1_1RSRPD.html',1,'iGbReg::Regs']]],
  ['rtc',['RTC',['../classTsunamiIO_1_1RTC.html',1,'TsunamiIO::RTC'],['../classMaltaIO_1_1RTC.html',1,'MaltaIO::RTC']]],
  ['rtcevent',['RTCEvent',['../structMC146818_1_1RTCEvent.html',1,'MC146818']]],
  ['rtctickevent',['RTCTickEvent',['../structMC146818_1_1RTCTickEvent.html',1,'MC146818']]],
  ['rubydirectedtester',['RubyDirectedTester',['../classRubyDirectedTester.html',1,'']]],
  ['rubydummyport',['RubyDummyPort',['../classRubyDummyPort.html',1,'']]],
  ['rubyport',['RubyPort',['../classRubyPort.html',1,'']]],
  ['rubyportproxy',['RubyPortProxy',['../classRubyPortProxy.html',1,'']]],
  ['rubyrequest',['RubyRequest',['../classRubyRequest.html',1,'']]],
  ['rubystatscallback',['RubyStatsCallback',['../classRubyStatsCallback.html',1,'']]],
  ['rubysystem',['RubySystem',['../classRubySystem.html',1,'']]],
  ['rubytester',['RubyTester',['../classRubyTester.html',1,'']]],
  ['rusage',['rusage',['../structLinux_1_1rusage.html',1,'Linux::rusage'],['../structArmFreebsd64_1_1rusage.html',1,'ArmFreebsd64::rusage'],['../structArmLinux32_1_1rusage.html',1,'ArmLinux32::rusage'],['../structArmLinux64_1_1rusage.html',1,'ArmLinux64::rusage'],['../structOperatingSystem_1_1rusage.html',1,'OperatingSystem::rusage'],['../structArmFreebsd32_1_1rusage.html',1,'ArmFreebsd32::rusage']]],
  ['rxcsum',['RXCSUM',['../structiGbReg_1_1Regs_1_1RXCSUM.html',1,'iGbReg::Regs']]],
  ['rxdctl',['RXDCTL',['../structiGbReg_1_1Regs_1_1RXDCTL.html',1,'iGbReg::Regs']]],
  ['rxdesc',['RxDesc',['../structiGbReg_1_1RxDesc.html',1,'iGbReg']]],
  ['rxdesccache',['RxDescCache',['../classIGbE_1_1RxDescCache.html',1,'IGbE']]],
  ['rxlink',['RxLink',['../classDistEtherLink_1_1RxLink.html',1,'DistEtherLink']]]
];
