gem5: base/addr_range.test.cc File Reference
addr_range.test.cc File Reference
#include <gtest/gtest.h>
#include <cmath>
#include "base/addr_range.hh"
#include "base/bitfield.hh"
Functions
TEST (AddrRangeTest, ValidRange)
TEST (AddrRangeTest, EmptyRange)
TEST (AddrRangeTest, RangeSizeOfOne)
TEST (AddrRangeTest, Range16Bit)
TEST (AddrRangeTest, InvalidRange)
TEST (AddrRangeTest, LessThan)
TEST (AddrRangeTest, EqualToNotEqualTo)
TEST (AddrRangeTest, MergesWith)
TEST (AddrRangeTest, DoesNotMergeWith)
TEST (AddrRangeTest, IntersectsCompleteOverlap)
TEST (AddrRangeTest, IntersectsAddressWithin)
TEST (AddrRangeTest, IntersectsPartialOverlap)
TEST (AddrRangeTest, IntersectsNoOverlap)
TEST (AddrRangeTest, IntersectsFirstLastAddressOverlap)
TEST (AddrRangeTest, isSubsetCompleteOverlap)
TEST (AddrRangeTest, isSubsetNoOverlap)
TEST (AddrRangeTest, isSubsetTrueSubset)
TEST (AddrRangeTest, isSubsetPartialSubset)
TEST (AddrRangeTest, Contains)
TEST (AddrRangeTest, ContainsInAnEmptyRange)
TEST (AddrRangeTest, RemoveIntlvBits)
TEST (AddrRangeTest, addIntlvBits)
TEST (AddrRangeTest, OffsetInRange)
TEST (AddrRangeTest, OffsetOutOfRangeAfter)
TEST (AddrRangeTest, OffsetOutOfRangeBefore)
TEST (AddrRangeTest, LsbInterleavingMask)
TEST (AddrRangeTest, TwoInterleavingMasks)
TEST (AddrRangeTest, ComplexInterleavingMasks)
TEST (AddrRangeTest, InterleavingAddressesMergesWith)
TEST (AddrRangeTest, InterleavingAddressesDoNotMergeWith)
TEST (AddrRangeTest, InterleavingAddressesDoNotIntersect)
TEST (AddrRangeTest, InterleavingAddressesIntersectsViaMerging)
TEST (AddrRangeTest, InterleavingAddressesDoesNotIntersectViaMerging)
TEST (AddrRangeTest, DISABLED_InterleavingAddressesIntersect)
TEST (AddrRangeTest, DISABLED_InterleavingAddressesIntersectsOnOneByteAddress)
TEST (AddrRangeTest, DISABLED_InterleavingAddressesDoesNotIntersectOnOneByteAddress)
TEST (AddrRangeTest, DISABLED_InterleavingAddressIsSubset)
TEST (AddrRangeTest, DISABLED_InterleavingAddressIsNotSubset)
TEST (AddrRangeTest, DISABLED_InterleavingAddressContains)
TEST (AddrRangeTest, InterleavingAddressAddRemoveInterlvBits)
TEST (AddrRangeTest, InterleavingAddressAddRemoveInterlvBitsTwoMasks)
TEST (AddrRangeTest, AddRemoveInterleavBitsAcrossRange)
TEST (AddrRangeTest, InterleavingAddressesGetOffset)
TEST (AddrRangeTest, InterleavingLessThanStartEquals)
TEST (AddrRangeTest, InterleavingLessThanStartNotEquals)
TEST (AddrRangeTest, InterleavingEqualTo)
TEST (AddrRangeTest, InterleavingNotEqualTo)
TEST (AddrRangeTest, MergingInterleavingAddressRanges)
TEST (AddrRangeTest, MergingInterleavingAddressRangesOneRange)
TEST (AddrRangeTest, LegacyConstructorNoInterleaving)
TEST (AddrRangeTest, LegacyConstructorOneBitMask)
TEST (AddrRangeTest, LegacyConstructorTwoBitMask)
TEST (AddrRangeTest, LegacyConstructorTwoBitMaskWithXOR)
TEST (AddrRangeTest, RangeExConstruction)
TEST (AddrRangeTest, RangeInConstruction)
TEST (AddrRangeTest, RangeSizeConstruction)
Function Documentation
TEST() [1/56]
TEST (AddrRangeTest , ValidRange)
Definition at line 49 of file addr_range.test.cc.
References EXPECT_FALSE, MipsISA::r, and AddrRange::valid().
TEST() [2/56]
TEST (AddrRangeTest , EmptyRange)
Definition at line 61 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, AddrRange::granularity(), AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [3/56]
TEST (AddrRangeTest , RangeSizeOfOne)
Definition at line 90 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, AddrRange::granularity(), AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [4/56]
TEST (AddrRangeTest , Range16Bit)
Definition at line 103 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, AddrRange::granularity(), AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [5/56]
TEST (AddrRangeTest , InvalidRange)
Definition at line 116 of file addr_range.test.cc.
References EXPECT_FALSE, MipsISA::r, and AddrRange::valid().
TEST() [6/56]
TEST (AddrRangeTest , LessThan)
Definition at line 122 of file addr_range.test.cc.
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [7/56]
TEST (AddrRangeTest , EqualToNotEqualTo)
Definition at line 140 of file addr_range.test.cc.
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [8/56]
TEST (AddrRangeTest , MergesWith)
Definition at line 157 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::mergesWith().
TEST() [9/56]
TEST (AddrRangeTest , DoesNotMergeWith)
Definition at line 170 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::mergesWith().
TEST() [10/56]
TEST (AddrRangeTest , IntersectsCompleteOverlap)
Definition at line 179 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [11/56]
TEST (AddrRangeTest , IntersectsAddressWithin)
Definition at line 188 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [12/56]
TEST (AddrRangeTest , IntersectsPartialOverlap)
Definition at line 197 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [13/56]
TEST (AddrRangeTest , IntersectsNoOverlap)
Definition at line 206 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::intersects().
TEST() [14/56]
TEST (AddrRangeTest , IntersectsFirstLastAddressOverlap)
Definition at line 215 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::intersects().
TEST() [15/56]
TEST (AddrRangeTest , isSubsetCompleteOverlap)
Definition at line 228 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::isSubset().
TEST() [16/56]
TEST (AddrRangeTest , isSubsetNoOverlap)
Definition at line 237 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::isSubset().
TEST() [17/56]
TEST (AddrRangeTest , isSubsetTrueSubset)
Definition at line 246 of file addr_range.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and AddrRange::isSubset().
TEST() [18/56]
TEST (AddrRangeTest , isSubsetPartialSubset)
Definition at line 255 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::isSubset().
TEST() [19/56]
TEST (AddrRangeTest , Contains)
Definition at line 264 of file addr_range.test.cc.
References AddrRange::contains(), EXPECT_FALSE, EXPECT_TRUE, and MipsISA::r.
TEST() [20/56]
TEST (AddrRangeTest , ContainsInAnEmptyRange)
Definition at line 278 of file addr_range.test.cc.
References AddrRange::contains(), EXPECT_FALSE, and MipsISA::r.
TEST() [21/56]
TEST (AddrRangeTest , RemoveIntlvBits)
Definition at line 285 of file addr_range.test.cc.
References ArmISA::a, EXPECT_EQ, MipsISA::r, and AddrRange::removeIntlvBits().
TEST() [22/56]
TEST (AddrRangeTest , addIntlvBits)
Definition at line 298 of file addr_range.test.cc.
References ArmISA::a, AddrRange::addIntlvBits(), EXPECT_EQ, and MipsISA::r.
TEST() [23/56]
TEST (AddrRangeTest , OffsetInRange)
Definition at line 311 of file addr_range.test.cc.
References EXPECT_EQ, AddrRange::getOffset(), and MipsISA::r.
TEST() [24/56]
TEST (AddrRangeTest , OffsetOutOfRangeAfter)
Definition at line 317 of file addr_range.test.cc.
References EXPECT_EQ, AddrRange::getOffset(), MaxAddr, and MipsISA::r.
TEST() [25/56]
TEST (AddrRangeTest , OffsetOutOfRangeBefore)
Definition at line 326 of file addr_range.test.cc.
References EXPECT_EQ, AddrRange::getOffset(), MaxAddr, and MipsISA::r.
TEST() [26/56]
TEST (AddrRangeTest , LsbInterleavingMask)
Definition at line 336 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_TRUE, AddrRange::granularity(), AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [27/56]
TEST (AddrRangeTest , TwoInterleavingMasks)
Definition at line 366 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_TRUE, AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [28/56]
TEST (AddrRangeTest , ComplexInterleavingMasks)
Definition at line 389 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_TRUE, AddrRange::interleaved(), MipsISA::r, AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), ULL, and AddrRange::valid().
TEST() [29/56]
TEST (AddrRangeTest , InterleavingAddressesMergesWith)
Definition at line 409 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::mergesWith().
TEST() [30/56]
TEST (AddrRangeTest , InterleavingAddressesDoNotMergeWith)
Definition at line 428 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::mergesWith().
TEST() [31/56]
TEST (AddrRangeTest , InterleavingAddressesDoNotIntersect)
Definition at line 450 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::intersects().
TEST() [32/56]
TEST (AddrRangeTest , InterleavingAddressesIntersectsViaMerging)
Definition at line 477 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [33/56]
TEST (AddrRangeTest , InterleavingAddressesDoesNotIntersectViaMerging)
Definition at line 499 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::intersects().
TEST() [34/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressesIntersect)
Definition at line 535 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [35/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressesIntersectsOnOneByteAddress)
Definition at line 562 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::intersects().
TEST() [36/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressesDoesNotIntersectOnOneByteAddress)
Definition at line 580 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::intersects().
TEST() [37/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressIsSubset)
Definition at line 605 of file addr_range.test.cc.
References EXPECT_TRUE, and AddrRange::isSubset().
TEST() [38/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressIsNotSubset)
Definition at line 628 of file addr_range.test.cc.
References EXPECT_FALSE, and AddrRange::isSubset().
TEST() [39/56]
TEST (AddrRangeTest , DISABLED_InterleavingAddressContains)
addr[0] && !addr[4]
Definition at line 652 of file addr_range.test.cc.
References addr, AddrRange::contains(), EXPECT_FALSE, EXPECT_TRUE, and MipsISA::r.
TEST() [40/56]
TEST (AddrRangeTest , InterleavingAddressAddRemoveInterlvBits)
Definition at line 675 of file addr_range.test.cc.
References AddrRange::addIntlvBits(), EXPECT_EQ, output(), MipsISA::r, and AddrRange::removeIntlvBits().
TEST() [41/56]
TEST (AddrRangeTest , InterleavingAddressAddRemoveInterlvBitsTwoMasks)
Definition at line 710 of file addr_range.test.cc.
References AddrRange::addIntlvBits(), EXPECT_EQ, output(), MipsISA::r, and AddrRange::removeIntlvBits().
TEST() [42/56]
TEST (AddrRangeTest , AddRemoveInterleavBitsAcrossRange)
Definition at line 737 of file addr_range.test.cc.
References AddrRange::addIntlvBits(), EXPECT_EQ, ArmISA::i, MipsISA::r, and AddrRange::removeIntlvBits().
TEST() [43/56]
TEST (AddrRangeTest , InterleavingAddressesGetOffset)
Definition at line 766 of file addr_range.test.cc.
References EXPECT_EQ, AddrRange::getOffset(), and MipsISA::r.
TEST() [44/56]
TEST (AddrRangeTest , InterleavingLessThanStartEquals)
Definition at line 784 of file addr_range.test.cc.
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [45/56]
TEST (AddrRangeTest , InterleavingLessThanStartNotEquals)
Definition at line 809 of file addr_range.test.cc.
References EXPECT_FALSE, and EXPECT_TRUE.
TEST() [46/56]
TEST (AddrRangeTest , InterleavingEqualTo)
Definition at line 830 of file addr_range.test.cc.
References EXPECT_TRUE.
TEST() [47/56]
TEST (AddrRangeTest , InterleavingNotEqualTo)
Definition at line 849 of file addr_range.test.cc.
References EXPECT_FALSE.
TEST() [48/56]
TEST (AddrRangeTest , MergingInterleavingAddressRanges)
Definition at line 878 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, EXPECT_FALSE, AddrRange::interleaved(), output(), and AddrRange::start().
TEST() [49/56]
TEST (AddrRangeTest , MergingInterleavingAddressRangesOneRange)
Definition at line 905 of file addr_range.test.cc.
References EXPECT_EQ, output(), and MipsISA::r.
TEST() [50/56]
TEST (AddrRangeTest , LegacyConstructorNoInterleaving)
Definition at line 942 of file addr_range.test.cc.
References EXPECT_EQ, and expected.
TEST() [51/56]
TEST (AddrRangeTest , LegacyConstructorOneBitMask)
Definition at line 953 of file addr_range.test.cc.
References EXPECT_TRUE, and expected.
TEST() [52/56]
TEST (AddrRangeTest , LegacyConstructorTwoBitMask)
Definition at line 969 of file addr_range.test.cc.
References EXPECT_TRUE, and expected.
TEST() [53/56]
TEST (AddrRangeTest , LegacyConstructorTwoBitMaskWithXOR)
Definition at line 986 of file addr_range.test.cc.
References AddrRange::contains(), EXPECT_FALSE, EXPECT_TRUE, and ArmISA::i.
TEST() [54/56]
TEST (AddrRangeTest , RangeExConstruction)
Definition at line 1023 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, MipsISA::r, RangeEx(), and AddrRange::start().
TEST() [55/56]
TEST (AddrRangeTest , RangeInConstruction)
Definition at line 1030 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, MipsISA::r, RangeIn(), and AddrRange::start().
TEST() [56/56]
TEST (AddrRangeTest , RangeSizeConstruction)
Definition at line 1037 of file addr_range.test.cc.
References AddrRange::end(), EXPECT_EQ, MipsISA::r, RangeSize(), and AddrRange::start().