gem5: base/addr_range_map.test.cc File Reference
addr_range_map.test.cc File Reference
#include <gtest/gtest.h>
#include "base/addr_range_map.hh"
Functions
TEST (AddrRangeMapTest, LegacyTests)
Function Documentation
TEST()
TEST (AddrRangeMapTest , LegacyTests)
Definition at line 48 of file addr_range_map.test.cc.
References AddrRangeMap< V, max_cache_size >::contains(), AddrRangeMap< V, max_cache_size >::end(), EXPECT_EQ, ArmISA::i, AddrRangeMap< V, max_cache_size >::insert(), AddrRangeMap< V, max_cache_size >::intersects(), MipsISA::r, and RangeIn().