gem5: arch/arm/freebsd/process.cc File Reference
process.cc File Reference
#include "arch/arm/freebsd/process.hh"
#include <sys/mman.h>
#include <sys/param.h>
#include <sys/syscall.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#include <utime.h>
#include "arch/arm/freebsd/freebsd.hh"
#include "arch/arm/isa_traits.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/freebsd/freebsd.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn issetugidFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
static SyscallReturn sysctlFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Variables
static SyscallDesc syscallDescs32 []
static SyscallDesc syscallDescs64 []
Function Documentation
issetugidFunc()
static SyscallReturn issetugidFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 90 of file process.cc.
sysctlFunc()
static SyscallReturn sysctlFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 97 of file process.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), and MipsISA::index.
Variable Documentation
syscallDescs32
SyscallDesc syscallDescs32[] static
Definition at line 141 of file process.cc.
Referenced by ArmFreebsdProcess32::ArmFreebsdProcess32().
syscallDescs64
SyscallDesc syscallDescs64[] static
Definition at line 692 of file process.cc.
Referenced by ArmFreebsdProcess64::ArmFreebsdProcess64().