gem5: arch/mips/linux/process.cc File Reference
process.cc File Reference
#include "arch/mips/linux/process.hh"
#include "arch/mips/isa_traits.hh"
#include "arch/mips/linux/linux.hh"
#include "base/loader/object_file.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "debug/SyscallVerbose.hh"
#include "kern/linux/linux.hh"
#include "sim/eventq.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target uname() handler.
static SyscallReturn sys_getsysinfoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target sys_getsysyinfo() handler.
static SyscallReturn sys_setsysinfoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target sys_setsysinfo() handler.
static SyscallReturn setThreadAreaFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Function Documentation
setThreadAreaFunc()
static SyscallReturn setThreadAreaFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Definition at line 162 of file process.cc.
References addr, brkFunc(), chownFunc(), closeFunc(), exitFunc(), fchownFunc(), fcntl64Func(), fcntlFunc(), ftruncateFunc(), getcwdFunc(), getegidFunc(), geteuidFunc(), getgidFunc(), gethostnameFunc(), getpagesizeFunc(), getpidFunc(), ThreadContext::getProcessPtr(), getuidFunc(), ignoreFunc(), MipsISA::index, lseekFunc(), MipsISA::MISCREG_TP_VALUE, mkdirFunc(), munmapFunc(), pipePseudoFunc(), readlinkFunc(), ThreadContext::setMiscRegNoEffect(), setuidFunc(), sys_getsysinfoFunc(), sys_setsysinfoFunc(), MipsLinuxProcess::syscallDescs, truncateFunc(), umaskFunc(), unameFunc(), unimplementedFunc(), and unlinkFunc().
sys_getsysinfoFunc()
static SyscallReturn sys_getsysinfoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target sys_getsysyinfo() handler.
Even though this call is borrowed from Tru64, the subcases that get used appear to be different in practice from those used by Tru64 processes.
Definition at line 103 of file process.cc.
References BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and X86ISA::op.
Referenced by setThreadAreaFunc().
sys_setsysinfoFunc()
static SyscallReturn sys_setsysinfoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target sys_setsysinfo() handler.
Definition at line 132 of file process.cc.
References BaseBufferArg::copyIn(), DPRINTFR, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, letoh(), and X86ISA::op.
Referenced by setThreadAreaFunc().
unameFunc()
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, ThreadContext * tc) static
Target uname() handler.
Definition at line 83 of file process.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and name().
Referenced by setThreadAreaFunc().