gem5: arch/arm/vtophys.cc File Reference
vtophys.cc File Reference
#include "arch/arm/vtophys.hh"
#include <string>
#include "arch/arm/faults.hh"
#include "arch/arm/table_walker.hh"
#include "arch/arm/tlb.hh"
#include "base/chunk_generator.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "mem/fs_translating_port_proxy.hh"
Functions
static std::pair< bool, Addr > try_translate (ThreadContext *tc, Addr addr)
Function Documentation
try_translate()
static std::pair<bool, Addr> try_translate (ThreadContext * tc, Addr addr) static
Definition at line 68 of file vtophys.cc.
References addr, ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), NoFault, BaseTLB::Read, ArmISA::tlb, and BaseTLB::translateFunctional().
Referenced by ArmISA::virtvalid(), and ArmISA::vtophys().