gem5: base/atomicio.hh File Reference
atomicio.hh File Reference
#include <unistd.h>
Macros
#define STATIC_MSG(fd, m)
Statically allocate a string and write it to a file descriptor.
#define STATIC_ERR(m) STATIC_MSG(STDERR_FILENO, m)
Statically allocate a string and write it to STDERR.
Functions
ssize_t atomic_read (int fd, void *s, size_t n)
ssize_t atomic_write (int fd, const void *s, size_t n)
Macro Definition Documentation
STATIC_ERR
#define STATIC_ERR (m) STATIC_MSG(STDERR_FILENO, m)
Statically allocate a string and write it to STDERR.
Warning
The return value will from atomic_write will be ignored which means that errors will be ignored. This is normally fine as this macro is intended to be used in fatal signal handlers where error handling might not be feasible.
Definition at line 66 of file atomicio.hh.
Referenced by abortHandler(), print_backtrace(), raiseFatalSignal(), and segvHandler().
STATIC_MSG
#define STATIC_MSG (fd, m)
Value:
do {                                                        \
        static const char msg[] = m;                            \
        atomic_write(fd, msg, sizeof(msg) - 1);                 \
    } while (0)
Statically allocate a string and write it to a file descriptor.
Warning
The return value will from atomic_write will be ignored which means that errors will be ignored. This is normally fine as this macro is intended to be used in fatal signal handlers where error handling might not be feasible.
Definition at line 52 of file atomicio.hh.
Function Documentation
atomic_read()
ssize_t atomic_read (int fd, void * s, size_t n)
Definition at line 37 of file atomicio.cc.
References MipsISA::p, and ArmISA::s.
Referenced by TEST().
atomic_write()
ssize_t atomic_write (int fd, const void * s, size_t n)
Definition at line 66 of file atomicio.cc.
References MipsISA::p, and ArmISA::s.
Referenced by Terminal::accept(), VncServer::accept(), TEST(), Terminal::write(), and VncServer::write().