gem5: base/debug.cc File Reference
debug.cc File Reference
#include "base/debug.hh"
#include <sys/types.h>
#include <unistd.h>
#include <algorithm>
#include <csignal>
#include "base/cprintf.hh"
#include "base/logging.hh"
Classes
struct Debug::AllFlags
Namespaces
Debug
Functions
void Debug::breakpoint ()
FlagsMap & Debug::allFlags ()
Flag * Debug::findFlag (const std::string &name)
bool Debug::changeFlag (const char *s, bool value)
void setDebugFlag (const char *string)
void clearDebugFlag (const char *string)
void dumpDebugFlags ()
Variables
int Debug::allFlagsVersion = 0
AllFlags Debug::theAllFlags
Flag *const Debug::All = &theAllFlags
Function Documentation
clearDebugFlag()
void clearDebugFlag (const char * string)
Definition at line 185 of file debug.cc.
References Debug::changeFlag().
Referenced by pybind_init_debug().
dumpDebugFlags()
void dumpDebugFlags ()
Definition at line 191 of file debug.cc.
References Debug::allFlags(), cprintf(), ArmISA::f, ArmISA::i, Debug::Flag::name(), and Debug::SimpleFlag::status().
Referenced by pybind_init_debug().
setDebugFlag()
void setDebugFlag (const char * string)
Definition at line 179 of file debug.cc.
References Debug::changeFlag().
Referenced by pybind_init_debug(), and Trace::TarmacTracer::TarmacTracer().