gem5: base/time.cc File Reference
time.cc File Reference
#include "base/time.hh"
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <sstream>
#include "base/logging.hh"
#include "config/use_posix_clock.hh"
#include "sim/core.hh"
#include "sim/serialize.hh"
Functions
void sleep (const Time &time)
time_t mkutctime (struct tm *time)
Function Documentation
mkutctime()
time_t mkutctime (struct tm * time)
Definition at line 155 of file time.cc.
References fatal, and ArmISA::tz.
Referenced by ArmSemihosting::ArmSemihosting(), DumbTOD::DumbTOD(), operator<<(), and MC146818::tickClock().
sleep()
void sleep (const Time & time)
Definition at line 143 of file time.cc.
References ArmISA::ts.
Referenced by Time::operator-=(), and Root::timeSync().