gem5: base/debug.hh File Reference
debug.hh File Reference
#include <map>
#include <string>
#include <vector>
Classes
class Debug::Flag
class Debug::SimpleFlag
class Debug::CompoundFlag
Namespaces
Debug
Typedefs
typedef std::map< std::string, Flag * > Debug::FlagsMap
Functions
void Debug::breakpoint ()
FlagsMap & Debug::allFlags ()
Flag * Debug::findFlag (const std::string &name)
bool Debug::changeFlag (const char *s, bool value)
void setDebugFlag (const char *string)
void clearDebugFlag (const char *string)
void dumpDebugFlags ()
Function Documentation
clearDebugFlag()
void clearDebugFlag (const char * string)
Definition at line 185 of file debug.cc.
References Debug::changeFlag().
Referenced by pybind_init_debug().
dumpDebugFlags()
void dumpDebugFlags ()
Definition at line 191 of file debug.cc.
References Debug::allFlags(), cprintf(), ArmISA::f, ArmISA::i, Debug::Flag::name(), and Debug::SimpleFlag::status().
Referenced by pybind_init_debug().
setDebugFlag()
void setDebugFlag (const char * string)
Definition at line 179 of file debug.cc.
References Debug::changeFlag().
Referenced by pybind_init_debug(), and Trace::TarmacTracer::TarmacTracer().