gem5: sim/byteswap.test.cc File Reference
byteswap.test.cc File Reference
#include <gtest/gtest.h>
#include "sim/byteswap.hh"
Functions
TEST (ByteswapTest, swap_byte64)
TEST (ByteswapTest, swap_byte32)
TEST (ByteswapTest, swap_byte16)
TEST (ByteswapTest, swap_byte)
TEST (ByteswapTest, htog)
TEST (ByteswapTest, gtoh)
TEST (ByteswapTest, betole)
TEST (ByteswapTest, letobe)
Function Documentation
TEST() [1/8]
TEST (ByteswapTest , swap_byte64)
Definition at line 35 of file byteswap.test.cc.
References EXPECT_EQ, and swap_byte64().
TEST() [2/8]
TEST (ByteswapTest , swap_byte32)
Definition at line 45 of file byteswap.test.cc.
References EXPECT_EQ, and swap_byte32().
TEST() [3/8]
TEST (ByteswapTest , swap_byte16)
Definition at line 55 of file byteswap.test.cc.
References EXPECT_EQ, and swap_byte16().
TEST() [4/8]
TEST (ByteswapTest , swap_byte)
Definition at line 65 of file byteswap.test.cc.
References EXPECT_EQ, and swap_byte().
TEST() [5/8]
TEST (ByteswapTest , htog)
Definition at line 87 of file byteswap.test.cc.
References BigEndianByteOrder, EXPECT_EQ, htog(), and LittleEndianByteOrder.
TEST() [6/8]
TEST (ByteswapTest , gtoh)
Definition at line 192 of file byteswap.test.cc.
References BigEndianByteOrder, EXPECT_EQ, gtoh(), and LittleEndianByteOrder.
TEST() [7/8]
TEST (ByteswapTest , betole)
Definition at line 297 of file byteswap.test.cc.
References betole(), and EXPECT_EQ.
TEST() [8/8]
TEST (ByteswapTest , letobe)
Definition at line 319 of file byteswap.test.cc.
References EXPECT_EQ, and letobe().