gem5: sim/byteswap.hh File Reference
byteswap.hh File Reference
#include "base/logging.hh"
#include "base/types.hh"
#include <machine/endian.h>
Functions
uint64_t swap_byte64 (uint64_t x)
uint32_t swap_byte32 (uint32_t x)
uint16_t swap_byte16 (uint16_t x)
template<typename T >
T swap_byte (T x)
template<typename T , size_t N>
std::array< T, N > swap_byte (std::array< T, N > a)
template<typename T >
T betole (T value)
template<typename T >
T letobe (T value)
template<typename T >
T htole (T value)
template<typename T >
T letoh (T value)
template<typename T >
T htobe (T value)
template<typename T >
T betoh (T value)
template<typename T >
T htog (T value, ByteOrder guest_byte_order)
template<typename T >
T gtoh (T value, ByteOrder guest_byte_order)
Variables
const ByteOrder HostByteOrder = BigEndianByteOrder
Function Documentation
betoh()
template<typename T > T betoh (T value) inline
Definition at line 147 of file byteswap.hh.
References HostByteOrder, htobe(), htole(), letoh(), LittleEndianByteOrder, and swap_byte().
Referenced by Trace::SparcNativeTrace::check(), DtbFile::findReleaseAddr(), BasePrefetcher::PrefetchInfo::get(), Packet::getBE(), gtoh(), SparcISA::Decoder::moreBytes(), PowerISA::Decoder::moreBytes(), VncServer::recvCutText(), VncServer::recvKeyboardInput(), VncServer::recvPointerInput(), VncServer::requestFbUpdate(), UFSHostDevice::UFSSCSIDevice::SCSICMDHandle(), VncServer::setEncodings(), VncServer::setPixelFormat(), PowerISA::RemoteGDB::PowerGdbRegCache::setRegs(), and SparcISA::vtophys().
betole()
template<typename T > T betole (T value) inline
Definition at line 137 of file byteswap.hh.
References swap_byte().
Referenced by TEST().
gtoh()
template<typename T > T gtoh (T value, ByteOrder guest_byte_order) inline
Definition at line 166 of file byteswap.hh.
References betoh(), BigEndianByteOrder, and letoh().
Referenced by amoMemAtomic(), dumpDmesgEntry(), PortProxy::read(), VirtQueue::VirtRing< struct vring_used_elem >::read(), VirtQueue::VirtRing< struct vring_used_elem >::readHeader(), readMemAtomic(), readvFunc(), TEST(), VirtDescriptor::update(), utimesFunc(), writeMemAtomic(), and writevFunc().
htobe()
template<typename T > T htobe (T value) inline
Definition at line 146 of file byteswap.hh.
Referenced by PowerProcess::argsInit(), SparcProcess::argsInit(), betoh(), VncServer::checkProtocolVersion(), VncServer::checkSecurity(), ElfObject::determineOpSys(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), PowerISA::RemoteGDB::PowerGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::getRegs(), SparcISA::getresuidFunc(), htog(), IGbE::IGbE(), VncServer::sendFrameBufferResized(), VncServer::sendFrameBufferUpdate(), VncServer::sendServerInit(), Packet::setBE(), and MmDisk::write().
htog()
template<typename T > T htog (T value, ByteOrder guest_byte_order) inline
Definition at line 159 of file byteswap.hh.
References BigEndianByteOrder, htobe(), and htole().
Referenced by _llseekFunc(), clock_gettimeFunc(), convertStat64Buf(), convertStatBuf(), copyOutStatfsBuf(), copyStringArray(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), ArmISA::TableWalker::doLongDescriptor(), getrlimitFunc(), getrusageFunc(), gettimeofdayFunc(), VirtIOBlock::RequestQueue::onNotifyDescriptor(), prlimitFunc(), VirtIOConsole::readConfig(), VirtIOBlock::readConfig(), readvFunc(), rmdirFunc(), TEST(), timeFunc(), timesFunc(), VirtIO9PBase::VirtIO9PBase(), PortProxy::write(), VirtQueue::VirtRing< struct vring_used_elem >::write(), VirtQueue::VirtRing< struct vring_used_elem >::writeHeader(), writeMemAtomic(), and writeMemTiming().
htole()
template<typename T > T htole (T value) inline
Definition at line 144 of file byteswap.hh.
References swap_byte().
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), betoh(), ArmISA::ArmStaticInst::cSwap(), ElfObject::determineOpSys(), X86ISA::handleIprRead(), X86ISA::handleIprWrite(), htog(), htop9(), IdeController::IdeController(), AlphaSystem::initState(), LinuxX86System::initState(), X86System::initState(), LinuxAlphaSystem::initState(), PciDevice::PciDevice(), PciVirtIO::PciVirtIO(), IGbE::RxDescCache::pktComplete(), X86ISA::Interrupts::read(), IdeController::readConfig(), AlphaSystem::setAlphaAccess(), Packet::setLE(), IdeController::writeConfig(), PciDevice::writeConfig(), X86ISA::writeMemAtomic(), X86ISA::writeMemTiming(), X86ISA::SMBios::SMBiosStructure::writeOut(), X86ISA::SMBios::BiosInformation::writeOut(), X86ISA::SMBios::SMBiosTable::writeOut(), writeOutField(), X86ISA::writePackedMem(), IGbE::RxDescCache::writePacket(), X86ISA::E820Table::writeTo(), and writeVal().
letobe()
template<typename T > T letobe (T value) inline
Definition at line 138 of file byteswap.hh.
References swap_byte().
Referenced by ArmISA::ArmStaticInst::cSwap(), and TEST().
letoh()
template<typename T > T letoh (T value) inline
Definition at line 145 of file byteswap.hh.
References swap_byte().
Referenced by betoh(), ArmISA::ArmStaticInst::cSwap(), BasePrefetcher::PrefetchInfo::get(), Packet::getLE(), gtoh(), X86ISA::handleIprWrite(), PciDevice::interruptLine(), AlphaISA::Decoder::moreBytes(), MipsISA::Decoder::moreBytes(), RiscvISA::Decoder::moreBytes(), ArmISA::Decoder::moreBytes(), X86ISA::Decoder::moreBytes(), osf_setsysinfoFunc(), p9toh(), PciDevice::PciDevice(), X86ISA::readMemAtomic(), X86ISA::readPackedMemAtomic(), SafeReadSwap(), SafeWriteSwap(), sys_setsysinfoFunc(), Trace::InstPBTrace::traceInst(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), X86ISA::Interrupts::write(), IdeController::writeConfig(), PciDevice::writeConfig(), X86ISA::writeMemAtomic(), and X86ISA::SMBios::SMBiosTable::writeOut().
swap_byte() [1/2]
template<typename T > T swap_byte (T x) inline
Definition at line 113 of file byteswap.hh.
References panic, swap_byte16(), swap_byte32(), swap_byte64(), and X86ISA::x.
Referenced by betoh(), betole(), htole(), letobe(), letoh(), and swap_byte().
swap_byte() [2/2]
template<typename T , size_t N> std::array<T, N> swap_byte (std::array< T, N > a) inline
Definition at line 128 of file byteswap.hh.
References ArmISA::a, swap_byte(), and ArmISA::v.
swap_byte16()
uint16_t swap_byte16 (uint16_t x) inline
Definition at line 96 of file byteswap.hh.
References X86ISA::x.
Referenced by swap_byte(), and TEST().
swap_byte32()
uint32_t swap_byte32 (uint32_t x) inline
Definition at line 82 of file byteswap.hh.
References X86ISA::x.
Referenced by swap_byte(), and TEST().
swap_byte64()
uint64_t swap_byte64 (uint64_t x) inline
Definition at line 63 of file byteswap.hh.
References ULL, and X86ISA::x.
Referenced by swap_byte(), and TEST().
Variable Documentation
HostByteOrder
const ByteOrder HostByteOrder = BigEndianByteOrder
Definition at line 143 of file byteswap.hh.
Referenced by betoh().