gem5: base/callback.test.cc File Reference
callback.test.cc File Reference
#include <gtest/gtest.h>
#include "base/callback.hh"
Classes
class CallbackImpl
class MockClass
Functions
TEST (CallbackQueueTest, GetName)
TEST (CallbackQueueTest, IsEmpty)
TEST (CallbackQueueTest, IsNotEmpty)
TEST (CallbackQueueTest, AddOneAndProcess)
TEST (CallbackQueueTest, AddManyAndProcess)
TEST (CallbackQueueTest, ClearQueue)
TEST (CallbackQueueTest, MakeCallbackAddByReference)
TEST (CallbackQueueTest, MakeCallbackAddByPointer)
Function Documentation
TEST() [1/8]
TEST (CallbackQueueTest , GetName)
Definition at line 64 of file callback.test.cc.
References EXPECT_EQ, and CallbackQueue::name().
TEST() [2/8]
TEST (CallbackQueueTest , IsEmpty)
Definition at line 70 of file callback.test.cc.
References CallbackQueue::empty(), and EXPECT_TRUE.
TEST() [3/8]
TEST (CallbackQueueTest , IsNotEmpty)
Definition at line 76 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::empty(), EXPECT_FALSE, and MipsISA::impl.
TEST() [4/8]
TEST (CallbackQueueTest , AddOneAndProcess)
Definition at line 84 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::empty(), EXPECT_FALSE, EXPECT_TRUE, MipsISA::impl, CallbackQueue::process(), and CallbackImpl::processed.
TEST() [5/8]
TEST (CallbackQueueTest , AddManyAndProcess)
Definition at line 96 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::empty(), EXPECT_FALSE, EXPECT_TRUE, CallbackQueue::process(), and CallbackImpl::processed.
TEST() [6/8]
TEST (CallbackQueueTest , ClearQueue)
Definition at line 119 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::clear(), CallbackQueue::empty(), EXPECT_FALSE, and EXPECT_TRUE.
TEST() [7/8]
TEST (CallbackQueueTest , MakeCallbackAddByReference)
Definition at line 129 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::empty(), EXPECT_FALSE, EXPECT_TRUE, MockClass::method(), MockClass::methodExecuted, and CallbackQueue::process().
TEST() [8/8]
TEST (CallbackQueueTest , MakeCallbackAddByPointer)
Definition at line 140 of file callback.test.cc.
References CallbackQueue::add(), CallbackQueue::empty(), EXPECT_FALSE, EXPECT_TRUE, MockClass::method(), MockClass::methodExecuted, and CallbackQueue::process().