gem5: base/cast.hh File Reference
cast.hh File Reference
#include <cassert>
Functions
template<class T , class U >
T safe_cast (U ptr)
Function Documentation
safe_cast()
template<class T , class U > T safe_cast (U ptr) inline
Definition at line 61 of file cast.hh.
Referenced by GPUCoalescer::atomicCallback(), SMMUv3SlaveInterface::atsMasterRecvTimingResp(), TLBCoalescer::canCoalesce(), GPUCoalescer::completeHitCallback(), Shader::functionalTLBAccess(), GarnetNetwork::GarnetNetwork(), X86ISA::GpuTLB::handleFuncTranslationReturn(), X86ISA::GpuTLB::handleTranslationReturn(), GPUCoalescer::hitCallback(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::info(), GarnetNetwork::init(), FetchUnit::initiateFetch(), X86ISA::GpuTLB::issueTLBLookup(), GarnetNetwork::makeExtInLink(), SimpleNetwork::makeExtOutLink(), GarnetNetwork::makeExtOutLink(), SimpleNetwork::makeInternalLink(), GarnetNetwork::makeInternalLink(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvTimingResp(), Packet::popLabel(), Stats::DistStor::prepare(), Stats::HistStor::prepare(), Stats::SampleStor::prepare(), Stats::AvgSampleStor::prepare(), FetchStage::processFetchReturn(), FetchUnit::processFetchReturn(), ComputeUnit::DataPort::processMemReqEvent(), ComputeUnit::DataPort::processMemRespEvent(), TLBCoalescer::processProbeTLBEvent(), Packet::pushLabel(), TLBCoalescer::CpuSidePort::recvFunctional(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), TLBCoalescer::CpuSidePort::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), RubyTester::CpuPort::recvTimingResp(), Gicv3Its::recvTimingResp(), Minor::Fetch1::recvTimingResp(), ComputeUnit::DataPort::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), ComputeUnit::ITLBPort::recvTimingResp(), Minor::LSQ::recvTimingResp(), Stats::DistStor::reset(), Stats::HistStor::reset(), RubyPort::ruby_hit_callback(), ComputeUnit::sendRequest(), SimpleNetwork::SimpleNetwork(), X86ISA::GpuTLB::translationReturn(), Packet::trySatisfyFunctional(), and TLBCoalescer::updatePhysAddresses().