gem5: base/circlebuf.hh File Reference
circlebuf.hh File Reference
#include <algorithm>
#include <cassert>
#include <vector>
#include "base/circular_queue.hh"
#include "base/logging.hh"
#include "sim/serialize.hh"
Classes
class CircleBuf< T >
Circular buffer backed by a vector though a CircularQueue.
class Fifo< T >
Simple FIFO implementation backed by a circular buffer.
Functions
template<typename T >
void arrayParamOut (CheckpointOut &cp, const std::string &name, const CircleBuf< T > &param)
template<typename T >
void arrayParamIn (CheckpointIn &cp, const std::string &name, CircleBuf< T > &param)
template<typename T >
void arrayParamOut (CheckpointOut &cp, const std::string &name, const Fifo< T > &param)
template<typename T >
void arrayParamIn (CheckpointIn &cp, const std::string &name, Fifo< T > &param)
Function Documentation
arrayParamIn() [1/2]
template<typename T > void arrayParamIn (CheckpointIn & cp, const std::string & name, CircleBuf< T > & param)
Definition at line 186 of file circlebuf.hh.
References CircularQueue< T >::flush(), and CircleBuf< T >::write().
Referenced by arrayParamIn(), PS2Device::unserialize(), EthPacketData::unserialize(), Globals::unserialize(), CopyEngine::CopyEngineChannel::unserialize(), MC146818::unserialize(), IGbE::DescCache< iGbReg::RxDesc >::unserialize(), and unserialize().
arrayParamIn() [2/2]
template<typename T > void arrayParamIn (CheckpointIn & cp, const std::string & name, Fifo< T > & param)
Definition at line 208 of file circlebuf.hh.
References arrayParamIn(), Fifo< T >::capacity(), fatal_if, Fifo< T >::flush(), and Fifo< T >::write().
arrayParamOut() [1/2]
template<typename T > void arrayParamOut (CheckpointOut & cp, const std::string & name, const CircleBuf< T > & param)
Definition at line 176 of file circlebuf.hh.
References CircleBuf< T >::peek(), and CircularQueue< T >::size().
Referenced by arrayParamOut(), AnnotateDumpCallback::process(), PS2Device::serialize(), EthPacketData::serialize(), CopyEngine::CopyEngineChannel::serialize(), MC146818::serialize(), IGbE::DescCache< iGbReg::RxDesc >::serialize(), and serialize().
arrayParamOut() [2/2]
template<typename T > void arrayParamOut (CheckpointOut & cp, const std::string & name, const Fifo< T > & param)
Definition at line 198 of file circlebuf.hh.
References arrayParamOut(), Fifo< T >::peek(), and Fifo< T >::size().