gem5: PS2Device Class Reference
PS2Device Class Reference abstract
#include <device.hh>
Public Member Functions
PS2Device (const PS2DeviceParams *p)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void hostRegDataAvailable (const std::function< void()> &c)
Register a data available callback into the PS/2 interface.
bool hostDataAvailable () const
Check if there is pending data from the PS/2 device.
uint8_t hostRead ()
Read a character from the device.
void hostWrite (uint8_t c)
Transmit a character from the host interface to the device.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
virtual bool recv (const std::vector< uint8_t > &data)=0
Data received from host.
void send (const uint8_t *data, size_t size)
Send data from a PS/2 device to a host.
void send (const std::vector< uint8_t > &data)
void send (uint8_t data)
Send a byte of data from a PS/2 device to a host.
void sendAck ()
Send an ACK byte to the host.
size_t sendPending () const
Output buffer size.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Attributes
std::deque< uint8_t > outBuffer
Device -> host FIFO.
std::vector< uint8_t > inBuffer
Host -> device buffer.
std::function< void()> dataAvailableCallback
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 54 of file device.hh.
Constructor & Destructor Documentation
PS2Device()
PS2Device::PS2Device (const PS2DeviceParams * p)
Definition at line 51 of file device.cc.
References inBuffer.
Member Function Documentation
hostDataAvailable()
bool PS2Device::hostDataAvailable () const inline
Check if there is pending data from the PS/2 device.
Returns
true if there is data pending that can be read using the readData() method.
Definition at line 76 of file device.hh.
References ArmISA::c, data, hostRead(), hostWrite(), outBuffer, recv(), and send().
Referenced by Pl050::read(), X86ISA::I8042::readDataOut(), Pl050::updateRxInt(), and X86ISA::I8042::write().
hostRead()
uint8_t PS2Device::hostRead ()
Read a character from the device.
Returns
Character from the device's output buffer, undefined if no data is pending.
Definition at line 89 of file device.cc.
References data, and outBuffer.
Referenced by hostDataAvailable(), Pl050::read(), X86ISA::I8042::readDataOut(), and X86ISA::I8042::write().
hostRegDataAvailable()
void PS2Device::hostRegDataAvailable (const std::function< void()> & c)
Register a data available callback into the PS/2 interface.
Parameters
c Callback instance from host interface
Definition at line 79 of file device.cc.
References ArmISA::c, dataAvailableCallback, and fatal_if.
Referenced by Pl050::Pl050().
hostWrite()
void PS2Device::hostWrite (uint8_t c)
Transmit a character from the host interface to the device.
Parameters
c Received data.
Definition at line 97 of file device.cc.
References DPRINTF, inBuffer, and recv().
Referenced by hostDataAvailable(), Pl050::write(), and X86ISA::I8042::write().
recv()
virtual bool PS2Device::recv (const std::vector< uint8_t > & data) protected pure virtual
Data received from host.
Data sent to the device is buffered one byte at a time. Each time a byte is added, this function is called and passed the current buffer. It should return true if it has consumed the data and the buffer can be cleared, or false if more data is needed to process the current command.
Parameters
data Pending input data (at least one byte)
Returns
false if more data is needed to process the current command, true otherwise.
Implemented in PS2Mouse, PS2TouchKit, and PS2Keyboard.
Referenced by hostDataAvailable(), and hostWrite().
send() [1/3]
void PS2Device::send (const uint8_t * data, size_t size) protected
Send data from a PS/2 device to a host.
Parameters
data Pointer to data array
size Size of the data array
Definition at line 106 of file device.cc.
References dataAvailableCallback, DPRINTF, and outBuffer.
Referenced by hostDataAvailable(), PS2Keyboard::keyPress(), PS2TouchKit::mouseAt(), PS2Keyboard::recv(), PS2TouchKit::recv(), PS2Mouse::recv(), send(), sendAck(), and PS2TouchKit::sendTouchKit().
send() [2/3]
void PS2Device::send (const std::vector< uint8_t > & data) inline protected
Definition at line 116 of file device.hh.
References send().
send() [3/3]
void PS2Device::send (uint8_t data) inline protected
Send a byte of data from a PS/2 device to a host.
Parameters
data Byte to send
Definition at line 125 of file device.hh.
References send(), and sendAck().
Referenced by send().
sendAck()
void PS2Device::sendAck () protected
Send an ACK byte to the host.
Definition at line 121 of file device.cc.
References Ps2::Ack, and send().
Referenced by PS2Keyboard::recv(), PS2TouchKit::recv(), PS2Mouse::recv(), PS2TouchKit::recvTouchKit(), and send().
sendPending()
size_t PS2Device::sendPending () const inline protected
Output buffer size.
Device models may use this method to query the size of the output buffer to do rate limiting.
Definition at line 136 of file device.hh.
References outBuffer.
Referenced by PS2TouchKit::mouseAt().
serialize()
void PS2Device::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in PS2Mouse, PS2TouchKit, and PS2Keyboard.
Definition at line 58 of file device.cc.
References arrayParamOut(), inBuffer, outBuffer, and SERIALIZE_CONTAINER.
Referenced by PS2Keyboard::serialize(), PS2TouchKit::serialize(), and PS2Mouse::serialize().
unserialize()
void PS2Device::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in PS2Mouse, PS2TouchKit, and PS2Keyboard.
Definition at line 68 of file device.cc.
References arrayParamIn(), ArmISA::c, inBuffer, outBuffer, and UNSERIALIZE_CONTAINER.
Referenced by PS2Keyboard::unserialize(), PS2TouchKit::unserialize(), and PS2Mouse::unserialize().
Member Data Documentation
dataAvailableCallback
std::function<void()> PS2Device::dataAvailableCallback private
Definition at line 145 of file device.hh.
Referenced by hostRegDataAvailable(), and send().
inBuffer
std::vector<uint8_t> PS2Device::inBuffer private
Host -> device buffer.
Definition at line 143 of file device.hh.
Referenced by hostWrite(), PS2Device(), serialize(), and unserialize().
outBuffer
std::deque<uint8_t> PS2Device::outBuffer private
Device -> host FIFO.
Definition at line 140 of file device.hh.
Referenced by hostDataAvailable(), hostRead(), send(), sendPending(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/ps2/device.hh
dev/ps2/device.cc