gem5: tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process Class Reference
Public Types
typedef sync_enum_type(MODULE::* NBTransportPtr) (int id, transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* BTransportPtr) (int id, transaction_type &, sc_core::sc_time &)
typedef unsigned int(MODULE::* TransportDbgPtr) (int id, transaction_type &)
typedef bool(MODULE::* GetDirectMem_ptr) (int id, transaction_type &, tlm::tlm_dmi &)
Public Member Functions
process (passthrough_socket_base *owner)
void set_nb_transport_user_id (int id)
void set_b_transport_user_id (int id)
void set_transport_dbg_user_id (int id)
void set_get_dmi_user_id (int id)
void set_nb_transport_ptr (MODULE *mod, NBTransportPtr p)
void set_b_transport_ptr (MODULE *mod, BTransportPtr p)
void set_transport_dbg_ptr (MODULE *mod, TransportDbgPtr p)
void set_get_direct_mem_ptr (MODULE *mod, GetDirectMem_ptr p)
sync_enum_type nb_transport_fw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void b_transport (transaction_type &trans, sc_core::sc_time &t)
unsigned int transport_dbg (transaction_type &trans)
bool get_direct_mem_ptr (transaction_type &trans, tlm::tlm_dmi &dmi_data)
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Private Attributes
MODULE * m_mod
NBTransportPtr m_nb_transport_ptr
BTransportPtr m_b_transport_ptr
TransportDbgPtr m_transport_dbg_ptr
GetDirectMem_ptr m_get_direct_mem_ptr
int m_nb_transport_user_id
int m_b_transport_user_id
int m_transport_dbg_user_id
int m_get_dmi_user_id
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from tlm_utils::convenience_socket_cb_holder
convenience_socket_cb_holder (convenience_socket_base *owner)
void display_warning (const char *msg) const
void display_error (const char *msg) const
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process
Definition at line 320 of file passthrough_target_socket.h.
Member Typedef Documentation
BTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::BTransportPtr) (int id, transaction_type &, sc_core::sc_time &)
Definition at line 326 of file passthrough_target_socket.h.
GetDirectMem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef bool(MODULE::* tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::GetDirectMem_ptr) (int id, transaction_type &, tlm::tlm_dmi &)
Definition at line 330 of file passthrough_target_socket.h.
NBTransportPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::NBTransportPtr) (int id, transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 324 of file passthrough_target_socket.h.
TransportDbgPtr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef unsigned int(MODULE::* tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::TransportDbgPtr) (int id, transaction_type &)
Definition at line 328 of file passthrough_target_socket.h.
Constructor & Destructor Documentation
process()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::process (passthrough_socket_base * owner) inline
Definition at line 333 of file passthrough_target_socket.h.
Member Function Documentation
b_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport (transaction_type & trans, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_blocking_transport_if< TYPES::tlm_payload_type >.
Definition at line 426 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_error(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, sc_assert, and ArmISA::t.
get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::get_direct_mem_ptr (transaction_type & trans, tlm::tlm_dmi & dmi_data) inline virtual
Implements tlm::tlm_fw_direct_mem_if< TYPES::tlm_payload_type >.
Definition at line 451 of file passthrough_target_socket.h.
References tlm::tlm_dmi::allow_read_write(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, sc_assert, tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline virtual
Implements tlm::tlm_fw_nonblocking_transport_if< TYPES::tlm_payload_type, TYPES::tlm_phase_type >.
Definition at line 412 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_error(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr, sc_assert, ArmISA::t, and tlm::TLM_COMPLETED.
set_b_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr (MODULE * mod, BTransportPtr p) inline
Definition at line 375 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, mod(), MipsISA::p, and sc_assert.
set_b_transport_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_user_id (int id) inline
Definition at line 347 of file passthrough_target_socket.h.
References ArmISA::id.
set_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr (MODULE * mod, GetDirectMem_ptr p) inline
Definition at line 399 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, mod(), MipsISA::p, and sc_assert.
set_get_dmi_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_dmi_user_id (int id) inline
Definition at line 357 of file passthrough_target_socket.h.
References ArmISA::id.
set_nb_transport_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr (MODULE * mod, NBTransportPtr p) inline
Definition at line 363 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr, mod(), MipsISA::p, and sc_assert.
set_nb_transport_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_user_id (int id) inline
Definition at line 342 of file passthrough_target_socket.h.
References ArmISA::id.
set_transport_dbg_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr (MODULE * mod, TransportDbgPtr p) inline
Definition at line 387 of file passthrough_target_socket.h.
References tlm_utils::convenience_socket_cb_holder::display_warning(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr, mod(), MipsISA::p, and sc_assert.
set_transport_dbg_user_id()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_user_id (int id) inline
Definition at line 352 of file passthrough_target_socket.h.
References ArmISA::id.
transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::transport_dbg (transaction_type & trans) inline virtual
Implements tlm::tlm_transport_dbg_if< TYPES::tlm_payload_type >.
Definition at line 438 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr, and sc_assert.
Member Data Documentation
m_b_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> BTransportPtr tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_ptr private
Definition at line 469 of file passthrough_target_socket.h.
m_b_transport_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_b_transport_user_id private
Definition at line 473 of file passthrough_target_socket.h.
m_get_direct_mem_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> GetDirectMem_ptr tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_direct_mem_ptr private
Definition at line 471 of file passthrough_target_socket.h.
m_get_dmi_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_get_dmi_user_id private
Definition at line 475 of file passthrough_target_socket.h.
m_mod
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> MODULE* tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_mod private
Definition at line 467 of file passthrough_target_socket.h.
m_nb_transport_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> NBTransportPtr tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_ptr private
Definition at line 468 of file passthrough_target_socket.h.
m_nb_transport_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_nb_transport_user_id private
Definition at line 472 of file passthrough_target_socket.h.
m_transport_dbg_ptr
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> TransportDbgPtr tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_ptr private
Definition at line 470 of file passthrough_target_socket.h.
m_transport_dbg_user_id
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::m_transport_dbg_user_id private
Definition at line 474 of file passthrough_target_socket.h.
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/passthrough_target_socket.h