gem5: MultiSocketSimpleSwitchAT Class Reference
MultiSocketSimpleSwitchAT Class Reference
#include <MultiSocketSimpleSwitchAT.h>
Classes
class BTag
class ConnectionInfo
class internalPEQTypes
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT > target_socket_type
typedef tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT > initiator_socket_type
Public Member Functions
SC_HAS_PROCESS (MultiSocketSimpleSwitchAT)
MultiSocketSimpleSwitchAT (sc_core::sc_module_name name)
void bindTargetSocket (initiator_socket_type::base_target_socket_type &target, sc_dt::uint64 low, sc_dt::uint64 high, sc_dt::uint64 mask=0xffffffffffffffffULL)
unsigned int decode (const sc_dt::uint64 &address)
void start_of_simulation ()
void b_transport (int initiator_id, transaction_type &trans, sc_core::sc_time &t)
void free (transaction_type *txn)
void initiatorNBTransport_core (transaction_type &trans, phase_type &phase, sc_core::sc_time &t, unsigned int tgtSocketNumber)
sync_enum_type initiatorNBTransport (int initiator_id, transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
sync_enum_type targetNBTransport (int portId, transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void bwPEQcb (transaction_type &trans, const phase_type &phase)
void fwPEQcb (transaction_type &trans, const phase_type &phase)
void dump_status ()
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from tlm::tlm_mm_interface
virtual ~tlm_mm_interface ()
Public Attributes
target_socket_type target_socket
Private Attributes
initiator_socket_type initiator_socket
SimpleAddressMap m_addrMap
std::vector< std::deque< transaction_type * > > m_pendingReqs
std::vector< std::deque< transaction_type * > > m_pendingResps
std::vector< sc_dt::uint64 > m_masks
tlm_utils::instance_specific_extension_accessor accessMySpecificExtensions
tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT > m_bwPEQ
tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT > m_fwPEQ
ExtensionPool< ConnectionInfo > m_connInfoPool
unsigned int m_target_count
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
Definition at line 46 of file MultiSocketSimpleSwitchAT.h.
Member Typedef Documentation
initiator_socket_type
typedef tlm_utils::multi_passthrough_initiator_socket<MultiSocketSimpleSwitchAT> MultiSocketSimpleSwitchAT::initiator_socket_type
Definition at line 53 of file MultiSocketSimpleSwitchAT.h.
phase_type
typedef tlm::tlm_phase MultiSocketSimpleSwitchAT::phase_type
Definition at line 50 of file MultiSocketSimpleSwitchAT.h.
sync_enum_type
typedef tlm::tlm_sync_enum MultiSocketSimpleSwitchAT::sync_enum_type
Definition at line 51 of file MultiSocketSimpleSwitchAT.h.
target_socket_type
typedef tlm_utils::multi_passthrough_target_socket<MultiSocketSimpleSwitchAT> MultiSocketSimpleSwitchAT::target_socket_type
Definition at line 52 of file MultiSocketSimpleSwitchAT.h.
transaction_type
typedef tlm::tlm_generic_payload MultiSocketSimpleSwitchAT::transaction_type
Definition at line 49 of file MultiSocketSimpleSwitchAT.h.
Constructor & Destructor Documentation
MultiSocketSimpleSwitchAT()
MultiSocketSimpleSwitchAT::MultiSocketSimpleSwitchAT (sc_core::sc_module_name name) inline
Definition at line 96 of file MultiSocketSimpleSwitchAT.h.
References b_transport(), initiatorNBTransport(), tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_b_transport(), tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_nb_transport_bw(), tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_nb_transport_fw(), and targetNBTransport().
Member Function Documentation
b_transport()
void MultiSocketSimpleSwitchAT::b_transport (int initiator_id, transaction_type & trans, sc_core::sc_time & t) inline
Definition at line 134 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, tlm::tlm_generic_payload::acquire(), tlm::BEGIN_REQ, MultiSocketSimpleSwitchAT::BTag::event, tlm::tlm_generic_payload::get_ref_count(), tlm::tlm_generic_payload::has_mm(), initiatorNBTransport(), tlm::tlm_generic_payload::release(), sc_assert, tlm::tlm_generic_payload::set_mm(), and sc_core::sc_module::wait().
Referenced by MultiSocketSimpleSwitchAT().
bindTargetSocket()
void MultiSocketSimpleSwitchAT::bindTargetSocket (initiator_socket_type::base_target_socket_type & target, sc_dt::uint64 low, sc_dt::uint64 high, sc_dt::uint64 mask = 0xffffffffffffffffULL) inline
Definition at line 110 of file MultiSocketSimpleSwitchAT.h.
References initiator_socket, SimpleAddressMap::insert(), and ArmISA::mask.
bwPEQcb()
void MultiSocketSimpleSwitchAT::bwPEQcb (transaction_type & trans, const phase_type & phase) inline
Definition at line 239 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, tlm::BEGIN_REQ, tlm::BEGIN_RESP, MultiSocketSimpleSwitchAT::ConnectionInfo::bwID, MultiSocketSimpleSwitchAT::ConnectionInfo::clearReq, tlm::END_REQ, tlm::END_RESP, X86ISA::exit, MultiSocketSimpleSwitchAT::ConnectionInfo::fwID, initiatorNBTransport_core(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), MipsISA::p, sc_assert, sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, and tlm::TLM_UPDATED.
decode()
unsigned int MultiSocketSimpleSwitchAT::decode (const sc_dt::uint64 & address) inline
Definition at line 122 of file MultiSocketSimpleSwitchAT.h.
References SimpleAddressMap::decode().
Referenced by initiatorNBTransport().
dump_status()
void MultiSocketSimpleSwitchAT::dump_status () inline
Definition at line 324 of file MultiSocketSimpleSwitchAT.h.
References SimpleAddressMap::dumpMap(), ArmISA::i, sc_core::sc_object::name(), sc_core::sc_time_stamp(), tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >::size(), and tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::size().
free()
void MultiSocketSimpleSwitchAT::free (transaction_type * txn) inline virtual
Implements tlm::tlm_mm_interface.
Definition at line 159 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, MultiSocketSimpleSwitchAT::BTag::event, sc_core::sc_event::notify(), tlm::tlm_generic_payload::reset(), and sc_assert.
fwPEQcb()
void MultiSocketSimpleSwitchAT::fwPEQcb (transaction_type & trans, const phase_type & phase) inline
Definition at line 290 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, MultiSocketSimpleSwitchAT::ConnectionInfo::alreadyComplete, tlm::BEGIN_REQ, tlm::BEGIN_RESP, MultiSocketSimpleSwitchAT::ConnectionInfo::bwID, MultiSocketSimpleSwitchAT::BTag::event, ExtensionPool< T >::free(), MultiSocketSimpleSwitchAT::ConnectionInfo::fwID, tlm::tlm_generic_payload::get_address(), initiatorNBTransport_core(), sc_core::sc_event::notify(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), sc_assert, sc_core::SC_ZERO_TIME, tlm::tlm_generic_payload::set_address(), ArmISA::t, and tlm::TLM_COMPLETED.
initiatorNBTransport()
sync_enum_type MultiSocketSimpleSwitchAT::initiatorNBTransport (int initiator_id, transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline
Definition at line 197 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, MultiSocketSimpleSwitchAT::ConnectionInfo::alreadyComplete, tlm::BEGIN_REQ, MultiSocketSimpleSwitchAT::ConnectionInfo::bwID, MultiSocketSimpleSwitchAT::ConnectionInfo::clearReq, ExtensionPool< T >::construct(), decode(), tlm::END_RESP, X86ISA::exit, MultiSocketSimpleSwitchAT::ConnectionInfo::fwID, tlm::tlm_generic_payload::get_address(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), sc_assert, tlm::TLM_ACCEPTED, and tlm::TLM_COMPLETED.
Referenced by b_transport(), and MultiSocketSimpleSwitchAT().
initiatorNBTransport_core()
void MultiSocketSimpleSwitchAT::initiatorNBTransport_core (transaction_type & trans, phase_type & phase, sc_core::sc_time & t, unsigned int tgtSocketNumber) inline
Definition at line 168 of file MultiSocketSimpleSwitchAT.h.
References accessMySpecificExtensions, MultiSocketSimpleSwitchAT::ConnectionInfo::alreadyComplete, tlm::BEGIN_REQ, tlm::BEGIN_RESP, tlm::END_RESP, X86ISA::exit, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), sc_assert, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, and tlm::TLM_UPDATED.
Referenced by bwPEQcb(), and fwPEQcb().
SC_HAS_PROCESS()
MultiSocketSimpleSwitchAT::SC_HAS_PROCESS (MultiSocketSimpleSwitchAT)
start_of_simulation()
void MultiSocketSimpleSwitchAT::start_of_simulation () inline virtual
Reimplemented from sc_core::sc_module.
Definition at line 127 of file MultiSocketSimpleSwitchAT.h.
References tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >::size(), and tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::size().
targetNBTransport()
sync_enum_type MultiSocketSimpleSwitchAT::targetNBTransport (int portId, transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline
Definition at line 224 of file MultiSocketSimpleSwitchAT.h.
References tlm::BEGIN_RESP, tlm::END_REQ, X86ISA::exit, sc_core::sc_object::name(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), sc_assert, and tlm::TLM_ACCEPTED.
Referenced by MultiSocketSimpleSwitchAT().
Member Data Documentation
accessMySpecificExtensions
tlm_utils::instance_specific_extension_accessor MultiSocketSimpleSwitchAT::accessMySpecificExtensions private
Definition at line 64 of file MultiSocketSimpleSwitchAT.h.
Referenced by b_transport(), bwPEQcb(), free(), fwPEQcb(), initiatorNBTransport(), and initiatorNBTransport_core().
initiator_socket
initiator_socket_type MultiSocketSimpleSwitchAT::initiator_socket private
Definition at line 59 of file MultiSocketSimpleSwitchAT.h.
Referenced by bindTargetSocket().
m_addrMap
SimpleAddressMap MultiSocketSimpleSwitchAT::m_addrMap private
Definition at line 60 of file MultiSocketSimpleSwitchAT.h.
m_bwPEQ
tlm_utils::peq_with_cb_and_phase<MultiSocketSimpleSwitchAT> MultiSocketSimpleSwitchAT::m_bwPEQ private
Definition at line 65 of file MultiSocketSimpleSwitchAT.h.
m_connInfoPool
ExtensionPool<ConnectionInfo> MultiSocketSimpleSwitchAT::m_connInfoPool private
Definition at line 91 of file MultiSocketSimpleSwitchAT.h.
m_fwPEQ
tlm_utils::peq_with_cb_and_phase<MultiSocketSimpleSwitchAT> MultiSocketSimpleSwitchAT::m_fwPEQ private
Definition at line 66 of file MultiSocketSimpleSwitchAT.h.
m_masks
std::vector<sc_dt::uint64> MultiSocketSimpleSwitchAT::m_masks private
Definition at line 63 of file MultiSocketSimpleSwitchAT.h.
m_pendingReqs
std::vector<std::deque<transaction_type*> > MultiSocketSimpleSwitchAT::m_pendingReqs private
Definition at line 61 of file MultiSocketSimpleSwitchAT.h.
m_pendingResps
std::vector<std::deque<transaction_type*> > MultiSocketSimpleSwitchAT::m_pendingResps private
Definition at line 62 of file MultiSocketSimpleSwitchAT.h.
m_target_count
unsigned int MultiSocketSimpleSwitchAT::m_target_count private
Definition at line 92 of file MultiSocketSimpleSwitchAT.h.
target_socket
target_socket_type MultiSocketSimpleSwitchAT::target_socket
Definition at line 56 of file MultiSocketSimpleSwitchAT.h.
The documentation for this class was generated from the following file:
systemc/tests/tlm/multi_sockets/MultiSocketSimpleSwitchAT.h