gem5: Gicv3 Class Reference
Gicv3 Class Reference
#include <gic_v3.hh>
Public Types
enum IntStatus { INT_INACTIVE, INT_PENDING, INT_ACTIVE, INT_ACTIVE_PENDING }
enum GroupId { G0S, G1S, G1NS }
enum IntTriggerType { INT_LEVEL_SENSITIVE, INT_EDGE_TRIGGERED }
Public Types inherited from BaseGic
enum GicVersion { GicVersion::GIC_V2, GicVersion::GIC_V3, GicVersion::GIC_V4 }
typedef BaseGicParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Gicv3 (const Params *p)
void deassertInt (uint32_t cpu, ArmISA::InterruptTypes int_type)
Gicv3CPUInterface * getCPUInterface (int cpu_id) const
Gicv3Distributor * getDistributor () const
Gicv3Redistributor * getRedistributor (ContextID context_id) const
Gicv3Redistributor * getRedistributorByAffinity (uint32_t affinity) const
Gicv3Redistributor * getRedistributorByAddr (Addr address) const
void postInt (uint32_t cpu, ArmISA::InterruptTypes int_type)
Public Member Functions inherited from BaseGic
BaseGic (const Params *p)
virtual ~BaseGic ()
const Params * params () const
ArmSystem * getSystem () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Static Public Attributes
static const int INTID_SECURE = 1020
static const int INTID_NONSECURE = 1021
static const int INTID_SPURIOUS = 1023
static const int SGI_MAX = 16
static const int PPI_MAX = 16
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
typedef Gicv3Params Params
Protected Member Functions
void clearInt (uint32_t int_id) override
Clear an interrupt from a device that is connected to the GIC.
void clearPPInt (uint32_t int_id, uint32_t cpu) override
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
const Params * params () const
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
void reset ()
void sendInt (uint32_t int_id) override
Post an interrupt from a device that is connected to the GIC.
void sendPPInt (uint32_t int_id, uint32_t cpu) override
Interface call for private peripheral interrupts.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
bool supportsVersion (GicVersion version) override
Check if version supported.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
Gicv3Distributor * distributor
std::vector< Gicv3Redistributor * > redistributors
std::vector< Gicv3CPUInterface * > cpuInterfaces
Gicv3Its * its
AddrRange distRange
AddrRange redistRange
AddrRangeList addrRanges
uint64_t redistSize
Protected Attributes inherited from BaseGic
Platform * platform
Platform this GIC belongs to.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class Gicv3CPUInterface
class Gicv3Redistributor
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Definition at line 54 of file gic_v3.hh.
Member Typedef Documentation
Params
typedef Gicv3Params Gicv3::Params protected
Definition at line 60 of file gic_v3.hh.
Member Enumeration Documentation
GroupId
enum Gicv3::GroupId
Enumerator
G0S
G1S
G1NS
Definition at line 91 of file gic_v3.hh.
IntStatus
enum Gicv3::IntStatus
Enumerator
INT_INACTIVE
INT_PENDING
INT_ACTIVE
INT_ACTIVE_PENDING
Definition at line 83 of file gic_v3.hh.
IntTriggerType
enum Gicv3::IntTriggerType
Enumerator
INT_LEVEL_SENSITIVE
INT_EDGE_TRIGGERED
Definition at line 97 of file gic_v3.hh.
Constructor & Destructor Documentation
Gicv3()
Gicv3::Gicv3 (const Params * p)
Definition at line 56 of file gic_v3.cc.
Referenced by params(), and unserialize().
Member Function Documentation
clearInt()
void Gicv3::clearInt (uint32_t num) override protected virtual
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 185 of file gic_v3.cc.
References Gicv3Distributor::deassertSPI(), and distributor.
clearPPInt()
void Gicv3::clearPPInt (uint32_t int_id, uint32_t cpu) override protected virtual
Implements BaseGic.
Definition at line 202 of file gic_v3.cc.
deassertInt()
void Gicv3::deassertInt (uint32_t cpu, ArmISA::InterruptTypes int_type)
Definition at line 220 of file gic_v3.cc.
References IntrControl::clear(), Platform::intrctrl, and BaseGic::platform.
Referenced by params(), Gicv3CPUInterface::update(), and Gicv3CPUInterface::virtualUpdate().
getAddrRanges()
AddrRangeList Gicv3::getAddrRanges () const inline override protected virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 108 of file gic_v3.hh.
References addrRanges, and init().
getCPUInterface()
Gicv3CPUInterface* Gicv3::getCPUInterface (int cpu_id) const inline
Definition at line 136 of file gic_v3.hh.
Referenced by Gicv3Redistributor::init(), and ArmISA::ISA::startup().
getDistributor()
Gicv3Distributor* Gicv3::getDistributor () const inline
Definition at line 143 of file gic_v3.hh.
References distributor.
Referenced by Gicv3Redistributor::init(), Gicv3CPUInterface::init(), and Gicv3Its::read().
getRedistributor()
Gicv3Redistributor* Gicv3::getRedistributor (ContextID context_id) const inline
Definition at line 149 of file gic_v3.hh.
References getRedistributorByAddr(), getRedistributorByAffinity(), and postInt().
Referenced by Gicv3CPUInterface::generateSGI(), Gicv3Its::getRedistributor(), Gicv3CPUInterface::init(), Gicv3Distributor::route(), and Gicv3Distributor::update().
getRedistributorByAddr()
Gicv3Redistributor * Gicv3::getRedistributorByAddr (Addr address) const
Definition at line 238 of file gic_v3.cc.
References AddrRange::contains(), panic_if, redistRange, redistributors, redistSize, and AddrRange::start().
Referenced by getRedistributor(), Gicv3Its::getRedistributor(), read(), and write().
getRedistributorByAffinity()
Gicv3Redistributor * Gicv3::getRedistributorByAffinity (uint32_t affinity) const
Definition at line 226 of file gic_v3.cc.
References redistributors.
Referenced by getRedistributor(), and Gicv3Distributor::route().
init()
void Gicv3::init () override protected virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseGic.
Definition at line 62 of file gic_v3.cc.
References Gicv3Distributor::ADDR_RANGE_SIZE, addrRanges, cpuInterfaces, distRange, distributor, Gicv3CPUInterface, Gicv3Redistributor, ArmISA::i, BaseGic::init(), Gicv3Distributor::init(), its, System::numContexts(), panic_if, params(), RangeSize(), redistRange, redistributors, redistSize, Gicv3Its::setGIC(), and PioDevice::sys.
Referenced by getAddrRanges().
params()
const Params* Gicv3::params () const inline protected
Definition at line 116 of file gic_v3.hh.
References SimObject::_params, deassertInt(), Gicv3(), MipsISA::p, read(), reset(), sendInt(), sendPPInt(), serialize(), supportsVersion(), unserialize(), and write().
Referenced by init(), read(), Gicv3CPUInterface::setThreadContext(), supportsVersion(), and write().
postInt()
void Gicv3::postInt (uint32_t cpu, ArmISA::InterruptTypes int_type)
Definition at line 207 of file gic_v3.cc.
References Platform::intrctrl, BaseGic::platform, and IntrControl::post().
Referenced by getRedistributor(), Gicv3CPUInterface::update(), and Gicv3CPUInterface::virtualUpdate().
read()
Tick Gicv3::read (PacketPtr pkt) override protected virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 102 of file gic_v3.cc.
References addr, AddrRange::contains(), distRange, distributor, DPRINTF, Packet::getAddr(), getRedistributorByAddr(), Packet::getSize(), Packet::isSecure(), LittleEndianByteOrder, Packet::makeAtomicResponse(), panic, panic_if, params(), Gicv3Redistributor::processorNumber(), Gicv3Redistributor::read(), Gicv3Distributor::read(), redistRange, redistSize, Packet::req, Packet::setUintX(), and AddrRange::start().
Referenced by params().
reset()
void Gicv3::reset () protected
Referenced by params().
sendInt()
void Gicv3::sendInt (uint32_t num) override protected virtual
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 176 of file gic_v3.cc.
References distributor, DPRINTF, INTID_SECURE, panic_if, PPI_MAX, Gicv3Distributor::sendInt(), and SGI_MAX.
Referenced by params().
sendPPInt()
void Gicv3::sendPPInt (uint32_t num, uint32_t cpu) override protected virtual
Interface call for private peripheral interrupts.
Parameters
num number of interrupt to send
cpu CPU to forward interrupt to
Implements BaseGic.
Definition at line 191 of file gic_v3.cc.
References DPRINTF, panic_if, PPI_MAX, redistributors, and SGI_MAX.
Referenced by params().
serialize()
void Gicv3::serialize (CheckpointOut & cp) const override protected virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 254 of file gic_v3.cc.
References cpuInterfaces, csprintf(), distributor, redistributors, and Serializable::serializeSection().
Referenced by params().
supportsVersion()
bool Gicv3::supportsVersion (GicVersion version) override protected virtual
Check if version supported.
Implements BaseGic.
Definition at line 213 of file gic_v3.cc.
References BaseGic::GIC_V3, BaseGic::GIC_V4, and params().
Referenced by params().
unserialize()
void Gicv3::unserialize (CheckpointIn & cp) override protected virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 270 of file gic_v3.cc.
References cpuInterfaces, csprintf(), distributor, BaseGic::getSystem(), Gicv3(), redistributors, ArmSystem::setGIC(), and Serializable::unserializeSection().
Referenced by params().
write()
Tick Gicv3::write (PacketPtr pkt) override protected virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 139 of file gic_v3.cc.
References addr, AddrRange::contains(), data, distRange, distributor, DPRINTF, Packet::getAddr(), getRedistributorByAddr(), Packet::getSize(), Packet::getUintX(), Packet::isSecure(), LittleEndianByteOrder, Packet::makeAtomicResponse(), panic, panic_if, params(), Gicv3Redistributor::processorNumber(), redistRange, redistSize, Packet::req, AddrRange::start(), Gicv3Redistributor::write(), and Gicv3Distributor::write().
Referenced by params().
Friends And Related Function Documentation
Gicv3CPUInterface
friend class Gicv3CPUInterface friend
Definition at line 57 of file gic_v3.hh.
Referenced by init().
Gicv3Redistributor
friend class Gicv3Redistributor friend
Definition at line 58 of file gic_v3.hh.
Referenced by init().
Member Data Documentation
addrRanges
AddrRangeList Gicv3::addrRanges protected
Definition at line 67 of file gic_v3.hh.
Referenced by getAddrRanges(), and init().
cpuInterfaces
std::vector<Gicv3CPUInterface *> Gicv3::cpuInterfaces protected
Definition at line 63 of file gic_v3.hh.
Referenced by init(), serialize(), and unserialize().
distRange
AddrRange Gicv3::distRange protected
Definition at line 65 of file gic_v3.hh.
Referenced by init(), read(), and write().
distributor
Gicv3Distributor* Gicv3::distributor protected
Definition at line 61 of file gic_v3.hh.
Referenced by clearInt(), getDistributor(), init(), read(), sendInt(), serialize(), unserialize(), and write().
INTID_NONSECURE
const int Gicv3::INTID_NONSECURE = 1021 static
Definition at line 74 of file gic_v3.hh.
Referenced by Gicv3CPUInterface::getHPPIR0(), and Gicv3CPUInterface::getHPPIR1().
INTID_SECURE
const int Gicv3::INTID_SECURE = 1020 static
Definition at line 73 of file gic_v3.hh.
Referenced by Gicv3CPUInterface::deactivateIRQ(), Gicv3CPUInterface::generateSGI(), Gicv3CPUInterface::getHPPIR0(), Gicv3CPUInterface::getHPPIR1(), Gicv3Distributor::Gicv3Distributor(), Gicv3CPUInterface::readMiscReg(), sendInt(), Gicv3CPUInterface::setMiscReg(), and Gicv3CPUInterface::virtualDeactivateIRQ().
INTID_SPURIOUS
const int Gicv3::INTID_SPURIOUS = 1023 static
Definition at line 75 of file gic_v3.hh.
Referenced by Gicv3CPUInterface::getHPPIR0(), Gicv3CPUInterface::getHPPIR1(), Gicv3CPUInterface::Gicv3CPUInterface(), Gicv3Its::lpiOutOfRange(), Gicv3CPUInterface::readMiscReg(), and Gicv3CPUInterface::setMiscReg().
its
Gicv3Its* Gicv3::its protected
Definition at line 64 of file gic_v3.hh.
Referenced by init().
PPI_MAX
const int Gicv3::PPI_MAX = 16 static
Definition at line 80 of file gic_v3.hh.
Referenced by Gicv3CPUInterface::deactivateIRQ(), Gicv3Distributor::deassertSPI(), Gicv3CPUInterface::generateSGI(), Gicv3Distributor::getIntGroup(), Gicv3Redistributor::getIntGroup(), Gicv3Redistributor::intStatus(), Gicv3Distributor::intStatus(), Gicv3Distributor::isNotSPI(), sendInt(), Gicv3Distributor::sendInt(), sendPPInt(), Gicv3Redistributor::sendPPInt(), Gicv3Redistributor::update(), and Gicv3Distributor::update().
redistRange
AddrRange Gicv3::redistRange protected
Definition at line 66 of file gic_v3.hh.
Referenced by getRedistributorByAddr(), init(), read(), and write().
redistributors
std::vector<Gicv3Redistributor *> Gicv3::redistributors protected
Definition at line 62 of file gic_v3.hh.
Referenced by getRedistributorByAddr(), getRedistributorByAffinity(), init(), sendPPInt(), serialize(), and unserialize().
redistSize
uint64_t Gicv3::redistSize protected
Definition at line 68 of file gic_v3.hh.
Referenced by getRedistributorByAddr(), init(), read(), and write().
SGI_MAX
const int Gicv3::SGI_MAX = 16 static
Definition at line 78 of file gic_v3.hh.
Referenced by Gicv3CPUInterface::deactivateIRQ(), Gicv3Distributor::deassertSPI(), Gicv3CPUInterface::generateSGI(), Gicv3Distributor::getIntGroup(), Gicv3Redistributor::getIntGroup(), Gicv3Redistributor::intStatus(), Gicv3Distributor::intStatus(), Gicv3Distributor::isNotSPI(), Gicv3Redistributor::read(), sendInt(), Gicv3Distributor::sendInt(), sendPPInt(), Gicv3Redistributor::sendPPInt(), Gicv3Redistributor::sendSGI(), Gicv3Redistributor::update(), Gicv3Distributor::update(), and Gicv3Redistributor::write().
The documentation for this class was generated from the following files:
dev/arm/gic_v3.hh
dev/arm/gic_v3.cc