gem5: DmaDevice Class Reference
DmaDevice Class Reference
#include <dma_device.hh>
Public Types
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from PioDevice
virtual AddrRangeList getAddrRanges () const =0
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
virtual Tick read (PacketPtr pkt)=0
Pure virtual function that the device must implement.
virtual Tick write (PacketPtr pkt)=0
Pure virtual function that the device must implement.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 169 of file dma_device.hh.
Member Typedef Documentation
Params
typedef DmaDeviceParams DmaDevice::Params
Definition at line 175 of file dma_device.hh.
Constructor & Destructor Documentation
DmaDevice()
DmaDevice::DmaDevice (const Params * p)
Definition at line 122 of file dma_device.cc.
~DmaDevice()
virtual DmaDevice::~DmaDevice () inline virtual
Definition at line 177 of file dma_device.hh.
Member Function Documentation
cacheBlockSize()
unsigned int DmaDevice::cacheBlockSize () const inline
Definition at line 209 of file dma_device.hh.
References System::cacheLineSize(), InvalidPortID, and DmaPort::sys.
Referenced by IGbE::TxDescCache::descInBlock(), IGbE::TxDescCache::pktComplete(), IGbE::rxStateMachine(), and IGbE::txStateMachine().
dmaPending()
bool DmaDevice::dmaPending () const inline
Definition at line 205 of file dma_device.hh.
References DmaPort::dmaPending(), and Stats::init.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), IdeDisk::doDmaWrite(), NSGigE::doRxDmaRead(), NSGigE::doRxDmaWrite(), NSGigE::doTxDmaRead(), NSGigE::doTxDmaWrite(), Sinic::Device::rxKick(), and Sinic::Device::txKick().
dmaRead() [1/2]
void DmaDevice::dmaRead (Addr addr, int size, Event * event, uint8_t * data, uint32_t sid, uint32_t ssid, Tick delay = 0) inline
Definition at line 192 of file dma_device.hh.
References DmaPort::DmaReqState::delay, DmaPort::dmaAction(), and MemCmd::ReadReq.
Referenced by IdeDisk::doDmaRead(), IdeDisk::doDmaTransfer(), NSGigE::doRxDmaRead(), NSGigE::doTxDmaRead(), IGbE::TxDescCache::getPacketData(), IGbE::TxDescCache::processContextDesc(), and Sinic::Device::txKick().
dmaRead() [2/2]
void DmaDevice::dmaRead (Addr addr, int size, Event * event, uint8_t * data, Tick delay = 0) inline
Definition at line 199 of file dma_device.hh.
References DmaPort::DmaReqState::delay, DmaPort::dmaAction(), and MemCmd::ReadReq.
dmaWrite() [1/2]
void DmaDevice::dmaWrite (Addr addr, int size, Event * event, uint8_t * data, uint32_t sid, uint32_t ssid, Tick delay = 0) inline
Definition at line 179 of file dma_device.hh.
References DmaPort::DmaReqState::delay, DmaPort::dmaAction(), and MemCmd::WriteReq.
Referenced by IGbE::TxDescCache::actionAfterWb(), IdeDisk::doDmaWrite(), NSGigE::doRxDmaWrite(), NSGigE::doTxDmaWrite(), Sinic::Device::rxKick(), and IGbE::RxDescCache::writePacket().
dmaWrite() [2/2]
void DmaDevice::dmaWrite (Addr addr, int size, Event * event, uint8_t * data, Tick delay = 0) inline
Definition at line 186 of file dma_device.hh.
References DmaPort::DmaReqState::delay, DmaPort::dmaAction(), and MemCmd::WriteReq.
getPort()
Port & DmaDevice::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Reimplemented in IGbE, NSGigE, Sinic::Device, CopyEngine, and GpuDispatcher.
Definition at line 282 of file dma_device.cc.
References dmaPort, and PioDevice::getPort().
Referenced by GpuDispatcher::getPort(), CopyEngine::getPort(), Sinic::Device::getPort(), NSGigE::getPort(), and IGbE::getPort().
init()
void DmaDevice::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in IGbE.
Definition at line 127 of file dma_device.cc.
References dmaPort, PioDevice::init(), Port::isConnected(), SimObject::name(), and panic.
Referenced by IGbE::init().
Member Data Documentation
dmaPort
DmaPort DmaDevice::dmaPort protected
Definition at line 172 of file dma_device.hh.
Referenced by Pl111::fillFifo(), getPort(), init(), UFSHostDevice::readDevice(), and UFSHostDevice::writeDevice().
The documentation for this class was generated from the following files:
dev/dma_device.hh
dev/dma_device.cc