gem5: PrdTableEntry Class Reference
PrdTableEntry Class Reference
#include <ide_disk.hh>
Public Member Functions
uint32_t getBaseAddr ()
uint32_t getByteCount ()
uint16_t getEOT ()
Public Attributes
PrdEntry_t entry
Detailed Description
Definition at line 77 of file ide_disk.hh.
Member Function Documentation
getBaseAddr()
uint32_t PrdTableEntry::getBaseAddr () inline
Definition at line 81 of file ide_disk.hh.
References PrdEntry::baseAddr, and PRD_BASE_MASK.
Referenced by IdeDisk::dmaPrdReadDone(), IdeDisk::doDmaRead(), and IdeDisk::doDmaWrite().
getByteCount()
uint32_t PrdTableEntry::getByteCount () inline
Definition at line 86 of file ide_disk.hh.
References PrdEntry::byteCount, MAX_SINGLE_DMA_SIZE, and PRD_COUNT_MASK.
Referenced by IdeDisk::dmaPrdReadDone(), IdeDisk::dmaReadDone(), IdeDisk::dmaWriteDone(), IdeDisk::doDmaDataRead(), IdeDisk::doDmaDataWrite(), IdeDisk::doDmaRead(), and IdeDisk::doDmaWrite().
getEOT()
uint16_t PrdTableEntry::getEOT () inline
Definition at line 92 of file ide_disk.hh.
References PrdEntry::endOfTable, and PRD_EOT_MASK.
Referenced by IdeDisk::dmaPrdReadDone(), IdeDisk::dmaReadDone(), IdeDisk::dmaWriteDone(), and IdeDisk::doDmaWrite().
Member Data Documentation
entry
PrdEntry_t PrdTableEntry::entry
Definition at line 79 of file ide_disk.hh.
Referenced by IdeDisk::doDmaTransfer(), IdeDisk::reset(), IdeDisk::serialize(), and IdeDisk::unserialize().
The documentation for this class was generated from the following file:
dev/storage/ide_disk.hh