gem5: ArmSemihosting::FileBase Class Reference
ArmSemihosting::FileBase Class Reference
Internal state for open files.
#include <semihosting.hh>
Public Member Functions
FileBase (ArmSemihosting &_parent, const char *name, const char *_mode)
virtual ~FileBase ()
FileBase ()=delete
FileBase (FileBase &)=delete
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
const std::string & fileName ()
virtual int64_t open ()
Open the the file.
virtual int64_t close ()
Close the file.
virtual bool isTTY () const
Check if a file corresponds to a TTY device.
virtual int64_t read (uint8_t *buffer, uint64_t size)
Read data from file.
virtual int64_t write (const uint8_t *buffer, uint64_t size)
Write data to file.
virtual int64_t seek (uint64_t pos)
Seek to an absolute position in the file.
virtual int64_t flen ()
Get the length of a file in bytes.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Static Public Member Functions
static std::unique_ptr< FileBase > create (ArmSemihosting &parent, const std::string &fname, const char *mode)
static std::unique_ptr< FileBase > create (ArmSemihosting &parent, CheckpointIn &cp, const std::string &sec)
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Attributes
ArmSemihosting & parent
std::string _name
std::string mode
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Internal state for open files.
This class describes the internal state of a file opened through the semihosting interface.
A file instance is normally created using one of the ArmSemihosting::FileBase::create() factory methods. These methods handle some the magic file names in the Arm Semihosting specification and instantiate the right implementation. For the same, when unserializing a checkpoint, the create method must be used to unserialize a new instance of a file descriptor.
Definition at line 115 of file semihosting.hh.
Constructor & Destructor Documentation
FileBase() [1/3]
ArmSemihosting::FileBase::FileBase (ArmSemihosting & _parent, const char * name, const char * _mode) inline
Definition at line 118 of file semihosting.hh.
~FileBase()
virtual ArmSemihosting::FileBase::~FileBase () inline virtual
Definition at line 120 of file semihosting.hh.
References create(), FileBase(), mode, parent, serialize(), and unserialize().
FileBase() [2/3]
ArmSemihosting::FileBase::FileBase () delete
Referenced by ~FileBase().
FileBase() [3/3]
ArmSemihosting::FileBase::FileBase (FileBase &) delete
Member Function Documentation
close()
virtual int64_t ArmSemihosting::FileBase::close () inline virtual
Close the file.
Returns
<0 on error (-errno), 0 on success.
Reimplemented in ArmSemihosting::File.
Definition at line 159 of file semihosting.hh.
Referenced by ArmSemihosting::File::open().
create() [1/2]
std::unique_ptr< ArmSemihosting::FileBase > ArmSemihosting::FileBase::create (ArmSemihosting & parent, const std::string & fname, const char * mode) static
Definition at line 712 of file semihosting.cc.
References ArmISA::mode.
Referenced by ArmSemihosting::readString(), ArmSemihosting::unserialize(), and ~FileBase().
create() [2/2]
std::unique_ptr< ArmSemihosting::FileBase > ArmSemihosting::FileBase::create (ArmSemihosting & parent, CheckpointIn & cp, const std::string & sec) static
Definition at line 726 of file semihosting.cc.
References Serializable::currentSection(), ArmISA::mode, paramIn(), and CheckpointIn::sectionExists().
fileName()
const std::string& ArmSemihosting::FileBase::fileName () inline
Definition at line 134 of file semihosting.hh.
References _name.
flen()
int64_t ArmSemihosting::FileBase::flen () virtual
Get the length of a file in bytes.
Returns
<0 on error (-errno), length on success
Reimplemented in ArmSemihosting::File.
Definition at line 779 of file semihosting.cc.
Referenced by isTTY(), and ArmSemihosting::File::open().
isTTY()
virtual bool ArmSemihosting::FileBase::isTTY () const inline virtual
Check if a file corresponds to a TTY device.
Returns
True if the file is a TTY, false otherwise.
Reimplemented in ArmSemihosting::File.
Definition at line 166 of file semihosting.hh.
References flen(), read(), seek(), and write().
Referenced by ArmSemihosting::File::needClose(), and ArmSemihosting::File::open().
open()
virtual int64_t ArmSemihosting::FileBase::open () inline virtual
Open the the file.
Semihosting file IO interfaces
These interfaces implement common IO functionality in the Semihosting interface.
All functions return a negative value that corresponds to a UNIX errno value when they fail and >=0 on success.
Returns
<0 on error (-errno), 0 on success.
Reimplemented in ArmSemihosting::File.
Definition at line 152 of file semihosting.hh.
read()
int64_t ArmSemihosting::FileBase::read (uint8_t * buffer, uint64_t size) virtual
Read data from file.
Returns
<0 on error (-errno), bytes read on success (0 for EOF).
Reimplemented in ArmSemihosting::File, and ArmSemihosting::FileFeatures.
Definition at line 761 of file semihosting.cc.
Referenced by isTTY(), and ArmSemihosting::File::open().
seek()
int64_t ArmSemihosting::FileBase::seek (uint64_t pos) virtual
Seek to an absolute position in the file.
Parameters
pos Byte offset from start of file.
Returns
<0 on error (-errno), 0 on success.
Reimplemented in ArmSemihosting::File, and ArmSemihosting::FileFeatures.
Definition at line 773 of file semihosting.cc.
Referenced by isTTY(), and ArmSemihosting::File::open().
serialize()
void ArmSemihosting::FileBase::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in ArmSemihosting::File, and ArmSemihosting::FileFeatures.
Definition at line 747 of file semihosting.cc.
References ArmISA::mode, paramOut(), and SERIALIZE_SCALAR.
Referenced by ArmSemihosting::FileFeatures::serialize(), ArmSemihosting::File::serialize(), and ~FileBase().
unserialize()
void ArmSemihosting::FileBase::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in ArmSemihosting::File, and ArmSemihosting::FileFeatures.
Definition at line 754 of file semihosting.cc.
Referenced by ArmSemihosting::FileFeatures::unserialize(), ArmSemihosting::File::unserialize(), and ~FileBase().
write()
int64_t ArmSemihosting::FileBase::write (const uint8_t * buffer, uint64_t size) virtual
Write data to file.
Returns
<0 on error (-errno), bytes written on success.
Reimplemented in ArmSemihosting::File.
Definition at line 767 of file semihosting.cc.
Referenced by isTTY(), and ArmSemihosting::File::open().
Member Data Documentation
_name
std::string ArmSemihosting::FileBase::_name protected
Definition at line 201 of file semihosting.hh.
Referenced by fileName(), ArmSemihosting::File::openImpl(), and ArmSemihosting::File::unserialize().
mode
std::string ArmSemihosting::FileBase::mode protected
Definition at line 202 of file semihosting.hh.
Referenced by ArmSemihosting::File::openImpl(), and ~FileBase().
parent
ArmSemihosting& ArmSemihosting::FileBase::parent protected
Definition at line 200 of file semihosting.hh.
Referenced by ArmSemihosting::File::isTTY(), ArmSemihosting::File::openImpl(), and ~FileBase().
The documentation for this class was generated from the following files:
arch/arm/semihosting.hh
arch/arm/semihosting.cc