gem5: SimpleRenameMap Class Reference
SimpleRenameMap Class Reference
Register rename map for a single class of registers (e.g., integer or floating point).
#include <rename_map.hh>
Public Types
using iterator = Arch2PhysMap::iterator
using const_iterator = Arch2PhysMap::const_iterator
typedef std::pair< PhysRegIdPtr, PhysRegIdPtr > RenameInfo
Pair of a physical register and a physical register.
Public Member Functions
SimpleRenameMap ()
~SimpleRenameMap ()
void init (unsigned size, SimpleFreeList *_freeList, RegIndex _zeroReg)
Because we have an array of rename maps (one per thread) in the CPU, it's awkward to initialize this object via the constructor.
RenameInfo rename (const RegId &arch_reg)
Tell rename map to get a new free physical register to remap the specified architectural register.
PhysRegIdPtr lookup (const RegId &arch_reg) const
Look up the physical register mapped to an architectural register.
void setEntry (const RegId &arch_reg, PhysRegIdPtr phys_reg)
Update rename map with a specific mapping.
unsigned numFreeEntries () const
Return the number of free entries on the associated free list.
iterator begin ()
Forward begin/cbegin to the map.
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
Forward end/cend to the map.
const_iterator end () const
const_iterator cend () const
Private Types
using Arch2PhysMap = std::vector< PhysRegIdPtr >
Private Attributes
Arch2PhysMap map
The acutal arch-to-phys register map.
SimpleFreeList * freeList
Pointer to the free list from which new physical registers should be allocated in rename()
RegId zeroReg
The architectural index of the zero register.
Detailed Description
Register rename map for a single class of registers (e.g., integer or floating point).
Because the register class is implicitly determined by the rename map instance being accessed, all architectural register index parameters and values in this class are relative (e.g., fp2 is just index 2).
Definition at line 66 of file rename_map.hh.
Member Typedef Documentation
Arch2PhysMap
using SimpleRenameMap::Arch2PhysMap = std::vector<PhysRegIdPtr> private
Definition at line 69 of file rename_map.hh.
const_iterator
using SimpleRenameMap::const_iterator = Arch2PhysMap::const_iterator
Definition at line 74 of file rename_map.hh.
iterator
using SimpleRenameMap::iterator = Arch2PhysMap::iterator
Definition at line 73 of file rename_map.hh.
RenameInfo
typedef std::pair<PhysRegIdPtr, PhysRegIdPtr> SimpleRenameMap::RenameInfo
Pair of a physical register and a physical register.
Used to return the physical register that a logical register has been renamed to, and the previous physical register that the same logical register was previously mapped to.
Definition at line 111 of file rename_map.hh.
Constructor & Destructor Documentation
SimpleRenameMap()
SimpleRenameMap::SimpleRenameMap ()
Definition at line 55 of file rename_map.cc.
~SimpleRenameMap()
SimpleRenameMap::~SimpleRenameMap () inline
Definition at line 96 of file rename_map.hh.
References init().
Member Function Documentation
begin() [1/2]
iterator SimpleRenameMap::begin () inline
Forward begin/cbegin to the map.
Definition at line 150 of file rename_map.hh.
begin() [2/2]
const_iterator SimpleRenameMap::begin () const inline
Definition at line 151 of file rename_map.hh.
cbegin()
const_iterator SimpleRenameMap::cbegin () const inline
Definition at line 152 of file rename_map.hh.
cend()
const_iterator SimpleRenameMap::cend () const inline
Definition at line 159 of file rename_map.hh.
end() [1/2]
iterator SimpleRenameMap::end () inline
Forward end/cend to the map.
Definition at line 157 of file rename_map.hh.
end() [2/2]
const_iterator SimpleRenameMap::end () const inline
Definition at line 158 of file rename_map.hh.
init()
void SimpleRenameMap::init (unsigned size, SimpleFreeList * _freeList, RegIndex _zeroReg)
Because we have an array of rename maps (one per thread) in the CPU, it's awkward to initialize this object via the constructor.
Instead, this method is used for initialization.
Definition at line 62 of file rename_map.cc.
References freeList, IntRegClass, map, and zeroReg.
Referenced by ~SimpleRenameMap(), and UnifiedRenameMap::~UnifiedRenameMap().
lookup()
PhysRegIdPtr SimpleRenameMap::lookup (const RegId & arch_reg) const inline
Look up the physical register mapped to an architectural register.
Parameters
arch_reg The architectural register to look up.
Returns
The physical register it is currently mapped to.
Definition at line 127 of file rename_map.hh.
References RegId::flatIndex().
Referenced by UnifiedRenameMap::lookup(), UnifiedRenameMap::rename(), and UnifiedRenameMap::setEntry().
numFreeEntries()
unsigned SimpleRenameMap::numFreeEntries () const inline
Return the number of free entries on the associated free list.
Definition at line 146 of file rename_map.hh.
References SimpleFreeList::numFreeRegs().
Referenced by UnifiedRenameMap::canRename(), UnifiedRenameMap::numFreeCCEntries(), UnifiedRenameMap::numFreeEntries(), UnifiedRenameMap::numFreeFloatEntries(), UnifiedRenameMap::numFreeIntEntries(), UnifiedRenameMap::numFreePredEntries(), and UnifiedRenameMap::numFreeVecEntries().
rename()
SimpleRenameMap::RenameInfo SimpleRenameMap::rename (const RegId & arch_reg)
Tell rename map to get a new free physical register to remap the specified architectural register.
Parameters
arch_reg The architectural register to remap.
Returns
A RenameInfo pair indicating both the new and previous physical registers.
Definition at line 74 of file rename_map.cc.
References PhysRegId::decrNumPinnedWrites(), DPRINTF, RegId::flatIndex(), PhysRegId::flatIndex(), freeList, RegId::getNumPinnedWrites(), PhysRegId::getNumPinnedWrites(), SimpleFreeList::getReg(), RegId::isZeroReg(), map, PhysRegId::setNumPinnedWrites(), PhysRegId::setNumPinnedWritesToComplete(), and zeroReg.
Referenced by UnifiedRenameMap::rename().
setEntry()
void SimpleRenameMap::setEntry (const RegId & arch_reg, PhysRegIdPtr phys_reg) inline
Update rename map with a specific mapping.
Generally used to roll back to old mappings on a squash.
Parameters
arch_reg The architectural register to remap.
phys_reg The physical register to remap it to.
Definition at line 139 of file rename_map.hh.
References RegId::flatIndex().
Referenced by UnifiedRenameMap::setEntry(), and UnifiedRenameMap::switchMode().
Member Data Documentation
freeList
SimpleFreeList* SimpleRenameMap::freeList private
Pointer to the free list from which new physical registers should be allocated in rename()
Definition at line 81 of file rename_map.hh.
Referenced by init(), rename(), and UnifiedRenameMap::~UnifiedRenameMap().
map
Arch2PhysMap SimpleRenameMap::map private
The acutal arch-to-phys register map.
Definition at line 71 of file rename_map.hh.
Referenced by init(), and rename().
zeroReg
RegId SimpleRenameMap::zeroReg private
The architectural index of the zero register.
This register is mapped but read-only, so we ignore attempts to rename it via the rename() method. If there is no such register for this map table, it should be set to an invalid index so that it never matches.
Definition at line 90 of file rename_map.hh.
Referenced by init(), and rename().
The documentation for this class was generated from the following files:
cpu/o3/rename_map.hh
cpu/o3/rename_map.cc