gem5: ScoreboardCheckStage Class Reference
ScoreboardCheckStage Class Reference
#include <scoreboard_check_stage.hh>
Public Member Functions
ScoreboardCheckStage (const ComputeUnitParams *params)
~ScoreboardCheckStage ()
void init (ComputeUnit *cu)
void exec ()
const std::string & name () const
void regStats ()
Private Member Functions
void collectStatistics (Wavefront *curWave, int unitId)
void initStatistics ()
Private Attributes
ComputeUnit * computeUnit
uint32_t numSIMDs
uint32_t numMemUnits
uint32_t numShrMemPipes
std::vector< bool > * vectorAluInstAvail
int lastGlbMemSimd
int lastShrMemSimd
int * glbMemInstAvail
int * shrMemInstAvail
std::vector< std::vector< Wavefront * > * > readyList
std::vector< std::vector< std::pair< Wavefront *, WAVE_STATUS > > * > waveStatusList
std::string _name
Detailed Description
Definition at line 64 of file scoreboard_check_stage.hh.
Constructor & Destructor Documentation
ScoreboardCheckStage()
ScoreboardCheckStage::ScoreboardCheckStage (const ComputeUnitParams * params)
Definition at line 46 of file scoreboard_check_stage.cc.
~ScoreboardCheckStage()
ScoreboardCheckStage::~ScoreboardCheckStage ()
Definition at line 57 of file scoreboard_check_stage.cc.
References glbMemInstAvail, readyList, shrMemInstAvail, and waveStatusList.
Member Function Documentation
collectStatistics()
void ScoreboardCheckStage::collectStatistics (Wavefront * curWave, int unitId) private
Definition at line 97 of file scoreboard_check_stage.cc.
References glbMemInstAvail, Wavefront::instructionBuffer, Wavefront::isOldestInstALU(), Wavefront::isOldestInstFlatMem(), Wavefront::isOldestInstGMem(), Wavefront::isOldestInstLMem(), Wavefront::isOldestInstPrivMem(), lastGlbMemSimd, lastShrMemSimd, numShrMemPipes, shrMemInstAvail, and vectorAluInstAvail.
Referenced by exec(), and name().
exec()
void ScoreboardCheckStage::exec ()
Definition at line 129 of file scoreboard_check_stage.cc.
References BLOCKED, ComputeUnit::cedeSIMD(), collectStatistics(), computeUnit, ComputeUnit::GlbMemUnitId(), Wavefront::I_ALU, Wavefront::I_FLAT, Wavefront::I_GLOBAL, Wavefront::I_PRIVATE, Wavefront::I_SHARED, initStatistics(), Shader::n_wf, numMemUnits, numSIMDs, READY, Wavefront::ready(), readyList, ComputeUnit::shader, ComputeUnit::ShrMemUnitId(), and waveStatusList.
Referenced by ComputeUnit::exec().
init()
void ScoreboardCheckStage::init (ComputeUnit * cu)
Definition at line 66 of file scoreboard_check_stage.cc.
References _name, computeUnit, glbMemInstAvail, ComputeUnit::glbMemInstAvail, SimObject::name(), numMemUnits, numSIMDs, readyList, ComputeUnit::readyList, shrMemInstAvail, ComputeUnit::shrMemInstAvail, vectorAluInstAvail, ComputeUnit::vectorAluInstAvail, waveStatusList, and ComputeUnit::waveStatusList.
Referenced by ComputeUnit::init().
initStatistics()
void ScoreboardCheckStage::initStatistics () private
Definition at line 85 of file scoreboard_check_stage.cc.
References glbMemInstAvail, lastGlbMemSimd, lastShrMemSimd, numSIMDs, shrMemInstAvail, and vectorAluInstAvail.
Referenced by exec(), and name().
name()
const std::string& ScoreboardCheckStage::name () const inline
Definition at line 73 of file scoreboard_check_stage.hh.
References _name, collectStatistics(), initStatistics(), and regStats().
regStats()
void ScoreboardCheckStage::regStats ()
Definition at line 172 of file scoreboard_check_stage.cc.
Referenced by name(), and ComputeUnit::regStats().
Member Data Documentation
_name
std::string ScoreboardCheckStage::_name private
Definition at line 103 of file scoreboard_check_stage.hh.
Referenced by init(), and name().
computeUnit
ComputeUnit* ScoreboardCheckStage::computeUnit private
Definition at line 79 of file scoreboard_check_stage.hh.
Referenced by exec(), and init().
glbMemInstAvail
int* ScoreboardCheckStage::glbMemInstAvail private
Definition at line 91 of file scoreboard_check_stage.hh.
Referenced by collectStatistics(), init(), initStatistics(), and ~ScoreboardCheckStage().
lastGlbMemSimd
int ScoreboardCheckStage::lastGlbMemSimd private
Definition at line 88 of file scoreboard_check_stage.hh.
Referenced by collectStatistics(), and initStatistics().
lastShrMemSimd
int ScoreboardCheckStage::lastShrMemSimd private
Definition at line 89 of file scoreboard_check_stage.hh.
Referenced by collectStatistics(), and initStatistics().
numMemUnits
uint32_t ScoreboardCheckStage::numMemUnits private
Definition at line 81 of file scoreboard_check_stage.hh.
Referenced by exec(), and init().
numShrMemPipes
uint32_t ScoreboardCheckStage::numShrMemPipes private
Definition at line 82 of file scoreboard_check_stage.hh.
Referenced by collectStatistics().
numSIMDs
uint32_t ScoreboardCheckStage::numSIMDs private
Definition at line 80 of file scoreboard_check_stage.hh.
Referenced by exec(), init(), and initStatistics().
readyList
std::vector<std::vector<Wavefront*>*> ScoreboardCheckStage::readyList private
Definition at line 95 of file scoreboard_check_stage.hh.
Referenced by exec(), init(), and ~ScoreboardCheckStage().
shrMemInstAvail
int* ScoreboardCheckStage::shrMemInstAvail private
Definition at line 92 of file scoreboard_check_stage.hh.
Referenced by collectStatistics(), init(), initStatistics(), and ~ScoreboardCheckStage().
vectorAluInstAvail
std::vector<bool>* ScoreboardCheckStage::vectorAluInstAvail private
Definition at line 87 of file scoreboard_check_stage.hh.
Referenced by collectStatistics(), init(), and initStatistics().
waveStatusList
std::vector<std::vector<std::pair<Wavefront*, WAVE_STATUS> >*> ScoreboardCheckStage::waveStatusList private
Definition at line 101 of file scoreboard_check_stage.hh.
Referenced by exec(), init(), and ~ScoreboardCheckStage().
The documentation for this class was generated from the following files:
gpu-compute/scoreboard_check_stage.hh
gpu-compute/scoreboard_check_stage.cc