gem5: BaseKvmCPU::KVMCpuPort Class Reference
BaseKvmCPU::KVMCpuPort Class Reference
KVM memory port.
#include <base.hh>
Public Member Functions
KVMCpuPort (const std::string &_name, BaseKvmCPU *_cpu)
Tick submitIO (PacketPtr pkt)
Interface to send Atomic or Timing IO request.
Status nextIOState () const
Returns next valid state after one or more IO accesses.
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
bool recvTimingResp (PacketPtr pkt) override
Receive a timing response from the peer.
void recvReqRetry () override
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from MasterPort
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
BaseKvmCPU * cpu
KVM cpu pointer for finishMMIOPending() callback.
std::queue< PacketPtr > pendingMMIOPkts
Pending MMIO packets.
unsigned int activeMMIOReqs
Number of MMIO requests in flight.
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
KVM memory port.
Uses default MasterPort behavior and provides an interface for KVM to transparently submit atomic or timing requests.
Definition at line 580 of file base.hh.
Constructor & Destructor Documentation
KVMCpuPort()
BaseKvmCPU::KVMCpuPort::KVMCpuPort (const std::string & _name, BaseKvmCPU * _cpu) inline
Definition at line 584 of file base.hh.
References nextIOState(), and submitIO().
Member Function Documentation
nextIOState()
BaseKvmCPU::Status BaseKvmCPU::KVMCpuPort::nextIOState () const
Returns next valid state after one or more IO accesses.
Definition at line 173 of file base.cc.
References BaseKvmCPU::RunningMMIOPending, and BaseKvmCPU::RunningServiceCompletion.
Referenced by BaseKvmCPU::handleKvmExit(), and KVMCpuPort().
recvReqRetry()
void BaseKvmCPU::KVMCpuPort::recvReqRetry () override protected virtual
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Implements TimingRequestProtocol.
Definition at line 215 of file base.cc.
References DPRINTF.
recvTimingResp()
bool BaseKvmCPU::KVMCpuPort::recvTimingResp (PacketPtr pkt) override protected virtual
Receive a timing response from the peer.
Implements TimingRequestProtocol.
Definition at line 198 of file base.cc.
References DPRINTF.
submitIO()
Tick BaseKvmCPU::KVMCpuPort::submitIO (PacketPtr pkt)
Interface to send Atomic or Timing IO request.
Assumes that the pkt and corresponding req have been dynamically allocated and deletes them both if the system is in atomic mode.
Definition at line 180 of file base.cc.
Referenced by BaseKvmCPU::doMMIOAccess(), X86KvmCPU::handleKvmExitIO(), and KVMCpuPort().
Member Data Documentation
activeMMIOReqs
unsigned int BaseKvmCPU::KVMCpuPort::activeMMIOReqs protected
Number of MMIO requests in flight.
Definition at line 605 of file base.hh.
cpu
BaseKvmCPU* BaseKvmCPU::KVMCpuPort::cpu protected
KVM cpu pointer for finishMMIOPending() callback.
Definition at line 599 of file base.hh.
pendingMMIOPkts
std::queue<PacketPtr> BaseKvmCPU::KVMCpuPort::pendingMMIOPkts protected
Pending MMIO packets.
Definition at line 602 of file base.hh.
The documentation for this class was generated from the following files:
cpu/kvm/base.hh
cpu/kvm/base.cc