gem5: Terminal Class Reference
Terminal Class Reference
#include <terminal.hh>
Classes
class DataEvent
class ListenEvent
Public Types
typedef TerminalParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Terminal (const Params *p)
~Terminal ()
OutputStream * terminalDump (const TerminalParams *p)
void data ()
void read (uint8_t &c)
size_t read (uint8_t *buf, size_t len)
void write (uint8_t c)
size_t write (const uint8_t *buf, size_t len)
void detach ()
uint8_t readData () override
Read a character from the device.
void writeData (uint8_t c) override
Transmit a character from the host interface to the device.
bool dataAvailable () const override
Check if there is pending data from the serial device.
uint64_t console_in ()
Public Member Functions inherited from SerialDevice
SerialDevice (const SerialDeviceParams *p)
~SerialDevice ()
void regInterfaceCallback (Callback *c)
Register a data available callback into the host interface layer.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void listen (int port)
void accept ()
Protected Member Functions inherited from SerialDevice
void notifyInterface ()
Notify the host interface of pending data.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
ListenEvent * listenEvent
DataEvent * dataEvent
int number
int data_fd
ListenSocket listener
CircleBuf< char > txbuf
CircleBuf< char > rxbuf
OutputStream * outfile
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class ListenEvent
class DataEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 64 of file terminal.hh.
Member Typedef Documentation
Params
typedef TerminalParams Terminal::Params
Definition at line 98 of file terminal.hh.
Constructor & Destructor Documentation
Terminal()
Terminal::Terminal (const Params * p)
Definition at line 121 of file terminal.cc.
References listen(), outfile, and OutputStream::stream().
Referenced by writeData().
~Terminal()
Terminal::~Terminal ()
Definition at line 136 of file terminal.cc.
References data_fd, dataEvent, and listenEvent.
Member Function Documentation
accept()
void Terminal::accept () protected
Definition at line 192 of file terminal.cc.
References ListenSocket::accept(), atomic_write(), ccprintf(), data_fd, DataEvent, dataEvent, DPRINTFN, ArmISA::fd, ArmISA::i, ListenSocket::islistening(), listener, SimObject::name(), number, panic, CircleBuf< T >::peek(), pollQueue, PollQueue::schedule(), CircularQueue< T >::size(), txbuf, and write().
Referenced by Terminal::ListenEvent::process().
console_in()
uint64_t Terminal::console_in ()
Definition at line 312 of file terminal.cc.
References dataAvailable(), DPRINTF, CircularQueue< T >::empty(), MORE_PENDING, readData(), RECEIVE_NONE, RECEIVE_SUCCESS, and rxbuf.
Referenced by dataAvailable(), and AlphaBackdoor::read().
data()
void Terminal::data ()
Definition at line 243 of file terminal.cc.
References ArmISA::len, SerialDevice::notifyInterface(), read(), rxbuf, and CircleBuf< T >::write().
Referenced by Terminal::DataEvent::process().
dataAvailable()
bool Terminal::dataAvailable () const inline override virtual
Check if there is pending data from the serial device.
Returns
true if there is data pending that can be read using the readData() method.
Implements SerialDevice.
Definition at line 132 of file terminal.hh.
References console_in(), and CircularQueue< T >::empty().
Referenced by console_in().
detach()
void Terminal::detach ()
Definition at line 228 of file terminal.cc.
References data_fd, dataEvent, DPRINTFN, number, pollQueue, and PollQueue::remove().
Referenced by Terminal::DataEvent::process(), read(), and write().
listen()
void Terminal::listen (int port) protected
Definition at line 170 of file terminal.cc.
References ListenSocket::allDisabled(), ccprintf(), DPRINTF, ListenSocket::getfd(), ListenSocket::listen(), listener, ListenEvent, listenEvent, SimObject::name(), pollQueue, PollQueue::schedule(), and warn_once.
Referenced by Terminal().
read() [1/2]
void Terminal::read (uint8_t & c) inline
Definition at line 123 of file terminal.hh.
References ArmISA::len, and read().
Referenced by data(), and read().
read() [2/2]
size_t Terminal::read (uint8_t * buf, size_t len)
Definition at line 256 of file terminal.cc.
References data_fd, detach(), DPRINTFN, panic, and read().
readData()
uint8_t Terminal::readData () override virtual
Read a character from the device.
Returns
Character from the device's output buffer, undefined if no data is pending.
Implements SerialDevice.
Definition at line 298 of file terminal.cc.
References ArmISA::c, DPRINTF, CircularQueue< T >::empty(), CircleBuf< T >::read(), and rxbuf.
Referenced by console_in(), and write().
terminalDump()
OutputStream * Terminal::terminalDump (const TerminalParams * p)
Definition at line 149 of file terminal.cc.
References OutputDirectory::findOrCreate(), Stats::none, panic, and simout.
write() [1/2]
void Terminal::write (uint8_t c) inline
Definition at line 125 of file terminal.hh.
References ArmISA::c, detach(), readData(), write(), and writeData().
Referenced by accept(), write(), and writeData().
write() [2/2]
size_t Terminal::write (const uint8_t * buf, size_t len)
Definition at line 280 of file terminal.cc.
References atomic_write(), data_fd, detach(), and panic.
writeData()
void Terminal::writeData (uint8_t c) override virtual
Transmit a character from the host interface to the device.
Parameters
c Received data.
Implements SerialDevice.
Definition at line 330 of file terminal.cc.
References ArmISA::c, data_fd, DPRINTF, DTRACE, outfile, OutputStream::stream(), Terminal(), txbuf, CircleBuf< T >::write(), and write().
Referenced by AlphaBackdoor::write(), and write().
Friends And Related Function Documentation
DataEvent
friend class DataEvent friend
Definition at line 90 of file terminal.hh.
Referenced by accept().
ListenEvent
friend class ListenEvent friend
Definition at line 77 of file terminal.hh.
Referenced by listen().
Member Data Documentation
data_fd
int Terminal::data_fd protected
Definition at line 95 of file terminal.hh.
Referenced by accept(), detach(), read(), write(), writeData(), and ~Terminal().
dataEvent
DataEvent* Terminal::dataEvent protected
Definition at line 91 of file terminal.hh.
Referenced by accept(), detach(), and ~Terminal().
listener
ListenSocket Terminal::listener protected
Definition at line 104 of file terminal.hh.
Referenced by accept(), and listen().
listenEvent
ListenEvent* Terminal::listenEvent protected
Definition at line 78 of file terminal.hh.
Referenced by listen(), and ~Terminal().
number
int Terminal::number protected
Definition at line 94 of file terminal.hh.
Referenced by accept(), and detach().
outfile
OutputStream* Terminal::outfile protected
Definition at line 112 of file terminal.hh.
Referenced by Terminal(), and writeData().
rxbuf
CircleBuf<char> Terminal::rxbuf protected
Definition at line 111 of file terminal.hh.
Referenced by console_in(), data(), and readData().
txbuf
CircleBuf<char> Terminal::txbuf protected
Definition at line 110 of file terminal.hh.
Referenced by accept(), and writeData().
The documentation for this class was generated from the following files:
dev/serial/terminal.hh
dev/serial/terminal.cc