gem5: Minor::BranchData Class Reference
Minor::BranchData Class Reference
Forward data betwen Execute and Fetch1 carrying change-of-address/stream information.
#include <pipe_data.hh>
Public Types
enum Reason {
NoBranch, CorrectlyPredictedBranch, UnpredictedBranch, BranchPrediction,
BadlyPredictedBranchTarget, BadlyPredictedBranch, SuspendThread, Interrupt,
HaltFetch
}
Public Member Functions
BranchData ()
BranchData (Reason reason_, ThreadID thread_id, InstSeqNum new_stream_seq_num, InstSeqNum new_prediction_seq_num, TheISA::PCState target, MinorDynInstPtr inst_)
bool isBubble () const
bool isStreamChange () const
As static isStreamChange but on this branch data.
bool isBranch () const
As static isBranch but on this branch data.
void reportData (std::ostream &os) const
ReportIF interface.
Static Public Member Functions
static bool isStreamChange (const BranchData::Reason reason)
Is a request with this reason actually a request to change the PC rather than a bubble or branch prediction information.
static bool isBranch (const BranchData::Reason reason)
Is a request with this reason actually a 'real' branch, that is, a stream change that's not just an instruction to Fetch1 to halt or wake up.
static BranchData bubble ()
BubbleIF interface.
Public Attributes
Reason reason
Explanation for this branch.
ThreadID threadId
ThreadID associated with branch.
InstSeqNum newStreamSeqNum
Sequence number of new stream/prediction to be adopted.
InstSeqNum newPredictionSeqNum
TheISA::PCState target
Starting PC of that stream.
MinorDynInstPtr inst
Instruction which caused this branch.
Detailed Description
Forward data betwen Execute and Fetch1 carrying change-of-address/stream information.
Definition at line 64 of file pipe_data.hh.
Member Enumeration Documentation
Reason
enum Minor::BranchData::Reason
Enumerator
NoBranch
CorrectlyPredictedBranch
UnpredictedBranch
BranchPrediction
BadlyPredictedBranchTarget
BadlyPredictedBranch
SuspendThread
Interrupt
HaltFetch
Definition at line 67 of file pipe_data.hh.
Constructor & Destructor Documentation
BranchData() [1/2]
Minor::BranchData::BranchData () inline
Definition at line 127 of file pipe_data.hh.
Referenced by bubble().
BranchData() [2/2]
Minor::BranchData::BranchData (Reason reason_, ThreadID thread_id, InstSeqNum new_stream_seq_num, InstSeqNum new_prediction_seq_num, TheISA::PCState target, MinorDynInstPtr inst_) inline
Definition at line 133 of file pipe_data.hh.
Member Function Documentation
bubble()
static BranchData Minor::BranchData::bubble () inline static
BubbleIF interface.
Definition at line 149 of file pipe_data.hh.
References BranchData().
Referenced by Minor::Execute::evaluate().
isBranch() [1/2]
bool Minor::BranchData::isBranch (const BranchData::Reason reason) static
Is a request with this reason actually a 'real' branch, that is, a stream change that's not just an instruction to Fetch1 to halt or wake up.
Definition at line 111 of file pipe_data.cc.
References BadlyPredictedBranch, BadlyPredictedBranchTarget, BranchPrediction, CorrectlyPredictedBranch, HaltFetch, Interrupt, NoBranch, SuspendThread, and UnpredictedBranch.
isBranch() [2/2]
bool Minor::BranchData::isBranch () const inline
As static isBranch but on this branch data.
Definition at line 156 of file pipe_data.hh.
References isBranch(), Minor::operator<<(), X86ISA::os, reason, and reportData().
Referenced by isBranch().
isBubble()
bool Minor::BranchData::isBubble () const inline
Definition at line 150 of file pipe_data.hh.
References NoBranch.
Referenced by Minor::Execute::commitInst(), Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), Minor::Fetch1::evaluate(), Minor::ForwardLineData::freeLine(), reportData(), Minor::ForwardLineData::reportData(), and Minor::ForwardInstData::width().
isStreamChange() [1/2]
bool Minor::BranchData::isStreamChange (const BranchData::Reason reason) static
Is a request with this reason actually a request to change the PC rather than a bubble or branch prediction information.
Definition at line 83 of file pipe_data.cc.
References BadlyPredictedBranch, BadlyPredictedBranchTarget, BranchPrediction, CorrectlyPredictedBranch, HaltFetch, Interrupt, NoBranch, SuspendThread, and UnpredictedBranch.
Referenced by Minor::Execute::commit(), Minor::Fetch2::evaluate(), and Minor::Fetch1::evaluate().
isStreamChange() [2/2]
bool Minor::BranchData::isStreamChange () const inline
As static isStreamChange but on this branch data.
Definition at line 153 of file pipe_data.hh.
References isStreamChange().
Referenced by isStreamChange(), and Minor::Execute::updateBranchData().
reportData()
void Minor::BranchData::reportData (std::ostream & os) const
ReportIF interface.
Definition at line 139 of file pipe_data.cc.
References inst, isBubble(), newPredictionSeqNum, newStreamSeqNum, reason, and target.
Referenced by isBranch(), Minor::ForwardLineData::isBubble(), and Minor::ForwardInstData::width().
Member Data Documentation
inst
MinorDynInstPtr Minor::BranchData::inst
Instruction which caused this branch.
Definition at line 124 of file pipe_data.hh.
Referenced by Minor::operator<<(), reportData(), and Minor::Fetch2::updateBranchPrediction().
newPredictionSeqNum
InstSeqNum Minor::BranchData::newPredictionSeqNum
Definition at line 118 of file pipe_data.hh.
Referenced by Minor::operator<<(), reportData(), and Minor::Fetch1::updateExpectedSeqNums().
newStreamSeqNum
InstSeqNum Minor::BranchData::newStreamSeqNum
Sequence number of new stream/prediction to be adopted.
Definition at line 117 of file pipe_data.hh.
Referenced by Minor::Fetch1::evaluate(), Minor::operator<<(), reportData(), and Minor::Fetch1::updateExpectedSeqNums().
reason
Reason Minor::BranchData::reason
Explanation for this branch.
Definition at line 111 of file pipe_data.hh.
Referenced by Minor::Fetch1::changeStream(), isBranch(), Minor::operator<<(), reportData(), and Minor::Fetch2::updateBranchPrediction().
target
TheISA::PCState Minor::BranchData::target
Starting PC of that stream.
Definition at line 121 of file pipe_data.hh.
Referenced by Minor::Fetch1::changeStream(), Minor::operator<<(), Minor::Fetch2::predictBranch(), reportData(), and Minor::Fetch2::updateBranchPrediction().
threadId
ThreadID Minor::BranchData::threadId
ThreadID associated with branch.
Definition at line 114 of file pipe_data.hh.
Referenced by Minor::Fetch1::changeStream(), Minor::Fetch2::evaluate(), Minor::Fetch1::evaluate(), and Minor::Fetch1::updateExpectedSeqNums().
The documentation for this class was generated from the following files:
cpu/minor/pipe_data.hh
cpu/minor/pipe_data.cc