gem5: SnoopFilter Class Reference
SnoopFilter Class Reference
This snoop filter keeps track of which connected port has a particular line of data.
#include <snoop_filter.hh>
Classes
struct ReqLookupResult
A request lookup must be followed by a call to finishRequest to inform the operation's success.
struct SnoopItem
Per cache line item tracking a bitmask of SlavePorts who have an outstanding request to this line (requested) or already share a cache line with this address (holder).
Public Types
typedef std::vector< QueuedSlavePort * > SnoopList
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
SnoopFilter (const SnoopFilterParams *p)
void setSlavePorts (const SnoopList &slave_ports)
Init a new snoop filter and tell it about all the slave ports of the enclosing bus.
std::pair< SnoopList, Cycles > lookupRequest (const Packet *cpkt, const SlavePort &slave_port)
Lookup a request (from a slave port) in the snoop filter and return a list of other slave ports that need forwarding of the resulting snoops.
void finishRequest (bool will_retry, Addr addr, bool is_secure)
For an un-successful request, revert the change to the snoop filter.
std::pair< SnoopList, Cycles > lookupSnoop (const Packet *cpkt)
Handle an incoming snoop from below (the master port).
void updateSnoopResponse (const Packet *cpkt, const SlavePort &rsp_port, const SlavePort &req_port)
Let the snoop filter see any snoop responses that turn into request responses and indicate cache to cache transfers.
void updateSnoopForward (const Packet *cpkt, const SlavePort &rsp_port, const MasterPort &req_port)
Pass snoop responses that travel downward through the snoop filter and let them update the snoop filter state.
void updateResponse (const Packet *cpkt, const SlavePort &slave_port)
Update the snoop filter with a response from below (outer / other cache, or memory) and update the tracking information in the snoop filter.
virtual void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Attributes
static const int SNOOP_MASK_SIZE = 256
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
typedef std::bitset< SNOOP_MASK_SIZE > SnoopMask
The underlying type for the bitmask we use for tracking.
typedef std::unordered_map< Addr, SnoopItem > SnoopFilterCache
HashMap of SnoopItems indexed by line address.
Protected Member Functions
std::pair< SnoopList, Cycles > snoopAll (Cycles latency) const
Simple factory methods for standard return values.
std::pair< SnoopList, Cycles > snoopSelected (const SnoopList &slave_ports, Cycles latency) const
std::pair< SnoopList, Cycles > snoopDown (Cycles latency) const
SnoopMask portToMask (const SlavePort &port) const
Convert a single port to a corresponding, one-hot bitmask.
SnoopList maskToPortList (SnoopMask ports) const
Converts a bitmask of ports into the corresponing list of ports.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Types
enum LineStatus { LineSecure = 0x01 }
Use the lower bits of the address to keep track of the line status.
Private Member Functions
void eraseIfNullEntry (SnoopFilterCache::iterator &sf_it)
Removes snoop filter items which have no requesters and no holders.
Private Attributes
SnoopFilterCache cachedLocations
Simple hash set of cached addresses.
struct SnoopFilter::ReqLookupResult reqLookupResult
SnoopList slavePorts
List of all attached snooping slave ports.
std::vector< PortID > localSlavePortIds
Track the mapping from port ids to the local mask ids.
const unsigned linesize
Cache line size.
const Cycles lookupLatency
Latency for doing a lookup in the filter.
const unsigned maxEntryCount
Max capacity in terms of cache blocks tracked, for sanity checking.
Stats::Scalar totRequests
Statistics.
Stats::Scalar hitSingleRequests
Stats::Scalar hitMultiRequests
Stats::Scalar totSnoops
Stats::Scalar hitSingleSnoops
Stats::Scalar hitMultiSnoops
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
This snoop filter keeps track of which connected port has a particular line of data.
It can be queried (through lookup*) on memory requests from above (reads / writes / ...); and also from below (snoops). The snoop filter precisely knows about the location of lines "above" it through a map from cache line address to sharers/ports. The snoop filter ties into the flows of requests (when they succeed at the lower interface), regular responses from below and also responses from sideway's caches (in update*). This allows the snoop filter to model cache-line residency by snooping the messages.
The tracking happens in two fields to be able to distinguish between in-flight requests (in requested) and already pulled in lines (in holder). This distinction is used for producing tighter assertions and tracking request completion. For safety, (requested | holder) should be notified and the requesting MSHRs will take care of ordering.
Overall, some trickery is required because: (1) snoops are not followed by an ACK, but only evoke a response if they need to (hit dirty) (2) side-channel information is funnelled through direct modifications of pkt, instead of proper messages through the bus (3) there are no clean evict messages telling the snoop filter that a local, upper cache dropped a line, making the snoop filter pessimistic for now (4) ordering: there is no single point of order in the system. Instead, requesting MSHRs track order between local requests and remote snoops
Definition at line 88 of file snoop_filter.hh.
Member Typedef Documentation
SnoopFilterCache
typedef std::unordered_map<Addr, SnoopItem> SnoopFilter::SnoopFilterCache protected
HashMap of SnoopItems indexed by line address.
Definition at line 222 of file snoop_filter.hh.
SnoopList
typedef std::vector<QueuedSlavePort*> SnoopFilter::SnoopList
Definition at line 94 of file snoop_filter.hh.
SnoopMask
typedef std::bitset<SNOOP_MASK_SIZE> SnoopFilter::SnoopMask protected
The underlying type for the bitmask we use for tracking.
This limits the number of snooping ports supported per crossbar.
Definition at line 208 of file snoop_filter.hh.
Member Enumeration Documentation
LineStatus
enum SnoopFilter::LineStatus private
Use the lower bits of the address to keep track of the line status.
Enumerator
LineSecure
block holds data from the secure memory space
Definition at line 309 of file snoop_filter.hh.
Constructor & Destructor Documentation
SnoopFilter()
SnoopFilter::SnoopFilter (const SnoopFilterParams * p) inline
Definition at line 96 of file snoop_filter.hh.
Referenced by regStats().
Member Function Documentation
eraseIfNullEntry()
void SnoopFilter::eraseIfNullEntry (SnoopFilterCache::iterator & sf_it) private
Removes snoop filter items which have no requesters and no holders.
Definition at line 55 of file snoop_filter.cc.
References cachedLocations, DPRINTF, SnoopFilter::SnoopItem::holder, and SnoopFilter::SnoopItem::requested.
Referenced by finishRequest(), lookupSnoop(), snoopDown(), updateResponse(), and updateSnoopForward().
finishRequest()
void SnoopFilter::finishRequest (bool will_retry, Addr addr, bool is_secure)
For an un-successful request, revert the change to the snoop filter.
Also take care of erasing any null entries. This method relies on the result from lookupRequest being stored in reqLookupResult.
Parameters
will_retry This request will retry on this bus / snoop filter
addr Packet address, merely for sanity checking
Definition at line 158 of file snoop_filter.cc.
References cachedLocations, DPRINTF, eraseIfNullEntry(), SnoopFilter::SnoopItem::holder, SnoopFilter::ReqLookupResult::it, LineSecure, linesize, reqLookupResult, SnoopFilter::SnoopItem::requested, and SnoopFilter::ReqLookupResult::retryItem.
Referenced by CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), and setSlavePorts().
lookupRequest()
std::pair< SnoopFilter::SnoopList, Cycles > SnoopFilter::lookupRequest (const Packet * cpkt, const SlavePort & slave_port)
Lookup a request (from a slave port) in the snoop filter and return a list of other slave ports that need forwarding of the resulting snoops.
Additionally, update the tracking structures with new request information. Note that the caller must also call finishRequest once it is known if the request needs to retry or not.
Parameters
cpkt Pointer to the request packet. Not changed.
slave_port Slave port where the request came from.
Returns
Pair of a vector of snoop target ports and lookup latency.
Definition at line 66 of file snoop_filter.cc.
References cachedLocations, Packet::cacheResponding(), DPRINTF, Packet::fromCache(), Packet::getBlockAddr(), hitMultiRequests, hitSingleRequests, SnoopFilter::SnoopItem::holder, Packet::isBlockCached(), Packet::isEviction(), Packet::isSecure(), SlavePort::isSnooping(), SnoopFilter::ReqLookupResult::it, LineSecure, linesize, lookupLatency, maskToPortList(), Port::name(), Packet::needsResponse(), panic_if, portToMask(), Packet::print(), Packet::req, reqLookupResult, SnoopFilter::SnoopItem::requested, SnoopFilter::ReqLookupResult::retryItem, snoopDown(), snoopSelected(), and totRequests.
Referenced by CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), and setSlavePorts().
lookupSnoop()
std::pair< SnoopFilter::SnoopList, Cycles > SnoopFilter::lookupSnoop (const Packet * cpkt)
Handle an incoming snoop from below (the master port).
These can upgrade the tracking logic and may also benefit from additional steering thanks to the snoop filter.
Parameters
cpkt Pointer to const Packet containing the snoop.
Returns
Pair with a vector of SlavePorts that need snooping and a lookup latency.
Definition at line 184 of file snoop_filter.cc.
References cachedLocations, DPRINTF, eraseIfNullEntry(), Packet::getBlockAddr(), hitMultiSnoops, hitSingleSnoops, SnoopFilter::SnoopItem::holder, Packet::isInvalidate(), Packet::isRequest(), Packet::isSecure(), Packet::isWriteback(), LineSecure, linesize, lookupLatency, maskToPortList(), maxEntryCount, Packet::needsWritable(), panic_if, Packet::print(), Packet::req, SnoopFilter::SnoopItem::requested, snoopDown(), snoopSelected(), and totSnoops.
Referenced by CoherentXBar::recvAtomicSnoop(), CoherentXBar::recvTimingSnoopReq(), and setSlavePorts().
maskToPortList()
SnoopFilter::SnoopList SnoopFilter::maskToPortList (SnoopMask ports) const inline protected
Converts a bitmask of ports into the corresponing list of ports.
Parameters
ports SnoopMask of the requested ports
Returns
SnoopList containing all the requested SlavePorts
Definition at line 334 of file snoop_filter.hh.
References MipsISA::p, portToMask(), and slavePorts.
Referenced by lookupRequest(), lookupSnoop(), and snoopDown().
portToMask()
SnoopFilter::SnoopMask SnoopFilter::portToMask (const SlavePort & port) const inline protected
Convert a single port to a corresponding, one-hot bitmask.
Parameters
port SlavePort that should be converted.
Returns
One-hot bitmask corresponding to the port.
Definition at line 325 of file snoop_filter.hh.
References Port::getId(), InvalidPortID, SlavePort::isSnooping(), and localSlavePortIds.
Referenced by lookupRequest(), maskToPortList(), snoopDown(), updateResponse(), and updateSnoopResponse().
regStats()
void SnoopFilter::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 391 of file snoop_filter.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), hitMultiRequests, hitMultiSnoops, hitSingleRequests, hitSingleSnoops, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::Group::regStats(), SnoopFilter(), totRequests, and totSnoops.
Referenced by setSlavePorts().
setSlavePorts()
void SnoopFilter::setSlavePorts (const SnoopList & slave_ports) inline
Init a new snoop filter and tell it about all the slave ports of the enclosing bus.
Parameters
slave_ports Slave ports that the bus is attached to.
Definition at line 109 of file snoop_filter.hh.
References addr, fatal_if, finishRequest(), InvalidPortID, localSlavePortIds, lookupRequest(), lookupSnoop(), MipsISA::p, regStats(), slavePorts, updateResponse(), updateSnoopForward(), and updateSnoopResponse().
Referenced by CoherentXBar::init().
snoopAll()
std::pair<SnoopList, Cycles> SnoopFilter::snoopAll (Cycles latency) const inline protected
Simple factory methods for standard return values.
Definition at line 227 of file snoop_filter.hh.
References slavePorts.
snoopDown()
std::pair<SnoopList, Cycles> SnoopFilter::snoopDown (Cycles latency) const inline protected
Definition at line 236 of file snoop_filter.hh.
References eraseIfNullEntry(), maskToPortList(), and portToMask().
Referenced by lookupRequest(), and lookupSnoop().
snoopSelected()
std::pair<SnoopList, Cycles> SnoopFilter::snoopSelected (const SnoopList & slave_ports, Cycles latency) const inline protected
Definition at line 231 of file snoop_filter.hh.
Referenced by lookupRequest(), and lookupSnoop().
updateResponse()
void SnoopFilter::updateResponse (const Packet * cpkt, const SlavePort & slave_port)
Update the snoop filter with a response from below (outer / other cache, or memory) and update the tracking information in the snoop filter.
Parameters
cpkt Pointer to const Packet holding the snoop response.
slave_port SlavePort that made the original request and is the target of this response.
Definition at line 338 of file snoop_filter.cc.
References cachedLocations, DPRINTF, eraseIfNullEntry(), Packet::getBlockAddr(), SnoopFilter::SnoopItem::holder, Packet::isInvalidate(), Packet::isResponse(), Packet::isSecure(), SlavePort::isSnooping(), LineSecure, linesize, Port::name(), panic_if, portToMask(), Packet::print(), Packet::req, and SnoopFilter::SnoopItem::requested.
Referenced by CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), CoherentXBar::recvTimingResp(), and setSlavePorts().
updateSnoopForward()
void SnoopFilter::updateSnoopForward (const Packet * cpkt, const SlavePort & rsp_port, const MasterPort & req_port)
Pass snoop responses that travel downward through the snoop filter and let them update the snoop filter state.
No additional routing happens.
Parameters
cpkt Pointer to const Packet holding the snoop response.
rsp_port SlavePort that sends the response.
req_port MasterPort through which the response is forwarded.
Definition at line 301 of file snoop_filter.cc.
References cachedLocations, Packet::cacheResponding(), DPRINTF, eraseIfNullEntry(), Packet::getBlockAddr(), Packet::hasSharers(), SnoopFilter::SnoopItem::holder, Packet::isResponse(), Packet::isSecure(), LineSecure, linesize, Port::name(), Packet::print(), and SnoopFilter::SnoopItem::requested.
Referenced by CoherentXBar::forwardAtomic(), CoherentXBar::recvTimingSnoopResp(), and setSlavePorts().
updateSnoopResponse()
void SnoopFilter::updateSnoopResponse (const Packet * cpkt, const SlavePort & rsp_port, const SlavePort & req_port)
Let the snoop filter see any snoop responses that turn into request responses and indicate cache to cache transfers.
These will update the corresponding state in the filter.
Parameters
cpkt Pointer to const Packet holding the snoop response.
rsp_port SlavePort that sends the response.
req_port SlavePort that made the original request and is the destination of the snoop response.
Definition at line 244 of file snoop_filter.cc.
References cachedLocations, Packet::cacheResponding(), DPRINTF, Packet::getBlockAddr(), Packet::hasSharers(), SnoopFilter::SnoopItem::holder, Packet::isResponse(), Packet::isSecure(), SlavePort::isSnooping(), Packet::isWriteback(), LineSecure, linesize, Port::name(), panic_if, portToMask(), Packet::print(), Packet::req, and SnoopFilter::SnoopItem::requested.
Referenced by CoherentXBar::forwardAtomic(), CoherentXBar::recvTimingSnoopResp(), and setSlavePorts().
Member Data Documentation
cachedLocations
SnoopFilterCache SnoopFilter::cachedLocations private
Simple hash set of cached addresses.
Definition at line 263 of file snoop_filter.hh.
Referenced by eraseIfNullEntry(), finishRequest(), lookupRequest(), lookupSnoop(), updateResponse(), updateSnoopForward(), and updateSnoopResponse().
hitMultiRequests
Stats::Scalar SnoopFilter::hitMultiRequests private
Definition at line 317 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
hitMultiSnoops
Stats::Scalar SnoopFilter::hitMultiSnoops private
Definition at line 321 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
hitSingleRequests
Stats::Scalar SnoopFilter::hitSingleRequests private
Definition at line 316 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
hitSingleSnoops
Stats::Scalar SnoopFilter::hitSingleSnoops private
Definition at line 320 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
linesize
const unsigned SnoopFilter::linesize private
Cache line size.
Definition at line 300 of file snoop_filter.hh.
Referenced by finishRequest(), lookupRequest(), lookupSnoop(), updateResponse(), updateSnoopForward(), and updateSnoopResponse().
localSlavePortIds
std::vector<PortID> SnoopFilter::localSlavePortIds private
Track the mapping from port ids to the local mask ids.
Definition at line 298 of file snoop_filter.hh.
Referenced by portToMask(), and setSlavePorts().
lookupLatency
const Cycles SnoopFilter::lookupLatency private
Latency for doing a lookup in the filter.
Definition at line 302 of file snoop_filter.hh.
Referenced by lookupRequest(), and lookupSnoop().
maxEntryCount
const unsigned SnoopFilter::maxEntryCount private
Max capacity in terms of cache blocks tracked, for sanity checking.
Definition at line 304 of file snoop_filter.hh.
Referenced by lookupSnoop().
reqLookupResult
struct SnoopFilter::ReqLookupResult SnoopFilter::reqLookupResult private
Referenced by finishRequest(), lookupRequest(), and SnoopFilter::ReqLookupResult::ReqLookupResult().
slavePorts
SnoopList SnoopFilter::slavePorts private
List of all attached snooping slave ports.
Definition at line 296 of file snoop_filter.hh.
Referenced by maskToPortList(), setSlavePorts(), and snoopAll().
SNOOP_MASK_SIZE
const int SnoopFilter::SNOOP_MASK_SIZE = 256 static
Definition at line 92 of file snoop_filter.hh.
totRequests
Stats::Scalar SnoopFilter::totRequests private
Statistics.
Definition at line 315 of file snoop_filter.hh.
Referenced by lookupRequest(), and regStats().
totSnoops
Stats::Scalar SnoopFilter::totSnoops private
Definition at line 319 of file snoop_filter.hh.
Referenced by lookupSnoop(), and regStats().
The documentation for this class was generated from the following files:
mem/snoop_filter.hh
mem/snoop_filter.cc