gem5: SMMUControlPort Class Reference
SMMUControlPort Class Reference
#include <smmu_v3_ports.hh>
Public Member Functions
SMMUControlPort (const std::string &_name, SMMUv3 &_smmu, AddrRange _addrRange)
virtual ~SMMUControlPort ()
Public Member Functions inherited from SimpleTimingPort
SimpleTimingPort (const std::string &name, SimObject *owner)
Create a new SimpleTimingPort that relies on a packet queue to hold responses, and implements recvTimingReq and recvFunctional through calls to recvAtomic.
virtual ~SimpleTimingPort ()
Public Member Functions inherited from QueuedSlavePort
QueuedSlavePort (const std::string &name, SimObject *owner, RespPacketQueue &resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
virtual ~QueuedSlavePort ()
void schedTimingResp (PacketPtr pkt, Tick when)
Schedule the sending of a timing response.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
virtual Tick recvAtomic (PacketPtr pkt)
Receive an atomic request packet from the peer.
virtual AddrRangeList getAddrRanges () const
Get a list of the non-overlapping address ranges the owner is responsible for.
Protected Member Functions inherited from SimpleTimingPort
void recvFunctional (PacketPtr pkt)
Implemented using recvAtomic().
bool recvTimingReq (PacketPtr pkt)
Implemented using recvAtomic().
Protected Member Functions inherited from QueuedSlavePort
void recvRespRetry ()
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
SMMUv3 & smmu
AddrRange addrRange
Protected Attributes inherited from SimpleTimingPort
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Protected Attributes inherited from QueuedSlavePort
RespPacketQueue & respQueue
Packet queue used to store outgoing responses.
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Definition at line 96 of file smmu_v3_ports.hh.
Constructor & Destructor Documentation
SMMUControlPort()
SMMUControlPort::SMMUControlPort (const std::string & _name, SMMUv3 & _smmu, AddrRange _addrRange)
Definition at line 109 of file smmu_v3_ports.cc.
~SMMUControlPort()
virtual SMMUControlPort::~SMMUControlPort () inline virtual
Definition at line 108 of file smmu_v3_ports.hh.
Member Function Documentation
getAddrRanges()
AddrRangeList SMMUControlPort::getAddrRanges () const protected virtual
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns
a list of ranges responded to
Implements SlavePort.
Definition at line 134 of file smmu_v3_ports.cc.
References addrRange, and sc_dt::list.
recvAtomic()
Tick SMMUControlPort::recvAtomic (PacketPtr pkt) protected virtual
Receive an atomic request packet from the peer.
Implements SimpleTimingPort.
Definition at line 118 of file smmu_v3_ports.cc.
References addr, addrRange, AddrRange::contains(), Packet::getAddr(), Packet::getSize(), Packet::headerDelay, Packet::isRead(), panic, Packet::payloadDelay, SMMUv3::readControl(), smmu, and SMMUv3::writeControl().
Member Data Documentation
addrRange
AddrRange SMMUControlPort::addrRange protected
Definition at line 100 of file smmu_v3_ports.hh.
Referenced by getAddrRanges(), and recvAtomic().
smmu
SMMUv3& SMMUControlPort::smmu protected
Definition at line 99 of file smmu_v3_ports.hh.
Referenced by recvAtomic().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_ports.hh
dev/arm/smmu_v3_ports.cc