gem5: ComputeUnit::DataPort Class Reference
ComputeUnit::DataPort Class Reference
Data access Port.
#include <compute_unit.hh>
Classes
struct SenderState
Public Member Functions
DataPort (const std::string &_name, ComputeUnit *_cu, PortID _index)
void processMemReqEvent (PacketPtr pkt)
EventFunctionWrapper * createMemReqEvent (PacketPtr pkt)
void processMemRespEvent (PacketPtr pkt)
EventFunctionWrapper * createMemRespEvent (PacketPtr pkt)
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Public Attributes
bool snoopRangeSent
std::deque< std::pair< PacketPtr, GPUDynInstPtr > > retries
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the peer.
virtual Tick recvAtomic (PacketPtr pkt)
virtual void recvFunctional (PacketPtr pkt)
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
virtual void recvReqRetry ()
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
virtual void getDeviceAddressRanges (AddrRangeList &resp, bool &snoop)
Protected Member Functions inherited from MasterPort
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
ComputeUnit * computeUnit
int index
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Data access Port.
Definition at line 422 of file compute_unit.hh.
Constructor & Destructor Documentation
DataPort()
ComputeUnit::DataPort::DataPort (const std::string & _name, ComputeUnit * _cu, PortID _index) inline
Definition at line 425 of file compute_unit.hh.
Member Function Documentation
createMemReqEvent()
EventFunctionWrapper * ComputeUnit::DataPort::createMemReqEvent (PacketPtr pkt)
Definition at line 1238 of file compute_unit.cc.
createMemRespEvent()
EventFunctionWrapper * ComputeUnit::DataPort::createMemRespEvent (PacketPtr pkt)
Definition at line 1246 of file compute_unit.cc.
getDeviceAddressRanges()
virtual void ComputeUnit::DataPort::getDeviceAddressRanges (AddrRangeList & resp, bool & snoop) inline protected virtual
Definition at line 463 of file compute_unit.hh.
processMemReqEvent()
void ComputeUnit::DataPort::processMemReqEvent (PacketPtr pkt)
Definition at line 1254 of file compute_unit.cc.
References ComputeUnit::DataPort::SenderState::_gpuDynInst, DPRINTF, MipsISA::index, M5_VAR_USED, Packet::req, safe_cast(), and Packet::senderState.
processMemRespEvent()
void ComputeUnit::DataPort::processMemRespEvent (PacketPtr pkt)
Definition at line 976 of file compute_unit.cc.
References ComputeUnit::DataPort::SenderState::_gpuDynInst, Packet::cmd, ComputeUnit::ComputeUnit(), ComputeUnit::cu_id, DPRINTF, ComputeUnit::globalMemoryPipe, GlobalMemPipeline::handleResponse(), MipsISA::index, Packet::isRead(), Packet::isWrite(), MAX_REGS_FOR_NON_VEC_MEM_INST, MemCmd::MemFenceResp, Packet::req, safe_cast(), Packet::senderState, and ULL.
recvAtomic()
virtual Tick ComputeUnit::DataPort::recvAtomic (PacketPtr pkt) inline protected virtual
Definition at line 457 of file compute_unit.hh.
recvFunctional()
virtual void ComputeUnit::DataPort::recvFunctional (PacketPtr pkt) inline protected virtual
Definition at line 458 of file compute_unit.hh.
recvRangeChange()
virtual void ComputeUnit::DataPort::recvRangeChange () inline protected virtual
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 459 of file compute_unit.hh.
recvReqRetry()
void ComputeUnit::DataPort::recvReqRetry () protected virtual
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Currently Ruby can return false due to conflicts for the particular cache block or address. Thus other requests should be allowed to pass and the data port should expect multiple retries.
Implements TimingRequestProtocol.
Definition at line 685 of file compute_unit.cc.
References DPRINTF, ArmISA::i, ArmISA::len, M5_VAR_USED, and Packet::req.
recvTimingResp()
bool ComputeUnit::DataPort::recvTimingResp (PacketPtr pkt) protected virtual
Receive a timing response from the peer.
Implements TimingRequestProtocol.
Definition at line 621 of file compute_unit.cc.
References ComputeUnit::DataPort::SenderState::_gpuDynInst, Wavefront::barrierCnt, curTick(), DPRINTF, MipsISA::index, Wavefront::kernId, Wavefront::outstandingReqs, ComputeUnit::DataPort::SenderState::port_index, Packet::req, Wavefront::S_RETURNING, Wavefront::S_STOPPED, safe_cast(), Packet::senderState, Wavefront::simdId, Wavefront::status, MipsISA::w, Wavefront::wfDynId, and Wavefront::wfSlotId.
Member Data Documentation
computeUnit
ComputeUnit* ComputeUnit::DataPort::computeUnit protected
Definition at line 453 of file compute_unit.hh.
index
int ComputeUnit::DataPort::index protected
Definition at line 454 of file compute_unit.hh.
retries
std::deque<std::pair<PacketPtr, GPUDynInstPtr> > ComputeUnit::DataPort::retries
Definition at line 450 of file compute_unit.hh.
snoopRangeSent
bool ComputeUnit::DataPort::snoopRangeSent
Definition at line 429 of file compute_unit.hh.
The documentation for this class was generated from the following files:
gpu-compute/compute_unit.hh
gpu-compute/compute_unit.cc