gem5: Prefetcher Class Reference
Prefetcher Class Reference
#include <Prefetcher.hh>
Public Types
typedef PrefetcherParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Prefetcher (const Params *p)
~Prefetcher ()
void issueNextPrefetch (Addr address, PrefetchEntry *stream)
void observePfHit (Addr address)
Implement the prefetch hit(miss) callback interface.
void observePfMiss (Addr address)
void observeMiss (Addr address, const RubyRequestType &type)
Observe a memory miss from the cache.
void print (std::ostream &out) const
Print out some statistics.
void setController (AbstractController *_ctrl)
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
uint32_t getLRUindex (void)
Returns an unused stream buffer (or if all are used, returns the least recently used (accessed) stream buffer).
void clearNonunitEntry (uint32_t index)
clear a non-unit stride prefetcher entry
void initializeStream (Addr address, int stride, uint32_t index, const RubyRequestType &type)
allocate a new stream buffer at a specific index
PrefetchEntry * getPrefetchEntry (Addr address, uint32_t &index)
get pointer to the matching stream entry, returns NULL if not found index holds the multiple of the stride this address is.
bool accessUnitFilter (std::vector< Addr > &filter_table, uint32_t *hit_table, uint32_t &index, Addr address, int stride, bool &alloc)
access a unit stride filter to determine if there is a hit
bool accessNonunitFilter (Addr address, int *stride, bool &alloc)
access a unit stride filter to determine if there is a hit
Addr pageAddress (Addr addr) const
determine the page aligned address
Private Attributes
uint32_t m_num_streams
number of prefetch streams available
std::vector< PrefetchEntry > m_array
an array of the active prefetch streams
uint32_t m_train_misses
number of misses I must see before allocating a stream
uint32_t m_num_startup_pfs
number of initial prefetches to startup a stream
uint32_t m_num_unit_filters
number of stride filters
uint32_t m_num_nonunit_filters
number of non-stride filters
std::vector< Addr > m_unit_filter
a unit stride filter array: helps reduce BW requirement of prefetching
uint32_t m_unit_filter_index
a round robin pointer into the unit filter group
uint32_t * m_unit_filter_hit
An array used to count the of times particular filter entries have been hit.
std::vector< Addr > m_negative_filter
a negative nit stride filter array: helps reduce BW requirement of prefetching
uint32_t m_negative_filter_index
a round robin pointer into the negative filter group
uint32_t * m_negative_filter_hit
An array used to count the of times particular filter entries have been hit.
std::vector< Addr > m_nonunit_filter
a non-unit stride filter array: helps reduce BW requirement of prefetching
int * m_nonunit_stride
An array of strides (in # of cache lines) for the filter entries.
uint32_t * m_nonunit_hit
An array used to count the of times particular filter entries have been hit.
uint32_t m_nonunit_index
a round robin pointer into the unit filter group
bool m_prefetch_cross_pages
Used for allowing prefetches across pages.
AbstractController * m_controller
const Addr m_page_shift
Stats::Scalar numMissObserved
Count of accesses to the prefetcher.
Stats::Scalar numAllocatedStreams
Count of prefetch streams allocated.
Stats::Scalar numPrefetchRequested
Count of prefetch requests made.
Stats::Scalar numPrefetchAccepted
Count of prefetch requests accepted.
Stats::Scalar numDroppedPrefetches
Count of prefetches dropped.
Stats::Scalar numHits
Count of successful prefetches.
Stats::Scalar numPartialHits
Count of partial successful prefetches.
Stats::Scalar numPagesCrossed
Count of pages crossed.
Stats::Scalar numMissedPrefetchedBlocks
Count of misses incurred for blocks that were prefetched.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 81 of file Prefetcher.hh.
Member Typedef Documentation
Params
typedef PrefetcherParams Prefetcher::Params
Definition at line 84 of file Prefetcher.hh.
Constructor & Destructor Documentation
Prefetcher()
Prefetcher::Prefetcher (const Params * p)
Definition at line 42 of file Prefetcher.cc.
References ArmISA::i, m_negative_filter_hit, m_negative_filter_index, m_nonunit_hit, m_nonunit_index, m_nonunit_stride, m_num_nonunit_filters, m_num_startup_pfs, m_num_streams, m_num_unit_filters, m_unit_filter_hit, m_unit_filter_index, and MAX_PF_INFLIGHT.
~Prefetcher()
Prefetcher::~Prefetcher ()
Definition at line 80 of file Prefetcher.cc.
References m_negative_filter_hit, m_nonunit_hit, m_nonunit_stride, and m_unit_filter_hit.
Member Function Documentation
accessNonunitFilter()
bool Prefetcher::accessNonunitFilter (Addr address, int * stride, bool & alloc) private
access a unit stride filter to determine if there is a hit
look for non-unit strides based on a (user-defined) page size
Definition at line 381 of file Prefetcher.cc.
References clearNonunitEntry(), RubySystem::getBlockSizeBytes(), ArmISA::i, m_nonunit_filter, m_nonunit_hit, m_nonunit_index, m_nonunit_stride, m_num_nonunit_filters, m_train_misses, makeLineAddress(), and pageAddress().
Referenced by observeMiss().
accessUnitFilter()
bool Prefetcher::accessUnitFilter (std::vector< Addr > & filter_table, uint32_t * hit_table, uint32_t & index, Addr address, int stride, bool & alloc) private
access a unit stride filter to determine if there is a hit
Definition at line 348 of file Prefetcher.cc.
References ArmISA::i, MipsISA::index, m_num_unit_filters, m_train_misses, makeLineAddress(), and makeNextStrideAddress().
Referenced by observeMiss().
clearNonunitEntry()
void Prefetcher::clearNonunitEntry (uint32_t index) private
clear a non-unit stride prefetcher entry
Definition at line 281 of file Prefetcher.cc.
References MipsISA::index, m_nonunit_filter, m_nonunit_hit, and m_nonunit_stride.
Referenced by accessNonunitFilter().
getLRUindex()
uint32_t Prefetcher::getLRUindex (void) private
Returns an unused stream buffer (or if all are used, returns the least recently used (accessed) stream buffer).
Returns
The index of the least recently used stream buffer.
Definition at line 262 of file Prefetcher.cc.
References ArmISA::i, m_array, and m_num_streams.
Referenced by observeMiss().
getPrefetchEntry()
PrefetchEntry * Prefetcher::getPrefetchEntry (Addr address, uint32_t & index) private
get pointer to the matching stream entry, returns NULL if not found index holds the multiple of the stride this address is.
Definition at line 330 of file Prefetcher.cc.
References ArmISA::i, ArmISA::j, m_array, m_num_startup_pfs, m_num_streams, and makeNextStrideAddress().
Referenced by issueNextPrefetch(), and observeMiss().
initializeStream()
void Prefetcher::initializeStream (Addr address, int stride, uint32_t index, const RubyRequestType & type) private
allocate a new stream buffer at a specific index
Definition at line 289 of file Prefetcher.cc.
References Clocked::curCycle(), DPRINTF, AbstractController::enqueuePrefetch(), MipsISA::index, MipsISA::k, PrefetchEntry::m_address, m_array, m_controller, PrefetchEntry::m_is_valid, m_num_startup_pfs, m_prefetch_cross_pages, PrefetchEntry::m_stride, PrefetchEntry::m_type, PrefetchEntry::m_use_time, makeLineAddress(), makeNextStrideAddress(), numAllocatedStreams, numPagesCrossed, numPrefetchRequested, pageAddress(), ArmISA::stride, and type.
Referenced by observeMiss().
issueNextPrefetch()
void Prefetcher::issueNextPrefetch (Addr address, PrefetchEntry * stream)
Definition at line 224 of file Prefetcher.cc.
References Clocked::curCycle(), DPRINTF, AbstractController::enqueuePrefetch(), getPrefetchEntry(), MipsISA::index, PrefetchEntry::m_address, m_controller, PrefetchEntry::m_is_valid, m_prefetch_cross_pages, PrefetchEntry::m_stride, PrefetchEntry::m_type, PrefetchEntry::m_use_time, makeNextStrideAddress(), numPagesCrossed, and pageAddress().
Referenced by observePfHit(), and observePfMiss().
observeMiss()
void Prefetcher::observeMiss (Addr address, const RubyRequestType & type)
Observe a memory miss from the cache.
Parameters
address The physical address that missed out of the cache.
Definition at line 140 of file Prefetcher.cc.
References accessNonunitFilter(), accessUnitFilter(), DPRINTF, getLRUindex(), getPrefetchEntry(), MipsISA::index, initializeStream(), m_negative_filter, m_negative_filter_hit, m_negative_filter_index, m_unit_filter, m_unit_filter_hit, m_unit_filter_index, makeLineAddress(), numMissedPrefetchedBlocks, numMissObserved, numPartialHits, observePfHit(), PrefetchEntry::requestCompleted, PrefetchEntry::requestIssued, and ArmISA::stride.
observePfHit()
void Prefetcher::observePfHit (Addr address)
Implement the prefetch hit(miss) callback interface.
These functions are called by the cache when it hits(misses) on a line with the line's prefetch bit set. If this address hits in m_array we will continue prefetching the stream.
Definition at line 216 of file Prefetcher.cc.
References DPRINTF, issueNextPrefetch(), and numHits.
Referenced by observeMiss().
observePfMiss()
void Prefetcher::observePfMiss (Addr address)
Definition at line 208 of file Prefetcher.cc.
References DPRINTF, issueNextPrefetch(), and numPartialHits.
pageAddress()
Addr Prefetcher::pageAddress (Addr addr) const private
determine the page aligned address
Definition at line 477 of file Prefetcher.cc.
References addr, and m_page_shift.
Referenced by accessNonunitFilter(), initializeStream(), and issueNextPrefetch().
print()
void Prefetcher::print (std::ostream & out) const
Print out some statistics.
Definition at line 444 of file Prefetcher.cc.
References ArmISA::i, m_array, m_negative_filter, m_nonunit_filter, m_nonunit_hit, m_nonunit_stride, m_num_nonunit_filters, m_num_streams, m_num_unit_filters, m_unit_filter, and SimObject::name().
regStats()
void Prefetcher::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 89 of file Prefetcher.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numAllocatedStreams, numDroppedPrefetches, numHits, numMissedPrefetchedBlocks, numMissObserved, numPagesCrossed, numPartialHits, numPrefetchAccepted, numPrefetchRequested, and Stats::Group::regStats().
setController()
void Prefetcher::setController (AbstractController * _ctrl) inline
Definition at line 109 of file Prefetcher.hh.
References addr, MipsISA::index, ArmISA::stride, and type.
Member Data Documentation
m_array
std::vector<PrefetchEntry> Prefetcher::m_array private
an array of the active prefetch streams
Definition at line 149 of file Prefetcher.hh.
Referenced by getLRUindex(), getPrefetchEntry(), initializeStream(), and print().
m_controller
AbstractController* Prefetcher::m_controller private
Definition at line 192 of file Prefetcher.hh.
Referenced by initializeStream(), and issueNextPrefetch().
m_negative_filter
std::vector<Addr> Prefetcher::m_negative_filter private
a negative nit stride filter array: helps reduce BW requirement of prefetching
Definition at line 171 of file Prefetcher.hh.
Referenced by observeMiss(), and print().
m_negative_filter_hit
uint32_t* Prefetcher::m_negative_filter_hit private
An array used to count the of times particular filter entries have been hit.
Definition at line 176 of file Prefetcher.hh.
Referenced by observeMiss(), Prefetcher(), and ~Prefetcher().
m_negative_filter_index
uint32_t Prefetcher::m_negative_filter_index private
a round robin pointer into the negative filter group
Definition at line 173 of file Prefetcher.hh.
Referenced by observeMiss(), and Prefetcher().
m_nonunit_filter
std::vector<Addr> Prefetcher::m_nonunit_filter private
a non-unit stride filter array: helps reduce BW requirement of prefetching
Definition at line 180 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), clearNonunitEntry(), and print().
m_nonunit_hit
uint32_t* Prefetcher::m_nonunit_hit private
An array used to count the of times particular filter entries have been hit.
Definition at line 185 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), clearNonunitEntry(), Prefetcher(), print(), and ~Prefetcher().
m_nonunit_index
uint32_t Prefetcher::m_nonunit_index private
a round robin pointer into the unit filter group
Definition at line 187 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), and Prefetcher().
m_nonunit_stride
int* Prefetcher::m_nonunit_stride private
An array of strides (in # of cache lines) for the filter entries.
Definition at line 182 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), clearNonunitEntry(), Prefetcher(), print(), and ~Prefetcher().
m_num_nonunit_filters
uint32_t Prefetcher::m_num_nonunit_filters private
number of non-stride filters
Definition at line 158 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), Prefetcher(), and print().
m_num_startup_pfs
uint32_t Prefetcher::m_num_startup_pfs private
number of initial prefetches to startup a stream
Definition at line 154 of file Prefetcher.hh.
Referenced by getPrefetchEntry(), initializeStream(), and Prefetcher().
m_num_streams
uint32_t Prefetcher::m_num_streams private
number of prefetch streams available
Definition at line 147 of file Prefetcher.hh.
Referenced by getLRUindex(), getPrefetchEntry(), Prefetcher(), and print().
m_num_unit_filters
uint32_t Prefetcher::m_num_unit_filters private
number of stride filters
Definition at line 156 of file Prefetcher.hh.
Referenced by accessUnitFilter(), Prefetcher(), and print().
m_page_shift
const Addr Prefetcher::m_page_shift private
Definition at line 194 of file Prefetcher.hh.
Referenced by pageAddress().
m_prefetch_cross_pages
bool Prefetcher::m_prefetch_cross_pages private
Used for allowing prefetches across pages.
Definition at line 190 of file Prefetcher.hh.
Referenced by initializeStream(), and issueNextPrefetch().
m_train_misses
uint32_t Prefetcher::m_train_misses private
number of misses I must see before allocating a stream
Definition at line 152 of file Prefetcher.hh.
Referenced by accessNonunitFilter(), and accessUnitFilter().
m_unit_filter
std::vector<Addr> Prefetcher::m_unit_filter private
a unit stride filter array: helps reduce BW requirement of prefetching
Definition at line 162 of file Prefetcher.hh.
Referenced by observeMiss(), and print().
m_unit_filter_hit
uint32_t* Prefetcher::m_unit_filter_hit private
An array used to count the of times particular filter entries have been hit.
Definition at line 167 of file Prefetcher.hh.
Referenced by observeMiss(), Prefetcher(), and ~Prefetcher().
m_unit_filter_index
uint32_t Prefetcher::m_unit_filter_index private
a round robin pointer into the unit filter group
Definition at line 164 of file Prefetcher.hh.
Referenced by observeMiss(), and Prefetcher().
numAllocatedStreams
Stats::Scalar Prefetcher::numAllocatedStreams private
Count of prefetch streams allocated.
Definition at line 199 of file Prefetcher.hh.
Referenced by initializeStream(), and regStats().
numDroppedPrefetches
Stats::Scalar Prefetcher::numDroppedPrefetches private
Count of prefetches dropped.
Definition at line 205 of file Prefetcher.hh.
Referenced by regStats().
numHits
Stats::Scalar Prefetcher::numHits private
Count of successful prefetches.
Definition at line 207 of file Prefetcher.hh.
Referenced by observePfHit(), and regStats().
numMissedPrefetchedBlocks
Stats::Scalar Prefetcher::numMissedPrefetchedBlocks private
Count of misses incurred for blocks that were prefetched.
Definition at line 213 of file Prefetcher.hh.
Referenced by observeMiss(), and regStats().
numMissObserved
Stats::Scalar Prefetcher::numMissObserved private
Count of accesses to the prefetcher.
Definition at line 197 of file Prefetcher.hh.
Referenced by observeMiss(), and regStats().
numPagesCrossed
Stats::Scalar Prefetcher::numPagesCrossed private
Count of pages crossed.
Definition at line 211 of file Prefetcher.hh.
Referenced by initializeStream(), issueNextPrefetch(), and regStats().
numPartialHits
Stats::Scalar Prefetcher::numPartialHits private
Count of partial successful prefetches.
Definition at line 209 of file Prefetcher.hh.
Referenced by observeMiss(), observePfMiss(), and regStats().
numPrefetchAccepted
Stats::Scalar Prefetcher::numPrefetchAccepted private
Count of prefetch requests accepted.
Definition at line 203 of file Prefetcher.hh.
Referenced by regStats().
numPrefetchRequested
Stats::Scalar Prefetcher::numPrefetchRequested private
Count of prefetch requests made.
Definition at line 201 of file Prefetcher.hh.
Referenced by initializeStream(), and regStats().
The documentation for this class was generated from the following files:
mem/ruby/structures/Prefetcher.hh
mem/ruby/structures/Prefetcher.cc