gem5: ArmISA::TLBIIPA Class Reference
ArmISA::TLBIIPA Class Reference
TLB Invalidate by Intermediate Physical Address.
#include <tlbi_op.hh>
Public Member Functions
TLBIIPA (ExceptionLevel _targetEL, bool _secure, Addr _addr)
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
Addr addr
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
TLB Invalidate by Intermediate Physical Address.
Definition at line 247 of file tlbi_op.hh.
Constructor & Destructor Documentation
TLBIIPA()
ArmISA::TLBIIPA::TLBIIPA (ExceptionLevel _targetEL, bool _secure, Addr _addr) inline
Definition at line 250 of file tlbi_op.hh.
References ArmISA::TLBIOp::operator()().
Member Function Documentation
operator()()
void ArmISA::TLBIIPA::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 157 of file tlbi_op.cc.
References addr, ArmISA::TLB::flushIpaVmid(), ThreadContext::getCheckerCpuPtr(), ArmISA::getDTBPtr(), ArmISA::getITBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
Member Data Documentation
addr
Addr ArmISA::TLBIIPA::addr protected
Definition at line 257 of file tlbi_op.hh.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc