gem5: MemFootprintProbe Class Reference
MemFootprintProbe Class Reference
Probe to track footprint of accessed memory Two granularity of footprint measurement i.e.
#include <mem_footprint.hh>
Public Types
typedef std::unordered_set< Addr > AddrSet
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MemFootprintProbe (MemFootprintProbeParams *p)
void regStats () override
Callback to set stat parameters.
void statReset ()
Public Member Functions inherited from BaseMemProbe
BaseMemProbe (BaseMemProbeParams *params)
void regProbeListeners () override
Register probe listeners for this object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void insertAddr (Addr addr, AddrSet *set, uint64_t limit)
void handleRequest (const ProbePoints::PacketInfo &pkt_info) override
Callback to analyse intercepted Packets.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const uint8_t cacheLineSizeLg2
Cache Line size for footprint measurement (log2)
const uint8_t pageSizeLg2
Page size for footprint measurement (log2)
const uint64_t totalCacheLinesInMem
const uint64_t totalPagesInMem
Stats::Scalar fpCacheLine
Footprint at cache line size granularity.
Stats::Scalar fpCacheLineTotal
Footprint at cache line size granularity, since simulation begin.
Stats::Scalar fpPage
Footprint at page granularity.
Stats::Scalar fpPageTotal
Footprint at page granularity, since simulation begin.
AddrSet cacheLines
AddrSet cacheLinesAll
AddrSet pages
AddrSet pagesAll
System * system
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Probe to track footprint of accessed memory Two granularity of footprint measurement i.e.
cache line and page
Definition at line 56 of file mem_footprint.hh.
Member Typedef Documentation
AddrSet
typedef std::unordered_set<Addr> MemFootprintProbe::AddrSet
Definition at line 59 of file mem_footprint.hh.
Constructor & Destructor Documentation
MemFootprintProbe()
MemFootprintProbe::MemFootprintProbe (MemFootprintProbeParams * p)
Definition at line 46 of file mem_footprint.cc.
References System::cacheLineSize(), fatal_if, isPowerOf2(), and system.
Referenced by statReset().
Member Function Documentation
handleRequest()
void MemFootprintProbe::handleRequest (const ProbePoints::PacketInfo & pkt_info) override protected virtual
Callback to analyse intercepted Packets.
Implements BaseMemProbe.
Definition at line 100 of file mem_footprint.cc.
References ProbePoints::PacketInfo::addr, cacheLines, cacheLinesAll, cacheLineSizeLg2, ProbePoints::PacketInfo::cmd, fpCacheLine, fpCacheLineTotal, fpPage, fpPageTotal, insertAddr(), System::isMemAddr(), MemCmd::isRequest(), pages, pagesAll, pageSizeLg2, system, totalCacheLinesInMem, and totalPagesInMem.
insertAddr()
void MemFootprintProbe::insertAddr (Addr addr, AddrSet * set, uint64_t limit) protected
Definition at line 93 of file mem_footprint.cc.
References X86ISA::limit.
Referenced by handleRequest().
regStats()
void MemFootprintProbe::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 65 of file mem_footprint.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), fpCacheLine, fpCacheLineTotal, fpPage, fpPageTotal, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nonan, Stats::nozero, Stats::registerResetCallback(), and Stats::Group::regStats().
statReset()
void MemFootprintProbe::statReset ()
Definition at line 122 of file mem_footprint.cc.
References cacheLines, MemFootprintProbe(), and pages.
Member Data Documentation
cacheLines
AddrSet MemFootprintProbe::cacheLines protected
Definition at line 87 of file mem_footprint.hh.
Referenced by handleRequest(), and statReset().
cacheLinesAll
AddrSet MemFootprintProbe::cacheLinesAll protected
Definition at line 89 of file mem_footprint.hh.
Referenced by handleRequest().
cacheLineSizeLg2
const uint8_t MemFootprintProbe::cacheLineSizeLg2 protected
Cache Line size for footprint measurement (log2)
Definition at line 68 of file mem_footprint.hh.
Referenced by handleRequest().
fpCacheLine
Stats::Scalar MemFootprintProbe::fpCacheLine protected
Footprint at cache line size granularity.
Definition at line 78 of file mem_footprint.hh.
Referenced by handleRequest(), and regStats().
fpCacheLineTotal
Stats::Scalar MemFootprintProbe::fpCacheLineTotal protected
Footprint at cache line size granularity, since simulation begin.
Definition at line 80 of file mem_footprint.hh.
Referenced by handleRequest(), and regStats().
fpPage
Stats::Scalar MemFootprintProbe::fpPage protected
Footprint at page granularity.
Definition at line 82 of file mem_footprint.hh.
Referenced by handleRequest(), and regStats().
fpPageTotal
Stats::Scalar MemFootprintProbe::fpPageTotal protected
Footprint at page granularity, since simulation begin.
Definition at line 84 of file mem_footprint.hh.
Referenced by handleRequest(), and regStats().
pages
AddrSet MemFootprintProbe::pages protected
Definition at line 91 of file mem_footprint.hh.
Referenced by handleRequest(), and statReset().
pagesAll
AddrSet MemFootprintProbe::pagesAll protected
Definition at line 93 of file mem_footprint.hh.
Referenced by handleRequest().
pageSizeLg2
const uint8_t MemFootprintProbe::pageSizeLg2 protected
Page size for footprint measurement (log2)
Definition at line 70 of file mem_footprint.hh.
Referenced by handleRequest().
system
System* MemFootprintProbe::system protected
Definition at line 94 of file mem_footprint.hh.
Referenced by handleRequest(), and MemFootprintProbe().
totalCacheLinesInMem
const uint64_t MemFootprintProbe::totalCacheLinesInMem protected
Definition at line 71 of file mem_footprint.hh.
Referenced by handleRequest().
totalPagesInMem
const uint64_t MemFootprintProbe::totalPagesInMem protected
Definition at line 72 of file mem_footprint.hh.
Referenced by handleRequest().
The documentation for this class was generated from the following files:
mem/probes/mem_footprint.hh
mem/probes/mem_footprint.cc