gem5: sc_dt::sc_proxy< X > Class Template Reference
sc_dt::sc_proxy< X > Class Template Reference
#include <sc_proxy.hh>
Public Types
typedef sc_proxy_traits< X >::traits_type traits_type
typedef traits_type::bit_type bit_type
typedef traits_type::value_type value_type
Public Member Functions
virtual ~sc_proxy ()
X & back_cast ()
const X & back_cast () const
template<class Y >
X & assign_ (const sc_proxy< Y > &a)
X & assign_ (const char *a)
X & assign_ (const bool *a)
X & assign_ (const sc_logic *a)
X & assign_ (const sc_unsigned &a)
X & assign_ (const sc_signed &a)
X & assign_ (const sc_uint_base &a)
X & assign_ (const sc_int_base &a)
X & assign_ (unsigned int a)
X & assign_ (int a)
X & assign_ (unsigned long a)
X & assign_ (long a)
X & assign_ (uint64 a)
X & assign_ (int64 a)
X & b_not ()
const sc_lv_base operator~ () const
X & operator&= (const char *b)
X & operator&= (const bool *b)
X & operator&= (const sc_logic *b)
X & operator&= (const sc_unsigned &b)
X & operator&= (const sc_signed &b)
X & operator&= (const sc_uint_base &b)
X & operator&= (const sc_int_base &b)
X & operator&= (unsigned long b)
X & operator&= (long b)
X & operator&= (unsigned int b)
X & operator&= (int b)
X & operator&= (uint64 b)
X & operator&= (int64 b)
const sc_lv_base operator& (const char *b) const
const sc_lv_base operator& (const bool *b) const
const sc_lv_base operator& (const sc_logic *b) const
const sc_lv_base operator& (const sc_unsigned &b) const
const sc_lv_base operator& (const sc_signed &b) const
const sc_lv_base operator& (const sc_uint_base &b) const
const sc_lv_base operator& (const sc_int_base &b) const
const sc_lv_base operator& (unsigned long b) const
const sc_lv_base operator& (long b) const
const sc_lv_base operator& (unsigned int b) const
const sc_lv_base operator& (int b) const
const sc_lv_base operator& (uint64 b) const
const sc_lv_base operator& (int64 b) const
X & operator|= (const char *b)
X & operator|= (const bool *b)
X & operator|= (const sc_logic *b)
X & operator|= (const sc_unsigned &b)
X & operator|= (const sc_signed &b)
X & operator|= (const sc_uint_base &b)
X & operator|= (const sc_int_base &b)
X & operator|= (unsigned long b)
X & operator|= (long b)
X & operator|= (unsigned int b)
X & operator|= (int b)
X & operator|= (uint64 b)
X & operator|= (int64 b)
const sc_lv_base operator| (const char *b) const
const sc_lv_base operator| (const bool *b) const
const sc_lv_base operator| (const sc_logic *b) const
const sc_lv_base operator| (const sc_unsigned &b) const
const sc_lv_base operator| (const sc_signed &b) const
const sc_lv_base operator| (const sc_uint_base &b) const
const sc_lv_base operator| (const sc_int_base &b) const
const sc_lv_base operator| (unsigned long b) const
const sc_lv_base operator| (long b) const
const sc_lv_base operator| (unsigned int b) const
const sc_lv_base operator| (int b) const
const sc_lv_base operator| (uint64 b) const
const sc_lv_base operator| (int64 b) const
X & operator^= (const char *b)
X & operator^= (const bool *b)
X & operator^= (const sc_logic *b)
X & operator^= (const sc_unsigned &b)
X & operator^= (const sc_signed &b)
X & operator^= (const sc_uint_base &b)
X & operator^= (const sc_int_base &b)
X & operator^= (unsigned long b)
X & operator^= (long b)
X & operator^= (unsigned int b)
X & operator^= (int b)
X & operator^= (uint64 b)
X & operator^= (int64 b)
const sc_lv_base operator^ (const char *b) const
const sc_lv_base operator^ (const bool *b) const
const sc_lv_base operator^ (const sc_logic *b) const
const sc_lv_base operator^ (const sc_unsigned &b) const
const sc_lv_base operator^ (const sc_signed &b) const
const sc_lv_base operator^ (const sc_uint_base &b) const
const sc_lv_base operator^ (const sc_int_base &b) const
const sc_lv_base operator^ (unsigned long b) const
const sc_lv_base operator^ (long b) const
const sc_lv_base operator^ (unsigned int b) const
const sc_lv_base operator^ (int b) const
const sc_lv_base operator^ (uint64 b) const
const sc_lv_base operator^ (int64 b) const
X & operator<<= (int n)
const sc_lv_base operator<< (int n) const
X & operator>>= (int n)
const sc_lv_base operator>> (int n) const
X & lrotate (int n)
X & rrotate (int n)
X & reverse ()
sc_bitref< X > operator[] (int i)
sc_bitref_r< X > operator[] (int i) const
sc_bitref< X > bit (int i)
sc_bitref_r< X > bit (int i) const
sc_subref< X > operator() (int hi, int lo)
sc_subref_r< X > operator() (int hi, int lo) const
sc_subref< X > range (int hi, int lo)
sc_subref_r< X > range (int hi, int lo) const
value_type and_reduce () const
value_type nand_reduce () const
value_type or_reduce () const
value_type nor_reduce () const
value_type xor_reduce () const
value_type xnor_reduce () const
bool operator== (const char *b) const
bool operator== (const bool *b) const
bool operator== (const sc_logic *b) const
bool operator== (const sc_unsigned &b) const
bool operator== (const sc_signed &b) const
bool operator== (const sc_uint_base &b) const
bool operator== (const sc_int_base &b) const
bool operator== (unsigned long b) const
bool operator== (long b) const
bool operator== (unsigned int b) const
bool operator== (int b) const
bool operator== (uint64 b) const
bool operator== (int64 b) const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
int64 to_int64 () const
uint64 to_uint64 () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Protected Member Functions
void check_bounds (int n) const
void check_wbounds (int n) const
sc_digit to_anything_unsigned () const
int64 to_anything_signed () const
Detailed Description
template<class X>
class sc_dt::sc_proxy< X >
Definition at line 80 of file sc_proxy.hh.
Member Typedef Documentation
bit_type
template<class X> typedef traits_type::bit_type sc_dt::sc_proxy< X >::bit_type
Definition at line 200 of file sc_proxy.hh.
traits_type
template<class X> typedef sc_proxy_traits<X>::traits_type sc_dt::sc_proxy< X >::traits_type
Definition at line 199 of file sc_proxy.hh.
value_type
template<class X> typedef traits_type::value_type sc_dt::sc_proxy< X >::value_type
Definition at line 201 of file sc_proxy.hh.
Constructor & Destructor Documentation
~sc_proxy()
template<class X> virtual sc_dt::sc_proxy< X >::~sc_proxy () inline virtual
Definition at line 204 of file sc_proxy.hh.
Member Function Documentation
and_reduce()
template<class X > sc_proxy< X >::value_type sc_dt::sc_proxy< X >::and_reduce () const inline
Definition at line 1126 of file sc_proxy.hh.
Referenced by sc_dt::and_reduce().
assign_() [1/14]
template<class X> template<class Y > X& sc_dt::sc_proxy< X >::assign_ (const sc_proxy< Y > & a) inline
Definition at line 214 of file sc_proxy.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::assign_().
assign_() [2/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (const char * a) inline
Definition at line 749 of file sc_proxy.hh.
assign_() [3/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (const bool * a) inline
Definition at line 772 of file sc_proxy.hh.
assign_() [4/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (const sc_logic * a) inline
Definition at line 785 of file sc_proxy.hh.
assign_() [5/14]
template<class X> X& sc_dt::sc_proxy< X >::assign_ (const sc_unsigned & a) inline
Definition at line 225 of file sc_proxy.hh.
assign_() [6/14]
template<class X> X& sc_dt::sc_proxy< X >::assign_ (const sc_signed & a) inline
Definition at line 232 of file sc_proxy.hh.
assign_() [7/14]
template<class X> X& sc_dt::sc_proxy< X >::assign_ (const sc_uint_base & a) inline
Definition at line 238 of file sc_proxy.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::assign_().
assign_() [8/14]
template<class X> X& sc_dt::sc_proxy< X >::assign_ (const sc_int_base & a) inline
Definition at line 239 of file sc_proxy.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::assign_().
assign_() [9/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (unsigned int a) inline
Definition at line 798 of file sc_proxy.hh.
assign_() [10/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (int a) inline
Definition at line 810 of file sc_proxy.hh.
assign_() [11/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (unsigned long a) inline
Definition at line 858 of file sc_proxy.hh.
assign_() [12/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (long a) inline
Definition at line 870 of file sc_proxy.hh.
assign_() [13/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (uint64 a) inline
Definition at line 884 of file sc_proxy.hh.
assign_() [14/14]
template<class X > X & sc_dt::sc_proxy< X >::assign_ (int64 a) inline
Definition at line 900 of file sc_proxy.hh.
b_not()
template<class X > X & sc_dt::sc_proxy< X >::b_not () inline
Definition at line 920 of file sc_proxy.hh.
Referenced by sc_dt::sc_proxy< sc_subref_r< X > >::operator~().
back_cast() [1/2]
template<class X> X& sc_dt::sc_proxy< X >::back_cast () inline
Definition at line 207 of file sc_proxy.hh.
Referenced by sc_dt::assign_p_(), sc_dt::assign_v_(), sc_dt::b_and_assign_(), sc_dt::b_or_assign_(), sc_dt::b_xor_assign_(), sc_dt::concat(), sc_dt::lrotate(), sc_dt::operator&(), sc_dt::operator&=(), sc_dt::operator,(), sc_dt::operator==(), sc_dt::operator^(), sc_dt::operator^=(), sc_dt::operator|(), sc_dt::operator|=(), sc_dt::reverse(), sc_dt::rrotate(), sc_dt::sc_bv_base::sc_bv_base(), and sc_dt::sc_lv_base::sc_lv_base().
back_cast() [2/2]
template<class X> const X& sc_dt::sc_proxy< X >::back_cast () const inline
Definition at line 209 of file sc_proxy.hh.
bit() [1/2]
template<class X> sc_bitref<X> sc_dt::sc_proxy< X >::bit (int i) inline
Definition at line 365 of file sc_proxy.hh.
bit() [2/2]
template<class X> sc_bitref_r<X> sc_dt::sc_proxy< X >::bit (int i) const inline
Definition at line 366 of file sc_proxy.hh.
check_bounds()
template<class X > void sc_dt::sc_proxy< X >::check_bounds (int n) const inline protected
Definition at line 1238 of file sc_proxy.hh.
check_wbounds()
template<class X > void sc_dt::sc_proxy< X >::check_wbounds (int n) const inline protected
Definition at line 1248 of file sc_proxy.hh.
lrotate()
template<class X > X & sc_dt::sc_proxy< X >::lrotate (int n) inline
Definition at line 617 of file sc_lv_base.hh.
nand_reduce()
template<class X> value_type sc_dt::sc_proxy< X >::nand_reduce () const inline
Definition at line 393 of file sc_proxy.hh.
Referenced by sc_dt::nand_reduce().
nor_reduce()
template<class X> value_type sc_dt::sc_proxy< X >::nor_reduce () const inline
Definition at line 398 of file sc_proxy.hh.
Referenced by sc_dt::nor_reduce().
operator&() [1/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const char * b) const
operator&() [2/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const bool * b) const
operator&() [3/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const sc_logic * b) const
operator&() [4/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const sc_unsigned & b) const
operator&() [5/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const sc_signed & b) const
operator&() [6/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const sc_uint_base & b) const
operator&() [7/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (const sc_int_base & b) const
operator&() [8/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (unsigned long b) const
operator&() [9/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (long b) const
operator&() [10/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (unsigned int b) const
operator&() [11/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (int b) const
operator&() [12/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (uint64 b) const
operator&() [13/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator & (int64 b) const
operator&=() [1/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const char * b)
operator&=() [2/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const bool * b)
operator&=() [3/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const sc_logic * b)
operator&=() [4/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const sc_unsigned & b)
operator&=() [5/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const sc_signed & b)
operator&=() [6/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const sc_uint_base & b) inline
Definition at line 260 of file sc_proxy.hh.
operator&=() [7/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (const sc_int_base & b) inline
Definition at line 261 of file sc_proxy.hh.
operator&=() [8/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (unsigned long b)
operator&=() [9/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (long b)
operator&=() [10/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (unsigned int b) inline
Definition at line 264 of file sc_proxy.hh.
operator&=() [11/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (int b) inline
Definition at line 265 of file sc_proxy.hh.
operator&=() [12/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (uint64 b)
operator&=() [13/13]
template<class X> X& sc_dt::sc_proxy< X >::operator &= (int64 b)
operator()() [1/2]
template<class X> sc_subref<X> sc_dt::sc_proxy< X >::operator() (int hi, int lo) inline
Definition at line 370 of file sc_proxy.hh.
operator()() [2/2]
template<class X> sc_subref_r<X> sc_dt::sc_proxy< X >::operator() (int hi, int lo) const inline
Definition at line 375 of file sc_proxy.hh.
operator<<()
template<class X > const sc_lv_base sc_dt::sc_proxy< X >::operator<< (int n) const inline
Definition at line 598 of file sc_lv_base.hh.
operator<<=()
template<class X > X & sc_dt::sc_proxy< X >::operator<<= (int n) inline
Definition at line 999 of file sc_proxy.hh.
operator==() [1/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const char * b) const
operator==() [2/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const bool * b) const
operator==() [3/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const sc_logic * b) const
operator==() [4/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const sc_unsigned & b) const
operator==() [5/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const sc_signed & b) const
operator==() [6/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const sc_uint_base & b) const
operator==() [7/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (const sc_int_base & b) const
operator==() [8/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (unsigned long b) const
operator==() [9/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (long b) const
operator==() [10/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (unsigned int b) const
operator==() [11/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (int b) const
operator==() [12/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (uint64 b) const
operator==() [13/13]
template<class X> bool sc_dt::sc_proxy< X >::operator== (int64 b) const
operator>>()
template<class X > const sc_lv_base sc_dt::sc_proxy< X >::operator>> (int n) const inline
Definition at line 608 of file sc_lv_base.hh.
operator>>=()
template<class X > X & sc_dt::sc_proxy< X >::operator>>= (int n) inline
Definition at line 1049 of file sc_proxy.hh.
operator[]() [1/2]
template<class X> sc_bitref<X> sc_dt::sc_proxy< X >::operator[] (int i) inline
Definition at line 359 of file sc_proxy.hh.
operator[]() [2/2]
template<class X> sc_bitref_r<X> sc_dt::sc_proxy< X >::operator[] (int i) const inline
Definition at line 361 of file sc_proxy.hh.
operator^() [1/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const char * b) const
operator^() [2/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const bool * b) const
operator^() [3/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const sc_logic * b) const
operator^() [4/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const sc_unsigned & b) const
operator^() [5/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const sc_signed & b) const
operator^() [6/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const sc_uint_base & b) const
operator^() [7/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (const sc_int_base & b) const
operator^() [8/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (unsigned long b) const
operator^() [9/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (long b) const
operator^() [10/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (unsigned int b) const
operator^() [11/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (int b) const
operator^() [12/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (uint64 b) const
operator^() [13/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator^ (int64 b) const
operator^=() [1/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const char * b)
operator^=() [2/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const bool * b)
operator^=() [3/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const sc_logic * b)
operator^=() [4/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const sc_unsigned & b)
operator^=() [5/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const sc_signed & b)
operator^=() [6/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const sc_uint_base & b) inline
Definition at line 318 of file sc_proxy.hh.
operator^=() [7/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (const sc_int_base & b) inline
Definition at line 319 of file sc_proxy.hh.
operator^=() [8/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (unsigned long b)
operator^=() [9/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (long b)
operator^=() [10/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (unsigned int b) inline
Definition at line 322 of file sc_proxy.hh.
operator^=() [11/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (int b) inline
Definition at line 323 of file sc_proxy.hh.
operator^=() [12/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (uint64 b)
operator^=() [13/13]
template<class X> X& sc_dt::sc_proxy< X >::operator^= (int64 b)
operator|() [1/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const char * b) const
operator|() [2/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const bool * b) const
operator|() [3/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const sc_logic * b) const
operator|() [4/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const sc_unsigned & b) const
operator|() [5/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const sc_signed & b) const
operator|() [6/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const sc_uint_base & b) const
operator|() [7/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (const sc_int_base & b) const
operator|() [8/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (unsigned long b) const
operator|() [9/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (long b) const
operator|() [10/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (unsigned int b) const
operator|() [11/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (int b) const
operator|() [12/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (uint64 b) const
operator|() [13/13]
template<class X> const sc_lv_base sc_dt::sc_proxy< X >::operator| (int64 b) const
operator|=() [1/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const char * b)
operator|=() [2/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const bool * b)
operator|=() [3/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const sc_logic * b)
operator|=() [4/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const sc_unsigned & b)
operator|=() [5/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const sc_signed & b)
operator|=() [6/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const sc_uint_base & b) inline
Definition at line 289 of file sc_proxy.hh.
operator|=() [7/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (const sc_int_base & b) inline
Definition at line 290 of file sc_proxy.hh.
operator|=() [8/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (unsigned long b)
operator|=() [9/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (long b)
operator|=() [10/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (unsigned int b) inline
Definition at line 293 of file sc_proxy.hh.
operator|=() [11/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (int b) inline
Definition at line 294 of file sc_proxy.hh.
operator|=() [12/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (uint64 b)
operator|=() [13/13]
template<class X> X& sc_dt::sc_proxy< X >::operator|= (int64 b)
operator~()
template<class X > const sc_lv_base sc_dt::sc_proxy< X >::operator~ () const inline
Definition at line 316 of file sc_lv_base.hh.
or_reduce()
template<class X > sc_proxy< X >::value_type sc_dt::sc_proxy< X >::or_reduce () const inline
Definition at line 1139 of file sc_proxy.hh.
Referenced by sc_dt::or_reduce().
print()
template<class X> void sc_dt::sc_proxy< X >::print (::std::ostream & os = ::std::cout) const inline
Definition at line 447 of file sc_proxy.hh.
Referenced by sc_dt::operator<<().
range() [1/2]
template<class X> sc_subref<X> sc_dt::sc_proxy< X >::range (int hi, int lo) inline
Definition at line 380 of file sc_proxy.hh.
range() [2/2]
template<class X> sc_subref_r<X> sc_dt::sc_proxy< X >::range (int hi, int lo) const inline
Definition at line 385 of file sc_proxy.hh.
reverse()
template<class X > X & sc_dt::sc_proxy< X >::reverse () inline
Definition at line 1107 of file sc_proxy.hh.
rrotate()
template<class X > X & sc_dt::sc_proxy< X >::rrotate (int n) inline
Definition at line 650 of file sc_lv_base.hh.
scan()
template<class X > void sc_dt::sc_proxy< X >::scan (::std::istream & is = ::std::cin) inline
Definition at line 1229 of file sc_proxy.hh.
Referenced by sc_dt::operator>>().
to_anything_signed()
template<class X > int64 sc_dt::sc_proxy< X >::to_anything_signed () const inline protected
Definition at line 1302 of file sc_proxy.hh.
to_anything_unsigned()
template<class X > sc_digit sc_dt::sc_proxy< X >::to_anything_unsigned () const inline protected
Definition at line 1258 of file sc_proxy.hh.
to_int()
template<class X> int sc_dt::sc_proxy< X >::to_int () const inline
Definition at line 429 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_int(), and sc_dt::sc_fxnum_fast_subref::to_int().
to_int64()
template<class X> int64 sc_dt::sc_proxy< X >::to_int64 () const inline
Definition at line 427 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_int64(), and sc_dt::sc_fxnum_fast_subref::to_int64().
to_long()
template<class X> long sc_dt::sc_proxy< X >::to_long () const inline
Definition at line 437 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_long(), and sc_dt::sc_fxnum_fast_subref::to_long().
to_string() [1/3]
template<class X > const std::string sc_dt::sc_proxy< X >::to_string () const inline
Definition at line 1201 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_string(), and sc_dt::sc_fxnum_fast_subref::to_string().
to_string() [2/3]
template<class X > const std::string sc_dt::sc_proxy< X >::to_string (sc_numrep numrep) const inline
Definition at line 1214 of file sc_proxy.hh.
to_string() [3/3]
template<class X > const std::string sc_dt::sc_proxy< X >::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 1221 of file sc_proxy.hh.
to_uint()
template<class X> unsigned int sc_dt::sc_proxy< X >::to_uint () const inline
Definition at line 432 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_uint(), and sc_dt::sc_fxnum_fast_subref::to_uint().
to_uint64()
template<class X > uint64 sc_dt::sc_proxy< X >::to_uint64 () const inline
Definition at line 1276 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_uint64(), and sc_dt::sc_fxnum_fast_subref::to_uint64().
to_ulong()
template<class X> unsigned long sc_dt::sc_proxy< X >::to_ulong () const inline
Definition at line 440 of file sc_proxy.hh.
Referenced by sc_dt::sc_fxnum_subref::to_ulong(), and sc_dt::sc_fxnum_fast_subref::to_ulong().
xnor_reduce()
template<class X> value_type sc_dt::sc_proxy< X >::xnor_reduce () const inline
Definition at line 401 of file sc_proxy.hh.
Referenced by sc_dt::xnor_reduce().
xor_reduce()
template<class X > sc_proxy< X >::value_type sc_dt::sc_proxy< X >::xor_reduce () const inline
Definition at line 1152 of file sc_proxy.hh.
Referenced by sc_dt::xor_reduce().
The documentation for this class was generated from the following files:
systemc/ext/dt/bit/sc_proxy.hh
systemc/ext/dt/bit/sc_lv_base.hh