gem5: RubyPort Class Reference
RubyPort Class Reference abstract
#include <RubyPort.hh>
Classes
class MemMasterPort
class MemSlavePort
class PioMasterPort
class PioSlavePort
struct SenderState
Public Types
typedef RubyPortParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
RubyPort (const Params *p)
virtual ~RubyPort ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
virtual RequestStatus makeRequest (PacketPtr pkt)=0
virtual int outstandingCount () const =0
virtual bool isDeadlockEventScheduled () const =0
virtual void descheduleDeadlockEvent ()=0
void setController (AbstractController *_cntrl)
uint32_t getId ()
DrainState drain () override
Notify an object that it needs to drain its state.
bool isCPUSequencer ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void trySendRetries ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (Addr address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
RubySystem * m_ruby_system
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
std::vector< MemSlavePort * > slave_ports
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Types
typedef std::vector< MemSlavePort * >::iterator CpuPortIter
Vector of M5 Ports attached to this Ruby port.
Private Member Functions
bool onRetryList (MemSlavePort *port)
void addToRetryList (MemSlavePort *port)
Private Attributes
PioMasterPort pioMasterPort
PioSlavePort pioSlavePort
MemMasterPort memMasterPort
MemSlavePort memSlavePort
unsigned int gotAddrRanges
std::vector< PioMasterPort * > master_ports
std::vector< MemSlavePort * > retryList
bool m_isCPUSequencer
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 58 of file RubyPort.hh.
Member Typedef Documentation
CpuPortIter
typedef std::vector<MemSlavePort *>::iterator RubyPort::CpuPortIter private
Vector of M5 Ports attached to this Ruby port.
Definition at line 213 of file RubyPort.hh.
Params
typedef RubyPortParams RubyPort::Params
Definition at line 145 of file RubyPort.hh.
Constructor & Destructor Documentation
RubyPort()
RubyPort::RubyPort (const Params * p)
Definition at line 54 of file RubyPort.cc.
References csprintf(), ArmISA::i, m_version, master_ports, SimObject::name(), and slave_ports.
~RubyPort()
virtual RubyPort::~RubyPort () inline virtual
Definition at line 147 of file RubyPort.hh.
References descheduleDeadlockEvent(), getPort(), init(), InvalidPortID, isDeadlockEventScheduled(), makeRequest(), and outstandingCount().
Member Function Documentation
addToRetryList()
void RubyPort::addToRetryList (MemSlavePort * port) inline private
Definition at line 200 of file RubyPort.hh.
References onRetryList(), and retryList.
Referenced by RubyPort::MemSlavePort::addToRetryList(), and RubyPort::MemSlavePort::getAddrRanges().
descheduleDeadlockEvent()
virtual void RubyPort::descheduleDeadlockEvent () pure virtual
Implemented in GPUCoalescer, RubyPortProxy, Sequencer, and DMASequencer.
Referenced by drain(), and ~RubyPort().
drain()
DrainState RubyPort::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 480 of file RubyPort.cc.
References descheduleDeadlockEvent(), DPRINTF, Drained, Draining, isDeadlockEventScheduled(), and outstandingCount().
Referenced by getId().
getId()
uint32_t RubyPort::getId () inline
Definition at line 164 of file RubyPort.hh.
References drain(), and m_version.
getPort()
Port & RubyPort::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 91 of file RubyPort.cc.
References SimObject::getPort(), master_ports, memMasterPort, memSlavePort, panic, pioMasterPort, pioSlavePort, and slave_ports.
Referenced by ~RubyPort().
init()
void RubyPort::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in RubyPortProxy.
Definition at line 84 of file RubyPort.cc.
References AbstractController::getMandatoryQueue(), m_controller, and m_mandatory_q_ptr.
Referenced by DMASequencer::init(), and ~RubyPort().
isCPUSequencer()
bool RubyPort::isCPUSequencer () inline
Definition at line 167 of file RubyPort.hh.
References m_isCPUSequencer, RubyPort::MemMasterPort::recvTimingResp(), ruby_eviction_callback(), ruby_hit_callback(), testDrainComplete(), and trySendRetries().
isDeadlockEventScheduled()
virtual bool RubyPort::isDeadlockEventScheduled () const pure virtual
Implemented in GPUCoalescer, RubyPortProxy, Sequencer, and DMASequencer.
Referenced by drain(), and ~RubyPort().
makeRequest()
virtual RequestStatus RubyPort::makeRequest (PacketPtr pkt) pure virtual
Implemented in GPUCoalescer, Sequencer, RubyPortProxy, DMASequencer, and VIPERCoalescer.
Referenced by ~RubyPort().
onRetryList()
bool RubyPort::onRetryList (MemSlavePort * port) inline private
Definition at line 195 of file RubyPort.hh.
References retryList.
Referenced by RubyPort::MemSlavePort::addToRetryList(), and addToRetryList().
outstandingCount()
virtual int RubyPort::outstandingCount () const pure virtual
Implemented in GPUCoalescer, RubyPortProxy, Sequencer, and DMASequencer.
Referenced by drain(), testDrainComplete(), and ~RubyPort().
recvTimingResp()
bool RubyPort::recvTimingResp (PacketPtr pkt, PortID master_port_id) protected
Called by the PIO port when receiving a timing response.
Parameters
pkt Response packet
master_port_id Port id of the PIO port
Returns
Whether successfully sent
ruby_eviction_callback()
void RubyPort::ruby_eviction_callback (Addr address) protected
Definition at line 589 of file RubyPort.cc.
References DPRINTF, Request::funcMasterId, RubySystem::getBlockSizeBytes(), MemCmd::InvalidateReq, MipsISA::p, and slave_ports.
Referenced by Sequencer::evictionCallback(), GPUCoalescer::evictionCallback(), and isCPUSequencer().
ruby_hit_callback()
void RubyPort::ruby_hit_callback (PacketPtr pkt) protected
Definition at line 417 of file RubyPort.cc.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), System::isMemAddr(), Packet::isRequest(), Packet::popSenderState(), safe_cast(), system, and trySendRetries().
Referenced by Sequencer::hitCallback(), isCPUSequencer(), DMASequencer::issueNext(), and GPUCoalescer::kernelCallback().
setController()
void RubyPort::setController (AbstractController * _cntrl) inline
Definition at line 163 of file RubyPort.hh.
References m_controller.
testDrainComplete()
void RubyPort::testDrainComplete () protected
Definition at line 466 of file RubyPort.cc.
References DPRINTF, Draining, Drainable::drainState(), outstandingCount(), and Drainable::signalDrainDone().
Referenced by GPUCoalescer::completeHitCallback(), Sequencer::hitCallback(), and isCPUSequencer().
trySendRetries()
void RubyPort::trySendRetries () protected
Definition at line 440 of file RubyPort.cc.
References DPRINTF, ArmISA::i, SimObject::name(), and retryList.
Referenced by GPUCoalescer::completeHitCallback(), VIPERCoalescer::invCallback(), isCPUSequencer(), ruby_hit_callback(), and VIPERCoalescer::wbCallback().
Member Data Documentation
gotAddrRanges
unsigned int RubyPort::gotAddrRanges private
Definition at line 210 of file RubyPort.hh.
Referenced by RubyPort::PioMasterPort::recvRangeChange().
m_controller
AbstractController* RubyPort::m_controller protected
Definition at line 187 of file RubyPort.hh.
Referenced by GPUCoalescer::getRequestStatus(), init(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), Sequencer::makeRequest(), RubyPort::MemSlavePort::recvAtomic(), setController(), VIPERCoalescer::wbL1(), Sequencer::writeCallback(), and GPUCoalescer::writeCallback().
m_isCPUSequencer
bool RubyPort::m_isCPUSequencer private
Definition at line 222 of file RubyPort.hh.
Referenced by isCPUSequencer().
m_mandatory_q_ptr
MessageBuffer* RubyPort::m_mandatory_q_ptr protected
Definition at line 188 of file RubyPort.hh.
Referenced by GPUCoalescer::getRequestStatus(), init(), GPUCoalescer::insertRequest(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), DMASequencer::issueNext(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), VIPERCoalescer::wbL1(), Sequencer::writeCallback(), and GPUCoalescer::writeCallback().
m_ruby_system
RubySystem* RubyPort::m_ruby_system protected
Definition at line 185 of file RubyPort.hh.
Referenced by RubyPort::MemSlavePort::hitCallback(), Sequencer::hitCallback(), RubyPort::MemSlavePort::recvAtomic(), and RubyPort::PioMasterPort::recvTimingResp().
m_usingRubyTester
bool RubyPort::m_usingRubyTester protected
Definition at line 189 of file RubyPort.hh.
Referenced by GPUCoalescer::atomicCallback(), Sequencer::hitCallback(), and GPUCoalescer::hitCallback().
m_version
uint32_t RubyPort::m_version protected
Definition at line 186 of file RubyPort.hh.
Referenced by getId(), Sequencer::handleLlsc(), GPUCoalescer::handleLlsc(), Sequencer::invalidateSC(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), Sequencer::print(), GPUCoalescer::print(), Sequencer::recordMissLatency(), GPUCoalescer::recordMissLatency(), RubyPort(), Sequencer::wakeup(), and GPUCoalescer::wakeup().
master_ports
std::vector<PioMasterPort *> RubyPort::master_ports private
Definition at line 214 of file RubyPort.hh.
Referenced by RubyPort::PioSlavePort::getAddrRanges(), getPort(), RubyPort::PioSlavePort::recvAtomic(), RubyPort::PioSlavePort::recvTimingReq(), and RubyPort().
memMasterPort
MemMasterPort RubyPort::memMasterPort private
Definition at line 208 of file RubyPort.hh.
Referenced by getPort(), and RubyPort::MemSlavePort::recvAtomic().
memSlavePort
MemSlavePort RubyPort::memSlavePort private
Definition at line 209 of file RubyPort.hh.
Referenced by getPort().
pioMasterPort
PioMasterPort RubyPort::pioMasterPort private
Definition at line 206 of file RubyPort.hh.
Referenced by getPort().
pioSlavePort
PioSlavePort RubyPort::pioSlavePort private
Definition at line 207 of file RubyPort.hh.
Referenced by getPort(), RubyPort::PioMasterPort::recvRangeChange(), and RubyPort::PioMasterPort::recvTimingResp().
retryList
std::vector<MemSlavePort *> RubyPort::retryList private
Definition at line 220 of file RubyPort.hh.
Referenced by addToRetryList(), onRetryList(), and trySendRetries().
slave_ports
std::vector<MemSlavePort *> RubyPort::slave_ports protected
Definition at line 192 of file RubyPort.hh.
Referenced by getPort(), DMASequencer::init(), ruby_eviction_callback(), and RubyPort().
system
System* RubyPort::system protected
Definition at line 190 of file RubyPort.hh.
Referenced by RubyPort::MemSlavePort::isPhysMemAddress(), Sequencer::makeRequest(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::PioSlavePort::recvAtomic(), and ruby_hit_callback().
The documentation for this class was generated from the following files:
mem/ruby/system/RubyPort.hh
mem/ruby/system/RubyPort.cc