gem5: X86ISA::RemoteGDB::AMD64GdbRegCache Class Reference
X86ISA::RemoteGDB::AMD64GdbRegCache Class Reference
#include <remote_gdb.hh>
Classes
struct M5_ATTR_PACKED
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct X86ISA::RemoteGDB::AMD64GdbRegCache::M5_ATTR_PACKED r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 95 of file remote_gdb.hh.
Member Function Documentation
data()
char* X86ISA::RemoteGDB::AMD64GdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 131 of file remote_gdb.hh.
References X86ISA::RemoteGDB::X86GdbRegCache::r.
getRegs()
void RemoteGDB::AMD64GdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 108 of file remote_gdb.cc.
References DPRINTF, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R13, ArmISA::INTREG_R14, ArmISA::INTREG_R15, ArmISA::INTREG_R8, ArmISA::INTREG_R9, X86ISA::MISCREG_CS, X86ISA::MISCREG_DS, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SS, ThreadContext::pcState(), X86ISA::r, ThreadContext::readIntReg(), and ThreadContext::readMiscRegNoEffect().
name()
const std::string X86ISA::RemoteGDB::AMD64GdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 136 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::AMD64GdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 160 of file remote_gdb.cc.
References DPRINTF, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R13, ArmISA::INTREG_R14, ArmISA::INTREG_R15, ArmISA::INTREG_R8, ArmISA::INTREG_R9, X86ISA::MISCREG_CS, X86ISA::MISCREG_DS, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SS, ThreadContext::pcState(), X86ISA::r, ThreadContext::readMiscRegNoEffect(), ThreadContext::setIntReg(), ThreadContext::setMiscReg(), and warn.
size()
size_t X86ISA::RemoteGDB::AMD64GdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 132 of file remote_gdb.hh.
References X86ISA::RemoteGDB::X86GdbRegCache::getRegs(), X86ISA::RemoteGDB::X86GdbRegCache::r, and X86ISA::RemoteGDB::X86GdbRegCache::setRegs().
Member Data Documentation
r
struct X86ISA::RemoteGDB::AMD64GdbRegCache::M5_ATTR_PACKED X86ISA::RemoteGDB::AMD64GdbRegCache::r private
The documentation for this class was generated from the following files:
arch/x86/remote_gdb.hh
arch/x86/remote_gdb.cc