gem5: Stats::Hdf5 Class Reference
Stats::Hdf5 Class Reference
#include <hdf5.hh>
Public Member Functions
Hdf5 (const std::string &file, unsigned chunking, bool desc, bool formulas)
~Hdf5 ()
Hdf5 ()=delete
Hdf5 (const Hdf5 &other)=delete
void begin () override
void end () override
bool valid () const override
void beginGroup (const char *name) override
void endGroup () override
void visit (const ScalarInfo &info) override
void visit (const VectorInfo &info) override
void visit (const DistInfo &info) override
void visit (const VectorDistInfo &info) override
void visit (const Vector2dInfo &info) override
void visit (const FormulaInfo &info) override
void visit (const SparseHistInfo &info) override
Public Member Functions inherited from Stats::Output
virtual ~Output ()
Protected Member Functions
H5::DataSet appendVectorInfo (const VectorInfo &info)
Helper function to append vector stats and set their metadata.
H5::DataSet appendStat (const Info &info, int rank, hsize_t *dims, const double *data)
Helper function to append an n-dimensional double stat to the file.
void addMetaData (H5::DataSet &loc, const char *name, const std::vector< const char *> &values)
Helper function to add a string vector attribute to a stat.
void addMetaData (H5::DataSet &loc, const char *name, const std::vector< std::string > &values)
Helper function to add a string vector attribute to a stat.
void addMetaData (H5::DataSet &loc, const char *name, const std::string &value)
Helper function to add a string attribute to a stat.
void addMetaData (H5::DataSet &loc, const char *name, double value)
Helper function to add a double attribute to a stat.
Protected Attributes
const std::string fname
const hsize_t timeChunk
const bool enableDescriptions
const bool enableFormula
std::stack< H5::Group > path
unsigned dumpCount
H5::H5File h5File
Detailed Description
Definition at line 56 of file hdf5.hh.
Constructor & Destructor Documentation
Hdf5() [1/3]
Stats::Hdf5::Hdf5 (const std::string & file, unsigned chunking, bool desc, bool formulas)
Definition at line 61 of file hdf5.cc.
~Hdf5()
Stats::Hdf5::~Hdf5 ()
Definition at line 73 of file hdf5.cc.
Hdf5() [2/3]
Stats::Hdf5::Hdf5 () delete
Referenced by Stats::initHDF5().
Hdf5() [3/3]
Stats::Hdf5::Hdf5 (const Hdf5 & other) delete
Member Function Documentation
addMetaData() [1/4]
void Stats::Hdf5::addMetaData (H5::DataSet & loc, const char * name, const std::vector< const char *> & values) protected
Helper function to add a string vector attribute to a stat.
Parameters
loc Parent location in the file.
name Attribute name.
values Attribute value.
Definition at line 274 of file hdf5.cc.
References type.
Referenced by addMetaData(), appendStat(), appendVectorInfo(), and visit().
addMetaData() [2/4]
void Stats::Hdf5::addMetaData (H5::DataSet & loc, const char * name, const std::vector< std::string > & values) protected
Helper function to add a string vector attribute to a stat.
Parameters
loc Parent location in the file.
name Attribute name.
values Attribute value.
Definition at line 285 of file hdf5.cc.
References addMetaData(), and ArmISA::i.
addMetaData() [3/4]
void Stats::Hdf5::addMetaData (H5::DataSet & loc, const char * name, const std::string & value) protected
Helper function to add a string attribute to a stat.
Parameters
loc Parent location in the file.
name Attribute name.
value Attribute value.
Definition at line 296 of file hdf5.cc.
References type.
addMetaData() [4/4]
void Stats::Hdf5::addMetaData (H5::DataSet & loc, const char * name, double value) protected
Helper function to add a double attribute to a stat.
Parameters
loc Parent location in the file.
name Attribute name.
value Attribute value.
Definition at line 307 of file hdf5.cc.
appendStat()
H5::DataSet Stats::Hdf5::appendStat (const Info & info, int rank, hsize_t * dims, const double * data) protected
Helper function to append an n-dimensional double stat to the file.
This helper function assumes that all stats include a time component. I.e., a Stat::Scalar is a 1-dimensional stat.
Parameters
info Stat info structure.
rank Stat dimensionality (including time).
dims Size of each of the dimensions.
Definition at line 219 of file hdf5.cc.
References addMetaData(), Stats::Info::desc, dumpCount, enableDescriptions, Stats::Info::name, path, and timeChunk.
Referenced by appendVectorInfo(), and visit().
appendVectorInfo()
H5::DataSet Stats::Hdf5::appendVectorInfo (const VectorInfo & info) protected
Helper function to append vector stats and set their metadata.
Definition at line 198 of file hdf5.cc.
References addMetaData(), appendStat(), dumpCount, emptyStrings(), Stats::VectorInfo::result(), Stats::VectorInfo::subdescs, and Stats::VectorInfo::subnames.
Referenced by visit().
begin()
void Stats::Hdf5::begin () override virtual
Implements Stats::Output.
Definition at line 79 of file hdf5.cc.
References dumpCount, fname, h5File, and path.
beginGroup()
void Stats::Hdf5::beginGroup (const char * name) override virtual
Implements Stats::Output.
Definition at line 103 of file hdf5.cc.
References X86ISA::base, ArmISA::e, and path.
end()
void Stats::Hdf5::end () override virtual
Implements Stats::Output.
Definition at line 88 of file hdf5.cc.
References dumpCount, and valid().
endGroup()
void Stats::Hdf5::endGroup () override virtual
Implements Stats::Output.
Definition at line 122 of file hdf5.cc.
References path.
valid()
bool Stats::Hdf5::valid () const override virtual
Implements Stats::Output.
Definition at line 96 of file hdf5.cc.
Referenced by end().
visit() [1/7]
void Stats::Hdf5::visit (const ScalarInfo & info) override virtual
Implements Stats::Output.
Definition at line 129 of file hdf5.cc.
References appendStat(), data, and Stats::ScalarInfo::result().
visit() [2/7]
void Stats::Hdf5::visit (const VectorInfo & info) override virtual
Implements Stats::Output.
Definition at line 141 of file hdf5.cc.
References appendVectorInfo().
visit() [3/7]
void Stats::Hdf5::visit (const DistInfo & info) override virtual
Implements Stats::Output.
Definition at line 147 of file hdf5.cc.
References warn_once.
visit() [4/7]
void Stats::Hdf5::visit (const VectorDistInfo & info) override virtual
Implements Stats::Output.
Definition at line 153 of file hdf5.cc.
References warn_once.
visit() [5/7]
void Stats::Hdf5::visit (const Vector2dInfo & info) override virtual
Implements Stats::Output.
Definition at line 159 of file hdf5.cc.
References addMetaData(), appendStat(), Stats::Vector2dInfo::cvec, dumpCount, emptyStrings(), Stats::Vector2dInfo::subdescs, Stats::Vector2dInfo::subnames, Stats::Vector2dInfo::x, Stats::Vector2dInfo::y, and Stats::Vector2dInfo::y_subnames.
visit() [6/7]
void Stats::Hdf5::visit (const FormulaInfo & info) override virtual
Implements Stats::Output.
Definition at line 180 of file hdf5.cc.
References addMetaData(), appendVectorInfo(), dumpCount, enableFormula, and Stats::FormulaInfo::str().
visit() [7/7]
void Stats::Hdf5::visit (const SparseHistInfo & info) override virtual
Implements Stats::Output.
Definition at line 192 of file hdf5.cc.
References warn_once.
Member Data Documentation
dumpCount
unsigned Stats::Hdf5::dumpCount protected
Definition at line 149 of file hdf5.hh.
Referenced by appendStat(), appendVectorInfo(), begin(), end(), and visit().
enableDescriptions
const bool Stats::Hdf5::enableDescriptions protected
Definition at line 144 of file hdf5.hh.
Referenced by appendStat().
enableFormula
const bool Stats::Hdf5::enableFormula protected
Definition at line 145 of file hdf5.hh.
Referenced by visit().
fname
const std::string Stats::Hdf5::fname protected
Definition at line 142 of file hdf5.hh.
Referenced by begin().
h5File
H5::H5File Stats::Hdf5::h5File protected
Definition at line 150 of file hdf5.hh.
Referenced by begin().
path
std::stack<H5::Group> Stats::Hdf5::path protected
Definition at line 147 of file hdf5.hh.
Referenced by appendStat(), begin(), beginGroup(), and endGroup().
timeChunk
const hsize_t Stats::Hdf5::timeChunk protected
Definition at line 143 of file hdf5.hh.
Referenced by appendStat().
The documentation for this class was generated from the following files:
base/stats/hdf5.hh
base/stats/hdf5.cc