gem5: sc_core::sc_time_tuple Class Reference
sc_core::sc_time_tuple Class Reference
#include <sc_time.hh>
Public Member Functions
sc_time_tuple ()
sc_time_tuple (const sc_time &)
bool has_value () const
sc_dt::uint64 value () const
sc_time_unit unit () const
const char * unit_symbol () const
operator sc_time () const
double to_double () const
std::string to_string () const
Private Attributes
sc_dt::uint64 _value
sc_time_unit _unit
bool _set
Detailed Description
Definition at line 116 of file sc_time.hh.
Constructor & Destructor Documentation
sc_time_tuple() [1/2]
sc_core::sc_time_tuple::sc_time_tuple () inline
Definition at line 119 of file sc_time.hh.
References sc_core::sc_time::value().
sc_time_tuple() [2/2]
sc_core::sc_time_tuple::sc_time_tuple (const sc_time & t)
Definition at line 397 of file sc_time.cc.
References _unit, _value, SimClock::Frequency, sc_core::SC_SEC, and sc_core::sc_time::value().
Member Function Documentation
has_value()
bool sc_core::sc_time_tuple::has_value () const
Definition at line 433 of file sc_time.cc.
References _set.
operator sc_time()
sc_core::sc_time_tuple::operator sc_time () const inline
Definition at line 129 of file sc_time.hh.
References sc_core::sc_time::sc_time(), sc_core::sc_time::to_double(), and sc_core::sc_time::to_string().
to_double()
double sc_core::sc_time_tuple::to_double () const
Definition at line 446 of file sc_time.cc.
References _value.
to_string()
std::string sc_core::sc_time_tuple::to_string () const
Definition at line 449 of file sc_time.cc.
References _value, ArmISA::ss, and unit_symbol().
Referenced by sc_core::sc_time::print().
unit()
sc_time_unit sc_core::sc_time_tuple::unit () const inline
Definition at line 125 of file sc_time.hh.
unit_symbol()
const char * sc_core::sc_time_tuple::unit_symbol () const
Definition at line 441 of file sc_time.cc.
References _unit, and sc_gem5::TimeUnitNames.
Referenced by to_string().
value()
sc_dt::uint64 sc_core::sc_time_tuple::value () const
Definition at line 438 of file sc_time.cc.
References _value.
Member Data Documentation
_set
bool sc_core::sc_time_tuple::_set private
Definition at line 137 of file sc_time.hh.
Referenced by has_value().
_unit
sc_time_unit sc_core::sc_time_tuple::_unit private
Definition at line 136 of file sc_time.hh.
Referenced by sc_time_tuple(), and unit_symbol().
_value
sc_dt::uint64 sc_core::sc_time_tuple::_value private
Definition at line 135 of file sc_time.hh.
Referenced by sc_time_tuple(), to_double(), to_string(), and value().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_time.hh
systemc/core/sc_time.cc