gem5: sc_dt::sc_bv< W > Class Template Reference
sc_dt::sc_bv< W > Class Template Reference
#include <sc_bv.hh>
Public Member Functions
sc_bv ()
sc_bv (bool init_value)
sc_bv (char init_value)
sc_bv (const char *a)
sc_bv (const bool *a)
sc_bv (const sc_logic *a)
sc_bv (const sc_unsigned &a)
sc_bv (const sc_signed &a)
sc_bv (const sc_uint_base &a)
sc_bv (const sc_int_base &a)
sc_bv (unsigned long a)
sc_bv (long a)
sc_bv (unsigned int a)
sc_bv (int a)
sc_bv (uint64 a)
sc_bv (int64 a)
template<class X >
sc_bv (const sc_proxy< X > &a)
sc_bv (const sc_bv< W > &a)
template<class X >
sc_bv< W > & operator= (const sc_proxy< X > &a)
sc_bv< W > & operator= (const sc_bv< W > &a)
sc_bv< W > & operator= (const char *a)
sc_bv< W > & operator= (const bool *a)
sc_bv< W > & operator= (const sc_logic *a)
sc_bv< W > & operator= (const sc_unsigned &a)
sc_bv< W > & operator= (const sc_signed &a)
sc_bv< W > & operator= (const sc_uint_base &a)
sc_bv< W > & operator= (const sc_int_base &a)
sc_bv< W > & operator= (unsigned long a)
sc_bv< W > & operator= (long a)
sc_bv< W > & operator= (unsigned int a)
sc_bv< W > & operator= (int a)
sc_bv< W > & operator= (uint64 a)
sc_bv< W > & operator= (int64 a)
Public Member Functions inherited from sc_dt::sc_bv_base
sc_bv_base (int length_=sc_length_param().len())
sc_bv_base (bool a, int length_=sc_length_param().len())
sc_bv_base (const char *a)
sc_bv_base (const char *a, int length_)
template<class X >
sc_bv_base (const sc_proxy< X > &a)
sc_bv_base (const sc_bv_base &a)
virtual ~sc_bv_base ()
template<class X >
sc_bv_base & operator= (const sc_proxy< X > &a)
sc_bv_base & operator= (const sc_bv_base &a)
sc_bv_base & operator= (const char *a)
sc_bv_base & operator= (const bool *a)
sc_bv_base & operator= (const sc_logic *a)
sc_bv_base & operator= (const sc_unsigned &a)
sc_bv_base & operator= (const sc_signed &a)
sc_bv_base & operator= (const sc_uint_base &a)
sc_bv_base & operator= (const sc_int_base &a)
sc_bv_base & operator= (unsigned long a)
sc_bv_base & operator= (long a)
sc_bv_base & operator= (unsigned int a)
sc_bv_base & operator= (int a)
sc_bv_base & operator= (uint64 a)
sc_bv_base & operator= (int64 a)
int length () const
int size () const
value_type get_bit (int i) const
void set_bit (int i, value_type value)
sc_digit get_word (int i) const
void set_word (int i, sc_digit w)
sc_digit get_cword (int) const
void set_cword (int i, sc_digit w)
void clean_tail ()
bool is_01 () const
Public Member Functions inherited from sc_dt::sc_proxy< sc_bv_base >
virtual ~sc_proxy ()
sc_bv_base & back_cast ()
const sc_bv_base & back_cast () const
sc_bv_base & assign_ (const sc_proxy< Y > &a)
sc_bv_base & assign_ (const char *a)
sc_bv_base & assign_ (const bool *a)
sc_bv_base & assign_ (const sc_logic *a)
sc_bv_base & assign_ (const sc_unsigned &a)
sc_bv_base & assign_ (const sc_signed &a)
sc_bv_base & assign_ (const sc_uint_base &a)
sc_bv_base & assign_ (const sc_int_base &a)
sc_bv_base & assign_ (unsigned int a)
sc_bv_base & assign_ (int a)
sc_bv_base & assign_ (unsigned long a)
sc_bv_base & assign_ (long a)
sc_bv_base & assign_ (uint64 a)
sc_bv_base & assign_ (int64 a)
sc_bv_base & b_not ()
const sc_lv_base operator~ () const
sc_bv_base & operator &= (const char *b)
sc_bv_base & operator &= (const bool *b)
sc_bv_base & operator &= (const sc_logic *b)
sc_bv_base & operator &= (const sc_unsigned &b)
sc_bv_base & operator &= (const sc_signed &b)
sc_bv_base & operator &= (const sc_uint_base &b)
sc_bv_base & operator &= (const sc_int_base &b)
sc_bv_base & operator &= (unsigned long b)
sc_bv_base & operator &= (long b)
sc_bv_base & operator &= (unsigned int b)
sc_bv_base & operator &= (int b)
sc_bv_base & operator &= (uint64 b)
sc_bv_base & operator &= (int64 b)
const sc_lv_base operator & (const char *b) const
const sc_lv_base operator & (const bool *b) const
const sc_lv_base operator & (const sc_logic *b) const
const sc_lv_base operator & (const sc_unsigned &b) const
const sc_lv_base operator & (const sc_signed &b) const
const sc_lv_base operator & (const sc_uint_base &b) const
const sc_lv_base operator & (const sc_int_base &b) const
const sc_lv_base operator & (unsigned long b) const
const sc_lv_base operator & (long b) const
const sc_lv_base operator & (unsigned int b) const
const sc_lv_base operator & (int b) const
const sc_lv_base operator & (uint64 b) const
const sc_lv_base operator & (int64 b) const
sc_bv_base & operator|= (const char *b)
sc_bv_base & operator|= (const bool *b)
sc_bv_base & operator|= (const sc_logic *b)
sc_bv_base & operator|= (const sc_unsigned &b)
sc_bv_base & operator|= (const sc_signed &b)
sc_bv_base & operator|= (const sc_uint_base &b)
sc_bv_base & operator|= (const sc_int_base &b)
sc_bv_base & operator|= (unsigned long b)
sc_bv_base & operator|= (long b)
sc_bv_base & operator|= (unsigned int b)
sc_bv_base & operator|= (int b)
sc_bv_base & operator|= (uint64 b)
sc_bv_base & operator|= (int64 b)
const sc_lv_base operator| (const char *b) const
const sc_lv_base operator| (const bool *b) const
const sc_lv_base operator| (const sc_logic *b) const
const sc_lv_base operator| (const sc_unsigned &b) const
const sc_lv_base operator| (const sc_signed &b) const
const sc_lv_base operator| (const sc_uint_base &b) const
const sc_lv_base operator| (const sc_int_base &b) const
const sc_lv_base operator| (unsigned long b) const
const sc_lv_base operator| (long b) const
const sc_lv_base operator| (unsigned int b) const
const sc_lv_base operator| (int b) const
const sc_lv_base operator| (uint64 b) const
const sc_lv_base operator| (int64 b) const
sc_bv_base & operator^= (const char *b)
sc_bv_base & operator^= (const bool *b)
sc_bv_base & operator^= (const sc_logic *b)
sc_bv_base & operator^= (const sc_unsigned &b)
sc_bv_base & operator^= (const sc_signed &b)
sc_bv_base & operator^= (const sc_uint_base &b)
sc_bv_base & operator^= (const sc_int_base &b)
sc_bv_base & operator^= (unsigned long b)
sc_bv_base & operator^= (long b)
sc_bv_base & operator^= (unsigned int b)
sc_bv_base & operator^= (int b)
sc_bv_base & operator^= (uint64 b)
sc_bv_base & operator^= (int64 b)
const sc_lv_base operator^ (const char *b) const
const sc_lv_base operator^ (const bool *b) const
const sc_lv_base operator^ (const sc_logic *b) const
const sc_lv_base operator^ (const sc_unsigned &b) const
const sc_lv_base operator^ (const sc_signed &b) const
const sc_lv_base operator^ (const sc_uint_base &b) const
const sc_lv_base operator^ (const sc_int_base &b) const
const sc_lv_base operator^ (unsigned long b) const
const sc_lv_base operator^ (long b) const
const sc_lv_base operator^ (unsigned int b) const
const sc_lv_base operator^ (int b) const
const sc_lv_base operator^ (uint64 b) const
const sc_lv_base operator^ (int64 b) const
sc_bv_base & operator<<= (int n)
const sc_lv_base operator<< (int n) const
sc_bv_base & operator>>= (int n)
const sc_lv_base operator>> (int n) const
sc_bv_base & lrotate (int n)
sc_bv_base & rrotate (int n)
sc_bv_base & reverse ()
sc_bitref< sc_bv_base > operator[] (int i)
sc_bitref_r< sc_bv_base > operator[] (int i) const
sc_bitref< sc_bv_base > bit (int i)
sc_bitref_r< sc_bv_base > bit (int i) const
sc_subref< sc_bv_base > operator() (int hi, int lo)
sc_subref_r< sc_bv_base > operator() (int hi, int lo) const
sc_subref< sc_bv_base > range (int hi, int lo)
sc_subref_r< sc_bv_base > range (int hi, int lo) const
value_type and_reduce () const
value_type nand_reduce () const
value_type or_reduce () const
value_type nor_reduce () const
value_type xor_reduce () const
value_type xnor_reduce () const
bool operator== (const char *b) const
bool operator== (const bool *b) const
bool operator== (const sc_logic *b) const
bool operator== (const sc_unsigned &b) const
bool operator== (const sc_signed &b) const
bool operator== (const sc_uint_base &b) const
bool operator== (const sc_int_base &b) const
bool operator== (unsigned long b) const
bool operator== (long b) const
bool operator== (unsigned int b) const
bool operator== (int b) const
bool operator== (uint64 b) const
bool operator== (int64 b) const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
int64 to_int64 () const
uint64 to_uint64 () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Additional Inherited Members
Public Types inherited from sc_dt::sc_bv_base
typedef sc_proxy< sc_bv_base > base_type
typedef base_type::value_type value_type
Public Types inherited from sc_dt::sc_proxy< sc_bv_base >
typedef sc_proxy_traits< sc_bv_base >::traits_type traits_type
typedef traits_type::bit_type bit_type
typedef traits_type::value_type value_type
Protected Member Functions inherited from sc_dt::sc_proxy< sc_bv_base >
void check_bounds (int n) const
void check_wbounds (int n) const
sc_digit to_anything_unsigned () const
int64 to_anything_signed () const
Protected Attributes inherited from sc_dt::sc_bv_base
int m_len
int m_size
sc_digit * m_data
Detailed Description
template<int W>
class sc_dt::sc_bv< W >
Definition at line 57 of file sc_bv.hh.
Constructor & Destructor Documentation
sc_bv() [1/18]
template<int W> sc_dt::sc_bv< W >::sc_bv () inline
Definition at line 71 of file sc_bv.hh.
sc_bv() [2/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (bool init_value) inline explicit
Definition at line 73 of file sc_bv.hh.
sc_bv() [3/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (char init_value) inline explicit
Definition at line 75 of file sc_bv.hh.
sc_bv() [4/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const char * a) inline
Definition at line 77 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [5/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const bool * a) inline
Definition at line 78 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [6/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_logic * a) inline
Definition at line 79 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [7/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_unsigned & a) inline
Definition at line 80 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [8/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_signed & a) inline
Definition at line 81 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [9/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_uint_base & a) inline
Definition at line 82 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [10/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_int_base & a) inline
Definition at line 86 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [11/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (unsigned long a) inline
Definition at line 87 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [12/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (long a) inline
Definition at line 88 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [13/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (unsigned int a) inline
Definition at line 89 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [14/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (int a) inline
Definition at line 90 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [15/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (uint64 a) inline
Definition at line 91 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [16/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (int64 a) inline
Definition at line 92 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [17/18]
template<int W> template<class X > sc_dt::sc_bv< W >::sc_bv (const sc_proxy< X > & a) inline
Definition at line 95 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
sc_bv() [18/18]
template<int W> sc_dt::sc_bv< W >::sc_bv (const sc_bv< W > & a) inline
Definition at line 96 of file sc_bv.hh.
Member Function Documentation
operator=() [1/15]
template<int W> template<class X > sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_proxy< X > & a) inline
Definition at line 101 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [2/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_bv< W > & a) inline
Definition at line 108 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [3/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const char * a) inline
Definition at line 115 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [4/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const bool * a) inline
Definition at line 122 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [5/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_logic * a) inline
Definition at line 129 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [6/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_unsigned & a) inline
Definition at line 136 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [7/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_signed & a) inline
Definition at line 143 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [8/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_uint_base & a) inline
Definition at line 150 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [9/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (const sc_int_base & a) inline
Definition at line 157 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [10/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (unsigned long a) inline
Definition at line 164 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [11/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (long a) inline
Definition at line 171 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [12/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (unsigned int a) inline
Definition at line 178 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [13/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (int a) inline
Definition at line 185 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [14/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (uint64 a) inline
Definition at line 192 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
operator=() [15/15]
template<int W> sc_bv<W>& sc_dt::sc_bv< W >::operator= (int64 a) inline
Definition at line 199 of file sc_bv.hh.
References sc_dt::sc_bv_base::operator=().
The documentation for this class was generated from the following file:
systemc/ext/dt/bit/sc_bv.hh