gem5: sc_core::sc_event_or_list Class Reference
sc_core::sc_event_or_list Class Reference
#include <sc_event.hh>
Public Member Functions
sc_event_or_list ()
sc_event_or_list (const sc_event_or_list &)
sc_event_or_list (const sc_event &)
sc_event_or_list & operator= (const sc_event_or_list &)
~sc_event_or_list ()
int size () const
void swap (sc_event_or_list &)
sc_event_or_list & operator|= (const sc_event &)
sc_event_or_list & operator|= (const sc_event_or_list &)
sc_event_or_expr operator| (const sc_event &) const
sc_event_or_expr operator| (const sc_event_or_list &) const
Private Member Functions
sc_event_or_list (bool auto_delete)
void insert (sc_event const &e)
void insert (sc_event_or_list const &eol)
Private Attributes
std::set< const sc_event * > events
bool autoDelete
unsigned busy
Friends
class sc_event_or_expr
class sc_gem5::DynamicSensitivityEventOrList
Detailed Description
Definition at line 95 of file sc_event.hh.
Constructor & Destructor Documentation
sc_event_or_list() [1/4]
sc_core::sc_event_or_list::sc_event_or_list ()
Definition at line 127 of file sc_event.cc.
sc_event_or_list() [2/4]
sc_core::sc_event_or_list::sc_event_or_list (const sc_event_or_list & eol)
Definition at line 129 of file sc_event.cc.
sc_event_or_list() [3/4]
sc_core::sc_event_or_list::sc_event_or_list (const sc_event & e)
Definition at line 133 of file sc_event.cc.
References insert().
~sc_event_or_list()
sc_core::sc_event_or_list::~sc_event_or_list ()
Definition at line 149 of file sc_event.cc.
sc_event_or_list() [4/4]
sc_core::sc_event_or_list::sc_event_or_list (bool auto_delete) explicit private
Definition at line 138 of file sc_event.cc.
Member Function Documentation
insert() [1/2]
void sc_core::sc_event_or_list::insert (sc_event const & e) private
Definition at line 196 of file sc_event.cc.
References events.
Referenced by sc_core::sc_event_or_expr::insert(), operator|=(), and sc_event_or_list().
insert() [2/2]
void sc_core::sc_event_or_list::insert (sc_event_or_list const & eol) private
Definition at line 202 of file sc_event.cc.
References events.
operator=()
sc_event_or_list & sc_core::sc_event_or_list::operator= (const sc_event_or_list & eol)
Definition at line 143 of file sc_event.cc.
References events.
operator|() [1/2]
sc_event_or_expr sc_core::sc_event_or_list::operator| (const sc_event & e) const
Definition at line 178 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
operator|() [2/2]
sc_event_or_expr sc_core::sc_event_or_list::operator| (const sc_event_or_list & eol) const
Definition at line 187 of file sc_event.cc.
References sc_core::sc_event_or_expr::insert().
operator|=() [1/2]
sc_event_or_list & sc_core::sc_event_or_list::operator|= (const sc_event & e)
Definition at line 164 of file sc_event.cc.
References insert().
operator|=() [2/2]
sc_event_or_list & sc_core::sc_event_or_list::operator|= (const sc_event_or_list & eol)
Definition at line 171 of file sc_event.cc.
References insert().
size()
int sc_core::sc_event_or_list::size () const
Definition at line 152 of file sc_event.cc.
References events.
swap()
void sc_core::sc_event_or_list::swap (sc_event_or_list & eol)
Definition at line 158 of file sc_event.cc.
References events.
Friends And Related Function Documentation
sc_event_or_expr
friend class sc_event_or_expr friend
Definition at line 114 of file sc_event.hh.
sc_gem5::DynamicSensitivityEventOrList
friend class sc_gem5::DynamicSensitivityEventOrList friend
Definition at line 115 of file sc_event.hh.
Member Data Documentation
autoDelete
bool sc_core::sc_event_or_list::autoDelete private
Definition at line 123 of file sc_event.hh.
busy
unsigned sc_core::sc_event_or_list::busy mutable private
Definition at line 124 of file sc_event.hh.
events
std::set<const sc_event *> sc_core::sc_event_or_list::events private
Definition at line 122 of file sc_event.hh.
Referenced by insert(), operator=(), size(), and swap().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_event.hh
systemc/core/sc_event.cc