gem5: sc_dt::scfx_string Class Reference
sc_dt::scfx_string Class Reference
#include <scfx_string.hh>
Public Member Functions
scfx_string ()
~scfx_string ()
int length () const
void clear ()
char & operator[] (int)
void append (int)
void discard (int)
void remove (int)
void operator+= (char)
void operator+= (const char *)
operator const char * ()
Private Member Functions
void resize (std::size_t)
Private Attributes
std::size_t m_len
std::size_t m_alloc
char * m_buffer
Detailed Description
Definition at line 76 of file scfx_string.hh.
Constructor & Destructor Documentation
scfx_string()
sc_dt::scfx_string::scfx_string () inline
Definition at line 127 of file scfx_string.hh.
References m_buffer, and m_len.
~scfx_string()
sc_dt::scfx_string::~scfx_string () inline
Definition at line 133 of file scfx_string.hh.
References m_buffer.
Member Function Documentation
append()
void sc_dt::scfx_string::append (int n) inline
Definition at line 154 of file scfx_string.hh.
References m_buffer, m_len, and ArmISA::n.
Referenced by sc_dt::print_dec().
clear()
void sc_dt::scfx_string::clear () inline
Definition at line 138 of file scfx_string.hh.
References m_buffer, and m_len.
Referenced by sc_dt::scfx_rep::to_string(), and sc_dt::to_string().
discard()
void sc_dt::scfx_string::discard (int n) inline
Definition at line 161 of file scfx_string.hh.
References m_buffer, m_len, and ArmISA::n.
Referenced by sc_dt::print_dec(), and sc_dt::print_other().
length()
int sc_dt::scfx_string::length () const inline
Definition at line 135 of file scfx_string.hh.
References m_len.
Referenced by sc_dt::print_dec(), sc_dt::print_other(), and sc_dt::scfx_csd2tc().
operator const char *()
sc_dt::scfx_string::operator const char * () inline
Definition at line 191 of file scfx_string.hh.
References m_buffer, and m_len.
operator+=() [1/2]
void sc_dt::scfx_string::operator+= (char c) inline
Definition at line 177 of file scfx_string.hh.
References ArmISA::c, m_len, and operator[]().
operator+=() [2/2]
void sc_dt::scfx_string::operator+= (const char * s) inline
Definition at line 185 of file scfx_string.hh.
operator[]()
char & sc_dt::scfx_string::operator[] (int i) inline
Definition at line 145 of file scfx_string.hh.
References ArmISA::i, m_alloc, m_buffer, and resize().
Referenced by operator+=().
remove()
void sc_dt::scfx_string::remove (int i) inline
Definition at line 168 of file scfx_string.hh.
References ArmISA::j, m_buffer, and m_len.
Referenced by sc_dt::print_dec().
resize()
void sc_dt::scfx_string::resize (std::size_t i) inline private
Definition at line 110 of file scfx_string.hh.
References ArmISA::j, m_alloc, m_buffer, and m_len.
Referenced by operator[]().
Member Data Documentation
m_alloc
std::size_t sc_dt::scfx_string::m_alloc private
Definition at line 102 of file scfx_string.hh.
Referenced by operator[](), and resize().
m_buffer
char* sc_dt::scfx_string::m_buffer private
Definition at line 103 of file scfx_string.hh.
Referenced by append(), clear(), discard(), operator const char *(), operator[](), remove(), resize(), scfx_string(), and ~scfx_string().
m_len
std::size_t sc_dt::scfx_string::m_len private
Definition at line 101 of file scfx_string.hh.
Referenced by append(), clear(), discard(), length(), operator const char *(), operator+=(), remove(), resize(), and scfx_string().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/scfx_string.hh