gem5: sc_gem5::Event Class Reference
sc_gem5::Event Class Reference
#include <event.hh>
Public Member Functions
Event (sc_core::sc_event *_sc_event, bool internal=false)
Event (sc_core::sc_event *_sc_event, const char *_basename, bool internal=false)
~Event ()
sc_core::sc_event * sc_event ()
const std::string & name () const
const std::string & basename () const
bool inHierarchy () const
sc_core::sc_object * getParentObject () const
void notify (StaticSensitivities &senses)
void notify (DynamicSensitivities &senses)
void notify ()
void notify (const sc_core::sc_time &t)
void notify (double d, sc_core::sc_time_unit &u)
void notifyDelayed (const sc_core::sc_time &t)
void cancel ()
bool triggered () const
uint64_t triggeredStamp () const
void addSensitivity (StaticSensitivity *s) const
void delSensitivity (StaticSensitivity *s) const
void addSensitivity (DynamicSensitivity *s) const
void delSensitivity (DynamicSensitivity *s) const
void clearParent ()
Static Public Member Functions
static Event * getFromScEvent (sc_core::sc_event *e)
static const Event * getFromScEvent (const sc_core::sc_event *e)
Private Attributes
sc_core::sc_event * _sc_event
std::string _basename
std::string _name
bool _inHierarchy
sc_core::sc_object * parent
ScEvent delayedNotify
uint64_t _triggeredStamp
StaticSensitivities staticSenseMethod
StaticSensitivities staticSenseThread
DynamicSensitivities dynamicSenseMethod
DynamicSensitivities dynamicSenseThread
Detailed Description
Definition at line 60 of file event.hh.
Constructor & Destructor Documentation
Event() [1/2]
Event::Event (sc_core::sc_event * _sc_event, bool internal = false)
Definition at line 46 of file event.cc.
Event() [2/2]
Event::Event (sc_core::sc_event * _sc_event, const char * _basename, bool internal = false)
Definition at line 50 of file event.cc.
References _basename, _name, _sc_event, _triggeredStamp, sc_gem5::Object::addChildEvent(), sc_gem5::allEvents, sc_gem5::UniqueNameGen::gen(), sc_gem5::Object::getFromScObject(), sc_gem5::globalNameGen, sc_core::sc_object::name(), notify(), parent, sc_gem5::pickParentObj(), sc_gem5::pickUniqueName(), sc_core::sc_gen_unique_name(), sc_core::SC_ID_INSTANCE_EXISTS_, sc_core::sc_is_running(), SC_REPORT_WARNING, sc_gem5::topLevelEvents, and ULL.
~Event()
Event::~Event ()
Definition at line 94 of file event.cc.
References _name, _sc_event, sc_gem5::allEvents, delayedNotify, sc_gem5::Object::delChildEvent(), sc_gem5::Scheduler::deschedule(), sc_gem5::findEvent(), sc_gem5::Object::getFromScObject(), inHierarchy(), parent, sc_gem5::ScEvent::scheduled(), sc_gem5::scheduler, and sc_gem5::topLevelEvents.
Member Function Documentation
addSensitivity() [1/2]
void sc_gem5::Event::addSensitivity (StaticSensitivity * s) const inline
Definition at line 105 of file event.hh.
References sc_gem5::Sensitivity::ofMethod(), and ArmISA::s.
Referenced by sc_gem5::DynamicSensitivity::addToEvent(), and sc_gem5::StaticSensitivity::addToEvent().
addSensitivity() [2/2]
void sc_gem5::Event::addSensitivity (DynamicSensitivity * s) const inline
Definition at line 125 of file event.hh.
References sc_gem5::Sensitivity::ofMethod().
basename()
const std::string & Event::basename () const
Definition at line 122 of file event.cc.
References _basename.
Referenced by sc_core::sc_event::basename().
cancel()
void Event::cancel ()
Definition at line 198 of file event.cc.
References delayedNotify, sc_gem5::Scheduler::deschedule(), sc_gem5::ScEvent::scheduled(), and sc_gem5::scheduler.
Referenced by sc_core::sc_event::cancel().
clearParent()
void Event::clearParent ()
Definition at line 211 of file event.cc.
References sc_gem5::Object::delChildEvent(), sc_gem5::Object::getFromScObject(), parent, sc_event(), and sc_gem5::topLevelEvents.
Referenced by sc_gem5::Object::~Object().
delSensitivity() [1/2]
void sc_gem5::Event::delSensitivity (StaticSensitivity * s) const inline
Definition at line 113 of file event.hh.
References sc_gem5::Sensitivity::ofMethod().
Referenced by sc_gem5::DynamicSensitivity::delFromEvent(), and sc_gem5::StaticSensitivity::delFromEvent().
delSensitivity() [2/2]
void sc_gem5::Event::delSensitivity (DynamicSensitivity * s) const inline
Definition at line 131 of file event.hh.
References sc_gem5::Sensitivity::ofMethod().
getFromScEvent() [1/2]
static Event* sc_gem5::Event::getFromScEvent (sc_core::sc_event * e) inline static
Definition at line 93 of file event.hh.
References sc_core::sc_event::_gem5_event.
Referenced by sc_gem5::DynamicSensitivity::addToEvent(), sc_gem5::StaticSensitivity::addToEvent(), sc_gem5::DynamicSensitivity::delFromEvent(), sc_gem5::StaticSensitivity::delFromEvent(), and sc_gem5::Object::~Object().
getFromScEvent() [2/2]
static const Event* sc_gem5::Event::getFromScEvent (const sc_core::sc_event * e) inline static
Definition at line 99 of file event.hh.
References sc_core::sc_event::_gem5_event.
getParentObject()
sc_core::sc_object * Event::getParentObject () const
Definition at line 134 of file event.cc.
References parent.
Referenced by sc_core::sc_event::get_parent_object().
inHierarchy()
bool Event::inHierarchy () const
Definition at line 128 of file event.cc.
References _inHierarchy.
Referenced by sc_core::sc_event::in_hierarchy(), and ~Event().
name()
const std::string & Event::name () const
Definition at line 116 of file event.cc.
References _name.
Referenced by sc_core::sc_event::name().
notify() [1/5]
void Event::notify (StaticSensitivities & senses)
Definition at line 140 of file event.cc.
References ArmISA::s.
Referenced by sc_core::sc_event::notify().
notify() [2/5]
void Event::notify (DynamicSensitivities & senses)
Definition at line 147 of file event.cc.
References notify().
notify() [3/5]
void Event::notify ()
Definition at line 161 of file event.cc.
References _triggeredStamp, sc_gem5::Scheduler::changeStamp(), delayedNotify, sc_gem5::Scheduler::deschedule(), dynamicSenseMethod, dynamicSenseThread, sc_gem5::Scheduler::inUpdate(), sc_core::SC_ID_IMMEDIATE_NOTIFICATION_, SC_REPORT_ERROR, sc_gem5::ScEvent::scheduled(), sc_gem5::scheduler, staticSenseMethod, and staticSenseThread.
Referenced by Event(), notify(), and notifyDelayed().
notify() [4/5]
void Event::notify (const sc_core::sc_time & t)
Definition at line 178 of file event.cc.
References sc_gem5::Scheduler::delayed(), delayedNotify, sc_gem5::Scheduler::deschedule(), sc_gem5::Scheduler::schedule(), sc_gem5::ScEvent::scheduled(), sc_gem5::scheduler, and sc_gem5::ScEvent::when().
notify() [5/5]
void sc_gem5::Event::notify (double d, sc_core::sc_time_unit & u) inline
Definition at line 82 of file event.hh.
notifyDelayed()
void Event::notifyDelayed (const sc_core::sc_time & t)
Definition at line 190 of file event.cc.
References delayedNotify, notify(), sc_core::SC_ID_NOTIFY_DELAYED_, SC_REPORT_ERROR, and sc_gem5::ScEvent::scheduled().
Referenced by sc_core::sc_event::notify_delayed().
sc_event()
sc_core::sc_event* sc_gem5::Event::sc_event () inline
Definition at line 69 of file event.hh.
References name(), and ArmISA::t.
Referenced by clearParent(), sc_gem5::DynamicSensitivityEventOrList::notifyWork(), and sc_gem5::DynamicSensitivityEventAndList::notifyWork().
triggered()
bool Event::triggered () const
Definition at line 205 of file event.cc.
References _triggeredStamp, sc_gem5::Scheduler::changeStamp(), and sc_gem5::scheduler.
Referenced by sc_core::sc_event::triggered().
triggeredStamp()
uint64_t sc_gem5::Event::triggeredStamp () const inline
Definition at line 90 of file event.hh.
Member Data Documentation
_basename
std::string sc_gem5::Event::_basename private
Definition at line 148 of file event.hh.
Referenced by basename(), and Event().
_inHierarchy
bool sc_gem5::Event::_inHierarchy private
Definition at line 150 of file event.hh.
Referenced by inHierarchy().
_name
std::string sc_gem5::Event::_name private
Definition at line 149 of file event.hh.
Referenced by Event(), name(), and ~Event().
_sc_event
sc_core::sc_event* sc_gem5::Event::_sc_event private
Definition at line 146 of file event.hh.
Referenced by Event(), and ~Event().
_triggeredStamp
uint64_t sc_gem5::Event::_triggeredStamp mutable private
Definition at line 155 of file event.hh.
Referenced by Event(), notify(), and triggered().
delayedNotify
ScEvent sc_gem5::Event::delayedNotify private
Definition at line 154 of file event.hh.
Referenced by cancel(), notify(), notifyDelayed(), and ~Event().
dynamicSenseMethod
DynamicSensitivities sc_gem5::Event::dynamicSenseMethod mutable private
Definition at line 159 of file event.hh.
Referenced by notify().
dynamicSenseThread
DynamicSensitivities sc_gem5::Event::dynamicSenseThread mutable private
Definition at line 160 of file event.hh.
Referenced by notify().
parent
sc_core::sc_object* sc_gem5::Event::parent private
Definition at line 152 of file event.hh.
Referenced by clearParent(), Event(), getParentObject(), and ~Event().
staticSenseMethod
StaticSensitivities sc_gem5::Event::staticSenseMethod mutable private
Definition at line 157 of file event.hh.
Referenced by notify().
staticSenseThread
StaticSensitivities sc_gem5::Event::staticSenseThread mutable private
Definition at line 158 of file event.hh.
Referenced by notify().
The documentation for this class was generated from the following files:
systemc/core/event.hh
systemc/core/event.cc