gem5: sc_core::sc_export_base Class Reference
sc_core::sc_export_base Class Reference abstract
#include <sc_export.hh>
Public Member Functions
sc_export_base (const char *n)
~sc_export_base ()
virtual sc_interface * get_iterface ()=0
virtual const sc_interface * get_interface () const =0
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual const char * kind () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
virtual void before_end_of_elaboration ()=0
virtual void end_of_elaboration ()=0
virtual void start_of_simulation ()=0
virtual void end_of_simulation ()=0
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Friends
class sc_gem5::Module
Detailed Description
Definition at line 43 of file sc_export.hh.
Constructor & Destructor Documentation
sc_export_base()
sc_core::sc_export_base::sc_export_base (const char * n)
Definition at line 58 of file sc_export.cc.
References sc_core::sc_object::kind(), ArmISA::m, sc_core::sc_object::name(), sc_gem5::pickParentModule(), sc_core::SC_ID_EXPORT_OUTSIDE_MODULE_, sc_core::SC_ID_INSERT_EXPORT_, sc_core::sc_is_running(), and sc_gem5::scheduler.
~sc_export_base()
sc_core::sc_export_base::~sc_export_base ()
Definition at line 73 of file sc_export.cc.
Member Function Documentation
before_end_of_elaboration()
virtual void sc_core::sc_export_base::before_end_of_elaboration () protected pure virtual
Implemented in sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >.
end_of_elaboration()
virtual void sc_core::sc_export_base::end_of_elaboration () protected pure virtual
Implemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >, sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >.
end_of_simulation()
virtual void sc_core::sc_export_base::end_of_simulation () protected pure virtual
Implemented in sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >.
get_interface()
virtual const sc_interface* sc_core::sc_export_base::get_interface () const pure virtual
Implemented in sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >.
get_iterface()
virtual sc_interface* sc_core::sc_export_base::get_iterface () pure virtual
Implemented in sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, and sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >.
start_of_simulation()
virtual void sc_core::sc_export_base::start_of_simulation () protected pure virtual
Implemented in tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_tagged_b< SimpleBusLT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< SimpleBusAT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_target_socket_b< sc_gem5::TlmToGem5Bridge< BITWIDTH >, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_b< SimpleATTarget2, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_gp2ext, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleATTarget1, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< ExplicitLTTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_ext2gp, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_target_socket_b< ExplicitATTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleLTTarget_ext, BUSWIDTH, my_extended_payload_types >, and tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >.
Friends And Related Function Documentation
sc_gem5::Module
friend class sc_gem5::Module friend
Definition at line 53 of file sc_export.hh.
The documentation for this class was generated from the following files:
systemc/ext/core/sc_export.hh
systemc/core/sc_export.cc