gem5: Stats::InfoAccess Class Reference
Stats::InfoAccess Class Reference
#include <statistics.hh>
Public Member Functions
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Member Functions
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Private Attributes
Info * _info
Detailed Description
Definition at line 186 of file statistics.hh.
Constructor & Destructor Documentation
InfoAccess()
Stats::InfoAccess::InfoAccess () inline
Definition at line 205 of file statistics.hh.
Member Function Documentation
check()
bool Stats::InfoAccess::check () const inline
Check that this stat has been set up properly and is ready for use.
Returns
true for success
Definition at line 224 of file statistics.hh.
info() [1/2]
Info * Stats::InfoAccess::info () protected
Grab the information class for this statistic.
Definition at line 118 of file statistics.cc.
References ArmISA::i, and Stats::statsMap().
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::info().
info() [2/2]
const Info * Stats::InfoAccess::info () const protected
Grab the information class for this statistic.
Definition at line 132 of file statistics.cc.
References ArmISA::i, and Stats::statsMap().
reset()
void Stats::InfoAccess::reset () inline
Reset the stat to the default state.
Definition at line 211 of file statistics.hh.
setInfo()
void Stats::InfoAccess::setInfo (Group * parent, Info * info) protected
Set up an info class for this statistic.
Definition at line 82 of file statistics.cc.
References panic_if, Stats::statsList(), and Stats::statsMap().
setInit()
void Stats::InfoAccess::setInit () protected
Save Storage class parameters if any.
Definition at line 112 of file statistics.cc.
References Stats::init.
Referenced by Stats::Formula::operator+=(), and Stats::Formula::operator=().
setParams()
void Stats::InfoAccess::setParams (const StorageParams * params) protected
Save Storage class parameters if any.
Definition at line 106 of file statistics.cc.
zero()
bool Stats::InfoAccess::zero () const inline
Returns
true if this stat has a value and satisfies its requirement as a prereq
Definition at line 217 of file statistics.hh.
Member Data Documentation
_info
Info* Stats::InfoAccess::_info private
Definition at line 189 of file statistics.hh.
The documentation for this class was generated from the following files:
base/statistics.hh
base/statistics.cc