gem5: CompressionBlk Class Reference
CompressionBlk Class Reference
A superblock is composed of sub-blocks, and each sub-block has information regarding its superblock and a pointer to its superblock tag.
#include <super_blk.hh>
Public Member Functions
CompressionBlk ()
CompressionBlk (const CompressionBlk &)=delete
CompressionBlk & operator= (const CompressionBlk &)=delete
~CompressionBlk ()
bool isCompressed () const
Check if this block holds compressed data.
void setCompressed ()
Set compression bit.
void setUncompressed ()
Clear compression bit.
std::size_t getSizeBits () const
void setSizeBits (const std::size_t size)
Set size, in bits, of this compressed block's data.
Cycles getDecompressionLatency () const
Get number of cycles needed to decompress this block.
void setDecompressionLatency (const Cycles lat)
Set number of cycles needed to decompress this block.
std::string print () const override
Pretty-print sector offset and other CacheBlk information.
Public Member Functions inherited from SectorSubBlk
SectorSubBlk ()
SectorSubBlk (const SectorSubBlk &)=delete
SectorSubBlk & operator= (const SectorSubBlk &)=delete
~SectorSubBlk ()
void setSectorBlock (SectorBlk *sector_blk)
Set sector block associated to this block.
const SectorBlk * getSectorBlock () const
Get sector block associated to this block.
void setSectorOffset (const int sector_offset)
Set offset of this sub-block within the sector.
int getSectorOffset () const
Get offset of this sub-block within the sector.
Addr getTag () const
Get tag associated to this block.
void setValid () override
Set valid bit and inform sector block.
void setSecure () override
Set secure bit and inform sector block.
void invalidate () override
Invalidate the block and inform sector block.
void insert (const Addr tag, const bool is_secure, const int src_master_ID, const uint32_t task_ID) override
Set member variables when a block insertion occurs.
Public Member Functions inherited from CacheBlk
CacheBlk ()
CacheBlk (const CacheBlk &)=delete
CacheBlk & operator= (const CacheBlk &)=delete
virtual ~CacheBlk ()
bool isWritable () const
Checks the write permissions of this block.
bool isReadable () const
Checks the read permissions of this block.
bool isValid () const
Checks that a block is valid.
bool isDirty () const
Check to see if a block has been written.
bool wasPrefetched () const
Check if this block was the result of a hardware prefetch, yet to be touched.
bool isSecure () const
Check if this block holds data from the secure memory space.
Tick getWhenReady () const
Get tick at which block's data will be available for access.
void setWhenReady (const Tick tick)
Set tick at which block's data will be available for access.
void trackLoadLocked (PacketPtr pkt)
Track the fact that a local locked was issued to the block.
void clearLoadLocks (const RequestPtr &req)
Clear the any load lock that intersect the request, and is from a different context.
bool checkWrite (PacketPtr pkt)
Handle interaction of load-locked operations and stores.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Private Attributes
std::size_t _size
Set size, in bits, of this compressed block's data.
Cycles _decompressionLatency
Number of cycles needed to decompress this block.
Additional Inherited Members
Public Types inherited from CacheBlk
typedef unsigned State
block state: OR of CacheBlkStatusBit
Public Attributes inherited from CacheBlk
uint32_t task_id
Task Id associated with this block.
Addr tag
Data block tag value.
uint8_t * data
Contains a copy of the data in this block for easy access.
State status
The current status of this block.
Tick whenReady
Which curTick() will this block be accessible.
unsigned refCount
Number of references to this block since it was brought in.
int srcMasterId
holds the source requestor ID for this block.
Tick tickInserted
Tick on which the block was inserted in the cache.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Protected Attributes inherited from SectorSubBlk
SectorBlk * _sectorBlk
Sector block associated to this block.
int _sectorOffset
The offset of this sub-block in the sector.
Protected Attributes inherited from CacheBlk
std::list< Lock > lockList
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
A superblock is composed of sub-blocks, and each sub-block has information regarding its superblock and a pointer to its superblock tag.
A superblock can be seen as a variation of a sector block, and therefore we use a sector nomenclature.
Definition at line 50 of file super_blk.hh.
Constructor & Destructor Documentation
CompressionBlk() [1/2]
CompressionBlk::CompressionBlk ()
Definition at line 41 of file super_blk.cc.
CompressionBlk() [2/2]
CompressionBlk::CompressionBlk (const CompressionBlk &) delete
~CompressionBlk()
CompressionBlk::~CompressionBlk () inline
Definition at line 68 of file super_blk.hh.
References getDecompressionLatency(), getSizeBits(), isCompressed(), print(), setCompressed(), setDecompressionLatency(), setSizeBits(), and setUncompressed().
Member Function Documentation
getDecompressionLatency()
Cycles CompressionBlk::getDecompressionLatency () const
Get number of cycles needed to decompress this block.
Returns
Decompression latency.
Definition at line 77 of file super_blk.cc.
References _decompressionLatency.
Referenced by BaseCacheCompressor::getDecompressionLatency(), print(), and ~CompressionBlk().
getSizeBits()
std::size_t CompressionBlk::getSizeBits () const
Definition at line 65 of file super_blk.cc.
References _size.
Referenced by CompressedTags::insertBlock(), print(), BaseCache::updateCompressionData(), and ~CompressionBlk().
isCompressed()
bool CompressionBlk::isCompressed () const
Check if this block holds compressed data.
Returns
True if the block holds compressed data.
Definition at line 47 of file super_blk.cc.
References BlkCompressed, and CacheBlk::status.
Referenced by BaseCacheCompressor::getDecompressionLatency(), SuperBlk::isCompressed(), print(), BaseCache::updateCompressionData(), ~CompressionBlk(), and SuperBlk::~SuperBlk().
operator=()
CompressionBlk& CompressionBlk::operator= (const CompressionBlk &) delete
Referenced by SuperBlk::SuperBlk().
print()
std::string CompressionBlk::print () const override virtual
Pretty-print sector offset and other CacheBlk information.
Returns
string with basic state information
Reimplemented from SectorSubBlk.
Definition at line 89 of file super_blk.cc.
References csprintf(), getDecompressionLatency(), getSizeBits(), isCompressed(), and SectorSubBlk::print().
Referenced by BaseCacheCompressor::getDecompressionLatency(), BaseCache::updateCompressionData(), and ~CompressionBlk().
setCompressed()
void CompressionBlk::setCompressed ()
Set compression bit.
Definition at line 53 of file super_blk.cc.
References BlkCompressed, and CacheBlk::status.
Referenced by CompressedTags::insertBlock(), BaseCache::updateCompressionData(), and ~CompressionBlk().
setDecompressionLatency()
void CompressionBlk::setDecompressionLatency (const Cycles lat)
Set number of cycles needed to decompress this block.
Parameters
Decompression latency.
Definition at line 83 of file super_blk.cc.
References _decompressionLatency.
Referenced by BaseCache::updateCompressionData(), and ~CompressionBlk().
setSizeBits()
void CompressionBlk::setSizeBits (const std::size_t size)
Set size, in bits, of this compressed block's data.
Parameters
The compressed size.
Definition at line 71 of file super_blk.cc.
References _size.
Referenced by BaseCache::updateCompressionData(), and ~CompressionBlk().
setUncompressed()
void CompressionBlk::setUncompressed ()
Clear compression bit.
Definition at line 59 of file super_blk.cc.
References BlkCompressed, and CacheBlk::status.
Referenced by CompressedTags::insertBlock(), BaseCache::updateCompressionData(), and ~CompressionBlk().
Member Data Documentation
_decompressionLatency
Cycles CompressionBlk::_decompressionLatency private
Number of cycles needed to decompress this block.
We store it to avoid doing decompressions.
Definition at line 62 of file super_blk.hh.
Referenced by getDecompressionLatency(), and setDecompressionLatency().
_size
std::size_t CompressionBlk::_size private
Set size, in bits, of this compressed block's data.
Definition at line 56 of file super_blk.hh.
Referenced by getSizeBits(), and setSizeBits().
The documentation for this class was generated from the following files:
mem/cache/tags/super_blk.hh
mem/cache/tags/super_blk.cc