gem5: my_extension Class Reference
my_extension Class Reference
#include <my_extension.h>
Public Member Functions
my_extension ()
tlm_extension_base * clone () const
void free ()
void copy_from (tlm_extension_base const &e)
my_extension ()
tlm_extension_base * clone () const
void free ()
void copy_from (tlm_extension_base const &e)
my_extension ()
tlm_extension_base * clone () const
void free ()
void copy_from (tlm_extension_base const &e)
Public Member Functions inherited from tlm::tlm_extension< my_extension >
virtual void copy_from (tlm_extension_base const &ext)=0
virtual ~tlm_extension ()
Public Attributes
int m_data
Additional Inherited Members
Static Public Attributes inherited from tlm::tlm_extension< my_extension >
static const unsigned int ID
Protected Member Functions inherited from tlm::tlm_extension_base
virtual ~tlm_extension_base ()
Static Protected Member Functions inherited from tlm::tlm_extension_base
static unsigned int register_extension (const std::type_info &)
Detailed Description
Definition at line 26 of file my_extension.h.
Constructor & Destructor Documentation
my_extension() [1/3]
my_extension::my_extension () inline
Definition at line 30 of file my_extension.h.
Referenced by clone().
my_extension() [2/3]
my_extension::my_extension () inline
Definition at line 30 of file my_extension.h.
my_extension() [3/3]
my_extension::my_extension () inline
Definition at line 30 of file my_extension.h.
Member Function Documentation
clone() [1/3]
tlm_extension_base* my_extension::clone () const inline virtual
Implements tlm::tlm_extension< my_extension >.
Definition at line 33 of file my_extension.h.
References my_extension().
clone() [2/3]
tlm_extension_base* my_extension::clone () const inline virtual
Implements tlm::tlm_extension< my_extension >.
Definition at line 33 of file my_extension.h.
References my_extension().
clone() [3/3]
tlm_extension_base* my_extension::clone () const inline virtual
Implements tlm::tlm_extension< my_extension >.
Definition at line 33 of file my_extension.h.
References my_extension().
copy_from() [1/3]
void my_extension::copy_from (tlm_extension_base const & e) inline
Definition at line 41 of file my_extension.h.
References ArmISA::e, m_data, and sc_assert.
copy_from() [2/3]
void my_extension::copy_from (tlm_extension_base const & e) inline
Definition at line 41 of file my_extension.h.
References ArmISA::e, m_data, and sc_assert.
copy_from() [3/3]
void my_extension::copy_from (tlm_extension_base const & e) inline
Definition at line 41 of file my_extension.h.
References ArmISA::e, m_data, and sc_assert.
free() [1/3]
void my_extension::free () inline virtual
Reimplemented from tlm::tlm_extension_base.
Definition at line 37 of file my_extension.h.
free() [2/3]
void my_extension::free () inline virtual
Reimplemented from tlm::tlm_extension_base.
Definition at line 37 of file my_extension.h.
free() [3/3]
void my_extension::free () inline virtual
Reimplemented from tlm::tlm_extension_base.
Definition at line 37 of file my_extension.h.
Member Data Documentation
m_data
int my_extension::m_data
Definition at line 47 of file my_extension.h.
Referenced by copy_from(), SimpleLTTarget_ext::myGetDMIPtr(), SimpleLTTarget_ext::myNBTransport(), and SimpleLTInitiator_ext::run().
The documentation for this class was generated from the following file:
systemc/tests/tlm/static_extensions/ext2gp/my_extension.h