gem5: ReplaceableEntry Class Reference
ReplaceableEntry Class Reference
A replaceable entry is a basic entry in a 2d table-like structure that needs to have replacement functionality.
#include <replaceable_entry.hh>
Public Member Functions
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Protected Attributes
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
A replaceable entry is a basic entry in a 2d table-like structure that needs to have replacement functionality.
This entry is located in a specific row and column of the table (set and way in cache nomenclature), which are stored within the entry itself.
It contains the replacement data pointer, which must be instantiated by the replacement policy before being used.
See also
Replacement Policies
Definition at line 53 of file replaceable_entry.hh.
Constructor & Destructor Documentation
ReplaceableEntry()
ReplaceableEntry::ReplaceableEntry () default
~ReplaceableEntry()
virtual ReplaceableEntry::~ReplaceableEntry () virtual default
Member Function Documentation
getSet()
uint32_t ReplaceableEntry::getSet () const inline
Get set number.
Returns
The set to which this entry belongs.
Definition at line 94 of file replaceable_entry.hh.
Referenced by StridePrefetcher::PCTable::findVictim(), CacheBlk::print(), SetAssociative::regenerateAddr(), SkewedAssociative::regenerateAddr(), and CacheMemory::setMRU().
getWay()
uint32_t ReplaceableEntry::getWay () const inline
Get way number.
Returns
The way to which this entry belongs.
Definition at line 101 of file replaceable_entry.hh.
Referenced by StridePrefetcher::PCTable::findVictim(), CacheBlk::print(), SkewedAssociative::regenerateAddr(), and CacheMemory::setMRU().
setPosition()
virtual void ReplaceableEntry::setPosition (const uint32_t set, const uint32_t way) inline virtual
Set both the set and way.
Should be called only once.
Parameters
set The set of this entry.
way The way of this entry.
Reimplemented in SectorBlk.
Definition at line 83 of file replaceable_entry.hh.
Referenced by BaseIndexingPolicy::setEntry(), SectorBlk::setPosition(), FALRU::tagsInit(), and SectorBlk::~SectorBlk().
Member Data Documentation
_set
uint32_t ReplaceableEntry::_set protected
Set to which this entry belongs.
Definition at line 59 of file replaceable_entry.hh.
_way
uint32_t ReplaceableEntry::_way protected
Way (relative position within the set) to which this entry belongs.
Definition at line 64 of file replaceable_entry.hh.
replacementData
std::shared_ptr<ReplacementData> ReplaceableEntry::replacementData
Replacement data associated to this entry.
It must be instantiated by the replacement policy before being used.
Definition at line 74 of file replaceable_entry.hh.
Referenced by BaseSetAssoc::accessBlock(), SectorTags::accessBlock(), StridePrefetcher::calculatePrefetch(), SecondChanceRP::getVictim(), SectorTags::insertBlock(), BaseSetAssoc::insertBlock(), BaseSetAssoc::invalidate(), SectorTags::invalidate(), CompressedTags::tagsInit(), BaseSetAssoc::tagsInit(), and SectorTags::tagsInit().
The documentation for this class was generated from the following file:
mem/cache/replacement_policies/replaceable_entry.hh