gem5: SimpleLTInitiator3_dmi Class Reference
SimpleLTInitiator3_dmi Class Reference
#include <SimpleLTInitiator3_DMI.h>
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_dmi dmi_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm_utils::simple_initiator_socket< SimpleLTInitiator3_dmi > initiator_socket_type
Public Member Functions
SC_HAS_PROCESS (SimpleLTInitiator3_dmi)
SimpleLTInitiator3_dmi (sc_core::sc_module_name name, unsigned int nrOfTransactions=0x5, unsigned int baseAddress=0x0)
bool initTransaction (transaction_type &trans)
void logStartTransation (transaction_type &trans)
void logEndTransaction (transaction_type &trans)
std::pair< dmi_type, bool > & getDMIData (const transaction_type &trans)
void run ()
void invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range)
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Attributes
initiator_socket_type socket
Private Attributes
std::pair< dmi_type, bool > mDMIDataReads
std::pair< dmi_type, bool > mDMIDataWrites
sc_core::sc_event mEndEvent
unsigned int mNrOfTransactions
unsigned int mBaseAddress
unsigned int mTransactionCount
unsigned int mData
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
Definition at line 42 of file SimpleLTInitiator3_DMI.h.
Member Typedef Documentation
dmi_type
typedef tlm::tlm_dmi SimpleLTInitiator3_dmi::dmi_type
Definition at line 46 of file SimpleLTInitiator3_DMI.h.
initiator_socket_type
typedef tlm_utils::simple_initiator_socket<SimpleLTInitiator3_dmi> SimpleLTInitiator3_dmi::initiator_socket_type
Definition at line 49 of file SimpleLTInitiator3_DMI.h.
phase_type
typedef tlm::tlm_phase SimpleLTInitiator3_dmi::phase_type
Definition at line 47 of file SimpleLTInitiator3_DMI.h.
sync_enum_type
typedef tlm::tlm_sync_enum SimpleLTInitiator3_dmi::sync_enum_type
Definition at line 48 of file SimpleLTInitiator3_DMI.h.
transaction_type
typedef tlm::tlm_generic_payload SimpleLTInitiator3_dmi::transaction_type
Definition at line 45 of file SimpleLTInitiator3_DMI.h.
Constructor & Destructor Documentation
SimpleLTInitiator3_dmi()
SimpleLTInitiator3_dmi::SimpleLTInitiator3_dmi (sc_core::sc_module_name name, unsigned int nrOfTransactions = 0x5, unsigned int baseAddress = 0x0) inline
Definition at line 56 of file SimpleLTInitiator3_DMI.h.
References invalidate_direct_mem_ptr(), mDMIDataReads, mDMIDataWrites, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_invalidate_direct_mem_ptr(), run(), and SC_THREAD.
Member Function Documentation
getDMIData()
std::pair<dmi_type, bool>& SimpleLTInitiator3_dmi::getDMIData (const transaction_type & trans) inline
Definition at line 132 of file SimpleLTInitiator3_DMI.h.
References tlm::tlm_generic_payload::get_command(), mDMIDataReads, mDMIDataWrites, and tlm::TLM_READ_COMMAND.
Referenced by run().
initTransaction()
bool SimpleLTInitiator3_dmi::initTransaction (transaction_type & trans) inline
Definition at line 76 of file SimpleLTInitiator3_DMI.h.
References mBaseAddress, mData, mNrOfTransactions, mTransactionCount, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_command(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), tlm::tlm_generic_payload::set_dmi_allowed(), tlm::tlm_generic_payload::set_response_status(), tlm::tlm_generic_payload::set_streaming_width(), tlm::TLM_INCOMPLETE_RESPONSE, tlm::TLM_READ_COMMAND, and tlm::TLM_WRITE_COMMAND.
Referenced by run().
invalidate_direct_mem_ptr()
void SimpleLTInitiator3_dmi::invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range) inline
Definition at line 219 of file SimpleLTInitiator3_DMI.h.
References mDMIDataReads, and mDMIDataWrites.
Referenced by SimpleLTInitiator3_dmi().
logEndTransaction()
void SimpleLTInitiator3_dmi::logEndTransaction (transaction_type & trans) inline
Definition at line 117 of file SimpleLTInitiator3_DMI.h.
References tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_response_status(), mData, sc_core::sc_object::name(), sc_core::sc_time_stamp(), tlm::TLM_OK_RESPONSE, and tlm::TLM_READ_COMMAND.
Referenced by run().
logStartTransation()
void SimpleLTInitiator3_dmi::logStartTransation (transaction_type & trans) inline
Definition at line 102 of file SimpleLTInitiator3_DMI.h.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), mData, sc_core::sc_object::name(), sc_core::sc_time_stamp(), and tlm::TLM_WRITE_COMMAND.
Referenced by run().
run()
void SimpleLTInitiator3_dmi::run () inline
Definition at line 142 of file SimpleLTInitiator3_DMI.h.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), getDMIData(), initTransaction(), logEndTransaction(), logStartTransation(), mData, sc_core::SC_ZERO_TIME, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_response_status(), ArmISA::t, tlm::TLM_OK_RESPONSE, tlm::TLM_WRITE_COMMAND, and sc_core::sc_module::wait().
Referenced by SimpleLTInitiator3_dmi().
SC_HAS_PROCESS()
SimpleLTInitiator3_dmi::SC_HAS_PROCESS (SimpleLTInitiator3_dmi)
Member Data Documentation
mBaseAddress
unsigned int SimpleLTInitiator3_dmi::mBaseAddress private
Definition at line 239 of file SimpleLTInitiator3_DMI.h.
Referenced by initTransaction().
mData
unsigned int SimpleLTInitiator3_dmi::mData private
Definition at line 241 of file SimpleLTInitiator3_DMI.h.
Referenced by initTransaction(), logEndTransaction(), logStartTransation(), and run().
mDMIDataReads
std::pair<dmi_type, bool> SimpleLTInitiator3_dmi::mDMIDataReads private
Definition at line 234 of file SimpleLTInitiator3_DMI.h.
Referenced by getDMIData(), invalidate_direct_mem_ptr(), and SimpleLTInitiator3_dmi().
mDMIDataWrites
std::pair<dmi_type, bool> SimpleLTInitiator3_dmi::mDMIDataWrites private
Definition at line 235 of file SimpleLTInitiator3_DMI.h.
Referenced by getDMIData(), invalidate_direct_mem_ptr(), and SimpleLTInitiator3_dmi().
mEndEvent
sc_core::sc_event SimpleLTInitiator3_dmi::mEndEvent private
Definition at line 237 of file SimpleLTInitiator3_DMI.h.
mNrOfTransactions
unsigned int SimpleLTInitiator3_dmi::mNrOfTransactions private
Definition at line 238 of file SimpleLTInitiator3_DMI.h.
Referenced by initTransaction().
mTransactionCount
unsigned int SimpleLTInitiator3_dmi::mTransactionCount private
Definition at line 240 of file SimpleLTInitiator3_DMI.h.
Referenced by initTransaction().
socket
initiator_socket_type SimpleLTInitiator3_dmi::socket
Definition at line 52 of file SimpleLTInitiator3_DMI.h.
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleLTInitiator3_DMI.h