gem5: DmaPort Class Reference
DmaPort Class Reference
#include <dma_device.hh>
Classes
struct DmaReqState
Public Member Functions
DmaPort (ClockedObject *dev, System *s, uint32_t sid=0, uint32_t ssid=0)
RequestPtr dmaAction (Packet::Command cmd, Addr addr, int size, Event *event, uint8_t *data, Tick delay, Request::Flags flag=0)
RequestPtr dmaAction (Packet::Command cmd, Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay, Request::Flags flag=0)
bool dmaPending () const
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Attributes
ClockedObject *const device
The device that owns this port.
System *const sys
The system that device/port are in.
const MasterID masterId
Id for all requests.
Protected Member Functions
bool recvTimingResp (PacketPtr pkt) override
Receive a timing response from the peer.
void recvReqRetry () override
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
void queueDma (PacketPtr pkt)
Protected Member Functions inherited from MasterPort
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
std::deque< PacketPtr > transmitList
Use a deque as we never do any insertion or removal in the middle.
EventFunctionWrapper sendEvent
Event used to schedule a future sending from the transmit list.
uint32_t pendingCount
Number of outstanding packets the dma port has.
bool inRetry
If the port is currently waiting for a retry before it can send whatever it is that it's sending.
const uint32_t defaultSid
Default streamId.
const uint32_t defaultSSid
Default substreamId.
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Private Member Functions
void trySendTimingReq ()
Take the first packet of the transmit list and attempt to send it as a timing request.
void sendDma ()
For timing, attempt to send the first item on the transmit list, and if it is successful and there are more packets waiting, then schedule the sending of the next packet.
void handleResp (PacketPtr pkt, Tick delay=0)
Handle a response packet by updating the corresponding DMA request state to reflect the bytes received, and also update the pending request counter.
Detailed Description
Definition at line 59 of file dma_device.hh.
Constructor & Destructor Documentation
DmaPort()
DmaPort::DmaPort (ClockedObject * dev, System * s, uint32_t sid = 0, uint32_t ssid = 0)
Definition at line 57 of file dma_device.cc.
References defaultSid, defaultSSid, inRetry, pendingCount, and sendDma().
Member Function Documentation
dmaAction() [1/2]
RequestPtr DmaPort::dmaAction (Packet::Command cmd, Addr addr, int size, Event * event, uint8_t * data, Tick delay, Request::Flags flag = 0)
Definition at line 202 of file dma_device.cc.
Referenced by DmaDevice::dmaRead(), DmaDevice::dmaWrite(), CopyEngine::CopyEngineChannel::fetchDescriptor(), ArmISA::TableWalker::fetchDescriptor(), CopyEngine::CopyEngineChannel::fetchNextAddr(), Pl111::fillFifo(), ArmISA::Stage2MMU::Stage2Translation::finish(), CopyEngine::CopyEngineChannel::readCopyBytes(), UFSHostDevice::readDevice(), DmaReadFifo::resumeFillTiming(), CopyEngine::CopyEngineChannel::writeCompletionStatus(), CopyEngine::CopyEngineChannel::writeCopyBytes(), and UFSHostDevice::writeDevice().
dmaAction() [2/2]
RequestPtr DmaPort::dmaAction (Packet::Command cmd, Addr addr, int size, Event * event, uint8_t * data, uint32_t sid, uint32_t ssid, Tick delay, Request::Flags flag = 0)
Definition at line 153 of file dma_device.cc.
References System::cacheLineSize(), Packet::dataStatic(), ContextSwitchTaskId::DMA, ChunkGenerator::done(), DPRINTF, Event::scheduled(), Packet::senderState, and PioDevice::sys.
dmaPending()
bool DmaPort::dmaPending () const inline
Definition at line 164 of file dma_device.hh.
References drain().
Referenced by DmaDevice::dmaPending().
drain()
DrainState DmaPort::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 135 of file dma_device.cc.
References DPRINTF, Drained, and Draining.
Referenced by dmaPending().
handleResp()
void DmaPort::handleResp (PacketPtr pkt, Tick delay = 0) private
Handle a response packet by updating the corresponding DMA request state to reflect the bytes received, and also update the pending request counter.
If the DMA request that this packet is part of is complete, then signal the completion event if present, potentially with a delay added to it.
Parameters
pkt Response packet to handler
delay Additional delay for scheduling the completion event
Definition at line 68 of file dma_device.cc.
References Packet::cmdString(), curTick(), device, ContextSwitchTaskId::DMA, DPRINTF, Packet::getAddr(), Packet::isResponse(), pendingCount, Packet::req, EventManager::schedule(), Packet::senderState, and Drainable::signalDrainDone().
Referenced by recvTimingResp().
queueDma()
void DmaPort::queueDma (PacketPtr pkt) protected
Definition at line 210 of file dma_device.cc.
recvReqRetry()
void DmaPort::recvReqRetry () override protected virtual
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Implements TimingRequestProtocol.
Definition at line 146 of file dma_device.cc.
recvTimingResp()
bool DmaPort::recvTimingResp (PacketPtr pkt) override protected virtual
Receive a timing response from the peer.
Implements TimingRequestProtocol.
Definition at line 111 of file dma_device.cc.
References Packet::cacheResponding(), handleResp(), Packet::hasSharers(), and Packet::req.
sendDma()
void DmaPort::sendDma () private
For timing, attempt to send the first item on the transmit list, and if it is successful and there are more packets waiting, then schedule the sending of the next packet.
For atomic, simply send and process everything on the transmit list.
Definition at line 249 of file dma_device.cc.
References ContextSwitchTaskId::DMA, DPRINTF, System::isAtomicMode(), System::isTimingMode(), panic, Packet::req, ArmISA::sendEvent(), and PioDevice::sys.
Referenced by DmaPort().
trySendTimingReq()
void DmaPort::trySendTimingReq () private
Take the first packet of the transmit list and attempt to send it as a timing request.
If it is successful, schedule the sending of the next packet, otherwise remember that we are waiting for a retry.
Definition at line 220 of file dma_device.cc.
References Packet::cmdString(), ContextSwitchTaskId::DMA, DPRINTF, Packet::getAddr(), and ArmISA::sendEvent().
Member Data Documentation
defaultSid
const uint32_t DmaPort::defaultSid protected
Default streamId.
Definition at line 138 of file dma_device.hh.
Referenced by DmaPort().
defaultSSid
const uint32_t DmaPort::defaultSSid protected
Default substreamId.
Definition at line 141 of file dma_device.hh.
Referenced by DmaPort().
device
ClockedObject* const DmaPort::device
The device that owns this port.
Definition at line 114 of file dma_device.hh.
Referenced by handleResp().
inRetry
bool DmaPort::inRetry protected
If the port is currently waiting for a retry before it can send whatever it is that it's sending.
Definition at line 135 of file dma_device.hh.
Referenced by DmaPort().
masterId
const MasterID DmaPort::masterId
Id for all requests.
Definition at line 121 of file dma_device.hh.
pendingCount
uint32_t DmaPort::pendingCount protected
Number of outstanding packets the dma port has.
Definition at line 131 of file dma_device.hh.
Referenced by DmaPort(), and handleResp().
sendEvent
EventFunctionWrapper DmaPort::sendEvent protected
Event used to schedule a future sending from the transmit list.
Definition at line 128 of file dma_device.hh.
sys
System* const DmaPort::sys
The system that device/port are in.
This is used to select which mode we are currently operating in.
Definition at line 118 of file dma_device.hh.
Referenced by DmaDevice::cacheBlockSize(), DmaReadFifo::resumeFill(), and DmaReadFifo::resumeFillFunctional().
transmitList
std::deque<PacketPtr> DmaPort::transmitList protected
Use a deque as we never do any insertion or removal in the middle.
Definition at line 125 of file dma_device.hh.
The documentation for this class was generated from the following files:
dev/dma_device.hh
dev/dma_device.cc