gem5: tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF > Class Template Reference abstract
#include <initiator_socket.hh>
Public Member Functions
virtual ~tlm_base_target_socket_b ()
virtual sc_core::sc_port_b< BW_IF > & get_base_port ()=0
virtual sc_core::sc_export< FW_IF > & get_base_export ()=0
virtual FW_IF & get_base_interface ()=0
Detailed Description
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>>
class tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >
Definition at line 48 of file initiator_socket.hh.
Constructor & Destructor Documentation
~tlm_base_target_socket_b()
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >::~tlm_base_target_socket_b () inline virtual
Definition at line 36 of file target_socket.hh.
Member Function Documentation
get_base_export()
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_export<FW_IF>& tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_export () pure virtual
Implemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >, tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Referenced by tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), and tlm::tlm_base_target_socket_b< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES > >::~tlm_base_target_socket_b().
get_base_interface()
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual FW_IF& tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_interface () pure virtual
Implemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >, tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Referenced by tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), and tlm::tlm_base_target_socket_b< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES > >::~tlm_base_target_socket_b().
get_base_port()
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>> virtual sc_core::sc_port_b<BW_IF>& tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >::get_base_port () pure virtual
Implemented in tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Referenced by tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), and tlm::tlm_base_target_socket_b< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES > >::~tlm_base_target_socket_b().
The documentation for this class was generated from the following files:
systemc/ext/tlm_core/2/sockets/initiator_socket.hh
systemc/ext/tlm_core/2/sockets/target_socket.hh