gem5: WriteQueueEntry Class Reference
WriteQueueEntry Class Reference
Write queue entry.
#include <write_queue_entry.hh>
Classes
class TargetList
Public Types
typedef std::list< WriteQueueEntry * > List
A list of write queue entriess.
typedef List::iterator Iterator
WriteQueueEntry list iterator.
Public Member Functions
bool sendPacket (BaseCache &cache) override
Send this queue entry as a downstream packet, with the exact behaviour depending on the specific entry type.
WriteQueueEntry ()
A simple constructor.
void allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order)
Allocate a miss to this entry.
void deallocate ()
Mark this entry as free.
int getNumTargets () const
Returns the current number of allocated targets.
bool hasTargets () const
Returns true if there are targets left.
Target * getTarget () override
Returns a reference to the first target.
void popTarget ()
Pop first target.
bool trySatisfyFunctional (PacketPtr pkt)
void print (std::ostream &os, int verbosity=0, const std::string &prefix="") const override
Prints the contents of this MSHR for debugging.
std::string print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
bool matchBlockAddr (const Addr addr, const bool is_secure) const override
Check if entry corresponds to the one being looked for.
bool matchBlockAddr (const PacketPtr pkt) const override
Check if entry contains a packet that corresponds to the one being looked for.
bool conflictAddr (const QueueEntry *entry) const override
Check if given entry's packets conflict with this' entries packets.
Public Member Functions inherited from QueueEntry
QueueEntry ()
bool isUncacheable () const
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Public Member Functions inherited from Printable
Printable ()
virtual ~Printable ()
Private Attributes
Iterator readyIter
Pointer to this entry on the ready list.
Iterator allocIter
Pointer to this entry on the allocated list.
TargetList targets
List of all requests that match the address.
Friends
template<typename Entry >
class Queue
Consider the queues friends to avoid making everything public.
class WriteQueue
Additional Inherited Members
Public Attributes inherited from QueueEntry
bool inService
True if the entry has been sent downstream.
Counter order
Order number assigned to disambiguate writes and misses.
Addr blkAddr
Block aligned address.
unsigned blkSize
Block size of the cache.
bool isSecure
True if the entry targets the secure memory space.
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Protected Attributes inherited from QueueEntry
Tick readyTime
Tick when ready to issue.
bool _isUncacheable
True if the entry is uncacheable.
Detailed Description
Write queue entry.
Definition at line 68 of file write_queue_entry.hh.
Member Typedef Documentation
Iterator
typedef List::iterator WriteQueueEntry::Iterator
WriteQueueEntry list iterator.
Definition at line 93 of file write_queue_entry.hh.
List
typedef std::list<WriteQueueEntry *> WriteQueueEntry::List
A list of write queue entriess.
Definition at line 91 of file write_queue_entry.hh.
Constructor & Destructor Documentation
WriteQueueEntry()
WriteQueueEntry::WriteQueueEntry () inline
A simple constructor.
Definition at line 117 of file write_queue_entry.hh.
References allocate(), and deallocate().
Member Function Documentation
allocate()
void WriteQueueEntry::allocate (Addr blk_addr, unsigned blk_size, PacketPtr pkt, Tick when_ready, Counter _order)
Allocate a miss to this entry.
Parameters
blk_addr The address of the block.
blk_size The number of bytes to request.
pkt The original write.
when_ready When should the write be sent out.
_order The logical order of this write.
Definition at line 91 of file write_queue_entry.cc.
References QueueEntry::_isUncacheable, WriteQueueEntry::TargetList::add(), QueueEntry::blkAddr, QueueEntry::blkSize, Packet::cmd, QueueEntry::inService, Packet::isEviction(), QueueEntry::isSecure, Packet::isSecure(), Packet::isWrite(), Packet::matchBlockAddr(), QueueEntry::order, panic_if, QueueEntry::readyTime, Packet::req, targets, and MemCmd::WriteClean.
Referenced by WriteQueue::allocate(), and WriteQueueEntry().
conflictAddr()
bool WriteQueueEntry::conflictAddr (const QueueEntry * entry) const override virtual
Check if given entry's packets conflict with this' entries packets.
Parameters
entry Other entry to compare against.
Returns
True if entry matches given information.
Implements QueueEntry.
Definition at line 162 of file write_queue_entry.cc.
References QueueEntry::blkAddr, hasTargets(), QueueEntry::isSecure, and QueueEntry::matchBlockAddr().
Referenced by popTarget().
deallocate()
void WriteQueueEntry::deallocate ()
Mark this entry as free.
Definition at line 121 of file write_queue_entry.cc.
References QueueEntry::inService, and targets.
Referenced by WriteQueueEntry().
getNumTargets()
int WriteQueueEntry::getNumTargets () const inline
Returns the current number of allocated targets.
Returns
The current number of allocated targets.
Definition at line 140 of file write_queue_entry.hh.
Referenced by BaseCache::access(), and Cache::recvTimingSnoopReq().
getTarget()
Target* WriteQueueEntry::getTarget () inline override virtual
Returns a reference to the first target.
Returns
A pointer to the first target.
Implements QueueEntry.
Definition at line 153 of file write_queue_entry.hh.
References hasTargets().
Referenced by BaseCache::access(), Cache::recvTimingSnoopReq(), and BaseCache::sendWriteQueuePacket().
hasTargets()
bool WriteQueueEntry::hasTargets () const inline
Returns true if there are targets left.
Returns
true if there are targets
Definition at line 147 of file write_queue_entry.hh.
Referenced by conflictAddr(), getTarget(), and matchBlockAddr().
matchBlockAddr() [1/2]
bool WriteQueueEntry::matchBlockAddr (const Addr addr, const bool is_secure) const override virtual
Check if entry corresponds to the one being looked for.
Parameters
addr Address to match against.
is_secure Whether the target should be in secure space or not.
Returns
True if entry matches given information.
Implements QueueEntry.
Definition at line 148 of file write_queue_entry.cc.
References QueueEntry::blkAddr, hasTargets(), and QueueEntry::isSecure.
Referenced by popTarget().
matchBlockAddr() [2/2]
bool WriteQueueEntry::matchBlockAddr (const PacketPtr pkt) const override virtual
Check if entry contains a packet that corresponds to the one being looked for.
Parameters
pkt The packet to search for.
Returns
True if any of its targets' packets matches the given one.
Implements QueueEntry.
Definition at line 155 of file write_queue_entry.cc.
References QueueEntry::blkAddr, QueueEntry::blkSize, hasTargets(), QueueEntry::isSecure, and Packet::matchBlockAddr().
popTarget()
void WriteQueueEntry::popTarget () inline
Pop first target.
Definition at line 162 of file write_queue_entry.hh.
References addr, conflictAddr(), matchBlockAddr(), X86ISA::os, WriteQueueEntry::TargetList::print(), and WriteQueueEntry::TargetList::trySatisfyFunctional().
Referenced by WriteQueue::markInService().
print() [1/2]
void WriteQueueEntry::print (std::ostream & os, int verbosity = 0, const std::string & prefix = "") const override virtual
Prints the contents of this MSHR for debugging.
Implements Printable.
Definition at line 169 of file write_queue_entry.cc.
References QueueEntry::_isUncacheable, QueueEntry::blkAddr, QueueEntry::blkSize, ccprintf(), QueueEntry::inService, QueueEntry::isSecure, WriteQueueEntry::TargetList::print(), and targets.
print() [2/2]
std::string WriteQueueEntry::print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
Returns
string with mshr fields
Definition at line 183 of file write_queue_entry.cc.
References WriteQueueEntry::TargetList::print().
sendPacket()
bool WriteQueueEntry::sendPacket (BaseCache & cache) override virtual
Send this queue entry as a downstream packet, with the exact behaviour depending on the specific entry type.
Implements QueueEntry.
Definition at line 142 of file write_queue_entry.cc.
References BaseCache::sendWriteQueuePacket().
trySatisfyFunctional()
bool WriteQueueEntry::trySatisfyFunctional (PacketPtr pkt)
Definition at line 128 of file write_queue_entry.cc.
References QueueEntry::blkAddr, QueueEntry::blkSize, Packet::isPrint(), QueueEntry::isSecure, targets, WriteQueueEntry::TargetList::trySatisfyFunctional(), and Packet::trySatisfyFunctional().
Friends And Related Function Documentation
Queue
template<typename Entry > friend class Queue friend
Consider the queues friends to avoid making everything public.
Definition at line 75 of file write_queue_entry.hh.
WriteQueue
friend class WriteQueue friend
Definition at line 76 of file write_queue_entry.hh.
Member Data Documentation
allocIter
Iterator WriteQueueEntry::allocIter private
Pointer to this entry on the allocated list.
See also
MissQueue, WriteQueue::allocatedList
Definition at line 109 of file write_queue_entry.hh.
readyIter
Iterator WriteQueueEntry::readyIter private
Pointer to this entry on the ready list.
See also
MissQueue, WriteQueue::readyList
Definition at line 103 of file write_queue_entry.hh.
Referenced by WriteQueue::allocate().
targets
TargetList WriteQueueEntry::targets private
List of all requests that match the address.
Definition at line 112 of file write_queue_entry.hh.
Referenced by allocate(), deallocate(), print(), and trySatisfyFunctional().
The documentation for this class was generated from the following files:
mem/cache/write_queue_entry.hh
mem/cache/write_queue_entry.cc