gem5: TraceGen Class Reference
TraceGen Class Reference
The trace replay generator reads a trace file and plays back the transactions.
#include <trace_gen.hh>
Classes
class InputStream
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
struct TraceElement
This struct stores a line in the trace file.
Public Member Functions
TraceGen (SimObject &obj, MasterID master_id, Tick _duration, const std::string &trace_file, Addr addr_offset)
Create a trace generator.
void enter ()
Enter this generator state.
PacketPtr getNextPacket ()
Get the next generated packet.
void exit ()
Exit this generator state.
Tick nextPacketTick (bool elastic, Tick delay) const
Returns the tick when the next request should be generated.
Public Member Functions inherited from BaseGen
BaseGen (SimObject &obj, MasterID master_id, Tick _duration)
Create a base generator.
virtual ~BaseGen ()
std::string name () const
Get the name, useful for DPRINTFs.
Private Attributes
InputStream trace
Input stream used for reading the input trace file.
TraceElement currElement
Store the current and next element in the trace.
TraceElement nextElement
Tick tickOffset
Stores the time when the state was entered.
Addr addrOffset
Offset for memory requests.
bool traceComplete
Set to true when the trace replay for one instance of state is complete.
Additional Inherited Members
Public Attributes inherited from BaseGen
const Tick duration
Time to spend in this state.
Protected Member Functions inherited from BaseGen
PacketPtr getPacket (Addr addr, unsigned size, const MemCmd &cmd, Request::FlagsType flags=0)
Generate a new request and associated packet.
Protected Attributes inherited from BaseGen
const std::string _name
Name to use for status and debug printing.
const MasterID masterID
The MasterID used for generating requests.
Detailed Description
The trace replay generator reads a trace file and plays back the transactions.
The trace is offset with respect to the time when the state was entered.
Definition at line 63 of file trace_gen.hh.
Constructor & Destructor Documentation
TraceGen()
TraceGen::TraceGen (SimObject & obj, MasterID master_id, Tick _duration, const std::string & trace_file, Addr addr_offset) inline
Create a trace generator.
Parameters
obj SimObject owning this sequence generator
master_id MasterID related to the memory requests
_duration duration of this state before transitioning
trace_file File to read the transactions from
addr_offset Positive offset to add to trace address
Definition at line 161 of file trace_gen.hh.
References enter(), exit(), getNextPacket(), and nextPacketTick().
Member Function Documentation
enter()
void TraceGen::enter () virtual
Enter this generator state.
Implements BaseGen.
Definition at line 119 of file trace_gen.cc.
References TraceGen::TraceElement::clear(), currElement, curTick(), nextElement, ProtoInputStream::read(), tickOffset, TraceGen::InputStream::trace, and traceComplete.
Referenced by TraceGen().
exit()
void TraceGen::exit () virtual
Exit this generator state.
By default do nothing.
Reimplemented from BaseGen.
Definition at line 168 of file trace_gen.cc.
References BaseGen::name(), ProtoInputStream::reset(), TraceGen::InputStream::trace, traceComplete, and warn.
Referenced by TraceGen().
getNextPacket()
PacketPtr TraceGen::getNextPacket () virtual
Get the next generated packet.
Returns
A packet to be sent at the current tick
Implements BaseGen.
Definition at line 132 of file trace_gen.cc.
References TraceGen::TraceElement::addr, addrOffset, TraceGen::TraceElement::blocksize, TraceGen::TraceElement::clear(), TraceGen::TraceElement::cmd, currElement, DPRINTF, TraceGen::TraceElement::flags, BaseGen::getPacket(), MemCmd::isRead(), TraceGen::TraceElement::isValid(), nextElement, ProtoInputStream::read(), TraceGen::TraceElement::tick, tickOffset, TraceGen::InputStream::trace, and traceComplete.
Referenced by TraceGen().
nextPacketTick()
Tick TraceGen::nextPacketTick (bool elastic, Tick delay) const virtual
Returns the tick when the next request should be generated.
If the end of the file has been reached, it returns MaxTick to indicate that there will be no more requests.
Implements BaseGen.
Definition at line 96 of file trace_gen.cc.
References curTick(), DPRINTF, TraceGen::TraceElement::isValid(), MaxTick, nextElement, TraceGen::TraceElement::tick, tickOffset, and traceComplete.
Referenced by TraceGen().
Member Data Documentation
addrOffset
Addr TraceGen::addrOffset private
Offset for memory requests.
Used to shift the trace away from the CPU address space.
Definition at line 204 of file trace_gen.hh.
Referenced by getNextPacket().
currElement
TraceElement TraceGen::currElement private
Store the current and next element in the trace.
Definition at line 190 of file trace_gen.hh.
Referenced by enter(), and getNextPacket().
nextElement
TraceElement TraceGen::nextElement private
Definition at line 191 of file trace_gen.hh.
Referenced by enter(), getNextPacket(), and nextPacketTick().
tickOffset
Tick TraceGen::tickOffset mutable private
Stores the time when the state was entered.
This is to add an offset to the times stored in the trace file. This is mutable to allow us to change it as part of nextPacketTick.
Definition at line 198 of file trace_gen.hh.
Referenced by enter(), getNextPacket(), and nextPacketTick().
trace
InputStream TraceGen::trace private
Input stream used for reading the input trace file.
Definition at line 187 of file trace_gen.hh.
traceComplete
bool TraceGen::traceComplete private
Set to true when the trace replay for one instance of state is complete.
Definition at line 210 of file trace_gen.hh.
Referenced by enter(), exit(), getNextPacket(), and nextPacketTick().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/trace_gen.hh
cpu/testers/traffic_gen/trace_gen.cc