gem5: FALRU::CacheTracking Class Reference
FALRU::CacheTracking Class Reference
Mechanism that allows us to simultaneously collect miss statistics for multiple caches.
Public Member Functions
CacheTracking (unsigned min_size, unsigned max_size, unsigned block_size)
void init (FALRUBlk *head, FALRUBlk *tail)
Initialiaze cache blocks and the tracking mechanism.
void moveBlockToHead (FALRUBlk *blk)
Update boundaries as a block will be moved to the MRU.
void moveBlockToTail (FALRUBlk *blk)
Update boundaries as a block will be moved to the LRU.
void recordAccess (FALRUBlk *blk)
Notify of a block access.
void check (const FALRUBlk *head, const FALRUBlk *tail) const
Check that the tracking mechanism is in consistent state.
void regStats (std::string name)
Register the stats for this object.
Protected Attributes
Stats::Vector hits
Hits in each cache.
Stats::Vector misses
Misses in each cache.
Stats::Scalar accesses
Total number of accesses.
Private Attributes
const unsigned blkSize
The size of the cache block.
const unsigned minTrackedSize
The smallest cache we are tracking.
const int numTrackedCaches
The number of different size caches being tracked.
const CachesMask inAllCachesMask
A mask for all cache being tracked.
std::vector< FALRUBlk * > boundaries
Array of pointers to blocks at the cache boundaries.
Detailed Description
Mechanism that allows us to simultaneously collect miss statistics for multiple caches.
Currently, we keep track of caches from a set minimum size of interest up to the actual cache size.
Definition at line 282 of file fa_lru.hh.
Constructor & Destructor Documentation
CacheTracking()
FALRU::CacheTracking::CacheTracking (unsigned min_size, unsigned max_size, unsigned block_size) inline
Definition at line 285 of file fa_lru.hh.
References fatal_if, Stats::init, and name().
Member Function Documentation
check()
void FALRU::CacheTracking::check (const FALRUBlk * head, const FALRUBlk * tail) const
Check that the tracking mechanism is in consistent state.
Iterate from the head (MRU) to the tail (LRU) of the list of blocks and assert the inCachesMask and the boundaries are in consistent state.
Parameters
head the MRU block of the actual cache
head the LRU block of the actual cache
Definition at line 293 of file fa_lru.cc.
References BaseTags::blkSize, FALRU::head, FALRUBlk::inCachesMask, ArmISA::j, FALRUBlk::next, and panic_if.
Referenced by FALRU::moveToHead(), and FALRU::moveToTail().
init()
void FALRU::CacheTracking::init (FALRUBlk * head, FALRUBlk * tail)
Initialiaze cache blocks and the tracking mechanism.
All blocks in the cache need to be initialized once.
Parameters
blk the MRU block
blk the LRU block
Definition at line 321 of file fa_lru.cc.
References BaseTags::blkSize, FALRU::head, FALRUBlk::inCachesMask, ArmISA::j, and FALRUBlk::next.
Referenced by FALRU::tagsInit().
moveBlockToHead()
void FALRU::CacheTracking::moveBlockToHead (FALRUBlk * blk)
Update boundaries as a block will be moved to the MRU.
For all caches that didn't fit the block before moving it, we move their boundaries one block closer to the MRU. We also update InCacheMasks as neccessary.
Parameters
blk the block that will be moved to the head
Definition at line 348 of file fa_lru.cc.
References ArmISA::i, FALRUBlk::inCachesMask, and FALRUBlk::prev.
Referenced by FALRU::moveToHead().
moveBlockToTail()
void FALRU::CacheTracking::moveBlockToTail (FALRUBlk * blk)
Update boundaries as a block will be moved to the LRU.
For all caches that fitted the block before moving it, we move their boundaries one block closer to the LRU. We also update InCacheMasks as neccessary.
Parameters
blk the block that will be moved to the head
Definition at line 374 of file fa_lru.cc.
References ArmISA::i, FALRUBlk::inCachesMask, and FALRUBlk::next.
Referenced by FALRU::moveToTail().
recordAccess()
void FALRU::CacheTracking::recordAccess (FALRUBlk * blk)
Notify of a block access.
This should be called every time a block is accessed and it updates statistics. If the input block is nullptr then we treat the access as a miss. The block's InCacheMask determines the caches in which the block fits.
Parameters
blk the block to record the access for
Definition at line 399 of file fa_lru.cc.
References ArmISA::i, FALRUBlk::inCachesMask, and CacheBlk::isValid().
Referenced by FALRU::accessBlock().
regStats()
void FALRU::CacheTracking::regStats (std::string name)
Register the stats for this object.
Definition at line 432 of file fa_lru.cc.
References ArmISA::i, and printSize().
Referenced by FALRU::regStats().
Member Data Documentation
blkSize
const unsigned FALRU::CacheTracking::blkSize private
The size of the cache block.
Definition at line 363 of file fa_lru.hh.
boundaries
std::vector<FALRUBlk*> FALRU::CacheTracking::boundaries private
Array of pointers to blocks at the cache boundaries.
Definition at line 371 of file fa_lru.hh.
inAllCachesMask
const CachesMask FALRU::CacheTracking::inAllCachesMask private
A mask for all cache being tracked.
Definition at line 369 of file fa_lru.hh.
minTrackedSize
const unsigned FALRU::CacheTracking::minTrackedSize private
The smallest cache we are tracking.
Definition at line 365 of file fa_lru.hh.
numTrackedCaches
const int FALRU::CacheTracking::numTrackedCaches private
The number of different size caches being tracked.
Definition at line 367 of file fa_lru.hh.
The documentation for this class was generated from the following files:
mem/cache/tags/fa_lru.hh
mem/cache/tags/fa_lru.cc