gem5: KvmVM Class Reference
KvmVM Class Reference
KVM VM container.
#include <vm.hh>
Classes
class MemorySlot
Structures tracking memory slots.
struct MemSlot
Public Member Functions
KvmVM (KvmVMParams *params)
virtual ~KvmVM ()
void notifyFork ()
Notify a child process of a fork.
void setTSSAddress (Addr tss_address)
Setup a shared three-page memory region used by the internals of KVM.
void createIRQChip ()
Create an in-kernel interrupt controller.
void setIRQLine (uint32_t irq, bool high)
Set the status of an IRQ line using KVM_IRQ_LINE.
bool hasKernelIRQChip () const
Is in-kernel IRQ chip emulation enabled?
void enableKernelIRQChip ()
Tell the VM and VCPUs to use an in-kernel IRQ chip for interrupt delivery.
const MemSlot allocMemSlot (uint64_t size)
Allocate a memory slot within the VM.
void setupMemSlot (const MemSlot slot, void *host_addr, Addr guest_addr, uint32_t flags)
Setup a region of physical memory in the guest.
void disableMemSlot (const MemSlot slot)
Disable a memory slot.
void freeMemSlot (const MemSlot slot)
Free a previously allocated memory slot.
int createDevice (uint32_t type, uint32_t flags=0)
Create an in-kernel device model.
void setSystem (System *s)
Initialize system pointer.
long contextIdToVCpuId (ContextID ctx) const
Get the VCPUID for a given context.
void coalesceMMIO (Addr start, int size)
Request coalescing MMIO for a memory range.
void coalesceMMIO (const AddrRange &range)
Request coalescing MMIO for a memory range.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
Kvm * kvm
Global KVM interface.
Protected Member Functions
void cpuStartup ()
VM CPU initialization code.
void delayedStartup ()
Delayed initialization, executed once before the first CPU starts.
int createVCPU (long vcpuID)
Create a new vCPU within a VM.
long allocVCPUID ()
Allocate a new vCPU ID within the VM.
int ioctl (int request, long p1) const
KVM VM ioctl interface.
int ioctl (int request, void *p1) const
int ioctl (int request) const
void setUserMemoryRegion (uint32_t slot, void *host_addr, Addr guest_addr, uint64_t len, uint32_t flags)
Setup a region of physical memory in the guest.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Member Functions
KvmVM (const KvmVM &vm)
KvmVM & operator= (const KvmVM &vm)
Private Attributes
System * system
int vmFD
KVM VM file descriptor.
bool started
Has delayedStartup() already been called?
bool _hasKernelIRQChip
Do we have in-kernel IRQ-chip emulation enabled?
long nextVCPUID
Next unallocated vCPU ID.
std::vector< MemorySlot > memorySlots
uint32_t maxMemorySlot
Friends
class BaseKvmCPU
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
KVM VM container.
A KVM VM container normally contains all the CPUs in a shared memory machine. The VM container handles things like physical memory and to some extent interrupts. Normally, the VM API is only used for interrupts when the PIC is emulated by the kernel, which is a feature we do not use. However, some architectures (notably ARM) use the VM interface to deliver interrupts to specific CPUs as well.
VM initialization is a bit different from that of other SimObjects. When we initialize the VM, we discover all physical memory mappings in the system. Since AbstractMem::unserialize re-maps the guests memory, we need to make sure that this is done after the memory has been re-mapped, but before the vCPUs are initialized (KVM requires memory mappings to be setup before CPUs can be created). Normally, we would just initialize the VM in init() or startup(), however, we can not use init() since this is called before AbstractMem::unserialize() and we can not use startup() since it must be called before BaseKvmCPU::startup() and the simulator framework does not guarantee call order. We therefore call cpuStartup() from BaseKvmCPU::startup() instead and execute the initialization code once when the first CPU in the VM is starting.
Definition at line 291 of file vm.hh.
Constructor & Destructor Documentation
KvmVM() [1/2]
KvmVM::KvmVM (KvmVMParams * params)
Definition at line 294 of file vm.cc.
References Kvm::capNumMemSlots(), coalesceMMIO(), ArmISA::i, kvm, and maxMemorySlot.
Referenced by ioctl().
~KvmVM()
KvmVM::~KvmVM () virtual
Definition at line 310 of file vm.cc.
References kvm, and vmFD.
KvmVM() [2/2]
KvmVM::KvmVM (const KvmVM & vm) private
Member Function Documentation
allocMemSlot()
const KvmVM::MemSlot KvmVM::allocMemSlot (uint64_t size)
Allocate a memory slot within the VM.
Definition at line 379 of file vm.cc.
References KvmVM::MemorySlot::active, maxMemorySlot, memorySlots, panic, KvmVM::MemorySlot::size, and KvmVM::MemorySlot::slot.
Referenced by delayedStartup().
allocVCPUID()
long KvmVM::allocVCPUID () protected
Allocate a new vCPU ID within the VM.
The returned vCPU ID is guaranteed to be unique within the VM. New IDs are allocated sequentially starting from 0.
Returns
ID of the new vCPU
Definition at line 560 of file vm.cc.
References ioctl(), nextVCPUID, and panic.
coalesceMMIO() [1/2]
void KvmVM::coalesceMMIO (Addr start, int size)
Request coalescing MMIO for a memory range.
Parameters
start Physical start address in guest
size Size of the MMIO region
Definition at line 464 of file vm.cc.
References DPRINTF, ioctl(), and panic.
Referenced by coalesceMMIO(), and KvmVM().
coalesceMMIO() [2/2]
void KvmVM::coalesceMMIO (const AddrRange & range)
Request coalescing MMIO for a memory range.
Parameters
range Coalesced MMIO range
Definition at line 458 of file vm.cc.
References coalesceMMIO(), AddrRange::size(), and AddrRange::start().
contextIdToVCpuId()
long KvmVM::contextIdToVCpuId (ContextID ctx) const
Get the VCPUID for a given context.
Definition at line 540 of file vm.cc.
References ThreadContext::getCpuPtr(), System::getThreadContext(), and system.
Referenced by KvmKernelGicV2::readCpu(), KvmKernelGicV2::readDistributor(), KvmKernelGicV2::writeCpu(), and KvmKernelGicV2::writeDistributor().
cpuStartup()
void KvmVM::cpuStartup () protected
VM CPU initialization code.
This method is called from BaseKvmCPU::startup() when a CPU in the VM executes its BaseKvmCPU::startup() method. The first time method is executed on a VM, it calls the delayedStartup() method.
Definition at line 334 of file vm.cc.
References delayedStartup(), and started.
Referenced by BaseKvmCPU::startup().
createDevice()
int KvmVM::createDevice (uint32_t type, uint32_t flags = 0)
Create an in-kernel device model.
Parameters
type Device type (KVM_DEV_TYPE_xxx)
flags Creation flags (KVM_CREATE_DEVICE_xxx)
Returns
Device file descriptor
Definition at line 515 of file vm.cc.
References ioctl(), panic, and type.
createVCPU()
int KvmVM::createVCPU (long vcpuID) protected
Create a new vCPU within a VM.
Parameters
vcpuID ID of the new CPU within the VM.
Returns
File descriptor referencing the CPU.
Definition at line 548 of file vm.cc.
References ArmISA::fd, ioctl(), and panic.
Referenced by BaseKvmCPU::startup().
delayedStartup()
void KvmVM::delayedStartup () protected
Delayed initialization, executed once before the first CPU starts.
This method provides a way to do VM initialization once before the first CPU in a VM starts. It is needed since some resources (e.g., memory mappings) can change in the normal SimObject::startup() path. Since the call order of SimObject::startup() is not guaranteed, we simply defer some initialization until a CPU is about to start.
Definition at line 344 of file vm.cc.
References allocMemSlot(), DPRINTF, PhysicalMemory::getBackingStore(), System::getPhysMem(), hack, AddrRange::interleaved(), panic, setupMemSlot(), AddrRange::size(), AddrRange::start(), and system.
Referenced by cpuStartup().
disableMemSlot()
void KvmVM::disableMemSlot (const MemSlot slot)
Disable a memory slot.
Definition at line 416 of file vm.cc.
References KvmVM::MemorySlot::active, memorySlots, KvmVM::MemSlot::num, and setUserMemoryRegion().
Referenced by freeMemSlot().
freeMemSlot()
void KvmVM::freeMemSlot (const MemSlot slot)
Free a previously allocated memory slot.
Definition at line 425 of file vm.cc.
References disableMemSlot(), memorySlots, KvmVM::MemSlot::num, and KvmVM::MemorySlot::size.
notifyFork()
void KvmVM::notifyFork () virtual
Notify a child process of a fork.
When calling fork in gem5, we need to ensure that resources shared between the parent and the child are consistent. This method is intended to be overloaded to handle that. For example, an object could use this method to re-open input files to get a separate file description with a private file offset.
This method is only called in the child of the fork. The call takes place in a drained system.
Reimplemented from Drainable.
Definition at line 320 of file vm.cc.
References kvm, vmFD, and warn.
operator=()
KvmVM& KvmVM::operator= (const KvmVM & vm) private
setSystem()
void KvmVM::setSystem (System * s)
Initialize system pointer.
Invoked by system object.
Definition at line 532 of file vm.cc.
References panic_if, ArmISA::s, and system.
Referenced by System::System().
setTSSAddress()
void KvmVM::setTSSAddress (Addr tss_address)
Setup a shared three-page memory region used by the internals of KVM.
This is currently only needed by x86 implementations.
Parameters
tss_address Physical address of the start of the TSS
Definition at line 480 of file vm.cc.
References ioctl(), and panic.
setupMemSlot()
void KvmVM::setupMemSlot (const MemSlot slot, void * host_addr, Addr guest_addr, uint32_t flags)
Setup a region of physical memory in the guest.
Parameters
slot KVM memory slot ID returned by allocMemSlot
host_addr Memory allocation backing the memory
guest_addr Address in the guest
flags Flags (see the KVM API documentation)
Definition at line 407 of file vm.cc.
References KvmVM::MemorySlot::active, memorySlots, KvmVM::MemSlot::num, setUserMemoryRegion(), and KvmVM::MemorySlot::size.
Referenced by delayedStartup().
setUserMemoryRegion()
void KvmVM::setUserMemoryRegion (uint32_t slot, void * host_addr, Addr guest_addr, uint64_t len, uint32_t flags) protected
Setup a region of physical memory in the guest.
Parameters
slot KVM memory slot ID (must be unique)
host_addr Memory allocation backing the memory
guest_addr Address in the guest
len Size of the allocation in bytes
flags Flags (see the KVM API documentation)
Definition at line 433 of file vm.cc.
References ioctl(), ArmISA::len, ArmISA::m, and panic.
Referenced by disableMemSlot(), and setupMemSlot().
Friends And Related Function Documentation
BaseKvmCPU
friend class BaseKvmCPU friend
Definition at line 293 of file vm.hh.
Member Data Documentation
_hasKernelIRQChip
bool KvmVM::_hasKernelIRQChip private
Do we have in-kernel IRQ-chip emulation enabled?
Definition at line 535 of file vm.hh.
Referenced by createIRQChip().
kvm
Kvm* KvmVM::kvm
Global KVM interface.
Definition at line 411 of file vm.hh.
Referenced by X86KvmCPU::dumpMSRs(), X86KvmCPU::getMsrIntersection(), Kvm::ioctl(), KvmVM(), notifyFork(), BaseKvmCPU::startup(), X86KvmCPU::X86KvmCPU(), and ~KvmVM().
maxMemorySlot
uint32_t KvmVM::maxMemorySlot private
Definition at line 551 of file vm.hh.
Referenced by allocMemSlot(), and KvmVM().
memorySlots
std::vector<MemorySlot> KvmVM::memorySlots private
Definition at line 550 of file vm.hh.
Referenced by allocMemSlot(), disableMemSlot(), freeMemSlot(), and setupMemSlot().
nextVCPUID
long KvmVM::nextVCPUID private
Next unallocated vCPU ID.
Definition at line 538 of file vm.hh.
Referenced by allocVCPUID().
started
bool KvmVM::started private
Has delayedStartup() already been called?
Definition at line 532 of file vm.hh.
Referenced by cpuStartup().
system
System* KvmVM::system private
Definition at line 526 of file vm.hh.
Referenced by contextIdToVCpuId(), delayedStartup(), and setSystem().
vmFD
int KvmVM::vmFD private
KVM VM file descriptor.
Definition at line 529 of file vm.hh.
Referenced by ioctl(), notifyFork(), and ~KvmVM().
The documentation for this class was generated from the following files:
cpu/kvm/vm.hh
cpu/kvm/vm.cc