gem5: VirtIO9PProxy Class Reference
VirtIO9PProxy Class Reference abstract
VirtIO 9p proxy base class.
#include <fs9p.hh>
Public Types
typedef VirtIO9PProxyParams Params
Public Types inherited from VirtIO9PBase
typedef VirtIO9PBaseParams Params
Public Types inherited from VirtIODeviceBase
typedef uint16_t QueueID
typedef uint32_t FeatureBits
typedef uint16_t VirtAddress
This is a VirtQueue address as exposed through the low-level interface. The address needs to be multiplied by the page size (seems to be hardcoded to 4096 in the spec) to get the real physical address.
typedef uint16_t DeviceId
Device Type (sometimes known as subsystem ID)
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
VirtIO9PProxy (Params *params)
virtual ~VirtIO9PProxy ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from VirtIO9PBase
VirtIO9PBase (Params *params)
virtual ~VirtIO9PBase ()
void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
Public Member Functions inherited from VirtIODeviceBase
BitUnion8 (DeviceStatus) Bitfield< 7 > failed
EndBitUnion (DeviceStatus) typedef VirtIODeviceBaseParams Params
VirtIODeviceBase (Params *params, DeviceId id, size_t config_size, FeatureBits features)
virtual ~VirtIODeviceBase ()
virtual void writeConfig (PacketPtr pkt, Addr cfgOffset)
Write to the configuration space of a device.
virtual void reset ()
Driver-request device reset.
void registerKickCallback (Callback *c)
Register a callback to kick the guest through the transport interface.
void onNotify (QueueID index)
Driver is requesting service.
void setQueueSelect (QueueID idx)
Change currently active queue.
QueueID getQueueSelect () const
Get the currently active queue.
void setQueueAddress (uint32_t address)
Change the host physical address of the currently active queue.
uint32_t getQueueAddress () const
Get the host physical address of the currently active queue.
uint16_t getQueueSize () const
Get the size (descriptors) of the currently active queue.
void setDeviceStatus (DeviceStatus status)
Update device status and optionally reset device.
DeviceStatus getDeviceStatus () const
Retrieve the device status.
void setGuestFeatures (FeatureBits features)
Set feature bits accepted by the guest driver.
FeatureBits getGuestFeatures () const
Get features accepted by the guest driver.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void recvTMsg (const P9MsgHeader &header, const uint8_t *data, size_t size) override
Handle incoming 9p RPC message.
void serverDataReady ()
Notification of pending data from server.
virtual ssize_t read (uint8_t *data, size_t len)=0
Read data from the server behind the proxy.
virtual ssize_t write (const uint8_t *data, size_t len)=0
Write data to the server behind the proxy.
void readAll (uint8_t *data, size_t len)
Convenience function that reads exactly len bytes.
void writeAll (const uint8_t *data, size_t len)
Convenience function that writes exactly len bytes.
Protected Member Functions inherited from VirtIO9PBase
void sendRMsg (const P9MsgHeader &header, const uint8_t *data, size_t size)
Send a 9p RPC message reply.
void dumpMsg (const P9MsgHeader &header, const uint8_t *data, size_t size)
Dump a 9p RPC message on the debug output.
Protected Member Functions inherited from VirtIODeviceBase
void kick ()
Inform the guest of available buffers.
void registerQueue (VirtQueue &queue)
Register a new VirtQueue with the device model.
void readConfigBlob (PacketPtr pkt, Addr cfgOffset, const uint8_t *cfg)
Read configuration data from a device structure.
void writeConfigBlob (PacketPtr pkt, Addr cfgOffset, uint8_t *cfg)
Write configuration data to a device structure.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
bool deviceUsed
Bool to track if the device has been used or not.
Protected Attributes inherited from VirtIO9PBase
struct VirtIO9PBase::Config M5_ATTR_PACKED
std::unique_ptr< Config > config
Currently active configuration (host byte order)
FSQueue queue
Protected Attributes inherited from VirtIODeviceBase
FeatureBits guestFeatures
Feature set accepted by the guest.
ByteOrder byteOrder
The byte order of the queues, descriptors, etc.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from VirtIODeviceBase
Bitfield< 2 > driver_ok
Bitfield< 1 > driver
Bitfield< 0 > acknowledge
const DeviceId deviceId
Device ID (sometimes known as subsystem ID)
const size_t configSize
Size of the device's configuration space.
const FeatureBits deviceFeatures
Feature set offered by the device.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Static Protected Attributes inherited from VirtIO9PBase
static const DeviceId ID_9P = 0x09
VirtIO device ID.
static const FeatureBits F_MOUNT_TAG = 0x01
Device provides a name of the resource in its configuration.
Detailed Description
VirtIO 9p proxy base class.
This base class provides basic functionality shared by different 9p proxy implementations.
Definition at line 213 of file fs9p.hh.
Member Typedef Documentation
Params
typedef VirtIO9PProxyParams VirtIO9PProxy::Params
Definition at line 216 of file fs9p.hh.
Constructor & Destructor Documentation
VirtIO9PProxy()
VirtIO9PProxy::VirtIO9PProxy (Params * params)
Definition at line 214 of file fs9p.cc.
~VirtIO9PProxy()
VirtIO9PProxy::~VirtIO9PProxy () virtual
Definition at line 219 of file fs9p.cc.
Member Function Documentation
read()
virtual ssize_t VirtIO9PProxy::read (uint8_t * data, size_t len) protected pure virtual
Read data from the server behind the proxy.
Note
This method may return read fewer than len bytes.
Parameters
data Memory location to store results in.
len Maximum length to read.
Returns
Number of bytes read, -errno on failure.
Implemented in VirtIO9PSocket, and VirtIO9PDiod.
Referenced by readAll().
readAll()
void VirtIO9PProxy::readAll (uint8_t * data, size_t len) protected
Convenience function that reads exactly len bytes.
This method calls read until exactly len number of bytes has been read. A read() call is retried if the underlying syscall was interrupted.
Parameters
data Memory location to store results in.
len Number of bytes to read.
Definition at line 284 of file fs9p.cc.
References panic, and read().
Referenced by serverDataReady().
recvTMsg()
void VirtIO9PProxy::recvTMsg (const P9MsgHeader & header, const uint8_t * data, size_t size) override protected virtual
Handle incoming 9p RPC message.
Parameters
header 9p message header.
data Pointer to data in message.
size Size of data (excluding header)
Implements VirtIO9PBase.
Definition at line 252 of file fs9p.cc.
References deviceUsed, htop9(), P9MsgHeader::len, and writeAll().
serialize()
void VirtIO9PProxy::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from VirtIODeviceBase.
Definition at line 225 of file fs9p.cc.
References deviceUsed, VirtIODeviceBase::serialize(), SERIALIZE_SCALAR, and warn.
serverDataReady()
void VirtIO9PProxy::serverDataReady () protected
Notification of pending data from server.
Definition at line 267 of file fs9p.cc.
References data, header, p9toh(), panic, readAll(), and VirtIO9PBase::sendRMsg().
unserialize()
void VirtIO9PProxy::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from VirtIODeviceBase.
Definition at line 238 of file fs9p.cc.
References deviceUsed, VirtIODeviceBase::unserialize(), UNSERIALIZE_SCALAR, and warn.
write()
virtual ssize_t VirtIO9PProxy::write (const uint8_t * data, size_t len) protected pure virtual
Write data to the server behind the proxy.
Note
This method may return write fewer than len bytes.
Parameters
data Pointer to data to write.
len Maximum length to write.
Returns
Number of bytes written, -errno on failure.
Implemented in VirtIO9PSocket, and VirtIO9PDiod.
Referenced by writeAll().
writeAll()
void VirtIO9PProxy::writeAll (const uint8_t * data, size_t len) protected
Convenience function that writes exactly len bytes.
This method calls write until exactly len number of bytes has been written. A write() call is retried if the underlying syscall was interrupted.
Parameters
data Data to write.
len Number of bytes to write.
Definition at line 299 of file fs9p.cc.
References panic, and write().
Referenced by recvTMsg().
Member Data Documentation
deviceUsed
bool VirtIO9PProxy::deviceUsed protected
Bool to track if the device has been used or not.
We need to keep track of if the device has been used as we are unable to checkpoint the device in the event that the device has been mounted in the guest system. This is due to the fact that we do not, and cannot, track the complete state across host and guest.
Definition at line 283 of file fs9p.hh.
Referenced by recvTMsg(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/virtio/fs9p.hh
dev/virtio/fs9p.cc