gem5: Linux::KernelPanicEvent Class Reference
Linux::KernelPanicEvent Class Reference
Dump the guest kernel's dmesg buffer to a file in gem5's output directory and panic.
#include <events.hh>
Public Member Functions
KernelPanicEvent (PCEventScope *s, const std::string &desc, Addr addr, const std::string &_fname)
virtual void process (ThreadContext *xc)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Protected Attributes
std::string fname
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Dump the guest kernel's dmesg buffer to a file in gem5's output directory and panic.
This event uses Linux::dumpDmesg() and comes with the same limitations. Most importantly, the kernel's address mappings must be available to the translating proxy.
Definition at line 87 of file events.hh.
Constructor & Destructor Documentation
KernelPanicEvent()
Linux::KernelPanicEvent::KernelPanicEvent (PCEventScope * s, const std::string & desc, Addr addr, const std::string & _fname) inline
Definition at line 93 of file events.hh.
References Linux::DebugPrintkEvent::process().
Member Function Documentation
process()
void Linux::KernelPanicEvent::process (ThreadContext * xc) virtual
Implements PCEvent.
Definition at line 115 of file events.cc.
References OutputDirectory::close(), OutputDirectory::create(), PCEvent::descr(), Linux::dumpDmesg(), ThreadContext::getCpuPtr(), inform, PCEvent::name(), SimObject::name(), X86ISA::os, panic, simout, and OutputStream::stream().
Member Data Documentation
fname
std::string Linux::KernelPanicEvent::fname protected
Definition at line 90 of file events.hh.
The documentation for this class was generated from the following files:
kern/linux/events.hh
kern/linux/events.cc