gem5: MipsISA::ResetFault Class Reference
MipsISA::ResetFault Class Reference
#include <faults.hh>
Public Member Functions
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Public Member Functions inherited from MipsISA::MipsFault< ResetFault >
FaultName name () const
FaultVect offset (ThreadContext *tc) const
ExcCode code () const
Public Member Functions inherited from MipsISA::MipsFaultBase
void setExceptionState (ThreadContext *, uint8_t)
virtual FaultVect base (ThreadContext *tc) const
FaultVect vect (ThreadContext *tc) const
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Additional Inherited Members
Protected Member Functions inherited from MipsISA::MipsFault< ResetFault >
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
MipsFaultBase::FaultVals vals
Static Protected Attributes inherited from MipsISA::MipsFault< ResetFault >
static FaultVals vals
Detailed Description
Definition at line 134 of file faults.hh.
Member Function Documentation
invoke()
void MipsISA::ResetFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from MipsISA::MipsFaultBase.
Definition at line 147 of file faults.cc.
References DPRINTF, FullSystem, MipsISA::MISCREG_STATUS, FaultBase::name(), ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscReg(), ArmISA::status, and MipsISA::MipsFaultBase::vect().
The documentation for this class was generated from the following files:
arch/mips/faults.hh
arch/mips/faults.cc