gem5: EmulationPageTable Class Reference
EmulationPageTable Class Reference
#include <page_table.hh>
Classes
struct Entry
Public Types
enum MappingFlags : uint32_t { Clobber = 1, Uncacheable = 4, ReadOnly = 8 }
Public Member Functions
EmulationPageTable (const std::string &__name, uint64_t _pid, Addr _pageSize)
uint64_t pid () const
virtual ~EmulationPageTable ()
virtual void initState ()
const std::string name () const
Addr pageAlign (Addr a)
Addr pageOffset (Addr a)
virtual void map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags=0)
Maps a virtual memory region to a physical memory region.
virtual void remap (Addr vaddr, int64_t size, Addr new_vaddr)
virtual void unmap (Addr vaddr, int64_t size)
virtual bool isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
const Entry * lookup (Addr vaddr)
Lookup function.
bool translate (Addr vaddr, Addr &paddr)
Translate function.
bool translate (Addr vaddr)
Simplified translate function (just check for translation)
Fault translate (const RequestPtr &req)
Perform a translation on the memory request, fills in paddr field of req.
void getMappings (std::vector< std::pair< Addr, Addr >> *addr_mappings)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
bool shared
Protected Types
typedef std::unordered_map< Addr, Entry > PTable
typedef PTable::iterator PTableItr
Protected Attributes
PTable pTable
const Addr pageSize
const Addr offsetMask
const uint64_t _pid
const std::string _name
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 50 of file page_table.hh.
Member Typedef Documentation
PTable
typedef std::unordered_map<Addr, Entry> EmulationPageTable::PTable protected
Definition at line 63 of file page_table.hh.
PTableItr
typedef PTable::iterator EmulationPageTable::PTableItr protected
Definition at line 64 of file page_table.hh.
Member Enumeration Documentation
MappingFlags
enum EmulationPageTable::MappingFlags : uint32_t
Enumerator
Clobber
Uncacheable
ReadOnly
Definition at line 93 of file page_table.hh.
Constructor & Destructor Documentation
EmulationPageTable()
EmulationPageTable::EmulationPageTable (const std::string & __name, uint64_t _pid, Addr _pageSize) inline
Definition at line 75 of file page_table.hh.
References isPowerOf2().
~EmulationPageTable()
virtual EmulationPageTable::~EmulationPageTable () inline virtual
Definition at line 85 of file page_table.hh.
Member Function Documentation
getMappings()
void EmulationPageTable::getMappings (std::vector< std::pair< Addr, Addr >> * addr_mappings)
Definition at line 98 of file page_table.cc.
References pTable.
Referenced by Process::clone(), and translate().
initState()
virtual void EmulationPageTable::initState () inline virtual
Reimplemented in MultiLevelPageTable< EntryTypes >.
Definition at line 102 of file page_table.hh.
Referenced by Process::initState().
isUnmapped()
bool EmulationPageTable::isUnmapped (Addr vaddr, int64_t size) virtual
Check if any pages in a region are already allocated.
Parameters
vaddr The starting virtual address of the region.
size The length of the region.
Returns
True if no pages in the region are mapped.
Definition at line 121 of file page_table.cc.
References ArmISA::offset, pageOffset(), pageSize, and pTable.
Referenced by pageOffset().
lookup()
const EmulationPageTable::Entry * EmulationPageTable::lookup (Addr vaddr)
Lookup function.
Parameters
vaddr The virtual address.
Returns
The page table entry corresponding to vaddr.
Definition at line 134 of file page_table.cc.
References pageAlign(), and pTable.
Referenced by SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), PowerISA::RemoteGDB::acc(), RiscvISA::RemoteGDB::acc(), X86ISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), AlphaISA::NDtbMissFault::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), AlphaISA::ItbPageFault::invoke(), pageOffset(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), X86ISA::TLB::translate(), and translate().
map()
void EmulationPageTable::map (Addr vaddr, Addr paddr, int64_t size, uint64_t flags = 0) virtual
Maps a virtual memory region to a physical memory region.
Parameters
vaddr The starting virtual address of the region.
paddr The starting physical address where the region is mapped.
size The length of the region.
flags Generic mapping flags that can be set by or-ing values from MappingFlags enum.
Reimplemented in MultiLevelPageTable< EntryTypes >.
Definition at line 49 of file page_table.cc.
References Clobber, DPRINTF, pageOffset(), pageSize, panic_if, and pTable.
Referenced by Process::allocateMem(), X86ISA::X86_64Process::initState(), Process::map(), MultiLevelPageTable< EntryTypes >::map(), pageOffset(), and Process::replicatePage().
name()
const std::string EmulationPageTable::name () const inline
Definition at line 105 of file page_table.hh.
References _name.
Referenced by PhysicalMemory::serializeStore().
pageAlign()
Addr EmulationPageTable::pageAlign (Addr a) inline
Definition at line 107 of file page_table.hh.
Referenced by SparcISA::FastInstructionAccessMMUMiss::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), lookup(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), X86ISA::TLB::translate(), and translate().
pageOffset()
Addr EmulationPageTable::pageOffset (Addr a) inline
Definition at line 108 of file page_table.hh.
References EmulationPageTable::Entry::flags, isUnmapped(), lookup(), map(), EmulationPageTable::Entry::paddr, remap(), translate(), unmap(), and MipsISA::vaddr.
Referenced by isUnmapped(), map(), remap(), translate(), and unmap().
pid()
uint64_t EmulationPageTable::pid () const inline
Definition at line 83 of file page_table.hh.
References _pid.
Referenced by AlphaISA::NDtbMissFault::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), AlphaISA::ItbPageFault::invoke(), and X86ISA::TLB::translate().
remap()
void EmulationPageTable::remap (Addr vaddr, int64_t size, Addr new_vaddr) virtual
Reimplemented in MultiLevelPageTable< EntryTypes >.
Definition at line 76 of file page_table.cc.
References DPRINTF, M5_VAR_USED, pageOffset(), pageSize, and pTable.
Referenced by pageOffset(), and MultiLevelPageTable< EntryTypes >::remap().
serialize()
void EmulationPageTable::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 173 of file page_table.cc.
References X86ISA::count, csprintf(), paramOut(), and pTable.
Referenced by Process::serialize(), MultiLevelPageTable< EntryTypes >::serialize(), and translate().
translate() [1/3]
bool EmulationPageTable::translate (Addr vaddr, Addr & paddr)
Translate function.
Parameters
vaddr The virtual address.
paddr Physical address from translation.
Returns
True if translation exists
Definition at line 144 of file page_table.cc.
References DPRINTF, lookup(), EmulationPageTable::Entry::paddr, and pageOffset().
Referenced by Process::clone(), pageOffset(), ComputeUnit::sendRequest(), translate(), RiscvISA::TLB::translateData(), MipsISA::TLB::translateData(), PowerISA::TLB::translateData(), RiscvISA::TLB::translateInst(), MipsISA::TLB::translateInst(), PowerISA::TLB::translateInst(), ArmISA::TLB::translateSe(), SETranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryReadBlob(), and SETranslatingPortProxy::tryWriteBlob().
translate() [2/3]
bool EmulationPageTable::translate (Addr vaddr) inline
Simplified translate function (just check for translation)
Parameters
vaddr The virtual address.
Returns
True if translation exists
Definition at line 150 of file page_table.hh.
References getMappings(), serialize(), translate(), and unserialize().
Referenced by translate().
translate() [3/3]
Fault EmulationPageTable::translate (const RequestPtr & req)
Perform a translation on the memory request, fills in paddr field of req.
Parameters
req The memory request.
Definition at line 157 of file page_table.cc.
References NoFault, pageAlign(), pageSize, panic, and translate().
unmap()
void EmulationPageTable::unmap (Addr vaddr, int64_t size) virtual
Reimplemented in MultiLevelPageTable< EntryTypes >.
Definition at line 105 of file page_table.cc.
References DPRINTF, pageOffset(), pageSize, and pTable.
Referenced by pageOffset(), and MultiLevelPageTable< EntryTypes >::unmap().
unserialize()
void EmulationPageTable::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 189 of file page_table.cc.
References X86ISA::count, csprintf(), ArmISA::i, paramIn(), pTable, UNSERIALIZE_SCALAR, and MipsISA::vaddr.
Referenced by translate(), Process::unserialize(), and MultiLevelPageTable< EntryTypes >::unserialize().
Member Data Documentation
_name
const std::string EmulationPageTable::_name protected
Definition at line 71 of file page_table.hh.
Referenced by name().
_pid
const uint64_t EmulationPageTable::_pid protected
Definition at line 70 of file page_table.hh.
Referenced by pid().
offsetMask
const Addr EmulationPageTable::offsetMask protected
Definition at line 68 of file page_table.hh.
pageSize
const Addr EmulationPageTable::pageSize protected
Definition at line 67 of file page_table.hh.
Referenced by isUnmapped(), map(), remap(), translate(), and unmap().
pTable
PTable EmulationPageTable::pTable protected
Definition at line 65 of file page_table.hh.
Referenced by getMappings(), isUnmapped(), lookup(), map(), remap(), serialize(), unmap(), and unserialize().
shared
bool EmulationPageTable::shared
Definition at line 100 of file page_table.hh.
Referenced by cloneFunc().
The documentation for this class was generated from the following files:
mem/page_table.hh
mem/page_table.cc