gem5: MPP_StatisticalCorrector_64KB Class Reference
MPP_StatisticalCorrector_64KB Class Reference
#include <multiperspective_perceptron_tage_64KB.hh>
Public Member Functions
MPP_StatisticalCorrector_64KB (const MPP_StatisticalCorrector_64KBParams *p)
size_t getSizeInBits () const override
Public Member Functions inherited from MPP_StatisticalCorrector
MPP_StatisticalCorrector (const MPP_StatisticalCorrectorParams *p)
void initBias () override
unsigned getIndBias (Addr branch_pc, StatisticalCorrector::BranchInfo *bi, bool bias) const override
unsigned getIndBiasSK (Addr branch_pc, StatisticalCorrector::BranchInfo *bi) const override
unsigned getIndBiasBank (Addr branch_pc, StatisticalCorrector::BranchInfo *bi, int hitBank, int altBank) const override
unsigned getIndUpd (Addr branch_pc) const override
int gIndexLogsSubstr (int nbr, int i) override
bool scPredict (ThreadID tid, Addr branch_pc, bool cond_branch, StatisticalCorrector::BranchInfo *bi, bool prev_pred_taken, bool bias_bit, bool use_conf_ctr, int8_t conf_ctr, unsigned conf_bits, int hitBank, int altBank, int64_t phist, int init_lsum) override
void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, StatisticalCorrector::BranchInfo *bi, Addr corrTarget, bool b, int hitBank, int altBank, int64_t phist) override
void gUpdate (Addr branch_pc, bool taken, int64_t hist, std::vector< int > &length, std::vector< int8_t > *tab, int nbr, int logs, std::vector< int8_t > &w, StatisticalCorrector::BranchInfo *bi) override
Public Member Functions inherited from StatisticalCorrector
StatisticalCorrector (const StatisticalCorrectorParams *p)
virtual BranchInfo * makeBranchInfo ()
unsigned getIndUpds (Addr branch_pc) const
int64_t gIndex (Addr branch_pc, int64_t bhist, int logs, int nbr, int i)
int gPredict (Addr branch_pc, int64_t hist, std::vector< int > &length, std::vector< int8_t > *tab, int nbr, int logs, std::vector< int8_t > &w)
void initGEHLTable (unsigned numLenghts, std::vector< int > lengths, std::vector< int8_t > *&table, unsigned logNumEntries, std::vector< int8_t > &w, int8_t wInitValue)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void regStats () override
Callback to set stat parameters.
void updateStats (bool taken, BranchInfo *bi)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
StatisticalCorrector::SCThreadHistory * makeThreadHistory () override
int gPredictions (ThreadID tid, Addr branch_pc, StatisticalCorrector::BranchInfo *bi, int &lsum, int64_t phist) override
void getBiasLSUM (Addr branch_pc, StatisticalCorrector::BranchInfo *bi, int &lsum) const override
void gUpdates (ThreadID tid, Addr pc, bool taken, StatisticalCorrector::BranchInfo *bi, int64_t phist) override
void scHistoryUpdate (Addr branch_pc, const StaticInstPtr &inst, bool taken, StatisticalCorrector::BranchInfo *bi, Addr corrTarget) override
Private Attributes
const unsigned numEntriesSecondLocalHistories
const unsigned numEntriesThirdLocalHistories
const unsigned snb
const unsigned logSnb
std::vector< int > sm
std::vector< int8_t > * sgehl
std::vector< int8_t > ws
const unsigned tnb
const unsigned logTnb
std::vector< int > tm
std::vector< int8_t > * tgehl
std::vector< int8_t > wt
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from StatisticalCorrector
template<typename T >
void ctrUpdate (T &ctr, bool taken, int nbits)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from MPP_StatisticalCorrector
int8_t thirdH
const unsigned pnb
const unsigned logPnb
std::vector< int > pm
std::vector< int8_t > * pgehl
std::vector< int8_t > wp
const unsigned gnb
const unsigned logGnb
std::vector< int > gm
std::vector< int8_t > * ggehl
std::vector< int8_t > wg
Protected Attributes inherited from StatisticalCorrector
SCThreadHistory * scHistory
const unsigned logBias
const unsigned logSizeUp
const unsigned logSizeUps
const unsigned numEntriesFirstLocalHistories
const unsigned bwnb
const unsigned logBwnb
std::vector< int > bwm
std::vector< int8_t > * bwgehl
std::vector< int8_t > wbw
const unsigned lnb
const unsigned logLnb
std::vector< int > lm
std::vector< int8_t > * lgehl
std::vector< int8_t > wl
const unsigned inb
const unsigned logInb
std::vector< int > im
std::vector< int8_t > * igehl
std::vector< int8_t > wi
std::vector< int8_t > bias
std::vector< int8_t > biasSK
std::vector< int8_t > biasBank
std::vector< int8_t > wb
int updateThreshold
std::vector< int > pUpdateThreshold
const unsigned chooserConfWidth
const unsigned updateThresholdWidth
const unsigned pUpdateThresholdWidth
const unsigned extraWeightsWidth
const unsigned scCountersWidth
int8_t firstH
int8_t secondH
Stats::Scalar scPredictorCorrect
Stats::Scalar scPredictorWrong
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 46 of file multiperspective_perceptron_tage_64KB.hh.
Constructor & Destructor Documentation
MPP_StatisticalCorrector_64KB()
MPP_StatisticalCorrector_64KB::MPP_StatisticalCorrector_64KB (const MPP_StatisticalCorrector_64KBParams * p)
Definition at line 42 of file multiperspective_perceptron_tage_64KB.cc.
References StatisticalCorrector::initGEHLTable(), logSnb, logTnb, sgehl, sm, snb, tgehl, tm, tnb, ws, and wt.
Referenced by getSizeInBits().
Member Function Documentation
getBiasLSUM()
void MPP_StatisticalCorrector_64KB::getBiasLSUM (Addr branch_pc, StatisticalCorrector::BranchInfo * bi, int & lsum) const override private virtual
Implements MPP_StatisticalCorrector.
Definition at line 73 of file multiperspective_perceptron_tage_64KB.cc.
References StatisticalCorrector::bias, StatisticalCorrector::biasSK, MPP_StatisticalCorrector::getIndBias(), and MPP_StatisticalCorrector::getIndBiasSK().
getSizeInBits()
size_t MPP_StatisticalCorrector_64KB::getSizeInBits () const override virtual
Reimplemented from StatisticalCorrector.
Definition at line 161 of file multiperspective_perceptron_tage_64KB.cc.
References bits(), StatisticalCorrector::chooserConfWidth, MPP_StatisticalCorrector::gnb, StatisticalCorrector::lm, StatisticalCorrector::lnb, StatisticalCorrector::logBias, MPP_StatisticalCorrector::logGnb, StatisticalCorrector::logLnb, MPP_StatisticalCorrector::logPnb, StatisticalCorrector::logSizeUp, logSnb, logTnb, MPP_StatisticalCorrector_64KB(), StatisticalCorrector::numEntriesFirstLocalHistories, numEntriesSecondLocalHistories, numEntriesThirdLocalHistories, MPP_StatisticalCorrector::pnb, StatisticalCorrector::pUpdateThresholdWidth, StatisticalCorrector::scCountersWidth, sm, snb, tm, and tnb.
gPredictions()
int MPP_StatisticalCorrector_64KB::gPredictions (ThreadID tid, Addr branch_pc, StatisticalCorrector::BranchInfo * bi, int & lsum, int64_t phist) override private virtual
Implements StatisticalCorrector.
Definition at line 83 of file multiperspective_perceptron_tage_64KB.cc.
References MPP_StatisticalCorrector::MPP_SCThreadHistory::getHistoryStackEntry(), MPP_StatisticalCorrector::getIndUpd(), StatisticalCorrector::SCThreadHistory::getLocalHistory(), MPP_StatisticalCorrector::ggehl, MPP_StatisticalCorrector::MPP_SCThreadHistory::globalHist, MPP_StatisticalCorrector::gm, MPP_StatisticalCorrector::gnb, StatisticalCorrector::gPredict(), StatisticalCorrector::lgehl, StatisticalCorrector::lm, StatisticalCorrector::lnb, MPP_StatisticalCorrector::logGnb, StatisticalCorrector::logLnb, MPP_StatisticalCorrector::logPnb, logSnb, logTnb, MipsISA::pc, MPP_StatisticalCorrector::pgehl, MPP_StatisticalCorrector::pm, MPP_StatisticalCorrector::pnb, StatisticalCorrector::BranchInfo::predBeforeSC, StatisticalCorrector::pUpdateThreshold, StatisticalCorrector::scHistory, sgehl, ArmISA::sh, sm, snb, tgehl, tm, tnb, MPP_StatisticalCorrector::wg, StatisticalCorrector::wl, MPP_StatisticalCorrector::wp, ws, and wt.
gUpdates()
void MPP_StatisticalCorrector_64KB::gUpdates (ThreadID tid, Addr pc, bool taken, StatisticalCorrector::BranchInfo * bi, int64_t phist) override private virtual
Implements StatisticalCorrector.
Definition at line 114 of file multiperspective_perceptron_tage_64KB.cc.
References PowerISA::bi, MPP_StatisticalCorrector::MPP_SCThreadHistory::getHistoryStackEntry(), StatisticalCorrector::SCThreadHistory::getLocalHistory(), MPP_StatisticalCorrector::ggehl, MPP_StatisticalCorrector::MPP_SCThreadHistory::globalHist, MPP_StatisticalCorrector::gm, MPP_StatisticalCorrector::gnb, MPP_StatisticalCorrector::gUpdate(), StatisticalCorrector::lgehl, StatisticalCorrector::lm, StatisticalCorrector::lnb, MPP_StatisticalCorrector::logGnb, StatisticalCorrector::logLnb, MPP_StatisticalCorrector::logPnb, logSnb, logTnb, MPP_StatisticalCorrector::pgehl, MPP_StatisticalCorrector::pm, MPP_StatisticalCorrector::pnb, StatisticalCorrector::BranchInfo::predBeforeSC, StatisticalCorrector::scHistory, sgehl, ArmISA::sh, sm, snb, tgehl, tm, tnb, MPP_StatisticalCorrector::wg, StatisticalCorrector::wl, MPP_StatisticalCorrector::wp, ws, and wt.
makeThreadHistory()
MPP_StatisticalCorrector_64KB::SCThreadHistory * MPP_StatisticalCorrector_64KB::makeThreadHistory () override private virtual
Reimplemented from StatisticalCorrector.
Definition at line 59 of file multiperspective_perceptron_tage_64KB.cc.
References StatisticalCorrector::SCThreadHistory::initLocalHistory(), StatisticalCorrector::numEntriesFirstLocalHistories, numEntriesSecondLocalHistories, numEntriesThirdLocalHistories, StatisticalCorrector::SCThreadHistory::setNumOrdinalHistories(), and ArmISA::sh.
scHistoryUpdate()
void MPP_StatisticalCorrector_64KB::scHistoryUpdate (Addr branch_pc, const StaticInstPtr & inst, bool taken, StatisticalCorrector::BranchInfo * bi, Addr corrTarget) override private virtual
Reimplemented from StatisticalCorrector.
Definition at line 136 of file multiperspective_perceptron_tage_64KB.cc.
References MPP_StatisticalCorrector::MPP_SCThreadHistory::globalHist, StaticInst::isCall(), StaticInst::isDirectCtrl(), StaticInst::isReturn(), StaticInst::isUncondCtrl(), StatisticalCorrector::scHistory, StatisticalCorrector::scHistoryUpdate(), ArmISA::sh, MPP_StatisticalCorrector::MPP_SCThreadHistory::updateHistoryStack(), and StatisticalCorrector::SCThreadHistory::updateLocalHistory().
Member Data Documentation
logSnb
const unsigned MPP_StatisticalCorrector_64KB::logSnb private
Definition at line 52 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
logTnb
const unsigned MPP_StatisticalCorrector_64KB::logTnb private
Definition at line 59 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
numEntriesSecondLocalHistories
const unsigned MPP_StatisticalCorrector_64KB::numEntriesSecondLocalHistories private
Definition at line 47 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), and makeThreadHistory().
numEntriesThirdLocalHistories
const unsigned MPP_StatisticalCorrector_64KB::numEntriesThirdLocalHistories private
Definition at line 48 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), and makeThreadHistory().
sgehl
std::vector<int8_t>* MPP_StatisticalCorrector_64KB::sgehl private
Definition at line 54 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
sm
std::vector<int> MPP_StatisticalCorrector_64KB::sm private
Definition at line 53 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
snb
const unsigned MPP_StatisticalCorrector_64KB::snb private
Definition at line 51 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
tgehl
std::vector<int8_t>* MPP_StatisticalCorrector_64KB::tgehl private
Definition at line 61 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
tm
std::vector<int> MPP_StatisticalCorrector_64KB::tm private
Definition at line 60 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
tnb
const unsigned MPP_StatisticalCorrector_64KB::tnb private
Definition at line 58 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by getSizeInBits(), gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
ws
std::vector<int8_t> MPP_StatisticalCorrector_64KB::ws private
Definition at line 55 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
wt
std::vector<int8_t> MPP_StatisticalCorrector_64KB::wt private
Definition at line 62 of file multiperspective_perceptron_tage_64KB.hh.
Referenced by gPredictions(), gUpdates(), and MPP_StatisticalCorrector_64KB().
The documentation for this class was generated from the following files:
cpu/pred/multiperspective_perceptron_tage_64KB.hh
cpu/pred/multiperspective_perceptron_tage_64KB.cc