gem5: PngWriter Class Reference
PngWriter Class Reference
Image writer implementing support for PNG.
#include <pngwriter.hh>
Classes
struct PngPixel24
Png Pixel type: not containing padding.
struct PngStructHandle
Public Member Functions
PngWriter (const FrameBuffer *_fb)
Create a png that takes data in a given mode & size and outputs to an ostream.
~PngWriter ()
const char * getImgExtension () const override
Return Image format as a string.
void write (std::ostream &png) const override
Write the frame buffer data into the provided ostream.
Public Member Functions inherited from ImgWriter
ImgWriter (const FrameBuffer *_fb)
virtual ~ImgWriter ()
Private Types
typedef PngPixel24 PixelType
Private Attributes
struct PngWriter::PngPixel24 M5_ATTR_PACKED
Static Private Attributes
static const char * _imgExtension = "png"
Additional Inherited Members
Protected Attributes inherited from ImgWriter
const FrameBuffer & fb
Detailed Description
Image writer implementing support for PNG.
Definition at line 52 of file pngwriter.hh.
Member Typedef Documentation
PixelType
typedef PngPixel24 PngWriter::PixelType private
Definition at line 102 of file pngwriter.hh.
Constructor & Destructor Documentation
PngWriter()
PngWriter::PngWriter (const FrameBuffer * _fb) inline
Create a png that takes data in a given mode & size and outputs to an ostream.
Definition at line 59 of file pngwriter.hh.
~PngWriter()
PngWriter::~PngWriter () inline
Definition at line 63 of file pngwriter.hh.
Member Function Documentation
getImgExtension()
const char* PngWriter::getImgExtension () const inline override virtual
Return Image format as a string.
Returns
img extension (e.g. .png for Png)
Implements ImgWriter.
Definition at line 70 of file pngwriter.hh.
References _imgExtension, and write().
write()
void PngWriter::write (std::ostream & png) const override virtual
Write the frame buffer data into the provided ostream.
Parameters
png stream to write to
Implements ImgWriter.
Definition at line 114 of file pngwriter.cc.
References FrameBuffer::area(), ImgWriter::fb, FrameBuffer::height(), FrameBuffer::pixel(), PngWriter::PngStructHandle::pngInfoP, PngWriter::PngStructHandle::pngWriteP, warn, ArmISA::width, FrameBuffer::width(), writePng(), and X86ISA::x.
Referenced by getImgExtension().
Member Data Documentation
_imgExtension
const char * PngWriter::_imgExtension = "png" static private
Definition at line 106 of file pngwriter.hh.
Referenced by getImgExtension().
M5_ATTR_PACKED
struct PngWriter::PngPixel24 PngWriter::M5_ATTR_PACKED private
The documentation for this class was generated from the following files:
base/pngwriter.hh
base/pngwriter.cc