gem5: ComputeUnit::DTLBPort Class Reference
ComputeUnit::DTLBPort Class Reference
Data TLB port.
#include <compute_unit.hh>
Classes
struct SenderState
SenderState is information carried along with the packet throughout the TLB hierarchy.
Public Member Functions
DTLBPort (const std::string &_name, ComputeUnit *_cu, PortID _index)
bool isStalled ()
void stallPort ()
void unstallPort ()
Public Member Functions inherited from MasterPort
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Public Attributes
std::deque< PacketPtr > retries
here we queue all the translation requests that were not successfully sent.
Protected Member Functions
virtual bool recvTimingResp (PacketPtr pkt)
Receive a timing response from the peer.
virtual Tick recvAtomic (PacketPtr pkt)
virtual void recvFunctional (PacketPtr pkt)
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
virtual void recvReqRetry ()
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from MasterPort
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
ComputeUnit * computeUnit
int index
bool stalled
Protected Attributes inherited from MasterPort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Data TLB port.
Definition at line 512 of file compute_unit.hh.
Constructor & Destructor Documentation
DTLBPort()
ComputeUnit::DTLBPort::DTLBPort (const std::string & _name, ComputeUnit * _cu, PortID _index) inline
Definition at line 515 of file compute_unit.hh.
Member Function Documentation
isStalled()
bool ComputeUnit::DTLBPort::isStalled () inline
Definition at line 520 of file compute_unit.hh.
recvAtomic()
virtual Tick ComputeUnit::DTLBPort::recvAtomic (PacketPtr pkt) inline protected virtual
Definition at line 554 of file compute_unit.hh.
recvFunctional()
virtual void ComputeUnit::DTLBPort::recvFunctional (PacketPtr pkt) inline protected virtual
Definition at line 555 of file compute_unit.hh.
recvRangeChange()
virtual void ComputeUnit::DTLBPort::recvRangeChange () inline protected virtual
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented from MasterPort.
Definition at line 556 of file compute_unit.hh.
recvReqRetry()
void ComputeUnit::DTLBPort::recvReqRetry () protected virtual
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Implements TimingRequestProtocol.
Definition at line 1284 of file compute_unit.cc.
References DPRINTF, ArmISA::i, ArmISA::len, M5_VAR_USED, Packet::req, and MipsISA::vaddr.
recvTimingResp()
bool ComputeUnit::DTLBPort::recvTimingResp (PacketPtr pkt) protected virtual
Receive a timing response from the peer.
Implements TimingRequestProtocol.
Definition at line 1069 of file compute_unit.cc.
References ComputeUnit::DTLBPort::SenderState::_gpuDynInst, Packet::cmd, curTick(), Packet::dataStatic(), DPRINTF, DPRINTFN, Packet::getPtr(), M5_VAR_USED, AlphaISA::PageBytes, AlphaISA::PageShift, panic, X86ISA::pf, ComputeUnit::DTLBPort::SenderState::portIndex, MemCmd::ReadReq, MemCmd::ReadResp, Packet::req, roundDown(), safe_cast(), Packet::senderState, ArmISA::stride, MemCmd::SwapReq, MemCmd::SwapResp, MemCmd::toString(), MipsISA::vaddr, MipsISA::w, MemCmd::WriteReq, and MemCmd::WriteResp.
stallPort()
void ComputeUnit::DTLBPort::stallPort () inline
Definition at line 521 of file compute_unit.hh.
unstallPort()
void ComputeUnit::DTLBPort::unstallPort () inline
Definition at line 522 of file compute_unit.hh.
Member Data Documentation
computeUnit
ComputeUnit* ComputeUnit::DTLBPort::computeUnit protected
Definition at line 549 of file compute_unit.hh.
index
int ComputeUnit::DTLBPort::index protected
Definition at line 550 of file compute_unit.hh.
retries
std::deque<PacketPtr> ComputeUnit::DTLBPort::retries
here we queue all the translation requests that were not successfully sent.
Definition at line 528 of file compute_unit.hh.
stalled
bool ComputeUnit::DTLBPort::stalled protected
Definition at line 551 of file compute_unit.hh.
The documentation for this class was generated from the following files:
gpu-compute/compute_unit.hh
gpu-compute/compute_unit.cc