gem5: RiscvISA::PCState Class Reference
RiscvISA::PCState Class Reference
#include <types.hh>
Public Member Functions
PCState ()
PCState (Addr val)
void compressed (bool c)
bool compressed ()
void rv32 (bool val)
bool rv32 () const
bool branching () const
Public Member Functions inherited from GenericISA::UPCState< MachInst >
MicroPC upc () const
void upc (MicroPC val)
MicroPC nupc () const
void nupc (MicroPC val)
MicroPC microPC () const
void set (Addr val)
UPCState ()
UPCState (Addr val)
bool branching () const
void uAdvance ()
void uEnd ()
bool operator== (const UPCState< MachInst > &opc) const
bool operator!= (const UPCState< MachInst > &opc) const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from GenericISA::SimplePCState< MachInst >
Addr pc () const
void pc (Addr val)
Addr npc () const
void npc (Addr val)
void set (Addr val)
void setNPC (Addr val)
SimplePCState ()
SimplePCState (Addr val)
bool branching () const
void advance ()
Public Member Functions inherited from GenericISA::PCStateBase
Addr instAddr () const
Returns the memory address the bytes of this instruction came from.
Addr nextInstAddr () const
Returns the memory address the bytes of the next instruction came from.
MicroPC microPC () const
Returns the current micropc.
void set (Addr val)
Force this PC to reflect a particular value, resetting all its other fields around it.
bool operator== (const PCStateBase &opc) const
bool operator!= (const PCStateBase &opc) const
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Attributes
bool _compressed
bool _rv32
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types inherited from GenericISA::UPCState< MachInst >
typedef SimplePCState< MachInst > Base
Protected Types inherited from GenericISA::SimplePCState< MachInst >
typedef PCStateBase Base
Protected Member Functions inherited from GenericISA::PCStateBase
PCStateBase ()
PCStateBase (Addr val)
Protected Attributes inherited from GenericISA::UPCState< MachInst >
MicroPC _upc
MicroPC _nupc
Protected Attributes inherited from GenericISA::PCStateBase
Addr _pc
Addr _npc
Detailed Description
Definition at line 57 of file types.hh.
Constructor & Destructor Documentation
PCState() [1/2]
RiscvISA::PCState::PCState () inline
Definition at line 64 of file types.hh.
PCState() [2/2]
RiscvISA::PCState::PCState (Addr val) inline
Definition at line 65 of file types.hh.
Member Function Documentation
branching()
bool RiscvISA::PCState::branching () const inline
Definition at line 74 of file types.hh.
References GenericISA::SimplePCState< MachInst >::npc(), GenericISA::UPCState< MachInst >::nupc(), GenericISA::SimplePCState< MachInst >::pc(), and GenericISA::UPCState< MachInst >::upc().
compressed() [1/2]
void RiscvISA::PCState::compressed (bool c) inline
Definition at line 67 of file types.hh.
References RiscvISA::c.
compressed() [2/2]
bool RiscvISA::PCState::compressed () inline
Definition at line 68 of file types.hh.
References _compressed.
rv32() [1/2]
void RiscvISA::PCState::rv32 (bool val) inline
Definition at line 70 of file types.hh.
References X86ISA::val.
Referenced by RiscvProcess32::initState().
rv32() [2/2]
bool RiscvISA::PCState::rv32 () const inline
Definition at line 71 of file types.hh.
References _rv32.
Member Data Documentation
_compressed
bool RiscvISA::PCState::_compressed private
Definition at line 60 of file types.hh.
Referenced by compressed().
_rv32
bool RiscvISA::PCState::_rv32 private
Definition at line 61 of file types.hh.
Referenced by rv32().
The documentation for this class was generated from the following file:
arch/riscv/types.hh