gem5: AlphaISA::ProcessInfo Class Reference
AlphaISA::ProcessInfo Class Reference
#include <stacktrace.hh>
Public Member Functions
ProcessInfo (ThreadContext *_tc)
Addr task (Addr ksp) const
int pid (Addr ksp) const
std::string name (Addr ksp) const
Private Attributes
ThreadContext * tc
int thread_info_size
int task_struct_size
int task_off
int pid_off
int name_off
Detailed Description
Definition at line 44 of file stacktrace.hh.
Constructor & Destructor Documentation
ProcessInfo()
AlphaISA::ProcessInfo::ProcessInfo (ThreadContext * _tc)
Definition at line 48 of file stacktrace.cc.
References addr, SymbolTable::findAddress(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), AlphaISA::GuestByteOrder, System::kernelSymtab, name_off, panic, pid_off, PortProxy::read(), task_off, task_struct_size, tc, and thread_info_size.
Member Function Documentation
name()
string AlphaISA::ProcessInfo::name (Addr ksp) const
Definition at line 107 of file stacktrace.cc.
References ThreadContext::getVirtProxy(), name_off, PortProxy::readString(), task(), and tc.
pid()
int AlphaISA::ProcessInfo::pid (Addr ksp) const
Definition at line 92 of file stacktrace.cc.
References ThreadContext::getVirtProxy(), AlphaISA::GuestByteOrder, pid_off, PortProxy::read(), task(), and tc.
task()
Addr AlphaISA::ProcessInfo::task (Addr ksp) const
Definition at line 77 of file stacktrace.cc.
References X86ISA::base, ThreadContext::getVirtProxy(), AlphaISA::GuestByteOrder, PortProxy::read(), task_off, tc, and ULL.
Referenced by name(), and pid().
Member Data Documentation
name_off
int AlphaISA::ProcessInfo::name_off private
Definition at line 53 of file stacktrace.hh.
Referenced by name(), and ProcessInfo().
pid_off
int AlphaISA::ProcessInfo::pid_off private
Definition at line 52 of file stacktrace.hh.
Referenced by pid(), and ProcessInfo().
task_off
int AlphaISA::ProcessInfo::task_off private
Definition at line 51 of file stacktrace.hh.
Referenced by ProcessInfo(), and task().
task_struct_size
int AlphaISA::ProcessInfo::task_struct_size private
Definition at line 50 of file stacktrace.hh.
Referenced by ProcessInfo().
tc
ThreadContext* AlphaISA::ProcessInfo::tc private
Definition at line 47 of file stacktrace.hh.
Referenced by name(), pid(), ProcessInfo(), and task().
thread_info_size
int AlphaISA::ProcessInfo::thread_info_size private
Definition at line 49 of file stacktrace.hh.
Referenced by ProcessInfo().
The documentation for this class was generated from the following files:
arch/alpha/stacktrace.hh
arch/alpha/stacktrace.cc