gem5: X86ISA::GpuTLB::Translation Class Reference
X86ISA::GpuTLB::Translation Class Reference abstract
#include <gpu_tlb.hh>
Public Member Functions
virtual ~Translation ()
virtual void markDelayed ()=0
Signal that the translation has been delayed due to a hw page table walk.
virtual void finish (Fault fault, const RequestPtr &req, ThreadContext *tc, Mode mode)=0
The memory for this object may be dynamically allocated, and it may be responsible for cleaning itslef up which will happen in this function.
Detailed Description
Definition at line 100 of file gpu_tlb.hh.
Constructor & Destructor Documentation
~Translation()
virtual X86ISA::GpuTLB::Translation::~Translation () inline virtual
Definition at line 103 of file gpu_tlb.hh.
References X86ISA::addr, X86ISA::GpuTLB::dumpAll(), finish(), X86ISA::GpuTLB::lookup(), X86ISA::GpuTLB::lookupIt(), markDelayed(), ArmISA::mode, X86ISA::GpuTLB::setConfigAddress(), and ArmISA::va.
Member Function Documentation
finish()
virtual void X86ISA::GpuTLB::Translation::finish (Fault fault, const RequestPtr & req, ThreadContext * tc, Mode mode) pure virtual
The memory for this object may be dynamically allocated, and it may be responsible for cleaning itslef up which will happen in this function.
Once it's called the object is no longer valid.
Referenced by X86ISA::GpuTLB::translateTiming(), and ~Translation().
markDelayed()
virtual void X86ISA::GpuTLB::Translation::markDelayed () pure virtual
Signal that the translation has been delayed due to a hw page table walk.
Referenced by ~Translation().
The documentation for this class was generated from the following file:
gpu-compute/gpu_tlb.hh