gem5: DictionaryCompressor< T >::MaskedPattern< mask > Class Template Reference
DictionaryCompressor< T >::MaskedPattern< mask > Class Template Reference
A pattern that compares masked values against dictionary entries.
#include <dictionary_compressor.hh>
Public Member Functions
MaskedPattern (const int number, const uint64_t code, const uint64_t metadata_length, const int match_location, const DictionaryEntry bytes, const bool allocate=true)
DictionaryEntry decompress (const DictionaryEntry dict_bytes) const override
Decompress the pattern.
Public Member Functions inherited from DictionaryCompressor< T >::Pattern
Pattern (const int number, const uint64_t code, const uint64_t metadata_length, const uint64_t num_unmatched_bits, const int match_location, const bool allocate=true)
Default constructor.
virtual ~Pattern ()=default
Default destructor.
int getPatternNumber () const
Get enum number associated to this pattern.
uint8_t getCode () const
Get code of this pattern.
uint8_t getMatchLocation () const
Get the index of the dictionary match location.
std::size_t getSizeBits () const
Get size, in bits, of the pattern (excluding prefix).
bool shouldAllocate () const
Determine if pattern allocates a dictionary entry.
std::string print () const
Extract pattern's information to a string.
Static Public Member Functions
static bool isPattern (const DictionaryEntry &bytes, const DictionaryEntry &dict_bytes, const int match_location)
Private Attributes
const T bits
A copy of the bits that do not belong to the mask.
Additional Inherited Members
Protected Attributes inherited from DictionaryCompressor< T >::Pattern
const int patternNumber
Pattern enum number.
const uint8_t code
Code associated to the pattern.
const uint8_t length
Length, in bits, of the code and match location.
const uint8_t numUnmatchedBits
Number of unmatched bits.
const int matchLocation
Index representing the the match location.
const bool allocate
Wether the pattern allocates a dictionary entry or not.
Detailed Description
template<class T>
template<T mask>
class DictionaryCompressor< T >::MaskedPattern< mask >
A pattern that compares masked values against dictionary entries.
If the masked dictionary entry matches perfectly the masked value to be compressed, there is a pattern match.
For example, if the mask is 0xFF00 (that is, this pattern matches the MSB), the value (V) 0xFF20 is being compressed, and the dictionary contains the value (D) 0xFF03, this is a match (V & mask == 0xFF00 == D & mask), and 0x0020 is added to the list of unmatched bits.
Template Parameters
mask A mask containing the bits that must match.
Definition at line 128 of file dictionary_compressor.hh.
Constructor & Destructor Documentation
MaskedPattern()
template<class T> template<T mask> DictionaryCompressor< T >::MaskedPattern< mask >::MaskedPattern (const int number, const uint64_t code, const uint64_t metadata_length, const int match_location, const DictionaryEntry bytes, const bool allocate = true) inline
Definition at line 459 of file dictionary_compressor.hh.
Member Function Documentation
decompress()
template<class T> template<T mask> DictionaryEntry DictionaryCompressor< T >::MaskedPattern< mask >::decompress (const DictionaryEntry dict_bytes) const inline override virtual
Decompress the pattern.
Each pattern has its own way of interpreting its data.
Parameters
dict_bytes The bytes in the corresponding matching entry.
Returns
The decompressed pattern.
Implements DictionaryCompressor< T >::Pattern.
Reimplemented in DictionaryCompressor< T >::MaskedValuePattern< value, mask >, and DictionaryCompressor< T >::MaskedValuePattern< 0, 0xFFFFFFFFFFFFFFFF >.
Definition at line 483 of file dictionary_compressor.hh.
References bits(), DictionaryCompressor< T >::fromDictionaryEntry(), ArmISA::mask, and DictionaryCompressor< T >::toDictionaryEntry().
isPattern()
template<class T> template<T mask> static bool DictionaryCompressor< T >::MaskedPattern< mask >::isPattern (const DictionaryEntry & bytes, const DictionaryEntry & dict_bytes, const int match_location) inline static
Definition at line 472 of file dictionary_compressor.hh.
References DictionaryCompressor< T >::fromDictionaryEntry(), and ArmISA::mask.
Member Data Documentation
bits
template<class T> template<T mask> const T DictionaryCompressor< T >::MaskedPattern< mask >::bits private
A copy of the bits that do not belong to the mask.
Definition at line 453 of file dictionary_compressor.hh.
The documentation for this class was generated from the following file:
mem/cache/compressors/dictionary_compressor.hh