gem5: Stats::StatEvent Class Reference
Stats::StatEvent Class Reference
Event to dump and/or reset the statistics.
Public Member Functions
StatEvent (Tick _when, bool _dump, bool _reset, Tick _repeat)
virtual void process ()
const char * description () const
Public Member Functions inherited from GlobalEvent
GlobalEvent (Priority p, Flags f)
GlobalEvent (Tick when, Priority p, Flags f)
Public Member Functions inherited from BaseGlobalEvent
BaseGlobalEvent (Priority p, Flags f)
virtual ~BaseGlobalEvent ()
void schedule (Tick when)
bool scheduled () const
Tick when () const
void deschedule ()
void reschedule (Tick when)
Private Attributes
bool dump
bool reset
Tick repeat
Additional Inherited Members
Public Types inherited from GlobalEvent
typedef BaseGlobalEventTemplate< GlobalEvent > Base
Public Types inherited from EventBase
typedef int8_t Priority
Static Public Attributes inherited from EventBase
static const Priority Minimum_Pri = SCHAR_MIN
Event priorities, to provide tie-breakers for events scheduled at the same cycle.
static const Priority Debug_Enable_Pri = -101
If we enable tracing on a particular cycle, do that as the very first thing so we don't miss any of the events on that cycle (even if we enter the debugger).
static const Priority Debug_Break_Pri = -100
Breakpoints should happen before anything else (except enabling trace output), so we don't miss any action when debugging.
static const Priority CPU_Switch_Pri = -31
CPU switches schedule the new CPU's tick event for the same cycle (after unscheduling the old CPU's tick event).
static const Priority Delayed_Writeback_Pri = -1
For some reason "delayed" inter-cluster writebacks are scheduled before regular writebacks (which have default priority).
static const Priority Default_Pri = 0
Default is zero for historical reasons.
static const Priority DVFS_Update_Pri = 31
DVFS update event leads to stats dump therefore given a lower priority to ensure all relevant states have been updated.
static const Priority Serialize_Pri = 32
Serailization needs to occur before tick events also, so that a serialize/unserialize is identical to an on-line CPU switch.
static const Priority CPU_Tick_Pri = 50
CPU ticks must come after other associated CPU events (such as writebacks).
static const Priority CPU_Exit_Pri = 64
If we want to exit a thread in a CPU, it comes after CPU_Tick_Pri.
static const Priority Stat_Event_Pri = 90
Statistics events (dump, reset, etc.) come after everything else, but before exit.
static const Priority Progress_Event_Pri = 95
Progress events come at the end.
static const Priority Sim_Exit_Pri = 100
If we want to exit on this cycle, it's the very last thing we do.
static const Priority Maximum_Pri = SCHAR_MAX
Maximum priority.
Protected Types inherited from EventBase
typedef unsigned short FlagsType
typedef ::Flags< FlagsType > Flags
Protected Member Functions inherited from BaseGlobalEventTemplate< GlobalEvent >
BaseGlobalEventTemplate (Priority p, Flags f)
Protected Attributes inherited from BaseGlobalEvent
Barrier barrier
The barrier that all threads wait on before performing the global event.
std::vector< BarrierEvent * > barrierEvent
The individual local event instances (one per thread/event queue).
Static Protected Attributes inherited from EventBase
static const FlagsType PublicRead = 0x003f
static const FlagsType PublicWrite = 0x001d
static const FlagsType Squashed = 0x0001
static const FlagsType Scheduled = 0x0002
static const FlagsType Managed = 0x0004
static const FlagsType AutoDelete = Managed
static const FlagsType Reserved0 = 0x0008
This used to be AutoSerialize.
static const FlagsType IsExitEvent = 0x0010
static const FlagsType IsMainQueue = 0x0020
static const FlagsType Initialized = 0x7a40
static const FlagsType InitMask = 0xffc0
Detailed Description
Event to dump and/or reset the statistics.
Definition at line 216 of file stat_control.cc.
Constructor & Destructor Documentation
StatEvent()
Stats::StatEvent::StatEvent (Tick _when, bool _dump, bool _reset, Tick _repeat) inline
Definition at line 224 of file stat_control.cc.
Member Function Documentation
description()
const char* Stats::StatEvent::description () const inline virtual
Implements BaseGlobalEvent.
Definition at line 244 of file stat_control.cc.
process()
virtual void Stats::StatEvent::process () inline virtual
Implements GlobalEvent.
Definition at line 231 of file stat_control.cc.
References curTick(), Stats::dump(), Stats::reset(), and Stats::schedStatEvent().
Member Data Documentation
dump
bool Stats::StatEvent::dump private
Definition at line 219 of file stat_control.cc.
repeat
Tick Stats::StatEvent::repeat private
Definition at line 221 of file stat_control.cc.
reset
bool Stats::StatEvent::reset private
Definition at line 220 of file stat_control.cc.
The documentation for this class was generated from the following file:
sim/stat_control.cc