gem5: Scheduler Class Reference
Scheduler Class Reference
#include <scheduler.hh>
Public Member Functions
Scheduler (const ComputeUnitParams *params)
Wavefront * chooseWave ()
void bindList (std::vector< Wavefront *> *sched_list)
Private Attributes
SchedulingPolicy * schedPolicy
Scheduling policy.
std::vector< Wavefront * > * scheduleList
Detailed Description
Definition at line 46 of file scheduler.hh.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler (const ComputeUnitParams * params)
Definition at line 43 of file scheduler.cc.
References fatal, and schedPolicy.
Member Function Documentation
bindList()
void Scheduler::bindList (std::vector< Wavefront *> * sched_list)
Definition at line 61 of file scheduler.cc.
References scheduleList.
Referenced by FetchUnit::init().
chooseWave()
Wavefront * Scheduler::chooseWave ()
Definition at line 55 of file scheduler.cc.
References SchedulingPolicy::chooseWave(), schedPolicy, and scheduleList.
Referenced by FetchUnit::exec().
Member Data Documentation
schedPolicy
SchedulingPolicy* Scheduler::schedPolicy private
Scheduling policy.
Currently the model can support oldest-first or round-robin scheduling.
Definition at line 58 of file scheduler.hh.
Referenced by chooseWave(), and Scheduler().
scheduleList
std::vector<Wavefront*>* Scheduler::scheduleList private
Definition at line 59 of file scheduler.hh.
Referenced by bindList(), and chooseWave().
The documentation for this class was generated from the following files:
gpu-compute/scheduler.hh
gpu-compute/scheduler.cc