gem5: BaseSetAssoc Class Reference
BaseSetAssoc Class Reference
A basic cache tag store.
#include <base_set_assoc.hh>
Public Types
typedef BaseSetAssocParams Params
Convenience typedef.
Public Types inherited from BaseTags
typedef BaseTagsParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BaseSetAssoc (const Params *p)
Construct and initialize this tag store.
virtual ~BaseSetAssoc ()
Destructor.
void tagsInit () override
Initialize blocks as CacheBlk instances.
void invalidate (CacheBlk *blk) override
This function updates the tags when a block is invalidated.
CacheBlk * accessBlock (Addr addr, bool is_secure, Cycles &lat) override
Access block and update replacement data.
CacheBlk * findVictim (Addr addr, const bool is_secure, const std::size_t size, std::vector< CacheBlk *> &evict_blks) const override
Find replacement victim based on address.
void insertBlock (const PacketPtr pkt, CacheBlk *blk) override
Insert the new block into the cache and update replacement data.
virtual void setWayAllocationMax (int ways) override
Limit the allocation for the cache ways.
virtual int getWayAllocationMax () const override
Get the way allocation mask limit.
Addr regenerateBlkAddr (const CacheBlk *blk) const override
Regenerate the block address from the tag and indexing location.
void forEachBlk (std::function< void(CacheBlk &)> visitor) override
Visit each block in the tags and apply a visitor.
bool anyBlk (std::function< bool(CacheBlk &)> visitor) override
Find if any of the blocks satisfies a condition.
Public Member Functions inherited from BaseTags
BaseTags (const Params *p)
virtual ~BaseTags ()
Destructor.
void cleanupRefs ()
Average in the reference count for valid blocks when the simulation exits.
void computeStats ()
Computes stats just prior to dump event.
std::string print ()
Print all tags used.
virtual CacheBlk * findBlock (Addr addr, bool is_secure) const
Finds the block in the cache without touching it.
virtual ReplaceableEntry * findBlockBySetAndWay (int set, int way) const
Find a block given set and way.
Addr blkAlign (Addr addr) const
Align an address to the block size.
int extractBlkOffset (Addr addr) const
Calculate the block offset of an address.
virtual Addr extractTag (const Addr addr) const
Generate the tag from the given address.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
unsigned allocAssoc
The allocatable associativity of the cache (alloc mask).
std::vector< CacheBlk > blks
The cache blocks.
const bool sequentialAccess
Whether tags and data are accessed sequentially.
BaseReplacementPolicy * replacementPolicy
Replacement policy.
Protected Attributes inherited from BaseTags
const unsigned blkSize
The block size of the cache.
const Addr blkMask
Mask out all bits that aren't part of the block offset.
const unsigned size
The size of the cache.
const Cycles lookupLatency
The tag lookup latency of the cache.
System * system
System we are currently operating in.
BaseIndexingPolicy * indexingPolicy
Indexing policy.
const unsigned warmupBound
The number of tags that need to be touched to meet the warmup percentage.
bool warmedUp
Marked true when the cache is warmed up.
const unsigned numBlocks
the number of blocks in the cache
std::unique_ptr< uint8_t[]> dataBlks
The data blocks, 1 per cache block.
BaseTags::BaseTagStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
A basic cache tag store.
See also
gem5 Memory System
The BaseSetAssoc placement policy divides the cache into s sets of w cache lines (ways).
Definition at line 74 of file base_set_assoc.hh.
Member Typedef Documentation
Params
typedef BaseSetAssocParams BaseSetAssoc::Params
Convenience typedef.
Definition at line 91 of file base_set_assoc.hh.
Constructor & Destructor Documentation
BaseSetAssoc()
BaseSetAssoc::BaseSetAssoc (const Params * p)
Construct and initialize this tag store.
Definition at line 54 of file base_set_assoc.cc.
References BaseTags::blkSize, fatal, and isPowerOf2().
Referenced by invalidate().
~BaseSetAssoc()
virtual BaseSetAssoc::~BaseSetAssoc () inline virtual
Destructor.
Definition at line 101 of file base_set_assoc.hh.
References invalidate(), and tagsInit().
Member Function Documentation
accessBlock()
CacheBlk* BaseSetAssoc::accessBlock (Addr addr, bool is_secure, Cycles & lat) inline override virtual
Access block and update replacement data.
May not succeed, in which case nullptr is returned. This has all the implications of a cache access and should only be used as such. Returns the tag lookup latency as a side effect.
Parameters
addr The address to find.
is_secure True if the target memory space is secure.
lat The latency of the tag lookup.
Returns
Pointer to the cache block if found.
Implements BaseTags.
Definition at line 127 of file base_set_assoc.hh.
References allocAssoc, BaseTags::BaseTagStats::dataAccesses, BaseTags::findBlock(), BaseTags::lookupLatency, CacheBlk::refCount, ReplaceableEntry::replacementData, BaseTags::stats, BaseTags::BaseTagStats::tagAccesses, and BaseReplacementPolicy::touch().
anyBlk()
bool BaseSetAssoc::anyBlk (std::function< bool(CacheBlk &)> visitor) inline override virtual
Find if any of the blocks satisfies a condition.
The visitor should be a std::function that takes a cache block reference as its parameter. The visitor will terminate the traversal early if the condition is satisfied.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 240 of file base_set_assoc.hh.
findVictim()
CacheBlk* BaseSetAssoc::findVictim (Addr addr, const bool is_secure, const std::size_t size, std::vector< CacheBlk *> & evict_blks) const inline override virtual
Find replacement victim based on address.
The list of evicted blocks only contains the victim.
Parameters
addr Address to find a victim for.
is_secure True if the target memory space is secure.
size Size, in bits, of new block to allocate.
evict_blks Cache blocks to be evicted.
Returns
Cache block to be replaced.
Implements BaseTags.
Definition at line 168 of file base_set_assoc.hh.
References BaseIndexingPolicy::getPossibleEntries(), BaseReplacementPolicy::getVictim(), and BaseTags::indexingPolicy.
forEachBlk()
void BaseSetAssoc::forEachBlk (std::function< void(CacheBlk &)> visitor) inline override virtual
Visit each block in the tags and apply a visitor.
The visitor should be a std::function that takes a cache block reference as its parameter.
Parameters
visitor Visitor to call on each block.
Implements BaseTags.
Definition at line 234 of file base_set_assoc.hh.
getWayAllocationMax()
virtual int BaseSetAssoc::getWayAllocationMax () const inline override virtual
Get the way allocation mask limit.
Returns
The maximum number of ways available for replacement.
Reimplemented from BaseTags.
Definition at line 218 of file base_set_assoc.hh.
References allocAssoc.
insertBlock()
void BaseSetAssoc::insertBlock (const PacketPtr pkt, CacheBlk * blk) inline override virtual
Insert the new block into the cache and update replacement data.
Parameters
pkt Packet holding the address to update
blk The block to update.
Reimplemented from BaseTags.
Definition at line 192 of file base_set_assoc.hh.
References BaseTags::insertBlock(), ReplaceableEntry::replacementData, BaseReplacementPolicy::reset(), BaseTags::stats, and BaseTags::BaseTagStats::tagsInUse.
invalidate()
void BaseSetAssoc::invalidate (CacheBlk * blk) override virtual
This function updates the tags when a block is invalidated.
It also updates the replacement data.
Parameters
blk The block to invalidate.
Reimplemented from BaseTags.
Definition at line 85 of file base_set_assoc.cc.
References BaseSetAssoc(), fatal_if, BaseReplacementPolicy::invalidate(), BaseTags::invalidate(), ReplaceableEntry::replacementData, replacementPolicy, BaseTags::stats, and BaseTags::BaseTagStats::tagsInUse.
Referenced by ~BaseSetAssoc().
regenerateBlkAddr()
Addr BaseSetAssoc::regenerateBlkAddr (const CacheBlk * blk) const inline override virtual
Regenerate the block address from the tag and indexing location.
Parameters
block The block.
Returns
the block address.
Implements BaseTags.
Definition at line 229 of file base_set_assoc.hh.
References BaseTags::indexingPolicy, BaseIndexingPolicy::regenerateAddr(), and CacheBlk::tag.
setWayAllocationMax()
virtual void BaseSetAssoc::setWayAllocationMax (int ways) inline override virtual
Limit the allocation for the cache ways.
Parameters
ways The maximum number of ways available for replacement.
Reimplemented from BaseTags.
Definition at line 208 of file base_set_assoc.hh.
References fatal_if.
tagsInit()
void BaseSetAssoc::tagsInit () override virtual
Initialize blocks as CacheBlk instances.
Implements BaseTags.
Definition at line 66 of file base_set_assoc.cc.
References blks, BaseTags::blkSize, CacheBlk::data, BaseTags::dataBlks, BaseTags::indexingPolicy, BaseReplacementPolicy::instantiateEntry(), BaseTags::numBlocks, ReplaceableEntry::replacementData, replacementPolicy, and BaseIndexingPolicy::setEntry().
Referenced by ~BaseSetAssoc().
Member Data Documentation
allocAssoc
unsigned BaseSetAssoc::allocAssoc protected
The allocatable associativity of the cache (alloc mask).
Definition at line 78 of file base_set_assoc.hh.
Referenced by accessBlock(), and getWayAllocationMax().
blks
std::vector<CacheBlk> BaseSetAssoc::blks protected
The cache blocks.
Definition at line 81 of file base_set_assoc.hh.
Referenced by tagsInit().
replacementPolicy
BaseReplacementPolicy* BaseSetAssoc::replacementPolicy protected
Replacement policy.
Definition at line 87 of file base_set_assoc.hh.
Referenced by invalidate(), and tagsInit().
sequentialAccess
const bool BaseSetAssoc::sequentialAccess protected
Whether tags and data are accessed sequentially.
Definition at line 84 of file base_set_assoc.hh.
The documentation for this class was generated from the following files:
mem/cache/tags/base_set_assoc.hh
mem/cache/tags/base_set_assoc.cc