gem5: tlm_utils::simple_socket_base Class Reference
tlm_utils::simple_socket_base Class Reference
#include <convenience_socket_bases.h>
Protected Member Functions
void elaboration_check (const char *action) const
Protected Member Functions inherited from tlm_utils::convenience_socket_base
virtual ~convenience_socket_base ()
Private Member Functions
virtual const char * get_report_type () const
Additional Inherited Members
Public Member Functions inherited from tlm_utils::convenience_socket_base
void display_warning (const char *msg) const
void display_error (const char *msg) const
Detailed Description
Definition at line 48 of file convenience_socket_bases.h.
Member Function Documentation
elaboration_check()
void tlm_utils::simple_socket_base::elaboration_check (const char * action) const protected
Definition at line 68 of file convenience_socket_bases.cc.
References tlm_utils::convenience_socket_base::display_error(), ArmISA::s, and sc_core::sc_get_curr_simcontext().
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg().
get_report_type()
const char * tlm_utils::simple_socket_base::get_report_type () const private virtual
Implements tlm_utils::convenience_socket_base.
Definition at line 62 of file convenience_socket_bases.cc.
The documentation for this class was generated from the following files:
systemc/ext/tlm_utils/convenience_socket_bases.h
systemc/tlm_utils/convenience_socket_bases.cc