gem5: HDLcd Class Reference
HDLcd Class Reference
#include <hdlcd.hh>
Classes
class DmaEngine
class PixelPump
Public Member Functions
HDLcd (const HDLcdParams *p)
~HDLcd ()
void regStats () override
Callback to set stat parameters.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
bool pxlNext (Pixel &p)
void pxlVSyncBegin ()
void pxlVSyncEnd ()
void pxlUnderrun ()
void pxlFrameDone ()
Public Member Functions inherited from AmbaDmaDevice
AmbaDmaDevice (const Params *p, Addr pio_size=0)
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum RegisterOffset {
Version = 0x0000, Int_RawStat = 0x0010, Int_Clear = 0x0014, Int_Mask = 0x0018,
Int_Status = 0x001C, Fb_Base = 0x0100, Fb_Line_Length = 0x0104, Fb_Line_Count = 0x0108,
Fb_Line_Pitch = 0x010C, Bus_Options = 0x0110, V_Sync = 0x0200, V_Back_Porch = 0x0204,
V_Data = 0x0208, V_Front_Porch = 0x020C, H_Sync = 0x0210, H_Back_Porch = 0x0214,
H_Data = 0x0218, H_Front_Porch = 0x021C, Polarities = 0x0220, Command = 0x0230,
Pixel_Format = 0x0240, Red_Select = 0x0244, Green_Select = 0x0248, Blue_Select = 0x024C
}
ARM HDLcd register offsets.
Protected Member Functions
uint32_t readReg (Addr offset)
void writeReg (Addr offset, uint32_t value)
PixelConverter pixelConverter () const
DisplayTimings displayTimings () const
void createDmaEngine ()
void cmdEnable ()
void cmdDisable ()
bool enabled () const
void setInterrupts (uint32_t ints, uint32_t mask)
Assign new interrupt values and update interrupt signals.
void intMask (uint32_t mask)
Convenience function to update the interrupt mask.
void intRaise (uint32_t ints)
Convenience function to raise a new interrupt.
void intClear (uint32_t ints)
Convenience function to clear interrupts.
uint32_t intStatus () const
Masked interrupt status register.
void virtRefresh ()
Handler for fast frame refresh in KVM-mode.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Member Functions inherited from AmbaDevice
bool readId (PacketPtr pkt, uint64_t amba_id, Addr pio_addr)
Protected Attributes
VncInput * vnc
const bool workaroundSwapRB
const bool workaroundDmaLineCount
const AddrRangeList addrRanges
const bool enableCapture
const Addr pixelBufferSize
const Tick virtRefreshRate
EventFunctionWrapper virtRefreshEvent
std::unique_ptr< ImgWriter > imgWriter
Helper to write out bitmaps.
Enums::ImageFormat imgFormat
Image Format.
OutputStream * pic
Picture of what the current frame buffer looks like.
PixelConverter conv
Cached pixel converter, set when the converter is enabled.
PixelPump pixelPump
std::unique_ptr< DmaEngine > dmaEngine
struct {
Stats::Scalar underruns
} stats
HDLCDRegisters
HDLCD register contents.
uint32_t int_rawstat
Interrupt raw status register.
uint32_t int_mask
Interrupt mask register.
uint32_t fb_base
Frame buffer base address register.
uint32_t fb_line_length
Frame buffer Line length register.
FbLineCountReg fb_line_count
Frame buffer Line count register.
int32_t fb_line_pitch
Frame buffer Line pitch register.
BusOptsReg bus_options
Bus options register.
TimingReg v_sync
Vertical sync width register.
TimingReg v_back_porch
Vertical back porch width register.
TimingReg v_data
Vertical data width register.
TimingReg v_front_porch
Vertical front porch width register.
TimingReg h_sync
Horizontal sync width register.
TimingReg h_back_porch
Horizontal back porch width register.
TimingReg h_data
Horizontal data width register.
TimingReg h_front_porch
Horizontal front porch width reg.
PolaritiesReg polarities
Polarities register.
CommandReg command
Command register.
PixelFormatReg pixel_format
Pixel format register.
ColorSelectReg red_select
Red color select register.
ColorSelectReg green_select
Green color select register.
ColorSelectReg blue_select
Blue color select register.
Protected Attributes inherited from AmbaDmaDevice
uint64_t ambaId
Addr pioAddr
Addr pioSize
Tick pioDelay
int intNum
BaseGic * gic
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static constexpr size_t BUS_OPTIONS_RESETV = 0x408
Reset value for Bus_Options register.
static constexpr size_t VERSION_RESETV = 0x1CDC0000
Reset value for Version register.
static constexpr size_t AXI_PORT_WIDTH = 8
AXI port width in bytes.
static constexpr size_t MAX_BURST_LEN = 16
max number of beats delivered in one dma burst
static constexpr size_t MAX_PIXEL_SIZE = 4
Maximum number of bytes per pixel.
Static Protected Attributes inherited from AmbaDevice
static const int AMBA_PER_ID0 = 0xFE0
static const int AMBA_PER_ID1 = 0xFE4
static const int AMBA_PER_ID2 = 0xFE8
static const int AMBA_PER_ID3 = 0xFEC
static const int AMBA_CEL_ID0 = 0xFF0
static const int AMBA_CEL_ID1 = 0xFF4
static const int AMBA_CEL_ID2 = 0xFF8
static const int AMBA_CEL_ID3 = 0xFFC
RegisterFieldLayouts
Bit layout declarations for multi-field registers.
version_minor
Bitfield< 15, 8 > version_major
Bitfield< 31, 16 > product_id
fb_line_count
Bitfield< 31, 12 > reserved_31_12
burst_len
Bitfield< 7, 5 > reserved_7_5
Bitfield< 11, 8 > max_outstanding
val
Bitfield< 1 > hsync_polarity
Bitfield< 2 > dataen_polarity
Bitfield< 3 > data_polarity
Bitfield< 4 > pxlclk_polarity
Bitfield< 31, 5 > reserved_31_5
Bitfield< 31, 1 > reserved_31_1
reserved_2_0
Bitfield< 4, 3 > bytes_per_pixel
Bitfield< 30, 5 > reserved_30_5
Bitfield< 31 > big_endian
offset
Bitfield< 11, 8 > size
Bitfield< 15, 12 > reserved_15_12
Bitfield< 23, 16 > default_color
Bitfield< 31, 24 > reserved_31_24
static constexpr uint32_t INT_BUS_ERROR = (1UL << 1)
static constexpr uint32_t INT_VSYNC = (1UL << 2)
static constexpr uint32_t INT_UNDERRUN = (1UL << 3)
BitUnion32 (VersionReg) Bitfield< 7
EndBitUnion (VersionReg) static const expr uint32_t INT_DMA_END
BitUnion32 (FbLineCountReg) Bitfield< 11
EndBitUnion (FbLineCountReg) BitUnion32(BusOptsReg) Bitfield< 4
EndBitUnion (BusOptsReg) BitUnion32(TimingReg) Bitfield< 11
EndBitUnion (TimingReg) BitUnion32(PolaritiesReg) Bitfield< 0 > vsync_polarity
EndBitUnion (PolaritiesReg) BitUnion32(CommandReg) Bitfield< 0 > enable
EndBitUnion (CommandReg) BitUnion32(PixelFormatReg) Bitfield< 2
EndBitUnion (PixelFormatReg) BitUnion32(ColorSelectReg) Bitfield< 4
Additional Inherited Members
Public Types inherited from AmbaDmaDevice
typedef AmbaDmaDeviceParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 93 of file hdlcd.hh.
Member Enumeration Documentation
RegisterOffset
enum HDLcd::RegisterOffset protected
ARM HDLcd register offsets.
Enumerator
Version
Int_RawStat
Int_Clear
Int_Mask
Int_Status
Fb_Base
Fb_Line_Length
Fb_Line_Count
Fb_Line_Pitch
Bus_Options
V_Sync
V_Back_Porch
V_Data
V_Front_Porch
H_Sync
H_Back_Porch
H_Data
H_Front_Porch
Polarities
Command
Pixel_Format
Red_Select
Green_Select
Blue_Select
Definition at line 123 of file hdlcd.hh.
Constructor & Destructor Documentation
HDLcd()
HDLcd::HDLcd (const HDLcdParams * p)
Definition at line 60 of file hdlcd.cc.
References blue_select, bus_options, BUS_OPTIONS_RESETV, command, conv, createImgWriter(), enableCapture, BasePixelPump::fb, fb_base, fb_line_count, fb_line_length, fb_line_pitch, green_select, h_back_porch, h_data, h_front_porch, h_sync, imgFormat, imgWriter, int_mask, int_rawstat, SimObject::name(), MipsISA::p, pic, AmbaDmaDevice::pioAddr, AmbaDmaDevice::pioSize, pixel_format, pixelBufferSize, pixelPump, polarities, RangeSize(), red_select, PixelConverter::rgba8888_le, VncInput::setFrameBuffer(), v_back_porch, v_data, v_front_porch, v_sync, VERSION_RESETV, virtRefresh(), virtRefreshEvent, virtRefreshRate, and vnc.
Referenced by HDLcd::PixelPump::dumpSettings().
~HDLcd()
HDLcd::~HDLcd ()
Definition at line 98 of file hdlcd.cc.
Member Function Documentation
BitUnion32() [1/2]
HDLcd::BitUnion32 (VersionReg) protected
BitUnion32() [2/2]
HDLcd::BitUnion32 (FbLineCountReg) protected
cmdDisable()
void HDLcd::cmdDisable () protected
Definition at line 512 of file hdlcd.cc.
References System::bypassCaches(), EventManager::deschedule(), dmaEngine, pixelPump, Event::scheduled(), BasePixelPump::stop(), PioDevice::sys, and virtRefreshEvent.
Referenced by drainResume(), and writeReg().
cmdEnable()
void HDLcd::cmdEnable () protected
Definition at line 496 of file hdlcd.cc.
References System::bypassCaches(), Clocked::clockEdge(), conv, createDmaEngine(), displayTimings(), pixelConverter(), pixelPump, EventManager::schedule(), BasePixelPump::start(), PioDevice::sys, BasePixelPump::updateTimings(), and virtRefreshEvent.
Referenced by drainResume(), and writeReg().
createDmaEngine()
void HDLcd::createDmaEngine () protected
Definition at line 469 of file hdlcd.cc.
References AXI_PORT_WIDTH, bus_options, dmaEngine, fb_line_count, fb_line_length, fb_line_pitch, findMsbSet(), MAX_BURST_LEN, pixelBufferSize, warn, and workaroundDmaLineCount.
Referenced by cmdEnable(), and unserialize().
displayTimings()
DisplayTimings HDLcd::displayTimings () const protected
Definition at line 460 of file hdlcd.cc.
References h_back_porch, h_data, h_front_porch, h_sync, v_back_porch, v_data, v_front_porch, and v_sync.
Referenced by cmdEnable().
drainResume()
void HDLcd::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 205 of file hdlcd.cc.
References BasePixelPump::active(), System::bypassCaches(), cmdDisable(), cmdEnable(), Drainable::drainResume(), enabled(), pixelPump, VncInput::setDirty(), PioDevice::sys, and vnc.
enabled()
bool HDLcd::enabled () const inline protected
Definition at line 269 of file hdlcd.hh.
References ArmISA::mask, pxlFrameDone(), pxlNext(), pxlUnderrun(), pxlVSyncBegin(), pxlVSyncEnd(), and setInterrupts().
Referenced by drainResume(), serialize(), and unserialize().
EndBitUnion() [1/7]
HDLcd::EndBitUnion (VersionReg) const protected
EndBitUnion() [2/7]
HDLcd::EndBitUnion (FbLineCountReg) protected
EndBitUnion() [3/7]
HDLcd::EndBitUnion (BusOptsReg) protected
EndBitUnion() [4/7]
HDLcd::EndBitUnion (TimingReg) protected
EndBitUnion() [5/7]
HDLcd::EndBitUnion (PolaritiesReg) protected
EndBitUnion() [6/7]
HDLcd::EndBitUnion (CommandReg) protected
EndBitUnion() [7/7]
HDLcd::EndBitUnion (PixelFormatReg) protected
getAddrRanges()
AddrRangeList HDLcd::getAddrRanges () const inline override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 110 of file hdlcd.hh.
References addrRanges.
intClear()
void HDLcd::intClear (uint32_t ints) inline protected
Convenience function to clear interrupts.
See also
setInterrupts
Parameters
ints Set of interrupts to clear
Definition at line 316 of file hdlcd.hh.
References int_mask, int_rawstat, and setInterrupts().
Referenced by writeReg().
intMask()
void HDLcd::intMask (uint32_t mask) inline protected
Convenience function to update the interrupt mask.
See also
setInterrupts
Parameters
mask New interrupt mask
Definition at line 298 of file hdlcd.hh.
References int_rawstat, and setInterrupts().
Referenced by writeReg().
intRaise()
void HDLcd::intRaise (uint32_t ints) inline protected
Convenience function to raise a new interrupt.
See also
setInterrupts
Parameters
ints Set of interrupts to raise
Definition at line 306 of file hdlcd.hh.
References int_mask, int_rawstat, and setInterrupts().
Referenced by HDLcd::DmaEngine::onIdle(), pxlUnderrun(), pxlVSyncBegin(), and writeReg().
intStatus()
uint32_t HDLcd::intStatus () const inline protected
Masked interrupt status register.
Definition at line 321 of file hdlcd.hh.
References int_mask, and int_rawstat.
Referenced by readReg(), and setInterrupts().
pixelConverter()
PixelConverter HDLcd::pixelConverter () const protected
Definition at line 437 of file hdlcd.cc.
References BigEndianByteOrder, blue_select, green_select, LittleEndianByteOrder, pixel_format, red_select, and workaroundSwapRB.
Referenced by cmdEnable(), and unserialize().
pxlFrameDone()
void HDLcd::pxlFrameDone ()
Definition at line 560 of file hdlcd.cc.
References OutputDirectory::create(), csprintf(), dmaEngine, DPRINTF, HDLcd::PixelPump::dumpSettings(), enableCapture, imgWriter, SimObject::name(), pic, pixelPump, VncInput::setDirty(), simout, OutputStream::stream(), PioDevice::sys, vnc, and warn.
Referenced by enabled(), and HDLcd::PixelPump::onFrameDone().
pxlNext()
bool HDLcd::pxlNext (Pixel & p)
Definition at line 524 of file hdlcd.cc.
References conv, dmaEngine, PixelConverter::length, MAX_PIXEL_SIZE, and PixelConverter::toPixel().
Referenced by enabled(), and HDLcd::PixelPump::nextPixel().
pxlUnderrun()
void HDLcd::pxlUnderrun ()
Definition at line 551 of file hdlcd.cc.
References dmaEngine, DPRINTF, INT_UNDERRUN, intRaise(), and stats.
Referenced by enabled(), and HDLcd::PixelPump::onUnderrun().
pxlVSyncBegin()
void HDLcd::pxlVSyncBegin ()
Definition at line 537 of file hdlcd.cc.
References DPRINTF, INT_VSYNC, and intRaise().
Referenced by enabled(), and HDLcd::PixelPump::onVSyncBegin().
pxlVSyncEnd()
void HDLcd::pxlVSyncEnd ()
Definition at line 544 of file hdlcd.cc.
References dmaEngine, DPRINTF, and fb_base.
Referenced by enabled(), and HDLcd::PixelPump::onVSyncEnd().
read()
Tick HDLcd::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 238 of file hdlcd.cc.
References data, DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic_if, AmbaDmaDevice::pioAddr, AmbaDmaDevice::pioDelay, AmbaDmaDevice::pioSize, readReg(), and Packet::setLE().
readReg()
uint32_t HDLcd::readReg (Addr offset) protected
Definition at line 277 of file hdlcd.cc.
References Blue_Select, blue_select, Bus_Options, bus_options, Command, command, Fb_Base, fb_base, Fb_Line_Count, fb_line_count, Fb_Line_Length, fb_line_length, Fb_Line_Pitch, fb_line_pitch, Green_Select, green_select, H_Back_Porch, h_back_porch, H_Data, h_data, H_Front_Porch, h_front_porch, H_Sync, h_sync, Int_Clear, Int_Mask, int_mask, Int_RawStat, int_rawstat, Int_Status, intStatus(), panic, Pixel_Format, pixel_format, Polarities, polarities, Red_Select, red_select, V_Back_Porch, v_back_porch, V_Data, v_data, V_Front_Porch, v_front_porch, V_Sync, v_sync, and Version.
Referenced by read().
regStats()
void HDLcd::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 103 of file hdlcd.cc.
References SimObject::name(), Stats::nozero, Stats::Group::regStats(), and stats.
serialize()
void HDLcd::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 117 of file hdlcd.cc.
References blue_select, bus_options, command, dmaEngine, DPRINTF, enabled(), fb_base, fb_line_count, fb_line_length, fb_line_pitch, green_select, h_back_porch, h_data, h_front_porch, h_sync, int_mask, int_rawstat, pixel_format, pixelPump, polarities, red_select, SERIALIZE_OBJ, SERIALIZE_SCALAR, v_back_porch, v_data, v_front_porch, and v_sync.
setInterrupts()
void HDLcd::setInterrupts (uint32_t ints, uint32_t mask) protected
Assign new interrupt values and update interrupt signals.
A new interrupt is scheduled signalled if the set of unmasked interrupts goes empty to non-empty. Conversely, if the set of unmasked interrupts goes from non-empty to empty, the interrupt signal is cleared.
Parameters
ints New raw interrupt status
mask New interrupt mask
Definition at line 590 of file hdlcd.cc.
References BaseGic::clearInt(), AmbaDmaDevice::gic, int_mask, int_rawstat, AmbaDmaDevice::intNum, intStatus(), ArmISA::mask, and BaseGic::sendInt().
Referenced by enabled(), intClear(), intMask(), and intRaise().
unserialize()
void HDLcd::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 154 of file hdlcd.cc.
References blue_select, bus_options, command, conv, createDmaEngine(), Serializable::currentSection(), dmaEngine, DPRINTF, enabled(), fb_base, fb_line_count, fb_line_length, fb_line_pitch, green_select, h_back_porch, h_data, h_front_porch, h_sync, int_mask, int_rawstat, pixel_format, pixelConverter(), pixelPump, polarities, red_select, CheckpointIn::sectionExists(), BasePixelPump::unserialize(), UNSERIALIZE_SCALAR, v_back_porch, v_data, v_front_porch, and v_sync.
virtRefresh()
void HDLcd::virtRefresh () protected
Handler for fast frame refresh in KVM-mode.
Definition at line 230 of file hdlcd.cc.
References curTick(), pixelPump, BasePixelPump::renderFrame(), EventManager::schedule(), virtRefreshEvent, and virtRefreshRate.
Referenced by HDLcd().
write()
Tick HDLcd::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 258 of file hdlcd.cc.
References data, DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeAtomicResponse(), panic_if, AmbaDmaDevice::pioAddr, AmbaDmaDevice::pioDelay, AmbaDmaDevice::pioSize, and writeReg().
writeReg()
void HDLcd::writeReg (Addr offset, uint32_t value) protected
Definition at line 316 of file hdlcd.cc.
References Blue_Select, blue_select, burst_len, Bus_Options, bus_options, cmdDisable(), cmdEnable(), Command, command, DPRINTF, Fb_Base, fb_base, Fb_Line_Count, fb_line_count, Fb_Line_Length, fb_line_length, Fb_Line_Pitch, fb_line_pitch, Green_Select, green_select, H_Back_Porch, h_back_porch, H_Data, h_data, H_Front_Porch, h_front_porch, H_Sync, h_sync, Int_Clear, Int_Mask, Int_RawStat, Int_Status, intClear(), intMask(), intRaise(), max_outstanding, panic, Pixel_Format, pixel_format, Polarities, polarities, Red_Select, red_select, V_Back_Porch, v_back_porch, V_Data, v_data, V_Front_Porch, v_front_porch, V_Sync, v_sync, and Version.
Referenced by write().
Member Data Documentation
addrRanges
const AddrRangeList HDLcd::addrRanges protected
Definition at line 116 of file hdlcd.hh.
Referenced by getAddrRanges().
AXI_PORT_WIDTH
constexpr size_t HDLcd::AXI_PORT_WIDTH = 8 static protected
AXI port width in bytes.
Definition at line 157 of file hdlcd.hh.
Referenced by createDmaEngine().
big_endian
Bitfield<31> HDLcd::big_endian protected
Definition at line 216 of file hdlcd.hh.
blue_select
ColorSelectReg HDLcd::blue_select protected
Blue color select register.
Definition at line 255 of file hdlcd.hh.
Referenced by HDLcd(), pixelConverter(), readReg(), serialize(), unserialize(), and writeReg().
burst_len
HDLcd::burst_len protected
Definition at line 187 of file hdlcd.hh.
Referenced by writeReg().
bus_options
BusOptsReg HDLcd::bus_options protected
Bus options register.
Definition at line 241 of file hdlcd.hh.
Referenced by createDmaEngine(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
BUS_OPTIONS_RESETV
constexpr size_t HDLcd::BUS_OPTIONS_RESETV = 0x408 static protected
Reset value for Bus_Options register.
Definition at line 151 of file hdlcd.hh.
Referenced by HDLcd().
bytes_per_pixel
Bitfield<4,3> HDLcd::bytes_per_pixel protected
Definition at line 214 of file hdlcd.hh.
command
CommandReg HDLcd::command protected
Command register.
Definition at line 251 of file hdlcd.hh.
Referenced by HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
conv
PixelConverter HDLcd::conv protected
Cached pixel converter, set when the converter is enabled.
Definition at line 362 of file hdlcd.hh.
Referenced by cmdEnable(), HDLcd(), pxlNext(), and unserialize().
data_polarity
Bitfield<3> HDLcd::data_polarity protected
Definition at line 202 of file hdlcd.hh.
dataen_polarity
Bitfield<2> HDLcd::dataen_polarity protected
Definition at line 201 of file hdlcd.hh.
default_color
Bitfield<23,16> HDLcd::default_color protected
Definition at line 224 of file hdlcd.hh.
dmaEngine
std::unique_ptr<DmaEngine> HDLcd::dmaEngine protected
Definition at line 394 of file hdlcd.hh.
Referenced by cmdDisable(), createDmaEngine(), pxlFrameDone(), pxlNext(), pxlUnderrun(), pxlVSyncEnd(), serialize(), and unserialize().
enableCapture
const bool HDLcd::enableCapture protected
Definition at line 117 of file hdlcd.hh.
Referenced by HDLcd(), and pxlFrameDone().
fb_base
uint32_t HDLcd::fb_base protected
Frame buffer base address register.
Definition at line 237 of file hdlcd.hh.
Referenced by HDLcd(), pxlVSyncEnd(), readReg(), serialize(), HDLcd::DmaEngine::startFrame(), unserialize(), and writeReg().
fb_line_count [1/2]
HDLcd::fb_line_count protected
Definition at line 182 of file hdlcd.hh.
Referenced by createDmaEngine(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
fb_line_count [2/2]
FbLineCountReg HDLcd::fb_line_count protected
Frame buffer Line count register.
Definition at line 239 of file hdlcd.hh.
fb_line_length
uint32_t HDLcd::fb_line_length protected
Frame buffer Line length register.
Definition at line 238 of file hdlcd.hh.
Referenced by createDmaEngine(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
fb_line_pitch
int32_t HDLcd::fb_line_pitch protected
Frame buffer Line pitch register.
Definition at line 240 of file hdlcd.hh.
Referenced by createDmaEngine(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
green_select
ColorSelectReg HDLcd::green_select protected
Green color select register.
Definition at line 254 of file hdlcd.hh.
Referenced by HDLcd(), pixelConverter(), readReg(), serialize(), unserialize(), and writeReg().
h_back_porch
TimingReg HDLcd::h_back_porch protected
Horizontal back porch width register.
Definition at line 247 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
h_data
TimingReg HDLcd::h_data protected
Horizontal data width register.
Definition at line 248 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
h_front_porch
TimingReg HDLcd::h_front_porch protected
Horizontal front porch width reg.
Definition at line 249 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
h_sync
TimingReg HDLcd::h_sync protected
Horizontal sync width register.
Definition at line 246 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
hsync_polarity
Bitfield<1> HDLcd::hsync_polarity protected
Definition at line 200 of file hdlcd.hh.
imgFormat
Enums::ImageFormat HDLcd::imgFormat protected
Image Format.
Definition at line 356 of file hdlcd.hh.
Referenced by HDLcd().
imgWriter
std::unique_ptr<ImgWriter> HDLcd::imgWriter protected
Helper to write out bitmaps.
Definition at line 353 of file hdlcd.hh.
Referenced by HDLcd(), and pxlFrameDone().
INT_BUS_ERROR
constexpr uint32_t HDLcd::INT_BUS_ERROR = (1UL << 1) static protected
Definition at line 177 of file hdlcd.hh.
int_mask
uint32_t HDLcd::int_mask protected
Interrupt mask register.
Definition at line 236 of file hdlcd.hh.
Referenced by HDLcd(), intClear(), intRaise(), intStatus(), readReg(), serialize(), setInterrupts(), and unserialize().
int_rawstat
uint32_t HDLcd::int_rawstat protected
Interrupt raw status register.
Definition at line 235 of file hdlcd.hh.
Referenced by HDLcd(), intClear(), intMask(), intRaise(), intStatus(), readReg(), serialize(), setInterrupts(), and unserialize().
INT_UNDERRUN
constexpr uint32_t HDLcd::INT_UNDERRUN = (1UL << 3) static protected
Definition at line 179 of file hdlcd.hh.
Referenced by pxlUnderrun().
INT_VSYNC
constexpr uint32_t HDLcd::INT_VSYNC = (1UL << 2) static protected
Definition at line 178 of file hdlcd.hh.
Referenced by pxlVSyncBegin().
MAX_BURST_LEN
constexpr size_t HDLcd::MAX_BURST_LEN = 16 static protected
max number of beats delivered in one dma burst
Definition at line 160 of file hdlcd.hh.
Referenced by createDmaEngine().
max_outstanding
Bitfield<11,8> HDLcd::max_outstanding protected
Definition at line 189 of file hdlcd.hh.
Referenced by writeReg().
MAX_PIXEL_SIZE
constexpr size_t HDLcd::MAX_PIXEL_SIZE = 4 static protected
Maximum number of bytes per pixel.
Definition at line 163 of file hdlcd.hh.
Referenced by pxlNext().
offset
HDLcd::offset protected
Definition at line 220 of file hdlcd.hh.
pic
OutputStream* HDLcd::pic protected
Picture of what the current frame buffer looks like.
Definition at line 359 of file hdlcd.hh.
Referenced by HDLcd(), and pxlFrameDone().
pixel_format
PixelFormatReg HDLcd::pixel_format protected
Pixel format register.
Definition at line 252 of file hdlcd.hh.
Referenced by HDLcd(), pixelConverter(), readReg(), serialize(), unserialize(), and writeReg().
pixelBufferSize
const Addr HDLcd::pixelBufferSize protected
Definition at line 118 of file hdlcd.hh.
Referenced by createDmaEngine(), and HDLcd().
pixelPump
PixelPump HDLcd::pixelPump protected
Definition at line 364 of file hdlcd.hh.
Referenced by cmdDisable(), cmdEnable(), drainResume(), HDLcd(), pxlFrameDone(), serialize(), unserialize(), and virtRefresh().
polarities
PolaritiesReg HDLcd::polarities protected
Polarities register.
Definition at line 250 of file hdlcd.hh.
Referenced by HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
product_id
Bitfield<31,16> HDLcd::product_id protected
Definition at line 173 of file hdlcd.hh.
pxlclk_polarity
Bitfield<4> HDLcd::pxlclk_polarity protected
Definition at line 203 of file hdlcd.hh.
red_select
ColorSelectReg HDLcd::red_select protected
Red color select register.
Definition at line 253 of file hdlcd.hh.
Referenced by HDLcd(), pixelConverter(), readReg(), serialize(), unserialize(), and writeReg().
reserved_15_12
Bitfield<15,12> HDLcd::reserved_15_12 protected
Definition at line 223 of file hdlcd.hh.
reserved_2_0
HDLcd::reserved_2_0 protected
Definition at line 213 of file hdlcd.hh.
reserved_30_5
Bitfield<30,5> HDLcd::reserved_30_5 protected
Definition at line 215 of file hdlcd.hh.
reserved_31_1
Bitfield<31,1> HDLcd::reserved_31_1 protected
Definition at line 209 of file hdlcd.hh.
reserved_31_12
Bitfield< 31, 12 > HDLcd::reserved_31_12 protected
Definition at line 183 of file hdlcd.hh.
reserved_31_24
Bitfield<31,24> HDLcd::reserved_31_24 protected
Definition at line 225 of file hdlcd.hh.
reserved_31_5
Bitfield<31,5> HDLcd::reserved_31_5 protected
Definition at line 204 of file hdlcd.hh.
reserved_7_5
Bitfield< 7, 5 > HDLcd::reserved_7_5 protected
Definition at line 188 of file hdlcd.hh.
size
Bitfield<11,8> HDLcd::size protected
Definition at line 222 of file hdlcd.hh.
stats
struct { ... } HDLcd::stats
Referenced by pxlUnderrun(), and regStats().
underruns
Stats::Scalar HDLcd::underruns
Definition at line 398 of file hdlcd.hh.
v_back_porch
TimingReg HDLcd::v_back_porch protected
Vertical back porch width register.
Definition at line 243 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
v_data
TimingReg HDLcd::v_data protected
Vertical data width register.
Definition at line 244 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
v_front_porch
TimingReg HDLcd::v_front_porch protected
Vertical front porch width register.
Definition at line 245 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
v_sync
TimingReg HDLcd::v_sync protected
Vertical sync width register.
Definition at line 242 of file hdlcd.hh.
Referenced by displayTimings(), HDLcd(), readReg(), serialize(), unserialize(), and writeReg().
val
HDLcd::val protected
Definition at line 194 of file hdlcd.hh.
version_major
Bitfield<15,8> HDLcd::version_major protected
Definition at line 172 of file hdlcd.hh.
version_minor
HDLcd::version_minor protected
Definition at line 171 of file hdlcd.hh.
VERSION_RESETV
constexpr size_t HDLcd::VERSION_RESETV = 0x1CDC0000 static protected
Reset value for Version register.
Definition at line 154 of file hdlcd.hh.
Referenced by HDLcd().
virtRefreshEvent
EventFunctionWrapper HDLcd::virtRefreshEvent protected
Definition at line 350 of file hdlcd.hh.
Referenced by cmdDisable(), cmdEnable(), HDLcd(), and virtRefresh().
virtRefreshRate
const Tick HDLcd::virtRefreshRate protected
Definition at line 119 of file hdlcd.hh.
Referenced by HDLcd(), and virtRefresh().
vnc
VncInput* HDLcd::vnc protected
Definition at line 113 of file hdlcd.hh.
Referenced by drainResume(), HDLcd(), and pxlFrameDone().
workaroundDmaLineCount
const bool HDLcd::workaroundDmaLineCount protected
Definition at line 115 of file hdlcd.hh.
Referenced by createDmaEngine().
workaroundSwapRB
const bool HDLcd::workaroundSwapRB protected
Definition at line 114 of file hdlcd.hh.
Referenced by pixelConverter().
The documentation for this class was generated from the following files:
dev/arm/hdlcd.hh
dev/arm/hdlcd.cc