gem5: RubySystem Class Reference
RubySystem Class Reference
#include <RubySystem.hh>
Public Types
typedef RubySystemParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
RubySystem (const Params *p)
~RubySystem ()
SimpleMemory * getPhysMem ()
Cycles getStartCycle ()
bool getAccessBackingStore ()
Profiler * getProfiler ()
void regStats () override
Callback to set stat parameters.
void collateStats ()
void resetStats () override
Callback to reset stats.
void memWriteback () override
Write back dirty buffers to memory using functional writes.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void drainResume () override
Resume execution after a successful drain.
void process ()
void startup () override
startup() is the final initialization call before simulation.
bool functionalRead (Packet *ptr)
bool functionalWrite (Packet *ptr)
void registerNetwork (Network *)
void registerAbstractController (AbstractController *)
bool eventQueueEmpty ()
void enqueueRubyEvent (Tick tick)
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Static Public Member Functions
static int getRandomization ()
static uint32_t getBlockSizeBytes ()
static uint32_t getBlockSizeBits ()
static uint32_t getMemorySizeBits ()
static bool getWarmupEnabled ()
static bool getCooldownEnabled ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
Profiler * m_profiler
CacheRecorder * m_cache_recorder
std::vector< std::map< uint32_t, AbstractController * > > m_abstract_controls
Private Member Functions
RubySystem (const RubySystem &obj)
RubySystem & operator= (const RubySystem &obj)
void makeCacheRecorder (uint8_t *uncompressed_trace, uint64_t cache_trace_size, uint64_t block_size_bytes)
void processRubyEvent ()
Static Private Member Functions
static void readCompressedTrace (std::string filename, uint8_t *&raw_data, uint64_t &uncompressed_trace_size)
static void writeCompressedTrace (uint8_t *raw_data, std::string file, uint64_t uncompressed_trace_size)
Private Attributes
SimpleMemory * m_phys_mem
const bool m_access_backing_store
Network * m_network
std::vector< AbstractController * > m_abs_cntrl_vec
Cycles m_start_cycle
Static Private Attributes
static bool m_randomization
static uint32_t m_block_size_bytes
static uint32_t m_block_size_bits
static uint32_t m_memory_size_bits
static bool m_warmup_enabled = false
static unsigned m_systems_to_warmup = 0
static bool m_cooldown_enabled = false
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 50 of file RubySystem.hh.
Member Typedef Documentation
Params
typedef RubySystemParams RubySystem::Params
Definition at line 53 of file RubySystem.hh.
Constructor & Destructor Documentation
RubySystem() [1/2]
RubySystem::RubySystem (const Params * p)
Definition at line 59 of file RubySystem.cc.
References floorLog2(), isPowerOf2(), m_abstract_controls, m_block_size_bits, m_block_size_bytes, m_memory_size_bits, m_phys_mem, m_profiler, m_randomization, and Stats::registerDumpCallback().
Referenced by enqueueRubyEvent(), and functionalWrite().
~RubySystem()
RubySystem::~RubySystem ()
Definition at line 95 of file RubySystem.cc.
References m_network, and m_profiler.
RubySystem() [2/2]
RubySystem::RubySystem (const RubySystem & obj) private
Member Function Documentation
collateStats()
void RubySystem::collateStats () inline
Definition at line 81 of file RubySystem.hh.
References Profiler::collateStats(), drainResume(), functionalRead(), functionalWrite(), m_profiler, memWriteback(), process(), registerAbstractController(), registerNetwork(), resetStats(), serialize(), startup(), and unserialize().
Referenced by RubyStatsCallback::process().
drainResume()
void RubySystem::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 263 of file RubySystem.cc.
References m_cache_recorder.
Referenced by collateStats().
enqueueRubyEvent()
void RubySystem::enqueueRubyEvent (Tick tick) inline
Definition at line 97 of file RubySystem.hh.
References ArmISA::e, makeCacheRecorder(), operator=(), processRubyEvent(), readCompressedTrace(), RubySystem(), EventManager::schedule(), and writeCompressedTrace().
Referenced by memWriteback(), and startup().
eventQueueEmpty()
bool RubySystem::eventQueueEmpty () inline
Definition at line 96 of file RubySystem.hh.
References EventQueue::empty(), and EventManager::eventq.
functionalRead()
bool RubySystem::functionalRead (Packet * ptr)
Definition at line 399 of file RubySystem.cc.
References DPRINTF, Packet::getAddr(), ArmISA::i, m_abs_cntrl_vec, makeLineAddress(), and warn.
Referenced by collateStats(), and RubyPort::MemSlavePort::recvFunctional().
functionalWrite()
bool RubySystem::functionalWrite (Packet * ptr)
Definition at line 488 of file RubySystem.cc.
References addr, DPRINTF, Network::functionalWrite(), Packet::getAddr(), ArmISA::i, M5_VAR_USED, m_abs_cntrl_vec, m_network, makeLineAddress(), and RubySystem().
Referenced by collateStats(), and RubyPort::MemSlavePort::recvFunctional().
getAccessBackingStore()
bool RubySystem::getAccessBackingStore () inline
Definition at line 67 of file RubySystem.hh.
References m_access_backing_store.
getBlockSizeBits()
static uint32_t RubySystem::getBlockSizeBits () inline static
Definition at line 60 of file RubySystem.hh.
References m_block_size_bits.
Referenced by getOffset(), DMASequencer::init(), makeLineAddress(), DirectoryMemory::mapAddressToLocalIdx(), and PrefetchEntry::PrefetchEntry().
getBlockSizeBytes()
static uint32_t RubySystem::getBlockSizeBytes () inline static
Definition at line 59 of file RubySystem.hh.
References m_block_size_bytes.
Referenced by Prefetcher::accessNonunitFilter(), DataBlock::alloc(), DataBlock::atomicPartial(), CacheRecorder::CacheRecorder(), DataBlock::clear(), DataBlock::copyPartial(), DataBlock::DataBlock(), CacheRecorder::enqueueNextFetchRequest(), DataBlock::equal(), DataBlock::getData(), CacheMemory::init(), DirectoryMemory::init(), Network::init(), DMASequencer::issueNext(), GPUCoalescer::issueRequest(), makeNextStrideAddress(), DMASequencer::makeRequest(), memWriteback(), DataBlock::operator=(), DataBlock::print(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvFunctional(), RubyPort::MemSlavePort::recvTimingReq(), AbstractController::recvTimingResp(), RubyPort::ruby_eviction_callback(), serialize(), DataBlock::setData(), and unserialize().
getCooldownEnabled()
static bool RubySystem::getCooldownEnabled () inline static
Definition at line 63 of file RubySystem.hh.
References m_cooldown_enabled.
Referenced by Sequencer::hitCallback(), and processRubyEvent().
getMemorySizeBits()
static uint32_t RubySystem::getMemorySizeBits () inline static
Definition at line 61 of file RubySystem.hh.
References m_memory_size_bits.
getPhysMem()
SimpleMemory* RubySystem::getPhysMem () inline
Definition at line 65 of file RubySystem.hh.
References m_phys_mem.
Referenced by RubyPort::MemSlavePort::hitCallback(), and RubyPort::MemSlavePort::recvFunctional().
getProfiler()
Profiler* RubySystem::getProfiler () inline
Definition at line 71 of file RubySystem.hh.
References m_profiler.
getRandomization()
static int RubySystem::getRandomization () inline static
Definition at line 58 of file RubySystem.hh.
References m_randomization.
Referenced by MessageBuffer::enqueue().
getStartCycle()
Cycles RubySystem::getStartCycle () inline
Definition at line 66 of file RubySystem.hh.
References m_start_cycle.
Referenced by Throttle::collateStats(), and GarnetNetwork::collateStats().
getWarmupEnabled()
static bool RubySystem::getWarmupEnabled () inline static
Definition at line 62 of file RubySystem.hh.
References m_warmup_enabled.
Referenced by MessageBuffer::enqueue(), Sequencer::hitCallback(), processRubyEvent(), AbstractController::queueMemoryRead(), and AbstractController::queueMemoryWrite().
makeCacheRecorder()
void RubySystem::makeCacheRecorder (uint8_t * uncompressed_trace, uint64_t cache_trace_size, uint64_t block_size_bytes) private
Definition at line 102 of file RubySystem.cc.
References m_abs_cntrl_vec, and m_cache_recorder.
Referenced by enqueueRubyEvent(), memWriteback(), and unserialize().
memWriteback()
void RubySystem::memWriteback () override virtual
Write back dirty buffers to memory using functional writes.
After returning, an object implementing this method should have written all its dirty data back to memory. This method is typically used to prepare a system with caches for checkpointing.
Reimplemented from SimObject.
Definition at line 135 of file RubySystem.cc.
References curTick(), EventQueue::deschedule(), DPRINTF, EventQueue::empty(), enqueueRubyEvent(), MipsISA::event, EventManager::eventq, getBlockSizeBytes(), EventQueue::getHead(), Event::isAutoDelete(), m_abs_cntrl_vec, m_cache_recorder, m_cooldown_enabled, makeCacheRecorder(), Event::name(), EventQueue::schedule(), EventManager::setCurTick(), simulate(), warn_once, and Event::when().
Referenced by collateStats().
operator=()
RubySystem& RubySystem::operator= (const RubySystem & obj) private
Referenced by enqueueRubyEvent().
process()
void RubySystem::process ()
Referenced by collateStats().
processRubyEvent()
void RubySystem::processRubyEvent () private
Definition at line 383 of file RubySystem.cc.
References CacheRecorder::enqueueNextFetchRequest(), CacheRecorder::enqueueNextFlushRequest(), getCooldownEnabled(), getWarmupEnabled(), and m_cache_recorder.
Referenced by enqueueRubyEvent().
readCompressedTrace()
void RubySystem::readCompressedTrace (std::string filename, uint8_t *& raw_data, uint64_t & uncompressed_trace_size) static private
Definition at line 274 of file RubySystem.cc.
References fatal, and ArmISA::fd.
Referenced by enqueueRubyEvent(), and unserialize().
registerAbstractController()
void RubySystem::registerAbstractController (AbstractController * cntrl)
Definition at line 87 of file RubySystem.cc.
References AbstractController::getMachineID(), m_abs_cntrl_vec, and m_abstract_controls.
Referenced by collateStats().
registerNetwork()
void RubySystem::registerNetwork (Network * network_ptr)
Definition at line 81 of file RubySystem.cc.
References m_network.
Referenced by collateStats().
regStats()
void RubySystem::regStats () inline override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 77 of file RubySystem.hh.
References m_profiler, SimObject::name(), Profiler::regStats(), and Stats::Group::regStats().
resetStats()
void RubySystem::resetStats () override virtual
Callback to reset stats.
Reimplemented from Stats::Group.
Definition at line 393 of file RubySystem.cc.
References Clocked::curCycle(), and m_start_cycle.
Referenced by collateStats(), and startup().
serialize()
void RubySystem::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 236 of file RubySystem.cc.
References CacheRecorder::aggregateRecords(), fatal, getBlockSizeBytes(), m_cache_recorder, SimObject::name(), SERIALIZE_SCALAR, and writeCompressedTrace().
Referenced by collateStats().
startup()
void RubySystem::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 332 of file RubySystem.cc.
References curTick(), DPRINTF, enqueueRubyEvent(), EventManager::eventq, m_cache_recorder, m_systems_to_warmup, m_warmup_enabled, EventQueue::replaceHead(), Clocked::resetClock(), resetStats(), EventManager::setCurTick(), and simulate().
Referenced by collateStats().
unserialize()
void RubySystem::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 305 of file RubySystem.cc.
References CheckpointIn::cptDir, getBlockSizeBytes(), m_systems_to_warmup, m_warmup_enabled, makeCacheRecorder(), readCompressedTrace(), UNSERIALIZE_OPT_SCALAR, and UNSERIALIZE_SCALAR.
Referenced by collateStats().
writeCompressedTrace()
void RubySystem::writeCompressedTrace (uint8_t * raw_data, std::string file, uint64_t uncompressed_trace_size) static private
Definition at line 207 of file RubySystem.cc.
References CheckpointIn::dir(), fatal, and ArmISA::fd.
Referenced by enqueueRubyEvent(), and serialize().
Member Data Documentation
m_abs_cntrl_vec
std::vector<AbstractController *> RubySystem::m_abs_cntrl_vec private
Definition at line 134 of file RubySystem.hh.
Referenced by functionalRead(), functionalWrite(), makeCacheRecorder(), memWriteback(), and registerAbstractController().
m_abstract_controls
std::vector<std::map<uint32_t, AbstractController *> > RubySystem::m_abstract_controls
Definition at line 140 of file RubySystem.hh.
Referenced by Profiler::collateStats(), RubyPort::MemSlavePort::recvAtomic(), registerAbstractController(), and RubySystem().
m_access_backing_store
const bool RubySystem::m_access_backing_store private
Definition at line 131 of file RubySystem.hh.
Referenced by getAccessBackingStore().
m_block_size_bits
uint32_t RubySystem::m_block_size_bits static private
Definition at line 124 of file RubySystem.hh.
Referenced by getBlockSizeBits(), and RubySystem().
m_block_size_bytes
uint32_t RubySystem::m_block_size_bytes static private
Definition at line 123 of file RubySystem.hh.
Referenced by getBlockSizeBytes(), and RubySystem().
m_cache_recorder
CacheRecorder* RubySystem::m_cache_recorder
Definition at line 139 of file RubySystem.hh.
Referenced by drainResume(), Sequencer::hitCallback(), makeCacheRecorder(), memWriteback(), processRubyEvent(), serialize(), and startup().
m_cooldown_enabled
bool RubySystem::m_cooldown_enabled = false static private
Definition at line 129 of file RubySystem.hh.
Referenced by getCooldownEnabled(), and memWriteback().
m_memory_size_bits
uint32_t RubySystem::m_memory_size_bits static private
Definition at line 125 of file RubySystem.hh.
Referenced by getMemorySizeBits(), and RubySystem().
m_network
Network* RubySystem::m_network private
Definition at line 133 of file RubySystem.hh.
Referenced by functionalWrite(), registerNetwork(), and ~RubySystem().
m_phys_mem
SimpleMemory* RubySystem::m_phys_mem private
Definition at line 130 of file RubySystem.hh.
Referenced by getPhysMem(), and RubySystem().
m_profiler
Profiler* RubySystem::m_profiler
Definition at line 138 of file RubySystem.hh.
Referenced by collateStats(), getProfiler(), regStats(), RubySystem(), and ~RubySystem().
m_randomization
bool RubySystem::m_randomization static private
Definition at line 122 of file RubySystem.hh.
Referenced by getRandomization(), and RubySystem().
m_start_cycle
Cycles RubySystem::m_start_cycle private
Definition at line 135 of file RubySystem.hh.
Referenced by getStartCycle(), and resetStats().
m_systems_to_warmup
unsigned RubySystem::m_systems_to_warmup = 0 static private
Definition at line 128 of file RubySystem.hh.
Referenced by startup(), and unserialize().
m_warmup_enabled
bool RubySystem::m_warmup_enabled = false static private
Definition at line 127 of file RubySystem.hh.
Referenced by getWarmupEnabled(), startup(), and unserialize().
The documentation for this class was generated from the following files:
mem/ruby/system/RubySystem.hh
mem/ruby/system/RubySystem.cc