gem5: flitBuffer Class Reference
flitBuffer Class Reference
#include <flitBuffer.hh>
Public Member Functions
flitBuffer ()
flitBuffer (int maximum_size)
bool isReady (Cycles curTime)
bool isEmpty ()
void print (std::ostream &out) const
bool isFull ()
void setMaxSize (int maximum)
int getSize () const
flit * getTopFlit ()
flit * peekTopFlit ()
void insert (flit *flt)
uint32_t functionalWrite (Packet *pkt)
Private Attributes
std::vector< flit * > m_buffer
int max_size
Detailed Description
Definition at line 44 of file flitBuffer.hh.
Constructor & Destructor Documentation
flitBuffer() [1/2]
flitBuffer::flitBuffer ()
Definition at line 36 of file flitBuffer.cc.
References INFINITE_, and max_size.
flitBuffer() [2/2]
flitBuffer::flitBuffer (int maximum_size)
Definition at line 41 of file flitBuffer.cc.
References max_size.
Member Function Documentation
functionalWrite()
uint32_t flitBuffer::functionalWrite (Packet * pkt)
Definition at line 82 of file flitBuffer.cc.
References ArmISA::i, and m_buffer.
Referenced by NetworkLink::functionalWrite(), NetworkInterface::functionalWrite(), VirtualChannel::functionalWrite(), OutputUnit::functionalWrite(), and insert().
getSize()
int flitBuffer::getSize () const inline
Definition at line 55 of file flitBuffer.hh.
References m_buffer.
Referenced by NetworkInterface::wakeup().
getTopFlit()
flit* flitBuffer::getTopFlit () inline
Definition at line 58 of file flitBuffer.hh.
References ArmISA::f, flit::greater(), and m_buffer.
Referenced by NetworkLink::consumeLink(), VirtualChannel::getTopFlit(), and NetworkLink::wakeup().
insert()
void flitBuffer::insert (flit * flt) inline
Definition at line 73 of file flitBuffer.hh.
References functionalWrite(), flit::greater(), and m_buffer.
Referenced by InputUnit::increment_credit(), OutputUnit::insert_flit(), VirtualChannel::insertFlit(), NetworkInterface::scheduleOutputLink(), NetworkInterface::sendCredit(), and NetworkLink::wakeup().
isEmpty()
bool flitBuffer::isEmpty ()
Definition at line 47 of file flitBuffer.cc.
References m_buffer.
isFull()
bool flitBuffer::isFull ()
Definition at line 70 of file flitBuffer.cc.
References m_buffer, and max_size.
isReady()
bool flitBuffer::isReady (Cycles curTime)
Definition at line 53 of file flitBuffer.cc.
References flit::get_time(), m_buffer, and peekTopFlit().
Referenced by VirtualChannel::isReady(), NetworkLink::isReady(), VirtualChannel::need_stage(), and NetworkLink::wakeup().
peekTopFlit()
flit* flitBuffer::peekTopFlit () inline
Definition at line 67 of file flitBuffer.hh.
References m_buffer.
Referenced by isReady(), VirtualChannel::need_stage(), NetworkLink::peekLink(), and VirtualChannel::peekTopFlit().
print()
void flitBuffer::print (std::ostream & out) const
Definition at line 64 of file flitBuffer.cc.
References m_buffer.
Referenced by operator<<().
setMaxSize()
void flitBuffer::setMaxSize (int maximum)
Definition at line 76 of file flitBuffer.cc.
References max_size.
Member Data Documentation
m_buffer
std::vector<flit *> flitBuffer::m_buffer private
Definition at line 82 of file flitBuffer.hh.
Referenced by functionalWrite(), getSize(), getTopFlit(), insert(), isEmpty(), isFull(), isReady(), peekTopFlit(), and print().
max_size
int flitBuffer::max_size private
Definition at line 83 of file flitBuffer.hh.
Referenced by flitBuffer(), isFull(), and setMaxSize().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/flitBuffer.hh
mem/ruby/network/garnet2.0/flitBuffer.cc