gem5: sc_gem5::VcdTraceValInt< T > Class Template Reference
sc_gem5::VcdTraceValInt< T > Class Template Reference
Public Member Functions
void output (std::ostream &os) override
Public Member Functions inherited from sc_gem5::VcdTraceVal< T >
VcdTraceVal (const T *t, const std::string &vcd_name, int width)
Public Member Functions inherited from sc_gem5::TraceVal< T, VcdTraceValBase >
TraceVal (const T *_t, int _width)
~TraceVal ()
void finalize () override
const T & value ()
bool check () override
Public Member Functions inherited from sc_gem5::VcdTraceValBase
VcdTraceValBase (int width)
~VcdTraceValBase ()
void vcdName (const std::string &vcd_name)
const std::string & vcdName ()
virtual std::string vcdType ()
Public Member Functions inherited from sc_gem5::TraceValBase
TraceValBase (int _width)
virtual ~TraceValBase ()
int width ()
Additional Inherited Members
Public Types inherited from sc_gem5::VcdTraceVal< T >
typedef T TracedType
Protected Member Functions inherited from sc_gem5::VcdTraceValBase
const char * stripLeadingBits (const char *orig)
char scLogicToVcdState (char in)
void printVal (std::ostream &os, const std::string &rep)
Protected Attributes inherited from sc_gem5::VcdTraceValBase
std::string _vcdName
Protected Attributes inherited from sc_gem5::TraceValBase
int _width
Detailed Description
template<typename T>
class sc_gem5::VcdTraceValInt< T >
Definition at line 594 of file vcd.cc.
Member Function Documentation
output()
template<typename T > void sc_gem5::VcdTraceValInt< T >::output (std::ostream & os) inline override virtual
Implements sc_gem5::VcdTraceValBase.
Definition at line 600 of file vcd.cc.
References bits(), ArmISA::i, ArmISA::mask, sc_gem5::VcdTraceValBase::printVal(), X86ISA::val, MipsISA::w, and sc_gem5::TraceValBase::width().
The documentation for this class was generated from the following file:
systemc/utils/vcd.cc