gem5: RiscvISA::ISA Class Reference
RiscvISA::ISA Class Reference
#include <isa.hh>
Public Types
typedef RiscvISAParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void clear ()
RegVal readMiscRegNoEffect (int misc_reg) const
RegVal readMiscReg (int misc_reg, ThreadContext *tc)
void setMiscRegNoEffect (int misc_reg, RegVal val)
void setMiscReg (int misc_reg, RegVal val, ThreadContext *tc)
RegId flattenRegId (const RegId &regId) const
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenVecIndex (int reg) const
int flattenVecElemIndex (int reg) const
int flattenVecPredIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
void startup (ThreadContext *tc)
const Params * params () const
ISA (Params *p)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
bool hpmCounterEnabled (int counter) const
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
std::vector< RegVal > miscRegFile
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 65 of file isa.hh.
Member Typedef Documentation
Params
typedef RiscvISAParams RiscvISA::ISA::Params
Definition at line 73 of file isa.hh.
Constructor & Destructor Documentation
ISA()
RiscvISA::ISA::ISA (Params * p)
Definition at line 49 of file isa.cc.
References clear(), miscRegFile, and RiscvISA::NumMiscRegs.
Referenced by startup().
Member Function Documentation
clear()
void RiscvISA::ISA::clear ()
Definition at line 61 of file isa.cc.
References MipsISA::fill, RiscvISA::FS_OFFSET, RiscvISA::MISCREG_ARCHID, RiscvISA::MISCREG_IMPID, RiscvISA::MISCREG_ISA, RiscvISA::MISCREG_MCOUNTEREN, RiscvISA::MISCREG_PRV, RiscvISA::MISCREG_SCOUNTEREN, RiscvISA::MISCREG_STATUS, RiscvISA::MISCREG_VENDORID, miscRegFile, RiscvISA::PRV_M, RiscvISA::SXL_OFFSET, ULL, and RiscvISA::UXL_OFFSET.
Referenced by ISA().
flattenCCIndex()
int RiscvISA::ISA::flattenCCIndex (int reg) const inline
Definition at line 88 of file isa.hh.
References X86ISA::reg.
flattenFloatIndex()
int RiscvISA::ISA::flattenFloatIndex (int reg) const inline
Definition at line 84 of file isa.hh.
References X86ISA::reg.
flattenIntIndex()
int RiscvISA::ISA::flattenIntIndex (int reg) const inline
Definition at line 83 of file isa.hh.
References X86ISA::reg.
flattenMiscIndex()
int RiscvISA::ISA::flattenMiscIndex (int reg) const inline
Definition at line 89 of file isa.hh.
References X86ISA::reg.
flattenRegId()
RegId RiscvISA::ISA::flattenRegId (const RegId & regId) const inline
Definition at line 82 of file isa.hh.
flattenVecElemIndex()
int RiscvISA::ISA::flattenVecElemIndex (int reg) const inline
Definition at line 86 of file isa.hh.
References X86ISA::reg.
flattenVecIndex()
int RiscvISA::ISA::flattenVecIndex (int reg) const inline
Definition at line 85 of file isa.hh.
References X86ISA::reg.
flattenVecPredIndex()
int RiscvISA::ISA::flattenVecPredIndex (int reg) const inline
Definition at line 87 of file isa.hh.
References X86ISA::reg.
hpmCounterEnabled()
bool RiscvISA::ISA::hpmCounterEnabled (int counter) const protected
Definition at line 77 of file isa.cc.
References RiscvISA::MISCREG_CYCLE, RiscvISA::MISCREG_MCOUNTEREN, RiscvISA::MISCREG_PRV, RiscvISA::MISCREG_SCOUNTEREN, miscRegFile, panic, RiscvISA::PRV_M, RiscvISA::PRV_S, RiscvISA::PRV_U, readMiscRegNoEffect(), and ULL.
Referenced by readMiscReg().
params()
const RiscvISAParams * RiscvISA::ISA::params () const
Definition at line 56 of file isa.cc.
References SimObject::_params.
Referenced by startup().
readMiscReg()
RegVal RiscvISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc)
Definition at line 113 of file isa.cc.
References ThreadContext::contextId(), Clocked::curCycle(), DPRINTF, ThreadContext::getCpuPtr(), BaseCPU::getInterruptController(), hpmCounterEnabled(), iGbReg::TxdOp::ic(), RiscvISA::MISCREG_CYCLE, RiscvISA::MISCREG_HARTID, RiscvISA::MISCREG_HPMCOUNTER03, RiscvISA::MISCREG_HPMCOUNTER31, RiscvISA::MISCREG_IE, RiscvISA::MISCREG_INSTRET, RiscvISA::MISCREG_IP, RiscvISA::MISCREG_TIME, readMiscRegNoEffect(), ThreadContext::threadId(), BaseCPU::totalInsts(), and warn.
readMiscRegNoEffect()
RegVal RiscvISA::ISA::readMiscRegNoEffect (int misc_reg) const
Definition at line 100 of file isa.cc.
References DPRINTF, miscRegFile, RiscvISA::NumMiscRegs, and panic.
Referenced by hpmCounterEnabled(), and readMiscReg().
setMiscReg()
void RiscvISA::ISA::setMiscReg (int misc_reg, RegVal val, ThreadContext * tc)
Definition at line 187 of file isa.cc.
References RiscvISA::CSRData, ThreadContext::getCpuPtr(), BaseCPU::getInterruptController(), iGbReg::TxdOp::ic(), RiscvISA::MISCREG_CYCLE, RiscvISA::MISCREG_HPMCOUNTER31, RiscvISA::MISCREG_IE, RiscvISA::MISCREG_IP, setMiscRegNoEffect(), ThreadContext::threadId(), and warn.
setMiscRegNoEffect()
void RiscvISA::ISA::setMiscRegNoEffect (int misc_reg, RegVal val)
Definition at line 176 of file isa.cc.
References DPRINTF, miscRegFile, RiscvISA::NumMiscRegs, panic, and X86ISA::val.
Referenced by setMiscReg().
startup()
void RiscvISA::ISA::startup (ThreadContext * tc) inline
Definition at line 91 of file isa.hh.
References ISA(), RiscvISA::p, params(), and SimObject::startup().
Member Data Documentation
miscRegFile
std::vector<RegVal> RiscvISA::ISA::miscRegFile protected
Definition at line 68 of file isa.hh.
Referenced by clear(), hpmCounterEnabled(), ISA(), readMiscRegNoEffect(), and setMiscRegNoEffect().
The documentation for this class was generated from the following files:
arch/riscv/isa.hh
arch/riscv/isa.cc