gem5: TAGEBase Class Reference
TAGEBase Class Reference
#include <tage_base.hh>
Classes
struct BranchInfo
struct FoldedHistory
struct TageEntry
struct ThreadHistory
Public Types
enum {
BIMODAL_ONLY = 0, TAGE_LONGEST_MATCH, BIMODAL_ALT_MATCH, TAGE_ALT_MATCH,
LAST_TAGE_PROVIDER_TYPE = TAGE_ALT_MATCH
}
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TAGEBase (const TAGEBaseParams *p)
void regStats () override
Callback to set stat parameters.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual BranchInfo * makeBranchInfo ()
virtual int bindex (Addr pc_in) const
Computes the index used to access the bimodal table.
virtual int gindex (ThreadID tid, Addr pc, int bank) const
Computes the index used to access a partially tagged table.
virtual int F (int phist, int size, int bank) const
Utility function to shuffle the path history depending on which tagged table we are accessing.
virtual uint16_t gtag (ThreadID tid, Addr pc, int bank) const
Computes the partial tag of a tagged table.
virtual bool getBimodePred (Addr pc, BranchInfo *bi) const
Get a branch prediction from the bimodal predictor.
void baseUpdate (Addr pc, bool taken, BranchInfo *bi)
Updates the bimodal predictor.
void updateGHist (uint8_t *&h, bool dir, uint8_t *tab, int &PT)
(Speculatively) updates the global branch history.
void update (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *bi)
Update TAGE.
virtual void updateHistories (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *b, bool speculative, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr, Addr target=MaxAddr)
(Speculatively) updates global histories (path and direction).
virtual void squash (ThreadID tid, bool taken, BranchInfo *bi, Addr target)
Restores speculatively updated path and direction histories.
virtual void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *bi, int nrand, Addr corrTarget, bool pred, bool preAdjustAlloc=false)
Update TAGE for conditional branches.
bool tagePredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo *bi)
TAGE prediction called from TAGE::predict.
virtual void updateStats (bool taken, BranchInfo *bi)
Update the stats.
virtual void buildTageTables ()
Instantiates the TAGE table entries.
virtual void calculateParameters ()
Calculates the history lengths and some other paramters in derived classes.
virtual void calculateIndicesAndTags (ThreadID tid, Addr branch_pc, BranchInfo *bi)
On a prediction, calculates the TAGE indices and tags for all the different history lengths.
virtual unsigned getUseAltIdx (BranchInfo *bi, Addr branch_pc)
Calculation of the index for useAltPredForNewlyAllocated On this base TAGE implementation it is always 0.
virtual void adjustAlloc (bool &alloc, bool taken, bool pred_taken)
Extra calculation to tell whether TAGE allocaitons may happen or not on an update For this base TAGE implementation it does nothing.
virtual void handleAllocAndUReset (bool alloc, bool taken, BranchInfo *bi, int nrand)
Handles Allocation and U bits reset on an update.
virtual void handleUReset ()
Handles the U bits reset.
virtual void handleTAGEUpdate (Addr branch_pc, bool taken, BranchInfo *bi)
Handles the update of the TAGE entries.
virtual void resetUctr (uint8_t &u)
Algorithm for resetting a single U counter.
virtual void extraAltCalc (BranchInfo *bi)
Extra steps for calculating altTaken For this base TAGE class it does nothing.
virtual bool isHighConfidence (BranchInfo *bi) const
void btbUpdate (ThreadID tid, Addr branch_addr, BranchInfo *&bi)
unsigned getGHR (ThreadID tid, BranchInfo *bi) const
int8_t getCtr (int hitBank, int hitBankIndex) const
unsigned getTageCtrBits () const
int getPathHist (ThreadID tid) const
bool isSpeculativeUpdateEnabled () const
size_t getSizeInBits () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
template<typename T >
static void ctrUpdate (T &ctr, bool taken, int nbits)
Updates a direction counter based on the actual branch outcome.
static void unsignedCtrUpdate (uint8_t &ctr, bool up, unsigned nbits)
Updates an unsigned counter based on up/down parameter.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions
virtual void initFoldedHistories (ThreadHistory &history)
Initialization of the folded histories.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const unsigned logRatioBiModalHystEntries
const unsigned nHistoryTables
const unsigned tagTableCounterBits
const unsigned tagTableUBits
const unsigned histBufferSize
const unsigned minHist
const unsigned maxHist
const unsigned pathHistBits
std::vector< unsigned > tagTableTagWidths
std::vector< int > logTagTableSizes
std::vector< bool > btablePrediction
std::vector< bool > btableHysteresis
TageEntry ** gtable
std::vector< ThreadHistory > threadHistory
int * histLengths
int * tableIndices
int * tableTags
std::vector< int8_t > useAltPredForNewlyAllocated
int64_t tCounter
uint64_t logUResetPeriod
const int64_t initialTCounterValue
unsigned numUseAltOnNa
unsigned useAltOnNaBits
unsigned maxNumAlloc
std::vector< bool > noSkip
const bool speculativeHistUpdate
const unsigned instShiftAmt
bool initialized
Stats::Scalar tageLongestMatchProviderCorrect
Stats::Scalar tageAltMatchProviderCorrect
Stats::Scalar bimodalAltMatchProviderCorrect
Stats::Scalar tageBimodalProviderCorrect
Stats::Scalar tageLongestMatchProviderWrong
Stats::Scalar tageAltMatchProviderWrong
Stats::Scalar bimodalAltMatchProviderWrong
Stats::Scalar tageBimodalProviderWrong
Stats::Scalar tageAltMatchProviderWouldHaveHit
Stats::Scalar tageLongestMatchProviderWouldHaveHit
Stats::Vector tageLongestMatchProvider
Stats::Vector tageAltMatchProvider
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 61 of file tage_base.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
BIMODAL_ONLY
TAGE_LONGEST_MATCH
BIMODAL_ALT_MATCH
TAGE_ALT_MATCH
LAST_TAGE_PROVIDER_TYPE
Definition at line 115 of file tage_base.hh.
Constructor & Destructor Documentation
TAGEBase()
TAGEBase::TAGEBase (const TAGEBaseParams * p)
Definition at line 48 of file tage_base.cc.
References nHistoryTables, and noSkip.
Referenced by getSizeInBits().
Member Function Documentation
adjustAlloc()
void TAGEBase::adjustAlloc (bool & alloc, bool taken, bool pred_taken) virtual
Extra calculation to tell whether TAGE allocaitons may happen or not on an update For this base TAGE implementation it does nothing.
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 433 of file tage_base.cc.
Referenced by condBranchUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
baseUpdate()
void TAGEBase::baseUpdate (Addr pc, bool taken, BranchInfo * bi)
Updates the bimodal predictor.
Parameters
pc The unshifted branch PC.
taken The actual branch outcome.
bi Pointer to information on the prediction recorded at prediction time.
Definition at line 297 of file tage_base.cc.
References TAGEBase::BranchInfo::bimodalIndex, btableHysteresis, btablePrediction, DPRINTF, and logRatioBiModalHystEntries.
Referenced by MPP_TAGE::handleTAGEUpdate(), handleTAGEUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
bindex()
int TAGEBase::bindex (Addr pc_in) const virtual
Computes the index used to access the bimodal table.
Parameters
pc_in The unshifted branch PC.
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 202 of file tage_base.cc.
References instShiftAmt, logTagTableSizes, and ULL.
Referenced by tagePredict(), and TAGEBase::BranchInfo::~BranchInfo().
btbUpdate()
void TAGEBase::btbUpdate (ThreadID tid, Addr branch_addr, BranchInfo *& bi)
Definition at line 183 of file tage_base.cc.
References TAGEBase::BranchInfo::ci, TAGEBase::FoldedHistory::comp, TAGEBase::ThreadHistory::computeIndices, TAGEBase::ThreadHistory::computeTags, TAGEBase::BranchInfo::ct0, TAGEBase::BranchInfo::ct1, DPRINTF, TAGEBase::ThreadHistory::gHist, TAGEBase::ThreadHistory::globalHistory, ArmISA::i, nHistoryTables, TAGEBase::ThreadHistory::ptGhist, speculativeHistUpdate, threadHistory, and TAGEBase::FoldedHistory::update().
Referenced by TAGE::btbUpdate(), and isHighConfidence().
buildTageTables()
void TAGEBase::buildTageTables () virtual
Instantiates the TAGE table entries.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 161 of file tage_base.cc.
References gtable, ArmISA::i, logTagTableSizes, and nHistoryTables.
Referenced by init(), and TAGEBase::BranchInfo::~BranchInfo().
calculateIndicesAndTags()
void TAGEBase::calculateIndicesAndTags (ThreadID tid, Addr branch_pc, BranchInfo * bi) virtual
On a prediction, calculates the TAGE indices and tags for all the different history lengths.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 335 of file tage_base.cc.
References gindex(), gtag(), ArmISA::i, nHistoryTables, TAGEBase::BranchInfo::tableIndices, tableIndices, TAGEBase::BranchInfo::tableTags, and tableTags.
Referenced by tagePredict(), and TAGEBase::BranchInfo::~BranchInfo().
calculateParameters()
void TAGEBase::calculateParameters () virtual
Calculates the history lengths and some other paramters in derived classes.
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 169 of file tage_base.cc.
References histLengths, ArmISA::i, maxHist, minHist, and nHistoryTables.
Referenced by init(), and TAGEBase::BranchInfo::~BranchInfo().
condBranchUpdate()
void TAGEBase::condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, BranchInfo * bi, int nrand, Addr corrTarget, bool pred, bool preAdjustAlloc = false) virtual
Update TAGE for conditional branches.
Parameters
branch_pc The unshifted branch PC.
taken Actual branch outcome.
bi Pointer to information on the prediction recorded at prediction time. Random int number from 0 to 3
corrTarget The correct branch target
pred Final prediction for this branch
preAdjustAlloc call adjustAlloc before checking pseudo newly allocated entries
Definition at line 509 of file tage_base.cc.
References adjustAlloc(), TAGEBase::BranchInfo::altTaken, ctrUpdate(), getUseAltIdx(), handleAllocAndUReset(), handleTAGEUpdate(), TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::longestMatchPred, nHistoryTables, TAGEBase::BranchInfo::pseudoNewAlloc, TAGEBase::BranchInfo::tagePred, useAltOnNaBits, and useAltPredForNewlyAllocated.
Referenced by LTAGE::update(), TAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), MPP_StatisticalCorrector::BranchInfo::~BranchInfo(), and TAGEBase::BranchInfo::~BranchInfo().
ctrUpdate()
template<typename T > template void TAGEBase::ctrUpdate (T & ctr, bool taken, int nbits) static
Updates a direction counter based on the actual branch outcome.
Parameters
ctr Reference to counter to update.
taken Actual branch outcome.
nbits Counter width.
Definition at line 256 of file tage_base.cc.
Referenced by condBranchUpdate(), MPP_TAGE::handleTAGEUpdate(), handleTAGEUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
extraAltCalc()
void TAGEBase::extraAltCalc (BranchInfo * bi) virtual
Extra steps for calculating altTaken For this base TAGE class it does nothing.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 650 of file tage_base.cc.
Referenced by tagePredict(), and TAGEBase::BranchInfo::~BranchInfo().
F()
int TAGEBase::F (int phist, int size, int bank) const virtual
Utility function to shuffle the path history depending on which tagged table we are accessing.
Parameters
phist The path history.
size Number of path history bits to use.
bank The partially tagged table to access.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 208 of file tage_base.cc.
References logTagTableSizes, and ULL.
Referenced by gindex(), and TAGEBase::BranchInfo::~BranchInfo().
getBimodePred()
bool TAGEBase::getBimodePred (Addr pc, BranchInfo * bi) const virtual
Get a branch prediction from the bimodal predictor.
Parameters
pc The unshifted branch PC.
bi Pointer to information on the prediction.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 288 of file tage_base.cc.
References TAGEBase::BranchInfo::bimodalIndex, and btablePrediction.
Referenced by TAGE_SC_L_TAGE::getBimodePred(), tagePredict(), and TAGEBase::BranchInfo::~BranchInfo().
getCtr()
int8_t TAGEBase::getCtr (int hitBank, int hitBankIndex) const
Definition at line 783 of file tage_base.cc.
References TAGEBase::TageEntry::ctr, and gtable.
Referenced by isHighConfidence(), and TAGE_SC_L::predict().
getGHR()
unsigned TAGEBase::getGHR (ThreadID tid, BranchInfo * bi) const
Definition at line 704 of file tage_base.cc.
References histBufferSize, ArmISA::i, TAGEBase::BranchInfo::ptGhist, threadHistory, and X86ISA::val.
Referenced by isHighConfidence().
getPathHist()
int TAGEBase::getPathHist (ThreadID tid) const
Definition at line 795 of file tage_base.cc.
References threadHistory.
Referenced by isHighConfidence(), MultiperspectivePerceptronTAGE::lookup(), TAGE_SC_L::predict(), TAGE_SC_L::update(), and MultiperspectivePerceptronTAGE::update().
getSizeInBits()
size_t TAGEBase::getSizeInBits () const
Definition at line 807 of file tage_base.cc.
References bits(), histLengths, ArmISA::i, logRatioBiModalHystEntries, logTagTableSizes, logUResetPeriod, nHistoryTables, numUseAltOnNa, pathHistBits, TAGEBase(), tagTableCounterBits, tagTableTagWidths, tagTableUBits, ULL, and useAltOnNaBits.
Referenced by MultiperspectivePerceptronTAGE::init(), and isHighConfidence().
getTageCtrBits()
unsigned TAGEBase::getTageCtrBits () const
Definition at line 789 of file tage_base.cc.
References tagTableCounterBits.
Referenced by isHighConfidence(), and TAGE_SC_L::predict().
getUseAltIdx()
unsigned TAGEBase::getUseAltIdx (BranchInfo * bi, Addr branch_pc) virtual
Calculation of the index for useAltPredForNewlyAllocated On this base TAGE implementation it is always 0.
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 348 of file tage_base.cc.
Referenced by condBranchUpdate(), tagePredict(), and TAGEBase::BranchInfo::~BranchInfo().
gindex()
int TAGEBase::gindex (ThreadID tid, Addr pc, int bank) const virtual
Computes the index used to access a partially tagged table.
Parameters
tid The thread ID used to select the global histories to use.
pc The unshifted branch PC.
bank The partially tagged table to access.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 225 of file tage_base.cc.
References F(), histLengths, MipsISA::index, instShiftAmt, logTagTableSizes, pathHistBits, threadHistory, and ULL.
Referenced by calculateIndicesAndTags(), and TAGEBase::BranchInfo::~BranchInfo().
gtag()
uint16_t TAGEBase::gtag (ThreadID tid, Addr pc, int bank) const virtual
Computes the partial tag of a tagged table.
Parameters
tid the thread ID used to select the global histories to use.
pc The unshifted branch PC.
bank The partially tagged table to access.
Reimplemented in TAGE_SC_L_TAGE, TAGE_SC_L_TAGE_64KB, and TAGE_SC_L_TAGE_8KB.
Definition at line 243 of file tage_base.cc.
References instShiftAmt, tagTableTagWidths, threadHistory, and ULL.
Referenced by calculateIndicesAndTags(), and TAGEBase::BranchInfo::~BranchInfo().
handleAllocAndUReset()
void TAGEBase::handleAllocAndUReset (bool alloc, bool taken, BranchInfo * bi, int nrand) virtual
Handles Allocation and U bits reset on an update.
Reimplemented in TAGE_SC_L_TAGE, MPP_TAGE, TAGE_SC_L_TAGE_64KB, and TAGE_SC_L_TAGE_8KB.
Definition at line 439 of file tage_base.cc.
References TAGEBase::TageEntry::ctr, gtable, handleUReset(), TAGEBase::BranchInfo::hitBank, ArmISA::i, maxNumAlloc, nHistoryTables, TAGEBase::BranchInfo::tableIndices, TAGEBase::BranchInfo::tableTags, TAGEBase::TageEntry::tag, tCounter, TAGEBase::TageEntry::u, ULL, and X86ISA::X.
Referenced by condBranchUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
handleTAGEUpdate()
void TAGEBase::handleTAGEUpdate (Addr branch_pc, bool taken, BranchInfo * bi) virtual
Handles the update of the TAGE entries.
Reimplemented in TAGE_SC_L_TAGE, MPP_TAGE, TAGE_SC_L_TAGE_64KB, and TAGE_SC_L_TAGE_8KB.
Definition at line 550 of file tage_base.cc.
References TAGEBase::BranchInfo::altBank, TAGEBase::BranchInfo::altBankIndex, TAGEBase::BranchInfo::altTaken, baseUpdate(), TAGEBase::TageEntry::ctr, ctrUpdate(), DPRINTF, gtable, TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::hitBankIndex, TAGEBase::BranchInfo::tagePred, tagTableCounterBits, tagTableUBits, TAGEBase::TageEntry::u, and unsignedCtrUpdate().
Referenced by condBranchUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
handleUReset()
void TAGEBase::handleUReset () virtual
Handles the U bits reset.
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 488 of file tage_base.cc.
References gtable, ArmISA::i, ArmISA::j, logTagTableSizes, logUResetPeriod, nHistoryTables, resetUctr(), tCounter, ArmISA::u, and ULL.
Referenced by handleAllocAndUReset(), and TAGEBase::BranchInfo::~BranchInfo().
init()
void TAGEBase::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 83 of file tage_base.cc.
References btableHysteresis, btablePrediction, buildTageTables(), calculateParameters(), gtable, histBufferSize, histLengths, initFoldedHistories(), initialized, initialTCounterValue, logRatioBiModalHystEntries, logTagTableSizes, logUResetPeriod, maxHist, nHistoryTables, numUseAltOnNa, pathHistBits, tableIndices, tableTags, tagTableTagWidths, tagTableUBits, tCounter, threadHistory, ULL, and useAltPredForNewlyAllocated.
Referenced by MultiperspectivePerceptronTAGE::init(), and MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::~MPPTAGEBranchInfo().
initFoldedHistories()
void TAGEBase::initFoldedHistories (ThreadHistory & history) protected virtual
Initialization of the folded histories.
Reimplemented in TAGE_SC_L_TAGE_8KB.
Definition at line 146 of file tage_base.cc.
References TAGEBase::ThreadHistory::computeIndices, TAGEBase::ThreadHistory::computeTags, DPRINTF, histLengths, ArmISA::i, TAGEBase::FoldedHistory::init(), logTagTableSizes, nHistoryTables, TAGEBase::FoldedHistory::origLength, and tagTableTagWidths.
Referenced by init().
isHighConfidence()
virtual bool TAGEBase::isHighConfidence (BranchInfo * bi) const inline virtual
Reimplemented in MPP_TAGE.
Definition at line 406 of file tage_base.hh.
References btbUpdate(), getCtr(), getGHR(), getPathHist(), getSizeInBits(), getTageCtrBits(), and isSpeculativeUpdateEnabled().
Referenced by MultiperspectivePerceptronTAGE::lookup().
isSpeculativeUpdateEnabled()
bool TAGEBase::isSpeculativeUpdateEnabled () const
Definition at line 801 of file tage_base.cc.
References speculativeHistUpdate.
Referenced by isHighConfidence(), MultiperspectivePerceptronTAGE::MultiperspectivePerceptronTAGE(), LTAGE::update(), TAGE_SC_L::update(), and MultiperspectivePerceptronTAGE::update().
makeBranchInfo()
TAGEBase::BranchInfo * TAGEBase::makeBranchInfo () virtual
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 78 of file tage_base.cc.
Referenced by TAGEBase::BranchInfo::~BranchInfo().
regStats()
void TAGEBase::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 719 of file tage_base.cc.
References bimodalAltMatchProviderCorrect, bimodalAltMatchProviderWrong, Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::VectorBase< Derived, Stor >::init(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), nHistoryTables, tageAltMatchProvider, tageAltMatchProviderCorrect, tageAltMatchProviderWouldHaveHit, tageAltMatchProviderWrong, tageBimodalProviderCorrect, tageBimodalProviderWrong, tageLongestMatchProvider, tageLongestMatchProviderCorrect, tageLongestMatchProviderWouldHaveHit, and tageLongestMatchProviderWrong.
resetUctr()
void TAGEBase::resetUctr (uint8_t & u) virtual
Algorithm for resetting a single U counter.
Reimplemented in MPP_TAGE, and TAGE_SC_L_TAGE_8KB.
Definition at line 503 of file tage_base.cc.
Referenced by handleUReset(), and TAGEBase::BranchInfo::~BranchInfo().
squash()
void TAGEBase::squash (ThreadID tid, bool taken, TAGEBase::BranchInfo * bi, Addr target) virtual
Restores speculatively updated path and direction histories.
Also recomputes compressed (folded) histories based on the correct branch outcome. This version of squash() is called once on a branch misprediction.
Parameters
tid The Thread ID to select the histories to rollback.
taken The correct branch outcome.
bp_history Wrapping pointer to BranchInfo (to allow storing derived class prediction information in the base class).
target The correct branch target
Postcondition
bp_history points to valid memory.
Reimplemented in TAGE_SC_L_TAGE.
Definition at line 624 of file tage_base.cc.
References TAGEBase::BranchInfo::branchPC, TAGEBase::BranchInfo::ci, TAGEBase::FoldedHistory::comp, TAGEBase::ThreadHistory::computeIndices, TAGEBase::ThreadHistory::computeTags, TAGEBase::BranchInfo::ct0, TAGEBase::BranchInfo::ct1, DPRINTF, TAGEBase::ThreadHistory::gHist, TAGEBase::ThreadHistory::globalHistory, ArmISA::i, nHistoryTables, TAGEBase::BranchInfo::pathHist, TAGEBase::ThreadHistory::pathHist, TAGEBase::BranchInfo::ptGhist, TAGEBase::ThreadHistory::ptGhist, speculativeHistUpdate, threadHistory, and TAGEBase::FoldedHistory::update().
Referenced by LTAGE::update(), TAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), TAGEBase::BranchInfo::~BranchInfo(), and MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::~MPPTAGEBranchInfo().
tagePredict()
bool TAGEBase::tagePredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo * bi)
TAGE prediction called from TAGE::predict.
Parameters
tid The thread ID to select the global histories to use.
branch_pc The unshifted branch PC.
cond_branch True if the branch is conditional.
bi Pointer to the BranchInfo
Definition at line 355 of file tage_base.cc.
References TAGEBase::BranchInfo::altBank, TAGEBase::BranchInfo::altBankIndex, TAGEBase::BranchInfo::altTaken, BIMODAL_ALT_MATCH, BIMODAL_ONLY, TAGEBase::BranchInfo::bimodalIndex, bindex(), TAGEBase::BranchInfo::branchPC, calculateIndicesAndTags(), TAGEBase::BranchInfo::condBranch, TAGEBase::TageEntry::ctr, DPRINTF, extraAltCalc(), getBimodePred(), getUseAltIdx(), gtable, TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::hitBankIndex, ArmISA::i, TAGEBase::BranchInfo::longestMatchPred, nHistoryTables, noSkip, MipsISA::pc, TAGEBase::BranchInfo::provider, TAGEBase::BranchInfo::pseudoNewAlloc, tableIndices, tableTags, TAGE_ALT_MATCH, TAGE_LONGEST_MATCH, TAGEBase::BranchInfo::tagePred, and useAltPredForNewlyAllocated.
Referenced by MultiperspectivePerceptronTAGE::lookup(), TAGE::predict(), LTAGE::predict(), TAGE_SC_L::predict(), and TAGEBase::BranchInfo::~BranchInfo().
unsignedCtrUpdate()
void TAGEBase::unsignedCtrUpdate (uint8_t & ctr, bool up, unsigned nbits) static
Updates an unsigned counter based on up/down parameter.
Parameters
ctr Reference to counter to update.
up Boolean indicating if the counter is incremented/decremented If true it is incremented, if false it is decremented
nbits Counter width.
Definition at line 274 of file tage_base.cc.
Referenced by handleTAGEUpdate(), and TAGEBase::BranchInfo::~BranchInfo().
update()
void TAGEBase::update (ThreadID tid, Addr branch_pc, bool taken, BranchInfo * bi)
Update TAGE.
Called at execute to repair histories on a misprediction and at commit to update the tables.
Parameters
tid The thread ID to select the global histories to use.
branch_pc The unshifted branch PC.
taken Actual branch outcome.
bi Pointer to information on the prediction recorded at prediction time.
Referenced by TAGEBase::BranchInfo::~BranchInfo(), and MultiperspectivePerceptronTAGE::MPPTAGEBranchInfo::~MPPTAGEBranchInfo().
updateGHist()
void TAGEBase::updateGHist (uint8_t *& h, bool dir, uint8_t * tab, int & PT)
(Speculatively) updates the global branch history.
Parameters
h Reference to pointer to global branch history.
dir (Predicted) outcome to update the histories with.
tab
PT Reference to path history.
Definition at line 317 of file tage_base.cc.
References DPRINTF, histBufferSize, ArmISA::i, and maxHist.
Referenced by updateHistories(), MPP_TAGE::updatePathAndGlobalHistory(), and TAGEBase::BranchInfo::~BranchInfo().
updateHistories()
void TAGEBase::updateHistories (ThreadID tid, Addr branch_pc, bool taken, BranchInfo * b, bool speculative, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr, Addr target = MaxAddr) virtual
(Speculatively) updates global histories (path and direction).
Also recomputes compressed (folded) histories based on the branch direction.
Parameters
tid The thread ID to select the histories to update.
branch_pc The unshifted branch PC.
taken (Predicted) branch direction.
b Wrapping pointer to BranchInfo (to allow storing derived class prediction information in the base class).
Reimplemented in TAGE_SC_L_TAGE, and MPP_TAGE.
Definition at line 583 of file tage_base.cc.
References TAGEBase::BranchInfo::ci, TAGEBase::FoldedHistory::comp, TAGEBase::ThreadHistory::computeIndices, TAGEBase::ThreadHistory::computeTags, TAGEBase::BranchInfo::ct0, TAGEBase::BranchInfo::ct1, DPRINTF, TAGEBase::ThreadHistory::gHist, TAGEBase::ThreadHistory::globalHistory, ArmISA::i, instShiftAmt, nHistoryTables, TAGEBase::BranchInfo::pathHist, TAGEBase::ThreadHistory::pathHist, pathHistBits, TAGEBase::BranchInfo::ptGhist, TAGEBase::ThreadHistory::ptGhist, speculativeHistUpdate, threadHistory, ULL, TAGEBase::FoldedHistory::update(), and updateGHist().
Referenced by TAGE::lookup(), TAGE::uncondBranch(), LTAGE::update(), TAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), and TAGEBase::BranchInfo::~BranchInfo().
updateStats()
void TAGEBase::updateStats (bool taken, BranchInfo * bi) virtual
Update the stats.
Parameters
taken Actual branch outcome
bi Pointer to information on the prediction recorded at prediction time.
Definition at line 657 of file tage_base.cc.
References TAGEBase::BranchInfo::altBank, TAGEBase::BranchInfo::altTaken, BIMODAL_ALT_MATCH, BIMODAL_ONLY, bimodalAltMatchProviderCorrect, bimodalAltMatchProviderWrong, TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::longestMatchPred, TAGEBase::BranchInfo::provider, TAGE_ALT_MATCH, TAGE_LONGEST_MATCH, tageAltMatchProvider, tageAltMatchProviderCorrect, tageAltMatchProviderWouldHaveHit, tageAltMatchProviderWrong, tageBimodalProviderCorrect, tageBimodalProviderWrong, tageLongestMatchProvider, tageLongestMatchProviderCorrect, tageLongestMatchProviderWouldHaveHit, tageLongestMatchProviderWrong, and TAGEBase::BranchInfo::tagePred.
Referenced by LTAGE::update(), TAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), and TAGEBase::BranchInfo::~BranchInfo().
Member Data Documentation
bimodalAltMatchProviderCorrect
Stats::Scalar TAGEBase::bimodalAltMatchProviderCorrect protected
Definition at line 492 of file tage_base.hh.
Referenced by regStats(), and updateStats().
bimodalAltMatchProviderWrong
Stats::Scalar TAGEBase::bimodalAltMatchProviderWrong protected
Definition at line 496 of file tage_base.hh.
Referenced by regStats(), and updateStats().
btableHysteresis
std::vector<bool> TAGEBase::btableHysteresis protected
Definition at line 433 of file tage_base.hh.
Referenced by baseUpdate(), init(), and MPP_TAGE::isHighConfidence().
btablePrediction
std::vector<bool> TAGEBase::btablePrediction protected
Definition at line 432 of file tage_base.hh.
Referenced by baseUpdate(), getBimodePred(), init(), and MPP_TAGE::isHighConfidence().
gtable
TageEntry** TAGEBase::gtable protected
Definition at line 434 of file tage_base.hh.
Referenced by buildTageTables(), getCtr(), MPP_TAGE::handleAllocAndUReset(), handleAllocAndUReset(), MPP_TAGE::handleTAGEUpdate(), handleTAGEUpdate(), MPP_TAGE::handleUReset(), handleUReset(), init(), MPP_TAGE::isHighConfidence(), and tagePredict().
histBufferSize
const unsigned TAGEBase::histBufferSize protected
Definition at line 424 of file tage_base.hh.
Referenced by getGHR(), init(), and updateGHist().
histLengths
int* TAGEBase::histLengths protected
Definition at line 466 of file tage_base.hh.
Referenced by MPP_TAGE::calculateParameters(), calculateParameters(), getSizeInBits(), gindex(), init(), and initFoldedHistories().
initialized
bool TAGEBase::initialized protected
Definition at line 487 of file tage_base.hh.
Referenced by init().
initialTCounterValue
const int64_t TAGEBase::initialTCounterValue protected
Definition at line 473 of file tage_base.hh.
Referenced by init().
instShiftAmt
const unsigned TAGEBase::instShiftAmt protected
Definition at line 485 of file tage_base.hh.
Referenced by bindex(), gindex(), gtag(), and updateHistories().
logRatioBiModalHystEntries
const unsigned TAGEBase::logRatioBiModalHystEntries protected
Definition at line 420 of file tage_base.hh.
Referenced by baseUpdate(), getSizeInBits(), init(), and MPP_TAGE::isHighConfidence().
logTagTableSizes
std::vector<int> TAGEBase::logTagTableSizes protected
Definition at line 430 of file tage_base.hh.
Referenced by MPP_TAGE::bindex(), bindex(), buildTageTables(), F(), getSizeInBits(), gindex(), MPP_TAGE::handleUReset(), handleUReset(), init(), and initFoldedHistories().
logUResetPeriod
uint64_t TAGEBase::logUResetPeriod protected
Definition at line 472 of file tage_base.hh.
Referenced by getSizeInBits(), MPP_TAGE::handleUReset(), handleUReset(), and init().
maxHist
const unsigned TAGEBase::maxHist protected
Definition at line 426 of file tage_base.hh.
Referenced by calculateParameters(), init(), and updateGHist().
maxNumAlloc
unsigned TAGEBase::maxNumAlloc protected
Definition at line 476 of file tage_base.hh.
Referenced by handleAllocAndUReset().
minHist
const unsigned TAGEBase::minHist protected
Definition at line 425 of file tage_base.hh.
Referenced by calculateParameters().
nHistoryTables
const unsigned TAGEBase::nHistoryTables protected
Definition at line 421 of file tage_base.hh.
Referenced by TAGEBase::BranchInfo::BranchInfo(), btbUpdate(), buildTageTables(), calculateIndicesAndTags(), MPP_TAGE::calculateParameters(), calculateParameters(), condBranchUpdate(), getSizeInBits(), MPP_TAGE::getUseAltIdx(), MPP_TAGE::handleAllocAndUReset(), handleAllocAndUReset(), MPP_TAGE::handleUReset(), handleUReset(), init(), initFoldedHistories(), regStats(), squash(), TAGEBase(), tagePredict(), updateHistories(), and MPP_TAGE::updatePathAndGlobalHistory().
noSkip
std::vector<bool> TAGEBase::noSkip protected
Definition at line 481 of file tage_base.hh.
Referenced by MPP_TAGE::handleAllocAndUReset(), TAGEBase(), and tagePredict().
numUseAltOnNa
unsigned TAGEBase::numUseAltOnNa protected
Definition at line 474 of file tage_base.hh.
Referenced by getSizeInBits(), MPP_TAGE::getUseAltIdx(), and init().
pathHistBits
const unsigned TAGEBase::pathHistBits protected
Definition at line 427 of file tage_base.hh.
Referenced by getSizeInBits(), gindex(), init(), and updateHistories().
speculativeHistUpdate
const bool TAGEBase::speculativeHistUpdate protected
Definition at line 483 of file tage_base.hh.
Referenced by btbUpdate(), isSpeculativeUpdateEnabled(), squash(), MPP_TAGE::updateHistories(), and updateHistories().
tableIndices
int* TAGEBase::tableIndices protected
Definition at line 467 of file tage_base.hh.
Referenced by calculateIndicesAndTags(), init(), and tagePredict().
tableTags
int* TAGEBase::tableTags protected
Definition at line 468 of file tage_base.hh.
Referenced by calculateIndicesAndTags(), init(), and tagePredict().
tageAltMatchProvider
Stats::Vector TAGEBase::tageAltMatchProvider protected
Definition at line 502 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageAltMatchProviderCorrect
Stats::Scalar TAGEBase::tageAltMatchProviderCorrect protected
Definition at line 491 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageAltMatchProviderWouldHaveHit
Stats::Scalar TAGEBase::tageAltMatchProviderWouldHaveHit protected
Definition at line 498 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageAltMatchProviderWrong
Stats::Scalar TAGEBase::tageAltMatchProviderWrong protected
Definition at line 495 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageBimodalProviderCorrect
Stats::Scalar TAGEBase::tageBimodalProviderCorrect protected
Definition at line 493 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageBimodalProviderWrong
Stats::Scalar TAGEBase::tageBimodalProviderWrong protected
Definition at line 497 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageLongestMatchProvider
Stats::Vector TAGEBase::tageLongestMatchProvider protected
Definition at line 501 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageLongestMatchProviderCorrect
Stats::Scalar TAGEBase::tageLongestMatchProviderCorrect protected
Definition at line 490 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageLongestMatchProviderWouldHaveHit
Stats::Scalar TAGEBase::tageLongestMatchProviderWouldHaveHit protected
Definition at line 499 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tageLongestMatchProviderWrong
Stats::Scalar TAGEBase::tageLongestMatchProviderWrong protected
Definition at line 494 of file tage_base.hh.
Referenced by regStats(), and updateStats().
tagTableCounterBits
const unsigned TAGEBase::tagTableCounterBits protected
Definition at line 422 of file tage_base.hh.
Referenced by getSizeInBits(), getTageCtrBits(), MPP_TAGE::handleTAGEUpdate(), handleTAGEUpdate(), and MPP_TAGE::isHighConfidence().
tagTableTagWidths
std::vector<unsigned> TAGEBase::tagTableTagWidths protected
Definition at line 429 of file tage_base.hh.
Referenced by getSizeInBits(), gtag(), init(), and initFoldedHistories().
tagTableUBits
const unsigned TAGEBase::tagTableUBits protected
Definition at line 423 of file tage_base.hh.
Referenced by getSizeInBits(), MPP_TAGE::handleTAGEUpdate(), handleTAGEUpdate(), and init().
tCounter
int64_t TAGEBase::tCounter protected
Definition at line 471 of file tage_base.hh.
Referenced by MPP_TAGE::handleAllocAndUReset(), handleAllocAndUReset(), MPP_TAGE::handleUReset(), handleUReset(), and init().
threadHistory
std::vector<ThreadHistory> TAGEBase::threadHistory protected
Definition at line 459 of file tage_base.hh.
Referenced by btbUpdate(), getGHR(), getPathHist(), gindex(), gtag(), init(), squash(), MPP_TAGE::updateHistories(), and updateHistories().
useAltOnNaBits
unsigned TAGEBase::useAltOnNaBits protected
Definition at line 475 of file tage_base.hh.
Referenced by condBranchUpdate(), and getSizeInBits().
useAltPredForNewlyAllocated
std::vector<int8_t> TAGEBase::useAltPredForNewlyAllocated protected
Definition at line 470 of file tage_base.hh.
Referenced by condBranchUpdate(), init(), and tagePredict().
The documentation for this class was generated from the following files:
cpu/pred/tage_base.hh
cpu/pred/tage_base.cc