gem5: ArmISA::TLBIOp Class Reference
ArmISA::TLBIOp Class Reference
#include <tlbi_op.hh>
Public Member Functions
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
virtual void operator() (ThreadContext *tc)
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
bool secureLookup
ExceptionLevel targetEL
Detailed Description
Definition at line 55 of file tlbi_op.hh.
Constructor & Destructor Documentation
TLBIOp()
ArmISA::TLBIOp::TLBIOp (ExceptionLevel _targetEL, bool _secure) inline
Definition at line 58 of file tlbi_op.hh.
~TLBIOp()
virtual ArmISA::TLBIOp::~TLBIOp () inline virtual
Definition at line 62 of file tlbi_op.hh.
Member Function Documentation
broadcast()
void ArmISA::TLBIOp::broadcast (ThreadContext * tc) inline
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Parameters
tc Thread Context
Definition at line 71 of file tlbi_op.hh.
References ThreadContext::getSystemPtr(), System::getThreadContext(), System::numContexts(), and X86ISA::x.
Referenced by ArmISA::DTLBIALL::DTLBIALL(), ArmISA::DTLBIASID::DTLBIASID(), ArmISA::DTLBIMVA::DTLBIMVA(), ArmISA::ITLBIALL::ITLBIALL(), ArmISA::ITLBIASID::ITLBIASID(), ArmISA::ITLBIMVA::ITLBIMVA(), and ArmISA::ISA::setMiscReg().
operator()()
virtual void ArmISA::TLBIOp::operator() (ThreadContext * tc) inline virtual
Reimplemented in ArmISA::TLBIIPA, ArmISA::DTLBIMVA, ArmISA::ITLBIMVA, ArmISA::TLBIMVA, ArmISA::TLBIMVAA, ArmISA::TLBIALLN, ArmISA::DTLBIASID, ArmISA::ITLBIASID, ArmISA::TLBIASID, ArmISA::DTLBIALL, ArmISA::ITLBIALL, and ArmISA::TLBIALL.
Definition at line 63 of file tlbi_op.hh.
Referenced by ArmISA::DTLBIALL::DTLBIALL(), ArmISA::DTLBIASID::DTLBIASID(), ArmISA::DTLBIMVA::DTLBIMVA(), ArmISA::ITLBIALL::ITLBIALL(), ArmISA::ITLBIASID::ITLBIASID(), ArmISA::ITLBIMVA::ITLBIMVA(), ArmISA::TLBIALL::TLBIALL(), ArmISA::TLBIALLN::TLBIALLN(), ArmISA::TLBIASID::TLBIASID(), ArmISA::TLBIIPA::TLBIIPA(), ArmISA::TLBIMVA::TLBIMVA(), and ArmISA::TLBIMVAA::TLBIMVAA().
Member Data Documentation
secureLookup
bool ArmISA::TLBIOp::secureLookup protected
Definition at line 81 of file tlbi_op.hh.
Referenced by ArmISA::TLBIALL::operator()(), ArmISA::ITLBIALL::operator()(), ArmISA::DTLBIALL::operator()(), ArmISA::TLBIASID::operator()(), ArmISA::ITLBIASID::operator()(), ArmISA::DTLBIASID::operator()(), ArmISA::TLBIMVAA::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::ITLBIMVA::operator()(), ArmISA::DTLBIMVA::operator()(), and ArmISA::TLBIIPA::operator()().
targetEL
ExceptionLevel ArmISA::TLBIOp::targetEL protected
Definition at line 82 of file tlbi_op.hh.
Referenced by ArmISA::TLBIALL::operator()(), ArmISA::ITLBIALL::operator()(), ArmISA::DTLBIALL::operator()(), ArmISA::TLBIASID::operator()(), ArmISA::ITLBIASID::operator()(), ArmISA::DTLBIASID::operator()(), ArmISA::TLBIALLN::operator()(), ArmISA::TLBIMVAA::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::ITLBIMVA::operator()(), ArmISA::DTLBIMVA::operator()(), and ArmISA::TLBIIPA::operator()().
The documentation for this class was generated from the following file:
arch/arm/tlbi_op.hh