gem5: SectorBlk Class Reference
SectorBlk Class Reference
A Basic Sector block.
#include <sector_blk.hh>
Public Member Functions
SectorBlk ()
SectorBlk (const SectorBlk &)=delete
SectorBlk & operator= (const SectorBlk &)=delete
~SectorBlk ()
bool isValid () const
Checks that a sector block is valid.
bool isSecure () const
Checks that a sector block is secure.
void setTag (const Addr tag)
Set tag associated to this block.
Addr getTag () const
Get tag associated to this block.
void validateSubBlk ()
Increase the number of valid sub-blocks.
void invalidateSubBlk ()
Decrease the number of valid sub-blocks.
void setSecure ()
Set secure bit.
void setPosition (const uint32_t set, const uint32_t way) override
Sets the position of the sub-entries, besides its own.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
std::vector< SectorSubBlk * > blks
List of blocks associated to this sector.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Protected Attributes
Addr _tag
Sector tag value.
uint8_t _validCounter
Counter of the number of valid sub-blocks.
bool _secureBit
Whether sector blk is in secure-space or not.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
A Basic Sector block.
Contains the tag and a list of blocks associated to this sector.
Definition at line 145 of file sector_blk.hh.
Constructor & Destructor Documentation
SectorBlk() [1/2]
SectorBlk::SectorBlk ()
Definition at line 118 of file sector_blk.cc.
SectorBlk() [2/2]
SectorBlk::SectorBlk (const SectorBlk &) delete
~SectorBlk()
SectorBlk::~SectorBlk () inline
Definition at line 168 of file sector_blk.hh.
References SectorSubBlk::getTag(), CacheBlk::isSecure(), CacheBlk::isValid(), ReplaceableEntry::setPosition(), SectorSubBlk::setSecure(), and CacheBlk::tag.
Member Function Documentation
getTag()
Addr SectorBlk::getTag () const
Get tag associated to this block.
Returns
The tag value.
Definition at line 144 of file sector_blk.cc.
References _tag.
Referenced by CompressedTags::findVictim(), SectorTags::findVictim(), SectorSubBlk::getTag(), and SectorSubBlk::insert().
invalidateSubBlk()
void SectorBlk::invalidateSubBlk ()
Decrease the number of valid sub-blocks.
Definition at line 156 of file sector_blk.cc.
References _secureBit, and _validCounter.
Referenced by SectorSubBlk::invalidate().
isSecure()
bool SectorBlk::isSecure () const
Checks that a sector block is secure.
A single secure block suffices to imply that the whole sector is secure, as the insertion proccess asserts that different secure spaces can't coexist in the same sector.
Returns
True if any of the blocks in the sector is secure.
Definition at line 131 of file sector_blk.cc.
References _secureBit.
Referenced by CompressedTags::findVictim(), SectorTags::findVictim(), and SectorSubBlk::insert().
isValid()
bool SectorBlk::isValid () const
Checks that a sector block is valid.
Returns
True if any of the blocks in the sector is valid.
Definition at line 124 of file sector_blk.cc.
References _validCounter.
Referenced by CompressedTags::findVictim(), SectorTags::findVictim(), SectorSubBlk::insert(), SectorTags::insertBlock(), and SectorTags::invalidate().
operator=()
SectorBlk& SectorBlk::operator= (const SectorBlk &) delete
setPosition()
void SectorBlk::setPosition (const uint32_t set, const uint32_t way) override virtual
Sets the position of the sub-entries, besides its own.
Parameters
set The set of this entry and sub-entries.
way The way of this entry and sub-entries.
Reimplemented from ReplaceableEntry.
Definition at line 172 of file sector_blk.cc.
References blks, and ReplaceableEntry::setPosition().
setSecure()
void SectorBlk::setSecure ()
Set secure bit.
Definition at line 166 of file sector_blk.cc.
References _secureBit.
Referenced by SectorSubBlk::setSecure().
setTag()
void SectorBlk::setTag (const Addr tag)
Set tag associated to this block.
Parameters
The tag value.
Definition at line 138 of file sector_blk.cc.
References _tag.
Referenced by SectorSubBlk::insert().
validateSubBlk()
void SectorBlk::validateSubBlk ()
Increase the number of valid sub-blocks.
Definition at line 150 of file sector_blk.cc.
References _validCounter.
Referenced by SectorSubBlk::setValid().
Member Data Documentation
_secureBit
bool SectorBlk::_secureBit protected
Whether sector blk is in secure-space or not.
Definition at line 162 of file sector_blk.hh.
Referenced by invalidateSubBlk(), isSecure(), and setSecure().
_tag
Addr SectorBlk::_tag protected
Sector tag value.
A sector's tag is the tag of all its sub-blocks.
Definition at line 151 of file sector_blk.hh.
Referenced by getTag(), and setTag().
_validCounter
uint8_t SectorBlk::_validCounter protected
Counter of the number of valid sub-blocks.
The sector is valid if any of its sub-blocks is valid.
Definition at line 157 of file sector_blk.hh.
Referenced by invalidateSubBlk(), isValid(), and validateSubBlk().
blks
std::vector<SectorSubBlk*> SectorBlk::blks
List of blocks associated to this sector.
Definition at line 168 of file sector_blk.hh.
Referenced by CompressedTags::findVictim(), SectorTags::findVictim(), setPosition(), CompressedTags::tagsInit(), SectorTags::tagsInit(), and BaseCache::updateCompressionData().
The documentation for this class was generated from the following files:
mem/cache/tags/sector_blk.hh
mem/cache/tags/sector_blk.cc