gem5: RespPacketQueue Class Reference
RespPacketQueue Class Reference
#include <packet_queue.hh>
Public Member Functions
RespPacketQueue (EventManager &_em, SlavePort &_slavePort, bool force_order=false, const std::string _label="RespPacketQueue")
Create a response packet queue, linked to an event manager, a slave port, and a label that will be used for functional print request packets.
virtual ~RespPacketQueue ()
const std::string name () const
Provide a name to simplify debugging.
bool sendTiming (PacketPtr pkt)
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
Public Member Functions inherited from PacketQueue
size_t size () const
Get the size of the queue.
Tick deferredPacketReadyTime () const
Get the next packet ready time.
bool checkConflict (const PacketPtr pkt, const int blk_size) const
Check if a packet corresponding to the same address exists in the queue.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
void schedSendEvent (Tick when)
Schedule a send event if we are not already waiting for a retry.
void schedSendTiming (PacketPtr pkt, Tick when)
Add a packet to the transmit list, and schedule a send event.
void retry ()
Retry sending a packet from the queue.
void disableSanityCheck ()
This allows a user to explicitly disable the sanity check on the size of the transmitList, which is enabled by default.
DrainState drain () override
Notify an object that it needs to drain its state.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Static Protected Member Functions
static const std::string name (const SlavePort &slavePort, const std::string &label)
Protected Attributes
SlavePort & slavePort
Protected Attributes inherited from PacketQueue
const std::string label
Label to use for print request packets label stack.
bool waitingOnRetry
Remember whether we're awaiting a retry.
Additional Inherited Members
Protected Member Functions inherited from PacketQueue
bool deferredPacketReady () const
Check whether we have a packet ready to go on the transmit list.
virtual void sendDeferredPacket ()
Attempt to send a packet.
PacketQueue (EventManager &_em, const std::string &_label, const std::string &_sendEventName, bool force_order=false, bool disable_sanity_check=false)
Create a packet queue, linked to an event manager, and a label that will be used for functional print request packets.
virtual ~PacketQueue ()
Virtual desctructor since the class may be used as a base class.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 299 of file packet_queue.hh.
Constructor & Destructor Documentation
RespPacketQueue()
RespPacketQueue::RespPacketQueue (EventManager & _em, SlavePort & _slavePort, bool force_order = false, const std::string _label = "RespPacketQueue")
Create a response packet queue, linked to an event manager, a slave port, and a label that will be used for functional print request packets.
Parameters
_em Event manager used for scheduling this queue
_slavePort Slave port used to send the packets
force_order Force insertion order for packets with same address
_label Label to push on the label stack for print request packets
Definition at line 266 of file packet_queue.cc.
~RespPacketQueue()
virtual RespPacketQueue::~RespPacketQueue () inline virtual
Definition at line 328 of file packet_queue.hh.
Member Function Documentation
name() [1/2]
static const std::string RespPacketQueue::name (const SlavePort & slavePort, const std::string & label) inline static protected
Definition at line 308 of file packet_queue.hh.
References PacketQueue::label, and Port::name().
name() [2/2]
const std::string RespPacketQueue::name () const inline virtual
Provide a name to simplify debugging.
Returns
A complete name, appended to module and port
Implements PacketQueue.
Definition at line 330 of file packet_queue.hh.
References PacketQueue::label, PacketQueue::name(), PacketQueue::DeferredPacket::pkt, and PacketQueue::sendTiming().
sendTiming()
bool RespPacketQueue::sendTiming (PacketPtr pkt) virtual
Send a packet using the appropriate method for the specific subclass (reuest, response or snoop response).
Implements PacketQueue.
Definition at line 275 of file packet_queue.cc.
References SlavePort::sendTimingResp(), and slavePort.
Member Data Documentation
slavePort
SlavePort& RespPacketQueue::slavePort protected
Definition at line 304 of file packet_queue.hh.
Referenced by sendTiming().
The documentation for this class was generated from the following files:
mem/packet_queue.hh
mem/packet_queue.cc