gem5: DmaReadFifo Class Reference
DmaReadFifo Class Reference
Buffered DMA engine helper class.
#include <dma_device.hh>
Classes
class DmaDoneEvent
Public Member Functions
DmaReadFifo (DmaPort &port, size_t size, unsigned max_req_size, unsigned max_pending, Request::Flags flags=0)
~DmaReadFifo ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
DrainState drain () override
Notify an object that it needs to drain its state.
FIFO access
bool tryGet (uint8_t *dst, size_t len)
Try to read data from the FIFO.
template<typename T >
bool tryGet (T &value)
void get (uint8_t *dst, size_t len)
Read data from the FIFO and panic on failure.
template<typename T >
T get ()
size_t size () const
Get the amount of data stored in the FIFO.
void flush ()
Flush the FIFO.
FIFO fill control
void startFill (Addr start, size_t size)
Start filling the FIFO.
void stopFill ()
Stop the DMA engine.
bool atEndOfBlock () const
Has the DMA engine sent out the last request for the active block?
bool isActive () const
Is the DMA engine active (i.e., are there still in-flight accesses)?
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Member Functions
Callbacks
virtual void onEndOfBlock ()
End of block callback.
virtual void onIdle ()
Last response received callback.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Types
typedef std::unique_ptr< DmaDoneEvent > DmaDoneEventUPtr
Private Member Functions
void dmaDone ()
DMA request done, handle incoming data and issue new request.
void handlePending ()
Handle pending requests that have been flagged as done.
void resumeFill ()
Try to issue new DMA requests or bypass DMA requests.
void resumeFillTiming ()
Try to issue new DMA requests during normal execution.
void resumeFillFunctional ()
Try to bypass DMA requests in KVM execution mode.
Private Attributes
const Addr maxReqSize
Maximum request size in bytes.
const size_t fifoSize
Maximum FIFO size in bytes.
const Request::Flags reqFlags
Request flags.
DmaPort & port
Fifo< uint8_t > buffer
Addr nextAddr
Addr endAddr
std::deque< DmaDoneEventUPtr > pendingRequests
std::deque< DmaDoneEventUPtr > freeRequests
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Buffered DMA engine helper class.
This class implements a simple DMA engine that feeds a FIFO buffer. The size of the buffer, the maximum number of pending requests and the maximum request size are all set when the engine is instantiated.
An asynchronous transfer of a block of data (designated by a start address and a size) is started by calling the startFill() method. The DMA engine will aggressively try to keep the internal FIFO full. As soon as there is room in the FIFO for more data and there are free request slots, a new fill will be started.
Data in the FIFO can be read back using the get() and tryGet() methods. Both request a block of data from the FIFO. However, get() panics if the block cannot be satisfied, while tryGet() simply returns false. The latter call makes it possible to implement custom buffer underrun handling.
A simple use case would be something like this:
// Create a DMA engine with a 1KiB buffer. Issue up to 8 concurrent
// uncacheable 64 byte (maximum) requests.
DmaReadFifo *dma = new DmaReadFifo(port, 1024, 64, 8,
                                   Request::UNCACHEABLE);
// Start copying 4KiB data from 0xFF000000
dma->startFill(0xFF000000, 0x1000);
// Some time later when there is data in the FIFO.
uint8_t data[8];
dma->get(data, sizeof(data))
The DMA engine allows new blocks to be requested as soon as the last request for a block has been sent (i.e., there is no need to wait for pending requests to complete). This can be queried with the atEndOfBlock() method and more advanced implementations may override the onEndOfBlock() callback.
Definition at line 329 of file dma_device.hh.
Member Typedef Documentation
DmaDoneEventUPtr
typedef std::unique_ptr<DmaDoneEvent> DmaReadFifo::DmaDoneEventUPtr private
Definition at line 500 of file dma_device.hh.
Constructor & Destructor Documentation
DmaReadFifo()
DmaReadFifo::DmaReadFifo (DmaPort & port, size_t size, unsigned max_req_size, unsigned max_pending, Request::Flags flags = 0)
Definition at line 290 of file dma_device.cc.
References ArmISA::e, and freeRequests.
~DmaReadFifo()
DmaReadFifo::~DmaReadFifo ()
Definition at line 305 of file dma_device.cc.
References ArmISA::e, MipsISA::p, and pendingRequests.
Member Function Documentation
atEndOfBlock()
bool DmaReadFifo::atEndOfBlock () const inline
Has the DMA engine sent out the last request for the active block?
Definition at line 424 of file dma_device.hh.
Referenced by resumeFill(), resumeFillTiming(), and startFill().
dmaDone()
void DmaReadFifo::dmaDone () private
DMA request done, handle incoming data and issue new request.
Definition at line 448 of file dma_device.cc.
References handlePending(), isActive(), onIdle(), and resumeFill().
Referenced by DmaReadFifo::DmaDoneEvent::process().
drain()
DrainState DmaReadFifo::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 479 of file dma_device.cc.
References Drained, Draining, and pendingRequests.
flush()
void DmaReadFifo::flush () inline
Flush the FIFO.
Definition at line 390 of file dma_device.hh.
Referenced by HDLcd::DmaEngine::abortFrame().
get() [1/2]
void DmaReadFifo::get (uint8_t * dst, size_t len)
Read data from the FIFO and panic on failure.
See also
tryGet()
Parameters
dst Pointer to a destination buffer
len Amount of data to read.
Definition at line 352 of file dma_device.cc.
References panic_if, and tryGet().
get() [2/2]
template<typename T > T DmaReadFifo::get () inline
Definition at line 381 of file dma_device.hh.
handlePending()
void DmaReadFifo::handlePending () private
Handle pending requests that have been flagged as done.
Definition at line 460 of file dma_device.cc.
References buffer, MipsISA::event, freeRequests, pendingRequests, Drainable::signalDrainDone(), and Fifo< T >::write().
Referenced by dmaDone().
isActive()
bool DmaReadFifo::isActive () const inline
Is the DMA engine active (i.e., are there still in-flight accesses)?
Definition at line 432 of file dma_device.hh.
Referenced by dmaDone().
onEndOfBlock()
virtual void DmaReadFifo::onEndOfBlock () inline protected virtual
End of block callback.
This callback is called once after the last access in a block has been sent. It is legal for a derived class to call startFill() from this method to initiate a transfer.
Reimplemented in HDLcd::DmaEngine.
Definition at line 449 of file dma_device.hh.
Referenced by resumeFill().
onIdle()
virtual void DmaReadFifo::onIdle () inline protected virtual
Last response received callback.
This callback is called when the DMA engine becomes idle (i.e., there are no pending requests).
It is possible for a DMA engine to reach the end of block and become idle at the same tick. In such a case, the onEndOfBlock() callback will be called first. This callback will NOT be called if that callback initiates a new DMA transfer.
Reimplemented in HDLcd::DmaEngine.
Definition at line 462 of file dma_device.hh.
Referenced by dmaDone().
resumeFill()
void DmaReadFifo::resumeFill () private
Try to issue new DMA requests or bypass DMA requests.
Definition at line 382 of file dma_device.cc.
References atEndOfBlock(), System::bypassCaches(), Draining, Drainable::drainState(), onEndOfBlock(), port, resumeFillFunctional(), resumeFillTiming(), and DmaPort::sys.
Referenced by dmaDone(), startFill(), and tryGet().
resumeFillFunctional()
void DmaReadFifo::resumeFillFunctional () private
Try to bypass DMA requests in KVM execution mode.
Definition at line 401 of file dma_device.cc.
References buffer, System::cacheLineSize(), Fifo< T >::capacity(), ContextSwitchTaskId::DMA, DPRINTF, endAddr, nextAddr, pendingRequests, System::physProxy, port, PortProxy::readBlob(), Fifo< T >::size(), DmaPort::sys, and Fifo< T >::write().
Referenced by resumeFill().
resumeFillTiming()
void DmaReadFifo::resumeFillTiming () private
Try to issue new DMA requests during normal execution.
Definition at line 422 of file dma_device.cc.
References atEndOfBlock(), buffer, DmaPort::dmaAction(), ArmISA::e, endAddr, MipsISA::event, fifoSize, freeRequests, maxReqSize, nextAddr, pendingRequests, port, MemCmd::ReadReq, reqFlags, and Fifo< T >::size().
Referenced by resumeFill().
serialize()
void DmaReadFifo::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 322 of file dma_device.cc.
References buffer, endAddr, nextAddr, pendingRequests, SERIALIZE_CONTAINER, and SERIALIZE_SCALAR.
Referenced by HDLcd::DmaEngine::serialize().
size()
size_t DmaReadFifo::size () const inline
Get the amount of data stored in the FIFO.
Definition at line 388 of file dma_device.hh.
Referenced by DmaReadFifo::DmaDoneEvent::reset(), and startFill().
startFill()
void DmaReadFifo::startFill (Addr start, size_t size)
Start filling the FIFO.
It's considered an error to call start on an active DMA engine unless the last request from the active block has been sent (i.e., atEndOfBlock() is true).
Parameters
start Physical address to copy from.
size Size of the block to copy.
Definition at line 359 of file dma_device.cc.
References atEndOfBlock(), endAddr, nextAddr, resumeFill(), and size().
Referenced by HDLcd::DmaEngine::onEndOfBlock(), and HDLcd::DmaEngine::startFrame().
stopFill()
void DmaReadFifo::stopFill ()
Stop the DMA engine.
Stop filling the FIFO and ignore incoming responses for pending requests. The onEndOfBlock() callback will not be called after this method has been invoked. However, once the last response has been received, the onIdle() callback will still be called.
Definition at line 369 of file dma_device.cc.
References endAddr, nextAddr, MipsISA::p, and pendingRequests.
Referenced by HDLcd::DmaEngine::abortFrame().
tryGet() [1/2]
bool DmaReadFifo::tryGet (uint8_t * dst, size_t len)
Try to read data from the FIFO.
This method reads len bytes of data from the FIFO and stores them in the memory location pointed to by dst. The method fails, and no data is written to the buffer, if the FIFO doesn't contain enough data to satisfy the request.
Parameters
dst Pointer to a destination buffer
len Amount of data to read.
Returns
true on success, false otherwise.
Definition at line 340 of file dma_device.cc.
References buffer, ArmISA::len, Fifo< T >::read(), resumeFill(), and Fifo< T >::size().
Referenced by get().
tryGet() [2/2]
template<typename T > bool DmaReadFifo::tryGet (T & value) inline
Definition at line 366 of file dma_device.hh.
References ArmISA::len.
unserialize()
void DmaReadFifo::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 332 of file dma_device.cc.
References buffer, endAddr, nextAddr, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
Referenced by HDLcd::DmaEngine::unserialize().
Member Data Documentation
buffer
Fifo<uint8_t> DmaReadFifo::buffer private
Definition at line 521 of file dma_device.hh.
Referenced by handlePending(), resumeFillFunctional(), resumeFillTiming(), serialize(), tryGet(), and unserialize().
endAddr
Addr DmaReadFifo::endAddr private
Definition at line 524 of file dma_device.hh.
Referenced by resumeFillFunctional(), resumeFillTiming(), serialize(), startFill(), stopFill(), and unserialize().
fifoSize
const size_t DmaReadFifo::fifoSize private
Maximum FIFO size in bytes.
Definition at line 469 of file dma_device.hh.
Referenced by resumeFillTiming().
freeRequests
std::deque<DmaDoneEventUPtr> DmaReadFifo::freeRequests private
Definition at line 527 of file dma_device.hh.
Referenced by DmaReadFifo(), handlePending(), and resumeFillTiming().
maxReqSize
const Addr DmaReadFifo::maxReqSize private
Maximum request size in bytes.
Definition at line 462 of file dma_device.hh.
Referenced by resumeFillTiming().
nextAddr
Addr DmaReadFifo::nextAddr private
Definition at line 523 of file dma_device.hh.
Referenced by resumeFillFunctional(), resumeFillTiming(), serialize(), startFill(), stopFill(), and unserialize().
pendingRequests
std::deque<DmaDoneEventUPtr> DmaReadFifo::pendingRequests private
Definition at line 526 of file dma_device.hh.
Referenced by drain(), handlePending(), resumeFillFunctional(), resumeFillTiming(), serialize(), stopFill(), and ~DmaReadFifo().
port
DmaPort& DmaReadFifo::port private
Definition at line 473 of file dma_device.hh.
Referenced by resumeFill(), resumeFillFunctional(), and resumeFillTiming().
reqFlags
const Request::Flags DmaReadFifo::reqFlags private
Request flags.
Definition at line 471 of file dma_device.hh.
Referenced by resumeFillTiming().
The documentation for this class was generated from the following files:
dev/dma_device.hh
dev/dma_device.cc