gem5: ComputeUnit::LDSPort::SenderState Class Reference
ComputeUnit::LDSPort::SenderState Class Reference
SenderState is information carried along with the packet, esp.
#include <compute_unit.hh>
Public Member Functions
SenderState (GPUDynInstPtr gpuDynInst)
GPUDynInstPtr getMemInst () const
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Protected Attributes
GPUDynInstPtr _gpuDynInst = nullptr
Additional Inherited Members
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Detailed Description
SenderState is information carried along with the packet, esp.
the GPUDynInstPtr
Definition at line 624 of file compute_unit.hh.
Constructor & Destructor Documentation
SenderState()
ComputeUnit::LDSPort::SenderState::SenderState (GPUDynInstPtr gpuDynInst) inline
Definition at line 631 of file compute_unit.hh.
Member Function Documentation
getMemInst()
GPUDynInstPtr ComputeUnit::LDSPort::SenderState::getMemInst () const inline
Definition at line 637 of file compute_unit.hh.
Referenced by LdsState::countBankConflicts(), LdsState::getDynInstr(), LdsState::process(), ComputeUnit::LDSPort::recvTimingResp(), and ComputeUnit::LDSPort::sendTimingReq().
Member Data Documentation
_gpuDynInst
GPUDynInstPtr ComputeUnit::LDSPort::SenderState::_gpuDynInst = nullptr protected
Definition at line 628 of file compute_unit.hh.
The documentation for this class was generated from the following file:
gpu-compute/compute_unit.hh