gem5: MessageBuffer Class Reference
MessageBuffer Class Reference
#include <MessageBuffer.hh>
Public Types
typedef MessageBufferParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
MessageBuffer (const Params *p)
void reanalyzeMessages (Addr addr, Tick current_time)
void reanalyzeAllMessages (Tick current_time)
void stallMessage (Addr addr, Tick current_time)
bool isReady (Tick current_time) const
void delayHead (Tick current_time, Tick delta)
bool areNSlotsAvailable (unsigned int n, Tick curTime)
int getPriority ()
void setPriority (int rank)
void setConsumer (Consumer *consumer)
Consumer * getConsumer ()
bool getOrdered ()
const Message * peek () const
Function for extracting the message at the head of the message queue.
const MsgPtr & peekMsgPtr () const
void enqueue (MsgPtr message, Tick curTime, Tick delta)
Tick dequeue (Tick current_time, bool decrement_messages=true)
Updates the delay cycles of the message at the head of the queue, removes it from the queue and returns its total delay.
void registerDequeueCallback (std::function< void()> callback)
void unregisterDequeueCallback ()
void recycle (Tick current_time, Tick recycle_latency)
bool isEmpty () const
bool isStallMapEmpty ()
unsigned int getStallMapSize ()
unsigned int getSize (Tick curTime)
void clear ()
void print (std::ostream &out) const
void clearStats ()
void setIncomingLink (int link_id)
void setVnet (int net)
Port & getPort (const std::string &, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void regStats () override
Callback to set stat parameters.
uint32_t functionalWrite (Packet *pkt)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Types
typedef std::map< Addr, std::list< MsgPtr > > StallMsgMapType
Private Member Functions
void reanalyzeList (std::list< MsgPtr > &, Tick)
Private Attributes
Consumer * m_consumer
Consumer to signal a wakeup(), can be NULL.
std::vector< MsgPtr > m_prio_heap
std::function< void()> m_dequeue_callback
StallMsgMapType m_stall_msg_map
A map from line addresses to lists of stalled messages for that line.
int m_stall_map_size
Current size of the stall map.
const unsigned int m_max_size
The maximum capacity.
Tick m_time_last_time_size_checked
unsigned int m_size_last_time_size_checked
Tick m_time_last_time_enqueue
Tick m_time_last_time_pop
Tick m_last_arrival_time
unsigned int m_size_at_cycle_start
unsigned int m_stalled_at_cycle_start
unsigned int m_msgs_this_cycle
Stats::Scalar m_not_avail_count
uint64_t m_msg_counter
int m_priority_rank
const bool m_strict_fifo
const bool m_randomization
int m_input_link_id
int m_vnet_id
Stats::Average m_buf_msgs
Stats::Average m_stall_time
Stats::Scalar m_stall_count
Stats::Formula m_occupancy
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 55 of file MessageBuffer.hh.
Member Typedef Documentation
Params
typedef MessageBufferParams MessageBuffer::Params
Definition at line 58 of file MessageBuffer.hh.
StallMsgMapType
typedef std::map<Addr, std::list<MsgPtr> > MessageBuffer::StallMsgMapType private
Definition at line 152 of file MessageBuffer.hh.
Constructor & Destructor Documentation
MessageBuffer()
MessageBuffer::MessageBuffer (const Params * p)
Definition at line 43 of file MessageBuffer.cc.
References m_buf_msgs, m_consumer, m_dequeue_callback, m_input_link_id, m_msg_counter, m_msgs_this_cycle, m_priority_rank, m_size_at_cycle_start, m_size_last_time_size_checked, m_stall_msg_map, m_stall_time, m_stalled_at_cycle_start, and m_vnet_id.
Referenced by functionalWrite().
Member Function Documentation
areNSlotsAvailable()
bool MessageBuffer::areNSlotsAvailable (unsigned int n, Tick curTime)
Definition at line 80 of file MessageBuffer.cc.
References DPRINTF, m_max_size, m_msgs_this_cycle, m_not_avail_count, m_prio_heap, m_size_at_cycle_start, m_stall_map_size, m_stalled_at_cycle_start, m_time_last_time_enqueue, and m_time_last_time_pop.
Referenced by delayHead(), GPUCoalescer::getRequestStatus(), GPUCoalescer::insertRequest(), and Throttle::operateVnet().
clear()
void MessageBuffer::clear ()
Definition at line 277 of file MessageBuffer.cc.
References m_msg_counter, m_msgs_this_cycle, m_prio_heap, m_size_at_cycle_start, m_stalled_at_cycle_start, m_time_last_time_enqueue, and m_time_last_time_pop.
Referenced by getStallMapSize().
clearStats()
void MessageBuffer::clearStats () inline
Definition at line 120 of file MessageBuffer.hh.
References m_msg_counter, and m_not_avail_count.
delayHead()
void MessageBuffer::delayHead (Tick current_time, Tick delta) inline
Definition at line 69 of file MessageBuffer.hh.
References areNSlotsAvailable(), enqueue(), ArmISA::m, m_prio_heap, and ArmISA::n.
dequeue()
Tick MessageBuffer::dequeue (Tick current_time, bool decrement_messages = true)
Updates the delay cycles of the message at the head of the queue, removes it from the queue and returns its total delay.
Definition at line 226 of file MessageBuffer.cc.
References curTick(), DPRINTF, isReady(), m_buf_msgs, m_dequeue_callback, m_prio_heap, m_size_at_cycle_start, m_stall_map_size, m_stall_time, m_stalled_at_cycle_start, and m_time_last_time_pop.
Referenced by PerfectSwitch::operateMessageBuffer(), Throttle::operateVnet(), peekMsgPtr(), stallMessage(), and NetworkInterface::wakeup().
enqueue()
void MessageBuffer::enqueue (MsgPtr message, Tick curTime, Tick delta)
Definition at line 150 of file MessageBuffer.cc.
References DPRINTF, Message::getLastEnqueueTime(), RubySystem::getRandomization(), RubySystem::getWarmupEnabled(), m_buf_msgs, m_consumer, m_last_arrival_time, m_msg_counter, m_msgs_this_cycle, m_prio_heap, m_randomization, m_strict_fifo, m_time_last_time_enqueue, m_vnet_id, SimObject::name(), panic, random_time(), Consumer::scheduleEventAbsolute(), Message::setLastEnqueueTime(), Message::setMsgCounter(), Consumer::storeEventInfo(), and Message::updateDelayedTicks().
Referenced by delayHead(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), DMASequencer::issueNext(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), Throttle::operateVnet(), peekMsgPtr(), AbstractController::recvTimingResp(), and VIPERCoalescer::wbL1().
functionalWrite()
uint32_t MessageBuffer::functionalWrite (Packet * pkt)
Definition at line 441 of file MessageBuffer.cc.
References Message::functionalWrite(), ArmISA::i, m_prio_heap, m_stall_msg_map, and MessageBuffer().
Referenced by getPort().
getConsumer()
Consumer* MessageBuffer::getConsumer () inline
Definition at line 92 of file MessageBuffer.hh.
References m_consumer.
getOrdered()
bool MessageBuffer::getOrdered () inline
Definition at line 94 of file MessageBuffer.hh.
References m_strict_fifo, and peek().
getPort()
Port& MessageBuffer::getPort (const std::string & if_name, PortID idx = InvalidPortID) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 126 of file MessageBuffer.hh.
References functionalWrite(), RubyDummyPort::instance(), reanalyzeList(), and regStats().
getPriority()
int MessageBuffer::getPriority () inline
Definition at line 79 of file MessageBuffer.hh.
References m_priority_rank.
getSize()
unsigned int MessageBuffer::getSize (Tick curTime)
Definition at line 69 of file MessageBuffer.cc.
References m_prio_heap, m_size_last_time_size_checked, and m_time_last_time_size_checked.
Referenced by getStallMapSize().
getStallMapSize()
unsigned int MessageBuffer::getStallMapSize () inline
Definition at line 114 of file MessageBuffer.hh.
References clear(), getSize(), m_stall_msg_map, and print().
isEmpty()
bool MessageBuffer::isEmpty () const inline
Definition at line 112 of file MessageBuffer.hh.
References m_prio_heap.
isReady()
bool MessageBuffer::isReady (Tick current_time) const
Definition at line 399 of file MessageBuffer.cc.
References m_prio_heap.
Referenced by dequeue(), PerfectSwitch::operateMessageBuffer(), Throttle::operateVnet(), recycle(), stallMessage(), and NetworkInterface::wakeup().
isStallMapEmpty()
bool MessageBuffer::isStallMapEmpty () inline
Definition at line 113 of file MessageBuffer.hh.
References m_stall_msg_map.
peek()
const Message * MessageBuffer::peek () const
Function for extracting the message at the head of the message queue.
The function assumes that the queue is nonempty.
Definition at line 127 of file MessageBuffer.cc.
References DPRINTF, and m_prio_heap.
Referenced by getOrdered().
peekMsgPtr()
const MsgPtr& MessageBuffer::peekMsgPtr () const inline
Definition at line 100 of file MessageBuffer.hh.
References dequeue(), enqueue(), m_prio_heap, recycle(), registerDequeueCallback(), and unregisterDequeueCallback().
Referenced by PerfectSwitch::operateMessageBuffer(), Throttle::operateVnet(), and NetworkInterface::wakeup().
print()
void MessageBuffer::print (std::ostream & out) const
Definition at line 386 of file MessageBuffer.cc.
References ccprintf(), m_consumer, m_prio_heap, and SimObject::name().
Referenced by getStallMapSize(), and operator<<().
reanalyzeAllMessages()
void MessageBuffer::reanalyzeAllMessages (Tick current_time)
Definition at line 344 of file MessageBuffer.cc.
References DPRINTF, m_stall_map_size, m_stall_msg_map, and reanalyzeList().
reanalyzeList()
void MessageBuffer::reanalyzeList (std::list< MsgPtr > & lt, Tick schdTick) private
Definition at line 306 of file MessageBuffer.cc.
References DPRINTF, ArmISA::m, m_consumer, m_prio_heap, and Consumer::scheduleEventAbsolute().
Referenced by getPort(), reanalyzeAllMessages(), and reanalyzeMessages().
reanalyzeMessages()
void MessageBuffer::reanalyzeMessages (Addr addr, Tick current_time)
Definition at line 326 of file MessageBuffer.cc.
References addr, DPRINTF, m_stall_map_size, m_stall_msg_map, and reanalyzeList().
recycle()
void MessageBuffer::recycle (Tick current_time, Tick recycle_latency)
Definition at line 290 of file MessageBuffer.cc.
References DPRINTF, isReady(), m_consumer, m_prio_heap, and Consumer::scheduleEventAbsolute().
Referenced by peekMsgPtr().
registerDequeueCallback()
void MessageBuffer::registerDequeueCallback (std::function< void()> callback)
Definition at line 265 of file MessageBuffer.cc.
References m_dequeue_callback.
Referenced by peekMsgPtr().
regStats()
void MessageBuffer::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 406 of file MessageBuffer.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), m_buf_msgs, m_max_size, m_not_avail_count, m_occupancy, m_stall_count, m_stall_time, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::nozero.
Referenced by getPort().
setConsumer()
void MessageBuffer::setConsumer (Consumer * consumer) inline
Definition at line 81 of file MessageBuffer.hh.
References DPRINTF, fatal, and m_consumer.
Referenced by Throttle::addLinks().
setIncomingLink()
void MessageBuffer::setIncomingLink (int link_id) inline
Definition at line 122 of file MessageBuffer.hh.
References m_input_link_id.
setPriority()
void MessageBuffer::setPriority (int rank) inline
Definition at line 80 of file MessageBuffer.hh.
References m_priority_rank.
setVnet()
void MessageBuffer::setVnet (int net) inline
Definition at line 123 of file MessageBuffer.hh.
References m_vnet_id.
stallMessage()
void MessageBuffer::stallMessage (Addr addr, Tick current_time)
Definition at line 364 of file MessageBuffer.cc.
References addr, dequeue(), DPRINTF, getOffset(), isReady(), m_prio_heap, m_stall_count, m_stall_map_size, and m_stall_msg_map.
unregisterDequeueCallback()
void MessageBuffer::unregisterDequeueCallback ()
Definition at line 271 of file MessageBuffer.cc.
References m_dequeue_callback.
Referenced by peekMsgPtr().
Member Data Documentation
m_buf_msgs
Stats::Average MessageBuffer::m_buf_msgs private
Definition at line 208 of file MessageBuffer.hh.
Referenced by dequeue(), enqueue(), MessageBuffer(), and regStats().
m_consumer
Consumer* MessageBuffer::m_consumer private
Consumer to signal a wakeup(), can be NULL.
Definition at line 145 of file MessageBuffer.hh.
Referenced by enqueue(), getConsumer(), MessageBuffer(), print(), reanalyzeList(), recycle(), and setConsumer().
m_dequeue_callback
std::function<void()> MessageBuffer::m_dequeue_callback private
Definition at line 148 of file MessageBuffer.hh.
Referenced by dequeue(), MessageBuffer(), registerDequeueCallback(), and unregisterDequeueCallback().
m_input_link_id
int MessageBuffer::m_input_link_id private
Definition at line 205 of file MessageBuffer.hh.
Referenced by MessageBuffer(), and setIncomingLink().
m_last_arrival_time
Tick MessageBuffer::m_last_arrival_time private
Definition at line 192 of file MessageBuffer.hh.
Referenced by enqueue().
m_max_size
const unsigned int MessageBuffer::m_max_size private
The maximum capacity.
For finite-sized buffers, m_max_size stores a number greater than 0 to indicate the maximum allowed number of messages in the buffer at any time. To get infinitely-sized buffers, set buffer size: m_max_size = 0
Definition at line 183 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), and regStats().
m_msg_counter
uint64_t MessageBuffer::m_msg_counter private
Definition at line 200 of file MessageBuffer.hh.
Referenced by clear(), clearStats(), enqueue(), and MessageBuffer().
m_msgs_this_cycle
unsigned int MessageBuffer::m_msgs_this_cycle private
Definition at line 196 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), enqueue(), and MessageBuffer().
m_not_avail_count
Stats::Scalar MessageBuffer::m_not_avail_count private
Definition at line 198 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clearStats(), and regStats().
m_occupancy
Stats::Formula MessageBuffer::m_occupancy private
Definition at line 211 of file MessageBuffer.hh.
Referenced by regStats().
m_prio_heap
std::vector<MsgPtr> MessageBuffer::m_prio_heap private
Definition at line 146 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), delayHead(), dequeue(), enqueue(), functionalWrite(), getSize(), isEmpty(), isReady(), peek(), peekMsgPtr(), print(), reanalyzeList(), recycle(), and stallMessage().
m_priority_rank
int MessageBuffer::m_priority_rank private
Definition at line 201 of file MessageBuffer.hh.
Referenced by getPriority(), MessageBuffer(), and setPriority().
m_randomization
const bool MessageBuffer::m_randomization private
Definition at line 203 of file MessageBuffer.hh.
Referenced by enqueue().
m_size_at_cycle_start
unsigned int MessageBuffer::m_size_at_cycle_start private
Definition at line 194 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), dequeue(), and MessageBuffer().
m_size_last_time_size_checked
unsigned int MessageBuffer::m_size_last_time_size_checked private
Definition at line 186 of file MessageBuffer.hh.
Referenced by getSize(), and MessageBuffer().
m_stall_count
Stats::Scalar MessageBuffer::m_stall_count private
Definition at line 210 of file MessageBuffer.hh.
Referenced by regStats(), and stallMessage().
m_stall_map_size
int MessageBuffer::m_stall_map_size private
Current size of the stall map.
Track the number of messages held in stall map lists. This is used to ensure that if the buffer is finite-sized, it blocks further requests when the m_prio_heap and m_stall_msg_map contain m_max_size messages.
Definition at line 175 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), dequeue(), reanalyzeAllMessages(), reanalyzeMessages(), and stallMessage().
m_stall_msg_map
StallMsgMapType MessageBuffer::m_stall_msg_map private
A map from line addresses to lists of stalled messages for that line.
If this buffer allows the receiver to stall messages, on a stall request, the stalled message is removed from the m_prio_heap and placed in the m_stall_msg_map. Messages are held there until the receiver requests they be reanalyzed, at which point they are moved back to m_prio_heap.
NOTE: The stall map holds messages in the order in which they were initially received, and when a line is unblocked, the messages are moved back to the m_prio_heap in the same order. This prevents starving older requests with younger ones.
Definition at line 167 of file MessageBuffer.hh.
Referenced by functionalWrite(), getStallMapSize(), isStallMapEmpty(), MessageBuffer(), reanalyzeAllMessages(), reanalyzeMessages(), and stallMessage().
m_stall_time
Stats::Average MessageBuffer::m_stall_time private
Definition at line 209 of file MessageBuffer.hh.
Referenced by dequeue(), MessageBuffer(), and regStats().
m_stalled_at_cycle_start
unsigned int MessageBuffer::m_stalled_at_cycle_start private
Definition at line 195 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), dequeue(), and MessageBuffer().
m_strict_fifo
const bool MessageBuffer::m_strict_fifo private
Definition at line 202 of file MessageBuffer.hh.
Referenced by enqueue(), and getOrdered().
m_time_last_time_enqueue
Tick MessageBuffer::m_time_last_time_enqueue private
Definition at line 190 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), and enqueue().
m_time_last_time_pop
Tick MessageBuffer::m_time_last_time_pop private
Definition at line 191 of file MessageBuffer.hh.
Referenced by areNSlotsAvailable(), clear(), and dequeue().
m_time_last_time_size_checked
Tick MessageBuffer::m_time_last_time_size_checked private
Definition at line 185 of file MessageBuffer.hh.
Referenced by getSize().
m_vnet_id
int MessageBuffer::m_vnet_id private
Definition at line 206 of file MessageBuffer.hh.
Referenced by enqueue(), MessageBuffer(), and setVnet().
The documentation for this class was generated from the following files:
mem/ruby/network/MessageBuffer.hh
mem/ruby/network/MessageBuffer.cc