gem5: Fifo< T > Class Template Reference
Fifo< T > Class Template Reference
Simple FIFO implementation backed by a circular buffer.
#include <circlebuf.hh>
Public Types
typedef T value_type
Public Member Functions
Fifo (size_t size)
bool empty () const
size_t size () const
size_t capacity () const
void flush ()
template<class OutputIterator >
void peek (OutputIterator out, size_t len) const
template<class OutputIterator >
void read (OutputIterator out, size_t len)
template<class InputIterator >
void write (InputIterator in, size_t len)
Private Attributes
CircleBuf< value_type > buf
Detailed Description
template<typename T>
class Fifo< T >
Simple FIFO implementation backed by a circular buffer.
This class provides the same basic functionallity as the circular buffer with the folling differences:
Writes are checked to ensure that overflows can't happen.
Unserialization ensures that the data in the checkpoint fits in the buffer.
Definition at line 142 of file circlebuf.hh.
Member Typedef Documentation
value_type
template<typename T> typedef T Fifo< T >::value_type
Definition at line 145 of file circlebuf.hh.
Constructor & Destructor Documentation
Fifo()
template<typename T> Fifo< T >::Fifo (size_t size) inline
Definition at line 148 of file circlebuf.hh.
Member Function Documentation
capacity()
template<typename T> size_t Fifo< T >::capacity () const inline
Definition at line 153 of file circlebuf.hh.
Referenced by arrayParamIn(), and DmaReadFifo::resumeFillFunctional().
empty()
template<typename T> bool Fifo< T >::empty () const inline
Definition at line 151 of file circlebuf.hh.
flush()
template<typename T> void Fifo< T >::flush () inline
Definition at line 155 of file circlebuf.hh.
Referenced by arrayParamIn().
peek()
template<typename T> template<class OutputIterator > void Fifo< T >::peek (OutputIterator out, size_t len) const inline
Definition at line 158 of file circlebuf.hh.
Referenced by arrayParamOut().
read()
template<typename T> template<class OutputIterator > void Fifo< T >::read (OutputIterator out, size_t len) inline
Definition at line 160 of file circlebuf.hh.
Referenced by DmaReadFifo::tryGet().
size()
template<typename T> size_t Fifo< T >::size () const inline
Definition at line 152 of file circlebuf.hh.
Referenced by arrayParamOut(), DmaReadFifo::resumeFillFunctional(), DmaReadFifo::resumeFillTiming(), and DmaReadFifo::tryGet().
write()
template<typename T> template<class InputIterator > void Fifo< T >::write (InputIterator in, size_t len) inline
Definition at line 163 of file circlebuf.hh.
Referenced by arrayParamIn(), DmaReadFifo::handlePending(), and DmaReadFifo::resumeFillFunctional().
Member Data Documentation
buf
template<typename T> CircleBuf<value_type> Fifo< T >::buf private
Definition at line 170 of file circlebuf.hh.
The documentation for this class was generated from the following file:
base/circlebuf.hh