gem5: Switch Class Reference
Switch Class Reference
#include <Switch.hh>
Public Types
typedef SwitchParams Params
Public Types inherited from BasicRouter
typedef BasicRouterParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Switch (const Params *p)
~Switch ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void addInPort (const std::vector< MessageBuffer *> &in)
void addOutPort (const std::vector< MessageBuffer *> &out, const NetDest &routing_table_entry, Cycles link_latency, int bw_multiplier)
const Throttle * getThrottle (LinkID link_number) const
void resetStats ()
Callback to reset stats.
void collateStats ()
void regStats ()
Callback to set stat parameters.
const Stats::Formula & getMsgCount (unsigned int type) const
void print (std::ostream &out) const
void init_net_ptr (SimpleNetwork *net_ptr)
bool functionalRead (Packet *)
uint32_t functionalWrite (Packet *)
Public Member Functions inherited from BasicRouter
BasicRouter (const Params *p)
const Params * params () const
void print (std::ostream &out) const
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
Switch (const Switch &obj)
Switch & operator= (const Switch &obj)
Private Attributes
PerfectSwitch * m_perfect_switch
SimpleNetwork * m_network_ptr
std::vector< Throttle * > m_throttles
std::vector< MessageBuffer * > m_port_buffers
unsigned m_num_connected_buffers
Stats::Formula m_avg_utilization
Stats::Formula m_msg_counts [MessageSizeType_NUM]
Stats::Formula m_msg_bytes [MessageSizeType_NUM]
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from BasicRouter
uint32_t m_id
uint32_t m_latency
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 57 of file Switch.hh.
Member Typedef Documentation
Params
typedef SwitchParams Switch::Params
Definition at line 60 of file Switch.hh.
Constructor & Destructor Documentation
Switch() [1/2]
Switch::Switch (const Params * p)
Definition at line 44 of file Switch.cc.
References BasicRouter::m_id, m_num_connected_buffers, m_perfect_switch, and m_port_buffers.
Referenced by functionalWrite(), and init_net_ptr().
~Switch()
Switch::~Switch ()
Definition at line 51 of file Switch.cc.
References m5::stl_helpers::deletePointers(), m_perfect_switch, m_port_buffers, and m_throttles.
Switch() [2/2]
Switch::Switch (const Switch & obj) private
Member Function Documentation
addInPort()
void Switch::addInPort (const std::vector< MessageBuffer *> & in)
Definition at line 70 of file Switch.cc.
References PerfectSwitch::addInPort(), and m_perfect_switch.
addOutPort()
void Switch::addOutPort (const std::vector< MessageBuffer *> & out, const NetDest & routing_table_entry, Cycles link_latency, int bw_multiplier)
Definition at line 76 of file Switch.cc.
References Throttle::addLinks(), PerfectSwitch::addOutPort(), SimpleNetwork::getEndpointBandwidth(), ArmISA::i, BasicRouter::m_id, m_network_ptr, m_num_connected_buffers, m_perfect_switch, m_port_buffers, m_throttles, Network::params(), and ArmISA::rs.
collateStats()
void Switch::collateStats ()
Definition at line 159 of file Switch.cc.
References PerfectSwitch::collateStats(), ArmISA::i, m_perfect_switch, and m_throttles.
functionalRead()
bool Switch::functionalRead (Packet * pkt)
Definition at line 175 of file Switch.cc.
Referenced by init_net_ptr().
functionalWrite()
uint32_t Switch::functionalWrite (Packet * pkt)
Definition at line 181 of file Switch.cc.
References ArmISA::i, m_port_buffers, and Switch().
Referenced by init_net_ptr().
getMsgCount()
const Stats::Formula& Switch::getMsgCount (unsigned int type) const inline
Definition at line 75 of file Switch.hh.
References m_msg_counts, print(), and type.
getThrottle()
const Throttle * Switch::getThrottle (LinkID link_number) const
Definition at line 107 of file Switch.cc.
References m_throttles.
init()
void Switch::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BasicRouter.
Definition at line 63 of file Switch.cc.
References BasicRouter::init(), PerfectSwitch::init(), m_network_ptr, and m_perfect_switch.
init_net_ptr()
void Switch::init_net_ptr (SimpleNetwork * net_ptr) inline
Definition at line 79 of file Switch.hh.
References functionalRead(), functionalWrite(), m_network_ptr, operator=(), and Switch().
Referenced by SimpleNetwork::SimpleNetwork().
operator=()
Switch& Switch::operator= (const Switch & obj) private
Referenced by init_net_ptr().
print()
void Switch::print (std::ostream & out) const
Definition at line 168 of file Switch.cc.
Referenced by getMsgCount(), and operator<<().
regStats()
void Switch::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 114 of file Switch.cc.
References Stats::constant(), Stats::DataWrap< Derived, InfoProxyType >::flags(), ArmISA::i, m_avg_utilization, m_msg_bytes, m_msg_counts, m_throttles, Network::MessageSizeType_to_int(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Stats::nozero, Stats::Group::regStats(), and type.
resetStats()
void Switch::resetStats () virtual
Callback to reset stats.
Reimplemented from Stats::Group.
Definition at line 150 of file Switch.cc.
References PerfectSwitch::clearStats(), ArmISA::i, m_perfect_switch, and m_throttles.
Member Data Documentation
m_avg_utilization
Stats::Formula Switch::m_avg_utilization private
Definition at line 96 of file Switch.hh.
Referenced by regStats().
m_msg_bytes
Stats::Formula Switch::m_msg_bytes[MessageSizeType_NUM] private
Definition at line 98 of file Switch.hh.
Referenced by regStats().
m_msg_counts
Stats::Formula Switch::m_msg_counts[MessageSizeType_NUM] private
Definition at line 97 of file Switch.hh.
Referenced by getMsgCount(), and regStats().
m_network_ptr
SimpleNetwork* Switch::m_network_ptr private
Definition at line 90 of file Switch.hh.
Referenced by addOutPort(), init(), and init_net_ptr().
m_num_connected_buffers
unsigned Switch::m_num_connected_buffers private
Definition at line 93 of file Switch.hh.
Referenced by addOutPort(), and Switch().
m_perfect_switch
PerfectSwitch* Switch::m_perfect_switch private
Definition at line 89 of file Switch.hh.
Referenced by addInPort(), addOutPort(), collateStats(), init(), resetStats(), Switch(), and ~Switch().
m_port_buffers
std::vector<MessageBuffer*> Switch::m_port_buffers private
Definition at line 92 of file Switch.hh.
Referenced by addOutPort(), functionalWrite(), Switch(), and ~Switch().
m_throttles
std::vector<Throttle*> Switch::m_throttles private
Definition at line 91 of file Switch.hh.
Referenced by addOutPort(), collateStats(), getThrottle(), regStats(), resetStats(), and ~Switch().
The documentation for this class was generated from the following files:
mem/ruby/network/simple/Switch.hh
mem/ruby/network/simple/Switch.cc