gem5: X86ISA::Interrupts Class Reference
X86ISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef X86LocalApicParams Params
Public Types inherited from BaseInterrupts
typedef BaseInterruptsParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
int getInitialApicId ()
void setCPU (BaseCPU *newCPU)
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Tick read (PacketPtr pkt)
Tick write (PacketPtr pkt)
Tick recvMessage (PacketPtr pkt)
void completeIPI (PacketPtr pkt)
bool triggerTimerInterrupt ()
AddrRangeList getAddrRanges () const
AddrRangeList getIntAddrRange () const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
uint32_t readReg (ApicRegIndex miscReg)
void setReg (ApicRegIndex reg, uint32_t val)
void setRegNoEffect (ApicRegIndex reg, uint32_t val)
Interrupts (Params *p)
bool checkInterrupts (ThreadContext *tc) const
bool checkInterruptsRaw () const
Check if there are pending interrupts without ignoring the interrupts disabled flag.
bool hasPendingUnmaskable () const
Check if there are pending unmaskable interrupts.
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
Public Member Functions inherited from BaseInterrupts
BaseInterrupts (Params *p)
const Params * params () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
BitUnion32 (LVTEntry) Bitfield< 7
EndBitUnion (LVTEntry) EventFunctionWrapper apicTimerEvent
void processApicTimerEvent ()
int findRegArrayMSB (ApicRegIndex base)
void updateIRRV ()
void updateISRV ()
void setRegArrayBit (ApicRegIndex base, uint8_t vector)
void clearRegArrayBit (ApicRegIndex base, uint8_t vector)
bool getRegArrayBit (ApicRegIndex base, uint8_t vector)
Tick clockPeriod () const
void requestInterrupt (uint8_t vector, uint8_t deliveryMode, bool level)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
System * sys
ClockDomain & clockDomain
uint32_t regs [NUM_APIC_REGS]
vector
Bitfield< 10, 8 > deliveryMode
Bitfield< 12 > status
Bitfield< 13 > polarity
Bitfield< 14 > remoteIRR
Bitfield< 15 > trigger
Bitfield< 16 > masked
Bitfield< 17 > periodic
bool pendingSmi
uint8_t smiVector
bool pendingNmi
uint8_t nmiVector
bool pendingExtInt
uint8_t extIntVector
bool pendingInit
uint8_t initVector
bool pendingStartup
uint8_t startupVector
bool startedUp
bool pendingUnmaskableInt
int pendingIPIs
uint8_t IRRV
uint8_t ISRV
BaseCPU * cpu
int initialApicId
IntSlavePort< Interrupts > intSlavePort
IntMasterPort< Interrupts > intMasterPort
PioPort< Interrupts > pioPort
Tick pioDelay
Addr pioAddr = MaxAddr
Protected Attributes inherited from BaseInterrupts
BaseCPU * cpu
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 76 of file interrupts.hh.
Member Typedef Documentation
Params
typedef X86LocalApicParams X86ISA::Interrupts::Params
Definition at line 197 of file interrupts.hh.
Constructor & Destructor Documentation
Interrupts()
X86ISA::Interrupts::Interrupts (Params * p)
Definition at line 598 of file interrupts.cc.
References X86ISA::APIC_DESTINATION_FORMAT, cpu, extIntVector, initVector, intMasterPort, intSlavePort, IRRV, ISRV, SimObject::name(), nmiVector, X86ISA::p, pendingExtInt, pendingInit, pendingIPIs, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, pioDelay, pioPort, processApicTimerEvent(), regs, smiVector, startedUp, and startupVector.
Referenced by setRegNoEffect().
Member Function Documentation
BitUnion32()
X86ISA::Interrupts::BitUnion32 (LVTEntry) protected
checkInterrupts()
bool X86ISA::Interrupts::checkInterrupts (ThreadContext * tc) const virtual
Implements BaseInterrupts.
Definition at line 621 of file interrupts.cc.
References X86ISA::APIC_TASK_PRIORITY, bits(), DPRINTF, IRRV, ISRV, X86ISA::MISCREG_RFLAGS, pendingExtInt, pendingUnmaskableInt, ThreadContext::readMiscRegNoEffect(), and regs.
Referenced by getInterrupt(), setRegNoEffect(), and updateIntrInfo().
checkInterruptsRaw()
bool X86ISA::Interrupts::checkInterruptsRaw () const
Check if there are pending interrupts without ignoring the interrupts disabled flag.
Returns
true if there are interrupts pending.
Definition at line 643 of file interrupts.cc.
References X86ISA::APIC_TASK_PRIORITY, bits(), IRRV, ISRV, pendingExtInt, pendingUnmaskableInt, and regs.
Referenced by setRegNoEffect().
clear()
void X86ISA::Interrupts::clear (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 301 of file interrupts.hh.
References panic.
clearAll()
void X86ISA::Interrupts::clearAll () inline virtual
Reimplemented from BaseInterrupts.
Definition at line 307 of file interrupts.hh.
References panic.
clearRegArrayBit()
void X86ISA::Interrupts::clearRegArrayBit (ApicRegIndex base, uint8_t vector) inline protected
Definition at line 161 of file interrupts.hh.
Referenced by updateIntrInfo().
clockPeriod()
Tick X86ISA::Interrupts::clockPeriod () const inline protected
Definition at line 172 of file interrupts.hh.
References ClockDomain::clockPeriod(), deliveryMode, X86ISA::level, requestInterrupt(), and vector.
completeIPI()
void X86ISA::Interrupts::completeIPI (PacketPtr pkt)
Definition at line 332 of file interrupts.cc.
References X86ISA::APIC_INTERRUPT_COMMAND_LOW, and DPRINTF.
Referenced by params().
EndBitUnion()
X86ISA::Interrupts::EndBitUnion (LVTEntry) protected
findRegArrayMSB()
int X86ISA::Interrupts::findRegArrayMSB (ApicRegIndex base) inline protected
Definition at line 131 of file interrupts.hh.
References findMsbSet(), and X86ISA::offset.
Referenced by updateIRRV(), and updateISRV().
getAddrRanges()
AddrRangeList X86ISA::Interrupts::getAddrRanges () const
Definition at line 346 of file interrupts.cc.
References X86ISA::PageBytes, and RangeSize().
Referenced by triggerTimerInterrupt().
getInitialApicId()
int X86ISA::Interrupts::getInitialApicId () inline
Definition at line 192 of file interrupts.hh.
References initialApicId.
getIntAddrRange()
AddrRangeList X86ISA::Interrupts::getIntAddrRange () const
Definition at line 356 of file interrupts.cc.
References X86ISA::PhysAddrAPICRangeSize, RangeEx(), and X86ISA::x86InterruptAddress().
Referenced by triggerTimerInterrupt().
getInterrupt()
Fault X86ISA::Interrupts::getInterrupt (ThreadContext * tc) virtual
Implements BaseInterrupts.
Definition at line 651 of file interrupts.cc.
References checkInterrupts(), DPRINTF, extIntVector, initVector, IRRV, nmiVector, NoFault, panic, pendingExtInt, pendingInit, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, and startupVector.
Referenced by hasPendingUnmaskable().
getPort()
Port& X86ISA::Interrupts::getPort (const std::string & if_name, PortID idx = InvalidPortID) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 232 of file interrupts.hh.
References SimObject::getPort(), intMasterPort, intSlavePort, pioPort, readReg(), X86ISA::reg, setReg(), and X86ISA::val.
getRegArrayBit()
bool X86ISA::Interrupts::getRegArrayBit (ApicRegIndex base, uint8_t vector) inline protected
Definition at line 167 of file interrupts.hh.
References bits().
hasPendingUnmaskable()
bool X86ISA::Interrupts::hasPendingUnmaskable () const inline
Check if there are pending unmaskable interrupts.
Returns
true there are unmaskable interrupts pending.
Definition at line 280 of file interrupts.hh.
References getInterrupt(), pendingUnmaskableInt, serialize(), unserialize(), and updateIntrInfo().
init()
void X86ISA::Interrupts::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 291 of file interrupts.cc.
References name(), and panic_if.
Referenced by params().
params()
const Params* X86ISA::Interrupts::params () const inline
Definition at line 202 of file interrupts.hh.
References SimObject::_params, completeIPI(), init(), read(), recvMessage(), and write().
post()
void X86ISA::Interrupts::post (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 295 of file interrupts.hh.
References panic.
processApicTimerEvent()
void X86ISA::Interrupts::processApicTimerEvent () protected
Definition at line 783 of file interrupts.cc.
References X86ISA::APIC_INITIAL_COUNT, readReg(), setReg(), and triggerTimerInterrupt().
Referenced by Interrupts().
read()
Tick X86ISA::Interrupts::read (PacketPtr pkt)
Definition at line 192 of file interrupts.cc.
References X86ISA::decodeAddr(), DPRINTF, Packet::getAddr(), Packet::getSize(), htole(), Packet::makeAtomicResponse(), X86ISA::mask, X86ISA::offset, panic, X86ISA::reg, Packet::setData(), and X86ISA::val.
Referenced by params().
readReg()
uint32_t X86ISA::Interrupts::readReg (ApicRegIndex miscReg)
Definition at line 367 of file interrupts.cc.
References X86ISA::APIC_ARBITRATION_PRIORITY, X86ISA::APIC_CURRENT_COUNT, X86ISA::APIC_DIVIDE_CONFIGURATION, X86ISA::APIC_ERROR_STATUS, X86ISA::APIC_INTERNAL_STATE, X86ISA::APIC_PROCESSOR_PRIORITY, X86ISA::APIC_TRIGGER_MODE(), curTick(), divideFromConf(), panic, X86ISA::reg, ULL, and X86ISA::val.
Referenced by getPort(), and processApicTimerEvent().
recvMessage()
Tick X86ISA::Interrupts::recvMessage (PacketPtr pkt)
Definition at line 304 of file interrupts.cc.
References Packet::cmd, DPRINTF, Packet::getAddr(), Packet::getRaw(), Packet::makeAtomicResponse(), X86ISA::offset, panic, MemCmd::WriteReq, and X86ISA::x86InterruptAddress().
Referenced by params().
requestInterrupt()
void X86ISA::Interrupts::requestInterrupt (uint8_t vector, uint8_t deliveryMode, bool level) protected
Definition at line 226 of file interrupts.cc.
References X86ISA::APIC_INTERRUPT_REQUEST_BASE, X86ISA::APIC_TRIGGER_MODE_BASE, DPRINTF, FullSystem, and X86ISA::vector.
Referenced by clockPeriod(), and triggerTimerInterrupt().
serialize()
void X86ISA::Interrupts::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 720 of file interrupts.cc.
References extIntVector, initVector, IRRV, ISRV, nmiVector, X86ISA::NUM_APIC_REGS, pendingExtInt, pendingInit, pendingIPIs, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, regs, SERIALIZE_ARRAY, SERIALIZE_SCALAR, smiVector, startedUp, and startupVector.
Referenced by hasPendingUnmaskable().
setCPU()
void X86ISA::Interrupts::setCPU (BaseCPU * newCPU) virtual
Implements BaseInterrupts.
Definition at line 276 of file interrupts.cc.
References X86ISA::APIC_ID, BaseCPU::cpuId(), panic, and X86ISA::x86LocalAPICAddress().
setReg()
void X86ISA::Interrupts::setReg (ApicRegIndex reg, uint32_t val)
Definition at line 405 of file interrupts.cc.
References X86ISA::APIC_ARBITRATION_PRIORITY, X86ISA::APIC_CURRENT_COUNT, X86ISA::APIC_DESTINATION_FORMAT, X86ISA::APIC_DIVIDE_CONFIGURATION, X86ISA::APIC_EOI, X86ISA::APIC_ERROR_STATUS, X86ISA::APIC_ID, X86ISA::APIC_IN_SERVICE(), X86ISA::APIC_IN_SERVICE_BASE, X86ISA::APIC_INITIAL_COUNT, X86ISA::APIC_INTERNAL_STATE, X86ISA::APIC_INTERRUPT_COMMAND_HIGH, X86ISA::APIC_INTERRUPT_COMMAND_LOW, X86ISA::APIC_INTERRUPT_REQUEST(), X86ISA::APIC_LOGICAL_DESTINATION, X86ISA::APIC_LVT_ERROR, X86ISA::APIC_LVT_LINT0, X86ISA::APIC_LVT_LINT1, X86ISA::APIC_LVT_PERFORMANCE_MONITORING_COUNTERS, X86ISA::APIC_LVT_THERMAL_SENSOR, X86ISA::APIC_LVT_TIMER, X86ISA::APIC_PROCESSOR_PRIORITY, X86ISA::APIC_SPURIOUS_INTERRUPT_VECTOR, X86ISA::APIC_TASK_PRIORITY, X86ISA::APIC_TRIGGER_MODE(), X86ISA::APIC_VERSION, bits(), X86ISA::buildIntTriggerPacket(), curTick(), divideFromConf(), hack_once, ArmISA::i, X86ISA::offset, panic, X86ISA::reg, ULL, X86ISA::val, and warn.
Referenced by getPort(), and processApicTimerEvent().
setRegArrayBit()
void X86ISA::Interrupts::setRegArrayBit (ApicRegIndex base, uint8_t vector) inline protected
Definition at line 155 of file interrupts.hh.
Referenced by updateIntrInfo().
setRegNoEffect()
void X86ISA::Interrupts::setRegNoEffect (ApicRegIndex reg, uint32_t val) inline
Definition at line 252 of file interrupts.hh.
References checkInterrupts(), checkInterruptsRaw(), Interrupts(), X86ISA::p, X86ISA::reg, and X86ISA::val.
Referenced by X86ISA::initCPU().
triggerTimerInterrupt()
bool X86ISA::Interrupts::triggerTimerInterrupt () inline
Definition at line 221 of file interrupts.hh.
References X86ISA::APIC_LVT_TIMER, getAddrRanges(), getIntAddrRange(), and requestInterrupt().
Referenced by processApicTimerEvent().
unserialize()
void X86ISA::Interrupts::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 745 of file interrupts.cc.
References extIntVector, initVector, IRRV, ISRV, nmiVector, X86ISA::NUM_APIC_REGS, pendingExtInt, pendingInit, pendingIPIs, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, regs, EventManager::reschedule(), EventManager::schedule(), smiVector, startedUp, startupVector, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by hasPendingUnmaskable().
updateIntrInfo()
void X86ISA::Interrupts::updateIntrInfo (ThreadContext * tc) virtual
Implements BaseInterrupts.
Definition at line 685 of file interrupts.cc.
References X86ISA::APIC_IN_SERVICE_BASE, X86ISA::APIC_INTERRUPT_REQUEST_BASE, checkInterrupts(), clearRegArrayBit(), DPRINTF, IRRV, ISRV, pendingExtInt, pendingInit, pendingNmi, pendingSmi, pendingStartup, pendingUnmaskableInt, setRegArrayBit(), startedUp, and updateIRRV().
Referenced by hasPendingUnmaskable().
updateIRRV()
void X86ISA::Interrupts::updateIRRV () inline protected
Definition at line 143 of file interrupts.hh.
References X86ISA::APIC_INTERRUPT_REQUEST_BASE, findRegArrayMSB(), and IRRV.
Referenced by updateIntrInfo().
updateISRV()
void X86ISA::Interrupts::updateISRV () inline protected
Definition at line 149 of file interrupts.hh.
References X86ISA::APIC_IN_SERVICE_BASE, findRegArrayMSB(), and ISRV.
write()
Tick X86ISA::Interrupts::write (PacketPtr pkt)
Definition at line 209 of file interrupts.cc.
References X86ISA::decodeAddr(), DPRINTF, Packet::getAddr(), Packet::getSize(), letoh(), Packet::makeAtomicResponse(), X86ISA::mask, X86ISA::offset, panic, X86ISA::reg, X86ISA::val, and Packet::writeData().
Referenced by params().
Member Data Documentation
clockDomain
ClockDomain& X86ISA::Interrupts::clockDomain protected
Definition at line 80 of file interrupts.hh.
cpu
BaseCPU* X86ISA::Interrupts::cpu protected
Definition at line 176 of file interrupts.hh.
Referenced by Interrupts().
deliveryMode
Bitfield<10, 8> X86ISA::Interrupts::deliveryMode protected
Definition at line 87 of file interrupts.hh.
Referenced by clockPeriod().
extIntVector
uint8_t X86ISA::Interrupts::extIntVector protected
Definition at line 111 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), and unserialize().
initialApicId
int X86ISA::Interrupts::initialApicId protected
Definition at line 178 of file interrupts.hh.
Referenced by getInitialApicId().
initVector
uint8_t X86ISA::Interrupts::initVector protected
Definition at line 113 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), and unserialize().
intMasterPort
IntMasterPort<Interrupts> X86ISA::Interrupts::intMasterPort protected
Definition at line 182 of file interrupts.hh.
Referenced by getPort(), and Interrupts().
intSlavePort
IntSlavePort<Interrupts> X86ISA::Interrupts::intSlavePort protected
Definition at line 181 of file interrupts.hh.
Referenced by getPort(), and Interrupts().
IRRV
uint8_t X86ISA::Interrupts::IRRV protected
Definition at line 127 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), Interrupts(), serialize(), unserialize(), updateIntrInfo(), and updateIRRV().
ISRV
uint8_t X86ISA::Interrupts::ISRV protected
Definition at line 128 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), Interrupts(), serialize(), unserialize(), updateIntrInfo(), and updateISRV().
masked
Bitfield<16> X86ISA::Interrupts::masked protected
Definition at line 92 of file interrupts.hh.
nmiVector
uint8_t X86ISA::Interrupts::nmiVector protected
Definition at line 109 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), and unserialize().
pendingExtInt
bool X86ISA::Interrupts::pendingExtInt protected
Definition at line 110 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
pendingInit
bool X86ISA::Interrupts::pendingInit protected
Definition at line 112 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
pendingIPIs
int X86ISA::Interrupts::pendingIPIs protected
Definition at line 122 of file interrupts.hh.
Referenced by Interrupts(), serialize(), and unserialize().
pendingNmi
bool X86ISA::Interrupts::pendingNmi protected
Definition at line 108 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
pendingSmi
bool X86ISA::Interrupts::pendingSmi protected
Definition at line 106 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
pendingStartup
bool X86ISA::Interrupts::pendingStartup protected
Definition at line 114 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
pendingUnmaskableInt
bool X86ISA::Interrupts::pendingUnmaskableInt protected
Definition at line 119 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), getInterrupt(), hasPendingUnmaskable(), Interrupts(), serialize(), unserialize(), and updateIntrInfo().
periodic
Bitfield<17> X86ISA::Interrupts::periodic protected
Definition at line 93 of file interrupts.hh.
pioAddr
Addr X86ISA::Interrupts::pioAddr = MaxAddr protected
Definition at line 188 of file interrupts.hh.
pioDelay
Tick X86ISA::Interrupts::pioDelay protected
Definition at line 187 of file interrupts.hh.
Referenced by Interrupts().
pioPort
PioPort<Interrupts> X86ISA::Interrupts::pioPort protected
Definition at line 185 of file interrupts.hh.
Referenced by getPort(), and Interrupts().
polarity
Bitfield<13> X86ISA::Interrupts::polarity protected
Definition at line 89 of file interrupts.hh.
regs
uint32_t X86ISA::Interrupts::regs[NUM_APIC_REGS] protected
Definition at line 83 of file interrupts.hh.
Referenced by checkInterrupts(), checkInterruptsRaw(), Interrupts(), serialize(), and unserialize().
remoteIRR
Bitfield<14> X86ISA::Interrupts::remoteIRR protected
Definition at line 90 of file interrupts.hh.
smiVector
uint8_t X86ISA::Interrupts::smiVector protected
Definition at line 107 of file interrupts.hh.
Referenced by Interrupts(), serialize(), and unserialize().
startedUp
bool X86ISA::Interrupts::startedUp protected
Definition at line 116 of file interrupts.hh.
Referenced by Interrupts(), serialize(), unserialize(), and updateIntrInfo().
startupVector
uint8_t X86ISA::Interrupts::startupVector protected
Definition at line 115 of file interrupts.hh.
Referenced by getInterrupt(), Interrupts(), serialize(), and unserialize().
status
Bitfield<12> X86ISA::Interrupts::status protected
Definition at line 88 of file interrupts.hh.
sys
System* X86ISA::Interrupts::sys protected
Definition at line 79 of file interrupts.hh.
trigger
Bitfield<15> X86ISA::Interrupts::trigger protected
Definition at line 91 of file interrupts.hh.
vector
X86ISA::Interrupts::vector protected
Definition at line 86 of file interrupts.hh.
Referenced by clockPeriod().
The documentation for this class was generated from the following files:
arch/x86/interrupts.hh
arch/x86/interrupts.cc