gem5: TrafficGen Class Reference
TrafficGen Class Reference
The traffic generator is a master module that generates stimuli for the memory system, based on a collection of simple behaviours that are either probabilistic or based on traces.
#include <traffic_gen.hh>
Classes
struct Transition
Struct to represent a probabilistic transition during parsing.
Public Member Functions
TrafficGen (const TrafficGenParams *p)
~TrafficGen ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from BaseTrafficGen
BaseTrafficGen (const BaseTrafficGenParams *p)
~BaseTrafficGen ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
DrainState drain () override
Notify an object that it needs to drain its state.
std::shared_ptr< BaseGen > createIdle (Tick duration)
std::shared_ptr< BaseGen > createExit (Tick duration)
std::shared_ptr< BaseGen > createLinear (Tick duration, Addr start_addr, Addr end_addr, Addr blocksize, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
std::shared_ptr< BaseGen > createRandom (Tick duration, Addr start_addr, Addr end_addr, Addr blocksize, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
std::shared_ptr< BaseGen > createDram (Tick duration, Addr start_addr, Addr end_addr, Addr blocksize, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit, unsigned int num_seq_pkts, unsigned int page_size, unsigned int nbr_of_banks_DRAM, unsigned int nbr_of_banks_util, Enums::AddrMap addr_mapping, unsigned int nbr_of_ranks)
std::shared_ptr< BaseGen > createDramRot (Tick duration, Addr start_addr, Addr end_addr, Addr blocksize, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit, unsigned int num_seq_pkts, unsigned int page_size, unsigned int nbr_of_banks_DRAM, unsigned int nbr_of_banks_util, Enums::AddrMap addr_mapping, unsigned int nbr_of_ranks, unsigned int max_seq_count_per_rank)
std::shared_ptr< BaseGen > createTrace (Tick duration, const std::string &trace_file, Addr addr_offset)
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
std::shared_ptr< BaseGen > nextGenerator () override
Protected Member Functions inherited from BaseTrafficGen
void start ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Private Member Functions
std::string resolveFile (const std::string &name)
Resolve a file path in the configuration file.
void parseConfig ()
Parse the config file and build the state map and transition matrix.
size_t nextState ()
Use the transition matrix to find the next state index.
Private Attributes
const std::string configFile
The config file to parse.
std::vector< std::vector< double > > transitionMatrix
State transition matrix.
uint32_t currState
Index of the current state.
std::unordered_map< uint32_t, std::shared_ptr< BaseGen > > states
Map of generator states.
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from BaseTrafficGen
System *const system
The system used to determine which mode we are currently operating in.
const bool elasticReq
Determine whether to add elasticity in the request injection, thus responding to backpressure by slowing things down.
const Tick progressCheck
Time to tolerate waiting for retries (not making progress), until we declare things broken.
std::unordered_map< RequestPtr, Tick > waitingResp
Reqs waiting for response.
BaseTrafficGen::StatGroup stats
const MasterID masterID
MasterID used in generated requests.
std::shared_ptr< BaseGen > activeGenerator
Currently active generator.
std::unique_ptr< StreamGen > streamGenerator
Stream/SubStreamID Generator.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
The traffic generator is a master module that generates stimuli for the memory system, based on a collection of simple behaviours that are either probabilistic or based on traces.
It can be used stand alone for creating test cases for interconnect and memory controllers, or function as a black-box replacement for system components that are not yet modelled in detail, e.g. a video engine or baseband subsystem in an SoC.
The traffic generator has a single master port that is used to send requests, independent of the specific behaviour. The behaviour of the traffic generator is specified in a configuration file, and this file describes a state transition graph where each state is a specific generator behaviour. Examples include idling, generating linear address sequences, random sequences and replay of captured traces. By describing these behaviours as states, it is straight forward to create very complex behaviours, simply by arranging them in graphs. The graph transitions can also be annotated with probabilities, effectively making it a Markov Chain.
Definition at line 71 of file traffic_gen.hh.
Constructor & Destructor Documentation
TrafficGen()
TrafficGen::TrafficGen (const TrafficGenParams * p)
Definition at line 58 of file traffic_gen.cc.
~TrafficGen()
TrafficGen::~TrafficGen () inline
Definition at line 129 of file traffic_gen.hh.
References init(), initState(), serialize(), and unserialize().
Member Function Documentation
init()
void TrafficGen::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseTrafficGen.
Definition at line 72 of file traffic_gen.cc.
References BaseTrafficGen::init(), and parseConfig().
Referenced by ~TrafficGen().
initState()
void TrafficGen::initState () override virtual
initState() is called on each SimObject when not restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from SimObject.
Definition at line 80 of file traffic_gen.cc.
References DPRINTF, SimObject::initState(), System::isTimingMode(), BaseTrafficGen::start(), and BaseTrafficGen::system.
Referenced by ~TrafficGen().
nextGenerator()
std::shared_ptr< BaseGen > TrafficGen::nextGenerator () override protected virtual
Implements BaseTrafficGen.
Definition at line 358 of file traffic_gen.cc.
References BaseTrafficGen::activeGenerator, currState, DPRINTF, nextState(), and states.
nextState()
size_t TrafficGen::nextState () private
Use the transition matrix to find the next state index.
Definition at line 343 of file traffic_gen.cc.
References currState, ArmISA::i, MipsISA::p, Random::random(), random_mt, and transitionMatrix.
Referenced by nextGenerator().
parseConfig()
void TrafficGen::parseConfig () private
Parse the config file and build the state map and transition matrix.
Definition at line 135 of file traffic_gen.cc.
References configFile, BaseTrafficGen::createDram(), BaseTrafficGen::createDramRot(), BaseTrafficGen::createExit(), BaseTrafficGen::createIdle(), BaseTrafficGen::createLinear(), BaseTrafficGen::createRandom(), BaseTrafficGen::createTrace(), currState, divCeil(), DPRINTF, fatal, TrafficGen::Transition::from, ArmISA::i, ArmISA::id, MipsISA::is, ArmISA::j, ArmISA::mode, SimObject::name(), TrafficGen::Transition::p, resolveFile(), states, RiscvISA::sum, ArmISA::t, TrafficGen::Transition::to, BaseTrafficGen::transition(), transitionMatrix, and warn.
Referenced by init().
resolveFile()
std::string TrafficGen::resolveFile (const std::string & name) private
Resolve a file path in the configuration file.
This method resolves a relative path to a file that has been referenced in the configuration file. It first tries to resolve the file relative to the configuration file's path. If that fails, it falls back to constructing a path relative to the current working directory.
Absolute paths are returned unmodified.
Parameters
name Path to resolve
Definition at line 114 of file traffic_gen.cc.
References configFile, csprintf(), and SimObject::name().
Referenced by parseConfig().
serialize()
void TrafficGen::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from BaseTrafficGen.
Definition at line 95 of file traffic_gen.cc.
References currState, BaseTrafficGen::serialize(), and SERIALIZE_SCALAR.
Referenced by ~TrafficGen().
unserialize()
void TrafficGen::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from BaseTrafficGen.
Definition at line 103 of file traffic_gen.cc.
References currState, BaseTrafficGen::unserialize(), and UNSERIALIZE_SCALAR.
Referenced by ~TrafficGen().
Member Data Documentation
configFile
const std::string TrafficGen::configFile private
The config file to parse.
Definition at line 77 of file traffic_gen.hh.
Referenced by parseConfig(), and resolveFile().
currState
uint32_t TrafficGen::currState private
Index of the current state.
Definition at line 117 of file traffic_gen.hh.
Referenced by nextGenerator(), nextState(), parseConfig(), serialize(), and unserialize().
states
std::unordered_map<uint32_t, std::shared_ptr<BaseGen> > TrafficGen::states private
Map of generator states.
Definition at line 120 of file traffic_gen.hh.
Referenced by nextGenerator(), and parseConfig().
transitionMatrix
std::vector<std::vector<double> > TrafficGen::transitionMatrix private
State transition matrix.
Definition at line 114 of file traffic_gen.hh.
Referenced by nextState(), and parseConfig().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/traffic_gen.hh
cpu/testers/traffic_gen/traffic_gen.cc