gem5: QTIsaac< ALPHA > Class Template Reference
QTIsaac< ALPHA > Class Template Reference
#include <isaac.h>
Classes
struct randctx
Public Types
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
enum { N = (1<<ALPHA) }
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
typedef unsigned char byte
Public Member Functions
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
QTIsaac (UINT32 a=0, UINT32 b=0, UINT32 c=0)
virtual ~QTIsaac (void)
UINT32 rand (void)
virtual void randinit (randctx *ctx, bool bUseSeed)
virtual void srand (UINT32 a=0, UINT32 b=0, UINT32 c=0, UINT32 *s=NULL)
Protected Member Functions
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
virtual void isaac (randctx *ctx)
UINT32 ind (UINT32 *mm, UINT32 x)
void rngstep (UINT32 mix, UINT32 &a, UINT32 &b, UINT32 *&mm, UINT32 *&m, UINT32 *&m2, UINT32 *&r, UINT32 &x, UINT32 &y)
virtual void shuffle (UINT32 &a, UINT32 &b, UINT32 &c, UINT32 &d, UINT32 &e, UINT32 &f, UINT32 &g, UINT32 &h)
Private Attributes
randctx m_rc
Detailed Description
template<UINT32 ALPHA = (8)>
class QTIsaac< ALPHA >
Definition at line 40 of file isaac.h.
Member Typedef Documentation
byte [1/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [2/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [3/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [4/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [5/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [6/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [7/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [8/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [9/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [10/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [11/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [12/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [13/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
byte [14/14]
template<UINT32 ALPHA = (8)> typedef unsigned char QTIsaac< ALPHA >::byte
Definition at line 44 of file isaac.h.
Member Enumeration Documentation
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
anonymous enum
template<UINT32 ALPHA = (8)> anonymous enum
Enumerator
N
Definition at line 76 of file isaac.h.
Constructor & Destructor Documentation
QTIsaac() [1/14]
template<UINT32 ALPHA> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
Definition at line 96 of file isaac.h.
References QTIsaac< ALPHA >::srand().
Referenced by QTIsaac< ALPHA >::randctx::~randctx().
~QTIsaac() [1/14]
template<UINT32 ALPHA> QTIsaac< ALPHA >::~QTIsaac (void) virtual
Definition at line 103 of file isaac.h.
Referenced by QTIsaac< ALPHA >::randctx::~randctx().
QTIsaac() [2/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [2/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [3/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [3/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [4/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [4/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [5/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [5/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [6/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [6/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [7/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [7/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [8/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [8/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [9/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [9/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [10/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [10/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [11/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [11/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [12/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [12/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [13/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [13/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
QTIsaac() [14/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::QTIsaac (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0)
~QTIsaac() [14/14]
template<UINT32 ALPHA = (8)> virtual QTIsaac< ALPHA >::~QTIsaac (void) virtual
Member Function Documentation
ind() [1/14]
template<UINT32 ALPHA> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) inline protected
Definition at line 203 of file isaac.h.
References QTIsaac< ALPHA >::N.
Referenced by QTIsaac< ALPHA >::rngstep(), and QTIsaac< ALPHA >::randctx::~randctx().
ind() [2/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [3/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [4/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [5/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [6/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [7/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [8/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [9/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [10/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [11/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [12/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [13/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
ind() [14/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::ind (UINT32 * mm, UINT32 x) protected
isaac() [1/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [2/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [3/14]
template<UINT32 ALPHA> void QTIsaac< ALPHA >::isaac (randctx * ctx) inline protected virtual
Definition at line 234 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::m, SparcISA::mm, QTIsaac< ALPHA >::N, MipsISA::r, QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), and X86ISA::x.
Referenced by QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randinit(), and QTIsaac< ALPHA >::randctx::~randctx().
isaac() [4/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [5/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [6/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [7/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [8/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [9/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [10/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [11/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [12/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [13/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
isaac() [14/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::isaac (randctx * ctx) protected virtual
rand() [1/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [2/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [3/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [4/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [5/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [6/14]
template<UINT32 ALPHA> UINT32 QTIsaac< ALPHA >::rand (void) inline
Definition at line 126 of file isaac.h.
References QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::m_rc, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randcnt, and QTIsaac< ALPHA >::randctx::randrsl.
Referenced by QTIsaac< ALPHA >::randctx::~randctx().
rand() [7/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [8/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [9/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [10/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [11/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [12/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [13/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
rand() [14/14]
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::rand (void)
randinit() [1/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [2/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [3/14]
template<UINT32 ALPHA> void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) inline virtual
Definition at line 135 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::N, MipsISA::r, QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, and QTIsaac< ALPHA >::shuffle().
Referenced by QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
randinit() [4/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [5/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [6/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [7/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [8/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [9/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [10/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [11/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [12/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [13/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
randinit() [14/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::randinit (randctx * ctx, bool bUseSeed) virtual
rngstep() [1/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [2/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [3/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [4/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [5/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [6/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [7/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [8/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [9/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [10/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [11/14]
template<UINT32 ALPHA> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) inline protected
Definition at line 210 of file isaac.h.
References ArmISA::b, QTIsaac< ALPHA >::ind(), ArmISA::m, and X86ISA::x.
Referenced by QTIsaac< ALPHA >::isaac(), and QTIsaac< ALPHA >::randctx::~randctx().
rngstep() [12/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [13/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
rngstep() [14/14]
template<UINT32 ALPHA = (8)> void QTIsaac< ALPHA >::rngstep (UINT32 mix, UINT32 & a, UINT32 & b, UINT32 *& mm, UINT32 *& m, UINT32 *& m2, UINT32 *& r, UINT32 & x, UINT32 & y) protected
shuffle() [1/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [2/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [3/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [4/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [5/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [6/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [7/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [8/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [9/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [10/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [11/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [12/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [13/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) protected virtual
shuffle() [14/14]
template<UINT32 ALPHA> void QTIsaac< ALPHA >::shuffle (UINT32 & a, UINT32 & b, UINT32 & c, UINT32 & d, UINT32 & e, UINT32 & f, UINT32 & g, UINT32 & h) inline protected virtual
Definition at line 220 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, and MipsISA::g.
Referenced by QTIsaac< ALPHA >::randinit(), and QTIsaac< ALPHA >::randctx::~randctx().
srand() [1/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [2/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [3/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [4/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [5/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [6/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [7/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [8/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [9/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [10/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [11/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [12/14]
template<UINT32 ALPHA> void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
Definition at line 110 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::i, QTIsaac< ALPHA >::m_rc, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randinit(), and QTIsaac< ALPHA >::randctx::randrsl.
Referenced by QTIsaac< ALPHA >::QTIsaac(), and QTIsaac< ALPHA >::randctx::~randctx().
srand() [13/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
srand() [14/14]
template<UINT32 ALPHA = (8)> virtual void QTIsaac< ALPHA >::srand (UINT32 a = 0, UINT32 b = 0, UINT32 c = 0, UINT32 * s = NULL) virtual
Member Data Documentation
m_rc
template<UINT32 ALPHA = (8)> randctx QTIsaac< ALPHA >::m_rc private
Definition at line 91 of file isaac.h.
Referenced by QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
The documentation for this class was generated from the following file:
systemc/tests/systemc/datatypes/int/arith/arith02/isaac.h