gem5: SimpleATInitiator1 Class Reference
SimpleATInitiator1 Class Reference
#include <SimpleATInitiator1.h>
Classes
class MyTransaction
class SimplePool
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm_utils::simple_initiator_socket< SimpleATInitiator1 > initiator_socket_type
typedef MyTransaction< unsigned int > mytransaction_type
Public Member Functions
SC_HAS_PROCESS (SimpleATInitiator1)
SimpleATInitiator1 (sc_core::sc_module_name name, unsigned int nrOfTransactions=0x5, unsigned int baseAddress=0x0)
bool initTransaction (mytransaction_type *&trans)
void logStartTransation (mytransaction_type &trans)
void logEndTransaction (mytransaction_type &trans)
void run ()
sync_enum_type myNBTransport (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void endResponse ()
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Attributes
initiator_socket_type socket
Private Attributes
const sc_core::sc_time ACCEPT_DELAY
unsigned int mNrOfTransactions
unsigned int mBaseAddress
SimplePool transPool
unsigned int mTransactionCount
sc_core::sc_event mEndRequestPhase
std::queue< mytransaction_type * > mEndResponseQueue
sc_core::sc_event mEndResponseEvent
transaction_type * mCurrentTransaction
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
Definition at line 42 of file SimpleATInitiator1.h.
Member Typedef Documentation
initiator_socket_type
typedef tlm_utils::simple_initiator_socket<SimpleATInitiator1> SimpleATInitiator1::initiator_socket_type
Definition at line 48 of file SimpleATInitiator1.h.
mytransaction_type
typedef MyTransaction<unsigned int> SimpleATInitiator1::mytransaction_type
Definition at line 71 of file SimpleATInitiator1.h.
phase_type
typedef tlm::tlm_phase SimpleATInitiator1::phase_type
Definition at line 46 of file SimpleATInitiator1.h.
sync_enum_type
typedef tlm::tlm_sync_enum SimpleATInitiator1::sync_enum_type
Definition at line 47 of file SimpleATInitiator1.h.
transaction_type
typedef tlm::tlm_generic_payload SimpleATInitiator1::transaction_type
Definition at line 45 of file SimpleATInitiator1.h.
Constructor & Destructor Documentation
SimpleATInitiator1()
SimpleATInitiator1::SimpleATInitiator1 (sc_core::sc_module_name name, unsigned int nrOfTransactions = 0x5, unsigned int baseAddress = 0x0) inline
Definition at line 100 of file SimpleATInitiator1.h.
References sc_core::sc_module::dont_initialize(), endResponse(), mEndResponseEvent, myNBTransport(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_nb_transport_bw(), run(), SC_METHOD, SC_THREAD, and sc_core::sc_module::sensitive.
Member Function Documentation
endResponse()
void SimpleATInitiator1::endResponse () inline
Definition at line 295 of file SimpleATInitiator1.h.
References ACCEPT_DELAY, tlm::END_RESP, logEndTransaction(), mEndResponseEvent, mEndResponseQueue, sc_core::sc_event::notify(), MipsISA::r, SimpleATInitiator1::SimplePool::release(), sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_COMPLETED, and transPool.
Referenced by SimpleATInitiator1().
initTransaction()
bool SimpleATInitiator1::initTransaction (mytransaction_type *& trans) inline
Definition at line 122 of file SimpleATInitiator1.h.
References SimpleATInitiator1::SimplePool::claim(), mBaseAddress, mNrOfTransactions, mTransactionCount, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_command(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_streaming_width(), SimpleATInitiator1::MyTransaction< DT >::setData(), tlm::TLM_READ_COMMAND, tlm::TLM_WRITE_COMMAND, and transPool.
Referenced by run().
logEndTransaction()
void SimpleATInitiator1::logEndTransaction (mytransaction_type & trans) inline
Definition at line 161 of file SimpleATInitiator1.h.
References tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_response_status(), SimpleATInitiator1::MyTransaction< DT >::getData(), sc_core::sc_object::name(), sc_core::sc_time_stamp(), tlm::TLM_OK_RESPONSE, and tlm::TLM_READ_COMMAND.
Referenced by endResponse(), and run().
logStartTransation()
void SimpleATInitiator1::logStartTransation (mytransaction_type & trans) inline
Definition at line 146 of file SimpleATInitiator1.h.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), SimpleATInitiator1::MyTransaction< DT >::getData(), sc_core::sc_object::name(), sc_core::sc_time_stamp(), and tlm::TLM_WRITE_COMMAND.
Referenced by run().
myNBTransport()
sync_enum_type SimpleATInitiator1::myNBTransport (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline
Definition at line 255 of file SimpleATInitiator1.h.
References ACCEPT_DELAY, tlm::BEGIN_REQ, tlm::BEGIN_RESP, tlm::END_REQ, tlm::END_RESP, X86ISA::exit, mCurrentTransaction, mEndRequestPhase, mEndResponseEvent, mEndResponseQueue, sc_core::sc_event::notify(), sc_core::SC_ZERO_TIME, and tlm::TLM_ACCEPTED.
Referenced by SimpleATInitiator1().
run()
void SimpleATInitiator1::run () inline
Definition at line 183 of file SimpleATInitiator1.h.
References ACCEPT_DELAY, tlm::BEGIN_REQ, tlm::BEGIN_RESP, tlm::END_REQ, tlm::END_RESP, X86ISA::exit, initTransaction(), logEndTransaction(), logStartTransation(), mCurrentTransaction, mEndRequestPhase, mEndResponseEvent, mEndResponseQueue, sc_core::sc_event::notify(), SimpleATInitiator1::SimplePool::release(), sc_core::SC_ZERO_TIME, ArmISA::t, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, tlm::TLM_UPDATED, transPool, and sc_core::sc_module::wait().
Referenced by SimpleATInitiator1().
SC_HAS_PROCESS()
SimpleATInitiator1::SC_HAS_PROCESS (SimpleATInitiator1)
Member Data Documentation
ACCEPT_DELAY
const sc_core::sc_time SimpleATInitiator1::ACCEPT_DELAY private
Definition at line 320 of file SimpleATInitiator1.h.
Referenced by endResponse(), myNBTransport(), and run().
mBaseAddress
unsigned int SimpleATInitiator1::mBaseAddress private
Definition at line 324 of file SimpleATInitiator1.h.
Referenced by initTransaction().
mCurrentTransaction
transaction_type* SimpleATInitiator1::mCurrentTransaction private
Definition at line 330 of file SimpleATInitiator1.h.
Referenced by myNBTransport(), and run().
mEndRequestPhase
sc_core::sc_event SimpleATInitiator1::mEndRequestPhase private
Definition at line 327 of file SimpleATInitiator1.h.
Referenced by myNBTransport(), and run().
mEndResponseEvent
sc_core::sc_event SimpleATInitiator1::mEndResponseEvent private
Definition at line 329 of file SimpleATInitiator1.h.
Referenced by endResponse(), myNBTransport(), run(), and SimpleATInitiator1().
mEndResponseQueue
std::queue<mytransaction_type*> SimpleATInitiator1::mEndResponseQueue private
Definition at line 328 of file SimpleATInitiator1.h.
Referenced by endResponse(), myNBTransport(), and run().
mNrOfTransactions
unsigned int SimpleATInitiator1::mNrOfTransactions private
Definition at line 323 of file SimpleATInitiator1.h.
Referenced by initTransaction().
mTransactionCount
unsigned int SimpleATInitiator1::mTransactionCount private
Definition at line 326 of file SimpleATInitiator1.h.
Referenced by initTransaction().
socket
initiator_socket_type SimpleATInitiator1::socket
Definition at line 96 of file SimpleATInitiator1.h.
transPool
SimplePool SimpleATInitiator1::transPool private
Definition at line 325 of file SimpleATInitiator1.h.
Referenced by endResponse(), initTransaction(), and run().
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleATInitiator1.h