gem5: HMCController Class Reference
HMCController Class Reference
HMC Controller, in general, is responsible for translating the host protocol (AXI for example) to serial links protocol.
#include <hmc_controller.hh>
Public Member Functions
HMCController (const HMCControllerParams *p)
Public Member Functions inherited from NoncoherentXBar
NoncoherentXBar (const NoncoherentXBarParams *p)
virtual ~NoncoherentXBar ()
Public Member Functions inherited from BaseXBar
virtual ~BaseXBar ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
A function used to return the port associated with this object.
void regStats () override
Callback to set stat parameters.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
virtual void recvRangeChange (PortID master_port_id)
Function called by the port when the crossbar is recieving a range change.
virtual bool recvTimingReq (PacketPtr pkt, PortID slave_port_id)
int rotate_counter ()
Function for rotating the round robin counter.
Private Attributes
int n_master_ports
int rr_counter
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from NoncoherentXBar
virtual bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
void recvReqRetry (PortID master_port_id)
Tick recvAtomicBackdoor (PacketPtr pkt, PortID slave_port_id, MemBackdoorPtr *backdoor=nullptr)
void recvFunctional (PacketPtr pkt, PortID slave_port_id)
Protected Member Functions inherited from BaseXBar
PortID findPort (AddrRange addr_range)
Find which port connected to this crossbar (if any) should be given a packet with this address range.
AddrRangeList getAddrRanges () const
Return the address ranges the crossbar is responsible for.
void calcPacketTiming (PacketPtr pkt, Tick header_delay)
Calculate the timing parameters for the packet.
BaseXBar (const BaseXBarParams *p)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from NoncoherentXBar
std::vector< ReqLayer * > reqLayers
Declare the layers of this crossbar, one vector for requests and one for responses.
std::vector< RespLayer * > respLayers
Protected Attributes inherited from BaseXBar
const Cycles frontendLatency
Cycles of front-end pipeline including the delay to accept the request and to decode the address.
const Cycles forwardLatency
const Cycles responseLatency
const uint32_t width
the width of the xbar in bytes
AddrRangeMap< PortID, 3 > portMap
std::unordered_map< RequestPtr, PortID > routeTo
Remember where request packets came from so that we can route responses to the appropriate port.
AddrRangeList xbarRanges
all contigous ranges seen by this crossbar
AddrRange defaultRange
std::vector< bool > gotAddrRanges
Remember for each of the master ports of the crossbar if we got an address range from the connected slave.
bool gotAllAddrRanges
std::vector< QueuedSlavePort * > slavePorts
The master and slave ports of the crossbar.
std::vector< MasterPort * > masterPorts
PortID defaultPortID
Port that handles requests that don't match any of the interfaces.
const bool useDefaultRange
If true, use address range provided by default device.
Stats::Vector transDist
Stats for transaction distribution and data passing through the crossbar.
Stats::Vector2d pktCount
Stats::Vector2d pktSize
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
HMC Controller, in general, is responsible for translating the host protocol (AXI for example) to serial links protocol.
Plus, it should have large internal buffers to hide the access latency of the cube. It is also inferred from the standard [1] and the literature [2] that serial links share the same address range and packets can travel over any of them, so a load distribution mechanism is required. This model simply queues the incoming transactions (using a Bridge) and schedules them to the serial links using a simple round robin mechanism to balance the load among them. More advanced global scheduling policies and reordering and steering of transactions can be added to this model if required [3]. [1] http://www.hybridmemorycube.org/specification-download/ [2] Low-Power Hybrid Memory Cubes With Link Power Manageme and Two-Level Prefetching (J. Ahn et. al) [3] The Open-Silicon HMC Controller IP http://www.open-silicon.com/open-silicon-ips/hmc/
Definition at line 75 of file hmc_controller.hh.
Constructor & Destructor Documentation
HMCController()
HMCController::HMCController (const HMCControllerParams * p)
Definition at line 6 of file hmc_controller.cc.
Member Function Documentation
recvRangeChange()
void HMCController::recvRangeChange (PortID master_port_id) private virtual
Function called by the port when the crossbar is recieving a range change.
Function called by the port when the crossbar is receiving a range change.
Parameters
master_port_id id of the port that received the change
Reimplemented from BaseXBar.
Definition at line 22 of file hmc_controller.cc.
References BaseXBar::gotAddrRanges, BaseXBar::gotAllAddrRanges, and BaseXBar::recvRangeChange().
recvTimingReq()
bool HMCController::recvTimingReq (PacketPtr pkt, PortID slave_port_id) private virtual
Reimplemented from NoncoherentXBar.
Definition at line 42 of file hmc_controller.cc.
References Packet::cacheResponding(), BaseXBar::calcPacketTiming(), Clocked::clockEdge(), Clocked::clockPeriod(), Packet::cmdString(), Packet::cmdToIndex(), DPRINTF, BaseXBar::forwardLatency, BaseXBar::frontendLatency, Packet::getAddr(), Packet::getSize(), Packet::hasData(), Packet::headerDelay, Packet::isExpressSnoop(), BaseXBar::masterPorts, Port::name(), Packet::needsResponse(), Packet::payloadDelay, BaseXBar::pktCount, BaseXBar::pktSize, Packet::req, NoncoherentXBar::reqLayers, rotate_counter(), BaseXBar::routeTo, BaseXBar::slavePorts, and BaseXBar::transDist.
rotate_counter()
int HMCController::rotate_counter () private
Function for rotating the round robin counter.
Returns
the next value of the counter
Definition at line 33 of file hmc_controller.cc.
References n_master_ports, and rr_counter.
Referenced by recvTimingReq().
Member Data Documentation
n_master_ports
int HMCController::n_master_ports private
Definition at line 92 of file hmc_controller.hh.
Referenced by rotate_counter().
rr_counter
int HMCController::rr_counter private
Definition at line 95 of file hmc_controller.hh.
Referenced by rotate_counter().
The documentation for this class was generated from the following files:
mem/hmc_controller.hh
mem/hmc_controller.cc