gem5: SparcLinux Class Reference
SparcLinux Class Reference
#include <linux.hh>
Classes
struct tgt_stat
struct tgt_sysinfo
Static Public Member Functions
static bool isTtyReq (unsigned req)
static void archClone (uint64_t flags, Process *pp, Process *cp, ThreadContext *ptc, ThreadContext *ctc, uint64_t stack, uint64_t tls)
Static Public Member Functions inherited from Linux
static bool isTtyReq (unsigned req)
Return true for the ioctl codes for which we return ENOTTY without printing a warning, since we know that ENOTTY is the correct thing to return (and not just a sign that we don't recognize the ioctl code.
static int openSpecialFile (std::string path, Process *process, ThreadContext *tc)
static std::string procMeminfo (Process *process, ThreadContext *tc)
static std::string etcPasswd (Process *process, ThreadContext *tc)
static std::string cpuOnline (Process *process, ThreadContext *tc)
Static Public Member Functions inherited from OperatingSystem
static int openSpecialFile (std::string path, Process *process, ThreadContext *tc)
Static Public Attributes
static const ByteOrder byteOrder = BigEndianByteOrder
static const int TGT_SIGHUP = 0x000001
static const int TGT_SIGINT = 0x000002
static const int TGT_SIGQUIT = 0x000003
static const int TGT_SIGILL = 0x000004
static const int TGT_SIGTRAP = 0x000005
static const int TGT_SIGABRT = 0x000006
static const int TGT_SIGIOT = 0x000006
static const int TGT_SIGEMT = 0x000007
static const int TGT_SIGFPE = 0x000008
static const int TGT_SIGKILL = 0x000009
static const int TGT_SIGBUS = 0x00000a
static const int TGT_SIGSEGV = 0x00000b
static const int TGT_SIGSYS = 0x00000c
static const int TGT_SIGPIPE = 0x00000d
static const int TGT_SIGALRM = 0x00000e
static const int TGT_SIGTERM = 0x00000f
static const int TGT_SIGURG = 0x000010
static const int TGT_SIGSTOP = 0x000011
static const int TGT_SIGTSTP = 0x000012
static const int TGT_SIGCONT = 0x000013
static const int TGT_SIGCHLD = 0x000014
static const int TGT_SIGTTIN = 0x000015
static const int TGT_SIGTTOU = 0x000016
static const int TGT_SIGIO = 0x000017
static const int TGT_SIGPOLL = 0x000017
static const int TGT_SIGXCPU = 0x000018
static const int TGT_SIGXFSZ = 0x000019
static const int TGT_SIGVTALRM = 0x00001a
static const int TGT_SIGPROF = 0x00001b
static const int TGT_SIGWINCH = 0x00001c
static const int TGT_SIGLOST = 0x00001d
static const int TGT_SIGPWR = 0x00001d
static const int TGT_SIGUSR1 = 0x00001e
static const int TGT_SIGUSR2 = 0x00001f
static SyscallFlagTransTable openFlagTable []
static const int TGT_O_RDONLY = 0x00000000
O_RDONLY.
static const int TGT_O_WRONLY = 0x00000001
O_WRONLY.
static const int TGT_O_RDWR = 0x00000002
O_RDWR.
static const int TGT_O_NONBLOCK = 0x00004000
O_NONBLOCK.
static const int TGT_O_APPEND = 0x00000008
O_APPEND.
static const int TGT_FASYNC = 0x00000040
FASYNC.
static const int TGT_O_CREAT = 0x00000200
O_CREAT.
static const int TGT_O_TRUNC = 0x00000400
O_TRUNC.
static const int TGT_O_EXCL = 0x00000800
O_EXCL.
static const int TGT_O_NOCTTY = 0x00008000
O_NOCTTY.
static const int TGT_O_DSYNC = 0x00002000
O_DSYNC.
static const int TGT_O_LARGEFILE = 0x00040000
O_LARGEFILE.
static const int TGT_O_DIRECT = 0x00100000
O_DIRECT.
static const int TGT_O_NOATIME = 0x00200000
O_NOATIME.
static const int TGT_O_CLOEXEC = 0x00400000
O_CLOEXEC.
static const int TGT_O_SYNC = 0x00802000
O_SYNC.
static const int TGT_O_PATH = 0x01000000
O_PATH.
static const int TGT_O_DIRECTORY = 000200000
O_DIRECTORY.
static const int TGT_O_NOFOLLOW = 000400000
O_NOFOLLOW.
static const int NUM_OPEN_FLAGS
static const unsigned TGT_MAP_SHARED = 0x00001
static const unsigned TGT_MAP_PRIVATE = 0x00002
static const unsigned TGT_MAP_ANON = 0x00020
static const unsigned TGT_MAP_DENYWRITE = 0x00800
static const unsigned TGT_MAP_EXECUTABLE = 0x01000
static const unsigned TGT_MAP_FILE = 0x00000
static const unsigned TGT_MAP_GROWSDOWN = 0x00200
static const unsigned TGT_MAP_HUGETLB = 0x40000
static const unsigned TGT_MAP_LOCKED = 0x00100
static const unsigned TGT_MAP_NONBLOCK = 0x10000
static const unsigned TGT_MAP_NORESERVE = 0x00040
static const unsigned TGT_MAP_POPULATE = 0x08000
static const unsigned TGT_MAP_STACK = 0x20000
static const unsigned TGT_MAP_ANONYMOUS = 0x00020
static const unsigned TGT_MAP_FIXED = 0x00010
static const unsigned TGT_MAP_INHERIT = 0x00080
static const unsigned NUM_MMAP_FLAGS
static const unsigned TGT_TCGETA = 0x40125401
ioctl() command codes.
static const unsigned TGT_TCSETAW = 0x80125403
static const unsigned TGT_TCGETS = 0x40385408
static const unsigned TGT_FIONREAD = 0x4004667f
static const unsigned TGT_TIOCGETP = 0x40067408
static const unsigned TGT_TIOCSETP = 0x80067409
static const unsigned TGT_TIOCSETN = 0x8006740a
Static Public Attributes inherited from Linux
static const int _SYS_NMLN = 65
Length of strings in struct utsname (plus 1 for null char).
static const int M5_SC_CLK_TCK = 100
Clock ticks per second, for times().
static const unsigned TGT_RLIMIT_CPU = 0
Resource constants for getrlimit().
static const unsigned TGT_RLIMIT_FSIZE = 1
static const unsigned TGT_RLIMIT_DATA = 2
static const unsigned TGT_RLIMIT_STACK = 3
static const unsigned TGT_RLIMIT_CORE = 4
static const unsigned TGT_RLIMIT_RSS = 5
static const unsigned TGT_RLIMIT_NPROC = 6
static const unsigned TGT_RLIMIT_NOFILE = 7
static const unsigned TGT_RLIMIT_MEMLOCK = 8
static const unsigned TGT_RLIMIT_AS = 9
static const unsigned TGT_RLIMIT_LOCKS = 10
static const unsigned TGT_RLIMIT_SIGPENDING = 11
static const unsigned TGT_RLIMIT_MSGQUEUE = 12
static const unsigned TGT_RLIMIT_NICE = 13
static const unsigned TGT_RLIMIT_RTPRIO = 14
static const unsigned TGT_RLIMIT_RTTIME = 15
static const unsigned TGT_RLIM_NLIMITS = 16
static const int TGT_RUSAGE_SELF = 0
For getrusage().
static const int TGT_RUSAGE_CHILDREN = -1
static const int TGT_RUSAGE_BOTH = -2
static const unsigned TGT_FUTEX_WAIT = 0
static const unsigned TGT_FUTEX_WAKE = 1
static const unsigned TGT_FUTEX_REQUEUE = 3
static const unsigned TGT_FUTEX_CMP_REQUEUE = 4
static const unsigned TGT_FUTEX_WAKE_OP = 5
static const unsigned TGT_FUTEX_WAIT_BITSET = 9
static const unsigned TGT_FUTEX_WAKE_BITSET = 10
static const unsigned TGT_EAGAIN = 11
static const unsigned TGT_EWOULDBLOCK = TGT_EAGAIN
static const unsigned TGT_FUTEX_PRIVATE_FLAG = 128
static const unsigned TGT_FUTEX_CLOCK_REALTIME_FLAG = 256
static const unsigned TGT_FUTEX_OP_SET = 0
static const unsigned TGT_FUTEX_OP_ADD = 1
static const unsigned TGT_FUTEX_OP_OR = 2
static const unsigned TGT_FUTEX_OP_ANDN = 3
static const unsigned TGT_FUTEX_OP_XOR = 4
static const unsigned TGT_FUTEX_OP_ARG_SHIFT = 8
static const unsigned TGT_FUTEX_OP_CMP_EQ = 0
static const unsigned TGT_FUTEX_OP_CMP_NE = 1
static const unsigned TGT_FUTEX_OP_CMP_LT = 2
static const unsigned TGT_FUTEX_OP_CMP_LE = 3
static const unsigned TGT_FUTEX_OP_CMP_GT = 4
static const unsigned TGT_FUTEX_OP_CMP_GE = 5
static const int TGT_AT_FDCWD = -100
static const unsigned TGT_MREMAP_MAYMOVE = 0x1
static const unsigned TGT_MREMAP_FIXED = 0x2
static const unsigned TGT_CLONE_VM = 0x00000100
static const unsigned TGT_CLONE_FS = 0x00000200
static const unsigned TGT_CLONE_FILES = 0x00000400
static const unsigned TGT_CLONE_SIGHAND = 0x00000800
static const unsigned TGT_CLONE_PTRACE = 0x00002000
static const unsigned TGT_CLONE_VFORK = 0x00004000
static const unsigned TGT_CLONE_PARENT = 0x00008000
static const unsigned TGT_CLONE_THREAD = 0x00010000
static const unsigned TGT_CLONE_NEWNS = 0x00020000
static const unsigned TGT_CLONE_SYSVSEM = 0x00040000
static const unsigned TGT_CLONE_SETTLS = 0x00080000
static const unsigned TGT_CLONE_PARENT_SETTID = 0x00100000
static const unsigned TGT_CLONE_CHILD_CLEARTID = 0x00200000
static const unsigned TGT_CLONE_DETACHED = 0x00400000
static const unsigned TGT_CLONE_UNTRACED = 0x00800000
static const unsigned TGT_CLONE_CHILD_SETTID = 0x01000000
static const unsigned TGT_CLONE_NEWUTS = 0x04000000
static const unsigned TGT_CLONE_NEWIPC = 0x08000000
static const unsigned TGT_CLONE_NEWUSER = 0x10000000
static const unsigned TGT_CLONE_NEWPID = 0x20000000
static const unsigned TGT_CLONE_NEWNET = 0x40000000
static const unsigned TGT_CLONE_IO = 0x80000000
static const unsigned TGT_WNOHANG = 0x00000001
static const unsigned TGT_WUNTRACED = 0x00000002
static const unsigned TGT_WSTOPPED = TGT_WUNTRACED
static const unsigned TGT_WEXITED = 0x00000004
static const unsigned TGT_WCONTINUED = 0x00000008
static const unsigned TGT_WNOWAIT = 0x01000000
static const unsigned TGT_TCGETS = 0x5401
ioctl() command codes.
static const unsigned TGT_TCGETA = 0x5405
static const unsigned TGT_TCSETAW = 0x5407
static const unsigned TGT_FIONREAD = 0x541B
Static Public Attributes inherited from OperatingSystem
static const int _SYS_NMLN = 65
Length of strings in struct utsname (plus 1 for null char).
Additional Inherited Members
Public Types inherited from Linux
typedef uint64_t size_t
Basic Linux types.
typedef uint64_t off_t
typedef int64_t time_t
typedef int64_t clock_t
typedef uint32_t uid_t
typedef uint32_t gid_t
Public Types inherited from OperatingSystem
typedef void tgt_stat
Stat buffer.
typedef void tgt_stat64
Detailed Description
Definition at line 37 of file linux.hh.
Member Function Documentation
archClone()
static void SparcLinux::archClone (uint64_t flags, Process * pp, Process * cp, ThreadContext * ptc, ThreadContext * ctc, uint64_t stack, uint64_t tls) inline static
Definition at line 190 of file linux.hh.
References SparcISA::ASI_PRIMARY, SparcISA::copyRegs(), SparcISA::MISCREG_ASI, SparcISA::MISCREG_CWP, SparcISA::MISCREG_TL, SparcISA::NumIntArchRegs, SparcISA::NWindows, ThreadContext::readIntReg(), ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ThreadContext::setMiscRegNoEffect(), and SparcISA::StackPointerReg.
isTtyReq()
static bool SparcLinux::isTtyReq (unsigned req) inline static
Definition at line 174 of file linux.hh.
References TGT_TCGETA, TGT_TCGETS, TGT_TCSETAW, TGT_TIOCGETP, TGT_TIOCSETN, and TGT_TIOCSETP.
Member Data Documentation
byteOrder
const ByteOrder SparcLinux::byteOrder = BigEndianByteOrder static
Definition at line 41 of file linux.hh.
NUM_MMAP_FLAGS
const unsigned SparcLinux::NUM_MMAP_FLAGS static
Definition at line 142 of file linux.hh.
NUM_OPEN_FLAGS
const int SparcLinux::NUM_OPEN_FLAGS static
Definition at line 123 of file linux.hh.
openFlagTable
SyscallFlagTransTable SparcLinux::openFlagTable[] static
Definition at line 100 of file linux.hh.
TGT_FASYNC
const int SparcLinux::TGT_FASYNC = 0x00000040 static
FASYNC.
Definition at line 107 of file linux.hh.
TGT_FIONREAD
const unsigned SparcLinux::TGT_FIONREAD = 0x4004667f static
Definition at line 167 of file linux.hh.
TGT_MAP_ANON
const unsigned SparcLinux::TGT_MAP_ANON = 0x00020 static
Definition at line 127 of file linux.hh.
TGT_MAP_ANONYMOUS
const unsigned SparcLinux::TGT_MAP_ANONYMOUS = 0x00020 static
Definition at line 138 of file linux.hh.
TGT_MAP_DENYWRITE
const unsigned SparcLinux::TGT_MAP_DENYWRITE = 0x00800 static
Definition at line 128 of file linux.hh.
TGT_MAP_EXECUTABLE
const unsigned SparcLinux::TGT_MAP_EXECUTABLE = 0x01000 static
Definition at line 129 of file linux.hh.
TGT_MAP_FILE
const unsigned SparcLinux::TGT_MAP_FILE = 0x00000 static
Definition at line 130 of file linux.hh.
TGT_MAP_FIXED
const unsigned SparcLinux::TGT_MAP_FIXED = 0x00010 static
Definition at line 139 of file linux.hh.
TGT_MAP_GROWSDOWN
const unsigned SparcLinux::TGT_MAP_GROWSDOWN = 0x00200 static
Definition at line 131 of file linux.hh.
TGT_MAP_HUGETLB
const unsigned SparcLinux::TGT_MAP_HUGETLB = 0x40000 static
Definition at line 132 of file linux.hh.
TGT_MAP_INHERIT
const unsigned SparcLinux::TGT_MAP_INHERIT = 0x00080 static
Definition at line 140 of file linux.hh.
TGT_MAP_LOCKED
const unsigned SparcLinux::TGT_MAP_LOCKED = 0x00100 static
Definition at line 133 of file linux.hh.
TGT_MAP_NONBLOCK
const unsigned SparcLinux::TGT_MAP_NONBLOCK = 0x10000 static
Definition at line 134 of file linux.hh.
TGT_MAP_NORESERVE
const unsigned SparcLinux::TGT_MAP_NORESERVE = 0x00040 static
Definition at line 135 of file linux.hh.
TGT_MAP_POPULATE
const unsigned SparcLinux::TGT_MAP_POPULATE = 0x08000 static
Definition at line 136 of file linux.hh.
TGT_MAP_PRIVATE
const unsigned SparcLinux::TGT_MAP_PRIVATE = 0x00002 static
Definition at line 126 of file linux.hh.
TGT_MAP_SHARED
const unsigned SparcLinux::TGT_MAP_SHARED = 0x00001 static
Definition at line 125 of file linux.hh.
TGT_MAP_STACK
const unsigned SparcLinux::TGT_MAP_STACK = 0x20000 static
Definition at line 137 of file linux.hh.
TGT_O_APPEND
const int SparcLinux::TGT_O_APPEND = 0x00000008 static
O_APPEND.
Definition at line 106 of file linux.hh.
TGT_O_CLOEXEC
const int SparcLinux::TGT_O_CLOEXEC = 0x00400000 static
O_CLOEXEC.
Definition at line 116 of file linux.hh.
TGT_O_CREAT
const int SparcLinux::TGT_O_CREAT = 0x00000200 static
O_CREAT.
Definition at line 108 of file linux.hh.
TGT_O_DIRECT
const int SparcLinux::TGT_O_DIRECT = 0x00100000 static
O_DIRECT.
Definition at line 114 of file linux.hh.
TGT_O_DIRECTORY
const int SparcLinux::TGT_O_DIRECTORY = 000200000 static
O_DIRECTORY.
Definition at line 120 of file linux.hh.
TGT_O_DSYNC
const int SparcLinux::TGT_O_DSYNC = 0x00002000 static
O_DSYNC.
Definition at line 112 of file linux.hh.
TGT_O_EXCL
const int SparcLinux::TGT_O_EXCL = 0x00000800 static
O_EXCL.
Definition at line 110 of file linux.hh.
TGT_O_LARGEFILE
const int SparcLinux::TGT_O_LARGEFILE = 0x00040000 static
O_LARGEFILE.
Definition at line 113 of file linux.hh.
TGT_O_NOATIME
const int SparcLinux::TGT_O_NOATIME = 0x00200000 static
O_NOATIME.
Definition at line 115 of file linux.hh.
TGT_O_NOCTTY
const int SparcLinux::TGT_O_NOCTTY = 0x00008000 static
O_NOCTTY.
Definition at line 111 of file linux.hh.
TGT_O_NOFOLLOW
const int SparcLinux::TGT_O_NOFOLLOW = 000400000 static
O_NOFOLLOW.
Definition at line 121 of file linux.hh.
TGT_O_NONBLOCK
const int SparcLinux::TGT_O_NONBLOCK = 0x00004000 static
O_NONBLOCK.
Definition at line 105 of file linux.hh.
TGT_O_PATH
const int SparcLinux::TGT_O_PATH = 0x01000000 static
O_PATH.
Definition at line 118 of file linux.hh.
TGT_O_RDONLY
const int SparcLinux::TGT_O_RDONLY = 0x00000000 static
O_RDONLY.
Definition at line 102 of file linux.hh.
TGT_O_RDWR
const int SparcLinux::TGT_O_RDWR = 0x00000002 static
O_RDWR.
Definition at line 104 of file linux.hh.
TGT_O_SYNC
const int SparcLinux::TGT_O_SYNC = 0x00802000 static
O_SYNC.
Definition at line 117 of file linux.hh.
TGT_O_TRUNC
const int SparcLinux::TGT_O_TRUNC = 0x00000400 static
O_TRUNC.
Definition at line 109 of file linux.hh.
TGT_O_WRONLY
const int SparcLinux::TGT_O_WRONLY = 0x00000001 static
O_WRONLY.
Definition at line 103 of file linux.hh.
TGT_SIGABRT
const int SparcLinux::TGT_SIGABRT = 0x000006 static
Definition at line 70 of file linux.hh.
TGT_SIGALRM
const int SparcLinux::TGT_SIGALRM = 0x00000e static
Definition at line 79 of file linux.hh.
TGT_SIGBUS
const int SparcLinux::TGT_SIGBUS = 0x00000a static
Definition at line 75 of file linux.hh.
TGT_SIGCHLD
const int SparcLinux::TGT_SIGCHLD = 0x000014 static
Definition at line 85 of file linux.hh.
TGT_SIGCONT
const int SparcLinux::TGT_SIGCONT = 0x000013 static
Definition at line 84 of file linux.hh.
TGT_SIGEMT
const int SparcLinux::TGT_SIGEMT = 0x000007 static
Definition at line 72 of file linux.hh.
TGT_SIGFPE
const int SparcLinux::TGT_SIGFPE = 0x000008 static
Definition at line 73 of file linux.hh.
TGT_SIGHUP
const int SparcLinux::TGT_SIGHUP = 0x000001 static
Definition at line 65 of file linux.hh.
TGT_SIGILL
const int SparcLinux::TGT_SIGILL = 0x000004 static
Definition at line 68 of file linux.hh.
TGT_SIGINT
const int SparcLinux::TGT_SIGINT = 0x000002 static
Definition at line 66 of file linux.hh.
TGT_SIGIO
const int SparcLinux::TGT_SIGIO = 0x000017 static
Definition at line 88 of file linux.hh.
TGT_SIGIOT
const int SparcLinux::TGT_SIGIOT = 0x000006 static
Definition at line 71 of file linux.hh.
TGT_SIGKILL
const int SparcLinux::TGT_SIGKILL = 0x000009 static
Definition at line 74 of file linux.hh.
TGT_SIGLOST
const int SparcLinux::TGT_SIGLOST = 0x00001d static
Definition at line 95 of file linux.hh.
TGT_SIGPIPE
const int SparcLinux::TGT_SIGPIPE = 0x00000d static
Definition at line 78 of file linux.hh.
TGT_SIGPOLL
const int SparcLinux::TGT_SIGPOLL = 0x000017 static
Definition at line 89 of file linux.hh.
TGT_SIGPROF
const int SparcLinux::TGT_SIGPROF = 0x00001b static
Definition at line 93 of file linux.hh.
TGT_SIGPWR
const int SparcLinux::TGT_SIGPWR = 0x00001d static
Definition at line 96 of file linux.hh.
TGT_SIGQUIT
const int SparcLinux::TGT_SIGQUIT = 0x000003 static
Definition at line 67 of file linux.hh.
TGT_SIGSEGV
const int SparcLinux::TGT_SIGSEGV = 0x00000b static
Definition at line 76 of file linux.hh.
TGT_SIGSTOP
const int SparcLinux::TGT_SIGSTOP = 0x000011 static
Definition at line 82 of file linux.hh.
TGT_SIGSYS
const int SparcLinux::TGT_SIGSYS = 0x00000c static
Definition at line 77 of file linux.hh.
TGT_SIGTERM
const int SparcLinux::TGT_SIGTERM = 0x00000f static
Definition at line 80 of file linux.hh.
TGT_SIGTRAP
const int SparcLinux::TGT_SIGTRAP = 0x000005 static
Definition at line 69 of file linux.hh.
TGT_SIGTSTP
const int SparcLinux::TGT_SIGTSTP = 0x000012 static
Definition at line 83 of file linux.hh.
TGT_SIGTTIN
const int SparcLinux::TGT_SIGTTIN = 0x000015 static
Definition at line 86 of file linux.hh.
TGT_SIGTTOU
const int SparcLinux::TGT_SIGTTOU = 0x000016 static
Definition at line 87 of file linux.hh.
TGT_SIGURG
const int SparcLinux::TGT_SIGURG = 0x000010 static
Definition at line 81 of file linux.hh.
TGT_SIGUSR1
const int SparcLinux::TGT_SIGUSR1 = 0x00001e static
Definition at line 97 of file linux.hh.
TGT_SIGUSR2
const int SparcLinux::TGT_SIGUSR2 = 0x00001f static
Definition at line 98 of file linux.hh.
TGT_SIGVTALRM
const int SparcLinux::TGT_SIGVTALRM = 0x00001a static
Definition at line 92 of file linux.hh.
TGT_SIGWINCH
const int SparcLinux::TGT_SIGWINCH = 0x00001c static
Definition at line 94 of file linux.hh.
TGT_SIGXCPU
const int SparcLinux::TGT_SIGXCPU = 0x000018 static
Definition at line 90 of file linux.hh.
TGT_SIGXFSZ
const int SparcLinux::TGT_SIGXFSZ = 0x000019 static
Definition at line 91 of file linux.hh.
TGT_TCGETA
const unsigned SparcLinux::TGT_TCGETA = 0x40125401 static
ioctl() command codes.
These were calculated using the SPARC Linux headers on an x86 machine and thus may not be correct. It would be good to verify/update these values on an actual SPARC Linux machine.
Definition at line 164 of file linux.hh.
Referenced by isTtyReq().
TGT_TCGETS
const unsigned SparcLinux::TGT_TCGETS = 0x40385408 static
Definition at line 166 of file linux.hh.
Referenced by isTtyReq().
TGT_TCSETAW
const unsigned SparcLinux::TGT_TCSETAW = 0x80125403 static
Definition at line 165 of file linux.hh.
Referenced by isTtyReq().
TGT_TIOCGETP
const unsigned SparcLinux::TGT_TIOCGETP = 0x40067408 static
Definition at line 168 of file linux.hh.
Referenced by isTtyReq().
TGT_TIOCSETN
const unsigned SparcLinux::TGT_TIOCSETN = 0x8006740a static
Definition at line 170 of file linux.hh.
Referenced by isTtyReq().
TGT_TIOCSETP
const unsigned SparcLinux::TGT_TIOCSETP = 0x80067409 static
Definition at line 169 of file linux.hh.
Referenced by isTtyReq().
The documentation for this class was generated from the following file:
arch/sparc/linux/linux.hh