gem5: TimingResponseProtocol Class Reference
TimingResponseProtocol Class Reference abstract
#include <timing.hh>
Protected Member Functions
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
virtual bool recvTimingReq (PacketPtr pkt)=0
Receive a timing request from the peer.
virtual bool tryTiming (PacketPtr pkt)=0
Availability request from the peer.
virtual bool recvTimingSnoopResp (PacketPtr pkt)=0
Receive a timing snoop response from the peer.
virtual void recvRespRetry ()=0
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Friends
class TimingRequestProtocol
Detailed Description
Definition at line 126 of file timing.hh.
Member Function Documentation
recvRespRetry()
virtual void TimingResponseProtocol::recvRespRetry () protected pure virtual
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Implemented in X86ISA::GpuTLB::CpuSidePort, CommMonitor::MonitorSlavePort, Bridge::BridgeSlavePort, AddrMapper::MapperSlavePort, SerialLink::SerialLinkSlavePort, MemCheckerMonitor::MonitorSlavePort, LdsState::CuSidePort, TLBCoalescer::CpuSidePort, SimpleCache::CPUSidePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, SimpleMemobj::CPUSidePort, SimpleMemory::MemoryPort, DRAMSim2::MemoryPort, StubSlavePort, and QueuedSlavePort.
Referenced by TimingRequestProtocol::sendRetryResp().
recvTimingReq()
virtual bool TimingResponseProtocol::recvTimingReq (PacketPtr pkt) protected pure virtual
Receive a timing request from the peer.
Implemented in BaseCache::CpuSidePort, X86ISA::GpuTLB::CpuSidePort, CommMonitor::MonitorSlavePort, Bridge::BridgeSlavePort, SerialLink::SerialLinkSlavePort, AddrMapper::MapperSlavePort, MemCheckerMonitor::MonitorSlavePort, TLBCoalescer::CpuSidePort, LdsState::CuSidePort, SMMUATSSlavePort, SimpleCache::CPUSidePort, RubyPort::PioSlavePort, SimpleMemobj::CPUSidePort, DRAMCtrl::MemoryPort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, MemDelay::SlavePort, NoncoherentXBar::NoncoherentXBarSlavePort, QoS::MemSinkCtrl::MemoryPort, SimpleMemory::MemoryPort, RubyPort::MemSlavePort, SMMUSlavePort, DRAMSim2::MemoryPort, SimpleTimingPort, and StubSlavePort.
Referenced by TimingRequestProtocol::sendReq().
recvTimingSnoopResp()
virtual bool TimingResponseProtocol::recvTimingSnoopResp (PacketPtr pkt) protected pure virtual
Receive a timing snoop response from the peer.
Implemented in SlavePort, BaseCache::CpuSidePort, CommMonitor::MonitorSlavePort, AddrMapper::MapperSlavePort, MemCheckerMonitor::MonitorSlavePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, CoherentXBar::CoherentXBarSlavePort, MemDelay::SlavePort, and StubSlavePort.
Referenced by TimingRequestProtocol::sendSnoopResp().
sendResp()
bool TimingResponseProtocol::sendResp (TimingRequestProtocol * peer, PacketPtr pkt) protected
Attempt to send a timing response to the peer by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvRespRetry at which point it can re-issue a sendTimingResp.
Parameters
peer Peer to send the packet to.
pkt Packet to send.
Returns
If the send was succesful or not.
Definition at line 81 of file timing.cc.
References Packet::isResponse(), and TimingRequestProtocol::recvTimingResp().
Referenced by SlavePort::sendTimingResp().
sendRetryReq()
void TimingResponseProtocol::sendRetryReq (TimingRequestProtocol * peer) protected
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
Definition at line 96 of file timing.cc.
References TimingRequestProtocol::recvReqRetry().
Referenced by SlavePort::sendRetryReq().
sendRetrySnoopResp()
void TimingResponseProtocol::sendRetrySnoopResp (TimingRequestProtocol * peer) protected
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Definition at line 102 of file timing.cc.
References TimingRequestProtocol::recvRetrySnoopResp().
Referenced by SlavePort::sendRetrySnoopResp().
sendSnoopReq()
void TimingResponseProtocol::sendSnoopReq (TimingRequestProtocol * peer, PacketPtr pkt) protected
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
Snoop requests always succeed and hence no return value is needed.
Parameters
peer Peer to send the packet to.
pkt Packet to send.
Definition at line 88 of file timing.cc.
References Packet::isRequest(), and TimingRequestProtocol::recvTimingSnoopReq().
Referenced by SlavePort::sendTimingSnoopReq().
tryTiming()
virtual bool TimingResponseProtocol::tryTiming (PacketPtr pkt) protected pure virtual
Availability request from the peer.
Implemented in SlavePort, BaseCache::CpuSidePort, CommMonitor::MonitorSlavePort, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort, and MemDelay::SlavePort.
Referenced by TimingRequestProtocol::trySend().
Friends And Related Function Documentation
TimingRequestProtocol
friend class TimingRequestProtocol friend
Definition at line 128 of file timing.hh.
The documentation for this class was generated from the following files:
mem/protocol/timing.hh
mem/protocol/timing.cc