gem5: tlm_utils::convenience_socket_base Class Reference
tlm_utils::convenience_socket_base Class Reference abstract
#include <convenience_socket_bases.h>
Public Member Functions
void display_warning (const char *msg) const
void display_error (const char *msg) const
Protected Member Functions
virtual ~convenience_socket_base ()
Private Member Functions
virtual const char * get_report_type () const =0
virtual const sc_core::sc_object * get_socket () const =0
Detailed Description
Definition at line 33 of file convenience_socket_bases.h.
Constructor & Destructor Documentation
~convenience_socket_base()
virtual tlm_utils::convenience_socket_base::~convenience_socket_base () inline protected virtual
Definition at line 40 of file convenience_socket_bases.h.
Member Function Documentation
display_error()
void tlm_utils::convenience_socket_base::display_error (const char * msg) const
Definition at line 40 of file convenience_socket_bases.cc.
References get_report_type(), get_socket(), sc_core::sc_object::name(), ArmISA::s, and SC_REPORT_ERROR.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::bind(), tlm_utils::simple_socket_base::elaboration_check(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::get_base_interface(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_base_interface(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::size(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::size().
display_warning()
void tlm_utils::convenience_socket_base::display_warning (const char * msg) const
Definition at line 32 of file convenience_socket_bases.cc.
References get_report_type(), get_socket(), sc_core::sc_object::name(), ArmISA::s, and SC_REPORT_WARNING.
Referenced by tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::bind(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::bind(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_b_transport(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_get_direct_mem_ptr(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::register_invalidate_direct_mem_ptr(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::register_nb_transport_bw(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_nb_transport_fw(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_transport_dbg(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::size(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::size().
get_report_type()
virtual const char* tlm_utils::convenience_socket_base::get_report_type () const private pure virtual
Implemented in tlm_utils::multi_socket_base, tlm_utils::passthrough_socket_base, and tlm_utils::simple_socket_base.
Referenced by display_error(), and display_warning().
get_socket()
virtual const sc_core::sc_object* tlm_utils::convenience_socket_base::get_socket () const private pure virtual
Implemented in tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_tagged_b< SimpleBusLT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< SimpleBusAT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_target_socket_b< sc_gem5::TlmToGem5Bridge< BITWIDTH >, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_b< SimpleATTarget2, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_gp2ext, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleATTarget1, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< ExplicitLTTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_ext2gp, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_target_socket_b< ExplicitATTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleLTTarget_ext, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_target_base< 32, tlm::tlm_base_protocol_types, 0, sc_core::SC_ONE_OR_MORE_BOUND >, tlm_utils::multi_init_base< BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_init_base< 32, tlm::tlm_base_protocol_types, 0, sc_core::SC_ONE_OR_MORE_BOUND >, tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_initiator_socket_tagged_b< SimpleBusLT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_tagged_b< SimpleBusAT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::passthrough_target_socket_b< SimpleLTTarget2, 32, tlm::tlm_base_protocol_types >, tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >, tlm_utils::simple_initiator_socket_b< SimpleLTInitiator3_dmi, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< adapt_ext2gp, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< SimpleLTInitiator_ext, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_initiator_socket_b< SimpleLTInitiator2_dmi, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< SimpleATInitiator1, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< SimpleLTInitiator2, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< sc_gem5::Gem5ToTlmBridge< BITWIDTH >, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< SimpleLTInitiator3, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< adapt_gp2ext, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_initiator_socket_b< SimpleATInitiator2, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_initiator_socket_b< CoreDecouplingLTInitiator, 32, tlm::tlm_base_protocol_types >, and tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >.
Referenced by display_error(), and display_warning().
The documentation for this class was generated from the following files:
systemc/ext/tlm_utils/convenience_socket_bases.h
systemc/tlm_utils/convenience_socket_bases.cc