gem5: MultiperspectivePerceptron Class Reference
MultiperspectivePerceptron Class Reference abstract
#include <multiperspective_perceptron.hh>
Classes
class ACYCLIC
class BIAS
class BLURRYPATH
struct FilterEntry
Entry of the branch filter.
class GHIST
Available features.
class GHISTMODPATH
class GHISTPATH
struct HistorySpec
Base class to implement the predictor tables.
class IMLI
class LOCAL
class LocalHistories
Local history entries, each enty contains the history of directions taken by a given branch.
class MODHIST
class MODPATH
class MPPBranchInfo
Branch information data.
class PATH
class RECENCY
class RECENCYPOS
class SGHISTPATH
struct ThreadData
History data is kept for each thread.
Public Member Functions
MultiperspectivePerceptron (const MultiperspectivePerceptronParams *params)
void setExtraBits (int bits)
Sets the starting number of storage bits to compute the number of table entries.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void uncondBranch (ThreadID tid, Addr pc, void *&bp_history) override
void squash (ThreadID tid, void *bp_history) override
bool lookup (ThreadID tid, Addr instPC, void *&bp_history) override
Looks up a given PC in the BP to see if it is taken or not taken.
void update (ThreadID tid, Addr instPC, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst, Addr corrTarget=MaxAddr) override
Updates the BP with taken/not taken information.
void btbUpdate (ThreadID tid, Addr branch_addr, void *&bp_history) override
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Public Member Functions inherited from BPredUnit
BPredUnit (const Params *p)
void regStats () override
Registers statistics.
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void insertModhistSpec (int p1, int p2)
Auxiliary function for MODHIST and GHISTMODPATH features.
void insertModpathSpec (int p1, int p2)
Auxiliary function for MODPATH and GHISTMODPATH features.
int insert (std::vector< int > &v, int x)
Auxiliary function used by insertModhistSpec and insertModpathSpec.
void computeBits (int num_filter_entries, int nlocal_histories, int local_history_length, bool ignore_path_size)
Computes the size in bits of the structures needed to keep track of the history and the predictor tables and assigns the sizes of those tables that did not had their size specified.
virtual void createSpecs ()=0
Creates the tables of the predictor.
unsigned int getIndex (ThreadID tid, const MPPBranchInfo &bi, const HistorySpec &spec, int index) const
Get the position index of a predictor table.
void findBest (ThreadID tid, std::vector< int > &best_preds) const
Finds the best subset of features to use in case of a low-confidence branch, returns the result as an ordered vector of the indices to the predictor tables.
int computeOutput (ThreadID tid, MPPBranchInfo &bi)
Computes the output of the predictor for a given branch and the resulting best value in case the prediction has low confidence.
void train (ThreadID tid, MPPBranchInfo &bi, bool taken)
Trains the branch predictor with the given branch and direction.
void satIncDec (bool taken, bool &sign, int &c, int max_weight) const
Auxiliary function to increase a table counter depending on the direction of the branch.
void addSpec (HistorySpec *spec)
Add a table spec to the prefetcher.
Protected Member Functions inherited from BPredUnit
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
const int blockSize
Predictor parameters.
const int pcshift
const int threshold
const int bias0
const int bias1
const int biasmostly0
const int biasmostly1
const int nbest
const int tunebits
const int hshift
const unsigned long long int imli_mask1
const unsigned long long int imli_mask4
const unsigned long long int recencypos_mask
const double fudge
const int n_sign_bits
const int pcbit
const int decay
const unsigned int record_mask
const bool hash_taken
const bool tuneonly
const int extra_rounds
const int speed
const int budgetbits
const bool speculative_update
std::vector< ThreadData * > threadData
std::vector< HistorySpec * > specs
Predictor tables.
std::vector< int > table_sizes
bool doing_local
runtime values and data used to count the size in bits
bool doing_recency
int assoc
int ghist_length
int modghist_length
int path_length
int thresholdCounter
int theta
int extrabits
std::vector< int > imli_counter_bits
std::vector< int > modhist_indices
std::vector< int > modhist_lengths
std::vector< int > modpath_indices
std::vector< int > modpath_lengths
std::vector< std::vector< int > > blurrypath_bits
std::vector< std::vector< std::vector< bool > > > acyclic_bits
Protected Attributes inherited from BPredUnit
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static int xlat []
Transfer function for 6-width tables.
static int xlat4 []
Transfer function for 5-width tables.
Additional Inherited Members
Public Types inherited from BPredUnit
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 48 of file multiperspective_perceptron.hh.
Constructor & Destructor Documentation
MultiperspectivePerceptron()
MultiperspectivePerceptron::MultiperspectivePerceptron (const MultiperspectivePerceptronParams * params)
Definition at line 113 of file multiperspective_perceptron.cc.
References fatal_if, and speculative_update.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
Member Function Documentation
addSpec()
void MultiperspectivePerceptron::addSpec (HistorySpec * spec) inline protected
Add a table spec to the prefetcher.
Definition at line 476 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron64KB::createSpecs(), MultiperspectivePerceptron8KB::createSpecs(), MultiperspectivePerceptronTAGE8KB::createSpecs(), and MultiperspectivePerceptronTAGE64KB::createSpecs().
btbUpdate()
void MultiperspectivePerceptron::btbUpdate (ThreadID tid, Addr instPC, void *& bp_history) override virtual
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Parameters
inst_PC The PC to look up the local predictor.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Implements BPredUnit.
Definition at line 810 of file multiperspective_perceptron.cc.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
computeBits()
void MultiperspectivePerceptron::computeBits (int num_filter_entries, int nlocal_histories, int local_history_length, bool ignore_path_size) protected
Computes the size in bits of the structures needed to keep track of the history and the predictor tables and assigns the sizes of those tables that did not had their size specified.
Parameters
num_filter_entries number of entries of the filter
nlocal_histories number of local history entries
local_history_length size of each local history entry
ignore_path_size ignore the path length storage
Definition at line 172 of file multiperspective_perceptron.cc.
References acyclic_bits, assoc, blurrypath_bits, budgetbits, doing_local, doing_recency, DPRINTF, extrabits, ghist_length, ArmISA::i, imli_counter_bits, ArmISA::len, modhist_lengths, modpath_lengths, n_sign_bits, path_length, specs, table_sizes, threshold, and tunebits.
Referenced by init(), and insert().
computeOutput()
int MultiperspectivePerceptron::computeOutput (ThreadID tid, MPPBranchInfo & bi) protected
Computes the output of the predictor for a given branch and the resulting best value in case the prediction has low confidence.
Parameters
tid Thread ID of the branch
bi branch informaiton data
Returns
resulting sum for low-confidence branch
Definition at line 303 of file multiperspective_perceptron.cc.
References bias0, bias1, biasmostly0, biasmostly1, MultiperspectivePerceptron::HistorySpec::coeff, findBest(), fudge, MultiperspectivePerceptron::MPPBranchInfo::getHPC(), getIndex(), MultiperspectivePerceptron::MPPBranchInfo::getPC(), ArmISA::i, ArmISA::j, n_sign_bits, nbest, specs, threadData, threshold, X86ISA::val, MultiperspectivePerceptron::HistorySpec::width, xlat, xlat4, and MultiperspectivePerceptron::MPPBranchInfo::yout.
Referenced by insert(), and lookup().
createSpecs()
virtual void MultiperspectivePerceptron::createSpecs () protected pure virtual
Creates the tables of the predictor.
Implemented in MultiperspectivePerceptronTAGE64KB, MultiperspectivePerceptronTAGE8KB, MultiperspectivePerceptron64KB, and MultiperspectivePerceptron8KB.
Referenced by init(), and insert().
findBest()
void MultiperspectivePerceptron::findBest (ThreadID tid, std::vector< int > & best_preds) const protected
Finds the best subset of features to use in case of a low-confidence branch, returns the result as an ordered vector of the indices to the predictor tables.
Parameters
tid Thread ID of the branch
vector to write the ordered list of indices of the best tables
Definition at line 246 of file multiperspective_perceptron.cc.
References ArmISA::i, MipsISA::index, nbest, operator<(), threadData, and threshold.
Referenced by computeOutput(), and insert().
getIndex()
unsigned int MultiperspectivePerceptron::getIndex (ThreadID tid, const MPPBranchInfo & bi, const HistorySpec & spec, int index) const protected
Get the position index of a predictor table.
Parameters
tid Thread ID of the branch
bi branch informaiton data
spec predictor table
index integer index of the predictor table
Returns
index to access the predictor table
Definition at line 272 of file multiperspective_perceptron.cc.
References doing_recency, MipsISA::g, MultiperspectivePerceptron::HistorySpec::getHash(), MultiperspectivePerceptron::MPPBranchInfo::getHPC(), MultiperspectivePerceptron::MPPBranchInfo::getPC(), MultiperspectivePerceptron::MPPBranchInfo::getPC2(), MultiperspectivePerceptron::RECENCYPOS::hash(), hshift, imli_mask1, imli_mask4, MipsISA::index, recencypos_mask, table_sizes, and threadData.
Referenced by computeOutput(), insert(), and train().
init()
void MultiperspectivePerceptron::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Reimplemented in MultiperspectivePerceptronTAGE.
Definition at line 140 of file multiperspective_perceptron.cc.
References acyclic_bits, assoc, blockSize, blurrypath_bits, computeBits(), createSpecs(), ghist_length, ArmISA::i, modhist_indices, modhist_lengths, modpath_indices, modpath_lengths, n_sign_bits, MipsISA::p, SimObject::params(), path_length, specs, table_sizes, and threadData.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash(), and MultiperspectivePerceptronTAGE::init().
insert()
int MultiperspectivePerceptron::insert (std::vector< int > & v, int x) inline protected
Auxiliary function used by insertModhistSpec and insertModpathSpec.
Definition at line 401 of file multiperspective_perceptron.hh.
References PowerISA::bi, ArmISA::c, computeBits(), computeOutput(), createSpecs(), findBest(), getIndex(), ArmISA::i, MipsISA::index, satIncDec(), and train().
Referenced by insertModhistSpec(), and insertModpathSpec().
insertModhistSpec()
void MultiperspectivePerceptron::insertModhistSpec (int p1, int p2) inline protected
Auxiliary function for MODHIST and GHISTMODPATH features.
Definition at line 373 of file multiperspective_perceptron.hh.
References insert(), and ArmISA::j.
insertModpathSpec()
void MultiperspectivePerceptron::insertModpathSpec (int p1, int p2) inline protected
Auxiliary function for MODPATH and GHISTMODPATH features.
Definition at line 387 of file multiperspective_perceptron.hh.
References insert(), and ArmISA::j.
lookup()
bool MultiperspectivePerceptron::lookup (ThreadID tid, Addr instPC, void *& bp_history) override virtual
Looks up a given PC in the BP to see if it is taken or not taken.
Parameters
inst_PC The PC to look up.
bp_history Pointer that will be set to an object that has the branch predictor state associated with the lookup.
Returns
Whether the branch is taken or not taken.
Implements BPredUnit.
Reimplemented in MultiperspectivePerceptronTAGE.
Definition at line 567 of file multiperspective_perceptron.cc.
References MultiperspectivePerceptron::FilterEntry::alwaysNotTakenSoFar(), MultiperspectivePerceptron::FilterEntry::alwaysTakenSoFar(), PowerISA::bi, computeOutput(), ArmISA::f, MultiperspectivePerceptron::MPPBranchInfo::filtered, MultiperspectivePerceptron::MPPBranchInfo::getHashFilter(), MultiperspectivePerceptron::FilterEntry::neverSeen(), pcshift, MultiperspectivePerceptron::MPPBranchInfo::prediction, threadData, threshold, and MultiperspectivePerceptron::MPPBranchInfo::yout.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
satIncDec()
void MultiperspectivePerceptron::satIncDec (bool taken, bool & sign, int & c, int max_weight) const protected
Auxiliary function to increase a table counter depending on the direction of the branch.
Parameters
taken whether the branch was taken
sign current sign of the table
c current value of the table
max_weight maximum value of the counter
Definition at line 366 of file multiperspective_perceptron.cc.
Referenced by insert(), and train().
setExtraBits()
void MultiperspectivePerceptron::setExtraBits (int bits)
Sets the starting number of storage bits to compute the number of table entries.
Parameters
bits number of bits used
Definition at line 134 of file multiperspective_perceptron.cc.
References bits(), and extrabits.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash(), and MultiperspectivePerceptronTAGE::init().
squash()
void MultiperspectivePerceptron::squash (ThreadID tid, void * bp_history) override virtual
Parameters
bp_history Pointer to the history object. The predictor will need to update any state and delete the object.
Implements BPredUnit.
Reimplemented in MultiperspectivePerceptronTAGE.
Definition at line 816 of file multiperspective_perceptron.cc.
References PowerISA::bi.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
train()
void MultiperspectivePerceptron::train (ThreadID tid, MPPBranchInfo & bi, bool taken) protected
Trains the branch predictor with the given branch and direction.
Parameters
tid Thread ID of the branch
bi branch informaiton data
taken whether the branch was taken
Definition at line 403 of file multiperspective_perceptron.cc.
References MultiperspectivePerceptron::HistorySpec::coeff, extra_rounds, MultiperspectivePerceptron::MPPBranchInfo::getHPC(), getIndex(), ArmISA::i, ArmISA::j, n_sign_bits, Random::random(), random_mt, satIncDec(), specs, speed, theta, threadData, threshold, thresholdCounter, tunebits, tuneonly, MultiperspectivePerceptron::HistorySpec::width, xlat, xlat4, and MultiperspectivePerceptron::MPPBranchInfo::yout.
Referenced by insert(), and update().
uncondBranch()
void MultiperspectivePerceptron::uncondBranch (ThreadID tid, Addr pc, void *& bp_history) override virtual
Implements BPredUnit.
Reimplemented in MultiperspectivePerceptronTAGE.
Definition at line 544 of file multiperspective_perceptron.cc.
References PowerISA::bi, blockSize, ghist_length, ArmISA::i, path_length, pcbit, pcshift, and threadData.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
update()
void MultiperspectivePerceptron::update (ThreadID tid, Addr instPC, bool taken, void * bp_history, bool squashed, const StaticInstPtr & inst, Addr corrTarget = MaxAddr) override virtual
Updates the BP with taken/not taken information.
Parameters
inst_PC The branch's PC that will be updated.
taken Whether the branch was taken or not taken.
bp_history Pointer to the branch predictor state that is associated with the branch lookup that is being updated.
squashed Set to true when this function is called during a squash operation.
inst Static instruction information
corrTarget The resolved target of the branch (only needed for squashed branches)
Todo:
Make this update flexible enough to handle a global predictor.
Implements BPredUnit.
Reimplemented in MultiperspectivePerceptronTAGE.
Definition at line 609 of file multiperspective_perceptron.cc.
References ArmISA::a, MultiperspectivePerceptron::FilterEntry::alwaysNotTakenSoFar(), MultiperspectivePerceptron::FilterEntry::alwaysTakenSoFar(), assoc, PowerISA::bi, blockSize, decay, doing_recency, ArmISA::f, MultiperspectivePerceptron::MPPBranchInfo::filtered, MultiperspectivePerceptron::MPPBranchInfo::getHashFilter(), MultiperspectivePerceptron::MPPBranchInfo::getHPC(), MultiperspectivePerceptron::MPPBranchInfo::getPC(), MultiperspectivePerceptron::MPPBranchInfo::getPC2(), ghist_length, hash_taken, ArmISA::i, MultiperspectivePerceptron::MPPBranchInfo::isUnconditional(), ArmISA::j, MaxAddr, modhist_indices, modhist_lengths, modpath_indices, modpath_lengths, path_length, pcbit, Random::random(), random_mt, RECORD_FILTERED_ACYCLIC, RECORD_FILTERED_BLURRY, RECORD_FILTERED_GHIST, RECORD_FILTERED_IMLI, RECORD_FILTERED_LOCAL, RECORD_FILTERED_MOD, RECORD_FILTERED_PATH, RECORD_FILTERED_RECENCY, record_mask, MultiperspectivePerceptron::FilterEntry::seenTaken, MultiperspectivePerceptron::FilterEntry::seenUntaken, threadData, train(), and ArmISA::z.
Referenced by MultiperspectivePerceptron::SGHISTPATH::getHash().
Member Data Documentation
acyclic_bits
std::vector<std::vector<std::vector<bool> > > MultiperspectivePerceptron::acyclic_bits protected
Definition at line 370 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), and MultiperspectivePerceptron::ThreadData::ThreadData().
assoc
int MultiperspectivePerceptron::assoc protected
Definition at line 357 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), MultiperspectivePerceptron::ThreadData::insertRecency(), update(), and MultiperspectivePerceptronTAGE::updateHistories().
bias0
const int MultiperspectivePerceptron::bias0 protected
Definition at line 260 of file multiperspective_perceptron.hh.
Referenced by computeOutput().
bias1
const int MultiperspectivePerceptron::bias1 protected
Definition at line 261 of file multiperspective_perceptron.hh.
Referenced by computeOutput().
biasmostly0
const int MultiperspectivePerceptron::biasmostly0 protected
Definition at line 262 of file multiperspective_perceptron.hh.
Referenced by computeOutput().
biasmostly1
const int MultiperspectivePerceptron::biasmostly1 protected
Definition at line 263 of file multiperspective_perceptron.hh.
Referenced by computeOutput().
blockSize
const int MultiperspectivePerceptron::blockSize protected
Predictor parameters.
Definition at line 257 of file multiperspective_perceptron.hh.
Referenced by init(), uncondBranch(), and update().
blurrypath_bits
std::vector<std::vector<int> > MultiperspectivePerceptron::blurrypath_bits protected
Definition at line 369 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), and MultiperspectivePerceptron::ThreadData::ThreadData().
budgetbits
const int MultiperspectivePerceptron::budgetbits protected
Definition at line 279 of file multiperspective_perceptron.hh.
Referenced by computeBits().
decay
const int MultiperspectivePerceptron::decay protected
Definition at line 273 of file multiperspective_perceptron.hh.
Referenced by update().
doing_local
bool MultiperspectivePerceptron::doing_local protected
runtime values and data used to count the size in bits
Definition at line 355 of file multiperspective_perceptron.hh.
Referenced by computeBits().
doing_recency
bool MultiperspectivePerceptron::doing_recency protected
Definition at line 356 of file multiperspective_perceptron.hh.
Referenced by computeBits(), getIndex(), and update().
extra_rounds
const int MultiperspectivePerceptron::extra_rounds protected
Definition at line 277 of file multiperspective_perceptron.hh.
Referenced by train().
extrabits
int MultiperspectivePerceptron::extrabits protected
Definition at line 363 of file multiperspective_perceptron.hh.
Referenced by computeBits(), and setExtraBits().
fudge
const double MultiperspectivePerceptron::fudge protected
Definition at line 270 of file multiperspective_perceptron.hh.
Referenced by computeOutput().
ghist_length
int MultiperspectivePerceptron::ghist_length protected
Definition at line 358 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), uncondBranch(), and update().
hash_taken
const bool MultiperspectivePerceptron::hash_taken protected
Definition at line 275 of file multiperspective_perceptron.hh.
Referenced by update().
hshift
const int MultiperspectivePerceptron::hshift protected
Definition at line 266 of file multiperspective_perceptron.hh.
Referenced by getIndex().
imli_counter_bits
std::vector<int> MultiperspectivePerceptron::imli_counter_bits protected
Definition at line 364 of file multiperspective_perceptron.hh.
Referenced by computeBits().
imli_mask1
const unsigned long long int MultiperspectivePerceptron::imli_mask1 protected
Definition at line 267 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptronTAGE::getIndex(), and getIndex().
imli_mask4
const unsigned long long int MultiperspectivePerceptron::imli_mask4 protected
Definition at line 268 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptronTAGE::getIndex(), and getIndex().
modghist_length
int MultiperspectivePerceptron::modghist_length protected
Definition at line 359 of file multiperspective_perceptron.hh.
modhist_indices
std::vector<int> MultiperspectivePerceptron::modhist_indices protected
Definition at line 365 of file multiperspective_perceptron.hh.
Referenced by init(), update(), and MultiperspectivePerceptronTAGE::updateHistories().
modhist_lengths
std::vector<int> MultiperspectivePerceptron::modhist_lengths protected
Definition at line 366 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), update(), and MultiperspectivePerceptronTAGE::updateHistories().
modpath_indices
std::vector<int> MultiperspectivePerceptron::modpath_indices protected
Definition at line 367 of file multiperspective_perceptron.hh.
Referenced by init(), update(), and MultiperspectivePerceptronTAGE::updateHistories().
modpath_lengths
std::vector<int> MultiperspectivePerceptron::modpath_lengths protected
Definition at line 368 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), update(), and MultiperspectivePerceptronTAGE::updateHistories().
n_sign_bits
const int MultiperspectivePerceptron::n_sign_bits protected
Definition at line 271 of file multiperspective_perceptron.hh.
Referenced by computeBits(), computeOutput(), init(), MultiperspectivePerceptron::ThreadData::ThreadData(), and train().
nbest
const int MultiperspectivePerceptron::nbest protected
Definition at line 264 of file multiperspective_perceptron.hh.
Referenced by computeOutput(), and findBest().
path_length
int MultiperspectivePerceptron::path_length protected
Definition at line 360 of file multiperspective_perceptron.hh.
Referenced by computeBits(), init(), uncondBranch(), and update().
pcbit
const int MultiperspectivePerceptron::pcbit protected
Definition at line 272 of file multiperspective_perceptron.hh.
Referenced by uncondBranch(), and update().
pcshift
const int MultiperspectivePerceptron::pcshift protected
Definition at line 258 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron::MPPBranchInfo::hashPC(), MultiperspectivePerceptronTAGE::lookup(), lookup(), MultiperspectivePerceptronTAGE::uncondBranch(), and uncondBranch().
recencypos_mask
const unsigned long long int MultiperspectivePerceptron::recencypos_mask protected
Definition at line 269 of file multiperspective_perceptron.hh.
Referenced by getIndex().
record_mask
const unsigned int MultiperspectivePerceptron::record_mask protected
Definition at line 274 of file multiperspective_perceptron.hh.
Referenced by update().
specs
std::vector<HistorySpec *> MultiperspectivePerceptron::specs protected
Predictor tables.
Definition at line 351 of file multiperspective_perceptron.hh.
Referenced by computeBits(), computeOutput(), MultiperspectivePerceptronTAGE::computePartialSum(), init(), train(), and MultiperspectivePerceptronTAGE::updatePartial().
speculative_update
const bool MultiperspectivePerceptron::speculative_update protected
Definition at line 280 of file multiperspective_perceptron.hh.
Referenced by MultiperspectivePerceptron().
speed
const int MultiperspectivePerceptron::speed protected
Definition at line 278 of file multiperspective_perceptron.hh.
Referenced by train().
table_sizes
std::vector<int> MultiperspectivePerceptron::table_sizes protected
Definition at line 352 of file multiperspective_perceptron.hh.
Referenced by computeBits(), MultiperspectivePerceptronTAGE::getIndex(), getIndex(), and init().
theta
int MultiperspectivePerceptron::theta protected
Definition at line 362 of file multiperspective_perceptron.hh.
Referenced by train().
threadData
std::vector<ThreadData *> MultiperspectivePerceptron::threadData protected
Definition at line 348 of file multiperspective_perceptron.hh.
Referenced by computeOutput(), MultiperspectivePerceptronTAGE::computePartialSum(), findBest(), MultiperspectivePerceptronTAGE::getIndex(), getIndex(), init(), lookup(), train(), uncondBranch(), MultiperspectivePerceptronTAGE::update(), update(), MultiperspectivePerceptronTAGE::updateHistories(), and MultiperspectivePerceptronTAGE::updatePartial().
threshold
const int MultiperspectivePerceptron::threshold protected
Definition at line 259 of file multiperspective_perceptron.hh.
Referenced by computeBits(), computeOutput(), findBest(), lookup(), and train().
thresholdCounter
int MultiperspectivePerceptron::thresholdCounter protected
Definition at line 361 of file multiperspective_perceptron.hh.
Referenced by train().
tunebits
const int MultiperspectivePerceptron::tunebits protected
Definition at line 265 of file multiperspective_perceptron.hh.
Referenced by computeBits(), and train().
tuneonly
const bool MultiperspectivePerceptron::tuneonly protected
Definition at line 276 of file multiperspective_perceptron.hh.
Referenced by train().
xlat
int MultiperspectivePerceptron::xlat static protected
Initial value:
=
    {1,3,4,5,7,8,9,11,12,14,15,17,19,21,23,25,27,29,32,34,37,41,45,49,53,58,63,
     69,76,85,94,106,}
Transfer function for 6-width tables.
Definition at line 283 of file multiperspective_perceptron.hh.
Referenced by computeOutput(), and train().
xlat4
int MultiperspectivePerceptron::xlat4 static protected
Initial value:
=
    {0,4,5,7,9,11,12,14,16,17,19,22,28,33,39,45,}
Transfer function for 5-width tables.
Definition at line 285 of file multiperspective_perceptron.hh.
Referenced by computeOutput(), and train().
The documentation for this class was generated from the following files:
cpu/pred/multiperspective_perceptron.hh
cpu/pred/multiperspective_perceptron.cc