gem5: Net::TcpPtr Class Reference
Net::TcpPtr Class Reference
#include <inet.hh>
Public Member Functions
TcpPtr ()
TcpPtr (const IpPtr &ptr)
TcpPtr (const Ip6Ptr &ptr)
TcpPtr (const TcpPtr &ptr)
TcpHdr * get ()
TcpHdr * operator-> ()
TcpHdr & operator* ()
const TcpHdr * get () const
const TcpHdr * operator-> () const
const TcpHdr & operator* () const
const TcpPtr & operator= (const IpPtr &i)
const TcpPtr & operator= (const TcpPtr &t)
const EthPacketPtr packet () const
EthPacketPtr packet ()
bool operator! () const
operator bool () const
int off () const
int pstart () const
Protected Member Functions
void set (const EthPacketPtr &ptr, int offset)
void set (const IpPtr &ptr)
void set (const Ip6Ptr &ptr)
Protected Attributes
EthPacketPtr p
int _off
Detailed Description
Definition at line 535 of file inet.hh.
Constructor & Destructor Documentation
TcpPtr() [1/4]
Net::TcpPtr::TcpPtr () inline
Definition at line 558 of file inet.hh.
TcpPtr() [2/4]
Net::TcpPtr::TcpPtr (const IpPtr & ptr) inline
Definition at line 559 of file inet.hh.
TcpPtr() [3/4]
Net::TcpPtr::TcpPtr (const Ip6Ptr & ptr) inline
Definition at line 560 of file inet.hh.
TcpPtr() [4/4]
Net::TcpPtr::TcpPtr (const TcpPtr & ptr) inline
Definition at line 561 of file inet.hh.
Member Function Documentation
get() [1/2]
TcpHdr* Net::TcpPtr::get () inline
Definition at line 563 of file inet.hh.
get() [2/2]
const TcpHdr* Net::TcpPtr::get () const inline
Definition at line 567 of file inet.hh.
off()
int Net::TcpPtr::off () const inline
Definition at line 580 of file inet.hh.
operator bool()
Net::TcpPtr::operator bool () const inline
Definition at line 579 of file inet.hh.
operator!()
bool Net::TcpPtr::operator! () const inline
Definition at line 578 of file inet.hh.
References MipsISA::p.
operator*() [1/2]
TcpHdr& Net::TcpPtr::operator* () inline
Definition at line 565 of file inet.hh.
operator*() [2/2]
const TcpHdr& Net::TcpPtr::operator* () const inline
Definition at line 569 of file inet.hh.
operator->() [1/2]
TcpHdr* Net::TcpPtr::operator-> () inline
Definition at line 564 of file inet.hh.
operator->() [2/2]
const TcpHdr* Net::TcpPtr::operator-> () const inline
Definition at line 568 of file inet.hh.
operator=() [1/2]
const TcpPtr& Net::TcpPtr::operator= (const IpPtr & i) inline
Definition at line 571 of file inet.hh.
References ArmISA::i.
operator=() [2/2]
const TcpPtr& Net::TcpPtr::operator= (const TcpPtr & t) inline
Definition at line 573 of file inet.hh.
References _off, and p.
packet() [1/2]
const EthPacketPtr Net::TcpPtr::packet () const inline
Definition at line 576 of file inet.hh.
References MipsISA::p.
Referenced by Net::cksum().
packet() [2/2]
EthPacketPtr Net::TcpPtr::packet () inline
Definition at line 577 of file inet.hh.
References MipsISA::p.
pstart()
int Net::TcpPtr::pstart () const inline
Definition at line 581 of file inet.hh.
References Net::cksum(), and Net::EthAddr::size().
Referenced by Net::hsplit().
set() [1/3]
void Net::TcpPtr::set (const EthPacketPtr & ptr, int offset) inline protected
Definition at line 541 of file inet.hh.
References ArmISA::offset.
set() [2/3]
void Net::TcpPtr::set (const IpPtr & ptr) inline protected
Definition at line 542 of file inet.hh.
set() [3/3]
void Net::TcpPtr::set (const Ip6Ptr & ptr) inline protected
Definition at line 549 of file inet.hh.
Member Data Documentation
_off
int Net::TcpPtr::_off protected
Definition at line 539 of file inet.hh.
Referenced by operator=().
p
EthPacketPtr Net::TcpPtr::p protected
Definition at line 538 of file inet.hh.
Referenced by operator=().
The documentation for this class was generated from the following file:
base/inet.hh