gem5: ExecStage Class Reference
ExecStage Class Reference
#include <exec_stage.hh>
Public Member Functions
ExecStage (const ComputeUnitParams *params)
~ExecStage ()
void init (ComputeUnit *cu)
void exec ()
std::string name ()
void regStats ()
Public Attributes
Stats::Scalar numCyclesWithNoIssue
Stats::Scalar numCyclesWithInstrIssued
Stats::Vector numCyclesWithInstrTypeIssued
Stats::Vector numCyclesWithNoInstrTypeIssued
Stats::Distribution spc
Private Member Functions
void collectStatistics (enum STAT_STATUS stage, int unitId)
void initStatistics ()
Private Attributes
ComputeUnit * computeUnit
uint32_t numSIMDs
uint32_t numMemUnits
std::vector< std::pair< Wavefront *, DISPATCH_STATUS > > * dispatchList
std::vector< bool > * vectorAluInstAvail
int * glbMemInstAvail
int * shrMemInstAvail
bool lastTimeInstExecuted
bool thisTimeInstExecuted
bool instrExecuted
Stats::Scalar numTransActiveIdle
Stats::Distribution idleDur
uint32_t executionResourcesUsed
uint64_t idle_dur
std::string _name
Detailed Description
Definition at line 70 of file exec_stage.hh.
Constructor & Destructor Documentation
ExecStage()
ExecStage::ExecStage (const ComputeUnitParams * params)
Definition at line 42 of file exec_stage.cc.
References idle_dur, and numTransActiveIdle.
~ExecStage()
ExecStage::~ExecStage () inline
Definition at line 74 of file exec_stage.hh.
References exec(), and init().
Member Function Documentation
collectStatistics()
void ExecStage::collectStatistics (enum STAT_STATUS stage, int unitId) private
Definition at line 66 of file exec_stage.cc.
References BusyExec, computeUnit, executionResourcesUsed, glbMemInstAvail, idle_dur, idleDur, IdleExec, instrExecuted, ComputeUnit::isGlbMem(), ComputeUnit::isShrMem(), ComputeUnit::isVecAlu(), lastTimeInstExecuted, numCyclesWithInstrIssued, numCyclesWithInstrTypeIssued, numCyclesWithNoInstrTypeIssued, numCyclesWithNoIssue, numTransActiveIdle, PostExec, Stats::DistBase< Derived, Stor >::sample(), shrMemInstAvail, spc, thisTimeInstExecuted, and vectorAluInstAvail.
Referenced by exec().
exec()
void ExecStage::exec ()
Definition at line 129 of file exec_stage.cc.
References BusyExec, collectStatistics(), dispatchList, EMPTY, IdleExec, initStatistics(), numMemUnits, numSIMDs, and PostExec.
Referenced by ComputeUnit::exec(), and ~ExecStage().
init()
void ExecStage::init (ComputeUnit * cu)
Definition at line 54 of file exec_stage.cc.
References _name, computeUnit, dispatchList, ComputeUnit::dispatchList, glbMemInstAvail, ComputeUnit::glbMemInstAvail, idle_dur, SimObject::name(), shrMemInstAvail, ComputeUnit::shrMemInstAvail, vectorAluInstAvail, and ComputeUnit::vectorAluInstAvail.
Referenced by ComputeUnit::init(), and ~ExecStage().
initStatistics()
void ExecStage::initStatistics () private
Definition at line 121 of file exec_stage.cc.
References executionResourcesUsed, instrExecuted, and thisTimeInstExecuted.
Referenced by exec().
name()
std::string ExecStage::name () inline
Definition at line 78 of file exec_stage.hh.
References _name, and regStats().
Referenced by regStats().
regStats()
void ExecStage::regStats ()
Definition at line 153 of file exec_stage.cc.
References csprintf(), Stats::DataWrap< Derived, InfoProxyType >::desc(), ArmISA::i, idleDur, Stats::VectorBase< Derived, Stor >::init(), Stats::Distribution::init(), name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numCyclesWithInstrIssued, numCyclesWithInstrTypeIssued, numCyclesWithNoInstrTypeIssued, numCyclesWithNoIssue, numMemUnits, numSIMDs, numTransActiveIdle, spc, and Stats::DataWrapVec< Derived, InfoProxyType >::subname().
Referenced by name(), and ComputeUnit::regStats().
Member Data Documentation
_name
std::string ExecStage::_name private
Definition at line 127 of file exec_stage.hh.
Referenced by init(), and name().
computeUnit
ComputeUnit* ExecStage::computeUnit private
Definition at line 97 of file exec_stage.hh.
Referenced by collectStatistics(), and init().
dispatchList
std::vector<std::pair<Wavefront*, DISPATCH_STATUS> >* ExecStage::dispatchList private
Definition at line 113 of file exec_stage.hh.
Referenced by exec(), and init().
executionResourcesUsed
uint32_t ExecStage::executionResourcesUsed private
Definition at line 125 of file exec_stage.hh.
Referenced by collectStatistics(), and initStatistics().
glbMemInstAvail
int* ExecStage::glbMemInstAvail private
Definition at line 118 of file exec_stage.hh.
Referenced by collectStatistics(), and init().
idle_dur
uint64_t ExecStage::idle_dur private
Definition at line 126 of file exec_stage.hh.
Referenced by collectStatistics(), ExecStage(), and init().
idleDur
Stats::Distribution ExecStage::idleDur private
Definition at line 124 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
instrExecuted
bool ExecStage::instrExecuted private
Definition at line 122 of file exec_stage.hh.
Referenced by collectStatistics(), and initStatistics().
lastTimeInstExecuted
bool ExecStage::lastTimeInstExecuted private
Definition at line 120 of file exec_stage.hh.
Referenced by collectStatistics().
numCyclesWithInstrIssued
Stats::Scalar ExecStage::numCyclesWithInstrIssued
Definition at line 83 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
numCyclesWithInstrTypeIssued
Stats::Vector ExecStage::numCyclesWithInstrTypeIssued
Definition at line 86 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
numCyclesWithNoInstrTypeIssued
Stats::Vector ExecStage::numCyclesWithNoInstrTypeIssued
Definition at line 90 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
numCyclesWithNoIssue
Stats::Scalar ExecStage::numCyclesWithNoIssue
Definition at line 81 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
numMemUnits
uint32_t ExecStage::numMemUnits private
Definition at line 102 of file exec_stage.hh.
Referenced by exec(), and regStats().
numSIMDs
uint32_t ExecStage::numSIMDs private
Definition at line 98 of file exec_stage.hh.
Referenced by exec(), and regStats().
numTransActiveIdle
Stats::Scalar ExecStage::numTransActiveIdle private
Definition at line 123 of file exec_stage.hh.
Referenced by collectStatistics(), ExecStage(), and regStats().
shrMemInstAvail
int* ExecStage::shrMemInstAvail private
Definition at line 119 of file exec_stage.hh.
Referenced by collectStatistics(), and init().
spc
Stats::Distribution ExecStage::spc
Definition at line 92 of file exec_stage.hh.
Referenced by collectStatistics(), and regStats().
thisTimeInstExecuted
bool ExecStage::thisTimeInstExecuted private
Definition at line 121 of file exec_stage.hh.
Referenced by collectStatistics(), and initStatistics().
vectorAluInstAvail
std::vector<bool>* ExecStage::vectorAluInstAvail private
Definition at line 117 of file exec_stage.hh.
Referenced by collectStatistics(), and init().
The documentation for this class was generated from the following files:
gpu-compute/exec_stage.hh
gpu-compute/exec_stage.cc