gem5: AlphaISA::ISA Class Reference
AlphaISA::ISA Class Reference
#include <isa.hh>
Public Types
typedef uint64_t InternalProcReg
typedef AlphaISAParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
RegVal readMiscRegNoEffect (int misc_reg, ThreadID tid=0) const
RegVal readMiscReg (int misc_reg, ThreadContext *tc, ThreadID tid=0)
void setMiscRegNoEffect (int misc_reg, RegVal val, ThreadID tid=0)
void setMiscReg (int misc_reg, RegVal val, ThreadContext *tc, ThreadID tid=0)
void clear ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
RegId flattenRegId (const RegId &regId) const
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenVecIndex (int reg) const
int flattenVecElemIndex (int reg) const
int flattenVecPredIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
const Params * params () const
ISA (Params *p)
void startup (ThreadContext *tc)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
InternalProcReg readIpr (int idx, ThreadContext *tc)
void setIpr (int idx, InternalProcReg val, ThreadContext *tc)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
System * system
uint64_t fpcr
uint64_t uniq
bool lock_flag
Addr lock_addr
int intr_flag
InternalProcReg ipr [NumInternalProcRegs]
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 53 of file isa.hh.
Member Typedef Documentation
InternalProcReg
typedef uint64_t AlphaISA::ISA::InternalProcReg
Definition at line 56 of file isa.hh.
Params
typedef AlphaISAParams AlphaISA::ISA::Params
Definition at line 57 of file isa.hh.
Constructor & Destructor Documentation
ISA()
AlphaISA::ISA::ISA (Params * p)
Definition at line 43 of file isa.cc.
References clear(), and AlphaISA::initializeIprTable().
Referenced by flattenMiscIndex().
Member Function Documentation
clear()
void AlphaISA::ISA::clear () inline
Definition at line 85 of file isa.hh.
References serialize(), and unserialize().
Referenced by ISA().
flattenCCIndex()
int AlphaISA::ISA::flattenCCIndex (int reg) const inline
Definition at line 132 of file isa.hh.
References X86ISA::reg.
flattenFloatIndex()
int AlphaISA::ISA::flattenFloatIndex (int reg) const inline
Definition at line 107 of file isa.hh.
References X86ISA::reg.
flattenIntIndex()
int AlphaISA::ISA::flattenIntIndex (int reg) const inline
Definition at line 101 of file isa.hh.
References X86ISA::reg.
flattenMiscIndex()
int AlphaISA::ISA::flattenMiscIndex (int reg) const inline
Definition at line 138 of file isa.hh.
References ISA(), MipsISA::p, params(), and X86ISA::reg.
flattenRegId()
RegId AlphaISA::ISA::flattenRegId (const RegId & regId) const inline
Definition at line 98 of file isa.hh.
flattenVecElemIndex()
int AlphaISA::ISA::flattenVecElemIndex (int reg) const inline
Definition at line 119 of file isa.hh.
References X86ISA::reg.
flattenVecIndex()
int AlphaISA::ISA::flattenVecIndex (int reg) const inline
Definition at line 113 of file isa.hh.
References X86ISA::reg.
flattenVecPredIndex()
int AlphaISA::ISA::flattenVecPredIndex (int reg) const inline
Definition at line 125 of file isa.hh.
References X86ISA::reg.
params()
const AlphaISAParams * AlphaISA::ISA::params () const
Definition at line 51 of file isa.cc.
References SimObject::_params.
Referenced by flattenMiscIndex().
readIpr()
RegVal AlphaISA::ISA::readIpr (int idx, ThreadContext * tc) protected
Definition at line 111 of file ev5.cc.
References AlphaISA::TlbEntry::asma, AlphaISA::TlbEntry::asn, Clocked::curCycle(), AlphaISA::TlbEntry::fonr, AlphaISA::TlbEntry::fonw, ThreadContext::getCpuPtr(), AlphaISA::getDTBPtr(), AlphaISA::TLB::index(), ipr, AlphaISA::IPR_ALT_MODE, AlphaISA::IPR_ASTER, AlphaISA::IPR_ASTRR, AlphaISA::IPR_CC, AlphaISA::IPR_DC_FLUSH, AlphaISA::IPR_DC_MODE, AlphaISA::IPR_DC_PERR_STAT, AlphaISA::IPR_DTB_CM, AlphaISA::IPR_DTB_IA, AlphaISA::IPR_DTB_IAP, AlphaISA::IPR_DTB_PTE, AlphaISA::IPR_EXC_ADDR, AlphaISA::IPR_EXC_MASK, AlphaISA::IPR_EXC_SUM, AlphaISA::IPR_HWINT_CLR, AlphaISA::IPR_IC_FLUSH, AlphaISA::IPR_IC_PERR_STAT, AlphaISA::IPR_ICM, AlphaISA::IPR_ICSR, AlphaISA::IPR_IFAULT_VA_FORM, AlphaISA::IPR_INTID, AlphaISA::IPR_IPLR, AlphaISA::IPR_ISR, AlphaISA::IPR_ITB_IA, AlphaISA::IPR_ITB_IAP, AlphaISA::IPR_IVPTBR, AlphaISA::IPR_MAF_MODE, AlphaISA::IPR_MCSR, AlphaISA::IPR_MM_STAT, AlphaISA::IPR_PAL_BASE, AlphaISA::IPR_PALtemp0, AlphaISA::IPR_PALtemp1, AlphaISA::IPR_PALtemp10, AlphaISA::IPR_PALtemp11, AlphaISA::IPR_PALtemp12, AlphaISA::IPR_PALtemp13, AlphaISA::IPR_PALtemp14, AlphaISA::IPR_PALtemp15, AlphaISA::IPR_PALtemp16, AlphaISA::IPR_PALtemp17, AlphaISA::IPR_PALtemp18, AlphaISA::IPR_PALtemp19, AlphaISA::IPR_PALtemp2, AlphaISA::IPR_PALtemp20, AlphaISA::IPR_PALtemp21, AlphaISA::IPR_PALtemp22, AlphaISA::IPR_PALtemp23, AlphaISA::IPR_PALtemp3, AlphaISA::IPR_PALtemp4, AlphaISA::IPR_PALtemp5, AlphaISA::IPR_PALtemp6, AlphaISA::IPR_PALtemp7, AlphaISA::IPR_PALtemp8, AlphaISA::IPR_PALtemp9, AlphaISA::IPR_PMCTR, AlphaISA::IPR_SIRR, AlphaISA::IPR_SL_XMIT, AlphaISA::IPR_VA, AlphaISA::IPR_VA_FORM, panic, AlphaISA::TlbEntry::ppn, ULL, AlphaISA::TlbEntry::xre, and AlphaISA::TlbEntry::xwe.
Referenced by readMiscReg().
readMiscReg()
RegVal AlphaISA::ISA::readMiscReg (int misc_reg, ThreadContext * tc, ThreadID tid = 0)
Definition at line 98 of file isa.cc.
References fpcr, intr_flag, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, readIpr(), and uniq.
readMiscRegNoEffect()
RegVal AlphaISA::ISA::readMiscRegNoEffect (int misc_reg, ThreadID tid = 0) const
Definition at line 78 of file isa.cc.
References fpcr, intr_flag, ipr, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, AlphaISA::NumInternalProcRegs, and uniq.
serialize()
void AlphaISA::ISA::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 57 of file isa.cc.
References fpcr, ipr, lock_addr, lock_flag, AlphaISA::NumInternalProcRegs, SERIALIZE_ARRAY, SERIALIZE_SCALAR, and uniq.
Referenced by clear().
setIpr()
void AlphaISA::ISA::setIpr (int idx, InternalProcReg val, ThreadContext * tc) protected
Definition at line 220 of file ev5.cc.
References AlphaISA::TlbEntry::asma, AlphaISA::TlbEntry::asn, AlphaISA::DTB_ASN_ASN(), AlphaISA::DTB_PTE_ASMA(), AlphaISA::DTB_PTE_FONR(), AlphaISA::DTB_PTE_FONW(), AlphaISA::DTB_PTE_GH(), AlphaISA::DTB_PTE_PPN(), AlphaISA::DTB_PTE_XRE(), AlphaISA::DTB_PTE_XWE(), AlphaISA::TLB::flushAddr(), AlphaISA::TLB::flushAll(), AlphaISA::TLB::flushProcesses(), AlphaISA::TlbEntry::fonr, AlphaISA::TlbEntry::fonw, AlphaISA::getDTBPtr(), AlphaISA::getITBPtr(), ThreadContext::getKernelStats(), AlphaISA::TLB::insert(), ipr, AlphaISA::IPR_ALT_MODE, AlphaISA::IPR_ASTER, AlphaISA::IPR_ASTRR, AlphaISA::IPR_CC, AlphaISA::IPR_CC_CTL, AlphaISA::IPR_DC_FLUSH, AlphaISA::IPR_DC_MODE, AlphaISA::IPR_DC_PERR_STAT, AlphaISA::IPR_DC_TEST_CTL, AlphaISA::IPR_DTB_ASN, AlphaISA::IPR_DTB_CM, AlphaISA::IPR_DTB_IA, AlphaISA::IPR_DTB_IAP, AlphaISA::IPR_DTB_IS, AlphaISA::IPR_DTB_PTE, AlphaISA::IPR_DTB_PTE_TEMP, AlphaISA::IPR_DTB_TAG, AlphaISA::IPR_EXC_ADDR, AlphaISA::IPR_EXC_MASK, AlphaISA::IPR_EXC_SUM, AlphaISA::IPR_HWINT_CLR, AlphaISA::IPR_IC_FLUSH, AlphaISA::IPR_IC_PERR_STAT, AlphaISA::IPR_ICM, AlphaISA::IPR_ICSR, AlphaISA::IPR_INTID, AlphaISA::IPR_IPLR, AlphaISA::IPR_ITB_ASN, AlphaISA::IPR_ITB_IA, AlphaISA::IPR_ITB_IAP, AlphaISA::IPR_ITB_IS, AlphaISA::IPR_ITB_PTE, AlphaISA::IPR_ITB_PTE_TEMP, AlphaISA::IPR_ITB_TAG, AlphaISA::IPR_IVPTBR, AlphaISA::IPR_MAF_MODE, AlphaISA::IPR_MCSR, AlphaISA::IPR_MM_STAT, AlphaISA::IPR_MVPTBR, AlphaISA::IPR_PAL_BASE, AlphaISA::IPR_PALtemp0, AlphaISA::IPR_PALtemp1, AlphaISA::IPR_PALtemp10, AlphaISA::IPR_PALtemp11, AlphaISA::IPR_PALtemp12, AlphaISA::IPR_PALtemp13, AlphaISA::IPR_PALtemp14, AlphaISA::IPR_PALtemp15, AlphaISA::IPR_PALtemp16, AlphaISA::IPR_PALtemp17, AlphaISA::IPR_PALtemp18, AlphaISA::IPR_PALtemp19, AlphaISA::IPR_PALtemp2, AlphaISA::IPR_PALtemp20, AlphaISA::IPR_PALtemp21, AlphaISA::IPR_PALtemp22, AlphaISA::IPR_PALtemp23, AlphaISA::IPR_PALtemp3, AlphaISA::IPR_PALtemp4, AlphaISA::IPR_PALtemp5, AlphaISA::IPR_PALtemp6, AlphaISA::IPR_PALtemp7, AlphaISA::IPR_PALtemp8, AlphaISA::IPR_PALtemp9, AlphaISA::IPR_PMCTR, AlphaISA::IPR_SIRR, AlphaISA::IPR_SL_RCV, AlphaISA::IPR_SL_XMIT, AlphaISA::ITB_ASN_ASN(), AlphaISA::ITB_PTE_ASMA(), AlphaISA::ITB_PTE_FONR(), AlphaISA::ITB_PTE_FONW(), AlphaISA::ITB_PTE_GH(), AlphaISA::ITB_PTE_PPN(), AlphaISA::ITB_PTE_XRE(), AlphaISA::Kernel::kernel, M5_FALLTHROUGH, panic, AlphaISA::TlbEntry::ppn, Stats::Group::stats, ULL, AlphaISA::Kernel::user, X86ISA::val, AlphaISA::TlbEntry::xre, and AlphaISA::TlbEntry::xwe.
Referenced by setMiscReg().
setMiscReg()
void AlphaISA::ISA::setMiscReg (int misc_reg, RegVal val, ThreadContext * tc, ThreadID tid = 0)
Definition at line 143 of file isa.cc.
References fpcr, intr_flag, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, setIpr(), uniq, and X86ISA::val.
setMiscRegNoEffect()
void AlphaISA::ISA::setMiscRegNoEffect (int misc_reg, RegVal val, ThreadID tid = 0)
Definition at line 117 of file isa.cc.
References fpcr, intr_flag, ipr, lock_addr, lock_flag, AlphaISA::MISCREG_FPCR, AlphaISA::MISCREG_INTR, AlphaISA::MISCREG_LOCKADDR, AlphaISA::MISCREG_LOCKFLAG, AlphaISA::MISCREG_UNIQ, AlphaISA::NumInternalProcRegs, uniq, and X86ISA::val.
startup()
void AlphaISA::ISA::startup (ThreadContext * tc) inline
Definition at line 147 of file isa.hh.
References SimObject::startup().
unserialize()
void AlphaISA::ISA::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 67 of file isa.cc.
References fpcr, ipr, lock_addr, lock_flag, AlphaISA::NumInternalProcRegs, uniq, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by clear().
Member Data Documentation
fpcr
uint64_t AlphaISA::ISA::fpcr protected
Definition at line 63 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
intr_flag
int AlphaISA::ISA::intr_flag protected
Definition at line 67 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), setMiscReg(), and setMiscRegNoEffect().
ipr
InternalProcReg AlphaISA::ISA::ipr[NumInternalProcRegs] protected
Definition at line 69 of file isa.hh.
Referenced by readIpr(), readMiscRegNoEffect(), serialize(), setIpr(), setMiscRegNoEffect(), and unserialize().
lock_addr
Addr AlphaISA::ISA::lock_addr protected
Definition at line 66 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
lock_flag
bool AlphaISA::ISA::lock_flag protected
Definition at line 65 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
system
System* AlphaISA::ISA::system protected
Definition at line 61 of file isa.hh.
uniq
uint64_t AlphaISA::ISA::uniq protected
Definition at line 64 of file isa.hh.
Referenced by readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), and unserialize().
The documentation for this class was generated from the following files:
arch/alpha/isa.hh
arch/alpha/ev5.cc
arch/alpha/isa.cc