gem5: sc_dt::sc_fix Class Reference
sc_dt::sc_fix Class Reference
#include <sc_fix.hh>
Public Member Functions
sc_fix (sc_fxnum_observer *=0)
sc_fix (int, int, sc_fxnum_observer *=0)
sc_fix (sc_q_mode, sc_o_mode, sc_fxnum_observer *=0)
sc_fix (sc_q_mode, sc_o_mode, int, sc_fxnum_observer *=0)
sc_fix (int, int, sc_q_mode, sc_o_mode, sc_fxnum_observer *=0)
sc_fix (int, int, sc_q_mode, sc_o_mode, int, sc_fxnum_observer *=0)
sc_fix (const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (int, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (int, int, sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (int, int, sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (const sc_fxtype_params &, sc_fxnum_observer *=0)
sc_fix (const sc_fxtype_params &, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_fix (const sc_fix &)
const sc_fix operator~ () const
sc_fix & operator= (const sc_fix &)
const sc_fxval operator++ (int)
const sc_fxval operator-- (int)
sc_fix & operator++ ()
sc_fix & operator-- ()
Public Member Functions inherited from sc_dt::sc_fxnum
const sc_fxval operator- () const
const sc_fxval operator+ () const
const sc_fxval operator++ (int)
const sc_fxval operator-- (int)
sc_fxnum & operator++ ()
sc_fxnum & operator-- ()
const sc_fxnum_bitref operator[] (int) const
sc_fxnum_bitref operator[] (int)
const sc_fxnum_bitref bit (int) const
sc_fxnum_bitref bit (int)
const sc_fxnum_subref operator() (int, int) const
sc_fxnum_subref operator() (int, int)
const sc_fxnum_subref range (int, int) const
sc_fxnum_subref range (int, int)
const sc_fxnum_subref operator() () const
sc_fxnum_subref operator() ()
const sc_fxnum_subref range () const
sc_fxnum_subref range ()
operator double () const
short to_short () const
unsigned short to_ushort () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
float to_float () const
double to_double () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
const std::string to_string (sc_fmt) const
const std::string to_string (sc_numrep, sc_fmt) const
const std::string to_string (sc_numrep, bool, sc_fmt) const
const std::string to_dec () const
const std::string to_bin () const
const std::string to_oct () const
const std::string to_hex () const
bool is_neg () const
bool is_zero () const
bool is_normal () const
bool quantization_flag () const
bool overflow_flag () const
const sc_fxval value () const
int wl () const
int iwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
const sc_fxtype_params & type_params () const
const sc_fxcast_switch & cast_switch () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
void observer_read () const
bool get_bit (int) const
Friends
void b_not (sc_fix &, const sc_fix &)
const sc_fix operator& (const sc_fix &, const sc_fix &)
const sc_fix operator& (const sc_fix &, const sc_fix_fast &)
const sc_fix operator& (const sc_fix_fast &, const sc_fix &)
const sc_fix operator| (const sc_fix &, const sc_fix &)
const sc_fix operator| (const sc_fix &, const sc_fix_fast &)
const sc_fix operator| (const sc_fix_fast &, const sc_fix &)
const sc_fix operator^ (const sc_fix &, const sc_fix &)
const sc_fix operator^ (const sc_fix &, const sc_fix_fast &)
const sc_fix operator^ (const sc_fix_fast &, const sc_fix &)
void b_and (sc_fix &, const sc_fix &, const sc_fix &)
void b_and (sc_fix &, const sc_fix &, const sc_fix_fast &)
void b_and (sc_fix &, const sc_fix_fast &, const sc_fix &)
void b_or (sc_fix &, const sc_fix &, const sc_fix &)
void b_or (sc_fix &, const sc_fix &, const sc_fix_fast &)
void b_or (sc_fix &, const sc_fix_fast &, const sc_fix &)
void b_xor (sc_fix &, const sc_fix &, const sc_fix &)
void b_xor (sc_fix &, const sc_fix &, const sc_fix_fast &)
void b_xor (sc_fix &, const sc_fix_fast &, const sc_fix &)
Additional Inherited Members
Protected Member Functions inherited from sc_dt::sc_fxnum
sc_fxnum_observer * observer () const
void cast ()
sc_fxnum (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &, sc_fxnum_observer *)
~sc_fxnum ()
const scfx_rep * get_rep () const
bool set_bit (int, bool)
bool get_slice (int, int, sc_bv_base &) const
bool set_slice (int, int, const sc_bv_base &)
sc_fxnum_observer * lock_observer () const
void unlock_observer (sc_fxnum_observer *) const
Detailed Description
Definition at line 69 of file sc_fix.hh.
Constructor & Destructor Documentation
sc_fix() [1/15]
sc_dt::sc_fix::sc_fix (sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 408 of file sc_fix.hh.
Referenced by operator~().
sc_fix() [2/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, sc_fxnum_observer * observer_ = 0) inline
Definition at line 412 of file sc_fix.hh.
sc_fix() [3/15]
sc_dt::sc_fix::sc_fix (sc_q_mode qm, sc_o_mode om, sc_fxnum_observer * observer_ = 0) inline
Definition at line 417 of file sc_fix.hh.
sc_fix() [4/15]
sc_dt::sc_fix::sc_fix (sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_observer * observer_ = 0) inline
Definition at line 423 of file sc_fix.hh.
sc_fix() [5/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, sc_fxnum_observer * observer_ = 0) inline
Definition at line 429 of file sc_fix.hh.
sc_fix() [6/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_observer * observer_ = 0) inline
Definition at line 435 of file sc_fix.hh.
sc_fix() [7/15]
sc_dt::sc_fix::sc_fix (const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 441 of file sc_fix.hh.
sc_fix() [8/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 446 of file sc_fix.hh.
sc_fix() [9/15]
sc_dt::sc_fix::sc_fix (sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 451 of file sc_fix.hh.
sc_fix() [10/15]
sc_dt::sc_fix::sc_fix (sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 457 of file sc_fix.hh.
sc_fix() [11/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 463 of file sc_fix.hh.
sc_fix() [12/15]
sc_dt::sc_fix::sc_fix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 470 of file sc_fix.hh.
sc_fix() [13/15]
sc_dt::sc_fix::sc_fix (const sc_fxtype_params & type_params_, sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 477 of file sc_fix.hh.
sc_fix() [14/15]
sc_dt::sc_fix::sc_fix (const sc_fxtype_params & type_params_, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 482 of file sc_fix.hh.
References DEFN_CTORS_T_A, and DEFN_CTORS_T_B.
sc_fix() [15/15]
sc_dt::sc_fix::sc_fix (const sc_fix & a) inline
Definition at line 681 of file sc_fix.hh.
Member Function Documentation
operator++() [1/2]
const sc_fxval sc_dt::sc_fix::operator++ (int) inline
Definition at line 846 of file sc_fix.hh.
References sc_dt::sc_fxnum::sc_fxval.
operator++() [2/2]
sc_fix & sc_dt::sc_fix::operator++ () inline
Definition at line 858 of file sc_fix.hh.
References sc_dt::sc_fxnum::operator++().
Referenced by sc_dt::sc_fixed< W, I, Q, O, N >::operator++().
operator--() [1/2]
const sc_fxval sc_dt::sc_fix::operator-- (int) inline
Definition at line 852 of file sc_fix.hh.
References sc_dt::sc_fxnum::sc_fxval.
operator--() [2/2]
sc_fix & sc_dt::sc_fix::operator-- () inline
Definition at line 865 of file sc_fix.hh.
References sc_dt::sc_fxnum::operator--().
Referenced by sc_dt::sc_fixed< W, I, Q, O, N >::operator--().
operator=()
sc_fix & sc_dt::sc_fix::operator= (const sc_fix & a) inline
Definition at line 771 of file sc_fix.hh.
References DEFN_ASN_OP, and DEFN_ASN_OP_T.
Referenced by sc_dt::sc_fixed< W, I, Q, O, N >::operator=().
operator~()
const sc_fix sc_dt::sc_fix::operator~ () const inline
Definition at line 686 of file sc_fix.hh.
References ArmISA::c, sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::iwl(), sc_fix(), SC_FXNUM_OBSERVER_READ_, sc_dt::sc_fxnum::set_bit(), and sc_dt::sc_fxnum::wl().
Friends And Related Function Documentation
b_and [1/3]
void b_and (sc_fix & , const sc_fix & , const sc_fix &) friend
Referenced by sc_dt::b_not().
b_and [2/3]
void b_and (sc_fix & , const sc_fix & , const sc_fix_fast &) friend
b_and [3/3]
void b_and (sc_fix & , const sc_fix_fast & , const sc_fix &) friend
b_not
void b_not (sc_fix & c, const sc_fix & a) friend
Definition at line 699 of file sc_fix.hh.
b_or [1/3]
void b_or (sc_fix & , const sc_fix & , const sc_fix &) friend
Referenced by sc_dt::b_not().
b_or [2/3]
void b_or (sc_fix & , const sc_fix & , const sc_fix_fast &) friend
b_or [3/3]
void b_or (sc_fix & , const sc_fix_fast & , const sc_fix &) friend
b_xor [1/3]
void b_xor (sc_fix & , const sc_fix & , const sc_fix &) friend
Referenced by sc_dt::b_not().
b_xor [2/3]
void b_xor (sc_fix & , const sc_fix & , const sc_fix_fast &) friend
b_xor [3/3]
void b_xor (sc_fix & , const sc_fix_fast & , const sc_fix &) friend
operator& [1/3]
const sc_fix operator & (const sc_fix & , const sc_fix &) friend
operator& [2/3]
const sc_fix operator & (const sc_fix & , const sc_fix_fast &) friend
operator& [3/3]
const sc_fix operator & (const sc_fix_fast & , const sc_fix &) friend
operator^ [1/3]
const sc_fix operator^ (const sc_fix & , const sc_fix &) friend
operator^ [2/3]
const sc_fix operator^ (const sc_fix & , const sc_fix_fast &) friend
operator^ [3/3]
const sc_fix operator^ (const sc_fix_fast & , const sc_fix &) friend
operator| [1/3]
const sc_fix operator| (const sc_fix & , const sc_fix &) friend
operator| [2/3]
const sc_fix operator| (const sc_fix & , const sc_fix_fast &) friend
operator| [3/3]
const sc_fix operator| (const sc_fix_fast & , const sc_fix &) friend
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_fix.hh