gem5: IGbE Class Reference
IGbE Class Reference
#include <i8254xGBe.hh>
Classes
class DescCache
class RxDescCache
class TxDescCache
Public Types
typedef IGbEParams Params
Public Types inherited from EtherDevice
typedef EtherDeviceParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
IGbE (const Params *params)
~IGbE ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick writeConfig (PacketPtr pkt) override
Write to the PCI config space data that is stored locally.
bool ethRxPkt (EthPacketPtr packet)
void ethTxDone ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
Public Member Functions inherited from EtherDevice
EtherDevice (const Params *params)
const Params * params () const
void regStats ()
Callback to set stat parameters.
Public Member Functions inherited from PciDevice
virtual Tick readConfig (PacketPtr pkt)
Read from the PCI config space data that is stored locally.
Addr pciToDma (Addr pci_addr) const
void intrPost ()
void intrClear ()
uint8_t interruptLine () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
PciDevice (const PciDeviceParams *params)
Constructor for PCI Dev.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
const PciBusAddr & busAddr () const
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
unsigned int cacheBlockSize () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
Tick lastInterrupt
Private Member Functions
void rdtrProcess ()
void radvProcess ()
void tadvProcess ()
void tidvProcess ()
void tick ()
void rxStateMachine ()
void txStateMachine ()
void txWire ()
void postInterrupt (iGbReg::IntTypes t, bool now=false)
Write an interrupt into the interrupt pending register and check mask and interrupt limit timer before sending interrupt to CPU.
void chkInterrupt ()
Check and see if changes to the mask register have caused an interrupt to need to be sent or perhaps removed an interrupt cause.
void delayIntEvent ()
Send an interrupt to the cpu.
void cpuPostInt ()
void cpuClearInt ()
Clear the interupt line to the cpu.
Tick intClock ()
void restartClock ()
This function is used to restart the clock so it can handle things like draining and resume in one place.
void checkDrain ()
Check if all the draining things that need to occur have occured and handle the drain event if so.
void anBegin (std::string sm, std::string st, int flags=CPA::FL_NONE)
void anQ (std::string sm, std::string q)
void anDq (std::string sm, std::string q)
void anPq (std::string sm, std::string q, int num=1)
void anRq (std::string sm, std::string q, int num=1)
void anWe (std::string sm, std::string q)
void anWf (std::string sm, std::string q)
Private Attributes
IGbEInt * etherInt
CPA * cpa
iGbReg::Regs regs
int eeOpBits
int eeAddrBits
int eeDataBits
uint8_t eeOpcode
uint8_t eeAddr
uint16_t flash [iGbReg::EEPROM_SIZE]
PacketFifo rxFifo
PacketFifo txFifo
EthPacketPtr txPacket
bool inTick
bool rxTick
bool txTick
bool txFifoTick
bool rxDmaPacket
unsigned pktOffset
Tick fetchDelay
Tick wbDelay
Tick fetchCompDelay
Tick wbCompDelay
Tick rxWriteDelay
Tick txReadDelay
EventFunctionWrapper rdtrEvent
EventFunctionWrapper radvEvent
EventFunctionWrapper tadvEvent
EventFunctionWrapper tidvEvent
EventFunctionWrapper tickEvent
uint64_t macAddr
EventFunctionWrapper interEvent
RxDescCache rxDescCache
TxDescCache txDescCache
Friends
class RxDescCache
class TxDescCache
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from PciDevice
bool isLargeBAR (int bar) const
Does the given BAR represent 32 lower bits of a 64-bit address?
bool isBAR (Addr addr, int bar) const
Does the given address lie within the space mapped by the given base address register?
int getBAR (Addr addr)
Which base address register (if any) maps the given address?
bool getBAR (Addr addr, int &bar, Addr &offs)
Which base address register (if any) maps the given address?
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from EtherDevice
Stats::Scalar txBytes
Stats::Scalar rxBytes
Stats::Scalar txPackets
Stats::Scalar rxPackets
Stats::Scalar txIpChecksums
Stats::Scalar rxIpChecksums
Stats::Scalar txTcpChecksums
Stats::Scalar rxTcpChecksums
Stats::Scalar txUdpChecksums
Stats::Scalar rxUdpChecksums
Stats::Scalar descDmaReads
Stats::Scalar descDmaWrites
Stats::Scalar descDmaRdBytes
Stats::Scalar descDmaWrBytes
Stats::Formula totBandwidth
Stats::Formula totPackets
Stats::Formula totBytes
Stats::Formula totPacketRate
Stats::Formula txBandwidth
Stats::Formula rxBandwidth
Stats::Formula txPacketRate
Stats::Formula rxPacketRate
Stats::Scalar postedSwi
Stats::Formula coalescedSwi
Stats::Scalar totalSwi
Stats::Scalar postedRxIdle
Stats::Formula coalescedRxIdle
Stats::Scalar totalRxIdle
Stats::Scalar postedRxOk
Stats::Formula coalescedRxOk
Stats::Scalar totalRxOk
Stats::Scalar postedRxDesc
Stats::Formula coalescedRxDesc
Stats::Scalar totalRxDesc
Stats::Scalar postedTxOk
Stats::Formula coalescedTxOk
Stats::Scalar totalTxOk
Stats::Scalar postedTxIdle
Stats::Formula coalescedTxIdle
Stats::Scalar totalTxIdle
Stats::Scalar postedTxDesc
Stats::Formula coalescedTxDesc
Stats::Scalar totalTxDesc
Stats::Scalar postedRxOrn
Stats::Formula coalescedRxOrn
Stats::Scalar totalRxOrn
Stats::Formula coalescedTotal
Stats::Scalar postedInterrupts
Stats::Scalar droppedPackets
Protected Attributes inherited from PciDevice
const PciBusAddr _busAddr
PCIConfig config
The current config space.
std::vector< MSIXTable > msix_table
MSIX Table and PBA Structures.
std::vector< MSIXPbaEntry > msix_pba
uint32_t BARSize [6]
The size of the BARs.
Addr BARAddrs [6]
The current address mapping of the BARs.
bool legacyIO [6]
Whether the BARs are really hardwired legacy IO locations.
PciHost::DeviceInterface hostInterface
Tick pioDelay
Tick configDelay
const int PMCAP_BASE
The capability list structures and base addresses.
const int PMCAP_ID_OFFSET
const int PMCAP_PC_OFFSET
const int PMCAP_PMCS_OFFSET
PMCAP pmcap
const int MSICAP_BASE
MSICAP msicap
const int MSIXCAP_BASE
const int MSIXCAP_ID_OFFSET
const int MSIXCAP_MXC_OFFSET
const int MSIXCAP_MTAB_OFFSET
const int MSIXCAP_MPBA_OFFSET
int MSIX_TABLE_OFFSET
int MSIX_TABLE_END
int MSIX_PBA_OFFSET
int MSIX_PBA_END
MSIXCAP msixcap
const int PXCAP_BASE
PXCAP pxcap
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 56 of file i8254xGBe.hh.
Member Typedef Documentation
Params
typedef IGbEParams IGbE::Params
Definition at line 512 of file i8254xGBe.hh.
Constructor & Destructor Documentation
IGbE()
IGbE::IGbE (const Params * params)
Definition at line 60 of file i8254xGBe.cc.
References PacketFifo::clear(), iGbReg::Regs::ctrl, delayIntEvent(), eeAddrBits, iGbReg::Regs::eecd, eeDataBits, eeOpBits, eeOpcode, iGbReg::EEPROM_CSUM, EEPROM_SIZE, etherInt, iGbReg::Regs::fcrth, flash, htobe(), iGbReg::Regs::iam, iGbReg::Regs::imr, interEvent, lastInterrupt, macAddr, SimObject::name(), MipsISA::p, iGbReg::Regs::pba, radvEvent, radvProcess(), rdtrProcess(), regs, iGbReg::Regs::rlpml, iGbReg::Regs::rxdctl, rxDescCache, rxFifo, iGbReg::Regs::sts, iGbReg::Regs::sw_fw_sync, tadvEvent, tadvProcess(), iGbReg::Regs::tdwba, tick(), tickEvent, tidvEvent, tidvProcess(), txDescCache, txFifo, and X86ISA::x.
Referenced by params(), and unserialize().
~IGbE()
IGbE::~IGbE ()
Definition at line 130 of file i8254xGBe.cc.
References etherInt.
Referenced by params().
Member Function Documentation
anBegin()
void IGbE::anBegin (std::string sm, std::string st, int flags = CPA::FL_NONE) inline private
Definition at line 177 of file i8254xGBe.hh.
References CPA::hwBegin(), and PioDevice::sys.
Referenced by ethRxPkt(), ethTxDone(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), rxStateMachine(), txStateMachine(), and txWire().
anDq()
void IGbE::anDq (std::string sm, std::string q) inline private
Definition at line 187 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwDq(), and PioDevice::sys.
Referenced by IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), IGbE::TxDescCache::processContextDesc(), rxStateMachine(), and txWire().
anPq()
void IGbE::anPq (std::string sm, std::string q, int num = 1) inline private
Definition at line 192 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwPq(), and PioDevice::sys.
Referenced by rxStateMachine(), txStateMachine(), and txWire().
anQ()
void IGbE::anQ (std::string sm, std::string q) inline private
Definition at line 182 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwQ(), and PioDevice::sys.
Referenced by ethRxPkt(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), IGbE::TxDescCache::processContextDesc(), txStateMachine(), and txWire().
anRq()
void IGbE::anRq (std::string sm, std::string q, int num = 1) inline private
Definition at line 197 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwRq(), and PioDevice::sys.
Referenced by txStateMachine().
anWe()
void IGbE::anWe (std::string sm, std::string q) inline private
Definition at line 202 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwWe(), and PioDevice::sys.
Referenced by rxStateMachine(), txStateMachine(), and txWire().
anWf()
void IGbE::anWf (std::string sm, std::string q) inline private
Definition at line 207 of file i8254xGBe.hh.
References CPA::FL_NONE, CPA::hwWf(), and PioDevice::sys.
Referenced by txStateMachine().
checkDrain()
void IGbE::checkDrain () private
Check if all the draining things that need to occur have occured and handle the drain event if so.
Definition at line 2117 of file i8254xGBe.cc.
References DPRINTF, Draining, Drainable::drainState(), IGbE::RxDescCache::hasOutstandingEvents(), IGbE::TxDescCache::hasOutstandingEvents(), rxDescCache, rxTick, Drainable::signalDrainDone(), txDescCache, txFifoTick, and txTick.
Referenced by IGbE::TxDescCache::headerComplete(), intClock(), IGbE::RxDescCache::pktComplete(), and IGbE::TxDescCache::pktComplete().
chkInterrupt()
void IGbE::chkInterrupt () private
Check and see if changes to the mask register have caused an interrupt to need to be sent or perhaps removed an interrupt cause.
Definition at line 791 of file i8254xGBe.cc.
References cpuClearInt(), cpuPostInt(), curTick(), EventManager::deschedule(), DPRINTF, iGbReg::Regs::icr, iGbReg::Regs::imr, interEvent, iGbReg::Regs::itr, SimClock::Int::ns, regs, EventManager::schedule(), Event::scheduled(), and ArmISA::t.
Referenced by read(), and write().
cpuClearInt()
void IGbE::cpuClearInt () private
Clear the interupt line to the cpu.
Definition at line 779 of file i8254xGBe.cc.
References DPRINTF, iGbReg::Regs::icr, PciDevice::intrClear(), and regs.
Referenced by chkInterrupt().
cpuPostInt()
void IGbE::cpuPostInt () private
Definition at line 735 of file i8254xGBe.cc.
References curTick(), EventManager::deschedule(), DPRINTF, iGbReg::Regs::icr, iGbReg::Regs::imr, interEvent, PciDevice::intrPost(), lastInterrupt, EtherDevice::postedInterrupts, radvEvent, rdtrEvent, regs, Event::scheduled(), tadvEvent, and tidvEvent.
Referenced by chkInterrupt(), delayIntEvent(), and postInterrupt().
delayIntEvent()
void IGbE::delayIntEvent () private
Send an interrupt to the cpu.
Definition at line 728 of file i8254xGBe.cc.
References cpuPostInt().
Referenced by IGbE().
drain()
DrainState IGbE::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 2081 of file i8254xGBe.cc.
References X86ISA::count, EventManager::deschedule(), DPRINTF, Drained, Draining, IGbE::RxDescCache::hasOutstandingEvents(), IGbE::TxDescCache::hasOutstandingEvents(), rxDescCache, rxTick, Event::scheduled(), tickEvent, txDescCache, txFifoTick, and txTick.
drainResume()
void IGbE::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 2104 of file i8254xGBe.cc.
References DPRINTF, Drainable::drainResume(), restartClock(), rxTick, txFifoTick, and txTick.
ethRxPkt()
bool IGbE::ethRxPkt (EthPacketPtr packet)
Definition at line 2235 of file i8254xGBe.cc.
References anBegin(), anQ(), CPA::available(), cpa, DPRINTF, Draining, Drainable::drainState(), CPA::enabled(), CPA::FL_BAD, CPA::FL_NONE, CPA::hwDq(), CPA::hwWe(), iGbReg::IT_RXO, macAddr, System::numSystemsRunning, postInterrupt(), PacketFifo::push(), iGbReg::Regs::rctl, regs, restartClock(), EtherDevice::rxBytes, rxFifo, EtherDevice::rxPackets, rxTick, Event::scheduled(), PioDevice::sys, System::systemList, tickEvent, and txTick.
Referenced by IGbEInt::recvPacket().
ethTxDone()
void IGbE::ethTxDone ()
Definition at line 2463 of file i8254xGBe.cc.
References anBegin(), IGbE::DescCache< T >::descLeft(), DPRINTF, Draining, Drainable::drainState(), inTick, restartClock(), txDescCache, txFifoTick, and txTick.
Referenced by IGbEInt::sendDone().
getPort()
Port & IGbE::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from DmaDevice.
Definition at line 143 of file i8254xGBe.cc.
References etherInt, and DmaDevice::getPort().
Referenced by params().
init()
void IGbE::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from DmaDevice.
Definition at line 136 of file i8254xGBe.cc.
References cpa, CPA::cpa(), and DmaDevice::init().
Referenced by params().
intClock()
Tick IGbE::intClock () inline private
Definition at line 166 of file i8254xGBe.hh.
References checkDrain(), SimClock::Int::ns, and restartClock().
Referenced by IGbE::RxDescCache::pktComplete(), and IGbE::TxDescCache::pktComplete().
params()
const Params* IGbE::params () const inline
Definition at line 514 of file i8254xGBe.hh.
References SimObject::_params, getPort(), IGbE(), init(), InvalidPortID, and ~IGbE().
Referenced by write().
postInterrupt()
void IGbE::postInterrupt (iGbReg::IntTypes t, bool now = false) private
Write an interrupt into the interrupt pending register and check mask and interrupt limit timer before sending interrupt to CPU.
Parameters
t the type of interrupt we are posting
now should we ignore the interrupt limiting timer
Definition at line 695 of file i8254xGBe.cc.
References cpuPostInt(), curTick(), EventManager::deschedule(), DPRINTF, iGbReg::Regs::icr, interEvent, iGbReg::Regs::itr, lastInterrupt, SimClock::Int::ns, regs, EventManager::schedule(), Event::scheduled(), and ArmISA::t.
Referenced by IGbE::TxDescCache::actionAfterWb(), ethRxPkt(), IGbE::RxDescCache::pktComplete(), radvProcess(), rdtrProcess(), read(), rxStateMachine(), tadvProcess(), tidvProcess(), txStateMachine(), and write().
radvProcess()
void IGbE::radvProcess () inline private
Definition at line 104 of file i8254xGBe.hh.
References DPRINTF, iGbReg::IT_RXT, postInterrupt(), rxDescCache, and IGbE::DescCache< T >::writeback().
Referenced by IGbE().
rdtrProcess()
void IGbE::rdtrProcess () inline private
Definition at line 94 of file i8254xGBe.hh.
References DPRINTF, iGbReg::IT_RXT, postInterrupt(), rxDescCache, and IGbE::DescCache< T >::writeback().
Referenced by IGbE().
read()
Tick IGbE::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 170 of file i8254xGBe.cc.
References chkInterrupt(), iGbReg::Regs::ctrl, iGbReg::Regs::ctrl_ext, DPRINTF, iGbReg::Regs::eecd, iGbReg::Regs::eerd, iGbReg::Regs::fcrth, iGbReg::Regs::fcrtl, iGbReg::Regs::fcttv, iGbReg::Regs::fwsm, Packet::getAddr(), PciDevice::getBAR(), Packet::getSize(), iGbReg::Regs::iam, iGbReg::Regs::icr, iGbReg::Regs::imr, IN_RANGE, iGbReg::IT_RXT, iGbReg::Regs::itr, Packet::makeAtomicResponse(), iGbReg::Regs::manc, ArmISA::mask, iGbReg::Regs::mdic, iGbReg::MULTICAST_TABLE_SIZE, panic, iGbReg::Regs::pba, PciDevice::pioDelay, postInterrupt(), iGbReg::Regs::radv, iGbReg::Regs::rctl, iGbReg::RCV_ADDRESS_TABLE_SIZE, iGbReg::Regs::rdba, iGbReg::Regs::rdh, iGbReg::Regs::rdlen, iGbReg::Regs::rdt, iGbReg::Regs::rdtr, iGbReg::REG_CRCERRS, iGbReg::REG_CTRL, iGbReg::REG_CTRL_EXT, iGbReg::REG_EECD, iGbReg::REG_EERD, iGbReg::REG_EICR, iGbReg::REG_FCRTH, iGbReg::REG_FCRTL, iGbReg::REG_FCTTV, iGbReg::REG_FWSM, iGbReg::REG_ICR, iGbReg::REG_ITR, iGbReg::REG_LEDCTL, iGbReg::REG_MANC, iGbReg::REG_MDIC, iGbReg::REG_MTA, iGbReg::REG_PBA, iGbReg::REG_RADV, iGbReg::REG_RAL, iGbReg::REG_RCTL, iGbReg::REG_RDBAH, iGbReg::REG_RDBAL, iGbReg::REG_RDH, iGbReg::REG_RDLEN, iGbReg::REG_RDT, iGbReg::REG_RDTR, iGbReg::REG_RFCTL, iGbReg::REG_RLPML, iGbReg::REG_RXCSUM, iGbReg::REG_RXDCTL, iGbReg::REG_SRRCTL, iGbReg::REG_STATUS, iGbReg::REG_SWFWSYNC, iGbReg::REG_SWSM, iGbReg::REG_TADV, iGbReg::REG_TCTL, iGbReg::REG_TDBAH, iGbReg::REG_TDBAL, iGbReg::REG_TDH, iGbReg::REG_TDLEN, iGbReg::REG_TDT, iGbReg::REG_TDWBAH, iGbReg::REG_TDWBAL, iGbReg::REG_TIDV, iGbReg::REG_TXDCA_CTL, iGbReg::REG_TXDCTL, iGbReg::REG_VFTA, iGbReg::REG_WUC, iGbReg::REG_WUFC, iGbReg::REG_WUS, regs, iGbReg::Regs::rfctl, iGbReg::Regs::rlpml, iGbReg::Regs::rxcsum, iGbReg::Regs::rxdctl, rxDescCache, Packet::setLE(), iGbReg::Regs::srrctl, iGbReg::STATS_REGS_SIZE, iGbReg::Regs::sts, iGbReg::Regs::sw_fw_sync, iGbReg::Regs::swsm, iGbReg::Regs::tadv, iGbReg::Regs::tctl, iGbReg::Regs::tdba, iGbReg::Regs::tdh, iGbReg::Regs::tdlen, iGbReg::Regs::tdt, iGbReg::Regs::tdwba, iGbReg::Regs::tidv, iGbReg::Regs::txdca_ctl, iGbReg::Regs::txdctl, iGbReg::VLAN_FILTER_TABLE_SIZE, and IGbE::DescCache< T >::writeback().
restartClock()
void IGbE::restartClock () private
This function is used to restart the clock so it can handle things like draining and resume in one place.
Definition at line 2073 of file i8254xGBe.cc.
References Clocked::clockEdge(), Drainable::drainState(), Running, rxTick, EventManager::schedule(), Event::scheduled(), tickEvent, txFifoTick, and txTick.
Referenced by drainResume(), IGbE::RxDescCache::enableSm(), IGbE::TxDescCache::enableSm(), ethRxPkt(), ethTxDone(), intClock(), and write().
rxStateMachine()
void IGbE::rxStateMachine () private
Definition at line 2283 of file i8254xGBe.cc.
References anBegin(), anDq(), IGbE::DescCache< T >::annUnusedCacheQ, anPq(), anWe(), DmaDevice::cacheBlockSize(), IGbE::DescCache< T >::descLeft(), IGbE::DescCache< iGbReg::TxDesc >::descLeft(), IGbE::DescCache< T >::descUnused(), IGbE::DescCache< T >::descUsed(), DPRINTF, PacketFifo::empty(), IGbE::DescCache< T >::fetchDescriptors(), PacketFifo::front(), iGbReg::IT_RXDMT, IGbE::RxDescCache::packetDone(), pktOffset, PacketFifo::pop(), postInterrupt(), iGbReg::Regs::rctl, iGbReg::Regs::rdlen, regs, iGbReg::Regs::rxdctl, rxDescCache, rxDmaPacket, rxFifo, rxTick, ULL, IGbE::DescCache< T >::writeback(), and IGbE::RxDescCache::writePacket().
Referenced by tick().
serialize()
void IGbE::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2479 of file i8254xGBe.cc.
References eeAddr, eeAddrBits, eeDataBits, eeOpBits, eeOpcode, iGbReg::EEPROM_SIZE, flash, interEvent, lastInterrupt, pktOffset, radvEvent, rdtrEvent, regs, rxDescCache, rxFifo, Event::scheduled(), PacketFifo::serialize(), PciDevice::serialize(), iGbReg::Regs::serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, Serializable::serializeSection(), tadvEvent, tidvEvent, txDescCache, txFifo, txPacket, and Event::when().
tadvProcess()
void IGbE::tadvProcess () inline private
Definition at line 114 of file i8254xGBe.hh.
References DPRINTF, iGbReg::IT_TXDW, postInterrupt(), txDescCache, and IGbE::DescCache< T >::writeback().
Referenced by IGbE().
tick()
void IGbE::tick () private
Definition at line 2435 of file i8254xGBe.cc.
References Clocked::clockPeriod(), curTick(), DPRINTF, inTick, rxStateMachine(), rxTick, EventManager::schedule(), tickEvent, txFifoTick, txStateMachine(), txTick, and txWire().
Referenced by IGbE().
tidvProcess()
void IGbE::tidvProcess () inline private
Definition at line 124 of file i8254xGBe.hh.
References DPRINTF, iGbReg::IT_TXDW, postInterrupt(), txDescCache, and IGbE::DescCache< T >::writeback().
Referenced by IGbE().
txStateMachine()
void IGbE::txStateMachine () private
Definition at line 2133 of file i8254xGBe.cc.
References anBegin(), IGbE::DescCache< T >::annUnusedCacheQ, anPq(), anQ(), anRq(), anWe(), anWf(), PacketFifo::avail(), DmaDevice::cacheBlockSize(), IGbE::DescCache< T >::descLeft(), IGbE::DescCache< T >::descUnused(), DPRINTF, Draining, Drainable::drainState(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::TxDescCache::getPacketData(), IGbE::TxDescCache::getPacketSize(), iGbReg::IT_TXDLOW, iGbReg::IT_TXQE, IGbE::TxDescCache::packetAvailable(), IGbE::TxDescCache::packetMultiDesc(), IGbE::TxDescCache::packetWaiting(), postInterrupt(), IGbE::TxDescCache::processContextDesc(), PacketFifo::push(), regs, PacketFifo::reserve(), IGbE::DescCache< iGbReg::TxDesc >::size, iGbReg::Regs::tctl, iGbReg::Regs::txdctl, txDescCache, txFifo, txFifoTick, txPacket, txTick, and IGbE::DescCache< T >::writeback().
Referenced by tick().
txWire()
void IGbE::txWire () private
Definition at line 2400 of file i8254xGBe.cc.
References anBegin(), anDq(), anPq(), anQ(), anWe(), PacketFifo::avail(), DPRINTF, DTRACE, PacketFifo::empty(), etherInt, PacketFifo::front(), iGbReg::TxdOp::ip(), PacketFifo::pop(), EtherInt::sendPacket(), EtherDevice::txBytes, txFifo, txFifoTick, and EtherDevice::txPackets.
Referenced by tick().
unserialize()
void IGbE::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 2530 of file i8254xGBe.cc.
References eeAddr, eeAddrBits, eeDataBits, eeOpBits, eeOpcode, iGbReg::EEPROM_SIZE, flash, IGbE(), interEvent, lastInterrupt, pktOffset, radvEvent, rdtrEvent, regs, rxDescCache, rxFifo, rxTick, EventManager::schedule(), tadvEvent, tidvEvent, txDescCache, txFifo, txFifoTick, txPacket, txTick, PacketFifo::unserialize(), PciDevice::unserialize(), iGbReg::Regs::unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, and Serializable::unserializeSection().
write()
Tick IGbE::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 358 of file i8254xGBe.cc.
References IGbE::DescCache< T >::areaChanged(), bits(), chkInterrupt(), PacketFifo::clear(), IGbE::TxDescCache::completionWriteback(), iGbReg::Regs::ctrl, iGbReg::Regs::ctrl_ext, DPRINTF, Drainable::drainState(), eeAddr, eeAddrBits, iGbReg::Regs::eecd, eeDataBits, eeOpBits, eeOpcode, iGbReg::EEPROM_RDSR_OPCODE_SPI, iGbReg::EEPROM_READ_OPCODE_SPI, EEPROM_SIZE, iGbReg::Regs::eerd, iGbReg::Regs::fcrth, iGbReg::Regs::fcrtl, iGbReg::Regs::fcttv, IGbE::DescCache< T >::fetchDescriptors(), flash, iGbReg::Regs::fwsm, Packet::getAddr(), PciDevice::getBAR(), Packet::getLE(), Packet::getSize(), iGbReg::Regs::iam, iGbReg::Regs::icr, iGbReg::Regs::imr, IN_RANGE, iGbReg::Regs::itr, Packet::makeAtomicResponse(), iGbReg::Regs::manc, ArmISA::mask, iGbReg::Regs::mdic, iGbReg::MULTICAST_TABLE_SIZE, panic, params(), iGbReg::Regs::pba, iGbReg::PHY_AGC, iGbReg::PHY_EPID, iGbReg::PHY_EPSTATUS, iGbReg::PHY_GSTATUS, iGbReg::PHY_PID, iGbReg::PHY_PSTATUS, PciDevice::pioDelay, postInterrupt(), iGbReg::Regs::radv, iGbReg::Regs::rctl, iGbReg::RCV_ADDRESS_TABLE_SIZE, iGbReg::Regs::rdba, iGbReg::Regs::rdh, iGbReg::Regs::rdlen, iGbReg::Regs::rdt, iGbReg::Regs::rdtr, iGbReg::REG_AIFS, iGbReg::REG_CTRL, iGbReg::REG_CTRL_EXT, iGbReg::REG_EECD, iGbReg::REG_EERD, iGbReg::REG_FCAH, iGbReg::REG_FCAL, iGbReg::REG_FCRTH, iGbReg::REG_FCRTL, iGbReg::REG_FCT, iGbReg::REG_FCTTV, iGbReg::REG_IAM, iGbReg::REG_ICR, iGbReg::REG_ICS, iGbReg::REG_IMC, iGbReg::REG_IMS, iGbReg::REG_ITR, iGbReg::REG_IVAR0, iGbReg::REG_LEDCTL, iGbReg::REG_MANC, iGbReg::REG_MDIC, iGbReg::REG_MTA, iGbReg::REG_PBA, iGbReg::REG_RADV, iGbReg::REG_RAL, iGbReg::REG_RCTL, iGbReg::REG_RDBAH, iGbReg::REG_RDBAL, iGbReg::REG_RDH, iGbReg::REG_RDLEN, iGbReg::REG_RDT, iGbReg::REG_RDTR, iGbReg::REG_RFCTL, iGbReg::REG_RLPML, iGbReg::REG_RXCSUM, iGbReg::REG_RXDCTL, iGbReg::REG_SRRCTL, iGbReg::REG_STATUS, iGbReg::REG_SWFWSYNC, iGbReg::REG_SWSM, iGbReg::REG_TADV, iGbReg::REG_TCTL, iGbReg::REG_TDBAH, iGbReg::REG_TDBAL, iGbReg::REG_TDH, iGbReg::REG_TDLEN, iGbReg::REG_TDT, iGbReg::REG_TDWBAH, iGbReg::REG_TDWBAL, iGbReg::REG_TIDV, iGbReg::REG_TIPG, iGbReg::REG_TXDCA_CTL, iGbReg::REG_TXDCTL, iGbReg::REG_VET, iGbReg::REG_VFTA, iGbReg::REG_WUC, iGbReg::REG_WUFC, iGbReg::REG_WUS, regs, IGbE::DescCache< T >::reset(), restartClock(), iGbReg::Regs::rfctl, iGbReg::Regs::rlpml, Running, iGbReg::Regs::rxcsum, iGbReg::Regs::rxdctl, rxDescCache, rxFifo, rxTick, iGbReg::Regs::srrctl, iGbReg::Regs::sts, iGbReg::Regs::sw_fw_sync, iGbReg::Regs::swsm, iGbReg::Regs::tadv, iGbReg::Regs::tctl, iGbReg::Regs::tdba, iGbReg::Regs::tdh, iGbReg::Regs::tdlen, iGbReg::Regs::tdt, iGbReg::Regs::tdwba, iGbReg::Regs::tidv, iGbReg::Regs::txdca_ctl, iGbReg::Regs::txdctl, txDescCache, txTick, X86ISA::val, iGbReg::VLAN_FILTER_TABLE_SIZE, and warn.
writeConfig()
Tick IGbE::writeConfig (PacketPtr pkt) override virtual
Write to the PCI config space data that is stored locally.
This may be overridden by the device but at some point it will eventually call this for normal operations that it does not need to override.
Parameters
pkt packet containing the write the offset into config space
Reimplemented from PciDevice.
Definition at line 151 of file i8254xGBe.cc.
References PciDevice::configDelay, Packet::getAddr(), ArmISA::offset, panic, PCI_CONFIG_SIZE, PCI_DEVICE_SPECIFIC, and PciDevice::writeConfig().
Friends And Related Function Documentation
RxDescCache
friend class RxDescCache friend
Definition at line 395 of file i8254xGBe.hh.
TxDescCache
friend class TxDescCache friend
Definition at line 507 of file i8254xGBe.hh.
Member Data Documentation
cpa
CPA* IGbE::cpa private
Definition at line 60 of file i8254xGBe.hh.
Referenced by ethRxPkt(), and init().
eeAddr
uint8_t IGbE::eeAddr private
Definition at line 67 of file i8254xGBe.hh.
Referenced by serialize(), unserialize(), and write().
eeAddrBits
int IGbE::eeAddrBits private
Definition at line 66 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), unserialize(), and write().
eeDataBits
int IGbE::eeDataBits private
Definition at line 66 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), unserialize(), and write().
eeOpBits
int IGbE::eeOpBits private
Definition at line 66 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), unserialize(), and write().
eeOpcode
uint8_t IGbE::eeOpcode private
Definition at line 67 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), unserialize(), and write().
etherInt
IGbEInt* IGbE::etherInt private
Definition at line 59 of file i8254xGBe.hh.
Referenced by getPort(), IGbE(), txWire(), and ~IGbE().
fetchCompDelay
Tick IGbE::fetchCompDelay private
Definition at line 90 of file i8254xGBe.hh.
fetchDelay
Tick IGbE::fetchDelay private
Definition at line 89 of file i8254xGBe.hh.
flash
uint16_t IGbE::flash[iGbReg::EEPROM_SIZE] private
Definition at line 68 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), unserialize(), and write().
interEvent
EventFunctionWrapper IGbE::interEvent private
Definition at line 160 of file i8254xGBe.hh.
Referenced by chkInterrupt(), cpuPostInt(), IGbE(), postInterrupt(), serialize(), and unserialize().
inTick
bool IGbE::inTick private
Definition at line 78 of file i8254xGBe.hh.
Referenced by ethTxDone(), and tick().
lastInterrupt
Tick IGbE::lastInterrupt
Definition at line 525 of file i8254xGBe.hh.
Referenced by cpuPostInt(), IGbE(), postInterrupt(), serialize(), and unserialize().
macAddr
uint64_t IGbE::macAddr private
Definition at line 137 of file i8254xGBe.hh.
Referenced by ethRxPkt(), and IGbE().
pktOffset
unsigned IGbE::pktOffset private
Definition at line 86 of file i8254xGBe.hh.
Referenced by rxStateMachine(), serialize(), and unserialize().
radvEvent
EventFunctionWrapper IGbE::radvEvent private
Definition at line 111 of file i8254xGBe.hh.
Referenced by cpuPostInt(), IGbE(), IGbE::RxDescCache::pktComplete(), serialize(), and unserialize().
rdtrEvent
EventFunctionWrapper IGbE::rdtrEvent private
Definition at line 101 of file i8254xGBe.hh.
Referenced by cpuPostInt(), IGbE::RxDescCache::pktComplete(), serialize(), and unserialize().
regs
iGbReg::Regs IGbE::regs private
Definition at line 63 of file i8254xGBe.hh.
Referenced by IGbE::TxDescCache::actionAfterWb(), chkInterrupt(), cpuClearInt(), cpuPostInt(), IGbE::RxDescCache::descBase(), IGbE::TxDescCache::descBase(), IGbE::RxDescCache::descHead(), IGbE::TxDescCache::descHead(), IGbE::RxDescCache::descLen(), IGbE::TxDescCache::descLen(), IGbE::RxDescCache::descTail(), IGbE::TxDescCache::descTail(), ethRxPkt(), IGbE(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), postInterrupt(), read(), rxStateMachine(), serialize(), txStateMachine(), unserialize(), IGbE::RxDescCache::updateHead(), IGbE::TxDescCache::updateHead(), write(), and IGbE::RxDescCache::writePacket().
rxDescCache
RxDescCache IGbE::rxDescCache private
Definition at line 397 of file i8254xGBe.hh.
Referenced by checkDrain(), drain(), IGbE(), radvProcess(), rdtrProcess(), read(), rxStateMachine(), serialize(), unserialize(), and write().
rxDmaPacket
bool IGbE::rxDmaPacket private
Definition at line 83 of file i8254xGBe.hh.
Referenced by rxStateMachine().
rxFifo
PacketFifo IGbE::rxFifo private
Definition at line 71 of file i8254xGBe.hh.
Referenced by ethRxPkt(), IGbE(), rxStateMachine(), serialize(), unserialize(), and write().
rxTick
bool IGbE::rxTick private
Definition at line 79 of file i8254xGBe.hh.
Referenced by checkDrain(), drain(), drainResume(), IGbE::RxDescCache::enableSm(), ethRxPkt(), IGbE::RxDescCache::fetchAfterWb(), restartClock(), rxStateMachine(), tick(), unserialize(), and write().
rxWriteDelay
Tick IGbE::rxWriteDelay private
Definition at line 91 of file i8254xGBe.hh.
Referenced by IGbE::RxDescCache::writePacket().
tadvEvent
EventFunctionWrapper IGbE::tadvEvent private
Definition at line 121 of file i8254xGBe.hh.
Referenced by cpuPostInt(), IGbE(), IGbE::TxDescCache::pktComplete(), serialize(), and unserialize().
tickEvent
EventFunctionWrapper IGbE::tickEvent private
Definition at line 134 of file i8254xGBe.hh.
Referenced by drain(), ethRxPkt(), IGbE(), restartClock(), and tick().
tidvEvent
EventFunctionWrapper IGbE::tidvEvent private
Definition at line 130 of file i8254xGBe.hh.
Referenced by cpuPostInt(), IGbE(), IGbE::TxDescCache::pktComplete(), serialize(), and unserialize().
txDescCache
TxDescCache IGbE::txDescCache private
Definition at line 509 of file i8254xGBe.hh.
Referenced by checkDrain(), drain(), ethTxDone(), IGbE(), serialize(), tadvProcess(), tidvProcess(), txStateMachine(), unserialize(), and write().
txFifo
PacketFifo IGbE::txFifo private
Definition at line 72 of file i8254xGBe.hh.
Referenced by IGbE(), serialize(), txStateMachine(), txWire(), and unserialize().
txFifoTick
bool IGbE::txFifoTick private
Definition at line 81 of file i8254xGBe.hh.
Referenced by checkDrain(), drain(), drainResume(), ethTxDone(), restartClock(), tick(), txStateMachine(), txWire(), and unserialize().
txPacket
EthPacketPtr IGbE::txPacket private
Definition at line 75 of file i8254xGBe.hh.
Referenced by serialize(), txStateMachine(), and unserialize().
txReadDelay
Tick IGbE::txReadDelay private
Definition at line 91 of file i8254xGBe.hh.
Referenced by IGbE::TxDescCache::getPacketData().
txTick
bool IGbE::txTick private
Definition at line 80 of file i8254xGBe.hh.
Referenced by checkDrain(), drain(), drainResume(), IGbE::TxDescCache::enableSm(), ethRxPkt(), ethTxDone(), IGbE::TxDescCache::fetchAfterWb(), restartClock(), tick(), txStateMachine(), unserialize(), and write().
wbCompDelay
Tick IGbE::wbCompDelay private
Definition at line 90 of file i8254xGBe.hh.
wbDelay
Tick IGbE::wbDelay private
Definition at line 89 of file i8254xGBe.hh.
The documentation for this class was generated from the following files:
dev/net/i8254xGBe.hh
dev/net/i8254xGBe.cc