gem5: ControlFlowInfo Class Reference
ControlFlowInfo Class Reference
#include <kernel_cfg.hh>
Static Public Member Functions
static void assignImmediatePostDominators (const std::vector< GPUStaticInst *> &instructions)
Compute immediate post-dominator instruction for kernel instructions.
Private Member Functions
ControlFlowInfo (const std::vector< GPUStaticInst *> &instructions)
GPUStaticInst * lastInstruction (const BasicBlock *block) const
BasicBlock * basicBlock (int inst_addr) const
BasicBlock * postDominator (const BasicBlock *block) const
void createBasicBlocks ()
void connectBasicBlocks ()
void findPostDominators ()
void findImmediatePostDominators ()
void printBasicBlocks () const
void printBasicBlockDot () const
void printPostDominators () const
void printImmediatePostDominators () const
Private Attributes
std::vector< std::unique_ptr< BasicBlock > > basicBlocks
std::vector< GPUStaticInst * > instructions
Detailed Description
Definition at line 94 of file kernel_cfg.hh.
Constructor & Destructor Documentation
ControlFlowInfo()
ControlFlowInfo::ControlFlowInfo (const std::vector< GPUStaticInst *> & instructions) private
Definition at line 58 of file kernel_cfg.cc.
References connectBasicBlocks(), and createBasicBlocks().
Member Function Documentation
assignImmediatePostDominators()
void ControlFlowInfo::assignImmediatePostDominators (const std::vector< GPUStaticInst *> & instructions) static
Compute immediate post-dominator instruction for kernel instructions.
Definition at line 50 of file kernel_cfg.cc.
References findImmediatePostDominators().
Referenced by HsailCode::init().
basicBlock()
BasicBlock * ControlFlowInfo::basicBlock (int inst_addr) const private
Definition at line 66 of file kernel_cfg.cc.
References basicBlocks, BasicBlock::firstInstruction, and GPUStaticInst::instAddr().
Referenced by connectBasicBlocks(), findImmediatePostDominators(), postDominator(), and printBasicBlocks().
connectBasicBlocks()
void ControlFlowInfo::connectBasicBlocks () private
Definition at line 131 of file kernel_cfg.cc.
References basicBlock(), basicBlocks, PowerISA::bb, GPUStaticInst::getTargetPc(), BasicBlock::id, GPUStaticInst::isBranch(), GPUStaticInst::isReturn(), GPUStaticInst::isUnconditionalJump(), lastInstruction(), and GPUStaticInst::nextInstAddr().
Referenced by ControlFlowInfo().
createBasicBlocks()
void ControlFlowInfo::createBasicBlocks () private
Definition at line 99 of file kernel_cfg.cc.
References basicBlocks, and instructions.
Referenced by ControlFlowInfo().
findImmediatePostDominators()
void ControlFlowInfo::findImmediatePostDominators () private
Definition at line 214 of file kernel_cfg.cc.
References basicBlock(), basicBlocks, findPostDominators(), BasicBlock::id, GPUStaticInst::instAddr(), GPUStaticInst::ipdInstNum(), BasicBlock::isExit(), lastInstruction(), BasicBlock::postDominatorIds, and setDifference().
Referenced by assignImmediatePostDominators().
findPostDominators()
void ControlFlowInfo::findPostDominators () private
Definition at line 170 of file kernel_cfg.cc.
References basicBlocks, ArmISA::i, intersect(), and ArmISA::s.
Referenced by findImmediatePostDominators().
lastInstruction()
GPUStaticInst * ControlFlowInfo::lastInstruction (const BasicBlock * block) const private
Definition at line 79 of file kernel_cfg.cc.
References BasicBlock::firstInstruction, GPUStaticInst::instNum(), instructions, BasicBlock::isExit(), and BasicBlock::size.
Referenced by connectBasicBlocks(), findImmediatePostDominators(), and postDominator().
postDominator()
BasicBlock * ControlFlowInfo::postDominator (const BasicBlock * block) const private
Definition at line 90 of file kernel_cfg.cc.
References basicBlock(), BasicBlock::isExit(), and lastInstruction().
Referenced by printImmediatePostDominators().
printBasicBlockDot()
void ControlFlowInfo::printBasicBlockDot () const private
Definition at line 284 of file kernel_cfg.cc.
References basicBlocks.
printBasicBlocks()
void ControlFlowInfo::printBasicBlocks () const private
Definition at line 270 of file kernel_cfg.cc.
References basicBlock(), BasicBlock::id, and instructions.
printImmediatePostDominators()
void ControlFlowInfo::printImmediatePostDominators () const private
Definition at line 258 of file kernel_cfg.cc.
References basicBlocks, and postDominator().
printPostDominators()
void ControlFlowInfo::printPostDominators () const private
Definition at line 246 of file kernel_cfg.cc.
References basicBlocks.
Member Data Documentation
basicBlocks
std::vector<std::unique_ptr<BasicBlock> > ControlFlowInfo::basicBlocks private
Definition at line 129 of file kernel_cfg.hh.
Referenced by basicBlock(), connectBasicBlocks(), createBasicBlocks(), findImmediatePostDominators(), findPostDominators(), printBasicBlockDot(), printImmediatePostDominators(), and printPostDominators().
instructions
std::vector<GPUStaticInst*> ControlFlowInfo::instructions private
Definition at line 130 of file kernel_cfg.hh.
Referenced by createBasicBlocks(), lastInstruction(), and printBasicBlocks().
The documentation for this class was generated from the following files:
gpu-compute/kernel_cfg.hh
gpu-compute/kernel_cfg.cc