gem5: ArmISA::TableWalker::DescriptorBase Class Reference
ArmISA::TableWalker::DescriptorBase Class Reference abstract
#include <table_walker.hh>
Public Member Functions
DescriptorBase ()
virtual Addr pfn () const =0
virtual TlbEntry::DomainType domain () const =0
virtual bool xn () const =0
virtual uint8_t ap () const =0
virtual bool global (WalkerState *currState) const =0
virtual uint8_t offsetBits () const =0
virtual bool secure (bool have_security, WalkerState *currState) const =0
virtual std::string dbgHeader () const =0
virtual uint64_t getRawData () const =0
virtual uint8_t texcb () const
virtual bool shareable () const
Public Attributes
LookupLevel lookupLevel
Current lookup level for this descriptor.
Detailed Description
Definition at line 69 of file table_walker.hh.
Constructor & Destructor Documentation
DescriptorBase()
ArmISA::TableWalker::DescriptorBase::DescriptorBase () inline
Definition at line 71 of file table_walker.hh.
Member Function Documentation
ap()
virtual uint8_t ArmISA::TableWalker::DescriptorBase::ap () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
dbgHeader()
virtual std::string ArmISA::TableWalker::DescriptorBase::dbgHeader () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
domain()
virtual TlbEntry::DomainType ArmISA::TableWalker::DescriptorBase::domain () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
getRawData()
virtual uint64_t ArmISA::TableWalker::DescriptorBase::getRawData () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
global()
virtual bool ArmISA::TableWalker::DescriptorBase::global (WalkerState * currState) const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
offsetBits()
virtual uint8_t ArmISA::TableWalker::DescriptorBase::offsetBits () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry(), ArmISA::TableWalker::LongDescriptor::paddr(), and ArmISA::TableWalker::LongDescriptor::pfn().
pfn()
virtual Addr ArmISA::TableWalker::DescriptorBase::pfn () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
secure()
virtual bool ArmISA::TableWalker::DescriptorBase::secure (bool have_security, WalkerState * currState) const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::haveLargeAsid64(), and ArmISA::TableWalker::insertTableEntry().
shareable()
virtual bool ArmISA::TableWalker::DescriptorBase::shareable () const inline virtual
Reimplemented in ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Definition at line 89 of file table_walker.hh.
References panic.
Referenced by ArmISA::TableWalker::insertTableEntry().
texcb()
virtual uint8_t ArmISA::TableWalker::DescriptorBase::texcb () const inline virtual
Reimplemented in ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Definition at line 85 of file table_walker.hh.
References panic.
Referenced by ArmISA::TableWalker::getTlb(), and ArmISA::TableWalker::insertTableEntry().
xn()
virtual bool ArmISA::TableWalker::DescriptorBase::xn () const pure virtual
Implemented in ArmISA::TableWalker::LongDescriptor, ArmISA::TableWalker::L2Descriptor, and ArmISA::TableWalker::L1Descriptor.
Referenced by ArmISA::TableWalker::insertTableEntry().
Member Data Documentation
lookupLevel
LookupLevel ArmISA::TableWalker::DescriptorBase::lookupLevel
Current lookup level for this descriptor.
Definition at line 74 of file table_walker.hh.
Referenced by ArmISA::TableWalker::LongDescriptor::dbgHeader(), ArmISA::TableWalker::doLongDescriptor(), ArmISA::TableWalker::doLongDescriptorWrapper(), ArmISA::TableWalker::generateLongDescFault(), ArmISA::TableWalker::insertTableEntry(), ArmISA::TableWalker::L1Descriptor::L1Descriptor(), ArmISA::TableWalker::L2Descriptor::L2Descriptor(), ArmISA::TableWalker::LongDescriptor::nextDescAddr(), ArmISA::TableWalker::LongDescriptor::offsetBits(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), and ArmISA::TableWalker::LongDescriptor::type().
The documentation for this class was generated from the following file:
arch/arm/table_walker.hh