gem5: CheckTable Class Reference
CheckTable Class Reference
#include <CheckTable.hh>
Public Member Functions
CheckTable (int _num_writers, int _num_readers, RubyTester *_tester)
~CheckTable ()
Check * getRandomCheck ()
Check * getCheck (Addr address)
void print (std::ostream &out) const
Private Member Functions
void addCheck (Addr address)
CheckTable (const CheckTable &obj)
CheckTable & operator= (const CheckTable &obj)
Private Attributes
std::vector< Check * > m_check_vector
std::unordered_map< Addr, Check * > m_lookup_map
int m_num_writers
int m_num_readers
RubyTester * m_tester_ptr
Detailed Description
Definition at line 42 of file CheckTable.hh.
Constructor & Destructor Documentation
CheckTable() [1/2]
CheckTable::CheckTable (int _num_writers, int _num_readers, RubyTester * _tester)
Definition at line 38 of file CheckTable.cc.
References addCheck(), CHECK_SIZE, DPRINTF, and ArmISA::i.
~CheckTable()
CheckTable::~CheckTable ()
Definition at line 75 of file CheckTable.cc.
References ArmISA::i, and m_check_vector.
CheckTable() [2/2]
CheckTable::CheckTable (const CheckTable & obj) private
Member Function Documentation
addCheck()
void CheckTable::addCheck (Addr address) private
Definition at line 83 of file CheckTable.cc.
References bitSelect(), CHECK_SIZE, CHECK_SIZE_BITS, DPRINTF, floorLog2(), ArmISA::i, m_check_vector, m_lookup_map, m_num_readers, m_num_writers, m_tester_ptr, and panic.
Referenced by CheckTable().
getCheck()
Check * CheckTable::getCheck (Addr address)
Definition at line 118 of file CheckTable.cc.
References DPRINTF, ArmISA::i, and m_lookup_map.
Referenced by RubyTester::hitCallback().
getRandomCheck()
Check * CheckTable::getRandomCheck ()
Definition at line 111 of file CheckTable.cc.
References m_check_vector, Random::random(), and random_mt.
Referenced by RubyTester::wakeup().
operator=()
CheckTable& CheckTable::operator= (const CheckTable & obj) private
print()
void CheckTable::print (std::ostream & out) const
Definition at line 133 of file CheckTable.cc.
Referenced by operator<<().
Member Data Documentation
m_check_vector
std::vector<Check*> CheckTable::m_check_vector private
Definition at line 65 of file CheckTable.hh.
Referenced by addCheck(), getRandomCheck(), and ~CheckTable().
m_lookup_map
std::unordered_map<Addr, Check*> CheckTable::m_lookup_map private
Definition at line 66 of file CheckTable.hh.
Referenced by addCheck(), and getCheck().
m_num_readers
int CheckTable::m_num_readers private
Definition at line 69 of file CheckTable.hh.
Referenced by addCheck().
m_num_writers
int CheckTable::m_num_writers private
Definition at line 68 of file CheckTable.hh.
Referenced by addCheck().
m_tester_ptr
RubyTester* CheckTable::m_tester_ptr private
Definition at line 70 of file CheckTable.hh.
Referenced by addCheck().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/CheckTable.hh
cpu/testers/rubytest/CheckTable.cc