gem5: MathExpr Class Reference
MathExpr Class Reference
#include <mathexpr.hh>
Classes
class Node
struct OpSearch
Public Types
typedef std::function< double(std::string)> EvalCallback
Public Member Functions
MathExpr (std::string expr)
std::string toStr () const
Prints an ASCII representation of the expression tree.
double eval (EvalCallback fn) const
Evaluates the expression.
Private Types
enum Operator {
bAdd, bSub, bMul, bDiv,
bPow, uNeg, sValue, sVariable,
nInvalid
}
typedef double(* binOp) (double, double)
Private Member Functions
Node * parse (std::string expr)
Parse and create nodes from string.
std::string toStr (Node *n, std::string prefix) const
Print tree as string.
double eval (const Node *n, EvalCallback fn) const
Eval a node.
Private Attributes
const int MAX_PRIO = 4
std::array< OpSearch, uNeg+1 > ops
Operator list.
Node * root
Root node.
Detailed Description
Definition at line 48 of file mathexpr.hh.
Member Typedef Documentation
binOp
typedef double(* MathExpr::binOp) (double, double) private
Definition at line 78 of file mathexpr.hh.
EvalCallback
typedef std::function<double(std::string)> MathExpr::EvalCallback
Definition at line 53 of file mathexpr.hh.
Member Enumeration Documentation
Operator
enum MathExpr::Operator private
Enumerator
bAdd
bSub
bMul
bDiv
bPow
uNeg
sValue
sVariable
nInvalid
Definition at line 72 of file mathexpr.hh.
Constructor & Destructor Documentation
MathExpr()
MathExpr::MathExpr (std::string expr)
Definition at line 49 of file mathexpr.cc.
References ArmISA::a, ArmISA::b, bAdd, bDiv, bMul, bPow, bSub, panic_if, parse(), root, and uNeg.
Member Function Documentation
eval() [1/2]
double MathExpr::eval (EvalCallback fn) const inline
Evaluates the expression.
Parameters
fn A callback funcion to evaluate variables
Returns
The value for this expression
Definition at line 69 of file mathexpr.hh.
References eval(), and root.
Referenced by eval(), and MathExprPowerModel::tryEval().
eval() [2/2]
double MathExpr::eval (const Node * n, EvalCallback fn) const private
Eval a node.
Definition at line 152 of file mathexpr.cc.
References eval(), ArmISA::fn, MathExpr::Node::l, MathExpr::Node::op, ops, panic, MathExpr::Node::r, sValue, sVariable, MathExpr::Node::value, and MathExpr::Node::variable.
parse()
MathExpr::Node * MathExpr::parse (std::string expr) private
Parse and create nodes from string.
This function parses a string expression into an expression tree.
It will look for operators in priority order to recursively build the tree, respecting parenthesization. Constants can be expressed in any format accepted by std::stod, whereas variables are essentially [A-Za-z0-9.$\]+
Definition at line 77 of file mathexpr.cc.
References ArmISA::c, ArmISA::i, MathExpr::Node::l, MipsISA::l, MAX_PRIO, ArmISA::n, MathExpr::Node::op, ops, MipsISA::p, MipsISA::r, MathExpr::Node::r, sValue, sVariable, ArmISA::v, MathExpr::Node::value, and MathExpr::Node::variable.
Referenced by MathExpr().
toStr() [1/2]
std::string MathExpr::toStr () const inline
Prints an ASCII representation of the expression tree.
Returns
A string containing the ASCII representation of the expression
Definition at line 60 of file mathexpr.hh.
References root, and toStr().
Referenced by MathExprPowerModel::eval(), and toStr().
toStr() [2/2]
std::string MathExpr::toStr (Node * n, std::string prefix) const private
Print tree as string.
Definition at line 169 of file mathexpr.cc.
References MathExpr::Node::l, MathExpr::Node::r, toStr(), and MathExpr::Node::toStr().
Member Data Documentation
MAX_PRIO
const int MathExpr::MAX_PRIO = 4 private
Definition at line 77 of file mathexpr.hh.
Referenced by parse().
ops
std::array<OpSearch, uNeg + 1> MathExpr::ops private
Operator list.
Definition at line 88 of file mathexpr.hh.
Referenced by eval(), and parse().
root
Node* MathExpr::root private
Root node.
Definition at line 114 of file mathexpr.hh.
Referenced by eval(), MathExpr(), and toStr().
The documentation for this class was generated from the following files:
sim/mathexpr.hh
sim/mathexpr.cc