gem5: DRAMSim2 Class Reference
DRAMSim2 Class Reference
#include <dramsim2.hh>
Classes
class MemoryPort
The memory port has to deal with its own flow control to avoid having unbounded storage that is implicitly created in the port itself.
Public Types
typedef DRAMSim2Params Params
Public Types inherited from AbstractMemory
typedef AbstractMemoryParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
DRAMSim2 (const Params *p)
void readComplete (unsigned id, uint64_t addr, uint64_t cycle)
Read completion callback.
void writeComplete (unsigned id, uint64_t addr, uint64_t cycle)
Write completion callback.
DrainState drain () override
Notify an object that it needs to drain its state.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void init () override
Initialise this memory.
void startup () override
startup() is the final initialization call before simulation.
Public Member Functions inherited from AbstractMemory
AbstractMemory (const Params *p)
virtual ~AbstractMemory ()
bool isNull () const
See if this is a null memory that should never store data and always return zero.
void setBackingStore (uint8_t *pmem_addr)
Set the host memory backing store to be used by this memory controller.
const std::list< LockedAddr > & getLockedAddrList () const
Get the list of locked addresses to allow checkpointing.
void addLockedAddr (LockedAddr addr)
Add a locked address to allow for checkpointing.
System * system () const
read the system pointer Implemented for completeness with the setter
void system (System *sys)
Set the system pointer on this memory This can't be done via a python parameter because the system needs pointers to all the memories and the reverse would create a cycle in the object graph.
const Params * params () const
AddrRange getAddrRange () const
Get the address range.
uint64_t size () const
Get the memory size.
Addr start () const
Get the start address.
bool isConfReported () const
Should this memory be passed to the kernel and part of the OS physical memory layout.
bool isInAddrMap () const
Some memories are used as shadow memories or should for other reasons not be part of the global address map.
bool isKvmMap () const
When shadow memories are in use, KVM may want to make one or the other, but cannot map both into the guest address space.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
Tick recvAtomic (PacketPtr pkt)
void recvFunctional (PacketPtr pkt)
bool recvTimingReq (PacketPtr pkt)
void recvRespRetry ()
Protected Member Functions inherited from AbstractMemory
bool checkLockedAddrList (PacketPtr pkt)
void trackLoadLocked (PacketPtr pkt)
bool writeOK (PacketPtr pkt)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Private Member Functions
unsigned int nbrOutstanding () const
void accessAndRespond (PacketPtr pkt)
When a packet is ready, use the "access()" method in AbstractMemory to actually create the response packet, and send it back to the outside world requestor.
void sendResponse ()
void tick ()
Progress the controller one clock cycle.
Private Attributes
MemoryPort port
DRAMSim2Wrapper wrapper
The actual DRAMSim2 wrapper.
bool retryReq
Is the connected port waiting for a retry from us.
bool retryResp
Are we waiting for a retry for sending a response.
Tick startTick
Keep track of when the wrapper is started.
std::unordered_map< Addr, std::queue< PacketPtr > > outstandingReads
Keep track of what packets are outstanding per address, and do so separately for reads and writes.
std::unordered_map< Addr, std::queue< PacketPtr > > outstandingWrites
unsigned int nbrOutstandingReads
Count the number of outstanding transactions so that we can block any further requests until there is space in DRAMSim2 and the sending queue we need to buffer the response packets.
unsigned int nbrOutstandingWrites
std::deque< PacketPtr > responseQueue
Queue to hold response packets until we can send them back.
EventFunctionWrapper sendResponseEvent
Event to schedule sending of responses.
EventFunctionWrapper tickEvent
Event to schedule clock ticks.
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from AbstractMemory
AddrRange range
uint8_t * pmemAddr
MemBackdoor backdoor
const bool confTableReported
const bool inAddrMap
const bool kvmMap
std::list< LockedAddr > lockedAddrList
System * _system
Pointer to the System object.
AbstractMemory::MemStats stats
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 55 of file dramsim2.hh.
Member Typedef Documentation
Params
typedef DRAMSim2Params DRAMSim2::Params
Definition at line 171 of file dramsim2.hh.
Constructor & Destructor Documentation
DRAMSim2()
DRAMSim2::DRAMSim2 (const Params * p)
Definition at line 49 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), DPRINTF, SimObject::name(), DRAMSim2Wrapper::printStats(), DRAMSim2Wrapper::queueSize(), readComplete(), registerExitCallback(), sendResponse(), DRAMSim2Wrapper::setCallbacks(), tick(), tickEvent, wrapper, and writeComplete().
Referenced by DRAMSim2::MemoryPort::recvRespRetry().
Member Function Documentation
accessAndRespond()
void DRAMSim2::accessAndRespond (PacketPtr pkt) private
When a packet is ready, use the "access()" method in AbstractMemory to actually create the response packet, and send it back to the outside world requestor.
Parameters
pkt The packet from the outside world
Definition at line 251 of file dramsim2.cc.
References AbstractMemory::access(), curTick(), DPRINTF, Packet::getAddr(), Packet::headerDelay, Packet::isResponse(), Packet::needsResponse(), Packet::payloadDelay, pendingDelete, responseQueue, retryResp, EventManager::schedule(), Event::scheduled(), and sendResponseEvent.
Referenced by readComplete(), and recvTimingReq().
drain()
DrainState DRAMSim2::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 350 of file dramsim2.cc.
References Drained, Draining, and nbrOutstanding().
getPort()
Port & DRAMSim2::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 340 of file dramsim2.cc.
References SimObject::getPort(), and port.
init()
void DRAMSim2::init () override virtual
Initialise this memory.
Reimplemented from AbstractMemory.
Definition at line 79 of file dramsim2.cc.
References DRAMSim2Wrapper::burstSize(), System::cacheLineSize(), fatal, AbstractMemory::init(), Port::isConnected(), SimObject::name(), port, SlavePort::sendRangeChange(), AbstractMemory::system(), and wrapper.
nbrOutstanding()
unsigned int DRAMSim2::nbrOutstanding () const private
Definition at line 134 of file dramsim2.cc.
References nbrOutstandingReads, nbrOutstandingWrites, and responseQueue.
Referenced by drain(), recvTimingReq(), sendResponse(), tick(), and writeComplete().
readComplete()
void DRAMSim2::readComplete (unsigned id, uint64_t addr, uint64_t cycle)
Read completion callback.
Parameters
id Channel id of the responder
addr Address of the request
cycle Internal cycle count of DRAMSim2
Definition at line 287 of file dramsim2.cc.
References accessAndRespond(), DRAMSim2Wrapper::clockPeriod(), curTick(), divCeil(), DPRINTF, nbrOutstandingReads, SimClock::Int::ns, outstandingReads, MipsISA::p, startTick, and wrapper.
Referenced by DRAMSim2().
recvAtomic()
Tick DRAMSim2::recvAtomic (PacketPtr pkt) protected
Definition at line 155 of file dramsim2.cc.
References AbstractMemory::access(), and Packet::cacheResponding().
recvFunctional()
void DRAMSim2::recvFunctional (PacketPtr pkt) protected
Definition at line 164 of file dramsim2.cc.
References AbstractMemory::functionalAccess(), ArmISA::i, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), responseQueue, and Packet::trySatisfyFunctional().
recvRespRetry()
void DRAMSim2::recvRespRetry () protected
Definition at line 241 of file dramsim2.cc.
References DPRINTF, retryResp, and sendResponse().
recvTimingReq()
bool DRAMSim2::recvTimingReq (PacketPtr pkt) protected
Definition at line 178 of file dramsim2.cc.
References accessAndRespond(), Packet::cacheResponding(), DRAMSim2Wrapper::canAccept(), DPRINTF, DRAMSim2Wrapper::enqueue(), Packet::getAddr(), Packet::isRead(), Packet::isWrite(), nbrOutstanding(), nbrOutstandingReads, nbrOutstandingWrites, outstandingReads, outstandingWrites, pendingDelete, DRAMSim2Wrapper::queueSize(), retryReq, and wrapper.
sendResponse()
void DRAMSim2::sendResponse () private
Definition at line 104 of file dramsim2.cc.
References curTick(), DPRINTF, nbrOutstanding(), nbrOutstandingReads, nbrOutstandingWrites, port, responseQueue, retryResp, EventManager::schedule(), Event::scheduled(), sendResponseEvent, SlavePort::sendTimingResp(), and Drainable::signalDrainDone().
Referenced by DRAMSim2(), and recvRespRetry().
startup()
void DRAMSim2::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 95 of file dramsim2.cc.
References Clocked::clockEdge(), curTick(), EventManager::schedule(), startTick, and tickEvent.
tick()
void DRAMSim2::tick () private
Progress the controller one clock cycle.
Definition at line 140 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), curTick(), nbrOutstanding(), SimClock::Int::ns, port, DRAMSim2Wrapper::queueSize(), retryReq, EventManager::schedule(), SlavePort::sendRetryReq(), DRAMSim2Wrapper::tick(), tickEvent, and wrapper.
Referenced by DRAMSim2().
writeComplete()
void DRAMSim2::writeComplete (unsigned id, uint64_t addr, uint64_t cycle)
Write completion callback.
Parameters
id Channel id of the responder
addr Address of the request
cycle Internal cycle count of DRAMSim2
Definition at line 315 of file dramsim2.cc.
References DRAMSim2Wrapper::clockPeriod(), curTick(), divCeil(), DPRINTF, nbrOutstanding(), nbrOutstandingWrites, SimClock::Int::ns, outstandingWrites, MipsISA::p, Drainable::signalDrainDone(), startTick, and wrapper.
Referenced by DRAMSim2().
Member Data Documentation
nbrOutstandingReads
unsigned int DRAMSim2::nbrOutstandingReads private
Count the number of outstanding transactions so that we can block any further requests until there is space in DRAMSim2 and the sending queue we need to buffer the response packets.
Definition at line 125 of file dramsim2.hh.
Referenced by nbrOutstanding(), readComplete(), recvTimingReq(), and sendResponse().
nbrOutstandingWrites
unsigned int DRAMSim2::nbrOutstandingWrites private
Definition at line 126 of file dramsim2.hh.
Referenced by nbrOutstanding(), recvTimingReq(), sendResponse(), and writeComplete().
outstandingReads
std::unordered_map<Addr, std::queue<PacketPtr> > DRAMSim2::outstandingReads private
Keep track of what packets are outstanding per address, and do so separately for reads and writes.
This is done so that we can return the right packet on completion from DRAMSim.
Definition at line 117 of file dramsim2.hh.
Referenced by readComplete(), and recvTimingReq().
outstandingWrites
std::unordered_map<Addr, std::queue<PacketPtr> > DRAMSim2::outstandingWrites private
Definition at line 118 of file dramsim2.hh.
Referenced by recvTimingReq(), and writeComplete().
pendingDelete
std::unique_ptr<Packet> DRAMSim2::pendingDelete private
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Definition at line 167 of file dramsim2.hh.
Referenced by accessAndRespond(), and recvTimingReq().
port
MemoryPort DRAMSim2::port private
Definition at line 89 of file dramsim2.hh.
Referenced by getPort(), init(), sendResponse(), and tick().
responseQueue
std::deque<PacketPtr> DRAMSim2::responseQueue private
Queue to hold response packets until we can send them back.
This is needed as DRAMSim2 unconditionally passes responses back without any flow control.
Definition at line 133 of file dramsim2.hh.
Referenced by accessAndRespond(), nbrOutstanding(), recvFunctional(), and sendResponse().
retryReq
bool DRAMSim2::retryReq private
Is the connected port waiting for a retry from us.
Definition at line 99 of file dramsim2.hh.
Referenced by recvTimingReq(), and tick().
retryResp
bool DRAMSim2::retryResp private
Are we waiting for a retry for sending a response.
Definition at line 104 of file dramsim2.hh.
Referenced by accessAndRespond(), recvRespRetry(), and sendResponse().
sendResponseEvent
EventFunctionWrapper DRAMSim2::sendResponseEvent private
Event to schedule sending of responses.
Definition at line 151 of file dramsim2.hh.
Referenced by accessAndRespond(), and sendResponse().
startTick
Tick DRAMSim2::startTick private
Keep track of when the wrapper is started.
Definition at line 109 of file dramsim2.hh.
Referenced by readComplete(), startup(), and writeComplete().
tickEvent
EventFunctionWrapper DRAMSim2::tickEvent private
Event to schedule clock ticks.
Definition at line 161 of file dramsim2.hh.
Referenced by DRAMSim2(), startup(), and tick().
wrapper
DRAMSim2Wrapper DRAMSim2::wrapper private
The actual DRAMSim2 wrapper.
Definition at line 94 of file dramsim2.hh.
Referenced by DRAMSim2(), init(), readComplete(), recvTimingReq(), tick(), and writeComplete().
The documentation for this class was generated from the following files:
mem/dramsim2.hh
mem/dramsim2.cc