gem5: ArmISA::DTLBIMVA Class Reference
ArmISA::DTLBIMVA Class Reference
Data TLB Invalidate by VA.
#include <tlbi_op.hh>
Public Member Functions
DTLBIMVA (ExceptionLevel _targetEL, bool _secure, Addr _addr, uint16_t _asid)
void broadcast (ThreadContext *tc)=delete
void operator() (ThreadContext *tc) override
Public Member Functions inherited from ArmISA::TLBIOp
TLBIOp (ExceptionLevel _targetEL, bool _secure)
virtual ~TLBIOp ()
void broadcast (ThreadContext *tc)
Broadcast the TLB Invalidate operation to all TLBs in the Arm system.
Protected Attributes
Addr addr
uint16_t asid
Protected Attributes inherited from ArmISA::TLBIOp
bool secureLookup
ExceptionLevel targetEL
Detailed Description
Data TLB Invalidate by VA.
Definition at line 229 of file tlbi_op.hh.
Constructor & Destructor Documentation
DTLBIMVA()
ArmISA::DTLBIMVA::DTLBIMVA (ExceptionLevel _targetEL, bool _secure, Addr _addr, uint16_t _asid) inline
Definition at line 232 of file tlbi_op.hh.
References ArmISA::TLBIOp::broadcast(), and ArmISA::TLBIOp::operator()().
Member Function Documentation
broadcast()
void ArmISA::DTLBIMVA::broadcast (ThreadContext * tc) delete
operator()()
void ArmISA::DTLBIMVA::operator() (ThreadContext * tc) override virtual
Reimplemented from ArmISA::TLBIOp.
Definition at line 150 of file tlbi_op.cc.
References addr, ArmISA::asid, ArmISA::TLB::flushMvaAsid(), ArmISA::getDTBPtr(), ArmISA::TLBIOp::secureLookup, and ArmISA::TLBIOp::targetEL.
Member Data Documentation
addr
Addr ArmISA::DTLBIMVA::addr protected
Definition at line 242 of file tlbi_op.hh.
asid
uint16_t ArmISA::DTLBIMVA::asid protected
Definition at line 243 of file tlbi_op.hh.
The documentation for this class was generated from the following files:
arch/arm/tlbi_op.hh
arch/arm/tlbi_op.cc