gem5: BaseO3DynInst< Impl > Class Template Reference
BaseO3DynInst< Impl > Class Template Reference
#include <dyn_inst.hh>
Public Types
enum { MaxInstSrcRegs = TheISA::MaxInstSrcRegs, MaxInstDestRegs = TheISA::MaxInstDestRegs }
typedef Impl::O3CPU O3CPU
Typedef for the CPU.
typedef TheISA::MachInst MachInst
Binary machine instruction type.
using VecRegContainer = TheISA::VecRegContainer
Register types.
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Public Types inherited from BaseDynInst< Impl >
enum { MaxInstSrcRegs = TheISA::MaxInstSrcRegs, MaxInstDestRegs = TheISA::MaxInstDestRegs }
typedef Impl::CPUType ImplCPU
typedef ImplCPU::ImplState ImplState
using VecRegContainer = TheISA::VecRegContainer
using LSQRequestPtr = typename Impl::CPUPol::LSQ::LSQRequest *
using LQIterator = typename Impl::CPUPol::LSQUnit::LQIterator
using SQIterator = typename Impl::CPUPol::LSQUnit::SQIterator
typedef Impl::DynInstPtr DynInstPtr
typedef RefCountingPtr< BaseDynInst< Impl > > BaseDynInstPtr
typedef std::list< DynInstPtr >::iterator ListIt
Public Types inherited from ExecContext
typedef TheISA::PCState PCState
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Public Member Functions
BaseO3DynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, O3CPU *cpu)
BaseDynInst constructor given a binary instruction.
BaseO3DynInst (const StaticInstPtr &_staticInst, const StaticInstPtr &_macroop)
BaseDynInst constructor given a static inst pointer.
~BaseO3DynInst ()
Fault execute ()
Executes the instruction.
Fault initiateAcc ()
Initiates the access.
Fault completeAcc (PacketPtr pkt)
Completes the access.
RegVal readMiscReg (int misc_reg) override
Reads a misc.
void setMiscReg (int misc_reg, RegVal val) override
Sets a misc.
RegVal readMiscRegOperand (const StaticInst *si, int idx) override
Reads a misc.
void setMiscRegOperand (const StaticInst *si, int idx, RegVal val) override
Sets a misc.
void updateMiscRegs ()
Called at the commit stage to update the misc.
void forwardOldRegs ()
void trap (const Fault &fault)
Traps to handle specified fault.
void syscall (int64_t callnum, Fault *fault) override
Emulates a syscall.
RegVal readIntRegOperand (const StaticInst *si, int idx) override
Reads an integer register.
RegVal readFloatRegOperandBits (const StaticInst *si, int idx) override
Reads a floating point register in its binary format, instead of by value.
const VecRegContainer & readVecRegOperand (const StaticInst *si, int idx) const override
Vector Register Interfaces.
VecRegContainer & getWritableVecRegOperand (const StaticInst *si, int idx) override
Read destination vector register operand for modification.
VecElem readVecElemOperand (const StaticInst *si, int idx) const override
Vector Elem Interfaces.
const VecPredRegContainer & readVecPredRegOperand (const StaticInst *si, int idx) const override
Predicate registers interface.
VecPredRegContainer & getWritableVecPredRegOperand (const StaticInst *si, int idx) override
Gets destination predicate register operand for modification.
RegVal readCCRegOperand (const StaticInst *si, int idx) override
void setIntRegOperand (const StaticInst *si, int idx, RegVal val) override
void setFloatRegOperandBits (const StaticInst *si, int idx, RegVal val) override
Records an fp register being set to an integer value.
void setVecRegOperand (const StaticInst *si, int idx, const VecRegContainer &val) override
Record a vector register being set to a value.
void setVecElemOperand (const StaticInst *si, int idx, const VecElem val) override
Record a vector register being set to a value.
void setVecPredRegOperand (const StaticInst *si, int idx, const VecPredRegContainer &val) override
Record a vector register being set to a value.
void setCCRegOperand (const StaticInst *si, int idx, RegVal val) override
Records a CC register being set to a value.
ConstVecLane8 readVec8BitLaneOperand (const StaticInst *si, int idx) const override
Vector Register Lane Interfaces.
ConstVecLane16 readVec16BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 16bit operand.
ConstVecLane32 readVec32BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 32bit operand.
ConstVecLane64 readVec64BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 64bit operand.
template<typename LD >
void setVecLaneOperandT (const StaticInst *si, int idx, const LD &val)
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::TwoByte > &val) override
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::FourByte > &val) override
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::EightByte > &val) override
Public Member Functions inherited from BaseDynInst< Impl >
BaseCPU * getCpuPtr ()
void recordResult (bool f)
Records changes to result?
bool effAddrValid () const
Is the effective virtual address valid.
void effAddrValid (bool b)
bool memOpDone () const
Whether or not the memory operation is done.
void memOpDone (bool f)
bool notAnInst () const
void setNotAnInst ()
void demapPage (Addr vaddr, uint64_t asn)
Invalidate a page in the DTLB and ITLB.
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
Fault initiateMemRead (Addr addr, unsigned size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Fault writeMem (uint8_t *data, unsigned size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >())
Fault initiateMemAMO (Addr addr, unsigned size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
bool translationStarted () const
True if the DTB address translation has started.
void translationStarted (bool f)
bool translationCompleted () const
True if the DTB address translation has completed.
void translationCompleted (bool f)
bool possibleLoadViolation () const
True if this address was found to match a previous load and they issued out of order.
void possibleLoadViolation (bool f)
bool hitExternalSnoop () const
True if the address hit a external snoop while sitting in the LSQ.
void hitExternalSnoop (bool f)
bool isTranslationDelayed () const
Returns true if the DTB address translation is being delayed due to a hw page table walk.
PhysRegIdPtr renamedDestRegIdx (int idx) const
Returns the physical register index of the i'th destination register.
PhysRegIdPtr renamedSrcRegIdx (int idx) const
Returns the physical register index of the i'th source register.
const RegId & flattenedDestRegIdx (int idx) const
Returns the flattened register index of the i'th destination register.
PhysRegIdPtr prevDestRegIdx (int idx) const
Returns the physical register index of the previous physical register that remapped to the same logical register index.
void renameDestReg (int idx, PhysRegIdPtr renamed_dest, PhysRegIdPtr previous_rename)
Renames a destination register to a physical register.
void renameSrcReg (int idx, PhysRegIdPtr renamed_src)
Renames a source logical register to the physical register which has/will produce that logical register's result.
void flattenDestReg (int idx, const RegId &flattened_dest)
Flattens a destination architectural register index into a logical index.
BaseDynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, ImplCPU *cpu)
BaseDynInst constructor given a binary instruction.
BaseDynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop)
BaseDynInst constructor given a StaticInst pointer.
~BaseDynInst ()
BaseDynInst destructor.
void dump ()
Dumps out contents of this BaseDynInst.
void dump (std::string &outstring)
Dumps out contents of this BaseDynInst into given string.
int cpuId () const
Read this CPU's ID.
uint32_t socketId () const
Read this CPU's Socket ID.
MasterID masterId () const
Read this CPU's data requestor ID.
ContextID contextId () const
Read this context's system-wide ID.
Fault getFault () const
Returns the fault type.
Fault & getFault ()
TODO: This I added for the LSQRequest side to be able to modify the fault.
bool doneTargCalc ()
Checks whether or not this instruction has had its branch target calculated yet.
void setPredTarg (const TheISA::PCState &_predPC)
Set the predicted target of this current instruction.
const TheISA::PCState & readPredTarg ()
Addr predInstAddr ()
Returns the predicted PC immediately after the branch.
Addr predNextInstAddr ()
Returns the predicted PC two instructions after the branch.
Addr predMicroPC ()
Returns the predicted micro PC after the branch.
bool readPredTaken ()
Returns whether the instruction was predicted taken or not.
void setPredTaken (bool predicted_taken)
bool mispredicted ()
Returns whether the instruction mispredicted.
bool isNop () const
bool isMemRef () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isStoreConditional () const
bool isInstPrefetch () const
bool isDataPrefetch () const
bool isInteger () const
bool isFloating () const
bool isVector () const
bool isControl () const
bool isCall () const
bool isReturn () const
bool isDirectCtrl () const
bool isIndirectCtrl () const
bool isCondCtrl () const
bool isUncondCtrl () const
bool isCondDelaySlot () const
bool isThreadSync () const
bool isSerializing () const
bool isSerializeBefore () const
bool isSerializeAfter () const
bool isSquashAfter () const
bool isMemBarrier () const
bool isWriteBarrier () const
bool isNonSpeculative () const
bool isQuiesce () const
bool isIprAccess () const
bool isUnverifiable () const
bool isSyscall () const
bool isMacroop () const
bool isMicroop () const
bool isDelayedCommit () const
bool isLastMicroop () const
bool isFirstMicroop () const
bool isMicroBranch () const
void setSerializeBefore ()
Temporarily sets this instruction as a serialize before instruction.
void clearSerializeBefore ()
Clears the serializeBefore part of this instruction.
bool isTempSerializeBefore ()
Checks if this serializeBefore is only temporarily set.
void setSerializeAfter ()
Temporarily sets this instruction as a serialize after instruction.
void clearSerializeAfter ()
Clears the serializeAfter part of this instruction.
bool isTempSerializeAfter ()
Checks if this serializeAfter is only temporarily set.
void setSerializeHandled ()
Sets the serialization part of this instruction as handled.
bool isSerializeHandled ()
Checks if the serialization part of this instruction has been handled.
OpClass opClass () const
Returns the opclass of this instruction.
TheISA::PCState branchTarget () const
Returns the branch target address.
int8_t numSrcRegs () const
Returns the number of source registers.
int8_t numDestRegs () const
Returns the number of destination registers.
int8_t numFPDestRegs () const
int8_t numIntDestRegs () const
int8_t numCCDestRegs () const
int8_t numVecDestRegs () const
int8_t numVecElemDestRegs () const
int8_t numVecPredDestRegs () const
const RegId & destRegIdx (int i) const
Returns the logical register index of the i'th destination register.
const RegId & srcRegIdx (int i) const
Returns the logical register index of the i'th source register.
uint8_t resultSize ()
Return the size of the instResult queue.
InstResult popResult (InstResult dflt=InstResult())
Pops a result off the instResult queue.
void markSrcRegReady ()
Records that one of the source registers is ready.
void markSrcRegReady (RegIndex src_idx)
Marks a specific register as ready.
bool isReadySrcRegIdx (int idx) const
Returns if a source register is ready.
void setCompleted ()
Sets this instruction as completed.
bool isCompleted () const
Returns whether or not this instruction is completed.
void setResultReady ()
Marks the result as ready.
bool isResultReady () const
Returns whether or not the result is ready.
void setCanIssue ()
Sets this instruction as ready to issue.
bool readyToIssue () const
Returns whether or not this instruction is ready to issue.
void clearCanIssue ()
Clears this instruction being able to issue.
void setIssued ()
Sets this instruction as issued from the IQ.
bool isIssued () const
Returns whether or not this instruction has issued.
void clearIssued ()
Clears this instruction as being issued.
void setExecuted ()
Sets this instruction as executed.
bool isExecuted () const
Returns whether or not this instruction has executed.
void setCanCommit ()
Sets this instruction as ready to commit.
void clearCanCommit ()
Clears this instruction as being ready to commit.
bool readyToCommit () const
Returns whether or not this instruction is ready to commit.
void setAtCommit ()
bool isAtCommit ()
void setCommitted ()
Sets this instruction as committed.
bool isCommitted () const
Returns whether or not this instruction is committed.
void setSquashed ()
Sets this instruction as squashed.
bool isSquashed () const
Returns whether or not this instruction is squashed.
void setInIQ ()
Sets this instruction as a entry the IQ.
void clearInIQ ()
Sets this instruction as a entry the IQ.
bool isInIQ () const
Returns whether or not this instruction has issued.
void setSquashedInIQ ()
Sets this instruction as squashed in the IQ.
bool isSquashedInIQ () const
Returns whether or not this instruction is squashed in the IQ.
void setInLSQ ()
Sets this instruction as a entry the LSQ.
void removeInLSQ ()
Sets this instruction as a entry the LSQ.
bool isInLSQ () const
Returns whether or not this instruction is in the LSQ.
void setSquashedInLSQ ()
Sets this instruction as squashed in the LSQ.
bool isSquashedInLSQ () const
Returns whether or not this instruction is squashed in the LSQ.
void setInROB ()
Sets this instruction as a entry the ROB.
void clearInROB ()
Sets this instruction as a entry the ROB.
bool isInROB () const
Returns whether or not this instruction is in the ROB.
void setSquashedInROB ()
Sets this instruction as squashed in the ROB.
bool isSquashedInROB () const
Returns whether or not this instruction is squashed in the ROB.
bool isPinnedRegsRenamed () const
Returns whether pinned registers are renamed.
void setPinnedRegsRenamed ()
Sets the destination registers as renamed.
bool isPinnedRegsWritten () const
Returns whether destination registers are written.
void setPinnedRegsWritten ()
Sets destination registers as written.
bool isPinnedRegsSquashDone () const
Return whether dest registers' pinning status updated after squash.
void setPinnedRegsSquashDone ()
Sets dest registers' status updated after squash.
TheISA::PCState pcState () const
Read the PC state of this instruction.
void pcState (const TheISA::PCState &val)
Set the PC state of this instruction.
Addr instAddr () const
Read the PC of this instruction.
Addr nextInstAddr () const
Read the PC of the next instruction.
Addr microPC () const
Read the micro PC of this instruction.
bool readPredicate () const
void setPredicate (bool val)
bool readMemAccPredicate () const
void setMemAccPredicate (bool val)
void setASID (short addr_space_id)
Sets the ASID.
short getASID ()
void setTid (ThreadID tid)
Sets the thread id.
void setThreadState (ImplState *state)
Sets the pointer to the thread state.
ThreadContext * tcBase ()
Returns the thread context.
bool eaSrcsReady () const
Returns whether or not the eff.
bool strictlyOrdered () const
Is this instruction's memory access strictly ordered?
void strictlyOrdered (bool so)
bool hasRequest () const
Has this instruction generated a memory request.
void setRequest ()
Assert this instruction has generated a memory request.
ListIt & getInstListIt ()
Returns iterator to this instruction in the list of all insts.
void setInstListIt (ListIt _instListIt)
Sets iterator for this instruction in the list of all insts.
unsigned int readStCondFailures () const
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int sc_failures)
Sets the number of consecutive store conditional failures.
void armMonitor (Addr address)
bool mwait (PacketPtr pkt)
void mwaitAtomic (ThreadContext *tc)
AddressMonitor * getAddrMonitor ()
template<typename T >
void setScalarResult (T &&t)
Pushes a result onto the instResult queue.
template<typename T >
void setVecResult (T &&t)
Full vector result.
template<typename T >
void setVecElemResult (T &&t)
Vector element result.
template<typename T >
void setVecPredResult (T &&t)
Predicate result.
Public Member Functions inherited from ExecContext
virtual Fault readMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Perform an atomic memory read operation.
virtual Fault initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Initiate a timing memory read operation.
virtual Fault writeMem (uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >())=0
For atomic-mode contexts, perform an atomic memory write operation.
virtual Fault amoMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
virtual Fault initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
Public Member Functions inherited from RefCounted
RefCounted ()
We initialize the reference count to zero and the first object to take ownership of it must increment it to one.
virtual ~RefCounted ()
We make the destructor virtual because we're likely to have virtual functions on reference counted objects.
void incref () const
Increment the reference count.
void decref () const
Decrement the reference count and destroy the object if all references are gone.
Static Public Attributes
static constexpr auto NumVecElemPerVecReg = TheISA::NumVecElemPerVecReg
Protected Attributes
std::array< RegVal, TheISA::MaxMiscDestRegs > _destMiscRegVal
Values to be written to the destination misc.
std::array< short, TheISA::MaxMiscDestRegs > _destMiscRegIdx
Indexes of the destination misc.
uint8_t _numDestMiscRegs
Number of destination misc.
Protected Attributes inherited from BaseDynInst< Impl >
std::queue< InstResult > instResult
The result of the instruction; assumes an instruction can have many destination registers.
TheISA::PCState pc
PC state for this instruction.
std::bitset< MaxInstSrcRegs > _readySrcRegIdx
Whether or not the source register is ready.
std::array< RegId, TheISA::MaxInstDestRegs > _flatDestRegIdx
Flattened register index of the destination registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstDestRegs > _destRegIdx
Physical register index of the destination registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstSrcRegs > _srcRegIdx
Physical register index of the source registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstDestRegs > _prevDestRegIdx
Physical register index of the previous producers of the architected destinations.
Private Member Functions
void initVars ()
Initializes variables.
Additional Inherited Members
Public Attributes inherited from BaseDynInst< Impl >
InstSeqNum seqNum
The sequence number of the instruction.
const StaticInstPtr staticInst
The StaticInst used by this BaseDynInst.
ImplCPU * cpu
Pointer to the Impl's CPU object.
ImplState * thread
Pointer to the thread state.
Fault fault
The kind of fault this instruction has generated.
Trace::InstRecord * traceData
InstRecord that tracks this instructions.
ThreadID threadNumber
The thread this instruction is from.
ListIt instListIt
Iterator pointing to this BaseDynInst in the list of all insts.
TheISA::PCState predPC
Predicted PC state after this instruction.
const StaticInstPtr macroop
The Macroop if one exists.
uint8_t readyRegs
How many source registers are ready.
Addr effAddr
The effective virtual address (lds & stores only).
Addr physEffAddr
The effective physical address.
unsigned memReqFlags
The memory request flags (from translation).
short asid
data address space ID, for loads & stores.
unsigned effSize
The size of the request.
uint8_t * memData
Pointer to the data for the memory access.
int16_t lqIdx
Load queue index.
LQIterator lqIt
int16_t sqIdx
Store queue index.
SQIterator sqIt
LSQRequestPtr savedReq
Saved memory request (needed when the DTB address translation is delayed due to a hw page table walk).
RequestPtr reqToVerify
Protected Types inherited from BaseDynInst< Impl >
enum Status {
IqEntry, RobEntry, LsqEntry, Completed,
ResultReady, CanIssue, Issued, Executed,
CanCommit, AtCommit, Committed, Squashed,
SquashedInIQ, SquashedInLSQ, SquashedInROB, PinnedRegsRenamed,
PinnedRegsWritten, PinnedRegsSquashDone, RecoverInst, BlockingInst,
ThreadsyncWait, SerializeBefore, SerializeAfter, SerializeHandled,
NumStatus
}
enum Flags {
NotAnInst, TranslationStarted, TranslationCompleted, PossibleLoadViolation,
HitExternalSnoop, EffAddrValid, RecordResult, Predicate,
MemAccPredicate, PredTaken, IsStrictlyOrdered, ReqMade,
MemOpDone, MaxFlags
}
Detailed Description
template<class Impl>
class BaseO3DynInst< Impl >
Definition at line 60 of file dyn_inst.hh.
Member Typedef Documentation
MachInst
template<class Impl > typedef TheISA::MachInst BaseO3DynInst< Impl >::MachInst
Binary machine instruction type.
Definition at line 67 of file dyn_inst.hh.
O3CPU
template<class Impl > typedef Impl::O3CPU BaseO3DynInst< Impl >::O3CPU
Typedef for the CPU.
Definition at line 64 of file dyn_inst.hh.
VecElem
template<class Impl > using BaseO3DynInst< Impl >::VecElem = TheISA::VecElem
Definition at line 70 of file dyn_inst.hh.
VecPredRegContainer
template<class Impl > using BaseO3DynInst< Impl >::VecPredRegContainer = TheISA::VecPredRegContainer
Definition at line 72 of file dyn_inst.hh.
VecRegContainer
template<class Impl > using BaseO3DynInst< Impl >::VecRegContainer = TheISA::VecRegContainer
Register types.
Definition at line 69 of file dyn_inst.hh.
Member Enumeration Documentation
anonymous enum
template<class Impl > anonymous enum
Enumerator
MaxInstSrcRegs
MaxInstDestRegs
Definition at line 74 of file dyn_inst.hh.
Constructor & Destructor Documentation
BaseO3DynInst() [1/2]
template<class Impl > BaseO3DynInst< Impl >::BaseO3DynInst (const StaticInstPtr & staticInst, const StaticInstPtr & macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, O3CPU * cpu)
BaseDynInst constructor given a binary instruction.
Definition at line 52 of file dyn_inst_impl.hh.
References BaseO3DynInst< Impl >::initVars().
BaseO3DynInst() [2/2]
template<class Impl > BaseO3DynInst< Impl >::BaseO3DynInst (const StaticInstPtr & _staticInst, const StaticInstPtr & _macroop)
BaseDynInst constructor given a static inst pointer.
Definition at line 62 of file dyn_inst_impl.hh.
References BaseO3DynInst< Impl >::initVars().
~BaseO3DynInst()
template<class Impl > BaseO3DynInst< Impl >::~BaseO3DynInst ()
Definition at line 69 of file dyn_inst_impl.hh.
References StaticInst::disassemble(), DPRINTFR, DTRACE, BaseDynInst< Impl >::instAddr(), BaseDynInst< Impl >::microPC(), BaseDynInst< Impl >::seqNum, BaseDynInst< Impl >::staticInst, and X86ISA::val.
Member Function Documentation
completeAcc()
template<class Impl > Fault BaseO3DynInst< Impl >::completeAcc (PacketPtr pkt)
Completes the access.
Only valid for memory operations.
Definition at line 165 of file dyn_inst_impl.hh.
References StaticInst::completeAcc(), BaseDynInst< Impl >::cpu, BaseDynInst< Impl >::fault, BaseDynInst< Impl >::isStoreConditional(), Packet::req, BaseDynInst< Impl >::reqToVerify, BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
execute()
template<class Impl > Fault BaseO3DynInst< Impl >::execute ()
Executes the instruction.
Definition at line 129 of file dyn_inst_impl.hh.
References StaticInst::execute(), BaseDynInst< Impl >::fault, BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
forwardOldRegs()
template<class Impl > void BaseO3DynInst< Impl >::forwardOldRegs () inline
Definition at line 210 of file dyn_inst.hh.
References CCRegClass, RegId::classValue(), BaseDynInst< Impl >::cpu, StaticInst::destRegIdx(), BaseDynInst< Impl >::fault, FloatRegClass, RefCountingPtr< T >::get(), IntRegClass, MiscRegClass, BaseDynInst< Impl >::numDestRegs(), panic, BaseDynInst< Impl >::prevDestRegIdx(), BaseO3DynInst< Impl >::setCCRegOperand(), BaseO3DynInst< Impl >::setFloatRegOperandBits(), BaseO3DynInst< Impl >::setIntRegOperand(), BaseO3DynInst< Impl >::setVecElemOperand(), BaseO3DynInst< Impl >::setVecPredRegOperand(), BaseO3DynInst< Impl >::setVecRegOperand(), BaseDynInst< Impl >::staticInst, BaseO3DynInst< Impl >::syscall(), BaseO3DynInst< Impl >::trap(), VecElemClass, VecPredRegClass, and VecRegClass.
getWritableVecPredRegOperand()
template<class Impl > VecPredRegContainer& BaseO3DynInst< Impl >::getWritableVecPredRegOperand (const StaticInst * si, int idx) inline override virtual
Gets destination predicate register operand for modification.
Implements ExecContext.
Definition at line 372 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
getWritableVecRegOperand()
template<class Impl > VecRegContainer& BaseO3DynInst< Impl >::getWritableVecRegOperand (const StaticInst * si, int idx) inline override virtual
Read destination vector register operand for modification.
Implements ExecContext.
Definition at line 292 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
initiateAcc()
template<class Impl > Fault BaseO3DynInst< Impl >::initiateAcc ()
Initiates the access.
Only valid for memory operations.
Definition at line 147 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::fault, StaticInst::initiateAcc(), BaseDynInst< Impl >::staticInst, BaseDynInst< Impl >::thread, and BaseDynInst< Impl >::traceData.
initVars()
template<class Impl > void BaseO3DynInst< Impl >::initVars () private
Initializes variables.
Definition at line 107 of file dyn_inst_impl.hh.
References BaseO3DynInst< Impl >::_numDestMiscRegs, and BaseDynInst< Impl >::_readySrcRegIdx.
Referenced by BaseO3DynInst< Impl >::BaseO3DynInst().
readCCRegOperand()
template<class Impl > RegVal BaseO3DynInst< Impl >::readCCRegOperand (const StaticInst * si, int idx) inline override virtual
Implements ExecContext.
Definition at line 378 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readFloatRegOperandBits()
template<class Impl > RegVal BaseO3DynInst< Impl >::readFloatRegOperandBits (const StaticInst * si, int idx) inline override virtual
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 277 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readIntRegOperand()
template<class Impl > RegVal BaseO3DynInst< Impl >::readIntRegOperand (const StaticInst * si, int idx) inline override virtual
Reads an integer register.
Implements ExecContext.
Definition at line 271 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readMiscReg()
template<class Impl > RegVal BaseO3DynInst< Impl >::readMiscReg (int misc_reg) inline override virtual
Reads a misc.
register, including any side-effects the read might have as defined by the architecture.
Implements ExecContext.
Definition at line 140 of file dyn_inst.hh.
References BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::threadNumber.
readMiscRegOperand()
template<class Impl > RegVal BaseO3DynInst< Impl >::readMiscRegOperand (const StaticInst * si, int idx) inline override virtual
Reads a misc.
register, including any side-effects the read might have as defined by the architecture.
Implements ExecContext.
Definition at line 174 of file dyn_inst.hh.
References BaseDynInst< Impl >::cpu, RegId::index(), RegId::isMiscReg(), X86ISA::reg, StaticInst::srcRegIdx(), and BaseDynInst< Impl >::threadNumber.
readVec16BitLaneOperand()
template<class Impl > ConstVecLane16 BaseO3DynInst< Impl >::readVec16BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 16bit operand.
Implements ExecContext.
Definition at line 308 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVec32BitLaneOperand()
template<class Impl > ConstVecLane32 BaseO3DynInst< Impl >::readVec32BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 32bit operand.
Implements ExecContext.
Definition at line 315 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVec64BitLaneOperand()
template<class Impl > ConstVecLane64 BaseO3DynInst< Impl >::readVec64BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 64bit operand.
Implements ExecContext.
Definition at line 322 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVec8BitLaneOperand()
template<class Impl > ConstVecLane8 BaseO3DynInst< Impl >::readVec8BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implements ExecContext.
Definition at line 301 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVecElemOperand()
template<class Impl > VecElem BaseO3DynInst< Impl >::readVecElemOperand (const StaticInst * si, int idx) const inline override virtual
Vector Elem Interfaces.
Reads an element of a vector register.
Implements ExecContext.
Definition at line 360 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVecPredRegOperand()
template<class Impl > const VecPredRegContainer& BaseO3DynInst< Impl >::readVecPredRegOperand (const StaticInst * si, int idx) const inline override virtual
Predicate registers interface.
Reads source predicate register operand.
Implements ExecContext.
Definition at line 366 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
readVecRegOperand()
template<class Impl > const VecRegContainer& BaseO3DynInst< Impl >::readVecRegOperand (const StaticInst * si, int idx) const inline override virtual
Vector Register Interfaces.
Reads source vector register operand.
Implements ExecContext.
Definition at line 283 of file dyn_inst.hh.
References BaseDynInst< Impl >::_srcRegIdx, and BaseDynInst< Impl >::cpu.
setCCRegOperand()
template<class Impl > void BaseO3DynInst< Impl >::setCCRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Records a CC register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 424 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setCCRegOperand().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
setFloatRegOperandBits()
template<class Impl > void BaseO3DynInst< Impl >::setFloatRegOperandBits (const StaticInst * si, int idx, RegVal val) inline override virtual
Records an fp register being set to an integer value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 394 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setFloatRegOperandBits().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
setIntRegOperand()
template<class Impl > void BaseO3DynInst< Impl >::setIntRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Todo:
: Make results into arrays so they can handle multiple dest registers.
Reimplemented from BaseDynInst< Impl >.
Definition at line 387 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setIntRegOperand().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
setMiscReg()
template<class Impl > void BaseO3DynInst< Impl >::setMiscReg (int misc_reg, RegVal val) inline override virtual
Sets a misc.
register, including any side-effects the write might have as defined by the architecture.
Writes to misc. registers are recorded and deferred until the commit stage, when updateMiscRegs() is called. First, check if the misc reg has been written before and update its value to be committed instead of making a new entry. If not, make a new entry and record the write.
Implements ExecContext.
Definition at line 149 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::_numDestMiscRegs, AlphaISA::MaxMiscDestRegs, and X86ISA::val.
Referenced by BaseO3DynInst< Impl >::setMiscRegOperand().
setMiscRegOperand()
template<class Impl > void BaseO3DynInst< Impl >::setMiscRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Sets a misc.
register, including any side-effects the write might have as defined by the architecture.
Implements ExecContext.
Definition at line 185 of file dyn_inst.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isMiscReg(), X86ISA::reg, BaseO3DynInst< Impl >::setMiscReg(), and X86ISA::val.
setVecElemOperand()
template<class Impl > void BaseO3DynInst< Impl >::setVecElemOperand (const StaticInst * si, int idx, const VecElem val) inline override virtual
Record a vector register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 408 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setVecElemOperand().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
setVecLaneOperand() [1/4]
template<class Impl > virtual void BaseO3DynInst< Impl >::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 335 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::setVecLaneOperandT().
setVecLaneOperand() [2/4]
template<class Impl > virtual void BaseO3DynInst< Impl >::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Implements ExecContext.
Definition at line 341 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::setVecLaneOperandT().
setVecLaneOperand() [3/4]
template<class Impl > virtual void BaseO3DynInst< Impl >::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::FourByte > & val) inline override virtual
Implements ExecContext.
Definition at line 347 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::setVecLaneOperandT().
setVecLaneOperand() [4/4]
template<class Impl > virtual void BaseO3DynInst< Impl >::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::EightByte > & val) inline override virtual
Implements ExecContext.
Definition at line 353 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::setVecLaneOperandT().
setVecLaneOperandT()
template<class Impl > template<typename LD > void BaseO3DynInst< Impl >::setVecLaneOperandT (const StaticInst * si, int idx, const LD & val) inline
Write a lane of the destination vector operand.
Definition at line 330 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, and BaseDynInst< Impl >::cpu.
Referenced by BaseO3DynInst< Impl >::setVecLaneOperand().
setVecPredRegOperand()
template<class Impl > void BaseO3DynInst< Impl >::setVecPredRegOperand (const StaticInst * si, int idx, const VecPredRegContainer & val) inline override virtual
Record a vector register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 417 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setVecPredRegOperand().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
setVecRegOperand()
template<class Impl > void BaseO3DynInst< Impl >::setVecRegOperand (const StaticInst * si, int idx, const VecRegContainer & val) inline override virtual
Record a vector register being set to a value.
Reimplemented from BaseDynInst< Impl >.
Definition at line 401 of file dyn_inst.hh.
References BaseDynInst< Impl >::_destRegIdx, BaseDynInst< Impl >::cpu, and BaseDynInst< Impl >::setVecRegOperand().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
syscall()
template<class Impl > void BaseO3DynInst< Impl >::syscall (int64_t callnum, Fault * fault) override virtual
Emulates a syscall.
Implements ExecContext.
Definition at line 196 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, FullSystem, panic, BaseDynInst< Impl >::pcState(), and BaseDynInst< Impl >::threadNumber.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
trap()
template<class Impl > void BaseO3DynInst< Impl >::trap (const Fault & fault)
Traps to handle specified fault.
Definition at line 189 of file dyn_inst_impl.hh.
References BaseDynInst< Impl >::cpu, BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::threadNumber.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
updateMiscRegs()
template<class Impl > void BaseO3DynInst< Impl >::updateMiscRegs () inline
Called at the commit stage to update the misc.
registers.
Definition at line 194 of file dyn_inst.hh.
References BaseO3DynInst< Impl >::_numDestMiscRegs, BaseDynInst< Impl >::cpu, ArmISA::i, and BaseDynInst< Impl >::thread.
Member Data Documentation
_destMiscRegIdx
template<class Impl > std::array<short, TheISA::MaxMiscDestRegs> BaseO3DynInst< Impl >::_destMiscRegIdx protected
Indexes of the destination misc.
registers. They are needed to defer the write accesses to the misc. registers until the commit stage, when the instruction is out of its speculative state.
Definition at line 117 of file dyn_inst.hh.
_destMiscRegVal
template<class Impl > std::array<RegVal, TheISA::MaxMiscDestRegs> BaseO3DynInst< Impl >::_destMiscRegVal protected
Values to be written to the destination misc.
registers.
Definition at line 111 of file dyn_inst.hh.
_numDestMiscRegs
template<class Impl > uint8_t BaseO3DynInst< Impl >::_numDestMiscRegs protected
Number of destination misc.
registers.
Definition at line 120 of file dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::initVars(), BaseO3DynInst< Impl >::setMiscReg(), and BaseO3DynInst< Impl >::updateMiscRegs().
NumVecElemPerVecReg
template<class Impl > constexpr auto BaseO3DynInst< Impl >::NumVecElemPerVecReg = TheISA::NumVecElemPerVecReg static
Definition at line 71 of file dyn_inst.hh.
The documentation for this class was generated from the following files:
cpu/o3/dyn_inst.hh
cpu/o3/dyn_inst_impl.hh