gem5: LSQ< Impl > Class Template Reference
LSQ< Impl > Class Template Reference
#include <lsq.hh>
Classes
class DcachePort
DcachePort class for the load/store queue.
class LSQRequest
Memory operation metadata.
class LSQSenderState
Derived class to hold any sender state the LSQ needs.
class SingleDataRequest
class SplitDataRequest
Public Types
typedef Impl::O3CPU O3CPU
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::CPUPol::IEW IEW
typedef Impl::CPUPol::LSQUnit LSQUnit
Public Member Functions
LSQ (O3CPU *cpu_ptr, IEW *iew_ptr, DerivO3CPUParams *params)
Constructs an LSQ with the given parameters.
~LSQ ()
std::string name () const
Returns the name of the LSQ.
void regStats ()
Registers statistics of each LSQ unit.
void setActiveThreads (std::list< ThreadID > *at_ptr)
Sets the pointer to the list of active threads.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool isDrained () const
Has the LSQ drained?
void takeOverFrom ()
Takes over execution from another CPU's thread.
int entryAmount (ThreadID num_threads)
Number of entries needed for the given amount of threads.
void tick ()
Ticks the LSQ.
void insertLoad (const DynInstPtr &load_inst)
Inserts a load into the LSQ.
void insertStore (const DynInstPtr &store_inst)
Inserts a store into the LSQ.
Fault executeLoad (const DynInstPtr &inst)
Executes a load.
Fault executeStore (const DynInstPtr &inst)
Executes a store.
void commitLoads (InstSeqNum &youngest_inst, ThreadID tid)
Commits loads up until the given sequence number for a specific thread.
void commitStores (InstSeqNum &youngest_inst, ThreadID tid)
Commits stores up until the given sequence number for a specific thread.
void writebackStores ()
Attempts to write back stores until all cache ports are used or the interface becomes blocked.
void writebackStores (ThreadID tid)
Same as above, but only for one thread.
void squash (const InstSeqNum &squashed_num, ThreadID tid)
Squash instructions from a thread until the specified sequence number.
bool violation ()
Returns whether or not there was a memory ordering violation.
bool violation (ThreadID tid)
Returns whether or not there was a memory ordering violation for a specific thread.
DynInstPtr getMemDepViolator (ThreadID tid)
Gets the instruction that caused the memory ordering violation.
int getLoadHead (ThreadID tid)
Returns the head index of the load queue for a specific thread.
InstSeqNum getLoadHeadSeqNum (ThreadID tid)
Returns the sequence number of the head of the load queue.
int getStoreHead (ThreadID tid)
Returns the head index of the store queue.
InstSeqNum getStoreHeadSeqNum (ThreadID tid)
Returns the sequence number of the head of the store queue.
int getCount ()
Returns the number of instructions in all of the queues.
int getCount (ThreadID tid)
Returns the number of instructions in the queues of one thread.
int numLoads ()
Returns the total number of loads in the load queue.
int numLoads (ThreadID tid)
Returns the total number of loads for a single thread.
int numStores ()
Returns the total number of stores in the store queue.
int numStores (ThreadID tid)
Returns the total number of stores for a single thread.
unsigned numFreeLoadEntries ()
Returns the number of free load entries.
unsigned numFreeStoreEntries ()
Returns the number of free store entries.
unsigned numFreeEntries (ThreadID tid)
Returns the number of free entries for a specific thread.
unsigned numFreeLoadEntries (ThreadID tid)
Returns the number of free entries in the LQ for a specific thread.
unsigned numFreeStoreEntries (ThreadID tid)
Returns the number of free entries in the SQ for a specific thread.
bool isFull ()
Returns if the LSQ is full (either LQ or SQ is full).
bool isFull (ThreadID tid)
Returns if the LSQ is full for a specific thread (either LQ or SQ is full).
bool isEmpty () const
Returns if the LSQ is empty (both LQ and SQ are empty).
bool lqEmpty () const
Returns if all of the LQs are empty.
bool sqEmpty () const
Returns if all of the SQs are empty.
bool lqFull ()
Returns if any of the LQs are full.
bool lqFull (ThreadID tid)
Returns if the LQ of a given thread is full.
bool sqFull ()
Returns if any of the SQs are full.
bool sqFull (ThreadID tid)
Returns if the SQ of a given thread is full.
bool isStalled ()
Returns if the LSQ is stalled due to a memory operation that must be replayed.
bool isStalled (ThreadID tid)
Returns if the LSQ of a specific thread is stalled due to a memory operation that must be replayed.
bool hasStoresToWB ()
Returns whether or not there are any stores to write back to memory.
bool hasStoresToWB (ThreadID tid)
Returns whether or not a specific thread has any stores to write back to memory.
int numStoresToWB (ThreadID tid)
Returns the number of stores a specific thread has to write back.
bool willWB ()
Returns if the LSQ will write back to memory this cycle.
bool willWB (ThreadID tid)
Returns if the LSQ of a specific thread will write back to memory this cycle.
void dumpInsts () const
Debugging function to print out all instructions.
void dumpInsts (ThreadID tid) const
Debugging function to print out instructions from a specific thread.
Fault read (LSQRequest *req, int load_idx)
Executes a read operation, using the load specified at the load index.
Fault write (LSQRequest *req, uint8_t *data, int store_idx)
Executes a store operation, using the store specified at the store index.
void recvReqRetry ()
Retry the previous send that failed.
void completeDataAccess (PacketPtr pkt)
bool recvTimingResp (PacketPtr pkt)
Handles writing back and completing the load or store that has returned from memory.
void recvTimingSnoopReq (PacketPtr pkt)
Fault pushRequest (const DynInstPtr &inst, bool isLoad, uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, AtomicOpFunctorPtr amo_op, const std::vector< bool > &byteEnable)
bool cacheBlocked () const
Is D-cache blocked?
void cacheBlocked (bool v)
Set D-cache blocked status.
bool cachePortAvailable (bool is_load) const
Is any store port available to use?
void cachePortBusy (bool is_load)
Another store port is in use.
MasterPort & getDataPort ()
Public Attributes
O3CPU * cpu
The CPU pointer.
IEW * iewStage
The IEW stage pointer.
Static Protected Member Functions
static uint32_t maxLSQAllocation (SMTQueuePolicy pol, uint32_t entries, uint32_t numThreads, uint32_t SMTThreshold)
Auxiliary function to calculate per-thread max LSQ allocation limit.
Protected Attributes
bool _cacheBlocked
D-cache is blocked.
int cacheStorePorts
The number of cache ports available each cycle (stores only).
int usedStorePorts
The number of used cache ports in this cycle by stores.
int cacheLoadPorts
The number of cache ports available each cycle (loads only).
int usedLoadPorts
The number of used cache ports in this cycle by loads.
SMTQueuePolicy lsqPolicy
The LSQ policy for SMT mode.
std::list< ThreadID > * activeThreads
List of Active Threads in System.
unsigned LQEntries
Total Size of LQ Entries.
unsigned SQEntries
Total Size of SQ Entries.
unsigned maxLQEntries
Max LQ Size - Used to Enforce Sharing Policies.
unsigned maxSQEntries
Max SQ Size - Used to Enforce Sharing Policies.
DcachePort dcachePort
Data port.
std::vector< LSQUnit > thread
The LSQ units for individual threads.
ThreadID numThreads
Number of Threads.
Detailed Description
template<class Impl>
class LSQ< Impl >
Definition at line 64 of file lsq.hh.
Member Typedef Documentation
DynInstPtr
template<class Impl> typedef Impl::DynInstPtr LSQ< Impl >::DynInstPtr
Definition at line 69 of file lsq.hh.
IEW
template<class Impl> typedef Impl::CPUPol::IEW LSQ< Impl >::IEW
Definition at line 70 of file lsq.hh.
LSQUnit
template<class Impl> typedef Impl::CPUPol::LSQUnit LSQ< Impl >::LSQUnit
Definition at line 71 of file lsq.hh.
O3CPU
template<class Impl> typedef Impl::O3CPU LSQ< Impl >::O3CPU
Definition at line 68 of file lsq.hh.
Constructor & Destructor Documentation
LSQ()
template<class Impl > LSQ< Impl >::LSQ (O3CPU * cpu_ptr, IEW * iew_ptr, DerivO3CPUParams * params)
Constructs an LSQ with the given parameters.
Definition at line 63 of file lsq_impl.hh.
References LSQ< Impl >::cpu, LSQ< Impl >::dcachePort, DPRINTF, LSQ< Impl >::lsqPolicy, LSQ< Impl >::maxLQEntries, LSQ< Impl >::maxSQEntries, LSQ< Impl >::numThreads, panic, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::SplitDataRequest::~SplitDataRequest().
~LSQ()
template<class Impl> LSQ< Impl >::~LSQ () inline
Definition at line 826 of file lsq.hh.
References LSQ< Impl >::drainSanityCheck(), LSQ< Impl >::entryAmount(), LSQ< Impl >::executeLoad(), LSQ< Impl >::executeStore(), LSQ< Impl >::insertLoad(), LSQ< Impl >::insertStore(), LSQ< Impl >::LSQSenderState::inst, LSQ< Impl >::isDrained(), LSQ< Impl >::name(), LSQ< Impl >::regStats(), LSQ< Impl >::setActiveThreads(), LSQ< Impl >::takeOverFrom(), and LSQ< Impl >::tick().
Member Function Documentation
cacheBlocked() [1/2]
template<class Impl > bool LSQ< Impl >::cacheBlocked () const
Is D-cache blocked?
Definition at line 193 of file lsq_impl.hh.
References LSQ< Impl >::_cacheBlocked.
Referenced by LSQ< Impl >::recvReqRetry(), and LSQUnit< Impl >::trySendPacket().
cacheBlocked() [2/2]
template<class Impl > void LSQ< Impl >::cacheBlocked (bool v)
Set D-cache blocked status.
Definition at line 200 of file lsq_impl.hh.
References LSQ< Impl >::_cacheBlocked, and ArmISA::v.
cachePortAvailable()
template<class Impl > bool LSQ< Impl >::cachePortAvailable (bool is_load) const
Is any store port available to use?
Definition at line 207 of file lsq_impl.hh.
References LSQ< Impl >::cacheLoadPorts, LSQ< Impl >::cacheStorePorts, LSQ< Impl >::usedLoadPorts, and LSQ< Impl >::usedStorePorts.
Referenced by LSQ< Impl >::cachePortBusy(), LSQUnit< Impl >::trySendPacket(), and LSQUnit< Impl >::writebackStores().
cachePortBusy()
template<class Impl > void LSQ< Impl >::cachePortBusy (bool is_load)
Another store port is in use.
Definition at line 220 of file lsq_impl.hh.
References LSQ< Impl >::cachePortAvailable(), LSQ< Impl >::usedLoadPorts, and LSQ< Impl >::usedStorePorts.
Referenced by LSQUnit< Impl >::trySendPacket().
commitLoads()
template<class Impl> void LSQ< Impl >::commitLoads (InstSeqNum & youngest_inst, ThreadID tid) inline
Commits loads up until the given sequence number for a specific thread.
Definition at line 864 of file lsq.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::tick().
commitStores()
template<class Impl> void LSQ< Impl >::commitStores (InstSeqNum & youngest_inst, ThreadID tid) inline
Commits stores up until the given sequence number for a specific thread.
Definition at line 870 of file lsq.hh.
References LSQ< Impl >::thread, and LSQ< Impl >::writebackStores().
Referenced by DefaultIEW< Impl >::tick().
completeDataAccess()
template<class Impl > void LSQ< Impl >::completeDataAccess (PacketPtr pkt)
Definition at line 317 of file lsq_impl.hh.
References LSQ< Impl >::cpu, Packet::senderState, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::dumpInsts().
drainSanityCheck()
template<class Impl > void LSQ< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 140 of file lsq_impl.hh.
References LSQ< Impl >::isDrained(), LSQ< Impl >::numThreads, and LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::drainSanityCheck(), and LSQ< Impl >::~LSQ().
dumpInsts() [1/2]
template<class Impl > void LSQ< Impl >::dumpInsts () const
Debugging function to print out all instructions.
Definition at line 674 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::willWB().
dumpInsts() [2/2]
template<class Impl> void LSQ< Impl >::dumpInsts (ThreadID tid) const inline
Debugging function to print out instructions from a specific thread.
Definition at line 1012 of file lsq.hh.
References addr, LSQ< Impl >::completeDataAccess(), data, LSQ< Impl >::LSQSenderState::isLoad, LSQ< Impl >::pushRequest(), LSQ< Impl >::read(), LSQ< Impl >::recvReqRetry(), LSQ< Impl >::recvTimingResp(), LSQ< Impl >::recvTimingSnoopReq(), LSQ< Impl >::thread, and LSQ< Impl >::write().
entryAmount()
template<class Impl> int LSQ< Impl >::entryAmount (ThreadID num_threads)
Number of entries needed for the given amount of threads.
Referenced by LSQ< Impl >::~LSQ().
executeLoad()
template<class Impl > Fault LSQ< Impl >::executeLoad (const DynInstPtr & inst)
Executes a load.
Definition at line 250 of file lsq_impl.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::executeInsts(), and LSQ< Impl >::~LSQ().
executeStore()
template<class Impl > Fault LSQ< Impl >::executeStore (const DynInstPtr & inst)
Executes a store.
Definition at line 259 of file lsq_impl.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::executeInsts(), and LSQ< Impl >::~LSQ().
getCount() [1/2]
template<class Impl > int LSQ< Impl >::getCount ()
Returns the number of instructions in all of the queues.
Definition at line 381 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and Stats::total.
Referenced by LSQ< Impl >::getStoreHeadSeqNum(), and DefaultIEW< Impl >::tick().
getCount() [2/2]
template<class Impl> int LSQ< Impl >::getCount (ThreadID tid) inline
Returns the number of instructions in the queues of one thread.
Definition at line 928 of file lsq.hh.
References LSQ< Impl >::numLoads(), and LSQ< Impl >::thread.
getDataPort()
template<class Impl> MasterPort& LSQ< Impl >::getDataPort () inline
Definition at line 1060 of file lsq.hh.
References LSQ< Impl >::dcachePort.
Referenced by DefaultIEW< Impl >::startupStage().
getLoadHead()
template<class Impl> int LSQ< Impl >::getLoadHead (ThreadID tid) inline
Returns the head index of the load queue for a specific thread.
Definition at line 906 of file lsq.hh.
References LSQ< Impl >::thread.
getLoadHeadSeqNum()
template<class Impl> InstSeqNum LSQ< Impl >::getLoadHeadSeqNum (ThreadID tid) inline
Returns the sequence number of the head of the load queue.
Definition at line 910 of file lsq.hh.
References LSQ< Impl >::thread.
getMemDepViolator()
template<class Impl> DynInstPtr LSQ< Impl >::getMemDepViolator (ThreadID tid) inline
Gets the instruction that caused the memory ordering violation.
Definition at line 900 of file lsq.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::executeInsts().
getStoreHead()
template<class Impl> int LSQ< Impl >::getStoreHead (ThreadID tid) inline
Returns the head index of the store queue.
Definition at line 916 of file lsq.hh.
References LSQ< Impl >::thread.
getStoreHeadSeqNum()
template<class Impl> InstSeqNum LSQ< Impl >::getStoreHeadSeqNum (ThreadID tid) inline
Returns the sequence number of the head of the store queue.
Definition at line 920 of file lsq.hh.
References LSQ< Impl >::getCount(), and LSQ< Impl >::thread.
hasStoresToWB() [1/2]
template<class Impl > bool LSQ< Impl >::hasStoresToWB ()
Returns whether or not there are any stores to write back to memory.
Definition at line 640 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads.
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and LSQ< Impl >::numStores().
hasStoresToWB() [2/2]
template<class Impl> bool LSQ< Impl >::hasStoresToWB (ThreadID tid) inline
Returns whether or not a specific thread has any stores to write back to memory.
Definition at line 997 of file lsq.hh.
References LSQ< Impl >::thread.
insertLoad()
template<class Impl > void LSQ< Impl >::insertLoad (const DynInstPtr & load_inst)
Inserts a load into the LSQ.
Definition at line 232 of file lsq_impl.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and LSQ< Impl >::~LSQ().
insertStore()
template<class Impl > void LSQ< Impl >::insertStore (const DynInstPtr & store_inst)
Inserts a store into the LSQ.
Definition at line 241 of file lsq_impl.hh.
References LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and LSQ< Impl >::~LSQ().
isDrained()
template<class Impl > bool LSQ< Impl >::isDrained () const
Has the LSQ drained?
Definition at line 150 of file lsq_impl.hh.
References DPRINTF, LSQ< Impl >::lqEmpty(), and LSQ< Impl >::sqEmpty().
Referenced by LSQ< Impl >::drainSanityCheck(), DefaultIEW< Impl >::isDrained(), and LSQ< Impl >::~LSQ().
isEmpty()
template<class Impl > bool LSQ< Impl >::isEmpty () const
Returns if the LSQ is empty (both LQ and SQ are empty).
Definition at line 514 of file lsq_impl.hh.
References LSQ< Impl >::lqEmpty(), and LSQ< Impl >::sqEmpty().
Referenced by LSQ< Impl >::numStores().
isFull() [1/2]
template<class Impl > bool LSQ< Impl >::isFull ()
Returns if the LSQ is full (either LQ or SQ is full).
Definition at line 485 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, LSQ< Impl >::lqFull(), LSQ< Impl >::sqFull(), and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::isFull(), and LSQ< Impl >::numStores().
isFull() [2/2]
template<class Impl > bool LSQ< Impl >::isFull (ThreadID tid)
Returns if the LSQ is full for a specific thread (either LQ or SQ is full).
Definition at line 502 of file lsq_impl.hh.
References LSQ< Impl >::isFull(), LSQ< Impl >::lsqPolicy, and LSQ< Impl >::thread.
isStalled() [1/2]
template<class Impl > bool LSQ< Impl >::isStalled ()
Returns if the LSQ is stalled due to a memory operation that must be replayed.
Definition at line 613 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::isStalled(), and LSQ< Impl >::numStores().
isStalled() [2/2]
template<class Impl > bool LSQ< Impl >::isStalled (ThreadID tid)
Returns if the LSQ of a specific thread is stalled due to a memory operation that must be replayed.
Definition at line 630 of file lsq_impl.hh.
References LSQ< Impl >::isStalled(), LSQ< Impl >::lsqPolicy, and LSQ< Impl >::thread.
lqEmpty()
template<class Impl > bool LSQ< Impl >::lqEmpty () const
Returns if all of the LQs are empty.
Definition at line 521 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::isDrained(), LSQ< Impl >::isEmpty(), and LSQ< Impl >::numStores().
lqFull() [1/2]
template<class Impl > bool LSQ< Impl >::lqFull ()
Returns if any of the LQs are full.
Definition at line 555 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::dispatchInsts(), LSQ< Impl >::isFull(), LSQ< Impl >::lqFull(), and LSQ< Impl >::numStores().
lqFull() [2/2]
template<class Impl > bool LSQ< Impl >::lqFull (ThreadID tid)
Returns if the LQ of a given thread is full.
Definition at line 572 of file lsq_impl.hh.
References LSQ< Impl >::lqFull(), LSQ< Impl >::lsqPolicy, and LSQ< Impl >::thread.
maxLSQAllocation()
template<class Impl> static uint32_t LSQ< Impl >::maxLSQAllocation (SMTQueuePolicy pol, uint32_t entries, uint32_t numThreads, uint32_t SMTThreshold) inline static protected
Auxiliary function to calculate per-thread max LSQ allocation limit.
Depending on a policy, number of entries and possibly number of threads and threshold, this function calculates how many resources each thread can occupy at most.
Definition at line 1084 of file lsq.hh.
References LSQ< Impl >::numThreads.
name()
template<class Impl > std::string LSQ< Impl >::name () const
Returns the name of the LSQ.
Definition at line 115 of file lsq_impl.hh.
References LSQ< Impl >::iewStage.
Referenced by LSQ< Impl >::~LSQ().
numFreeEntries()
template<class Impl> unsigned LSQ< Impl >::numFreeEntries (ThreadID tid)
Returns the number of free entries for a specific thread.
Referenced by LSQ< Impl >::numStores().
numFreeLoadEntries() [1/2]
template<class Impl > unsigned LSQ< Impl >::numFreeLoadEntries ()
Returns the number of free load entries.
Definition at line 435 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, LSQ< Impl >::thread, and Stats::total.
Referenced by DefaultIEW< Impl >::clearStates(), LSQ< Impl >::numStores(), DefaultIEW< Impl >::startupStage(), and DefaultIEW< Impl >::tick().
numFreeLoadEntries() [2/2]
template<class Impl > unsigned LSQ< Impl >::numFreeLoadEntries (ThreadID tid)
Returns the number of free entries in the LQ for a specific thread.
Definition at line 471 of file lsq_impl.hh.
References LSQ< Impl >::thread.
numFreeStoreEntries() [1/2]
template<class Impl > unsigned LSQ< Impl >::numFreeStoreEntries ()
Returns the number of free store entries.
Definition at line 453 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, LSQ< Impl >::thread, and Stats::total.
Referenced by DefaultIEW< Impl >::clearStates(), LSQ< Impl >::numStores(), DefaultIEW< Impl >::startupStage(), and DefaultIEW< Impl >::tick().
numFreeStoreEntries() [2/2]
template<class Impl > unsigned LSQ< Impl >::numFreeStoreEntries (ThreadID tid)
Returns the number of free entries in the SQ for a specific thread.
Definition at line 478 of file lsq_impl.hh.
References LSQ< Impl >::thread.
numLoads() [1/2]
template<class Impl > int LSQ< Impl >::numLoads ()
Returns the total number of loads in the load queue.
Definition at line 399 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and Stats::total.
Referenced by LSQ< Impl >::getCount().
numLoads() [2/2]
template<class Impl> int LSQ< Impl >::numLoads (ThreadID tid) inline
Returns the total number of loads for a single thread.
Definition at line 933 of file lsq.hh.
References LSQ< Impl >::numStores(), and LSQ< Impl >::thread.
numStores() [1/2]
template<class Impl > int LSQ< Impl >::numStores ()
Returns the total number of stores in the store queue.
Definition at line 417 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, LSQ< Impl >::thread, and Stats::total.
Referenced by LSQ< Impl >::numLoads().
numStores() [2/2]
template<class Impl> int LSQ< Impl >::numStores (ThreadID tid) inline
Returns the total number of stores for a single thread.
Definition at line 938 of file lsq.hh.
References LSQ< Impl >::hasStoresToWB(), LSQ< Impl >::isEmpty(), LSQ< Impl >::isFull(), LSQ< Impl >::isStalled(), LSQ< Impl >::lqEmpty(), LSQ< Impl >::lqFull(), LSQ< Impl >::numFreeEntries(), LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), LSQ< Impl >::sqEmpty(), LSQ< Impl >::sqFull(), and LSQ< Impl >::thread.
numStoresToWB()
template<class Impl> int LSQ< Impl >::numStoresToWB (ThreadID tid) inline
Returns the number of stores a specific thread has to write back.
Definition at line 1000 of file lsq.hh.
References LSQ< Impl >::thread, and LSQ< Impl >::willWB().
Referenced by LSQ< Impl >::writebackStores().
pushRequest()
template<class Impl > Fault LSQ< Impl >::pushRequest (const DynInstPtr & inst, bool isLoad, uint8_t * data, unsigned int size, Addr addr, Request::Flags flags, uint64_t * res, AtomicOpFunctorPtr amo_op, const std::vector< bool > & byteEnable)
Definition at line 688 of file lsq_impl.hh.
References LSQ< Impl >::LSQRequest::_byteEnable, LSQ< Impl >::cpu, LSQ< Impl >::LSQRequest::getVaddr(), LSQ< Impl >::LSQRequest::initiateTranslation(), LSQ< Impl >::LSQRequest::isMemAccessRequired(), LSQ< Impl >::LSQRequest::isTranslationComplete(), M5_VAR_USED, NoFault, LSQ< Impl >::LSQRequest::request(), LSQ< Impl >::LSQRequest::taskId(), LSQ< Impl >::thread, and transferNeedsBurst().
Referenced by LSQ< Impl >::dumpInsts().
read()
template<class Impl > Fault LSQ< Impl >::read (LSQRequest * req, int load_idx)
Executes a read operation, using the load specified at the load index.
Definition at line 1127 of file lsq.hh.
References LSQ< Impl >::cpu, LSQ< Impl >::LSQRequest::request(), and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::dumpInsts().
recvReqRetry()
template<class Impl > void LSQ< Impl >::recvReqRetry ()
Retry the previous send that failed.
Definition at line 305 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, LSQ< Impl >::cacheBlocked(), LSQ< Impl >::iewStage, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::dumpInsts(), and LSQ< Impl >::DcachePort::recvFunctionalSnoop().
recvTimingResp()
template<class Impl > bool LSQ< Impl >::recvTimingResp (PacketPtr pkt)
Handles writing back and completing the load or store that has returned from memory.
Parameters
pkt Response packet from the memory sub-system
Definition at line 326 of file lsq_impl.hh.
References LSQ< Impl >::cpu, DPRINTF, Packet::getAddr(), Packet::isError(), Packet::isInvalidate(), LSQ< Impl >::numThreads, panic_if, Packet::senderState, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::DcachePort::DcachePort(), LSQ< Impl >::dumpInsts(), LSQ< Impl >::LSQRequest::isSplit(), LSQ< Impl >::SingleDataRequest::~SingleDataRequest(), and LSQ< Impl >::SplitDataRequest::~SplitDataRequest().
recvTimingSnoopReq()
template<class Impl > void LSQ< Impl >::recvTimingSnoopReq (PacketPtr pkt)
Definition at line 364 of file lsq_impl.hh.
References Packet::cmdString(), DPRINTF, Packet::getAddr(), Packet::isInvalidate(), LSQ< Impl >::numThreads, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::DcachePort::DcachePort(), and LSQ< Impl >::dumpInsts().
regStats()
template<class Impl > void LSQ< Impl >::regStats ()
Registers statistics of each LSQ unit.
Definition at line 122 of file lsq_impl.hh.
References LSQ< Impl >::numThreads, and LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::regStats(), and LSQ< Impl >::~LSQ().
setActiveThreads()
template<class Impl > void LSQ< Impl >::setActiveThreads (std::list< ThreadID > * at_ptr)
Sets the pointer to the list of active threads.
Definition at line 132 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads.
Referenced by DefaultIEW< Impl >::setActiveThreads(), and LSQ< Impl >::~LSQ().
sqEmpty()
template<class Impl > bool LSQ< Impl >::sqEmpty () const
Returns if all of the SQs are empty.
Definition at line 538 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::isDrained(), LSQ< Impl >::isEmpty(), and LSQ< Impl >::numStores().
sqFull() [1/2]
template<class Impl > bool LSQ< Impl >::sqFull ()
Returns if any of the SQs are full.
Definition at line 584 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads.
Referenced by DefaultIEW< Impl >::dispatchInsts(), LSQ< Impl >::isFull(), LSQ< Impl >::numStores(), and LSQ< Impl >::sqFull().
sqFull() [2/2]
template<class Impl > bool LSQ< Impl >::sqFull (ThreadID tid)
Returns if the SQ of a given thread is full.
Definition at line 601 of file lsq_impl.hh.
References LSQ< Impl >::lsqPolicy, LSQ< Impl >::sqFull(), and LSQ< Impl >::thread.
squash()
template<class Impl> void LSQ< Impl >::squash (const InstSeqNum & squashed_num, ThreadID tid) inline
Squash instructions from a thread until the specified sequence number.
Definition at line 885 of file lsq.hh.
References LSQ< Impl >::thread, and LSQ< Impl >::violation().
Referenced by DefaultIEW< Impl >::squash().
takeOverFrom()
template<class Impl > void LSQ< Impl >::takeOverFrom ()
Takes over execution from another CPU's thread.
Definition at line 169 of file lsq_impl.hh.
References LSQ< Impl >::_cacheBlocked, LSQ< Impl >::numThreads, LSQ< Impl >::thread, and LSQ< Impl >::usedStorePorts.
Referenced by DefaultIEW< Impl >::takeOverFrom(), and LSQ< Impl >::~LSQ().
tick()
template<class Impl > void LSQ< Impl >::tick ()
Ticks the LSQ.
Definition at line 181 of file lsq_impl.hh.
References LSQ< Impl >::_cacheBlocked, LSQ< Impl >::cacheLoadPorts, LSQ< Impl >::iewStage, LSQ< Impl >::usedLoadPorts, and LSQ< Impl >::usedStorePorts.
Referenced by DefaultIEW< Impl >::tick(), and LSQ< Impl >::~LSQ().
violation() [1/2]
template<class Impl > bool LSQ< Impl >::violation ()
Returns whether or not there was a memory ordering violation.
Definition at line 287 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, and LSQ< Impl >::thread.
Referenced by DefaultIEW< Impl >::executeInsts(), and LSQ< Impl >::squash().
violation() [2/2]
template<class Impl> bool LSQ< Impl >::violation (ThreadID tid) inline
Returns whether or not there was a memory ordering violation for a specific thread.
Definition at line 896 of file lsq.hh.
References LSQ< Impl >::thread.
willWB() [1/2]
template<class Impl > bool LSQ< Impl >::willWB ()
Returns if the LSQ will write back to memory this cycle.
Definition at line 657 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads.
Referenced by LSQ< Impl >::numStoresToWB(), and DefaultIEW< Impl >::updateStatus().
willWB() [2/2]
template<class Impl> bool LSQ< Impl >::willWB (ThreadID tid) inline
Returns if the LSQ of a specific thread will write back to memory this cycle.
Definition at line 1007 of file lsq.hh.
References LSQ< Impl >::dumpInsts(), and LSQ< Impl >::thread.
write()
template<class Impl > Fault LSQ< Impl >::write (LSQRequest * req, uint8_t * data, int store_idx)
Executes a store operation, using the store specified at the store index.
Definition at line 1136 of file lsq.hh.
References LSQ< Impl >::cpu, LSQ< Impl >::LSQRequest::request(), and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::dumpInsts().
writebackStores() [1/2]
template<class Impl > void LSQ< Impl >::writebackStores ()
Attempts to write back stores until all cache ports are used or the interface becomes blocked.
Definition at line 268 of file lsq_impl.hh.
References LSQ< Impl >::activeThreads, DPRINTF, LSQ< Impl >::numStoresToWB(), and LSQ< Impl >::thread.
Referenced by LSQ< Impl >::commitStores(), and DefaultIEW< Impl >::tick().
writebackStores() [2/2]
template<class Impl> void LSQ< Impl >::writebackStores (ThreadID tid)
Same as above, but only for one thread.
Member Data Documentation
_cacheBlocked
template<class Impl> bool LSQ< Impl >::_cacheBlocked protected
D-cache is blocked.
Definition at line 1064 of file lsq.hh.
Referenced by LSQ< Impl >::cacheBlocked(), LSQ< Impl >::takeOverFrom(), and LSQ< Impl >::tick().
activeThreads
template<class Impl> std::list<ThreadID>* LSQ< Impl >::activeThreads protected
List of Active Threads in System.
Definition at line 1102 of file lsq.hh.
Referenced by LSQ< Impl >::dumpInsts(), LSQ< Impl >::getCount(), LSQ< Impl >::hasStoresToWB(), LSQ< Impl >::isFull(), LSQ< Impl >::isStalled(), LSQ< Impl >::lqEmpty(), LSQ< Impl >::lqFull(), LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), LSQ< Impl >::numLoads(), LSQ< Impl >::numStores(), LSQ< Impl >::recvReqRetry(), LSQ< Impl >::setActiveThreads(), LSQ< Impl >::sqEmpty(), LSQ< Impl >::sqFull(), LSQ< Impl >::violation(), LSQ< Impl >::willWB(), and LSQ< Impl >::writebackStores().
cacheLoadPorts
template<class Impl> int LSQ< Impl >::cacheLoadPorts protected
The number of cache ports available each cycle (loads only).
Definition at line 1070 of file lsq.hh.
Referenced by LSQ< Impl >::cachePortAvailable(), and LSQ< Impl >::tick().
cacheStorePorts
template<class Impl> int LSQ< Impl >::cacheStorePorts protected
The number of cache ports available each cycle (stores only).
Definition at line 1066 of file lsq.hh.
Referenced by LSQ< Impl >::cachePortAvailable().
cpu
template<class Impl> O3CPU* LSQ< Impl >::cpu
The CPU pointer.
Definition at line 1046 of file lsq.hh.
Referenced by LSQ< Impl >::completeDataAccess(), LSQ< Impl >::LSQ(), LSQ< Impl >::pushRequest(), LSQ< Impl >::read(), LSQ< Impl >::recvTimingResp(), LSQ< Impl >::DcachePort::recvTimingSnoopReq(), and LSQ< Impl >::write().
dcachePort
template<class Impl> DcachePort LSQ< Impl >::dcachePort protected
Data port.
Definition at line 1116 of file lsq.hh.
Referenced by LSQ< Impl >::getDataPort(), and LSQ< Impl >::LSQ().
iewStage
template<class Impl> IEW* LSQ< Impl >::iewStage
The IEW stage pointer.
Definition at line 1049 of file lsq.hh.
Referenced by LSQ< Impl >::name(), LSQ< Impl >::recvReqRetry(), and LSQ< Impl >::tick().
LQEntries
template<class Impl> unsigned LSQ< Impl >::LQEntries protected
Total Size of LQ Entries.
Definition at line 1105 of file lsq.hh.
lsqPolicy
template<class Impl> SMTQueuePolicy LSQ< Impl >::lsqPolicy protected
The LSQ policy for SMT mode.
Definition at line 1076 of file lsq.hh.
Referenced by LSQ< Impl >::isFull(), LSQ< Impl >::isStalled(), LSQ< Impl >::lqFull(), LSQ< Impl >::LSQ(), and LSQ< Impl >::sqFull().
maxLQEntries
template<class Impl> unsigned LSQ< Impl >::maxLQEntries protected
Max LQ Size - Used to Enforce Sharing Policies.
Definition at line 1110 of file lsq.hh.
Referenced by LSQ< Impl >::LSQ().
maxSQEntries
template<class Impl> unsigned LSQ< Impl >::maxSQEntries protected
Max SQ Size - Used to Enforce Sharing Policies.
Definition at line 1113 of file lsq.hh.
Referenced by LSQ< Impl >::LSQ().
numThreads
template<class Impl> ThreadID LSQ< Impl >::numThreads protected
Number of Threads.
Definition at line 1122 of file lsq.hh.
Referenced by LSQ< Impl >::drainSanityCheck(), LSQ< Impl >::LSQ(), LSQ< Impl >::maxLSQAllocation(), LSQ< Impl >::recvTimingResp(), LSQ< Impl >::recvTimingSnoopReq(), LSQ< Impl >::regStats(), and LSQ< Impl >::takeOverFrom().
SQEntries
template<class Impl> unsigned LSQ< Impl >::SQEntries protected
Total Size of SQ Entries.
Definition at line 1107 of file lsq.hh.
thread
template<class Impl> std::vector<LSQUnit> LSQ< Impl >::thread protected
The LSQ units for individual threads.
Definition at line 1119 of file lsq.hh.
Referenced by LSQ< Impl >::commitLoads(), LSQ< Impl >::commitStores(), LSQ< Impl >::completeDataAccess(), LSQ< Impl >::drainSanityCheck(), LSQ< Impl >::dumpInsts(), LSQ< Impl >::executeLoad(), LSQ< Impl >::executeStore(), LSQ< Impl >::getCount(), LSQ< Impl >::getLoadHead(), LSQ< Impl >::getLoadHeadSeqNum(), LSQ< Impl >::getMemDepViolator(), LSQ< Impl >::getStoreHead(), LSQ< Impl >::getStoreHeadSeqNum(), LSQ< Impl >::hasStoresToWB(), LSQ< Impl >::insertLoad(), LSQ< Impl >::insertStore(), LSQ< Impl >::isFull(), LSQ< Impl >::LSQRequest::isSplit(), LSQ< Impl >::isStalled(), LSQ< Impl >::lqEmpty(), LSQ< Impl >::lqFull(), LSQ< Impl >::LSQ(), LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), LSQ< Impl >::numLoads(), LSQ< Impl >::numStores(), LSQ< Impl >::numStoresToWB(), LSQ< Impl >::pushRequest(), LSQ< Impl >::read(), LSQ< Impl >::recvReqRetry(), LSQ< Impl >::recvTimingResp(), LSQ< Impl >::recvTimingSnoopReq(), LSQ< Impl >::regStats(), LSQ< Impl >::sqEmpty(), LSQ< Impl >::sqFull(), LSQ< Impl >::squash(), LSQ< Impl >::takeOverFrom(), LSQ< Impl >::violation(), LSQ< Impl >::willWB(), LSQ< Impl >::write(), LSQ< Impl >::writebackStores(), LSQ< Impl >::SingleDataRequest::~SingleDataRequest(), and LSQ< Impl >::SplitDataRequest::~SplitDataRequest().
usedLoadPorts
template<class Impl> int LSQ< Impl >::usedLoadPorts protected
The number of used cache ports in this cycle by loads.
Definition at line 1072 of file lsq.hh.
Referenced by LSQ< Impl >::cachePortAvailable(), LSQ< Impl >::cachePortBusy(), and LSQ< Impl >::tick().
usedStorePorts
template<class Impl> int LSQ< Impl >::usedStorePorts protected
The number of used cache ports in this cycle by stores.
Definition at line 1068 of file lsq.hh.
Referenced by LSQ< Impl >::cachePortAvailable(), LSQ< Impl >::cachePortBusy(), LSQ< Impl >::takeOverFrom(), and LSQ< Impl >::tick().
The documentation for this class was generated from the following files:
cpu/o3/lsq.hh
cpu/o3/lsq_impl.hh