gem5: Random Class Reference
Random Class Reference
#include <random.hh>
Public Member Functions
Random ()
Random (uint32_t s)
~Random ()
void init (uint32_t s)
template<typename T >
std::enable_if< std::is_integral< T >::value, T >::type random ()
Use the SFINAE idiom to choose an implementation based on whether the type is integral or floating point.
template<typename T >
std::enable_if< std::is_floating_point< T >::value, T >::type random ()
template<typename T >
std::enable_if< std::is_integral< T >::value, T >::type random (T min, T max)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Attributes
std::mt19937_64 gen
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 62 of file random.hh.
Constructor & Destructor Documentation
Random() [1/2]
Random::Random ()
Definition at line 52 of file random.cc.
References init().
Random() [2/2]
Random::Random (uint32_t s)
Definition at line 58 of file random.cc.
References init().
~Random()
Random::~Random ()
Definition at line 63 of file random.cc.
Member Function Documentation
init()
void Random::init (uint32_t s)
Definition at line 68 of file random.cc.
References gen.
Referenced by DistIface::init(), pybind_init_core(), and Random().
random() [1/3]
template<typename T > std::enable_if<std::is_integral<T>::value, T>::type Random::random () inline
Use the SFINAE idiom to choose an implementation based on whether the type is integral or floating point.
Definition at line 83 of file random.hh.
References Stats::dist, and type.
Referenced by MPP_TAGE::adjustAlloc(), TAGE_SC_L_TAGE::adjustAlloc(), RiscvProcess::argsInit(), TAGE_SC_L_TAGE::calcDep(), Check::Check(), GarnetSyntheticTraffic::generatePkt(), DramGen::genStartAddr(), SimpleMemory::getLatency(), RandomGen::getNextPacket(), LinearGen::getNextPacket(), DramGen::getNextPacket(), CheckTable::getRandomCheck(), RandomRP::getVictim(), TAGE_SC_L_TAGE_8KB::handleAllocAndUReset(), MPP_TAGE::handleAllocAndUReset(), SeriesRequestGenerator::initiate(), Check::initiate(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), SimpleCache::insert(), LoopPredictor::loopUpdate(), RandomGen::nextPacketTick(), LinearGen::nextPacketTick(), TrafficGen::nextState(), PerfectSwitch::operateMessageBuffer(), MPP_LoopPredictor::optionalAgeInc(), TAGE_SC_L_LoopPredictor::optionalAgeInc(), SMMUTLB::pickEntryIdxToReplace(), ARMArchTLB::pickEntryIdxToReplace(), IPACache::pickEntryIdxToReplace(), ConfigCache::pickEntryIdxToReplace(), WalkCache::pickEntryIdxToReplace(), Check::pickInitiatingNode(), Check::pickValue(), random_time(), RandomStreamGen::randomPick(), BIPRP::reset(), BRRIPRP::reset(), EtherSwitch::Interface::switchingDelay(), GarnetSyntheticTraffic::tick(), MemTest::tick(), DefaultFetch< Impl >::tick(), MultiperspectivePerceptron::train(), EtherLink::Link::transmit(), DistEtherLink::TxLink::transmit(), LTAGE::update(), TAGE::update(), TAGE_SC_L::update(), MultiperspectivePerceptronTAGE::update(), and MultiperspectivePerceptron::update().
random() [2/3]
template<typename T > std::enable_if<std::is_floating_point<T>::value, T>::type Random::random () inline
Definition at line 92 of file random.hh.
References Stats::dist, and type.
random() [3/3]
template<typename T > std::enable_if<std::is_integral<T>::value, T>::type Random::random (T min, T max) inline
Definition at line 101 of file random.hh.
References Stats::dist, random_mt, serialize(), and unserialize().
serialize()
void Random::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 74 of file random.cc.
References gen, panic, and paramOut().
Referenced by random().
unserialize()
void Random::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 86 of file random.cc.
References gen, optParamIn(), and panic.
Referenced by random().
Member Data Documentation
gen
std::mt19937_64 Random::gen private
Definition at line 67 of file random.hh.
Referenced by init(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
base/random.hh
base/random.cc