gem5: Intel8254Timer Class Reference
Intel8254Timer Class Reference
Programmable Interval Timer (Intel 8254)
#include <intel_8254_timer.hh>
Classes
class Counter
Counter element for PIT.
Public Member Functions
virtual ~Intel8254Timer ()
Intel8254Timer (EventManager *em, const std::string &name, Counter *counter0, Counter *counter1, Counter *counter2)
Intel8254Timer (EventManager *em, const std::string &name)
void writeControl (const CtrlReg data)
Write control word.
uint8_t readCounter (unsigned int num)
void writeCounter (unsigned int num, const uint8_t data)
bool outputHigh (unsigned int num)
void serialize (const std::string &base, CheckpointOut &cp) const
Serialize this object to the given output stream.
void unserialize (const std::string &base, CheckpointIn &cp)
Reconstruct the state of this object from a checkpoint.
void startup ()
Start ticking.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Protected Types
enum ReadWriteVal { LatchCommand, LsbOnly, MsbOnly, TwoPhase }
enum ModeVal {
InitTc, OneShot, RateGen, SquareWave,
SoftwareStrobe, HardwareStrobe
}
Protected Member Functions
BitUnion8 (CtrlReg) Bitfield< 7
EndBitUnion (CtrlReg) enum SelectVal
const std::string & name () const
virtual void counterInterrupt (unsigned int num)
Protected Attributes
sel
Bitfield< 5, 4 > rw
Bitfield< 3, 1 > mode
Bitfield< 0 > bcd
std::string _name
Counter * counter [3]
PIT has three seperate counters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Programmable Interval Timer (Intel 8254)
Definition at line 47 of file intel_8254_timer.hh.
Member Enumeration Documentation
ModeVal
enum Intel8254Timer::ModeVal protected
Enumerator
InitTc
OneShot
RateGen
SquareWave
SoftwareStrobe
HardwareStrobe
Definition at line 71 of file intel_8254_timer.hh.
ReadWriteVal
enum Intel8254Timer::ReadWriteVal protected
Enumerator
LatchCommand
LsbOnly
MsbOnly
TwoPhase
Definition at line 64 of file intel_8254_timer.hh.
Constructor & Destructor Documentation
~Intel8254Timer()
virtual Intel8254Timer::~Intel8254Timer () inline virtual
Definition at line 212 of file intel_8254_timer.hh.
References data, X86ISA::em, Intel8254Timer(), Event::name(), and writeControl().
Intel8254Timer() [1/2]
Intel8254Timer::Intel8254Timer (EventManager * em, const std::string & name, Counter * counter0, Counter * counter1, Counter * counter2)
Referenced by ~Intel8254Timer().
Intel8254Timer() [2/2]
Intel8254Timer::Intel8254Timer (EventManager * em, const std::string & name)
Member Function Documentation
BitUnion8()
Intel8254Timer::BitUnion8 (CtrlReg) protected
counterInterrupt()
virtual void Intel8254Timer::counterInterrupt (unsigned int num) inline protected virtual
Reimplemented in X86ISA::I8254::X86Intel8254Timer.
Definition at line 204 of file intel_8254_timer.hh.
References DPRINTF.
Referenced by Intel8254Timer::Counter::CounterEvent::process().
EndBitUnion()
Intel8254Timer::EndBitUnion (CtrlReg) inline protected
Definition at line 55 of file intel_8254_timer.hh.
name()
const std::string& Intel8254Timer::name () const inline protected
Definition at line 198 of file intel_8254_timer.hh.
References Intel8254Timer::Counter::_name.
Referenced by X86ISA::I8254::I8254().
outputHigh()
bool Intel8254Timer::outputHigh (unsigned int num) inline
Definition at line 238 of file intel_8254_timer.hh.
References X86ISA::base, Intel8254Timer::Counter::num, Intel8254Timer::Counter::outputHigh(), Event::serialize(), Intel8254Timer::Counter::startup(), and Event::unserialize().
Referenced by X86ISA::I8254::outputHigh(), and TsunamiIO::read().
readCounter()
uint8_t Intel8254Timer::readCounter (unsigned int num) inline
Definition at line 224 of file intel_8254_timer.hh.
References Intel8254Timer::Counter::num, and Intel8254Timer::Counter::read().
Referenced by X86ISA::I8254::read(), TsunamiIO::read(), and X86ISA::I8254::readCounter().
serialize()
void Intel8254Timer::serialize (const std::string & base, CheckpointOut & cp) const
Serialize this object to the given output stream.
Parameters
base The base name of the counter object.
os The stream to serialize to.
Definition at line 75 of file intel_8254_timer.cc.
Referenced by X86ISA::I8254::serialize(), MaltaIO::serialize(), TsunamiIO::serialize(), and X86ISA::I8254::writeControl().
startup()
void Intel8254Timer::startup ()
Start ticking.
Definition at line 93 of file intel_8254_timer.cc.
Referenced by X86ISA::I8254::startup(), MaltaIO::startup(), TsunamiIO::startup(), and X86ISA::I8254::writeControl().
unserialize()
void Intel8254Timer::unserialize (const std::string & base, CheckpointIn & cp)
Reconstruct the state of this object from a checkpoint.
Parameters
base The base name of the counter object.
cp The checkpoint use.
section The section name of this object
Definition at line 84 of file intel_8254_timer.cc.
Referenced by X86ISA::I8254::unserialize(), MaltaIO::unserialize(), TsunamiIO::unserialize(), and X86ISA::I8254::writeControl().
writeControl()
void Intel8254Timer::writeControl (const CtrlReg data)
Write control word.
Definition at line 58 of file intel_8254_timer.cc.
References panic, and ArmISA::sel.
Referenced by X86ISA::I8254::write(), TsunamiIO::write(), X86ISA::I8254::writeControl(), and ~Intel8254Timer().
writeCounter()
void Intel8254Timer::writeCounter (unsigned int num, const uint8_t data) inline
Definition at line 231 of file intel_8254_timer.hh.
References Intel8254Timer::Counter::num, and Intel8254Timer::Counter::write().
Referenced by X86ISA::I8254::write(), TsunamiIO::write(), and X86ISA::I8254::writeCounter().
Member Data Documentation
_name
std::string Intel8254Timer::_name protected
Definition at line 197 of file intel_8254_timer.hh.
bcd
Bitfield<0> Intel8254Timer::bcd protected
Definition at line 54 of file intel_8254_timer.hh.
counter
Counter* Intel8254Timer::counter[3] protected
PIT has three seperate counters.
Definition at line 201 of file intel_8254_timer.hh.
Referenced by Intel8254Timer::Counter::CounterEvent::CounterEvent(), Intel8254Timer::Counter::CounterEvent::process(), and Intel8254Timer::Counter::CounterEvent::setTo().
mode
Bitfield<3, 1> Intel8254Timer::mode protected
Definition at line 53 of file intel_8254_timer.hh.
rw
Bitfield<5, 4> Intel8254Timer::rw protected
Definition at line 52 of file intel_8254_timer.hh.
sel
Intel8254Timer::sel protected
Definition at line 51 of file intel_8254_timer.hh.
The documentation for this class was generated from the following files:
dev/intel_8254_timer.hh
dev/intel_8254_timer.cc