gem5: sc_core::sc_join Class Reference
sc_core::sc_join Class Reference
#include <sc_join.hh>
Public Member Functions
sc_join ()
void add_process (sc_process_handle)
int process_count ()
void signal ()
void wait ()
void wait_clocked ()
Private Attributes
sc_gem5::InternalScEvent joinEvent
int remaining
Detailed Description
Definition at line 43 of file sc_join.hh.
Constructor & Destructor Documentation
sc_join()
sc_core::sc_join::sc_join ()
Definition at line 40 of file sc_join.cc.
Member Function Documentation
add_process()
void sc_core::sc_join::add_process (sc_process_handle h)
Definition at line 43 of file sc_join.cc.
References MipsISA::p, remaining, sc_core::SC_ID_JOIN_ON_METHOD_HANDLE_, sc_core::SC_METHOD_PROC_, and SC_REPORT_ERROR.
process_count()
int sc_core::sc_join::process_count ()
Definition at line 57 of file sc_join.cc.
References remaining.
signal()
void sc_core::sc_join::signal ()
Definition at line 58 of file sc_join.cc.
References joinEvent, sc_core::sc_event::notify(), and remaining.
wait()
void sc_core::sc_join::wait ()
Definition at line 59 of file sc_join.cc.
References joinEvent, and sc_core::wait().
wait_clocked()
void sc_core::sc_join::wait_clocked ()
Definition at line 60 of file sc_join.cc.
References remaining, and sc_core::wait().
Member Data Documentation
joinEvent
sc_gem5::InternalScEvent sc_core::sc_join::joinEvent private
Definition at line 55 of file sc_join.hh.
Referenced by signal(), and wait().
remaining
int sc_core::sc_join::remaining private
Definition at line 56 of file sc_join.hh.
Referenced by add_process(), process_count(), signal(), and wait_clocked().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_join.hh
systemc/core/sc_join.cc