gem5: X86ISA::ISA Class Reference
X86ISA::ISA Class Reference
#include <isa.hh>
Public Types
typedef X86ISAParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void clear ()
ISA (Params *p)
const Params * params () const
RegVal readMiscRegNoEffect (int miscReg) const
RegVal readMiscReg (int miscReg, ThreadContext *tc)
void setMiscRegNoEffect (int miscReg, RegVal val)
void setMiscReg (int miscReg, RegVal val, ThreadContext *tc)
RegId flattenRegId (const RegId &regId) const
int flattenIntIndex (int reg) const
int flattenFloatIndex (int reg) const
int flattenVecIndex (int reg) const
int flattenVecElemIndex (int reg) const
int flattenVecPredIndex (int reg) const
int flattenCCIndex (int reg) const
int flattenMiscIndex (int reg) const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup (ThreadContext *tc)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void updateHandyM5Reg (Efer efer, CR0 cr0, SegAttr csAttr, SegAttr ssAttr, RFLAGS rflags, ThreadContext *tc)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
RegVal regVal [NUM_MISCREGS]
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 51 of file isa.hh.
Member Typedef Documentation
Params
typedef X86ISAParams X86ISA::ISA::Params
Definition at line 60 of file isa.hh.
Constructor & Destructor Documentation
ISA()
X86ISA::ISA::ISA (Params * p)
Definition at line 115 of file isa.cc.
References clear().
Member Function Documentation
clear()
void X86ISA::ISA::clear ()
Definition at line 106 of file isa.cc.
References X86ISA::mask, X86ISA::MISCREG_DR6, X86ISA::MISCREG_DR7, X86ISA::NumMiscRegs, and regVal.
Referenced by ISA().
flattenCCIndex()
int X86ISA::ISA::flattenCCIndex (int reg) const inline
Definition at line 126 of file isa.hh.
References X86ISA::reg.
Referenced by flattenRegId().
flattenFloatIndex()
int X86ISA::ISA::flattenFloatIndex (int reg) const inline
Definition at line 98 of file isa.hh.
References X86ISA::FLOATREG_STACK(), X86ISA::MISCREG_X87_TOP, X86ISA::NUM_FLOATREGS, and X86ISA::reg.
Referenced by flattenRegId().
flattenIntIndex()
int X86ISA::ISA::flattenIntIndex (int reg) const inline
Definition at line 92 of file isa.hh.
References X86ISA::IntFoldBit.
Referenced by flattenRegId().
flattenMiscIndex()
int X86ISA::ISA::flattenMiscIndex (int reg) const inline
Definition at line 132 of file isa.hh.
References X86ISA::reg, serialize(), SimObject::startup(), and unserialize().
Referenced by flattenRegId().
flattenRegId()
RegId X86ISA::ISA::flattenRegId (const RegId & regId) const inline
Definition at line 74 of file isa.hh.
References CCRegClass, RegId::classValue(), flattenCCIndex(), flattenFloatIndex(), flattenIntIndex(), flattenMiscIndex(), FloatRegClass, RegId::index(), IntRegClass, and MiscRegClass.
flattenVecElemIndex()
int X86ISA::ISA::flattenVecElemIndex (int reg) const inline
Definition at line 114 of file isa.hh.
References X86ISA::reg.
flattenVecIndex()
int X86ISA::ISA::flattenVecIndex (int reg) const inline
Definition at line 108 of file isa.hh.
References X86ISA::reg.
flattenVecPredIndex()
int X86ISA::ISA::flattenVecPredIndex (int reg) const inline
Definition at line 120 of file isa.hh.
References X86ISA::reg.
params()
const X86ISAParams * X86ISA::ISA::params () const
Definition at line 122 of file isa.cc.
References SimObject::_params.
readMiscReg()
RegVal X86ISA::ISA::readMiscReg (int miscReg, ThreadContext * tc)
Definition at line 139 of file isa.cc.
References Clocked::curCycle(), ThreadContext::getCpuPtr(), insertBits(), X86ISA::MISCREG_FSW, X86ISA::MISCREG_TSC, X86ISA::MISCREG_X87_TOP, readMiscRegNoEffect(), and regVal.
readMiscRegNoEffect()
RegVal X86ISA::ISA::readMiscRegNoEffect (int miscReg) const
Definition at line 128 of file isa.cc.
References X86ISA::isValidMiscReg(), and regVal.
Referenced by readMiscReg().
serialize()
void X86ISA::ISA::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 398 of file isa.cc.
References X86ISA::NumMiscRegs, regVal, and SERIALIZE_ARRAY.
Referenced by flattenMiscIndex().
setMiscReg()
void X86ISA::ISA::setMiscReg (int miscReg, RegVal val, ThreadContext * tc)
Definition at line 197 of file isa.cc.
References Clocked::curCycle(), ThreadContext::getCpuPtr(), ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), M5_FALLTHROUGH, X86ISA::MISCREG_CR0, X86ISA::MISCREG_CR2, X86ISA::MISCREG_CR3, X86ISA::MISCREG_CR4, X86ISA::MISCREG_CR8, X86ISA::MISCREG_CS_ATTR, X86ISA::MISCREG_CS_BASE, X86ISA::MISCREG_CS_EFF_BASE, X86ISA::MISCREG_DR0, X86ISA::MISCREG_DR1, X86ISA::MISCREG_DR2, X86ISA::MISCREG_DR3, X86ISA::MISCREG_DR4, X86ISA::MISCREG_DR5, X86ISA::MISCREG_DR6, X86ISA::MISCREG_DR7, X86ISA::MISCREG_DS_BASE, X86ISA::MISCREG_DS_EFF_BASE, X86ISA::MISCREG_EFER, X86ISA::MISCREG_ES_BASE, X86ISA::MISCREG_ES_EFF_BASE, X86ISA::MISCREG_FS_BASE, X86ISA::MISCREG_GS_BASE, X86ISA::MISCREG_HS_BASE, X86ISA::MISCREG_IDTR_BASE, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SEG_BASE_BASE, X86ISA::MISCREG_SEG_EFF_BASE(), X86ISA::MISCREG_SS_ATTR, X86ISA::MISCREG_SS_BASE, X86ISA::MISCREG_SS_EFF_BASE, X86ISA::MISCREG_TR_BASE, X86ISA::MISCREG_TSC, X86ISA::MISCREG_TSG_BASE, X86ISA::MISCREG_TSL_BASE, panic, regVal, setMiscRegNoEffect(), updateHandyM5Reg(), and X86ISA::val.
setMiscRegNoEffect()
void X86ISA::ISA::setMiscRegNoEffect (int miscReg, RegVal val)
Definition at line 155 of file isa.cc.
References X86ISA::isValidMiscReg(), X86ISA::mask, X86ISA::MISCREG_FCW, X86ISA::MISCREG_FIOFF, X86ISA::MISCREG_FISEG, X86ISA::MISCREG_FOOFF, X86ISA::MISCREG_FOP, X86ISA::MISCREG_FOSEG, X86ISA::MISCREG_FSW, X86ISA::MISCREG_FTW, X86ISA::MISCREG_M5_REG, X86ISA::MISCREG_MXCSR, X86ISA::MISCREG_X87_TOP, regVal, and X86ISA::SixtyFourBitMode.
Referenced by setMiscReg().
startup()
void X86ISA::ISA::startup (ThreadContext * tc)
Definition at line 416 of file isa.cc.
References ThreadContext::getDecoderPtr(), X86ISA::MISCREG_M5_REG, and regVal.
unserialize()
void X86ISA::ISA::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 404 of file isa.cc.
References X86ISA::MISCREG_CR0, X86ISA::MISCREG_CS_ATTR, X86ISA::MISCREG_EFER, X86ISA::MISCREG_RFLAGS, X86ISA::MISCREG_SS_ATTR, X86ISA::NumMiscRegs, regVal, UNSERIALIZE_ARRAY, and updateHandyM5Reg().
Referenced by flattenMiscIndex().
updateHandyM5Reg()
void X86ISA::ISA::updateHandyM5Reg (Efer efer, CR0 cr0, SegAttr csAttr, SegAttr ssAttr, RFLAGS rflags, ThreadContext * tc) protected
Definition at line 44 of file isa.cc.
References X86ISA::CompatabilityMode, ThreadContext::getDecoderPtr(), X86ISA::MISCREG_M5_REG, X86ISA::ProtectedMode, X86ISA::RealMode, regVal, X86ISA::SixtyFourBitMode, and X86ISA::Virtual8086Mode.
Referenced by setMiscReg(), and unserialize().
Member Data Documentation
regVal
RegVal X86ISA::ISA::regVal[NUM_MISCREGS] protected
Definition at line 54 of file isa.hh.
Referenced by clear(), readMiscReg(), readMiscRegNoEffect(), serialize(), setMiscReg(), setMiscRegNoEffect(), startup(), unserialize(), and updateHandyM5Reg().
The documentation for this class was generated from the following files:
arch/x86/isa.hh
arch/x86/isa.cc