gem5: sc_dt::sc_biguint< W > Class Template Reference
sc_dt::sc_biguint< W > Class Template Reference
#include <sc_biguint.hh>
Public Member Functions
sc_biguint ()
sc_biguint (const sc_biguint< W > &v)
sc_biguint (const sc_unsigned &v)
sc_biguint (const sc_unsigned_subref &v)
template<class T >
sc_biguint (const sc_generic_base< T > &a)
sc_biguint (const sc_signed &v)
sc_biguint (const sc_signed_subref &v)
sc_biguint (const char *v)
sc_biguint (int64 v)
sc_biguint (uint64 v)
sc_biguint (long v)
sc_biguint (unsigned long v)
sc_biguint (int v)
sc_biguint (unsigned int v)
sc_biguint (double v)
sc_biguint (const sc_bv_base &v)
sc_biguint (const sc_lv_base &v)
sc_biguint (const sc_fxval &v)
sc_biguint (const sc_fxval_fast &v)
sc_biguint (const sc_fxnum &v)
sc_biguint (const sc_fxnum_fast &v)
~sc_biguint ()
sc_biguint< W > & operator= (const sc_biguint< W > &v)
sc_biguint< W > & operator= (const sc_unsigned &v)
sc_biguint< W > & operator= (const sc_unsigned_subref &v)
template<class T >
sc_biguint< W > & operator= (const sc_generic_base< T > &a)
sc_biguint< W > & operator= (const sc_signed &v)
sc_biguint< W > & operator= (const sc_signed_subref &v)
sc_biguint< W > & operator= (const char *v)
sc_biguint< W > & operator= (int64 v)
sc_biguint< W > & operator= (uint64 v)
sc_biguint< W > & operator= (long v)
sc_biguint< W > & operator= (unsigned long v)
sc_biguint< W > & operator= (int v)
sc_biguint< W > & operator= (unsigned int v)
sc_biguint< W > & operator= (double v)
sc_biguint< W > & operator= (const sc_bv_base &v)
sc_biguint< W > & operator= (const sc_lv_base &v)
sc_biguint< W > & operator= (const sc_int_base &v)
sc_biguint< W > & operator= (const sc_uint_base &v)
sc_biguint< W > & operator= (const sc_fxval &v)
sc_biguint< W > & operator= (const sc_fxval_fast &v)
sc_biguint< W > & operator= (const sc_fxnum &v)
sc_biguint< W > & operator= (const sc_fxnum_fast &v)
Public Member Functions inherited from sc_dt::sc_unsigned
sc_unsigned (int nb=sc_length_param().len())
sc_unsigned (const sc_unsigned &v)
sc_unsigned (const sc_signed &v)
template<class T >
sc_unsigned (const sc_generic_base< T > &v)
sc_unsigned (const sc_bv_base &v)
sc_unsigned (const sc_lv_base &v)
sc_unsigned (const sc_int_subref_r &v)
sc_unsigned (const sc_uint_subref_r &v)
sc_unsigned (const sc_signed_subref_r &v)
sc_unsigned (const sc_unsigned_subref_r &v)
const sc_unsigned & operator= (const sc_unsigned &v)
const sc_unsigned & operator= (const sc_unsigned_subref_r &a)
template<class T >
const sc_unsigned & operator= (const sc_generic_base< T > &a)
const sc_unsigned & operator= (const sc_signed &v)
const sc_unsigned & operator= (const sc_signed_subref_r &a)
const sc_unsigned & operator= (const char *v)
const sc_unsigned & operator= (int64 v)
const sc_unsigned & operator= (uint64 v)
const sc_unsigned & operator= (long v)
const sc_unsigned & operator= (unsigned long v)
const sc_unsigned & operator= (int v)
const sc_unsigned & operator= (unsigned int v)
const sc_unsigned & operator= (double v)
const sc_unsigned & operator= (const sc_int_base &v)
const sc_unsigned & operator= (const sc_uint_base &v)
const sc_unsigned & operator= (const sc_bv_base &)
const sc_unsigned & operator= (const sc_lv_base &)
const sc_unsigned & operator= (const sc_fxval &)
const sc_unsigned & operator= (const sc_fxval_fast &)
const sc_unsigned & operator= (const sc_fxnum &)
const sc_unsigned & operator= (const sc_fxnum_fast &)
virtual ~sc_unsigned ()
sc_digit * get_raw () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
sc_unsigned & operator++ ()
const sc_unsigned operator++ (int)
sc_unsigned & operator-- ()
const sc_unsigned operator-- (int)
void check_index (int i) const
void invalid_index (int i) const
sc_unsigned_bitref & operator[] (int i)
const sc_unsigned_bitref_r & operator[] (int i) const
sc_unsigned_bitref & bit (int i)
const sc_unsigned_bitref_r & bit (int i) const
void check_range (int l, int r) const
void invalid_range (int l, int r) const
sc_unsigned_subref & range (int i, int j)
const sc_unsigned_subref_r & range (int i, int j) const
sc_unsigned_subref & operator() (int i, int j)
const sc_unsigned_subref_r & operator() (int i, int j) const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
void dump (::std::ostream &os=::std::cout) const
int length () const
bool iszero () const
bool sign () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
bool test (int i) const
void set (int i)
void clear (int i)
void set (int i, bool v)
void invert (int i)
void reverse ()
void get_packed_rep (sc_digit *buf) const
void set_packed_rep (sc_digit *buf)
const sc_unsigned & operator+= (const sc_signed &v)
const sc_unsigned & operator+= (const sc_unsigned &v)
const sc_unsigned & operator+= (int64 v)
const sc_unsigned & operator+= (uint64 v)
const sc_unsigned & operator+= (long v)
const sc_unsigned & operator+= (unsigned long v)
const sc_unsigned & operator+= (int v)
const sc_unsigned & operator+= (unsigned int v)
const sc_unsigned & operator+= (const sc_int_base &v)
const sc_unsigned & operator+= (const sc_uint_base &v)
const sc_unsigned & operator-= (const sc_signed &v)
const sc_unsigned & operator-= (const sc_unsigned &v)
const sc_unsigned & operator-= (int64 v)
const sc_unsigned & operator-= (uint64 v)
const sc_unsigned & operator-= (long v)
const sc_unsigned & operator-= (unsigned long v)
const sc_unsigned & operator-= (int v)
const sc_unsigned & operator-= (unsigned int v)
const sc_unsigned & operator-= (const sc_int_base &v)
const sc_unsigned & operator-= (const sc_uint_base &v)
const sc_unsigned & operator*= (const sc_signed &v)
const sc_unsigned & operator*= (const sc_unsigned &v)
const sc_unsigned & operator*= (int64 v)
const sc_unsigned & operator*= (uint64 v)
const sc_unsigned & operator*= (long v)
const sc_unsigned & operator*= (unsigned long v)
const sc_unsigned & operator*= (int v)
const sc_unsigned & operator*= (unsigned int v)
const sc_unsigned & operator*= (const sc_int_base &v)
const sc_unsigned & operator*= (const sc_uint_base &v)
const sc_unsigned & operator/= (const sc_signed &v)
const sc_unsigned & operator/= (const sc_unsigned &v)
const sc_unsigned & operator/= (int64 v)
const sc_unsigned & operator/= (uint64 v)
const sc_unsigned & operator/= (long v)
const sc_unsigned & operator/= (unsigned long v)
const sc_unsigned & operator/= (int v)
const sc_unsigned & operator/= (unsigned int v)
const sc_unsigned & operator/= (const sc_int_base &v)
const sc_unsigned & operator/= (const sc_uint_base &v)
const sc_unsigned & operator%= (const sc_signed &v)
const sc_unsigned & operator%= (const sc_unsigned &v)
const sc_unsigned & operator%= (int64 v)
const sc_unsigned & operator%= (uint64 v)
const sc_unsigned & operator%= (long v)
const sc_unsigned & operator%= (unsigned long v)
const sc_unsigned & operator%= (int v)
const sc_unsigned & operator%= (unsigned int v)
const sc_unsigned & operator%= (const sc_int_base &v)
const sc_unsigned & operator%= (const sc_uint_base &v)
const sc_unsigned & operator&= (const sc_signed &v)
const sc_unsigned & operator&= (const sc_unsigned &v)
const sc_unsigned & operator&= (int64 v)
const sc_unsigned & operator&= (uint64 v)
const sc_unsigned & operator&= (long v)
const sc_unsigned & operator&= (unsigned long v)
const sc_unsigned & operator&= (int v)
const sc_unsigned & operator&= (unsigned int v)
const sc_unsigned & operator&= (const sc_int_base &v)
const sc_unsigned & operator&= (const sc_uint_base &v)
const sc_unsigned & operator|= (const sc_signed &v)
const sc_unsigned & operator|= (const sc_unsigned &v)
const sc_unsigned & operator|= (int64 v)
const sc_unsigned & operator|= (uint64 v)
const sc_unsigned & operator|= (long v)
const sc_unsigned & operator|= (unsigned long v)
const sc_unsigned & operator|= (int v)
const sc_unsigned & operator|= (unsigned int v)
const sc_unsigned & operator|= (const sc_int_base &v)
const sc_unsigned & operator|= (const sc_uint_base &v)
const sc_unsigned & operator^= (const sc_signed &v)
const sc_unsigned & operator^= (const sc_unsigned &v)
const sc_unsigned & operator^= (int64 v)
const sc_unsigned & operator^= (uint64 v)
const sc_unsigned & operator^= (long v)
const sc_unsigned & operator^= (unsigned long v)
const sc_unsigned & operator^= (int v)
const sc_unsigned & operator^= (unsigned int v)
const sc_unsigned & operator^= (const sc_int_base &v)
const sc_unsigned & operator^= (const sc_uint_base &v)
const sc_unsigned & operator<<= (const sc_signed &v)
const sc_unsigned & operator<<= (const sc_unsigned &v)
const sc_unsigned & operator<<= (int64 v)
const sc_unsigned & operator<<= (uint64 v)
const sc_unsigned & operator<<= (long v)
const sc_unsigned & operator<<= (unsigned long v)
const sc_unsigned & operator<<= (int v)
const sc_unsigned & operator<<= (unsigned int v)
const sc_unsigned & operator<<= (const sc_int_base &v)
const sc_unsigned & operator<<= (const sc_uint_base &v)
const sc_unsigned & operator>>= (const sc_signed &v)
const sc_unsigned & operator>>= (const sc_unsigned &v)
const sc_unsigned & operator>>= (int64 v)
const sc_unsigned & operator>>= (uint64 v)
const sc_unsigned & operator>>= (long v)
const sc_unsigned & operator>>= (unsigned long v)
const sc_unsigned & operator>>= (int v)
const sc_unsigned & operator>>= (unsigned int v)
const sc_unsigned & operator>>= (const sc_int_base &v)
const sc_unsigned & operator>>= (const sc_uint_base &v)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Additional Inherited Members
Static Public Attributes inherited from sc_dt::sc_unsigned
static sc_core::sc_vpool< sc_unsigned > m_pool
Detailed Description
template<int W>
class sc_dt::sc_biguint< W >
Definition at line 65 of file sc_biguint.hh.
Constructor & Destructor Documentation
sc_biguint() [1/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint () inline
Definition at line 91 of file sc_biguint.hh.
sc_biguint() [2/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_biguint< W > & v) inline
Definition at line 92 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [3/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_unsigned & v) inline
Definition at line 93 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [4/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_unsigned_subref & v) inline
Definition at line 94 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [5/21]
template<int W> template<class T > sc_dt::sc_biguint< W >::sc_biguint (const sc_generic_base< T > & a) inline
Definition at line 97 of file sc_biguint.hh.
sc_biguint() [6/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_signed & v) inline
Definition at line 102 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [7/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_signed_subref & v) inline
Definition at line 103 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [8/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const char * v) inline
Definition at line 104 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [9/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (int64 v) inline
Definition at line 105 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [10/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (uint64 v) inline
Definition at line 106 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [11/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (long v) inline
Definition at line 107 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [12/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (unsigned long v) inline
Definition at line 108 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [13/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (int v) inline
Definition at line 109 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [14/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (unsigned int v) inline
Definition at line 110 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [15/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (double v) inline
Definition at line 111 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [16/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_bv_base & v) inline
Definition at line 112 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [17/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_lv_base & v) inline
Definition at line 113 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [18/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_fxval & v) inline explicit
Definition at line 115 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [19/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_fxval_fast & v) inline explicit
Definition at line 116 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [20/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_fxnum & v) inline explicit
Definition at line 117 of file sc_biguint.hh.
References ArmISA::v.
sc_biguint() [21/21]
template<int W> sc_dt::sc_biguint< W >::sc_biguint (const sc_fxnum_fast & v) inline explicit
Definition at line 118 of file sc_biguint.hh.
References ArmISA::v.
~sc_biguint()
template<int W> sc_dt::sc_biguint< W >::~sc_biguint () inline
Definition at line 122 of file sc_biguint.hh.
Member Function Documentation
operator=() [1/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_biguint< W > & v) inline
Definition at line 127 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [2/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_unsigned & v) inline
Definition at line 134 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [3/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_unsigned_subref & v) inline
Definition at line 141 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [4/22]
template<int W> template<class T > sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_generic_base< T > & a) inline
Definition at line 149 of file sc_biguint.hh.
operator=() [5/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_signed & v) inline
Definition at line 155 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [6/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_signed_subref & v) inline
Definition at line 162 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [7/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const char * v) inline
Definition at line 169 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [8/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (int64 v) inline
Definition at line 176 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [9/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (uint64 v) inline
Definition at line 183 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [10/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (long v) inline
Definition at line 190 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [11/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (unsigned long v) inline
Definition at line 197 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [12/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (int v) inline
Definition at line 204 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [13/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (unsigned int v) inline
Definition at line 211 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [14/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (double v) inline
Definition at line 218 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [15/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_bv_base & v) inline
Definition at line 226 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [16/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_lv_base & v) inline
Definition at line 233 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [17/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_int_base & v) inline
Definition at line 240 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [18/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_uint_base & v) inline
Definition at line 247 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [19/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_fxval & v) inline
Definition at line 254 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [20/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_fxval_fast & v) inline
Definition at line 261 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [21/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_fxnum & v) inline
Definition at line 268 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
operator=() [22/22]
template<int W> sc_biguint<W>& sc_dt::sc_biguint< W >::operator= (const sc_fxnum_fast & v) inline
Definition at line 275 of file sc_biguint.hh.
References sc_dt::sc_unsigned::operator=().
The documentation for this class was generated from the following file:
systemc/ext/dt/int/sc_biguint.hh