gem5: PCEvent Class Reference
PCEvent Class Reference abstract
#include <pc_event.hh>
Public Member Functions
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
virtual void process (ThreadContext *tc)=0
Protected Attributes
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 45 of file pc_event.hh.
Constructor & Destructor Documentation
PCEvent()
PCEvent::PCEvent (PCEventScope * q, const std::string & desc, Addr pc) inline
Definition at line 132 of file pc_event.hh.
References PCEventScope::schedule(), and scope.
~PCEvent()
virtual PCEvent::~PCEvent () inline virtual
Definition at line 55 of file pc_event.hh.
Member Function Documentation
descr()
std::string PCEvent::descr () const inline
Definition at line 60 of file pc_event.hh.
References description.
Referenced by Linux::DmesgDumpEvent::process(), Linux::KernelPanicEvent::process(), BreakPCEvent::process(), and PanicPCEvent::process().
name()
virtual const std::string PCEvent::name () const inline virtual
Reimplemented in HardBreakpoint.
Definition at line 58 of file pc_event.hh.
References description.
Referenced by Linux::DebugPrintkEvent::process(), Linux::DmesgDumpEvent::process(), Linux::KernelPanicEvent::process(), BreakPCEvent::process(), and PanicPCEvent::process().
pc()
Addr PCEvent::pc () const inline
Definition at line 61 of file pc_event.hh.
References evpc, and process().
Referenced by PCEventQueue::doService(), PCEventQueue::equal_range(), PCEventQueue::MapCompare::operator()(), PCEventQueue::remove(), PCEventQueue::schedule(), and PCEventQueue::service().
process()
virtual void PCEvent::process (ThreadContext * tc) pure virtual
Implemented in HardBreakpoint, PanicPCEvent, BreakPCEvent, DumpStatsPCEvent, Linux::UDelayEvent, Linux::KernelPanicEvent, Linux::DmesgDumpEvent, LinuxMipsSystem::PrintThreadInfo, LinuxAlphaSystem::PrintThreadInfo, FreeBSD::UDelayEvent, LinuxMipsSystem::SkipDelayLoopEvent, LinuxAlphaSystem::SkipDelayLoopEvent, Linux::DebugPrintkEvent, FreebsdAlphaSystem::SkipCalibrateClocksEvent, IdleStartEvent, IdleStartEvent, IdleStartEvent, and SkipFuncEvent.
Referenced by pc().
remove()
bool PCEvent::remove () inline
Definition at line 139 of file pc_event.hh.
References panic, PCEventScope::remove(), and scope.
Member Data Documentation
description
std::string PCEvent::description protected
Definition at line 48 of file pc_event.hh.
Referenced by descr(), and name().
evpc
Addr PCEvent::evpc protected
Definition at line 50 of file pc_event.hh.
Referenced by pc().
scope
PCEventScope* PCEvent::scope protected
Definition at line 49 of file pc_event.hh.
Referenced by PCEvent(), and remove().
The documentation for this class was generated from the following file:
cpu/pc_event.hh