gem5: Gicv3Its Class Reference
Gicv3Its Class Reference
GICv3 ITS module.
#include <gic_v3_its.hh>
Classes
class DataPort
Public Types
enum : Addr {
GITS_CTLR = itsControl + 0x0000, GITS_IIDR = itsControl + 0x0004, GITS_TYPER = itsControl + 0x0008, GITS_CBASER = itsControl + 0x0080,
GITS_CWRITER = itsControl + 0x0088, GITS_CREADR = itsControl + 0x0090, GITS_PIDR2 = itsControl + 0xffe8, GITS_TRANSLATER = itsTranslate + 0x0040
}
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Port & getPort (const std::string &if_name, PortID idx) override
Get a port with a given name and index.
bool recvTimingResp (PacketPtr pkt)
void recvReqRetry ()
Gicv3Its (const Gicv3ItsParams *params)
void setGIC (Gicv3 *_gic)
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
DrainState drain () override
Notify an object that it needs to drain its state.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void translate (PacketPtr pkt)
BitUnion32 (CTLR) Bitfield< 31 > quiescent
EndBitUnion (CTLR) BitUnion64(CRDWR) Bitfield< 63
EndBitUnion (CRDWR) BitUnion64(CBASER) Bitfield< 63
EndBitUnion (CBASER) BitUnion64(BASER) Bitfield< 63 > valid
EndBitUnion (BASER) BitUnion64(TYPER) Bitfield< 63
EndBitUnion (TYPER) CTLR gitsControl
bool idOutOfRange (uint32_t event_id, uint8_t itt_range) const
Returns TRUE if the eventID supplied has bits above the implemented size or above the itt_range.
bool deviceOutOfRange (uint32_t device_id) const
Returns TRUE if the value supplied has bits above the implemented range or if the value supplied exceeds the maximum configured size in the appropriate GITS_BASER<n>
bool sizeOutOfRange (uint32_t size) const
Returns TRUE if the value (size) supplied exceeds the maximum allowed by GITS_TYPER.ID_bits.
bool collectionOutOfRange (uint32_t collection_id) const
Returns TRUE if the value supplied has bits above the implemented range or if the value exceeds the total number of collections supported in hardware and external memory.
bool lpiOutOfRange (uint32_t intid) const
Returns TRUE if the value supplied is larger than that permitted by GICD_TYPER.IDbits or not in the LPI range and is not 1023.
BitUnion64 (DTE) Bitfield< 57
EndBitUnion (DTE) BitUnion64(ITTE) Bitfield< 59
EndBitUnion (ITTE) BitUnion64(CTE) Bitfield< 40
EndBitUnion (CTE) enum InterruptType
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
DataPort dmaPort
Bitfield< 7, 4 > itsNumber
Bitfield< 1 > imDe
Bitfield< 0 > enabled
high
Bitfield< 31, 0 > low
Bitfield< 19, 5 > offset
Bitfield< 0 > retry
Bitfield< 0 > stalled
Bitfield< 63 > valid
Bitfield< 61, 59 > innerCache
Bitfield< 55, 53 > outerCache
Bitfield< 51, 12 > physAddr
Bitfield< 11, 10 > shareability
Bitfield< 7, 0 > size
Bitfield< 62 > indirect
Bitfield< 58, 56 > type
Bitfield< 52, 48 > entrySize
Bitfield< 47, 12 > physAddr
Bitfield< 9, 8 > pageSize
Bitfield< 37 > vmovp
Bitfield< 36 > cil
Bitfield< 35, 32 > cidBits
Bitfield< 31, 24 > hcc
Bitfield< 19 > pta
Bitfield< 18 > seis
Bitfield< 17, 13 > devBits
Bitfield< 12, 8 > idBits
Bitfield< 7, 4 > ittEntrySize
Bitfield< 2 > cct
Bitfield< 1 > _virtual
Bitfield< 0 > physical
TYPER gitsTyper
CBASER gitsCbaser
CRDWR gitsCreadr
CRDWR gitsCwriter
uint32_t gitsIidr
uint32_t gitsTranslater
std::vector< BASER > tableBases
ittRange
Bitfield< 52, 1 > ittAddress
Bitfield< 0 > valid
vpeid
Bitfield< 45, 30 > icid
Bitfield< 29, 16 > intNumHyp
Bitfield< 15, 2 > intNum
Bitfield< 1 > intType
rdBase
Static Public Attributes
static const uint32_t itsControl = 0x0
static const uint32_t itsTranslate = 0x10000
static const AddrRange GITS_BASER
static const uint32_t NUM_BASER_REGS = 8
static const uint64_t BASER_INDIRECT = 0x4000000000000000
static const uint64_t BASER_TYPE = 0x0700000000000000
static const uint64_t BASER_ESZ = 0x001F000000000000
static const uint64_t BASER_SZ = 0x00000000000000FF
static const uint64_t BASER_WMASK
static const uint64_t BASER_WMASK_UNIMPL
static const uint32_t CTLR_QUIESCENT = 0x80000000
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Private Types
enum ItsTables { DEVICE_TABLE = 1, VPE_TABLE = 2, TRANSLATION_TABLE = 3, COLLECTION_TABLE = 4 }
enum PageSize { SIZE_4K, SIZE_16K, SIZE_64K }
Private Member Functions
uint64_t maxCommands () const
void checkCommandQueue ()
void incrementReadPointer ()
Gicv3Redistributor * getRedistributor (uint64_t rd_base)
Gicv3Redistributor * getRedistributor (CTE cte)
ItsAction runProcess (ItsProcess *proc, PacketPtr pkt)
ItsAction runProcessTiming (ItsProcess *proc, PacketPtr pkt)
ItsAction runProcessAtomic (ItsProcess *proc, PacketPtr pkt)
Addr pageAddress (enum ItsTables table)
void moveAllPendingState (Gicv3Redistributor *rd1, Gicv3Redistributor *rd2)
Private Attributes
std::queue< ItsAction > packetsToRetry
uint32_t masterId
Gicv3 * gic
EventFunctionWrapper commandEvent
bool pendingCommands
uint32_t pendingTranslations
Friends
class ::ItsProcess
class ::ItsTranslation
class ::ItsCommand
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
GICv3 ITS module.
This class is just modelling a pio device with its memory mapped registers. Most of the ITS functionalities are implemented as processes (ItsProcess) objects, like ItsTranslation or ItsCommand. Main job of Gicv3Its is to spawn those processes upon receival of packets.
Definition at line 76 of file gic_v3_its.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum : Addr
Enumerator
GITS_CTLR
GITS_IIDR
GITS_TYPER
GITS_CBASER
GITS_CWRITER
GITS_CREADR
GITS_PIDR2
GITS_TRANSLATER
Definition at line 132 of file gic_v3_its.hh.
ItsTables
enum Gicv3Its::ItsTables private
Enumerator
DEVICE_TABLE
VPE_TABLE
TRANSLATION_TABLE
COLLECTION_TABLE
Definition at line 302 of file gic_v3_its.hh.
PageSize
enum Gicv3Its::PageSize private
Enumerator
SIZE_4K
SIZE_16K
SIZE_64K
Definition at line 310 of file gic_v3_its.hh.
Constructor & Destructor Documentation
Gicv3Its()
Gicv3Its::Gicv3Its (const Gicv3ItsParams * params)
Definition at line 776 of file gic_v3_its.cc.
References checkCommandQueue(), COLLECTION_TABLE, DEVICE_TABLE, SimObject::name(), pendingCommands, pendingTranslations, and tableBases.
Referenced by moveAllPendingState().
Member Function Documentation
BitUnion32()
Gicv3Its::BitUnion32 (CTLR)
BitUnion64()
Gicv3Its::BitUnion64 (DTE)
checkCommandQueue()
void Gicv3Its::checkCommandQueue () private
Definition at line 1080 of file gic_v3_its.cc.
References DPRINTF, gitsCbaser, gitsCreadr, gitsCwriter, maxCommands(), pendingCommands, and runProcess().
Referenced by Gicv3Its(), and write().
collectionOutOfRange()
bool Gicv3Its::collectionOutOfRange (uint32_t collection_id) const
Returns TRUE if the value supplied has bits above the implemented range or if the value exceeds the total number of collections supported in hardware and external memory.
Definition at line 1006 of file gic_v3_its.cc.
References gitsTyper, and ULL.
Referenced by ItsTranslation::translateLPI().
deviceOutOfRange()
bool Gicv3Its::deviceOutOfRange (uint32_t device_id) const
Returns TRUE if the value supplied has bits above the implemented range or if the value supplied exceeds the maximum configured size in the appropriate GITS_BASER<n>
Definition at line 994 of file gic_v3_its.cc.
References gitsTyper, and ULL.
Referenced by ItsTranslation::translateLPI().
drain()
DrainState Gicv3Its::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 1025 of file gic_v3_its.cc.
References DPRINTF, Drained, Draining, pendingCommands, and pendingTranslations.
EndBitUnion() [1/8]
Gicv3Its::EndBitUnion (CTLR)
EndBitUnion() [2/8]
Gicv3Its::EndBitUnion (CRDWR)
EndBitUnion() [3/8]
Gicv3Its::EndBitUnion (CBASER)
EndBitUnion() [4/8]
Gicv3Its::EndBitUnion (BASER)
EndBitUnion() [5/8]
Gicv3Its::EndBitUnion (TYPER)
EndBitUnion() [6/8]
Gicv3Its::EndBitUnion (DTE)
EndBitUnion() [7/8]
Gicv3Its::EndBitUnion (ITTE)
EndBitUnion() [8/8]
Gicv3Its::EndBitUnion (CTE) inline
Definition at line 283 of file gic_v3_its.hh.
getAddrRanges()
AddrRangeList Gicv3Its::getAddrRanges () const override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 809 of file gic_v3_its.cc.
References DPRINTF, BasicPioDevice::pioAddr, BasicPioDevice::pioSize, and RangeSize().
getPort()
Port & Gicv3Its::getPort (const std::string & if_name, PortID idx) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 1108 of file gic_v3_its.cc.
References dmaPort, and PioDevice::getPort().
getRedistributor() [1/2]
Gicv3Redistributor * Gicv3Its::getRedistributor (uint64_t rd_base) private
Definition at line 1232 of file gic_v3_its.cc.
References Gicv3::getRedistributor(), Gicv3::getRedistributorByAddr(), gic, and gitsTyper.
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::movall(), ItsCommand::movi(), and ItsTranslation::translateLPI().
getRedistributor() [2/2]
Gicv3Redistributor* Gicv3Its::getRedistributor (CTE cte) inline private
Definition at line 293 of file gic_v3_its.hh.
idOutOfRange()
bool Gicv3Its::idOutOfRange (uint32_t event_id, uint8_t itt_range) const
Returns TRUE if the eventID supplied has bits above the implemented size or above the itt_range.
Definition at line 986 of file gic_v3_its.cc.
References gitsTyper, and ULL.
Referenced by ItsTranslation::translateLPI().
incrementReadPointer()
void Gicv3Its::incrementReadPointer () private
Definition at line 1062 of file gic_v3_its.cc.
References gitsCreadr, and maxCommands().
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::inv(), ItsCommand::invall(), ItsCommand::main(), ItsCommand::mapc(), ItsCommand::mapd(), ItsCommand::mapi(), ItsCommand::mapti(), and ItsCommand::movi().
lpiOutOfRange()
bool Gicv3Its::lpiOutOfRange (uint32_t intid) const
Returns TRUE if the value supplied is larger than that permitted by GICD_TYPER.IDbits or not in the LPI range and is not 1023.
Definition at line 1017 of file gic_v3_its.cc.
References Gicv3Distributor::IDBITS, Gicv3::INTID_SPURIOUS, Gicv3Redistributor::SMALLEST_LPI_ID, and ULL.
Referenced by ItsCommand::mapi(), and ItsCommand::mapti().
maxCommands()
uint64_t Gicv3Its::maxCommands () const private
Definition at line 1074 of file gic_v3_its.cc.
References gitsCbaser.
Referenced by checkCommandQueue(), and incrementReadPointer().
moveAllPendingState()
void Gicv3Its::moveAllPendingState (Gicv3Redistributor * rd1, Gicv3Redistributor * rd2) private
Definition at line 1269 of file gic_v3_its.cc.
References Gicv3Its(), Gicv3Redistributor::lpiIDBits, Gicv3Redistributor::lpiPendingTablePtr, Gicv3Redistributor::memProxy, PortProxy::memsetBlob(), PortProxy::readBlob(), ULL, Gicv3Redistributor::updateDistributor(), and PortProxy::writeBlob().
Referenced by ItsCommand::movall().
pageAddress()
Addr Gicv3Its::pageAddress (enum ItsTables table) private
Definition at line 1244 of file gic_v3_its.cc.
References ArmISA::b, X86ISA::base, bits(), mbits(), panic, panic_if, SIZE_16K, SIZE_4K, SIZE_64K, and tableBases.
Referenced by ItsProcess::readDeviceTable(), ItsProcess::readIrqCollectionTable(), ItsProcess::writeDeviceTable(), and ItsProcess::writeIrqCollectionTable().
read()
Tick Gicv3Its::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 819 of file gic_v3_its.cc.
References addr, AddrRange::contains(), DPRINTF, Packet::getAddr(), Gicv3::getDistributor(), gic, Gicv3Distributor::gicdPidr2, GITS_BASER, GITS_CBASER, GITS_CREADR, GITS_CTLR, GITS_CWRITER, GITS_IIDR, GITS_PIDR2, GITS_TRANSLATER, GITS_TYPER, gitsCbaser, gitsCreadr, gitsCwriter, gitsIidr, gitsTranslater, gitsTyper, LittleEndianByteOrder, Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, Packet::setUintX(), AddrRange::start(), and tableBases.
recvReqRetry()
void Gicv3Its::recvReqRetry ()
Definition at line 1117 of file gic_v3_its.cc.
References ArmISA::a, dmaPort, packetsToRetry, ItsAction::pkt, SEND_REQ, MasterPort::sendTimingReq(), and ItsAction::type.
Referenced by Gicv3Its::DataPort::recvReqRetry().
recvTimingResp()
bool Gicv3Its::recvTimingResp (PacketPtr pkt)
Definition at line 1134 of file gic_v3_its.cc.
References Packet::headerDelay, Packet::payloadDelay, Packet::popSenderState(), runProcessTiming(), and safe_cast().
Referenced by Gicv3Its::DataPort::recvTimingResp().
runProcess()
ItsAction Gicv3Its::runProcess (ItsProcess * proc, PacketPtr pkt) private
Definition at line 1148 of file gic_v3_its.cc.
References System::isAtomicMode(), System::isTimingMode(), panic, runProcessAtomic(), runProcessTiming(), and PioDevice::sys.
Referenced by checkCommandQueue(), and translate().
runProcessAtomic()
ItsAction Gicv3Its::runProcessAtomic (ItsProcess * proc, PacketPtr pkt) private
Definition at line 1191 of file gic_v3_its.cc.
References ItsAction::delay, dmaPort, panic, ItsAction::pkt, ItsProcess::run(), SEND_REQ, MasterPort::sendAtomic(), TERMINATE, and ItsAction::type.
Referenced by runProcess().
runProcessTiming()
ItsAction Gicv3Its::runProcessTiming (ItsProcess * proc, PacketPtr pkt) private
Definition at line 1160 of file gic_v3_its.cc.
References Clocked::clockEdge(), commandEvent, dmaPort, packetsToRetry, panic, pendingCommands, ItsAction::pkt, Packet::pushSenderState(), ItsProcess::run(), EventManager::schedule(), Event::scheduled(), SEND_REQ, MasterPort::sendTimingReq(), TERMINATE, and ItsAction::type.
Referenced by recvTimingResp(), and runProcess().
serialize()
void Gicv3Its::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1036 of file gic_v3_its.cc.
References gitsCbaser, gitsCreadr, gitsCwriter, gitsIidr, gitsTyper, SERIALIZE_CONTAINER, SERIALIZE_SCALAR, and tableBases.
setGIC()
void Gicv3Its::setGIC (Gicv3 * _gic)
Definition at line 802 of file gic_v3_its.cc.
References gic.
Referenced by Gicv3::init().
sizeOutOfRange()
bool Gicv3Its::sizeOutOfRange (uint32_t size) const
Returns TRUE if the value (size) supplied exceeds the maximum allowed by GITS_TYPER.ID_bits.
Size is the parameter which is passed to the ITS via the MAPD command and is stored in the DTE.ittRange field.
Definition at line 1000 of file gic_v3_its.cc.
References gitsTyper.
translate()
void Gicv3Its::translate (PacketPtr pkt)
Definition at line 1223 of file gic_v3_its.cc.
References DPRINTF, and runProcess().
Referenced by write().
unserialize()
void Gicv3Its::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1049 of file gic_v3_its.cc.
References gitsCbaser, gitsCreadr, gitsCwriter, gitsIidr, gitsTyper, tableBases, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
write()
Tick Gicv3Its::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 893 of file gic_v3_its.cc.
References addr, BASER_WMASK, BASER_WMASK_UNIMPL, checkCommandQueue(), AddrRange::contains(), CTLR_QUIESCENT, DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), GITS_BASER, GITS_CBASER, GITS_CREADR, GITS_CTLR, GITS_CWRITER, GITS_IIDR, GITS_TRANSLATER, GITS_TYPER, gitsCbaser, gitsCreadr, gitsCwriter, Packet::makeAtomicResponse(), panic, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, AddrRange::start(), tableBases, translate(), and X86ISA::val.
Friends And Related Function Documentation
::ItsCommand
friend class ::ItsCommand friend
Definition at line 80 of file gic_v3_its.hh.
::ItsProcess
friend class ::ItsProcess friend
Definition at line 78 of file gic_v3_its.hh.
::ItsTranslation
friend class ::ItsTranslation friend
Definition at line 79 of file gic_v3_its.hh.
Member Data Documentation
_virtual
Bitfield<1> Gicv3Its::_virtual
Definition at line 211 of file gic_v3_its.hh.
BASER_ESZ
const uint64_t Gicv3Its::BASER_ESZ = 0x001F000000000000 static
Definition at line 122 of file gic_v3_its.hh.
BASER_INDIRECT
const uint64_t Gicv3Its::BASER_INDIRECT = 0x4000000000000000 static
Definition at line 120 of file gic_v3_its.hh.
BASER_SZ
const uint64_t Gicv3Its::BASER_SZ = 0x00000000000000FF static
Definition at line 123 of file gic_v3_its.hh.
BASER_TYPE
const uint64_t Gicv3Its::BASER_TYPE = 0x0700000000000000 static
Definition at line 121 of file gic_v3_its.hh.
BASER_WMASK
const uint64_t Gicv3Its::BASER_WMASK static
Initial value:
=
        ~(BASER_INDIRECT | BASER_TYPE | BASER_ESZ)
Definition at line 124 of file gic_v3_its.hh.
Referenced by write().
BASER_WMASK_UNIMPL
const uint64_t Gicv3Its::BASER_WMASK_UNIMPL static
Initial value:
=
        ~(BASER_INDIRECT | BASER_TYPE | BASER_ESZ | BASER_SZ)
Definition at line 126 of file gic_v3_its.hh.
Referenced by write().
cct
Bitfield<2> Gicv3Its::cct
Definition at line 210 of file gic_v3_its.hh.
cidBits
Bitfield<35, 32> Gicv3Its::cidBits
Definition at line 203 of file gic_v3_its.hh.
cil
Bitfield<36> Gicv3Its::cil
Definition at line 202 of file gic_v3_its.hh.
commandEvent
EventFunctionWrapper Gicv3Its::commandEvent private
Definition at line 326 of file gic_v3_its.hh.
Referenced by runProcessTiming().
CTLR_QUIESCENT
const uint32_t Gicv3Its::CTLR_QUIESCENT = 0x80000000 static
Definition at line 130 of file gic_v3_its.hh.
Referenced by write().
devBits
Bitfield<17, 13> Gicv3Its::devBits
Definition at line 207 of file gic_v3_its.hh.
dmaPort
DataPort Gicv3Its::dmaPort
Definition at line 99 of file gic_v3_its.hh.
Referenced by getPort(), recvReqRetry(), runProcessAtomic(), and runProcessTiming().
enabled
Bitfield<0> Gicv3Its::enabled
Definition at line 162 of file gic_v3_its.hh.
entrySize
Bitfield<52, 48> Gicv3Its::entrySize
Definition at line 191 of file gic_v3_its.hh.
gic
Gicv3* Gicv3Its::gic private
Definition at line 325 of file gic_v3_its.hh.
Referenced by getRedistributor(), read(), and setGIC().
GITS_BASER
const AddrRange Gicv3Its::GITS_BASER static
Definition at line 113 of file gic_v3_its.hh.
Referenced by read(), and write().
gitsCbaser
CBASER Gicv3Its::gitsCbaser
Definition at line 217 of file gic_v3_its.hh.
Referenced by checkCommandQueue(), maxCommands(), read(), ItsCommand::readCommand(), serialize(), unserialize(), and write().
gitsCreadr
CRDWR Gicv3Its::gitsCreadr
Definition at line 218 of file gic_v3_its.hh.
Referenced by checkCommandQueue(), incrementReadPointer(), ItsCommand::main(), read(), ItsCommand::readCommand(), serialize(), unserialize(), and write().
gitsCwriter
CRDWR Gicv3Its::gitsCwriter
Definition at line 219 of file gic_v3_its.hh.
Referenced by checkCommandQueue(), ItsCommand::main(), read(), serialize(), unserialize(), and write().
gitsIidr
uint32_t Gicv3Its::gitsIidr
Definition at line 220 of file gic_v3_its.hh.
Referenced by read(), serialize(), and unserialize().
gitsTranslater
uint32_t Gicv3Its::gitsTranslater
Definition at line 221 of file gic_v3_its.hh.
Referenced by ItsTranslation::main(), and read().
gitsTyper
TYPER Gicv3Its::gitsTyper
Definition at line 216 of file gic_v3_its.hh.
Referenced by collectionOutOfRange(), deviceOutOfRange(), getRedistributor(), idOutOfRange(), read(), serialize(), sizeOutOfRange(), and unserialize().
hcc
Bitfield<31, 24> Gicv3Its::hcc
Definition at line 204 of file gic_v3_its.hh.
high
Gicv3Its::high
Definition at line 167 of file gic_v3_its.hh.
icid
Bitfield<45, 30> Gicv3Its::icid
Definition at line 273 of file gic_v3_its.hh.
Referenced by ItsCommand::invall(), and ItsCommand::mapc().
idBits
Bitfield<12, 8> Gicv3Its::idBits
Definition at line 208 of file gic_v3_its.hh.
imDe
Bitfield<1> Gicv3Its::imDe
Definition at line 161 of file gic_v3_its.hh.
indirect
Bitfield<62> Gicv3Its::indirect
Definition at line 187 of file gic_v3_its.hh.
innerCache
Bitfield< 61, 59 > Gicv3Its::innerCache
Definition at line 178 of file gic_v3_its.hh.
intNum
Bitfield<15, 2> Gicv3Its::intNum
Definition at line 275 of file gic_v3_its.hh.
intNumHyp
Bitfield<29, 16> Gicv3Its::intNumHyp
Definition at line 274 of file gic_v3_its.hh.
intType
Bitfield<1> Gicv3Its::intType
Definition at line 276 of file gic_v3_its.hh.
itsControl
const uint32_t Gicv3Its::itsControl = 0x0 static
Definition at line 109 of file gic_v3_its.hh.
itsNumber
Bitfield<7, 4> Gicv3Its::itsNumber
Definition at line 160 of file gic_v3_its.hh.
itsTranslate
const uint32_t Gicv3Its::itsTranslate = 0x10000 static
Definition at line 110 of file gic_v3_its.hh.
ittAddress
Bitfield<52, 1> Gicv3Its::ittAddress
Definition at line 267 of file gic_v3_its.hh.
ittEntrySize
Bitfield<7, 4> Gicv3Its::ittEntrySize
Definition at line 209 of file gic_v3_its.hh.
ittRange
Gicv3Its::ittRange
Definition at line 266 of file gic_v3_its.hh.
low
Bitfield< 31, 0 > Gicv3Its::low
Definition at line 168 of file gic_v3_its.hh.
masterId
uint32_t Gicv3Its::masterId private
Definition at line 324 of file gic_v3_its.hh.
Referenced by ItsProcess::doRead(), and ItsProcess::doWrite().
NUM_BASER_REGS
const uint32_t Gicv3Its::NUM_BASER_REGS = 8 static
Definition at line 115 of file gic_v3_its.hh.
offset
Bitfield<19, 5> Gicv3Its::offset
Definition at line 169 of file gic_v3_its.hh.
outerCache
Bitfield< 55, 53 > Gicv3Its::outerCache
Definition at line 179 of file gic_v3_its.hh.
packetsToRetry
std::queue<ItsAction> Gicv3Its::packetsToRetry private
Definition at line 323 of file gic_v3_its.hh.
Referenced by recvReqRetry(), and runProcessTiming().
pageSize
Bitfield<9, 8> Gicv3Its::pageSize
Definition at line 194 of file gic_v3_its.hh.
pendingCommands
bool Gicv3Its::pendingCommands private
Definition at line 328 of file gic_v3_its.hh.
Referenced by checkCommandQueue(), drain(), Gicv3Its(), ItsCommand::ItsCommand(), runProcessTiming(), ItsCommand::~ItsCommand(), and ItsTranslation::~ItsTranslation().
pendingTranslations
uint32_t Gicv3Its::pendingTranslations private
Definition at line 329 of file gic_v3_its.hh.
Referenced by drain(), Gicv3Its(), ItsTranslation::ItsTranslation(), ItsCommand::~ItsCommand(), and ItsTranslation::~ItsTranslation().
physAddr [1/2]
Bitfield<51, 12> Gicv3Its::physAddr
Definition at line 180 of file gic_v3_its.hh.
physAddr [2/2]
Bitfield<47, 12> Gicv3Its::physAddr
Definition at line 192 of file gic_v3_its.hh.
physical
Bitfield<0> Gicv3Its::physical
Definition at line 212 of file gic_v3_its.hh.
pta
Bitfield<19> Gicv3Its::pta
Definition at line 205 of file gic_v3_its.hh.
rdBase
Gicv3Its::rdBase
Definition at line 281 of file gic_v3_its.hh.
retry
Bitfield<0> Gicv3Its::retry
Definition at line 170 of file gic_v3_its.hh.
seis
Bitfield<18> Gicv3Its::seis
Definition at line 206 of file gic_v3_its.hh.
shareability
Bitfield< 11, 10 > Gicv3Its::shareability
Definition at line 181 of file gic_v3_its.hh.
size
Bitfield< 7, 0 > Gicv3Its::size
Definition at line 182 of file gic_v3_its.hh.
Referenced by ItsProcess::doRead(), ItsProcess::doWrite(), Gicv3Distributor::nsAccessToSecInt(), Gicv3Redistributor::processorNumber(), NoMaliGpu::read(), and NoMaliGpu::write().
stalled
Bitfield<0> Gicv3Its::stalled
Definition at line 171 of file gic_v3_its.hh.
tableBases
std::vector<BASER> Gicv3Its::tableBases
Definition at line 223 of file gic_v3_its.hh.
Referenced by Gicv3Its(), pageAddress(), read(), serialize(), unserialize(), and write().
type
Bitfield<58, 56> Gicv3Its::type
Definition at line 189 of file gic_v3_its.hh.
valid [1/2]
Bitfield< 0 > Gicv3Its::valid
Definition at line 177 of file gic_v3_its.hh.
valid [2/2]
Bitfield<0> Gicv3Its::valid
Definition at line 268 of file gic_v3_its.hh.
vmovp
Bitfield<37> Gicv3Its::vmovp
Definition at line 201 of file gic_v3_its.hh.
vpeid
Gicv3Its::vpeid
Definition at line 272 of file gic_v3_its.hh.
The documentation for this class was generated from the following files:
dev/arm/gic_v3_its.hh
dev/arm/gic_v3_its.cc