gem5: Named Class Reference
Named Class Reference
#include <trace.hh>
Public Member Functions
Named (const std::string &name_)
const std::string & name () const
Protected Attributes
const std::string _name
Detailed Description
Definition at line 143 of file trace.hh.
Constructor & Destructor Documentation
Named()
Named::Named (const std::string & name_) inline
Definition at line 149 of file trace.hh.
Member Function Documentation
name()
const std::string& Named::name () const inline
Definition at line 152 of file trace.hh.
Referenced by Minor::FUPipeline::findTiming(), Minor::Fetch1::handleTLBResponse(), Minor::LSQ::StoreBuffer::insert(), Minor::LSQ::LSQ(), Minor::Fetch1::recvTimingResp(), and Minor::Fetch2::regStats().
Member Data Documentation
_name
const std::string Named::_name protected
Definition at line 146 of file trace.hh.
The documentation for this class was generated from the following file:
base/trace.hh