gem5: GenericISA::BasicDecodeCache Class Reference
GenericISA::BasicDecodeCache Class Reference
#include <decode_cache.hh>
Public Member Functions
StaticInstPtr decode (TheISA::Decoder *const decoder, TheISA::ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
Private Attributes
DecodeCache::InstMap< TheISA::ExtMachInst > instMap
DecodeCache::AddrMap< StaticInstPtr > decodePages
Detailed Description
Definition at line 47 of file decode_cache.hh.
Member Function Documentation
decode()
StaticInstPtr GenericISA::BasicDecodeCache::decode (TheISA::Decoder *const decoder, TheISA::ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
Parameters
mach_inst The binary instruction to decode.
Return values
A pointer to the corresponding StaticInst object.
Definition at line 42 of file decode_cache.cc.
References decodePages, instMap, StaticInst::machInst, and PowerISA::si.
Referenced by AlphaISA::Decoder::decode(), MipsISA::Decoder::decode(), PowerISA::Decoder::decode(), SparcISA::Decoder::decode(), and ArmISA::Decoder::decode().
Member Data Documentation
decodePages
DecodeCache::AddrMap<StaticInstPtr> GenericISA::BasicDecodeCache::decodePages private
Definition at line 51 of file decode_cache.hh.
Referenced by decode().
instMap
DecodeCache::InstMap<TheISA::ExtMachInst> GenericISA::BasicDecodeCache::instMap private
Definition at line 50 of file decode_cache.hh.
Referenced by decode().
The documentation for this class was generated from the following files:
arch/generic/decode_cache.hh
arch/generic/decode_cache.cc