gem5: HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst > Class Template Reference
HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst > Class Template Reference
#include <mem.hh>
Public Member Functions
void generateDisassembly () override
AtomicInst (const Brig::BrigInstBase *ib, const BrigObject *obj, const char *_opcode)
void initiateAcc (GPUDynInstPtr gpuDynInst) override
void completeAcc (GPUDynInstPtr gpuDynInst) override
void execute (GPUDynInstPtr gpuDynInst) override
Public Member Functions inherited from HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >
AtomicInstBase (const Brig::BrigInstBase *ib, const BrigObject *obj, const char *_opcode)
int numSrcRegOperands ()
int numDstRegOperands ()
int getNumOperands ()
bool isVectorRegister (int operandIndex)
bool isCondRegister (int operandIndex)
bool isScalarRegister (int operandIndex)
bool isSrcOperand (int operandIndex)
bool isDstOperand (int operandIndex)
int getOperandSize (int operandIndex)
int getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst)
Public Member Functions inherited from HsailISA::HsailGPUStaticInst
HsailGPUStaticInst (const BrigObject *obj, const std::string &opcode)
int instSize () const override
bool isValid () const override
Public Member Functions inherited from GPUStaticInst
GPUStaticInst (const std::string &opcode)
void instAddr (int inst_addr)
int instAddr () const
int nextInstAddr () const
void instNum (int num)
int instNum ()
void ipdInstNum (int num)
int ipdInstNum () const
const std::string & disassemble ()
bool isALU () const
bool isBranch () const
bool isNop () const
bool isReturn () const
bool isUnconditionalJump () const
bool isSpecialOp () const
bool isWaitcnt () const
bool isBarrier () const
bool isMemFence () const
bool isMemRef () const
bool isFlat () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isAtomicNoRet () const
bool isAtomicRet () const
bool isScalar () const
bool readsSCC () const
bool writesSCC () const
bool readsVCC () const
bool writesVCC () const
bool isAtomicAnd () const
bool isAtomicOr () const
bool isAtomicXor () const
bool isAtomicCAS () const
bool isAtomicExch () const
bool isAtomicAdd () const
bool isAtomicSub () const
bool isAtomicInc () const
bool isAtomicDec () const
bool isAtomicMax () const
bool isAtomicMin () const
bool isArgLoad () const
bool isGlobalMem () const
bool isLocalMem () const
bool isArgSeg () const
bool isGlobalSeg () const
bool isGroupSeg () const
bool isKernArgSeg () const
bool isPrivateSeg () const
bool isReadOnlySeg () const
bool isSpillSeg () const
bool isWorkitemScope () const
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isNoScope () const
bool isRelaxedOrder () const
bool isAcquire () const
bool isRelease () const
bool isAcquireRelease () const
bool isNoOrder () const
bool isGloballyCoherent () const
Coherence domain of a memory instruction.
bool isSystemCoherent () const
virtual uint32_t getTargetPc ()
void setFlag (Flags flag)
virtual void execLdAcq (GPUDynInstPtr gpuDynInst)
virtual void execSt (GPUDynInstPtr gpuDynInst)
Public Member Functions inherited from HsailISA::MemInst
MemInst ()
MemInst (Enums::MemType m_type)
void init_addr (AddrOperandBase *_addr_operand)
int getMemOperandSize ()
AddrOperandBase * getAddressOperand ()
Private Member Functions
void execAtomic (GPUDynInstPtr gpuDynInst) override
void execAtomicAcq (GPUDynInstPtr gpuDynInst) override
Additional Inherited Members
Public Attributes inherited from HsailISA::AtomicInstBase< MemDataType::OperandType, AddrOperandType, NumSrcOperands, HasDst >
MemDataType::OperandType ::DestOperand dest
MemDataType::OperandType ::SrcOperand src [NumSrcOperands]
AddrOperandType addr
Brig::BrigSegment segment
Brig::BrigMemoryOrder memoryOrder
Brig::BrigAtomicOperation atomicOperation
Brig::BrigMemoryScope memoryScope
Brig::BrigOpcode opcode
Public Attributes inherited from GPUStaticInst
Enums::StorageClassType executed_as
Static Public Attributes inherited from GPUStaticInst
static uint64_t dynamic_id_count
Protected Attributes inherited from HsailISA::HsailGPUStaticInst
HsailCode * hsailCode
Protected Attributes inherited from GPUStaticInst
const std::string opcode
std::string disassembly
int _instNum
int _instAddr
int _ipdInstNum
Identifier of the immediate post-dominator instruction.
std::bitset< Num_Flags > _flags
Detailed Description
template<typename MemDataType, typename AddrOperandType, int NumSrcOperands, bool HasDst>
class HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >
Definition at line 1458 of file mem.hh.
Constructor & Destructor Documentation
AtomicInst()
template<typename MemDataType , typename AddrOperandType , int NumSrcOperands, bool HasDst> HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::AtomicInst (const Brig::BrigInstBase * ib, const BrigObject * obj, const char * _opcode) inline
Definition at line 1466 of file mem.hh.
References addr, and HsailISA::MemInst::init_addr().
Member Function Documentation
completeAcc()
template<typename MemDataType , typename AddrOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::completeAcc (GPUDynInstPtr gpuDynInst) inline override virtual
Reimplemented from GPUStaticInst.
Definition at line 1508 of file mem.hh.
References Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, ArmISA::i, Wavefront::remap(), Wavefront::simdId, ComputeUnit::vrf, MipsISA::w, ComputeUnit::wfSize(), and Wavefront::wfSlotId.
execAtomic()
template<typename MemDataType , typename AddrOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic (GPUDynInstPtr gpuDynInst) inline override private virtual
Reimplemented from GPUStaticInst.
Definition at line 1566 of file mem.hh.
References ArmISA::d, Packet::dataStatic(), ArmISA::e, GPUStaticInst::execAtomicAcq(), ArmISA::f, fatal, ArmISA::i, Wavefront::ldsChunk, LdsChunk::read(), MemCmd::SwapReq, MipsISA::vaddr, and LdsChunk::write().
execAtomicAcq()
template<typename MemDataType , typename AddrOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomicAcq (GPUDynInstPtr gpuDynInst) inline override private virtual
Reimplemented from GPUStaticInst.
Definition at line 1666 of file mem.hh.
References Request::ACQUIRE.
execute()
template<typename DataType , typename AddrRegOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< DataType, AddrRegOperandType, NumSrcOperands, HasDst >::execute (GPUDynInstPtr gpuDynInst) override virtual
Implements GPUStaticInst.
Definition at line 545 of file mem_impl.hh.
References addr, HsailISA::atomicOpToString(), Brig::BRIG_SEGMENT_GLOBAL, Brig::BRIG_SEGMENT_GROUP, Wavefront::computeUnit, ComputeUnit::cu_id, Wavefront::execMask(), fatal, LocalMemPipeline::getLMReqFIFO(), GLBMEM_PIPE, ComputeUnit::globalMemoryPipe, GlobalMemPipeline::issueRequest(), Wavefront::kernId, LDSMEM_PIPE, ComputeUnit::localMemoryPipe, ArmISA::m, Wavefront::memReqsInPipe, Wavefront::outstandingReqs, Wavefront::outstandingReqsRdGm, Wavefront::outstandingReqsRdLm, Wavefront::outstandingReqsWrGm, Wavefront::outstandingReqsWrLm, Wavefront::rdGmReqsInPipe, Wavefront::rdLmReqsInPipe, ComputeUnit::shader, Wavefront::simdId, Shader::tick_cnt, Shader::ticks(), MipsISA::w, Wavefront::wfDynId, ComputeUnit::wfSize(), Wavefront::wfSlotId, Wavefront::wrGmReqsInPipe, and Wavefront::wrLmReqsInPipe.
generateDisassembly()
template<typename DataType , typename AddrRegOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< DataType, AddrRegOperandType, NumSrcOperands, HasDst >::generateDisassembly () override virtual
Reimplemented from HsailISA::HsailGPUStaticInst.
Definition at line 626 of file mem_impl.hh.
References addr, HsailISA::atomicOpToString(), csprintf(), ArmISA::i, ArmISA::opcode, and segmentNames.
initiateAcc()
template<typename MemDataType , typename AddrOperandType , int NumSrcOperands, bool HasDst> void HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::initiateAcc (GPUDynInstPtr gpuDynInst) inline override virtual
Reimplemented from GPUStaticInst.
Definition at line 1477 of file mem.hh.
References GPUStaticInst::execAtomic(), and Request::RELEASE.
The documentation for this class was generated from the following files:
arch/hsail/insts/mem.hh
arch/hsail/insts/mem_impl.hh