gem5: Stats::FormulaNode Class Reference
Stats::FormulaNode Class Reference
"Statistic Types"
#include <statistics.hh>
Public Member Functions
FormulaNode (const Formula &f)
size_type size () const
Return the number of nodes in the subtree starting at this node.
const VResult & result () const
Return the result vector of this subtree.
Result total () const
Return the total of the result vector.
std::string str () const
Public Member Functions inherited from Stats::Node
virtual ~Node ()
Private Attributes
const Formula & formula
VResult vec
Detailed Description
Definition at line 3100 of file statistics.hh.
Constructor & Destructor Documentation
FormulaNode()
Stats::FormulaNode::FormulaNode (const Formula & f) inline
Definition at line 3107 of file statistics.hh.
Member Function Documentation
result()
const VResult& Stats::FormulaNode::result () const inline virtual
Return the result vector of this subtree.
Returns
The result vector of this subtree.
Implements Stats::Node.
Definition at line 3110 of file statistics.hh.
References Stats::Formula::result().
size()
size_type Stats::FormulaNode::size () const inline virtual
Return the number of nodes in the subtree starting at this node.
Returns
the number of nodes in this subtree.
Implements Stats::Node.
Definition at line 3109 of file statistics.hh.
References Stats::Formula::size().
str()
std::string Stats::FormulaNode::str () const inline virtual
Implements Stats::Node.
Definition at line 3113 of file statistics.hh.
References Stats::Formula::str().
total()
Result Stats::FormulaNode::total () const inline virtual
Return the total of the result vector.
Returns
The total of the result vector.
Implements Stats::Node.
Definition at line 3111 of file statistics.hh.
References Stats::Formula::total().
Member Data Documentation
formula
const Formula& Stats::FormulaNode::formula private
Definition at line 3103 of file statistics.hh.
vec
VResult Stats::FormulaNode::vec mutable private
Definition at line 3104 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh