gem5: BaseKvmCPU Class Reference
BaseKvmCPU Class Reference abstract
Base class for KVM based CPU models.
#include <base.hh>
Classes
class KVMCpuPort
KVM memory port.
Public Member Functions
BaseKvmCPU (BaseKvmCPUParams *params)
virtual ~BaseKvmCPU ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void startup () override
startup() is the final initialization call before simulation.
void regStats () override
Callback to set stat parameters.
void serializeThread (CheckpointOut &cp, ThreadID tid) const override
Serialize a single thread.
void unserializeThread (CheckpointIn &cp, ThreadID tid) override
Unserialize one thread.
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void notifyFork () override
Notify a child process of a fork.
void switchOut () override
Prepare for another CPU to take over execution.
void takeOverFrom (BaseCPU *cpu) override
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
void verifyMemoryMode () const override
Verify that the system is in a memory mode supported by the CPU.
Port & getDataPort () override
Purely virtual method that returns a reference to the data port.
Port & getInstPort () override
Purely virtual method that returns a reference to the instruction port.
void wakeup (ThreadID tid=0) override
void activateContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now active.
void suspendContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now suspended.
void deallocateContext (ThreadID thread_num)
void haltContext (ThreadID thread_num) override
Notify the CPU that the indicated context is now halted.
long getVCpuID () const
ThreadContext * getContext (int tn) override
Given a thread num get tho thread context for it.
Counter totalInsts () const override
Counter totalOps () const override
void finishMMIOPending ()
Callback from KvmCPUPort to transition the CPU out of RunningMMIOPending when all timing requests have completed.
virtual void dump () const
Dump the internal state to the terminal.
void kick () const
Force an exit from KVM.
Public Member Functions inherited from BaseCPU
virtual PortProxy::SendFunctionalFunc getSendFunctional ()
Returns a sendFunctional delegate for use with port proxies.
int cpuId () const
Reads this CPU's ID.
uint32_t socketId () const
Reads this CPU's Socket ID.
MasterID dataMasterId () const
Reads this CPU's unique data requestor ID.
MasterID instMasterId () const
Reads this CPU's unique instruction requestor ID.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port on this CPU.
uint32_t taskId () const
Get cpu task id.
void taskId (uint32_t id)
Set cpu task id.
uint32_t getPid () const
void setPid (uint32_t pid)
void workItemBegin ()
void workItemEnd ()
Tick instCount ()
BaseInterrupts * getInterruptController (ThreadID tid)
void postInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupt (ThreadID tid, int int_num, int index)
void clearInterrupts (ThreadID tid)
bool checkInterrupts (ThreadContext *tc) const
void processProfileEvent ()
Trace::InstTracer * getTracer ()
Provide access to the tracer pointer.
int findContext (ThreadContext *tc)
Given a Thread Context pointer return the thread num.
unsigned numContexts ()
Get the number of thread contexts available.
ThreadID contextToThread (ContextID cid)
Convert ContextID to threadID.
const Params * params () const
BaseCPU (Params *params, bool is_checker=false)
virtual ~BaseCPU ()
void regProbePoints () override
Register probe points for this object.
void registerThreadContexts ()
void deschedulePowerGatingEvent ()
void schedulePowerGatingEvent ()
void flushTLBs ()
Flush all TLBs in the CPU.
bool switchedOut () const
Determine if the CPU is switched out.
unsigned int cacheLineSize () const
Get the cache line size of the system.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
void scheduleInstStop (ThreadID tid, Counter insts, const char *cause)
Schedule an event that exits the simulation loops after a predefined number of instructions.
uint64_t getCurrentInstCount (ThreadID tid)
Get the number of instructions executed by the specified thread on this CPU.
void traceFunctions (Addr pc)
void armMonitor (ThreadID tid, Addr address)
bool mwait (ThreadID tid, PacketPtr pkt)
void mwaitAtomic (ThreadID tid, ThreadContext *tc, BaseTLB *dtb)
AddressMonitor * getCpuAddrMonitor (ThreadID tid)
bool waitForRemoteGDB () const
virtual void probeInstCommit (const StaticInstPtr &inst, Addr pc)
Helper method to trigger PMU probes for a committed instruction.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
SimpleThread * thread
A cached copy of a thread's state in the form of a SimpleThread object.
ThreadContext * tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
KvmVM & vm
Counter ctrInsts
Number of instructions executed by the CPU.
Stats::Scalar numInsts
Stats::Scalar numVMExits
Stats::Scalar numVMHalfEntries
Stats::Scalar numExitSignal
Stats::Scalar numMMIO
Stats::Scalar numCoalescedMMIO
Stats::Scalar numIO
Stats::Scalar numHalt
Stats::Scalar numInterrupts
Stats::Scalar numHypercalls
Public Attributes inherited from BaseCPU
TheISA::MicrocodeRom microcodeRom
EventFunctionWrapper * profileEvent
ThreadID numThreads
Number of threads we're actually simulating (<= SMT_MAX_THREADS).
System * system
Stats::Scalar numCycles
Stats::Scalar numWorkItemsStarted
Stats::Scalar numWorkItemsCompleted
Cycles syscallRetryLatency
Protected Types
enum Status {
Idle, Running, RunningService, RunningMMIOPending,
RunningServiceCompletion
}
Protected Types inherited from BaseCPU
enum CPUState { CPU_STATE_ON, CPU_STATE_SLEEP, CPU_STATE_WAKEUP }
Protected Member Functions
void tick ()
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
virtual uint64_t getHostCycles () const
Get the value of the hardware cycle counter in the guest.
virtual Tick kvmRun (Tick ticks)
Request KVM to run the guest for a given number of ticks.
virtual Tick kvmRunDrain ()
Request the CPU to run until draining completes.
struct kvm_run * getKvmRunState ()
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
uint8_t * getGuestData (uint64_t offset) const
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
void kvmNonMaskableInterrupt ()
Send a non-maskable interrupt to the guest.
void kvmInterrupt (const struct kvm_interrupt &interrupt)
Send a normal interrupt to the guest.
std::string getAndFormatOneReg (uint64_t id) const
Get and format one register for printout.
virtual bool archIsDrained () const
Is the architecture specific code in a state that prevents draining?
Tick doMMIOAccess (Addr paddr, void *data, int size, bool write)
Inject a memory mapped IO request into gem5.
int ioctl (int request, long p1) const
vCPU ioctl interface.
int ioctl (int request, void *p1) const
int ioctl (int request) const
void getRegisters (struct kvm_regs &regs) const
Get/Set the register state of the guest vCPU.
void setRegisters (const struct kvm_regs &regs)
void getSpecialRegisters (struct kvm_sregs &regs) const
void setSpecialRegisters (const struct kvm_sregs &regs)
void getFPUState (struct kvm_fpu &state) const
Get/Set the guest FPU/vector state.
void setFPUState (const struct kvm_fpu &state)
void setOneReg (uint64_t id, const void *addr)
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
void setOneReg (uint64_t id, uint64_t value)
void setOneReg (uint64_t id, uint32_t value)
void getOneReg (uint64_t id, void *addr) const
uint64_t getOneRegU64 (uint64_t id) const
uint32_t getOneRegU32 (uint64_t id) const
virtual void updateKvmState ()=0
Update the KVM state from the current thread context.
virtual void updateThreadContext ()=0
Update the current thread context with the KVM state.
void syncThreadContext ()
Update a thread context if the KVM state is dirty with respect to the cached thread context.
EventQueue * deviceEventQueue ()
Get a pointer to the event queue owning devices.
void syncKvmState ()
Update the KVM if the thread context is dirty.
virtual Tick handleKvmExit ()
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
virtual Tick handleKvmExitIO ()
The guest performed a legacy IO request (out/inp on x86)
virtual Tick handleKvmExitHypercall ()
The guest requested a monitor service using a hypercall.
virtual Tick handleKvmExitIRQWindowOpen ()
The guest exited because an interrupt window was requested.
virtual Tick handleKvmExitUnknown ()
An unknown architecture dependent error occurred when starting the vCPU.
virtual Tick handleKvmExitException ()
An unhandled virtualization exception occured.
virtual Tick handleKvmExitFailEntry ()
KVM failed to start the virtualized CPU.
void setSignalMask (const sigset_t *mask)
Set the signal mask used in kvmRun()
Protected Member Functions inherited from BaseCPU
void updateCycleCounters (CPUState state)
base method keeping track of cycle progression
void enterPwrGating ()
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
Status _status
CPU run state.
KVMCpuPort dataPort
Port for data requests.
KVMCpuPort instPort
Unused dummy port for the instruction interface.
const bool alwaysSyncTC
Be conservative and always synchronize the thread context on KVM entry/exit.
bool threadContextDirty
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
bool kvmStateDirty
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
const long vcpuID
KVM internal ID of the vCPU.
pthread_t vcpuThread
ID of the vCPU thread.
Protected Attributes inherited from BaseCPU
Tick instCnt
Instruction count used for SPARC misc register.
int _cpuId
const uint32_t _socketId
Each cpu will have a socket ID that corresponds to its physical location in the system.
MasterID _instMasterId
instruction side request id that must be placed in all requests
MasterID _dataMasterId
data side request id that must be placed in all requests
uint32_t _taskId
An intrenal representation of a task identifier within gem5.
uint32_t _pid
The current OS process ID that is executing on this processor.
bool _switchedOut
Is the CPU switched out or active?
const unsigned int _cacheLineSize
Cache the cache line size that we get from the system.
std::vector< BaseInterrupts * > interrupts
std::vector< ThreadContext * > threadContexts
Trace::InstTracer * tracer
Cycles previousCycle
CPUState previousState
const Cycles pwrGatingLatency
const bool powerGatingOnIdle
EventFunctionWrapper enterPwrGatingEvent
ProbePoints::PMUUPtr ppRetiredInsts
Instruction commit probe point.
ProbePoints::PMUUPtr ppRetiredInstsPC
ProbePoints::PMUUPtr ppRetiredLoads
Retired load instructions.
ProbePoints::PMUUPtr ppRetiredStores
Retired store instructions.
ProbePoints::PMUUPtr ppRetiredBranches
Retired branches (any type)
ProbePoints::PMUUPtr ppAllCycles
CPU cycle counter even if any thread Context is suspended.
ProbePoints::PMUUPtr ppActiveCycles
CPU cycle counter, only counts if any thread contexts is active.
ProbePointArg< bool > * ppSleeping
ProbePoint that signals transitions of threadContexts sets.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
Tick flushCoalescedMMIO ()
Service MMIO requests in the mmioRing.
void setupSignalHandler ()
Setup a signal handler to catch the timer signal used to switch back to the monitor.
bool discardPendingSignal (int signum) const
Discard a (potentially) pending signal.
void startupThread ()
Thread-specific initialization.
bool tryDrain ()
Try to drain the CPU if a drain is pending.
void ioctlRun ()
Execute the KVM_RUN ioctl.
void setupInstStop ()
Setup an instruction break if there is one pending.
Private Attributes
int vcpuFD
KVM vCPU file descriptor.
int vcpuMMapSize
Size of MMAPed kvm_run area.
struct kvm_run * _kvmRun
Pointer to the kvm_run structure used to communicate parameters with KVM.
struct kvm_coalesced_mmio_ring * mmioRing
Coalesced MMIO ring buffer.
const long pageSize
Cached page size of the host.
EventFunctionWrapper tickEvent
std::unique_ptr< BaseKvmTimer > runTimer
Timer used to force execution into the monitor after a specified number of simulation tick equivalents have executed in the guest.
float hostFactor
Host factor as specified in the configuration.
uint64_t activeInstPeriod
Currently active instruction count breakpoint.
PerfKvmCounter hwCycles
Guest cycle counter.
PerfKvmCounter hwInstructions
Guest instruction counter.
bool perfControlledByTimer
Does the runTimer control the performance counters?
void setupCounters ()
Setup hardware performance counters.
void setupInstCounter (uint64_t period=0)
Setup the guest instruction counter.
Additional Inherited Members
Public Types inherited from BaseCPU
typedef BaseCPUParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from BaseCPU
static int numSimulatedInsts ()
static int numSimulatedOps ()
static void wakeup (ThreadID tid)
static int numSimulatedCPUs ()
static Counter numSimulatedInsts ()
static Counter numSimulatedOps ()
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from BaseCPU
static const uint32_t invldPid = std::numeric_limits<uint32_t>::max()
Invalid or unknown Pid.
static const Addr PCMask = ~((Addr)sizeof(TheISA::MachInst) - 1)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Base class for KVM based CPU models.
All architecture specific KVM implementation should inherit from this class. The most basic CPU models only need to override the updateKvmState() and updateThreadContext() methods to implement state synchronization between gem5 and KVM.
The architecture specific implementation is also responsible for delivering interrupts into the VM. This is typically done by overriding tick() and checking the thread context before entering into the VM. In order to deliver an interrupt, the implementation then calls KvmVM::setIRQLine() or BaseKvmCPU::kvmInterrupt() depending on the specifics of the underlying hardware/drivers.
Definition at line 79 of file base.hh.
Member Enumeration Documentation
Status
enum BaseKvmCPU::Status protected
Enumerator
Idle
Context not scheduled in KVM.
The CPU generally enters this state when the guest execute an instruction that halts the CPU (e.g., WFI on ARM or HLT on X86) if KVM traps this instruction. Ticks are not scheduled in this state.
See also
suspendContext()
Running
Running normally.
This is the normal run state of the CPU. KVM will be entered next time tick() is called.
RunningService
Requiring service at the beginning of the next cycle.
The virtual machine has exited and requires service, tick() will call handleKvmExit() on the next cycle. The next state after running service is determined in handleKvmExit() and depends on what kind of service the guest requested:
IO/MMIO (Atomic): RunningServiceCompletion
IO/MMIO (Timing): RunningMMIOPending
Halt: Idle
Others: Running
RunningMMIOPending
Timing MMIO request in flight or stalled.
The VM has requested IO/MMIO and we are in timing mode. A timing request is either stalled (and will be retried with recvReqRetry()) or it is in flight. After the timing request is complete, the CPU will transition to the RunningServiceCompletion state.
RunningServiceCompletion
Service completion in progress.
The VM has requested service that requires KVM to be entered once in order to get to a consistent state. This happens in handleKvmExit() or one of its friends after IO exits. After executing tick(), the CPU will transition into the Running or RunningService state.
Definition at line 181 of file base.hh.
Constructor & Destructor Documentation
BaseKvmCPU()
BaseKvmCPU::BaseKvmCPU (BaseKvmCPUParams * params)
Definition at line 65 of file base.cc.
References activeInstPeriod, EventBase::CPU_Tick_Pri, ctrInsts, FullSystem, SimpleThread::getTC(), ThreadContext::Halted, hostFactor, pageSize, panic, BaseCPU::params(), perfControlledByTimer, SimpleThread::setStatus(), tc, thread, BaseCPU::threadContexts, and tick().
~BaseKvmCPU()
BaseKvmCPU::~BaseKvmCPU () virtual
Definition at line 101 of file base.cc.
References _kvmRun, vcpuFD, and vcpuMMapSize.
Member Function Documentation
activateContext()
void BaseKvmCPU::activateContext (ThreadID thread_num) override virtual
Notify the CPU that the indicated context is now active.
Reimplemented from BaseCPU.
Definition at line 533 of file base.cc.
References _status, Clocked::clockEdge(), DPRINTF, Idle, ThreadState::lastActivate, ThreadState::lastSuspend, BaseCPU::numCycles, Running, EventManager::schedule(), Event::scheduled(), thread, tickEvent, and Clocked::ticksToCycles().
Referenced by getInstPort().
archIsDrained()
virtual bool BaseKvmCPU::archIsDrained () const inline protected virtual
Is the architecture specific code in a state that prevents draining?
This method should return false if there are any pending events in the guest vCPU that won't be carried over to the gem5 state and thus will prevent correct checkpointing or CPU handover. It might, for example, check for pending interrupts that have been passed to the vCPU but not acknowledged by the OS. Architecures implementing this method must override kvmRunDrain().
See also
BaseKvmCPU::kvmRunDrain()
Returns
true if the vCPU is drained, false otherwise.
Reimplemented in X86KvmCPU.
Definition at line 524 of file base.hh.
References data, doMMIOAccess(), ioctl(), ArmISA::mask, and setSignalMask().
Referenced by drain(), and tryDrain().
deallocateContext()
void BaseKvmCPU::deallocateContext (ThreadID thread_num)
Definition at line 574 of file base.cc.
References suspendContext().
Referenced by getInstPort().
deviceEventQueue()
EventQueue* BaseKvmCPU::deviceEventQueue () inline protected
Get a pointer to the event queue owning devices.
Devices always live in a separate device event queue when running in multi-core mode. We need to temporarily migrate to this queue when accessing devices. By convention, devices and the VM use the same event queue.
Definition at line 430 of file base.hh.
References EventManager::eventQueue(), handleKvmExit(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitHypercall(), handleKvmExitIO(), handleKvmExitIRQWindowOpen(), handleKvmExitUnknown(), and syncKvmState().
Referenced by doMMIOAccess(), X86KvmCPU::handleKvmExitIO(), ArmV8KvmCPU::updateKvmState(), and ArmV8KvmCPU::updateThreadContext().
discardPendingSignal()
bool BaseKvmCPU::discardPendingSignal (int signum) const private
Discard a (potentially) pending signal.
Parameters
signum Signal to discard
Returns
true if the signal was pending, false otherwise.
Definition at line 1258 of file base.cc.
References panic.
Referenced by kvmRun().
doMMIOAccess()
Tick BaseKvmCPU::doMMIOAccess (Addr paddr, void * data, int size, bool write) protected
Inject a memory mapped IO request into gem5.
Parameters
paddr Physical address
data Pointer to the source/destination buffer
size Memory access size
write True if write, False if read
Returns
Number of ticks spent servicing the memory access
Definition at line 1114 of file base.cc.
References Clocked::clockPeriod(), ThreadContext::contextId(), BaseCPU::dataMasterId(), dataPort, Packet::dataStatic(), deviceEventQueue(), BaseTLB::finalizePhysical(), ThreadContext::getDTBPtr(), SimpleThread::getTC(), GenericISA::handleIprRead(), GenericISA::handleIprWrite(), NoFault, BaseTLB::Read, MemCmd::ReadReq, BaseKvmCPU::KVMCpuPort::submitIO(), syncThreadContext(), tc, thread, threadContextDirty, Request::UNCACHEABLE, warn, BaseTLB::Write, and MemCmd::WriteReq.
Referenced by archIsDrained(), flushCoalescedMMIO(), and handleKvmExit().
drain()
DrainState BaseKvmCPU::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 353 of file base.cc.
References _status, archIsDrained(), EventManager::deschedule(), DPRINTF, Drained, Draining, EventManager::eventQueue(), Idle, X86ISA::lock, M5_FALLTHROUGH, panic, Running, RunningMMIOPending, RunningService, RunningServiceCompletion, Event::scheduled(), BaseCPU::switchedOut(), syncThreadContext(), and tickEvent.
drainResume()
void BaseKvmCPU::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 424 of file base.cc.
References _status, ThreadContext::Active, DPRINTF, Idle, Clocked::nextCycle(), Running, EventManager::schedule(), Event::scheduled(), ThreadContext::status(), BaseCPU::switchedOut(), tc, tickEvent, and verifyMemoryMode().
dump()
void BaseKvmCPU::dump () const virtual
Dump the internal state to the terminal.
Reimplemented in ArmV8KvmCPU, and X86KvmCPU.
Definition at line 611 of file base.cc.
References inform.
Referenced by getVCpuID(), handleKvmExit(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitUnknown(), and serializeThread().
finishMMIOPending()
void BaseKvmCPU::finishMMIOPending ()
Callback from KvmCPUPort to transition the CPU out of RunningMMIOPending when all timing requests have completed.
Definition at line 231 of file base.cc.
References _status, Clocked::nextCycle(), RunningMMIOPending, RunningServiceCompletion, EventManager::schedule(), Event::scheduled(), and tickEvent.
Referenced by getVCpuID().
flushCoalescedMMIO()
Tick BaseKvmCPU::flushCoalescedMMIO () private
Service MMIO requests in the mmioRing.
Returns
Number of ticks spent servicing the MMIO requests in the MMIO ring buffer
Definition at line 1187 of file base.cc.
References doMMIOAccess(), DPRINTF, mmioRing, and numCoalescedMMIO.
Referenced by kvmRun().
getAndFormatOneReg()
std::string BaseKvmCPU::getAndFormatOneReg (uint64_t id) const protected
Get and format one register for printout.
This function call getOneReg() to retrieve the contents of one register and automatically formats it for printing.
Note
The presence of this call depends on Kvm::capOneReg().
Definition at line 919 of file base.cc.
References panic, and ArmISA::ss.
Referenced by ArmV8KvmCPU::dump(), ArmKvmCPU::dumpKvmStateCoProc(), ArmKvmCPU::dumpKvmStateMisc(), ArmKvmCPU::dumpKvmStateVFP(), getOneRegU32(), ArmV8KvmCPU::updateKvmState(), and ArmV8KvmCPU::updateThreadContext().
getContext()
ThreadContext * BaseKvmCPU::getContext (int tn) override virtual
Given a thread num get tho thread context for it.
Reimplemented from BaseCPU.
Definition at line 589 of file base.cc.
References syncThreadContext(), and tc.
Referenced by getVCpuID(), and ArmKvmCPU::onKvmExitHypercall().
getDataPort()
Port& BaseKvmCPU::getDataPort () inline override virtual
Purely virtual method that returns a reference to the data port.
All subclasses must implement this method.
Returns
a reference to the data port
Implements BaseCPU.
Definition at line 101 of file base.hh.
References dataPort.
getFPUState()
void BaseKvmCPU::getFPUState (struct kvm_fpu & state) const protected
Get/Set the guest FPU/vector state.
Definition at line 870 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpFpuRegs(), getGuestData(), and X86KvmCPU::updateThreadContext().
getGuestData()
uint8_t* BaseKvmCPU::getGuestData (uint64_t offset) const inline protected
Retrieve a pointer to guest data stored at the end of the kvm_run structure.
This is mainly used for PIO operations (KVM_EXIT_IO).
Parameters
offset Offset as specified by the kvm_run structure
Returns
Pointer to guest data
Definition at line 310 of file base.hh.
References _kvmRun, addr, getFPUState(), getRegisters(), getSpecialRegisters(), kvmInterrupt(), kvmNonMaskableInterrupt(), ArmISA::offset, setFPUState(), setOneReg(), setRegisters(), and setSpecialRegisters().
Referenced by X86KvmCPU::handleIOMiscReg32(), and X86KvmCPU::handleKvmExitIO().
getHostCycles()
uint64_t BaseKvmCPU::getHostCycles () const protected virtual
Get the value of the hardware cycle counter in the guest.
This method is supposed to return the total number of cycles executed in hardware mode relative to some arbitrary point in the past. It's mainly used when estimating the number of cycles actually executed by the CPU in kvmRun(). The default behavior of this method is to use the cycles performance counter, but some architectures may want to use internal registers instead.
Returns
Number of host cycles executed relative to an undefined point in the past.
Reimplemented in X86KvmCPU.
Definition at line 722 of file base.cc.
References hwCycles, and PerfKvmCounter::read().
Referenced by kvmRun().
getInstPort()
Port& BaseKvmCPU::getInstPort () inline override virtual
Purely virtual method that returns a reference to the instruction port.
All subclasses must implement this method.
Returns
a reference to the instruction port
Implements BaseCPU.
Definition at line 102 of file base.hh.
References activateContext(), deallocateContext(), haltContext(), instPort, suspendContext(), and wakeup().
getKvmRunState()
struct kvm_run* BaseKvmCPU::getKvmRunState () inline protected
Get a pointer to the kvm_run structure containing all the input and output parameters from kvmRun().
Definition at line 300 of file base.hh.
References _kvmRun.
Referenced by X86KvmCPU::handleIOMiscReg32(), X86KvmCPU::handleKvmExitIO(), X86KvmCPU::kvmRun(), X86KvmCPU::kvmRunDrain(), X86KvmCPU::kvmRunWrapper(), and X86KvmCPU::updateThreadContextSRegs().
getOneReg()
void BaseKvmCPU::getOneReg (uint64_t id, void * addr) const protected
Definition at line 902 of file base.cc.
References ArmISA::id, ioctl(), and panic.
Referenced by getOneRegU32(), getOneRegU64(), setOneReg(), and ArmV8KvmCPU::updateThreadContext().
getOneRegU32()
uint32_t BaseKvmCPU::getOneRegU32 (uint64_t id) const inline protected
Definition at line 378 of file base.hh.
References getAndFormatOneReg(), getOneReg(), syncThreadContext(), updateKvmState(), and updateThreadContext().
Referenced by ArmKvmCPU::dumpKvmStateCoProc(), ArmKvmCPU::dumpKvmStateCore(), ArmKvmCPU::updateTCStateCoProc(), and ArmKvmCPU::updateTCStateCore().
getOneRegU64()
uint64_t BaseKvmCPU::getOneRegU64 (uint64_t id) const inline protected
Definition at line 373 of file base.hh.
References getOneReg().
Referenced by ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateVFP(), and ArmV8KvmCPU::updateThreadContext().
getRegisters()
void BaseKvmCPU::getRegisters (struct kvm_regs & regs) const protected
Get/Set the register state of the guest vCPU.
KVM has two different interfaces for accessing the state of the guest CPU. One interface updates 'normal' registers and one updates 'special' registers. The distinction between special and normal registers isn't very clear and is architecture dependent.
Definition at line 842 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpIntRegs(), getGuestData(), and X86KvmCPU::updateThreadContext().
getSpecialRegisters()
void BaseKvmCPU::getSpecialRegisters (struct kvm_sregs & regs) const protected
Definition at line 856 of file base.cc.
References ioctl(), and panic.
Referenced by X86KvmCPU::dumpSpecRegs(), getGuestData(), and X86KvmCPU::updateThreadContext().
getVCpuID()
long BaseKvmCPU::getVCpuID () const inline
Definition at line 110 of file base.hh.
References dump(), finishMMIOPending(), getContext(), totalInsts(), totalOps(), and vcpuID.
haltContext()
void BaseKvmCPU::haltContext (ThreadID thread_num) override virtual
Notify the CPU that the indicated context is now halted.
Reimplemented from BaseCPU.
Definition at line 581 of file base.cc.
References BaseCPU::CPU_STATE_SLEEP, suspendContext(), and BaseCPU::updateCycleCounters().
Referenced by getInstPort().
handleKvmExit()
Tick BaseKvmCPU::handleKvmExit () protected virtual
Main kvmRun exit handler, calls the relevant handleKvmExit* depending on exit type.
Returns
Number of ticks spent servicing the exit request
Definition at line 990 of file base.cc.
References _kvmRun, _status, dataPort, doMMIOAccess(), DPRINTF, dump(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitHypercall(), handleKvmExitIO(), handleKvmExitIRQWindowOpen(), handleKvmExitUnknown(), Idle, BaseKvmCPU::KVMCpuPort::nextIOState(), numHalt, numHypercalls, numIO, numMMIO, panic, Running, RunningService, SimpleThread::suspend(), and thread.
Referenced by deviceEventQueue(), and tick().
handleKvmExitException()
Tick BaseKvmCPU::handleKvmExitException () protected virtual
An unhandled virtualization exception occured.
Some KVM virtualization drivers return unhandled exceptions to the user-space monitor. This interface is currently only used by the Intel VMX KVM driver.
Returns
Number of ticks delay the next CPU tick
Definition at line 1097 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by deviceEventQueue(), and handleKvmExit().
handleKvmExitFailEntry()
Tick BaseKvmCPU::handleKvmExitFailEntry () protected virtual
KVM failed to start the virtualized CPU.
The kvm_run data structure contains the hardware-specific error code.
Returns
Number of ticks delay the next CPU tick
Definition at line 1106 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by deviceEventQueue(), and handleKvmExit().
handleKvmExitHypercall()
Tick BaseKvmCPU::handleKvmExitHypercall () protected virtual
The guest requested a monitor service using a hypercall.
Returns
Number of ticks spent servicing the hypercall
Definition at line 1075 of file base.cc.
References panic.
Referenced by deviceEventQueue(), and handleKvmExit().
handleKvmExitIO()
Tick BaseKvmCPU::handleKvmExitIO () protected virtual
The guest performed a legacy IO request (out/inp on x86)
Returns
Number of ticks spent servicing the IO request
Reimplemented in X86KvmCPU.
Definition at line 1067 of file base.cc.
References _kvmRun, and panic.
Referenced by deviceEventQueue(), and handleKvmExit().
handleKvmExitIRQWindowOpen()
Tick BaseKvmCPU::handleKvmExitIRQWindowOpen () protected virtual
The guest exited because an interrupt window was requested.
The guest exited because an interrupt window was requested (request_interrupt_window in the kvm_run structure was set to 1 before calling kvmRun) and it is now ready to receive
Returns
Number of ticks spent servicing the IRQ
Reimplemented in X86KvmCPU.
Definition at line 1081 of file base.cc.
References warn.
Referenced by deviceEventQueue(), and handleKvmExit().
handleKvmExitUnknown()
Tick BaseKvmCPU::handleKvmExitUnknown () protected virtual
An unknown architecture dependent error occurred when starting the vCPU.
The kvm_run data structure contains the hardware error code. The defaults behavior of this method just prints the HW error code and panics. Architecture dependent implementations may want to override this method to provide better, hardware-aware, error messages.
Returns
Number of ticks delay the next CPU tick
Definition at line 1089 of file base.cc.
References _kvmRun, dump(), and panic.
Referenced by deviceEventQueue(), and handleKvmExit().
init()
void BaseKvmCPU::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BaseCPU.
Definition at line 109 of file base.cc.
References ThreadContext::contextId(), fatal, FullSystem, BaseCPU::init(), AlphaISA::initCPU(), ThreadContext::initMemProxies(), BaseCPU::numThreads, BaseCPU::switchedOut(), and tc.
ioctlRun()
void BaseKvmCPU::ioctlRun () private
Execute the KVM_RUN ioctl.
Definition at line 1339 of file base.cc.
References ioctl(), and panic.
Referenced by kvmRun().
kick()
void BaseKvmCPU::kick () const inline
Force an exit from KVM.
Send a signal to the thread owning this vCPU to get it to exit from KVM. Ignored if the vCPU is not executing.
Definition at line 131 of file base.hh.
References KVM_KICK_SIGNAL, and vcpuThread.
Referenced by kvmRun(), and wakeup().
kvmRun()
Tick BaseKvmCPU::kvmRun (Tick ticks) protected virtual
Request KVM to run the guest for a given number of ticks.
The method returns the approximate number of ticks executed.
Note
The returned number of ticks can be both larger or smaller than the requested number of ticks. A smaller number can, for example, occur when the guest executes MMIO. A larger number is typically due to performance counter inaccuracies.
This method is virtual in order to allow implementations to check for architecture specific events (e.g., interrupts) before entering the VM.
It is the response of the caller (normally tick()) to make sure that the KVM state is synchronized and that the TC is invalidated after entering KVM.
This method does not normally cause any state transitions. However, if it may suspend the CPU by suspending the thread, which leads to a transition to the Idle state. In such a case, kvm must not be entered.
Parameters
ticks Number of ticks to execute, set to 0 to exit immediately after finishing pending operations.
Returns
Number of ticks executed (see note)
Reimplemented in ArmKvmCPU, X86KvmCPU, and BaseArmKvmCPU.
Definition at line 728 of file base.cc.
References Clocked::clockPeriod(), ctrInsts, curEventQueue(), discardPendingSignal(), DPRINTF, fatal_if, flushCoalescedMMIO(), getHostCycles(), hostFactor, hwCycles, hwInstructions, ioctlRun(), kick(), KVM_KICK_SIGNAL, BaseCPU::numCycles, numInsts, numVMExits, numVMHalfEntries, perfControlledByTimer, PerfKvmCounter::read(), runTimer, PerfKvmCounter::start(), PerfKvmCounter::stop(), BaseCPU::system, System::totalNumInsts, and vcpuFD.
Referenced by BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), kvmRunDrain(), X86KvmCPU::kvmRunWrapper(), and tick().
kvmRunDrain()
Tick BaseKvmCPU::kvmRunDrain () protected virtual
Request the CPU to run until draining completes.
This function normally calls kvmRun(0) to make KVM finish pending MMIO operations. Architecures implementing archIsDrained() must override this method.
See also
BaseKvmCPU::archIsDrained()
Returns
Number of ticks executed
Reimplemented in X86KvmCPU.
Definition at line 708 of file base.cc.
References _status, kvmRun(), RunningMMIOPending, and RunningServiceCompletion.
Referenced by tick().
notifyFork()
void BaseKvmCPU::notifyFork () override virtual
Notify a child process of a fork.
When calling fork in gem5, we need to ensure that resources shared between the parent and the child are consistent. This method is intended to be overloaded to handle that. For example, an object could use this method to re-open input files to get a separate file description with a private file offset.
This method is only called in the child of the fork. The call takes place in a drained system.
Reimplemented from Drainable.
Definition at line 447 of file base.cc.
References _kvmRun, _status, PerfKvmCounter::detach(), hwCycles, hwInstructions, Idle, Event::scheduled(), tickEvent, vcpuFD, vcpuMMapSize, and warn.
regStats()
void BaseKvmCPU::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from BaseCPU.
Definition at line 271 of file base.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numCoalescedMMIO, numExitSignal, numHalt, numHypercalls, numInsts, numInterrupts, numIO, numMMIO, numVMExits, numVMHalfEntries, and BaseCPU::regStats().
serializeThread()
void BaseKvmCPU::serializeThread (CheckpointOut & cp, ThreadID tid) const override virtual
Serialize a single thread.
Parameters
cp The stream to serialize to.
tid ID of the current thread.
Reimplemented from BaseCPU.
Definition at line 329 of file base.cc.
References _status, DPRINTF, DTRACE, dump(), Idle, SimpleThread::serialize(), and thread.
setFPUState()
void BaseKvmCPU::setFPUState (const struct kvm_fpu & state) protected
Definition at line 877 of file base.cc.
References ioctl(), and panic.
Referenced by getGuestData(), and X86KvmCPU::updateKvmStateFPULegacy().
setOneReg() [1/3]
void BaseKvmCPU::setOneReg (uint64_t id, const void * addr) protected
Get/Set single register using the KVM_(SET|GET)_ONE_REG API.
Note
The presence of this call depends on Kvm::capOneReg().
Definition at line 885 of file base.cc.
References ArmISA::id, ioctl(), and panic.
Referenced by getGuestData(), ArmKvmCPU::onKvmExitHypercall(), ArmV8KvmCPU::startup(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCoProc(), ArmKvmCPU::updateKvmStateCore(), and ArmKvmCPU::updateKvmStateVFP().
setOneReg() [2/3]
void BaseKvmCPU::setOneReg (uint64_t id, uint64_t value) inline protected
Definition at line 370 of file base.hh.
References setOneReg().
Referenced by setOneReg().
setOneReg() [3/3]
void BaseKvmCPU::setOneReg (uint64_t id, uint32_t value) inline protected
Definition at line 371 of file base.hh.
References getOneReg(), and setOneReg().
Referenced by setOneReg().
setRegisters()
void BaseKvmCPU::setRegisters (const struct kvm_regs & regs) protected
Definition at line 849 of file base.cc.
References ioctl(), and panic.
Referenced by getGuestData(), and X86KvmCPU::updateKvmStateRegs().
setSignalMask()
void BaseKvmCPU::setSignalMask (const sigset_t * mask) protected
Set the signal mask used in kvmRun()
This method allows the signal mask of the thread executing kvmRun() to be overridden inside the actual system call. This allows us to mask timer signals used to force KVM exits while in gem5.
The signal mask can be disabled by setting it to NULL.
Parameters
mask Signals to mask
Definition at line 1157 of file base.cc.
References ioctl(), and panic.
Referenced by archIsDrained(), and setupSignalHandler().
setSpecialRegisters()
void BaseKvmCPU::setSpecialRegisters (const struct kvm_sregs & regs) protected
Definition at line 863 of file base.cc.
References ioctl(), and panic.
Referenced by getGuestData(), and X86KvmCPU::updateKvmStateSRegs().
setupCounters()
void BaseKvmCPU::setupCounters () private
Setup hardware performance counters.
Definition at line 1286 of file base.cc.
References PerfKvmCounter::attach(), PerfKvmCounterConfig::disabled(), DPRINTF, PerfKvmCounterConfig::exclude_host(), PerfKvmCounterConfig::exclude_hv(), hwCycles, perfControlledByTimer, PerfKvmCounterConfig::pinned(), PerfKvmCounterConfig::samplePeriod(), setupInstCounter(), and PerfKvmCounterConfig::wakeupEvents().
Referenced by startupThread().
setupInstCounter()
void BaseKvmCPU::setupInstCounter (uint64_t period = 0) private
Setup the guest instruction counter.
Setup the guest instruction counter and optionally request a signal every N instructions executed by the guest. This method will re-attach the counter if the counter has already been attached and its sampling settings have changed.
Parameters
period Signal period, set to 0 to disable signaling.
Definition at line 1361 of file base.cc.
References activeInstPeriod, PerfKvmCounter::attach(), PerfKvmCounter::attached(), PerfKvmCounter::detach(), PerfKvmCounter::enableSignals(), PerfKvmCounterConfig::exclude_host(), PerfKvmCounterConfig::exclude_hv(), hwCycles, hwInstructions, KVM_KICK_SIGNAL, PerfKvmCounterConfig::samplePeriod(), and PerfKvmCounterConfig::wakeupEvents().
Referenced by setupCounters(), and setupInstStop().
setupInstStop()
void BaseKvmCPU::setupInstStop () private
Setup an instruction break if there is one pending.
Check if there are pending instruction breaks in the CPU's instruction event queue and schedule an instruction break using PerfEvent.
Note
This method doesn't currently handle the main system instruction event queue.
Definition at line 1349 of file base.cc.
References SimpleThread::comInstEventQueue, ctrInsts, EventQueue::empty(), EventQueue::nextTick(), setupInstCounter(), and thread.
Referenced by tick().
setupSignalHandler()
void BaseKvmCPU::setupSignalHandler () private
Setup a signal handler to catch the timer signal used to switch back to the monitor.
Definition at line 1229 of file base.cc.
References KVM_KICK_SIGNAL, onKickSignal(), panic, and setSignalMask().
Referenced by startupThread().
startup()
void BaseKvmCPU::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from BaseCPU.
Reimplemented in X86KvmCPU.
Definition at line 124 of file base.cc.
References _kvmRun, Kvm::capCoalescedMMIO(), KvmVM::cpuStartup(), KvmVM::createVCPU(), curTick(), Kvm::getVCPUMMapSize(), inform, KvmVM::kvm, mmioRing, SimObject::name(), MipsISA::p, pageSize, panic, BaseCPU::params(), EventManager::schedule(), SimpleThread::startup(), BaseCPU::startup(), startupThread(), thread, vcpuFD, vcpuID, vcpuMMapSize, and vm.
Referenced by X86KvmCPU::startup(), BaseArmKvmCPU::startup(), and ArmKvmCPU::startup().
startupThread()
void BaseKvmCPU::startupThread () private
Thread-specific initialization.
Some KVM-related initialization requires us to know the TID of the thread that is going to execute our event queue. For example, when setting up timers, we need to know the TID of the thread executing in KVM in order to deliver the timer signal to that thread. This method is called as the first event in this SimObject's event queue.
See also
startup
Definition at line 241 of file base.cc.
References hwCycles, KVM_KICK_SIGNAL, MipsISA::p, BaseCPU::params(), runTimer, setupCounters(), setupSignalHandler(), and vcpuThread.
Referenced by startup().
suspendContext()
void BaseKvmCPU::suspendContext (ThreadID thread_num) override virtual
Notify the CPU that the indicated context is now suspended.
Check if possible to enter a lower power state
Reimplemented from BaseCPU.
Definition at line 551 of file base.cc.
References _status, EventManager::deschedule(), DPRINTF, Idle, Running, RunningServiceCompletion, Event::scheduled(), thread, and tickEvent.
Referenced by deallocateContext(), getInstPort(), and haltContext().
switchOut()
void BaseKvmCPU::switchOut () override virtual
Prepare for another CPU to take over execution.
When this method exits, all internal state should have been flushed. After the method returns, the simulator calls takeOverFrom() on the new CPU with this CPU as its parameter.
Reimplemented from BaseCPU.
Definition at line 470 of file base.cc.
References _status, DPRINTF, Idle, Event::scheduled(), BaseCPU::switchOut(), and tickEvent.
syncKvmState()
void BaseKvmCPU::syncKvmState () protected
Update the KVM if the thread context is dirty.
Definition at line 978 of file base.cc.
References kvmStateDirty, threadContextDirty, and updateKvmState().
Referenced by deviceEventQueue(), and tick().
syncThreadContext()
void BaseKvmCPU::syncThreadContext () protected
Update a thread context if the KVM state is dirty with respect to the cached thread context.
Definition at line 966 of file base.cc.
References kvmStateDirty, threadContextDirty, and updateThreadContext().
Referenced by X86KvmCPU::deliverInterrupts(), doMMIOAccess(), drain(), getContext(), getOneRegU32(), X86KvmCPU::kvmRun(), and tick().
takeOverFrom()
void BaseKvmCPU::takeOverFrom (BaseCPU * cpu) override virtual
Load the state of a CPU from the previous CPU object, invoked on all new CPUs that are about to be switched in.
A CPU model implementing this method is expected to initialize its state from the old CPU and connect its memory (unless they are already connected) to the memories connected to the old CPU.
Parameters
cpu CPU to initialize read state from.
Reimplemented from BaseCPU.
Definition at line 484 of file base.cc.
References _status, DPRINTF, Idle, Event::scheduled(), BaseCPU::takeOverFrom(), threadContextDirty, BaseCPU::threadContexts, tickEvent, and updateKvmState().
tick()
void BaseKvmCPU::tick () protected
Execute the CPU until the next event in the main event queue or until the guest needs service from gem5.
Definition at line 617 of file base.cc.
References _kvmRun, _status, alwaysSyncTC, Clocked::clockEdge(), SimpleThread::comInstEventQueue, ctrInsts, curEventQueue(), curTick(), DPRINTF, Draining, Drainable::drainState(), handleKvmExit(), Idle, kvmRun(), kvmRunDrain(), kvmStateDirty, MaxTick, numExitSignal, panic, Running, RunningMMIOPending, RunningService, RunningServiceCompletion, EventManager::schedule(), setupInstStop(), syncKvmState(), syncThreadContext(), thread, threadContextDirty, tickEvent, Clocked::ticksToCycles(), and tryDrain().
Referenced by BaseKvmCPU().
totalInsts()
Counter BaseKvmCPU::totalInsts () const override virtual
Implements BaseCPU.
Definition at line 598 of file base.cc.
References ctrInsts.
Referenced by getVCpuID().
totalOps()
Counter BaseKvmCPU::totalOps () const override virtual
Implements BaseCPU.
Definition at line 604 of file base.cc.
References ctrInsts, and hack_once.
Referenced by getVCpuID().
tryDrain()
bool BaseKvmCPU::tryDrain () private
Try to drain the CPU if a drain is pending.
Definition at line 1317 of file base.cc.
References _status, archIsDrained(), DPRINTF, Draining, Drainable::drainState(), Idle, Running, and Drainable::signalDrainDone().
Referenced by tick().
unserializeThread()
void BaseKvmCPU::unserializeThread (CheckpointIn & cp, ThreadID tid) override virtual
Unserialize one thread.
Parameters
cp The checkpoint use.
tid ID of the current thread.
Reimplemented from BaseCPU.
Definition at line 342 of file base.cc.
References _status, DPRINTF, Idle, thread, threadContextDirty, and SimpleThread::unserialize().
updateKvmState()
virtual void BaseKvmCPU::updateKvmState () protected pure virtual
Update the KVM state from the current thread context.
The base CPU calls this method before starting the guest CPU when the contextDirty flag is set. The architecture dependent CPU implementation is expected to update all guest state (registers, special registers, and FPU state).
Implemented in X86KvmCPU, ArmKvmCPU, and ArmV8KvmCPU.
Referenced by getOneRegU32(), syncKvmState(), and takeOverFrom().
updateThreadContext()
virtual void BaseKvmCPU::updateThreadContext () protected pure virtual
Update the current thread context with the KVM state.
The base CPU after the guest updates any of the KVM state. In practice, this happens after kvmRun is called. The architecture dependent code is expected to read the state of the guest CPU and update gem5's thread state.
Implemented in X86KvmCPU, ArmKvmCPU, and ArmV8KvmCPU.
Referenced by getOneRegU32(), and syncThreadContext().
verifyMemoryMode()
void BaseKvmCPU::verifyMemoryMode () const override virtual
Verify that the system is in a memory mode supported by the CPU.
Implementations are expected to query the system for the current memory mode and ensure that it is what the CPU model expects. If the check fails, the implementation should terminate the simulation using fatal().
Reimplemented from BaseCPU.
Definition at line 506 of file base.cc.
References System::bypassCaches(), fatal, and BaseCPU::system.
Referenced by drainResume().
wakeup()
void BaseKvmCPU::wakeup (ThreadID tid = 0) override virtual
Implements BaseCPU.
Definition at line 515 of file base.cc.
References SimpleThread::activate(), DPRINTF, EventManager::eventQueue(), kick(), SimpleThread::status(), ThreadContext::Suspended, and thread.
Referenced by getInstPort().
Member Data Documentation
_kvmRun
struct kvm_run* BaseKvmCPU::_kvmRun private
Pointer to the kvm_run structure used to communicate parameters with KVM.
Note
This is the base pointer of the MMAPed KVM region. The first page contains the kvm_run structure. Subsequent pages may contain other data such as the MMIO ring buffer.
Definition at line 699 of file base.hh.
Referenced by getGuestData(), getKvmRunState(), handleKvmExit(), handleKvmExitException(), handleKvmExitFailEntry(), handleKvmExitIO(), handleKvmExitUnknown(), notifyFork(), startup(), tick(), and ~BaseKvmCPU().
_status
Status BaseKvmCPU::_status protected
CPU run state.
Definition at line 232 of file base.hh.
Referenced by activateContext(), drain(), drainResume(), finishMMIOPending(), handleKvmExit(), X86KvmCPU::kvmRun(), kvmRunDrain(), notifyFork(), serializeThread(), suspendContext(), switchOut(), takeOverFrom(), tick(), tryDrain(), and unserializeThread().
activeInstPeriod
uint64_t BaseKvmCPU::activeInstPeriod private
Currently active instruction count breakpoint.
Definition at line 739 of file base.hh.
Referenced by BaseKvmCPU(), and setupInstCounter().
alwaysSyncTC
const bool BaseKvmCPU::alwaysSyncTC protected
Be conservative and always synchronize the thread context on KVM entry/exit.
Definition at line 623 of file base.hh.
Referenced by tick().
ctrInsts
Counter BaseKvmCPU::ctrInsts
Number of instructions executed by the CPU.
Definition at line 800 of file base.hh.
Referenced by BaseKvmCPU(), kvmRun(), setupInstStop(), tick(), totalInsts(), and totalOps().
dataPort
KVMCpuPort BaseKvmCPU::dataPort protected
Port for data requests.
Definition at line 614 of file base.hh.
Referenced by doMMIOAccess(), getDataPort(), handleKvmExit(), and X86KvmCPU::handleKvmExitIO().
hostFactor
float BaseKvmCPU::hostFactor private
Host factor as specified in the configuration.
Definition at line 783 of file base.hh.
Referenced by BaseKvmCPU(), and kvmRun().
hwCycles
PerfKvmCounter BaseKvmCPU::hwCycles private
Guest cycle counter.
This is the group leader of all performance counters measuring the guest system. It can be used in conjunction with the PerfKvmTimer (see perfControlledByTimer) to trigger exits from KVM.
Definition at line 749 of file base.hh.
Referenced by getHostCycles(), kvmRun(), notifyFork(), setupCounters(), setupInstCounter(), and startupThread().
hwInstructions
PerfKvmCounter BaseKvmCPU::hwInstructions private
Guest instruction counter.
This counter is typically only used to measure the number of instructions executed by the guest. However, it can also be used to trigger exits from KVM if the configuration script requests an exit after a certain number of instructions.
See also
setupInstBreak
scheduleInstStop
Definition at line 762 of file base.hh.
Referenced by kvmRun(), notifyFork(), and setupInstCounter().
instPort
KVMCpuPort BaseKvmCPU::instPort protected
Unused dummy port for the instruction interface.
Definition at line 617 of file base.hh.
Referenced by getInstPort().
kvmStateDirty
bool BaseKvmCPU::kvmStateDirty protected
Is the KVM state dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
Definition at line 635 of file base.hh.
Referenced by syncKvmState(), syncThreadContext(), and tick().
mmioRing
struct kvm_coalesced_mmio_ring* BaseKvmCPU::mmioRing private
Coalesced MMIO ring buffer.
NULL if coalesced MMIO is not supported.
Definition at line 704 of file base.hh.
Referenced by flushCoalescedMMIO(), and startup().
numCoalescedMMIO
Stats::Scalar BaseKvmCPU::numCoalescedMMIO
Definition at line 792 of file base.hh.
Referenced by flushCoalescedMMIO(), and regStats().
numExitSignal
Stats::Scalar BaseKvmCPU::numExitSignal
Definition at line 790 of file base.hh.
Referenced by regStats(), and tick().
numHalt
Stats::Scalar BaseKvmCPU::numHalt
Definition at line 794 of file base.hh.
Referenced by handleKvmExit(), and regStats().
numHypercalls
Stats::Scalar BaseKvmCPU::numHypercalls
Definition at line 796 of file base.hh.
Referenced by handleKvmExit(), and regStats().
numInsts
Stats::Scalar BaseKvmCPU::numInsts
Definition at line 787 of file base.hh.
Referenced by kvmRun(), and regStats().
numInterrupts
Stats::Scalar BaseKvmCPU::numInterrupts
Definition at line 795 of file base.hh.
Referenced by kvmInterrupt(), kvmNonMaskableInterrupt(), and regStats().
numIO
Stats::Scalar BaseKvmCPU::numIO
Definition at line 793 of file base.hh.
Referenced by handleKvmExit(), and regStats().
numMMIO
Stats::Scalar BaseKvmCPU::numMMIO
Definition at line 791 of file base.hh.
Referenced by handleKvmExit(), and regStats().
numVMExits
Stats::Scalar BaseKvmCPU::numVMExits
Definition at line 788 of file base.hh.
Referenced by kvmRun(), and regStats().
numVMHalfEntries
Stats::Scalar BaseKvmCPU::numVMHalfEntries
Definition at line 789 of file base.hh.
Referenced by kvmRun(), and regStats().
pageSize
const long BaseKvmCPU::pageSize private
Cached page size of the host.
Definition at line 706 of file base.hh.
Referenced by BaseKvmCPU(), and startup().
perfControlledByTimer
bool BaseKvmCPU::perfControlledByTimer private
Does the runTimer control the performance counters?
The run timer will automatically enable and disable performance counters if a PerfEvent-based timer is used to control KVM exits.
Definition at line 771 of file base.hh.
Referenced by BaseKvmCPU(), kvmRun(), and setupCounters().
runTimer
std::unique_ptr<BaseKvmTimer> BaseKvmCPU::runTimer private
Timer used to force execution into the monitor after a specified number of simulation tick equivalents have executed in the guest.
This counter generates the signal specified by KVM_TIMER_SIGNAL.
Definition at line 780 of file base.hh.
Referenced by kvmRun(), and startupThread().
tc
ThreadContext* BaseKvmCPU::tc
ThreadContext object, provides an interface for external objects to modify this thread's state.
Definition at line 151 of file base.hh.
Referenced by BaseKvmCPU(), X86KvmCPU::deliverInterrupts(), doMMIOAccess(), drainResume(), ArmKvmCPU::dumpKvmStateCoProc(), getContext(), X86KvmCPU::handleIOMiscReg32(), X86KvmCPU::handleKvmExitIO(), init(), X86KvmCPU::kvmRun(), X86KvmCPU::kvmRunWrapper(), ArmKvmCPU::onKvmExitHypercall(), ArmV8KvmCPU::startup(), X86KvmCPU::updateCPUID(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCoProc(), ArmKvmCPU::updateKvmStateCore(), X86KvmCPU::updateKvmStateFPULegacy(), X86KvmCPU::updateKvmStateFPUXSave(), X86KvmCPU::updateKvmStateMSRs(), X86KvmCPU::updateKvmStateRegs(), X86KvmCPU::updateKvmStateSRegs(), ArmKvmCPU::updateKvmStateVFP(), ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateCore(), ArmKvmCPU::updateTCStateVFP(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContextFPU(), X86KvmCPU::updateThreadContextMSRs(), X86KvmCPU::updateThreadContextRegs(), and X86KvmCPU::updateThreadContextXSave().
thread
SimpleThread* BaseKvmCPU::thread
A cached copy of a thread's state in the form of a SimpleThread object.
Normally the actual thread state is stored in the KVM vCPU. If KVM has been running this copy is will be out of date. If we recently handled some events within gem5 that required state to be updated this could be the most up-to-date copy. When getContext() or updateThreadContext() is called this copy gets updated. The method syncThreadContext can be used within a KVM CPU to update the thread context if the KVM state is dirty (i.e., the vCPU has been run since the last update).
Definition at line 146 of file base.hh.
Referenced by activateContext(), BaseKvmCPU(), X86KvmCPU::deliverInterrupts(), doMMIOAccess(), handleKvmExit(), serializeThread(), setupInstStop(), startup(), suspendContext(), tick(), unserializeThread(), and wakeup().
threadContextDirty
bool BaseKvmCPU::threadContextDirty protected
Is the gem5 context dirty? Set to true to force an update of the KVM vCPU state upon the next call to kvmRun().
Definition at line 629 of file base.hh.
Referenced by X86KvmCPU::deliverInterrupts(), doMMIOAccess(), syncKvmState(), syncThreadContext(), takeOverFrom(), tick(), and unserializeThread().
tickEvent
EventFunctionWrapper BaseKvmCPU::tickEvent private
Definition at line 708 of file base.hh.
Referenced by activateContext(), drain(), drainResume(), finishMMIOPending(), notifyFork(), suspendContext(), switchOut(), takeOverFrom(), and tick().
vcpuFD
int BaseKvmCPU::vcpuFD private
KVM vCPU file descriptor.
Definition at line 688 of file base.hh.
Referenced by ioctl(), kvmRun(), notifyFork(), startup(), and ~BaseKvmCPU().
vcpuID
const long BaseKvmCPU::vcpuID protected
KVM internal ID of the vCPU.
Definition at line 638 of file base.hh.
Referenced by getVCpuID(), BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), and startup().
vcpuMMapSize
int BaseKvmCPU::vcpuMMapSize private
Size of MMAPed kvm_run area.
Definition at line 690 of file base.hh.
Referenced by notifyFork(), startup(), and ~BaseKvmCPU().
vcpuThread
pthread_t BaseKvmCPU::vcpuThread protected
ID of the vCPU thread.
Definition at line 641 of file base.hh.
Referenced by kick(), and startupThread().
vm
KvmVM& BaseKvmCPU::vm
Definition at line 153 of file base.hh.
Referenced by X86KvmCPU::dumpMSRs(), X86KvmCPU::getMsrIntersection(), BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), BaseArmKvmCPU::startup(), startup(), and X86KvmCPU::X86KvmCPU().
The documentation for this class was generated from the following files:
cpu/kvm/base.hh
cpu/kvm/base.cc