gem5: TAGE_SC_L Class Reference
TAGE_SC_L Class Reference
#include <tage_sc_l.hh>
Classes
struct TageSCLBranchInfo
Public Member Functions
TAGE_SC_L (const TAGE_SC_LParams *params)
bool predict (ThreadID tid, Addr branch_pc, bool cond_branch, void *&b) override
Get a branch prediction from LTAGE.
void regStats () override
Registers statistics.
void update (ThreadID tid, Addr branch_addr, bool taken, void *bp_history, bool squashed, const StaticInstPtr &inst, Addr corrTarget=MaxAddr) override
Updates the BP with taken/not taken information.
Public Member Functions inherited from LTAGE
LTAGE (const LTAGEParams *params)
void squash (ThreadID tid, void *bp_history) override
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from TAGE
TAGE (const TAGEParams *params)
void uncondBranch (ThreadID tid, Addr br_pc, void *&bp_history) override
bool lookup (ThreadID tid, Addr branch_addr, void *&bp_history) override
Looks up a given PC in the BP to see if it is taken or not taken.
void btbUpdate (ThreadID tid, Addr branch_addr, void *&bp_history) override
If a branch is not taken, because the BTB address is invalid or missing, this function sets the appropriate counter in the global and local predictors to not taken.
Public Member Functions inherited from BPredUnit
BPredUnit (const Params *p)
void regProbePoints () override
Register probe points for this object.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool predict (const StaticInstPtr &inst, const InstSeqNum &seqNum, TheISA::PCState &pc, ThreadID tid)
Predicts whether or not the instruction is a taken branch, and the target of the branch if it is taken.
void update (const InstSeqNum &done_sn, ThreadID tid)
Tells the branch predictor to commit any updates until the given sequence number.
void squash (const InstSeqNum &squashed_sn, ThreadID tid)
Squashes all outstanding updates until a given sequence number.
void squash (const InstSeqNum &squashed_sn, const TheISA::PCState &corr_target, bool actually_taken, ThreadID tid)
Squashes all outstanding updates until a given sequence number, and corrects that sn's update with the proper address and taken/not taken.
bool BTBValid (Addr instPC)
Looks up a given PC in the BTB to see if a matching entry exists.
TheISA::PCState BTBLookup (Addr instPC)
Looks up a given PC in the BTB to get the predicted target.
void BTBUpdate (Addr instPC, const TheISA::PCState &target)
Updates the BTB with the target of a branch.
void dump ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
enum { SC = LAST_LTAGE_PROVIDER_TYPE + 1 }
Protected Types inherited from LTAGE
enum { LOOP = TAGEBase::LAST_TAGE_PROVIDER_TYPE + 1, LAST_LTAGE_PROVIDER_TYPE = LOOP }
Private Attributes
StatisticalCorrector * statisticalCorrector
Additional Inherited Members
Public Types inherited from BPredUnit
typedef BranchPredictorParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from BPredUnit
ProbePoints::PMUUPtr pmuProbePoint (const char *name)
Helper method to instantiate probe points belonging to this object.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from LTAGE
LoopPredictor * loopPredictor
The loop predictor object.
Protected Attributes inherited from TAGE
TAGEBase * tage
Protected Attributes inherited from BPredUnit
const unsigned instShiftAmt
Number of bits to shift instructions by for predictor addresses.
ProbePoints::PMUUPtr ppBranches
Branches seen by the branch predictor.
ProbePoints::PMUUPtr ppMisses
Miss-predicted branches.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 148 of file tage_sc_l.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
SC
Definition at line 181 of file tage_sc_l.hh.
Constructor & Destructor Documentation
TAGE_SC_L()
TAGE_SC_L::TAGE_SC_L (const TAGE_SC_LParams * params)
Definition at line 67 of file tage_sc_l.cc.
Member Function Documentation
predict()
bool TAGE_SC_L::predict (ThreadID tid, Addr branch_pc, bool cond_branch, void *& b) override virtual
Get a branch prediction from LTAGE.
NOT an override of BpredUnit::predict().
Parameters
tid The thread ID to select the global histories to use.
branch_pc The unshifted branch PC.
cond_branch True if the branch is conditional.
b Reference to wrapping pointer to allow storing derived class prediction information in the base class.
Reimplemented from LTAGE.
Definition at line 365 of file tage_sc_l.cc.
References TAGE_SC_L_TAGE::BranchInfo::altConf, StatisticalCorrector::BranchInfo::altConf, PowerISA::bi, TAGEBase::getCtr(), TAGEBase::getPathHist(), TAGEBase::getTageCtrBits(), TAGE_SC_L_TAGE::BranchInfo::highConf, StatisticalCorrector::BranchInfo::highConf, TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::hitBankIndex, BPredUnit::instShiftAmt, LTAGE::LOOP, LoopPredictor::loopPredict(), LTAGE::loopPredictor, TAGE_SC_L_TAGE::BranchInfo::lowConf, StatisticalCorrector::BranchInfo::lowConf, TAGE_SC_L_TAGE::BranchInfo::medConf, StatisticalCorrector::BranchInfo::medConf, SC, TAGE_SC_L::TageSCLBranchInfo::scBranchInfo, StatisticalCorrector::scPredict(), statisticalCorrector, TAGE::tage, TAGEBase::tagePredict(), and StatisticalCorrector::BranchInfo::usedScPred.
regStats()
void TAGE_SC_L::regStats () override virtual
Registers statistics.
Reimplemented from LTAGE.
Definition at line 471 of file tage_sc_l.cc.
References LTAGE::regStats().
update()
void TAGE_SC_L::update (ThreadID tid, Addr instPC, bool taken, void * bp_history, bool squashed, const StaticInstPtr & inst, Addr corrTarget = MaxAddr) override virtual
Updates the BP with taken/not taken information.
Parameters
inst_PC The branch's PC that will be updated.
taken Whether the branch was taken or not taken.
bp_history Pointer to the branch predictor state that is associated with the branch lookup that is being updated.
squashed Set to true when this function is called during a squash operation.
inst Static instruction information
corrTarget The resolved target of the branch (only needed for squashed branches)
Todo:
Make this update flexible enough to handle a global predictor.
Reimplemented from LTAGE.
Definition at line 413 of file tage_sc_l.cc.
References PowerISA::bi, TAGEBase::BranchInfo::condBranch, LoopPredictor::condBranchUpdate(), StatisticalCorrector::condBranchUpdate(), TAGEBase::condBranchUpdate(), DPRINTF, TAGEBase::getPathHist(), BPredUnit::instShiftAmt, TAGEBase::isSpeculativeUpdateEnabled(), LTAGE::loopPredictor, MaxAddr, Random::random(), random_mt, TAGE_SC_L::TageSCLBranchInfo::scBranchInfo, StatisticalCorrector::scHistoryUpdate(), TAGEBase::squash(), LoopPredictor::squashLoop(), statisticalCorrector, TAGE::tage, TAGEBase::updateHistories(), LoopPredictor::updateStats(), StatisticalCorrector::updateStats(), and TAGEBase::updateStats().
Member Data Documentation
statisticalCorrector
StatisticalCorrector* TAGE_SC_L::statisticalCorrector private
Definition at line 150 of file tage_sc_l.hh.
Referenced by predict(), and update().
The documentation for this class was generated from the following files:
cpu/pred/tage_sc_l.hh
cpu/pred/tage_sc_l.cc