gem5: StreamGen Class Reference
StreamGen Class Reference abstract
#include <stream_gen.hh>
Public Member Functions
virtual ~StreamGen ()
virtual uint32_t pickStreamID ()=0
virtual uint32_t pickSubStreamID ()=0
bool ssidValid () const
Returns true if the substreamID generation is valid and hence should be taken into account.
Static Public Member Functions
static StreamGen * create (const BaseTrafficGenParams *p)
Factory method for constructing a Stream generator.
Protected Member Functions
StreamGen (const BaseTrafficGenParams *p)
Protected Attributes
std::vector< uint32_t > streamIds
Store preset Stream and Substream IDs to use for requests This is the set of available streamIDs the generator can pick.
std::vector< uint32_t > substreamIds
Detailed Description
Definition at line 51 of file stream_gen.hh.
Constructor & Destructor Documentation
StreamGen()
StreamGen::StreamGen (const BaseTrafficGenParams * p) inline protected
Definition at line 54 of file stream_gen.hh.
References fatal_if, and streamIds.
~StreamGen()
virtual StreamGen::~StreamGen () inline virtual
Definition at line 66 of file stream_gen.hh.
References create(), MipsISA::p, pickStreamID(), and pickSubStreamID().
Member Function Documentation
create()
StreamGen * StreamGen::create (const BaseTrafficGenParams * p) static
Factory method for constructing a Stream generator.
The Stream generator type is selected by the StreamGenType enum parameter.
p pointer to BaseTrafficGenParams struct where the stream generator type is stored.
Returns
a pointer to the newly alocated StremGen
Definition at line 45 of file stream_gen.cc.
References Stats::none, and MipsISA::random.
Referenced by BaseTrafficGen::BaseTrafficGen(), and ~StreamGen().
pickStreamID()
virtual uint32_t StreamGen::pickStreamID () pure virtual
Implemented in RandomStreamGen, and FixedStreamGen.
Referenced by ~StreamGen().
pickSubStreamID()
virtual uint32_t StreamGen::pickSubStreamID () pure virtual
Implemented in RandomStreamGen, and FixedStreamGen.
Referenced by ~StreamGen().
ssidValid()
bool StreamGen::ssidValid () const inline
Returns true if the substreamID generation is valid and hence should be taken into account.
It is valid if the set of substreamIDs passed as a parameter to the TrafficGenerator is a non empty list.
Returns
true if ssid is valid, false otherwise
Definition at line 90 of file stream_gen.hh.
References substreamIds.
Member Data Documentation
streamIds
std::vector<uint32_t> StreamGen::streamIds protected
Store preset Stream and Substream IDs to use for requests This is the set of available streamIDs the generator can pick.
The actual ID being picked for a specific memory request is selected by the pickStreamID and pickSubStreamID methods.
Definition at line 100 of file stream_gen.hh.
Referenced by FixedStreamGen::FixedStreamGen(), FixedStreamGen::pickStreamID(), RandomStreamGen::pickStreamID(), and StreamGen().
substreamIds
std::vector<uint32_t> StreamGen::substreamIds protected
Definition at line 101 of file stream_gen.hh.
Referenced by FixedStreamGen::FixedStreamGen(), FixedStreamGen::pickSubStreamID(), RandomStreamGen::pickSubStreamID(), and ssidValid().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/stream_gen.hh
cpu/testers/traffic_gen/stream_gen.cc