gem5: AlphaISA::ItbFault Class Reference
AlphaISA::ItbFault Class Reference abstract
#include <faults.hh>
Public Member Functions
ItbFault (Addr _pc)
FaultName name () const =0
FaultVect vect ()=0
FaultStat & countStat ()=0
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Public Member Functions inherited from AlphaISA::AlphaFault
virtual ~AlphaFault ()
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Protected Attributes
Addr pc
Additional Inherited Members
Protected Member Functions inherited from AlphaISA::AlphaFault
virtual bool skipFaultingInstruction ()
virtual bool setRestartAddress ()
Detailed Description
Definition at line 232 of file faults.hh.
Constructor & Destructor Documentation
ItbFault()
AlphaISA::ItbFault::ItbFault (Addr _pc) inline
Definition at line 238 of file faults.hh.
References AlphaISA::AlphaFault::countStat(), AlphaISA::AlphaFault::invoke(), FaultBase::name(), StaticInst::nullStaticInstPtr, and AlphaISA::AlphaFault::vect().
Member Function Documentation
countStat()
FaultStat& AlphaISA::ItbFault::countStat () pure virtual
Implements AlphaISA::AlphaFault.
Implemented in AlphaISA::ItbAcvFault, and AlphaISA::ItbPageFault.
invoke()
void AlphaISA::ItbFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from AlphaISA::AlphaFault.
Reimplemented in AlphaISA::ItbPageFault.
Definition at line 179 of file faults.cc.
References FullSystem, AlphaISA::AlphaFault::invoke(), AlphaISA::IPR_IFAULT_VA_FORM, AlphaISA::IPR_ITB_TAG, AlphaISA::IPR_IVPTBR, MipsISA::pc, ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscRegNoEffect(), and AlphaISA::VAddr::vpn().
Referenced by AlphaISA::ItbPageFault::invoke().
name()
FaultName AlphaISA::ItbFault::name () const pure virtual
Implements FaultBase.
Implemented in AlphaISA::ItbAcvFault, and AlphaISA::ItbPageFault.
vect()
FaultVect AlphaISA::ItbFault::vect () pure virtual
Implements AlphaISA::AlphaFault.
Implemented in AlphaISA::ItbAcvFault, and AlphaISA::ItbPageFault.
Member Data Documentation
pc
Addr AlphaISA::ItbFault::pc protected
Definition at line 235 of file faults.hh.
The documentation for this class was generated from the following files:
arch/alpha/faults.hh
arch/alpha/faults.cc