gem5: sc_dt::sc_ufixed_fast< W, I, Q, O, N > Class Template Reference
sc_dt::sc_ufixed_fast< W, I, Q, O, N > Class Template Reference
#include <sc_ufixed.hh>
Public Member Functions
sc_ufixed_fast (sc_fxnum_fast_observer *=0)
sc_ufixed_fast (const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufixed_fast (const sc_ufixed_fast< W, I, Q, O, N > &)
sc_ufixed_fast & operator= (const sc_ufixed_fast< W, I, Q, O, N > &)
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_ufixed_fast & operator++ ()
sc_ufixed_fast & operator-- ()
Public Member Functions inherited from sc_dt::sc_ufix_fast
sc_ufix_fast (sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxtype_params &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxtype_params &, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_ufix_fast &)
const sc_ufix_fast operator~ () const
sc_ufix_fast & operator= (const sc_ufix_fast &)
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_ufix_fast & operator++ ()
sc_ufix_fast & operator-- ()
Public Member Functions inherited from sc_dt::sc_fxnum_fast
const sc_fxval_fast operator- () const
const sc_fxval_fast operator+ () const
DECL_BIN_OP_T (/, int64) DECL_BIN_OP_T(/
uint64 DECL_BIN_OP_T (/, const sc_int_base &) DECL_BIN_OP_T(/
uint64 const sc_uint_base & DECL_BIN_OP_T (/, const sc_signed &) friend const sc_fxval_fast operator<<(const sc_fxnum_fast &
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_fxnum_fast & operator++ ()
sc_fxnum_fast & operator-- ()
const sc_fxnum_fast_bitref operator[] (int) const
sc_fxnum_fast_bitref operator[] (int)
const sc_fxnum_fast_bitref bit (int) const
sc_fxnum_fast_bitref bit (int)
const sc_fxnum_fast_subref operator() (int, int) const
sc_fxnum_fast_subref operator() (int, int)
const sc_fxnum_fast_subref range (int, int) const
sc_fxnum_fast_subref range (int, int)
const sc_fxnum_fast_subref operator() () const
sc_fxnum_fast_subref operator() ()
const sc_fxnum_fast_subref range () const
sc_fxnum_fast_subref range ()
operator double () const
short to_short () const
unsigned short to_ushort () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
float to_float () const
double to_double () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
const std::string to_string (sc_fmt) const
const std::string to_string (sc_numrep, sc_fmt) const
const std::string to_string (sc_numrep, bool, sc_fmt) const
const std::string to_dec () const
const std::string to_bin () const
const std::string to_oct () const
const std::string to_hex () const
bool is_neg () const
bool is_zero () const
bool is_normal () const
bool quantization_flag () const
bool overflow_flag () const
const sc_fxval_fast value () const
int wl () const
int iwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
const sc_fxtype_params & type_params () const
const sc_fxcast_switch & cast_switch () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
void observer_read () const
bool get_bit (int) const
Additional Inherited Members
Public Attributes inherited from sc_dt::sc_fxnum_fast
uint64 const sc_uint_base int
Protected Member Functions inherited from sc_dt::sc_fxnum_fast
sc_fxnum_fast_observer * observer () const
void cast ()
sc_fxnum_fast (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &, sc_fxnum_fast_observer *)
~sc_fxnum_fast ()
double get_val () const
bool set_bit (int, bool)
bool get_slice (int, int, sc_bv_base &) const
bool set_slice (int, int, const sc_bv_base &)
sc_fxnum_fast_observer * lock_observer () const
void unlock_observer (sc_fxnum_fast_observer *) const
Detailed Description
template<int W, int I, sc_q_mode Q = SC_DEFAULT_Q_MODE_, sc_o_mode O = SC_DEFAULT_O_MODE_, int N = SC_DEFAULT_N_BITS_>
class sc_dt::sc_ufixed_fast< W, I, Q, O, N >
Definition at line 62 of file sc_ufixed.hh.
Constructor & Destructor Documentation
sc_ufixed_fast() [1/3]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_dt::sc_ufixed_fast< W, I, Q, O, N >::sc_ufixed_fast (sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 436 of file sc_ufixed.hh.
sc_ufixed_fast() [2/3]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_dt::sc_ufixed_fast< W, I, Q, O, N >::sc_ufixed_fast (const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 442 of file sc_ufixed.hh.
sc_ufixed_fast() [3/3]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_dt::sc_ufixed_fast< W, I, Q, O, N >::sc_ufixed_fast (const sc_ufixed_fast< W, I, Q, O, N > & a) inline
Definition at line 485 of file sc_ufixed.hh.
Member Function Documentation
operator++() [1/2]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> const sc_fxval_fast sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator++ (int) inline
Definition at line 555 of file sc_ufixed.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator++() [2/2]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_ufixed_fast< W, I, Q, O, N > & sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator++ () inline
Definition at line 569 of file sc_ufixed.hh.
References sc_dt::sc_ufix_fast::operator++().
operator--() [1/2]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> const sc_fxval_fast sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator-- (int) inline
Definition at line 562 of file sc_ufixed.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator--() [2/2]
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_ufixed_fast< W, I, Q, O, N > & sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator-- () inline
Definition at line 577 of file sc_ufixed.hh.
References sc_dt::sc_ufix_fast::operator--().
operator=()
template<int W, int I, sc_q_mode Q, sc_o_mode O, int N> sc_ufixed_fast< W, I, Q, O, N > & sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator= (const sc_ufixed_fast< W, I, Q, O, N > & a) inline
Definition at line 493 of file sc_ufixed.hh.
References sc_dt::sc_ufix_fast::operator=().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_ufixed.hh