gem5: LSQUnit< Impl >::SQEntry Class Reference
LSQUnit< Impl >::SQEntry Class Reference
Public Member Functions
SQEntry ()
Constructs an empty store queue entry.
~SQEntry ()
void set (const DynInstPtr &inst)
void clear ()
bool & canWB ()
Member accessors.
const bool & canWB () const
bool & completed ()
const bool & completed () const
bool & committed ()
const bool & committed () const
bool & isAllZeros ()
const bool & isAllZeros () const
char * data ()
const char * data () const
Public Member Functions inherited from LSQUnit< Impl >::LSQEntry
LSQEntry ()
Constructs an empty store queue entry.
~LSQEntry ()
void clear ()
void set (const DynInstPtr &inst)
LSQRequest * request ()
void setRequest (LSQRequest *r)
bool hasRequest ()
bool valid () const
Member accessors.
uint32_t & size ()
const uint32_t & size () const
const DynInstPtr & instruction () const
Static Public Attributes
static constexpr size_t DataSize = sizeof(_data)
Private Attributes
char _data [MaxDataBytes]
The store data.
bool _canWB
Whether or not the store can writeback.
bool _committed
Whether or not the store is committed.
bool _completed
Whether or not the store is completed.
bool _isAllZeros
Does this request write all zeros and thus doesn't have any data attached to it.
Detailed Description
template<class Impl>
class LSQUnit< Impl >::SQEntry
Definition at line 154 of file lsq_unit.hh.
Constructor & Destructor Documentation
SQEntry()
template<class Impl> LSQUnit< Impl >::SQEntry::SQEntry () inline
Constructs an empty store queue entry.
Definition at line 173 of file lsq_unit.hh.
~SQEntry()
template<class Impl> LSQUnit< Impl >::SQEntry::~SQEntry () inline
Definition at line 180 of file lsq_unit.hh.
Member Function Documentation
canWB() [1/2]
template<class Impl> bool& LSQUnit< Impl >::SQEntry::canWB () inline
Member accessors.
Definition at line 198 of file lsq_unit.hh.
canWB() [2/2]
template<class Impl> const bool& LSQUnit< Impl >::SQEntry::canWB () const inline
Definition at line 199 of file lsq_unit.hh.
clear()
template<class Impl> void LSQUnit< Impl >::SQEntry::clear () inline
Definition at line 191 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::clear().
committed() [1/2]
template<class Impl> bool& LSQUnit< Impl >::SQEntry::committed () inline
Definition at line 202 of file lsq_unit.hh.
committed() [2/2]
template<class Impl> const bool& LSQUnit< Impl >::SQEntry::committed () const inline
Definition at line 203 of file lsq_unit.hh.
completed() [1/2]
template<class Impl> bool& LSQUnit< Impl >::SQEntry::completed () inline
Definition at line 200 of file lsq_unit.hh.
completed() [2/2]
template<class Impl> const bool& LSQUnit< Impl >::SQEntry::completed () const inline
Definition at line 201 of file lsq_unit.hh.
data() [1/2]
template<class Impl> char* LSQUnit< Impl >::SQEntry::data () inline
Definition at line 206 of file lsq_unit.hh.
data() [2/2]
template<class Impl> const char* LSQUnit< Impl >::SQEntry::data () const inline
Definition at line 207 of file lsq_unit.hh.
isAllZeros() [1/2]
template<class Impl> bool& LSQUnit< Impl >::SQEntry::isAllZeros () inline
Definition at line 204 of file lsq_unit.hh.
isAllZeros() [2/2]
template<class Impl> const bool& LSQUnit< Impl >::SQEntry::isAllZeros () const inline
Definition at line 205 of file lsq_unit.hh.
set()
template<class Impl> void LSQUnit< Impl >::SQEntry::set (const DynInstPtr & inst) inline
Definition at line 185 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::inst, and LSQUnit< Impl >::LSQEntry::set().
Member Data Documentation
_canWB
template<class Impl> bool LSQUnit< Impl >::SQEntry::_canWB private
Whether or not the store can writeback.
Definition at line 160 of file lsq_unit.hh.
_committed
template<class Impl> bool LSQUnit< Impl >::SQEntry::_committed private
Whether or not the store is committed.
Definition at line 162 of file lsq_unit.hh.
_completed
template<class Impl> bool LSQUnit< Impl >::SQEntry::_completed private
Whether or not the store is completed.
Definition at line 164 of file lsq_unit.hh.
_data
template<class Impl> char LSQUnit< Impl >::SQEntry::_data[MaxDataBytes] private
The store data.
Definition at line 158 of file lsq_unit.hh.
_isAllZeros
template<class Impl> bool LSQUnit< Impl >::SQEntry::_isAllZeros private
Does this request write all zeros and thus doesn't have any data attached to it.
Used for cache block zero style instructs (ARM DC ZVA; ALPHA WH64)
Definition at line 169 of file lsq_unit.hh.
DataSize
template<class Impl> constexpr size_t LSQUnit< Impl >::SQEntry::DataSize = sizeof(_data) static
Definition at line 171 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::write().
The documentation for this class was generated from the following file:
cpu/o3/lsq_unit.hh