gem5: InstructionQueue< Impl > Class Template Reference
InstructionQueue< Impl > Class Template Reference
A standard instruction queue class.
#include <inst_queue.hh>
Classes
class FUCompletion
FU completion event class.
struct ListOrderEntry
Entry for the list age ordering by op class.
struct pqCompare
Struct for comparing entries to be added to the priority queue.
Public Types
typedef Impl::O3CPU O3CPU
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::CPUPol::IEW IEW
typedef Impl::CPUPol::MemDepUnit MemDepUnit
typedef Impl::CPUPol::IssueStruct IssueStruct
typedef Impl::CPUPol::TimeStruct TimeStruct
typedef std::list< DynInstPtr >::iterator ListIt
Public Member Functions
InstructionQueue (O3CPU *cpu_ptr, IEW *iew_ptr, DerivO3CPUParams *params)
Constructs an IQ.
~InstructionQueue ()
Destructs the IQ.
std::string name () const
Returns the name of the IQ.
void regStats ()
Registers statistics.
void resetState ()
Resets all instruction queue state.
void setActiveThreads (std::list< ThreadID > *at_ptr)
Sets active threads list.
void setIssueToExecuteQueue (TimeBuffer< IssueStruct > *i2eQueue)
Sets the timer buffer between issue and execute.
void setTimeBuffer (TimeBuffer< TimeStruct > *tb_ptr)
Sets the global time buffer.
bool isDrained () const
Determine if we are drained.
void drainSanityCheck () const
Perform sanity checks after a drain.
void takeOverFrom ()
Takes over execution from another CPU's thread.
int entryAmount (ThreadID num_threads)
Number of entries needed for given amount of threads.
void resetEntries ()
Resets max entries for all threads.
unsigned numFreeEntries ()
Returns total number of free entries.
unsigned numFreeEntries (ThreadID tid)
Returns number of free entries for a thread.
bool isFull ()
Returns whether or not the IQ is full.
bool isFull (ThreadID tid)
Returns whether or not the IQ is full for a specific thread.
bool hasReadyInsts ()
Returns if there are any ready instructions in the IQ.
void insert (const DynInstPtr &new_inst)
Inserts a new instruction into the IQ.
void insertNonSpec (const DynInstPtr &new_inst)
Inserts a new, non-speculative instruction into the IQ.
void insertBarrier (const DynInstPtr &barr_inst)
Inserts a memory or write barrier into the IQ to make sure loads and stores are ordered properly.
DynInstPtr getInstToExecute ()
Returns the oldest scheduled instruction, and removes it from the list of instructions waiting to execute.
DynInstPtr getDeferredMemInstToExecute ()
Gets a memory instruction that was referred due to a delayed DTB translation if it is now ready to execute.
DynInstPtr getBlockedMemInstToExecute ()
Gets a memory instruction that was blocked on the cache.
void recordProducer (const DynInstPtr &inst)
Records the instruction as the producer of a register without adding it to the rest of the IQ.
void processFUCompletion (const DynInstPtr &inst, int fu_idx)
Process FU completion event.
void scheduleReadyInsts ()
Schedules ready instructions, adding the ready ones (oldest first) to the queue to execute.
void scheduleNonSpec (const InstSeqNum &inst)
Schedules a single specific non-speculative instruction.
void commit (const InstSeqNum &inst, ThreadID tid=0)
Commits all instructions up to and including the given sequence number, for a specific thread.
int wakeDependents (const DynInstPtr &completed_inst)
Wakes all dependents of a completed instruction.
void addReadyMemInst (const DynInstPtr &ready_inst)
Adds a ready memory instruction to the ready list.
void rescheduleMemInst (const DynInstPtr &resched_inst)
Reschedules a memory instruction.
void replayMemInst (const DynInstPtr &replay_inst)
Replays a memory instruction.
void completeMemInst (const DynInstPtr &completed_inst)
Completes a memory operation.
void deferMemInst (const DynInstPtr &deferred_inst)
Defers a memory instruction when its DTB translation incurs a hw page table walk.
void blockMemInst (const DynInstPtr &blocked_inst)
Defers a memory instruction when it is cache blocked.
void cacheUnblocked ()
Notify instruction queue that a previous blockage has resolved.
void violation (const DynInstPtr &store, const DynInstPtr &faulting_load)
Indicates an ordering violation between a store and a load.
void squash (ThreadID tid)
Squashes instructions for a thread.
unsigned getCount (ThreadID tid)
Returns the number of used entries for a thread.
void printInsts ()
Debug function to print all instructions.
Public Attributes
Stats::Scalar intInstQueueReads
Stats::Scalar intInstQueueWrites
Stats::Scalar intInstQueueWakeupAccesses
Stats::Scalar fpInstQueueReads
Stats::Scalar fpInstQueueWrites
Stats::Scalar fpInstQueueWakeupAccesses
Stats::Scalar vecInstQueueReads
Stats::Scalar vecInstQueueWrites
Stats::Scalar vecInstQueueWakeupAccesses
Stats::Scalar intAluAccesses
Stats::Scalar fpAluAccesses
Stats::Scalar vecAluAccesses
Private Types
typedef std::priority_queue< DynInstPtr, std::vector< DynInstPtr >, pqCompare > ReadyInstQueue
typedef std::map< InstSeqNum, DynInstPtr >::iterator NonSpecMapIt
typedef std::list< ListOrderEntry >::iterator ListOrderIt
Private Member Functions
void doSquash (ThreadID tid)
Does the actual squashing.
void addToOrderList (OpClass op_class)
Add an op class to the age order list.
void moveToYoungerInst (ListOrderIt age_order_it)
Called when the oldest instruction has been removed from a ready queue; this places that ready queue into the proper spot in the age order list.
bool addToDependents (const DynInstPtr &new_inst)
Adds an instruction to the dependency graph, as a consumer.
void addToProducers (const DynInstPtr &new_inst)
Adds an instruction to the dependency graph, as a producer.
void addIfReady (const DynInstPtr &inst)
Moves an instruction to the ready queue if it is ready.
int countInsts ()
Debugging function to count how many entries are in the IQ.
void dumpLists ()
Debugging function to dump all the list sizes, as well as print out the list of nonspeculative instructions.
void dumpInsts ()
Debugging function to dump out all instructions that are in the IQ.
Private Attributes
O3CPU * cpu
Pointer to the CPU.
MemInterface * dcacheInterface
Cache interface.
IEW * iewStage
Pointer to IEW stage.
MemDepUnit memDepUnit [Impl::MaxThreads]
The memory dependence unit, which tracks/predicts memory dependences between instructions.
TimeBuffer< IssueStruct > * issueToExecuteQueue
The queue to the execute stage.
TimeBuffer< TimeStruct > * timeBuffer
The backwards time buffer.
TimeBuffer< TimeStruct >::wire fromCommit
Wire to read information from timebuffer.
FUPool * fuPool
Function unit pool.
std::list< DynInstPtr > instList [Impl::MaxThreads]
List of all the instructions in the IQ (some of which may be issued).
std::list< DynInstPtr > instsToExecute
List of instructions that are ready to be executed.
std::list< DynInstPtr > deferredMemInsts
List of instructions waiting for their DTB translation to complete (hw page table walk in progress).
std::list< DynInstPtr > blockedMemInsts
List of instructions that have been cache blocked.
std::list< DynInstPtr > retryMemInsts
List of instructions that were cache blocked, but a retry has been seen since, so they can now be retried.
ReadyInstQueue readyInsts [Num_OpClasses]
List of ready instructions, per op class.
std::map< InstSeqNum, DynInstPtr > nonSpecInsts
List of non-speculative instructions that will be scheduled once the IQ gets a signal from commit.
std::list< ListOrderEntry > listOrder
List that contains the age order of the oldest instruction of each ready queue.
bool queueOnList [Num_OpClasses]
Tracks if each ready queue is on the age order list.
ListOrderIt readyIt [Num_OpClasses]
Iterators of each ready queue.
DependencyGraph< DynInstPtr > dependGraph
SMTQueuePolicy iqPolicy
IQ sharing policy for SMT.
ThreadID numThreads
Number of Total Threads.
std::list< ThreadID > * activeThreads
Pointer to list of active threads.
unsigned count [Impl::MaxThreads]
Per Thread IQ count.
unsigned maxEntries [Impl::MaxThreads]
Max IQ Entries Per Thread.
unsigned freeEntries
Number of free IQ entries left.
unsigned numEntries
The number of entries in the instruction queue.
unsigned totalWidth
The total number of instructions that can be issued in one cycle.
unsigned numPhysRegs
The number of physical registers in the CPU.
int wbOutstanding
Number of instructions currently in flight to FUs.
Cycles commitToIEWDelay
Delay between commit stage and the IQ.
InstSeqNum squashedSeqNum [Impl::MaxThreads]
The sequence number of the squashed instruction.
std::vector< bool > regScoreboard
A cache of the recently woken registers.
Stats::Scalar iqInstsAdded
Stat for number of instructions added.
Stats::Scalar iqNonSpecInstsAdded
Stat for number of non-speculative instructions added.
Stats::Scalar iqInstsIssued
Stats::Scalar iqIntInstsIssued
Stat for number of integer instructions issued.
Stats::Scalar iqFloatInstsIssued
Stat for number of floating point instructions issued.
Stats::Scalar iqBranchInstsIssued
Stat for number of branch instructions issued.
Stats::Scalar iqMemInstsIssued
Stat for number of memory instructions issued.
Stats::Scalar iqMiscInstsIssued
Stat for number of miscellaneous instructions issued.
Stats::Scalar iqSquashedInstsIssued
Stat for number of squashed instructions that were ready to issue.
Stats::Scalar iqSquashedInstsExamined
Stat for number of squashed instructions examined when squashing.
Stats::Scalar iqSquashedOperandsExamined
Stat for number of squashed instruction operands examined when squashing.
Stats::Scalar iqSquashedNonSpecRemoved
Stat for number of non-speculative instructions removed due to a squash.
Stats::Distribution numIssuedDist
Distribution of number of instructions in the queue.
Stats::Vector statFuBusy
Distribution of the cycles it takes to issue an instruction.
Stats::Vector2d statIssuedInstType
Stat for total number issued for each instruction type.
Stats::Formula issueRate
Number of instructions issued per cycle.
Stats::Vector fuBusy
Number of times the FU was busy.
Stats::Formula fuBusyRate
Number of times the FU was busy per instruction issued.
Detailed Description
template<class Impl>
class InstructionQueue< Impl >
A standard instruction queue class.
It holds ready instructions, in order, in seperate priority queues to facilitate the scheduling of instructions. The IQ uses a separate linked list to track dependencies. Similar to the rename map and the free list, it expects that floating point registers have their indices start after the integer registers (ie with 96 int and 96 fp registers, regs 0-95 are integer and 96-191 are fp). This remains true even for both logical and physical register indices. The IQ depends on the memory dependence unit to track when memory operations are ready in terms of ordering; register dependencies are tracked normally. Right now the IQ also handles the execution timing; this is mainly to allow back-to-back scheduling without requiring IEW to be able to peek into the IQ. At the end of the execution latency, the instruction is put into the queue to execute, where it will have the execute() function called on it.
Todo:
: Make IQ able to handle multiple FU pools.
Definition at line 83 of file inst_queue.hh.
Member Typedef Documentation
DynInstPtr
template<class Impl> typedef Impl::DynInstPtr InstructionQueue< Impl >::DynInstPtr
Definition at line 88 of file inst_queue.hh.
IEW
template<class Impl> typedef Impl::CPUPol::IEW InstructionQueue< Impl >::IEW
Definition at line 90 of file inst_queue.hh.
IssueStruct
template<class Impl> typedef Impl::CPUPol::IssueStruct InstructionQueue< Impl >::IssueStruct
Definition at line 92 of file inst_queue.hh.
ListIt
template<class Impl> typedef std::list<DynInstPtr>::iterator InstructionQueue< Impl >::ListIt
Definition at line 96 of file inst_queue.hh.
ListOrderIt
template<class Impl> typedef std::list<ListOrderEntry>::iterator InstructionQueue< Impl >::ListOrderIt private
Definition at line 382 of file inst_queue.hh.
MemDepUnit
template<class Impl> typedef Impl::CPUPol::MemDepUnit InstructionQueue< Impl >::MemDepUnit
Definition at line 91 of file inst_queue.hh.
NonSpecMapIt
template<class Impl> typedef std::map<InstSeqNum, DynInstPtr>::iterator InstructionQueue< Impl >::NonSpecMapIt private
Definition at line 365 of file inst_queue.hh.
O3CPU
template<class Impl> typedef Impl::O3CPU InstructionQueue< Impl >::O3CPU
Definition at line 87 of file inst_queue.hh.
ReadyInstQueue
template<class Impl> typedef std::priority_queue<DynInstPtr, std::vector<DynInstPtr>, pqCompare> InstructionQueue< Impl >::ReadyInstQueue private
Definition at line 349 of file inst_queue.hh.
TimeStruct
template<class Impl> typedef Impl::CPUPol::TimeStruct InstructionQueue< Impl >::TimeStruct
Definition at line 93 of file inst_queue.hh.
Constructor & Destructor Documentation
InstructionQueue()
template<class Impl > InstructionQueue< Impl >::InstructionQueue (O3CPU * cpu_ptr, IEW * iew_ptr, DerivO3CPUParams * params)
Constructs an IQ.
Definition at line 88 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::dependGraph, DPRINTF, InstructionQueue< Impl >::fuPool, MemDepUnit< MemDepPred, Impl >::init(), InstructionQueue< Impl >::iqPolicy, InstructionQueue< Impl >::maxEntries, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::numEntries, InstructionQueue< Impl >::numPhysRegs, InstructionQueue< Impl >::numThreads, AlphaISA::NumVecElemPerVecReg, InstructionQueue< Impl >::regScoreboard, InstructionQueue< Impl >::resetState(), and MemDepUnit< MemDepPred, Impl >::setIQ().
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
~InstructionQueue()
template<class Impl > InstructionQueue< Impl >::~InstructionQueue ()
Destructs the IQ.
Definition at line 162 of file inst_queue_impl.hh.
References cprintf(), and InstructionQueue< Impl >::dependGraph.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
Member Function Documentation
addIfReady()
template<class Impl > void InstructionQueue< Impl >::addIfReady (const DynInstPtr & inst) private
Moves an instruction to the ready queue if it is ready.
Definition at line 1452 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addToOrderList(), DPRINTF, InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::queueOnList, InstructionQueue< Impl >::readyInsts, InstructionQueue< Impl >::readyIt, and MemDepUnit< MemDepPred, Impl >::regsReady().
Referenced by InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::scheduleNonSpec(), and InstructionQueue< Impl >::wakeDependents().
addReadyMemInst()
template<class Impl > void InstructionQueue< Impl >::addReadyMemInst (const DynInstPtr & ready_inst)
Adds a ready memory instruction to the ready list.
Definition at line 1085 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addToOrderList(), DPRINTF, InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::queueOnList, InstructionQueue< Impl >::readyInsts, and InstructionQueue< Impl >::readyIt.
Referenced by InstructionQueue< Impl >::recordProducer(), and InstructionQueue< Impl >::scheduleReadyInsts().
addToDependents()
template<class Impl > bool InstructionQueue< Impl >::addToDependents (const DynInstPtr & new_inst) private
Adds an instruction to the dependency graph, as a consumer.
Definition at line 1368 of file inst_queue_impl.hh.
References RegId::className(), InstructionQueue< Impl >::dependGraph, DPRINTF, PhysRegId::flatIndex(), RegId::index(), PhysRegId::isFixedMapping(), and InstructionQueue< Impl >::regScoreboard.
Referenced by InstructionQueue< Impl >::insert().
addToOrderList()
template<class Impl > void InstructionQueue< Impl >::addToOrderList (OpClass op_class) private
Add an op class to the age order list.
Definition at line 699 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::ListOrderEntry::oldestInst, InstructionQueue< Impl >::queueOnList, InstructionQueue< Impl >::ListOrderEntry::queueType, InstructionQueue< Impl >::readyInsts, and InstructionQueue< Impl >::readyIt.
Referenced by InstructionQueue< Impl >::addIfReady(), and InstructionQueue< Impl >::addReadyMemInst().
addToProducers()
template<class Impl > void InstructionQueue< Impl >::addToProducers (const DynInstPtr & new_inst) private
Adds an instruction to the dependency graph, as a producer.
Definition at line 1416 of file inst_queue_impl.hh.
References RegId::className(), InstructionQueue< Impl >::dependGraph, PhysRegId::flatIndex(), RegId::index(), PhysRegId::isFixedMapping(), panic, and InstructionQueue< Impl >::regScoreboard.
Referenced by InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::recordProducer().
blockMemInst()
template<class Impl > void InstructionQueue< Impl >::blockMemInst (const DynInstPtr & blocked_inst)
Defers a memory instruction when it is cache blocked.
Definition at line 1153 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::blockedMemInsts.
Referenced by InstructionQueue< Impl >::recordProducer().
cacheUnblocked()
template<class Impl > void InstructionQueue< Impl >::cacheUnblocked ()
Notify instruction queue that a previous blockage has resolved.
Definition at line 1162 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::blockedMemInsts, InstructionQueue< Impl >::cpu, and InstructionQueue< Impl >::retryMemInsts.
Referenced by InstructionQueue< Impl >::recordProducer().
commit()
template<class Impl > void InstructionQueue< Impl >::commit (const InstSeqNum & inst, ThreadID tid = 0)
Commits all instructions up to and including the given sequence number, for a specific thread.
Definition at line 972 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::countInsts(), DPRINTF, InstructionQueue< Impl >::freeEntries, InstructionQueue< Impl >::instList, and InstructionQueue< Impl >::numEntries.
Referenced by InstructionQueue< Impl >::recordProducer().
completeMemInst()
template<class Impl > void InstructionQueue< Impl >::completeMemInst (const DynInstPtr & completed_inst)
Completes a memory operation.
Definition at line 1129 of file inst_queue_impl.hh.
References MemDepUnit< MemDepPred, Impl >::completed(), InstructionQueue< Impl >::count, DPRINTF, InstructionQueue< Impl >::freeEntries, and InstructionQueue< Impl >::memDepUnit.
Referenced by InstructionQueue< Impl >::recordProducer(), and InstructionQueue< Impl >::wakeDependents().
countInsts()
template<class Impl > int InstructionQueue< Impl >::countInsts () private
Debugging function to count how many entries are in the IQ.
It does a linear walk through the instructions, so do not call this function during normal execution.
Definition at line 1492 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::freeEntries, and InstructionQueue< Impl >::numEntries.
Referenced by InstructionQueue< Impl >::commit(), InstructionQueue< Impl >::insert(), and InstructionQueue< Impl >::insertNonSpec().
deferMemInst()
template<class Impl > void InstructionQueue< Impl >::deferMemInst (const DynInstPtr & deferred_inst)
Defers a memory instruction when its DTB translation incurs a hw page table walk.
Definition at line 1146 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::deferredMemInsts.
Referenced by InstructionQueue< Impl >::recordProducer().
doSquash()
template<class Impl > void InstructionQueue< Impl >::doSquash (ThreadID tid) private
Does the actual squashing.
Definition at line 1225 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::count, InstructionQueue< Impl >::dependGraph, DPRINTF, PhysRegId::flatIndex(), InstructionQueue< Impl >::fpInstQueueWrites, InstructionQueue< Impl >::freeEntries, InstructionQueue< Impl >::instList, InstructionQueue< Impl >::intInstQueueWrites, InstructionQueue< Impl >::iqSquashedInstsExamined, InstructionQueue< Impl >::iqSquashedNonSpecRemoved, InstructionQueue< Impl >::iqSquashedOperandsExamined, PhysRegId::isFixedMapping(), NoFault, InstructionQueue< Impl >::nonSpecInsts, InstructionQueue< Impl >::squashedSeqNum, and InstructionQueue< Impl >::vecInstQueueWrites.
Referenced by InstructionQueue< Impl >::getCount(), and InstructionQueue< Impl >::squash().
drainSanityCheck()
template<class Impl > void InstructionQueue< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 473 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::dependGraph, InstructionQueue< Impl >::instsToExecute, InstructionQueue< Impl >::memDepUnit, and InstructionQueue< Impl >::numThreads.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
dumpInsts()
template<class Impl > void InstructionQueue< Impl >::dumpInsts () private
Debugging function to dump out all instructions that are in the IQ.
Definition at line 1542 of file inst_queue_impl.hh.
References cprintf(), InstructionQueue< Impl >::instList, InstructionQueue< Impl >::instsToExecute, and InstructionQueue< Impl >::numThreads.
dumpLists()
template<class Impl > void InstructionQueue< Impl >::dumpLists () private
Debugging function to dump all the list sizes, as well as print out the list of nonspeculative instructions.
Should not be used in any other capacity, but it has no harmful sideaffects.
Definition at line 1499 of file inst_queue_impl.hh.
References cprintf(), ArmISA::i, InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::nonSpecInsts, Num_OpClasses, and InstructionQueue< Impl >::readyInsts.
entryAmount()
template<class Impl > int InstructionQueue< Impl >::entryAmount (ThreadID num_threads)
Number of entries needed for given amount of threads.
Definition at line 490 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::iqPolicy, and InstructionQueue< Impl >::numEntries.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
getBlockedMemInstToExecute()
template<class Impl > Impl::DynInstPtr InstructionQueue< Impl >::getBlockedMemInstToExecute ()
Gets a memory instruction that was blocked on the cache.
NULL if none available.
Definition at line 1186 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::retryMemInsts.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts(), and InstructionQueue< Impl >::FUCompletion::setFreeFU().
getCount()
template<class Impl> unsigned InstructionQueue< Impl >::getCount (ThreadID tid) inline
Returns the number of used entries for a thread.
Definition at line 270 of file inst_queue.hh.
References InstructionQueue< Impl >::count, InstructionQueue< Impl >::doSquash(), and InstructionQueue< Impl >::printInsts().
getDeferredMemInstToExecute()
template<class Impl > Impl::DynInstPtr InstructionQueue< Impl >::getDeferredMemInstToExecute ()
Gets a memory instruction that was referred due to a delayed DTB translation if it is now ready to execute.
NULL if none available.
Definition at line 1171 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::deferredMemInsts.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts(), and InstructionQueue< Impl >::FUCompletion::setFreeFU().
getInstToExecute()
template<class Impl > Impl::DynInstPtr InstructionQueue< Impl >::getInstToExecute ()
Returns the oldest scheduled instruction, and removes it from the list of instructions waiting to execute.
Definition at line 682 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::fpInstQueueReads, InstructionQueue< Impl >::instsToExecute, InstructionQueue< Impl >::intInstQueueReads, and InstructionQueue< Impl >::vecInstQueueReads.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
hasReadyInsts()
template<class Impl > bool InstructionQueue< Impl >::hasReadyInsts ()
Returns if there are any ready instructions in the IQ.
Definition at line 563 of file inst_queue_impl.hh.
References ArmISA::i, InstructionQueue< Impl >::listOrder, Num_OpClasses, and InstructionQueue< Impl >::readyInsts.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
insert()
template<class Impl > void InstructionQueue< Impl >::insert (const DynInstPtr & new_inst)
Inserts a new instruction into the IQ.
Definition at line 580 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::addToDependents(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::count, InstructionQueue< Impl >::countInsts(), DPRINTF, InstructionQueue< Impl >::fpInstQueueWrites, InstructionQueue< Impl >::freeEntries, MemDepUnit< MemDepPred, Impl >::insert(), InstructionQueue< Impl >::instList, InstructionQueue< Impl >::intInstQueueWrites, InstructionQueue< Impl >::iqInstsAdded, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::numEntries, and InstructionQueue< Impl >::vecInstQueueWrites.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
insertBarrier()
template<class Impl > void InstructionQueue< Impl >::insertBarrier (const DynInstPtr & barr_inst)
Inserts a memory or write barrier into the IQ to make sure loads and stores are ordered properly.
Definition at line 673 of file inst_queue_impl.hh.
References MemDepUnit< MemDepPred, Impl >::insertBarrier(), InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::memDepUnit.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
insertNonSpec()
template<class Impl > void InstructionQueue< Impl >::insertNonSpec (const DynInstPtr & new_inst)
Inserts a new, non-speculative instruction into the IQ.
Definition at line 626 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::count, InstructionQueue< Impl >::countInsts(), DPRINTF, InstructionQueue< Impl >::fpInstQueueWrites, InstructionQueue< Impl >::freeEntries, MemDepUnit< MemDepPred, Impl >::insertNonSpec(), InstructionQueue< Impl >::instList, InstructionQueue< Impl >::intInstQueueWrites, InstructionQueue< Impl >::iqNonSpecInstsAdded, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::nonSpecInsts, InstructionQueue< Impl >::numEntries, and InstructionQueue< Impl >::vecInstQueueWrites.
Referenced by InstructionQueue< Impl >::insertBarrier(), and InstructionQueue< Impl >::FUCompletion::setFreeFU().
isDrained()
template<class Impl > bool InstructionQueue< Impl >::isDrained () const
Determine if we are drained.
Definition at line 460 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::dependGraph, InstructionQueue< Impl >::instsToExecute, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::numThreads, and InstructionQueue< Impl >::wbOutstanding.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
isFull() [1/2]
template<class Impl > bool InstructionQueue< Impl >::isFull ()
Returns whether or not the IQ is full.
Definition at line 541 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::freeEntries.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
isFull() [2/2]
template<class Impl > bool InstructionQueue< Impl >::isFull (ThreadID tid)
Returns whether or not the IQ is full for a specific thread.
Definition at line 552 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::numFreeEntries().
moveToYoungerInst()
template<class Impl > void InstructionQueue< Impl >::moveToYoungerInst (ListOrderIt age_order_it) private
Called when the oldest instruction has been removed from a ready queue; this places that ready queue into the proper spot in the age order list.
Definition at line 726 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::ListOrderEntry::oldestInst, InstructionQueue< Impl >::ListOrderEntry::queueType, InstructionQueue< Impl >::readyInsts, and InstructionQueue< Impl >::readyIt.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
name()
template<class Impl > std::string InstructionQueue< Impl >::name () const
Returns the name of the IQ.
Definition at line 173 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::cpu.
Referenced by InstructionQueue< Impl >::regStats().
numFreeEntries() [1/2]
template<class Impl > unsigned InstructionQueue< Impl >::numFreeEntries ()
Returns total number of free entries.
Definition at line 525 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::freeEntries.
Referenced by InstructionQueue< Impl >::isFull(), and InstructionQueue< Impl >::FUCompletion::setFreeFU().
numFreeEntries() [2/2]
template<class Impl > unsigned InstructionQueue< Impl >::numFreeEntries (ThreadID tid)
Returns number of free entries for a thread.
Definition at line 532 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::count, and InstructionQueue< Impl >::maxEntries.
printInsts()
template<class Impl> void InstructionQueue< Impl >::printInsts ()
Debug function to print all instructions.
Referenced by InstructionQueue< Impl >::getCount().
processFUCompletion()
template<class Impl > void InstructionQueue< Impl >::processFUCompletion (const DynInstPtr & inst, int fu_idx)
Process FU completion event.
Definition at line 752 of file inst_queue_impl.hh.
References TimeBuffer< T >::access(), InstructionQueue< Impl >::cpu, DPRINTF, FUPool::freeUnitNextCycle(), InstructionQueue< Impl >::fuPool, InstructionQueue< Impl >::iewStage, InstructionQueue< Impl >::instsToExecute, InstructionQueue< Impl >::issueToExecuteQueue, IssueStruct< Impl >::size, and InstructionQueue< Impl >::wbOutstanding.
Referenced by InstructionQueue< Impl >::recordProducer().
recordProducer()
template<class Impl> void InstructionQueue< Impl >::recordProducer (const DynInstPtr & inst) inline
Records the instruction as the producer of a register without adding it to the rest of the IQ.
Definition at line 209 of file inst_queue.hh.
References InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::blockMemInst(), InstructionQueue< Impl >::cacheUnblocked(), InstructionQueue< Impl >::commit(), InstructionQueue< Impl >::completeMemInst(), InstructionQueue< Impl >::deferMemInst(), InstructionQueue< Impl >::FUCompletion::inst, InstructionQueue< Impl >::processFUCompletion(), InstructionQueue< Impl >::replayMemInst(), InstructionQueue< Impl >::rescheduleMemInst(), InstructionQueue< Impl >::scheduleNonSpec(), InstructionQueue< Impl >::scheduleReadyInsts(), Event::squash(), InstructionQueue< Impl >::violation(), and InstructionQueue< Impl >::wakeDependents().
regStats()
template<class Impl > void InstructionQueue< Impl >::regStats ()
Registers statistics.
Definition at line 180 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::cpu, Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::dist, Stats::DataWrap< Derived, InfoProxyType >::flags(), InstructionQueue< Impl >::fpAluAccesses, InstructionQueue< Impl >::fpInstQueueReads, InstructionQueue< Impl >::fpInstQueueWakeupAccesses, InstructionQueue< Impl >::fpInstQueueWrites, InstructionQueue< Impl >::fuBusy, InstructionQueue< Impl >::fuBusyRate, ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), Stats::Vector2dBase< Derived, Stor >::init(), Stats::Distribution::init(), InstructionQueue< Impl >::intAluAccesses, InstructionQueue< Impl >::intInstQueueReads, InstructionQueue< Impl >::intInstQueueWakeupAccesses, InstructionQueue< Impl >::intInstQueueWrites, InstructionQueue< Impl >::iqBranchInstsIssued, InstructionQueue< Impl >::iqFloatInstsIssued, InstructionQueue< Impl >::iqInstsAdded, InstructionQueue< Impl >::iqInstsIssued, InstructionQueue< Impl >::iqIntInstsIssued, InstructionQueue< Impl >::iqMemInstsIssued, InstructionQueue< Impl >::iqMiscInstsIssued, InstructionQueue< Impl >::iqNonSpecInstsAdded, InstructionQueue< Impl >::iqSquashedInstsExamined, InstructionQueue< Impl >::iqSquashedInstsIssued, InstructionQueue< Impl >::iqSquashedNonSpecRemoved, InstructionQueue< Impl >::iqSquashedOperandsExamined, InstructionQueue< Impl >::issueRate, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), Num_OpClasses, InstructionQueue< Impl >::numIssuedDist, InstructionQueue< Impl >::numThreads, Stats::pdf, Stats::DataWrap< Derived, InfoProxyType >::prereq(), MemDepUnit< MemDepPred, Impl >::regStats(), InstructionQueue< Impl >::statFuBusy, InstructionQueue< Impl >::statIssuedInstType, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), Stats::total, InstructionQueue< Impl >::totalWidth, InstructionQueue< Impl >::vecAluAccesses, InstructionQueue< Impl >::vecInstQueueReads, InstructionQueue< Impl >::vecInstQueueWakeupAccesses, InstructionQueue< Impl >::vecInstQueueWrites, and Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubnames().
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
replayMemInst()
template<class Impl > void InstructionQueue< Impl >::replayMemInst (const DynInstPtr & replay_inst)
Replays a memory instruction.
It must be rescheduled first.
Definition at line 1122 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::memDepUnit, and MemDepUnit< MemDepPred, Impl >::replay().
Referenced by InstructionQueue< Impl >::recordProducer().
rescheduleMemInst()
template<class Impl > void InstructionQueue< Impl >::rescheduleMemInst (const DynInstPtr & resched_inst)
Reschedules a memory instruction.
It will be ready to issue once replayMemInst() is called.
Definition at line 1108 of file inst_queue_impl.hh.
References DPRINTF, InstructionQueue< Impl >::memDepUnit, and MemDepUnit< MemDepPred, Impl >::reschedule().
Referenced by InstructionQueue< Impl >::recordProducer().
resetEntries()
template<class Impl > void InstructionQueue< Impl >::resetEntries ()
Resets max entries for all threads.
Definition at line 502 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::activeThreads, InstructionQueue< Impl >::iqPolicy, InstructionQueue< Impl >::maxEntries, InstructionQueue< Impl >::numEntries, and InstructionQueue< Impl >::numThreads.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
resetState()
template<class Impl > void InstructionQueue< Impl >::resetState ()
Resets all instruction queue state.
Definition at line 397 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::blockedMemInsts, InstructionQueue< Impl >::count, InstructionQueue< Impl >::deferredMemInsts, InstructionQueue< Impl >::freeEntries, ArmISA::i, InstructionQueue< Impl >::instList, InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::nonSpecInsts, Num_OpClasses, InstructionQueue< Impl >::numEntries, InstructionQueue< Impl >::numPhysRegs, InstructionQueue< Impl >::queueOnList, InstructionQueue< Impl >::readyInsts, InstructionQueue< Impl >::readyIt, InstructionQueue< Impl >::regScoreboard, InstructionQueue< Impl >::retryMemInsts, InstructionQueue< Impl >::squashedSeqNum, and InstructionQueue< Impl >::wbOutstanding.
Referenced by InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::FUCompletion::setFreeFU(), and InstructionQueue< Impl >::takeOverFrom().
scheduleNonSpec()
template<class Impl > void InstructionQueue< Impl >::scheduleNonSpec (const InstSeqNum & inst)
Schedules a single specific non-speculative instruction.
Definition at line 944 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addIfReady(), DPRINTF, InstructionQueue< Impl >::memDepUnit, MemDepUnit< MemDepPred, Impl >::nonSpecInstReady(), and InstructionQueue< Impl >::nonSpecInsts.
Referenced by InstructionQueue< Impl >::recordProducer().
scheduleReadyInsts()
template<class Impl > void InstructionQueue< Impl >::scheduleReadyInsts ()
Schedules ready instructions, adding the ready ones (oldest first) to the queue to execute.
Definition at line 776 of file inst_queue_impl.hh.
References TimeBuffer< T >::access(), InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::count, InstructionQueue< Impl >::cpu, curTick(), InstructionQueue< Impl >::deferredMemInsts, DPRINTF, InstructionQueue< Impl >::fpAluAccesses, InstructionQueue< Impl >::fpInstQueueReads, InstructionQueue< Impl >::freeEntries, FUPool::freeUnitNextCycle(), InstructionQueue< Impl >::fuBusy, InstructionQueue< Impl >::fuPool, InstructionQueue< Impl >::getBlockedMemInstToExecute(), InstructionQueue< Impl >::getDeferredMemInstToExecute(), FUPool::getOpLatency(), FUPool::getUnit(), InstructionQueue< Impl >::instsToExecute, InstructionQueue< Impl >::intAluAccesses, InstructionQueue< Impl >::intInstQueueReads, InstructionQueue< Impl >::iqInstsIssued, InstructionQueue< Impl >::iqSquashedInstsIssued, FUPool::isPipelined(), MemDepUnit< MemDepPred, Impl >::issue(), InstructionQueue< Impl >::issueToExecuteQueue, InstructionQueue< Impl >::listOrder, InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::moveToYoungerInst(), FUPool::NoCapableFU, FUPool::NoFreeFU, InstructionQueue< Impl >::numIssuedDist, InstructionQueue< Impl >::queueOnList, InstructionQueue< Impl >::readyInsts, InstructionQueue< Impl >::readyIt, InstructionQueue< Impl >::retryMemInsts, Stats::DistBase< Derived, Stor >::sample(), InstructionQueue< Impl >::FUCompletion::setFreeFU(), IssueStruct< Impl >::size, InstructionQueue< Impl >::statFuBusy, InstructionQueue< Impl >::statIssuedInstType, InstructionQueue< Impl >::totalWidth, InstructionQueue< Impl >::vecAluAccesses, InstructionQueue< Impl >::vecInstQueueReads, and InstructionQueue< Impl >::wbOutstanding.
Referenced by InstructionQueue< Impl >::recordProducer().
setActiveThreads()
template<class Impl > void InstructionQueue< Impl >::setActiveThreads (std::list< ThreadID > * at_ptr)
Sets active threads list.
Definition at line 437 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::activeThreads.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
setIssueToExecuteQueue()
template<class Impl > void InstructionQueue< Impl >::setIssueToExecuteQueue (TimeBuffer< IssueStruct > * i2eQueue)
Sets the timer buffer between issue and execute.
Definition at line 444 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::issueToExecuteQueue.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
setTimeBuffer()
template<class Impl > void InstructionQueue< Impl >::setTimeBuffer (TimeBuffer< TimeStruct > * tb_ptr)
Sets the global time buffer.
Definition at line 451 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::commitToIEWDelay, InstructionQueue< Impl >::fromCommit, TimeBuffer< T >::getWire(), and InstructionQueue< Impl >::timeBuffer.
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
squash()
template<class Impl > void InstructionQueue< Impl >::squash (ThreadID tid)
Squashes instructions for a thread.
Squashing information is obtained from the time buffer.
Definition at line 1208 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::doSquash(), DPRINTF, InstructionQueue< Impl >::fromCommit, InstructionQueue< Impl >::memDepUnit, MemDepUnit< MemDepPred, Impl >::squash(), and InstructionQueue< Impl >::squashedSeqNum.
takeOverFrom()
template<class Impl > void InstructionQueue< Impl >::takeOverFrom ()
Takes over execution from another CPU's thread.
Definition at line 483 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::resetState().
Referenced by InstructionQueue< Impl >::FUCompletion::setFreeFU().
violation()
template<class Impl > void InstructionQueue< Impl >::violation (const DynInstPtr & store, const DynInstPtr & faulting_load)
Indicates an ordering violation between a store and a load.
Definition at line 1199 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::intInstQueueWrites, InstructionQueue< Impl >::memDepUnit, and MemDepUnit< MemDepPred, Impl >::violation().
Referenced by InstructionQueue< Impl >::recordProducer().
wakeDependents()
template<class Impl > int InstructionQueue< Impl >::wakeDependents (const DynInstPtr & completed_inst)
Wakes all dependents of a completed instruction.
Definition at line 990 of file inst_queue_impl.hh.
References InstructionQueue< Impl >::addIfReady(), RegId::className(), MemDepUnit< MemDepPred, Impl >::completeBarrier(), InstructionQueue< Impl >::completeMemInst(), PhysRegId::decrNumPinnedWritesToComplete(), InstructionQueue< Impl >::dependGraph, DPRINTF, PhysRegId::flatIndex(), InstructionQueue< Impl >::fpInstQueueWakeupAccesses, PhysRegId::getNumPinnedWritesToComplete(), RegId::index(), InstructionQueue< Impl >::intInstQueueWakeupAccesses, PhysRegId::isFixedMapping(), PhysRegId::isPinned(), InstructionQueue< Impl >::memDepUnit, InstructionQueue< Impl >::regScoreboard, InstructionQueue< Impl >::vecInstQueueWakeupAccesses, and MemDepUnit< MemDepPred, Impl >::wakeDependents().
Referenced by InstructionQueue< Impl >::recordProducer().
Member Data Documentation
activeThreads
template<class Impl> std::list<ThreadID>* InstructionQueue< Impl >::activeThreads private
Pointer to list of active threads.
Definition at line 414 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::resetEntries(), and InstructionQueue< Impl >::setActiveThreads().
blockedMemInsts
template<class Impl> std::list<DynInstPtr> InstructionQueue< Impl >::blockedMemInsts private
List of instructions that have been cache blocked.
Definition at line 327 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::blockMemInst(), InstructionQueue< Impl >::cacheUnblocked(), and InstructionQueue< Impl >::resetState().
commitToIEWDelay
template<class Impl> Cycles InstructionQueue< Impl >::commitToIEWDelay private
Delay between commit stage and the IQ.
Todo:
: Make there be a distinction between the delays within IEW.
Definition at line 440 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::setTimeBuffer().
count
template<class Impl> unsigned InstructionQueue< Impl >::count[Impl::MaxThreads] private
Per Thread IQ count.
Definition at line 417 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::completeMemInst(), InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::getCount(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::numFreeEntries(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
cpu
template<class Impl> O3CPU* InstructionQueue< Impl >::cpu private
Pointer to the CPU.
Definition at line 284 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::cacheUnblocked(), InstructionQueue< Impl >::name(), InstructionQueue< Impl >::processFUCompletion(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
dcacheInterface
template<class Impl> MemInterface* InstructionQueue< Impl >::dcacheInterface private
Cache interface.
Definition at line 287 of file inst_queue.hh.
deferredMemInsts
template<class Impl> std::list<DynInstPtr> InstructionQueue< Impl >::deferredMemInsts private
List of instructions waiting for their DTB translation to complete (hw page table walk in progress).
Definition at line 324 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::deferMemInst(), InstructionQueue< Impl >::getDeferredMemInstToExecute(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
dependGraph
template<class Impl> DependencyGraph<DynInstPtr> InstructionQueue< Impl >::dependGraph private
Definition at line 401 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addToDependents(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::drainSanityCheck(), InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::isDrained(), InstructionQueue< Impl >::wakeDependents(), and InstructionQueue< Impl >::~InstructionQueue().
fpAluAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::fpAluAccesses
Definition at line 546 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
fpInstQueueReads
template<class Impl> Stats::Scalar InstructionQueue< Impl >::fpInstQueueReads
Definition at line 538 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::getInstToExecute(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
fpInstQueueWakeupAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::fpInstQueueWakeupAccesses
Definition at line 540 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::wakeDependents().
fpInstQueueWrites
template<class Impl> Stats::Scalar InstructionQueue< Impl >::fpInstQueueWrites
Definition at line 539 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::regStats().
freeEntries
template<class Impl> unsigned InstructionQueue< Impl >::freeEntries private
Number of free IQ entries left.
Definition at line 423 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::commit(), InstructionQueue< Impl >::completeMemInst(), InstructionQueue< Impl >::countInsts(), InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::isFull(), InstructionQueue< Impl >::numFreeEntries(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
fromCommit
template<class Impl> TimeBuffer<TimeStruct>::wire InstructionQueue< Impl >::fromCommit private
Wire to read information from timebuffer.
Definition at line 306 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::setTimeBuffer(), and InstructionQueue< Impl >::squash().
fuBusy
template<class Impl> Stats::Vector InstructionQueue< Impl >::fuBusy private
Number of times the FU was busy.
Definition at line 531 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
fuBusyRate
template<class Impl> Stats::Formula InstructionQueue< Impl >::fuBusyRate private
Number of times the FU was busy per instruction issued.
Definition at line 533 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
fuPool
template<class Impl> FUPool* InstructionQueue< Impl >::fuPool private
Function unit pool.
Definition at line 309 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::processFUCompletion(), and InstructionQueue< Impl >::scheduleReadyInsts().
iewStage
template<class Impl> IEW* InstructionQueue< Impl >::iewStage private
Pointer to IEW stage.
Definition at line 290 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::processFUCompletion().
instList
template<class Impl> std::list<DynInstPtr> InstructionQueue< Impl >::instList[Impl::MaxThreads] private
List of all the instructions in the IQ (some of which may be issued).
Definition at line 316 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::commit(), InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::dumpInsts(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::resetState().
instsToExecute
template<class Impl> std::list<DynInstPtr> InstructionQueue< Impl >::instsToExecute private
List of instructions that are ready to be executed.
Definition at line 319 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::drainSanityCheck(), InstructionQueue< Impl >::dumpInsts(), InstructionQueue< Impl >::getInstToExecute(), InstructionQueue< Impl >::isDrained(), InstructionQueue< Impl >::processFUCompletion(), and InstructionQueue< Impl >::scheduleReadyInsts().
intAluAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::intAluAccesses
Definition at line 545 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
intInstQueueReads
template<class Impl> Stats::Scalar InstructionQueue< Impl >::intInstQueueReads
Definition at line 535 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::getInstToExecute(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
intInstQueueWakeupAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::intInstQueueWakeupAccesses
Definition at line 537 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::wakeDependents().
intInstQueueWrites
template<class Impl> Stats::Scalar InstructionQueue< Impl >::intInstQueueWrites
Definition at line 536 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::violation().
iqBranchInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqBranchInstsIssued private
Stat for number of branch instructions issued.
Definition at line 490 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
iqFloatInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqFloatInstsIssued private
Stat for number of floating point instructions issued.
Definition at line 488 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
iqInstsAdded
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqInstsAdded private
Stat for number of instructions added.
Definition at line 480 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::insert(), and InstructionQueue< Impl >::regStats().
iqInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqInstsIssued private
Definition at line 484 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
iqIntInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqIntInstsIssued private
Stat for number of integer instructions issued.
Definition at line 486 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
iqMemInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqMemInstsIssued private
Stat for number of memory instructions issued.
Definition at line 492 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
iqMiscInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqMiscInstsIssued private
Stat for number of miscellaneous instructions issued.
Definition at line 494 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
iqNonSpecInstsAdded
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqNonSpecInstsAdded private
Stat for number of non-speculative instructions added.
Definition at line 482 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::regStats().
iqPolicy
template<class Impl> SMTQueuePolicy InstructionQueue< Impl >::iqPolicy private
IQ sharing policy for SMT.
Definition at line 408 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::entryAmount(), InstructionQueue< Impl >::InstructionQueue(), and InstructionQueue< Impl >::resetEntries().
iqSquashedInstsExamined
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqSquashedInstsExamined private
Stat for number of squashed instructions examined when squashing.
Definition at line 498 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), and InstructionQueue< Impl >::regStats().
iqSquashedInstsIssued
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqSquashedInstsIssued private
Stat for number of squashed instructions that were ready to issue.
Definition at line 496 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
iqSquashedNonSpecRemoved
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqSquashedNonSpecRemoved private
Stat for number of non-speculative instructions removed due to a squash.
Definition at line 505 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), and InstructionQueue< Impl >::regStats().
iqSquashedOperandsExamined
template<class Impl> Stats::Scalar InstructionQueue< Impl >::iqSquashedOperandsExamined private
Stat for number of squashed instruction operands examined when squashing.
Definition at line 502 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), and InstructionQueue< Impl >::regStats().
issueRate
template<class Impl> Stats::Formula InstructionQueue< Impl >::issueRate private
Number of instructions issued per cycle.
Definition at line 528 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats().
issueToExecuteQueue
template<class Impl> TimeBuffer<IssueStruct>* InstructionQueue< Impl >::issueToExecuteQueue private
The queue to the execute stage.
Issued instructions will be written into it.
Definition at line 300 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::processFUCompletion(), InstructionQueue< Impl >::scheduleReadyInsts(), and InstructionQueue< Impl >::setIssueToExecuteQueue().
listOrder
template<class Impl> std::list<ListOrderEntry> InstructionQueue< Impl >::listOrder private
List that contains the age order of the oldest instruction of each ready queue.
Used to select the oldest instruction available among op classes.
Todo:
: Might be better to just move these entries around instead of creating new ones every time the position changes due to an instruction issuing. Not sure std::list supports this.
Definition at line 380 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::addToOrderList(), InstructionQueue< Impl >::dumpLists(), InstructionQueue< Impl >::hasReadyInsts(), InstructionQueue< Impl >::moveToYoungerInst(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
maxEntries
template<class Impl> unsigned InstructionQueue< Impl >::maxEntries[Impl::MaxThreads] private
Max IQ Entries Per Thread.
Definition at line 420 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::numFreeEntries(), and InstructionQueue< Impl >::resetEntries().
memDepUnit
template<class Impl> MemDepUnit InstructionQueue< Impl >::memDepUnit[Impl::MaxThreads] private
The memory dependence unit, which tracks/predicts memory dependences between instructions.
Definition at line 295 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::completeMemInst(), InstructionQueue< Impl >::drainSanityCheck(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertBarrier(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::isDrained(), InstructionQueue< Impl >::regStats(), InstructionQueue< Impl >::replayMemInst(), InstructionQueue< Impl >::rescheduleMemInst(), InstructionQueue< Impl >::scheduleNonSpec(), InstructionQueue< Impl >::scheduleReadyInsts(), InstructionQueue< Impl >::squash(), InstructionQueue< Impl >::violation(), and InstructionQueue< Impl >::wakeDependents().
nonSpecInsts
template<class Impl> std::map<InstSeqNum, DynInstPtr> InstructionQueue< Impl >::nonSpecInsts private
List of non-speculative instructions that will be scheduled once the IQ gets a signal from commit.
While it's redundant to have the key be a part of the value (the sequence number is stored inside of DynInst), when these instructions are woken up only the sequence number will be available. Thus it is most efficient to be able to search by the sequence number alone.
Definition at line 363 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::dumpLists(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleNonSpec().
numEntries
template<class Impl> unsigned InstructionQueue< Impl >::numEntries private
The number of entries in the instruction queue.
Definition at line 426 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::commit(), InstructionQueue< Impl >::countInsts(), InstructionQueue< Impl >::entryAmount(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::resetEntries(), and InstructionQueue< Impl >::resetState().
numIssuedDist
template<class Impl> Stats::Distribution InstructionQueue< Impl >::numIssuedDist private
Distribution of number of instructions in the queue.
Todo:
: Need to create struct to track the entry time for each instruction.
Distribution of the number of instructions issued.
Definition at line 513 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
numPhysRegs
template<class Impl> unsigned InstructionQueue< Impl >::numPhysRegs private
The number of physical registers in the CPU.
Definition at line 432 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::InstructionQueue(), and InstructionQueue< Impl >::resetState().
numThreads
template<class Impl> ThreadID InstructionQueue< Impl >::numThreads private
Number of Total Threads.
Definition at line 411 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::drainSanityCheck(), InstructionQueue< Impl >::dumpInsts(), InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::isDrained(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::resetEntries().
queueOnList
template<class Impl> bool InstructionQueue< Impl >::queueOnList[Num_OpClasses] private
Tracks if each ready queue is on the age order list.
Definition at line 385 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::addToOrderList(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
readyInsts
template<class Impl> ReadyInstQueue InstructionQueue< Impl >::readyInsts[Num_OpClasses] private
List of ready instructions, per op class.
They are separated by op class to allow for easy mapping to FUs.
Definition at line 354 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::addToOrderList(), InstructionQueue< Impl >::dumpLists(), InstructionQueue< Impl >::hasReadyInsts(), InstructionQueue< Impl >::moveToYoungerInst(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
readyIt
template<class Impl> ListOrderIt InstructionQueue< Impl >::readyIt[Num_OpClasses] private
Iterators of each ready queue.
Points to their spot in the age order list.
Definition at line 390 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addIfReady(), InstructionQueue< Impl >::addReadyMemInst(), InstructionQueue< Impl >::addToOrderList(), InstructionQueue< Impl >::moveToYoungerInst(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
regScoreboard
template<class Impl> std::vector<bool> InstructionQueue< Impl >::regScoreboard private
A cache of the recently woken registers.
It is 1 if the register has been woken up recently, and 0 if the register has been added to the dependency graph and has not yet received its value. It is basically a secondary scoreboard, and should pretty much mirror the scoreboard that exists in the rename map.
Definition at line 451 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::addToDependents(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::InstructionQueue(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::wakeDependents().
retryMemInsts
template<class Impl> std::list<DynInstPtr> InstructionQueue< Impl >::retryMemInsts private
List of instructions that were cache blocked, but a retry has been seen since, so they can now be retried.
May fail again go on the blocked list.
Definition at line 332 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::cacheUnblocked(), InstructionQueue< Impl >::getBlockedMemInstToExecute(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
squashedSeqNum
template<class Impl> InstSeqNum InstructionQueue< Impl >::squashedSeqNum[Impl::MaxThreads] private
The sequence number of the squashed instruction.
Definition at line 443 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::squash().
statFuBusy
template<class Impl> Stats::Vector InstructionQueue< Impl >::statFuBusy private
Distribution of the cycles it takes to issue an instruction.
Todo:
: Need to create struct to track the ready time for each instruction.
Number of times an instruction could not be issued because a FU was busy.
Definition at line 522 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
statIssuedInstType
template<class Impl> Stats::Vector2d InstructionQueue< Impl >::statIssuedInstType private
Stat for total number issued for each instruction type.
Definition at line 525 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
timeBuffer
template<class Impl> TimeBuffer<TimeStruct>* InstructionQueue< Impl >::timeBuffer private
The backwards time buffer.
Definition at line 303 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::setTimeBuffer().
totalWidth
template<class Impl> unsigned InstructionQueue< Impl >::totalWidth private
The total number of instructions that can be issued in one cycle.
Definition at line 429 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
vecAluAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::vecAluAccesses
Definition at line 547 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
vecInstQueueReads
template<class Impl> Stats::Scalar InstructionQueue< Impl >::vecInstQueueReads
Definition at line 541 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::getInstToExecute(), InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::scheduleReadyInsts().
vecInstQueueWakeupAccesses
template<class Impl> Stats::Scalar InstructionQueue< Impl >::vecInstQueueWakeupAccesses
Definition at line 543 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::regStats(), and InstructionQueue< Impl >::wakeDependents().
vecInstQueueWrites
template<class Impl> Stats::Scalar InstructionQueue< Impl >::vecInstQueueWrites
Definition at line 542 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::doSquash(), InstructionQueue< Impl >::insert(), InstructionQueue< Impl >::insertNonSpec(), and InstructionQueue< Impl >::regStats().
wbOutstanding
template<class Impl> int InstructionQueue< Impl >::wbOutstanding private
Number of instructions currently in flight to FUs.
Definition at line 435 of file inst_queue.hh.
Referenced by InstructionQueue< Impl >::isDrained(), InstructionQueue< Impl >::processFUCompletion(), InstructionQueue< Impl >::resetState(), and InstructionQueue< Impl >::scheduleReadyInsts().
The documentation for this class was generated from the following files:
cpu/o3/inst_queue.hh
cpu/o3/inst_queue_impl.hh