gem5: ArmISA::StackTrace Class Reference
ArmISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Protected Types
typedef ArmISA::MachInst MachInst
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 63 of file stacktrace.hh.
Member Typedef Documentation
MachInst
typedef ArmISA::MachInst ArmISA::StackTrace::MachInst protected
Definition at line 66 of file stacktrace.hh.
Constructor & Destructor Documentation
StackTrace() [1/2]
ArmISA::StackTrace::StackTrace ()
Definition at line 114 of file stacktrace.cc.
StackTrace() [2/2]
ArmISA::StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 119 of file stacktrace.cc.
References trace().
~StackTrace()
ArmISA::StackTrace::~StackTrace ()
Definition at line 125 of file stacktrace.cc.
Member Function Documentation
clear()
void ArmISA::StackTrace::clear () inline
Definition at line 84 of file stacktrace.hh.
decodePrologue()
bool ArmISA::StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) private
Definition at line 157 of file stacktrace.cc.
References DPRINTFN, and Stats::dump().
decodeSave()
bool ArmISA::StackTrace::decodeSave (MachInst inst, int & reg, int & disp) private
Definition at line 147 of file stacktrace.cc.
decodeStack()
bool ArmISA::StackTrace::decodeStack (MachInst inst, int & disp) private
Definition at line 141 of file stacktrace.cc.
dprintf()
void ArmISA::StackTrace::dprintf () inline
Definition at line 104 of file stacktrace.hh.
getstack()
const std::vector<Addr>& ArmISA::StackTrace::getstack () const inline
Definition at line 94 of file stacktrace.hh.
References DTRACE, Stats::dump(), and X86ISA::stack.
isEntry()
bool ArmISA::StackTrace::isEntry (Addr addr) private
Definition at line 135 of file stacktrace.cc.
trace() [1/2]
void ArmISA::StackTrace::trace (ThreadContext * tc, bool is_call) private
Definition at line 130 of file stacktrace.cc.
Referenced by StackTrace().
trace() [2/2]
bool ArmISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 109 of file stacktrace.hh.
References StaticInst::isCall(), and StaticInst::isReturn().
valid()
bool ArmISA::StackTrace::valid () const inline
Definition at line 90 of file stacktrace.hh.
Member Data Documentation
stack
std::vector<Addr> ArmISA::StackTrace::stack private
Definition at line 69 of file stacktrace.hh.
tc
ThreadContext* ArmISA::StackTrace::tc private
Definition at line 68 of file stacktrace.hh.
The documentation for this class was generated from the following files:
arch/arm/stacktrace.hh
arch/arm/stacktrace.cc