gem5: AddrRange Class Reference
AddrRange Class Reference
The AddrRange class encapsulates an address range, and supports a number of tests to check if two ranges intersect, if a range contains a specific address etc.
#include <addr_range.hh>
Public Member Functions
AddrRange ()
AddrRange (Addr _start, Addr _end, const std::vector< Addr > &_masks, uint8_t _intlv_match)
Construct an address range.
AddrRange (Addr _start, Addr _end, uint8_t _intlv_high_bit, uint8_t _xor_high_bit, uint8_t _intlv_bits, uint8_t _intlv_match)
Legacy constructor of AddrRange.
AddrRange (Addr _start, Addr _end)
AddrRange (const std::vector< AddrRange > &ranges)
Create an address range by merging a collection of interleaved ranges.
bool interleaved () const
Determine if the range is interleaved or not.
uint64_t granularity () const
Determing the interleaving granularity of the range.
uint32_t stripes () const
Determine the number of interleaved address stripes this range is part of.
Addr size () const
Get the size of the address range.
bool valid () const
Determine if the range is valid.
Addr start () const
Get the start address of the range.
Addr end () const
Get the end address of the range.
std::string to_string () const
Get a string representation of the range.
bool mergesWith (const AddrRange &r) const
Determine if another range merges with the current one, i.e.
bool intersects (const AddrRange &r) const
Determine if another range intersects this one, i.e.
bool isSubset (const AddrRange &r) const
Determine if this range is a subset of another range, i.e.
bool contains (const Addr &a) const
Determine if the range contains an address.
Addr removeIntlvBits (Addr a) const
Remove the interleaving bits from an input address.
Addr addIntlvBits (Addr a) const
This method adds the interleaving bits removed by removeIntlvBits.
Addr getOffset (const Addr &a) const
Determine the offset of an address within the range.
bool operator< (const AddrRange &r) const
Less-than operator used to turn an STL map into a binary search tree of non-overlapping address ranges.
bool operator== (const AddrRange &r) const
bool operator!= (const AddrRange &r) const
Private Attributes
Addr _start
Private fields for the start and end of the range _start is the beginning of the range (inclusive).
Addr _end
std::vector< Addr > masks
Each mask determines the bits we need to xor to get one bit of sel.
uint8_t intlvMatch
The value to compare sel with.
Detailed Description
The AddrRange class encapsulates an address range, and supports a number of tests to check if two ranges intersect, if a range contains a specific address etc.
Besides a basic range, the AddrRange also support interleaved ranges, to stripe across cache banks, or memory controllers. The interleaving is implemented by allowing a number of bits of the address, at an arbitrary bit position, to be used as interleaving bits with an associated matching value. In addition, to prevent uniformly strided address patterns from a very biased interleaving, we also allow XOR-based hashing by specifying a set of bits to XOR with before matching.
The AddrRange is also able to coalesce a number of interleaved ranges to a contiguous range.
Definition at line 72 of file addr_range.hh.
Constructor & Destructor Documentation
AddrRange() [1/5]
AddrRange::AddrRange () inline
Definition at line 95 of file addr_range.hh.
Referenced by RangeEx(), RangeIn(), and RangeSize().
AddrRange() [2/5]
AddrRange::AddrRange (Addr _start, Addr _end, const std::vector< Addr > & _masks, uint8_t _intlv_match) inline
Construct an address range.
If the user provides a non empty vector of masks then the address range is interleaved. Each mask determines a set of bits that are xored to determine one bit of the sel value, starting from the least significant bit (i.e., masks[0] determines the least significant bit of sel, ...). If sel matches the provided _intlv_match then the address a is in the range.
For example if the input mask is _masks = { 1 << 8 | 1 << 11 | 1 << 13, 1 << 15 | 1 << 17 | 1 << 19}
Then a belongs to the address range if _start <= a < _end and sel == _intlv_match where sel[0] = a[8] ^ a[11] ^ a[13] sel[1] = a[15] ^ a[17] ^ a[19]
Parameters
_start The start address of this range
_end The end address of this range (not included in the range)
_masks The input vector of masks
intlv_match The matching value of the xor operations
Definition at line 127 of file addr_range.hh.
References fatal_if, and ULL.
AddrRange() [3/5]
AddrRange::AddrRange (Addr _start, Addr _end, uint8_t _intlv_high_bit, uint8_t _xor_high_bit, uint8_t _intlv_bits, uint8_t _intlv_match) inline
Legacy constructor of AddrRange.
If the user provides a non-zero value in _intlv_high_bit the address range is interleaved.
An address a belongs to the address range if _start <= a < _end and sel == _intlv_match where sel = sel1 ^ sel2 sel1 = a[_intlv_low_bit:_intlv_high_bit] sel2 = a[_xor_low_bit:_xor_high_bit] _intlv_low_bit = _intlv_high_bit - intv_bits _xor_low_bit = _xor_high_bit - intv_bits
Parameters
_start The start address of this range
_end The end address of this range (not included in the range)
_intlv_high_bit The MSB of the intlv bits (disabled if 0)
_xor_high_bit The MSB of the xor bit (disabled if 0)
_intlv_bits the size, in bits, of the intlv and xor bits
intlv_match The matching value of the xor operations
Definition at line 162 of file addr_range.hh.
References fatal, fatal_if, ArmISA::i, ArmISA::mask, and ULL.
AddrRange() [4/5]
AddrRange::AddrRange (Addr _start, Addr _end) inline
Definition at line 200 of file addr_range.hh.
AddrRange() [5/5]
AddrRange::AddrRange (const std::vector< AddrRange > & ranges) inline
Create an address range by merging a collection of interleaved ranges.
Parameters
ranges Interleaved ranges to be merged
Definition at line 210 of file addr_range.hh.
References fatal, mergesWith(), MipsISA::r, to_string(), and ULL.
Member Function Documentation
addIntlvBits()
Addr AddrRange::addIntlvBits (Addr a) const inline
This method adds the interleaving bits removed by removeIntlvBits.
Definition at line 479 of file addr_range.hh.
References ArmISA::a, bits(), ctz64(), ArmISA::i, insertBits(), and popCount().
Referenced by ChannelAddr::getPA(), and TEST().
contains()
bool AddrRange::contains (const Addr & a) const inline
Determine if the range contains an address.
Parameters
a Address to compare with
Returns
true if the address is in the range
Definition at line 406 of file addr_range.hh.
References _end, ArmISA::i, intlvMatch, popCount(), and ArmISA::sel.
Referenced by System::allocPhysPages(), X86ISA::TLB::finalizePhysical(), ArmISA::TLB::finalizePhysical(), Gicv3::getRedistributorByAddr(), intersects(), isSubset(), TsunamiPChip::read(), Gicv3::read(), Gicv3Its::read(), Gicv3Redistributor::read(), Gicv3Distributor::read(), GenericTimerMem::read(), GicV2::read(), GicV2::readDistributor(), Trace::TarmacParserRecord::readMemNoEffect(), SMMUControlPort::recvAtomic(), TEST(), TsunamiPChip::write(), Gicv3::write(), Gicv3Its::write(), Gicv3Redistributor::write(), Gicv3Distributor::write(), GenericTimerMem::write(), GicV2::write(), and GicV2::writeDistributor().
end()
Addr AddrRange::end () const inline
Get the end address of the range.
Definition at line 302 of file addr_range.hh.
References _end.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), init_range(), and TEST().
getOffset()
Addr AddrRange::getOffset (const Addr & a) const inline
Determine the offset of an address within the range.
This function returns the offset of the given address from the starting address discarding any bits that are used for interleaving. This way we can convert the input address to a new unique address in a continuous range that starts from 0.
Parameters
the input address
Returns
the flat offset in the address range
Definition at line 524 of file addr_range.hh.
References _end, _start, interleaved(), MaxAddr, and removeIntlvBits().
Referenced by DRAMCtrl::getCtrlAddr(), and TEST().
granularity()
uint64_t AddrRange::granularity () const inline
Determing the interleaving granularity of the range.
Returns
The size of the regions created by the interleaving bits
Definition at line 257 of file addr_range.hh.
References ctz64(), interleaved(), ArmISA::mask, size(), and ULL.
Referenced by DRAMCtrl::DRAMCtrl(), DRAMCtrl::init(), init_range(), isSubset(), and TEST().
interleaved()
bool AddrRange::interleaved () const inline
Determine if the range is interleaved or not.
Returns
true if interleaved
Definition at line 250 of file addr_range.hh.
Referenced by ChannelAddrRange::ChannelAddrRange(), PhysicalMemory::createBackingStore(), KvmVM::delayedStartup(), DRAMCtrl::DRAMCtrl(), getOffset(), granularity(), DRAMCtrl::init(), init_range(), intersects(), isSubset(), AbstractMemory::setBackingStore(), TEST(), and to_string().
intersects()
bool AddrRange::intersects (const AddrRange & r) const inline
Determine if another range intersects this one, i.e.
if there is an address that is both in this range and the other range. No check is made to ensure either range is valid.
Parameters
r Range to intersect with
Returns
true if the intersection of the two ranges is not empty
Definition at line 351 of file addr_range.hh.
References _end, _start, contains(), interleaved(), intlvMatch, mergesWith(), panic, size(), start(), and to_string().
Referenced by init_range(), AddrRangeMap< AbstractMemory *, 1 >::intersects(), and TEST().
isSubset()
bool AddrRange::isSubset (const AddrRange & r) const inline
Determine if this range is a subset of another range, i.e.
if every address in this range is also in the other range. No check is made to ensure either range is valid.
Parameters
r Range to compare with
Returns
true if the this range is a subset of the other one
Definition at line 383 of file addr_range.hh.
References _end, _start, contains(), granularity(), interleaved(), panic, size(), and to_string().
Referenced by AbstractMemory::access(), AddrRangeMap< AbstractMemory *, 1 >::contains(), BaseXBar::findPort(), AbstractMemory::functionalAccess(), init_range(), and TEST().
mergesWith()
bool AddrRange::mergesWith (const AddrRange & r) const inline
Determine if another range merges with the current one, i.e.
if they are part of the same contigous range and have the same interleaving bits.
Parameters
r Range to evaluate merging with
Returns
true if the two ranges would merge
Definition at line 337 of file addr_range.hh.
References _end, _start, and masks.
Referenced by AddrRange(), init_range(), intersects(), and TEST().
operator!=()
bool AddrRange::operator!= (const AddrRange & r) const inline
Definition at line 564 of file addr_range.hh.
References MipsISA::r.
operator<()
bool AddrRange::operator< (const AddrRange & r) const inline
Less-than operator used to turn an STL map into a binary search tree of non-overlapping address ranges.
Parameters
r Range to compare with
Returns
true if the start address is less than that of the other range
Definition at line 544 of file addr_range.hh.
References _start, and intlvMatch.
operator==()
bool AddrRange::operator== (const AddrRange & r) const inline
Definition at line 554 of file addr_range.hh.
References _end, _start, intlvMatch, and masks.
removeIntlvBits()
Addr AddrRange::removeIntlvBits (Addr a) const inline
Remove the interleaving bits from an input address.
This function returns a new address in a continous range [ start, start + size / intlv_bits). We can achieve this by discarding the LSB in each mask.
e.g., if the input address is of the form:
| a_high | x1 | a_mid | x0 | a_low |
where x0 is the LSB set in masks[0] and x1 is the LSB set in masks[1]
this function will return:
| 0 | a_high | a_mid | a_low |
Parameters
a the input address
Returns
the new address
Definition at line 449 of file addr_range.hh.
References ArmISA::a, ctz64(), ArmISA::i, and insertBits().
Referenced by getOffset(), and TEST().
size()
Addr AddrRange::size () const inline
Get the size of the address range.
For a case where interleaving is used we make the simplifying assumption that the size is a divisible by the size of the interleaving slice.
Definition at line 284 of file addr_range.hh.
Referenced by KvmVM::coalesceMMIO(), PhysicalMemory::createBackingStore(), KvmVM::delayedStartup(), granularity(), init_range(), intersects(), isSubset(), PhysicalMemory::serializeStore(), AbstractMemory::size(), SMMUv3::SMMUv3(), TEST(), and PhysicalMemory::unserializeStore().
start()
Addr AddrRange::start () const inline
Get the start address of the range.
Definition at line 297 of file addr_range.hh.
References _start.
Referenced by AbstractMemory::access(), KvmVM::coalesceMMIO(), MuxingKvmGic::copyGicState(), KvmVM::delayedStartup(), X86ISA::TLB::finalizePhysical(), AbstractMemory::functionalAccess(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), Gicv3::getRedistributorByAddr(), init_range(), intersects(), TsunamiPChip::read(), Gicv3::read(), Gicv3Its::read(), Gicv3Redistributor::read(), Gicv3Distributor::read(), GenericTimerMem::read(), SMMUv3::readControl(), GicV2::readCpu(), GicV2::readDistributor(), AbstractMemory::start(), TEST(), TsunamiPChip::write(), Gicv3::write(), Gicv3Its::write(), Gicv3Redistributor::write(), Gicv3Distributor::write(), GenericTimerMem::write(), SMMUv3::writeControl(), GicV2::writeCpu(), and GicV2::writeDistributor().
stripes()
uint32_t AddrRange::stripes () const inline
Determine the number of interleaved address stripes this range is part of.
Returns
The number of stripes spanned by the interleaving bits
Definition at line 277 of file addr_range.hh.
References ULL.
Referenced by init_range(), and TEST().
to_string()
std::string AddrRange::to_string () const inline
Get a string representation of the range.
This could alternatively be implemented as a operator<<, but at the moment that seems like overkill.
Definition at line 309 of file addr_range.hh.
References bits(), csprintf(), ctz64(), ArmISA::i, interleaved(), ArmISA::mask, and ULL.
Referenced by AddrRange(), PhysicalMemory::createBackingStore(), BaseXBar::findPort(), init_range(), intersects(), isSubset(), and TEST().
valid()
bool AddrRange::valid () const inline
Determine if the range is valid.
Definition at line 292 of file addr_range.hh.
References _end.
Referenced by ChannelAddrRange::ChannelAddrRange(), init_range(), and TEST().
Member Data Documentation
_end
Addr AddrRange::_end private
Definition at line 81 of file addr_range.hh.
Referenced by contains(), end(), getOffset(), intersects(), isSubset(), mergesWith(), operator==(), and valid().
_start
Addr AddrRange::_start private
Private fields for the start and end of the range _start is the beginning of the range (inclusive).
_end is not part of the range.
Definition at line 80 of file addr_range.hh.
Referenced by getOffset(), intersects(), isSubset(), mergesWith(), operator<(), operator==(), and start().
intlvMatch
uint8_t AddrRange::intlvMatch private
The value to compare sel with.
Definition at line 91 of file addr_range.hh.
Referenced by contains(), intersects(), operator<(), and operator==().
masks
std::vector<Addr> AddrRange::masks private
Each mask determines the bits we need to xor to get one bit of sel.
The first (0) mask is used to get the LSB and the last for the MSB of sel.
Definition at line 88 of file addr_range.hh.
Referenced by mergesWith(), and operator==().
The documentation for this class was generated from the following file:
base/addr_range.hh