gem5: PhysRegId Class Reference
PhysRegId Class Reference
Physical register ID.
#include <reg_class.hh>
Public Member Functions
PhysRegId ()
PhysRegId (RegClass _regClass, PhysRegIndex _regIdx, PhysRegIndex _flatIdx)
Scalar PhysRegId constructor.
PhysRegId (RegClass _regClass, PhysRegIndex _regIdx, ElemIndex elem_idx, PhysRegIndex flat_idx)
Vector PhysRegId constructor (w/ elemIndex).
bool isIntPhysReg () const
bool isFloatPhysReg () const
bool isCCPhysReg () const
true if it is a condition-code physical register.
bool isVectorPhysReg () const
true if it is a vector physical register.
bool isVectorPhysElem () const
true if it is a vector element physical register.
bool isVecPredPhysReg () const
bool isMiscPhysReg () const
true if it is a condition-code physical register.
bool isFixedMapping () const
Returns true if this register is always associated to the same architectural register.
const PhysRegIndex & flatIndex () const
Flat index accessor.
int getNumPinnedWrites () const
void setNumPinnedWrites (int numWrites)
void decrNumPinnedWrites ()
void incrNumPinnedWrites ()
bool isPinned () const
int getNumPinnedWritesToComplete () const
void setNumPinnedWritesToComplete (int numWrites)
void decrNumPinnedWritesToComplete ()
void incrNumPinnedWritesToComplete ()
bool operator< (const PhysRegId &that) const
Explicit forward methods, to prevent comparisons of PhysRegId with RegIds.
bool operator== (const PhysRegId &that) const
bool operator!= (const PhysRegId &that) const
Static Public Member Functions
static PhysRegId elemId (PhysRegId *vid, ElemIndex elem)
Private Attributes
PhysRegIndex flatIdx
int numPinnedWritesToComplete
bool pinned
Private Attributes inherited from RegId
RegClass regClass
RegIndex regIdx
ElemIndex elemIdx
int numPinnedWrites
Additional Inherited Members
Private Member Functions inherited from RegId
RegId ()
RegId (RegClass reg_class, RegIndex reg_idx)
RegId (RegClass reg_class, RegIndex reg_idx, ElemIndex elem_idx)
bool operator== (const RegId &that) const
bool operator!= (const RegId &that) const
bool operator< (const RegId &that) const
Order operator.
bool isRenameable () const
Return true if this register can be renamed.
bool isZeroReg () const
Check if this is the zero register.
bool isIntReg () const
bool isFloatReg () const
bool isVecReg () const
true if it is a condition-code physical register.
bool isVecElem () const
true if it is a condition-code physical register.
bool isVecPredReg () const
true if it is a predicate physical register.
bool isCCReg () const
true if it is a condition-code physical register.
bool isMiscReg () const
true if it is a condition-code physical register.
bool isRenameable ()
Return true if this register can be renamed.
const RegIndex & elemIndex () const
Elem accessor.
const RegClass & classValue () const
Class accessor.
const char * className () const
Return a const char* with the register class name.
int getNumPinnedWrites () const
void setNumPinnedWrites (int num_writes)
const RegIndex & index () const
Index accessors.
RegIndex & index ()
RegIndex flatIndex () const
Index flattening.
Static Private Attributes inherited from RegId
static const char * regClassStrings []
static constexpr size_t Scale = TheISA::NumVecElemPerVecReg
Detailed Description
Physical register ID.
Like a register ID but physical. The inheritance is private because the only relationship between this types is functional, and it is done to prevent code replication.
Definition at line 229 of file reg_class.hh.
Constructor & Destructor Documentation
PhysRegId() [1/3]
PhysRegId::PhysRegId () inline explicit
Definition at line 236 of file reg_class.hh.
PhysRegId() [2/3]
PhysRegId::PhysRegId (RegClass _regClass, PhysRegIndex _regIdx, PhysRegIndex _flatIdx) inline explicit
Scalar PhysRegId constructor.
Definition at line 241 of file reg_class.hh.
PhysRegId() [3/3]
PhysRegId::PhysRegId (RegClass _regClass, PhysRegIndex _regIdx, ElemIndex elem_idx, PhysRegIndex flat_idx) inline explicit
Vector PhysRegId constructor (w/ elemIndex).
Definition at line 248 of file reg_class.hh.
References RegId::className(), RegId::classValue(), RegId::elemIndex(), RegId::index(), and RegId::isZeroReg().
Member Function Documentation
decrNumPinnedWrites()
void PhysRegId::decrNumPinnedWrites () inline
Definition at line 333 of file reg_class.hh.
References RegId::numPinnedWrites.
Referenced by SimpleRenameMap::rename().
decrNumPinnedWritesToComplete()
void PhysRegId::decrNumPinnedWritesToComplete () inline
Definition at line 348 of file reg_class.hh.
Referenced by InstructionQueue< Impl >::wakeDependents().
elemId()
static PhysRegId PhysRegId::elemId (PhysRegId * vid, ElemIndex elem) inline static
Definition at line 313 of file reg_class.hh.
References RegId::index(), isVectorPhysReg(), and VecElemClass.
flatIndex()
const PhysRegIndex& PhysRegId::flatIndex () const inline
Flat index accessor.
Definition at line 311 of file reg_class.hh.
Referenced by InstructionQueue< Impl >::addToDependents(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::doSquash(), Scoreboard::getReg(), SimpleRenameMap::rename(), DefaultRename< Impl >::renameSrcRegs(), Scoreboard::setReg(), Scoreboard::unsetReg(), ElasticTrace::updateRegDep(), and InstructionQueue< Impl >::wakeDependents().
getNumPinnedWrites()
int PhysRegId::getNumPinnedWrites () const inline
Definition at line 319 of file reg_class.hh.
References RegId::numPinnedWrites.
Referenced by SimpleRenameMap::rename().
getNumPinnedWritesToComplete()
int PhysRegId::getNumPinnedWritesToComplete () const inline
Definition at line 338 of file reg_class.hh.
Referenced by InstructionQueue< Impl >::wakeDependents().
incrNumPinnedWrites()
void PhysRegId::incrNumPinnedWrites () inline
Definition at line 334 of file reg_class.hh.
References RegId::numPinnedWrites.
Referenced by BaseDynInst< Impl >::setSquashed().
incrNumPinnedWritesToComplete()
void PhysRegId::incrNumPinnedWritesToComplete () inline
Definition at line 349 of file reg_class.hh.
Referenced by BaseDynInst< Impl >::setSquashed().
isCCPhysReg()
bool PhysRegId::isCCPhysReg () const inline
true if it is a condition-code physical register.
Definition at line 287 of file reg_class.hh.
References RegId::isCCReg().
Referenced by PhysRegFile::readCCReg(), PhysRegFile::setCCReg(), and UnifiedRenameMap::setEntry().
isFixedMapping()
bool PhysRegId::isFixedMapping () const inline
Returns true if this register is always associated to the same architectural register.
Definition at line 305 of file reg_class.hh.
References RegId::isRenameable().
Referenced by InstructionQueue< Impl >::addToDependents(), InstructionQueue< Impl >::addToProducers(), InstructionQueue< Impl >::doSquash(), Scoreboard::getReg(), Scoreboard::setReg(), Scoreboard::unsetReg(), and InstructionQueue< Impl >::wakeDependents().
isFloatPhysReg()
bool PhysRegId::isFloatPhysReg () const inline
Returns
true if it is a floating-point physical register.
Definition at line 284 of file reg_class.hh.
References RegId::isFloatReg().
Referenced by PhysRegFile::readFloatReg(), UnifiedRenameMap::setEntry(), and PhysRegFile::setFloatReg().
isIntPhysReg()
bool PhysRegId::isIntPhysReg () const inline
Returns
true if it is an integer physical register.
Definition at line 281 of file reg_class.hh.
References RegId::isIntReg().
Referenced by PhysRegFile::readIntReg(), UnifiedRenameMap::setEntry(), and PhysRegFile::setIntReg().
isMiscPhysReg()
bool PhysRegId::isMiscPhysReg () const inline
true if it is a condition-code physical register.
Definition at line 299 of file reg_class.hh.
References RegId::isMiscReg().
isPinned()
bool PhysRegId::isPinned () const inline
Definition at line 336 of file reg_class.hh.
Referenced by BaseDynInst< Impl >::renameDestReg(), BaseDynInst< Impl >::setSquashed(), and InstructionQueue< Impl >::wakeDependents().
isVecPredPhysReg()
bool PhysRegId::isVecPredPhysReg () const inline
Returns
true if it is a vector predicate physical register.
Definition at line 296 of file reg_class.hh.
References RegId::isVecPredReg().
Referenced by PhysRegFile::readVecPredReg(), UnifiedRenameMap::setEntry(), and PhysRegFile::setVecPredReg().
isVectorPhysElem()
bool PhysRegId::isVectorPhysElem () const inline
true if it is a vector element physical register.
Definition at line 293 of file reg_class.hh.
References RegId::isVecElem().
Referenced by PhysRegFile::getTrueId(), PhysRegFile::readVecElem(), UnifiedRenameMap::setEntry(), and PhysRegFile::setVecElem().
isVectorPhysReg()
bool PhysRegId::isVectorPhysReg () const inline
true if it is a vector physical register.
Definition at line 290 of file reg_class.hh.
References RegId::isVecReg().
Referenced by elemId(), PhysRegFile::readVecReg(), UnifiedRenameMap::setEntry(), PhysRegFile::setVecLane(), and PhysRegFile::setVecReg().
operator!=()
bool PhysRegId::operator!= (const PhysRegId & that) const inline
Definition at line 275 of file reg_class.hh.
References RegId::operator!=().
operator<()
bool PhysRegId::operator< (const PhysRegId & that) const inline
Explicit forward methods, to prevent comparisons of PhysRegId with RegIds.
Definition at line 267 of file reg_class.hh.
References RegId::operator<().
operator==()
bool PhysRegId::operator== (const PhysRegId & that) const inline
Definition at line 271 of file reg_class.hh.
References RegId::operator==().
setNumPinnedWrites()
void PhysRegId::setNumPinnedWrites (int numWrites) inline
Definition at line 321 of file reg_class.hh.
References RegId::numPinnedWrites.
Referenced by SimpleRenameMap::rename().
setNumPinnedWritesToComplete()
void PhysRegId::setNumPinnedWritesToComplete (int numWrites) inline
Definition at line 343 of file reg_class.hh.
Referenced by SimpleRenameMap::rename().
Member Data Documentation
flatIdx
PhysRegIndex PhysRegId::flatIdx private
Definition at line 231 of file reg_class.hh.
numPinnedWritesToComplete
int PhysRegId::numPinnedWritesToComplete private
Definition at line 232 of file reg_class.hh.
pinned
bool PhysRegId::pinned private
Definition at line 233 of file reg_class.hh.
The documentation for this class was generated from the following file:
cpu/reg_class.hh