gem5: tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL > Class Template Reference
tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL > Class Template Reference
#include <simple_target_socket.h>
Classes
class bw_process
class fw_process
Public Types
typedef TYPES::tlm_payload_type transaction_type
typedef TYPES::tlm_phase_type phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm::tlm_fw_transport_if< TYPES > fw_interface_type
typedef tlm::tlm_bw_transport_if< TYPES > bw_interface_type
typedef tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, POL > base_type
Public Types inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
typedef tlm_fw_transport_if< TYPES > fw_interface_type
typedef tlm_bw_transport_if< TYPES > bw_interface_type
typedef sc_core::sc_port< bw_interface_type, N, POL > port_type
typedef sc_core::sc_export< fw_interface_type > export_type
typedef tlm_base_initiator_socket_b< BUSWIDTH, fw_interface_type, bw_interface_type > base_initiator_socket_type
typedef tlm_base_target_socket_b< BUSWIDTH, fw_interface_type, bw_interface_type > base_type
Public Member Functions
simple_target_socket_b (const char *n=default_name())
tlm::tlm_bw_transport_if< TYPES > * operator-> ()
void register_nb_transport_fw (MODULE *mod, sync_enum_type(MODULE::*cb)(transaction_type &, phase_type &, sc_core::sc_time &))
void register_b_transport (MODULE *mod, void(MODULE::*cb)(transaction_type &, sc_core::sc_time &))
void register_transport_dbg (MODULE *mod, unsigned int(MODULE::*cb)(transaction_type &))
void register_get_direct_mem_ptr (MODULE *mod, bool(MODULE::*cb)(transaction_type &, tlm::tlm_dmi &))
Public Member Functions inherited from tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, POL >
tlm_target_socket ()
tlm_target_socket (const char *name)
virtual const char * kind () const
virtual std::type_index get_protocol_types () const
Public Member Functions inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
tlm_base_target_socket ()
tlm_base_target_socket (const char *name)
virtual void bind (base_initiator_socket_type &s)
virtual void bind (base_type &s)
virtual void bind (fw_interface_type &ifs)
void operator() (base_initiator_socket_type &s)
void operator() (base_type &s)
void operator() (fw_interface_type &s)
int size () const
bw_interface_type * operator-> ()
bw_interface_type * operator[] (int i)
virtual sc_core::sc_port_base & get_port_base ()
virtual sc_core::sc_port_base const & get_port_base () const
virtual sc_core::sc_export_base & get_export_base ()
virtual sc_core::sc_export_base const & get_export_base () const
virtual unsigned int get_bus_width () const
virtual tlm_socket_category get_socket_category () const
virtual sc_core::sc_port_b< tlm_bw_transport_if< TYPES > > & get_base_port ()
virtual sc_core::sc_port_b< tlm_bw_transport_if< TYPES > > const & get_base_port () const
virtual tlm_fw_transport_if< TYPES > & get_base_interface ()
virtual tlm_fw_transport_if< TYPES > const & get_base_interface () const
virtual sc_core::sc_export< tlm_fw_transport_if< TYPES > > & get_base_export ()
virtual sc_core::sc_export< tlm_fw_transport_if< TYPES > > const & get_base_export () const
Public Member Functions inherited from tlm::tlm_base_target_socket_b< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES > >
virtual ~tlm_base_target_socket_b ()
Public Member Functions inherited from sc_core::sc_export< tlm_fw_transport_if< TYPES > >
sc_export ()
sc_export (const char *n)
virtual ~sc_export ()
void operator() (tlm_fw_transport_if< TYPES > &i)
virtual void bind (tlm_fw_transport_if< TYPES > &i)
operator tlm_fw_transport_if< TYPES > & ()
operator const tlm_fw_transport_if< TYPES > & () const
tlm_fw_transport_if< TYPES > * operator-> ()
const tlm_fw_transport_if< TYPES > * operator-> () const
sc_interface * get_iterface () override
const sc_interface * get_interface () const override
Public Member Functions inherited from sc_core::sc_export_base
sc_export_base (const char *n)
~sc_export_base ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Static Public Member Functions
static const char * default_name ()
Protected Member Functions
void start_of_simulation ()
Protected Member Functions inherited from tlm::tlm_base_socket_if
virtual ~tlm_base_socket_if ()
Protected Member Functions inherited from sc_core::sc_export< tlm_fw_transport_if< TYPES > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from tlm_utils::simple_socket_base
void elaboration_check (const char *action) const
Protected Member Functions inherited from tlm_utils::convenience_socket_base
virtual ~convenience_socket_base ()
void display_warning (const char *msg) const
void display_error (const char *msg) const
Private Member Functions
sync_enum_type bw_nb_transport (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void bw_invalidate_direct_mem_ptr (sc_dt::uint64 s, sc_dt::uint64 e)
const sc_core::sc_object * get_socket () const
Private Attributes
fw_process m_fw_process
bw_process m_bw_process
std::map< transaction_type *, sc_core::sc_event * > m_pending_trans
sc_core::sc_event m_end_request
transaction_type * m_current_transaction
Friends
class fw_process
class bw_process
Additional Inherited Members
Protected Attributes inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
port_type m_port
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >
Definition at line 40 of file simple_target_socket.h.
Member Typedef Documentation
base_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm::tlm_target_socket<BUSWIDTH, TYPES, 1, POL> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::base_type
Definition at line 52 of file simple_target_socket.h.
bw_interface_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm::tlm_bw_transport_if<TYPES> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_interface_type
Definition at line 51 of file simple_target_socket.h.
fw_interface_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm::tlm_fw_transport_if<TYPES> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_interface_type
Definition at line 50 of file simple_target_socket.h.
phase_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef TYPES::tlm_phase_type tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::phase_type
Definition at line 48 of file simple_target_socket.h.
sync_enum_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm::tlm_sync_enum tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::sync_enum_type
Definition at line 49 of file simple_target_socket.h.
transaction_type
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef TYPES::tlm_payload_type tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::transaction_type
Definition at line 47 of file simple_target_socket.h.
Constructor & Destructor Documentation
simple_target_socket_b()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::simple_target_socket_b (const char * n = default_name()) inline explicit
Definition at line 61 of file simple_target_socket.h.
Member Function Documentation
bw_invalidate_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_invalidate_direct_mem_ptr (sc_dt::uint64 s, sc_dt::uint64 e) inline private
Definition at line 124 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::invalidate_direct_mem_ptr(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::invalidate_direct_mem_ptr().
bw_nb_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sync_enum_type tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_nb_transport (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline private
Definition at line 117 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb2b_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw().
default_name()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> static const char* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::default_name () inline static
Definition at line 56 of file simple_target_socket.h.
get_socket()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> const sc_core::sc_object* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::get_socket () const inline private virtual
Implements tlm_utils::convenience_socket_base.
Definition at line 576 of file simple_target_socket.h.
operator->()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm::tlm_bw_transport_if<TYPES>* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::operator-> () inline
Definition at line 70 of file simple_target_socket.h.
register_b_transport()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_b_transport (MODULE * mod, void(MODULE::*)(transaction_type &, sc_core::sc_time &) cb) inline
Definition at line 83 of file simple_target_socket.h.
Referenced by ExplicitLTTarget::ExplicitLTTarget().
register_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_get_direct_mem_ptr (MODULE * mod, bool(MODULE::*)(transaction_type &, tlm::tlm_dmi &) cb) inline
Definition at line 99 of file simple_target_socket.h.
Referenced by adapt_ext2gp< BUSWIDTH >::adapt_ext2gp(), adapt_gp2ext< BUSWIDTH >::adapt_gp2ext(), and SimpleLTTarget_ext::SimpleLTTarget_ext().
register_nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_nb_transport_fw (MODULE * mod, sync_enum_type(MODULE::*)(transaction_type &, phase_type &, sc_core::sc_time &) cb) inline
Definition at line 74 of file simple_target_socket.h.
Referenced by adapt_ext2gp< BUSWIDTH >::adapt_ext2gp(), adapt_gp2ext< BUSWIDTH >::adapt_gp2ext(), ExplicitATTarget::ExplicitATTarget(), SimpleATTarget1::SimpleATTarget1(), SimpleATTarget2::SimpleATTarget2(), and SimpleLTTarget_ext::SimpleLTTarget_ext().
register_transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::register_transport_dbg (MODULE * mod, unsigned int(MODULE::*)(transaction_type &) cb) inline
Definition at line 91 of file simple_target_socket.h.
Referenced by adapt_ext2gp< BUSWIDTH >::adapt_ext2gp(), adapt_gp2ext< BUSWIDTH >::adapt_gp2ext(), ExplicitATTarget::ExplicitATTarget(), ExplicitLTTarget::ExplicitLTTarget(), and SimpleLTTarget_ext::SimpleLTTarget_ext().
start_of_simulation()
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::start_of_simulation () inline protected virtual
Implements sc_core::sc_export_base.
Definition at line 108 of file simple_target_socket.h.
Friends And Related Function Documentation
bw_process
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> friend class bw_process friend
Definition at line 45 of file simple_target_socket.h.
fw_process
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> friend class fw_process friend
Definition at line 44 of file simple_target_socket.h.
Member Data Documentation
m_bw_process
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bw_process tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_bw_process private
Definition at line 580 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::operator->(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::operator->().
m_current_transaction
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> transaction_type* tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_current_transaction private
Definition at line 583 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw().
m_end_request
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> sc_core::sc_event tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_end_request private
Definition at line 582 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw().
m_fw_process
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> fw_process tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_fw_process private
Definition at line 579 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_b_transport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_get_direct_mem_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_nb_transport_fw(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::register_transport_dbg(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::simple_target_socket_b(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::simple_target_socket_tagged_b(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::start_of_simulation().
m_pending_trans
template<typename MODULE, unsigned int BUSWIDTH, typename TYPES, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::map<transaction_type *, sc_core::sc_event *> tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::m_pending_trans private
Definition at line 581 of file simple_target_socket.h.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b2nb_thread(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::b_transport(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::bw_process::nb_transport_bw().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/simple_target_socket.h