gem5: Gicv3Distributor Class Reference
Gicv3Distributor Class Reference
#include <gic_v3_distributor.hh>
Public Member Functions
Gicv3Distributor (Gicv3 *gic, uint32_t it_lines)
void deassertSPI (uint32_t int_id)
void clearIrqCpuInterface (uint32_t int_id)
void init ()
uint64_t read (Addr addr, size_t size, bool is_secure_access)
void sendInt (uint32_t int_id)
void write (Addr addr, uint64_t data, size_t size, bool is_secure_access)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Static Public Attributes
static const uint32_t ADDR_RANGE_SIZE = 0x10000
static const uint32_t IDBITS = 0xf
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Types
enum {
GICD_CTLR = 0x0000, GICD_TYPER = 0x0004, GICD_IIDR = 0x0008, GICD_STATUSR = 0x0010,
GICD_SETSPI_NSR = 0x0040, GICD_CLRSPI_NSR = 0x0048, GICD_SETSPI_SR = 0x0050, GICD_CLRSPI_SR = 0x0058,
GICD_SGIR = 0x0f00, GICD_PIDR0 = 0xffe0, GICD_PIDR1 = 0xffe4, GICD_PIDR2 = 0xffe8,
GICD_PIDR3 = 0xffec, GICD_PIDR4 = 0xffd0, GICD_PIDR5 = 0xffd4, GICD_PIDR6 = 0xffd8,
GICD_PIDR7 = 0xffdc
}
Protected Member Functions
BitUnion64 (IROUTER) Bitfield< 63
EndBitUnion (IROUTER) static const uint32_t GICD_CTLR_ENABLEGRP0
void activateIRQ (uint32_t int_id)
void deactivateIRQ (uint32_t int_id)
void fullUpdate ()
Gicv3::GroupId getIntGroup (int int_id) const
bool groupEnabled (Gicv3::GroupId group) const
Gicv3::IntStatus intStatus (uint32_t int_id) const
bool isNotSPI (uint32_t int_id) const
bool nsAccessToSecInt (uint32_t int_id, bool is_secure_access) const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void update ()
Gicv3CPUInterface * route (uint32_t int_id)
Protected Attributes
Gicv3 * gic
const uint32_t itLines
res0_1
Bitfield< 39, 32 > Aff3
Bitfield< 31 > IRM
Bitfield< 30, 24 > res0_2
Bitfield< 23, 16 > Aff2
Bitfield< 15, 8 > Aff1
Bitfield< 7, 0 > Aff0
bool ARE
bool DS
bool EnableGrp1S
bool EnableGrp1NS
bool EnableGrp0
std::vector< uint8_t > irqGroup
std::vector< bool > irqEnabled
std::vector< bool > irqPending
std::vector< bool > irqActive
std::vector< uint8_t > irqPriority
std::vector< Gicv3::IntTriggerType > irqConfig
std::vector< uint8_t > irqGrpmod
std::vector< uint8_t > irqNsacr
std::vector< IROUTER > irqAffinityRouting
uint32_t gicdTyper
uint32_t gicdPidr0
uint32_t gicdPidr1
uint32_t gicdPidr2
uint32_t gicdPidr3
uint32_t gicdPidr4
Static Protected Attributes
static const AddrRange GICD_IGROUPR
static const AddrRange GICD_ISENABLER
static const AddrRange GICD_ICENABLER
static const AddrRange GICD_ISPENDR
static const AddrRange GICD_ICPENDR
static const AddrRange GICD_ISACTIVER
static const AddrRange GICD_ICACTIVER
static const AddrRange GICD_IPRIORITYR
static const AddrRange GICD_ITARGETSR
static const AddrRange GICD_ICFGR
static const AddrRange GICD_IGRPMODR
static const AddrRange GICD_NSACR
static const AddrRange GICD_CPENDSGIR
static const AddrRange GICD_SPENDSGIR
static const AddrRange GICD_IROUTER
static const uint32_t GICD_CTLR_ENABLEGRP1 = 1 << 0
static const uint32_t GICD_CTLR_ENABLEGRP1NS = 1 << 1
static const uint32_t GICD_CTLR_ENABLEGRP1A = 1 << 1
static const uint32_t GICD_CTLR_ENABLEGRP1S = 1 << 2
static const uint32_t GICD_CTLR_DS = 1 << 6
Friends
class Gicv3Redistributor
class Gicv3CPUInterface
class Gicv3Its
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Definition at line 50 of file gic_v3_distributor.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GICD_CTLR
GICD_TYPER
GICD_IIDR
GICD_STATUSR
GICD_SETSPI_NSR
GICD_CLRSPI_NSR
GICD_SETSPI_SR
GICD_CLRSPI_SR
GICD_SGIR
GICD_PIDR0
GICD_PIDR1
GICD_PIDR2
GICD_PIDR3
GICD_PIDR4
GICD_PIDR5
GICD_PIDR6
GICD_PIDR7
Definition at line 63 of file gic_v3_distributor.hh.
Constructor & Destructor Documentation
Gicv3Distributor()
Gicv3Distributor::Gicv3Distributor (Gicv3 * gic, uint32_t it_lines)
Definition at line 69 of file gic_v3_distributor.cc.
References divCeil(), DS, BaseGic::getSystem(), gicdTyper, ArmSystem::haveSecurity(), IDBITS, Gicv3::INTID_SECURE, itLines, and panic_if.
Referenced by nsAccessToSecInt().
Member Function Documentation
activateIRQ()
void Gicv3Distributor::activateIRQ (uint32_t int_id) protected
Definition at line 1143 of file gic_v3_distributor.cc.
References irqActive, and irqPending.
Referenced by Gicv3CPUInterface::generateSGI().
BitUnion64()
Gicv3Distributor::BitUnion64 (IROUTER) protected
clearIrqCpuInterface()
void Gicv3Distributor::clearIrqCpuInterface (uint32_t int_id)
Definition at line 1054 of file gic_v3_distributor.cc.
References route().
Referenced by deassertSPI(), nsAccessToSecInt(), and write().
deactivateIRQ()
void Gicv3Distributor::deactivateIRQ (uint32_t int_id) protected
Definition at line 1150 of file gic_v3_distributor.cc.
References irqActive.
Referenced by Gicv3CPUInterface::deactivateIRQ().
deassertSPI()
void Gicv3Distributor::deassertSPI (uint32_t int_id)
Definition at line 1006 of file gic_v3_distributor.cc.
References clearIrqCpuInterface(), irqPending, itLines, panic_if, Gicv3::PPI_MAX, Gicv3::SGI_MAX, and update().
Referenced by Gicv3::clearInt(), nsAccessToSecInt(), and write().
EndBitUnion()
Gicv3Distributor::EndBitUnion (IROUTER) const protected
fullUpdate()
void Gicv3Distributor::fullUpdate () protected
getIntGroup()
Gicv3::GroupId Gicv3Distributor::getIntGroup (int int_id) const protected
Definition at line 1116 of file gic_v3_distributor.cc.
References DS, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, irqGroup, irqGrpmod, itLines, panic_if, Gicv3::PPI_MAX, and Gicv3::SGI_MAX.
Referenced by nsAccessToSecInt(), read(), route(), Gicv3CPUInterface::setMiscReg(), update(), Gicv3CPUInterface::virtualDeactivateIRQ(), and write().
groupEnabled()
bool Gicv3Distributor::groupEnabled (Gicv3::GroupId group) const inline protected
Definition at line 183 of file gic_v3_distributor.hh.
References EnableGrp0, EnableGrp1NS, EnableGrp1S, Gicv3::G0S, Gicv3::G1NS, Gicv3::G1S, intStatus(), and panic.
Referenced by Gicv3Redistributor::canBeSelectedFor1toNInterrupt(), Gicv3Redistributor::update(), and update().
init()
void Gicv3Distributor::init ()
Definition at line 133 of file gic_v3_distributor.cc.
Referenced by Gicv3::init(), and nsAccessToSecInt().
intStatus()
Gicv3::IntStatus Gicv3Distributor::intStatus (uint32_t int_id) const protected
Definition at line 1097 of file gic_v3_distributor.cc.
References Gicv3::INT_ACTIVE, Gicv3::INT_ACTIVE_PENDING, Gicv3::INT_INACTIVE, Gicv3::INT_PENDING, irqActive, irqPending, itLines, panic_if, Gicv3::PPI_MAX, and Gicv3::SGI_MAX.
Referenced by groupEnabled().
isNotSPI()
bool Gicv3Distributor::isNotSPI (uint32_t int_id) const inline protected
Definition at line 218 of file gic_v3_distributor.hh.
References Gicv3::PPI_MAX, and Gicv3::SGI_MAX.
Referenced by read(), and write().
nsAccessToSecInt()
bool Gicv3Distributor::nsAccessToSecInt (uint32_t int_id, bool is_secure_access) const inline protected
Definition at line 227 of file gic_v3_distributor.hh.
References addr, clearIrqCpuInterface(), data, deassertSPI(), DS, Gicv3::G1NS, getIntGroup(), Gicv3Distributor(), init(), read(), route(), sendInt(), serialize(), Gicv3Its::size, unserialize(), update(), and write().
Referenced by read(), and write().
read()
uint64_t Gicv3Distributor::read (Addr addr, size_t size, bool is_secure_access)
Definition at line 138 of file gic_v3_distributor.cc.
References ARE, AddrRange::contains(), DS, EnableGrp0, EnableGrp1NS, EnableGrp1S, Gicv3::G1NS, getIntGroup(), GICD_CPENDSGIR, GICD_CTLR, GICD_ICACTIVER, GICD_ICENABLER, GICD_ICFGR, GICD_ICPENDR, GICD_IGROUPR, GICD_IGRPMODR, GICD_IIDR, GICD_IPRIORITYR, GICD_IROUTER, GICD_ISACTIVER, GICD_ISENABLER, GICD_ISPENDR, GICD_ITARGETSR, GICD_NSACR, GICD_PIDR0, GICD_PIDR1, GICD_PIDR2, GICD_PIDR3, GICD_PIDR4, GICD_PIDR5, GICD_PIDR6, GICD_PIDR7, GICD_SPENDSGIR, GICD_STATUSR, GICD_TYPER, gicdPidr0, gicdPidr1, gicdPidr2, gicdPidr3, gicdPidr4, gicdTyper, ArmISA::i, Gicv3::INT_EDGE_TRIGGERED, irqActive, irqAffinityRouting, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, isNotSPI(), itLines, nsAccessToSecInt(), panic, AddrRange::start(), X86ISA::val, and warn.
Referenced by nsAccessToSecInt(), and Gicv3::read().
route()
Gicv3CPUInterface * Gicv3Distributor::route (uint32_t int_id) protected
Definition at line 1017 of file gic_v3_distributor.cc.
References Gicv3Redistributor::canBeSelectedFor1toNInterrupt(), Gicv3Redistributor::getCPUInterface(), getIntGroup(), Gicv3::getRedistributor(), Gicv3::getRedistributorByAffinity(), BaseGic::getSystem(), gic, ArmISA::i, irqAffinityRouting, and System::numContexts().
Referenced by clearIrqCpuInterface(), nsAccessToSecInt(), and update().
sendInt()
void Gicv3Distributor::sendInt (uint32_t int_id)
Definition at line 995 of file gic_v3_distributor.cc.
References DPRINTF, irqPending, itLines, panic_if, Gicv3::PPI_MAX, Gicv3::SGI_MAX, and update().
Referenced by nsAccessToSecInt(), Gicv3::sendInt(), and write().
serialize()
void Gicv3Distributor::serialize (CheckpointOut & cp) const override protected virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1156 of file gic_v3_distributor.cc.
References ARE, DS, EnableGrp0, EnableGrp1NS, EnableGrp1S, irqActive, irqAffinityRouting, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, SERIALIZE_CONTAINER, and SERIALIZE_SCALAR.
Referenced by nsAccessToSecInt().
unserialize()
void Gicv3Distributor::unserialize (CheckpointIn & cp) override protected virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1175 of file gic_v3_distributor.cc.
References ARE, DS, EnableGrp0, EnableGrp1NS, EnableGrp1S, irqActive, irqAffinityRouting, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
Referenced by nsAccessToSecInt().
update()
void Gicv3Distributor::update () protected
Definition at line 1062 of file gic_v3_distributor.cc.
References getIntGroup(), Gicv3::getRedistributor(), BaseGic::getSystem(), gic, Gicv3CPUInterface::hppi_t::group, groupEnabled(), Gicv3CPUInterface::hppi, ArmISA::i, Gicv3CPUInterface::hppi_t::intid, irqActive, irqEnabled, irqPending, irqPriority, itLines, System::numContexts(), Gicv3::PPI_MAX, Gicv3CPUInterface::hppi_t::prio, route(), Gicv3::SGI_MAX, and Gicv3Redistributor::update().
Referenced by deassertSPI(), nsAccessToSecInt(), sendInt(), Gicv3Redistributor::updateDistributor(), Gicv3CPUInterface::updateDistributor(), and write().
write()
void Gicv3Distributor::write (Addr addr, uint64_t data, size_t size, bool is_secure_access)
Definition at line 507 of file gic_v3_distributor.cc.
References bits(), clearIrqCpuInterface(), AddrRange::contains(), data, deassertSPI(), Trace::disable(), DPRINTF, DS, X86ISA::enable, EnableGrp0, EnableGrp1NS, EnableGrp1S, Gicv3::G1NS, getIntGroup(), GICD_CLRSPI_NSR, GICD_CLRSPI_SR, GICD_CTLR, GICD_CTLR_DS, GICD_CTLR_ENABLEGRP1A, GICD_CTLR_ENABLEGRP1NS, GICD_CTLR_ENABLEGRP1S, GICD_ICACTIVER, GICD_ICENABLER, GICD_ICFGR, GICD_ICPENDR, GICD_IGROUPR, GICD_IGRPMODR, GICD_IPRIORITYR, GICD_IROUTER, GICD_ISACTIVER, GICD_ISENABLER, GICD_ISPENDR, GICD_ITARGETSR, GICD_NSACR, GICD_SETSPI_NSR, GICD_SETSPI_SR, GICD_SGIR, ArmISA::i, Gicv3::INT_EDGE_TRIGGERED, Gicv3::INT_LEVEL_SENSITIVE, irqActive, irqAffinityRouting, irqConfig, irqEnabled, irqGroup, irqGrpmod, irqNsacr, irqPending, irqPriority, isNotSPI(), itLines, nsAccessToSecInt(), panic, sendInt(), AddrRange::start(), update(), and warn.
Referenced by nsAccessToSecInt(), and Gicv3::write().
Friends And Related Function Documentation
Gicv3CPUInterface
friend class Gicv3CPUInterface friend
Definition at line 55 of file gic_v3_distributor.hh.
Gicv3Its
friend class Gicv3Its friend
Definition at line 56 of file gic_v3_distributor.hh.
Gicv3Redistributor
friend class Gicv3Redistributor friend
Definition at line 54 of file gic_v3_distributor.hh.
Member Data Documentation
ADDR_RANGE_SIZE
const uint32_t Gicv3Distributor::ADDR_RANGE_SIZE = 0x10000 static
Definition at line 172 of file gic_v3_distributor.hh.
Referenced by Gicv3::init().
Aff0
Bitfield<7, 0> Gicv3Distributor::Aff0 protected
Definition at line 138 of file gic_v3_distributor.hh.
Aff1
Bitfield<15, 8> Gicv3Distributor::Aff1 protected
Definition at line 137 of file gic_v3_distributor.hh.
Aff2
Bitfield<23, 16> Gicv3Distributor::Aff2 protected
Definition at line 136 of file gic_v3_distributor.hh.
Aff3
Bitfield<39, 32> Gicv3Distributor::Aff3 protected
Definition at line 133 of file gic_v3_distributor.hh.
ARE
bool Gicv3Distributor::ARE protected
Definition at line 148 of file gic_v3_distributor.hh.
Referenced by read(), serialize(), and unserialize().
DS
bool Gicv3Distributor::DS protected
Definition at line 149 of file gic_v3_distributor.hh.
Referenced by Gicv3CPUInterface::getHPPIR0(), Gicv3CPUInterface::getHPPIR1(), getIntGroup(), Gicv3Redistributor::getIntGroup(), Gicv3Distributor(), Gicv3CPUInterface::intSignalType(), nsAccessToSecInt(), Gicv3Redistributor::read(), read(), Gicv3Redistributor::sendSGI(), serialize(), Gicv3CPUInterface::setMiscReg(), unserialize(), Gicv3Redistributor::write(), and write().
EnableGrp0
bool Gicv3Distributor::EnableGrp0 protected
Definition at line 152 of file gic_v3_distributor.hh.
Referenced by groupEnabled(), Gicv3CPUInterface::groupEnabled(), read(), serialize(), unserialize(), and write().
EnableGrp1NS
bool Gicv3Distributor::EnableGrp1NS protected
Definition at line 151 of file gic_v3_distributor.hh.
Referenced by groupEnabled(), Gicv3CPUInterface::groupEnabled(), read(), serialize(), unserialize(), and write().
EnableGrp1S
bool Gicv3Distributor::EnableGrp1S protected
Definition at line 150 of file gic_v3_distributor.hh.
Referenced by groupEnabled(), Gicv3CPUInterface::groupEnabled(), read(), serialize(), unserialize(), and write().
gic
Gicv3* Gicv3Distributor::gic protected
Definition at line 60 of file gic_v3_distributor.hh.
Referenced by route(), and update().
GICD_CPENDSGIR
const AddrRange Gicv3Distributor::GICD_CPENDSGIR static protected
Definition at line 125 of file gic_v3_distributor.hh.
Referenced by read().
GICD_CTLR_DS
const uint32_t Gicv3Distributor::GICD_CTLR_DS = 1 << 6 static protected
Definition at line 146 of file gic_v3_distributor.hh.
Referenced by write().
GICD_CTLR_ENABLEGRP1
const uint32_t Gicv3Distributor::GICD_CTLR_ENABLEGRP1 = 1 << 0 static protected
Definition at line 142 of file gic_v3_distributor.hh.
GICD_CTLR_ENABLEGRP1A
const uint32_t Gicv3Distributor::GICD_CTLR_ENABLEGRP1A = 1 << 1 static protected
Definition at line 144 of file gic_v3_distributor.hh.
Referenced by write().
GICD_CTLR_ENABLEGRP1NS
const uint32_t Gicv3Distributor::GICD_CTLR_ENABLEGRP1NS = 1 << 1 static protected
Definition at line 143 of file gic_v3_distributor.hh.
Referenced by write().
GICD_CTLR_ENABLEGRP1S
const uint32_t Gicv3Distributor::GICD_CTLR_ENABLEGRP1S = 1 << 2 static protected
Definition at line 145 of file gic_v3_distributor.hh.
Referenced by write().
GICD_ICACTIVER
const AddrRange Gicv3Distributor::GICD_ICACTIVER static protected
Definition at line 113 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ICENABLER
const AddrRange Gicv3Distributor::GICD_ICENABLER static protected
Definition at line 105 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ICFGR
const AddrRange Gicv3Distributor::GICD_ICFGR static protected
Definition at line 119 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ICPENDR
const AddrRange Gicv3Distributor::GICD_ICPENDR static protected
Definition at line 109 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_IGROUPR
const AddrRange Gicv3Distributor::GICD_IGROUPR static protected
Definition at line 101 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_IGRPMODR
const AddrRange Gicv3Distributor::GICD_IGRPMODR static protected
Definition at line 121 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_IPRIORITYR
const AddrRange Gicv3Distributor::GICD_IPRIORITYR static protected
Definition at line 115 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_IROUTER
const AddrRange Gicv3Distributor::GICD_IROUTER static protected
Definition at line 129 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ISACTIVER
const AddrRange Gicv3Distributor::GICD_ISACTIVER static protected
Definition at line 111 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ISENABLER
const AddrRange Gicv3Distributor::GICD_ISENABLER static protected
Definition at line 103 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ISPENDR
const AddrRange Gicv3Distributor::GICD_ISPENDR static protected
Definition at line 107 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_ITARGETSR
const AddrRange Gicv3Distributor::GICD_ITARGETSR static protected
Definition at line 117 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_NSACR
const AddrRange Gicv3Distributor::GICD_NSACR static protected
Definition at line 123 of file gic_v3_distributor.hh.
Referenced by read(), and write().
GICD_SPENDSGIR
const AddrRange Gicv3Distributor::GICD_SPENDSGIR static protected
Definition at line 127 of file gic_v3_distributor.hh.
Referenced by read().
gicdPidr0
uint32_t Gicv3Distributor::gicdPidr0 protected
Definition at line 164 of file gic_v3_distributor.hh.
Referenced by read().
gicdPidr1
uint32_t Gicv3Distributor::gicdPidr1 protected
Definition at line 165 of file gic_v3_distributor.hh.
Referenced by read().
gicdPidr2
uint32_t Gicv3Distributor::gicdPidr2 protected
Definition at line 166 of file gic_v3_distributor.hh.
Referenced by Gicv3Its::read(), and read().
gicdPidr3
uint32_t Gicv3Distributor::gicdPidr3 protected
Definition at line 167 of file gic_v3_distributor.hh.
Referenced by read().
gicdPidr4
uint32_t Gicv3Distributor::gicdPidr4 protected
Definition at line 168 of file gic_v3_distributor.hh.
Referenced by read().
gicdTyper
uint32_t Gicv3Distributor::gicdTyper protected
Definition at line 163 of file gic_v3_distributor.hh.
Referenced by Gicv3Distributor(), and read().
IDBITS
const uint32_t Gicv3Distributor::IDBITS = 0xf static
Definition at line 173 of file gic_v3_distributor.hh.
Referenced by Gicv3Distributor(), and Gicv3Its::lpiOutOfRange().
IRM
Bitfield<31> Gicv3Distributor::IRM protected
Definition at line 134 of file gic_v3_distributor.hh.
irqActive
std::vector<bool> Gicv3Distributor::irqActive protected
Definition at line 156 of file gic_v3_distributor.hh.
Referenced by activateIRQ(), deactivateIRQ(), intStatus(), read(), serialize(), unserialize(), update(), and write().
irqAffinityRouting
std::vector<IROUTER> Gicv3Distributor::irqAffinityRouting protected
Definition at line 161 of file gic_v3_distributor.hh.
Referenced by read(), route(), serialize(), unserialize(), and write().
irqConfig
std::vector<Gicv3::IntTriggerType> Gicv3Distributor::irqConfig protected
Definition at line 158 of file gic_v3_distributor.hh.
Referenced by read(), serialize(), unserialize(), and write().
irqEnabled
std::vector<bool> Gicv3Distributor::irqEnabled protected
Definition at line 154 of file gic_v3_distributor.hh.
Referenced by read(), serialize(), unserialize(), update(), and write().
irqGroup
std::vector<uint8_t> Gicv3Distributor::irqGroup protected
Definition at line 153 of file gic_v3_distributor.hh.
Referenced by getIntGroup(), read(), serialize(), unserialize(), and write().
irqGrpmod
std::vector<uint8_t> Gicv3Distributor::irqGrpmod protected
Definition at line 159 of file gic_v3_distributor.hh.
Referenced by getIntGroup(), read(), serialize(), unserialize(), and write().
irqNsacr
std::vector<uint8_t> Gicv3Distributor::irqNsacr protected
Definition at line 160 of file gic_v3_distributor.hh.
Referenced by read(), serialize(), unserialize(), and write().
irqPending
std::vector<bool> Gicv3Distributor::irqPending protected
Definition at line 155 of file gic_v3_distributor.hh.
Referenced by activateIRQ(), deassertSPI(), intStatus(), read(), sendInt(), serialize(), unserialize(), update(), and write().
irqPriority
std::vector<uint8_t> Gicv3Distributor::irqPriority protected
Definition at line 157 of file gic_v3_distributor.hh.
Referenced by read(), serialize(), unserialize(), update(), and write().
itLines
const uint32_t Gicv3Distributor::itLines protected
Definition at line 61 of file gic_v3_distributor.hh.
Referenced by deassertSPI(), getIntGroup(), Gicv3Distributor(), intStatus(), read(), sendInt(), update(), and write().
res0_1
Gicv3Distributor::res0_1 protected
Definition at line 132 of file gic_v3_distributor.hh.
res0_2
Bitfield<30, 24> Gicv3Distributor::res0_2 protected
Definition at line 135 of file gic_v3_distributor.hh.
The documentation for this class was generated from the following files:
dev/arm/gic_v3_distributor.hh
dev/arm/gic_v3_distributor.cc