gem5: sc_dt::sc_fxval_observer Class Reference
sc_dt::sc_fxval_observer Class Reference
#include <sc_fxval_observer.hh>
Public Member Functions
virtual void construct (const sc_fxval &)
virtual void destruct (const sc_fxval &)
virtual void read (const sc_fxval &)
virtual void write (const sc_fxval &)
Static Public Attributes
static sc_fxval_observer *(* default_observer)()
Protected Member Functions
sc_fxval_observer ()
virtual ~sc_fxval_observer ()
Detailed Description
Definition at line 111 of file sc_fxval_observer.hh.
Constructor & Destructor Documentation
sc_fxval_observer()
sc_dt::sc_fxval_observer::sc_fxval_observer () inline protected
Definition at line 114 of file sc_fxval_observer.hh.
~sc_fxval_observer()
virtual sc_dt::sc_fxval_observer::~sc_fxval_observer () inline protected virtual
Definition at line 115 of file sc_fxval_observer.hh.
References construct(), destruct(), read(), and write().
Member Function Documentation
construct()
void sc_dt::sc_fxval_observer::construct (const sc_fxval &) inline virtual
Definition at line 158 of file sc_fxval_observer.hh.
Referenced by sc_dt::sc_fxval_fast_observer::~sc_fxval_fast_observer(), and ~sc_fxval_observer().
destruct()
void sc_dt::sc_fxval_observer::destruct (const sc_fxval &) inline virtual
Definition at line 159 of file sc_fxval_observer.hh.
Referenced by sc_dt::sc_fxval_fast_observer::~sc_fxval_fast_observer(), and ~sc_fxval_observer().
read()
void sc_dt::sc_fxval_observer::read (const sc_fxval &) inline virtual
Definition at line 160 of file sc_fxval_observer.hh.
Referenced by sc_dt::sc_fxval_fast_observer::~sc_fxval_fast_observer(), and ~sc_fxval_observer().
write()
void sc_dt::sc_fxval_observer::write (const sc_fxval &) inline virtual
Definition at line 161 of file sc_fxval_observer.hh.
Referenced by sc_dt::sc_fxval_fast_observer::~sc_fxval_fast_observer(), and ~sc_fxval_observer().
Member Data Documentation
default_observer
sc_fxval_observer *(* sc_dt::sc_fxval_observer::default_observer)()=0 static
Definition at line 122 of file sc_fxval_observer.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxval_observer.hh
systemc/dt/fx/sc_fxval_observer.cc