gem5: Credit Class Reference
Credit Class Reference
#include <Credit.hh>
Public Member Functions
Credit ()
Credit (int vc, bool is_free_signal, Cycles curTime)
bool is_free_signal ()
Public Member Functions inherited from flit
flit ()
flit (int id, int vc, int vnet, RouteInfo route, int size, MsgPtr msg_ptr, Cycles curTime)
int get_outport ()
int get_size ()
Cycles get_enqueue_time ()
Cycles get_dequeue_time ()
int get_id ()
Cycles get_time ()
int get_vnet ()
int get_vc ()
RouteInfo get_route ()
MsgPtr & get_msg_ptr ()
flit_type get_type ()
std::pair< flit_stage, Cycles > get_stage ()
Cycles get_src_delay ()
void set_outport (int port)
void set_time (Cycles time)
void set_vc (int vc)
void set_route (RouteInfo route)
void set_src_delay (Cycles delay)
void set_dequeue_time (Cycles time)
void increment_hops ()
void print (std::ostream &out) const
bool is_stage (flit_stage stage, Cycles time)
void advance_stage (flit_stage t_stage, Cycles newTime)
bool functionalWrite (Packet *pkt)
Private Attributes
bool m_is_free_signal
Additional Inherited Members
Static Public Member Functions inherited from flit
static bool greater (flit *n1, flit *n2)
Protected Attributes inherited from flit
int m_id
int m_vnet
int m_vc
RouteInfo m_route
int m_size
Cycles m_enqueue_time
Cycles m_dequeue_time
Cycles m_time
flit_type m_type
MsgPtr m_msg_ptr
int m_outport
Cycles src_delay
std::pair< flit_stage, Cycles > m_stage
Detailed Description
Definition at line 48 of file Credit.hh.
Constructor & Destructor Documentation
Credit() [1/2]
Credit::Credit () inline
Definition at line 51 of file Credit.hh.
References is_free_signal().
Credit() [2/2]
Credit::Credit (int vc, bool is_free_signal, Cycles curTime)
Definition at line 40 of file Credit.cc.
References is_free_signal(), flit::m_id, m_is_free_signal, flit::m_time, and flit::m_vc.
Member Function Documentation
is_free_signal()
bool Credit::is_free_signal () inline
Definition at line 54 of file Credit.hh.
References m_is_free_signal.
Referenced by Credit(), OutputUnit::wakeup(), and NetworkInterface::wakeup().
Member Data Documentation
m_is_free_signal
bool Credit::m_is_free_signal private
Definition at line 57 of file Credit.hh.
Referenced by Credit(), and is_free_signal().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/Credit.hh
mem/ruby/network/garnet2.0/Credit.cc