gem5: GPUCoalescer Class Reference
GPUCoalescer Class Reference
#include <GPUCoalescer.hh>
Public Types
typedef RubyGPUCoalescerParams Params
Public Types inherited from RubyPort
typedef RubyPortParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
GPUCoalescer (const Params *)
~GPUCoalescer ()
void wakeup ()
void printProgress (std::ostream &out) const
void resetStats ()
Callback to reset stats.
void collateStats ()
void regStats ()
Callback to set stat parameters.
void writeCallback (Addr address, DataBlock &data)
void writeCallback (Addr address, MachineType mach, DataBlock &data)
void writeCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void writeCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
void readCallback (Addr address, DataBlock &data)
void readCallback (Addr address, MachineType mach, DataBlock &data)
void readCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
void readCallback (Addr address, MachineType mach, DataBlock &data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void atomicCallback (Addr address, MachineType mach, const DataBlock &data)
void recordCPReadCallBack (MachineID myMachID, MachineID senderMachID)
void recordCPWriteCallBack (MachineID myMachID, MachineID senderMachID)
virtual RequestStatus makeRequest (PacketPtr pkt)
int outstandingCount () const
bool isDeadlockEventScheduled () const
void descheduleDeadlockEvent ()
bool empty () const
void print (std::ostream &out) const
void checkCoherence (Addr address)
void markRemoved ()
void removeRequest (GPUCoalescerRequest *request)
void evictionCallback (Addr address)
void completeIssue ()
void insertKernel (int wavefront_id, PacketPtr pkt)
void recordRequestType (SequencerRequestType requestType)
Stats::Histogram & getOutstandReqHist ()
Stats::Histogram & getLatencyHist ()
Stats::Histogram & getTypeLatencyHist (uint32_t t)
Stats::Histogram & getMissLatencyHist ()
Stats::Histogram & getMissTypeLatencyHist (uint32_t t)
Stats::Histogram & getMissMachLatencyHist (uint32_t t) const
Stats::Histogram & getMissTypeMachLatencyHist (uint32_t r, uint32_t t) const
Stats::Histogram & getIssueToInitialDelayHist (uint32_t t) const
Stats::Histogram & getInitialToForwardDelayHist (const MachineType t) const
Stats::Histogram & getForwardRequestToFirstResponseHist (const MachineType t) const
Stats::Histogram & getFirstResponseToCompletionDelayHist (const MachineType t) const
Public Member Functions inherited from RubyPort
RubyPort (const Params *p)
virtual ~RubyPort ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void setController (AbstractController *_cntrl)
uint32_t getId ()
DrainState drain () override
Notify an object that it needs to drain its state.
bool isCPUSequencer ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
typedef std::unordered_map< Addr, std::vector< RequestDesc > > CoalescingTable
typedef std::unordered_map< Addr, GPUCoalescerRequest * > RequestTable
Protected Member Functions
bool tryCacheAccess (Addr addr, RubyRequestType type, Addr pc, RubyAccessMode access_mode, int size, DataBlock *&data_ptr)
virtual void issueRequest (PacketPtr pkt, RubyRequestType type)
void kernelCallback (int wavfront_id)
void hitCallback (GPUCoalescerRequest *request, MachineType mach, DataBlock &data, bool success, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
void recordMissLatency (GPUCoalescerRequest *request, MachineType mach, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool success, bool isRegion)
void completeHitCallback (std::vector< PacketPtr > &mylist, int len)
PacketPtr mapAddrToPkt (Addr address)
RequestStatus getRequestStatus (PacketPtr pkt, RubyRequestType request_type)
bool insertRequest (PacketPtr pkt, RubyRequestType request_type)
bool handleLlsc (Addr address, GPUCoalescerRequest *request)
Protected Member Functions inherited from RubyPort
void trySendRetries ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (Addr address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
EventFunctionWrapper issueEvent
int m_max_outstanding_requests
int m_deadlock_threshold
CacheMemory * m_dataCache_ptr
CacheMemory * m_instCache_ptr
CoalescingTable reqCoalescer
std::vector< Addr > newRequests
RequestTable m_writeRequestTable
RequestTable m_readRequestTable
int m_outstanding_count
bool m_deadlock_check_scheduled
std::unordered_map< int, PacketPtr > kernelEndList
std::vector< int > newKernelEnds
int m_store_waiting_on_load_cycles
int m_store_waiting_on_store_cycles
int m_load_waiting_on_store_cycles
int m_load_waiting_on_load_cycles
bool m_runningGarnetStandalone
EventFunctionWrapper deadlockCheckEvent
bool assumingRfOCoherence
Stats::Scalar GPU_TCPLdHits
Stats::Scalar GPU_TCPLdTransfers
Stats::Scalar GPU_TCCLdHits
Stats::Scalar GPU_LdMiss
Stats::Scalar GPU_TCPStHits
Stats::Scalar GPU_TCPStTransfers
Stats::Scalar GPU_TCCStHits
Stats::Scalar GPU_StMiss
Stats::Scalar CP_TCPLdHits
Stats::Scalar CP_TCPLdTransfers
Stats::Scalar CP_TCCLdHits
Stats::Scalar CP_LdMiss
Stats::Scalar CP_TCPStHits
Stats::Scalar CP_TCPStTransfers
Stats::Scalar CP_TCCStHits
Stats::Scalar CP_StMiss
Stats::Histogram m_outstandReqHist
Histogram for number of outstanding requests per cycle.
Stats::Histogram m_latencyHist
Histogram for holding latency profile of all requests.
std::vector< Stats::Histogram * > m_typeLatencyHist
Stats::Histogram m_missLatencyHist
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
std::vector< Stats::Histogram * > m_missTypeLatencyHist
std::vector< Stats::Histogram * > m_missMachLatencyHist
Histograms for profiling the latencies for requests that required external messages.
std::vector< std::vector< Stats::Histogram * > > m_missTypeMachLatencyHist
std::vector< Stats::Histogram * > m_IssueToInitialDelayHist
Histograms for recording the breakdown of miss latency.
std::vector< Stats::Histogram * > m_InitialToForwardDelayHist
std::vector< Stats::Histogram * > m_ForwardToFirstResponseDelayHist
std::vector< Stats::Histogram * > m_FirstResponseToCompletionDelayHist
Protected Attributes inherited from RubyPort
RubySystem * m_ruby_system
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
std::vector< MemSlavePort * > slave_ports
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
GPUCoalescer (const GPUCoalescer &obj)
GPUCoalescer & operator= (const GPUCoalescer &obj)
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 96 of file GPUCoalescer.hh.
Member Typedef Documentation
CoalescingTable
typedef std::unordered_map<Addr, std::vector<RequestDesc> > GPUCoalescer::CoalescingTable protected
Definition at line 273 of file GPUCoalescer.hh.
Params
typedef RubyGPUCoalescerParams GPUCoalescer::Params
Definition at line 99 of file GPUCoalescer.hh.
RequestTable
typedef std::unordered_map<Addr, GPUCoalescerRequest*> GPUCoalescer::RequestTable protected
Definition at line 277 of file GPUCoalescer.hh.
Constructor & Destructor Documentation
GPUCoalescer() [1/2]
GPUCoalescer::GPUCoalescer (const Params * p)
Definition at line 118 of file GPUCoalescer.cc.
References assumingRfOCoherence, completeIssue(), deadlockCheckEvent, m_dataCache_ptr, m_deadlock_threshold, m_instCache_ptr, m_load_waiting_on_load_cycles, m_load_waiting_on_store_cycles, m_max_outstanding_requests, m_outstanding_count, m_runningGarnetStandalone, m_store_waiting_on_load_cycles, m_store_waiting_on_store_cycles, MipsISA::p, EventBase::Progress_Event_Pri, and wakeup().
~GPUCoalescer()
GPUCoalescer::~GPUCoalescer ()
Definition at line 150 of file GPUCoalescer.cc.
GPUCoalescer() [2/2]
GPUCoalescer::GPUCoalescer (const GPUCoalescer & obj) private
Member Function Documentation
atomicCallback()
void GPUCoalescer::atomicCallback (Addr address, MachineType mach, const DataBlock & data)
Definition at line 1052 of file GPUCoalescer.cc.
References completeHitCallback(), DPRINTF, Packet::getAddr(), DataBlock::getData(), getOffset(), Packet::getPtr(), Packet::getSize(), ArmISA::i, ArmISA::len, RubyPort::m_usingRubyTester, m_writeRequestTable, makeLineAddress(), markRemoved(), SubBlock::mergeFrom(), Packet::SenderState::predecessor, recordMissLatency(), reqCoalescer, safe_cast(), Packet::senderState, Packet::setData(), and RubyTester::SenderState::subBlock.
checkCoherence()
void GPUCoalescer::checkCoherence (Addr address)
Definition at line 985 of file GPUCoalescer.cc.
collateStats()
void GPUCoalescer::collateStats ()
completeHitCallback()
void GPUCoalescer::completeHitCallback (std::vector< PacketPtr > & mylist, int len) protected
Definition at line 1153 of file GPUCoalescer.cc.
References ArmISA::i, ArmISA::len, RubyPort::SenderState::port, Packet::SenderState::predecessor, safe_cast(), ArmISA::ss, RubyPort::testDrainComplete(), and RubyPort::trySendRetries().
Referenced by atomicCallback(), and hitCallback().
completeIssue()
void GPUCoalescer::completeIssue ()
Definition at line 997 of file GPUCoalescer.cc.
References DPRINTF, ArmISA::i, insertRequest(), issueRequest(), kernelCallback(), ArmISA::len, newKernelEnds, newRequests, panic, RequestDesc::pkt, RequestDesc::primaryType, Packet::req, reqCoalescer, and RequestDesc::secondaryType.
Referenced by GPUCoalescer(), VIPERCoalescer::invCallback(), VIPERCoalescer::makeRequest(), and VIPERCoalescer::wbCallback().
descheduleDeadlockEvent()
void GPUCoalescer::descheduleDeadlockEvent () inline virtual
Implements RubyPort.
Definition at line 173 of file GPUCoalescer.hh.
References GPUCoalescerRequest::pkt.
empty()
bool GPUCoalescer::empty () const
Definition at line 679 of file GPUCoalescer.cc.
References m_readRequestTable, and m_writeRequestTable.
evictionCallback()
void GPUCoalescer::evictionCallback (Addr address)
Definition at line 1036 of file GPUCoalescer.cc.
References RubyPort::ruby_eviction_callback().
getFirstResponseToCompletionDelayHist()
Stats::Histogram& GPUCoalescer::getFirstResponseToCompletionDelayHist (const MachineType t) const inline
Definition at line 221 of file GPUCoalescer.hh.
References addr, data, ArmISA::len, MipsISA::pc, ArmISA::t, and type.
getForwardRequestToFirstResponseHist()
Stats::Histogram& GPUCoalescer::getForwardRequestToFirstResponseHist (const MachineType t) const inline
Definition at line 217 of file GPUCoalescer.hh.
References ArmISA::t.
getInitialToForwardDelayHist()
Stats::Histogram& GPUCoalescer::getInitialToForwardDelayHist (const MachineType t) const inline
Definition at line 213 of file GPUCoalescer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getIssueToInitialDelayHist()
Stats::Histogram& GPUCoalescer::getIssueToInitialDelayHist (uint32_t t) const inline
Definition at line 209 of file GPUCoalescer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getLatencyHist()
Stats::Histogram& GPUCoalescer::getLatencyHist () inline
Definition at line 193 of file GPUCoalescer.hh.
Referenced by Profiler::collateStats().
getMissLatencyHist()
Stats::Histogram& GPUCoalescer::getMissLatencyHist () inline
Definition at line 197 of file GPUCoalescer.hh.
Referenced by Profiler::collateStats().
getMissMachLatencyHist()
Stats::Histogram& GPUCoalescer::getMissMachLatencyHist (uint32_t t) const inline
Definition at line 202 of file GPUCoalescer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getMissTypeLatencyHist()
Stats::Histogram& GPUCoalescer::getMissTypeLatencyHist (uint32_t t) inline
Definition at line 199 of file GPUCoalescer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
getMissTypeMachLatencyHist()
Stats::Histogram& GPUCoalescer::getMissTypeMachLatencyHist (uint32_t r, uint32_t t) const inline
Definition at line 206 of file GPUCoalescer.hh.
References MipsISA::r, and ArmISA::t.
Referenced by Profiler::collateStats().
getOutstandReqHist()
Stats::Histogram& GPUCoalescer::getOutstandReqHist () inline
Definition at line 191 of file GPUCoalescer.hh.
Referenced by Profiler::collateStats().
getRequestStatus()
RequestStatus GPUCoalescer::getRequestStatus (PacketPtr pkt, RubyRequestType request_type) protected
Definition at line 235 of file GPUCoalescer.cc.
References MessageBuffer::areNSlotsAvailable(), Clocked::clockEdge(), Packet::getAddr(), AbstractController::isBlocked(), RubyPort::m_controller, m_load_waiting_on_load_cycles, m_load_waiting_on_store_cycles, RubyPort::m_mandatory_q_ptr, m_readRequestTable, m_store_waiting_on_load_cycles, m_store_waiting_on_store_cycles, m_writeRequestTable, and makeLineAddress().
Referenced by insertRequest(), and makeRequest().
getTypeLatencyHist()
Stats::Histogram& GPUCoalescer::getTypeLatencyHist (uint32_t t) inline
Definition at line 194 of file GPUCoalescer.hh.
References ArmISA::t.
Referenced by Profiler::collateStats().
handleLlsc()
bool GPUCoalescer::handleLlsc (Addr address, GPUCoalescerRequest * request) protected
Definition at line 412 of file GPUCoalescer.cc.
References CacheMemory::clearLocked(), CacheMemory::isLocked(), CacheMemory::isTagPresent(), m_dataCache_ptr, GPUCoalescerRequest::m_type, RubyPort::m_version, GPUCoalescerRequest::pkt, Packet::req, and CacheMemory::setLocked().
Referenced by writeCallback().
hitCallback()
void GPUCoalescer::hitCallback (GPUCoalescerRequest * request, MachineType mach, DataBlock & data, bool success, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion) protected
Definition at line 594 of file GPUCoalescer.cc.
References completeHitCallback(), DPRINTF, Packet::getAddr(), DataBlock::getData(), getOffset(), Packet::getPtr(), Packet::getSize(), ArmISA::i, CacheMemory::isTagPresent(), ArmISA::len, m_dataCache_ptr, m_instCache_ptr, GPUCoalescerRequest::m_type, RubyPort::m_usingRubyTester, makeLineAddress(), SubBlock::mergeFrom(), GPUCoalescerRequest::pkt, Packet::SenderState::predecessor, recordMissLatency(), reqCoalescer, safe_cast(), Packet::senderState, DataBlock::setData(), Packet::setData(), CacheMemory::setMRU(), RubyTester::SenderState::subBlock, and type.
Referenced by readCallback(), and writeCallback().
insertKernel()
void GPUCoalescer::insertKernel (int wavefront_id, PacketPtr pkt)
Definition at line 295 of file GPUCoalescer.cc.
References DPRINTF, and kernelEndList.
Referenced by VIPERCoalescer::makeRequest(), and makeRequest().
insertRequest()
bool GPUCoalescer::insertRequest (PacketPtr pkt, RubyRequestType request_type) protected
Definition at line 312 of file GPUCoalescer.cc.
References MessageBuffer::areNSlotsAvailable(), Clocked::clockEdge(), Clocked::curCycle(), curTick(), deadlockCheckEvent, DPRINTF, Packet::getAddr(), getRequestStatus(), ArmISA::i, M5_VAR_USED, m_deadlock_threshold, RubyPort::m_mandatory_q_ptr, m_outstanding_count, m_outstandReqHist, m_readRequestTable, m_writeRequestTable, makeLineAddress(), MipsISA::r, Packet::req, Stats::DistBase< Derived, Stor >::sample(), EventManager::schedule(), and Event::scheduled().
Referenced by completeIssue().
isDeadlockEventScheduled()
bool GPUCoalescer::isDeadlockEventScheduled () const inline virtual
Implements RubyPort.
Definition at line 167 of file GPUCoalescer.hh.
issueRequest()
void GPUCoalescer::issueRequest (PacketPtr pkt, RubyRequestType type) protected virtual
Definition at line 872 of file GPUCoalescer.cc.
References DataBlock::clear(), Clocked::clockEdge(), curTick(), Clocked::cyclesToTicks(), DPRINTFR, MessageBuffer::enqueue(), fatal_if, Packet::getAddr(), Packet::getAtomicOp(), RubySystem::getBlockSizeBytes(), Packet::getPtr(), Packet::getSize(), ArmISA::i, Packet::isAtomicOp(), Packet::isWrite(), ArmISA::j, RubyPort::m_controller, RubyPort::m_mandatory_q_ptr, RubyPort::m_version, makeLineAddress(), AbstractController::mandatoryQueueLatency(), MipsISA::pc, printAddress(), Packet::req, reqCoalescer, reqScopeToHSAScope(), and reqSegmentToHSASegment().
Referenced by completeIssue().
kernelCallback()
void GPUCoalescer::kernelCallback (int wavfront_id) protected
Definition at line 1042 of file GPUCoalescer.cc.
References kernelEndList, and RubyPort::ruby_hit_callback().
Referenced by completeIssue().
makeRequest()
RequestStatus GPUCoalescer::makeRequest (PacketPtr pkt) virtual
Implements RubyPort.
Reimplemented in VIPERCoalescer.
Definition at line 694 of file GPUCoalescer.cc.
References assumingRfOCoherence, curTick(), X86ISA::FlagShift, Packet::getAddr(), getRequestStatus(), insertKernel(), Packet::isAtomicOp(), Packet::isFlush(), Packet::isLLSC(), Packet::isRead(), issueEvent, Packet::isWrite(), m_max_outstanding_requests, m_outstanding_count, makeLineAddress(), newKernelEnds, newRequests, panic, Packet::req, reqCoalescer, EventManager::schedule(), Event::scheduled(), ArmISA::status, and X86ISA::StoreCheck.
Referenced by VIPERCoalescer::makeRequest().
mapAddrToPkt()
PacketPtr GPUCoalescer::mapAddrToPkt (Addr address) protected
Definition at line 1171 of file GPUCoalescer.cc.
References ArmISA::i, m_readRequestTable, and GPUCoalescerRequest::pkt.
markRemoved()
void GPUCoalescer::markRemoved ()
Definition at line 382 of file GPUCoalescer.cc.
References m_outstanding_count, m_readRequestTable, and m_writeRequestTable.
Referenced by atomicCallback(), readCallback(), removeRequest(), and writeCallback().
operator=()
GPUCoalescer& GPUCoalescer::operator= (const GPUCoalescer & obj) private
outstandingCount()
int GPUCoalescer::outstandingCount () const inline virtual
Implements RubyPort.
Definition at line 164 of file GPUCoalescer.hh.
print()
void GPUCoalescer::print (std::ostream & out) const
Definition at line 972 of file GPUCoalescer.cc.
References m_outstanding_count, m_readRequestTable, RubyPort::m_version, and m_writeRequestTable.
Referenced by operator<<().
printProgress()
void GPUCoalescer::printProgress (std::ostream & out) const
Definition at line 230 of file GPUCoalescer.cc.
readCallback() [1/4]
void GPUCoalescer::readCallback (Addr address, DataBlock & data)
Definition at line 538 of file GPUCoalescer.cc.
Referenced by readCallback().
readCallback() [2/4]
void GPUCoalescer::readCallback (Addr address, MachineType mach, DataBlock & data)
Definition at line 544 of file GPUCoalescer.cc.
References readCallback().
readCallback() [3/4]
void GPUCoalescer::readCallback (Addr address, MachineType mach, DataBlock & data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
Definition at line 552 of file GPUCoalescer.cc.
References readCallback().
readCallback() [4/4]
void GPUCoalescer::readCallback (Addr address, MachineType mach, DataBlock & data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
Definition at line 566 of file GPUCoalescer.cc.
References DPRINTF, hitCallback(), ArmISA::i, m_readRequestTable, makeLineAddress(), and markRemoved().
recordCPReadCallBack()
void GPUCoalescer::recordCPReadCallBack (MachineID myMachID, MachineID senderMachID)
Definition at line 1125 of file GPUCoalescer.cc.
References CP_LdMiss, CP_TCCLdHits, CP_TCPLdHits, CP_TCPLdTransfers, and machineIDToMachineType().
recordCPWriteCallBack()
void GPUCoalescer::recordCPWriteCallBack (MachineID myMachID, MachineID senderMachID)
Definition at line 1139 of file GPUCoalescer.cc.
References CP_StMiss, CP_TCCStHits, CP_TCPStHits, CP_TCPStTransfers, and machineIDToMachineType().
recordMissLatency()
void GPUCoalescer::recordMissLatency (GPUCoalescerRequest * request, MachineType mach, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool success, bool isRegion) protected
Definition at line 1180 of file GPUCoalescer.cc.
References Clocked::curCycle(), curTick(), DPRINTFR, Packet::getAddr(), GPU_LdMiss, GPU_StMiss, GPU_TCCLdHits, GPU_TCCStHits, GPU_TCPLdHits, GPU_TCPLdTransfers, GPU_TCPStHits, GPU_TCPStTransfers, GPUCoalescerRequest::issue_time, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, GPUCoalescerRequest::m_type, m_typeLatencyHist, RubyPort::m_version, GPUCoalescerRequest::pkt, printAddress(), Stats::DistBase< Derived, Stor >::sample(), and type.
Referenced by atomicCallback(), and hitCallback().
recordRequestType()
void GPUCoalescer::recordRequestType (SequencerRequestType requestType)
Definition at line 990 of file GPUCoalescer.cc.
References DPRINTF.
regStats()
void GPUCoalescer::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 1258 of file GPUCoalescer.cc.
References CP_LdMiss, CP_StMiss, CP_TCCLdHits, CP_TCCStHits, CP_TCPLdHits, CP_TCPLdTransfers, CP_TCPStHits, CP_TCPStTransfers, Stats::DataWrap< Derived, InfoProxyType >::desc(), GPU_LdMiss, GPU_StMiss, GPU_TCCLdHits, GPU_TCCStHits, GPU_TCPLdHits, GPU_TCPLdTransfers, GPU_TCPStHits, GPU_TCPStTransfers, ArmISA::i, Stats::Histogram::init(), ArmISA::j, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_outstandReqHist, m_typeLatencyHist, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::Group::regStats().
removeRequest()
void GPUCoalescer::removeRequest (GPUCoalescerRequest * request)
Definition at line 390 of file GPUCoalescer.cc.
References Packet::getAddr(), m_outstanding_count, m_readRequestTable, GPUCoalescerRequest::m_type, m_writeRequestTable, makeLineAddress(), markRemoved(), and GPUCoalescerRequest::pkt.
resetStats()
void GPUCoalescer::resetStats () virtual
Callback to reset stats.
Reimplemented from Stats::Group.
Definition at line 207 of file GPUCoalescer.cc.
References ArmISA::i, ArmISA::j, m_FirstResponseToCompletionDelayHist, m_ForwardToFirstResponseDelayHist, m_InitialToForwardDelayHist, m_IssueToInitialDelayHist, m_latencyHist, m_missLatencyHist, m_missMachLatencyHist, m_missTypeLatencyHist, m_missTypeMachLatencyHist, m_typeLatencyHist, and Stats::DistBase< Derived, Stor >::reset().
tryCacheAccess()
bool GPUCoalescer::tryCacheAccess (Addr addr, RubyRequestType type, Addr pc, RubyAccessMode access_mode, int size, DataBlock *& data_ptr) protected
wakeup()
void GPUCoalescer::wakeup ()
Definition at line 155 of file GPUCoalescer.cc.
References Clocked::clockPeriod(), Clocked::curCycle(), curTick(), deadlockCheckEvent, Packet::getAddr(), GPUCoalescerRequest::issue_time, m_deadlock_threshold, m_outstanding_count, m_readRequestTable, RubyPort::m_version, m_writeRequestTable, panic, GPUCoalescerRequest::pkt, and EventManager::schedule().
Referenced by GPUCoalescer().
writeCallback() [1/4]
void GPUCoalescer::writeCallback (Addr address, DataBlock & data)
Definition at line 456 of file GPUCoalescer.cc.
Referenced by writeCallback().
writeCallback() [2/4]
void GPUCoalescer::writeCallback (Addr address, MachineType mach, DataBlock & data)
Definition at line 462 of file GPUCoalescer.cc.
References writeCallback().
writeCallback() [3/4]
void GPUCoalescer::writeCallback (Addr address, MachineType mach, DataBlock & data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime, bool isRegion)
Definition at line 483 of file GPUCoalescer.cc.
References AbstractController::blockOnQueue(), DPRINTF, handleLlsc(), hitCallback(), ArmISA::i, RubyPort::m_controller, RubyPort::m_mandatory_q_ptr, m_runningGarnetStandalone, m_writeRequestTable, makeLineAddress(), markRemoved(), and AbstractController::unblock().
writeCallback() [4/4]
void GPUCoalescer::writeCallback (Addr address, MachineType mach, DataBlock & data, Cycles initialRequestTime, Cycles forwardRequestTime, Cycles firstResponseTime)
Definition at line 470 of file GPUCoalescer.cc.
References writeCallback().
Member Data Documentation
assumingRfOCoherence
bool GPUCoalescer::assumingRfOCoherence protected
Definition at line 294 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), and makeRequest().
CP_LdMiss
Stats::Scalar GPUCoalescer::CP_LdMiss protected
Definition at line 310 of file GPUCoalescer.hh.
Referenced by recordCPReadCallBack(), and regStats().
CP_StMiss
Stats::Scalar GPUCoalescer::CP_StMiss protected
Definition at line 315 of file GPUCoalescer.hh.
Referenced by recordCPWriteCallBack(), and regStats().
CP_TCCLdHits
Stats::Scalar GPUCoalescer::CP_TCCLdHits protected
Definition at line 309 of file GPUCoalescer.hh.
Referenced by recordCPReadCallBack(), and regStats().
CP_TCCStHits
Stats::Scalar GPUCoalescer::CP_TCCStHits protected
Definition at line 314 of file GPUCoalescer.hh.
Referenced by recordCPWriteCallBack(), and regStats().
CP_TCPLdHits
Stats::Scalar GPUCoalescer::CP_TCPLdHits protected
Definition at line 307 of file GPUCoalescer.hh.
Referenced by recordCPReadCallBack(), and regStats().
CP_TCPLdTransfers
Stats::Scalar GPUCoalescer::CP_TCPLdTransfers protected
Definition at line 308 of file GPUCoalescer.hh.
Referenced by recordCPReadCallBack(), and regStats().
CP_TCPStHits
Stats::Scalar GPUCoalescer::CP_TCPStHits protected
Definition at line 312 of file GPUCoalescer.hh.
Referenced by recordCPWriteCallBack(), and regStats().
CP_TCPStTransfers
Stats::Scalar GPUCoalescer::CP_TCPStTransfers protected
Definition at line 313 of file GPUCoalescer.hh.
Referenced by recordCPWriteCallBack(), and regStats().
deadlockCheckEvent
EventFunctionWrapper GPUCoalescer::deadlockCheckEvent protected
Definition at line 293 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), insertRequest(), and wakeup().
GPU_LdMiss
Stats::Scalar GPUCoalescer::GPU_LdMiss protected
Definition at line 300 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_StMiss
Stats::Scalar GPUCoalescer::GPU_StMiss protected
Definition at line 305 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCCLdHits
Stats::Scalar GPUCoalescer::GPU_TCCLdHits protected
Definition at line 299 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCCStHits
Stats::Scalar GPUCoalescer::GPU_TCCStHits protected
Definition at line 304 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCPLdHits
Stats::Scalar GPUCoalescer::GPU_TCPLdHits protected
Definition at line 297 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCPLdTransfers
Stats::Scalar GPUCoalescer::GPU_TCPLdTransfers protected
Definition at line 298 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCPStHits
Stats::Scalar GPUCoalescer::GPU_TCPStHits protected
Definition at line 302 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
GPU_TCPStTransfers
Stats::Scalar GPUCoalescer::GPU_TCPStTransfers protected
Definition at line 303 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), and regStats().
issueEvent
EventFunctionWrapper GPUCoalescer::issueEvent protected
Definition at line 258 of file GPUCoalescer.hh.
Referenced by VIPERCoalescer::makeRequest(), and makeRequest().
kernelEndList
std::unordered_map<int, PacketPtr> GPUCoalescer::kernelEndList protected
Definition at line 283 of file GPUCoalescer.hh.
Referenced by insertKernel(), VIPERCoalescer::invCallback(), kernelCallback(), VIPERCoalescer::makeRequest(), and VIPERCoalescer::wbCallback().
m_dataCache_ptr
CacheMemory* GPUCoalescer::m_dataCache_ptr protected
Definition at line 266 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), handleLlsc(), hitCallback(), VIPERCoalescer::invL1(), VIPERCoalescer::invwbL1(), and VIPERCoalescer::wbL1().
m_deadlock_check_scheduled
bool GPUCoalescer::m_deadlock_check_scheduled protected
Definition at line 282 of file GPUCoalescer.hh.
m_deadlock_threshold
int GPUCoalescer::m_deadlock_threshold protected
Definition at line 264 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), insertRequest(), and wakeup().
m_FirstResponseToCompletionDelayHist
std::vector<Stats::Histogram *> GPUCoalescer::m_FirstResponseToCompletionDelayHist protected
Definition at line 338 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_ForwardToFirstResponseDelayHist
std::vector<Stats::Histogram *> GPUCoalescer::m_ForwardToFirstResponseDelayHist protected
Definition at line 337 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_InitialToForwardDelayHist
std::vector<Stats::Histogram *> GPUCoalescer::m_InitialToForwardDelayHist protected
Definition at line 336 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_instCache_ptr
CacheMemory* GPUCoalescer::m_instCache_ptr protected
Definition at line 267 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), and hitCallback().
m_IssueToInitialDelayHist
std::vector<Stats::Histogram *> GPUCoalescer::m_IssueToInitialDelayHist protected
Histograms for recording the breakdown of miss latency.
Definition at line 335 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_latencyHist
Stats::Histogram GPUCoalescer::m_latencyHist protected
Histogram for holding latency profile of all requests.
Definition at line 321 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_load_waiting_on_load_cycles
int GPUCoalescer::m_load_waiting_on_load_cycles protected
Definition at line 289 of file GPUCoalescer.hh.
Referenced by getRequestStatus(), and GPUCoalescer().
m_load_waiting_on_store_cycles
int GPUCoalescer::m_load_waiting_on_store_cycles protected
Definition at line 288 of file GPUCoalescer.hh.
Referenced by getRequestStatus(), and GPUCoalescer().
m_max_outstanding_requests
int GPUCoalescer::m_max_outstanding_requests protected
Definition at line 263 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), and makeRequest().
m_missLatencyHist
Stats::Histogram GPUCoalescer::m_missLatencyHist protected
Histogram for holding latency profile of all requests that miss in the controller connected to this sequencer.
Definition at line 326 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missMachLatencyHist
std::vector<Stats::Histogram *> GPUCoalescer::m_missMachLatencyHist protected
Histograms for profiling the latencies for requests that required external messages.
Definition at line 331 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missTypeLatencyHist
std::vector<Stats::Histogram *> GPUCoalescer::m_missTypeLatencyHist protected
Definition at line 327 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_missTypeMachLatencyHist
std::vector< std::vector<Stats::Histogram *> > GPUCoalescer::m_missTypeMachLatencyHist protected
Definition at line 332 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_outstanding_count
int GPUCoalescer::m_outstanding_count protected
Definition at line 281 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), insertRequest(), makeRequest(), markRemoved(), print(), removeRequest(), and wakeup().
m_outstandReqHist
Stats::Histogram GPUCoalescer::m_outstandReqHist protected
Histogram for number of outstanding requests per cycle.
Definition at line 318 of file GPUCoalescer.hh.
Referenced by insertRequest(), and regStats().
m_readRequestTable
RequestTable GPUCoalescer::m_readRequestTable protected
Definition at line 279 of file GPUCoalescer.hh.
Referenced by empty(), getRequestStatus(), insertRequest(), mapAddrToPkt(), markRemoved(), print(), readCallback(), removeRequest(), and wakeup().
m_runningGarnetStandalone
bool GPUCoalescer::m_runningGarnetStandalone protected
Definition at line 291 of file GPUCoalescer.hh.
Referenced by GPUCoalescer(), and writeCallback().
m_store_waiting_on_load_cycles
int GPUCoalescer::m_store_waiting_on_load_cycles protected
Definition at line 286 of file GPUCoalescer.hh.
Referenced by getRequestStatus(), and GPUCoalescer().
m_store_waiting_on_store_cycles
int GPUCoalescer::m_store_waiting_on_store_cycles protected
Definition at line 287 of file GPUCoalescer.hh.
Referenced by getRequestStatus(), and GPUCoalescer().
m_typeLatencyHist
std::vector<Stats::Histogram *> GPUCoalescer::m_typeLatencyHist protected
Definition at line 322 of file GPUCoalescer.hh.
Referenced by recordMissLatency(), regStats(), and resetStats().
m_writeRequestTable
RequestTable GPUCoalescer::m_writeRequestTable protected
Definition at line 278 of file GPUCoalescer.hh.
Referenced by atomicCallback(), empty(), getRequestStatus(), insertRequest(), markRemoved(), print(), removeRequest(), wakeup(), and writeCallback().
newKernelEnds
std::vector<int> GPUCoalescer::newKernelEnds protected
Definition at line 284 of file GPUCoalescer.hh.
Referenced by completeIssue(), VIPERCoalescer::invCallback(), VIPERCoalescer::makeRequest(), makeRequest(), and VIPERCoalescer::wbCallback().
newRequests
std::vector<Addr> GPUCoalescer::newRequests protected
Definition at line 275 of file GPUCoalescer.hh.
Referenced by completeIssue(), and makeRequest().
reqCoalescer
CoalescingTable GPUCoalescer::reqCoalescer protected
Definition at line 274 of file GPUCoalescer.hh.
Referenced by atomicCallback(), completeIssue(), hitCallback(), issueRequest(), and makeRequest().
The documentation for this class was generated from the following files:
mem/ruby/system/GPUCoalescer.hh
mem/ruby/system/GPUCoalescer.cc