gem5: sc_gem5::ScExportWrapper< IF > Class Template Reference
sc_gem5::ScExportWrapper< IF > Class Template Reference
#include <sc_port_wrapper.hh>
Public Types
using ScExport = sc_core::sc_export< IF >
Public Member Functions
ScExportWrapper (ScExport &p, const std::string &name, PortID id)
ScExport & port ()
void unbind () override
Dettach from a peer port.
void bind (::Port &peer) override
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
virtual void bind (Port &peer)
Attach to a peer port.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Private Attributes
ScExport & port_
Additional Inherited Members
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
template<typename IF>
class sc_gem5::ScExportWrapper< IF >
Definition at line 51 of file sc_port_wrapper.hh.
Member Typedef Documentation
ScExport
template<typename IF > using sc_gem5::ScExportWrapper< IF >::ScExport = sc_core::sc_export<IF>
Definition at line 138 of file sc_port_wrapper.hh.
Constructor & Destructor Documentation
ScExportWrapper()
template<typename IF > sc_gem5::ScExportWrapper< IF >::ScExportWrapper (ScExport & p, const std::string & name, PortID id) inline
Definition at line 140 of file sc_port_wrapper.hh.
Member Function Documentation
bind()
template<typename IF > void sc_gem5::ScExportWrapper< IF >::bind (::Port & peer) inline override
Definition at line 157 of file sc_port_wrapper.hh.
References sc_core::sc_port_b< IF >::bind(), sc_gem5::Port::bind(), fatal_if, Port::name(), and sc_gem5::ScPortWrapper< IF >::port_.
port()
template<typename IF > ScExport& sc_gem5::ScExportWrapper< IF >::port () inline
Definition at line 145 of file sc_port_wrapper.hh.
References sc_gem5::ScPortWrapper< IF >::port_.
unbind()
template<typename IF > void sc_gem5::ScExportWrapper< IF >::unbind () inline override virtual
Dettach from a peer port.
Reimplemented from Port.
Definition at line 151 of file sc_port_wrapper.hh.
References panic.
Member Data Documentation
port_
template<typename IF > ScExport& sc_gem5::ScExportWrapper< IF >::port_ private
Definition at line 169 of file sc_port_wrapper.hh.
The documentation for this class was generated from the following file:
systemc/sc_port_wrapper.hh