gem5: FunctionRefOperand Class Reference
FunctionRefOperand Class Reference
#include <operand.hh>
Public Member Functions
void init (unsigned opOffset, const BrigObject *obj)
std::string disassemble ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Public Attributes
const char * func_name
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 787 of file operand.hh.
Member Function Documentation
disassemble()
std::string FunctionRefOperand::disassemble ()
Definition at line 133 of file operand.cc.
References csprintf(), and DPRINTF.
Referenced by HsailISA::Call::Call(), and HsailISA::Call::execute().
init()
void FunctionRefOperand::init (unsigned opOffset, const BrigObject * obj)
Definition at line 116 of file operand.cc.
References Brig::BRIG_KIND_OPERAND_CODE_REF, fatal, BrigObject::getCodeSectionEntry(), BrigObject::getOperand(), BrigObject::getString(), Brig::BrigBase::kind, Brig::BrigDirectiveExecutable::name, MipsISA::p, and Brig::BrigOperandCodeRef::ref.
Referenced by HsailISA::Call::Call().
Member Data Documentation
func_name
const char* FunctionRefOperand::func_name
Definition at line 790 of file operand.hh.
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc