gem5: sc_core::sc_export< IF > Class Template Reference
sc_core::sc_export< IF > Class Template Reference
#include <sc_export.hh>
Public Member Functions
sc_export ()
sc_export (const char *n)
virtual ~sc_export ()
virtual const char * kind () const
void operator() (IF &i)
virtual void bind (IF &i)
operator IF & ()
operator const IF & () const
IF * operator-> ()
const IF * operator-> () const
sc_interface * get_iterface () override
const sc_interface * get_interface () const override
Public Member Functions inherited from sc_core::sc_export_base
sc_export_base (const char *n)
~sc_export_base ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Member Functions
sc_export (const sc_export< IF > &)
sc_export< IF > & operator= (const sc_export< IF > &)
Private Attributes
IF * interface
Detailed Description
template<class IF>
class sc_core::sc_export< IF >
Definition at line 62 of file sc_export.hh.
Constructor & Destructor Documentation
sc_export() [1/3]
template<class IF> sc_core::sc_export< IF >::sc_export () inline
Definition at line 65 of file sc_export.hh.
sc_export() [2/3]
template<class IF> sc_core::sc_export< IF >::sc_export (const char * n) inline explicit
Definition at line 68 of file sc_export.hh.
~sc_export()
template<class IF> virtual sc_core::sc_export< IF >::~sc_export () inline virtual
Definition at line 71 of file sc_export.hh.
sc_export() [3/3]
template<class IF> sc_core::sc_export< IF >::sc_export (const sc_export< IF > &) private
Member Function Documentation
before_end_of_elaboration()
template<class IF> void sc_core::sc_export< IF >::before_end_of_elaboration () inline protected virtual
Implements sc_core::sc_export_base.
Definition at line 112 of file sc_export.hh.
bind()
template<class IF> virtual void sc_core::sc_export< IF >::bind (IF & i) inline virtual
Reimplemented in tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, and tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Definition at line 77 of file sc_export.hh.
Referenced by tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::before_end_of_elaboration(), tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >::bind(), tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >::get_base_export(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::simple_initiator_socket_b(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >::simple_initiator_socket_tagged_b().
end_of_elaboration()
template<class IF> void sc_core::sc_export< IF >::end_of_elaboration () inline protected virtual
Implements sc_core::sc_export_base.
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >.
Definition at line 114 of file sc_export.hh.
end_of_simulation()
template<class IF> void sc_core::sc_export< IF >::end_of_simulation () inline protected virtual
Implements sc_core::sc_export_base.
Definition at line 123 of file sc_export.hh.
get_interface()
template<class IF> const sc_interface* sc_core::sc_export< IF >::get_interface () const inline override virtual
Implements sc_core::sc_export_base.
Definition at line 109 of file sc_export.hh.
get_iterface()
template<class IF> sc_interface* sc_core::sc_export< IF >::get_iterface () inline override virtual
Implements sc_core::sc_export_base.
Definition at line 108 of file sc_export.hh.
kind()
template<class IF> virtual const char* sc_core::sc_export< IF >::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Reimplemented in tlm::tlm_target_socket< BUSWIDTH, TYPES, N, POL >, tlm::tlm_target_socket< 32 >, tlm::tlm_target_socket< BUSWIDTH, my_extended_payload_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, tlm::tlm_base_protocol_types, N, POL >, tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, tlm::tlm_base_protocol_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, POL >, ClockRateControlTargetSocket, SignalInterruptTargetSocket, tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Definition at line 73 of file sc_export.hh.
operator const IF &()
template<class IF> sc_core::sc_export< IF >::operator const IF & () const inline
Definition at line 91 of file sc_export.hh.
operator IF &()
template<class IF> sc_core::sc_export< IF >::operator IF & () inline
Definition at line 85 of file sc_export.hh.
operator()()
template<class IF> void sc_core::sc_export< IF >::operator() (IF & i) inline
Definition at line 75 of file sc_export.hh.
operator->() [1/2]
template<class IF> IF* sc_core::sc_export< IF >::operator-> () inline
Definition at line 94 of file sc_export.hh.
operator->() [2/2]
template<class IF> const IF* sc_core::sc_export< IF >::operator-> () const inline
Definition at line 101 of file sc_export.hh.
operator=()
template<class IF> sc_export<IF>& sc_core::sc_export< IF >::operator= (const sc_export< IF > &) private
start_of_simulation()
template<class IF> void sc_core::sc_export< IF >::start_of_simulation () inline protected virtual
Implements sc_core::sc_export_base.
Reimplemented in tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_tagged_b< SimpleBusLT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< SimpleBusAT, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::simple_target_socket_b< sc_gem5::TlmToGem5Bridge< BITWIDTH >, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket_b< SimpleATTarget2, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_gp2ext, BUSWIDTH, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleATTarget1, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< ExplicitLTTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< adapt_ext2gp, BUSWIDTH, my_extended_payload_types >, tlm_utils::simple_target_socket_b< ExplicitATTarget, 32, tlm::tlm_base_protocol_types >, tlm_utils::simple_target_socket_b< SimpleLTTarget_ext, BUSWIDTH, my_extended_payload_types >, and tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, sc_core::SC_ZERO_OR_MORE_BOUND >.
Definition at line 122 of file sc_export.hh.
Member Data Documentation
interface
template<class IF> IF* sc_core::sc_export< IF >::interface private
Definition at line 126 of file sc_export.hh.
The documentation for this class was generated from the following file:
systemc/ext/core/sc_export.hh