gem5: sc_gem5::ScMainFiber Class Reference
sc_gem5::ScMainFiber Class Reference
#include <sc_main_fiber.hh>
Public Member Functions
ScMainFiber ()
int argc ()
const char *const * argv ()
std::string resultStr ()
int resultInt ()
bool called ()
void setArgs (int new_argc, char **new_argv)
void main () override
This method is called when this fiber is first run.
Public Member Functions inherited from Fiber
Fiber (size_t stack_size=DefaultStackSize)
stack_size is the size of the stack available to this fiber.
Fiber (Fiber *link, size_t stack_size=DefaultStackSize)
virtual ~Fiber ()
void run ()
Start executing the fiber represented by this object.
bool finished () const
Returns whether the "main" function of this fiber has finished.
bool started () const
Returns whether the "main" function of this fiber has started.
Private Attributes
int _argc = 0
char ** _argv = NULL
std::string _resultStr
int _resultInt = 1
bool _called = false
Additional Inherited Members
Static Public Member Functions inherited from Fiber
static Fiber * currentFiber ()
Get a pointer to the current running Fiber.
static Fiber * primaryFiber ()
Get a pointer to the primary Fiber.
Static Public Attributes inherited from Fiber
static const size_t DefaultStackSize = 0x50000
Protected Member Functions inherited from Fiber
void setStarted ()
Detailed Description
Definition at line 39 of file sc_main_fiber.hh.
Constructor & Destructor Documentation
ScMainFiber()
sc_gem5::ScMainFiber::ScMainFiber () inline
Definition at line 50 of file sc_main_fiber.hh.
Member Function Documentation
argc()
int sc_gem5::ScMainFiber::argc () inline
Definition at line 52 of file sc_main_fiber.hh.
References _argc.
Referenced by sc_core::sc_argc().
argv()
const char* const* sc_gem5::ScMainFiber::argv () inline
Definition at line 53 of file sc_main_fiber.hh.
References _argv.
Referenced by sc_core::sc_argv().
called()
bool sc_gem5::ScMainFiber::called () inline
Definition at line 56 of file sc_main_fiber.hh.
References _called.
Referenced by sc_gem5::Scheduler::pause(), sc_gem5::Scheduler::stop(), and sc_gem5::Scheduler::throwUp().
main()
void sc_gem5::ScMainFiber::main () override virtual
This method is called when this fiber is first run.
Override it to give your fiber something to do. When main returns, the fiber will mark itself as finished and switch to its link fiber.
Implements Fiber.
Definition at line 49 of file sc_main_fiber.cc.
References _argc, _argv, _called, _resultInt, _resultStr, sc_gem5::Scheduler::clear(), fatal, sc_core::sc_report_handler::get_catch_actions(), MipsISA::r, sc_gem5::reportHandlerProc, sc_gem5::reportifyException(), sc_main(), and sc_gem5::scheduler.
Referenced by setArgs().
resultInt()
int sc_gem5::ScMainFiber::resultInt () inline
Definition at line 55 of file sc_main_fiber.hh.
References _resultInt.
resultStr()
std::string sc_gem5::ScMainFiber::resultStr () inline
Definition at line 54 of file sc_main_fiber.hh.
References _resultStr.
setArgs()
void sc_gem5::ScMainFiber::setArgs (int new_argc, char ** new_argv) inline
Definition at line 59 of file sc_main_fiber.hh.
References main(), and sc_gem5::scMainFiber.
Member Data Documentation
_argc
int sc_gem5::ScMainFiber::_argc = 0 private
Definition at line 42 of file sc_main_fiber.hh.
Referenced by argc(), and main().
_argv
char** sc_gem5::ScMainFiber::_argv = NULL private
Definition at line 43 of file sc_main_fiber.hh.
Referenced by argv(), and main().
_called
bool sc_gem5::ScMainFiber::_called = false private
Definition at line 47 of file sc_main_fiber.hh.
Referenced by called(), and main().
_resultInt
int sc_gem5::ScMainFiber::_resultInt = 1 private
Definition at line 45 of file sc_main_fiber.hh.
Referenced by main(), and resultInt().
_resultStr
std::string sc_gem5::ScMainFiber::_resultStr private
Definition at line 44 of file sc_main_fiber.hh.
Referenced by main(), and resultStr().
The documentation for this class was generated from the following files:
systemc/core/sc_main_fiber.hh
systemc/core/sc_main_fiber.cc