gem5: TimeBuffer< T >::wire Class Reference
TimeBuffer< T >::wire Class Reference
#include <timebuf.hh>
Public Member Functions
wire ()
wire (const wire &i)
const wire & operator= (const wire &i)
const wire & operator= (int idx)
const wire & operator+= (int offset)
const wire & operator-= (int offset)
wire & operator++ ()
wire & operator++ (int)
wire & operator-- ()
wire & operator-- (int)
T & operator* () const
T * operator-> () const
Protected Member Functions
void set (int idx)
wire (TimeBuffer< T > *buf, int i)
Protected Attributes
TimeBuffer< T > * buffer
int index
Friends
class TimeBuffer
Detailed Description
template<class T>
class TimeBuffer< T >::wire
Definition at line 59 of file timebuf.hh.
Constructor & Destructor Documentation
wire() [1/3]
template<class T> TimeBuffer< T >::wire::wire (TimeBuffer< T > * buf, int i) inline protected
Definition at line 72 of file timebuf.hh.
wire() [2/3]
template<class T> TimeBuffer< T >::wire::wire () inline
Definition at line 77 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::getWire(), TimeBuffer< T >::wire::operator++(), TimeBuffer< T >::wire::operator--(), and TimeBuffer< DecodeStruct >::zero().
wire() [3/3]
template<class T> TimeBuffer< T >::wire::wire (const wire & i) inline
Definition at line 80 of file timebuf.hh.
Member Function Documentation
operator*()
template<class T> T& TimeBuffer< T >::wire::operator* () const inline
Definition at line 134 of file timebuf.hh.
References TimeBuffer< T >::access().
operator++() [1/2]
template<class T> wire& TimeBuffer< T >::wire::operator++ () inline
Definition at line 109 of file timebuf.hh.
operator++() [2/2]
template<class T> wire& TimeBuffer< T >::wire::operator++ (int) inline
Definition at line 115 of file timebuf.hh.
References ArmISA::i, TimeBuffer< T >::wire::index, and TimeBuffer< T >::wire::wire().
operator+=()
template<class T> const wire& TimeBuffer< T >::wire::operator+= (int offset) inline
Definition at line 97 of file timebuf.hh.
References ArmISA::offset.
operator--() [1/2]
template<class T> wire& TimeBuffer< T >::wire::operator-- () inline
Definition at line 122 of file timebuf.hh.
operator--() [2/2]
template<class T> wire& TimeBuffer< T >::wire::operator-- (int) inline
Definition at line 128 of file timebuf.hh.
References ArmISA::i, TimeBuffer< T >::wire::index, and TimeBuffer< T >::wire::wire().
operator-=()
template<class T> const wire& TimeBuffer< T >::wire::operator-= (int offset) inline
Definition at line 103 of file timebuf.hh.
References ArmISA::offset.
operator->()
template<class T> T* TimeBuffer< T >::wire::operator-> () const inline
Definition at line 135 of file timebuf.hh.
References TimeBuffer< T >::access().
operator=() [1/2]
template<class T> const wire& TimeBuffer< T >::wire::operator= (const wire & i) inline
Definition at line 84 of file timebuf.hh.
References TimeBuffer< T >::wire::buffer, and TimeBuffer< T >::wire::index.
operator=() [2/2]
template<class T> const wire& TimeBuffer< T >::wire::operator= (int idx) inline
Definition at line 91 of file timebuf.hh.
set()
template<class T> void TimeBuffer< T >::wire::set (int idx) inline protected
Definition at line 66 of file timebuf.hh.
References TimeBuffer< T >::valid().
Friends And Related Function Documentation
TimeBuffer
template<class T> friend class TimeBuffer friend
Definition at line 61 of file timebuf.hh.
Member Data Documentation
buffer
template<class T> TimeBuffer<T>* TimeBuffer< T >::wire::buffer protected
Definition at line 63 of file timebuf.hh.
Referenced by TimeBuffer< T >::wire::operator=().
index
template<class T> int TimeBuffer< T >::wire::index protected
Definition at line 64 of file timebuf.hh.
Referenced by TimeBuffer< T >::wire::operator++(), TimeBuffer< T >::wire::operator--(), and TimeBuffer< T >::wire::operator=().
The documentation for this class was generated from the following file:
cpu/timebuf.hh