gem5: IdeDisk Class Reference
IdeDisk Class Reference
IDE Disk device model.
#include <ide_disk.hh>
Public Types
typedef IdeDiskParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
IdeDisk (const Params *p)
~IdeDisk ()
Delete the data buffer.
void reset (int id)
Reset the device state.
void regStats () override
Register Statistics.
void setController (IdeController *c, Addr page_bytes)
Set the controller for this device.
void readCommand (const Addr offset, int size, uint8_t *data)
void readControl (const Addr offset, int size, uint8_t *data)
void writeCommand (const Addr offset, int size, const uint8_t *data)
void writeControl (const Addr offset, int size, const uint8_t *data)
void startDma (const uint32_t &prdTableBase)
void abortDma ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
IdeController * ctrl
The IDE controller for this disk.
DiskImage * image
The image that contains the data of this disk.
int diskDelay
The disk delay in microseconds.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
void startCommand ()
void intrPost ()
void intrClear ()
void doDmaTransfer ()
void doDmaDataRead ()
void doDmaRead ()
void doDmaDataWrite ()
void doDmaWrite ()
void dmaPrdReadDone ()
void dmaReadDone ()
void dmaWriteDone ()
void readDisk (uint32_t sector, uint8_t *data)
void writeDisk (uint32_t sector, uint8_t *data)
void updateState (DevAction_t action)
bool isBSYSet ()
bool isIENSet ()
bool isDEVSelect ()
void setComplete ()
uint32_t getLBABase ()
Addr pciToDma (Addr pciAddr)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Private Attributes
struct ataparams driveID
Drive identification structure for this disk.
uint8_t * dataBuffer
Data buffer for transfers.
uint32_t cmdBytes
Number of bytes in command data transfer.
uint32_t cmdBytesLeft
Number of bytes left in command data transfer.
uint32_t drqBytesLeft
Number of bytes left in DRQ block.
uint32_t curSector
Current sector in access.
CommandReg_t cmdReg
Command block registers.
uint8_t status
Status register.
bool nIENBit
Interrupt enable bit.
DevState_t devState
Device state.
DmaState_t dmaState
Dma state.
bool dmaRead
Dma transaction is a read.
Addr pageBytes
Size of OS pages.
uint32_t curPrdAddr
PRD table base address.
PrdTableEntry curPrd
PRD entry.
int devID
Device ID (master=0/slave=1)
bool intrPending
Interrupt pending.
bool dmaAborted
DMA Aborted.
Stats::Scalar dmaReadFullPages
Stats::Scalar dmaReadBytes
Stats::Scalar dmaReadTxs
Stats::Scalar dmaWriteFullPages
Stats::Scalar dmaWriteBytes
Stats::Scalar dmaWriteTxs
EventFunctionWrapper dmaTransferEvent
ChunkGenerator * dmaReadCG
EventFunctionWrapper dmaReadWaitEvent
ChunkGenerator * dmaWriteCG
EventFunctionWrapper dmaWriteWaitEvent
EventFunctionWrapper dmaPrdReadEvent
EventFunctionWrapper dmaReadEvent
EventFunctionWrapper dmaWriteEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
IDE Disk device model.
Definition at line 207 of file ide_disk.hh.
Member Typedef Documentation
Params
typedef IdeDiskParams IdeDisk::Params
Definition at line 265 of file ide_disk.hh.
Constructor & Destructor Documentation
IdeDisk()
IdeDisk::IdeDisk (const Params * p)
Definition at line 65 of file ide_disk.cc.
References ataparams::atap_ata_major, ataparams::atap_capabilities1, ataparams::atap_capacity, ataparams::atap_curmulti, ataparams::atap_curmulti_valid, ataparams::atap_cylinders, ataparams::atap_dmamode_supp, ataparams::atap_extensions, ataparams::atap_heads, ataparams::atap_hwreset_res, ataparams::atap_model, ataparams::atap_multi, ataparams::atap_piomode_supp, ataparams::atap_sectors, ataparams::atap_udmamode_supp, dmaPrdReadDone(), dmaPrdReadEvent, dmaReadCG, dmaReadDone(), dmaReadEvent, dmaReadWaitEvent, dmaWriteCG, dmaWriteDone(), dmaWriteEvent, dmaWriteWaitEvent, doDmaRead(), doDmaTransfer(), doDmaWrite(), driveID, image, MAX_MULTSECT, SimObject::name(), MipsISA::p, panic, reset(), DiskImage::size(), and WDC_VER_ATA7.
Referenced by unserialize().
~IdeDisk()
IdeDisk::~IdeDisk ()
Delete the data buffer.
Definition at line 139 of file ide_disk.cc.
References dataBuffer.
Member Function Documentation
abortDma()
void IdeDisk::abortDma ()
Definition at line 614 of file ide_disk.cc.
References ACT_CMD_ERROR, devState, Dma_Idle, dmaState, panic, Prepare_Data_Dma, Transfer_Data_Dma, and updateState().
dmaPrdReadDone()
void IdeDisk::dmaPrdReadDone () private
Definition at line 358 of file ide_disk.cc.
References ACT_CMD_ERROR, cmdBytesLeft, curPrd, curPrdAddr, curSector, dmaAborted, dmaRead, doDmaDataRead(), doDmaDataWrite(), DPRINTF, PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), pciToDma(), SectorSize, and updateState().
Referenced by IdeDisk().
dmaReadDone()
void IdeDisk::dmaReadDone () private
Definition at line 466 of file ide_disk.cc.
References ACT_DMA_DONE, cmdBytesLeft, curPrd, curSector, dataBuffer, Dma_Idle, dmaState, doDmaTransfer(), PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), SectorSize, updateState(), and writeDisk().
Referenced by doDmaRead(), and IdeDisk().
dmaWriteDone()
void IdeDisk::dmaWriteDone () private
Definition at line 553 of file ide_disk.cc.
References ACT_DMA_DONE, cmdBytesLeft, curPrd, Dma_Idle, dmaState, doDmaTransfer(), DPRINTF, PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), and updateState().
Referenced by doDmaWrite(), and IdeDisk().
doDmaDataRead()
void IdeDisk::doDmaDataRead () private
Todo:
we need to figure out what the delay actually will be
Definition at line 382 of file ide_disk.cc.
References curPrd, curTick(), diskDelay, dmaReadWaitEvent, DPRINTF, PrdTableEntry::getByteCount(), EventManager::schedule(), and SectorSize.
Referenced by dmaPrdReadDone().
doDmaDataWrite()
void IdeDisk::doDmaDataWrite () private
Todo:
we need to figure out what the delay actually will be
Definition at line 489 of file ide_disk.cc.
References cmdBytesLeft, curPrd, curSector, curTick(), dataBuffer, diskDelay, dmaWriteWaitEvent, DPRINTF, PrdTableEntry::getByteCount(), MAX_DMA_SIZE, readDisk(), EventManager::schedule(), and SectorSize.
Referenced by dmaPrdReadDone().
doDmaRead()
void IdeDisk::doDmaRead () private
Definition at line 427 of file ide_disk.cc.
References ACT_CMD_ERROR, ChunkGenerator::addr(), ChunkGenerator::complete(), ctrl, curPrd, curTick(), dataBuffer, DMA_BACKOFF_PERIOD, dmaAborted, DmaDevice::dmaPending(), DmaDevice::dmaRead(), dmaReadBytes, dmaReadCG, dmaReadDone(), dmaReadFullPages, dmaReadTxs, dmaReadWaitEvent, ChunkGenerator::done(), DPRINTF, Drainable::drainState(), PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), MAX_DMA_SIZE, ChunkGenerator::next(), pageBytes, pciToDma(), Running, EventManager::schedule(), ChunkGenerator::size(), and updateState().
Referenced by IdeDisk().
doDmaTransfer()
void IdeDisk::doDmaTransfer () private
Definition at line 337 of file ide_disk.cc.
References ACT_CMD_ERROR, ctrl, curPrd, curPrdAddr, curTick(), devState, DMA_BACKOFF_PERIOD, Dma_Transfer, dmaAborted, DmaDevice::dmaPending(), dmaPrdReadEvent, DmaDevice::dmaRead(), dmaState, dmaTransferEvent, DPRINTF, Drainable::drainState(), PrdTableEntry::entry, panic, Running, EventManager::schedule(), Transfer_Data_Dma, and updateState().
Referenced by dmaReadDone(), dmaWriteDone(), and IdeDisk().
doDmaWrite()
void IdeDisk::doDmaWrite () private
Definition at line 512 of file ide_disk.cc.
References ACT_CMD_ERROR, ChunkGenerator::addr(), ChunkGenerator::complete(), ctrl, curPrd, curTick(), dataBuffer, DMA_BACKOFF_PERIOD, dmaAborted, DmaDevice::dmaPending(), DmaDevice::dmaWrite(), dmaWriteBytes, dmaWriteCG, dmaWriteDone(), dmaWriteFullPages, dmaWriteTxs, dmaWriteWaitEvent, ChunkGenerator::done(), DPRINTF, Drainable::drainState(), PrdTableEntry::getBaseAddr(), PrdTableEntry::getByteCount(), PrdTableEntry::getEOT(), MAX_DMA_SIZE, ChunkGenerator::next(), pageBytes, pciToDma(), Running, EventManager::schedule(), ChunkGenerator::size(), and updateState().
Referenced by IdeDisk().
getLBABase()
uint32_t IdeDisk::getLBABase () inline private
Definition at line 359 of file ide_disk.hh.
References CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::head, CommandReg::sec_num, serialize(), and unserialize().
Referenced by startCommand().
intrClear()
void IdeDisk::intrClear () private
Definition at line 757 of file ide_disk.cc.
References ctrl, DPRINTF, PciDevice::intrClear(), intrPending, and panic.
Referenced by updateState().
intrPost()
void IdeDisk::intrPost () private
Definition at line 742 of file ide_disk.cc.
References ctrl, DPRINTF, intrPending, IdeController::intrPost(), and panic.
Referenced by updateState().
isBSYSet()
bool IdeDisk::isBSYSet () inline private
Definition at line 345 of file ide_disk.hh.
References STATUS_BSY_BIT.
isDEVSelect()
bool IdeDisk::isDEVSelect () private
Definition at line 190 of file ide_disk.cc.
References ctrl, and IdeController::isDiskSelected().
Referenced by updateState().
isIENSet()
bool IdeDisk::isIENSet () inline private
Definition at line 346 of file ide_disk.hh.
Referenced by updateState().
pciToDma()
Addr IdeDisk::pciToDma (Addr pciAddr) inline private
Definition at line 196 of file ide_disk.cc.
References ctrl, panic, and PciDevice::pciToDma().
Referenced by dmaPrdReadDone(), doDmaRead(), doDmaWrite(), and startDma().
readCommand()
void IdeDisk::readCommand (const Addr offset, int size, uint8_t * data)
Definition at line 209 of file ide_disk.cc.
References ACT_DATA_READ_SHORT, ACT_STAT_READ, cmdReg, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::data, DATA_OFFSET, DPRINTF, CommandReg::drive, DRIVE_OFFSET, CommandReg::error, ERROR_OFFSET, HCYL_OFFSET, LCYL_OFFSET, NSECTOR_OFFSET, panic, CommandReg::sec_count, CommandReg::sec_num, SECTOR_OFFSET, status, STATUS_OFFSET, and updateState().
readControl()
void IdeDisk::readControl (const Addr offset, int size, uint8_t * data)
Definition at line 255 of file ide_disk.cc.
References ALTSTAT_OFFSET, DPRINTF, panic, and status.
readDisk()
void IdeDisk::readDisk (uint32_t sector, uint8_t * data) private
Definition at line 572 of file ide_disk.cc.
References image, SimObject::name(), panic, DiskImage::read(), and SectorSize.
Referenced by doDmaDataWrite(), and updateState().
regStats()
void IdeDisk::regStats () override virtual
Register Statistics.
Reimplemented from Stats::Group.
Definition at line 394 of file ide_disk.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), dmaReadBytes, dmaReadFullPages, dmaReadTxs, dmaWriteBytes, dmaWriteFullPages, dmaWriteTxs, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::Group::regStats().
reset()
void IdeDisk::reset (int id)
Reset the device state.
Definition at line 146 of file ide_disk.cc.
References cmdBytes, cmdBytesLeft, cmdReg, curPrd, curPrdAddr, curSector, dataBuffer, DEV0, DEV1, Device_Idle_NS, Device_Idle_S, devID, devState, Dma_Idle, dmaAborted, dmaRead, dmaState, drqBytesLeft, PrdTableEntry::entry, CommandReg::error, intrPending, MAX_DMA_SIZE, panic, status, and STATUS_DRDY_BIT.
Referenced by IdeDisk(), and updateState().
serialize()
void IdeDisk::serialize (CheckpointOut & cp) const override private virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Todo:
need to serialized chunk generator stuff!!
Implements Serializable.
Definition at line 1075 of file ide_disk.cc.
References PrdEntry::baseAddr, PrdEntry::byteCount, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, curPrd, curPrdAddr, curSector, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::data, dataBuffer, devID, devState, dmaAborted, dmaPrdReadEvent, DmaRead, dmaRead, dmaReadEvent, dmaReadWaitEvent, dmaState, dmaTransferEvent, DmaWrite, dmaWriteEvent, dmaWriteWaitEvent, CommandReg::drive, drqBytesLeft, PrdEntry::endOfTable, PrdTableEntry::entry, MipsISA::event, intrPending, MAX_DMA_SIZE, nIENBit, None, PrdRead, ReadWait, EventManager::reschedule(), Event::scheduled(), CommandReg::sec_count, CommandReg::sec_num, SERIALIZE_ARRAY, SERIALIZE_ENUM, SERIALIZE_SCALAR, status, Transfer, Event::when(), and WriteWait.
setComplete()
void IdeDisk::setComplete () inline private
Definition at line 349 of file ide_disk.hh.
References STATUS_DRDY_BIT, and STATUS_SEEK_BIT.
Referenced by updateState().
setController()
void IdeDisk::setController (IdeController * c, Addr page_bytes) inline
Set the controller for this device.
Parameters
c The IDE controller
Definition at line 288 of file ide_disk.hh.
References ArmISA::c, data, ArmISA::offset, and panic_if.
startCommand()
void IdeDisk::startCommand () private
Todo:
make this a scheduled event to simulate disk delay
Definition at line 626 of file ide_disk.cc.
References ACT_CMD_COMPLETE, ACT_DATA_READY, ACT_DMA_READY, ACT_NONE, ATAPI_IDENTIFY_DEVICE, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, Command_Execution, curSector, CommandReg::cyl_high, CommandReg::cyl_low, devState, dmaRead, DPRINTF, CommandReg::drive, DRIVE_LBA_BIT, getLBABase(), CommandReg::head, image, M5_FALLTHROUGH, panic, Prepare_Data_Dma, Prepare_Data_In, Prepare_Data_Out, CommandReg::sec_count, CommandReg::sec_num, SectorSize, SET_FEATURES, DiskImage::size(), status, STATUS_BSY_BIT, STATUS_DF_BIT, STATUS_DRQ_BIT, updateState(), WDCC_FLUSHCACHE, WDCC_IDENTIFY, WDCC_IDLE, WDCC_IDP, WDCC_READ, WDCC_READDMA, WDCC_READMULTI, WDCC_RECAL, WDCC_SETMULTI, WDCC_STANDBY_IMMED, WDCC_WRITE, WDCC_WRITEDMA, WDCC_WRITEMULTI, WDSF_READ_NATIVE_MAX, WDSF_SEEK, and WDSF_VERIFY.
Referenced by updateState().
startDma()
void IdeDisk::startDma (const uint32_t & prdTableBase)
Definition at line 596 of file ide_disk.cc.
References curPrdAddr, curTick(), devState, Dma_Start, Dma_Transfer, dmaState, dmaTransferEvent, panic, pciToDma(), EventManager::schedule(), Transfer_Data_Dma, and ULL.
unserialize()
void IdeDisk::unserialize (CheckpointIn & cp) override private virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Todo:
need to serialized chunk generator stuff!!
Implements Serializable.
Definition at line 1153 of file ide_disk.cc.
References PrdEntry::baseAddr, PrdEntry::byteCount, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, curPrd, curPrdAddr, curSector, CommandReg::cyl_high, CommandReg::cyl_low, CommandReg::data, dataBuffer, devID, devState, dmaAborted, dmaPrdReadEvent, DmaRead, dmaRead, dmaReadEvent, dmaReadWaitEvent, dmaState, dmaTransferEvent, DmaWrite, dmaWriteEvent, dmaWriteWaitEvent, CommandReg::drive, drqBytesLeft, PrdEntry::endOfTable, PrdTableEntry::entry, MipsISA::event, IdeDisk(), intrPending, MAX_DMA_SIZE, nIENBit, None, PrdRead, ReadWait, EventManager::reschedule(), EventManager::schedule(), CommandReg::sec_count, CommandReg::sec_num, status, Transfer, UNSERIALIZE_ARRAY, UNSERIALIZE_ENUM, UNSERIALIZE_SCALAR, and WriteWait.
updateState()
void IdeDisk::updateState (DevAction_t action) private
Todo:
change this to a scheduled event to simulate disk delay
Todo:
change this to a scheduled event to simulate disk delay
Definition at line 775 of file ide_disk.cc.
References ACT_CMD_COMPLETE, ACT_CMD_ERROR, ACT_CMD_WRITE, ACT_DATA_READ_BYTE, ACT_DATA_READ_SHORT, ACT_DATA_READY, ACT_DATA_WRITE_BYTE, ACT_DATA_WRITE_SHORT, ACT_DMA_DONE, ACT_DMA_READY, ACT_SELECT_WRITE, ACT_SRST_CLEAR, ACT_SRST_SET, ACT_STAT_READ, ATAPI_IDENTIFY_DEVICE, cmdBytes, cmdBytesLeft, cmdReg, CommandReg::command, Command_Execution, ctrl, curSector, CommandReg::data, Data_Ready_INTRQ_In, Data_Ready_INTRQ_Out, dataBuffer, Device_Dma_Abort, Device_Idle_NS, Device_Idle_S, Device_Idle_SI, Device_Srst, devID, devState, Dma_Idle, Dma_Start, dmaAborted, dmaState, DPRINTF, driveID, drqBytesLeft, intrClear(), intrPending, intrPost(), isDEVSelect(), isIENSet(), MAX_DMA_SIZE, panic, Prepare_Data_Dma, Prepare_Data_In, Prepare_Data_Out, readDisk(), reset(), SectorSize, setComplete(), IdeController::setDmaComplete(), startCommand(), status, STATUS_BSY_BIT, STATUS_DRQ_BIT, STATUS_SEEK_BIT, Transfer_Data_Dma, Transfer_Data_In, Transfer_Data_Out, WDCC_IDENTIFY, and writeDisk().
Referenced by abortDma(), dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaRead(), doDmaTransfer(), doDmaWrite(), readCommand(), startCommand(), writeCommand(), and writeControl().
writeCommand()
void IdeDisk::writeCommand (const Addr offset, int size, const uint8_t * data)
Definition at line 265 of file ide_disk.cc.
References ACT_CMD_WRITE, ACT_DATA_WRITE_SHORT, ACT_SELECT_WRITE, cmdReg, CommandReg::command, COMMAND_OFFSET, CommandReg::cyl_high, CommandReg::cyl_low, data, CommandReg::data, DATA_OFFSET, DPRINTF, CommandReg::drive, DRIVE_OFFSET, FEATURES_OFFSET, HCYL_OFFSET, LCYL_OFFSET, NSECTOR_OFFSET, panic, CommandReg::sec_count, CommandReg::sec_num, SECTOR_OFFSET, and updateState().
writeControl()
void IdeDisk::writeControl (const Addr offset, int size, const uint8_t * data)
Definition at line 313 of file ide_disk.cc.
References ACT_SRST_CLEAR, ACT_SRST_SET, CONTROL_IEN_BIT, CONTROL_OFFSET, CONTROL_RST_BIT, Device_Srst, devState, DPRINTF, nIENBit, panic, and updateState().
writeDisk()
void IdeDisk::writeDisk (uint32_t sector, uint8_t * data) private
Definition at line 582 of file ide_disk.cc.
References image, SimObject::name(), panic, SectorSize, and DiskImage::write().
Referenced by dmaReadDone(), and updateState().
Member Data Documentation
cmdBytes
uint32_t IdeDisk::cmdBytes private
Number of bytes in command data transfer.
Definition at line 225 of file ide_disk.hh.
Referenced by reset(), serialize(), startCommand(), unserialize(), and updateState().
cmdBytesLeft
uint32_t IdeDisk::cmdBytesLeft private
Number of bytes left in command data transfer.
Definition at line 227 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaDataWrite(), reset(), serialize(), startCommand(), unserialize(), and updateState().
cmdReg
CommandReg_t IdeDisk::cmdReg private
Command block registers.
Definition at line 233 of file ide_disk.hh.
Referenced by readCommand(), reset(), serialize(), startCommand(), unserialize(), updateState(), and writeCommand().
ctrl
IdeController* IdeDisk::ctrl protected
The IDE controller for this disk.
Definition at line 211 of file ide_disk.hh.
Referenced by doDmaRead(), doDmaTransfer(), doDmaWrite(), intrClear(), intrPost(), isDEVSelect(), pciToDma(), and updateState().
curPrd
PrdTableEntry IdeDisk::curPrd private
PRD entry.
Definition at line 249 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), dmaWriteDone(), doDmaDataRead(), doDmaDataWrite(), doDmaRead(), doDmaTransfer(), doDmaWrite(), reset(), serialize(), and unserialize().
curPrdAddr
uint32_t IdeDisk::curPrdAddr private
PRD table base address.
Definition at line 247 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), doDmaTransfer(), reset(), serialize(), startDma(), and unserialize().
curSector
uint32_t IdeDisk::curSector private
Current sector in access.
Definition at line 231 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), dmaReadDone(), doDmaDataWrite(), reset(), serialize(), startCommand(), unserialize(), and updateState().
dataBuffer
uint8_t* IdeDisk::dataBuffer private
Data buffer for transfers.
Definition at line 223 of file ide_disk.hh.
Referenced by dmaReadDone(), doDmaDataWrite(), doDmaRead(), doDmaWrite(), reset(), serialize(), unserialize(), updateState(), and ~IdeDisk().
devID
int IdeDisk::devID private
Device ID (master=0/slave=1)
Definition at line 251 of file ide_disk.hh.
Referenced by reset(), serialize(), unserialize(), and updateState().
devState
DevState_t IdeDisk::devState private
Device state.
Definition at line 239 of file ide_disk.hh.
Referenced by abortDma(), doDmaTransfer(), reset(), serialize(), startCommand(), startDma(), unserialize(), updateState(), and writeControl().
diskDelay
int IdeDisk::diskDelay protected
The disk delay in microseconds.
Definition at line 217 of file ide_disk.hh.
Referenced by doDmaDataRead(), and doDmaDataWrite().
dmaAborted
bool IdeDisk::dmaAborted private
DMA Aborted.
Definition at line 255 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), doDmaRead(), doDmaTransfer(), doDmaWrite(), reset(), serialize(), unserialize(), and updateState().
dmaPrdReadEvent
EventFunctionWrapper IdeDisk::dmaPrdReadEvent private
Definition at line 329 of file ide_disk.hh.
Referenced by doDmaTransfer(), IdeDisk(), serialize(), and unserialize().
dmaRead
bool IdeDisk::dmaRead private
Dma transaction is a read.
Definition at line 243 of file ide_disk.hh.
Referenced by dmaPrdReadDone(), reset(), serialize(), startCommand(), and unserialize().
dmaReadBytes
Stats::Scalar IdeDisk::dmaReadBytes private
Definition at line 258 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
dmaReadCG
ChunkGenerator* IdeDisk::dmaReadCG private
Definition at line 319 of file ide_disk.hh.
Referenced by doDmaRead(), and IdeDisk().
dmaReadEvent
EventFunctionWrapper IdeDisk::dmaReadEvent private
Definition at line 332 of file ide_disk.hh.
Referenced by IdeDisk(), serialize(), and unserialize().
dmaReadFullPages
Stats::Scalar IdeDisk::dmaReadFullPages private
Definition at line 257 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
dmaReadTxs
Stats::Scalar IdeDisk::dmaReadTxs private
Definition at line 259 of file ide_disk.hh.
Referenced by doDmaRead(), and regStats().
dmaReadWaitEvent
EventFunctionWrapper IdeDisk::dmaReadWaitEvent private
Definition at line 320 of file ide_disk.hh.
Referenced by doDmaDataRead(), doDmaRead(), IdeDisk(), serialize(), and unserialize().
dmaState
DmaState_t IdeDisk::dmaState private
Dma state.
Definition at line 241 of file ide_disk.hh.
Referenced by abortDma(), dmaReadDone(), dmaWriteDone(), doDmaTransfer(), reset(), serialize(), startDma(), unserialize(), and updateState().
dmaTransferEvent
EventFunctionWrapper IdeDisk::dmaTransferEvent private
Definition at line 314 of file ide_disk.hh.
Referenced by doDmaTransfer(), serialize(), startDma(), and unserialize().
dmaWriteBytes
Stats::Scalar IdeDisk::dmaWriteBytes private
Definition at line 261 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
dmaWriteCG
ChunkGenerator* IdeDisk::dmaWriteCG private
Definition at line 325 of file ide_disk.hh.
Referenced by doDmaWrite(), and IdeDisk().
dmaWriteEvent
EventFunctionWrapper IdeDisk::dmaWriteEvent private
Definition at line 335 of file ide_disk.hh.
Referenced by IdeDisk(), serialize(), and unserialize().
dmaWriteFullPages
Stats::Scalar IdeDisk::dmaWriteFullPages private
Definition at line 260 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
dmaWriteTxs
Stats::Scalar IdeDisk::dmaWriteTxs private
Definition at line 262 of file ide_disk.hh.
Referenced by doDmaWrite(), and regStats().
dmaWriteWaitEvent
EventFunctionWrapper IdeDisk::dmaWriteWaitEvent private
Definition at line 326 of file ide_disk.hh.
Referenced by doDmaDataWrite(), doDmaWrite(), IdeDisk(), serialize(), and unserialize().
driveID
struct ataparams IdeDisk::driveID private
Drive identification structure for this disk.
Definition at line 221 of file ide_disk.hh.
Referenced by IdeDisk(), and updateState().
drqBytesLeft
uint32_t IdeDisk::drqBytesLeft private
Number of bytes left in DRQ block.
Definition at line 229 of file ide_disk.hh.
Referenced by reset(), serialize(), unserialize(), and updateState().
image
DiskImage* IdeDisk::image protected
The image that contains the data of this disk.
Definition at line 213 of file ide_disk.hh.
Referenced by IdeDisk(), readDisk(), startCommand(), and writeDisk().
intrPending
bool IdeDisk::intrPending private
Interrupt pending.
Definition at line 253 of file ide_disk.hh.
Referenced by intrClear(), intrPost(), reset(), serialize(), unserialize(), and updateState().
nIENBit
bool IdeDisk::nIENBit private
Interrupt enable bit.
Definition at line 237 of file ide_disk.hh.
Referenced by serialize(), unserialize(), and writeControl().
pageBytes
Addr IdeDisk::pageBytes private
Size of OS pages.
Definition at line 245 of file ide_disk.hh.
Referenced by doDmaRead(), and doDmaWrite().
status
uint8_t IdeDisk::status private
Status register.
Definition at line 235 of file ide_disk.hh.
Referenced by readCommand(), readControl(), reset(), serialize(), startCommand(), unserialize(), and updateState().
The documentation for this class was generated from the following files:
dev/storage/ide_disk.hh
dev/storage/ide_disk.cc