gem5: PersistentTable Class Reference
PersistentTable Class Reference
#include <PersistentTable.hh>
Public Member Functions
PersistentTable ()
~PersistentTable ()
void persistentRequestLock (Addr address, MachineID locker, AccessType type)
void persistentRequestUnlock (Addr address, MachineID unlocker)
bool okToIssueStarving (Addr address, MachineID machID) const
MachineID findSmallest (Addr address) const
AccessType typeOfSmallest (Addr address) const
void markEntries (Addr address)
bool isLocked (Addr addr) const
int countStarvingForAddress (Addr addr) const
int countReadStarvingForAddress (Addr addr) const
void print (std::ostream &out) const
Private Types
typedef std::unordered_map< Addr, PersistentTableEntry > AddressMap
Private Member Functions
PersistentTable (const PersistentTable &obj)
PersistentTable & operator= (const PersistentTable &obj)
Private Attributes
AddressMap m_map
Detailed Description
Definition at line 51 of file PersistentTable.hh.
Member Typedef Documentation
AddressMap
typedef std::unordered_map<Addr, PersistentTableEntry> PersistentTable::AddressMap private
Definition at line 80 of file PersistentTable.hh.
Constructor & Destructor Documentation
PersistentTable() [1/2]
PersistentTable::PersistentTable ()
Definition at line 34 of file PersistentTable.cc.
~PersistentTable()
PersistentTable::~PersistentTable ()
Definition at line 38 of file PersistentTable.cc.
PersistentTable() [2/2]
PersistentTable::PersistentTable (const PersistentTable & obj) private
Member Function Documentation
countReadStarvingForAddress()
int PersistentTable::countReadStarvingForAddress (Addr addr) const
Definition at line 181 of file PersistentTable.cc.
References NetDest::count(), ArmISA::i, PersistentTableEntry::m_request_to_write, PersistentTableEntry::m_starving, and makeLineAddress().
countStarvingForAddress()
int PersistentTable::countStarvingForAddress (Addr addr) const
Definition at line 169 of file PersistentTable.cc.
References NetDest::count(), ArmISA::i, PersistentTableEntry::m_starving, and makeLineAddress().
findSmallest()
MachineID PersistentTable::findSmallest (Addr address) const
Definition at line 118 of file PersistentTable.cc.
References ArmISA::i, PersistentTableEntry::m_starving, makeLineAddress(), and NetDest::smallestElement().
isLocked()
bool PersistentTable::isLocked (Addr addr) const
Definition at line 160 of file PersistentTable.cc.
References makeLineAddress().
markEntries()
void PersistentTable::markEntries (Addr address)
Definition at line 143 of file PersistentTable.cc.
References ArmISA::i, NetDest::isEmpty(), PersistentTableEntry::m_marked, PersistentTableEntry::m_starving, and makeLineAddress().
okToIssueStarving()
bool PersistentTable::okToIssueStarving (Addr address, MachineID machID) const
Definition at line 95 of file PersistentTable.cc.
References ArmISA::i, NetDest::isElement(), NetDest::isEmpty(), PersistentTableEntry::m_marked, PersistentTableEntry::m_starving, and makeLineAddress().
operator=()
PersistentTable& PersistentTable::operator= (const PersistentTable & obj) private
persistentRequestLock()
void PersistentTable::persistentRequestLock (Addr address, MachineID locker, AccessType type)
Definition at line 43 of file PersistentTable.cc.
References NetDest::add(), ArmISA::i, NetDest::isElement(), NetDest::isSubset(), PersistentTableEntry::m_marked, PersistentTableEntry::m_request_to_write, PersistentTableEntry::m_starving, makeLineAddress(), X86ISA::present, and MipsISA::r.
persistentRequestUnlock()
void PersistentTable::persistentRequestUnlock (Addr address, MachineID unlocker)
Definition at line 70 of file PersistentTable.cc.
References PersistentTableEntry::m_starving, makeLineAddress(), and NetDest::remove().
print()
void PersistentTable::print (std::ostream & out) const
Definition at line 193 of file PersistentTable.cc.
Referenced by operator<<().
typeOfSmallest()
AccessType PersistentTable::typeOfSmallest (Addr address) const
Definition at line 128 of file PersistentTable.cc.
References ArmISA::i, and makeLineAddress().
Member Data Documentation
m_map
AddressMap PersistentTable::m_map private
Definition at line 81 of file PersistentTable.hh.
The documentation for this class was generated from the following files:
mem/ruby/structures/PersistentTable.hh
mem/ruby/structures/PersistentTable.cc