gem5: IniFile::Entry Class Reference
IniFile::Entry Class Reference
A single key/value pair.
#include <inifile.hh>
Public Member Functions
Entry (const std::string &v)
Constructor.
bool isReferenced ()
Has this entry been used?
const std::string & getValue () const
Fetch the value.
void setValue (const std::string &v)
Set the value.
void appendValue (const std::string &v)
Append the given string to the value.
Private Attributes
std::string value
The entry value.
bool referenced
Has this entry been used?
Detailed Description
A single key/value pair.
Definition at line 61 of file inifile.hh.
Constructor & Destructor Documentation
Entry()
IniFile::Entry::Entry (const std::string & v) inline
Constructor.
Definition at line 68 of file inifile.hh.
Member Function Documentation
appendValue()
void IniFile::Entry::appendValue (const std::string & v) inline
Append the given string to the value.
A space is inserted between the existing value and the new value. Since this operation is typically used with values that are space-separated lists of tokens, this keeps the tokens separate.
Definition at line 87 of file inifile.hh.
References ArmISA::v.
getValue()
const string & IniFile::Entry::getValue () const
Fetch the value.
Definition at line 71 of file inifile.cc.
Referenced by IniFile::find(), isReferenced(), and IniFile::Section::printUnreferenced().
isReferenced()
bool IniFile::Entry::isReferenced () inline
Has this entry been used?
Definition at line 74 of file inifile.hh.
References getValue(), and referenced.
Referenced by IniFile::Section::printUnreferenced().
setValue()
void IniFile::Entry::setValue (const std::string & v) inline
Set the value.
Definition at line 80 of file inifile.hh.
References ArmISA::v.
Member Data Documentation
referenced
bool IniFile::Entry::referenced mutable private
Has this entry been used?
Definition at line 64 of file inifile.hh.
Referenced by isReferenced(), and IniFile::Section::isReferenced().
value
std::string IniFile::Entry::value private
The entry value.
Definition at line 63 of file inifile.hh.
Referenced by IniFile::Section::isReferenced().
The documentation for this class was generated from the following files:
base/inifile.hh
base/inifile.cc