gem5: tlm::tlm_phase Class Reference
tlm::tlm_phase Class Reference
#include <phase.hh>
Public Member Functions
tlm_phase ()
tlm_phase (unsigned int id)
tlm_phase (tlm_phase_enum standard)
tlm_phase & operator= (tlm_phase_enum standard)
operator unsigned int () const
const char * get_name () const
Protected Member Functions
tlm_phase (const std::type_info &type, const char *name)
Private Attributes
unsigned int m_id
Detailed Description
Definition at line 47 of file phase.hh.
Constructor & Destructor Documentation
tlm_phase() [1/4]
tlm::tlm_phase::tlm_phase () inline
Definition at line 67 of file phase.hh.
Referenced by operator unsigned int().
tlm_phase() [2/4]
tlm::tlm_phase::tlm_phase (unsigned int id)
Definition at line 98 of file phase.cc.
tlm_phase() [3/4]
tlm::tlm_phase::tlm_phase (tlm_phase_enum standard) inline
Definition at line 69 of file phase.hh.
tlm_phase() [4/4]
tlm::tlm_phase::tlm_phase (const std::type_info & type, const char * name) protected
Definition at line 101 of file phase.cc.
Member Function Documentation
get_name()
const char * tlm::tlm_phase::get_name () const
Definition at line 106 of file phase.cc.
References m_id.
Referenced by operator unsigned int(), and tlm::operator<<().
operator unsigned int()
tlm::tlm_phase::operator unsigned int () const inline
Definition at line 56 of file phase.hh.
References get_name(), m_id, name(), tlm_phase(), and type.
operator=()
tlm_phase & tlm::tlm_phase::operator= (tlm_phase_enum standard) inline
Definition at line 72 of file phase.hh.
References m_id.
Member Data Documentation
m_id
unsigned int tlm::tlm_phase::m_id private
Definition at line 64 of file phase.hh.
Referenced by get_name(), operator unsigned int(), and operator=().
The documentation for this class was generated from the following files:
systemc/ext/tlm_core/2/generic_payload/phase.hh
systemc/tlm_core/2/generic_payload/phase.cc