gem5: MemoryImage Class Reference
MemoryImage Class Reference
#include <memory_image.hh>
Classes
struct Segment
Public Member Functions
MemoryImage ()
MemoryImage (const Segment &seg)
MemoryImage (std::initializer_list< Segment > segs)
const std::vector< Segment > & segments () const
void addSegment (const Segment &seg)
void addSegments (std::initializer_list< Segment > segs)
bool write (const PortProxy &proxy) const
MemoryImage & move (std::function< Addr(Addr)> mapper)
MemoryImage & offset (Addr by)
MemoryImage & mask (Addr m)
Addr maxAddr () const
Addr minAddr () const
bool contains (Addr addr) const
Private Member Functions
bool writeSegment (const Segment &seg, const PortProxy &proxy) const
Private Attributes
std::vector< Segment > _segments
Detailed Description
Definition at line 48 of file memory_image.hh.
Constructor & Destructor Documentation
MemoryImage() [1/3]
MemoryImage::MemoryImage () inline
Definition at line 82 of file memory_image.hh.
MemoryImage() [2/3]
MemoryImage::MemoryImage (const Segment & seg) inline
Definition at line 84 of file memory_image.hh.
References addSegment().
MemoryImage() [3/3]
MemoryImage::MemoryImage (std::initializer_list< Segment > segs) inline
Definition at line 89 of file memory_image.hh.
References addSegments().
Member Function Documentation
addSegment()
void MemoryImage::addSegment (const Segment & seg) inline
Definition at line 106 of file memory_image.hh.
Referenced by addSegments(), ElfObject::handleLoadableSegment(), and MemoryImage().
addSegments()
void MemoryImage::addSegments (std::initializer_list< Segment > segs) inline
Definition at line 112 of file memory_image.hh.
References addSegment(), move(), X86ISA::seg, and write().
Referenced by MemoryImage().
contains()
bool MemoryImage::contains (Addr addr) const inline
Definition at line 149 of file memory_image.hh.
References X86ISA::seg.
mask()
MemoryImage& MemoryImage::mask (Addr m) inline
Definition at line 126 of file memory_image.hh.
References ArmISA::a, ArmISA::m, and move().
Referenced by AlphaSystem::initState().
maxAddr()
Addr MemoryImage::maxAddr () const inline
Definition at line 131 of file memory_image.hh.
References X86ISA::seg.
Referenced by AlphaProcess::AlphaProcess(), ArmProcess32::ArmProcess32(), ArmProcess64::ArmProcess64(), X86ISA::I386Process::I386Process(), MipsProcess::MipsProcess(), PowerProcess::PowerProcess(), RiscvProcess32::RiscvProcess32(), RiscvProcess64::RiscvProcess64(), Sparc32Process::Sparc32Process(), Sparc64Process::Sparc64Process(), SparcSystem::SparcSystem(), System::System(), and X86ISA::X86_64Process::X86_64Process().
minAddr()
Addr MemoryImage::minAddr () const inline
Definition at line 140 of file memory_image.hh.
References MaxAddr, and X86ISA::seg.
Referenced by AlphaProcess::AlphaProcess(), SparcSystem::SparcSystem(), and System::System().
move()
MemoryImage & MemoryImage::move (std::function< Addr(Addr)> mapper)
Definition at line 59 of file memory_image.cc.
References _segments, and X86ISA::seg.
Referenced by addSegments(), mask(), offset(), and System::System().
offset()
MemoryImage& MemoryImage::offset (Addr by) inline
Definition at line 121 of file memory_image.hh.
References ArmISA::a, and move().
Referenced by MemoryImage::Segment::Segment(), SparcSystem::SparcSystem(), and ElfObject::updateBias().
segments()
const std::vector<Segment>& MemoryImage::segments () const inline
Definition at line 100 of file memory_image.hh.
References _segments.
Referenced by ElfObject::ElfObject().
write()
bool MemoryImage::write (const PortProxy & proxy) const
Definition at line 50 of file memory_image.cc.
References _segments, X86ISA::seg, and writeSegment().
Referenced by addSegments(), PowerProcess::argsInit(), BareMetalRiscvSystem::initState(), AlphaSystem::initState(), Process::initState(), ArmSystem::initState(), System::initState(), and SparcSystem::SparcSystem().
writeSegment()
bool MemoryImage::writeSegment (const Segment & seg, const PortProxy & proxy) const private
Definition at line 36 of file memory_image.cc.
References MemoryImage::Segment::base, MemoryImage::Segment::data, PortProxy::memsetBlob(), MemoryImage::Segment::size, and PortProxy::writeBlob().
Referenced by write().
Member Data Documentation
_segments
std::vector<Segment> MemoryImage::_segments private
Definition at line 95 of file memory_image.hh.
Referenced by move(), segments(), and write().
The documentation for this class was generated from the following files:
base/loader/memory_image.hh
base/loader/memory_image.cc