gem5: sc_dt::sc_global< T > Class Template Reference
sc_dt::sc_global< T > Class Template Reference
#include <sc_context.hh>
Public Member Functions
const T *& value_ptr ()
Static Public Member Functions
static sc_global< T > * instance ()
Private Member Functions
sc_global ()
void update ()
Private Attributes
std::map< void *, const T * > m_map
void * m_proc
const T * m_value_ptr
Static Private Attributes
static sc_global< T > * m_instance = 0
Detailed Description
template<class T>
class sc_dt::sc_global< T >
Definition at line 73 of file sc_context.hh.
Constructor & Destructor Documentation
sc_global()
template<class T > sc_dt::sc_global< T >::sc_global () inline private
Definition at line 169 of file sc_context.hh.
Member Function Documentation
instance()
template<class T > sc_global< T > * sc_dt::sc_global< T >::instance () inline static
Definition at line 195 of file sc_context.hh.
References sc_dt::sc_global< T >::m_instance.
Referenced by sc_dt::sc_context< T >::default_value().
update()
template<class T > void sc_dt::sc_global< T >::update () inline private
Definition at line 178 of file sc_context.hh.
References sc_dt::sc_global< T >::m_map, sc_dt::sc_global< T >::m_proc, sc_dt::sc_global< T >::m_value_ptr, MipsISA::p, and sc_core::sc_get_current_process_handle().
Referenced by sc_dt::sc_global< T >::value_ptr().
value_ptr()
template<class T > const T *& sc_dt::sc_global< T >::value_ptr () inline
Definition at line 206 of file sc_context.hh.
References sc_dt::sc_global< T >::m_value_ptr, and sc_dt::sc_global< T >::update().
Member Data Documentation
m_instance
template<class T> sc_global< T > * sc_dt::sc_global< T >::m_instance = 0 static private
Definition at line 104 of file sc_context.hh.
Referenced by sc_dt::sc_global< T >::instance().
m_map
template<class T> std::map<void *, const T *> sc_dt::sc_global< T >::m_map private
Definition at line 106 of file sc_context.hh.
Referenced by sc_dt::sc_global< T >::update().
m_proc
template<class T> void* sc_dt::sc_global< T >::m_proc private
Definition at line 107 of file sc_context.hh.
Referenced by sc_dt::sc_global< T >::update().
m_value_ptr
template<class T> const T* sc_dt::sc_global< T >::m_value_ptr private
Definition at line 108 of file sc_context.hh.
Referenced by sc_dt::sc_global< T >::update(), and sc_dt::sc_global< T >::value_ptr().
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_context.hh