gem5: VGic Class Reference
VGic Class Reference
#include <vgic.hh>
Public Types
typedef VGicParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
VGic (const Params *p)
~VGic ()
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
void processPostVIntEvent (uint32_t cpu)
Post interrupt to CPU.
BitUnion32 (ListReg) Bitfield< 31 > HW
EndBitUnion (ListReg) BitUnion32(HCR) Bitfield< 31
EndBitUnion (HCR) BitUnion32(VCTLR) Bitfield< 9 > EOImode
Tick readVCpu (PacketPtr pkt)
Tick readCtrl (PacketPtr pkt)
Tick writeVCpu (PacketPtr pkt)
Tick writeCtrl (PacketPtr pkt)
void updateIntState (ContextID ctx_id)
uint32_t getMISR (struct vcpuIntData *vid)
void postVInt (uint32_t cpu, Tick when)
void unPostVInt (uint32_t cpu)
void postMaintInt (uint32_t cpu)
void unPostMaintInt (uint32_t cpu)
unsigned int lrPending (struct vcpuIntData *vid)
unsigned int lrValid (struct vcpuIntData *vid)
int findHighestPendingLR (struct vcpuIntData *vid)
Returns LR index or -1 if none pending.
int findLRForVIRQ (struct vcpuIntData *vid, int virq, int vcpu)
Private Attributes
const uint32_t gicvIIDR
EventFunctionWrapper * postVIntEvent [VGIC_CPU_MAX]
bool maintIntPosted [VGIC_CPU_MAX]
bool vIntPosted [VGIC_CPU_MAX]
Platform * platform
BaseGic * gic
Addr vcpuAddr
Addr hvAddr
Tick pioDelay
int maintInt
Bitfield< 30 > Grp1
Bitfield< 29, 28 > State
Bitfield< 27, 23 > Priority
Bitfield< 19 > EOI
Bitfield< 12, 10 > CpuID
Bitfield< 9, 0 > VirtualID
EOICount
Bitfield< 7 > VGrp1DIE
Bitfield< 6 > VGrp1EIE
Bitfield< 5 > VGrp0DIE
Bitfield< 4 > VGrp0EIE
Bitfield< 3 > NPIE
Bitfield< 2 > LRENPIE
Bitfield< 1 > UIE
Bitfield< 0 > En
Bitfield< 4 > CPBR
Bitfield< 3 > FIQEn
Bitfield< 2 > AckCtl
Bitfield< 1 > EnGrp1
EndBitUnion(VCTLR) struct vcpuIntData struct std::array< vcpuIntData, VGIC_CPU_MAX > vcpuData
Static Private Attributes
static const int VGIC_CPU_MAX = 256
static const int NUM_LR = 4
static const int GICH_SIZE = 0x200
static const int GICH_REG_SIZE = 0x2000
static const int GICH_HCR = 0x000
static const int GICH_VTR = 0x004
static const int GICH_VMCR = 0x008
static const int GICH_MISR = 0x010
static const int GICH_EISR0 = 0x020
static const int GICH_EISR1 = 0x024
static const int GICH_ELSR0 = 0x030
static const int GICH_ELSR1 = 0x034
static const int GICH_APR0 = 0x0f0
static const int GICH_LR0 = 0x100
static const int GICH_LR1 = 0x104
static const int GICH_LR2 = 0x108
static const int GICH_LR3 = 0x10c
static const int GICV_SIZE = 0x2000
static const int GICV_CTLR = 0x000
static const int GICV_PMR = 0x004
static const int GICV_BPR = 0x008
static const int GICV_IAR = 0x00c
static const int GICV_EOIR = 0x010
static const int GICV_RPR = 0x014
static const int GICV_HPPIR = 0x018
static const int GICV_ABPR = 0x01c
static const int GICV_AIAR = 0x020
static const int GICV_AEOIR = 0x024
static const int GICV_AHPPIR = 0x028
static const int GICV_APR0 = 0x0d0
static const int GICV_IIDR = 0x0fc
static const int GICV_DIR = 0x1000
static const uint32_t LR_PENDING = 1
static const uint32_t LR_ACTIVE = 2
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 65 of file vgic.hh.
Member Typedef Documentation
Params
typedef VGicParams VGic::Params
Definition at line 191 of file vgic.hh.
Constructor & Destructor Documentation
VGic()
VGic::VGic (const Params * p)
Definition at line 49 of file vgic.cc.
References maintIntPosted, System::numRunningContexts(), postVIntEvent, processPostVIntEvent(), PioDevice::sys, VGIC_CPU_MAX, vIntPosted, and X86ISA::x.
Referenced by params(), and unserialize().
~VGic()
VGic::~VGic ()
Definition at line 64 of file vgic.cc.
References postVIntEvent, VGIC_CPU_MAX, and X86ISA::x.
Referenced by params().
Member Function Documentation
BitUnion32()
VGic::BitUnion32 (ListReg) private
EndBitUnion() [1/2]
VGic::EndBitUnion (ListReg) private
EndBitUnion() [2/2]
VGic::EndBitUnion (HCR) private
findHighestPendingLR()
int VGic::findHighestPendingLR (struct vcpuIntData * vid) inline private
Returns LR index or -1 if none pending.
Definition at line 242 of file vgic.hh.
References ArmISA::i, NUM_LR, and MipsISA::p.
Referenced by readVCpu().
findLRForVIRQ()
int VGic::findLRForVIRQ (struct vcpuIntData * vid, int virq, int vcpu) inline private
Definition at line 255 of file vgic.hh.
References ArmISA::i, and NUM_LR.
Referenced by writeVCpu().
getAddrRanges()
AddrRangeList VGic::getAddrRanges () const override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 449 of file vgic.cc.
References GICH_REG_SIZE, GICV_SIZE, hvAddr, RangeSize(), and vcpuAddr.
Referenced by params().
getMISR()
uint32_t VGic::getMISR (struct vcpuIntData * vid) private
Definition at line 351 of file vgic.cc.
References lrPending(), and lrValid().
Referenced by params(), readCtrl(), and updateIntState().
lrPending()
unsigned int VGic::lrPending (struct vcpuIntData * vid) inline private
Definition at line 222 of file vgic.hh.
References ArmISA::i, and NUM_LR.
Referenced by getMISR(), and updateIntState().
lrValid()
unsigned int VGic::lrValid (struct vcpuIntData * vid) inline private
Definition at line 231 of file vgic.hh.
References ArmISA::i, and NUM_LR.
Referenced by getMISR().
params()
const Params* VGic::params () const inline
Definition at line 193 of file vgic.hh.
References SimObject::_params, getAddrRanges(), getMISR(), MipsISA::p, postMaintInt(), postVInt(), read(), readCtrl(), readVCpu(), serialize(), unPostMaintInt(), unPostVInt(), unserialize(), updateIntState(), VGic(), write(), writeCtrl(), writeVCpu(), and ~VGic().
postMaintInt()
void VGic::postMaintInt (uint32_t cpu) private
Definition at line 386 of file vgic.cc.
References DPRINTF, gic, maintInt, and BaseGic::sendPPInt().
Referenced by params(), and updateIntState().
postVInt()
void VGic::postVInt (uint32_t cpu, Tick when) private
Definition at line 364 of file vgic.cc.
References DPRINTF, EventManager::eventq, postVIntEvent, and EventQueue::schedule().
Referenced by params(), and updateIntState().
processPostVIntEvent()
void VGic::processPostVIntEvent (uint32_t cpu) private
Post interrupt to CPU.
Definition at line 379 of file vgic.cc.
References ArmISA::INT_VIRT_IRQ, Platform::intrctrl, platform, and IntrControl::post().
Referenced by VGic().
read()
Tick VGic::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 71 of file vgic.cc.
References addr, Packet::getAddr(), GICH_REG_SIZE, GICV_SIZE, hvAddr, panic, readCtrl(), readVCpu(), and vcpuAddr.
Referenced by params().
readCtrl()
Tick VGic::readCtrl (PacketPtr pkt) private
Definition at line 144 of file vgic.cc.
References DPRINTF, Packet::getAddr(), getMISR(), GICH_APR0, GICH_EISR0, GICH_EISR1, GICH_ELSR0, GICH_ELSR1, GICH_HCR, GICH_LR0, GICH_LR1, GICH_LR2, GICH_LR3, GICH_MISR, GICH_VMCR, GICH_VTR, hvAddr, ArmISA::i, Packet::makeAtomicResponse(), NUM_LR, panic, pioDelay, Packet::req, Packet::setLE(), vcpuData, VGIC_CPU_MAX, and warn_once.
Referenced by params(), and read().
readVCpu()
Tick VGic::readVCpu (PacketPtr pkt) private
Definition at line 97 of file vgic.cc.
References DPRINTF, findHighestPendingLR(), Packet::getAddr(), GICV_CTLR, GICV_IAR, GICV_IIDR, gicvIIDR, ArmISA::i, LR_ACTIVE, Packet::makeAtomicResponse(), panic, pioDelay, Packet::req, Packet::setLE(), updateIntState(), vcpuAddr, vcpuData, and VGIC_CPU_MAX.
Referenced by params(), and read().
serialize()
void VGic::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 458 of file vgic.cc.
References csprintf(), DPRINTF, hvAddr, ArmISA::i, maintInt, maintIntPosted, NUM_LR, paramOut(), pioDelay, postVIntEvent, serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, Serializable::serializeSection(), vcpuAddr, vcpuData, VGIC_CPU_MAX, vIntPosted, and Event::when().
Referenced by params().
unPostMaintInt()
void VGic::unPostMaintInt (uint32_t cpu) private
Definition at line 394 of file vgic.cc.
References BaseGic::clearPPInt(), DPRINTF, gic, and maintInt.
Referenced by params(), and updateIntState().
unPostVInt()
void VGic::unPostVInt (uint32_t cpu) private
Definition at line 372 of file vgic.cc.
References IntrControl::clear(), DPRINTF, ArmISA::INT_VIRT_IRQ, Platform::intrctrl, and platform.
Referenced by params(), and updateIntState().
unserialize()
void VGic::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 516 of file vgic.cc.
References csprintf(), DPRINTF, hvAddr, ArmISA::i, maintInt, maintIntPosted, NUM_LR, paramIn(), pioDelay, postVIntEvent, EventManager::schedule(), unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_SCALAR, vcpuAddr, vcpuData, VGic(), VGIC_CPU_MAX, and vIntPosted.
Referenced by params().
updateIntState()
void VGic::updateIntState (ContextID ctx_id) private
Definition at line 404 of file vgic.cc.
References curTick(), getMISR(), ArmISA::i, lrPending(), maintIntPosted, NUM_LR, System::numRunningContexts(), postMaintInt(), postVInt(), PioDevice::sys, unPostMaintInt(), unPostVInt(), vcpuData, VGIC_CPU_MAX, and vIntPosted.
Referenced by params(), readVCpu(), writeCtrl(), and writeVCpu().
write()
Tick VGic::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 84 of file vgic.cc.
References addr, Packet::getAddr(), GICH_REG_SIZE, GICV_SIZE, hvAddr, panic, vcpuAddr, writeCtrl(), and writeVCpu().
Referenced by params().
writeCtrl()
Tick VGic::writeCtrl (PacketPtr pkt) private
Definition at line 287 of file vgic.cc.
References ArmISA::d, DPRINTF, Packet::getAddr(), Packet::getLE(), GICH_APR0, GICH_HCR, GICH_LR0, GICH_LR1, GICH_LR2, GICH_LR3, GICH_VMCR, hvAddr, Packet::makeAtomicResponse(), panic, pioDelay, Packet::req, updateIntState(), vcpuData, VGIC_CPU_MAX, and warn_once.
Referenced by params(), and write().
writeVCpu()
Tick VGic::writeVCpu (PacketPtr pkt) private
Definition at line 238 of file vgic.cc.
References DPRINTF, findLRForVIRQ(), Packet::getAddr(), Packet::getLE(), GICV_CTLR, GICV_EOIR, GICV_PMR, ArmISA::i, Packet::makeAtomicResponse(), panic, pioDelay, Packet::req, updateIntState(), vcpuAddr, vcpuData, VGIC_CPU_MAX, and MipsISA::w.
Referenced by params(), and write().
Member Data Documentation
AckCtl
Bitfield<2> VGic::AckCtl private
Definition at line 149 of file vgic.hh.
CPBR
Bitfield<4> VGic::CPBR private
Definition at line 147 of file vgic.hh.
CpuID
Bitfield<12,10> VGic::CpuID private
Definition at line 129 of file vgic.hh.
En
Bitfield< 0 > VGic::En private
Definition at line 142 of file vgic.hh.
EnGrp1
Bitfield<1> VGic::EnGrp1 private
Definition at line 150 of file vgic.hh.
EOI
Bitfield<19> VGic::EOI private
Definition at line 128 of file vgic.hh.
EOICount
VGic::EOICount private
Definition at line 134 of file vgic.hh.
FIQEn
Bitfield<3> VGic::FIQEn private
Definition at line 148 of file vgic.hh.
gic
BaseGic* VGic::gic private
Definition at line 116 of file vgic.hh.
Referenced by postMaintInt(), and unPostMaintInt().
GICH_APR0
const int VGic::GICH_APR0 = 0x0f0 static private
Definition at line 82 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_EISR0
const int VGic::GICH_EISR0 = 0x020 static private
Definition at line 78 of file vgic.hh.
Referenced by readCtrl().
GICH_EISR1
const int VGic::GICH_EISR1 = 0x024 static private
Definition at line 79 of file vgic.hh.
Referenced by readCtrl().
GICH_ELSR0
const int VGic::GICH_ELSR0 = 0x030 static private
Definition at line 80 of file vgic.hh.
Referenced by readCtrl().
GICH_ELSR1
const int VGic::GICH_ELSR1 = 0x034 static private
Definition at line 81 of file vgic.hh.
Referenced by readCtrl().
GICH_HCR
const int VGic::GICH_HCR = 0x000 static private
Definition at line 74 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_LR0
const int VGic::GICH_LR0 = 0x100 static private
Definition at line 83 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_LR1
const int VGic::GICH_LR1 = 0x104 static private
Definition at line 84 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_LR2
const int VGic::GICH_LR2 = 0x108 static private
Definition at line 85 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_LR3
const int VGic::GICH_LR3 = 0x10c static private
Definition at line 86 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_MISR
const int VGic::GICH_MISR = 0x010 static private
Definition at line 77 of file vgic.hh.
Referenced by readCtrl().
GICH_REG_SIZE
const int VGic::GICH_REG_SIZE = 0x2000 static private
Definition at line 72 of file vgic.hh.
Referenced by getAddrRanges(), read(), and write().
GICH_SIZE
const int VGic::GICH_SIZE = 0x200 static private
Definition at line 71 of file vgic.hh.
GICH_VMCR
const int VGic::GICH_VMCR = 0x008 static private
Definition at line 76 of file vgic.hh.
Referenced by readCtrl(), and writeCtrl().
GICH_VTR
const int VGic::GICH_VTR = 0x004 static private
Definition at line 75 of file vgic.hh.
Referenced by readCtrl().
GICV_ABPR
const int VGic::GICV_ABPR = 0x01c static private
Definition at line 96 of file vgic.hh.
GICV_AEOIR
const int VGic::GICV_AEOIR = 0x024 static private
Definition at line 98 of file vgic.hh.
GICV_AHPPIR
const int VGic::GICV_AHPPIR = 0x028 static private
Definition at line 99 of file vgic.hh.
GICV_AIAR
const int VGic::GICV_AIAR = 0x020 static private
Definition at line 97 of file vgic.hh.
GICV_APR0
const int VGic::GICV_APR0 = 0x0d0 static private
Definition at line 100 of file vgic.hh.
GICV_BPR
const int VGic::GICV_BPR = 0x008 static private
Definition at line 91 of file vgic.hh.
GICV_CTLR
const int VGic::GICV_CTLR = 0x000 static private
Definition at line 89 of file vgic.hh.
Referenced by readVCpu(), and writeVCpu().
GICV_DIR
const int VGic::GICV_DIR = 0x1000 static private
Definition at line 102 of file vgic.hh.
GICV_EOIR
const int VGic::GICV_EOIR = 0x010 static private
Definition at line 93 of file vgic.hh.
Referenced by writeVCpu().
GICV_HPPIR
const int VGic::GICV_HPPIR = 0x018 static private
Definition at line 95 of file vgic.hh.
GICV_IAR
const int VGic::GICV_IAR = 0x00c static private
Definition at line 92 of file vgic.hh.
Referenced by readVCpu().
GICV_IIDR
const int VGic::GICV_IIDR = 0x0fc static private
Definition at line 101 of file vgic.hh.
Referenced by readVCpu().
GICV_PMR
const int VGic::GICV_PMR = 0x004 static private
Definition at line 90 of file vgic.hh.
Referenced by writeVCpu().
GICV_RPR
const int VGic::GICV_RPR = 0x014 static private
Definition at line 94 of file vgic.hh.
GICV_SIZE
const int VGic::GICV_SIZE = 0x2000 static private
Definition at line 88 of file vgic.hh.
Referenced by getAddrRanges(), read(), and write().
gicvIIDR
const uint32_t VGic::gicvIIDR private
Definition at line 106 of file vgic.hh.
Referenced by readVCpu().
Grp1
Bitfield<30> VGic::Grp1 private
Definition at line 125 of file vgic.hh.
hvAddr
Addr VGic::hvAddr private
Definition at line 119 of file vgic.hh.
Referenced by getAddrRanges(), read(), readCtrl(), serialize(), unserialize(), write(), and writeCtrl().
LR_ACTIVE
const uint32_t VGic::LR_ACTIVE = 2 static private
Definition at line 105 of file vgic.hh.
Referenced by readVCpu().
LR_PENDING
const uint32_t VGic::LR_PENDING = 1 static private
Definition at line 104 of file vgic.hh.
LRENPIE
Bitfield<2> VGic::LRENPIE private
Definition at line 140 of file vgic.hh.
maintInt
int VGic::maintInt private
Definition at line 121 of file vgic.hh.
Referenced by postMaintInt(), serialize(), unPostMaintInt(), and unserialize().
maintIntPosted
bool VGic::maintIntPosted[VGIC_CPU_MAX] private
Definition at line 112 of file vgic.hh.
Referenced by serialize(), unserialize(), updateIntState(), and VGic().
NPIE
Bitfield<3> VGic::NPIE private
Definition at line 139 of file vgic.hh.
NUM_LR
const int VGic::NUM_LR = 4 static private
Definition at line 69 of file vgic.hh.
Referenced by findHighestPendingLR(), findLRForVIRQ(), lrPending(), lrValid(), readCtrl(), serialize(), unserialize(), and updateIntState().
pioDelay
Tick VGic::pioDelay private
Definition at line 120 of file vgic.hh.
Referenced by readCtrl(), readVCpu(), serialize(), unserialize(), writeCtrl(), and writeVCpu().
platform
Platform* VGic::platform private
Definition at line 115 of file vgic.hh.
Referenced by processPostVIntEvent(), and unPostVInt().
postVIntEvent
EventFunctionWrapper* VGic::postVIntEvent[VGIC_CPU_MAX] private
Definition at line 111 of file vgic.hh.
Referenced by postVInt(), serialize(), unserialize(), VGic(), and ~VGic().
Priority
Bitfield<27,23> VGic::Priority private
Definition at line 127 of file vgic.hh.
State
Bitfield<29,28> VGic::State private
Definition at line 126 of file vgic.hh.
UIE
Bitfield<1> VGic::UIE private
Definition at line 141 of file vgic.hh.
vcpuAddr
Addr VGic::vcpuAddr private
Definition at line 118 of file vgic.hh.
Referenced by getAddrRanges(), read(), readVCpu(), serialize(), unserialize(), write(), and writeVCpu().
vcpuData
EndBitUnion (VCTLR) struct vcpuIntData struct std::array< vcpuIntData, VGIC_CPU_MAX > VGic::vcpuData private
Definition at line 188 of file vgic.hh.
Referenced by readCtrl(), readVCpu(), serialize(), unserialize(), updateIntState(), writeCtrl(), and writeVCpu().
VGIC_CPU_MAX
const int VGic::VGIC_CPU_MAX = 256 static private
Definition at line 68 of file vgic.hh.
Referenced by readCtrl(), readVCpu(), serialize(), unserialize(), updateIntState(), VGic(), writeCtrl(), writeVCpu(), and ~VGic().
VGrp0DIE
Bitfield<5> VGic::VGrp0DIE private
Definition at line 137 of file vgic.hh.
VGrp0EIE
Bitfield<4> VGic::VGrp0EIE private
Definition at line 138 of file vgic.hh.
VGrp1DIE
Bitfield<7> VGic::VGrp1DIE private
Definition at line 135 of file vgic.hh.
VGrp1EIE
Bitfield<6> VGic::VGrp1EIE private
Definition at line 136 of file vgic.hh.
vIntPosted
bool VGic::vIntPosted[VGIC_CPU_MAX] private
Definition at line 113 of file vgic.hh.
Referenced by serialize(), unserialize(), updateIntState(), and VGic().
VirtualID
Bitfield<9,0> VGic::VirtualID private
Definition at line 130 of file vgic.hh.
The documentation for this class was generated from the following files:
dev/arm/vgic.hh
dev/arm/vgic.cc