gem5: PowerISA::RemoteGDB::PowerGdbRegCache Class Reference
PowerISA::RemoteGDB::PowerGdbRegCache Class Reference
#include <remote_gdb.hh>
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct {
uint32_t gpr [NumIntArchRegs]
uint64_t fpr [NumFloatArchRegs]
uint32_t pc
uint32_t msr
uint32_t cr
uint32_t lr
uint32_t ctr
uint32_t xer
} r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 53 of file remote_gdb.hh.
Member Function Documentation
data()
char* PowerISA::RemoteGDB::PowerGdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 68 of file remote_gdb.hh.
References r.
getRegs()
void RemoteGDB::PowerGdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 175 of file remote_gdb.cc.
References DPRINTF, htobe(), ArmISA::i, PowerISA::INTREG_CR, PowerISA::INTREG_CTR, PowerISA::INTREG_LR, PowerISA::INTREG_XER, PowerISA::NumFloatArchRegs, PowerISA::NumIntArchRegs, ThreadContext::pcState(), MipsISA::r, ThreadContext::readFloatReg(), and ThreadContext::readIntReg().
Referenced by size().
name()
const std::string PowerISA::RemoteGDB::PowerGdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 73 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::PowerGdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 198 of file remote_gdb.cc.
References betoh(), DPRINTF, ArmISA::i, PowerISA::INTREG_CR, PowerISA::INTREG_CTR, PowerISA::INTREG_LR, PowerISA::INTREG_XER, PowerISA::NumFloatArchRegs, PowerISA::NumIntArchRegs, ThreadContext::pcState(), MipsISA::r, ThreadContext::setFloatReg(), and ThreadContext::setIntReg().
Referenced by size().
size()
size_t PowerISA::RemoteGDB::PowerGdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 69 of file remote_gdb.hh.
References getRegs(), r, and setRegs().
Member Data Documentation
cr
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::cr
Definition at line 62 of file remote_gdb.hh.
ctr
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::ctr
Definition at line 64 of file remote_gdb.hh.
fpr
uint64_t PowerISA::RemoteGDB::PowerGdbRegCache::fpr[NumFloatArchRegs]
Definition at line 59 of file remote_gdb.hh.
gpr
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::gpr[NumIntArchRegs]
Definition at line 58 of file remote_gdb.hh.
lr
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::lr
Definition at line 63 of file remote_gdb.hh.
msr
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::msr
Definition at line 61 of file remote_gdb.hh.
pc
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::pc
Definition at line 60 of file remote_gdb.hh.
r
struct { ... } PowerISA::RemoteGDB::PowerGdbRegCache::r
Referenced by data(), and size().
xer
uint32_t PowerISA::RemoteGDB::PowerGdbRegCache::xer
Definition at line 65 of file remote_gdb.hh.
The documentation for this class was generated from the following files:
arch/power/remote_gdb.hh
arch/power/remote_gdb.cc