gem5: Topology Class Reference
Topology Class Reference
#include <Topology.hh>
Public Member Functions
Topology (uint32_t num_routers, const std::vector< BasicExtLink *> &ext_links, const std::vector< BasicIntLink *> &int_links)
uint32_t numSwitches () const
void createLinks (Network *net)
void print (std::ostream &out) const
Private Member Functions
void addLink (SwitchID src, SwitchID dest, BasicLink *link, PortDirection src_outport_dirn="", PortDirection dest_inport_dirn="")
void makeLink (Network *net, SwitchID src, SwitchID dest, const NetDest &routing_table_entry)
void extend_shortest_path (Matrix &current_dist, Matrix &latencies, Matrix &inter_switches)
std::vector< std::vector< int > > shortest_path (const Matrix &weights, Matrix &latencies, Matrix &inter_switches)
bool link_is_shortest_path_to_node (SwitchID src, SwitchID next, SwitchID final, const Matrix &weights, const Matrix &dist)
NetDest shortest_path_to_node (SwitchID src, SwitchID next, const Matrix &weights, const Matrix &dist)
Private Attributes
const uint32_t m_nodes
const uint32_t m_number_of_switches
std::vector< BasicExtLink * > m_ext_link_vector
std::vector< BasicIntLink * > m_int_link_vector
LinkMap m_link_map
Detailed Description
Definition at line 66 of file Topology.hh.
Constructor & Destructor Documentation
Topology()
Topology::Topology (uint32_t num_routers, const std::vector< BasicExtLink *> & ext_links, const std::vector< BasicIntLink *> & int_links)
Definition at line 51 of file Topology.cc.
References addLink(), AbstractController::getType(), AbstractController::getVersion(), ArmISA::i, m_int_link_vector, m_nodes, BasicRouter::params(), BasicExtLink::params(), and BasicIntLink::params().
Member Function Documentation
addLink()
void Topology::addLink (SwitchID src, SwitchID dest, BasicLink * link, PortDirection src_outport_dirn = "", PortDirection dest_inport_dirn = "") private
Definition at line 162 of file Topology.cc.
References LinkEntry::dst_inport_dirn, LinkEntry::link, m_link_map, m_nodes, m_number_of_switches, and LinkEntry::src_outport_dirn.
Referenced by Topology().
createLinks()
void Topology::createLinks (Network * net)
Definition at line 109 of file Topology.cc.
References Stats::dist, ArmISA::i, INFINITE_LATENCY, ArmISA::j, BasicLink::m_latency, m_link_map, BasicLink::m_weight, makeLink(), shortest_path(), and shortest_path_to_node().
Referenced by SimpleNetwork::init(), and GarnetNetwork::init().
extend_shortest_path()
void Topology::extend_shortest_path (Matrix & current_dist, Matrix & latencies, Matrix & inter_switches) private
Definition at line 221 of file Topology.cc.
References ArmISA::i, ArmISA::j, and MipsISA::k.
Referenced by shortest_path().
link_is_shortest_path_to_node()
bool Topology::link_is_shortest_path_to_node (SwitchID src, SwitchID next, SwitchID final, const Matrix & weights, const Matrix & dist) private
Definition at line 268 of file Topology.cc.
Referenced by shortest_path_to_node().
makeLink()
void Topology::makeLink (Network * net, SwitchID src, SwitchID dest, const NetDest & routing_table_entry) private
Definition at line 181 of file Topology.cc.
References LinkEntry::dst_inport_dirn, LinkEntry::link, m_link_map, m_nodes, Network::makeExtInLink(), Network::makeExtOutLink(), Network::makeInternalLink(), and LinkEntry::src_outport_dirn.
Referenced by createLinks().
numSwitches()
uint32_t Topology::numSwitches () const inline
Definition at line 72 of file Topology.hh.
print()
void Topology::print (std::ostream & out) const inline
Definition at line 74 of file Topology.hh.
References Stats::dist, LinkEntry::link, and LinkEntry::src_outport_dirn.
Referenced by operator<<().
shortest_path()
Matrix Topology::shortest_path (const Matrix & weights, Matrix & latencies, Matrix & inter_switches) private
Definition at line 259 of file Topology.cc.
References Stats::dist, and extend_shortest_path().
Referenced by createLinks().
shortest_path_to_node()
NetDest Topology::shortest_path_to_node (SwitchID src, SwitchID next, const Matrix & weights, const Matrix & dist) private
Definition at line 276 of file Topology.cc.
References NetDest::add(), ArmISA::d, DPRINTF, ArmISA::i, link_is_shortest_path_to_node(), and ArmISA::m.
Referenced by createLinks().
Member Data Documentation
m_ext_link_vector
std::vector<BasicExtLink*> Topology::m_ext_link_vector private
Definition at line 99 of file Topology.hh.
m_int_link_vector
std::vector<BasicIntLink*> Topology::m_int_link_vector private
Definition at line 100 of file Topology.hh.
Referenced by Topology().
m_link_map
LinkMap Topology::m_link_map private
Definition at line 102 of file Topology.hh.
Referenced by addLink(), createLinks(), and makeLink().
m_nodes
const uint32_t Topology::m_nodes private
Definition at line 96 of file Topology.hh.
Referenced by addLink(), makeLink(), and Topology().
m_number_of_switches
const uint32_t Topology::m_number_of_switches private
Definition at line 97 of file Topology.hh.
Referenced by addLink().
The documentation for this class was generated from the following files:
mem/ruby/network/Topology.hh
mem/ruby/network/Topology.cc