gem5: m5::Coroutine< Arg, Ret > Class Template Reference
m5::Coroutine< Arg, Ret > Class Template Reference
This template defines a Coroutine wrapper type with a Boost-like interface.
#include <coroutine.hh>
Classes
class CallerType
CallerType: A reference to an object of this class will be passed to the coroutine task.
struct Empty
Public Member Functions
Coroutine ()=delete
Coroutine (const Coroutine &rhs)=delete
Coroutine & operator= (const Coroutine &rhs)=delete
Coroutine (std::function< void(CallerType &)> f, bool run_coroutine=true)
Coroutine constructor.
virtual ~Coroutine ()
template<typename T = Arg>
Coroutine & operator() (typename std::enable_if< !std::is_same< T, void >::value, T >::type param)
Coroutine interface.
template<typename T = Arg>
std::enable_if< std::is_same< T, void >::value, Coroutine >::type & operator() ()
operator() is the way we can jump inside the coroutine.
template<typename T = Ret>
std::enable_if<!std::is_same< T, void >::value, T >::type get ()
get() is the way we can extrapolate return values (yielded) from the coroutine.
operator bool () const
Check if coroutine is still running.
Public Member Functions inherited from Fiber
Fiber (size_t stack_size=DefaultStackSize)
stack_size is the size of the stack available to this fiber.
Fiber (Fiber *link, size_t stack_size=DefaultStackSize)
virtual ~Fiber ()
void run ()
Start executing the fiber represented by this object.
bool finished () const
Returns whether the "main" function of this fiber has finished.
bool started () const
Returns whether the "main" function of this fiber has started.
Private Types
using ArgChannel = typename std::conditional< std::is_same< Arg, void >::value, Empty, std::stack< Arg > >::type
using RetChannel = typename std::conditional< std::is_same< Ret, void >::value, Empty, std::stack< Ret > >::type
Private Member Functions
void main () override
Overriding base (Fiber) main.
void call ()
Private Attributes
ArgChannel argsChannel
Arguments for the coroutine.
std::function< void(CallerType &)> task
Coroutine task.
CallerType caller
Coroutine caller.
Additional Inherited Members
Static Public Member Functions inherited from Fiber
static Fiber * currentFiber ()
Get a pointer to the current running Fiber.
static Fiber * primaryFiber ()
Get a pointer to the primary Fiber.
Static Public Attributes inherited from Fiber
static const size_t DefaultStackSize = 0x50000
Protected Member Functions inherited from Fiber
void setStarted ()
Detailed Description
template<typename Arg, typename Ret>
class m5::Coroutine< Arg, Ret >
This template defines a Coroutine wrapper type with a Boost-like interface.
It is built on top of the gem5 fiber class. The two template parameters (Arg and Ret) are the coroutine argument and coroutine return types which are passed between the coroutine and the caller via operator() and get() method. This implementation doesn't support passing multiple values, so a tuple must be used in that scenario.
Most methods are templatized since it is relevant to distinguish the cases where one or both of the template parameters are void
Definition at line 64 of file coroutine.hh.
Member Typedef Documentation
ArgChannel
template<typename Arg, typename Ret> using m5::Coroutine< Arg, Ret >::ArgChannel = typename std::conditional< std::is_same<Arg, void>::value, Empty, std::stack<Arg> >::type private
Definition at line 72 of file coroutine.hh.
RetChannel
template<typename Arg, typename Ret> using m5::Coroutine< Arg, Ret >::RetChannel = typename std::conditional< std::is_same<Ret, void>::value, Empty, std::stack<Ret> >::type private
Definition at line 75 of file coroutine.hh.
Constructor & Destructor Documentation
Coroutine() [1/3]
template<typename Arg, typename Ret> m5::Coroutine< Arg, Ret >::Coroutine () delete
Coroutine() [2/3]
template<typename Arg, typename Ret> m5::Coroutine< Arg, Ret >::Coroutine (const Coroutine< Arg, Ret > & rhs) delete
Coroutine() [3/3]
template<typename Arg, typename Ret> m5::Coroutine< Arg, Ret >::Coroutine (std::function< void(CallerType &)> f, bool run_coroutine = true) inline
Coroutine constructor.
The only way to construct a coroutine is to pass it the routine it needs to run. The first argument of the function should be a reference to the Coroutine<Arg,Ret>::caller_type which the routine will use as a way for yielding to the caller. The optional second boolean argument controls if the Coroutine should be run on creation, which mimics Boost's Coroutine semantics by default. This can be disabled as an optimization to avoid unnecessary context switches on Coroutine creation.
Parameters
f task run by the coroutine
run_coroutine set to false to disable running the coroutine immediately after it is created
Definition at line 173 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::call().
~Coroutine()
template<typename Arg, typename Ret> virtual m5::Coroutine< Arg, Ret >::~Coroutine () inline virtual
Definition at line 181 of file coroutine.hh.
Member Function Documentation
call()
template<typename Arg, typename Ret> void m5::Coroutine< Arg, Ret >::call () inline private
Definition at line 254 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::caller, m5::Coroutine< Arg, Ret >::CallerType::callerFiber, Fiber::currentFiber(), and Fiber::run().
Referenced by m5::Coroutine< Arg, Ret >::Coroutine(), m5::Coroutine< Arg, Ret >::get(), and m5::Coroutine< Arg, Ret >::operator()().
get()
template<typename Arg, typename Ret> template<typename T = Ret> std::enable_if<!std::is_same<T, void>::value, T>::type m5::Coroutine< Arg, Ret >::get () inline
get() is the way we can extrapolate return values (yielded) from the coroutine.
The caller blocks, waiting for the value, unless it is already available; otherwise coroutine execution is resumed, and caller won't execute until a value is yielded back from the coroutine.
Returns
ret yielded value
Definition at line 229 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::call(), m5::Coroutine< Arg, Ret >::caller, and m5::Coroutine< Arg, Ret >::CallerType::retChannel.
Referenced by TEST().
main()
template<typename Arg, typename Ret> void m5::Coroutine< Arg, Ret >::main () inline override private virtual
Overriding base (Fiber) main.
This method will be automatically called by the Fiber running engine and it is a simple wrapper for the task that the coroutine is supposed to run.
Implements Fiber.
Definition at line 251 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::caller, and m5::Coroutine< Arg, Ret >::task.
operator bool()
template<typename Arg, typename Ret> m5::Coroutine< Arg, Ret >::operator bool () const inline
Check if coroutine is still running.
Definition at line 242 of file coroutine.hh.
References Fiber::finished().
operator()() [1/2]
template<typename Arg, typename Ret> template<typename T = Arg> Coroutine& m5::Coroutine< Arg, Ret >::operator() (typename std::enable_if< !std::is_same< T, void >::value, T >::type param) inline
Coroutine interface.
operator() is the way we can jump inside the coroutine and passing arguments.
This method is generated only if the coroutine takes arguments (Arg != void)
Definition at line 195 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::argsChannel, and m5::Coroutine< Arg, Ret >::call().
operator()() [2/2]
template<typename Arg, typename Ret> template<typename T = Arg> std::enable_if<std::is_same<T, void>::value, Coroutine>::type& m5::Coroutine< Arg, Ret >::operator() () inline
operator() is the way we can jump inside the coroutine.
This method is generated only if the coroutine takes no arguments. (Arg = void)
Definition at line 211 of file coroutine.hh.
References m5::Coroutine< Arg, Ret >::call().
operator=()
template<typename Arg, typename Ret> Coroutine& m5::Coroutine< Arg, Ret >::operator= (const Coroutine< Arg, Ret > & rhs) delete
Member Data Documentation
argsChannel
template<typename Arg, typename Ret> ArgChannel m5::Coroutine< Arg, Ret >::argsChannel private
Arguments for the coroutine.
Definition at line 262 of file coroutine.hh.
Referenced by m5::Coroutine< Arg, Ret >::operator()().
caller
template<typename Arg, typename Ret> CallerType m5::Coroutine< Arg, Ret >::caller private
Coroutine caller.
Definition at line 268 of file coroutine.hh.
Referenced by m5::Coroutine< Arg, Ret >::call(), m5::Coroutine< Arg, Ret >::get(), and m5::Coroutine< Arg, Ret >::main().
task
template<typename Arg, typename Ret> std::function<void(CallerType&)> m5::Coroutine< Arg, Ret >::task private
Coroutine task.
Definition at line 265 of file coroutine.hh.
Referenced by m5::Coroutine< Arg, Ret >::main().
The documentation for this class was generated from the following file:
base/coroutine.hh