gem5: tlm_utils::convenience_socket_cb_holder Class Reference
tlm_utils::convenience_socket_cb_holder Class Reference
#include <convenience_socket_bases.h>
Public Member Functions
void display_warning (const char *msg) const
void display_error (const char *msg) const
Protected Member Functions
convenience_socket_cb_holder (convenience_socket_base *owner)
Private Attributes
convenience_socket_base * m_owner
Detailed Description
Definition at line 69 of file convenience_socket_bases.h.
Constructor & Destructor Documentation
convenience_socket_cb_holder()
tlm_utils::convenience_socket_cb_holder::convenience_socket_cb_holder (convenience_socket_base * owner) inline explicit protected
Definition at line 76 of file convenience_socket_bases.h.
Member Function Documentation
display_error()
void tlm_utils::convenience_socket_cb_holder::display_error (const char * msg) const
Definition at line 56 of file convenience_socket_bases.cc.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::b_transport(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_bw(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw(), and tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::nb_transport_fw().
display_warning()
void tlm_utils::convenience_socket_cb_holder::display_warning (const char * msg) const
Definition at line 50 of file convenience_socket_bases.cc.
Referenced by tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr().
Member Data Documentation
m_owner
convenience_socket_base* tlm_utils::convenience_socket_cb_holder::m_owner private
Definition at line 81 of file convenience_socket_bases.h.
The documentation for this class was generated from the following files:
systemc/ext/tlm_utils/convenience_socket_bases.h
systemc/tlm_utils/convenience_socket_bases.cc