gem5: sc_core::sc_object Class Reference
sc_core::sc_object Class Reference
#include <sc_object.hh>
Public Member Functions
const char * name () const
const char * basename () const
virtual const char * kind () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Attributes
sc_gem5::Object * _gem5_object
Friends
class sc_gem5::Object
Detailed Description
Definition at line 52 of file sc_object.hh.
Constructor & Destructor Documentation
sc_object() [1/3]
sc_core::sc_object::sc_object () protected
Definition at line 135 of file sc_object.cc.
References _gem5_object.
sc_object() [2/3]
sc_core::sc_object::sc_object (const char * name) protected
Definition at line 140 of file sc_object.cc.
References _gem5_object.
sc_object() [3/3]
sc_core::sc_object::sc_object (const sc_object & other) protected
Definition at line 145 of file sc_object.cc.
References _gem5_object.
~sc_object()
sc_core::sc_object::~sc_object () protected virtual
Definition at line 157 of file sc_object.cc.
References _gem5_object.
Member Function Documentation
add_attribute()
bool sc_core::sc_object::add_attribute (sc_attr_base & attr)
Definition at line 88 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::add_attribute().
attr_cltn() [1/2]
sc_attr_cltn & sc_core::sc_object::attr_cltn ()
Definition at line 118 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::attr_cltn().
attr_cltn() [2/2]
const sc_attr_cltn & sc_core::sc_object::attr_cltn () const
Definition at line 124 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::attr_cltn().
basename()
const char * sc_core::sc_object::basename () const
Definition at line 52 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::basename().
Referenced by sc_gem5::Object::Object().
dump()
void sc_core::sc_object::dump (std::ostream & out = std::cout) const virtual
Reimplemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >, sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >, and sc_core::sc_fifo< T >.
Definition at line 64 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::dump().
get_attribute()
sc_attr_base * sc_core::sc_object::get_attribute (const std::string & name)
Definition at line 94 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::get_attribute().
Referenced by Iris::BaseCPU::BaseCPU(), and FastModel::CortexA76Cluster::CortexA76Cluster().
get_child_events()
const std::vector< sc_event * > & sc_core::sc_object::get_child_events () const virtual
Reimplemented in sc_core::sc_module.
Definition at line 76 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::get_child_events().
Referenced by sc_core::sc_process_handle::get_child_events().
get_child_objects()
const std::vector< sc_object * > & sc_core::sc_object::get_child_objects () const virtual
Reimplemented in sc_core::sc_module.
Definition at line 70 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::get_child_objects().
Referenced by sc_core::sc_process_handle::get_child_objects().
get_parent_object()
sc_object * sc_core::sc_object::get_parent_object () const
Definition at line 82 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::get_parent_object().
Referenced by sc_core::sc_vector_base::forceParent(), sc_core::sc_process_handle::get_parent_object(), and sc_gem5::Object::Object().
kind()
virtual const char* sc_core::sc_object::kind () const inline virtual
Reimplemented in sc_core::sc_inout< sc_dt::sc_bigint< W > >, sc_core::sc_inout< sc_dt::sc_biguint< W > >, sc_core::sc_inout< sc_dt::sc_uint< W > >, sc_core::sc_inout< sc_dt::sc_int< W > >, sc_core::sc_in< sc_dt::sc_bigint< W > >, sc_core::sc_in< sc_dt::sc_biguint< W > >, sc_core::sc_in< sc_dt::sc_uint< W > >, sc_core::sc_in< sc_dt::sc_int< W > >, sc_core::sc_inout< sc_dt::sc_logic >, sc_core::sc_in< sc_dt::sc_logic >, sc_core::sc_signal< sc_dt::sc_bigint< W > >, sc_core::sc_signal< sc_dt::sc_biguint< W > >, sc_core::sc_inout< bool >, sc_core::sc_signal< sc_dt::sc_uint< W > >, sc_core::sc_signal< sc_dt::sc_int< W > >, sc_core::sc_in< bool >, sc_core::sc_port< IF, N, P >, sc_core::sc_port< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port< bw_interface_type, 1, sc_core::SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< bool >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_put_if< T >, 1 >, sc_core::sc_port< sc_signal_in_if< T >, 1 >, sc_core::sc_port< tlm_nonblocking_get_if< T >, 1 >, sc_core::sc_port< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_inout_if< bool >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_int< W > >, 1 >, sc_core::sc_port< sc_signal_inout_if< T >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< FW_IF, N, POL >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_peek_if< T >, 1 >, sc_core::sc_port< sc_fifo_out_if< T >, 0 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_fifo_in_if< T >, 0 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_int< W > >, 1 >, sc_core::sc_port< bw_interface_type, N, POL >, tlm::tlm_target_socket< BUSWIDTH, TYPES, N, POL >, tlm::tlm_target_socket< 32 >, tlm::tlm_target_socket< BUSWIDTH, my_extended_payload_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, tlm::tlm_base_protocol_types, N, POL >, tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, tlm::tlm_base_protocol_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_target_socket< BUSWIDTH, TYPES, 1, POL >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, N, POL >, tlm::tlm_initiator_socket< 32 >, tlm::tlm_initiator_socket< BUSWIDTH, my_extended_payload_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, tlm::tlm_base_protocol_types, N, POL >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, tlm::tlm_base_protocol_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, 1, POL >, sc_core::sc_fifo< T >, sc_core::sc_vector_base, sc_core::sc_inout< T >, sc_core::sc_inout< sc_dt::sc_lv< W > >, sc_core::sc_in< T >, sc_core::sc_in< sc_dt::sc_lv< W > >, tlm::tlm_fifo< T >, sc_gem5::CThread, ClockRateControlTargetSocket, sc_core::sc_module, SignalInterruptTargetSocket, sc_core::sc_inout_rv< W >, sc_core::sc_signal_rv< W >, sc_core::sc_out< T >, sc_core::sc_out< bool >, sc_core::sc_fifo_in< T >, sc_core::sc_fifo_out< T >, tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, sc_core::sc_out_rv< W >, sc_core::sc_port_base, ClockRateControlInitiatorSocket, tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_target_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, tlm::tlm_base_target_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >, sc_core::sc_clock, SignalInterruptInitiatorSocket, sc_core::sc_buffer< T, WRITER_POLICY >, sc_core::sc_export< IF >, sc_core::sc_export< tlm::tlm_fifo_get_if< REQ > >, sc_core::sc_export< tlm_fw_transport_if< my_extended_payload_types > >, sc_core::sc_export< FW_IF >, sc_core::sc_export< bw_interface_type >, sc_core::sc_export< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_export< tlm::tlm_fifo_put_if< RSP > >, sc_core::sc_export< tlm_fw_transport_if< TYPES > >, sc_core::sc_export< tlm::tlm_fifo_put_if< REQ > >, sc_core::sc_export< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm_base_protocol_types > >, sc_core::sc_export< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_export< tlm_fw_transport_if< tlm::tlm_base_protocol_types > >, sc_core::sc_export< ClockRateControlFwIf >, sc_core::sc_export< SignalInterruptFwIf >, sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >, sc_core::sc_signal_resolved, sc_core::sc_in_rv< W >, sc_gem5::Thread, sc_core::sc_event_queue, sc_core::sc_inout_resolved, sc_core::sc_out_resolved, sc_gem5::ScSignalBase, sc_core::sc_prim_channel, sc_core::sc_in_resolved, sc_core::sc_mutex, sc_core::sc_semaphore, and sc_gem5::Method.
Definition at line 58 of file sc_object.hh.
References Stats::dump().
Referenced by sc_gem5::ScSignalBaseBinary::_signalNegedge(), sc_gem5::Object::dump(), sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::end_of_elaboration(), and sc_core::sc_export_base::sc_export_base().
name()
const char * sc_core::sc_object::name () const
Definition at line 46 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::name().
Referenced by sc_gem5::ScSignalBaseBinary::_signalNegedge(), SimpleLTTarget1::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::before_end_of_elaboration(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration(), sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::bind(), sc_core::sc_signal< sc_dt::sc_int< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_uint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::check_writer(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::check_writer(), sc_core::sc_vector_base::checkIndex(), Iris::CPU< ArmThreadContext >::CPU(), tlm_utils::convenience_socket_base::display_error(), tlm_utils::convenience_socket_base::display_warning(), sc_core::sc_fifo< T >::dump(), MultiSocketSimpleSwitchAT::dump_status(), sc_core::sc_in_resolved::end_of_elaboration(), sc_core::sc_inout_resolved::end_of_elaboration(), sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::end_of_elaboration(), SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), sc_gem5::Event::Event(), tlm::tlm_event_finder_t< IF, T >::find_event(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorNBTransport(), SimpleLTInitiator1_dmi::invalidate_direct_mem_ptr(), SimpleLTInitiator_ext::invalidate_direct_mem_ptr(), SimpleLTInitiator2::logEndTransaction(), SimpleLTInitiator3::logEndTransaction(), SimpleLTInitiator1::logEndTransaction(), CoreDecouplingLTInitiator::logEndTransaction(), SimpleLTInitiator_ext::logEndTransaction(), SimpleLTInitiator3_dmi::logEndTransaction(), SimpleLTInitiator1_dmi::logEndTransaction(), SimpleLTInitiator2_dmi::logEndTransaction(), SimpleATInitiator2::logEndTransaction(), SimpleATInitiator1::logEndTransaction(), SimpleLTInitiator2::logStartTransation(), SimpleLTInitiator3::logStartTransation(), CoreDecouplingLTInitiator::logStartTransation(), SimpleLTInitiator1::logStartTransation(), SimpleLTInitiator_ext::logStartTransation(), SimpleLTInitiator3_dmi::logStartTransation(), SimpleLTInitiator1_dmi::logStartTransation(), SimpleLTInitiator2_dmi::logStartTransation(), SimpleATInitiator2::logStartTransation(), SimpleATInitiator1::logStartTransation(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), SimpleLTTarget_ext::myGetDMIPtr(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), sc_core::sc_process_handle::name(), sc_gem5::newCThreadProcess(), sc_gem5::newMethodProcess(), sc_gem5::newThreadProcess(), sc_gem5::Sensitivity::notify(), sc_core::sc_export< tlm_fw_transport_if< TYPES > >::operator tlm_fw_transport_if< TYPES > &(), sc_core::sc_export< tlm::tlm_fifo_get_if< RSP > >::operator->(), sc_core::sc_int_sigref::operator=(), sc_core::sc_unsigned_sigref::operator=(), sc_core::sc_signed_sigref::operator=(), sc_core::sc_fifo< T >::register_port(), sc_core::sc_signal< sc_dt::sc_int< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_uint< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::register_port(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::register_port(), sc_core::sc_report_handler::report(), sc_core::sc_port_base::report_error(), sc_core::sc_vector_base::reportEmpty(), sc_core::sc_export_base::sc_export_base(), sc_core::sc_port_base::sc_port_base(), sc_core::sc_semaphore::sc_semaphore(), sc_core::sc_trace(), sc_core::sc_trace< bool >(), sc_core::sc_trace< sc_dt::sc_logic >(), FastModel::CortexA76Cluster::set_evs_param(), sc_gem5::spawnWork(), MultiSocketSimpleSwitchAT::targetNBTransport(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::targetNBTransport().
num_attributes()
int sc_core::sc_object::num_attributes () const
Definition at line 112 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::num_attributes().
operator=()
sc_object & sc_core::sc_object::operator= (const sc_object & other) protected
Definition at line 151 of file sc_object.cc.
References _gem5_object.
print()
void sc_core::sc_object::print (std::ostream & out = std::cout) const virtual
Reimplemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, SC_ONE_WRITER >, sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >, sc_gem5::ScSignalBaseT< bool, WRITER_POLICY >, sc_gem5::ScSignalBaseT< sc_dt::sc_logic, WRITER_POLICY >, and sc_core::sc_fifo< T >.
Definition at line 58 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::print().
remove_all_attributes()
void sc_core::sc_object::remove_all_attributes ()
Definition at line 106 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::remove_all_attributes().
remove_attribute()
sc_attr_base * sc_core::sc_object::remove_attribute (const std::string & name)
Definition at line 100 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::remove_attribute().
simcontext()
sc_simcontext * sc_core::sc_object::simcontext () const
Definition at line 130 of file sc_object.cc.
References _gem5_object, and sc_gem5::Object::simcontext().
Referenced by sc_core::sc_signal< sc_dt::sc_int< W > >::update(), sc_core::sc_signal< sc_dt::sc_uint< W > >::update(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::update(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::update().
Friends And Related Function Documentation
sc_gem5::Object
friend class sc_gem5::Object friend
Definition at line 86 of file sc_object.hh.
Member Data Documentation
_gem5_object
sc_gem5::Object* sc_core::sc_object::_gem5_object private
Definition at line 87 of file sc_object.hh.
Referenced by add_attribute(), attr_cltn(), basename(), dump(), get_attribute(), get_child_events(), get_child_objects(), get_parent_object(), sc_gem5::Object::getFromScObject(), name(), num_attributes(), sc_gem5::Object::Object(), operator=(), print(), remove_all_attributes(), remove_attribute(), sc_object(), simcontext(), sc_gem5::Object::~Object(), and ~sc_object().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_object.hh
systemc/core/sc_object.cc