gem5: SuperBlk Class Reference
SuperBlk Class Reference
A basic compression superblock.
#include <super_blk.hh>
Public Member Functions
SuperBlk ()
SuperBlk (const SuperBlk &)=delete
SuperBlk & operator= (const SuperBlk &)=delete
~SuperBlk ()
bool isCompressed (const CompressionBlk *ignored_blk=nullptr) const
Returns whether the superblock contains compressed blocks or not.
bool canCoAllocate (const std::size_t compressed_size) const
Checks whether a superblock can co-allocate given compressed data block.
void setBlkSize (const std::size_t blk_size)
Set block size.
Public Member Functions inherited from SectorBlk
SectorBlk ()
SectorBlk (const SectorBlk &)=delete
SectorBlk & operator= (const SectorBlk &)=delete
~SectorBlk ()
bool isValid () const
Checks that a sector block is valid.
bool isSecure () const
Checks that a sector block is secure.
void setTag (const Addr tag)
Set tag associated to this block.
Addr getTag () const
Get tag associated to this block.
void validateSubBlk ()
Increase the number of valid sub-blocks.
void invalidateSubBlk ()
Decrease the number of valid sub-blocks.
void setSecure ()
Set secure bit.
void setPosition (const uint32_t set, const uint32_t way) override
Sets the position of the sub-entries, besides its own.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Protected Attributes
std::size_t blkSize
Block size, in bytes.
Protected Attributes inherited from SectorBlk
Addr _tag
Sector tag value.
uint8_t _validCounter
Counter of the number of valid sub-blocks.
bool _secureBit
Whether sector blk is in secure-space or not.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Additional Inherited Members
Public Attributes inherited from SectorBlk
std::vector< SectorSubBlk * > blks
List of blocks associated to this sector.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Detailed Description
A basic compression superblock.
Contains the tag and a list of blocks associated to this superblock.
Definition at line 127 of file super_blk.hh.
Constructor & Destructor Documentation
SuperBlk() [1/2]
SuperBlk::SuperBlk () inline
Definition at line 134 of file super_blk.hh.
References CompressionBlk::operator=().
SuperBlk() [2/2]
SuperBlk::SuperBlk (const SuperBlk &) delete
~SuperBlk()
SuperBlk::~SuperBlk () inline
Definition at line 137 of file super_blk.hh.
References CompressionBlk::isCompressed().
Member Function Documentation
canCoAllocate()
bool SuperBlk::canCoAllocate (const std::size_t compressed_size) const
Checks whether a superblock can co-allocate given compressed data block.
Parameters
compressed_size Size, in bits, of new block to allocate.
Returns
True if block can be co-allocated in superblock.
Definition at line 110 of file super_blk.cc.
Referenced by CompressedTags::findVictim(), CompressedTags::insertBlock(), and BaseCache::updateCompressionData().
isCompressed()
bool SuperBlk::isCompressed (const CompressionBlk * ignored_blk = nullptr) const
Returns whether the superblock contains compressed blocks or not.
By default, if not blocks are valid, the superblock is compressible.
Parameters
ignored_blk If provided don't consider the given block.
Returns
The compressibility state of the superblock.
Definition at line 97 of file super_blk.cc.
References CompressionBlk::isCompressed().
Referenced by CompressedTags::findVictim(), CompressedTags::insertBlock(), and BaseCache::updateCompressionData().
operator=()
SuperBlk& SuperBlk::operator= (const SuperBlk &) delete
setBlkSize()
void SuperBlk::setBlkSize (const std::size_t blk_size)
Set block size.
Should be called only once, when initializing blocks.
Parameters
blk_size The uncompressed block size.
Definition at line 119 of file super_blk.cc.
Referenced by CompressedTags::tagsInit().
Member Data Documentation
blkSize
std::size_t SuperBlk::blkSize protected
Block size, in bytes.
Definition at line 131 of file super_blk.hh.
The documentation for this class was generated from the following files:
mem/cache/tags/super_blk.hh
mem/cache/tags/super_blk.cc