gem5: RiscvISA::SyscallFault Class Reference
RiscvISA::SyscallFault Class Reference
#include <faults.hh>
Public Member Functions
SyscallFault (PrivilegeMode prv)
void invokeSE (ThreadContext *tc, const StaticInstPtr &inst) override
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Additional Inherited Members
Protected Member Functions inherited from RiscvISA::RiscvFault
RiscvFault (FaultName n, bool i, ExceptionCode c)
FaultName name () const override
bool isInterrupt () const
ExceptionCode exception () const
virtual RegVal trap_value () const
void invoke (ThreadContext *tc, const StaticInstPtr &inst) override
Protected Attributes inherited from RiscvISA::RiscvFault
const FaultName _name
const bool _interrupt
ExceptionCode _code
Detailed Description
Definition at line 226 of file faults.hh.
Constructor & Destructor Documentation
SyscallFault()
RiscvISA::SyscallFault::SyscallFault (PrivilegeMode prv) inline
Definition at line 229 of file faults.hh.
References RiscvISA::RiscvFault::_code, RiscvISA::ECALL_MACHINE, RiscvISA::ECALL_SUPER, RiscvISA::ECALL_USER, RiscvISA::RiscvFault::invokeSE(), panic, RiscvISA::PRV_M, RiscvISA::PRV_S, and RiscvISA::PRV_U.
Member Function Documentation
invokeSE()
void RiscvISA::SyscallFault::invokeSE (ThreadContext * tc, const StaticInstPtr & inst) override virtual
Reimplemented from RiscvISA::RiscvFault.
Definition at line 191 of file faults.cc.
References NoFault, ThreadContext::readIntReg(), ThreadContext::syscall(), and RiscvISA::SyscallNumReg.
The documentation for this class was generated from the following files:
arch/riscv/faults.hh
arch/riscv/faults.cc