gem5: Minor::MinorDynInst Class Reference
Minor::MinorDynInst Class Reference
Dynamic instruction for Minor.
#include <dyn_inst.hh>
Public Member Functions
MinorDynInst (InstId id_=InstId(), Fault fault_=NoFault)
bool isBubble () const
The BubbleIF interface.
bool isFault () const
Is this a fault rather than instruction.
bool isInst () const
Is this a real instruction.
bool isMemRef () const
Is this a real mem ref instruction.
bool isNoCostInst () const
Is this an instruction that can be executed `for free' and needn't spend time in an FU.
bool isLastOpInInst () const
Assuming this is not a fault, is this instruction either a whole instruction or the last microop from a macroop.
void minorTraceInst (const Named &named_object) const
Print (possibly verbose) instruction information for MinorTrace using the given Named object's name.
void reportData (std::ostream &os) const
ReportIF interface.
bool readPredicate () const
void setPredicate (bool val)
bool readMemAccPredicate () const
void setMemAccPredicate (bool val)
~MinorDynInst ()
Public Member Functions inherited from RefCounted
RefCounted ()
We initialize the reference count to zero and the first object to take ownership of it must increment it to one.
virtual ~RefCounted ()
We make the destructor virtual because we're likely to have virtual functions on reference counted objects.
void incref () const
Increment the reference count.
void decref () const
Decrement the reference count and destroy the object if all references are gone.
Static Public Member Functions
static MinorDynInstPtr bubble ()
There is a single bubble inst.
static void init ()
Initialise the class.
Public Attributes
StaticInstPtr staticInst
InstId id
Trace::InstRecord * traceData
Trace information for this instruction's execution.
TheISA::PCState pc
The fetch address of this instruction.
Fault fault
This is actually a fault masquerading as an instruction.
bool triedToPredict
Tried to predict the destination of this inst (if a control instruction or a sys call)
bool predictedTaken
This instruction was predicted to change control flow and the following instructions will have a newer predictionSeqNum.
TheISA::PCState predictedTarget
Predicted branch target.
unsigned int fuIndex
Fields only set during execution.
bool inLSQ
This instruction is in the LSQ, not a functional unit.
Fault translationFault
Translation fault in case of a mem ref.
bool inStoreBuffer
The instruction has been sent to the store buffer.
bool canEarlyIssue
Can this instruction be executed out of order.
bool predicate
Flag controlling conditional execution of the instruction.
bool memAccPredicate
Flag controlling conditional execution of the memory access associated with the instruction (only meaningful for loads/stores)
InstSeqNum instToWaitFor
execSeqNum of the latest inst on which this inst depends.
Cycles extraCommitDelay
Extra delay at the end of the pipeline.
TimingExpr * extraCommitDelayExpr
Cycles minimumCommitCycle
Once issued, extraCommitDelay becomes minimumCommitCycle to account for delay in absolute time.
RegId flatDestRegIdx [TheISA::MaxInstDestRegs]
Flat register indices so that, when clearing the scoreboard, we have the same register indices as when the instruction was marked up.
Static Private Attributes
static MinorDynInstPtr bubbleInst = NULL
A prototypical bubble instruction.
Detailed Description
Dynamic instruction for Minor.
MinorDynInst implements the BubbleIF interface Has two separate notions of sequence number for pre/post-micro-op decomposition: fetchSeqNum and execSeqNum
Definition at line 157 of file dyn_inst.hh.
Constructor & Destructor Documentation
MinorDynInst()
Minor::MinorDynInst::MinorDynInst (InstId id_ = InstId(), Fault fault_ = NoFault) inline
Definition at line 235 of file dyn_inst.hh.
Referenced by init().
~MinorDynInst()
Minor::MinorDynInst::~MinorDynInst ()
Definition at line 240 of file dyn_inst.cc.
References traceData.
Member Function Documentation
bubble()
static MinorDynInstPtr Minor::MinorDynInst::bubble () inline static
There is a single bubble inst.
Definition at line 250 of file dyn_inst.hh.
Referenced by Minor::ForwardInstData::bubbleFill(), Minor::Execute::commit(), Minor::Execute::evaluate(), and Minor::Execute::takeInterrupt().
init()
void Minor::MinorDynInst::init () static
Initialise the class.
Definition at line 81 of file dyn_inst.cc.
References bubbleInst, and MinorDynInst().
Referenced by MinorCPU::MinorCPU().
isBubble()
bool Minor::MinorDynInst::isBubble () const inline
The BubbleIF interface.
Definition at line 247 of file dyn_inst.hh.
Referenced by reportData().
isFault()
bool Minor::MinorDynInst::isFault () const inline
Is this a fault rather than instruction.
Definition at line 253 of file dyn_inst.hh.
References NoFault.
Referenced by minorTraceInst(), Minor::operator<<(), and reportData().
isInst()
bool Minor::MinorDynInst::isInst () const inline
Is this a real instruction.
Definition at line 256 of file dyn_inst.hh.
Referenced by isNoCostInst().
isLastOpInInst()
bool Minor::MinorDynInst::isLastOpInInst () const
Assuming this is not a fault, is this instruction either a whole instruction or the last microop from a macroop.
Definition at line 92 of file dyn_inst.cc.
References StaticInst::isLastMicroop(), StaticInst::isMicroop(), and staticInst.
isMemRef()
bool Minor::MinorDynInst::isMemRef () const inline
Is this a real mem ref instruction.
Definition at line 259 of file dyn_inst.hh.
References Stats::init, and StaticInst::isMemRef().
isNoCostInst()
bool Minor::MinorDynInst::isNoCostInst () const
Is this an instruction that can be executed `for free' and needn't spend time in an FU.
Definition at line 99 of file dyn_inst.cc.
References isInst(), StaticInst::opClass(), and staticInst.
minorTraceInst()
void Minor::MinorDynInst::minorTraceInst (const Named & named_object) const
Print (possibly verbose) instruction information for MinorTrace using the given Named object's name.
Definition at line 183 of file dyn_inst.cc.
References StaticInst::destRegIdx(), StaticInst::disassemble(), fault, isFault(), StaticInst::isMacroop(), StaticInst::machInst, MINORINST, StaticInst::numDestRegs(), StaticInst::numSrcRegs(), StaticInst::opClass(), pc, predictedTaken, StaticInst::printFlags(), Minor::printRegName(), StaticInst::srcRegIdx(), and staticInst.
readMemAccPredicate()
bool Minor::MinorDynInst::readMemAccPredicate () const inline
Definition at line 283 of file dyn_inst.hh.
readPredicate()
bool Minor::MinorDynInst::readPredicate () const inline
Definition at line 279 of file dyn_inst.hh.
reportData()
void Minor::MinorDynInst::reportData (std::ostream & os) const
ReportIF interface.
Definition at line 105 of file dyn_inst.cc.
References id, isBubble(), isFault(), NoFault, and translationFault.
setMemAccPredicate()
void Minor::MinorDynInst::setMemAccPredicate (bool val) inline
Definition at line 285 of file dyn_inst.hh.
References Minor::operator<<(), and X86ISA::val.
setPredicate()
void Minor::MinorDynInst::setPredicate (bool val) inline
Definition at line 281 of file dyn_inst.hh.
References X86ISA::val.
Member Data Documentation
bubbleInst
MinorDynInstPtr Minor::MinorDynInst::bubbleInst = NULL static private
A prototypical bubble instruction.
You must call MinorDynInst::init to initialise this
Definition at line 162 of file dyn_inst.hh.
Referenced by init(), and Minor::operator<<().
canEarlyIssue
bool Minor::MinorDynInst::canEarlyIssue
Can this instruction be executed out of order.
In this model, this only happens with mem refs that need to be issued early to allow other instructions to fill the fetch delay
Definition at line 206 of file dyn_inst.hh.
extraCommitDelay
Cycles Minor::MinorDynInst::extraCommitDelay
Extra delay at the end of the pipeline.
Definition at line 222 of file dyn_inst.hh.
extraCommitDelayExpr
TimingExpr* Minor::MinorDynInst::extraCommitDelayExpr
Definition at line 223 of file dyn_inst.hh.
fault
Fault Minor::MinorDynInst::fault
This is actually a fault masquerading as an instruction.
Definition at line 176 of file dyn_inst.hh.
Referenced by minorTraceInst(), and Minor::operator<<().
flatDestRegIdx
RegId Minor::MinorDynInst::flatDestRegIdx[TheISA::MaxInstDestRegs]
Flat register indices so that, when clearing the scoreboard, we have the same register indices as when the instruction was marked up.
Definition at line 232 of file dyn_inst.hh.
fuIndex
unsigned int Minor::MinorDynInst::fuIndex
Fields only set during execution.
FU this instruction is issued to
Definition at line 192 of file dyn_inst.hh.
id
InstId Minor::MinorDynInst::id
Definition at line 167 of file dyn_inst.hh.
Referenced by Minor::operator<<(), and reportData().
inLSQ
bool Minor::MinorDynInst::inLSQ
This instruction is in the LSQ, not a functional unit.
Definition at line 195 of file dyn_inst.hh.
inStoreBuffer
bool Minor::MinorDynInst::inStoreBuffer
The instruction has been sent to the store buffer.
Definition at line 201 of file dyn_inst.hh.
instToWaitFor
InstSeqNum Minor::MinorDynInst::instToWaitFor
execSeqNum of the latest inst on which this inst depends.
This can be used as a sanity check for dependency ordering where slightly out of order execution is required (notably initiateAcc for memory ops)
Definition at line 219 of file dyn_inst.hh.
memAccPredicate
bool Minor::MinorDynInst::memAccPredicate
Flag controlling conditional execution of the memory access associated with the instruction (only meaningful for loads/stores)
Definition at line 213 of file dyn_inst.hh.
minimumCommitCycle
Cycles Minor::MinorDynInst::minimumCommitCycle
Once issued, extraCommitDelay becomes minimumCommitCycle to account for delay in absolute time.
Definition at line 227 of file dyn_inst.hh.
pc
TheISA::PCState Minor::MinorDynInst::pc
The fetch address of this instruction.
Definition at line 173 of file dyn_inst.hh.
Referenced by minorTraceInst(), and Minor::operator<<().
predicate
bool Minor::MinorDynInst::predicate
Flag controlling conditional execution of the instruction.
Definition at line 209 of file dyn_inst.hh.
predictedTaken
bool Minor::MinorDynInst::predictedTaken
This instruction was predicted to change control flow and the following instructions will have a newer predictionSeqNum.
Definition at line 184 of file dyn_inst.hh.
Referenced by minorTraceInst().
predictedTarget
TheISA::PCState Minor::MinorDynInst::predictedTarget
Predicted branch target.
Definition at line 187 of file dyn_inst.hh.
staticInst
StaticInstPtr Minor::MinorDynInst::staticInst
Definition at line 165 of file dyn_inst.hh.
Referenced by isLastOpInInst(), isNoCostInst(), minorTraceInst(), and Minor::operator<<().
traceData
Trace::InstRecord* Minor::MinorDynInst::traceData
Trace information for this instruction's execution.
Definition at line 170 of file dyn_inst.hh.
Referenced by ~MinorDynInst().
translationFault
Fault Minor::MinorDynInst::translationFault
Translation fault in case of a mem ref.
Definition at line 198 of file dyn_inst.hh.
Referenced by Minor::operator<<(), and reportData().
triedToPredict
bool Minor::MinorDynInst::triedToPredict
Tried to predict the destination of this inst (if a control instruction or a sys call)
Definition at line 180 of file dyn_inst.hh.
The documentation for this class was generated from the following files:
cpu/minor/dyn_inst.hh
cpu/minor/dyn_inst.cc