gem5: ProtoInputStream Class Reference
ProtoInputStream Class Reference
A ProtoInputStream wraps a coded stream, potentially with decompression, based on looking at the file name.
#include <protoio.hh>
Public Member Functions
ProtoInputStream (const std::string &filename)
Create an input stream for a given file name.
~ProtoInputStream ()
Destruct the input stream, and also close the underlying file streams and coded streams.
bool read (google::protobuf::Message &msg)
Read a message from the stream.
void reset ()
Reset the input stream and seek to the beginning of the file.
Private Member Functions
void createStreams ()
Create the internal streams that are wrapping the input file.
void destroyStreams ()
Destroy the internal streams that are wrapping the input file.
Private Attributes
std::ifstream fileStream
Underlying file input stream.
const std::string fileName
Hold on to the file name for debug messages.
bool useGzip
Boolean flag to remember whether we use gzip or not.
google::protobuf::io::IstreamInputStream * wrappedFileStream
Zero Copy stream wrapping the STL input stream.
google::protobuf::io::GzipInputStream * gzipStream
Optional Gzip stream to wrap the Zero Copy stream.
google::protobuf::io::ZeroCopyInputStream * zeroCopyStream
Top-level zero-copy stream, either with compression or not.
Additional Inherited Members
Protected Member Functions inherited from ProtoStream
ProtoStream ()
Create a ProtoStream.
Static Protected Attributes inherited from ProtoStream
static const uint32_t magicNumber = 0x356d6567
Use the ASCII characters gem5 as our magic number.
Detailed Description
A ProtoInputStream wraps a coded stream, potentially with decompression, based on looking at the file name.
Reading from the stream is done on a per-message basis to avoid having to deal with huge data structures. The latter assumes the length of each message is encoded in the stream when it is written.
Definition at line 142 of file protoio.hh.
Constructor & Destructor Documentation
ProtoInputStream()
ProtoInputStream::ProtoInputStream (const std::string & filename)
Create an input stream for a given file name.
If the filename ends with .gz then the file will be decompressed accordingly.
Parameters
filename Path to the file to read from
Definition at line 98 of file protoio.cc.
References createStreams(), fileStream, panic, and useGzip.
~ProtoInputStream()
ProtoInputStream::~ProtoInputStream ()
Destruct the input stream, and also close the underlying file streams and coded streams.
Definition at line 159 of file protoio.cc.
References destroyStreams(), and fileStream.
Member Function Documentation
createStreams()
void ProtoInputStream::createStreams () private
Create the internal streams that are wrapping the input file.
Definition at line 119 of file protoio.cc.
References fileName, fileStream, gzipStream, ProtoStream::magicNumber, panic, useGzip, wrappedFileStream, and zeroCopyStream.
Referenced by ProtoInputStream(), and reset().
destroyStreams()
void ProtoInputStream::destroyStreams () private
Destroy the internal streams that are wrapping the input file.
Definition at line 145 of file protoio.cc.
References gzipStream, wrappedFileStream, and zeroCopyStream.
Referenced by reset(), and ~ProtoInputStream().
read()
bool ProtoInputStream::read (google::protobuf::Message & msg)
Read a message from the stream.
Parameters
msg Message read from the stream
return True if a message was read, false if reading fails
Definition at line 177 of file protoio.cc.
References fileName, X86ISA::limit, panic, and zeroCopyStream.
Referenced by TraceGen::enter(), TraceGen::getNextPacket(), TraceGen::InputStream::init(), TraceCPU::FixedRetryGen::InputStream::InputStream(), TraceCPU::ElasticDataGen::InputStream::InputStream(), TraceGen::InputStream::read(), TraceCPU::FixedRetryGen::InputStream::read(), and TraceCPU::ElasticDataGen::InputStream::read().
reset()
void ProtoInputStream::reset ()
Reset the input stream and seek to the beginning of the file.
Definition at line 167 of file protoio.cc.
References createStreams(), destroyStreams(), and fileStream.
Referenced by TraceGen::exit(), TraceGen::InputStream::reset(), TraceCPU::FixedRetryGen::InputStream::reset(), and TraceCPU::ElasticDataGen::InputStream::reset().
Member Data Documentation
fileName
const std::string ProtoInputStream::fileName private
Hold on to the file name for debug messages.
Definition at line 190 of file protoio.hh.
Referenced by createStreams(), and read().
fileStream
std::ifstream ProtoInputStream::fileStream private
Underlying file input stream.
Definition at line 187 of file protoio.hh.
Referenced by createStreams(), ProtoInputStream(), reset(), and ~ProtoInputStream().
gzipStream
google::protobuf::io::GzipInputStream* ProtoInputStream::gzipStream private
Optional Gzip stream to wrap the Zero Copy stream.
Definition at line 199 of file protoio.hh.
Referenced by createStreams(), and destroyStreams().
useGzip
bool ProtoInputStream::useGzip private
Boolean flag to remember whether we use gzip or not.
Definition at line 193 of file protoio.hh.
Referenced by createStreams(), and ProtoInputStream().
wrappedFileStream
google::protobuf::io::IstreamInputStream* ProtoInputStream::wrappedFileStream private
Zero Copy stream wrapping the STL input stream.
Definition at line 196 of file protoio.hh.
Referenced by createStreams(), and destroyStreams().
zeroCopyStream
google::protobuf::io::ZeroCopyInputStream* ProtoInputStream::zeroCopyStream private
Top-level zero-copy stream, either with compression or not.
Definition at line 202 of file protoio.hh.
Referenced by createStreams(), destroyStreams(), and read().
The documentation for this class was generated from the following files:
proto/protoio.hh
proto/protoio.cc