gem5: LinearGen Class Reference
LinearGen Class Reference
The linear generator generates sequential requests from a start to an end address, with a fixed block size.
#include <linear_gen.hh>
Public Member Functions
LinearGen (SimObject &obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
Create a linear address sequence generator.
void enter ()
Enter this generator state.
PacketPtr getNextPacket ()
Get the next generated packet.
Tick nextPacketTick (bool elastic, Tick delay) const
Determine the tick when the next packet is available.
Public Member Functions inherited from StochasticGen
StochasticGen (SimObject &obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit)
Public Member Functions inherited from BaseGen
BaseGen (SimObject &obj, MasterID master_id, Tick _duration)
Create a base generator.
virtual ~BaseGen ()
std::string name () const
Get the name, useful for DPRINTFs.
virtual void exit ()
Exit this generator state.
Private Attributes
Addr nextAddr
Address of next request.
Addr dataManipulated
Counter to determine the amount of data manipulated.
Additional Inherited Members
Public Attributes inherited from BaseGen
const Tick duration
Time to spend in this state.
Protected Member Functions inherited from BaseGen
PacketPtr getPacket (Addr addr, unsigned size, const MemCmd &cmd, Request::FlagsType flags=0)
Generate a new request and associated packet.
Protected Attributes inherited from StochasticGen
const Addr startAddr
Start of address range.
const Addr endAddr
End of address range.
const Addr blocksize
Blocksize and address increment.
const Addr cacheLineSize
Cache line size in the simulated system.
const Tick minPeriod
Request generation period.
const Tick maxPeriod
const uint8_t readPercent
Percent of generated transactions that should be reads.
const Addr dataLimit
Maximum amount of data to manipulate.
Protected Attributes inherited from BaseGen
const std::string _name
Name to use for status and debug printing.
const MasterID masterID
The MasterID used for generating requests.
Detailed Description
The linear generator generates sequential requests from a start to an end address, with a fixed block size.
A fraction of the requests are reads, as determined by the read percent. There is an optional data limit for when to stop generating new requests.
Definition at line 64 of file linear_gen.hh.
Constructor & Destructor Documentation
LinearGen()
LinearGen::LinearGen (SimObject & obj, MasterID master_id, Tick _duration, Addr start_addr, Addr end_addr, Addr _blocksize, Addr cacheline_size, Tick min_period, Tick max_period, uint8_t read_percent, Addr data_limit) inline
Create a linear address sequence generator.
Set min_period == max_period for a fixed inter-transaction time.
Parameters
obj SimObject owning this sequence generator
master_id MasterID related to the memory requests
_duration duration of this state before transitioning
start_addr Start address
end_addr End address
_blocksize Size used for transactions injected
cacheline_size cache line size in the system
min_period Lower limit of random inter-transaction time
max_period Upper limit of random inter-transaction time
read_percent Percent of transactions that are reads
data_limit Upper limit on how much data to read/write
Definition at line 86 of file linear_gen.hh.
References enter(), getNextPacket(), and nextPacketTick().
Member Function Documentation
enter()
void LinearGen::enter () virtual
Enter this generator state.
Implements BaseGen.
Definition at line 52 of file linear_gen.cc.
References dataManipulated, nextAddr, and StochasticGen::startAddr.
Referenced by LinearGen().
getNextPacket()
PacketPtr LinearGen::getNextPacket () virtual
Get the next generated packet.
Returns
A packet to be sent at the current tick
Implements BaseGen.
Definition at line 60 of file linear_gen.cc.
References StochasticGen::blocksize, dataManipulated, DPRINTF, StochasticGen::endAddr, BaseGen::getPacket(), nextAddr, Random::random(), random_mt, StochasticGen::readPercent, MemCmd::ReadReq, StochasticGen::startAddr, and MemCmd::WriteReq.
Referenced by LinearGen().
nextPacketTick()
Tick LinearGen::nextPacketTick (bool elastic, Tick delay) const virtual
Determine the tick when the next packet is available.
MaxTick means that there will not be any further packets in the current activation cycle of the generator.
Parameters
elastic should the injection respond to flow control or not
delay time the previous packet spent waiting
Returns
next tick when a packet is available
Implements BaseGen.
Definition at line 93 of file linear_gen.cc.
References curTick(), StochasticGen::dataLimit, dataManipulated, DPRINTF, StochasticGen::maxPeriod, MaxTick, StochasticGen::minPeriod, Random::random(), random_mt, and sc_core::wait().
Referenced by LinearGen().
Member Data Documentation
dataManipulated
Addr LinearGen::dataManipulated private
Counter to determine the amount of data manipulated.
Used to determine if we should continue generating requests.
Definition at line 114 of file linear_gen.hh.
Referenced by enter(), getNextPacket(), and nextPacketTick().
nextAddr
Addr LinearGen::nextAddr private
Address of next request.
Definition at line 107 of file linear_gen.hh.
Referenced by enter(), and getNextPacket().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/linear_gen.hh
cpu/testers/traffic_gen/linear_gen.cc