gem5: sc_core::sc_vector_base Class Reference
sc_core::sc_vector_base Class Reference abstract
#include <sc_vector.hh>
Public Types
typedef size_t size_type
Public Member Functions
sc_vector_base (const char *_name)
virtual const char * kind () const
size_type size () const
const std::vector< sc_object * > & get_elements () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
sc_object * implicitCast (sc_object *p) const
sc_object * implicitCast (...) const
virtual sc_object * objectCast (void *) const =0
void checkIndex (size_type index) const
void forceParent () const
void unforceParent () const
void reportEmpty (const char *kind_, bool empty_dest) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
std::vector< void * > objs
std::vector< sc_object * > elements
Detailed Description
Definition at line 165 of file sc_vector.hh.
Member Typedef Documentation
size_type
typedef size_t sc_core::sc_vector_base::size_type
Definition at line 168 of file sc_vector.hh.
Constructor & Destructor Documentation
sc_vector_base()
sc_core::sc_vector_base::sc_vector_base (const char * _name) inline
Definition at line 170 of file sc_vector.hh.
Member Function Documentation
checkIndex()
void sc_core::sc_vector_base::checkIndex (size_type index) const protected
Definition at line 75 of file sc_vector.cc.
References ccprintf(), sc_core::sc_object::name(), sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, SC_REPORT_ERROR, size(), and ArmISA::ss.
forceParent()
void sc_core::sc_vector_base::forceParent () const protected
Definition at line 86 of file sc_vector.cc.
References sc_core::sc_object::get_parent_object(), and sc_gem5::pushParentObj().
get_elements()
const std::vector< sc_object * > & sc_core::sc_vector_base::get_elements () const
Definition at line 63 of file sc_vector.cc.
References elements, objectCast(), and objs.
implicitCast() [1/2]
sc_object* sc_core::sc_vector_base::implicitCast (sc_object * p) const inline protected
Definition at line 183 of file sc_vector.hh.
References MipsISA::p.
implicitCast() [2/2]
sc_object* sc_core::sc_vector_base::implicitCast (...) const inline protected
Definition at line 184 of file sc_vector.hh.
References MipsISA::index, name(), sc_core::SC_ID_VECTOR_NONOBJECT_ELEMENTS_, and SC_REPORT_ERROR.
kind()
virtual const char* sc_core::sc_vector_base::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 172 of file sc_vector.hh.
objectCast()
virtual sc_object* sc_core::sc_vector_base::objectCast (void *) const protected pure virtual
Implemented in sc_core::sc_vector< T >, and sc_core::sc_vector< svp_gicv3_comms::gicv3_comms_target_socket<> >.
Referenced by get_elements().
reportEmpty()
void sc_core::sc_vector_base::reportEmpty (const char * kind_, bool empty_dest) const protected
Definition at line 98 of file sc_vector.cc.
References sc_core::sc_object::name(), sc_core::SC_ID_VECTOR_BIND_EMPTY_, SC_REPORT_WARNING, size(), and ArmISA::ss.
size()
sc_vector_base::size_type sc_core::sc_vector_base::size () const
Definition at line 60 of file sc_vector.cc.
References objs.
Referenced by checkIndex(), and reportEmpty().
unforceParent()
void sc_core::sc_vector_base::unforceParent () const protected
Definition at line 92 of file sc_vector.cc.
References sc_gem5::popParentObj().
Member Data Documentation
elements
std::vector<sc_object *> sc_core::sc_vector_base::elements mutable protected
Definition at line 181 of file sc_vector.hh.
Referenced by get_elements().
objs
std::vector<void *> sc_core::sc_vector_base::objs protected
Definition at line 177 of file sc_vector.hh.
Referenced by get_elements(), and size().
The documentation for this class was generated from the following files:
systemc/ext/utils/sc_vector.hh
systemc/utils/sc_vector.cc