gem5: GenericPageTableFault Class Reference
GenericPageTableFault Class Reference
#include <faults.hh>
Public Member Functions
FaultName name () const
GenericPageTableFault (Addr va)
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Addr getFaultVAddr () const
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Private Attributes
Addr vaddr
Detailed Description
Definition at line 93 of file faults.hh.
Constructor & Destructor Documentation
GenericPageTableFault()
GenericPageTableFault::GenericPageTableFault (Addr va) inline
Definition at line 99 of file faults.hh.
References FaultBase::invoke(), and StaticInst::nullStaticInstPtr.
Member Function Documentation
getFaultVAddr()
Addr GenericPageTableFault::getFaultVAddr () const inline
Definition at line 102 of file faults.hh.
References MipsISA::vaddr.
Referenced by ArmISA::getFaultVAddr().
invoke()
void GenericPageTableFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from FaultBase.
Definition at line 67 of file faults.cc.
References Process::fixupStackFault(), FullSystem, ThreadContext::getProcessPtr(), MipsISA::p, panic, and MipsISA::vaddr.
name()
FaultName GenericPageTableFault::name () const inline virtual
Implements FaultBase.
Definition at line 98 of file faults.hh.
Member Data Documentation
vaddr
Addr GenericPageTableFault::vaddr private
Definition at line 96 of file faults.hh.
The documentation for this class was generated from the following files:
sim/faults.hh
sim/faults.cc