gem5: sc_gem5::VcdTraceScope Class Reference
sc_gem5::VcdTraceScope Class Reference
#include <vcd.hh>
Public Member Functions
void addValue (const std::string &name, VcdTraceValBase *value)
void output (const std::string &name, std::ostream &os)
Private Attributes
std::vector< std::pair< std::string, VcdTraceValBase * > > values
std::map< std::string, VcdTraceScope * > scopes
Detailed Description
Definition at line 42 of file vcd.hh.
Member Function Documentation
addValue()
void sc_gem5::VcdTraceScope::addValue (const std::string & name, VcdTraceValBase * value)
Definition at line 144 of file vcd.cc.
Referenced by sc_gem5::VcdTraceFile::addNewTraceVal().
output()
void sc_gem5::VcdTraceScope::output (const std::string & name, std::ostream & os)
Definition at line 159 of file vcd.cc.
References ccprintf(), csprintf(), MipsISA::p, SC_REPORT_ERROR, sc_gem5::VcdTraceValBase::vcdName(), sc_gem5::VcdTraceValBase::vcdType(), MipsISA::w, and sc_gem5::TraceValBase::width().
Member Data Documentation
scopes
std::map<std::string, VcdTraceScope *> sc_gem5::VcdTraceScope::scopes private
Definition at line 46 of file vcd.hh.
values
std::vector<std::pair<std::string, VcdTraceValBase *> > sc_gem5::VcdTraceScope::values private
Definition at line 45 of file vcd.hh.
The documentation for this class was generated from the following files:
systemc/utils/vcd.hh
systemc/utils/vcd.cc