gem5: sc_dt::sc_int_bitref Class Reference
sc_dt::sc_int_bitref Class Reference
#include <sc_int_base.hh>
Public Member Functions
sc_int_bitref (const sc_int_bitref &a)
sc_int_bitref & operator= (const sc_int_bitref_r &b)
sc_int_bitref & operator= (const sc_int_bitref &b)
sc_int_bitref & operator= (bool b)
sc_int_bitref & operator&= (bool b)
sc_int_bitref & operator|= (bool b)
sc_int_bitref & operator^= (bool b)
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_int_bitref_r
sc_int_bitref_r (const sc_int_bitref_r &a)
virtual ~sc_int_bitref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Attributes
static sc_core::sc_vpool< sc_int_bitref > m_pool
Private Member Functions
sc_int_bitref ()
Friends
class sc_int_base
class sc_core::sc_vpool< sc_int_bitref >
Additional Inherited Members
Protected Member Functions inherited from sc_dt::sc_int_bitref_r
sc_int_bitref_r ()
void initialize (const sc_int_base *obj_p, int index_)
Protected Attributes inherited from sc_dt::sc_int_bitref_r
int m_index
sc_int_base * m_obj_p
Detailed Description
Definition at line 243 of file sc_int_base.hh.
Constructor & Destructor Documentation
sc_int_bitref() [1/2]
sc_dt::sc_int_bitref::sc_int_bitref () inline private
Definition at line 249 of file sc_int_base.hh.
sc_int_bitref() [2/2]
sc_dt::sc_int_bitref::sc_int_bitref (const sc_int_bitref & a) inline
Definition at line 253 of file sc_int_base.hh.
References ArmISA::b, MipsISA::is, sc_dt::operator&=(), sc_dt::operator^=(), and sc_dt::operator|=().
Member Function Documentation
concat_set() [1/4]
void sc_dt::sc_int_bitref::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 112 of file sc_int_base.cc.
References PowerISA::aa.
concat_set() [2/4]
void sc_dt::sc_int_bitref::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 118 of file sc_int_base.cc.
References PowerISA::aa, and sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_int_bitref::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 127 of file sc_int_base.cc.
References PowerISA::aa, and sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_int_bitref::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 136 of file sc_int_base.cc.
References PowerISA::aa.
operator&=()
sc_int_bitref& sc_dt::sc_int_bitref::operator &= (bool b)
Referenced by operator=().
operator=() [1/3]
sc_int_bitref & sc_dt::sc_int_bitref::operator= (const sc_int_bitref_r & b) inline
Definition at line 989 of file sc_int_base.hh.
operator=() [2/3]
sc_int_bitref & sc_dt::sc_int_bitref::operator= (const sc_int_bitref & b) inline
Definition at line 997 of file sc_int_base.hh.
operator=() [3/3]
sc_int_bitref & sc_dt::sc_int_bitref::operator= (bool b) inline
Definition at line 1005 of file sc_int_base.hh.
References ArmISA::b, and operator&=().
operator^=()
sc_int_bitref & sc_dt::sc_int_bitref::operator^= (bool b) inline
Definition at line 1034 of file sc_int_base.hh.
References sc_dt::UINT_ONE.
operator|=()
sc_int_bitref & sc_dt::sc_int_bitref::operator|= (bool b) inline
Definition at line 1024 of file sc_int_base.hh.
scan()
void sc_dt::sc_int_bitref::scan (::std::istream & is = ::std::cin)
Definition at line 145 of file sc_int_base.cc.
References ArmISA::b.
Referenced by sc_dt::operator>>().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_int_bitref >
friend class sc_core::sc_vpool< sc_int_bitref > friend
Definition at line 246 of file sc_int_base.hh.
sc_int_base
friend class sc_int_base friend
Definition at line 245 of file sc_int_base.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_int_bitref > sc_dt::sc_int_bitref::m_pool static
Definition at line 274 of file sc_int_base.hh.
Referenced by sc_dt::sc_int_base::bit(), and sc_dt::sc_int_base::operator[]().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_int_base.hh
systemc/dt/int/sc_int_base.cc