gem5: BaseTLB::Translation Class Reference
BaseTLB::Translation Class Reference abstract
#include <tlb.hh>
Public Member Functions
virtual ~Translation ()
virtual void markDelayed ()=0
Signal that the translation has been delayed due to a hw page table walk.
virtual void finish (const Fault &fault, const RequestPtr &req, ThreadContext *tc, Mode mode)=0
virtual bool squashed () const
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
Detailed Description
Definition at line 61 of file tlb.hh.
Constructor & Destructor Documentation
~Translation()
virtual BaseTLB::Translation::~Translation () inline virtual
Definition at line 64 of file tlb.hh.
References finish(), markDelayed(), and ArmISA::mode.
Member Function Documentation
finish()
virtual void BaseTLB::Translation::finish (const Fault & fault, const RequestPtr & req, ThreadContext * tc, Mode mode) pure virtual
Implemented in LSQ< Impl >::SplitDataRequest, LSQ< Impl >::SingleDataRequest, Minor::LSQ::SplitDataRequest, Minor::LSQ::SingleDataRequest, Minor::LSQ::SpecialDataRequest, DataTranslation< ExecContextPtr >, Minor::Fetch1::FetchRequest, DefaultFetch< Impl >::FetchTranslation, TimingSimpleCPU::FetchTranslation, QueuedPrefetcher::DeferredPacket, ArmISA::Stage2LookUp, and ArmISA::Stage2MMU::Stage2Translation.
Referenced by ArmISA::TableWalker::doL1DescriptorWrapper(), ArmISA::TableWalker::doL2DescriptorWrapper(), ArmISA::TableWalker::doLongDescriptorWrapper(), ArmISA::Stage2LookUp::finish(), ArmISA::TableWalker::processWalkWrapper(), X86ISA::Walker::startWalkWrapper(), ArmISA::TLB::translateComplete(), RiscvISA::TLB::translateTiming(), MipsISA::TLB::translateTiming(), X86ISA::TLB::translateTiming(), AlphaISA::TLB::translateTiming(), PowerISA::TLB::translateTiming(), SparcISA::TLB::translateTiming(), and ~Translation().
markDelayed()
virtual void BaseTLB::Translation::markDelayed () pure virtual
Signal that the translation has been delayed due to a hw page table walk.
Implemented in LSQ< Impl >::LSQRequest, DataTranslation< ExecContextPtr >, Minor::LSQ::LSQRequest, Minor::Fetch1::FetchRequest, DefaultFetch< Impl >::FetchTranslation, QueuedPrefetcher::DeferredPacket, TimingSimpleCPU::FetchTranslation, ArmISA::Stage2LookUp, and ArmISA::Stage2MMU::Stage2Translation.
Referenced by ArmISA::TLB::translateComplete(), X86ISA::TLB::translateTiming(), and ~Translation().
squashed()
virtual bool BaseTLB::Translation::squashed () const inline virtual
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
@ return Is the instruction that requested this translation squashed?
Reimplemented in LSQ< Impl >::LSQRequest, and DataTranslation< ExecContextPtr >.
Definition at line 86 of file tlb.hh.
References BaseTLB::demapPage(), ArmISA::mode, BaseTLB::translateAtomic(), BaseTLB::translateTiming(), and MipsISA::vaddr.
Referenced by ArmISA::TableWalker::processWalkWrapper(), and X86ISA::Walker::startWalkWrapper().
The documentation for this class was generated from the following file:
arch/generic/tlb.hh