gem5: CopyEngine::CopyEngineChannel Class Reference
CopyEngine::CopyEngineChannel Class Reference
Public Member Functions
CopyEngineChannel (CopyEngine *_ce, int cid)
virtual ~CopyEngineChannel ()
Port & getPort ()
std::string name ()
virtual Tick read (PacketPtr pkt)
virtual Tick write (PacketPtr pkt)
void channelRead (PacketPtr pkt, Addr daddr, int size)
void channelWrite (PacketPtr pkt, Addr daddr, int size)
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Types
enum ChannelState {
Idle, AddressFetch, DescriptorFetch, DMARead,
DMAWrite, CompletionWrite
}
Private Member Functions
void fetchDescriptor (Addr address)
void fetchDescComplete ()
void fetchNextAddr (Addr address)
void fetchAddrComplete ()
void readCopyBytes ()
void readCopyBytesComplete ()
void writeCopyBytes ()
void writeCopyBytesComplete ()
void writeCompletionStatus ()
void writeStatusComplete ()
void continueProcessing ()
void recvCommand ()
bool inDrain ()
void restartStateMachine ()
void anBegin (const char *s)
void anWait ()
void anDq ()
void anPq ()
void anQ (const char *s, uint64_t id, int size=1)
Private Attributes
DmaPort cePort
CopyEngine * ce
CopyEngineReg::ChanRegs cr
int channelId
CopyEngineReg::DmaDesc * curDmaDesc
uint8_t * copyBuffer
bool busy
bool underReset
bool refreshNext
Addr lastDescriptorAddr
Addr fetchAddress
Tick latBeforeBegin
Tick latAfterCompletion
uint64_t completionDataReg
ChannelState nextState
EventFunctionWrapper fetchCompleteEvent
EventFunctionWrapper addrCompleteEvent
EventFunctionWrapper readCompleteEvent
EventFunctionWrapper writeCompleteEvent
EventFunctionWrapper statusCompleteEvent
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 63 of file copy_engine.hh.
Member Enumeration Documentation
ChannelState
enum CopyEngine::CopyEngineChannel::ChannelState private
Enumerator
Idle
AddressFetch
DescriptorFetch
DMARead
DMAWrite
CompletionWrite
Definition at line 84 of file copy_engine.hh.
Constructor & Destructor Documentation
CopyEngineChannel()
CopyEngine::CopyEngineChannel::CopyEngineChannel (CopyEngine * _ce, int cid)
Definition at line 81 of file copy_engine.cc.
References addrCompleteEvent, ce, CopyEngineReg::ChanRegs::completionAddr, copyBuffer, cr, curDmaDesc, CopyEngineReg::ChanRegs::descChainAddr, fetchAddrComplete(), fetchDescComplete(), name(), CopyEngine::params(), readCompleteEvent, readCopyBytesComplete(), CopyEngineReg::ChanRegs::status, statusCompleteEvent, writeCompleteEvent, writeCopyBytesComplete(), and writeStatusComplete().
~CopyEngineChannel()
CopyEngine::CopyEngineChannel::~CopyEngineChannel () virtual
Definition at line 110 of file copy_engine.cc.
References copyBuffer, and curDmaDesc.
Member Function Documentation
anBegin()
void CopyEngine::CopyEngineChannel::anBegin (const char * s) inline private
Definition at line 141 of file copy_engine.hh.
References CPA::cpa(), CPA::FL_NONE, CPA::hwBegin(), and PioDevice::sys.
Referenced by continueProcessing(), fetchAddrComplete(), fetchDescComplete(), fetchDescriptor(), fetchNextAddr(), readCopyBytes(), writeCompletionStatus(), and writeCopyBytes().
anDq()
void CopyEngine::CopyEngineChannel::anDq () inline private
Definition at line 153 of file copy_engine.hh.
References CPA::cpa(), CPA::FL_NONE, CPA::hwDq(), and PioDevice::sys.
Referenced by fetchDescriptor().
anPq()
void CopyEngine::CopyEngineChannel::anPq () inline private
Definition at line 159 of file copy_engine.hh.
References CPA::cpa(), CPA::FL_NONE, CPA::hwDq(), and PioDevice::sys.
anQ()
void CopyEngine::CopyEngineChannel::anQ (const char * s, uint64_t id, int size = 1) inline private
Definition at line 165 of file copy_engine.hh.
References CPA::cpa(), CPA::FL_NONE, CPA::hwQ(), and PioDevice::sys.
Referenced by writeCopyBytesComplete().
anWait()
void CopyEngine::CopyEngineChannel::anWait () inline private
Definition at line 147 of file copy_engine.hh.
References CPA::cpa(), CPA::FL_NONE, CPA::hwWe(), and PioDevice::sys.
Referenced by continueProcessing(), fetchAddrComplete(), and fetchDescComplete().
channelRead()
void CopyEngine::CopyEngineChannel::channelRead (PacketPtr pkt, Addr daddr, int size)
Definition at line 242 of file copy_engine.cc.
References bits(), busy, CopyEngineReg::CHAN_CHAINADDR, CopyEngineReg::CHAN_CHAINADDR_HIGH, CopyEngineReg::CHAN_CMPLNADDR, CopyEngineReg::CHAN_CMPLNADDR_HIGH, CopyEngineReg::CHAN_COMMAND, CopyEngineReg::CHAN_CONTROL, CopyEngineReg::CHAN_ERROR, CopyEngineReg::CHAN_STATUS, channelId, CopyEngineReg::ChanRegs::command, CopyEngineReg::ChanRegs::completionAddr, cr, CopyEngineReg::ChanRegs::ctrl, CopyEngineReg::ChanRegs::descChainAddr, CopyEngineReg::ChanRegs::error, panic, Packet::setLE(), and CopyEngineReg::ChanRegs::status.
Referenced by write().
channelWrite()
void CopyEngine::CopyEngineChannel::channelWrite (PacketPtr pkt, Addr daddr, int size)
Definition at line 370 of file copy_engine.cc.
References CopyEngineReg::CHAN_CHAINADDR, CopyEngineReg::CHAN_CHAINADDR_HIGH, CopyEngineReg::CHAN_CMPLNADDR, CopyEngineReg::CHAN_CMPLNADDR_HIGH, CopyEngineReg::CHAN_COMMAND, CopyEngineReg::CHAN_CONTROL, CopyEngineReg::CHAN_ERROR, CopyEngineReg::CHAN_STATUS, channelId, CopyEngineReg::ChanRegs::command, CopyEngineReg::ChanRegs::completionAddr, cr, CopyEngineReg::ChanRegs::ctrl, CopyEngineReg::ChanRegs::descChainAddr, DPRINTF, CopyEngineReg::ChanRegs::error, Packet::getLE(), ArmISA::mask, panic, and recvCommand().
Referenced by write().
continueProcessing()
void CopyEngine::CopyEngineChannel::continueProcessing () private
Definition at line 559 of file copy_engine.cc.
References AddressFetch, anBegin(), anWait(), busy, curDmaDesc, DescriptorFetch, fetchAddress, fetchDescriptor(), fetchNextAddr(), Idle, inDrain(), lastDescriptorAddr, CopyEngineReg::DmaDesc::next, nextState, refreshNext, and underReset.
Referenced by writeCopyBytesComplete(), and writeStatusComplete().
drain()
DrainState CopyEngine::CopyEngineChannel::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 656 of file copy_engine.cc.
References ce, DPRINTF, Drained, Draining, Drainable::drainState(), Idle, nextState, and Running.
Referenced by write().
drainResume()
void CopyEngine::CopyEngineChannel::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 747 of file copy_engine.cc.
References CopyEngine::CopyEngine(), DPRINTF, nextState, and restartStateMachine().
Referenced by write().
fetchAddrComplete()
void CopyEngine::CopyEngineChannel::fetchAddrComplete () private
Definition at line 625 of file copy_engine.cc.
References anBegin(), anWait(), busy, curDmaDesc, DescriptorFetch, DPRINTF, fetchAddress, fetchDescriptor(), Idle, inDrain(), CopyEngineReg::DmaDesc::next, and nextState.
Referenced by CopyEngineChannel().
fetchDescComplete()
void CopyEngine::CopyEngineChannel::fetchDescComplete () private
Definition at line 471 of file copy_engine.cc.
References anBegin(), anWait(), busy, CopyEngineReg::DmaDesc::command, CompletionWrite, curDmaDesc, CopyEngineReg::DESC_CTRL_CP_STS, CopyEngineReg::DESC_CTRL_NULL, DMARead, DPRINTF, Idle, inDrain(), nextState, panic, readCopyBytes(), and writeCompletionStatus().
Referenced by CopyEngineChannel(), and write().
fetchDescriptor()
void CopyEngine::CopyEngineChannel::fetchDescriptor (Addr address) private
Definition at line 452 of file copy_engine.cc.
References anBegin(), anDq(), busy, ce, cePort, curDmaDesc, DmaPort::dmaAction(), DPRINTF, fetchCompleteEvent, lastDescriptorAddr, latBeforeBegin, PciDevice::pciToDma(), and MemCmd::ReadReq.
Referenced by continueProcessing(), fetchAddrComplete(), recvCommand(), restartStateMachine(), and write().
fetchNextAddr()
void CopyEngine::CopyEngineChannel::fetchNextAddr (Addr address) private
Definition at line 613 of file copy_engine.cc.
References addrCompleteEvent, anBegin(), busy, ce, cePort, curDmaDesc, DmaPort::dmaAction(), DPRINTF, PciDevice::pciToDma(), and MemCmd::ReadReq.
Referenced by continueProcessing(), recvCommand(), and restartStateMachine().
getPort()
Port & CopyEngine::CopyEngineChannel::getPort ()
Definition at line 133 of file copy_engine.cc.
References cePort.
Referenced by CopyEngine::params().
inDrain()
bool CopyEngine::CopyEngineChannel::inDrain () private
Definition at line 645 of file copy_engine.cc.
References ce, DPRINTF, Draining, Drainable::drainState(), Running, and Drainable::signalDrainDone().
Referenced by continueProcessing(), fetchAddrComplete(), fetchDescComplete(), readCopyBytesComplete(), and writeCopyBytesComplete().
name()
std::string CopyEngine::CopyEngineChannel::name () inline
Definition at line 100 of file copy_engine.hh.
References csprintf(), and SimObject::name().
Referenced by CopyEngineChannel(), and CopyEngine::regStats().
read()
virtual Tick CopyEngine::CopyEngineChannel::read (PacketPtr pkt) inline virtual
Definition at line 101 of file copy_engine.hh.
References panic.
Referenced by CopyEngine::params().
readCopyBytes()
void CopyEngine::CopyEngineChannel::readCopyBytes () private
Definition at line 502 of file copy_engine.cc.
References anBegin(), ce, cePort, copyBuffer, curDmaDesc, CopyEngineReg::DmaDesc::dest, DmaPort::dmaAction(), DPRINTF, CopyEngineReg::DmaDesc::len, PciDevice::pciToDma(), readCompleteEvent, MemCmd::ReadReq, and CopyEngineReg::DmaDesc::src.
Referenced by fetchDescComplete(), and restartStateMachine().
readCopyBytesComplete()
void CopyEngine::CopyEngineChannel::readCopyBytesComplete () private
Definition at line 513 of file copy_engine.cc.
References DMAWrite, DPRINTF, inDrain(), nextState, and writeCopyBytes().
Referenced by CopyEngineChannel().
recvCommand()
void CopyEngine::CopyEngineChannel::recvCommand () private
Definition at line 139 of file copy_engine.cc.
References AddressFetch, busy, ce, CopyEngineReg::ChanRegs::command, cr, CopyEngineReg::ChanRegs::descChainAddr, DescriptorFetch, Drainable::drainState(), fetchAddress, fetchDescriptor(), fetchNextAddr(), Idle, lastDescriptorAddr, nextState, panic, refreshNext, Running, CopyEngineReg::ChanRegs::status, and underReset.
Referenced by channelWrite().
restartStateMachine()
void CopyEngine::CopyEngineChannel::restartStateMachine () private
Definition at line 721 of file copy_engine.cc.
References AddressFetch, CompletionWrite, DescriptorFetch, DMARead, DMAWrite, fetchAddress, fetchDescriptor(), fetchNextAddr(), Idle, lastDescriptorAddr, nextState, panic, readCopyBytes(), writeCompletionStatus(), and writeCopyBytes().
Referenced by drainResume().
serialize()
void CopyEngine::CopyEngineChannel::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 685 of file copy_engine.cc.
References arrayParamOut(), busy, ce, channelId, completionDataReg, copyBuffer, cr, curDmaDesc, fetchAddress, lastDescriptorAddr, nextState, CopyEngine::params(), refreshNext, CopyEngineReg::ChanRegs::serialize(), SERIALIZE_ARRAY, SERIALIZE_SCALAR, and underReset.
Referenced by CopyEngine::params(), and write().
unserialize()
void CopyEngine::CopyEngineChannel::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 702 of file copy_engine.cc.
References arrayParamIn(), busy, ce, channelId, completionDataReg, copyBuffer, cr, curDmaDesc, fetchAddress, lastDescriptorAddr, nextState, CopyEngine::params(), refreshNext, underReset, CopyEngineReg::ChanRegs::unserialize(), UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by CopyEngine::params(), and write().
write()
virtual Tick CopyEngine::CopyEngineChannel::write (PacketPtr pkt) inline virtual
Definition at line 103 of file copy_engine.hh.
References channelRead(), channelWrite(), drain(), drainResume(), fetchDescComplete(), fetchDescriptor(), panic, serialize(), and unserialize().
Referenced by CopyEngine::params().
writeCompletionStatus()
void CopyEngine::CopyEngineChannel::writeCompletionStatus () private
Definition at line 592 of file copy_engine.cc.
References anBegin(), ce, cePort, CopyEngineReg::ChanRegs::completionAddr, completionDataReg, cr, DmaPort::dmaAction(), DPRINTF, latAfterCompletion, PciDevice::pciToDma(), statusCompleteEvent, and MemCmd::WriteReq.
Referenced by fetchDescComplete(), restartStateMachine(), and writeCopyBytesComplete().
writeCopyBytes()
void CopyEngine::CopyEngineChannel::writeCopyBytes () private
Definition at line 523 of file copy_engine.cc.
References anBegin(), CopyEngine::bytesCopied, ce, cePort, channelId, CopyEngine::copiesProcessed, copyBuffer, curDmaDesc, CopyEngineReg::DmaDesc::dest, DmaPort::dmaAction(), DPRINTF, CopyEngineReg::DmaDesc::len, PciDevice::pciToDma(), writeCompleteEvent, and MemCmd::WriteReq.
Referenced by readCopyBytesComplete(), and restartStateMachine().
writeCopyBytesComplete()
void CopyEngine::CopyEngineChannel::writeCopyBytesComplete () private
Definition at line 538 of file copy_engine.cc.
References anQ(), channelId, CopyEngineReg::DmaDesc::command, completionDataReg, CompletionWrite, continueProcessing(), cr, curDmaDesc, CopyEngineReg::DESC_CTRL_CP_STS, DPRINTF, inDrain(), lastDescriptorAddr, CopyEngineReg::DmaDesc::len, nextState, CopyEngineReg::ChanRegs::status, CopyEngineReg::DmaDesc::user1, and writeCompletionStatus().
Referenced by CopyEngineChannel().
writeStatusComplete()
void CopyEngine::CopyEngineChannel::writeStatusComplete () private
Definition at line 606 of file copy_engine.cc.
References continueProcessing(), and DPRINTF.
Referenced by CopyEngineChannel().
Member Data Documentation
addrCompleteEvent
EventFunctionWrapper CopyEngine::CopyEngineChannel::addrCompleteEvent private
Definition at line 122 of file copy_engine.hh.
Referenced by CopyEngineChannel(), and fetchNextAddr().
busy
bool CopyEngine::CopyEngineChannel::busy private
Definition at line 73 of file copy_engine.hh.
Referenced by channelRead(), continueProcessing(), fetchAddrComplete(), fetchDescComplete(), fetchDescriptor(), fetchNextAddr(), recvCommand(), serialize(), and unserialize().
ce
CopyEngine* CopyEngine::CopyEngineChannel::ce private
Definition at line 67 of file copy_engine.hh.
Referenced by CopyEngineChannel(), drain(), fetchDescriptor(), fetchNextAddr(), inDrain(), readCopyBytes(), recvCommand(), serialize(), unserialize(), writeCompletionStatus(), and writeCopyBytes().
cePort
DmaPort CopyEngine::CopyEngineChannel::cePort private
Definition at line 66 of file copy_engine.hh.
Referenced by fetchDescriptor(), fetchNextAddr(), getPort(), readCopyBytes(), writeCompletionStatus(), and writeCopyBytes().
channelId
int CopyEngine::CopyEngineChannel::channelId private
Definition at line 69 of file copy_engine.hh.
Referenced by channelRead(), channelWrite(), serialize(), unserialize(), writeCopyBytes(), and writeCopyBytesComplete().
completionDataReg
uint64_t CopyEngine::CopyEngineChannel::completionDataReg private
Definition at line 82 of file copy_engine.hh.
Referenced by serialize(), unserialize(), writeCompletionStatus(), and writeCopyBytesComplete().
copyBuffer
uint8_t* CopyEngine::CopyEngineChannel::copyBuffer private
Definition at line 71 of file copy_engine.hh.
Referenced by CopyEngineChannel(), readCopyBytes(), serialize(), unserialize(), writeCopyBytes(), and ~CopyEngineChannel().
cr
CopyEngineReg::ChanRegs CopyEngine::CopyEngineChannel::cr private
Definition at line 68 of file copy_engine.hh.
Referenced by channelRead(), channelWrite(), CopyEngineChannel(), recvCommand(), serialize(), unserialize(), writeCompletionStatus(), and writeCopyBytesComplete().
curDmaDesc
CopyEngineReg::DmaDesc* CopyEngine::CopyEngineChannel::curDmaDesc private
Definition at line 70 of file copy_engine.hh.
Referenced by continueProcessing(), CopyEngineChannel(), fetchAddrComplete(), fetchDescComplete(), fetchDescriptor(), fetchNextAddr(), readCopyBytes(), serialize(), unserialize(), writeCopyBytes(), writeCopyBytesComplete(), and ~CopyEngineChannel().
fetchAddress
Addr CopyEngine::CopyEngineChannel::fetchAddress private
Definition at line 77 of file copy_engine.hh.
Referenced by continueProcessing(), fetchAddrComplete(), recvCommand(), restartStateMachine(), serialize(), and unserialize().
fetchCompleteEvent
EventFunctionWrapper CopyEngine::CopyEngineChannel::fetchCompleteEvent private
Definition at line 118 of file copy_engine.hh.
Referenced by fetchDescriptor().
lastDescriptorAddr
Addr CopyEngine::CopyEngineChannel::lastDescriptorAddr private
Definition at line 76 of file copy_engine.hh.
Referenced by continueProcessing(), fetchDescriptor(), recvCommand(), restartStateMachine(), serialize(), unserialize(), and writeCopyBytesComplete().
latAfterCompletion
Tick CopyEngine::CopyEngineChannel::latAfterCompletion private
Definition at line 80 of file copy_engine.hh.
Referenced by writeCompletionStatus().
latBeforeBegin
Tick CopyEngine::CopyEngineChannel::latBeforeBegin private
Definition at line 79 of file copy_engine.hh.
Referenced by fetchDescriptor().
nextState
ChannelState CopyEngine::CopyEngineChannel::nextState private
Definition at line 93 of file copy_engine.hh.
Referenced by continueProcessing(), drain(), drainResume(), fetchAddrComplete(), fetchDescComplete(), readCopyBytesComplete(), recvCommand(), restartStateMachine(), serialize(), unserialize(), and writeCopyBytesComplete().
readCompleteEvent
EventFunctionWrapper CopyEngine::CopyEngineChannel::readCompleteEvent private
Definition at line 126 of file copy_engine.hh.
Referenced by CopyEngineChannel(), and readCopyBytes().
refreshNext
bool CopyEngine::CopyEngineChannel::refreshNext private
Definition at line 75 of file copy_engine.hh.
Referenced by continueProcessing(), recvCommand(), serialize(), and unserialize().
statusCompleteEvent
EventFunctionWrapper CopyEngine::CopyEngineChannel::statusCompleteEvent private
Definition at line 134 of file copy_engine.hh.
Referenced by CopyEngineChannel(), and writeCompletionStatus().
underReset
bool CopyEngine::CopyEngineChannel::underReset private
Definition at line 74 of file copy_engine.hh.
Referenced by continueProcessing(), recvCommand(), serialize(), and unserialize().
writeCompleteEvent
EventFunctionWrapper CopyEngine::CopyEngineChannel::writeCompleteEvent private
Definition at line 130 of file copy_engine.hh.
Referenced by CopyEngineChannel(), and writeCopyBytes().
The documentation for this class was generated from the following files:
dev/pci/copy_engine.hh
dev/pci/copy_engine.cc