gem5: DumpStatsPCEvent64 Class Reference
DumpStatsPCEvent64 Class Reference
#include <system.hh>
Public Member Functions
DumpStatsPCEvent64 (PCEventScope *s, const std::string &desc, Addr addr)
Public Member Functions inherited from DumpStatsPCEvent
DumpStatsPCEvent (PCEventScope *s, const std::string &desc, Addr addr)
virtual void process (ThreadContext *tc)
This function is called whenever the the kernel function "__switch_to" is called to change running tasks.
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Private Member Functions
void getTaskDetails (ThreadContext *tc, uint32_t &pid, uint32_t &tgid, std::string &next_task_str, int32_t &mm) override
Extracts the information used by the DumpStatsPCEvent64 by reading the task_struct pointer passed to __switch_to() in 64 bit ARM Linux.
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 141 of file system.hh.
Constructor & Destructor Documentation
DumpStatsPCEvent64()
DumpStatsPCEvent64::DumpStatsPCEvent64 (PCEventScope * s, const std::string & desc, Addr addr) inline
Definition at line 143 of file system.hh.
Member Function Documentation
getTaskDetails()
void DumpStatsPCEvent64::getTaskDetails (ThreadContext * tc, uint32_t & pid, uint32_t & tgid, std::string & next_task_str, int32_t & mm) override private virtual
Extracts the information used by the DumpStatsPCEvent64 by reading the task_struct pointer passed to __switch_to() in 64 bit ARM Linux.
r0 = task_struct of the previously running process r1 = task_struct of next process to run
Reimplemented from DumpStatsPCEvent.
Definition at line 306 of file system.cc.
References Linux::ThreadInfo::curTaskMmFromTaskStruct(), Linux::ThreadInfo::curTaskNameFromTaskStruct(), Linux::ThreadInfo::curTaskPIDFromTaskStruct(), Linux::ThreadInfo::curTaskTGIDFromTaskStruct(), ThreadContext::readIntReg(), and MipsISA::ti.
The documentation for this class was generated from the following files:
arch/arm/linux/system.hh
arch/arm/linux/system.cc