gem5: Stats::DistStor Class Reference
Stats::DistStor Class Reference
Templatized storage and interface for a distribution stat.
#include <statistics.hh>
Classes
struct Params
The parameters for a distribution stat.
Public Member Functions
DistStor (Info *info)
void sample (Counter val, int number)
Add a value to the distribution for the given number of times.
size_type size () const
Return the number of buckets in this distribution.
bool zero () const
Returns true if any calls to sample have been made.
void prepare (Info *info, DistData &data)
void reset (Info *info)
Reset stat value to default.
Private Attributes
Counter min_track
The minimum value to track.
Counter max_track
The maximum value to track.
Counter bucket_size
The number of entries in each bucket.
Counter min_val
The smallest value sampled.
Counter max_val
The largest value sampled.
Counter underflow
The number of values sampled less than min.
Counter overflow
The number of values sampled more than max.
Counter sum
The current sum.
Counter squares
The sum of squares.
Counter samples
The number of samples.
VCounter cvec
Counter for each bucket.
Detailed Description
Templatized storage and interface for a distribution stat.
Definition at line 1395 of file statistics.hh.
Constructor & Destructor Documentation
DistStor()
Stats::DistStor::DistStor (Info * info) inline
Definition at line 1440 of file statistics.hh.
References Stats::InfoProxy< Stat, Base >::reset().
Member Function Documentation
prepare()
void Stats::DistStor::prepare (Info * info, DistData & data) inline
Definition at line 1493 of file statistics.hh.
References Stats::DistData::bucket_size, Stats::DistStor::Params::bucket_size, Stats::DistStor::Params::buckets, Stats::DistData::cvec, Stats::Dist, ArmISA::i, Stats::DistData::max, Stats::DistStor::Params::max, Stats::DistData::max_val, Stats::DistData::min, Stats::DistStor::Params::min, Stats::DistData::min_val, Stats::DistData::overflow, sc_dt::overflow(), safe_cast(), Stats::DistData::samples, Stats::DistData::squares, Stats::Info::storageParams, Stats::DistData::sum, Stats::DistData::type, Stats::DistParams::type, and Stats::DistData::underflow.
reset()
void Stats::DistStor::reset (Info * info) inline
Reset stat value to default.
Definition at line 1521 of file statistics.hh.
References Stats::DistStor::Params::bucket_size, ArmISA::i, Stats::DistStor::Params::max, Stats::DistStor::Params::min, safe_cast(), and Stats::Info::storageParams.
sample()
void Stats::DistStor::sample (Counter val, int number) inline
Add a value to the distribution for the given number of times.
Parameters
val The value to add.
number The number of times to add the value.
Definition at line 1452 of file statistics.hh.
References MipsISA::index, and X86ISA::val.
size()
size_type Stats::DistStor::size () const inline
Return the number of buckets in this distribution.
Returns
the number of buckets.
Definition at line 1480 of file statistics.hh.
zero()
bool Stats::DistStor::zero () const inline
Returns true if any calls to sample have been made.
Returns
True if any values have been sampled.
Definition at line 1487 of file statistics.hh.
Member Data Documentation
bucket_size
Counter Stats::DistStor::bucket_size private
The number of entries in each bucket.
Definition at line 1420 of file statistics.hh.
cvec
VCounter Stats::DistStor::cvec private
Counter for each bucket.
Definition at line 1437 of file statistics.hh.
max_track
Counter Stats::DistStor::max_track private
The maximum value to track.
Definition at line 1418 of file statistics.hh.
max_val
Counter Stats::DistStor::max_val private
The largest value sampled.
Definition at line 1425 of file statistics.hh.
min_track
Counter Stats::DistStor::min_track private
The minimum value to track.
Definition at line 1416 of file statistics.hh.
min_val
Counter Stats::DistStor::min_val private
The smallest value sampled.
Definition at line 1423 of file statistics.hh.
overflow
Counter Stats::DistStor::overflow private
The number of values sampled more than max.
Definition at line 1429 of file statistics.hh.
samples
Counter Stats::DistStor::samples private
The number of samples.
Definition at line 1435 of file statistics.hh.
squares
Counter Stats::DistStor::squares private
The sum of squares.
Definition at line 1433 of file statistics.hh.
sum
Counter Stats::DistStor::sum private
The current sum.
Definition at line 1431 of file statistics.hh.
underflow
Counter Stats::DistStor::underflow private
The number of values sampled less than min.
Definition at line 1427 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh