gem5: WriteAllocator Class Reference
WriteAllocator Class Reference
The write allocator inspects write packets and detects streaming patterns.
#include <base.hh>
Public Member Functions
WriteAllocator (const WriteAllocatorParams *p)
bool coalesce () const
Should writes be coalesced? This is true if the mode is set to NO_ALLOCATE.
bool allocate () const
Should writes allocate?
void reset ()
Reset the write allocator state, meaning that it allocates for writes and has not recorded any information about qualifying writes that might trigger a switch to coalescing and later no allocation.
bool delay (Addr blk_addr)
Access whether we need to delay the current write.
void resetDelay (Addr blk_addr)
Clear delay counter for the input block.
void updateMode (Addr write_addr, unsigned write_size, Addr blk_addr)
Update the write mode based on the current write packet.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Types
enum WriteMode : char { WriteMode::ALLOCATE, WriteMode::COALESCE, WriteMode::NO_ALLOCATE }
The current mode for write coalescing and allocation, either normal operation (ALLOCATE), write coalescing (COALESCE), or write coalescing without allocation (NO_ALLOCATE).
Private Attributes
WriteMode mode
Addr nextAddr
Address to match writes against to detect streams.
uint32_t byteCount
Bytes written contiguously.
const uint32_t coalesceLimit
Limits for when to switch between the different write modes.
const uint32_t noAllocateLimit
const uint32_t delayThreshold
The number of times the allocator will delay an WriteReq MSHR.
std::unordered_map< Addr, Counter > delayCtr
Keep track of the number of times the allocator has delayed an WriteReq MSHR.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
The write allocator inspects write packets and detects streaming patterns.
The write allocator supports a single stream where writes are expected to access consecutive locations and keeps track of size of the area covered by the concecutive writes in byteCount.
1) When byteCount has surpassed the coallesceLimit the mode switches from ALLOCATE to COALESCE where writes should be delayed until the whole block is written at which point a single packet (whole line write) can service them.
2) When byteCount has also exceeded the noAllocateLimit (whole line) we switch to NO_ALLOCATE when writes should not allocate in the cache but rather send a whole line write to the memory below.
Definition at line 1294 of file base.hh.
Member Enumeration Documentation
WriteMode
enum WriteAllocator::WriteMode : char strong private
The current mode for write coalescing and allocation, either normal operation (ALLOCATE), write coalescing (COALESCE), or write coalescing without allocation (NO_ALLOCATE).
Enumerator
ALLOCATE
COALESCE
NO_ALLOCATE
Definition at line 1378 of file base.hh.
Constructor & Destructor Documentation
WriteAllocator()
WriteAllocator::WriteAllocator (const WriteAllocatorParams * p) inline
Definition at line 1296 of file base.hh.
References Stats::reset().
Member Function Documentation
allocate()
bool WriteAllocator::allocate () const inline
Should writes allocate?
Returns
return true if the cache should not allocate for writes.
Definition at line 1320 of file base.hh.
References ArmISA::mode.
Referenced by Cache::handleAtomicReqMiss(), and BaseCache::recvTimingResp().
coalesce()
bool WriteAllocator::coalesce () const inline
Should writes be coalesced? This is true if the mode is set to NO_ALLOCATE.
Returns
return true if the cache should coalesce writes.
Definition at line 1311 of file base.hh.
References ArmISA::mode.
Referenced by BaseCache::coalesce(), and BaseCache::sendMSHRQueuePacket().
delay()
bool WriteAllocator::delay (Addr blk_addr) inline
Access whether we need to delay the current write.
Parameters
blk_addr The block address the packet writes to
Returns
true if the current packet should be delayed
Definition at line 1342 of file base.hh.
Referenced by BaseCache::sendMSHRQueuePacket().
reset()
void WriteAllocator::reset () inline
Reset the write allocator state, meaning that it allocates for writes and has not recorded any information about qualifying writes that might trigger a switch to coalescing and later no allocation.
Definition at line 1330 of file base.hh.
References ArmISA::mode.
Referenced by BaseCache::sendMSHRQueuePacket().
resetDelay()
void WriteAllocator::resetDelay (Addr blk_addr) inline
Clear delay counter for the input block.
Parameters
blk_addr The accessed cache block
Definition at line 1356 of file base.hh.
Referenced by BaseCache::sendMSHRQueuePacket().
updateMode()
void WriteAllocator::updateMode (Addr write_addr, unsigned write_size, Addr blk_addr)
Update the write mode based on the current write packet.
This method compares the packet's address with any current stream, and updates the tracking and the mode accordingly.
Parameters
write_addr Start address of the write request
write_size Size of the write request
blk_addr The block address that this packet writes to
Definition at line 2487 of file base.cc.
References DPRINTF, and ArmISA::mode.
Referenced by BaseCache::handleTimingReqMiss().
Member Data Documentation
byteCount
uint32_t WriteAllocator::byteCount private
Bytes written contiguously.
Saturating once we no longer allocate.
Definition at line 1392 of file base.hh.
coalesceLimit
const uint32_t WriteAllocator::coalesceLimit private
Limits for when to switch between the different write modes.
Definition at line 1397 of file base.hh.
delayCtr
std::unordered_map<Addr, Counter> WriteAllocator::delayCtr private
Keep track of the number of times the allocator has delayed an WriteReq MSHR.
Definition at line 1408 of file base.hh.
delayThreshold
const uint32_t WriteAllocator::delayThreshold private
The number of times the allocator will delay an WriteReq MSHR.
Definition at line 1402 of file base.hh.
mode
WriteMode WriteAllocator::mode private
Definition at line 1383 of file base.hh.
nextAddr
Addr WriteAllocator::nextAddr private
Address to match writes against to detect streams.
Definition at line 1386 of file base.hh.
noAllocateLimit
const uint32_t WriteAllocator::noAllocateLimit private
Definition at line 1398 of file base.hh.
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc