gem5: StridePrefetcher::PCTable Class Reference
StridePrefetcher::PCTable Class Reference
#include <stride.hh>
Public Member Functions
PCTable (int assoc, int sets, const std::string name, BaseReplacementPolicy *replacementPolicy)
Default constructor.
~PCTable ()
Default destructor.
StrideEntry * findEntry (Addr pc, bool is_secure)
Search for an entry in the pc table.
StrideEntry * findVictim (Addr pc)
Find a replacement victim to make room for given PC.
Private Member Functions
const std::string name ()
Addr pcHash (Addr pc) const
PC hashing function to index sets in the table.
Private Attributes
const int pcTableSets
const std::string _name
std::vector< std::vector< StrideEntry > > entries
BaseReplacementPolicy * replacementPolicy
Replacement policy used by StridePrefetcher.
Detailed Description
Definition at line 98 of file stride.hh.
Constructor & Destructor Documentation
PCTable()
StridePrefetcher::PCTable::PCTable (int assoc, int sets, const std::string name, BaseReplacementPolicy * replacementPolicy)
Default constructor.
Create a table with given parameters.
Parameters
assoc Associativity of the table.
sets Number of sets in the table.
name Name of the prefetcher.
replacementPolicy Replacement policy used by the table.
Definition at line 118 of file stride.cc.
References entries, and BaseReplacementPolicy::instantiateEntry().
~PCTable()
StridePrefetcher::PCTable::~PCTable ()
Default destructor.
Definition at line 136 of file stride.cc.
Member Function Documentation
findEntry()
StridePrefetcher::StrideEntry * StridePrefetcher::PCTable::findEntry (Addr pc, bool is_secure) inline
Search for an entry in the pc table.
Parameters
pc The PC to look for.
is_secure True if the target memory space is secure.
Returns
Pointer to the entry.
Definition at line 251 of file stride.cc.
References DPRINTF, entries, pcHash(), replacementPolicy, StridePrefetcher::StridePrefetcher(), and BaseReplacementPolicy::touch().
Referenced by StridePrefetcher::calculatePrefetch().
findVictim()
StridePrefetcher::StrideEntry * StridePrefetcher::PCTable::findVictim (Addr pc) inline
Find a replacement victim to make room for given PC.
Parameters
pc The PC value.
Returns
The victimized entry.
Definition at line 229 of file stride.cc.
References DPRINTF, entries, ReplaceableEntry::getSet(), BaseReplacementPolicy::getVictim(), ReplaceableEntry::getWay(), pcHash(), and replacementPolicy.
Referenced by StridePrefetcher::calculatePrefetch().
name()
const std::string StridePrefetcher::PCTable::name () inline private
Definition at line 135 of file stride.hh.
pcHash()
Addr StridePrefetcher::PCTable::pcHash (Addr pc) const inline private
PC hashing function to index sets in the table.
Parameters
pc The PC value.
Returns
The set to which this PC maps.
Definition at line 221 of file stride.cc.
References floorLog2(), and pcTableSets.
Referenced by findEntry(), and findVictim().
Member Data Documentation
_name
const std::string StridePrefetcher::PCTable::_name private
Definition at line 137 of file stride.hh.
entries
std::vector<std::vector<StrideEntry> > StridePrefetcher::PCTable::entries private
Definition at line 138 of file stride.hh.
Referenced by findEntry(), findVictim(), and PCTable().
pcTableSets
const int StridePrefetcher::PCTable::pcTableSets private
Definition at line 136 of file stride.hh.
Referenced by pcHash().
replacementPolicy
BaseReplacementPolicy* StridePrefetcher::PCTable::replacementPolicy private
Replacement policy used by StridePrefetcher.
Definition at line 143 of file stride.hh.
Referenced by StridePrefetcher::calculatePrefetch(), findEntry(), and findVictim().
The documentation for this class was generated from the following files:
mem/cache/prefetch/stride.hh
mem/cache/prefetch/stride.cc