gem5: sc_gem5::Sensitivity Class Reference
sc_gem5::Sensitivity Class Reference abstract
#include <sensitivity.hh>
Public Types
enum Category { Static, Dynamic }
Public Member Functions
virtual void clear ()=0
void satisfy ()
virtual bool notifyWork (Event *e)
bool notify (Event *e)
virtual Category category ()=0
bool ofMethod ()
Protected Member Functions
Sensitivity (Process *p)
virtual ~Sensitivity ()
virtual void addToEvent (const ::sc_core::sc_event *e)=0
virtual void delFromEvent (const ::sc_core::sc_event *e)=0
Protected Attributes
Process * process
Detailed Description
Definition at line 64 of file sensitivity.hh.
Member Enumeration Documentation
Category
enum sc_gem5::Sensitivity::Category
Enumerator
Static
Dynamic
Definition at line 82 of file sensitivity.hh.
Constructor & Destructor Documentation
Sensitivity()
sc_gem5::Sensitivity::Sensitivity (Process * p) inline protected
Definition at line 69 of file sensitivity.hh.
~Sensitivity()
virtual sc_gem5::Sensitivity::~Sensitivity () inline protected virtual
Definition at line 70 of file sensitivity.hh.
References ArmISA::e.
Member Function Documentation
addToEvent()
virtual void sc_gem5::Sensitivity::addToEvent (const ::sc_core::sc_event * e) protected pure virtual
Implemented in sc_gem5::StaticSensitivity, and sc_gem5::DynamicSensitivity.
category()
virtual Category sc_gem5::Sensitivity::category () pure virtual
Implemented in sc_gem5::StaticSensitivity, and sc_gem5::DynamicSensitivity.
clear()
virtual void sc_gem5::Sensitivity::clear () pure virtual
Implemented in sc_gem5::SensitivityEvents, and sc_gem5::SensitivityEvent.
delFromEvent()
virtual void sc_gem5::Sensitivity::delFromEvent (const ::sc_core::sc_event * e) protected pure virtual
Implemented in sc_gem5::StaticSensitivity, and sc_gem5::DynamicSensitivity.
notify()
bool sc_gem5::Sensitivity::notify (Event * e)
Definition at line 65 of file sensitivity.cc.
References sc_gem5::Scheduler::current(), sc_gem5::Process::disabled(), sc_core::sc_object::name(), notifyWork(), process, sc_core::SC_ID_IMMEDIATE_SELF_NOTIFICATION_, SC_REPORT_WARNING, and sc_gem5::scheduler.
notifyWork()
bool sc_gem5::Sensitivity::notifyWork (Event * e) virtual
Reimplemented in sc_gem5::DynamicSensitivityEventAndList, and sc_gem5::DynamicSensitivityEventOrList.
Definition at line 58 of file sensitivity.cc.
References satisfy().
Referenced by notify().
ofMethod()
bool sc_gem5::Sensitivity::ofMethod ()
Definition at line 84 of file sensitivity.cc.
References process, sc_gem5::Process::procKind(), and sc_core::SC_METHOD_PROC_.
Referenced by sc_gem5::Event::addSensitivity(), and sc_gem5::Event::delSensitivity().
satisfy()
void sc_gem5::Sensitivity::satisfy ()
Definition at line 52 of file sensitivity.cc.
References process, and sc_gem5::Process::satisfySensitivity().
Referenced by notifyWork(), sc_gem5::DynamicSensitivityEventOrList::notifyWork(), and sc_gem5::DynamicSensitivityEventAndList::notifyWork().
Member Data Documentation
process
Process* sc_gem5::Sensitivity::process protected
Definition at line 67 of file sensitivity.hh.
Referenced by notify(), ofMethod(), and satisfy().
The documentation for this class was generated from the following files:
systemc/core/sensitivity.hh
systemc/core/sensitivity.cc