gem5: StoreTrace Class Reference
StoreTrace Class Reference
#include <StoreTrace.hh>
Public Member Functions
StoreTrace ()
StoreTrace (Addr addr)
~StoreTrace ()
void store (NodeID node)
void downgrade (NodeID node)
int getTotal () const
void print (std::ostream &out) const
Static Public Member Functions
static void initSummary ()
static void printSummary (std::ostream &out)
static void clearSummary ()
Private Attributes
Addr m_addr
NodeID m_last_writer
Tick m_first_store
Tick m_last_store
int m_stores_this_interval
int64_t m_total_samples
Histogram m_store_count
Histogram m_store_first_to_stolen
Histogram m_store_last_to_stolen
Histogram m_store_first_to_last
Static Private Attributes
static bool s_init = false
static int64_t s_total_samples = 0
static Histogram * s_store_count_ptr = NULL
static Histogram * s_store_first_to_stolen_ptr = NULL
static Histogram * s_store_last_to_stolen_ptr = NULL
static Histogram * s_store_first_to_last_ptr = NULL
Detailed Description
Definition at line 38 of file StoreTrace.hh.
Constructor & Destructor Documentation
StoreTrace() [1/2]
StoreTrace::StoreTrace () inline
Definition at line 41 of file StoreTrace.hh.
References addr, downgrade(), store(), and ~StoreTrace().
StoreTrace() [2/2]
StoreTrace::StoreTrace (Addr addr) explicit
Definition at line 44 of file StoreTrace.cc.
References addr, initSummary(), m_addr, m_last_writer, m_stores_this_interval, and m_total_samples.
~StoreTrace()
StoreTrace::~StoreTrace ()
Definition at line 57 of file StoreTrace.cc.
Referenced by StoreTrace().
Member Function Documentation
clearSummary()
void StoreTrace::clearSummary () static
Definition at line 96 of file StoreTrace.cc.
References Histogram::clear(), initSummary(), s_store_count_ptr, s_store_first_to_last_ptr, s_store_first_to_stolen_ptr, s_store_last_to_stolen_ptr, and s_total_samples.
Referenced by getTotal().
downgrade()
void StoreTrace::downgrade (NodeID node)
Definition at line 128 of file StoreTrace.cc.
References Histogram::add(), curTick(), m_first_store, m_last_store, m_last_writer, m_store_count, m_store_first_to_last, m_store_first_to_stolen, m_store_last_to_stolen, m_stores_this_interval, m_total_samples, s_store_count_ptr, s_store_first_to_last_ptr, s_store_first_to_stolen_ptr, s_store_last_to_stolen_ptr, and s_total_samples.
Referenced by StoreTrace().
getTotal()
int StoreTrace::getTotal () const inline
Definition at line 47 of file StoreTrace.hh.
References clearSummary(), initSummary(), m_total_samples, print(), and printSummary().
Referenced by node_less_then_eq().
initSummary()
void StoreTrace::initSummary () static
Definition at line 73 of file StoreTrace.cc.
References s_init, s_store_count_ptr, s_store_first_to_last_ptr, s_store_first_to_stolen_ptr, s_store_last_to_stolen_ptr, and s_total_samples.
Referenced by clearSummary(), getTotal(), and StoreTrace().
print()
void StoreTrace::print (std::ostream & out) const
Definition at line 62 of file StoreTrace.cc.
References m_addr, m_store_count, m_store_first_to_last, m_store_first_to_stolen, m_store_last_to_stolen, and m_total_samples.
Referenced by getTotal(), and operator<<().
printSummary()
void StoreTrace::printSummary (std::ostream & out) static
Definition at line 86 of file StoreTrace.cc.
References s_total_samples.
Referenced by getTotal().
store()
void StoreTrace::store (NodeID node)
Definition at line 107 of file StoreTrace.cc.
References curTick(), m_first_store, m_last_store, m_last_writer, and m_stores_this_interval.
Referenced by StoreTrace().
Member Data Documentation
m_addr
Addr StoreTrace::m_addr private
Definition at line 63 of file StoreTrace.hh.
Referenced by print(), and StoreTrace().
m_first_store
Tick StoreTrace::m_first_store private
Definition at line 65 of file StoreTrace.hh.
Referenced by downgrade(), and store().
m_last_store
Tick StoreTrace::m_last_store private
Definition at line 66 of file StoreTrace.hh.
Referenced by downgrade(), and store().
m_last_writer
NodeID StoreTrace::m_last_writer private
Definition at line 64 of file StoreTrace.hh.
Referenced by downgrade(), store(), and StoreTrace().
m_store_count
Histogram StoreTrace::m_store_count private
Definition at line 70 of file StoreTrace.hh.
Referenced by downgrade(), and print().
m_store_first_to_last
Histogram StoreTrace::m_store_first_to_last private
Definition at line 73 of file StoreTrace.hh.
Referenced by downgrade(), and print().
m_store_first_to_stolen
Histogram StoreTrace::m_store_first_to_stolen private
Definition at line 71 of file StoreTrace.hh.
Referenced by downgrade(), and print().
m_store_last_to_stolen
Histogram StoreTrace::m_store_last_to_stolen private
Definition at line 72 of file StoreTrace.hh.
Referenced by downgrade(), and print().
m_stores_this_interval
int StoreTrace::m_stores_this_interval private
Definition at line 67 of file StoreTrace.hh.
Referenced by downgrade(), store(), and StoreTrace().
m_total_samples
int64_t StoreTrace::m_total_samples private
Definition at line 69 of file StoreTrace.hh.
Referenced by downgrade(), getTotal(), print(), and StoreTrace().
s_init
bool StoreTrace::s_init = false static private
Definition at line 55 of file StoreTrace.hh.
Referenced by initSummary().
s_store_count_ptr
Histogram * StoreTrace::s_store_count_ptr = NULL static private
Definition at line 58 of file StoreTrace.hh.
Referenced by clearSummary(), downgrade(), and initSummary().
s_store_first_to_last_ptr
Histogram * StoreTrace::s_store_first_to_last_ptr = NULL static private
Definition at line 61 of file StoreTrace.hh.
Referenced by clearSummary(), downgrade(), and initSummary().
s_store_first_to_stolen_ptr
Histogram * StoreTrace::s_store_first_to_stolen_ptr = NULL static private
Definition at line 59 of file StoreTrace.hh.
Referenced by clearSummary(), downgrade(), and initSummary().
s_store_last_to_stolen_ptr
Histogram * StoreTrace::s_store_last_to_stolen_ptr = NULL static private
Definition at line 60 of file StoreTrace.hh.
Referenced by clearSummary(), downgrade(), and initSummary().
s_total_samples
int64_t StoreTrace::s_total_samples = 0 static private
Definition at line 56 of file StoreTrace.hh.
Referenced by clearSummary(), downgrade(), initSummary(), and printSummary().
The documentation for this class was generated from the following files:
mem/ruby/profiler/StoreTrace.hh
mem/ruby/profiler/StoreTrace.cc