gem5: Stats::AvgSampleStor Class Reference
Stats::AvgSampleStor Class Reference
Templatized storage for distribution that calculates per tick mean and variance.
#include <statistics.hh>
Classes
struct Params
Public Member Functions
AvgSampleStor (Info *info)
Create and initialize this storage.
void sample (Counter val, int number)
Add a value to the distribution for the given number of times.
size_type size () const
Return the number of entries, in this case 1.
bool zero () const
Return true if no samples have been added.
void prepare (Info *info, DistData &data)
void reset (Info *info)
Reset stat value to default.
Private Attributes
Counter sum
Current total.
Counter squares
Current sum of squares.
Detailed Description
Templatized storage for distribution that calculates per tick mean and variance.
Definition at line 1773 of file statistics.hh.
Constructor & Destructor Documentation
AvgSampleStor()
Stats::AvgSampleStor::AvgSampleStor (Info * info) inline
Create and initialize this storage.
Definition at line 1791 of file statistics.hh.
Member Function Documentation
prepare()
void Stats::AvgSampleStor::prepare (Info * info, DistData & data) inline
Definition at line 1822 of file statistics.hh.
References curTick(), Stats::Deviation, safe_cast(), Stats::DistData::samples, Stats::DistData::squares, Stats::Info::storageParams, Stats::DistData::sum, Stats::sum(), Stats::DistData::type, and Stats::DistParams::type.
reset()
void Stats::AvgSampleStor::reset (Info * info) inline
Reset stat value to default.
Definition at line 1837 of file statistics.hh.
sample()
void Stats::AvgSampleStor::sample (Counter val, int number) inline
Add a value to the distribution for the given number of times.
Update the running sum and sum of squares.
Parameters
val The value to add.
number The number of times to add the value.
Definition at line 1802 of file statistics.hh.
size()
size_type Stats::AvgSampleStor::size () const inline
Return the number of entries, in this case 1.
Returns
1.
Definition at line 1813 of file statistics.hh.
zero()
bool Stats::AvgSampleStor::zero () const inline
Return true if no samples have been added.
Returns
True if the sum is zero.
Definition at line 1819 of file statistics.hh.
Member Data Documentation
squares
Counter Stats::AvgSampleStor::squares private
Current sum of squares.
Definition at line 1785 of file statistics.hh.
sum
Counter Stats::AvgSampleStor::sum private
Current total.
Definition at line 1783 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh