gem5: Label Class Reference
Label Class Reference
#include <hsail_code.hh>
Public Member Functions
Label ()
bool defined ()
void checkName (std::string &_name)
void define (std::string &_name, int _value)
int get ()
Public Attributes
std::string name
int value
Detailed Description
Definition at line 166 of file hsail_code.hh.
Constructor & Destructor Documentation
Label()
Label::Label () inline
Definition at line 172 of file hsail_code.hh.
Member Function Documentation
checkName()
void Label::checkName (std::string & _name) inline
Definition at line 179 of file hsail_code.hh.
Referenced by define(), and LabelMap::refLabel().
define()
void Label::define (std::string & _name, int _value) inline
Definition at line 189 of file hsail_code.hh.
References checkName(), and defined().
Referenced by LabelMap::addLabel().
defined()
bool Label::defined () inline
Definition at line 176 of file hsail_code.hh.
Referenced by LabelMap::addLabel(), define(), and get().
get()
int Label::get () inline
Definition at line 198 of file hsail_code.hh.
References defined(), and value.
Member Data Documentation
name
std::string Label::name
Definition at line 169 of file hsail_code.hh.
Referenced by StorageSpace::StorageSpace().
value
int Label::value
Definition at line 170 of file hsail_code.hh.
Referenced by get().
The documentation for this class was generated from the following file:
gpu-compute/hsail_code.hh