gem5: Trace::OstreamLogger Class Reference
Trace::OstreamLogger Class Reference
Logging wrapper for ostreams with the format: <when>: <name>: <message-body>
#include <trace.hh>
Public Member Functions
OstreamLogger (std::ostream &stream_)
void logMessage (Tick when, const std::string &name, const std::string &message) override
Log formatted message.
std::ostream & getOstream () override
Return an ostream that can be used to send messages to the 'same place' as formatted logMessage messages.
Public Member Functions inherited from Trace::Logger
template<typename ... Args>
void dprintf (Tick when, const std::string &name, const char *fmt, const Args &...args)
Log a single message.
virtual void dump (Tick when, const std::string &name, const void *d, int len)
Dump a block of data of length len.
void setIgnore (ObjectMatch &ignore_)
Set objects to ignore.
void addIgnore (const ObjectMatch &ignore_)
Add objects to ignore.
virtual ~Logger ()
Protected Attributes
std::ostream & stream
Protected Attributes inherited from Trace::Logger
ObjectMatch ignore
Name match for objects to ignore.
Detailed Description
Logging wrapper for ostreams with the format: <when>: <name>: <message-body>
Definition at line 97 of file trace.hh.
Constructor & Destructor Documentation
OstreamLogger()
Trace::OstreamLogger::OstreamLogger (std::ostream & stream_) inline
Definition at line 103 of file trace.hh.
References Trace::Logger::logMessage(), and name().
Member Function Documentation
getOstream()
std::ostream& Trace::OstreamLogger::getOstream () inline override virtual
Return an ostream that can be used to send messages to the 'same place' as formatted logMessage messages.
This can be implemented to use a logger's underlying ostream, to provide an ostream which formats the output in some way, or just set to one of std::cout, std::cerr
Implements Trace::Logger.
Definition at line 109 of file trace.hh.
References Trace::disable(), Trace::enable(), Trace::getDebugLogger(), Trace::output(), and Trace::setDebugLogger().
logMessage()
void Trace::OstreamLogger::logMessage (Tick when, const std::string & name, const std::string & message) override virtual
Log formatted message.
Implements Trace::Logger.
Definition at line 144 of file trace.cc.
References ccprintf(), ObjectMatch::match(), and MaxTick.
Member Data Documentation
stream
std::ostream& Trace::OstreamLogger::stream protected
Definition at line 100 of file trace.hh.
The documentation for this class was generated from the following files:
base/trace.hh
base/trace.cc