gem5: WireBuffer Class Reference
WireBuffer Class Reference
#include <WireBuffer.hh>
Public Types
typedef RubyWireBufferParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
WireBuffer (const Params *p)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
~WireBuffer ()
void wakeup ()
void setConsumer (Consumer *consumer_ptr)
Consumer * getConsumer ()
void setDescription (const std::string &name)
std::string getDescription ()
void enqueue (MsgPtr message, Tick current_time, Tick delta)
void dequeue (Tick current_time)
const Message * peek ()
void recycle (Tick current_time, Tick recycle_latency)
bool isReady (Tick current_time)
bool areNSlotsAvailable (int n, Tick current_time)
void print (std::ostream &out) const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
uint64_t m_msg_counter
Private Member Functions
WireBuffer (const WireBuffer &obj)
WireBuffer & operator= (const WireBuffer &obj)
Private Attributes
Consumer * m_consumer_ptr
std::string m_description
std::vector< MsgPtr > m_message_queue
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 56 of file WireBuffer.hh.
Member Typedef Documentation
Params
typedef RubyWireBufferParams WireBuffer::Params
Definition at line 59 of file WireBuffer.hh.
Constructor & Destructor Documentation
WireBuffer() [1/2]
WireBuffer::WireBuffer (const Params * p)
Definition at line 57 of file WireBuffer.cc.
References m_msg_counter.
Referenced by wakeup().
~WireBuffer()
WireBuffer::~WireBuffer ()
Definition at line 68 of file WireBuffer.cc.
WireBuffer() [2/2]
WireBuffer::WireBuffer (const WireBuffer & obj) private
Member Function Documentation
areNSlotsAvailable()
bool WireBuffer::areNSlotsAvailable (int n, Tick current_time) inline
Definition at line 81 of file WireBuffer.hh.
References print().
dequeue()
void WireBuffer::dequeue (Tick current_time)
Definition at line 91 of file WireBuffer.cc.
References isReady(), and m_message_queue.
Referenced by getDescription().
enqueue()
void WireBuffer::enqueue (MsgPtr message, Tick current_time, Tick delta)
Definition at line 73 of file WireBuffer.cc.
References m_consumer_ptr, m_message_queue, m_msg_counter, panic, and Message::setLastEnqueueTime().
Referenced by getDescription().
getConsumer()
Consumer* WireBuffer::getConsumer () inline
Definition at line 71 of file WireBuffer.hh.
References m_consumer_ptr.
getDescription()
std::string WireBuffer::getDescription () inline
Definition at line 73 of file WireBuffer.hh.
References dequeue(), enqueue(), isReady(), m_description, peek(), and recycle().
init()
void WireBuffer::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 64 of file WireBuffer.cc.
isReady()
bool WireBuffer::isReady (Tick current_time)
Definition at line 129 of file WireBuffer.cc.
References m_message_queue.
Referenced by dequeue(), getDescription(), and recycle().
operator=()
WireBuffer& WireBuffer::operator= (const WireBuffer & obj) private
peek()
const Message * WireBuffer::peek ()
Definition at line 100 of file WireBuffer.cc.
References m_message_queue.
Referenced by getDescription().
print()
void WireBuffer::print (std::ostream & out) const
Definition at line 136 of file WireBuffer.cc.
Referenced by areNSlotsAvailable(), and operator<<().
recycle()
void WireBuffer::recycle (Tick current_time, Tick recycle_latency)
Definition at line 108 of file WireBuffer.cc.
References isReady(), m_consumer_ptr, and m_message_queue.
Referenced by getDescription().
setConsumer()
void WireBuffer::setConsumer (Consumer * consumer_ptr) inline
Definition at line 67 of file WireBuffer.hh.
References m_consumer_ptr.
setDescription()
void WireBuffer::setDescription (const std::string & name) inline
Definition at line 72 of file WireBuffer.hh.
References m_description, and SimObject::name().
wakeup()
void WireBuffer::wakeup ()
Definition at line 141 of file WireBuffer.cc.
References WireBuffer().
Member Data Documentation
m_consumer_ptr
Consumer* WireBuffer::m_consumer_ptr private
Definition at line 92 of file WireBuffer.hh.
Referenced by enqueue(), getConsumer(), recycle(), and setConsumer().
m_description
std::string WireBuffer::m_description private
Definition at line 93 of file WireBuffer.hh.
Referenced by getDescription(), and setDescription().
m_message_queue
std::vector<MsgPtr> WireBuffer::m_message_queue private
Definition at line 96 of file WireBuffer.hh.
Referenced by dequeue(), enqueue(), isReady(), peek(), and recycle().
m_msg_counter
uint64_t WireBuffer::m_msg_counter
Definition at line 84 of file WireBuffer.hh.
Referenced by enqueue(), and WireBuffer().
The documentation for this class was generated from the following files:
mem/ruby/structures/WireBuffer.hh
mem/ruby/structures/WireBuffer.cc