gem5: BasePrefetcher::PrefetchListener Class Reference
BasePrefetcher::PrefetchListener Class Reference
Public Member Functions
PrefetchListener (BasePrefetcher &_parent, ProbeManager *pm, const std::string &name, bool _isFill=false, bool _miss=false)
void notify (const PacketPtr &pkt) override
Public Member Functions inherited from ProbeListenerArgBase< PacketPtr >
ProbeListenerArgBase (ProbeManager *pm, const std::string &name)
Public Member Functions inherited from ProbeListener
ProbeListener (ProbeManager *manager, const std::string &name)
virtual ~ProbeListener ()
Protected Attributes
BasePrefetcher & parent
const bool isFill
const bool miss
Protected Attributes inherited from ProbeListener
ProbeManager *const manager
const std::string name
Detailed Description
Definition at line 69 of file base.hh.
Constructor & Destructor Documentation
PrefetchListener()
BasePrefetcher::PrefetchListener::PrefetchListener (BasePrefetcher & _parent, ProbeManager * pm, const std::string & name, bool _isFill = false, bool _miss = false) inline
Definition at line 72 of file base.hh.
References notify().
Member Function Documentation
notify()
void BasePrefetcher::PrefetchListener::notify (const PacketPtr & pkt) override virtual
Implements ProbeListenerArgBase< PacketPtr >.
Definition at line 83 of file base.cc.
Referenced by PrefetchListener(), and BasePrefetcher::~BasePrefetcher().
Member Data Documentation
isFill
const bool BasePrefetcher::PrefetchListener::isFill protected
Definition at line 80 of file base.hh.
miss
const bool BasePrefetcher::PrefetchListener::miss protected
Definition at line 81 of file base.hh.
Referenced by BasePrefetcher::notifyFill(), and BasePrefetcher::PrefetchInfo::sameAddr().
parent
BasePrefetcher& BasePrefetcher::PrefetchListener::parent protected
Definition at line 79 of file base.hh.
The documentation for this class was generated from the following files:
mem/cache/prefetch/base.hh
mem/cache/prefetch/base.cc