gem5: Port Class Reference
Port Class Reference
Ports are used to interface objects to each other.
#include <port.hh>
Public Member Functions
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
virtual void bind (Port &peer)
Attach to a peer port.
virtual void unbind ()
Dettach from a peer port.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Private Attributes
const std::string portName
Descriptive name (for DPRINTF output)
Detailed Description
Ports are used to interface objects to each other.
Definition at line 60 of file port.hh.
Constructor & Destructor Documentation
Port()
Port::Port (const std::string & _name, PortID _id) protected
Abstract base class for ports.
Parameters
_name Port name including the owners name
_id A port identifier for vector ports
Definition at line 52 of file port.cc.
~Port()
Port::~Port () protected virtual
Virtual destructor due to inheritance.
Definition at line 55 of file port.cc.
Member Function Documentation
bind()
virtual void Port::bind (Port & peer) inline virtual
Attach to a peer port.
Reimplemented in SlavePort, IntSourcePinBase, MasterPort, IntSinkPinBase, EtherInt, and RubyDummyPort.
Definition at line 113 of file port.hh.
Referenced by IntSinkPinBase::bind(), MasterPort::bind(), IntSourcePinBase::bind(), CxxConfigManager::bindPort(), SlavePort::slaveBind(), and takeOverFrom().
getId()
PortID Port::getId () const inline
Get the port id.
Definition at line 109 of file port.hh.
References id.
Referenced by SnoopFilter::portToMask().
getPeer()
Port& Port::getPeer () inline
Return a reference to this port's peer.
Definition at line 103 of file port.hh.
References _peer.
Referenced by X86ISA::IntSlavePort< X86ISA::Interrupts >::recvAtomic(), SMMUv3SlaveInterface::recvAtomic(), SMMUv3SlaveInterface::recvTimingReq(), SMMUv3SlaveInterface::sendRange(), and takeOverFrom().
isConnected()
bool Port::isConnected () const inline
Is this port currently connected to a peer?
Definition at line 128 of file port.hh.
References _connected.
Referenced by CxxConfigManager::bindPort(), AddrMapper::init(), MemDelay::init(), MemCheckerMonitor::init(), CommMonitor::init(), System::init(), ExternalMaster::init(), ExternalSlave::init(), PioDevice::init(), QoS::MemSinkCtrl::init(), SMMUv3::init(), SimpleMemory::init(), DRAMSim2::init(), DmaDevice::init(), BaseTrafficGen::init(), SerialLink::init(), Bridge::init(), BaseCache::init(), DRAMCtrl::init(), RubyPort::MemSlavePort::recvAtomic(), SMMUv3SlaveInterface::sendRange(), and takeOverFrom().
name()
const std::string Port::name () const inline
Return port name (for DPRINTF).
Definition at line 106 of file port.hh.
References portName.
Referenced by EtherInt::bind(), sc_gem5::TlmInitiatorBaseWrapper< BITWIDTH >::bind(), IntSinkPinBase::bind(), sc_gem5::ScPortWrapper< IF >::bind(), MasterPort::bind(), IntSourcePinBase::bind(), sc_gem5::ScInterfaceWrapper< IF >::bind(), sc_gem5::ScExportWrapper< IF >::bind(), DmaCallback::getChunkEvent(), StubSlavePortHandler::getExternalPort(), SnoopFilter::lookupRequest(), ReqPacketQueue::name(), SnoopRespPacketQueue::name(), RespPacketQueue::name(), operator<<(), X86ISA::IntSlavePort< X86ISA::Interrupts >::recvAtomic(), SlavePort::recvAtomicBackdoor(), MasterPort::recvAtomicSnoop(), MasterPort::recvFunctionalSnoop(), RubyDirectedTester::CpuPort::recvReqRetry(), RubyTester::CpuPort::recvReqRetry(), MasterPort::recvRetrySnoopResp(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), MasterPort::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), SlavePort::recvTimingSnoopResp(), SlavePort::sendRangeChange(), StubSlavePort::StubSlavePort(), SlavePort::tryTiming(), MasterPort::unbind(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), SnoopFilter::updateSnoopResponse(), and X86ISA::Walker::Walker().
takeOverFrom()
void Port::takeOverFrom (Port * old) inline
A utility function to make it easier to swap out ports.
Definition at line 132 of file port.hh.
References bind(), getPeer(), isConnected(), and unbind().
Referenced by AtomicSimpleCPU::getInstPort(), TraceCPU::takeOverFrom(), and BaseCPU::takeOverFrom().
unbind()
virtual void Port::unbind () inline virtual
Dettach from a peer port.
Reimplemented in SlavePort, sc_gem5::ScExportWrapper< IF >, sc_gem5::ScInterfaceWrapper< IF >, sc_gem5::TlmTargetBaseWrapper< BUSWIDTH, FW_IF, BW_IF, N, POL >, sc_gem5::TlmTargetBaseWrapper< 64 >, sc_gem5::TlmTargetBaseWrapper< 64, amba_pv::amba_pv_protocol_types >, sc_gem5::TlmTargetBaseWrapper< BITWIDTH >, IntSourcePinBase, MasterPort, sc_gem5::TlmInitiatorBaseWrapper< BUSWIDTH, FW_IF, BW_IF, N, POL >, sc_gem5::TlmInitiatorBaseWrapper< 64 >, sc_gem5::TlmInitiatorBaseWrapper< 64, amba_pv::amba_pv_protocol_types >, sc_gem5::TlmInitiatorBaseWrapper< BITWIDTH >, IntSinkPinBase, sc_gem5::ScPortWrapper< IF >, EtherInt, and RubyDummyPort.
Definition at line 121 of file port.hh.
Referenced by SlavePort::slaveUnbind(), takeOverFrom(), IntSinkPinBase::unbind(), MasterPort::unbind(), and IntSourcePinBase::unbind().
Member Data Documentation
_connected
bool Port::_connected protected
Whether this port is currently connected to a peer port.
Definition at line 85 of file port.hh.
Referenced by EtherInt::bind(), isConnected(), and EtherInt::unbind().
_peer
Port* Port::_peer protected
A pointer to this port's peer.
Definition at line 79 of file port.hh.
Referenced by getPeer().
id
const PortID Port::id protected
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Definition at line 74 of file port.hh.
Referenced by getId(), and RubyPort::MemSlavePort::recvTimingReq().
portName
const std::string Port::portName private
Descriptive name (for DPRINTF output)
Definition at line 66 of file port.hh.
Referenced by name().
The documentation for this class was generated from the following files:
sim/port.hh
sim/port.cc