gem5: EtherSwitch::Interface::PortFifo Class Reference
EtherSwitch::Interface::PortFifo Class Reference
#include <etherswitch.hh>
Classes
struct EntryOrder
Public Member Functions
PortFifo (const std::string &name, int max)
~PortFifo ()
const std::string name ()
int avail () const
EthPacketPtr front ()
bool empty () const
unsigned size () const
bool push (EthPacketPtr ptr, unsigned senderId)
Push a packet into the fifo and sort the packets with same recv tick by port id.
void pop ()
void clear ()
void serialize (CheckpointOut &cp) const
Serialization stuff.
void unserialize (CheckpointIn &cp)
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
std::set< PortFifoEntry, EntryOrder > fifo
const std::string objName
const unsigned _maxsize
unsigned _size
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 122 of file etherswitch.hh.
Constructor & Destructor Documentation
PortFifo()
EtherSwitch::Interface::PortFifo::PortFifo (const std::string & name, int max) inline
Definition at line 142 of file etherswitch.hh.
~PortFifo()
EtherSwitch::Interface::PortFifo::~PortFifo () inline
Definition at line 144 of file etherswitch.hh.
Member Function Documentation
avail()
int EtherSwitch::Interface::PortFifo::avail () const inline
Definition at line 152 of file etherswitch.hh.
clear()
void EtherSwitch::Interface::PortFifo::clear ()
Definition at line 121 of file etherswitch.cc.
empty()
bool EtherSwitch::Interface::PortFifo::empty () const inline
Definition at line 155 of file etherswitch.hh.
Referenced by EtherSwitch::Interface::transmit().
front()
EthPacketPtr EtherSwitch::Interface::PortFifo::front () inline
Definition at line 154 of file etherswitch.hh.
Referenced by EtherSwitch::Interface::switchingDelay(), and EtherSwitch::Interface::transmit().
name()
const std::string EtherSwitch::Interface::PortFifo::name () inline
Definition at line 146 of file etherswitch.hh.
pop()
void EtherSwitch::Interface::PortFifo::pop ()
Definition at line 109 of file etherswitch.cc.
Referenced by EtherSwitch::Interface::transmit().
push()
bool EtherSwitch::Interface::PortFifo::push (EthPacketPtr ptr, unsigned senderId)
Push a packet into the fifo and sort the packets with same recv tick by port id.
Definition at line 77 of file etherswitch.cc.
References curTick(), DPRINTF, and warn.
Referenced by EtherSwitch::Interface::enqueue().
serialize()
void EtherSwitch::Interface::PortFifo::serialize (CheckpointOut & cp) const virtual
Serialization stuff.
Implements Serializable.
Definition at line 321 of file etherswitch.cc.
References csprintf(), ArmISA::i, and SERIALIZE_SCALAR.
size()
unsigned EtherSwitch::Interface::PortFifo::size () const inline
Definition at line 156 of file etherswitch.hh.
References EtherSwitch::Interface::PortFifoEntry::serialize(), and EtherSwitch::Interface::PortFifoEntry::unserialize().
unserialize()
void EtherSwitch::Interface::PortFifo::unserialize (CheckpointIn & cp) virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 334 of file etherswitch.cc.
References csprintf(), EtherSwitch::EtherSwitch(), ArmISA::i, UNSERIALIZE_SCALAR, and Serializable::unserializeSection().
Member Data Documentation
_maxsize
const unsigned EtherSwitch::Interface::PortFifo::_maxsize protected
Definition at line 138 of file etherswitch.hh.
_size
unsigned EtherSwitch::Interface::PortFifo::_size protected
Definition at line 139 of file etherswitch.hh.
fifo
std::set<PortFifoEntry, EntryOrder> EtherSwitch::Interface::PortFifo::fifo protected
Definition at line 135 of file etherswitch.hh.
objName
const std::string EtherSwitch::Interface::PortFifo::objName protected
Definition at line 137 of file etherswitch.hh.
The documentation for this class was generated from the following files:
dev/net/etherswitch.hh
dev/net/etherswitch.cc