gem5: sc_core::sc_spawn_options Class Reference
sc_core::sc_spawn_options Class Reference
#include <sc_spawn.hh>
Classes
struct Reset
Public Member Functions
sc_spawn_options ()
void spawn_method ()
void dont_initialize ()
void set_stack_size (int)
void set_sensitivity (const sc_event *)
void set_sensitivity (sc_port_base *)
void set_sensitivity (sc_export_base *)
void set_sensitivity (sc_interface *)
void set_sensitivity (sc_event_finder *)
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
Private Member Functions
sc_spawn_options (const sc_spawn_options &)
sc_spawn_options & operator= (const sc_spawn_options &)
Private Attributes
bool _spawnMethod
bool _dontInitialize
int _stackSize
std::vector< const sc_event * > _events
std::vector< sc_port_base * > _ports
std::vector< sc_export_base * > _exports
std::vector< sc_interface * > _interfaces
std::vector< sc_event_finder * > _finders
std::vector< Reset< const sc_in< bool > > > _in_resets
std::vector< Reset< const sc_inout< bool > > > _inout_resets
std::vector< Reset< const sc_out< bool > > > _out_resets
std::vector< Reset< const sc_signal_in_if< bool > > > _if_resets
Friends
::sc_gem5::Process * sc_gem5::spawnWork (::sc_gem5::ProcessFuncWrapper *, const char *, const sc_spawn_options *)
Detailed Description
Definition at line 95 of file sc_spawn.hh.
Constructor & Destructor Documentation
sc_spawn_options() [1/2]
sc_core::sc_spawn_options::sc_spawn_options ()
Definition at line 123 of file sc_spawn.cc.
sc_spawn_options() [2/2]
sc_core::sc_spawn_options::sc_spawn_options (const sc_spawn_options &) inline private
Definition at line 150 of file sc_spawn.hh.
Member Function Documentation
async_reset_signal_is() [1/4]
void sc_core::sc_spawn_options::async_reset_signal_is (const sc_in< bool > & port, bool value)
Definition at line 205 of file sc_spawn.cc.
References _in_resets.
async_reset_signal_is() [2/4]
void sc_core::sc_spawn_options::async_reset_signal_is (const sc_inout< bool > & port, bool value)
Definition at line 211 of file sc_spawn.cc.
References _inout_resets.
async_reset_signal_is() [3/4]
void sc_core::sc_spawn_options::async_reset_signal_is (const sc_out< bool > & port, bool value)
Definition at line 217 of file sc_spawn.cc.
References _out_resets.
async_reset_signal_is() [4/4]
void sc_core::sc_spawn_options::async_reset_signal_is (const sc_signal_in_if< bool > & iface, bool value)
Definition at line 223 of file sc_spawn.cc.
References _if_resets.
dont_initialize()
void sc_core::sc_spawn_options::dont_initialize ()
Definition at line 135 of file sc_spawn.cc.
References _dontInitialize.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
operator=()
sc_spawn_options& sc_core::sc_spawn_options::operator= (const sc_spawn_options &) inline private
Definition at line 151 of file sc_spawn.hh.
reset_signal_is() [1/4]
void sc_core::sc_spawn_options::reset_signal_is (const sc_in< bool > & port, bool value)
Definition at line 179 of file sc_spawn.cc.
References _in_resets.
reset_signal_is() [2/4]
void sc_core::sc_spawn_options::reset_signal_is (const sc_inout< bool > & port, bool value)
Definition at line 185 of file sc_spawn.cc.
References _inout_resets.
reset_signal_is() [3/4]
void sc_core::sc_spawn_options::reset_signal_is (const sc_out< bool > & port, bool value)
Definition at line 191 of file sc_spawn.cc.
References _out_resets.
reset_signal_is() [4/4]
void sc_core::sc_spawn_options::reset_signal_is (const sc_signal_in_if< bool > & iface, bool value)
Definition at line 197 of file sc_spawn.cc.
References _if_resets.
set_sensitivity() [1/5]
void sc_core::sc_spawn_options::set_sensitivity (const sc_event * e)
Definition at line 148 of file sc_spawn.cc.
References _events.
Referenced by tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::nb_transport_fw(), tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation(), and tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::start_of_simulation().
set_sensitivity() [2/5]
void sc_core::sc_spawn_options::set_sensitivity (sc_port_base * p)
Definition at line 154 of file sc_spawn.cc.
References _ports.
set_sensitivity() [3/5]
void sc_core::sc_spawn_options::set_sensitivity (sc_export_base * e)
Definition at line 160 of file sc_spawn.cc.
References _exports.
set_sensitivity() [4/5]
void sc_core::sc_spawn_options::set_sensitivity (sc_interface * i)
Definition at line 166 of file sc_spawn.cc.
References _interfaces.
set_sensitivity() [5/5]
void sc_core::sc_spawn_options::set_sensitivity (sc_event_finder * f)
Definition at line 172 of file sc_spawn.cc.
References _finders.
set_stack_size()
void sc_core::sc_spawn_options::set_stack_size (int ss)
Definition at line 141 of file sc_spawn.cc.
References _stackSize, and ArmISA::ss.
spawn_method()
void sc_core::sc_spawn_options::spawn_method ()
Definition at line 129 of file sc_spawn.cc.
References _spawnMethod.
Referenced by tlm_utils::peq_with_cb_and_phase< MultiSocketSimpleSwitchAT >::peq_with_cb_and_phase().
Friends And Related Function Documentation
sc_gem5::spawnWork
::sc_gem5::Process* sc_gem5::spawnWork (::sc_gem5::ProcessFuncWrapper * , const char * , const sc_spawn_options *) friend
Member Data Documentation
_dontInitialize
bool sc_core::sc_spawn_options::_dontInitialize private
Definition at line 126 of file sc_spawn.hh.
Referenced by dont_initialize().
_events
std::vector<const sc_event *> sc_core::sc_spawn_options::_events private
Definition at line 128 of file sc_spawn.hh.
Referenced by set_sensitivity().
_exports
std::vector<sc_export_base *> sc_core::sc_spawn_options::_exports private
Definition at line 130 of file sc_spawn.hh.
Referenced by set_sensitivity().
_finders
std::vector<sc_event_finder *> sc_core::sc_spawn_options::_finders private
Definition at line 132 of file sc_spawn.hh.
Referenced by set_sensitivity().
_if_resets
std::vector<Reset<const sc_signal_in_if<bool> > > sc_core::sc_spawn_options::_if_resets private
Definition at line 147 of file sc_spawn.hh.
Referenced by async_reset_signal_is(), and reset_signal_is().
_in_resets
std::vector<Reset<const sc_in<bool> > > sc_core::sc_spawn_options::_in_resets private
Definition at line 144 of file sc_spawn.hh.
Referenced by async_reset_signal_is(), and reset_signal_is().
_inout_resets
std::vector<Reset<const sc_inout<bool> > > sc_core::sc_spawn_options::_inout_resets private
Definition at line 145 of file sc_spawn.hh.
Referenced by async_reset_signal_is(), and reset_signal_is().
_interfaces
std::vector<sc_interface *> sc_core::sc_spawn_options::_interfaces private
Definition at line 131 of file sc_spawn.hh.
Referenced by set_sensitivity().
_out_resets
std::vector<Reset<const sc_out<bool> > > sc_core::sc_spawn_options::_out_resets private
Definition at line 146 of file sc_spawn.hh.
Referenced by async_reset_signal_is(), and reset_signal_is().
_ports
std::vector<sc_port_base *> sc_core::sc_spawn_options::_ports private
Definition at line 129 of file sc_spawn.hh.
Referenced by set_sensitivity().
_spawnMethod
bool sc_core::sc_spawn_options::_spawnMethod private
Definition at line 125 of file sc_spawn.hh.
Referenced by spawn_method().
_stackSize
int sc_core::sc_spawn_options::_stackSize private
Definition at line 127 of file sc_spawn.hh.
Referenced by set_stack_size().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_spawn.hh
systemc/core/sc_spawn.cc