gem5: CircularQueue< T > Class Template Reference
CircularQueue< T > Class Template Reference
Circular queue.
#include <circular_queue.hh>
Classes
struct iterator
Iterator to the circular queue.
Public Member Functions
CircularQueue (uint32_t size=0)
void flush ()
Remove all the elements in the queue.
bool isValidIdx (size_t idx) const
Test if the index is in the range of valid elements.
bool isValidIdx (size_t idx, uint32_t round) const
Test if the index is in the range of valid elements.
reference front ()
reference back ()
uint32_t head () const
uint32_t tail () const
size_t capacity () const
uint32_t size () const
uint32_t moduloAdd (uint32_t s1, uint32_t s2) const
uint32_t moduloSub (uint32_t s1, uint32_t s2) const
void pop_front (size_t num_elem=1)
Circularly increase the head pointer.
void pop_back ()
Circularly decrease the tail pointer.
void push_back (typename Base::value_type val)
Pushes an element at the end of the queue.
void advance_tail ()
Increases the tail by one.
void advance_tail (uint32_t len)
Increases the tail by a specified number of steps.
bool empty () const
Is the queue empty?
bool full () const
Is the queue full? A queue is full if the head is the 0^{th} element and the tail is the (size-1)^{th} element, or if the head is the n^{th} element and the tail the (n-1)^{th} element.
iterator begin ()
Iterators.
iterator begin () const
iterator end ()
iterator end () const
iterator getIterator (size_t idx)
Return an iterator to an index in the vector.
Protected Types
using Base = std::vector< T >
Protected Member Functions
void increase (uint32_t &v, size_t delta=1)
void decrease (uint32_t &v)
Static Protected Member Functions
static uint32_t moduloAdd (uint32_t op1, uint32_t op2, uint32_t size)
General modular addition.
static uint32_t moduloSub (uint32_t op1, uint32_t op2, uint32_t size)
General modular subtraction.
static int32_t sub (uint32_t op1, uint32_t op2, uint32_t size)
Protected Attributes
const uint32_t _capacity
uint32_t _head
uint32_t _tail
uint32_t _empty
uint32_t _round
Counter for how many times the tail wraps around.
Additional Inherited Members
Private Attributes inherited from std::vector< T >
T item
Dummy Item.
Detailed Description
template<typename T>
class CircularQueue< T >
Circular queue.
Circular queue implemented on top of a standard vector. Instead of using a sentinel entry, we use a boolean to distinguish the case in which the queue is full or empty. Thus, a circular queue is represented by the 5-tuple (Capacity, IsEmpty?, Head, Tail, Round) Where:
Capacity is the size of the underlying vector.
IsEmpty? can be T or F.
Head is the index in the vector of the first element of the queue.
Tail is the index in the vector of the last element of the queue.
Round is the counter of how many times the Tail has wrapped around. A queue is empty when Head == (Tail + 1 mod Capacity) && IsEmpty?. Conversely, a queue if full when Head == (Tail + 1 mod Capacity) && !IsEmpty?. Comments may show depictions of the underlying vector in the following format: '|' delimit the 'cells' of the underlying vector. '-' represents an element of the vector that is out-of-bounds of the circular queue, while 'o' represents and element that is inside the bounds. The characters '[' and ']' are added to mark the entries that hold the head and tail of the circular queue respectively. E.g.:
Empty queues of capacity 4: (4,T,1,0,_): |-]|[-|-|-| (4,T,3,2): |-|-|-]|[-|
Full queues of capacity 4: (4,F,1,0,_): |o]|[o|o|o| (4,F,3,2): |o|o|o]|[o|
Queues of capacity 4 with 2 elements: (4,F,0,1,_): |[o|o]|-|-| (4,F,3,0): |o]|-|-|[o|
The Round number is only relevant for checking validity of indices, therefore it will be omitted or shown as '_'
Definition at line 84 of file circular_queue.hh.
Member Typedef Documentation
Base
template<typename T> using CircularQueue< T >::Base = std::vector<T> protected
Definition at line 87 of file circular_queue.hh.
Constructor & Destructor Documentation
CircularQueue()
template<typename T> CircularQueue< T >::CircularQueue (uint32_t size = 0) inline explicit
Definition at line 413 of file circular_queue.hh.
Member Function Documentation
advance_tail() [1/2]
template<typename T> void CircularQueue< T >::advance_tail () inline
Increases the tail by one.
Check for wrap-arounds to update the round counter.
Definition at line 555 of file circular_queue.hh.
Referenced by CircularQueue< char >::advance_tail(), LSQUnit< Impl >::insertLoad(), CircularQueue< char >::push_back(), and CircleBuf< char >::write().
advance_tail() [2/2]
template<typename T> void CircularQueue< T >::advance_tail (uint32_t len) inline
Increases the tail by a specified number of steps.
Parameters
len Number of steps
Definition at line 571 of file circular_queue.hh.
back()
template<typename T> reference CircularQueue< T >::back () inline
Definition at line 492 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::squash(), and TEST().
begin() [1/2]
template<typename T> iterator CircularQueue< T >::begin () inline
Iterators.
Definition at line 592 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), CircleBuf< char >::peek(), CircularQueue< char >::pop_front(), and TEST().
begin() [2/2]
template<typename T> iterator CircularQueue< T >::begin () const inline
Definition at line 603 of file circular_queue.hh.
capacity()
template<typename T> size_t CircularQueue< T >::capacity () const inline
Definition at line 495 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::drainSanityCheck(), LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::numFreeLoadEntries(), CircularQueue< T >::iterator::operator+=(), CircularQueue< T >::iterator::operator-(), CircularQueue< T >::iterator::operator-=(), TEST(), CircleBuf< char >::write(), and Fifo< uint8_t >::write().
decrease()
template<typename T> void CircularQueue< T >::decrease (uint32_t & v) inline protected
Definition at line 132 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::operator--(), and CircularQueue< char >::pop_back().
empty()
template<typename T> bool CircularQueue< T >::empty () const inline
Is the queue empty?
Definition at line 578 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), Terminal::console_in(), Terminal::dataAvailable(), CircularQueue< T >::iterator::decrementable(), Terminal::readData(), and TEST().
end() [1/2]
template<typename T> iterator CircularQueue< T >::end () inline
Definition at line 615 of file circular_queue.hh.
Referenced by CircularQueue< char >::begin(), LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::checkViolations(), CircularQueue< char >::getIterator(), LSQUnit< Impl >::insertStore(), CircularQueue< char >::pop_front(), TEST(), and CircleBuf< char >::write().
end() [2/2]
template<typename T> iterator CircularQueue< T >::end () const inline
Definition at line 624 of file circular_queue.hh.
flush()
template<typename T> void CircularQueue< T >::flush () inline
Remove all the elements in the queue.
Note: This does not actually remove elements from the backing store.
Definition at line 425 of file circular_queue.hh.
Referenced by arrayParamIn().
front()
template<typename T> reference CircularQueue< T >::front () inline
Definition at line 491 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::commitLoad(), LSQUnit< Impl >::commitLoads(), LSQUnit< Impl >::getLoadHeadSeqNum(), LSQUnit< Impl >::getStoreHeadSeqNum(), and TEST().
full()
template<typename T> bool CircularQueue< T >::full () const inline
Is the queue full? A queue is full if the head is the 0^{th} element and the tail is the (size-1)^{th} element, or if the head is the n^{th} element and the tail the (n-1)^{th} element.
Definition at line 585 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::lqFull(), and TEST().
getIterator()
template<typename T> iterator CircularQueue< T >::getIterator (size_t idx) inline
Return an iterator to an index in the vector.
This poses the problem of round determination. By convention, the round is picked so that isValidIndex(idx, round) is true. If that is not possible, then the round value is _round, unless _tail is at the end of the storage, in which case the PTE wraps up and becomes _round + 1
Definition at line 639 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::insertLoad(), and LSQUnit< Impl >::read().
head()
template<typename T> uint32_t CircularQueue< T >::head () const inline
Definition at line 493 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::decrementable(), LSQUnit< Impl >::getLoadHead(), LSQUnit< Impl >::getStoreHead(), LSQUnit< Impl >::read(), and TEST().
increase()
template<typename T> void CircularQueue< T >::increase (uint32_t & v, size_t delta = 1) inline protected
Definition at line 127 of file circular_queue.hh.
Referenced by CircularQueue< char >::advance_tail(), and CircularQueue< T >::iterator::operator++().
isValidIdx() [1/2]
template<typename T> bool CircularQueue< T >::isValidIdx (size_t idx) const inline
Test if the index is in the range of valid elements.
Definition at line 434 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::dereferenceable(), and CircularQueue< char >::getIterator().
isValidIdx() [2/2]
template<typename T> bool CircularQueue< T >::isValidIdx (size_t idx, uint32_t round) const inline
Test if the index is in the range of valid elements.
The round counter is used to disambiguate aliasing.
Definition at line 457 of file circular_queue.hh.
moduloAdd() [1/2]
template<typename T> static uint32_t CircularQueue< T >::moduloAdd (uint32_t op1, uint32_t op2, uint32_t size) inline static protected
General modular addition.
Definition at line 105 of file circular_queue.hh.
Referenced by CircularQueue< char >::end(), CircularQueue< char >::getIterator(), CircularQueue< char >::increase(), LSQUnit< Impl >::insertStore(), CircularQueue< char >::moduloAdd(), and CircularQueue< T >::iterator::operator+=().
moduloAdd() [2/2]
template<typename T> uint32_t CircularQueue< T >::moduloAdd (uint32_t s1, uint32_t s2) const inline
Definition at line 507 of file circular_queue.hh.
moduloSub() [1/2]
template<typename T> static uint32_t CircularQueue< T >::moduloSub (uint32_t op1, uint32_t op2, uint32_t size) inline static protected
General modular subtraction.
Definition at line 112 of file circular_queue.hh.
Referenced by CircularQueue< char >::moduloSub(), and CircularQueue< T >::iterator::operator-=().
moduloSub() [2/2]
template<typename T> uint32_t CircularQueue< T >::moduloSub (uint32_t s1, uint32_t s2) const inline
Definition at line 512 of file circular_queue.hh.
pop_back()
template<typename T> void CircularQueue< T >::pop_back () inline
Circularly decrease the tail pointer.
Definition at line 536 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::squash().
pop_front()
template<typename T> void CircularQueue< T >::pop_front (size_t num_elem = 1) inline
Circularly increase the head pointer.
By increasing the head pointer we are removing elements from the begin of the circular queue. Check that the queue is not empty. And set it to empty if it had only one value prior to insertion.
num_elem number of elements to remove
Definition at line 525 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::commitLoad(), CircleBuf< char >::read(), and TEST().
push_back()
template<typename T> void CircularQueue< T >::push_back (typename Base::value_type val) inline
Pushes an element at the end of the queue.
Definition at line 546 of file circular_queue.hh.
Referenced by TEST().
size()
template<typename T> uint32_t CircularQueue< T >::size () const inline
Definition at line 497 of file circular_queue.hh.
Referenced by Terminal::accept(), arrayParamOut(), CircularQueue< char >::CircularQueue(), CircularQueue< char >::moduloAdd(), CircularQueue< char >::moduloSub(), CircleBuf< char >::peek(), CircularQueue< char >::sub(), TEST(), and Fifo< uint8_t >::write().
sub()
template<typename T> static int32_t CircularQueue< T >::sub (uint32_t op1, uint32_t op2, uint32_t size) inline static protected
Definition at line 119 of file circular_queue.hh.
Referenced by CircularQueue< char >::moduloSub(), and CircularQueue< T >::iterator::operator-().
tail()
template<typename T> uint32_t CircularQueue< T >::tail () const inline
Definition at line 494 of file circular_queue.hh.
Referenced by LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::insertStore(), LSQUnit< Impl >::squash(), and TEST().
Member Data Documentation
_capacity
template<typename T> const uint32_t CircularQueue< T >::_capacity protected
Definition at line 90 of file circular_queue.hh.
Referenced by CircularQueue< char >::capacity(), and CircularQueue< char >::decrease().
_empty
template<typename T> uint32_t CircularQueue< T >::_empty protected
Definition at line 93 of file circular_queue.hh.
Referenced by CircularQueue< char >::empty().
_head
template<typename T> uint32_t CircularQueue< T >::_head protected
Definition at line 91 of file circular_queue.hh.
Referenced by CircularQueue< char >::front(), and CircularQueue< char >::head().
_round
template<typename T> uint32_t CircularQueue< T >::_round protected
Counter for how many times the tail wraps around.
Some parts of the code rely on getting the past the end iterator, and expect to use it after inserting on the tail. To support this without ambiguity, we need the round number to guarantee that it did not become a before-the-beginning iterator.
Definition at line 101 of file circular_queue.hh.
Referenced by CircularQueue< T >::iterator::decrementable().
_tail
template<typename T> uint32_t CircularQueue< T >::_tail protected
Definition at line 92 of file circular_queue.hh.
Referenced by CircularQueue< char >::back(), CircularQueue< char >::isValidIdx(), CircularQueue< char >::pop_back(), CircularQueue< char >::push_back(), and CircularQueue< char >::tail().
The documentation for this class was generated from the following file:
base/circular_queue.hh