gem5: SectorSubBlk Class Reference
SectorSubBlk Class Reference
A sector is composed of sub-blocks, and each sub-block has information regarding its sector and a pointer to its sector tag.
#include <sector_blk.hh>
Public Member Functions
SectorSubBlk ()
SectorSubBlk (const SectorSubBlk &)=delete
SectorSubBlk & operator= (const SectorSubBlk &)=delete
~SectorSubBlk ()
void setSectorBlock (SectorBlk *sector_blk)
Set sector block associated to this block.
const SectorBlk * getSectorBlock () const
Get sector block associated to this block.
void setSectorOffset (const int sector_offset)
Set offset of this sub-block within the sector.
int getSectorOffset () const
Get offset of this sub-block within the sector.
Addr getTag () const
Get tag associated to this block.
void setValid () override
Set valid bit and inform sector block.
void setSecure () override
Set secure bit and inform sector block.
void invalidate () override
Invalidate the block and inform sector block.
void insert (const Addr tag, const bool is_secure, const int src_master_ID, const uint32_t task_ID) override
Set member variables when a block insertion occurs.
std::string print () const override
Pretty-print sector offset and other CacheBlk information.
Public Member Functions inherited from CacheBlk
CacheBlk ()
CacheBlk (const CacheBlk &)=delete
CacheBlk & operator= (const CacheBlk &)=delete
virtual ~CacheBlk ()
bool isWritable () const
Checks the write permissions of this block.
bool isReadable () const
Checks the read permissions of this block.
bool isValid () const
Checks that a block is valid.
bool isDirty () const
Check to see if a block has been written.
bool wasPrefetched () const
Check if this block was the result of a hardware prefetch, yet to be touched.
bool isSecure () const
Check if this block holds data from the secure memory space.
Tick getWhenReady () const
Get tick at which block's data will be available for access.
void setWhenReady (const Tick tick)
Set tick at which block's data will be available for access.
void trackLoadLocked (PacketPtr pkt)
Track the fact that a local locked was issued to the block.
void clearLoadLocks (const RequestPtr &req)
Clear the any load lock that intersect the request, and is from a different context.
bool checkWrite (PacketPtr pkt)
Handle interaction of load-locked operations and stores.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Protected Attributes
SectorBlk * _sectorBlk
Sector block associated to this block.
int _sectorOffset
The offset of this sub-block in the sector.
Protected Attributes inherited from CacheBlk
std::list< Lock > lockList
List of thread contexts that have performed a load-locked (LL) on the block since the last store.
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Additional Inherited Members
Public Types inherited from CacheBlk
typedef unsigned State
block state: OR of CacheBlkStatusBit
Public Attributes inherited from CacheBlk
uint32_t task_id
Task Id associated with this block.
Addr tag
Data block tag value.
uint8_t * data
Contains a copy of the data in this block for easy access.
State status
The current status of this block.
Tick whenReady
Which curTick() will this block be accessible.
unsigned refCount
Number of references to this block since it was brought in.
int srcMasterId
holds the source requestor ID for this block.
Tick tickInserted
Tick on which the block was inserted in the cache.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Detailed Description
A sector is composed of sub-blocks, and each sub-block has information regarding its sector and a pointer to its sector tag.
Definition at line 50 of file sector_blk.hh.
Constructor & Destructor Documentation
SectorSubBlk() [1/2]
SectorSubBlk::SectorSubBlk () inline
Definition at line 64 of file sector_blk.hh.
References operator=().
SectorSubBlk() [2/2]
SectorSubBlk::SectorSubBlk (const SectorSubBlk &) delete
~SectorSubBlk()
SectorSubBlk::~SectorSubBlk () inline
Definition at line 67 of file sector_blk.hh.
References getSectorBlock(), getSectorOffset(), getTag(), insert(), invalidate(), print(), setSectorBlock(), setSectorOffset(), setSecure(), setValid(), and CacheBlk::tag.
Member Function Documentation
getSectorBlock()
const SectorBlk * SectorSubBlk::getSectorBlock () const
Get sector block associated to this block.
Returns
The sector block pointer.
Definition at line 51 of file sector_blk.cc.
References _sectorBlk.
Referenced by SectorTags::accessBlock(), CompressedTags::insertBlock(), SectorTags::insertBlock(), SectorTags::invalidate(), SectorTags::regenerateBlkAddr(), BaseCache::updateCompressionData(), and ~SectorSubBlk().
getSectorOffset()
int SectorSubBlk::getSectorOffset () const
Get offset of this sub-block within the sector.
Returns
sector_offset The block's offset.
Definition at line 63 of file sector_blk.cc.
References _sectorOffset.
Referenced by print(), SectorTags::regenerateBlkAddr(), and ~SectorSubBlk().
getTag()
Addr SectorSubBlk::getTag () const
Get tag associated to this block.
Returns
The tag value.
Definition at line 69 of file sector_blk.cc.
References _sectorBlk, and SectorBlk::getTag().
Referenced by SectorBlk::~SectorBlk(), and ~SectorSubBlk().
insert()
void SectorSubBlk::insert (const Addr tag, const bool is_secure, const int src_master_ID, const uint32_t task_ID) override virtual
Set member variables when a block insertion occurs.
Resets reference count to 1 (the insertion counts as a reference), and touch block if it hadn't been touched previously. Sets the insertion tick to the current tick. Marks the block valid.
Parameters
tag Block address tag.
is_secure Whether the block is in secure space or not.
src_master_ID The source requestor ID.
task_ID The new task ID.
Reimplemented from CacheBlk.
Definition at line 96 of file sector_blk.cc.
References _sectorBlk, SectorBlk::getTag(), CacheBlk::insert(), SectorBlk::isSecure(), SectorBlk::isValid(), panic_if, SectorBlk::setTag(), and CacheBlk::tag.
Referenced by ~SectorSubBlk().
invalidate()
void SectorSubBlk::invalidate () override virtual
Invalidate the block and inform sector block.
Reimplemented from CacheBlk.
Definition at line 89 of file sector_blk.cc.
References _sectorBlk, CacheBlk::invalidate(), and SectorBlk::invalidateSubBlk().
Referenced by ~SectorSubBlk().
operator=()
SectorSubBlk& SectorSubBlk::operator= (const SectorSubBlk &) delete
Referenced by SectorSubBlk().
print()
std::string SectorSubBlk::print () const override virtual
Pretty-print sector offset and other CacheBlk information.
Returns
string with basic state information
Reimplemented from CacheBlk.
Reimplemented in CompressionBlk.
Definition at line 112 of file sector_blk.cc.
References csprintf(), getSectorOffset(), and CacheBlk::print().
Referenced by CompressionBlk::print(), and ~SectorSubBlk().
setSectorBlock()
void SectorSubBlk::setSectorBlock (SectorBlk * sector_blk)
Set sector block associated to this block.
Parameters
sector_blk The sector block pointer.
Definition at line 44 of file sector_blk.cc.
References _sectorBlk.
Referenced by CompressedTags::tagsInit(), SectorTags::tagsInit(), and ~SectorSubBlk().
setSectorOffset()
void SectorSubBlk::setSectorOffset (const int sector_offset)
Set offset of this sub-block within the sector.
Parameters
sector_offset The block's offset.
Definition at line 57 of file sector_blk.cc.
References _sectorOffset.
Referenced by CompressedTags::tagsInit(), SectorTags::tagsInit(), and ~SectorSubBlk().
setSecure()
void SectorSubBlk::setSecure () override virtual
Set secure bit and inform sector block.
Reimplemented from CacheBlk.
Definition at line 82 of file sector_blk.cc.
References _sectorBlk, SectorBlk::setSecure(), and CacheBlk::setSecure().
Referenced by SectorBlk::~SectorBlk(), and ~SectorSubBlk().
setValid()
void SectorSubBlk::setValid () override virtual
Set valid bit and inform sector block.
Reimplemented from CacheBlk.
Definition at line 75 of file sector_blk.cc.
References _sectorBlk, CacheBlk::setValid(), and SectorBlk::validateSubBlk().
Referenced by ~SectorSubBlk().
Member Data Documentation
_sectorBlk
SectorBlk* SectorSubBlk::_sectorBlk protected
Sector block associated to this block.
Definition at line 56 of file sector_blk.hh.
Referenced by getSectorBlock(), getTag(), insert(), invalidate(), setSectorBlock(), setSecure(), and setValid().
_sectorOffset
int SectorSubBlk::_sectorOffset protected
The offset of this sub-block in the sector.
Definition at line 61 of file sector_blk.hh.
Referenced by getSectorOffset(), and setSectorOffset().
The documentation for this class was generated from the following files:
mem/cache/tags/sector_blk.hh
mem/cache/tags/sector_blk.cc