gem5: Malta Class Reference
Malta Class Reference
Top level class for Malta Chipset emulation.
#include <malta.hh>
Public Types
typedef MaltaParams Params
Constructor for the Malta Class.
Public Types inherited from Platform
typedef PlatformParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Malta (const Params *p)
void postConsoleInt () override
Cause the cpu to post a serial interrupt to the CPU.
void clearConsoleInt () override
Clear a posted CPU interrupt (id=55)
void postPciInt (int line) override
Cause the chipset to post a cpi interrupt to the CPU.
void clearPciInt (int line) override
Clear a posted PCI->CPU interrupt.
virtual Addr pciToDma (Addr pciAddr) const
Addr calcPciConfigAddr (int bus, int dev, int func)
Addr calcPciIOAddr (Addr addr)
Addr calcPciMemAddr (Addr addr)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Platform
Platform (const Params *p)
virtual ~Platform ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
System * system
Pointer to the system.
MaltaIO * io
Pointer to the MaltaIO device which has the RTC.
MaltaCChip * cchip
Pointer to the Malta CChip.
int intr_sum_type [Malta::Max_CPUs]
int ipi_pending [Malta::Max_CPUs]
Public Attributes inherited from Platform
IntrControl * intrctrl
Pointer to the interrupt controller.
Static Public Attributes
static const int Max_CPUs = 64
Max number of CPUs in a Malta.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Top level class for Malta Chipset emulation.
This structure just contains pointers to all the children so the children can commnicate to do the read work
Definition at line 56 of file malta.hh.
Member Typedef Documentation
Params
typedef MaltaParams Malta::Params
Constructor for the Malta Class.
Parameters
name name of the object
s system the object belongs to
intctrl pointer to the interrupt controller
Definition at line 84 of file malta.hh.
Constructor & Destructor Documentation
Malta()
Malta::Malta (const Params * p)
Definition at line 51 of file malta.cc.
References ArmISA::i, intr_sum_type, and Max_CPUs.
Referenced by unserialize().
Member Function Documentation
calcPciConfigAddr()
Addr Malta::calcPciConfigAddr (int bus, int dev, int func) inline
Definition at line 111 of file malta.hh.
References panic.
calcPciIOAddr()
Addr Malta::calcPciIOAddr (Addr addr) inline
Definition at line 118 of file malta.hh.
References panic.
calcPciMemAddr()
Addr Malta::calcPciMemAddr (Addr addr) inline
Definition at line 125 of file malta.hh.
References panic, serialize(), and unserialize().
clearConsoleInt()
void Malta::clearConsoleInt () override virtual
Clear a posted CPU interrupt (id=55)
Implements Platform.
Definition at line 66 of file malta.cc.
References MaltaIO::clearIntr(), and io.
clearPciInt()
void Malta::clearPciInt (int line) override virtual
Clear a posted PCI->CPU interrupt.
Reimplemented from Platform.
Definition at line 79 of file malta.cc.
References panic.
pciToDma()
Addr Malta::pciToDma (Addr pciAddr) const virtual
Definition at line 85 of file malta.cc.
References panic.
postConsoleInt()
void Malta::postConsoleInt () override virtual
Cause the cpu to post a serial interrupt to the CPU.
Implements Platform.
Definition at line 59 of file malta.cc.
References io, and MaltaIO::postIntr().
postPciInt()
void Malta::postPciInt (int line) override virtual
Cause the chipset to post a cpi interrupt to the CPU.
Reimplemented from Platform.
Definition at line 73 of file malta.cc.
References panic.
serialize()
void Malta::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 91 of file malta.cc.
References intr_sum_type, Max_CPUs, and SERIALIZE_ARRAY.
Referenced by calcPciMemAddr().
unserialize()
void Malta::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 97 of file malta.cc.
References intr_sum_type, Malta(), Max_CPUs, and UNSERIALIZE_ARRAY.
Referenced by calcPciMemAddr().
Member Data Documentation
cchip
MaltaCChip* Malta::cchip
Pointer to the Malta CChip.
The chip contains some configuration information and all the interrupt mask and status registers
Definition at line 72 of file malta.hh.
Referenced by MaltaIO::clearIntr(), MaltaIO::RTC::handleEvent(), MaltaCChip::MaltaCChip(), and MaltaIO::postIntr().
intr_sum_type
int Malta::intr_sum_type[Malta::Max_CPUs]
Definition at line 74 of file malta.hh.
Referenced by Malta(), serialize(), and unserialize().
io
MaltaIO* Malta::io
Pointer to the MaltaIO device which has the RTC.
Definition at line 66 of file malta.hh.
Referenced by clearConsoleInt(), MaltaIO::MaltaIO(), and postConsoleInt().
ipi_pending
int Malta::ipi_pending[Malta::Max_CPUs]
Definition at line 75 of file malta.hh.
Max_CPUs
const int Malta::Max_CPUs = 64 static
Max number of CPUs in a Malta.
Definition at line 60 of file malta.hh.
Referenced by MaltaCChip::clearIntr(), Malta(), MaltaCChip::postIntr(), serialize(), and unserialize().
system
System* Malta::system
Pointer to the system.
Definition at line 63 of file malta.hh.
The documentation for this class was generated from the following files:
dev/mips/malta.hh
dev/mips/malta.cc