gem5: VoltageDomain Class Reference
VoltageDomain Class Reference
A VoltageDomain is used to group clock domains that operate under the same voltage.
#include <voltage_domain.hh>
Classes
struct VoltageDomainStats
Public Types
typedef VoltageDomainParams Params
typedef SrcClockDomain::PerfLevel PerfLevel
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
VoltageDomain (const Params *p)
double voltage () const
Get the current voltage.
double voltage (PerfLevel perf_level) const
Get the voltage at specified performance level.
uint32_t numVoltages () const
void perfLevel (PerfLevel perf_level)
Set the voltage point of the domain.
PerfLevel perfLevel () const
Get the voltage point of the domain.
void registerSrcClockDom (SrcClockDomain *src_clock_dom)
Register a SrcClockDomain with this voltage domain.
void startup () override
Startup has all SrcClockDomains registered with this voltage domain, so try to make sure that all perf level requests from them are met.
bool sanitiseVoltages ()
Recomputes the highest (fastest, i.e., numerically lowest) requested performance level of all associated clock domains, and updates the performance level of this voltage domain to match.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Types
typedef std::vector< double > Voltages
typedef std::vector< SrcClockDomain * > SrcClockChildren
List of associated SrcClockDomains that are connected to this voltage domain.
Private Attributes
const Voltages voltageOpPoints
List of possible minimum voltage at each of the frequency operational points, should be in descending order and same size as freqOpPoints.
PerfLevel _perfLevel
VoltageDomain::VoltageDomainStats stats
SrcClockChildren srcClockChildren
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
A VoltageDomain is used to group clock domains that operate under the same voltage.
The class provides methods for setting and getting the voltage.
Definition at line 56 of file voltage_domain.hh.
Member Typedef Documentation
Params
typedef VoltageDomainParams VoltageDomain::Params
Definition at line 60 of file voltage_domain.hh.
PerfLevel
typedef SrcClockDomain::PerfLevel VoltageDomain::PerfLevel
Definition at line 63 of file voltage_domain.hh.
SrcClockChildren
typedef std::vector<SrcClockDomain *> VoltageDomain::SrcClockChildren private
List of associated SrcClockDomains that are connected to this voltage domain.
Definition at line 158 of file voltage_domain.hh.
Voltages
typedef std::vector<double> VoltageDomain::Voltages private
Definition at line 133 of file voltage_domain.hh.
Constructor & Destructor Documentation
VoltageDomain()
VoltageDomain::VoltageDomain (const Params * p)
Definition at line 51 of file voltage_domain.cc.
References fatal_if, SimObject::name(), and voltageOpPoints.
Referenced by startup().
Member Function Documentation
numVoltages()
uint32_t VoltageDomain::numVoltages () const inline
Definition at line 87 of file voltage_domain.hh.
References perfLevel(), and voltageOpPoints.
Referenced by sanitiseVoltages(), SrcClockDomain::SrcClockDomain(), voltage(), and DVFSHandler::voltageAtPerfLevel().
perfLevel() [1/2]
void VoltageDomain::perfLevel (PerfLevel perf_level)
Set the voltage point of the domain.
Parameters
Voltage value to be set
Definition at line 65 of file voltage_domain.cc.
References _perfLevel, chatty_assert, DPRINTF, SimObject::name(), voltage(), and voltageOpPoints.
perfLevel() [2/2]
PerfLevel VoltageDomain::perfLevel () const inline
Get the voltage point of the domain.
Parameters
Voltage value to be set
Definition at line 99 of file voltage_domain.hh.
References _perfLevel.
Referenced by numVoltages(), sanitiseVoltages(), and unserialize().
registerSrcClockDom()
void VoltageDomain::registerSrcClockDom (SrcClockDomain * src_clock_dom) inline
Register a SrcClockDomain with this voltage domain.
Parameters
src_clock_domain The SrcClockDomain to register.
Definition at line 105 of file voltage_domain.hh.
References sanitiseVoltages(), serialize(), srcClockChildren, startup(), unserialize(), and ClockDomain::voltageDomain().
Referenced by SrcClockDomain::SrcClockDomain().
sanitiseVoltages()
bool VoltageDomain::sanitiseVoltages ()
Recomputes the highest (fastest, i.e., numerically lowest) requested performance level of all associated clock domains, and updates the performance level of this voltage domain to match.
This means that for two connected clock domains, one fast and one slow, the voltage domain will provide the voltage associated with the fast DVFS operation point. Must be called whenever a clock domain decides to swtich its performance level.
Returns
True, if the voltage was actually changed.
Definition at line 83 of file voltage_domain.cc.
References chatty_assert, ArmISA::d, ArmISA::dit, SrcClockDomain::domainID(), DPRINTF, SimObject::name(), numVoltages(), perfLevel(), SrcClockDomain::perfLevel(), srcClockChildren, and ClockDomain::voltageDomain().
Referenced by registerSrcClockDom(), SrcClockDomain::signalPerfLevelUpdate(), and startup().
serialize()
void VoltageDomain::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from SimObject.
Definition at line 137 of file voltage_domain.cc.
References _perfLevel, and SERIALIZE_SCALAR.
Referenced by registerSrcClockDom().
startup()
void VoltageDomain::startup () override virtual
Startup has all SrcClockDomains registered with this voltage domain, so try to make sure that all perf level requests from them are met.
Reimplemented from SimObject.
Definition at line 122 of file voltage_domain.cc.
References SimObject::name(), sanitiseVoltages(), VoltageDomain(), and warn.
Referenced by registerSrcClockDom().
unserialize()
void VoltageDomain::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from SimObject.
Definition at line 143 of file voltage_domain.cc.
References _perfLevel, perfLevel(), and UNSERIALIZE_SCALAR.
Referenced by registerSrcClockDom().
voltage() [1/2]
double VoltageDomain::voltage () const inline
Get the current voltage.
Returns
Voltage of the domain
Definition at line 70 of file voltage_domain.hh.
References _perfLevel, and voltageOpPoints.
Referenced by perfLevel(), ClockDomain::voltage(), DVFSHandler::voltageAtPerfLevel(), and VoltageDomain::VoltageDomainStats::VoltageDomainStats().
voltage() [2/2]
double VoltageDomain::voltage (PerfLevel perf_level) const inline
Get the voltage at specified performance level.
Parameters
perf_level Performance level for which the voltage is requested
Returns
Voltage of the domain at specified performance level
Definition at line 78 of file voltage_domain.hh.
References chatty_assert, SimObject::name(), numVoltages(), and voltageOpPoints.
Member Data Documentation
_perfLevel
PerfLevel VoltageDomain::_perfLevel private
Definition at line 142 of file voltage_domain.hh.
Referenced by perfLevel(), serialize(), unserialize(), and voltage().
srcClockChildren
SrcClockChildren VoltageDomain::srcClockChildren private
Definition at line 159 of file voltage_domain.hh.
Referenced by registerSrcClockDom(), and sanitiseVoltages().
stats
VoltageDomain::VoltageDomainStats VoltageDomain::stats private
voltageOpPoints
const Voltages VoltageDomain::voltageOpPoints private
List of possible minimum voltage at each of the frequency operational points, should be in descending order and same size as freqOpPoints.
An empty list corresponds to default voltage specified for the voltage domain its clock domain belongs. The same voltage is applied for each freqOpPoints, overall implying NO DVS
Definition at line 141 of file voltage_domain.hh.
Referenced by numVoltages(), perfLevel(), voltage(), and VoltageDomain().
The documentation for this class was generated from the following files:
sim/voltage_domain.hh
sim/voltage_domain.cc