gem5: HsaObject Class Reference
HsaObject Class Reference abstract
#include <hsa_object.hh>
Public Member Functions
HsaObject (const std::string &fileName)
virtual HsaCode * getKernel (const std::string &name) const =0
virtual HsaCode * getKernel (int i) const =0
virtual HsaCode * getFunction (const std::string &name) const =0
virtual int numKernels () const =0
const std::string & name () const
Static Public Member Functions
static HsaObject * createHsaObject (const std::string &fname)
Public Attributes
uint8_t * readonlyData
Static Public Attributes
static std::vector< std::function< HsaObject *(const std::string &, int, uint8_t *)> > tryFileFuncs = { BrigObject::tryFile }
Protected Attributes
const std::string filename
Detailed Description
Definition at line 51 of file hsa_object.hh.
Constructor & Destructor Documentation
HsaObject()
HsaObject::HsaObject (const std::string & fileName)
Definition at line 43 of file hsa_object.cc.
Member Function Documentation
createHsaObject()
HsaObject * HsaObject::createHsaObject (const std::string & fname) static
Definition at line 49 of file hsa_object.cc.
References MipsISA::ate, fatal, and tryFileFuncs.
Referenced by ClDriver::ClDriver().
getFunction()
virtual HsaCode* HsaObject::getFunction (const std::string & name) const pure virtual
Implemented in BrigObject.
getKernel() [1/2]
virtual HsaCode* HsaObject::getKernel (const std::string & name) const pure virtual
Implemented in BrigObject.
Referenced by ClDriver::ClDriver().
getKernel() [2/2]
virtual HsaCode* HsaObject::getKernel (int i) const pure virtual
Implemented in BrigObject.
name()
const std::string& HsaObject::name () const inline
Definition at line 65 of file hsa_object.hh.
References filename.
numKernels()
virtual int HsaObject::numKernels () const pure virtual
Implemented in BrigObject.
Referenced by ClDriver::ClDriver().
Member Data Documentation
filename
const std::string HsaObject::filename protected
Definition at line 71 of file hsa_object.hh.
Referenced by name().
readonlyData
uint8_t* HsaObject::readonlyData
Definition at line 67 of file hsa_object.hh.
Referenced by ClDriver::ClDriver().
tryFileFuncs
std::vector< std::function< HsaObject *(const std::string &, int, uint8_t *)> > HsaObject::tryFileFuncs = { BrigObject::tryFile } static
Definition at line 58 of file hsa_object.hh.
Referenced by createHsaObject().
The documentation for this class was generated from the following files:
gpu-compute/hsa_object.hh
gpu-compute/brig_object.cc
gpu-compute/hsa_object.cc