gem5: EnergyCtrl Class Reference
EnergyCtrl Class Reference
#include <energy_ctrl.hh>
Public Types
enum Registers {
DVFS_HANDLER_STATUS = 0, DVFS_NUM_DOMAINS, DVFS_DOMAINID_AT_INDEX, DVFS_HANDLER_TRANS_LATENCY,
DOMAIN_ID, PERF_LEVEL, PERF_LEVEL_ACK, NUM_OF_PERF_LEVELS,
PERF_LEVEL_TO_READ, FREQ_AT_PERF_LEVEL, VOLT_AT_PERF_LEVEL, PIO_NUM_FIELDS
}
Discovery flows:
typedef EnergyCtrlParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
EnergyCtrl (const Params *p)
Tick read (PacketPtr pkt) override
Read command sent to the device.
Tick write (PacketPtr pkt) override
Write command sent to the device.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup () override
startup() is the final initialization call before simulation.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
void updatePLAck ()
Update the acknowledgment that is read back by the software to confirm newly requested performance level has been set.
Static Private Member Functions
static uint32_t ticksTokHz (Tick period)
static uint32_t toMicroVolt (double voltage)
Private Attributes
DVFSHandler * dvfsHandler
uint32_t domainID
Cluster ID (DOMAIN_ID) R/W register, programmed to ID of the domain for which the set/get performance level command can be issued.
uint32_t domainIDIndexToRead
Index for getting the domain ID from the domain ID list available with the DVFS handler.
uint32_t perfLevelAck
Acknowledgment (PERF_LEVEL_ACK) RO register, software polls this register to read back the status of the last programmed change in the domain ID and/or the performance level.
uint32_t perfLevelToRead
EventFunctionWrapper updateAckEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 65 of file energy_ctrl.hh.
Member Typedef Documentation
Params
typedef EnergyCtrlParams EnergyCtrl::Params
Definition at line 119 of file energy_ctrl.hh.
Member Enumeration Documentation
Registers
enum EnergyCtrl::Registers
Discovery flows:
get basic DVFS handler information read(DVFS_HANDLER_STATUS) read(DVFS_HANDLER_TRANS_LATENCY)
get the number of domain IDs read(DVFS_NUM_DOMAINS) -> domains
query the driver to get the IDs for all i in domains write(DVFS_DOMAINID_AT_INDEX <- i) read(DOMAIN_ID) -> domainID_i
for each domainID i get voltage / frequency pairs write(DOMAIN_ID <- domainID_i) read(NUM_OF_PERF_LEVELS) -> levels_i
for each l in levels_i write(PERF_LEVEL_TO_READ <- l) read(FREQ_AT_PERF_LEVEL) -> freq_l_i read(VOLT_AT_PERF_LEVEL) -> volt_l_i
Setting a specific performance level (V/F combination)
get performance for domain_ID i write(DOMAIN_ID <- i) read(PERF_LEVEL) -> perf_level_i
set performance for domain_ID i write(DOMAIN_ID <- i) write(PERF_LEVEL <- perf_level_i)
wait for DVFS transition completion while (!read(PERF_LEVEL_ACK));
Enumerator
DVFS_HANDLER_STATUS
DVFS_NUM_DOMAINS
DVFS_DOMAINID_AT_INDEX
DVFS_HANDLER_TRANS_LATENCY
DOMAIN_ID
PERF_LEVEL
PERF_LEVEL_ACK
NUM_OF_PERF_LEVELS
PERF_LEVEL_TO_READ
FREQ_AT_PERF_LEVEL
VOLT_AT_PERF_LEVEL
PIO_NUM_FIELDS
Definition at line 104 of file energy_ctrl.hh.
Constructor & Destructor Documentation
EnergyCtrl()
EnergyCtrl::EnergyCtrl (const Params * p)
Definition at line 50 of file energy_ctrl.cc.
References fatal_if, SimObject::name(), MipsISA::p, and updatePLAck().
Referenced by unserialize().
Member Function Documentation
init()
void EnergyCtrl::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 261 of file energy_ctrl.cc.
References PioDevice::init().
read()
Tick EnergyCtrl::read (PacketPtr pkt) override virtual
Read command sent to the device.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 64 of file energy_ctrl.cc.
References DVFSHandler::clkPeriodAtPerfLevel(), DOMAIN_ID, DVFSHandler::domainID(), domainID, domainIDIndexToRead, DPRINTF, DVFS_DOMAINID_AT_INDEX, DVFS_HANDLER_STATUS, DVFS_HANDLER_TRANS_LATENCY, DVFS_NUM_DOMAINS, dvfsHandler, FREQ_AT_PERF_LEVEL, Packet::getAddr(), Packet::getSize(), DVFSHandler::isEnabled(), Packet::makeAtomicResponse(), SimClock::Int::ns, NUM_OF_PERF_LEVELS, DVFSHandler::numDomains(), DVFSHandler::numPerfLevels(), panic, PERF_LEVEL, PERF_LEVEL_ACK, DVFSHandler::perfLevel(), perfLevelAck, perfLevelToRead, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, X86ISA::reg, Packet::setLE(), ticksTokHz(), toMicroVolt(), DVFSHandler::transLatency(), VOLT_AT_PERF_LEVEL, Clocked::voltage(), DVFSHandler::voltageAtPerfLevel(), and warn_once.
serialize()
void EnergyCtrl::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 220 of file energy_ctrl.cc.
References domainID, domainIDIndexToRead, perfLevelAck, perfLevelToRead, Event::scheduled(), SERIALIZE_SCALAR, updateAckEvent, and Event::when().
startup()
void EnergyCtrl::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 253 of file energy_ctrl.cc.
References dvfsHandler, DVFSHandler::isEnabled(), and warn.
ticksTokHz()
static uint32_t EnergyCtrl::ticksTokHz (Tick period) inline static private
Definition at line 169 of file energy_ctrl.hh.
References SimClock::Int::ms.
Referenced by read().
toMicroVolt()
static uint32_t EnergyCtrl::toMicroVolt (double voltage) inline static private
Definition at line 173 of file energy_ctrl.hh.
Referenced by read().
unserialize()
void EnergyCtrl::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 232 of file energy_ctrl.cc.
References domainID, domainIDIndexToRead, EnergyCtrl(), perfLevelAck, perfLevelToRead, EventManager::schedule(), UNSERIALIZE_SCALAR, and updateAckEvent.
updatePLAck()
void EnergyCtrl::updatePLAck () inline private
Update the acknowledgment that is read back by the software to confirm newly requested performance level has been set.
Definition at line 181 of file energy_ctrl.hh.
Referenced by EnergyCtrl().
write()
Tick EnergyCtrl::write (PacketPtr pkt) override virtual
Write command sent to the device.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 150 of file energy_ctrl.cc.
References curTick(), data, EventManager::deschedule(), DOMAIN_ID, domainID, domainIDIndexToRead, DPRINTF, DVFS_DOMAINID_AT_INDEX, dvfsHandler, Packet::getAddr(), Packet::getLE(), Packet::getSize(), DVFSHandler::isEnabled(), Packet::makeAtomicResponse(), panic, PERF_LEVEL, PERF_LEVEL_TO_READ, DVFSHandler::perfLevel(), perfLevelToRead, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, X86ISA::reg, EventManager::schedule(), Event::scheduled(), DVFSHandler::transLatency(), updateAckEvent, DVFSHandler::validDomainID(), and warn_once.
Member Data Documentation
domainID
uint32_t EnergyCtrl::domainID private
Cluster ID (DOMAIN_ID) R/W register, programmed to ID of the domain for which the set/get performance level command can be issued.
Definition at line 148 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
domainIDIndexToRead
uint32_t EnergyCtrl::domainIDIndexToRead private
Index for getting the domain ID from the domain ID list available with the DVFS handler.
Definition at line 154 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
dvfsHandler
DVFSHandler* EnergyCtrl::dvfsHandler private
Definition at line 142 of file energy_ctrl.hh.
Referenced by read(), startup(), and write().
perfLevelAck
uint32_t EnergyCtrl::perfLevelAck private
Acknowledgment (PERF_LEVEL_ACK) RO register, software polls this register to read back the status of the last programmed change in the domain ID and/or the performance level.
Valid values are: '0' - Ack is not OK yet '1' - Ack is OK It is a read destructive register with a read of '1' resets the ack to '0'.
Definition at line 165 of file energy_ctrl.hh.
Referenced by read(), serialize(), and unserialize().
perfLevelToRead
uint32_t EnergyCtrl::perfLevelToRead private
Definition at line 167 of file energy_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
updateAckEvent
EventFunctionWrapper EnergyCtrl::updateAckEvent private
Definition at line 185 of file energy_ctrl.hh.
Referenced by serialize(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/arm/energy_ctrl.hh
dev/arm/energy_ctrl.cc