gem5: Minor::Pipeline Class Reference
Minor::Pipeline Class Reference
The constructed pipeline.
#include <pipeline.hh>
Public Types
enum StageId {
CPUStageId = 0, Fetch1StageId, Fetch2StageId, DecodeStageId,
ExecuteStageId, Num_StageId
}
Enumerated ids of the 'stages' for the activity recorder.
Public Member Functions
Pipeline (MinorCPU &cpu_, MinorCPUParams &params)
void wakeupFetch (ThreadID tid)
Wake up the Fetch unit.
bool drain ()
Try to drain the CPU.
void drainResume ()
bool isDrained ()
Test to see if the CPU is drained.
void evaluate () override
A custom evaluate allows report in the right place (between stages and pipeline advance)
void minorTrace () const
void regStats ()
Stats registering.
MinorCPU::MinorCPUPort & getInstPort ()
Functions below here are BaseCPU operations passed on to pipeline stages.
MinorCPU::MinorCPUPort & getDataPort ()
Return the DcachePort belonging to Execute for the CPU.
MinorActivityRecorder * getActivityRecorder ()
To give the activity recorder to the CPU.
Public Member Functions inherited from Ticked
Ticked (ClockedObject &object_, Stats::Scalar *imported_num_cycles=NULL, Event::Priority priority=Event::CPU_Tick_Pri)
virtual ~Ticked ()
void regStats ()
Register {num,ticks}Cycles if necessary.
void start ()
Start ticking.
Cycles cyclesSinceLastStopped () const
How long have we been stopped for?
void resetLastStopped ()
Reset stopped time to current time.
void stop ()
Cancel the next tick event and issue no more.
void serialize (CheckpointOut &cp) const override
Checkpoint lastStopped.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
virtual void countCycles (Cycles delta)
Callback to handle cycle statistics and probes.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
bool needToSignalDrained
True after drain is called but draining isn't complete.
Protected Attributes
MinorCPU & cpu
bool allow_idling
Allow cycles to be skipped when the pipeline is idle.
Latch< ForwardLineData > f1ToF2
Latch< BranchData > f2ToF1
Latch< ForwardInstData > f2ToD
Latch< ForwardInstData > dToE
Latch< BranchData > eToF1
Execute execute
Decode decode
Fetch2 fetch2
Fetch1 fetch1
MinorActivityRecorder activityRecorder
Activity recording for the pipeline.
Protected Attributes inherited from Ticked
ClockedObject & object
ClockedObject who is responsible for this Ticked's actions/stats.
EventFunctionWrapper event
The wrapper for processClockEvent.
bool running
Have I been started? and am not stopped.
Cycles lastStopped
Time of last stop event to calculate run time.
Stats::Scalar & numCycles
Total number of cycles either ticked or spend stopped.
Stats::Scalar tickCycles
Number of cycles ticked.
Stats::Formula idleCycles
Number of cycles stopped.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Ticked
void processClockEvent ()
Evaluate and reschedule.
Detailed Description
The constructed pipeline.
Kept out of MinorCPU to keep the interface between the CPU and its grubby implementation details clean.
Definition at line 71 of file pipeline.hh.
Member Enumeration Documentation
StageId
enum Minor::Pipeline::StageId
Enumerated ids of the 'stages' for the activity recorder.
Enumerator
CPUStageId
Fetch1StageId
Fetch2StageId
DecodeStageId
ExecuteStageId
Num_StageId
Definition at line 97 of file pipeline.hh.
Constructor & Destructor Documentation
Pipeline()
Minor::Pipeline::Pipeline (MinorCPU & cpu_, MinorCPUParams & params)
Definition at line 56 of file pipeline.cc.
References cpu, fatal, and SimObject::name().
Member Function Documentation
drain()
bool Minor::Pipeline::drain ()
Try to drain the CPU.
Definition at line 205 of file pipeline.cc.
References DPRINTF, Minor::Execute::drain(), execute, isDrained(), and needToSignalDrained.
drainResume()
void Minor::Pipeline::drainResume ()
Definition at line 221 of file pipeline.cc.
References cpu, DPRINTF, Minor::Execute::drainResume(), execute, fetch1, BaseCPU::numThreads, and Minor::Fetch1::wakeupFetch().
evaluate()
void Minor::Pipeline::evaluate () override virtual
A custom evaluate allows report in the right place (between stages and pipeline advance)
Implements Ticked.
Definition at line 132 of file pipeline.cc.
References ActivityRecorder::active(), activityRecorder, allow_idling, cpu, CPUStageId, ActivityRecorder::deactivateStage(), decode, DecodeStageId, DPRINTF, dToE, DTRACE, eToF1, Minor::MinorActivityRecorder::evaluate(), Minor::Decode::evaluate(), Minor::Fetch2::evaluate(), Minor::Execute::evaluate(), Minor::Fetch1::evaluate(), execute, ExecuteStageId, f1ToF2, f2ToD, f2ToF1, fetch1, Fetch1StageId, fetch2, Fetch2StageId, isDrained(), minorTrace(), needToSignalDrained, MinorCPU::signalDrainDone(), and Ticked::stop().
getActivityRecorder()
MinorActivityRecorder* Minor::Pipeline::getActivityRecorder () inline
To give the activity recorder to the CPU.
Definition at line 143 of file pipeline.hh.
References activityRecorder.
getDataPort()
MinorCPU::MinorCPUPort & Minor::Pipeline::getDataPort ()
Return the DcachePort belonging to Execute for the CPU.
Definition at line 193 of file pipeline.cc.
References execute, and Minor::Execute::getDcachePort().
getInstPort()
MinorCPU::MinorCPUPort & Minor::Pipeline::getInstPort ()
Functions below here are BaseCPU operations passed on to pipeline stages.
Return the IcachePort belonging to Fetch1 for the CPU
Definition at line 187 of file pipeline.cc.
References fetch1, and Minor::Fetch1::getIcachePort().
isDrained()
bool Minor::Pipeline::isDrained ()
Test to see if the CPU is drained.
Definition at line 233 of file pipeline.cc.
References decode, DPRINTF, dToE, execute, f1ToF2, f2ToD, f2ToF1, fetch1, fetch2, Minor::Decode::isDrained(), Minor::Fetch2::isDrained(), Minor::Execute::isDrained(), and Minor::Fetch1::isDrained().
Referenced by drain(), and evaluate().
minorTrace()
void Minor::Pipeline::minorTrace () const
Definition at line 117 of file pipeline.cc.
References activityRecorder, decode, dToE, eToF1, execute, f1ToF2, f2ToD, f2ToF1, fetch1, fetch2, Minor::MinorActivityRecorder::minorTrace(), Minor::Decode::minorTrace(), Minor::Fetch2::minorTrace(), Minor::Execute::minorTrace(), and Minor::Fetch1::minorTrace().
Referenced by evaluate().
regStats()
void Minor::Pipeline::regStats ()
Stats registering.
Definition at line 109 of file pipeline.cc.
References fetch2, Ticked::regStats(), and Minor::Fetch2::regStats().
wakeupFetch()
void Minor::Pipeline::wakeupFetch (ThreadID tid)
Wake up the Fetch unit.
This is needed on thread activation esp. after quiesce wakeup
Definition at line 199 of file pipeline.cc.
References fetch1, and Minor::Fetch1::wakeupFetch().
Member Data Documentation
activityRecorder
MinorActivityRecorder Minor::Pipeline::activityRecorder protected
Activity recording for the pipeline.
This is access through the CPU by the pipeline stages but belongs to the Pipeline as it is the cleanest place to initialise it
Definition at line 93 of file pipeline.hh.
Referenced by evaluate(), getActivityRecorder(), and minorTrace().
allow_idling
bool Minor::Pipeline::allow_idling protected
Allow cycles to be skipped when the pipeline is idle.
Definition at line 77 of file pipeline.hh.
Referenced by evaluate().
cpu
MinorCPU& Minor::Pipeline::cpu protected
Definition at line 74 of file pipeline.hh.
Referenced by drainResume(), evaluate(), and Pipeline().
decode
Decode Minor::Pipeline::decode protected
Definition at line 86 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
dToE
Latch<ForwardInstData> Minor::Pipeline::dToE protected
Definition at line 82 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
eToF1
Latch<BranchData> Minor::Pipeline::eToF1 protected
Definition at line 83 of file pipeline.hh.
Referenced by evaluate(), and minorTrace().
execute
Execute Minor::Pipeline::execute protected
Definition at line 85 of file pipeline.hh.
Referenced by drain(), drainResume(), evaluate(), getDataPort(), isDrained(), and minorTrace().
f1ToF2
Latch<ForwardLineData> Minor::Pipeline::f1ToF2 protected
Definition at line 79 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
f2ToD
Latch<ForwardInstData> Minor::Pipeline::f2ToD protected
Definition at line 81 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
f2ToF1
Latch<BranchData> Minor::Pipeline::f2ToF1 protected
Definition at line 80 of file pipeline.hh.
Referenced by evaluate(), isDrained(), and minorTrace().
fetch1
Fetch1 Minor::Pipeline::fetch1 protected
Definition at line 88 of file pipeline.hh.
Referenced by drainResume(), evaluate(), getInstPort(), isDrained(), minorTrace(), and wakeupFetch().
fetch2
Fetch2 Minor::Pipeline::fetch2 protected
Definition at line 87 of file pipeline.hh.
Referenced by evaluate(), isDrained(), minorTrace(), and regStats().
needToSignalDrained
bool Minor::Pipeline::needToSignalDrained
True after drain is called but draining isn't complete.
Definition at line 107 of file pipeline.hh.
Referenced by drain(), and evaluate().
The documentation for this class was generated from the following files:
cpu/minor/pipeline.hh
cpu/minor/pipeline.cc