gem5: FrameBuffer Class Reference
FrameBuffer Class Reference
Internal gem5 representation of a frame buffer.
#include <framebuffer.hh>
Public Member Functions
FrameBuffer (unsigned width, unsigned height)
Create a frame buffer of a given size.
FrameBuffer ()
Create an empty (0x0) frame buffer.
virtual ~FrameBuffer ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void resize (unsigned width, unsigned height)
Resize the frame buffer.
unsigned width () const
Frame buffer width in pixels.
unsigned height () const
Frame buffer height in pixels.
unsigned area () const
Total number of pixels in frame buffer.
void fill (const Pixel &pixel)
Fill the frame buffer with a single pixel value.
void clear ()
Fill the frame buffer with black pixels.
void copyIn (const uint8_t *fb, const PixelConverter &conv)
Fill the frame buffer with pixel data from an external buffer of the same width and height as this frame buffer.
void copyIn (const std::vector< uint8_t > &fb, const PixelConverter &conv)
Fill the frame buffer with pixel data from an external buffer of the same width and height as this frame buffer.
void copyOut (uint8_t *fb, const PixelConverter &conv) const
Store the contents of this frame buffer in an external buffer of the same width and height as this frame buffer.
void copyOut (std::vector< uint8_t > &fb, const PixelConverter &conv) const
Store the contents of this frame buffer in an external buffer of the same width and height as this frame buffer.
const Pixel & pixel (unsigned x, unsigned y) const
Get a pixel from an (x, y) coordinate.
Pixel & pixel (unsigned x, unsigned y)
Get a pixel from an (x, y) coordinate.
uint64_t getHash () const
Create a hash of the image that can be used for quick comparisons.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
std::vector< Pixel > pixels
Frame buffer backing store.
Static Public Attributes
static const FrameBuffer dummy
Static "dummy" frame buffer.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes
unsigned _width
Width in pixels.
unsigned _height
Height in pixels.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Internal gem5 representation of a frame buffer.
Display controllers and other devices producing images are expected to use this class to represent the final image.
Pixels are indexed relative to the upper left corner of the image. That is, the pixel at position (0, 0) is the upper left corner. The backing store is a linear vector of Pixels ordered left to right starting in the upper left corner.
Definition at line 67 of file framebuffer.hh.
Constructor & Destructor Documentation
FrameBuffer() [1/2]
FrameBuffer::FrameBuffer (unsigned width, unsigned height)
Create a frame buffer of a given size.
Parameters
width Width in pixels
height Height in pixels
Definition at line 48 of file framebuffer.cc.
References clear().
FrameBuffer() [2/2]
FrameBuffer::FrameBuffer ()
Create an empty (0x0) frame buffer.
Definition at line 55 of file framebuffer.cc.
~FrameBuffer()
FrameBuffer::~FrameBuffer () virtual
Definition at line 60 of file framebuffer.cc.
Member Function Documentation
area()
unsigned FrameBuffer::area () const inline
Total number of pixels in frame buffer.
Definition at line 102 of file framebuffer.hh.
References _height, _width, clear(), copyIn(), ArmISA::fb, fill(), and pixel().
Referenced by BmpWriter::getCompleteHeader(), getHash(), and PngWriter::write().
clear()
void FrameBuffer::clear ()
Fill the frame buffer with black pixels.
Definition at line 98 of file framebuffer.cc.
References fill().
Referenced by area(), and FrameBuffer().
copyIn() [1/2]
void FrameBuffer::copyIn (const uint8_t * fb, const PixelConverter & conv)
Fill the frame buffer with pixel data from an external buffer of the same width and height as this frame buffer.
Parameters
fb External frame buffer
conv Pixel conversion helper
Definition at line 106 of file framebuffer.cc.
References PixelConverter::length, MipsISA::p, pixels, and PixelConverter::toPixel().
Referenced by area(), copyIn(), Pl111::dmaDone(), and Pl111::unserialize().
copyIn() [2/2]
void FrameBuffer::copyIn (const std::vector< uint8_t > & fb, const PixelConverter & conv) inline
Fill the frame buffer with pixel data from an external buffer of the same width and height as this frame buffer.
Parameters
fb External frame buffer
conv Pixel conversion helper
Definition at line 130 of file framebuffer.hh.
References copyIn(), and copyOut().
copyOut() [1/2]
void FrameBuffer::copyOut (uint8_t * fb, const PixelConverter & conv) const
Store the contents of this frame buffer in an external buffer of the same width and height as this frame buffer.
Parameters
fb External frame buffer
conv Pixel conversion helper
Definition at line 115 of file framebuffer.cc.
References PixelConverter::fromPixel(), PixelConverter::length, MipsISA::p, and pixels.
Referenced by copyIn(), and copyOut().
copyOut() [2/2]
void FrameBuffer::copyOut (std::vector< uint8_t > & fb, const PixelConverter & conv) const inline
Store the contents of this frame buffer in an external buffer of the same width and height as this frame buffer.
Parameters
fb External frame buffer
conv Pixel conversion helper
Definition at line 149 of file framebuffer.hh.
References copyOut().
fill()
void FrameBuffer::fill (const Pixel & pixel)
Fill the frame buffer with a single pixel value.
Parameters
pixel Pixel value to fill with.
Definition at line 91 of file framebuffer.cc.
References MipsISA::p, pixel(), and pixels.
Referenced by area(), and clear().
getHash()
uint64_t FrameBuffer::getHash () const
Create a hash of the image that can be used for quick comparisons.
Definition at line 124 of file framebuffer.cc.
References area(), and pixels.
Referenced by VncInput::captureFrameBuffer(), and pixel().
height()
unsigned FrameBuffer::height () const inline
Frame buffer height in pixels.
Definition at line 100 of file framebuffer.hh.
References _height.
Referenced by BmpWriter::getCompleteHeader(), resize(), VncServer::sendFrameBufferUpdate(), VncInput::setDirty(), BasePixelPump::updateTimings(), PngWriter::write(), and BmpWriter::write().
pixel() [1/2]
const Pixel& FrameBuffer::pixel (unsigned x, unsigned y) const inline
Get a pixel from an (x, y) coordinate.
Parameters
x Distance from the left margin.
y Distance from the top of the frame.
Definition at line 159 of file framebuffer.hh.
References _height, _width, pixels, and X86ISA::x.
Referenced by area(), fill(), BasePixelPump::renderLine(), BasePixelPump::renderPixels(), VncServer::sendFrameBufferUpdate(), PngWriter::write(), and BmpWriter::write().
pixel() [2/2]
Pixel& FrameBuffer::pixel (unsigned x, unsigned y) inline
Get a pixel from an (x, y) coordinate.
Parameters
x Distance from the left margin.
y Distance from the top of the frame.
Definition at line 172 of file framebuffer.hh.
References _height, _width, getHash(), pixels, and X86ISA::x.
resize()
void FrameBuffer::resize (unsigned width, unsigned height)
Resize the frame buffer.
This method resizes frame buffer including the backing store. The contents of the backing store are undefined after this operation.
Parameters
with Width in pixels.
height Height in pixels.
Definition at line 82 of file framebuffer.cc.
References _height, _width, height(), pixels, and width().
Referenced by BasePixelPump::updateTimings(), and Pl111::updateVideoParams().
serialize()
void FrameBuffer::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 66 of file framebuffer.cc.
References _height, _width, pixels, SERIALIZE_CONTAINER, and SERIALIZE_SCALAR.
unserialize()
void FrameBuffer::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 74 of file framebuffer.cc.
References _height, _width, pixels, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
width()
unsigned FrameBuffer::width () const inline
Frame buffer width in pixels.
Definition at line 98 of file framebuffer.hh.
References _width.
Referenced by BmpWriter::getCompleteHeader(), resize(), VncServer::sendFrameBufferUpdate(), VncInput::setDirty(), BasePixelPump::updateTimings(), PngWriter::write(), and BmpWriter::write().
Member Data Documentation
_height
unsigned FrameBuffer::_height protected
Height in pixels.
Definition at line 200 of file framebuffer.hh.
Referenced by area(), height(), pixel(), resize(), serialize(), and unserialize().
_width
unsigned FrameBuffer::_width protected
Width in pixels.
Definition at line 198 of file framebuffer.hh.
Referenced by area(), pixel(), resize(), serialize(), unserialize(), and width().
dummy
const FrameBuffer FrameBuffer::dummy static
Static "dummy" frame buffer.
This is a dummy frame buffer that can be used as a place holder for devices that always expect a frame buffer to be present.
Definition at line 191 of file framebuffer.hh.
pixels
std::vector<Pixel> FrameBuffer::pixels
Frame buffer backing store.
Definition at line 194 of file framebuffer.hh.
Referenced by copyIn(), copyOut(), fill(), getHash(), pixel(), resize(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
base/framebuffer.hh
base/framebuffer.cc