gem5: SkipFuncEvent Class Reference
SkipFuncEvent Class Reference
#include <system_events.hh>
Public Member Functions
SkipFuncEvent (PCEventScope *s, const std::string &desc, Addr addr)
virtual void process (ThreadContext *tc)
Public Member Functions inherited from PCEvent
PCEvent (PCEventScope *q, const std::string &desc, Addr pc)
virtual ~PCEvent ()
virtual const std::string name () const
std::string descr () const
Addr pc () const
bool remove ()
Additional Inherited Members
Protected Attributes inherited from PCEvent
std::string description
PCEventScope * scope
Addr evpc
Detailed Description
Definition at line 38 of file system_events.hh.
Constructor & Destructor Documentation
SkipFuncEvent()
SkipFuncEvent::SkipFuncEvent (PCEventScope * s, const std::string & desc, Addr addr) inline
Definition at line 41 of file system_events.hh.
References process().
Member Function Documentation
process()
void SkipFuncEvent::process (ThreadContext * tc) virtual
Implements PCEvent.
Reimplemented in Linux::UDelayEvent, FreeBSD::UDelayEvent, LinuxMipsSystem::SkipDelayLoopEvent, LinuxAlphaSystem::SkipDelayLoopEvent, Linux::DebugPrintkEvent, and FreebsdAlphaSystem::SkipCalibrateClocksEvent.
Definition at line 44 of file system_events.cc.
References DPRINTF, M5_VAR_USED, ThreadContext::pcState(), and AlphaISA::skipFunction().
Referenced by FreebsdAlphaSystem::SkipCalibrateClocksEvent::process(), Linux::DebugPrintkEvent::process(), LinuxAlphaSystem::SkipDelayLoopEvent::process(), LinuxMipsSystem::SkipDelayLoopEvent::process(), FreeBSD::UDelayEvent::process(), Linux::UDelayEvent::process(), and SkipFuncEvent().
The documentation for this class was generated from the following files:
kern/system_events.hh
kern/system_events.cc