gem5: AlphaISA::NDtbMissFault Class Reference
AlphaISA::NDtbMissFault Class Reference
#include <faults.hh>
Public Member Functions
NDtbMissFault (VAddr vaddr, Request::Flags reqFlags, uint64_t flags)
FaultName name () const
FaultVect vect ()
FaultStat & countStat ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Public Member Functions inherited from AlphaISA::DtbFault
DtbFault (VAddr _vaddr, Request::Flags _reqFlags, uint64_t _flags)
Public Member Functions inherited from AlphaISA::AlphaFault
virtual ~AlphaFault ()
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Static Private Attributes
static FaultName _name = "dtb_miss_single"
static FaultVect _vect = 0x0201
static FaultStat _count
Additional Inherited Members
Protected Member Functions inherited from AlphaISA::AlphaFault
virtual bool skipFaultingInstruction ()
virtual bool setRestartAddress ()
Protected Attributes inherited from AlphaISA::DtbFault
VAddr vaddr
Request::Flags reqFlags
uint64_t flags
Detailed Description
Definition at line 150 of file faults.hh.
Constructor & Destructor Documentation
NDtbMissFault()
AlphaISA::NDtbMissFault::NDtbMissFault (VAddr vaddr, Request::Flags reqFlags, uint64_t flags) inline
Definition at line 158 of file faults.hh.
Member Function Documentation
countStat()
FaultStat& AlphaISA::NDtbMissFault::countStat () inline virtual
Implements AlphaISA::DtbFault.
Definition at line 163 of file faults.hh.
References AlphaISA::AlphaFault::invoke(), and StaticInst::nullStaticInstPtr.
invoke()
void AlphaISA::NDtbMissFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from AlphaISA::DtbFault.
Definition at line 210 of file faults.cc.
References Process::fixupStackFault(), EmulationPageTable::Entry::flags, FullSystem, ThreadContext::getDTBPtr(), ThreadContext::getProcessPtr(), AlphaISA::DtbFault::invoke(), EmulationPageTable::lookup(), MipsISA::p, EmulationPageTable::Entry::paddr, panic_if, EmulationPageTable::pid(), Process::pTable, EmulationPageTable::ReadOnly, EmulationPageTable::Uncacheable, and MipsISA::vaddr.
name()
FaultName AlphaISA::NDtbMissFault::name () const inline virtual
Implements AlphaISA::DtbFault.
Definition at line 161 of file faults.hh.
vect()
FaultVect AlphaISA::NDtbMissFault::vect () inline virtual
Implements AlphaISA::DtbFault.
Definition at line 162 of file faults.hh.
Member Data Documentation
_count
FaultStat AlphaISA::NDtbMissFault::_count static private
Definition at line 155 of file faults.hh.
_name
FaultName AlphaISA::NDtbMissFault::_name = "dtb_miss_single" static private
Definition at line 153 of file faults.hh.
_vect
FaultVect AlphaISA::NDtbMissFault::_vect = 0x0201 static private
Definition at line 154 of file faults.hh.
The documentation for this class was generated from the following files:
arch/alpha/faults.hh
arch/alpha/faults.cc