gem5: VncServer Class Reference
VncServer Class Reference
#include <vncserver.hh>
Classes
class DataEvent
DataEvent to read data from vnc.
struct FrameBufferRect
struct FrameBufferUpdate
class ListenEvent
ListenEvent to accept a vnc client connection.
struct ServerCutText
struct ServerInitMsg
Public Types
enum ServerMessages { ServerFrameBufferUpdate = 0, ServerSetColorMapEntries = 1, ServerBell = 2, ServerCutText = 3 }
Server -> Client message IDs.
enum EncodingTypes { EncodingRaw = 0, EncodingCopyRect = 1, EncodingHextile = 5, EncodingDesktopSize = -223 }
Encoding types.
enum MouseEvents { MouseLeftButton = 0x1, MouseRightButton = 0x2, MouseMiddleButton = 0x4 }
keyboard/mouse support
enum ConnectionState {
WaitForProtocolVersion, WaitForSecurityResponse, WaitForClientInit, InitializationPhase,
NormalPhase
}
typedef VncServerParams Params
Public Types inherited from VncInput
enum ClientMessages {
ClientSetPixelFormat = 0, ClientSetEncodings = 2, ClientFrameBufferUpdate = 3, ClientKeyEvent = 4,
ClientPointerEvent = 5, ClientCutText = 6
}
Client -> Server message IDs.
typedef VncInputParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const char * vncVersion () const
VncServer (const Params *p)
VncServer.
~VncServer ()
void setDirty () override
The frame buffer uses this call to notify the vnc server that the frame buffer has been updated and a new image needs to be sent to the client.
void frameBufferResized () override
Public Member Functions inherited from VncInput
VncInput (const Params *p)
virtual void setFrameBuffer (const FrameBuffer *rfb)
Set the address of the frame buffer we are going to show.
void setKeyboard (VncKeyboard *_keyboard)
Set up the device that would like to receive notifications when keys are pressed in the vnc client keyboard.
void setMouse (VncMouse *_mouse)
Setup the device that would like to receive notifications when mouse movements or button presses are received from the vnc client.
uint16_t videoWidth () const
What is the width of the screen we're displaying.
uint16_t videoHeight () const
What is the height of the screen we're displaying.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
struct VncServer::ServerInitMsg M5_ATTR_PACKED
struct VncServer::FrameBufferUpdate M5_ATTR_PACKED
struct VncServer::FrameBufferRect M5_ATTR_PACKED
struct VncServer::ServerCutText M5_ATTR_PACKED
Public Attributes inherited from VncInput
struct VncInput::PixelFormat M5_ATTR_PACKED
struct VncInput::PixelFormatMessage M5_ATTR_PACKED
struct VncInput::PixelEncodingsMessage M5_ATTR_PACKED
struct VncInput::FrameBufferUpdateReq M5_ATTR_PACKED
struct VncInput::KeyEventMessage M5_ATTR_PACKED
struct VncInput::PointerEventMessage M5_ATTR_PACKED
struct VncInput::ClientCutTextMessage M5_ATTR_PACKED
Static Public Attributes
static const uint32_t AuthInvalid = 0
Authentication modes.
static const uint32_t AuthNone = 1
static const uint32_t VncOK = 0
Error conditions.
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions
void listen (int port)
void accept ()
void data ()
void detach ()
void sendError (const char *error_msg)
vnc client Interface
bool read (uint8_t *buf, size_t len)
Read some data from the client.
bool read1 (uint8_t *buf, size_t len)
Read len -1 bytes from the client into the buffer provided + 1 assert that we read enough bytes.
template<typename T >
bool read (T *val)
Templated version of the read function above to read simple data to the client.
bool write (const uint8_t *buf, size_t len)
Write a buffer to the client.
template<typename T >
bool write (T *val)
Templated version of the write function above to write simple data to the client.
bool write (const char *str)
Send a string to the client.
void checkProtocolVersion ()
Check the client's protocol verion for compatibility and send the security types we support.
void checkSecurity ()
Check that the security exchange was successful.
void sendServerInit ()
Send client our idea about what the frame buffer looks like.
void sendError (std::string error_msg)
Send an error message to the client when something goes wrong.
void sendFrameBufferUpdate ()
Send a updated frame buffer to the client.
void setPixelFormat ()
Receive pixel foramt message from client and process it.
void setEncodings ()
Receive encodings message from client and process it.
void requestFbUpdate ()
Receive message from client asking for updated frame buffer.
void recvKeyboardInput ()
Receive message from client providing new keyboard input.
void recvPointerInput ()
Recv message from client providing new mouse movement or button click.
void recvCutText ()
Receive message from client that there is text in it's paste buffer.
void sendFrameBufferResized ()
Tell the client that the frame buffer resized.
Protected Member Functions inherited from VncInput
void captureFrameBuffer ()
Captures the current frame buffer to a file.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
ListenEvent * listenEvent
DataEvent * dataEvent
int number
int dataFd
ListenSocket listener
ConnectionState curState
The rfb prototol state the connection is in.
bool sendUpdate
An update needs to be sent to the client.
PixelFormat pixelFormat
The one and only pixel format we support.
bool supportsRawEnc
If the vnc client supports receiving raw data.
bool supportsResizeEnc
If the vnc client supports the desktop resize command.
Protected Attributes inherited from VncInput
VncKeyboard * keyboard
The device to notify when we get key events.
VncMouse * mouse
The device to notify when we get mouse events.
const FrameBuffer * fb
pointer to the actual data that is stored in the frame buffer device
uint16_t _videoWidth
the width of the frame buffer we are sending to the client
uint16_t _videoHeight
the height of the frame buffer we are sending to the client
bool captureEnabled
Flag indicating whether to capture snapshots of frame buffer or not.
int captureCurrentFrame
Current frame number being captured to a file.
OutputDirectory * captureOutputDirectory
Directory to store captured frames to.
uint64_t captureLastHash
Computed hash of the last captured frame.
std::unique_ptr< ImgWriter > captureImage
Cached ImgWriter object for writing out frame buffers to file.
Enums::ImageFormat imgFormat
image format
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const PixelConverter pixelConverter
Friends
class ListenEvent
class DataEvent
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Definition at line 61 of file vncserver.hh.
Member Typedef Documentation
Params
typedef VncServerParams VncServer::Params
Definition at line 182 of file vncserver.hh.
Constructor & Destructor Documentation
VncServer()
VncServer::VncServer (const Params * p)
VncServer.
Definition at line 121 of file vncserver.cc.
References VncInput::PixelFormat::bigendian, BigEndianByteOrder, VncInput::PixelFormat::bluemax, VncInput::PixelFormat::blueshift, VncInput::PixelFormat::bpp, PixelConverter::byte_order, PixelConverter::ch_b, PixelConverter::ch_g, PixelConverter::ch_r, curState, VncInput::PixelFormat::depth, PixelConverter::depth, DPRINTF, VncInput::PixelFormat::greenmax, VncInput::PixelFormat::greenshift, PixelConverter::length, listen(), PixelConverter::Channel::mask, PixelConverter::Channel::offset, pixelConverter, pixelFormat, VncInput::PixelFormat::redmax, VncInput::PixelFormat::redshift, VncInput::PixelFormat::truecolor, and WaitForProtocolVersion.
Referenced by frameBufferResized().
~VncServer()
VncServer::~VncServer ()
Definition at line 148 of file vncserver.cc.
References dataEvent, dataFd, and listenEvent.
Member Function Documentation
accept()
void VncServer::accept () protected
Definition at line 186 of file vncserver.cc.
References ListenSocket::accept(), atomic_write(), DataEvent, dataEvent, dataFd, EventManager::eventQueue(), ArmISA::fd, inform, ListenSocket::islistening(), listener, SimObject::name(), panic, pollQueue, PollQueue::schedule(), vncVersion(), warn, and write().
Referenced by VncServer::ListenEvent::process().
checkProtocolVersion()
void VncServer::checkProtocolVersion () protected
Check the client's protocol verion for compatibility and send the security types we support.
Definition at line 380 of file vncserver.cc.
References AuthInvalid, AuthNone, curState, detach(), DPRINTF, htobe(), ArmISA::len, M5_VAR_USED, read(), sendError(), WaitForProtocolVersion, WaitForSecurityResponse, warn, and write().
Referenced by data().
checkSecurity()
void VncServer::checkSecurity () protected
Check that the security exchange was successful.
Definition at line 432 of file vncserver.cc.
References AuthNone, curState, DPRINTF, htobe(), read(), sendError(), VncOK, WaitForClientInit, WaitForSecurityResponse, warn, and write().
Referenced by data().
data()
void VncServer::data () protected
Definition at line 223 of file vncserver.cc.
References checkProtocolVersion(), checkSecurity(), VncInput::ClientCutText, VncInput::ClientFrameBufferUpdate, VncInput::ClientKeyEvent, VncInput::ClientPointerEvent, VncInput::ClientSetEncodings, VncInput::ClientSetPixelFormat, curState, detach(), DPRINTF, NormalPhase, panic, read(), recvCutText(), recvKeyboardInput(), recvPointerInput(), requestFbUpdate(), sendServerInit(), setEncodings(), setPixelFormat(), WaitForClientInit, WaitForProtocolVersion, WaitForSecurityResponse, and warn.
Referenced by VncServer::DataEvent::process().
detach()
void VncServer::detach () protected
Definition at line 351 of file vncserver.cc.
References curState, dataEvent, dataFd, DPRINTF, inform, number, pollQueue, PollEvent::queued(), PollQueue::remove(), and WaitForProtocolVersion.
Referenced by checkProtocolVersion(), data(), frameBufferResized(), VncServer::DataEvent::process(), read(), setEncodings(), setPixelFormat(), and write().
frameBufferResized()
void VncServer::frameBufferResized () override virtual
Reimplemented from VncInput.
Definition at line 725 of file vncserver.cc.
References curState, dataFd, detach(), NormalPhase, sendFrameBufferResized(), supportsResizeEnc, and VncServer().
listen()
void VncServer::listen (int port) protected
Definition at line 163 of file vncserver.cc.
References ListenSocket::allDisabled(), ccprintf(), DPRINTF, ListenSocket::getfd(), ListenSocket::listen(), listener, ListenEvent, listenEvent, SimObject::name(), pollQueue, PollQueue::schedule(), and warn_once.
Referenced by VncServer().
read() [1/2]
bool VncServer::read (uint8_t * buf, size_t len) protected
Read some data from the client.
Parameters
buf the data to read
len the amount of data to read
Returns
whether the read was successful
Definition at line 284 of file vncserver.cc.
References dataFd, detach(), DPRINTF, and panic.
Referenced by checkProtocolVersion(), checkSecurity(), data(), read(), read1(), recvCutText(), and setEncodings().
read() [2/2]
template<typename T > bool VncServer::read (T * val) protected
Templated version of the read function above to read simple data to the client.
Parameters
val data to recv from the client
Definition at line 313 of file vncserver.cc.
References read().
read1()
bool VncServer::read1 (uint8_t * buf, size_t len) protected
Read len -1 bytes from the client into the buffer provided + 1 assert that we read enough bytes.
This function exists to handle reading all of the protocol structs above when we've already read the first byte which describes which one we're reading
Parameters
buf the address of the buffer to add one to and read data into
len the amount of data + 1 to read
Returns
whether the read was successful.
Definition at line 305 of file vncserver.cc.
References read().
Referenced by recvCutText(), recvKeyboardInput(), recvPointerInput(), requestFbUpdate(), setEncodings(), and setPixelFormat().
recvCutText()
void VncServer::recvCutText () protected
Receive message from client that there is text in it's paste buffer.
This is a no-op at the moment, but perhaps we would want to be able to paste it at some point.
Definition at line 606 of file vncserver.cc.
References betoh(), DPRINTF, read(), and read1().
Referenced by data().
recvKeyboardInput()
void VncServer::recvKeyboardInput () protected
Receive message from client providing new keyboard input.
Definition at line 572 of file vncserver.cc.
References betoh(), DPRINTF, VncInput::KeyEventMessage::key, VncInput::keyboard, VncKeyboard::keyPress(), and read1().
Referenced by data().
recvPointerInput()
void VncServer::recvPointerInput () protected
Recv message from client providing new mouse movement or button click.
Definition at line 588 of file vncserver.cc.
References betoh(), DPRINTF, VncInput::mouse, VncMouse::mouseAt(), read1(), and VncInput::PointerEventMessage::x.
Referenced by data().
requestFbUpdate()
void VncServer::requestFbUpdate () protected
Receive message from client asking for updated frame buffer.
Definition at line 552 of file vncserver.cc.
References betoh(), DPRINTF, read1(), sendFrameBufferUpdate(), and VncInput::FrameBufferUpdateReq::x.
Referenced by data().
sendError() [1/2]
void VncServer::sendError (const char * error_msg) protected
vnc client Interface
Send an error message to the client
Parameters
error_msg text to send describing the error
Definition at line 371 of file vncserver.cc.
References ArmISA::len, and write().
Referenced by checkProtocolVersion(), and checkSecurity().
sendError() [2/2]
void VncServer::sendError (std::string error_msg) protected
Send an error message to the client when something goes wrong.
Parameters
error_msg error to send
sendFrameBufferResized()
void VncServer::sendFrameBufferResized () protected
Tell the client that the frame buffer resized.
This happens when the simulated system changes video modes (E.g. X11 starts).
Definition at line 683 of file vncserver.cc.
References curState, dataFd, DPRINTF, VncServer::FrameBufferRect::encoding, EncodingDesktopSize, VncInput::fb, VncServer::FrameBufferRect::height, htobe(), NormalPhase, VncServer::FrameBufferUpdate::num_rects, ServerFrameBufferUpdate, VncServer::FrameBufferUpdate::type, VncInput::videoHeight(), VncInput::videoWidth(), VncServer::FrameBufferRect::width, write(), VncServer::FrameBufferRect::x, and VncServer::FrameBufferRect::y.
Referenced by frameBufferResized().
sendFrameBufferUpdate()
void VncServer::sendFrameBufferUpdate () protected
Send a updated frame buffer to the client.
Todo:
this doesn't do anything smart and just sends the entire image
Definition at line 630 of file vncserver.cc.
References curState, dataFd, DPRINTF, VncServer::FrameBufferRect::encoding, EncodingRaw, VncInput::fb, PixelConverter::fromPixel(), FrameBuffer::height(), VncServer::FrameBufferRect::height, htobe(), PixelConverter::length, NormalPhase, VncServer::FrameBufferUpdate::num_rects, FrameBuffer::pixel(), pixelConverter, sendUpdate, ServerFrameBufferUpdate, VncServer::FrameBufferUpdate::type, VncInput::videoHeight(), VncInput::videoWidth(), FrameBuffer::width(), VncServer::FrameBufferRect::width, write(), X86ISA::x, VncServer::FrameBufferRect::x, and VncServer::FrameBufferRect::y.
Referenced by requestFbUpdate(), and setDirty().
sendServerInit()
void VncServer::sendServerInit () protected
Send client our idea about what the frame buffer looks like.
Definition at line 454 of file vncserver.cc.
References VncInput::PixelFormat::bigendian, VncInput::PixelFormat::bluemax, VncInput::PixelFormat::blueshift, VncInput::PixelFormat::bpp, curState, VncInput::PixelFormat::depth, DPRINTF, VncServer::ServerInitMsg::fbHeight, VncServer::ServerInitMsg::fbWidth, VncInput::PixelFormat::greenmax, VncInput::PixelFormat::greenshift, htobe(), VncServer::ServerInitMsg::name, VncServer::ServerInitMsg::namelen, NormalPhase, VncInput::PixelFormat::padding, pixelFormat, VncServer::ServerInitMsg::px, VncInput::PixelFormat::redmax, VncInput::PixelFormat::redshift, VncInput::PixelFormat::truecolor, VncInput::videoHeight(), VncInput::videoWidth(), and write().
Referenced by data().
setDirty()
void VncServer::setDirty () override virtual
The frame buffer uses this call to notify the vnc server that the frame buffer has been updated and a new image needs to be sent to the client.
Reimplemented from VncInput.
Definition at line 716 of file vncserver.cc.
References sendFrameBufferUpdate(), sendUpdate, and VncInput::setDirty().
setEncodings()
void VncServer::setEncodings () protected
Receive encodings message from client and process it.
Definition at line 516 of file vncserver.cc.
References betoh(), detach(), DPRINTF, ArmISA::encoding, EncodingDesktopSize, EncodingRaw, VncInput::PixelEncodingsMessage::num_encodings, read(), read1(), supportsRawEnc, supportsResizeEnc, warn, and X86ISA::x.
Referenced by data().
setPixelFormat()
void VncServer::setPixelFormat () protected
Receive pixel foramt message from client and process it.
Definition at line 484 of file vncserver.cc.
References betoh(), VncInput::PixelFormat::bigendian, VncInput::PixelFormat::bluemax, VncInput::PixelFormat::blueshift, VncInput::PixelFormat::bpp, VncInput::PixelFormat::depth, detach(), DPRINTF, VncInput::PixelFormat::greenmax, VncInput::PixelFormat::greenshift, pixelFormat, read1(), VncInput::PixelFormat::redmax, VncInput::PixelFormat::redshift, VncInput::PixelFormat::truecolor, and warn.
Referenced by data().
write() [1/3]
bool VncServer::write (const uint8_t * buf, size_t len) protected
Write a buffer to the client.
Parameters
buf buffer to send
len length of the buffer
Returns
whether the write was successful
Definition at line 320 of file vncserver.cc.
References atomic_write(), dataFd, detach(), DPRINTF, and panic.
Referenced by accept(), checkProtocolVersion(), checkSecurity(), sendError(), sendFrameBufferResized(), sendFrameBufferUpdate(), sendServerInit(), and write().
write() [2/3]
template<typename T > bool VncServer::write (T * val) protected
Templated version of the write function above to write simple data to the client.
Parameters
val data to send to the client
Definition at line 338 of file vncserver.cc.
References write().
write() [3/3]
bool VncServer::write (const char * str) protected
Send a string to the client.
Parameters
str string to transmit
Definition at line 344 of file vncserver.cc.
References write().
Friends And Related Function Documentation
DataEvent
friend class DataEvent friend
Definition at line 168 of file vncserver.hh.
Referenced by accept().
ListenEvent
friend class ListenEvent friend
Definition at line 154 of file vncserver.hh.
Referenced by listen().
Member Data Documentation
curState
ConnectionState VncServer::curState protected
The rfb prototol state the connection is in.
Definition at line 190 of file vncserver.hh.
Referenced by checkProtocolVersion(), checkSecurity(), data(), detach(), frameBufferResized(), sendFrameBufferResized(), sendFrameBufferUpdate(), sendServerInit(), and VncServer().
dataEvent
DataEvent* VncServer::dataEvent protected
Definition at line 169 of file vncserver.hh.
Referenced by accept(), detach(), and ~VncServer().
dataFd
int VncServer::dataFd protected
Definition at line 172 of file vncserver.hh.
Referenced by accept(), detach(), frameBufferResized(), read(), sendFrameBufferResized(), sendFrameBufferUpdate(), write(), and ~VncServer().
listener
ListenSocket VncServer::listener protected
Definition at line 174 of file vncserver.hh.
Referenced by accept(), and listen().
listenEvent
ListenEvent* VncServer::listenEvent protected
Definition at line 155 of file vncserver.hh.
Referenced by listen(), and ~VncServer().
number
int VncServer::number protected
Definition at line 171 of file vncserver.hh.
Referenced by detach().
pixelConverter
const PixelConverter VncServer::pixelConverter static protected
Definition at line 306 of file vncserver.hh.
Referenced by sendFrameBufferUpdate(), and VncServer().
pixelFormat
PixelFormat VncServer::pixelFormat protected
The one and only pixel format we support.
Definition at line 197 of file vncserver.hh.
Referenced by sendServerInit(), setPixelFormat(), and VncServer().
sendUpdate
bool VncServer::sendUpdate protected
An update needs to be sent to the client.
Without doing this the client will constantly request data that is pointless
Definition at line 194 of file vncserver.hh.
Referenced by sendFrameBufferUpdate(), and setDirty().
supportsRawEnc
bool VncServer::supportsRawEnc protected
If the vnc client supports receiving raw data.
It always should
Definition at line 200 of file vncserver.hh.
Referenced by setEncodings().
supportsResizeEnc
bool VncServer::supportsResizeEnc protected
If the vnc client supports the desktop resize command.
Definition at line 203 of file vncserver.hh.
Referenced by frameBufferResized(), and setEncodings().
The documentation for this class was generated from the following files:
base/vnc/vncserver.hh
base/vnc/vncserver.cc