gem5: PollEvent Class Reference
PollEvent Class Reference abstract
#include <pollevent.hh>
Public Member Functions
PollEvent (int fd, int event)
virtual ~PollEvent ()
void disable ()
void enable ()
virtual void process (int revent)=0
bool queued ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Protected Attributes
pollfd pfd
PollQueue * queue
bool enabled
Friends
class PollQueue
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 43 of file pollevent.hh.
Constructor & Destructor Documentation
PollEvent()
PollEvent::PollEvent (int fd, int event)
Definition at line 61 of file pollevent.cc.
References pfd.
~PollEvent()
PollEvent::~PollEvent () virtual
Definition at line 69 of file pollevent.cc.
References queue, and PollQueue::remove().
Member Function Documentation
disable()
void PollEvent::disable ()
Definition at line 76 of file pollevent.cc.
References PollQueue::copy(), enabled, and queue.
enable()
void PollEvent::enable ()
Definition at line 86 of file pollevent.cc.
References PollQueue::copy(), enabled, and queue.
process()
virtual void PollEvent::process (int revent) pure virtual
Implemented in VirtIO9PSocket::SocketDataEvent, VirtIO9PDiod::DiodDataEvent, TapListener::Event, VncServer::DataEvent, BaseRemoteGDB::SocketEvent< F >, VncServer::ListenEvent, Terminal::DataEvent, TapEvent, and Terminal::ListenEvent.
queued()
bool PollEvent::queued () inline
Definition at line 61 of file pollevent.hh.
References serialize(), and unserialize().
Referenced by VncServer::detach(), and EtherTapBase::unserialize().
serialize()
void PollEvent::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 96 of file pollevent.cc.
References enabled, pfd, and SERIALIZE_SCALAR.
Referenced by queued().
unserialize()
void PollEvent::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 104 of file pollevent.cc.
References enabled, pfd, and UNSERIALIZE_SCALAR.
Referenced by queued().
Friends And Related Function Documentation
PollQueue
friend class PollQueue friend
Definition at line 46 of file pollevent.hh.
Member Data Documentation
enabled
bool PollEvent::enabled protected
Definition at line 51 of file pollevent.hh.
Referenced by disable(), enable(), serialize(), and unserialize().
pfd
pollfd PollEvent::pfd protected
Definition at line 49 of file pollevent.hh.
Referenced by PollEvent(), PollQueue::schedule(), serialize(), and unserialize().
queue
PollQueue* PollEvent::queue protected
Definition at line 50 of file pollevent.hh.
Referenced by disable(), enable(), PollQueue::schedule(), and ~PollEvent().
The documentation for this class was generated from the following files:
base/pollevent.hh
base/pollevent.cc