gem5: PS2TouchKit Class Reference
PS2TouchKit Class Reference
#include <touchkit.hh>
Public Member Functions
PS2TouchKit (const PS2TouchKitParams *p)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void mouseAt (uint16_t x, uint16_t y, uint8_t buttons) override
called whenever the mouse moves or it's button state changes buttons is a simple mask with each button (0-8) corresponding to a bit position in the byte with 1 being down and 0 being up
Public Member Functions inherited from PS2Device
PS2Device (const PS2DeviceParams *p)
void hostRegDataAvailable (const std::function< void()> &c)
Register a data available callback into the PS/2 interface.
bool hostDataAvailable () const
Check if there is pending data from the PS/2 device.
uint8_t hostRead ()
Read a character from the device.
void hostWrite (uint8_t c)
Transmit a character from the host interface to the device.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
enum PS2Commands { TpReadId = 0xE1, TouchKitDiag = 0x0A }
enum TKCommands { TouchKitActive = 'A', TouchKitFWRev = 'D', TouchKitCtrlType = 'E' }
Protected Member Functions
bool recv (const std::vector< uint8_t > &data) override
Data received from host.
bool recvTouchKit (const std::vector< uint8_t > &data)
void sendTouchKit (const uint8_t *data, size_t size)
void sendTouchKit (uint8_t data)
Protected Member Functions inherited from PS2Device
void send (const uint8_t *data, size_t size)
Send data from a PS/2 device to a host.
void send (const std::vector< uint8_t > &data)
void send (uint8_t data)
Send a byte of data from a PS/2 device to a host.
void sendAck ()
Send an ACK byte to the host.
size_t sendPending () const
Output buffer size.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
VncInput *const vnc
The vnc server we're connected to (if any)
bool enabled
Is the device enabled?
bool touchKitEnabled
Has the driver enabled TouchKit mode? The model suppresses touch event generation until this is true.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 48 of file touchkit.hh.
Member Enumeration Documentation
PS2Commands
enum PS2TouchKit::PS2Commands protected
Enumerator
TpReadId
TouchKitDiag
Definition at line 51 of file touchkit.hh.
TKCommands
enum PS2TouchKit::TKCommands protected
Enumerator
TouchKitActive
TouchKitFWRev
TouchKitCtrlType
Definition at line 56 of file touchkit.hh.
Constructor & Destructor Documentation
PS2TouchKit()
PS2TouchKit::PS2TouchKit (const PS2TouchKitParams * p)
Definition at line 52 of file touchkit.cc.
References VncInput::setMouse(), and vnc.
Referenced by mouseAt().
Member Function Documentation
mouseAt()
void PS2TouchKit::mouseAt (uint16_t x, uint16_t y, uint8_t buttons) override virtual
called whenever the mouse moves or it's button state changes buttons is a simple mask with each button (0-8) corresponding to a bit position in the byte with 1 being down and 0 being up
Parameters
x the x position of the mouse
y the y position of the mouse
buttos the button state as described above
Implements VncMouse.
Definition at line 189 of file touchkit.cc.
References enabled, PS2TouchKit(), PS2Device::send(), PS2Device::sendPending(), touchKitEnabled, VncInput::videoHeight(), VncInput::videoWidth(), and vnc.
recv()
bool PS2TouchKit::recv (const std::vector< uint8_t > & data) override protected virtual
Data received from host.
Data sent to the device is buffered one byte at a time. Each time a byte is added, this function is called and passed the current buffer. It should return true if it has consumed the data and the buffer can be cleared, or false if more data is needed to process the current command.
Parameters
data Pending input data (at least one byte)
Returns
false if more data is needed to process the current command, true otherwise.
Implements PS2Device.
Definition at line 80 of file touchkit.cc.
References Ps2::DefaultsAndDisable, Ps2::Disable, DPRINTF, Ps2::Enable, enabled, Ps2::Mouse::GetStatus, Ps2::Mouse::ID, panic, Ps2::ReadID, recvTouchKit(), Ps2::Reset, Ps2::Mouse::SampleRate, Ps2::Mouse::Scale1to1, Ps2::Mouse::Scale2to1, Ps2::SelfTestPass, PS2Device::send(), PS2Device::sendAck(), Ps2::Mouse::SetResolution, TouchKitDiag, touchKitEnabled, and TpReadId.
recvTouchKit()
bool PS2TouchKit::recvTouchKit (const std::vector< uint8_t > & data) protected
Definition at line 149 of file touchkit.cc.
References ArmISA::len, panic, PS2Device::sendAck(), sendTouchKit(), TouchKitActive, TouchKitDiag, touchKitEnabled, and warn_if.
Referenced by recv().
sendTouchKit() [1/2]
void PS2TouchKit::sendTouchKit (const uint8_t * data, size_t size) protected
Definition at line 179 of file touchkit.cc.
References ArmISA::i, PS2Device::send(), and TouchKitDiag.
Referenced by recvTouchKit().
sendTouchKit() [2/2]
void PS2TouchKit::sendTouchKit (uint8_t data) inline protected
Definition at line 77 of file touchkit.hh.
References sendTouchKit().
Referenced by sendTouchKit().
serialize()
void PS2TouchKit::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from PS2Device.
Definition at line 62 of file touchkit.cc.
References enabled, PS2Device::serialize(), SERIALIZE_SCALAR, and touchKitEnabled.
unserialize()
void PS2TouchKit::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from PS2Device.
Definition at line 71 of file touchkit.cc.
References enabled, touchKitEnabled, PS2Device::unserialize(), and UNSERIALIZE_SCALAR.
Member Data Documentation
enabled
bool PS2TouchKit::enabled protected
Is the device enabled?
Definition at line 83 of file touchkit.hh.
Referenced by mouseAt(), recv(), serialize(), and unserialize().
touchKitEnabled
bool PS2TouchKit::touchKitEnabled protected
Has the driver enabled TouchKit mode? The model suppresses touch event generation until this is true.
Definition at line 89 of file touchkit.hh.
Referenced by mouseAt(), recv(), recvTouchKit(), serialize(), and unserialize().
vnc
VncInput* const PS2TouchKit::vnc protected
The vnc server we're connected to (if any)
Definition at line 80 of file touchkit.hh.
Referenced by mouseAt(), and PS2TouchKit().
The documentation for this class was generated from the following files:
dev/ps2/touchkit.hh
dev/ps2/touchkit.cc