gem5: VirtQueue Class Reference
VirtQueue Class Reference
Base wrapper around a virtqueue.
#include <base.hh>
Classes
class VirtRing
VirtIO ring buffer wrapper.
Public Member Functions
virtual ~VirtQueue ()
Checkpointing Interface
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Low-level Device Interface
void setAddress (Addr address)
Set the base address of this queue.
Addr getAddress () const
Get the guest physical address of this queue.
uint16_t getSize () const
Get the number of descriptors available in this queue.
VirtDescriptor * getDescriptor (VirtDescriptor::Index index)
Get a pointer to a specific descriptor in the queue.
Device Model Interfaces
VirtDescriptor * consumeDescriptor ()
Get an incoming descriptor chain from the queue.
void produceDescriptor (VirtDescriptor *desc, uint32_t len)
Send a descriptor chain to the guest.
Device Model Callbacks
virtual void onNotify ()
Notify queue of pending events.
virtual void onNotifyDescriptor (VirtDescriptor *desc)
Notify queue of pending incoming descriptor.
Debug interfaces
void dump () const
Dump the contents of a queue.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Static Public Attributes
static const Addr ALIGN_BITS = 12
Page size used by VirtIO. It's hard-coded to 4096 bytes in the spec for historical reasons.
static const Addr ALIGN_SIZE = 1 << ALIGN_BITS
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions
VirtQueue (PortProxy &proxy, ByteOrder bo, uint16_t size)
Instantiate a new virtqueue.
Protected Attributes
ByteOrder byteOrder
Byte order in this queue.
Private Member Functions
VirtQueue ()
Private Attributes
const uint16_t _size
Queue size in terms of number of descriptors.
Addr _address
Base address of the queue.
PortProxy & memProxy
Guest physical memory proxy.
VirtRing< VirtDescriptor::Index > avail
Ring of available (incoming) descriptors.
VirtRing< struct vring_used_elem > used
Ring of used (outgoing) descriptors.
uint16_t _last_avail
Offset of last consumed descriptor in the VirtQueue::avail ring.
std::vector< VirtDescriptor > descriptors
Vector of pre-created descriptors indexed by their index into the queue.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Detailed Description
Base wrapper around a virtqueue.
VirtIO device models typically need to extend this class to implement their own device queues.
Note
Queues must be registered with VirtIODeviceBase::registerQueue() to be active.
Definition at line 293 of file base.hh.
Constructor & Destructor Documentation
~VirtQueue()
virtual VirtQueue::~VirtQueue () inline virtual
Definition at line 295 of file base.hh.
References serialize(), and unserialize().
VirtQueue() [1/2]
VirtQueue::VirtQueue (PortProxy & proxy, ByteOrder bo, uint16_t size) protected
Instantiate a new virtqueue.
Instantiate a virtqueue with a fixed size. The size is specified in descriptors which are defined as 4096 bytes each.
Parameters
proxy Proxy to the guest physical memory.
size Size in descriptors/pages.
Definition at line 229 of file base.cc.
References _size, descriptors, and ArmISA::i.
VirtQueue() [2/2]
VirtQueue::VirtQueue () private
Member Function Documentation
consumeDescriptor()
VirtDescriptor * VirtQueue::consumeDescriptor ()
Get an incoming descriptor chain from the queue.
Returns
Pointer to descriptor on success, NULL if no pending descriptors are available.
Definition at line 273 of file base.cc.
References _last_avail, avail, ArmISA::d, descriptors, DPRINTF, VirtQueue::VirtRing< T >::header, MipsISA::index, VirtQueue::VirtRing< T >::read(), VirtQueue::VirtRing< T >::ring, VirtDescriptor::updateChain(), and used.
Referenced by onNotify().
dump()
void VirtQueue::dump () const
Dump the contents of a queue.
Definition at line 306 of file base.cc.
References ArmISA::d, descriptors, and DTRACE.
getAddress()
Addr VirtQueue::getAddress () const inline
Get the guest physical address of this queue.
Returns
Physical address in guest where this queue resides.
Definition at line 317 of file base.hh.
Referenced by VirtDescriptor::update().
getDescriptor()
VirtDescriptor* VirtQueue::getDescriptor (VirtDescriptor::Index index) inline
Get a pointer to a specific descriptor in the queue.
Note
This interfaces is normally only used by VirtDescriptor to follow descriptor chains. Device models typically don't need to use it.
Returns
Pointer to a VirtDescriptor.
Definition at line 335 of file base.hh.
References VirtDescriptor::desc, VirtDescriptor::index(), and ArmISA::len.
Referenced by VirtDescriptor::next().
getSize()
uint16_t VirtQueue::getSize () const inline
Get the number of descriptors available in this queue.
Returns
Size of queue in descriptors.
Definition at line 324 of file base.hh.
onNotify()
void VirtQueue::onNotify () virtual
Notify queue of pending events.
This method is called by VirtIODeviceBase::onNotify() to notify the device model of pending data in a virtqueue. The default implementation of this method iterates over the available descriptor chains and calls onNotifyDescriptor() for every new incoming chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented in VirtIOConsole::TermRecvQueue.
Definition at line 316 of file base.cc.
References consumeDescriptor(), ArmISA::d, DPRINTF, and onNotifyDescriptor().
onNotifyDescriptor()
virtual void VirtQueue::onNotifyDescriptor (VirtDescriptor * desc) inline virtual
Notify queue of pending incoming descriptor.
This method is called by the default implementation of onNotify() to notify the device model of pending data in a descriptor chain.
Device models should normally overload one of onNotify() and onNotifyDescriptor().
Reimplemented in VirtIOBlock::RequestQueue, VirtIO9PBase::FSQueue, and VirtIOConsole::TermTransQueue.
Definition at line 397 of file base.hh.
References VirtDescriptor::dump().
Referenced by onNotify().
produceDescriptor()
void VirtQueue::produceDescriptor (VirtDescriptor * desc, uint32_t len)
Send a descriptor chain to the guest.
This method posts a descriptor chain to the guest after a device model has finished processing it. The device model typically needs to call VirtIODeviceBase::kick() to deliver notify tell the guest that the queue has been updated.
Note
The desc parameter must refer to the first descriptor in a chain that has been retrieved using consumeDescriptor().
The len parameter specified the amount of data produced by the device model. It seems to be ignored by Linux and it is not well defined.
Parameters
desc Start of descriptor chain.
len Length of the produced data.
Definition at line 292 of file base.cc.
References DPRINTF, ArmISA::e, VirtQueue::VirtRing< T >::header, VirtDescriptor::index(), ArmISA::len, VirtQueue::VirtRing< T >::readHeader(), VirtQueue::VirtRing< T >::ring, used, and VirtQueue::VirtRing< T >::write().
Referenced by VirtIO9PBase::sendRMsg().
serialize()
void VirtQueue::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 240 of file base.cc.
References _address, _last_avail, and SERIALIZE_SCALAR.
setAddress()
void VirtQueue::setAddress (Addr address)
Set the base address of this queue.
Parameters
address Guest physical base address of the queue.
Definition at line 260 of file base.cc.
References _address, _size, ALIGN_SIZE, avail, VirtQueue::VirtRing< T >::setAddress(), and used.
Referenced by VirtIODeviceBase::setQueueAddress(), and unserialize().
unserialize()
void VirtQueue::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 247 of file base.cc.
References _last_avail, paramIn(), setAddress(), and UNSERIALIZE_SCALAR.
Member Data Documentation
_address
Addr VirtQueue::_address private
Base address of the queue.
Definition at line 437 of file base.hh.
Referenced by serialize(), and setAddress().
_last_avail
uint16_t VirtQueue::_last_avail private
Offset of last consumed descriptor in the VirtQueue::avail ring.
Definition at line 543 of file base.hh.
Referenced by consumeDescriptor(), serialize(), and unserialize().
_size
const uint16_t VirtQueue::_size private
Queue size in terms of number of descriptors.
Definition at line 435 of file base.hh.
Referenced by setAddress(), and VirtQueue().
ALIGN_BITS
const Addr VirtQueue::ALIGN_BITS = 12 static
Page size used by VirtIO. It's hard-coded to 4096 bytes in the spec for historical reasons.
Definition at line 412 of file base.hh.
Referenced by VirtIODeviceBase::getQueueAddress().
ALIGN_SIZE
const Addr VirtQueue::ALIGN_SIZE = 1 << ALIGN_BITS static
Definition at line 413 of file base.hh.
Referenced by MmioVirtIO::read(), setAddress(), VirtIODeviceBase::setQueueAddress(), and MmioVirtIO::write().
avail
VirtRing<VirtDescriptor::Index> VirtQueue::avail private
Ring of available (incoming) descriptors.
Definition at line 537 of file base.hh.
Referenced by consumeDescriptor(), and setAddress().
byteOrder
ByteOrder VirtQueue::byteOrder protected
Byte order in this queue.
Definition at line 429 of file base.hh.
descriptors
std::vector<VirtDescriptor> VirtQueue::descriptors private
Vector of pre-created descriptors indexed by their index into the queue.
Definition at line 547 of file base.hh.
Referenced by consumeDescriptor(), dump(), and VirtQueue().
memProxy
PortProxy& VirtQueue::memProxy private
Guest physical memory proxy.
Definition at line 439 of file base.hh.
used
VirtRing<struct vring_used_elem> VirtQueue::used private
Ring of used (outgoing) descriptors.
Definition at line 539 of file base.hh.
Referenced by consumeDescriptor(), produceDescriptor(), and setAddress().
The documentation for this class was generated from the following files:
dev/virtio/base.hh
dev/virtio/base.cc