gem5: AccessTraceForAddress Class Reference
AccessTraceForAddress Class Reference
#include <AccessTraceForAddress.hh>
Public Member Functions
AccessTraceForAddress ()
~AccessTraceForAddress ()
void setAddress (Addr addr)
void update (RubyRequestType type, RubyAccessMode access_mode, NodeID cpu, bool sharing_miss)
int getTotal () const
int getSharing () const
int getTouchedBy () const
Addr getAddress () const
void addSample (int value)
void print (std::ostream &out) const
Static Public Member Functions
static bool less_equal (const AccessTraceForAddress *n1, const AccessTraceForAddress *n2)
Private Attributes
Addr m_addr
uint64_t m_loads
uint64_t m_stores
uint64_t m_atomics
uint64_t m_total
uint64_t m_user
uint64_t m_sharing
Set m_touched_by
Histogram * m_histogram_ptr
Detailed Description
Definition at line 41 of file AccessTraceForAddress.hh.
Constructor & Destructor Documentation
AccessTraceForAddress()
AccessTraceForAddress::AccessTraceForAddress () inline
Definition at line 44 of file AccessTraceForAddress.hh.
References ~AccessTraceForAddress().
~AccessTraceForAddress()
AccessTraceForAddress::~AccessTraceForAddress ()
Definition at line 33 of file AccessTraceForAddress.cc.
References m_histogram_ptr.
Referenced by AccessTraceForAddress().
Member Function Documentation
addSample()
void AccessTraceForAddress::addSample (int value)
Definition at line 98 of file AccessTraceForAddress.cc.
References Histogram::add(), m_histogram_ptr, and m_total.
Referenced by getAddress(), and AddressProfiler::profileRetry().
getAddress()
Addr AccessTraceForAddress::getAddress () const inline
Definition at line 56 of file AccessTraceForAddress.hh.
References addSample(), m_addr, and print().
getSharing()
int AccessTraceForAddress::getSharing () const inline
Definition at line 54 of file AccessTraceForAddress.hh.
References m_sharing.
getTotal()
int AccessTraceForAddress::getTotal () const
Definition at line 88 of file AccessTraceForAddress.cc.
References Histogram::getTotal(), m_histogram_ptr, and m_total.
Referenced by less_equal(), printSorted(), and setAddress().
getTouchedBy()
int AccessTraceForAddress::getTouchedBy () const inline
Definition at line 55 of file AccessTraceForAddress.hh.
References Set::count(), and m_touched_by.
Referenced by printSorted().
less_equal()
static bool AccessTraceForAddress::less_equal (const AccessTraceForAddress * n1, const AccessTraceForAddress * n2) inline static
Definition at line 62 of file AccessTraceForAddress.hh.
References getTotal().
Referenced by printSorted().
print()
void AccessTraceForAddress::print (std::ostream & out) const
Definition at line 42 of file AccessTraceForAddress.cc.
References Set::count(), m_addr, m_atomics, m_histogram_ptr, m_loads, m_sharing, m_stores, m_total, m_touched_by, and m_user.
Referenced by getAddress(), and operator<<().
setAddress()
void AccessTraceForAddress::setAddress (Addr addr) inline
Definition at line 50 of file AccessTraceForAddress.hh.
References addr, getTotal(), m_addr, type, and update().
Referenced by lookupTraceForAddress().
update()
void AccessTraceForAddress::update (RubyRequestType type, RubyAccessMode access_mode, NodeID cpu, bool sharing_miss)
Definition at line 62 of file AccessTraceForAddress.cc.
References Set::add(), m_atomics, m_loads, m_sharing, m_stores, m_total, m_touched_by, and m_user.
Referenced by setAddress().
Member Data Documentation
m_addr
Addr AccessTraceForAddress::m_addr private
Definition at line 69 of file AccessTraceForAddress.hh.
Referenced by getAddress(), print(), and setAddress().
m_atomics
uint64_t AccessTraceForAddress::m_atomics private
Definition at line 72 of file AccessTraceForAddress.hh.
Referenced by print(), and update().
m_histogram_ptr
Histogram* AccessTraceForAddress::m_histogram_ptr private
Definition at line 77 of file AccessTraceForAddress.hh.
Referenced by addSample(), getTotal(), print(), and ~AccessTraceForAddress().
m_loads
uint64_t AccessTraceForAddress::m_loads private
Definition at line 70 of file AccessTraceForAddress.hh.
Referenced by print(), and update().
m_sharing
uint64_t AccessTraceForAddress::m_sharing private
Definition at line 75 of file AccessTraceForAddress.hh.
Referenced by getSharing(), print(), and update().
m_stores
uint64_t AccessTraceForAddress::m_stores private
Definition at line 71 of file AccessTraceForAddress.hh.
Referenced by print(), and update().
m_total
uint64_t AccessTraceForAddress::m_total private
Definition at line 73 of file AccessTraceForAddress.hh.
Referenced by addSample(), getTotal(), print(), and update().
m_touched_by
Set AccessTraceForAddress::m_touched_by private
Definition at line 76 of file AccessTraceForAddress.hh.
Referenced by getTouchedBy(), print(), and update().
m_user
uint64_t AccessTraceForAddress::m_user private
Definition at line 74 of file AccessTraceForAddress.hh.
Referenced by print(), and update().
The documentation for this class was generated from the following files:
mem/ruby/profiler/AccessTraceForAddress.hh
mem/ruby/profiler/AccessTraceForAddress.cc