gem5: FUPool::FUIdxQueue Class Reference
FUPool::FUIdxQueue Class Reference
Class that implements a circular queue to hold FU indices.
Public Member Functions
FUIdxQueue ()
Constructs a circular queue of FU indices.
void addFU (int fu_idx)
Adds a FU to the queue.
int getFU ()
Returns the index of the FU at the head of the queue, and changes the index to the next element.
Private Attributes
int idx
Circular queue index.
int size
Size of the queue.
std::vector< int > funcUnitsIdx
Queue of FU indices.
Detailed Description
Class that implements a circular queue to hold FU indices.
The hope is that FUs that have been just used will be moved to the end of the queue by iterating through it, thus leaving free units at the head of the queue.
Definition at line 94 of file fu_pool.hh.
Constructor & Destructor Documentation
FUIdxQueue()
FUPool::FUIdxQueue::FUIdxQueue () inline
Constructs a circular queue of FU indices.
Definition at line 97 of file fu_pool.hh.
References addFU(), and getFU().
Member Function Documentation
addFU()
void FUPool::FUIdxQueue::addFU (int fu_idx) inline
Adds a FU to the queue.
Definition at line 57 of file fu_pool.cc.
Referenced by FUIdxQueue(), and FUPool::FUPool().
getFU()
int FUPool::FUIdxQueue::getFU () inline
Returns the index of the FU at the head of the queue, and changes the index to the next element.
Definition at line 64 of file fu_pool.cc.
Referenced by FUIdxQueue(), and FUPool::getUnit().
Member Data Documentation
funcUnitsIdx
std::vector<int> FUPool::FUIdxQueue::funcUnitsIdx private
Queue of FU indices.
Definition at line 117 of file fu_pool.hh.
idx
int FUPool::FUIdxQueue::idx private
Circular queue index.
Definition at line 111 of file fu_pool.hh.
size
int FUPool::FUIdxQueue::size private
Size of the queue.
Definition at line 114 of file fu_pool.hh.
The documentation for this class was generated from the following files:
cpu/o3/fu_pool.hh
cpu/o3/fu_pool.cc