gem5: sc_dt::sc_unsigned_subref_r Class Reference
sc_dt::sc_unsigned_subref_r Class Reference
#include <sc_unsigned.hh>
Public Member Functions
virtual ~sc_unsigned_subref_r ()
sc_unsigned_subref_r (const sc_unsigned_subref_r &a)
int length () const
operator sc_unsigned () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
virtual int concat_length (bool *xz_present_p) const
virtual uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_unsigned_subref_r ()
void initialize (const sc_unsigned *obj_p, int left_, int right_)
Protected Attributes
int m_left
sc_unsigned * m_obj_p
int m_right
Private Member Functions
const sc_unsigned_subref_r & operator= (const sc_unsigned_subref_r &)
Friends
class sc_signed
class sc_unsigned
class sc_unsigned_signal
Detailed Description
Definition at line 721 of file sc_unsigned.hh.
Constructor & Destructor Documentation
sc_unsigned_subref_r() [1/2]
sc_dt::sc_unsigned_subref_r::sc_unsigned_subref_r () inline protected
Definition at line 729 of file sc_unsigned.hh.
~sc_unsigned_subref_r()
virtual sc_dt::sc_unsigned_subref_r::~sc_unsigned_subref_r () inline virtual
Definition at line 742 of file sc_unsigned.hh.
sc_unsigned_subref_r() [2/2]
sc_dt::sc_unsigned_subref_r::sc_unsigned_subref_r (const sc_unsigned_subref_r & a) inline
Definition at line 745 of file sc_unsigned.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_unsigned_subref_r::and_reduce () const inline
Definition at line 2076 of file sc_unsigned.hh.
References ArmISA::i, and sc_dt::sc_unsigned::test().
concat_get_ctrl()
bool sc_dt::sc_unsigned_subref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 57 of file sc_unsigned.cc.
concat_get_data()
bool sc_dt::sc_unsigned_subref_r::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 65 of file sc_unsigned.cc.
concat_get_uint64()
uint64 sc_dt::sc_unsigned_subref_r::concat_get_uint64 () const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 49 of file sc_unsigned.cc.
concat_length()
virtual int sc_dt::sc_unsigned_subref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 777 of file sc_unsigned.hh.
References sc_dt::and_reduce(), sc_dt::nand_reduce(), sc_dt::nor_reduce(), sc_dt::or_reduce(), sc_dt::xnor_reduce(), and sc_dt::xor_reduce().
initialize()
void sc_dt::sc_unsigned_subref_r::initialize (const sc_unsigned * obj_p, int left_, int right_) inline protected
Definition at line 733 of file sc_unsigned.hh.
Referenced by sc_dt::sc_unsigned::operator()(), and sc_dt::sc_unsigned::range().
length()
int sc_dt::sc_unsigned_subref_r::length () const inline
Definition at line 752 of file sc_unsigned.hh.
References sc_dt::SC_DEC, and sc_dt::to_string().
nand_reduce()
bool sc_dt::sc_unsigned_subref_r::nand_reduce () const inline
Definition at line 2086 of file sc_unsigned.hh.
References sc_dt::and_reduce().
nor_reduce()
bool sc_dt::sc_unsigned_subref_r::nor_reduce () const inline
Definition at line 2102 of file sc_unsigned.hh.
References sc_dt::or_reduce().
operator sc_unsigned()
sc_dt::sc_unsigned_subref_r::operator sc_unsigned () const
Definition at line 73 of file sc_unsigned.cc.
operator=()
const sc_unsigned_subref_r& sc_dt::sc_unsigned_subref_r::operator= (const sc_unsigned_subref_r &) private
or_reduce()
bool sc_dt::sc_unsigned_subref_r::or_reduce () const inline
Definition at line 2092 of file sc_unsigned.hh.
References ArmISA::i, and sc_dt::sc_unsigned::test().
print()
void sc_dt::sc_unsigned_subref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 797 of file sc_unsigned.hh.
References X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
to_double()
double sc_dt::sc_unsigned_subref_r::to_double () const
Definition at line 123 of file sc_unsigned.cc.
to_int()
int sc_dt::sc_unsigned_subref_r::to_int () const
Definition at line 81 of file sc_unsigned.cc.
to_int64()
int64 sc_dt::sc_unsigned_subref_r::to_int64 () const
Definition at line 109 of file sc_unsigned.cc.
to_long()
long sc_dt::sc_unsigned_subref_r::to_long () const
Definition at line 95 of file sc_unsigned.cc.
to_string() [1/2]
const std::string sc_dt::sc_unsigned_subref_r::to_string (sc_numrep numrep = SC_DEC) const
Definition at line 132 of file sc_unsigned.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
to_string() [2/2]
const std::string sc_dt::sc_unsigned_subref_r::to_string (sc_numrep numrep, bool w_prefix) const
Definition at line 140 of file sc_unsigned.cc.
to_uint()
unsigned int sc_dt::sc_unsigned_subref_r::to_uint () const
Definition at line 88 of file sc_unsigned.cc.
to_uint64()
uint64 sc_dt::sc_unsigned_subref_r::to_uint64 () const
Definition at line 116 of file sc_unsigned.cc.
Referenced by sc_dt::sc_int_base::sc_int_base(), and sc_dt::sc_uint_base::sc_uint_base().
to_ulong()
unsigned long sc_dt::sc_unsigned_subref_r::to_ulong () const
Definition at line 102 of file sc_unsigned.cc.
xnor_reduce()
bool sc_dt::sc_unsigned_subref_r::xnor_reduce () const inline
Definition at line 2118 of file sc_unsigned.hh.
References sc_dt::xor_reduce().
xor_reduce()
bool sc_dt::sc_unsigned_subref_r::xor_reduce () const inline
Definition at line 2108 of file sc_unsigned.hh.
References ArmISA::i, and sc_dt::sc_unsigned::test().
Friends And Related Function Documentation
sc_signed
friend class sc_signed friend
Definition at line 723 of file sc_unsigned.hh.
sc_unsigned
friend class sc_unsigned friend
Definition at line 724 of file sc_unsigned.hh.
sc_unsigned_signal
friend class sc_unsigned_signal friend
Definition at line 725 of file sc_unsigned.hh.
Member Data Documentation
m_left
int sc_dt::sc_unsigned_subref_r::m_left protected
Definition at line 803 of file sc_unsigned.hh.
m_obj_p
sc_unsigned* sc_dt::sc_unsigned_subref_r::m_obj_p protected
Definition at line 804 of file sc_unsigned.hh.
m_right
int sc_dt::sc_unsigned_subref_r::m_right protected
Definition at line 805 of file sc_unsigned.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_unsigned.hh
systemc/dt/int/sc_unsigned.cc