gem5: LSQUnit< Impl > Class Template Reference
LSQUnit< Impl > Class Template Reference
Class that implements the actual LQ and SQ for each specific thread.
#include <lsq_unit.hh>
Classes
class LQSenderState
Particularisation of the LSQSenderState to the LQ.
class LSQEntry
class SQEntry
class SQSenderState
Particularisation of the LSQSenderState to the SQ.
class WritebackEvent
Writeback event, specifically for when stores forward data to loads.
Public Types
typedef Impl::O3CPU O3CPU
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::CPUPol::IEW IEW
typedef Impl::CPUPol::LSQ LSQ
typedef Impl::CPUPol::IssueStruct IssueStruct
using LSQSenderState = typename LSQ::LSQSenderState
using LSQRequest = typename Impl::CPUPol::LSQ::LSQRequest
using LoadQueue = CircularQueue< LQEntry >
using StoreQueue = CircularQueue< SQEntry >
typedef CircularQueue< LQEntry >::iterator LQIterator
typedef CircularQueue< SQEntry >::iterator SQIterator
typedef CircularQueue< LQEntry > LQueue
typedef CircularQueue< SQEntry > SQueue
Public Member Functions
LSQUnit (uint32_t lqEntries, uint32_t sqEntries)
Constructs an LSQ unit.
LSQUnit (const LSQUnit &l)
We cannot copy LSQUnit because it has stats for which copy contructor is deleted explicitly.
void init (O3CPU *cpu_ptr, IEW *iew_ptr, DerivO3CPUParams *params, LSQ *lsq_ptr, unsigned id)
Initializes the LSQ unit with the specified number of entries.
std::string name () const
Returns the name of the LSQ unit.
void regStats ()
Registers statistics.
void setDcachePort (MasterPort *dcache_port)
Sets the pointer to the dcache port.
void drainSanityCheck () const
Perform sanity checks after a drain.
void takeOverFrom ()
Takes over from another CPU's thread.
void insert (const DynInstPtr &inst)
Inserts an instruction.
void insertLoad (const DynInstPtr &load_inst)
Inserts a load instruction.
void insertStore (const DynInstPtr &store_inst)
Inserts a store instruction.
Fault checkViolations (typename LoadQueue::iterator &loadIt, const DynInstPtr &inst)
Check for ordering violations in the LSQ.
void checkSnoop (PacketPtr pkt)
Check if an incoming invalidate hits in the lsq on a load that might have issued out of order wrt another load beacuse of the intermediate invalidate.
Fault executeLoad (const DynInstPtr &inst)
Executes a load instruction.
Fault executeLoad (int lq_idx)
Fault executeStore (const DynInstPtr &inst)
Executes a store instruction.
void commitLoad ()
Commits the head load.
void commitLoads (InstSeqNum &youngest_inst)
Commits loads older than a specific sequence number.
void commitStores (InstSeqNum &youngest_inst)
Commits stores older than a specific sequence number.
void writebackStores ()
Writes back stores.
void completeDataAccess (PacketPtr pkt)
Completes the data access that has been returned from the memory system.
void squash (const InstSeqNum &squashed_num)
Squashes all instructions younger than a specific sequence number.
bool violation ()
Returns if there is a memory ordering violation.
DynInstPtr getMemDepViolator ()
Returns the memory ordering violator.
unsigned numFreeLoadEntries ()
Returns the number of free LQ entries.
unsigned numFreeStoreEntries ()
Returns the number of free SQ entries.
int numLoads ()
Returns the number of loads in the LQ.
int numStores ()
Returns the number of stores in the SQ.
bool isFull ()
Returns if either the LQ or SQ is full.
bool isEmpty () const
Returns if both the LQ and SQ are empty.
bool lqFull ()
Returns if the LQ is full.
bool sqFull ()
Returns if the SQ is full.
bool lqEmpty () const
Returns if the LQ is empty.
bool sqEmpty () const
Returns if the SQ is empty.
unsigned getCount ()
Returns the number of instructions in the LSQ.
bool hasStoresToWB ()
Returns if there are any stores to writeback.
int numStoresToWB ()
Returns the number of stores to writeback.
bool willWB ()
Returns if the LSQ unit will writeback on this cycle.
void recvRetry ()
Handles doing the retry.
unsigned int cacheLineSize ()
bool trySendPacket (bool isLoad, PacketPtr data_pkt)
Attempts to send a packet to the cache.
void dumpInsts () const
Debugging function to dump instructions in the LSQ.
void schedule (Event &ev, Tick when)
Schedule event for the cpu.
BaseTLB * dTLB ()
bool recvTimingResp (PacketPtr pkt)
Handles writing back and completing the load or store that has returned from memory.
Fault read (LSQRequest *req, int load_idx)
Executes the load at the given index.
Fault write (LSQRequest *req, uint8_t *data, int store_idx)
Executes the store at the given index.
int getLoadHead ()
Returns the index of the head load instruction.
InstSeqNum getLoadHeadSeqNum ()
Returns the sequence number of the head load instruction.
int getStoreHead ()
Returns the index of the head store instruction.
InstSeqNum getStoreHeadSeqNum ()
Returns the sequence number of the head store instruction.
bool isStalled ()
Returns whether or not the LSQ unit is stalled.
Public Attributes
CircularQueue< SQEntry > storeQueue
The store queue.
LoadQueue loadQueue
The load queue.
Static Public Attributes
static constexpr auto MaxDataBytes = MaxVecRegLenInBytes
Private Types
using LQEntry = LSQEntry
Private Member Functions
void resetState ()
Reset the LSQ state.
void writeback (const DynInstPtr &inst, PacketPtr pkt)
Writes back the instruction, sending it to IEW.
void writebackBlockedStore ()
Try to finish a previously blocked write back attempt.
void completeStore (typename StoreQueue::iterator store_idx)
Completes the store at the specified index.
void storePostSend ()
Handles completing the send of a store to memory.
Private Attributes
O3CPU * cpu
Pointer to the CPU.
IEW * iewStage
Pointer to the IEW stage.
LSQ * lsq
Pointer to the LSQ.
MasterPort * dcachePort
Pointer to the dcache port.
ThreadID lsqID
The LSQUnit thread id.
unsigned depCheckShift
The number of places to shift addresses in the LSQ before checking for dependency violations.
bool checkLoads
Should loads be checked for dependency issues.
int loads
The number of load instructions in the LQ.
int stores
The number of store instructions in the SQ.
int storesToWB
The number of store instructions in the SQ waiting to writeback.
StoreQueue::iterator storeWBIt
The index of the first instruction that may be ready to be written back, and has not yet been written back.
Addr cacheBlockMask
Address Mask for a cache block (e.g.
TimeBuffer< IssueStruct >::wire fromIssue
Wire to read information from the issue stage time queue.
bool stalled
Whether or not the LSQ is stalled.
InstSeqNum stallingStoreIsn
The store that causes the stall due to partial store to load forwarding.
int stallingLoadIdx
The index of the above store.
PacketPtr retryPkt
The packet that needs to be retried.
bool isStoreBlocked
Whehter or not a store is blocked due to the memory system.
bool storeInFlight
Whether or not a store is in flight.
DynInstPtr memDepViolator
The oldest load that caused a memory ordering violation.
bool hasPendingRequest
Whether or not there is a packet that couldn't be sent because of a lack of cache ports.
LSQRequest * pendingRequest
The packet that is pending free cache ports.
bool needsTSO
Flag for memory model.
Stats::Scalar lsqForwLoads
Total number of loads forwaded from LSQ stores.
Stats::Scalar invAddrLoads
Total number of loads ignored due to invalid addresses.
Stats::Scalar lsqSquashedLoads
Total number of squashed loads.
Stats::Scalar lsqIgnoredResponses
Total number of responses from the memory system that are ignored due to the instruction already being squashed.
Stats::Scalar lsqMemOrderViolation
Tota number of memory ordering violations.
Stats::Scalar lsqSquashedStores
Total number of squashed stores.
Stats::Scalar invAddrSwpfs
Total number of software prefetches ignored due to invalid addresses.
Stats::Scalar lsqBlockedLoads
Ready loads blocked due to partial store-forwarding.
Stats::Scalar lsqRescheduledLoads
Number of loads that were rescheduled.
Stats::Scalar lsqCacheBlocked
Number of times the LSQ is blocked due to the cache.
Detailed Description
template<class Impl>
class LSQUnit< Impl >
Class that implements the actual LQ and SQ for each specific thread.
Both are circular queues; load entries are freed upon committing, while store entries are freed once they writeback. The LSQUnit tracks if there are memory ordering violations, and also detects partial load to store forwarding cases (a store only has part of a load's data) that requires the load to wait until the store writes back. In the former case it holds onto the instruction until the dependence unit looks at it, and in the latter it stalls the LSQ until the store writes back. At that point the load is replayed.
Definition at line 81 of file lsq_unit.hh.
Member Typedef Documentation
DynInstPtr
template<class Impl> typedef Impl::DynInstPtr LSQUnit< Impl >::DynInstPtr
Definition at line 87 of file lsq_unit.hh.
IEW
template<class Impl> typedef Impl::CPUPol::IEW LSQUnit< Impl >::IEW
Definition at line 88 of file lsq_unit.hh.
IssueStruct
template<class Impl> typedef Impl::CPUPol::IssueStruct LSQUnit< Impl >::IssueStruct
Definition at line 90 of file lsq_unit.hh.
LoadQueue
template<class Impl> using LSQUnit< Impl >::LoadQueue = CircularQueue<LQEntry>
Definition at line 213 of file lsq_unit.hh.
LQEntry
template<class Impl> using LSQUnit< Impl >::LQEntry = LSQEntry private
Definition at line 210 of file lsq_unit.hh.
LQIterator
template<class Impl> typedef CircularQueue<LQEntry>::iterator LSQUnit< Impl >::LQIterator
Definition at line 605 of file lsq_unit.hh.
LQueue
template<class Impl> typedef CircularQueue<LQEntry> LSQUnit< Impl >::LQueue
Definition at line 607 of file lsq_unit.hh.
LSQ
template<class Impl> typedef Impl::CPUPol::LSQ LSQUnit< Impl >::LSQ
Definition at line 89 of file lsq_unit.hh.
LSQRequest
template<class Impl> using LSQUnit< Impl >::LSQRequest = typename Impl::CPUPol::LSQ::LSQRequest
Definition at line 93 of file lsq_unit.hh.
LSQSenderState
template<class Impl> using LSQUnit< Impl >::LSQSenderState = typename LSQ::LSQSenderState
Definition at line 92 of file lsq_unit.hh.
O3CPU
template<class Impl> typedef Impl::O3CPU LSQUnit< Impl >::O3CPU
Definition at line 86 of file lsq_unit.hh.
SQIterator
template<class Impl> typedef CircularQueue<SQEntry>::iterator LSQUnit< Impl >::SQIterator
Definition at line 606 of file lsq_unit.hh.
SQueue
template<class Impl> typedef CircularQueue<SQEntry> LSQUnit< Impl >::SQueue
Definition at line 608 of file lsq_unit.hh.
StoreQueue
template<class Impl> using LSQUnit< Impl >::StoreQueue = CircularQueue<SQEntry>
Definition at line 214 of file lsq_unit.hh.
Constructor & Destructor Documentation
LSQUnit() [1/2]
template<class Impl > LSQUnit< Impl >::LSQUnit (uint32_t lqEntries, uint32_t sqEntries)
Constructs an LSQ unit.
init() must be called prior to use.
Definition at line 146 of file lsq_unit_impl.hh.
LSQUnit() [2/2]
template<class Impl> LSQUnit< Impl >::LSQUnit (const LSQUnit< Impl > & l) inline
We cannot copy LSQUnit because it has stats for which copy contructor is deleted explicitly.
However, STL vector requires a valid copy constructor for the base type at compile time.
Definition at line 224 of file lsq_unit.hh.
References LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::checkViolations(), LSQUnit< Impl >::drainSanityCheck(), LSQUnit< Impl >::executeLoad(), LSQUnit< Impl >::init(), LSQUnit< Impl >::insert(), LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::insertStore(), LSQUnit< Impl >::LSQEntry::inst, LSQUnit< Impl >::name(), panic, LSQUnit< Impl >::regStats(), LSQUnit< Impl >::setDcachePort(), and LSQUnit< Impl >::takeOverFrom().
Member Function Documentation
cacheLineSize()
template<class Impl > unsigned int LSQUnit< Impl >::cacheLineSize ()
Definition at line 1133 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::cpu.
Referenced by LSQUnit< Impl >::willWB().
checkSnoop()
template<class Impl > void LSQUnit< Impl >::checkSnoop (PacketPtr pkt)
Check if an incoming invalidate hits in the lsq on a load that might have issued out of order wrt another load beacuse of the intermediate invalidate.
Definition at line 371 of file lsq_unit_impl.hh.
References CircularQueue< T >::begin(), LSQUnit< Impl >::cacheBlockMask, LSQUnit< Impl >::cpu, DPRINTF, CircularQueue< T >::empty(), CircularQueue< T >::end(), Packet::getAddr(), TheISA::handleLockedSnoop(), TheISA::handleLockedSnoopHit(), Packet::isInvalidate(), Request::LLSC, LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::needsTSO, and X86ISA::x.
Referenced by LSQUnit< Impl >::LSQUnit().
checkViolations()
template<class Impl > Fault LSQUnit< Impl >::checkViolations (typename LoadQueue::iterator & loadIt, const DynInstPtr & inst)
Check for ordering violations in the LSQ.
For a store squash if we ever find a conflicting load. For a load, only squash if we an external snoop invalidate has been seen for that load address
Parameters
load_idx index to start checking at
inst the instruction to check
Todo:
in theory you only need to check an instruction that has executed however, there isn't a good way in the pipeline at the moment to check all instructions that will execute before the store writes back. Thus, like the implementation that came before it, we're overly conservative.
Definition at line 452 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::depCheckShift, DPRINTF, CircularQueue< T >::end(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::lsqMemOrderViolation, LSQUnit< Impl >::memDepViolator, and NoFault.
Referenced by LSQUnit< Impl >::executeLoad(), LSQUnit< Impl >::executeStore(), and LSQUnit< Impl >::LSQUnit().
commitLoad()
template<class Impl > void LSQUnit< Impl >::commitLoad ()
Commits the head load.
Definition at line 654 of file lsq_unit_impl.hh.
References DPRINTF, CircularQueue< T >::front(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::loads, and CircularQueue< T >::pop_front().
Referenced by LSQUnit< Impl >::commitLoads(), and LSQUnit< Impl >::executeLoad().
commitLoads()
template<class Impl > void LSQUnit< Impl >::commitLoads (InstSeqNum & youngest_inst)
Commits loads older than a specific sequence number.
Definition at line 669 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::commitLoad(), CircularQueue< T >::front(), LSQUnit< Impl >::loadQueue, and LSQUnit< Impl >::loads.
Referenced by LSQUnit< Impl >::executeLoad().
commitStores()
template<class Impl > void LSQUnit< Impl >::commitStores (InstSeqNum & youngest_inst)
Commits stores older than a specific sequence number.
Definition at line 681 of file lsq_unit_impl.hh.
References DPRINTF, LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, LSQUnit< Impl >::storesToWB, and X86ISA::x.
Referenced by LSQUnit< Impl >::executeLoad().
completeDataAccess()
template<class Impl > void LSQUnit< Impl >::completeDataAccess (PacketPtr pkt)
Completes the data access that has been returned from the memory system.
Definition at line 113 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::cpu, LSQUnit< Impl >::WritebackEvent::inst, Packet::senderState, ArmISA::ss, and LSQUnit< Impl >::writeback().
Referenced by LSQUnit< Impl >::executeLoad().
completeStore()
template<class Impl > void LSQUnit< Impl >::completeStore (typename StoreQueue::iterator store_idx) private
Completes the store at the specified index.
Definition at line 993 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::cpu, curTick(), DPRINTF, DTRACE, CircularQueue< T >::iterator::idx(), LSQUnit< Impl >::iewStage, LSQUnit< Impl >::isStalled(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::needsTSO, LSQUnit< Impl >::stalled, LSQUnit< Impl >::stallingLoadIdx, LSQUnit< Impl >::stallingStoreIsn, LSQUnit< Impl >::storeInFlight, LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, and LSQUnit< Impl >::storesToWB.
Referenced by LSQUnit< Impl >::completeDataAccess(), LSQUnit< Impl >::willWB(), and LSQUnit< Impl >::writebackStores().
drainSanityCheck()
template<class Impl > void LSQUnit< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 258 of file lsq_unit_impl.hh.
References CircularQueue< T >::capacity(), ArmISA::i, LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::retryPkt, and LSQUnit< Impl >::storesToWB.
Referenced by LSQUnit< Impl >::LSQUnit().
dTLB()
template<class Impl> BaseTLB* LSQUnit< Impl >::dTLB () inline
Definition at line 384 of file lsq_unit.hh.
References LSQUnit< Impl >::cpu.
dumpInsts()
template<class Impl > void LSQUnit< Impl >::dumpInsts () const
Debugging function to dump instructions in the LSQ.
Definition at line 1108 of file lsq_unit_impl.hh.
References cprintf(), ArmISA::e, LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::loads, LSQUnit< Impl >::storeQueue, and LSQUnit< Impl >::stores.
Referenced by LSQUnit< Impl >::willWB().
executeLoad() [1/2]
template<class Impl > Fault LSQUnit< Impl >::executeLoad (const DynInstPtr & inst)
Executes a load instruction.
Definition at line 533 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::checkLoads, LSQUnit< Impl >::checkViolations(), DPRINTF, LSQUnit< Impl >::iewStage, and NoFault.
Referenced by LSQUnit< Impl >::LSQUnit().
executeLoad() [2/2]
template<class Impl> Fault LSQUnit< Impl >::executeLoad (int lq_idx) inline
Definition at line 270 of file lsq_unit.hh.
References LSQUnit< Impl >::commitLoad(), LSQUnit< Impl >::commitLoads(), LSQUnit< Impl >::commitStores(), LSQUnit< Impl >::completeDataAccess(), LSQUnit< Impl >::executeStore(), NoFault, panic, LSQUnit< Impl >::squash(), and LSQUnit< Impl >::writebackStores().
executeStore()
template<class Impl > Fault LSQUnit< Impl >::executeStore (const DynInstPtr & inst)
Executes a store instruction.
Definition at line 601 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::checkViolations(), DPRINTF, NoFault, LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, and LSQUnit< Impl >::storesToWB.
Referenced by LSQUnit< Impl >::executeLoad().
getCount()
template<class Impl> unsigned LSQUnit< Impl >::getCount () inline
Returns the number of instructions in the LSQ.
Definition at line 331 of file lsq_unit.hh.
References LSQUnit< Impl >::loads, and LSQUnit< Impl >::stores.
getLoadHead()
template<class Impl> int LSQUnit< Impl >::getLoadHead () inline
Returns the index of the head load instruction.
Definition at line 580 of file lsq_unit.hh.
References CircularQueue< T >::head().
getLoadHeadSeqNum()
template<class Impl> InstSeqNum LSQUnit< Impl >::getLoadHeadSeqNum () inline
Returns the sequence number of the head load instruction.
Definition at line 584 of file lsq_unit.hh.
References CircularQueue< T >::front().
getMemDepViolator()
template<class Impl > Impl::DynInstPtr LSQUnit< Impl >::getMemDepViolator ()
Returns the memory ordering violator.
Definition at line 337 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::memDepViolator.
Referenced by LSQUnit< Impl >::violation().
getStoreHead()
template<class Impl> int LSQUnit< Impl >::getStoreHead () inline
Returns the index of the head store instruction.
Definition at line 592 of file lsq_unit.hh.
References CircularQueue< T >::head().
getStoreHeadSeqNum()
template<class Impl> InstSeqNum LSQUnit< Impl >::getStoreHeadSeqNum () inline
Returns the sequence number of the head store instruction.
Definition at line 595 of file lsq_unit.hh.
References CircularQueue< T >::front().
hasStoresToWB()
template<class Impl> bool LSQUnit< Impl >::hasStoresToWB () inline
Returns if there are any stores to writeback.
Definition at line 334 of file lsq_unit.hh.
References LSQUnit< Impl >::storesToWB.
init()
template<class Impl > void LSQUnit< Impl >::init (O3CPU * cpu_ptr, IEW * iew_ptr, DerivO3CPUParams * params, LSQ * lsq_ptr, unsigned id)
Initializes the LSQ unit with the specified number of entries.
Definition at line 156 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::checkLoads, LSQUnit< Impl >::cpu, LSQUnit< Impl >::depCheckShift, DPRINTF, ArmISA::id, LSQUnit< Impl >::iewStage, LSQUnit< Impl >::lsq, LSQUnit< Impl >::lsqID, LSQUnit< Impl >::needsTSO, and LSQUnit< Impl >::resetState().
Referenced by LSQUnit< Impl >::LSQUnit().
insert()
template<class Impl > void LSQUnit< Impl >::insert (const DynInstPtr & inst)
Inserts an instruction.
Definition at line 276 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::insertLoad(), and LSQUnit< Impl >::insertStore().
Referenced by LSQUnit< Impl >::LSQUnit().
insertLoad()
template<class Impl > void LSQUnit< Impl >::insertLoad (const DynInstPtr & load_inst)
Inserts a load instruction.
Definition at line 293 of file lsq_unit_impl.hh.
References CircularQueue< T >::advance_tail(), CircularQueue< T >::back(), CircularQueue< T >::capacity(), DPRINTF, CircularQueue< T >::full(), CircularQueue< T >::getIterator(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::loads, LSQUnit< Impl >::storeQueue, and CircularQueue< T >::tail().
Referenced by LSQUnit< Impl >::insert(), and LSQUnit< Impl >::LSQUnit().
insertStore()
template<class Impl > void LSQUnit< Impl >::insertStore (const DynInstPtr & store_inst)
Inserts a store instruction.
Definition at line 316 of file lsq_unit_impl.hh.
References DPRINTF, CircularQueue< T >::end(), LSQUnit< Impl >::loadQueue, CircularQueue< T >::moduloAdd(), LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, and CircularQueue< T >::tail().
Referenced by LSQUnit< Impl >::insert(), and LSQUnit< Impl >::LSQUnit().
isEmpty()
template<class Impl> bool LSQUnit< Impl >::isEmpty () const inline
Returns if both the LQ and SQ are empty.
Definition at line 316 of file lsq_unit.hh.
References LSQUnit< Impl >::lqEmpty(), and LSQUnit< Impl >::sqEmpty().
isFull()
template<class Impl> bool LSQUnit< Impl >::isFull () inline
Returns if either the LQ or SQ is full.
Definition at line 313 of file lsq_unit.hh.
References LSQUnit< Impl >::lqFull(), and LSQUnit< Impl >::sqFull().
isStalled()
template<class Impl> bool LSQUnit< Impl >::isStalled () inline
Returns whether or not the LSQ unit is stalled.
Definition at line 603 of file lsq_unit.hh.
References LSQUnit< Impl >::stalled.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::storePostSend().
lqEmpty()
template<class Impl> bool LSQUnit< Impl >::lqEmpty () const inline
Returns if the LQ is empty.
Definition at line 325 of file lsq_unit.hh.
References LSQUnit< Impl >::loads.
Referenced by LSQUnit< Impl >::isEmpty().
lqFull()
template<class Impl> bool LSQUnit< Impl >::lqFull () inline
Returns if the LQ is full.
Definition at line 319 of file lsq_unit.hh.
References CircularQueue< T >::full(), and LSQUnit< Impl >::loadQueue.
Referenced by LSQUnit< Impl >::isFull().
name()
template<class Impl > std::string LSQUnit< Impl >::name () const
Returns the name of the LSQ unit.
Definition at line 195 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::iewStage, LSQUnit< Impl >::lsqID, and sc_dt::to_string().
Referenced by LSQUnit< Impl >::LSQUnit(), and LSQUnit< Impl >::regStats().
numFreeLoadEntries()
template<class Impl > unsigned LSQUnit< Impl >::numFreeLoadEntries ()
Returns the number of free LQ entries.
Definition at line 348 of file lsq_unit_impl.hh.
References CircularQueue< T >::capacity(), DPRINTF, LSQUnit< Impl >::loadQueue, and LSQUnit< Impl >::loads.
Referenced by LSQUnit< Impl >::violation().
numFreeStoreEntries()
template<class Impl > unsigned LSQUnit< Impl >::numFreeStoreEntries ()
Returns the number of free SQ entries.
Definition at line 359 of file lsq_unit_impl.hh.
References DPRINTF, LSQUnit< Impl >::storeQueue, and LSQUnit< Impl >::stores.
Referenced by LSQUnit< Impl >::violation().
numLoads()
template<class Impl> int LSQUnit< Impl >::numLoads () inline
Returns the number of loads in the LQ.
Definition at line 307 of file lsq_unit.hh.
References LSQUnit< Impl >::loads.
numStores()
template<class Impl> int LSQUnit< Impl >::numStores () inline
Returns the number of stores in the SQ.
Definition at line 310 of file lsq_unit.hh.
References LSQUnit< Impl >::stores.
numStoresToWB()
template<class Impl> int LSQUnit< Impl >::numStoresToWB () inline
Returns the number of stores to writeback.
Definition at line 337 of file lsq_unit.hh.
References LSQUnit< Impl >::storesToWB.
read()
template<class Impl > Fault LSQUnit< Impl >::read (LSQRequest * req, int load_idx)
Executes the load at the given index.
Definition at line 613 of file lsq_unit.hh.
References LSQUnit< Impl >::cpu, curTick(), Packet::dataStatic(), DPRINTF, CircularQueue< T >::getIterator(), TheISA::handleLockedRead(), CircularQueue< T >::head(), LSQUnit< Impl >::iewStage, LSQUnit< Impl >::LSQEntry::instruction(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::lsqForwLoads, LSQUnit< Impl >::lsqID, LSQUnit< Impl >::lsqRescheduledLoads, LSQUnit< Impl >::MaxDataBytes, NoFault, panic, MemCmd::ReadReq, LSQUnit< Impl >::LSQEntry::setRequest(), LSQUnit< Impl >::stalled, LSQUnit< Impl >::stallingLoadIdx, LSQUnit< Impl >::stallingStoreIsn, LSQUnit< Impl >::storeQueue, and LSQUnit< Impl >::storeWBIt.
recvRetry()
template<class Impl > void LSQUnit< Impl >::recvRetry ()
Handles doing the retry.
Definition at line 1098 of file lsq_unit_impl.hh.
References DPRINTF, LSQUnit< Impl >::isStoreBlocked, and LSQUnit< Impl >::writebackBlockedStore().
Referenced by LSQUnit< Impl >::willWB().
recvTimingResp()
template<class Impl > bool LSQUnit< Impl >::recvTimingResp (PacketPtr pkt)
Handles writing back and completing the load or store that has returned from memory.
Parameters
pkt Response packet from the memory sub-system
Definition at line 95 of file lsq_unit_impl.hh.
References Packet::senderState.
regStats()
template<class Impl > void LSQUnit< Impl >::regStats ()
Registers statistics.
Definition at line 206 of file lsq_unit_impl.hh.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), LSQUnit< Impl >::invAddrLoads, LSQUnit< Impl >::invAddrSwpfs, LSQUnit< Impl >::lsqBlockedLoads, LSQUnit< Impl >::lsqCacheBlocked, LSQUnit< Impl >::lsqForwLoads, LSQUnit< Impl >::lsqIgnoredResponses, LSQUnit< Impl >::lsqMemOrderViolation, LSQUnit< Impl >::lsqRescheduledLoads, LSQUnit< Impl >::lsqSquashedLoads, LSQUnit< Impl >::lsqSquashedStores, LSQUnit< Impl >::name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
Referenced by LSQUnit< Impl >::LSQUnit().
resetState()
template<class Impl > void LSQUnit< Impl >::resetState () private
Reset the LSQ state.
Definition at line 178 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::cacheBlockMask, LSQUnit< Impl >::cpu, LSQUnit< Impl >::loads, LSQUnit< Impl >::memDepViolator, LSQUnit< Impl >::retryPkt, LSQUnit< Impl >::stalled, LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, LSQUnit< Impl >::storesToWB, and LSQUnit< Impl >::storeWBIt.
Referenced by LSQUnit< Impl >::init(), LSQUnit< Impl >::takeOverFrom(), and LSQUnit< Impl >::willWB().
schedule()
template<class Impl> void LSQUnit< Impl >::schedule (Event & ev, Tick when) inline
Schedule event for the cpu.
Definition at line 382 of file lsq_unit.hh.
References LSQUnit< Impl >::cpu.
setDcachePort()
template<class Impl > void LSQUnit< Impl >::setDcachePort (MasterPort * dcache_port)
Sets the pointer to the dcache port.
Definition at line 251 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::dcachePort.
Referenced by LSQUnit< Impl >::LSQUnit().
sqEmpty()
template<class Impl> bool LSQUnit< Impl >::sqEmpty () const inline
Returns if the SQ is empty.
Definition at line 328 of file lsq_unit.hh.
References LSQUnit< Impl >::stores.
Referenced by LSQUnit< Impl >::isEmpty().
sqFull()
template<class Impl> bool LSQUnit< Impl >::sqFull () inline
Returns if the SQ is full.
Definition at line 322 of file lsq_unit.hh.
References LSQUnit< Impl >::storeQueue.
Referenced by LSQUnit< Impl >::isFull().
squash()
template<class Impl > void LSQUnit< Impl >::squash (const InstSeqNum & squashed_num)
Squashes all instructions younger than a specific sequence number.
Definition at line 849 of file lsq_unit_impl.hh.
References CircularQueue< T >::back(), DPRINTF, LSQUnit< Impl >::isStalled(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::loads, LSQUnit< Impl >::lsqSquashedLoads, LSQUnit< Impl >::lsqSquashedStores, LSQUnit< Impl >::memDepViolator, panic, CircularQueue< T >::pop_back(), LSQUnit< Impl >::stalled, LSQUnit< Impl >::stallingLoadIdx, LSQUnit< Impl >::stallingStoreIsn, LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, and CircularQueue< T >::tail().
Referenced by LSQUnit< Impl >::executeLoad().
storePostSend()
template<class Impl > void LSQUnit< Impl >::storePostSend () private
Handles completing the send of a store to memory.
Definition at line 918 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::cpu, DPRINTF, LSQUnit< Impl >::iewStage, LSQUnit< Impl >::isStalled(), LSQUnit< Impl >::loadQueue, LSQUnit< Impl >::needsTSO, LSQUnit< Impl >::stalled, LSQUnit< Impl >::stallingLoadIdx, LSQUnit< Impl >::stallingStoreIsn, LSQUnit< Impl >::storeInFlight, and LSQUnit< Impl >::storeWBIt.
Referenced by LSQUnit< Impl >::willWB(), LSQUnit< Impl >::writebackBlockedStore(), and LSQUnit< Impl >::writebackStores().
takeOverFrom()
template<class Impl > void LSQUnit< Impl >::takeOverFrom ()
Takes over from another CPU's thread.
Definition at line 269 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::resetState().
Referenced by LSQUnit< Impl >::LSQUnit().
trySendPacket()
template<class Impl > bool LSQUnit< Impl >::trySendPacket (bool isLoad, PacketPtr data_pkt)
Attempts to send a packet to the cache.
Check if there are ports available. Return true if there are, false if there are not.
Definition at line 1058 of file lsq_unit_impl.hh.
References LSQ< Impl >::cacheBlocked(), LSQ< Impl >::cachePortAvailable(), LSQ< Impl >::cachePortBusy(), LSQUnit< Impl >::dcachePort, LSQUnit< Impl >::isStoreBlocked, LSQUnit< Impl >::lsq, LSQUnit< Impl >::lsqCacheBlocked, Packet::senderState, MasterPort::sendTimingReq(), and LSQUnit< Impl >::storeWBIt.
Referenced by LSQUnit< Impl >::willWB().
violation()
template<class Impl> bool LSQUnit< Impl >::violation () inline
Returns if there is a memory ordering violation.
Value is reset upon call to getMemDepViolator().
Definition at line 295 of file lsq_unit.hh.
References LSQUnit< Impl >::getMemDepViolator(), LSQUnit< Impl >::memDepViolator, LSQUnit< Impl >::numFreeLoadEntries(), and LSQUnit< Impl >::numFreeStoreEntries().
willWB()
template<class Impl> bool LSQUnit< Impl >::willWB () inline
Returns if the LSQ unit will writeback on this cycle.
Definition at line 341 of file lsq_unit.hh.
References LSQUnit< Impl >::cacheLineSize(), LSQUnit< Impl >::completeStore(), CircularQueue< T >::iterator::dereferenceable(), LSQUnit< Impl >::dumpInsts(), LSQUnit< Impl >::isStoreBlocked, LSQUnit< Impl >::recvRetry(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::storePostSend(), LSQUnit< Impl >::storeWBIt, LSQUnit< Impl >::trySendPacket(), LSQUnit< Impl >::writeback(), and LSQUnit< Impl >::writebackBlockedStore().
write()
template<class Impl > Fault LSQUnit< Impl >::write (LSQRequest * req, uint8_t * data, int store_idx)
Executes the store at the given index.
Definition at line 855 of file lsq_unit.hh.
References Request::CACHE_BLOCK_ZERO, data, LSQUnit< Impl >::SQEntry::DataSize, DPRINTF, NoFault, LSQUnit< Impl >::LSQEntry::size(), Request::STORE_NO_DATA, LSQUnit< Impl >::storeQueue, and LSQUnit< Impl >::LSQEntry::valid().
writeback()
template<class Impl > void LSQUnit< Impl >::writeback (const DynInstPtr & inst, PacketPtr pkt) private
Writes back the instruction, sending it to IEW.
Definition at line 950 of file lsq_unit_impl.hh.
References DPRINTF, LSQUnit< Impl >::iewStage, LSQUnit< Impl >::lsqIgnoredResponses, and NoFault.
Referenced by LSQUnit< Impl >::completeDataAccess(), and LSQUnit< Impl >::willWB().
writebackBlockedStore()
template<class Impl > void LSQUnit< Impl >::writebackBlockedStore () private
Try to finish a previously blocked write back attempt.
Definition at line 708 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::isStoreBlocked, LSQUnit< Impl >::storePostSend(), and LSQUnit< Impl >::storeWBIt.
Referenced by LSQUnit< Impl >::recvRetry(), LSQUnit< Impl >::willWB(), and LSQUnit< Impl >::writebackStores().
writebackStores()
template<class Impl > void LSQUnit< Impl >::writebackStores ()
Writes back stores.
Definition at line 719 of file lsq_unit_impl.hh.
References LSQUnit< Impl >::cacheBlockMask, LSQ< Impl >::cachePortAvailable(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::cpu, curTick(), Packet::dataStatic(), CircularQueue< T >::iterator::dereferenceable(), DPRINTF, TheISA::handleLockedWrite(), CircularQueue< T >::iterator::idx(), LSQUnit< Impl >::isStoreBlocked, LSQUnit< Impl >::lsq, LSQUnit< Impl >::lsqID, LSQUnit< Impl >::needsTSO, LSQUnit< Impl >::storeInFlight, LSQUnit< Impl >::storePostSend(), LSQUnit< Impl >::storeQueue, LSQUnit< Impl >::stores, LSQUnit< Impl >::storesToWB, LSQUnit< Impl >::storeWBIt, LSQUnit< Impl >::writebackBlockedStore(), and MemCmd::WriteReq.
Referenced by LSQUnit< Impl >::executeLoad().
Member Data Documentation
cacheBlockMask
template<class Impl> Addr LSQUnit< Impl >::cacheBlockMask private
Address Mask for a cache block (e.g.
~(cache_block_size-1))
Definition at line 502 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::resetState(), and LSQUnit< Impl >::writebackStores().
checkLoads
template<class Impl> bool LSQUnit< Impl >::checkLoads private
Should loads be checked for dependency issues.
Definition at line 487 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::executeLoad(), and LSQUnit< Impl >::init().
cpu
template<class Impl> O3CPU* LSQUnit< Impl >::cpu private
Pointer to the CPU.
Definition at line 388 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::cacheLineSize(), LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::completeDataAccess(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::dTLB(), LSQUnit< Impl >::init(), LSQUnit< Impl >::read(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::schedule(), LSQUnit< Impl >::storePostSend(), and LSQUnit< Impl >::writebackStores().
dcachePort
template<class Impl> MasterPort* LSQUnit< Impl >::dcachePort private
Pointer to the dcache port.
Used only for sending.
Definition at line 397 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::setDcachePort(), and LSQUnit< Impl >::trySendPacket().
depCheckShift
template<class Impl> unsigned LSQUnit< Impl >::depCheckShift private
The number of places to shift addresses in the LSQ before checking for dependency violations.
Definition at line 484 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkViolations(), and LSQUnit< Impl >::init().
fromIssue
template<class Impl> TimeBuffer<IssueStruct>::wire LSQUnit< Impl >::fromIssue private
Wire to read information from the issue stage time queue.
Definition at line 505 of file lsq_unit.hh.
hasPendingRequest
template<class Impl> bool LSQUnit< Impl >::hasPendingRequest private
Whether or not there is a packet that couldn't be sent because of a lack of cache ports.
Definition at line 530 of file lsq_unit.hh.
iewStage
template<class Impl> IEW* LSQUnit< Impl >::iewStage private
Pointer to the IEW stage.
Definition at line 391 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::executeLoad(), LSQUnit< Impl >::init(), LSQUnit< Impl >::name(), LSQUnit< Impl >::read(), LSQUnit< Impl >::storePostSend(), and LSQUnit< Impl >::writeback().
invAddrLoads
template<class Impl> Stats::Scalar LSQUnit< Impl >::invAddrLoads private
Total number of loads ignored due to invalid addresses.
Definition at line 545 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats().
invAddrSwpfs
template<class Impl> Stats::Scalar LSQUnit< Impl >::invAddrSwpfs private
Total number of software prefetches ignored due to invalid addresses.
Definition at line 561 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats().
isStoreBlocked
template<class Impl> bool LSQUnit< Impl >::isStoreBlocked private
Whehter or not a store is blocked due to the memory system.
Definition at line 520 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::recvRetry(), LSQUnit< Impl >::trySendPacket(), LSQUnit< Impl >::willWB(), LSQUnit< Impl >::writebackBlockedStore(), and LSQUnit< Impl >::writebackStores().
loadQueue
template<class Impl> LoadQueue LSQUnit< Impl >::loadQueue
The load queue.
Definition at line 478 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::checkViolations(), LSQUnit< Impl >::commitLoad(), LSQUnit< Impl >::commitLoads(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::drainSanityCheck(), LSQUnit< Impl >::dumpInsts(), LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::insertStore(), LSQ< Impl >::LSQRequest::install(), LSQUnit< Impl >::lqFull(), LSQUnit< Impl >::numFreeLoadEntries(), LSQUnit< Impl >::read(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::storePostSend().
loads
template<class Impl> int LSQUnit< Impl >::loads private
The number of load instructions in the LQ.
Definition at line 490 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::commitLoad(), LSQUnit< Impl >::commitLoads(), LSQUnit< Impl >::dumpInsts(), LSQUnit< Impl >::getCount(), LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::lqEmpty(), LSQUnit< Impl >::numFreeLoadEntries(), LSQUnit< Impl >::numLoads(), LSQUnit< Impl >::resetState(), and LSQUnit< Impl >::squash().
lsq
template<class Impl> LSQ* LSQUnit< Impl >::lsq private
Pointer to the LSQ.
Definition at line 394 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::init(), LSQUnit< Impl >::trySendPacket(), and LSQUnit< Impl >::writebackStores().
lsqBlockedLoads
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqBlockedLoads private
Ready loads blocked due to partial store-forwarding.
Definition at line 564 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats().
lsqCacheBlocked
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqCacheBlocked private
Number of times the LSQ is blocked due to the cache.
Definition at line 570 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats(), and LSQUnit< Impl >::trySendPacket().
lsqForwLoads
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqForwLoads private
Total number of loads forwaded from LSQ stores.
Definition at line 542 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::read(), and LSQUnit< Impl >::regStats().
lsqID
template<class Impl> ThreadID LSQUnit< Impl >::lsqID private
The LSQUnit thread id.
Definition at line 472 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::init(), LSQUnit< Impl >::name(), LSQUnit< Impl >::read(), and LSQUnit< Impl >::writebackStores().
lsqIgnoredResponses
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqIgnoredResponses private
Total number of responses from the memory system that are ignored due to the instruction already being squashed.
Definition at line 552 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats(), and LSQUnit< Impl >::writeback().
lsqMemOrderViolation
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqMemOrderViolation private
Tota number of memory ordering violations.
Definition at line 555 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkViolations(), and LSQUnit< Impl >::regStats().
lsqRescheduledLoads
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqRescheduledLoads private
Number of loads that were rescheduled.
Definition at line 567 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::read(), and LSQUnit< Impl >::regStats().
lsqSquashedLoads
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqSquashedLoads private
Total number of squashed loads.
Definition at line 548 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats(), and LSQUnit< Impl >::squash().
lsqSquashedStores
template<class Impl> Stats::Scalar LSQUnit< Impl >::lsqSquashedStores private
Total number of squashed stores.
Definition at line 558 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::regStats(), and LSQUnit< Impl >::squash().
MaxDataBytes
template<class Impl> constexpr auto LSQUnit< Impl >::MaxDataBytes = MaxVecRegLenInBytes static
Definition at line 84 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::read().
memDepViolator
template<class Impl> DynInstPtr LSQUnit< Impl >::memDepViolator private
The oldest load that caused a memory ordering violation.
Definition at line 526 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkViolations(), LSQUnit< Impl >::getMemDepViolator(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::violation().
needsTSO
template<class Impl> bool LSQUnit< Impl >::needsTSO private
Flag for memory model.
Definition at line 536 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::checkSnoop(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::init(), LSQUnit< Impl >::storePostSend(), and LSQUnit< Impl >::writebackStores().
pendingRequest
template<class Impl> LSQRequest* LSQUnit< Impl >::pendingRequest private
The packet that is pending free cache ports.
Definition at line 533 of file lsq_unit.hh.
retryPkt
template<class Impl> PacketPtr LSQUnit< Impl >::retryPkt private
The packet that needs to be retried.
Definition at line 517 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::drainSanityCheck(), and LSQUnit< Impl >::resetState().
stalled
template<class Impl> bool LSQUnit< Impl >::stalled private
Whether or not the LSQ is stalled.
Definition at line 508 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::isStalled(), LSQUnit< Impl >::read(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::storePostSend().
stallingLoadIdx
template<class Impl> int LSQUnit< Impl >::stallingLoadIdx private
The index of the above store.
Definition at line 514 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::read(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::storePostSend().
stallingStoreIsn
template<class Impl> InstSeqNum LSQUnit< Impl >::stallingStoreIsn private
The store that causes the stall due to partial store to load forwarding.
Definition at line 512 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::read(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::storePostSend().
storeInFlight
template<class Impl> bool LSQUnit< Impl >::storeInFlight private
Whether or not a store is in flight.
Definition at line 523 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::storePostSend(), and LSQUnit< Impl >::writebackStores().
storeQueue
template<class Impl> CircularQueue<SQEntry> LSQUnit< Impl >::storeQueue
The store queue.
Definition at line 475 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::commitStores(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::dumpInsts(), LSQUnit< Impl >::executeStore(), LSQUnit< Impl >::insertLoad(), LSQUnit< Impl >::insertStore(), LSQ< Impl >::LSQRequest::install(), LSQUnit< Impl >::numFreeStoreEntries(), LSQUnit< Impl >::read(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::sqFull(), LSQUnit< Impl >::squash(), LSQUnit< Impl >::write(), and LSQUnit< Impl >::writebackStores().
stores
template<class Impl> int LSQUnit< Impl >::stores private
The number of store instructions in the SQ.
Definition at line 492 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::commitStores(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::dumpInsts(), LSQUnit< Impl >::executeStore(), LSQUnit< Impl >::getCount(), LSQUnit< Impl >::insertStore(), LSQUnit< Impl >::numFreeStoreEntries(), LSQUnit< Impl >::numStores(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::sqEmpty(), LSQUnit< Impl >::squash(), and LSQUnit< Impl >::writebackStores().
storesToWB
template<class Impl> int LSQUnit< Impl >::storesToWB private
The number of store instructions in the SQ waiting to writeback.
Definition at line 494 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::commitStores(), LSQUnit< Impl >::completeStore(), LSQUnit< Impl >::drainSanityCheck(), LSQUnit< Impl >::executeStore(), LSQUnit< Impl >::hasStoresToWB(), LSQUnit< Impl >::numStoresToWB(), LSQUnit< Impl >::resetState(), and LSQUnit< Impl >::writebackStores().
storeWBIt
template<class Impl> StoreQueue::iterator LSQUnit< Impl >::storeWBIt private
The index of the first instruction that may be ready to be written back, and has not yet been written back.
Definition at line 499 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::read(), LSQUnit< Impl >::resetState(), LSQUnit< Impl >::storePostSend(), LSQUnit< Impl >::trySendPacket(), LSQUnit< Impl >::willWB(), LSQUnit< Impl >::writebackBlockedStore(), and LSQUnit< Impl >::writebackStores().
The documentation for this class was generated from the following files:
cpu/o3/lsq_unit.hh
cpu/o3/lsq_unit_impl.hh