gem5: Set Class Reference
Set Class Reference
#include <Set.hh>
Public Member Functions
Set ()
Set (int size)
Set (const Set &obj)
~Set ()
Set & operator= (const Set &obj)
void add (NodeID index)
void addSet (const Set &obj)
void remove (NodeID index)
void removeSet (const Set &obj)
void clear ()
void broadcast ()
int count () const
bool isEqual (const Set &obj) const
Set OR (const Set &obj) const
Set AND (const Set &obj) const
bool intersectionIsEmpty (const Set &obj) const
bool isSuperset (const Set &test) const
bool isSubset (const Set &test) const
bool isElement (NodeID element) const
bool isBroadcast () const
bool isEmpty () const
NodeID smallestElement () const
bool elementAt (int index) const
int getSize () const
void setSize (int size)
void print (std::ostream &out) const
Private Attributes
int m_nSize
std::bitset< NUMBER_BITS_PER_SET > bits
Detailed Description
Definition at line 42 of file Set.hh.
Constructor & Destructor Documentation
Set() [1/3]
Set::Set () inline
Definition at line 51 of file Set.hh.
Set() [2/3]
Set::Set (int size) inline
Definition at line 53 of file Set.hh.
References fatal.
Set() [3/3]
Set::Set (const Set & obj) inline
Definition at line 61 of file Set.hh.
~Set()
Set::~Set () inline
Definition at line 62 of file Set.hh.
Member Function Documentation
add()
void Set::add (NodeID index) inline
Definition at line 72 of file Set.hh.
Referenced by AccessTraceForAddress::update().
addSet()
void Set::addSet (const Set & obj) inline
Definition at line 82 of file Set.hh.
References bits, and m_nSize.
Referenced by AddressProfiler::profileGetS(), and AddressProfiler::profileGetX().
AND()
Set Set::AND (const Set & obj) const inline
Definition at line 147 of file Set.hh.
References bits, m_nSize, and MipsISA::r.
broadcast()
void Set::broadcast () inline
Definition at line 112 of file Set.hh.
References ArmISA::j.
clear()
void Set::clear () inline
Definition at line 107 of file Set.hh.
count()
int Set::count () const inline
Definition at line 123 of file Set.hh.
Referenced by AccessTraceForAddress::getTouchedBy(), AccessTraceForAddress::print(), AddressProfiler::profileGetS(), and AddressProfiler::profileGetX().
elementAt()
bool Set::elementAt (int index) const inline
Definition at line 200 of file Set.hh.
References MipsISA::index.
getSize()
int Set::getSize () const inline
Definition at line 202 of file Set.hh.
References m_nSize.
intersectionIsEmpty()
bool Set::intersectionIsEmpty (const Set & obj) const inline
Definition at line 157 of file Set.hh.
References bits, and MipsISA::r.
isBroadcast()
bool Set::isBroadcast () const inline
Definition at line 183 of file Set.hh.
References m_nSize.
isElement()
bool Set::isElement (NodeID element) const inline
Definition at line 177 of file Set.hh.
isEmpty()
bool Set::isEmpty () const inline
Definition at line 188 of file Set.hh.
isEqual()
bool Set::isEqual (const Set & obj) const inline
Definition at line 129 of file Set.hh.
References bits, and m_nSize.
isSubset()
bool Set::isSubset (const Set & test) const inline
Definition at line 175 of file Set.hh.
References isSuperset().
isSuperset()
bool Set::isSuperset (const Set & test) const inline
Definition at line 168 of file Set.hh.
References bits, m_nSize, and MipsISA::r.
Referenced by isSubset().
operator=()
Set& Set::operator= (const Set & obj) inline
Definition at line 64 of file Set.hh.
References bits, and m_nSize.
OR()
Set Set::OR (const Set & obj) const inline
Definition at line 137 of file Set.hh.
References bits, m_nSize, and MipsISA::r.
print()
void Set::print (std::ostream & out) const inline
Definition at line 215 of file Set.hh.
Referenced by operator<<().
remove()
void Set::remove (NodeID index) inline
Definition at line 92 of file Set.hh.
References MipsISA::index.
Referenced by AddressProfiler::profileGetS(), and AddressProfiler::profileGetX().
removeSet()
void Set::removeSet (const Set & obj) inline
Definition at line 101 of file Set.hh.
References bits, and m_nSize.
setSize()
void Set::setSize (int size) inline
Definition at line 205 of file Set.hh.
References fatal.
smallestElement()
NodeID Set::smallestElement () const inline
Definition at line 190 of file Set.hh.
References ArmISA::i, m_nSize, and panic.
Member Data Documentation
bits
std::bitset<NUMBER_BITS_PER_SET> Set::bits private
Definition at line 48 of file Set.hh.
Referenced by addSet(), AND(), intersectionIsEmpty(), isEqual(), isSuperset(), operator=(), OR(), and removeSet().
m_nSize
int Set::m_nSize private
Definition at line 47 of file Set.hh.
Referenced by addSet(), AND(), getSize(), isBroadcast(), isEqual(), isSuperset(), operator=(), OR(), removeSet(), and smallestElement().
The documentation for this class was generated from the following file:
mem/ruby/common/Set.hh