gem5: sc_dt::sc_ufix Class Reference
sc_dt::sc_ufix Class Reference
#include <sc_ufix.hh>
Public Member Functions
sc_ufix (sc_fxnum_observer *=0)
sc_ufix (int, int, sc_fxnum_observer *=0)
sc_ufix (sc_q_mode, sc_o_mode, sc_fxnum_observer *=0)
sc_ufix (sc_q_mode, sc_o_mode, int, sc_fxnum_observer *=0)
sc_ufix (int, int, sc_q_mode, sc_o_mode, sc_fxnum_observer *=0)
sc_ufix (int, int, sc_q_mode, sc_o_mode, int, sc_fxnum_observer *=0)
sc_ufix (const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (int, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (int, int, sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (int, int, sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (const sc_fxtype_params &, sc_fxnum_observer *=0)
sc_ufix (const sc_fxtype_params &, const sc_fxcast_switch &, sc_fxnum_observer *=0)
sc_ufix (const sc_ufix &)
const sc_ufix operator~ () const
sc_ufix & operator= (const sc_ufix &)
const sc_fxval operator++ (int)
const sc_fxval operator-- (int)
sc_ufix & operator++ ()
sc_ufix & operator-- ()
Public Member Functions inherited from sc_dt::sc_fxnum
const sc_fxval operator- () const
const sc_fxval operator+ () const
const sc_fxval operator++ (int)
const sc_fxval operator-- (int)
sc_fxnum & operator++ ()
sc_fxnum & operator-- ()
const sc_fxnum_bitref operator[] (int) const
sc_fxnum_bitref operator[] (int)
const sc_fxnum_bitref bit (int) const
sc_fxnum_bitref bit (int)
const sc_fxnum_subref operator() (int, int) const
sc_fxnum_subref operator() (int, int)
const sc_fxnum_subref range (int, int) const
sc_fxnum_subref range (int, int)
const sc_fxnum_subref operator() () const
sc_fxnum_subref operator() ()
const sc_fxnum_subref range () const
sc_fxnum_subref range ()
operator double () const
short to_short () const
unsigned short to_ushort () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
float to_float () const
double to_double () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
const std::string to_string (sc_fmt) const
const std::string to_string (sc_numrep, sc_fmt) const
const std::string to_string (sc_numrep, bool, sc_fmt) const
const std::string to_dec () const
const std::string to_bin () const
const std::string to_oct () const
const std::string to_hex () const
bool is_neg () const
bool is_zero () const
bool is_normal () const
bool quantization_flag () const
bool overflow_flag () const
const sc_fxval value () const
int wl () const
int iwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
const sc_fxtype_params & type_params () const
const sc_fxcast_switch & cast_switch () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
void observer_read () const
bool get_bit (int) const
Friends
void b_not (sc_ufix &, const sc_ufix &)
const sc_ufix operator& (const sc_ufix &, const sc_ufix &)
const sc_ufix operator& (const sc_ufix &, const sc_ufix_fast &)
const sc_ufix operator& (const sc_ufix_fast &, const sc_ufix &)
const sc_ufix operator| (const sc_ufix &, const sc_ufix &)
const sc_ufix operator| (const sc_ufix &, const sc_ufix_fast &)
const sc_ufix operator| (const sc_ufix_fast &, const sc_ufix &)
const sc_ufix operator^ (const sc_ufix &, const sc_ufix &)
const sc_ufix operator^ (const sc_ufix &, const sc_ufix_fast &)
const sc_ufix operator^ (const sc_ufix_fast &, const sc_ufix &)
void b_and (sc_ufix &, const sc_ufix &, const sc_ufix &)
void b_and (sc_ufix &, const sc_ufix &, const sc_ufix_fast &)
void b_and (sc_ufix &, const sc_ufix_fast &, const sc_ufix &)
void b_or (sc_ufix &, const sc_ufix &, const sc_ufix &)
void b_or (sc_ufix &, const sc_ufix &, const sc_ufix_fast &)
void b_or (sc_ufix &, const sc_ufix_fast &, const sc_ufix &)
void b_xor (sc_ufix &, const sc_ufix &, const sc_ufix &)
void b_xor (sc_ufix &, const sc_ufix &, const sc_ufix_fast &)
void b_xor (sc_ufix &, const sc_ufix_fast &, const sc_ufix &)
Additional Inherited Members
Protected Member Functions inherited from sc_dt::sc_fxnum
sc_fxnum_observer * observer () const
void cast ()
sc_fxnum (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &, sc_fxnum_observer *)
~sc_fxnum ()
const scfx_rep * get_rep () const
bool set_bit (int, bool)
bool get_slice (int, int, sc_bv_base &) const
bool set_slice (int, int, const sc_bv_base &)
sc_fxnum_observer * lock_observer () const
void unlock_observer (sc_fxnum_observer *) const
Detailed Description
Definition at line 69 of file sc_ufix.hh.
Constructor & Destructor Documentation
sc_ufix() [1/15]
sc_dt::sc_ufix::sc_ufix (sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 416 of file sc_ufix.hh.
Referenced by operator~().
sc_ufix() [2/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, sc_fxnum_observer * observer_ = 0) inline
Definition at line 420 of file sc_ufix.hh.
sc_ufix() [3/15]
sc_dt::sc_ufix::sc_ufix (sc_q_mode qm, sc_o_mode om, sc_fxnum_observer * observer_ = 0) inline
Definition at line 425 of file sc_ufix.hh.
sc_ufix() [4/15]
sc_dt::sc_ufix::sc_ufix (sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_observer * observer_ = 0) inline
Definition at line 432 of file sc_ufix.hh.
sc_ufix() [5/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, sc_fxnum_observer * observer_ = 0) inline
Definition at line 438 of file sc_ufix.hh.
sc_ufix() [6/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_observer * observer_ = 0) inline
Definition at line 444 of file sc_ufix.hh.
sc_ufix() [7/15]
sc_dt::sc_ufix::sc_ufix (const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 450 of file sc_ufix.hh.
sc_ufix() [8/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 455 of file sc_ufix.hh.
sc_ufix() [9/15]
sc_dt::sc_ufix::sc_ufix (sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 460 of file sc_ufix.hh.
sc_ufix() [10/15]
sc_dt::sc_ufix::sc_ufix (sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 466 of file sc_ufix.hh.
sc_ufix() [11/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 472 of file sc_ufix.hh.
sc_ufix() [12/15]
sc_dt::sc_ufix::sc_ufix (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 479 of file sc_ufix.hh.
sc_ufix() [13/15]
sc_dt::sc_ufix::sc_ufix (const sc_fxtype_params & type_params_, sc_fxnum_observer * observer_ = 0) inline explicit
Definition at line 486 of file sc_ufix.hh.
sc_ufix() [14/15]
sc_dt::sc_ufix::sc_ufix (const sc_fxtype_params & type_params_, const sc_fxcast_switch & cast_sw, sc_fxnum_observer * observer_ = 0) inline
Definition at line 491 of file sc_ufix.hh.
References DEFN_CTORS_T_A, and DEFN_CTORS_T_B.
sc_ufix() [15/15]
sc_dt::sc_ufix::sc_ufix (const sc_ufix & a) inline
Definition at line 692 of file sc_ufix.hh.
Member Function Documentation
operator++() [1/2]
const sc_fxval sc_dt::sc_ufix::operator++ (int) inline
Definition at line 858 of file sc_ufix.hh.
References sc_dt::sc_fxnum::sc_fxval.
operator++() [2/2]
sc_ufix & sc_dt::sc_ufix::operator++ () inline
Definition at line 870 of file sc_ufix.hh.
References sc_dt::sc_fxnum::operator++().
Referenced by sc_dt::sc_ufixed< W, I, Q, O, N >::operator++().
operator--() [1/2]
const sc_fxval sc_dt::sc_ufix::operator-- (int) inline
Definition at line 864 of file sc_ufix.hh.
References sc_dt::sc_fxnum::sc_fxval.
operator--() [2/2]
sc_ufix & sc_dt::sc_ufix::operator-- () inline
Definition at line 877 of file sc_ufix.hh.
References sc_dt::sc_fxnum::operator--().
Referenced by sc_dt::sc_ufixed< W, I, Q, O, N >::operator--().
operator=()
sc_ufix & sc_dt::sc_ufix::operator= (const sc_ufix & a) inline
Definition at line 782 of file sc_ufix.hh.
References DEFN_ASN_OP, and DEFN_ASN_OP_T.
Referenced by sc_dt::sc_ufixed< W, I, Q, O, N >::operator=().
operator~()
const sc_ufix sc_dt::sc_ufix::operator~ () const inline
Definition at line 698 of file sc_ufix.hh.
References ArmISA::c, sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::iwl(), SC_FXNUM_OBSERVER_READ_, sc_ufix(), sc_dt::sc_fxnum::set_bit(), and sc_dt::sc_fxnum::wl().
Friends And Related Function Documentation
b_and [1/3]
void b_and (sc_ufix & , const sc_ufix & , const sc_ufix &) friend
Referenced by sc_dt::b_not().
b_and [2/3]
void b_and (sc_ufix & , const sc_ufix & , const sc_ufix_fast &) friend
b_and [3/3]
void b_and (sc_ufix & , const sc_ufix_fast & , const sc_ufix &) friend
b_not
void b_not (sc_ufix & c, const sc_ufix & a) friend
Definition at line 711 of file sc_ufix.hh.
b_or [1/3]
void b_or (sc_ufix & , const sc_ufix & , const sc_ufix &) friend
Referenced by sc_dt::b_not().
b_or [2/3]
void b_or (sc_ufix & , const sc_ufix & , const sc_ufix_fast &) friend
b_or [3/3]
void b_or (sc_ufix & , const sc_ufix_fast & , const sc_ufix &) friend
b_xor [1/3]
void b_xor (sc_ufix & , const sc_ufix & , const sc_ufix &) friend
Referenced by sc_dt::b_not().
b_xor [2/3]
void b_xor (sc_ufix & , const sc_ufix & , const sc_ufix_fast &) friend
b_xor [3/3]
void b_xor (sc_ufix & , const sc_ufix_fast & , const sc_ufix &) friend
operator& [1/3]
const sc_ufix operator & (const sc_ufix & , const sc_ufix &) friend
operator& [2/3]
const sc_ufix operator & (const sc_ufix & , const sc_ufix_fast &) friend
operator& [3/3]
const sc_ufix operator & (const sc_ufix_fast & , const sc_ufix &) friend
operator^ [1/3]
const sc_ufix operator^ (const sc_ufix & , const sc_ufix &) friend
operator^ [2/3]
const sc_ufix operator^ (const sc_ufix & , const sc_ufix_fast &) friend
operator^ [3/3]
const sc_ufix operator^ (const sc_ufix_fast & , const sc_ufix &) friend
operator| [1/3]
const sc_ufix operator| (const sc_ufix & , const sc_ufix &) friend
operator| [2/3]
const sc_ufix operator| (const sc_ufix & , const sc_ufix_fast &) friend
operator| [3/3]
const sc_ufix operator| (const sc_ufix_fast & , const sc_ufix &) friend
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_ufix.hh