gem5: sc_gem5::StaticSensitivity Class Reference
sc_gem5::StaticSensitivity Class Reference
#include <sensitivity.hh>
Public Member Functions
Category category () override
Public Member Functions inherited from sc_gem5::Sensitivity
virtual void clear ()=0
void satisfy ()
virtual bool notifyWork (Event *e)
bool notify (Event *e)
bool ofMethod ()
Protected Member Functions
StaticSensitivity (Process *p)
void addToEvent (const ::sc_core::sc_event *e) override
void delFromEvent (const ::sc_core::sc_event *e) override
Protected Member Functions inherited from sc_gem5::Sensitivity
Sensitivity (Process *p)
virtual ~Sensitivity ()
Additional Inherited Members
Public Types inherited from sc_gem5::Sensitivity
enum Category { Static, Dynamic }
Protected Attributes inherited from sc_gem5::Sensitivity
Process * process
Detailed Description
Definition at line 113 of file sensitivity.hh.
Constructor & Destructor Documentation
StaticSensitivity()
sc_gem5::StaticSensitivity::StaticSensitivity (Process * p) inline protected
Definition at line 116 of file sensitivity.hh.
References ArmISA::e.
Member Function Documentation
addToEvent()
void sc_gem5::StaticSensitivity::addToEvent (const ::sc_core::sc_event * e) override protected virtual
Implements sc_gem5::Sensitivity.
Definition at line 107 of file sensitivity.cc.
References sc_gem5::Event::addSensitivity(), and sc_gem5::Event::getFromScEvent().
category()
Category sc_gem5::StaticSensitivity::category () inline override virtual
Implements sc_gem5::Sensitivity.
Definition at line 122 of file sensitivity.hh.
delFromEvent()
void sc_gem5::StaticSensitivity::delFromEvent (const ::sc_core::sc_event * e) override protected virtual
Implements sc_gem5::Sensitivity.
Definition at line 113 of file sensitivity.cc.
References sc_gem5::Event::delSensitivity(), and sc_gem5::Event::getFromScEvent().
The documentation for this class was generated from the following files:
systemc/core/sensitivity.hh
systemc/core/sensitivity.cc