gem5: sc_gem5::Channel Class Reference
sc_gem5::Channel Class Reference
#include <channel.hh>
Public Member Functions
Channel (sc_core::sc_prim_channel *_sc_chan)
virtual ~Channel ()
void requestUpdate ()
void asyncRequestUpdate ()
void update ()
sc_core::sc_prim_channel * sc_chan ()
Public Member Functions inherited from sc_gem5::ListNode
ListNode ()
virtual ~ListNode ()
void popListNode ()
Private Attributes
sc_core::sc_prim_channel * _sc_chan
Additional Inherited Members
Public Attributes inherited from sc_gem5::ListNode
ListNode * nextListNode
ListNode * prevListNode
Detailed Description
Definition at line 41 of file channel.hh.
Constructor & Destructor Documentation
Channel()
sc_gem5::Channel::Channel (sc_core::sc_prim_channel * _sc_chan)
Definition at line 37 of file channel.cc.
References sc_gem5::allChannels.
~Channel()
sc_gem5::Channel::~Channel () virtual
Definition at line 42 of file channel.cc.
References sc_gem5::allChannels, and sc_gem5::ListNode::popListNode().
Member Function Documentation
asyncRequestUpdate()
void sc_gem5::Channel::asyncRequestUpdate ()
Definition at line 55 of file channel.cc.
References sc_gem5::Scheduler::asyncRequestUpdate(), and sc_gem5::scheduler.
Referenced by sc_core::sc_prim_channel::async_request_update().
requestUpdate()
void sc_gem5::Channel::requestUpdate ()
Definition at line 49 of file channel.cc.
References sc_gem5::Scheduler::requestUpdate(), and sc_gem5::scheduler.
Referenced by sc_core::sc_prim_channel::request_update().
sc_chan()
sc_core::sc_prim_channel* sc_gem5::Channel::sc_chan () inline
Definition at line 52 of file channel.hh.
References _sc_chan.
update()
void sc_gem5::Channel::update () inline
Definition at line 50 of file channel.hh.
References sc_core::sc_prim_channel::update().
Referenced by sc_gem5::Scheduler::runUpdate().
Member Data Documentation
_sc_chan
sc_core::sc_prim_channel* sc_gem5::Channel::_sc_chan private
Definition at line 55 of file channel.hh.
Referenced by sc_chan().
The documentation for this class was generated from the following files:
systemc/core/channel.hh
systemc/core/channel.cc