gem5: BaseRemoteGDB Class Reference
BaseRemoteGDB Class Reference abstract
#include <remote_gdb.hh>
Classes
struct GdbCommand
class SocketEvent
class TrapEvent
Public Member Functions
bool breakpoint ()
void replaceThreadContext (ThreadContext *tc)
virtual ~BaseRemoteGDB ()
BaseRemoteGDB (System *system, ThreadContext *context, int _port)
virtual ~BaseRemoteGDB ()
std::string name ()
void listen ()
void connect ()
int port () const
void attach (int fd)
void detach ()
bool isAttached ()
void replaceThreadContext (ThreadContext *_tc)
bool trap (int type)
bool breakpoint ()
Protected Member Functions
ThreadContext * context ()
System * system ()
void encodeBinaryData (const std::string &unencoded, std::string &encoded) const
void encodeXferResponse (const std::string &unencoded, std::string &encoded, size_t offset, size_t unencoded_length) const
virtual bool checkBpLen (size_t len)
virtual BaseGdbRegCache * gdbRegs ()=0
virtual bool acc (Addr addr, size_t len)=0
virtual std::vector< std::string > availableFeatures () const
virtual bool getXferFeaturesRead (const std::string &annex, std::string &output)
Get an XML target description.
Private Types
typedef SocketEvent<&BaseRemoteGDB::connectWrapper > ConnectEvent
typedef SocketEvent<&BaseRemoteGDB::incomingData > DataEvent
Private Member Functions
void incomingData (int revent)
void connectWrapper (int revent)
uint8_t getbyte ()
void putbyte (uint8_t b)
void recv (std::vector< char > &bp)
void send (const char *data)
bool read (Addr addr, size_t size, char *data)
bool write (Addr addr, size_t size, const char *data)
template<class T >
T read (Addr addr)
template<class T >
void write (Addr addr, T data)
void singleStep ()
void clearSingleStep ()
void setSingleStep ()
void scheduleInstCommitEvent (Event *ev, int delta)
Schedule an event which will be triggered "delta" instructions later.
void descheduleInstCommitEvent (Event *ev)
Deschedule an instruction count based event.
void insertSoftBreak (Addr addr, size_t len)
void removeSoftBreak (Addr addr, size_t len)
void insertHardBreak (Addr addr, size_t len)
void removeHardBreak (Addr addr, size_t len)
void clearTempBreakpoint (Addr &bkpt)
void setTempBreakpoint (Addr bkpt)
bool cmd_unsupported (GdbCommand::Context &ctx)
bool cmd_signal (GdbCommand::Context &ctx)
bool cmd_cont (GdbCommand::Context &ctx)
bool cmd_async_cont (GdbCommand::Context &ctx)
bool cmd_detach (GdbCommand::Context &ctx)
bool cmd_reg_r (GdbCommand::Context &ctx)
bool cmd_reg_w (GdbCommand::Context &ctx)
bool cmd_set_thread (GdbCommand::Context &ctx)
bool cmd_mem_r (GdbCommand::Context &ctx)
bool cmd_mem_w (GdbCommand::Context &ctx)
bool cmd_query_var (GdbCommand::Context &ctx)
bool cmd_step (GdbCommand::Context &ctx)
bool cmd_async_step (GdbCommand::Context &ctx)
bool cmd_clr_hw_bkpt (GdbCommand::Context &ctx)
bool cmd_set_hw_bkpt (GdbCommand::Context &ctx)
Private Attributes
friend ConnectEvent
friend DataEvent
ConnectEvent * connectEvent
DataEvent * dataEvent
ListenSocket listener
int _port
int fd
bool active
bool attached
System * sys
ThreadContext * tc
BaseGdbRegCache * regCachePtr
BaseRemoteGDB::TrapEvent trapEvent
EventWrapper< BaseRemoteGDB, &BaseRemoteGDB::singleStep > singleStepEvent
Static Private Attributes
static std::map< char, GdbCommand > command_map
Friends
class HardBreakpoint
Detailed Description
Definition at line 45 of file remote_gdb.hh.
Member Typedef Documentation
ConnectEvent
typedef SocketEvent<&BaseRemoteGDB::connectWrapper> BaseRemoteGDB::ConnectEvent private
Definition at line 166 of file remote_gdb.hh.
DataEvent
typedef SocketEvent<&BaseRemoteGDB::incomingData> BaseRemoteGDB::DataEvent private
Definition at line 167 of file remote_gdb.hh.
Constructor & Destructor Documentation
~BaseRemoteGDB() [1/2]
BaseRemoteGDB::~BaseRemoteGDB () inline virtual
Definition at line 53 of file remote_gdb.hh.
Referenced by BaseRemoteGDB().
BaseRemoteGDB()
BaseRemoteGDB::BaseRemoteGDB (System * system, ThreadContext * context, int _port)
Definition at line 322 of file remote_gdb.cc.
References connectEvent, dataEvent, and ~BaseRemoteGDB().
~BaseRemoteGDB() [2/2]
virtual BaseRemoteGDB::~BaseRemoteGDB () virtual
Member Function Documentation
acc()
virtual bool BaseRemoteGDB::acc (Addr addr, size_t len) protected pure virtual
Implemented in ArmISA::RemoteGDB, X86ISA::RemoteGDB, RiscvISA::RemoteGDB, AlphaISA::RemoteGDB, PowerISA::RemoteGDB, MipsISA::RemoteGDB, and SparcISA::RemoteGDB.
Referenced by cmd_mem_r(), and cmd_mem_w().
attach()
void BaseRemoteGDB::attach (int fd)
Definition at line 387 of file remote_gdb.cc.
References attached, dataEvent, DPRINTFN, ArmISA::f, fd, pollQueue, and PollQueue::schedule().
Referenced by connect().
availableFeatures()
std::vector< std::string > BaseRemoteGDB::availableFeatures () const protected virtual
Reimplemented in ArmISA::RemoteGDB.
Definition at line 1007 of file remote_gdb.cc.
Referenced by cmd_query_var().
breakpoint() [1/2]
bool BaseRemoteGDB::breakpoint () inline
Definition at line 50 of file remote_gdb.hh.
breakpoint() [2/2]
bool BaseRemoteGDB::breakpoint () inline
Definition at line 143 of file remote_gdb.hh.
checkBpLen()
bool BaseRemoteGDB::checkBpLen (size_t len) protected virtual
Reimplemented in X86ISA::RemoteGDB, and RiscvISA::RemoteGDB.
Definition at line 826 of file remote_gdb.cc.
Referenced by insertHardBreak(), insertSoftBreak(), removeHardBreak(), and removeSoftBreak().
clearSingleStep()
void BaseRemoteGDB::clearSingleStep () private
Definition at line 674 of file remote_gdb.cc.
References descheduleInstCommitEvent(), and singleStepEvent.
Referenced by cmd_async_cont(), cmd_cont(), detach(), and trap().
clearTempBreakpoint()
void BaseRemoteGDB::clearTempBreakpoint (Addr & bkpt) private
Definition at line 739 of file remote_gdb.cc.
References DPRINTF, and removeHardBreak().
cmd_async_cont()
bool BaseRemoteGDB::cmd_async_cont (GdbCommand::Context & ctx) private
Definition at line 860 of file remote_gdb.cc.
References clearSingleStep(), BaseRemoteGDB::GdbCommand::Context::data, MipsISA::p, ThreadContext::pcState(), and tc.
Referenced by descheduleInstCommitEvent().
cmd_async_step()
bool BaseRemoteGDB::cmd_async_step (GdbCommand::Context & ctx) private
Definition at line 1045 of file remote_gdb.cc.
References BaseRemoteGDB::GdbCommand::Context::data, MipsISA::p, ThreadContext::pcState(), setSingleStep(), and tc.
Referenced by descheduleInstCommitEvent().
cmd_clr_hw_bkpt()
bool BaseRemoteGDB::cmd_clr_hw_bkpt (GdbCommand::Context & ctx) private
Definition at line 1070 of file remote_gdb.cc.
References addr, BaseRemoteGDB::GdbCommand::Context::data, DPRINTF, ArmISA::len, MipsISA::p, removeHardBreak(), removeSoftBreak(), and send().
Referenced by descheduleInstCommitEvent().
cmd_cont()
bool BaseRemoteGDB::cmd_cont (GdbCommand::Context & ctx) private
Definition at line 848 of file remote_gdb.cc.
References clearSingleStep(), BaseRemoteGDB::GdbCommand::Context::data, BaseRemoteGDB::GdbCommand::Context::len, MipsISA::p, ThreadContext::pcState(), and tc.
Referenced by descheduleInstCommitEvent().
cmd_detach()
bool BaseRemoteGDB::cmd_detach (GdbCommand::Context & ctx) private
Definition at line 873 of file remote_gdb.cc.
References detach().
Referenced by descheduleInstCommitEvent().
cmd_mem_r()
bool BaseRemoteGDB::cmd_mem_r (GdbCommand::Context & ctx) private
Definition at line 914 of file remote_gdb.cc.
References acc(), addr, BaseRemoteGDB::GdbCommand::Context::data, ArmISA::len, MipsISA::p, read(), and send().
Referenced by descheduleInstCommitEvent().
cmd_mem_w()
bool BaseRemoteGDB::cmd_mem_w (GdbCommand::Context & ctx) private
Definition at line 938 of file remote_gdb.cc.
References acc(), addr, BaseRemoteGDB::GdbCommand::Context::data, BaseRemoteGDB::GdbCommand::Context::len, ArmISA::len, MipsISA::p, send(), and write().
Referenced by descheduleInstCommitEvent().
cmd_query_var()
bool BaseRemoteGDB::cmd_query_var (GdbCommand::Context & ctx) private
Definition at line 962 of file remote_gdb.cc.
References availableFeatures(), BaseRemoteGDB::GdbCommand::Context::data, ArmISA::e, encodeXferResponse(), getXferFeaturesRead(), BaseRemoteGDB::GdbCommand::Context::len, length, ArmISA::offset, ArmISA::s, and send().
Referenced by descheduleInstCommitEvent().
cmd_reg_r()
bool BaseRemoteGDB::cmd_reg_r (GdbCommand::Context & ctx) private
Definition at line 880 of file remote_gdb.cc.
References BaseGdbRegCache::data(), regCachePtr, send(), and BaseGdbRegCache::size().
Referenced by descheduleInstCommitEvent().
cmd_reg_w()
bool BaseRemoteGDB::cmd_reg_w (GdbCommand::Context & ctx) private
Definition at line 890 of file remote_gdb.cc.
References BaseGdbRegCache::data(), BaseRemoteGDB::GdbCommand::Context::data, MipsISA::p, regCachePtr, send(), BaseGdbRegCache::setRegs(), BaseGdbRegCache::size(), and tc.
Referenced by descheduleInstCommitEvent().
cmd_set_hw_bkpt()
bool BaseRemoteGDB::cmd_set_hw_bkpt (GdbCommand::Context & ctx) private
Definition at line 1103 of file remote_gdb.cc.
References addr, BaseRemoteGDB::GdbCommand::Context::data, DPRINTF, insertHardBreak(), insertSoftBreak(), ArmISA::len, MipsISA::p, and send().
Referenced by descheduleInstCommitEvent().
cmd_set_thread()
bool BaseRemoteGDB::cmd_set_thread (GdbCommand::Context & ctx) private
Definition at line 904 of file remote_gdb.cc.
References BaseRemoteGDB::GdbCommand::Context::data, MipsISA::p, and send().
Referenced by descheduleInstCommitEvent().
cmd_signal()
bool BaseRemoteGDB::cmd_signal (GdbCommand::Context & ctx) private
Definition at line 841 of file remote_gdb.cc.
References csprintf(), send(), and BaseRemoteGDB::GdbCommand::Context::type.
Referenced by descheduleInstCommitEvent().
cmd_step()
bool BaseRemoteGDB::cmd_step (GdbCommand::Context & ctx) private
Definition at line 1058 of file remote_gdb.cc.
References BaseRemoteGDB::GdbCommand::Context::data, BaseRemoteGDB::GdbCommand::Context::len, MipsISA::p, ThreadContext::pcState(), setSingleStep(), and tc.
Referenced by descheduleInstCommitEvent().
cmd_unsupported()
bool BaseRemoteGDB::cmd_unsupported (GdbCommand::Context & ctx) private
Definition at line 832 of file remote_gdb.cc.
References BaseRemoteGDB::GdbCommand::Context::cmd, BaseRemoteGDB::GdbCommand::Context::data, DDUMP, DPRINTF, BaseRemoteGDB::GdbCommand::Context::len, and BaseRemoteGDB::GdbCommand::name.
Referenced by descheduleInstCommitEvent().
connect()
void BaseRemoteGDB::connect ()
Definition at line 363 of file remote_gdb.cc.
References ListenSocket::accept(), attach(), isAttached(), ListenSocket::islistening(), listener, and panic_if.
connectWrapper()
void BaseRemoteGDB::connectWrapper (int revent) inline private
Definition at line 150 of file remote_gdb.hh.
context()
ThreadContext* BaseRemoteGDB::context () inline protected
Definition at line 287 of file remote_gdb.hh.
Referenced by SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), PowerISA::RemoteGDB::acc(), AlphaISA::RemoteGDB::acc(), RiscvISA::RemoteGDB::acc(), X86ISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), SparcISA::RemoteGDB::gdbRegs(), ArmISA::RemoteGDB::gdbRegs(), X86ISA::RemoteGDB::gdbRegs(), ArmISA::RemoteGDB::getXferFeaturesRead(), and AlphaISA::RemoteGDB::AlphaGdbRegCache::name().
descheduleInstCommitEvent()
void BaseRemoteGDB::descheduleInstCommitEvent (Event * ev) private
Deschedule an instruction count based event.
Definition at line 762 of file remote_gdb.cc.
References cmd_async_cont(), cmd_async_step(), cmd_clr_hw_bkpt(), cmd_cont(), cmd_detach(), cmd_mem_r(), cmd_mem_w(), cmd_query_var(), cmd_reg_r(), cmd_reg_w(), cmd_set_hw_bkpt(), cmd_set_thread(), cmd_signal(), cmd_step(), cmd_unsupported(), command_map, ThreadContext::descheduleInstCountEvent(), Event::scheduled(), and tc.
Referenced by clearSingleStep(), and incomingData().
detach()
void BaseRemoteGDB::detach ()
Definition at line 399 of file remote_gdb.cc.
References active, attached, clearSingleStep(), dataEvent, DPRINTFN, fd, pollQueue, and PollQueue::remove().
Referenced by cmd_detach(), incomingData(), and trap().
encodeBinaryData()
void BaseRemoteGDB::encodeBinaryData (const std::string & unencoded, std::string & encoded) const protected
Definition at line 1020 of file remote_gdb.cc.
References ArmISA::c.
Referenced by encodeXferResponse().
encodeXferResponse()
void BaseRemoteGDB::encodeXferResponse (const std::string & unencoded, std::string & encoded, size_t offset, size_t unencoded_length) const protected
Definition at line 1034 of file remote_gdb.cc.
References encodeBinaryData().
Referenced by cmd_query_var().
gdbRegs()
virtual BaseGdbRegCache* BaseRemoteGDB::gdbRegs () protected pure virtual
Implemented in X86ISA::RemoteGDB, ArmISA::RemoteGDB, SparcISA::RemoteGDB, RiscvISA::RemoteGDB, MipsISA::RemoteGDB, PowerISA::RemoteGDB, and AlphaISA::RemoteGDB.
Referenced by trap().
getbyte()
uint8_t BaseRemoteGDB::getbyte () private
Definition at line 508 of file remote_gdb.cc.
References ArmISA::b, fd, and read().
Referenced by recv(), and send().
getXferFeaturesRead()
bool BaseRemoteGDB::getXferFeaturesRead (const std::string & annex, std::string & output) protected virtual
Get an XML target description.
Parameters
[in] annex the XML filename
[out] output set to the decoded XML
Returns
true if the given annex was found
Reimplemented in ArmISA::RemoteGDB.
Definition at line 1013 of file remote_gdb.cc.
Referenced by cmd_query_var().
incomingData()
void BaseRemoteGDB::incomingData (int revent) private
Definition at line 491 of file remote_gdb.cc.
References descheduleInstCommitEvent(), detach(), Event::scheduled(), scheduleInstCommitEvent(), trapEvent, BaseRemoteGDB::TrapEvent::type(), and warn.
insertHardBreak()
void BaseRemoteGDB::insertHardBreak (Addr addr, size_t len) private
Definition at line 705 of file remote_gdb.cc.
References addr, checkBpLen(), DPRINTF, HardBreakpoint, HardBreakpoint::refcount, and sys.
Referenced by cmd_set_hw_bkpt(), insertSoftBreak(), and setTempBreakpoint().
insertSoftBreak()
void BaseRemoteGDB::insertSoftBreak (Addr addr, size_t len) private
Definition at line 687 of file remote_gdb.cc.
References checkBpLen(), and insertHardBreak().
Referenced by cmd_set_hw_bkpt().
isAttached()
bool BaseRemoteGDB::isAttached () inline
Definition at line 138 of file remote_gdb.hh.
Referenced by connect().
listen()
void BaseRemoteGDB::listen ()
Definition at line 343 of file remote_gdb.cc.
References _port, ListenSocket::allDisabled(), ccprintf(), connectEvent, curTick(), DPRINTF, ListenSocket::getfd(), ListenSocket::listen(), listener, name(), pollQueue, PollQueue::schedule(), and warn_once.
name()
string BaseRemoteGDB::name ()
Definition at line 337 of file remote_gdb.cc.
References SimObject::name(), and sys.
Referenced by listen(), AlphaISA::RemoteGDB::AlphaGdbRegCache::name(), SparcISA::RemoteGDB::SPARCGdbRegCache::name(), PowerISA::RemoteGDB::PowerGdbRegCache::name(), MipsISA::RemoteGDB::MipsGdbRegCache::name(), RiscvISA::RemoteGDB::RiscvGdbRegCache::name(), ArmISA::RemoteGDB::AArch32GdbRegCache::name(), X86ISA::RemoteGDB::X86GdbRegCache::name(), SparcISA::RemoteGDB::SPARC64GdbRegCache::name(), ArmISA::RemoteGDB::AArch64GdbRegCache::name(), X86ISA::RemoteGDB::AMD64GdbRegCache::name(), and HardBreakpoint::name().
port()
int BaseRemoteGDB::port () const
Definition at line 379 of file remote_gdb.cc.
References _port, ListenSocket::islistening(), listener, and panic_if.
putbyte()
void BaseRemoteGDB::putbyte (uint8_t b) private
Definition at line 518 of file remote_gdb.cc.
References fd, and write().
Referenced by recv(), and send().
read() [1/2]
bool BaseRemoteGDB::read (Addr addr, size_t size, char * data) private
Definition at line 609 of file remote_gdb.cc.
References DPRINTF, DPRINTFNR, DTRACE, ThreadContext::getVirtProxy(), PortProxy::readBlob(), and tc.
Referenced by cmd_mem_r(), and getbyte().
read() [2/2]
template<class T > T BaseRemoteGDB::read (Addr addr) inline private
Definition at line 318 of file remote_gdb.hh.
recv()
void BaseRemoteGDB::recv (std::vector< char > & bp) private
Definition at line 528 of file remote_gdb.cc.
References ArmISA::c, DPRINTF, GDBBadP, GDBEnd, GDBGoodP, GDBStart, getbyte(), and putbyte().
Referenced by trap().
removeHardBreak()
void BaseRemoteGDB::removeHardBreak (Addr addr, size_t len) private
Definition at line 720 of file remote_gdb.cc.
References checkBpLen(), DPRINTF, ArmISA::i, and HardBreakpoint::refcount.
Referenced by clearTempBreakpoint(), cmd_clr_hw_bkpt(), and removeSoftBreak().
removeSoftBreak()
void BaseRemoteGDB::removeSoftBreak (Addr addr, size_t len) private
Definition at line 696 of file remote_gdb.cc.
References checkBpLen(), and removeHardBreak().
Referenced by cmd_clr_hw_bkpt().
replaceThreadContext() [1/2]
void BaseRemoteGDB::replaceThreadContext (ThreadContext * tc) inline
Definition at line 51 of file remote_gdb.hh.
replaceThreadContext() [2/2]
void BaseRemoteGDB::replaceThreadContext (ThreadContext * _tc) inline
Definition at line 140 of file remote_gdb.hh.
References type.
scheduleInstCommitEvent()
void BaseRemoteGDB::scheduleInstCommitEvent (Event * ev, int delta) private
Schedule an event which will be triggered "delta" instructions later.
Definition at line 754 of file remote_gdb.cc.
References ThreadContext::getCurrentInstCount(), ThreadContext::scheduleInstCountEvent(), and tc.
Referenced by incomingData(), setSingleStep(), and singleStep().
send()
void BaseRemoteGDB::send (const char * data) private
Definition at line 580 of file remote_gdb.cc.
References ArmISA::c, DPRINTF, GDBBadP, GDBEnd, GDBStart, getbyte(), MipsISA::p, and putbyte().
Referenced by cmd_clr_hw_bkpt(), cmd_mem_r(), cmd_mem_w(), cmd_query_var(), cmd_reg_r(), cmd_reg_w(), cmd_set_hw_bkpt(), cmd_set_thread(), cmd_signal(), and trap().
setSingleStep()
void BaseRemoteGDB::setSingleStep () private
Definition at line 680 of file remote_gdb.cc.
References Event::scheduled(), scheduleInstCommitEvent(), and singleStepEvent.
Referenced by cmd_async_step(), and cmd_step().
setTempBreakpoint()
void BaseRemoteGDB::setTempBreakpoint (Addr bkpt) private
Definition at line 747 of file remote_gdb.cc.
References DPRINTF, and insertHardBreak().
singleStep()
void BaseRemoteGDB::singleStep () private
Definition at line 666 of file remote_gdb.cc.
References Event::scheduled(), scheduleInstCommitEvent(), singleStepEvent, and trap().
system()
System* BaseRemoteGDB::system () inline protected
Definition at line 288 of file remote_gdb.hh.
References ArmISA::len, ArmISA::offset, and output().
Referenced by AlphaISA::RemoteGDB::acc(), and AlphaISA::RemoteGDB::AlphaGdbRegCache::name().
trap()
bool BaseRemoteGDB::trap (int type)
Definition at line 417 of file remote_gdb.cc.
References active, attached, clearSingleStep(), BaseRemoteGDB::GdbCommand::Context::cmd, BaseRemoteGDB::GdbCommand::Context::cmd_byte, command_map, csprintf(), data, BaseRemoteGDB::GdbCommand::Context::data, detach(), DPRINTF, ArmISA::e, BaseRemoteGDB::GdbCommand::func, gdbRegs(), BaseGdbRegCache::getRegs(), BaseRemoteGDB::GdbCommand::Context::len, panic, ThreadContext::pcState(), recv(), regCachePtr, send(), tc, BaseRemoteGDB::GdbCommand::Context::type, type, and warn.
Referenced by HardBreakpoint::process(), BaseRemoteGDB::TrapEvent::process(), and singleStep().
write() [1/2]
bool BaseRemoteGDB::write (Addr addr, size_t size, const char * data) private
Definition at line 640 of file remote_gdb.cc.
References DPRINTF, DPRINTFN, DPRINTFNR, DTRACE, ThreadContext::getVirtProxy(), tc, and PortProxy::writeBlob().
Referenced by cmd_mem_w(), and putbyte().
write() [2/2]
template<class T > void BaseRemoteGDB::write (Addr addr, T data) inline private
Definition at line 327 of file remote_gdb.hh.
Friends And Related Function Documentation
HardBreakpoint
friend class HardBreakpoint friend
Definition at line 120 of file remote_gdb.hh.
Referenced by insertHardBreak().
Member Data Documentation
_port
int BaseRemoteGDB::_port private
Definition at line 176 of file remote_gdb.hh.
Referenced by listen(), AlphaISA::RemoteGDB::AlphaGdbRegCache::name(), and port().
active
bool BaseRemoteGDB::active private
Definition at line 191 of file remote_gdb.hh.
Referenced by detach(), and trap().
attached
bool BaseRemoteGDB::attached private
Definition at line 192 of file remote_gdb.hh.
Referenced by attach(), detach(), and trap().
command_map
std::map< char, BaseRemoteGDB::GdbCommand > BaseRemoteGDB::command_map static private
Definition at line 267 of file remote_gdb.hh.
Referenced by descheduleInstCommitEvent(), and trap().
ConnectEvent
friend BaseRemoteGDB::ConnectEvent private
Definition at line 169 of file remote_gdb.hh.
connectEvent
ConnectEvent* BaseRemoteGDB::connectEvent private
Definition at line 172 of file remote_gdb.hh.
Referenced by BaseRemoteGDB(), and listen().
DataEvent
friend BaseRemoteGDB::DataEvent private
Definition at line 170 of file remote_gdb.hh.
dataEvent
DataEvent* BaseRemoteGDB::dataEvent private
Definition at line 173 of file remote_gdb.hh.
Referenced by attach(), BaseRemoteGDB(), and detach().
fd
int BaseRemoteGDB::fd private
Definition at line 179 of file remote_gdb.hh.
Referenced by attach(), detach(), getbyte(), and putbyte().
listener
ListenSocket BaseRemoteGDB::listener private
Definition at line 175 of file remote_gdb.hh.
Referenced by connect(), listen(), and port().
regCachePtr
BaseGdbRegCache* BaseRemoteGDB::regCachePtr private
Definition at line 197 of file remote_gdb.hh.
Referenced by cmd_reg_r(), cmd_reg_w(), and trap().
singleStepEvent
EventWrapper<BaseRemoteGDB, &BaseRemoteGDB::singleStep> BaseRemoteGDB::singleStepEvent private
Definition at line 225 of file remote_gdb.hh.
Referenced by clearSingleStep(), setSingleStep(), and singleStep().
sys
System* BaseRemoteGDB::sys private
Definition at line 194 of file remote_gdb.hh.
Referenced by insertHardBreak(), and name().
tc
ThreadContext* BaseRemoteGDB::tc private
Definition at line 195 of file remote_gdb.hh.
Referenced by cmd_async_cont(), cmd_async_step(), cmd_cont(), cmd_reg_w(), cmd_step(), descheduleInstCommitEvent(), HardBreakpoint::process(), read(), scheduleInstCommitEvent(), trap(), and write().
trapEvent
BaseRemoteGDB::TrapEvent BaseRemoteGDB::trapEvent private
Referenced by incomingData().
The documentation for this class was generated from the following files:
arch/null/remote_gdb.hh
base/remote_gdb.cc