gem5: DefaultIEW< Impl > Class Template Reference
DefaultIEW< Impl > Class Template Reference
DefaultIEW handles both single threaded and SMT IEW (issue/execute/writeback).
#include <iew.hh>
Public Types
enum Status { Active, Inactive }
Overall IEW stage status.
enum StageStatus {
Running, Blocked, Idle, StartSquash,
Squashing, Unblocking
}
Status for Issue, Execute, and Writeback stages.
Public Member Functions
DefaultIEW (O3CPU *_cpu, DerivO3CPUParams *params)
Constructs a DefaultIEW with the given parameters.
std::string name () const
Returns the name of the DefaultIEW stage.
void regStats ()
Registers statistics.
void regProbePoints ()
Registers probes.
void startupStage ()
Initializes stage; sends back the number of free IQ and LSQ entries.
void clearStates (ThreadID tid)
Clear all thread-specific states.
void setTimeBuffer (TimeBuffer< TimeStruct > *tb_ptr)
Sets main time buffer used for backwards communication.
void setRenameQueue (TimeBuffer< RenameStruct > *rq_ptr)
Sets time buffer for getting instructions coming from rename.
void setIEWQueue (TimeBuffer< IEWStruct > *iq_ptr)
Sets time buffer to pass on instructions to commit.
void setActiveThreads (std::list< ThreadID > *at_ptr)
Sets pointer to list of active threads.
void setScoreboard (Scoreboard *sb_ptr)
Sets pointer to the scoreboard.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool isDrained () const
Has the stage drained?
void takeOverFrom ()
Takes over from another CPU's thread.
void squash (ThreadID tid)
Squashes instructions in IEW for a specific thread.
void wakeDependents (const DynInstPtr &inst)
Wakes all dependents of a completed instruction.
void rescheduleMemInst (const DynInstPtr &inst)
Tells memory dependence unit that a memory instruction needs to be rescheduled.
void replayMemInst (const DynInstPtr &inst)
Re-executes all rescheduled memory instructions.
void blockMemInst (const DynInstPtr &inst)
Moves memory instruction onto the list of cache blocked instructions.
void cacheUnblocked ()
Notifies that the cache has become unblocked.
void instToCommit (const DynInstPtr &inst)
Sends an instruction to commit through the time buffer.
void skidInsert (ThreadID tid)
Inserts unused instructions of a thread into the skid buffer.
int skidCount ()
Returns the max of the number of entries in all of the skid buffers.
bool skidsEmpty ()
Returns if all of the skid buffers are empty.
void updateStatus ()
Updates overall IEW status based on all of the stages' statuses.
void resetEntries ()
Resets entries of the IQ and the LSQ.
void wakeCPU ()
Tells the CPU to wakeup if it has descheduled itself due to no activity.
void activityThisCycle ()
Reports to the CPU that there is activity this cycle.
void activateStage ()
Tells CPU that the IEW stage is active and running.
void deactivateStage ()
Tells CPU that the IEW stage is inactive and idle.
bool hasStoresToWB ()
Returns if the LSQ has any stores to writeback.
bool hasStoresToWB (ThreadID tid)
Returns if the LSQ has any stores to writeback.
void checkMisprediction (const DynInstPtr &inst)
Check misprediction.
void tick ()
Ticks IEW stage, causing Dispatch, the IQ, the LSQ, Execute, and Writeback to run for one cycle.
Public Attributes
IQ instQueue
Instruction queue.
LSQ ldstQueue
Load / store queue.
FUPool * fuPool
Pointer to the functional unit pool.
bool updateLSQNextCycle
Records if the LSQ needs to be updated on the next cycle, so that IEW knows if there will be activity on the next cycle.
Private Types
typedef Impl::CPUPol CPUPol
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::O3CPU O3CPU
typedef CPUPol::IQ IQ
typedef CPUPol::RenameMap RenameMap
typedef CPUPol::LSQ LSQ
typedef CPUPol::TimeStruct TimeStruct
typedef CPUPol::IEWStruct IEWStruct
typedef CPUPol::RenameStruct RenameStruct
typedef CPUPol::IssueStruct IssueStruct
Private Member Functions
void squashDueToBranch (const DynInstPtr &inst, ThreadID tid)
Sends commit proper information for a squash due to a branch mispredict.
void squashDueToMemOrder (const DynInstPtr &inst, ThreadID tid)
Sends commit proper information for a squash due to a memory order violation.
void block (ThreadID tid)
Sets Dispatch to blocked, and signals back to other stages to block.
void unblock (ThreadID tid)
Unblocks Dispatch if the skid buffer is empty, and signals back to other stages to unblock.
void dispatch (ThreadID tid)
Determines proper actions to take given Dispatch's status.
void dispatchInsts (ThreadID tid)
Dispatches instructions to IQ and LSQ.
void executeInsts ()
Executes instructions.
void writebackInsts ()
Writebacks instructions.
unsigned validInstsFromRename ()
Returns the number of valid, non-squashed instructions coming from rename to dispatch.
bool checkStall (ThreadID tid)
Checks if any of the stall conditions are currently true.
void checkSignalsAndUpdate (ThreadID tid)
Processes inputs and changes state accordingly.
void emptyRenameInsts (ThreadID tid)
Removes instructions from rename from a thread's instruction list.
void sortInsts ()
Sorts instructions coming from rename into lists separated by thread.
void updateExeInstStats (const DynInstPtr &inst)
Updates execution stats based on the instruction.
void printAvailableInsts ()
Debug function to print instructions that are issued this cycle.
Private Attributes
Status _status
Overall stage status.
StageStatus dispatchStatus [Impl::MaxThreads]
Dispatch status.
StageStatus exeStatus
Execute status.
StageStatus wbStatus
Writeback status.
ProbePointArg< DynInstPtr > * ppMispredict
Probe points.
ProbePointArg< DynInstPtr > * ppDispatch
ProbePointArg< DynInstPtr > * ppExecute
To probe when instruction execution begins.
ProbePointArg< DynInstPtr > * ppToCommit
To probe when instruction execution is complete.
TimeBuffer< TimeStruct > * timeBuffer
Pointer to main time buffer used for backwards communication.
TimeBuffer< TimeStruct >::wire toFetch
Wire to write information heading to previous stages.
TimeBuffer< TimeStruct >::wire fromCommit
Wire to get commit's output from backwards time buffer.
TimeBuffer< TimeStruct >::wire toRename
Wire to write information heading to previous stages.
TimeBuffer< RenameStruct > * renameQueue
Rename instruction queue interface.
TimeBuffer< RenameStruct >::wire fromRename
Wire to get rename's output from rename queue.
TimeBuffer< IssueStruct > issueToExecQueue
Issue stage queue.
TimeBuffer< IssueStruct >::wire fromIssue
Wire to read information from the issue stage time queue.
TimeBuffer< IEWStruct > * iewQueue
IEW stage time buffer.
TimeBuffer< IEWStruct >::wire toCommit
Wire to write infromation heading to commit.
std::queue< DynInstPtr > insts [Impl::MaxThreads]
Queue of all instructions coming from rename this cycle.
std::queue< DynInstPtr > skidBuffer [Impl::MaxThreads]
Skid buffer between rename and IEW.
Scoreboard * scoreboard
Scoreboard pointer.
O3CPU * cpu
CPU pointer.
bool wroteToTimeBuffer
Records if IEW has written to the time buffer this cycle, so that the CPU can deschedule itself if there is no activity.
bool fetchRedirect [Impl::MaxThreads]
Records if there is a fetch redirect on this cycle for each thread.
bool updatedQueues
Records if the queues have been changed (inserted or issued insts), so that IEW knows to broadcast the updated amount of free entries.
Cycles commitToIEWDelay
Commit to IEW delay.
Cycles renameToIEWDelay
Rename to IEW delay.
Cycles issueToExecuteDelay
Issue to execute delay.
unsigned dispatchWidth
Width of dispatch, in instructions.
unsigned issueWidth
Width of issue, in instructions.
unsigned wbNumInst
Index into queue of instructions being written back.
unsigned wbCycle
Cycle number within the queue of instructions being written back.
unsigned wbWidth
Writeback width.
ThreadID numThreads
Number of active threads.
std::list< ThreadID > * activeThreads
Pointer to list of active threads.
unsigned skidBufferMax
Maximum size of the skid buffer.
Stats::Scalar iewIdleCycles
Stat for total number of idle cycles.
Stats::Scalar iewSquashCycles
Stat for total number of squashing cycles.
Stats::Scalar iewBlockCycles
Stat for total number of blocking cycles.
Stats::Scalar iewUnblockCycles
Stat for total number of unblocking cycles.
Stats::Scalar iewDispatchedInsts
Stat for total number of instructions dispatched.
Stats::Scalar iewDispSquashedInsts
Stat for total number of squashed instructions dispatch skips.
Stats::Scalar iewDispLoadInsts
Stat for total number of dispatched load instructions.
Stats::Scalar iewDispStoreInsts
Stat for total number of dispatched store instructions.
Stats::Scalar iewDispNonSpecInsts
Stat for total number of dispatched non speculative instructions.
Stats::Scalar iewIQFullEvents
Stat for number of times the IQ becomes full.
Stats::Scalar iewLSQFullEvents
Stat for number of times the LSQ becomes full.
Stats::Scalar memOrderViolationEvents
Stat for total number of memory ordering violation events.
Stats::Scalar predictedTakenIncorrect
Stat for total number of incorrect predicted taken branches.
Stats::Scalar predictedNotTakenIncorrect
Stat for total number of incorrect predicted not taken branches.
Stats::Formula branchMispredicts
Stat for total number of mispredicted branches detected at execute.
Stats::Scalar iewExecutedInsts
Stat for total number of executed instructions.
Stats::Vector iewExecLoadInsts
Stat for total number of executed load instructions.
Stats::Scalar iewExecSquashedInsts
Stat for total number of executed store instructions.
Stats::Vector iewExecutedSwp
Number of executed software prefetches.
Stats::Vector iewExecutedNop
Number of executed nops.
Stats::Vector iewExecutedRefs
Number of executed meomory references.
Stats::Vector iewExecutedBranches
Number of executed branches.
Stats::Formula iewExecStoreInsts
Number of executed store instructions.
Stats::Formula iewExecRate
Number of instructions executed per cycle.
Stats::Vector iewInstsToCommit
Number of instructions sent to commit.
Stats::Vector writebackCount
Number of instructions that writeback.
Stats::Vector producerInst
Number of instructions that wake consumers.
Stats::Vector consumerInst
Number of instructions that wake up from producers.
Stats::Formula wbRate
Number of instructions per cycle written back.
Stats::Formula wbFanout
Average number of woken instructions per writeback.
Detailed Description
template<class Impl>
class DefaultIEW< Impl >
DefaultIEW handles both single threaded and SMT IEW (issue/execute/writeback).
It handles the dispatching of instructions to the LSQ/IQ as part of the issue stage, and has the IQ try to issue instructions each cycle. The execute latency is actually tied into the issue latency to allow the IQ to be able to do back-to-back scheduling without having to speculatively schedule instructions. This happens by having the IQ have access to the functional units, and the IQ gets the execution latencies from the FUs when it issues instructions. Instructions reach the execute stage on the last cycle of their execution, which is when the IQ knows to wake up any dependent instructions, allowing back to back scheduling. The execute portion of IEW separates memory instructions from non-memory instructions, either telling the LSQ to execute the instruction, or executing the instruction directly. The writeback portion of IEW completes the instructions by waking up any dependents, and marking the register ready on the scoreboard.
Definition at line 80 of file iew.hh.
Member Typedef Documentation
CPUPol
template<class Impl > typedef Impl::CPUPol DefaultIEW< Impl >::CPUPol private
Definition at line 84 of file iew.hh.
DynInstPtr
template<class Impl > typedef Impl::DynInstPtr DefaultIEW< Impl >::DynInstPtr private
Definition at line 85 of file iew.hh.
IEWStruct
template<class Impl > typedef CPUPol::IEWStruct DefaultIEW< Impl >::IEWStruct private
Definition at line 93 of file iew.hh.
IQ
template<class Impl > typedef CPUPol::IQ DefaultIEW< Impl >::IQ private
Definition at line 88 of file iew.hh.
IssueStruct
template<class Impl > typedef CPUPol::IssueStruct DefaultIEW< Impl >::IssueStruct private
Definition at line 95 of file iew.hh.
LSQ
template<class Impl > typedef CPUPol::LSQ DefaultIEW< Impl >::LSQ private
Definition at line 90 of file iew.hh.
O3CPU
template<class Impl > typedef Impl::O3CPU DefaultIEW< Impl >::O3CPU private
Definition at line 86 of file iew.hh.
RenameMap
template<class Impl > typedef CPUPol::RenameMap DefaultIEW< Impl >::RenameMap private
Definition at line 89 of file iew.hh.
RenameStruct
template<class Impl > typedef CPUPol::RenameStruct DefaultIEW< Impl >::RenameStruct private
Definition at line 94 of file iew.hh.
TimeStruct
template<class Impl > typedef CPUPol::TimeStruct DefaultIEW< Impl >::TimeStruct private
Definition at line 92 of file iew.hh.
Member Enumeration Documentation
StageStatus
template<class Impl > enum DefaultIEW::StageStatus
Status for Issue, Execute, and Writeback stages.
Enumerator
Running
Blocked
Idle
StartSquash
Squashing
Unblocking
Definition at line 107 of file iew.hh.
Status
template<class Impl > enum DefaultIEW::Status
Overall IEW stage status.
Used to determine if the CPU can deschedule itself due to a lack of activity.
Enumerator
Active
Inactive
Definition at line 101 of file iew.hh.
Constructor & Destructor Documentation
DefaultIEW()
template<class Impl > DefaultIEW< Impl >::DefaultIEW (O3CPU * _cpu, DerivO3CPUParams * params)
Constructs a DefaultIEW with the given parameters.
Definition at line 68 of file iew_impl.hh.
References DefaultIEW< Impl >::_status, DefaultIEW< Impl >::Active, DefaultIEW< Impl >::dispatchStatus, DefaultIEW< Impl >::dispatchWidth, DefaultIEW< Impl >::exeStatus, fatal, DefaultIEW< Impl >::fetchRedirect, DefaultIEW< Impl >::fromIssue, TimeBuffer< T >::getWire(), DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::issueToExecQueue, DefaultIEW< Impl >::issueToExecuteDelay, DefaultIEW< Impl >::issueWidth, DefaultIEW< Impl >::renameToIEWDelay, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::skidBufferMax, DefaultIEW< Impl >::updateLSQNextCycle, DefaultIEW< Impl >::wbStatus, and DefaultIEW< Impl >::wbWidth.
Member Function Documentation
activateStage()
template<class Impl > void DefaultIEW< Impl >::activateStage () inline
Tells CPU that the IEW stage is active and running.
Definition at line 897 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu, and DPRINTF.
Referenced by DefaultIEW< Impl >::updateStatus().
activityThisCycle()
template<class Impl > void DefaultIEW< Impl >::activityThisCycle ()
Reports to the CPU that there is activity this cycle.
Definition at line 889 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu, and DPRINTF.
Referenced by DefaultIEW< Impl >::executeInsts().
block()
template<class Impl > void DefaultIEW< Impl >::block (ThreadID tid) private
Sets Dispatch to blocked, and signals back to other stages to block.
Definition at line 552 of file iew_impl.hh.
References DefaultIEW< Impl >::Blocked, DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::skidInsert(), DefaultIEW< Impl >::toRename, DefaultIEW< Impl >::Unblocking, and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::hasStoresToWB().
blockMemInst()
template<class Impl > void DefaultIEW< Impl >::blockMemInst (const DynInstPtr & inst)
Moves memory instruction onto the list of cache blocked instructions.
Definition at line 609 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue.
cacheUnblocked()
template<class Impl > void DefaultIEW< Impl >::cacheUnblocked ()
Notifies that the cache has become unblocked.
Definition at line 616 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue.
checkMisprediction()
template<class Impl > void DefaultIEW< Impl >::checkMisprediction (const DynInstPtr & inst)
Check misprediction.
Definition at line 1666 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::fetchRedirect, DefaultIEW< Impl >::predictedNotTakenIncorrect, DefaultIEW< Impl >::predictedTakenIncorrect, DefaultIEW< Impl >::squashDueToBranch(), and DefaultIEW< Impl >::toCommit.
Referenced by DefaultIEW< Impl >::hasStoresToWB().
checkSignalsAndUpdate()
template<class Impl > void DefaultIEW< Impl >::checkSignalsAndUpdate (ThreadID tid) private
Processes inputs and changes state accordingly.
Definition at line 782 of file iew_impl.hh.
References DefaultIEW< Impl >::block(), DefaultIEW< Impl >::Blocked, DefaultIEW< Impl >::checkStall(), DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::emptyRenameInsts(), DefaultIEW< Impl >::fetchRedirect, DefaultIEW< Impl >::fromCommit, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::squash(), DefaultIEW< Impl >::Squashing, DefaultIEW< Impl >::toRename, DefaultIEW< Impl >::unblock(), DefaultIEW< Impl >::Unblocking, and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::tick().
checkStall()
template<class Impl > bool DefaultIEW< Impl >::checkStall (ThreadID tid) private
Checks if any of the stall conditions are currently true.
Definition at line 765 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::fromCommit, and DefaultIEW< Impl >::instQueue.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate(), and DefaultIEW< Impl >::hasStoresToWB().
clearStates()
template<class Impl > void DefaultIEW< Impl >::clearStates (ThreadID tid)
Clear all thread-specific states.
Definition at line 328 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), and DefaultIEW< Impl >::toRename.
deactivateStage()
template<class Impl > void DefaultIEW< Impl >::deactivateStage () inline
Tells CPU that the IEW stage is inactive and idle.
Definition at line 905 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu, and DPRINTF.
Referenced by DefaultIEW< Impl >::updateStatus().
dispatch()
template<class Impl > void DefaultIEW< Impl >::dispatch (ThreadID tid) private
Determines proper actions to take given Dispatch's status.
Definition at line 913 of file iew_impl.hh.
References DefaultIEW< Impl >::Blocked, DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::iewBlockCycles, DefaultIEW< Impl >::iewSquashCycles, DefaultIEW< Impl >::iewUnblockCycles, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::skidInsert(), DefaultIEW< Impl >::skidsEmpty(), DefaultIEW< Impl >::Squashing, DefaultIEW< Impl >::unblock(), DefaultIEW< Impl >::Unblocking, and DefaultIEW< Impl >::validInstsFromRename().
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::tick().
dispatchInsts()
template<class Impl > void DefaultIEW< Impl >::dispatchInsts (ThreadID tid) private
Dispatches instructions to IQ and LSQ.
Definition at line 961 of file iew_impl.hh.
References DefaultIEW< Impl >::block(), curTick(), DefaultIEW< Impl >::dispatchStatus, DefaultIEW< Impl >::dispatchWidth, DPRINTF, DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::iewDispatchedInsts, DefaultIEW< Impl >::iewDispLoadInsts, DefaultIEW< Impl >::iewDispNonSpecInsts, DefaultIEW< Impl >::iewDispSquashedInsts, DefaultIEW< Impl >::iewDispStoreInsts, DefaultIEW< Impl >::iewExecutedNop, DefaultIEW< Impl >::iewIQFullEvents, DefaultIEW< Impl >::iewLSQFullEvents, LSQ< Impl >::insertLoad(), LSQ< Impl >::insertStore(), DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::insts, DefaultIEW< Impl >::ldstQueue, LSQ< Impl >::lqFull(), ProbePointArg< Arg >::notify(), DefaultIEW< Impl >::ppDispatch, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::skidBuffer, LSQ< Impl >::sqFull(), DefaultIEW< Impl >::toRename, DefaultIEW< Impl >::Unblocking, and DefaultIEW< Impl >::updatedQueues.
Referenced by DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::hasStoresToWB().
drainSanityCheck()
template<class Impl > void DefaultIEW< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 425 of file iew_impl.hh.
References LSQ< Impl >::drainSanityCheck(), DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::isDrained(), and DefaultIEW< Impl >::ldstQueue.
emptyRenameInsts()
template<class Impl > void DefaultIEW< Impl >::emptyRenameInsts (ThreadID tid) private
Removes instructions from rename from a thread's instruction list.
Definition at line 860 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::insts, and DefaultIEW< Impl >::toRename.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::squash().
executeInsts()
template<class Impl > void DefaultIEW< Impl >::executeInsts () private
Executes instructions.
In the case of memory operations, it informs the LSQ to execute the instructions. Also handles any redirects that occur due to the executed instructions.
Definition at line 1207 of file iew_impl.hh.
References DefaultIEW< Impl >::activeThreads, DefaultIEW< Impl >::activityThisCycle(), DefaultIEW< Impl >::cpu, DPRINTF, LSQ< Impl >::executeLoad(), LSQ< Impl >::executeStore(), DefaultIEW< Impl >::exeStatus, DefaultIEW< Impl >::fetchRedirect, DefaultIEW< Impl >::fromIssue, LSQ< Impl >::getMemDepViolator(), DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::iewExecSquashedInsts, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::instToCommit(), DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::memOrderViolationEvents, NoFault, ProbePointArg< Arg >::notify(), panic, DefaultIEW< Impl >::ppExecute, DefaultIEW< Impl >::ppMispredict, DefaultIEW< Impl >::predictedNotTakenIncorrect, DefaultIEW< Impl >::predictedTakenIncorrect, DefaultIEW< Impl >::Running, TimeBuffer< T >::size, DefaultIEW< Impl >::squashDueToBranch(), DefaultIEW< Impl >::squashDueToMemOrder(), DefaultIEW< Impl >::toCommit, DefaultIEW< Impl >::updatedQueues, DefaultIEW< Impl >::updateExeInstStats(), LSQ< Impl >::violation(), DefaultIEW< Impl >::wbCycle, and DefaultIEW< Impl >::wbNumInst.
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::tick().
hasStoresToWB() [1/2]
template<class Impl > bool DefaultIEW< Impl >::hasStoresToWB () inline
Returns if the LSQ has any stores to writeback.
Definition at line 230 of file iew.hh.
References LSQ< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::ldstQueue.
hasStoresToWB() [2/2]
template<class Impl > bool DefaultIEW< Impl >::hasStoresToWB (ThreadID tid) inline
Returns if the LSQ has any stores to writeback.
Definition at line 233 of file iew.hh.
References DefaultIEW< Impl >::block(), DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::checkStall(), DefaultIEW< Impl >::dispatch(), DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::emptyRenameInsts(), DefaultIEW< Impl >::executeInsts(), LSQ< Impl >::hasStoresToWB(), DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::sortInsts(), DefaultIEW< Impl >::squashDueToBranch(), DefaultIEW< Impl >::squashDueToMemOrder(), DefaultIEW< Impl >::tick(), DefaultIEW< Impl >::unblock(), DefaultIEW< Impl >::updateExeInstStats(), DefaultIEW< Impl >::validInstsFromRename(), and DefaultIEW< Impl >::writebackInsts().
instToCommit()
template<class Impl > void DefaultIEW< Impl >::instToCommit (const DynInstPtr & inst)
Sends an instruction to commit through the time buffer.
Definition at line 623 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::iewQueue, DefaultIEW< Impl >::insts, DefaultIEW< Impl >::wbCycle, DefaultIEW< Impl >::wbNumInst, and DefaultIEW< Impl >::wbWidth.
Referenced by DefaultIEW< Impl >::executeInsts().
isDrained()
template<class Impl > bool DefaultIEW< Impl >::isDrained () const
Has the stage drained?
Definition at line 396 of file iew_impl.hh.
References DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::fuPool, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::insts, FUPool::isDrained(), LSQ< Impl >::isDrained(), DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::numThreads, DefaultIEW< Impl >::Running, and DefaultIEW< Impl >::skidBuffer.
Referenced by DefaultIEW< Impl >::drainSanityCheck().
name()
template<class Impl > std::string DefaultIEW< Impl >::name () const
Returns the name of the DefaultIEW stage.
Definition at line 119 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu.
Referenced by DefaultIEW< Impl >::regStats().
printAvailableInsts()
template<class Impl > void DefaultIEW< Impl >::printAvailableInsts () private
Debug function to print instructions that are issued this cycle.
Definition at line 1184 of file iew_impl.hh.
References DefaultIEW< Impl >::fromIssue.
regProbePoints()
template<class Impl > void DefaultIEW< Impl >::regProbePoints ()
Registers probes.
Probe point with dynamic instruction as the argument used to probe when an instruction starts to execute.
Probe point with dynamic instruction as the argument used to probe when an instruction execution completes and it is marked ready to commit.
Definition at line 126 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu, DefaultIEW< Impl >::ppDispatch, DefaultIEW< Impl >::ppExecute, DefaultIEW< Impl >::ppMispredict, and DefaultIEW< Impl >::ppToCommit.
regStats()
template<class Impl > void DefaultIEW< Impl >::regStats ()
Registers statistics.
Definition at line 146 of file iew_impl.hh.
References DefaultIEW< Impl >::branchMispredicts, DefaultIEW< Impl >::consumerInst, DefaultIEW< Impl >::cpu, Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::DataWrap< Derived, InfoProxyType >::flags(), DefaultIEW< Impl >::iewBlockCycles, DefaultIEW< Impl >::iewDispatchedInsts, DefaultIEW< Impl >::iewDispLoadInsts, DefaultIEW< Impl >::iewDispNonSpecInsts, DefaultIEW< Impl >::iewDispSquashedInsts, DefaultIEW< Impl >::iewDispStoreInsts, DefaultIEW< Impl >::iewExecLoadInsts, DefaultIEW< Impl >::iewExecRate, DefaultIEW< Impl >::iewExecSquashedInsts, DefaultIEW< Impl >::iewExecStoreInsts, DefaultIEW< Impl >::iewExecutedBranches, DefaultIEW< Impl >::iewExecutedInsts, DefaultIEW< Impl >::iewExecutedNop, DefaultIEW< Impl >::iewExecutedRefs, DefaultIEW< Impl >::iewExecutedSwp, DefaultIEW< Impl >::iewIdleCycles, DefaultIEW< Impl >::iewInstsToCommit, DefaultIEW< Impl >::iewIQFullEvents, DefaultIEW< Impl >::iewLSQFullEvents, DefaultIEW< Impl >::iewSquashCycles, DefaultIEW< Impl >::iewUnblockCycles, Stats::VectorBase< Derived, Stor >::init(), DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::memOrderViolationEvents, DefaultIEW< Impl >::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), DefaultIEW< Impl >::predictedNotTakenIncorrect, DefaultIEW< Impl >::predictedTakenIncorrect, DefaultIEW< Impl >::producerInst, LSQ< Impl >::regStats(), Stats::total, DefaultIEW< Impl >::wbFanout, DefaultIEW< Impl >::wbRate, and DefaultIEW< Impl >::writebackCount.
replayMemInst()
template<class Impl > void DefaultIEW< Impl >::replayMemInst (const DynInstPtr & inst)
Re-executes all rescheduled memory instructions.
Definition at line 602 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue.
rescheduleMemInst()
template<class Impl > void DefaultIEW< Impl >::rescheduleMemInst (const DynInstPtr & inst)
Tells memory dependence unit that a memory instruction needs to be rescheduled.
It will re-execute once replayMemInst() is called.
Definition at line 595 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue.
resetEntries()
template<class Impl > void DefaultIEW< Impl >::resetEntries ()
Resets entries of the IQ and the LSQ.
setActiveThreads()
template<class Impl > void DefaultIEW< Impl >::setActiveThreads (std::list< ThreadID > * at_ptr)
Sets pointer to list of active threads.
Definition at line 379 of file iew_impl.hh.
References DefaultIEW< Impl >::activeThreads, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, and LSQ< Impl >::setActiveThreads().
setIEWQueue()
template<class Impl > void DefaultIEW< Impl >::setIEWQueue (TimeBuffer< IEWStruct > * iq_ptr)
Sets time buffer to pass on instructions to commit.
Definition at line 369 of file iew_impl.hh.
References TimeBuffer< T >::getWire(), DefaultIEW< Impl >::iewQueue, and DefaultIEW< Impl >::toCommit.
setRenameQueue()
template<class Impl > void DefaultIEW< Impl >::setRenameQueue (TimeBuffer< RenameStruct > * rq_ptr)
Sets time buffer for getting instructions coming from rename.
Definition at line 359 of file iew_impl.hh.
References DefaultIEW< Impl >::fromRename, TimeBuffer< T >::getWire(), DefaultIEW< Impl >::renameQueue, and DefaultIEW< Impl >::renameToIEWDelay.
setScoreboard()
template<class Impl > void DefaultIEW< Impl >::setScoreboard (Scoreboard * sb_ptr)
Sets pointer to the scoreboard.
Definition at line 389 of file iew_impl.hh.
References DefaultIEW< Impl >::scoreboard.
setTimeBuffer()
template<class Impl > void DefaultIEW< Impl >::setTimeBuffer (TimeBuffer< TimeStruct > * tb_ptr)
Sets main time buffer used for backwards communication.
Definition at line 341 of file iew_impl.hh.
References DefaultIEW< Impl >::commitToIEWDelay, DefaultIEW< Impl >::fromCommit, TimeBuffer< T >::getWire(), DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::timeBuffer, DefaultIEW< Impl >::toFetch, and DefaultIEW< Impl >::toRename.
skidCount()
template<class Impl > int DefaultIEW< Impl >::skidCount ()
Returns the max of the number of entries in all of the skid buffers.
Definition at line 688 of file iew_impl.hh.
References DefaultIEW< Impl >::activeThreads, and DefaultIEW< Impl >::skidBuffer.
skidInsert()
template<class Impl > void DefaultIEW< Impl >::skidInsert (ThreadID tid)
Inserts unused instructions of a thread into the skid buffer.
Definition at line 666 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::insts, DefaultIEW< Impl >::skidBuffer, and DefaultIEW< Impl >::skidBufferMax.
Referenced by DefaultIEW< Impl >::block(), and DefaultIEW< Impl >::dispatch().
skidsEmpty()
template<class Impl > bool DefaultIEW< Impl >::skidsEmpty ()
Returns if all of the skid buffers are empty.
Definition at line 707 of file iew_impl.hh.
References DefaultIEW< Impl >::activeThreads, and DefaultIEW< Impl >::skidBuffer.
Referenced by DefaultIEW< Impl >::dispatch().
sortInsts()
template<class Impl > void DefaultIEW< Impl >::sortInsts () private
Sorts instructions coming from rename into lists separated by thread.
Definition at line 846 of file iew_impl.hh.
References DefaultIEW< Impl >::fromRename, ArmISA::i, DefaultIEW< Impl >::insts, DefaultIEW< Impl >::numThreads, and TimeBuffer< T >::size.
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::tick().
squash()
template<class Impl > void DefaultIEW< Impl >::squash (ThreadID tid)
Squashes instructions in IEW for a specific thread.
Definition at line 463 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::emptyRenameInsts(), DefaultIEW< Impl >::fromCommit, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::skidBuffer, LSQ< Impl >::squash(), DefaultIEW< Impl >::toRename, and DefaultIEW< Impl >::updatedQueues.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate().
squashDueToBranch()
template<class Impl > void DefaultIEW< Impl >::squashDueToBranch (const DynInstPtr & inst, ThreadID tid) private
Sends commit proper information for a squash due to a branch mispredict.
Definition at line 499 of file iew_impl.hh.
References AlphaISA::advancePC(), DPRINTF, MipsISA::pc, DefaultIEW< Impl >::toCommit, and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::hasStoresToWB().
squashDueToMemOrder()
template<class Impl > void DefaultIEW< Impl >::squashDueToMemOrder (const DynInstPtr & inst, ThreadID tid) private
Sends commit proper information for a squash due to a memory order violation.
Definition at line 525 of file iew_impl.hh.
References DPRINTF, DefaultIEW< Impl >::toCommit, and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::hasStoresToWB().
startupStage()
template<class Impl > void DefaultIEW< Impl >::startupStage ()
Initializes stage; sends back the number of free IQ and LSQ entries.
Definition at line 306 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu, LSQ< Impl >::getDataPort(), DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), DefaultIEW< Impl >::numThreads, and DefaultIEW< Impl >::toRename.
Referenced by DefaultIEW< Impl >::takeOverFrom().
takeOverFrom()
template<class Impl > void DefaultIEW< Impl >::takeOverFrom ()
Takes over from another CPU's thread.
Definition at line 435 of file iew_impl.hh.
References DefaultIEW< Impl >::_status, DefaultIEW< Impl >::Active, TimeBuffer< T >::advance(), DefaultIEW< Impl >::cpu, DefaultIEW< Impl >::dispatchStatus, DefaultIEW< Impl >::exeStatus, DefaultIEW< Impl >::fetchRedirect, DefaultIEW< Impl >::fuPool, TimeBuffer< T >::getSize(), ArmISA::i, DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::issueToExecQueue, DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::numThreads, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::startupStage(), FUPool::takeOverFrom(), LSQ< Impl >::takeOverFrom(), DefaultIEW< Impl >::updateLSQNextCycle, and DefaultIEW< Impl >::wbStatus.
tick()
template<class Impl > void DefaultIEW< Impl >::tick ()
Ticks IEW stage, causing Dispatch, the IQ, the LSQ, Execute, and Writeback to run for one cycle.
Definition at line 1504 of file iew_impl.hh.
References DefaultIEW< Impl >::activeThreads, TimeBuffer< T >::advance(), DefaultIEW< Impl >::checkSignalsAndUpdate(), LSQ< Impl >::commitLoads(), LSQ< Impl >::commitStores(), DefaultIEW< Impl >::cpu, DefaultIEW< Impl >::dispatch(), DPRINTF, DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::exeStatus, DefaultIEW< Impl >::fromCommit, DefaultIEW< Impl >::fuPool, LSQ< Impl >::getCount(), DefaultIEW< Impl >::Idle, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::issueToExecQueue, DefaultIEW< Impl >::ldstQueue, LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), FUPool::processFreeUnits(), DefaultIEW< Impl >::Running, DefaultIEW< Impl >::sortInsts(), DefaultIEW< Impl >::Squashing, LSQ< Impl >::tick(), DefaultIEW< Impl >::toFetch, DefaultIEW< Impl >::toRename, DefaultIEW< Impl >::updatedQueues, DefaultIEW< Impl >::updateLSQNextCycle, DefaultIEW< Impl >::updateStatus(), DefaultIEW< Impl >::wbCycle, DefaultIEW< Impl >::wbNumInst, DefaultIEW< Impl >::writebackInsts(), LSQ< Impl >::writebackStores(), and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::hasStoresToWB().
unblock()
template<class Impl > void DefaultIEW< Impl >::unblock (ThreadID tid) private
Unblocks Dispatch if the skid buffer is empty, and signals back to other stages to unblock.
Definition at line 571 of file iew_impl.hh.
References DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::Running, DefaultIEW< Impl >::skidBuffer, DefaultIEW< Impl >::toRename, and DefaultIEW< Impl >::wroteToTimeBuffer.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::hasStoresToWB().
updateExeInstStats()
template<class Impl > void DefaultIEW< Impl >::updateExeInstStats (const DynInstPtr & inst) private
Updates execution stats based on the instruction.
Definition at line 1634 of file iew_impl.hh.
References curTick(), DTRACE, DefaultIEW< Impl >::iewExecLoadInsts, DefaultIEW< Impl >::iewExecutedBranches, DefaultIEW< Impl >::iewExecutedInsts, and DefaultIEW< Impl >::iewExecutedRefs.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::hasStoresToWB().
updateStatus()
template<class Impl > void DefaultIEW< Impl >::updateStatus ()
Updates overall IEW status based on all of the stages' statuses.
Definition at line 724 of file iew_impl.hh.
References DefaultIEW< Impl >::_status, DefaultIEW< Impl >::activateStage(), DefaultIEW< Impl >::Active, DefaultIEW< Impl >::activeThreads, DefaultIEW< Impl >::deactivateStage(), DefaultIEW< Impl >::dispatchStatus, DPRINTF, DefaultIEW< Impl >::Inactive, DefaultIEW< Impl >::instQueue, DefaultIEW< Impl >::ldstQueue, DefaultIEW< Impl >::Unblocking, and LSQ< Impl >::willWB().
Referenced by DefaultIEW< Impl >::tick().
validInstsFromRename()
template<class Impl > unsigned DefaultIEW< Impl >::validInstsFromRename () private
Returns the number of valid, non-squashed instructions coming from rename to dispatch.
Definition at line 652 of file iew_impl.hh.
References DefaultIEW< Impl >::fromRename, ArmISA::i, and TimeBuffer< T >::size.
Referenced by DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::hasStoresToWB().
wakeCPU()
template<class Impl > void DefaultIEW< Impl >::wakeCPU ()
Tells the CPU to wakeup if it has descheduled itself due to no activity.
Used mainly by the LdWritebackEvent.
Definition at line 882 of file iew_impl.hh.
References DefaultIEW< Impl >::cpu.
wakeDependents()
template<class Impl > void DefaultIEW< Impl >::wakeDependents (const DynInstPtr & inst)
Wakes all dependents of a completed instruction.
Definition at line 588 of file iew_impl.hh.
References DefaultIEW< Impl >::instQueue.
writebackInsts()
template<class Impl > void DefaultIEW< Impl >::writebackInsts () private
Writebacks instructions.
In our model, the instruction's execute() function atomically reads registers, executes, and writes registers. Thus this writeback only wakes up dependent instructions, and informs the scoreboard of registers becoming ready.
Definition at line 1454 of file iew_impl.hh.
References DefaultIEW< Impl >::consumerInst, DPRINTF, ArmISA::i, DefaultIEW< Impl >::iewInstsToCommit, DefaultIEW< Impl >::instQueue, NoFault, ProbePointArg< Arg >::notify(), DefaultIEW< Impl >::ppToCommit, DefaultIEW< Impl >::producerInst, DefaultIEW< Impl >::scoreboard, Scoreboard::setReg(), DefaultIEW< Impl >::toCommit, DefaultIEW< Impl >::wbWidth, and DefaultIEW< Impl >::writebackCount.
Referenced by DefaultIEW< Impl >::hasStoresToWB(), and DefaultIEW< Impl >::tick().
Member Data Documentation
_status
template<class Impl > Status DefaultIEW< Impl >::_status private
Overall stage status.
Definition at line 118 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::takeOverFrom(), and DefaultIEW< Impl >::updateStatus().
activeThreads
template<class Impl > std::list<ThreadID>* DefaultIEW< Impl >::activeThreads private
Pointer to list of active threads.
Definition at line 416 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::setActiveThreads(), DefaultIEW< Impl >::skidCount(), DefaultIEW< Impl >::skidsEmpty(), DefaultIEW< Impl >::tick(), and DefaultIEW< Impl >::updateStatus().
branchMispredicts
template<class Impl > Stats::Formula DefaultIEW< Impl >::branchMispredicts private
Stat for total number of mispredicted branches detected at execute.
Definition at line 450 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
commitToIEWDelay
template<class Impl > Cycles DefaultIEW< Impl >::commitToIEWDelay private
Commit to IEW delay.
Definition at line 381 of file iew.hh.
Referenced by DefaultIEW< Impl >::setTimeBuffer().
consumerInst
template<class Impl > Stats::Vector DefaultIEW< Impl >::consumerInst private
Number of instructions that wake up from producers.
Definition at line 480 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::writebackInsts().
cpu
template<class Impl > O3CPU* DefaultIEW< Impl >::cpu private
CPU pointer.
Definition at line 347 of file iew.hh.
Referenced by DefaultIEW< Impl >::activateStage(), DefaultIEW< Impl >::activityThisCycle(), DefaultIEW< Impl >::deactivateStage(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::name(), DefaultIEW< Impl >::regProbePoints(), DefaultIEW< Impl >::regStats(), DefaultIEW< Impl >::startupStage(), DefaultIEW< Impl >::takeOverFrom(), DefaultIEW< Impl >::tick(), and DefaultIEW< Impl >::wakeCPU().
dispatchStatus
template<class Impl > StageStatus DefaultIEW< Impl >::dispatchStatus[Impl::MaxThreads] private
Dispatch status.
Definition at line 120 of file iew.hh.
Referenced by DefaultIEW< Impl >::block(), DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::dispatch(), DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::takeOverFrom(), DefaultIEW< Impl >::unblock(), and DefaultIEW< Impl >::updateStatus().
dispatchWidth
template<class Impl > unsigned DefaultIEW< Impl >::dispatchWidth private
Width of dispatch, in instructions.
Definition at line 394 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), and DefaultIEW< Impl >::dispatchInsts().
exeStatus
template<class Impl > StageStatus DefaultIEW< Impl >::exeStatus private
Execute status.
Definition at line 122 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::takeOverFrom(), and DefaultIEW< Impl >::tick().
fetchRedirect
template<class Impl > bool DefaultIEW< Impl >::fetchRedirect[Impl::MaxThreads] private
Records if there is a fetch redirect on this cycle for each thread.
Definition at line 373 of file iew.hh.
Referenced by DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::takeOverFrom().
fromCommit
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultIEW< Impl >::fromCommit private
Wire to get commit's output from backwards time buffer.
Definition at line 310 of file iew.hh.
Referenced by DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::checkStall(), DefaultIEW< Impl >::setTimeBuffer(), DefaultIEW< Impl >::squash(), and DefaultIEW< Impl >::tick().
fromIssue
template<class Impl > TimeBuffer<IssueStruct>::wire DefaultIEW< Impl >::fromIssue private
Wire to read information from the issue stage time queue.
Definition at line 325 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::printAvailableInsts().
fromRename
template<class Impl > TimeBuffer<RenameStruct>::wire DefaultIEW< Impl >::fromRename private
Wire to get rename's output from rename queue.
Definition at line 319 of file iew.hh.
Referenced by DefaultIEW< Impl >::setRenameQueue(), DefaultIEW< Impl >::sortInsts(), and DefaultIEW< Impl >::validInstsFromRename().
fuPool
template<class Impl > FUPool* DefaultIEW< Impl >::fuPool
Pointer to the functional unit pool.
Definition at line 365 of file iew.hh.
Referenced by DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::takeOverFrom(), and DefaultIEW< Impl >::tick().
iewBlockCycles
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewBlockCycles private
Stat for total number of blocking cycles.
Definition at line 426 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::regStats().
iewDispatchedInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewDispatchedInsts private
Stat for total number of instructions dispatched.
Definition at line 430 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewDispLoadInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewDispLoadInsts private
Stat for total number of dispatched load instructions.
Definition at line 434 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewDispNonSpecInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewDispNonSpecInsts private
Stat for total number of dispatched non speculative instructions.
Definition at line 438 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewDispSquashedInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewDispSquashedInsts private
Stat for total number of squashed instructions dispatch skips.
Definition at line 432 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewDispStoreInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewDispStoreInsts private
Stat for total number of dispatched store instructions.
Definition at line 436 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewExecLoadInsts
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewExecLoadInsts private
Stat for total number of executed load instructions.
Definition at line 455 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::updateExeInstStats().
iewExecRate
template<class Impl > Stats::Formula DefaultIEW< Impl >::iewExecRate private
Number of instructions executed per cycle.
Definition at line 471 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
iewExecSquashedInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewExecSquashedInsts private
Stat for total number of executed store instructions.
Stat for total number of squashed instructions skipped at execute.
Definition at line 459 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regStats().
iewExecStoreInsts
template<class Impl > Stats::Formula DefaultIEW< Impl >::iewExecStoreInsts private
Number of executed store instructions.
Definition at line 469 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
iewExecutedBranches
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewExecutedBranches private
Number of executed branches.
Definition at line 467 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::updateExeInstStats().
iewExecutedInsts
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewExecutedInsts private
Stat for total number of executed instructions.
Definition at line 453 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::updateExeInstStats().
iewExecutedNop
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewExecutedNop private
Number of executed nops.
Definition at line 463 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewExecutedRefs
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewExecutedRefs private
Number of executed meomory references.
Definition at line 465 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::updateExeInstStats().
iewExecutedSwp
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewExecutedSwp private
Number of executed software prefetches.
Definition at line 461 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
iewIdleCycles
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewIdleCycles private
Stat for total number of idle cycles.
Definition at line 422 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
iewInstsToCommit
template<class Impl > Stats::Vector DefaultIEW< Impl >::iewInstsToCommit private
Number of instructions sent to commit.
Definition at line 474 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::writebackInsts().
iewIQFullEvents
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewIQFullEvents private
Stat for number of times the IQ becomes full.
Definition at line 440 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewLSQFullEvents
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewLSQFullEvents private
Stat for number of times the LSQ becomes full.
Definition at line 442 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regStats().
iewQueue
template<class Impl > TimeBuffer<IEWStruct>* DefaultIEW< Impl >::iewQueue private
IEW stage time buffer.
Holds ROB indices of instructions that can be marked as completed.
Definition at line 331 of file iew.hh.
Referenced by DefaultIEW< Impl >::instToCommit(), and DefaultIEW< Impl >::setIEWQueue().
iewSquashCycles
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewSquashCycles private
Stat for total number of squashing cycles.
Definition at line 424 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::regStats().
iewUnblockCycles
template<class Impl > Stats::Scalar DefaultIEW< Impl >::iewUnblockCycles private
Stat for total number of unblocking cycles.
Definition at line 428 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatch(), and DefaultIEW< Impl >::regStats().
instQueue
template<class Impl > IQ DefaultIEW< Impl >::instQueue
Instruction queue.
Definition at line 359 of file iew.hh.
Referenced by DefaultIEW< Impl >::blockMemInst(), DefaultIEW< Impl >::cacheUnblocked(), DefaultIEW< Impl >::checkStall(), DefaultIEW< Impl >::clearStates(), DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::drainSanityCheck(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::regStats(), DefaultIEW< Impl >::replayMemInst(), DefaultIEW< Impl >::rescheduleMemInst(), DefaultIEW< Impl >::setActiveThreads(), DefaultIEW< Impl >::setTimeBuffer(), DefaultIEW< Impl >::squash(), DefaultIEW< Impl >::startupStage(), DefaultIEW< Impl >::takeOverFrom(), DefaultIEW< Impl >::tick(), DefaultIEW< Impl >::updateStatus(), DefaultIEW< Impl >::wakeDependents(), and DefaultIEW< Impl >::writebackInsts().
insts
template<class Impl > std::queue<DynInstPtr> DefaultIEW< Impl >::insts[Impl::MaxThreads] private
Queue of all instructions coming from rename this cycle.
Definition at line 337 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::emptyRenameInsts(), DefaultIEW< Impl >::instToCommit(), DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::skidInsert(), and DefaultIEW< Impl >::sortInsts().
issueToExecQueue
template<class Impl > TimeBuffer<IssueStruct> DefaultIEW< Impl >::issueToExecQueue private
Issue stage queue.
Definition at line 322 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::takeOverFrom(), and DefaultIEW< Impl >::tick().
issueToExecuteDelay
template<class Impl > Cycles DefaultIEW< Impl >::issueToExecuteDelay private
Issue to execute delay.
What this actually represents is the amount of time it takes for an instruction to wake up, be scheduled, and sent to a FU for execution.
Definition at line 391 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW().
issueWidth
template<class Impl > unsigned DefaultIEW< Impl >::issueWidth private
Width of issue, in instructions.
Definition at line 397 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW().
ldstQueue
template<class Impl > LSQ DefaultIEW< Impl >::ldstQueue
Load / store queue.
Definition at line 362 of file iew.hh.
Referenced by DefaultIEW< Impl >::clearStates(), DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::drainSanityCheck(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::hasStoresToWB(), DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::regStats(), DefaultIEW< Impl >::setActiveThreads(), DefaultIEW< Impl >::squash(), DefaultIEW< Impl >::startupStage(), DefaultIEW< Impl >::takeOverFrom(), DefaultIEW< Impl >::tick(), and DefaultIEW< Impl >::updateStatus().
memOrderViolationEvents
template<class Impl > Stats::Scalar DefaultIEW< Impl >::memOrderViolationEvents private
Stat for total number of memory ordering violation events.
Definition at line 444 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regStats().
numThreads
template<class Impl > ThreadID DefaultIEW< Impl >::numThreads private
Number of active threads.
Definition at line 413 of file iew.hh.
Referenced by DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::sortInsts(), DefaultIEW< Impl >::startupStage(), and DefaultIEW< Impl >::takeOverFrom().
ppDispatch
template<class Impl > ProbePointArg<DynInstPtr>* DefaultIEW< Impl >::ppDispatch private
Definition at line 128 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), and DefaultIEW< Impl >::regProbePoints().
ppExecute
template<class Impl > ProbePointArg<DynInstPtr>* DefaultIEW< Impl >::ppExecute private
To probe when instruction execution begins.
Definition at line 130 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regProbePoints().
ppMispredict
template<class Impl > ProbePointArg<DynInstPtr>* DefaultIEW< Impl >::ppMispredict private
Probe points.
Definition at line 127 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regProbePoints().
ppToCommit
template<class Impl > ProbePointArg<DynInstPtr>* DefaultIEW< Impl >::ppToCommit private
To probe when instruction execution is complete.
Definition at line 132 of file iew.hh.
Referenced by DefaultIEW< Impl >::regProbePoints(), and DefaultIEW< Impl >::writebackInsts().
predictedNotTakenIncorrect
template<class Impl > Stats::Scalar DefaultIEW< Impl >::predictedNotTakenIncorrect private
Stat for total number of incorrect predicted not taken branches.
Definition at line 448 of file iew.hh.
Referenced by DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regStats().
predictedTakenIncorrect
template<class Impl > Stats::Scalar DefaultIEW< Impl >::predictedTakenIncorrect private
Stat for total number of incorrect predicted taken branches.
Definition at line 446 of file iew.hh.
Referenced by DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::executeInsts(), and DefaultIEW< Impl >::regStats().
producerInst
template<class Impl > Stats::Vector DefaultIEW< Impl >::producerInst private
Number of instructions that wake consumers.
Definition at line 478 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::writebackInsts().
renameQueue
template<class Impl > TimeBuffer<RenameStruct>* DefaultIEW< Impl >::renameQueue private
Rename instruction queue interface.
Definition at line 316 of file iew.hh.
Referenced by DefaultIEW< Impl >::setRenameQueue().
renameToIEWDelay
template<class Impl > Cycles DefaultIEW< Impl >::renameToIEWDelay private
Rename to IEW delay.
Definition at line 384 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), and DefaultIEW< Impl >::setRenameQueue().
scoreboard
template<class Impl > Scoreboard* DefaultIEW< Impl >::scoreboard private
Scoreboard pointer.
Definition at line 343 of file iew.hh.
Referenced by DefaultIEW< Impl >::setScoreboard(), and DefaultIEW< Impl >::writebackInsts().
skidBuffer
template<class Impl > std::queue<DynInstPtr> DefaultIEW< Impl >::skidBuffer[Impl::MaxThreads] private
Skid buffer between rename and IEW.
Definition at line 340 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::isDrained(), DefaultIEW< Impl >::skidCount(), DefaultIEW< Impl >::skidInsert(), DefaultIEW< Impl >::skidsEmpty(), DefaultIEW< Impl >::squash(), and DefaultIEW< Impl >::unblock().
skidBufferMax
template<class Impl > unsigned DefaultIEW< Impl >::skidBufferMax private
Maximum size of the skid buffer.
Definition at line 419 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), and DefaultIEW< Impl >::skidInsert().
timeBuffer
template<class Impl > TimeBuffer<TimeStruct>* DefaultIEW< Impl >::timeBuffer private
Pointer to main time buffer used for backwards communication.
Definition at line 304 of file iew.hh.
Referenced by DefaultIEW< Impl >::setTimeBuffer().
toCommit
template<class Impl > TimeBuffer<IEWStruct>::wire DefaultIEW< Impl >::toCommit private
Wire to write infromation heading to commit.
Definition at line 334 of file iew.hh.
Referenced by DefaultIEW< Impl >::checkMisprediction(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::setIEWQueue(), DefaultIEW< Impl >::squashDueToBranch(), DefaultIEW< Impl >::squashDueToMemOrder(), and DefaultIEW< Impl >::writebackInsts().
toFetch
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultIEW< Impl >::toFetch private
Wire to write information heading to previous stages.
Definition at line 307 of file iew.hh.
Referenced by DefaultIEW< Impl >::setTimeBuffer(), and DefaultIEW< Impl >::tick().
toRename
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultIEW< Impl >::toRename private
Wire to write information heading to previous stages.
Definition at line 313 of file iew.hh.
Referenced by DefaultIEW< Impl >::block(), DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::clearStates(), DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::emptyRenameInsts(), DefaultIEW< Impl >::setTimeBuffer(), DefaultIEW< Impl >::squash(), DefaultIEW< Impl >::startupStage(), DefaultIEW< Impl >::tick(), and DefaultIEW< Impl >::unblock().
updatedQueues
template<class Impl > bool DefaultIEW< Impl >::updatedQueues private
Records if the queues have been changed (inserted or issued insts), so that IEW knows to broadcast the updated amount of free entries.
Definition at line 378 of file iew.hh.
Referenced by DefaultIEW< Impl >::dispatchInsts(), DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::squash(), and DefaultIEW< Impl >::tick().
updateLSQNextCycle
template<class Impl > bool DefaultIEW< Impl >::updateLSQNextCycle
Records if the LSQ needs to be updated on the next cycle, so that IEW knows if there will be activity on the next cycle.
Definition at line 369 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::takeOverFrom(), and DefaultIEW< Impl >::tick().
wbCycle
template<class Impl > unsigned DefaultIEW< Impl >::wbCycle private
Cycle number within the queue of instructions being written back.
Used in case there are too many instructions writing back at the current cycle and writesbacks need to be scheduled for the future. See comments in instToCommit().
Definition at line 407 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::instToCommit(), and DefaultIEW< Impl >::tick().
wbFanout
template<class Impl > Stats::Formula DefaultIEW< Impl >::wbFanout private
Average number of woken instructions per writeback.
Definition at line 484 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
wbNumInst
template<class Impl > unsigned DefaultIEW< Impl >::wbNumInst private
Index into queue of instructions being written back.
Definition at line 400 of file iew.hh.
Referenced by DefaultIEW< Impl >::executeInsts(), DefaultIEW< Impl >::instToCommit(), and DefaultIEW< Impl >::tick().
wbRate
template<class Impl > Stats::Formula DefaultIEW< Impl >::wbRate private
Number of instructions per cycle written back.
Definition at line 482 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats().
wbStatus
template<class Impl > StageStatus DefaultIEW< Impl >::wbStatus private
Writeback status.
Definition at line 124 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), and DefaultIEW< Impl >::takeOverFrom().
wbWidth
template<class Impl > unsigned DefaultIEW< Impl >::wbWidth private
Writeback width.
Definition at line 410 of file iew.hh.
Referenced by DefaultIEW< Impl >::DefaultIEW(), DefaultIEW< Impl >::instToCommit(), and DefaultIEW< Impl >::writebackInsts().
writebackCount
template<class Impl > Stats::Vector DefaultIEW< Impl >::writebackCount private
Number of instructions that writeback.
Definition at line 476 of file iew.hh.
Referenced by DefaultIEW< Impl >::regStats(), and DefaultIEW< Impl >::writebackInsts().
wroteToTimeBuffer
template<class Impl > bool DefaultIEW< Impl >::wroteToTimeBuffer private
Records if IEW has written to the time buffer this cycle, so that the CPU can deschedule itself if there is no activity.
Definition at line 352 of file iew.hh.
Referenced by DefaultIEW< Impl >::block(), DefaultIEW< Impl >::checkSignalsAndUpdate(), DefaultIEW< Impl >::squashDueToBranch(), DefaultIEW< Impl >::squashDueToMemOrder(), DefaultIEW< Impl >::tick(), and DefaultIEW< Impl >::unblock().
The documentation for this class was generated from the following files:
cpu/o3/iew.hh
cpu/o3/iew_impl.hh