gem5: ProbePoint Class Reference
ProbePoint Class Reference abstract
ProbeListener base class; again used to simplify use of ProbePoints in containers and used as to define interface for adding removing listeners to the ProbePoint.
#include <probe.hh>
Public Member Functions
ProbePoint (ProbeManager *manager, const std::string &name)
virtual ~ProbePoint ()
virtual void addListener (ProbeListener *listener)=0
virtual void removeListener (ProbeListener *listener)=0
std::string getName () const
Protected Attributes
const std::string name
Detailed Description
ProbeListener base class; again used to simplify use of ProbePoints in containers and used as to define interface for adding removing listeners to the ProbePoint.
Definition at line 135 of file probe.hh.
Constructor & Destructor Documentation
ProbePoint()
ProbePoint::ProbePoint (ProbeManager * manager, const std::string & name)
Definition at line 45 of file probe.cc.
References ProbeManager::addPoint().
~ProbePoint()
virtual ProbePoint::~ProbePoint () inline virtual
Definition at line 141 of file probe.hh.
Member Function Documentation
addListener()
virtual void ProbePoint::addListener (ProbeListener * listener) pure virtual
Implemented in ProbePointArg< Arg >, ProbePointArg< double >, ProbePointArg< std::pair< SimpleThread *, const RefCountingPtr > >, ProbePointArg< DynInstPtr >, ProbePointArg< std::pair >, ProbePointArg< std::pair< DynInstPtr, Packet > >, ProbePointArg< Packet >, ProbePointArg< bool >, and ProbePointArg< RequestPtr >.
getName()
std::string ProbePoint::getName () const inline
Definition at line 145 of file probe.hh.
References name().
Referenced by ProbeManager::addPoint().
removeListener()
virtual void ProbePoint::removeListener (ProbeListener * listener) pure virtual
Implemented in ProbePointArg< Arg >, ProbePointArg< double >, ProbePointArg< std::pair< SimpleThread *, const RefCountingPtr > >, ProbePointArg< DynInstPtr >, ProbePointArg< std::pair >, ProbePointArg< std::pair< DynInstPtr, Packet > >, ProbePointArg< Packet >, ProbePointArg< bool >, and ProbePointArg< RequestPtr >.
Member Data Documentation
name
const std::string ProbePoint::name protected
Definition at line 138 of file probe.hh.
The documentation for this class was generated from the following files:
sim/probe/probe.hh
sim/probe/probe.cc