gem5: EtherTapStub Class Reference
EtherTapStub Class Reference
#include <ethertap.hh>
Public Types
typedef EtherTapStubParams Params
Public Types inherited from EtherTapBase
typedef EtherTapBaseParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
EtherTapStub (const Params *p)
~EtherTapStub ()
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EtherTapBase
EtherTapBase (const Params *p)
virtual ~EtherTapBase ()
const Params * params () const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
bool recvSimulated (EthPacketPtr packet)
void sendSimulated (void *data, size_t len)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
void attach (int fd)
void detach ()
void recvReal (int revent) override
bool sendReal (const void *data, size_t len) override
Protected Member Functions inherited from EtherTapBase
void pollFd (int fd)
void stopPolling ()
void retransmit ()
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
TapListener * listener
int socket
uint32_t buffer_used
uint32_t frame_len
Protected Attributes inherited from EtherTapBase
uint8_t * buffer
int buflen
EtherDump * dump
TapEvent * event
EtherTapInt * interface
std::queue< EthPacketPtr > packetBuffer
EventFunctionWrapper txEvent
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class TapListener
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 138 of file ethertap.hh.
Member Typedef Documentation
Params
typedef EtherTapStubParams EtherTapStub::Params
Definition at line 141 of file ethertap.hh.
Constructor & Destructor Documentation
EtherTapStub()
EtherTapStub::EtherTapStub (const Params * p)
Definition at line 288 of file ethertap.cc.
References ListenSocket::allDisabled(), fatal, TapListener::listen(), listener, and TapListener.
Referenced by sendReal().
~EtherTapStub()
EtherTapStub::~EtherTapStub ()
Definition at line 297 of file ethertap.cc.
References listener.
Member Function Documentation
attach()
void EtherTapStub::attach (int fd) protected
Definition at line 324 of file ethertap.cc.
References buffer_used, DPRINTF, ArmISA::fd, frame_len, EtherTapBase::pollFd(), and socket.
detach()
void EtherTapStub::detach () protected
Definition at line 337 of file ethertap.cc.
References DPRINTF, socket, and EtherTapBase::stopPolling().
Referenced by recvReal().
params()
const Params* EtherTapStub::params () const inline
Definition at line 146 of file ethertap.hh.
References SimObject::_params, EtherTapBase::serialize(), and EtherTapBase::unserialize().
recvReal()
void EtherTapStub::recvReal (int revent) override protected virtual
Implements EtherTapBase.
Definition at line 346 of file ethertap.cc.
References EtherTapBase::buffer, buffer_used, EtherTapBase::buflen, detach(), DPRINTF, frame_len, ArmISA::len, EtherTapBase::sendSimulated(), and socket.
sendReal()
bool EtherTapStub::sendReal (const void * data, size_t len) override protected virtual
Implements EtherTapBase.
Definition at line 392 of file ethertap.cc.
References EtherTapBase::buffer, EtherTapBase::buflen, data, EtherTapBase::EtherTapBase(), EtherTapStub(), ArmISA::fd, frame_len, ArmISA::len, ArmISA::n, MipsISA::p, panic, EtherTapBase::pollFd(), EtherTapBase::sendSimulated(), socket, and EtherTapBase::stopPolling().
serialize()
void EtherTapStub::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from EtherTapBase.
Definition at line 303 of file ethertap.cc.
References buffer_used, frame_len, EtherTapBase::serialize(), SERIALIZE_SCALAR, and socket.
unserialize()
void EtherTapStub::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from EtherTapBase.
Definition at line 313 of file ethertap.cc.
References buffer_used, frame_len, socket, EtherTapBase::unserialize(), and UNSERIALIZE_SCALAR.
Friends And Related Function Documentation
TapListener
friend class TapListener friend
Definition at line 156 of file ethertap.hh.
Referenced by EtherTapStub().
Member Data Documentation
buffer_used
uint32_t EtherTapStub::buffer_used protected
Definition at line 164 of file ethertap.hh.
Referenced by attach(), recvReal(), serialize(), and unserialize().
frame_len
uint32_t EtherTapStub::frame_len protected
Definition at line 165 of file ethertap.hh.
Referenced by attach(), recvReal(), sendReal(), serialize(), and unserialize().
listener
TapListener* EtherTapStub::listener protected
Definition at line 157 of file ethertap.hh.
Referenced by EtherTapStub(), and ~EtherTapStub().
socket
int EtherTapStub::socket protected
Definition at line 159 of file ethertap.hh.
Referenced by attach(), detach(), recvReal(), sendReal(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/net/ethertap.hh
dev/net/ethertap.cc