gem5: LSQUnit< Impl >::LSQEntry Class Reference
LSQUnit< Impl >::LSQEntry Class Reference
Public Member Functions
LSQEntry ()
Constructs an empty store queue entry.
~LSQEntry ()
void clear ()
void set (const DynInstPtr &inst)
LSQRequest * request ()
void setRequest (LSQRequest *r)
bool hasRequest ()
bool valid () const
Member accessors.
uint32_t & size ()
const uint32_t & size () const
const DynInstPtr & instruction () const
Private Attributes
DynInstPtr inst
The instruction.
LSQRequest * req
The request.
uint32_t _size
The size of the operation.
bool _valid
Valid entry.
Detailed Description
template<class Impl>
class LSQUnit< Impl >::LSQEntry
Definition at line 95 of file lsq_unit.hh.
Constructor & Destructor Documentation
LSQEntry()
template<class Impl> LSQUnit< Impl >::LSQEntry::LSQEntry () inline
Constructs an empty store queue entry.
Definition at line 108 of file lsq_unit.hh.
~LSQEntry()
template<class Impl> LSQUnit< Impl >::LSQEntry::~LSQEntry () inline
Definition at line 113 of file lsq_unit.hh.
Member Function Documentation
clear()
template<class Impl> void LSQUnit< Impl >::LSQEntry::clear () inline
Definition at line 123 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::SQEntry::clear().
hasRequest()
template<class Impl> bool LSQUnit< Impl >::LSQEntry::hasRequest () inline
Definition at line 144 of file lsq_unit.hh.
instruction()
template<class Impl> const DynInstPtr& LSQUnit< Impl >::LSQEntry::instruction () const inline
Definition at line 150 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::inst.
Referenced by LSQUnit< Impl >::read().
request()
template<class Impl> LSQRequest* LSQUnit< Impl >::LSQEntry::request () inline
Definition at line 142 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::req.
set()
template<class Impl> void LSQUnit< Impl >::LSQEntry::set (const DynInstPtr & inst) inline
Definition at line 135 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::inst.
Referenced by LSQUnit< Impl >::SQEntry::set().
setRequest()
template<class Impl> void LSQUnit< Impl >::LSQEntry::setRequest (LSQRequest * r) inline
Definition at line 143 of file lsq_unit.hh.
References MipsISA::r.
Referenced by LSQUnit< Impl >::read().
size() [1/2]
template<class Impl> uint32_t& LSQUnit< Impl >::LSQEntry::size () inline
Definition at line 148 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::_size.
Referenced by LSQUnit< Impl >::write().
size() [2/2]
template<class Impl> const uint32_t& LSQUnit< Impl >::LSQEntry::size () const inline
Definition at line 149 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::_size.
valid()
template<class Impl> bool LSQUnit< Impl >::LSQEntry::valid () const inline
Member accessors.
Definition at line 147 of file lsq_unit.hh.
References LSQUnit< Impl >::LSQEntry::_valid.
Referenced by LSQUnit< Impl >::write().
Member Data Documentation
_size
template<class Impl> uint32_t LSQUnit< Impl >::LSQEntry::_size private
The size of the operation.
Definition at line 103 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::LSQEntry::size().
_valid
template<class Impl> bool LSQUnit< Impl >::LSQEntry::_valid private
Valid entry.
Definition at line 105 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::LSQEntry::valid().
inst
template<class Impl> DynInstPtr LSQUnit< Impl >::LSQEntry::inst private
The instruction.
Definition at line 99 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::LSQEntry::instruction(), LSQUnit< Impl >::LSQUnit(), LSQUnit< Impl >::LSQEntry::set(), and LSQUnit< Impl >::SQEntry::set().
req
template<class Impl> LSQRequest* LSQUnit< Impl >::LSQEntry::req private
The request.
Definition at line 101 of file lsq_unit.hh.
Referenced by LSQUnit< Impl >::LSQEntry::request().
The documentation for this class was generated from the following file:
cpu/o3/lsq_unit.hh