gem5: TapListener Class Reference
TapListener Class Reference
Classes
class Event
Public Member Functions
TapListener (EtherTapStub *t, int p)
~TapListener ()
void listen ()
Protected Member Functions
void accept ()
Protected Attributes
Event * event
ListenSocket listener
EtherTapStub * tap
int port
Friends
class Event
Detailed Description
Definition at line 227 of file ethertap.cc.
Constructor & Destructor Documentation
TapListener()
TapListener::TapListener (EtherTapStub * t, int p) inline
Definition at line 252 of file ethertap.cc.
~TapListener()
TapListener::~TapListener () inline
Definition at line 253 of file ethertap.cc.
References EtherTapBase::event.
Member Function Documentation
accept()
void TapListener::accept () protected
Definition at line 272 of file ethertap.cc.
References panic.
Referenced by TapListener::Event::process().
listen()
void TapListener::listen ()
Definition at line 259 of file ethertap.cc.
References ccprintf(), DPRINTF, EtherTapBase::event, Event::Event(), pollQueue, and PollQueue::schedule().
Referenced by EtherTapStub::EtherTapStub().
Friends And Related Function Documentation
Event
friend class Event friend
Definition at line 241 of file ethertap.cc.
Member Data Documentation
event
Event* TapListener::event protected
Definition at line 242 of file ethertap.cc.
listener
ListenSocket TapListener::listener protected
Definition at line 247 of file ethertap.cc.
port
int TapListener::port protected
Definition at line 249 of file ethertap.cc.
tap
EtherTapStub* TapListener::tap protected
Definition at line 248 of file ethertap.cc.
The documentation for this class was generated from the following file:
dev/net/ethertap.cc