gem5: Process Class Reference
Process Class Reference abstract
#include <process.hh>
Classes
class Loader
Each instance of a Loader subclass will have a chance to try to load an object file when tryLoaders is called.
Public Member Functions
Process (ProcessParams *params, EmulationPageTable *pTable, ObjectFile *obj_file)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
DrainState drain () override
Notify an object that it needs to drain its state.
virtual void syscall (int64_t callnum, ThreadContext *tc, Fault *fault)
virtual RegVal getSyscallArg (ThreadContext *tc, int &i)=0
virtual RegVal getSyscallArg (ThreadContext *tc, int &i, int width)
virtual void setSyscallArg (ThreadContext *tc, int i, RegVal val)=0
virtual void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)=0
virtual SyscallDesc * getDesc (int callnum)=0
uint64_t uid ()
uint64_t euid ()
uint64_t gid ()
uint64_t egid ()
uint64_t pid ()
uint64_t ppid ()
uint64_t pgid ()
void pgid (uint64_t pgid)
uint64_t tgid ()
const char * progName () const
EmulatedDriver * findDriver (std::string filename)
Find an emulated device driver.
void updateBias ()
Addr getBias ()
Addr getStartPC ()
ObjectFile * getInterpreter ()
void regStats () override
Callback to set stat parameters.
void allocateMem (Addr vaddr, int64_t size, bool clobber=false)
bool fixupStackFault (Addr vaddr)
Attempt to fix up a fault at vaddr by allocating a page on the stack.
void assignThreadContext (ContextID context_id)
ThreadContext * findFreeContext ()
void revokeThreadContext (int context_id)
After delegating a thread context to a child process no longer should relate to the ThreadContext.
virtual bool mmapGrowsDown () const
Does mmap region grow upward or downward from mmapEnd? Most platforms grow downward, but a few (such as Alpha) grow upward instead, so they can override this method to return false.
bool map (Addr vaddr, Addr paddr, int size, bool cacheable=true)
Maps a contiguous range of virtual addresses in this process's address space to a contiguous range of physical addresses.
void replicatePage (Addr vaddr, Addr new_paddr, ThreadContext *old_tc, ThreadContext *new_tc, bool alloc_page)
virtual void clone (ThreadContext *old_tc, ThreadContext *new_tc, Process *new_p, RegVal flags)
std::string absolutePath (const std::string &path, bool host_fs)
Return an absolute path given a relative path paired with the current working directory of the process running under simulation.
std::string checkPathRedirect (const std::string &filename)
Redirect file path if it matches any keys initialized by system object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Static Public Member Functions
static Process * tryLoaders (ProcessParams *params, ObjectFile *obj_file)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes
std::vector< ContextID > contextIds
System * system
Stats::Scalar numSyscalls
bool useArchPT
bool kvmInSE
bool useForClone
EmulationPageTable * pTable
SETranslatingPortProxy initVirtMem
ObjectFile * objFile
MemoryImage image
MemoryImage interpImage
std::vector< std::string > argv
std::vector< std::string > envp
std::string executable
std::string tgtCwd
The cwd members are used to track changes to the current working directory for the purpose of executing system calls which depend on relative paths (i.e.
std::string hostCwd
std::string release
uint64_t _uid
uint64_t _euid
uint64_t _gid
uint64_t _egid
uint64_t _pid
uint64_t _ppid
uint64_t _pgid
uint64_t _tgid
std::vector< EmulatedDriver * > drivers
std::shared_ptr< FDArray > fds
bool * exitGroup
std::shared_ptr< MemState > memState
uint64_t childClearTID
Calls a futex wakeup at the address specified by this pointer when this process exits.
bool * sigchld
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 64 of file process.hh.
Constructor & Destructor Documentation
Process()
Process::Process (ProcessParams * params, EmulationPageTable * pTable, ObjectFile * obj_file)
Linux bundles together processes into this concept called a thread group. The thread group is responsible for recording which processes behave as threads within a process context. The thread group leader is the process who's tgid is equal to its pid. Other processes which belong to the thread group, but do not lead the thread group, are treated as child threads. These threads are created by the clone system call with options specified to create threads (differing from the options used to implement a fork). By default, set up the tgid/pid with a new, equivalent value. If CLONE_THREAD is specified, patch the tgid value with the old process' value.
Definition at line 117 of file process.cc.
References _pid, _tgid, ImageFile::buildImage(), debugSymbolTable, exitGroup, fatal, image, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), ObjectFile::loadWeakSymbols(), System::maxPID, objFile, System::PIDs, sigchld, and system.
Member Function Documentation
absolutePath()
std::string Process::absolutePath (const std::string & path, bool host_fs)
Return an absolute path given a relative path paired with the current working directory of the process running under simulation.
Parameters
path The relative path (generally a filename) that needs the current working directory prepended.
host_fs A flag which determines whether to return a path for the host filesystem or the filesystem of the process running under simulation. Only matters if filesysem redirection is used to replace files (or directories) that would normally appear via the host filesystem.
Returns
String containing an absolute path.
Definition at line 550 of file process.cc.
References createObjectFile(), executable, fatal_if, hostCwd, normalize(), startswith(), tgtCwd, and tryLoaders().
Referenced by checkPathRedirect().
allocateMem()
void Process::allocateMem (Addr vaddr, int64_t size, bool clobber = false)
Definition at line 343 of file process.cc.
References System::allocPhysPages(), EmulationPageTable::Clobber, divCeil(), EmulationPageTable::map(), AlphaISA::PageBytes, pTable, and system.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), fixupStackFault(), ArmLinuxProcess32::initState(), X86ISA::X86_64Process::initState(), X86ISA::I386Process::initState(), Shader::mmap(), progName(), SETranslatingPortProxy::tryMemsetBlob(), and SETranslatingPortProxy::tryWriteBlob().
assignThreadContext()
void Process::assignThreadContext (ContextID context_id) inline
Definition at line 125 of file process.hh.
References contextIds, findFreeContext(), and revokeThreadContext().
Referenced by cloneFunc(), execveFunc(), and BaseCPU::registerThreadContexts().
checkPathRedirect()
std::string Process::checkPathRedirect (const std::string & filename)
Redirect file path if it matches any keys initialized by system object.
Parameters
filename An input parameter containing either a relative path or an absolute path. If given a relative path, the path will be prepended to the current working directory of the simulation with respect to the host filesystem.
Returns
String containing an absolute path.
Definition at line 469 of file process.cc.
References absolutePath(), Serializable::path, System::redirectPaths, startswith(), and system.
clone()
void Process::clone (ThreadContext * old_tc, ThreadContext * new_tc, Process * new_p, RegVal flags) virtual
Share the process memory address space between the new process and the old process. Changes in one will be visible in the other due to the pointer use.
Duplicate the process memory address space. The state needs to be copied over (rather than using pointers to share everything).
The parent and child file descriptors are shared because the two FDArray pointers are pointing to the same FDArray. Opening and closing file descriptors will be visible to both processes.
Copy the file descriptors from the old process into the new child process. The file descriptors entry can be opened and closed independently of the other process being considered. The host file descriptors are also dup'd so that the flags for the host file descriptor is independent of the other process.
Reimplemented in X86ISA::I386Process, X86ISA::X86_64Process, X86ISA::X86Process, X86ISA::I386LinuxProcess, and X86ISA::X86_64LinuxProcess.
Definition at line 177 of file process.cc.
References _tgid, argv, CLONE_FILES, CLONE_THREAD, CLONE_VM, envp, exitGroup, fds, EmulationPageTable::getMappings(), HBFDEntry::getSimFD(), ThreadContext::getVirtProxy(), map(), memState, pTable, replicatePage(), SETranslatingPortProxy::setPageTable(), HBFDEntry::setSimFD(), EmulationPageTable::translate(), and MipsISA::vaddr.
Referenced by X86ISA::X86Process::clone(), and mmapGrowsDown().
drain()
DrainState Process::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 336 of file process.cc.
References Drained, and fds.
egid()
uint64_t Process::egid () inline
Definition at line 88 of file process.hh.
References _egid.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and getegidFunc().
euid()
uint64_t Process::euid () inline
Definition at line 86 of file process.hh.
References _euid.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and geteuidFunc().
findDriver()
EmulatedDriver * Process::findDriver (std::string filename)
Find an emulated device driver.
Parameters
filename Name of the device (under /dev)
Returns
Pointer to driver object if found, else nullptr
Definition at line 458 of file process.cc.
References ArmISA::d, and drivers.
Referenced by progName().
findFreeContext()
ThreadContext * Process::findFreeContext ()
Definition at line 284 of file process.cc.
References ThreadContext::Halted, system, and System::threadContexts.
Referenced by assignThreadContext().
fixupStackFault()
bool Process::fixupStackFault (Addr vaddr)
Attempt to fix up a fault at vaddr by allocating a page on the stack.
Returns
Whether the fault has been fixed.
Definition at line 372 of file process.cc.
References allocateMem(), fatal, inform, memState, AlphaISA::PageBytes, and roundDown().
Referenced by GenericPageTableFault::invoke(), AlphaISA::NDtbMissFault::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), X86ISA::m5PageFault(), progName(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), ComputeUnit::sendRequest(), X86ISA::TLB::translate(), and SETranslatingPortProxy::tryWriteBlob().
getBias()
Addr Process::getBias ()
Definition at line 534 of file process.cc.
References ObjectFile::bias(), getInterpreter(), and objFile.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and progName().
getDesc()
virtual SyscallDesc* Process::getDesc (int callnum) pure virtual
Implemented in ArmLinuxProcess64, SparcISA::Sparc64LinuxProcess, ArmFreebsdProcess64, X86ISA::X86Process, ArmLinuxProcess32, ArmFreebsdProcess32, RiscvLinuxProcess32, SparcISA::Sparc32LinuxProcess, RiscvLinuxProcess64, SparcISA::SparcSolarisProcess, MipsLinuxProcess, AlphaISA::AlphaLinuxProcess, and PowerLinuxProcess.
Referenced by syscall().
getInterpreter()
ObjectFile * Process::getInterpreter ()
Definition at line 528 of file process.cc.
References ObjectFile::getInterpreter(), and objFile.
Referenced by getBias(), getStartPC(), and progName().
getStartPC()
Addr Process::getStartPC ()
Definition at line 542 of file process.cc.
References ObjectFile::entryPoint(), getInterpreter(), and objFile.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and progName().
getSyscallArg() [1/2]
virtual RegVal Process::getSyscallArg (ThreadContext * tc, int & i) pure virtual
Implemented in X86ISA::I386Process, Sparc64Process, X86ISA::X86_64Process, ArmProcess64, Sparc32Process, ArmProcess32, MipsProcess, RiscvProcess, PowerProcess, AlphaProcess, and PowerLinuxProcess.
Referenced by archPrctlFunc(), faccessatFunc(), fstatat64Func(), futexFunc(), getrlimitFunc(), getrusageFunc(), getSyscallArg(), ClDriver::ioctl(), mremapFunc(), readlinkatFunc(), renameatFunc(), setpgidFunc(), setTidAddressFunc(), setTLSFunc32(), setTLSFunc64(), Sparc32Process::Sparc32Process(), Sparc64Process::Sparc64Process(), sysctlFunc(), tgkillFunc(), timeFunc(), and unlinkatFunc().
getSyscallArg() [2/2]
RegVal Process::getSyscallArg (ThreadContext * tc, int & i, int width) virtual
Reimplemented in X86ISA::I386Process, ArmProcess64, and ArmProcess32.
Definition at line 452 of file process.cc.
References getSyscallArg().
gid()
uint64_t Process::gid () inline
Definition at line 87 of file process.hh.
References _gid.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and getgidFunc().
init()
void Process::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 307 of file process.cc.
References ImageFile::buildImage(), ObjectFile::getInterpreter(), interpImage, objFile, and updateBias().
initState()
void Process::initState () override virtual
initState() is called on each SimObject when not restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from SimObject.
Definition at line 317 of file process.cc.
References ThreadContext::activate(), contextIds, fatal, System::getThreadContext(), image, EmulationPageTable::initState(), initVirtMem, interpImage, SimObject::name(), pTable, system, and MemoryImage::write().
Referenced by cloneFunc(), execveFunc(), AlphaProcess::initState(), MipsProcess::initState(), PowerProcess::initState(), SparcProcess::initState(), RiscvProcess64::initState(), RiscvProcess32::initState(), ArmProcess32::initState(), ArmProcess64::initState(), X86ISA::X86_64Process::initState(), and X86ISA::I386Process::initState().
map()
bool Process::map (Addr vaddr, Addr paddr, int size, bool cacheable = true)
Maps a contiguous range of virtual addresses in this process's address space to a contiguous range of physical addresses.
This function exists primarily to expose the map operation to python, so that configuration scripts can set up mappings in SE mode.
Parameters
vaddr The starting virtual address of the range.
paddr The starting physical address of the range.
size The length of the range in bytes.
cacheable Specifies whether accesses are cacheable.
Returns
True if the map operation was successful. (At this point in time, the map operation always succeeds.)
Definition at line 431 of file process.cc.
References EmulationPageTable::map(), pTable, and EmulationPageTable::Uncacheable.
Referenced by clone(), and mmapGrowsDown().
mmapGrowsDown()
virtual bool Process::mmapGrowsDown () const inline virtual
Does mmap region grow upward or downward from mmapEnd? Most platforms grow downward, but a few (such as Alpha) grow upward instead, so they can override this method to return false.
Reimplemented in AlphaProcess, and RiscvProcess.
Definition at line 144 of file process.hh.
References clone(), map(), and replicatePage().
Referenced by Shader::mmap(), and updateBias().
pgid() [1/2]
uint64_t Process::pgid () inline
Definition at line 91 of file process.hh.
References _pgid.
Referenced by getpgrpFunc(), and setpgidFunc().
pgid() [2/2]
void Process::pgid (uint64_t pgid) inline
Definition at line 92 of file process.hh.
References _pgid, and pgid().
Referenced by pgid().
pid()
uint64_t Process::pid () inline
Definition at line 89 of file process.hh.
References _pid.
Referenced by cloneFunc(), exitImpl(), gettidFunc(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), setpgidFunc(), and tgkillFunc().
ppid()
uint64_t Process::ppid () inline
Definition at line 90 of file process.hh.
References _ppid.
Referenced by getppidFunc().
progName()
const char* Process::progName () const inline
Definition at line 95 of file process.hh.
References allocateMem(), executable, findDriver(), fixupStackFault(), getBias(), getInterpreter(), getStartPC(), regStats(), updateBias(), and MipsISA::vaddr.
regStats()
void Process::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 271 of file process.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numSyscalls, and Stats::Group::regStats().
Referenced by progName().
replicatePage()
void Process::replicatePage (Addr vaddr, Addr new_paddr, ThreadContext * old_tc, ThreadContext * new_tc, bool alloc_page)
Definition at line 353 of file process.cc.
References System::allocPhysPages(), ThreadContext::getVirtProxy(), EmulationPageTable::map(), AlphaISA::PageBytes, pTable, PortProxy::readBlob(), system, and PortProxy::writeBlob().
Referenced by clone(), and mmapGrowsDown().
revokeThreadContext()
void Process::revokeThreadContext (int context_id)
After delegating a thread context to a child process no longer should relate to the ThreadContext.
Definition at line 294 of file process.cc.
References contextIds, and warn.
Referenced by assignThreadContext(), and cloneFunc().
serialize()
void Process::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Checkpoints for file descriptors currently do not work. Need to come back and fix them at a later date.
Implements Serializable.
Definition at line 402 of file process.cc.
References memState, pTable, EmulationPageTable::serialize(), and warn.
setSyscallArg()
virtual void Process::setSyscallArg (ThreadContext * tc, int i, RegVal val) pure virtual
Implemented in X86ISA::I386Process, Sparc64Process, X86ISA::X86_64Process, Sparc32Process, ArmProcess64, ArmProcess32, MipsProcess, RiscvProcess, PowerProcess, AlphaProcess, and PowerLinuxProcess.
Referenced by Sparc32Process::Sparc32Process(), and Sparc64Process::Sparc64Process().
setSyscallReturn()
virtual void Process::setSyscallReturn (ThreadContext * tc, SyscallReturn return_value) pure virtual
Implemented in ArmProcess64, ArmProcess32, X86ISA::X86Process, SparcProcess, MipsProcess, RiscvProcess, PowerProcess, and AlphaProcess.
Referenced by cloneFunc().
syscall()
void Process::syscall (int64_t callnum, ThreadContext * tc, Fault * fault) virtual
Reimplemented in X86ISA::I386Process.
Definition at line 440 of file process.cc.
References SyscallDesc::doSyscall(), fatal, getDesc(), and numSyscalls.
Referenced by O3ThreadState< Impl >::syscall(), and X86ISA::I386Process::syscall().
tgid()
uint64_t Process::tgid () inline
Definition at line 93 of file process.hh.
References _tgid.
Referenced by exitImpl(), getpidFunc(), and tgkillFunc().
tryLoaders()
Process * Process::tryLoaders (ProcessParams * params, ObjectFile * obj_file) static
Definition at line 98 of file process.cc.
References MipsISA::p.
Referenced by absolutePath(), and Process::Loader::~Loader().
uid()
uint64_t Process::uid () inline
Definition at line 85 of file process.hh.
References _uid.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and getuidFunc().
unserialize()
void Process::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Checkpoints for file descriptors currently do not work. Need to come back and fix them at a later date.
Implements Serializable.
Definition at line 415 of file process.cc.
References memState, pTable, EmulationPageTable::unserialize(), and warn.
Referenced by AlphaProcess::unserialize().
updateBias()
void Process::updateBias ()
Definition at line 502 of file process.cc.
References ObjectFile::getInterpreter(), ObjectFile::mapSize(), memState, mmapGrowsDown(), objFile, AlphaISA::PageBytes, ObjectFile::relocatable(), roundUp(), and ObjectFile::updateBias().
Referenced by init(), and progName().
Member Data Documentation
_egid
uint64_t Process::_egid
Definition at line 270 of file process.hh.
Referenced by egid().
_euid
uint64_t Process::_euid
Definition at line 268 of file process.hh.
Referenced by euid().
_gid
uint64_t Process::_gid
Definition at line 269 of file process.hh.
Referenced by gid().
_pgid
uint64_t Process::_pgid
Definition at line 275 of file process.hh.
Referenced by pgid().
_pid
uint64_t Process::_pid
Definition at line 273 of file process.hh.
Referenced by SparcProcess::initState(), pid(), Process(), and AlphaProcess::setupASNReg().
_ppid
uint64_t Process::_ppid
Definition at line 274 of file process.hh.
Referenced by ppid().
_tgid
uint64_t Process::_tgid
Definition at line 276 of file process.hh.
Referenced by clone(), Process(), and tgid().
_uid
uint64_t Process::_uid
Definition at line 267 of file process.hh.
Referenced by uid().
argv
std::vector<std::string> Process::argv
Definition at line 221 of file process.hh.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and clone().
childClearTID
uint64_t Process::childClearTID
Calls a futex wakeup at the address specified by this pointer when this process exits.
Definition at line 290 of file process.hh.
Referenced by cloneFunc().
contextIds
std::vector<ContextID> Process::contextIds
Definition at line 168 of file process.hh.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), ArmProcess64::armHwcapImpl(), assignThreadContext(), AlphaProcess::initState(), SparcProcess::initState(), RiscvProcess64::initState(), ArmLinuxProcess32::initState(), initState(), RiscvProcess32::initState(), ArmProcess32::initState(), ArmProcess64::initState(), Sparc32Process::initState(), X86ISA::X86_64Process::initState(), Sparc64Process::initState(), X86ISA::I386Process::initState(), revokeThreadContext(), and AlphaProcess::setupASNReg().
drivers
std::vector<EmulatedDriver *> Process::drivers
Definition at line 279 of file process.hh.
Referenced by findDriver().
envp
std::vector<std::string> Process::envp
Definition at line 222 of file process.hh.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), and clone().
executable
std::string Process::executable
Definition at line 223 of file process.hh.
Referenced by absolutePath(), and progName().
exitGroup
bool* Process::exitGroup
Definition at line 283 of file process.hh.
Referenced by clone(), and Process().
fds
std::shared_ptr<FDArray> Process::fds
Definition at line 281 of file process.hh.
Referenced by clone(), drain(), and execveFunc().
hostCwd
std::string Process::hostCwd
Definition at line 261 of file process.hh.
Referenced by absolutePath().
image
MemoryImage Process::image
Definition at line 219 of file process.hh.
Referenced by AlphaProcess::AlphaProcess(), PowerProcess::argsInit(), ArmProcess32::ArmProcess32(), ArmProcess64::ArmProcess64(), X86ISA::I386Process::I386Process(), initState(), MipsProcess::MipsProcess(), PowerProcess::PowerProcess(), Process(), RiscvProcess32::RiscvProcess32(), RiscvProcess64::RiscvProcess64(), Sparc32Process::Sparc32Process(), Sparc64Process::Sparc64Process(), and X86ISA::X86_64Process::X86_64Process().
initVirtMem
SETranslatingPortProxy Process::initVirtMem
Definition at line 184 of file process.hh.
Referenced by AlphaProcess::argsInit(), RiscvProcess::argsInit(), MipsProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), Sparc32Process::argsInit(), Sparc64Process::argsInit(), initState(), X86ISA::X86_64Process::initState(), and X86ISA::I386Process::initState().
interpImage
MemoryImage Process::interpImage
Definition at line 220 of file process.hh.
Referenced by PowerProcess::argsInit(), init(), and initState().
kvmInSE
bool Process::kvmInSE
Definition at line 178 of file process.hh.
Referenced by X86ISA::I386Process::I386Process(), and X86ISA::X86_64Process::initState().
memState
std::shared_ptr<MemState> Process::memState
Definition at line 284 of file process.hh.
Referenced by AlphaProcess::AlphaProcess(), AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), ArmProcess32::ArmProcess32(), ArmProcess64::ArmProcess64(), clone(), fixupStackFault(), X86ISA::I386Process::I386Process(), MipsProcess::MipsProcess(), Shader::mmap(), PowerProcess::PowerProcess(), RiscvProcess32::RiscvProcess32(), RiscvProcess64::RiscvProcess64(), serialize(), Sparc32Process::Sparc32Process(), Sparc64Process::Sparc64Process(), unserialize(), updateBias(), and X86ISA::X86_64Process::X86_64Process().
numSyscalls
Stats::Scalar Process::numSyscalls
Definition at line 173 of file process.hh.
Referenced by regStats(), and syscall().
objFile
ObjectFile* Process::objFile
Definition at line 218 of file process.hh.
Referenced by AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), getBias(), getInterpreter(), getStartPC(), init(), Process(), ArmProcess32::setSyscallReturn(), ArmProcess64::setSyscallReturn(), and updateBias().
pTable
EmulationPageTable* Process::pTable
Definition at line 182 of file process.hh.
Referenced by SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), PowerISA::RemoteGDB::acc(), RiscvISA::RemoteGDB::acc(), X86ISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), allocateMem(), clone(), cloneFunc(), initState(), X86ISA::X86_64Process::initState(), AlphaISA::NDtbMissFault::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), AlphaISA::ItbPageFault::invoke(), map(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), replicatePage(), ComputeUnit::sendRequest(), serialize(), X86ISA::TLB::translate(), RiscvISA::TLB::translateData(), MipsISA::TLB::translateData(), PowerISA::TLB::translateData(), RiscvISA::TLB::translateInst(), MipsISA::TLB::translateInst(), PowerISA::TLB::translateInst(), ArmISA::TLB::translateSe(), and unserialize().
release
std::string Process::release
Definition at line 264 of file process.hh.
sigchld
bool* Process::sigchld
Definition at line 293 of file process.hh.
Referenced by cloneFunc(), execveFunc(), and Process().
system
System* Process::system
Definition at line 171 of file process.hh.
Referenced by allocateMem(), AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), ArmProcess64::armHwcapImpl(), checkPathRedirect(), findFreeContext(), AlphaProcess::initState(), SparcProcess::initState(), RiscvProcess64::initState(), ArmLinuxProcess32::initState(), initState(), RiscvProcess32::initState(), ArmProcess32::initState(), Sparc32Process::initState(), ArmProcess64::initState(), X86ISA::X86_64Process::initState(), Sparc64Process::initState(), X86ISA::I386Process::initState(), Process(), Linux::procMeminfo(), replicatePage(), and AlphaProcess::setupASNReg().
tgtCwd
std::string Process::tgtCwd
The cwd members are used to track changes to the current working directory for the purpose of executing system calls which depend on relative paths (i.e.
open, chdir).
The tgt member and host member may differ if the path for the current working directory is redirected to point to a different location (i.e. cd /proc should point to '/m5out/fs/proc' instead of '/proc').
Definition at line 260 of file process.hh.
Referenced by absolutePath(), and Linux::etcPasswd().
useArchPT
bool Process::useArchPT
Definition at line 176 of file process.hh.
useForClone
bool Process::useForClone
Definition at line 180 of file process.hh.
Referenced by cloneFunc(), and X86ISA::X86_64Process::initState().
The documentation for this class was generated from the following files:
sim/process.hh
sim/process.cc