gem5: sc_dt::sc_concatref Class Reference
sc_dt::sc_concatref Class Reference
#include <sc_concatref.hh>
Public Types
enum concat_flags { cf_none = 0, cf_xz_present = 1 }
Public Member Functions
void initialize (sc_value_base &left, sc_value_base &right)
void initialize (const sc_value_base &left, const sc_value_base &right)
virtual ~sc_concatref ()
unsigned int length () const
virtual int concat_length (bool *xz_present_p) const
virtual void concat_clear_data (bool to_ones)
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
uint64 to_uint64 () const
const sc_unsigned & value () const
int64 to_int64 () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
double to_double () const
void to_sc_signed (sc_signed &target) const
void to_sc_unsigned (sc_unsigned &target) const
operator uint64 () const
operator const sc_unsigned & () const
sc_unsigned operator+ () const
sc_signed operator- () const
sc_unsigned operator~ () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
const sc_concatref & operator= (int v)
const sc_concatref & operator= (long v)
const sc_concatref & operator= (int64 v)
const sc_concatref & operator= (unsigned int v)
const sc_concatref & operator= (unsigned long v)
const sc_concatref & operator= (uint64 v)
const sc_concatref & operator= (const sc_concatref &v)
const sc_concatref & operator= (const sc_signed &v)
const sc_concatref & operator= (const sc_unsigned &v)
const sc_concatref & operator= (const char *v_p)
const sc_concatref & operator= (const sc_bv_base &v)
const sc_concatref & operator= (const sc_lv_base &v)
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is)
Public Member Functions inherited from sc_dt::sc_generic_base< sc_concatref >
const sc_concatref * operator-> () const
sc_concatref * operator-> ()
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Attributes
static sc_core::sc_vpool< sc_concatref > m_pool
Protected Attributes
sc_value_base * m_left_p
sc_value_base * m_right_p
int m_len
int m_len_r
concat_flags m_flags
Private Member Functions
sc_concatref (const sc_concatref &)
sc_concatref ()
Friends
class sc_core::sc_vpool< sc_concatref >
Detailed Description
Definition at line 119 of file sc_concatref.hh.
Member Enumeration Documentation
concat_flags
enum sc_dt::sc_concatref::concat_flags
Enumerator
cf_none
cf_xz_present
Definition at line 434 of file sc_concatref.hh.
Constructor & Destructor Documentation
~sc_concatref()
virtual sc_dt::sc_concatref::~sc_concatref () inline virtual
Definition at line 152 of file sc_concatref.hh.
sc_concatref() [1/2]
sc_dt::sc_concatref::sc_concatref (const sc_concatref &) private
sc_concatref() [2/2]
sc_dt::sc_concatref::sc_concatref () inline private
Definition at line 448 of file sc_concatref.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_concatref::and_reduce () const inline
Definition at line 411 of file sc_concatref.hh.
Referenced by sc_dt::and_reduce().
concat_clear_data()
virtual void sc_dt::sc_concatref::concat_clear_data (bool to_ones) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 167 of file sc_concatref.hh.
concat_get_ctrl()
virtual bool sc_dt::sc_concatref::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 174 of file sc_concatref.hh.
concat_get_data()
virtual bool sc_dt::sc_concatref::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 182 of file sc_concatref.hh.
concat_get_uint64()
virtual uint64 sc_dt::sc_concatref::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 190 of file sc_concatref.hh.
concat_length()
virtual int sc_dt::sc_concatref::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 159 of file sc_concatref.hh.
Referenced by sc_dt::operator>>().
concat_set() [1/4]
virtual void sc_dt::sc_concatref::concat_set (int64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 201 of file sc_concatref.hh.
Referenced by operator=().
concat_set() [2/4]
virtual void sc_dt::sc_concatref::concat_set (const sc_signed & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 208 of file sc_concatref.hh.
concat_set() [3/4]
virtual void sc_dt::sc_concatref::concat_set (const sc_unsigned & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 215 of file sc_concatref.hh.
concat_set() [4/4]
virtual void sc_dt::sc_concatref::concat_set (uint64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 222 of file sc_concatref.hh.
initialize() [1/2]
void sc_dt::sc_concatref::initialize (sc_value_base & left, sc_value_base & right) inline
Definition at line 125 of file sc_concatref.hh.
References sc_dt::sc_value_base::concat_length().
Referenced by sc_dt::concat(), and sc_dt::operator,().
initialize() [2/2]
void sc_dt::sc_concatref::initialize (const sc_value_base & left, const sc_value_base & right) inline
Definition at line 139 of file sc_concatref.hh.
References sc_dt::sc_value_base::concat_length().
length()
unsigned int sc_dt::sc_concatref::length () const inline
Definition at line 155 of file sc_concatref.hh.
Referenced by operator=().
nand_reduce()
bool sc_dt::sc_concatref::nand_reduce () const inline
Definition at line 412 of file sc_concatref.hh.
Referenced by sc_dt::nand_reduce().
nor_reduce()
bool sc_dt::sc_concatref::nor_reduce () const inline
Definition at line 414 of file sc_concatref.hh.
Referenced by sc_dt::nor_reduce().
operator const sc_unsigned &()
sc_dt::sc_concatref::operator const sc_unsigned & () const inline
Definition at line 283 of file sc_concatref.hh.
operator uint64()
sc_dt::sc_concatref::operator uint64 () const inline
Definition at line 281 of file sc_concatref.hh.
operator+()
sc_unsigned sc_dt::sc_concatref::operator+ () const inline
Definition at line 286 of file sc_concatref.hh.
operator-()
sc_signed sc_dt::sc_concatref::operator- () const inline
Definition at line 288 of file sc_concatref.hh.
operator=() [1/12]
const sc_concatref& sc_dt::sc_concatref::operator= (int v) inline
Definition at line 307 of file sc_concatref.hh.
References concat_set().
operator=() [2/12]
const sc_concatref& sc_dt::sc_concatref::operator= (long v) inline
Definition at line 315 of file sc_concatref.hh.
References concat_set().
operator=() [3/12]
const sc_concatref& sc_dt::sc_concatref::operator= (int64 v) inline
Definition at line 323 of file sc_concatref.hh.
References concat_set().
operator=() [4/12]
const sc_concatref& sc_dt::sc_concatref::operator= (unsigned int v) inline
Definition at line 331 of file sc_concatref.hh.
References concat_set().
operator=() [5/12]
const sc_concatref& sc_dt::sc_concatref::operator= (unsigned long v) inline
Definition at line 339 of file sc_concatref.hh.
References concat_set().
operator=() [6/12]
const sc_concatref& sc_dt::sc_concatref::operator= (uint64 v) inline
Definition at line 347 of file sc_concatref.hh.
References concat_set().
operator=() [7/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const sc_concatref & v) inline
Definition at line 355 of file sc_concatref.hh.
References sc_dt::sc_unsigned::concat_set(), length(), and value().
operator=() [8/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const sc_signed & v) inline
Definition at line 365 of file sc_concatref.hh.
References concat_set().
operator=() [9/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const sc_unsigned & v) inline
Definition at line 373 of file sc_concatref.hh.
References concat_set().
operator=() [10/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const char * v_p) inline
Definition at line 381 of file sc_concatref.hh.
References sc_dt::sc_unsigned::concat_set(), and ArmISA::v.
operator=() [11/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const sc_bv_base & v) inline
Definition at line 391 of file sc_concatref.hh.
References sc_dt::sc_bv_base::length(), and ArmISA::v.
operator=() [12/12]
const sc_concatref& sc_dt::sc_concatref::operator= (const sc_lv_base & v) inline
Definition at line 401 of file sc_concatref.hh.
References data, sc_dt::sc_lv_base::length(), and ArmISA::v.
operator~()
sc_unsigned sc_dt::sc_concatref::operator~ () const inline
Definition at line 290 of file sc_concatref.hh.
or_reduce()
bool sc_dt::sc_concatref::or_reduce () const inline
Definition at line 413 of file sc_concatref.hh.
Referenced by sc_dt::or_reduce().
print()
void sc_dt::sc_concatref::print (::std::ostream & os = ::std::cout) const inline
Definition at line 419 of file sc_concatref.hh.
References X86ISA::os.
scan()
void sc_dt::sc_concatref::scan (::std::istream & is) inline
Definition at line 422 of file sc_concatref.hh.
References ArmISA::s.
to_double()
double sc_dt::sc_concatref::to_double () const inline
Definition at line 274 of file sc_concatref.hh.
to_int()
int sc_dt::sc_concatref::to_int () const inline
Definition at line 270 of file sc_concatref.hh.
to_int64()
int64 sc_dt::sc_concatref::to_int64 () const inline
Definition at line 269 of file sc_concatref.hh.
to_long()
long sc_dt::sc_concatref::to_long () const inline
Definition at line 272 of file sc_concatref.hh.
to_sc_signed()
void sc_dt::sc_concatref::to_sc_signed (sc_signed & target) const inline
Definition at line 276 of file sc_concatref.hh.
to_sc_unsigned()
void sc_dt::sc_concatref::to_sc_unsigned (sc_unsigned & target) const inline
Definition at line 278 of file sc_concatref.hh.
to_string() [1/2]
const std::string sc_dt::sc_concatref::to_string (sc_numrep numrep = SC_DEC) const inline
Definition at line 294 of file sc_concatref.hh.
to_string() [2/2]
const std::string sc_dt::sc_concatref::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 300 of file sc_concatref.hh.
to_uint()
unsigned int sc_dt::sc_concatref::to_uint () const inline
Definition at line 271 of file sc_concatref.hh.
to_uint64()
uint64 sc_dt::sc_concatref::to_uint64 () const inline
Definition at line 230 of file sc_concatref.hh.
References ArmISA::mask.
to_ulong()
unsigned long sc_dt::sc_concatref::to_ulong () const inline
Definition at line 273 of file sc_concatref.hh.
value()
const sc_unsigned& sc_dt::sc_concatref::value () const inline
Definition at line 249 of file sc_concatref.hh.
References sc_dt::sc_unsigned::digit, DIV_CEIL, sc_dt::sc_unsigned::m_pool, sc_dt::sc_unsigned::nbits, sc_dt::sc_unsigned::ndigits, sc_dt::sc_unsigned::num_bits(), SC_POS, sc_core::sc_temp_heap, SC_ZERO, and sc_dt::sc_unsigned::sgn.
Referenced by sc_dt::operator<<(), operator=(), and sc_dt::operator>>().
xnor_reduce()
bool sc_dt::sc_concatref::xnor_reduce () const inline
Definition at line 416 of file sc_concatref.hh.
Referenced by sc_dt::xnor_reduce().
xor_reduce()
bool sc_dt::sc_concatref::xor_reduce () const inline
Definition at line 415 of file sc_concatref.hh.
Referenced by sc_dt::xor_reduce().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_concatref >
friend class sc_core::sc_vpool< sc_concatref > friend
Definition at line 122 of file sc_concatref.hh.
Member Data Documentation
m_flags
concat_flags sc_dt::sc_concatref::m_flags protected
Definition at line 444 of file sc_concatref.hh.
m_left_p
sc_value_base* sc_dt::sc_concatref::m_left_p protected
Definition at line 440 of file sc_concatref.hh.
m_len
int sc_dt::sc_concatref::m_len protected
Definition at line 442 of file sc_concatref.hh.
m_len_r
int sc_dt::sc_concatref::m_len_r protected
Definition at line 443 of file sc_concatref.hh.
m_pool
sc_core::sc_vpool< sc_concatref > sc_dt::sc_concatref::m_pool static
Definition at line 431 of file sc_concatref.hh.
Referenced by sc_dt::concat(), and sc_dt::operator,().
m_right_p
sc_value_base* sc_dt::sc_concatref::m_right_p protected
Definition at line 441 of file sc_concatref.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/misc/sc_concatref.hh
systemc/dt/misc/sc_concatref.cc