gem5: Sparc64Process Class Reference
Sparc64Process Class Reference
#include <process.hh>
Public Member Functions
void argsInit (int intSize, int pageSize)
void flushWindows (ThreadContext *tc)
RegVal getSyscallArg (ThreadContext *tc, int &i)
void setSyscallArg (ThreadContext *tc, int i, RegVal val)
Public Member Functions inherited from SparcProcess
virtual void handleTrap (int trapNum, ThreadContext *tc, Fault *fault)
Addr readFillStart ()
Addr readSpillStart ()
void setSyscallReturn (ThreadContext *tc, SyscallReturn return_value)
Public Member Functions inherited from Process
Process (ProcessParams *params, EmulationPageTable *pTable, ObjectFile *obj_file)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void initState () override
initState() is called on each SimObject when not restoring from a checkpoint.
DrainState drain () override
Notify an object that it needs to drain its state.
virtual void syscall (int64_t callnum, ThreadContext *tc, Fault *fault)
virtual RegVal getSyscallArg (ThreadContext *tc, int &i, int width)
virtual SyscallDesc * getDesc (int callnum)=0
uint64_t uid ()
uint64_t euid ()
uint64_t gid ()
uint64_t egid ()
uint64_t pid ()
uint64_t ppid ()
uint64_t pgid ()
void pgid (uint64_t pgid)
uint64_t tgid ()
const char * progName () const
EmulatedDriver * findDriver (std::string filename)
Find an emulated device driver.
void updateBias ()
Addr getBias ()
Addr getStartPC ()
ObjectFile * getInterpreter ()
void regStats () override
Callback to set stat parameters.
void allocateMem (Addr vaddr, int64_t size, bool clobber=false)
bool fixupStackFault (Addr vaddr)
Attempt to fix up a fault at vaddr by allocating a page on the stack.
void assignThreadContext (ContextID context_id)
ThreadContext * findFreeContext ()
void revokeThreadContext (int context_id)
After delegating a thread context to a child process no longer should relate to the ThreadContext.
virtual bool mmapGrowsDown () const
Does mmap region grow upward or downward from mmapEnd? Most platforms grow downward, but a few (such as Alpha) grow upward instead, so they can override this method to return false.
bool map (Addr vaddr, Addr paddr, int size, bool cacheable=true)
Maps a contiguous range of virtual addresses in this process's address space to a contiguous range of physical addresses.
void replicatePage (Addr vaddr, Addr new_paddr, ThreadContext *old_tc, ThreadContext *new_tc, bool alloc_page)
virtual void clone (ThreadContext *old_tc, ThreadContext *new_tc, Process *new_p, RegVal flags)
std::string absolutePath (const std::string &path, bool host_fs)
Return an absolute path given a relative path paired with the current working directory of the process running under simulation.
std::string checkPathRedirect (const std::string &filename)
Redirect file path if it matches any keys initialized by system object.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
Sparc64Process (ProcessParams *params, ObjectFile *objFile)
void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
Protected Member Functions inherited from SparcProcess
SparcProcess (ProcessParams *params, ObjectFile *objFile, Addr _StackBias)
template<class IntType >
void argsInit (int pageSize)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from Process
static Process * tryLoaders (ProcessParams *params, ObjectFile *obj_file)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from Process
std::vector< ContextID > contextIds
System * system
Stats::Scalar numSyscalls
bool useArchPT
bool kvmInSE
bool useForClone
EmulationPageTable * pTable
SETranslatingPortProxy initVirtMem
ObjectFile * objFile
MemoryImage image
MemoryImage interpImage
std::vector< std::string > argv
std::vector< std::string > envp
std::string executable
std::string tgtCwd
The cwd members are used to track changes to the current working directory for the purpose of executing system calls which depend on relative paths (i.e.
std::string hostCwd
std::string release
uint64_t _uid
uint64_t _euid
uint64_t _gid
uint64_t _egid
uint64_t _pid
uint64_t _ppid
uint64_t _pgid
uint64_t _tgid
std::vector< EmulatedDriver * > drivers
std::shared_ptr< FDArray > fds
bool * exitGroup
std::shared_ptr< MemState > memState
uint64_t childClearTID
Calls a futex wakeup at the address specified by this pointer when this process exits.
bool * sigchld
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from SparcProcess
const Addr StackBias
Addr fillStart
Addr spillStart
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 118 of file process.hh.
Constructor & Destructor Documentation
Sparc64Process()
Sparc64Process::Sparc64Process (ProcessParams * params, ObjectFile * objFile) inline protected
Definition at line 122 of file process.hh.
References SparcProcess::argsInit(), SparcProcess::flushWindows(), Process::getSyscallArg(), ArmISA::i, Process::image, SparcProcess::initState(), MemoryImage::maxAddr(), Process::memState, SparcISA::PageBytes, roundUp(), Process::setSyscallArg(), ULL, and X86ISA::val.
Member Function Documentation
argsInit()
void Sparc64Process::argsInit (int intSize, int pageSize)
Definition at line 409 of file process.cc.
References SparcISA::fillHandler64, SparcProcess::fillStart, Process::initVirtMem, SparcISA::numFillInsts, SparcISA::numSpillInsts, SparcISA::spillHandler64, SparcProcess::spillStart, and PortProxy::writeBlob().
flushWindows()
void Sparc64Process::flushWindows (ThreadContext * tc) virtual
Implements SparcProcess.
Definition at line 467 of file process.cc.
References ThreadContext::getVirtProxy(), htobe(), MipsISA::index, SparcISA::MISCREG_CWP, AlphaISA::NumIntArchRegs, SparcISA::NWindows, panic, ThreadContext::readIntReg(), ThreadContext::readMiscReg(), ThreadContext::setIntReg(), ThreadContext::setMiscReg(), ArmISA::sp, AlphaISA::StackPointerReg, PortProxy::tryWriteBlob(), and warn.
getSyscallArg()
RegVal Sparc64Process::getSyscallArg (ThreadContext * tc, int & i) virtual
Implements Process.
Definition at line 516 of file process.cc.
References FirstArgumentReg, and ThreadContext::readIntReg().
initState()
void Sparc64Process::initState () protected virtual
initState() is called on each SimObject when not restoring from a checkpoint.
This provides a hook for state initializations that are only required for a "cold start".
Reimplemented from SparcProcess.
Definition at line 176 of file process.cc.
References SparcProcess::argsInit(), Process::contextIds, System::getThreadContext(), SparcProcess::initState(), SparcISA::MISCREG_PSTATE, AlphaISA::PageBytes, ThreadContext::setMiscReg(), and Process::system.
setSyscallArg()
void Sparc64Process::setSyscallArg (ThreadContext * tc, int i, RegVal val) virtual
Implements Process.
Definition at line 523 of file process.cc.
References FirstArgumentReg, and ThreadContext::setIntReg().
The documentation for this class was generated from the following files:
arch/sparc/process.hh
arch/sparc/process.cc