gem5: GarnetIntLink Class Reference
GarnetIntLink Class Reference
#include <GarnetLink.hh>
Public Types
typedef GarnetIntLinkParams Params
Public Types inherited from BasicIntLink
typedef BasicIntLinkParams Params
Public Types inherited from BasicLink
typedef BasicLinkParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
GarnetIntLink (const Params *p)
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
void print (std::ostream &out) const
Public Member Functions inherited from BasicIntLink
BasicIntLink (const Params *p)
const Params * params () const
Public Member Functions inherited from BasicLink
BasicLink (const Params *p)
const Params * params () const
void print (std::ostream &out) const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
NetworkLink * m_network_link
CreditLink * m_credit_link
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Friends
class GarnetNetwork
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from BasicLink
Cycles m_latency
int m_bandwidth_factor
int m_weight
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 47 of file GarnetLink.hh.
Member Typedef Documentation
Params
typedef GarnetIntLinkParams GarnetIntLink::Params
Definition at line 50 of file GarnetLink.hh.
Constructor & Destructor Documentation
GarnetIntLink()
GarnetIntLink::GarnetIntLink (const Params * p)
Definition at line 39 of file GarnetLink.cc.
References m_credit_link, and m_network_link.
Referenced by print().
Member Function Documentation
init()
void GarnetIntLink::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from BasicLink.
Definition at line 49 of file GarnetLink.cc.
print()
void GarnetIntLink::print (std::ostream & out) const
Definition at line 54 of file GarnetLink.cc.
References GarnetIntLink(), and SimObject::name().
Referenced by operator<<().
Friends And Related Function Documentation
GarnetNetwork
friend class GarnetNetwork friend
Definition at line 57 of file GarnetLink.hh.
Member Data Documentation
m_credit_link
CreditLink* GarnetIntLink::m_credit_link protected
Definition at line 61 of file GarnetLink.hh.
Referenced by GarnetIntLink(), and GarnetNetwork::makeInternalLink().
m_network_link
NetworkLink* GarnetIntLink::m_network_link protected
Definition at line 60 of file GarnetLink.hh.
Referenced by GarnetIntLink(), and GarnetNetwork::makeInternalLink().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet2.0/GarnetLink.hh
mem/ruby/network/garnet2.0/GarnetLink.cc