gem5: BaseCache Class Reference
BaseCache Class Reference abstract
A basic cache interface.
#include <base.hh>
Classes
struct CacheCmdStats
class CacheMasterPort
A cache master port is used for the memory-side port of the cache, and in addition to the basic timing port that only sends response packets through a transmit list, it also offers the ability to schedule and send request packets (requests & writebacks).
class CacheReqPacketQueue
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
class CacheSlavePort
A cache slave port is used for the CPU-side port of the cache, and it is basically a simple timing port that uses a transmit list for responses to the CPU (or connected master).
struct CacheStats
class CpuSidePort
The CPU-side port extends the base cache slave port with access functions for functional, atomic and timing requests.
class MemSidePort
The memory-side port extends the base cache master port with access functions for functional, atomic and timing snoops.
Public Types
enum BlockedCause { Blocked_NoMSHRs = MSHRQueue_MSHRs, Blocked_NoWBBuffers = MSHRQueue_WriteBuffer, Blocked_NoTargets, NUM_BLOCKED_CAUSES }
Reasons for caches to be blocked.
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void regProbePoints () override
Registers probes.
BaseCache (const BaseCacheParams *p, unsigned blk_size)
~BaseCache ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
unsigned getBlockSize () const
Query block size of a cache.
const AddrRangeList & getAddrRanges () const
MSHR * allocateMissBuffer (PacketPtr pkt, Tick time, bool sched_send=true)
void allocateWriteBuffer (PacketPtr pkt, Tick time)
bool isBlocked () const
Returns true if the cache is blocked for accesses.
void setBlocked (BlockedCause cause)
Marks the access path of the cache as blocked for the given cause.
void clearBlocked (BlockedCause cause)
Marks the cache as unblocked for the given cause.
void schedMemSideSendEvent (Tick time)
Schedule a send event for the memory-side port.
bool inCache (Addr addr, bool is_secure) const
bool hasBeenPrefetched (Addr addr, bool is_secure) const
bool inMissQueue (Addr addr, bool is_secure) const
void incMissCount (PacketPtr pkt)
void incHitCount (PacketPtr pkt)
bool coalesce () const
Checks if the cache is coalescing writes.
void writebackVisitor (CacheBlk &blk)
Cache block visitor that writes back dirty cache blocks using functional writes.
void invalidateVisitor (CacheBlk &blk)
Cache block visitor that invalidates all blocks in the cache.
virtual bool sendMSHRQueuePacket (MSHR *mshr)
Take an MSHR, turn it into a suitable downstream packet, and send it out.
bool sendWriteQueuePacket (WriteQueueEntry *wq_entry)
Similar to sendMSHR, but for a write-queue entry instead.
void serialize (CheckpointOut &cp) const override
Serialize the state of the caches.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
System * system
System we are currently operating in.
BaseCache::CacheStats stats
Protected Types
enum MSHRQueueIndex { MSHRQueue_MSHRs, MSHRQueue_WriteBuffer }
Indexes to enumerate the MSHR queues.
Protected Member Functions
void markInService (MSHR *mshr, bool pending_modified_resp)
Mark a request as in service (sent downstream in the memory system), effectively making this MSHR the ordering point.
void markInService (WriteQueueEntry *entry)
bool allocOnFill (MemCmd cmd) const
Determine whether we should allocate on a fill or not.
Addr regenerateBlkAddr (CacheBlk *blk)
Regenerate block address using tags.
Cycles calculateTagOnlyLatency (const uint32_t delay, const Cycles lookup_lat) const
Calculate latency of accesses that only touch the tag array.
Cycles calculateAccessLatency (const CacheBlk *blk, const uint32_t delay, const Cycles lookup_lat) const
Calculate access latency in ticks given a tag lookup latency, and whether access was a hit or miss.
virtual bool access (PacketPtr pkt, CacheBlk *&blk, Cycles &lat, PacketList &writebacks)
Does all the processing necessary to perform the provided request.
virtual void handleTimingReqHit (PacketPtr pkt, CacheBlk *blk, Tick request_time)
virtual void handleTimingReqMiss (PacketPtr pkt, CacheBlk *blk, Tick forward_time, Tick request_time)=0
void handleTimingReqMiss (PacketPtr pkt, MSHR *mshr, CacheBlk *blk, Tick forward_time, Tick request_time)
virtual void recvTimingReq (PacketPtr pkt)
Performs the access specified by the request.
void handleUncacheableWriteResp (PacketPtr pkt)
Handling the special case of uncacheable write responses to make recvTimingResp less cluttered.
virtual void serviceMSHRTargets (MSHR *mshr, const PacketPtr pkt, CacheBlk *blk)=0
Service non-deferred MSHR targets using the received response.
virtual void recvTimingResp (PacketPtr pkt)
Handles a response (cache line fill/write ack) from the bus.
virtual void recvTimingSnoopReq (PacketPtr pkt)=0
Snoops bus transactions to maintain coherence.
virtual void recvTimingSnoopResp (PacketPtr pkt)=0
Handle a snoop response.
virtual Cycles handleAtomicReqMiss (PacketPtr pkt, CacheBlk *&blk, PacketList &writebacks)=0
Handle a request in atomic mode that missed in this cache.
virtual Tick recvAtomic (PacketPtr pkt)
Performs the access specified by the request.
virtual Tick recvAtomicSnoop (PacketPtr pkt)=0
Snoop for the provided request in the cache and return the estimated time taken.
virtual void functionalAccess (PacketPtr pkt, bool from_cpu_side)
Performs the access specified by the request.
void cmpAndSwap (CacheBlk *blk, PacketPtr pkt)
Handle doing the Compare and Swap function for SPARC.
QueueEntry * getNextQueueEntry ()
Return the next queue entry to service, either a pending miss from the MSHR queue, a buffered write from the write buffer, or something from the prefetcher.
virtual void doWritebacks (PacketList &writebacks, Tick forward_time)=0
Insert writebacks into the write buffer.
virtual void doWritebacksAtomic (PacketList &writebacks)=0
Send writebacks down the memory hierarchy in atomic mode.
virtual PacketPtr createMissPacket (PacketPtr cpu_pkt, CacheBlk *blk, bool needs_writable, bool is_whole_line_write) const =0
Create an appropriate downstream bus request packet.
void writebackTempBlockAtomic ()
Send the outstanding tempBlock writeback.
bool updateCompressionData (CacheBlk *blk, const uint64_t *data, PacketList &writebacks)
When a block is overwriten, its compression information must be updated, and it may need to be recompressed.
virtual void satisfyRequest (PacketPtr pkt, CacheBlk *blk, bool deferred_response=false, bool pending_downgrade=false)
Perform any necessary updates to the block and perform any data exchange between the packet and the block.
void maintainClusivity (bool from_cache, CacheBlk *blk)
Maintain the clusivity of this cache by potentially invalidating a block.
CacheBlk * handleFill (PacketPtr pkt, CacheBlk *blk, PacketList &writebacks, bool allocate)
Handle a fill operation caused by a received packet.
CacheBlk * allocateBlock (const PacketPtr pkt, PacketList &writebacks)
Allocate a new block and perform any necessary writebacks.
virtual M5_NODISCARD PacketPtr evictBlock (CacheBlk *blk)=0
Evict a cache block.
void evictBlock (CacheBlk *blk, PacketList &writebacks)
Evict a cache block.
void invalidateBlock (CacheBlk *blk)
Invalidate a cache block.
PacketPtr writebackBlk (CacheBlk *blk)
Create a writeback request for the given block.
PacketPtr writecleanBlk (CacheBlk *blk, Request::Flags dest, PacketId id)
Create a writeclean request for the given block.
virtual void memWriteback () override
Write back dirty blocks in the cache using functional accesses.
virtual void memInvalidate () override
Invalidates all blocks in the cache.
bool isDirty () const
Determine if there are any dirty blocks in the cache.
bool inRange (Addr addr) const
Determine if an address is in the ranges covered by this cache.
Tick nextQueueReadyTime () const
Find next request ready time from among possible sources.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
CpuSidePort cpuSidePort
MemSidePort memSidePort
MSHRQueue mshrQueue
Miss status registers.
WriteQueue writeBuffer
Write/writeback buffer.
BaseTags * tags
Tag and data Storage.
BaseCacheCompressor * compressor
Compression method being used.
BasePrefetcher * prefetcher
Prefetcher.
ProbePointArg< PacketPtr > * ppHit
To probe when a cache hit occurs.
ProbePointArg< PacketPtr > * ppMiss
To probe when a cache miss occurs.
ProbePointArg< PacketPtr > * ppFill
To probe when a cache fill occurs.
WriteAllocator *const writeAllocator
The writeAllocator drive optimizations for streaming writes.
TempCacheBlk * tempBlock
Temporary cache block for occasional transitory use.
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
const bool writebackClean
Determine if clean lines should be written back or not.
PacketPtr tempBlockWriteback
Writebacks from the tempBlock, resulting on the response path in atomic mode, must happen after the call to recvAtomic has finished (for the right ordering of the packets).
EventFunctionWrapper writebackTempBlockAtomicEvent
An event to writeback the tempBlock after recvAtomic finishes.
const unsigned blkSize
Block size of this cache.
const Cycles lookupLatency
The latency of tag lookup of a cache.
const Cycles dataLatency
The latency of data access of a cache.
const Cycles forwardLatency
This is the forward latency of the cache.
const Cycles fillLatency
The latency to fill a cache block.
const Cycles responseLatency
The latency of sending reponse to its upper level cache/core on a linefill.
const bool sequentialAccess
Whether tags and data are accessed sequentially.
const int numTarget
The number of targets for each MSHR.
bool forwardSnoops
Do we forward snoops from mem side port through to cpu side port?
const Enums::Clusivity clusivity
Clusivity with respect to the upstream cache, determining if we fill into both this cache and the cache above on a miss.
const bool isReadOnly
Is this cache read only, for example the instruction cache, or table-walker cache.
uint8_t blocked
Bit vector of the blocking reasons for the access path.
uint64_t order
Increasing order number assigned to each incoming request.
Cycles blockedCycle
Stores time the cache blocked for statistics.
MSHR * noTargetMSHR
Pointer to the MSHR that has no targets.
Counter missCount
The number of misses to trigger an exit event.
const AddrRangeList addrRanges
The address range to which the cache responds on the CPU side.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
A basic cache interface.
Implements some common functions for speed.
Definition at line 93 of file base.hh.
Member Enumeration Documentation
BlockedCause
enum BaseCache::BlockedCause
Reasons for caches to be blocked.
Enumerator
Blocked_NoMSHRs
Blocked_NoWBBuffers
Blocked_NoTargets
NUM_BLOCKED_CAUSES
Definition at line 108 of file base.hh.
MSHRQueueIndex
enum BaseCache::MSHRQueueIndex protected
Indexes to enumerate the MSHR queues.
Enumerator
MSHRQueue_MSHRs
MSHRQueue_WriteBuffer
Definition at line 99 of file base.hh.
Constructor & Destructor Documentation
BaseCache()
BaseCache::BaseCache (const BaseCacheParams * p, unsigned blk_size)
Definition at line 79 of file base.cc.
References addrRanges, blkSize, blocked, clusivity, dataLatency, EventBase::Delayed_Writeback_Pri, fillLatency, forwardLatency, forwardSnoops, isReadOnly, lookupLatency, missCount, SimObject::name(), noTargetMSHR, numTarget, order, MipsISA::p, prefetcher, responseLatency, sequentialAccess, BasePrefetcher::setCache(), stats, system, tags, BaseTags::tagsInit(), tempBlock, and writebackTempBlockAtomic().
~BaseCache()
BaseCache::~BaseCache ()
Definition at line 129 of file base.cc.
References tempBlock.
Member Function Documentation
access()
bool BaseCache::access (PacketPtr pkt, CacheBlk *& blk, Cycles & lat, PacketList & writebacks) protected virtual
Does all the processing necessary to perform the provided request.
Parameters
pkt The memory request to perform.
blk The cache block to be updated.
lat The latency of the access.
writebacks List for any writebacks that need to be performed.
Returns
Boolean indicating whether the request was satisfied.
Reimplemented in Cache, and NoncoherentCache.
Definition at line 1023 of file base.cc.
References BaseTags::accessBlock(), allocateBlock(), BlkDirty, BlkReadable, blkSize, BlkWritable, calculateAccessLatency(), calculateTagOnlyLatency(), chatty_assert, MemCmd::CleanEvict, Packet::clearBlockCached(), Clocked::clockEdge(), Packet::cmd, compressor, Clocked::cyclesToTicks(), CacheBlk::data, DPRINTF, fillLatency, Queue< Entry >::findMatch(), Packet::fromCache(), Packet::getAddr(), Packet::getConstPtr(), BaseCacheCompressor::getDecompressionLatency(), WriteQueueEntry::getNumTargets(), Packet::getSize(), WriteQueueEntry::getTarget(), Packet::hasSharers(), Packet::headerDelay, incHitCount(), incMissCount(), invalidateBlock(), Packet::isCleanEviction(), Packet::isEviction(), Packet::isLLSC(), Packet::isRead(), CacheBlk::isReadable(), isReadOnly, Packet::isRequest(), Packet::isSecure(), CacheBlk::isWritable(), Packet::isWrite(), Packet::isWriteback(), maintainClusivity(), markInService(), mshrQueue, SimObject::name(), Packet::needsResponse(), Packet::needsWritable(), Packet::payloadDelay, QueueEntry::Target::pkt, CacheBlk::print(), Packet::print(), Packet::req, satisfyRequest(), CacheBlk::setWhenReady(), CacheBlk::status, tags, updateCompressionData(), MemCmd::WritebackClean, MemCmd::WritebackDirty, writeBuffer, MemCmd::WriteClean, Packet::writeDataToBlock(), and Packet::writeThrough().
Referenced by NoncoherentCache::access(), Cache::access(), allocOnFill(), recvAtomic(), and recvTimingReq().
allocateBlock()
CacheBlk * BaseCache::allocateBlock (const PacketPtr pkt, PacketList & writebacks) protected
Allocate a new block and perform any necessary writebacks.
Find a victim block and if necessary prepare writebacks for any existing data. May return nullptr if there are no replaceable blocks. If a replaceable block is found, it inserts the new block in its place. The new block, however, is not set as valid yet.
Parameters
pkt Packet holding the address to update
writebacks A list of writeback packets for the evicted blocks
Returns
the allocated block
Definition at line 1396 of file base.cc.
References addr, blkSize, BaseCacheCompressor::compress(), compressor, DPRINTF, evictBlock(), Queue< Entry >::findMatch(), BaseTags::findVictim(), Packet::getAddr(), Packet::getConstPtr(), Packet::hasData(), BaseTags::insertBlock(), MSHR::isCleaning(), Packet::isSecure(), mshrQueue, MSHR::needsWritable(), CacheBlk::print(), regenerateBlkAddr(), BaseCache::CacheStats::replacements, BaseCacheCompressor::setDecompressionLatency(), BaseCacheCompressor::setSizeBits(), stats, tags, and BaseCache::CacheStats::unusedPrefetches.
Referenced by access(), and handleFill().
allocateMissBuffer()
MSHR* BaseCache::allocateMissBuffer (PacketPtr pkt, Tick time, bool sched_send = true) inline
Definition at line 1089 of file base.hh.
References MSHRQueue::allocate(), allocOnFill(), blkSize, Packet::getBlockAddr(), Queue< Entry >::isFull(), MSHRQueue_MSHRs, schedMemSideSendEvent(), and setBlocked().
Referenced by getNextQueueEntry(), Cache::handleTimingReqMiss(), and handleTimingReqMiss().
allocateWriteBuffer()
void BaseCache::allocateWriteBuffer (PacketPtr pkt, Tick time) inline
Definition at line 1107 of file base.hh.
References WriteQueue::allocate(), MemCmd::CleanEvict, Packet::cmd, DPRINTF, Queue< Entry >::findMatch(), Packet::getBlockAddr(), QueueEntry::inService, Queue< Entry >::isFull(), Packet::isSecure(), Packet::isWrite(), MSHRQueue_WriteBuffer, Packet::payloadDelay, Packet::print(), schedMemSideSendEvent(), and setBlocked().
Referenced by NoncoherentCache::doWritebacks(), Cache::doWritebacks(), Cache::handleTimingReqMiss(), and handleTimingReqMiss().
allocOnFill()
bool BaseCache::allocOnFill (MemCmd cmd) const inline protected
Determine whether we should allocate on a fill or not.
If this cache is mostly inclusive with regards to the upstream cache(s) we always allocate (for any non-forwarded and cacheable requests). In the case of a mostly exclusive cache, we allocate on fill if the packet did not come from a cache, thus if we: are dealing with a whole-line write (the latter behaves much like a writeback), the original target packet came from a non-caching source, or if we are performing a prefetch or LLSC.
Parameters
cmd Command of the incoming requesting packet
Returns
Whether we should allocate on the fill
Definition at line 408 of file base.hh.
References access(), calculateAccessLatency(), calculateTagOnlyLatency(), clusivity, cmpAndSwap(), createMissPacket(), doWritebacks(), doWritebacksAtomic(), functionalAccess(), getNextQueueEntry(), handleAtomicReqMiss(), handleTimingReqHit(), handleTimingReqMiss(), handleUncacheableWriteResp(), MemCmd::isLLSC(), MemCmd::isPrefetch(), MemCmd::ReadReq, recvAtomic(), MasterPort::recvAtomicSnoop(), recvTimingReq(), TimingRequestProtocol::recvTimingResp(), MasterPort::recvTimingSnoopReq(), recvTimingSnoopResp(), regenerateBlkAddr(), serviceMSHRTargets(), MemCmd::WriteLineReq, and MemCmd::WriteReq.
Referenced by allocateMissBuffer(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), and handleTimingReqMiss().
calculateAccessLatency()
Cycles BaseCache::calculateAccessLatency (const CacheBlk * blk, const uint32_t delay, const Cycles lookup_lat) const protected
Calculate access latency in ticks given a tag lookup latency, and whether access was a hit or miss.
Parameters
blk The cache block that was accessed.
delay The delay until the packet's metadata is present.
lookup_lat Latency of the respective tag lookup.
Returns
The number of ticks that pass due to a block access.
Definition at line 989 of file base.cc.
References calculateTagOnlyLatency(), curTick(), dataLatency, CacheBlk::getWhenReady(), sequentialAccess, Clocked::tick, and Clocked::ticksToCycles().
Referenced by access(), and allocOnFill().
calculateTagOnlyLatency()
Cycles BaseCache::calculateTagOnlyLatency (const uint32_t delay, const Cycles lookup_lat) const protected
Calculate latency of accesses that only touch the tag array.
See also
calculateAccessLatency
Parameters
delay The delay until the packet's metadata is present.
lookup_lat Latency of the respective tag lookup.
Returns
The number of ticks that pass due to a tag-only access.
Definition at line 980 of file base.cc.
References Clocked::ticksToCycles().
Referenced by access(), allocOnFill(), and calculateAccessLatency().
clearBlocked()
void BaseCache::clearBlocked (BlockedCause cause) inline
Marks the cache as unblocked for the given cause.
This also clears the blocked flags in the appropriate interfaces.
Parameters
cause The newly unblocked cause.
Warning
Calling this function can cause a blocked request on the bus to access the cache. The cache must be in a state to handle that request.
Definition at line 1171 of file base.hh.
References BaseCache::CacheStats::blocked_cycles, blockedCycle, BaseCache::CacheSlavePort::clearBlocked(), Clocked::curCycle(), DPRINTF, and stats.
Referenced by markInService(), recvTimingResp(), and Cache::sendMSHRQueuePacket().
cmpAndSwap()
void BaseCache::cmpAndSwap (CacheBlk * blk, PacketPtr pkt) protected
Handle doing the Compare and Swap function for SPARC.
Definition at line 680 of file base.cc.
References BlkDirty, blkSize, CacheBlk::data, Packet::getOffset(), Packet::getSize(), Packet::isRequest(), ArmISA::offset, panic, Packet::req, Packet::setData(), CacheBlk::status, and Packet::writeData().
Referenced by allocOnFill(), and satisfyRequest().
coalesce()
bool BaseCache::coalesce () const
Checks if the cache is coalescing writes.
Returns
True if the cache is coalescing writes
Definition at line 1623 of file base.cc.
References WriteAllocator::coalesce(), and writeAllocator.
Referenced by incHitCount(), and BasePrefetcher::probeNotify().
createMissPacket()
virtual PacketPtr BaseCache::createMissPacket (PacketPtr cpu_pkt, CacheBlk * blk, bool needs_writable, bool is_whole_line_write) const protected pure virtual
Create an appropriate downstream bus request packet.
Creates a new packet with the request to be send to the memory below, or nullptr if the current request in cpu_pkt should just be forwarded on.
Parameters
cpu_pkt The miss packet that needs to be satisfied.
blk The referenced block, can be nullptr.
needs_writable Indicates that the block must be writable even if the request in cpu_pkt doesn't indicate that.
is_whole_line_write True if there are writes for the whole line
Returns
A packet send to the memory below
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), and sendMSHRQueuePacket().
doWritebacks()
virtual void BaseCache::doWritebacks (PacketList & writebacks, Tick forward_time) protected pure virtual
Insert writebacks into the write buffer.
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), recvTimingReq(), recvTimingResp(), and sendMSHRQueuePacket().
doWritebacksAtomic()
virtual void BaseCache::doWritebacksAtomic (PacketList & writebacks) protected pure virtual
Send writebacks down the memory hierarchy in atomic mode.
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), recvAtomic(), and writebackTempBlockAtomic().
evictBlock() [1/2]
virtual M5_NODISCARD PacketPtr BaseCache::evictBlock (CacheBlk * blk) protected pure virtual
Evict a cache block.
Performs a writeback if necesssary and invalidates the block
Parameters
blk Block to invalidate
Returns
A packet with the writeback, can be nullptr
Implemented in Cache, and NoncoherentCache.
Referenced by Cache::access(), allocateBlock(), evictBlock(), recvAtomic(), recvTimingResp(), and updateCompressionData().
evictBlock() [2/2]
void BaseCache::evictBlock (CacheBlk * blk, PacketList & writebacks) protected
Evict a cache block.
Performs a writeback if necesssary and invalidates the block
Parameters
blk Block to invalidate
writebacks Return a list of packets with writebacks
Definition at line 1502 of file base.cc.
References evictBlock().
functionalAccess()
void BaseCache::functionalAccess (PacketPtr pkt, bool from_cpu_side) protected virtual
Performs the access specified by the request.
Parameters
pkt The request to perform.
fromCpuSide from the CPU side port or the memory side port
Reimplemented in NoncoherentCache.
Definition at line 623 of file base.cc.
References blkSize, cpuSidePort, CacheBlk::data, DPRINTF, BaseTags::findBlock(), Queue< Entry >::findMatch(), Packet::getAddr(), Packet::getBlockAddr(), QueueEntry::inService, CacheBlk::isDirty(), MSHR::isPendingModified(), Packet::isSecure(), SlavePort::isSnooping(), CacheBlk::isValid(), Packet::makeResponse(), memSidePort, mshrQueue, SimObject::name(), Packet::popLabel(), Packet::print(), Packet::pushLabel(), MasterPort::sendFunctional(), SlavePort::sendFunctionalSnoop(), tags, QueuedSlavePort::trySatisfyFunctional(), QueuedMasterPort::trySatisfyFunctional(), Queue< Entry >::trySatisfyFunctional(), Packet::trySatisfyFunctional(), and writeBuffer.
Referenced by allocOnFill(), NoncoherentCache::functionalAccess(), BaseCache::CpuSidePort::recvFunctional(), and BaseCache::MemSidePort::recvFunctionalSnoop().
getAddrRanges()
const AddrRangeList& BaseCache::getAddrRanges () const inline
Definition at line 1087 of file base.hh.
References addrRanges.
Referenced by BaseCache::CpuSidePort::getAddrRanges().
getBlockSize()
unsigned BaseCache::getBlockSize () const inline
Query block size of a cache.
Returns
The block size
Definition at line 1082 of file base.hh.
References blkSize.
Referenced by BasePrefetcher::setCache().
getNextQueueEntry()
QueueEntry * BaseCache::getNextQueueEntry () protected
Return the next queue entry to service, either a pending miss from the MSHR queue, a buffered write from the write buffer, or something from the prefetcher.
This function is responsible for prioritizing among those sources on the fly.
Definition at line 720 of file base.cc.
References allocateMissBuffer(), blkSize, MSHRQueue::canPrefetch(), BaseCache::CacheStats::cmdStats(), curTick(), BaseTags::findBlock(), Queue< Entry >::findMatch(), Queue< Entry >::findPending(), Packet::getBlockAddr(), Queue< Entry >::getNext(), BasePrefetcher::getPacket(), Queue< Entry >::isFull(), Packet::isSecure(), System::maxMasters(), BaseCache::CacheCmdStats::mshr_misses, mshrQueue, QueueEntry::order, prefetcher, Packet::req, stats, system, tags, and writeBuffer.
Referenced by allocOnFill(), and BaseCache::CacheReqPacketQueue::sendDeferredPacket().
getPort()
Port & BaseCache::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 191 of file base.cc.
References cpuSidePort, SimObject::getPort(), and memSidePort.
handleAtomicReqMiss()
virtual Cycles BaseCache::handleAtomicReqMiss (PacketPtr pkt, CacheBlk *& blk, PacketList & writebacks) protected pure virtual
Handle a request in atomic mode that missed in this cache.
Creates a downstream request, sends it to the memory below and handles the response. As we are in atomic mode all operations are performed immediately.
Parameters
pkt The packet with the requests
blk The referenced block
writebacks A list with packets for any performed writebacks
Returns
Cycles for handling the request
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), and recvAtomic().
handleFill()
CacheBlk * BaseCache::handleFill (PacketPtr pkt, CacheBlk * blk, PacketList & writebacks, bool allocate) protected
Handle a fill operation caused by a received packet.
Populates a cache block and handles all outstanding requests for the satisfied fill request. This version takes two memory requests. One contains the fill data, the other is an optional target to satisfy. Note that the reason we return a list of writebacks rather than inserting them directly in the write buffer is that this function is called by both atomic and timing-mode accesses, and in atomic mode we don't mess with the write buffer (we just perform the writebacks atomically once the original request is complete).
Parameters
pkt The memory request with the fill data.
blk The cache block if it already exists.
writebacks List for any writebacks that need to be performed.
allocate Whether to allocate a block or use the temp block
Returns
Pointer to the new cache block.
Definition at line 1299 of file base.cc.
References addr, allocateBlock(), BlkDirty, BlkReadable, blkSize, BlkWritable, Packet::cacheResponding(), chatty_assert, Clocked::clockEdge(), Packet::cmd, CacheBlk::data, DPRINTF, fillLatency, Queue< Entry >::findMatch(), Packet::getAddr(), Packet::getBlockAddr(), Packet::getSize(), Packet::hasData(), Packet::hasSharers(), Packet::headerDelay, TempCacheBlk::insert(), MemCmd::InvalidateResp, Packet::isRead(), isReadOnly, Packet::isResponse(), CacheBlk::isSecure(), Packet::isSecure(), CacheBlk::isValid(), SimObject::name(), Packet::payloadDelay, CacheBlk::print(), regenerateBlkAddr(), CacheBlk::setWhenReady(), CacheBlk::status, tempBlock, writeBuffer, and Packet::writeDataToBlock().
Referenced by NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), and recvTimingResp().
handleTimingReqHit()
void BaseCache::handleTimingReqHit (PacketPtr pkt, CacheBlk * blk, Tick request_time) protected virtual
Reimplemented in Cache.
Definition at line 214 of file base.cc.
References cpuSidePort, DPRINTF, Packet::headerDelay, Packet::makeTimingResponse(), Packet::needsResponse(), Packet::payloadDelay, pendingDelete, Packet::print(), and QueuedSlavePort::schedTimingResp().
Referenced by allocOnFill(), Cache::handleTimingReqHit(), and recvTimingReq().
handleTimingReqMiss() [1/2]
virtual void BaseCache::handleTimingReqMiss (PacketPtr pkt, CacheBlk * blk, Tick forward_time, Tick request_time) protected pure virtual
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), and recvTimingReq().
handleTimingReqMiss() [2/2]
void BaseCache::handleTimingReqMiss (PacketPtr pkt, MSHR * mshr, CacheBlk * blk, Tick forward_time, Tick request_time) protected
MSHR hit
Note
writebacks will be checked in getNextMSHR() for any conflicting requests to the same block
Definition at line 242 of file base.cc.
References allocateMissBuffer(), MSHR::allocateTarget(), allocateWriteBuffer(), allocOnFill(), BlkReadable, blkSize, Blocked_NoTargets, MemCmd::CleanEvict, Packet::cmd, BaseCache::CacheStats::cmdStats(), DPRINTF, Packet::getAddr(), Packet::getBlockAddr(), MSHR::getNumTargets(), Packet::getSize(), Packet::isEviction(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWrite(), Packet::isWriteback(), System::maxMasters(), BaseCache::CacheCmdStats::mshr_hits, BaseCache::CacheCmdStats::mshr_misses, Packet::needsWritable(), noTargetMSHR, numTarget, order, pendingDelete, Packet::print(), Packet::req, setBlocked(), stats, CacheBlk::status, system, WriteAllocator::updateMode(), writeAllocator, and MemCmd::WriteClean.
handleUncacheableWriteResp()
void BaseCache::handleUncacheableWriteResp (PacketPtr pkt) protected
Handling the special case of uncacheable write responses to make recvTimingResp less cluttered.
Definition at line 393 of file base.cc.
References Clocked::clockEdge(), cpuSidePort, Packet::headerDelay, Packet::payloadDelay, responseLatency, and QueuedSlavePort::schedTimingResp().
Referenced by allocOnFill(), and recvTimingResp().
hasBeenPrefetched()
bool BaseCache::hasBeenPrefetched (Addr addr, bool is_secure) const inline
Definition at line 1199 of file base.hh.
References BaseTags::findBlock(), and CacheBlk::wasPrefetched().
Referenced by BasePrefetcher::hasBeenPrefetched().
inCache()
bool BaseCache::inCache (Addr addr, bool is_secure) const inline
Definition at line 1195 of file base.hh.
References BaseTags::findBlock().
Referenced by BasePrefetcher::inCache().
incHitCount()
void BaseCache::incHitCount (PacketPtr pkt) inline
Definition at line 1223 of file base.hh.
References BaseCache::CacheStats::cmdStats(), coalesce(), BaseCache::CacheCmdStats::hits, invalidateVisitor(), System::maxMasters(), Packet::req, sendMSHRQueuePacket(), sendWriteQueuePacket(), serialize(), stats, unserialize(), and writebackVisitor().
Referenced by access().
incMissCount()
void BaseCache::incMissCount (PacketPtr pkt) inline
Definition at line 1212 of file base.hh.
References BaseCache::CacheStats::cmdStats(), exitSimLoop(), System::maxMasters(), missCount, BaseCache::CacheCmdStats::misses, Packet::req, and stats.
Referenced by access().
init()
void BaseCache::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 182 of file base.cc.
References cpuSidePort, fatal, forwardSnoops, Port::isConnected(), SlavePort::isSnooping(), memSidePort, SimObject::name(), and SlavePort::sendRangeChange().
inMissQueue()
bool BaseCache::inMissQueue (Addr addr, bool is_secure) const inline
Definition at line 1208 of file base.hh.
References Queue< Entry >::findMatch().
Referenced by BasePrefetcher::inMissQueue().
inRange()
bool BaseCache::inRange (Addr addr) const protected
Determine if an address is in the ranges covered by this cache.
This is useful to filter snoops.
Parameters
addr Address to check against
Returns
If the address in question is in range
Definition at line 203 of file base.cc.
References addrRanges, and MipsISA::r.
Referenced by Cache::recvAtomicSnoop(), and Cache::recvTimingSnoopReq().
invalidateBlock()
void BaseCache::invalidateBlock (CacheBlk * blk) protected
Invalidate a cache block.
Parameters
blk Block to invalidate
Definition at line 1490 of file base.cc.
References BaseTags::invalidate(), TempCacheBlk::invalidate(), tags, and tempBlock.
Referenced by access(), NoncoherentCache::evictBlock(), Cache::evictBlock(), Cache::handleAtomicReqMiss(), Cache::handleSnoop(), invalidateVisitor(), maintainClusivity(), satisfyRequest(), and Cache::serviceMSHRTargets().
invalidateVisitor()
void BaseCache::invalidateVisitor (CacheBlk & blk)
Cache block visitor that invalidates all blocks in the cache.
Dirty cache lines will not be written back to memory.
Definition at line 1652 of file base.cc.
References invalidateBlock(), CacheBlk::isDirty(), CacheBlk::isValid(), and warn_once.
Referenced by incHitCount(), and memInvalidate().
isBlocked()
bool BaseCache::isBlocked () const inline
Returns true if the cache is blocked for accesses.
Definition at line 1142 of file base.hh.
isDirty()
bool BaseCache::isDirty () const protected
Determine if there are any dirty blocks in the cache.
Returns
true if at least one block is dirty, false otherwise.
Definition at line 1617 of file base.cc.
References BaseTags::anyBlk(), CacheBlk::isDirty(), and tags.
Referenced by serialize().
maintainClusivity()
void BaseCache::maintainClusivity (bool from_cache, CacheBlk * blk) protected
Maintain the clusivity of this cache by potentially invalidating a block.
This method works in conjunction with satisfyRequest, but is separate to allow us to handle all MSHR targets before potentially dropping a block.
Parameters
from_cache Whether we have dealt with a packet from a cache
blk The block that should potentially be dropped
Definition at line 1287 of file base.cc.
References clusivity, invalidateBlock(), CacheBlk::isDirty(), and CacheBlk::isValid().
Referenced by access(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), and Cache::serviceMSHRTargets().
markInService() [1/2]
void BaseCache::markInService (MSHR * mshr, bool pending_modified_resp) inline protected
Mark a request as in service (sent downstream in the memory system), effectively making this MSHR the ordering point.
Definition at line 375 of file base.hh.
References Blocked_NoMSHRs, clearBlocked(), Queue< Entry >::isFull(), and MSHRQueue::markInService().
Referenced by access(), Cache::recvTimingSnoopReq(), Cache::sendMSHRQueuePacket(), sendMSHRQueuePacket(), and sendWriteQueuePacket().
markInService() [2/2]
void BaseCache::markInService (WriteQueueEntry * entry) inline protected
Definition at line 385 of file base.hh.
References Blocked_NoWBBuffers, clearBlocked(), Queue< Entry >::isFull(), and WriteQueue::markInService().
memInvalidate()
void BaseCache::memInvalidate () override protected virtual
Invalidates all blocks in the cache.
Dirty cache lines will not be written back to memory. Make sure to call functionalWriteback() first if you want the to write them to memory.
Reimplemented from SimObject.
Definition at line 1611 of file base.cc.
References BaseTags::forEachBlk(), invalidateVisitor(), and tags.
memWriteback()
void BaseCache::memWriteback () override protected virtual
Write back dirty blocks in the cache using functional accesses.
Reimplemented from SimObject.
Definition at line 1605 of file base.cc.
References BaseTags::forEachBlk(), tags, and writebackVisitor().
nextQueueReadyTime()
Tick BaseCache::nextQueueReadyTime () const protected
Find next request ready time from among possible sources.
Definition at line 1665 of file base.cc.
References MSHRQueue::canPrefetch(), mshrQueue, BasePrefetcher::nextPrefetchReadyTime(), Queue< Entry >::nextReadyTime(), prefetcher, and writeBuffer.
Referenced by BaseCache::CacheReqPacketQueue::sendDeferredPacket().
recvAtomic()
Tick BaseCache::recvAtomic (PacketPtr pkt) protected virtual
Performs the access specified by the request.
Parameters
pkt The request to perform.
Returns
The number of ticks required for the access.
Reimplemented in Cache, and NoncoherentCache.
Definition at line 543 of file base.cc.
References access(), Clocked::clockPeriod(), curTick(), doWritebacksAtomic(), DPRINTF, evictBlock(), handleAtomicReqMiss(), Packet::id, Packet::isClean(), CacheBlk::isDirty(), CacheBlk::isValid(), lookupLatency, Packet::makeAtomicResponse(), Packet::needsResponse(), CacheBlk::print(), Packet::print(), Packet::req, EventManager::schedule(), Packet::setSatisfied(), tempBlock, tempBlockWriteback, writebackTempBlockAtomic(), writebackTempBlockAtomicEvent, and writecleanBlk().
Referenced by allocOnFill(), NoncoherentCache::recvAtomic(), Cache::recvAtomic(), and BaseCache::CpuSidePort::recvAtomic().
recvAtomicSnoop()
virtual Tick BaseCache::recvAtomicSnoop (PacketPtr pkt) protected pure virtual
Snoop for the provided request in the cache and return the estimated time taken.
Parameters
pkt The memory request to snoop
Returns
The number of ticks required for the snoop.
Implemented in Cache, and NoncoherentCache.
Referenced by BaseCache::MemSidePort::recvAtomicSnoop().
recvTimingReq()
void BaseCache::recvTimingReq (PacketPtr pkt) protected virtual
Performs the access specified by the request.
Parameters
pkt The request to perform.
Reimplemented in Cache, and NoncoherentCache.
Definition at line 337 of file base.cc.
References access(), BlkHWPrefetched, Clocked::clockEdge(), doWritebacks(), forwardLatency, handleTimingReqHit(), handleTimingReqMiss(), Packet::headerDelay, MaxTick, BasePrefetcher::nextPrefetchReadyTime(), Packet::payloadDelay, ppHit, ppMiss, prefetcher, schedMemSideSendEvent(), CacheBlk::status, and CacheBlk::wasPrefetched().
Referenced by allocOnFill(), NoncoherentCache::recvTimingReq(), Cache::recvTimingReq(), and BaseCache::CpuSidePort::recvTimingReq().
recvTimingResp()
void BaseCache::recvTimingResp (PacketPtr pkt) protected virtual
Handles a response (cache line fill/write ack) from the bus.
Parameters
pkt The response packet
Reimplemented in NoncoherentCache.
Definition at line 405 of file base.cc.
References WriteAllocator::allocate(), MSHR::allocOnFill(), BlkReadable, Blocked_NoMSHRs, Blocked_NoTargets, MSHRQueue::canPrefetch(), clearBlocked(), Clocked::clockEdge(), Packet::cmd, BaseCache::CacheStats::cmdStats(), curTick(), Queue< Entry >::deallocate(), doWritebacks(), DPRINTF, evictBlock(), BaseTags::findBlock(), forwardLatency, Packet::getAddr(), MSHR::getTarget(), handleFill(), handleUncacheableWriteResp(), MemCmd::HardPFResp, Packet::headerDelay, Packet::isClean(), Packet::isError(), MSHR::isForward, Queue< Entry >::isFull(), Packet::isInvalidate(), Packet::isRead(), Packet::isResponse(), Packet::isSecure(), CacheBlk::isValid(), Packet::isWrite(), MSHRQueue::markPending(), System::maxMasters(), MaxTick, BaseCache::CacheCmdStats::mshr_miss_latency, BaseCache::CacheCmdStats::mshr_uncacheable_lat, mshrQueue, SimObject::name(), BasePrefetcher::nextPrefetchReadyTime(), noTargetMSHR, panic_if, Packet::payloadDelay, QueueEntry::Target::pkt, Packet::popSenderState(), ppFill, prefetcher, Packet::print(), MSHR::promoteDeferredTargets(), MSHR::promoteReadable(), MSHR::promoteWritable(), QueueEntry::Target::recvTime, Packet::req, schedMemSideSendEvent(), serviceMSHRTargets(), stats, system, tags, tempBlock, MemCmd::UpgradeResp, MSHR::wasWholeLineWrite, and writeAllocator.
Referenced by NoncoherentCache::recvTimingResp(), BaseCache::MemSidePort::recvTimingResp(), and Cache::recvTimingSnoopResp().
recvTimingSnoopReq()
virtual void BaseCache::recvTimingSnoopReq (PacketPtr pkt) protected pure virtual
Snoops bus transactions to maintain coherence.
Parameters
pkt The current bus transaction.
Implemented in Cache, and NoncoherentCache.
Referenced by BaseCache::MemSidePort::recvTimingSnoopReq().
recvTimingSnoopResp()
virtual void BaseCache::recvTimingSnoopResp (PacketPtr pkt) protected pure virtual
Handle a snoop response.
Parameters
pkt Snoop response packet
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), and BaseCache::CpuSidePort::recvTimingSnoopResp().
regenerateBlkAddr()
Addr BaseCache::regenerateBlkAddr (CacheBlk * blk) protected
Regenerate block address using tags.
Block address regeneration depends on whether we're using a temporary block or not.
Parameters
blk The block to regenerate address.
Returns
The block's address.
Definition at line 172 of file base.cc.
References TempCacheBlk::getAddr(), BaseTags::regenerateBlkAddr(), tags, and tempBlock.
Referenced by allocateBlock(), allocOnFill(), Cache::cleanEvictBlk(), handleFill(), updateCompressionData(), writebackBlk(), writebackVisitor(), and writecleanBlk().
regProbePoints()
void BaseCache::regProbePoints () override virtual
Registers probes.
Reimplemented from SimObject.
Definition at line 2299 of file base.cc.
References SimObject::getProbeManager(), ppFill, ppHit, and ppMiss.
satisfyRequest()
void BaseCache::satisfyRequest (PacketPtr pkt, CacheBlk * blk, bool deferred_response = false, bool pending_downgrade = false) protected virtual
Perform any necessary updates to the block and perform any data exchange between the packet and the block.
The flags of the packet are also set accordingly.
Parameters
pkt Request packet from upstream that hit a block
blk Cache block that the packet hit
deferred_response Whether this request originally missed
pending_downgrade Whether the writable flag is to be removed
Reimplemented in Cache, and NoncoherentCache.
Definition at line 897 of file base.cc.
References BlkDirty, blkSize, CacheBlk::checkWrite(), Packet::cmd, cmpAndSwap(), CacheBlk::data, DPRINTF, BaseTags::extractBlkOffset(), Packet::getAddr(), Packet::getAtomicOp(), Packet::getOffset(), Packet::getSize(), Packet::hasRespData(), Packet::hasSharers(), invalidateBlock(), Packet::isAtomicOp(), Packet::isClean(), CacheBlk::isDirty(), Packet::isInvalidate(), Packet::isLLSC(), Packet::isRead(), Packet::isRequest(), Packet::isUpgrade(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::isWrite(), ArmISA::offset, Packet::print(), Packet::setCacheResponding(), Packet::setData(), Packet::setDataFromBlock(), CacheBlk::status, MemCmd::SwapReq, tags, CacheBlk::trackLoadLocked(), and Packet::writeDataToBlock().
Referenced by access(), NoncoherentCache::satisfyRequest(), and Cache::satisfyRequest().
schedMemSideSendEvent()
void BaseCache::schedMemSideSendEvent (Tick time) inline
Schedule a send event for the memory-side port.
If already scheduled, this may reschedule the event at an earlier time. When the specified time is reached, the port is free to send either a response, a request, or a prefetch request.
Parameters
time The time when to attempt sending a packet.
Definition at line 1190 of file base.hh.
References BaseCache::CacheMasterPort::schedSendEvent().
Referenced by allocateMissBuffer(), allocateWriteBuffer(), recvTimingReq(), and recvTimingResp().
sendMSHRQueuePacket()
bool BaseCache::sendMSHRQueuePacket (MSHR * mshr) virtual
Take an MSHR, turn it into a suitable downstream packet, and send it out.
This construct allows a queue entry to choose a suitable approach based on its type.
Parameters
mshr The MSHR to turn into a packet and send
Returns
True if the port is waiting for a retry
Reimplemented in Cache.
Definition at line 1682 of file base.cc.
References QueueEntry::blkAddr, blkSize, Packet::cacheResponding(), Clocked::clockPeriod(), WriteAllocator::coalesce(), createMissPacket(), MSHRQueue::delay(), WriteAllocator::delay(), doWritebacks(), DPRINTF, BaseTags::findBlock(), Packet::getSize(), MSHR::getTarget(), Packet::hasSharers(), Packet::id, Packet::isClean(), CacheBlk::isDirty(), MSHR::isForward, QueueEntry::isSecure, MSHR::isWholeLineWrite(), Packet::isWrite(), markInService(), memSidePort, mshrQueue, MSHR::needsWritable(), QueueEntry::Target::pkt, CacheBlk::print(), Packet::print(), Packet::pushSenderState(), Packet::req, WriteAllocator::reset(), WriteAllocator::resetDelay(), MasterPort::sendTimingReq(), Packet::setSatisfied(), tags, writeAllocator, and writecleanBlk().
Referenced by incHitCount(), Cache::sendMSHRQueuePacket(), and MSHR::sendPacket().
sendWriteQueuePacket()
bool BaseCache::sendWriteQueuePacket (WriteQueueEntry * wq_entry)
Similar to sendMSHR, but for a write-queue entry instead.
Create the packet, and send it, and if successful also mark the entry in service.
Parameters
wq_entry The write-queue entry to turn into a packet and send
Returns
True if the port is waiting for a retry
Definition at line 1785 of file base.cc.
References DPRINTF, WriteQueueEntry::getTarget(), markInService(), memSidePort, QueueEntry::Target::pkt, Packet::print(), and MasterPort::sendTimingReq().
Referenced by incHitCount(), and WriteQueueEntry::sendPacket().
serialize()
void BaseCache::serialize (CheckpointOut & cp) const override virtual
Serialize the state of the caches.
We currently don't support checkpointing cache state, so this panics.
Implements Serializable.
Definition at line 1809 of file base.cc.
References isDirty(), SERIALIZE_SCALAR, and warn.
Referenced by incHitCount().
serviceMSHRTargets()
virtual void BaseCache::serviceMSHRTargets (MSHR * mshr, const PacketPtr pkt, CacheBlk * blk) protected pure virtual
Service non-deferred MSHR targets using the received response.
Iterates through the list of targets that can be serviced with the current response.
Parameters
mshr The MSHR that corresponds to the reponse
pkt The response packet
blk The reference block
Implemented in Cache, and NoncoherentCache.
Referenced by allocOnFill(), and recvTimingResp().
setBlocked()
void BaseCache::setBlocked (BlockedCause cause) inline
Marks the access path of the cache as blocked for the given cause.
This also sets the blocked flag in the slave interface.
Parameters
cause The reason for the cache blocking.
Definition at line 1152 of file base.hh.
References BaseCache::CacheStats::blocked_causes, Clocked::curCycle(), DPRINTF, BaseCache::CacheSlavePort::setBlocked(), and stats.
Referenced by allocateMissBuffer(), allocateWriteBuffer(), and handleTimingReqMiss().
unserialize()
void BaseCache::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1829 of file base.cc.
References fatal, and UNSERIALIZE_SCALAR.
Referenced by incHitCount().
updateCompressionData()
bool BaseCache::updateCompressionData (CacheBlk * blk, const uint64_t * data, PacketList & writebacks) protected
When a block is overwriten, its compression information must be updated, and it may need to be recompressed.
If the compression size changes, the block may either become smaller, in which case there is no side effect, or bigger (data expansion; fat write), in which case the block might not fit in its current location anymore. If that happens, there are usually two options to be taken:
The co-allocated blocks must be evicted to make room for this block. Simpler, but ignores replacement data.
The block itself is moved elsewhere (used in policies where the CF determines the location of the block).
This implementation uses the first approach.
Notice that this is only called for writebacks, which means that L1 caches (which see regular Writes), do not support compression.
See also
CompressedTags
Parameters
blk The block to be overwriten.
data A pointer to the data to be compressed (blk's new data).
writebacks List for any writebacks that need to be performed.
Returns
Whether operation is successful or not.
Definition at line 798 of file base.cc.
References SectorBlk::blks, blkSize, SuperBlk::canCoAllocate(), BaseCacheCompressor::compress(), compressor, BaseCache::CacheStats::dataExpansions, DPRINTF, evictBlock(), Queue< Entry >::findMatch(), SectorSubBlk::getSectorBlock(), CompressionBlk::getSizeBits(), CompressionBlk::isCompressed(), SuperBlk::isCompressed(), M5_VAR_USED, mshrQueue, CompressionBlk::print(), CacheBlk::print(), regenerateBlkAddr(), CompressionBlk::setCompressed(), CompressionBlk::setDecompressionLatency(), CompressionBlk::setSizeBits(), CompressionBlk::setUncompressed(), stats, tempBlock, and BaseCache::CacheStats::unusedPrefetches.
Referenced by access().
writebackBlk()
PacketPtr BaseCache::writebackBlk (CacheBlk * blk) protected
Create a writeback request for the given block.
Parameters
blk The block to writeback.
Returns
The writeback request for the block.
Definition at line 1511 of file base.cc.
References Packet::allocate(), BlkDirty, blkSize, BlkWritable, chatty_assert, compressor, CacheBlk::data, DPRINTF, BaseCacheCompressor::getDecompressionLatency(), CacheBlk::isDirty(), isReadOnly, CacheBlk::isSecure(), CacheBlk::isValid(), CacheBlk::isWritable(), Packet::payloadDelay, Packet::print(), regenerateBlkAddr(), Request::SECURE, Packet::setDataFromBlock(), Packet::setHasSharers(), stats, CacheBlk::status, CacheBlk::task_id, Request::wbMasterId, MemCmd::WritebackClean, writebackClean, MemCmd::WritebackDirty, and BaseCache::CacheStats::writebacks.
Referenced by NoncoherentCache::evictBlock(), and Cache::evictBlock().
writebackTempBlockAtomic()
void BaseCache::writebackTempBlockAtomic () inline protected
Send the outstanding tempBlock writeback.
To be called after recvAtomic finishes in cases where the block we filled is in fact the tempBlock, and now needs to be written back.
Definition at line 646 of file base.hh.
References doWritebacksAtomic().
Referenced by BaseCache(), and recvAtomic().
writebackVisitor()
void BaseCache::writebackVisitor (CacheBlk & blk)
Cache block visitor that writes back dirty cache blocks using functional writes.
Definition at line 1629 of file base.cc.
References BlkDirty, blkSize, CacheBlk::data, Packet::dataStatic(), Request::funcMasterId, CacheBlk::isDirty(), CacheBlk::isSecure(), CacheBlk::isValid(), memSidePort, regenerateBlkAddr(), Request::SECURE, MasterPort::sendFunctional(), CacheBlk::status, CacheBlk::task_id, and MemCmd::WriteReq.
Referenced by incHitCount(), and memWriteback().
writecleanBlk()
PacketPtr BaseCache::writecleanBlk (CacheBlk * blk, Request::Flags dest, PacketId id) protected
Create a writeclean request for the given block.
Creates a request that writes the block to the cache below without evicting the block from the current cache.
Parameters
blk The block to write clean.
dest The destination of the write clean operation.
id Use the given packet id for the write clean operation.
Returns
The generated write clean packet.
Definition at line 1559 of file base.cc.
References Packet::allocate(), BlkDirty, blkSize, BlkWritable, compressor, CacheBlk::data, DPRINTF, BaseCacheCompressor::getDecompressionLatency(), CacheBlk::isDirty(), CacheBlk::isSecure(), CacheBlk::isWritable(), Packet::payloadDelay, Packet::print(), regenerateBlkAddr(), Request::SECURE, Packet::setDataFromBlock(), Packet::setHasSharers(), Packet::setWriteThrough(), CacheBlk::status, CacheBlk::task_id, Request::wbMasterId, and MemCmd::WriteClean.
Referenced by Cache::handleSnoop(), recvAtomic(), and sendMSHRQueuePacket().
Member Data Documentation
addrRanges
const AddrRangeList BaseCache::addrRanges protected
The address range to which the cache responds on the CPU side.
Normally this is all possible memory addresses.
Definition at line 909 of file base.hh.
Referenced by BaseCache(), getAddrRanges(), and inRange().
blkSize
const unsigned BaseCache::blkSize protected
Block size of this cache.
Definition at line 831 of file base.hh.
Referenced by access(), allocateBlock(), allocateMissBuffer(), BaseCache(), BaseCache::CacheReqPacketQueue::checkConflictingSnoop(), Cache::cleanEvictBlk(), cmpAndSwap(), NoncoherentCache::createMissPacket(), Cache::createMissPacket(), Cache::doTimingSupplyResponse(), functionalAccess(), getBlockSize(), getNextQueueEntry(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), handleFill(), Cache::handleSnoop(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), handleTimingReqMiss(), Cache::promoteWholeLineWrites(), Cache::recvTimingSnoopReq(), Cache::satisfyRequest(), satisfyRequest(), sendMSHRQueuePacket(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), updateCompressionData(), writebackBlk(), writebackVisitor(), and writecleanBlk().
blocked
uint8_t BaseCache::blocked protected
Bit vector of the blocking reasons for the access path.
See also
BlockedCause
Definition at line 892 of file base.hh.
Referenced by BaseCache(), BaseCache::CacheSlavePort::clearBlocked(), BaseCache::CacheSlavePort::isBlocked(), BaseCache::CacheSlavePort::setBlocked(), and BaseCache::CpuSidePort::tryTiming().
blockedCycle
Cycles BaseCache::blockedCycle protected
Stores time the cache blocked for statistics.
Definition at line 898 of file base.hh.
Referenced by clearBlocked().
clusivity
const Enums::Clusivity BaseCache::clusivity protected
Clusivity with respect to the upstream cache, determining if we fill into both this cache and the cache above on a miss.
Note that we currently do not support strict clusivity policies.
Definition at line 878 of file base.hh.
Referenced by allocOnFill(), BaseCache(), Cache::createMissPacket(), and maintainClusivity().
compressor
BaseCacheCompressor* BaseCache::compressor protected
Compression method being used.
Definition at line 327 of file base.hh.
Referenced by access(), allocateBlock(), Cache::handleSnoop(), updateCompressionData(), writebackBlk(), and writecleanBlk().
cpuSidePort
CpuSidePort BaseCache::cpuSidePort protected
Definition at line 312 of file base.hh.
Referenced by functionalAccess(), getPort(), Cache::handleSnoop(), handleTimingReqHit(), Cache::handleTimingReqMiss(), handleUncacheableWriteResp(), init(), Cache::isCachedAbove(), Cache::sendMSHRQueuePacket(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
dataLatency
const Cycles BaseCache::dataLatency protected
The latency of data access of a cache.
It occurs when there is an access to the cache.
Definition at line 843 of file base.hh.
Referenced by BaseCache(), and calculateAccessLatency().
fillLatency
const Cycles BaseCache::fillLatency protected
The latency to fill a cache block.
Definition at line 853 of file base.hh.
Referenced by access(), BaseCache(), and handleFill().
forwardLatency
const Cycles BaseCache::forwardLatency protected
This is the forward latency of the cache.
It occurs when there is a cache miss and a request is forwarded downstream, in particular an outbound miss.
Definition at line 850 of file base.hh.
Referenced by BaseCache(), Cache::doTimingSupplyResponse(), Cache::handleSnoop(), recvTimingReq(), recvTimingResp(), and Cache::recvTimingSnoopResp().
forwardSnoops
bool BaseCache::forwardSnoops protected
Do we forward snoops from mem side port through to cpu side port?
Definition at line 871 of file base.hh.
Referenced by BaseCache(), Cache::handleSnoop(), init(), Cache::isCachedAbove(), and Cache::sendMSHRQueuePacket().
isReadOnly
const bool BaseCache::isReadOnly protected
Is this cache read only, for example the instruction cache, or table-walker cache.
A cache that is read only should never see any writes, and should never get any dirty data (and hence never have to do any writebacks).
Definition at line 886 of file base.hh.
Referenced by Cache::access(), access(), BaseCache(), Cache::createMissPacket(), handleFill(), Cache::handleSnoop(), Cache::serviceMSHRTargets(), and writebackBlk().
lookupLatency
const Cycles BaseCache::lookupLatency protected
The latency of tag lookup of a cache.
It occurs when there is an access to the cache.
Definition at line 837 of file base.hh.
Referenced by Cache::access(), BaseCache(), recvAtomic(), Cache::recvAtomicSnoop(), and Cache::recvTimingSnoopReq().
memSidePort
MemSidePort BaseCache::memSidePort protected
Definition at line 313 of file base.hh.
Referenced by Cache::doTimingSupplyResponse(), NoncoherentCache::doWritebacksAtomic(), Cache::doWritebacksAtomic(), functionalAccess(), getPort(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), init(), Cache::recvAtomic(), BaseCache::CpuSidePort::recvAtomic(), BaseCache::CpuSidePort::recvFunctional(), Cache::recvTimingReq(), BaseCache::CpuSidePort::recvTimingReq(), Cache::recvTimingSnoopResp(), sendMSHRQueuePacket(), sendWriteQueuePacket(), and writebackVisitor().
missCount
Counter BaseCache::missCount protected
The number of misses to trigger an exit event.
Definition at line 904 of file base.hh.
Referenced by BaseCache(), and incMissCount().
mshrQueue
MSHRQueue BaseCache::mshrQueue protected
Miss status registers.
Definition at line 318 of file base.hh.
Referenced by access(), allocateBlock(), functionalAccess(), getNextQueueEntry(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), nextQueueReadyTime(), recvTimingResp(), Cache::recvTimingSnoopReq(), Cache::sendMSHRQueuePacket(), sendMSHRQueuePacket(), and updateCompressionData().
noTargetMSHR
MSHR* BaseCache::noTargetMSHR protected
Pointer to the MSHR that has no targets.
Definition at line 901 of file base.hh.
Referenced by BaseCache(), handleTimingReqMiss(), and recvTimingResp().
numTarget
const int BaseCache::numTarget protected
The number of targets for each MSHR.
Definition at line 868 of file base.hh.
Referenced by BaseCache(), handleTimingReqMiss(), and Cache::recvTimingSnoopReq().
order
uint64_t BaseCache::order protected
Increasing order number assigned to each incoming request.
Definition at line 895 of file base.hh.
Referenced by BaseCache(), handleTimingReqMiss(), and Cache::recvTimingSnoopReq().
pendingDelete
std::unique_ptr<Packet> BaseCache::pendingDelete protected
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Definition at line 369 of file base.hh.
Referenced by handleTimingReqHit(), handleTimingReqMiss(), and Cache::recvTimingReq().
ppFill
ProbePointArg<PacketPtr>* BaseCache::ppFill protected
To probe when a cache fill occurs.
Definition at line 339 of file base.hh.
Referenced by recvTimingResp(), and regProbePoints().
ppHit
ProbePointArg<PacketPtr>* BaseCache::ppHit protected
To probe when a cache hit occurs.
Definition at line 333 of file base.hh.
Referenced by recvTimingReq(), and regProbePoints().
ppMiss
ProbePointArg<PacketPtr>* BaseCache::ppMiss protected
To probe when a cache miss occurs.
Definition at line 336 of file base.hh.
Referenced by recvTimingReq(), and regProbePoints().
prefetcher
BasePrefetcher* BaseCache::prefetcher protected
Prefetcher.
Definition at line 330 of file base.hh.
Referenced by BaseCache(), getNextQueueEntry(), nextQueueReadyTime(), recvTimingReq(), and recvTimingResp().
responseLatency
const Cycles BaseCache::responseLatency protected
The latency of sending reponse to its upper level cache/core on a linefill.
The responseLatency parameter captures this latency.
Definition at line 860 of file base.hh.
Referenced by BaseCache(), handleUncacheableWriteResp(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
sequentialAccess
const bool BaseCache::sequentialAccess protected
Whether tags and data are accessed sequentially.
Definition at line 865 of file base.hh.
Referenced by BaseCache(), and calculateAccessLatency().
stats
BaseCache::CacheStats BaseCache::stats
Referenced by allocateBlock(), BaseCache(), clearBlocked(), getNextQueueEntry(), Cache::handleTimingReqMiss(), handleTimingReqMiss(), incHitCount(), incMissCount(), recvTimingResp(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), setBlocked(), updateCompressionData(), and writebackBlk().
system
System* BaseCache::system
System we are currently operating in.
Definition at line 913 of file base.hh.
Referenced by BaseCache(), getNextQueueEntry(), handleTimingReqMiss(), QueuedPrefetcher::insert(), BaseCache::CpuSidePort::recvAtomic(), BaseCache::MemSidePort::recvAtomicSnoop(), BaseCache::CpuSidePort::recvFunctional(), BaseCache::MemSidePort::recvFunctionalSnoop(), BaseCache::CpuSidePort::recvTimingReq(), recvTimingResp(), BaseCache::MemSidePort::recvTimingSnoopReq(), BaseCache::CpuSidePort::recvTimingSnoopResp(), BaseCache::CacheStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), and BaseCache::CpuSidePort::tryTiming().
tags
BaseTags* BaseCache::tags protected
Tag and data Storage.
Definition at line 324 of file base.hh.
Referenced by Cache::access(), access(), allocateBlock(), BaseCache(), NoncoherentCache::evictBlock(), functionalAccess(), getNextQueueEntry(), invalidateBlock(), isDirty(), memInvalidate(), memWriteback(), Cache::recvAtomicSnoop(), Cache::recvTimingReq(), recvTimingResp(), Cache::recvTimingSnoopReq(), regenerateBlkAddr(), satisfyRequest(), Cache::sendMSHRQueuePacket(), and sendMSHRQueuePacket().
tempBlock
TempCacheBlk* BaseCache::tempBlock protected
Temporary cache block for occasional transitory use.
We use the tempBlock to fill when allocation fails (e.g., when there is an outstanding request that accesses the victim block) or when we want to avoid allocation (e.g., exclusive caches)
Definition at line 363 of file base.hh.
Referenced by BaseCache(), handleFill(), invalidateBlock(), recvAtomic(), recvTimingResp(), regenerateBlkAddr(), updateCompressionData(), and ~BaseCache().
tempBlockWriteback
PacketPtr BaseCache::tempBlockWriteback protected
Writebacks from the tempBlock, resulting on the response path in atomic mode, must happen after the call to recvAtomic has finished (for the right ordering of the packets).
We therefore need to hold on to the packets, and have a method and an event to send them.
Definition at line 639 of file base.hh.
Referenced by recvAtomic().
writeAllocator
WriteAllocator* const BaseCache::writeAllocator protected
The writeAllocator drive optimizations for streaming writes.
It first determines whether a WriteReq MSHR should be delayed, thus ensuring that we wait longer in cases when we are write coalescing and allowing all the bytes of the line to be written before the MSHR packet is sent downstream. This works in unison with the tracking in the MSHR to check if the entire line is written. The write mode also affects the behaviour on filling any whole-line writes. Normally the cache allocates the line when receiving the InvalidateResp, but after seeing enough consecutive lines we switch to using the tempBlock, and thus end up not allocating the line, and instead turning the whole-line write into a writeback straight away.
Definition at line 355 of file base.hh.
Referenced by coalesce(), Cache::handleAtomicReqMiss(), handleTimingReqMiss(), recvTimingResp(), and sendMSHRQueuePacket().
writebackClean
const bool BaseCache::writebackClean protected
Determine if clean lines should be written back or not.
In cases where a downstream cache is mostly inclusive we likely want it to act as a victim cache also for lines that have not been modified. Hence, we cannot simply drop the line (or send a clean evict), but rather need to send the actual data.
Definition at line 630 of file base.hh.
Referenced by Cache::cleanEvictBlk(), Cache::doWritebacks(), NoncoherentCache::evictBlock(), Cache::evictBlock(), and writebackBlk().
writebackTempBlockAtomicEvent
EventFunctionWrapper BaseCache::writebackTempBlockAtomicEvent protected
An event to writeback the tempBlock after recvAtomic finishes.
To avoid other calls to recvAtomic getting in between, we create this event with a higher priority.
Definition at line 658 of file base.hh.
Referenced by recvAtomic().
writeBuffer
WriteQueue BaseCache::writeBuffer protected
Write/writeback buffer.
Definition at line 321 of file base.hh.
Referenced by access(), functionalAccess(), getNextQueueEntry(), handleFill(), nextQueueReadyTime(), and Cache::recvTimingSnoopReq().
The documentation for this class was generated from the following files:
mem/cache/base.hh
mem/cache/base.cc