gem5: StubSlavePortHandler Class Reference
StubSlavePortHandler Class Reference
Public Member Functions
ExternalSlave::ExternalPort * getExternalPort (const std::string &name_, ExternalSlave &owner, const std::string &port_data)
Create or find an external port which can be bound.
Detailed Description
Definition at line 82 of file external_slave.cc.
Member Function Documentation
getExternalPort()
ExternalSlave::ExternalPort* StubSlavePortHandler::getExternalPort (const std::string & name, ExternalSlave & owner, const std::string & port_data) inline virtual
Create or find an external port which can be bound.
Returns NULL on failure
Implements ExternalSlave::Handler.
Definition at line 86 of file external_slave.cc.
References DPRINTF, ExternalSlave::ExternalPort::ExternalPort(), Port::name(), and StubSlavePort::StubSlavePort().
The documentation for this class was generated from the following file:
mem/external_slave.cc