gem5: DirectoryMemory Class Reference
DirectoryMemory Class Reference
#include <DirectoryMemory.hh>
Public Types
typedef RubyDirectoryMemoryParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
DirectoryMemory (const Params *p)
~DirectoryMemory ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
uint64_t mapAddressToLocalIdx (Addr address)
Return the index in the directory based on an address.
uint64_t getSize ()
bool isPresent (Addr address)
AbstractCacheEntry * lookup (Addr address)
AbstractCacheEntry * allocate (Addr address, AbstractCacheEntry *new_entry)
void print (std::ostream &out) const
void recordRequestType (DirectoryRequestType requestType)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
DirectoryMemory (const DirectoryMemory &obj)
DirectoryMemory & operator= (const DirectoryMemory &obj)
Private Attributes
const std::string m_name
AbstractCacheEntry ** m_entries
uint64_t m_size_bytes
uint64_t m_size_bits
uint64_t m_num_entries
const AddrRangeList addrRanges
The address range for which the directory responds.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 54 of file DirectoryMemory.hh.
Member Typedef Documentation
Params
typedef RubyDirectoryMemoryParams DirectoryMemory::Params
Definition at line 57 of file DirectoryMemory.hh.
Constructor & Destructor Documentation
DirectoryMemory() [1/2]
DirectoryMemory::DirectoryMemory (const Params * p)
Definition at line 56 of file DirectoryMemory.cc.
References addrRanges, floorLog2(), m_num_entries, m_size_bits, m_size_bytes, and MipsISA::r.
Referenced by getSize(), and recordRequestType().
~DirectoryMemory()
DirectoryMemory::~DirectoryMemory ()
Definition at line 76 of file DirectoryMemory.cc.
References ArmISA::i, m_entries, and m_num_entries.
DirectoryMemory() [2/2]
DirectoryMemory::DirectoryMemory (const DirectoryMemory & obj) private
Member Function Documentation
allocate()
AbstractCacheEntry * DirectoryMemory::allocate (Addr address, AbstractCacheEntry * new_entry)
Definition at line 124 of file DirectoryMemory.cc.
References AbstractCacheEntry::changePermission(), DPRINTF, isPresent(), m_entries, m_num_entries, and mapAddressToLocalIdx().
Referenced by getSize().
getSize()
uint64_t DirectoryMemory::getSize () inline
Definition at line 76 of file DirectoryMemory.hh.
References allocate(), DirectoryMemory(), isPresent(), lookup(), m_size_bytes, operator=(), print(), and recordRequestType().
init()
void DirectoryMemory::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 68 of file DirectoryMemory.cc.
References RubySystem::getBlockSizeBytes(), ArmISA::i, m_entries, m_num_entries, and m_size_bytes.
isPresent()
bool DirectoryMemory::isPresent (Addr address)
Definition at line 88 of file DirectoryMemory.cc.
References addrRanges, and MipsISA::r.
Referenced by allocate(), getSize(), and lookup().
lookup()
AbstractCacheEntry * DirectoryMemory::lookup (Addr address)
Definition at line 113 of file DirectoryMemory.cc.
References DPRINTF, isPresent(), m_entries, m_num_entries, and mapAddressToLocalIdx().
Referenced by getSize().
mapAddressToLocalIdx()
uint64_t DirectoryMemory::mapAddressToLocalIdx (Addr address)
Return the index in the directory based on an address.
This function transforms an address which belongs to a not necessarily continuous vector of address ranges into a flat address that we use to index in the directory
Parameters
an input address
Returns
the corresponding index in the directory
Definition at line 99 of file DirectoryMemory.cc.
References addrRanges, RubySystem::getBlockSizeBits(), and MipsISA::r.
Referenced by allocate(), and lookup().
operator=()
DirectoryMemory& DirectoryMemory::operator= (const DirectoryMemory & obj) private
Referenced by getSize().
print()
void DirectoryMemory::print (std::ostream & out) const
Definition at line 139 of file DirectoryMemory.cc.
Referenced by getSize(), and operator<<().
recordRequestType()
void DirectoryMemory::recordRequestType (DirectoryRequestType requestType)
Definition at line 144 of file DirectoryMemory.cc.
References DirectoryMemory(), and DPRINTF.
Referenced by getSize().
Member Data Documentation
addrRanges
const AddrRangeList DirectoryMemory::addrRanges private
The address range for which the directory responds.
Normally this is all possible memory addresses.
Definition at line 103 of file DirectoryMemory.hh.
Referenced by DirectoryMemory(), isPresent(), and mapAddressToLocalIdx().
m_entries
AbstractCacheEntry** DirectoryMemory::m_entries private
Definition at line 92 of file DirectoryMemory.hh.
Referenced by allocate(), init(), lookup(), and ~DirectoryMemory().
m_name
const std::string DirectoryMemory::m_name private
Definition at line 91 of file DirectoryMemory.hh.
m_num_entries
uint64_t DirectoryMemory::m_num_entries private
Definition at line 97 of file DirectoryMemory.hh.
Referenced by allocate(), DirectoryMemory(), init(), lookup(), and ~DirectoryMemory().
m_size_bits
uint64_t DirectoryMemory::m_size_bits private
Definition at line 96 of file DirectoryMemory.hh.
Referenced by DirectoryMemory().
m_size_bytes
uint64_t DirectoryMemory::m_size_bytes private
Definition at line 95 of file DirectoryMemory.hh.
Referenced by DirectoryMemory(), getSize(), and init().
The documentation for this class was generated from the following files:
mem/ruby/structures/DirectoryMemory.hh
mem/ruby/structures/DirectoryMemory.cc