gem5: Gem5SystemC::Gem5Extension Class Reference
Gem5SystemC::Gem5Extension Class Reference
#include <sc_ext.hh>
Public Member Functions
Gem5Extension (PacketPtr _packet)
virtual tlm_extension_base * clone () const
virtual void copy_from (const tlm_extension_base &ext)
PacketPtr getPacket ()
bool isPipeThrough () const
void setPipeThrough ()
Public Member Functions inherited from tlm::tlm_extension< Gem5Extension >
virtual void copy_from (tlm_extension_base const &ext)=0
virtual ~tlm_extension ()
Public Member Functions inherited from tlm::tlm_extension_base
virtual void free ()
Static Public Member Functions
static Gem5Extension & getExtension (const tlm::tlm_generic_payload *payload)
static Gem5Extension & getExtension (const tlm::tlm_generic_payload &payload)
Private Attributes
PacketPtr packet
bool pipeThrough
Additional Inherited Members
Static Public Attributes inherited from tlm::tlm_extension< Gem5Extension >
static const unsigned int ID
Protected Member Functions inherited from tlm::tlm_extension_base
virtual ~tlm_extension_base ()
Static Protected Member Functions inherited from tlm::tlm_extension_base
static unsigned int register_extension (const std::type_info &)
Detailed Description
Definition at line 47 of file sc_ext.hh.
Constructor & Destructor Documentation
Gem5Extension()
Gem5SystemC::Gem5Extension::Gem5Extension (PacketPtr _packet)
Definition at line 45 of file sc_ext.cc.
References packet, and pipeThrough.
Referenced by clone().
Member Function Documentation
clone()
tlm::tlm_extension_base * Gem5SystemC::Gem5Extension::clone () const virtual
Implements tlm::tlm_extension< Gem5Extension >.
Definition at line 73 of file sc_ext.cc.
References Gem5Extension(), and packet.
copy_from()
void Gem5SystemC::Gem5Extension::copy_from (const tlm_extension_base & ext) virtual
Definition at line 79 of file sc_ext.cc.
References ArmISA::ext, and packet.
getExtension() [1/2]
Gem5Extension & Gem5SystemC::Gem5Extension::getExtension (const tlm::tlm_generic_payload * payload) static
Definition at line 52 of file sc_ext.cc.
References tlm::tlm_generic_payload::get_extension(), and sc_assert.
Referenced by getExtension(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvRespRetry().
getExtension() [2/2]
Gem5Extension & Gem5SystemC::Gem5Extension::getExtension (const tlm::tlm_generic_payload & payload) static
Definition at line 61 of file sc_ext.cc.
References getExtension().
getPacket()
PacketPtr Gem5SystemC::Gem5Extension::getPacket ()
Definition at line 67 of file sc_ext.cc.
References packet.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvRespRetry(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg().
isPipeThrough()
bool Gem5SystemC::Gem5Extension::isPipeThrough () const inline
Definition at line 61 of file sc_ext.hh.
References pipeThrough.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp().
setPipeThrough()
void Gem5SystemC::Gem5Extension::setPipeThrough () inline
Definition at line 62 of file sc_ext.hh.
References pipeThrough.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg().
Member Data Documentation
packet
PacketPtr Gem5SystemC::Gem5Extension::packet private
Definition at line 65 of file sc_ext.hh.
Referenced by clone(), copy_from(), Gem5Extension(), and getPacket().
pipeThrough
bool Gem5SystemC::Gem5Extension::pipeThrough private
Definition at line 66 of file sc_ext.hh.
Referenced by Gem5Extension(), isPipeThrough(), and setPipeThrough().
The documentation for this class was generated from the following files:
systemc/tlm_bridge/sc_ext.hh
systemc/tlm_bridge/sc_ext.cc