gem5: Trace::X86NativeTrace Class Reference
Trace::X86NativeTrace Class Reference
#include <nativetrace.hh>
Classes
struct ThreadState
Public Member Functions
X86NativeTrace (const Params *p)
void check (NativeTraceRecord *record)
Public Member Functions inherited from Trace::NativeTrace
NativeTrace (const Params *p)
virtual ~NativeTrace ()
NativeTraceRecord * getInstRecord (Tick when, ThreadContext *tc, const StaticInstPtr staticInst, TheISA::PCState pc, const StaticInstPtr macroStaticInst=NULL)
template<class T >
bool checkReg (const char *regName, T &val, T &realVal)
void read (void *ptr, size_t size)
Public Member Functions inherited from Trace::ExeTracer
ExeTracer (const Params *params)
Public Member Functions inherited from Trace::InstTracer
InstTracer (const Params *p)
virtual ~InstTracer ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Member Functions
bool checkRcxReg (const char *regName, uint64_t &, uint64_t &)
bool checkR11Reg (const char *regName, uint64_t &, uint64_t &)
bool checkXMM (int num, uint64_t mXmmBuf[], uint64_t nXmmBuf[])
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
bool checkRcx
bool checkR11
uint64_t oldRcxVal
uint64_t oldR11Val
uint64_t oldRealRcxVal
uint64_t oldRealR11Val
ThreadState nState
ThreadState mState
Protected Attributes inherited from Trace::NativeTrace
int fd
ListenSocket native_listener
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from Trace::ExeTracer
typedef ExeTracerParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 41 of file nativetrace.hh.
Constructor & Destructor Documentation
X86NativeTrace()
Trace::X86NativeTrace::X86NativeTrace (const Params * p)
Definition at line 99 of file nativetrace.cc.
References checkR11, and checkRcx.
Member Function Documentation
check()
void Trace::X86NativeTrace::check (NativeTraceRecord * record) virtual
Implements Trace::NativeTrace.
Definition at line 141 of file nativetrace.cc.
References checkR11, checkR11Reg(), checkRcx, checkRcxReg(), Trace::NativeTrace::checkReg(), checkXMM(), Trace::InstRecord::getStaticInst(), Trace::InstRecord::getThread(), StaticInst::isSyscall(), mState, nState, oldR11Val, oldRcxVal, oldRealR11Val, oldRealRcxVal, Trace::X86NativeTrace::ThreadState::r10, Trace::X86NativeTrace::ThreadState::r11, Trace::X86NativeTrace::ThreadState::r12, Trace::X86NativeTrace::ThreadState::r13, Trace::X86NativeTrace::ThreadState::r14, Trace::X86NativeTrace::ThreadState::r15, Trace::X86NativeTrace::ThreadState::r8, Trace::X86NativeTrace::ThreadState::r9, Trace::X86NativeTrace::ThreadState::rax, Trace::X86NativeTrace::ThreadState::rbp, Trace::X86NativeTrace::ThreadState::rbx, Trace::X86NativeTrace::ThreadState::rcx, Trace::X86NativeTrace::ThreadState::rdi, Trace::X86NativeTrace::ThreadState::rdx, Trace::X86NativeTrace::ThreadState::rip, Trace::X86NativeTrace::ThreadState::rsi, Trace::X86NativeTrace::ThreadState::rsp, Trace::X86NativeTrace::ThreadState::update(), and Trace::X86NativeTrace::ThreadState::xmm.
checkR11Reg()
bool Trace::X86NativeTrace::checkR11Reg (const char * regName, uint64_t & mVal, uint64_t & nVal) protected
Definition at line 117 of file nativetrace.cc.
References checkR11, Trace::NativeTrace::checkReg(), oldR11Val, and oldRealR11Val.
Referenced by check().
checkRcxReg()
bool Trace::X86NativeTrace::checkRcxReg (const char * regName, uint64_t & mVal, uint64_t & nVal) protected
Definition at line 107 of file nativetrace.cc.
References checkRcx, Trace::NativeTrace::checkReg(), oldRcxVal, and oldRealRcxVal.
Referenced by check().
checkXMM()
bool Trace::X86NativeTrace::checkXMM (int num, uint64_t mXmmBuf[], uint64_t nXmmBuf[]) protected
Definition at line 127 of file nativetrace.cc.
References DPRINTF.
Referenced by check().
Member Data Documentation
checkR11
bool Trace::X86NativeTrace::checkR11 protected
Definition at line 45 of file nativetrace.hh.
Referenced by check(), checkR11Reg(), and X86NativeTrace().
checkRcx
bool Trace::X86NativeTrace::checkRcx protected
Definition at line 44 of file nativetrace.hh.
Referenced by check(), checkRcxReg(), and X86NativeTrace().
mState
ThreadState Trace::X86NativeTrace::mState protected
Definition at line 76 of file nativetrace.hh.
Referenced by check().
nState
ThreadState Trace::X86NativeTrace::nState protected
Definition at line 75 of file nativetrace.hh.
Referenced by check().
oldR11Val
uint64_t Trace::X86NativeTrace::oldR11Val protected
Definition at line 46 of file nativetrace.hh.
Referenced by check(), and checkR11Reg().
oldRcxVal
uint64_t Trace::X86NativeTrace::oldRcxVal protected
Definition at line 46 of file nativetrace.hh.
Referenced by check(), and checkRcxReg().
oldRealR11Val
uint64_t Trace::X86NativeTrace::oldRealR11Val protected
Definition at line 47 of file nativetrace.hh.
Referenced by check(), and checkR11Reg().
oldRealRcxVal
uint64_t Trace::X86NativeTrace::oldRealRcxVal protected
Definition at line 47 of file nativetrace.hh.
Referenced by check(), and checkRcxReg().
The documentation for this class was generated from the following files:
arch/x86/nativetrace.hh
arch/x86/nativetrace.cc