gem5: sc_dt::scfx_mant Class Reference
sc_dt::scfx_mant Class Reference
#include <scfx_mant.hh>
Public Member Functions
scfx_mant (std::size_t)
scfx_mant (const scfx_mant &)
scfx_mant & operator= (const scfx_mant &)
~scfx_mant ()
void clear ()
void resize_to (int, int=0)
int size () const
word operator[] (int) const
word & operator[] (int)
half_word half_at (int) const
half_word & half_at (int)
half_word * half_addr (int=0) const
Static Private Member Functions
static word * alloc (std::size_t)
static void free (word *, std::size_t)
static word * alloc_word (std::size_t size)
static void free_word (word *array, std::size_t size)
Private Attributes
word * m_array
int m_size
Detailed Description
Definition at line 75 of file scfx_mant.hh.
Constructor & Destructor Documentation
scfx_mant() [1/2]
sc_dt::scfx_mant::scfx_mant (std::size_t size_) inline explicit
Definition at line 157 of file scfx_mant.hh.
References alloc(), and m_array.
scfx_mant() [2/2]
sc_dt::scfx_mant::scfx_mant (const scfx_mant & rhs) inline
Definition at line 162 of file scfx_mant.hh.
References alloc(), ArmISA::i, m_array, and m_size.
~scfx_mant()
sc_dt::scfx_mant::~scfx_mant () inline
Definition at line 187 of file scfx_mant.hh.
References free(), m_array, and m_size.
Member Function Documentation
alloc()
word * sc_dt::scfx_mant::alloc (std::size_t size) inline static private
Definition at line 116 of file scfx_mant.hh.
References alloc_word().
Referenced by operator=(), resize_to(), and scfx_mant().
alloc_word()
word * sc_dt::scfx_mant::alloc_word (std::size_t size) static private
Definition at line 82 of file scfx_mant.cc.
References ArmISA::i, sc_dt::word_list::m_next_p, sc_dt::next_pow2_index(), and sc_dt::UINT64_ONE.
Referenced by alloc().
clear()
void sc_dt::scfx_mant::clear () inline
Definition at line 195 of file scfx_mant.hh.
References ArmISA::i, and m_size.
Referenced by sc_dt::add_scfx_rep(), sc_dt::div_scfx_rep(), sc_dt::scfx_rep::from_string(), sc_dt::multiply(), sc_dt::scfx_rep::o_set_low(), sc_dt::scfx_rep::resize(), sc_dt::scfx_rep::scfx_rep(), and sc_dt::sub_scfx_rep().
free()
void sc_dt::scfx_mant::free (word * mant, std::size_t size) inline static private
Definition at line 126 of file scfx_mant.hh.
References free_word().
Referenced by operator=(), resize_to(), and ~scfx_mant().
free_word()
void sc_dt::scfx_mant::free_word (word * array, std::size_t size) static private
Definition at line 106 of file scfx_mant.cc.
References sc_dt::word_list::m_next_p, and sc_dt::next_pow2_index().
Referenced by free().
half_addr()
half_word * sc_dt::scfx_mant::half_addr (int i = 0) const inline
Definition at line 282 of file scfx_mant.hh.
References ArmISA::i, m_array, m_size, and SC_ASSERT_.
Referenced by sc_dt::multiply().
half_at() [1/2]
half_word sc_dt::scfx_mant::half_at (int i) const inline
Definition at line 258 of file scfx_mant.hh.
References m_array, m_size, and SC_ASSERT_.
half_at() [2/2]
half_word & sc_dt::scfx_mant::half_at (int i) inline
Definition at line 270 of file scfx_mant.hh.
References m_array, m_size, and SC_ASSERT_.
operator=()
scfx_mant & sc_dt::scfx_mant::operator= (const scfx_mant & rhs) inline
Definition at line 172 of file scfx_mant.hh.
References alloc(), free(), ArmISA::i, m_array, and m_size.
operator[]() [1/2]
word sc_dt::scfx_mant::operator[] (int i) const inline
Definition at line 136 of file scfx_mant.hh.
References ArmISA::i, m_array, m_size, and SC_ASSERT_.
operator[]() [2/2]
word & sc_dt::scfx_mant::operator[] (int i) inline
Definition at line 147 of file scfx_mant.hh.
References ArmISA::i, m_array, m_size, and SC_ASSERT_.
resize_to()
void sc_dt::scfx_mant::resize_to (int size, int restore = 0) inline
Definition at line 203 of file scfx_mant.hh.
References alloc(), free(), ArmISA::i, m_array, m_size, MipsISA::p, sc_dt::sc_min(), and size().
Referenced by sc_dt::scfx_rep::resize_to().
size()
int sc_dt::scfx_mant::size () const inline
Definition at line 113 of file scfx_mant.hh.
References m_size.
Referenced by sc_dt::complement(), sc_dt::scfx_rep::from_string(), sc_dt::inc(), sc_dt::scfx_rep::multiply_by_ten(), resize_to(), sc_dt::scfx_rep::size(), and sc_dt::scfx_rep::toggle_tc().
Member Data Documentation
m_array
word* sc_dt::scfx_mant::m_array private
Definition at line 77 of file scfx_mant.hh.
Referenced by half_addr(), half_at(), operator=(), operator[](), resize_to(), scfx_mant(), and ~scfx_mant().
m_size
int sc_dt::scfx_mant::m_size private
Definition at line 78 of file scfx_mant.hh.
Referenced by clear(), half_addr(), half_at(), operator=(), operator[](), resize_to(), scfx_mant(), size(), and ~scfx_mant().
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/scfx_mant.hh
systemc/dt/fx/scfx_mant.cc