gem5: SimpleNetwork Class Reference
SimpleNetwork Class Reference
#include <SimpleNetwork.hh>
Public Types
typedef SimpleNetworkParams Params
Public Types inherited from Network
typedef RubyNetworkParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
SimpleNetwork (const Params *p)
~SimpleNetwork ()
void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
int getBufferSize ()
int getEndpointBandwidth ()
bool getAdaptiveRouting ()
void collateStats ()
void regStats ()
Callback to set stat parameters.
bool isVNetOrdered (int vnet) const
void makeExtOutLink (SwitchID src, NodeID dest, BasicLink *link, const NetDest &routing_table_entry)
void makeExtInLink (NodeID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry)
void makeInternalLink (SwitchID src, SwitchID dest, BasicLink *link, const NetDest &routing_table_entry, PortDirection src_outport, PortDirection dst_inport)
void print (std::ostream &out) const
bool functionalRead (Packet *pkt)
uint32_t functionalWrite (Packet *pkt)
Public Member Functions inherited from Network
Network (const Params *p)
const Params * params () const
virtual ~Network ()
int getNumNodes () const
void setToNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void setFromNetQueue (NodeID id, bool ordered, int netNumber, std::string vnet_type, MessageBuffer *b)
virtual void checkNetworkAllocation (NodeID id, bool ordered, int network_num, std::string vnet_type)
NodeID addressToNodeID (Addr addr, MachineType mtype)
Map an address to the correct NodeID.
Port & getPort (const std::string &, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
void addLink (SwitchID src, SwitchID dest, int link_latency)
void makeLink (SwitchID src, SwitchID dest, const NetDest &routing_table_entry, int link_latency)
void makeTopology ()
SimpleNetwork (const SimpleNetwork &obj)
SimpleNetwork & operator= (const SimpleNetwork &obj)
Private Attributes
std::vector< Switch * > m_switches
std::vector< MessageBuffer * > m_int_link_buffers
int m_num_connected_buffers
const int m_buffer_size
const int m_endpoint_bandwidth
const bool m_adaptive_routing
Stats::Formula m_msg_counts [MessageSizeType_NUM]
Stats::Formula m_msg_bytes [MessageSizeType_NUM]
Additional Inherited Members
Static Public Member Functions inherited from Network
static uint32_t getNumberOfVirtualNetworks ()
static uint32_t MessageSizeType_to_int (MessageSizeType size_type)
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Network
Network (const Network &obj)
Network & operator= (const Network &obj)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from Network
uint32_t m_nodes
std::vector< std::string > m_vnet_type_names
Topology * m_topology_ptr
std::vector< std::vector< MessageBuffer * > > m_toNetQueues
std::vector< std::vector< MessageBuffer * > > m_fromNetQueues
std::vector< bool > m_ordered
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes inherited from Network
static uint32_t m_virtual_networks
static uint32_t m_control_msg_size
static uint32_t m_data_msg_size
Detailed Description
Definition at line 43 of file SimpleNetwork.hh.
Member Typedef Documentation
Params
typedef SimpleNetworkParams SimpleNetwork::Params
Definition at line 46 of file SimpleNetwork.hh.
Constructor & Destructor Documentation
SimpleNetwork() [1/2]
SimpleNetwork::SimpleNetwork (const Params * p)
Definition at line 46 of file SimpleNetwork.cc.
References ArmISA::i, Switch::init_net_ptr(), m_int_link_buffers, m_num_connected_buffers, m_switches, ArmISA::s, and safe_cast().
Referenced by isVNetOrdered(), and print().
~SimpleNetwork()
SimpleNetwork::~SimpleNetwork ()
Definition at line 74 of file SimpleNetwork.cc.
References m5::stl_helpers::deletePointers(), m_int_link_buffers, and m_switches.
SimpleNetwork() [2/2]
SimpleNetwork::SimpleNetwork (const SimpleNetwork & obj) private
Member Function Documentation
addLink()
void SimpleNetwork::addLink (SwitchID src, SwitchID dest, int link_latency) private
Referenced by isVNetOrdered().
collateStats()
void SimpleNetwork::collateStats () virtual
Implements Network.
Definition at line 161 of file SimpleNetwork.cc.
References ArmISA::i, and m_switches.
Referenced by getAdaptiveRouting().
functionalRead()
bool SimpleNetwork::functionalRead (Packet * pkt) virtual
Reimplemented from Network.
Definition at line 186 of file SimpleNetwork.cc.
References ArmISA::i, and m_switches.
Referenced by isVNetOrdered().
functionalWrite()
uint32_t SimpleNetwork::functionalWrite (Packet * pkt) virtual
Reimplemented from Network.
Definition at line 198 of file SimpleNetwork.cc.
References ArmISA::i, m_int_link_buffers, and m_switches.
Referenced by isVNetOrdered().
getAdaptiveRouting()
bool SimpleNetwork::getAdaptiveRouting () inline
Definition at line 54 of file SimpleNetwork.hh.
References collateStats(), m_adaptive_routing, and regStats().
Referenced by PerfectSwitch::operateMessageBuffer().
getBufferSize()
int SimpleNetwork::getBufferSize () inline
Definition at line 52 of file SimpleNetwork.hh.
References m_buffer_size.
getEndpointBandwidth()
int SimpleNetwork::getEndpointBandwidth () inline
Definition at line 53 of file SimpleNetwork.hh.
References m_endpoint_bandwidth.
Referenced by Switch::addOutPort().
init()
void SimpleNetwork::init () virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from Network.
Definition at line 64 of file SimpleNetwork.cc.
References Topology::createLinks(), Network::init(), and Network::m_topology_ptr.
isVNetOrdered()
bool SimpleNetwork::isVNetOrdered (int vnet) const inline
Definition at line 59 of file SimpleNetwork.hh.
References addLink(), functionalRead(), functionalWrite(), Network::m_ordered, makeExtInLink(), makeExtOutLink(), makeInternalLink(), makeLink(), makeTopology(), operator=(), print(), and SimpleNetwork().
Referenced by PerfectSwitch::operateMessageBuffer().
makeExtInLink()
void SimpleNetwork::makeExtInLink (NodeID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry) virtual
Implements Network.
Definition at line 98 of file SimpleNetwork.cc.
References Network::m_nodes, m_switches, and Network::m_toNetQueues.
Referenced by isVNetOrdered().
makeExtOutLink()
void SimpleNetwork::makeExtOutLink (SwitchID src, NodeID dest, BasicLink * link, const NetDest & routing_table_entry) virtual
Implements Network.
Definition at line 82 of file SimpleNetwork.cc.
References SimpleExtLink::m_bw_multiplier, Network::m_fromNetQueues, BasicLink::m_latency, Network::m_nodes, m_switches, and safe_cast().
Referenced by isVNetOrdered().
makeInternalLink()
void SimpleNetwork::makeInternalLink (SwitchID src, SwitchID dest, BasicLink * link, const NetDest & routing_table_entry, PortDirection src_outport, PortDirection dst_inport) virtual
Implements Network.
Definition at line 107 of file SimpleNetwork.cc.
References ArmISA::i, SimpleIntLink::m_bw_multiplier, m_int_link_buffers, BasicLink::m_latency, m_num_connected_buffers, m_switches, Network::m_virtual_networks, and safe_cast().
Referenced by isVNetOrdered().
makeLink()
void SimpleNetwork::makeLink (SwitchID src, SwitchID dest, const NetDest & routing_table_entry, int link_latency) private
Referenced by isVNetOrdered().
makeTopology()
void SimpleNetwork::makeTopology () private
Referenced by isVNetOrdered().
operator=()
SimpleNetwork& SimpleNetwork::operator= (const SimpleNetwork & obj) private
Referenced by isVNetOrdered().
print()
void SimpleNetwork::print (std::ostream & out) const virtual
Implements Network.
Definition at line 169 of file SimpleNetwork.cc.
References SimpleNetwork().
Referenced by isVNetOrdered(), and operator<<().
regStats()
void SimpleNetwork::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 133 of file SimpleNetwork.cc.
References Stats::constant(), ArmISA::i, m_msg_bytes, m_msg_counts, m_switches, Network::MessageSizeType_to_int(), SimObject::name(), Stats::nozero, Stats::Group::regStats(), RiscvISA::sum, and type.
Referenced by getAdaptiveRouting().
Member Data Documentation
m_adaptive_routing
const bool SimpleNetwork::m_adaptive_routing private
Definition at line 91 of file SimpleNetwork.hh.
Referenced by getAdaptiveRouting().
m_buffer_size
const int SimpleNetwork::m_buffer_size private
Definition at line 89 of file SimpleNetwork.hh.
Referenced by getBufferSize().
m_endpoint_bandwidth
const int SimpleNetwork::m_endpoint_bandwidth private
Definition at line 90 of file SimpleNetwork.hh.
Referenced by getEndpointBandwidth().
m_int_link_buffers
std::vector<MessageBuffer*> SimpleNetwork::m_int_link_buffers private
Definition at line 87 of file SimpleNetwork.hh.
Referenced by functionalWrite(), makeInternalLink(), SimpleNetwork(), and ~SimpleNetwork().
m_msg_bytes
Stats::Formula SimpleNetwork::m_msg_bytes[MessageSizeType_NUM] private
Definition at line 95 of file SimpleNetwork.hh.
Referenced by regStats().
m_msg_counts
Stats::Formula SimpleNetwork::m_msg_counts[MessageSizeType_NUM] private
Definition at line 94 of file SimpleNetwork.hh.
Referenced by regStats().
m_num_connected_buffers
int SimpleNetwork::m_num_connected_buffers private
Definition at line 88 of file SimpleNetwork.hh.
Referenced by makeInternalLink(), and SimpleNetwork().
m_switches
std::vector<Switch*> SimpleNetwork::m_switches private
Definition at line 86 of file SimpleNetwork.hh.
Referenced by collateStats(), functionalRead(), functionalWrite(), makeExtInLink(), makeExtOutLink(), makeInternalLink(), regStats(), SimpleNetwork(), and ~SimpleNetwork().
The documentation for this class was generated from the following files:
mem/ruby/network/simple/SimpleNetwork.hh
mem/ruby/network/simple/SimpleNetwork.cc