gem5: tlm_utils::instance_specific_extension_container Class Reference
tlm_utils::instance_specific_extension_container Class Reference
#include <instance_specific_extensions_int.h>
Private Types
typedef void release_fn(instance_specific_extension_carrier *, void *)
Private Member Functions
instance_specific_extension_container ()
~instance_specific_extension_container ()
void resize ()
void inc_use_count ()
void dec_use_count ()
void attach_carrier (instance_specific_extension_carrier *, void *txn, release_fn *)
instance_specific_extensions_per_accessor * get_accessor (unsigned int index)
Static Private Member Functions
static instance_specific_extension_container * create ()
Private Attributes
std::vector< instance_specific_extensions_per_accessor * > m_ispex_per_accessor
unsigned int use_count
void * m_txn
release_fn * m_release_fn
instance_specific_extension_carrier * m_carrier
instance_specific_extension_container * next
Friends
class instance_specific_extension_accessor
class instance_specific_extension_carrier
class instance_specific_extension_container_pool
class instance_specific_extensions_per_accessor
Detailed Description
Definition at line 124 of file instance_specific_extensions_int.h.
Member Typedef Documentation
release_fn
typedef void tlm_utils::instance_specific_extension_container::release_fn(instance_specific_extension_carrier *, void *) private
Definition at line 131 of file instance_specific_extensions_int.h.
Constructor & Destructor Documentation
instance_specific_extension_container()
tlm_utils::instance_specific_extension_container::instance_specific_extension_container () private
Definition at line 162 of file instance_specific_extensions.cc.
References attach_carrier(), and resize().
~instance_specific_extension_container()
tlm_utils::instance_specific_extension_container::~instance_specific_extension_container () private
Definition at line 191 of file instance_specific_extensions.cc.
References ArmISA::i, and m_ispex_per_accessor.
Referenced by resize().
Member Function Documentation
attach_carrier()
void tlm_utils::instance_specific_extension_container::attach_carrier (instance_specific_extension_carrier * carrier, void * txn, release_fn * rel_fn) private
Definition at line 170 of file instance_specific_extensions.cc.
References m_carrier, m_release_fn, and m_txn.
Referenced by instance_specific_extension_container(), and tlm_utils::instance_specific_extension_accessor::operator()().
create()
instance_specific_extension_container * tlm_utils::instance_specific_extension_container::create () static private
Definition at line 156 of file instance_specific_extensions.cc.
References create().
Referenced by create(), and tlm_utils::instance_specific_extension_accessor::operator()().
dec_use_count()
void tlm_utils::instance_specific_extension_container::dec_use_count () private
Definition at line 204 of file instance_specific_extensions.cc.
References tlm_utils::instance_specific_extension_container_pool::free(), tlm_utils::instance_specific_extension_container_pool::instance(), m_carrier, m_release_fn, m_txn, and use_count.
get_accessor()
instance_specific_extensions_per_accessor * tlm_utils::instance_specific_extension_container::get_accessor (unsigned int index) private
Definition at line 216 of file instance_specific_extensions.cc.
References m_ispex_per_accessor.
Referenced by tlm_utils::instance_specific_extension_accessor::operator()().
inc_use_count()
void tlm_utils::instance_specific_extension_container::inc_use_count () private
Definition at line 198 of file instance_specific_extensions.cc.
References use_count.
resize()
void tlm_utils::instance_specific_extension_container::resize () private
Definition at line 179 of file instance_specific_extensions.cc.
References ArmISA::i, instance_specific_extensions_per_accessor, m_ispex_per_accessor, tlm_utils::max_num_ispex_accessors(), and ~instance_specific_extension_container().
Referenced by instance_specific_extension_container().
Friends And Related Function Documentation
instance_specific_extension_accessor
friend class instance_specific_extension_accessor friend
Definition at line 126 of file instance_specific_extensions_int.h.
instance_specific_extension_carrier
friend class instance_specific_extension_carrier friend
Definition at line 127 of file instance_specific_extensions_int.h.
instance_specific_extension_container_pool
friend class instance_specific_extension_container_pool friend
Definition at line 128 of file instance_specific_extensions_int.h.
instance_specific_extensions_per_accessor
friend class instance_specific_extensions_per_accessor friend
Definition at line 129 of file instance_specific_extensions_int.h.
Referenced by resize().
Member Data Documentation
m_carrier
instance_specific_extension_carrier* tlm_utils::instance_specific_extension_container::m_carrier private
Definition at line 153 of file instance_specific_extensions_int.h.
Referenced by attach_carrier(), and dec_use_count().
m_ispex_per_accessor
std::vector<instance_specific_extensions_per_accessor *> tlm_utils::instance_specific_extension_container::m_ispex_per_accessor private
Definition at line 149 of file instance_specific_extensions_int.h.
Referenced by get_accessor(), resize(), and ~instance_specific_extension_container().
m_release_fn
release_fn* tlm_utils::instance_specific_extension_container::m_release_fn private
Definition at line 152 of file instance_specific_extensions_int.h.
Referenced by attach_carrier(), and dec_use_count().
m_txn
void* tlm_utils::instance_specific_extension_container::m_txn private
Definition at line 151 of file instance_specific_extensions_int.h.
Referenced by attach_carrier(), and dec_use_count().
next
instance_specific_extension_container* tlm_utils::instance_specific_extension_container::next private
Definition at line 154 of file instance_specific_extensions_int.h.
Referenced by tlm_utils::instance_specific_extension_container_pool::create(), tlm_utils::instance_specific_extension_container_pool::free(), and tlm_utils::instance_specific_extension_container_pool::~instance_specific_extension_container_pool().
use_count
unsigned int tlm_utils::instance_specific_extension_container::use_count private
Definition at line 150 of file instance_specific_extensions_int.h.
Referenced by dec_use_count(), and inc_use_count().
The documentation for this class was generated from the following files:
systemc/ext/tlm_utils/instance_specific_extensions_int.h
systemc/tlm_utils/instance_specific_extensions.cc