gem5: sc_dt::sc_ufix_fast Class Reference
sc_dt::sc_ufix_fast Class Reference
#include <sc_ufix.hh>
Public Member Functions
sc_ufix_fast (sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, int, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (int, int, sc_q_mode, sc_o_mode, int, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxtype_params &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_fxtype_params &, const sc_fxcast_switch &, sc_fxnum_fast_observer *=0)
sc_ufix_fast (const sc_ufix_fast &)
const sc_ufix_fast operator~ () const
sc_ufix_fast & operator= (const sc_ufix_fast &)
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_ufix_fast & operator++ ()
sc_ufix_fast & operator-- ()
Public Member Functions inherited from sc_dt::sc_fxnum_fast
const sc_fxval_fast operator- () const
const sc_fxval_fast operator+ () const
DECL_BIN_OP_T (/, int64) DECL_BIN_OP_T(/
uint64 DECL_BIN_OP_T (/, const sc_int_base &) DECL_BIN_OP_T(/
uint64 const sc_uint_base & DECL_BIN_OP_T (/, const sc_signed &) friend const sc_fxval_fast operator<<(const sc_fxnum_fast &
const sc_fxval_fast operator++ (int)
const sc_fxval_fast operator-- (int)
sc_fxnum_fast & operator++ ()
sc_fxnum_fast & operator-- ()
const sc_fxnum_fast_bitref operator[] (int) const
sc_fxnum_fast_bitref operator[] (int)
const sc_fxnum_fast_bitref bit (int) const
sc_fxnum_fast_bitref bit (int)
const sc_fxnum_fast_subref operator() (int, int) const
sc_fxnum_fast_subref operator() (int, int)
const sc_fxnum_fast_subref range (int, int) const
sc_fxnum_fast_subref range (int, int)
const sc_fxnum_fast_subref operator() () const
sc_fxnum_fast_subref operator() ()
const sc_fxnum_fast_subref range () const
sc_fxnum_fast_subref range ()
operator double () const
short to_short () const
unsigned short to_ushort () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
float to_float () const
double to_double () const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
const std::string to_string (sc_fmt) const
const std::string to_string (sc_numrep, sc_fmt) const
const std::string to_string (sc_numrep, bool, sc_fmt) const
const std::string to_dec () const
const std::string to_bin () const
const std::string to_oct () const
const std::string to_hex () const
bool is_neg () const
bool is_zero () const
bool is_normal () const
bool quantization_flag () const
bool overflow_flag () const
const sc_fxval_fast value () const
int wl () const
int iwl () const
sc_q_mode q_mode () const
sc_o_mode o_mode () const
int n_bits () const
const sc_fxtype_params & type_params () const
const sc_fxcast_switch & cast_switch () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
void observer_read () const
bool get_bit (int) const
Friends
void b_not (sc_ufix_fast &, const sc_ufix_fast &)
const sc_ufix_fast operator& (const sc_ufix_fast &, const sc_ufix_fast &)
const sc_ufix_fast operator^ (const sc_ufix_fast &, const sc_ufix_fast &)
const sc_ufix_fast operator| (const sc_ufix_fast &, const sc_ufix_fast &)
void b_and (sc_ufix_fast &, const sc_ufix_fast &, const sc_ufix_fast &)
void b_or (sc_ufix_fast &, const sc_ufix_fast &, const sc_ufix_fast &)
void b_xor (sc_ufix_fast &, const sc_ufix_fast &, const sc_ufix_fast &)
Additional Inherited Members
Public Attributes inherited from sc_dt::sc_fxnum_fast
uint64 const sc_uint_base int
Protected Member Functions inherited from sc_dt::sc_fxnum_fast
sc_fxnum_fast_observer * observer () const
void cast ()
sc_fxnum_fast (const sc_fxtype_params &, sc_enc, const sc_fxcast_switch &, sc_fxnum_fast_observer *)
~sc_fxnum_fast ()
double get_val () const
bool set_bit (int, bool)
bool get_slice (int, int, sc_bv_base &) const
bool set_slice (int, int, const sc_bv_base &)
sc_fxnum_fast_observer * lock_observer () const
void unlock_observer (sc_fxnum_fast_observer *) const
Detailed Description
Definition at line 238 of file sc_ufix.hh.
Constructor & Destructor Documentation
sc_ufix_fast() [1/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 892 of file sc_ufix.hh.
Referenced by operator~().
sc_ufix_fast() [2/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 897 of file sc_ufix.hh.
sc_ufix_fast() [3/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (sc_q_mode qm, sc_o_mode om, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 903 of file sc_ufix.hh.
sc_ufix_fast() [4/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 909 of file sc_ufix.hh.
sc_ufix_fast() [5/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 915 of file sc_ufix.hh.
sc_ufix_fast() [6/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 922 of file sc_ufix.hh.
sc_ufix_fast() [7/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 929 of file sc_ufix.hh.
sc_ufix_fast() [8/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 934 of file sc_ufix.hh.
sc_ufix_fast() [9/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 940 of file sc_ufix.hh.
sc_ufix_fast() [10/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 946 of file sc_ufix.hh.
sc_ufix_fast() [11/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 952 of file sc_ufix.hh.
sc_ufix_fast() [12/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (int wl_, int iwl_, sc_q_mode qm, sc_o_mode om, int nb, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 959 of file sc_ufix.hh.
sc_ufix_fast() [13/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (const sc_fxtype_params & type_params_, sc_fxnum_fast_observer * observer_ = 0) inline explicit
Definition at line 966 of file sc_ufix.hh.
sc_ufix_fast() [14/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (const sc_fxtype_params & type_params_, const sc_fxcast_switch & cast_sw, sc_fxnum_fast_observer * observer_ = 0) inline
Definition at line 971 of file sc_ufix.hh.
sc_ufix_fast() [15/15]
sc_dt::sc_ufix_fast::sc_ufix_fast (const sc_ufix_fast & a) inline
Definition at line 1178 of file sc_ufix.hh.
Member Function Documentation
operator++() [1/2]
const sc_fxval_fast sc_dt::sc_ufix_fast::operator++ (int) inline
Definition at line 1327 of file sc_ufix.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator++() [2/2]
sc_ufix_fast & sc_dt::sc_ufix_fast::operator++ () inline
Definition at line 1339 of file sc_ufix.hh.
References sc_dt::sc_fxnum_fast::operator++().
Referenced by sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator++().
operator--() [1/2]
const sc_fxval_fast sc_dt::sc_ufix_fast::operator-- (int) inline
Definition at line 1333 of file sc_ufix.hh.
References sc_dt::sc_fxnum_fast::sc_fxval_fast.
operator--() [2/2]
sc_ufix_fast & sc_dt::sc_ufix_fast::operator-- () inline
Definition at line 1346 of file sc_ufix.hh.
References sc_dt::sc_fxnum_fast::operator--().
Referenced by sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator--().
operator=()
sc_ufix_fast & sc_dt::sc_ufix_fast::operator= (const sc_ufix_fast & a) inline
Definition at line 1252 of file sc_ufix.hh.
Referenced by sc_dt::sc_ufixed_fast< W, I, Q, O, N >::operator=().
operator~()
const sc_ufix_fast sc_dt::sc_ufix_fast::operator~ () const inline
Definition at line 1184 of file sc_ufix.hh.
References ArmISA::c, sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::iwl(), SC_FXNUM_FAST_OBSERVER_READ_, sc_ufix_fast(), sc_dt::sc_fxnum_fast::set_bit(), and sc_dt::sc_fxnum_fast::wl().
Friends And Related Function Documentation
b_and
void b_and (sc_ufix_fast & , const sc_ufix_fast & , const sc_ufix_fast &) friend
b_not
void b_not (sc_ufix_fast & c, const sc_ufix_fast & a) friend
Definition at line 1197 of file sc_ufix.hh.
b_or
void b_or (sc_ufix_fast & , const sc_ufix_fast & , const sc_ufix_fast &) friend
b_xor
void b_xor (sc_ufix_fast & , const sc_ufix_fast & , const sc_ufix_fast &) friend
operator&
const sc_ufix_fast operator & (const sc_ufix_fast & , const sc_ufix_fast &) friend
operator^
const sc_ufix_fast operator^ (const sc_ufix_fast & , const sc_ufix_fast &) friend
operator|
const sc_ufix_fast operator| (const sc_ufix_fast & , const sc_ufix_fast &) friend
The documentation for this class was generated from the following file:
systemc/ext/dt/fx/sc_ufix.hh