gem5: Debug::Flag Class Reference
Debug::Flag Class Reference abstract
#include <debug.hh>
Public Member Functions
Flag (const char *name, const char *desc)
virtual ~Flag ()
std::string name () const
std::string desc () const
virtual std::vector< Flag * > kids ()
virtual void enable ()=0
virtual void disable ()=0
virtual void sync ()
Protected Attributes
const char * _name
const char * _desc
Detailed Description
Definition at line 43 of file debug.hh.
Constructor & Destructor Documentation
Flag()
Debug::Flag::Flag (const char * name, const char * desc)
Definition at line 83 of file debug.cc.
References Debug::allFlags(), Debug::allFlagsVersion, and panic.
~Flag()
Debug::Flag::~Flag () virtual
Definition at line 95 of file debug.cc.
Member Function Documentation
desc()
std::string Debug::Flag::desc () const inline
Definition at line 54 of file debug.hh.
References _desc.
Referenced by pybind_init_debug().
disable()
virtual void Debug::Flag::disable () pure virtual
Implemented in Debug::AllFlags, Debug::CompoundFlag, and Debug::SimpleFlag.
Referenced by Debug::changeFlag(), kids(), Debug::CompoundFlag::kids(), and pybind_init_debug().
enable()
virtual void Debug::Flag::enable () pure virtual
Implemented in Debug::AllFlags, Debug::CompoundFlag, and Debug::SimpleFlag.
Referenced by Debug::changeFlag(), kids(), Debug::CompoundFlag::kids(), and pybind_init_debug().
kids()
virtual std::vector<Flag *> Debug::Flag::kids () inline virtual
Reimplemented in Debug::CompoundFlag.
Definition at line 55 of file debug.hh.
References disable(), and enable().
Referenced by pybind_init_debug().
name()
std::string Debug::Flag::name () const inline
Definition at line 53 of file debug.hh.
References _name.
Referenced by dumpDebugFlags(), and pybind_init_debug().
sync()
virtual void Debug::Flag::sync () inline virtual
Reimplemented in Debug::SimpleFlag.
Definition at line 59 of file debug.hh.
Referenced by Debug::SimpleFlag::disable(), Debug::SimpleFlag::enable(), and pybind_init_debug().
Member Data Documentation
_desc
const char* Debug::Flag::_desc protected
Definition at line 47 of file debug.hh.
Referenced by desc().
_name
const char* Debug::Flag::_name protected
Definition at line 46 of file debug.hh.
Referenced by name().
The documentation for this class was generated from the following files:
base/debug.hh
base/debug.cc