gem5: ItsProcess Class Reference
ItsProcess Class Reference abstract
ItsProcess is a base coroutine wrapper which is spawned by the Gicv3Its module when the latter needs to perform different actions, like translating a peripheral's MSI into an LPI (See derived ItsTranslation) or processing a Command from the ITS queue (ItsCommand).
#include <gic_v3_its.hh>
Public Types
using DTE = Gicv3Its::DTE
using ITTE = Gicv3Its::ITTE
using CTE = Gicv3Its::CTE
using Coroutine = m5::Coroutine< PacketPtr, ItsAction >
using Yield = Coroutine::CallerType
Public Member Functions
ItsProcess (Gicv3Its &_its)
virtual ~ItsProcess ()
const std::string name () const
Returns the Gicv3Its name.
ItsAction run (PacketPtr pkt)
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Protected Member Functions
void reinit ()
virtual void main (Yield &yield)=0
void writeDeviceTable (Yield &yield, uint32_t device_id, DTE dte)
void writeIrqTranslationTable (Yield &yield, const Addr itt_base, uint32_t event_id, ITTE itte)
void writeIrqCollectionTable (Yield &yield, uint32_t collection_id, CTE cte)
uint64_t readDeviceTable (Yield &yield, uint32_t device_id)
uint64_t readIrqTranslationTable (Yield &yield, const Addr itt_base, uint32_t event_id)
uint64_t readIrqCollectionTable (Yield &yield, uint32_t collection_id)
void doRead (Yield &yield, Addr addr, void *ptr, size_t size)
void doWrite (Yield &yield, Addr addr, void *ptr, size_t size)
void terminate (Yield &yield)
Protected Attributes
Gicv3Its & its
Private Attributes
std::unique_ptr< Coroutine > coroutine
Additional Inherited Members
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Detailed Description
ItsProcess is a base coroutine wrapper which is spawned by the Gicv3Its module when the latter needs to perform different actions, like translating a peripheral's MSI into an LPI (See derived ItsTranslation) or processing a Command from the ITS queue (ItsCommand).
The action to take is implemented by the method:
virtual void main(Yield &yield) = 0; It's inheriting from Packet::SenderState since the generic process will be stopped (we are using coroutines) and sent with the packet to memory when doing table walks. When Gicv3Its receives a response, it will resume the coroutine from the point it stopped when yielding.
Definition at line 347 of file gic_v3_its.hh.
Member Typedef Documentation
Coroutine
using ItsProcess::Coroutine = m5::Coroutine<PacketPtr, ItsAction>
Definition at line 353 of file gic_v3_its.hh.
CTE
using ItsProcess::CTE = Gicv3Its::CTE
Definition at line 352 of file gic_v3_its.hh.
DTE
using ItsProcess::DTE = Gicv3Its::DTE
Definition at line 350 of file gic_v3_its.hh.
ITTE
using ItsProcess::ITTE = Gicv3Its::ITTE
Definition at line 351 of file gic_v3_its.hh.
Yield
using ItsProcess::Yield = Coroutine::CallerType
Definition at line 354 of file gic_v3_its.hh.
Constructor & Destructor Documentation
ItsProcess()
ItsProcess::ItsProcess (Gicv3Its & _its)
Definition at line 57 of file gic_v3_its.cc.
~ItsProcess()
ItsProcess::~ItsProcess () virtual
Definition at line 62 of file gic_v3_its.cc.
Member Function Documentation
doRead()
void ItsProcess::doRead (Yield & yield, Addr addr, void * ptr, size_t size) protected
Definition at line 88 of file gic_v3_its.cc.
References ArmISA::a, addr, Packet::dataStatic(), ItsAction::delay, ContextSwitchTaskId::DMA, m5::Coroutine< Arg, Ret >::CallerType::get(), Packet::getSize(), its, Gicv3Its::masterId, ItsAction::pkt, MemCmd::ReadReq, SEND_REQ, Gicv3Its::size, and ItsAction::type.
Referenced by ItsCommand::readCommand(), readDeviceTable(), readIrqCollectionTable(), and readIrqTranslationTable().
doWrite()
void ItsProcess::doWrite (Yield & yield, Addr addr, void * ptr, size_t size) protected
Definition at line 112 of file gic_v3_its.cc.
References ArmISA::a, addr, Packet::dataStatic(), ItsAction::delay, ContextSwitchTaskId::DMA, m5::Coroutine< Arg, Ret >::CallerType::get(), Packet::getSize(), its, Gicv3Its::masterId, ItsAction::pkt, SEND_REQ, Gicv3Its::size, ItsAction::type, and MemCmd::WriteReq.
Referenced by writeDeviceTable(), writeIrqCollectionTable(), and writeIrqTranslationTable().
main()
virtual void ItsProcess::main (Yield & yield) protected pure virtual
Implemented in ItsCommand, and ItsTranslation.
Referenced by reinit().
name()
const std::string ItsProcess::name () const
Returns the Gicv3Its name.
Mainly used for DPRINTS
Definition at line 74 of file gic_v3_its.cc.
References its, and SimObject::name().
readDeviceTable()
uint64_t ItsProcess::readDeviceTable (Yield & yield, uint32_t device_id) protected
Definition at line 180 of file gic_v3_its.cc.
References X86ISA::base, Gicv3Its::DEVICE_TABLE, doRead(), DPRINTF, its, and Gicv3Its::pageAddress().
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::inv(), ItsCommand::mapi(), ItsCommand::mapti(), ItsCommand::movi(), and ItsTranslation::translateLPI().
readIrqCollectionTable()
uint64_t ItsProcess::readIrqCollectionTable (Yield & yield, uint32_t collection_id) protected
Definition at line 206 of file gic_v3_its.cc.
References X86ISA::base, Gicv3Its::COLLECTION_TABLE, doRead(), DPRINTF, its, and Gicv3Its::pageAddress().
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::inv(), ItsCommand::invall(), ItsCommand::movi(), and ItsTranslation::translateLPI().
readIrqTranslationTable()
uint64_t ItsProcess::readIrqTranslationTable (Yield & yield, const Addr itt_base, uint32_t event_id) protected
Definition at line 193 of file gic_v3_its.cc.
References doRead(), and DPRINTF.
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::inv(), ItsCommand::mapi(), ItsCommand::mapti(), ItsCommand::movi(), and ItsTranslation::translateLPI().
reinit()
void ItsProcess::reinit () protected
Definition at line 67 of file gic_v3_its.cc.
References coroutine, and main().
Referenced by ItsCommand::ItsCommand(), and ItsTranslation::ItsTranslation().
run()
ItsAction ItsProcess::run (PacketPtr pkt)
Definition at line 80 of file gic_v3_its.cc.
References coroutine.
Referenced by Gicv3Its::runProcessAtomic(), and Gicv3Its::runProcessTiming().
terminate()
void ItsProcess::terminate (Yield & yield) protected
Definition at line 136 of file gic_v3_its.cc.
References ArmISA::a, ItsAction::delay, ItsAction::pkt, TERMINATE, and ItsAction::type.
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), ItsCommand::inv(), ItsCommand::invall(), ItsTranslation::main(), ItsCommand::main(), ItsCommand::mapc(), ItsCommand::mapd(), ItsCommand::mapi(), ItsCommand::mapti(), ItsCommand::movi(), and ItsTranslation::translateLPI().
writeDeviceTable()
void ItsProcess::writeDeviceTable (Yield & yield, uint32_t device_id, DTE dte) protected
Definition at line 146 of file gic_v3_its.cc.
References X86ISA::base, Gicv3Its::DEVICE_TABLE, doWrite(), DPRINTF, its, and Gicv3Its::pageAddress().
Referenced by ItsCommand::mapd().
writeIrqCollectionTable()
void ItsProcess::writeIrqCollectionTable (Yield & yield, uint32_t collection_id, CTE cte) protected
Definition at line 168 of file gic_v3_its.cc.
References X86ISA::base, Gicv3Its::COLLECTION_TABLE, doWrite(), DPRINTF, its, and Gicv3Its::pageAddress().
Referenced by ItsCommand::mapc().
writeIrqTranslationTable()
void ItsProcess::writeIrqTranslationTable (Yield & yield, const Addr itt_base, uint32_t event_id, ITTE itte) protected
Definition at line 157 of file gic_v3_its.cc.
References doWrite(), and DPRINTF.
Referenced by ItsCommand::discard(), ItsCommand::mapi(), ItsCommand::mapti(), and ItsCommand::movi().
Member Data Documentation
coroutine
std::unique_ptr<Coroutine> ItsProcess::coroutine private
Definition at line 392 of file gic_v3_its.hh.
Referenced by reinit(), and run().
its
Gicv3Its& ItsProcess::its protected
Definition at line 389 of file gic_v3_its.hh.
Referenced by ItsCommand::clear(), ItsCommand::discard(), ItsCommand::doInt(), doRead(), doWrite(), ItsCommand::inv(), ItsCommand::invall(), ItsCommand::ItsCommand(), ItsTranslation::ItsTranslation(), ItsTranslation::main(), ItsCommand::main(), ItsCommand::mapc(), ItsCommand::mapd(), ItsCommand::mapi(), ItsCommand::mapti(), ItsCommand::movall(), ItsCommand::movi(), name(), ItsCommand::readCommand(), readDeviceTable(), readIrqCollectionTable(), ItsTranslation::translateLPI(), writeDeviceTable(), writeIrqCollectionTable(), ItsCommand::~ItsCommand(), and ItsTranslation::~ItsTranslation().
The documentation for this class was generated from the following files:
dev/arm/gic_v3_its.hh
dev/arm/gic_v3_its.cc