gem5: sc_gem5::Gem5ToTlmBridge< BITWIDTH > Class Template Reference
sc_gem5::Gem5ToTlmBridge< BITWIDTH > Class Template Reference
#include <gem5_to_tlm.hh>
Classes
class BridgeSlavePort
Public Types
typedef Gem5ToTlmBridgeBaseParams Params
Public Member Functions
::Port & gem5_getPort (const std::string &if_name, int idx=-1) override
Gem5ToTlmBridge (Params *p, const sc_core::sc_module_name &mn)
tlm_utils::simple_initiator_socket< Gem5ToTlmBridge< BITWIDTH >, BITWIDTH > & getSocket ()
void before_end_of_elaboration () override
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
void pec (Gem5SystemC::PayloadEvent< Gem5ToTlmBridge< BITWIDTH >> *pe, tlm::tlm_generic_payload &trans, const tlm::tlm_phase &phase)
MemBackdoorPtr getBackdoor (tlm::tlm_generic_payload &trans)
Tick recvAtomic (PacketPtr packet)
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
void recvFunctional (PacketPtr packet)
bool recvTimingReq (PacketPtr packet)
bool tryTiming (PacketPtr packet)
bool recvTimingSnoopResp (PacketPtr packet)
void recvRespRetry ()
void recvFunctionalSnoop (PacketPtr packet)
AddrRangeList getAddrRanges () const
tlm::tlm_sync_enum nb_transport_bw (tlm::tlm_generic_payload &trans, tlm::tlm_phase &phase, sc_core::sc_time &t)
void invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range)
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
AddrRangeMap< MemBackdoorPtr > backdoorMap
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Private Attributes
BridgeSlavePort bsp
tlm_utils::simple_initiator_socket< Gem5ToTlmBridge< BITWIDTH >, BITWIDTH > socket
sc_gem5::TlmInitiatorWrapper< BITWIDTH > wrapper
System * system
tlm::tlm_generic_payload * blockingRequest
A transaction after BEGIN_REQ has been sent but before END_REQ, which is blocking the request channel (Exlusion Rule, see IEEE1666)
bool needToSendRequestRetry
Did another gem5 request arrive while currently blocked? This variable is needed when a retry should happen.
tlm::tlm_generic_payload * blockingResponse
A response which has been asked to retry by gem5 and so is blocking the response channel.
AddrRangeList addrRanges
Detailed Description
template<unsigned int BITWIDTH>
class sc_gem5::Gem5ToTlmBridge< BITWIDTH >
Definition at line 90 of file gem5_to_tlm.hh.
Member Typedef Documentation
Params
template<unsigned int BITWIDTH> typedef Gem5ToTlmBridgeBaseParams sc_gem5::Gem5ToTlmBridge< BITWIDTH >::Params
Definition at line 197 of file gem5_to_tlm.hh.
Constructor & Destructor Documentation
Gem5ToTlmBridge()
template<unsigned int BITWIDTH> sc_gem5::Gem5ToTlmBridge< BITWIDTH >::Gem5ToTlmBridge (Params * p, const sc_core::sc_module_name & mn)
Definition at line 462 of file gem5_to_tlm.cc.
Member Function Documentation
before_end_of_elaboration()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration () override virtual
Reimplemented from sc_core::sc_module.
Definition at line 487 of file gem5_to_tlm.cc.
References sc_core::sc_module::before_end_of_elaboration(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::bsp, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::invalidate_direct_mem_ptr(), sc_core::sc_object::name(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::nb_transport_bw(), SlavePort::sendRangeChange(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::socket.
gem5_getPort()
template<unsigned int BITWIDTH> Port & sc_gem5::Gem5ToTlmBridge< BITWIDTH >::gem5_getPort (const std::string & if_name, int idx = -1) override
Definition at line 475 of file gem5_to_tlm.cc.
References sc_gem5::Gem5ToTlmBridge< BITWIDTH >::bsp, sc_core::sc_module::gem5_getPort(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::wrapper.
getAddrRanges()
template<unsigned int BITWIDTH> AddrRangeList sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getAddrRanges () const inline protected
Definition at line 185 of file gem5_to_tlm.hh.
References sc_core::sc_module::gem5_getPort(), and ArmISA::t.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::getAddrRanges().
getBackdoor()
template<unsigned int BITWIDTH> MemBackdoorPtr sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getBackdoor (tlm::tlm_generic_payload & trans) protected
Definition at line 184 of file gem5_to_tlm.cc.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_data_length(), MemBackdoor::NoAccess, MipsISA::r, and MemBackdoor::readable().
getSocket()
template<unsigned int BITWIDTH> tlm_utils::simple_initiator_socket<Gem5ToTlmBridge<BITWIDTH>, BITWIDTH>& sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getSocket () inline
Definition at line 201 of file gem5_to_tlm.hh.
References sc_core::sc_module::before_end_of_elaboration().
invalidate_direct_mem_ptr()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range) protected
Definition at line 445 of file gem5_to_tlm.cc.
References MipsISA::r.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration().
nb_transport_bw()
template<unsigned int BITWIDTH> tlm::tlm_sync_enum sc_gem5::Gem5ToTlmBridge< BITWIDTH >::nb_transport_bw (tlm::tlm_generic_payload & trans, tlm::tlm_phase & phase, sc_core::sc_time & t) protected
Definition at line 432 of file gem5_to_tlm.cc.
References curTick(), X86ISA::pe, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec(), X86ISA::system, tlm::TLM_ACCEPTED, and sc_core::sc_time::value().
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration().
pec()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec (Gem5SystemC::PayloadEvent< Gem5ToTlmBridge< BITWIDTH >> * pe, tlm::tlm_generic_payload & trans, const tlm::tlm_phase & phase) protected
Definition at line 126 of file gem5_to_tlm.cc.
References tlm::BEGIN_RESP, X86ISA::bsp, tlm::END_REQ, tlm::END_RESP, Gem5SystemC::Gem5Extension::getExtension(), X86ISA::pe, tlm::tlm_generic_payload::release(), sc_assert, and sc_core::SC_ZERO_TIME.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::nb_transport_bw(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq().
recvAtomic()
template<unsigned int BITWIDTH> Tick sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic (PacketPtr packet) protected
Definition at line 216 of file gem5_to_tlm.cc.
References Packet::cacheResponding(), Packet::makeResponse(), Packet::needsResponse(), sc_gem5::packet2payload(), panic_if, sc_core::SC_ZERO_TIME, tlm::TLM_IGNORE_COMMAND, and sc_core::sc_time::value().
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvAtomic().
recvAtomicBackdoor()
template<unsigned int BITWIDTH> Tick sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & backdoor) protected
Definition at line 241 of file gem5_to_tlm.cc.
References Packet::cacheResponding(), Packet::makeResponse(), Packet::needsResponse(), sc_gem5::packet2payload(), panic_if, sc_core::SC_ZERO_TIME, and tlm::TLM_IGNORE_COMMAND.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvAtomicBackdoor().
recvFunctional()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvFunctional (PacketPtr packet) protected
Definition at line 415 of file gem5_to_tlm.cc.
References sc_gem5::packet2payload(), and SC_REPORT_FATAL.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvFunctional().
recvFunctionalSnoop()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvFunctionalSnoop (PacketPtr packet) protected
Definition at line 274 of file gem5_to_tlm.cc.
References SC_REPORT_FATAL.
recvRespRetry()
template<unsigned int BITWIDTH> void sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvRespRetry () protected
Definition at line 391 of file gem5_to_tlm.cc.
References X86ISA::bsp, tlm::END_RESP, Gem5SystemC::Gem5Extension::getExtension(), Gem5SystemC::Gem5Extension::getPacket(), tlm::tlm_generic_payload::release(), sc_assert, and sc_core::SC_ZERO_TIME.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvRespRetry().
recvTimingReq()
template<unsigned int BITWIDTH> bool sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq (PacketPtr packet) protected
Definition at line 284 of file gem5_to_tlm.cc.
References tlm::BEGIN_REQ, tlm::BEGIN_RESP, Packet::cacheResponding(), curTick(), tlm::END_REQ, tlm::END_RESP, sc_core::sc_time::from_value(), Packet::headerDelay, Packet::isRead(), Packet::isWrite(), sc_gem5::packet2payload(), panic_if, Packet::payloadDelay, X86ISA::pe, sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec(), sc_assert, ArmISA::status, X86ISA::system, tlm::TLM_ACCEPTED, tlm::TLM_COMPLETED, and tlm::TLM_UPDATED.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvTimingReq().
recvTimingSnoopResp()
template<unsigned int BITWIDTH> bool sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingSnoopResp (PacketPtr packet) protected
Definition at line 374 of file gem5_to_tlm.cc.
References SC_REPORT_FATAL.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::recvTimingSnoopResp().
tryTiming()
template<unsigned int BITWIDTH> bool sc_gem5::Gem5ToTlmBridge< BITWIDTH >::tryTiming (PacketPtr packet) protected
Definition at line 384 of file gem5_to_tlm.cc.
References panic.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::BridgeSlavePort::tryTiming().
Member Data Documentation
addrRanges
template<unsigned int BITWIDTH> AddrRangeList sc_gem5::Gem5ToTlmBridge< BITWIDTH >::addrRanges private
Definition at line 167 of file gem5_to_tlm.hh.
backdoorMap
template<unsigned int BITWIDTH> AddrRangeMap<MemBackdoorPtr> sc_gem5::Gem5ToTlmBridge< BITWIDTH >::backdoorMap protected
Definition at line 174 of file gem5_to_tlm.hh.
blockingRequest
template<unsigned int BITWIDTH> tlm::tlm_generic_payload* sc_gem5::Gem5ToTlmBridge< BITWIDTH >::blockingRequest private
A transaction after BEGIN_REQ has been sent but before END_REQ, which is blocking the request channel (Exlusion Rule, see IEEE1666)
Definition at line 153 of file gem5_to_tlm.hh.
blockingResponse
template<unsigned int BITWIDTH> tlm::tlm_generic_payload* sc_gem5::Gem5ToTlmBridge< BITWIDTH >::blockingResponse private
A response which has been asked to retry by gem5 and so is blocking the response channel.
Definition at line 165 of file gem5_to_tlm.hh.
bsp
template<unsigned int BITWIDTH> BridgeSlavePort sc_gem5::Gem5ToTlmBridge< BITWIDTH >::bsp private
Definition at line 142 of file gem5_to_tlm.hh.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration(), and sc_gem5::Gem5ToTlmBridge< BITWIDTH >::gem5_getPort().
needToSendRequestRetry
template<unsigned int BITWIDTH> bool sc_gem5::Gem5ToTlmBridge< BITWIDTH >::needToSendRequestRetry private
Did another gem5 request arrive while currently blocked? This variable is needed when a retry should happen.
Definition at line 159 of file gem5_to_tlm.hh.
socket
template<unsigned int BITWIDTH> tlm_utils::simple_initiator_socket< Gem5ToTlmBridge<BITWIDTH>, BITWIDTH> sc_gem5::Gem5ToTlmBridge< BITWIDTH >::socket private
Definition at line 144 of file gem5_to_tlm.hh.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::before_end_of_elaboration().
system
template<unsigned int BITWIDTH> System* sc_gem5::Gem5ToTlmBridge< BITWIDTH >::system private
Definition at line 147 of file gem5_to_tlm.hh.
wrapper
template<unsigned int BITWIDTH> sc_gem5::TlmInitiatorWrapper<BITWIDTH> sc_gem5::Gem5ToTlmBridge< BITWIDTH >::wrapper private
Definition at line 145 of file gem5_to_tlm.hh.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::gem5_getPort().
The documentation for this class was generated from the following files:
systemc/tlm_bridge/gem5_to_tlm.hh
systemc/tlm_bridge/gem5_to_tlm.cc