gem5: Serializable Class Reference
Serializable Class Reference abstract
Basic support for object serialization.
#include <serialize.hh>
Classes
class ScopedCheckpointSection
Scoped checkpoint section helper class.
Public Member Functions
Serializable ()
virtual ~Serializable ()
virtual void serialize (CheckpointOut &cp) const =0
Serialize an object.
virtual void unserialize (CheckpointIn &cp)=0
Unserialize an object.
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Static Public Member Functions
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Static Private Attributes
static std::stack< std::string > path
Detailed Description
Basic support for object serialization.
Objects that support serialization should derive from this class. Such objects can largely be divided into two categories: 1) True SimObjects (deriving from SimObject), and 2) child objects (non-SimObjects).
SimObjects are serialized automatically into their own sections automatically by the SimObject base class (see SimObject::serializeAll().
SimObjects can contain other serializable objects that are not SimObjects. Much like normal serialized members are not serialized automatically, these objects will not be serialized automatically and it is expected that the objects owning such serializable objects call the required serialization/unserialization methods on child objects. The preferred method to serialize a child object is to call serializeSection() on the child, which serializes the object into a new subsection in the current section. Another option is to call serialize() directly, which serializes the object into the current section. The latter is not recommended as it can lead to naming clashes between objects.
Note
Many objects that support serialization need to be put in a consistent state when serialization takes place. We refer to the action of forcing an object into a consistent state as 'draining'. Objects that need draining inherit from Drainable. See Drainable for more information.
Definition at line 153 of file serialize.hh.
Constructor & Destructor Documentation
Serializable()
Serializable::Serializable ()
Definition at line 167 of file serialize.cc.
~Serializable()
Serializable::~Serializable () virtual
Definition at line 171 of file serialize.cc.
Member Function Documentation
currentSection()
const std::string & Serializable::currentSection () static
Get the fully-qualified name of the active section.
Definition at line 244 of file serialize.cc.
References CheckpointIn::baseFilename, and CheckpointIn::currentDirectory.
Referenced by arrayParamIn(), ArmSemihosting::FileBase::create(), Serializable::ScopedCheckpointSection::nameOut(), objParamIn(), optParamIn(), paramIn(), Globals::unserialize(), HDLcd::unserialize(), and GicV2::unserialize().
serialize()
virtual void Serializable::serialize (CheckpointOut & cp) const pure virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implemented in BaseCache, iGbReg::Regs, ArmISA::ISA, DistIface, System, VirtIODeviceBase, IGbE, IGbE::TxDescCache, GicV2, GenericISA::DelaySlotUPCState< MachInst >, DistIface::RecvScheduler, ArmISA::PMU::CounterState, Event, BaseCPU, IGbE::RxDescCache, ArmISA::TLB, HDLcd::DmaEngine, Pl111, IdeDisk, NSGigE, DistIface::RecvScheduler::Desc, GenericISA::DelaySlotPCState< MachInst >, DmaReadFifo, X86ISA::PCState, IGbE::DescCache< T >, IGbE::DescCache< iGbReg::TxDesc >, IGbE::DescCache< iGbReg::RxDesc >, Gicv3CPUInterface, GenericTimerMem, VirtQueue, ArmISA::TlbEntry, Sinic::Device, X86ISA::Interrupts, DistIface::SyncSwitch, MultiLevelPageTable< EntryTypes >, ArmISA::Interrupts, BasePixelPump::PixelEvent, GenericISA::UPCState< MachInst >, SparcISA::Interrupts, BaseTrafficGen, ClockedObject, PhysicalMemory, SrcClockDomain, X86ISA::GpuTLB, DistIface::SyncNode, Gicv3Distributor, DistEtherLink, ArmSemihosting::File, PciDevice, GenericTimer, Gicv3Redistributor, VirtIO9PProxy, DeviceFDEntry, SimObject, ArmSemihosting::FileFeatures, RealViewOsc, VGic, CopyEngine, GicV2::BankedRegs, DistIface::Sync, CopyEngineReg::ChanRegs, EtherSwitch, CpuLocalTimer, SMMUv3, SparcISA::TLB, RealViewCtrl, PipeFDEntry, ArchTimer, UFSHostDevice, TickedObject, CheckerCPU, DVFSHandler, PowerISA::TLB, A9GlobalTimer, SparcISA::ISA, EtherSwitch::Interface::PortFifo, ThermalModel, SimpleThread, Sp804, EmulationPageTable, IdeController, EtherLink, X86ISA::TLB, BasePixelPump, Gicv3Its, EtherTapStub, I2CBus, MinorCPU, CpuLocalTimer::Timer, X86ISA::I8042, AlphaISA::TlbEntry, Iob, Ticked, TsunamiIO, FileFDEntry, X86ISA::ISA, A9GlobalTimer::Timer, Pl050, MaltaCChip, CowDiskImage, RiscvISA::Interrupts, EnergyCtrl, TrafficGen, TsunamiCChip, MaltaIO, ArmSemihosting::FileBase, Malta, ThermalReference, VoltageDomain, PL031, CopyEngineReg::Regs, X86ISA::I8259, Gicv3, AlphaISA::Interrupts, Sp804::Timer, X86ISA::I8254, O3ThreadState< Impl >, AlphaBackdoor, AlphaISA::TLB, GenericISA::PCStateBase, X86ISA::TlbEntry, EtherSwitch::Interface::PortFifoEntry, X86ISA::I82094AA, MipsISA::Interrupts, CopyEngine::CopyEngineChannel, MipsISA::TLB, Root, RiscvISA::TLB, ArmISA::PMU, Random, Uart8250, GpuDispatcher, SystemCounter, HDLcd, X86ISA::Cmos, ThermalDomain, DistEtherLink::Link, AlphaISA::Kernel::Statistics, ThermalCapacitor, AlphaISA::ISA, LocalSimLoopExitEvent, MemState, EtherSwitch::Interface, Tsunami, Globals, RubySystem, FrameBuffer, ArmSemihosting, AlphaBackdoor::Access, TsunamiPChip, X86ISA::Speaker, Sinic::Base, EtherTapBase, Process, PS2Mouse, FlashDevice, ThermalResistor, ThreadState, DisplayTimings, DumbTOD, PS2TouchKit, PS2Keyboard, MmDisk, FDEntry, PollEvent, Pl011, Kernel::Statistics, X86ISA::I8237, NoMaliGpu, and PS2Device.
serializeAll()
void Serializable::serializeAll (const std::string & cpt_dir) static
Definition at line 190 of file serialize.cc.
References CheckpointIn::baseFilename, fatal, SimObject::serializeAll(), serializeSection(), CheckpointIn::setDir(), and ArmISA::t.
Referenced by debug_serialize(), and pybind_init_core().
serializeSection() [1/2]
void Serializable::serializeSection (CheckpointOut & cp, const char * name) const
Serialize an object into a new section.
This method creates a new section in a checkpoint and calls serialize() to serialize the current object into that section. The name of the section is appended to the current checkpoint path.
Parameters
cp Checkpoint state
name Name to append to the active path
Definition at line 176 of file serialize.cc.
References serialize().
Referenced by EtherSwitch::Interface::serialize(), ArmISA::PMU::serialize(), AlphaISA::TLB::serialize(), Gicv3::serialize(), Sp804::serialize(), CpuLocalTimer::serialize(), CopyEngine::serialize(), VGic::serialize(), GenericTimer::serialize(), DistEtherLink::serialize(), GenericTimerMem::serialize(), ArmISA::TLB::serialize(), IGbE::serialize(), VirtIODeviceBase::serialize(), System::serialize(), DistIface::serialize(), SimObject::serializeAll(), and serializeAll().
serializeSection() [2/2]
void Serializable::serializeSection (CheckpointOut & cp, const std::string & name) const inline
Definition at line 237 of file serialize.hh.
unserialize()
virtual void Serializable::unserialize (CheckpointIn & cp) pure virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implemented in BaseCache, iGbReg::Regs, ArmISA::ISA, DistIface, System, VirtIODeviceBase, IGbE, IGbE::TxDescCache, GicV2, GenericISA::DelaySlotUPCState< MachInst >, DistIface::RecvScheduler, ArmISA::PMU::CounterState, BaseCPU, Event, IGbE::RxDescCache, ArmISA::TLB, HDLcd::DmaEngine, Pl111, IdeDisk, GenericISA::DelaySlotPCState< MachInst >, NSGigE, DistIface::RecvScheduler::Desc, X86ISA::PCState, DmaReadFifo, IGbE::DescCache< T >, IGbE::DescCache< iGbReg::TxDesc >, IGbE::DescCache< iGbReg::RxDesc >, Gicv3CPUInterface, ArmISA::TlbEntry, GenericTimerMem, VirtQueue, Sinic::Device, X86ISA::Interrupts, MultiLevelPageTable< EntryTypes >, DistIface::SyncSwitch, ArmISA::Interrupts, GenericISA::UPCState< MachInst >, BasePixelPump::PixelEvent, SparcISA::Interrupts, PhysicalMemory, BaseTrafficGen, ClockedObject, SrcClockDomain, X86ISA::GpuTLB, DistIface::SyncNode, Gicv3Distributor, DistEtherLink, PciDevice, ArmSemihosting::File, GenericTimer, Gicv3Redistributor, VirtIO9PProxy, DeviceFDEntry, SimObject, ArmSemihosting::FileFeatures, RealViewOsc, CopyEngineReg::ChanRegs, VGic, CopyEngine, GicV2::BankedRegs, DistIface::Sync, EtherSwitch, CpuLocalTimer, SMMUv3, SparcISA::TLB, RealViewCtrl, PipeFDEntry, ArchTimer, UFSHostDevice, TickedObject, CheckerCPU, DVFSHandler, PowerISA::TLB, A9GlobalTimer, SparcISA::ISA, EtherSwitch::Interface::PortFifo, ThermalModel, SimpleThread, Sp804, EmulationPageTable, IdeController, EtherLink, X86ISA::TLB, BasePixelPump, Gicv3Its, EtherTapStub, I2CBus, MinorCPU, CpuLocalTimer::Timer, X86ISA::I8042, AlphaISA::TlbEntry, Iob, RiscvISA::Interrupts, Ticked, TsunamiIO, FileFDEntry, X86ISA::ISA, A9GlobalTimer::Timer, Pl050, MaltaCChip, CowDiskImage, EnergyCtrl, CopyEngineReg::Regs, TrafficGen, TsunamiCChip, MaltaIO, ArmSemihosting::FileBase, Malta, ThermalReference, AlphaISA::Interrupts, O3ThreadState< Impl >, VoltageDomain, PL031, X86ISA::I8259, Gicv3, GenericISA::PCStateBase, Sp804::Timer, X86ISA::I8254, AlphaBackdoor, AlphaISA::TLB, MipsISA::Interrupts, X86ISA::TlbEntry, EtherSwitch::Interface::PortFifoEntry, X86ISA::I82094AA, CopyEngine::CopyEngineChannel, MipsISA::TLB, RiscvISA::TLB, ArmISA::PMU, Random, Uart8250, GpuDispatcher, SystemCounter, MemState, HDLcd, X86ISA::Cmos, ThermalDomain, DistEtherLink::Link, AlphaISA::Kernel::Statistics, ThermalCapacitor, AlphaISA::ISA, LocalSimLoopExitEvent, EtherSwitch::Interface, Tsunami, Globals, RubySystem, FrameBuffer, ArmSemihosting, AlphaBackdoor::Access, TsunamiPChip, X86ISA::Speaker, Sinic::Base, EtherTapBase, Process, PS2Mouse, FlashDevice, ThreadState, ThermalResistor, DisplayTimings, DumbTOD, PS2TouchKit, PS2Keyboard, FDEntry, PollEvent, Pl011, Kernel::Statistics, X86ISA::I8237, NoMaliGpu, PS2Device, and AlphaProcess.
unserializeGlobals()
void Serializable::unserializeGlobals (CheckpointIn & cp) static
Definition at line 209 of file serialize.cc.
References ArmISA::i, mainEventQueue, numMainEventQueues, Globals::unserializedCurTick, and unserializeSection().
Referenced by pybind_init_core().
unserializeSection() [1/2]
void Serializable::unserializeSection (CheckpointIn & cp, const char * name)
Unserialize an a child object.
This method loads a child object from a checkpoint. The object name is appended to the active path to form a fully qualified section name and unserialize() is called.
Parameters
cp Checkpoint state
name Name to append to the active path
Definition at line 183 of file serialize.cc.
References unserialize().
Referenced by SimObject::loadState(), EtherSwitch::Interface::unserialize(), ArmISA::PMU::unserialize(), Gicv3::unserialize(), X86ISA::TLB::unserialize(), Sp804::unserialize(), EtherSwitch::Interface::PortFifo::unserialize(), CpuLocalTimer::unserialize(), CopyEngine::unserialize(), GenericTimer::unserialize(), DistEtherLink::unserialize(), GenericTimerMem::unserialize(), ArmISA::TLB::unserialize(), DistIface::RecvScheduler::unserialize(), IGbE::unserialize(), VirtIODeviceBase::unserialize(), System::unserialize(), DistIface::unserialize(), and unserializeGlobals().
unserializeSection() [2/2]
void Serializable::unserializeSection (CheckpointIn & cp, const std::string & name) inline
Definition at line 253 of file serialize.hh.
Member Data Documentation
ckptCount
int Serializable::ckptCount = 0 static
Definition at line 260 of file serialize.hh.
ckptMaxCount
int Serializable::ckptMaxCount = 0 static
Definition at line 261 of file serialize.hh.
ckptPrevCount
int Serializable::ckptPrevCount = -1 static
Definition at line 262 of file serialize.hh.
path
std::stack< std::string > Serializable::path static private
Definition at line 267 of file serialize.hh.
Referenced by Process::checkPathRedirect(), Iris::CPU< ArmThreadContext >::CPU(), MathExprPowerModel::MathExprPowerModel(), ArmSemihosting::readString(), FastModel::CortexA76::set_evs_param(), MPP_TAGE::updatePathAndGlobalHistory(), and TAGE_SC_L_TAGE::updatePathAndGlobalHistory().
The documentation for this class was generated from the following files:
sim/serialize.hh
sim/serialize.cc