gem5: sc_dt::sc_unsigned_bitref Class Reference
sc_dt::sc_unsigned_bitref Class Reference
#include <sc_unsigned.hh>
Public Member Functions
sc_unsigned_bitref (const sc_unsigned_bitref &a)
const sc_unsigned_bitref & operator= (const sc_unsigned_bitref_r &)
const sc_unsigned_bitref & operator= (const sc_unsigned_bitref &)
const sc_unsigned_bitref & operator= (bool)
const sc_unsigned_bitref & operator&= (bool)
const sc_unsigned_bitref & operator|= (bool)
const sc_unsigned_bitref & operator^= (bool)
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_unsigned_bitref_r
virtual ~sc_unsigned_bitref_r ()
sc_unsigned_bitref_r (const sc_unsigned_bitref_r &a)
int length () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
virtual int concat_length (bool *xz_present_p) const
virtual uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_unsigned_bitref ()
Protected Member Functions inherited from sc_dt::sc_unsigned_bitref_r
sc_unsigned_bitref_r ()
void initialize (const sc_unsigned *obj_p, int index_)
Static Protected Attributes
static sc_core::sc_vpool< sc_unsigned_bitref > m_pool
Friends
class sc_unsigned
class sc_core::sc_vpool< sc_unsigned_bitref >
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_unsigned_bitref_r
int m_index
sc_unsigned * m_obj_p
Detailed Description
Definition at line 677 of file sc_unsigned.hh.
Constructor & Destructor Documentation
sc_unsigned_bitref() [1/2]
sc_dt::sc_unsigned_bitref::sc_unsigned_bitref () inline protected
Definition at line 683 of file sc_unsigned.hh.
sc_unsigned_bitref() [2/2]
sc_dt::sc_unsigned_bitref::sc_unsigned_bitref (const sc_unsigned_bitref & a) inline
Definition at line 687 of file sc_unsigned.hh.
References MipsISA::is, sc_dt::operator&=(), sc_dt::operator^=(), and sc_dt::operator|=().
Member Function Documentation
concat_set() [1/4]
void sc_dt::sc_unsigned_bitref::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 125 of file sc_unsigned.cc.
concat_set() [2/4]
void sc_dt::sc_unsigned_bitref::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 132 of file sc_unsigned.cc.
concat_set() [3/4]
void sc_dt::sc_unsigned_bitref::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 141 of file sc_unsigned.cc.
concat_set() [4/4]
void sc_dt::sc_unsigned_bitref::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 150 of file sc_unsigned.cc.
operator&=()
const sc_unsigned_bitref& sc_dt::sc_unsigned_bitref::operator &= (bool)
operator=() [1/3]
const sc_unsigned_bitref & sc_dt::sc_unsigned_bitref::operator= (const sc_unsigned_bitref_r & b)
Definition at line 75 of file sc_unsigned.cc.
operator=() [2/3]
const sc_unsigned_bitref & sc_dt::sc_unsigned_bitref::operator= (const sc_unsigned_bitref & b)
Definition at line 82 of file sc_unsigned.cc.
operator=() [3/3]
const sc_unsigned_bitref & sc_dt::sc_unsigned_bitref::operator= (bool b)
Definition at line 89 of file sc_unsigned.cc.
operator^=()
const sc_unsigned_bitref & sc_dt::sc_unsigned_bitref::operator^= (bool b)
Definition at line 115 of file sc_unsigned.cc.
operator|=()
const sc_unsigned_bitref & sc_dt::sc_unsigned_bitref::operator|= (bool b)
Definition at line 106 of file sc_unsigned.cc.
scan()
void sc_dt::sc_unsigned_bitref::scan (::std::istream & is = ::std::cin)
Definition at line 158 of file sc_unsigned.cc.
Referenced by sc_dt::operator>>().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_unsigned_bitref >
friend class sc_core::sc_vpool< sc_unsigned_bitref > friend
Definition at line 680 of file sc_unsigned.hh.
sc_unsigned
friend class sc_unsigned friend
Definition at line 679 of file sc_unsigned.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_unsigned_bitref > sc_dt::sc_unsigned_bitref::m_pool static protected
Definition at line 709 of file sc_unsigned.hh.
Referenced by sc_dt::sc_unsigned::bit(), and sc_dt::sc_unsigned::operator[]().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_unsigned.hh
systemc/dt/int/sc_unsigned.cc