gem5: Gicv2m Class Reference
Gicv2m Class Reference
#include <gic_v2m.hh>
Public Types
typedef Gicv2mParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Gicv2m (const Params *p)
virtual AddrRangeList getAddrRanges () const
Return the address ranges used by the Gicv2m This is the set of frame addresses.
virtual Tick read (PacketPtr pkt)
A PIO read to the device.
virtual Tick write (PacketPtr pkt)
A PIO read to the device.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Member Functions
int frameFromAddr (Addr a) const
Determine which frame a PIO access lands in.
Private Attributes
const Tick pioDelay
Latency for an MMIO operation.
std::vector< Gicv2mFrame * > frames
A set of configured hardware frames.
BaseGic * gic
Gic to which we fire interrupts.
unsigned int log2framenum
Count of number of configured frames, as log2(frames)
Static Private Attributes
static const int FRAME_SIZE = 0x10000
static const int MSI_TYPER = 0x0008
static const int MSI_SETSPI_NSR = 0x0040
static const int PER_ID4 = 0x0fd0
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 75 of file gic_v2m.hh.
Member Typedef Documentation
Params
typedef Gicv2mParams Gicv2m::Params
Definition at line 97 of file gic_v2m.hh.
Constructor & Destructor Documentation
Gicv2m()
Gicv2m::Gicv2m (const Params * p)
Definition at line 81 of file gic_v2m.cc.
References fatal, fatal_if, floorLog2(), frames, ArmISA::i, isPowerOf2(), log2framenum, and X86ISA::x.
Member Function Documentation
frameFromAddr()
int Gicv2m::frameFromAddr (Addr a) const private
Determine which frame a PIO access lands in.
Definition at line 163 of file gic_v2m.cc.
References addr, FRAME_SIZE, frames, and ArmISA::i.
Referenced by read(), and write().
getAddrRanges()
AddrRangeList Gicv2m::getAddrRanges () const virtual
Return the address ranges used by the Gicv2m This is the set of frame addresses.
Implements PioDevice.
Definition at line 97 of file gic_v2m.cc.
References addr, FRAME_SIZE, frames, ArmISA::i, and RangeSize().
read()
Tick Gicv2m::read (PacketPtr pkt) virtual
A PIO read to the device.
Implements PioDevice.
Definition at line 107 of file gic_v2m.cc.
References DPRINTF, frameFromAddr(), frames, Packet::getAddr(), log2framenum, Packet::makeAtomicResponse(), MSI_TYPER, ArmISA::offset, PER_ID4, pioDelay, and Packet::setLE().
write()
Tick Gicv2m::write (PacketPtr pkt) virtual
A PIO read to the device.
Implements PioDevice.
Definition at line 137 of file gic_v2m.cc.
References DPRINTF, frameFromAddr(), frames, Packet::getAddr(), Packet::getLE(), gic, ArmISA::m, Packet::makeAtomicResponse(), MSI_SETSPI_NSR, ArmISA::offset, pioDelay, and BaseGic::sendInt().
Member Data Documentation
FRAME_SIZE
const int Gicv2m::FRAME_SIZE = 0x10000 static private
Definition at line 78 of file gic_v2m.hh.
Referenced by frameFromAddr(), and getAddrRanges().
frames
std::vector<Gicv2mFrame *> Gicv2m::frames private
A set of configured hardware frames.
Definition at line 88 of file gic_v2m.hh.
Referenced by frameFromAddr(), getAddrRanges(), Gicv2m(), read(), and write().
gic
BaseGic* Gicv2m::gic private
Gic to which we fire interrupts.
Definition at line 91 of file gic_v2m.hh.
Referenced by write().
log2framenum
unsigned int Gicv2m::log2framenum private
Count of number of configured frames, as log2(frames)
Definition at line 94 of file gic_v2m.hh.
Referenced by Gicv2m(), and read().
MSI_SETSPI_NSR
const int Gicv2m::MSI_SETSPI_NSR = 0x0040 static private
Definition at line 81 of file gic_v2m.hh.
Referenced by write().
MSI_TYPER
const int Gicv2m::MSI_TYPER = 0x0008 static private
Definition at line 80 of file gic_v2m.hh.
Referenced by read().
PER_ID4
const int Gicv2m::PER_ID4 = 0x0fd0 static private
Definition at line 82 of file gic_v2m.hh.
Referenced by read().
pioDelay
const Tick Gicv2m::pioDelay private
Latency for an MMIO operation.
Definition at line 85 of file gic_v2m.hh.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
dev/arm/gic_v2m.hh
dev/arm/gic_v2m.cc