gem5: sc_core::sc_report Class Reference
sc_core::sc_report Class Reference
#include <sc_report.hh>
Public Member Functions
sc_report (const sc_report &)
sc_report & operator= (const sc_report &)
virtual ~sc_report () throw ()
sc_severity get_severity () const
const char * get_msg_type () const
const char * get_msg () const
int get_verbosity () const
const char * get_file_name () const
int get_line_number () const
const sc_time & get_time () const
const char * get_process_name () const
virtual const char * what () const throw ()
int get_id () const
Static Public Member Functions
static const char * get_message (int id)
static bool is_suppressed (int id)
static void make_warnings_errors (bool)
static void register_id (int id, const char *msg)
static void suppress_id (int id, bool)
static void suppress_infos (bool)
static void suppress_warnings (bool)
Private Member Functions
sc_report (sc_severity _severity, const char *_msgType, const char *_msg, int _verbosity, const char *_fileName, int _lineNumber, sc_time _time, const char *_processName, int _id)
Private Attributes
sc_severity _severity
const char * _msgType
const char * _msg
int _verbosity
const char * _fileName
int _lineNumber
sc_time _time
const char * _processName
int _id
std::string _what
Friends
class sc_report_handler
Detailed Description
Definition at line 62 of file sc_report.hh.
Constructor & Destructor Documentation
sc_report() [1/2]
sc_core::sc_report::sc_report (const sc_report & r)
Definition at line 55 of file sc_report.cc.
~sc_report()
sc_core::sc_report::~sc_report () throw () virtual
Definition at line 77 of file sc_report.cc.
References _msg, and _msgType.
sc_report() [2/2]
sc_core::sc_report::sc_report (sc_severity _severity, const char * _msgType, const char * _msg, int _verbosity, const char * _fileName, int _lineNumber, sc_time _time, const char * _processName, int _id) private
Definition at line 41 of file sc_report.cc.
References _msg, _msgType, _what, and sc_core::sc_report_compose_message().
Member Function Documentation
get_file_name()
const char* sc_core::sc_report::get_file_name () const inline
Definition at line 73 of file sc_report.hh.
References _fileName.
Referenced by sc_core::sc_report_compose_message().
get_id()
int sc_core::sc_report::get_id () const inline
Definition at line 89 of file sc_report.hh.
References _id.
Referenced by sc_core::sc_report_compose_message().
get_line_number()
int sc_core::sc_report::get_line_number () const inline
Definition at line 74 of file sc_report.hh.
References _lineNumber.
Referenced by sc_core::sc_report_compose_message().
get_message()
const char * sc_core::sc_report::get_message (int id) static
Definition at line 90 of file sc_report.cc.
References sc_gem5::reportIdToMsgMap().
Referenced by get_process_name().
get_msg()
const char* sc_core::sc_report::get_msg () const inline
Definition at line 71 of file sc_report.hh.
References _msg.
Referenced by sc_core::sc_report_compose_message().
get_msg_type()
const char* sc_core::sc_report::get_msg_type () const inline
Definition at line 70 of file sc_report.hh.
References _msgType.
Referenced by sc_core::sc_report_handler::default_handler(), and sc_core::sc_report_compose_message().
get_process_name()
const char* sc_core::sc_report::get_process_name () const inline
Definition at line 77 of file sc_report.hh.
References _processName, get_message(), is_suppressed(), make_warnings_errors(), register_id(), suppress_id(), suppress_infos(), suppress_warnings(), and what().
Referenced by sc_core::sc_report_compose_message().
get_severity()
sc_severity sc_core::sc_report::get_severity () const inline
Definition at line 69 of file sc_report.hh.
References _severity.
Referenced by sc_core::sc_report_handler::default_handler(), and sc_core::sc_report_compose_message().
get_time()
const sc_time& sc_core::sc_report::get_time () const inline
Definition at line 76 of file sc_report.hh.
References _time.
Referenced by sc_core::sc_report_handler::default_handler(), and sc_core::sc_report_compose_message().
get_verbosity()
int sc_core::sc_report::get_verbosity () const inline
Definition at line 72 of file sc_report.hh.
References _verbosity.
is_suppressed()
bool sc_core::sc_report::is_suppressed (int id) static
Definition at line 100 of file sc_report.cc.
References sc_gem5::reportIdToMsgMap(), sc_gem5::reportMsgInfoMap(), sc_core::SC_DO_NOTHING, sc_core::SC_INFO, and sc_core::SC_WARNING.
Referenced by get_process_name().
make_warnings_errors()
void sc_core::sc_report::make_warnings_errors (bool val) static
Definition at line 114 of file sc_report.cc.
References sc_gem5::reportWarningsAsErrors, and X86ISA::val.
Referenced by get_process_name().
operator=()
sc_report & sc_core::sc_report::operator= (const sc_report & r)
Definition at line 61 of file sc_report.cc.
References _fileName, _id, _lineNumber, _msg, _msgType, _processName, _severity, _time, and _verbosity.
register_id()
void sc_core::sc_report::register_id (int id, const char * msg) static
Definition at line 120 of file sc_report.cc.
References ArmISA::id, MipsISA::p, sc_gem5::reportIdToMsgMap(), sc_gem5::reportMsgInfoMap(), sc_core::SC_ID_REGISTER_ID_FAILED_, and SC_REPORT_ERROR.
Referenced by sc_gem5::DefaultReportMessages::DefaultReportMessages(), and get_process_name().
suppress_id()
void sc_core::sc_report::suppress_id (int id, bool suppress) static
Definition at line 140 of file sc_report.cc.
References sc_gem5::reportIdToMsgMap(), sc_gem5::reportMsgInfoMap(), sc_core::SC_DO_NOTHING, sc_core::SC_INFO, sc_core::SC_UNSPECIFIED, and sc_core::SC_WARNING.
Referenced by get_process_name().
suppress_infos()
void sc_core::sc_report::suppress_infos (bool suppress) static
Definition at line 160 of file sc_report.cc.
References sc_gem5::ReportSevInfo::actions, sc_gem5::reportSevInfos, sc_core::SC_DEFAULT_INFO_ACTIONS, sc_core::SC_DO_NOTHING, and sc_core::SC_INFO.
Referenced by get_process_name().
suppress_warnings()
void sc_core::sc_report::suppress_warnings (bool suppress) static
Definition at line 169 of file sc_report.cc.
References sc_gem5::ReportSevInfo::actions, sc_gem5::reportSevInfos, sc_core::SC_DEFAULT_WARNING_ACTIONS, sc_core::SC_DO_NOTHING, and sc_core::SC_WARNING.
Referenced by get_process_name().
what()
const char * sc_core::sc_report::what () const throw () virtual
Definition at line 84 of file sc_report.cc.
References _what.
Referenced by get_process_name().
Friends And Related Function Documentation
sc_report_handler
friend class sc_report_handler friend
Definition at line 92 of file sc_report.hh.
Member Data Documentation
_fileName
const char* sc_core::sc_report::_fileName private
Definition at line 108 of file sc_report.hh.
Referenced by get_file_name(), and operator=().
_id
int sc_core::sc_report::_id private
Definition at line 112 of file sc_report.hh.
Referenced by get_id(), and operator=().
_lineNumber
int sc_core::sc_report::_lineNumber private
Definition at line 109 of file sc_report.hh.
Referenced by get_line_number(), and operator=().
_msg
const char* sc_core::sc_report::_msg private
Definition at line 106 of file sc_report.hh.
Referenced by get_msg(), operator=(), sc_report(), and ~sc_report().
_msgType
const char* sc_core::sc_report::_msgType private
Definition at line 105 of file sc_report.hh.
Referenced by get_msg_type(), operator=(), sc_report(), and ~sc_report().
_processName
const char* sc_core::sc_report::_processName private
Definition at line 111 of file sc_report.hh.
Referenced by get_process_name(), and operator=().
_severity
sc_severity sc_core::sc_report::_severity private
Definition at line 104 of file sc_report.hh.
Referenced by get_severity(), and operator=().
_time
sc_time sc_core::sc_report::_time private
Definition at line 110 of file sc_report.hh.
Referenced by get_time(), and operator=().
_verbosity
int sc_core::sc_report::_verbosity private
Definition at line 107 of file sc_report.hh.
Referenced by get_verbosity(), and operator=().
_what
std::string sc_core::sc_report::_what private
Definition at line 113 of file sc_report.hh.
Referenced by sc_report(), and what().
The documentation for this class was generated from the following files:
systemc/ext/utils/sc_report.hh
systemc/utils/sc_report.cc