gem5: sc_dt::sc_lv< W > Class Template Reference
sc_dt::sc_lv< W > Class Template Reference
#include <sc_in_rv.hh>
Public Member Functions
sc_lv ()
sc_lv (const sc_logic &init_value)
sc_lv (bool init_value)
sc_lv (char init_value)
sc_lv (const char *a)
sc_lv (const bool *a)
sc_lv (const sc_logic *a)
sc_lv (const sc_unsigned &a)
sc_lv (const sc_signed &a)
sc_lv (const sc_uint_base &a)
sc_lv (const sc_int_base &a)
sc_lv (unsigned long a)
sc_lv (long a)
sc_lv (unsigned int a)
sc_lv (int a)
sc_lv (uint64 a)
sc_lv (int64 a)
template<class X >
sc_lv (const sc_proxy< X > &a)
sc_lv (const sc_lv< W > &a)
template<class X >
sc_lv< W > & operator= (const sc_proxy< X > &a)
sc_lv< W > & operator= (const sc_lv< W > &a)
sc_lv< W > & operator= (const char *a)
sc_lv< W > & operator= (const bool *a)
sc_lv< W > & operator= (const sc_logic *a)
sc_lv< W > & operator= (const sc_unsigned &a)
sc_lv< W > & operator= (const sc_signed &a)
sc_lv< W > & operator= (const sc_uint_base &a)
sc_lv< W > & operator= (const sc_int_base &a)
sc_lv< W > & operator= (unsigned long a)
sc_lv< W > & operator= (long a)
sc_lv< W > & operator= (unsigned int a)
sc_lv< W > & operator= (int a)
sc_lv< W > & operator= (uint64 a)
sc_lv< W > & operator= (int64 a)
Public Member Functions inherited from sc_dt::sc_lv_base
sc_lv_base (int length_=sc_length_param().len())
sc_lv_base (const sc_logic &a, int length_=sc_length_param().len())
sc_lv_base (const char *a)
sc_lv_base (const char *a, int length_)
template<class X >
sc_lv_base (const sc_proxy< X > &a)
sc_lv_base (const sc_lv_base &a)
virtual ~sc_lv_base ()
template<class X >
sc_lv_base & operator= (const sc_proxy< X > &a)
sc_lv_base & operator= (const sc_lv_base &a)
sc_lv_base & operator= (const char *a)
sc_lv_base & operator= (const bool *a)
sc_lv_base & operator= (const sc_logic *a)
sc_lv_base & operator= (const sc_unsigned &a)
sc_lv_base & operator= (const sc_signed &a)
sc_lv_base & operator= (const sc_uint_base &a)
sc_lv_base & operator= (const sc_int_base &a)
sc_lv_base & operator= (unsigned long a)
sc_lv_base & operator= (long a)
sc_lv_base & operator= (unsigned int a)
sc_lv_base & operator= (int a)
sc_lv_base & operator= (uint64 a)
sc_lv_base & operator= (int64 a)
int length () const
int size () const
value_type get_bit (int i) const
void set_bit (int i, value_type value)
sc_digit get_word (int wi) const
void set_word (int wi, sc_digit w)
sc_digit get_cword (int wi) const
void set_cword (int wi, sc_digit w)
void clean_tail ()
bool is_01 () const
Public Member Functions inherited from sc_dt::sc_proxy< sc_lv_base >
virtual ~sc_proxy ()
sc_lv_base & back_cast ()
const sc_lv_base & back_cast () const
sc_lv_base & assign_ (const sc_proxy< Y > &a)
sc_lv_base & assign_ (const char *a)
sc_lv_base & assign_ (const bool *a)
sc_lv_base & assign_ (const sc_logic *a)
sc_lv_base & assign_ (const sc_unsigned &a)
sc_lv_base & assign_ (const sc_signed &a)
sc_lv_base & assign_ (const sc_uint_base &a)
sc_lv_base & assign_ (const sc_int_base &a)
sc_lv_base & assign_ (unsigned int a)
sc_lv_base & assign_ (int a)
sc_lv_base & assign_ (unsigned long a)
sc_lv_base & assign_ (long a)
sc_lv_base & assign_ (uint64 a)
sc_lv_base & assign_ (int64 a)
sc_lv_base & b_not ()
const sc_lv_base operator~ () const
sc_lv_base & operator &= (const char *b)
sc_lv_base & operator &= (const bool *b)
sc_lv_base & operator &= (const sc_logic *b)
sc_lv_base & operator &= (const sc_unsigned &b)
sc_lv_base & operator &= (const sc_signed &b)
sc_lv_base & operator &= (const sc_uint_base &b)
sc_lv_base & operator &= (const sc_int_base &b)
sc_lv_base & operator &= (unsigned long b)
sc_lv_base & operator &= (long b)
sc_lv_base & operator &= (unsigned int b)
sc_lv_base & operator &= (int b)
sc_lv_base & operator &= (uint64 b)
sc_lv_base & operator &= (int64 b)
const sc_lv_base operator & (const char *b) const
const sc_lv_base operator & (const bool *b) const
const sc_lv_base operator & (const sc_logic *b) const
const sc_lv_base operator & (const sc_unsigned &b) const
const sc_lv_base operator & (const sc_signed &b) const
const sc_lv_base operator & (const sc_uint_base &b) const
const sc_lv_base operator & (const sc_int_base &b) const
const sc_lv_base operator & (unsigned long b) const
const sc_lv_base operator & (long b) const
const sc_lv_base operator & (unsigned int b) const
const sc_lv_base operator & (int b) const
const sc_lv_base operator & (uint64 b) const
const sc_lv_base operator & (int64 b) const
sc_lv_base & operator|= (const char *b)
sc_lv_base & operator|= (const bool *b)
sc_lv_base & operator|= (const sc_logic *b)
sc_lv_base & operator|= (const sc_unsigned &b)
sc_lv_base & operator|= (const sc_signed &b)
sc_lv_base & operator|= (const sc_uint_base &b)
sc_lv_base & operator|= (const sc_int_base &b)
sc_lv_base & operator|= (unsigned long b)
sc_lv_base & operator|= (long b)
sc_lv_base & operator|= (unsigned int b)
sc_lv_base & operator|= (int b)
sc_lv_base & operator|= (uint64 b)
sc_lv_base & operator|= (int64 b)
const sc_lv_base operator| (const char *b) const
const sc_lv_base operator| (const bool *b) const
const sc_lv_base operator| (const sc_logic *b) const
const sc_lv_base operator| (const sc_unsigned &b) const
const sc_lv_base operator| (const sc_signed &b) const
const sc_lv_base operator| (const sc_uint_base &b) const
const sc_lv_base operator| (const sc_int_base &b) const
const sc_lv_base operator| (unsigned long b) const
const sc_lv_base operator| (long b) const
const sc_lv_base operator| (unsigned int b) const
const sc_lv_base operator| (int b) const
const sc_lv_base operator| (uint64 b) const
const sc_lv_base operator| (int64 b) const
sc_lv_base & operator^= (const char *b)
sc_lv_base & operator^= (const bool *b)
sc_lv_base & operator^= (const sc_logic *b)
sc_lv_base & operator^= (const sc_unsigned &b)
sc_lv_base & operator^= (const sc_signed &b)
sc_lv_base & operator^= (const sc_uint_base &b)
sc_lv_base & operator^= (const sc_int_base &b)
sc_lv_base & operator^= (unsigned long b)
sc_lv_base & operator^= (long b)
sc_lv_base & operator^= (unsigned int b)
sc_lv_base & operator^= (int b)
sc_lv_base & operator^= (uint64 b)
sc_lv_base & operator^= (int64 b)
const sc_lv_base operator^ (const char *b) const
const sc_lv_base operator^ (const bool *b) const
const sc_lv_base operator^ (const sc_logic *b) const
const sc_lv_base operator^ (const sc_unsigned &b) const
const sc_lv_base operator^ (const sc_signed &b) const
const sc_lv_base operator^ (const sc_uint_base &b) const
const sc_lv_base operator^ (const sc_int_base &b) const
const sc_lv_base operator^ (unsigned long b) const
const sc_lv_base operator^ (long b) const
const sc_lv_base operator^ (unsigned int b) const
const sc_lv_base operator^ (int b) const
const sc_lv_base operator^ (uint64 b) const
const sc_lv_base operator^ (int64 b) const
sc_lv_base & operator<<= (int n)
const sc_lv_base operator<< (int n) const
sc_lv_base & operator>>= (int n)
const sc_lv_base operator>> (int n) const
sc_lv_base & lrotate (int n)
sc_lv_base & rrotate (int n)
sc_lv_base & reverse ()
sc_bitref< sc_lv_base > operator[] (int i)
sc_bitref_r< sc_lv_base > operator[] (int i) const
sc_bitref< sc_lv_base > bit (int i)
sc_bitref_r< sc_lv_base > bit (int i) const
sc_subref< sc_lv_base > operator() (int hi, int lo)
sc_subref_r< sc_lv_base > operator() (int hi, int lo) const
sc_subref< sc_lv_base > range (int hi, int lo)
sc_subref_r< sc_lv_base > range (int hi, int lo) const
value_type and_reduce () const
value_type nand_reduce () const
value_type or_reduce () const
value_type nor_reduce () const
value_type xor_reduce () const
value_type xnor_reduce () const
bool operator== (const char *b) const
bool operator== (const bool *b) const
bool operator== (const sc_logic *b) const
bool operator== (const sc_unsigned &b) const
bool operator== (const sc_signed &b) const
bool operator== (const sc_uint_base &b) const
bool operator== (const sc_int_base &b) const
bool operator== (unsigned long b) const
bool operator== (long b) const
bool operator== (unsigned int b) const
bool operator== (int b) const
bool operator== (uint64 b) const
bool operator== (int64 b) const
const std::string to_string () const
const std::string to_string (sc_numrep) const
const std::string to_string (sc_numrep, bool) const
int64 to_int64 () const
uint64 to_uint64 () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Additional Inherited Members
Public Types inherited from sc_dt::sc_lv_base
typedef sc_proxy< sc_lv_base > base_type
typedef base_type::value_type value_type
Public Types inherited from sc_dt::sc_proxy< sc_lv_base >
typedef sc_proxy_traits< sc_lv_base >::traits_type traits_type
typedef traits_type::bit_type bit_type
typedef traits_type::value_type value_type
Protected Member Functions inherited from sc_dt::sc_proxy< sc_lv_base >
void check_bounds (int n) const
void check_wbounds (int n) const
sc_digit to_anything_unsigned () const
int64 to_anything_signed () const
Protected Attributes inherited from sc_dt::sc_lv_base
int m_len
int m_size
sc_digit * m_data
sc_digit * m_ctrl
Detailed Description
template<int W>
class sc_dt::sc_lv< W >
Definition at line 43 of file sc_in_rv.hh.
Constructor & Destructor Documentation
sc_lv() [1/19]
template<int W> sc_dt::sc_lv< W >::sc_lv () inline
Definition at line 71 of file sc_lv.hh.
sc_lv() [2/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_logic & init_value) inline explicit
Definition at line 72 of file sc_lv.hh.
sc_lv() [3/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (bool init_value) inline explicit
Definition at line 73 of file sc_lv.hh.
sc_lv() [4/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (char init_value) inline explicit
Definition at line 74 of file sc_lv.hh.
sc_lv() [5/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const char * a) inline
Definition at line 75 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [6/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const bool * a) inline
Definition at line 76 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [7/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_logic * a) inline
Definition at line 77 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [8/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_unsigned & a) inline
Definition at line 78 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [9/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_signed & a) inline
Definition at line 79 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [10/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_uint_base & a) inline
Definition at line 80 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [11/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_int_base & a) inline
Definition at line 84 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [12/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (unsigned long a) inline
Definition at line 85 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [13/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (long a) inline
Definition at line 86 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [14/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (unsigned int a) inline
Definition at line 87 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [15/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (int a) inline
Definition at line 88 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [16/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (uint64 a) inline
Definition at line 89 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [17/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (int64 a) inline
Definition at line 90 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [18/19]
template<int W> template<class X > sc_dt::sc_lv< W >::sc_lv (const sc_proxy< X > & a) inline
Definition at line 92 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
sc_lv() [19/19]
template<int W> sc_dt::sc_lv< W >::sc_lv (const sc_lv< W > & a) inline
Definition at line 93 of file sc_lv.hh.
Member Function Documentation
operator=() [1/15]
template<int W> template<class X > sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_proxy< X > & a) inline
Definition at line 98 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [2/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_lv< W > & a) inline
Definition at line 105 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [3/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const char * a) inline
Definition at line 112 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [4/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const bool * a) inline
Definition at line 119 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [5/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_logic * a) inline
Definition at line 126 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [6/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_unsigned & a) inline
Definition at line 133 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [7/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_signed & a) inline
Definition at line 140 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [8/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_uint_base & a) inline
Definition at line 147 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [9/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (const sc_int_base & a) inline
Definition at line 154 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [10/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (unsigned long a) inline
Definition at line 161 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [11/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (long a) inline
Definition at line 168 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [12/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (unsigned int a) inline
Definition at line 175 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [13/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (int a) inline
Definition at line 182 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [14/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (uint64 a) inline
Definition at line 189 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
operator=() [15/15]
template<int W> sc_lv<W>& sc_dt::sc_lv< W >::operator= (int64 a) inline
Definition at line 196 of file sc_lv.hh.
References sc_dt::sc_lv_base::operator=().
The documentation for this class was generated from the following files:
systemc/ext/channel/sc_in_rv.hh
systemc/ext/dt/bit/sc_lv.hh