gem5: Printable Class Reference
Printable Class Reference abstract
Abstract base class for objects which support being printed to a stream for debugging.
#include <printable.hh>
Public Member Functions
Printable ()
virtual ~Printable ()
virtual void print (std::ostream &os, int verbosity=0, const std::string &prefix="") const =0
Detailed Description
Abstract base class for objects which support being printed to a stream for debugging.
Primarily used to support PrintReq in memory system.
Definition at line 44 of file printable.hh.
Constructor & Destructor Documentation
Printable()
Printable::Printable () inline
Definition at line 47 of file printable.hh.
~Printable()
virtual Printable::~Printable () inline virtual
Definition at line 48 of file printable.hh.
References X86ISA::os, and print().
Member Function Documentation
print()
virtual void Printable::print (std::ostream & os, int verbosity = 0, const std::string & prefix = "") const pure virtual
Implemented in Packet, MSHR, CacheBlkPrintWrapper, Trace::TarmacTracerRecord::TraceMemEntry, WriteQueueEntry, Trace::TarmacTracerRecord::TraceRegEntry, Trace::TarmacTracerRecord::TraceInstEntry, and Trace::TarmacTracerRecordV8::TraceInstEntryV8.
Referenced by Packet::PrintReqState::printObj(), and ~Printable().
The documentation for this class was generated from the following file:
base/printable.hh