gem5: Debug::SimpleFlag Class Reference
Debug::SimpleFlag Class Reference
#include <debug.hh>
Public Member Functions
SimpleFlag (const char *name, const char *desc)
bool status () const
operator bool () const
bool operator! () const
void enable ()
void disable ()
void sync ()
Public Member Functions inherited from Debug::Flag
Flag (const char *name, const char *desc)
virtual ~Flag ()
std::string name () const
std::string desc () const
virtual std::vector< Flag * > kids ()
Static Public Member Functions
static void enableAll ()
static void disableAll ()
Protected Attributes
bool _tracing
bool _status
Protected Attributes inherited from Debug::Flag
const char * _name
const char * _desc
Static Private Attributes
static bool _active = false
Detailed Description
Definition at line 62 of file debug.hh.
Constructor & Destructor Documentation
SimpleFlag()
Debug::SimpleFlag::SimpleFlag (const char * name, const char * desc) inline
Definition at line 70 of file debug.hh.
Member Function Documentation
disable()
void Debug::SimpleFlag::disable () inline virtual
Implements Debug::Flag.
Definition at line 79 of file debug.hh.
References Debug::Flag::sync().
disableAll()
void Debug::SimpleFlag::disableAll () static
Definition at line 109 of file debug.cc.
References Debug::allFlags(), and ArmISA::i.
Referenced by Trace::disable().
enable()
void Debug::SimpleFlag::enable () inline virtual
Implements Debug::Flag.
Definition at line 78 of file debug.hh.
References Debug::Flag::sync().
enableAll()
void Debug::SimpleFlag::enableAll () static
Definition at line 101 of file debug.cc.
References Debug::allFlags(), and ArmISA::i.
Referenced by Trace::enable().
operator bool()
Debug::SimpleFlag::operator bool () const inline
Definition at line 75 of file debug.hh.
operator!()
bool Debug::SimpleFlag::operator! () const inline
Definition at line 76 of file debug.hh.
status()
bool Debug::SimpleFlag::status () const inline
Definition at line 74 of file debug.hh.
Referenced by dumpDebugFlags().
sync()
void Debug::SimpleFlag::sync () inline virtual
Reimplemented from Debug::Flag.
Definition at line 81 of file debug.hh.
Member Data Documentation
_active
bool Debug::SimpleFlag::_active = false static private
Definition at line 64 of file debug.hh.
_status
bool Debug::SimpleFlag::_status protected
Definition at line 67 of file debug.hh.
_tracing
bool Debug::SimpleFlag::_tracing protected
Definition at line 66 of file debug.hh.
The documentation for this class was generated from the following files:
base/debug.hh
base/debug.cc