gem5: PacketFifo Class Reference
PacketFifo Class Reference
#include <pktfifo.hh>
Public Types
typedef std::list< PacketFifoEntry > fifo_list
typedef fifo_list::iterator iterator
typedef fifo_list::const_iterator const_iterator
Public Member Functions
PacketFifo (int max)
virtual ~PacketFifo ()
unsigned packets () const
unsigned maxsize () const
unsigned size () const
unsigned reserved () const
unsigned avail () const
bool empty () const
bool full () const
unsigned reserve (unsigned len=0)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
EthPacketPtr front ()
bool push (EthPacketPtr ptr)
void pop ()
void clear ()
void remove (iterator i)
bool copyout (void *dest, unsigned offset, unsigned len)
int countPacketsBefore (const_iterator i) const
int countPacketsAfter (const_iterator i) const
void check () const
void serialize (const std::string &base, CheckpointOut &cp) const
Serialization stuff.
void unserialize (const std::string &base, CheckpointIn &cp)
Protected Attributes
std::list< PacketFifoEntry > fifo
uint64_t _counter
unsigned _maxsize
unsigned _size
unsigned _reserved
Detailed Description
Definition at line 78 of file pktfifo.hh.
Member Typedef Documentation
const_iterator
typedef fifo_list::const_iterator PacketFifo::const_iterator
Definition at line 84 of file pktfifo.hh.
fifo_list
typedef std::list<PacketFifoEntry> PacketFifo::fifo_list
Definition at line 82 of file pktfifo.hh.
iterator
typedef fifo_list::iterator PacketFifo::iterator
Definition at line 83 of file pktfifo.hh.
Constructor & Destructor Documentation
PacketFifo()
PacketFifo::PacketFifo (int max) inline explicit
Definition at line 94 of file pktfifo.hh.
~PacketFifo()
virtual PacketFifo::~PacketFifo () inline virtual
Definition at line 96 of file pktfifo.hh.
Member Function Documentation
avail()
unsigned PacketFifo::avail () const inline
Definition at line 102 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead(), Sinic::Device::recvPacket(), NSGigE::recvPacket(), Sinic::Device::transmit(), NSGigE::transmit(), Sinic::Device::txKick(), NSGigE::txKick(), IGbE::txStateMachine(), and IGbE::txWire().
begin() [1/2]
iterator PacketFifo::begin () inline
Definition at line 114 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead(), Sinic::Device::serialize(), and Sinic::Device::unserialize().
begin() [2/2]
const_iterator PacketFifo::begin () const inline
Definition at line 117 of file pktfifo.hh.
check()
void PacketFifo::check () const inline
Definition at line 194 of file pktfifo.hh.
References X86ISA::base, ArmISA::i, panic, PacketFifoEntry::serialize(), Stats::total, and PacketFifoEntry::unserialize().
Referenced by Sinic::Device::rxKick().
clear()
void PacketFifo::clear () inline
Definition at line 151 of file pktfifo.hh.
References ArmISA::i.
Referenced by IGbE::IGbE(), Sinic::Device::reset(), NSGigE::rxReset(), NSGigE::txReset(), and IGbE::write().
copyout()
bool PacketFifo::copyout (void * dest, unsigned offset, unsigned len)
Definition at line 38 of file pktfifo.cc.
References data, ArmISA::i, and panic.
countPacketsAfter()
int PacketFifo::countPacketsAfter (const_iterator i) const inline
Definition at line 186 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead().
countPacketsBefore()
int PacketFifo::countPacketsBefore (const_iterator i) const inline
Definition at line 179 of file pktfifo.hh.
Referenced by Sinic::Device::rxKick(), and Sinic::Device::serialize().
empty()
bool PacketFifo::empty () const inline
Definition at line 103 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead(), Sinic::Device::rxKick(), NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transferDone(), NSGigE::transferDone(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
end() [1/2]
iterator PacketFifo::end () inline
Definition at line 115 of file pktfifo.hh.
Referenced by Sinic::Device::recvPacket(), Sinic::Device::reset(), Sinic::Device::rxKick(), Sinic::Device::serialize(), Sinic::Device::unserialize(), and Sinic::Device::write().
end() [2/2]
const_iterator PacketFifo::end () const inline
Definition at line 118 of file pktfifo.hh.
front()
EthPacketPtr PacketFifo::front () inline
Definition at line 120 of file pktfifo.hh.
Referenced by NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
full()
bool PacketFifo::full () const inline
Definition at line 104 of file pktfifo.hh.
Referenced by NSGigE::txKick().
maxsize()
unsigned PacketFifo::maxsize () const inline
Definition at line 99 of file pktfifo.hh.
packets()
unsigned PacketFifo::packets () const inline
Definition at line 98 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead().
pop()
void PacketFifo::pop () inline
Definition at line 139 of file pktfifo.hh.
Referenced by NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
push()
bool PacketFifo::push (EthPacketPtr ptr) inline
Definition at line 122 of file pktfifo.hh.
References length, PacketFifoEntry::number, and PacketFifoEntry::packet.
Referenced by IGbE::ethRxPkt(), Sinic::Device::recvPacket(), NSGigE::recvPacket(), Sinic::Device::txKick(), NSGigE::txKick(), and IGbE::txStateMachine().
remove()
void PacketFifo::remove (iterator i) inline
Definition at line 160 of file pktfifo.hh.
References ArmISA::i, ArmISA::len, and ArmISA::offset.
Referenced by Sinic::Device::rxKick().
reserve()
unsigned PacketFifo::reserve (unsigned len = 0) inline
Definition at line 107 of file pktfifo.hh.
References ArmISA::len.
Referenced by NSGigE::txKick(), and IGbE::txStateMachine().
reserved()
unsigned PacketFifo::reserved () const inline
Definition at line 101 of file pktfifo.hh.
serialize()
void PacketFifo::serialize (const std::string & base, CheckpointOut & cp) const
Serialization stuff.
Definition at line 88 of file pktfifo.cc.
References csprintf(), ArmISA::i, and paramOut().
Referenced by Sinic::Device::serialize(), NSGigE::serialize(), and IGbE::serialize().
size()
unsigned PacketFifo::size () const inline
Definition at line 100 of file pktfifo.hh.
Referenced by Sinic::Device::prepareRead(), Sinic::Device::recvPacket(), Sinic::Device::rxKick(), NSGigE::rxKick(), Sinic::Device::transmit(), NSGigE::transmit(), and Sinic::Device::txKick().
unserialize()
void PacketFifo::unserialize (const std::string & base, CheckpointIn & cp)
Definition at line 101 of file pktfifo.cc.
References csprintf(), ArmISA::i, paramIn(), and PacketFifoEntry::unserialize().
Referenced by Sinic::Device::unserialize(), NSGigE::unserialize(), and IGbE::unserialize().
Member Data Documentation
_counter
uint64_t PacketFifo::_counter protected
Definition at line 88 of file pktfifo.hh.
_maxsize
unsigned PacketFifo::_maxsize protected
Definition at line 89 of file pktfifo.hh.
_reserved
unsigned PacketFifo::_reserved protected
Definition at line 91 of file pktfifo.hh.
_size
unsigned PacketFifo::_size protected
Definition at line 90 of file pktfifo.hh.
fifo
std::list<PacketFifoEntry> PacketFifo::fifo protected
Definition at line 87 of file pktfifo.hh.
The documentation for this class was generated from the following files:
dev/net/pktfifo.hh
dev/net/pktfifo.cc