gem5: ImageFile Class Reference
ImageFile Class Reference abstract
#include <image_file.hh>
Public Member Functions
virtual MemoryImage buildImage () const =0
Protected Member Functions
ImageFile (ImageFileDataPtr data)
virtual ~ImageFile ()
Protected Attributes
ImageFileDataPtr imageData
Detailed Description
Definition at line 41 of file image_file.hh.
Constructor & Destructor Documentation
ImageFile()
ImageFile::ImageFile (ImageFileDataPtr data) inline protected
Definition at line 45 of file image_file.hh.
~ImageFile()
virtual ImageFile::~ImageFile () inline protected virtual
Definition at line 46 of file image_file.hh.
References buildImage().
Member Function Documentation
buildImage()
virtual MemoryImage ImageFile::buildImage () const pure virtual
Implemented in ElfObject, DtbFile, EcoffObject, AoutObject, and RawImage.
Referenced by Process::init(), BareMetalRiscvSystem::initState(), AlphaSystem::initState(), ArmSystem::initState(), Process::Process(), SparcSystem::SparcSystem(), System::System(), and ~ImageFile().
Member Data Documentation
imageData
ImageFileDataPtr ImageFile::imageData protected
Definition at line 44 of file image_file.hh.
Referenced by AoutObject::AoutObject(), RawImage::buildImage(), AoutObject::buildImage(), EcoffObject::buildImage(), DtbFile::buildImage(), DtbFile::DtbFile(), EcoffObject::EcoffObject(), ElfObject::ElfObject(), ElfObject::getSections(), ElfObject::handleLoadableSegment(), EcoffObject::loadGlobalSymbols(), EcoffObject::loadLocalSymbols(), and ElfObject::loadSomeSymbols().
The documentation for this class was generated from the following file:
base/loader/image_file.hh