gem5: IntSinkPinBase Class Reference
IntSinkPinBase Class Reference abstract
#include <intpin.hh>
Public Member Functions
int number ()
bool state ()
void bind (Port &peer) override
Attach to a peer port.
void unbind () override
Dettach from a peer port.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
IntSinkPinBase (const std::string &_name, PortID _id, int num)
virtual void raiseOnDevice ()=0
virtual void lowerOnDevice ()=0
void raise ()
void lower ()
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Attributes
friend IntSourcePinBase
IntSourcePinBase * source = nullptr
int _number = 0
bool _state = false
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Definition at line 37 of file intpin.hh.
Constructor & Destructor Documentation
IntSinkPinBase()
IntSinkPinBase::IntSinkPinBase (const std::string & _name, PortID _id, int num) inline protected
Definition at line 47 of file intpin.hh.
References lowerOnDevice(), and raiseOnDevice().
Member Function Documentation
bind()
void IntSinkPinBase::bind (Port & peer) override virtual
Attach to a peer port.
Reimplemented from Port.
Definition at line 35 of file intpin.cc.
References Port::bind(), fatal_if, Port::name(), and source.
Referenced by IntSourcePinBase::lower(), and state().
lower()
void IntSinkPinBase::lower () inline protected
Definition at line 62 of file intpin.hh.
References lowerOnDevice().
Referenced by IntSourcePinBase::bind(), and IntSourcePinBase::lower().
lowerOnDevice()
virtual void IntSinkPinBase::lowerOnDevice () protected pure virtual
Implemented in IntSinkPin< Device >, IntSinkPin< X86ISA::I82094AA >, and IntSinkPin< X86ISA::I8259 >.
Referenced by IntSinkPinBase(), and lower().
number()
int IntSinkPinBase::number () inline
Definition at line 69 of file intpin.hh.
References _number.
Referenced by IntSinkPin< X86ISA::I8259 >::lowerOnDevice(), and IntSinkPin< X86ISA::I8259 >::raiseOnDevice().
raise()
void IntSinkPinBase::raise () inline protected
Definition at line 55 of file intpin.hh.
References raiseOnDevice().
Referenced by IntSourcePinBase::raise().
raiseOnDevice()
virtual void IntSinkPinBase::raiseOnDevice () protected pure virtual
Implemented in IntSinkPin< Device >, IntSinkPin< X86ISA::I82094AA >, and IntSinkPin< X86ISA::I8259 >.
Referenced by IntSinkPinBase(), and raise().
state()
bool IntSinkPinBase::state () inline
Definition at line 70 of file intpin.hh.
References _state, bind(), and unbind().
unbind()
void IntSinkPinBase::unbind () override virtual
Dettach from a peer port.
Reimplemented from Port.
Definition at line 44 of file intpin.cc.
References source, and Port::unbind().
Referenced by IntSourcePinBase::lower(), and state().
Member Data Documentation
_number
int IntSinkPinBase::_number = 0 protected
Definition at line 44 of file intpin.hh.
Referenced by number().
_state
bool IntSinkPinBase::_state = false protected
Definition at line 45 of file intpin.hh.
Referenced by IntSourcePinBase::bind(), and state().
IntSourcePinBase
friend IntSinkPinBase::IntSourcePinBase protected
Definition at line 40 of file intpin.hh.
source
IntSourcePinBase* IntSinkPinBase::source = nullptr protected
Definition at line 42 of file intpin.hh.
Referenced by bind(), and unbind().
The documentation for this class was generated from the following files:
dev/intpin.hh
dev/intpin.cc