gem5: SparcISA::TLB Class Reference
SparcISA::TLB Class Reference
#include <tlb.hh>
Public Types
typedef SparcTLBParams Params
Public Types inherited from BaseTLB
enum Mode { Read, Write, Execute }
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TlbEntry * lookup (Addr va, int partition_id, bool real, int context_id=0, bool update_used=true)
lookup an entry in the TLB based on the partition id, and real bit if real is true or the partition id, and context id if real is false.
void flushAll () override
Remove all entries from the TLB.
TLB (const Params *p)
void takeOverFrom (BaseTLB *otlb) override
Take over from an old tlb context.
void demapPage (Addr vaddr, uint64_t asn) override
void dumpAll ()
Fault translateAtomic (const RequestPtr &req, ThreadContext *tc, Mode mode) override
void translateTiming (const RequestPtr &req, ThreadContext *tc, Translation *translation, Mode mode) override
Fault finalizePhysical (const RequestPtr &req, ThreadContext *tc, Mode mode) const override
Do post-translation physical address finalization.
Cycles doMmuRegRead (ThreadContext *tc, Packet *pkt)
Cycles doMmuRegWrite (ThreadContext *tc, Packet *pkt)
void GetTsbPtr (ThreadContext *tc, Addr addr, int ctx, Addr *ptrs)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
uint64_t TteRead (int entry)
Give an entry id, read that tlb entries' tte.
Public Member Functions inherited from BaseTLB
virtual Fault translateFunctional (const RequestPtr &req, ThreadContext *tc, Mode mode)
virtual Port * getTableWalkerPort ()
Get the table walker port if present.
void memInvalidate ()
Invalidate the contents of memory buffers.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
enum FaultTypes {
OtherFault = 0, PrivViolation = 0x1, SideEffect = 0x2, AtomicToIo = 0x4,
IllegalAsi = 0x8, LoadFromNfo = 0x10, VaOutOfRange = 0x20, VaOutOfRangeJmp = 0x40
}
enum ContextType { Primary = 0, Secondary = 1, Nucleus = 2 }
enum TsbPageSize { Ps0, Ps1 }
typedef TlbMap::iterator MapIter
Protected Member Functions
void insert (Addr vpn, int partition_id, int context_id, bool real, const PageTableEntry &PTE, int entry=-1)
Insert a PTE into the TLB.
uint64_t TagRead (int entry)
Given an entry id, read that tlb entries' tag.
void demapAll (int partition_id)
Remove all non-locked entries from the tlb that match partition id.
void demapContext (int partition_id, int context_id)
Remove all entries that match a given context/partition id.
void demapPage (Addr va, int partition_id, bool real, int context_id)
Remve all entries that match a certain partition id, (contextid), and va).
bool validVirtualAddress (Addr va, bool am)
Checks if the virtual address provided is a valid one.
void writeSfsr (bool write, ContextType ct, bool se, FaultTypes ft, int asi)
void clearUsedBits ()
void writeTagAccess (Addr va, int context)
Fault translateInst (const RequestPtr &req, ThreadContext *tc)
Fault translateData (const RequestPtr &req, ThreadContext *tc, bool write)
Protected Member Functions inherited from BaseTLB
BaseTLB (const Params *p)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes
uint64_t sfar
uint64_t c0_tsb_ps0
uint64_t c0_tsb_ps1
uint64_t c0_config
uint64_t cx_tsb_ps0
uint64_t cx_tsb_ps1
uint64_t cx_config
uint64_t sfsr
uint64_t tag_access
TlbMap lookupTable
TlbEntry * tlb
int size
int usedEntries
int lastReplaced
uint64_t cacheState
bool cacheValid
std::list< TlbEntry * > freeList
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
void writeSfsr (Addr a, bool write, ContextType ct, bool se, FaultTypes ft, int asi)
uint64_t MakeTsbPtr (TsbPageSize ps, uint64_t tag_access, uint64_t c0_tsb, uint64_t c0_config, uint64_t cX_tsb, uint64_t cX_config)
Private Attributes
TlbEntry * cacheEntry [2]
ASI cacheAsi [2]
Friends
class FastInstructionAccessMMUMiss
class FastDataAccessMMUMiss
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 52 of file tlb.hh.
Member Typedef Documentation
MapIter
typedef TlbMap::iterator SparcISA::TLB::MapIter protected
Definition at line 72 of file tlb.hh.
Params
typedef SparcTLBParams SparcISA::TLB::Params
Definition at line 158 of file tlb.hh.
Member Enumeration Documentation
ContextType
enum SparcISA::TLB::ContextType protected
Enumerator
Primary
Secondary
Nucleus
Definition at line 97 of file tlb.hh.
FaultTypes
enum SparcISA::TLB::FaultTypes protected
Enumerator
OtherFault
PrivViolation
SideEffect
AtomicToIo
IllegalAsi
LoadFromNfo
VaOutOfRange
VaOutOfRangeJmp
Definition at line 86 of file tlb.hh.
TsbPageSize
enum SparcISA::TLB::TsbPageSize protected
Enumerator
Ps0
Ps1
Definition at line 103 of file tlb.hh.
Constructor & Destructor Documentation
TLB()
SparcISA::TLB::TLB (const Params * p)
Definition at line 55 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, cacheEntry, cx_config, cx_tsb_ps0, cx_tsb_ps1, fatal, freeList, sfar, sfsr, size, tag_access, tlb, and X86ISA::x.
Member Function Documentation
clearUsedBits()
void SparcISA::TLB::clearUsedBits () protected
Definition at line 83 of file tlb.cc.
References SparcISA::TlbMap::begin(), SparcISA::TlbMap::end(), ArmISA::i, SparcISA::PageTableEntry::locked(), lookupTable, SparcISA::TlbEntry::pte, ArmISA::t, SparcISA::TlbEntry::used, and usedEntries.
Referenced by insert(), and lookup().
demapAll()
void SparcISA::TLB::demapAll (int partition_id) protected
Remove all non-locked entries from the tlb that match partition id.
Definition at line 310 of file tlb.cc.
References cacheValid, DPRINTF, SparcISA::TlbMap::erase(), freeList, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::range, size, tlb, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
demapContext()
void SparcISA::TLB::demapContext (int partition_id, int context_id) protected
Remove all entries that match a given context/partition id.
Definition at line 288 of file tlb.cc.
References cacheValid, DPRINTF, SparcISA::TlbMap::erase(), freeList, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::range, size, tlb, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
demapPage() [1/2]
void SparcISA::TLB::demapPage (Addr va, int partition_id, bool real, int context_id) protected
Remve all entries that match a certain partition id, (contextid), and va).
Definition at line 256 of file tlb.cc.
References cacheValid, SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::erase(), SparcISA::TlbMap::find(), freeList, ArmISA::i, lookupTable, SparcISA::TlbRange::partitionId, SparcISA::TlbRange::real, SparcISA::TlbRange::size, usedEntries, SparcISA::TlbRange::va, and ArmISA::va.
Referenced by doMmuRegWrite().
demapPage() [2/2]
void SparcISA::TLB::demapPage (Addr vaddr, uint64_t asn) inline override virtual
Implements BaseTLB.
Definition at line 164 of file tlb.hh.
References ArmISA::a, addr, doMmuRegRead(), doMmuRegWrite(), dumpAll(), finalizePhysical(), GetTsbPtr(), MakeTsbPtr(), ArmISA::mode, panic, ArmISA::ps, serialize(), translateAtomic(), translateTiming(), TteRead(), unserialize(), and writeSfsr().
doMmuRegRead()
Cycles SparcISA::TLB::doMmuRegRead (ThreadContext * tc, Packet * pkt)
Definition at line 861 of file tlb.cc.
References SparcISA::ASI_DMMU, SparcISA::ASI_DMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_TSB_PS0_PTR_REG, SparcISA::ASI_DMMU_TSB_PS1_PTR_REG, SparcISA::ASI_HYP_SCRATCHPAD, SparcISA::ASI_IMMU, SparcISA::ASI_IMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_TSB_PS0_PTR_REG, SparcISA::ASI_IMMU_TSB_PS1_PTR_REG, SparcISA::ASI_LSU_CONTROL_REG, SparcISA::ASI_MMU, SparcISA::ASI_QUEUE, SparcISA::ASI_SCRATCHPAD, SparcISA::ASI_SPARC_ERROR_STATUS_REG, SparcISA::ASI_SWVR_INTR_RECEIVE, SparcISA::ASI_SWVR_UDB_INTR_R, bits(), c0_config, c0_tsb_ps0, c0_tsb_ps1, BaseCPU::clearInterrupt(), cx_config, cx_tsb_ps0, cx_tsb_ps1, DPRINTF, findMsbSet(), SparcISA::Interrupts::get_vec(), Packet::getAddr(), ThreadContext::getCpuPtr(), BaseCPU::getInterruptController(), ThreadContext::getITBPtr(), SparcISA::IT_INT_VEC, Packet::makeAtomicResponse(), MakeTsbPtr(), SparcISA::MISCREG_MMU_LSU_CTRL, SparcISA::MISCREG_MMU_P_CONTEXT, SparcISA::MISCREG_MMU_PART_ID, SparcISA::MISCREG_MMU_S_CONTEXT, SparcISA::MISCREG_QUEUE_CPU_MONDO_HEAD, SparcISA::MISCREG_SCRATCHPAD_R0, panic, Ps0, Ps1, ThreadContext::readMiscReg(), Packet::req, Packet::setBE(), sfar, sfsr, tag_access, and ArmISA::va.
Referenced by demapPage().
doMmuRegWrite()
Cycles SparcISA::TLB::doMmuRegWrite (ThreadContext * tc, Packet * pkt)
Definition at line 1046 of file tlb.cc.
References SparcISA::ASI_DMMU, SparcISA::ASI_DMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_DMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_DMMU_DEMAP, SparcISA::ASI_DTLB_DATA_ACCESS_REG, SparcISA::ASI_DTLB_DATA_IN_REG, SparcISA::ASI_HYP_SCRATCHPAD, SparcISA::ASI_IMMU, SparcISA::ASI_IMMU_CTXT_NONZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_NONZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_CTXT_ZERO_CONFIG, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS0, SparcISA::ASI_IMMU_CTXT_ZERO_TSB_BASE_PS1, SparcISA::ASI_IMMU_DEMAP, SparcISA::ASI_ITLB_DATA_ACCESS_REG, SparcISA::ASI_ITLB_DATA_IN_REG, SparcISA::ASI_LSU_CONTROL_REG, SparcISA::ASI_MMU, SparcISA::ASI_QUEUE, SparcISA::ASI_SCRATCHPAD, SparcISA::ASI_SPARC_ERROR_EN_REG, SparcISA::ASI_SPARC_ERROR_STATUS_REG, SparcISA::ASI_SWVR_INTR_RECEIVE, SparcISA::ASI_SWVR_UDB_INTR_W, bits(), c0_config, c0_tsb_ps0, c0_tsb_ps1, BaseCPU::clearInterrupt(), cx_config, cx_tsb_ps0, cx_tsb_ps1, data, demapAll(), demapContext(), demapPage(), DPRINTF, findMsbSet(), SparcISA::Interrupts::get_vec(), Packet::getAddr(), Packet::getBE(), ThreadContext::getCpuPtr(), BaseCPU::getInterruptController(), ThreadContext::getITBPtr(), ThreadContext::getSystemPtr(), ignore(), inform, insert(), SparcISA::IT_INT_VEC, M5_FALLTHROUGH, Packet::makeAtomicResponse(), mbits(), SparcISA::MISCREG_MMU_LSU_CTRL, SparcISA::MISCREG_MMU_P_CONTEXT, SparcISA::MISCREG_MMU_PART_ID, SparcISA::MISCREG_MMU_S_CONTEXT, SparcISA::MISCREG_QUEUE_CPU_MONDO_HEAD, SparcISA::MISCREG_SCRATCHPAD_R0, panic, SparcISA::PageTableEntry::populate(), ThreadContext::readMiscReg(), Packet::req, ThreadContext::setMiscReg(), sfsr, SparcISA::PageTableEntry::sun4u, SparcISA::PageTableEntry::sun4v, tag_access, System::threadContexts, and ArmISA::va.
Referenced by demapPage().
dumpAll()
void SparcISA::TLB::dumpAll ()
Definition at line 242 of file tlb.cc.
References SparcISA::TlbRange::contextId, DPRINTFN, ArmISA::i, SparcISA::PageTableEntry::paddr(), SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, size, SparcISA::TlbRange::size, tlb, SparcISA::TlbRange::va, and X86ISA::x.
Referenced by demapPage().
finalizePhysical()
Fault SparcISA::TLB::finalizePhysical (const RequestPtr & req, ThreadContext * tc, Mode mode) const override virtual
Do post-translation physical address finalization.
This method is used by some architectures that need post-translation massaging of physical addresses. For example, X86 uses this to remap physical addresses in the APIC range to a range of physical memory not normally available to real x86 implementations.
Parameters
req Request to updated in-place.
tc Thread context that created the request.
mode Request type (read/write/execute).
Returns
A fault on failure, NoFault otherwise.
Implements BaseTLB.
Definition at line 854 of file tlb.cc.
References NoFault.
Referenced by demapPage().
flushAll()
void SparcISA::TLB::flushAll () override virtual
Remove all entries from the TLB.
Implements BaseTLB.
Definition at line 329 of file tlb.cc.
References cacheValid, SparcISA::TlbMap::clear(), freeList, lookupTable, size, tlb, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbEntry::valid, and X86ISA::x.
GetTsbPtr()
void SparcISA::TLB::GetTsbPtr (ThreadContext * tc, Addr addr, int ctx, Addr * ptrs)
Definition at line 1300 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, cx_config, cx_tsb_ps0, cx_tsb_ps1, ThreadContext::getITBPtr(), MakeTsbPtr(), mbits(), Ps0, Ps1, and tag_access.
Referenced by demapPage(), and SparcISA::vtophys().
insert()
void SparcISA::TLB::insert (Addr vpn, int partition_id, int context_id, bool real, const PageTableEntry & PTE, int entry = -1) protected
Insert a PTE into the TLB.
Definition at line 97 of file tlb.cc.
References cacheValid, clearUsedBits(), SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::erase(), freeList, ArmISA::i, SparcISA::TlbMap::insert(), lastReplaced, lookupTable, SparcISA::PageTableEntry::paddr(), SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, size, SparcISA::PageTableEntry::size(), SparcISA::TlbRange::size, tlb, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbRange::va, ArmISA::va, SparcISA::PageTableEntry::valid(), SparcISA::TlbEntry::valid, and X86ISA::x.
Referenced by doMmuRegWrite().
lookup()
TlbEntry * SparcISA::TLB::lookup (Addr va, int partition_id, bool real, int context_id = 0, bool update_used = true)
lookup an entry in the TLB based on the partition id, and real bit if real is true or the partition id, and context id if real is false.
Parameters
va the virtual address not shifted (e.g. bottom 13 bits are 0)
paritition_id partition this entry is for
real is this a real->phys or virt->phys translation
context_id if this is virt->phys what context
update_used should ew update the used bits in the entries on not useful if we are trying to do a va->pa without mucking with any state for a debug read for example.
Returns
A pointer to a tlb entry
Definition at line 198 of file tlb.cc.
References clearUsedBits(), SparcISA::TlbRange::contextId, DPRINTF, SparcISA::TlbMap::end(), SparcISA::TlbMap::find(), ArmISA::i, lookupTable, SparcISA::PageTableEntry::paddr(), SparcISA::TlbRange::partitionId, SparcISA::TlbEntry::pte, SparcISA::TlbRange::real, size, SparcISA::PageTableEntry::size(), SparcISA::TlbRange::size, ArmISA::t, SparcISA::TlbEntry::used, usedEntries, SparcISA::TlbRange::va, and ArmISA::va.
Referenced by translateData(), translateInst(), and SparcISA::vtophys().
MakeTsbPtr()
uint64_t SparcISA::TLB::MakeTsbPtr (TsbPageSize ps, uint64_t tag_access, uint64_t c0_tsb, uint64_t c0_config, uint64_t cX_tsb, uint64_t cX_config) private
Definition at line 1327 of file tlb.cc.
References bits(), c0_config, ArmISA::mask, mbits(), Ps0, Ps1, and ULL.
Referenced by demapPage(), doMmuRegRead(), and GetTsbPtr().
serialize()
void SparcISA::TLB::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1354 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, csprintf(), cx_config, cx_tsb_ps0, cx_tsb_ps1, freeList, lastReplaced, SparcISA::TlbEntry::serialize(), SERIALIZE_CONTAINER, SERIALIZE_SCALAR, sfar, sfsr, size, tag_access, tlb, usedEntries, and X86ISA::x.
Referenced by demapPage().
TagRead()
uint64_t SparcISA::TLB::TagRead (int entry) protected
Given an entry id, read that tlb entries' tag.
Definition at line 357 of file tlb.cc.
References SparcISA::TlbRange::contextId, SparcISA::TlbEntry::range, SparcISA::TlbRange::real, size, tlb, ULL, and SparcISA::TlbRange::va.
takeOverFrom()
void SparcISA::TLB::takeOverFrom (BaseTLB * otlb) inline override virtual
Take over from an old tlb context.
Implements BaseTLB.
Definition at line 161 of file tlb.hh.
translateAtomic()
Fault SparcISA::TLB::translateAtomic (const RequestPtr & req, ThreadContext * tc, Mode mode) override virtual
Implements BaseTLB.
Definition at line 837 of file tlb.cc.
References BaseTLB::Execute, translateData(), translateInst(), and BaseTLB::Write.
Referenced by demapPage(), and translateTiming().
translateData()
Fault SparcISA::TLB::translateData (const RequestPtr & req, ThreadContext * tc, bool write) protected
Normal flow ends here.
Definition at line 533 of file tlb.cc.
References SparcISA::ASI_IMPLICIT, SparcISA::ASI_N, SparcISA::ASI_P, SparcISA::ASI_S, SparcISA::ASI_SWVR_UDB_INTR_R, SparcISA::ASI_SWVR_UDB_INTR_W, SparcISA::asiIsAsIfUser(), SparcISA::asiIsBlock(), SparcISA::asiIsCmt(), SparcISA::asiIsHPriv(), SparcISA::asiIsInterrupt(), SparcISA::asiIsLittle(), SparcISA::asiIsMmu(), SparcISA::asiIsNoFault(), SparcISA::asiIsNucleus(), SparcISA::asiIsPartialStore(), SparcISA::asiIsPrimary(), SparcISA::asiIsQueue(), SparcISA::asiIsReal(), SparcISA::asiIsScratchPad(), SparcISA::asiIsSecondary(), SparcISA::asiIsSparcError(), SparcISA::asiIsTwin(), SparcISA::asiIsUnPriv(), bits(), cacheAsi, cacheEntry, cacheState, cacheValid, MipsISA::ce, DPRINTF, ArmISA::e, freeList, FullSystem, SparcISA::hpriv, IllegalAsi, LoadFromNfo, lookup(), lookupTable, SparcISA::MISCREG_TLB_DATA, Request::MMAPPED_IPR, SparcISA::PageTableEntry::nofault(), NoFault, Nucleus, OtherFault, SparcISA::PageTableEntry::paddr(), SparcISA::PAddrImplMask, panic, Primary, SparcISA::priv, SparcISA::PageTableEntry::priv(), PrivViolation, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, ThreadContext::readMiscRegNoEffect(), SparcISA::red, Secondary, SideEffect, SparcISA::PageTableEntry::sideffect(), size, SparcISA::TlbMap::size(), Request::STRICT_ORDER, MipsISA::tl, SparcISA::PageTableEntry::translate(), Request::UNCACHEABLE, SparcISA::TlbRange::va, MipsISA::vaddr, SparcISA::VAddrAMask, SparcISA::TlbEntry::valid, validVirtualAddress(), VaOutOfRange, SparcISA::PageTableEntry::writable(), writeSfsr(), and writeTagAccess().
Referenced by translateAtomic().
translateInst()
Fault SparcISA::TLB::translateInst (const RequestPtr & req, ThreadContext * tc) protected
Definition at line 419 of file tlb.cc.
References SparcISA::ASI_IMPLICIT, SparcISA::ASI_N, SparcISA::ASI_P, bits(), cacheEntry, cacheState, cacheValid, DPRINTF, ArmISA::e, FullSystem, SparcISA::hpriv, lookup(), SparcISA::MISCREG_TLB_DATA, NoFault, Nucleus, OtherFault, SparcISA::PAddrImplMask, Primary, SparcISA::priv, SparcISA::PageTableEntry::priv(), PrivViolation, SparcISA::TlbEntry::pte, SparcISA::TlbEntry::range, ThreadContext::readMiscRegNoEffect(), SparcISA::red, SparcISA::TlbRange::size, MipsISA::tl, SparcISA::PageTableEntry::translate(), SparcISA::TlbRange::va, MipsISA::vaddr, SparcISA::VAddrAMask, SparcISA::TlbEntry::valid, validVirtualAddress(), VaOutOfRange, writeSfsr(), and writeTagAccess().
Referenced by translateAtomic().
translateTiming()
void SparcISA::TLB::translateTiming (const RequestPtr & req, ThreadContext * tc, Translation * translation, Mode mode) override virtual
Implements BaseTLB.
Definition at line 846 of file tlb.cc.
References BaseTLB::Translation::finish(), and translateAtomic().
Referenced by demapPage().
TteRead()
uint64_t SparcISA::TLB::TteRead (int entry)
Give an entry id, read that tlb entries' tte.
Definition at line 344 of file tlb.cc.
References panic, SparcISA::TlbEntry::pte, size, and tlb.
Referenced by demapPage().
unserialize()
void SparcISA::TLB::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1384 of file tlb.cc.
References c0_config, c0_tsb_ps0, c0_tsb_ps1, SparcISA::TlbMap::clear(), csprintf(), cx_config, cx_tsb_ps0, cx_tsb_ps1, freeList, SparcISA::TlbMap::insert(), lastReplaced, lookupTable, panic, paramIn(), sfar, sfsr, size, tag_access, tlb, SparcISA::TlbEntry::unserialize(), UNSERIALIZE_CONTAINER, UNSERIALIZE_SCALAR, usedEntries, and X86ISA::x.
Referenced by demapPage().
validVirtualAddress()
bool SparcISA::TLB::validVirtualAddress (Addr va, bool am) protected
Checks if the virtual address provided is a valid one.
Definition at line 373 of file tlb.cc.
References SparcISA::EndVAddrHole, and SparcISA::StartVAddrHole.
Referenced by translateData(), and translateInst().
writeSfsr() [1/2]
void SparcISA::TLB::writeSfsr (bool write, ContextType ct, bool se, FaultTypes ft, int asi) protected
Definition at line 383 of file tlb.cc.
References sfsr.
Referenced by demapPage(), translateData(), translateInst(), and writeSfsr().
writeSfsr() [2/2]
void SparcISA::TLB::writeSfsr (Addr a, bool write, ContextType ct, bool se, FaultTypes ft, int asi) private
Definition at line 409 of file tlb.cc.
References ArmISA::a, DPRINTF, sfar, and writeSfsr().
writeTagAccess()
void SparcISA::TLB::writeTagAccess (Addr va, int context) protected
Definition at line 400 of file tlb.cc.
References DPRINTF, mbits(), and tag_access.
Referenced by translateData(), and translateInst().
Friends And Related Function Documentation
FastDataAccessMMUMiss
friend class FastDataAccessMMUMiss friend
Definition at line 56 of file tlb.hh.
FastInstructionAccessMMUMiss
friend class FastInstructionAccessMMUMiss friend
Definition at line 55 of file tlb.hh.
Member Data Documentation
c0_config
uint64_t SparcISA::TLB::c0_config protected
Definition at line 64 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), MakeTsbPtr(), serialize(), TLB(), and unserialize().
c0_tsb_ps0
uint64_t SparcISA::TLB::c0_tsb_ps0 protected
Definition at line 62 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
c0_tsb_ps1
uint64_t SparcISA::TLB::c0_tsb_ps1 protected
Definition at line 63 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
cacheAsi
ASI SparcISA::TLB::cacheAsi[2] private
Definition at line 199 of file tlb.hh.
Referenced by translateData().
cacheEntry
TlbEntry* SparcISA::TLB::cacheEntry[2] private
Definition at line 198 of file tlb.hh.
Referenced by TLB(), translateData(), and translateInst().
cacheState
uint64_t SparcISA::TLB::cacheState protected
Definition at line 81 of file tlb.hh.
Referenced by translateData(), and translateInst().
cacheValid
bool SparcISA::TLB::cacheValid protected
Definition at line 82 of file tlb.hh.
Referenced by demapAll(), demapContext(), demapPage(), flushAll(), insert(), translateData(), and translateInst().
cx_config
uint64_t SparcISA::TLB::cx_config protected
Definition at line 67 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
cx_tsb_ps0
uint64_t SparcISA::TLB::cx_tsb_ps0 protected
Definition at line 65 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
cx_tsb_ps1
uint64_t SparcISA::TLB::cx_tsb_ps1 protected
Definition at line 66 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), and unserialize().
freeList
std::list<TlbEntry*> SparcISA::TLB::freeList protected
Definition at line 84 of file tlb.hh.
Referenced by demapAll(), demapContext(), demapPage(), flushAll(), insert(), serialize(), TLB(), translateData(), and unserialize().
lastReplaced
int SparcISA::TLB::lastReplaced protected
Definition at line 79 of file tlb.hh.
Referenced by insert(), serialize(), and unserialize().
lookupTable
TlbMap SparcISA::TLB::lookupTable protected
Definition at line 72 of file tlb.hh.
Referenced by clearUsedBits(), demapAll(), demapContext(), demapPage(), flushAll(), insert(), lookup(), translateData(), and unserialize().
sfar
uint64_t SparcISA::TLB::sfar protected
Definition at line 61 of file tlb.hh.
Referenced by doMmuRegRead(), serialize(), TLB(), unserialize(), and writeSfsr().
sfsr
uint64_t SparcISA::TLB::sfsr protected
Definition at line 68 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), serialize(), TLB(), unserialize(), and writeSfsr().
size
int SparcISA::TLB::size protected
Definition at line 77 of file tlb.hh.
Referenced by demapAll(), demapContext(), dumpAll(), flushAll(), insert(), lookup(), serialize(), TagRead(), TLB(), translateData(), TteRead(), and unserialize().
tag_access
uint64_t SparcISA::TLB::tag_access protected
Definition at line 69 of file tlb.hh.
Referenced by doMmuRegRead(), doMmuRegWrite(), GetTsbPtr(), serialize(), TLB(), unserialize(), and writeTagAccess().
tlb
TlbEntry* SparcISA::TLB::tlb protected
Definition at line 75 of file tlb.hh.
Referenced by demapAll(), demapContext(), dumpAll(), flushAll(), insert(), serialize(), TagRead(), TLB(), TteRead(), and unserialize().
usedEntries
int SparcISA::TLB::usedEntries protected
Definition at line 78 of file tlb.hh.
Referenced by clearUsedBits(), demapAll(), demapContext(), demapPage(), flushAll(), insert(), lookup(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
arch/sparc/tlb.hh
arch/sparc/tlb.cc