gem5: AddrRangeMap< V, max_cache_size > Class Template Reference
AddrRangeMap< V, max_cache_size > Class Template Reference
The AddrRangeMap uses an STL map to implement an interval tree for address decoding.
#include <addr_range_map.hh>
Public Types
typedef RangeMap::iterator iterator
typedef RangeMap::const_iterator const_iterator
Public Member Functions
const_iterator contains (const AddrRange &r) const
Find entry that contains the given address range.
iterator contains (const AddrRange &r)
const_iterator contains (Addr r) const
Find entry that contains the given address.
iterator contains (Addr r)
const_iterator intersects (const AddrRange &r) const
Find entry that intersects with the given address range.
iterator intersects (const AddrRange &r)
iterator insert (const AddrRange &r, const V &d)
void erase (iterator p)
void erase (iterator p, iterator q)
void clear ()
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
std::size_t size () const
bool empty () const
Private Types
typedef std::map< AddrRange, V > RangeMap
Private Member Functions
void addNewEntryToCache (iterator it) const
Add an address range map entry to the cache.
iterator find (const AddrRange &r, std::function< bool(const AddrRange)> cond)
Find entry that satisfies a condition on an address range.
const_iterator find (const AddrRange &r, std::function< bool(const AddrRange)> cond) const
Private Attributes
RangeMap tree
std::list< iterator > cache
A list of iterator that correspond to the max_cache_size most recently used entries in the address range map.
Detailed Description
template<typename V, int max_cache_size = 0>
class AddrRangeMap< V, max_cache_size >
The AddrRangeMap uses an STL map to implement an interval tree for address decoding.
The value stored is a template type and can be e.g. a port identifier, or a pointer.
Definition at line 62 of file addr_range_map.hh.
Member Typedef Documentation
const_iterator
template<typename V, int max_cache_size = 0> typedef RangeMap::const_iterator AddrRangeMap< V, max_cache_size >::const_iterator
Definition at line 69 of file addr_range_map.hh.
iterator
template<typename V, int max_cache_size = 0> typedef RangeMap::iterator AddrRangeMap< V, max_cache_size >::iterator
Definition at line 68 of file addr_range_map.hh.
RangeMap
template<typename V, int max_cache_size = 0> typedef std::map<AddrRange, V> AddrRangeMap< V, max_cache_size >::RangeMap private
Definition at line 65 of file addr_range_map.hh.
Member Function Documentation
addNewEntryToCache()
template<typename V, int max_cache_size = 0> void AddrRangeMap< V, max_cache_size >::addNewEntryToCache (iterator it) const inline private
Add an address range map entry to the cache.
Parameters
it Iterator to the entry in the address range map
Definition at line 209 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::find().
begin() [1/2]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::begin () const inline
Definition at line 167 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::find().
begin() [2/2]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::begin () inline
Definition at line 173 of file addr_range_map.hh.
clear()
template<typename V, int max_cache_size = 0> void AddrRangeMap< V, max_cache_size >::clear () inline
Definition at line 160 of file addr_range_map.hh.
contains() [1/4]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::contains (const AddrRange & r) const inline
Find entry that contains the given address range.
Searches through the ranges in the address map and returns an iterator to the entry which range is a superset of the input address range. Returns end() if none found.
Parameters
r An input address range
Returns
An iterator that contains the input address range
Definition at line 82 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::contains(), and TEST().
contains() [2/4]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::contains (const AddrRange & r) inline
Definition at line 87 of file addr_range_map.hh.
contains() [3/4]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::contains (Addr r) const inline
Find entry that contains the given address.
Searches through the ranges in the address map and returns an iterator to the entry which range is a superset of the input address. Returns end() if none found.
Parameters
r An input address
Returns
An iterator that contains the input address
Definition at line 103 of file addr_range_map.hh.
contains() [4/4]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::contains (Addr r) inline
Definition at line 108 of file addr_range_map.hh.
empty()
template<typename V, int max_cache_size = 0> bool AddrRangeMap< V, max_cache_size >::empty () const inline
Definition at line 197 of file addr_range_map.hh.
end() [1/2]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::end () const inline
Definition at line 179 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::find(), AddrRangeMap< AbstractMemory *, 1 >::insert(), and TEST().
end() [2/2]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::end () inline
Definition at line 185 of file addr_range_map.hh.
erase() [1/2]
template<typename V, int max_cache_size = 0> void AddrRangeMap< V, max_cache_size >::erase (iterator p) inline
Definition at line 144 of file addr_range_map.hh.
erase() [2/2]
template<typename V, int max_cache_size = 0> void AddrRangeMap< V, max_cache_size >::erase (iterator p, iterator q) inline
Definition at line 151 of file addr_range_map.hh.
find() [1/2]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::find (const AddrRange & r, std::function< bool(const AddrRange)> cond) inline private
Find entry that satisfies a condition on an address range.
Searches through the ranges in the address map and returns an iterator to the entry that satisfies the input conidition on the input address range. Returns end() if none found.
Parameters
r An input address range
f A condition on an address range
Returns
An iterator that contains the input address range
Definition at line 240 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::contains(), AddrRangeMap< AbstractMemory *, 1 >::find(), and AddrRangeMap< AbstractMemory *, 1 >::intersects().
find() [2/2]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::find (const AddrRange & r, std::function< bool(const AddrRange)> cond) const inline private
Definition at line 277 of file addr_range_map.hh.
insert()
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::insert (const AddrRange & r, const V & d) inline
Definition at line 135 of file addr_range_map.hh.
Referenced by TEST().
intersects() [1/2]
template<typename V, int max_cache_size = 0> const_iterator AddrRangeMap< V, max_cache_size >::intersects (const AddrRange & r) const inline
Find entry that intersects with the given address range.
Searches through the ranges in the address map and returns an iterator to the first entry which range intersects with the input address.
Parameters
r An input address
Returns
An iterator that intersects with the input address range
Definition at line 124 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::insert(), and TEST().
intersects() [2/2]
template<typename V, int max_cache_size = 0> iterator AddrRangeMap< V, max_cache_size >::intersects (const AddrRange & r) inline
Definition at line 129 of file addr_range_map.hh.
size()
template<typename V, int max_cache_size = 0> std::size_t AddrRangeMap< V, max_cache_size >::size () const inline
Definition at line 191 of file addr_range_map.hh.
Member Data Documentation
cache
template<typename V, int max_cache_size = 0> std::list<iterator> AddrRangeMap< V, max_cache_size >::cache mutable private
A list of iterator that correspond to the max_cache_size most recently used entries in the address range map.
This mainly used to optimize lookups. The elements in the list should always be valid iterators of the tree.
Definition at line 290 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::addNewEntryToCache(), AddrRangeMap< AbstractMemory *, 1 >::clear(), AddrRangeMap< AbstractMemory *, 1 >::erase(), and AddrRangeMap< AbstractMemory *, 1 >::find().
tree
template<typename V, int max_cache_size = 0> RangeMap AddrRangeMap< V, max_cache_size >::tree private
Definition at line 282 of file addr_range_map.hh.
Referenced by AddrRangeMap< AbstractMemory *, 1 >::begin(), AddrRangeMap< AbstractMemory *, 1 >::clear(), AddrRangeMap< AbstractMemory *, 1 >::empty(), AddrRangeMap< AbstractMemory *, 1 >::end(), AddrRangeMap< AbstractMemory *, 1 >::erase(), AddrRangeMap< AbstractMemory *, 1 >::find(), AddrRangeMap< AbstractMemory *, 1 >::insert(), and AddrRangeMap< AbstractMemory *, 1 >::size().
The documentation for this class was generated from the following file:
base/addr_range_map.hh