gem5: RubyTester Class Reference
RubyTester Class Reference
#include <RubyTester.hh>
Classes
class CpuPort
struct SenderState
Public Types
typedef RubyTesterParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
RubyTester (const Params *p)
~RubyTester ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
bool isInstOnlyCpuPort (int idx)
bool isInstDataCpuPort (int idx)
MasterPort * getReadableCpuPort (int idx)
MasterPort * getWritableCpuPort (int idx)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void wakeup ()
void incrementCheckCompletions ()
void printStats (std::ostream &out) const
void clearStats ()
void printConfig (std::ostream &out) const
void print (std::ostream &out) const
bool getCheckFlush ()
MasterID masterId ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
EventFunctionWrapper checkStartEvent
MasterID _masterId
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Member Functions
void hitCallback (NodeID proc, SubBlock *data)
void checkForDeadlock ()
RubyTester (const RubyTester &obj)
RubyTester & operator= (const RubyTester &obj)
Private Attributes
CheckTable * m_checkTable_ptr
std::vector< Cycles > m_last_progress_vector
int m_num_cpus
uint64_t m_checks_completed
std::vector< MasterPort * > writePorts
std::vector< MasterPort * > readPorts
uint64_t m_checks_to_complete
int m_deadlock_threshold
int m_num_writers
int m_num_readers
int m_wakeup_frequency
bool m_check_flush
int m_num_inst_only_ports
int m_num_inst_data_ports
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 57 of file RubyTester.hh.
Member Typedef Documentation
Params
typedef RubyTesterParams RubyTester::Params
Definition at line 94 of file RubyTester.hh.
Constructor & Destructor Documentation
RubyTester() [1/2]
RubyTester::RubyTester (const Params * p)
Definition at line 52 of file RubyTester.cc.
References _masterId, checkStartEvent, EventBase::CPU_Tick_Pri, csprintf(), ArmISA::i, m_check_flush, m_checks_completed, m_checks_to_complete, m_checkTable_ptr, m_deadlock_threshold, m_num_cpus, m_num_inst_data_ports, m_num_inst_only_ports, m_num_readers, m_num_writers, m_wakeup_frequency, SimObject::name(), MipsISA::p, readPorts, EventManager::schedule(), wakeup(), and writePorts.
Referenced by print().
~RubyTester()
RubyTester::~RubyTester ()
Definition at line 106 of file RubyTester.cc.
References ArmISA::i, m_checkTable_ptr, and readPorts.
RubyTester() [2/2]
RubyTester::RubyTester (const RubyTester & obj) private
Member Function Documentation
checkForDeadlock()
void RubyTester::checkForDeadlock () private
Definition at line 261 of file RubyTester.cc.
References Clocked::curCycle(), m_deadlock_threshold, m_last_progress_vector, and panic.
Referenced by wakeup().
clearStats()
void RubyTester::clearStats () inline
Definition at line 114 of file RubyTester.hh.
getCheckFlush()
bool RubyTester::getCheckFlush () inline
Definition at line 118 of file RubyTester.hh.
References m_check_flush.
Referenced by Check::initiate().
getPort()
Port & RubyTester::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 132 of file RubyTester.cc.
References SimObject::getPort(), m_num_inst_data_ports, m_num_inst_only_ports, panic, and readPorts.
getReadableCpuPort()
MasterPort * RubyTester::getReadableCpuPort (int idx)
Definition at line 207 of file RubyTester.cc.
References readPorts.
Referenced by Check::initiateCheck(), and Check::initiatePrefetch().
getWritableCpuPort()
MasterPort * RubyTester::getWritableCpuPort (int idx)
Definition at line 215 of file RubyTester.cc.
References writePorts.
Referenced by Check::initiateAction(), and Check::initiateFlush().
hitCallback()
void RubyTester::hitCallback (NodeID proc, SubBlock * data) private
Definition at line 223 of file RubyTester.cc.
References Clocked::curCycle(), DPRINTF, DPRINTFR, SubBlock::getAddress(), SubBlock::getByte(), CheckTable::getCheck(), SubBlock::getSize(), m_checkTable_ptr, m_last_progress_vector, and Check::performCallback().
incrementCheckCompletions()
void RubyTester::incrementCheckCompletions () inline
Definition at line 111 of file RubyTester.hh.
References m_checks_completed.
Referenced by Check::performCallback().
init()
void RubyTester::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 115 of file RubyTester.cc.
References ArmISA::i, m_checkTable_ptr, m_last_progress_vector, m_num_cpus, m_num_readers, m_num_writers, readPorts, and writePorts.
isInstDataCpuPort()
bool RubyTester::isInstDataCpuPort (int idx)
Definition at line 200 of file RubyTester.cc.
References m_num_inst_data_ports, and m_num_inst_only_ports.
Referenced by Check::initiateCheck(), and Check::initiatePrefetch().
isInstOnlyCpuPort()
bool RubyTester::isInstOnlyCpuPort (int idx)
Definition at line 194 of file RubyTester.cc.
References m_num_inst_only_ports.
Referenced by Check::initiateCheck(), and Check::initiatePrefetch().
masterId()
MasterID RubyTester::masterId () inline
Definition at line 120 of file RubyTester.hh.
References _masterId.
Referenced by Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), and Check::initiatePrefetch().
operator=()
RubyTester& RubyTester::operator= (const RubyTester & obj) private
print()
void RubyTester::print (std::ostream & out) const
Definition at line 277 of file RubyTester.cc.
References RubyTester().
Referenced by operator<<(), and printConfig().
printConfig()
void RubyTester::printConfig (std::ostream & out) const inline
Definition at line 115 of file RubyTester.hh.
References print().
printStats()
void RubyTester::printStats (std::ostream & out) const inline
Definition at line 113 of file RubyTester.hh.
wakeup()
void RubyTester::wakeup ()
Definition at line 244 of file RubyTester.cc.
References checkForDeadlock(), checkStartEvent, curTick(), exitSimLoop(), CheckTable::getRandomCheck(), Check::initiate(), m_checks_completed, m_checks_to_complete, m_checkTable_ptr, m_wakeup_frequency, and EventManager::schedule().
Referenced by RubyTester().
Member Data Documentation
_masterId
MasterID RubyTester::_masterId protected
Definition at line 124 of file RubyTester.hh.
Referenced by masterId(), and RubyTester().
checkStartEvent
EventFunctionWrapper RubyTester::checkStartEvent protected
Definition at line 122 of file RubyTester.hh.
Referenced by RubyTester(), and wakeup().
m_check_flush
bool RubyTester::m_check_flush private
Definition at line 147 of file RubyTester.hh.
Referenced by getCheckFlush(), and RubyTester().
m_checks_completed
uint64_t RubyTester::m_checks_completed private
Definition at line 139 of file RubyTester.hh.
Referenced by incrementCheckCompletions(), RubyTester(), and wakeup().
m_checks_to_complete
uint64_t RubyTester::m_checks_to_complete private
Definition at line 142 of file RubyTester.hh.
Referenced by RubyTester(), and wakeup().
m_checkTable_ptr
CheckTable* RubyTester::m_checkTable_ptr private
Definition at line 135 of file RubyTester.hh.
Referenced by hitCallback(), init(), RubyTester(), wakeup(), and ~RubyTester().
m_deadlock_threshold
int RubyTester::m_deadlock_threshold private
Definition at line 143 of file RubyTester.hh.
Referenced by checkForDeadlock(), and RubyTester().
m_last_progress_vector
std::vector<Cycles> RubyTester::m_last_progress_vector private
Definition at line 136 of file RubyTester.hh.
Referenced by checkForDeadlock(), hitCallback(), and init().
m_num_cpus
int RubyTester::m_num_cpus private
Definition at line 138 of file RubyTester.hh.
Referenced by init(), and RubyTester().
m_num_inst_data_ports
int RubyTester::m_num_inst_data_ports private
Definition at line 149 of file RubyTester.hh.
Referenced by getPort(), isInstDataCpuPort(), and RubyTester().
m_num_inst_only_ports
int RubyTester::m_num_inst_only_ports private
Definition at line 148 of file RubyTester.hh.
Referenced by getPort(), isInstDataCpuPort(), isInstOnlyCpuPort(), and RubyTester().
m_num_readers
int RubyTester::m_num_readers private
Definition at line 145 of file RubyTester.hh.
Referenced by init(), and RubyTester().
m_num_writers
int RubyTester::m_num_writers private
Definition at line 144 of file RubyTester.hh.
Referenced by init(), and RubyTester().
m_wakeup_frequency
int RubyTester::m_wakeup_frequency private
Definition at line 146 of file RubyTester.hh.
Referenced by RubyTester(), and wakeup().
readPorts
std::vector<MasterPort*> RubyTester::readPorts private
Definition at line 141 of file RubyTester.hh.
Referenced by getPort(), getReadableCpuPort(), init(), RubyTester(), and ~RubyTester().
writePorts
std::vector<MasterPort*> RubyTester::writePorts private
Definition at line 140 of file RubyTester.hh.
Referenced by getWritableCpuPort(), init(), and RubyTester().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/RubyTester.hh
cpu/testers/rubytest/RubyTester.cc