gem5: Minor::LSQ::SingleDataRequest Class Reference
Minor::LSQ::SingleDataRequest Class Reference
SingleDataRequest is used for requests that don't fragment.
#include <lsq.hh>
Public Member Functions
void startAddrTranslation ()
Send single translation request.
PacketPtr getHeadPacket ()
Get the head packet as counted by numIssuedFragments.
void stepToNextPacket ()
Remember that the packet has been sent.
bool hasPacketsInMemSystem ()
Has packet been sent.
bool sentAllPackets ()
packetInFlight can become false again, so need to check packetSent
void retireResponse (PacketPtr packet_)
Keep the given packet as the response packet LSQRequest::packet.
SingleDataRequest (LSQ &port_, MinorDynInstPtr inst_, bool isLoad_, PacketDataPtr data_=NULL, uint64_t *res_=NULL)
Public Member Functions inherited from Minor::LSQ::LSQRequest
LSQRequest (LSQ &port_, MinorDynInstPtr inst_, bool isLoad_, PacketDataPtr data_=NULL, uint64_t *res_=NULL)
virtual ~LSQRequest ()
void makePacket ()
Make a packet to use with the memory transaction.
bool skippedMemAccess ()
Was no memory access attempted for this request?
void setSkipped ()
Set this request as having been skipped before a memory transfer was attempt.
AddrRangeCoverage containsAddrRangeOf (LSQRequest *other_request)
Does this request's address range fully cover the range of other_request?
virtual bool isBarrier ()
Is this a request a barrier?
bool needsToBeSentToStoreBuffer ()
This request, once processed by the requests/transfers queues, will need to go to the store buffer.
void setState (LSQRequestState new_state)
Set state and output trace output.
bool isComplete () const
Has this request been completed.
void reportData (std::ostream &os) const
MinorTrace report interface.
Public Member Functions inherited from BaseTLB::Translation
virtual ~Translation ()
virtual bool squashed () const
This function is used by the page table walker to determine if it should translate the a pending request or if the underlying request has been squashed.
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Protected Member Functions
void finish (const Fault &fault_, const RequestPtr &request_, ThreadContext *tc, BaseTLB::Mode mode)
TLB interace.
Protected Member Functions inherited from Minor::LSQ::LSQRequest
void markDelayed ()
BaseTLB::Translation interface.
void tryToSuppressFault ()
Instructions may want to suppress translation faults (e.g.
void disableMemAccess ()
void completeDisabledMemAccess ()
Protected Attributes
bool packetInFlight
Has my only packet been sent to the memory system but has not yet been responded to.
bool packetSent
Has the packet been at least sent to the memory system?
Additional Inherited Members
Public Types inherited from Minor::LSQ::LSQRequest
enum LSQRequestState {
NotIssued, InTranslation, Translated, Failed,
RequestIssuing, StoreToStoreBuffer, RequestNeedsRetry, StoreInStoreBuffer,
StoreBufferIssuing, StoreBufferNeedsRetry, Complete
}
Static Public Member Functions inherited from Minor::LSQ::LSQRequest
static AddrRangeCoverage containsAddrRangeOf (Addr req1_addr, unsigned int req1_size, Addr req2_addr, unsigned int req2_size)
Does address range req1 (req1_addr to req1_addr + req1_size - 1) fully cover, partially cover or not cover at all the range req2.
Public Attributes inherited from Minor::LSQ::LSQRequest
LSQ & port
Owning port.
MinorDynInstPtr inst
Instruction which made this request.
bool isLoad
Load/store indication used for building packet.
PacketDataPtr data
Dynamically allocated and populated data carried for building write packets.
PacketPtr packet
RequestPtr request
The underlying request of this LSQRequest.
uint64_t * res
Res from pushRequest.
bool skipped
Was skipped.
bool issuedToMemory
This in an access other than a normal cacheable load that's visited the memory system.
bool isTranslationDelayed
Address translation is delayed due to table walk.
LSQRequestState state
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Detailed Description
SingleDataRequest is used for requests that don't fragment.
Definition at line 339 of file lsq.hh.
Constructor & Destructor Documentation
SingleDataRequest()
Minor::LSQ::SingleDataRequest::SingleDataRequest (LSQ & port_, MinorDynInstPtr inst_, bool isLoad_, PacketDataPtr data_ = NULL, uint64_t * res_ = NULL) inline
Definition at line 375 of file lsq.hh.
Member Function Documentation
finish()
void LSQ< Impl >::SingleDataRequest::finish (const Fault & fault_, const RequestPtr & request_, ThreadContext * tc, BaseTLB::Mode mode) protected virtual
TLB interace.
Implements BaseTLB::Translation.
Definition at line 263 of file lsq.cc.
References Minor::LSQ::LSQRequest::Complete, Minor::LSQ::LSQRequest::completeDisabledMemAccess(), Minor::LSQ::cpu, DPRINTFS, Minor::Pipeline::ExecuteStageId, Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::isTranslationDelayed, Minor::LSQ::LSQRequest::makePacket(), NoFault, Minor::LSQ::numAccessesInDTLB, Minor::LSQ::LSQRequest::port, Minor::LSQ::LSQRequest::setState(), Minor::LSQ::LSQRequest::Translated, Minor::LSQ::tryToSendToTransfers(), Minor::LSQ::LSQRequest::tryToSuppressFault(), and MinorCPU::wakeupOnEvent().
getHeadPacket()
PacketPtr Minor::LSQ::SingleDataRequest::getHeadPacket () inline virtual
Get the head packet as counted by numIssuedFragments.
Implements Minor::LSQ::LSQRequest.
Definition at line 358 of file lsq.hh.
hasPacketsInMemSystem()
bool Minor::LSQ::SingleDataRequest::hasPacketsInMemSystem () inline virtual
Has packet been sent.
Implements Minor::LSQ::LSQRequest.
Definition at line 364 of file lsq.hh.
retireResponse()
void LSQ< Impl >::SingleDataRequest::retireResponse (PacketPtr packet_) virtual
Keep the given packet as the response packet LSQRequest::packet.
Implements Minor::LSQ::LSQRequest.
Definition at line 318 of file lsq.cc.
References Minor::LSQ::LSQRequest::Complete, DPRINTFS, Minor::LSQ::LSQRequest::packet, Minor::LSQ::LSQRequest::port, and Minor::LSQ::LSQRequest::setState().
sentAllPackets()
bool Minor::LSQ::SingleDataRequest::sentAllPackets () inline virtual
packetInFlight can become false again, so need to check packetSent
Implements Minor::LSQ::LSQRequest.
Definition at line 368 of file lsq.hh.
startAddrTranslation()
void LSQ< Impl >::SingleDataRequest::startAddrTranslation () virtual
Send single translation request.
Implements Minor::LSQ::LSQRequest.
Definition at line 293 of file lsq.cc.
References Minor::LSQ::LSQRequest::Complete, Minor::LSQ::cpu, Minor::LSQ::LSQRequest::disableMemAccess(), DPRINTFS, BaseCPU::getContext(), ThreadContext::getDTBPtr(), Minor::LSQ::LSQRequest::inst, Minor::LSQ::LSQRequest::InTranslation, isAnyActiveElement(), Minor::LSQ::LSQRequest::isLoad, Minor::LSQ::numAccessesInDTLB, Minor::LSQ::LSQRequest::port, BaseTLB::Read, Minor::LSQ::LSQRequest::request, Minor::LSQ::LSQRequest::setState(), BaseTLB::translateTiming(), and BaseTLB::Write.
stepToNextPacket()
void Minor::LSQ::SingleDataRequest::stepToNextPacket () inline virtual
Remember that the packet has been sent.
Implements Minor::LSQ::LSQRequest.
Definition at line 361 of file lsq.hh.
Member Data Documentation
packetInFlight
bool Minor::LSQ::SingleDataRequest::packetInFlight protected
Has my only packet been sent to the memory system but has not yet been responded to.
Definition at line 348 of file lsq.hh.
packetSent
bool Minor::LSQ::SingleDataRequest::packetSent protected
Has the packet been at least sent to the memory system?
Definition at line 351 of file lsq.hh.
The documentation for this class was generated from the following files:
cpu/minor/lsq.hh
cpu/minor/lsq.cc