gem5: SimpleLTInitiator1_dmi Class Reference
SimpleLTInitiator1_dmi Class Reference
#include <SimpleLTInitiator1_DMI.h>
Public Types
typedef tlm::tlm_generic_payload transaction_type
typedef tlm::tlm_dmi dmi_type
typedef tlm::tlm_phase phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef tlm::tlm_fw_transport_if fw_interface_type
typedef tlm::tlm_bw_transport_if bw_interface_type
typedef tlm::tlm_initiator_socket initiator_socket_type
Public Member Functions
SC_HAS_PROCESS (SimpleLTInitiator1_dmi)
SimpleLTInitiator1_dmi (sc_core::sc_module_name name, unsigned int nrOfTransactions=0x5, unsigned int baseAddress=0x0)
bool initTransaction (transaction_type &trans)
void logStartTransation (transaction_type &trans)
void logEndTransaction (transaction_type &trans)
void run ()
sync_enum_type nb_transport_bw (transaction_type &trans, phase_type &phase, sc_core::sc_time &t)
void invalidate (dmi_type &dmiData)
void invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range)
void end_of_simulation ()
Public Member Functions inherited from sc_core::sc_module
virtual ::Port & gem5_getPort (const std::string &if_name, int idx=-1)
virtual ~sc_module ()
virtual const char * kind () const
void operator() (const sc_bind_proxy &p001, const sc_bind_proxy &p002=SC_BIND_PROXY_NIL, const sc_bind_proxy &p003=SC_BIND_PROXY_NIL, const sc_bind_proxy &p004=SC_BIND_PROXY_NIL, const sc_bind_proxy &p005=SC_BIND_PROXY_NIL, const sc_bind_proxy &p006=SC_BIND_PROXY_NIL, const sc_bind_proxy &p007=SC_BIND_PROXY_NIL, const sc_bind_proxy &p008=SC_BIND_PROXY_NIL, const sc_bind_proxy &p009=SC_BIND_PROXY_NIL, const sc_bind_proxy &p010=SC_BIND_PROXY_NIL, const sc_bind_proxy &p011=SC_BIND_PROXY_NIL, const sc_bind_proxy &p012=SC_BIND_PROXY_NIL, const sc_bind_proxy &p013=SC_BIND_PROXY_NIL, const sc_bind_proxy &p014=SC_BIND_PROXY_NIL, const sc_bind_proxy &p015=SC_BIND_PROXY_NIL, const sc_bind_proxy &p016=SC_BIND_PROXY_NIL, const sc_bind_proxy &p017=SC_BIND_PROXY_NIL, const sc_bind_proxy &p018=SC_BIND_PROXY_NIL, const sc_bind_proxy &p019=SC_BIND_PROXY_NIL, const sc_bind_proxy &p020=SC_BIND_PROXY_NIL, const sc_bind_proxy &p021=SC_BIND_PROXY_NIL, const sc_bind_proxy &p022=SC_BIND_PROXY_NIL, const sc_bind_proxy &p023=SC_BIND_PROXY_NIL, const sc_bind_proxy &p024=SC_BIND_PROXY_NIL, const sc_bind_proxy &p025=SC_BIND_PROXY_NIL, const sc_bind_proxy &p026=SC_BIND_PROXY_NIL, const sc_bind_proxy &p027=SC_BIND_PROXY_NIL, const sc_bind_proxy &p028=SC_BIND_PROXY_NIL, const sc_bind_proxy &p029=SC_BIND_PROXY_NIL, const sc_bind_proxy &p030=SC_BIND_PROXY_NIL, const sc_bind_proxy &p031=SC_BIND_PROXY_NIL, const sc_bind_proxy &p032=SC_BIND_PROXY_NIL, const sc_bind_proxy &p033=SC_BIND_PROXY_NIL, const sc_bind_proxy &p034=SC_BIND_PROXY_NIL, const sc_bind_proxy &p035=SC_BIND_PROXY_NIL, const sc_bind_proxy &p036=SC_BIND_PROXY_NIL, const sc_bind_proxy &p037=SC_BIND_PROXY_NIL, const sc_bind_proxy &p038=SC_BIND_PROXY_NIL, const sc_bind_proxy &p039=SC_BIND_PROXY_NIL, const sc_bind_proxy &p040=SC_BIND_PROXY_NIL, const sc_bind_proxy &p041=SC_BIND_PROXY_NIL, const sc_bind_proxy &p042=SC_BIND_PROXY_NIL, const sc_bind_proxy &p043=SC_BIND_PROXY_NIL, const sc_bind_proxy &p044=SC_BIND_PROXY_NIL, const sc_bind_proxy &p045=SC_BIND_PROXY_NIL, const sc_bind_proxy &p046=SC_BIND_PROXY_NIL, const sc_bind_proxy &p047=SC_BIND_PROXY_NIL, const sc_bind_proxy &p048=SC_BIND_PROXY_NIL, const sc_bind_proxy &p049=SC_BIND_PROXY_NIL, const sc_bind_proxy &p050=SC_BIND_PROXY_NIL, const sc_bind_proxy &p051=SC_BIND_PROXY_NIL, const sc_bind_proxy &p052=SC_BIND_PROXY_NIL, const sc_bind_proxy &p053=SC_BIND_PROXY_NIL, const sc_bind_proxy &p054=SC_BIND_PROXY_NIL, const sc_bind_proxy &p055=SC_BIND_PROXY_NIL, const sc_bind_proxy &p056=SC_BIND_PROXY_NIL, const sc_bind_proxy &p057=SC_BIND_PROXY_NIL, const sc_bind_proxy &p058=SC_BIND_PROXY_NIL, const sc_bind_proxy &p059=SC_BIND_PROXY_NIL, const sc_bind_proxy &p060=SC_BIND_PROXY_NIL, const sc_bind_proxy &p061=SC_BIND_PROXY_NIL, const sc_bind_proxy &p062=SC_BIND_PROXY_NIL, const sc_bind_proxy &p063=SC_BIND_PROXY_NIL, const sc_bind_proxy &p064=SC_BIND_PROXY_NIL)
sc_module & operator<< (sc_interface &)
sc_module & operator<< (sc_port_base &)
sc_module & operator, (sc_interface &)
sc_module & operator, (sc_port_base &)
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from tlm::tlm_bw_nonblocking_transport_if< tlm_base_protocol_types ::tlm_payload_type, tlm_base_protocol_types ::tlm_phase_type >
virtual tlm_sync_enum nb_transport_bw (tlm_base_protocol_types ::tlm_payload_type &trans, tlm_base_protocol_types ::tlm_phase_type &phase, sc_core::sc_time &t)=0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Public Attributes
initiator_socket_type socket
Private Attributes
dmi_type mDMIData
sc_core::sc_event mEndEvent
unsigned int mNrOfTransactions
unsigned int mBaseAddress
unsigned int mTransactionCount
unsigned int mData
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_module
sc_module (const sc_module_name &)
sc_module ()
sc_module (const char *)
sc_module (const std::string &)
void end_module ()
void reset_signal_is (const sc_in< bool > &, bool)
void reset_signal_is (const sc_inout< bool > &, bool)
void reset_signal_is (const sc_out< bool > &, bool)
void reset_signal_is (const sc_signal_in_if< bool > &, bool)
void async_reset_signal_is (const sc_in< bool > &, bool)
void async_reset_signal_is (const sc_inout< bool > &, bool)
void async_reset_signal_is (const sc_out< bool > &, bool)
void async_reset_signal_is (const sc_signal_in_if< bool > &, bool)
void dont_initialize ()
void set_stack_size (size_t)
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
void halt ()
void at_posedge (const sc_signal_in_if< bool > &)
void at_posedge (const sc_signal_in_if< sc_dt::sc_logic > &)
void at_negedge (const sc_signal_in_if< bool > &)
void at_negedge (const sc_signal_in_if< sc_dt::sc_logic > &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Attributes inherited from sc_core::sc_module
sc_sensitive sensitive
Detailed Description
Definition at line 41 of file SimpleLTInitiator1_DMI.h.
Member Typedef Documentation
bw_interface_type
typedef tlm::tlm_bw_transport_if SimpleLTInitiator1_dmi::bw_interface_type
Definition at line 51 of file SimpleLTInitiator1_DMI.h.
dmi_type
typedef tlm::tlm_dmi SimpleLTInitiator1_dmi::dmi_type
Definition at line 47 of file SimpleLTInitiator1_DMI.h.
fw_interface_type
typedef tlm::tlm_fw_transport_if SimpleLTInitiator1_dmi::fw_interface_type
Definition at line 50 of file SimpleLTInitiator1_DMI.h.
initiator_socket_type
typedef tlm::tlm_initiator_socket SimpleLTInitiator1_dmi::initiator_socket_type
Definition at line 52 of file SimpleLTInitiator1_DMI.h.
phase_type
typedef tlm::tlm_phase SimpleLTInitiator1_dmi::phase_type
Definition at line 48 of file SimpleLTInitiator1_DMI.h.
sync_enum_type
typedef tlm::tlm_sync_enum SimpleLTInitiator1_dmi::sync_enum_type
Definition at line 49 of file SimpleLTInitiator1_DMI.h.
transaction_type
typedef tlm::tlm_generic_payload SimpleLTInitiator1_dmi::transaction_type
Definition at line 46 of file SimpleLTInitiator1_DMI.h.
Constructor & Destructor Documentation
SimpleLTInitiator1_dmi()
SimpleLTInitiator1_dmi::SimpleLTInitiator1_dmi (sc_core::sc_module_name name, unsigned int nrOfTransactions = 0x5, unsigned int baseAddress = 0x0) inline
Definition at line 59 of file SimpleLTInitiator1_DMI.h.
References invalidate(), mDMIData, run(), SC_THREAD, and socket.
Member Function Documentation
end_of_simulation()
void SimpleLTInitiator1_dmi::end_of_simulation () inline virtual
Reimplemented from sc_core::sc_module.
Definition at line 242 of file SimpleLTInitiator1_DMI.h.
References data, tlm::host_has_little_endianness(), ArmISA::i, ArmISA::j, MipsISA::k, mBaseAddress, ArmISA::n, sc_core::sc_object::name(), tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), and tlm::tlm_generic_payload::set_read().
initTransaction()
bool SimpleLTInitiator1_dmi::initTransaction (transaction_type & trans) inline
Definition at line 77 of file SimpleLTInitiator1_DMI.h.
References mBaseAddress, mData, mNrOfTransactions, mTransactionCount, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_command(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), tlm::tlm_generic_payload::set_dmi_allowed(), tlm::tlm_generic_payload::set_streaming_width(), tlm::TLM_READ_COMMAND, and tlm::TLM_WRITE_COMMAND.
Referenced by run().
invalidate()
void SimpleLTInitiator1_dmi::invalidate (dmi_type & dmiData) inline
Definition at line 215 of file SimpleLTInitiator1_DMI.h.
References tlm::tlm_dmi::set_end_address(), and tlm::tlm_dmi::set_start_address().
Referenced by invalidate_direct_mem_ptr(), and SimpleLTInitiator1_dmi().
invalidate_direct_mem_ptr()
void SimpleLTInitiator1_dmi::invalidate_direct_mem_ptr (sc_dt::uint64 start_range, sc_dt::uint64 end_range) inline virtual
Implements tlm::tlm_bw_direct_mem_if.
Definition at line 222 of file SimpleLTInitiator1_DMI.h.
References tlm::tlm_dmi::get_end_address(), tlm::tlm_dmi::get_start_address(), invalidate(), mDMIData, sc_core::sc_object::name(), and sc_core::sc_time_stamp().
logEndTransaction()
void SimpleLTInitiator1_dmi::logEndTransaction (transaction_type & trans) inline
Definition at line 119 of file SimpleLTInitiator1_DMI.h.
References tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_response_status(), mData, sc_core::sc_object::name(), sc_core::sc_time_stamp(), tlm::TLM_OK_RESPONSE, and tlm::TLM_READ_COMMAND.
Referenced by run().
logStartTransation()
void SimpleLTInitiator1_dmi::logStartTransation (transaction_type & trans) inline
Definition at line 104 of file SimpleLTInitiator1_DMI.h.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), mData, sc_core::sc_object::name(), sc_core::sc_time_stamp(), and tlm::TLM_WRITE_COMMAND.
Referenced by run().
nb_transport_bw()
sync_enum_type SimpleLTInitiator1_dmi::nb_transport_bw (transaction_type & trans, phase_type & phase, sc_core::sc_time & t) inline
Definition at line 208 of file SimpleLTInitiator1_DMI.h.
References tlm::TLM_COMPLETED.
run()
void SimpleLTInitiator1_dmi::run () inline
Definition at line 134 of file SimpleLTInitiator1_DMI.h.
References addr, tlm::BEGIN_REQ, tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), tlm::tlm_dmi::get_dmi_ptr(), tlm::tlm_dmi::get_end_address(), tlm::tlm_dmi::get_read_latency(), tlm::tlm_dmi::get_start_address(), tlm::tlm_dmi::get_write_latency(), tlm::tlm_dmi::init(), initTransaction(), tlm::tlm_generic_payload::is_dmi_allowed(), tlm::tlm_dmi::is_write_allowed(), logEndTransaction(), logStartTransation(), mData, mDMIData, sc_core::SC_ZERO_TIME, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_response_status(), tlm::tlm_generic_payload::set_write(), ArmISA::t, tlm::TLM_OK_RESPONSE, tlm::TLM_WRITE_COMMAND, and sc_core::sc_module::wait().
Referenced by SimpleLTInitiator1_dmi().
SC_HAS_PROCESS()
SimpleLTInitiator1_dmi::SC_HAS_PROCESS (SimpleLTInitiator1_dmi)
Member Data Documentation
mBaseAddress
unsigned int SimpleLTInitiator1_dmi::mBaseAddress private
Definition at line 300 of file SimpleLTInitiator1_DMI.h.
Referenced by end_of_simulation(), and initTransaction().
mData
unsigned int SimpleLTInitiator1_dmi::mData private
Definition at line 302 of file SimpleLTInitiator1_DMI.h.
Referenced by initTransaction(), logEndTransaction(), logStartTransation(), and run().
mDMIData
dmi_type SimpleLTInitiator1_dmi::mDMIData private
Definition at line 296 of file SimpleLTInitiator1_DMI.h.
Referenced by invalidate_direct_mem_ptr(), run(), and SimpleLTInitiator1_dmi().
mEndEvent
sc_core::sc_event SimpleLTInitiator1_dmi::mEndEvent private
Definition at line 298 of file SimpleLTInitiator1_DMI.h.
mNrOfTransactions
unsigned int SimpleLTInitiator1_dmi::mNrOfTransactions private
Definition at line 299 of file SimpleLTInitiator1_DMI.h.
Referenced by initTransaction().
mTransactionCount
unsigned int SimpleLTInitiator1_dmi::mTransactionCount private
Definition at line 301 of file SimpleLTInitiator1_DMI.h.
Referenced by initTransaction().
socket
initiator_socket_type SimpleLTInitiator1_dmi::socket
Definition at line 55 of file SimpleLTInitiator1_DMI.h.
Referenced by SimpleLTInitiator1_dmi().
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleLTInitiator1_DMI.h