gem5: tlm::tlm_global_quantum Class Reference
tlm::tlm_global_quantum Class Reference
#include <global_quantum.hh>
Public Member Functions
void set (const sc_core::sc_time &t)
const sc_core::sc_time & get () const
sc_core::sc_time compute_local_quantum ()
Static Public Member Functions
static tlm_global_quantum & instance ()
Protected Member Functions
tlm_global_quantum ()
Protected Attributes
sc_core::sc_time m_global_quantum
Detailed Description
Definition at line 42 of file global_quantum.hh.
Constructor & Destructor Documentation
tlm_global_quantum()
tlm::tlm_global_quantum::tlm_global_quantum () protected
Definition at line 27 of file global_quantum.cc.
Referenced by get().
Member Function Documentation
compute_local_quantum()
sc_core::sc_time tlm::tlm_global_quantum::compute_local_quantum ()
Definition at line 39 of file global_quantum.cc.
References sc_core::sc_time::from_value(), m_global_quantum, sc_core::sc_time_stamp(), sc_core::SC_ZERO_TIME, and sc_core::sc_time::value().
Referenced by tlm_utils::tlm_quantumkeeper::compute_local_quantum(), and get().
get()
const sc_core::sc_time& tlm::tlm_global_quantum::get () const inline
Definition at line 56 of file global_quantum.hh.
References compute_local_quantum(), m_global_quantum, and tlm_global_quantum().
Referenced by tlm_utils::tlm_quantumkeeper::get_global_quantum().
instance()
tlm_global_quantum & tlm::tlm_global_quantum::instance () static
Definition at line 32 of file global_quantum.cc.
References instance_.
Referenced by tlm_utils::tlm_quantumkeeper::compute_local_quantum(), tlm_utils::tlm_quantumkeeper::get_global_quantum(), and tlm_utils::tlm_quantumkeeper::set_global_quantum().
set()
void tlm::tlm_global_quantum::set (const sc_core::sc_time & t) inline
Definition at line 55 of file global_quantum.hh.
References m_global_quantum, and ArmISA::t.
Referenced by tlm_utils::tlm_quantumkeeper::set_global_quantum().
Member Data Documentation
m_global_quantum
sc_core::sc_time tlm::tlm_global_quantum::m_global_quantum protected
Definition at line 71 of file global_quantum.hh.
Referenced by compute_local_quantum(), get(), and set().
The documentation for this class was generated from the following files:
systemc/ext/tlm_core/2/quantum/global_quantum.hh
systemc/tlm_core/2/quantum/global_quantum.cc