gem5: TAGE_SC_L_TAGE_64KB Class Reference
TAGE_SC_L_TAGE_64KB Class Reference
#include <tage_sc_l_64KB.hh>
Public Member Functions
TAGE_SC_L_TAGE_64KB (const TAGE_SC_L_TAGE_64KBParams *p)
int gindex_ext (int index, int bank) const override
uint16_t gtag (ThreadID tid, Addr pc, int bank) const override
Computes the partial tag of a tagged table.
void handleAllocAndUReset (bool alloc, bool taken, TAGEBase::BranchInfo *bi, int nrand) override
Handles Allocation and U bits reset on an update.
void handleTAGEUpdate (Addr branch_pc, bool taken, TAGEBase::BranchInfo *bi) override
Handles the update of the TAGE entries.
Public Member Functions inherited from TAGE_SC_L_TAGE
virtual TAGEBase::BranchInfo * makeBranchInfo () override
TAGE_SC_L_TAGE (const TAGE_SC_L_TAGEParams *p)
void calculateParameters () override
Calculates the history lengths and some other paramters in derived classes.
void buildTageTables () override
Instantiates the TAGE table entries.
void calculateIndicesAndTags (ThreadID tid, Addr branch_pc, TAGEBase::BranchInfo *bi) override
On a prediction, calculates the TAGE indices and tags for all the different history lengths.
unsigned getUseAltIdx (TAGEBase::BranchInfo *bi, Addr branch_pc) override
Calculation of the index for useAltPredForNewlyAllocated On this base TAGE implementation it is always 0.
void updateHistories (ThreadID tid, Addr branch_pc, bool taken, TAGEBase::BranchInfo *b, bool speculative, const StaticInstPtr &inst, Addr target) override
(Speculatively) updates global histories (path and direction).
int bindex (Addr pc_in) const override
Computes the index used to access the bimodal table.
int gindex (ThreadID tid, Addr pc, int bank) const override
Computes the index used to access a partially tagged table.
int F (int phist, int size, int bank) const override
Utility function to shuffle the path history depending on which tagged table we are accessing.
void squash (ThreadID tid, bool taken, TAGEBase::BranchInfo *bi, Addr target) override
Restores speculatively updated path and direction histories.
void updatePathAndGlobalHistory (ThreadHistory &tHist, int brtype, bool taken, Addr branch_pc, Addr target)
void adjustAlloc (bool &alloc, bool taken, bool pred_taken) override
Extra calculation to tell whether TAGE allocaitons may happen or not on an update For this base TAGE implementation it does nothing.
void handleUReset () override
Handles the U bits reset.
int calcDep (TAGEBase::BranchInfo *bi)
bool getBimodePred (Addr branch_pc, TAGEBase::BranchInfo *tage_bi) const override
Get a branch prediction from the bimodal predictor.
void extraAltCalc (TAGEBase::BranchInfo *bi) override
Extra steps for calculating altTaken For this base TAGE class it does nothing.
Public Member Functions inherited from TAGEBase
TAGEBase (const TAGEBaseParams *p)
void regStats () override
Callback to set stat parameters.
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void baseUpdate (Addr pc, bool taken, BranchInfo *bi)
Updates the bimodal predictor.
void updateGHist (uint8_t *&h, bool dir, uint8_t *tab, int &PT)
(Speculatively) updates the global branch history.
void update (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *bi)
Update TAGE.
virtual void condBranchUpdate (ThreadID tid, Addr branch_pc, bool taken, BranchInfo *bi, int nrand, Addr corrTarget, bool pred, bool preAdjustAlloc=false)
Update TAGE for conditional branches.
bool tagePredict (ThreadID tid, Addr branch_pc, bool cond_branch, BranchInfo *bi)
TAGE prediction called from TAGE::predict.
virtual void updateStats (bool taken, BranchInfo *bi)
Update the stats.
virtual void resetUctr (uint8_t &u)
Algorithm for resetting a single U counter.
virtual bool isHighConfidence (BranchInfo *bi) const
void btbUpdate (ThreadID tid, Addr branch_addr, BranchInfo *&bi)
unsigned getGHR (ThreadID tid, BranchInfo *bi) const
int8_t getCtr (int hitBank, int hitBankIndex) const
unsigned getTageCtrBits () const
int getPathHist (ThreadID tid) const
bool isSpeculativeUpdateEnabled () const
size_t getSizeInBits () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Additional Inherited Members
Public Types inherited from TAGEBase
enum {
BIMODAL_ONLY = 0, TAGE_LONGEST_MATCH, BIMODAL_ALT_MATCH, TAGE_ALT_MATCH,
LAST_TAGE_PROVIDER_TYPE = TAGE_ALT_MATCH
}
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from TAGEBase
template<typename T >
static void ctrUpdate (T &ctr, bool taken, int nbits)
Updates a direction counter based on the actual branch outcome.
static void unsignedCtrUpdate (uint8_t &ctr, bool up, unsigned nbits)
Updates an unsigned counter based on up/down parameter.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from TAGEBase
virtual void initFoldedHistories (ThreadHistory &history)
Initialization of the folded histories.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from TAGEBase
const unsigned logRatioBiModalHystEntries
const unsigned nHistoryTables
const unsigned tagTableCounterBits
const unsigned tagTableUBits
const unsigned histBufferSize
const unsigned minHist
const unsigned maxHist
const unsigned pathHistBits
std::vector< unsigned > tagTableTagWidths
std::vector< int > logTagTableSizes
std::vector< bool > btablePrediction
std::vector< bool > btableHysteresis
TageEntry ** gtable
std::vector< ThreadHistory > threadHistory
int * histLengths
int * tableIndices
int * tableTags
std::vector< int8_t > useAltPredForNewlyAllocated
int64_t tCounter
uint64_t logUResetPeriod
const int64_t initialTCounterValue
unsigned numUseAltOnNa
unsigned useAltOnNaBits
unsigned maxNumAlloc
std::vector< bool > noSkip
const bool speculativeHistUpdate
const unsigned instShiftAmt
bool initialized
Stats::Scalar tageLongestMatchProviderCorrect
Stats::Scalar tageAltMatchProviderCorrect
Stats::Scalar bimodalAltMatchProviderCorrect
Stats::Scalar tageBimodalProviderCorrect
Stats::Scalar tageLongestMatchProviderWrong
Stats::Scalar tageAltMatchProviderWrong
Stats::Scalar bimodalAltMatchProviderWrong
Stats::Scalar tageBimodalProviderWrong
Stats::Scalar tageAltMatchProviderWouldHaveHit
Stats::Scalar tageLongestMatchProviderWouldHaveHit
Stats::Vector tageLongestMatchProvider
Stats::Vector tageAltMatchProvider
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 53 of file tage_sc_l_64KB.hh.
Constructor & Destructor Documentation
TAGE_SC_L_TAGE_64KB()
TAGE_SC_L_TAGE_64KB::TAGE_SC_L_TAGE_64KB (const TAGE_SC_L_TAGE_64KBParams * p) inline
Definition at line 55 of file tage_sc_l_64KB.hh.
References PowerISA::bi, gindex_ext(), gtag(), handleAllocAndUReset(), handleTAGEUpdate(), MipsISA::index, and MipsISA::pc.
Member Function Documentation
gindex_ext()
int TAGE_SC_L_TAGE_64KB::gindex_ext (int index, int bank) const override virtual
Implements TAGE_SC_L_TAGE.
Definition at line 200 of file tage_sc_l_64KB.cc.
References MipsISA::index.
Referenced by TAGE_SC_L_TAGE_64KB().
gtag()
uint16_t TAGE_SC_L_TAGE_64KB::gtag (ThreadID tid, Addr pc, int bank) const override virtual
Computes the partial tag of a tagged table.
Parameters
tid the thread ID used to select the global histories to use.
pc The unshifted branch PC.
bank The partially tagged table to access.
Implements TAGE_SC_L_TAGE.
Definition at line 206 of file tage_sc_l_64KB.cc.
References ULL.
Referenced by TAGE_SC_L_TAGE_64KB().
handleAllocAndUReset()
void TAGE_SC_L_TAGE_64KB::handleAllocAndUReset (bool alloc, bool taken, TAGEBase::BranchInfo * bi, int nrand) override virtual
Handles Allocation and U bits reset on an update.
Implements TAGE_SC_L_TAGE.
Definition at line 216 of file tage_sc_l_64KB.cc.
References ArmISA::i, ArmISA::j, TAGEBase::BranchInfo::tableIndices, and TAGEBase::BranchInfo::tableTags.
Referenced by TAGE_SC_L_TAGE_64KB().
handleTAGEUpdate()
void TAGE_SC_L_TAGE_64KB::handleTAGEUpdate (Addr branch_pc, bool taken, TAGEBase::BranchInfo * bi) override virtual
Handles the update of the TAGE entries.
Implements TAGE_SC_L_TAGE.
Definition at line 264 of file tage_sc_l_64KB.cc.
References TAGEBase::BranchInfo::altBank, TAGEBase::BranchInfo::altBankIndex, TAGEBase::BranchInfo::altTaken, StatisticalCorrector::ctrUpdate(), TAGEBase::BranchInfo::hitBank, TAGEBase::BranchInfo::hitBankIndex, and TAGEBase::BranchInfo::longestMatchPred.
Referenced by TAGE_SC_L_TAGE_64KB().
The documentation for this class was generated from the following files:
cpu/pred/tage_sc_l_64KB.hh
cpu/pred/tage_sc_l_64KB.cc