gem5: AnnotateDumpCallback Class Reference
AnnotateDumpCallback Class Reference
Public Member Functions
virtual void process ()
virtual process function that is invoked when the callback queue is executed.
AnnotateDumpCallback (CPA *_cpa)
Public Member Functions inherited from Callback
virtual ~Callback ()
virtualize the destructor to make sure that the correct one gets called.
Private Attributes
CPA * cpa
Additional Inherited Members
Protected Member Functions inherited from Callback
virtual void autoDestruct ()
Detailed Description
Definition at line 85 of file cp_annotate.cc.
Constructor & Destructor Documentation
AnnotateDumpCallback()
AnnotateDumpCallback::AnnotateDumpCallback (CPA * _cpa) inline
Definition at line 92 of file cp_annotate.cc.
Member Function Documentation
process()
void AnnotateDumpCallback::process () virtual
virtual process function that is invoked when the callback queue is executed.
Implements Callback.
Definition at line 98 of file cp_annotate.cc.
References Stats::_enabled, ArmISA::a, arrayParamOut(), ArmISA::b, ArmISA::c, ThreadContext::contextId(), X86ISA::count, MipsISA::cpuid, OutputDirectory::create(), createObjectFile(), csprintf(), Linux::ThreadInfo::curTaskName(), curTick(), ArmISA::d, data, debugSymbolTable, DPRINTF, DPRINTFN, DPRINTFS, Stats::dump(), Stats::enabled(), ArmISA::f, fatal, SymbolTable::findNearestSymbol(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), ArmISA::i, ArmISA::id, AlphaISA::inUserMode(), AlphaISA::IPR_PALtemp23, CPAIgnoreSymbol::len, PowerISA::li, ObjectFile::loadGlobalSymbols(), ObjectFile::loadLocalSymbols(), ArmISA::lsm, name(), SimObject::name(), PowerISA::ni, objParamIn(), X86ISA::of, X86ISA::op, X86ISA::os, MipsISA::p, panic, paramIn(), paramOut(), ArmISA::q, ThreadContext::readIntReg(), ThreadContext::readMiscRegNoEffect(), PortProxy::readString(), registerExitCallback(), AlphaISA::ReturnAddressReg, serialize(), SERIALIZE_SCALAR, X86ISA::sf, PowerISA::si, simout, MipsISA::sm, ArmISA::st, RiscvISA::sti, CPA::swAq(), CPA::swAutoBegin(), CPA::swDq(), CPA::swEnd(), CPA::swExplictBegin(), CPA::swGetId(), CPA::swIdentify(), CPA::swLink(), CPA::swPq(), CPA::swQ(), CPA::swRq(), CPA::swSmBegin(), CPA::swSmEnd(), CPA::swSq(), CPA::swSyscallLink(), CPA::swWe(), CPA::swWf(), CPAIgnoreSymbol::symbol, ArmISA::t, MipsISA::ti, ULL, unserialize(), UNSERIALIZE_CONTAINER, UNSERIALIZE_SCALAR, warn, and X86ISA::x.
Member Data Documentation
cpa
CPA* AnnotateDumpCallback::cpa private
Definition at line 89 of file cp_annotate.cc.
The documentation for this class was generated from the following file:
base/cp_annotate.cc