gem5: sc_dt::sc_fxnum_fast_bitref Class Reference
sc_dt::sc_fxnum_fast_bitref Class Reference
#include <sc_fxnum.hh>
Public Member Functions
sc_fxnum_fast_bitref (const sc_fxnum_fast_bitref &)
operator bool () const
void print (::std::ostream &=::std::cout) const
void scan (::std::istream &=::std::cin)
void dump (::std::ostream &=::std::cout) const
Private Member Functions
bool get () const
void set (bool)
sc_fxnum_fast_bitref (sc_fxnum_fast &, int)
sc_fxnum_fast_bitref ()
Private Attributes
sc_fxnum_fast & m_num
int m_idx
Friends
class sc_fxnum_fast
class sc_fxnum_bitref
Detailed Description
Definition at line 155 of file sc_fxnum.hh.
Constructor & Destructor Documentation
sc_fxnum_fast_bitref() [1/3]
sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref (sc_fxnum_fast & num_, int idx_) inline private
Definition at line 1398 of file sc_fxnum.hh.
sc_fxnum_fast_bitref() [2/3]
sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref (const sc_fxnum_fast_bitref & a) inline
Definition at line 1403 of file sc_fxnum.hh.
References ArmISA::a, sc_dt::sc_fxnum_bitref::get(), get(), sc_dt::sc_fxnum_bitref::m_num, m_num, sc_dt::operator&=(), sc_dt::operator^=(), sc_dt::operator|=(), SC_FXNUM_FAST_OBSERVER_READ_, SC_FXNUM_FAST_OBSERVER_WRITE_, and SC_FXNUM_OBSERVER_READ_.
sc_fxnum_fast_bitref() [3/3]
sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref () private
Member Function Documentation
dump()
void sc_dt::sc_fxnum_fast_bitref::dump (::std::ostream & os = ::std::cout) const
Definition at line 115 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::dump(), sc_dt::sc_fxnum_bitref::m_idx, and sc_dt::sc_fxnum_bitref::m_num.
get()
bool sc_dt::sc_fxnum_fast_bitref::get () const private
Definition at line 100 of file sc_fxnum.cc.
References sc_dt::sc_fxnum::get_bit(), sc_dt::sc_fxnum_bitref::m_idx, and sc_dt::sc_fxnum_bitref::m_num.
Referenced by sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), and sc_fxnum_fast_bitref().
operator bool()
sc_dt::sc_fxnum_fast_bitref::operator bool () const inline
Definition at line 1563 of file sc_fxnum.hh.
References m_num, and SC_FXNUM_FAST_OBSERVER_READ_.
print()
void sc_dt::sc_fxnum_fast_bitref::print (::std::ostream & os = ::std::cout) const
Definition at line 104 of file sc_fxnum.cc.
Referenced by sc_dt::operator<<().
scan()
void sc_dt::sc_fxnum_fast_bitref::scan (::std::istream & is = ::std::cin)
Definition at line 107 of file sc_fxnum.cc.
References ArmISA::b.
Referenced by sc_dt::operator>>().
set()
void sc_dt::sc_fxnum_fast_bitref::set (bool high) private
Definition at line 101 of file sc_fxnum.cc.
References sc_dt::sc_fxnum_bitref::m_idx, sc_dt::sc_fxnum_bitref::m_num, and sc_dt::sc_fxnum::set_bit().
Friends And Related Function Documentation
sc_fxnum_bitref
friend class sc_fxnum_bitref friend
Definition at line 158 of file sc_fxnum.hh.
sc_fxnum_fast
friend class sc_fxnum_fast friend
Definition at line 157 of file sc_fxnum.hh.
Member Data Documentation
m_idx
int sc_dt::sc_fxnum_fast_bitref::m_idx private
Definition at line 198 of file sc_fxnum.hh.
m_num
sc_fxnum_fast& sc_dt::sc_fxnum_fast_bitref::m_num private
Definition at line 197 of file sc_fxnum.hh.
Referenced by operator bool(), sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), and sc_fxnum_fast_bitref().
The documentation for this class was generated from the following files:
systemc/ext/dt/fx/sc_fxnum.hh
systemc/dt/fx/sc_fxnum.cc