gem5: PerfKvmTimer Class Reference
PerfKvmTimer Class Reference
PerfEvent based timer using the host's CPU cycle counter.
#include <timer.hh>
Public Member Functions
PerfKvmTimer (PerfKvmCounter &ctr, int signo, float hostFactor, Tick hostFreq)
Create a timer that uses an existing hardware cycle counter.
~PerfKvmTimer ()
void arm (Tick ticks)
Arm the timer so that it fires after a certain number of ticks.
void disarm ()
Disarm the timer.
Public Member Functions inherited from BaseKvmTimer
BaseKvmTimer (int signo, float hostFactor, Tick hostFreq)
Setup basic timer functionality shared by all timer implementations.
virtual ~BaseKvmTimer ()
Tick resolution ()
Determine the resolution of the timer in ticks.
Tick ticksFromHostCycles (uint64_t cycles)
Convert cycles executed on the host into Ticks executed in the simulator.
Tick ticksFromHostNs (uint64_t ns)
Convert nanoseconds executed on the host into Ticks executed in the simulator.
Protected Member Functions
Tick calcResolution ()
Calculate the timer resolution, used by resolution() which caches the result.
Protected Member Functions inherited from BaseKvmTimer
uint64_t hostNs (Tick ticks)
Convert a time in simulator ticks to host nanoseconds.
uint64_t hostCycles (Tick ticks)
Convert a time in simulator ticks to host cycles.
Private Attributes
PerfKvmCounter & hwOverflow
Additional Inherited Members
Protected Attributes inherited from BaseKvmTimer
int signo
Signal to deliver when the timer times out.
Detailed Description
PerfEvent based timer using the host's CPU cycle counter.
Warning
There is a known problem in some versions of the PerfEvent API that prevents the counter overflow period from being updated reliably, which might break this timer. See PerfKvmCounter::period() for details.
Definition at line 215 of file timer.hh.
Constructor & Destructor Documentation
PerfKvmTimer()
PerfKvmTimer::PerfKvmTimer (PerfKvmCounter & ctr, int signo, float hostFactor, Tick hostFreq)
Create a timer that uses an existing hardware cycle counter.
Note
The performance counter must be configured for overflow sampling, which in practice means that it must have a non-zero sample period. The initial sample period is ignored since period will be updated when arm() is called.
Parameters
ctr Attached performance counter configured for overflow reporting.
signo Signal to deliver
hostFactor Performance scaling factor
hostFreq Clock frequency of the host
Definition at line 161 of file timer.cc.
References PerfKvmCounter::enableSignals(), and hwOverflow.
~PerfKvmTimer()
PerfKvmTimer::~PerfKvmTimer ()
Definition at line 169 of file timer.cc.
Member Function Documentation
arm()
void PerfKvmTimer::arm (Tick ticks) virtual
Arm the timer so that it fires after a certain number of ticks.
Note
A timer implementation is free to convert between simulation ticks and virtualized time using any method it chooses. The accuracy of the timer therefore depends on what it measures, an accurate timer implementation should measure the number of cycles or instructions executed in the guest. If such counters are unavailable, it may fallback to wall clock time.
Parameters
ticks Number of ticks until the timer fires
Implements BaseKvmTimer.
Definition at line 174 of file timer.cc.
References BaseKvmTimer::hostCycles(), hwOverflow, PerfKvmCounter::period(), and PerfKvmCounter::refresh().
calcResolution()
Tick PerfKvmTimer::calcResolution () protected virtual
Calculate the timer resolution, used by resolution() which caches the result.
Returns
Minimum number of ticks the timer can resolve
Implements BaseKvmTimer.
Definition at line 187 of file timer.cc.
References MIN_HOST_CYCLES, and BaseKvmTimer::ticksFromHostCycles().
disarm()
void PerfKvmTimer::disarm () virtual
Disarm the timer.
When this method has returned, the timer may no longer deliver signals upon timeout.
Implements BaseKvmTimer.
Definition at line 181 of file timer.cc.
References hwOverflow, and PerfKvmCounter::stop().
Member Data Documentation
hwOverflow
PerfKvmCounter& PerfKvmTimer::hwOverflow private
Definition at line 244 of file timer.hh.
Referenced by arm(), disarm(), and PerfKvmTimer().
The documentation for this class was generated from the following files:
cpu/kvm/timer.hh
cpu/kvm/timer.cc