gem5: ThreadContext Class Reference
ThreadContext Class Reference abstract
ThreadContext is the external interface to all thread state for anything outside of the CPU.
#include <thread_context.hh>
Public Types
enum Status { Active, Suspended, Halting, Halted }
Public Member Functions
virtual ~ThreadContext ()
virtual BaseCPU * getCpuPtr ()=0
virtual int cpuId () const =0
virtual uint32_t socketId () const =0
virtual int threadId () const =0
virtual void setThreadId (int id)=0
virtual ContextID contextId () const =0
virtual void setContextId (ContextID id)=0
virtual BaseTLB * getITBPtr ()=0
virtual BaseTLB * getDTBPtr ()=0
virtual CheckerCPU * getCheckerCpuPtr ()=0
virtual TheISA::ISA * getIsaPtr ()=0
virtual TheISA::Decoder * getDecoderPtr ()=0
virtual System * getSystemPtr ()=0
virtual ::Kernel::Statistics * getKernelStats ()=0
virtual PortProxy & getPhysProxy ()=0
virtual PortProxy & getVirtProxy ()=0
virtual void initMemProxies (ThreadContext *tc)=0
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
virtual Process * getProcessPtr ()=0
virtual void setProcessPtr (Process *p)=0
virtual Status status () const =0
virtual void setStatus (Status new_status)=0
virtual void activate ()=0
Set the status to Active.
virtual void suspend ()=0
Set the status to Suspended.
virtual void halt ()=0
Set the status to Halted.
void quiesce ()
Quiesce thread context.
void quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
virtual void dumpFuncProfile ()=0
virtual void takeOverFrom (ThreadContext *old_context)=0
virtual void regStats (const std::string &name)=0
virtual EndQuiesceEvent * getQuiesceEvent ()=0
virtual void scheduleInstCountEvent (Event *event, Tick count)=0
virtual void descheduleInstCountEvent (Event *event)=0
virtual Tick getCurrentInstCount ()=0
virtual Tick readLastActivate ()=0
virtual Tick readLastSuspend ()=0
virtual void profileClear ()=0
virtual void profileSample ()=0
virtual void copyArchRegs (ThreadContext *tc)=0
virtual void clearArchRegs ()=0
virtual RegVal readIntReg (RegIndex reg_idx) const =0
virtual RegVal readFloatReg (RegIndex reg_idx) const =0
virtual const VecRegContainer & readVecReg (const RegId &reg) const =0
virtual VecRegContainer & getWritableVecReg (const RegId &reg)=0
virtual const VecElem & readVecElem (const RegId &reg) const =0
virtual const VecPredRegContainer & readVecPredReg (const RegId &reg) const =0
virtual VecPredRegContainer & getWritableVecPredReg (const RegId &reg)=0
virtual RegVal readCCReg (RegIndex reg_idx) const =0
virtual void setIntReg (RegIndex reg_idx, RegVal val)=0
virtual void setFloatReg (RegIndex reg_idx, RegVal val)=0
virtual void setVecReg (const RegId &reg, const VecRegContainer &val)=0
virtual void setVecElem (const RegId &reg, const VecElem &val)=0
virtual void setVecPredReg (const RegId &reg, const VecPredRegContainer &val)=0
virtual void setCCReg (RegIndex reg_idx, RegVal val)=0
virtual TheISA::PCState pcState () const =0
virtual void pcState (const TheISA::PCState &val)=0
void setNPC (Addr val)
virtual void pcStateNoRecord (const TheISA::PCState &val)=0
virtual Addr instAddr () const =0
virtual Addr nextInstAddr () const =0
virtual MicroPC microPC () const =0
virtual RegVal readMiscRegNoEffect (RegIndex misc_reg) const =0
virtual RegVal readMiscReg (RegIndex misc_reg)=0
virtual void setMiscRegNoEffect (RegIndex misc_reg, RegVal val)=0
virtual void setMiscReg (RegIndex misc_reg, RegVal val)=0
virtual RegId flattenRegId (const RegId &regId) const =0
virtual unsigned readStCondFailures () const =0
virtual void setStCondFailures (unsigned sc_failures)=0
virtual Counter readFuncExeInst () const =0
virtual void syscall (int64_t callnum, Fault *fault)=0
virtual int exit ()
virtual ConstVecLane8 readVec8BitLaneReg (const RegId &reg) const =0
Vector Register Lane Interfaces.
virtual ConstVecLane16 readVec16BitLaneReg (const RegId &reg) const =0
Reads source vector 16bit operand.
virtual ConstVecLane32 readVec32BitLaneReg (const RegId &reg) const =0
Reads source vector 32bit operand.
virtual ConstVecLane64 readVec64BitLaneReg (const RegId &reg) const =0
Reads source vector 64bit operand.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::Byte > &val)=0
Write a lane of the destination vector register.
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::TwoByte > &val)=0
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::FourByte > &val)=0
virtual void setVecLane (const RegId &reg, const LaneData< LaneSize::EightByte > &val)=0
virtual RegVal readIntRegFlat (RegIndex idx) const =0
Flat register interfaces.
virtual void setIntRegFlat (RegIndex idx, RegVal val)=0
virtual RegVal readFloatRegFlat (RegIndex idx) const =0
virtual void setFloatRegFlat (RegIndex idx, RegVal val)=0
virtual const VecRegContainer & readVecRegFlat (RegIndex idx) const =0
virtual VecRegContainer & getWritableVecRegFlat (RegIndex idx)=0
virtual void setVecRegFlat (RegIndex idx, const VecRegContainer &val)=0
virtual const VecElem & readVecElemFlat (RegIndex idx, const ElemIndex &elemIdx) const =0
virtual void setVecElemFlat (RegIndex idx, const ElemIndex &elemIdx, const VecElem &val)=0
virtual const VecPredRegContainer & readVecPredRegFlat (RegIndex idx) const =0
virtual VecPredRegContainer & getWritableVecPredRegFlat (RegIndex idx)=0
virtual void setVecPredRegFlat (RegIndex idx, const VecPredRegContainer &val)=0
virtual RegVal readCCRegFlat (RegIndex idx) const =0
virtual void setCCRegFlat (RegIndex idx, RegVal val)=0
Public Member Functions inherited from PCEventScope
virtual bool remove (PCEvent *event)=0
virtual bool schedule (PCEvent *event)=0
Static Public Member Functions
static void compare (ThreadContext *one, ThreadContext *two)
function to compare two thread contexts (for debugging)
Protected Types
typedef TheISA::MachInst MachInst
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
ThreadContext is the external interface to all thread state for anything outside of the CPU.
It provides all accessor methods to state that might be needed by external objects, ranging from register values to things such as kernel stats. It is an abstract base class; the CPU can create its own ThreadContext by deriving from it.
The ThreadContext is slightly different than the ExecContext. The ThreadContext provides access to an individual thread's state; an ExecContext provides ISA access to the CPU (meaning it is implicitly multithreaded on SMT systems). Additionally the ThreadState is an abstract class that exactly defines the interface; the ExecContext is a more implicit interface that must be implemented so that the ISA can access whatever state it needs.
Definition at line 92 of file thread_context.hh.
Member Typedef Documentation
MachInst
typedef TheISA::MachInst ThreadContext::MachInst protected
Definition at line 95 of file thread_context.hh.
VecElem
using ThreadContext::VecElem = TheISA::VecElem protected
Definition at line 97 of file thread_context.hh.
VecPredRegContainer
using ThreadContext::VecPredRegContainer = TheISA::VecPredRegContainer protected
Definition at line 98 of file thread_context.hh.
VecRegContainer
using ThreadContext::VecRegContainer = TheISA::VecRegContainer protected
Definition at line 96 of file thread_context.hh.
Member Enumeration Documentation
Status
enum ThreadContext::Status
Enumerator
Active
Running.
Instructions should be executed only when the context is in this state.
Suspended
Temporarily inactive.
Entered while waiting for synchronization, etc.
Halting
Trying to exit and waiting for an event to completely exit.
Entered when target executes an exit syscall.
Halted
Permanently shut down.
Entered when target executes m5exit pseudo-instruction. When all contexts enter this state, the simulation will terminate.
Definition at line 102 of file thread_context.hh.
Constructor & Destructor Documentation
~ThreadContext()
virtual ThreadContext::~ThreadContext () inline virtual
Reimplemented in Iris::ThreadContext.
Definition at line 122 of file thread_context.hh.
References X86ISA::count, MipsISA::event, AlphaISA::getDTBPtr(), AlphaISA::getITBPtr(), MipsISA::halt, name(), MipsISA::p, PseudoInst::quiesce(), ArmISA::readVecElem(), X86ISA::reg, ArmISA::status, takeOverFrom(), and X86ISA::val.
Member Function Documentation
activate()
virtual void ThreadContext::activate () pure virtual
Set the status to Active.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by cloneFunc(), execveFunc(), Process::initState(), EndQuiesceEvent::process(), DistIface::SyncEvent::process(), PowerISA::startupCPU(), AlphaISA::startupCPU(), SparcISA::startupCPU(), ArmISA::startupCPU(), RiscvISA::startupCPU(), X86ISA::startupCPU(), MipsISA::startupCPU(), PseudoInst::wakeCPU(), and FutexMap::wakeup_bitset().
clearArchRegs()
virtual void ThreadContext::clearArchRegs () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by cloneFunc(), execveFunc(), and ArmISA::Reset::invoke().
compare()
void ThreadContext::compare (ThreadContext * one, ThreadContext * two) static
function to compare two thread contexts (for debugging)
Definition at line 59 of file thread_context.cc.
References contextId(), cpuId(), DPRINTF, ArmISA::i, AlphaISA::NumCCRegs, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, AlphaISA::NumMiscRegs, AlphaISA::NumVecPredRegs, AlphaISA::NumVecRegs, panic, pcState(), readCCReg(), readFloatReg(), readIntReg(), readMiscRegNoEffect(), readVecPredReg(), readVecReg(), ArmISA::t1, ArmISA::t2, VecPredRegClass, and VecRegClass.
contextId()
virtual ContextID ThreadContext::contextId () const pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by cloneFunc(), compare(), SimpleThread::copyState(), BaseKvmCPU::doMMIOAccess(), execveFunc(), X86ISA::TLB::finalizePhysical(), CheckerCPU::genMemFragmentRequest(), ArmPPIGen::get(), ArmISA::ISA::getGenericTimer(), ArmISA::getMPIDR(), X86KvmCPU::handleKvmExitIO(), BaseKvmCPU::init(), FullO3CPU< O3CPUImpl >::init(), AnnotateDumpCallback::process(), SparcISA::ISA::readFSReg(), RiscvISA::ISA::readMiscReg(), BaseCPU::registerThreadContexts(), ArmISA::ISA::setMiscReg(), ArmISA::PMU::setThreadContext(), ArmISA::ISA::startup(), BaseCPU::takeOverFrom(), takeOverFrom(), ArmInterruptPin::targetContext(), X86ISA::GpuTLB::translate(), and ArmISA::TLB::updateMiscReg().
copyArchRegs()
virtual void ThreadContext::copyArchRegs (ThreadContext * tc) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by takeOverFrom().
cpuId()
virtual int ThreadContext::cpuId () const pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by cloneFunc(), compare(), ArmISA::getMPIDR(), DumpStatsPCEvent::process(), and Trace::InstPBTrace::traceInst().
descheduleInstCountEvent()
virtual void ThreadContext::descheduleInstCountEvent (Event * event) pure virtual
Implemented in SimpleThread, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by BaseRemoteGDB::descheduleInstCommitEvent().
dumpFuncProfile()
virtual void ThreadContext::dumpFuncProfile () pure virtual
Implemented in CheckerThreadContext< TC >, SimpleThread, O3ThreadContext< Impl >, and Iris::ThreadContext.
exit()
virtual int ThreadContext::exit () inline virtual
Definition at line 315 of file thread_context.hh.
References HsailISA::compare(), Ps2::one, serialize(), takeOverFrom(), and unserialize().
flattenRegId()
virtual RegId ThreadContext::flattenRegId (const RegId & regId) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by Minor::flattenRegIndex(), DefaultRename< Impl >::renameDestRegs(), and DefaultRename< Impl >::renameSrcRegs().
getCheckerCpuPtr()
virtual CheckerCPU* ThreadContext::getCheckerCpuPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by BaseCPU::flushTLBs(), ArmISA::TLBIALL::operator()(), ArmISA::TLBIASID::operator()(), ArmISA::TLBIALLN::operator()(), ArmISA::TLBIMVAA::operator()(), ArmISA::TLBIMVA::operator()(), ArmISA::TLBIIPA::operator()(), ArmISA::ISA::setMiscReg(), ArmISA::skipFunction(), and BaseCPU::takeOverFrom().
getCpuPtr()
virtual BaseCPU* ThreadContext::getCpuPtr () pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by SparcISA::ISA::checkSoftInt(), KvmVM::contextIdToVCpuId(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), PseudoInst::dumpresetstats(), PseudoInst::dumpstats(), ArmISA::TableWalker::fetchDescriptor(), ArmISA::Stage2MMU::Stage2Translation::finish(), X86ISA::initCPU(), PseudoInst::initParam(), ArmISA::Reset::invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::SystemError::invoke(), ArmISA::ArmSev::invoke(), PseudoInst::loadsymbol(), PseudoInst::m5checkpoint(), Linux::openSpecialFile(), EndQuiesceEvent::process(), Linux::DmesgDumpEvent::process(), Linux::KernelPanicEvent::process(), DumpStatsPCEvent::process(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), quiesce(), PseudoInst::quiesceCycles(), PseudoInst::quiesceSkip(), quiesceTick(), AlphaISA::ISA::readIpr(), X86ISA::ISA::readMiscReg(), RiscvISA::ISA::readMiscReg(), SparcISA::ISA::readMiscReg(), ArmISA::ISA::readMiscReg(), MipsISA::readRegOtherThread(), System::registerThreadContext(), PseudoInst::resetstats(), ArmISA::sendEvent(), SparcISA::ISA::serialize(), LinuxAlphaSystem::setDelayLoop(), SparcISA::ISA::setFSReg(), X86ISA::ISA::setMiscReg(), RiscvISA::ISA::setMiscReg(), MipsISA::ISA::setMiscReg(), SparcISA::ISA::setMiscReg(), MipsISA::setRegOtherThread(), takeOverFrom(), Trace::TarmacContext::tarmacCpuName(), PseudoInst::workbegin(), and PseudoInst::workend().
getCurrentInstCount()
virtual Tick ThreadContext::getCurrentInstCount () pure virtual
Implemented in SimpleThread, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by BaseRemoteGDB::scheduleInstCommitEvent().
getDecoderPtr()
virtual TheISA::Decoder* ThreadContext::getDecoderPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by Minor::Fetch2::evaluate(), SparcISA::ISA::setMiscReg(), ArmISA::ISA::setMiscReg(), X86ISA::ISA::startup(), SimpleThread::takeOverFrom(), O3ThreadContext< Impl >::takeOverFrom(), and X86ISA::ISA::updateHandyM5Reg().
getDTBPtr()
virtual BaseTLB* ThreadContext::getDTBPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by X86ISA::RemoteGDB::acc(), X86ISA::copyMiscRegs(), ArmISA::copyRegs(), BaseKvmCPU::doMMIOAccess(), BaseCPU::flushTLBs(), SparcISA::handleIprRead(), SparcISA::handleIprWrite(), AlphaISA::NDtbMissFault::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), X86ISA::PageFault::invoke(), mmapImpl(), Trace::TarmacParserRecord::readMemNoEffect(), Minor::LSQ::SplitDataRequest::sendNextFragmentToTranslation(), X86ISA::ISA::setMiscReg(), Minor::LSQ::SingleDataRequest::startAddrTranslation(), BaseCPU::takeOverFrom(), Trace::TarmacTracerRecordV8::TraceInstEntryV8::TraceInstEntryV8(), Trace::TarmacTracerRecordV8::TraceMemEntryV8::TraceMemEntryV8(), try_translate(), SparcISA::vtophys(), and X86ISA::vtophys().
getIsaPtr()
virtual TheISA::ISA* ThreadContext::getIsaPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by MiscRegOp64::checkEL2Trap(), ArmISA::ArmStaticInst::getCurSveVecLenInBits(), ArmISA::mcrMrc15TrapToHyp(), and ArmISA::snsBankedIndex64().
getITBPtr()
virtual BaseTLB* ThreadContext::getITBPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by X86ISA::copyMiscRegs(), ArmISA::copyRegs(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), BaseCPU::flushTLBs(), SparcISA::TLB::GetTsbPtr(), SparcISA::FastInstructionAccessMMUMiss::invoke(), AlphaISA::ItbPageFault::invoke(), X86ISA::PageFault::invoke(), mmapImpl(), X86ISA::ISA::setMiscReg(), BaseCPU::takeOverFrom(), try_translate(), and SparcISA::vtophys().
getKernelStats()
virtual ::Kernel::Statistics* ThreadContext::getKernelStats () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by PseudoInst::arm(), IdleStartEvent::process(), quiesce(), quiesceTick(), SparcISA::ISA::setFSReg(), AlphaISA::ISA::setIpr(), SimpleThread::takeOverFrom(), and O3ThreadContext< Impl >::takeOverFrom().
getPhysProxy()
virtual PortProxy& ThreadContext::getPhysProxy () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by Linux::ThreadInfo::curThreadInfo(), ArmSemihosting::physProxy(), SparcISA::vtophys(), and AlphaISA::vtophys().
getProcessPtr()
virtual Process* ThreadContext::getProcessPtr () pure virtual
Implemented in SimpleThread, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by _llseekFunc(), SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), PowerISA::RemoteGDB::acc(), RiscvISA::RemoteGDB::acc(), X86ISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), acceptFunc(), accessFunc(), archPrctlFunc(), bindFunc(), brkFunc(), chdirFunc(), chmodFunc(), chownFunc(), clock_getresFunc(), clock_gettimeFunc(), cloneFunc(), closeFunc(), connectFunc(), SyscallDesc::doSyscall(), dup2Func(), dupFunc(), eventfdFunc(), execveFunc(), exitImpl(), faccessatFunc(), fallocateFunc(), fchmodFunc(), fchownFunc(), fcntl64Func(), fcntlFunc(), fstat64Func(), fstatat64Func(), fstatfsFunc(), fstatFunc(), ftruncate64Func(), ftruncateFunc(), futexFunc(), getcwdFunc(), getegidFunc(), geteuidFunc(), getgidFunc(), getgidPseudoFunc(), gethostnameFunc(), getpeernameFunc(), getpgrpFunc(), getpidFunc(), getpidPseudoFunc(), getppidFunc(), SparcISA::getresuidFunc(), getrlimitFunc(), getrusageFunc(), getsocknameFunc(), getsockoptFunc(), gettidFunc(), gettimeofdayFunc(), getuidFunc(), getuidPseudoFunc(), GenericPageTableFault::invoke(), AlphaISA::NDtbMissFault::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::SpillNNormal::invoke(), AlphaISA::ItbPageFault::invoke(), SparcISA::FillNNormal::invoke(), SparcISA::TrapInstruction::invoke(), ClDriver::ioctl(), ioctlFunc(), linkFunc(), listenFunc(), lseekFunc(), lstat64Func(), lstatFunc(), X86ISA::m5PageFault(), mkdirFunc(), mknodFunc(), Shader::mmap(), mmapImpl(), mremapFunc(), ClDriver::open(), openImpl(), osf_getsysinfoFunc(), osf_setsysinfoFunc(), pipeImpl(), pollFunc(), prlimitFunc(), pwrite64Func(), readFunc(), readlinkatFunc(), readlinkFunc(), readvFunc(), recvfromFunc(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), recvmsgFunc(), BaseCPU::registerThreadContexts(), renameatFunc(), renameFunc(), rmdirFunc(), selectFunc(), sendmsgFunc(), ComputeUnit::sendRequest(), sendtoFunc(), setpgidFunc(), setsockoptFunc(), setThreadArea32Func(), setThreadAreaFunc(), setTidAddressFunc(), setTLSFunc32(), setTLSFunc64(), setuidFunc(), shutdownFunc(), socketFunc(), socketpairFunc(), stat64Func(), statfsFunc(), statFunc(), symlinkFunc(), sys_getsysinfoFunc(), sys_setsysinfoFunc(), sysctlFunc(), sysinfoFunc(), takeOverFrom(), tgkillFunc(), timeFunc(), timesFunc(), X86ISA::TLB::translate(), X86ISA::GpuTLB::translate(), RiscvISA::TLB::translateData(), MipsISA::TLB::translateData(), PowerISA::TLB::translateData(), RiscvISA::TLB::translateInst(), MipsISA::TLB::translateInst(), PowerISA::TLB::translateInst(), ArmISA::TLB::translateSe(), X86ISA::GpuTLB::translationReturn(), truncate64Func(), truncateFunc(), SparcISA::unameFunc(), unameFunc(), unameFunc32(), unameFunc64(), unlinkatFunc(), unlinkHelper(), utimesFunc(), wait4Func(), writeFunc(), and writevFunc().
getQuiesceEvent()
virtual EndQuiesceEvent* ThreadContext::getQuiesceEvent () pure virtual
Implemented in O3ThreadContext< Impl >, SimpleThread, CheckerThreadContext< TC >, and Iris::ThreadContext.
Referenced by quiesceTick(), and takeOverFrom().
getSystemPtr()
virtual System* ThreadContext::getSystemPtr () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by _llseekFunc(), PseudoInst::addsymbol(), ArmISA::TLBIOp::broadcast(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), SparcISA::TLB::doMmuRegWrite(), dumpDmesgEntry(), exitFutexWake(), exitImpl(), futexFunc(), ArmSystem::getArmSystem(), getrlimitFunc(), X86System::initState(), RiscvISA::Reset::invoke(), ArmISA::Reset::invoke(), PseudoInst::loadsymbol(), ArmSemihosting::physProxy(), pollFunc(), FreebsdAlphaSystem::SkipCalibrateClocksEvent::process(), Linux::DebugPrintkEvent::process(), LinuxAlphaSystem::SkipDelayLoopEvent::process(), LinuxMipsSystem::SkipDelayLoopEvent::process(), AnnotateDumpCallback::process(), DumpStatsPCEvent::process(), AlphaISA::ProcessInfo::ProcessInfo(), PseudoInst::readfile(), SparcISA::ISA::readFSReg(), ArmISA::ISA::readMiscReg(), ArmSemihosting::readString(), X86ISA::readSymbol(), ArmISA::readSymbol(), rmdirFunc(), selectFunc(), setpgidFunc(), takeOverFrom(), tgkillFunc(), DistIface::toggleSync(), AlphaISA::StackTrace::trace(), RiscvISA::TLB::translateData(), RiscvISA::TLB::translateInst(), wait4Func(), PseudoInst::wakeCPU(), PseudoInst::workbegin(), and PseudoInst::workend().
getVirtProxy()
virtual PortProxy& ThreadContext::getVirtProxy () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by _llseekFunc(), acceptFunc(), accessFunc(), PseudoInst::addsymbol(), archPrctlFunc(), bindFunc(), brkFunc(), chdirFunc(), chmodFunc(), chownFunc(), clock_getresFunc(), clock_gettimeFunc(), Process::clone(), cloneFunc(), connectFunc(), Linux::ThreadInfo::curTaskInfo(), Linux::ThreadInfo::curTaskMmFromTaskStruct(), Linux::ThreadInfo::curTaskNameFromTaskStruct(), Linux::ThreadInfo::curTaskPIDFromTaskStruct(), Linux::ThreadInfo::curTaskStartFromTaskStruct(), Linux::ThreadInfo::curTaskTGIDFromTaskStruct(), MipsISA::StackTrace::decodePrologue(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), dumpDmesgEntry(), execveFunc(), exitFutexWake(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), fstat64Func(), fstatat64Func(), fstatfsFunc(), fstatFunc(), futexFunc(), Linux::ThreadInfo::get_data(), AlphaISA::getArgument(), SparcISA::getArgument(), ArmISA::getArgument(), getcwdFunc(), gethostnameFunc(), getpeernameFunc(), SparcISA::getresuidFunc(), getrlimitFunc(), getrusageFunc(), getsocknameFunc(), getsockoptFunc(), gettimeofdayFunc(), ArmLinuxProcess32::initState(), ClDriver::ioctl(), ioctlFunc(), linkFunc(), lstat64Func(), lstatFunc(), X86ISA::m5PageFault(), mkdirFunc(), mknodFunc(), mmapImpl(), MipsISA::ProcessInfo::name(), X86ISA::ProcessInfo::name(), AlphaISA::ProcessInfo::name(), ArmISA::ProcessInfo::name(), openImpl(), Arguments::operator char *(), Arguments::operator T*(), osf_getsysinfoFunc(), osf_setsysinfoFunc(), MipsISA::ProcessInfo::pid(), X86ISA::ProcessInfo::pid(), AlphaISA::ProcessInfo::pid(), ArmISA::ProcessInfo::pid(), pipeImpl(), pollFunc(), prlimitFunc(), AnnotateDumpCallback::process(), AlphaISA::ProcessInfo::ProcessInfo(), pwrite64Func(), BaseRemoteGDB::read(), PseudoInst::readfile(), readFunc(), readlinkFunc(), Trace::TarmacParserRecord::readMemNoEffect(), X86ISA::readSymbol(), ArmISA::readSymbol(), readvFunc(), recvfromFunc(), recvmsgFunc(), VPtr< T >::refresh(), renameatFunc(), renameFunc(), Process::replicatePage(), rmdirFunc(), selectFunc(), sendmsgFunc(), sendtoFunc(), LinuxAlphaSystem::setDelayLoop(), setsockoptFunc(), setThreadArea32Func(), setTLSFunc32(), socketpairFunc(), stat64Func(), statfsFunc(), statFunc(), symlinkFunc(), sys_getsysinfoFunc(), sys_setsysinfoFunc(), sysctlFunc(), sysinfoFunc(), MipsISA::ProcessInfo::task(), X86ISA::ProcessInfo::task(), AlphaISA::ProcessInfo::task(), ArmISA::ProcessInfo::task(), timeFunc(), timesFunc(), truncate64Func(), truncateFunc(), SparcISA::unameFunc(), unameFunc(), unameFunc32(), unameFunc64(), unlinkHelper(), utimesFunc(), wait4Func(), BaseRemoteGDB::write(), PseudoInst::writefile(), writeFunc(), and writevFunc().
getWritableVecPredReg()
virtual VecPredRegContainer& ThreadContext::getWritableVecPredReg (const RegId & reg) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
getWritableVecPredRegFlat()
virtual VecPredRegContainer& ThreadContext::getWritableVecPredRegFlat (RegIndex idx) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
getWritableVecReg()
virtual VecRegContainer& ThreadContext::getWritableVecReg (const RegId & reg) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs().
getWritableVecRegFlat()
virtual VecRegContainer& ThreadContext::getWritableVecRegFlat (RegIndex idx) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
halt()
virtual void ThreadContext::halt () pure virtual
Set the status to Halted.
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by exitImpl().
initMemProxies()
virtual void ThreadContext::initMemProxies (ThreadContext * tc) pure virtual
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
tc ThreadContext for the virtual-to-physical translation
Implemented in SimpleThread, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by BaseKvmCPU::init(), and MinorCPU::init().
instAddr()
virtual Addr ThreadContext::instAddr () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by RiscvISA::RiscvFault::invoke(), BaseCPU::mwaitAtomic(), X86ISA::TLB::translate(), X86ISA::GpuTLB::translate(), Minor::Execute::tryPCEvents(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCore(), and X86KvmCPU::updateKvmStateRegs().
microPC()
virtual MicroPC ThreadContext::microPC () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
nextInstAddr()
virtual Addr ThreadContext::nextInstAddr () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by Trace::ArmNativeTrace::check(), and DefaultCommit< Impl >::commitHead().
pcState() [1/2]
virtual TheISA::PCState ThreadContext::pcState () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by GenericISA::M5DebugFault::advancePC(), AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), Trace::SparcNativeTrace::check(), AlphaISA::Interrupts::checkInterrupts(), cloneFunc(), BaseRemoteGDB::cmd_async_cont(), BaseRemoteGDB::cmd_async_step(), BaseRemoteGDB::cmd_cont(), BaseRemoteGDB::cmd_step(), Minor::Execute::commit(), Minor::Execute::commitInst(), compare(), O3ThreadContext< Impl >::copyArchRegs(), PowerISA::copyRegs(), AlphaISA::copyRegs(), RiscvISA::copyRegs(), ArmISA::copyRegs(), SparcISA::copyRegs(), X86ISA::copyRegs(), MipsISA::copyRegs(), ArmISA::copyVecRegs(), SparcISA::doNormalFault(), SparcISA::doREDFault(), Minor::Execute::executeMemRefInst(), execveFunc(), AlphaISA::RemoteGDB::AlphaGdbRegCache::getRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::getRegs(), RiscvISA::RemoteGDB::RiscvGdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::getRegs(), X86ISA::RemoteGDB::X86GdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::getRegs(), SparcProcess::handleTrap(), AlphaISA::initCPU(), X86ISA::initCPU(), RiscvProcess32::initState(), X86System::initState(), FullO3CPU< O3CPUImpl >::insertThread(), FaultBase::invoke(), AlphaISA::AlphaFault::invoke(), ReExec::invoke(), SparcISA::SparcFaultBase::invoke(), X86ISA::X86FaultBase::invoke(), SyscallRetryFault::invoke(), SparcISA::PowerOnReset::invoke(), MipsISA::MipsFaultBase::invoke(), RiscvISA::RiscvFault::invoke(), X86ISA::X86Trap::invoke(), RiscvISA::Reset::invoke(), MipsISA::ResetFault::invoke(), ArmISA::ArmFault::invoke(), SparcISA::SpillNNormal::invoke(), MipsISA::TlbFault< TlbInvalidFault >::invoke(), SparcISA::FillNNormal::invoke(), SparcISA::TrapInstruction::invoke(), ArmISA::Reset::invoke(), ArmISA::SupervisorCall::invoke(), X86ISA::PageFault::invoke(), X86ISA::InitInterrupt::invoke(), X86ISA::StartupInterrupt::invoke(), ArmISA::ArmFault::invoke64(), RiscvISA::RiscvFault::invokeSE(), RiscvISA::UnknownInstFault::invokeSE(), RiscvISA::IllegalInstFault::invokeSE(), RiscvISA::UnimplementedFault::invokeSE(), RiscvISA::IllegalFrmFault::invokeSE(), ioctlFunc(), mmapImpl(), Iris::ThreadContext::pcStateNoRecord(), SkipFuncEvent::process(), PseudoInst::pseudoInst(), Trace::TarmacParserRecord::readMemNoEffect(), ArmISA::ISA::readMiscReg(), serialize(), MipsISA::MipsFaultBase::setExceptionState(), ArmISA::ISA::setMiscReg(), AlphaISA::RemoteGDB::AlphaGdbRegCache::setRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), RiscvISA::RemoteGDB::RiscvGdbRegCache::setRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::setRegs(), X86ISA::RemoteGDB::X86GdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::setRegs(), AlphaISA::skipFunction(), ArmISA::skipFunction(), SparcISA::skipFunction(), MipsISA::skipFunction(), X86ISA::I386Process::syscall(), Minor::Execute::takeInterrupt(), AlphaISA::StackTrace::trace(), BaseRemoteGDB::trap(), Minor::Execute::tryPCEvents(), Minor::Execute::tryToBranch(), unserialize(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), ArmKvmCPU::updateTCStateCore(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContextRegs(), and Minor::Fetch1::wakeupFetch().
pcState() [2/2]
virtual void ThreadContext::pcState (const TheISA::PCState & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
pcStateNoRecord()
virtual void ThreadContext::pcStateNoRecord (const TheISA::PCState & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::ISA::setMiscReg(), and ArmISA::skipFunction().
profileClear()
virtual void ThreadContext::profileClear () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
profileSample()
virtual void ThreadContext::profileSample () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
quiesce()
void ThreadContext::quiesce ()
Quiesce thread context.
Definition at line 133 of file thread_context.cc.
References DPRINTF, getCpuPtr(), getKernelStats(), name(), Kernel::Statistics::quiesce(), and suspend().
Referenced by PseudoInst::quiesce(), and DistIface::toggleSync().
quiesceTick()
void ThreadContext::quiesceTick (Tick resume)
Quiesce, suspend, and schedule activate at resume.
Definition at line 147 of file thread_context.cc.
References DPRINTF, getCpuPtr(), getKernelStats(), getQuiesceEvent(), SimObject::name(), BaseCPU::params(), Kernel::Statistics::quiesce(), EventManager::reschedule(), and suspend().
Referenced by PseudoInst::quiesceCycles(), PseudoInst::quiesceNs(), PseudoInst::quiesceSkip(), and DistIface::toggleSync().
readCCReg()
virtual RegVal ThreadContext::readCCReg (RegIndex reg_idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by compare(), ArmISA::copyRegs(), X86ISA::getRFlags(), ArmISA::ArmFault::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::ISA::readMiscReg(), Trace::ArmNativeTrace::ThreadState::update(), Trace::TarmacTracerRecord::TraceRegEntry::updateCC(), ArmV8KvmCPU::updateKvmState(), and Trace::TarmacTracerRecord::TraceRegEntry::updateMisc().
readCCRegFlat()
virtual RegVal ThreadContext::readCCRegFlat (RegIndex idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by X86ISA::copyRegs(), and serialize().
readFloatReg()
virtual RegVal ThreadContext::readFloatReg (RegIndex reg_idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by compare(), PowerISA::copyRegs(), AlphaISA::copyRegs(), SparcISA::copyRegs(), AlphaISA::getArgument(), AlphaISA::RemoteGDB::AlphaGdbRegCache::getRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::getRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::getRegs(), MipsISA::readRegOtherThread(), Trace::X86NativeTrace::ThreadState::update(), Trace::TarmacTracerRecord::TraceRegEntry::updateFloat(), ArmV8KvmCPU::updateKvmState(), and updateKvmStateFPUCommon().
readFloatRegFlat()
virtual RegVal ThreadContext::readFloatRegFlat (RegIndex idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyRegs(), X86ISA::copyRegs(), MipsISA::copyRegs(), serialize(), and ArmKvmCPU::updateKvmStateVFP().
readFuncExeInst()
virtual Counter ThreadContext::readFuncExeInst () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by O3ThreadContext< Impl >::copyArchRegs(), SimpleThread::copyState(), SimpleThread::takeOverFrom(), and O3ThreadContext< Impl >::takeOverFrom().
readIntReg()
virtual RegVal ThreadContext::readIntReg (RegIndex reg_idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by SparcLinux::archClone(), PowerISA::BranchRegCond::branchTarget(), Trace::SparcNativeTrace::check(), cloneFunc(), compare(), PowerISA::copyRegs(), AlphaISA::copyRegs(), RiscvISA::copyRegs(), SparcISA::copyRegs(), FreebsdAlphaSystem::doCalibrateClocks(), SparcISA::doNormalFault(), SparcISA::doREDFault(), TimingExprReadIntReg::eval(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), AlphaISA::getArgument(), SparcISA::getArgument(), X86ISA::getArgument(), ArmISA::getArgument(), AlphaISA::RemoteGDB::AlphaGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::getRegs(), RiscvISA::RemoteGDB::RiscvGdbRegCache::getRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::getRegs(), X86ISA::RemoteGDB::X86GdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::getRegs(), PowerLinuxProcess::getSyscallArg(), AlphaProcess::getSyscallArg(), PowerProcess::getSyscallArg(), RiscvProcess::getSyscallArg(), MipsProcess::getSyscallArg(), ArmProcess32::getSyscallArg(), Sparc32Process::getSyscallArg(), ArmProcess64::getSyscallArg(), X86ISA::X86_64Process::getSyscallArg(), Sparc64Process::getSyscallArg(), X86ISA::I386Process::getSyscallArg(), DumpStatsPCEvent::getTaskDetails(), DumpStatsPCEvent64::getTaskDetails(), SparcISA::Sparc32LinuxProcess::handleTrap(), SparcISA::Sparc64LinuxProcess::handleTrap(), ArmISA::ArmFault::invoke(), ArmISA::SupervisorCall::invoke(), RiscvISA::SyscallFault::invokeSE(), X86ISA::m5Syscall(), AnnotateDumpCallback::process(), ArmISA::ISA::readMiscReg(), MipsISA::readRegOtherThread(), PowerProcess::setSyscallReturn(), SparcProcess::setSyscallReturn(), AlphaISA::skipFunction(), ArmISA::skipFunction(), SparcISA::skipFunction(), MipsISA::skipFunction(), AlphaISA::StackTrace::trace(), Trace::X86NativeTrace::ThreadState::update(), Trace::ArmNativeTrace::ThreadState::update(), Trace::TarmacTracerRecord::TraceRegEntry::updateInt(), and ArmV8KvmCPU::updateKvmState().
readIntRegFlat()
virtual RegVal ThreadContext::readIntRegFlat (RegIndex idx) const pure virtual
Flat register interfaces.
Some architectures have different registers visible in different modes. Such architectures "flatten" a register (see flattenRegId()) to map it into the gem5 register file. This interface provides a flat interface to the underlying register file, which allows for example serialization code to access all registers.
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyRegs(), X86ISA::copyRegs(), MipsISA::copyRegs(), ArmKvmCPU::onKvmExitHypercall(), serialize(), and ArmKvmCPU::updateKvmStateCore().
readLastActivate()
virtual Tick ThreadContext::readLastActivate () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by PseudoInst::quiesceTime().
readLastSuspend()
virtual Tick ThreadContext::readLastSuspend () pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by PseudoInst::quiesceTime().
readMiscReg()
virtual RegVal ThreadContext::readMiscReg (RegIndex misc_reg) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmProcess64::armHwcapImpl(), MipsISA::MipsFaultBase::base(), ArmISA::canReadAArch64SysReg(), ArmISA::canWriteAArch64SysReg(), ArmISA::ArmStaticInst::checkAdvSIMDOrFPEnabled32(), MiscRegOp64::checkEL1Trap(), MiscRegOp64::checkEL2Trap(), MiscRegOp64::checkEL3Trap(), ArmISA::ArmStaticInst::checkFPAdvSIMDTrap64(), ArmISA::Interrupts::checkInterrupts(), ArmISA::TLB::checkPAN(), ArmISA::ArmStaticInst::checkSveTrap(), X86ISA::copyMiscRegs(), ArmISA::currOpMode(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), ArmKvmCPU::dumpKvmStateCoProc(), ArmISA::PrefetchAbort::ec(), ArmISA::DataAbort::ec(), ArmISA::ELIsInHost(), ArmISA::ELUsingAArch32K(), MiscRegImplDefined64::execute(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), SparcISA::RemoteGDB::gdbRegs(), ArmISA::ArmStaticInst::generalExceptionsToAArch64(), ArmISA::getExecutingAsid(), ArmISA::Interrupts::getInterrupt(), SparcISA::RemoteGDB::SPARCGdbRegCache::getRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::getRegs(), ArmISA::getRestoredITBits(), ArmISA::ArmFault::getVector(), ArmISA::Reset::getVector(), ArmISA::ArmFault::getVector64(), RiscvISA::Interrupts::globalMask(), X86ISA::handleIprRead(), ArmISA::illegalExceptionReturn(), ArmISA::inAArch64(), ArmProcess32::initState(), ArmProcess64::initState(), ArmISA::inSecureState(), MipsISA::inUserMode(), RiscvISA::RiscvFault::invoke(), RiscvISA::Reset::invoke(), MipsISA::CoprocessorUnusableFault::invoke(), ArmISA::ArmFault::invoke(), ArmISA::Reset::invoke(), ArmISA::SupervisorCall::invoke(), X86ISA::InitInterrupt::invoke(), X86ISA::StartupInterrupt::invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::ArmFault::invoke64(), ArmISA::isBigEndian64(), ArmISA::isSecureBelowEL3(), ArmISA::ArmStaticInst::isWFxTrapping(), X86KvmCPU::kvmRunWrapper(), ArmISA::longDescFormatInUse(), X86ISA::m5PageFault(), X86ISA::m5Syscall(), ArmISA::mcrMrc15TrapToHyp(), ArmISA::TableWalker::memAttrs(), ArmISA::TableWalker::memAttrsAArch64(), ArmISA::TableWalker::memAttrsLPAE(), ArmISA::ArmFaultVals< FastInterrupt >::offset(), MipsISA::TlbRefillFault::offset(), ArmISA::TableWalker::processWalk(), ArmISA::TableWalker::processWalkAArch64(), ArmISA::TableWalker::processWalkLPAE(), ArmISA::purifyTaggedAddr(), ArmISA::readMPIDR(), MipsISA::readRegOtherThread(), ArmISA::sendEvent(), MipsISA::MipsFaultBase::setExceptionState(), ArmISA::ISA::setMiscReg(), MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState(), ArmISA::snsBankedIndex(), ArmISA::snsBankedIndex64(), ArmISA::ArmStaticInst::softwareBreakpoint32(), ArmISA::SPAlignmentCheckEnabled(), ArmV8KvmCPU::startup(), ArmISA::Interrupts::takeInt(), Trace::ArmNativeTrace::ThreadState::update(), ArmISA::ArmFault::update(), ArmV8KvmCPU::updateKvmState(), ArmKvmCPU::updateKvmStateCore(), updateKvmStateFPUCommon(), X86KvmCPU::updateKvmStateMSRs(), X86KvmCPU::updateKvmStateRegs(), X86KvmCPU::updateKvmStateSRegs(), ArmKvmCPU::updateKvmStateVFP(), ArmISA::TLB::updateMiscReg(), and ArmISA::TableWalker::walk().
readMiscRegNoEffect()
virtual RegVal ThreadContext::readMiscRegNoEffect (RegIndex misc_reg) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::AbortFault< DataAbort >::abortDisable(), ArmISA::Interrupt::abortDisable(), ArmISA::FastInterrupt::abortDisable(), AlphaISA::RemoteGDB::acc(), archPrctlFunc(), MipsISA::Interrupts::checkInterrupts(), SparcISA::Interrupts::checkInterrupts(), AlphaISA::Interrupts::checkInterrupts(), X86ISA::Interrupts::checkInterrupts(), ArmISA::ArmStaticInst::checkSETENDEnabled(), compare(), AlphaISA::copyIprs(), SparcISA::copyMiscRegs(), AlphaISA::copyMiscRegs(), X86ISA::copyMiscRegs(), ArmISA::copyRegs(), SparcISA::copyRegs(), MipsISA::copyRegs(), Linux::ThreadInfo::curThreadInfo(), SparcISA::doNormalFault(), SparcISA::doREDFault(), ArmKvmCPU::dumpKvmStateCoProc(), SparcISA::enterREDState(), X86ISA::TLB::finalizePhysical(), ArmISA::FastInterrupt::fiqDisable(), X86ISA::RemoteGDB::gdbRegs(), MipsISA::getCauseIP(), SparcISA::getExecutingAsid(), AlphaISA::getExecutingAsid(), SparcISA::getHyperVector(), MipsISA::Interrupts::getInterrupt(), AlphaISA::Interrupts::getInterrupt(), SparcISA::Interrupts::getInterrupt(), SparcISA::getPrivVector(), MipsISA::RemoteGDB::MipsGdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::getRegs(), X86ISA::RemoteGDB::X86GdbRegCache::getRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::getRegs(), X86ISA::getRFlags(), ArmISA::ArmFault::getVector(), ArmISA::Reset::getVector(), X86KvmCPU::handleIOMiscReg32(), X86ISA::handleIprWrite(), X86KvmCPU::handleKvmExitIO(), AlphaISA::initCPU(), X86System::initState(), MipsISA::Interrupts::interruptsPending(), AlphaISA::inUserMode(), SparcISA::inUserMode(), X86ISA::inUserMode(), ArmISA::inUserMode(), AlphaISA::AlphaFault::invoke(), SparcISA::SparcFaultBase::invoke(), X86ISA::X86FaultBase::invoke(), SparcISA::PowerOnReset::invoke(), MipsISA::ResetFault::invoke(), AlphaISA::DtbFault::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), ArmISA::ArmFault::invoke(), SparcISA::FastDataAccessMMUMiss::invoke(), AlphaISA::ItbFault::invoke(), X86ISA::PageFault::invoke(), ArmISA::VirtualDataAbort::invoke(), AlphaISA::StackTrace::isEntry(), AlphaISA::Kernel::Statistics::mode(), MipsISA::InterruptFault::offset(), MipsISA::Interrupts::onCpuTimerInterrupt(), X86ISA::GpuTLB::pagingProtectionChecks(), IdleStartEvent::process(), AnnotateDumpCallback::process(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), ArmISA::UndefinedInstruction::routeToHyp(), ArmISA::SupervisorCall::routeToHyp(), ArmISA::SupervisorTrap::routeToHyp(), ArmISA::PrefetchAbort::routeToHyp(), ArmISA::DataAbort::routeToHyp(), ArmISA::Interrupt::routeToHyp(), ArmISA::FastInterrupt::routeToHyp(), ArmISA::PCAlignmentFault::routeToHyp(), ArmISA::SystemError::routeToHyp(), ArmISA::SoftwareBreakpoint::routeToHyp(), ArmISA::PrefetchAbort::routeToMonitor(), ArmISA::DataAbort::routeToMonitor(), ArmISA::Interrupt::routeToMonitor(), ArmISA::FastInterrupt::routeToMonitor(), ArmISA::SystemError::routeToMonitor(), MipsISA::setCauseIP(), setKvmDTableReg(), setKvmSegmentReg(), X86ISA::RemoteGDB::X86GdbRegCache::setRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::setRegs(), SparcProcess::setSyscallReturn(), Trace::TarmacBaseRecord::TarmacBaseRecord(), X86ISA::GpuTLB::tlbLookup(), AlphaISA::StackTrace::trace(), X86ISA::TLB::translate(), X86ISA::GpuTLB::translate(), AlphaISA::TLB::translateData(), SparcISA::TLB::translateData(), AlphaISA::TLB::translateInst(), SparcISA::TLB::translateInst(), X86ISA::TLB::translateInt(), X86ISA::GpuTLB::translateInt(), Trace::ArmNativeTrace::ThreadState::update(), ArmISA::ArmFault::update(), Trace::TarmacTracerRecord::TraceRegEntry::updateInt(), ArmKvmCPU::updateKvmStateCoProc(), updateKvmStateFPUCommon(), X86KvmCPU::updateKvmStateFPULegacy(), X86KvmCPU::updateKvmStateFPUXSave(), Trace::TarmacTracerRecord::TraceRegEntry::updateMisc(), ArmKvmCPU::updateTCStateCore(), SparcISA::vtophys(), and AlphaISA::vtophys().
readStCondFailures()
virtual unsigned ThreadContext::readStCondFailures () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
readVec16BitLaneReg()
virtual ConstVecLane16 ThreadContext::readVec16BitLaneReg (const RegId & reg) const pure virtual
Reads source vector 16bit operand.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
readVec32BitLaneReg()
virtual ConstVecLane32 ThreadContext::readVec32BitLaneReg (const RegId & reg) const pure virtual
Reads source vector 32bit operand.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
readVec64BitLaneReg()
virtual ConstVecLane64 ThreadContext::readVec64BitLaneReg (const RegId & reg) const pure virtual
Reads source vector 64bit operand.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
readVec8BitLaneReg()
virtual ConstVecLane8 ThreadContext::readVec8BitLaneReg (const RegId & reg) const pure virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
readVecElem()
virtual const VecElem& ThreadContext::readVecElem (const RegId & reg) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
readVecElemFlat()
virtual const VecElem& ThreadContext::readVecElemFlat (RegIndex idx, const ElemIndex & elemIdx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyVecRegs().
readVecPredReg()
virtual const VecPredRegContainer& ThreadContext::readVecPredReg (const RegId & reg) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by compare(), and Trace::TarmacTracerRecordV8::TraceRegEntryV8::updatePred().
readVecPredRegFlat()
virtual const VecPredRegContainer& ThreadContext::readVecPredRegFlat (RegIndex idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by serialize().
readVecReg()
virtual const VecRegContainer& ThreadContext::readVecReg (const RegId & reg) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by compare(), ArmISA::RemoteGDB::AArch64GdbRegCache::getRegs(), Trace::ArmNativeTrace::ThreadState::update(), and Trace::TarmacTracerRecordV8::TraceRegEntryV8::updateVec().
readVecRegFlat()
virtual const VecRegContainer& ThreadContext::readVecRegFlat (RegIndex idx) const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyVecRegs(), and serialize().
regStats()
virtual void ThreadContext::regStats (const std::string & name) pure virtual
Implemented in CheckerThreadContext< TC >, Iris::ThreadContext, O3ThreadContext< Impl >, and SimpleThread.
scheduleInstCountEvent()
virtual void ThreadContext::scheduleInstCountEvent (Event * event, Tick count) pure virtual
Implemented in SimpleThread, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by ElasticTrace::regProbeListeners(), and BaseRemoteGDB::scheduleInstCommitEvent().
setCCReg()
virtual void ThreadContext::setCCReg (RegIndex reg_idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by ArmISA::copyRegs(), ArmISA::ISA::setMiscReg(), X86ISA::setRFlags(), ArmProcess32::setSyscallReturn(), ArmProcess64::setSyscallReturn(), and ArmV8KvmCPU::updateThreadContext().
setCCRegFlat()
virtual void ThreadContext::setCCRegFlat (RegIndex idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by X86ISA::copyRegs(), and unserialize().
setContextId()
virtual void ThreadContext::setContextId (ContextID id) pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by BaseCPU::registerThreadContexts(), and takeOverFrom().
setFloatReg()
virtual void ThreadContext::setFloatReg (RegIndex reg_idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by PowerISA::copyRegs(), AlphaISA::copyRegs(), SparcISA::copyRegs(), MipsISA::setRegOtherThread(), AlphaISA::RemoteGDB::AlphaGdbRegCache::setRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::setRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::setRegs(), ArmV8KvmCPU::updateThreadContext(), and updateThreadContextFPUCommon().
setFloatRegFlat()
virtual void ThreadContext::setFloatRegFlat (RegIndex idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyRegs(), X86ISA::copyRegs(), MipsISA::copyRegs(), unserialize(), and ArmKvmCPU::updateTCStateVFP().
setIntReg()
virtual void ThreadContext::setIntReg (RegIndex reg_idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, O3ThreadContext< Impl >, and Iris::ArmThreadContext.
Referenced by X86Linux::archClone(), SparcLinux::archClone(), RiscvLinux64::archClone(), AlphaLinux::archClone(), ArmLinux32::archClone(), RiscvLinux32::archClone(), ArmLinux64::archClone(), AlphaProcess::argsInit(), MipsProcess::argsInit(), RiscvProcess::argsInit(), PowerProcess::argsInit(), SparcProcess::argsInit(), ArmProcess::argsInit(), X86ISA::X86Process::argsInit(), cloneFunc(), PowerISA::copyRegs(), AlphaISA::copyRegs(), RiscvISA::copyRegs(), SparcISA::copyRegs(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), getgidPseudoFunc(), getpidPseudoFunc(), getuidPseudoFunc(), AlphaISA::initCPU(), X86ISA::initCPU(), AlphaProcess::initState(), SparcProcess::initState(), X86ISA::X86FaultBase::invoke(), ArmISA::ArmFault::invoke(), X86ISA::InitInterrupt::invoke(), pipeImpl(), ArmISA::ISA::setMiscReg(), MipsISA::setRegOtherThread(), AlphaISA::RemoteGDB::AlphaGdbRegCache::setRegs(), PowerISA::RemoteGDB::PowerGdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARCGdbRegCache::setRegs(), MipsISA::RemoteGDB::MipsGdbRegCache::setRegs(), RiscvISA::RemoteGDB::RiscvGdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::setRegs(), X86ISA::RemoteGDB::X86GdbRegCache::setRegs(), SparcISA::RemoteGDB::SPARC64GdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::setRegs(), PowerLinuxProcess::setSyscallArg(), AlphaProcess::setSyscallArg(), PowerProcess::setSyscallArg(), RiscvProcess::setSyscallArg(), MipsProcess::setSyscallArg(), ArmProcess32::setSyscallArg(), ArmProcess64::setSyscallArg(), Sparc32Process::setSyscallArg(), X86ISA::X86_64Process::setSyscallArg(), Sparc64Process::setSyscallArg(), X86ISA::I386Process::setSyscallArg(), AlphaProcess::setSyscallReturn(), PowerProcess::setSyscallReturn(), RiscvProcess::setSyscallReturn(), MipsProcess::setSyscallReturn(), SparcProcess::setSyscallReturn(), X86ISA::X86Process::setSyscallReturn(), ArmProcess32::setSyscallReturn(), ArmProcess64::setSyscallReturn(), and ArmV8KvmCPU::updateThreadContext().
setIntRegFlat()
virtual void ThreadContext::setIntRegFlat (RegIndex idx, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyRegs(), X86ISA::copyRegs(), MipsISA::copyRegs(), unserialize(), ArmKvmCPU::updateTCStateCore(), and ArmV8KvmCPU::updateThreadContext().
setMiscReg()
virtual void ThreadContext::setMiscReg (RegIndex misc_reg, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmLinux::archClone(), SparcLinux::archClone(), SparcISA::copyMiscRegs(), X86ISA::copyMiscRegs(), ArmISA::copyRegs(), SparcISA::copyRegs(), SparcISA::TLB::doMmuRegWrite(), SparcISA::doNormalFault(), SparcISA::doREDFault(), SparcISA::enterREDState(), Sparc32Process::flushWindows(), Sparc64Process::flushWindows(), X86KvmCPU::handleIOMiscReg32(), X86ISA::handleIprWrite(), X86ISA::initCPU(), SparcProcess::initState(), ArmProcess32::initState(), X86System::initState(), ArmProcess64::initState(), Sparc32Process::initState(), X86ISA::X86_64Process::initState(), Sparc64Process::initState(), X86ISA::I386Process::initState(), X86ISA::installSegDesc(), SparcISA::PowerOnReset::invoke(), RiscvISA::RiscvFault::invoke(), RiscvISA::Reset::invoke(), MipsISA::ResetFault::invoke(), ArmISA::ArmFault::invoke(), ArmISA::Reset::invoke(), X86ISA::PageFault::invoke(), X86ISA::InitInterrupt::invoke(), X86ISA::StartupInterrupt::invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::PCAlignmentFault::invoke(), ArmISA::ArmSev::invoke(), ArmISA::ArmFault::invoke64(), X86KvmCPU::kvmRunWrapper(), X86ISA::m5Syscall(), setContextSegment(), MipsISA::setRegOtherThread(), ArmISA::RemoteGDB::AArch32GdbRegCache::setRegs(), X86ISA::RemoteGDB::X86GdbRegCache::setRegs(), X86ISA::RemoteGDB::AMD64GdbRegCache::setRegs(), X86ISA::setRFlags(), ArmISA::ArmFault::setSyndrome(), setTLSFunc32(), setTLSFunc64(), ArmKvmCPU::updateTCStateCore(), ArmKvmCPU::updateTCStateVFP(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContext(), and X86KvmCPU::updateThreadContextMSRs().
setMiscRegNoEffect()
virtual void ThreadContext::setMiscRegNoEffect (RegIndex misc_reg, RegVal val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by X86Linux::archClone(), SparcLinux::archClone(), archPrctlFunc(), AlphaISA::copyIprs(), SparcISA::copyMiscRegs(), AlphaISA::copyMiscRegs(), X86ISA::copyMiscRegs(), ArmISA::copyRegs(), MipsISA::copyRegs(), SparcISA::doNormalFault(), SparcISA::doREDFault(), AlphaISA::initIPRs(), AlphaProcess::initState(), SparcProcess::initState(), RiscvProcess64::initState(), RiscvProcess32::initState(), X86ISA::X86_64Process::initState(), X86ISA::I386Process::initState(), AlphaISA::AlphaFault::invoke(), SparcISA::PowerOnReset::invoke(), AlphaISA::DtbFault::invoke(), MipsISA::CoprocessorUnusableFault::invoke(), MipsISA::AddressFault< TlbInvalidFault >::invoke(), ArmISA::ArmFault::invoke(), AlphaISA::ItbFault::invoke(), ArmISA::VirtualDataAbort::invoke(), MipsISA::setCauseIP(), MipsISA::MipsFaultBase::setExceptionState(), MipsISA::RemoteGDB::MipsGdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch32GdbRegCache::setRegs(), ArmISA::RemoteGDB::AArch64GdbRegCache::setRegs(), setThreadAreaFunc(), MipsISA::TlbFault< TlbInvalidFault >::setTlbExceptionState(), AlphaProcess::setupASNReg(), AlphaISA::Interrupts::updateIntrInfo(), ArmKvmCPU::updateTCStateCoProc(), ArmKvmCPU::updateTCStateCore(), ArmV8KvmCPU::updateThreadContext(), X86KvmCPU::updateThreadContextFPU(), updateThreadContextFPUCommon(), and X86KvmCPU::updateThreadContextXSave().
setNPC()
void ThreadContext::setNPC (Addr val) inline
Definition at line 276 of file thread_context.hh.
Referenced by execveFunc(), and CheckerThreadContext< TC >::setNPC().
setProcessPtr()
virtual void ThreadContext::setProcessPtr (Process * p) pure virtual
Implemented in SimpleThread, Iris::ThreadContext, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by cloneFunc(), and execveFunc().
setStatus()
virtual void ThreadContext::setStatus (Status new_status) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, and O3ThreadContext< Impl >.
Referenced by FullO3CPU< O3CPUImpl >::exitThreads(), FullO3CPU< O3CPUImpl >::insertThread(), and takeOverFrom().
setStCondFailures()
virtual void ThreadContext::setStCondFailures (unsigned sc_failures) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
setThreadId()
virtual void ThreadContext::setThreadId (int id) pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, CheckerThreadContext< TC >, and Iris::ThreadContext.
Referenced by takeOverFrom().
setVecElem()
virtual void ThreadContext::setVecElem (const RegId & reg, const VecElem & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecElemFlat()
virtual void ThreadContext::setVecElemFlat (RegIndex idx, const ElemIndex & elemIdx, const VecElem & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyVecRegs().
setVecLane() [1/4]
virtual void ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::Byte > & val) pure virtual
Write a lane of the destination vector register.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecLane() [2/4]
virtual void ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::TwoByte > & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecLane() [3/4]
virtual void ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::FourByte > & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecLane() [4/4]
virtual void ThreadContext::setVecLane (const RegId & reg, const LaneData< LaneSize::EightByte > & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecPredReg()
virtual void ThreadContext::setVecPredReg (const RegId & reg, const VecPredRegContainer & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecPredRegFlat()
virtual void ThreadContext::setVecPredRegFlat (RegIndex idx, const VecPredRegContainer & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by unserialize().
setVecReg()
virtual void ThreadContext::setVecReg (const RegId & reg, const VecRegContainer & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
setVecRegFlat()
virtual void ThreadContext::setVecRegFlat (RegIndex idx, const VecRegContainer & val) pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, O3ThreadContext< Impl >, and Iris::ThreadContext.
Referenced by ArmISA::copyVecRegs(), and unserialize().
socketId()
virtual uint32_t ThreadContext::socketId () const pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by ArmISA::getMPIDR().
status()
virtual Status ThreadContext::status () const pure virtual
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by Minor::Execute::commitInst(), SimpleThread::copyState(), BaseKvmCPU::drainResume(), Minor::Fetch1::getScheduledThread(), Shader::hostWakeUp(), Minor::Execute::issue(), DistIface::SyncEvent::process(), SparcISA::ISA::processHSTickCompare(), SparcISA::ISA::processSTickCompare(), takeOverFrom(), DistIface::toggleSync(), Minor::Execute::tryToBranch(), and PseudoInst::wakeCPU().
suspend()
virtual void ThreadContext::suspend () pure virtual
Set the status to Suspended.
Implemented in SimpleThread, CheckerThreadContext< TC >, Iris::ThreadContext, and O3ThreadContext< Impl >.
Referenced by quiesce(), quiesceTick(), SparcISA::ISA::setFSReg(), X86ISA::startupCPU(), FutexMap::suspend(), and FutexMap::suspend_bitset().
syscall()
virtual void ThreadContext::syscall (int64_t callnum, Fault * fault) pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, Iris::ThreadContext, and CheckerThreadContext< TC >.
Referenced by SparcISA::Sparc32LinuxProcess::handleTrap(), SparcISA::Sparc64LinuxProcess::handleTrap(), ArmISA::SupervisorCall::invoke(), RiscvISA::SyscallFault::invokeSE(), and X86ISA::m5Syscall().
takeOverFrom()
virtual void ThreadContext::takeOverFrom (ThreadContext * old_context) pure virtual
Implemented in CheckerThreadContext< TC >, O3ThreadContext< Impl >, and SimpleThread.
Referenced by BaseCPU::takeOverFrom().
threadId()
virtual int ThreadContext::threadId () const pure virtual
Implemented in SimpleThread, O3ThreadContext< Impl >, CheckerThreadContext< TC >, and Iris::ThreadContext.
Referenced by BaseCPU::checkInterrupts(), cloneFunc(), SimpleThread::copyState(), Shader::hostWakeUp(), ArmISA::Reset::invoke(), ArmISA::AbortFault< DataAbort >::invoke(), ArmISA::SystemError::invoke(), ArmISA::ArmSev::invoke(), RiscvISA::ISA::readMiscReg(), ArmISA::ISA::readMiscReg(), ArmISA::sendEvent(), RiscvISA::ISA::setMiscReg(), BaseCPU::takeOverFrom(), and takeOverFrom().
The documentation for this class was generated from the following files:
cpu/thread_context.hh
cpu/thread_context.cc