gem5: ProbePointArg< Arg > Class Template Reference
ProbePointArg< Arg > Class Template Reference
ProbePointArg generates a point for the class of Arg.
#include <thermal_domain.hh>
Public Member Functions
ProbePointArg (ProbeManager *manager, std::string name)
void addListener (ProbeListener *l)
adds a ProbeListener to this ProbePoints notify list.
void removeListener (ProbeListener *l)
remove a ProbeListener from this ProbePoints notify list.
void notify (const Arg &arg)
called at the ProbePoint call site, passes arg to each listener.
Public Member Functions inherited from ProbePoint
ProbePoint (ProbeManager *manager, const std::string &name)
virtual ~ProbePoint ()
std::string getName () const
Private Attributes
std::vector< ProbeListenerArgBase< Arg > * > listeners
The attached listeners.
Additional Inherited Members
Protected Attributes inherited from ProbePoint
const std::string name
Detailed Description
template<typename Arg>
class ProbePointArg< Arg >
ProbePointArg generates a point for the class of Arg.
As ProbePointArgs talk directly to ProbeListenerArgs of the same type, we can store the vector of ProbeListeners as their Arg type (and not as base type).
Methods are provided to addListener, removeListener and notify.
Definition at line 52 of file thermal_domain.hh.
Constructor & Destructor Documentation
ProbePointArg()
template<typename Arg> ProbePointArg< Arg >::ProbePointArg (ProbeManager * manager, std::string name) inline
Definition at line 257 of file probe.hh.
Member Function Documentation
addListener()
template<typename Arg> void ProbePointArg< Arg >::addListener (ProbeListener * l) inline virtual
adds a ProbeListener to this ProbePoints notify list.
Parameters
l the ProbeListener to add to the notify list.
Implements ProbePoint.
Definition at line 266 of file probe.hh.
notify()
template<typename Arg> void ProbePointArg< Arg >::notify (const Arg & arg) inline
called at the ProbePoint call site, passes arg to each listener.
Parameters
arg the argument to pass to each listener.
Definition at line 288 of file probe.hh.
Referenced by DefaultCommit< Impl >::commitInsts(), DefaultIEW< Impl >::dispatchInsts(), ThermalDomain::emitUpdate(), DefaultIEW< Impl >::executeInsts(), DefaultFetch< Impl >::fetch(), DefaultFetch< Impl >::finishTranslation(), DefaultFetch< Impl >::recvReqRetry(), DefaultRename< Impl >::renameInsts(), DefaultCommit< Impl >::tick(), BaseCPU::updateCycleCounters(), and DefaultIEW< Impl >::writebackInsts().
removeListener()
template<typename Arg> void ProbePointArg< Arg >::removeListener (ProbeListener * l) inline virtual
remove a ProbeListener from this ProbePoints notify list.
Parameters
l the ProbeListener to remove from the notify list.
Implements ProbePoint.
Definition at line 278 of file probe.hh.
Member Data Documentation
listeners
template<typename Arg> std::vector<ProbeListenerArgBase<Arg> *> ProbePointArg< Arg >::listeners private
The attached listeners.
Definition at line 254 of file probe.hh.
The documentation for this class was generated from the following files:
sim/power/thermal_domain.hh
sim/probe/probe.hh