gem5: AtomicRequestProtocol Class Reference
AtomicRequestProtocol Class Reference abstract
#include <atomic.hh>
Protected Member Functions
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
virtual Tick recvAtomicSnoop (PacketPtr pkt)=0
Receive an atomic snoop request packet from our peer.
Friends
class AtomicResponseProtocol
Detailed Description
Definition at line 53 of file atomic.hh.
Member Function Documentation
recvAtomicSnoop()
virtual Tick AtomicRequestProtocol::recvAtomicSnoop (PacketPtr pkt) protected pure virtual
Receive an atomic snoop request packet from our peer.
Implemented in BaseCache::MemSidePort, MasterPort, CoherentXBar::CoherentXBarMasterPort, AtomicSimpleCPU::AtomicCPUDPort, BaseTrafficGen::TrafficGenPort, CommMonitor::MonitorMasterPort, AddrMapper::MapperMasterPort, MemTest::CpuPort, MemCheckerMonitor::MonitorMasterPort, and MemDelay::MasterPort.
Referenced by AtomicResponseProtocol::sendSnoop().
send()
Tick AtomicRequestProtocol::send (AtomicResponseProtocol * peer, PacketPtr pkt) protected
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters
peer Peer to send packet to.
pkt Packet to send.
Returns
Estimated latency of access.
Definition at line 52 of file atomic.cc.
References Packet::isRequest(), and AtomicResponseProtocol::recvAtomic().
Referenced by TraceCPU::FixedRetryGen::name(), and MasterPort::sendAtomic().
sendBackdoor()
Tick AtomicRequestProtocol::sendBackdoor (AtomicResponseProtocol * peer, PacketPtr pkt, MemBackdoorPtr & backdoor) protected
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Parameters
peer Peer to send packet to.
pkt Packet to send.
backdoor Can be set to a back door pointer by the target to let caller have direct access to the requested data.
Returns
Estimated latency of access.
Definition at line 59 of file atomic.cc.
References Packet::isRequest(), and AtomicResponseProtocol::recvAtomicBackdoor().
Referenced by MasterPort::sendAtomicBackdoor().
Friends And Related Function Documentation
AtomicResponseProtocol
friend class AtomicResponseProtocol friend
Definition at line 55 of file atomic.hh.
The documentation for this class was generated from the following files:
mem/protocol/atomic.hh
mem/protocol/atomic.cc