gem5: DictionaryCompressor< T > Class Template Reference
DictionaryCompressor< T > Class Template Reference abstract
A template version of the dictionary compressor that allows to choose the dictionary size.
#include <dictionary_compressor.hh>
Classes
class CompData
class DeltaPattern
A pattern that checks whether the difference of the value and the dictionary entries' is below a certain threshold.
struct Factory
Create a factory to determine if input matches a pattern.
struct Factory< Head >
Specialization to end the recursion.
class LocatedMaskedPattern
A pattern that narrows the MaskedPattern by allowing a only single possible dictionary entry to be matched against.
class MaskedPattern
A pattern that compares masked values against dictionary entries.
class MaskedValuePattern
A pattern that compares masked values to a masked portion of a fixed value.
class Pattern
The compressed data is composed of multiple pattern entries.
class RepeatedValuePattern
A pattern that checks if dictionary entry sized values are solely composed of multiple copies of a single value.
class UncompressedPattern
A pattern containing the original uncompressed data.
Public Types
typedef BaseDictionaryCompressorParams Params
Public Types inherited from BaseDictionaryCompressor
typedef BaseDictionaryCompressorParams Params
Public Types inherited from BaseCacheCompressor
typedef BaseCacheCompressorParams Params
Convenience typedef.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
DictionaryCompressor (const Params *p)
~DictionaryCompressor ()=default
Public Member Functions inherited from BaseDictionaryCompressor
BaseDictionaryCompressor (const Params *p)
~BaseDictionaryCompressor ()=default
void regStats () override
Register local statistics.
Public Member Functions inherited from BaseCacheCompressor
BaseCacheCompressor (const Params *p)
Default constructor.
virtual ~BaseCacheCompressor ()
Default destructor.
void compress (const uint64_t *data, Cycles &comp_lat, Cycles &decomp_lat, std::size_t &comp_size_bits)
Apply the compression process to the cache line.
Cycles getDecompressionLatency (const CacheBlk *blk) const
Get the decompression latency if the block is compressed.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Types
typedef std::array< uint8_t, sizeof(T)> DictionaryEntry
Convenience typedef for a dictionary entry.
Protected Member Functions
virtual std::unique_ptr< Pattern > getPattern (const DictionaryEntry &bytes, const DictionaryEntry &dict_bytes, const int match_location) const =0
Since the factory cannot be instantiated here, classes that inherit from this base class have to implement the call to their factory's getPattern.
std::unique_ptr< Pattern > compressValue (const T data)
Compress data.
T decompressValue (const Pattern *pattern)
Decompress a pattern into a value that fits in a dictionary entry.
virtual void resetDictionary ()
Clear all dictionary entries.
virtual void addToDictionary (const DictionaryEntry data)=0
Add an entry to the dictionary.
std::unique_ptr< BaseCacheCompressor::CompressionData > compress (const uint64_t *data)
Apply compression.
void decompress (const CompressionData *comp_data, uint64_t *data) override
Decompress data.
Protected Member Functions inherited from BaseDictionaryCompressor
virtual uint64_t getNumPatterns () const =0
Trick function to get the number of patterns.
virtual std::string getName (int number) const =0
Get meta-name assigned to the given pattern.
Protected Member Functions inherited from BaseCacheCompressor
virtual std::unique_ptr< CompressionData > compress (const uint64_t *cache_line, Cycles &comp_lat, Cycles &decomp_lat)=0
Apply the compression process to the cache line.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Static Protected Member Functions
static DictionaryEntry toDictionaryEntry (T value)
Turn a value into a dictionary entry.
static T fromDictionaryEntry (const DictionaryEntry &entry)
Turn a dictionary entry into a value.
Protected Attributes
std::vector< DictionaryEntry > dictionary
The dictionary.
Protected Attributes inherited from BaseDictionaryCompressor
const std::size_t dictionarySize
Dictionary size.
std::size_t numEntries
Number of valid entries in the dictionary.
Stats::Vector patternStats
Number of data entries that were compressed to each pattern.
Protected Attributes inherited from BaseCacheCompressor
const std::size_t blkSize
Uncompressed cache line size (in bytes).
const std::size_t sizeThreshold
Size in bytes at which a compression is classified as bad and therefore the compressed block is restored to its uncompressed format.
Stats::Vector compressionSize
Number of blocks that were compressed to this power of two size.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from BaseCacheCompressor
static void setDecompressionLatency (CacheBlk *blk, const Cycles lat)
Set the decompression latency of compressed block.
static void setSizeBits (CacheBlk *blk, const std::size_t size_bits)
Set the size of the compressed block, in bits.
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
template<class T>
class DictionaryCompressor< T >
A template version of the dictionary compressor that allows to choose the dictionary size.
Template Parameters
The type of a dictionary entry (e.g., uint16_t, uint32_t, etc).
Definition at line 112 of file dictionary_compressor.hh.
Member Typedef Documentation
DictionaryEntry
template<class T> typedef std::array<uint8_t, sizeof(T)> DictionaryCompressor< T >::DictionaryEntry protected
Convenience typedef for a dictionary entry.
Definition at line 116 of file dictionary_compressor.hh.
Params
template<class T> typedef BaseDictionaryCompressorParams DictionaryCompressor< T >::Params
Definition at line 258 of file dictionary_compressor.hh.
Constructor & Destructor Documentation
DictionaryCompressor()
template<class T > DictionaryCompressor< T >::DictionaryCompressor (const Params * p)
Definition at line 62 of file dictionary_compressor_impl.hh.
~DictionaryCompressor()
template<class T> DictionaryCompressor< T >::~DictionaryCompressor () default
Member Function Documentation
addToDictionary()
template<class T> virtual void DictionaryCompressor< T >::addToDictionary (const DictionaryEntry data) protected pure virtual
Add an entry to the dictionary.
Parameters
data The new entry.
Referenced by DictionaryCompressor< uint64_t >::compressValue(), and DictionaryCompressor< uint64_t >::decompressValue().
compress()
template<class T > std::unique_ptr< BaseCacheCompressor::CompressionData > DictionaryCompressor< T >::compress (const uint64_t * data) protected
Apply compression.
Parameters
data The cache line to be compressed.
Returns
Cache line after compression.
Definition at line 118 of file dictionary_compressor_impl.hh.
Referenced by RepeatedQwordsCompressor::compress(), ZeroCompressor::compress(), CPack::compress(), BaseDelta< uint64_t, 16 >::compress(), and FPCD::compress().
compressValue()
template<typename T> std::unique_ptr< typename DictionaryCompressor< T >::Pattern > DictionaryCompressor< T >::compressValue (const T data) protected
Compress data.
Parameters
data Data to be compressed.
Returns
The pattern this data matches.
Definition at line 83 of file dictionary_compressor_impl.hh.
Referenced by DictionaryCompressor< uint64_t >::compress().
decompress()
template<class T > void DictionaryCompressor< T >::decompress (const CompressionData * comp_data, uint64_t * data) override protected virtual
Decompress data.
Parameters
comp_data Compressed cache line.
data The cache line to be decompressed.
Implements BaseCacheCompressor.
Definition at line 161 of file dictionary_compressor_impl.hh.
decompressValue()
template<class T > T DictionaryCompressor< T >::decompressValue (const Pattern * pattern) protected
Decompress a pattern into a value that fits in a dictionary entry.
Parameters
pattern The pattern to be decompressed.
Returns
The decompressed word.
Definition at line 142 of file dictionary_compressor_impl.hh.
Referenced by DictionaryCompressor< uint64_t >::decompress().
fromDictionaryEntry()
template<class T > T DictionaryCompressor< T >::fromDictionaryEntry (const DictionaryEntry & entry) static protected
Turn a dictionary entry into a value.
Parameters
The dictionary entry to turn.
Returns
The value that the dictionary entry contained.
Definition at line 203 of file dictionary_compressor_impl.hh.
Referenced by DictionaryCompressor< T >::MaskedPattern< mask >::decompress(), DictionaryCompressor< uint64_t >::decompressValue(), DictionaryCompressor< T >::MaskedPattern< mask >::isPattern(), DictionaryCompressor< T >::MaskedValuePattern< 0, 0xFFFFFFFFFFFFFFFF >::isPattern(), DictionaryCompressor< T >::RepeatedValuePattern< RepT >::isPattern(), and DictionaryCompressor< T >::DeltaPattern< DeltaSizeBits >::isValidDelta().
getPattern()
template<class T> virtual std::unique_ptr<Pattern> DictionaryCompressor< T >::getPattern (const DictionaryEntry & bytes, const DictionaryEntry & dict_bytes, const int match_location) const protected pure virtual
Since the factory cannot be instantiated here, classes that inherit from this base class have to implement the call to their factory's getPattern.
Referenced by DictionaryCompressor< uint64_t >::compressValue().
resetDictionary()
template<class T > void DictionaryCompressor< T >::resetDictionary () protected virtual
Clear all dictionary entries.
Reimplemented in BaseDelta< BaseType, DeltaSizeBits >, BaseDelta< uint64_t, 32 >, BaseDelta< uint32_t, 16 >, BaseDelta< uint32_t, 8 >, BaseDelta< uint64_t, 8 >, BaseDelta< uint16_t, 8 >, and BaseDelta< uint64_t, 16 >.
Definition at line 72 of file dictionary_compressor_impl.hh.
Referenced by DictionaryCompressor< uint64_t >::compress(), DictionaryCompressor< uint64_t >::decompress(), DictionaryCompressor< uint64_t >::DictionaryCompressor(), and BaseDelta< uint64_t, 16 >::resetDictionary().
toDictionaryEntry()
template<class T> DictionaryCompressor< T >::DictionaryEntry DictionaryCompressor< T >::toDictionaryEntry (T value) static protected
Turn a value into a dictionary entry.
Parameters
value The value to turn.
Returns
A dictionary entry containing the value.
Definition at line 191 of file dictionary_compressor_impl.hh.
Referenced by DictionaryCompressor< uint64_t >::compressValue(), DictionaryCompressor< T >::MaskedPattern< mask >::decompress(), DictionaryCompressor< T >::RepeatedValuePattern< RepT >::decompress(), and DictionaryCompressor< uint64_t >::resetDictionary().
Member Data Documentation
dictionary
template<class T> std::vector<DictionaryEntry> DictionaryCompressor< T >::dictionary protected
The dictionary.
Definition at line 187 of file dictionary_compressor.hh.
Referenced by DictionaryCompressor< uint64_t >::compressValue(), DictionaryCompressor< uint64_t >::decompressValue(), DictionaryCompressor< uint64_t >::DictionaryCompressor(), and DictionaryCompressor< uint64_t >::resetDictionary().
The documentation for this class was generated from the following files:
mem/cache/compressors/dictionary_compressor.hh
mem/cache/compressors/dictionary_compressor_impl.hh