gem5: VirtIODeviceBase Class Reference
VirtIODeviceBase Class Reference
Base class for all VirtIO-based devices.
#include <base.hh>
Public Types
typedef uint16_t QueueID
typedef uint32_t FeatureBits
typedef uint16_t VirtAddress
This is a VirtQueue address as exposed through the low-level interface. The address needs to be multiplied by the page size (seems to be hardcoded to 4096 in the spec) to get the real physical address.
typedef uint16_t DeviceId
Device Type (sometimes known as subsystem ID)
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
BitUnion8 (DeviceStatus) Bitfield< 7 > failed
EndBitUnion (DeviceStatus) typedef VirtIODeviceBaseParams Params
VirtIODeviceBase (Params *params, DeviceId id, size_t config_size, FeatureBits features)
virtual ~VirtIODeviceBase ()
SimObject Interfaces
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Optional VirtIO Interfaces
virtual void readConfig (PacketPtr pkt, Addr cfgOffset)
Read from the configuration space of a device.
virtual void writeConfig (PacketPtr pkt, Addr cfgOffset)
Write to the configuration space of a device.
virtual void reset ()
Driver-request device reset.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
Bitfield< 2 > driver_ok
Bitfield< 1 > driver
Bitfield< 0 > acknowledge
Private Member Functions
const VirtQueue & getCurrentQueue () const
Convenience method to get the currently selected queue.
VirtQueue & getCurrentQueue ()
Convenience method to get the currently selected queue.
Private Attributes
DeviceStatus _deviceStatus
Status of the device.
QueueID _queueSelect
Queue select register (set by guest)
std::vector< VirtQueue * > _queues
List of virtual queues supported by this device.
Callback * transKick
Callbacks to kick the guest through the transport layer.
Device Model Interfaces
FeatureBits guestFeatures
Feature set accepted by the guest.
void kick ()
Inform the guest of available buffers.
void registerQueue (VirtQueue &queue)
Register a new VirtQueue with the device model.
Device Model Helpers
ByteOrder byteOrder
The byte order of the queues, descriptors, etc.
void readConfigBlob (PacketPtr pkt, Addr cfgOffset, const uint8_t *cfg)
Read configuration data from a device structure.
void writeConfigBlob (PacketPtr pkt, Addr cfgOffset, uint8_t *cfg)
Write configuration data to a device structure.
VirtIO Transport Interfaces
const DeviceId deviceId
Device ID (sometimes known as subsystem ID)
const size_t configSize
Size of the device's configuration space.
const FeatureBits deviceFeatures
Feature set offered by the device.
void registerKickCallback (Callback *c)
Register a callback to kick the guest through the transport interface.
void onNotify (QueueID index)
Driver is requesting service.
void setQueueSelect (QueueID idx)
Change currently active queue.
QueueID getQueueSelect () const
Get the currently active queue.
void setQueueAddress (uint32_t address)
Change the host physical address of the currently active queue.
uint32_t getQueueAddress () const
Get the host physical address of the currently active queue.
uint16_t getQueueSize () const
Get the size (descriptors) of the currently active queue.
void setDeviceStatus (DeviceStatus status)
Update device status and optionally reset device.
DeviceStatus getDeviceStatus () const
Retrieve the device status.
void setGuestFeatures (FeatureBits features)
Set feature bits accepted by the guest driver.
FeatureBits getGuestFeatures () const
Get features accepted by the guest driver.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Base class for all VirtIO-based devices.
This class implements the functionality of the VirtIO 0.9.5 specification. This version of VirtIO is also known as "legacy" in the VirtIO 1.0 specification from OASIS.
See also
https://github.com/rustyrussell/virtio-spec
http://docs.oasis-open.org/virtio/virtio/v1.0/virtio-v1.0.html
Definition at line 560 of file base.hh.
Member Typedef Documentation
DeviceId
typedef uint16_t VirtIODeviceBase::DeviceId
Device Type (sometimes known as subsystem ID)
Definition at line 572 of file base.hh.
FeatureBits
typedef uint32_t VirtIODeviceBase::FeatureBits
Definition at line 564 of file base.hh.
QueueID
typedef uint16_t VirtIODeviceBase::QueueID
Definition at line 563 of file base.hh.
VirtAddress
typedef uint16_t VirtIODeviceBase::VirtAddress
This is a VirtQueue address as exposed through the low-level interface. The address needs to be multiplied by the page size (seems to be hardcoded to 4096 in the spec) to get the real physical address.
Definition at line 570 of file base.hh.
Constructor & Destructor Documentation
VirtIODeviceBase()
VirtIODeviceBase::VirtIODeviceBase (Params * params, DeviceId id, size_t config_size, FeatureBits features)
Definition at line 327 of file base.cc.
~VirtIODeviceBase()
VirtIODeviceBase::~VirtIODeviceBase () virtual
Definition at line 339 of file base.cc.
Member Function Documentation
BitUnion8()
VirtIODeviceBase::BitUnion8 (DeviceStatus)
EndBitUnion()
VirtIODeviceBase::EndBitUnion (DeviceStatus)
getCurrentQueue() [1/2]
const VirtQueue & VirtIODeviceBase::getCurrentQueue () const private
Convenience method to get the currently selected queue.
Definition at line 448 of file base.cc.
References _queues, _queueSelect, and panic.
Referenced by getQueueAddress(), and setQueueAddress().
getCurrentQueue() [2/2]
VirtQueue & VirtIODeviceBase::getCurrentQueue () private
Convenience method to get the currently selected queue.
Definition at line 457 of file base.cc.
References _queues, _queueSelect, and panic.
getDeviceStatus()
DeviceStatus VirtIODeviceBase::getDeviceStatus () const inline
Retrieve the device status.
Returns
Device status.
Definition at line 824 of file base.hh.
Referenced by PciVirtIO::read(), and MmioVirtIO::read().
getGuestFeatures()
FeatureBits VirtIODeviceBase::getGuestFeatures () const inline
Get features accepted by the guest driver.
Returns
Currently active features.
Definition at line 839 of file base.hh.
Referenced by PciVirtIO::read(), and MmioVirtIO::read().
getQueueAddress()
uint32_t VirtIODeviceBase::getQueueAddress () const
Get the host physical address of the currently active queue.
Note
The new address is specified in multiples of the page size (fixed to 4096 bytes in the standard). For example, if the address 10 is selected, the actual host physical address will be 40960.
See also
setQueueSelect
getQueueSelect
Returns
Address of the currently active queue (in pages).
Definition at line 472 of file base.cc.
References VirtQueue::ALIGN_BITS, and getCurrentQueue().
Referenced by PciVirtIO::read(), and MmioVirtIO::read().
getQueueSelect()
QueueID VirtIODeviceBase::getQueueSelect () const inline
Get the currently active queue.
The transport interface works on a queue at a time. The currently active queue is decided by the value of the queue select field in a device.
Returns
The ID of the currently active queue.
Definition at line 769 of file base.hh.
Referenced by PciVirtIO::read(), and MmioVirtIO::read().
getQueueSize()
uint16_t VirtIODeviceBase::getQueueSize () const inline
Get the size (descriptors) of the currently active queue.
Returns
Size of the currently active queue in number of descriptors.
Definition at line 807 of file base.hh.
References ArmISA::status.
Referenced by PciVirtIO::read(), and MmioVirtIO::read().
kick()
void VirtIODeviceBase::kick () inline protected
Inform the guest of available buffers.
When a device model has finished processing incoming buffers (after onNotify has been called), it typically needs to inform the guest that there are new pending outgoing buffers. The method used to inform the guest is transport dependent, but is typically through an interrupt. Device models call this method to tell the transport interface to notify the guest.
Definition at line 610 of file base.hh.
References VirtDescriptor::queue.
Referenced by VirtIO9PBase::sendRMsg().
onNotify()
void VirtIODeviceBase::onNotify (QueueID index)
Driver is requesting service.
This method is called by the underlying hardware interface (e.g., PciVirtIO or MmmioVirtIO) to notify a device of pending incoming descriptors.
Parameters
index ID of the queue with pending actions.
Definition at line 375 of file base.cc.
References _queues, DPRINTF, and panic.
Referenced by PciVirtIO::write(), and MmioVirtIO::write().
readConfig()
void VirtIODeviceBase::readConfig (PacketPtr pkt, Addr cfgOffset) virtual
Read from the configuration space of a device.
This method is called by the transport interface to read data from a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
Reimplemented in VirtIO9PBase, VirtIOBlock, and VirtIOConsole.
Definition at line 411 of file base.cc.
References panic.
Referenced by MmioVirtIO::read(), and PciVirtIO::read().
readConfigBlob()
void VirtIODeviceBase::readConfigBlob (PacketPtr pkt, Addr cfgOffset, const uint8_t * cfg) protected
Read configuration data from a device structure.
Parameters
pkt Read request packet.
cfgOffset Offset into the device's configuration space.
cfg Device configuration
Definition at line 423 of file base.cc.
References configSize, Packet::getSize(), Packet::makeResponse(), panic, and Packet::setData().
Referenced by VirtIOConsole::readConfig(), VirtIOBlock::readConfig(), and VirtIO9PBase::readConfig().
registerKickCallback()
void VirtIODeviceBase::registerKickCallback (Callback * c) inline
Register a callback to kick the guest through the transport interface.
Parameters
c Callback into transport interface.
Definition at line 732 of file base.hh.
References ArmISA::c, and VirtDescriptor::index().
Referenced by MmioVirtIO::MmioVirtIO(), and PciVirtIO::PciVirtIO().
registerQueue()
void VirtIODeviceBase::registerQueue (VirtQueue & queue) protected
Register a new VirtQueue with the device model.
Devices typically register at least one VirtQueue to use for communication with the guest. This must be done from the constructor since the number of queues are assumed to be constant throughout the lifetime of the device.
Warning
This method may only be called from the device model constructor.
Definition at line 480 of file base.cc.
References _queues.
Referenced by VirtIO9PBase::VirtIO9PBase(), VirtIOBlock::VirtIOBlock(), and VirtIOConsole::VirtIOConsole().
reset()
void VirtIODeviceBase::reset () virtual
Driver-request device reset.
The device driver may reset a device by writing zero to the device status register (using setDeviceStatus()), which causes this method to be called. Device models overriding this method must ensure that the reset method of the base class is called when the device is reset.
Note
Always call the reset method of the base class from device-specific reset methods.
Definition at line 364 of file base.cc.
References _deviceStatus, _queues, _queueSelect, guestFeatures, and ArmISA::i.
Referenced by setDeviceStatus().
serialize()
void VirtIODeviceBase::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in VirtIO9PProxy.
Definition at line 344 of file base.cc.
References _deviceStatus, _queues, _queueSelect, csprintf(), guestFeatures, ArmISA::i, SERIALIZE_SCALAR, and Serializable::serializeSection().
Referenced by VirtIO9PProxy::serialize().
setDeviceStatus()
void VirtIODeviceBase::setDeviceStatus (DeviceStatus status)
Update device status and optionally reset device.
The special device status of 0 is used to reset the device by calling reset().
Parameters
status New device status.
Definition at line 401 of file base.cc.
References _deviceStatus, DPRINTF, reset(), and ArmISA::status.
Referenced by PciVirtIO::write(), and MmioVirtIO::write().
setGuestFeatures()
void VirtIODeviceBase::setGuestFeatures (FeatureBits features)
Set feature bits accepted by the guest driver.
This enables a subset of the features offered by the device model through the getGuestFeatures() interface.
Definition at line 387 of file base.cc.
References deviceFeatures, DPRINTF, guestFeatures, and panic.
Referenced by PciVirtIO::write(), and MmioVirtIO::write().
setQueueAddress()
void VirtIODeviceBase::setQueueAddress (uint32_t address)
Change the host physical address of the currently active queue.
Note
The new address is specified in multiples of the page size (fixed to 4096 bytes in the standard). For example, if the address 10 is selected, the actual host physical address will be 40960.
See also
setQueueSelect
getQueueSelect
Parameters
address New address of the currently active queue (in pages).
Definition at line 466 of file base.cc.
References VirtQueue::ALIGN_SIZE, getCurrentQueue(), and VirtQueue::setAddress().
Referenced by PciVirtIO::write(), and MmioVirtIO::write().
setQueueSelect()
void VirtIODeviceBase::setQueueSelect (QueueID idx) inline
Change currently active queue.
The transport interface works on a queue at a time. The currently active queue is decided by the value of the queue select field in a device.
Parameters
idx ID of the queue to select.
Definition at line 759 of file base.hh.
Referenced by PciVirtIO::write(), and MmioVirtIO::write().
unserialize()
void VirtIODeviceBase::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Reimplemented in VirtIO9PProxy.
Definition at line 354 of file base.cc.
References _deviceStatus, _queues, _queueSelect, csprintf(), guestFeatures, ArmISA::i, UNSERIALIZE_SCALAR, and Serializable::unserializeSection().
Referenced by VirtIO9PProxy::unserialize().
writeConfig()
void VirtIODeviceBase::writeConfig (PacketPtr pkt, Addr cfgOffset) virtual
Write to the configuration space of a device.
This method is called by the transport interface to write data into a device model's configuration space. The device model should use the cfgOffset parameter as the offset into its configuration space.
Warning
The address in the packet should not be used to determine the offset into a device's configuration space.
Parameters
pkt Write request packet.
cfgOffset Offset into the device's configuration space.
Definition at line 417 of file base.cc.
References panic.
Referenced by MmioVirtIO::write(), and PciVirtIO::write().
writeConfigBlob()
void VirtIODeviceBase::writeConfigBlob (PacketPtr pkt, Addr cfgOffset, uint8_t * cfg) protected
Write configuration data to a device structure.
Parameters
pkt Write request packet.
cfgOffset Offset into the device's configuration space.
cfg Device configuration
Definition at line 435 of file base.cc.
References configSize, Packet::getSize(), Packet::makeResponse(), panic, and Packet::writeData().
Member Data Documentation
_deviceStatus
DeviceStatus VirtIODeviceBase::_deviceStatus private
Status of the device.
See also
getDeviceStatus
setDeviceStatus
Definition at line 863 of file base.hh.
Referenced by reset(), serialize(), setDeviceStatus(), and unserialize().
_queues
std::vector<VirtQueue *> VirtIODeviceBase::_queues private
List of virtual queues supported by this device.
Definition at line 869 of file base.hh.
Referenced by getCurrentQueue(), onNotify(), registerQueue(), reset(), serialize(), and unserialize().
_queueSelect
QueueID VirtIODeviceBase::_queueSelect private
Queue select register (set by guest)
Definition at line 866 of file base.hh.
Referenced by getCurrentQueue(), reset(), serialize(), and unserialize().
acknowledge
Bitfield<0> VirtIODeviceBase::acknowledge
Definition at line 578 of file base.hh.
byteOrder
ByteOrder VirtIODeviceBase::byteOrder protected
The byte order of the queues, descriptors, etc.
Definition at line 718 of file base.hh.
Referenced by VirtIOBlock::RequestQueue::onNotifyDescriptor(), VirtIOConsole::readConfig(), VirtIOBlock::readConfig(), and VirtIO9PBase::VirtIO9PBase().
configSize
const size_t VirtIODeviceBase::configSize
Size of the device's configuration space.
Definition at line 845 of file base.hh.
Referenced by PciVirtIO::PciVirtIO(), readConfigBlob(), VirtIO9PBase::VirtIO9PBase(), and writeConfigBlob().
deviceFeatures
const FeatureBits VirtIODeviceBase::deviceFeatures
Feature set offered by the device.
Definition at line 848 of file base.hh.
Referenced by PciVirtIO::read(), MmioVirtIO::read(), and setGuestFeatures().
deviceId
const DeviceId VirtIODeviceBase::deviceId
Device ID (sometimes known as subsystem ID)
Definition at line 842 of file base.hh.
Referenced by PciVirtIO::PciVirtIO(), and MmioVirtIO::read().
driver
Bitfield<1> VirtIODeviceBase::driver
Definition at line 577 of file base.hh.
driver_ok
Bitfield<2> VirtIODeviceBase::driver_ok
Definition at line 576 of file base.hh.
guestFeatures
FeatureBits VirtIODeviceBase::guestFeatures protected
Feature set accepted by the guest.
When the guest starts the driver for the device, it starts by negotiating features. The device first offers a set of features (see deviceFeatures), the driver then notifies the device of which features it accepted. The base class will automatically accept any feature set that is a subset of the features offered by the device.
Definition at line 639 of file base.hh.
Referenced by reset(), serialize(), setGuestFeatures(), and unserialize().
transKick
Callback* VirtIODeviceBase::transKick private
Callbacks to kick the guest through the transport layer.
Definition at line 872 of file base.hh.
The documentation for this class was generated from the following files:
dev/virtio/base.hh
dev/virtio/base.cc