gem5: DistIface::SyncNode Class Reference
DistIface::SyncNode Class Reference
Public Member Functions
SyncNode ()
~SyncNode ()
bool run (bool same_tick) override
Core method to perform a full dist sync.
bool progress (Tick max_req_tick, Tick next_repeat, ReqType do_ckpt, ReqType do_exit, ReqType do_stop_sync) override
Callback when the receiver thread gets a sync ack message.
void requestCkpt (ReqType req) override
void requestExit (ReqType req) override
void requestStopSync (ReqType req) override
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from DistIface::Sync
void init (Tick start, Tick repeat)
Initialize periodic sync params.
void abort ()
Abort processing an on-going sync event (in case of an error, e.g.
void drainComplete ()
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Attributes
ReqType needExit
Exit requested.
ReqType needCkpt
Ckpt requested.
ReqType needStopSync
Sync stop requested.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from DistIface::Sync
std::mutex lock
The lock to protect access to the Sync object.
std::condition_variable cv
Condition variable for the simulation thread to wait on until all receiver threads completes the current global synchronisation.
unsigned waitNum
Number of receiver threads that not yet completed the current global synchronisation.
bool doExit
Flag is set if exit is permitted upon sync completion.
bool doCkpt
Flag is set if taking a ckpt is permitted upon sync completion.
bool doStopSync
Flag is set if sync is to stop upon sync completion.
Tick nextRepeat
The repeat value for the next periodic sync.
Tick nextAt
Tick for the next periodic sync (if the event is not scheduled yet)
bool isAbort
Flag is set if the sync is aborted (e.g.
Detailed Description
Definition at line 205 of file dist_iface.hh.
Constructor & Destructor Documentation
SyncNode()
DistIface::SyncNode::SyncNode ()
Definition at line 111 of file dist_iface.cc.
References Stats::none.
~SyncNode()
DistIface::SyncNode::~SyncNode () inline
Definition at line 224 of file dist_iface.hh.
References DistIface::Sync::progress(), DistIface::Sync::requestCkpt(), DistIface::Sync::requestExit(), DistIface::Sync::requestStopSync(), DistIface::Sync::run(), DistIface::Sync::serialize(), and DistIface::Sync::unserialize().
Member Function Documentation
progress()
bool DistIface::SyncNode::progress (Tick send_tick, Tick next_repeat, ReqType do_ckpt, ReqType do_exit, ReqType do_stop_sync) override virtual
Callback when the receiver thread gets a sync ack message.
Returns
false if the receiver thread needs to stop (e.g. simulation is to exit)
Implements DistIface::Sync.
Definition at line 242 of file dist_iface.cc.
References X86ISA::lock, and Stats::none.
requestCkpt()
void DistIface::SyncNode::requestCkpt (ReqType req) override virtual
Implements DistIface::Sync.
Definition at line 270 of file dist_iface.cc.
References X86ISA::lock, Stats::none, and warn.
requestExit()
void DistIface::SyncNode::requestExit (ReqType req) override virtual
Implements DistIface::Sync.
Definition at line 281 of file dist_iface.cc.
References X86ISA::lock, Stats::none, and warn.
requestStopSync()
void DistIface::SyncNode::requestStopSync (ReqType req) override virtual
Implements DistIface::Sync.
Definition at line 848 of file dist_iface.cc.
References X86ISA::lock.
run()
bool DistIface::SyncNode::run (bool same_tick) override virtual
Core method to perform a full dist sync.
Returns
true if the sync completes, false if it gets aborted
Implements DistIface::Sync.
Definition at line 126 of file dist_iface.cc.
References curTick(), header, X86ISA::lock, DistHeaderPkt::Header::msgType, DistHeaderPkt::Header::needCkpt, DistHeaderPkt::Header::needExit, DistHeaderPkt::Header::needStopSync, Stats::none, DistIface::recvThreadsNum, DistIface::sendCmd(), DistHeaderPkt::Header::sendTick, and DistHeaderPkt::Header::syncRepeat.
serialize()
void DistIface::SyncNode::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements DistIface::Sync.
Definition at line 306 of file dist_iface.cc.
References SERIALIZE_SCALAR.
unserialize()
void DistIface::SyncNode::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements DistIface::Sync.
Definition at line 313 of file dist_iface.cc.
References UNSERIALIZE_SCALAR.
Member Data Documentation
needCkpt
ReqType DistIface::SyncNode::needCkpt private
Ckpt requested.
Definition at line 215 of file dist_iface.hh.
needExit
ReqType DistIface::SyncNode::needExit private
Exit requested.
Definition at line 211 of file dist_iface.hh.
needStopSync
ReqType DistIface::SyncNode::needStopSync private
Sync stop requested.
Definition at line 219 of file dist_iface.hh.
The documentation for this class was generated from the following files:
dev/net/dist_iface.hh
dev/net/dist_iface.cc