gem5: RealViewCtrl::Device Class Reference
RealViewCtrl::Device Class Reference abstract
#include <rv_ctrl.hh>
Public Member Functions
Device (RealViewCtrl &parent, DeviceFunc func, uint8_t site, uint8_t pos, uint8_t dcc, uint16_t dev)
virtual ~Device ()
virtual uint32_t read () const =0
virtual void write (uint32_t value)=0
Detailed Description
Definition at line 71 of file rv_ctrl.hh.
Constructor & Destructor Documentation
Device()
RealViewCtrl::Device::Device (RealViewCtrl & parent, DeviceFunc func, uint8_t site, uint8_t pos, uint8_t dcc, uint16_t dev) inline
Definition at line 74 of file rv_ctrl.hh.
References RealViewCtrl::registerDevice().
~Device()
virtual RealViewCtrl::Device::~Device () inline virtual
Definition at line 80 of file rv_ctrl.hh.
References read(), and write().
Member Function Documentation
read()
virtual uint32_t RealViewCtrl::Device::read () const pure virtual
Implemented in RealViewTemperatureSensor, and RealViewOsc.
Referenced by RealViewCtrl::params(), RealViewCtrl::write(), ~Device(), RealViewOsc::~RealViewOsc(), and RealViewTemperatureSensor::~RealViewTemperatureSensor().
write()
virtual void RealViewCtrl::Device::write (uint32_t value) pure virtual
Implemented in RealViewTemperatureSensor, and RealViewOsc.
Referenced by RealViewCtrl::params(), RealViewCtrl::write(), ~Device(), and RealViewOsc::~RealViewOsc().
The documentation for this class was generated from the following file:
dev/arm/rv_ctrl.hh