gem5: TLBCoalescer Class Reference
TLBCoalescer Class Reference
The TLBCoalescer is a ClockedObject sitting on the front side (CPUSide) of each TLB.
#include <tlb_coalescer.hh>
Classes
class CpuSidePort
class MemSidePort
Public Types
typedef TLBCoalescerParams Params
typedef std::vector< PacketPtr > coalescedReq
typedef std::unordered_map< int64_t, std::vector< coalescedReq > > CoalescingFIFO
typedef std::unordered_map< Addr, coalescedReq > CoalescingTable
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TLBCoalescer (const Params *p)
~TLBCoalescer ()
bool canCoalesce (PacketPtr pkt1, PacketPtr pkt2)
void updatePhysAddresses (PacketPtr pkt)
void regStats () override
Callback to set stat parameters.
Tick frequency () const
Tick ticks (int numCycles) const
Tick curCycle () const
Tick tickToCycles (Tick val) const
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void processProbeTLBEvent ()
void processCleanupEvent ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
int TLBProbesPerCycle
int coalescingWindow
bool disableCoalescing
CoalescingFIFO coalescerFIFO
CoalescingTable issuedTranslationsTable
Stats::Scalar uncoalescedAccesses
Stats::Scalar coalescedAccesses
Stats::Scalar queuingCycles
Stats::Scalar localqueuingCycles
Stats::Formula localLatency
std::vector< CpuSidePort * > cpuSidePort
std::vector< MemSidePort * > memSidePort
EventFunctionWrapper probeTLBEvent
This event issues the TLB probes.
EventFunctionWrapper cleanupEvent
The cleanupEvent is scheduled after a TLBEvent triggers in order to free memory and do the required clean-up.
std::queue< Addr > cleanupQueue
Protected Attributes
int clock
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
The TLBCoalescer is a ClockedObject sitting on the front side (CPUSide) of each TLB.
It receives packets and issues coalesced requests to the TLB below it. It controls how requests are coalesced (the rules) and the permitted number of TLB probes per cycle (i.e., how many coalesced requests it feeds the TLB per cycle).
Definition at line 68 of file tlb_coalescer.hh.
Member Typedef Documentation
coalescedReq
typedef std::vector<PacketPtr> TLBCoalescer::coalescedReq
Definition at line 91 of file tlb_coalescer.hh.
CoalescingFIFO
typedef std::unordered_map<int64_t, std::vector<coalescedReq> > TLBCoalescer::CoalescingFIFO
Definition at line 110 of file tlb_coalescer.hh.
CoalescingTable
typedef std::unordered_map<Addr, coalescedReq> TLBCoalescer::CoalescingTable
Definition at line 123 of file tlb_coalescer.hh.
Params
typedef TLBCoalescerParams TLBCoalescer::Params
Definition at line 78 of file tlb_coalescer.hh.
Constructor & Destructor Documentation
TLBCoalescer()
TLBCoalescer::TLBCoalescer (const Params * p)
Definition at line 44 of file tlb_coalescer.cc.
References cleanupEvent, EventBase::CPU_Tick_Pri, cpuSidePort, csprintf(), ArmISA::i, EventBase::Maximum_Pri, memSidePort, SimObject::name(), MipsISA::p, processCleanupEvent(), and processProbeTLBEvent().
Referenced by regStats().
~TLBCoalescer()
TLBCoalescer::~TLBCoalescer () inline
Definition at line 80 of file tlb_coalescer.hh.
Member Function Documentation
canCoalesce()
bool TLBCoalescer::canCoalesce (PacketPtr pkt1, PacketPtr pkt2)
Definition at line 97 of file tlb_coalescer.cc.
References disableCoalescing, AlphaISA::PageBytes, Packet::req, roundDown(), safe_cast(), and Packet::senderState.
curCycle()
Tick TLBCoalescer::curCycle () const inline
Definition at line 152 of file tlb_coalescer.hh.
References clock, and curTick().
frequency()
Tick TLBCoalescer::frequency () const inline
Definition at line 150 of file tlb_coalescer.hh.
References clock, and SimClock::Frequency.
getPort()
Port & TLBCoalescer::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 71 of file tlb_coalescer.cc.
References cpuSidePort, memSidePort, and panic.
processCleanupEvent()
void TLBCoalescer::processCleanupEvent ()
Definition at line 513 of file tlb_coalescer.cc.
References cleanupQueue, DPRINTF, and issuedTranslationsTable.
Referenced by TLBCoalescer().
processProbeTLBEvent()
void TLBCoalescer::processProbeTLBEvent ()
Definition at line 407 of file tlb_coalescer.cc.
References coalescerFIFO, curTick(), DPRINTF, ArmISA::i, issuedTranslationsTable, localqueuingCycles, memSidePort, SimObject::name(), AlphaISA::PageBytes, queuingCycles, Packet::req, roundDown(), safe_cast(), Packet::senderState, and TLBProbesPerCycle.
Referenced by TLBCoalescer().
regStats()
void TLBCoalescer::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 526 of file tlb_coalescer.cc.
References coalescedAccesses, Stats::DataWrap< Derived, InfoProxyType >::desc(), localLatency, localqueuingCycles, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), queuingCycles, Stats::Group::regStats(), TLBCoalescer(), and uncoalescedAccesses.
ticks()
Tick TLBCoalescer::ticks (int numCycles) const inline
Definition at line 151 of file tlb_coalescer.hh.
tickToCycles()
Tick TLBCoalescer::tickToCycles (Tick val) const inline
Definition at line 153 of file tlb_coalescer.hh.
References clock.
updatePhysAddresses()
void TLBCoalescer::updatePhysAddresses (PacketPtr pkt)
Definition at line 142 of file tlb_coalescer.cc.
References cleanupEvent, cleanupQueue, curTick(), DPRINTF, ArmISA::i, Packet::isRequest(), issuedTranslationsTable, Packet::makeTimingResponse(), MipsISA::p, AlphaISA::PageBytes, Packet::req, roundDown(), safe_cast(), EventManager::schedule(), Event::scheduled(), Packet::senderState, SlavePort::sendTimingResp(), and Request::UNCACHEABLE.
Member Data Documentation
cleanupEvent
EventFunctionWrapper TLBCoalescer::cleanupEvent
The cleanupEvent is scheduled after a TLBEvent triggers in order to free memory and do the required clean-up.
Definition at line 224 of file tlb_coalescer.hh.
Referenced by TLBCoalescer(), and updatePhysAddresses().
cleanupQueue
std::queue<Addr> TLBCoalescer::cleanupQueue
Definition at line 228 of file tlb_coalescer.hh.
Referenced by processCleanupEvent(), and updatePhysAddresses().
clock
int TLBCoalescer::clock protected
Definition at line 75 of file tlb_coalescer.hh.
Referenced by curCycle(), frequency(), and tickToCycles().
coalescedAccesses
Stats::Scalar TLBCoalescer::coalescedAccesses
Definition at line 130 of file tlb_coalescer.hh.
Referenced by regStats().
coalescerFIFO
CoalescingFIFO TLBCoalescer::coalescerFIFO
Definition at line 112 of file tlb_coalescer.hh.
Referenced by processProbeTLBEvent().
coalescingWindow
int TLBCoalescer::coalescingWindow
Definition at line 87 of file tlb_coalescer.hh.
cpuSidePort
std::vector<CpuSidePort*> TLBCoalescer::cpuSidePort
Definition at line 210 of file tlb_coalescer.hh.
Referenced by getPort(), and TLBCoalescer().
disableCoalescing
bool TLBCoalescer::disableCoalescing
Definition at line 94 of file tlb_coalescer.hh.
Referenced by canCoalesce().
issuedTranslationsTable
CoalescingTable TLBCoalescer::issuedTranslationsTable
Definition at line 125 of file tlb_coalescer.hh.
Referenced by processCleanupEvent(), processProbeTLBEvent(), and updatePhysAddresses().
localLatency
Stats::Formula TLBCoalescer::localLatency
Definition at line 142 of file tlb_coalescer.hh.
Referenced by regStats().
localqueuingCycles
Stats::Scalar TLBCoalescer::localqueuingCycles
Definition at line 140 of file tlb_coalescer.hh.
Referenced by processProbeTLBEvent(), and regStats().
memSidePort
std::vector<MemSidePort*> TLBCoalescer::memSidePort
Definition at line 212 of file tlb_coalescer.hh.
Referenced by getPort(), processProbeTLBEvent(), and TLBCoalescer().
probeTLBEvent
EventFunctionWrapper TLBCoalescer::probeTLBEvent
This event issues the TLB probes.
Definition at line 219 of file tlb_coalescer.hh.
queuingCycles
Stats::Scalar TLBCoalescer::queuingCycles
Definition at line 135 of file tlb_coalescer.hh.
Referenced by processProbeTLBEvent(), and regStats().
TLBProbesPerCycle
int TLBCoalescer::TLBProbesPerCycle
Definition at line 83 of file tlb_coalescer.hh.
Referenced by processProbeTLBEvent().
uncoalescedAccesses
Stats::Scalar TLBCoalescer::uncoalescedAccesses
Definition at line 128 of file tlb_coalescer.hh.
Referenced by regStats().
The documentation for this class was generated from the following files:
gpu-compute/tlb_coalescer.hh
gpu-compute/tlb_coalescer.cc