gem5: HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType > Class Template Reference
HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType > Class Template Reference
#include <mem.hh>
Public Member Functions
LdInstBase (const Brig::BrigInstBase *ib, const BrigObject *obj, const char *_opcode)
int numSrcRegOperands () override
int numDstRegOperands () override
int getNumOperands () override
bool isVectorRegister (int operandIndex) override
bool isCondRegister (int operandIndex) override
bool isScalarRegister (int operandIndex) override
bool isSrcOperand (int operandIndex) override
bool isDstOperand (int operandIndex) override
int getOperandSize (int operandIndex) override
int getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) override
Public Member Functions inherited from HsailISA::HsailGPUStaticInst
HsailGPUStaticInst (const BrigObject *obj, const std::string &opcode)
void generateDisassembly () override
int instSize () const override
bool isValid () const override
Public Member Functions inherited from GPUStaticInst
GPUStaticInst (const std::string &opcode)
void instAddr (int inst_addr)
int instAddr () const
int nextInstAddr () const
void instNum (int num)
int instNum ()
void ipdInstNum (int num)
int ipdInstNum () const
virtual void execute (GPUDynInstPtr gpuDynInst)=0
const std::string & disassemble ()
bool isALU () const
bool isBranch () const
bool isNop () const
bool isReturn () const
bool isUnconditionalJump () const
bool isSpecialOp () const
bool isWaitcnt () const
bool isBarrier () const
bool isMemFence () const
bool isMemRef () const
bool isFlat () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isAtomicNoRet () const
bool isAtomicRet () const
bool isScalar () const
bool readsSCC () const
bool writesSCC () const
bool readsVCC () const
bool writesVCC () const
bool isAtomicAnd () const
bool isAtomicOr () const
bool isAtomicXor () const
bool isAtomicCAS () const
bool isAtomicExch () const
bool isAtomicAdd () const
bool isAtomicSub () const
bool isAtomicInc () const
bool isAtomicDec () const
bool isAtomicMax () const
bool isAtomicMin () const
bool isArgLoad () const
bool isGlobalMem () const
bool isLocalMem () const
bool isArgSeg () const
bool isGlobalSeg () const
bool isGroupSeg () const
bool isKernArgSeg () const
bool isPrivateSeg () const
bool isReadOnlySeg () const
bool isSpillSeg () const
bool isWorkitemScope () const
bool isWavefrontScope () const
bool isWorkgroupScope () const
bool isDeviceScope () const
bool isSystemScope () const
bool isNoScope () const
bool isRelaxedOrder () const
bool isAcquire () const
bool isRelease () const
bool isAcquireRelease () const
bool isNoOrder () const
bool isGloballyCoherent () const
Coherence domain of a memory instruction.
bool isSystemCoherent () const
virtual void initiateAcc (GPUDynInstPtr gpuDynInst)
virtual void completeAcc (GPUDynInstPtr gpuDynInst)
virtual uint32_t getTargetPc ()
void setFlag (Flags flag)
virtual void execLdAcq (GPUDynInstPtr gpuDynInst)
virtual void execSt (GPUDynInstPtr gpuDynInst)
virtual void execAtomic (GPUDynInstPtr gpuDynInst)
virtual void execAtomicAcq (GPUDynInstPtr gpuDynInst)
Public Attributes
Brig::BrigWidth8_t width
DestOperandType::DestOperand dest
AddrOperandType addr
Brig::BrigSegment segment
Brig::BrigMemoryOrder memoryOrder
Brig::BrigMemoryScope memoryScope
unsigned int equivClass
Public Attributes inherited from GPUStaticInst
Enums::StorageClassType executed_as
Additional Inherited Members
Static Public Attributes inherited from GPUStaticInst
static uint64_t dynamic_id_count
Protected Attributes inherited from HsailISA::HsailGPUStaticInst
HsailCode * hsailCode
Protected Attributes inherited from GPUStaticInst
const std::string opcode
std::string disassembly
int _instNum
int _instAddr
int _ipdInstNum
Identifier of the immediate post-dominator instruction.
std::bitset< Num_Flags > _flags
Detailed Description
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType>
class HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >
Definition at line 209 of file mem.hh.
Constructor & Destructor Documentation
LdInstBase()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::LdInstBase (const Brig::BrigInstBase * ib, const BrigObject * obj, const char * _opcode) inline
Definition at line 221 of file mem.hh.
Member Function Documentation
getNumOperands()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::getNumOperands () inline override virtual
Implements GPUStaticInst.
Definition at line 338 of file mem.hh.
getOperandSize()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::getOperandSize (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 375 of file mem.hh.
getRegisterIndex()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::getRegisterIndex (int operandIndex, GPUDynInstPtr gpuDynInst) inline override virtual
Implements GPUStaticInst.
Definition at line 382 of file mem.hh.
isCondRegister()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> bool HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::isCondRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 351 of file mem.hh.
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::isCondRegister().
isDstOperand()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> bool HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::isDstOperand (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 370 of file mem.hh.
isScalarRegister()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> bool HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::isScalarRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 357 of file mem.hh.
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::isScalarRegister().
isSrcOperand()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> bool HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::isSrcOperand (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 363 of file mem.hh.
isVectorRegister()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> bool HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::isVectorRegister (int operandIndex) inline override virtual
Implements GPUStaticInst.
Definition at line 345 of file mem.hh.
Referenced by HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::isVectorRegister().
numDstRegOperands()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::numDstRegOperands () inline override virtual
Implements GPUStaticInst.
Definition at line 337 of file mem.hh.
numSrcRegOperands()
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::numSrcRegOperands () inline override virtual
Implements GPUStaticInst.
Definition at line 335 of file mem.hh.
Member Data Documentation
addr
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> AddrOperandType HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::addr
Definition at line 214 of file mem.hh.
dest
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> DestOperandType::DestOperand HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::dest
Definition at line 213 of file mem.hh.
equivClass
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> unsigned int HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::equivClass
Definition at line 219 of file mem.hh.
memoryOrder
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> Brig::BrigMemoryOrder HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::memoryOrder
Definition at line 217 of file mem.hh.
memoryScope
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> Brig::BrigMemoryScope HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::memoryScope
Definition at line 218 of file mem.hh.
segment
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> Brig::BrigSegment HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::segment
Definition at line 216 of file mem.hh.
width
template<typename MemOperandType, typename DestOperandType, typename AddrOperandType> Brig::BrigWidth8_t HsailISA::LdInstBase< MemOperandType, DestOperandType, AddrOperandType >::width
Definition at line 212 of file mem.hh.
The documentation for this class was generated from the following file:
arch/hsail/insts/mem.hh