gem5: Minor::MinorStats Class Reference
Minor::MinorStats Class Reference
Currently unused stats class.
#include <stats.hh>
Public Member Functions
MinorStats ()
void regStats (const std::string &name, BaseCPU &baseCpu)
Public Attributes
Stats::Scalar numInsts
Number of simulated instructions.
Stats::Scalar numOps
Number of simulated insts and microops.
Stats::Scalar numDiscardedOps
Number of ops discarded before committing.
Stats::Scalar numFetchSuspends
Number of times fetch was asked to suspend by Execute.
Stats::Scalar quiesceCycles
Number of cycles in quiescent state.
Stats::Formula cpi
CPI/IPC for total cycle counts and macro insts.
Stats::Formula ipc
Stats::Vector2d committedInstType
Number of instructions by type (OpClass)
Detailed Description
Currently unused stats class.
Definition at line 57 of file stats.hh.
Constructor & Destructor Documentation
MinorStats()
Minor::MinorStats::MinorStats ()
Definition at line 45 of file stats.cc.
Member Function Documentation
regStats()
void Minor::MinorStats::regStats (const std::string & name, BaseCPU & baseCpu)
Definition at line 49 of file stats.cc.
References committedInstType, cpi, Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::dist, Stats::DataWrap< Derived, InfoProxyType >::flags(), Stats::Vector2dBase< Derived, Stor >::init(), ipc, Stats::DataWrap< Derived, InfoProxyType >::name(), BaseCPU::numCycles, numDiscardedOps, numFetchSuspends, numInsts, numOps, BaseCPU::numThreads, Stats::pdf, Stats::DataWrap< Derived, InfoProxyType >::precision(), Stats::DataWrap< Derived, InfoProxyType >::prereq(), quiesceCycles, Stats::total, and Stats::DataWrapVec2d< Derived, InfoProxyType >::ysubnames().
Referenced by MinorCPU::regStats().
Member Data Documentation
committedInstType
Stats::Vector2d Minor::MinorStats::committedInstType
Number of instructions by type (OpClass)
Definition at line 80 of file stats.hh.
Referenced by Minor::Execute::doInstCommitAccounting(), and regStats().
cpi
Stats::Formula Minor::MinorStats::cpi
CPI/IPC for total cycle counts and macro insts.
Definition at line 76 of file stats.hh.
Referenced by regStats().
ipc
Stats::Formula Minor::MinorStats::ipc
Definition at line 77 of file stats.hh.
Referenced by regStats().
numDiscardedOps
Stats::Scalar Minor::MinorStats::numDiscardedOps
Number of ops discarded before committing.
Definition at line 67 of file stats.hh.
Referenced by Minor::Execute::commit(), and regStats().
numFetchSuspends
Stats::Scalar Minor::MinorStats::numFetchSuspends
Number of times fetch was asked to suspend by Execute.
Definition at line 70 of file stats.hh.
Referenced by Minor::Execute::commitInst(), and regStats().
numInsts
Stats::Scalar Minor::MinorStats::numInsts
Number of simulated instructions.
Definition at line 61 of file stats.hh.
Referenced by Minor::Execute::doInstCommitAccounting(), and regStats().
numOps
Stats::Scalar Minor::MinorStats::numOps
Number of simulated insts and microops.
Definition at line 64 of file stats.hh.
Referenced by Minor::Execute::doInstCommitAccounting(), and regStats().
quiesceCycles
Stats::Scalar Minor::MinorStats::quiesceCycles
Number of cycles in quiescent state.
Definition at line 73 of file stats.hh.
Referenced by MinorCPU::activateContext(), and regStats().
The documentation for this class was generated from the following files:
cpu/minor/stats.hh
cpu/minor/stats.cc