gem5: sc_core::sc_in< bool > Class Template Reference
sc_core::sc_in< bool > Class Template Reference
#include <sc_in.hh>
Public Member Functions
sc_in ()
sc_in (const char *name)
virtual ~sc_in ()
sc_in (const sc_signal_in_if< bool > &interface)
sc_in (const char *name, const sc_signal_in_if< bool > &interface)
sc_in (sc_port_b< sc_signal_in_if< bool > > &parent)
sc_in (const char *name, sc_port_b< sc_signal_in_if< bool > > &parent)
sc_in (sc_port< sc_signal_in_if< bool >, 1 > &parent)
sc_in (const char *name, sc_port< sc_signal_in_if< bool >, 1 > &parent)
virtual void bind (const sc_signal_in_if< bool > &i)
void operator() (const sc_signal_in_if< bool > &i)
virtual void bind (sc_port< sc_signal_in_if< bool >, 1 > &p)
void operator() (sc_port< sc_signal_in_if< bool >, 1 > &p)
virtual void bind (sc_port< sc_signal_inout_if< bool >, 1 > &p)
void operator() (sc_port< sc_signal_inout_if< bool >, 1 > &p)
virtual void end_of_elaboration ()
const bool & read () const
operator const bool & () const
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_event & posedge_event () const
const sc_event & negedge_event () const
bool event () const
bool posedge () const
bool negedge () const
sc_event_finder & value_changed () const
sc_event_finder & pos () const
sc_event_finder & neg () const
virtual const char * kind () const
void add_trace (sc_trace_file *tf, const std::string &name) const
Public Member Functions inherited from sc_core::sc_port< sc_signal_in_if< bool >, 1 >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_in_if< bool > &interface)
sc_port (const char *name, const sc_signal_in_if< bool > &interface)
sc_port (sc_port_b< sc_signal_in_if< bool > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_in_if< bool > > &parent)
sc_port (sc_port< sc_signal_in_if< bool >, N, SC_ONE_OR_MORE_BOUND > &parent)
sc_port (const char *name, sc_port< sc_signal_in_if< bool >, N, SC_ONE_OR_MORE_BOUND > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< bool > >
void operator() (sc_signal_in_if< bool > &i)
void operator() (sc_port_b< sc_signal_in_if< bool > > &p)
virtual void bind (sc_signal_in_if< bool > &i)
virtual void bind (sc_port_b< sc_signal_in_if< bool > > &p)
sc_signal_in_if< bool > * operator-> ()
const sc_signal_in_if< bool > * operator-> () const
sc_signal_in_if< bool > * operator[] (int n)
const sc_signal_in_if< bool > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Private Member Functions
sc_in (const sc_in< bool > &)
sc_in< bool > & operator= (const sc_in< bool > &)
Private Attributes
sc_event_finder_t< sc_signal_in_if< bool > > _valueChangedFinder
sc_event_finder_t< sc_signal_in_if< bool > > _posFinder
sc_event_finder_t< sc_signal_in_if< bool > > _negFinder
sc_trace_params_vec traceParamsVec
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_in_if< bool > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Detailed Description
template<>
class sc_core::sc_in< bool >
Definition at line 167 of file sc_in.hh.
Constructor & Destructor Documentation
sc_in() [1/9]
sc_core::sc_in< bool >::sc_in () inline
Definition at line 170 of file sc_in.hh.
sc_in() [2/9]
sc_core::sc_in< bool >::sc_in (const char * name) inline explicit
Definition at line 176 of file sc_in.hh.
~sc_in()
virtual sc_core::sc_in< bool >::~sc_in () inline virtual
Definition at line 183 of file sc_in.hh.
sc_in() [3/9]
sc_core::sc_in< bool >::sc_in (const sc_signal_in_if< bool > & interface) inline explicit
Definition at line 186 of file sc_in.hh.
sc_in() [4/9]
sc_core::sc_in< bool >::sc_in (const char * name, const sc_signal_in_if< bool > & interface) inline
Definition at line 193 of file sc_in.hh.
sc_in() [5/9]
sc_core::sc_in< bool >::sc_in (sc_port_b< sc_signal_in_if< bool > > & parent) inline explicit
Definition at line 200 of file sc_in.hh.
sc_in() [6/9]
sc_core::sc_in< bool >::sc_in (const char * name, sc_port_b< sc_signal_in_if< bool > > & parent) inline
Definition at line 207 of file sc_in.hh.
sc_in() [7/9]
sc_core::sc_in< bool >::sc_in (sc_port< sc_signal_in_if< bool >, 1 > & parent) inline explicit
Definition at line 214 of file sc_in.hh.
sc_in() [8/9]
sc_core::sc_in< bool >::sc_in (const char * name, sc_port< sc_signal_in_if< bool >, 1 > & parent) inline
Definition at line 221 of file sc_in.hh.
References sc_core::sc_in< T >::bind().
sc_in() [9/9]
sc_core::sc_in< bool >::sc_in (const sc_in< bool > &) private
Member Function Documentation
add_trace()
void sc_core::sc_in< bool >::add_trace (sc_trace_file * tf, const std::string & name) const inline
Definition at line 301 of file sc_in.hh.
References sc_core::sc_in< T >::traceParamsVec.
bind() [1/3]
virtual void sc_core::sc_in< bool >::bind (const sc_signal_in_if< bool > & i) inline virtual
Definition at line 232 of file sc_in.hh.
References sc_core::sc_in< T >::bind().
bind() [2/3]
virtual void sc_core::sc_in< bool >::bind (sc_port< sc_signal_in_if< bool >, 1 > & p) inline virtual
Definition at line 240 of file sc_in.hh.
References sc_core::sc_in< T >::bind(), and MipsISA::p.
bind() [3/3]
virtual void sc_core::sc_in< bool >::bind (sc_port< sc_signal_inout_if< bool >, 1 > & p) inline virtual
Definition at line 251 of file sc_in.hh.
References sc_core::sc_port_base::bind(), and MipsISA::p.
default_event()
const sc_event& sc_core::sc_in< bool >::default_event () const inline
Definition at line 273 of file sc_in.hh.
end_of_elaboration()
virtual void sc_core::sc_in< bool >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Definition at line 262 of file sc_in.hh.
References sc_core::sc_trace(), and sc_core::sc_in< T >::traceParamsVec.
event()
bool sc_core::sc_in< bool >::event () const inline
Definition at line 290 of file sc_in.hh.
kind()
virtual const char* sc_core::sc_in< bool >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_in_if< bool >, 1 >.
Definition at line 298 of file sc_in.hh.
neg()
sc_event_finder& sc_core::sc_in< bool >::neg () const inline
Definition at line 296 of file sc_in.hh.
negedge()
bool sc_core::sc_in< bool >::negedge () const inline
Definition at line 292 of file sc_in.hh.
negedge_event()
const sc_event& sc_core::sc_in< bool >::negedge_event () const inline
Definition at line 285 of file sc_in.hh.
operator const bool &()
sc_core::sc_in< bool >::operator const bool & () const inline
Definition at line 271 of file sc_in.hh.
operator()() [1/3]
void sc_core::sc_in< bool >::operator() (const sc_signal_in_if< bool > & i) inline
Definition at line 237 of file sc_in.hh.
References sc_core::sc_in< T >::bind().
operator()() [2/3]
void sc_core::sc_in< bool >::operator() (sc_port< sc_signal_in_if< bool >, 1 > & p) inline
Definition at line 245 of file sc_in.hh.
References sc_core::sc_in< T >::bind(), and MipsISA::p.
operator()() [3/3]
void sc_core::sc_in< bool >::operator() (sc_port< sc_signal_inout_if< bool >, 1 > & p) inline
Definition at line 256 of file sc_in.hh.
References sc_core::sc_in< T >::bind(), and MipsISA::p.
operator=()
sc_in<bool>& sc_core::sc_in< bool >::operator= (const sc_in< bool > &) private
pos()
sc_event_finder& sc_core::sc_in< bool >::pos () const inline
Definition at line 295 of file sc_in.hh.
Referenced by sc_core::sc_sensitive::operator()().
posedge()
bool sc_core::sc_in< bool >::posedge () const inline
Definition at line 291 of file sc_in.hh.
posedge_event()
const sc_event& sc_core::sc_in< bool >::posedge_event () const inline
Definition at line 280 of file sc_in.hh.
read()
const bool& sc_core::sc_in< bool >::read () const inline
Definition at line 270 of file sc_in.hh.
value_changed()
sc_event_finder& sc_core::sc_in< bool >::value_changed () const inline
Definition at line 294 of file sc_in.hh.
References sc_core::sc_in< T >::_valueChangedFinder.
value_changed_event()
const sc_event& sc_core::sc_in< bool >::value_changed_event () const inline
Definition at line 275 of file sc_in.hh.
Member Data Documentation
_negFinder
sc_event_finder_t<sc_signal_in_if<bool> > sc_core::sc_in< bool >::_negFinder mutable private
Definition at line 309 of file sc_in.hh.
_posFinder
sc_event_finder_t<sc_signal_in_if<bool> > sc_core::sc_in< bool >::_posFinder mutable private
Definition at line 308 of file sc_in.hh.
_valueChangedFinder
sc_event_finder_t<sc_signal_in_if<bool> > sc_core::sc_in< bool >::_valueChangedFinder mutable private
Definition at line 307 of file sc_in.hh.
traceParamsVec
sc_trace_params_vec sc_core::sc_in< bool >::traceParamsVec mutable private
Definition at line 311 of file sc_in.hh.
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_in.hh