gem5: LabelMap Class Reference
LabelMap Class Reference
#include <hsail_code.hh>
Public Member Functions
LabelMap ()
void addLabel (const Brig::BrigDirectiveLabel *lbl, int inst_index, const BrigObject *obj)
Label * refLabel (const Brig::BrigDirectiveLabel *lbl, const BrigObject *obj)
Private Attributes
std::map< std::string, Label > map
Detailed Description
Definition at line 205 of file hsail_code.hh.
Constructor & Destructor Documentation
LabelMap()
LabelMap::LabelMap () inline
Definition at line 210 of file hsail_code.hh.
Member Function Documentation
addLabel()
void LabelMap::addLabel (const Brig::BrigDirectiveLabel * lbl, int inst_index, const BrigObject * obj)
Definition at line 227 of file hsail_code.cc.
References Label::define(), Label::defined(), DPRINTF, fatal, BrigObject::getString(), and Brig::BrigDirectiveLabel::name.
Referenced by HsailCode::init().
refLabel()
Label * LabelMap::refLabel (const Brig::BrigDirectiveLabel * lbl, const BrigObject * obj)
Definition at line 242 of file hsail_code.cc.
References Label::checkName(), BrigObject::getString(), HsaCode::name(), and Brig::BrigDirectiveLabel::name.
Referenced by HsailCode::refLabel().
Member Data Documentation
map
std::map<std::string, Label> LabelMap::map private
Definition at line 207 of file hsail_code.hh.
The documentation for this class was generated from the following files:
gpu-compute/hsail_code.hh
gpu-compute/hsail_code.cc