gem5: EmbeddedPyBind Class Reference
EmbeddedPyBind Class Reference
#include <init.hh>
Public Member Functions
EmbeddedPyBind (const char *_name, void(*init_func)(pybind11::module &), const char *_base)
EmbeddedPyBind (const char *_name, void(*init_func)(pybind11::module &))
Static Public Member Functions
static void initAll ()
Private Member Functions
bool depsReady () const
void init (pybind11::module &m)
Static Private Member Functions
static std::map< std::string, EmbeddedPyBind * > & getMap ()
Private Attributes
void(* initFunc)(pybind11::module &)
bool registered
const std::string name
const std::string base
Detailed Description
Definition at line 83 of file init.hh.
Constructor & Destructor Documentation
EmbeddedPyBind() [1/2]
EmbeddedPyBind::EmbeddedPyBind (const char * _name, void(*)(pybind11::module &) init_func, const char * _base)
Referenced by EmbeddedPython::initAll().
EmbeddedPyBind() [2/2]
EmbeddedPyBind::EmbeddedPyBind (const char * _name, void(*)(pybind11::module &) init_func)
Member Function Documentation
depsReady()
bool EmbeddedPyBind::depsReady () const private
Definition at line 182 of file init.cc.
References X86ISA::base.
Referenced by initAll().
getMap()
std::map< std::string, EmbeddedPyBind * > & EmbeddedPyBind::getMap () static private
Definition at line 188 of file init.cc.
init()
void EmbeddedPyBind::init (pybind11::module & m) private
Definition at line 171 of file init.cc.
References cprintf(), and name().
Referenced by initAll().
initAll()
void EmbeddedPyBind::initAll () static
Definition at line 199 of file init.cc.
References depsReady(), init(), pybind_init_core(), pybind_init_debug(), pybind_init_event(), and pybind_init_stats().
Referenced by registerNativeModules().
Member Data Documentation
base
const std::string EmbeddedPyBind::base private
Definition at line 107 of file init.hh.
initFunc
void(* EmbeddedPyBind::initFunc) (pybind11::module &) private
Definition at line 100 of file init.hh.
name
const std::string EmbeddedPyBind::name private
Definition at line 106 of file init.hh.
registered
bool EmbeddedPyBind::registered private
Definition at line 105 of file init.hh.
The documentation for this class was generated from the following files:
sim/init.hh
sim/init.cc