gem5: sc_dt::sc_int_subref Class Reference
sc_dt::sc_int_subref Class Reference
#include <sc_int_base.hh>
Public Member Functions
sc_int_subref (const sc_int_subref &a)
sc_int_subref & operator= (int_type v)
sc_int_subref & operator= (const sc_int_base &a)
sc_int_subref & operator= (const sc_int_subref_r &a)
sc_int_subref & operator= (const sc_int_subref &a)
template<class T >
sc_int_subref & operator= (const sc_generic_base< T > &a)
sc_int_subref & operator= (const char *a)
sc_int_subref & operator= (unsigned long a)
sc_int_subref & operator= (long a)
sc_int_subref & operator= (unsigned int a)
sc_int_subref & operator= (int a)
sc_int_subref & operator= (uint64 a)
sc_int_subref & operator= (double a)
sc_int_subref & operator= (const sc_signed &)
sc_int_subref & operator= (const sc_unsigned &)
sc_int_subref & operator= (const sc_bv_base &)
sc_int_subref & operator= (const sc_lv_base &)
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_int_subref_r
sc_int_subref_r (const sc_int_subref_r &a)
virtual ~sc_int_subref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Static Public Attributes
static sc_core::sc_vpool< sc_int_subref > m_pool
Protected Member Functions
sc_int_subref ()
Protected Member Functions inherited from sc_dt::sc_int_subref_r
sc_int_subref_r ()
void initialize (const sc_int_base *obj_p, int left_i, int right_i)
Friends
class sc_int_base
class sc_core::sc_vpool< sc_int_subref >
Additional Inherited Members
Protected Attributes inherited from sc_dt::sc_int_subref_r
int m_left
sc_int_base * m_obj_p
int m_right
Detailed Description
Definition at line 392 of file sc_int_base.hh.
Constructor & Destructor Documentation
sc_int_subref() [1/2]
sc_dt::sc_int_subref::sc_int_subref () inline protected
Definition at line 399 of file sc_int_base.hh.
sc_int_subref() [2/2]
sc_dt::sc_int_subref::sc_int_subref (const sc_int_subref & a) inline
Definition at line 403 of file sc_int_base.hh.
References ArmISA::a, and ArmISA::v.
Member Function Documentation
concat_set() [1/4]
void sc_dt::sc_int_subref::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 308 of file sc_int_base.cc.
References PowerISA::aa, and length.
concat_set() [2/4]
void sc_dt::sc_int_subref::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 315 of file sc_int_base.cc.
References PowerISA::aa, length, and sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_int_subref::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 325 of file sc_int_base.cc.
References PowerISA::aa, length, and sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_int_subref::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 335 of file sc_int_base.cc.
References PowerISA::aa, and length.
operator=() [1/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (int_type v)
Definition at line 265 of file sc_int_base.cc.
References ArmISA::mask, sc_dt::mask_int, and X86ISA::val.
operator=() [2/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const sc_int_base & a) inline
Definition at line 1222 of file sc_int_base.hh.
operator=() [3/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (const sc_int_subref_r & a) inline
Definition at line 410 of file sc_int_base.hh.
operator=() [4/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (const sc_int_subref & a) inline
Definition at line 416 of file sc_int_base.hh.
operator=() [5/16]
template<class T > sc_int_subref& sc_dt::sc_int_subref::operator= (const sc_generic_base< T > & a) inline
Definition at line 423 of file sc_int_base.hh.
operator=() [6/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const char * a) inline
Definition at line 1228 of file sc_int_base.hh.
References PowerISA::aa, and length.
operator=() [7/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (unsigned long a) inline
Definition at line 431 of file sc_int_base.hh.
operator=() [8/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (long a) inline
Definition at line 437 of file sc_int_base.hh.
operator=() [9/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (unsigned int a) inline
Definition at line 443 of file sc_int_base.hh.
operator=() [10/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (int a) inline
Definition at line 449 of file sc_int_base.hh.
operator=() [11/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (uint64 a) inline
Definition at line 455 of file sc_int_base.hh.
operator=() [12/16]
sc_int_subref& sc_dt::sc_int_subref::operator= (double a) inline
Definition at line 461 of file sc_int_base.hh.
References MipsISA::is.
operator=() [13/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const sc_signed & a)
Definition at line 277 of file sc_int_base.cc.
References PowerISA::aa, and length.
operator=() [14/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const sc_unsigned & a)
Definition at line 284 of file sc_int_base.cc.
References PowerISA::aa, and length.
operator=() [15/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const sc_bv_base & a)
Definition at line 291 of file sc_int_base.cc.
References PowerISA::aa, and length.
operator=() [16/16]
sc_int_subref & sc_dt::sc_int_subref::operator= (const sc_lv_base & a)
Definition at line 298 of file sc_int_base.cc.
References PowerISA::aa, and length.
scan()
void sc_dt::sc_int_subref::scan (::std::istream & is = ::std::cin)
Definition at line 344 of file sc_int_base.cc.
References ArmISA::s.
Referenced by sc_dt::operator>>().
Friends And Related Function Documentation
sc_core::sc_vpool< sc_int_subref >
friend class sc_core::sc_vpool< sc_int_subref > friend
Definition at line 395 of file sc_int_base.hh.
sc_int_base
friend class sc_int_base friend
Definition at line 394 of file sc_int_base.hh.
Member Data Documentation
m_pool
sc_core::sc_vpool< sc_int_subref > sc_dt::sc_int_subref::m_pool static
Definition at line 481 of file sc_int_base.hh.
Referenced by sc_dt::sc_int_base::operator()(), and sc_dt::sc_int_base::range().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_int_base.hh
systemc/dt/int/sc_int_base.cc