gem5: X86ISA::I8254 Class Reference
X86ISA::I8254 Class Reference
#include <i8254.hh>
Classes
class X86Intel8254Timer
Public Types
typedef I8254Params Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
const Params * params () const
I8254 (Params *p)
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
bool outputHigh (unsigned int num)
uint8_t readCounter (unsigned int num)
void writeCounter (unsigned int num, const uint8_t data)
void writeControl (uint8_t val)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup () override
startup() is the final initialization call before simulation.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
void counterInterrupt (unsigned int num)
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
Tick latency
X86Intel8254Timer pit
std::vector< IntSourcePin< I8254 > * > intPin
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 42 of file i8254.hh.
Member Typedef Documentation
Params
typedef I8254Params X86ISA::I8254::Params
Definition at line 71 of file i8254.hh.
Constructor & Destructor Documentation
I8254()
X86ISA::I8254::I8254 (Params * p) inline
Definition at line 88 of file i8254.hh.
References csprintf(), ArmISA::i, Intel8254Timer::name(), read(), and write().
Member Function Documentation
counterInterrupt()
void X86ISA::I8254::counterInterrupt (unsigned int num) protected
Definition at line 39 of file i8254.cc.
References DPRINTF, and intPin.
Referenced by X86ISA::I8254::X86Intel8254Timer::counterInterrupt().
getPort()
Port& X86ISA::I8254::getPort (const std::string & if_name, PortID idx = InvalidPortID) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from PioDevice.
Definition at line 74 of file i8254.hh.
References PioDevice::getPort().
outputHigh()
bool X86ISA::I8254::outputHigh (unsigned int num) inline
Definition at line 101 of file i8254.hh.
References Intel8254Timer::outputHigh().
params()
const Params* X86ISA::I8254::params () const inline
Definition at line 83 of file i8254.hh.
References SimObject::_params.
read()
Tick X86ISA::I8254::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 52 of file i8254.cc.
References Packet::getAddr(), Packet::getSize(), latency, Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, pit, Intel8254Timer::readCounter(), and Packet::setLE().
Referenced by I8254().
readCounter()
uint8_t X86ISA::I8254::readCounter (unsigned int num) inline
Definition at line 107 of file i8254.hh.
References Intel8254Timer::readCounter().
serialize()
void X86ISA::I8254::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 84 of file i8254.cc.
References pit, and Intel8254Timer::serialize().
startup()
void X86ISA::I8254::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 96 of file i8254.cc.
References pit, and Intel8254Timer::startup().
unserialize()
void X86ISA::I8254::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 90 of file i8254.cc.
References pit, and Intel8254Timer::unserialize().
write()
Tick X86ISA::I8254::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 68 of file i8254.cc.
References Packet::getAddr(), Packet::getLE(), Packet::getSize(), latency, Packet::makeAtomicResponse(), X86ISA::offset, panic, BasicPioDevice::pioAddr, pit, Intel8254Timer::writeControl(), and Intel8254Timer::writeCounter().
Referenced by I8254().
writeControl()
void X86ISA::I8254::writeControl (uint8_t val) inline
Definition at line 119 of file i8254.hh.
References Intel8254Timer::serialize(), Intel8254Timer::startup(), Intel8254Timer::unserialize(), and Intel8254Timer::writeControl().
Referenced by Pc::init().
writeCounter()
void X86ISA::I8254::writeCounter (unsigned int num, const uint8_t data) inline
Definition at line 113 of file i8254.hh.
References Intel8254Timer::writeCounter().
Member Data Documentation
intPin
std::vector<IntSourcePin<I8254> *> X86ISA::I8254::intPin protected
Definition at line 66 of file i8254.hh.
Referenced by counterInterrupt().
latency
Tick X86ISA::I8254::latency protected
Definition at line 45 of file i8254.hh.
Referenced by read(), and write().
pit
X86Intel8254Timer X86ISA::I8254::pit protected
Definition at line 64 of file i8254.hh.
Referenced by read(), serialize(), startup(), unserialize(), and write().
The documentation for this class was generated from the following files:
dev/x86/i8254.hh
dev/x86/i8254.cc