gem5: SimpleCache::CPUSidePort Class Reference
SimpleCache::CPUSidePort Class Reference
Port on the CPU-side that receives requests.
Public Member Functions
CPUSidePort (const std::string &name, int id, SimpleCache *owner)
Constructor.
void sendPacket (PacketPtr pkt)
Send a packet across this port.
AddrRangeList getAddrRanges () const override
Get a list of the non-overlapping address ranges the owner is responsible for.
void trySendRetry ()
Send a retry to the peer port only if it is needed.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
Tick recvAtomic (PacketPtr pkt) override
Receive an atomic request packet from the master port.
void recvFunctional (PacketPtr pkt) override
Receive a functional request packet from the master port.
bool recvTimingReq (PacketPtr pkt) override
Receive a timing request from the master port.
void recvRespRetry () override
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Attributes
int id
Since this is a vector port, need to know what number this one is.
SimpleCache * owner
The object that owns this object (SimpleCache)
bool needRetry
True if the port needs to send a retry req.
PacketPtr blockedPacket
If we tried to send a packet and it was blocked, store it here.
Additional Inherited Members
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Port on the CPU-side that receives requests.
Mostly just forwards requests to the cache (owner)
Definition at line 56 of file simple_cache.hh.
Constructor & Destructor Documentation
CPUSidePort()
SimpleCache::CPUSidePort::CPUSidePort (const std::string & name, int id, SimpleCache * owner) inline
Constructor.
Just calls the superclass constructor.
Definition at line 75 of file simple_cache.hh.
References getAddrRanges(), sendPacket(), and trySendRetry().
Member Function Documentation
getAddrRanges()
AddrRangeList SimpleCache::CPUSidePort::getAddrRanges () const override virtual
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns
a list of ranges responded to
Implements SlavePort.
Definition at line 87 of file simple_cache.cc.
Referenced by CPUSidePort(), and SimpleCache::MemSidePort::MemSidePort().
recvAtomic()
Tick SimpleCache::CPUSidePort::recvAtomic (PacketPtr pkt) inline override protected virtual
Receive an atomic request packet from the master port.
No need to implement in this simple cache.
Implements AtomicResponseProtocol.
Definition at line 109 of file simple_cache.hh.
References panic, recvFunctional(), recvRespRetry(), and recvTimingReq().
recvFunctional()
void SimpleCache::CPUSidePort::recvFunctional (PacketPtr pkt) override protected virtual
Receive a functional request packet from the master port.
Performs a "debug" access updating/reading the data in place.
Parameters
packet the requestor sent.
Implements FunctionalResponseProtocol.
Definition at line 104 of file simple_cache.cc.
Referenced by recvAtomic().
recvRespRetry()
void SimpleCache::CPUSidePort::recvRespRetry () override protected virtual
Called by the master port if sendTimingResp was called on this slave port (causing recvTimingResp to be called on the master port) and was unsuccesful.
Implements TimingResponseProtocol.
Definition at line 134 of file simple_cache.cc.
References DPRINTF, and Packet::print().
Referenced by recvAtomic().
recvTimingReq()
bool SimpleCache::CPUSidePort::recvTimingReq (PacketPtr pkt) override protected virtual
Receive a timing request from the master port.
Parameters
the packet that the requestor sent
Returns
whether this object can consume to packet. If false, we will call sendRetry() when we can try to receive this request again.
Implements TimingResponseProtocol.
Definition at line 111 of file simple_cache.cc.
References DPRINTF, and Packet::print().
Referenced by recvAtomic().
sendPacket()
void SimpleCache::CPUSidePort::sendPacket (PacketPtr pkt)
Send a packet across this port.
This is called by the owner and all of the flow control is hanled in this function. This is a convenience function for the SimpleCache to send pkts.
Parameters
packet to send.
Definition at line 72 of file simple_cache.cc.
References DPRINTF, panic_if, and Packet::print().
Referenced by CPUSidePort(), and SimpleCache::MemSidePort::MemSidePort().
trySendRetry()
void SimpleCache::CPUSidePort::trySendRetry ()
Send a retry to the peer port only if it is needed.
This is called from the SimpleCache whenever it is unblocked.
Definition at line 93 of file simple_cache.cc.
References DPRINTF.
Referenced by CPUSidePort().
Member Data Documentation
blockedPacket
PacketPtr SimpleCache::CPUSidePort::blockedPacket private
If we tried to send a packet and it was blocked, store it here.
Definition at line 69 of file simple_cache.hh.
id
int SimpleCache::CPUSidePort::id private
Since this is a vector port, need to know what number this one is.
Definition at line 60 of file simple_cache.hh.
needRetry
bool SimpleCache::CPUSidePort::needRetry private
True if the port needs to send a retry req.
Definition at line 66 of file simple_cache.hh.
owner
SimpleCache* SimpleCache::CPUSidePort::owner private
The object that owns this object (SimpleCache)
Definition at line 63 of file simple_cache.hh.
The documentation for this class was generated from the following files:
learning_gem5/part2/simple_cache.hh
learning_gem5/part2/simple_cache.cc