gem5: Trace::ExeTracerRecord Class Reference
Trace::ExeTracerRecord Class Reference
#include <exetrace.hh>
Public Member Functions
ExeTracerRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
void traceInst (const StaticInstPtr &inst, bool ran)
void dump ()
virtual void dumpTicks (std::ostream &outs)
Public Member Functions inherited from Trace::InstRecord
InstRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual ~InstRecord ()
void setWhen (Tick new_when)
void setMem (Addr a, Addr s, unsigned f)
template<typename T , size_t N>
void setData (std::array< T, N > d)
void setData (uint64_t d)
void setData (uint32_t d)
void setData (uint16_t d)
void setData (uint8_t d)
void setData (int64_t d)
void setData (int32_t d)
void setData (int16_t d)
void setData (int8_t d)
void setData (double d)
void setData (::VecRegContainer< TheISA::VecRegSizeBytes > &d)
void setData (::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > &d)
void setFetchSeq (InstSeqNum seq)
void setCPSeq (InstSeqNum seq)
void setPredicate (bool val)
Tick getWhen () const
ThreadContext * getThread () const
StaticInstPtr getStaticInst () const
TheISA::PCState getPCState () const
StaticInstPtr getMacroStaticInst () const
Addr getAddr () const
Addr getSize () const
unsigned getFlags () const
bool getMemValid () const
uint64_t getIntData () const
double getFloatData () const
int getDataStatus () const
InstSeqNum getFetchSeq () const
bool getFetchSeqValid () const
InstSeqNum getCpSeq () const
bool getCpSeqValid () const
Additional Inherited Members
Protected Types inherited from Trace::InstRecord
enum DataStatus {
DataInvalid = 0, DataInt8 = 1, DataInt16 = 2, DataInt32 = 4,
DataInt64 = 8, DataDouble = 3, DataVec = 5, DataVecPred = 6
}
What size of data was written?
Protected Attributes inherited from Trace::InstRecord
Tick when
ThreadContext * thread
StaticInstPtr staticInst
TheISA::PCState pc
StaticInstPtr macroStaticInst
Addr addr
The address that was accessed.
Addr size
The size of the memory request.
unsigned flags
The flags that were assigned to the request.
union {
uint64_t as_int
double as_double
::VecRegContainer< TheISA::VecRegSizeBytes > * as_vec
::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > * as_pred
} data
InstSeqNum fetch_seq
InstSeqNum cp_seq
enum Trace::InstRecord::DataStatus data_status
bool mem_valid
Are the memory fields in the record valid?
bool fetch_seq_valid
Are the fetch sequence number fields valid?
bool cp_seq_valid
Are the commit sequence number fields valid?
bool predicate
is the predicate for execution this inst true or false (not execed)?
Detailed Description
Definition at line 47 of file exetrace.hh.
Constructor & Destructor Documentation
ExeTracerRecord()
Trace::ExeTracerRecord::ExeTracerRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst = NULL) inline
Definition at line 50 of file exetrace.hh.
References dump(), dumpTicks(), and traceInst().
Referenced by Trace::ExeTracer::getInstRecord().
Member Function Documentation
dump()
void Trace::ExeTracerRecord::dump () virtual
Implements Trace::InstRecord.
Reimplemented in Trace::NativeTraceRecord.
Definition at line 190 of file exetrace.cc.
Referenced by ExeTracerRecord().
dumpTicks()
void Trace::ExeTracerRecord::dumpTicks (std::ostream & outs) virtual
Definition at line 66 of file exetrace.cc.
References ccprintf().
Referenced by ExeTracerRecord().
traceInst()
void Trace::ExeTracerRecord::traceInst (const StaticInstPtr & inst, bool ran)
Definition at line 72 of file exetrace.cc.
References addr, ccprintf(), csprintf(), data, debugSymbolTable, StaticInst::disassemble(), SymbolTable::findNearestSymbol(), FullSystem, AlphaISA::getExecutingAsid(), ArmISA::i, AlphaISA::inUserMode(), StaticInst::isMicroop(), StaticInst::opClass(), Trace::output(), MipsISA::pc, StaticInst::printFlags(), AlphaISA::VecPredRegSizeBits, and AlphaISA::VecRegSizeBytes.
Referenced by Trace::ArmNativeTrace::check(), and ExeTracerRecord().
The documentation for this class was generated from the following files:
cpu/exetrace.hh
cpu/exetrace.cc