gem5: ProfileNode Class Reference
ProfileNode Class Reference
#include <profile.hh>
Public Member Functions
ProfileNode ()
void dump (const std::string &symbol, uint64_t id, const SymbolTable *symtab, std::ostream &os) const
void clear ()
Public Attributes
Counter count
Private Types
typedef std::map< Addr, ProfileNode * > ChildList
Private Attributes
ChildList children
Friends
class FunctionProfile
Detailed Description
Definition at line 43 of file profile.hh.
Member Typedef Documentation
ChildList
typedef std::map<Addr, ProfileNode *> ProfileNode::ChildList private
Definition at line 48 of file profile.hh.
Constructor & Destructor Documentation
ProfileNode()
ProfileNode::ProfileNode ()
Definition at line 45 of file profile.cc.
Member Function Documentation
clear()
void ProfileNode::clear ()
Definition at line 80 of file profile.cc.
References children, count, and ArmISA::i.
dump()
void ProfileNode::dump (const std::string & symbol, uint64_t id, const SymbolTable * symtab, std::ostream & os) const
Definition at line 50 of file profile.cc.
References addr, ccprintf(), children, count, dump(), SymbolTable::findSymbol(), ArmISA::i, and panic.
Referenced by dump().
Friends And Related Function Documentation
FunctionProfile
friend class FunctionProfile friend
Definition at line 46 of file profile.hh.
Member Data Documentation
children
ChildList ProfileNode::children private
Definition at line 49 of file profile.hh.
Referenced by clear(), FunctionProfile::consume(), and dump().
count
Counter ProfileNode::count
Definition at line 52 of file profile.hh.
Referenced by clear(), dump(), and FunctionProfile::sample().
The documentation for this class was generated from the following files:
cpu/profile.hh
cpu/profile.cc