gem5: SRegOperand Class Reference
SRegOperand Class Reference
#include <operand.hh>
Public Member Functions
bool init (unsigned opOffset, const BrigObject *obj)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj)
template<typename OperandType >
OperandType get (Wavefront *w, int lane)
uint32_t getTarget (Wavefront *w, int lane)
template<typename OperandType >
void set (Wavefront *w, int lane, OperandType &val)
std::string disassemble ()
template<>
void set (Wavefront *w, int lane, uint64_t &val)
Public Member Functions inherited from BaseRegOperand
bool init (unsigned opOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at, unsigned &maxRegIdx, char _regFileChar)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
unsigned int regIndex ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Static Public Attributes
static unsigned maxRegIdx
Additional Inherited Members
Public Attributes inherited from BaseRegOperand
unsigned regIdx
char regFileChar
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 120 of file operand.hh.
Member Function Documentation
disassemble()
std::string SRegOperand::disassemble ()
Definition at line 195 of file operand.cc.
References csprintf().
get()
template<typename OperandType > OperandType SRegOperand::get (Wavefront * w, int lane) inline
Definition at line 156 of file operand.hh.
References Wavefront::computeUnit, panic, Wavefront::remap(), Wavefront::simdId, and ComputeUnit::vrf.
getTarget()
uint32_t SRegOperand::getTarget (Wavefront * w, int lane) inline
Definition at line 190 of file operand.hh.
References X86ISA::val, and MipsISA::w.
init()
bool SRegOperand::init (unsigned opOffset, const BrigObject * obj) inline
Definition at line 126 of file operand.hh.
References BaseRegOperand::init(), BaseOperand::registerType, and BaseOperand::regOperandSize.
init_from_vect()
bool SRegOperand::init_from_vect (unsigned opOffset, const BrigObject * obj, int at) inline
Definition at line 135 of file operand.hh.
References BaseRegOperand::init_from_vect(), BaseOperand::registerType, and BaseOperand::regOperandSize.
initWithStrOffset()
void SRegOperand::initWithStrOffset (unsigned strOffset, const BrigObject * obj) inline
Definition at line 145 of file operand.hh.
References BaseRegOperand::initWithStrOffset(), BaseOperand::registerType, and BaseOperand::regOperandSize.
set() [1/2]
template<typename OperandType > void SRegOperand::set (Wavefront * w, int lane, OperandType & val)
Definition at line 202 of file operand.hh.
References Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, Wavefront::remap(), Wavefront::simdId, X86ISA::val, ComputeUnit::vrf, and Wavefront::wfSlotId.
set() [2/2]
template<> void SRegOperand::set (Wavefront * w, int lane, uint64_t & val) inline
Definition at line 215 of file operand.hh.
References Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, Wavefront::remap(), Wavefront::simdId, X86ISA::val, ComputeUnit::vrf, and Wavefront::wfSlotId.
Member Data Documentation
maxRegIdx
unsigned SRegOperand::maxRegIdx static
Definition at line 123 of file operand.hh.
Referenced by HsailCode::init(), and BaseRegOperand::initWithStrOffset().
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc