gem5: sc_core::sc_port_base Class Reference
sc_core::sc_port_base Class Reference abstract
#include <sc_port.hh>
Public Member Functions
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
const char * kind () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
void bind (sc_interface &)
void bind (sc_port_base &)
virtual int vbind (sc_interface &)=0
virtual int vbind (sc_port_base &)=0
virtual void before_end_of_elaboration ()=0
virtual void end_of_elaboration ()=0
virtual void start_of_simulation ()=0
virtual void end_of_simulation ()=0
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Member Functions
virtual sc_interface * _gem5Interface (int n) const =0
virtual void _gem5AddInterface (sc_interface *i)=0
virtual const char * _ifTypeName () const =0
virtual sc_port_policy _portPolicy () const =0
Private Attributes
::sc_gem5::Port * _gem5Port
Friends
class ::sc_gem5::Module
class ::sc_gem5::Port
class ::sc_gem5::Kernel
Detailed Description
Definition at line 76 of file sc_port.hh.
Constructor & Destructor Documentation
sc_port_base()
sc_core::sc_port_base::sc_port_base (const char * name, int n, sc_port_policy p)
Definition at line 61 of file sc_port.cc.
References _gem5Port, kind(), ArmISA::m, sc_core::sc_object::name(), sc_gem5::pickParentModule(), sc_core::SC_ID_INSERT_PORT_, sc_core::SC_ID_PORT_OUTSIDE_MODULE_, sc_core::sc_is_running(), and sc_gem5::scheduler.
~sc_port_base()
sc_core::sc_port_base::~sc_port_base () virtual
Definition at line 81 of file sc_port.cc.
References _gem5Port.
Member Function Documentation
_gem5AddInterface()
virtual void sc_core::sc_port_base::_gem5AddInterface (sc_interface * i) private pure virtual
Implemented in sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
Referenced by sc_gem5::Port::addInterface().
_gem5Interface()
virtual sc_interface* sc_core::sc_port_base::_gem5Interface (int n) const private pure virtual
Implemented in sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
Referenced by sc_gem5::Port::addInterfaces(), tlm::tlm_event_finder_t< IF, T >::find_event(), and sc_gem5::Port::getInterface().
_ifTypeName()
virtual const char* sc_core::sc_port_base::_ifTypeName () const private pure virtual
Implemented in sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
Referenced by sc_gem5::Port::regPort().
_portPolicy()
virtual sc_port_policy sc_core::sc_port_base::_portPolicy () const private pure virtual
Implemented in sc_core::sc_port< IF, N, P >, sc_core::sc_port< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port< bw_interface_type, 1, sc_core::SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< bool >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_put_if< T >, 1 >, sc_core::sc_port< sc_signal_in_if< T >, 1 >, sc_core::sc_port< tlm_nonblocking_get_if< T >, 1 >, sc_core::sc_port< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_inout_if< bool >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_int< W > >, 1 >, sc_core::sc_port< sc_signal_inout_if< T >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< FW_IF, N, POL >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_peek_if< T >, 1 >, sc_core::sc_port< sc_fifo_out_if< T >, 0 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_fifo_in_if< T >, 0 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_int< W > >, 1 >, and sc_core::sc_port< bw_interface_type, N, POL >.
Referenced by sc_gem5::Port::finalize().
before_end_of_elaboration()
virtual void sc_core::sc_port_base::before_end_of_elaboration () protected pure virtual
Implemented in tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, sc_core::SC_ZERO_OR_MORE_BOUND >, tlm_utils::multi_passthrough_initiator_socket< MultiSocketSimpleSwitchAT >, sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
bind() [1/2]
void sc_core::sc_port_base::bind (sc_interface & i) protected
Definition at line 111 of file sc_port.cc.
References _gem5Port, and sc_gem5::Port::bind().
Referenced by sc_core::sc_in< sc_dt::sc_lv< W > >::bind(), sc_core::sc_in< bool >::bind(), sc_core::sc_in< sc_dt::sc_logic >::bind(), sc_core::sc_in< sc_dt::sc_int< W > >::bind(), sc_core::sc_in< sc_dt::sc_uint< W > >::bind(), sc_core::sc_in< sc_dt::sc_biguint< W > >::bind(), sc_core::sc_in< sc_dt::sc_bigint< W > >::bind(), sc_core::sc_inout< sc_dt::sc_int< W > >::bind(), sc_core::sc_inout< sc_dt::sc_uint< W > >::bind(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::bind(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::bind(), sc_core::sc_in< sc_dt::sc_int< W > >::operator()(), sc_core::sc_in< sc_dt::sc_uint< W > >::operator()(), sc_core::sc_in< sc_dt::sc_biguint< W > >::operator()(), sc_core::sc_in< sc_dt::sc_bigint< W > >::operator()(), sc_core::sc_inout< sc_dt::sc_int< W > >::operator()(), sc_core::sc_inout< sc_dt::sc_uint< W > >::operator()(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::operator()(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::operator()(), sc_core::sc_in< sc_dt::sc_int< W > >::sc_in(), sc_core::sc_in< sc_dt::sc_uint< W > >::sc_in(), sc_core::sc_in< sc_dt::sc_biguint< W > >::sc_in(), sc_core::sc_in< sc_dt::sc_bigint< W > >::sc_in(), sc_core::sc_in< sc_dt::sc_int< W > >::vbind(), sc_core::sc_in< sc_dt::sc_uint< W > >::vbind(), sc_core::sc_in< sc_dt::sc_biguint< W > >::vbind(), sc_core::sc_in< sc_dt::sc_bigint< W > >::vbind(), sc_core::sc_inout< sc_dt::sc_int< W > >::vbind(), sc_core::sc_inout< sc_dt::sc_uint< W > >::vbind(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::vbind(), and sc_core::sc_inout< sc_dt::sc_bigint< W > >::vbind().
bind() [2/2]
void sc_core::sc_port_base::bind (sc_port_base & p) protected
Definition at line 112 of file sc_port.cc.
References _gem5Port, and sc_gem5::Port::bind().
end_of_elaboration()
virtual void sc_core::sc_port_base::end_of_elaboration () protected pure virtual
Implemented in sc_core::sc_inout< sc_dt::sc_bigint< W > >, sc_core::sc_inout< sc_dt::sc_biguint< W > >, sc_core::sc_inout< sc_dt::sc_uint< W > >, sc_core::sc_inout< sc_dt::sc_int< W > >, sc_core::sc_in< sc_dt::sc_bigint< W > >, sc_core::sc_in< sc_dt::sc_biguint< W > >, sc_core::sc_in< sc_dt::sc_uint< W > >, sc_core::sc_in< sc_dt::sc_int< W > >, sc_core::sc_inout< sc_dt::sc_logic >, sc_core::sc_in< sc_dt::sc_logic >, sc_core::sc_inout< bool >, sc_core::sc_in< bool >, sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, sc_core::sc_port_b< tlm_nonblocking_put_if< T > >, sc_core::sc_in< T >, sc_core::sc_in< sc_dt::sc_lv< W > >, sc_core::sc_inout< T >, sc_core::sc_inout< sc_dt::sc_lv< W > >, sc_core::sc_inout_rv< W >, sc_core::sc_in_rv< W >, sc_core::sc_inout_resolved, and sc_core::sc_in_resolved.
end_of_simulation()
virtual void sc_core::sc_port_base::end_of_simulation () protected pure virtual
Implemented in sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
kind()
const char* sc_core::sc_port_base::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Reimplemented in sc_core::sc_inout< sc_dt::sc_bigint< W > >, sc_core::sc_inout< sc_dt::sc_biguint< W > >, sc_core::sc_inout< sc_dt::sc_uint< W > >, sc_core::sc_inout< sc_dt::sc_int< W > >, sc_core::sc_in< sc_dt::sc_bigint< W > >, sc_core::sc_in< sc_dt::sc_biguint< W > >, sc_core::sc_in< sc_dt::sc_uint< W > >, sc_core::sc_in< sc_dt::sc_int< W > >, sc_core::sc_port< IF, N, P >, sc_core::sc_port< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port< bw_interface_type, 1, sc_core::SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< bool >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_put_if< T >, 1 >, sc_core::sc_port< sc_signal_in_if< T >, 1 >, sc_core::sc_port< tlm_nonblocking_get_if< T >, 1 >, sc_core::sc_port< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_inout_if< bool >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_int< W > >, 1 >, sc_core::sc_port< sc_signal_inout_if< T >, 1 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_logic >, 1 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_biguint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< FW_IF, N, POL >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_bigint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< tlm_nonblocking_peek_if< T >, 1 >, sc_core::sc_port< sc_fifo_out_if< T >, 0 >, sc_core::sc_port< sc_signal_in_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >, sc_core::sc_port< sc_fifo_in_if< T >, 0 >, sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_int< W > >, 1 >, sc_core::sc_port< bw_interface_type, N, POL >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, N, POL >, tlm::tlm_initiator_socket< 32 >, tlm::tlm_initiator_socket< BUSWIDTH, my_extended_payload_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, tlm::tlm_base_protocol_types, N, POL >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, tlm::tlm_base_protocol_types, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_initiator_socket< BUSWIDTH, TYPES, 1, POL >, sc_core::sc_inout< sc_dt::sc_lv< W > >, sc_core::sc_in< sc_dt::sc_lv< W > >, sc_core::sc_out< bool >, tlm::tlm_base_initiator_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm::tlm_base_protocol_types >, tlm_bw_transport_if< tlm::tlm_base_protocol_types >, N, POL >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< tlm_base_protocol_types >, tlm_bw_transport_if< tlm_base_protocol_types >, 1, sc_core::SC_ONE_OR_MORE_BOUND >, tlm::tlm_base_initiator_socket< 64, ClockRateControlFwIf, ClockRateControlBwIf >, tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< my_extended_payload_types >, tlm_bw_transport_if< my_extended_payload_types >, N, POL >, and tlm::tlm_base_initiator_socket< 64, SignalInterruptFwIf, SignalInterruptBwIf >.
Definition at line 87 of file sc_port.hh.
Referenced by tlm::tlm_event_finder_t< IF, T >::find_event(), report_error(), and sc_port_base().
maxSize()
int sc_core::sc_port_base::maxSize () const
Definition at line 108 of file sc_port.cc.
References _gem5Port, and sc_gem5::Port::maxSize().
report_error()
void sc_core::sc_port_base::report_error (const char * id, const char * add_msg) const protected
Definition at line 99 of file sc_port.cc.
References kind(), sc_core::sc_object::name(), SC_REPORT_ERROR, and ArmISA::ss.
Referenced by sc_gem5::Port::finalize().
size()
int sc_core::sc_port_base::size () const
Definition at line 109 of file sc_port.cc.
References _gem5Port, and sc_gem5::Port::size().
Referenced by sc_gem5::Port::addInterfaces().
start_of_simulation()
virtual void sc_core::sc_port_base::start_of_simulation () protected pure virtual
Implemented in sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
vbind() [1/2]
virtual int sc_core::sc_port_base::vbind (sc_interface &) protected pure virtual
Implemented in sc_core::sc_inout< sc_dt::sc_bigint< W > >, sc_core::sc_inout< sc_dt::sc_biguint< W > >, sc_core::sc_inout< sc_dt::sc_uint< W > >, sc_core::sc_inout< sc_dt::sc_int< W > >, sc_core::sc_in< sc_dt::sc_bigint< W > >, sc_core::sc_in< sc_dt::sc_biguint< W > >, sc_core::sc_in< sc_dt::sc_uint< W > >, sc_core::sc_in< sc_dt::sc_int< W > >, sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
vbind() [2/2]
virtual int sc_core::sc_port_base::vbind (sc_port_base &) protected pure virtual
Implemented in sc_core::sc_inout< sc_dt::sc_bigint< W > >, sc_core::sc_inout< sc_dt::sc_biguint< W > >, sc_core::sc_inout< sc_dt::sc_uint< W > >, sc_core::sc_inout< sc_dt::sc_int< W > >, sc_core::sc_in< sc_dt::sc_bigint< W > >, sc_core::sc_in< sc_dt::sc_biguint< W > >, sc_core::sc_in< sc_dt::sc_uint< W > >, sc_core::sc_in< sc_dt::sc_int< W > >, sc_core::sc_port_b< IF >, sc_core::sc_port_b< FW_IF >, sc_core::sc_port_b< bw_interface_type >, sc_core::sc_port_b< tlm::tlm_master_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< bool > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_biguint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< sc_fifo_out_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_int< W > > >, sc_core::sc_port_b< tlm::tlm_transport_if< REQ, RSP > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_in_if< T > >, sc_core::sc_port_b< tlm_nonblocking_get_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_fifo_out_if< T > >, sc_core::sc_port_b< tlm_nonblocking_peek_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_bigint< W > > >, sc_core::sc_port_b< tlm::tlm_slave_if< REQ, RSP > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< sc_dt::sc_lv< W > > >, sc_core::sc_port_b< sc_signal_in_if< bool > >, sc_core::sc_port_b< sc_core::sc_fifo_in_if< T > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >, sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< T > >, sc_core::sc_port_b< sc_core::sc_signal_in_if< T > >, sc_core::sc_port_b< sc_signal_in_if< sc_dt::sc_logic > >, sc_core::sc_port_b< sc_core::sc_signal_inout_if< bool > >, and sc_core::sc_port_b< tlm_nonblocking_put_if< T > >.
warn_port_constructor()
void sc_core::sc_port_base::warn_port_constructor () const
Definition at line 87 of file sc_port.cc.
References sc_core::SC_ID_IEEE_1666_DEPRECATION_, and SC_REPORT_INFO.
Friends And Related Function Documentation
::sc_gem5::Kernel
friend class ::sc_gem5::Kernel friend
Definition at line 109 of file sc_port.hh.
::sc_gem5::Module
friend class ::sc_gem5::Module friend
Definition at line 94 of file sc_port.hh.
::sc_gem5::Port
friend class ::sc_gem5::Port friend
Definition at line 108 of file sc_port.hh.
Member Data Documentation
_gem5Port
::sc_gem5::Port* sc_core::sc_port_base::_gem5Port private
Definition at line 114 of file sc_port.hh.
Referenced by sc_gem5::Port::addInterfaces(), bind(), maxSize(), sc_port_base(), size(), and ~sc_port_base().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_port.hh
systemc/core/sc_port.cc