gem5: BasePixelPump Class Reference
BasePixelPump Class Reference abstract
Timing generator for a pixel-based display.
#include <pixelpump.hh>
Classes
class PixelEvent
Callback helper class with suspend support.
Public Member Functions
BasePixelPump (EventManager &em, ClockDomain &pxl_clk, unsigned pixel_chunk)
virtual ~BasePixelPump ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void updateTimings (const DisplayTimings &timings)
Update frame size using display timing.
void renderFrame ()
Render an entire frame in KVM execution mode.
void start ()
Starting pushing pixels in timing mode.
void stop ()
Immediately stop pushing pixels.
const DisplayTimings & timings () const
Get a constant reference of the current display timings.
bool active () const
Is the pixel pump active and refreshing the display?
bool underrun () const
Did a buffer underrun occur within this refresh interval?
bool visibleLine () const
Is the current line within the visible range?
unsigned posX () const
Current pixel position within the visible area.
unsigned posY () const
Current pixel position within the visible area.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
FrameBuffer fb
Output frame buffer.
Protected Member Functions
virtual bool nextPixel (Pixel &p)=0
Get the next pixel from the scan line buffer.
virtual void onVSyncBegin ()
First pixel clock of the first VSync line.
virtual void onVSyncEnd ()
Callback on the first pixel of the line after the end VSync region (typically the first pixel of the vertical back porch).
virtual void onHSyncBegin ()
Start of the HSync region.
virtual void onHSyncEnd ()
Start of the first pixel after the HSync region.
virtual void onUnderrun (unsigned x, unsigned y)
Buffer underrun occurred on a frame.
virtual void onFrameDone ()
Finished displaying the visible region of a frame.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Private Member Functions
void beginLine ()
void renderPixels ()
void renderLine ()
Fast and event-free line rendering function.
Private Attributes
const unsigned pixelChunk
Maximum number of pixels to handle per render callback.
std::vector< PixelEvent * > pixelEvents
Convenience vector when doing operations on all events.
PixelEvent evVSyncBegin
PixelEvent evVSyncEnd
PixelEvent evHSyncBegin
PixelEvent evHSyncEnd
PixelEvent evBeginLine
PixelEvent evRenderPixels
DisplayTimings _timings
unsigned line
Current line (including back porch, front porch, and vsync) within a frame.
unsigned _posX
X-coordinate within the visible region of a frame.
bool _underrun
Did a buffer underrun occur within this refresh interval?
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Timing generator for a pixel-based display.
Pixels are ordered relative to the top left corner of the display. Scan lines appear in the following order:
Vertical Sync (starting at line 0)
Vertical back porch
Visible lines
Vertical front porch
Pixel order within a scan line:
Horizontal Sync
Horizontal Back Porch
Visible pixels
Horizontal Front Porch
Definition at line 146 of file pixelpump.hh.
Constructor & Destructor Documentation
BasePixelPump()
BasePixelPump::BasePixelPump (EventManager & em, ClockDomain & pxl_clk, unsigned pixel_chunk)
Definition at line 88 of file pixelpump.cc.
~BasePixelPump()
BasePixelPump::~BasePixelPump () virtual
Definition at line 104 of file pixelpump.cc.
Member Function Documentation
active()
bool BasePixelPump::active () const inline
Is the pixel pump active and refreshing the display?
Definition at line 175 of file pixelpump.hh.
Referenced by HDLcd::drainResume(), and updateTimings().
beginLine()
void BasePixelPump::beginLine () private
Definition at line 182 of file pixelpump.cc.
References _posX, _timings, _underrun, Clocked::clockEdge(), DisplayTimings::cyclesPerLine(), evBeginLine, evHSyncBegin, evHSyncEnd, evRenderPixels, DisplayTimings::hBackPorch, DisplayTimings::hSync, line, DisplayTimings::lineFirstVisible(), DisplayTimings::lineFrontPorchStart(), DisplayTimings::linesPerFrame(), DisplayTimings::lineVBackPorchStart(), DisplayTimings::lineVSyncStart(), onVSyncBegin(), onVSyncEnd(), and EventManager::schedule().
nextPixel()
virtual bool BasePixelPump::nextPixel (Pixel & p) protected pure virtual
Get the next pixel from the scan line buffer.
Parameters
p Output pixel value, undefined on underrun
Returns
true on success, false on buffer underrun
Implemented in HDLcd::PixelPump.
Referenced by renderLine(), and renderPixels().
onFrameDone()
virtual void BasePixelPump::onFrameDone () inline protected virtual
Finished displaying the visible region of a frame.
Reimplemented in HDLcd::PixelPump.
Definition at line 244 of file pixelpump.hh.
Referenced by renderFrame(), and renderPixels().
onHSyncBegin()
virtual void BasePixelPump::onHSyncBegin () inline protected virtual
Start of the HSync region.
Note
This is called even for scan lines outside of the visible region.
Definition at line 221 of file pixelpump.hh.
Referenced by renderFrame().
onHSyncEnd()
virtual void BasePixelPump::onHSyncEnd () inline protected virtual
Start of the first pixel after the HSync region.
Note
This is called even for scan lines outside of the visible region.
Definition at line 229 of file pixelpump.hh.
Referenced by renderFrame().
onUnderrun()
virtual void BasePixelPump::onUnderrun (unsigned x, unsigned y) inline protected virtual
Buffer underrun occurred on a frame.
This method is called once if there is buffer underrun while refreshing the display. The underrun state is reset on the next refresh.
Parameters
x Coordinate within the visible region.
y Coordinate within the visible region.
Reimplemented in HDLcd::PixelPump.
Definition at line 241 of file pixelpump.hh.
Referenced by renderPixels().
onVSyncBegin()
virtual void BasePixelPump::onVSyncBegin () inline protected virtual
First pixel clock of the first VSync line.
Reimplemented in HDLcd::PixelPump.
Definition at line 207 of file pixelpump.hh.
Referenced by beginLine(), and renderFrame().
onVSyncEnd()
virtual void BasePixelPump::onVSyncEnd () inline protected virtual
Callback on the first pixel of the line after the end VSync region (typically the first pixel of the vertical back porch).
Reimplemented in HDLcd::PixelPump.
Definition at line 213 of file pixelpump.hh.
Referenced by beginLine(), and renderFrame().
posX()
unsigned BasePixelPump::posX () const inline
Current pixel position within the visible area.
Definition at line 187 of file pixelpump.hh.
posY()
unsigned BasePixelPump::posY () const inline
Current pixel position within the visible area.
Definition at line 190 of file pixelpump.hh.
Referenced by renderLine(), and renderPixels().
renderFrame()
void BasePixelPump::renderFrame ()
Render an entire frame in KVM execution mode.
Definition at line 252 of file pixelpump.cc.
References _posX, _timings, _underrun, line, DisplayTimings::lineFirstVisible(), DisplayTimings::lineFrontPorchStart(), DisplayTimings::lineVBackPorchStart(), DisplayTimings::lineVSyncStart(), onFrameDone(), onHSyncBegin(), onHSyncEnd(), onVSyncBegin(), onVSyncEnd(), and renderLine().
Referenced by HDLcd::virtRefresh().
renderLine()
void BasePixelPump::renderLine () private
Fast and event-free line rendering function.
Definition at line 284 of file pixelpump.cc.
References _posX, _timings, fb, nextPixel(), panic, FrameBuffer::pixel(), posY(), and DisplayTimings::width.
Referenced by renderFrame().
renderPixels()
void BasePixelPump::renderPixels () private
Definition at line 215 of file pixelpump.cc.
References _posX, _timings, _underrun, Clocked::clockEdge(), evRenderPixels, fb, DisplayTimings::height, nextPixel(), onFrameDone(), onUnderrun(), FrameBuffer::pixel(), pixelChunk, posY(), EventManager::schedule(), warn, and DisplayTimings::width.
serialize()
void BasePixelPump::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 109 of file pixelpump.cc.
References _posX, _timings, _underrun, MipsISA::event, fb, line, pixelEvents, SERIALIZE_OBJ, and SERIALIZE_SCALAR.
start()
void BasePixelPump::start ()
Starting pushing pixels in timing mode.
Definition at line 156 of file pixelpump.cc.
References Clocked::clockEdge(), evBeginLine, and EventManager::schedule().
Referenced by HDLcd::cmdEnable().
stop()
void BasePixelPump::stop ()
Immediately stop pushing pixels.
Definition at line 163 of file pixelpump.cc.
References EventManager::deschedule(), evBeginLine, evHSyncBegin, evHSyncEnd, evRenderPixels, evVSyncEnd, and Event::scheduled().
Referenced by HDLcd::cmdDisable().
timings()
const DisplayTimings& BasePixelPump::timings () const inline
Get a constant reference of the current display timings.
Definition at line 172 of file pixelpump.hh.
Referenced by updateTimings().
underrun()
bool BasePixelPump::underrun () const inline
Did a buffer underrun occur within this refresh interval?
Definition at line 178 of file pixelpump.hh.
unserialize()
void BasePixelPump::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 123 of file pixelpump.cc.
References _posX, _timings, _underrun, MipsISA::event, fb, line, pixelEvents, UNSERIALIZE_OBJ, and UNSERIALIZE_SCALAR.
Referenced by HDLcd::unserialize().
updateTimings()
void BasePixelPump::updateTimings (const DisplayTimings & timings)
Update frame size using display timing.
Definition at line 140 of file pixelpump.cc.
References _timings, active(), fb, FrameBuffer::height(), DisplayTimings::height, line, DisplayTimings::linesPerFrame(), panic_if, FrameBuffer::resize(), timings(), FrameBuffer::width(), and DisplayTimings::width.
Referenced by HDLcd::cmdEnable().
visibleLine()
bool BasePixelPump::visibleLine () const inline
Is the current line within the visible range?
Definition at line 181 of file pixelpump.hh.
Member Data Documentation
_posX
unsigned BasePixelPump::_posX private
X-coordinate within the visible region of a frame.
Definition at line 316 of file pixelpump.hh.
Referenced by beginLine(), renderFrame(), renderLine(), renderPixels(), serialize(), and unserialize().
_timings
DisplayTimings BasePixelPump::_timings private
Definition at line 308 of file pixelpump.hh.
Referenced by beginLine(), renderFrame(), renderLine(), renderPixels(), serialize(), unserialize(), and updateTimings().
_underrun
bool BasePixelPump::_underrun private
Did a buffer underrun occur within this refresh interval?
Definition at line 319 of file pixelpump.hh.
Referenced by beginLine(), renderFrame(), renderPixels(), serialize(), and unserialize().
evBeginLine
PixelEvent BasePixelPump::evBeginLine private
Definition at line 305 of file pixelpump.hh.
Referenced by beginLine(), start(), and stop().
evHSyncBegin
PixelEvent BasePixelPump::evHSyncBegin private
Definition at line 303 of file pixelpump.hh.
Referenced by beginLine(), and stop().
evHSyncEnd
PixelEvent BasePixelPump::evHSyncEnd private
Definition at line 304 of file pixelpump.hh.
Referenced by beginLine(), and stop().
evRenderPixels
PixelEvent BasePixelPump::evRenderPixels private
Definition at line 306 of file pixelpump.hh.
Referenced by beginLine(), renderPixels(), and stop().
evVSyncBegin
PixelEvent BasePixelPump::evVSyncBegin private
Definition at line 301 of file pixelpump.hh.
evVSyncEnd
PixelEvent BasePixelPump::evVSyncEnd private
Definition at line 302 of file pixelpump.hh.
Referenced by stop().
fb
FrameBuffer BasePixelPump::fb
Output frame buffer.
Definition at line 195 of file pixelpump.hh.
Referenced by HDLcd::HDLcd(), renderLine(), renderPixels(), serialize(), unserialize(), and updateTimings().
line
unsigned BasePixelPump::line private
Current line (including back porch, front porch, and vsync) within a frame.
Definition at line 314 of file pixelpump.hh.
Referenced by beginLine(), renderFrame(), serialize(), unserialize(), and updateTimings().
pixelChunk
const unsigned BasePixelPump::pixelChunk private
Maximum number of pixels to handle per render callback.
Definition at line 244 of file pixelpump.hh.
Referenced by renderPixels().
pixelEvents
std::vector<PixelEvent *> BasePixelPump::pixelEvents private
Convenience vector when doing operations on all events.
Definition at line 299 of file pixelpump.hh.
Referenced by BasePixelPump::PixelEvent::PixelEvent(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/pixelpump.hh
dev/pixelpump.cc