gem5: sc_core::sc_simcontext Class Reference
sc_core::sc_simcontext Class Reference
#include <sc_simcontext.hh>
Public Member Functions
sc_dt::uint64 delta_count () const
void reset ()
sc_curr_proc_handle get_curr_proc_info ()
sc_object * first_object ()
sc_object * next_object ()
bool elaboration_done ()
Detailed Description
Definition at line 39 of file sc_simcontext.hh.
Member Function Documentation
delta_count()
sc_dt::uint64 sc_core::sc_simcontext::delta_count () const
Definition at line 48 of file sc_simcontext.cc.
References sc_core::sc_delta_count().
Referenced by sc_core::sc_signal< sc_dt::sc_int< W > >::update(), sc_core::sc_signal< sc_dt::sc_uint< W > >::update(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::update(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::update().
elaboration_done()
bool sc_core::sc_simcontext::elaboration_done ()
Definition at line 81 of file sc_simcontext.cc.
References sc_gem5::Scheduler::elaborationDone(), and sc_gem5::scheduler.
first_object()
sc_object * sc_core::sc_simcontext::first_object ()
Definition at line 61 of file sc_simcontext.cc.
References sc_gem5::allObjects.
get_curr_proc_info()
sc_curr_proc_handle sc_core::sc_simcontext::get_curr_proc_info ()
Definition at line 52 of file sc_simcontext.cc.
References sc_gem5::Scheduler::current(), MipsISA::p, sc_gem5::Process::procKind(), sc_core::SC_NO_PROC_, and sc_gem5::scheduler.
next_object()
sc_object * sc_core::sc_simcontext::next_object ()
Definition at line 71 of file sc_simcontext.cc.
References sc_gem5::allObjects.
reset()
void sc_core::sc_simcontext::reset ()
Definition at line 49 of file sc_simcontext.cc.
The documentation for this class was generated from the following files:
systemc/ext/core/sc_simcontext.hh
systemc/core/sc_simcontext.cc