gem5: DRegOperand Class Reference
DRegOperand Class Reference
#include <operand.hh>
Public Member Functions
bool init (unsigned opOffset, const BrigObject *obj)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj)
template<typename OperandType >
OperandType get (Wavefront *w, int lane)
template<typename OperandType >
void set (Wavefront *w, int lane, OperandType &val)
std::string disassemble ()
Public Member Functions inherited from BaseRegOperand
bool init (unsigned opOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at, unsigned &maxRegIdx, char _regFileChar)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
unsigned int regIndex ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Static Public Attributes
static unsigned maxRegIdx
Additional Inherited Members
Public Attributes inherited from BaseRegOperand
unsigned regIdx
char regFileChar
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 225 of file operand.hh.
Member Function Documentation
disassemble()
std::string DRegOperand::disassemble ()
Definition at line 201 of file operand.cc.
References csprintf().
get()
template<typename OperandType > OperandType DRegOperand::get (Wavefront * w, int lane) inline
Definition at line 261 of file operand.hh.
References Wavefront::computeUnit, Wavefront::remap(), Wavefront::simdId, and ComputeUnit::vrf.
init()
bool DRegOperand::init (unsigned opOffset, const BrigObject * obj) inline
Definition at line 231 of file operand.hh.
References BaseRegOperand::init(), BaseOperand::registerType, and BaseOperand::regOperandSize.
init_from_vect()
bool DRegOperand::init_from_vect (unsigned opOffset, const BrigObject * obj, int at) inline
Definition at line 240 of file operand.hh.
References BaseRegOperand::init_from_vect(), BaseOperand::registerType, and BaseOperand::regOperandSize.
initWithStrOffset()
void DRegOperand::initWithStrOffset (unsigned strOffset, const BrigObject * obj) inline
Definition at line 250 of file operand.hh.
References BaseRegOperand::initWithStrOffset(), BaseOperand::registerType, and BaseOperand::regOperandSize.
set()
template<typename OperandType > void DRegOperand::set (Wavefront * w, int lane, OperandType & val) inline
Definition at line 273 of file operand.hh.
References Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, Wavefront::remap(), Wavefront::simdId, X86ISA::val, ComputeUnit::vrf, and Wavefront::wfSlotId.
Member Data Documentation
maxRegIdx
unsigned DRegOperand::maxRegIdx static
Definition at line 228 of file operand.hh.
Referenced by HsailCode::init(), and BaseRegOperand::initWithStrOffset().
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc