gem5: sc_core::sc_signal< sc_dt::sc_biguint< W > > Class Reference
sc_core::sc_signal< sc_dt::sc_biguint< W > > Class Reference
#include <scx_signal_unsigned.h>
Public Types
typedef sc_signal< sc_dt::sc_biguint< W > > this_type
Public Types inherited from sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >
typedef sc_signal_in_if< sc_dt::sc_biguint< W > > this_type
Public Member Functions
sc_signal ()
sc_signal (const char *name_)
virtual ~sc_signal ()
bool base_event () const
const sc_dt::sc_biguint< W > & base_read () const
const sc_event & base_value_changed_event () const
void base_write (sc_dt::int64 value)
void base_write (sc_dt::uint64 value)
void base_write (const sc_dt::sc_signed &value)
void base_write (const sc_dt::sc_unsigned &value)
virtual const char * kind () const
virtual void update ()
virtual const sc_event & default_event () const
virtual void register_port (sc_port_base &port_, const char *if_typename_)
virtual sc_dt::sc_unsigned * part_read_target ()
virtual sc_dt::sc_unsigned read_part (int left, int right) const
virtual sc_unsigned_sigref & select_part (int left, int right)
virtual void write_part (sc_dt::int64 v, int left, int right)
virtual void write_part (sc_dt::uint64 v, int left, int right)
virtual void write_part (const sc_dt::sc_signed &v, int left, int right)
virtual void write_part (const sc_dt::sc_unsigned &v, int left, int right)
virtual bool event () const
virtual const sc_dt::sc_biguint< W > & get_data_ref () const
virtual sc_signal< sc_dt::sc_biguint< W > > & get_signal ()
virtual const sc_dt::sc_biguint< W > & read () const
virtual const sc_event & value_changed_event () const
virtual void write (const sc_in< sc_dt::sc_biguint< W > > &value)
virtual void write (const sc_inout< sc_dt::sc_biguint< W > > &value)
virtual void write (const sc_dt::sc_biguint< W > &value)
sc_unsigned_sigref & operator() (int left, int right)
sc_unsigned_sigref & operator[] (int bit)
void operator= (const this_type &new_val)
void operator= (const char *new_val)
void operator= (sc_dt::uint64 new_val)
void operator= (sc_dt::int64 new_val)
void operator= (int new_val)
void operator= (long new_val)
void operator= (short new_val)
void operator= (unsigned int new_val)
void operator= (unsigned long new_val)
void operator= (unsigned short new_val)
template<typename T >
void operator= (const sc_dt::sc_generic_base< T > &new_val)
void operator= (const sc_dt::sc_signed &new_val)
void operator= (const sc_dt::sc_unsigned &new_val)
void operator= (const sc_dt::sc_bv_base &new_val)
void operator= (const sc_dt::sc_lv_base &new_val)
virtual void concat_set (sc_dt::int64 src, int low_i)
virtual void concat_set (const sc_dt::sc_lv_base &src, int low_i)
virtual void concat_set (const sc_dt::sc_signed &src, int low_i)
virtual void concat_set (const sc_dt::sc_unsigned &src, int low_i)
virtual void concat_set (sc_dt::uint64 src, int low_i)
template<typename T >
SC_TEMPLATE void operator= (const sc_dt::sc_generic_base< T > &new_val)
Public Member Functions inherited from sc_dt::sc_biguint< W >
sc_biguint ()
sc_biguint (const sc_biguint< W > &v)
sc_biguint (const sc_unsigned &v)
sc_biguint (const sc_unsigned_subref &v)
template<class T >
sc_biguint (const sc_generic_base< T > &a)
sc_biguint (const sc_signed &v)
sc_biguint (const sc_signed_subref &v)
sc_biguint (const char *v)
sc_biguint (int64 v)
sc_biguint (uint64 v)
sc_biguint (long v)
sc_biguint (unsigned long v)
sc_biguint (int v)
sc_biguint (unsigned int v)
sc_biguint (double v)
sc_biguint (const sc_bv_base &v)
sc_biguint (const sc_lv_base &v)
sc_biguint (const sc_fxval &v)
sc_biguint (const sc_fxval_fast &v)
sc_biguint (const sc_fxnum &v)
sc_biguint (const sc_fxnum_fast &v)
~sc_biguint ()
sc_biguint< W > & operator= (const sc_biguint< W > &v)
sc_biguint< W > & operator= (const sc_unsigned &v)
sc_biguint< W > & operator= (const sc_unsigned_subref &v)
template<class T >
sc_biguint< W > & operator= (const sc_generic_base< T > &a)
sc_biguint< W > & operator= (const sc_signed &v)
sc_biguint< W > & operator= (const sc_signed_subref &v)
sc_biguint< W > & operator= (const char *v)
sc_biguint< W > & operator= (int64 v)
sc_biguint< W > & operator= (uint64 v)
sc_biguint< W > & operator= (long v)
sc_biguint< W > & operator= (unsigned long v)
sc_biguint< W > & operator= (int v)
sc_biguint< W > & operator= (unsigned int v)
sc_biguint< W > & operator= (double v)
sc_biguint< W > & operator= (const sc_bv_base &v)
sc_biguint< W > & operator= (const sc_lv_base &v)
sc_biguint< W > & operator= (const sc_int_base &v)
sc_biguint< W > & operator= (const sc_uint_base &v)
sc_biguint< W > & operator= (const sc_fxval &v)
sc_biguint< W > & operator= (const sc_fxval_fast &v)
sc_biguint< W > & operator= (const sc_fxnum &v)
sc_biguint< W > & operator= (const sc_fxnum_fast &v)
Public Member Functions inherited from sc_dt::sc_unsigned
sc_unsigned (int nb=sc_length_param().len())
sc_unsigned (const sc_unsigned &v)
sc_unsigned (const sc_signed &v)
template<class T >
sc_unsigned (const sc_generic_base< T > &v)
sc_unsigned (const sc_bv_base &v)
sc_unsigned (const sc_lv_base &v)
sc_unsigned (const sc_int_subref_r &v)
sc_unsigned (const sc_uint_subref_r &v)
sc_unsigned (const sc_signed_subref_r &v)
sc_unsigned (const sc_unsigned_subref_r &v)
const sc_unsigned & operator= (const sc_unsigned &v)
const sc_unsigned & operator= (const sc_unsigned_subref_r &a)
template<class T >
const sc_unsigned & operator= (const sc_generic_base< T > &a)
const sc_unsigned & operator= (const sc_signed &v)
const sc_unsigned & operator= (const sc_signed_subref_r &a)
const sc_unsigned & operator= (const char *v)
const sc_unsigned & operator= (int64 v)
const sc_unsigned & operator= (uint64 v)
const sc_unsigned & operator= (long v)
const sc_unsigned & operator= (unsigned long v)
const sc_unsigned & operator= (int v)
const sc_unsigned & operator= (unsigned int v)
const sc_unsigned & operator= (double v)
const sc_unsigned & operator= (const sc_int_base &v)
const sc_unsigned & operator= (const sc_uint_base &v)
const sc_unsigned & operator= (const sc_bv_base &)
const sc_unsigned & operator= (const sc_lv_base &)
const sc_unsigned & operator= (const sc_fxval &)
const sc_unsigned & operator= (const sc_fxval_fast &)
const sc_unsigned & operator= (const sc_fxnum &)
const sc_unsigned & operator= (const sc_fxnum_fast &)
virtual ~sc_unsigned ()
sc_digit * get_raw () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
sc_unsigned & operator++ ()
const sc_unsigned operator++ (int)
sc_unsigned & operator-- ()
const sc_unsigned operator-- (int)
void check_index (int i) const
void invalid_index (int i) const
sc_unsigned_bitref & operator[] (int i)
const sc_unsigned_bitref_r & operator[] (int i) const
sc_unsigned_bitref & bit (int i)
const sc_unsigned_bitref_r & bit (int i) const
void check_range (int l, int r) const
void invalid_range (int l, int r) const
sc_unsigned_subref & range (int i, int j)
const sc_unsigned_subref_r & range (int i, int j) const
sc_unsigned_subref & operator() (int i, int j)
const sc_unsigned_subref_r & operator() (int i, int j) const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
void dump (::std::ostream &os=::std::cout) const
int length () const
bool iszero () const
bool sign () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
bool test (int i) const
void set (int i)
void clear (int i)
void set (int i, bool v)
void invert (int i)
void reverse ()
void get_packed_rep (sc_digit *buf) const
void set_packed_rep (sc_digit *buf)
const sc_unsigned & operator+= (const sc_signed &v)
const sc_unsigned & operator+= (const sc_unsigned &v)
const sc_unsigned & operator+= (int64 v)
const sc_unsigned & operator+= (uint64 v)
const sc_unsigned & operator+= (long v)
const sc_unsigned & operator+= (unsigned long v)
const sc_unsigned & operator+= (int v)
const sc_unsigned & operator+= (unsigned int v)
const sc_unsigned & operator+= (const sc_int_base &v)
const sc_unsigned & operator+= (const sc_uint_base &v)
const sc_unsigned & operator-= (const sc_signed &v)
const sc_unsigned & operator-= (const sc_unsigned &v)
const sc_unsigned & operator-= (int64 v)
const sc_unsigned & operator-= (uint64 v)
const sc_unsigned & operator-= (long v)
const sc_unsigned & operator-= (unsigned long v)
const sc_unsigned & operator-= (int v)
const sc_unsigned & operator-= (unsigned int v)
const sc_unsigned & operator-= (const sc_int_base &v)
const sc_unsigned & operator-= (const sc_uint_base &v)
const sc_unsigned & operator*= (const sc_signed &v)
const sc_unsigned & operator*= (const sc_unsigned &v)
const sc_unsigned & operator*= (int64 v)
const sc_unsigned & operator*= (uint64 v)
const sc_unsigned & operator*= (long v)
const sc_unsigned & operator*= (unsigned long v)
const sc_unsigned & operator*= (int v)
const sc_unsigned & operator*= (unsigned int v)
const sc_unsigned & operator*= (const sc_int_base &v)
const sc_unsigned & operator*= (const sc_uint_base &v)
const sc_unsigned & operator/= (const sc_signed &v)
const sc_unsigned & operator/= (const sc_unsigned &v)
const sc_unsigned & operator/= (int64 v)
const sc_unsigned & operator/= (uint64 v)
const sc_unsigned & operator/= (long v)
const sc_unsigned & operator/= (unsigned long v)
const sc_unsigned & operator/= (int v)
const sc_unsigned & operator/= (unsigned int v)
const sc_unsigned & operator/= (const sc_int_base &v)
const sc_unsigned & operator/= (const sc_uint_base &v)
const sc_unsigned & operator%= (const sc_signed &v)
const sc_unsigned & operator%= (const sc_unsigned &v)
const sc_unsigned & operator%= (int64 v)
const sc_unsigned & operator%= (uint64 v)
const sc_unsigned & operator%= (long v)
const sc_unsigned & operator%= (unsigned long v)
const sc_unsigned & operator%= (int v)
const sc_unsigned & operator%= (unsigned int v)
const sc_unsigned & operator%= (const sc_int_base &v)
const sc_unsigned & operator%= (const sc_uint_base &v)
const sc_unsigned & operator&= (const sc_signed &v)
const sc_unsigned & operator&= (const sc_unsigned &v)
const sc_unsigned & operator&= (int64 v)
const sc_unsigned & operator&= (uint64 v)
const sc_unsigned & operator&= (long v)
const sc_unsigned & operator&= (unsigned long v)
const sc_unsigned & operator&= (int v)
const sc_unsigned & operator&= (unsigned int v)
const sc_unsigned & operator&= (const sc_int_base &v)
const sc_unsigned & operator&= (const sc_uint_base &v)
const sc_unsigned & operator|= (const sc_signed &v)
const sc_unsigned & operator|= (const sc_unsigned &v)
const sc_unsigned & operator|= (int64 v)
const sc_unsigned & operator|= (uint64 v)
const sc_unsigned & operator|= (long v)
const sc_unsigned & operator|= (unsigned long v)
const sc_unsigned & operator|= (int v)
const sc_unsigned & operator|= (unsigned int v)
const sc_unsigned & operator|= (const sc_int_base &v)
const sc_unsigned & operator|= (const sc_uint_base &v)
const sc_unsigned & operator^= (const sc_signed &v)
const sc_unsigned & operator^= (const sc_unsigned &v)
const sc_unsigned & operator^= (int64 v)
const sc_unsigned & operator^= (uint64 v)
const sc_unsigned & operator^= (long v)
const sc_unsigned & operator^= (unsigned long v)
const sc_unsigned & operator^= (int v)
const sc_unsigned & operator^= (unsigned int v)
const sc_unsigned & operator^= (const sc_int_base &v)
const sc_unsigned & operator^= (const sc_uint_base &v)
const sc_unsigned & operator<<= (const sc_signed &v)
const sc_unsigned & operator<<= (const sc_unsigned &v)
const sc_unsigned & operator<<= (int64 v)
const sc_unsigned & operator<<= (uint64 v)
const sc_unsigned & operator<<= (long v)
const sc_unsigned & operator<<= (unsigned long v)
const sc_unsigned & operator<<= (int v)
const sc_unsigned & operator<<= (unsigned int v)
const sc_unsigned & operator<<= (const sc_int_base &v)
const sc_unsigned & operator<<= (const sc_uint_base &v)
const sc_unsigned & operator>>= (const sc_signed &v)
const sc_unsigned & operator>>= (const sc_unsigned &v)
const sc_unsigned & operator>>= (int64 v)
const sc_unsigned & operator>>= (uint64 v)
const sc_unsigned & operator>>= (long v)
const sc_unsigned & operator>>= (unsigned long v)
const sc_unsigned & operator>>= (int v)
const sc_unsigned & operator>>= (unsigned int v)
const sc_unsigned & operator>>= (const sc_int_base &v)
const sc_unsigned & operator>>= (const sc_uint_base &v)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_core::sc_interface
virtual ~sc_interface ()
Public Member Functions inherited from sc_core::sc_signal_write_if< sc_dt::sc_biguint< W > >
virtual sc_writer_policy get_writer_policy () const
Protected Member Functions
void check_writer ()
Protected Member Functions inherited from sc_core::sc_prim_channel
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from sc_core::sc_signal_inout_if< sc_dt::sc_biguint< W > >
sc_signal_inout_if ()
Protected Member Functions inherited from sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_unsigned_part_if
sc_unsigned_part_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_signal_write_if< sc_dt::sc_biguint< W > >
sc_signal_write_if ()
Protected Attributes
sc_event * m_changed_event_p
sc_dt::uint64 m_event_delta
sc_dt::sc_unsigned m_new_val
sc_port_base * m_output_p
sc_process_b * m_writer_p
Private Member Functions
sc_dt::sc_unsigned & operator++ ()
const sc_dt::sc_unsigned & operator++ (int)
sc_dt::sc_unsigned & operator-- ()
const sc_dt::sc_unsigned & operator-- (int)
sc_dt::sc_unsigned & operator+= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator+= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator+= (sc_dt::int64)
sc_dt::sc_unsigned & operator+= (sc_dt::uint64)
sc_dt::sc_unsigned & operator+= (long)
sc_dt::sc_unsigned & operator+= (unsigned long)
sc_dt::sc_unsigned & operator+= (int)
sc_dt::sc_unsigned & operator+= (unsigned int)
sc_dt::sc_unsigned & operator-= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator-= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator-= (sc_dt::int64)
sc_dt::sc_unsigned & operator-= (sc_dt::uint64)
sc_dt::sc_unsigned & operator-= (long)
sc_dt::sc_unsigned & operator-= (unsigned long)
sc_dt::sc_unsigned & operator-= (int)
sc_dt::sc_unsigned & operator-= (unsigned int)
sc_dt::sc_unsigned & operator*= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator*= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator*= (sc_dt::int64)
sc_dt::sc_unsigned & operator*= (sc_dt::uint64)
sc_dt::sc_unsigned & operator*= (long)
sc_dt::sc_unsigned & operator*= (unsigned long)
sc_dt::sc_unsigned & operator*= (int)
sc_dt::sc_unsigned & operator*= (unsigned int)
sc_dt::sc_unsigned & operator/= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator/= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator/= (sc_dt::int64)
sc_dt::sc_unsigned & operator/= (sc_dt::uint64)
sc_dt::sc_unsigned & operator/= (long)
sc_dt::sc_unsigned & operator/= (unsigned long)
sc_dt::sc_unsigned & operator/= (int)
sc_dt::sc_unsigned & operator/= (unsigned int)
sc_dt::sc_unsigned & operator%= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator%= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator%= (sc_dt::int64)
sc_dt::sc_unsigned & operator%= (sc_dt::uint64)
sc_dt::sc_unsigned & operator%= (long)
sc_dt::sc_unsigned & operator%= (unsigned long)
sc_dt::sc_unsigned & operator%= (int)
sc_dt::sc_unsigned & operator%= (unsigned int)
sc_dt::sc_unsigned & operator&= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator&= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator&= (sc_dt::int64)
sc_dt::sc_unsigned & operator&= (sc_dt::uint64)
sc_dt::sc_unsigned & operator&= (long)
sc_dt::sc_unsigned & operator&= (unsigned long)
sc_dt::sc_unsigned & operator&= (int)
sc_dt::sc_unsigned & operator&= (unsigned int)
sc_dt::sc_unsigned & operator|= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator|= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator|= (sc_dt::int64)
sc_dt::sc_unsigned & operator|= (sc_dt::uint64)
sc_dt::sc_unsigned & operator|= (long)
sc_dt::sc_unsigned & operator|= (unsigned long)
sc_dt::sc_unsigned & operator|= (int)
sc_dt::sc_unsigned & operator|= (unsigned int)
sc_dt::sc_unsigned & operator^= (const sc_dt::sc_signed &)
sc_dt::sc_unsigned & operator^= (const sc_dt::sc_unsigned &)
sc_dt::sc_unsigned & operator^= (sc_dt::int64)
sc_dt::sc_unsigned & operator^= (sc_dt::uint64)
sc_dt::sc_unsigned & operator^= (long)
sc_dt::sc_unsigned & operator^= (unsigned long)
sc_dt::sc_unsigned & operator^= (int)
sc_dt::sc_unsigned & operator^= (unsigned int)
Additional Inherited Members
Static Public Attributes inherited from sc_dt::sc_unsigned
static sc_core::sc_vpool< sc_unsigned > m_pool
Detailed Description
Definition at line 325 of file scx_signal_unsigned.h.
Member Typedef Documentation
this_type
typedef sc_signal<sc_dt::sc_biguint<W> > sc_core::sc_signal< sc_dt::sc_biguint< W > >::this_type
Definition at line 331 of file scx_signal_unsigned.h.
Constructor & Destructor Documentation
sc_signal() [1/2]
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_biguint< W > >::sc_signal () inline
Definition at line 806 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
sc_signal() [2/2]
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_biguint< W > >::sc_signal (const char * name_) inline explicit
Definition at line 816 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
~sc_signal()
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_biguint< W > >::~sc_signal () inline virtual
Definition at line 826 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
Member Function Documentation
base_event()
SC_TEMPLATE bool sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_event () const inline
Definition at line 490 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_read()
SC_TEMPLATE const sc_dt::sc_biguint< W > & sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_read () const inline
Definition at line 497 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_value_changed_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_value_changed_event () const inline
Definition at line 504 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_write() [1/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_write (sc_dt::int64 value) inline
Definition at line 532 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_write() [2/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_write (sc_dt::uint64 value) inline
Definition at line 543 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_write() [3/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_write (const sc_dt::sc_signed & value) inline
Definition at line 512 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
base_write() [4/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::base_write (const sc_dt::sc_unsigned & value) inline
Definition at line 522 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
check_writer()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::check_writer () inline protected
Definition at line 560 of file scx_signal_unsigned.h.
References name(), sc_core::sc_object::name(), sc_core::sc_get_current_process_b(), sc_core::sc_signal_invalid_writer(), and SC_TEMPLATE.
concat_set() [1/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::concat_set (sc_dt::int64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_unsigned.
Definition at line 586 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
concat_set() [2/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::concat_set (const sc_dt::sc_lv_base & src, int low_i) inline virtual
Definition at line 599 of file scx_signal_unsigned.h.
References sc_dt::sc_lv_base::length(), and SC_TEMPLATE.
concat_set() [3/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::concat_set (const sc_dt::sc_signed & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_unsigned.
Definition at line 608 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
concat_set() [4/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::concat_set (const sc_dt::sc_unsigned & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_unsigned.
Definition at line 615 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
concat_set() [5/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::concat_set (sc_dt::uint64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_unsigned.
Definition at line 622 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
default_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_biguint< W > >::default_event () const inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 630 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
event()
SC_TEMPLATE bool sc_core::sc_signal< sc_dt::sc_biguint< W > >::event () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >.
Definition at line 635 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
get_data_ref()
SC_TEMPLATE const sc_dt::sc_biguint< W > & sc_core::sc_signal< sc_dt::sc_biguint< W > >::get_data_ref () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >.
Definition at line 640 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
get_signal()
SC_TEMPLATE sc_signal< sc_dt::sc_biguint< W > > & sc_core::sc_signal< sc_dt::sc_biguint< W > >::get_signal () inline virtual
Definition at line 645 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
kind()
SC_TEMPLATE const char * sc_core::sc_signal< sc_dt::sc_biguint< W > >::kind () const inline virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 650 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator%=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (const sc_dt::sc_signed &) private
operator%=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (const sc_dt::sc_unsigned &) private
operator%=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (sc_dt::int64) private
operator%=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (sc_dt::uint64) private
operator%=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (long) private
operator%=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (unsigned long) private
operator%=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (int) private
operator%=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator%= (unsigned int) private
operator&=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (const sc_dt::sc_signed &) private
operator&=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (const sc_dt::sc_unsigned &) private
operator&=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (sc_dt::int64) private
operator&=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (sc_dt::uint64) private
operator&=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (long) private
operator&=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (unsigned long) private
operator&=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (int) private
operator&=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator &= (unsigned int) private
operator()()
SC_TEMPLATE sc_unsigned_sigref & sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator() (int left, int right) inline
Definition at line 664 of file scx_signal_unsigned.h.
References sc_core::sc_unsigned_sigref::initialize(), sc_core::sc_unsigned_sigref::m_pool, and SC_TEMPLATE.
operator*=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (const sc_dt::sc_signed &) private
operator*=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (const sc_dt::sc_unsigned &) private
operator*=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (sc_dt::int64) private
operator*=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (sc_dt::uint64) private
operator*=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (long) private
operator*=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (unsigned long) private
operator*=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (int) private
operator*=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator*= (unsigned int) private
operator++() [1/2]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator++ () private
operator++() [2/2]
const sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator++ (int) private
operator+=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (const sc_dt::sc_signed &) private
operator+=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (const sc_dt::sc_unsigned &) private
operator+=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (sc_dt::int64) private
operator+=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (sc_dt::uint64) private
operator+=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (long) private
operator+=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (unsigned long) private
operator+=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (int) private
operator+=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator+= (unsigned int) private
operator--() [1/2]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-- () private
operator--() [2/2]
const sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-- (int) private
operator-=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (const sc_dt::sc_signed &) private
operator-=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (const sc_dt::sc_unsigned &) private
operator-=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (sc_dt::int64) private
operator-=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (sc_dt::uint64) private
operator-=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (long) private
operator-=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (unsigned long) private
operator-=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (int) private
operator-=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator-= (unsigned int) private
operator/=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (const sc_dt::sc_signed &) private
operator/=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (const sc_dt::sc_unsigned &) private
operator/=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (sc_dt::int64) private
operator/=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (sc_dt::uint64) private
operator/=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (long) private
operator/=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (unsigned long) private
operator/=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (int) private
operator/=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator/= (unsigned int) private
operator=() [1/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const this_type & new_val) inline
Definition at line 688 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [2/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const char * new_val) inline
Definition at line 692 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [3/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (sc_dt::uint64 new_val) inline
Definition at line 702 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [4/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (sc_dt::int64 new_val) inline
Definition at line 707 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [5/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (int new_val) inline
Definition at line 712 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [6/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (long new_val) inline
Definition at line 717 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [7/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (short new_val) inline
Definition at line 722 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [8/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (unsigned int new_val) inline
Definition at line 727 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [9/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (unsigned long new_val) inline
Definition at line 732 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [10/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (unsigned short new_val) inline
Definition at line 737 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [11/16]
template<typename T > void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
operator=() [12/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_signed & new_val) inline
Definition at line 753 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [13/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_unsigned & new_val) inline
Definition at line 697 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [14/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_bv_base & new_val) inline
Definition at line 757 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [15/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_lv_base & new_val) inline
Definition at line 761 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator=() [16/16]
template<typename T > SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
Definition at line 743 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator[]()
SC_TEMPLATE sc_unsigned_sigref & sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator[] (int bit) inline
Definition at line 681 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
operator^=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (const sc_dt::sc_signed &) private
operator^=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (const sc_dt::sc_unsigned &) private
operator^=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (sc_dt::int64) private
operator^=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (sc_dt::uint64) private
operator^=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (long) private
operator^=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (unsigned long) private
operator^=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (int) private
operator^=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator^= (unsigned int) private
operator|=() [1/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (const sc_dt::sc_signed &) private
operator|=() [2/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (const sc_dt::sc_unsigned &) private
operator|=() [3/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (sc_dt::int64) private
operator|=() [4/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (sc_dt::uint64) private
operator|=() [5/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (long) private
operator|=() [6/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (unsigned long) private
operator|=() [7/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (int) private
operator|=() [8/8]
sc_dt::sc_unsigned& sc_core::sc_signal< sc_dt::sc_biguint< W > >::operator|= (unsigned int) private
part_read_target()
SC_TEMPLATE sc_dt::sc_unsigned * sc_core::sc_signal< sc_dt::sc_biguint< W > >::part_read_target () inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 766 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
read()
SC_TEMPLATE const sc_dt::sc_biguint< W > & sc_core::sc_signal< sc_dt::sc_biguint< W > >::read () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >.
Definition at line 771 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
read_part()
SC_TEMPLATE sc_dt::sc_unsigned sc_core::sc_signal< sc_dt::sc_biguint< W > >::read_part (int left, int right) const inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 776 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
register_port()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::register_port (sc_port_base & port_, const char * if_typename_) inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 785 of file scx_signal_unsigned.h.
References name(), sc_core::sc_object::name(), sc_core::sc_signal_invalid_writer(), and SC_TEMPLATE.
select_part()
SC_TEMPLATE sc_unsigned_sigref & sc_core::sc_signal< sc_dt::sc_biguint< W > >::select_part (int left, int right) inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 879 of file scx_signal_unsigned.h.
References sc_core::sc_unsigned_sigref::initialize(), sc_core::sc_unsigned_sigref::m_pool, and SC_TEMPLATE.
update()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::update () inline virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 833 of file scx_signal_unsigned.h.
References sc_core::sc_simcontext::delta_count(), sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_dt::sc_unsigned::operator=(), SC_TEMPLATE, and sc_core::sc_object::simcontext().
value_changed_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_biguint< W > >::value_changed_event () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_biguint< W > >.
Definition at line 848 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
write() [1/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write (const sc_in< sc_dt::sc_biguint< W > > & value) inline virtual
Definition at line 853 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
write() [2/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write (const sc_inout< sc_dt::sc_biguint< W > > & value) inline virtual
Definition at line 859 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
write() [3/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write (const sc_dt::sc_biguint< W > & value) inline virtual
Implements sc_core::sc_signal_write_if< sc_dt::sc_biguint< W > >.
Definition at line 865 of file scx_signal_unsigned.h.
References SC_TEMPLATE.
write_part() [1/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part (sc_dt::int64 v, int left, int right) inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 871 of file scx_signal_unsigned.h.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_core::sc_prim_channel::request_update(), SC_TEMPLATE, and ArmISA::v.
write_part() [2/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part (sc_dt::uint64 v, int left, int right) inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 890 of file scx_signal_unsigned.h.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_core::sc_prim_channel::request_update(), SC_TEMPLATE, and ArmISA::v.
write_part() [3/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part (const sc_dt::sc_signed & v, int left, int right) inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 899 of file scx_signal_unsigned.h.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_core::sc_prim_channel::request_update(), SC_TEMPLATE, and ArmISA::v.
write_part() [4/4]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part (const sc_dt::sc_unsigned & v, int left, int right) inline virtual
Reimplemented from sc_core::sc_unsigned_part_if.
Definition at line 909 of file scx_signal_unsigned.h.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_core::sc_prim_channel::request_update(), SC_TEMPLATE, and ArmISA::v.
Member Data Documentation
m_changed_event_p
sc_event* sc_core::sc_signal< sc_dt::sc_biguint< W > >::m_changed_event_p mutable protected
Definition at line 481 of file scx_signal_unsigned.h.
m_event_delta
sc_dt::uint64 sc_core::sc_signal< sc_dt::sc_biguint< W > >::m_event_delta protected
Definition at line 482 of file scx_signal_unsigned.h.
m_new_val
sc_dt::sc_unsigned sc_core::sc_signal< sc_dt::sc_biguint< W > >::m_new_val protected
Definition at line 483 of file scx_signal_unsigned.h.
m_output_p
sc_port_base* sc_core::sc_signal< sc_dt::sc_biguint< W > >::m_output_p protected
Definition at line 484 of file scx_signal_unsigned.h.
m_writer_p
sc_process_b* sc_core::sc_signal< sc_dt::sc_biguint< W > >::m_writer_p protected
Definition at line 485 of file scx_signal_unsigned.h.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_unsigned.h