gem5: sc_core::sc_fifo< T > Class Template Reference
sc_core::sc_fifo< T > Class Template Reference
#include <sc_fifo.hh>
Public Member Functions
sc_fifo (int size=16)
sc_fifo (const char *name, int size=16)
virtual ~sc_fifo ()
virtual void register_port (sc_port_base &port, const char *iface_type_name)
virtual void read (T &t)
virtual T read ()
virtual bool nb_read (T &t)
operator T ()
virtual void write (const T &t)
virtual bool nb_write (const T &t)
sc_fifo< T > & operator= (const T &t)
virtual const sc_event & data_written_event () const
virtual const sc_event & data_read_event () const
virtual int num_available () const
virtual int num_free () const
virtual void print (std::ostream &os=std::cout) const
virtual void dump (std::ostream &os=std::cout) const
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_interface
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
virtual void update ()
Protected Member Functions inherited from sc_core::sc_fifo_in_if< T >
sc_fifo_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_fifo_out_if< T >
sc_fifo_out_if ()
Protected Member Functions inherited from sc_core::sc_prim_channel
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Member Functions
sc_fifo (const sc_fifo< T > &)
sc_fifo & operator= (const sc_fifo< T > &)
Private Attributes
sc_gem5::InternalScEvent _dataReadEvent
sc_gem5::InternalScEvent _dataWriteEvent
sc_port_base * _reader
sc_port_base * _writer
int _size
int _num_free
int _num_available
std::list< T > _entries
bool _readsHappened
bool _writesHappened
Detailed Description
template<class T>
class sc_core::sc_fifo< T >
Definition at line 50 of file sc_fifo.hh.
Constructor & Destructor Documentation
sc_fifo() [1/3]
template<class T > sc_core::sc_fifo< T >::sc_fifo (int size = 16) inline explicit
Definition at line 55 of file sc_fifo.hh.
sc_fifo() [2/3]
template<class T > sc_core::sc_fifo< T >::sc_fifo (const char * name, int size = 16) inline explicit
Definition at line 62 of file sc_fifo.hh.
~sc_fifo()
template<class T > virtual sc_core::sc_fifo< T >::~sc_fifo () inline virtual
Definition at line 68 of file sc_fifo.hh.
sc_fifo() [3/3]
template<class T > sc_core::sc_fifo< T >::sc_fifo (const sc_fifo< T > &) inline private
Definition at line 199 of file sc_fifo.hh.
Member Function Documentation
data_read_event()
template<class T > virtual const sc_event& sc_core::sc_fifo< T >::data_read_event () const inline virtual
Implements sc_core::sc_fifo_nonblocking_out_if< T >.
Definition at line 153 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_dataReadEvent.
data_written_event()
template<class T > virtual const sc_event& sc_core::sc_fifo< T >::data_written_event () const inline virtual
Implements sc_core::sc_fifo_nonblocking_in_if< T >.
Definition at line 148 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_dataWriteEvent.
dump()
template<class T > virtual void sc_core::sc_fifo< T >::dump (std::ostream & os = std::cout) const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 170 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_entries, sc_core::sc_object::name(), and X86ISA::os.
kind()
template<class T > virtual const char* sc_core::sc_fifo< T >::kind () const inline virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 179 of file sc_fifo.hh.
nb_read()
template<class T > virtual bool sc_core::sc_fifo< T >::nb_read (T & t) inline virtual
Implements sc_core::sc_fifo_nonblocking_in_if< T >.
Definition at line 109 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::num_available(), and sc_core::sc_fifo< T >::read().
nb_write()
template<class T > virtual bool sc_core::sc_fifo< T >::nb_write (const T & t) inline virtual
Implements sc_core::sc_fifo_nonblocking_out_if< T >.
Definition at line 131 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::num_free(), and sc_core::sc_fifo< T >::write().
num_available()
template<class T > virtual int sc_core::sc_fifo< T >::num_available () const inline virtual
Implements sc_core::sc_fifo_in_if< T >.
Definition at line 158 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_num_available.
Referenced by sc_core::sc_fifo< T >::nb_read(), and sc_core::sc_fifo< T >::read().
num_free()
template<class T > virtual int sc_core::sc_fifo< T >::num_free () const inline virtual
Implements sc_core::sc_fifo_out_if< T >.
Definition at line 159 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_num_free.
Referenced by sc_core::sc_fifo< T >::nb_write(), and sc_core::sc_fifo< T >::write().
operator T()
template<class T > sc_core::sc_fifo< T >::operator T () inline
Definition at line 118 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::read().
operator=() [1/2]
template<class T > sc_fifo<T>& sc_core::sc_fifo< T >::operator= (const T & t) inline
Definition at line 141 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::write().
operator=() [2/2]
template<class T > sc_fifo& sc_core::sc_fifo< T >::operator= (const sc_fifo< T > &) inline private
Definition at line 201 of file sc_fifo.hh.
print()
template<class T > virtual void sc_core::sc_fifo< T >::print (std::ostream & os = std::cout) const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 162 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_entries, and X86ISA::os.
read() [1/2]
template<class T > virtual void sc_core::sc_fifo< T >::read (T & t) inline virtual
Implements sc_core::sc_fifo_blocking_in_if< T >.
Definition at line 91 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_dataWriteEvent, sc_core::sc_fifo< T >::_entries, sc_core::sc_fifo< T >::_num_available, sc_core::sc_fifo< T >::_readsHappened, sc_core::sc_fifo< T >::num_available(), sc_core::sc_prim_channel::request_update(), and sc_core::wait().
read() [2/2]
template<class T > virtual T sc_core::sc_fifo< T >::read () inline virtual
Implements sc_core::sc_fifo_blocking_in_if< T >.
Definition at line 102 of file sc_fifo.hh.
References ArmISA::t.
Referenced by sc_core::sc_fifo< T >::nb_read(), and sc_core::sc_fifo< T >::operator T().
register_port()
template<class T > virtual void sc_core::sc_fifo< T >::register_port (sc_port_base & port, const char * iface_type_name) inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 71 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_reader, sc_core::sc_fifo< T >::_writer, sc_core::sc_object::name(), sc_core::SC_ID_BIND_IF_TO_PORT_, sc_core::SC_ID_MORE_THAN_ONE_FIFO_READER_, sc_core::SC_ID_MORE_THAN_ONE_FIFO_WRITER_, and SC_REPORT_ERROR.
update()
template<class T > virtual void sc_core::sc_fifo< T >::update () inline protected virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 183 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_dataReadEvent, sc_core::sc_fifo< T >::_dataWriteEvent, sc_core::sc_fifo< T >::_entries, sc_core::sc_fifo< T >::_num_available, sc_core::sc_fifo< T >::_num_free, sc_core::sc_fifo< T >::_readsHappened, sc_core::sc_fifo< T >::_size, sc_core::sc_fifo< T >::_writesHappened, sc_core::sc_event::notify(), and sc_core::SC_ZERO_TIME.
write()
template<class T > virtual void sc_core::sc_fifo< T >::write (const T & t) inline virtual
Implements sc_core::sc_fifo_blocking_out_if< T >.
Definition at line 121 of file sc_fifo.hh.
References sc_core::sc_fifo< T >::_dataReadEvent, sc_core::sc_fifo< T >::_entries, sc_core::sc_fifo< T >::_num_free, sc_core::sc_fifo< T >::_writesHappened, sc_core::sc_fifo< T >::num_free(), sc_core::sc_prim_channel::request_update(), and sc_core::wait().
Referenced by sc_core::sc_fifo< T >::nb_write(), and sc_core::sc_fifo< T >::operator=().
Member Data Documentation
_dataReadEvent
template<class T > sc_gem5::InternalScEvent sc_core::sc_fifo< T >::_dataReadEvent private
Definition at line 203 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::data_read_event(), sc_core::sc_fifo< T >::update(), and sc_core::sc_fifo< T >::write().
_dataWriteEvent
template<class T > sc_gem5::InternalScEvent sc_core::sc_fifo< T >::_dataWriteEvent private
Definition at line 204 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::data_written_event(), sc_core::sc_fifo< T >::read(), and sc_core::sc_fifo< T >::update().
_entries
template<class T > std::list<T> sc_core::sc_fifo< T >::_entries mutable private
Definition at line 212 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::dump(), sc_core::sc_fifo< T >::print(), sc_core::sc_fifo< T >::read(), sc_core::sc_fifo< T >::update(), and sc_core::sc_fifo< T >::write().
_num_available
template<class T > int sc_core::sc_fifo< T >::_num_available private
Definition at line 211 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::num_available(), sc_core::sc_fifo< T >::read(), and sc_core::sc_fifo< T >::update().
_num_free
template<class T > int sc_core::sc_fifo< T >::_num_free private
Definition at line 210 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::num_free(), sc_core::sc_fifo< T >::update(), and sc_core::sc_fifo< T >::write().
_reader
template<class T > sc_port_base* sc_core::sc_fifo< T >::_reader private
Definition at line 206 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::register_port().
_readsHappened
template<class T > bool sc_core::sc_fifo< T >::_readsHappened private
Definition at line 213 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::read(), and sc_core::sc_fifo< T >::update().
_size
template<class T > int sc_core::sc_fifo< T >::_size private
Definition at line 209 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::update().
_writer
template<class T > sc_port_base* sc_core::sc_fifo< T >::_writer private
Definition at line 207 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::register_port().
_writesHappened
template<class T > bool sc_core::sc_fifo< T >::_writesHappened private
Definition at line 214 of file sc_fifo.hh.
Referenced by sc_core::sc_fifo< T >::update(), and sc_core::sc_fifo< T >::write().
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_fifo.hh