gem5: sc_gem5::ScSignalBaseT< T, WRITER_POLICY > Class Template Reference
sc_gem5::ScSignalBaseT< T, WRITER_POLICY > Class Template Reference
#include <sc_signal.hh>
Public Member Functions
ScSignalBaseT (const char *_name)
ScSignalBaseT (const char *_name, const T &initial_value)
virtual ~ScSignalBaseT ()
virtual void register_port (sc_core::sc_port_base &port, const char *iface_type_name)
virtual const T & read () const
operator const T & () const
virtual void write (const T &t)
virtual const sc_core::sc_event & default_event () const
virtual const sc_core::sc_event & value_changed_event () const
virtual void print (std::ostream &os=std::cout) const
virtual void dump (std::ostream &os=std::cout) const
virtual bool event () const
virtual sc_core::sc_writer_policy get_writer_policy () const
Public Member Functions inherited from sc_gem5::ScSignalBase
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_core::sc_interface
virtual ~sc_interface ()
Protected Attributes
T m_cur_val
T m_new_val
WriteChecker< WRITER_POLICY > _checker
Protected Attributes inherited from sc_gem5::ScSignalBase
InternalScEvent _valueChangedEvent
uint64_t _changeStamp
sc_core::sc_port_base * _gem5WriterPort
Additional Inherited Members
Protected Member Functions inherited from sc_gem5::ScSignalBasePicker< T >
ScSignalBasePicker (const char *_name)
Protected Member Functions inherited from sc_gem5::ScSignalBase
ScSignalBase (const char *_name)
virtual ~ScSignalBase ()
const sc_core::sc_event & defaultEvent () const
const sc_core::sc_event & valueChangedEvent () const
bool event () const
void _signalChange ()
Protected Member Functions inherited from sc_core::sc_prim_channel
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
virtual void update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from sc_core::sc_signal_inout_if< T >
sc_signal_inout_if ()
Protected Member Functions inherited from sc_core::sc_signal_in_if< T >
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_signal_write_if< T >
sc_signal_write_if ()
Detailed Description
template<class T, sc_core::sc_writer_policy WRITER_POLICY>
class sc_gem5::ScSignalBaseT< T, WRITER_POLICY >
Definition at line 162 of file sc_signal.hh.
Constructor & Destructor Documentation
ScSignalBaseT() [1/2]
template<class T, sc_core::sc_writer_policy WRITER_POLICY> sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::ScSignalBaseT (const char * _name) inline
Definition at line 166 of file sc_signal.hh.
ScSignalBaseT() [2/2]
template<class T, sc_core::sc_writer_policy WRITER_POLICY> sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::ScSignalBaseT (const char * _name, const T & initial_value) inline
Definition at line 170 of file sc_signal.hh.
~ScSignalBaseT()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::~ScSignalBaseT () inline virtual
Definition at line 174 of file sc_signal.hh.
Member Function Documentation
default_event()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual const sc_core::sc_event& sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::default_event () const inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 205 of file sc_signal.hh.
dump()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual void sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::dump (std::ostream & os = std::cout) const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 218 of file sc_signal.hh.
event()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual bool sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::event () const inline virtual
Implements sc_core::sc_signal_in_if< T >.
Definition at line 225 of file sc_signal.hh.
get_writer_policy()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual sc_core::sc_writer_policy sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::get_writer_policy () const inline virtual
Implements sc_gem5::ScSignalBase.
Definition at line 228 of file sc_signal.hh.
operator const T &()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::operator const T & () const inline
Definition at line 188 of file sc_signal.hh.
print()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual void sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::print (std::ostream & os = std::cout) const inline virtual
Reimplemented from sc_core::sc_object.
Definition at line 216 of file sc_signal.hh.
read()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual const T& sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::read () const inline virtual
Implements sc_core::sc_signal_in_if< T >.
Definition at line 187 of file sc_signal.hh.
Referenced by sc_core::sc_in< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_in< sc_dt::sc_bigint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_int< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_uint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_biguint< W > >::end_of_elaboration(), sc_core::sc_inout< sc_dt::sc_bigint< W > >::end_of_elaboration(), sc_core::sc_signal_resolved::operator=(), sc_core::sc_buffer< T, WRITER_POLICY >::operator=(), sc_core::sc_signal< sc_dt::sc_logic, SC_MANY_WRITERS >::operator=(), sc_core::sc_signal< bool, WRITER_POLICY >::operator=(), and sc_core::sc_signal< sc_dt::sc_logic, WRITER_POLICY >::operator=().
register_port()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual void sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::register_port (sc_core::sc_port_base & port, const char * iface_type_name) inline virtual
Reimplemented from sc_core::sc_interface.
Reimplemented in sc_core::sc_signal_rv< W >, and sc_core::sc_signal_resolved.
Definition at line 177 of file sc_signal.hh.
value_changed_event()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual const sc_core::sc_event& sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::value_changed_event () const inline virtual
Implements sc_core::sc_signal_in_if< T >.
Definition at line 211 of file sc_signal.hh.
write()
template<class T, sc_core::sc_writer_policy WRITER_POLICY> virtual void sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::write (const T & t) inline virtual
Implements sc_core::sc_signal_write_if< T >.
Reimplemented in sc_core::sc_clock, sc_core::sc_signal_rv< W >, sc_core::sc_signal_resolved, and sc_core::sc_buffer< T, WRITER_POLICY >.
Definition at line 191 of file sc_signal.hh.
Member Data Documentation
_checker
template<class T, sc_core::sc_writer_policy WRITER_POLICY> WriteChecker<WRITER_POLICY> sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::_checker protected
Definition at line 240 of file sc_signal.hh.
Referenced by sc_core::sc_buffer< T, WRITER_POLICY >::write().
m_cur_val
template<class T, sc_core::sc_writer_policy WRITER_POLICY> T sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_cur_val protected
Definition at line 237 of file sc_signal.hh.
Referenced by sc_core::sc_buffer< T, WRITER_POLICY >::update().
m_new_val
template<class T, sc_core::sc_writer_policy WRITER_POLICY> T sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val protected
Definition at line 238 of file sc_signal.hh.
Referenced by sc_core::sc_buffer< T, WRITER_POLICY >::update(), sc_core::sc_signal< sc_dt::sc_int< W > >::update(), sc_core::sc_signal< sc_dt::sc_uint< W > >::update(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::update(), sc_core::sc_signal< sc_dt::sc_bigint< W > >::update(), sc_core::sc_buffer< T, WRITER_POLICY >::write(), sc_core::sc_signal< sc_dt::sc_int< W > >::write_part(), sc_core::sc_signal< sc_dt::sc_uint< W > >::write_part(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::write_part().
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_signal.hh