gem5: DefaultDecode< Impl > Class Template Reference
DefaultDecode< Impl > Class Template Reference
DefaultDecode class handles both single threaded and SMT decode.
#include <decode.hh>
Classes
struct Stalls
Source of possible stalls.
Public Types
enum DecodeStatus { Active, Inactive }
Overall decode stage status.
enum ThreadStatus {
Running, Idle, StartSquash, Squashing,
Blocked, Unblocking
}
Individual thread status.
Public Member Functions
DefaultDecode (O3CPU *_cpu, DerivO3CPUParams *params)
DefaultDecode constructor.
void startupStage ()
void clearStates (ThreadID tid)
Clear all thread-specific states.
void resetStage ()
std::string name () const
Returns the name of decode.
void regStats ()
Registers statistics.
void setTimeBuffer (TimeBuffer< TimeStruct > *tb_ptr)
Sets the main backwards communication time buffer pointer.
void setDecodeQueue (TimeBuffer< DecodeStruct > *dq_ptr)
Sets pointer to time buffer used to communicate to the next stage.
void setFetchQueue (TimeBuffer< FetchStruct > *fq_ptr)
Sets pointer to time buffer coming from fetch.
void setActiveThreads (std::list< ThreadID > *at_ptr)
Sets pointer to list of active threads.
void drainSanityCheck () const
Perform sanity checks after a drain.
bool isDrained () const
Has the stage drained?
void takeOverFrom ()
Takes over from another CPU's thread.
void tick ()
Ticks decode, processing all input signals and decoding as many instructions as possible.
void decode (bool &status_change, ThreadID tid)
Determines what to do based on decode's current status.
void decodeInsts (ThreadID tid)
Processes instructions from fetch and passes them on to rename.
unsigned squash (ThreadID tid)
Squashes due to commit signalling a squash.
Private Types
typedef Impl::O3CPU O3CPU
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::CPUPol CPUPol
typedef CPUPol::FetchStruct FetchStruct
typedef CPUPol::DecodeStruct DecodeStruct
typedef CPUPol::TimeStruct TimeStruct
Private Member Functions
void skidInsert (ThreadID tid)
Inserts a thread's instructions into the skid buffer, to be decoded once decode unblocks.
bool skidsEmpty ()
Returns if all of the skid buffers are empty.
void updateStatus ()
Updates overall decode status based on all of the threads' statuses.
void sortInsts ()
Separates instructions from fetch into individual lists of instructions sorted by thread.
void readStallSignals (ThreadID tid)
Reads all stall signals from the backwards communication timebuffer.
bool checkSignalsAndUpdate (ThreadID tid)
Checks all input signals and updates decode's status appropriately.
bool checkStall (ThreadID tid) const
Checks all stall signals, and returns if any are true.
bool fetchInstsValid ()
Returns if there any instructions from fetch on this cycle.
bool block (ThreadID tid)
Switches decode to blocking, and signals back that decode has become blocked.
bool unblock (ThreadID tid)
Switches decode to unblocking if the skid buffer is empty, and signals back that decode has unblocked.
void squash (const DynInstPtr &inst, ThreadID tid)
Squashes if there is a PC-relative branch that was predicted incorrectly.
Private Attributes
DecodeStatus _status
Decode status.
ThreadStatus decodeStatus [Impl::MaxThreads]
Per-thread status.
O3CPU * cpu
CPU interface.
TimeBuffer< TimeStruct > * timeBuffer
Time buffer interface.
TimeBuffer< TimeStruct >::wire fromRename
Wire to get rename's output from backwards time buffer.
TimeBuffer< TimeStruct >::wire fromIEW
Wire to get iew's information from backwards time buffer.
TimeBuffer< TimeStruct >::wire fromCommit
Wire to get commit's information from backwards time buffer.
TimeBuffer< TimeStruct >::wire toFetch
Wire to write information heading to previous stages.
TimeBuffer< DecodeStruct > * decodeQueue
Decode instruction queue.
TimeBuffer< DecodeStruct >::wire toRename
Wire used to write any information heading to rename.
TimeBuffer< FetchStruct > * fetchQueue
Fetch instruction queue interface.
TimeBuffer< FetchStruct >::wire fromFetch
Wire to get fetch's output from fetch queue.
std::queue< DynInstPtr > insts [Impl::MaxThreads]
Queue of all instructions coming from fetch this cycle.
std::queue< DynInstPtr > skidBuffer [Impl::MaxThreads]
Skid buffer between fetch and decode.
bool wroteToTimeBuffer
Variable that tracks if decode has written to the time buffer this cycle.
Stalls stalls [Impl::MaxThreads]
Tracks which stages are telling decode to stall.
Cycles renameToDecodeDelay
Rename to decode delay.
Cycles iewToDecodeDelay
IEW to decode delay.
Cycles commitToDecodeDelay
Commit to decode delay.
Cycles fetchToDecodeDelay
Fetch to decode delay.
unsigned decodeWidth
The width of decode, in instructions.
unsigned toRenameIndex
Index of instructions being sent to rename.
ThreadID numThreads
number of Active Threads
std::list< ThreadID > * activeThreads
List of active thread ids.
unsigned skidBufferMax
Maximum size of the skid buffer.
Addr bdelayDoneSeqNum [Impl::MaxThreads]
SeqNum of Squashing Branch Delay Instruction (used for MIPS)
DynInstPtr squashInst [Impl::MaxThreads]
Instruction used for squashing branch (used for MIPS)
bool squashAfterDelaySlot [Impl::MaxThreads]
Tells when their is a pending delay slot inst.
Stats::Scalar decodeIdleCycles
Stat for total number of idle cycles.
Stats::Scalar decodeBlockedCycles
Stat for total number of blocked cycles.
Stats::Scalar decodeRunCycles
Stat for total number of normal running cycles.
Stats::Scalar decodeUnblockCycles
Stat for total number of unblocking cycles.
Stats::Scalar decodeSquashCycles
Stat for total number of squashing cycles.
Stats::Scalar decodeBranchResolved
Stat for number of times a branch is resolved at decode.
Stats::Scalar decodeBranchMispred
Stat for number of times a branch mispredict is detected.
Stats::Scalar decodeControlMispred
Stat for number of times decode detected a non-control instruction incorrectly predicted as a branch.
Stats::Scalar decodeDecodedInsts
Stat for total number of decoded instructions.
Stats::Scalar decodeSquashedInsts
Stat for total number of squashed instructions.
Detailed Description
template<class Impl>
class DefaultDecode< Impl >
DefaultDecode class handles both single threaded and SMT decode.
Its width is specified by the parameters; each cycles it tries to decode that many instructions. Because instructions are actually decoded when the StaticInst is created, this stage does not do much other than check any PC-relative branches.
Definition at line 61 of file decode.hh.
Member Typedef Documentation
CPUPol
template<class Impl > typedef Impl::CPUPol DefaultDecode< Impl >::CPUPol private
Definition at line 67 of file decode.hh.
DecodeStruct
template<class Impl > typedef CPUPol::DecodeStruct DefaultDecode< Impl >::DecodeStruct private
Definition at line 71 of file decode.hh.
DynInstPtr
template<class Impl > typedef Impl::DynInstPtr DefaultDecode< Impl >::DynInstPtr private
Definition at line 66 of file decode.hh.
FetchStruct
template<class Impl > typedef CPUPol::FetchStruct DefaultDecode< Impl >::FetchStruct private
Definition at line 70 of file decode.hh.
O3CPU
template<class Impl > typedef Impl::O3CPU DefaultDecode< Impl >::O3CPU private
Definition at line 65 of file decode.hh.
TimeStruct
template<class Impl > typedef CPUPol::TimeStruct DefaultDecode< Impl >::TimeStruct private
Definition at line 72 of file decode.hh.
Member Enumeration Documentation
DecodeStatus
template<class Impl > enum DefaultDecode::DecodeStatus
Overall decode stage status.
Used to determine if the CPU can deschedule itself due to a lack of activity.
Enumerator
Active
Inactive
Definition at line 78 of file decode.hh.
ThreadStatus
template<class Impl > enum DefaultDecode::ThreadStatus
Individual thread status.
Enumerator
Running
Idle
StartSquash
Squashing
Blocked
Unblocking
Definition at line 84 of file decode.hh.
Constructor & Destructor Documentation
DefaultDecode()
template<class Impl > DefaultDecode< Impl >::DefaultDecode (O3CPU * _cpu, DerivO3CPUParams * params)
DefaultDecode constructor.
Definition at line 62 of file decode_impl.hh.
References DefaultDecode< Impl >::bdelayDoneSeqNum, DefaultDecode< Impl >::decodeStatus, DefaultDecode< Impl >::decodeWidth, fatal, DefaultDecode< Impl >::fetchToDecodeDelay, DefaultDecode< Impl >::Idle, DefaultDecode< Impl >::skidBufferMax, DefaultDecode< Impl >::squashAfterDelaySlot, DefaultDecode< Impl >::squashInst, and DefaultDecode< Impl >::stalls.
Member Function Documentation
block()
template<class Impl > bool DefaultDecode< Impl >::block (ThreadID tid) private
Switches decode to blocking, and signals back that decode has become blocked.
Returns
Returns true if there is a status change.
Definition at line 257 of file decode_impl.hh.
References DefaultDecode< Impl >::Blocked, DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::skidInsert(), DefaultDecode< Impl >::toFetch, and DefaultDecode< Impl >::wroteToTimeBuffer.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::takeOverFrom().
checkSignalsAndUpdate()
template<class Impl > bool DefaultDecode< Impl >::checkSignalsAndUpdate (ThreadID tid) private
Checks all input signals and updates decode's status appropriately.
Definition at line 509 of file decode_impl.hh.
References DefaultDecode< Impl >::block(), DefaultDecode< Impl >::Blocked, DefaultDecode< Impl >::checkStall(), DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::fromCommit, DefaultDecode< Impl >::readStallSignals(), DefaultDecode< Impl >::Running, DefaultDecode< Impl >::squash(), DefaultDecode< Impl >::Squashing, DefaultDecode< Impl >::unblock(), and DefaultDecode< Impl >::Unblocking.
Referenced by DefaultDecode< Impl >::takeOverFrom(), and DefaultDecode< Impl >::tick().
checkStall()
template<class Impl > bool DefaultDecode< Impl >::checkStall (ThreadID tid) const private
Checks all stall signals, and returns if any are true.
Definition at line 236 of file decode_impl.hh.
References DPRINTF, and DefaultDecode< Impl >::stalls.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), and DefaultDecode< Impl >::takeOverFrom().
clearStates()
template<class Impl > void DefaultDecode< Impl >::clearStates (ThreadID tid)
Clear all thread-specific states.
Definition at line 96 of file decode_impl.hh.
References DefaultDecode< Impl >::decodeStatus, DefaultDecode< Impl >::Idle, DefaultDecode< Impl >::Stalls::rename, and DefaultDecode< Impl >::stalls.
decode()
template<class Impl > void DefaultDecode< Impl >::decode (bool & status_change, ThreadID tid)
Determines what to do based on decode's current status.
Parameters
status_change decode() sets this variable if there was a status change (ie switching from from blocking to unblocking).
tid Thread id to decode instructions from.
Definition at line 602 of file decode_impl.hh.
References DefaultDecode< Impl >::Blocked, DefaultDecode< Impl >::decodeBlockedCycles, DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::decodeSquashCycles, DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::fetchInstsValid(), DefaultDecode< Impl >::Idle, DefaultDecode< Impl >::Running, DefaultDecode< Impl >::skidInsert(), DefaultDecode< Impl >::skidsEmpty(), DefaultDecode< Impl >::Squashing, DefaultDecode< Impl >::unblock(), and DefaultDecode< Impl >::Unblocking.
Referenced by DefaultDecode< Impl >::takeOverFrom(), and DefaultDecode< Impl >::tick().
decodeInsts()
template<class Impl > void DefaultDecode< Impl >::decodeInsts (ThreadID tid)
Processes instructions from fetch and passes them on to rename.
Decoding of instructions actually happens when they are created in fetch, so this function mostly checks if PC-relative branches are correct.
Definition at line 647 of file decode_impl.hh.
References DefaultDecode< Impl >::block(), curTick(), DefaultDecode< Impl >::decodeBranchMispred, DefaultDecode< Impl >::decodeBranchResolved, DefaultDecode< Impl >::decodeControlMispred, DefaultDecode< Impl >::decodeDecodedInsts, DefaultDecode< Impl >::decodeIdleCycles, DefaultDecode< Impl >::decodeRunCycles, DefaultDecode< Impl >::decodeSquashedInsts, DefaultDecode< Impl >::decodeStatus, DefaultDecode< Impl >::decodeUnblockCycles, DefaultDecode< Impl >::decodeWidth, DPRINTF, DTRACE, DefaultDecode< Impl >::insts, panic, DefaultDecode< Impl >::Running, TimeBuffer< T >::size, DefaultDecode< Impl >::skidBuffer, DefaultDecode< Impl >::squash(), DefaultDecode< Impl >::toRename, DefaultDecode< Impl >::toRenameIndex, DefaultDecode< Impl >::Unblocking, and DefaultDecode< Impl >::wroteToTimeBuffer.
Referenced by DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::takeOverFrom().
drainSanityCheck()
template<class Impl > void DefaultDecode< Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 214 of file decode_impl.hh.
References DefaultDecode< Impl >::insts, DefaultDecode< Impl >::numThreads, and DefaultDecode< Impl >::skidBuffer.
fetchInstsValid()
template<class Impl > bool DefaultDecode< Impl >::fetchInstsValid () inline private
Returns if there any instructions from fetch on this cycle.
Definition at line 250 of file decode_impl.hh.
References DefaultDecode< Impl >::fromFetch, and TimeBuffer< T >::size.
Referenced by DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::takeOverFrom().
isDrained()
template<class Impl > bool DefaultDecode< Impl >::isDrained () const
Has the stage drained?
Definition at line 224 of file decode_impl.hh.
References DefaultDecode< Impl >::decodeStatus, DefaultDecode< Impl >::Idle, DefaultDecode< Impl >::insts, DefaultDecode< Impl >::numThreads, DefaultDecode< Impl >::Running, and DefaultDecode< Impl >::skidBuffer.
name()
template<class Impl > std::string DefaultDecode< Impl >::name () const
Returns the name of decode.
Definition at line 118 of file decode_impl.hh.
References DefaultDecode< Impl >::cpu.
Referenced by DefaultDecode< Impl >::regStats().
readStallSignals()
template<class Impl > void DefaultDecode< Impl >::readStallSignals (ThreadID tid) private
Reads all stall signals from the backwards communication timebuffer.
Definition at line 495 of file decode_impl.hh.
References DefaultDecode< Impl >::fromRename, DefaultDecode< Impl >::Stalls::rename, and DefaultDecode< Impl >::stalls.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), and DefaultDecode< Impl >::takeOverFrom().
regStats()
template<class Impl > void DefaultDecode< Impl >::regStats ()
Registers statistics.
Definition at line 125 of file decode_impl.hh.
References DefaultDecode< Impl >::decodeBlockedCycles, DefaultDecode< Impl >::decodeBranchMispred, DefaultDecode< Impl >::decodeBranchResolved, DefaultDecode< Impl >::decodeControlMispred, DefaultDecode< Impl >::decodeDecodedInsts, DefaultDecode< Impl >::decodeIdleCycles, DefaultDecode< Impl >::decodeRunCycles, DefaultDecode< Impl >::decodeSquashCycles, DefaultDecode< Impl >::decodeSquashedInsts, DefaultDecode< Impl >::decodeUnblockCycles, Stats::DataWrap< Derived, InfoProxyType >::desc(), DefaultDecode< Impl >::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), and Stats::DataWrap< Derived, InfoProxyType >::prereq().
resetStage()
template<class Impl > void DefaultDecode< Impl >::resetStage ()
Definition at line 104 of file decode_impl.hh.
References DefaultDecode< Impl >::_status, DefaultDecode< Impl >::decodeStatus, DefaultDecode< Impl >::Idle, DefaultDecode< Impl >::Inactive, DefaultDecode< Impl >::numThreads, DefaultDecode< Impl >::Stalls::rename, and DefaultDecode< Impl >::stalls.
Referenced by DefaultDecode< Impl >::startupStage(), and DefaultDecode< Impl >::takeOverFrom().
setActiveThreads()
template<class Impl > void DefaultDecode< Impl >::setActiveThreads (std::list< ThreadID > * at_ptr)
Sets pointer to list of active threads.
Definition at line 207 of file decode_impl.hh.
References DefaultDecode< Impl >::activeThreads.
setDecodeQueue()
template<class Impl > void DefaultDecode< Impl >::setDecodeQueue (TimeBuffer< DecodeStruct > * dq_ptr)
Sets pointer to time buffer used to communicate to the next stage.
Definition at line 187 of file decode_impl.hh.
References DefaultDecode< Impl >::decodeQueue, TimeBuffer< T >::getWire(), and DefaultDecode< Impl >::toRename.
setFetchQueue()
template<class Impl > void DefaultDecode< Impl >::setFetchQueue (TimeBuffer< FetchStruct > * fq_ptr)
Sets pointer to time buffer coming from fetch.
Definition at line 197 of file decode_impl.hh.
References DefaultDecode< Impl >::fetchQueue, DefaultDecode< Impl >::fetchToDecodeDelay, DefaultDecode< Impl >::fromFetch, and TimeBuffer< T >::getWire().
setTimeBuffer()
template<class Impl > void DefaultDecode< Impl >::setTimeBuffer (TimeBuffer< TimeStruct > * tb_ptr)
Sets the main backwards communication time buffer pointer.
Definition at line 172 of file decode_impl.hh.
References DefaultDecode< Impl >::commitToDecodeDelay, DefaultDecode< Impl >::fromCommit, DefaultDecode< Impl >::fromIEW, DefaultDecode< Impl >::fromRename, TimeBuffer< T >::getWire(), DefaultDecode< Impl >::iewToDecodeDelay, DefaultDecode< Impl >::renameToDecodeDelay, DefaultDecode< Impl >::timeBuffer, and DefaultDecode< Impl >::toFetch.
skidInsert()
template<class Impl > void DefaultDecode< Impl >::skidInsert (ThreadID tid) private
Inserts a thread's instructions into the skid buffer, to be decoded once decode unblocks.
Definition at line 406 of file decode_impl.hh.
References DPRINTF, DefaultDecode< Impl >::insts, DefaultDecode< Impl >::skidBuffer, and DefaultDecode< Impl >::skidBufferMax.
Referenced by DefaultDecode< Impl >::block(), DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::takeOverFrom().
skidsEmpty()
template<class Impl > bool DefaultDecode< Impl >::skidsEmpty () private
Returns if all of the skid buffers are empty.
Definition at line 430 of file decode_impl.hh.
References DefaultDecode< Impl >::activeThreads, and DefaultDecode< Impl >::skidBuffer.
Referenced by DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::takeOverFrom().
sortInsts()
template<class Impl > void DefaultDecode< Impl >::sortInsts () private
Separates instructions from fetch into individual lists of instructions sorted by thread.
Definition at line 485 of file decode_impl.hh.
References DefaultDecode< Impl >::fromFetch, ArmISA::i, DefaultDecode< Impl >::insts, and TimeBuffer< T >::size.
Referenced by DefaultDecode< Impl >::takeOverFrom(), and DefaultDecode< Impl >::tick().
squash() [1/2]
template<class Impl > void DefaultDecode< Impl >::squash (const DynInstPtr & inst, ThreadID tid) private
Squashes if there is a PC-relative branch that was predicted incorrectly.
Sends squash information back to fetch.
Definition at line 306 of file decode_impl.hh.
References DefaultDecode< Impl >::Blocked, DefaultDecode< Impl >::cpu, DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::fromFetch, ArmISA::i, DefaultDecode< Impl >::insts, TimeBuffer< T >::size, DefaultDecode< Impl >::skidBuffer, DefaultDecode< Impl >::Squashing, DefaultDecode< Impl >::toFetch, and DefaultDecode< Impl >::Unblocking.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::takeOverFrom().
squash() [2/2]
template<class Impl > unsigned DefaultDecode< Impl >::squash (ThreadID tid)
Squashes due to commit signalling a squash.
Changes status to squashing and clears block/unblock signals as needed.
Definition at line 358 of file decode_impl.hh.
References DefaultDecode< Impl >::Blocked, DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::fromFetch, FullSystem, ArmISA::i, DefaultDecode< Impl >::insts, TimeBuffer< T >::size, DefaultDecode< Impl >::skidBuffer, DefaultDecode< Impl >::Squashing, DefaultDecode< Impl >::toFetch, and DefaultDecode< Impl >::Unblocking.
startupStage()
template<class Impl > void DefaultDecode< Impl >::startupStage ()
Definition at line 89 of file decode_impl.hh.
References DefaultDecode< Impl >::resetStage().
takeOverFrom()
template<class Impl > void DefaultDecode< Impl >::takeOverFrom () inline
Takes over from another CPU's thread.
Definition at line 136 of file decode.hh.
References DefaultDecode< Impl >::block(), DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::checkStall(), DefaultDecode< Impl >::decode(), DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::fetchInstsValid(), DefaultDecode< Impl >::readStallSignals(), DefaultDecode< Impl >::resetStage(), DefaultDecode< Impl >::skidInsert(), DefaultDecode< Impl >::skidsEmpty(), DefaultDecode< Impl >::sortInsts(), DefaultDecode< Impl >::squash(), DefaultDecode< Impl >::tick(), DefaultDecode< Impl >::unblock(), and DefaultDecode< Impl >::updateStatus().
tick()
template<class Impl > void DefaultDecode< Impl >::tick ()
Ticks decode, processing all input signals and decoding as many instructions as possible.
Definition at line 566 of file decode_impl.hh.
References DefaultDecode< Impl >::activeThreads, DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::cpu, DefaultDecode< Impl >::decode(), DPRINTF, DefaultDecode< Impl >::sortInsts(), DefaultDecode< Impl >::toRenameIndex, DefaultDecode< Impl >::updateStatus(), and DefaultDecode< Impl >::wroteToTimeBuffer.
Referenced by DefaultDecode< Impl >::takeOverFrom().
unblock()
template<class Impl > bool DefaultDecode< Impl >::unblock (ThreadID tid) private
Switches decode to unblocking if the skid buffer is empty, and signals back that decode has unblocked.
Returns
Returns true if there is a status change.
Definition at line 287 of file decode_impl.hh.
References DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::Running, DefaultDecode< Impl >::skidBuffer, DefaultDecode< Impl >::toFetch, and DefaultDecode< Impl >::wroteToTimeBuffer.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::takeOverFrom().
updateStatus()
template<class Impl > void DefaultDecode< Impl >::updateStatus () private
Updates overall decode status based on all of the threads' statuses.
Definition at line 446 of file decode_impl.hh.
References DefaultDecode< Impl >::_status, DefaultDecode< Impl >::Active, DefaultDecode< Impl >::activeThreads, DefaultDecode< Impl >::cpu, DefaultDecode< Impl >::decodeStatus, DPRINTF, DefaultDecode< Impl >::Inactive, and DefaultDecode< Impl >::Unblocking.
Referenced by DefaultDecode< Impl >::takeOverFrom(), and DefaultDecode< Impl >::tick().
Member Data Documentation
_status
template<class Impl > DecodeStatus DefaultDecode< Impl >::_status private
Decode status.
Definition at line 95 of file decode.hh.
Referenced by DefaultDecode< Impl >::resetStage(), and DefaultDecode< Impl >::updateStatus().
activeThreads
template<class Impl > std::list<ThreadID>* DefaultDecode< Impl >::activeThreads private
List of active thread ids.
Definition at line 283 of file decode.hh.
Referenced by DefaultDecode< Impl >::setActiveThreads(), DefaultDecode< Impl >::skidsEmpty(), DefaultDecode< Impl >::tick(), and DefaultDecode< Impl >::updateStatus().
bdelayDoneSeqNum
template<class Impl > Addr DefaultDecode< Impl >::bdelayDoneSeqNum[Impl::MaxThreads] private
SeqNum of Squashing Branch Delay Instruction (used for MIPS)
Definition at line 289 of file decode.hh.
Referenced by DefaultDecode< Impl >::DefaultDecode().
commitToDecodeDelay
template<class Impl > Cycles DefaultDecode< Impl >::commitToDecodeDelay private
Commit to decode delay.
Definition at line 268 of file decode.hh.
Referenced by DefaultDecode< Impl >::setTimeBuffer().
cpu
template<class Impl > O3CPU* DefaultDecode< Impl >::cpu private
CPU interface.
Definition at line 212 of file decode.hh.
Referenced by DefaultDecode< Impl >::name(), DefaultDecode< Impl >::squash(), DefaultDecode< Impl >::tick(), and DefaultDecode< Impl >::updateStatus().
decodeBlockedCycles
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeBlockedCycles private
Stat for total number of blocked cycles.
Definition at line 304 of file decode.hh.
Referenced by DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::regStats().
decodeBranchMispred
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeBranchMispred private
Stat for number of times a branch mispredict is detected.
Definition at line 314 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeBranchResolved
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeBranchResolved private
Stat for number of times a branch is resolved at decode.
Definition at line 312 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeControlMispred
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeControlMispred private
Stat for number of times decode detected a non-control instruction incorrectly predicted as a branch.
Definition at line 318 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeDecodedInsts
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeDecodedInsts private
Stat for total number of decoded instructions.
Definition at line 320 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeIdleCycles
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeIdleCycles private
Stat for total number of idle cycles.
Definition at line 302 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeQueue
template<class Impl > TimeBuffer<DecodeStruct>* DefaultDecode< Impl >::decodeQueue private
Decode instruction queue.
Definition at line 231 of file decode.hh.
Referenced by DefaultDecode< Impl >::setDecodeQueue().
decodeRunCycles
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeRunCycles private
Stat for total number of normal running cycles.
Definition at line 306 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeSquashCycles
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeSquashCycles private
Stat for total number of squashing cycles.
Definition at line 310 of file decode.hh.
Referenced by DefaultDecode< Impl >::decode(), and DefaultDecode< Impl >::regStats().
decodeSquashedInsts
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeSquashedInsts private
Stat for total number of squashed instructions.
Definition at line 322 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeStatus
template<class Impl > ThreadStatus DefaultDecode< Impl >::decodeStatus[Impl::MaxThreads] private
Per-thread status.
Definition at line 98 of file decode.hh.
Referenced by DefaultDecode< Impl >::block(), DefaultDecode< Impl >::checkSignalsAndUpdate(), DefaultDecode< Impl >::clearStates(), DefaultDecode< Impl >::decode(), DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::DefaultDecode(), DefaultDecode< Impl >::isDrained(), DefaultDecode< Impl >::resetStage(), DefaultDecode< Impl >::squash(), DefaultDecode< Impl >::unblock(), and DefaultDecode< Impl >::updateStatus().
decodeUnblockCycles
template<class Impl > Stats::Scalar DefaultDecode< Impl >::decodeUnblockCycles private
Stat for total number of unblocking cycles.
Definition at line 308 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::regStats().
decodeWidth
template<class Impl > unsigned DefaultDecode< Impl >::decodeWidth private
The width of decode, in instructions.
Definition at line 274 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::DefaultDecode().
fetchQueue
template<class Impl > TimeBuffer<FetchStruct>* DefaultDecode< Impl >::fetchQueue private
Fetch instruction queue interface.
Definition at line 237 of file decode.hh.
Referenced by DefaultDecode< Impl >::setFetchQueue().
fetchToDecodeDelay
template<class Impl > Cycles DefaultDecode< Impl >::fetchToDecodeDelay private
Fetch to decode delay.
Definition at line 271 of file decode.hh.
Referenced by DefaultDecode< Impl >::DefaultDecode(), and DefaultDecode< Impl >::setFetchQueue().
fromCommit
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultDecode< Impl >::fromCommit private
Wire to get commit's information from backwards time buffer.
Definition at line 224 of file decode.hh.
Referenced by DefaultDecode< Impl >::checkSignalsAndUpdate(), and DefaultDecode< Impl >::setTimeBuffer().
fromFetch
template<class Impl > TimeBuffer<FetchStruct>::wire DefaultDecode< Impl >::fromFetch private
Wire to get fetch's output from fetch queue.
Definition at line 240 of file decode.hh.
Referenced by DefaultDecode< Impl >::fetchInstsValid(), DefaultDecode< Impl >::setFetchQueue(), DefaultDecode< Impl >::sortInsts(), and DefaultDecode< Impl >::squash().
fromIEW
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultDecode< Impl >::fromIEW private
Wire to get iew's information from backwards time buffer.
Definition at line 221 of file decode.hh.
Referenced by DefaultDecode< Impl >::setTimeBuffer().
fromRename
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultDecode< Impl >::fromRename private
Wire to get rename's output from backwards time buffer.
Definition at line 218 of file decode.hh.
Referenced by DefaultDecode< Impl >::readStallSignals(), and DefaultDecode< Impl >::setTimeBuffer().
iewToDecodeDelay
template<class Impl > Cycles DefaultDecode< Impl >::iewToDecodeDelay private
IEW to decode delay.
Definition at line 265 of file decode.hh.
Referenced by DefaultDecode< Impl >::setTimeBuffer().
insts
template<class Impl > std::queue<DynInstPtr> DefaultDecode< Impl >::insts[Impl::MaxThreads] private
Queue of all instructions coming from fetch this cycle.
Definition at line 243 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::drainSanityCheck(), DefaultDecode< Impl >::isDrained(), DefaultDecode< Impl >::skidInsert(), DefaultDecode< Impl >::sortInsts(), and DefaultDecode< Impl >::squash().
numThreads
template<class Impl > ThreadID DefaultDecode< Impl >::numThreads private
number of Active Threads
Definition at line 280 of file decode.hh.
Referenced by DefaultDecode< Impl >::drainSanityCheck(), DefaultDecode< Impl >::isDrained(), and DefaultDecode< Impl >::resetStage().
renameToDecodeDelay
template<class Impl > Cycles DefaultDecode< Impl >::renameToDecodeDelay private
Rename to decode delay.
Definition at line 262 of file decode.hh.
Referenced by DefaultDecode< Impl >::setTimeBuffer().
skidBuffer
template<class Impl > std::queue<DynInstPtr> DefaultDecode< Impl >::skidBuffer[Impl::MaxThreads] private
Skid buffer between fetch and decode.
Definition at line 246 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::drainSanityCheck(), DefaultDecode< Impl >::isDrained(), DefaultDecode< Impl >::skidInsert(), DefaultDecode< Impl >::skidsEmpty(), DefaultDecode< Impl >::squash(), and DefaultDecode< Impl >::unblock().
skidBufferMax
template<class Impl > unsigned DefaultDecode< Impl >::skidBufferMax private
Maximum size of the skid buffer.
Definition at line 286 of file decode.hh.
Referenced by DefaultDecode< Impl >::DefaultDecode(), and DefaultDecode< Impl >::skidInsert().
squashAfterDelaySlot
template<class Impl > bool DefaultDecode< Impl >::squashAfterDelaySlot[Impl::MaxThreads] private
Tells when their is a pending delay slot inst.
to send to rename. If there is, then wait squash after the next instruction (used for MIPS).
Definition at line 298 of file decode.hh.
Referenced by DefaultDecode< Impl >::DefaultDecode().
squashInst
template<class Impl > DynInstPtr DefaultDecode< Impl >::squashInst[Impl::MaxThreads] private
Instruction used for squashing branch (used for MIPS)
Definition at line 292 of file decode.hh.
Referenced by DefaultDecode< Impl >::DefaultDecode().
stalls
template<class Impl > Stalls DefaultDecode< Impl >::stalls[Impl::MaxThreads] private
Tracks which stages are telling decode to stall.
Definition at line 259 of file decode.hh.
Referenced by DefaultDecode< Impl >::checkStall(), DefaultDecode< Impl >::clearStates(), DefaultDecode< Impl >::DefaultDecode(), DefaultDecode< Impl >::readStallSignals(), and DefaultDecode< Impl >::resetStage().
timeBuffer
template<class Impl > TimeBuffer<TimeStruct>* DefaultDecode< Impl >::timeBuffer private
Time buffer interface.
Definition at line 215 of file decode.hh.
Referenced by DefaultDecode< Impl >::setTimeBuffer().
toFetch
template<class Impl > TimeBuffer<TimeStruct>::wire DefaultDecode< Impl >::toFetch private
Wire to write information heading to previous stages.
Definition at line 228 of file decode.hh.
Referenced by DefaultDecode< Impl >::block(), DefaultDecode< Impl >::setTimeBuffer(), DefaultDecode< Impl >::squash(), and DefaultDecode< Impl >::unblock().
toRename
template<class Impl > TimeBuffer<DecodeStruct>::wire DefaultDecode< Impl >::toRename private
Wire used to write any information heading to rename.
Definition at line 234 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::setDecodeQueue().
toRenameIndex
template<class Impl > unsigned DefaultDecode< Impl >::toRenameIndex private
Index of instructions being sent to rename.
Definition at line 277 of file decode.hh.
Referenced by DefaultDecode< Impl >::decodeInsts(), and DefaultDecode< Impl >::tick().
wroteToTimeBuffer
template<class Impl > bool DefaultDecode< Impl >::wroteToTimeBuffer private
Variable that tracks if decode has written to the time buffer this cycle.
Used to tell CPU if there is activity this cycle.
Definition at line 251 of file decode.hh.
Referenced by DefaultDecode< Impl >::block(), DefaultDecode< Impl >::decodeInsts(), DefaultDecode< Impl >::tick(), and DefaultDecode< Impl >::unblock().
The documentation for this class was generated from the following files:
cpu/o3/decode.hh
cpu/o3/decode_impl.hh