gem5: sc_core::sc_signal< sc_dt::sc_uint< W > > Class Reference
sc_core::sc_signal< sc_dt::sc_uint< W > > Class Reference
#include <scx_signal_uint.h>
Public Types
typedef sc_signal< sc_dt::sc_uint< W > > this_type
Public Types inherited from sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >
typedef sc_signal_in_if< sc_dt::sc_uint< W > > this_type
Public Member Functions
sc_signal ()
sc_signal (const char *name_)
virtual ~sc_signal ()
bool base_event () const
const sc_dt::sc_uint< W > & base_read () const
const sc_event & base_value_changed_event () const
void base_write (sc_dt::uint64 value)
virtual const char * kind () const
virtual void update ()
virtual const sc_event & default_event () const
virtual void register_port (sc_port_base &port_, const char *if_typename_)
virtual sc_dt::sc_uint_base * part_read_target ()
virtual sc_dt::uint64 read_part (int left, int right) const
virtual sc_uint_sigref & select_part (int left, int right)
virtual void write_part (sc_dt::uint64 v, int left, int right)
virtual bool event () const
virtual const sc_dt::sc_uint< W > & get_data_ref () const
virtual const sc_dt::sc_uint< W > & read () const
virtual const sc_event & value_changed_event () const
virtual void write (const sc_in< sc_dt::sc_uint< W > > &value)
virtual void write (const sc_inout< sc_dt::sc_uint< W > > &value)
virtual void write (const sc_dt::sc_uint< W > &value)
sc_uint_sigref & operator() (int left, int right)
sc_uint_sigref & operator[] (int bit)
void operator= (const this_type &new_val)
void operator= (const char *new_val)
void operator= (sc_dt::uint64 new_val)
void operator= (sc_dt::int64 new_val)
void operator= (int new_val)
void operator= (long new_val)
void operator= (short new_val)
void operator= (unsigned int new_val)
void operator= (unsigned long new_val)
void operator= (unsigned short new_val)
template<typename T >
void operator= (const sc_dt::sc_generic_base< T > &new_val)
void operator= (const sc_dt::sc_signed &new_val)
void operator= (const sc_dt::sc_unsigned &new_val)
void operator= (const sc_dt::sc_bv_base &new_val)
void operator= (const sc_dt::sc_lv_base &new_val)
virtual void concat_set (sc_dt::int64 src, int low_i)
virtual void concat_set (const sc_dt::sc_lv_base &src, int low_i)
virtual void concat_set (const sc_dt::sc_signed &src, int low_i)
virtual void concat_set (const sc_dt::sc_unsigned &src, int low_i)
virtual void concat_set (sc_dt::uint64 src, int low_i)
template<typename T >
SC_TEMPLATE void operator= (const sc_dt::sc_generic_base< T > &new_val)
Public Member Functions inherited from sc_core::sc_interface
virtual ~sc_interface ()
Public Member Functions inherited from sc_core::sc_signal_write_if< sc_dt::sc_uint< W > >
virtual sc_writer_policy get_writer_policy () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_dt::sc_uint< W >
sc_uint ()
sc_uint (uint_type v)
sc_uint (const sc_uint< W > &a)
sc_uint (const sc_uint_base &a)
sc_uint (const sc_uint_subref_r &a)
template<class T >
sc_uint (const sc_generic_base< T > &a)
sc_uint (const sc_signed &a)
sc_uint (const sc_unsigned &a)
sc_uint (const sc_fxval &a)
sc_uint (const sc_fxval_fast &a)
sc_uint (const sc_fxnum &a)
sc_uint (const sc_fxnum_fast &a)
sc_uint (const sc_bv_base &a)
sc_uint (const sc_lv_base &a)
sc_uint (const char *a)
sc_uint (unsigned long a)
sc_uint (long a)
sc_uint (unsigned int a)
sc_uint (int a)
sc_uint (int64 a)
sc_uint (double a)
sc_uint< W > & operator= (uint_type v)
sc_uint< W > & operator= (const sc_uint_base &a)
sc_uint< W > & operator= (const sc_uint_subref_r &a)
sc_uint< W > & operator= (const sc_uint< W > &a)
template<class T >
sc_uint< W > & operator= (const sc_generic_base< T > &a)
sc_uint< W > & operator= (const sc_signed &a)
sc_uint< W > & operator= (const sc_unsigned &a)
sc_uint< W > & operator= (const sc_fxval &a)
sc_uint< W > & operator= (const sc_fxval_fast &a)
sc_uint< W > & operator= (const sc_fxnum &a)
sc_uint< W > & operator= (const sc_fxnum_fast &a)
sc_uint< W > & operator= (const sc_bv_base &a)
sc_uint< W > & operator= (const sc_lv_base &a)
sc_uint< W > & operator= (const char *a)
sc_uint< W > & operator= (unsigned long a)
sc_uint< W > & operator= (long a)
sc_uint< W > & operator= (unsigned int a)
sc_uint< W > & operator= (int a)
sc_uint< W > & operator= (int64 a)
sc_uint< W > & operator= (double a)
sc_uint< W > & operator+= (uint_type v)
sc_uint< W > & operator-= (uint_type v)
sc_uint< W > & operator*= (uint_type v)
sc_uint< W > & operator/= (uint_type v)
sc_uint< W > & operator%= (uint_type v)
sc_uint< W > & operator&= (uint_type v)
sc_uint< W > & operator|= (uint_type v)
sc_uint< W > & operator^= (uint_type v)
sc_uint< W > & operator<<= (uint_type v)
sc_uint< W > & operator>>= (uint_type v)
sc_uint< W > & operator++ ()
const sc_uint< W > operator++ (int)
sc_uint< W > & operator-- ()
const sc_uint< W > operator-- (int)
Public Member Functions inherited from sc_dt::sc_uint_base
sc_uint_base (int w=sc_length_param().len())
sc_uint_base (uint_type v, int w)
sc_uint_base (const sc_uint_base &a)
sc_uint_base (const sc_uint_subref_r &a)
template<class T >
sc_uint_base (const sc_generic_base< T > &a)
sc_uint_base (const sc_bv_base &v)
sc_uint_base (const sc_lv_base &v)
sc_uint_base (const sc_int_subref_r &v)
sc_uint_base (const sc_signed_subref_r &v)
sc_uint_base (const sc_unsigned_subref_r &v)
sc_uint_base (const sc_signed &a)
sc_uint_base (const sc_unsigned &a)
virtual ~sc_uint_base ()
sc_uint_base & operator= (uint_type v)
sc_uint_base & operator= (const sc_uint_base &a)
sc_uint_base & operator= (const sc_uint_subref_r &a)
template<class T >
sc_uint_base & operator= (const sc_generic_base< T > &a)
sc_uint_base & operator= (const sc_signed &a)
sc_uint_base & operator= (const sc_unsigned &a)
sc_uint_base & operator= (const sc_fxval &a)
sc_uint_base & operator= (const sc_fxval_fast &a)
sc_uint_base & operator= (const sc_fxnum &a)
sc_uint_base & operator= (const sc_fxnum_fast &a)
sc_uint_base & operator= (const sc_bv_base &a)
sc_uint_base & operator= (const sc_lv_base &a)
sc_uint_base & operator= (const char *a)
sc_uint_base & operator= (unsigned long a)
sc_uint_base & operator= (long a)
sc_uint_base & operator= (unsigned int a)
sc_uint_base & operator= (int a)
sc_uint_base & operator= (int64 a)
sc_uint_base & operator= (double a)
sc_uint_base & operator+= (uint_type v)
sc_uint_base & operator-= (uint_type v)
sc_uint_base & operator*= (uint_type v)
sc_uint_base & operator/= (uint_type v)
sc_uint_base & operator%= (uint_type v)
sc_uint_base & operator&= (uint_type v)
sc_uint_base & operator|= (uint_type v)
sc_uint_base & operator^= (uint_type v)
sc_uint_base & operator<<= (uint_type v)
sc_uint_base & operator>>= (uint_type v)
sc_uint_base & operator++ ()
const sc_uint_base operator++ (int)
sc_uint_base & operator-- ()
const sc_uint_base operator-- (int)
sc_uint_bitref & operator[] (int i)
const sc_uint_bitref_r & operator[] (int i) const
sc_uint_bitref & bit (int i)
const sc_uint_bitref_r & bit (int i) const
sc_uint_subref & operator() (int left, int right)
const sc_uint_subref_r & operator() (int left, int right) const
sc_uint_subref & range (int left, int right)
const sc_uint_subref_r & range (int left, int right) const
bool test (int i) const
void set (int i)
void set (int i, bool v)
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
long long_low () const
long long_high () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
void check_writer ()
Protected Member Functions inherited from sc_core::sc_signal_inout_if< sc_dt::sc_uint< W > >
sc_signal_inout_if ()
Protected Member Functions inherited from sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_uint_part_if
sc_uint_part_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Protected Member Functions inherited from sc_core::sc_signal_write_if< sc_dt::sc_uint< W > >
sc_signal_write_if ()
Protected Member Functions inherited from sc_core::sc_prim_channel
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
sc_event * m_changed_event_p
sc_dt::uint64 m_event_delta
sc_dt::uint64 m_new_val
sc_port_base * m_output_p
sc_process_b * m_writer_p
Protected Attributes inherited from sc_dt::sc_uint_base
uint_type m_val
int m_len
int m_ulen
Private Member Functions
sc_signal< sc_dt::sc_uint< W > > & operator++ ()
const sc_signal< sc_dt::sc_uint< W > > & operator++ (int)
sc_signal< sc_dt::sc_uint< W > > & operator-- ()
const sc_signal< sc_dt::sc_uint< W > > & operator-- (int)
sc_signal< sc_dt::sc_uint< W > > & operator+= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator-= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator*= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator/= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator%= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator&= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator|= (sc_dt::uint_type)
sc_signal< sc_dt::sc_uint< W > > & operator^= (sc_dt::uint_type)
Detailed Description
Definition at line 317 of file scx_signal_uint.h.
Member Typedef Documentation
this_type
typedef sc_signal<sc_dt::sc_uint<W> > sc_core::sc_signal< sc_dt::sc_uint< W > >::this_type
Definition at line 323 of file scx_signal_uint.h.
Constructor & Destructor Documentation
sc_signal() [1/2]
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_uint< W > >::sc_signal () inline
Definition at line 706 of file scx_signal_uint.h.
References SC_TEMPLATE.
sc_signal() [2/2]
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_uint< W > >::sc_signal (const char * name_) inline explicit
Definition at line 715 of file scx_signal_uint.h.
References SC_TEMPLATE.
~sc_signal()
SC_TEMPLATE sc_core::sc_signal< sc_dt::sc_uint< W > >::~sc_signal () inline virtual
Definition at line 724 of file scx_signal_uint.h.
References SC_TEMPLATE.
Member Function Documentation
base_event()
SC_TEMPLATE bool sc_core::sc_signal< sc_dt::sc_uint< W > >::base_event () const inline
Definition at line 418 of file scx_signal_uint.h.
References SC_TEMPLATE.
base_read()
SC_TEMPLATE const sc_dt::sc_uint< W > & sc_core::sc_signal< sc_dt::sc_uint< W > >::base_read () const inline
Definition at line 425 of file scx_signal_uint.h.
References SC_TEMPLATE.
base_value_changed_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_uint< W > >::base_value_changed_event () const inline
Definition at line 432 of file scx_signal_uint.h.
References SC_TEMPLATE.
base_write()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::base_write (sc_dt::uint64 value) inline
Definition at line 440 of file scx_signal_uint.h.
References SC_TEMPLATE.
check_writer()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::check_writer () inline protected
Definition at line 456 of file scx_signal_uint.h.
References name(), sc_core::sc_object::name(), sc_core::sc_get_current_process_b(), sc_core::sc_signal_invalid_writer(), and SC_TEMPLATE.
concat_set() [1/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::concat_set (sc_dt::int64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_uint_base.
Definition at line 482 of file scx_signal_uint.h.
References SC_TEMPLATE.
concat_set() [2/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::concat_set (const sc_dt::sc_lv_base & src, int low_i) inline virtual
Definition at line 496 of file scx_signal_uint.h.
References sc_dt::sc_lv_base::length(), and SC_TEMPLATE.
concat_set() [3/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::concat_set (const sc_dt::sc_signed & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_uint_base.
Definition at line 505 of file scx_signal_uint.h.
References SC_TEMPLATE.
concat_set() [4/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::concat_set (const sc_dt::sc_unsigned & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_uint_base.
Definition at line 512 of file scx_signal_uint.h.
References SC_TEMPLATE.
concat_set() [5/5]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::concat_set (sc_dt::uint64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_uint_base.
Definition at line 519 of file scx_signal_uint.h.
References SC_TEMPLATE.
default_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_uint< W > >::default_event () const inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 528 of file scx_signal_uint.h.
References SC_TEMPLATE.
event()
SC_TEMPLATE bool sc_core::sc_signal< sc_dt::sc_uint< W > >::event () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >.
Definition at line 533 of file scx_signal_uint.h.
References SC_TEMPLATE.
get_data_ref()
SC_TEMPLATE const sc_dt::sc_uint< W > & sc_core::sc_signal< sc_dt::sc_uint< W > >::get_data_ref () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >.
Definition at line 539 of file scx_signal_uint.h.
References SC_TEMPLATE.
kind()
SC_TEMPLATE const char * sc_core::sc_signal< sc_dt::sc_uint< W > >::kind () const inline virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 551 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator%=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator%= (sc_dt::uint_type) private
operator&=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator &= (sc_dt::uint_type) private
operator()()
SC_TEMPLATE sc_uint_sigref & sc_core::sc_signal< sc_dt::sc_uint< W > >::operator() (int left, int right) inline
Definition at line 566 of file scx_signal_uint.h.
References sc_core::sc_uint_sigref::initialize(), sc_core::sc_uint_sigref::m_pool, and SC_TEMPLATE.
operator*=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator*= (sc_dt::uint_type) private
operator++() [1/2]
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator++ () private
operator++() [2/2]
const sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator++ (int) private
operator+=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator+= (sc_dt::uint_type) private
operator--() [1/2]
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator-- () private
operator--() [2/2]
const sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator-- (int) private
operator-=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator-= (sc_dt::uint_type) private
operator/=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator/= (sc_dt::uint_type) private
operator=() [1/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const this_type & new_val) inline
Definition at line 589 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [2/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const char * new_val) inline
Definition at line 599 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [3/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (sc_dt::uint64 new_val) inline
Definition at line 594 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [4/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (sc_dt::int64 new_val) inline
Definition at line 604 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [5/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (int new_val) inline
Definition at line 609 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [6/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (long new_val) inline
Definition at line 614 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [7/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (short new_val) inline
Definition at line 619 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [8/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (unsigned int new_val) inline
Definition at line 624 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [9/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (unsigned long new_val) inline
Definition at line 629 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [10/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (unsigned short new_val) inline
Definition at line 634 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [11/16]
template<typename T > void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
operator=() [12/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_signed & new_val) inline
Definition at line 646 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [13/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_unsigned & new_val) inline
Definition at line 652 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [14/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_bv_base & new_val) inline
Definition at line 657 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [15/16]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_lv_base & new_val) inline
Definition at line 662 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator=() [16/16]
template<typename T > SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
Definition at line 640 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator[]()
SC_TEMPLATE sc_uint_sigref & sc_core::sc_signal< sc_dt::sc_uint< W > >::operator[] (int bit) inline
Definition at line 583 of file scx_signal_uint.h.
References SC_TEMPLATE.
operator^=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator^= (sc_dt::uint_type) private
operator|=()
sc_signal<sc_dt::sc_uint<W> >& sc_core::sc_signal< sc_dt::sc_uint< W > >::operator|= (sc_dt::uint_type) private
part_read_target()
SC_TEMPLATE sc_dt::sc_uint_base * sc_core::sc_signal< sc_dt::sc_uint< W > >::part_read_target () inline virtual
Reimplemented from sc_core::sc_uint_part_if.
Definition at line 668 of file scx_signal_uint.h.
References SC_TEMPLATE.
read()
SC_TEMPLATE const sc_dt::sc_uint< W > & sc_core::sc_signal< sc_dt::sc_uint< W > >::read () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >.
Definition at line 673 of file scx_signal_uint.h.
References SC_TEMPLATE.
read_part()
SC_TEMPLATE sc_dt::uint64 sc_core::sc_signal< sc_dt::sc_uint< W > >::read_part (int left, int right) const inline virtual
Reimplemented from sc_core::sc_uint_part_if.
Definition at line 678 of file scx_signal_uint.h.
References sc_dt::mask_int, and SC_TEMPLATE.
register_port()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::register_port (sc_port_base & port_, const char * if_typename_) inline virtual
Reimplemented from sc_core::sc_interface.
Definition at line 685 of file scx_signal_uint.h.
References name(), sc_core::sc_object::name(), sc_core::sc_signal_invalid_writer(), and SC_TEMPLATE.
select_part()
SC_TEMPLATE sc_uint_sigref & sc_core::sc_signal< sc_dt::sc_uint< W > >::select_part (int left, int right) inline virtual
Reimplemented from sc_core::sc_uint_part_if.
Definition at line 773 of file scx_signal_uint.h.
References sc_core::sc_uint_sigref::initialize(), sc_core::sc_uint_sigref::m_pool, and SC_TEMPLATE.
update()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::update () inline virtual
Reimplemented from sc_core::sc_prim_channel.
Definition at line 731 of file scx_signal_uint.h.
References sc_core::sc_simcontext::delta_count(), sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_dt::sc_uint_base::operator=(), SC_TEMPLATE, and sc_core::sc_object::simcontext().
value_changed_event()
SC_TEMPLATE const sc_event & sc_core::sc_signal< sc_dt::sc_uint< W > >::value_changed_event () const inline virtual
Implements sc_core::sc_signal_in_if< sc_dt::sc_uint< W > >.
Definition at line 752 of file scx_signal_uint.h.
References SC_TEMPLATE.
write() [1/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::write (const sc_in< sc_dt::sc_uint< W > > & value) inline virtual
Definition at line 757 of file scx_signal_uint.h.
References SC_TEMPLATE.
write() [2/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::write (const sc_inout< sc_dt::sc_uint< W > > & value) inline virtual
Definition at line 762 of file scx_signal_uint.h.
References SC_TEMPLATE.
write() [3/3]
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::write (const sc_dt::sc_uint< W > & value) inline virtual
Implements sc_core::sc_signal_write_if< sc_dt::sc_uint< W > >.
Definition at line 767 of file scx_signal_uint.h.
References SC_TEMPLATE.
write_part()
SC_TEMPLATE void sc_core::sc_signal< sc_dt::sc_uint< W > >::write_part (sc_dt::uint64 v, int left, int right) inline virtual
Reimplemented from sc_core::sc_uint_part_if.
Definition at line 783 of file scx_signal_uint.h.
References sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::m_new_val, sc_dt::mask_int, sc_core::sc_prim_channel::request_update(), and SC_TEMPLATE.
Member Data Documentation
m_changed_event_p
sc_event* sc_core::sc_signal< sc_dt::sc_uint< W > >::m_changed_event_p mutable protected
Definition at line 409 of file scx_signal_uint.h.
m_event_delta
sc_dt::uint64 sc_core::sc_signal< sc_dt::sc_uint< W > >::m_event_delta protected
Definition at line 410 of file scx_signal_uint.h.
m_new_val
sc_dt::uint64 sc_core::sc_signal< sc_dt::sc_uint< W > >::m_new_val protected
Definition at line 411 of file scx_signal_uint.h.
m_output_p
sc_port_base* sc_core::sc_signal< sc_dt::sc_uint< W > >::m_output_p protected
Definition at line 412 of file scx_signal_uint.h.
m_writer_p
sc_process_b* sc_core::sc_signal< sc_dt::sc_uint< W > >::m_writer_p protected
Definition at line 413 of file scx_signal_uint.h.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_uint.h