gem5: QoS::QueuePolicy Class Reference
QoS::QueuePolicy Class Reference abstract
QoS Queue Policy.
#include <q_policy.hh>
Public Types
typedef std::deque< PacketPtr > PacketQueue
Public Member Functions
virtual void enqueuePacket (PacketPtr pkt)
This method is called by the memory controller after it enqueues a packet.
virtual PacketQueue::iterator selectPacket (PacketQueue *queue)=0
Policy selector.
void setMemCtrl (MemCtrl *mem)
Setting a pointer to the Memory Controller implementing the policy.
virtual ~QueuePolicy ()
Static Public Member Functions
static QueuePolicy * create (const QoSMemCtrlParams *p)
This factory method is used for generating the queue policy.
Protected Member Functions
QueuePolicy (const QoSMemCtrlParams *p)
Protected Attributes
MemCtrl * memCtrl
Pointer to parent memory controller implementing the policy.
Detailed Description
QoS Queue Policy.
The QoS Queue Policy class implements algorithms to schedule packets within the same QoS priority queue
Definition at line 59 of file q_policy.hh.
Member Typedef Documentation
PacketQueue
typedef std::deque<PacketPtr> QoS::QueuePolicy::PacketQueue
Definition at line 62 of file q_policy.hh.
Constructor & Destructor Documentation
~QueuePolicy()
virtual QoS::QueuePolicy::~QueuePolicy () inline virtual
Definition at line 102 of file q_policy.hh.
QueuePolicy()
QoS::QueuePolicy::QueuePolicy (const QoSMemCtrlParams * p) inline protected
Definition at line 105 of file q_policy.hh.
Member Function Documentation
create()
QueuePolicy * QoS::QueuePolicy::create (const QoSMemCtrlParams * p) static
This factory method is used for generating the queue policy.
It takes the memory controller params as an argument and returns the related QueuePolicy object. If no particular QueuePolicy has been specified in the QoSMemCtrlParams, the method will default to a LIFO queue policy.
Parameters
p QoS::MemCtrl parameter variable
Returns
Pointer to the QueuePolicy
Definition at line 52 of file q_policy.cc.
enqueuePacket()
virtual void QoS::QueuePolicy::enqueuePacket (PacketPtr pkt) inline virtual
This method is called by the memory controller after it enqueues a packet.
It is a way for the queue policy to hook into the packet enqueuing and update relevant metadata. This will then be used once the QueuePolicy::selectPacket will be called.
Parameters
pkt Enqueued packet
Reimplemented in QoS::LrgQueuePolicy.
Definition at line 83 of file q_policy.hh.
References selectPacket().
Referenced by QoS::LrgQueuePolicy::LrgQueuePolicy().
selectPacket()
virtual PacketQueue::iterator QoS::QueuePolicy::selectPacket (PacketQueue * queue) pure virtual
Policy selector.
The implementation of this virtual method selects the packet to be serviced from the packet queue passed as an argument.
Parameters
queue Packet queue
Returns
Iterator pointing to the packet in the queue to be serviced
Implemented in QoS::LrgQueuePolicy, QoS::FifoQueuePolicy, and QoS::LifoQueuePolicy.
Referenced by enqueuePacket(), and QoS::LrgQueuePolicy::LrgQueuePolicy().
setMemCtrl()
void QoS::QueuePolicy::setMemCtrl (MemCtrl * mem) inline
Setting a pointer to the Memory Controller implementing the policy.
Definition at line 100 of file q_policy.hh.
References mem, and memCtrl.
Member Data Documentation
memCtrl
MemCtrl* QoS::QueuePolicy::memCtrl protected
Pointer to parent memory controller implementing the policy.
Definition at line 110 of file q_policy.hh.
Referenced by QoS::LrgQueuePolicy::enqueuePacket(), QoS::LrgQueuePolicy::selectPacket(), and setMemCtrl().
The documentation for this class was generated from the following files:
mem/qos/q_policy.hh
mem/qos/q_policy.cc