gem5: sc_dt::sc_int_subref_r Class Reference
sc_dt::sc_int_subref_r Class Reference
#include <sc_int_base.hh>
Public Member Functions
sc_int_subref_r (const sc_int_subref_r &a)
virtual ~sc_int_subref_r ()
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_int_subref_r ()
void initialize (const sc_int_base *obj_p, int left_i, int right_i)
Protected Attributes
int m_left
sc_int_base * m_obj_p
int m_right
Private Member Functions
const sc_int_subref_r & operator= (const sc_int_subref_r &)
Friends
class sc_int_base
class sc_int_signal
class sc_int_subref
Detailed Description
Definition at line 288 of file sc_int_base.hh.
Constructor & Destructor Documentation
sc_int_subref_r() [1/2]
sc_dt::sc_int_subref_r::sc_int_subref_r () inline protected
Definition at line 296 of file sc_int_base.hh.
sc_int_subref_r() [2/2]
sc_dt::sc_int_subref_r::sc_int_subref_r (const sc_int_subref_r & a) inline
Definition at line 308 of file sc_int_base.hh.
~sc_int_subref_r()
virtual sc_dt::sc_int_subref_r::~sc_int_subref_r () inline virtual
Definition at line 314 of file sc_int_base.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_int_subref_r::and_reduce () const inline
Definition at line 1073 of file sc_int_base.hh.
References ArmISA::a, and sc_dt::sc_int_base::and_reduce().
Referenced by sc_dt::and_reduce().
concat_get_ctrl()
bool sc_dt::sc_int_subref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 160 of file sc_int_base.cc.
References BITS_PER_DIGIT, ArmISA::mask, and sc_dt::mask_int.
concat_get_data()
bool sc_dt::sc_int_subref_r::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 200 of file sc_int_base.cc.
References BITS_PER_DIGIT, DIGIT_MASK, ArmISA::mask, sc_dt::mask_int, sc_dt::UINT_ZERO, and X86ISA::val.
concat_get_uint64()
virtual uint64 sc_dt::sc_int_subref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 330 of file sc_int_base.hh.
References sc_dt::and_reduce(), ArmISA::len, length, and X86ISA::val.
concat_length()
virtual int sc_dt::sc_int_subref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 321 of file sc_int_base.hh.
References length.
initialize()
void sc_dt::sc_int_subref_r::initialize (const sc_int_base * obj_p, int left_i, int right_i) inline protected
Definition at line 299 of file sc_int_base.hh.
Referenced by sc_dt::sc_int_base::operator()(), and sc_dt::sc_int_base::range().
length()
int sc_dt::sc_int_subref_r::length () const inline
Definition at line 317 of file sc_int_base.hh.
nand_reduce()
bool sc_dt::sc_int_subref_r::nand_reduce () const inline
Definition at line 342 of file sc_int_base.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
Referenced by sc_dt::nand_reduce().
nor_reduce()
bool sc_dt::sc_int_subref_r::nor_reduce () const inline
Definition at line 344 of file sc_int_base.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
Referenced by sc_dt::nor_reduce().
operator uint_type()
sc_dt::sc_int_subref_r::operator uint_type () const inline
Definition at line 1061 of file sc_int_base.hh.
References SC_INTWIDTH, and X86ISA::val.
operator=()
const sc_int_subref_r& sc_dt::sc_int_subref_r::operator= (const sc_int_subref_r &) private
or_reduce()
bool sc_dt::sc_int_subref_r::or_reduce () const inline
Definition at line 1080 of file sc_int_base.hh.
References ArmISA::a, and sc_dt::sc_int_base::or_reduce().
Referenced by sc_dt::or_reduce().
print()
void sc_dt::sc_int_subref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 369 of file sc_int_base.hh.
References X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
to_double()
double sc_dt::sc_int_subref_r::to_double () const inline
Definition at line 1139 of file sc_int_base.hh.
to_int()
int sc_dt::sc_int_subref_r::to_int () const inline
Definition at line 1097 of file sc_int_base.hh.
to_int64()
int64 sc_dt::sc_int_subref_r::to_int64 () const inline
Definition at line 1125 of file sc_int_base.hh.
to_long()
long sc_dt::sc_int_subref_r::to_long () const inline
Definition at line 1111 of file sc_int_base.hh.
to_string() [1/2]
const std::string sc_dt::sc_int_subref_r::to_string (sc_numrep numrep = SC_DEC) const inline
Definition at line 1149 of file sc_int_base.hh.
References ArmISA::a, length, and sc_dt::sc_uint_base::to_string().
to_string() [2/2]
const std::string sc_dt::sc_int_subref_r::to_string (sc_numrep numrep, bool w_prefix) const inline
Definition at line 1157 of file sc_int_base.hh.
References ArmISA::a, length, and sc_dt::sc_uint_base::to_string().
to_uint()
unsigned int sc_dt::sc_int_subref_r::to_uint () const inline
Definition at line 1104 of file sc_int_base.hh.
to_uint64()
uint64 sc_dt::sc_int_subref_r::to_uint64 () const inline
Definition at line 1132 of file sc_int_base.hh.
Referenced by sc_dt::sc_uint_base::sc_uint_base().
to_ulong()
unsigned long sc_dt::sc_int_subref_r::to_ulong () const inline
Definition at line 1118 of file sc_int_base.hh.
value()
uint_type sc_dt::sc_int_subref_r::value () const inline
Definition at line 352 of file sc_int_base.hh.
References sc_dt::SC_DEC, and sc_dt::to_string().
xnor_reduce()
bool sc_dt::sc_int_subref_r::xnor_reduce () const inline
Definition at line 346 of file sc_int_base.hh.
References sc_dt::xor_reduce().
Referenced by sc_dt::xnor_reduce().
xor_reduce()
bool sc_dt::sc_int_subref_r::xor_reduce () const inline
Definition at line 1087 of file sc_int_base.hh.
References ArmISA::a, and sc_dt::sc_int_base::xor_reduce().
Referenced by sc_dt::xor_reduce().
Friends And Related Function Documentation
sc_int_base
friend class sc_int_base friend
Definition at line 290 of file sc_int_base.hh.
sc_int_signal
friend class sc_int_signal friend
Definition at line 291 of file sc_int_base.hh.
sc_int_subref
friend class sc_int_subref friend
Definition at line 292 of file sc_int_base.hh.
Member Data Documentation
m_left
int sc_dt::sc_int_subref_r::m_left protected
Definition at line 375 of file sc_int_base.hh.
m_obj_p
sc_int_base* sc_dt::sc_int_subref_r::m_obj_p protected
Definition at line 376 of file sc_int_base.hh.
m_right
int sc_dt::sc_int_subref_r::m_right protected
Definition at line 377 of file sc_int_base.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_int_base.hh
systemc/dt/int/sc_int_base.cc