gem5: RealViewTemperatureSensor Class Reference
RealViewTemperatureSensor Class Reference
This device implements the temperature sensor used in the RealView/Versatile Express platform.
#include <rv_ctrl.hh>
Public Member Functions
RealViewTemperatureSensor (RealViewTemperatureSensorParams *p)
virtual ~RealViewTemperatureSensor ()
uint32_t read () const override
void write (uint32_t temp) override
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
System * system
The system this RV device belongs to.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Private Member Functions inherited from RealViewCtrl::Device
Device (RealViewCtrl &parent, DeviceFunc func, uint8_t site, uint8_t pos, uint8_t dcc, uint16_t dev)
virtual ~Device ()
Detailed Description
This device implements the temperature sensor used in the RealView/Versatile Express platform.
See ARM DUI 0447J (ARM Motherboard Express uATX – V2M-P1).
Definition at line 229 of file rv_ctrl.hh.
Constructor & Destructor Documentation
RealViewTemperatureSensor()
RealViewTemperatureSensor::RealViewTemperatureSensor (RealViewTemperatureSensorParams * p) inline
Definition at line 233 of file rv_ctrl.hh.
~RealViewTemperatureSensor()
virtual RealViewTemperatureSensor::~RealViewTemperatureSensor () inline virtual
Definition at line 239 of file rv_ctrl.hh.
References RealViewCtrl::Device::read().
Member Function Documentation
read()
uint32_t RealViewTemperatureSensor::read () const override virtual
Implements RealViewCtrl::Device.
Definition at line 304 of file rv_ctrl.cc.
References ThermalModel::getTemp(), RealViewOsc::RealViewOsc(), X86ISA::system, ArmISA::t, and warn.
write()
void RealViewTemperatureSensor::write (uint32_t temp) inline override virtual
Implements RealViewCtrl::Device.
Definition at line 243 of file rv_ctrl.hh.
Member Data Documentation
system
System* RealViewTemperatureSensor::system protected
The system this RV device belongs to.
Definition at line 247 of file rv_ctrl.hh.
The documentation for this class was generated from the following files:
dev/arm/rv_ctrl.hh
dev/arm/rv_ctrl.cc