gem5: SimpleATInitiator2::SimplePool Class Reference
SimpleATInitiator2::SimplePool Class Reference
#include <SimpleATInitiator2.h>
Public Member Functions
SimplePool ()
mytransaction_type * claim ()
void release (mytransaction_type *t)
void free (tlm::tlm_generic_payload *t)
Public Member Functions inherited from tlm::tlm_mm_interface
virtual ~tlm_mm_interface ()
Detailed Description
Definition at line 74 of file SimpleATInitiator2.h.
Constructor & Destructor Documentation
SimplePool()
SimpleATInitiator2::SimplePool::SimplePool () inline
Definition at line 77 of file SimpleATInitiator2.h.
Member Function Documentation
claim()
mytransaction_type* SimpleATInitiator2::SimplePool::claim () inline
Definition at line 78 of file SimpleATInitiator2.h.
References tlm::tlm_generic_payload::acquire(), and ArmISA::t.
Referenced by SimpleATInitiator2::initTransaction().
free()
void SimpleATInitiator2::SimplePool::free (tlm::tlm_generic_payload * t) inline virtual
Implements tlm::tlm_mm_interface.
Definition at line 88 of file SimpleATInitiator2.h.
References tlm::tlm_generic_payload::reset(), and ArmISA::t.
release()
void SimpleATInitiator2::SimplePool::release (mytransaction_type * t) inline
Definition at line 84 of file SimpleATInitiator2.h.
References tlm::tlm_generic_payload::release().
Referenced by SimpleATInitiator2::myNBTransport(), and SimpleATInitiator2::run().
The documentation for this class was generated from the following file:
systemc/tests/include/SimpleATInitiator2.h