gem5: LabelOperand Class Reference
LabelOperand Class Reference
#include <operand.hh>
Public Member Functions
void init (unsigned opOffset, const BrigObject *obj)
std::string disassemble ()
uint32_t getTarget (Wavefront *w, int lane)
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Public Attributes
Label * label
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 737 of file operand.hh.
Member Function Documentation
disassemble()
std::string LabelOperand::disassemble ()
Definition at line 465 of file operand.cc.
getTarget()
uint32_t LabelOperand::getTarget (Wavefront * w, int lane)
Definition at line 459 of file operand.cc.
init()
void LabelOperand::init (unsigned opOffset, const BrigObject * obj)
Definition at line 444 of file operand.cc.
References Brig::BrigOperandCodeRef::base, Brig::BRIG_KIND_DIRECTIVE_LABEL, Brig::BRIG_KIND_OPERAND_CODE_REF, BrigObject::currentCode, BrigObject::getCodeSectionEntry(), BrigObject::getOperand(), Brig::BrigBase::kind, X86ISA::op, Brig::BrigOperandCodeRef::ref, and HsailCode::refLabel().
Member Data Documentation
label
Label* LabelOperand::label
Definition at line 740 of file operand.hh.
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc