gem5: PhysicalMemory Class Reference
PhysicalMemory Class Reference
The physical memory encapsulates all memories in the system and provides basic functionality for accessing those memories without going through the memory system and interconnect.
#include <physical.hh>
Public Member Functions
PhysicalMemory (const std::string &_name, const std::vector< AbstractMemory *> &_memories, bool mmap_using_noreserve)
Create a physical memory object, wrapping a number of memories.
~PhysicalMemory ()
Unmap all the backing store we have used.
const std::string name () const
Return the name for debugging and for creation of sections for checkpointing.
bool isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
AddrRangeList getConfAddrRanges () const
Get the memory ranges for all memories that are to be reported to the configuration table.
uint64_t totalSize () const
Get the total physical memory size.
std::vector< BackingStoreEntry > getBackingStore () const
Get the pointers to the backing store for external host access.
void access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
void functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
void serialize (CheckpointOut &cp) const override
Serialize all the memories in the system.
void serializeStore (CheckpointOut &cp, unsigned int store_id, AddrRange range, uint8_t *pmem) const
Serialize a specific store.
void unserialize (CheckpointIn &cp) override
Unserialize the memories in the system.
void unserializeStore (CheckpointIn &cp)
Unserialize a specific backing store, identified by a section.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Member Functions
PhysicalMemory (const PhysicalMemory &)
PhysicalMemory & operator= (const PhysicalMemory &)
void createBackingStore (AddrRange range, const std::vector< AbstractMemory *> &_memories, bool conf_table_reported, bool in_addr_map, bool kvm_map)
Create the memory region providing the backing store for a given address range that corresponds to a set of memories in the simulated system.
Private Attributes
std::string _name
AddrRangeMap< AbstractMemory *, 1 > addrMap
std::vector< AbstractMemory * > memories
uint64_t size
const bool mmapUsingNoReserve
std::vector< BackingStoreEntry > backingStore
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
The physical memory encapsulates all memories in the system and provides basic functionality for accessing those memories without going through the memory system and interconnect.
The physical memory is also responsible for providing the host system backingstore used by the memories in the simulated guest system. When the system is created, the physical memory allocates the backing store based on the address ranges that are populated in the system, and does so independent of how those map to actual memory controllers. Thus, the physical memory completely abstracts the mapping of the backing store of the host system and the address mapping in the guest system. This enables us to arbitrarily change the number of memory controllers, and their address mapping, as long as the ranges stay the same.
Definition at line 112 of file physical.hh.
Constructor & Destructor Documentation
PhysicalMemory() [1/2]
PhysicalMemory::PhysicalMemory (const PhysicalMemory &) private
PhysicalMemory() [2/2]
PhysicalMemory::PhysicalMemory (const std::string & _name, const std::vector< AbstractMemory *> & _memories, bool mmap_using_noreserve)
Create a physical memory object, wrapping a number of memories.
~PhysicalMemory()
PhysicalMemory::~PhysicalMemory ()
Unmap all the backing store we have used.
Definition at line 228 of file physical.cc.
References ArmISA::s.
Member Function Documentation
access()
void PhysicalMemory::access (PacketPtr pkt)
Perform an untimed memory access and update all the state (e.g.
locked addresses) and statistics accordingly. The packet is turned into a response if required.
Parameters
pkt Packet performing the access
Definition at line 278 of file physical.cc.
References Packet::getAddrRange(), Packet::isRequest(), and ArmISA::m.
Referenced by NonCachingSimpleCPU::sendPacket().
createBackingStore()
void PhysicalMemory::createBackingStore (AddrRange range, const std::vector< AbstractMemory *> & _memories, bool conf_table_reported, bool in_addr_map, bool kvm_map) private
Create the memory region providing the backing store for a given address range that corresponds to a set of memories in the simulated system.
Parameters
range The address range covered
memories The memories this range maps to
kvm_map Should KVM map this memory for the guest
Definition at line 185 of file physical.cc.
References DPRINTF, fatal, AddrRange::interleaved(), ArmISA::m, panic_if, AddrRange::size(), and AddrRange::to_string().
functionalAccess()
void PhysicalMemory::functionalAccess (PacketPtr pkt)
Perform an untimed memory read or write without changing anything but the memory itself.
No stats are affected by this access. In addition to normal accesses this also facilitates print requests.
Parameters
pkt Packet performing the access
Definition at line 287 of file physical.cc.
References Packet::getAddrRange(), Packet::isRequest(), and ArmISA::m.
getBackingStore()
std::vector<BackingStoreEntry> PhysicalMemory::getBackingStore () const inline
Get the pointers to the backing store for external host access.
Note that memory in the guest should be accessed using access() or functionalAccess(). This interface is primarily intended for CPU models using hardware virtualization. Note that memories that are null are not present, and that the backing store may also contain memories that are not part of the OS-visible global address map and thus are allowed to overlap.
Returns
Pointers to the memory backing store
Definition at line 214 of file physical.hh.
References BackingStoreEntry::pmem, BackingStoreEntry::range, serialize(), and unserialize().
Referenced by KvmVM::delayedStartup().
getConfAddrRanges()
AddrRangeList PhysicalMemory::getConfAddrRanges () const
Get the memory ranges for all memories that are to be reported to the configuration table.
The ranges are merged before they are returned such that any interleaved ranges appear as a single range.
Returns
All configuration table memory ranges
Definition at line 242 of file physical.cc.
References MipsISA::r.
Referenced by LinuxArmSystem::initState(), and ArmSemihosting::readString().
isMemAddr()
bool PhysicalMemory::isMemAddr (Addr addr) const
Check if a physical address is within a range of a memory that is part of the global address map.
Parameters
addr A physical address
Returns
Whether the address corresponds to a memory
Definition at line 236 of file physical.cc.
Referenced by System::isMemAddr().
name()
const std::string PhysicalMemory::name () const inline
Return the name for debugging and for creation of sections for checkpointing.
Definition at line 174 of file physical.hh.
References addr.
operator=()
PhysicalMemory& PhysicalMemory::operator= (const PhysicalMemory &) private
serialize()
void PhysicalMemory::serialize (CheckpointOut & cp) const override virtual
Serialize all the memories in the system.
This is independent of the logical memory layout, and the serialization only sees the contigous backing store, independent of how this maps to logical memories in the guest system.
Parameters
os stream to serialize to
Implements Serializable.
Definition at line 296 of file physical.cc.
References csprintf(), MipsISA::l, RiscvISA::locked_addrs, ArmISA::m, ArmISA::s, SERIALIZE_CONTAINER, and SERIALIZE_SCALAR.
serializeStore()
void PhysicalMemory::serializeStore (CheckpointOut & cp, unsigned int store_id, AddrRange range, uint8_t * pmem) const
Serialize a specific store.
Parameters
store_id Unique identifier of this backing store
range The address range of this backing store
pmem The host pointer to this backing store
Definition at line 326 of file physical.cc.
References CheckpointIn::dir(), DPRINTF, fatal, EmulationPageTable::name(), SERIALIZE_SCALAR, AddrRange::size(), and sc_dt::to_string().
totalSize()
uint64_t PhysicalMemory::totalSize () const inline
Get the total physical memory size.
Returns
The sum of all memory sizes
Definition at line 200 of file physical.hh.
Referenced by System::allocPhysPages(), System::freeMemSize(), and System::memSize().
unserialize()
void PhysicalMemory::unserialize (CheckpointIn & cp) override virtual
Unserialize the memories in the system.
As with the serialization, this action is independent of how the address ranges are mapped to logical memories in the guest system.
Implements Serializable.
Definition at line 372 of file physical.cc.
References csprintf(), ArmISA::i, ArmISA::m, UNSERIALIZE_CONTAINER, and UNSERIALIZE_SCALAR.
unserializeStore()
void PhysicalMemory::unserializeStore (CheckpointIn & cp)
Unserialize a specific backing store, identified by a section.
Definition at line 397 of file physical.cc.
References CheckpointIn::cptDir, DPRINTF, fatal, AddrRange::size(), UNSERIALIZE_SCALAR, and X86ISA::x.
Member Data Documentation
_name
std::string PhysicalMemory::_name private
Definition at line 118 of file physical.hh.
addrMap
AddrRangeMap<AbstractMemory*, 1> PhysicalMemory::addrMap private
Definition at line 121 of file physical.hh.
backingStore
std::vector<BackingStoreEntry> PhysicalMemory::backingStore private
Definition at line 134 of file physical.hh.
memories
std::vector<AbstractMemory*> PhysicalMemory::memories private
Definition at line 124 of file physical.hh.
mmapUsingNoReserve
const bool PhysicalMemory::mmapUsingNoReserve private
Definition at line 130 of file physical.hh.
size
uint64_t PhysicalMemory::size private
Definition at line 127 of file physical.hh.
The documentation for this class was generated from the following files:
mem/physical.hh
mem/physical.cc