gem5: SimpleExecContext Class Reference
SimpleExecContext Class Reference
#include <exec_context.hh>
Public Member Functions
SimpleExecContext (BaseSimpleCPU *_cpu, SimpleThread *_thread)
Constructor.
RegVal readIntRegOperand (const StaticInst *si, int idx) override
Reads an integer register.
void setIntRegOperand (const StaticInst *si, int idx, RegVal val) override
Sets an integer register to a value.
RegVal readFloatRegOperandBits (const StaticInst *si, int idx) override
Reads a floating point register in its binary format, instead of by value.
void setFloatRegOperandBits (const StaticInst *si, int idx, RegVal val) override
Sets the bits of a floating point register of single width to a binary value.
const VecRegContainer & readVecRegOperand (const StaticInst *si, int idx) const override
Reads a vector register.
VecRegContainer & getWritableVecRegOperand (const StaticInst *si, int idx) override
Reads a vector register for modification.
void setVecRegOperand (const StaticInst *si, int idx, const VecRegContainer &val) override
Sets a vector register to a value.
VecElem readVecElemOperand (const StaticInst *si, int idx) const override
Reads an element of a vector register.
void setVecElemOperand (const StaticInst *si, int idx, const VecElem val) override
Sets an element of a vector register to a value.
const VecPredRegContainer & readVecPredRegOperand (const StaticInst *si, int idx) const override
Predicate registers interface.
VecPredRegContainer & getWritableVecPredRegOperand (const StaticInst *si, int idx) override
Gets destination predicate register operand for modification.
void setVecPredRegOperand (const StaticInst *si, int idx, const VecPredRegContainer &val) override
Sets a destination predicate register operand to a value.
RegVal readCCRegOperand (const StaticInst *si, int idx) override
void setCCRegOperand (const StaticInst *si, int idx, RegVal val) override
RegVal readMiscRegOperand (const StaticInst *si, int idx) override
void setMiscRegOperand (const StaticInst *si, int idx, RegVal val) override
RegVal readMiscReg (int misc_reg) override
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
void setMiscReg (int misc_reg, RegVal val) override
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
PCState pcState () const override
void pcState (const PCState &val) override
Fault readMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >()) override
Perform an atomic memory read operation.
Fault initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >()) override
Initiate a timing memory read operation.
Fault writeMem (uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >()) override
For atomic-mode contexts, perform an atomic memory write operation.
Fault amoMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) override
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
Fault initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) override
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
void setStCondFailures (unsigned int sc_failures) override
Sets the number of consecutive store conditional failures.
unsigned int readStCondFailures () const override
Returns the number of consecutive store conditional failures.
void syscall (int64_t callnum, Fault *fault) override
Executes a syscall specified by the callnum.
ThreadContext * tcBase () override
Returns a pointer to the ThreadContext.
bool readPredicate () const override
void setPredicate (bool val) override
bool readMemAccPredicate () const override
void setMemAccPredicate (bool val) override
void demapPage (Addr vaddr, uint64_t asn) override
Invalidate a page in the DTLB and ITLB.
void armMonitor (Addr address) override
bool mwait (PacketPtr pkt) override
void mwaitAtomic (ThreadContext *tc) override
AddressMonitor * getAddrMonitor () override
template<typename VecElem >
VecLaneT< VecElem, true > readVecLaneOperand (const StaticInst *si, int idx) const
Vector Register Lane Interfaces.
virtual ConstVecLane8 readVec8BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 8bit operand.
virtual ConstVecLane16 readVec16BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 16bit operand.
virtual ConstVecLane32 readVec32BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 32bit operand.
virtual ConstVecLane64 readVec64BitLaneOperand (const StaticInst *si, int idx) const override
Reads source vector 64bit operand.
template<typename LD >
void setVecLaneOperandT (const StaticInst *si, int idx, const LD &val)
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::Byte > &val) override
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::TwoByte > &val) override
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::FourByte > &val) override
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::EightByte > &val) override
Write a lane of the destination vector operand.
Integer Register Interfaces
Floating Point Register Interfaces
Condition Code Registers
Misc Register Interfaces
PC Control
Memory Interface
SysCall Emulation Interfaces
ARM-Specific Interfaces
X86-Specific Interfaces
Public Attributes
BaseSimpleCPU * cpu
SimpleThread * thread
Addr fetchOffset
bool stayAtPC
TheISA::PCState predPC
Counter numInst
PER-THREAD STATS.
Stats::Scalar numInsts
Counter numOp
Stats::Scalar numOps
Stats::Scalar numIntAluAccesses
Stats::Scalar numFpAluAccesses
Stats::Scalar numVecAluAccesses
Stats::Scalar numCallsReturns
Stats::Scalar numCondCtrlInsts
Stats::Scalar numIntInsts
Stats::Scalar numFpInsts
Stats::Scalar numVecInsts
Stats::Scalar numIntRegReads
Stats::Scalar numIntRegWrites
Stats::Scalar numFpRegReads
Stats::Scalar numFpRegWrites
Stats::Scalar numVecRegReads
Stats::Scalar numVecRegWrites
Stats::Scalar numVecPredRegReads
Stats::Scalar numVecPredRegWrites
Stats::Scalar numCCRegReads
Stats::Scalar numCCRegWrites
Stats::Scalar numMemRefs
Stats::Scalar numLoadInsts
Stats::Scalar numStoreInsts
Stats::Formula numIdleCycles
Stats::Formula numBusyCycles
Counter numLoad
Stats::Average notIdleFraction
Stats::Formula idleFraction
Stats::Scalar icacheStallCycles
Counter lastIcacheStall
Stats::Scalar dcacheStallCycles
Counter lastDcacheStall
Stats::Vector statExecutedInstType
Stats::Scalar numBranches
Stats::Scalar numPredictedBranches
Number of branches predicted as taken.
Stats::Scalar numBranchMispred
Number of misprediced branches.
Protected Types
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
Additional Inherited Members
Public Types inherited from ExecContext
typedef TheISA::PCState PCState
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Detailed Description
Definition at line 61 of file exec_context.hh.
Member Typedef Documentation
VecElem
using SimpleExecContext::VecElem = TheISA::VecElem protected
Definition at line 64 of file exec_context.hh.
VecRegContainer
using SimpleExecContext::VecRegContainer = TheISA::VecRegContainer protected
Definition at line 63 of file exec_context.hh.
Constructor & Destructor Documentation
SimpleExecContext()
SimpleExecContext::SimpleExecContext (BaseSimpleCPU * _cpu, SimpleThread * _thread) inline
Constructor.
Definition at line 171 of file exec_context.hh.
Member Function Documentation
amoMem()
Fault SimpleExecContext::amoMem (Addr addr, uint8_t * data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) inline override virtual
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
Reimplemented from ExecContext.
Definition at line 465 of file exec_context.hh.
References BaseSimpleCPU::amoMem().
armMonitor()
void SimpleExecContext::armMonitor (Addr address) inline override virtual
Implements ExecContext.
Definition at line 549 of file exec_context.hh.
References BaseCPU::armMonitor(), and SimpleThread::threadId().
demapPage()
void SimpleExecContext::demapPage (Addr vaddr, uint64_t asn) inline override virtual
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 543 of file exec_context.hh.
References SimpleThread::demapPage().
getAddrMonitor()
AddressMonitor* SimpleExecContext::getAddrMonitor () inline override virtual
Implements ExecContext.
Definition at line 567 of file exec_context.hh.
References BaseCPU::getCpuAddrMonitor(), and SimpleThread::threadId().
getWritableVecPredRegOperand()
VecPredRegContainer& SimpleExecContext::getWritableVecPredRegOperand (const StaticInst * si, int idx) inline override virtual
Gets destination predicate register operand for modification.
Implements ExecContext.
Definition at line 349 of file exec_context.hh.
References StaticInst::destRegIdx(), SimpleThread::getWritableVecPredReg(), RegId::isVecPredReg(), and X86ISA::reg.
getWritableVecRegOperand()
VecRegContainer& SimpleExecContext::getWritableVecRegOperand (const StaticInst * si, int idx) inline override virtual
Reads a vector register for modification.
Implements ExecContext.
Definition at line 230 of file exec_context.hh.
References StaticInst::destRegIdx(), SimpleThread::getWritableVecReg(), RegId::isVecReg(), and X86ISA::reg.
initiateMemAMO()
Fault SimpleExecContext::initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) inline override virtual
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
Reimplemented from ExecContext.
Definition at line 471 of file exec_context.hh.
References BaseSimpleCPU::initiateMemAMO().
initiateMemRead()
Fault SimpleExecContext::initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>()) inline override virtual
Initiate a timing memory read operation.
Must be overridden for exec contexts that support timing memory mode. Not pure virtual since exec contexts that only support atomic memory mode need not override (though in that case this function should never be called).
Reimplemented from ExecContext.
Definition at line 447 of file exec_context.hh.
References BaseSimpleCPU::initiateMemRead().
mwait()
bool SimpleExecContext::mwait (PacketPtr pkt) inline override virtual
Implements ExecContext.
Definition at line 555 of file exec_context.hh.
References BaseCPU::mwait(), and SimpleThread::threadId().
mwaitAtomic()
void SimpleExecContext::mwaitAtomic (ThreadContext * tc) inline override virtual
Implements ExecContext.
Definition at line 561 of file exec_context.hh.
References SimpleThread::dtb, BaseCPU::mwaitAtomic(), and SimpleThread::threadId().
pcState() [1/2]
PCState SimpleExecContext::pcState () const inline override virtual
Implements ExecContext.
Definition at line 426 of file exec_context.hh.
References SimpleThread::pcState().
pcState() [2/2]
void SimpleExecContext::pcState (const PCState & val) inline override virtual
Implements ExecContext.
Definition at line 432 of file exec_context.hh.
References SimpleThread::pcState().
readCCRegOperand()
RegVal SimpleExecContext::readCCRegOperand (const StaticInst * si, int idx) inline override virtual
Implements ExecContext.
Definition at line 368 of file exec_context.hh.
References RegId::index(), RegId::isCCReg(), SimpleThread::readCCReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readFloatRegOperandBits()
RegVal SimpleExecContext::readFloatRegOperandBits (const StaticInst * si, int idx) inline override virtual
Reads a floating point register in its binary format, instead of by value.
Implements ExecContext.
Definition at line 199 of file exec_context.hh.
References RegId::index(), RegId::isFloatReg(), SimpleThread::readFloatReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readIntRegOperand()
RegVal SimpleExecContext::readIntRegOperand (const StaticInst * si, int idx) inline override virtual
Reads an integer register.
Implements ExecContext.
Definition at line 178 of file exec_context.hh.
References RegId::index(), RegId::isIntReg(), SimpleThread::readIntReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readMem()
Fault SimpleExecContext::readMem (Addr addr, uint8_t * data, unsigned int size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>()) inline override virtual
Perform an atomic memory read operation.
Must be overridden for exec contexts that support atomic memory mode. Not pure virtual since exec contexts that only support timing memory mode need not override (though in that case this function should never be called).
Reimplemented from ExecContext.
Definition at line 438 of file exec_context.hh.
References BaseSimpleCPU::readMem().
readMemAccPredicate()
bool SimpleExecContext::readMemAccPredicate () const inline override virtual
Implements ExecContext.
Definition at line 528 of file exec_context.hh.
References SimpleThread::readMemAccPredicate().
readMiscReg()
RegVal SimpleExecContext::readMiscReg (int misc_reg) inline override virtual
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implements ExecContext.
Definition at line 408 of file exec_context.hh.
References SimpleThread::readMiscReg().
readMiscRegOperand()
RegVal SimpleExecContext::readMiscRegOperand (const StaticInst * si, int idx) inline override virtual
Implements ExecContext.
Definition at line 386 of file exec_context.hh.
References RegId::index(), RegId::isMiscReg(), SimpleThread::readMiscReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readPredicate()
bool SimpleExecContext::readPredicate () const inline override virtual
Implements ExecContext.
Definition at line 512 of file exec_context.hh.
References SimpleThread::readPredicate().
readStCondFailures()
unsigned int SimpleExecContext::readStCondFailures () const inline override virtual
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 491 of file exec_context.hh.
References SimpleThread::readStCondFailures().
readVec16BitLaneOperand()
virtual ConstVecLane16 SimpleExecContext::readVec16BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 16bit operand.
Implements ExecContext.
Definition at line 269 of file exec_context.hh.
References PowerISA::si.
readVec32BitLaneOperand()
virtual ConstVecLane32 SimpleExecContext::readVec32BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 32bit operand.
Implements ExecContext.
Definition at line 275 of file exec_context.hh.
References PowerISA::si.
readVec64BitLaneOperand()
virtual ConstVecLane64 SimpleExecContext::readVec64BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 64bit operand.
Implements ExecContext.
Definition at line 281 of file exec_context.hh.
References PowerISA::si.
readVec8BitLaneOperand()
virtual ConstVecLane8 SimpleExecContext::readVec8BitLaneOperand (const StaticInst * si, int idx) const inline override virtual
Reads source vector 8bit operand.
Implements ExecContext.
Definition at line 263 of file exec_context.hh.
References PowerISA::si.
readVecElemOperand()
VecElem SimpleExecContext::readVecElemOperand (const StaticInst * si, int idx) const inline override virtual
Reads an element of a vector register.
Implements ExecContext.
Definition at line 320 of file exec_context.hh.
References RegId::isVecElem(), SimpleThread::readVecElem(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecLaneOperand()
template<typename VecElem > VecLaneT<VecElem, true> SimpleExecContext::readVecLaneOperand (const StaticInst * si, int idx) const inline
Vector Register Lane Interfaces.
Reads source vector lane.
Definition at line 254 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVecLane(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecPredRegOperand()
const VecPredRegContainer& SimpleExecContext::readVecPredRegOperand (const StaticInst * si, int idx) const inline override virtual
Predicate registers interface.
Reads source predicate register operand.
Implements ExecContext.
Definition at line 340 of file exec_context.hh.
References RegId::isVecPredReg(), SimpleThread::readVecPredReg(), X86ISA::reg, and StaticInst::srcRegIdx().
readVecRegOperand()
const VecRegContainer& SimpleExecContext::readVecRegOperand (const StaticInst * si, int idx) const inline override virtual
Reads a vector register.
Implements ExecContext.
Definition at line 220 of file exec_context.hh.
References RegId::isVecReg(), SimpleThread::readVecReg(), X86ISA::reg, and StaticInst::srcRegIdx().
setCCRegOperand()
void SimpleExecContext::setCCRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Implements ExecContext.
Definition at line 377 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isCCReg(), X86ISA::reg, SimpleThread::setCCReg(), and X86ISA::val.
setFloatRegOperandBits()
void SimpleExecContext::setFloatRegOperandBits (const StaticInst * si, int idx, RegVal val) inline override virtual
Sets the bits of a floating point register of single width to a binary value.
Implements ExecContext.
Definition at line 210 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isFloatReg(), X86ISA::reg, SimpleThread::setFloatReg(), and X86ISA::val.
setIntRegOperand()
void SimpleExecContext::setIntRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Sets an integer register to a value.
Implements ExecContext.
Definition at line 188 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isIntReg(), X86ISA::reg, SimpleThread::setIntReg(), and X86ISA::val.
setMemAccPredicate()
void SimpleExecContext::setMemAccPredicate (bool val) inline override virtual
Implements ExecContext.
Definition at line 534 of file exec_context.hh.
References SimpleThread::setMemAccPredicate().
Referenced by BaseSimpleCPU::preExecute().
setMiscReg()
void SimpleExecContext::setMiscReg (int misc_reg, RegVal val) inline override virtual
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implements ExecContext.
Definition at line 419 of file exec_context.hh.
References SimpleThread::setMiscReg().
setMiscRegOperand()
void SimpleExecContext::setMiscRegOperand (const StaticInst * si, int idx, RegVal val) inline override virtual
Implements ExecContext.
Definition at line 395 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::index(), RegId::isMiscReg(), X86ISA::reg, SimpleThread::setMiscReg(), and X86ISA::val.
setPredicate()
void SimpleExecContext::setPredicate (bool val) inline override virtual
Implements ExecContext.
Definition at line 518 of file exec_context.hh.
References Trace::InstRecord::setPredicate(), SimpleThread::setPredicate(), and BaseSimpleCPU::traceData.
Referenced by BaseSimpleCPU::preExecute().
setStCondFailures()
void SimpleExecContext::setStCondFailures (unsigned int sc_failures) inline override virtual
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 482 of file exec_context.hh.
References SimpleThread::setStCondFailures().
setVecElemOperand()
void SimpleExecContext::setVecElemOperand (const StaticInst * si, int idx, const VecElem val) inline override virtual
Sets an element of a vector register to a value.
Implements ExecContext.
Definition at line 330 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecElem(), X86ISA::reg, and SimpleThread::setVecElem().
setVecLaneOperand() [1/4]
virtual void SimpleExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::Byte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 298 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [2/4]
virtual void SimpleExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::TwoByte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 303 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [3/4]
virtual void SimpleExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::FourByte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 308 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperand() [4/4]
virtual void SimpleExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::EightByte > & val) inline override virtual
Write a lane of the destination vector operand.
Implements ExecContext.
Definition at line 313 of file exec_context.hh.
References setVecLaneOperandT().
setVecLaneOperandT()
template<typename LD > void SimpleExecContext::setVecLaneOperandT (const StaticInst * si, int idx, const LD & val) inline
Write a lane of the destination vector operand.
Definition at line 288 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecReg(), X86ISA::reg, and SimpleThread::setVecLane().
Referenced by setVecLaneOperand().
setVecPredRegOperand()
void SimpleExecContext::setVecPredRegOperand (const StaticInst * si, int idx, const VecPredRegContainer & val) inline override virtual
Sets a destination predicate register operand to a value.
Implements ExecContext.
Definition at line 358 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecPredReg(), X86ISA::reg, and SimpleThread::setVecPredReg().
setVecRegOperand()
void SimpleExecContext::setVecRegOperand (const StaticInst * si, int idx, const VecRegContainer & val) inline override virtual
Sets a vector register to a value.
Implements ExecContext.
Definition at line 240 of file exec_context.hh.
References StaticInst::destRegIdx(), RegId::isVecReg(), X86ISA::reg, and SimpleThread::setVecReg().
syscall()
void SimpleExecContext::syscall (int64_t callnum, Fault * fault) inline override virtual
Executes a syscall specified by the callnum.
Implements ExecContext.
Definition at line 500 of file exec_context.hh.
References FullSystem, panic, and SimpleThread::syscall().
tcBase()
ThreadContext* SimpleExecContext::tcBase () inline override virtual
Returns a pointer to the ThreadContext.
Implements ExecContext.
Definition at line 509 of file exec_context.hh.
References SimpleThread::getTC().
writeMem()
Fault SimpleExecContext::writeMem (uint8_t * data, unsigned int size, Addr addr, Request::Flags flags, uint64_t * res, const std::vector< bool > & byteEnable = std::vector< bool >()) inline override virtual
For atomic-mode contexts, perform an atomic memory write operation.
For timing-mode contexts, initiate a timing memory write operation.
Implements ExecContext.
Definition at line 456 of file exec_context.hh.
References BaseSimpleCPU::writeMem().
Member Data Documentation
cpu
BaseSimpleCPU* SimpleExecContext::cpu
Definition at line 67 of file exec_context.hh.
dcacheStallCycles
Stats::Scalar SimpleExecContext::dcacheStallCycles
Definition at line 154 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
fetchOffset
Addr SimpleExecContext::fetchOffset
Definition at line 71 of file exec_context.hh.
Referenced by BaseSimpleCPU::advancePC(), BaseSimpleCPU::checkForInterrupts(), BaseSimpleCPU::preExecute(), and BaseSimpleCPU::setupFetchRequest().
icacheStallCycles
Stats::Scalar SimpleExecContext::icacheStallCycles
Definition at line 150 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
idleFraction
Stats::Formula SimpleExecContext::idleFraction
Definition at line 147 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
lastDcacheStall
Counter SimpleExecContext::lastDcacheStall
Definition at line 155 of file exec_context.hh.
lastIcacheStall
Counter SimpleExecContext::lastIcacheStall
Definition at line 151 of file exec_context.hh.
notIdleFraction
Stats::Average SimpleExecContext::notIdleFraction
Definition at line 146 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numBranches
Stats::Scalar SimpleExecContext::numBranches
Total number of branches fetched
Definition at line 159 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numBranchMispred
Stats::Scalar SimpleExecContext::numBranchMispred
Number of misprediced branches.
Definition at line 163 of file exec_context.hh.
Referenced by BaseSimpleCPU::advancePC(), and BaseSimpleCPU::regStats().
numBusyCycles
Stats::Formula SimpleExecContext::numBusyCycles
Definition at line 140 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numCallsReturns
Stats::Scalar SimpleExecContext::numCallsReturns
Definition at line 97 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numCCRegReads
Stats::Scalar SimpleExecContext::numCCRegReads
Definition at line 128 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numCCRegWrites
Stats::Scalar SimpleExecContext::numCCRegWrites
Definition at line 129 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numCondCtrlInsts
Stats::Scalar SimpleExecContext::numCondCtrlInsts
Definition at line 100 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numFpAluAccesses
Stats::Scalar SimpleExecContext::numFpAluAccesses
Definition at line 91 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numFpInsts
Stats::Scalar SimpleExecContext::numFpInsts
Definition at line 106 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numFpRegReads
Stats::Scalar SimpleExecContext::numFpRegReads
Definition at line 116 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numFpRegWrites
Stats::Scalar SimpleExecContext::numFpRegWrites
Definition at line 117 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numIdleCycles
Stats::Formula SimpleExecContext::numIdleCycles
Definition at line 137 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numInst
Counter SimpleExecContext::numInst
PER-THREAD STATS.
Definition at line 82 of file exec_context.hh.
Referenced by BaseSimpleCPU::countInst(), and BaseSimpleCPU::preExecute().
numInsts
Stats::Scalar SimpleExecContext::numInsts
Definition at line 83 of file exec_context.hh.
Referenced by BaseSimpleCPU::countInst(), and BaseSimpleCPU::regStats().
numIntAluAccesses
Stats::Scalar SimpleExecContext::numIntAluAccesses
Definition at line 88 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numIntInsts
Stats::Scalar SimpleExecContext::numIntInsts
Definition at line 103 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numIntRegReads
Stats::Scalar SimpleExecContext::numIntRegReads
Definition at line 112 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numIntRegWrites
Stats::Scalar SimpleExecContext::numIntRegWrites
Definition at line 113 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numLoad
Counter SimpleExecContext::numLoad
Definition at line 143 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute().
numLoadInsts
Stats::Scalar SimpleExecContext::numLoadInsts
Definition at line 133 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numMemRefs
Stats::Scalar SimpleExecContext::numMemRefs
Definition at line 132 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numOp
Counter SimpleExecContext::numOp
Definition at line 84 of file exec_context.hh.
Referenced by BaseSimpleCPU::countInst().
numOps
Stats::Scalar SimpleExecContext::numOps
Definition at line 85 of file exec_context.hh.
Referenced by BaseSimpleCPU::countInst(), and BaseSimpleCPU::regStats().
numPredictedBranches
Stats::Scalar SimpleExecContext::numPredictedBranches
Number of branches predicted as taken.
Definition at line 161 of file exec_context.hh.
Referenced by BaseSimpleCPU::preExecute(), and BaseSimpleCPU::regStats().
numStoreInsts
Stats::Scalar SimpleExecContext::numStoreInsts
Definition at line 134 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numVecAluAccesses
Stats::Scalar SimpleExecContext::numVecAluAccesses
Definition at line 94 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numVecInsts
Stats::Scalar SimpleExecContext::numVecInsts
Definition at line 109 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
numVecPredRegReads
Stats::Scalar SimpleExecContext::numVecPredRegReads mutable
Definition at line 124 of file exec_context.hh.
numVecPredRegWrites
Stats::Scalar SimpleExecContext::numVecPredRegWrites
Definition at line 125 of file exec_context.hh.
numVecRegReads
Stats::Scalar SimpleExecContext::numVecRegReads mutable
Definition at line 120 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
numVecRegWrites
Stats::Scalar SimpleExecContext::numVecRegWrites
Definition at line 121 of file exec_context.hh.
Referenced by BaseSimpleCPU::regStats().
predPC
TheISA::PCState SimpleExecContext::predPC
Definition at line 77 of file exec_context.hh.
Referenced by BaseSimpleCPU::advancePC(), and BaseSimpleCPU::preExecute().
statExecutedInstType
Stats::Vector SimpleExecContext::statExecutedInstType
Definition at line 167 of file exec_context.hh.
Referenced by BaseSimpleCPU::postExecute(), and BaseSimpleCPU::regStats().
stayAtPC
bool SimpleExecContext::stayAtPC
Definition at line 74 of file exec_context.hh.
Referenced by TimingSimpleCPU::advanceInst(), AtomicSimpleCPU::isCpuDrained(), TimingSimpleCPU::isCpuDrained(), BaseSimpleCPU::preExecute(), TimingSimpleCPU::switchOut(), and AtomicSimpleCPU::tick().
thread
SimpleThread* SimpleExecContext::thread
Definition at line 68 of file exec_context.hh.
Referenced by BaseSimpleCPU::advancePC(), AtomicSimpleCPU::amoMem(), BaseSimpleCPU::checkForInterrupts(), BaseSimpleCPU::countInst(), TimingSimpleCPU::fetch(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), TimingSimpleCPU::initiateMemAMO(), TimingSimpleCPU::initiateMemRead(), AtomicSimpleCPU::isCpuDrained(), TimingSimpleCPU::isCpuDrained(), BaseSimpleCPU::postExecute(), BaseSimpleCPU::preExecute(), AtomicSimpleCPU::readMem(), TimingSimpleCPU::sendData(), BaseSimpleCPU::setupFetchRequest(), TimingSimpleCPU::switchOut(), AtomicSimpleCPU::tick(), AtomicSimpleCPU::writeMem(), and TimingSimpleCPU::writeMem().
The documentation for this class was generated from the following file:
cpu/simple/exec_context.hh