gem5: MSHR::TargetList Class Reference
MSHR::TargetList Class Reference
#include <mshr.hh>
Public Member Functions
TargetList ()
void updateFlags (PacketPtr pkt, Target::Source source, bool alloc_on_fill)
Use the provided packet and the source to update the flags of this TargetList.
void init (Addr blk_addr, Addr blk_size)
Reset state.
void resetFlags ()
void populateFlags ()
Goes through the list of targets and uses them to populate the flags of this TargetList.
void updateWriteFlags (PacketPtr pkt)
Add the specified packet in the TargetList.
bool isReset () const
Tests if the flags of this TargetList have their default values.
void add (PacketPtr pkt, Tick readyTime, Counter order, Target::Source source, bool markPending, bool alloc_on_fill)
Add the specified packet in the TargetList.
void replaceUpgrades ()
Convert upgrades to the equivalent request if the cache line they refer to would have been invalid (Upgrade -> ReadEx, SC* -> Fail).
void clearDownstreamPending ()
void clearDownstreamPending (iterator begin, iterator end)
bool trySatisfyFunctional (PacketPtr pkt)
void print (std::ostream &os, int verbosity, const std::string &prefix) const
bool isWholeLineWrite () const
Check if this list contains writes that cover an entire cache line.
Public Attributes
bool needsWritable
bool hasUpgrade
bool allocOnFill
Set when the response should allocate on fill.
bool hasFromCache
Determine whether there was at least one non-snooping target coming from another cache.
Public Attributes inherited from std::list< Target >
Target item
Dummy Item.
Private Attributes
Addr blkAddr
Address of the cache block for this list of targets.
Addr blkSize
Size of the cache block.
bool canMergeWrites
Indicates whether we can merge incoming write requests.
std::vector< char > writesBitmap
Track which bytes are written by requests in this target list.
Detailed Description
Definition at line 165 of file mshr.hh.
Constructor & Destructor Documentation
TargetList()
MSHR::TargetList::TargetList ()
Definition at line 71 of file mshr.cc.
Member Function Documentation
add()
void MSHR::TargetList::add (PacketPtr pkt, Tick readyTime, Counter order, Target::Source source, bool markPending, bool alloc_on_fill) inline
Add the specified packet in the TargetList.
This function stores information related to the added packet and updates accordingly the flags.
Parameters
pkt Packet considered for adding
readTime Tick at which the packet is processed by this cache
order A counter giving a unique id to each target
source Indicates the source agent of the packet
markPending Set for deferred targets or pending MSHRs
alloc_on_fill Whether it should allocate on a fill
Definition at line 115 of file mshr.cc.
References MSHR::downstreamPending, Packet::findNextSenderState(), and updateFlags().
Referenced by MSHR::allocate(), MSHR::allocateTarget(), and MSHR::handleSnoop().
clearDownstreamPending() [1/2]
void MSHR::TargetList::clearDownstreamPending ()
Definition at line 206 of file mshr.cc.
Referenced by MSHR::clearDownstreamPending(), MSHR::markInService(), MSHR::promoteIf(), and replaceUpgrades().
clearDownstreamPending() [2/2]
void MSHR::TargetList::clearDownstreamPending (iterator begin, iterator end)
init()
void MSHR::TargetList::init (Addr blk_addr, Addr blk_size) inline
Reset state.
Parameters
blk_addr Address of the cache block
blk_size Size of the cache block
Definition at line 197 of file mshr.hh.
References QueueEntry::blkAddr, and QueueEntry::blkSize.
Referenced by MSHR::allocate(), and MSHR::extractServiceableTargets().
isReset()
bool MSHR::TargetList::isReset () const inline
Tests if the flags of this TargetList have their default values.
Returns
True if the TargetList are reset, false otherwise.
Definition at line 269 of file mshr.hh.
References MSHR::clearDownstreamPending(), QueueEntry::Target::order, X86ISA::os, QueueEntry::Target::pkt, MSHR::print(), QueueEntry::Target::readyTime, MSHR::Target::source, and MSHR::trySatisfyFunctional().
Referenced by MSHR::deallocate().
isWholeLineWrite()
bool MSHR::TargetList::isWholeLineWrite () const inline
Check if this list contains writes that cover an entire cache line.
This is used as part of the miss-packet creation. Note that new requests may arrive after a miss-packet has been created, and for the corresponding fill we use the wasWholeLineWrite field.
Definition at line 308 of file mshr.hh.
References ArmISA::i.
Referenced by MSHR::isWholeLineWrite(), and MSHR::markInService().
populateFlags()
void MSHR::TargetList::populateFlags ()
Goes through the list of targets and uses them to populate the flags of this TargetList.
When the function returns the flags are consistent with the properties of packets in the list.
Definition at line 106 of file mshr.cc.
References resetFlags(), ArmISA::t, and updateFlags().
Referenced by MSHR::extractServiceableTargets(), MSHR::promoteDeferredTargets(), and MSHR::promoteIf().
print()
void MSHR::TargetList::print (std::ostream & os, int verbosity, const std::string & prefix) const
Definition at line 226 of file mshr.cc.
References ccprintf(), MSHR::Target::FromCPU, MSHR::Target::FromPrefetcher, MSHR::Target::FromSnoop, ArmISA::s, and ArmISA::t.
Referenced by MSHR::print().
replaceUpgrades()
void MSHR::TargetList::replaceUpgrades ()
Convert upgrades to the equivalent request if the cache line they refer to would have been invalid (Upgrade -> ReadEx, SC* -> Fail).
Used to rejig ordering between targets waiting on an MSHR.
Definition at line 171 of file mshr.cc.
References clearDownstreamPending(), MSHR::clearDownstreamPending(), hasUpgrade, replaceUpgrade(), and ArmISA::t.
Referenced by MSHR::handleSnoop().
resetFlags()
void MSHR::TargetList::resetFlags () inline
Definition at line 205 of file mshr.hh.
References MipsISA::fill.
Referenced by MSHR::deallocate(), and populateFlags().
trySatisfyFunctional()
bool MSHR::TargetList::trySatisfyFunctional (PacketPtr pkt)
Definition at line 213 of file mshr.cc.
References ArmISA::t, and Packet::trySatisfyFunctional().
Referenced by MSHR::trySatisfyFunctional().
updateFlags()
void MSHR::TargetList::updateFlags (PacketPtr pkt, Target::Source source, bool alloc_on_fill)
Use the provided packet and the source to update the flags of this TargetList.
Parameters
pkt Packet considered for the flag update
source Indicates the source of the packet
alloc_on_fill Whether the pkt would allocate on a fill
Definition at line 78 of file mshr.cc.
References allocOnFill, Packet::cmd, Packet::fromCache(), MSHR::Target::FromPrefetcher, MSHR::Target::FromSnoop, hasFromCache, hasUpgrade, Packet::isUpgrade(), needsWritable, Packet::needsWritable(), MemCmd::StoreCondReq, and updateWriteFlags().
Referenced by add(), and populateFlags().
updateWriteFlags()
void MSHR::TargetList::updateWriteFlags (PacketPtr pkt) inline
Add the specified packet in the TargetList.
This function stores information related to the added packet and updates accordingly the flags.
Parameters
pkt Packet considered for adding
Definition at line 231 of file mshr.hh.
References QueueEntry::blkSize, MipsISA::fill, Packet::getOffset(), Packet::getSize(), MSHR::isWholeLineWrite(), Packet::isWrite(), Request::LLSC, Request::MEM_SWAP, Request::MEM_SWAP_COND, Request::MMAPPED_IPR, ArmISA::offset, Request::PRIVILEGED, Packet::req, Request::SECURE, Request::STRICT_ORDER, and Request::UNCACHEABLE.
Referenced by updateFlags().
Member Data Documentation
allocOnFill
bool MSHR::TargetList::allocOnFill
Set when the response should allocate on fill.
Definition at line 171 of file mshr.hh.
Referenced by MSHR::allocOnFill(), MSHR::print(), and updateFlags().
blkAddr
Addr MSHR::TargetList::blkAddr private
Address of the cache block for this list of targets.
Definition at line 316 of file mshr.hh.
Referenced by MSHR::allocate(), MSHR::conflictAddr(), MSHR::extractServiceableTargets(), MSHR::matchBlockAddr(), MSHR::print(), and MSHR::trySatisfyFunctional().
blkSize
Addr MSHR::TargetList::blkSize private
Size of the cache block.
Definition at line 319 of file mshr.hh.
Referenced by MSHR::allocate(), MSHR::extractServiceableTargets(), MSHR::handleSnoop(), MSHR::matchBlockAddr(), MSHR::print(), and MSHR::trySatisfyFunctional().
canMergeWrites
bool MSHR::TargetList::canMergeWrites private
Indicates whether we can merge incoming write requests.
Definition at line 322 of file mshr.hh.
hasFromCache
bool MSHR::TargetList::hasFromCache
Determine whether there was at least one non-snooping target coming from another cache.
Definition at line 176 of file mshr.hh.
Referenced by MSHR::hasFromCache(), MSHR::print(), and updateFlags().
hasUpgrade
bool MSHR::TargetList::hasUpgrade
Definition at line 169 of file mshr.hh.
Referenced by replaceUpgrades(), and updateFlags().
needsWritable
bool MSHR::TargetList::needsWritable
Definition at line 168 of file mshr.hh.
Referenced by MSHR::handleSnoop(), MSHR::markInService(), MSHR::needsWritable(), MSHR::print(), MSHR::promoteWritable(), and updateFlags().
writesBitmap
std::vector<char> MSHR::TargetList::writesBitmap private
Track which bytes are written by requests in this target list.
Definition at line 331 of file mshr.hh.
The documentation for this class was generated from the following files:
mem/cache/mshr.hh
mem/cache/mshr.cc