gem5: sc_dt::sc_signed_bitref_r Class Reference
sc_dt::sc_signed_bitref_r Class Reference
#include <sc_signed.hh>
Public Member Functions
virtual ~sc_signed_bitref_r ()
sc_signed_bitref_r (const sc_signed_bitref_r &a)
int length () const
operator uint64 () const
bool operator! () const
bool operator~ () const
bool value () const
bool to_bool () const
virtual int concat_length (bool *xz_present_p) const
virtual uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_signed_bitref_r ()
void initialize (const sc_signed *obj_p, int index_)
Protected Attributes
int m_index
sc_signed * m_obj_p
Private Member Functions
const sc_signed_bitref_r & operator= (const sc_signed_bitref_r &)
Friends
class sc_signed
Detailed Description
Definition at line 670 of file sc_signed.hh.
Constructor & Destructor Documentation
sc_signed_bitref_r() [1/2]
sc_dt::sc_signed_bitref_r::sc_signed_bitref_r () inline protected
Definition at line 675 of file sc_signed.hh.
~sc_signed_bitref_r()
virtual sc_dt::sc_signed_bitref_r::~sc_signed_bitref_r () inline virtual
Definition at line 686 of file sc_signed.hh.
sc_signed_bitref_r() [2/2]
sc_dt::sc_signed_bitref_r::sc_signed_bitref_r (const sc_signed_bitref_r & a) inline
Definition at line 689 of file sc_signed.hh.
Member Function Documentation
concat_get_ctrl()
virtual bool sc_dt::sc_signed_bitref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 723 of file sc_signed.hh.
References BITS_PER_DIGIT.
concat_get_data()
virtual bool sc_dt::sc_signed_bitref_r::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 732 of file sc_signed.hh.
References BITS_PER_DIGIT.
concat_get_uint64()
virtual uint64 sc_dt::sc_signed_bitref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 718 of file sc_signed.hh.
concat_length()
virtual int sc_dt::sc_signed_bitref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 710 of file sc_signed.hh.
initialize()
void sc_dt::sc_signed_bitref_r::initialize (const sc_signed * obj_p, int index_) inline protected
Definition at line 678 of file sc_signed.hh.
Referenced by sc_dt::sc_signed::bit(), and sc_dt::sc_signed::operator[]().
length()
int sc_dt::sc_signed_bitref_r::length () const inline
Definition at line 694 of file sc_signed.hh.
References sc_dt::operator~().
operator uint64()
sc_dt::sc_signed_bitref_r::operator uint64 () const
Definition at line 48 of file sc_signed.cc.
operator!()
bool sc_dt::sc_signed_bitref_r::operator! () const
Definition at line 54 of file sc_signed.cc.
operator=()
const sc_signed_bitref_r& sc_dt::sc_signed_bitref_r::operator= (const sc_signed_bitref_r &) private
operator~()
bool sc_dt::sc_signed_bitref_r::operator~ () const
Definition at line 60 of file sc_signed.cc.
print()
void sc_dt::sc_signed_bitref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 748 of file sc_signed.hh.
References X86ISA::os, and to_bool().
Referenced by sc_dt::operator<<().
to_bool()
bool sc_dt::sc_signed_bitref_r::to_bool () const inline
Definition at line 706 of file sc_signed.hh.
value()
bool sc_dt::sc_signed_bitref_r::value () const inline
Definition at line 704 of file sc_signed.hh.
Friends And Related Function Documentation
sc_signed
friend class sc_signed friend
Definition at line 672 of file sc_signed.hh.
Member Data Documentation
m_index
int sc_dt::sc_signed_bitref_r::m_index protected
Definition at line 751 of file sc_signed.hh.
m_obj_p
sc_signed* sc_dt::sc_signed_bitref_r::m_obj_p protected
Definition at line 752 of file sc_signed.hh.
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_signed.hh
systemc/dt/int/sc_signed.cc