gem5: X86ISA::SegDescriptorLimit Class Reference
X86ISA::SegDescriptorLimit Class Reference
#include <misc.hh>
Public Member Functions
uint32_t getter (const uint64_t &storage) const
void setter (uint64_t &storage, uint32_t limit)
Detailed Description
Definition at line 888 of file misc.hh.
Member Function Documentation
getter()
uint32_t X86ISA::SegDescriptorLimit::getter (const uint64_t & storage) const inline
Definition at line 892 of file misc.hh.
References bits(), X86ISA::limit, and X86ISA::mask.
setter()
void X86ISA::SegDescriptorLimit::setter (uint64_t & storage, uint32_t limit) inline
Definition at line 902 of file misc.hh.
References bits(), X86ISA::BitUnion64(), X86ISA::g, X86ISA::mask, panic_if, and replaceBits().
The documentation for this class was generated from the following file:
arch/x86/regs/misc.hh