gem5: sc_gem5::Object Class Reference
sc_gem5::Object Class Reference
#include <object.hh>
Public Member Functions
Object (sc_core::sc_object *_sc_obj)
Object (sc_core::sc_object *_sc_obj, const char *)
Object (sc_core::sc_object *_sc_obj, const Object &)
Object & operator= (const Object &)
virtual ~Object ()
const char * name () const
const char * basename () const
void print (std::ostream &=std::cout) const
void dump (std::ostream &=std::cout) const
const std::vector< sc_core::sc_object * > & get_child_objects () const
const std::vector< sc_core::sc_event * > & get_child_events () const
sc_core::sc_object * get_parent_object () const
bool add_attribute (sc_core::sc_attr_base &)
sc_core::sc_attr_base * get_attribute (const std::string &)
sc_core::sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_core::sc_attr_cltn & attr_cltn ()
const sc_core::sc_attr_cltn & attr_cltn () const
sc_core::sc_simcontext * simcontext () const
sc_core::sc_object * sc_obj ()
EventsIt addChildEvent (sc_core::sc_event *e)
void delChildEvent (sc_core::sc_event *e)
std::string pickUniqueName (std::string name)
Static Public Member Functions
static Object * getFromScObject (sc_core::sc_object *sc_obj)
Private Attributes
sc_core::sc_object * _sc_obj
std::string _basename
std::string _name
Objects children
Events events
sc_core::sc_object * parent
sc_core::sc_attr_cltn cltn
Detailed Description
Definition at line 49 of file object.hh.
Constructor & Destructor Documentation
Object() [1/3]
sc_gem5::Object::Object (sc_core::sc_object * _sc_obj)
Definition at line 88 of file object.cc.
Object() [2/3]
sc_gem5::Object::Object (sc_core::sc_object * _sc_obj, const char * obj_name)
Definition at line 90 of file object.cc.
References _basename, sc_core::sc_object::_gem5_object, _name, sc_gem5::allObjects, sc_core::sc_object::basename(), children, sc_gem5::Module::finish(), sc_core::sc_object::get_parent_object(), ArmISA::n, sc_gem5::newModule(), parent, sc_gem5::pickParentObj(), sc_gem5::pickUniqueName(), sc_core::sc_gen_unique_name(), sc_core::SC_ID_INSTANCE_EXISTS_, SC_REPORT_WARNING, and sc_gem5::topLevelObjects.
Object() [3/3]
sc_gem5::Object::Object (sc_core::sc_object * _sc_obj, const Object & arg)
Definition at line 130 of file object.cc.
~Object()
sc_gem5::Object::~Object () virtual
Definition at line 140 of file object.cc.
References sc_core::sc_object::_gem5_object, _name, sc_gem5::allObjects, children, sc_gem5::Event::clearParent(), MipsISA::event, sc_gem5::Event::getFromScEvent(), parent, and sc_gem5::topLevelObjects.
Member Function Documentation
add_attribute()
bool sc_gem5::Object::add_attribute (sc_core::sc_attr_base & attr)
Definition at line 202 of file object.cc.
References cltn, and sc_core::sc_attr_cltn::push_back().
Referenced by sc_core::sc_object::add_attribute().
addChildEvent()
EventsIt sc_gem5::Object::addChildEvent (sc_core::sc_event * e)
Definition at line 250 of file object.cc.
References ArmISA::e.
Referenced by sc_gem5::Event::Event(), and sc_obj().
attr_cltn() [1/2]
sc_core::sc_attr_cltn & sc_gem5::Object::attr_cltn ()
Definition at line 232 of file object.cc.
References cltn.
Referenced by sc_core::sc_object::attr_cltn().
attr_cltn() [2/2]
const sc_core::sc_attr_cltn & sc_gem5::Object::attr_cltn () const
Definition at line 238 of file object.cc.
References cltn.
basename()
const char * sc_gem5::Object::basename () const
Definition at line 166 of file object.cc.
References _basename.
Referenced by sc_core::sc_object::basename().
delChildEvent()
void sc_gem5::Object::delChildEvent (sc_core::sc_event * e)
Definition at line 256 of file object.cc.
References ArmISA::e.
Referenced by sc_gem5::Event::clearParent(), sc_obj(), and sc_gem5::Event::~Event().
dump()
void sc_gem5::Object::dump (std::ostream & out = std::cout) const
Definition at line 178 of file object.cc.
References _sc_obj, sc_core::sc_object::kind(), and name().
Referenced by sc_core::sc_object::dump().
get_attribute()
sc_core::sc_attr_base * sc_gem5::Object::get_attribute (const std::string & attr)
Definition at line 208 of file object.cc.
References ArmISA::attr, and cltn.
Referenced by sc_core::sc_object::get_attribute().
get_child_events()
const std::vector< sc_core::sc_event * > & sc_gem5::Object::get_child_events () const
Definition at line 191 of file object.cc.
References events.
Referenced by sc_core::sc_object::get_child_events().
get_child_objects()
const std::vector< sc_core::sc_object * > & sc_gem5::Object::get_child_objects () const
Definition at line 185 of file object.cc.
References children.
Referenced by sc_core::sc_object::get_child_objects().
get_parent_object()
sc_core::sc_object * sc_gem5::Object::get_parent_object () const
Definition at line 196 of file object.cc.
References parent.
Referenced by sc_core::sc_object::get_parent_object().
getFromScObject()
static Object* sc_gem5::Object::getFromScObject (sc_core::sc_object * sc_obj) inline static
Definition at line 83 of file object.hh.
References sc_core::sc_object::_gem5_object.
Referenced by sc_gem5::Event::clearParent(), sc_gem5::Event::Event(), sc_gem5::pickUniqueName(), and sc_gem5::Event::~Event().
name()
const char * sc_gem5::Object::name () const
Definition at line 160 of file object.cc.
References _name.
Referenced by dump(), sc_core::sc_object::name(), and print().
num_attributes()
int sc_gem5::Object::num_attributes () const
Definition at line 226 of file object.cc.
References cltn, and sc_core::sc_attr_cltn::size().
Referenced by sc_core::sc_object::num_attributes().
operator=()
Object & sc_gem5::Object::operator= (const Object &)
Definition at line 135 of file object.cc.
pickUniqueName()
std::string sc_gem5::Object::pickUniqueName (std::string name)
Definition at line 265 of file object.cc.
References X86ISA::base, children, and sc_core::sc_gen_unique_name().
Referenced by sc_gem5::pickUniqueName(), and sc_obj().
print()
void sc_gem5::Object::print (std::ostream & out = std::cout) const
Definition at line 172 of file object.cc.
References name().
Referenced by sc_core::sc_object::print().
remove_all_attributes()
void sc_gem5::Object::remove_all_attributes ()
Definition at line 220 of file object.cc.
References cltn, and sc_core::sc_attr_cltn::remove_all().
Referenced by sc_core::sc_object::remove_all_attributes().
remove_attribute()
sc_core::sc_attr_base * sc_gem5::Object::remove_attribute (const std::string & attr)
Definition at line 214 of file object.cc.
References cltn, and sc_core::sc_attr_cltn::remove().
Referenced by sc_core::sc_object::remove_attribute().
sc_obj()
sc_core::sc_object* sc_gem5::Object::sc_obj () inline
Definition at line 88 of file object.hh.
References _sc_obj, addChildEvent(), delChildEvent(), ArmISA::e, and pickUniqueName().
Referenced by sc_gem5::Module::finish(), and sc_gem5::pushParentModule().
simcontext()
sc_core::sc_simcontext * sc_gem5::Object::simcontext () const
Definition at line 244 of file object.cc.
References sc_core::sc_get_curr_simcontext().
Referenced by sc_core::sc_object::simcontext().
Member Data Documentation
_basename
std::string sc_gem5::Object::_basename private
Definition at line 98 of file object.hh.
Referenced by basename(), and Object().
_name
std::string sc_gem5::Object::_name private
Definition at line 99 of file object.hh.
Referenced by name(), Object(), and ~Object().
_sc_obj
sc_core::sc_object* sc_gem5::Object::_sc_obj private
Definition at line 96 of file object.hh.
Referenced by dump(), and sc_obj().
children
Objects sc_gem5::Object::children private
Definition at line 101 of file object.hh.
Referenced by get_child_objects(), Object(), pickUniqueName(), and ~Object().
cltn
sc_core::sc_attr_cltn sc_gem5::Object::cltn private
Definition at line 105 of file object.hh.
Referenced by add_attribute(), attr_cltn(), get_attribute(), num_attributes(), remove_all_attributes(), and remove_attribute().
events
Events sc_gem5::Object::events private
Definition at line 102 of file object.hh.
Referenced by get_child_events().
parent
sc_core::sc_object* sc_gem5::Object::parent private
Definition at line 103 of file object.hh.
Referenced by get_parent_object(), Object(), and ~Object().
The documentation for this class was generated from the following files:
systemc/core/object.hh
systemc/core/object.cc