gem5: FetchStage Class Reference
FetchStage Class Reference
#include <fetch_stage.hh>
Public Member Functions
FetchStage (const ComputeUnitParams *params)
~FetchStage ()
void init (ComputeUnit *cu)
void exec ()
void processFetchReturn (PacketPtr pkt)
void fetch (PacketPtr pkt, Wavefront *wave)
std::string name ()
void regStats ()
Public Attributes
Stats::Distribution instFetchInstReturned
Private Attributes
uint32_t numSIMDs
ComputeUnit * computeUnit
std::vector< FetchUnit > fetchUnit
std::string _name
Detailed Description
Definition at line 54 of file fetch_stage.hh.
Constructor & Destructor Documentation
FetchStage()
FetchStage::FetchStage (const ComputeUnitParams * params)
Definition at line 42 of file fetch_stage.cc.
References fetchUnit, ArmISA::j, and numSIMDs.
~FetchStage()
FetchStage::~FetchStage ()
Definition at line 51 of file fetch_stage.cc.
References fetchUnit.
Member Function Documentation
exec()
void FetchStage::exec ()
Definition at line 69 of file fetch_stage.cc.
References fetchUnit, ArmISA::j, and numSIMDs.
Referenced by ComputeUnit::exec().
fetch()
void FetchStage::fetch (PacketPtr pkt, Wavefront * wave)
Definition at line 93 of file fetch_stage.cc.
References fetchUnit, and Wavefront::simdId.
init()
void FetchStage::init (ComputeUnit * cu)
Definition at line 57 of file fetch_stage.cc.
References _name, computeUnit, fetchUnit, ArmISA::j, SimObject::name(), numSIMDs, and ComputeUnit::wfList.
Referenced by ComputeUnit::init().
name()
std::string FetchStage::name () inline
Definition at line 65 of file fetch_stage.hh.
References _name, and regStats().
Referenced by regStats().
processFetchReturn()
void FetchStage::processFetchReturn (PacketPtr pkt)
Definition at line 77 of file fetch_stage.cc.
References fetchUnit, instFetchInstReturned, Packet::req, safe_cast(), Stats::DistBase< Derived, Stor >::sample(), Packet::senderState, and ComputeUnit::SQCPort::SenderState::wavefront.
regStats()
void FetchStage::regStats ()
Definition at line 99 of file fetch_stage.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), Stats::Distribution::init(), instFetchInstReturned, name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
Referenced by name(), and ComputeUnit::regStats().
Member Data Documentation
_name
std::string FetchStage::_name private
Definition at line 76 of file fetch_stage.hh.
Referenced by init(), and name().
computeUnit
ComputeUnit* FetchStage::computeUnit private
Definition at line 71 of file fetch_stage.hh.
Referenced by init().
fetchUnit
std::vector<FetchUnit> FetchStage::fetchUnit private
Definition at line 75 of file fetch_stage.hh.
Referenced by exec(), fetch(), FetchStage(), init(), processFetchReturn(), and ~FetchStage().
instFetchInstReturned
Stats::Distribution FetchStage::instFetchInstReturned
Definition at line 67 of file fetch_stage.hh.
Referenced by processFetchReturn(), and regStats().
numSIMDs
uint32_t FetchStage::numSIMDs private
Definition at line 70 of file fetch_stage.hh.
Referenced by exec(), FetchStage(), and init().
The documentation for this class was generated from the following files:
gpu-compute/fetch_stage.hh
gpu-compute/fetch_stage.cc