gem5: X86ISA::StackTrace Class Reference
X86ISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Static Public Attributes
static const int user = 1
static const int console = 2
static const int unknown = 3
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 62 of file stacktrace.hh.
Constructor & Destructor Documentation
StackTrace() [1/2]
X86ISA::StackTrace::StackTrace ()
Definition at line 114 of file stacktrace.cc.
StackTrace() [2/2]
X86ISA::StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 119 of file stacktrace.cc.
References trace().
~StackTrace()
X86ISA::StackTrace::~StackTrace ()
Definition at line 125 of file stacktrace.cc.
Member Function Documentation
clear()
void X86ISA::StackTrace::clear () inline
Definition at line 81 of file stacktrace.hh.
decodePrologue()
bool X86ISA::StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) private
Definition at line 160 of file stacktrace.cc.
References X86ISA::addr, console, decodeSave(), decodeStack(), DPRINTFN, Stats::dump(), ThreadContext::getCpuPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), ArmISA::i, System::kernelSymtab, name(), SimObject::name(), X86ISA::pc, PortProxy::read(), X86ISA::reg, X86ISA::ReturnAddressReg, stack, tc, unknown, and user.
decodeSave()
bool X86ISA::StackTrace::decodeSave (MachInst inst, int & reg, int & disp) private
Definition at line 148 of file stacktrace.cc.
Referenced by decodePrologue().
decodeStack()
bool X86ISA::StackTrace::decodeStack (MachInst inst, int & disp) private
Definition at line 141 of file stacktrace.cc.
Referenced by decodePrologue().
dprintf()
void X86ISA::StackTrace::dprintf () inline
Definition at line 105 of file stacktrace.hh.
getstack()
const std::vector<Addr>& X86ISA::StackTrace::getstack () const inline
Definition at line 91 of file stacktrace.hh.
References X86ISA::stack.
isEntry()
bool X86ISA::StackTrace::isEntry (Addr addr) private
Definition at line 135 of file stacktrace.cc.
trace() [1/2]
void X86ISA::StackTrace::trace (ThreadContext * tc, bool is_call) private
Definition at line 130 of file stacktrace.cc.
Referenced by StackTrace().
trace() [2/2]
bool X86ISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 110 of file stacktrace.hh.
References StaticInst::isCall(), and StaticInst::isReturn().
valid()
bool X86ISA::StackTrace::valid () const inline
Definition at line 87 of file stacktrace.hh.
Member Data Documentation
console
const int X86ISA::StackTrace::console = 2 static
Definition at line 94 of file stacktrace.hh.
Referenced by decodePrologue().
stack
std::vector<Addr> X86ISA::StackTrace::stack private
Definition at line 66 of file stacktrace.hh.
Referenced by decodePrologue().
tc
ThreadContext* X86ISA::StackTrace::tc private
Definition at line 65 of file stacktrace.hh.
Referenced by decodePrologue().
unknown
const int X86ISA::StackTrace::unknown = 3 static
Definition at line 95 of file stacktrace.hh.
Referenced by decodePrologue().
user
const int X86ISA::StackTrace::user = 1 static
Definition at line 93 of file stacktrace.hh.
Referenced by decodePrologue().
The documentation for this class was generated from the following files:
arch/x86/stacktrace.hh
arch/x86/stacktrace.cc