gem5: TsunamiIO Class Reference
TsunamiIO Class Reference
Tsunami I/O device is a catch all for all the south bridge stuff we care to implement.
#include <tsunami_io.hh>
Classes
class RTC
Public Types
typedef TsunamiIOParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
Tick frequency () const
Return the freqency of the RTC.
TsunamiIO (const Params *p)
Initialize all the data for devices supported by Tsunami I/O.
const Params * params () const
Tick read (PacketPtr pkt) override
Pure virtual function that the device must implement.
Tick write (PacketPtr pkt) override
Pure virtual function that the device must implement.
void postPIC (uint8_t bitvector)
Post an PIC interrupt to the CPU via the CChip.
void clearPIC (uint8_t bitvector)
Clear a posted interrupt.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void startup () override
Start running.
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Attributes
uint8_t mask1
Mask of the PIC1.
uint8_t mask2
Mask of the PIC2.
uint8_t mode1
Mode of PIC1.
uint8_t mode2
Mode of PIC2.
uint8_t picr
Raw PIC interrupt register before masking.
bool picInterrupting
Is the pic interrupting right now or not.
Tsunami * tsunami
A pointer to the Tsunami device which be belong to.
Intel8254Timer pitimer
Intel 8253 Periodic Interval Timer.
RTC rtc
uint8_t rtcAddr
uint16_t timerData
The interval is set via two writes to the PIT.
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Tsunami I/O device is a catch all for all the south bridge stuff we care to implement.
Definition at line 52 of file tsunami_io.hh.
Member Typedef Documentation
Params
typedef TsunamiIOParams TsunamiIO::Params
Definition at line 113 of file tsunami_io.hh.
Constructor & Destructor Documentation
TsunamiIO()
TsunamiIO::TsunamiIO (const Params * p)
Initialize all the data for devices supported by Tsunami I/O.
Parameters
p pointer to Params struct
Definition at line 68 of file tsunami_io.cc.
References Tsunami::io, picInterrupting, picr, timerData, and tsunami.
Referenced by startup().
Member Function Documentation
clearPIC()
void TsunamiIO::clearPIC (uint8_t bitvector)
Clear a posted interrupt.
Parameters
bitvector interrupt to clear
Definition at line 242 of file tsunami_io.cc.
References Tsunami::cchip, TsunamiCChip::clearDRIR(), DPRINTF, mask1, picr, and tsunami.
Referenced by Tsunami::clearConsoleInt(), and params().
frequency()
Tick TsunamiIO::frequency () const
Return the freqency of the RTC.
Returns
interrupt rate of the RTC
Definition at line 81 of file tsunami_io.cc.
References SimClock::Frequency, and params().
Referenced by Tsunami::init(), and AlphaBackdoor::startup().
params()
const Params* TsunamiIO::params () const inline
Definition at line 121 of file tsunami_io.hh.
References SimObject::_params, clearPIC(), postPIC(), read(), MC146818::serialize(), MC146818::startup(), MC146818::unserialize(), and write().
Referenced by frequency().
postPIC()
void TsunamiIO::postPIC (uint8_t bitvector)
Post an PIC interrupt to the CPU via the CChip.
Parameters
bitvector interrupt to post.
Definition at line 231 of file tsunami_io.cc.
References Tsunami::cchip, DPRINTF, mask1, picr, TsunamiCChip::postDRIR(), and tsunami.
Referenced by params(), and Tsunami::postConsoleInt().
read()
Tick TsunamiIO::read (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a read command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 87 of file tsunami_io.cc.
References DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), mask1, mask2, Intel8254Timer::outputHigh(), panic, picr, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, pitimer, PORTB_SPKR_HIGH, Intel8254Timer::readCounter(), MC146818::readData(), rtc, rtcAddr, Packet::setLE(), TSDEV_CTRL_PORTB, TSDEV_PIC1_ISR, TSDEV_PIC1_MASK, TSDEV_PIC2_ISR, TSDEV_PIC2_MASK, TSDEV_RTC_DATA, TSDEV_TMR0_DATA, TSDEV_TMR1_DATA, and TSDEV_TMR2_DATA.
Referenced by params().
serialize()
void TsunamiIO::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 253 of file tsunami_io.cc.
References mask1, mask2, mode1, mode2, picInterrupting, picr, pitimer, rtc, rtcAddr, MC146818::serialize(), Intel8254Timer::serialize(), SERIALIZE_SCALAR, and timerData.
startup()
void TsunamiIO::startup () override virtual
Start running.
Reimplemented from SimObject.
Definition at line 287 of file tsunami_io.cc.
References pitimer, rtc, MC146818::startup(), Intel8254Timer::startup(), and TsunamiIO().
unserialize()
void TsunamiIO::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 270 of file tsunami_io.cc.
References mask1, mask2, mode1, mode2, picInterrupting, picr, pitimer, rtc, rtcAddr, timerData, MC146818::unserialize(), Intel8254Timer::unserialize(), and UNSERIALIZE_SCALAR.
write()
Tick TsunamiIO::write (PacketPtr pkt) override virtual
Pure virtual function that the device must implement.
Called when a write command is recieved by the port.
Parameters
pkt Packet describing this request
Returns
number of ticks it took to complete
Implements PioDevice.
Definition at line 150 of file tsunami_io.cc.
References Tsunami::cchip, TsunamiCChip::clearDRIR(), DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), Packet::makeAtomicResponse(), mask1, mask2, mode1, mode2, panic, picInterrupting, picr, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, pitimer, TsunamiCChip::postDRIR(), rtc, rtcAddr, TSDEV_CTRL_PORTB, TSDEV_DMA1_CMND, TSDEV_DMA1_MASK, TSDEV_DMA1_MMASK, TSDEV_DMA1_MODE, TSDEV_DMA1_RESET, TSDEV_DMA2_CMND, TSDEV_DMA2_MASK, TSDEV_DMA2_MMASK, TSDEV_DMA2_MODE, TSDEV_DMA2_RESET, TSDEV_KBD, TSDEV_PIC1_ACK, TSDEV_PIC1_MASK, TSDEV_PIC2_ACK, TSDEV_PIC2_MASK, TSDEV_RTC_ADDR, TSDEV_RTC_DATA, TSDEV_TMR0_DATA, TSDEV_TMR1_DATA, TSDEV_TMR2_DATA, TSDEV_TMR_CTRL, tsunami, Intel8254Timer::writeControl(), Intel8254Timer::writeCounter(), and MC146818::writeData().
Referenced by params().
Member Data Documentation
mask1
uint8_t TsunamiIO::mask1 protected
Mask of the PIC1.
Definition at line 72 of file tsunami_io.hh.
Referenced by clearPIC(), postPIC(), read(), serialize(), unserialize(), and write().
mask2
uint8_t TsunamiIO::mask2 protected
Mask of the PIC2.
Definition at line 75 of file tsunami_io.hh.
Referenced by read(), serialize(), unserialize(), and write().
mode1
uint8_t TsunamiIO::mode1 protected
Mode of PIC1.
Not used for anything
Definition at line 78 of file tsunami_io.hh.
Referenced by serialize(), unserialize(), and write().
mode2
uint8_t TsunamiIO::mode2 protected
Mode of PIC2.
Not used for anything
Definition at line 81 of file tsunami_io.hh.
Referenced by serialize(), unserialize(), and write().
picInterrupting
bool TsunamiIO::picInterrupting protected
Is the pic interrupting right now or not.
Definition at line 87 of file tsunami_io.hh.
Referenced by serialize(), TsunamiIO(), unserialize(), and write().
picr
uint8_t TsunamiIO::picr protected
Raw PIC interrupt register before masking.
Definition at line 84 of file tsunami_io.hh.
Referenced by clearPIC(), postPIC(), read(), serialize(), TsunamiIO(), unserialize(), and write().
pitimer
Intel8254Timer TsunamiIO::pitimer protected
Intel 8253 Periodic Interval Timer.
Definition at line 93 of file tsunami_io.hh.
Referenced by read(), serialize(), startup(), unserialize(), and write().
rtc
RTC TsunamiIO::rtc protected
Definition at line 95 of file tsunami_io.hh.
Referenced by read(), serialize(), startup(), unserialize(), and write().
rtcAddr
uint8_t TsunamiIO::rtcAddr protected
Definition at line 97 of file tsunami_io.hh.
Referenced by read(), serialize(), unserialize(), and write().
timerData
uint16_t TsunamiIO::timerData protected
The interval is set via two writes to the PIT.
This variable contains a flag as to how many writes have happened, and the time so far.
Definition at line 103 of file tsunami_io.hh.
Referenced by serialize(), TsunamiIO(), and unserialize().
tsunami
Tsunami* TsunamiIO::tsunami protected
A pointer to the Tsunami device which be belong to.
Definition at line 90 of file tsunami_io.hh.
Referenced by clearPIC(), postPIC(), TsunamiIO(), and write().
The documentation for this class was generated from the following files:
dev/alpha/tsunami_io.hh
dev/alpha/tsunami_io.cc