gem5: CoherentXBar::CoherentXBarSlavePort Class Reference
CoherentXBar::CoherentXBarSlavePort Class Reference
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
#include <coherent_xbar.hh>
Public Member Functions
CoherentXBarSlavePort (const std::string &_name, CoherentXBar &_xbar, PortID _id)
Public Member Functions inherited from QueuedSlavePort
QueuedSlavePort (const std::string &name, SimObject *owner, RespPacketQueue &resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
virtual ~QueuedSlavePort ()
void schedTimingResp (PacketPtr pkt, Tick when)
Schedule the sending of a timing response.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
bool recvTimingReq (PacketPtr pkt) override
Receive a timing request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Tick recvAtomic (PacketPtr pkt) override
Receive an atomic request packet from the peer.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Receive an atomic request packet from the peer, and optionally provide a backdoor to the data being accessed.
void recvFunctional (PacketPtr pkt) override
Receive a functional request packet from the peer.
AddrRangeList getAddrRanges () const override
Get a list of the non-overlapping address ranges the owner is responsible for.
Protected Member Functions inherited from QueuedSlavePort
void recvRespRetry ()
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Attributes
CoherentXBar & xbar
A reference to the crossbar to which this port belongs.
RespPacketQueue queue
A normal packet queue used to store responses.
Additional Inherited Members
Protected Attributes inherited from QueuedSlavePort
RespPacketQueue & respQueue
Packet queue used to store outgoing responses.
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
Declaration of the coherent crossbar slave port type, one will be instantiated for each of the master ports connecting to the crossbar.
Definition at line 90 of file coherent_xbar.hh.
Constructor & Destructor Documentation
CoherentXBarSlavePort()
CoherentXBar::CoherentXBarSlavePort::CoherentXBarSlavePort (const std::string & _name, CoherentXBar & _xbar, PortID _id) inline
Definition at line 103 of file coherent_xbar.hh.
Member Function Documentation
getAddrRanges()
AddrRangeList CoherentXBar::CoherentXBarSlavePort::getAddrRanges () const inline override protected virtual
Get a list of the non-overlapping address ranges the owner is responsible for.
All slave ports must override this function and return a populated list with at least one item.
Returns
a list of ranges responded to
Implements SlavePort.
Definition at line 142 of file coherent_xbar.hh.
References BaseXBar::getAddrRanges().
recvAtomic()
Tick CoherentXBar::CoherentXBarSlavePort::recvAtomic (PacketPtr pkt) inline override protected virtual
Receive an atomic request packet from the peer.
Implements AtomicResponseProtocol.
Definition at line 124 of file coherent_xbar.hh.
References CoherentXBar::recvAtomicBackdoor().
recvAtomicBackdoor()
Tick CoherentXBar::CoherentXBarSlavePort::recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & backdoor) inline override protected virtual
Receive an atomic request packet from the peer, and optionally provide a backdoor to the data being accessed.
Implements AtomicResponseProtocol.
Definition at line 130 of file coherent_xbar.hh.
References CoherentXBar::recvAtomicBackdoor().
Referenced by CoherentXBar::forwardTiming().
recvFunctional()
void CoherentXBar::CoherentXBarSlavePort::recvFunctional (PacketPtr pkt) inline override protected virtual
Receive a functional request packet from the peer.
Implements FunctionalResponseProtocol.
Definition at line 136 of file coherent_xbar.hh.
References CoherentXBar::recvFunctional().
Referenced by CoherentXBar::forwardAtomic().
recvTimingReq()
bool CoherentXBar::CoherentXBarSlavePort::recvTimingReq (PacketPtr pkt) inline override protected virtual
Receive a timing request from the peer.
Implements TimingResponseProtocol.
Definition at line 112 of file coherent_xbar.hh.
References CoherentXBar::recvTimingReq().
recvTimingSnoopResp()
bool CoherentXBar::CoherentXBarSlavePort::recvTimingSnoopResp (PacketPtr pkt) inline override protected virtual
Receive a timing snoop response from the peer.
Implements TimingResponseProtocol.
Definition at line 118 of file coherent_xbar.hh.
References CoherentXBar::recvTimingSnoopResp().
Member Data Documentation
queue
RespPacketQueue CoherentXBar::CoherentXBarSlavePort::queue private
A normal packet queue used to store responses.
Definition at line 99 of file coherent_xbar.hh.
xbar
CoherentXBar& CoherentXBar::CoherentXBarSlavePort::xbar private
A reference to the crossbar to which this port belongs.
Definition at line 96 of file coherent_xbar.hh.
The documentation for this class was generated from the following file:
mem/coherent_xbar.hh