gem5: Stats::DataWrap< Derived, InfoProxyType > Class Template Reference
Stats::DataWrap< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>
Public Types
typedef InfoProxyType< Derived > Info
Public Member Functions
const Info * info () const
DataWrap ()=delete
DataWrap (const DataWrap &)=delete
DataWrap & operator= (const DataWrap &)=delete
DataWrap (Group *parent, const char *name, const char *desc)
Derived & name (const std::string &name)
Set the name and marks this stat to print at the end of simulation.
const std::string & name () const
Derived & setSeparator (const std::string &_sep)
Set the character(s) used between the name and vector number on vectors, dist, etc.
const std::string & setSeparator () const
Derived & desc (const std::string &_desc)
Set the description and marks this stat to print at the end of simulation.
Derived & precision (int _precision)
Set the precision and marks this stat to print at the end of simulation.
Derived & flags (Flags _flags)
Set the flags and marks this stat to print at the end of simulation.
template<class Stat >
Derived & prereq (const Stat &prereq)
Set the prerequisite stat and marks this stat to print at the end of simulation.
Public Member Functions inherited from Stats::InfoAccess
InfoAccess ()
void reset ()
Reset the stat to the default state.
bool zero () const
bool check () const
Check that this stat has been set up properly and is ready for use.
Protected Member Functions
Derived & self ()
Info * info ()
Protected Member Functions inherited from Stats::InfoAccess
void setInfo (Group *parent, Info *info)
Set up an info class for this statistic.
void setParams (const StorageParams *params)
Save Storage class parameters if any.
void setInit ()
Save Storage class parameters if any.
Info * info ()
Grab the information class for this statistic.
const Info * info () const
Grab the information class for this statistic.
Detailed Description
template<class Derived, template< class > class InfoProxyType>
class Stats::DataWrap< Derived, InfoProxyType >
Definition at line 228 of file statistics.hh.
Member Typedef Documentation
Info
template<class Derived, template< class > class InfoProxyType> typedef InfoProxyType<Derived> Stats::DataWrap< Derived, InfoProxyType >::Info
Definition at line 231 of file statistics.hh.
Constructor & Destructor Documentation
DataWrap() [1/3]
template<class Derived, template< class > class InfoProxyType> Stats::DataWrap< Derived, InfoProxyType >::DataWrap () delete
DataWrap() [2/3]
template<class Derived, template< class > class InfoProxyType> Stats::DataWrap< Derived, InfoProxyType >::DataWrap (const DataWrap< Derived, InfoProxyType > &) delete
DataWrap() [3/3]
template<class Derived, template< class > class InfoProxyType> Stats::DataWrap< Derived, InfoProxyType >::DataWrap (Group * parent, const char * name, const char * desc) inline
Definition at line 256 of file statistics.hh.
Member Function Documentation
desc()
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::desc (const std::string & _desc) inline
Set the description and marks this stat to print at the end of simulation.
Parameters
desc The new description.
Returns
A reference to this stat.
Definition at line 312 of file statistics.hh.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::desc(), Stats::Global::Global(), GpuDispatcher::GpuDispatcher(), StackDistProbe::regStats(), EtherDevice::regStats(), MemFootprintProbe::regStats(), TAGEBase::regStats(), FetchStage::regStats(), Profiler::regStats(), MemTest::regStats(), ExecStage::regStats(), BPredUnit::regStats(), LocalMemPipeline::regStats(), Minor::MinorStats::regStats(), BaseKvmCPU::regStats(), PowerModelState::regStats(), SMMUv3BaseCache::regStats(), AlphaISA::TLB::regStats(), ThermalDomain::regStats(), AbstractController::regStats(), Ticked::regStats(), BaseDictionaryCompressor::regStats(), MemDepUnit< MemDepPred, Impl >::regStats(), GPUCoalescer::regStats(), RiscvISA::TLB::regStats(), Prefetcher::regStats(), MipsISA::TLB::regStats(), Process::regStats(), DefaultDecode< Impl >::regStats(), GlobalMemPipeline::regStats(), CacheMemory::regStats(), MessageBuffer::regStats(), InstructionQueue< Impl >::regStats(), PowerModel::regStats(), DefaultRename< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultIEW< Impl >::regStats(), TLBCoalescer::regStats(), FlashDevice::regStats(), DefaultCommit< Impl >::regStats(), X86ISA::TLB::regStats(), BaseCacheCompressor::regStats(), SMMUv3::regStats(), PowerISA::TLB::regStats(), ElasticTrace::regStats(), FullO3CPU< O3CPUImpl >::regStats(), CopyEngine::regStats(), QueuedPrefetcher::regStats(), SnoopFilter::regStats(), Minor::Fetch2::regStats(), X86ISA::GpuTLB::regStats(), DefaultFetch< Impl >::regStats(), LSQUnit< Impl >::regStats(), QoS::MemSinkCtrl::regStats(), LoopPredictor::regStats(), StatisticalCorrector::regStats(), ROB< Impl >::regStats(), IdeDisk::regStats(), Sinic::Device::regStats(), BaseCPU::regStats(), WalkCache::regStats(), SimpleCache::regStats(), Wavefront::regStats(), BasePrefetcher::regStats(), ComputeUnit::regStats(), ArmISA::TLB::regStats(), TraceCPU::FixedRetryGen::regStats(), ArmISA::TableWalker::regStats(), UFSHostDevice::regStats(), TraceCPU::regStats(), and AlphaISA::Kernel::Statistics::Statistics().
flags()
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::flags (Flags _flags) inline
Set the flags and marks this stat to print at the end of simulation.
Parameters
f The new flags.
Returns
A reference to this stat.
Definition at line 336 of file statistics.hh.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::flags(), CommMonitor::MonitorStats::MonitorStats(), StackDistProbe::regStats(), MemFootprintProbe::regStats(), Profiler::regStats(), Switch::regStats(), Minor::MinorStats::regStats(), SMMUv3BaseCache::regStats(), AbstractController::regStats(), Router::regStats(), GarnetNetwork::regStats(), BaseTags::BaseTagStats::regStats(), CacheMemory::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), MessageBuffer::regStats(), InstructionQueue< Impl >::regStats(), DefaultRename< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultIEW< Impl >::regStats(), FlashDevice::regStats(), DefaultCommit< Impl >::regStats(), AbstractMemory::MemStats::regStats(), SMMUv3::regStats(), FullO3CPU< O3CPUImpl >::regStats(), CopyEngine::regStats(), Minor::Fetch2::regStats(), DefaultFetch< Impl >::regStats(), ClockedObject::ClockedObjectStats::regStats(), WalkCache::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), UFSHostDevice::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), and AlphaISA::Kernel::Statistics::Statistics().
info() [1/2]
template<class Derived, template< class > class InfoProxyType> Info* Stats::DataWrap< Derived, InfoProxyType >::info () inline protected
Definition at line 238 of file statistics.hh.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::prereq(), and Stats::DataWrapVec< VectorStandardDeviation, VectorDistInfoProxy >::subname().
info() [2/2]
template<class Derived, template< class > class InfoProxyType> const Info* Stats::DataWrap< Derived, InfoProxyType >::info () const inline
Definition at line 245 of file statistics.hh.
name() [1/2]
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::name (const std::string & name) inline
Set the name and marks this stat to print at the end of simulation.
Parameters
name The new name.
Returns
A reference to this stat.
Definition at line 279 of file statistics.hh.
Referenced by Stats::Global::Global(), GpuDispatcher::GpuDispatcher(), StackDistProbe::regStats(), EtherDevice::regStats(), MemFootprintProbe::regStats(), TAGEBase::regStats(), FetchStage::regStats(), Profiler::regStats(), Switch::regStats(), MemTest::regStats(), ExecStage::regStats(), BPredUnit::regStats(), LocalMemPipeline::regStats(), Throttle::regStats(), Minor::MinorStats::regStats(), BaseKvmCPU::regStats(), PowerModelState::regStats(), SMMUv3BaseCache::regStats(), AlphaISA::TLB::regStats(), ThermalDomain::regStats(), AbstractController::regStats(), Ticked::regStats(), BaseDictionaryCompressor::regStats(), Router::regStats(), MemDepUnit< MemDepPred, Impl >::regStats(), GarnetNetwork::regStats(), GPUCoalescer::regStats(), Prefetcher::regStats(), RiscvISA::TLB::regStats(), MipsISA::TLB::regStats(), Process::regStats(), DefaultDecode< Impl >::regStats(), GlobalMemPipeline::regStats(), CacheMemory::regStats(), MessageBuffer::regStats(), InstructionQueue< Impl >::regStats(), PowerModel::regStats(), DefaultRename< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultIEW< Impl >::regStats(), TLBCoalescer::regStats(), FlashDevice::regStats(), DefaultCommit< Impl >::regStats(), X86ISA::TLB::regStats(), BaseCacheCompressor::regStats(), SMMUv3::regStats(), PowerISA::TLB::regStats(), ElasticTrace::regStats(), FullO3CPU< O3CPUImpl >::regStats(), CopyEngine::regStats(), QueuedPrefetcher::regStats(), SnoopFilter::regStats(), Minor::Fetch2::regStats(), X86ISA::GpuTLB::regStats(), DefaultFetch< Impl >::regStats(), LSQUnit< Impl >::regStats(), QoS::MemSinkCtrl::regStats(), LoopPredictor::regStats(), StatisticalCorrector::regStats(), ROB< Impl >::regStats(), IdeDisk::regStats(), Sinic::Device::regStats(), BaseCPU::regStats(), WalkCache::regStats(), SimpleCache::regStats(), Wavefront::regStats(), BasePrefetcher::regStats(), ComputeUnit::regStats(), ArmISA::TLB::regStats(), TraceCPU::FixedRetryGen::regStats(), ArmISA::TableWalker::regStats(), UFSHostDevice::regStats(), TraceCPU::regStats(), and AlphaISA::Kernel::Statistics::Statistics().
name() [2/2]
template<class Derived, template< class > class InfoProxyType> const std::string& Stats::DataWrap< Derived, InfoProxyType >::name () const inline
Definition at line 286 of file statistics.hh.
operator=()
template<class Derived, template< class > class InfoProxyType> DataWrap& Stats::DataWrap< Derived, InfoProxyType >::operator= (const DataWrap< Derived, InfoProxyType > &) delete
precision()
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::precision (int _precision) inline
Set the precision and marks this stat to print at the end of simulation.
Parameters
_precision The new precision
Returns
A reference to this stat.
Definition at line 324 of file statistics.hh.
Referenced by Stats::Global::Global(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::precision(), EtherDevice::regStats(), BPredUnit::regStats(), Minor::MinorStats::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), AbstractMemory::MemStats::regStats(), FullO3CPU< O3CPUImpl >::regStats(), DRAMCtrl::DRAMStats::regStats(), and TraceCPU::regStats().
prereq()
template<class Derived, template< class > class InfoProxyType> template<class Stat > Derived& Stats::DataWrap< Derived, InfoProxyType >::prereq (const Stat & prereq) inline
Set the prerequisite stat and marks this stat to print at the end of simulation.
Parameters
prereq The prerequisite stat.
Returns
A reference to this stat.
Definition at line 350 of file statistics.hh.
Referenced by Stats::Global::Global(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::prereq(), EtherDevice::regStats(), Minor::MinorStats::regStats(), DefaultDecode< Impl >::regStats(), InstructionQueue< Impl >::regStats(), DefaultRename< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultCommit< Impl >::regStats(), AbstractMemory::MemStats::regStats(), FullO3CPU< O3CPUImpl >::regStats(), and DefaultFetch< Impl >::regStats().
self()
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::self () inline protected
Definition at line 234 of file statistics.hh.
setSeparator() [1/2]
template<class Derived, template< class > class InfoProxyType> Derived& Stats::DataWrap< Derived, InfoProxyType >::setSeparator (const std::string & _sep) inline
Set the character(s) used between the name and vector number on vectors, dist, etc.
Parameters
_sep The new separator string
Returns
A reference to this stat.
Definition at line 295 of file statistics.hh.
Referenced by Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::setSeparator().
setSeparator() [2/2]
template<class Derived, template< class > class InfoProxyType> const std::string& Stats::DataWrap< Derived, InfoProxyType >::setSeparator () const inline
Definition at line 300 of file statistics.hh.
The documentation for this class was generated from the following file:
base/statistics.hh