gem5: sc_dt::sc_uint_bitref_r Class Reference
sc_dt::sc_uint_bitref_r Class Reference
#include <sc_uint_base.hh>
Public Member Functions
sc_uint_bitref_r (const sc_uint_bitref_r &init)
virtual ~sc_uint_bitref_r ()
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
int length () const
operator uint64 () const
bool operator! () const
bool operator~ () const
uint64 value () const
bool to_bool () const
void print (::std::ostream &os=::std::cout) const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
sc_uint_bitref_r ()
void initialize (const sc_uint_base *obj_p, int index_)
Protected Attributes
int m_index
sc_uint_base * m_obj_p
Private Member Functions
sc_uint_bitref_r & operator= (const sc_uint_bitref_r &)
Friends
class sc_uint_base
class sc_uint_signal
Detailed Description
Definition at line 136 of file sc_uint_base.hh.
Constructor & Destructor Documentation
sc_uint_bitref_r() [1/2]
sc_dt::sc_uint_bitref_r::sc_uint_bitref_r (const sc_uint_bitref_r & init) inline
Definition at line 143 of file sc_uint_base.hh.
sc_uint_bitref_r() [2/2]
sc_dt::sc_uint_bitref_r::sc_uint_bitref_r () inline protected
Definition at line 148 of file sc_uint_base.hh.
~sc_uint_bitref_r()
virtual sc_dt::sc_uint_bitref_r::~sc_uint_bitref_r () inline virtual
Definition at line 160 of file sc_uint_base.hh.
Member Function Documentation
concat_get_ctrl()
virtual bool sc_dt::sc_uint_bitref_r::concat_get_ctrl (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 171 of file sc_uint_base.hh.
References BITS_PER_DIGIT.
concat_get_data()
virtual bool sc_dt::sc_uint_bitref_r::concat_get_data (sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 180 of file sc_uint_base.hh.
References BITS_PER_DIGIT.
concat_get_uint64()
virtual uint64 sc_dt::sc_uint_bitref_r::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 195 of file sc_uint_base.hh.
concat_length()
virtual int sc_dt::sc_uint_bitref_r::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 164 of file sc_uint_base.hh.
initialize()
void sc_dt::sc_uint_bitref_r::initialize (const sc_uint_base * obj_p, int index_) inline protected
Definition at line 152 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_base::bit(), and sc_dt::sc_uint_base::operator[]().
length()
int sc_dt::sc_uint_bitref_r::length () const inline
Definition at line 198 of file sc_uint_base.hh.
References sc_dt::operator~().
operator uint64()
sc_dt::sc_uint_bitref_r::operator uint64 () const inline
Definition at line 877 of file sc_uint_base.hh.
operator!()
bool sc_dt::sc_uint_bitref_r::operator! () const inline
Definition at line 883 of file sc_uint_base.hh.
operator=()
sc_uint_bitref_r& sc_dt::sc_uint_bitref_r::operator= (const sc_uint_bitref_r &) private
operator~()
bool sc_dt::sc_uint_bitref_r::operator~ () const inline
Definition at line 889 of file sc_uint_base.hh.
print()
void sc_dt::sc_uint_bitref_r::print (::std::ostream & os = ::std::cout) const inline
Definition at line 210 of file sc_uint_base.hh.
References X86ISA::os, and to_bool().
Referenced by sc_dt::operator<<().
to_bool()
bool sc_dt::sc_uint_bitref_r::to_bool () const inline
Definition at line 207 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_bitref::operator=().
value()
uint64 sc_dt::sc_uint_bitref_r::value () const inline
Definition at line 206 of file sc_uint_base.hh.
Friends And Related Function Documentation
sc_uint_base
friend class sc_uint_base friend
Definition at line 138 of file sc_uint_base.hh.
sc_uint_signal
friend class sc_uint_signal friend
Definition at line 139 of file sc_uint_base.hh.
Member Data Documentation
m_index
int sc_dt::sc_uint_bitref_r::m_index protected
Definition at line 213 of file sc_uint_base.hh.
m_obj_p
sc_uint_base* sc_dt::sc_uint_bitref_r::m_obj_p protected
Definition at line 214 of file sc_uint_base.hh.
The documentation for this class was generated from the following file:
systemc/ext/dt/int/sc_uint_base.hh