gem5: tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL > Class Template Reference
tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL > Class Template Reference
#include <multi_passthrough_target_socket.h>
Public Types
typedef TYPES::tlm_payload_type transaction_type
typedef TYPES::tlm_phase_type phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef sync_enum_type(MODULE::* nb_cb) (int, transaction_type &, phase_type &, sc_core::sc_time &)
typedef void(MODULE::* b_cb) (int, transaction_type &, sc_core::sc_time &)
typedef unsigned int(MODULE::* dbg_cb) (int, transaction_type &txn)
typedef bool(MODULE::* dmi_cb) (int, transaction_type &txn, tlm::tlm_dmi &dmi)
typedef multi_target_base< BUSWIDTH, TYPES, N, POL > base_type
typedef base_type::base_initiator_socket_type base_initiator_socket_type
Public Types inherited from tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >
typedef tlm::tlm_target_socket< BUSWIDTH, TYPES, N, POL > base_type
Public Types inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
typedef tlm_fw_transport_if< TYPES > fw_interface_type
typedef tlm_bw_transport_if< TYPES > bw_interface_type
typedef sc_core::sc_port< bw_interface_type, N, POL > port_type
typedef sc_core::sc_export< fw_interface_type > export_type
typedef tlm_base_initiator_socket_b< BUSWIDTH, fw_interface_type, bw_interface_type > base_initiator_socket_type
typedef tlm_base_target_socket_b< BUSWIDTH, fw_interface_type, bw_interface_type > base_type
Public Member Functions
multi_passthrough_target_socket (const char *name=default_name())
~multi_passthrough_target_socket ()
void check_export_binding ()
void register_nb_transport_fw (MODULE *mod, nb_cb cb)
void register_b_transport (MODULE *mod, b_cb cb)
void register_transport_dbg (MODULE *mod, dbg_cb cb)
void register_get_direct_mem_ptr (MODULE *mod, dmi_cb cb)
virtual tlm::tlm_fw_transport_if< TYPES > & get_base_interface ()
virtual const tlm::tlm_fw_transport_if< TYPES > & get_base_interface () const
virtual sc_core::sc_export< tlm::tlm_fw_transport_if< TYPES > > & get_base_export ()
virtual const sc_core::sc_export< tlm::tlm_fw_transport_if< TYPES > > & get_base_export () const
void end_of_elaboration ()
virtual void bind (base_type &s)
void operator() (base_type &s)
tlm::tlm_bw_transport_if< TYPES > * operator[] (int i)
unsigned int size ()
Public Member Functions inherited from tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >
virtual tlm::tlm_socket_category get_socket_category () const
virtual ~multi_target_base ()
multi_target_base ()
multi_target_base (const char *name)
Public Member Functions inherited from tlm::tlm_target_socket< BUSWIDTH, TYPES, N, POL >
tlm_target_socket ()
tlm_target_socket (const char *name)
virtual const char * kind () const
virtual std::type_index get_protocol_types () const
Public Member Functions inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
tlm_base_target_socket ()
tlm_base_target_socket (const char *name)
virtual void bind (base_initiator_socket_type &s)
virtual void bind (base_type &s)
virtual void bind (fw_interface_type &ifs)
void operator() (base_initiator_socket_type &s)
void operator() (base_type &s)
void operator() (fw_interface_type &s)
int size () const
bw_interface_type * operator-> ()
bw_interface_type * operator[] (int i)
virtual sc_core::sc_port_base & get_port_base ()
virtual sc_core::sc_port_base const & get_port_base () const
virtual sc_core::sc_export_base & get_export_base ()
virtual sc_core::sc_export_base const & get_export_base () const
virtual unsigned int get_bus_width () const
virtual sc_core::sc_port_b< tlm_bw_transport_if< TYPES > > & get_base_port ()
virtual sc_core::sc_port_b< tlm_bw_transport_if< TYPES > > const & get_base_port () const
Public Member Functions inherited from tlm::tlm_base_target_socket_b< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES > >
virtual ~tlm_base_target_socket_b ()
Public Member Functions inherited from sc_core::sc_export< tlm_fw_transport_if< TYPES > >
sc_export ()
sc_export (const char *n)
virtual ~sc_export ()
void operator() (tlm_fw_transport_if< TYPES > &i)
virtual void bind (tlm_fw_transport_if< TYPES > &i)
operator tlm_fw_transport_if< TYPES > & ()
operator const tlm_fw_transport_if< TYPES > & () const
tlm_fw_transport_if< TYPES > * operator-> ()
const tlm_fw_transport_if< TYPES > * operator-> () const
sc_interface * get_iterface () override
const sc_interface * get_interface () const override
Public Member Functions inherited from sc_core::sc_export_base
sc_export_base (const char *n)
~sc_export_base ()
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from tlm_utils::multi_to_multi_bind_base< TYPES >
virtual ~multi_to_multi_bind_base ()
Static Public Member Functions
static const char * default_name ()
Protected Member Functions
base_type * get_hierarch_bind ()
std::map< unsigned int, tlm::tlm_bw_transport_if< TYPES > * > & get_multi_binds ()
void set_hierarch_bind (base_type *h)
tlm::tlm_fw_transport_if< TYPES > * get_last_binder (tlm::tlm_bw_transport_if< TYPES > *other)
void disable_cb_bind ()
std::vector< callback_binder_fw< TYPES > * > & get_binders ()
Protected Member Functions inherited from tlm::tlm_base_socket_if
virtual ~tlm_base_socket_if ()
Protected Member Functions inherited from sc_core::sc_export< tlm_fw_transport_if< TYPES > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Member Functions inherited from tlm_utils::multi_target_base_if< TYPES >
virtual ~multi_target_base_if ()
Protected Member Functions inherited from tlm_utils::convenience_socket_base
virtual ~convenience_socket_base ()
void display_warning (const char *msg) const
void display_error (const char *msg) const
Protected Attributes
std::map< unsigned int, tlm::tlm_bw_transport_if< TYPES > * > m_multi_binds
std::vector< tlm::tlm_bw_transport_if< TYPES > * > m_sockets
std::vector< callback_binder_fw< TYPES > * > m_binders
base_type * m_hierarch_bind
bool m_eoe_disabled
bool m_export_callback_created
callback_binder_fw< TYPES >::nb_func_type m_nb_f
callback_binder_fw< TYPES >::b_func_type m_b_f
callback_binder_fw< TYPES >::debug_func_type m_dbg_f
callback_binder_fw< TYPES >::dmi_func_type m_dmi_f
Protected Attributes inherited from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >
port_type m_port
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >
Definition at line 43 of file multi_passthrough_target_socket.h.
Member Typedef Documentation
b_cb
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef void(MODULE::* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::b_cb) (int, transaction_type &, sc_core::sc_time &)
Definition at line 57 of file multi_passthrough_target_socket.h.
base_initiator_socket_type
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef base_type::base_initiator_socket_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::base_initiator_socket_type
Definition at line 65 of file multi_passthrough_target_socket.h.
base_type
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef multi_target_base<BUSWIDTH, TYPES, N, POL> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::base_type
Definition at line 62 of file multi_passthrough_target_socket.h.
dbg_cb
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef unsigned int(MODULE::* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::dbg_cb) (int, transaction_type &txn)
Definition at line 58 of file multi_passthrough_target_socket.h.
dmi_cb
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef bool(MODULE::* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::dmi_cb) (int, transaction_type &txn, tlm::tlm_dmi &dmi)
Definition at line 59 of file multi_passthrough_target_socket.h.
nb_cb
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sync_enum_type(MODULE::* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::nb_cb) (int, transaction_type &, phase_type &, sc_core::sc_time &)
Definition at line 55 of file multi_passthrough_target_socket.h.
phase_type
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef TYPES::tlm_phase_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::phase_type
Definition at line 51 of file multi_passthrough_target_socket.h.
sync_enum_type
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm::tlm_sync_enum tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::sync_enum_type
Definition at line 52 of file multi_passthrough_target_socket.h.
transaction_type
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef TYPES::tlm_payload_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::transaction_type
Definition at line 50 of file multi_passthrough_target_socket.h.
Constructor & Destructor Documentation
multi_passthrough_target_socket()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::multi_passthrough_target_socket (const char * name = default_name()) inline explicit
Definition at line 73 of file multi_passthrough_target_socket.h.
~multi_passthrough_target_socket()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::~multi_passthrough_target_socket () inline
Definition at line 78 of file multi_passthrough_target_socket.h.
Member Function Documentation
bind()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::bind (base_type & s) inline virtual
Definition at line 276 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::check_export_binding(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::operator()().
check_export_binding()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::check_export_binding () inline
Definition at line 86 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_b_transport(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_get_direct_mem_ptr(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_nb_transport_fw(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_transport_dbg().
default_name()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> static const char* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::default_name () inline static
Definition at line 68 of file multi_passthrough_target_socket.h.
disable_cb_bind()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::disable_cb_bind () inline protected
Definition at line 338 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::bind().
end_of_elaboration()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::end_of_elaboration () inline virtual
Implements sc_core::sc_export_base.
Definition at line 227 of file multi_passthrough_target_socket.h.
get_base_export() [1/2]
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual sc_core::sc_export<tlm::tlm_fw_transport_if<TYPES> >& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_base_export () inline virtual
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >.
Definition at line 212 of file multi_passthrough_target_socket.h.
get_base_export() [2/2]
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual const sc_core::sc_export<tlm::tlm_fw_transport_if<TYPES> >& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_base_export () const inline virtual
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >.
Definition at line 220 of file multi_passthrough_target_socket.h.
get_base_interface() [1/2]
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual tlm::tlm_fw_transport_if<TYPES>& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_base_interface () inline virtual
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >.
Definition at line 183 of file multi_passthrough_target_socket.h.
get_base_interface() [2/2]
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual const tlm::tlm_fw_transport_if<TYPES>& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_base_interface () const inline virtual
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, N, POL >.
Definition at line 202 of file multi_passthrough_target_socket.h.
get_binders()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::vector<callback_binder_fw<TYPES> *>& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_binders () inline protected virtual
Implements tlm_utils::multi_target_base_if< TYPES >.
Definition at line 340 of file multi_passthrough_target_socket.h.
get_hierarch_bind()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> base_type* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_hierarch_bind () inline protected virtual
Implements tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >.
Definition at line 314 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::size().
get_last_binder()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm::tlm_fw_transport_if<TYPES>* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_last_binder (tlm::tlm_bw_transport_if< TYPES > * other) inline protected virtual
Implements tlm_utils::multi_to_multi_bind_base< TYPES >.
Definition at line 328 of file multi_passthrough_target_socket.h.
get_multi_binds()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::map<unsigned int, tlm::tlm_bw_transport_if<TYPES> *>& tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::get_multi_binds () inline protected virtual
Implements tlm_utils::multi_target_base_if< TYPES >.
Definition at line 322 of file multi_passthrough_target_socket.h.
operator()()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::operator() (base_type & s) inline
Definition at line 295 of file multi_passthrough_target_socket.h.
operator[]()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm::tlm_bw_transport_if<TYPES>* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::operator[] (int i) inline
Definition at line 299 of file multi_passthrough_target_socket.h.
register_b_transport()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_b_transport (MODULE * mod, b_cb cb) inline
Definition at line 130 of file multi_passthrough_target_socket.h.
Referenced by MultiSocketSimpleSwitchAT::MultiSocketSimpleSwitchAT().
register_get_direct_mem_ptr()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_get_direct_mem_ptr (MODULE * mod, dmi_cb cb) inline
Definition at line 162 of file multi_passthrough_target_socket.h.
register_nb_transport_fw()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_nb_transport_fw (MODULE * mod, nb_cb cb) inline
Definition at line 114 of file multi_passthrough_target_socket.h.
Referenced by MultiSocketSimpleSwitchAT::MultiSocketSimpleSwitchAT().
register_transport_dbg()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::register_transport_dbg (MODULE * mod, dbg_cb cb) inline
Definition at line 146 of file multi_passthrough_target_socket.h.
set_hierarch_bind()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::set_hierarch_bind (base_type * h) inline protected virtual
Implements tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >.
Definition at line 326 of file multi_passthrough_target_socket.h.
size()
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::size () inline
Definition at line 306 of file multi_passthrough_target_socket.h.
Referenced by MultiSocketSimpleSwitchAT::dump_status(), and MultiSocketSimpleSwitchAT::start_of_simulation().
Member Data Documentation
m_b_f
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> callback_binder_fw<TYPES>::b_func_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_b_f protected
Definition at line 361 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_b_transport().
m_binders
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::vector<callback_binder_fw<TYPES> *> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_binders protected
Definition at line 348 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::check_export_binding(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_base_interface(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_binders(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_last_binder(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::~multi_passthrough_target_socket().
m_dbg_f
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> callback_binder_fw<TYPES>::debug_func_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_dbg_f protected
Definition at line 362 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_transport_dbg().
m_dmi_f
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> callback_binder_fw<TYPES>::dmi_func_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_dmi_f protected
Definition at line 363 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_get_direct_mem_ptr().
m_eoe_disabled
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_eoe_disabled protected
Definition at line 352 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::bind(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::disable_cb_bind(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration().
m_export_callback_created
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bool tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_export_callback_created protected
Definition at line 355 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::check_export_binding(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_base_interface().
m_hierarch_bind
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> base_type* tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_hierarch_bind protected
Definition at line 350 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_base_interface(), tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_hierarch_bind(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::set_hierarch_bind().
m_multi_binds
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::map<unsigned int, tlm::tlm_bw_transport_if<TYPES> *> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_multi_binds protected
Definition at line 336 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_last_binder(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::get_multi_binds().
m_nb_f
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> callback_binder_fw<TYPES>::nb_func_type tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_nb_f protected
Definition at line 360 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::register_nb_transport_fw().
m_sockets
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, unsigned int N = 0, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> std::vector<tlm::tlm_bw_transport_if<TYPES> *> tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >::m_sockets protected
Definition at line 345 of file multi_passthrough_target_socket.h.
Referenced by tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::end_of_elaboration(), and tlm_utils::multi_passthrough_target_socket< MultiSocketSimpleSwitchAT >::operator[]().
The documentation for this class was generated from the following file:
systemc/ext/tlm_utils/multi_passthrough_target_socket.h