gem5: tlm::tlm_event_finder_t< IF, T > Class Template Reference
tlm::tlm_event_finder_t< IF, T > Class Template Reference
#include <event_finder.hh>
Public Member Functions
tlm_event_finder_t (const sc_core::sc_port_base &port_, const sc_core::sc_event &(IF::*event_method_)(tlm_tag< T > *) const)
virtual ~tlm_event_finder_t ()
virtual const sc_core::sc_event & find_event (sc_core::sc_interface *if_p=nullptr) const
Public Member Functions inherited from sc_core::sc_event_finder
virtual const sc_port_base * port () const =0
Private Member Functions
tlm_event_finder_t ()
tlm_event_finder_t (const tlm_event_finder_t< IF, T > &)
tlm_event_finder_t< IF, T > & operator= (const tlm_event_finder_t< IF, T > &)
Private Attributes
const sc_core::sc_event &(IF::* m_event_method)(tlm_tag< T > *) const
Additional Inherited Members
Protected Member Functions inherited from sc_core::sc_event_finder
virtual ~sc_event_finder ()
Detailed Description
template<class IF, class T>
class tlm::tlm_event_finder_t< IF, T >
Definition at line 31 of file event_finder.hh.
Constructor & Destructor Documentation
tlm_event_finder_t() [1/3]
template<class IF, class T> tlm::tlm_event_finder_t< IF, T >::tlm_event_finder_t (const sc_core::sc_port_base & port_, const sc_core::sc_event &(IF::*)(tlm_tag< T > *) const event_method_) inline
Definition at line 34 of file event_finder.hh.
~tlm_event_finder_t()
template<class IF, class T> virtual tlm::tlm_event_finder_t< IF, T >::~tlm_event_finder_t () inline virtual
Definition at line 40 of file event_finder.hh.
References tlm::tlm_event_finder_t< IF, T >::find_event().
tlm_event_finder_t() [2/3]
template<class IF, class T> tlm::tlm_event_finder_t< IF, T >::tlm_event_finder_t () private
tlm_event_finder_t() [3/3]
template<class IF, class T> tlm::tlm_event_finder_t< IF, T >::tlm_event_finder_t (const tlm_event_finder_t< IF, T > &) private
Member Function Documentation
find_event()
template<class IF , class T > const sc_core::sc_event & tlm::tlm_event_finder_t< IF, T >::find_event (sc_core::sc_interface * if_p = nullptr) const inline virtual
Implements sc_core::sc_event_finder.
Definition at line 57 of file event_finder.hh.
References sc_core::sc_port_base::_gem5Interface(), sc_core::sc_port_base::kind(), tlm::tlm_event_finder_t< IF, T >::m_event_method, sc_core::sc_object::name(), Stats::none, sc_core::sc_event_finder::port(), sc_core::SC_ID_FIND_EVENT_, and SC_REPORT_ERROR.
Referenced by tlm::tlm_event_finder_t< IF, T >::~tlm_event_finder_t().
operator=()
template<class IF, class T> tlm_event_finder_t<IF, T>& tlm::tlm_event_finder_t< IF, T >::operator= (const tlm_event_finder_t< IF, T > &) private
Member Data Documentation
m_event_method
template<class IF, class T> const sc_core::sc_event&(IF::* tlm::tlm_event_finder_t< IF, T >::m_event_method) (tlm_tag< T > *) const private
Definition at line 46 of file event_finder.hh.
Referenced by tlm::tlm_event_finder_t< IF, T >::find_event().
The documentation for this class was generated from the following file:
systemc/ext/tlm_core/1/req_rsp/ports/event_finder.hh