gem5: BaseRegOperand Class Reference
BaseRegOperand Class Reference
#include <operand.hh>
Public Member Functions
bool init (unsigned opOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
bool init_from_vect (unsigned opOffset, const BrigObject *obj, int at, unsigned &maxRegIdx, char _regFileChar)
void initWithStrOffset (unsigned strOffset, const BrigObject *obj, unsigned &maxRegIdx, char _regFileChar)
unsigned int regIndex ()
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Public Attributes
unsigned regIdx
char regFileChar
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 103 of file operand.hh.
Member Function Documentation
init()
bool BaseRegOperand::init (unsigned opOffset, const BrigObject * obj, unsigned & maxRegIdx, char _regFileChar)
Definition at line 41 of file operand.cc.
References Brig::BRIG_KIND_OPERAND_REGISTER, DPRINTF, BrigObject::getOperand(), Brig::BrigBase::kind, Brig::BrigOperandRegister::regKind, and Brig::BrigOperandRegister::regNum.
Referenced by SRegOperand::init(), DRegOperand::init(), and CRegOperand::init().
init_from_vect()
bool BaseRegOperand::init_from_vect (unsigned opOffset, const BrigObject * obj, int at, unsigned & maxRegIdx, char _regFileChar)
Definition at line 141 of file operand.cc.
References Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_KIND_OPERAND_REGISTER, DPRINTF, Brig::BrigOperandOperandList::elements, BrigObject::getData(), BrigObject::getOperand(), Brig::BrigBase::kind, MipsISA::p, Brig::BrigOperandRegister::regKind, and Brig::BrigOperandRegister::regNum.
Referenced by SRegOperand::init_from_vect(), DRegOperand::init_from_vect(), and CRegOperand::init_from_vect().
initWithStrOffset()
void BaseRegOperand::initWithStrOffset (unsigned strOffset, const BrigObject * obj, unsigned & maxRegIdx, char _regFileChar)
Definition at line 176 of file operand.cc.
References fatal, BrigObject::getString(), SRegOperand::maxRegIdx, DRegOperand::maxRegIdx, CRegOperand::maxRegIdx, and name().
Referenced by SRegOperand::initWithStrOffset(), DRegOperand::initWithStrOffset(), and CRegOperand::initWithStrOffset().
regIndex()
unsigned int BaseRegOperand::regIndex () inline
Definition at line 117 of file operand.hh.
Member Data Documentation
regFileChar
char BaseRegOperand::regFileChar
Definition at line 107 of file operand.hh.
regIdx
unsigned BaseRegOperand::regIdx
Definition at line 106 of file operand.hh.
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc