gem5: AlphaISA::DtbFault Class Reference
AlphaISA::DtbFault Class Reference abstract
#include <faults.hh>
Public Member Functions
DtbFault (VAddr _vaddr, Request::Flags _reqFlags, uint64_t _flags)
FaultName name () const =0
FaultVect vect ()=0
FaultStat & countStat ()=0
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
Public Member Functions inherited from AlphaISA::AlphaFault
virtual ~AlphaFault ()
Public Member Functions inherited from FaultBase
virtual ~FaultBase ()
Protected Attributes
VAddr vaddr
Request::Flags reqFlags
uint64_t flags
Additional Inherited Members
Protected Member Functions inherited from AlphaISA::AlphaFault
virtual bool skipFaultingInstruction ()
virtual bool setRestartAddress ()
Detailed Description
Definition at line 132 of file faults.hh.
Constructor & Destructor Documentation
DtbFault()
AlphaISA::DtbFault::DtbFault (VAddr _vaddr, Request::Flags _reqFlags, uint64_t _flags) inline
Definition at line 140 of file faults.hh.
References AlphaISA::AlphaFault::countStat(), AlphaISA::AlphaFault::invoke(), FaultBase::name(), StaticInst::nullStaticInstPtr, and AlphaISA::AlphaFault::vect().
Member Function Documentation
countStat()
FaultStat& AlphaISA::DtbFault::countStat () pure virtual
Implements AlphaISA::AlphaFault.
Implemented in AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, and AlphaISA::NDtbMissFault.
invoke()
void AlphaISA::DtbFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from AlphaISA::AlphaFault.
Reimplemented in AlphaISA::NDtbMissFault.
Definition at line 150 of file faults.cc.
References FullSystem, AlphaISA::AlphaFault::invoke(), AlphaISA::IPR_MM_STAT, AlphaISA::IPR_MVPTBR, AlphaISA::IPR_VA, AlphaISA::IPR_VA_FORM, StaticInst::machInst, AlphaISA::Opcode(), Request::PREFETCH, AlphaISA::Ra(), ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscRegNoEffect(), MipsISA::vaddr, and AlphaISA::AlphaRequestFlags::VPTE.
Referenced by AlphaISA::NDtbMissFault::invoke().
name()
FaultName AlphaISA::DtbFault::name () const pure virtual
Implements FaultBase.
Implemented in AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, and AlphaISA::NDtbMissFault.
vect()
FaultVect AlphaISA::DtbFault::vect () pure virtual
Implements AlphaISA::AlphaFault.
Implemented in AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, and AlphaISA::NDtbMissFault.
Member Data Documentation
flags
uint64_t AlphaISA::DtbFault::flags protected
Definition at line 137 of file faults.hh.
reqFlags
Request::Flags AlphaISA::DtbFault::reqFlags protected
Definition at line 136 of file faults.hh.
vaddr
VAddr AlphaISA::DtbFault::vaddr protected
Definition at line 135 of file faults.hh.
The documentation for this class was generated from the following files:
arch/alpha/faults.hh
arch/alpha/faults.cc