gem5: Packet Class Reference
Packet Class Reference
A Packet is used to encapsulate a transfer between two objects in the memory system (e.g., the L1 and L2 cache).
#include <packet.hh>
Classes
class PrintReqState
Object used to maintain state of a PrintReq.
struct SenderState
A virtual base opaque structure used to hold state associated with the packet (e.g., an MSHR), specific to a SimObject that sees the packet.
Public Types
typedef uint32_t FlagsType
typedef ::Flags< FlagsType > Flags
typedef MemCmd::Command Command
Public Member Functions
void pushSenderState (SenderState *sender_state)
Push a new sender state to the packet and make the current sender state the predecessor of the new one.
SenderState * popSenderState ()
Pop the top of the state stack and return a pointer to it.
template<typename T >
T * findNextSenderState () const
Go through the sender state stack and return the first instance that is of type T (as determined by a dynamic_cast).
const std::string & cmdString () const
Return the string name of the cmd field (for debugging and tracing).
int cmdToIndex () const
Return the index of this command.
bool isRead () const
bool isWrite () const
bool isUpgrade () const
bool isRequest () const
bool isResponse () const
bool needsWritable () const
bool needsResponse () const
bool isInvalidate () const
bool isEviction () const
bool isClean () const
bool fromCache () const
bool isWriteback () const
bool hasData () const
bool hasRespData () const
bool isLLSC () const
bool isError () const
bool isPrint () const
bool isFlush () const
bool isWholeLineWrite (unsigned blk_size)
void setExpressSnoop ()
The express snoop flag is used for two purposes.
bool isExpressSnoop () const
void setResponderHadWritable ()
On responding to a snoop request (which only happens for Modified or Owned lines), make sure that we can transform an Owned response to a Modified one.
bool responderHadWritable () const
void copyResponderFlags (const PacketPtr pkt)
Copy the reponse flags from an input packet to this packet.
void setWriteThrough ()
A writeback/writeclean cmd gets propagated further downstream by the receiver when the flag is set.
void clearWriteThrough ()
bool writeThrough () const
void setSatisfied ()
Set when a request hits in a cache and the cache is not going to respond.
bool satisfied () const
void setSuppressFuncError ()
bool suppressFuncError () const
void setBlockCached ()
bool isBlockCached () const
void clearBlockCached ()
uint8_t qosValue () const
QoS Value getter Returns 0 if QoS value was never set (constructor default).
void qosValue (const uint8_t qos_value)
QoS Value setter Interface for setting QoS priority value of the packet.
MasterID masterId () const
void setBadAddress ()
void copyError (Packet *pkt)
Addr getAddr () const
void setAddr (Addr _addr)
Update the address of this packet mid-transaction.
unsigned getSize () const
AddrRange getAddrRange () const
Get address range to which this packet belongs.
Addr getOffset (unsigned int blk_size) const
Addr getBlockAddr (unsigned int blk_size) const
bool isSecure () const
AtomicOpFunctor * getAtomicOp () const
Accessor function to atomic op.
bool isAtomicOp () const
void convertScToWrite ()
It has been determined that the SC packet should successfully update memory.
void convertLlToRead ()
When ruby is in use, Ruby will monitor the cache line and the phys memory should treat LL ops as normal reads.
Packet (const RequestPtr &_req, MemCmd _cmd)
Constructor.
Packet (const RequestPtr &_req, MemCmd _cmd, int _blkSize, PacketId _id=0)
Alternate constructor if you are trying to create a packet with a request that is for a whole block, not the address from the req.
Packet (const PacketPtr pkt, bool clear_flags, bool alloc_data)
Alternate constructor for copying a packet.
~Packet ()
clean up packet variables
void makeResponse ()
Take a request packet and modify it in place to be suitable for returning as a response to that request.
void makeAtomicResponse ()
void makeTimingResponse ()
void setFunctionalResponseStatus (bool success)
void setSize (unsigned size)
bool matchBlockAddr (const Addr addr, const bool is_secure, const int blk_size) const
Check if packet corresponds to a given block-aligned address and address space.
bool matchBlockAddr (const PacketPtr pkt, const int blk_size) const
Check if this packet refers to the same block-aligned address and address space as another packet.
bool matchAddr (const Addr addr, const bool is_secure) const
Check if packet corresponds to a given address and address space.
bool matchAddr (const PacketPtr pkt) const
Check if this packet refers to the same address and address space as another packet.
template<typename T >
T getRaw () const
Get the data in the packet without byte swapping.
template<typename T >
void setRaw (T v)
Set the value in the data pointer to v without byte swapping.
bool trySatisfyFunctional (PacketPtr other)
Check a functional request against a memory value stored in another packet (i.e.
bool mustCheckAbove () const
Does the request need to check for cached copies of the same block in the memory hierarchy above.
bool isCleanEviction () const
Is this packet a clean eviction, including both actual clean evict packets, but also clean writebacks.
bool isMaskedWrite () const
bool trySatisfyFunctional (Printable *obj, Addr base, bool is_secure, int size, uint8_t *_data)
Check a functional request against a memory value represented by a base/size pair and an associated data array.
void pushLabel (const std::string &lbl)
Push label for PrintReq (safe to call unconditionally).
void popLabel ()
Pop label for PrintReq (safe to call unconditionally).
void print (std::ostream &o, int verbosity=0, const std::string &prefix="") const
std::string print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
void setCacheResponding ()
Snoop flags.
bool cacheResponding () const
void setHasSharers ()
On fills, the hasSharers flag is used by the caches in combination with the cacheResponding flag, as clarified above.
bool hasSharers () const
Data accessor mehtods
template<typename T >
void dataStatic (T *p)
Set the data pointer to the following value that should not be freed.
template<typename T >
void dataStaticConst (const T *p)
Set the data pointer to the following value that should not be freed.
template<typename T >
void dataDynamic (T *p)
Set the data pointer to a value that should have delete [] called on it.
template<typename T >
T * getPtr ()
get a pointer to the data ptr.
template<typename T >
const T * getConstPtr () const
template<typename T >
T getBE () const
Get the data in the packet byte swapped from big endian to host endian.
template<typename T >
T getLE () const
Get the data in the packet byte swapped from little endian to host endian.
template<typename T >
T get (ByteOrder endian) const
Get the data in the packet byte swapped from the specified endianness.
template<typename T >
void setBE (T v)
Set the value in the data pointer to v as big endian.
template<typename T >
void setLE (T v)
Set the value in the data pointer to v as little endian.
template<typename T >
void set (T v, ByteOrder endian)
Set the value in the data pointer to v using the specified endianness.
uint64_t getUintX (ByteOrder endian) const
Get the data in the packet byte swapped from the specified endianness and zero-extended to 64 bits.
void setUintX (uint64_t w, ByteOrder endian)
Set the value in the word w after truncating it to the length of the packet and then byteswapping it to the desired endianness.
void setData (const uint8_t *p)
Copy data into the packet from the provided pointer.
void setDataFromBlock (const uint8_t *blk_data, int blkSize)
Copy data into the packet from the provided block pointer, which is aligned to the given block size.
void writeData (uint8_t *p) const
Copy data from the packet to the memory at the provided pointer.
void writeDataToBlock (uint8_t *blk_data, int blkSize) const
Copy data from the packet to the provided block pointer, which is aligned to the given block size.
void deleteData ()
delete the data pointed to in the data pointer.
void allocate ()
Allocate memory for the packet.
Public Member Functions inherited from Printable
Printable ()
virtual ~Printable ()
Static Public Member Functions
static MemCmd makeReadCmd (const RequestPtr &req)
Generate the appropriate read MemCmd based on the Request flags.
static MemCmd makeWriteCmd (const RequestPtr &req)
Generate the appropriate write MemCmd based on the Request flags.
static PacketPtr createRead (const RequestPtr &req)
Constructor-like methods that return Packets based on Request objects.
static PacketPtr createWrite (const RequestPtr &req)
Public Attributes
MemCmd cmd
The command field of the packet.
const PacketId id
RequestPtr req
A pointer to the original request.
uint32_t headerDelay
The extra delay from seeing the packet until the header is transmitted.
uint32_t snoopDelay
Keep track of the extra delay incurred by snooping upwards before sending a request down the memory system.
uint32_t payloadDelay
The extra pipelining delay from seeing the packet until the end of payload is transmitted by the component that provided it (if any).
SenderState * senderState
This packet's sender state.
Private Types
enum : FlagsType {
COPY_FLAGS = 0x0000003F, RESPONDER_FLAGS = 0x00000009, HAS_SHARERS = 0x00000001, EXPRESS_SNOOP = 0x00000002,
RESPONDER_HAD_WRITABLE = 0x00000004, CACHE_RESPONDING = 0x00000008, WRITE_THROUGH = 0x00000010, SATISFIED = 0x00000020,
VALID_ADDR = 0x00000100, VALID_SIZE = 0x00000200, STATIC_DATA = 0x00001000, DYNAMIC_DATA = 0x00002000,
SUPPRESS_FUNC_ERROR = 0x00008000, BLOCK_CACHED = 0x00010000
}
Private Attributes
Flags flags
PacketDataPtr data
A pointer to the data being transferred.
Addr addr
The address of the request.
bool _isSecure
True if the request targets the secure memory space.
unsigned size
The size of the request or transfer.
std::vector< bool > bytesValid
Track the bytes found that satisfy a functional read.
uint8_t _qosValue
Detailed Description
A Packet is used to encapsulate a transfer between two objects in the memory system (e.g., the L1 and L2 cache).
(In contrast, a single Request travels all the way from the requester to the ultimate destination and back, possibly being conveyed by several different Packets along the way.)
Definition at line 255 of file packet.hh.
Member Typedef Documentation
Command
typedef MemCmd::Command Packet::Command
Definition at line 319 of file packet.hh.
Flags
typedef ::Flags<FlagsType> Packet::Flags
Definition at line 259 of file packet.hh.
FlagsType
typedef uint32_t Packet::FlagsType
Definition at line 258 of file packet.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum : FlagsType private
Enumerator
COPY_FLAGS
RESPONDER_FLAGS
HAS_SHARERS
EXPRESS_SNOOP
Special timing-mode atomic snoop for multi-level coherence.
RESPONDER_HAD_WRITABLE
Allow a responding cache to inform the cache hierarchy that it had a writable copy before responding.
See setResponderHadWritable below.
CACHE_RESPONDING
WRITE_THROUGH
SATISFIED
VALID_ADDR
Are the 'addr' and 'size' fields valid?
VALID_SIZE
STATIC_DATA
Is the data pointer set to a value that shouldn't be freed when the packet is destroyed?
DYNAMIC_DATA
The data pointer points to a value that should be freed when the packet is destroyed.
The pointer is assumed to be pointing to an array, and delete [] is consequently called
SUPPRESS_FUNC_ERROR
suppress the error if this packet encounters a functional access failure.
BLOCK_CACHED
Definition at line 263 of file packet.hh.
Constructor & Destructor Documentation
Packet() [1/3]
Packet::Packet (const RequestPtr & _req, MemCmd _cmd) inline
Constructor.
Note that a Request object must be constructed first, but the Requests's physical address and size fields need not be valid. The command must be supplied.
Definition at line 796 of file packet.hh.
References Flags< T >::set().
Packet() [2/3]
Packet::Packet (const RequestPtr & _req, MemCmd _cmd, int _blkSize, PacketId _id = 0) inline
Alternate constructor if you are trying to create a packet with a request that is for a whole block, not the address from the req.
this allows for overriding the size/addr of the req.
Definition at line 818 of file packet.hh.
References Flags< T >::set().
Packet() [3/3]
Packet::Packet (const PacketPtr pkt, bool clear_flags, bool alloc_data) inline
Alternate constructor for copying a packet.
Copy all fields except if the original packet's data was dynamic, don't copy that, as we can't guarantee that the new packet's lifetime is less than that of the original packet. In this case the new packet should allocate its own data.
Definition at line 840 of file packet.hh.
References data, flags, Flags< T >::isSet(), and Flags< T >::set().
~Packet()
Packet::~Packet () inline
clean up packet variables
Definition at line 927 of file packet.hh.
Member Function Documentation
allocate()
void Packet::allocate () inline
Allocate memory for the packet.
Definition at line 1232 of file packet.hh.
References MemCmd::hasData(), Flags< T >::noneSet(), and Flags< T >::set().
Referenced by SimpleCache::accessTiming(), X86ISA::buildIntPacket(), Cache::cleanEvictBlk(), Cache::createMissPacket(), QueuedPrefetcher::DeferredPacket::createPkt(), SeriesRequestGenerator::initiate(), InvalidateGenerator::initiate(), Minor::makePacketForRequest(), GpuDispatcher::read(), replaceUpgrade(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
cacheResponding()
bool Packet::cacheResponding () const inline
Definition at line 591 of file packet.hh.
References Flags< T >::isSet().
Referenced by AbstractMemory::access(), copyResponderFlags(), CoherentXBar::forwardAtomic(), BaseCache::handleFill(), Cache::handleSnoop(), Cache::isCachedAbove(), SnoopFilter::lookupRequest(), NoncoherentCache::recvAtomic(), Cache::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), SimpleMemory::recvAtomic(), DRAMSim2::recvAtomic(), Bridge::BridgeSlavePort::recvAtomic(), QoS::MemSinkCtrl::recvAtomic(), CommMonitor::recvAtomic(), DRAMCtrl::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor(), SimpleTimingPort::recvTimingReq(), NoncoherentCache::recvTimingReq(), HMCController::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), Cache::recvTimingReq(), NoncoherentXBar::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), DRAMSim2::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CommMonitor::recvTimingReq(), CoherentXBar::recvTimingReq(), DRAMCtrl::recvTimingReq(), DefaultFetch< Impl >::IcachePort::recvTimingResp(), DmaPort::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), BaseCache::sendMSHRQueuePacket(), CoherentXBar::sinkPacket(), SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
clearBlockCached()
void Packet::clearBlockCached () inline
Definition at line 693 of file packet.hh.
References Flags< T >::clear().
Referenced by BaseCache::access().
clearWriteThrough()
void Packet::clearWriteThrough () inline
Definition at line 673 of file packet.hh.
References Flags< T >::clear().
Referenced by CoherentXBar::recvAtomicBackdoor(), and CoherentXBar::recvTimingReq().
cmdString()
const std::string& Packet::cmdString () const inline
Return the string name of the cmd field (for debugging and tracing).
Definition at line 523 of file packet.hh.
References MemCmd::toString().
Referenced by AbstractMemory::functionalAccess(), DmaPort::handleResp(), Sequencer::hitCallback(), print(), DRAMCtrl::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), RubyPort::MemSlavePort::recvFunctional(), NoncoherentXBar::recvFunctional(), AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop(), RubyPort::MemSlavePort::recvTimingReq(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), DRAMCtrl::recvTimingReq(), NoncoherentXBar::recvTimingResp(), SerialLink::SerialLinkMasterPort::recvTimingResp(), Bridge::BridgeMasterPort::recvTimingResp(), LSQ< Impl >::recvTimingSnoopReq(), RubyPort::ruby_hit_callback(), PacketQueue::schedSendTiming(), AtomicSimpleCPU::threadSnoop(), trySatisfyFunctional(), DmaPort::trySendTimingReq(), and BaseTrafficGen::update().
cmdToIndex()
int Packet::cmdToIndex () const inline
Return the index of this command.
Definition at line 526 of file packet.hh.
References MemCmd::toInt().
Referenced by BaseCache::CacheStats::cmdStats(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), and CoherentXBar::recvTimingSnoopResp().
convertLlToRead()
void Packet::convertLlToRead () inline
When ruby is in use, Ruby will monitor the cache line and the phys memory should treat LL ops as normal reads.
Definition at line 784 of file packet.hh.
References MemCmd::isLLSC(), MemCmd::isRead(), and MemCmd::ReadReq.
Referenced by RubyPort::MemSlavePort::hitCallback().
convertScToWrite()
void Packet::convertScToWrite () inline
It has been determined that the SC packet should successfully update memory.
Therefore, convert this SC packet to a normal write.
Definition at line 772 of file packet.hh.
References MemCmd::isLLSC(), MemCmd::isWrite(), and MemCmd::WriteReq.
Referenced by RubyPort::MemSlavePort::hitCallback().
copyError()
void Packet::copyError (Packet * pkt) inline
Definition at line 724 of file packet.hh.
References cmd, and isError().
Referenced by NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), Minor::LSQ::SplitDataRequest::retireResponse(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
copyResponderFlags()
void Packet::copyResponderFlags (const PacketPtr pkt)
Copy the reponse flags from an input packet to this packet.
The reponse flags determine whether a responder has been found and the state at which the block will be at the destination.
The packet that we will copy flags from
Definition at line 309 of file packet.cc.
References cacheResponding(), flags, isRequest(), RESPONDER_FLAGS, and Flags< T >::set().
Referenced by Cache::handleSnoop(), and Cache::serviceMSHRTargets().
createRead()
static PacketPtr Packet::createRead (const RequestPtr & req) inline static
Constructor-like methods that return Packets based on Request objects.
Fine-tune the MemCmd type if it's not a vanilla read or write.
Definition at line 913 of file packet.hh.
References MemCmd::Packet.
Referenced by TimingSimpleCPU::buildPacket(), LSQ< Impl >::SingleDataRequest::buildPackets(), LSQ< Impl >::SplitDataRequest::buildPackets(), TraceCPU::ElasticDataGen::executeMemReq(), Minor::makePacketForRequest(), AbstractController::queueMemoryRead(), CheckerCPU::readMem(), and LSQ< Impl >::SplitDataRequest::recvTimingResp().
createWrite()
static PacketPtr Packet::createWrite (const RequestPtr & req) inline static
Definition at line 919 of file packet.hh.
References MemCmd::Packet.
Referenced by TimingSimpleCPU::buildPacket(), LSQ< Impl >::SingleDataRequest::buildPackets(), LSQ< Impl >::SplitDataRequest::buildPackets(), TraceCPU::ElasticDataGen::executeMemReq(), Minor::makePacketForRequest(), AbstractController::queueMemoryWrite(), AbstractController::queueMemoryWritePartial(), and LSQ< Impl >::SplitDataRequest::recvTimingResp().
dataDynamic()
template<typename T > void Packet::dataDynamic (T * p) inline
Set the data pointer to a value that should have delete [] called on it.
Dynamic data is local to this packet, and as the packet travels from source to destination, forwarded packets will allocate their own data. When a packet reaches the final destination it will populate the dynamic data of that specific packet, and on the way back towards the source, memcpy will be invoked in every step where a new packet was created e.g. in the caches. Ultimately when the response reaches the source a final memcpy is needed to extract the data from the packet before it is deallocated.
Definition at line 1078 of file packet.hh.
References Flags< T >::noneSet(), and Flags< T >::set().
Referenced by LSQ< Impl >::SplitDataRequest::buildPackets(), TimingSimpleCPU::buildSplitPacket(), TraceCPU::ElasticDataGen::executeMemReq(), FetchUnit::fetch(), DefaultFetch< Impl >::finishTranslation(), BaseGen::getPacket(), Check::initiateAction(), Check::initiateCheck(), Check::initiatePrefetch(), Minor::makePacketForRequest(), TraceCPU::FixedRetryGen::send(), and TimingSimpleCPU::sendData().
dataStatic()
template<typename T > void Packet::dataStatic (T * p) inline
Set the data pointer to the following value that should not be freed.
Static data allows us to do a single memcpy even if multiple packets are required to get from source to destination and back. In essence the pointer is set calling dataStatic on the original packet, and whenever this packet is copied and forwarded the same pointer is passed on. When a packet eventually reaches the destination holding the data, it is copied once into the location originally set. On the way back to the source, no copies are necessary.
Definition at line 1040 of file packet.hh.
References Flags< T >::noneSet(), and Flags< T >::set().
Referenced by AtomicSimpleCPU::amoMem(), LSQ< Impl >::SplitDataRequest::buildPackets(), TimingSimpleCPU::buildSplitPacket(), DmaPort::dmaAction(), Shader::doFunctionalAccess(), BaseKvmCPU::doMMIOAccess(), SMMUProcess::doRead(), ItsProcess::doRead(), SMMUProcess::doWrite(), ItsProcess::doWrite(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execAtomic(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execSt(), ArmISA::TableWalker::fetchDescriptor(), LSQ< Impl >::SplitDataRequest::handleIprRead(), LSQ< Impl >::SplitDataRequest::handleIprWrite(), X86KvmCPU::handleKvmExitIO(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::initiateAcc(), LSQUnit< Impl >::read(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), ComputeUnit::DTLBPort::recvTimingResp(), LSQ< Impl >::SplitDataRequest::recvTimingResp(), ComputeUnit::sendRequest(), AtomicSimpleCPU::tick(), Checker< O3CPUImpl >::verify(), LSQUnit< Impl >::writebackStores(), BaseCache::writebackVisitor(), and AtomicSimpleCPU::writeMem().
dataStaticConst()
template<typename T > void Packet::dataStaticConst (const T * p) inline
Set the data pointer to the following value that should not be freed.
This version of the function allows the pointer passed to us to be const. To avoid issues down the line we cast the constness away, the alternative would be to keep both a const and non-const data pointer and cleverly choose between them. Note that this is only allowed for static data.
Definition at line 1057 of file packet.hh.
References Flags< T >::noneSet(), MipsISA::p, and Flags< T >::set().
deleteData()
void Packet::deleteData () inline
delete the data pointed to in the data pointer.
Ok to call to matter how data was allocted.
Definition at line 1221 of file packet.hh.
References Flags< T >::clear(), and Flags< T >::isSet().
findNextSenderState()
template<typename T > T* Packet::findNextSenderState () const inline
Go through the sender state stack and return the first instance that is of type T (as determined by a dynamic_cast).
If there is no sender state of type T, NULL is returned.
Returns
The topmost state of type T
Definition at line 510 of file packet.hh.
References Packet::SenderState::predecessor, and ArmISA::t.
Referenced by MSHR::TargetList::add(), Sequencer::hitCallback(), and Minor::LSQ::tryToSend().
fromCache()
bool Packet::fromCache () const inline
Definition at line 546 of file packet.hh.
References MemCmd::fromCache().
Referenced by AbstractMemory::access(), BaseCache::access(), Cache::handleAtomicReqMiss(), SnoopFilter::lookupRequest(), Cache::satisfyRequest(), and MSHR::TargetList::updateFlags().
get()
template<typename T > T Packet::get (ByteOrder endian) const inline
Get the data in the packet byte swapped from the specified endianness.
Definition at line 86 of file packet_access.hh.
References BigEndianByteOrder, LittleEndianByteOrder, and panic.
Referenced by getMem().
getAddr()
Addr Packet::getAddr () const inline
Definition at line 726 of file packet.hh.
References addr, and Flags< T >::isSet().
Referenced by Cache::access(), AbstractMemory::access(), BaseCache::access(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), SimpleCache::accessTiming(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), BaseCache::allocateBlock(), GPUCoalescer::atomicCallback(), SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3SlaveInterface::atsSlaveRecvAtomic(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), AbstractMemory::checkLockedAddrList(), LSQUnit< Impl >::checkSnoop(), TimingSimpleCPU::completeIfetch(), Cache::createMissPacket(), IdeController::dispatchAccess(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), AddressMonitor::doMonitor(), SMMUTranslRequest::fromPacket(), AbstractMemory::functionalAccess(), BaseCache::functionalAccess(), RubySystem::functionalRead(), RubySystem::functionalWrite(), RubyRequest::functionalWrite(), getAddrRange(), QueuedPrefetcher::getPacket(), GPUCoalescer::getRequestStatus(), NoncoherentCache::handleAtomicReqMiss(), BaseCache::handleFill(), GenericISA::handleGenericIprRead(), GenericISA::handleGenericIprWrite(), X86ISA::handleIprRead(), X86ISA::handleIprWrite(), MipsISA::handleLockedSnoop(), ArmISA::handleLockedSnoop(), AlphaISA::handleLockedSnoop(), RiscvISA::handleLockedSnoop(), Minor::Execute::handleMemResponse(), handlePseudoInst(), SimpleMemobj::handleRequest(), SimpleCache::handleRequest(), DmaPort::handleResp(), SimpleMemobj::handleResponse(), SimpleCache::handleResponse(), Cache::handleSnoop(), BaseCache::handleTimingReqMiss(), Sequencer::hitCallback(), GPUCoalescer::hitCallback(), SimpleCache::insert(), BaseTags::insertBlock(), Sequencer::insertRequest(), GPUCoalescer::insertRequest(), I2CBus::isClockSet(), I2CBus::isEnd(), I2CBus::isStart(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), SMMUv3::masterRecvReqRetry(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvReqRetry(), SMMUv3::masterTableWalkRecvTimingResp(), matchAddr(), BaseCPU::mwait(), BOPPrefetcher::notifyFill(), SBOOEPrefetcher::notifyFill(), sc_gem5::packet2payload(), BasePrefetcher::PrefetchInfo::PrefetchInfo(), print(), BasePrefetcher::probeNotify(), QoS::MemSinkCtrl::processNextReqEvent(), SimpleUart::read(), PciVirtIO::read(), MmioVirtIO::read(), X86ISA::I8237::read(), MmDisk::read(), DumbTOD::read(), NoMaliGpu::read(), Pl011::read(), AmbaFake::read(), X86ISA::Speaker::read(), A9SCU::read(), IsaFake::read(), TsunamiPChip::read(), Uart8250::read(), X86ISA::Cmos::read(), TsunamiCChip::read(), X86ISA::I8254::read(), X86ISA::I82094AA::read(), X86ISA::I8259::read(), HDLcd::read(), Gicv2m::read(), AlphaBackdoor::read(), PL031::read(), Gicv3::read(), TsunamiIO::read(), EnergyCtrl::read(), Pl050::read(), Iob::read(), X86ISA::I8042::read(), GpuDispatcher::read(), I2CBus::read(), Gicv3Its::read(), Sp804::read(), A9GlobalTimer::read(), RealViewCtrl::read(), CpuLocalTimer::read(), CopyEngine::read(), VGic::read(), X86ISA::Interrupts::read(), Sinic::Device::read(), GenericPciHost::read(), GenericTimerMem::read(), NSGigE::read(), Pl111::read(), GicV2::read(), IGbE::read(), UFSHostDevice::read(), IdeController::readConfig(), PciDevice::readConfig(), SMMUv3::readControl(), GicV2::readCpu(), VGic::readCtrl(), GicV2::readDistributor(), AmbaDevice::readId(), Iob::readIob(), Iob::readJBus(), VGic::readVCpu(), Sequencer::recordMissLatency(), GPUCoalescer::recordMissLatency(), StubSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvAtomic(), SMMUv3SlaveInterface::recvAtomic(), SMMUControlPort::recvAtomic(), RubyPort::PioSlavePort::recvAtomic(), AddrMapper::recvAtomic(), DRAMCtrl::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), Cache::recvAtomicSnoop(), AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), AddrMapper::recvAtomicSnoop(), RubyPort::MemSlavePort::recvFunctional(), NoncoherentXBar::recvFunctional(), MemCheckerMonitor::recvFunctional(), AddrMapper::recvFunctional(), AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop(), MemCheckerMonitor::recvFunctionalSnoop(), AddrMapper::recvFunctionalSnoop(), X86ISA::Interrupts::recvMessage(), HMCController::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), SMMUv3SlaveInterface::recvTimingReq(), RubyPort::PioSlavePort::recvTimingReq(), NoncoherentXBar::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), DRAMSim2::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CoherentXBar::recvTimingReq(), DRAMCtrl::recvTimingReq(), RubyDirectedTester::CpuPort::recvTimingResp(), RubyPort::MemMasterPort::recvTimingResp(), RubyPort::PioMasterPort::recvTimingResp(), AbstractController::recvTimingResp(), NoncoherentXBar::recvTimingResp(), TimingSimpleCPU::IcachePort::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), AddrMapper::recvTimingResp(), TimingSimpleCPU::DcachePort::recvTimingResp(), SerialLink::SerialLinkMasterPort::recvTimingResp(), Bridge::BridgeMasterPort::recvTimingResp(), BaseCache::recvTimingResp(), Minor::LSQ::recvTimingResp(), LSQ< Impl >::recvTimingResp(), Cache::recvTimingSnoopReq(), LSQ< Impl >::recvTimingSnoopReq(), Cache::recvTimingSnoopResp(), GPUCoalescer::removeRequest(), RubyPort::ruby_hit_callback(), SMMUv3::runProcessTiming(), BaseCache::satisfyRequest(), PacketQueue::schedSendTiming(), Cache::sendMSHRQueuePacket(), NonCachingSimpleCPU::sendPacket(), ComputeUnit::sendRequest(), SimpleCache::sendResponse(), testAndRead(), testAndReadMask(), testAndWrite(), AtomicSimpleCPU::threadSnoop(), trySatisfyFunctional(), SerialLink::SerialLinkSlavePort::trySendTiming(), Bridge::BridgeSlavePort::trySendTiming(), SerialLink::SerialLinkMasterPort::trySendTiming(), Bridge::BridgeMasterPort::trySendTiming(), DmaPort::trySendTimingReq(), BaseTrafficGen::update(), I2CBus::updateSignals(), GPUCoalescer::wakeup(), SimpleUart::write(), PciVirtIO::write(), MmioVirtIO::write(), X86ISA::I8237::write(), MmDisk::write(), NoMaliGpu::write(), Pl011::write(), AmbaFake::write(), X86ISA::Speaker::write(), A9SCU::write(), TsunamiPChip::write(), IsaFake::write(), Uart8250::write(), X86ISA::Cmos::write(), TsunamiCChip::write(), X86ISA::I8254::write(), X86ISA::I82094AA::write(), X86ISA::I8259::write(), HDLcd::write(), Gicv2m::write(), AlphaBackdoor::write(), PL031::write(), TsunamiIO::write(), Gicv3::write(), EnergyCtrl::write(), Pl050::write(), Iob::write(), X86ISA::I8042::write(), I2CBus::write(), GpuDispatcher::write(), Gicv3Its::write(), Sp804::write(), A9GlobalTimer::write(), RealViewCtrl::write(), CpuLocalTimer::write(), CopyEngine::write(), VGic::write(), X86ISA::Interrupts::write(), Sinic::Device::write(), GenericPciHost::write(), GenericTimerMem::write(), NSGigE::write(), Pl111::write(), GicV2::write(), IGbE::write(), UFSHostDevice::write(), IdeController::writeConfig(), PciDevice::writeConfig(), NSGigE::writeConfig(), IGbE::writeConfig(), SMMUv3::writeControl(), GicV2::writeCpu(), VGic::writeCtrl(), GicV2::writeDistributor(), Iob::writeIob(), Iob::writeJBus(), and VGic::writeVCpu().
getAddrRange()
AddrRange Packet::getAddrRange () const
Get address range to which this packet belongs.
Returns
Address range of this packet.
Definition at line 228 of file packet.cc.
References getAddr(), getSize(), and RangeSize().
Referenced by PhysicalMemory::access(), AbstractMemory::access(), PhysicalMemory::functionalAccess(), AbstractMemory::functionalAccess(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), and CoherentXBar::recvTimingSnoopReq().
getAtomicOp()
AtomicOpFunctor* Packet::getAtomicOp () const inline
Accessor function to atomic op.
Definition at line 764 of file packet.hh.
Referenced by AbstractMemory::access(), GPUCoalescer::issueRequest(), and BaseCache::satisfyRequest().
getBE()
template<typename T > T Packet::getBE () const inline
Get the data in the packet byte swapped from big endian to host endian.
Definition at line 72 of file packet_access.hh.
References betoh().
Referenced by SparcISA::TLB::doMmuRegWrite(), Iob::writeIob(), and Iob::writeJBus().
getBlockAddr()
Addr Packet::getBlockAddr (unsigned int blk_size) const inline
Definition at line 750 of file packet.hh.
Referenced by SimpleCache::accessFunctional(), SimpleCache::accessTiming(), BaseCache::allocateMissBuffer(), BaseCache::allocateWriteBuffer(), Cache::createMissPacket(), BaseCache::functionalAccess(), BaseCache::getNextQueueEntry(), BaseCache::handleFill(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), SimpleCache::insert(), SnoopFilter::lookupRequest(), SnoopFilter::lookupSnoop(), matchBlockAddr(), Cache::recvTimingSnoopReq(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
getConstPtr()
template<typename T > const T* Packet::getConstPtr () const inline
Definition at line 1099 of file packet.hh.
References data, Flags< T >::isSet(), ArmISA::v, and MipsISA::w.
Referenced by BaseCache::access(), SimpleCache::accessTiming(), BaseCache::allocateBlock(), AbstractMemory::checkLockedAddrList(), MemTest::completeRequest(), RubyRequest::functionalWrite(), Minor::Execute::handleMemResponse(), Sequencer::hitCallback(), Check::initiateAction(), SimpleCache::insert(), BasePrefetcher::PrefetchInfo::PrefetchInfo(), DefaultFetch< Impl >::processCacheCompletion(), StubSlavePort::recvAtomic(), Cache::recvTimingSnoopReq(), Minor::LSQ::SplitDataRequest::retireResponse(), Cache::serviceMSHRTargets(), testAndWrite(), and AtomicSimpleCPU::writeMem().
getLE()
template<typename T > T Packet::getLE () const inline
Get the data in the packet byte swapped from little endian to host endian.
Definition at line 79 of file packet_access.hh.
References letoh().
Referenced by CopyEngine::CopyEngineChannel::channelWrite(), IdeController::dispatchAccess(), X86ISA::getMem(), X86ISA::getPackedMem(), ItsTranslation::main(), Pl011::read(), TsunamiCChip::read(), AlphaBackdoor::read(), Sp804::Timer::read(), PL031::read(), A9GlobalTimer::Timer::read(), Pl050::read(), Pl111::read(), IdeController::readConfig(), PciDevice::readConfig(), X86ISA::Walker::WalkerState::stepWalk(), MmioVirtIO::write(), PciVirtIO::write(), X86ISA::I8237::write(), NoMaliGpu::write(), Pl011::write(), X86ISA::Speaker::write(), TsunamiPChip::write(), IsaFake::write(), X86ISA::Cmos::write(), TsunamiCChip::write(), X86ISA::I8254::write(), X86ISA::I82094AA::write(), X86ISA::I8259::write(), HDLcd::write(), Gicv2m::write(), AlphaBackdoor::write(), Sp804::Timer::write(), PL031::write(), TsunamiIO::write(), EnergyCtrl::write(), A9GlobalTimer::Timer::write(), X86ISA::I8042::write(), CpuLocalTimer::Timer::write(), GpuDispatcher::write(), Gicv3Its::write(), RealViewCtrl::write(), CopyEngine::write(), Sinic::Device::write(), GenericTimerMem::write(), NSGigE::write(), Pl111::write(), IGbE::write(), UFSHostDevice::write(), IdeController::writeConfig(), PciDevice::writeConfig(), SMMUv3::writeControl(), GicV2::writeCpu(), VGic::writeCtrl(), GicV2::writeDistributor(), and VGic::writeVCpu().
getOffset()
Addr Packet::getOffset (unsigned int blk_size) const inline
Definition at line 745 of file packet.hh.
Referenced by BaseCache::cmpAndSwap(), Cache::promoteWholeLineWrites(), BaseCache::satisfyRequest(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), and MSHR::TargetList::updateWriteFlags().
getPtr()
template<typename T > T* Packet::getPtr () inline
get a pointer to the data ptr.
Definition at line 1090 of file packet.hh.
References data, and Flags< T >::isSet().
Referenced by Minor::ForwardLineData::adoptPacketData(), GPUCoalescer::atomicCallback(), IdeController::dispatchAccess(), Minor::LSQ::StoreBuffer::forwardStoreData(), LSQ< Impl >::SplitDataRequest::handleIprRead(), LSQ< Impl >::SplitDataRequest::handleIprWrite(), GPUCoalescer::hitCallback(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), sc_gem5::packet2payload(), FetchUnit::processFetchReturn(), IsaFake::read(), GpuDispatcher::read(), GenericPciHost::read(), NSGigE::read(), AbstractController::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), Minor::LSQ::SplitDataRequest::retireResponse(), ComputeUnit::sendRequest(), testAndRead(), testAndReadMask(), trySatisfyFunctional(), and GpuDispatcher::write().
getRaw()
template<typename T > T Packet::getRaw () const inline
Get the data in the packet without byte swapping.
Definition at line 53 of file packet_access.hh.
References data, DYNAMIC_DATA, flags, Flags< T >::isSet(), size, and STATIC_DATA.
Referenced by I2CBus::isClockSet(), I2CBus::isEnd(), I2CBus::isStart(), X86ISA::Interrupts::recvMessage(), I2CBus::updateSignals(), MmDisk::write(), and Uart8250::write().
getSize()
unsigned Packet::getSize () const inline
Definition at line 736 of file packet.hh.
References Flags< T >::isSet().
Referenced by AbstractMemory::access(), BaseCache::access(), SimpleCache::accessTiming(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), GPUCoalescer::atomicCallback(), SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3SlaveInterface::atsSlaveRecvAtomic(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), BaseXBar::calcPacketTiming(), AbstractMemory::checkLockedAddrList(), BaseCache::cmpAndSwap(), IdeController::dispatchAccess(), SMMUProcess::doRead(), ItsProcess::doRead(), ItsProcess::doWrite(), SMMUTranslRequest::fromPacket(), RubyRequest::functionalWrite(), getAddrRange(), getUintX(), BaseCache::handleFill(), X86ISA::handleIprRead(), X86ISA::handleIprWrite(), Minor::Execute::handleMemResponse(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), Sequencer::hitCallback(), GPUCoalescer::hitCallback(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), SMMUv3::masterRecvReqRetry(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvReqRetry(), SMMUv3::masterTableWalkRecvTimingResp(), sc_gem5::packet2payload(), print(), QoS::MemSinkCtrl::processNextReqEvent(), Cache::promoteWholeLineWrites(), MmioVirtIO::read(), PciVirtIO::read(), X86ISA::I8237::read(), MmDisk::read(), DumbTOD::read(), NoMaliGpu::read(), Pl011::read(), A9SCU::read(), X86ISA::Speaker::read(), IsaFake::read(), TsunamiPChip::read(), Uart8250::read(), X86ISA::Cmos::read(), TsunamiCChip::read(), X86ISA::I8254::read(), X86ISA::I82094AA::read(), X86ISA::I8259::read(), HDLcd::read(), AlphaBackdoor::read(), PL031::read(), Gicv3::read(), TsunamiIO::read(), EnergyCtrl::read(), X86ISA::I8042::read(), GpuDispatcher::read(), Sp804::read(), A9GlobalTimer::read(), RealViewCtrl::read(), CpuLocalTimer::read(), CopyEngine::read(), X86ISA::Interrupts::read(), Sinic::Device::read(), GenericPciHost::read(), GenericTimerMem::read(), NSGigE::read(), Pl111::read(), IGbE::read(), IdeController::readConfig(), PciDevice::readConfig(), VirtIODeviceBase::readConfigBlob(), SMMUv3::readControl(), GicV2::readDistributor(), AmbaDevice::readId(), StubSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvAtomic(), SMMUv3SlaveInterface::recvAtomic(), SMMUControlPort::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicSnoop(), RubyPort::MemSlavePort::recvFunctional(), MemCheckerMonitor::recvFunctional(), MemCheckerMonitor::recvFunctionalSnoop(), HMCController::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), SMMUv3SlaveInterface::recvTimingReq(), NoncoherentXBar::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CoherentXBar::recvTimingReq(), DRAMCtrl::recvTimingReq(), NoncoherentXBar::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), SerialLink::SerialLinkMasterPort::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), Minor::LSQ::SplitDataRequest::retireResponse(), SMMUv3::runProcessTiming(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), PacketQueue::schedSendTiming(), QoS::Policy::schedule(), QoS::MemCtrl::schedule(), BaseCache::sendMSHRQueuePacket(), ComputeUnit::sendRequest(), Cache::serviceMSHRTargets(), setUintX(), X86ISA::Walker::WalkerState::stepWalk(), testAndRead(), testAndReadMask(), testAndWrite(), trySatisfyFunctional(), SerialLink::SerialLinkSlavePort::trySendTiming(), SerialLink::SerialLinkMasterPort::trySendTiming(), MSHR::TargetList::updateWriteFlags(), MmioVirtIO::write(), PciVirtIO::write(), X86ISA::I8237::write(), MmDisk::write(), NoMaliGpu::write(), Pl011::write(), X86ISA::Speaker::write(), TsunamiPChip::write(), IsaFake::write(), Uart8250::write(), X86ISA::Cmos::write(), TsunamiCChip::write(), X86ISA::I8254::write(), X86ISA::I82094AA::write(), X86ISA::I8259::write(), HDLcd::write(), AlphaBackdoor::write(), PL031::write(), Gicv3::write(), TsunamiIO::write(), EnergyCtrl::write(), Pl050::write(), X86ISA::I8042::write(), GpuDispatcher::write(), Gicv3Its::write(), Sp804::write(), A9GlobalTimer::write(), CpuLocalTimer::write(), CopyEngine::write(), X86ISA::Interrupts::write(), Sinic::Device::write(), GenericPciHost::write(), GenericTimerMem::write(), NSGigE::write(), Pl111::write(), IGbE::write(), UFSHostDevice::write(), IdeController::writeConfig(), PciDevice::writeConfig(), VirtIODeviceBase::writeConfigBlob(), SMMUv3::writeControl(), and GicV2::writeDistributor().
getUintX()
uint64_t Packet::getUintX (ByteOrder endian) const
Get the data in the packet byte swapped from the specified endianness and zero-extended to 64 bits.
Definition at line 337 of file packet.cc.
References getSize(), and panic.
Referenced by AbstractMemory::checkLockedAddrList(), SimpleUart::write(), Gicv3::write(), and Pl050::write().
hasData()
bool Packet::hasData () const inline
Definition at line 548 of file packet.hh.
References MemCmd::hasData().
Referenced by BaseCache::allocateBlock(), BaseXBar::calcPacketTiming(), BaseCache::handleFill(), Cache::handleSnoop(), DRAMCtrl::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicSnoop(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentXBar::recvTimingResp(), CoherentXBar::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), replaceUpgrade(), and trySatisfyFunctional().
hasRespData()
bool Packet::hasRespData () const inline
Definition at line 549 of file packet.hh.
References MemCmd::hasData(), and MemCmd::responseCommand().
Referenced by replaceUpgrade(), and BaseCache::satisfyRequest().
hasSharers()
bool Packet::hasSharers () const inline
Definition at line 618 of file packet.hh.
References Flags< T >::isSet().
Referenced by BaseCache::access(), Cache::createMissPacket(), NoncoherentCache::handleAtomicReqMiss(), BaseCache::handleFill(), Cache::handleSnoop(), NoncoherentCache::recvTimingResp(), DefaultFetch< Impl >::IcachePort::recvTimingResp(), DmaPort::recvTimingResp(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), BaseCache::sendMSHRQueuePacket(), SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
isAtomicOp()
bool Packet::isAtomicOp () const inline
Definition at line 765 of file packet.hh.
Referenced by AbstractMemory::access(), GPUCoalescer::issueRequest(), GPUCoalescer::makeRequest(), and BaseCache::satisfyRequest().
isBlockCached()
bool Packet::isBlockCached () const inline
Definition at line 692 of file packet.hh.
References Flags< T >::isSet().
Referenced by Cache::handleSnoop(), Cache::isCachedAbove(), SnoopFilter::lookupRequest(), and CoherentXBar::sinkPacket().
isClean()
bool Packet::isClean () const inline
Definition at line 545 of file packet.hh.
References MemCmd::isClean().
Referenced by AbstractMemory::access(), Cache::createMissPacket(), CoherentXBar::forwardPacket(), Cache::handleSnoop(), MSHR::handleSnoop(), MSHR::isCleaning(), BaseCache::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), BaseCache::recvTimingResp(), BaseCache::satisfyRequest(), and BaseCache::sendMSHRQueuePacket().
isCleanEviction()
bool Packet::isCleanEviction () const inline
Is this packet a clean eviction, including both actual clean evict packets, but also clean writebacks.
Definition at line 1300 of file packet.hh.
References MemCmd::CleanEvict, and MemCmd::WritebackClean.
Referenced by BaseCache::access(), and CoherentXBar::sinkPacket().
isError()
bool Packet::isError () const inline
Definition at line 555 of file packet.hh.
References MemCmd::isError().
Referenced by AtomicSimpleCPU::amoMem(), TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), MemTest::completeRequest(), copyError(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), Minor::Execute::handleMemResponse(), Minor::Fetch1::minorTraceResponseLine(), ArmISA::Stage2MMU::readDataUntimed(), AtomicSimpleCPU::readMem(), PioPort< X86ISA::Interrupts >::recvAtomic(), Minor::Fetch1::recvTimingResp(), BaseCache::recvTimingResp(), Minor::LSQ::recvTimingResp(), LSQ< Impl >::recvTimingResp(), Minor::LSQ::SplitDataRequest::retireResponse(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), AtomicSimpleCPU::tick(), and AtomicSimpleCPU::writeMem().
isEviction()
bool Packet::isEviction () const inline
Definition at line 544 of file packet.hh.
References MemCmd::isEviction().
Referenced by BaseCache::access(), WriteQueueEntry::allocate(), Cache::createMissPacket(), Cache::handleAtomicReqMiss(), BaseCache::handleTimingReqMiss(), Cache::isCachedAbove(), SnoopFilter::lookupRequest(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), and Cache::recvTimingSnoopReq().
isExpressSnoop()
bool Packet::isExpressSnoop () const inline
Definition at line 634 of file packet.hh.
References Flags< T >::isSet().
Referenced by MSHR::handleSnoop(), print(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), CoherentXBar::recvTimingReq(), CoherentXBar::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopResp(), PacketQueue::schedSendTiming(), and BaseCache::CpuSidePort::tryTiming().
isFlush()
bool Packet::isFlush () const inline
Definition at line 557 of file packet.hh.
References MemCmd::isFlush().
Referenced by RubyPort::MemSlavePort::hitCallback(), Sequencer::hitCallback(), Sequencer::issueRequest(), Sequencer::makeRequest(), and GPUCoalescer::makeRequest().
isInvalidate()
bool Packet::isInvalidate () const inline
Definition at line 543 of file packet.hh.
References MemCmd::isInvalidate().
Referenced by AbstractMemory::access(), LSQUnit< Impl >::checkSnoop(), Cache::doTimingSupplyResponse(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), ArmISA::handleLockedSnoop(), Cache::handleSnoop(), MSHR::handleSnoop(), SnoopFilter::lookupSnoop(), BasePrefetcher::observeAccess(), sc_gem5::packet2payload(), AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), AtomicSimpleCPU::AtomicCPUDPort::recvFunctionalSnoop(), NoncoherentCache::recvTimingResp(), BaseCache::recvTimingResp(), LSQ< Impl >::recvTimingResp(), Cache::recvTimingSnoopReq(), TimingSimpleCPU::DcachePort::recvTimingSnoopReq(), Minor::LSQ::recvTimingSnoopReq(), LSQ< Impl >::recvTimingSnoopReq(), BaseCache::satisfyRequest(), Cache::serviceMSHRTargets(), Minor::LSQ::threadSnoop(), and SnoopFilter::updateResponse().
isLLSC()
bool Packet::isLLSC () const inline
Definition at line 554 of file packet.hh.
References MemCmd::isLLSC().
Referenced by AbstractMemory::access(), BaseCache::access(), AbstractMemory::checkLockedAddrList(), CacheBlk::checkWrite(), Cache::createMissPacket(), RubyPort::MemSlavePort::hitCallback(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), MemCheckerMonitor::recvTimingResp(), BaseCache::satisfyRequest(), CacheBlk::trackLoadLocked(), and AbstractMemory::writeOK().
isMaskedWrite()
bool Packet::isMaskedWrite () const inline
Definition at line 1306 of file packet.hh.
References X86ISA::base, and MemCmd::WriteReq.
Referenced by Cache::promoteWholeLineWrites(), and trySatisfyFunctional().
isPrint()
bool Packet::isPrint () const inline
Definition at line 556 of file packet.hh.
References MemCmd::isPrint().
Referenced by AbstractMemory::functionalAccess(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), CoherentXBar::recvFunctionalSnoop(), WriteQueueEntry::trySatisfyFunctional(), MSHR::trySatisfyFunctional(), and trySatisfyFunctional().
isRead()
bool Packet::isRead () const inline
Definition at line 528 of file packet.hh.
References MemCmd::isRead().
Referenced by AbstractMemory::access(), BaseCache::access(), SimpleCache::accessFunctional(), SimpleCache::accessTiming(), MemTest::completeRequest(), SimpleMemDelay::delayReq(), SimpleMemDelay::delayResp(), Cache::doTimingSupplyResponse(), CoherentXBar::forwardPacket(), AbstractMemory::functionalAccess(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), BaseCache::handleFill(), handlePseudoInst(), TimingSimpleCPU::handleReadPacket(), Cache::handleSnoop(), Cache::handleTimingReqMiss(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), BasePrefetcher::observeAccess(), sc_gem5::packet2payload(), ComputeUnit::DataPort::processMemRespEvent(), QoS::MemSinkCtrl::processNextReqEvent(), PioPort< X86ISA::Interrupts >::recvAtomic(), SMMUControlPort::recvAtomic(), NoncoherentCache::recvAtomic(), RubyPort::MemSlavePort::recvFunctional(), X86ISA::Walker::WalkerState::recvPacket(), TimingSimpleCPU::DcachePort::recvReqRetry(), NoncoherentCache::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SimpleMemory::recvTimingReq(), DRAMSim2::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CommMonitor::recvTimingReq(), DRAMCtrl::recvTimingReq(), NoncoherentCache::recvTimingResp(), AbstractController::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), BaseCache::recvTimingResp(), Cache::recvTimingSnoopReq(), Minor::LSQ::SplitDataRequest::retireResponse(), NoncoherentCache::satisfyRequest(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), ComputeUnit::sendRequest(), Cache::serviceMSHRTargets(), CoherentXBar::sinkPacket(), and trySatisfyFunctional().
isRequest()
bool Packet::isRequest () const inline
Definition at line 531 of file packet.hh.
References MemCmd::isRequest().
Referenced by Cache::access(), PhysicalMemory::access(), BaseCache::access(), BaseCache::cmpAndSwap(), copyResponderFlags(), Cache::doTimingSupplyResponse(), PhysicalMemory::functionalAccess(), Cache::handleSnoop(), X86ISA::GpuTLB::handleTranslationReturn(), SnoopFilter::lookupSnoop(), MemCheckerMonitor::recvTimingReq(), CommMonitor::recvTimingReq(), BaseCache::CpuSidePort::recvTimingReq(), RubyPort::ruby_hit_callback(), BaseCache::satisfyRequest(), FunctionalRequestProtocol::send(), AtomicRequestProtocol::send(), AtomicRequestProtocol::sendBackdoor(), TimingRequestProtocol::sendReq(), FunctionalResponseProtocol::sendSnoop(), AtomicResponseProtocol::sendSnoop(), TimingResponseProtocol::sendSnoopReq(), TimingRequestProtocol::trySend(), and TLBCoalescer::updatePhysAddresses().
isResponse()
bool Packet::isResponse () const inline
Definition at line 532 of file packet.hh.
References MemCmd::isResponse().
Referenced by DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), GarnetSyntheticTraffic::completeRequest(), CoherentXBar::forwardAtomic(), CoherentXBar::forwardFunctional(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), BaseCache::handleFill(), DmaPort::handleResp(), Cache::handleSnoop(), SimpleCache::insert(), PioPort< X86ISA::Interrupts >::recvAtomic(), CommMonitor::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicSnoop(), CoherentXBar::recvFunctional(), X86ISA::Walker::WalkerState::recvPacket(), SimpleTimingPort::recvTimingReq(), SimpleMemory::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), NoncoherentCache::recvTimingResp(), X86ISA::IntMasterPort< X86ISA::I82094AA >::recvTimingResp(), AbstractController::recvTimingResp(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), BaseCache::recvTimingResp(), BaseCache::CpuSidePort::recvTimingSnoopResp(), TimingResponseProtocol::sendResp(), TimingRequestProtocol::sendSnoopResp(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), and SnoopFilter::updateSnoopResponse().
isSecure()
bool Packet::isSecure () const inline
Definition at line 755 of file packet.hh.
References Flags< T >::isSet().
Referenced by Cache::access(), BaseCache::access(), WriteQueueEntry::allocate(), MSHR::allocate(), BaseCache::allocateBlock(), BaseCache::allocateWriteBuffer(), BaseCache::functionalAccess(), BaseCache::getNextQueueEntry(), BaseCache::handleFill(), NoncoherentCache::handleTimingReqMiss(), Cache::handleTimingReqMiss(), BaseTags::insertBlock(), SnoopFilter::lookupRequest(), SnoopFilter::lookupSnoop(), matchAddr(), matchBlockAddr(), BasePrefetcher::probeNotify(), Gicv3::read(), CoherentXBar::recvAtomicBackdoor(), Cache::recvAtomicSnoop(), CoherentXBar::recvTimingReq(), BaseCache::recvTimingResp(), Cache::recvTimingSnoopReq(), Cache::recvTimingSnoopResp(), Cache::sendMSHRQueuePacket(), trySatisfyFunctional(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), SnoopFilter::updateSnoopResponse(), and Gicv3::write().
isUpgrade()
bool Packet::isUpgrade () const inline
Definition at line 530 of file packet.hh.
References MemCmd::isUpgrade().
Referenced by Cache::createMissPacket(), BaseCache::satisfyRequest(), and MSHR::TargetList::updateFlags().
isWholeLineWrite()
bool Packet::isWholeLineWrite (unsigned blk_size) inline
Definition at line 559 of file packet.hh.
References getOffset(), MemCmd::WriteLineReq, and MemCmd::WriteReq.
Referenced by NoncoherentCache::handleAtomicReqMiss(), and Cache::handleAtomicReqMiss().
isWrite()
bool Packet::isWrite () const inline
Definition at line 529 of file packet.hh.
References MemCmd::isWrite().
Referenced by Cache::access(), AbstractMemory::access(), BaseCache::access(), SimpleCache::accessFunctional(), SimpleCache::accessTiming(), DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), WriteQueueEntry::allocate(), BaseCache::allocateWriteBuffer(), CacheBlk::checkWrite(), TraceCPU::ElasticDataGen::completeMemAccess(), GarnetSyntheticTraffic::completeRequest(), MemTest::completeRequest(), SimpleMemDelay::delayReq(), SimpleMemDelay::delayResp(), CoherentXBar::forwardPacket(), SMMUTranslRequest::fromPacket(), AbstractMemory::functionalAccess(), Cache::handleAtomicReqMiss(), ArmISA::handleLockedSnoop(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), RubyPort::MemSlavePort::hitCallback(), GPUCoalescer::issueRequest(), DMASequencer::makeRequest(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), sc_gem5::packet2payload(), BasePrefetcher::probeNotify(), ComputeUnit::DataPort::processMemRespEvent(), NoncoherentCache::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), AtomicSimpleCPU::AtomicCPUDPort::recvAtomicSnoop(), RubyPort::MemSlavePort::recvFunctional(), TimingSimpleCPU::DcachePort::recvReqRetry(), NoncoherentCache::recvTimingReq(), SMMUv3SlaveInterface::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SimpleMemory::recvTimingReq(), DRAMSim2::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CommMonitor::recvTimingReq(), CoherentXBar::recvTimingReq(), DRAMCtrl::recvTimingReq(), BaseTrafficGen::recvTimingResp(), AbstractController::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), CommMonitor::recvTimingResp(), BaseCache::recvTimingResp(), TimingSimpleCPU::DcachePort::recvTimingSnoopReq(), Minor::LSQ::recvTimingSnoopReq(), Minor::LSQ::SplitDataRequest::retireResponse(), NoncoherentCache::satisfyRequest(), BaseCache::satisfyRequest(), BaseCache::sendMSHRQueuePacket(), ComputeUnit::sendRequest(), CoherentXBar::sinkPacket(), Minor::LSQ::threadSnoop(), trySatisfyFunctional(), and MSHR::TargetList::updateWriteFlags().
isWriteback()
bool Packet::isWriteback () const inline
Definition at line 547 of file packet.hh.
References MemCmd::isWriteback().
Referenced by NoncoherentCache::access(), BaseCache::access(), NoncoherentCache::handleAtomicReqMiss(), BaseCache::handleTimingReqMiss(), SnoopFilter::lookupSnoop(), and SnoopFilter::updateSnoopResponse().
makeAtomicResponse()
void Packet::makeAtomicResponse () inline
Definition at line 949 of file packet.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), IdeController::dispatchAccess(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), Cache::handleSnoop(), SimpleUart::read(), X86ISA::I8237::read(), MmDisk::read(), DumbTOD::read(), Pl011::read(), AmbaFake::read(), A9SCU::read(), X86ISA::Speaker::read(), IsaFake::read(), TsunamiPChip::read(), Uart8250::read(), X86ISA::Cmos::read(), TsunamiCChip::read(), X86ISA::I8254::read(), X86ISA::I82094AA::read(), X86ISA::I8259::read(), HDLcd::read(), Gicv2m::read(), AlphaBackdoor::read(), PL031::read(), Gicv3::read(), TsunamiIO::read(), EnergyCtrl::read(), Pl050::read(), Iob::read(), X86ISA::I8042::read(), GpuDispatcher::read(), I2CBus::read(), Gicv3Its::read(), Sp804::read(), A9GlobalTimer::read(), RealViewCtrl::read(), CpuLocalTimer::read(), CopyEngine::read(), X86ISA::Interrupts::read(), GenericPciHost::read(), NSGigE::read(), Pl111::read(), IGbE::read(), IdeController::readConfig(), PciDevice::readConfig(), SMMUv3::readControl(), GicV2::readCpu(), VGic::readCtrl(), GicV2::readDistributor(), VGic::readVCpu(), BaseCache::recvAtomic(), X86ISA::Interrupts::recvMessage(), SimpleUart::write(), X86ISA::I8237::write(), MmDisk::write(), NoMaliGpu::write(), Pl011::write(), AmbaFake::write(), X86ISA::Speaker::write(), A9SCU::write(), TsunamiPChip::write(), IsaFake::write(), Uart8250::write(), X86ISA::Cmos::write(), TsunamiCChip::write(), X86ISA::I8254::write(), X86ISA::I82094AA::write(), X86ISA::I8259::write(), HDLcd::write(), Gicv2m::write(), AlphaBackdoor::write(), PL031::write(), Gicv3::write(), TsunamiIO::write(), EnergyCtrl::write(), Pl050::write(), Iob::write(), X86ISA::I8042::write(), GpuDispatcher::write(), Gicv3Its::write(), Sp804::write(), A9GlobalTimer::write(), RealViewCtrl::write(), CpuLocalTimer::write(), CopyEngine::write(), X86ISA::Interrupts::write(), NSGigE::write(), Pl111::write(), IGbE::write(), IdeController::writeConfig(), PciDevice::writeConfig(), SMMUv3::writeControl(), GicV2::writeCpu(), VGic::writeCtrl(), GicV2::writeDistributor(), and VGic::writeVCpu().
makeReadCmd()
static MemCmd Packet::makeReadCmd (const RequestPtr & req) inline static
Generate the appropriate read MemCmd based on the Request flags.
Definition at line 877 of file packet.hh.
References MemCmd::LoadLockedReq, MemCmd::ReadReq, MemCmd::SoftPFExReq, and MemCmd::SoftPFReq.
Referenced by AtomicSimpleCPU::readMem().
makeResponse()
void Packet::makeResponse () inline
Take a request packet and modify it in place to be suitable for returning as a response to that request.
Definition at line 937 of file packet.hh.
References Flags< T >::clear(), MemCmd::isRequest(), MemCmd::needsResponse(), and MemCmd::responseCommand().
Referenced by AbstractMemory::access(), SimpleCache::accessTiming(), AbstractMemory::functionalAccess(), BaseCache::functionalAccess(), SimpleCache::handleFunctional(), SimpleCache::handleResponse(), RubyPort::MemSlavePort::hitCallback(), StubSlavePort::processResponseEvent(), MmioVirtIO::read(), PciVirtIO::read(), NoMaliGpu::read(), GenericTimerMem::read(), UFSHostDevice::read(), VirtIODeviceBase::readConfigBlob(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), MemDelay::SlavePort::recvFunctional(), NoncoherentXBar::recvFunctional(), SerialLink::SerialLinkSlavePort::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), CoherentXBar::recvFunctional(), MemDelay::MasterPort::recvFunctionalSnoop(), CoherentXBar::recvFunctionalSnoop(), RubyPort::MemSlavePort::recvTimingReq(), CoherentXBar::recvTimingReq(), Minor::LSQ::SplitDataRequest::retireResponse(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendSplitData(), SerialLink::SerialLinkMasterPort::trySatisfyFunctional(), Bridge::BridgeMasterPort::trySatisfyFunctional(), Minor::LSQ::tryToSendToTransfers(), MmioVirtIO::write(), PciVirtIO::write(), GenericTimerMem::write(), UFSHostDevice::write(), and VirtIODeviceBase::writeConfigBlob().
makeTimingResponse()
void Packet::makeTimingResponse () inline
Definition at line 955 of file packet.hh.
Referenced by SMMUTranslationProcess::completeTransaction(), BaseCache::handleTimingReqHit(), Cache::handleTimingReqMiss(), X86ISA::GpuTLB::handleTranslationReturn(), LdsState::process(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), and TLBCoalescer::updatePhysAddresses().
makeWriteCmd()
static MemCmd Packet::makeWriteCmd (const RequestPtr & req) inline static
Generate the appropriate write MemCmd based on the Request flags.
Definition at line 893 of file packet.hh.
References MemCmd::CleanInvalidReq, MemCmd::CleanSharedReq, MemCmd::InvalidateReq, MemCmd::StoreCondReq, MemCmd::SwapReq, and MemCmd::WriteReq.
Referenced by AtomicSimpleCPU::amoMem(), and AtomicSimpleCPU::writeMem().
masterId()
MasterID Packet::masterId () const inline
Definition at line 712 of file packet.hh.
Referenced by DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), QoS::LrgQueuePolicy::enqueuePacket(), and QoS::MemCtrl::qosSchedule().
matchAddr() [1/2]
bool Packet::matchAddr (const Addr addr, const bool is_secure) const
Check if packet corresponds to a given address and address space.
Parameters
addr The address to compare against.
is_secure Whether addr belongs to the secure address space.
Returns
Whether packet matches description.
Definition at line 411 of file packet.cc.
References getAddr(), and isSecure().
Referenced by matchAddr(), and Cache::serviceMSHRTargets().
matchAddr() [2/2]
bool Packet::matchAddr (const PacketPtr pkt) const
Check if this packet refers to the same address and address space as another packet.
Parameters
pkt The packet to compare against.
Returns
Whether packet matches description.
Definition at line 417 of file packet.cc.
References getAddr(), isSecure(), and matchAddr().
matchBlockAddr() [1/2]
bool Packet::matchBlockAddr (const Addr addr, const bool is_secure, const int blk_size) const
Check if packet corresponds to a given block-aligned address and address space.
Parameters
addr The address to compare against.
is_secure Whether addr belongs to the secure address space.
blk_size Block size in bytes.
Returns
Whether packet matches description.
Definition at line 397 of file packet.cc.
References getBlockAddr(), and isSecure().
Referenced by WriteQueueEntry::allocate(), MSHR::allocate(), WriteQueueEntry::matchBlockAddr(), MSHR::matchBlockAddr(), and matchBlockAddr().
matchBlockAddr() [2/2]
bool Packet::matchBlockAddr (const PacketPtr pkt, const int blk_size) const
Check if this packet refers to the same block-aligned address and address space as another packet.
Parameters
pkt The packet to compare against.
blk_size Block size in bytes.
Returns
Whether packet matches description.
Definition at line 404 of file packet.cc.
References getBlockAddr(), isSecure(), and matchBlockAddr().
mustCheckAbove()
bool Packet::mustCheckAbove () const inline
Does the request need to check for cached copies of the same block in the memory hierarchy above.
Definition at line 1290 of file packet.hh.
References MemCmd::HardPFReq, and MemCmd::isEviction().
Referenced by Cache::handleSnoop(), and Cache::recvTimingSnoopReq().
needsResponse()
bool Packet::needsResponse () const inline
Definition at line 542 of file packet.hh.
References MemCmd::needsResponse().
Referenced by AbstractMemory::access(), BaseCache::access(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), SimpleCache::accessTiming(), BaseTrafficGen::allocateWaitingRespSlot(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), NoncoherentCache::createMissPacket(), Cache::createMissPacket(), Cache::doTimingSupplyResponse(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), Cache::handleSnoop(), MSHR::handleSnoop(), BaseCache::handleTimingReqHit(), Cache::handleTimingReqMiss(), RubyPort::MemSlavePort::hitCallback(), SnoopFilter::lookupRequest(), QoS::MemSinkCtrl::processNextReqEvent(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), CommMonitor::recvAtomic(), BaseCache::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), RubyPort::MemSlavePort::recvFunctional(), NoncoherentXBar::recvFunctional(), CoherentXBar::recvFunctional(), CoherentXBar::recvFunctionalSnoop(), SimpleTimingPort::recvTimingReq(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), CommMonitor::recvTimingReq(), CoherentXBar::recvTimingReq(), Cache::recvTimingSnoopReq(), Minor::LSQ::SplitDataRequest::retireResponse(), CoherentXBar::sinkPacket(), and Minor::Fetch1::tryToSendToTransfers().
needsWritable()
bool Packet::needsWritable () const inline
Definition at line 533 of file packet.hh.
References MemCmd::isRequest(), and MemCmd::needsWritable().
Referenced by BaseCache::access(), MSHR::allocateTarget(), Cache::handleAtomicReqMiss(), Cache::handleSnoop(), MSHR::handleSnoop(), BaseCache::handleTimingReqMiss(), SnoopFilter::lookupSnoop(), Cache::recvAtomic(), Cache::recvTimingReq(), Cache::recvTimingSnoopReq(), Cache::satisfyRequest(), Cache::serviceMSHRTargets(), CoherentXBar::sinkPacket(), and MSHR::TargetList::updateFlags().
popLabel()
void Packet::popLabel () inline
Pop label for PrintReq (safe to call unconditionally).
Definition at line 1336 of file packet.hh.
References MemCmd::isPrint(), and safe_cast().
Referenced by BaseCache::functionalAccess(), QoS::MemSinkCtrl::MemoryPort::recvFunctional(), DRAMCtrl::MemoryPort::recvFunctional(), SimpleMemory::recvFunctional(), SerialLink::SerialLinkSlavePort::recvFunctional(), DRAMSim2::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), QoS::MemSinkCtrl::recvFunctional(), Queue< WriteQueueEntry >::trySatisfyFunctional(), and PacketQueue::trySatisfyFunctional().
popSenderState()
Packet::SenderState * Packet::popSenderState ()
Pop the top of the state stack and return a pointer to it.
This assumes the current sender state is not NULL. This should be preferred over direct manipulation of the senderState member variable.
Returns
The current top of the stack
Definition at line 327 of file packet.cc.
References Packet::SenderState::predecessor, and senderState.
Referenced by SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvTimingResp(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), CommMonitor::recvTimingReq(), RubyPort::MemMasterPort::recvTimingResp(), Gicv3Its::recvTimingResp(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp(), X86ISA::Walker::recvTimingResp(), Minor::Fetch1::recvTimingResp(), BaseCache::recvTimingResp(), Minor::LSQ::recvTimingResp(), RubyPort::ruby_hit_callback(), and X86ISA::Walker::sendTiming().
print() [1/2]
void Packet::print (std::ostream & o, int verbosity = 0, const std::string & prefix = "") const virtual
Implements Printable.
Definition at line 376 of file packet.cc.
References ccprintf(), cmdString(), getAddr(), getSize(), isExpressSnoop(), and req.
Referenced by Cache::access(), AbstractMemory::access(), BaseCache::access(), SimpleCache::accessTiming(), BaseCache::allocateWriteBuffer(), Cache::cleanEvictBlk(), NoncoherentCache::createMissPacket(), Cache::createMissPacket(), Cache::doTimingSupplyResponse(), CoherentXBar::forwardTiming(), BaseCache::functionalAccess(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), Cache::handleSnoop(), MSHR::handleSnoop(), BaseCache::handleTimingReqHit(), BaseCache::handleTimingReqMiss(), SimpleCache::insert(), SnoopFilter::lookupRequest(), SnoopFilter::lookupSnoop(), Cache::recvAtomic(), BaseCache::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), NoncoherentCache::recvAtomicSnoop(), CoherentXBar::recvAtomicSnoop(), CoherentXBar::recvFunctional(), CoherentXBar::recvFunctionalSnoop(), SimpleCache::CPUSidePort::recvRespRetry(), Cache::recvTimingReq(), SimpleCache::CPUSidePort::recvTimingReq(), CoherentXBar::recvTimingReq(), BaseTrafficGen::recvTimingResp(), CoherentXBar::recvTimingResp(), BaseCache::recvTimingResp(), NoncoherentCache::recvTimingSnoopReq(), Cache::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopReq(), NoncoherentCache::recvTimingSnoopResp(), Cache::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), BaseCache::satisfyRequest(), Cache::sendMSHRQueuePacket(), BaseCache::sendMSHRQueuePacket(), SimpleCache::CPUSidePort::sendPacket(), BaseCache::sendWriteQueuePacket(), Cache::serviceMSHRTargets(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopForward(), SnoopFilter::updateSnoopResponse(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
print() [2/2]
std::string Packet::print () const
A no-args wrapper of print(std::ostream...) meant to be invoked from DPRINTFs avoiding string overheads in fast mode.
Returns
string with the request's type and start<->end addresses
Definition at line 390 of file packet.cc.
pushLabel()
void Packet::pushLabel (const std::string & lbl) inline
Push label for PrintReq (safe to call unconditionally).
Definition at line 1326 of file packet.hh.
References MemCmd::isPrint(), and safe_cast().
Referenced by BaseCache::functionalAccess(), QoS::MemSinkCtrl::MemoryPort::recvFunctional(), DRAMCtrl::MemoryPort::recvFunctional(), SimpleMemory::recvFunctional(), SerialLink::SerialLinkSlavePort::recvFunctional(), DRAMSim2::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), QoS::MemSinkCtrl::recvFunctional(), Queue< WriteQueueEntry >::trySatisfyFunctional(), and PacketQueue::trySatisfyFunctional().
pushSenderState()
void Packet::pushSenderState (Packet::SenderState * sender_state)
Push a new sender state to the packet and make the current sender state the predecessor of the new one.
This should be prefered over direct manipulation of the senderState member variable.
Parameters
sender_state SenderState to push at the top of the stack
Definition at line 319 of file packet.cc.
References Packet::SenderState::predecessor, and senderState.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), Minor::makePacketForRequest(), RubyPort::MemSlavePort::recvAtomic(), RubyPort::MemSlavePort::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), CommMonitor::recvTimingReq(), SMMUv3::runProcessTiming(), Gicv3Its::runProcessTiming(), BaseCache::sendMSHRQueuePacket(), and X86ISA::Walker::sendTiming().
qosValue() [1/2]
uint8_t Packet::qosValue () const inline
QoS Value getter Returns 0 if QoS value was never set (constructor default).
Returns
QoS priority value of the packet
Definition at line 701 of file packet.hh.
Referenced by DRAMCtrl::addToReadQueue(), DRAMCtrl::addToWriteQueue(), QoS::MemSinkCtrl::processNextReqEvent(), QoS::MemCtrl::qosSchedule(), QoS::MemSinkCtrl::recvTimingReq(), and QoS::MemCtrl::schedule().
qosValue() [2/2]
void Packet::qosValue (const uint8_t qos_value) inline
QoS Value setter Interface for setting QoS priority value of the packet.
Parameters
qos_value QoS priority value
Definition at line 709 of file packet.hh.
responderHadWritable()
bool Packet::responderHadWritable () const inline
Definition at line 651 of file packet.hh.
References Flags< T >::isSet().
Referenced by Cache::recvAtomic(), Cache::recvTimingReq(), and CoherentXBar::sinkPacket().
satisfied()
bool Packet::satisfied () const inline
Definition at line 687 of file packet.hh.
References Flags< T >::isSet().
Referenced by Cache::handleSnoop(), CoherentXBar::recvAtomicBackdoor(), and CoherentXBar::recvTimingReq().
set()
template<typename T > void Packet::set (T v, ByteOrder endian) inline
Set the value in the data pointer to v using the specified endianness.
Definition at line 116 of file packet_access.hh.
References BigEndianByteOrder, LittleEndianByteOrder, panic, and ArmISA::v.
Referenced by handlePseudoInst(), and LSQ< Impl >::SplitDataRequest::SplitDataRequest().
setAddr()
void Packet::setAddr (Addr _addr) inline
Update the address of this packet mid-transaction.
This is used by the address mapper to change an already set address to a new one based on the system configuration. It is intended to remap an existing address, so it asserts that the current address is valid.
Definition at line 734 of file packet.hh.
References Flags< T >::isSet().
Referenced by SMMUTranslationProcess::completeTransaction(), AddrMapper::recvAtomic(), AddrMapper::recvAtomicSnoop(), AddrMapper::recvFunctional(), AddrMapper::recvFunctionalSnoop(), AddrMapper::recvTimingReq(), and AddrMapper::recvTimingResp().
setBadAddress()
void Packet::setBadAddress () inline
Definition at line 718 of file packet.hh.
References MemCmd::BadAddressError, and MemCmd::isResponse().
Referenced by IsaFake::read(), AlphaBackdoor::read(), and IsaFake::write().
setBE()
template<typename T > void Packet::setBE (T v) inline
Set the value in the data pointer to v as big endian.
Definition at line 102 of file packet_access.hh.
References htobe(), and setRaw().
Referenced by SparcISA::TLB::doMmuRegRead(), DumbTOD::read(), Iob::readIob(), and Iob::readJBus().
setBlockCached()
void Packet::setBlockCached () inline
Definition at line 691 of file packet.hh.
References Flags< T >::set().
Referenced by Cache::doWritebacks(), Cache::handleSnoop(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), and Cache::recvTimingSnoopReq().
setCacheResponding()
void Packet::setCacheResponding () inline
Snoop flags.
Set the cacheResponding flag. This is used by the caches to signal another cache that they are responding to a request. A cache will only respond to snoops if it has the line in either Modified or Owned state. Note that on snoop hits we always pass the line as Modified and never Owned. In the case of an Owned line we proceed to invalidate all other copies.
On a cache fill (see Cache::handleFill), we check hasSharers first, ignoring the cacheResponding flag if hasSharers is set. A line is consequently allocated as:
hasSharers cacheResponding state true false Shared true true Shared false false Exclusive false true Modified
Definition at line 585 of file packet.hh.
References MemCmd::isRequest(), Flags< T >::isSet(), and Flags< T >::set().
Referenced by Cache::handleSnoop(), MSHR::handleSnoop(), Cache::recvTimingSnoopReq(), Cache::satisfyRequest(), and BaseCache::satisfyRequest().
setData()
void Packet::setData (const uint8_t * p) inline
Copy data into the packet from the provided pointer.
Definition at line 1158 of file packet.hh.
References Flags< T >::isSet().
Referenced by AbstractMemory::access(), GPUCoalescer::atomicCallback(), BaseCache::cmpAndSwap(), AbstractMemory::functionalAccess(), X86ISA::handleIprRead(), Sequencer::hitCallback(), GPUCoalescer::hitCallback(), X86ISA::Interrupts::read(), VirtIODeviceBase::readConfigBlob(), BaseCache::satisfyRequest(), and Cache::serviceMSHRTargets().
setDataFromBlock()
void Packet::setDataFromBlock (const uint8_t * blk_data, int blkSize) inline
Copy data into the packet from the provided block pointer, which is aligned to the given block size.
Definition at line 1177 of file packet.hh.
References getOffset().
Referenced by SimpleCache::accessFunctional(), Cache::handleSnoop(), BaseCache::satisfyRequest(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
setExpressSnoop()
void Packet::setExpressSnoop () inline
The express snoop flag is used for two purposes.
Firstly, it is used to bypass flow control for normal (non-snoop) requests going downstream in the memory system. In cases where a cache is responding to a snoop from another cache (it had a dirty line), but the line is not writable (and there are possibly other copies), the express snoop flag is set by the downstream cache to invalidate all other copies in zero time. Secondly, the express snoop flag is also set to be able to distinguish snoop packets that came from a downstream cache, rather than snoop packets from neighbouring caches.
Definition at line 633 of file packet.hh.
References Flags< T >::set().
Referenced by Cache::handleSnoop(), Cache::isCachedAbove(), and CoherentXBar::recvTimingReq().
setFunctionalResponseStatus()
void Packet::setFunctionalResponseStatus (bool success) inline
Definition at line 961 of file packet.hh.
References MemCmd::FunctionalReadError, MemCmd::FunctionalWriteError, and MemCmd::isWrite().
Referenced by RubyPort::MemSlavePort::recvFunctional().
setHasSharers()
void Packet::setHasSharers () inline
On fills, the hasSharers flag is used by the caches in combination with the cacheResponding flag, as clarified above.
If the hasSharers flag is not set, the packet is passing writable. Thus, a response from a memory passes the line as writable by default.
The hasSharers flag is also used by upstream caches to inform a downstream cache that they have the block (by calling setHasSharers on snoop request packets that hit in upstream cachs tags or MSHRs). If the snoop packet has sharers, a downstream cache is prevented from passing a dirty line upwards if it was not explicitly asked for a writable copy. See Cache::satisfyCpuSideRequest.
The hasSharers flag is also used on writebacks, in combination with the WritbackClean or WritebackDirty commands, to allocate the block downstream either as:
command hasSharers state WritebackDirty false Modified WritebackDirty true Owned WritebackClean false Exclusive WritebackClean true Shared
Definition at line 617 of file packet.hh.
References Flags< T >::set().
Referenced by Cache::createMissPacket(), Cache::handleSnoop(), MSHR::handleSnoop(), Cache::recvTimingSnoopReq(), Cache::satisfyRequest(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
setLE()
template<typename T > void Packet::setLE (T v) inline
Set the value in the data pointer to v as little endian.
Definition at line 109 of file packet_access.hh.
References htole(), and setRaw().
Referenced by CopyEngine::CopyEngineChannel::channelRead(), MmioVirtIO::read(), PciVirtIO::read(), NoMaliGpu::read(), Pl011::read(), AmbaFake::read(), A9SCU::read(), X86ISA::Speaker::read(), IsaFake::read(), TsunamiPChip::read(), X86ISA::Cmos::read(), TsunamiCChip::read(), X86ISA::I8254::read(), X86ISA::I82094AA::read(), X86ISA::I8259::read(), HDLcd::read(), Gicv2m::read(), AlphaBackdoor::read(), PL031::read(), Sp804::Timer::read(), TsunamiIO::read(), EnergyCtrl::read(), A9GlobalTimer::Timer::read(), X86ISA::I8042::read(), CpuLocalTimer::Timer::read(), GpuDispatcher::read(), RealViewCtrl::read(), CopyEngine::read(), Sinic::Device::read(), GenericTimerMem::read(), NSGigE::read(), Pl111::read(), IGbE::read(), UFSHostDevice::read(), IdeController::readConfig(), PciDevice::readConfig(), SMMUv3::readControl(), GicV2::readCpu(), VGic::readCtrl(), GicV2::readDistributor(), AmbaDevice::readId(), VGic::readVCpu(), and X86ISA::Walker::WalkerState::stepWalk().
setRaw()
template<typename T > void Packet::setRaw (T v) inline
Set the value in the data pointer to v without byte swapping.
Definition at line 62 of file packet_access.hh.
References data, DYNAMIC_DATA, flags, Flags< T >::isSet(), size, and STATIC_DATA.
Referenced by X86ISA::buildIntPacket(), MmDisk::read(), Uart8250::read(), I2CBus::read(), setBE(), and setLE().
setResponderHadWritable()
void Packet::setResponderHadWritable () inline
On responding to a snoop request (which only happens for Modified or Owned lines), make sure that we can transform an Owned response to a Modified one.
If this flag is not set, the responding cache had the line in the Owned state, and there are possibly other Shared copies in the memory system. A downstream cache helps in orchestrating the invalidation of these copies by sending out the appropriate express snoops.
Definition at line 645 of file packet.hh.
References Flags< T >::set().
Referenced by Cache::handleSnoop(), MSHR::handleSnoop(), and Cache::recvTimingSnoopReq().
setSatisfied()
void Packet::setSatisfied () inline
Set when a request hits in a cache and the cache is not going to respond.
This is used by the crossbar to coordinate responses for cache maintenance operations.
Definition at line 681 of file packet.hh.
References MemCmd::isClean(), Flags< T >::isSet(), and Flags< T >::set().
Referenced by Cache::handleSnoop(), MSHR::handleSnoop(), BaseCache::recvAtomic(), and BaseCache::sendMSHRQueuePacket().
setSize()
void Packet::setSize (unsigned size) inline
Definition at line 973 of file packet.hh.
References Flags< T >::isSet(), and Flags< T >::set().
setSuppressFuncError()
void Packet::setSuppressFuncError () inline
Definition at line 689 of file packet.hh.
References Flags< T >::set().
Referenced by Shader::doFunctionalAccess().
setUintX()
void Packet::setUintX (uint64_t w, ByteOrder endian)
Set the value in the word w after truncating it to the length of the packet and then byteswapping it to the desired endianness.
Definition at line 354 of file packet.cc.
References getSize(), and panic.
Referenced by SimpleUart::read(), Gicv3::read(), Pl050::read(), and Gicv3Its::read().
setWriteThrough()
void Packet::setWriteThrough () inline
A writeback/writeclean cmd gets propagated further downstream by the receiver when the flag is set.
Definition at line 667 of file packet.hh.
References MemCmd::isEviction(), MemCmd::isWrite(), Flags< T >::set(), and MemCmd::WriteClean.
Referenced by BaseCache::writecleanBlk().
suppressFuncError()
bool Packet::suppressFuncError () const inline
Definition at line 690 of file packet.hh.
References Flags< T >::isSet().
Referenced by RubyPort::MemSlavePort::recvFunctional().
trySatisfyFunctional() [1/2]
bool Packet::trySatisfyFunctional (PacketPtr other) inline
Check a functional request against a memory value stored in another packet (i.e.
an in-transit request or response). Returns true if the current packet is a read, and the other packet provides the data, which is then copied to the current packet. If the current packet is a write, and the other packet intersects this one, then we update the data accordingly.
Definition at line 1264 of file packet.hh.
References getAddr(), getPtr(), getSize(), hasData(), isMaskedWrite(), isSecure(), and warn.
Referenced by BaseCache::functionalAccess(), SimpleMemory::recvFunctional(), SerialLink::SerialLinkSlavePort::recvFunctional(), DRAMSim2::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), WriteQueueEntry::TargetList::trySatisfyFunctional(), WriteQueueEntry::trySatisfyFunctional(), PacketQueue::trySatisfyFunctional(), SerialLink::SerialLinkMasterPort::trySatisfyFunctional(), MSHR::TargetList::trySatisfyFunctional(), Bridge::BridgeMasterPort::trySatisfyFunctional(), and MSHR::trySatisfyFunctional().
trySatisfyFunctional() [2/2]
bool Packet::trySatisfyFunctional (Printable * obj, Addr base, bool is_secure, int size, uint8_t * _data)
Check a functional request against a memory value represented by a base/size pair and an associated data array.
If the current packet is a read, it may be satisfied by the memory value. If the current packet is a write, it may update the memory value.
Definition at line 234 of file packet.cc.
References _isSecure, addr, bytesValid, cmdString(), getAddr(), getSize(), ArmISA::i, isPrint(), isRead(), isWrite(), panic, safe_cast(), and senderState.
writeData()
void Packet::writeData (uint8_t * p) const inline
Copy data from the packet to the memory at the provided pointer.
Parameters
p Pointer to which data will be copied.
Definition at line 1187 of file packet.hh.
References X86ISA::base, and ArmISA::i.
Referenced by AbstractMemory::access(), BaseCache::cmpAndSwap(), AbstractMemory::functionalAccess(), X86ISA::handleIprWrite(), Sequencer::hitCallback(), MemCheckerMonitor::recvTimingReq(), MemCheckerMonitor::recvTimingResp(), X86ISA::Interrupts::write(), and VirtIODeviceBase::writeConfigBlob().
writeDataToBlock()
void Packet::writeDataToBlock (uint8_t * blk_data, int blkSize) const inline
Copy data from the packet to the provided block pointer, which is aligned to the given block size.
Parameters
blk_data Pointer to block to which data will be copied.
blkSize Block size in bytes.
Definition at line 1211 of file packet.hh.
References getOffset().
Referenced by BaseCache::access(), SimpleCache::accessFunctional(), BaseCache::handleFill(), SimpleCache::insert(), and BaseCache::satisfyRequest().
writeThrough()
bool Packet::writeThrough () const inline
Definition at line 674 of file packet.hh.
References Flags< T >::isSet().
Referenced by BaseCache::access().
Member Data Documentation
_isSecure
bool Packet::_isSecure private
True if the request targets the secure memory space.
Definition at line 344 of file packet.hh.
Referenced by trySatisfyFunctional().
_qosValue
uint8_t Packet::_qosValue private
Definition at line 355 of file packet.hh.
addr
Addr Packet::addr private
The address of the request.
This address could be virtual or physical, depending on the system configuration.
Definition at line 341 of file packet.hh.
Referenced by trySatisfyFunctional().
bytesValid
std::vector<bool> Packet::bytesValid private
Track the bytes found that satisfy a functional read.
Definition at line 352 of file packet.hh.
Referenced by trySatisfyFunctional().
cmd
MemCmd Packet::cmd
The command field of the packet.
Definition at line 322 of file packet.hh.
Referenced by NoncoherentCache::access(), AbstractMemory::access(), BaseCache::access(), WriteQueueEntry::allocate(), MSHR::allocate(), MSHR::allocateTarget(), BaseCache::allocateWriteBuffer(), TimingSimpleCPU::buildSplitPacket(), copyError(), Cache::createMissPacket(), Cache::doWritebacks(), Cache::doWritebacksAtomic(), MSHR::extractServiceableTargets(), CoherentXBar::forwardAtomic(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), BaseCache::handleFill(), MSHR::handleSnoop(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), RubyPort::MemSlavePort::hitCallback(), Cache::isCachedAbove(), BOPPrefetcher::notifyFill(), BasePrefetcher::observeAccess(), BasePrefetcher::probeNotify(), ComputeUnit::DataPort::processMemRespEvent(), Cache::promoteWholeLineWrites(), X86ISA::IntSlavePort< X86ISA::Interrupts >::recvAtomic(), RubyPort::MemSlavePort::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicSnoop(), X86ISA::Interrupts::recvMessage(), RubyPort::MemSlavePort::recvTimingReq(), CoherentXBar::recvTimingReq(), NoncoherentCache::recvTimingResp(), BaseCache::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), ComputeUnit::ITLBPort::recvTimingResp(), Minor::LSQ::recvTimingResp(), Cache::recvTimingSnoopResp(), replaceUpgrade(), Cache::satisfyRequest(), BaseCache::satisfyRequest(), Cache::sendMSHRQueuePacket(), ComputeUnit::sendRequest(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), X86ISA::Walker::WalkerState::stepWalk(), and MSHR::TargetList::updateFlags().
data
PacketDataPtr Packet::data private
A pointer to the data being transferred.
It can be different sizes at each level of the hierarchy so it belongs to the packet, not request. This may or may not be populated when a responder receives the packet. If not populated memory should be allocated.
Definition at line 337 of file packet.hh.
Referenced by getRaw(), Packet(), and setRaw().
flags
Flags Packet::flags private
Definition at line 316 of file packet.hh.
Referenced by copyResponderFlags(), getRaw(), Packet(), and setRaw().
headerDelay
uint32_t Packet::headerDelay
The extra delay from seeing the packet until the header is transmitted.
This delay is used to communicate the crossbar forwarding latency to the neighbouring object (e.g. a cache) that actually makes the packet wait. As the delay is relative, a 32-bit unsigned should be sufficient.
Definition at line 366 of file packet.hh.
Referenced by BaseCache::access(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), BaseXBar::calcPacketTiming(), BaseCache::handleFill(), Cache::handleSnoop(), BaseCache::handleTimingReqHit(), BaseCache::handleUncacheableWriteResp(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvTimingResp(), StubSlavePort::processResponseEvent(), GenericPciHost::read(), PioPort< X86ISA::Interrupts >::recvAtomic(), X86ISA::IntSlavePort< X86ISA::Interrupts >::recvAtomic(), SMMUControlPort::recvAtomic(), X86ISA::Walker::WalkerState::recvPacket(), HMCController::recvTimingReq(), SMMUv3SlaveInterface::recvTimingReq(), NoncoherentXBar::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), CoherentXBar::recvTimingReq(), BaseCache::recvTimingReq(), Gicv3Its::recvTimingResp(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp(), NoncoherentXBar::recvTimingResp(), SerialLink::SerialLinkMasterPort::recvTimingResp(), CoherentXBar::recvTimingResp(), Bridge::BridgeMasterPort::recvTimingResp(), BaseCache::recvTimingResp(), CoherentXBar::recvTimingSnoopReq(), Cache::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), SMMUv3::runProcessTiming(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), and GenericPciHost::write().
id
const PacketId Packet::id
Definition at line 324 of file packet.hh.
Referenced by Cache::handleSnoop(), MSHR::handleSnoop(), BaseCache::recvAtomic(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvTimingReq(), and BaseCache::sendMSHRQueuePacket().
payloadDelay
uint32_t Packet::payloadDelay
The extra pipelining delay from seeing the packet until the end of payload is transmitted by the component that provided it (if any).
This includes the header delay. Similar to the header delay, this is used to make up for the fact that the crossbar does not make the packet wait. As the delay is relative, a 32-bit unsigned should be sufficient.
Definition at line 384 of file packet.hh.
Referenced by BaseCache::access(), DRAMSim2::accessAndRespond(), DRAMCtrl::accessAndRespond(), BaseCache::allocateWriteBuffer(), SMMUv3SlaveInterface::atsMasterRecvTimingResp(), SMMUv3SlaveInterface::atsSlaveRecvTimingReq(), BaseXBar::calcPacketTiming(), BaseCache::handleFill(), Cache::handleSnoop(), BaseCache::handleTimingReqHit(), BaseCache::handleUncacheableWriteResp(), SMMUv3::masterRecvTimingResp(), SMMUv3::masterTableWalkRecvTimingResp(), StubSlavePort::processResponseEvent(), GenericPciHost::read(), PioPort< X86ISA::Interrupts >::recvAtomic(), X86ISA::IntSlavePort< X86ISA::Interrupts >::recvAtomic(), SMMUControlPort::recvAtomic(), NoncoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicBackdoor(), CoherentXBar::recvAtomicSnoop(), X86ISA::Walker::WalkerState::recvPacket(), HMCController::recvTimingReq(), SMMUv3SlaveInterface::recvTimingReq(), NoncoherentXBar::recvTimingReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), SerialLink::SerialLinkSlavePort::recvTimingReq(), SimpleMemory::recvTimingReq(), Bridge::BridgeSlavePort::recvTimingReq(), CoherentXBar::recvTimingReq(), BaseCache::recvTimingReq(), Gicv3Its::recvTimingResp(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::recvTimingResp(), NoncoherentXBar::recvTimingResp(), SerialLink::SerialLinkMasterPort::recvTimingResp(), CoherentXBar::recvTimingResp(), Bridge::BridgeMasterPort::recvTimingResp(), BaseCache::recvTimingResp(), Cache::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), SMMUv3::runProcessTiming(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), GenericPciHost::write(), BaseCache::writebackBlk(), and BaseCache::writecleanBlk().
req
RequestPtr Packet::req
A pointer to the original request.
Definition at line 327 of file packet.hh.
Referenced by Cache::access(), AbstractMemory::access(), BaseCache::access(), SimpleCache::accessTiming(), Minor::ForwardLineData::adoptPacketData(), WriteQueueEntry::allocate(), MSHR::allocate(), MSHR::allocateTarget(), BaseTrafficGen::allocateWaitingRespSlot(), TLBCoalescer::canCoalesce(), Minor::LSQ::StoreBuffer::canForwardDataToLoad(), AbstractMemory::checkLockedAddrList(), CacheBlk::checkWrite(), BaseCache::cmpAndSwap(), BaseO3DynInst< Impl >::completeAcc(), TimingSimpleCPU::completeDataAccess(), TimingSimpleCPU::completeIfetch(), GPUCoalescer::completeIssue(), TraceCPU::ElasticDataGen::completeMemAccess(), GarnetSyntheticTraffic::completeRequest(), MemTest::completeRequest(), SMMUTranslationProcess::completeTransaction(), NoncoherentCache::createMissPacket(), Cache::createMissPacket(), QueuedPrefetcher::DeferredPacket::createPkt(), QueuedPrefetcher::createPrefetchRequest(), Shader::doFunctionalAccess(), SparcISA::TLB::doMmuRegRead(), SparcISA::TLB::doMmuRegWrite(), AddressMonitor::doMonitor(), Cache::doTimingSupplyResponse(), FetchUnit::fetch(), SMMUTranslRequest::fromPacket(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), BaseCache::getNextQueueEntry(), Cache::handleAtomicReqMiss(), X86ISA::GpuTLB::handleFuncTranslationReturn(), Sequencer::handleLlsc(), GPUCoalescer::handleLlsc(), TimingSimpleCPU::handleReadPacket(), DmaPort::handleResp(), SimpleMemobj::handleResponse(), Cache::handleSnoop(), MSHR::handleSnoop(), Cache::handleTimingReqHit(), Cache::handleTimingReqMiss(), BaseCache::handleTimingReqMiss(), X86ISA::GpuTLB::handleTranslationReturn(), TimingSimpleCPU::handleWritePacket(), RubyPort::MemSlavePort::hitCallback(), Sequencer::hitCallback(), BaseCache::incHitCount(), BaseCache::incMissCount(), QueuedPrefetcher::insert(), BaseTags::insertBlock(), GPUCoalescer::insertRequest(), CoherentXBar::isDestination(), GenericISA::isGenericIprAccess(), Sequencer::issueRequest(), GPUCoalescer::issueRequest(), X86ISA::GpuTLB::issueTLBLookup(), SnoopFilter::lookupRequest(), SnoopFilter::lookupSnoop(), ItsTranslation::main(), VIPERCoalescer::makeRequest(), Sequencer::makeRequest(), GPUCoalescer::makeRequest(), BaseCPU::mwait(), BasePrefetcher::observeAccess(), AMBA::orderId(), sc_gem5::packet2payload(), X86ISA::GpuTLB::pagingProtectionChecks(), BasePrefetcher::PrefetchInfo::PrefetchInfo(), print(), BasePrefetcher::probeNotify(), DefaultFetch< Impl >::processCacheCompletion(), FetchStage::processFetchReturn(), FetchUnit::processFetchReturn(), ComputeUnit::DataPort::processMemReqEvent(), ComputeUnit::DataPort::processMemRespEvent(), QoS::MemSinkCtrl::processNextReqEvent(), TLBCoalescer::processProbeTLBEvent(), MSHR::promoteWritable(), TsunamiCChip::read(), Gicv3::read(), CpuLocalTimer::read(), Sinic::Device::read(), GicV2::readCpu(), VGic::readCtrl(), GicV2::readDistributor(), Iob::readJBus(), VGic::readVCpu(), Cache::recvAtomic(), BaseCache::recvAtomic(), TLBCoalescer::CpuSidePort::recvFunctional(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), DefaultFetch< Impl >::recvReqRetry(), ComputeUnit::DataPort::recvReqRetry(), ComputeUnit::SQCPort::recvReqRetry(), ComputeUnit::DTLBPort::recvReqRetry(), ComputeUnit::ITLBPort::recvReqRetry(), RubyPort::MemSlavePort::recvTimingReq(), HMCController::recvTimingReq(), NoncoherentXBar::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), QoS::MemSinkCtrl::recvTimingReq(), CoherentXBar::recvTimingReq(), BaseTrafficGen::recvTimingResp(), DefaultFetch< Impl >::IcachePort::recvTimingResp(), DmaPort::recvTimingResp(), NoncoherentXBar::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), X86ISA::GpuTLB::MemSidePort::recvTimingResp(), CoherentXBar::recvTimingResp(), ComputeUnit::DataPort::recvTimingResp(), BaseCache::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), ComputeUnit::ITLBPort::recvTimingResp(), Cache::recvTimingSnoopReq(), CoherentXBar::recvTimingSnoopReq(), Cache::recvTimingSnoopResp(), CoherentXBar::recvTimingSnoopResp(), Minor::LSQ::SplitDataRequest::retireResponse(), QoS::Policy::schedule(), QoS::MemCtrl::schedule(), DmaPort::sendDma(), BaseCache::sendMSHRQueuePacket(), ComputeUnit::sendRequest(), ComputeUnit::sendSyncRequest(), ComputeUnit::LDSPort::sendTimingReq(), NoncoherentCache::serviceMSHRTargets(), Cache::serviceMSHRTargets(), X86ISA::Walker::WalkerState::stepWalk(), AbstractMemory::trackLoadLocked(), CacheBlk::trackLoadLocked(), X86ISA::GpuTLB::translationReturn(), Minor::LSQ::tryToSend(), BaseTrafficGen::update(), TLBCoalescer::updatePhysAddresses(), SnoopFilter::updateResponse(), SnoopFilter::updateSnoopResponse(), MSHR::TargetList::updateWriteFlags(), Gicv3::write(), GpuDispatcher::write(), CpuLocalTimer::write(), Sinic::Device::write(), GicV2::writeCpu(), VGic::writeCtrl(), GicV2::writeDistributor(), Iob::writeJBus(), AbstractMemory::writeOK(), and VGic::writeVCpu().
senderState
SenderState* Packet::senderState
This packet's sender state.
Devices should use dynamic_cast<> to cast to the state appropriate to the sender. The intent of this variable is to allow a device to attach extra information to a request. A response packet must return the sender state that was attached to the original request (even if a new packet is created).
Definition at line 480 of file packet.hh.
Referenced by GPUCoalescer::atomicCallback(), LSQ< Impl >::SplitDataRequest::buildPackets(), TimingSimpleCPU::buildSplitPacket(), TLBCoalescer::canCoalesce(), TimingSimpleCPU::SplitFragmentSenderState::clearFromParent(), LSQUnit< Impl >::completeDataAccess(), TimingSimpleCPU::completeDataAccess(), LSQ< Impl >::completeDataAccess(), LdsState::countBankConflicts(), DmaPort::dmaAction(), FetchUnit::fetch(), AbstractMemory::functionalAccess(), Shader::functionalTLBAccess(), LdsState::getDynInstr(), X86ISA::GpuTLB::handleFuncTranslationReturn(), DmaPort::handleResp(), X86ISA::GpuTLB::handleTranslationReturn(), GPUCoalescer::hitCallback(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), Cache::isCachedAbove(), X86ISA::GpuTLB::issueTLBLookup(), popSenderState(), LdsState::process(), FetchStage::processFetchReturn(), FetchUnit::processFetchReturn(), ComputeUnit::DataPort::processMemReqEvent(), ComputeUnit::DataPort::processMemRespEvent(), TLBCoalescer::processProbeTLBEvent(), pushSenderState(), TLBCoalescer::CpuSidePort::recvFunctional(), X86ISA::GpuTLB::CpuSidePort::recvFunctional(), TimingSimpleCPU::DcachePort::recvReqRetry(), TLBCoalescer::CpuSidePort::recvTimingReq(), RubyTester::CpuPort::recvTimingResp(), AbstractController::recvTimingResp(), MemCheckerMonitor::recvTimingResp(), AddrMapper::recvTimingResp(), CommMonitor::recvTimingResp(), ComputeUnit::DataPort::recvTimingResp(), LSQUnit< Impl >::recvTimingResp(), ComputeUnit::DTLBPort::recvTimingResp(), ComputeUnit::ITLBPort::recvTimingResp(), ComputeUnit::LDSPort::recvTimingResp(), LSQ< Impl >::SingleDataRequest::recvTimingResp(), LSQ< Impl >::SplitDataRequest::recvTimingResp(), LSQ< Impl >::recvTimingResp(), ComputeUnit::sendRequest(), TimingSimpleCPU::sendSplitData(), ComputeUnit::sendSyncRequest(), ComputeUnit::LDSPort::sendTimingReq(), ComputeUnit::sendToLds(), X86ISA::GpuTLB::translationReturn(), trySatisfyFunctional(), LSQUnit< Impl >::trySendPacket(), and TLBCoalescer::updatePhysAddresses().
size
unsigned Packet::size private
The size of the request or transfer.
Definition at line 347 of file packet.hh.
Referenced by getRaw(), and setRaw().
snoopDelay
uint32_t Packet::snoopDelay
Keep track of the extra delay incurred by snooping upwards before sending a request down the memory system.
This is used by the coherent crossbar to account for the additional request delay.
Definition at line 374 of file packet.hh.
Referenced by CoherentXBar::recvTimingReq(), Cache::recvTimingSnoopReq(), and CoherentXBar::recvTimingSnoopReq().
The documentation for this class was generated from the following files:
mem/packet.hh
mem/packet.cc
mem/packet_access.hh