gem5: Stats::ProxyInfo Class Reference
Stats::ProxyInfo Class Reference
#include <statistics.hh>
Public Member Functions
std::string str () const
size_type size () const
bool check () const
Check that this stat has been set up properly and is ready for use.
void prepare ()
Prepare the stat for dumping.
void reset ()
Reset the stat to the default state.
bool zero () const
void visit (Output &visitor)
Visitor entry for outputing statistics data.
Public Member Functions inherited from Stats::ScalarInfo
virtual Counter value () const =0
virtual Result result () const =0
virtual Result total () const =0
Public Member Functions inherited from Stats::Info
Info ()
virtual ~Info ()
void setName (const std::string &name)
Set the name of this statistic.
void setName (const Group *parent, const std::string &name)
void setSeparator (std::string _sep)
bool baseCheck () const
virtual void enable ()
Enable the stat for use.
Additional Inherited Members
Static Public Member Functions inherited from Stats::Info
static bool less (Info *stat1, Info *stat2)
Checks if the first stat's name is alphabetically less than the second.
Public Attributes inherited from Stats::Info
std::string name
The name of the stat.
std::string desc
The description of the stat.
Flags flags
The formatting flags.
int precision
The display precision.
const Info * prereq
A pointer to a prerequisite Stat.
int id
const StorageParams * storageParams
Static Public Attributes inherited from Stats::Info
static std::string separatorString = "::"
The separator string used for vectors, dist, etc.
static int id_count = 0
A unique stat ID for each stat in the simulator.
Detailed Description
Definition at line 773 of file statistics.hh.
Member Function Documentation
check()
bool Stats::ProxyInfo::check () const inline virtual
Check that this stat has been set up properly and is ready for use.
Returns
true for success
Implements Stats::Info.
Definition at line 778 of file statistics.hh.
prepare()
void Stats::ProxyInfo::prepare () inline virtual
Prepare the stat for dumping.
Implements Stats::Info.
Definition at line 779 of file statistics.hh.
reset()
void Stats::ProxyInfo::reset () inline virtual
Reset the stat to the default state.
Implements Stats::Info.
Definition at line 780 of file statistics.hh.
size()
size_type Stats::ProxyInfo::size () const inline
Definition at line 777 of file statistics.hh.
Referenced by Stats::ValueBase< Value >::size().
str()
std::string Stats::ProxyInfo::str () const inline
Definition at line 776 of file statistics.hh.
References sc_dt::to_string().
Referenced by Stats::ValueBase< Value >::str().
visit()
void Stats::ProxyInfo::visit (Output & visitor) inline virtual
Visitor entry for outputing statistics data.
Implements Stats::Info.
Definition at line 783 of file statistics.hh.
References Stats::Output::visit().
zero()
bool Stats::ProxyInfo::zero () const inline virtual
Returns
true if this stat has a value and satisfies its requirement as a prereq
Implements Stats::Info.
Definition at line 781 of file statistics.hh.
Referenced by Stats::ValueBase< Value >::zero().
The documentation for this class was generated from the following file:
base/statistics.hh