gem5: tlm::tlm_generic_payload Class Reference
tlm::tlm_generic_payload Class Reference
#include <gp.hh>
Public Member Functions
tlm_generic_payload ()
tlm_generic_payload (tlm_mm_interface *mm)
void acquire ()
void release ()
int get_ref_count () const
void set_mm (tlm_mm_interface *mm)
bool has_mm () const
void reset ()
void deep_copy_from (const tlm_generic_payload &other)
void update_original_from (const tlm_generic_payload &other, bool use_byte_enable_on_read=true)
void update_extensions_from (const tlm_generic_payload &other)
void free_all_extensions ()
virtual ~tlm_generic_payload ()
bool is_read () const
void set_read ()
bool is_write () const
void set_write ()
tlm_command get_command () const
void set_command (const tlm_command command)
sc_dt::uint64 get_address () const
void set_address (const sc_dt::uint64 address)
unsigned char * get_data_ptr () const
void set_data_ptr (unsigned char *data)
unsigned int get_data_length () const
void set_data_length (const unsigned int length)
bool is_response_ok () const
bool is_response_error () const
tlm_response_status get_response_status () const
void set_response_status (const tlm_response_status response_status)
std::string get_response_string () const
unsigned int get_streaming_width () const
void set_streaming_width (const unsigned int streaming_width)
unsigned char * get_byte_enable_ptr () const
void set_byte_enable_ptr (unsigned char *byte_enable)
unsigned int get_byte_enable_length () const
void set_byte_enable_length (const unsigned int byte_enable_length)
void set_dmi_allowed (bool dmi_allowed)
bool is_dmi_allowed () const
tlm_gp_option get_gp_option () const
void set_gp_option (const tlm_gp_option gp_opt)
template<typename T >
T * set_extension (T *ext)
tlm_extension_base * set_extension (unsigned int index, tlm_extension_base *ext)
template<typename T >
T * set_auto_extension (T *ext)
tlm_extension_base * set_auto_extension (unsigned int index, tlm_extension_base *ext)
template<typename T >
void get_extension (T *&ext) const
template<typename T >
T * get_extension () const
tlm_extension_base * get_extension (unsigned int index) const
template<typename T >
void clear_extension (const T *ext)
template<typename T >
void clear_extension ()
template<typename T >
void release_extension (T *ext)
template<typename T >
void release_extension ()
void resize_extensions ()
Private Member Functions
tlm_generic_payload (const tlm_generic_payload &x)
tlm_generic_payload & operator= (const tlm_generic_payload &x)
void clear_extension (unsigned int index)
void release_extension (unsigned int index)
Private Attributes
sc_dt::uint64 m_address
tlm_command m_command
unsigned char * m_data
unsigned int m_length
tlm_response_status m_response_status
bool m_dmi
unsigned char * m_byte_enable
unsigned int m_byte_enable_length
unsigned int m_streaming_width
tlm_gp_option m_gp_option
tlm_array< tlm_extension_base * > m_extensions
tlm_mm_interface * m_mm
unsigned int m_ref_count
Detailed Description
Definition at line 116 of file gp.hh.
Constructor & Destructor Documentation
tlm_generic_payload() [1/3]
tlm::tlm_generic_payload::tlm_generic_payload ()
Definition at line 100 of file gp.cc.
tlm_generic_payload() [2/3]
tlm::tlm_generic_payload::tlm_generic_payload (tlm_mm_interface * mm) explicit
Definition at line 108 of file gp.cc.
tlm_generic_payload() [3/3]
tlm::tlm_generic_payload::tlm_generic_payload (const tlm_generic_payload & x) private
~tlm_generic_payload()
tlm::tlm_generic_payload::~tlm_generic_payload () virtual
Definition at line 262 of file gp.cc.
References ArmISA::i, and m_extensions.
Member Function Documentation
acquire()
void tlm::tlm_generic_payload::acquire () inline
Definition at line 123 of file gp.hh.
References sc_assert.
Referenced by MultiSocketSimpleSwitchAT::b_transport(), SimpleATInitiator2::SimplePool::claim(), SimpleATInitiator1::SimplePool::claim(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), and sc_gem5::packet2payload().
clear_extension() [1/3]
template<typename T > void tlm::tlm_generic_payload::clear_extension (const T * ext) inline
Definition at line 379 of file gp.hh.
Referenced by adapt_gp2ext< BUSWIDTH >::get_dmi_pointer().
clear_extension() [2/3]
template<typename T > void tlm::tlm_generic_payload::clear_extension () inline
Definition at line 386 of file gp.hh.
References clear_extension(), and Ps2::Keyboard::ID.
Referenced by clear_extension().
clear_extension() [3/3]
void tlm::tlm_generic_payload::clear_extension (unsigned int index) private
Definition at line 330 of file gp.cc.
References MipsISA::index, m_extensions, and sc_assert.
deep_copy_from()
void tlm::tlm_generic_payload::deep_copy_from (const tlm_generic_payload & other)
Definition at line 126 of file gp.cc.
References ArmISA::ext, get_address(), get_byte_enable_length(), get_command(), get_data_length(), get_gp_option(), get_response_status(), get_streaming_width(), has_mm(), ArmISA::i, is_dmi_allowed(), m_address, m_byte_enable, m_byte_enable_length, m_command, m_data, m_dmi, m_extensions, m_gp_option, m_length, m_response_status, m_streaming_width, set_auto_extension(), and set_extension().
free_all_extensions()
void tlm::tlm_generic_payload::free_all_extensions ()
Definition at line 251 of file gp.cc.
References ArmISA::i, and m_extensions.
get_address()
sc_dt::uint64 tlm::tlm_generic_payload::get_address () const inline
Definition at line 184 of file gp.hh.
Referenced by SimpleLTTarget1::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), deep_copy_from(), MultiSocketSimpleSwitchAT::fwPEQcb(), SimpleLTTarget1::get_direct_mem_ptr(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getBackdoor(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport(), MultiSocketSimpleSwitchAT::initiatorNBTransport(), SimpleLTInitiator2::logStartTransation(), SimpleLTInitiator3::logStartTransation(), CoreDecouplingLTInitiator::logStartTransation(), SimpleLTInitiator1::logStartTransation(), SimpleLTInitiator_ext::logStartTransation(), SimpleLTInitiator3_dmi::logStartTransation(), SimpleLTInitiator1_dmi::logStartTransation(), SimpleLTInitiator2_dmi::logStartTransation(), SimpleATInitiator2::logStartTransation(), SimpleATInitiator1::logStartTransation(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), SimpleLTTarget2::myGetDMIPtr(), SimpleLTTarget_ext::myGetDMIPtr(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), sc_gem5::payload2packet(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), tlm::tlm_to_hostendian_generic(), tlm::tlm_to_hostendian_single(), tlm::tlm_to_hostendian_word(), ExplicitLTTarget::transport_dbg(), SimpleLTTarget1::transport_dbg(), SimpleLTTarget2::transport_dbg(), SimpleLTTarget_ext::transport_dbg(), ExplicitATTarget::transport_dbg(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug().
get_byte_enable_length()
unsigned int tlm::tlm_generic_payload::get_byte_enable_length () const inline
Definition at line 226 of file gp.hh.
Referenced by deep_copy_from(), and tlm::tlm_to_hostendian_generic().
get_byte_enable_ptr()
unsigned char* tlm::tlm_generic_payload::get_byte_enable_ptr () const inline
Definition at line 219 of file gp.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), tlm::tlm_from_hostendian_aligned(), tlm::tlm_from_hostendian_generic(), tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
get_command()
tlm_command tlm::tlm_generic_payload::get_command () const inline
Definition at line 180 of file gp.hh.
Referenced by SimpleLTTarget1::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), deep_copy_from(), SimpleLTInitiator3_dmi::getDMIData(), SimpleLTInitiator2_dmi::getDMIData(), SimpleLTInitiator2::logEndTransaction(), SimpleLTInitiator3::logEndTransaction(), SimpleLTInitiator1::logEndTransaction(), CoreDecouplingLTInitiator::logEndTransaction(), SimpleLTInitiator_ext::logEndTransaction(), SimpleLTInitiator3_dmi::logEndTransaction(), SimpleLTInitiator1_dmi::logEndTransaction(), SimpleLTInitiator2_dmi::logEndTransaction(), SimpleATInitiator2::logEndTransaction(), SimpleATInitiator1::logEndTransaction(), SimpleLTInitiator2::logStartTransation(), SimpleLTInitiator3::logStartTransation(), CoreDecouplingLTInitiator::logStartTransation(), SimpleLTInitiator1::logStartTransation(), SimpleLTInitiator_ext::logStartTransation(), SimpleLTInitiator3_dmi::logStartTransation(), SimpleLTInitiator2_dmi::logStartTransation(), SimpleLTInitiator1_dmi::logStartTransation(), SimpleATInitiator2::logStartTransation(), SimpleATInitiator1::logStartTransation(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), sc_gem5::payload2packet(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), SimpleLTInitiator3_dmi::run(), and SimpleLTInitiator2_dmi::run().
get_data_length()
unsigned int tlm::tlm_generic_payload::get_data_length () const inline
Definition at line 192 of file gp.hh.
Referenced by deep_copy_from(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::getBackdoor(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), sc_gem5::payload2packet(), tlm::tlm_from_hostendian_aligned(), tlm::tlm_from_hostendian_generic(), tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), tlm::tlm_to_hostendian_word(), ExplicitLTTarget::transport_dbg(), SimpleLTTarget1::transport_dbg(), SimpleLTTarget2::transport_dbg(), SimpleLTTarget_ext::transport_dbg(), ExplicitATTarget::transport_dbg(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg().
get_data_ptr()
unsigned char* tlm::tlm_generic_payload::get_data_ptr () const inline
Definition at line 188 of file gp.hh.
Referenced by SimpleLTTarget1::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), SimpleATTarget2::myNBTransport(), SimpleATTarget1::myNBTransport(), sc_gem5::payload2packet(), tlm::tlm_from_hostendian_aligned(), tlm::tlm_from_hostendian_generic(), tlm::tlm_from_hostendian_word(), tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), tlm::tlm_to_hostendian_word(), ExplicitLTTarget::transport_dbg(), SimpleLTTarget1::transport_dbg(), SimpleLTTarget2::transport_dbg(), SimpleLTTarget_ext::transport_dbg(), and ExplicitATTarget::transport_dbg().
get_extension() [1/3]
template<typename T > void tlm::tlm_generic_payload::get_extension (T *& ext) const inline
Definition at line 364 of file gp.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), tlm::establish_context(), adapt_gp2ext< BUSWIDTH >::forward_nb_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), adapt_gp2ext< BUSWIDTH >::get_dmi_pointer(), Gem5SystemC::Gem5Extension::getExtension(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), SimpleLTTarget_ext::myGetDMIPtr(), SimpleLTTarget_ext::myNBTransport(), tlm::tlm_from_hostendian(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg().
get_extension() [2/3]
template<typename T > T* tlm::tlm_generic_payload::get_extension () const inline
Definition at line 367 of file gp.hh.
References Ps2::Keyboard::ID.
get_extension() [3/3]
tlm_extension_base * tlm::tlm_generic_payload::get_extension (unsigned int index) const
Definition at line 323 of file gp.cc.
References MipsISA::index, m_extensions, and sc_assert.
get_gp_option()
tlm_gp_option tlm::tlm_generic_payload::get_gp_option () const inline
Definition at line 250 of file gp.hh.
Referenced by deep_copy_from().
get_ref_count()
int tlm::tlm_generic_payload::get_ref_count () const inline
Definition at line 137 of file gp.hh.
Referenced by MultiSocketSimpleSwitchAT::b_transport().
get_response_status()
tlm_response_status tlm::tlm_generic_payload::get_response_status () const inline
Definition at line 199 of file gp.hh.
Referenced by deep_copy_from(), SimpleLTInitiator2::logEndTransaction(), SimpleLTInitiator3::logEndTransaction(), SimpleLTInitiator1::logEndTransaction(), CoreDecouplingLTInitiator::logEndTransaction(), SimpleLTInitiator3_dmi::logEndTransaction(), SimpleLTInitiator_ext::logEndTransaction(), SimpleLTInitiator2_dmi::logEndTransaction(), SimpleLTInitiator1_dmi::logEndTransaction(), SimpleATInitiator2::logEndTransaction(), SimpleATInitiator1::logEndTransaction(), and update_original_from().
get_response_string()
std::string tlm::tlm_generic_payload::get_response_string () const
Definition at line 275 of file gp.cc.
References m_response_status, tlm::TLM_ADDRESS_ERROR_RESPONSE, tlm::TLM_BURST_ERROR_RESPONSE, tlm::TLM_BYTE_ENABLE_ERROR_RESPONSE, tlm::TLM_COMMAND_ERROR_RESPONSE, tlm::TLM_GENERIC_ERROR_RESPONSE, tlm::TLM_INCOMPLETE_RESPONSE, and tlm::TLM_OK_RESPONSE.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::checkTransaction().
get_streaming_width()
unsigned int tlm::tlm_generic_payload::get_streaming_width () const inline
Definition at line 211 of file gp.hh.
Referenced by deep_copy_from(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), tlm::tlm_from_hostendian_generic(), and tlm::tlm_to_hostendian_generic().
has_mm()
bool tlm::tlm_generic_payload::has_mm () const inline
Definition at line 140 of file gp.hh.
References Stats::reset(), and X86ISA::x.
Referenced by MultiSocketSimpleSwitchAT::b_transport(), deep_copy_from(), and sc_gem5::packet2payload().
is_dmi_allowed()
bool tlm::tlm_generic_payload::is_dmi_allowed () const inline
Definition at line 244 of file gp.hh.
Referenced by deep_copy_from(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), and update_original_from().
is_read()
bool tlm::tlm_generic_payload::is_read () const inline
Definition at line 176 of file gp.hh.
References tlm::TLM_READ_COMMAND.
Referenced by tlm::tlm_from_hostendian_aligned(), tlm::tlm_from_hostendian_generic(), tlm::tlm_from_hostendian_word(), tlm::tlm_to_hostendian_word(), ExplicitLTTarget::transport_dbg(), SimpleLTTarget1::transport_dbg(), SimpleLTTarget2::transport_dbg(), SimpleLTTarget_ext::transport_dbg(), ExplicitATTarget::transport_dbg(), and update_original_from().
is_response_error()
bool tlm::tlm_generic_payload::is_response_error () const inline
Definition at line 197 of file gp.hh.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::checkTransaction().
is_response_ok()
bool tlm::tlm_generic_payload::is_response_ok () const inline
Definition at line 196 of file gp.hh.
is_write()
bool tlm::tlm_generic_payload::is_write () const inline
Definition at line 178 of file gp.hh.
References tlm::TLM_WRITE_COMMAND.
Referenced by tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), ExplicitLTTarget::transport_dbg(), and ExplicitATTarget::transport_dbg().
operator=()
tlm_generic_payload& tlm::tlm_generic_payload::operator= (const tlm_generic_payload & x) private
release()
void tlm::tlm_generic_payload::release () inline
Definition at line 130 of file gp.hh.
References sc_assert.
Referenced by MultiSocketSimpleSwitchAT::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::pec(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvRespRetry(), SimpleATInitiator1::SimplePool::release(), and SimpleATInitiator2::SimplePool::release().
release_extension() [1/3]
template<typename T > void tlm::tlm_generic_payload::release_extension (T * ext) inline
Definition at line 392 of file gp.hh.
release_extension() [2/3]
template<typename T > void tlm::tlm_generic_payload::release_extension () inline
Definition at line 401 of file gp.hh.
References Ps2::Keyboard::ID.
release_extension() [3/3]
void tlm::tlm_generic_payload::release_extension (unsigned int index) private
Definition at line 337 of file gp.cc.
References MipsISA::index, m_extensions, m_mm, and sc_assert.
reset()
void tlm::tlm_generic_payload::reset ()
Definition at line 117 of file gp.cc.
References m_extensions, m_gp_option, and tlm::TLM_MIN_PAYLOAD.
Referenced by mm::free(), Gem5SystemC::MemoryManager::free(), SimpleATInitiator2::SimplePool::free(), SimpleATInitiator1::SimplePool::free(), MultiSocketSimpleSwitchAT::free(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::free(), and mm::~mm().
resize_extensions()
void tlm::tlm_generic_payload::resize_extensions ()
Definition at line 349 of file gp.cc.
References m_extensions, and tlm::max_num_extensions().
set_address()
void tlm::tlm_generic_payload::set_address (const sc_dt::uint64 address) inline
Definition at line 185 of file gp.hh.
Referenced by SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), MultiSocketSimpleSwitchAT::fwPEQcb(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::getDMIPointer(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::initiatorBTransport(), SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), SimpleLTInitiator_ext::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleATInitiator2::initTransaction(), SimpleATInitiator1::initTransaction(), sc_gem5::packet2payload(), SimpleLTInitiator1_dmi::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), tlm::tlm_to_hostendian_generic(), tlm::tlm_to_hostendian_single(), tlm::tlm_to_hostendian_word(), SimpleBusLT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug(), and SimpleBusAT< NR_OF_INITIATORS, NR_OF_TARGETS >::transportDebug().
set_auto_extension() [1/2]
template<typename T > T* tlm::tlm_generic_payload::set_auto_extension (T * ext) inline
Definition at line 353 of file gp.hh.
References Ps2::Keyboard::ID.
Referenced by deep_copy_from(), and sc_gem5::packet2payload().
set_auto_extension() [2/2]
tlm_extension_base * tlm::tlm_generic_payload::set_auto_extension (unsigned int index, tlm_extension_base * ext)
Definition at line 310 of file gp.cc.
References ArmISA::ext, MipsISA::index, m_extensions, m_mm, and sc_assert.
set_byte_enable_length()
void tlm::tlm_generic_payload::set_byte_enable_length (const unsigned int byte_enable_length) inline
Definition at line 231 of file gp.hh.
Referenced by tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
set_byte_enable_ptr()
void tlm::tlm_generic_payload::set_byte_enable_ptr (unsigned char * byte_enable) inline
Definition at line 221 of file gp.hh.
Referenced by tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
set_command()
void tlm::tlm_generic_payload::set_command (const tlm_command command) inline
Definition at line 181 of file gp.hh.
Referenced by SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), SimpleLTInitiator_ext::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleATInitiator2::initTransaction(), SimpleATInitiator1::initTransaction(), and sc_gem5::packet2payload().
set_data_length()
void tlm::tlm_generic_payload::set_data_length (const unsigned int length) inline
Definition at line 193 of file gp.hh.
References length.
Referenced by SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleATInitiator2::initTransaction(), SimpleATInitiator1::initTransaction(), sc_gem5::packet2payload(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
set_data_ptr()
void tlm::tlm_generic_payload::set_data_ptr (unsigned char * data) inline
Definition at line 189 of file gp.hh.
References data.
Referenced by SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), SimpleLTInitiator_ext::end_of_simulation(), SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), SimpleLTInitiator_ext::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleATInitiator1::MyTransaction< DT >::MyTransaction(), SimpleATInitiator2::MyTransaction< DT >::MyTransaction(), sc_gem5::packet2payload(), tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
set_dmi_allowed()
void tlm::tlm_generic_payload::set_dmi_allowed (bool dmi_allowed) inline
Definition at line 239 of file gp.hh.
Referenced by SimpleLTTarget1::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), SimpleLTInitiator3::initTransaction(), SimpleLTInitiator2::initTransaction(), SimpleLTInitiator_ext::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleLTTarget2::myBTransport(), and SimpleLTTarget_ext::myNBTransport().
set_extension() [1/2]
template<typename T > T* tlm::tlm_generic_payload::set_extension (T * ext) inline
Definition at line 340 of file gp.hh.
References ArmISA::ext, Ps2::Keyboard::ID, and MipsISA::index.
Referenced by adapt_gp2ext< BUSWIDTH >::backward_nb_transport(), deep_copy_from(), tlm::establish_context(), adapt_gp2ext< BUSWIDTH >::forward_nb_transport(), adapt_gp2ext< BUSWIDTH >::get_dmi_pointer(), and SimpleLTInitiator_ext::run().
set_extension() [2/2]
tlm_extension_base * tlm::tlm_generic_payload::set_extension (unsigned int index, tlm_extension_base * ext)
Definition at line 301 of file gp.cc.
References ArmISA::ext, MipsISA::index, m_extensions, and sc_assert.
set_gp_option()
void tlm::tlm_generic_payload::set_gp_option (const tlm_gp_option gp_opt) inline
Definition at line 251 of file gp.hh.
set_mm()
void tlm::tlm_generic_payload::set_mm (tlm_mm_interface * mm) inline
Definition at line 139 of file gp.hh.
References SparcISA::mm.
Referenced by MultiSocketSimpleSwitchAT::b_transport().
set_read()
void tlm::tlm_generic_payload::set_read () inline
Definition at line 177 of file gp.hh.
References tlm::TLM_READ_COMMAND.
Referenced by SimpleLTInitiator2_dmi::end_of_simulation(), SimpleLTInitiator1_dmi::end_of_simulation(), and SimpleLTInitiator_ext::end_of_simulation().
set_response_status()
void tlm::tlm_generic_payload::set_response_status (const tlm_response_status response_status) inline
Definition at line 204 of file gp.hh.
Referenced by SimpleLTTarget1::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), ExplicitATTarget::beginResponse(), SimpleATTarget2::beginResponse(), SimpleATTarget1::beginResponse(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), ExplicitLTTarget::myBTransport(), SimpleLTTarget2::myBTransport(), ExplicitATTarget::myNBTransport(), SimpleLTTarget_ext::myNBTransport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::nb_transport_fw(), SimpleLTInitiator_ext::run(), SimpleLTInitiator1_dmi::run(), SimpleLTInitiator3_dmi::run(), SimpleLTInitiator2_dmi::run(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::sendBeginResp().
set_streaming_width()
void tlm::tlm_generic_payload::set_streaming_width (const unsigned int streaming_width) inline
Definition at line 213 of file gp.hh.
Referenced by SimpleLTInitiator2::initTransaction(), SimpleLTInitiator3::initTransaction(), CoreDecouplingLTInitiator::initTransaction(), SimpleLTInitiator1::initTransaction(), SimpleLTInitiator3_dmi::initTransaction(), SimpleLTInitiator1_dmi::initTransaction(), SimpleLTInitiator2_dmi::initTransaction(), SimpleATInitiator2::initTransaction(), SimpleATInitiator1::initTransaction(), sc_gem5::packet2payload(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
set_write()
void tlm::tlm_generic_payload::set_write () inline
Definition at line 179 of file gp.hh.
References tlm::TLM_WRITE_COMMAND.
Referenced by SimpleLTInitiator_ext::run(), and SimpleLTInitiator1_dmi::run().
update_extensions_from()
void tlm::tlm_generic_payload::update_extensions_from (const tlm_generic_payload & other)
Definition at line 232 of file gp.cc.
References ArmISA::i, m_extensions, and sc_assert.
Referenced by update_original_from().
update_original_from()
void tlm::tlm_generic_payload::update_original_from (const tlm_generic_payload & other, bool use_byte_enable_on_read = true)
Definition at line 180 of file gp.cc.
References get_response_status(), ArmISA::i, is_dmi_allowed(), is_read(), m_byte_enable, m_byte_enable_length, m_data, m_dmi, m_length, m_response_status, ArmISA::u, and update_extensions_from().
Member Data Documentation
m_address
sc_dt::uint64 tlm::tlm_generic_payload::m_address private
Definition at line 289 of file gp.hh.
Referenced by deep_copy_from().
m_byte_enable
unsigned char* tlm::tlm_generic_payload::m_byte_enable private
Definition at line 295 of file gp.hh.
Referenced by deep_copy_from(), and update_original_from().
m_byte_enable_length
unsigned int tlm::tlm_generic_payload::m_byte_enable_length private
Definition at line 296 of file gp.hh.
Referenced by deep_copy_from(), and update_original_from().
m_command
tlm_command tlm::tlm_generic_payload::m_command private
Definition at line 290 of file gp.hh.
Referenced by deep_copy_from().
m_data
unsigned char* tlm::tlm_generic_payload::m_data private
Definition at line 291 of file gp.hh.
Referenced by deep_copy_from(), and update_original_from().
m_dmi
bool tlm::tlm_generic_payload::m_dmi private
Definition at line 294 of file gp.hh.
Referenced by deep_copy_from(), and update_original_from().
m_extensions
tlm_array<tlm_extension_base *> tlm::tlm_generic_payload::m_extensions private
Definition at line 421 of file gp.hh.
Referenced by clear_extension(), deep_copy_from(), free_all_extensions(), get_extension(), release_extension(), reset(), resize_extensions(), set_auto_extension(), set_extension(), update_extensions_from(), and ~tlm_generic_payload().
m_gp_option
tlm_gp_option tlm::tlm_generic_payload::m_gp_option private
Definition at line 298 of file gp.hh.
Referenced by deep_copy_from(), and reset().
m_length
unsigned int tlm::tlm_generic_payload::m_length private
Definition at line 292 of file gp.hh.
Referenced by deep_copy_from(), and update_original_from().
m_mm
tlm_mm_interface* tlm::tlm_generic_payload::m_mm private
Definition at line 422 of file gp.hh.
Referenced by release_extension(), and set_auto_extension().
m_ref_count
unsigned int tlm::tlm_generic_payload::m_ref_count private
Definition at line 423 of file gp.hh.
m_response_status
tlm_response_status tlm::tlm_generic_payload::m_response_status private
Definition at line 293 of file gp.hh.
Referenced by deep_copy_from(), get_response_string(), and update_original_from().
m_streaming_width
unsigned int tlm::tlm_generic_payload::m_streaming_width private
Definition at line 297 of file gp.hh.
Referenced by deep_copy_from().
The documentation for this class was generated from the following files:
systemc/ext/tlm_core/2/generic_payload/gp.hh
systemc/tlm_core/2/generic_payload/gp.cc