gem5: ListOperand Class Reference
ListOperand Class Reference
#include <operand.hh>
Public Member Functions
int getSrcOperand (int idx)
void init (unsigned opOffset, const BrigObject *obj)
std::string disassemble ()
template<typename OperandType >
OperandType get (Wavefront *w, int lane, int arg_idx)
template<typename OperandType >
void set (Wavefront *w, int lane, OperandType val)
Public Member Functions inherited from BaseOperand
BaseOperand ()
bool isVectorRegister ()
bool isScalarRegister ()
bool isCondRegister ()
unsigned int regIndex ()
uint32_t opSize ()
virtual ~BaseOperand ()
Public Attributes
int elementCount
std::vector< StorageElement * > callArgs
Public Attributes inherited from BaseOperand
Enums::RegisterType registerType
uint32_t regOperandSize
Detailed Description
Definition at line 750 of file operand.hh.
Member Function Documentation
disassemble()
std::string ListOperand::disassemble ()
Definition at line 104 of file operand.cc.
References csprintf().
get()
template<typename OperandType > OperandType ListOperand::get (Wavefront * w, int lane, int arg_idx) inline
Definition at line 771 of file operand.hh.
References Wavefront::readCallArgMem().
Referenced by HsailISA::Call::calcAddr(), HsailISA::Call::execPseudoInst(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), HsailISA::Call::MagicMaskLower(), HsailISA::Call::MagicMaskUpper(), HsailISA::Call::MagicMostSigBroadcast(), HsailISA::Call::MagicPanic(), HsailISA::Call::MagicPrefixSum(), HsailISA::Call::MagicPrintLane(), HsailISA::Call::MagicPrintLane64(), HsailISA::Call::MagicPrintWF32(), HsailISA::Call::MagicPrintWF32ID(), HsailISA::Call::MagicPrintWF64(), HsailISA::Call::MagicPrintWFFloat(), HsailISA::Call::MagicPrintWFID64(), HsailISA::Call::MagicReduction(), and HsailISA::Call::MagicXactCasLd().
getSrcOperand()
int ListOperand::getSrcOperand (int idx) inline
Definition at line 757 of file operand.hh.
References DPRINTF, and Stats::init.
init()
void ListOperand::init (unsigned opOffset, const BrigObject * obj)
Definition at line 63 of file operand.cc.
References Brig::BRIG_KIND_OPERAND_CODE_LIST, Brig::BRIG_SEGMENT_ARG, Brig::BrigData::byteCount, BrigObject::currentCode, DPRINTF, Brig::BrigOperandCodeList::elements, fatal, BrigObject::getBrigBaseData(), BrigObject::getData(), BrigObject::getOperand(), ArmISA::i, Brig::BrigBase::kind, MipsISA::p, and HsailCode::storageMap.
Referenced by HsailISA::Call::Call().
set()
template<typename OperandType > void ListOperand::set (Wavefront * w, int lane, OperandType val) inline
Definition at line 778 of file operand.hh.
References Wavefront::computeUnit, ComputeUnit::cu_id, DPRINTF, Wavefront::simdId, X86ISA::val, Wavefront::wfSlotId, and Wavefront::writeCallArgMem().
Referenced by HsailISA::Call::MagicMaskLower(), HsailISA::Call::MagicMaskUpper(), HsailISA::Call::MagicMostSigBroadcast(), HsailISA::Call::MagicMostSigThread(), HsailISA::Call::MagicPrefixSum(), and HsailISA::Call::MagicReduction().
Member Data Documentation
callArgs
std::vector<StorageElement*> ListOperand::callArgs
Definition at line 754 of file operand.hh.
elementCount
int ListOperand::elementCount
Definition at line 753 of file operand.hh.
The documentation for this class was generated from the following files:
arch/hsail/operand.hh
arch/hsail/operand.cc