gem5: MemDepUnit< MemDepPred, Impl > Class Template Reference
MemDepUnit< MemDepPred, Impl > Class Template Reference
Memory dependency unit class.
#include <mem_dep_unit.hh>
Classes
class MemDepEntry
Memory dependence entries that track memory operations, marking when the instruction is ready to execute and what instructions depend upon it.
Public Types
typedef Impl::DynInstPtr DynInstPtr
typedef Impl::DynInstConstPtr DynInstConstPtr
Public Member Functions
MemDepUnit ()
Empty constructor.
MemDepUnit (DerivO3CPUParams *params)
Constructs a MemDepUnit with given parameters.
~MemDepUnit ()
Frees up any memory allocated.
std::string name () const
Returns the name of the memory dependence unit.
void init (DerivO3CPUParams *params, ThreadID tid)
Initializes the unit with parameters and a thread id.
void regStats ()
Registers statistics.
bool isDrained () const
Determine if we are drained.
void drainSanityCheck () const
Perform sanity checks after a drain.
void takeOverFrom ()
Takes over from another CPU's thread.
void setIQ (InstructionQueue< Impl > *iq_ptr)
Sets the pointer to the IQ.
void insert (const DynInstPtr &inst)
Inserts a memory instruction.
void insertNonSpec (const DynInstPtr &inst)
Inserts a non-speculative memory instruction.
void insertBarrier (const DynInstPtr &barr_inst)
Inserts a barrier instruction.
void regsReady (const DynInstPtr &inst)
Indicate that an instruction has its registers ready.
void nonSpecInstReady (const DynInstPtr &inst)
Indicate that a non-speculative instruction is ready.
void reschedule (const DynInstPtr &inst)
Reschedules an instruction to be re-executed.
void replay ()
Replays all instructions that have been rescheduled by moving them to the ready list.
void completed (const DynInstPtr &inst)
Completes a memory instruction.
void completeBarrier (const DynInstPtr &inst)
Completes a barrier instruction.
void wakeDependents (const DynInstPtr &inst)
Wakes any dependents of a memory instruction.
void squash (const InstSeqNum &squashed_num, ThreadID tid)
Squashes all instructions up until a given sequence number for a specific thread.
void violation (const DynInstPtr &store_inst, const DynInstPtr &violating_load)
Indicates an ordering violation between a store and a younger load.
void issue (const DynInstPtr &inst)
Issues the given instruction.
void dumpLists ()
Debugging function to dump the lists of instructions.
Protected Attributes
std::string _name
Private Types
typedef std::list< DynInstPtr >::iterator ListIt
typedef std::shared_ptr< MemDepEntry > MemDepEntryPtr
typedef std::unordered_map< InstSeqNum, MemDepEntryPtr, SNHash > MemDepHash
typedef MemDepHash::iterator MemDepHashIt
Private Member Functions
MemDepEntryPtr & findInHash (const DynInstConstPtr &inst)
Finds the memory dependence entry in the hash map.
void moveToReady (MemDepEntryPtr &ready_inst_entry)
Moves an entry to the ready list.
Private Attributes
MemDepHash memDepHash
A hash map of all memory dependence entries.
std::list< DynInstPtr > instList [Impl::MaxThreads]
A list of all instructions in the memory dependence unit.
std::list< DynInstPtr > instsToReplay
A list of all instructions that are going to be replayed.
MemDepPred depPred
The memory dependence predictor.
bool loadBarrier
Is there an outstanding load barrier that loads must wait on.
InstSeqNum loadBarrierSN
The sequence number of the load barrier.
bool storeBarrier
Is there an outstanding store barrier that loads must wait on.
InstSeqNum storeBarrierSN
The sequence number of the store barrier.
InstructionQueue< Impl > * iqPtr
Pointer to the IQ.
int id
The thread id of this memory dependence unit.
Stats::Scalar insertedLoads
Stat for number of inserted loads.
Stats::Scalar insertedStores
Stat for number of inserted stores.
Stats::Scalar conflictingLoads
Stat for number of conflicting loads that had to wait for a store.
Stats::Scalar conflictingStores
Stat for number of conflicting stores that had to wait for a store.
Detailed Description
template<class MemDepPred, class Impl>
class MemDepUnit< MemDepPred, Impl >
Memory dependency unit class.
This holds the memory dependence predictor. As memory operations are issued to the IQ, they are also issued to this unit, which then looks up the prediction as to what they are dependent upon. This unit must be checked prior to a memory operation being able to issue. Although this is templated, it's somewhat hard to make a generic memory dependence unit. This one is mostly for store sets; it will be quite limited in what other memory dependence predictions it can also utilize. Thus this class should be most likely be rewritten for other dependence prediction schemes.
Definition at line 81 of file mem_dep_unit.hh.
Member Typedef Documentation
DynInstConstPtr
template<class MemDepPred , class Impl > typedef Impl::DynInstConstPtr MemDepUnit< MemDepPred, Impl >::DynInstConstPtr
Definition at line 88 of file mem_dep_unit.hh.
DynInstPtr
template<class MemDepPred , class Impl > typedef Impl::DynInstPtr MemDepUnit< MemDepPred, Impl >::DynInstPtr
Definition at line 87 of file mem_dep_unit.hh.
ListIt
template<class MemDepPred , class Impl > typedef std::list<DynInstPtr>::iterator MemDepUnit< MemDepPred, Impl >::ListIt private
Definition at line 168 of file mem_dep_unit.hh.
MemDepEntryPtr
template<class MemDepPred , class Impl > typedef std::shared_ptr<MemDepEntry> MemDepUnit< MemDepPred, Impl >::MemDepEntryPtr private
Definition at line 170 of file mem_dep_unit.hh.
MemDepHash
template<class MemDepPred , class Impl > typedef std::unordered_map<InstSeqNum, MemDepEntryPtr, SNHash> MemDepUnit< MemDepPred, Impl >::MemDepHash private
Definition at line 242 of file mem_dep_unit.hh.
MemDepHashIt
template<class MemDepPred , class Impl > typedef MemDepHash::iterator MemDepUnit< MemDepPred, Impl >::MemDepHashIt private
Definition at line 244 of file mem_dep_unit.hh.
Constructor & Destructor Documentation
MemDepUnit() [1/2]
template<class MemDepPred , class Impl > MemDepUnit< MemDepPred, Impl >::MemDepUnit ()
Empty constructor.
Must call init() prior to using in this case.
Definition at line 54 of file mem_dep_unit_impl.hh.
MemDepUnit() [2/2]
template<class MemDepPred , class Impl > MemDepUnit< MemDepPred, Impl >::MemDepUnit (DerivO3CPUParams * params)
Constructs a MemDepUnit with given parameters.
Definition at line 61 of file mem_dep_unit_impl.hh.
References DPRINTF.
~MemDepUnit()
template<class MemDepPred , class Impl > MemDepUnit< MemDepPred, Impl >::~MemDepUnit ()
Frees up any memory allocated.
Definition at line 72 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::instList, and MemDepUnit< MemDepPred, Impl >::memDepHash.
Member Function Documentation
completeBarrier()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::completeBarrier (const DynInstPtr & inst)
Completes a barrier instruction.
Definition at line 431 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::completed(), DPRINTF, MemDepUnit< MemDepPred, Impl >::loadBarrier, MemDepUnit< MemDepPred, Impl >::loadBarrierSN, MemDepUnit< MemDepPred, Impl >::storeBarrier, MemDepUnit< MemDepPred, Impl >::storeBarrierSN, and MemDepUnit< MemDepPred, Impl >::wakeDependents().
Referenced by InstructionQueue< Impl >::wakeDependents().
completed()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::completed (const DynInstPtr & inst)
Completes a memory instruction.
Definition at line 407 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::instList, and MemDepUnit< MemDepPred, Impl >::memDepHash.
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), and InstructionQueue< Impl >::completeMemInst().
drainSanityCheck()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::drainSanityCheck () const
Perform sanity checks after a drain.
Definition at line 145 of file mem_dep_unit_impl.hh.
References ArmISA::i, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::instsToReplay, and MemDepUnit< MemDepPred, Impl >::memDepHash.
dumpLists()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::dumpLists ()
Debugging function to dump the lists of instructions.
Definition at line 586 of file mem_dep_unit_impl.hh.
References cprintf(), MemDepUnit< MemDepPred, Impl >::instList, and MemDepUnit< MemDepPred, Impl >::memDepHash.
findInHash()
template<class MemDepPred , class Impl > MemDepUnit< MemDepPred, Impl >::MemDepEntryPtr & MemDepUnit< MemDepPred, Impl >::findInHash (const DynInstConstPtr & inst) inline private
Finds the memory dependence entry in the hash map.
Definition at line 562 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::memDepHash.
Referenced by MemDepUnit< MemDepPred, Impl >::nonSpecInstReady(), MemDepUnit< MemDepPred, Impl >::regsReady(), MemDepUnit< MemDepPred, Impl >::replay(), and MemDepUnit< MemDepPred, Impl >::wakeDependents().
init()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::init (DerivO3CPUParams * params, ThreadID tid)
Initializes the unit with parameters and a thread id.
Definition at line 98 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::_name, csprintf(), MemDepUnit< MemDepPred, Impl >::depPred, and DPRINTF.
Referenced by InstructionQueue< Impl >::InstructionQueue().
insert()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::insert (const DynInstPtr & inst)
Inserts a memory instruction.
Definition at line 174 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::conflictingLoads, MemDepUnit< MemDepPred, Impl >::conflictingStores, MemDepUnit< MemDepPred, Impl >::depPred, DPRINTF, MemDepUnit< MemDepPred, Impl >::insertedLoads, MemDepUnit< MemDepPred, Impl >::insertedStores, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::loadBarrier, MemDepUnit< MemDepPred, Impl >::loadBarrierSN, MemDepUnit< MemDepPred, Impl >::memDepHash, MemDepUnit< MemDepPred, Impl >::moveToReady(), panic, MemDepUnit< MemDepPred, Impl >::storeBarrier, and MemDepUnit< MemDepPred, Impl >::storeBarrierSN.
Referenced by InstructionQueue< Impl >::insert().
insertBarrier()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::insertBarrier (const DynInstPtr & barr_inst)
Inserts a barrier instruction.
Definition at line 307 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::loadBarrier, MemDepUnit< MemDepPred, Impl >::loadBarrierSN, MemDepUnit< MemDepPred, Impl >::memDepHash, MemDepUnit< MemDepPred, Impl >::storeBarrier, and MemDepUnit< MemDepPred, Impl >::storeBarrierSN.
Referenced by InstructionQueue< Impl >::insertBarrier().
insertNonSpec()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::insertNonSpec (const DynInstPtr & inst)
Inserts a non-speculative memory instruction.
Definition at line 271 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::depPred, DPRINTF, MemDepUnit< MemDepPred, Impl >::insertedLoads, MemDepUnit< MemDepPred, Impl >::insertedStores, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::memDepHash, and panic.
Referenced by InstructionQueue< Impl >::insertNonSpec().
isDrained()
template<class MemDepPred , class Impl > bool MemDepUnit< MemDepPred, Impl >::isDrained () const
Determine if we are drained.
Definition at line 132 of file mem_dep_unit_impl.hh.
References ArmISA::i, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::instsToReplay, and MemDepUnit< MemDepPred, Impl >::memDepHash.
issue()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::issue (const DynInstPtr & inst)
Issues the given instruction.
Definition at line 552 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::depPred, and DPRINTF.
Referenced by InstructionQueue< Impl >::scheduleReadyInsts().
moveToReady()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::moveToReady (MemDepEntryPtr & ready_inst_entry) inline private
Moves an entry to the ready list.
Definition at line 573 of file mem_dep_unit_impl.hh.
References DPRINTF, and MemDepUnit< MemDepPred, Impl >::iqPtr.
Referenced by MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::nonSpecInstReady(), MemDepUnit< MemDepPred, Impl >::regsReady(), MemDepUnit< MemDepPred, Impl >::replay(), and MemDepUnit< MemDepPred, Impl >::wakeDependents().
name()
template<class MemDepPred , class Impl > std::string MemDepUnit< MemDepPred, Impl >::name () const inline
Returns the name of the memory dependence unit.
Definition at line 100 of file mem_dep_unit.hh.
References Stats::init, and takeOverFrom().
Referenced by MemDepUnit< MemDepPred, Impl >::regStats().
nonSpecInstReady()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::nonSpecInstReady (const DynInstPtr & inst)
Indicate that a non-speculative instruction is ready.
Definition at line 366 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::findInHash(), and MemDepUnit< MemDepPred, Impl >::moveToReady().
Referenced by InstructionQueue< Impl >::scheduleNonSpec().
regsReady()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::regsReady (const DynInstPtr & inst)
Indicate that an instruction has its registers ready.
Definition at line 343 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::findInHash(), and MemDepUnit< MemDepPred, Impl >::moveToReady().
Referenced by InstructionQueue< Impl >::addIfReady().
regStats()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::regStats ()
Registers statistics.
Definition at line 111 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::conflictingLoads, MemDepUnit< MemDepPred, Impl >::conflictingStores, Stats::DataWrap< Derived, InfoProxyType >::desc(), MemDepUnit< MemDepPred, Impl >::insertedLoads, MemDepUnit< MemDepPred, Impl >::insertedStores, MemDepUnit< MemDepPred, Impl >::name(), and Stats::DataWrap< Derived, InfoProxyType >::name().
Referenced by InstructionQueue< Impl >::regStats().
replay()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::replay ()
Replays all instructions that have been rescheduled by moving them to the ready list.
Definition at line 386 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::findInHash(), MemDepUnit< MemDepPred, Impl >::instsToReplay, and MemDepUnit< MemDepPred, Impl >::moveToReady().
Referenced by InstructionQueue< Impl >::replayMemInst().
reschedule()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::reschedule (const DynInstPtr & inst)
Reschedules an instruction to be re-executed.
Definition at line 379 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::instsToReplay.
Referenced by InstructionQueue< Impl >::rescheduleMemInst().
setIQ()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::setIQ (InstructionQueue< Impl > * iq_ptr)
Sets the pointer to the IQ.
Definition at line 167 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::iqPtr.
Referenced by InstructionQueue< Impl >::InstructionQueue().
squash()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::squash (const InstSeqNum & squashed_num, ThreadID tid)
Squashes all instructions up until a given sequence number for a specific thread.
Definition at line 486 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::depPred, DPRINTF, MemDepUnit< MemDepPred, Impl >::instList, MemDepUnit< MemDepPred, Impl >::instsToReplay, MemDepUnit< MemDepPred, Impl >::loadBarrier, MemDepUnit< MemDepPred, Impl >::loadBarrierSN, MemDepUnit< MemDepPred, Impl >::memDepHash, MemDepUnit< MemDepPred, Impl >::storeBarrier, and MemDepUnit< MemDepPred, Impl >::storeBarrierSN.
Referenced by InstructionQueue< Impl >::squash().
takeOverFrom()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::takeOverFrom ()
Takes over from another CPU's thread.
Definition at line 157 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::depPred, MemDepUnit< MemDepPred, Impl >::loadBarrier, MemDepUnit< MemDepPred, Impl >::loadBarrierSN, MemDepUnit< MemDepPred, Impl >::storeBarrier, and MemDepUnit< MemDepPred, Impl >::storeBarrierSN.
violation()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::violation (const DynInstPtr & store_inst, const DynInstPtr & violating_load)
Indicates an ordering violation between a store and a younger load.
Definition at line 540 of file mem_dep_unit_impl.hh.
References MemDepUnit< MemDepPred, Impl >::depPred, and DPRINTF.
Referenced by InstructionQueue< Impl >::violation().
wakeDependents()
template<class MemDepPred , class Impl > void MemDepUnit< MemDepPred, Impl >::wakeDependents (const DynInstPtr & inst)
Wakes any dependents of a memory instruction.
Definition at line 452 of file mem_dep_unit_impl.hh.
References DPRINTF, MemDepUnit< MemDepPred, Impl >::findInHash(), ArmISA::i, and MemDepUnit< MemDepPred, Impl >::moveToReady().
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), and InstructionQueue< Impl >::wakeDependents().
Member Data Documentation
_name
template<class MemDepPred , class Impl > std::string MemDepUnit< MemDepPred, Impl >::_name protected
Definition at line 84 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::init().
conflictingLoads
template<class MemDepPred , class Impl > Stats::Scalar MemDepUnit< MemDepPred, Impl >::conflictingLoads private
Stat for number of conflicting loads that had to wait for a store.
Definition at line 282 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::insert(), and MemDepUnit< MemDepPred, Impl >::regStats().
conflictingStores
template<class MemDepPred , class Impl > Stats::Scalar MemDepUnit< MemDepPred, Impl >::conflictingStores private
Stat for number of conflicting stores that had to wait for a store.
Definition at line 284 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::insert(), and MemDepUnit< MemDepPred, Impl >::regStats().
depPred
template<class MemDepPred , class Impl > MemDepPred MemDepUnit< MemDepPred, Impl >::depPred private
The memory dependence predictor.
It is accessed upon new instructions being added to the IQ, and responds by telling this unit what instruction the newly added instruction is dependent upon.
Definition at line 260 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::init(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertNonSpec(), MemDepUnit< MemDepPred, Impl >::issue(), MemDepUnit< MemDepPred, Impl >::squash(), MemDepUnit< MemDepPred, Impl >::takeOverFrom(), and MemDepUnit< MemDepPred, Impl >::violation().
id
template<class MemDepPred , class Impl > int MemDepUnit< MemDepPred, Impl >::id private
The thread id of this memory dependence unit.
Definition at line 275 of file mem_dep_unit.hh.
insertedLoads
template<class MemDepPred , class Impl > Stats::Scalar MemDepUnit< MemDepPred, Impl >::insertedLoads private
Stat for number of inserted loads.
Definition at line 278 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertNonSpec(), and MemDepUnit< MemDepPred, Impl >::regStats().
insertedStores
template<class MemDepPred , class Impl > Stats::Scalar MemDepUnit< MemDepPred, Impl >::insertedStores private
Stat for number of inserted stores.
Definition at line 280 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertNonSpec(), and MemDepUnit< MemDepPred, Impl >::regStats().
instList
template<class MemDepPred , class Impl > std::list<DynInstPtr> MemDepUnit< MemDepPred, Impl >::instList[Impl::MaxThreads] private
A list of all instructions in the memory dependence unit.
Definition at line 250 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completed(), MemDepUnit< MemDepPred, Impl >::drainSanityCheck(), MemDepUnit< MemDepPred, Impl >::dumpLists(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::insertNonSpec(), MemDepUnit< MemDepPred, Impl >::isDrained(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::~MemDepUnit().
instsToReplay
template<class MemDepPred , class Impl > std::list<DynInstPtr> MemDepUnit< MemDepPred, Impl >::instsToReplay private
A list of all instructions that are going to be replayed.
Definition at line 253 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::drainSanityCheck(), MemDepUnit< MemDepPred, Impl >::isDrained(), MemDepUnit< MemDepPred, Impl >::replay(), MemDepUnit< MemDepPred, Impl >::reschedule(), and MemDepUnit< MemDepPred, Impl >::squash().
iqPtr
template<class MemDepPred , class Impl > InstructionQueue<Impl>* MemDepUnit< MemDepPred, Impl >::iqPtr private
Pointer to the IQ.
Definition at line 272 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::moveToReady(), and MemDepUnit< MemDepPred, Impl >::setIQ().
loadBarrier
template<class MemDepPred , class Impl > bool MemDepUnit< MemDepPred, Impl >::loadBarrier private
Is there an outstanding load barrier that loads must wait on.
Definition at line 263 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::takeOverFrom().
loadBarrierSN
template<class MemDepPred , class Impl > InstSeqNum MemDepUnit< MemDepPred, Impl >::loadBarrierSN private
The sequence number of the load barrier.
Definition at line 265 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::takeOverFrom().
memDepHash
template<class MemDepPred , class Impl > MemDepHash MemDepUnit< MemDepPred, Impl >::memDepHash private
A hash map of all memory dependence entries.
Definition at line 247 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completed(), MemDepUnit< MemDepPred, Impl >::drainSanityCheck(), MemDepUnit< MemDepPred, Impl >::dumpLists(), MemDepUnit< MemDepPred, Impl >::findInHash(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::insertNonSpec(), MemDepUnit< MemDepPred, Impl >::isDrained(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::~MemDepUnit().
storeBarrier
template<class MemDepPred , class Impl > bool MemDepUnit< MemDepPred, Impl >::storeBarrier private
Is there an outstanding store barrier that loads must wait on.
Definition at line 267 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::takeOverFrom().
storeBarrierSN
template<class MemDepPred , class Impl > InstSeqNum MemDepUnit< MemDepPred, Impl >::storeBarrierSN private
The sequence number of the store barrier.
Definition at line 269 of file mem_dep_unit.hh.
Referenced by MemDepUnit< MemDepPred, Impl >::completeBarrier(), MemDepUnit< MemDepPred, Impl >::insert(), MemDepUnit< MemDepPred, Impl >::insertBarrier(), MemDepUnit< MemDepPred, Impl >::squash(), and MemDepUnit< MemDepPred, Impl >::takeOverFrom().
The documentation for this class was generated from the following files:
cpu/o3/mem_dep_unit.hh
cpu/o3/mem_dep_unit_impl.hh