gem5: Stats::Group Class Reference
Stats::Group Class Reference
Statistics container.
#include <group.hh>
Public Member Functions
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Member Functions
void mergeStatGroup (Group *block)
Merge the contents (stats & children) of a block to this block.
Private Attributes
Group *const mergedParent
Parent pointer if merged into parent.
std::map< std::string, Group * > statGroups
std::vector< Group * > mergedStatGroups
std::vector< Info * > stats
Detailed Description
Statistics container.
A stat group is a hierarchical structure that contain statistics and other groups. Groups are used by the stat system to reflect gem5's SimObject hierarchy and to expose internal hierarchy within an object. They can also be used to conveniently group stats into their own class/struct and then be merged into the parent group (typically a SimObject).
Definition at line 85 of file group.hh.
Constructor & Destructor Documentation
Group() [1/3]
Stats::Group::Group () delete
Group() [2/3]
Stats::Group::Group (const Group &) delete
Group() [3/3]
Stats::Group::Group (Group * parent, const char * name = nullptr)
Construct a new statistics group.
The constructor takes two parameters, a parent and a name. The parent group should typically be specified. However, there are special cases where the parent group may be null. One such special case is SimObjects where the Python code performs late binding of the group parent.
If the name parameter is NULL, the group gets merged into the parent group instead of creating a sub-group. Stats belonging to a merged group behave as if they have been added directly to the parent group.
Parameters
parent Parent group to associate this object to.
name Name of this group, can be NULL to merge this group with the parent group.
Definition at line 51 of file group.cc.
References addStatGroup(), and mergeStatGroup().
~Group()
Stats::Group::~Group () virtual
Definition at line 61 of file group.cc.
Member Function Documentation
addStat()
void Stats::Group::addStat (Stats::Info * info)
Register a stat with this group.
This method is normally called automatically when a stat is instantiated.
Definition at line 107 of file group.cc.
References addStat(), mergedParent, and stats.
Referenced by addStat(), and Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::DataWrap().
addStatGroup()
void Stats::Group::addStatGroup (const char * name, Group * block)
Add a stat block as a child of this block.
This method may only be called from a Group constructor or from regStats. It's typically only called explicitly from Python when setting up the SimObject hierarchy.
Definition at line 115 of file group.cc.
References name(), and statGroups.
Referenced by Group(), and pybind_init_stats().
getStatGroups()
const std::map< std::string, Group * > & Stats::Group::getStatGroups () const
Get all child groups associated with this object.
Definition at line 129 of file group.cc.
References statGroups.
Referenced by pybind_init_stats().
getStats()
const std::vector< Info * > & Stats::Group::getStats () const
Get all stats associated with this object.
Definition at line 135 of file group.cc.
References stats.
Referenced by pybind_init_stats().
mergeStatGroup()
void Stats::Group::mergeStatGroup (Group * block) private
Merge the contents (stats & children) of a block to this block.
This is called on a parent group by the child when it is being merged into the parent.
Definition at line 123 of file group.cc.
References mergedStatGroups.
Referenced by Group().
operator=()
Group& Stats::Group::operator= (const Group &) delete
Referenced by sc_core::sc_prim_channel::end_of_simulation().
preDumpStats()
void Stats::Group::preDumpStats () virtual
Callback before stats are dumped.
This can be overridden by objects that need to perform calculations in addition to the capabiltiies implemented in the stat framework.
Reimplemented in ClockedObject::ClockedObjectStats, DRAMCtrl::RankStats, and BaseTags::BaseTagStats.
Definition at line 97 of file group.cc.
References MipsISA::g, mergedStatGroups, and statGroups.
Referenced by BaseTags::BaseTagStats::preDumpStats(), DRAMCtrl::RankStats::preDumpStats(), ClockedObject::ClockedObjectStats::preDumpStats(), and pybind_init_stats().
regStats()
void Stats::Group::regStats () virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented in TraceCPU, DRAMCtrl::DRAMStats, UFSHostDevice, BaseCache::CacheStats, ArmISA::TableWalker, CoherentXBar, System, BaseXBar, ArmISA::TLB, ComputeUnit, BasePrefetcher, Wavefront, SimpleCache, BaseCPU, ClockedObject::ClockedObjectStats, Sinic::Device, IdeDisk, DRAMCtrl::RankStats, StatisticalCorrector, LoopPredictor, QoS::MemSinkCtrl, X86ISA::GpuTLB, SnoopFilter, QueuedPrefetcher, CopyEngine, FullO3CPU< Impl >, FullO3CPU< O3CPUImpl >, ElasticTrace, PowerISA::TLB, TickedObject, SMMUv3, AbstractMemory::MemStats, FALRU, BaseCacheCompressor, TAGE_SC_L, X86ISA::TLB, FlashDevice, TLBCoalescer, BaseSimpleCPU, MinorCPU, PowerModel, MessageBuffer, QoS::MemCtrl::MemCtrlStats, CacheMemory, Process, MipsISA::TLB, RiscvISA::TLB, BaseTags::BaseTagStats, Prefetcher, GPUCoalescer, GarnetNetwork, BaseDictionaryCompressor, Router, HDLcd, AbstractController, ThermalDomain, AlphaISA::TLB, BaseO3CPU, MathExprPowerModel, PowerModelState, BaseKvmCPU, MultiCompressor, BPredUnit, MemTest, RubySystem, LTAGE, Switch, Sequencer, QoS::Policy, TAGEBase, EtherDevice, MemFootprintProbe, SimpleNetwork, StackDistProbe, and sc_gem5::Kernel.
Definition at line 66 of file group.cc.
References DPRINTF, DTRACE, MipsISA::g, M5_VAR_USED, mergedStatGroups, PowerISA::so, and statGroups.
Referenced by DRAMCtrl::Rank::forceSelfRefreshExit(), CxxConfigManager::instantiate(), pybind_init_stats(), StackDistProbe::regStats(), SimpleNetwork::regStats(), MemFootprintProbe::regStats(), EtherDevice::regStats(), Sequencer::regStats(), Switch::regStats(), RubySystem::regStats(), MemTest::regStats(), BPredUnit::regStats(), AlphaISA::TLB::regStats(), ThermalDomain::regStats(), HDLcd::regStats(), AbstractController::regStats(), Router::regStats(), GarnetNetwork::regStats(), GPUCoalescer::regStats(), Prefetcher::regStats(), RiscvISA::TLB::regStats(), BaseTags::BaseTagStats::regStats(), MipsISA::TLB::regStats(), Process::regStats(), CacheMemory::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), TLBCoalescer::regStats(), FlashDevice::regStats(), X86ISA::TLB::regStats(), BaseCacheCompressor::regStats(), FALRU::regStats(), AbstractMemory::MemStats::regStats(), SMMUv3::regStats(), TickedObject::regStats(), PowerISA::TLB::regStats(), ElasticTrace::regStats(), CopyEngine::regStats(), SnoopFilter::regStats(), X86ISA::GpuTLB::regStats(), QoS::MemSinkCtrl::regStats(), DRAMCtrl::RankStats::regStats(), IdeDisk::regStats(), ClockedObject::ClockedObjectStats::regStats(), BaseCPU::regStats(), SimpleCache::regStats(), Wavefront::regStats(), BasePrefetcher::regStats(), ComputeUnit::regStats(), ArmISA::TLB::regStats(), BaseXBar::regStats(), System::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), UFSHostDevice::regStats(), and BaseCache::CacheCmdStats::regStatsFromParent().
resetStats()
void Stats::Group::resetStats () virtual
Callback to reset stats.
Reimplemented in DRAMCtrl::DRAMStats, Sinic::Device, DRAMCtrl::RankStats, BaseSimpleCPU, GPUCoalescer, Router, AbstractController, RubySystem, NetworkLink, Switch, and Sequencer.
Definition at line 84 of file group.cc.
References MipsISA::g, mergedStatGroups, ArmISA::s, statGroups, and stats.
Referenced by DRAMCtrl::Rank::forceSelfRefreshExit(), pybind_init_stats(), DRAMCtrl::RankStats::resetStats(), and Sinic::Device::resetStats().
Member Data Documentation
mergedParent
Group* const Stats::Group::mergedParent private
Parent pointer if merged into parent.
Definition at line 173 of file group.hh.
Referenced by addStat().
mergedStatGroups
std::vector<Group *> Stats::Group::mergedStatGroups private
Definition at line 176 of file group.hh.
Referenced by mergeStatGroup(), preDumpStats(), regStats(), and resetStats().
statGroups
std::map<std::string, Group *> Stats::Group::statGroups private
Definition at line 175 of file group.hh.
Referenced by addStatGroup(), getStatGroups(), preDumpStats(), regStats(), and resetStats().
stats
std::vector<Info *> Stats::Group::stats private
Definition at line 177 of file group.hh.
Referenced by AbstractMemory::access(), addStat(), getStats(), BaseTags::invalidate(), QoS::MemCtrl::recordTurnaroundStats(), CommMonitor::recvAtomic(), CommMonitor::recvTimingReq(), BaseTrafficGen::recvTimingResp(), CommMonitor::recvTimingResp(), resetStats(), CommMonitor::samplePeriodic(), and AlphaISA::ISA::setIpr().
The documentation for this class was generated from the following files:
base/stats/group.hh
base/stats/group.cc