gem5: SubBlock Class Reference
SubBlock Class Reference
#include <SubBlock.hh>
Public Member Functions
SubBlock ()
SubBlock (Addr addr, int size)
~SubBlock ()
Addr getAddress () const
void setAddress (Addr addr)
int getSize () const
void resize (int size)
uint8_t getByte (int offset) const
void setByte (int offset, uint8_t data)
uint8_t readByte () const
void writeByte (uint8_t data)
void mergeTo (DataBlock &data) const
void mergeFrom (const DataBlock &data)
void print (std::ostream &out) const
Private Member Functions
void internalMergeTo (DataBlock &data) const
void internalMergeFrom (const DataBlock &data)
Private Attributes
Addr m_address
std::vector< uint8_t > m_data
Detailed Description
Definition at line 38 of file SubBlock.hh.
Constructor & Destructor Documentation
SubBlock() [1/2]
SubBlock::SubBlock () inline
Definition at line 41 of file SubBlock.hh.
References addr.
SubBlock() [2/2]
SubBlock::SubBlock (Addr addr, int size)
Definition at line 35 of file SubBlock.cc.
References addr, ArmISA::i, m_address, resize(), and setByte().
~SubBlock()
SubBlock::~SubBlock () inline
Definition at line 43 of file SubBlock.hh.
Member Function Documentation
getAddress()
Addr SubBlock::getAddress () const inline
Definition at line 45 of file SubBlock.hh.
References m_address.
Referenced by RubyTester::hitCallback(), and Check::performCallback().
getByte()
uint8_t SubBlock::getByte (int offset) const inline
Definition at line 50 of file SubBlock.hh.
References m_data, and ArmISA::offset.
Referenced by RubyTester::hitCallback(), internalMergeTo(), Check::performCallback(), and readByte().
getSize()
int SubBlock::getSize () const inline
Definition at line 48 of file SubBlock.hh.
References m_data.
Referenced by RubyTester::hitCallback(), internalMergeFrom(), internalMergeTo(), and print().
internalMergeFrom()
void SubBlock::internalMergeFrom (const DataBlock & data) private
Definition at line 45 of file SubBlock.cc.
References DataBlock::getByte(), getOffset(), getSize(), ArmISA::i, m_address, ArmISA::offset, and setByte().
Referenced by mergeFrom().
internalMergeTo()
void SubBlock::internalMergeTo (DataBlock & data) const private
Definition at line 56 of file SubBlock.cc.
References getByte(), getOffset(), getSize(), ArmISA::i, m_address, ArmISA::offset, and DataBlock::setByte().
Referenced by mergeFrom(), and mergeTo().
mergeFrom()
void SubBlock::mergeFrom (const DataBlock & data) inline
Definition at line 60 of file SubBlock.hh.
References data, internalMergeFrom(), internalMergeTo(), and print().
Referenced by GPUCoalescer::atomicCallback(), and GPUCoalescer::hitCallback().
mergeTo()
void SubBlock::mergeTo (DataBlock & data) const inline
Definition at line 59 of file SubBlock.hh.
References internalMergeTo().
print()
void SubBlock::print (std::ostream & out) const
Definition at line 68 of file SubBlock.cc.
References getSize(), m_address, and m_data.
Referenced by mergeFrom(), and operator<<().
readByte()
uint8_t SubBlock::readByte () const inline
Definition at line 54 of file SubBlock.hh.
References getByte().
resize()
void SubBlock::resize (int size) inline
Definition at line 49 of file SubBlock.hh.
References m_data.
Referenced by SubBlock().
setAddress()
void SubBlock::setAddress (Addr addr) inline
Definition at line 46 of file SubBlock.hh.
References addr, and m_address.
setByte()
void SubBlock::setByte (int offset, uint8_t data) inline
Definition at line 51 of file SubBlock.hh.
References data, m_data, and ArmISA::offset.
Referenced by internalMergeFrom(), Check::performCallback(), SubBlock(), and writeByte().
writeByte()
void SubBlock::writeByte (uint8_t data) inline
Definition at line 55 of file SubBlock.hh.
References setByte().
Member Data Documentation
m_address
Addr SubBlock::m_address private
Definition at line 69 of file SubBlock.hh.
Referenced by getAddress(), internalMergeFrom(), internalMergeTo(), print(), setAddress(), and SubBlock().
m_data
std::vector<uint8_t> SubBlock::m_data private
Definition at line 70 of file SubBlock.hh.
Referenced by getByte(), getSize(), print(), resize(), and setByte().
The documentation for this class was generated from the following files:
mem/ruby/common/SubBlock.hh
mem/ruby/common/SubBlock.cc