gem5: ConfigCache Class Reference
ConfigCache Class Reference
#include <smmu_v3_caches.hh>
Classes
struct Entry
Public Member Functions
ConfigCache (unsigned numEntries, unsigned _associativity, const std::string &policy)
virtual ~ConfigCache ()
const Entry * lookup (uint32_t sid, uint32_t ssid, bool updStats=true)
void store (const Entry &incoming)
void invalidateSSID (uint32_t sid, uint32_t ssid)
void invalidateSID (uint32_t sid)
void invalidateAll ()
Public Member Functions inherited from SMMUv3BaseCache
SMMUv3BaseCache (const std::string &policy_name, uint32_t seed)
virtual ~SMMUv3BaseCache ()
virtual void regStats (const std::string &name)
Private Types
typedef std::vector< Entry > Set
Private Member Functions
size_t pickSetIdx (uint32_t sid, uint32_t ssid) const
size_t pickEntryIdxToReplace (const Set &set)
Private Attributes
std::vector< Set > sets
size_t associativity
Additional Inherited Members
Static Protected Member Functions inherited from SMMUv3BaseCache
static int decodePolicyName (const std::string &policy_name)
Protected Attributes inherited from SMMUv3BaseCache
int replacementPolicy
size_t nextToReplace
Random random
uint32_t useStamp
Stats::Formula averageLookups
Stats::Scalar totalLookups
Stats::Formula averageMisses
Stats::Scalar totalMisses
Stats::Formula averageUpdates
Stats::Scalar totalUpdates
Stats::Formula averageHitRate
Stats::Scalar insertions
Detailed Description
Definition at line 236 of file smmu_v3_caches.hh.
Member Typedef Documentation
Set
typedef std::vector<Entry> ConfigCache::Set private
Definition at line 274 of file smmu_v3_caches.hh.
Constructor & Destructor Documentation
ConfigCache()
ConfigCache::ConfigCache (unsigned numEntries, unsigned _associativity, const std::string & policy)
Definition at line 808 of file smmu_v3_caches.cc.
References associativity, ArmISA::e, fatal, sets, and ConfigCache::Entry::valid.
~ConfigCache()
virtual ConfigCache::~ConfigCache () inline virtual
Definition at line 264 of file smmu_v3_caches.hh.
Member Function Documentation
invalidateAll()
void ConfigCache::invalidateAll ()
Definition at line 918 of file smmu_v3_caches.cc.
References ArmISA::i, ArmISA::s, and sets.
Referenced by SMMUv3::processCommand().
invalidateSID()
void ConfigCache::invalidateSID (uint32_t sid)
Definition at line 903 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ArmISA::s, sets, ConfigCache::Entry::sid, and ConfigCache::Entry::valid.
Referenced by SMMUv3::processCommand().
invalidateSSID()
void ConfigCache::invalidateSSID (uint32_t sid, uint32_t ssid)
Definition at line 890 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, pickSetIdx(), sets, ConfigCache::Entry::sid, ConfigCache::Entry::ssid, and ConfigCache::Entry::valid.
Referenced by SMMUv3::processCommand().
lookup()
const ConfigCache::Entry * ConfigCache::lookup (uint32_t sid, uint32_t ssid, bool updStats = true)
Definition at line 838 of file smmu_v3_caches.cc.
References ArmISA::e, ArmISA::i, ConfigCache::Entry::lastUsed, panic, pickSetIdx(), sets, ConfigCache::Entry::sid, ConfigCache::Entry::ssid, SMMUv3BaseCache::totalLookups, SMMUv3BaseCache::totalMisses, SMMUv3BaseCache::useStamp, and ConfigCache::Entry::valid.
Referenced by SMMUTranslationProcess::configCacheLookup(), and store().
pickEntryIdxToReplace()
size_t ConfigCache::pickEntryIdxToReplace (const Set & set) private
Definition at line 935 of file smmu_v3_caches.cc.
References associativity, ArmISA::i, SMMUv3BaseCache::insertions, SMMUv3BaseCache::nextToReplace, panic, SMMUv3BaseCache::random, Random::random(), SMMUv3BaseCache::replacementPolicy, SMMU_CACHE_REPL_LRU, SMMU_CACHE_REPL_RANDOM, and SMMU_CACHE_REPL_ROUND_ROBIN.
Referenced by store().
pickSetIdx()
size_t ConfigCache::pickSetIdx (uint32_t sid, uint32_t ssid) const private
Definition at line 929 of file smmu_v3_caches.cc.
References sets.
Referenced by invalidateSSID(), lookup(), and store().
store()
void ConfigCache::store (const Entry & incoming)
Definition at line 870 of file smmu_v3_caches.cc.
References ConfigCache::Entry::lastUsed, lookup(), panic, pickEntryIdxToReplace(), pickSetIdx(), sets, ConfigCache::Entry::sid, ConfigCache::Entry::ssid, SMMUv3BaseCache::totalUpdates, and ConfigCache::Entry::valid.
Referenced by SMMUTranslationProcess::configCacheUpdate().
Member Data Documentation
associativity
size_t ConfigCache::associativity private
Definition at line 277 of file smmu_v3_caches.hh.
Referenced by ConfigCache(), and pickEntryIdxToReplace().
sets
std::vector<Set> ConfigCache::sets private
Definition at line 275 of file smmu_v3_caches.hh.
Referenced by ConfigCache(), invalidateAll(), invalidateSID(), invalidateSSID(), lookup(), pickSetIdx(), and store().
The documentation for this class was generated from the following files:
dev/arm/smmu_v3_caches.hh
dev/arm/smmu_v3_caches.cc