gem5: ArmISA::TlbTestInterface Class Reference
ArmISA::TlbTestInterface Class Reference abstract
#include <tlb.hh>
Public Member Functions
TlbTestInterface ()
virtual ~TlbTestInterface ()
virtual Fault translationCheck (const RequestPtr &req, bool is_priv, BaseTLB::Mode mode, TlbEntry::DomainType domain)=0
Check if a TLB translation should be forced to fail.
virtual Fault walkCheck (Addr pa, Addr size, Addr va, bool is_secure, Addr is_priv, BaseTLB::Mode mode, TlbEntry::DomainType domain, LookupLevel lookup_level)=0
Check if a page table walker access should be forced to fail.
Detailed Description
Definition at line 66 of file tlb.hh.
Constructor & Destructor Documentation
TlbTestInterface()
ArmISA::TlbTestInterface::TlbTestInterface () inline
Definition at line 69 of file tlb.hh.
~TlbTestInterface()
virtual ArmISA::TlbTestInterface::~TlbTestInterface () inline virtual
Definition at line 70 of file tlb.hh.
References ArmISA::domain, ArmISA::mode, ArmISA::pa, translationCheck(), ArmISA::va, and walkCheck().
Member Function Documentation
translationCheck()
virtual Fault ArmISA::TlbTestInterface::translationCheck (const RequestPtr & req, bool is_priv, BaseTLB::Mode mode, TlbEntry::DomainType domain) pure virtual
Check if a TLB translation should be forced to fail.
Parameters
req Request requiring a translation.
is_priv Access from a privileged mode (i.e., not EL0)
mode Access type
domain Domain type
Referenced by ~TlbTestInterface().
walkCheck()
virtual Fault ArmISA::TlbTestInterface::walkCheck (Addr pa, Addr size, Addr va, bool is_secure, Addr is_priv, BaseTLB::Mode mode, TlbEntry::DomainType domain, LookupLevel lookup_level) pure virtual
Check if a page table walker access should be forced to fail.
Parameters
pa Physical address the walker is accessing
size Walker access size
va Virtual address that initiated the walk
is_secure Access from secure state
is_priv Access from a privileged mode (i.e., not EL0)
mode Access type
domain Domain type
lookup_level Page table walker level
Referenced by ~TlbTestInterface().
The documentation for this class was generated from the following file:
arch/arm/tlb.hh