gem5: GicV2 Class Reference
GicV2 Class Reference
#include <gic_v2.hh>
Classes
struct BankedRegs
Registers "banked for each connected processor" per ARM IHI0048B.
Public Types
typedef GicV2Params Params
Public Types inherited from BaseGic
enum GicVersion { GicVersion::GIC_V2, GicVersion::GIC_V3, GicVersion::GIC_V4 }
typedef BaseGicParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
GicV2 (const Params *p)
~GicV2 ()
DrainState drain () override
Notify an object that it needs to drain its state.
void drainResume () override
Resume execution after a successful drain.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
AddrRangeList getAddrRanges () const override
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Tick read (PacketPtr pkt) override
A PIO read to the device, immediately split up into readDistributor() or readCpu()
Tick write (PacketPtr pkt) override
A PIO read to the device, immediately split up into writeDistributor() or writeCpu()
void sendInt (uint32_t number) override
Post an interrupt from a device that is connected to the GIC.
void clearInt (uint32_t number) override
Clear an interrupt from a device that is connected to the GIC.
void sendPPInt (uint32_t num, uint32_t cpu) override
Interface call for private peripheral interrupts.
void clearPPInt (uint32_t num, uint32_t cpu) override
bool supportsVersion (GicVersion version) override
Check if version supported.
Public Member Functions inherited from BaseGic
BaseGic (const Params *p)
virtual ~BaseGic ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
const Params * params () const
ArmSystem * getSystem () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum {
GICD_CTLR = 0x000, GICD_TYPER = 0x004, GICD_IIDR = 0x008, GICD_SGIR = 0xf00,
GICD_PIDR0 = 0xfe0, GICD_PIDR1 = 0xfe4, GICD_PIDR2 = 0xfe8, GICD_PIDR3 = 0xfec,
DIST_SIZE = 0x1000
}
enum {
GICC_CTLR = 0x00, GICC_PMR = 0x04, GICC_BPR = 0x08, GICC_IAR = 0x0C,
GICC_EOIR = 0x10, GICC_RPR = 0x14, GICC_HPPIR = 0x18, GICC_ABPR = 0x1c,
GICC_APR0 = 0xd0, GICC_APR1 = 0xd4, GICC_APR2 = 0xd8, GICC_APR3 = 0xdc,
GICC_IIDR = 0xfc, GICC_DIR = 0x1000
}
Protected Member Functions
BitUnion32 (SWI) Bitfield< 3
EndBitUnion (SWI) BitUnion32(IAR) Bitfield< 9
EndBitUnion (IAR) BitUnion32(CTLR) Bitfield< 3 > fiqEn
BankedRegs & getBankedRegs (ContextID)
uint32_t & getIntEnabled (ContextID ctx, uint32_t ix)
uint32_t & getPendingInt (ContextID ctx, uint32_t ix)
uint32_t & getActiveInt (ContextID ctx, uint32_t ix)
uint32_t & getIntGroup (ContextID ctx, uint32_t ix)
uint8_t & getIntPriority (ContextID ctx, uint32_t ix)
uint8_t getIntConfig (ContextID ctx, uint32_t ix)
GICD_ICFGRn get 2 bit config associated to an interrupt.
uint8_t getCpuTarget (ContextID ctx, uint32_t ix)
bool isLevelSensitive (ContextID ctx, uint32_t ix)
bool isGroup0 (ContextID ctx, uint32_t int_num)
bool isFiq (ContextID ctx, uint32_t int_num)
This method checks if an interrupt ID must be signaled or has been signaled as a FIQ to the cpu.
bool cpuEnabled (ContextID ctx) const
CPU enabled: Checks if GICC_CTLR.EnableGrp0 or EnableGrp1 are set.
uint8_t getCpuPriority (unsigned cpu)
void softInt (ContextID ctx, SWI swi)
software generated interrupt
virtual void updateIntState (int hint)
See if some processor interrupt flags need to be enabled/disabled.
void updateRunPri ()
Update the register that records priority of the highest priority active interrupt.
uint64_t genSwiMask (int cpu)
generate a bit mask to check cpuSgi for an interrupt.
int intNumToWord (int num) const
int intNumToBit (int num) const
void clearInt (ContextID ctx, uint32_t int_num)
Clears a cpu IRQ or FIQ signal.
void postInt (uint32_t cpu, Tick when)
Post an interrupt to a CPU with a delay.
void postFiq (uint32_t cpu, Tick when)
void postDelayedInt (uint32_t cpu)
Deliver a delayed interrupt to the target CPU.
void postDelayedFiq (uint32_t cpu)
Tick readDistributor (PacketPtr pkt)
Handle a read to the distributor portion of the GIC.
uint32_t readDistributor (ContextID ctx, Addr daddr, size_t resp_sz)
uint32_t readDistributor (ContextID ctx, Addr daddr) override
Tick readCpu (PacketPtr pkt)
Handle a read to the cpu portion of the GIC.
uint32_t readCpu (ContextID ctx, Addr daddr) override
Tick writeDistributor (PacketPtr pkt)
Handle a write to the distributor portion of the GIC.
void writeDistributor (ContextID ctx, Addr daddr, uint32_t data, size_t data_sz)
void writeDistributor (ContextID ctx, Addr daddr, uint32_t data) override
Tick writeCpu (PacketPtr pkt)
Handle a write to the cpu portion of the GIC.
void writeCpu (ContextID ctx, Addr daddr, uint32_t data) override
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
const uint32_t gicdPIDR
const uint32_t gicdIIDR
const uint32_t giccIIDR
sgi_id
Bitfield< 23, 16 > cpu_list
Bitfield< 25, 24 > list_type
ack_id
Bitfield< 12, 10 > cpu_id
Bitfield< 1 > enableGrp1
Bitfield< 0 > enableGrp0
EndBitUnion(CTLR) protected const AddrRange cpuRange
Address range for the distributor interface.
const AddrRangeList addrRanges
All address ranges used by this GIC.
const Tick distPioDelay
Latency for a distributor operation.
const Tick cpuPioDelay
Latency for a cpu operation.
const Tick intLatency
Latency for a interrupt to get to CPU.
bool enabled
Gic enabled.
const bool haveGem5Extensions
Are gem5 extensions available?
bool gem5ExtensionsEnabled
gem5 many-core extension enabled by driver
uint32_t itLines
Number of itLines enabled.
std::vector< BankedRegs * > bankedRegs
uint32_t intEnabled [INT_BITS_MAX-1]
GICD_I{S,C}ENABLER{1..31} interrupt enable bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t pendingInt [INT_BITS_MAX-1]
GICD_I{S,C}PENDR{1..31} interrupt pending bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t activeInt [INT_BITS_MAX-1]
GICD_I{S,C}ACTIVER{1..31} interrupt active bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t intGroup [INT_BITS_MAX-1]
GICD_IGROUPR{1..31} interrupt group bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
uint32_t iccrpr [CPU_MAX]
read only running priority register, 1 per cpu
uint8_t intPriority [GLOBAL_INT_LINES]
GICD_IPRIORITYR{8..255} an 8 bit priority (lower is higher priority) for each of the global (not replicated per CPU) interrupts.
uint8_t cpuTarget [GLOBAL_INT_LINES]
GICD_ITARGETSR{8..255} an 8 bit cpu target id for each global interrupt.
uint32_t intConfig [INT_BITS_MAX *2]
2 bit per interrupt signaling if it's level or edge sensitive and if it is 1:N or N:N
CTLR cpuControl [CPU_MAX]
GICC_CTLR: CPU interface control register.
uint8_t cpuPriority [CPU_MAX]
CPU priority.
uint8_t cpuBpr [CPU_MAX]
Binary point registers.
uint32_t cpuHighestInt [CPU_MAX]
highest interrupt that is interrupting CPU
uint64_t cpuSgiPending [SGI_MAX]
One bit per cpu per software interrupt that is pending for each possible sgi source.
uint64_t cpuSgiActive [SGI_MAX]
uint32_t cpuSgiPendingExt [CPU_MAX]
SGI pending arrays for gem5 GIC extension mode, which instead keeps 16 SGI pending bits for each of the (large number of) CPUs.
uint32_t cpuSgiActiveExt [CPU_MAX]
uint32_t cpuPpiPending [CPU_MAX]
One bit per private peripheral interrupt.
uint32_t cpuPpiActive [CPU_MAX]
EventFunctionWrapper * postIntEvent [CPU_MAX]
EventFunctionWrapper * postFiqEvent [CPU_MAX]
int pendingDelayedInterrupts
Protected Attributes inherited from BaseGic
Platform * platform
Platform this GIC belongs to.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Static Protected Attributes
static const AddrRange GICD_IGROUPR
static const AddrRange GICD_ISENABLER
static const AddrRange GICD_ICENABLER
static const AddrRange GICD_ISPENDR
static const AddrRange GICD_ICPENDR
static const AddrRange GICD_ISACTIVER
static const AddrRange GICD_ICACTIVER
static const AddrRange GICD_IPRIORITYR
static const AddrRange GICD_ITARGETSR
static const AddrRange GICD_ICFGR
static const int SGI_MAX = 16
static const int PPI_MAX = 16
static const int SGI_MASK = 0xFFFF0000
Mask off SGI's when setting/clearing pending bits.
static const int NN_CONFIG_MASK = 0x55555555
Mask for bits that config N:N mode in GICD_ICFGR's.
static const int CPU_MAX = 256
static const int SPURIOUS_INT = 1023
static const int INT_BITS_MAX = 32
static const int INT_LINES_MAX = 1020
static const int GLOBAL_INT_LINES = INT_LINES_MAX - SGI_MAX - PPI_MAX
static const int GICC_BPR_MINIMUM = 2
minimum value for Binary Point Register ("IMPLEMENTATION DEFINED"); chosen for consistency with Linux's in-kernel KVM GIC model
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 61 of file gic_v2.hh.
Member Typedef Documentation
Params
typedef GicV2Params GicV2::Params
Definition at line 443 of file gic_v2.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
GICD_CTLR
GICD_TYPER
GICD_IIDR
GICD_SGIR
GICD_PIDR0
GICD_PIDR1
GICD_PIDR2
GICD_PIDR3
DIST_SIZE
Definition at line 65 of file gic_v2.hh.
anonymous enum
anonymous enum protected
Enumerator
GICC_CTLR
GICC_PMR
GICC_BPR
GICC_IAR
GICC_EOIR
GICC_RPR
GICC_HPPIR
GICC_ABPR
GICC_APR0
GICC_APR1
GICC_APR2
GICC_APR3
GICC_IIDR
GICC_DIR
Definition at line 94 of file gic_v2.hh.
Constructor & Destructor Documentation
GicV2()
GicV2::GicV2 (const Params * p)
Definition at line 65 of file gic_v2.cc.
References activeInt, CPU_MAX, cpuBpr, cpuControl, cpuEnabled(), cpuHighestInt, cpuPioDelay, cpuPpiActive, cpuPpiPending, cpuPriority, cpuRange, cpuSgiActive, cpuSgiActiveExt, cpuSgiPending, cpuSgiPendingExt, cpuTarget, distPioDelay, DPRINTF, enabled, gem5ExtensionsEnabled, GICC_BPR_MINIMUM, haveGem5Extensions, iccrpr, intConfig, intEnabled, intLatency, intPriority, itLines, MipsISA::p, pendingDelayedInterrupts, pendingInt, postDelayedFiq(), postDelayedInt(), postFiqEvent, postIntEvent, SPURIOUS_INT, and X86ISA::x.
Referenced by params(), and GicV2::BankedRegs::unserialize().
~GicV2()
GicV2::~GicV2 ()
Definition at line 104 of file gic_v2.cc.
References CPU_MAX, postFiqEvent, postIntEvent, and X86ISA::x.
Referenced by params().
Member Function Documentation
BitUnion32()
GicV2::BitUnion32 (SWI) protected
clearInt() [1/2]
void GicV2::clearInt (ContextID ctx, uint32_t int_num) protected
Clears a cpu IRQ or FIQ signal.
Definition at line 916 of file gic_v2.cc.
References IntrControl::clear(), ArmISA::INT_FIQ, ArmISA::INT_IRQ, Platform::intrctrl, isFiq(), and BaseGic::platform.
Referenced by MuxingKvmGic::clearInt(), getAddrRanges(), intNumToBit(), readCpu(), and updateIntState().
clearInt() [2/2]
void GicV2::clearInt (uint32_t num) override virtual
Clear an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC may de-assert it's CPU line.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 888 of file gic_v2.cc.
References DPRINTF, getCpuTarget(), getPendingInt(), intNumToBit(), intNumToWord(), isLevelSensitive(), and updateIntState().
clearPPInt()
void GicV2::clearPPInt (uint32_t num, uint32_t cpu) override virtual
Implements BaseGic.
Definition at line 907 of file gic_v2.cc.
References cpuPpiPending, DPRINTF, intNumToWord(), SGI_MAX, and updateIntState().
Referenced by MuxingKvmGic::clearPPInt(), and getAddrRanges().
cpuEnabled()
bool GicV2::cpuEnabled (ContextID ctx) const inline protected
CPU enabled: Checks if GICC_CTLR.EnableGrp0 or EnableGrp1 are set.
Definition at line 365 of file gic_v2.hh.
References cpuControl.
Referenced by GicV2(), readCpu(), softInt(), updateIntState(), updateRunPri(), and writeCpu().
drain()
DrainState GicV2::drain () override virtual
Notify an object that it needs to drain its state.
If the object does not need further simulation to drain internal buffers, it returns DrainState::Drained and automatically switches to the Drained state. If the object needs more simulation, it returns DrainState::Draining and automatically enters the Draining state. Other return values are invalid.
Note
An object that has entered the Drained state can be disturbed by other objects in the system and consequently stop being drained. These perturbations are not visible in the drain state. The simulator therefore repeats the draining process until all objects return DrainState::Drained on the first call to drain().
Returns
DrainState::Drained if the object is drained at this point in time, DrainState::Draining if it needs further simulation.
Implements Drainable.
Definition at line 970 of file gic_v2.cc.
References Drained, Draining, and pendingDelayedInterrupts.
Referenced by MuxingKvmGic::drain(), and params().
drainResume()
void GicV2::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 981 of file gic_v2.cc.
References updateIntState().
Referenced by MuxingKvmGic::drainResume(), and params().
EndBitUnion() [1/2]
GicV2::EndBitUnion (SWI) protected
EndBitUnion() [2/2]
GicV2::EndBitUnion (IAR) protected
genSwiMask()
uint64_t GicV2::genSwiMask (int cpu) protected
generate a bit mask to check cpuSgi for an interrupt.
Definition at line 719 of file gic_v2.cc.
References System::numContexts(), panic, PioDevice::sys, and ULL.
Referenced by updateIntState(), and updateRunPri().
getActiveInt()
uint32_t& GicV2::getActiveInt (ContextID ctx, uint32_t ix) inline protected
Definition at line 245 of file gic_v2.hh.
References GicV2::BankedRegs::activeInt, and getBankedRegs().
Referenced by readCpu(), readDistributor(), updateIntState(), updateRunPri(), writeCpu(), and writeDistributor().
getAddrRanges()
AddrRangeList GicV2::getAddrRanges () const inline override virtual
Every PIO device is obliged to provide an implementation that returns the address ranges the device responds to.
Returns
a list of non-overlapping address ranges
Implements PioDevice.
Definition at line 459 of file gic_v2.hh.
References addrRanges, clearInt(), clearPPInt(), read(), readDistributor(), sendInt(), sendPPInt(), supportsVersion(), and write().
getBankedRegs()
GicV2::BankedRegs & GicV2::getBankedRegs (ContextID ctx) protected
Definition at line 639 of file gic_v2.cc.
References bankedRegs.
Referenced by getActiveInt(), getIntEnabled(), getIntGroup(), getIntPriority(), getPendingInt(), and unserialize().
getCpuPriority()
uint8_t GicV2::getCpuPriority (unsigned cpu) protected
Definition at line 727 of file gic_v2.cc.
References cpuBpr, and cpuPriority.
Referenced by updateIntState().
getCpuTarget()
uint8_t GicV2::getCpuTarget (ContextID ctx, uint32_t ix) inline protected
Definition at line 301 of file gic_v2.hh.
References fatal_if, gem5ExtensionsEnabled, and SimObject::name().
Referenced by clearInt(), readDistributor(), sendInt(), and updateIntState().
getIntConfig()
uint8_t GicV2::getIntConfig (ContextID ctx, uint32_t ix) inline protected
GICD_ICFGRn get 2 bit config associated to an interrupt.
Definition at line 289 of file gic_v2.hh.
References bits(), intConfig, intNumToBit(), and intNumToWord().
Referenced by isLevelSensitive().
getIntEnabled()
uint32_t& GicV2::getIntEnabled (ContextID ctx, uint32_t ix) inline protected
Definition at line 218 of file gic_v2.hh.
References getBankedRegs(), and GicV2::BankedRegs::intEnabled.
Referenced by readDistributor(), updateIntState(), and writeDistributor().
getIntGroup()
uint32_t& GicV2::getIntGroup (ContextID ctx, uint32_t ix) inline protected
Definition at line 259 of file gic_v2.hh.
References getBankedRegs(), and GicV2::BankedRegs::intGroup.
Referenced by isGroup0(), readDistributor(), and writeDistributor().
getIntPriority()
uint8_t& GicV2::getIntPriority (ContextID ctx, uint32_t ix) inline protected
Definition at line 277 of file gic_v2.hh.
References getBankedRegs(), GicV2::BankedRegs::intPriority, and PPI_MAX.
Referenced by readDistributor(), updateIntState(), updateRunPri(), and writeDistributor().
getPendingInt()
uint32_t& GicV2::getPendingInt (ContextID ctx, uint32_t ix) inline protected
Definition at line 231 of file gic_v2.hh.
References getBankedRegs(), and GicV2::BankedRegs::pendingInt.
Referenced by clearInt(), readCpu(), readDistributor(), sendInt(), updateIntState(), and writeDistributor().
intNumToBit()
int GicV2::intNumToBit (int num) const inline protected
Definition at line 421 of file gic_v2.hh.
References clearInt(), postDelayedFiq(), postDelayedInt(), postFiq(), and postInt().
Referenced by clearInt(), getIntConfig(), isGroup0(), readCpu(), sendInt(), updateIntState(), updateRunPri(), and writeCpu().
intNumToWord()
int GicV2::intNumToWord (int num) const inline protected
Definition at line 420 of file gic_v2.hh.
Referenced by clearInt(), clearPPInt(), getIntConfig(), isGroup0(), readCpu(), sendInt(), sendPPInt(), updateIntState(), updateRunPri(), and writeCpu().
isFiq()
bool GicV2::isFiq (ContextID ctx, uint32_t int_num) inline protected
This method checks if an interrupt ID must be signaled or has been signaled as a FIQ to the cpu.
It does that by reading:
1) GICD_IGROUPR: controls if the interrupt is part of group0 or group1. Only group0 interrupts can be signaled as FIQs.
2) GICC_CTLR.FIQEn: controls whether the CPU interface signals Group 0 interrupts to a target processor using the FIQ or the IRQ signal
Definition at line 351 of file gic_v2.hh.
References cpuControl, and isGroup0().
Referenced by clearInt(), and updateIntState().
isGroup0()
bool GicV2::isGroup0 (ContextID ctx, uint32_t int_num) inline protected
Definition at line 336 of file gic_v2.hh.
References bits(), getIntGroup(), intNumToBit(), and intNumToWord().
Referenced by isFiq().
isLevelSensitive()
bool GicV2::isLevelSensitive (ContextID ctx, uint32_t ix) inline protected
Definition at line 328 of file gic_v2.hh.
References bits(), and getIntConfig().
Referenced by clearInt(), readCpu(), and updateIntState().
params()
const Params* GicV2::params () const inline
Definition at line 445 of file gic_v2.hh.
References SimObject::_params, drain(), drainResume(), GicV2(), MipsISA::p, serialize(), unserialize(), and ~GicV2().
postDelayedFiq()
void GicV2::postDelayedFiq (uint32_t cpu) protected
Definition at line 960 of file gic_v2.cc.
References ArmISA::INT_FIQ, Platform::intrctrl, pendingDelayedInterrupts, BaseGic::platform, IntrControl::post(), and Drainable::signalDrainDone().
Referenced by GicV2(), and intNumToBit().
postDelayedInt()
void GicV2::postDelayedInt (uint32_t cpu) protected
Deliver a delayed interrupt to the target CPU.
Definition at line 935 of file gic_v2.cc.
References ArmISA::INT_IRQ, Platform::intrctrl, pendingDelayedInterrupts, BaseGic::platform, IntrControl::post(), and Drainable::signalDrainDone().
Referenced by GicV2(), and intNumToBit().
postFiq()
void GicV2::postFiq (uint32_t cpu, Tick when) protected
Definition at line 945 of file gic_v2.cc.
References EventManager::eventq, pendingDelayedInterrupts, postFiqEvent, and EventQueue::schedule().
Referenced by intNumToBit(), and updateIntState().
postInt()
void GicV2::postInt (uint32_t cpu, Tick when) protected
Post an interrupt to a CPU with a delay.
Definition at line 926 of file gic_v2.cc.
References EventManager::eventq, pendingDelayedInterrupts, postIntEvent, and EventQueue::schedule().
Referenced by intNumToBit(), and updateIntState().
read()
Tick GicV2::read (PacketPtr pkt) override virtual
A PIO read to the device, immediately split up into readDistributor() or readCpu()
Implements PioDevice.
Definition at line 113 of file gic_v2.cc.
References addr, AddrRange::contains(), cpuRange, Packet::getAddr(), panic, readCpu(), and readDistributor().
Referenced by getAddrRanges(), and MuxingKvmGic::read().
readCpu() [1/2]
Tick GicV2::readCpu (PacketPtr pkt) protected
Handle a read to the cpu portion of the GIC.
Parameters
pkt packet to respond to
Definition at line 291 of file gic_v2.cc.
References cpuPioDelay, cpuRange, DPRINTF, Packet::getAddr(), Packet::makeAtomicResponse(), Packet::req, Packet::setLE(), and AddrRange::start().
Referenced by read(), and readDistributor().
readCpu() [2/2]
uint32_t GicV2::readCpu (ContextID ctx, Addr daddr) override protected virtual
Implements BaseGicRegisters.
Definition at line 309 of file gic_v2.cc.
References bits(), clearInt(), cpuBpr, cpuControl, cpuEnabled(), cpuHighestInt, cpuPpiActive, cpuPpiPending, cpuPriority, cpuSgiActive, cpuSgiActiveExt, cpuSgiPending, cpuSgiPendingExt, DPRINTF, enabled, gem5ExtensionsEnabled, getActiveInt(), getPendingInt(), GICC_BPR, GICC_CTLR, GICC_HPPIR, GICC_IAR, GICC_IIDR, GICC_PMR, GICC_RPR, giccIIDR, iccrpr, intNumToBit(), intNumToWord(), isLevelSensitive(), System::numRunningContexts(), panic, panic_if, PPI_MAX, SGI_MAX, SPURIOUS_INT, PioDevice::sys, ULL, updateIntState(), updateRunPri(), and X86ISA::x.
readDistributor() [1/3]
Tick GicV2::readDistributor (PacketPtr pkt) protected
Handle a read to the distributor portion of the GIC.
Parameters
pkt packet to respond to
Definition at line 140 of file gic_v2.cc.
References distPioDelay, DPRINTF, Packet::getAddr(), Packet::getSize(), Packet::makeAtomicResponse(), panic, Packet::req, and Packet::setLE().
Referenced by getAddrRanges(), read(), and readDistributor().
readDistributor() [2/3]
uint32_t GicV2::readDistributor (ContextID ctx, Addr daddr, size_t resp_sz) protected
Todo:
software generated interrupts and PPIs can't be configured in some ways
Definition at line 169 of file gic_v2.cc.
References AddrRange::contains(), DPRINTF, enabled, getActiveInt(), getCpuTarget(), getIntEnabled(), getIntGroup(), getIntPriority(), getPendingInt(), GICD_CTLR, GICD_ICACTIVER, GICD_ICENABLER, GICD_ICFGR, GICD_ICPENDR, GICD_IGROUPR, GICD_IIDR, GICD_IPRIORITYR, GICD_ISACTIVER, GICD_ISENABLER, GICD_ISPENDR, GICD_ITARGETSR, GICD_PIDR0, GICD_PIDR1, GICD_PIDR2, GICD_PIDR3, GICD_TYPER, gicdIIDR, gicdPIDR, haveGem5Extensions, INT_BITS_MAX, INT_LINES_MAX, intConfig, itLines, mbits(), System::numRunningContexts(), panic, AddrRange::start(), and PioDevice::sys.
readDistributor() [3/3]
uint32_t GicV2::readDistributor (ContextID ctx, Addr daddr) inline override protected virtual
Implements BaseGicRegisters.
Definition at line 487 of file gic_v2.hh.
References data, readCpu(), readDistributor(), and writeDistributor().
sendInt()
void GicV2::sendInt (uint32_t num) override virtual
Post an interrupt from a device that is connected to the GIC.
Depending on the configuration, the GIC will pass this interrupt on through to a CPU.
Parameters
num number of interrupt to send
Implements BaseGic.
Definition at line 865 of file gic_v2.cc.
References DPRINTF, gem5ExtensionsEnabled, getCpuTarget(), getPendingInt(), intNumToBit(), intNumToWord(), panic, panic_if, PPI_MAX, SGI_MAX, and updateIntState().
Referenced by getAddrRanges(), and MuxingKvmGic::sendInt().
sendPPInt()
void GicV2::sendPPInt (uint32_t num, uint32_t cpu) override virtual
Interface call for private peripheral interrupts.
Parameters
num number of interrupt to send
cpu CPU to forward interrupt to
Implements BaseGic.
Definition at line 879 of file gic_v2.cc.
References cpuPpiPending, DPRINTF, intNumToWord(), SGI_MAX, and updateIntState().
Referenced by getAddrRanges(), and MuxingKvmGic::sendPPInt().
serialize()
void GicV2::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 988 of file gic_v2.cc.
References activeInt, bankedRegs, CPU_MAX, cpuBpr, cpuControl, cpuHighestInt, cpuPpiActive, cpuPpiPending, cpuPriority, cpuSgiActive, cpuSgiActiveExt, cpuSgiPending, cpuSgiPendingExt, cpuTarget, csprintf(), DPRINTF, enabled, gem5ExtensionsEnabled, GLOBAL_INT_LINES, ArmISA::i, iccrpr, INT_BITS_MAX, intConfig, intEnabled, intGroup, intPriority, itLines, pendingInt, SERIALIZE_ARRAY, SERIALIZE_SCALAR, and SGI_MAX.
Referenced by params().
softInt()
void GicV2::softInt (ContextID ctx, SWI swi) protected
software generated interrupt
Parameters
data data to decode that indicates which cpus to interrupt
Definition at line 649 of file gic_v2.cc.
References cpu_list, cpuEnabled(), cpuSgiPending, cpuSgiPendingExt, DPRINTF, gem5ExtensionsEnabled, ArmISA::i, System::numContexts(), PioDevice::sys, updateIntState(), and X86ISA::x.
Referenced by writeDistributor().
supportsVersion()
bool GicV2::supportsVersion (GicVersion version) override virtual
Check if version supported.
Implements BaseGic.
Definition at line 954 of file gic_v2.cc.
References BaseGic::GIC_V2.
Referenced by getAddrRanges().
unserialize()
void GicV2::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 1032 of file gic_v2.cc.
References activeInt, CPU_MAX, cpuBpr, cpuControl, cpuHighestInt, cpuPpiActive, cpuPpiPending, cpuPriority, cpuSgiActive, cpuSgiActiveExt, cpuSgiPending, cpuSgiPendingExt, cpuTarget, csprintf(), Serializable::currentSection(), DPRINTF, enabled, CheckpointIn::entryExists(), gem5ExtensionsEnabled, getBankedRegs(), GLOBAL_INT_LINES, ArmISA::i, iccrpr, INT_BITS_MAX, intConfig, intEnabled, intGroup, intPriority, itLines, pendingInt, postIntEvent, EventManager::schedule(), CheckpointIn::sectionExists(), SGI_MAX, GicV2::BankedRegs::unserialize(), UNSERIALIZE_ARRAY, UNSERIALIZE_OPT_SCALAR, and UNSERIALIZE_SCALAR.
Referenced by params().
updateIntState()
void GicV2::updateIntState (int hint) protected virtual
See if some processor interrupt flags need to be enabled/disabled.
Parameters
hint which set of interrupts needs to be checked
Reimplemented in MuxingKvmGic.
Definition at line 738 of file gic_v2.cc.
References bits(), clearInt(), cpuEnabled(), cpuHighestInt, cpuPpiPending, cpuSgiPending, cpuSgiPendingExt, curTick(), DPRINTF, enabled, gem5ExtensionsEnabled, genSwiMask(), getActiveInt(), getCpuPriority(), getCpuTarget(), getIntEnabled(), getIntPriority(), getPendingInt(), INT_BITS_MAX, intLatency, intNumToBit(), intNumToWord(), isFiq(), isLevelSensitive(), itLines, System::numContexts(), System::numRunningContexts(), postFiq(), postInt(), PPI_MAX, SGI_MAX, SPURIOUS_INT, PioDevice::sys, and X86ISA::x.
Referenced by clearInt(), clearPPInt(), drainResume(), readCpu(), sendInt(), sendPPInt(), softInt(), MuxingKvmGic::updateIntState(), writeCpu(), and writeDistributor().
updateRunPri()
void GicV2::updateRunPri () protected
Update the register that records priority of the highest priority active interrupt.
Definition at line 836 of file gic_v2.cc.
References cpuEnabled(), cpuPpiActive, cpuSgiActive, cpuSgiActiveExt, genSwiMask(), getActiveInt(), getIntPriority(), ArmISA::i, iccrpr, intNumToBit(), intNumToWord(), itLines, System::numContexts(), PPI_MAX, SGI_MAX, and PioDevice::sys.
Referenced by readCpu(), writeCpu(), and writeDistributor().
write()
Tick GicV2::write (PacketPtr pkt) override virtual
A PIO read to the device, immediately split up into writeDistributor() or writeCpu()
Implements PioDevice.
Definition at line 127 of file gic_v2.cc.
References addr, AddrRange::contains(), cpuRange, Packet::getAddr(), panic, writeCpu(), and writeDistributor().
Referenced by getAddrRanges(), and MuxingKvmGic::write().
writeCpu() [1/2]
Tick GicV2::writeCpu (PacketPtr pkt) protected
Handle a write to the cpu portion of the GIC.
Parameters
pkt packet to respond to
Definition at line 558 of file gic_v2.cc.
References cpuPioDelay, cpuRange, data, DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::makeAtomicResponse(), Packet::req, and AddrRange::start().
Referenced by write(), and writeDistributor().
writeCpu() [2/2]
void GicV2::writeCpu (ContextID ctx, Addr daddr, uint32_t data) override protected virtual
Implements BaseGicRegisters.
Definition at line 576 of file gic_v2.cc.
References cpuBpr, cpuControl, cpuEnabled(), cpuPpiActive, cpuPriority, cpuSgiActive, cpuSgiActiveExt, data, DPRINTF, gem5ExtensionsEnabled, getActiveInt(), GICC_APR0, GICC_APR1, GICC_APR2, GICC_APR3, GICC_BPR, GICC_BPR_MINIMUM, GICC_CTLR, GICC_DIR, GICC_EOIR, GICC_PMR, intNumToBit(), intNumToWord(), panic, PPI_MAX, SGI_MAX, ULL, updateIntState(), updateRunPri(), and warn.
writeDistributor() [1/3]
Tick GicV2::writeDistributor (PacketPtr pkt) protected
Handle a write to the distributor portion of the GIC.
Parameters
pkt packet to respond to
Definition at line 389 of file gic_v2.cc.
References distPioDelay, DPRINTF, Packet::getAddr(), Packet::getLE(), Packet::getSize(), M5_VAR_USED, Packet::makeAtomicResponse(), panic, and Packet::req.
Referenced by readDistributor(), write(), and writeDistributor().
writeDistributor() [2/3]
void GicV2::writeDistributor (ContextID ctx, Addr daddr, uint32_t data, size_t data_sz) protected
Definition at line 424 of file gic_v2.cc.
References bits(), AddrRange::contains(), cpuTarget, data, DPRINTF, enabled, gem5ExtensionsEnabled, getActiveInt(), getIntEnabled(), getIntGroup(), getIntPriority(), getPendingInt(), GICD_CTLR, GICD_ICACTIVER, GICD_ICENABLER, GICD_ICFGR, GICD_ICPENDR, GICD_IGROUPR, GICD_IPRIORITYR, GICD_ISACTIVER, GICD_ISENABLER, GICD_ISPENDR, GICD_ITARGETSR, GICD_SGIR, GICD_TYPER, haveGem5Extensions, INT_BITS_MAX, intConfig, ArmISA::mask, NN_CONFIG_MASK, ArmISA::offset, panic, PPI_MAX, SGI_MASK, SGI_MAX, softInt(), AddrRange::start(), updateIntState(), updateRunPri(), and warn.
writeDistributor() [3/3]
void GicV2::writeDistributor (ContextID ctx, Addr daddr, uint32_t data) inline override protected virtual
Implements BaseGicRegisters.
Definition at line 503 of file gic_v2.hh.
References writeCpu(), and writeDistributor().
Member Data Documentation
ack_id
GicV2::ack_id protected
Definition at line 137 of file gic_v2.hh.
activeInt
uint32_t GicV2::activeInt[INT_BITS_MAX-1] protected
GICD_I{S,C}ACTIVER{1..31} interrupt active bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
Definition at line 243 of file gic_v2.hh.
Referenced by GicV2(), GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), and unserialize().
addrRanges
const AddrRangeList GicV2::addrRanges protected
All address ranges used by this GIC.
Definition at line 155 of file gic_v2.hh.
Referenced by getAddrRanges().
bankedRegs
std::vector<BankedRegs*> GicV2::bankedRegs protected
Definition at line 209 of file gic_v2.hh.
Referenced by getBankedRegs(), and serialize().
cpu_id
Bitfield<12,10> GicV2::cpu_id protected
Definition at line 138 of file gic_v2.hh.
cpu_list
Bitfield<23,16> GicV2::cpu_list protected
Definition at line 132 of file gic_v2.hh.
Referenced by softInt().
CPU_MAX
const int GicV2::CPU_MAX = 256 static protected
Definition at line 120 of file gic_v2.hh.
Referenced by GicV2(), serialize(), unserialize(), and ~GicV2().
cpuBpr
uint8_t GicV2::cpuBpr[CPU_MAX] protected
Binary point registers.
Definition at line 380 of file gic_v2.hh.
Referenced by getCpuPriority(), GicV2(), readCpu(), serialize(), unserialize(), and writeCpu().
cpuControl
CTLR GicV2::cpuControl[CPU_MAX] protected
GICC_CTLR: CPU interface control register.
Definition at line 373 of file gic_v2.hh.
Referenced by cpuEnabled(), GicV2(), isFiq(), readCpu(), serialize(), unserialize(), and writeCpu().
cpuHighestInt
uint32_t GicV2::cpuHighestInt[CPU_MAX] protected
highest interrupt that is interrupting CPU
Definition at line 383 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), unserialize(), and updateIntState().
cpuPioDelay
const Tick GicV2::cpuPioDelay protected
Latency for a cpu operation.
Definition at line 161 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), and writeCpu().
cpuPpiActive
uint32_t GicV2::cpuPpiActive[CPU_MAX] protected
Definition at line 401 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), unserialize(), updateRunPri(), and writeCpu().
cpuPpiPending
uint32_t GicV2::cpuPpiPending[CPU_MAX] protected
One bit per private peripheral interrupt.
Only upper 16 bits will be used since PPI interrupts are numberred from 16 to 32
Definition at line 400 of file gic_v2.hh.
Referenced by clearPPInt(), GicV2(), readCpu(), sendPPInt(), serialize(), unserialize(), and updateIntState().
cpuPriority
uint8_t GicV2::cpuPriority[CPU_MAX] protected
CPU priority.
Definition at line 376 of file gic_v2.hh.
Referenced by MuxingKvmGic::fromKvmToGicV2(), getCpuPriority(), GicV2(), readCpu(), serialize(), unserialize(), and writeCpu().
cpuRange
EndBitUnion (CTLR) protected const AddrRange GicV2::cpuRange protected
Address range for the distributor interface.
Address range for the CPU interfaces
Definition at line 145 of file gic_v2.hh.
Referenced by GicV2(), read(), readCpu(), write(), and writeCpu().
cpuSgiActive
uint64_t GicV2::cpuSgiActive[SGI_MAX] protected
Definition at line 390 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), unserialize(), updateRunPri(), and writeCpu().
cpuSgiActiveExt
uint32_t GicV2::cpuSgiActiveExt[CPU_MAX] protected
Definition at line 396 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), unserialize(), updateRunPri(), and writeCpu().
cpuSgiPending
uint64_t GicV2::cpuSgiPending[SGI_MAX] protected
One bit per cpu per software interrupt that is pending for each possible sgi source.
Indexed by SGI number. Each byte in generating cpu id and bits in position is destination id. e.g. 0x4 = CPU 0 generated interrupt for CPU 2.
Definition at line 389 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), softInt(), unserialize(), and updateIntState().
cpuSgiPendingExt
uint32_t GicV2::cpuSgiPendingExt[CPU_MAX] protected
SGI pending arrays for gem5 GIC extension mode, which instead keeps 16 SGI pending bits for each of the (large number of) CPUs.
Definition at line 395 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), softInt(), unserialize(), and updateIntState().
cpuTarget
uint8_t GicV2::cpuTarget[GLOBAL_INT_LINES] protected
GICD_ITARGETSR{8..255} an 8 bit cpu target id for each global interrupt.
Definition at line 299 of file gic_v2.hh.
Referenced by GicV2(), serialize(), unserialize(), and writeDistributor().
distPioDelay
const Tick GicV2::distPioDelay protected
Latency for a distributor operation.
Definition at line 158 of file gic_v2.hh.
Referenced by GicV2(), readDistributor(), and writeDistributor().
enabled
bool GicV2::enabled protected
Gic enabled.
Definition at line 168 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), readDistributor(), serialize(), unserialize(), updateIntState(), and writeDistributor().
enableGrp0
Bitfield<0> GicV2::enableGrp0 protected
Definition at line 144 of file gic_v2.hh.
enableGrp1
Bitfield<1> GicV2::enableGrp1 protected
Definition at line 143 of file gic_v2.hh.
gem5ExtensionsEnabled
bool GicV2::gem5ExtensionsEnabled protected
gem5 many-core extension enabled by driver
Definition at line 174 of file gic_v2.hh.
Referenced by getCpuTarget(), GicV2(), readCpu(), sendInt(), serialize(), softInt(), unserialize(), updateIntState(), writeCpu(), and writeDistributor().
GICC_BPR_MINIMUM
const int GicV2::GICC_BPR_MINIMUM = 2 static protected
minimum value for Binary Point Register ("IMPLEMENTATION DEFINED"); chosen for consistency with Linux's in-kernel KVM GIC model
Definition at line 128 of file gic_v2.hh.
Referenced by GicV2(), and writeCpu().
giccIIDR
const uint32_t GicV2::giccIIDR protected
Definition at line 80 of file gic_v2.hh.
Referenced by readCpu().
GICD_ICACTIVER
const AddrRange GicV2::GICD_ICACTIVER static protected
Definition at line 88 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ICENABLER
const AddrRange GicV2::GICD_ICENABLER static protected
Definition at line 84 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ICFGR
const AddrRange GicV2::GICD_ICFGR static protected
Definition at line 91 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ICPENDR
const AddrRange GicV2::GICD_ICPENDR static protected
Definition at line 86 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_IGROUPR
const AddrRange GicV2::GICD_IGROUPR static protected
Definition at line 82 of file gic_v2.hh.
Referenced by readDistributor(), and writeDistributor().
GICD_IPRIORITYR
const AddrRange GicV2::GICD_IPRIORITYR static protected
Definition at line 89 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ISACTIVER
const AddrRange GicV2::GICD_ISACTIVER static protected
Definition at line 87 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ISENABLER
const AddrRange GicV2::GICD_ISENABLER static protected
Definition at line 83 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ISPENDR
const AddrRange GicV2::GICD_ISPENDR static protected
Definition at line 85 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
GICD_ITARGETSR
const AddrRange GicV2::GICD_ITARGETSR static protected
Definition at line 90 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), readDistributor(), and writeDistributor().
gicdIIDR
const uint32_t GicV2::gicdIIDR protected
Definition at line 79 of file gic_v2.hh.
Referenced by readDistributor().
gicdPIDR
const uint32_t GicV2::gicdPIDR protected
Definition at line 78 of file gic_v2.hh.
Referenced by readDistributor().
GLOBAL_INT_LINES
const int GicV2::GLOBAL_INT_LINES = INT_LINES_MAX - SGI_MAX - PPI_MAX static protected
Definition at line 124 of file gic_v2.hh.
Referenced by serialize(), and unserialize().
haveGem5Extensions
const bool GicV2::haveGem5Extensions protected
Are gem5 extensions available?
Definition at line 171 of file gic_v2.hh.
Referenced by GicV2(), readDistributor(), and writeDistributor().
iccrpr
uint32_t GicV2::iccrpr[CPU_MAX] protected
read only running priority register, 1 per cpu
Definition at line 269 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), serialize(), unserialize(), and updateRunPri().
INT_BITS_MAX
const int GicV2::INT_BITS_MAX = 32 static protected
Definition at line 122 of file gic_v2.hh.
Referenced by readDistributor(), serialize(), unserialize(), updateIntState(), and writeDistributor().
INT_LINES_MAX
const int GicV2::INT_LINES_MAX = 1020 static protected
Definition at line 123 of file gic_v2.hh.
Referenced by readDistributor().
intConfig
uint32_t GicV2::intConfig[INT_BITS_MAX *2] protected
2 bit per interrupt signaling if it's level or edge sensitive and if it is 1:N or N:N
Definition at line 326 of file gic_v2.hh.
Referenced by getIntConfig(), GicV2(), readDistributor(), serialize(), unserialize(), and writeDistributor().
intEnabled
uint32_t GicV2::intEnabled[INT_BITS_MAX-1] protected
GICD_I{S,C}ENABLER{1..31} interrupt enable bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
Definition at line 216 of file gic_v2.hh.
Referenced by GicV2(), GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), and unserialize().
intGroup
uint32_t GicV2::intGroup[INT_BITS_MAX-1] protected
GICD_IGROUPR{1..31} interrupt group bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
Definition at line 257 of file gic_v2.hh.
Referenced by GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), and unserialize().
intLatency
const Tick GicV2::intLatency protected
Latency for a interrupt to get to CPU.
Definition at line 164 of file gic_v2.hh.
Referenced by GicV2(), and updateIntState().
intPriority
uint8_t GicV2::intPriority[GLOBAL_INT_LINES] protected
GICD_IPRIORITYR{8..255} an 8 bit priority (lower is higher priority) for each of the global (not replicated per CPU) interrupts.
Definition at line 275 of file gic_v2.hh.
Referenced by GicV2(), GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), and unserialize().
itLines
uint32_t GicV2::itLines protected
Number of itLines enabled.
Definition at line 177 of file gic_v2.hh.
Referenced by MuxingKvmGic::copyGicState(), GicV2(), readDistributor(), serialize(), unserialize(), updateIntState(), and updateRunPri().
list_type
Bitfield<25,24> GicV2::list_type protected
Definition at line 133 of file gic_v2.hh.
NN_CONFIG_MASK
const int GicV2::NN_CONFIG_MASK = 0x55555555 static protected
Mask for bits that config N:N mode in GICD_ICFGR's.
Definition at line 118 of file gic_v2.hh.
Referenced by writeDistributor().
pendingDelayedInterrupts
int GicV2::pendingDelayedInterrupts protected
Definition at line 440 of file gic_v2.hh.
Referenced by drain(), GicV2(), postDelayedFiq(), postDelayedInt(), postFiq(), and postInt().
pendingInt
uint32_t GicV2::pendingInt[INT_BITS_MAX-1] protected
GICD_I{S,C}PENDR{1..31} interrupt pending bits for global interrupts 1b per interrupt, 32 bits per word, 31 words.
Definition at line 229 of file gic_v2.hh.
Referenced by GicV2(), GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), and unserialize().
postFiqEvent
EventFunctionWrapper* GicV2::postFiqEvent[CPU_MAX] protected
Definition at line 439 of file gic_v2.hh.
Referenced by GicV2(), postFiq(), and ~GicV2().
postIntEvent
EventFunctionWrapper* GicV2::postIntEvent[CPU_MAX] protected
Definition at line 438 of file gic_v2.hh.
Referenced by GicV2(), postInt(), unserialize(), and ~GicV2().
PPI_MAX
const int GicV2::PPI_MAX = 16 static protected
Definition at line 112 of file gic_v2.hh.
Referenced by getIntPriority(), readCpu(), sendInt(), GicV2::BankedRegs::serialize(), GicV2::BankedRegs::unserialize(), updateIntState(), updateRunPri(), writeCpu(), and writeDistributor().
sgi_id
GicV2::sgi_id protected
Definition at line 131 of file gic_v2.hh.
SGI_MASK
const int GicV2::SGI_MASK = 0xFFFF0000 static protected
Mask off SGI's when setting/clearing pending bits.
Definition at line 115 of file gic_v2.hh.
Referenced by writeDistributor().
SGI_MAX
const int GicV2::SGI_MAX = 16 static protected
Definition at line 111 of file gic_v2.hh.
Referenced by clearPPInt(), readCpu(), sendInt(), sendPPInt(), GicV2::BankedRegs::serialize(), serialize(), GicV2::BankedRegs::unserialize(), unserialize(), updateIntState(), updateRunPri(), writeCpu(), and writeDistributor().
SPURIOUS_INT
const int GicV2::SPURIOUS_INT = 1023 static protected
Definition at line 121 of file gic_v2.hh.
Referenced by GicV2(), readCpu(), and updateIntState().
The documentation for this class was generated from the following files:
dev/arm/gic_v2.hh
dev/arm/gic_v2.cc