gem5: BasePrefetcher Class Reference
BasePrefetcher Class Reference abstract
#include <base.hh>
Classes
class PrefetchInfo
Class containing the information needed by the prefetch to train and generate new prefetch requests.
class PrefetchListener
Public Member Functions
BasePrefetcher (const BasePrefetcherParams *p)
virtual ~BasePrefetcher ()
virtual void setCache (BaseCache *_cache)
virtual void notify (const PacketPtr &pkt, const PrefetchInfo &pfi)=0
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.)
virtual void notifyFill (const PacketPtr &pkt)
Notify prefetcher of cache fill.
virtual PacketPtr getPacket ()=0
virtual Tick nextPrefetchReadyTime () const =0
void regStats () override
Register local statistics.
void regProbeListeners () override
Register probe points for this object.
void probeNotify (const PacketPtr &pkt, bool miss)
Process a notification event from the ProbeListener.
void addEventProbe (SimObject *obj, const char *name)
Add a SimObject and a probe name to listen events from.
void addTLB (BaseTLB *tlb)
Add a BaseTLB object to be used whenever a translation is needed.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Member Functions
bool observeAccess (const PacketPtr &pkt, bool miss) const
Determine if this access should be observed.
bool inCache (Addr addr, bool is_secure) const
Determine if address is in cache.
bool inMissQueue (Addr addr, bool is_secure) const
Determine if address is in cache miss queue.
bool hasBeenPrefetched (Addr addr, bool is_secure) const
bool samePage (Addr a, Addr b) const
Determine if addresses are on the same page.
Addr blockAddress (Addr a) const
Determine the address of the block in which a lays.
Addr blockIndex (Addr a) const
Determine the address of a at block granularity.
Addr pageAddress (Addr a) const
Determine the address of the page in which a lays.
Addr pageOffset (Addr a) const
Determine the page-offset of a.
Addr pageIthBlockAddress (Addr page, uint32_t i) const
Build the address of the i-th block inside the page.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
BaseCache * cache
Pointr to the parent cache.
unsigned blkSize
The block size of the parent cache.
unsigned lBlkSize
log_2(block size of the parent cache).
const bool onMiss
Only consult prefetcher on cache misses?
const bool onRead
Consult prefetcher on reads?
const bool onWrite
Consult prefetcher on reads?
const bool onData
Consult prefetcher on data accesses?
const bool onInst
Consult prefetcher on instruction accesses?
const MasterID masterId
Request id for prefetches.
const Addr pageBytes
const bool prefetchOnAccess
Prefetch on every access, not just misses.
const bool useVirtualAddresses
Use Virtual Addresses for prefetching.
Stats::Scalar pfIssued
uint64_t issuedPrefetches
Total prefetches issued.
uint64_t usefulPrefetches
Total prefetches that has been useful.
BaseTLB * tlb
Registered tlb for address translations.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
std::vector< PrefetchListener * > listeners
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 67 of file base.hh.
Constructor & Destructor Documentation
BasePrefetcher()
BasePrefetcher::BasePrefetcher (const BasePrefetcherParams * p)
Definition at line 92 of file base.cc.
~BasePrefetcher()
virtual BasePrefetcher::~BasePrefetcher () inline virtual
Definition at line 337 of file base.hh.
References BasePrefetcher::PrefetchListener::notify(), and setCache().
Member Function Documentation
addEventProbe()
void BasePrefetcher::addEventProbe (SimObject * obj, const char * name)
Add a SimObject and a probe name to listen events from.
Parameters
obj The SimObject pointer to listen from
name The probe name
Definition at line 252 of file base.cc.
References SimObject::getProbeManager(), and listeners.
Referenced by notifyFill().
addTLB()
void BasePrefetcher::addTLB (BaseTLB * tlb)
Add a BaseTLB object to be used whenever a translation is needed.
This is generally required when the prefetcher is allowed to generate page crossing references and/or uses virtual addresses for training.
Parameters
tlb pointer to the BaseTLB object to add
Definition at line 259 of file base.cc.
References fatal_if, ArmISA::t, and tlb.
Referenced by notifyFill().
blockAddress()
Addr BasePrefetcher::blockAddress (Addr a) const protected
Determine the address of the block in which a lays.
Definition at line 173 of file base.cc.
References blkSize.
Referenced by TaggedPrefetcher::calculatePrefetch(), and QueuedPrefetcher::notify().
blockIndex()
Addr BasePrefetcher::blockIndex (Addr a) const protected
Determine the address of a at block granularity.
Definition at line 179 of file base.cc.
References lBlkSize.
Referenced by IrregularStreamBufferPrefetcher::calculatePrefetch().
getPacket()
virtual PacketPtr BasePrefetcher::getPacket () pure virtual
Implemented in QueuedPrefetcher, and MultiPrefetcher.
Referenced by BaseCache::getNextQueueEntry(), and notifyFill().
hasBeenPrefetched()
bool BasePrefetcher::hasBeenPrefetched (Addr addr, bool is_secure) const protected
Definition at line 161 of file base.cc.
References cache, and BaseCache::hasBeenPrefetched().
Referenced by probeNotify().
inCache()
bool BasePrefetcher::inCache (Addr addr, bool is_secure) const protected
Determine if address is in cache.
Definition at line 149 of file base.cc.
References cache, and BaseCache::inCache().
Referenced by STeMSPrefetcher::checkForActiveGenerationsEnd(), QueuedPrefetcher::insert(), and QueuedPrefetcher::translationComplete().
inMissQueue()
bool BasePrefetcher::inMissQueue (Addr addr, bool is_secure) const protected
Determine if address is in cache miss queue.
Definition at line 155 of file base.cc.
References cache, and BaseCache::inMissQueue().
Referenced by STeMSPrefetcher::checkForActiveGenerationsEnd(), QueuedPrefetcher::insert(), and QueuedPrefetcher::translationComplete().
nextPrefetchReadyTime()
virtual Tick BasePrefetcher::nextPrefetchReadyTime () const pure virtual
Implemented in QueuedPrefetcher, and MultiPrefetcher.
Referenced by BaseCache::nextQueueReadyTime(), notifyFill(), BaseCache::recvTimingReq(), and BaseCache::recvTimingResp().
notify()
virtual void BasePrefetcher::notify (const PacketPtr & pkt, const PrefetchInfo & pfi) pure virtual
Notify prefetcher of cache access (may be any access or just misses, depending on cache parameters.)
Implemented in QueuedPrefetcher, and MultiPrefetcher.
Referenced by probeNotify().
notifyFill()
virtual void BasePrefetcher::notifyFill (const PacketPtr & pkt) inline virtual
Notify prefetcher of cache fill.
Reimplemented in SBOOEPrefetcher, BOPPrefetcher, and MultiPrefetcher.
Definition at line 348 of file base.hh.
References addEventProbe(), addTLB(), getPacket(), BasePrefetcher::PrefetchListener::miss, ProbeListener::name, nextPrefetchReadyTime(), probeNotify(), regProbeListeners(), and regStats().
observeAccess()
bool BasePrefetcher::observeAccess (const PacketPtr & pkt, bool miss) const protected
Determine if this access should be observed.
Parameters
pkt The memory request causing the event
miss whether this event comes from a cache miss
Definition at line 127 of file base.cc.
References MemCmd::CleanEvict, Packet::cmd, X86ISA::inv, Packet::isInvalidate(), Packet::isRead(), onData, onInst, onMiss, onRead, onWrite, and Packet::req.
Referenced by probeNotify().
pageAddress()
Addr BasePrefetcher::pageAddress (Addr a) const protected
Determine the address of the page in which a lays.
Definition at line 185 of file base.cc.
References pageBytes, and roundDown().
pageIthBlockAddress()
Addr BasePrefetcher::pageIthBlockAddress (Addr page, uint32_t i) const protected
Build the address of the i-th block inside the page.
Definition at line 197 of file base.cc.
References lBlkSize.
pageOffset()
Addr BasePrefetcher::pageOffset (Addr a) const protected
Determine the page-offset of a.
Definition at line 191 of file base.cc.
References pageBytes.
probeNotify()
void BasePrefetcher::probeNotify (const PacketPtr & pkt, bool miss)
Process a notification event from the ProbeListener.
Parameters
pkt The memory request causing the event
miss whether this event comes from a cache miss
Definition at line 203 of file base.cc.
References cache, Packet::cmd, BaseCache::coalesce(), Packet::getAddr(), hasBeenPrefetched(), Packet::isSecure(), MemCmd::isSWPrefetch(), Packet::isWrite(), notify(), observeAccess(), panic, Packet::req, usefulPrefetches, and useVirtualAddresses.
Referenced by notifyFill().
regProbeListeners()
void BasePrefetcher::regProbeListeners () override virtual
Register probe points for this object.
If no probes were added by the configuration scripts, connect to the parent cache using the probe "Miss". Also connect to "Hit", if the cache is configured to prefetch on accesses.
Reimplemented from SimObject.
Definition at line 231 of file base.cc.
References cache, SimObject::getProbeManager(), listeners, and prefetchOnAccess.
Referenced by notifyFill().
regStats()
void BasePrefetcher::regStats () override virtual
Register local statistics.
Reimplemented from Stats::Group.
Reimplemented in QueuedPrefetcher.
Definition at line 115 of file base.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), pfIssued, and Stats::Group::regStats().
Referenced by notifyFill(), and QueuedPrefetcher::regStats().
samePage()
bool BasePrefetcher::samePage (Addr a, Addr b) const protected
Determine if addresses are on the same page.
Definition at line 167 of file base.cc.
References pageBytes, and roundDown().
Referenced by QueuedPrefetcher::insert(), and QueuedPrefetcher::notify().
setCache()
void BasePrefetcher::setCache (BaseCache * _cache) virtual
Reimplemented in MultiPrefetcher.
Definition at line 104 of file base.cc.
References blkSize, cache, floorLog2(), BaseCache::getBlockSize(), and lBlkSize.
Referenced by BaseCache::BaseCache(), and ~BasePrefetcher().
Member Data Documentation
blkSize
unsigned BasePrefetcher::blkSize protected
The block size of the parent cache.
Definition at line 264 of file base.hh.
Referenced by SignaturePathPrefetcher::addPrefetch(), blockAddress(), BOPPrefetcher::BOPPrefetcher(), TaggedPrefetcher::calculatePrefetch(), StridePrefetcher::calculatePrefetch(), STeMSPrefetcher::calculatePrefetch(), SignaturePathPrefetcher::calculatePrefetch(), STeMSPrefetcher::checkForActiveGenerationsEnd(), QueuedPrefetcher::createPrefetchRequest(), QueuedPrefetcher::insert(), setCache(), BOPPrefetcher::tag(), and QueuedPrefetcher::translationComplete().
cache
BaseCache* BasePrefetcher::cache protected
Pointr to the parent cache.
Definition at line 261 of file base.hh.
Referenced by hasBeenPrefetched(), inCache(), inMissQueue(), QueuedPrefetcher::insert(), probeNotify(), regProbeListeners(), and setCache().
issuedPrefetches
uint64_t BasePrefetcher::issuedPrefetches protected
Total prefetches issued.
Definition at line 326 of file base.hh.
Referenced by SignaturePathPrefetcherV2::calculateLookaheadConfidence(), QueuedPrefetcher::getMaxPermittedPrefetches(), and QueuedPrefetcher::getPacket().
lBlkSize
unsigned BasePrefetcher::lBlkSize protected
log_2(block size of the parent cache).
Definition at line 267 of file base.hh.
Referenced by blockIndex(), IrregularStreamBufferPrefetcher::calculatePrefetch(), BOPPrefetcher::calculatePrefetch(), SBOOEPrefetcher::calculatePrefetch(), PIFPrefetcher::calculatePrefetch(), PIFPrefetcher::notifyRetiredInst(), pageIthBlockAddress(), and setCache().
listeners
std::vector<PrefetchListener *> BasePrefetcher::listeners private
Definition at line 84 of file base.hh.
Referenced by addEventProbe(), and regProbeListeners().
masterId
const MasterID BasePrefetcher::masterId protected
Request id for prefetches.
Definition at line 285 of file base.hh.
Referenced by QueuedPrefetcher::createPrefetchRequest(), BasePrefetcher::PrefetchInfo::getMasterId(), QueuedPrefetcher::insert(), and QueuedPrefetcher::translationComplete().
onData
const bool BasePrefetcher::onData protected
Consult prefetcher on data accesses?
Definition at line 279 of file base.hh.
Referenced by observeAccess().
onInst
const bool BasePrefetcher::onInst protected
Consult prefetcher on instruction accesses?
Definition at line 282 of file base.hh.
Referenced by observeAccess().
onMiss
const bool BasePrefetcher::onMiss protected
Only consult prefetcher on cache misses?
Definition at line 270 of file base.hh.
Referenced by observeAccess().
onRead
const bool BasePrefetcher::onRead protected
Consult prefetcher on reads?
Definition at line 273 of file base.hh.
Referenced by observeAccess().
onWrite
const bool BasePrefetcher::onWrite protected
Consult prefetcher on reads?
Definition at line 276 of file base.hh.
Referenced by observeAccess().
pageBytes
const Addr BasePrefetcher::pageBytes protected
Definition at line 287 of file base.hh.
Referenced by SignaturePathPrefetcher::addPrefetch(), SignaturePathPrefetcher::calculatePrefetch(), pageAddress(), pageOffset(), and samePage().
pfIssued
Stats::Scalar BasePrefetcher::pfIssued protected
Definition at line 323 of file base.hh.
Referenced by QueuedPrefetcher::getPacket(), and regStats().
prefetchOnAccess
const bool BasePrefetcher::prefetchOnAccess protected
Prefetch on every access, not just misses.
Definition at line 290 of file base.hh.
Referenced by regProbeListeners().
tlb
BaseTLB* BasePrefetcher::tlb protected
Registered tlb for address translations.
Definition at line 331 of file base.hh.
Referenced by addTLB(), QueuedPrefetcher::DeferredPacket::markDelayed(), QueuedPrefetcher::notify(), QueuedPrefetcher::processMissingTranslations(), and QueuedPrefetcher::translationComplete().
usefulPrefetches
uint64_t BasePrefetcher::usefulPrefetches protected
Total prefetches that has been useful.
Definition at line 328 of file base.hh.
Referenced by SignaturePathPrefetcherV2::calculateLookaheadConfidence(), QueuedPrefetcher::getMaxPermittedPrefetches(), and probeNotify().
useVirtualAddresses
const bool BasePrefetcher::useVirtualAddresses protected
Use Virtual Addresses for prefetching.
Definition at line 293 of file base.hh.
Referenced by QueuedPrefetcher::insert(), and probeNotify().
The documentation for this class was generated from the following files:
mem/cache/prefetch/base.hh
mem/cache/prefetch/base.cc