gem5: Globals Class Reference
Globals Class Reference
Container for serializing global variables (not associated with any serialized object).
Public Member Functions
Globals ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
Tick unserializedCurTick
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Container for serializing global variables (not associated with any serialized object).
Definition at line 83 of file serialize.cc.
Constructor & Destructor Documentation
Globals()
Globals::Globals () inline
Definition at line 86 of file serialize.cc.
References serialize(), and unserialize().
Member Function Documentation
serialize()
void Globals::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 103 of file serialize.cc.
References curTick(), paramOut(), SERIALIZE_CONTAINER, and version_tags.
unserialize()
void Globals::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 110 of file serialize.cc.
References arrayParamIn(), Serializable::currentSection(), CheckpointIn::find(), paramIn(), ArmISA::t, version_tags, and warn.
Member Data Documentation
unserializedCurTick
Tick Globals::unserializedCurTick
Definition at line 92 of file serialize.cc.
Referenced by Serializable::unserializeGlobals().
The documentation for this class was generated from the following file:
sim/serialize.cc