gem5: ComputeUnit::CUExitCallback Class Reference
ComputeUnit::CUExitCallback Class Reference
#include <compute_unit.hh>
Public Member Functions
virtual ~CUExitCallback ()
CUExitCallback (ComputeUnit *_cu)
virtual void process ()
virtual process function that is invoked when the callback queue is executed.
Public Member Functions inherited from Callback
virtual ~Callback ()
virtualize the destructor to make sure that the correct one gets called.
Private Attributes
ComputeUnit * computeUnit
Additional Inherited Members
Protected Member Functions inherited from Callback
virtual void autoDestruct ()
Detailed Description
Definition at line 402 of file compute_unit.hh.
Constructor & Destructor Documentation
~CUExitCallback()
virtual ComputeUnit::CUExitCallback::~CUExitCallback () inline virtual
Definition at line 408 of file compute_unit.hh.
CUExitCallback()
ComputeUnit::CUExitCallback::CUExitCallback (ComputeUnit * _cu) inline
Definition at line 410 of file compute_unit.hh.
References process().
Member Function Documentation
process()
void ComputeUnit::CUExitCallback::process () virtual
virtual process function that is invoked when the callback queue is executed.
Implements Callback.
Definition at line 1713 of file compute_unit.cc.
References OutputDirectory::create(), and simout.
Referenced by CUExitCallback().
Member Data Documentation
computeUnit
ComputeUnit* ComputeUnit::CUExitCallback::computeUnit private
Definition at line 405 of file compute_unit.hh.
The documentation for this class was generated from the following files:
gpu-compute/compute_unit.hh
gpu-compute/compute_unit.cc