gem5: AccessMapPatternMatching Class Reference
AccessMapPatternMatching Class Reference
#include <access_map_pattern_matching.hh>
Classes
struct AccessMapEntry
AccessMapEntry data type.
Public Member Functions
AccessMapPatternMatching (const AccessMapPatternMatchingParams *p)
Copyright (c) 2018 Metempsy Technology Consulting All rights reserved.
~AccessMapPatternMatching ()
void startup () override
startup() is the final initialization call before simulation.
void calculatePrefetch (const BasePrefetcher::PrefetchInfo &pfi, std::vector< QueuedPrefetcher::AddrPriority > &addresses)
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Types
enum AccessMapState { AM_INIT, AM_PREFETCH, AM_ACCESS, AM_INVALID }
Data type representing the state of a cacheline in the access map.
Private Member Functions
bool checkCandidate (std::vector< AccessMapState > const &states, Addr current, int stride) const
Given a target cacheline, this function checks if the cachelines that follow the provided stride have been accessed.
AccessMapEntry * getAccessMapEntry (Addr am_addr, bool is_secure)
Obtain an AccessMapEntry from the AccessMapTable, if the entry is not found a new one is initialized and inserted.
void setEntryState (AccessMapEntry &entry, Addr block, enum AccessMapState state)
Updates the state of a block within an AccessMapEntry, also updates the prefetcher metrics.
void processEpochEvent ()
This event constitues the epoch of the statistics that keep track of the prefetcher accuracy, when this event triggers, the prefetcher degree is adjusted and the statistics counters are reset.
Private Attributes
const unsigned blkSize
Cacheline size used by the prefetcher using this object.
const unsigned limitStride
Limit the stride checking to -limitStride/+limitStride.
const unsigned startDegree
Maximum number of prefetch generated.
const uint64_t hotZoneSize
Amount of memory covered by a hot zone.
const double highCoverageThreshold
A prefetch coverage factor bigger than this is considered high.
const double lowCoverageThreshold
A prefetch coverage factor smaller than this is considered low.
const double highAccuracyThreshold
A prefetch accuracy factor bigger than this is considered high.
const double lowAccuracyThreshold
A prefetch accuracy factor smaller than this is considered low.
const double highCacheHitThreshold
A cache hit ratio bigger than this is considered high.
const double lowCacheHitThreshold
A cache hit ratio smaller than this is considered low.
const Cycles epochCycles
Cycles in an epoch period.
const Tick offChipMemoryLatency
Off chip memory latency to use for the epoch bandwidth calculation.
AssociativeSet< AccessMapEntry > accessMapTable
Access map table.
uint64_t numGoodPrefetches
Number of good prefetches.
uint64_t numTotalPrefetches
Number of prefetches issued.
uint64_t numRawCacheMisses
Number of raw cache misses.
uint64_t numRawCacheHits
Number of raw cache hits.
unsigned degree
Current degree.
unsigned usefulDegree
Current useful degree.
EventFunctionWrapper epochEvent
Additional Inherited Members
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 50 of file access_map_pattern_matching.hh.
Member Enumeration Documentation
AccessMapState
enum AccessMapPatternMatching::AccessMapState private
Data type representing the state of a cacheline in the access map.
Enumerator
AM_INIT
AM_PREFETCH
AM_ACCESS
AM_INVALID
Definition at line 78 of file access_map_pattern_matching.hh.
Constructor & Destructor Documentation
AccessMapPatternMatching()
AccessMapPatternMatching::AccessMapPatternMatching (const AccessMapPatternMatchingParams * p)
Copyright (c) 2018 Metempsy Technology Consulting All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer; redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution; neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Authors: Javier Bueno
Definition at line 38 of file access_map_pattern_matching.cc.
References fatal_if, hotZoneSize, isPowerOf2(), SimObject::name(), and processEpochEvent().
Referenced by calculatePrefetch().
~AccessMapPatternMatching()
AccessMapPatternMatching::~AccessMapPatternMatching () inline
Definition at line 181 of file access_map_pattern_matching.hh.
References calculatePrefetch(), and startup().
Member Function Documentation
calculatePrefetch()
void AccessMapPatternMatching::calculatePrefetch (const BasePrefetcher::PrefetchInfo & pfi, std::vector< QueuedPrefetcher::AddrPriority > & addresses)
Create a contiguous copy of the 3 entries states. With this, we avoid doing boundaries checking in the loop that looks for prefetch candidates, mark out of range positions with AM_INVALID
am_entry_prev->states => states[ 0 .. lines_per_zone-1] am_entry_curr->states => states[ lines_per_zone .. 2*lines_per_zone-1] am_entry_next->states => states[2*lines_per_zone .. 3*lines_per_zone-1]
Definition at line 154 of file access_map_pattern_matching.cc.
References AccessMapPatternMatching(), AM_ACCESS, AM_INVALID, AM_PREFETCH, blkSize, checkCandidate(), degree, getAccessMapEntry(), BasePrefetcher::PrefetchInfo::getAddr(), hotZoneSize, BasePrefetcher::PrefetchInfo::isSecure(), limitStride, MaxAddr, setEntryState(), AccessMapPatternMatching::AccessMapEntry::states, and ArmISA::stride.
Referenced by SlimAMPMPrefetcher::calculatePrefetch(), AMPMPrefetcher::calculatePrefetch(), ~AccessMapPatternMatching(), and AMPMPrefetcher::~AMPMPrefetcher().
checkCandidate()
bool AccessMapPatternMatching::checkCandidate (std::vector< AccessMapState > const & states, Addr current, int stride) const inline private
Given a target cacheline, this function checks if the cachelines that follow the provided stride have been accessed.
If so, the line is considered a good candidate.
Parameters
states vector containing the states of three contiguous hot zones
current target block (cacheline)
stride access stride to obtain the reference cachelines
Returns
true if current is a prefetch candidate
Definition at line 140 of file access_map_pattern_matching.hh.
References AM_ACCESS, AM_INVALID, getAccessMapEntry(), processEpochEvent(), ArmISA::s, setEntryState(), and ArmISA::stride.
Referenced by calculatePrefetch().
getAccessMapEntry()
AccessMapPatternMatching::AccessMapEntry * AccessMapPatternMatching::getAccessMapEntry (Addr am_addr, bool is_secure) private
Obtain an AccessMapEntry from the AccessMapTable, if the entry is not found a new one is initialized and inserted.
Parameters
am_addr address of the hot zone
is_secure whether the address belongs to the secure memory area
Returns
the corresponding entry
Definition at line 103 of file access_map_pattern_matching.cc.
References accessMapTable.
Referenced by calculatePrefetch(), and checkCandidate().
processEpochEvent()
void AccessMapPatternMatching::processEpochEvent () private
This event constitues the epoch of the statistics that keep track of the prefetcher accuracy, when this event triggers, the prefetcher degree is adjusted and the statistics counters are reset.
Definition at line 69 of file access_map_pattern_matching.cc.
References Clocked::clockEdge(), degree, epochCycles, epochEvent, highAccuracyThreshold, highCacheHitThreshold, highCoverageThreshold, lowAccuracyThreshold, lowCacheHitThreshold, lowCoverageThreshold, numGoodPrefetches, numRawCacheHits, numRawCacheMisses, numTotalPrefetches, offChipMemoryLatency, EventManager::schedule(), and usefulDegree.
Referenced by AccessMapPatternMatching(), and checkCandidate().
setEntryState()
void AccessMapPatternMatching::setEntryState (AccessMapEntry & entry, Addr block, enum AccessMapState state) private
Updates the state of a block within an AccessMapEntry, also updates the prefetcher metrics.
Parameters
entry AccessMapEntry to update
block cacheline within the hot zone
state new state
Definition at line 119 of file access_map_pattern_matching.cc.
References AM_ACCESS, AM_INIT, AM_PREFETCH, numGoodPrefetches, numRawCacheHits, numRawCacheMisses, numTotalPrefetches, panic, and AccessMapPatternMatching::AccessMapEntry::states.
Referenced by calculatePrefetch(), and checkCandidate().
startup()
void AccessMapPatternMatching::startup () override virtual
startup() is the final initialization call before simulation.
All state is initialized (including unserialized state, if any, such as the curTick() value), so this is the appropriate place to schedule initial event(s) for objects that need them.
Reimplemented from SimObject.
Definition at line 63 of file access_map_pattern_matching.cc.
References Clocked::clockEdge(), epochCycles, epochEvent, and EventManager::schedule().
Referenced by ~AccessMapPatternMatching().
Member Data Documentation
accessMapTable
AssociativeSet<AccessMapEntry> AccessMapPatternMatching::accessMapTable private
Access map table.
Definition at line 104 of file access_map_pattern_matching.hh.
Referenced by getAccessMapEntry().
blkSize
const unsigned AccessMapPatternMatching::blkSize private
Cacheline size used by the prefetcher using this object.
Definition at line 53 of file access_map_pattern_matching.hh.
Referenced by calculatePrefetch().
degree
unsigned AccessMapPatternMatching::degree private
Current degree.
Definition at line 127 of file access_map_pattern_matching.hh.
Referenced by calculatePrefetch(), and processEpochEvent().
epochCycles
const Cycles AccessMapPatternMatching::epochCycles private
Cycles in an epoch period.
Definition at line 73 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and startup().
epochEvent
EventFunctionWrapper AccessMapPatternMatching::epochEvent private
Definition at line 177 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and startup().
highAccuracyThreshold
const double AccessMapPatternMatching::highAccuracyThreshold private
A prefetch accuracy factor bigger than this is considered high.
Definition at line 65 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
highCacheHitThreshold
const double AccessMapPatternMatching::highCacheHitThreshold private
A cache hit ratio bigger than this is considered high.
Definition at line 69 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
highCoverageThreshold
const double AccessMapPatternMatching::highCoverageThreshold private
A prefetch coverage factor bigger than this is considered high.
Definition at line 61 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
hotZoneSize
const uint64_t AccessMapPatternMatching::hotZoneSize private
Amount of memory covered by a hot zone.
Definition at line 59 of file access_map_pattern_matching.hh.
Referenced by AccessMapPatternMatching(), and calculatePrefetch().
limitStride
const unsigned AccessMapPatternMatching::limitStride private
Limit the stride checking to -limitStride/+limitStride.
Definition at line 55 of file access_map_pattern_matching.hh.
Referenced by calculatePrefetch().
lowAccuracyThreshold
const double AccessMapPatternMatching::lowAccuracyThreshold private
A prefetch accuracy factor smaller than this is considered low.
Definition at line 67 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
lowCacheHitThreshold
const double AccessMapPatternMatching::lowCacheHitThreshold private
A cache hit ratio smaller than this is considered low.
Definition at line 71 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
lowCoverageThreshold
const double AccessMapPatternMatching::lowCoverageThreshold private
A prefetch coverage factor smaller than this is considered low.
Definition at line 63 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
numGoodPrefetches
uint64_t AccessMapPatternMatching::numGoodPrefetches private
Number of good prefetches.
State transitions from PREFETCH to ACCESS
Definition at line 110 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and setEntryState().
numRawCacheHits
uint64_t AccessMapPatternMatching::numRawCacheHits private
Number of raw cache hits.
State transitions from ACCESS to ACCESS
Definition at line 125 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and setEntryState().
numRawCacheMisses
uint64_t AccessMapPatternMatching::numRawCacheMisses private
Number of raw cache misses.
State transitions from INIT or PREFETCH to ACCESS
Definition at line 120 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and setEntryState().
numTotalPrefetches
uint64_t AccessMapPatternMatching::numTotalPrefetches private
Number of prefetches issued.
State transitions from INIT to PREFETCH
Definition at line 115 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent(), and setEntryState().
offChipMemoryLatency
const Tick AccessMapPatternMatching::offChipMemoryLatency private
Off chip memory latency to use for the epoch bandwidth calculation.
Definition at line 75 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
startDegree
const unsigned AccessMapPatternMatching::startDegree private
Maximum number of prefetch generated.
Definition at line 57 of file access_map_pattern_matching.hh.
usefulDegree
unsigned AccessMapPatternMatching::usefulDegree private
Current useful degree.
Definition at line 129 of file access_map_pattern_matching.hh.
Referenced by processEpochEvent().
The documentation for this class was generated from the following files:
mem/cache/prefetch/access_map_pattern_matching.hh
mem/cache/prefetch/access_map_pattern_matching.cc