gem5: BaseDynInst< Impl > Class Template Reference
BaseDynInst< Impl > Class Template Reference
#include <base_dyn_inst.hh>
Public Types
enum { MaxInstSrcRegs = TheISA::MaxInstSrcRegs, MaxInstDestRegs = TheISA::MaxInstDestRegs }
typedef Impl::CPUType ImplCPU
typedef ImplCPU::ImplState ImplState
using VecRegContainer = TheISA::VecRegContainer
using LSQRequestPtr = typename Impl::CPUPol::LSQ::LSQRequest *
using LQIterator = typename Impl::CPUPol::LSQUnit::LQIterator
using SQIterator = typename Impl::CPUPol::LSQUnit::SQIterator
typedef Impl::DynInstPtr DynInstPtr
typedef RefCountingPtr< BaseDynInst< Impl > > BaseDynInstPtr
typedef std::list< DynInstPtr >::iterator ListIt
Public Types inherited from ExecContext
typedef TheISA::PCState PCState
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Public Member Functions
BaseCPU * getCpuPtr ()
void recordResult (bool f)
Records changes to result?
bool effAddrValid () const
Is the effective virtual address valid.
void effAddrValid (bool b)
bool memOpDone () const
Whether or not the memory operation is done.
void memOpDone (bool f)
bool notAnInst () const
void setNotAnInst ()
void demapPage (Addr vaddr, uint64_t asn)
Invalidate a page in the DTLB and ITLB.
void demapInstPage (Addr vaddr, uint64_t asn)
void demapDataPage (Addr vaddr, uint64_t asn)
Fault initiateMemRead (Addr addr, unsigned size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Fault writeMem (uint8_t *data, unsigned size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >())
Fault initiateMemAMO (Addr addr, unsigned size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
bool translationStarted () const
True if the DTB address translation has started.
void translationStarted (bool f)
bool translationCompleted () const
True if the DTB address translation has completed.
void translationCompleted (bool f)
bool possibleLoadViolation () const
True if this address was found to match a previous load and they issued out of order.
void possibleLoadViolation (bool f)
bool hitExternalSnoop () const
True if the address hit a external snoop while sitting in the LSQ.
void hitExternalSnoop (bool f)
bool isTranslationDelayed () const
Returns true if the DTB address translation is being delayed due to a hw page table walk.
PhysRegIdPtr renamedDestRegIdx (int idx) const
Returns the physical register index of the i'th destination register.
PhysRegIdPtr renamedSrcRegIdx (int idx) const
Returns the physical register index of the i'th source register.
const RegId & flattenedDestRegIdx (int idx) const
Returns the flattened register index of the i'th destination register.
PhysRegIdPtr prevDestRegIdx (int idx) const
Returns the physical register index of the previous physical register that remapped to the same logical register index.
void renameDestReg (int idx, PhysRegIdPtr renamed_dest, PhysRegIdPtr previous_rename)
Renames a destination register to a physical register.
void renameSrcReg (int idx, PhysRegIdPtr renamed_src)
Renames a source logical register to the physical register which has/will produce that logical register's result.
void flattenDestReg (int idx, const RegId &flattened_dest)
Flattens a destination architectural register index into a logical index.
BaseDynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, ImplCPU *cpu)
BaseDynInst constructor given a binary instruction.
BaseDynInst (const StaticInstPtr &staticInst, const StaticInstPtr &macroop)
BaseDynInst constructor given a StaticInst pointer.
~BaseDynInst ()
BaseDynInst destructor.
void dump ()
Dumps out contents of this BaseDynInst.
void dump (std::string &outstring)
Dumps out contents of this BaseDynInst into given string.
int cpuId () const
Read this CPU's ID.
uint32_t socketId () const
Read this CPU's Socket ID.
MasterID masterId () const
Read this CPU's data requestor ID.
ContextID contextId () const
Read this context's system-wide ID.
Fault getFault () const
Returns the fault type.
Fault & getFault ()
TODO: This I added for the LSQRequest side to be able to modify the fault.
bool doneTargCalc ()
Checks whether or not this instruction has had its branch target calculated yet.
void setPredTarg (const TheISA::PCState &_predPC)
Set the predicted target of this current instruction.
const TheISA::PCState & readPredTarg ()
Addr predInstAddr ()
Returns the predicted PC immediately after the branch.
Addr predNextInstAddr ()
Returns the predicted PC two instructions after the branch.
Addr predMicroPC ()
Returns the predicted micro PC after the branch.
bool readPredTaken ()
Returns whether the instruction was predicted taken or not.
void setPredTaken (bool predicted_taken)
bool mispredicted ()
Returns whether the instruction mispredicted.
bool isNop () const
bool isMemRef () const
bool isLoad () const
bool isStore () const
bool isAtomic () const
bool isStoreConditional () const
bool isInstPrefetch () const
bool isDataPrefetch () const
bool isInteger () const
bool isFloating () const
bool isVector () const
bool isControl () const
bool isCall () const
bool isReturn () const
bool isDirectCtrl () const
bool isIndirectCtrl () const
bool isCondCtrl () const
bool isUncondCtrl () const
bool isCondDelaySlot () const
bool isThreadSync () const
bool isSerializing () const
bool isSerializeBefore () const
bool isSerializeAfter () const
bool isSquashAfter () const
bool isMemBarrier () const
bool isWriteBarrier () const
bool isNonSpeculative () const
bool isQuiesce () const
bool isIprAccess () const
bool isUnverifiable () const
bool isSyscall () const
bool isMacroop () const
bool isMicroop () const
bool isDelayedCommit () const
bool isLastMicroop () const
bool isFirstMicroop () const
bool isMicroBranch () const
void setSerializeBefore ()
Temporarily sets this instruction as a serialize before instruction.
void clearSerializeBefore ()
Clears the serializeBefore part of this instruction.
bool isTempSerializeBefore ()
Checks if this serializeBefore is only temporarily set.
void setSerializeAfter ()
Temporarily sets this instruction as a serialize after instruction.
void clearSerializeAfter ()
Clears the serializeAfter part of this instruction.
bool isTempSerializeAfter ()
Checks if this serializeAfter is only temporarily set.
void setSerializeHandled ()
Sets the serialization part of this instruction as handled.
bool isSerializeHandled ()
Checks if the serialization part of this instruction has been handled.
OpClass opClass () const
Returns the opclass of this instruction.
TheISA::PCState branchTarget () const
Returns the branch target address.
int8_t numSrcRegs () const
Returns the number of source registers.
int8_t numDestRegs () const
Returns the number of destination registers.
int8_t numFPDestRegs () const
int8_t numIntDestRegs () const
int8_t numCCDestRegs () const
int8_t numVecDestRegs () const
int8_t numVecElemDestRegs () const
int8_t numVecPredDestRegs () const
const RegId & destRegIdx (int i) const
Returns the logical register index of the i'th destination register.
const RegId & srcRegIdx (int i) const
Returns the logical register index of the i'th source register.
uint8_t resultSize ()
Return the size of the instResult queue.
InstResult popResult (InstResult dflt=InstResult())
Pops a result off the instResult queue.
void setIntRegOperand (const StaticInst *si, int idx, RegVal val)
Records an integer register being set to a value.
void setCCRegOperand (const StaticInst *si, int idx, RegVal val)
Records a CC register being set to a value.
void setVecRegOperand (const StaticInst *si, int idx, const VecRegContainer &val)
Record a vector register being set to a value.
void setFloatRegOperandBits (const StaticInst *si, int idx, RegVal val)
Records an fp register being set to an integer value.
void setVecElemOperand (const StaticInst *si, int idx, const VecElem val)
Record a vector register being set to a value.
void setVecPredRegOperand (const StaticInst *si, int idx, const VecPredRegContainer &val)
Record a vector register being set to a value.
void markSrcRegReady ()
Records that one of the source registers is ready.
void markSrcRegReady (RegIndex src_idx)
Marks a specific register as ready.
bool isReadySrcRegIdx (int idx) const
Returns if a source register is ready.
void setCompleted ()
Sets this instruction as completed.
bool isCompleted () const
Returns whether or not this instruction is completed.
void setResultReady ()
Marks the result as ready.
bool isResultReady () const
Returns whether or not the result is ready.
void setCanIssue ()
Sets this instruction as ready to issue.
bool readyToIssue () const
Returns whether or not this instruction is ready to issue.
void clearCanIssue ()
Clears this instruction being able to issue.
void setIssued ()
Sets this instruction as issued from the IQ.
bool isIssued () const
Returns whether or not this instruction has issued.
void clearIssued ()
Clears this instruction as being issued.
void setExecuted ()
Sets this instruction as executed.
bool isExecuted () const
Returns whether or not this instruction has executed.
void setCanCommit ()
Sets this instruction as ready to commit.
void clearCanCommit ()
Clears this instruction as being ready to commit.
bool readyToCommit () const
Returns whether or not this instruction is ready to commit.
void setAtCommit ()
bool isAtCommit ()
void setCommitted ()
Sets this instruction as committed.
bool isCommitted () const
Returns whether or not this instruction is committed.
void setSquashed ()
Sets this instruction as squashed.
bool isSquashed () const
Returns whether or not this instruction is squashed.
void setInIQ ()
Sets this instruction as a entry the IQ.
void clearInIQ ()
Sets this instruction as a entry the IQ.
bool isInIQ () const
Returns whether or not this instruction has issued.
void setSquashedInIQ ()
Sets this instruction as squashed in the IQ.
bool isSquashedInIQ () const
Returns whether or not this instruction is squashed in the IQ.
void setInLSQ ()
Sets this instruction as a entry the LSQ.
void removeInLSQ ()
Sets this instruction as a entry the LSQ.
bool isInLSQ () const
Returns whether or not this instruction is in the LSQ.
void setSquashedInLSQ ()
Sets this instruction as squashed in the LSQ.
bool isSquashedInLSQ () const
Returns whether or not this instruction is squashed in the LSQ.
void setInROB ()
Sets this instruction as a entry the ROB.
void clearInROB ()
Sets this instruction as a entry the ROB.
bool isInROB () const
Returns whether or not this instruction is in the ROB.
void setSquashedInROB ()
Sets this instruction as squashed in the ROB.
bool isSquashedInROB () const
Returns whether or not this instruction is squashed in the ROB.
bool isPinnedRegsRenamed () const
Returns whether pinned registers are renamed.
void setPinnedRegsRenamed ()
Sets the destination registers as renamed.
bool isPinnedRegsWritten () const
Returns whether destination registers are written.
void setPinnedRegsWritten ()
Sets destination registers as written.
bool isPinnedRegsSquashDone () const
Return whether dest registers' pinning status updated after squash.
void setPinnedRegsSquashDone ()
Sets dest registers' status updated after squash.
TheISA::PCState pcState () const
Read the PC state of this instruction.
void pcState (const TheISA::PCState &val)
Set the PC state of this instruction.
Addr instAddr () const
Read the PC of this instruction.
Addr nextInstAddr () const
Read the PC of the next instruction.
Addr microPC () const
Read the micro PC of this instruction.
bool readPredicate () const
void setPredicate (bool val)
bool readMemAccPredicate () const
void setMemAccPredicate (bool val)
void setASID (short addr_space_id)
Sets the ASID.
short getASID ()
void setTid (ThreadID tid)
Sets the thread id.
void setThreadState (ImplState *state)
Sets the pointer to the thread state.
ThreadContext * tcBase ()
Returns the thread context.
bool eaSrcsReady () const
Returns whether or not the eff.
bool strictlyOrdered () const
Is this instruction's memory access strictly ordered?
void strictlyOrdered (bool so)
bool hasRequest () const
Has this instruction generated a memory request.
void setRequest ()
Assert this instruction has generated a memory request.
ListIt & getInstListIt ()
Returns iterator to this instruction in the list of all insts.
void setInstListIt (ListIt _instListIt)
Sets iterator for this instruction in the list of all insts.
unsigned int readStCondFailures () const
Returns the number of consecutive store conditional failures.
void setStCondFailures (unsigned int sc_failures)
Sets the number of consecutive store conditional failures.
void armMonitor (Addr address)
bool mwait (PacketPtr pkt)
void mwaitAtomic (ThreadContext *tc)
AddressMonitor * getAddrMonitor ()
template<typename T >
void setScalarResult (T &&t)
Pushes a result onto the instResult queue.
template<typename T >
void setVecResult (T &&t)
Full vector result.
template<typename T >
void setVecElemResult (T &&t)
Vector element result.
template<typename T >
void setVecPredResult (T &&t)
Predicate result.
Public Member Functions inherited from ExecContext
virtual RegVal readIntRegOperand (const StaticInst *si, int idx)=0
Reads an integer register.
virtual RegVal readFloatRegOperandBits (const StaticInst *si, int idx)=0
Reads a floating point register in its binary format, instead of by value.
virtual const VecRegContainer & readVecRegOperand (const StaticInst *si, int idx) const =0
Vector Register Interfaces.
virtual VecRegContainer & getWritableVecRegOperand (const StaticInst *si, int idx)=0
Gets destination vector register operand for modification.
virtual ConstVecLane8 readVec8BitLaneOperand (const StaticInst *si, int idx) const =0
Vector Register Lane Interfaces.
virtual ConstVecLane16 readVec16BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 16bit operand.
virtual ConstVecLane32 readVec32BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 32bit operand.
virtual ConstVecLane64 readVec64BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 64bit operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::Byte > &val)=0
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::TwoByte > &val)=0
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::FourByte > &val)=0
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::EightByte > &val)=0
virtual VecElem readVecElemOperand (const StaticInst *si, int idx) const =0
Vector Elem Interfaces.
virtual const VecPredRegContainer & readVecPredRegOperand (const StaticInst *si, int idx) const =0
Predicate registers interface.
virtual VecPredRegContainer & getWritableVecPredRegOperand (const StaticInst *si, int idx)=0
Gets destination predicate register operand for modification.
virtual RegVal readCCRegOperand (const StaticInst *si, int idx)=0
virtual RegVal readMiscRegOperand (const StaticInst *si, int idx)=0
virtual void setMiscRegOperand (const StaticInst *si, int idx, RegVal val)=0
virtual RegVal readMiscReg (int misc_reg)=0
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
virtual void setMiscReg (int misc_reg, RegVal val)=0
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
virtual Fault readMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Perform an atomic memory read operation.
virtual Fault initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Initiate a timing memory read operation.
virtual Fault writeMem (uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >())=0
For atomic-mode contexts, perform an atomic memory write operation.
virtual Fault amoMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
virtual Fault initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
virtual void syscall (int64_t callnum, Fault *fault)=0
Executes a syscall specified by the callnum.
Public Member Functions inherited from RefCounted
RefCounted ()
We initialize the reference count to zero and the first object to take ownership of it must increment it to one.
virtual ~RefCounted ()
We make the destructor virtual because we're likely to have virtual functions on reference counted objects.
void incref () const
Increment the reference count.
void decref () const
Decrement the reference count and destroy the object if all references are gone.
Public Attributes
InstSeqNum seqNum
The sequence number of the instruction.
const StaticInstPtr staticInst
The StaticInst used by this BaseDynInst.
ImplCPU * cpu
Pointer to the Impl's CPU object.
ImplState * thread
Pointer to the thread state.
Fault fault
The kind of fault this instruction has generated.
Trace::InstRecord * traceData
InstRecord that tracks this instructions.
ThreadID threadNumber
The thread this instruction is from.
ListIt instListIt
Iterator pointing to this BaseDynInst in the list of all insts.
TheISA::PCState predPC
Predicted PC state after this instruction.
const StaticInstPtr macroop
The Macroop if one exists.
uint8_t readyRegs
How many source registers are ready.
Addr effAddr
The effective virtual address (lds & stores only).
Addr physEffAddr
The effective physical address.
unsigned memReqFlags
The memory request flags (from translation).
short asid
data address space ID, for loads & stores.
unsigned effSize
The size of the request.
uint8_t * memData
Pointer to the data for the memory access.
int16_t lqIdx
Load queue index.
LQIterator lqIt
int16_t sqIdx
Store queue index.
SQIterator sqIt
LSQRequestPtr savedReq
Saved memory request (needed when the DTB address translation is delayed due to a hw page table walk).
RequestPtr reqToVerify
Protected Types
enum Status {
IqEntry, RobEntry, LsqEntry, Completed,
ResultReady, CanIssue, Issued, Executed,
CanCommit, AtCommit, Committed, Squashed,
SquashedInIQ, SquashedInLSQ, SquashedInROB, PinnedRegsRenamed,
PinnedRegsWritten, PinnedRegsSquashDone, RecoverInst, BlockingInst,
ThreadsyncWait, SerializeBefore, SerializeAfter, SerializeHandled,
NumStatus
}
enum Flags {
NotAnInst, TranslationStarted, TranslationCompleted, PossibleLoadViolation,
HitExternalSnoop, EffAddrValid, RecordResult, Predicate,
MemAccPredicate, PredTaken, IsStrictlyOrdered, ReqMade,
MemOpDone, MaxFlags
}
Protected Attributes
std::queue< InstResult > instResult
The result of the instruction; assumes an instruction can have many destination registers.
TheISA::PCState pc
PC state for this instruction.
std::bitset< MaxInstSrcRegs > _readySrcRegIdx
Whether or not the source register is ready.
std::array< RegId, TheISA::MaxInstDestRegs > _flatDestRegIdx
Flattened register index of the destination registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstDestRegs > _destRegIdx
Physical register index of the destination registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstSrcRegs > _srcRegIdx
Physical register index of the source registers of this instruction.
std::array< PhysRegIdPtr, TheISA::MaxInstDestRegs > _prevDestRegIdx
Physical register index of the previous producers of the architected destinations.
Private Member Functions
void initVars ()
Function to initialize variables in the constructors.
Private Attributes
std::bitset< MaxFlags > instFlags
std::bitset< NumStatus > status
The status of this BaseDynInst.
Detailed Description
template<class Impl>
class BaseDynInst< Impl >
Definition at line 78 of file base_dyn_inst.hh.
Member Typedef Documentation
BaseDynInstPtr
template<class Impl > typedef RefCountingPtr<BaseDynInst<Impl> > BaseDynInst< Impl >::BaseDynInstPtr
Definition at line 92 of file base_dyn_inst.hh.
DynInstPtr
template<class Impl > typedef Impl::DynInstPtr BaseDynInst< Impl >::DynInstPtr
Definition at line 91 of file base_dyn_inst.hh.
ImplCPU
template<class Impl > typedef Impl::CPUType BaseDynInst< Impl >::ImplCPU
Definition at line 82 of file base_dyn_inst.hh.
ImplState
template<class Impl > typedef ImplCPU::ImplState BaseDynInst< Impl >::ImplState
Definition at line 83 of file base_dyn_inst.hh.
ListIt
template<class Impl > typedef std::list<DynInstPtr>::iterator BaseDynInst< Impl >::ListIt
Definition at line 95 of file base_dyn_inst.hh.
LQIterator
template<class Impl > using BaseDynInst< Impl >::LQIterator = typename Impl::CPUPol::LSQUnit::LQIterator
Definition at line 87 of file base_dyn_inst.hh.
LSQRequestPtr
template<class Impl > using BaseDynInst< Impl >::LSQRequestPtr = typename Impl::CPUPol::LSQ::LSQRequest*
Definition at line 86 of file base_dyn_inst.hh.
SQIterator
template<class Impl > using BaseDynInst< Impl >::SQIterator = typename Impl::CPUPol::LSQUnit::SQIterator
Definition at line 88 of file base_dyn_inst.hh.
VecRegContainer
template<class Impl > using BaseDynInst< Impl >::VecRegContainer = TheISA::VecRegContainer
Definition at line 84 of file base_dyn_inst.hh.
Member Enumeration Documentation
anonymous enum
template<class Impl > anonymous enum
Enumerator
MaxInstSrcRegs
MaxInstDestRegs
Max source regs.
Definition at line 97 of file base_dyn_inst.hh.
Flags
template<class Impl > enum BaseDynInst::Flags protected
Enumerator
NotAnInst
TranslationStarted
TranslationCompleted
PossibleLoadViolation
HitExternalSnoop
EffAddrValid
RecordResult
Predicate
MemAccPredicate
PredTaken
IsStrictlyOrdered
ReqMade
MemOpDone
MaxFlags
Definition at line 132 of file base_dyn_inst.hh.
Status
template<class Impl > enum BaseDynInst::Status protected
Enumerator
IqEntry
RobEntry
Instruction is in the IQ.
LsqEntry
Instruction is in the ROB.
Completed
Instruction is in the LSQ.
ResultReady
Instruction has completed.
CanIssue
Instruction has its result.
Issued
Instruction can issue and execute.
Executed
Instruction has issued.
CanCommit
Instruction has executed.
AtCommit
Instruction can commit.
Committed
Instruction has reached commit.
Squashed
Instruction has committed.
SquashedInIQ
Instruction is squashed.
SquashedInLSQ
Instruction is squashed in the IQ.
SquashedInROB
Instruction is squashed in the LSQ.
PinnedRegsRenamed
Instruction is squashed in the ROB.
PinnedRegsWritten
Pinned registers are renamed.
PinnedRegsSquashDone
Pinned registers are written back.
RecoverInst
Regs pinning status updated after squash.
BlockingInst
Is a recover instruction.
ThreadsyncWait
Is a blocking instruction.
SerializeBefore
Is a thread synchronization instruction.
SerializeAfter
Needs to serialize on instructions ahead of it.
SerializeHandled
Needs to serialize instructions behind it.
NumStatus
Serialization has been handled.
Definition at line 103 of file base_dyn_inst.hh.
Constructor & Destructor Documentation
BaseDynInst() [1/2]
template<class Impl > BaseDynInst< Impl >::BaseDynInst (const StaticInstPtr & staticInst, const StaticInstPtr & macroop, TheISA::PCState pc, TheISA::PCState predPC, InstSeqNum seq_num, ImplCPU * cpu)
BaseDynInst constructor given a binary instruction.
Parameters
staticInst A StaticInstPtr to the underlying instruction.
pc The PC state for the instruction.
predPC The predicted next PC state for the instruction.
seq_num The sequence number of the instruction.
cpu Pointer to the instruction's CPU.
Definition at line 62 of file base_dyn_inst_impl.hh.
References BaseDynInst< Impl >::initVars(), BaseDynInst< Impl >::pc, BaseDynInst< Impl >::predPC, and BaseDynInst< Impl >::seqNum.
Referenced by BaseDynInst< Impl >::flattenDestReg().
BaseDynInst() [2/2]
template<class Impl > BaseDynInst< Impl >::BaseDynInst (const StaticInstPtr & staticInst, const StaticInstPtr & macroop)
BaseDynInst constructor given a StaticInst pointer.
Parameters
_staticInst The StaticInst for this BaseDynInst.
Definition at line 83 of file base_dyn_inst_impl.hh.
References BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::seqNum.
~BaseDynInst()
template<class Impl > BaseDynInst< Impl >::~BaseDynInst ()
BaseDynInst destructor.
Definition at line 143 of file base_dyn_inst_impl.hh.
References RefCounted::count, cprintf(), BaseDynInst< Impl >::cpu, DPRINTF, BaseDynInst< Impl >::fault, BaseDynInst< Impl >::memData, NoFault, BaseDynInst< Impl >::seqNum, and BaseDynInst< Impl >::traceData.
Referenced by BaseDynInst< Impl >::flattenDestReg().
Member Function Documentation
armMonitor()
template<class Impl > void BaseDynInst< Impl >::armMonitor (Addr address) inline virtual
Implements ExecContext.
Definition at line 954 of file base_dyn_inst.hh.
branchTarget()
template<class Impl > TheISA::PCState BaseDynInst< Impl >::branchTarget () const inline
Returns the branch target address.
Definition at line 580 of file base_dyn_inst.hh.
References StaticInst::branchTarget().
clearCanCommit()
template<class Impl > void BaseDynInst< Impl >::clearCanCommit () inline
Clears this instruction as being ready to commit.
Definition at line 761 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanCommit.
clearCanIssue()
template<class Impl > void BaseDynInst< Impl >::clearCanIssue () inline
Clears this instruction being able to issue.
Definition at line 740 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanIssue.
clearInIQ()
template<class Impl > void BaseDynInst< Impl >::clearInIQ () inline
Sets this instruction as a entry the IQ.
Definition at line 788 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::IqEntry.
clearInROB()
template<class Impl > void BaseDynInst< Impl >::clearInROB () inline
Sets this instruction as a entry the ROB.
Definition at line 824 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RobEntry.
clearIssued()
template<class Impl > void BaseDynInst< Impl >::clearIssued () inline
Clears this instruction as being issued.
Definition at line 749 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Issued.
clearSerializeAfter()
template<class Impl > void BaseDynInst< Impl >::clearSerializeAfter () inline
Clears the serializeAfter part of this instruction.
Definition at line 561 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeAfter.
clearSerializeBefore()
template<class Impl > void BaseDynInst< Impl >::clearSerializeBefore () inline
Clears the serializeBefore part of this instruction.
Definition at line 552 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeBefore.
contextId()
template<class Impl > ContextID BaseDynInst< Impl >::contextId () const inline
Read this context's system-wide ID.
Definition at line 453 of file base_dyn_inst.hh.
cpuId()
template<class Impl > int BaseDynInst< Impl >::cpuId () const inline
Read this CPU's ID.
Definition at line 444 of file base_dyn_inst.hh.
demapDataPage()
template<class Impl > void BaseDynInst< Impl >::demapDataPage (Addr vaddr, uint64_t asn) inline
Definition at line 301 of file base_dyn_inst.hh.
References addr, data, BaseDynInst< Impl >::initiateMemAMO(), BaseDynInst< Impl >::initiateMemRead(), and BaseDynInst< Impl >::writeMem().
demapInstPage()
template<class Impl > void BaseDynInst< Impl >::demapInstPage (Addr vaddr, uint64_t asn) inline
Definition at line 297 of file base_dyn_inst.hh.
demapPage()
template<class Impl > void BaseDynInst< Impl >::demapPage (Addr vaddr, uint64_t asn) inline virtual
Invalidate a page in the DTLB and ITLB.
Implements ExecContext.
Definition at line 293 of file base_dyn_inst.hh.
destRegIdx()
template<class Impl > const RegId& BaseDynInst< Impl >::destRegIdx (int i) const inline
Returns the logical register index of the i'th destination register.
Definition at line 606 of file base_dyn_inst.hh.
References StaticInst::destRegIdx().
doneTargCalc()
template<class Impl > bool BaseDynInst< Impl >::doneTargCalc () inline
Checks whether or not this instruction has had its branch target calculated yet.
For now it is not utilized and is hacked to be always false.
Todo:
: Actually use this instruction.
Definition at line 466 of file base_dyn_inst.hh.
dump() [1/2]
template<class Impl > void BaseDynInst< Impl >::dump ()
Dumps out contents of this BaseDynInst.
Definition at line 186 of file base_dyn_inst_impl.hh.
References cprintf(), StaticInst::disassemble(), BaseDynInst< Impl >::pc, BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::threadNumber.
Referenced by BaseDynInst< Impl >::flattenDestReg().
dump() [2/2]
template<class Impl > void BaseDynInst< Impl >::dump (std::string & outstring)
Dumps out contents of this BaseDynInst into given string.
Definition at line 195 of file base_dyn_inst_impl.hh.
References StaticInst::disassemble(), BaseDynInst< Impl >::pc, ArmISA::s, BaseDynInst< Impl >::staticInst, and BaseDynInst< Impl >::threadNumber.
eaSrcsReady()
template<class Impl > bool BaseDynInst< Impl >::eaSrcsReady () const
Returns whether or not the eff.
addr. source registers are ready.
Definition at line 226 of file base_dyn_inst_impl.hh.
References BaseDynInst< Impl >::_readySrcRegIdx, ArmISA::i, and BaseDynInst< Impl >::numSrcRegs().
Referenced by BaseDynInst< Impl >::tcBase().
effAddrValid() [1/2]
template<class Impl > bool BaseDynInst< Impl >::effAddrValid () const inline
Is the effective virtual address valid.
Definition at line 276 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::EffAddrValid.
effAddrValid() [2/2]
template<class Impl > void BaseDynInst< Impl >::effAddrValid (bool b) inline
Definition at line 277 of file base_dyn_inst.hh.
References ArmISA::b, and BaseDynInst< Impl >::EffAddrValid.
flattenDestReg()
template<class Impl > void BaseDynInst< Impl >::flattenDestReg (int idx, const RegId & flattened_dest) inline
Flattens a destination architectural register index into a logical index.
Definition at line 409 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::BaseDynInst(), BaseDynInst< Impl >::dump(), BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::~BaseDynInst().
flattenedDestRegIdx()
template<class Impl > const RegId& BaseDynInst< Impl >::flattenedDestRegIdx (int idx) const inline
Returns the flattened register index of the i'th destination register.
Definition at line 371 of file base_dyn_inst.hh.
getAddrMonitor()
template<class Impl > AddressMonitor* BaseDynInst< Impl >::getAddrMonitor () inline virtual
Implements ExecContext.
Definition at line 958 of file base_dyn_inst.hh.
getASID()
template<class Impl > short BaseDynInst< Impl >::getASID () inline
Definition at line 913 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::asid.
getCpuPtr()
template<class Impl > BaseCPU* BaseDynInst< Impl >::getCpuPtr () inline
Definition at line 159 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::cpu.
getFault() [1/2]
template<class Impl > Fault BaseDynInst< Impl >::getFault () const inline
Returns the fault type.
Definition at line 456 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::fault.
getFault() [2/2]
template<class Impl > Fault& BaseDynInst< Impl >::getFault () inline
TODO: This I added for the LSQRequest side to be able to modify the fault.
There should be a better mechanism in place.
Definition at line 459 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::fault.
getInstListIt()
template<class Impl > ListIt& BaseDynInst< Impl >::getInstListIt () inline
Returns iterator to this instruction in the list of all insts.
Definition at line 938 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::instListIt.
hasRequest()
template<class Impl > bool BaseDynInst< Impl >::hasRequest () const inline
Has this instruction generated a memory request.
Definition at line 933 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::ReqMade.
hitExternalSnoop() [1/2]
template<class Impl > bool BaseDynInst< Impl >::hitExternalSnoop () const inline
True if the address hit a external snoop while sitting in the LSQ.
If this is true and a older instruction sees it, this instruction must reexecute
Definition at line 336 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::HitExternalSnoop.
hitExternalSnoop() [2/2]
template<class Impl > void BaseDynInst< Impl >::hitExternalSnoop (bool f) inline
Definition at line 337 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::HitExternalSnoop.
initiateMemAMO()
template<class Impl > Fault BaseDynInst< Impl >::initiateMemAMO (Addr addr, unsigned size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
Definition at line 987 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::demapDataPage().
initiateMemRead()
template<class Impl > Fault BaseDynInst< Impl >::initiateMemRead (Addr addr, unsigned size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>())
Definition at line 964 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::demapDataPage().
initVars()
template<class Impl > void BaseDynInst< Impl >::initVars () private
Function to initialize variables in the constructors.
Definition at line 93 of file base_dyn_inst_impl.hh.
References BaseDynInst< Impl >::asid, BaseDynInst< Impl >::cpu, DPRINTF, BaseDynInst< Impl >::effAddr, BaseDynInst< Impl >::fault, BaseDynInst< Impl >::instFlags, BaseDynInst< Impl >::lqIdx, BaseDynInst< Impl >::MemAccPredicate, BaseDynInst< Impl >::memData, BaseDynInst< Impl >::memReqFlags, NoFault, BaseDynInst< Impl >::physEffAddr, BaseDynInst< Impl >::Predicate, BaseDynInst< Impl >::readyRegs, BaseDynInst< Impl >::RecordResult, BaseDynInst< Impl >::seqNum, BaseDynInst< Impl >::sqIdx, BaseDynInst< Impl >::status, and BaseDynInst< Impl >::threadNumber.
Referenced by BaseDynInst< Impl >::BaseDynInst(), and BaseDynInst< Impl >::flattenDestReg().
instAddr()
template<class Impl > Addr BaseDynInst< Impl >::instAddr () const inline
Read the PC of this instruction.
Definition at line 877 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::~BaseO3DynInst().
isAtCommit()
template<class Impl > bool BaseDynInst< Impl >::isAtCommit () inline
Definition at line 768 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::AtCommit.
isAtomic()
template<class Impl > bool BaseDynInst< Impl >::isAtomic () const inline
Definition at line 511 of file base_dyn_inst.hh.
References StaticInst::isAtomic().
isCall()
template<class Impl > bool BaseDynInst< Impl >::isCall () const inline
Definition at line 520 of file base_dyn_inst.hh.
References StaticInst::isCall().
isCommitted()
template<class Impl > bool BaseDynInst< Impl >::isCommitted () const inline
Returns whether or not this instruction is committed.
Definition at line 774 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Committed, and BaseDynInst< Impl >::setSquashed().
isCompleted()
template<class Impl > bool BaseDynInst< Impl >::isCompleted () const inline
Returns whether or not this instruction is completed.
Definition at line 725 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Completed.
isCondCtrl()
template<class Impl > bool BaseDynInst< Impl >::isCondCtrl () const inline
Definition at line 524 of file base_dyn_inst.hh.
References StaticInst::isCondCtrl().
isCondDelaySlot()
template<class Impl > bool BaseDynInst< Impl >::isCondDelaySlot () const inline
Definition at line 526 of file base_dyn_inst.hh.
References StaticInst::isCondDelaySlot().
isControl()
template<class Impl > bool BaseDynInst< Impl >::isControl () const inline
Definition at line 519 of file base_dyn_inst.hh.
References StaticInst::isControl().
isDataPrefetch()
template<class Impl > bool BaseDynInst< Impl >::isDataPrefetch () const inline
Definition at line 515 of file base_dyn_inst.hh.
References StaticInst::isDataPrefetch().
isDelayedCommit()
template<class Impl > bool BaseDynInst< Impl >::isDelayedCommit () const inline
Definition at line 543 of file base_dyn_inst.hh.
References StaticInst::isDelayedCommit().
isDirectCtrl()
template<class Impl > bool BaseDynInst< Impl >::isDirectCtrl () const inline
Definition at line 522 of file base_dyn_inst.hh.
References StaticInst::isDirectCtrl().
isExecuted()
template<class Impl > bool BaseDynInst< Impl >::isExecuted () const inline
Returns whether or not this instruction has executed.
Definition at line 755 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Executed.
isFirstMicroop()
template<class Impl > bool BaseDynInst< Impl >::isFirstMicroop () const inline
Definition at line 545 of file base_dyn_inst.hh.
References StaticInst::isFirstMicroop().
isFloating()
template<class Impl > bool BaseDynInst< Impl >::isFloating () const inline
Definition at line 517 of file base_dyn_inst.hh.
References StaticInst::isFloating().
isIndirectCtrl()
template<class Impl > bool BaseDynInst< Impl >::isIndirectCtrl () const inline
Definition at line 523 of file base_dyn_inst.hh.
References StaticInst::isIndirectCtrl().
isInIQ()
template<class Impl > bool BaseDynInst< Impl >::isInIQ () const inline
Returns whether or not this instruction has issued.
Definition at line 791 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::IqEntry.
isInLSQ()
template<class Impl > bool BaseDynInst< Impl >::isInLSQ () const inline
Returns whether or not this instruction is in the LSQ.
Definition at line 809 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::LsqEntry.
isInROB()
template<class Impl > bool BaseDynInst< Impl >::isInROB () const inline
Returns whether or not this instruction is in the ROB.
Definition at line 827 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RobEntry.
isInstPrefetch()
template<class Impl > bool BaseDynInst< Impl >::isInstPrefetch () const inline
Definition at line 514 of file base_dyn_inst.hh.
References StaticInst::isInstPrefetch().
isInteger()
template<class Impl > bool BaseDynInst< Impl >::isInteger () const inline
Definition at line 516 of file base_dyn_inst.hh.
References StaticInst::isInteger().
isIprAccess()
template<class Impl > bool BaseDynInst< Impl >::isIprAccess () const inline
Definition at line 538 of file base_dyn_inst.hh.
References StaticInst::isIprAccess().
isIssued()
template<class Impl > bool BaseDynInst< Impl >::isIssued () const inline
Returns whether or not this instruction has issued.
Definition at line 746 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Issued.
isLastMicroop()
template<class Impl > bool BaseDynInst< Impl >::isLastMicroop () const inline
Definition at line 544 of file base_dyn_inst.hh.
References StaticInst::isLastMicroop().
isLoad()
template<class Impl > bool BaseDynInst< Impl >::isLoad () const inline
Definition at line 509 of file base_dyn_inst.hh.
References StaticInst::isLoad().
isMacroop()
template<class Impl > bool BaseDynInst< Impl >::isMacroop () const inline
Definition at line 541 of file base_dyn_inst.hh.
References StaticInst::isMacroop().
isMemBarrier()
template<class Impl > bool BaseDynInst< Impl >::isMemBarrier () const inline
Definition at line 534 of file base_dyn_inst.hh.
References StaticInst::isMemBarrier().
isMemRef()
template<class Impl > bool BaseDynInst< Impl >::isMemRef () const inline
Definition at line 508 of file base_dyn_inst.hh.
References StaticInst::isMemRef().
isMicroBranch()
template<class Impl > bool BaseDynInst< Impl >::isMicroBranch () const inline
Definition at line 546 of file base_dyn_inst.hh.
References StaticInst::isMicroBranch().
isMicroop()
template<class Impl > bool BaseDynInst< Impl >::isMicroop () const inline
Definition at line 542 of file base_dyn_inst.hh.
References StaticInst::isMicroop().
isNonSpeculative()
template<class Impl > bool BaseDynInst< Impl >::isNonSpeculative () const inline
Definition at line 536 of file base_dyn_inst.hh.
References StaticInst::isNonSpeculative().
isNop()
template<class Impl > bool BaseDynInst< Impl >::isNop () const inline
Definition at line 507 of file base_dyn_inst.hh.
References StaticInst::isNop().
isPinnedRegsRenamed()
template<class Impl > bool BaseDynInst< Impl >::isPinnedRegsRenamed () const inline
Returns whether pinned registers are renamed.
Definition at line 836 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsRenamed.
Referenced by BaseDynInst< Impl >::setSquashed().
isPinnedRegsSquashDone()
template<class Impl > bool BaseDynInst< Impl >::isPinnedRegsSquashDone () const inline
Return whether dest registers' pinning status updated after squash.
Definition at line 861 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsSquashDone.
Referenced by BaseDynInst< Impl >::setSquashed().
isPinnedRegsWritten()
template<class Impl > bool BaseDynInst< Impl >::isPinnedRegsWritten () const inline
Returns whether destination registers are written.
Definition at line 848 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsWritten.
Referenced by BaseDynInst< Impl >::setSquashed().
isQuiesce()
template<class Impl > bool BaseDynInst< Impl >::isQuiesce () const inline
Definition at line 537 of file base_dyn_inst.hh.
References StaticInst::isQuiesce().
isReadySrcRegIdx()
template<class Impl > bool BaseDynInst< Impl >::isReadySrcRegIdx (int idx) const inline
Returns if a source register is ready.
Definition at line 716 of file base_dyn_inst.hh.
isResultReady()
template<class Impl > bool BaseDynInst< Impl >::isResultReady () const inline
Returns whether or not the result is ready.
Definition at line 731 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::ResultReady.
isReturn()
template<class Impl > bool BaseDynInst< Impl >::isReturn () const inline
Definition at line 521 of file base_dyn_inst.hh.
References StaticInst::isReturn().
isSerializeAfter()
template<class Impl > bool BaseDynInst< Impl >::isSerializeAfter () const inline
Definition at line 531 of file base_dyn_inst.hh.
References StaticInst::isSerializeAfter(), and BaseDynInst< Impl >::SerializeAfter.
isSerializeBefore()
template<class Impl > bool BaseDynInst< Impl >::isSerializeBefore () const inline
Definition at line 529 of file base_dyn_inst.hh.
References StaticInst::isSerializeBefore(), and BaseDynInst< Impl >::SerializeBefore.
isSerializeHandled()
template<class Impl > bool BaseDynInst< Impl >::isSerializeHandled () inline
Checks if the serialization part of this instruction has been handled.
This does not apply to the temporary serializing state; it only applies to this instruction's own permanent serializing state.
Definition at line 574 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeHandled.
isSerializing()
template<class Impl > bool BaseDynInst< Impl >::isSerializing () const inline
Definition at line 528 of file base_dyn_inst.hh.
References StaticInst::isSerializing().
isSquashAfter()
template<class Impl > bool BaseDynInst< Impl >::isSquashAfter () const inline
Definition at line 533 of file base_dyn_inst.hh.
References StaticInst::isSquashAfter().
isSquashed()
template<class Impl > bool BaseDynInst< Impl >::isSquashed () const inline
Returns whether or not this instruction is squashed.
Definition at line 780 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Squashed.
isSquashedInIQ()
template<class Impl > bool BaseDynInst< Impl >::isSquashedInIQ () const inline
Returns whether or not this instruction is squashed in the IQ.
Definition at line 797 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SquashedInIQ.
isSquashedInLSQ()
template<class Impl > bool BaseDynInst< Impl >::isSquashedInLSQ () const inline
Returns whether or not this instruction is squashed in the LSQ.
Definition at line 815 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SquashedInLSQ.
isSquashedInROB()
template<class Impl > bool BaseDynInst< Impl >::isSquashedInROB () const inline
Returns whether or not this instruction is squashed in the ROB.
Definition at line 833 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SquashedInROB.
isStore()
template<class Impl > bool BaseDynInst< Impl >::isStore () const inline
Definition at line 510 of file base_dyn_inst.hh.
References StaticInst::isStore().
isStoreConditional()
template<class Impl > bool BaseDynInst< Impl >::isStoreConditional () const inline
Definition at line 512 of file base_dyn_inst.hh.
References StaticInst::isStoreConditional().
Referenced by BaseO3DynInst< Impl >::completeAcc().
isSyscall()
template<class Impl > bool BaseDynInst< Impl >::isSyscall () const inline
Definition at line 540 of file base_dyn_inst.hh.
References StaticInst::isSyscall().
isTempSerializeAfter()
template<class Impl > bool BaseDynInst< Impl >::isTempSerializeAfter () inline
Checks if this serializeAfter is only temporarily set.
Definition at line 564 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeAfter.
isTempSerializeBefore()
template<class Impl > bool BaseDynInst< Impl >::isTempSerializeBefore () inline
Checks if this serializeBefore is only temporarily set.
Definition at line 555 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeBefore.
isThreadSync()
template<class Impl > bool BaseDynInst< Impl >::isThreadSync () const inline
Definition at line 527 of file base_dyn_inst.hh.
References StaticInst::isThreadSync().
isTranslationDelayed()
template<class Impl > bool BaseDynInst< Impl >::isTranslationDelayed () const inline
Returns true if the DTB address translation is being delayed due to a hw page table walk.
Definition at line 343 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::translationCompleted(), and BaseDynInst< Impl >::translationStarted().
isUncondCtrl()
template<class Impl > bool BaseDynInst< Impl >::isUncondCtrl () const inline
Definition at line 525 of file base_dyn_inst.hh.
References StaticInst::isUncondCtrl().
isUnverifiable()
template<class Impl > bool BaseDynInst< Impl >::isUnverifiable () const inline
Definition at line 539 of file base_dyn_inst.hh.
References StaticInst::isUnverifiable().
isVector()
template<class Impl > bool BaseDynInst< Impl >::isVector () const inline
Definition at line 518 of file base_dyn_inst.hh.
References StaticInst::isVector().
isWriteBarrier()
template<class Impl > bool BaseDynInst< Impl >::isWriteBarrier () const inline
Definition at line 535 of file base_dyn_inst.hh.
References StaticInst::isWriteBarrier().
markSrcRegReady() [1/2]
template<class Impl > void BaseDynInst< Impl >::markSrcRegReady ()
Records that one of the source registers is ready.
Definition at line 206 of file base_dyn_inst_impl.hh.
References DPRINTF, BaseDynInst< Impl >::numSrcRegs(), BaseDynInst< Impl >::readyRegs, BaseDynInst< Impl >::readyToIssue(), BaseDynInst< Impl >::seqNum, and BaseDynInst< Impl >::setCanIssue().
Referenced by BaseDynInst< Impl >::markSrcRegReady(), and BaseDynInst< Impl >::setVecPredRegOperand().
markSrcRegReady() [2/2]
template<class Impl > void BaseDynInst< Impl >::markSrcRegReady (RegIndex src_idx)
Marks a specific register as ready.
Definition at line 217 of file base_dyn_inst_impl.hh.
References BaseDynInst< Impl >::_readySrcRegIdx, and BaseDynInst< Impl >::markSrcRegReady().
masterId()
template<class Impl > MasterID BaseDynInst< Impl >::masterId () const inline
Read this CPU's data requestor ID.
Definition at line 450 of file base_dyn_inst.hh.
memOpDone() [1/2]
template<class Impl > bool BaseDynInst< Impl >::memOpDone () const inline
Whether or not the memory operation is done.
Definition at line 280 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::MemOpDone.
memOpDone() [2/2]
template<class Impl > void BaseDynInst< Impl >::memOpDone (bool f) inline
Definition at line 281 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::MemOpDone.
microPC()
template<class Impl > Addr BaseDynInst< Impl >::microPC () const inline
Read the micro PC of this instruction.
Definition at line 883 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::~BaseO3DynInst().
mispredicted()
template<class Impl > bool BaseDynInst< Impl >::mispredicted () inline
Returns whether the instruction mispredicted.
Definition at line 497 of file base_dyn_inst.hh.
References AlphaISA::advancePC(), BaseDynInst< Impl >::pc, and BaseDynInst< Impl >::predPC.
mwait()
template<class Impl > bool BaseDynInst< Impl >::mwait (PacketPtr pkt) inline virtual
Implements ExecContext.
Definition at line 955 of file base_dyn_inst.hh.
mwaitAtomic()
template<class Impl > void BaseDynInst< Impl >::mwaitAtomic (ThreadContext * tc) inline virtual
Implements ExecContext.
Definition at line 956 of file base_dyn_inst.hh.
nextInstAddr()
template<class Impl > Addr BaseDynInst< Impl >::nextInstAddr () const inline
Read the PC of the next instruction.
Definition at line 880 of file base_dyn_inst.hh.
notAnInst()
template<class Impl > bool BaseDynInst< Impl >::notAnInst () const inline
Definition at line 283 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::NotAnInst.
numCCDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numCCDestRegs () const inline
Definition at line 593 of file base_dyn_inst.hh.
References StaticInst::numCCDestRegs().
numDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numDestRegs () const inline
Returns the number of destination registers.
Definition at line 587 of file base_dyn_inst.hh.
References StaticInst::numDestRegs().
Referenced by BaseO3DynInst< Impl >::forwardOldRegs(), and BaseDynInst< Impl >::setSquashed().
numFPDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numFPDestRegs () const inline
Definition at line 591 of file base_dyn_inst.hh.
References StaticInst::numFPDestRegs().
numIntDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numIntDestRegs () const inline
Definition at line 592 of file base_dyn_inst.hh.
References StaticInst::numIntDestRegs().
numSrcRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numSrcRegs () const inline
Returns the number of source registers.
Definition at line 584 of file base_dyn_inst.hh.
References StaticInst::numSrcRegs().
Referenced by BaseDynInst< Impl >::eaSrcsReady(), and BaseDynInst< Impl >::markSrcRegReady().
numVecDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numVecDestRegs () const inline
Definition at line 594 of file base_dyn_inst.hh.
References StaticInst::numVecDestRegs().
numVecElemDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numVecElemDestRegs () const inline
Definition at line 595 of file base_dyn_inst.hh.
References StaticInst::numVecElemDestRegs().
numVecPredDestRegs()
template<class Impl > int8_t BaseDynInst< Impl >::numVecPredDestRegs () const inline
Definition at line 600 of file base_dyn_inst.hh.
References StaticInst::numVecPredDestRegs().
opClass()
template<class Impl > OpClass BaseDynInst< Impl >::opClass () const inline
Returns the opclass of this instruction.
Definition at line 577 of file base_dyn_inst.hh.
References StaticInst::opClass().
pcState() [1/2]
template<class Impl > TheISA::PCState BaseDynInst< Impl >::pcState () const inline virtual
Read the PC state of this instruction.
Implements ExecContext.
Definition at line 871 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::pc.
Referenced by BaseO3DynInst< Impl >::syscall().
pcState() [2/2]
template<class Impl > void BaseDynInst< Impl >::pcState (const TheISA::PCState & val) inline virtual
Set the PC state of this instruction.
Implements ExecContext.
Definition at line 874 of file base_dyn_inst.hh.
References X86ISA::val.
popResult()
template<class Impl > InstResult BaseDynInst< Impl >::popResult (InstResult dflt = InstResult()) inline
Pops a result off the instResult queue.
If the result stack is empty, return the default value.
Definition at line 617 of file base_dyn_inst.hh.
References ArmISA::t.
possibleLoadViolation() [1/2]
template<class Impl > bool BaseDynInst< Impl >::possibleLoadViolation () const inline
True if this address was found to match a previous load and they issued out of order.
If that happend, then it's only a problem if an incoming snoop invalidate modifies the line, in which case we need to squash. If nothing modified the line the order doesn't matter.
Definition at line 329 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PossibleLoadViolation.
possibleLoadViolation() [2/2]
template<class Impl > void BaseDynInst< Impl >::possibleLoadViolation (bool f) inline
Definition at line 330 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::PossibleLoadViolation.
predInstAddr()
template<class Impl > Addr BaseDynInst< Impl >::predInstAddr () inline
Returns the predicted PC immediately after the branch.
Definition at line 477 of file base_dyn_inst.hh.
predMicroPC()
template<class Impl > Addr BaseDynInst< Impl >::predMicroPC () inline
Returns the predicted micro PC after the branch.
Definition at line 483 of file base_dyn_inst.hh.
predNextInstAddr()
template<class Impl > Addr BaseDynInst< Impl >::predNextInstAddr () inline
Returns the predicted PC two instructions after the branch.
Definition at line 480 of file base_dyn_inst.hh.
prevDestRegIdx()
template<class Impl > PhysRegIdPtr BaseDynInst< Impl >::prevDestRegIdx (int idx) const inline
Returns the physical register index of the previous physical register that remapped to the same logical register index.
Definition at line 379 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::forwardOldRegs().
readMemAccPredicate()
template<class Impl > bool BaseDynInst< Impl >::readMemAccPredicate () const inline virtual
Implements ExecContext.
Definition at line 900 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::MemAccPredicate.
readPredicate()
template<class Impl > bool BaseDynInst< Impl >::readPredicate () const inline virtual
Implements ExecContext.
Definition at line 885 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Predicate.
readPredTaken()
template<class Impl > bool BaseDynInst< Impl >::readPredTaken () inline
Returns whether the instruction was predicted taken or not.
Definition at line 486 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PredTaken.
readPredTarg()
template<class Impl > const TheISA::PCState& BaseDynInst< Impl >::readPredTarg () inline
Definition at line 474 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::predPC.
readStCondFailures()
template<class Impl > unsigned int BaseDynInst< Impl >::readStCondFailures () const inline virtual
Returns the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 945 of file base_dyn_inst.hh.
readyToCommit()
template<class Impl > bool BaseDynInst< Impl >::readyToCommit () const inline
Returns whether or not this instruction is ready to commit.
Definition at line 764 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanCommit.
readyToIssue()
template<class Impl > bool BaseDynInst< Impl >::readyToIssue () const inline
Returns whether or not this instruction is ready to issue.
Definition at line 737 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanIssue.
Referenced by BaseDynInst< Impl >::markSrcRegReady().
recordResult()
template<class Impl > void BaseDynInst< Impl >::recordResult (bool f) inline
Records changes to result?
Definition at line 273 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::RecordResult.
removeInLSQ()
template<class Impl > void BaseDynInst< Impl >::removeInLSQ () inline
Sets this instruction as a entry the LSQ.
Definition at line 806 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::LsqEntry.
renamedDestRegIdx()
template<class Impl > PhysRegIdPtr BaseDynInst< Impl >::renamedDestRegIdx (int idx) const inline
Returns the physical register index of the i'th destination register.
Definition at line 356 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::setSquashed().
renameDestReg()
template<class Impl > void BaseDynInst< Impl >::renameDestReg (int idx, PhysRegIdPtr renamed_dest, PhysRegIdPtr previous_rename) inline
Renames a destination register to a physical register.
Also records the previous physical register that the logical register mapped to.
Definition at line 387 of file base_dyn_inst.hh.
References PhysRegId::isPinned(), and BaseDynInst< Impl >::setPinnedRegsRenamed().
renamedSrcRegIdx()
template<class Impl > PhysRegIdPtr BaseDynInst< Impl >::renamedSrcRegIdx (int idx) const inline
Returns the physical register index of the i'th source register.
Definition at line 362 of file base_dyn_inst.hh.
References ArmISA::MaxInstSrcRegs.
renameSrcReg()
template<class Impl > void BaseDynInst< Impl >::renameSrcReg (int idx, PhysRegIdPtr renamed_src) inline
Renames a source logical register to the physical register which has/will produce that logical register's result.
Todo:
: add in whether or not the source register is ready.
Definition at line 401 of file base_dyn_inst.hh.
resultSize()
template<class Impl > uint8_t BaseDynInst< Impl >::resultSize () inline
Return the size of the instResult queue.
Definition at line 612 of file base_dyn_inst.hh.
setASID()
template<class Impl > void BaseDynInst< Impl >::setASID (short addr_space_id) inline
Sets the ASID.
Definition at line 912 of file base_dyn_inst.hh.
setAtCommit()
template<class Impl > void BaseDynInst< Impl >::setAtCommit () inline
Definition at line 766 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::AtCommit.
setCanCommit()
template<class Impl > void BaseDynInst< Impl >::setCanCommit () inline
Sets this instruction as ready to commit.
Definition at line 758 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanCommit.
setCanIssue()
template<class Impl > void BaseDynInst< Impl >::setCanIssue () inline
Sets this instruction as ready to issue.
Definition at line 734 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::CanIssue.
Referenced by BaseDynInst< Impl >::markSrcRegReady().
setCCRegOperand()
template<class Impl > void BaseDynInst< Impl >::setCCRegOperand (const StaticInst * si, int idx, RegVal val) inline virtual
Records a CC register being set to a value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 677 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::setScalarResult().
Referenced by BaseO3DynInst< Impl >::setCCRegOperand().
setCommitted()
template<class Impl > void BaseDynInst< Impl >::setCommitted () inline
Sets this instruction as committed.
Definition at line 771 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Committed.
setCompleted()
template<class Impl > void BaseDynInst< Impl >::setCompleted () inline
Sets this instruction as completed.
Definition at line 722 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Completed.
setExecuted()
template<class Impl > void BaseDynInst< Impl >::setExecuted () inline
Sets this instruction as executed.
Definition at line 752 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Executed.
setFloatRegOperandBits()
template<class Impl > void BaseDynInst< Impl >::setFloatRegOperandBits (const StaticInst * si, int idx, RegVal val) inline virtual
Records an fp register being set to an integer value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 691 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::setScalarResult().
Referenced by BaseO3DynInst< Impl >::setFloatRegOperandBits().
setInIQ()
template<class Impl > void BaseDynInst< Impl >::setInIQ () inline
Sets this instruction as a entry the IQ.
Definition at line 785 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::IqEntry.
setInLSQ()
template<class Impl > void BaseDynInst< Impl >::setInLSQ () inline
Sets this instruction as a entry the LSQ.
Definition at line 803 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::LsqEntry.
setInROB()
template<class Impl > void BaseDynInst< Impl >::setInROB () inline
Sets this instruction as a entry the ROB.
Definition at line 821 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RobEntry.
setInstListIt()
template<class Impl > void BaseDynInst< Impl >::setInstListIt (ListIt _instListIt) inline
Sets iterator for this instruction in the list of all insts.
Definition at line 941 of file base_dyn_inst.hh.
setIntRegOperand()
template<class Impl > void BaseDynInst< Impl >::setIntRegOperand (const StaticInst * si, int idx, RegVal val) inline virtual
Records an integer register being set to a value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 671 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::setScalarResult().
Referenced by BaseO3DynInst< Impl >::setIntRegOperand().
setIssued()
template<class Impl > void BaseDynInst< Impl >::setIssued () inline
Sets this instruction as issued from the IQ.
Definition at line 743 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Issued.
setMemAccPredicate()
template<class Impl > void BaseDynInst< Impl >::setMemAccPredicate (bool val) inline virtual
Implements ExecContext.
Definition at line 906 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::MemAccPredicate, and X86ISA::val.
setNotAnInst()
template<class Impl > void BaseDynInst< Impl >::setNotAnInst () inline
Definition at line 284 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::NotAnInst.
setPinnedRegsRenamed()
template<class Impl > void BaseDynInst< Impl >::setPinnedRegsRenamed () inline
Sets the destination registers as renamed.
Definition at line 840 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsRenamed, BaseDynInst< Impl >::PinnedRegsSquashDone, and BaseDynInst< Impl >::PinnedRegsWritten.
Referenced by BaseDynInst< Impl >::renameDestReg().
setPinnedRegsSquashDone()
template<class Impl > void BaseDynInst< Impl >::setPinnedRegsSquashDone () inline
Sets dest registers' status updated after squash.
Definition at line 865 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsSquashDone.
Referenced by BaseDynInst< Impl >::setSquashed().
setPinnedRegsWritten()
template<class Impl > void BaseDynInst< Impl >::setPinnedRegsWritten () inline
Sets destination registers as written.
Definition at line 852 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PinnedRegsRenamed, BaseDynInst< Impl >::PinnedRegsSquashDone, and BaseDynInst< Impl >::PinnedRegsWritten.
setPredicate()
template<class Impl > void BaseDynInst< Impl >::setPredicate (bool val) inline virtual
Implements ExecContext.
Definition at line 890 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Predicate, Trace::InstRecord::setPredicate(), and X86ISA::val.
setPredTaken()
template<class Impl > void BaseDynInst< Impl >::setPredTaken (bool predicted_taken) inline
Definition at line 491 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::PredTaken.
setPredTarg()
template<class Impl > void BaseDynInst< Impl >::setPredTarg (const TheISA::PCState & _predPC) inline
Set the predicted target of this current instruction.
Definition at line 469 of file base_dyn_inst.hh.
setRequest()
template<class Impl > void BaseDynInst< Impl >::setRequest () inline
Assert this instruction has generated a memory request.
Definition at line 935 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::ReqMade.
setResultReady()
template<class Impl > void BaseDynInst< Impl >::setResultReady () inline
Marks the result as ready.
Definition at line 728 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::ResultReady.
setScalarResult()
template<class Impl > template<typename T > void BaseDynInst< Impl >::setScalarResult (T && t) inline
Pushes a result onto the instResult queue.
Scalar result.
Definition at line 631 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RecordResult, InstResult::Scalar, and ArmISA::t.
Referenced by BaseDynInst< Impl >::setCCRegOperand(), BaseDynInst< Impl >::setFloatRegOperandBits(), and BaseDynInst< Impl >::setIntRegOperand().
setSerializeAfter()
template<class Impl > void BaseDynInst< Impl >::setSerializeAfter () inline
Temporarily sets this instruction as a serialize after instruction.
Definition at line 558 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeAfter.
setSerializeBefore()
template<class Impl > void BaseDynInst< Impl >::setSerializeBefore () inline
Temporarily sets this instruction as a serialize before instruction.
Definition at line 549 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeBefore.
setSerializeHandled()
template<class Impl > void BaseDynInst< Impl >::setSerializeHandled () inline
Sets the serialization part of this instruction as handled.
Definition at line 567 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SerializeHandled.
setSquashed()
template<class Impl > void BaseDynInst< Impl >::setSquashed ()
Sets this instruction as squashed.
Definition at line 244 of file base_dyn_inst_impl.hh.
References PhysRegId::incrNumPinnedWrites(), PhysRegId::incrNumPinnedWritesToComplete(), PhysRegId::isPinned(), BaseDynInst< Impl >::isPinnedRegsRenamed(), BaseDynInst< Impl >::isPinnedRegsSquashDone(), BaseDynInst< Impl >::isPinnedRegsWritten(), BaseDynInst< Impl >::numDestRegs(), BaseDynInst< Impl >::renamedDestRegIdx(), BaseDynInst< Impl >::setPinnedRegsSquashDone(), BaseDynInst< Impl >::Squashed, and BaseDynInst< Impl >::status.
Referenced by BaseDynInst< Impl >::isCommitted().
setSquashedInIQ()
template<class Impl > void BaseDynInst< Impl >::setSquashedInIQ () inline
Sets this instruction as squashed in the IQ.
Definition at line 794 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Squashed, and BaseDynInst< Impl >::SquashedInIQ.
setSquashedInLSQ()
template<class Impl > void BaseDynInst< Impl >::setSquashedInLSQ () inline
Sets this instruction as squashed in the LSQ.
Definition at line 812 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::Squashed, and BaseDynInst< Impl >::SquashedInLSQ.
setSquashedInROB()
template<class Impl > void BaseDynInst< Impl >::setSquashedInROB () inline
Sets this instruction as squashed in the ROB.
Definition at line 830 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::SquashedInROB.
setStCondFailures()
template<class Impl > void BaseDynInst< Impl >::setStCondFailures (unsigned int sc_failures) inline virtual
Sets the number of consecutive store conditional failures.
Implements ExecContext.
Definition at line 949 of file base_dyn_inst.hh.
setThreadState()
template<class Impl > void BaseDynInst< Impl >::setThreadState (ImplState * state) inline
Sets the pointer to the thread state.
Definition at line 919 of file base_dyn_inst.hh.
setTid()
template<class Impl > void BaseDynInst< Impl >::setTid (ThreadID tid) inline
Sets the thread id.
Definition at line 916 of file base_dyn_inst.hh.
setVecElemOperand()
template<class Impl > void BaseDynInst< Impl >::setVecElemOperand (const StaticInst * si, int idx, const VecElem val) inline virtual
Record a vector register being set to a value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 697 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::setVecElemResult().
Referenced by BaseO3DynInst< Impl >::setVecElemOperand().
setVecElemResult()
template<class Impl > template<typename T > void BaseDynInst< Impl >::setVecElemResult (T && t) inline
Vector element result.
Definition at line 651 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RecordResult, ArmISA::t, and InstResult::VecElem.
Referenced by BaseDynInst< Impl >::setVecElemOperand().
setVecPredRegOperand()
template<class Impl > void BaseDynInst< Impl >::setVecPredRegOperand (const StaticInst * si, int idx, const VecPredRegContainer & val) inline virtual
Record a vector register being set to a value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 703 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::markSrcRegReady(), and BaseDynInst< Impl >::setVecPredResult().
Referenced by BaseO3DynInst< Impl >::setVecPredRegOperand().
setVecPredResult()
template<class Impl > template<typename T > void BaseDynInst< Impl >::setVecPredResult (T && t) inline
Predicate result.
Definition at line 661 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RecordResult, ArmISA::t, and InstResult::VecPredReg.
Referenced by BaseDynInst< Impl >::setVecPredRegOperand().
setVecRegOperand()
template<class Impl > void BaseDynInst< Impl >::setVecRegOperand (const StaticInst * si, int idx, const VecRegContainer & val) inline virtual
Record a vector register being set to a value.
Implements ExecContext.
Reimplemented in BaseO3DynInst< Impl >.
Definition at line 683 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::setVecResult().
Referenced by BaseO3DynInst< Impl >::setVecRegOperand().
setVecResult()
template<class Impl > template<typename T > void BaseDynInst< Impl >::setVecResult (T && t) inline
Full vector result.
Definition at line 641 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::RecordResult, ArmISA::t, and InstResult::VecReg.
Referenced by BaseDynInst< Impl >::setVecRegOperand().
socketId()
template<class Impl > uint32_t BaseDynInst< Impl >::socketId () const inline
Read this CPU's Socket ID.
Definition at line 447 of file base_dyn_inst.hh.
srcRegIdx()
template<class Impl > const RegId& BaseDynInst< Impl >::srcRegIdx (int i) const inline
Returns the logical register index of the i'th source register.
Definition at line 609 of file base_dyn_inst.hh.
References StaticInst::srcRegIdx().
strictlyOrdered() [1/2]
template<class Impl > bool BaseDynInst< Impl >::strictlyOrdered () const inline
Is this instruction's memory access strictly ordered?
Definition at line 929 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::IsStrictlyOrdered.
strictlyOrdered() [2/2]
template<class Impl > void BaseDynInst< Impl >::strictlyOrdered (bool so) inline
Definition at line 930 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::IsStrictlyOrdered, and PowerISA::so.
tcBase()
template<class Impl > ThreadContext* BaseDynInst< Impl >::tcBase () inline virtual
Returns the thread context.
Implements ExecContext.
Definition at line 922 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::eaSrcsReady().
translationCompleted() [1/2]
template<class Impl > bool BaseDynInst< Impl >::translationCompleted () const inline
True if the DTB address translation has completed.
Definition at line 321 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::TranslationCompleted.
Referenced by BaseDynInst< Impl >::isTranslationDelayed().
translationCompleted() [2/2]
template<class Impl > void BaseDynInst< Impl >::translationCompleted (bool f) inline
Definition at line 322 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::TranslationCompleted.
translationStarted() [1/2]
template<class Impl > bool BaseDynInst< Impl >::translationStarted () const inline
True if the DTB address translation has started.
Definition at line 317 of file base_dyn_inst.hh.
References BaseDynInst< Impl >::TranslationStarted.
Referenced by BaseDynInst< Impl >::isTranslationDelayed().
translationStarted() [2/2]
template<class Impl > void BaseDynInst< Impl >::translationStarted (bool f) inline
Definition at line 318 of file base_dyn_inst.hh.
References ArmISA::f, and BaseDynInst< Impl >::TranslationStarted.
writeMem()
template<class Impl > Fault BaseDynInst< Impl >::writeMem (uint8_t * data, unsigned size, Addr addr, Request::Flags flags, uint64_t * res, const std::vector< bool > & byteEnable = std::vector<bool>())
Definition at line 976 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::demapDataPage().
Member Data Documentation
_destRegIdx
template<class Impl > std::array<PhysRegIdPtr, TheISA::MaxInstDestRegs> BaseDynInst< Impl >::_destRegIdx protected
Physical register index of the destination registers of this instruction.
Definition at line 258 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::getWritableVecPredRegOperand(), BaseO3DynInst< Impl >::getWritableVecRegOperand(), BaseO3DynInst< Impl >::setCCRegOperand(), BaseO3DynInst< Impl >::setFloatRegOperandBits(), BaseO3DynInst< Impl >::setIntRegOperand(), BaseO3DynInst< Impl >::setVecElemOperand(), BaseO3DynInst< Impl >::setVecLaneOperandT(), BaseO3DynInst< Impl >::setVecPredRegOperand(), and BaseO3DynInst< Impl >::setVecRegOperand().
_flatDestRegIdx
template<class Impl > std::array<RegId, TheISA::MaxInstDestRegs> BaseDynInst< Impl >::_flatDestRegIdx protected
Flattened register index of the destination registers of this instruction.
Definition at line 253 of file base_dyn_inst.hh.
_prevDestRegIdx
template<class Impl > std::array<PhysRegIdPtr, TheISA::MaxInstDestRegs> BaseDynInst< Impl >::_prevDestRegIdx protected
Physical register index of the previous producers of the architected destinations.
Definition at line 268 of file base_dyn_inst.hh.
_readySrcRegIdx
template<class Impl > std::bitset<MaxInstSrcRegs> BaseDynInst< Impl >::_readySrcRegIdx protected
Whether or not the source register is ready.
Todo:
: Not sure this should be here vs the derived class.
Definition at line 190 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::eaSrcsReady(), BaseO3DynInst< Impl >::initVars(), and BaseDynInst< Impl >::markSrcRegReady().
_srcRegIdx
template<class Impl > std::array<PhysRegIdPtr, TheISA::MaxInstSrcRegs> BaseDynInst< Impl >::_srcRegIdx protected
Physical register index of the source registers of this instruction.
Definition at line 263 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::readCCRegOperand(), BaseO3DynInst< Impl >::readFloatRegOperandBits(), BaseO3DynInst< Impl >::readIntRegOperand(), BaseO3DynInst< Impl >::readVec16BitLaneOperand(), BaseO3DynInst< Impl >::readVec32BitLaneOperand(), BaseO3DynInst< Impl >::readVec64BitLaneOperand(), BaseO3DynInst< Impl >::readVec8BitLaneOperand(), BaseO3DynInst< Impl >::readVecElemOperand(), BaseO3DynInst< Impl >::readVecPredRegOperand(), and BaseO3DynInst< Impl >::readVecRegOperand().
asid
template<class Impl > short BaseDynInst< Impl >::asid
data address space ID, for loads & stores.
Definition at line 221 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::getASID(), and BaseDynInst< Impl >::initVars().
cpu
template<class Impl > ImplCPU* BaseDynInst< Impl >::cpu
Pointer to the Impl's CPU object.
Definition at line 157 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc(), BaseO3DynInst< Impl >::forwardOldRegs(), BaseDynInst< Impl >::getCpuPtr(), BaseO3DynInst< Impl >::getWritableVecPredRegOperand(), BaseO3DynInst< Impl >::getWritableVecRegOperand(), BaseDynInst< Impl >::initVars(), BaseO3DynInst< Impl >::readCCRegOperand(), BaseO3DynInst< Impl >::readFloatRegOperandBits(), BaseO3DynInst< Impl >::readIntRegOperand(), BaseO3DynInst< Impl >::readMiscReg(), BaseO3DynInst< Impl >::readMiscRegOperand(), BaseO3DynInst< Impl >::readVec16BitLaneOperand(), BaseO3DynInst< Impl >::readVec32BitLaneOperand(), BaseO3DynInst< Impl >::readVec64BitLaneOperand(), BaseO3DynInst< Impl >::readVec8BitLaneOperand(), BaseO3DynInst< Impl >::readVecElemOperand(), BaseO3DynInst< Impl >::readVecPredRegOperand(), BaseO3DynInst< Impl >::readVecRegOperand(), BaseO3DynInst< Impl >::setCCRegOperand(), BaseO3DynInst< Impl >::setFloatRegOperandBits(), BaseO3DynInst< Impl >::setIntRegOperand(), BaseO3DynInst< Impl >::setVecElemOperand(), BaseO3DynInst< Impl >::setVecLaneOperandT(), BaseO3DynInst< Impl >::setVecPredRegOperand(), BaseO3DynInst< Impl >::setVecRegOperand(), BaseO3DynInst< Impl >::syscall(), BaseO3DynInst< Impl >::trap(), BaseO3DynInst< Impl >::updateMiscRegs(), and BaseDynInst< Impl >::~BaseDynInst().
effAddr
template<class Impl > Addr BaseDynInst< Impl >::effAddr
The effective virtual address (lds & stores only).
Definition at line 212 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
effSize
template<class Impl > unsigned BaseDynInst< Impl >::effSize
The size of the request.
Definition at line 224 of file base_dyn_inst.hh.
fault
template<class Impl > Fault BaseDynInst< Impl >::fault
The kind of fault this instruction has generated.
Definition at line 165 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc(), BaseO3DynInst< Impl >::execute(), BaseO3DynInst< Impl >::forwardOldRegs(), BaseDynInst< Impl >::getFault(), BaseO3DynInst< Impl >::initiateAcc(), BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::~BaseDynInst().
instFlags
template<class Impl > std::bitset<MaxFlags> BaseDynInst< Impl >::instFlags private
Definition at line 181 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
instListIt
template<class Impl > ListIt BaseDynInst< Impl >::instListIt
Iterator pointing to this BaseDynInst in the list of all insts.
Definition at line 197 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::getInstListIt().
instResult
template<class Impl > std::queue<InstResult> BaseDynInst< Impl >::instResult protected
The result of the instruction; assumes an instruction can have many destination registers.
Definition at line 174 of file base_dyn_inst.hh.
lqIdx
template<class Impl > int16_t BaseDynInst< Impl >::lqIdx
Load queue index.
Definition at line 230 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
lqIt
template<class Impl > LQIterator BaseDynInst< Impl >::lqIt
Definition at line 231 of file base_dyn_inst.hh.
macroop
template<class Impl > const StaticInstPtr BaseDynInst< Impl >::macroop
The Macroop if one exists.
Definition at line 204 of file base_dyn_inst.hh.
memData
template<class Impl > uint8_t* BaseDynInst< Impl >::memData
Pointer to the data for the memory access.
Definition at line 227 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::~BaseDynInst().
memReqFlags
template<class Impl > unsigned BaseDynInst< Impl >::memReqFlags
The memory request flags (from translation).
Definition at line 218 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
pc
template<class Impl > TheISA::PCState BaseDynInst< Impl >::pc protected
PC state for this instruction.
Definition at line 177 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::BaseDynInst(), BaseDynInst< Impl >::dump(), BaseDynInst< Impl >::mispredicted(), and BaseDynInst< Impl >::pcState().
physEffAddr
template<class Impl > Addr BaseDynInst< Impl >::physEffAddr
The effective physical address.
Definition at line 215 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
predPC
template<class Impl > TheISA::PCState BaseDynInst< Impl >::predPC
Predicted PC state after this instruction.
Definition at line 201 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::BaseDynInst(), BaseDynInst< Impl >::mispredicted(), and BaseDynInst< Impl >::readPredTarg().
readyRegs
template<class Impl > uint8_t BaseDynInst< Impl >::readyRegs
How many source registers are ready.
Definition at line 207 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::markSrcRegReady().
reqToVerify
template<class Impl > RequestPtr BaseDynInst< Impl >::reqToVerify
Definition at line 247 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc().
savedReq
template<class Impl > LSQRequestPtr BaseDynInst< Impl >::savedReq
Saved memory request (needed when the DTB address translation is delayed due to a hw page table walk).
Definition at line 243 of file base_dyn_inst.hh.
seqNum
template<class Impl > InstSeqNum BaseDynInst< Impl >::seqNum
The sequence number of the instruction.
Definition at line 151 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::BaseDynInst(), BaseDynInst< Impl >::initVars(), BaseDynInst< Impl >::markSrcRegReady(), BaseDynInst< Impl >::~BaseDynInst(), and BaseO3DynInst< Impl >::~BaseO3DynInst().
sqIdx
template<class Impl > int16_t BaseDynInst< Impl >::sqIdx
Store queue index.
Definition at line 234 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars().
sqIt
template<class Impl > SQIterator BaseDynInst< Impl >::sqIt
Definition at line 235 of file base_dyn_inst.hh.
staticInst
template<class Impl > const StaticInstPtr BaseDynInst< Impl >::staticInst
The StaticInst used by this BaseDynInst.
Definition at line 154 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc(), BaseDynInst< Impl >::dump(), BaseO3DynInst< Impl >::execute(), BaseO3DynInst< Impl >::forwardOldRegs(), BaseO3DynInst< Impl >::initiateAcc(), BaseO3DynInst< Impl >::trap(), and BaseO3DynInst< Impl >::~BaseO3DynInst().
status
template<class Impl > std::bitset<NumStatus> BaseDynInst< Impl >::status private
The status of this BaseDynInst.
Several bits can be set.
Definition at line 184 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::initVars(), and BaseDynInst< Impl >::setSquashed().
thread
template<class Impl > ImplState* BaseDynInst< Impl >::thread
Pointer to the thread state.
Definition at line 162 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc(), BaseO3DynInst< Impl >::execute(), BaseO3DynInst< Impl >::initiateAcc(), and BaseO3DynInst< Impl >::updateMiscRegs().
threadNumber
template<class Impl > ThreadID BaseDynInst< Impl >::threadNumber
The thread this instruction is from.
Definition at line 194 of file base_dyn_inst.hh.
Referenced by BaseDynInst< Impl >::dump(), BaseDynInst< Impl >::initVars(), BaseO3DynInst< Impl >::readMiscReg(), BaseO3DynInst< Impl >::readMiscRegOperand(), BaseO3DynInst< Impl >::syscall(), and BaseO3DynInst< Impl >::trap().
traceData
template<class Impl > Trace::InstRecord* BaseDynInst< Impl >::traceData
InstRecord that tracks this instructions.
Definition at line 168 of file base_dyn_inst.hh.
Referenced by BaseO3DynInst< Impl >::completeAcc(), BaseO3DynInst< Impl >::execute(), BaseO3DynInst< Impl >::initiateAcc(), and BaseDynInst< Impl >::~BaseDynInst().
The documentation for this class was generated from the following files:
cpu/base_dyn_inst.hh
cpu/base_dyn_inst_impl.hh