gem5: AlphaISA::AlphaFault Class Reference
AlphaISA::AlphaFault Class Reference abstract
#include <faults.hh>
Public Member Functions
virtual ~AlphaFault ()
void invoke (ThreadContext *tc, const StaticInstPtr &inst=StaticInst::nullStaticInstPtr)
virtual FaultVect vect ()=0
virtual FaultStat & countStat ()=0
Public Member Functions inherited from FaultBase
virtual FaultName name () const =0
virtual ~FaultBase ()
Protected Member Functions
virtual bool skipFaultingInstruction ()
virtual bool setRestartAddress ()
Detailed Description
Definition at line 45 of file faults.hh.
Constructor & Destructor Documentation
~AlphaFault()
virtual AlphaISA::AlphaFault::~AlphaFault () inline virtual
Definition at line 51 of file faults.hh.
References countStat(), invoke(), StaticInst::nullStaticInstPtr, and vect().
Member Function Documentation
countStat()
virtual FaultStat& AlphaISA::AlphaFault::countStat () pure virtual
Implemented in AlphaISA::IntegerOverflowFault, AlphaISA::PalFault, AlphaISA::VectorEnableFault, AlphaISA::FloatEnableFault, AlphaISA::UnimplementedOpcodeFault, AlphaISA::ItbAcvFault, AlphaISA::ItbPageFault, AlphaISA::ItbFault, AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, AlphaISA::NDtbMissFault, AlphaISA::DtbFault, AlphaISA::InterruptFault, AlphaISA::ArithmeticFault, AlphaISA::ResetFault, AlphaISA::AlignmentFault, and AlphaISA::MachineCheckFault.
Referenced by AlphaISA::DtbFault::DtbFault(), invoke(), AlphaISA::ItbFault::ItbFault(), and ~AlphaFault().
invoke()
void AlphaISA::AlphaFault::invoke (ThreadContext * tc, const StaticInstPtr & inst = StaticInst::nullStaticInstPtr) virtual
Reimplemented from FaultBase.
Reimplemented in AlphaISA::ItbPageFault, AlphaISA::ItbFault, AlphaISA::NDtbMissFault, AlphaISA::DtbFault, and AlphaISA::ArithmeticFault.
Definition at line 117 of file faults.cc.
References countStat(), FullSystem, FaultBase::invoke(), AlphaISA::IPR_EXC_ADDR, AlphaISA::IPR_PAL_BASE, GenericISA::SimplePCState< MachInst >::pc(), MipsISA::pc, ThreadContext::pcState(), ThreadContext::readMiscRegNoEffect(), GenericISA::SimplePCState< MachInst >::set(), ThreadContext::setMiscRegNoEffect(), setRestartAddress(), skipFaultingInstruction(), and vect().
Referenced by AlphaISA::ArithmeticFault::countStat(), AlphaISA::NDtbMissFault::countStat(), AlphaISA::ItbPageFault::countStat(), AlphaISA::DtbFault::DtbFault(), AlphaISA::DtbFault::invoke(), AlphaISA::ItbFault::invoke(), AlphaISA::ItbFault::ItbFault(), and ~AlphaFault().
setRestartAddress()
virtual bool AlphaISA::AlphaFault::setRestartAddress () inline protected virtual
Reimplemented in AlphaISA::InterruptFault.
Definition at line 49 of file faults.hh.
Referenced by invoke().
skipFaultingInstruction()
virtual bool AlphaISA::AlphaFault::skipFaultingInstruction () inline protected virtual
Reimplemented in AlphaISA::PalFault, and AlphaISA::ArithmeticFault.
Definition at line 48 of file faults.hh.
Referenced by invoke().
vect()
virtual FaultVect AlphaISA::AlphaFault::vect () pure virtual
Implemented in AlphaISA::IntegerOverflowFault, AlphaISA::PalFault, AlphaISA::VectorEnableFault, AlphaISA::FloatEnableFault, AlphaISA::UnimplementedOpcodeFault, AlphaISA::ItbAcvFault, AlphaISA::ItbPageFault, AlphaISA::ItbFault, AlphaISA::DtbAlignmentFault, AlphaISA::DtbAcvFault, AlphaISA::DtbPageFault, AlphaISA::PDtbMissFault, AlphaISA::NDtbMissFault, AlphaISA::DtbFault, AlphaISA::InterruptFault, AlphaISA::ArithmeticFault, AlphaISA::ResetFault, AlphaISA::AlignmentFault, and AlphaISA::MachineCheckFault.
Referenced by AlphaISA::DtbFault::DtbFault(), AlphaISA::initCPU(), invoke(), AlphaISA::ItbFault::ItbFault(), and ~AlphaFault().
The documentation for this class was generated from the following files:
arch/alpha/faults.hh
arch/alpha/faults.cc