gem5: DRAMPower Class Reference
DRAMPower Class Reference
DRAMPower is a standalone tool which calculates the power consumed by a DRAM in the system.
#include <drampower.hh>
Public Member Functions
DRAMPower (const DRAMCtrlParams *p, bool include_io)
Public Attributes
libDRAMPower powerlib
Static Private Member Functions
static Data::MemArchitectureSpec getArchParams (const DRAMCtrlParams *p)
Transform the architechture parameters defined in DRAMCtrlParams to the memSpec of DRAMPower.
static Data::MemTimingSpec getTimingParams (const DRAMCtrlParams *p)
Transforms the timing parameters defined in DRAMCtrlParams to the memSpec of DRAMPower.
static Data::MemPowerSpec getPowerParams (const DRAMCtrlParams *p)
Transforms the power and current parameters defined in DRAMCtrlParam to the memSpec of DRAMPower.
static uint8_t getDataRate (const DRAMCtrlParams *p)
Determine data rate, either one or two.
static bool hasTwoVDD (const DRAMCtrlParams *p)
Determine if DRAM has two voltage domains (or one)
static Data::MemorySpecification getMemSpec (const DRAMCtrlParams *p)
Return an instance of MemSpec based on the DRAMCtrlParams.
Detailed Description
DRAMPower is a standalone tool which calculates the power consumed by a DRAM in the system.
This class wraps the DRAMPower library.
Definition at line 55 of file drampower.hh.
Constructor & Destructor Documentation
DRAMPower()
DRAMPower::DRAMPower (const DRAMCtrlParams * p, bool include_io)
Definition at line 45 of file drampower.cc.
Member Function Documentation
getArchParams()
Data::MemArchitectureSpec DRAMPower::getArchParams (const DRAMCtrlParams * p) static private
Transform the architechture parameters defined in DRAMCtrlParams to the memSpec of DRAMPower.
Definition at line 51 of file drampower.cc.
References getDataRate(), and hasTwoVDD().
Referenced by getMemSpec().
getDataRate()
uint8_t DRAMPower::getDataRate (const DRAMCtrlParams * p) static private
Determine data rate, either one or two.
Definition at line 153 of file drampower.cc.
References divCeil(), and fatal.
Referenced by getArchParams().
getMemSpec()
Data::MemorySpecification DRAMPower::getMemSpec (const DRAMCtrlParams * p) static private
Return an instance of MemSpec based on the DRAMCtrlParams.
Definition at line 137 of file drampower.cc.
References getArchParams(), getPowerParams(), and getTimingParams().
getPowerParams()
Data::MemPowerSpec DRAMPower::getPowerParams (const DRAMCtrlParams * p) static private
Transforms the power and current parameters defined in DRAMCtrlParam to the memSpec of DRAMPower.
Definition at line 105 of file drampower.cc.
Referenced by getMemSpec().
getTimingParams()
Data::MemTimingSpec DRAMPower::getTimingParams (const DRAMCtrlParams * p) static private
Transforms the timing parameters defined in DRAMCtrlParams to the memSpec of DRAMPower.
Definition at line 73 of file drampower.cc.
References divCeil(), and SimClock::Int::ns.
Referenced by getMemSpec().
hasTwoVDD()
bool DRAMPower::hasTwoVDD (const DRAMCtrlParams * p) static private
Determine if DRAM has two voltage domains (or one)
Definition at line 147 of file drampower.cc.
Referenced by getArchParams().
Member Data Documentation
powerlib
libDRAMPower DRAMPower::powerlib
Definition at line 96 of file drampower.hh.
Referenced by DRAMCtrl::Rank::flushCmdList(), DRAMCtrl::Rank::resetStats(), and DRAMCtrl::Rank::updatePowerStats().
The documentation for this class was generated from the following files:
mem/drampower.hh
mem/drampower.cc