gem5: SparcISA::Interrupts Class Reference
SparcISA::Interrupts Class Reference
#include <interrupts.hh>
Public Types
typedef SparcInterruptsParams Params
Public Types inherited from BaseInterrupts
typedef BaseInterruptsParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void setCPU (BaseCPU *_cpu)
const Params * params () const
Interrupts (Params *p)
int InterruptLevel (uint64_t softint)
void post (int int_num, int index)
void clear (int int_num, int index)
void clearAll ()
bool checkInterrupts (ThreadContext *tc) const
Fault getInterrupt (ThreadContext *tc)
void updateIntrInfo (ThreadContext *tc)
uint64_t get_vec (int int_num)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from BaseInterrupts
BaseInterrupts (Params *p)
const Params * params () const
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Attributes
BaseCPU * cpu
uint64_t interrupts [NumInterruptTypes]
uint64_t intStatus
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from BaseInterrupts
BaseCPU * cpu
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 59 of file interrupts.hh.
Member Typedef Documentation
Params
typedef SparcInterruptsParams SparcISA::Interrupts::Params
Definition at line 75 of file interrupts.hh.
Constructor & Destructor Documentation
Interrupts()
SparcISA::Interrupts::Interrupts (Params * p) inline
Definition at line 83 of file interrupts.hh.
References clearAll().
Member Function Documentation
checkInterrupts()
bool SparcISA::Interrupts::checkInterrupts (ThreadContext * tc) const inline virtual
Implements BaseInterrupts.
Definition at line 135 of file interrupts.hh.
References SparcISA::IT_CPU_MONDO, SparcISA::IT_DEV_MONDO, SparcISA::IT_HINTP, SparcISA::IT_INT_VEC, SparcISA::IT_RES_ERROR, SparcISA::IT_SOFT_INT, SparcISA::IT_TRAP_LEVEL_ZERO, SparcISA::MISCREG_HPSTATE, SparcISA::MISCREG_PSTATE, and ThreadContext::readMiscRegNoEffect().
Referenced by getInterrupt().
clear()
void SparcISA::Interrupts::clear (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 114 of file interrupts.hh.
References DPRINTF, MipsISA::index, SparcISA::NumInterruptTypes, and ULL.
clearAll()
void SparcISA::Interrupts::clearAll () inline virtual
Reimplemented from BaseInterrupts.
Definition at line 126 of file interrupts.hh.
References ArmISA::i, and SparcISA::NumInterruptTypes.
Referenced by Interrupts().
get_vec()
uint64_t SparcISA::Interrupts::get_vec (int int_num) inline
Definition at line 254 of file interrupts.hh.
References SparcISA::NumInterruptTypes.
Referenced by SparcISA::TLB::doMmuRegRead(), and SparcISA::TLB::doMmuRegWrite().
getInterrupt()
Fault SparcISA::Interrupts::getInterrupt (ThreadContext * tc) inline virtual
Implements BaseInterrupts.
Definition at line 193 of file interrupts.hh.
References checkInterrupts(), InterruptLevel(), SparcISA::IT_CPU_MONDO, SparcISA::IT_DEV_MONDO, SparcISA::IT_HINTP, SparcISA::IT_INT_VEC, SparcISA::IT_RES_ERROR, SparcISA::IT_SOFT_INT, SparcISA::IT_TRAP_LEVEL_ZERO, X86ISA::level, SparcISA::MISCREG_HPSTATE, SparcISA::MISCREG_PSTATE, NoFault, and ThreadContext::readMiscRegNoEffect().
InterruptLevel()
int SparcISA::Interrupts::InterruptLevel (uint64_t softint) inline
Definition at line 89 of file interrupts.hh.
References X86ISA::level.
Referenced by getInterrupt().
params()
const Params* SparcISA::Interrupts::params () const inline
Definition at line 78 of file interrupts.hh.
References SimObject::_params.
post()
void SparcISA::Interrupts::post (int int_num, int index) inline virtual
Reimplemented from BaseInterrupts.
Definition at line 103 of file interrupts.hh.
References DPRINTF, MipsISA::index, SparcISA::NumInterruptTypes, and ULL.
serialize()
void SparcISA::Interrupts::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 261 of file interrupts.hh.
References SparcISA::NumInterruptTypes, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
setCPU()
void SparcISA::Interrupts::setCPU (BaseCPU * _cpu) inline virtual
Implements BaseInterrupts.
Definition at line 70 of file interrupts.hh.
unserialize()
void SparcISA::Interrupts::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 268 of file interrupts.hh.
References SparcISA::NumInterruptTypes, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
updateIntrInfo()
void SparcISA::Interrupts::updateIntrInfo (ThreadContext * tc) inline virtual
Implements BaseInterrupts.
Definition at line 250 of file interrupts.hh.
Member Data Documentation
cpu
BaseCPU* SparcISA::Interrupts::cpu private
Definition at line 62 of file interrupts.hh.
interrupts
uint64_t SparcISA::Interrupts::interrupts[NumInterruptTypes] private
Definition at line 64 of file interrupts.hh.
intStatus
uint64_t SparcISA::Interrupts::intStatus private
Definition at line 65 of file interrupts.hh.
The documentation for this class was generated from the following file:
arch/sparc/interrupts.hh