gem5: ArmISA::RemoteGDB::AArch32GdbRegCache Class Reference
ArmISA::RemoteGDB::AArch32GdbRegCache Class Reference
#include <remote_gdb.hh>
Public Member Functions
char * data () const
Return the pointer to the raw bytes buffer containing the register values.
size_t size () const
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
void getRegs (ThreadContext *)
Fill the raw buffer from the registers in the ThreadContext.
void setRegs (ThreadContext *) const
Set the ThreadContext's registers from the values in the raw buffer.
const std::string name () const
Return the name to use in places like DPRINTF.
Public Member Functions inherited from BaseGdbRegCache
BaseGdbRegCache (BaseRemoteGDB *g)
virtual ~BaseGdbRegCache ()
Private Attributes
struct {
uint32_t gpr [16]
uint32_t cpsr
uint64_t fpr [32]
uint32_t fpscr
} r
Additional Inherited Members
Protected Attributes inherited from BaseGdbRegCache
BaseRemoteGDB * gdb
Detailed Description
Definition at line 69 of file remote_gdb.hh.
Member Function Documentation
data()
char* ArmISA::RemoteGDB::AArch32GdbRegCache::data () const inline virtual
Return the pointer to the raw bytes buffer containing the register values.
Each byte of this buffer is literally encoded as two hex digits in the g or G RSP packet.
Implements BaseGdbRegCache.
Definition at line 80 of file remote_gdb.hh.
References r.
getRegs()
void RemoteGDB::AArch32GdbRegCache::getRegs (ThreadContext *) virtual
Fill the raw buffer from the registers in the ThreadContext.
Implements BaseGdbRegCache.
Definition at line 254 of file remote_gdb.cc.
References DPRINTF, ArmISA::i, ArmISA::INTREG_LR, ArmISA::INTREG_R0, ArmISA::INTREG_R1, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R2, ArmISA::INTREG_R3, ArmISA::INTREG_R4, ArmISA::INTREG_R5, ArmISA::INTREG_R6, ArmISA::INTREG_R7, ArmISA::INTREG_R8, ArmISA::INTREG_R9, ArmISA::INTREG_SP, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPSCR, ThreadContext::pcState(), MipsISA::r, ThreadContext::readIntReg(), and ThreadContext::readMiscRegNoEffect().
Referenced by size(), and ArmISA::RemoteGDB::AArch64GdbRegCache::size().
name()
const std::string ArmISA::RemoteGDB::AArch32GdbRegCache::name () const inline virtual
Return the name to use in places like DPRINTF.
Having each concrete superclass redefine this member is useful in situations where the class of the regCache can change on the fly.
Implements BaseGdbRegCache.
Definition at line 85 of file remote_gdb.hh.
References BaseGdbRegCache::gdb, and BaseRemoteGDB::name().
setRegs()
void RemoteGDB::AArch32GdbRegCache::setRegs (ThreadContext *) const virtual
Set the ThreadContext's registers from the values in the raw buffer.
Implements BaseGdbRegCache.
Definition at line 284 of file remote_gdb.cc.
References DPRINTF, ArmISA::INTREG_LR, ArmISA::INTREG_R0, ArmISA::INTREG_R1, ArmISA::INTREG_R10, ArmISA::INTREG_R11, ArmISA::INTREG_R12, ArmISA::INTREG_R2, ArmISA::INTREG_R3, ArmISA::INTREG_R4, ArmISA::INTREG_R5, ArmISA::INTREG_R6, ArmISA::INTREG_R7, ArmISA::INTREG_R8, ArmISA::INTREG_R9, ArmISA::INTREG_SP, ArmISA::MISCREG_CPSR, ArmISA::MISCREG_FPSCR, ThreadContext::pcState(), MipsISA::r, ThreadContext::setIntReg(), ThreadContext::setMiscReg(), and ThreadContext::setMiscRegNoEffect().
Referenced by size(), and ArmISA::RemoteGDB::AArch64GdbRegCache::size().
size()
size_t ArmISA::RemoteGDB::AArch32GdbRegCache::size () const inline virtual
Return the size of the raw buffer, in bytes (i.e., half of the number of digits in the g/G packet).
Implements BaseGdbRegCache.
Definition at line 81 of file remote_gdb.hh.
References getRegs(), r, and setRegs().
Member Data Documentation
cpsr
uint32_t ArmISA::RemoteGDB::AArch32GdbRegCache::cpsr
Definition at line 75 of file remote_gdb.hh.
fpr
uint64_t ArmISA::RemoteGDB::AArch32GdbRegCache::fpr[32]
Definition at line 76 of file remote_gdb.hh.
fpscr
uint32_t ArmISA::RemoteGDB::AArch32GdbRegCache::fpscr
Definition at line 77 of file remote_gdb.hh.
gpr
uint32_t ArmISA::RemoteGDB::AArch32GdbRegCache::gpr[16]
Definition at line 74 of file remote_gdb.hh.
r
struct { ... } ArmISA::RemoteGDB::AArch32GdbRegCache::r
Referenced by data(), ArmISA::RemoteGDB::AArch64GdbRegCache::data(), size(), and ArmISA::RemoteGDB::AArch64GdbRegCache::size().
The documentation for this class was generated from the following files:
arch/arm/remote_gdb.hh
arch/arm/remote_gdb.cc