gem5: MasterPort Class Reference
MasterPort Class Reference
A MasterPort is a specialisation of a BaseMasterPort, which implements the default protocol for the three different level of transport functions.
#include <port.hh>
Public Member Functions
MasterPort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Master port.
virtual ~MasterPort ()
void bind (Port &peer) override
Bind this master port to a slave port.
void unbind () override
Unbind this master port and the associated slave port.
virtual bool isSnooping () const
Determine if this master port is snooping or not.
AddrRangeList getAddrRanges () const
Get the address ranges of the connected slave port.
void printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
Tick sendAtomic (PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
void sendFunctional (PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingReq (PacketPtr pkt)
Attempt to send a timing request to the slave port by calling its corresponding receive function.
bool tryTiming (PacketPtr pkt) const
Check if the slave can handle a timing request.
bool sendTimingSnoopResp (PacketPtr pkt)
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
virtual void sendRetryResp ()
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
virtual void recvRangeChange ()
Called to receive an address range change from the peer slave port.
Tick recvAtomicSnoop (PacketPtr pkt) override
Default implementations.
void recvFunctionalSnoop (PacketPtr pkt) override
Receive a functional snoop request packet from the peer.
void recvTimingSnoopReq (PacketPtr pkt) override
Receive a timing snoop request from the peer.
void recvRetrySnoopResp () override
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicRequestProtocol
Tick send (AtomicResponseProtocol *peer, PacketPtr pkt)
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Tick sendBackdoor (AtomicResponseProtocol *peer, PacketPtr pkt, MemBackdoorPtr &backdoor)
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Protected Member Functions inherited from TimingRequestProtocol
bool sendReq (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing request to the peer by calling its corresponding receive function.
bool trySend (TimingResponseProtocol *peer, PacketPtr pkt) const
Check if the peer can handle a timing request.
bool sendSnoopResp (TimingResponseProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop response packet to it's peer by calling its corresponding receive function.
void sendRetryResp (TimingResponseProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingResp to this protocol and failed.
virtual bool recvTimingResp (PacketPtr pkt)=0
Receive a timing response from the peer.
virtual void recvReqRetry ()=0
Called by the peer if sendTimingReq was called on this peer (causing recvTimingReq to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from FunctionalRequestProtocol
void send (FunctionalResponseProtocol *peer, PacketPtr pkt) const
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Protected Attributes
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Private Attributes
SlavePort * _slavePort
Friends
class SlavePort
Detailed Description
A MasterPort is a specialisation of a BaseMasterPort, which implements the default protocol for the three different level of transport functions.
In addition to the basic functionality of sending packets, it also has functions to receive range changes or determine if the port is snooping or not.
The three protocols are atomic, timing, and functional, each with its own header file.
Definition at line 75 of file port.hh.
Constructor & Destructor Documentation
MasterPort()
MasterPort::MasterPort (const std::string & name, SimObject * _owner, PortID id = InvalidPortID)
Master port.
Definition at line 57 of file port.cc.
~MasterPort()
MasterPort::~MasterPort () virtual
Definition at line 62 of file port.cc.
Member Function Documentation
bind()
void MasterPort::bind (Port & peer) override virtual
Bind this master port to a slave port.
This also does the mirror action and binds the slave port to the master port.
Reimplemented from Port.
Definition at line 67 of file port.cc.
References _slavePort, Port::bind(), fatal, and Port::name().
getAddrRanges()
AddrRangeList MasterPort::getAddrRanges () const
Get the address ranges of the connected slave port.
Definition at line 93 of file port.cc.
References _slavePort, and SlavePort::getAddrRanges().
Referenced by MemDelay::SlavePort::getAddrRanges(), SimpleMemobj::getAddrRanges(), MemCheckerMonitor::getAddrRanges(), SimpleCache::getAddrRanges(), CommMonitor::getAddrRanges(), isSnooping(), RubyPort::PioSlavePort::recvFunctional(), and SlavePort::sendRangeChange().
isSnooping()
virtual bool MasterPort::isSnooping () const inline virtual
Determine if this master port is snooping or not.
The default implementation returns false and thus tells the neighbour we are not snooping. Any master port that wants to receive snoop requests (e.g. a cache connected to a bus) has to override this function.
Returns
true if the port should be considered a snooper
Reimplemented in TraceCPU::DcachePort, TimingSimpleCPU::DcachePort, CoherentXBar::CoherentXBarMasterPort, LSQ< Impl >::DcachePort, CommMonitor::MonitorMasterPort, BaseCache::CacheMasterPort, AtomicSimpleCPU::AtomicCPUDPort, AddrMapper::MapperMasterPort, MemCheckerMonitor::MonitorMasterPort, Minor::LSQ::DcachePort, and MemDelay::MasterPort.
Definition at line 111 of file port.hh.
References ArmISA::a, getAddrRanges(), printAddr(), sendAtomic(), sendAtomicBackdoor(), sendFunctional(), sendRetryResp(), sendTimingReq(), sendTimingSnoopResp(), and tryTiming().
Referenced by SlavePort::isSnooping().
printAddr()
void MasterPort::printAddr (Addr a)
Inject a PrintReq for the given address to print the state of that address throughout the memory system.
For debugging.
Definition at line 99 of file port.cc.
References ArmISA::a, Request::funcMasterId, MemCmd::PrintReq, and sendFunctional().
Referenced by AtomicSimpleCPU::getInstPort(), isSnooping(), GarnetSyntheticTraffic::printAddr(), AtomicSimpleCPU::printAddr(), and TimingSimpleCPU::printAddr().
recvAtomicSnoop()
Tick MasterPort::recvAtomicSnoop (PacketPtr pkt) inline override protected virtual
Default implementations.
Implements AtomicRequestProtocol.
Definition at line 224 of file port.hh.
References Port::name(), and panic.
Referenced by BaseCache::allocOnFill().
recvFunctionalSnoop()
void MasterPort::recvFunctionalSnoop (PacketPtr pkt) inline override protected virtual
Receive a functional snoop request packet from the peer.
Implements FunctionalRequestProtocol.
Definition at line 231 of file port.hh.
References Port::name(), and panic.
recvRangeChange()
virtual void MasterPort::recvRangeChange () inline protected virtual
Called to receive an address range change from the peer slave port.
The default implementation ignores the change and does nothing. Override this function in a derived class if the owner needs to be aware of the address ranges, e.g. in an interconnect component like a bus.
Reimplemented in ComputeUnit::LDSPort, ComputeUnit::ITLBPort, ComputeUnit::DTLBPort, ComputeUnit::SQCPort, ComputeUnit::DataPort, X86ISA::GpuTLB::MemSidePort, CoherentXBar::CoherentXBarMasterPort, TLBCoalescer::MemSidePort, SimpleCache::MemSidePort, SimpleMemobj::MemSidePort, NoncoherentXBar::NoncoherentXBarMasterPort, CommMonitor::MonitorMasterPort, GpuDispatcher::TLBPort, AddrMapper::MapperMasterPort, MemCheckerMonitor::MonitorMasterPort, RubyPort::PioMasterPort, sc_gem5::TlmToGem5Bridge< BITWIDTH >::BridgeMasterPort, MemDelay::MasterPort, and RubyPort::MemMasterPort.
Definition at line 218 of file port.hh.
Referenced by SlavePort::sendRangeChange().
recvRetrySnoopResp()
void MasterPort::recvRetrySnoopResp () inline override protected virtual
Called by the peer if sendTimingSnoopResp was called on this protocol (causing recvTimingSnoopResp to be called on the peer) and was unsuccessful.
Implements TimingRequestProtocol.
Reimplemented in QueuedMasterPort.
Definition at line 243 of file port.hh.
References Port::name(), and panic.
recvTimingSnoopReq()
void MasterPort::recvTimingSnoopReq (PacketPtr pkt) inline override protected virtual
Receive a timing snoop request from the peer.
Implements TimingRequestProtocol.
Definition at line 237 of file port.hh.
References Port::name(), and panic.
Referenced by BaseCache::allocOnFill().
sendAtomic()
Tick MasterPort::sendAtomic (PacketPtr pkt) inline
Send an atomic request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Parameters
pkt Packet to send.
Returns
Estimated latency of access.
Definition at line 427 of file port.hh.
References _slavePort, and AtomicRequestProtocol::send().
Referenced by NoncoherentCache::doWritebacksAtomic(), Cache::doWritebacksAtomic(), NoncoherentCache::handleAtomicReqMiss(), Cache::handleAtomicReqMiss(), isSnooping(), ArmISA::Stage2MMU::readDataUntimed(), RubyPort::MemSlavePort::recvAtomic(), MemDelay::SlavePort::recvAtomic(), Cache::recvAtomic(), AbstractController::recvAtomic(), SerialLink::SerialLinkSlavePort::recvAtomic(), Bridge::BridgeSlavePort::recvAtomic(), AddrMapper::recvAtomic(), CommMonitor::recvAtomic(), BaseCache::CpuSidePort::recvAtomic(), SMMUv3::runProcessAtomic(), Gicv3Its::runProcessAtomic(), NonCachingSimpleCPU::sendPacket(), and AtomicSimpleCPU::sendPacket().
sendAtomicBackdoor()
Tick MasterPort::sendAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr & backdoor) inline
Send an atomic request packet like above, but also request a backdoor to the data being accessed.
Parameters
pkt Packet to send.
backdoor Can be set to a back door pointer by the target to let caller have direct access to the requested data.
Returns
Estimated latency of access.
Definition at line 433 of file port.hh.
References _slavePort, and AtomicRequestProtocol::sendBackdoor().
Referenced by isSnooping().
sendFunctional()
void MasterPort::sendFunctional (PacketPtr pkt) const inline
Send a functional request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Parameters
pkt Packet to send.
Definition at line 439 of file port.hh.
References _slavePort, and FunctionalRequestProtocol::send().
Referenced by FetchUnit::fetch(), ArmISA::TableWalker::fetchDescriptor(), BaseCache::functionalAccess(), AbstractController::functionalMemoryRead(), AbstractController::functionalMemoryWrite(), Shader::functionalTLBAccess(), SimpleMemobj::handleFunctional(), SimpleCache::handleFunctional(), FetchUnit::initiateFetch(), isSnooping(), PortProxy::PortProxy(), printAddr(), AbstractController::queueMemoryRead(), AbstractController::queueMemoryWrite(), ArmISA::Stage2MMU::readDataUntimed(), CheckerCPU::readMem(), MemDelay::SlavePort::recvFunctional(), SerialLink::SerialLinkSlavePort::recvFunctional(), MemCheckerMonitor::recvFunctional(), AddrMapper::recvFunctional(), Bridge::BridgeSlavePort::recvFunctional(), CommMonitor::recvFunctional(), BaseCache::CpuSidePort::recvFunctional(), MemTest::tick(), and BaseCache::writebackVisitor().
sendRetryResp()
void MasterPort::sendRetryResp () inline virtual
Send a retry to the slave port that previously attempted a sendTimingResp to this master port and failed.
Note that this is virtual so that the "fake" snoop response port in the coherent crossbar can override the behaviour.
Reimplemented in CoherentXBar::SnoopRespPort.
Definition at line 463 of file port.hh.
References _slavePort, and TimingRequestProtocol::sendRetryResp().
Referenced by isSnooping(), MemCheckerMonitor::recvRespRetry(), AddrMapper::recvRespRetry(), CommMonitor::recvRespRetry(), and BaseXBar::RespLayer::sendRetry().
sendTimingReq()
bool MasterPort::sendTimingReq (PacketPtr pkt) inline
Attempt to send a timing request to the slave port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvReqRetry at which point it can re-issue a sendTimingReq.
Parameters
pkt Packet to send.
Returns
If the send was succesful or not.
Definition at line 445 of file port.hh.
References _slavePort, and TimingRequestProtocol::sendReq().
Referenced by GarnetSyntheticTraffic::doRetry(), FetchUnit::fetch(), DefaultFetch< Impl >::finishTranslation(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), SeriesRequestGenerator::initiate(), InvalidateGenerator::initiate(), Check::initiateAction(), Check::initiateCheck(), FetchUnit::initiateFetch(), Check::initiateFlush(), Check::initiatePrefetch(), isSnooping(), SMMUv3::masterRecvReqRetry(), SMMUv3::masterTableWalkRecvReqRetry(), Gicv3Its::recvReqRetry(), DefaultFetch< Impl >::recvReqRetry(), ComputeUnit::LDSPort::recvReqRetry(), MemTest::recvRetry(), Cache::recvTimingReq(), MemCheckerMonitor::recvTimingReq(), AddrMapper::recvTimingReq(), CommMonitor::recvTimingReq(), BaseCache::CpuSidePort::recvTimingReq(), BaseTrafficGen::retryReq(), SMMUv3::runProcessTiming(), Gicv3Its::runProcessTiming(), TraceCPU::FixedRetryGen::send(), TimingSimpleCPU::sendFetch(), BaseCache::sendMSHRQueuePacket(), X86ISA::Walker::sendTiming(), ReqPacketQueue::sendTiming(), ComputeUnit::LDSPort::sendTimingReq(), BaseCache::sendWriteQueuePacket(), TraceCPU::FixedRetryGen::tryNext(), LSQUnit< Impl >::trySendPacket(), Minor::Fetch1::tryToSend(), Minor::LSQ::tryToSend(), and BaseTrafficGen::update().
sendTimingSnoopResp()
bool MasterPort::sendTimingSnoopResp (PacketPtr pkt) inline
Attempt to send a timing snoop response packet to the slave port by calling its corresponding receive function.
If the send does not succeed, as indicated by the return value, then the sender must wait for a recvRetrySnoop at which point it can re-issue a sendTimingSnoopResp.
Parameters
pkt Packet to send.
Definition at line 457 of file port.hh.
References _slavePort, and TimingRequestProtocol::sendSnoopResp().
Referenced by isSnooping(), MemCheckerMonitor::recvTimingSnoopResp(), AddrMapper::recvTimingSnoopResp(), CommMonitor::recvTimingSnoopResp(), and SnoopRespPacketQueue::sendTiming().
tryTiming()
bool MasterPort::tryTiming (PacketPtr pkt) const inline
Check if the slave can handle a timing request.
If the send cannot be handled at the moment, as indicated by the return value, then the sender will receive a recvReqRetry at which point it can re-issue a sendTimingReq.
Parameters
pkt Packet to send.
Returns
If the send was succesful or not.
Definition at line 451 of file port.hh.
References _slavePort, and TimingRequestProtocol::trySend().
Referenced by isSnooping(), and CommMonitor::tryTiming().
unbind()
void MasterPort::unbind () override virtual
Unbind this master port and the associated slave port.
Reimplemented from Port.
Definition at line 82 of file port.cc.
References _slavePort, Port::name(), panic, SlavePort::slaveUnbind(), and Port::unbind().
Friends And Related Function Documentation
SlavePort
friend class SlavePort friend
Definition at line 78 of file port.hh.
Member Data Documentation
_slavePort
SlavePort* MasterPort::_slavePort private
Definition at line 81 of file port.hh.
Referenced by bind(), getAddrRanges(), sendAtomic(), sendAtomicBackdoor(), sendFunctional(), sendRetryResp(), sendTimingReq(), sendTimingSnoopResp(), tryTiming(), and unbind().
owner
SimObject& MasterPort::owner protected
Definition at line 84 of file port.hh.
The documentation for this class was generated from the following files:
mem/port.hh
mem/port.cc