gem5: DistIface::SyncSwitch Class Reference
DistIface::SyncSwitch Class Reference
Public Member Functions
SyncSwitch (int num_nodes)
~SyncSwitch ()
bool run (bool same_tick) override
Core method to perform a full dist sync.
bool progress (Tick max_req_tick, Tick next_repeat, ReqType do_ckpt, ReqType do_exit, ReqType do_stop_sync) override
Callback when the receiver thread gets a sync ack message.
void requestCkpt (ReqType) override
void requestExit (ReqType) override
void requestStopSync (ReqType) override
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from DistIface::Sync
void init (Tick start, Tick repeat)
Initialize periodic sync params.
void abort ()
Abort processing an on-going sync event (in case of an error, e.g.
void drainComplete ()
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Private Attributes
unsigned numExitReq
Counter for recording exit requests.
unsigned numCkptReq
Counter for recording ckpt requests.
unsigned numStopSyncReq
Counter for recording stop sync requests.
unsigned numNodes
Number of connected simulated nodes.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from DistIface::Sync
std::mutex lock
The lock to protect access to the Sync object.
std::condition_variable cv
Condition variable for the simulation thread to wait on until all receiver threads completes the current global synchronisation.
unsigned waitNum
Number of receiver threads that not yet completed the current global synchronisation.
bool doExit
Flag is set if exit is permitted upon sync completion.
bool doCkpt
Flag is set if taking a ckpt is permitted upon sync completion.
bool doStopSync
Flag is set if sync is to stop upon sync completion.
Tick nextRepeat
The repeat value for the next periodic sync.
Tick nextAt
Tick for the next periodic sync (if the event is not scheduled yet)
bool isAbort
Flag is set if the sync is aborted (e.g.
Detailed Description
Definition at line 240 of file dist_iface.hh.
Constructor & Destructor Documentation
SyncSwitch()
DistIface::SyncSwitch::SyncSwitch (int num_nodes)
Definition at line 96 of file dist_iface.cc.
~SyncSwitch()
DistIface::SyncSwitch::~SyncSwitch () inline
Definition at line 262 of file dist_iface.hh.
References DistIface::Sync::progress(), and DistIface::Sync::run().
Member Function Documentation
progress()
bool DistIface::SyncSwitch::progress (Tick send_tick, Tick next_repeat, ReqType do_ckpt, ReqType do_exit, ReqType do_stop_sync) override virtual
Callback when the receiver thread gets a sync ack message.
Returns
false if the receiver thread needs to stop (e.g. simulation is to exit)
Implements DistIface::Sync.
Definition at line 201 of file dist_iface.cc.
References X86ISA::lock.
requestCkpt()
void DistIface::SyncSwitch::requestCkpt (ReqType) inline override virtual
Implements DistIface::Sync.
Definition at line 271 of file dist_iface.hh.
References panic.
requestExit()
void DistIface::SyncSwitch::requestExit (ReqType) inline override virtual
Implements DistIface::Sync.
Definition at line 274 of file dist_iface.hh.
References panic.
requestStopSync()
void DistIface::SyncSwitch::requestStopSync (ReqType) inline override virtual
Implements DistIface::Sync.
Definition at line 277 of file dist_iface.hh.
References panic, DistIface::Sync::serialize(), and DistIface::Sync::unserialize().
run()
bool DistIface::SyncSwitch::run (bool same_tick) override virtual
Core method to perform a full dist sync.
Returns
true if the sync completes, false if it gets aborted
Implements DistIface::Sync.
Definition at line 158 of file dist_iface.cc.
References curTick(), header, X86ISA::lock, DistHeaderPkt::Header::msgType, DistHeaderPkt::Header::needCkpt, DistHeaderPkt::Header::needExit, DistHeaderPkt::Header::needStopSync, Stats::none, DistIface::sendCmd(), DistHeaderPkt::Header::sendTick, and DistHeaderPkt::Header::syncRepeat.
serialize()
void DistIface::SyncSwitch::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements DistIface::Sync.
Definition at line 321 of file dist_iface.cc.
References SERIALIZE_SCALAR.
unserialize()
void DistIface::SyncSwitch::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements DistIface::Sync.
Definition at line 327 of file dist_iface.cc.
References UNSERIALIZE_SCALAR.
Member Data Documentation
numCkptReq
unsigned DistIface::SyncSwitch::numCkptReq private
Counter for recording ckpt requests.
Definition at line 250 of file dist_iface.hh.
numExitReq
unsigned DistIface::SyncSwitch::numExitReq private
Counter for recording exit requests.
Definition at line 246 of file dist_iface.hh.
numNodes
unsigned DistIface::SyncSwitch::numNodes private
Number of connected simulated nodes.
Definition at line 258 of file dist_iface.hh.
numStopSyncReq
unsigned DistIface::SyncSwitch::numStopSyncReq private
Counter for recording stop sync requests.
Definition at line 254 of file dist_iface.hh.
The documentation for this class was generated from the following files:
dev/net/dist_iface.hh
dev/net/dist_iface.cc