gem5: Sp804::Timer Class Reference
Sp804::Timer Class Reference
#include <timer_sp804.hh>
Public Types
enum {
LoadReg = 0x00, CurrentReg = 0x04, ControlReg = 0x08, IntClear = 0x0C,
RawISR = 0x10, MaskedISR = 0x14, BGLoad = 0x18, Size = 0x20
}
Public Member Functions
BitUnion32 (CTRL) Bitfield< 0 > oneShot
void counterAtZero ()
Called when the counter reaches 0.
void restartCounter (uint32_t val)
Restart the counter ticking at val.
Timer (std::string __name, Sp804 *parent, int int_num, Tick clock)
std::string name () const
void read (PacketPtr pkt, Addr daddr)
Handle read for a single timer.
void write (PacketPtr pkt, Addr daddr)
Handle write for a single timer.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
Bitfield< 1 > timerSize
Bitfield< 3, 2 > timerPrescale
Bitfield< 5 > intEnable
Bitfield< 6 > timerMode
Bitfield< 7 > timerEnable
EndBitUnion(CTRL) protected Sp804 * parent
Pointer to parent class.
const uint32_t intNum
Number of interrupt to cause/clear.
const Tick clock
Number of ticks in a clock input.
CTRL control
Control register as specified above.
bool rawInt
If timer has caused an interrupt.
bool pendingInt
If an interrupt is currently pending.
uint32_t loadValue
Value to load into counter when periodic mode reaches 0.
EventFunctionWrapper zeroEvent
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 55 of file timer_sp804.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
LoadReg
CurrentReg
ControlReg
IntClear
RawISR
MaskedISR
BGLoad
Size
Definition at line 59 of file timer_sp804.hh.
Constructor & Destructor Documentation
Timer()
Sp804::Timer::Timer (std::string __name, Sp804 * parent, int int_num, Tick clock)
Definition at line 57 of file timer_sp804.cc.
References counterAtZero(), and name().
Member Function Documentation
BitUnion32()
Sp804::Timer::BitUnion32 (CTRL)
counterAtZero()
void Sp804::Timer::counterAtZero ()
Called when the counter reaches 0.
Definition at line 197 of file timer_sp804.cc.
References control, DPRINTF, Sp804::gic, intNum, loadValue, parent, pendingInt, rawInt, restartCounter(), and BaseGic::sendInt().
Referenced by Timer().
name()
std::string Sp804::Timer::name () const inline
Definition at line 116 of file timer_sp804.hh.
References read(), serialize(), unserialize(), and write().
Referenced by Timer().
read()
void Sp804::Timer::read (PacketPtr pkt, Addr daddr)
Handle read for a single timer.
Definition at line 85 of file timer_sp804.cc.
References BGLoad, clock, control, ControlReg, CurrentReg, curTick(), DPRINTF, Packet::getLE(), LoadReg, loadValue, MaskedISR, panic, pendingInt, power(), rawInt, RawISR, Packet::setLE(), Event::when(), and zeroEvent.
Referenced by name(), Sp804::params(), and Sp804::read().
restartCounter()
void Sp804::Timer::restartCounter (uint32_t val)
Restart the counter ticking at val.
Parameters
val the value to start at (pre-16 bit masking if en)
Definition at line 176 of file timer_sp804.cc.
References bits(), clock, control, curTick(), EventManager::deschedule(), DPRINTF, parent, power(), EventManager::schedule(), Event::scheduled(), X86ISA::val, and zeroEvent.
Referenced by counterAtZero(), and write().
serialize()
void Sp804::Timer::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 224 of file timer_sp804.cc.
References control, DPRINTF, loadValue, pendingInt, rawInt, Event::scheduled(), SERIALIZE_SCALAR, Event::when(), and zeroEvent.
Referenced by name(), and Sp804::params().
unserialize()
void Sp804::Timer::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 246 of file timer_sp804.cc.
References control, DPRINTF, loadValue, parent, pendingInt, rawInt, EventManager::schedule(), UNSERIALIZE_SCALAR, and zeroEvent.
Referenced by name(), and Sp804::params().
write()
void Sp804::Timer::write (PacketPtr pkt, Addr daddr)
Handle write for a single timer.
Definition at line 139 of file timer_sp804.cc.
References BGLoad, BaseGic::clearInt(), control, ControlReg, CurrentReg, DPRINTF, Packet::getLE(), Sp804::gic, IntClear, intNum, LoadReg, loadValue, panic, parent, pendingInt, rawInt, and restartCounter().
Referenced by name(), Sp804::params(), and Sp804::write().
Member Data Documentation
clock
const Tick Sp804::Timer::clock
Number of ticks in a clock input.
Definition at line 89 of file timer_sp804.hh.
Referenced by read(), and restartCounter().
control
CTRL Sp804::Timer::control
Control register as specified above.
Definition at line 92 of file timer_sp804.hh.
Referenced by counterAtZero(), read(), restartCounter(), serialize(), unserialize(), and write().
intEnable
Bitfield<5> Sp804::Timer::intEnable
Definition at line 74 of file timer_sp804.hh.
intNum
const uint32_t Sp804::Timer::intNum
Number of interrupt to cause/clear.
Definition at line 86 of file timer_sp804.hh.
Referenced by counterAtZero(), and write().
loadValue
uint32_t Sp804::Timer::loadValue
Value to load into counter when periodic mode reaches 0.
Definition at line 103 of file timer_sp804.hh.
Referenced by counterAtZero(), read(), serialize(), unserialize(), and write().
parent
EndBitUnion (CTRL) protected Sp804* Sp804::Timer::parent
Pointer to parent class.
Definition at line 77 of file timer_sp804.hh.
Referenced by counterAtZero(), restartCounter(), unserialize(), and write().
pendingInt
bool Sp804::Timer::pendingInt
If an interrupt is currently pending.
Logical and of CTRL.intEnable and rawInt
Definition at line 100 of file timer_sp804.hh.
Referenced by counterAtZero(), read(), serialize(), unserialize(), and write().
rawInt
bool Sp804::Timer::rawInt
If timer has caused an interrupt.
This is irrespective of interrupt enable
Definition at line 96 of file timer_sp804.hh.
Referenced by counterAtZero(), read(), serialize(), unserialize(), and write().
timerEnable
Bitfield<7> Sp804::Timer::timerEnable
Definition at line 76 of file timer_sp804.hh.
timerMode
Bitfield<6> Sp804::Timer::timerMode
Definition at line 75 of file timer_sp804.hh.
timerPrescale
Bitfield<3,2> Sp804::Timer::timerPrescale
Definition at line 73 of file timer_sp804.hh.
timerSize
Bitfield<1> Sp804::Timer::timerSize
Definition at line 72 of file timer_sp804.hh.
zeroEvent
EventFunctionWrapper Sp804::Timer::zeroEvent
Definition at line 107 of file timer_sp804.hh.
Referenced by read(), restartCounter(), serialize(), and unserialize().
The documentation for this class was generated from the following files:
dev/arm/timer_sp804.hh
dev/arm/timer_sp804.cc