gem5: RealViewCtrl Class Reference
RealViewCtrl Class Reference abstract
#include <rv_ctrl.hh>
Classes
class Device
Public Types
enum DeviceFunc {
FUNC_OSC = 1, FUNC_VOLT = 2, FUNC_AMP = 3, FUNC_TEMP = 4,
FUNC_RESET = 5, FUNC_SCC = 6, FUNC_MUXFPGA = 7, FUNC_SHUTDOWN = 8,
FUNC_REBOOT = 9, FUNC_DVIMODE = 11, FUNC_POWER = 12, FUNC_ENERGY = 13
}
typedef RealViewCtrlParams Params
Public Types inherited from BasicPioDevice
typedef BasicPioDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
RealViewCtrl (Params *p)
The constructor for RealView just registers itself with the MMU.
Tick read (PacketPtr pkt) override
Handle a read to the device.
Tick write (PacketPtr pkt) override
All writes are simply ignored.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
void registerDevice (DeviceFunc func, uint8_t site, uint8_t pos, uint8_t dcc, uint16_t dev, Device *handler)
Public Member Functions inherited from BasicPioDevice
BasicPioDevice (const Params *p, Addr size)
const Params * params () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum {
IdReg = 0x00, SwReg = 0x04, Led = 0x08, Osc0 = 0x0C,
Osc1 = 0x10, Osc2 = 0x14, Osc3 = 0x18, Osc4 = 0x1C,
Lock = 0x20, Clock100 = 0x24, CfgData1 = 0x28, CfgData2 = 0x2C,
Flags = 0x30, FlagsClr = 0x34, NvFlags = 0x38, NvFlagsClr = 0x3C,
ResetCtl = 0x40, PciCtl = 0x44, MciCtl = 0x48, Flash = 0x4C,
Clcd = 0x50, ClcdSer = 0x54, Bootcs = 0x58, Clock24 = 0x5C,
Misc = 0x60, IoSel = 0x70, ProcId0 = 0x84, ProcId1 = 0x88,
CfgData = 0xA0, CfgCtrl = 0xA4, CfgStat = 0xA8, TestOsc0 = 0xC0,
TestOsc1 = 0xC4, TestOsc2 = 0xC8, TestOsc3 = 0xCC, TestOsc4 = 0xD0
}
Protected Member Functions
BitUnion32 (SysLockReg) Bitfield< 15
EndBitUnion (SysLockReg) BitUnion32(CfgCtrlReg) Bitfield< 11
EndBitUnion (CfgCtrlReg) static const uint32_t CFG_CTRL_ADDR_MASK=0x3fffffffUL
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
lockVal
Bitfield< 16 > locked
dev
Bitfield< 15, 12 > pos
Bitfield< 17, 16 > site
Bitfield< 25, 20 > func
Bitfield< 29, 26 > dcc
Bitfield< 30 > wr
Bitfield< 31 > start
SysLockReg sysLock
uint32_t flags
This register is used for smp booting.
uint32_t scData
This register contains the result from a system control reg access.
std::map< uint32_t, Device * > devices
Protected Attributes inherited from BasicPioDevice
Addr pioAddr
Address that the device listens to.
Addr pioSize
Size that the device's address range.
Tick pioDelay
Delay that the device experinces on an access.
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 53 of file rv_ctrl.hh.
Member Typedef Documentation
Params
typedef RealViewCtrlParams RealViewCtrl::Params
Definition at line 158 of file rv_ctrl.hh.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
IdReg
SwReg
Led
Osc0
Osc1
Osc2
Osc3
Osc4
Lock
Clock100
CfgData1
CfgData2
Flags
FlagsClr
NvFlags
NvFlagsClr
ResetCtl
PciCtl
MciCtl
Flash
Clcd
ClcdSer
Bootcs
Clock24
Misc
IoSel
ProcId0
ProcId1
CfgData
CfgCtrl
CfgStat
TestOsc0
TestOsc1
TestOsc2
TestOsc3
TestOsc4
Definition at line 87 of file rv_ctrl.hh.
DeviceFunc
enum RealViewCtrl::DeviceFunc
Enumerator
FUNC_OSC
FUNC_VOLT
FUNC_AMP
FUNC_TEMP
FUNC_RESET
FUNC_SCC
FUNC_MUXFPGA
FUNC_SHUTDOWN
FUNC_REBOOT
FUNC_DVIMODE
FUNC_POWER
FUNC_ENERGY
Definition at line 56 of file rv_ctrl.hh.
Constructor & Destructor Documentation
RealViewCtrl()
RealViewCtrl::RealViewCtrl (Params * p)
The constructor for RealView just registers itself with the MMU.
Parameters
p params structure
Definition at line 50 of file rv_ctrl.cc.
Referenced by params().
Member Function Documentation
BitUnion32()
RealViewCtrl::BitUnion32 (SysLockReg) protected
EndBitUnion() [1/2]
RealViewCtrl::EndBitUnion (SysLockReg) protected
EndBitUnion() [2/2]
RealViewCtrl::EndBitUnion (CfgCtrlReg) const protected pure virtual
params()
const Params* RealViewCtrl::params () const inline
Definition at line 160 of file rv_ctrl.hh.
References SimObject::_params, dcc, dev, func, MipsISA::p, pos, RealViewCtrl::Device::read(), RealViewCtrl(), registerDevice(), serialize(), site, unserialize(), and RealViewCtrl::Device::write().
Referenced by read().
read()
Tick RealViewCtrl::read (PacketPtr pkt) override virtual
Handle a read to the device.
Parameters
pkt The memory request.
data Where to put the data.
Implements PioDevice.
Definition at line 56 of file rv_ctrl.cc.
References CfgCtrl, CfgData, CfgStat, Clcd, Clock100, Clock24, curTick(), DPRINTF, Flags, flags, Flash, Packet::getAddr(), Packet::getSize(), IdReg, Lock, Packet::makeAtomicResponse(), SimClock::Float::MHz, Osc0, Osc1, Osc2, Osc3, Osc4, params(), BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, ProcId0, ProcId1, scData, Packet::setLE(), sysLock, and warn.
registerDevice()
void RealViewCtrl::registerDevice (DeviceFunc func, uint8_t site, uint8_t pos, uint8_t dcc, uint16_t dev, Device * handler)
Definition at line 218 of file rv_ctrl.cc.
References addr, dcc, dev, devices, fatal, func, pos, and site.
Referenced by RealViewCtrl::Device::Device(), and params().
serialize()
void RealViewCtrl::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 206 of file rv_ctrl.cc.
References flags, and SERIALIZE_SCALAR.
Referenced by params(), and RealViewOsc::~RealViewOsc().
unserialize()
void RealViewCtrl::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 212 of file rv_ctrl.cc.
References flags, and UNSERIALIZE_SCALAR.
Referenced by params(), and RealViewOsc::~RealViewOsc().
write()
Tick RealViewCtrl::write (PacketPtr pkt) override virtual
All writes are simply ignored.
Parameters
pkt The memory request.
data the data
Implements PioDevice.
Definition at line 132 of file rv_ctrl.cc.
References CfgCtrl, CfgData, CfgStat, Clcd, dev, devices, DPRINTF, Flags, flags, FlagsClr, Flash, Packet::getAddr(), Packet::getLE(), Lock, Packet::makeAtomicResponse(), Osc0, Osc1, Osc2, Osc3, Osc4, BasicPioDevice::pioAddr, BasicPioDevice::pioDelay, BasicPioDevice::pioSize, RealViewCtrl::Device::read(), ResetCtl, scData, sysLock, warn, warn_once, and RealViewCtrl::Device::write().
Member Data Documentation
dcc
Bitfield<29, 26> RealViewCtrl::dcc protected
Definition at line 137 of file rv_ctrl.hh.
Referenced by params(), and registerDevice().
dev
RealViewCtrl::dev protected
Definition at line 133 of file rv_ctrl.hh.
Referenced by params(), registerDevice(), and write().
devices
std::map<uint32_t, Device *> RealViewCtrl::devices protected
Definition at line 193 of file rv_ctrl.hh.
Referenced by registerDevice(), and write().
flags
uint32_t RealViewCtrl::flags protected
This register is used for smp booting.
The primary cpu writes the secondary start address here before sends it a soft interrupt. The secondary cpu reads this register and if it's non-zero it jumps to the address
Definition at line 151 of file rv_ctrl.hh.
Referenced by read(), serialize(), unserialize(), and write().
func
Bitfield<25, 20> RealViewCtrl::func protected
Definition at line 136 of file rv_ctrl.hh.
Referenced by params(), and registerDevice().
locked
Bitfield<16> RealViewCtrl::locked protected
Definition at line 129 of file rv_ctrl.hh.
lockVal
RealViewCtrl::lockVal protected
Definition at line 128 of file rv_ctrl.hh.
pos
Bitfield<15, 12> RealViewCtrl::pos protected
Definition at line 134 of file rv_ctrl.hh.
Referenced by params(), and registerDevice().
scData
uint32_t RealViewCtrl::scData protected
This register contains the result from a system control reg access.
Definition at line 155 of file rv_ctrl.hh.
Referenced by read(), and write().
site
Bitfield<17, 16> RealViewCtrl::site protected
Definition at line 135 of file rv_ctrl.hh.
Referenced by params(), and registerDevice().
start
Bitfield<31> RealViewCtrl::start protected
Definition at line 139 of file rv_ctrl.hh.
sysLock
SysLockReg RealViewCtrl::sysLock protected
Definition at line 144 of file rv_ctrl.hh.
Referenced by read(), and write().
wr
Bitfield<30> RealViewCtrl::wr protected
Definition at line 138 of file rv_ctrl.hh.
The documentation for this class was generated from the following files:
dev/arm/rv_ctrl.hh
dev/arm/rv_ctrl.cc