gem5: Trace::ArmNativeTrace Class Reference
Trace::ArmNativeTrace Class Reference
#include <nativetrace.hh>
Classes
struct ThreadState
Public Types
enum StateID {
STATE_R0, STATE_R1, STATE_R2, STATE_R3,
STATE_R4, STATE_R5, STATE_R6, STATE_R7,
STATE_R8, STATE_R9, STATE_R10, STATE_R11,
STATE_FP = STATE_R11, STATE_R12, STATE_R13, STATE_SP = STATE_R13,
STATE_R14, STATE_LR = STATE_R14, STATE_R15, STATE_PC = STATE_R15,
STATE_CPSR, STATE_F0, STATE_F1, STATE_F2,
STATE_F3, STATE_F4, STATE_F5, STATE_F6,
STATE_F7, STATE_F8, STATE_F9, STATE_F10,
STATE_F11, STATE_F12, STATE_F13, STATE_F14,
STATE_F15, STATE_F16, STATE_F17, STATE_F18,
STATE_F19, STATE_F20, STATE_F21, STATE_F22,
STATE_F23, STATE_F24, STATE_F25, STATE_F26,
STATE_F27, STATE_F28, STATE_F29, STATE_F30,
STATE_F31, STATE_FPSCR, STATE_NUMVALS
}
typedef ArmNativeTraceParams Params
Public Types inherited from Trace::ExeTracer
typedef ExeTracerParams Params
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
const Params * params () const
ArmNativeTrace (const Params *p)
void check (NativeTraceRecord *record)
Public Member Functions inherited from Trace::NativeTrace
NativeTrace (const Params *p)
virtual ~NativeTrace ()
NativeTraceRecord * getInstRecord (Tick when, ThreadContext *tc, const StaticInstPtr staticInst, TheISA::PCState pc, const StaticInstPtr macroStaticInst=NULL)
template<class T >
bool checkReg (const char *regName, T &val, T &realVal)
void read (void *ptr, size_t size)
Public Member Functions inherited from Trace::ExeTracer
ExeTracer (const Params *params)
Public Member Functions inherited from Trace::InstTracer
InstTracer (const Params *p)
virtual ~InstTracer ()
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Protected Attributes
ThreadState nState
ThreadState mState
bool stopOnPCError
Protected Attributes inherited from Trace::NativeTrace
int fd
ListenSocket native_listener
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Detailed Description
Definition at line 40 of file nativetrace.hh.
Member Typedef Documentation
Params
typedef ArmNativeTraceParams Trace::ArmNativeTrace::Params
Definition at line 101 of file nativetrace.hh.
Member Enumeration Documentation
StateID
enum Trace::ArmNativeTrace::StateID
Enumerator
STATE_R0
STATE_R1
STATE_R2
STATE_R3
STATE_R4
STATE_R5
STATE_R6
STATE_R7
STATE_R8
STATE_R9
STATE_R10
STATE_R11
STATE_FP
STATE_R12
STATE_R13
STATE_SP
STATE_R14
STATE_LR
STATE_R15
STATE_PC
STATE_CPSR
STATE_F0
STATE_F1
STATE_F2
STATE_F3
STATE_F4
STATE_F5
STATE_F6
STATE_F7
STATE_F8
STATE_F9
STATE_F10
STATE_F11
STATE_F12
STATE_F13
STATE_F14
STATE_F15
STATE_F16
STATE_F17
STATE_F18
STATE_F19
STATE_F20
STATE_F21
STATE_F22
STATE_F23
STATE_F24
STATE_F25
STATE_F26
STATE_F27
STATE_F28
STATE_F29
STATE_F30
STATE_F31
STATE_FPSCR
STATE_NUMVALS
Definition at line 43 of file nativetrace.hh.
Constructor & Destructor Documentation
ArmNativeTrace()
Trace::ArmNativeTrace::ArmNativeTrace (const Params * p) inline
Definition at line 109 of file nativetrace.hh.
References check().
Member Function Documentation
check()
void Trace::ArmNativeTrace::check (NativeTraceRecord * record) virtual
Implements Trace::NativeTrace.
Definition at line 139 of file nativetrace.cc.
References DPRINTF, Trace::InstRecord::getMacroStaticInst(), Trace::InstRecord::getStaticInst(), Trace::InstRecord::getThread(), ArmISA::i, StaticInst::isMicroop(), ThreadContext::nextInstAddr(), panic, and Trace::ExeTracerRecord::traceInst().
Referenced by ArmNativeTrace().
params()
const Params* Trace::ArmNativeTrace::params () const inline
Definition at line 104 of file nativetrace.hh.
References SimObject::_params.
Member Data Documentation
mState
ThreadState Trace::ArmNativeTrace::mState protected
Definition at line 96 of file nativetrace.hh.
nState
ThreadState Trace::ArmNativeTrace::nState protected
Definition at line 96 of file nativetrace.hh.
stopOnPCError
bool Trace::ArmNativeTrace::stopOnPCError protected
Definition at line 98 of file nativetrace.hh.
The documentation for this class was generated from the following files:
arch/arm/nativetrace.hh
arch/arm/nativetrace.cc