gem5: Sinic::Device Class Reference
Sinic::Device Class Reference
#include <sinic.hh>
Classes
struct VirtualReg
Public Member Functions
bool recvPacket (EthPacketPtr packet)
device ethernet interface
void transferDone ()
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
Tick read (PacketPtr pkt) override
Memory Interface.
Tick write (PacketPtr pkt) override
IPR read of device register.
virtual void drainResume () override
Resume execution after a successful drain.
void prepareIO (ContextID cpu, int index)
void prepareRead (ContextID cpu, int index)
void prepareWrite (ContextID cpu, int index)
void regStats () override
Callback to set stat parameters.
void resetStats () override
Callback to reset stats.
void serialize (CheckpointOut &cp) const override
Serialization stuff.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Device (const Params *p)
~Device ()
Public Member Functions inherited from Sinic::Base
const Params * params () const
Base (const Params *p)
Public Member Functions inherited from EtherDevBase
EtherDevBase (const EtherDevBaseParams *params)
const EtherDevBaseParams * params () const
Public Member Functions inherited from EtherDevice
EtherDevice (const Params *params)
const Params * params () const
Public Member Functions inherited from PciDevice
virtual Tick writeConfig (PacketPtr pkt)
Write to the PCI config space data that is stored locally.
virtual Tick readConfig (PacketPtr pkt)
Read from the PCI config space data that is stored locally.
Addr pciToDma (Addr pci_addr) const
void intrPost ()
void intrClear ()
uint8_t interruptLine () const
AddrRangeList getAddrRanges () const override
Determine the address ranges that this device responds to.
PciDevice (const PciDeviceParams *params)
Constructor for PCI Dev.
void serialize (CheckpointOut &cp) const override
Serialize this object to the given output stream.
void unserialize (CheckpointIn &cp) override
Reconstruct the state of this object from a checkpoint.
const PciBusAddr & busAddr () const
Public Member Functions inherited from DmaDevice
DmaDevice (const Params *p)
virtual ~DmaDevice ()
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaWrite (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, uint32_t sid, uint32_t ssid, Tick delay=0)
void dmaRead (Addr addr, int size, Event *event, uint8_t *data, Tick delay=0)
bool dmaPending () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
unsigned int cacheBlockSize () const
Public Member Functions inherited from PioDevice
PioDevice (const Params *p)
virtual ~PioDevice ()
const Params * params () const
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Protected Types
enum RxState {
rxIdle, rxFifoBlock, rxBeginCopy, rxCopy,
rxCopyDone
}
Receive State Machine States.
enum TxState {
txIdle, txFifoBlock, txBeginCopy, txCopy,
txCopyDone
}
Transmit State Machine states.
typedef std::vector< VirtualReg > VirtualRegs
typedef std::list< unsigned > VirtualList
Protected Member Functions
uint8_t & regData8 (Addr daddr)
uint32_t & regData32 (Addr daddr)
uint64_t & regData64 (Addr daddr)
void reset ()
void rxKick ()
void txKick ()
void transmit ()
Retransmit event.
void txEventTransmit ()
void txDump () const
void rxDump () const
bool rxFilter (const EthPacketPtr &packet)
receive address filter
void changeConfig (uint32_t newconfig)
device configuration
void command (uint32_t command)
void rxDmaDone ()
DMA parameters.
void txDmaDone ()
void devIntrPost (uint32_t interrupts)
Interrupt management.
void devIntrClear (uint32_t interrupts=Regs::Intr_All)
void devIntrChangeMask (uint32_t newmask)
Protected Member Functions inherited from Sinic::Base
void cpuIntrPost (Tick when)
void cpuInterrupt ()
void cpuIntrClear ()
bool cpuIntrPending () const
void cpuIntrAck ()
Protected Member Functions inherited from PciDevice
bool isLargeBAR (int bar) const
Does the given BAR represent 32 lower bits of a 64-bit address?
bool isBAR (Addr addr, int bar) const
Does the given address lie within the space mapped by the given base address register?
int getBAR (Addr addr)
Which base address register (if any) maps the given address?
bool getBAR (Addr addr, int &bar, Addr &offs)
Which base address register (if any) maps the given address?
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes
struct {
uint32_t Config
uint32_t Command
uint32_t IntrStatus
uint32_t IntrMask
uint32_t RxMaxCopy
uint32_t TxMaxCopy
uint32_t ZeroCopySize
uint32_t ZeroCopyMark
uint32_t VirtualCount
uint32_t RxMaxIntr
uint32_t RxFifoSize
uint32_t TxFifoSize
uint32_t RxFifoLow
uint32_t TxFifoLow
uint32_t RxFifoHigh
uint32_t TxFifoHigh
uint64_t RxData
uint64_t RxDone
uint64_t RxWait
uint64_t TxData
uint64_t TxDone
uint64_t TxWait
uint64_t HwAddr
uint64_t RxStatus
} regs
device register file
Counter rxUnique
Counter txUnique
VirtualRegs virtualRegs
VirtualList rxList
VirtualList rxBusy
int rxActive
VirtualList txList
int rxBusyCount
int rxMappedCount
int rxDirtyCount
RxState rxState
PacketFifo rxFifo
PacketFifo::iterator rxFifoPtr
bool rxEmpty
bool rxLow
Addr rxDmaAddr
uint8_t * rxDmaData
unsigned rxDmaLen
TxState txState
PacketFifo txFifo
bool txFull
EthPacketPtr txPacket
int txPacketOffset
int txPacketBytes
Addr txDmaAddr
uint8_t * txDmaData
int txDmaLen
Tick rxKickTick
Tick txKickTick
EventFunctionWrapper txEvent
EventFunctionWrapper rxDmaEvent
EventFunctionWrapper txDmaEvent
Tick dmaReadDelay
Tick dmaReadFactor
Tick dmaWriteDelay
Tick dmaWriteFactor
Protected Attributes inherited from Sinic::Base
bool rxEnable
bool txEnable
Tick intrDelay
Tick intrTick
bool cpuIntrEnable
bool cpuPendingIntr
EventFunctionWrapper * intrEvent
Interface * interface
Protected Attributes inherited from EtherDevice
Stats::Scalar txBytes
Stats::Scalar rxBytes
Stats::Scalar txPackets
Stats::Scalar rxPackets
Stats::Scalar txIpChecksums
Stats::Scalar rxIpChecksums
Stats::Scalar txTcpChecksums
Stats::Scalar rxTcpChecksums
Stats::Scalar txUdpChecksums
Stats::Scalar rxUdpChecksums
Stats::Scalar descDmaReads
Stats::Scalar descDmaWrites
Stats::Scalar descDmaRdBytes
Stats::Scalar descDmaWrBytes
Stats::Formula totBandwidth
Stats::Formula totPackets
Stats::Formula totBytes
Stats::Formula totPacketRate
Stats::Formula txBandwidth
Stats::Formula rxBandwidth
Stats::Formula txPacketRate
Stats::Formula rxPacketRate
Stats::Scalar postedSwi
Stats::Formula coalescedSwi
Stats::Scalar totalSwi
Stats::Scalar postedRxIdle
Stats::Formula coalescedRxIdle
Stats::Scalar totalRxIdle
Stats::Scalar postedRxOk
Stats::Formula coalescedRxOk
Stats::Scalar totalRxOk
Stats::Scalar postedRxDesc
Stats::Formula coalescedRxDesc
Stats::Scalar totalRxDesc
Stats::Scalar postedTxOk
Stats::Formula coalescedTxOk
Stats::Scalar totalTxOk
Stats::Scalar postedTxIdle
Stats::Formula coalescedTxIdle
Stats::Scalar totalTxIdle
Stats::Scalar postedTxDesc
Stats::Formula coalescedTxDesc
Stats::Scalar totalTxDesc
Stats::Scalar postedRxOrn
Stats::Formula coalescedRxOrn
Stats::Scalar totalRxOrn
Stats::Formula coalescedTotal
Stats::Scalar postedInterrupts
Stats::Scalar droppedPackets
Protected Attributes inherited from PciDevice
const PciBusAddr _busAddr
PCIConfig config
The current config space.
std::vector< MSIXTable > msix_table
MSIX Table and PBA Structures.
std::vector< MSIXPbaEntry > msix_pba
uint32_t BARSize [6]
The size of the BARs.
Addr BARAddrs [6]
The current address mapping of the BARs.
bool legacyIO [6]
Whether the BARs are really hardwired legacy IO locations.
PciHost::DeviceInterface hostInterface
Tick pioDelay
Tick configDelay
const int PMCAP_BASE
The capability list structures and base addresses.
const int PMCAP_ID_OFFSET
const int PMCAP_PC_OFFSET
const int PMCAP_PMCS_OFFSET
PMCAP pmcap
const int MSICAP_BASE
MSICAP msicap
const int MSIXCAP_BASE
const int MSIXCAP_ID_OFFSET
const int MSIXCAP_MXC_OFFSET
const int MSIXCAP_MTAB_OFFSET
const int MSIXCAP_MPBA_OFFSET
int MSIX_TABLE_OFFSET
int MSIX_TABLE_END
int MSIX_PBA_OFFSET
int MSIX_PBA_END
MSIXCAP msixcap
const int PXCAP_BASE
PXCAP pxcap
Protected Attributes inherited from DmaDevice
DmaPort dmaPort
Protected Attributes inherited from PioDevice
System * sys
PioPort< PioDevice > pioPort
The pioPort that handles the requests for us and provides us requests that it sees.
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
Stats::Scalar totalVnicDistance
Statistics.
Stats::Scalar numVnicDistance
Stats::Scalar maxVnicDistance
Stats::Formula avgVnicDistance
int _maxVnicDistance
Additional Inherited Members
Public Types inherited from Sinic::Base
typedef SinicParams Params
Construction/Destruction/Parameters.
Public Types inherited from EtherDevice
typedef EtherDeviceParams Params
Public Types inherited from DmaDevice
typedef DmaDeviceParams Params
Public Types inherited from PioDevice
typedef PioDeviceParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 86 of file sinic.hh.
Member Typedef Documentation
VirtualList
typedef std::list<unsigned> Sinic::Device::VirtualList protected
Definition at line 155 of file sinic.hh.
VirtualRegs
typedef std::vector<VirtualReg> Sinic::Device::VirtualRegs protected
Definition at line 154 of file sinic.hh.
Member Enumeration Documentation
RxState
enum Sinic::Device::RxState protected
Receive State Machine States.
Enumerator
rxIdle
rxFifoBlock
rxBeginCopy
rxCopy
rxCopyDone
Definition at line 90 of file sinic.hh.
TxState
enum Sinic::Device::TxState protected
Transmit State Machine states.
Enumerator
txIdle
txFifoBlock
txBeginCopy
txCopy
txCopyDone
Definition at line 99 of file sinic.hh.
Constructor & Destructor Documentation
Device()
Sinic::Device::Device (const Params * p)
Definition at line 83 of file sinic.cc.
References dmaReadDelay, dmaReadFactor, dmaWriteDelay, dmaWriteFactor, SimObject::name(), MipsISA::p, reset(), rxDmaDone(), rxDmaEvent, txDmaDone(), txDmaEvent, and txEventTransmit().
~Device()
Sinic::Device::~Device ()
Definition at line 99 of file sinic.cc.
Member Function Documentation
changeConfig()
void Sinic::Device::changeConfig (uint32_t newconfig) protected
device configuration
Definition at line 567 of file sinic.cc.
References Sinic::Base::cpuIntrClear(), Sinic::Base::cpuIntrEnable, Sinic::Base::cpuIntrPost(), curTick(), regs, Sinic::Base::rxEnable, rxKick(), Sinic::Base::txEnable, and txKick().
Referenced by write().
command()
void Sinic::Device::command (uint32_t command) protected
Definition at line 599 of file sinic.cc.
References devIntrPost(), and reset().
Referenced by write().
devIntrChangeMask()
void Sinic::Device::devIntrChangeMask (uint32_t newmask) protected
Definition at line 461 of file sinic.cc.
References Sinic::Base::cpuIntrClear(), Sinic::Base::cpuIntrPost(), curTick(), DPRINTF, and regs.
Referenced by write().
devIntrClear()
void Sinic::Device::devIntrClear (uint32_t interrupts = Regs::Intr_All) protected
Definition at line 445 of file sinic.cc.
References Sinic::Base::cpuIntrClear(), DPRINTF, panic, and regs.
Referenced by read(), and write().
devIntrPost()
void Sinic::Device::devIntrPost (uint32_t interrupts) protected
Interrupt management.
Definition at line 409 of file sinic.cc.
References Sinic::Base::cpuIntrPost(), curTick(), DPRINTF, Sinic::Base::intrDelay, panic, regs, rxEmpty, and txFull.
Referenced by command(), recvPacket(), rxKick(), transmit(), and txKick().
drainResume()
void Sinic::Device::drainResume () override virtual
Resume execution after a successful drain.
Reimplemented from Drainable.
Definition at line 1191 of file sinic.cc.
References Drainable::drainResume(), rxKick(), and txKick().
getPort()
Port & Sinic::Device::getPort (const std::string & if_name, PortID idx = InvalidPortID) override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from DmaDevice.
Definition at line 140 of file sinic.cc.
References DmaDevice::getPort(), and Sinic::Base::interface.
prepareIO()
void Sinic::Device::prepareIO (ContextID cpu, int index)
Definition at line 149 of file sinic.cc.
References panic, and virtualRegs.
Referenced by prepareRead(), and prepareWrite().
prepareRead()
void Sinic::Device::prepareRead (ContextID cpu, int index)
Definition at line 162 of file sinic.cc.
References PacketFifo::avail(), PacketFifo::begin(), PacketFifo::countPacketsAfter(), PacketFifo::empty(), MipsISA::index, PacketFifo::packets(), prepareIO(), regs, rxBusyCount, Sinic::Device::VirtualReg::RxData, rxDirtyCount, Sinic::Device::VirtualReg::RxDone, rxFifo, rxFifoPtr, rxLow, rxMappedCount, PacketFifo::size(), Sinic::Device::VirtualReg::TxData, Sinic::Device::VirtualReg::TxDone, txFifo, and virtualRegs.
Referenced by read().
prepareWrite()
void Sinic::Device::prepareWrite (ContextID cpu, int index)
Definition at line 203 of file sinic.cc.
References prepareIO().
Referenced by write().
read()
Tick Sinic::Device::read (PacketPtr pkt) override virtual
Memory Interface.
I/O read of device register.
Implements PioDevice.
Definition at line 212 of file sinic.cc.
References PciDevice::BARAddrs, PciDevice::BARSize, PCIConfig::command, PciDevice::config, devIntrClear(), DPRINTF, Packet::getAddr(), Packet::getSize(), MipsISA::index, M5_VAR_USED, panic, PCI_CMD_MSE, PciDevice::pioDelay, prepareRead(), X86ISA::reg, regData32(), regData64(), Sinic::regInfo(), Sinic::regValid(), Packet::req, Packet::setLE(), Sinic::Regs::VirtualMask, and Sinic::Regs::VirtualShift.
recvPacket()
bool Sinic::Device::recvPacket (EthPacketPtr packet)
device ethernet interface
Definition at line 1153 of file sinic.cc.
References PacketFifo::avail(), devIntrPost(), DPRINTF, PacketFifo::end(), PacketFifo::push(), regs, EtherDevice::rxBytes, Sinic::Base::rxEnable, rxFifo, rxFifoPtr, rxFilter(), rxKick(), EtherDevice::rxPackets, and PacketFifo::size().
Referenced by Sinic::Interface::recvPacket().
regData32()
uint32_t& Sinic::Device::regData32 (Addr daddr) inline protected
Definition at line 169 of file sinic.hh.
Referenced by read().
regData64()
uint64_t& Sinic::Device::regData64 (Addr daddr) inline protected
Definition at line 170 of file sinic.hh.
Referenced by read().
regData8()
uint8_t& Sinic::Device::regData8 (Addr daddr) inline protected
Definition at line 168 of file sinic.hh.
regStats()
void Sinic::Device::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from EtherDevice.
Definition at line 103 of file sinic.cc.
References _maxVnicDistance, avgVnicDistance, Stats::DataWrap< Derived, InfoProxyType >::desc(), maxVnicDistance, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numVnicDistance, EtherDevice::regStats(), and totalVnicDistance.
reset()
void Sinic::Device::reset () protected
Definition at line 609 of file sinic.cc.
References PacketFifo::clear(), PacketFifo::end(), ArmISA::i, panic, Sinic::Base::params(), regs, rxActive, rxBusy, rxBusyCount, rxDirtyCount, rxEmpty, rxFifo, rxFifoPtr, rxIdle, rxList, rxLow, rxMappedCount, rxState, txFifo, txFull, txIdle, txList, txState, and virtualRegs.
Referenced by command(), and Device().
resetStats()
void Sinic::Device::resetStats () override virtual
Callback to reset stats.
Reimplemented from Stats::Group.
Definition at line 132 of file sinic.cc.
References _maxVnicDistance, and Stats::Group::resetStats().
rxDmaDone()
void Sinic::Device::rxDmaDone () protected
DMA parameters.
Definition at line 679 of file sinic.cc.
References DDUMP, DPRINTF, rxCopy, rxCopyDone, rxDmaAddr, rxDmaData, rxDmaLen, rxKick(), rxState, txBeginCopy, txKick(), and txState.
Referenced by Device().
rxDump()
void Sinic::Device::rxDump () const protected
rxFilter()
bool Sinic::Device::rxFilter (const EthPacketPtr & packet) protected
receive address filter
Definition at line 1142 of file sinic.cc.
References panic, and regs.
Referenced by recvPacket().
rxKick()
void Sinic::Device::rxKick () protected
Todo:
do we want to schedule a future kick?
Definition at line 695 of file sinic.cc.
References _maxVnicDistance, Net::TcpHdr::ack(), PacketFifo::check(), Net::cksum(), PacketFifo::countPacketsBefore(), curTick(), devIntrPost(), DmaDevice::dmaPending(), DmaDevice::dmaWrite(), Net::TcpHdr::dport(), DPRINTF, Drainable::drainState(), DTRACE, PacketFifo::empty(), PacketFifo::end(), X86ISA::exit, ArmISA::i, Net::IpHdr::id(), iGbReg::TxdOp::ip(), LL, maxVnicDistance, numVnicDistance, panic, PciDevice::pciToDma(), regs, PacketFifo::remove(), Running, rxActive, rxBeginCopy, rxBusy, rxBusyCount, rxCopy, rxCopyDone, Sinic::Device::VirtualReg::RxData, rxDirtyCount, rxDmaAddr, rxDmaData, rxDmaEvent, rxDmaLen, Sinic::Device::VirtualReg::RxDone, Sinic::Device::VirtualReg::rxDoneData, rxEmpty, rxFifo, rxFifoBlock, rxFifoPtr, rxIdle, Sinic::Device::VirtualReg::rxIndex, EtherDevice::rxIpChecksums, rxKickTick, rxList, rxLow, rxMappedCount, Sinic::Device::VirtualReg::rxPacketBytes, Sinic::Device::VirtualReg::rxPacketOffset, rxState, EtherDevice::rxTcpChecksums, EtherDevice::rxUdpChecksums, Sinic::Device::VirtualReg::rxUnique, Net::TcpHdr::seq(), PacketFifo::size(), Net::TcpHdr::sport(), ArmISA::status, iGbReg::TxdOp::tcp(), totalVnicDistance, and virtualRegs.
Referenced by changeConfig(), drainResume(), recvPacket(), rxDmaDone(), txDmaDone(), and write().
serialize()
void Sinic::Device::serialize (CheckpointOut & cp) const override virtual
Serialization stuff.
Reimplemented from Sinic::Base.
Definition at line 1251 of file sinic.cc.
References PacketFifo::begin(), X86ISA::count, PacketFifo::countPacketsBefore(), csprintf(), curTick(), PacketFifo::end(), ArmISA::i, panic, paramOut(), X86ISA::reg, regs, rxActive, rxBusy, rxBusyCount, rxCopy, Sinic::Device::VirtualReg::RxData, rxDirtyCount, Sinic::Device::VirtualReg::RxDone, Sinic::Device::VirtualReg::rxDoneData, rxEmpty, rxFifo, rxFifoPtr, Sinic::Device::VirtualReg::rxIndex, rxList, rxLow, rxMappedCount, Sinic::Device::VirtualReg::rxPacketBytes, Sinic::Device::VirtualReg::rxPacketOffset, rxState, Event::scheduled(), Sinic::Base::serialize(), PacketFifo::serialize(), SERIALIZE_SCALAR, txCopy, Sinic::Device::VirtualReg::TxData, Sinic::Device::VirtualReg::TxDone, txEvent, txFifo, txFull, txList, txPacket, txPacketBytes, txPacketOffset, txState, virtualRegs, and Event::when().
transferDone()
void Sinic::Device::transferDone ()
Definition at line 1129 of file sinic.cc.
References Clocked::clockEdge(), DPRINTF, PacketFifo::empty(), EventManager::reschedule(), txEvent, and txFifo.
Referenced by Sinic::Interface::sendDone().
transmit()
void Sinic::Device::transmit () protected
Retransmit event.
Definition at line 965 of file sinic.cc.
References PacketFifo::avail(), DDUMP, devIntrPost(), DPRINTF, DTRACE, PacketFifo::empty(), PacketFifo::front(), Net::IpHdr::id(), Sinic::Base::interface, iGbReg::TxdOp::ip(), PacketFifo::pop(), regs, EtherInt::sendPacket(), PacketFifo::size(), iGbReg::TxdOp::tcp(), EtherDevice::txBytes, txFifo, and EtherDevice::txPackets.
Referenced by txKick().
txDmaDone()
void Sinic::Device::txDmaDone () protected
Definition at line 949 of file sinic.cc.
References DDUMP, DPRINTF, rxBeginCopy, rxKick(), rxState, txCopy, txCopyDone, txDmaAddr, txDmaData, txDmaLen, txKick(), and txState.
Referenced by Device().
txDump()
void Sinic::Device::txDump () const protected
txEventTransmit()
void Sinic::Device::txEventTransmit () inline protected
Definition at line 205 of file sinic.hh.
Referenced by Device().
txKick()
void Sinic::Device::txKick () protected
Todo:
do we want to schedule a future kick?
Definition at line 1011 of file sinic.cc.
References PacketFifo::avail(), Net::cksum(), curTick(), devIntrPost(), DmaDevice::dmaPending(), DmaDevice::dmaRead(), DPRINTF, Drainable::drainState(), X86ISA::exit, iGbReg::TxdOp::ip(), panic, PciDevice::pciToDma(), PacketFifo::push(), regs, Running, PacketFifo::size(), Net::IpHdr::sum(), Net::TcpHdr::sum(), Net::UdpHdr::sum(), iGbReg::TxdOp::tcp(), transmit(), txBeginCopy, txCopy, txCopyDone, txDmaAddr, txDmaData, txDmaEvent, txDmaLen, txFifo, txFifoBlock, txFull, txIdle, EtherDevice::txIpChecksums, txKickTick, txList, txPacket, txPacketOffset, txState, EtherDevice::txTcpChecksums, EtherDevice::txUdpChecksums, and virtualRegs.
Referenced by changeConfig(), drainResume(), rxDmaDone(), txDmaDone(), and write().
unserialize()
void Sinic::Device::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Reimplemented from Sinic::Base.
Definition at line 1366 of file sinic.cc.
References PacketFifo::begin(), csprintf(), curTick(), PacketFifo::end(), ArmISA::i, paramIn(), PioDevice::pioPort, X86ISA::reg, regs, rxActive, rxBusy, rxBusyCount, Sinic::Device::VirtualReg::RxData, rxDirtyCount, Sinic::Device::VirtualReg::RxDone, Sinic::Device::VirtualReg::rxDoneData, rxEmpty, rxFifo, rxFifoPtr, Sinic::Device::VirtualReg::rxIndex, rxList, rxLow, rxMappedCount, Sinic::Device::VirtualReg::rxPacketBytes, Sinic::Device::VirtualReg::rxPacketOffset, rxState, Sinic::Device::VirtualReg::rxUnique, rxUnique, EventManager::schedule(), SlavePort::sendRangeChange(), Sinic::Device::VirtualReg::TxData, Sinic::Device::VirtualReg::TxDone, txEvent, txFifo, txFull, txList, txPacket, txPacketBytes, txPacketOffset, txState, Sinic::Device::VirtualReg::txUnique, txUnique, Sinic::Base::unserialize(), PacketFifo::unserialize(), UNSERIALIZE_SCALAR, and virtualRegs.
write()
Tick Sinic::Device::write (PacketPtr pkt) override virtual
IPR read of device register.
Fault Device::iprRead(Addr daddr, ContextID cpu, uint64_t &result) { if (!regValid(daddr)) panic("invalid address: da=%#x", daddr);
const Regs::Info &info = regInfo(daddr); if (!info.read) panic("reading %s (write only): cpu=%d da=%#x", info.name, cpu, daddr);
DPRINTF(EthernetPIO, "IPR read %s: cpu=%d da=%#x\n", info.name, cpu, daddr);
prepareRead(cpu, 0);
if (info.size == 4) result = regData32(daddr);
if (info.size == 8) result = regData64(daddr);
DPRINTF(EthernetPIO, "IPR read %s: cpu=%s da=%#x val=%#x\n", info.name, cpu, result);
return NoFault; } I/O write of device register
Implements PioDevice.
Definition at line 297 of file sinic.cc.
References PciDevice::BARAddrs, PciDevice::BARSize, changeConfig(), PCIConfig::command, command(), PciDevice::config, devIntrChangeMask(), devIntrClear(), DPRINTF, PacketFifo::end(), Packet::getAddr(), Packet::getLE(), Packet::getSize(), MipsISA::index, panic, PCI_CMD_MSE, PciDevice::pioDelay, prepareWrite(), Sinic::regInfo(), regs, Sinic::regValid(), Packet::req, rxBusy, rxBusyCount, Sinic::Device::VirtualReg::RxData, Sinic::Device::VirtualReg::RxDone, Sinic::Base::rxEnable, rxFifo, rxFifoBlock, rxIdle, Sinic::Device::VirtualReg::rxIndex, rxKick(), rxList, rxState, Sinic::Device::VirtualReg::rxUnique, rxUnique, Sinic::Device::VirtualReg::TxDone, Sinic::Base::txEnable, txFifoBlock, txIdle, txKick(), txList, txState, Sinic::Device::VirtualReg::txUnique, txUnique, Sinic::Regs::VirtualMask, virtualRegs, and Sinic::Regs::VirtualShift.
Member Data Documentation
_maxVnicDistance
int Sinic::Device::_maxVnicDistance private
Definition at line 281 of file sinic.hh.
Referenced by regStats(), resetStats(), and rxKick().
avgVnicDistance
Stats::Formula Sinic::Device::avgVnicDistance private
Definition at line 279 of file sinic.hh.
Referenced by regStats().
Command
uint32_t Sinic::Device::Command
Definition at line 110 of file sinic.hh.
Config
uint32_t Sinic::Device::Config
Definition at line 109 of file sinic.hh.
dmaReadDelay
Tick Sinic::Device::dmaReadDelay protected
Definition at line 246 of file sinic.hh.
Referenced by Device().
dmaReadFactor
Tick Sinic::Device::dmaReadFactor protected
Definition at line 247 of file sinic.hh.
Referenced by Device().
dmaWriteDelay
Tick Sinic::Device::dmaWriteDelay protected
Definition at line 248 of file sinic.hh.
Referenced by Device().
dmaWriteFactor
Tick Sinic::Device::dmaWriteFactor protected
Definition at line 249 of file sinic.hh.
Referenced by Device().
HwAddr
uint64_t Sinic::Device::HwAddr
Definition at line 131 of file sinic.hh.
IntrMask
uint32_t Sinic::Device::IntrMask
Definition at line 112 of file sinic.hh.
IntrStatus
uint32_t Sinic::Device::IntrStatus
Definition at line 111 of file sinic.hh.
maxVnicDistance
Stats::Scalar Sinic::Device::maxVnicDistance private
Definition at line 278 of file sinic.hh.
Referenced by regStats(), and rxKick().
numVnicDistance
Stats::Scalar Sinic::Device::numVnicDistance private
Definition at line 277 of file sinic.hh.
Referenced by regStats(), and rxKick().
regs
struct { ... } Sinic::Device::regs
device register file
Referenced by changeConfig(), devIntrChangeMask(), devIntrClear(), devIntrPost(), prepareRead(), recvPacket(), reset(), rxFilter(), rxKick(), serialize(), transmit(), txKick(), unserialize(), and write().
rxActive
int Sinic::Device::rxActive protected
Definition at line 161 of file sinic.hh.
Referenced by reset(), rxKick(), serialize(), and unserialize().
rxBusy
VirtualList Sinic::Device::rxBusy protected
Definition at line 160 of file sinic.hh.
Referenced by reset(), rxKick(), serialize(), unserialize(), and write().
rxBusyCount
int Sinic::Device::rxBusyCount protected
Definition at line 164 of file sinic.hh.
Referenced by prepareRead(), reset(), rxKick(), serialize(), unserialize(), and write().
RxData
uint64_t Sinic::Device::RxData
Definition at line 125 of file sinic.hh.
rxDirtyCount
int Sinic::Device::rxDirtyCount protected
Definition at line 166 of file sinic.hh.
Referenced by prepareRead(), reset(), rxKick(), serialize(), and unserialize().
rxDmaAddr
Addr Sinic::Device::rxDmaAddr protected
Definition at line 178 of file sinic.hh.
Referenced by rxDmaDone(), and rxKick().
rxDmaData
uint8_t* Sinic::Device::rxDmaData protected
Definition at line 179 of file sinic.hh.
Referenced by rxDmaDone(), and rxKick().
rxDmaEvent
EventFunctionWrapper Sinic::Device::rxDmaEvent protected
Definition at line 241 of file sinic.hh.
Referenced by Device(), and rxKick().
rxDmaLen
unsigned Sinic::Device::rxDmaLen protected
Definition at line 180 of file sinic.hh.
Referenced by rxDmaDone(), and rxKick().
RxDone
uint64_t Sinic::Device::RxDone
Definition at line 126 of file sinic.hh.
rxEmpty
bool Sinic::Device::rxEmpty protected
Definition at line 176 of file sinic.hh.
Referenced by devIntrPost(), reset(), rxKick(), serialize(), and unserialize().
rxFifo
PacketFifo Sinic::Device::rxFifo protected
Definition at line 174 of file sinic.hh.
Referenced by prepareRead(), recvPacket(), reset(), rxKick(), serialize(), unserialize(), and write().
RxFifoHigh
uint32_t Sinic::Device::RxFifoHigh
Definition at line 123 of file sinic.hh.
RxFifoLow
uint32_t Sinic::Device::RxFifoLow
Definition at line 121 of file sinic.hh.
rxFifoPtr
PacketFifo::iterator Sinic::Device::rxFifoPtr protected
Definition at line 175 of file sinic.hh.
Referenced by prepareRead(), recvPacket(), reset(), rxKick(), serialize(), and unserialize().
RxFifoSize
uint32_t Sinic::Device::RxFifoSize
Definition at line 119 of file sinic.hh.
rxKickTick
Tick Sinic::Device::rxKickTick protected
Definition at line 196 of file sinic.hh.
Referenced by rxKick().
rxList
VirtualList Sinic::Device::rxList protected
Definition at line 159 of file sinic.hh.
Referenced by reset(), rxKick(), serialize(), unserialize(), and write().
rxLow
bool Sinic::Device::rxLow protected
Definition at line 177 of file sinic.hh.
Referenced by prepareRead(), reset(), rxKick(), serialize(), and unserialize().
rxMappedCount
int Sinic::Device::rxMappedCount protected
Definition at line 165 of file sinic.hh.
Referenced by prepareRead(), reset(), rxKick(), serialize(), and unserialize().
RxMaxCopy
uint32_t Sinic::Device::RxMaxCopy
Definition at line 113 of file sinic.hh.
RxMaxIntr
uint32_t Sinic::Device::RxMaxIntr
Definition at line 118 of file sinic.hh.
rxState
RxState Sinic::Device::rxState protected
Definition at line 173 of file sinic.hh.
Referenced by reset(), rxDmaDone(), rxKick(), serialize(), txDmaDone(), unserialize(), and write().
RxStatus
uint64_t Sinic::Device::RxStatus
Definition at line 132 of file sinic.hh.
rxUnique
Counter Sinic::Device::rxUnique protected
Definition at line 156 of file sinic.hh.
Referenced by unserialize(), and write().
RxWait
uint64_t Sinic::Device::RxWait
Definition at line 127 of file sinic.hh.
totalVnicDistance
Stats::Scalar Sinic::Device::totalVnicDistance private
Statistics.
Definition at line 276 of file sinic.hh.
Referenced by regStats(), and rxKick().
TxData
uint64_t Sinic::Device::TxData
Definition at line 128 of file sinic.hh.
txDmaAddr
Addr Sinic::Device::txDmaAddr protected
Definition at line 188 of file sinic.hh.
Referenced by txDmaDone(), and txKick().
txDmaData
uint8_t* Sinic::Device::txDmaData protected
Definition at line 189 of file sinic.hh.
Referenced by txDmaDone(), and txKick().
txDmaEvent
EventFunctionWrapper Sinic::Device::txDmaEvent protected
Definition at line 244 of file sinic.hh.
Referenced by Device(), and txKick().
txDmaLen
int Sinic::Device::txDmaLen protected
Definition at line 190 of file sinic.hh.
Referenced by txDmaDone(), and txKick().
TxDone
uint64_t Sinic::Device::TxDone
Definition at line 129 of file sinic.hh.
txEvent
EventFunctionWrapper Sinic::Device::txEvent protected
Definition at line 211 of file sinic.hh.
Referenced by serialize(), transferDone(), and unserialize().
txFifo
PacketFifo Sinic::Device::txFifo protected
Definition at line 183 of file sinic.hh.
Referenced by prepareRead(), reset(), serialize(), transferDone(), transmit(), txKick(), and unserialize().
TxFifoHigh
uint32_t Sinic::Device::TxFifoHigh
Definition at line 124 of file sinic.hh.
TxFifoLow
uint32_t Sinic::Device::TxFifoLow
Definition at line 122 of file sinic.hh.
TxFifoSize
uint32_t Sinic::Device::TxFifoSize
Definition at line 120 of file sinic.hh.
txFull
bool Sinic::Device::txFull protected
Definition at line 184 of file sinic.hh.
Referenced by devIntrPost(), reset(), serialize(), txKick(), and unserialize().
txKickTick
Tick Sinic::Device::txKickTick protected
Definition at line 199 of file sinic.hh.
Referenced by txKick().
txList
VirtualList Sinic::Device::txList protected
Definition at line 162 of file sinic.hh.
Referenced by reset(), serialize(), txKick(), unserialize(), and write().
TxMaxCopy
uint32_t Sinic::Device::TxMaxCopy
Definition at line 114 of file sinic.hh.
txPacket
EthPacketPtr Sinic::Device::txPacket protected
Definition at line 185 of file sinic.hh.
Referenced by serialize(), txKick(), and unserialize().
txPacketBytes
int Sinic::Device::txPacketBytes protected
Definition at line 187 of file sinic.hh.
Referenced by serialize(), and unserialize().
txPacketOffset
int Sinic::Device::txPacketOffset protected
Definition at line 186 of file sinic.hh.
Referenced by serialize(), txKick(), and unserialize().
txState
TxState Sinic::Device::txState protected
Definition at line 182 of file sinic.hh.
Referenced by reset(), rxDmaDone(), serialize(), txDmaDone(), txKick(), unserialize(), and write().
txUnique
Counter Sinic::Device::txUnique protected
Definition at line 157 of file sinic.hh.
Referenced by unserialize(), and write().
TxWait
uint64_t Sinic::Device::TxWait
Definition at line 130 of file sinic.hh.
VirtualCount
uint32_t Sinic::Device::VirtualCount
Definition at line 117 of file sinic.hh.
virtualRegs
VirtualRegs Sinic::Device::virtualRegs protected
Definition at line 158 of file sinic.hh.
Referenced by prepareIO(), prepareRead(), reset(), rxKick(), serialize(), txKick(), unserialize(), and write().
ZeroCopyMark
uint32_t Sinic::Device::ZeroCopyMark
Definition at line 116 of file sinic.hh.
ZeroCopySize
uint32_t Sinic::Device::ZeroCopySize
Definition at line 115 of file sinic.hh.
The documentation for this class was generated from the following files:
dev/net/sinic.hh
dev/net/sinic.cc