gem5: ComputeUnit Class Reference
ComputeUnit Class Reference
#include <compute_unit.hh>
Classes
class CUExitCallback
class DataPort
Data access Port.
class DTLBPort
Data TLB port.
class ITLBPort
class LDSPort
the port intended to communicate between the CU and its LDS
class SQCPort
class waveIdentifier
class waveQueue
Public Types
typedef ComputeUnitParams Params
typedef std::unordered_map< Addr, std::pair< int, int > > pageDataStruct
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
void registerEvent (uint32_t simdId, uint32_t regIdx, uint32_t operandSize, uint64_t when, uint8_t newStatus)
void updateEvents ()
ComputeUnit (const Params *p)
~ComputeUnit ()
int spBypassLength ()
int dpBypassLength ()
int storeBusLength ()
int loadBusLength ()
int wfSize () const
void resizeRegFiles (int num_cregs, int num_sregs, int num_dregs)
void exec ()
void initiateFetch (Wavefront *wavefront)
void fetch (PacketPtr pkt, Wavefront *wavefront)
void fillKernelState (Wavefront *w, NDRange *ndr)
void startWavefront (Wavefront *w, int waveId, LdsChunk *ldsChunk, NDRange *ndr)
void StartWorkgroup (NDRange *ndr)
int ReadyWorkgroup (NDRange *ndr)
bool isVecAlu (int unitId)
bool isGlbMem (int unitId)
bool isShrMem (int unitId)
int GlbMemUnitId ()
int ShrMemUnitId ()
int nextGlbRdBus ()
int nextLocRdBus ()
int AllAtBarrier (uint32_t _barrier_id, uint32_t bcnt, uint32_t bslots)
bool cedeSIMD (int simdId, int wfSlotId)
template<typename c0 , typename c1 >
void doSmReturn (GPUDynInstPtr gpuDynInst)
virtual void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
void sendRequest (GPUDynInstPtr gpuDynInst, int index, PacketPtr pkt)
void sendSyncRequest (GPUDynInstPtr gpuDynInst, int index, PacketPtr pkt)
void injectGlobalMemFence (GPUDynInstPtr gpuDynInst, bool kernelLaunch=true, RequestPtr req=nullptr)
void handleMemPacket (PacketPtr pkt, int memport_index)
bool processTimingPacket (PacketPtr pkt)
void processFetchReturn (PacketPtr pkt)
void updatePageDivergenceDist (Addr addr)
MasterID masterId ()
bool isDone () const
bool isSimdDone (uint32_t) const
void updateInstStats (GPUDynInstPtr gpuDynInst)
void regStats () override
Callback to set stat parameters.
LdsState & getLds () const
int32_t getRefCounter (const uint32_t dispatchId, const uint32_t wgId) const
int cacheLineSize () const
bool sendToLds (GPUDynInstPtr gpuDynInst) __attribute__((warn_unused_result))
send a general request to the LDS make sure to look at the return value here as your request might be NACK'd and returning false means that you have to have some backup plan
LDSPort * getLdsPort () const
Port & getPort (const std::string &if_name, PortID idx) override
Get a port with a given name and index.
uint64_t getAndIncSeqNum ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Public Attributes
FetchStage fetchStage
ScoreboardCheckStage scoreboardCheckStage
ScheduleStage scheduleStage
ExecStage execStage
GlobalMemPipeline globalMemoryPipe
LocalMemPipeline localMemoryPipe
std::vector< std::vector< Wavefront * > > readyList
std::vector< std::vector< std::pair< Wavefront *, WAVE_STATUS > > > waveStatusList
std::vector< std::pair< Wavefront *, DISPATCH_STATUS > > dispatchList
int rrNextMemID
int rrNextALUWp
std::vector< std::vector< Wavefront * > > wfList
int cu_id
std::vector< VectorRegisterFile * > vrf
int numSIMDs
int spBypassPipeLength
int dpBypassPipeLength
int issuePeriod
int numGlbMemUnits
int numLocMemUnits
std::vector< uint64_t > lastExecCycle
bool perLaneTLB
int prefetchDepth
int prefetchStride
std::vector< Addr > lastVaddrCU
std::vector< std::vector< Addr > > lastVaddrSimd
std::vector< std::vector< std::vector< Addr > > > lastVaddrWF
Enums::PrefetchType prefetchType
EXEC_POLICY exec_policy
bool xact_cas_mode
bool debugSegFault
bool functionalTLB
bool localMemBarrier
bool countPages
Shader * shader
uint32_t barrier_id
std::vector< WaitClass > aluPipe
std::vector< WaitClass > wfWait
std::vector< WaitClass > vrfToGlobalMemPipeBus
std::vector< WaitClass > vrfToLocalMemPipeBus
int nextGlbMemBus
int nextLocMemBus
WaitClass glbMemToVrfBus
WaitClass locMemToVrfBus
uint32_t vrfToCoalescerBusWidth
uint32_t coalescerToVrfBusWidth
uint32_t numCyclesPerStoreTransfer
uint32_t numCyclesPerLoadTransfer
Tick req_tick_latency
Tick resp_tick_latency
std::vector< int > vectorRegsReserved
uint32_t numVecRegsPerSimd
std::vector< std::pair< uint32_t, uint32_t > > regIdxVec
std::vector< uint64_t > timestampVec
std::vector< uint8_t > statusVec
std::map< Addr, int > pagesTouched
Stats::Scalar vALUInsts
Stats::Formula vALUInstsPerWF
Stats::Scalar sALUInsts
Stats::Formula sALUInstsPerWF
Stats::Scalar instCyclesVALU
Stats::Scalar instCyclesSALU
Stats::Scalar threadCyclesVALU
Stats::Formula vALUUtilization
Stats::Scalar ldsNoFlatInsts
Stats::Formula ldsNoFlatInstsPerWF
Stats::Scalar flatVMemInsts
Stats::Formula flatVMemInstsPerWF
Stats::Scalar flatLDSInsts
Stats::Formula flatLDSInstsPerWF
Stats::Scalar vectorMemWrites
Stats::Formula vectorMemWritesPerWF
Stats::Scalar vectorMemReads
Stats::Formula vectorMemReadsPerWF
Stats::Scalar scalarMemWrites
Stats::Formula scalarMemWritesPerWF
Stats::Scalar scalarMemReads
Stats::Formula scalarMemReadsPerWF
Stats::Scalar tlbRequests
Stats::Scalar tlbCycles
Stats::Formula tlbLatency
Stats::Vector hitsPerTLBLevel
Stats::Scalar ldsBankAccesses
Stats::Distribution ldsBankConflictDist
Stats::Distribution pageDivergenceDist
Stats::Scalar dynamicGMemInstrCnt
Stats::Scalar dynamicLMemInstrCnt
Stats::Scalar wgBlockedDueLdsAllocation
Stats::Scalar numInstrExecuted
Stats::Distribution execRateDist
Stats::Scalar numVecOpsExecuted
Stats::Scalar totalCycles
Stats::Formula vpc
Stats::Formula ipc
Stats::Distribution controlFlowDivergenceDist
Stats::Distribution activeLanesPerGMemInstrDist
Stats::Distribution activeLanesPerLMemInstrDist
Stats::Formula numALUInstsExecuted
Stats::Scalar numTimesWgBlockedDueVgprAlloc
Stats::Scalar numCASOps
Stats::Scalar numFailedCASOps
Stats::Scalar completedWfs
std::vector< bool > vectorAluInstAvail
int shrMemInstAvail
int glbMemInstAvail
pageDataStruct pageAccesses
CUExitCallback * cuExitCallback
LDSPort * ldsPort = nullptr
The port to access the Local Data Store Can be connected to a LDS object.
std::vector< DataPort * > memPort
The memory port for SIMD data accesses.
std::vector< DTLBPort * > tlbPort
SQCPort * sqcPort
ITLBPort * sqcTLBPort
std::map< unsigned, waveQueue > xactCasLoadMap
Protected Attributes
MasterID _masterId
LdsState & lds
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Private Attributes
const int _cacheLineSize
uint64_t globalSeqNum
int wavefrontSize
GPUStaticInst * kernelLaunchInst
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Detailed Description
Definition at line 94 of file compute_unit.hh.
Member Typedef Documentation
pageDataStruct
typedef std::unordered_map<Addr, std::pair<int, int> > ComputeUnit::pageDataStruct
Definition at line 399 of file compute_unit.hh.
Params
typedef ComputeUnitParams ComputeUnit::Params
Definition at line 135 of file compute_unit.hh.
Constructor & Destructor Documentation
ComputeUnit()
ComputeUnit::ComputeUnit (const Params * p)
This check is necessary because std::bitset only provides conversion to unsigned long or unsigned long long via to_ulong() or to_ullong(). there are * a few places in the code where to_ullong() is used, however if VSZ is larger than a value the host can support then bitset will throw a runtime exception. we should remove all use of to_long() or to_ullong() so we can have VSZ greater than 64b, however until that is done this assert is required.
Definition at line 61 of file compute_unit.cc.
References coalescerToVrfBusWidth, cuExitCallback, exec_policy, fatal, fatal_if, ArmISA::i, isPowerOf2(), ArmISA::j, MipsISA::k, lastExecCycle, lastVaddrCU, lastVaddrSimd, lastVaddrWF, lds, memPort, numCyclesPerLoadTransfer, numCyclesPerStoreTransfer, numSIMDs, numVecRegsPerSimd, OLDEST, perLaneTLB, registerExitCallback(), RR, LdsState::setParent(), tlbPort, vrf, vrfToCoalescerBusWidth, wavefrontSize, wfList, wfSize(), and xactCasLoadMap.
Referenced by ComputeUnit::DataPort::processMemRespEvent().
~ComputeUnit()
ComputeUnit::~ComputeUnit ()
Definition at line 162 of file compute_unit.cc.
References cuExitCallback, dispatchList, ArmISA::i, ArmISA::j, lastVaddrCU, lastVaddrSimd, ldsPort, Shader::n_wf, numSIMDs, readyList, shader, vectorAluInstAvail, waveStatusList, and wfList.
Member Function Documentation
AllAtBarrier()
int ComputeUnit::AllAtBarrier (uint32_t _barrier_id, uint32_t bcnt, uint32_t bslots)
Definition at line 448 of file compute_unit.cc.
References Wavefront::barrierCnt, Wavefront::barrierId, cu_id, DPRINTF, Shader::n_wf, numSIMDs, Wavefront::outstandingReqs, Wavefront::S_RUNNING, shader, Wavefront::status, MipsISA::w, and wfList.
Referenced by nextLocRdBus(), and Wavefront::ready().
cacheLineSize()
int ComputeUnit::cacheLineSize () const inline
Definition at line 394 of file compute_unit.hh.
References __attribute__(), _cacheLineSize, and sendToLds().
Referenced by FetchUnit::initiateFetch().
cedeSIMD()
bool ComputeUnit::cedeSIMD (int simdId, int wfSlotId)
Definition at line 486 of file compute_unit.cc.
References ComputeUnit::waveIdentifier::simdId, ComputeUnit::waveIdentifier::wfSlotId, xact_cas_mode, and xactCasLoadMap.
Referenced by ScoreboardCheckStage::exec(), and nextLocRdBus().
doSmReturn()
template<typename c0 , typename c1 > void ComputeUnit::doSmReturn (GPUDynInstPtr gpuDynInst)
Referenced by nextLocRdBus().
dpBypassLength()
int ComputeUnit::dpBypassLength () inline
Definition at line 249 of file compute_unit.hh.
References dpBypassPipeLength.
Referenced by VectorRegisterFile::exec().
exec()
void ComputeUnit::exec ()
Definition at line 534 of file compute_unit.cc.
References FetchStage::exec(), LocalMemPipeline::exec(), ScheduleStage::exec(), GlobalMemPipeline::exec(), ScoreboardCheckStage::exec(), ExecStage::exec(), execStage, fetchStage, globalMemoryPipe, localMemoryPipe, scheduleStage, scoreboardCheckStage, totalCycles, and updateEvents().
Referenced by wfSize().
fetch()
void ComputeUnit::fetch (PacketPtr pkt, Wavefront * wavefront)
Referenced by wfSize().
fillKernelState()
void ComputeUnit::fillKernelState (Wavefront * w, NDRange * ndr)
Definition at line 181 of file compute_unit.cc.
References HsaQueueEntry::args, Wavefront::computeActualWgSz(), HsaQueueEntry::cRegCount, HsaQueueEntry::dRegCount, HsaQueueEntry::gdSize, Wavefront::gridSz, Wavefront::kernelArgs, HsaQueueEntry::privMemPerItem, Wavefront::privSizePerItem, NDRange::q, Wavefront::resizeRegFiles(), Wavefront::roBase, HsaQueueEntry::roMemStart, HsaQueueEntry::roMemTotal, Wavefront::roSize, HsaQueueEntry::spillMemPerItem, Wavefront::spillSizePerItem, HsaQueueEntry::sRegCount, HsaQueueEntry::wgSize, Wavefront::wgSz, and Wavefront::workGroupSz.
Referenced by StartWorkgroup(), and wfSize().
getAndIncSeqNum()
uint64_t ComputeUnit::getAndIncSeqNum () inline
Definition at line 742 of file compute_unit.hh.
References globalSeqNum.
Referenced by StartWorkgroup().
getLds()
LdsState& ComputeUnit::getLds () const inline
Definition at line 386 of file compute_unit.hh.
References getRefCounter(), and lds.
Referenced by HsailISA::Ret::execute().
getLdsPort()
LDSPort* ComputeUnit::getLdsPort () const inline
Definition at line 678 of file compute_unit.hh.
References ldsPort.
getPort()
Port& ComputeUnit::getPort (const std::string & if_name, PortID idx) inline override virtual
Get a port with a given name and index.
This is used at binding time and returns a reference to a protocol-agnostic port.
Parameters
if_name Port name
idx Index in the case of a VectorPort
Returns
A reference to the given port
Reimplemented from SimObject.
Definition at line 695 of file compute_unit.hh.
References csprintf(), fatal, ldsPort, SimObject::name(), panic, sqcPort, and sqcTLBPort.
getRefCounter()
int32_t ComputeUnit::getRefCounter (const uint32_t dispatchId, const uint32_t wgId) const
Definition at line 1760 of file compute_unit.cc.
References LdsState::getRefCounter(), and lds.
Referenced by getLds(), and Wavefront::ready().
GlbMemUnitId()
int ComputeUnit::GlbMemUnitId () inline
Definition at line 269 of file compute_unit.hh.
References GLBMEM_PIPE.
Referenced by ScoreboardCheckStage::exec(), Wavefront::exec(), and Wavefront::updateResources().
handleMemPacket()
void ComputeUnit::handleMemPacket (PacketPtr pkt, int memport_index)
Referenced by nextLocRdBus().
init()
void ComputeUnit::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 550 of file compute_unit.cc.
References aluPipe, BLOCKED, dispatchList, EMPTY, execStage, fatal_if, fetchStage, Shader::funcargs_size, glbMemInstAvail, glbMemToVrfBus, globalMemoryPipe, ArmISA::i, WaitClass::init(), FetchStage::init(), LocalMemPipeline::init(), ScheduleStage::init(), GlobalMemPipeline::init(), ScoreboardCheckStage::init(), ExecStage::init(), ArmISA::j, localMemoryPipe, locMemToVrfBus, Shader::n_wf, nextGlbMemBus, nextLocMemBus, numGlbMemUnits, numLocMemUnits, numSIMDs, readyList, scheduleStage, scoreboardCheckStage, shader, shrMemInstAvail, Shader::tick_cnt, Shader::ticks(), vectorAluInstAvail, vectorRegsReserved, vrfToGlobalMemPipeBus, vrfToLocalMemPipeBus, wavefrontSize, waveStatusList, wfList, and wfWait.
Referenced by nextLocRdBus().
initiateFetch()
void ComputeUnit::initiateFetch (Wavefront * wavefront)
Referenced by wfSize().
injectGlobalMemFence()
void ComputeUnit::injectGlobalMemFence (GPUDynInstPtr gpuDynInst, bool kernelLaunch = true, RequestPtr req = nullptr)
Definition at line 941 of file compute_unit.cc.
References Request::KERNEL, masterId(), MemCmd::MemFenceReq, and sendSyncRequest().
Referenced by HsailISA::Ret::execute(), HsailISA::MemFence::initiateAcc(), nextLocRdBus(), and StartWorkgroup().
isDone()
bool ComputeUnit::isDone () const
Definition at line 1731 of file compute_unit.cc.
References glbMemToVrfBus, globalMemoryPipe, ArmISA::i, GlobalMemPipeline::isGMLdRespFIFOWrRdy(), GlobalMemPipeline::isGMReqFIFOWrRdy(), GlobalMemPipeline::isGMStRespFIFOWrRdy(), LocalMemPipeline::isLMReqFIFOWrRdy(), LocalMemPipeline::isLMRespFIFOWrRdy(), isSimdDone(), ArmISA::j, localMemoryPipe, locMemToVrfBus, numGlbMemUnits, numLocMemUnits, numSIMDs, WaitClass::rdy(), vrfToGlobalMemPipeBus, and vrfToLocalMemPipeBus.
Referenced by masterId().
isGlbMem()
bool ComputeUnit::isGlbMem (int unitId) inline
Definition at line 267 of file compute_unit.hh.
References GLBMEM_PIPE.
Referenced by ExecStage::collectStatistics().
isShrMem()
bool ComputeUnit::isShrMem (int unitId) inline
Definition at line 268 of file compute_unit.hh.
References LDSMEM_PIPE.
Referenced by ExecStage::collectStatistics().
isSimdDone()
bool ComputeUnit::isSimdDone (uint32_t simdId) const
Definition at line 1766 of file compute_unit.cc.
References aluPipe, ArmISA::i, Shader::n_wf, numGlbMemUnits, numLocMemUnits, numSIMDs, Wavefront::S_STOPPED, shader, ArmISA::status, vrfToGlobalMemPipeBus, vrfToLocalMemPipeBus, and wfList.
Referenced by isDone(), and masterId().
isVecAlu()
bool ComputeUnit::isVecAlu (int unitId) inline
Definition at line 266 of file compute_unit.hh.
References SIMD0, and SIMD3.
Referenced by ExecStage::collectStatistics().
loadBusLength()
int ComputeUnit::loadBusLength () inline
Definition at line 251 of file compute_unit.hh.
References numCyclesPerLoadTransfer.
Referenced by LdsState::processPacket().
masterId()
MasterID ComputeUnit::masterId () inline
Definition at line 294 of file compute_unit.hh.
References _masterId, isDone(), and isSimdDone().
Referenced by FetchUnit::initiateFetch(), and injectGlobalMemFence().
nextGlbRdBus()
int ComputeUnit::nextGlbRdBus () inline
Definition at line 271 of file compute_unit.hh.
References numGlbMemUnits.
Referenced by Wavefront::exec(), and Wavefront::updateResources().
nextLocRdBus()
int ComputeUnit::nextLocRdBus () inline
Definition at line 272 of file compute_unit.hh.
References addr, AllAtBarrier(), cedeSIMD(), doSmReturn(), handleMemPacket(), MipsISA::index, init(), injectGlobalMemFence(), numLocMemUnits, processFetchReturn(), processTimingPacket(), sendRequest(), sendSyncRequest(), and updatePageDivergenceDist().
Referenced by Wavefront::exec(), and Wavefront::updateResources().
processFetchReturn()
void ComputeUnit::processFetchReturn (PacketPtr pkt)
Referenced by nextLocRdBus().
processTimingPacket()
bool ComputeUnit::processTimingPacket (PacketPtr pkt)
Referenced by nextLocRdBus().
ReadyWorkgroup()
int ComputeUnit::ReadyWorkgroup (NDRange * ndr)
Definition at line 366 of file compute_unit.cc.
References LdsState::canReserve(), ArmISA::d, DPRINTF, HsaQueueEntry::dRegCount, HsaQueueEntry::gdSize, ArmISA::i, ArmISA::j, lds, HsaQueueEntry::ldsSize, Shader::n_wf, numSIMDs, numTimesWgBlockedDueVgprAlloc, numVecRegsPerSimd, NDRange::q, Wavefront::S_STOPPED, shader, HsaQueueEntry::sRegCount, ArmISA::status, vrf, wfList, wfSize(), wgBlockedDueLdsAllocation, NDRange::wgId, and HsaQueueEntry::wgSize.
Referenced by wfSize().
registerEvent()
void ComputeUnit::registerEvent (uint32_t simdId, uint32_t regIdx, uint32_t operandSize, uint64_t when, uint8_t newStatus) inline
Definition at line 222 of file compute_unit.hh.
References updateEvents().
Referenced by VectorRegisterFile::exec().
regStats()
void ComputeUnit::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 1398 of file compute_unit.cc.
References activeLanesPerGMemInstrDist, activeLanesPerLMemInstrDist, completedWfs, controlFlowDivergenceDist, csprintf(), Stats::DataWrap< Derived, InfoProxyType >::desc(), dynamicGMemInstrCnt, dynamicLMemInstrCnt, execRateDist, execStage, fetchStage, flatLDSInsts, flatLDSInstsPerWF, flatVMemInsts, flatVMemInstsPerWF, globalMemoryPipe, hitsPerTLBLevel, ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), Stats::Distribution::init(), instCyclesSALU, instCyclesVALU, ipc, ldsBankAccesses, ldsBankConflictDist, ldsNoFlatInsts, ldsNoFlatInstsPerWF, localMemoryPipe, SimObject::name(), Stats::DataWrap< Derived, InfoProxyType >::name(), numALUInstsExecuted, numCASOps, numFailedCASOps, numInstrExecuted, numTimesWgBlockedDueVgprAlloc, numVecOpsExecuted, pageDivergenceDist, FetchStage::regStats(), ScheduleStage::regStats(), ScoreboardCheckStage::regStats(), ExecStage::regStats(), LocalMemPipeline::regStats(), GlobalMemPipeline::regStats(), Stats::Group::regStats(), sALUInsts, sALUInstsPerWF, scalarMemReads, scalarMemReadsPerWF, scalarMemWrites, scalarMemWritesPerWF, scheduleStage, scoreboardCheckStage, Stats::DataWrapVec< Derived, InfoProxyType >::subname(), threadCyclesVALU, tlbCycles, tlbLatency, tlbRequests, totalCycles, vALUInsts, vALUInstsPerWF, vALUUtilization, vectorMemReads, vectorMemReadsPerWF, vectorMemWrites, vectorMemWritesPerWF, vpc, wfSize(), and wgBlockedDueLdsAllocation.
resizeRegFiles()
void ComputeUnit::resizeRegFiles (int num_cregs, int num_sregs, int num_dregs)
Referenced by wfSize().
sendRequest()
void ComputeUnit::sendRequest (GPUDynInstPtr gpuDynInst, int index, PacketPtr pkt)
Definition at line 743 of file compute_unit.cc.
References Packet::cmd, cu_id, curTick(), Packet::dataStatic(), debugSegFault, DPRINTF, fatal, Process::fixupStackFault(), functionalTLB, Packet::getAddr(), ThreadContext::getProcessPtr(), Packet::getPtr(), Packet::getSize(), Shader::gpuTc, hitsPerTLBLevel, MipsISA::index, Packet::isRead(), Packet::isWrite(), MemCmd::MemFenceReq, memPort, MipsISA::p, panic, perLaneTLB, Process::pTable, BaseTLB::Read, Packet::req, req_tick_latency, safe_cast(), X86ISA::GpuTLB::TranslationState::saved, EventManager::schedule(), Packet::senderState, shader, Shader::timingSim, tlbCycles, X86ISA::GpuTLB::TranslationState::tlbEntry, tlbPort, tlbRequests, EmulationPageTable::translate(), updatePageDivergenceDist(), MipsISA::vaddr, and BaseTLB::Write.
Referenced by nextLocRdBus().
sendSyncRequest()
void ComputeUnit::sendSyncRequest (GPUDynInstPtr gpuDynInst, int index, PacketPtr pkt)
Definition at line 923 of file compute_unit.cc.
References cu_id, curTick(), DPRINTF, MipsISA::index, memPort, Packet::req, req_tick_latency, EventManager::schedule(), and Packet::senderState.
Referenced by injectGlobalMemFence(), and nextLocRdBus().
sendToLds()
bool ComputeUnit::sendToLds (GPUDynInstPtr gpuDynInst)
send a general request to the LDS make sure to look at the return value here as your request might be NACK'd and returning false means that you have to have some backup plan
Definition at line 1797 of file compute_unit.cc.
References ldsPort, MemCmd::ReadReq, Packet::senderState, and ComputeUnit::LDSPort::sendTimingReq().
Referenced by cacheLineSize(), and LocalMemPipeline::exec().
ShrMemUnitId()
int ComputeUnit::ShrMemUnitId () inline
Definition at line 270 of file compute_unit.hh.
References LDSMEM_PIPE.
Referenced by ScoreboardCheckStage::exec(), Wavefront::exec(), and Wavefront::updateResources().
spBypassLength()
int ComputeUnit::spBypassLength () inline
Definition at line 248 of file compute_unit.hh.
References spBypassPipeLength.
Referenced by ConditionRegisterState::exec(), VectorRegisterFile::exec(), Wavefront::exec(), and Wavefront::updateResources().
startWavefront()
void ComputeUnit::startWavefront (Wavefront * w, int waveId, LdsChunk * ldsChunk, NDRange * ndr)
Definition at line 228 of file compute_unit.cc.
References Wavefront::actualWgSz, Wavefront::actualWgSzTotal, Wavefront::barCnt, barrier_id, Wavefront::barrierCnt, Wavefront::barrierId, Wavefront::barrierSlots, HsaQueueEntry::code_ptr, cu_id, NDRange::dispatchId, Wavefront::dispatchId, divCeil(), DPRINTF, Wavefront::dropFetch, NDRange::globalWgId, LdsState::increaseRefCounter(), Wavefront::initMask, Wavefront::instructionBuffer, MipsISA::k, Wavefront::kernId, lds, Wavefront::ldsChunk, M5_VAR_USED, Wavefront::maxBarCnt, NDRange::numWg, Wavefront::oldBarrierCnt, Wavefront::pendingFetch, Wavefront::privBase, HsaQueueEntry::privMemPerItem, HsaQueueEntry::privMemStart, Wavefront::pushToReconvergenceStack(), NDRange::q, Wavefront::simdId, Wavefront::spillBase, HsaQueueEntry::spillMemPerItem, HsaQueueEntry::spillMemStart, Wavefront::spillWidth, Wavefront::stalledAtBarrier, Wavefront::start(), Wavefront::wfId, wfSize(), Wavefront::wfSlotId, Wavefront::wgId, Wavefront::workGroupId, Wavefront::workItemFlatId, and Wavefront::workItemId.
Referenced by StartWorkgroup(), and wfSize().
StartWorkgroup()
void ComputeUnit::StartWorkgroup (NDRange * ndr)
Definition at line 312 of file compute_unit.cc.
References Wavefront::actualWgSzTotal, barrier_id, NDRange::dispatchId, HsaQueueEntry::dRegCount, fillKernelState(), getAndIncSeqNum(), NDRange::globalWgId, Shader::impl_kern_boundary_sync, injectGlobalMemFence(), kernelLaunchInst, lds, HsaQueueEntry::ldsSize, ArmISA::m, Shader::n_wf, numSIMDs, numVecRegsPerSimd, NDRange::q, Wavefront::reservedVectorRegs, LdsState::reserveSpace(), Wavefront::S_STOPPED, shader, HsaQueueEntry::sRegCount, Wavefront::startVgprIndex, startWavefront(), Wavefront::status, vectorRegsReserved, vrf, MipsISA::w, wfList, and wfSize().
Referenced by wfSize().
storeBusLength()
int ComputeUnit::storeBusLength () inline
Definition at line 250 of file compute_unit.hh.
References numCyclesPerStoreTransfer.
Referenced by LdsState::processPacket().
updateEvents()
void ComputeUnit::updateEvents ()
Definition at line 201 of file compute_unit.cc.
References ArmISA::i, numSIMDs, regIdxVec, Sinic::regInfo(), shader, statusVec, Shader::tick_cnt, timestampVec, and vrf.
Referenced by exec(), and registerEvent().
updateInstStats()
void ComputeUnit::updateInstStats (GPUDynInstPtr gpuDynInst)
Definition at line 1669 of file compute_unit.cc.
References flatLDSInsts, flatVMemInsts, instCyclesSALU, instCyclesVALU, ldsNoFlatInsts, sALUInsts, scalarMemReads, scalarMemWrites, threadCyclesVALU, vALUInsts, vectorMemReads, and vectorMemWrites.
Referenced by Wavefront::exec().
updatePageDivergenceDist()
void ComputeUnit::updatePageDivergenceDist (Addr addr)
Definition at line 1702 of file compute_unit.cc.
References AlphaISA::PageBytes, pagesTouched, and roundDown().
Referenced by nextLocRdBus(), and sendRequest().
wfSize()
int ComputeUnit::wfSize () const inline
Definition at line 252 of file compute_unit.hh.
References exec(), fetch(), fillKernelState(), initiateFetch(), ReadyWorkgroup(), resizeRegFiles(), startWavefront(), StartWorkgroup(), MipsISA::w, and wavefrontSize.
Referenced by HsailISA::Call::calcAddr(), HsailISA::calcPrivAddr(), RegAddrOperand< RegOperandType >::calcVector(), NoRegAddrOperand::calcVector(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::completeAcc(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::completeAcc(), ComputeUnit(), LdsState::countBankConflicts(), HsailISA::Call::execPseudoInst(), HsailISA::LdaInst< DestDataType, AddrOperandType >::execute(), HsailISA::CbrInstBase< SRegOperand >::execute(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::Ret::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), Wavefront::getContext(), Wavefront::getStaticContextSize(), GPUDynInst::GPUDynInst(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), HsailISA::Call::MagicJoinWFBar(), HsailISA::Call::MagicMaskLower(), HsailISA::Call::MagicMaskUpper(), HsailISA::Call::MagicMostSigBroadcast(), HsailISA::Call::MagicMostSigThread(), HsailISA::Call::MagicPanic(), HsailISA::Call::MagicPrefixSum(), HsailISA::Call::MagicPrintLane(), HsailISA::Call::MagicPrintLane64(), HsailISA::Call::MagicPrintWF32(), HsailISA::Call::MagicPrintWF32ID(), HsailISA::Call::MagicPrintWF64(), HsailISA::Call::MagicPrintWFFloat(), HsailISA::Call::MagicPrintWFID64(), HsailISA::Call::MagicReduction(), HsailISA::Call::MagicSimBreak(), HsailISA::Call::MagicWaitWFBar(), HsailISA::Call::MagicXactCasLd(), ReadyWorkgroup(), regStats(), Wavefront::setContext(), startWavefront(), and StartWorkgroup().
Member Data Documentation
_cacheLineSize
const int ComputeUnit::_cacheLineSize private
Definition at line 745 of file compute_unit.hh.
Referenced by cacheLineSize().
_masterId
MasterID ComputeUnit::_masterId protected
Definition at line 300 of file compute_unit.hh.
Referenced by masterId().
activeLanesPerGMemInstrDist
Stats::Distribution ComputeUnit::activeLanesPerGMemInstrDist
Definition at line 361 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
activeLanesPerLMemInstrDist
Stats::Distribution ComputeUnit::activeLanesPerLMemInstrDist
Definition at line 362 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
aluPipe
std::vector<WaitClass> ComputeUnit::aluPipe
Definition at line 189 of file compute_unit.hh.
Referenced by Wavefront::exec(), init(), isSimdDone(), and Wavefront::updateResources().
barrier_id
uint32_t ComputeUnit::barrier_id
Definition at line 187 of file compute_unit.hh.
Referenced by startWavefront(), and StartWorkgroup().
coalescerToVrfBusWidth
uint32_t ComputeUnit::coalescerToVrfBusWidth
Definition at line 205 of file compute_unit.hh.
Referenced by ComputeUnit().
completedWfs
Stats::Scalar ComputeUnit::completedWfs
Definition at line 369 of file compute_unit.hh.
Referenced by HsailISA::Ret::execute(), and regStats().
controlFlowDivergenceDist
Stats::Distribution ComputeUnit::controlFlowDivergenceDist
Definition at line 360 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
countPages
bool ComputeUnit::countPages
Definition at line 184 of file compute_unit.hh.
cu_id
int ComputeUnit::cu_id
Definition at line 137 of file compute_unit.hh.
Referenced by AllAtBarrier(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::completeAcc(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::completeAcc(), GlobalMemPipeline::exec(), Wavefront::exec(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::Ret::execute(), HsailISA::MemFence::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), FetchUnit::fetch(), Wavefront::getContext(), Wavefront::getStaticContextSize(), GPUDynInst::initiateAcc(), FetchUnit::initiateFetch(), HsailISA::Call::MagicSimBreak(), Wavefront::popFromReconvergenceStack(), FetchUnit::processFetchReturn(), ComputeUnit::DataPort::processMemRespEvent(), Wavefront::ready(), sendRequest(), sendSyncRequest(), SRegOperand::set(), DRegOperand::set(), CRegOperand::set(), ListOperand::set(), Wavefront::setContext(), and startWavefront().
cuExitCallback
CUExitCallback* ComputeUnit::cuExitCallback
Definition at line 419 of file compute_unit.hh.
Referenced by ComputeUnit(), and ~ComputeUnit().
debugSegFault
bool ComputeUnit::debugSegFault
Definition at line 172 of file compute_unit.hh.
Referenced by sendRequest().
dispatchList
std::vector<std::pair<Wavefront*, DISPATCH_STATUS> > ComputeUnit::dispatchList
Definition at line 131 of file compute_unit.hh.
Referenced by ScheduleStage::init(), ExecStage::init(), init(), and ~ComputeUnit().
dpBypassPipeLength
int ComputeUnit::dpBypassPipeLength
Definition at line 148 of file compute_unit.hh.
Referenced by dpBypassLength().
dynamicGMemInstrCnt
Stats::Scalar ComputeUnit::dynamicGMemInstrCnt
Definition at line 344 of file compute_unit.hh.
Referenced by regStats(), and GPUDynInst::updateStats().
dynamicLMemInstrCnt
Stats::Scalar ComputeUnit::dynamicLMemInstrCnt
Definition at line 345 of file compute_unit.hh.
Referenced by regStats(), and GPUDynInst::updateStats().
exec_policy
EXEC_POLICY ComputeUnit::exec_policy
Definition at line 169 of file compute_unit.hh.
Referenced by ComputeUnit().
execRateDist
Stats::Distribution ComputeUnit::execRateDist
Definition at line 353 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
execStage
ExecStage ComputeUnit::execStage
Definition at line 100 of file compute_unit.hh.
Referenced by exec(), init(), and regStats().
fetchStage
FetchStage ComputeUnit::fetchStage
Definition at line 97 of file compute_unit.hh.
Referenced by exec(), init(), and regStats().
flatLDSInsts
Stats::Scalar ComputeUnit::flatLDSInsts
Definition at line 317 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
flatLDSInstsPerWF
Stats::Formula ComputeUnit::flatLDSInstsPerWF
Definition at line 318 of file compute_unit.hh.
Referenced by regStats().
flatVMemInsts
Stats::Scalar ComputeUnit::flatVMemInsts
Definition at line 315 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
flatVMemInstsPerWF
Stats::Formula ComputeUnit::flatVMemInstsPerWF
Definition at line 316 of file compute_unit.hh.
Referenced by regStats().
functionalTLB
bool ComputeUnit::functionalTLB
Definition at line 173 of file compute_unit.hh.
Referenced by sendRequest().
glbMemInstAvail
int ComputeUnit::glbMemInstAvail
Definition at line 380 of file compute_unit.hh.
Referenced by ScoreboardCheckStage::init(), ExecStage::init(), and init().
glbMemToVrfBus
WaitClass ComputeUnit::glbMemToVrfBus
Definition at line 200 of file compute_unit.hh.
Referenced by GlobalMemPipeline::exec(), init(), and isDone().
globalMemoryPipe
GlobalMemPipeline ComputeUnit::globalMemoryPipe
Definition at line 101 of file compute_unit.hh.
Referenced by exec(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::MemFence::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), init(), isDone(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), HsailISA::Call::MagicLoadGlobalU32Reg(), ComputeUnit::DataPort::processMemRespEvent(), Wavefront::ready(), and regStats().
globalSeqNum
uint64_t ComputeUnit::globalSeqNum private
Definition at line 746 of file compute_unit.hh.
Referenced by getAndIncSeqNum().
hitsPerTLBLevel
Stats::Vector ComputeUnit::hitsPerTLBLevel
Definition at line 336 of file compute_unit.hh.
Referenced by regStats(), and sendRequest().
instCyclesSALU
Stats::Scalar ComputeUnit::instCyclesSALU
Definition at line 310 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
instCyclesVALU
Stats::Scalar ComputeUnit::instCyclesVALU
Definition at line 309 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
ipc
Stats::Formula ComputeUnit::ipc
Definition at line 359 of file compute_unit.hh.
Referenced by regStats().
issuePeriod
int ComputeUnit::issuePeriod
Definition at line 150 of file compute_unit.hh.
Referenced by Wavefront::exec(), and Wavefront::updateResources().
kernelLaunchInst
GPUStaticInst* ComputeUnit::kernelLaunchInst private
Definition at line 748 of file compute_unit.hh.
Referenced by StartWorkgroup().
lastExecCycle
std::vector<uint64_t> ComputeUnit::lastExecCycle
Definition at line 156 of file compute_unit.hh.
Referenced by ComputeUnit(), and Wavefront::exec().
lastVaddrCU
std::vector<Addr> ComputeUnit::lastVaddrCU
Definition at line 165 of file compute_unit.hh.
Referenced by ComputeUnit(), and ~ComputeUnit().
lastVaddrSimd
std::vector<std::vector<Addr> > ComputeUnit::lastVaddrSimd
Definition at line 166 of file compute_unit.hh.
Referenced by ComputeUnit(), and ~ComputeUnit().
lastVaddrWF
std::vector<std::vector<std::vector<Addr> > > ComputeUnit::lastVaddrWF
Definition at line 167 of file compute_unit.hh.
Referenced by ComputeUnit().
lds
LdsState& ComputeUnit::lds protected
Definition at line 302 of file compute_unit.hh.
Referenced by ComputeUnit(), getLds(), getRefCounter(), ReadyWorkgroup(), startWavefront(), and StartWorkgroup().
ldsBankAccesses
Stats::Scalar ComputeUnit::ldsBankAccesses
Definition at line 338 of file compute_unit.hh.
Referenced by LdsState::processPacket(), and regStats().
ldsBankConflictDist
Stats::Distribution ComputeUnit::ldsBankConflictDist
Definition at line 339 of file compute_unit.hh.
Referenced by LdsState::processPacket(), and regStats().
ldsNoFlatInsts
Stats::Scalar ComputeUnit::ldsNoFlatInsts
Definition at line 313 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
ldsNoFlatInstsPerWF
Stats::Formula ComputeUnit::ldsNoFlatInstsPerWF
Definition at line 314 of file compute_unit.hh.
Referenced by regStats().
ldsPort
LDSPort* ComputeUnit::ldsPort = nullptr
The port to access the Local Data Store Can be connected to a LDS object.
Definition at line 675 of file compute_unit.hh.
Referenced by getLdsPort(), getPort(), sendToLds(), and ~ComputeUnit().
localMemBarrier
bool ComputeUnit::localMemBarrier
Definition at line 174 of file compute_unit.hh.
localMemoryPipe
LocalMemPipeline ComputeUnit::localMemoryPipe
Definition at line 102 of file compute_unit.hh.
Referenced by exec(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), init(), isDone(), Wavefront::ready(), and regStats().
locMemToVrfBus
WaitClass ComputeUnit::locMemToVrfBus
Definition at line 202 of file compute_unit.hh.
Referenced by LocalMemPipeline::exec(), init(), and isDone().
memPort
std::vector<DataPort*> ComputeUnit::memPort
The memory port for SIMD data accesses.
Can be connected to PhysMem for Ruby for timing simulations
Definition at line 686 of file compute_unit.hh.
Referenced by ComputeUnit(), sendRequest(), and sendSyncRequest().
nextGlbMemBus
int ComputeUnit::nextGlbMemBus
Definition at line 197 of file compute_unit.hh.
Referenced by init().
nextLocMemBus
int ComputeUnit::nextLocMemBus
Definition at line 198 of file compute_unit.hh.
Referenced by init().
numALUInstsExecuted
Stats::Formula ComputeUnit::numALUInstsExecuted
Definition at line 364 of file compute_unit.hh.
Referenced by regStats().
numCASOps
Stats::Scalar ComputeUnit::numCASOps
Definition at line 367 of file compute_unit.hh.
Referenced by AtomicOpCAS< T >::execute(), and regStats().
numCyclesPerLoadTransfer
uint32_t ComputeUnit::numCyclesPerLoadTransfer
Definition at line 207 of file compute_unit.hh.
Referenced by ComputeUnit(), and loadBusLength().
numCyclesPerStoreTransfer
uint32_t ComputeUnit::numCyclesPerStoreTransfer
Definition at line 206 of file compute_unit.hh.
Referenced by ComputeUnit(), and storeBusLength().
numFailedCASOps
Stats::Scalar ComputeUnit::numFailedCASOps
Definition at line 368 of file compute_unit.hh.
Referenced by AtomicOpCAS< T >::execute(), and regStats().
numGlbMemUnits
int ComputeUnit::numGlbMemUnits
Definition at line 153 of file compute_unit.hh.
Referenced by init(), isDone(), isSimdDone(), nextGlbRdBus(), and Wavefront::ready().
numInstrExecuted
Stats::Scalar ComputeUnit::numInstrExecuted
Definition at line 350 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
numLocMemUnits
int ComputeUnit::numLocMemUnits
Definition at line 154 of file compute_unit.hh.
Referenced by init(), isDone(), isSimdDone(), nextLocRdBus(), and Wavefront::ready().
numSIMDs
int ComputeUnit::numSIMDs
Definition at line 142 of file compute_unit.hh.
Referenced by AllAtBarrier(), ComputeUnit(), init(), isDone(), isSimdDone(), ReadyWorkgroup(), StartWorkgroup(), updateEvents(), and ~ComputeUnit().
numTimesWgBlockedDueVgprAlloc
Stats::Scalar ComputeUnit::numTimesWgBlockedDueVgprAlloc
Definition at line 366 of file compute_unit.hh.
Referenced by ReadyWorkgroup(), and regStats().
numVecOpsExecuted
Stats::Scalar ComputeUnit::numVecOpsExecuted
Definition at line 355 of file compute_unit.hh.
Referenced by Wavefront::exec(), and regStats().
numVecRegsPerSimd
uint32_t ComputeUnit::numVecRegsPerSimd
Definition at line 215 of file compute_unit.hh.
Referenced by ComputeUnit(), ReadyWorkgroup(), and StartWorkgroup().
pageAccesses
pageDataStruct ComputeUnit::pageAccesses
Definition at line 400 of file compute_unit.hh.
Referenced by GPUDynInst::updateStats().
pageDivergenceDist
Stats::Distribution ComputeUnit::pageDivergenceDist
Definition at line 343 of file compute_unit.hh.
Referenced by regStats(), and GPUDynInst::updateStats().
pagesTouched
std::map<Addr, int> ComputeUnit::pagesTouched
Definition at line 244 of file compute_unit.hh.
Referenced by updatePageDivergenceDist(), and GPUDynInst::updateStats().
perLaneTLB
bool ComputeUnit::perLaneTLB
Definition at line 159 of file compute_unit.hh.
Referenced by ComputeUnit(), and sendRequest().
prefetchDepth
int ComputeUnit::prefetchDepth
Definition at line 161 of file compute_unit.hh.
prefetchStride
int ComputeUnit::prefetchStride
Definition at line 163 of file compute_unit.hh.
prefetchType
Enums::PrefetchType ComputeUnit::prefetchType
Definition at line 168 of file compute_unit.hh.
readyList
std::vector<std::vector<Wavefront*> > ComputeUnit::readyList
Definition at line 111 of file compute_unit.hh.
Referenced by ScheduleStage::exec(), ScheduleStage::init(), ScoreboardCheckStage::init(), init(), and ~ComputeUnit().
regIdxVec
std::vector<std::pair<uint32_t, uint32_t> > ComputeUnit::regIdxVec
Definition at line 217 of file compute_unit.hh.
Referenced by updateEvents().
req_tick_latency
Tick ComputeUnit::req_tick_latency
Definition at line 209 of file compute_unit.hh.
Referenced by sendRequest(), and sendSyncRequest().
resp_tick_latency
Tick ComputeUnit::resp_tick_latency
Definition at line 210 of file compute_unit.hh.
rrNextALUWp
int ComputeUnit::rrNextALUWp
Definition at line 134 of file compute_unit.hh.
rrNextMemID
int ComputeUnit::rrNextMemID
Definition at line 133 of file compute_unit.hh.
sALUInsts
Stats::Scalar ComputeUnit::sALUInsts
Definition at line 307 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
sALUInstsPerWF
Stats::Formula ComputeUnit::sALUInstsPerWF
Definition at line 308 of file compute_unit.hh.
Referenced by regStats().
scalarMemReads
Stats::Scalar ComputeUnit::scalarMemReads
Definition at line 325 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
scalarMemReadsPerWF
Stats::Formula ComputeUnit::scalarMemReadsPerWF
Definition at line 326 of file compute_unit.hh.
Referenced by regStats().
scalarMemWrites
Stats::Scalar ComputeUnit::scalarMemWrites
Definition at line 323 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
scalarMemWritesPerWF
Stats::Formula ComputeUnit::scalarMemWritesPerWF
Definition at line 324 of file compute_unit.hh.
Referenced by regStats().
scheduleStage
ScheduleStage ComputeUnit::scheduleStage
Definition at line 99 of file compute_unit.hh.
Referenced by exec(), init(), and regStats().
scoreboardCheckStage
ScoreboardCheckStage ComputeUnit::scoreboardCheckStage
Definition at line 98 of file compute_unit.hh.
Referenced by exec(), init(), and regStats().
shader
Shader* ComputeUnit::shader
Definition at line 186 of file compute_unit.hh.
Referenced by AllAtBarrier(), FetchUnit::exec(), LocalMemPipeline::exec(), GlobalMemPipeline::exec(), ScoreboardCheckStage::exec(), ConditionRegisterState::exec(), VectorRegisterFile::exec(), Wavefront::exec(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::execute(), HsailISA::Ret::execute(), HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::execute(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::execute(), FetchUnit::init(), GlobalMemPipeline::init(), init(), FetchUnit::initiateFetch(), isSimdDone(), HsailISA::Call::MagicAtomicNRAddGlobalU32Reg(), HsailISA::Call::MagicAtomicNRAddGroupU32Reg(), HsailISA::Call::MagicLoadGlobalU32Reg(), LdsState::processPacket(), ReadyWorkgroup(), sendRequest(), StartWorkgroup(), updateEvents(), Wavefront::updateResources(), and ~ComputeUnit().
shrMemInstAvail
int ComputeUnit::shrMemInstAvail
Definition at line 377 of file compute_unit.hh.
Referenced by ScoreboardCheckStage::init(), ExecStage::init(), and init().
spBypassPipeLength
int ComputeUnit::spBypassPipeLength
Definition at line 145 of file compute_unit.hh.
Referenced by spBypassLength().
sqcPort
SQCPort* ComputeUnit::sqcPort
Definition at line 690 of file compute_unit.hh.
Referenced by FetchUnit::fetch(), and getPort().
sqcTLBPort
ITLBPort* ComputeUnit::sqcTLBPort
Definition at line 692 of file compute_unit.hh.
Referenced by getPort(), and FetchUnit::initiateFetch().
statusVec
std::vector<uint8_t> ComputeUnit::statusVec
Definition at line 219 of file compute_unit.hh.
Referenced by updateEvents().
threadCyclesVALU
Stats::Scalar ComputeUnit::threadCyclesVALU
Definition at line 311 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
timestampVec
std::vector<uint64_t> ComputeUnit::timestampVec
Definition at line 218 of file compute_unit.hh.
Referenced by updateEvents().
tlbCycles
Stats::Scalar ComputeUnit::tlbCycles
Definition at line 333 of file compute_unit.hh.
Referenced by regStats(), and sendRequest().
tlbLatency
Stats::Formula ComputeUnit::tlbLatency
Definition at line 334 of file compute_unit.hh.
Referenced by regStats().
tlbPort
std::vector<DTLBPort*> ComputeUnit::tlbPort
Definition at line 688 of file compute_unit.hh.
Referenced by ComputeUnit(), and sendRequest().
tlbRequests
Stats::Scalar ComputeUnit::tlbRequests
Definition at line 332 of file compute_unit.hh.
Referenced by regStats(), and sendRequest().
totalCycles
Stats::Scalar ComputeUnit::totalCycles
Definition at line 357 of file compute_unit.hh.
Referenced by exec(), Wavefront::exec(), and regStats().
vALUInsts
Stats::Scalar ComputeUnit::vALUInsts
Definition at line 305 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
vALUInstsPerWF
Stats::Formula ComputeUnit::vALUInstsPerWF
Definition at line 306 of file compute_unit.hh.
Referenced by regStats().
vALUUtilization
Stats::Formula ComputeUnit::vALUUtilization
Definition at line 312 of file compute_unit.hh.
Referenced by regStats().
vectorAluInstAvail
std::vector<bool> ComputeUnit::vectorAluInstAvail
Definition at line 374 of file compute_unit.hh.
Referenced by ScoreboardCheckStage::init(), ExecStage::init(), init(), and ~ComputeUnit().
vectorMemReads
Stats::Scalar ComputeUnit::vectorMemReads
Definition at line 321 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
vectorMemReadsPerWF
Stats::Formula ComputeUnit::vectorMemReadsPerWF
Definition at line 322 of file compute_unit.hh.
Referenced by regStats().
vectorMemWrites
Stats::Scalar ComputeUnit::vectorMemWrites
Definition at line 319 of file compute_unit.hh.
Referenced by regStats(), and updateInstStats().
vectorMemWritesPerWF
Stats::Formula ComputeUnit::vectorMemWritesPerWF
Definition at line 320 of file compute_unit.hh.
Referenced by regStats().
vectorRegsReserved
std::vector<int> ComputeUnit::vectorRegsReserved
Definition at line 213 of file compute_unit.hh.
Referenced by HsailISA::Ret::execute(), init(), and StartWorkgroup().
vpc
Stats::Formula ComputeUnit::vpc
Definition at line 358 of file compute_unit.hh.
Referenced by regStats().
vrf
std::vector<VectorRegisterFile*> ComputeUnit::vrf
Definition at line 140 of file compute_unit.hh.
Referenced by ScheduleStage::arbitrate(), HsailISA::LdInst< MemDataType, DestDataType, AddrOperandType >::completeAcc(), HsailISA::AtomicInst< MemDataType, AddrOperandType, NumSrcOperands, HasDst >::completeAcc(), ComputeUnit(), LocalMemPipeline::exec(), GlobalMemPipeline::exec(), Wavefront::exec(), HsailISA::Ret::execute(), SRegOperand::get(), DRegOperand::get(), Wavefront::getContext(), Wavefront::ready(), ReadyWorkgroup(), Wavefront::remap(), SRegOperand::set(), DRegOperand::set(), Wavefront::setContext(), StartWorkgroup(), updateEvents(), and Wavefront::updateResources().
vrfToCoalescerBusWidth
uint32_t ComputeUnit::vrfToCoalescerBusWidth
Definition at line 204 of file compute_unit.hh.
Referenced by ComputeUnit().
vrfToGlobalMemPipeBus
std::vector<WaitClass> ComputeUnit::vrfToGlobalMemPipeBus
Definition at line 194 of file compute_unit.hh.
Referenced by Wavefront::exec(), init(), isDone(), isSimdDone(), Wavefront::ready(), and Wavefront::updateResources().
vrfToLocalMemPipeBus
std::vector<WaitClass> ComputeUnit::vrfToLocalMemPipeBus
Definition at line 196 of file compute_unit.hh.
Referenced by Wavefront::exec(), init(), isDone(), isSimdDone(), Wavefront::ready(), and Wavefront::updateResources().
wavefrontSize
int ComputeUnit::wavefrontSize private
Definition at line 747 of file compute_unit.hh.
Referenced by ComputeUnit(), init(), and wfSize().
waveStatusList
std::vector<std::vector<std::pair<Wavefront*, WAVE_STATUS> > > ComputeUnit::waveStatusList
Definition at line 119 of file compute_unit.hh.
Referenced by ScheduleStage::init(), ScoreboardCheckStage::init(), init(), and ~ComputeUnit().
wfList
std::vector<std::vector<Wavefront*> > ComputeUnit::wfList
Definition at line 136 of file compute_unit.hh.
Referenced by AllAtBarrier(), ComputeUnit(), FetchStage::init(), init(), isSimdDone(), ReadyWorkgroup(), StartWorkgroup(), and ~ComputeUnit().
wfWait
std::vector<WaitClass> ComputeUnit::wfWait
Definition at line 191 of file compute_unit.hh.
Referenced by LocalMemPipeline::exec(), GlobalMemPipeline::exec(), Wavefront::exec(), init(), Wavefront::ready(), and Wavefront::updateResources().
wgBlockedDueLdsAllocation
Stats::Scalar ComputeUnit::wgBlockedDueLdsAllocation
Definition at line 347 of file compute_unit.hh.
Referenced by ReadyWorkgroup(), and regStats().
xact_cas_mode
bool ComputeUnit::xact_cas_mode
Definition at line 171 of file compute_unit.hh.
Referenced by cedeSIMD(), and AtomicOpCAS< T >::execute().
xactCasLoadMap
std::map<unsigned, waveQueue> ComputeUnit::xactCasLoadMap
Definition at line 740 of file compute_unit.hh.
Referenced by cedeSIMD(), ComputeUnit(), AtomicOpCAS< T >::execute(), and HsailISA::Call::MagicXactCasLd().
The documentation for this class was generated from the following files:
gpu-compute/compute_unit.hh
gpu-compute/compute_unit.cc