gem5: sc_core::sc_signal_in_if< T > Class Template Reference
sc_core::sc_signal_in_if< T > Class Template Reference abstract
#include <sc_signal_in_if.hh>
Public Member Functions
virtual const T & read () const =0
virtual const sc_event & value_changed_event () const =0
virtual bool event () const =0
Public Member Functions inherited from sc_core::sc_interface
virtual void register_port (sc_port_base &, const char *)
virtual const sc_event & default_event () const
virtual ~sc_interface ()
Protected Member Functions
sc_signal_in_if ()
Protected Member Functions inherited from sc_core::sc_interface
sc_interface ()
Private Member Functions
sc_signal_in_if (const sc_signal_in_if< T > &)
sc_signal_in_if< T > & operator= (const sc_signal_in_if< T > &)
Detailed Description
template<class T>
class sc_core::sc_signal_in_if< T >
Definition at line 55 of file sc_signal_in_if.hh.
Constructor & Destructor Documentation
sc_signal_in_if() [1/2]
template<class T> sc_core::sc_signal_in_if< T >::sc_signal_in_if () inline protected
Definition at line 63 of file sc_signal_in_if.hh.
sc_signal_in_if() [2/2]
template<class T> sc_core::sc_signal_in_if< T >::sc_signal_in_if (const sc_signal_in_if< T > &) inline private
Definition at line 67 of file sc_signal_in_if.hh.
Member Function Documentation
event()
template<class T> virtual bool sc_core::sc_signal_in_if< T >::event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, and sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >.
operator=()
template<class T> sc_signal_in_if<T>& sc_core::sc_signal_in_if< T >::operator= (const sc_signal_in_if< T > &) inline private
Definition at line 69 of file sc_signal_in_if.hh.
read()
template<class T> virtual const T& sc_core::sc_signal_in_if< T >::read () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, and sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >.
Referenced by sc_core::sc_inout< sc_dt::sc_lv< W > >::initialize(), sc_core::sc_inout< sc_dt::sc_lv< W > >::operator=(), and sc_core::sc_trace().
value_changed_event()
template<class T> virtual const sc_event& sc_core::sc_signal_in_if< T >::value_changed_event () const pure virtual
Implemented in sc_gem5::ScSignalBaseT< T, WRITER_POLICY >, and sc_gem5::ScSignalBaseT< sc_dt::sc_lv< W >, WRITER_POLICY >.
The documentation for this class was generated from the following file:
systemc/ext/channel/sc_signal_in_if.hh