gem5: MipsISA::StackTrace Class Reference
MipsISA::StackTrace Class Reference
#include <stacktrace.hh>
Public Member Functions
StackTrace ()
StackTrace (ThreadContext *tc, const StaticInstPtr &inst)
~StackTrace ()
void clear ()
bool valid () const
bool trace (ThreadContext *tc, const StaticInstPtr &inst)
const std::vector< Addr > & getstack () const
void dprintf ()
Static Public Attributes
static const int user = 1
static const int console = 2
static const int unknown = 3
Protected Types
typedef MipsISA::MachInst MachInst
Private Member Functions
bool isEntry (Addr addr)
bool decodePrologue (Addr sp, Addr callpc, Addr func, int &size, Addr &ra)
bool decodeSave (MachInst inst, int &reg, int &disp)
bool decodeStack (MachInst inst, int &disp)
void trace (ThreadContext *tc, bool is_call)
Private Attributes
ThreadContext * tc
std::vector< Addr > stack
Detailed Description
Definition at line 60 of file stacktrace.hh.
Member Typedef Documentation
MachInst
typedef MipsISA::MachInst MipsISA::StackTrace::MachInst protected
Definition at line 63 of file stacktrace.hh.
Constructor & Destructor Documentation
StackTrace() [1/2]
StackTrace::StackTrace ()
Definition at line 94 of file stacktrace.cc.
StackTrace() [2/2]
StackTrace::StackTrace (ThreadContext * tc, const StaticInstPtr & inst)
Definition at line 99 of file stacktrace.cc.
References trace().
~StackTrace()
StackTrace::~StackTrace ()
Definition at line 105 of file stacktrace.cc.
Member Function Documentation
clear()
void MipsISA::StackTrace::clear () inline
Definition at line 81 of file stacktrace.hh.
decodePrologue()
bool StackTrace::decodePrologue (Addr sp, Addr callpc, Addr func, int & size, Addr & ra) private
Definition at line 198 of file stacktrace.cc.
References decodeSave(), decodeStack(), Stats::dump(), ThreadContext::getVirtProxy(), panic, MipsISA::pc, PortProxy::read(), X86ISA::reg, MipsISA::ReturnAddressReg, and tc.
decodeSave()
bool StackTrace::decodeSave (MachInst inst, int & reg, int & disp) private
Definition at line 169 of file stacktrace.cc.
Referenced by decodePrologue().
decodeStack()
bool StackTrace::decodeStack (MachInst inst, int & disp) private
Definition at line 128 of file stacktrace.cc.
Referenced by decodePrologue().
dprintf()
void MipsISA::StackTrace::dprintf () inline
Definition at line 105 of file stacktrace.hh.
getstack()
const std::vector<Addr>& MipsISA::StackTrace::getstack () const inline
Definition at line 91 of file stacktrace.hh.
References X86ISA::stack.
isEntry()
bool StackTrace::isEntry (Addr addr) private
Definition at line 122 of file stacktrace.cc.
trace() [1/2]
void StackTrace::trace (ThreadContext * tc, bool is_call) private
Definition at line 110 of file stacktrace.cc.
References stack, tc, and user.
Referenced by StackTrace().
trace() [2/2]
bool MipsISA::StackTrace::trace (ThreadContext * tc, const StaticInstPtr & inst) inline
Definition at line 110 of file stacktrace.hh.
References StaticInst::isCall(), and StaticInst::isReturn().
valid()
bool MipsISA::StackTrace::valid () const inline
Definition at line 87 of file stacktrace.hh.
Member Data Documentation
console
const int MipsISA::StackTrace::console = 2 static
Definition at line 94 of file stacktrace.hh.
stack
std::vector<Addr> MipsISA::StackTrace::stack private
Definition at line 66 of file stacktrace.hh.
Referenced by trace().
tc
ThreadContext* MipsISA::StackTrace::tc private
Definition at line 65 of file stacktrace.hh.
Referenced by decodePrologue(), and trace().
unknown
const int MipsISA::StackTrace::unknown = 3 static
Definition at line 95 of file stacktrace.hh.
user
const int MipsISA::StackTrace::user = 1 static
Definition at line 93 of file stacktrace.hh.
Referenced by trace().
The documentation for this class was generated from the following files:
arch/mips/stacktrace.hh
arch/mips/stacktrace.cc