gem5: sc_core::sc_inout< sc_dt::sc_uint< W > > Class Reference
sc_core::sc_inout< sc_dt::sc_uint< W > > Class Reference
#include <scx_signal_uint.h>
Public Types
typedef sc_dt::sc_uint< W > data_type
typedef sc_signal_inout_if< sc_dt::sc_uint< W > > if_type
typedef sc_port< if_type, 1, SC_ONE_OR_MORE_BOUND > base_type
typedef sc_inout< sc_dt::sc_uint< W > > this_type
typedef if_type inout_if_type
typedef base_type inout_port_type
Public Member Functions
void bind (const inout_if_type &interface_)
void operator() (const inout_if_type &interface_)
void bind (inout_port_type &parent_)
void operator() (inout_port_type &parent_)
sc_inout ()
sc_inout (const char *name_)
sc_inout (inout_if_type &interface_)
sc_inout (const char *name_, inout_if_type &interface_)
sc_inout (inout_port_type &parent_)
sc_inout (const char *name_, inout_port_type &parent_)
sc_inout (this_type &parent_)
sc_inout (const char *name_, this_type &parent_)
virtual ~sc_inout ()
sc_dt::sc_uint_bitref_r operator[] (int i) const
sc_dt::sc_uint_bitref_r bit (int i) const
sc_uint_sigref & operator[] (int i)
sc_uint_sigref & bit (int i)
sc_dt::sc_uint_subref_r operator() (int left, int right) const
sc_dt::sc_uint_subref_r range (int left, int right) const
sc_uint_sigref & operator() (int left, int right)
sc_uint_sigref & range (int left, int right)
const sc_event & default_event () const
const sc_event & value_changed_event () const
const sc_dt::sc_uint< W > & read () const
operator sc_dt::uint64 () const
bool event () const
sc_event_finder & value_changed () const
bool and_reduce () const
bool nand_reduce () const
bool nor_reduce () const
bool or_reduce () const
bool xnor_reduce () const
bool xor_reduce () const
virtual void end_of_elaboration ()
virtual const char * kind () const
void initialize (const sc_dt::sc_uint< W > &value_)
void add_trace (sc_trace_file *tf_, const std::string &name_) const
virtual int concat_length (bool *xz_present_p) const
virtual sc_dt::uint64 concat_get_uint64 () const
virtual bool concat_get_ctrl (sc_dt::sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_dt::sc_digit *dst_p, int low_i) const
virtual void concat_set (sc_dt::int64 src, int low_i)
virtual void concat_set (const sc_dt::sc_signed &src, int low_i)
virtual void concat_set (const sc_dt::sc_unsigned &src, int low_i)
virtual void concat_set (sc_dt::uint64 src, int low_i)
void operator= (const this_type &new_val)
void operator= (const char *new_val)
void operator= (sc_dt::uint64 new_val)
void operator= (sc_dt::int64 new_val)
void operator= (int new_val)
void operator= (long new_val)
void operator= (short new_val)
void operator= (unsigned int new_val)
void operator= (unsigned long new_val)
void operator= (unsigned short new_val)
template<typename T >
void operator= (const sc_dt::sc_generic_base< T > &new_val)
void operator= (const sc_dt::sc_signed &new_val)
void operator= (const sc_dt::sc_unsigned &new_val)
void operator= (const sc_dt::sc_bv_base &new_val)
void operator= (const sc_dt::sc_lv_base &new_val)
void write (const sc_in< sc_dt::sc_uint< W > > &new_val)
void write (const sc_inout< sc_dt::sc_uint< W > > &new_val)
void write (const sc_dt::sc_uint< W > &new_val)
Public Member Functions inherited from sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >
sc_port ()
sc_port (const char *name)
sc_port (const sc_signal_inout_if< sc_dt::sc_uint< W > > &interface)
sc_port (const char *name, const sc_signal_inout_if< sc_dt::sc_uint< W > > &interface)
sc_port (sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > > &parent)
sc_port (const char *name, sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > > &parent)
sc_port (sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, N, P > &parent)
sc_port (const char *name, sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, N, P > &parent)
virtual ~sc_port ()
Public Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >
void operator() (sc_signal_inout_if< sc_dt::sc_uint< W > > &i)
void operator() (sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > > &p)
virtual void bind (sc_signal_inout_if< sc_dt::sc_uint< W > > &i)
virtual void bind (sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > > &p)
sc_signal_inout_if< sc_dt::sc_uint< W > > * operator-> ()
const sc_signal_inout_if< sc_dt::sc_uint< W > > * operator-> () const
sc_signal_inout_if< sc_dt::sc_uint< W > > * operator[] (int n)
const sc_signal_inout_if< sc_dt::sc_uint< W > > * operator[] (int n) const
sc_interface * get_interface ()
const sc_interface * get_interface () const
Public Member Functions inherited from sc_core::sc_port_base
sc_port_base (const char *name, int n, sc_port_policy p)
virtual ~sc_port_base ()
void warn_port_constructor () const
int maxSize () const
int size () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Member Functions
virtual int vbind (sc_interface &interface_)
virtual int vbind (sc_port_base &parent_)
void remove_traces () const
Protected Member Functions inherited from sc_core::sc_port_b< sc_signal_inout_if< sc_dt::sc_uint< W > > >
void before_end_of_elaboration ()
void end_of_elaboration ()
void start_of_simulation ()
void end_of_simulation ()
sc_port_b (int n, sc_port_policy p)
sc_port_b (const char *name, int n, sc_port_policy p)
virtual ~sc_port_b ()
int vbind (sc_interface &i)
int vbind (sc_port_base &pb)
Protected Member Functions inherited from sc_core::sc_port_base
void bind (sc_interface &)
void bind (sc_port_base &)
void report_error (const char *id, const char *add_msg) const
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Protected Attributes
sc_dt::uint64 * m_init_val_p
sc_trace_params_vec * m_traces
Private Member Functions
sc_inout (const sc_inout< sc_dt::sc_uint< W > > &)
Detailed Description
Definition at line 1074 of file scx_signal_uint.h.
Member Typedef Documentation
base_type
typedef sc_port<if_type,1,SC_ONE_OR_MORE_BOUND> sc_core::sc_inout< sc_dt::sc_uint< W > >::base_type
Definition at line 1085 of file scx_signal_uint.h.
data_type
typedef sc_dt::sc_uint<W> sc_core::sc_inout< sc_dt::sc_uint< W > >::data_type
Definition at line 1083 of file scx_signal_uint.h.
if_type
typedef sc_signal_inout_if<sc_dt::sc_uint<W> > sc_core::sc_inout< sc_dt::sc_uint< W > >::if_type
Definition at line 1084 of file scx_signal_uint.h.
inout_if_type
typedef if_type sc_core::sc_inout< sc_dt::sc_uint< W > >::inout_if_type
Definition at line 1088 of file scx_signal_uint.h.
inout_port_type
typedef base_type sc_core::sc_inout< sc_dt::sc_uint< W > >::inout_port_type
Definition at line 1089 of file scx_signal_uint.h.
this_type
typedef sc_inout<sc_dt::sc_uint<W> > sc_core::sc_inout< sc_dt::sc_uint< W > >::this_type
Definition at line 1086 of file scx_signal_uint.h.
Constructor & Destructor Documentation
sc_inout() [1/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout () inline
Definition at line 1125 of file scx_signal_uint.h.
sc_inout() [2/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (const char * name_) inline explicit
Definition at line 1129 of file scx_signal_uint.h.
sc_inout() [3/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (inout_if_type & interface_) inline explicit
Definition at line 1133 of file scx_signal_uint.h.
sc_inout() [4/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (const char * name_, inout_if_type & interface_) inline
Definition at line 1137 of file scx_signal_uint.h.
sc_inout() [5/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (inout_port_type & parent_) inline explicit
Definition at line 1141 of file scx_signal_uint.h.
sc_inout() [6/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (const char * name_, inout_port_type & parent_) inline
Definition at line 1145 of file scx_signal_uint.h.
sc_inout() [7/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (this_type & parent_) inline
Definition at line 1149 of file scx_signal_uint.h.
sc_inout() [8/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (const char * name_, this_type & parent_) inline
Definition at line 1153 of file scx_signal_uint.h.
~sc_inout()
virtual sc_core::sc_inout< sc_dt::sc_uint< W > >::~sc_inout () inline virtual
Definition at line 1160 of file scx_signal_uint.h.
sc_inout() [9/9]
sc_core::sc_inout< sc_dt::sc_uint< W > >::sc_inout (const sc_inout< sc_dt::sc_uint< W > > &) private
Member Function Documentation
add_trace()
void sc_core::sc_inout< sc_dt::sc_uint< W > >::add_trace (sc_trace_file * tf_, const std::string & name_) const inline
Definition at line 1279 of file scx_signal_uint.h.
and_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::and_reduce () const inline
Definition at line 1225 of file scx_signal_uint.h.
bind() [1/2]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::bind (const inout_if_type & interface_) inline
Definition at line 1095 of file scx_signal_uint.h.
References sc_core::sc_port_base::bind().
bind() [2/2]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::bind (inout_port_type & parent_) inline
Definition at line 1099 of file scx_signal_uint.h.
References sc_core::sc_port_base::bind().
bit() [1/2]
sc_dt::sc_uint_bitref_r sc_core::sc_inout< sc_dt::sc_uint< W > >::bit (int i) const inline
Definition at line 1169 of file scx_signal_uint.h.
References ArmISA::i.
bit() [2/2]
sc_uint_sigref& sc_core::sc_inout< sc_dt::sc_uint< W > >::bit (int i) inline
Definition at line 1173 of file scx_signal_uint.h.
concat_get_ctrl()
virtual bool sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_get_ctrl (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1296 of file scx_signal_uint.h.
concat_get_data()
virtual bool sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_get_data (sc_dt::sc_digit * dst_p, int low_i) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1299 of file scx_signal_uint.h.
concat_get_uint64()
virtual sc_dt::uint64 sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1294 of file scx_signal_uint.h.
concat_length()
virtual int sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1292 of file scx_signal_uint.h.
concat_set() [1/4]
virtual void sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_set (sc_dt::int64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1302 of file scx_signal_uint.h.
concat_set() [2/4]
virtual void sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_set (const sc_dt::sc_signed & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1308 of file scx_signal_uint.h.
concat_set() [3/4]
virtual void sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_set (const sc_dt::sc_unsigned & src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1310 of file scx_signal_uint.h.
concat_set() [4/4]
virtual void sc_core::sc_inout< sc_dt::sc_uint< W > >::concat_set (sc_dt::uint64 src, int low_i) inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 1312 of file scx_signal_uint.h.
default_event()
const sc_event& sc_core::sc_inout< sc_dt::sc_uint< W > >::default_event () const inline
Definition at line 1189 of file scx_signal_uint.h.
end_of_elaboration()
virtual void sc_core::sc_inout< sc_dt::sc_uint< W > >::end_of_elaboration () inline virtual
Implements sc_core::sc_port_base.
Definition at line 1243 of file scx_signal_uint.h.
References ArmISA::i, sc_core::sc_trace_params::name, MipsISA::p, sc_gem5::ScSignalBaseT< T, WRITER_POLICY >::read(), sc_core::sc_trace(), and sc_core::sc_trace_params::tf.
event()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::event () const inline
Definition at line 1209 of file scx_signal_uint.h.
initialize()
void sc_core::sc_inout< sc_dt::sc_uint< W > >::initialize (const sc_dt::sc_uint< W > & value_) inline
Definition at line 1264 of file scx_signal_uint.h.
References sc_core::sc_signal_write_if< T >::write().
kind()
virtual const char* sc_core::sc_inout< sc_dt::sc_uint< W > >::kind () const inline virtual
Reimplemented from sc_core::sc_port< sc_signal_inout_if< sc_dt::sc_uint< W > >, 1, SC_ONE_OR_MORE_BOUND >.
Definition at line 1259 of file scx_signal_uint.h.
nand_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::nand_reduce () const inline
Definition at line 1227 of file scx_signal_uint.h.
nor_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::nor_reduce () const inline
Definition at line 1229 of file scx_signal_uint.h.
operator sc_dt::uint64()
sc_core::sc_inout< sc_dt::sc_uint< W > >::operator sc_dt::uint64 () const inline
Definition at line 1204 of file scx_signal_uint.h.
operator()() [1/4]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator() (const inout_if_type & interface_) inline
Definition at line 1097 of file scx_signal_uint.h.
References sc_core::sc_port_base::bind().
operator()() [2/4]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator() (inout_port_type & parent_) inline
Definition at line 1101 of file scx_signal_uint.h.
References sc_core::sc_port_base::bind().
operator()() [3/4]
sc_dt::sc_uint_subref_r sc_core::sc_inout< sc_dt::sc_uint< W > >::operator() (int left, int right) const inline
Definition at line 1175 of file scx_signal_uint.h.
operator()() [4/4]
sc_uint_sigref& sc_core::sc_inout< sc_dt::sc_uint< W > >::operator() (int left, int right) inline
Definition at line 1179 of file scx_signal_uint.h.
operator=() [1/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const this_type & new_val) inline
Definition at line 1318 of file scx_signal_uint.h.
operator=() [2/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const char * new_val) inline
Definition at line 1320 of file scx_signal_uint.h.
operator=() [3/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (sc_dt::uint64 new_val) inline
Definition at line 1322 of file scx_signal_uint.h.
operator=() [4/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (sc_dt::int64 new_val) inline
Definition at line 1324 of file scx_signal_uint.h.
operator=() [5/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (int new_val) inline
Definition at line 1326 of file scx_signal_uint.h.
operator=() [6/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (long new_val) inline
Definition at line 1328 of file scx_signal_uint.h.
operator=() [7/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (short new_val) inline
Definition at line 1330 of file scx_signal_uint.h.
operator=() [8/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (unsigned int new_val) inline
Definition at line 1332 of file scx_signal_uint.h.
operator=() [9/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (unsigned long new_val) inline
Definition at line 1334 of file scx_signal_uint.h.
operator=() [10/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (unsigned short new_val) inline
Definition at line 1336 of file scx_signal_uint.h.
operator=() [11/15]
template<typename T > void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_generic_base< T > & new_val) inline
Definition at line 1339 of file scx_signal_uint.h.
operator=() [12/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_signed & new_val) inline
Definition at line 1341 of file scx_signal_uint.h.
References sc_dt::sc_signed::to_uint64().
operator=() [13/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_unsigned & new_val) inline
Definition at line 1343 of file scx_signal_uint.h.
References sc_dt::sc_unsigned::to_uint64().
operator=() [14/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_bv_base & new_val) inline
Definition at line 1345 of file scx_signal_uint.h.
operator=() [15/15]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::operator= (const sc_dt::sc_lv_base & new_val) inline
Definition at line 1347 of file scx_signal_uint.h.
operator[]() [1/2]
sc_dt::sc_uint_bitref_r sc_core::sc_inout< sc_dt::sc_uint< W > >::operator[] (int i) const inline
Definition at line 1167 of file scx_signal_uint.h.
References ArmISA::i.
operator[]() [2/2]
sc_uint_sigref& sc_core::sc_inout< sc_dt::sc_uint< W > >::operator[] (int i) inline
Definition at line 1171 of file scx_signal_uint.h.
or_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::or_reduce () const inline
Definition at line 1231 of file scx_signal_uint.h.
range() [1/2]
sc_dt::sc_uint_subref_r sc_core::sc_inout< sc_dt::sc_uint< W > >::range (int left, int right) const inline
Definition at line 1177 of file scx_signal_uint.h.
range() [2/2]
sc_uint_sigref& sc_core::sc_inout< sc_dt::sc_uint< W > >::range (int left, int right) inline
Definition at line 1181 of file scx_signal_uint.h.
read()
const sc_dt::sc_uint<W>& sc_core::sc_inout< sc_dt::sc_uint< W > >::read () const inline
Definition at line 1201 of file scx_signal_uint.h.
remove_traces()
void sc_core::sc_inout< sc_dt::sc_uint< W > >::remove_traces () const inline protected
Definition at line 1358 of file scx_signal_uint.h.
References ArmISA::i.
value_changed()
sc_event_finder& sc_core::sc_inout< sc_dt::sc_uint< W > >::value_changed () const inline
Definition at line 1215 of file scx_signal_uint.h.
value_changed_event()
const sc_event& sc_core::sc_inout< sc_dt::sc_uint< W > >::value_changed_event () const inline
Definition at line 1195 of file scx_signal_uint.h.
vbind() [1/2]
virtual int sc_core::sc_inout< sc_dt::sc_uint< W > >::vbind (sc_interface & interface_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 1106 of file scx_signal_uint.h.
References sc_core::sc_port_b< IF >::vbind().
vbind() [2/2]
virtual int sc_core::sc_inout< sc_dt::sc_uint< W > >::vbind (sc_port_base & parent_) inline protected virtual
Implements sc_core::sc_port_base.
Definition at line 1110 of file scx_signal_uint.h.
References sc_core::sc_port_base::bind().
write() [1/3]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::write (const sc_in< sc_dt::sc_uint< W > > & new_val) inline
Definition at line 1350 of file scx_signal_uint.h.
write() [2/3]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::write (const sc_inout< sc_dt::sc_uint< W > > & new_val) inline
Definition at line 1352 of file scx_signal_uint.h.
write() [3/3]
void sc_core::sc_inout< sc_dt::sc_uint< W > >::write (const sc_dt::sc_uint< W > & new_val) inline
Definition at line 1354 of file scx_signal_uint.h.
xnor_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::xnor_reduce () const inline
Definition at line 1233 of file scx_signal_uint.h.
xor_reduce()
bool sc_core::sc_inout< sc_dt::sc_uint< W > >::xor_reduce () const inline
Definition at line 1235 of file scx_signal_uint.h.
Member Data Documentation
m_init_val_p
sc_dt::uint64* sc_core::sc_inout< sc_dt::sc_uint< W > >::m_init_val_p protected
Definition at line 1369 of file scx_signal_uint.h.
m_traces
sc_trace_params_vec* sc_core::sc_inout< sc_dt::sc_uint< W > >::m_traces mutable protected
Definition at line 1370 of file scx_signal_uint.h.
The documentation for this class was generated from the following file:
systemc/tests/include/specialized_signals/scx_signal_uint.h