gem5: sc_gem5::StaticSensitivityFinder Class Reference
sc_gem5::StaticSensitivityFinder Class Reference
#include <sensitivity.hh>
Public Member Functions
const ::sc_core::sc_event & find (::sc_core::sc_interface *i)
Public Member Functions inherited from sc_gem5::StaticSensitivity
Category category () override
Public Member Functions inherited from sc_gem5::Sensitivity
void satisfy ()
virtual bool notifyWork (Event *e)
bool notify (Event *e)
bool ofMethod ()
Public Member Functions inherited from sc_gem5::SensitivityEvents
void clear () override
void addEvent (const ::sc_core::sc_event *event)
Private Member Functions
StaticSensitivityFinder (Process *p, const sc_core::sc_event_finder *f)
Private Attributes
const sc_core::sc_event_finder * finder
Friends
void newStaticSensitivityFinder (Process *p, const sc_core::sc_event_finder *f)
Additional Inherited Members
Public Types inherited from sc_gem5::Sensitivity
enum Category { Static, Dynamic }
Protected Member Functions inherited from sc_gem5::StaticSensitivity
StaticSensitivity (Process *p)
void addToEvent (const ::sc_core::sc_event *e) override
void delFromEvent (const ::sc_core::sc_event *e) override
Protected Member Functions inherited from sc_gem5::Sensitivity
Sensitivity (Process *p)
virtual ~Sensitivity ()
Protected Member Functions inherited from sc_gem5::SensitivityEvents
SensitivityEvents (Process *p)
SensitivityEvents (Process *p, const std::set< const ::sc_core::sc_event *> &s)
Protected Attributes inherited from sc_gem5::Sensitivity
Process * process
Protected Attributes inherited from sc_gem5::SensitivityEvents
std::set< const ::sc_core::sc_event * > events
Detailed Description
Definition at line 230 of file sensitivity.hh.
Constructor & Destructor Documentation
StaticSensitivityFinder()
sc_gem5::StaticSensitivityFinder::StaticSensitivityFinder (Process * p, const sc_core::sc_event_finder * f) inline private
Definition at line 239 of file sensitivity.hh.
References sc_gem5::newDynamicSensitivityEvent(), sc_gem5::newDynamicSensitivityEventAndList(), and sc_gem5::newDynamicSensitivityEventOrList().
Member Function Documentation
find()
const ::sc_core::sc_event & sc_gem5::StaticSensitivityFinder::find (::sc_core::sc_interface * i)
Definition at line 179 of file sensitivity.cc.
Referenced by sc_gem5::Port::finalizeFinder().
Friends And Related Function Documentation
newStaticSensitivityFinder
void newStaticSensitivityFinder (Process * p, const sc_core::sc_event_finder * f) friend
Definition at line 157 of file sensitivity.cc.
Member Data Documentation
finder
const sc_core::sc_event_finder* sc_gem5::StaticSensitivityFinder::finder private
Definition at line 234 of file sensitivity.hh.
The documentation for this class was generated from the following files:
systemc/core/sensitivity.hh
systemc/core/sensitivity.cc