gem5: Bridge::BridgeSlavePort Class Reference
Bridge::BridgeSlavePort Class Reference
The port on the side that receives requests and sends responses.
#include <bridge.hh>
Public Member Functions
BridgeSlavePort (const std::string &_name, Bridge &_bridge, BridgeMasterPort &_masterPort, Cycles _delay, int _resp_limit, std::vector< AddrRange > _ranges)
Constructor for the BridgeSlavePort.
void schedTimingResp (PacketPtr pkt, Tick when)
Queue a response packet to be sent out later and also schedule a send if necessary.
void retryStalledReq ()
Retry any stalled request that we have failed to accept at an earlier point in time.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
bool recvTimingReq (PacketPtr pkt)
When receiving a timing request from the peer port, pass it to the bridge.
void recvRespRetry ()
When receiving a retry request from the peer port, pass it to the bridge.
Tick recvAtomic (PacketPtr pkt)
When receiving a Atomic requestfrom the peer port, pass it to the bridge.
void recvFunctional (PacketPtr pkt)
When receiving a Functional request from the peer port, pass it to the bridge.
AddrRangeList getAddrRanges () const
When receiving a address range request the peer port, pass it to the bridge.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
Private Member Functions
bool respQueueFull () const
Is this side blocked from accepting new response packets.
void trySendTiming ()
Handle send event, scheduled when the packet at the head of the response queue is ready to transmit (for timing accesses only).
Private Attributes
Bridge & bridge
The bridge to which this port belongs.
BridgeMasterPort & masterPort
Master port on the other side of the bridge.
const Cycles delay
Minimum request delay though this bridge.
const AddrRangeList ranges
Address ranges to pass through the bridge.
std::deque< DeferredPacket > transmitList
Response packet queue.
unsigned int outstandingResponses
Counter to track the outstanding responses.
bool retryReq
If we should send a retry when space becomes available.
unsigned int respQueueLimit
Max queue size for reserved responses.
std::unique_ptr< Packet > pendingDelete
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
EventFunctionWrapper sendEvent
Send event for the response queue.
Additional Inherited Members
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
The port on the side that receives requests and sends responses.
The slave port has a set of address ranges that it is responsible for. The slave port also has a buffer for the responses not yet sent.
Definition at line 103 of file bridge.hh.
Constructor & Destructor Documentation
BridgeSlavePort()
Bridge::BridgeSlavePort::BridgeSlavePort (const std::string & _name, Bridge & _bridge, BridgeMasterPort & _masterPort, Cycles _delay, int _resp_limit, std::vector< AddrRange > _ranges)
Constructor for the BridgeSlavePort.
Parameters
_name the port name including the owner
_bridge the structural owner
_masterPort the master port on the other side of the bridge
_delay the delay in cycles from receiving to sending
_resp_limit the size of the response queue
_ranges a number of address ranges to forward
Definition at line 57 of file bridge.cc.
References trySendTiming().
Member Function Documentation
getAddrRanges()
AddrRangeList Bridge::BridgeSlavePort::getAddrRanges () const protected virtual
When receiving a address range request the peer port, pass it to the bridge.
Implements SlavePort.
Definition at line 391 of file bridge.cc.
References Bridge::Bridge().
recvAtomic()
Tick Bridge::BridgeSlavePort::recvAtomic (PacketPtr pkt) protected virtual
When receiving a Atomic requestfrom the peer port, pass it to the bridge.
Implements AtomicResponseProtocol.
Definition at line 341 of file bridge.cc.
References Packet::cacheResponding(), Bridge::masterPort, panic_if, and MasterPort::sendAtomic().
recvFunctional()
void Bridge::BridgeSlavePort::recvFunctional (PacketPtr pkt) protected virtual
When receiving a Functional request from the peer port, pass it to the bridge.
Implements FunctionalResponseProtocol.
Definition at line 350 of file bridge.cc.
References ArmISA::i, Packet::makeResponse(), Bridge::masterPort, SimObject::name(), Packet::popLabel(), Packet::pushLabel(), MasterPort::sendFunctional(), Bridge::BridgeMasterPort::trySatisfyFunctional(), and Packet::trySatisfyFunctional().
recvRespRetry()
void Bridge::BridgeSlavePort::recvRespRetry () protected virtual
When receiving a retry request from the peer port, pass it to the bridge.
Implements TimingResponseProtocol.
Definition at line 335 of file bridge.cc.
recvTimingReq()
bool Bridge::BridgeSlavePort::recvTimingReq (PacketPtr pkt) protected virtual
When receiving a timing request from the peer port, pass it to the bridge.
Implements TimingResponseProtocol.
Definition at line 146 of file bridge.cc.
References Packet::cacheResponding(), Packet::cmdString(), DPRINTF, Packet::getAddr(), Packet::headerDelay, Bridge::masterPort, Packet::needsResponse(), panic_if, Packet::payloadDelay, Bridge::BridgeMasterPort::reqQueueFull(), and Bridge::BridgeMasterPort::schedTimingReq().
respQueueFull()
bool Bridge::BridgeSlavePort::respQueueFull () const private
Is this side blocked from accepting new response packets.
Returns
true if the reserved space has reached the set limit
Definition at line 112 of file bridge.cc.
retryStalledReq()
void Bridge::BridgeSlavePort::retryStalledReq ()
Retry any stalled request that we have failed to accept at an earlier point in time.
This call will do nothing if no request is waiting.
Definition at line 206 of file bridge.cc.
References DPRINTF.
Referenced by Bridge::BridgeMasterPort::trySendTiming().
schedTimingResp()
void Bridge::BridgeSlavePort::schedTimingResp (PacketPtr pkt, Tick when)
Queue a response packet to be sent out later and also schedule a send if necessary.
Parameters
pkt a response to send out after a delay
when tick when response packet should be sent
Definition at line 233 of file bridge.cc.
References ArmISA::sendEvent().
Referenced by Bridge::BridgeMasterPort::recvTimingResp().
trySendTiming()
void Bridge::BridgeSlavePort::trySendTiming () private
Handle send event, scheduled when the packet at the head of the response queue is ready to transmit (for timing accesses only).
Definition at line 285 of file bridge.cc.
References curTick(), DPRINTF, Packet::getAddr(), Bridge::masterPort, Bridge::BridgeMasterPort::reqQueueFull(), ArmISA::sendEvent(), and Bridge::DeferredPacket::tick.
Referenced by BridgeSlavePort().
Member Data Documentation
bridge
Bridge& Bridge::BridgeSlavePort::bridge private
The bridge to which this port belongs.
Definition at line 109 of file bridge.hh.
delay
const Cycles Bridge::BridgeSlavePort::delay private
Minimum request delay though this bridge.
Definition at line 117 of file bridge.hh.
masterPort
BridgeMasterPort& Bridge::BridgeSlavePort::masterPort private
Master port on the other side of the bridge.
Definition at line 114 of file bridge.hh.
outstandingResponses
unsigned int Bridge::BridgeSlavePort::outstandingResponses private
Counter to track the outstanding responses.
Definition at line 131 of file bridge.hh.
pendingDelete
std::unique_ptr<Packet> Bridge::BridgeSlavePort::pendingDelete private
Upstream caches need this packet until true is returned, so hold it for deletion until a subsequent call.
Definition at line 143 of file bridge.hh.
ranges
const AddrRangeList Bridge::BridgeSlavePort::ranges private
Address ranges to pass through the bridge.
Definition at line 120 of file bridge.hh.
respQueueLimit
unsigned int Bridge::BridgeSlavePort::respQueueLimit private
Max queue size for reserved responses.
Definition at line 137 of file bridge.hh.
retryReq
bool Bridge::BridgeSlavePort::retryReq private
If we should send a retry when space becomes available.
Definition at line 134 of file bridge.hh.
sendEvent
EventFunctionWrapper Bridge::BridgeSlavePort::sendEvent private
Send event for the response queue.
Definition at line 160 of file bridge.hh.
transmitList
std::deque<DeferredPacket> Bridge::BridgeSlavePort::transmitList private
Response packet queue.
Response packets are held in this queue for a specified delay to model the processing delay of the bridge. We use a deque as we need to iterate over the items for functional accesses.
Definition at line 128 of file bridge.hh.
The documentation for this class was generated from the following files:
mem/bridge.hh
mem/bridge.cc