gem5: QueuedSlavePort Class Reference
QueuedSlavePort Class Reference
A queued port is a port that has an infinite queue for outgoing packets and thus decouples the module that wants to send request/responses from the flow control (retry mechanism) of the port.
#include <qport.hh>
Public Member Functions
QueuedSlavePort (const std::string &name, SimObject *owner, RespPacketQueue &resp_queue, PortID id=InvalidPortID)
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
virtual ~QueuedSlavePort ()
void schedTimingResp (PacketPtr pkt, Tick when)
Schedule the sending of a timing response.
bool trySatisfyFunctional (PacketPtr pkt)
Check the list of buffered packets against the supplied functional request.
Public Member Functions inherited from SlavePort
SlavePort (const std::string &name, SimObject *_owner, PortID id=InvalidPortID)
Slave port.
virtual ~SlavePort ()
bool isSnooping () const
Find out if the peer master port is snooping or not.
void sendRangeChange () const
Called by the owner to send a range change.
virtual AddrRangeList getAddrRanges () const =0
Get a list of the non-overlapping address ranges the owner is responsible for.
void unbind () override
We let the master port do the work, so these don't do anything.
void bind (Port &peer) override
Attach to a peer port.
Tick sendAtomicSnoop (PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
void sendFunctionalSnoop (PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
bool sendTimingResp (PacketPtr pkt)
Attempt to send a timing response to the master port by calling its corresponding receive function.
void sendTimingSnoopReq (PacketPtr pkt)
Attempt to send a timing snoop request packet to the master port by calling its corresponding receive function.
void sendRetryReq ()
Send a retry to the master port that previously attempted a sendTimingReq to this slave port and failed.
void sendRetrySnoopResp ()
Send a retry to the master port that previously attempted a sendTimingSnoopResp to this slave port and failed.
Public Member Functions inherited from Port
Port & getPeer ()
Return a reference to this port's peer.
const std::string name () const
Return port name (for DPRINTF).
PortID getId () const
Get the port id.
bool isConnected () const
Is this port currently connected to a peer?
void takeOverFrom (Port *old)
A utility function to make it easier to swap out ports.
Protected Member Functions
void recvRespRetry ()
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Protected Member Functions inherited from SlavePort
void slaveUnbind ()
Called by the master port to unbind.
void slaveBind (MasterPort &master_port)
Called by the master port to bind.
Tick recvAtomicBackdoor (PacketPtr pkt, MemBackdoorPtr &backdoor) override
Default implementations.
bool tryTiming (PacketPtr pkt) override
Availability request from the peer.
bool recvTimingSnoopResp (PacketPtr pkt) override
Receive a timing snoop response from the peer.
Protected Member Functions inherited from Port
Port (const std::string &_name, PortID _id)
Abstract base class for ports.
virtual ~Port ()
Virtual destructor due to inheritance.
Protected Member Functions inherited from AtomicResponseProtocol
Tick sendSnoop (AtomicRequestProtocol *peer, PacketPtr pkt)
Send an atomic snoop request packet, where the data is moved and the state is updated in zero time, without interleaving with other memory accesses.
virtual Tick recvAtomic (PacketPtr pkt)=0
Receive an atomic request packet from the peer.
Protected Member Functions inherited from TimingResponseProtocol
bool sendResp (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing response to the peer by calling its corresponding receive function.
void sendSnoopReq (TimingRequestProtocol *peer, PacketPtr pkt)
Attempt to send a timing snoop request packet to the peer by calling its corresponding receive function.
void sendRetryReq (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingReq to this protocol and failed.
void sendRetrySnoopResp (TimingRequestProtocol *peer)
Send a retry to the peer that previously attempted a sendTimingSnoopResp to this peer and failed.
virtual bool recvTimingReq (PacketPtr pkt)=0
Receive a timing request from the peer.
Protected Member Functions inherited from FunctionalResponseProtocol
void sendSnoop (FunctionalRequestProtocol *peer, PacketPtr pkt) const
Send a functional snoop request packet, where the data is instantly updated everywhere in the memory system, without affecting the current state of any block or moving the block.
virtual void recvFunctional (PacketPtr pkt)=0
Receive a functional request packet from the peer.
Protected Attributes
RespPacketQueue & respQueue
Packet queue used to store outgoing responses.
Protected Attributes inherited from SlavePort
SimObject & owner
Protected Attributes inherited from Port
const PortID id
A numeric identifier to distinguish ports in a vector, and set to InvalidPortID in case this port is not part of a vector.
Port * _peer
A pointer to this port's peer.
bool _connected
Whether this port is currently connected to a peer port.
Detailed Description
A queued port is a port that has an infinite queue for outgoing packets and thus decouples the module that wants to send request/responses from the flow control (retry mechanism) of the port.
A queued port can be used by both a master and a slave. The queue is a parameter to allow tailoring of the queue implementation (used in the cache).
Definition at line 60 of file qport.hh.
Constructor & Destructor Documentation
QueuedSlavePort()
QueuedSlavePort::QueuedSlavePort (const std::string & name, SimObject * owner, RespPacketQueue & resp_queue, PortID id = InvalidPortID) inline
Create a QueuedPort with a given name, owner, and a supplied implementation of a packet queue.
The external definition of the queue enables e.g. the cache to implement a specific queue behaviuor in a subclass, and provide the latter to the QueuePort constructor.
Definition at line 79 of file qport.hh.
~QueuedSlavePort()
virtual QueuedSlavePort::~QueuedSlavePort () inline virtual
Definition at line 84 of file qport.hh.
Member Function Documentation
recvRespRetry()
void QueuedSlavePort::recvRespRetry () inline protected virtual
Called by the peer if sendTimingResp was called on this protocol (causing recvTimingResp to be called on the peer) and was unsuccessful.
Implements TimingResponseProtocol.
Definition at line 68 of file qport.hh.
References PacketQueue::retry().
schedTimingResp()
void QueuedSlavePort::schedTimingResp (PacketPtr pkt, Tick when) inline
Schedule the sending of a timing response.
Parameters
pkt Packet to send
when Absolute time (in ticks) to send packet
Definition at line 92 of file qport.hh.
References PacketQueue::schedSendTiming().
Referenced by DRAMCtrl::accessAndRespond(), BaseCache::handleTimingReqHit(), Cache::handleTimingReqMiss(), BaseCache::handleUncacheableWriteResp(), RubyPort::MemSlavePort::hitCallback(), QoS::MemSinkCtrl::processNextReqEvent(), SimpleTimingPort::recvTimingReq(), RubyPort::MemSlavePort::recvTimingReq(), MemDelay::MasterPort::recvTimingResp(), RubyPort::PioMasterPort::recvTimingResp(), SMMUv3SlaveInterface::schedAtsTimingResp(), SMMUv3SlaveInterface::schedTimingResp(), NoncoherentCache::serviceMSHRTargets(), and Cache::serviceMSHRTargets().
trySatisfyFunctional()
bool QueuedSlavePort::trySatisfyFunctional (PacketPtr pkt) inline
Check the list of buffered packets against the supplied functional request.
Definition at line 97 of file qport.hh.
References PacketQueue::trySatisfyFunctional().
Referenced by BaseCache::functionalAccess(), and MemDelay::trySatisfyFunctional().
Member Data Documentation
respQueue
RespPacketQueue& QueuedSlavePort::respQueue protected
Packet queue used to store outgoing responses.
Definition at line 66 of file qport.hh.
Referenced by SimpleTimingPort::recvFunctional().
The documentation for this class was generated from the following file:
mem/qport.hh