gem5: Trace::TarmacParserRecord Class Reference
Trace::TarmacParserRecord Class Reference
#include <tarmac_parser.hh>
Classes
struct ParserInstEntry
struct ParserMemEntry
struct ParserRegEntry
struct TarmacParserRecordEvent
Event triggered to check the value of the destination registers.
Public Member Functions
TarmacParserRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, ArmISA::PCState _pc, TarmacParser &_parent, const StaticInstPtr _macroStaticInst=NULL)
void dump () override
bool readMemNoEffect (Addr addr, uint8_t *data, unsigned size, unsigned flags)
Performs a memory access to read the value written by a previous write.
Public Member Functions inherited from Trace::TarmacBaseRecord
TarmacBaseRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, ArmISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
Public Member Functions inherited from Trace::InstRecord
InstRecord (Tick _when, ThreadContext *_thread, const StaticInstPtr _staticInst, TheISA::PCState _pc, const StaticInstPtr _macroStaticInst=NULL)
virtual ~InstRecord ()
void setWhen (Tick new_when)
void setMem (Addr a, Addr s, unsigned f)
template<typename T , size_t N>
void setData (std::array< T, N > d)
void setData (uint64_t d)
void setData (uint32_t d)
void setData (uint16_t d)
void setData (uint8_t d)
void setData (int64_t d)
void setData (int32_t d)
void setData (int16_t d)
void setData (int8_t d)
void setData (double d)
void setData (::VecRegContainer< TheISA::VecRegSizeBytes > &d)
void setData (::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > &d)
void setFetchSeq (InstSeqNum seq)
void setCPSeq (InstSeqNum seq)
void setPredicate (bool val)
Tick getWhen () const
ThreadContext * getThread () const
StaticInstPtr getStaticInst () const
TheISA::PCState getPCState () const
StaticInstPtr getMacroStaticInst () const
Addr getAddr () const
Addr getSize () const
unsigned getFlags () const
bool getMemValid () const
uint64_t getIntData () const
double getFloatData () const
int getDataStatus () const
InstSeqNum getFetchSeq () const
bool getFetchSeqValid () const
InstSeqNum getCpSeq () const
bool getCpSeqValid () const
Static Public Member Functions
static void printMismatchHeader (const StaticInstPtr inst, ArmISA::PCState pc)
Print a mismatch header containing the instruction fields as reported by gem5.
Static Public Member Functions inherited from Trace::TarmacBaseRecord
static ISetState pcToISetState (ArmISA::PCState pc)
Returns the Instruction Set State according to the current PCState.
Static Public Attributes
static const int MaxLineLength = 256
Protected Attributes
TarmacParser & parent
Protected Attributes inherited from Trace::InstRecord
Tick when
ThreadContext * thread
StaticInstPtr staticInst
TheISA::PCState pc
StaticInstPtr macroStaticInst
Addr addr
The address that was accessed.
Addr size
The size of the memory request.
unsigned flags
The flags that were assigned to the request.
union {
uint64_t as_int
double as_double
::VecRegContainer< TheISA::VecRegSizeBytes > * as_vec
::VecPredRegContainer< TheISA::VecPredRegSizeBits, TheISA::VecPredRegHasPackedRepr > * as_pred
} data
InstSeqNum fetch_seq
InstSeqNum cp_seq
enum Trace::InstRecord::DataStatus data_status
bool mem_valid
Are the memory fields in the record valid?
bool fetch_seq_valid
Are the fetch sequence number fields valid?
bool cp_seq_valid
Are the commit sequence number fields valid?
bool predicate
is the predicate for execution this inst true or false (not execed)?
Private Types
using MiscRegMap = std::unordered_map< std::string, RegIndex >
Map from misc.
Private Member Functions
bool advanceTrace ()
Advances the TARMAC trace up to the next instruction, register, or memory access record.
const char * iSetStateToStr (ISetState isetstate) const
Returns the string representation of an instruction set state.
Private Attributes
bool parsingStarted
True if a TARMAC instruction record has already been parsed for this instruction.
bool mismatch
True if a mismatch has been detected for this instruction.
bool mismatchOnPcOrOpcode
True if a mismatch has been detected for this instruction on PC or opcode.
RequestPtr memReq
Request for memory write checks.
Static Private Attributes
static ParserInstEntry instRecord
Buffer for instruction trace records.
static ParserRegEntry regRecord
Buffer for register trace records.
static ParserMemEntry memRecord
Buffer for memory access trace records (stores only).
static TarmacRecordType currRecordType
Type of last parsed record.
static char buf [MaxLineLength]
Buffer used for trace file parsing.
static std::list< ParserRegEntry > destRegRecords
List of records of destination registers.
static MiscRegMap miscRegMap
static int8_t maxVectorLength = 0
Max.
Additional Inherited Members
Public Types inherited from Trace::TarmacBaseRecord
enum TarmacRecordType { TARMAC_INST, TARMAC_REG, TARMAC_MEM, TARMAC_UNSUPPORTED }
TARMAC trace record type.
enum ISetState { ISET_ARM, ISET_THUMB, ISET_A64, ISET_UNSUPPORTED }
ARM instruction set state.
enum RegType {
REG_R, REG_X, REG_S, REG_D,
REG_P, REG_Q, REG_Z, REG_MISC
}
ARM register type.
Protected Types inherited from Trace::InstRecord
enum DataStatus {
DataInvalid = 0, DataInt8 = 1, DataInt16 = 2, DataInt32 = 4,
DataInt64 = 8, DataDouble = 3, DataVec = 5, DataVecPred = 6
}
What size of data was written?
Detailed Description
Definition at line 66 of file tarmac_parser.hh.
Member Typedef Documentation
MiscRegMap
using Trace::TarmacParserRecord::MiscRegMap = std::unordered_map<std::string, RegIndex> private
Map from misc.
register names to indexes.
Definition at line 181 of file tarmac_parser.hh.
Constructor & Destructor Documentation
TarmacParserRecord()
Trace::TarmacParserRecord::TarmacParserRecord (Tick _when, ThreadContext * _thread, const StaticInstPtr _staticInst, ArmISA::PCState _pc, TarmacParser & _parent, const StaticInstPtr _macroStaticInst = NULL)
Definition at line 856 of file tarmac_parser.cc.
References maxVectorLength, and memReq.
Referenced by Trace::TarmacParser::getInstRecord().
Member Function Documentation
advanceTrace()
bool Trace::TarmacParserRecord::advanceTrace () private
Advances the TARMAC trace up to the next instruction, register, or memory access record.
The collected data is stored in one of {inst/reg/mem}_record.
Returns
False if EOF is reached.
Definition at line 981 of file tarmac_parser.cc.
References buf, ArmISA::c, Trace::TarmacParser::cpuId, currRecordType, Trace::InstRecord::data, ArmISA::i, instRecord, ArmISA::INTREG_ABT(), ArmISA::INTREG_FIQ(), ArmISA::INTREG_HYP(), ArmISA::INTREG_IRQ(), ArmISA::INTREG_MON(), ArmISA::INTREG_SP0, ArmISA::INTREG_SVC(), ArmISA::INTREG_UND(), ArmISA::INTREG_USR(), Trace::TarmacBaseRecord::ISET_A64, Trace::TarmacBaseRecord::ISET_ARM, Trace::TarmacBaseRecord::ISET_THUMB, Trace::TarmacBaseRecord::ISET_UNSUPPORTED, ArmISA::lo, MaxLineLength, maxVectorLength, memRecord, Trace::TarmacParser::memWrCheck, miscRegMap, parent, parsingStarted, Trace::TarmacBaseRecord::REG_D, Trace::TarmacBaseRecord::REG_MISC, Trace::TarmacBaseRecord::REG_P, Trace::TarmacBaseRecord::REG_Q, Trace::TarmacBaseRecord::REG_R, Trace::TarmacBaseRecord::REG_S, Trace::TarmacBaseRecord::REG_X, Trace::TarmacBaseRecord::REG_Z, regRecord, Trace::TarmacParserRecord::ParserRegEntry::repr, Trace::TarmacParserRecord::ParserInstEntry::seq_num, Trace::TarmacBaseRecord::TARMAC_INST, Trace::TarmacBaseRecord::TARMAC_MEM, Trace::TarmacBaseRecord::TARMAC_REG, Trace::TarmacBaseRecord::TARMAC_UNSUPPORTED, Trace::TarmacParser::trace, ArmISA::v, and warn.
Referenced by dump().
dump()
void Trace::TarmacParserRecord::dump () override virtual
Implements Trace::TarmacBaseRecord.
Definition at line 873 of file tarmac_parser.cc.
References advanceTrace(), ArmISA::TLB::AllowUnaligned, currRecordType, curTick(), destRegRecords, MipsISA::event, Trace::TarmacParser::exitOnDiff, Trace::TarmacParser::exitOnInsnDiff, exitSimLoop(), RefCountingPtr< T >::get(), instRecord, Trace::TarmacBaseRecord::ISET_UNSUPPORTED, iSetStateToStr(), StaticInst::isLastMicroop(), StaticInst::isMicroop(), Trace::TarmacParser::macroopInProgress, mainEventQueue, memRecord, mismatch, mismatchOnPcOrOpcode, ArmISA::TLB::MustBeOne, Trace::output(), panic, parent, parsingStarted, Trace::InstRecord::pc, Trace::TarmacBaseRecord::pcToISetState(), printMismatchHeader(), readMemNoEffect(), regRecord, Trace::InstRecord::staticInst, Trace::TarmacBaseRecord::TARMAC_INST, Trace::TarmacBaseRecord::TARMAC_MEM, Trace::TarmacBaseRecord::TARMAC_REG, Trace::TarmacBaseRecord::TARMAC_UNSUPPORTED, and Trace::InstRecord::thread.
iSetStateToStr()
const char * Trace::TarmacParserRecord::iSetStateToStr (ISetState isetstate) const private
Returns the string representation of an instruction set state.
Definition at line 1253 of file tarmac_parser.cc.
References Trace::TarmacBaseRecord::ISET_A64, Trace::TarmacBaseRecord::ISET_ARM, and Trace::TarmacBaseRecord::ISET_THUMB.
Referenced by dump().
printMismatchHeader()
void Trace::TarmacParserRecord::printMismatchHeader (const StaticInstPtr inst, ArmISA::PCState pc) static
Print a mismatch header containing the instruction fields as reported by gem5.
Definition at line 843 of file tarmac_parser.cc.
References curTick(), StaticInst::disassemble(), StaticInst::machInst, and Trace::output().
Referenced by dump().
readMemNoEffect()
bool Trace::TarmacParserRecord::readMemNoEffect (Addr addr, uint8_t * data, unsigned size, unsigned flags)
Performs a memory access to read the value written by a previous write.
Returns
False if the result of the memory access should be ignored (faulty memory access, etc.).
Definition at line 1185 of file tarmac_parser.cc.
References AddrRange::contains(), Request::funcMasterId, ThreadContext::getDTBPtr(), ThreadContext::getVirtProxy(), Trace::TarmacParser::ignoredAddrRange, memReq, Request::NO_ACCESS, NoFault, parent, ThreadContext::pcState(), BaseTLB::Read, PortProxy::readBlob(), Trace::InstRecord::thread, and ArmISA::TLB::translateAtomic().
Referenced by dump().
Member Data Documentation
buf
char Trace::TarmacParserRecord::buf static private
Buffer used for trace file parsing.
Definition at line 175 of file tarmac_parser.hh.
Referenced by advanceTrace(), and Trace::TarmacParser::advanceTraceToStartPc().
currRecordType
TarmacBaseRecord::TarmacRecordType Trace::TarmacParserRecord::currRecordType static private
Type of last parsed record.
Definition at line 172 of file tarmac_parser.hh.
Referenced by advanceTrace(), and dump().
destRegRecords
list< TarmacParserRecord::ParserRegEntry > Trace::TarmacParserRecord::destRegRecords static private
List of records of destination registers.
Definition at line 178 of file tarmac_parser.hh.
Referenced by dump().
instRecord
TarmacParserRecord::ParserInstEntry Trace::TarmacParserRecord::instRecord static private
Buffer for instruction trace records.
Definition at line 163 of file tarmac_parser.hh.
Referenced by advanceTrace(), and dump().
MaxLineLength
const int Trace::TarmacParserRecord::MaxLineLength = 256 static
Definition at line 126 of file tarmac_parser.hh.
Referenced by advanceTrace(), and Trace::TarmacParser::advanceTraceToStartPc().
maxVectorLength
int8_t Trace::TarmacParserRecord::maxVectorLength = 0 static private
Max.
vector length (SVE).
Definition at line 203 of file tarmac_parser.hh.
Referenced by advanceTrace(), and TarmacParserRecord().
memRecord
TarmacParserRecord::ParserMemEntry Trace::TarmacParserRecord::memRecord static private
Buffer for memory access trace records (stores only).
Definition at line 169 of file tarmac_parser.hh.
Referenced by advanceTrace(), and dump().
memReq
RequestPtr Trace::TarmacParserRecord::memReq private
Request for memory write checks.
Definition at line 200 of file tarmac_parser.hh.
Referenced by readMemNoEffect(), and TarmacParserRecord().
miscRegMap
TarmacParserRecord::MiscRegMap Trace::TarmacParserRecord::miscRegMap static private
Definition at line 182 of file tarmac_parser.hh.
Referenced by advanceTrace().
mismatch
bool Trace::TarmacParserRecord::mismatch private
True if a mismatch has been detected for this instruction.
Definition at line 191 of file tarmac_parser.hh.
Referenced by dump().
mismatchOnPcOrOpcode
bool Trace::TarmacParserRecord::mismatchOnPcOrOpcode private
True if a mismatch has been detected for this instruction on PC or opcode.
Definition at line 197 of file tarmac_parser.hh.
Referenced by dump().
parent
TarmacParser& Trace::TarmacParserRecord::parent protected
Definition at line 206 of file tarmac_parser.hh.
Referenced by advanceTrace(), dump(), and readMemNoEffect().
parsingStarted
bool Trace::TarmacParserRecord::parsingStarted private
True if a TARMAC instruction record has already been parsed for this instruction.
Definition at line 188 of file tarmac_parser.hh.
Referenced by advanceTrace(), and dump().
regRecord
TarmacParserRecord::ParserRegEntry Trace::TarmacParserRecord::regRecord static private
Buffer for register trace records.
Definition at line 166 of file tarmac_parser.hh.
Referenced by advanceTrace(), and dump().
The documentation for this class was generated from the following files:
arch/arm/tracers/tarmac_parser.hh
arch/arm/tracers/tarmac_parser.cc