gem5: sc_core::sc_prim_channel Class Reference
sc_core::sc_prim_channel Class Reference
#include <sc_prim.hh>
Public Member Functions
virtual const char * kind () const
Public Member Functions inherited from sc_core::sc_object
const char * name () const
const char * basename () const
virtual void print (std::ostream &=std::cout) const
virtual void dump (std::ostream &=std::cout) const
virtual const std::vector< sc_object * > & get_child_objects () const
virtual const std::vector< sc_event * > & get_child_events () const
sc_object * get_parent_object () const
bool add_attribute (sc_attr_base &)
sc_attr_base * get_attribute (const std::string &)
sc_attr_base * remove_attribute (const std::string &)
void remove_all_attributes ()
int num_attributes () const
sc_attr_cltn & attr_cltn ()
const sc_attr_cltn & attr_cltn () const
sc_simcontext * simcontext () const
Protected Member Functions
sc_prim_channel ()
sc_prim_channel (const char *)
virtual ~sc_prim_channel ()
void request_update ()
void async_request_update ()
virtual void update ()
void next_trigger ()
void next_trigger (const sc_event &)
void next_trigger (const sc_event_or_list &)
void next_trigger (const sc_event_and_list &)
void next_trigger (const sc_time &)
void next_trigger (double, sc_time_unit)
void next_trigger (const sc_time &, const sc_event &)
void next_trigger (double, sc_time_unit, const sc_event &)
void next_trigger (const sc_time &, const sc_event_or_list &)
void next_trigger (double, sc_time_unit, const sc_event_or_list &)
void next_trigger (const sc_time &, const sc_event_and_list &)
void next_trigger (double, sc_time_unit, const sc_event_and_list &)
bool timed_out ()
void wait ()
void wait (int)
void wait (const sc_event &)
void wait (const sc_event_or_list &)
void wait (const sc_event_and_list &)
void wait (const sc_time &)
void wait (double, sc_time_unit)
void wait (const sc_time &, const sc_event &)
void wait (double, sc_time_unit, const sc_event &)
void wait (const sc_time &, const sc_event_or_list &)
void wait (double, sc_time_unit, const sc_event_or_list &)
void wait (const sc_time &, const sc_event_and_list &)
void wait (double, sc_time_unit, const sc_event_and_list &)
virtual void before_end_of_elaboration ()
virtual void end_of_elaboration ()
virtual void start_of_simulation ()
virtual void end_of_simulation ()
Protected Member Functions inherited from sc_core::sc_object
sc_object ()
sc_object (const char *)
sc_object (const sc_object &)
sc_object & operator= (const sc_object &)
virtual ~sc_object ()
Private Member Functions
sc_prim_channel (const sc_prim_channel &)
sc_prim_channel & operator= (const sc_prim_channel &)
Private Attributes
sc_gem5::Channel * _gem5_channel
Friends
class sc_gem5::Kernel
class sc_gem5::Channel
Detailed Description
Definition at line 52 of file sc_prim.hh.
Constructor & Destructor Documentation
sc_prim_channel() [1/3]
sc_core::sc_prim_channel::sc_prim_channel () protected
Definition at line 46 of file sc_prim.cc.
References _gem5_channel, sc_core::SC_ID_INSERT_PRIM_CHANNEL_, sc_core::sc_is_running(), SC_REPORT_ERROR, and sc_gem5::scheduler.
sc_prim_channel() [2/3]
sc_core::sc_prim_channel::sc_prim_channel (const char * _name) explicit protected
Definition at line 57 of file sc_prim.cc.
References _gem5_channel, sc_core::SC_ID_INSERT_PRIM_CHANNEL_, sc_core::sc_is_running(), SC_REPORT_ERROR, and sc_gem5::scheduler.
~sc_prim_channel()
sc_core::sc_prim_channel::~sc_prim_channel () protected virtual
Definition at line 69 of file sc_prim.cc.
References _gem5_channel.
sc_prim_channel() [3/3]
sc_core::sc_prim_channel::sc_prim_channel (const sc_prim_channel &) private
Member Function Documentation
async_request_update()
void sc_core::sc_prim_channel::async_request_update () protected
Definition at line 78 of file sc_prim.cc.
References _gem5_channel, and sc_gem5::Channel::asyncRequestUpdate().
before_end_of_elaboration()
virtual void sc_core::sc_prim_channel::before_end_of_elaboration () inline protected virtual
Reimplemented in sc_core::sc_clock.
Definition at line 98 of file sc_prim.hh.
end_of_elaboration()
virtual void sc_core::sc_prim_channel::end_of_elaboration () inline protected virtual
Definition at line 99 of file sc_prim.hh.
end_of_simulation()
virtual void sc_core::sc_prim_channel::end_of_simulation () inline protected virtual
Definition at line 101 of file sc_prim.hh.
References Stats::Group::operator=().
kind()
virtual const char* sc_core::sc_prim_channel::kind () const inline virtual
Reimplemented from sc_core::sc_object.
Reimplemented in sc_core::sc_signal< sc_dt::sc_bigint< W > >, sc_core::sc_signal< sc_dt::sc_biguint< W > >, sc_core::sc_signal< sc_dt::sc_uint< W > >, sc_core::sc_signal< sc_dt::sc_int< W > >, sc_core::sc_fifo< T >, tlm::tlm_fifo< T >, sc_core::sc_signal_rv< W >, sc_core::sc_clock, sc_core::sc_buffer< T, WRITER_POLICY >, sc_core::sc_signal_resolved, and sc_gem5::ScSignalBase.
Definition at line 55 of file sc_prim.hh.
next_trigger() [1/12]
void sc_core::sc_prim_channel::next_trigger () protected
Definition at line 84 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [2/12]
void sc_core::sc_prim_channel::next_trigger (const sc_event & e) protected
Definition at line 90 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [3/12]
void sc_core::sc_prim_channel::next_trigger (const sc_event_or_list & eol) protected
Definition at line 96 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [4/12]
void sc_core::sc_prim_channel::next_trigger (const sc_event_and_list & eal) protected
Definition at line 102 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [5/12]
void sc_core::sc_prim_channel::next_trigger (const sc_time & t) protected
Definition at line 108 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [6/12]
void sc_core::sc_prim_channel::next_trigger (double d, sc_time_unit u) protected
Definition at line 114 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [7/12]
void sc_core::sc_prim_channel::next_trigger (const sc_time & t, const sc_event & e) protected
Definition at line 120 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [8/12]
void sc_core::sc_prim_channel::next_trigger (double d, sc_time_unit u, const sc_event & e) protected
Definition at line 126 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [9/12]
void sc_core::sc_prim_channel::next_trigger (const sc_time & t, const sc_event_or_list & eol) protected
Definition at line 132 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [10/12]
void sc_core::sc_prim_channel::next_trigger (double d, sc_time_unit u, const sc_event_or_list & eol) protected
Definition at line 138 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [11/12]
void sc_core::sc_prim_channel::next_trigger (const sc_time & t, const sc_event_and_list & eal) protected
Definition at line 145 of file sc_prim.cc.
References sc_core::next_trigger().
next_trigger() [12/12]
void sc_core::sc_prim_channel::next_trigger (double d, sc_time_unit u, const sc_event_and_list & eal) protected
Definition at line 151 of file sc_prim.cc.
References sc_core::next_trigger().
operator=()
sc_prim_channel& sc_core::sc_prim_channel::operator= (const sc_prim_channel &) private
request_update()
void sc_core::sc_prim_channel::request_update () protected
Definition at line 72 of file sc_prim.cc.
References _gem5_channel, and sc_gem5::Channel::requestUpdate().
Referenced by sc_core::sc_fifo< T >::read(), sc_core::sc_buffer< T, WRITER_POLICY >::write(), sc_core::sc_signal_resolved::write(), sc_core::sc_fifo< T >::write(), sc_core::sc_signal< sc_dt::sc_int< W > >::write_part(), sc_core::sc_signal< sc_dt::sc_uint< W > >::write_part(), sc_core::sc_signal< sc_dt::sc_biguint< W > >::write_part(), and sc_core::sc_signal< sc_dt::sc_bigint< W > >::write_part().
start_of_simulation()
virtual void sc_core::sc_prim_channel::start_of_simulation () inline protected virtual
Definition at line 100 of file sc_prim.hh.
timed_out()
bool sc_core::sc_prim_channel::timed_out () protected
Definition at line 158 of file sc_prim.cc.
References sc_core::timed_out().
update()
virtual void sc_core::sc_prim_channel::update () inline protected virtual
Reimplemented in sc_core::sc_signal< sc_dt::sc_logic, WRITER_POLICY >, sc_core::sc_signal< sc_dt::sc_bigint< W > >, sc_core::sc_signal< bool, WRITER_POLICY >, sc_core::sc_signal< sc_dt::sc_biguint< W > >, sc_core::sc_signal< sc_dt::sc_uint< W > >, sc_core::sc_signal< sc_dt::sc_int< W > >, sc_core::sc_signal< T, WRITER_POLICY >, sc_core::sc_signal< sc_dt::sc_lv< W >, SC_MANY_WRITERS >, sc_core::sc_signal< bool >, sc_core::sc_signal< sc_dt::sc_logic, SC_MANY_WRITERS >, sc_core::sc_fifo< T >, tlm::tlm_fifo< T >, sc_core::sc_signal_rv< W >, sc_core::sc_buffer< T, WRITER_POLICY >, and sc_core::sc_signal_resolved.
Definition at line 64 of file sc_prim.hh.
References sc_core::next_trigger(), sc_core::timed_out(), and sc_core::wait().
Referenced by sc_gem5::Channel::update().
wait() [1/13]
void sc_core::sc_prim_channel::wait () protected
Definition at line 164 of file sc_prim.cc.
References sc_core::wait().
wait() [2/13]
void sc_core::sc_prim_channel::wait (int i) protected
Definition at line 170 of file sc_prim.cc.
References sc_core::wait().
wait() [3/13]
void sc_core::sc_prim_channel::wait (const sc_event & e) protected
Definition at line 176 of file sc_prim.cc.
References sc_core::wait().
wait() [4/13]
void sc_core::sc_prim_channel::wait (const sc_event_or_list & eol) protected
Definition at line 182 of file sc_prim.cc.
References sc_core::wait().
wait() [5/13]
void sc_core::sc_prim_channel::wait (const sc_event_and_list & eal) protected
Definition at line 188 of file sc_prim.cc.
References sc_core::wait().
wait() [6/13]
void sc_core::sc_prim_channel::wait (const sc_time & t) protected
Definition at line 194 of file sc_prim.cc.
References sc_core::wait().
wait() [7/13]
void sc_core::sc_prim_channel::wait (double d, sc_time_unit u) protected
Definition at line 200 of file sc_prim.cc.
References sc_core::wait().
wait() [8/13]
void sc_core::sc_prim_channel::wait (const sc_time & t, const sc_event & e) protected
Definition at line 206 of file sc_prim.cc.
References sc_core::wait().
wait() [9/13]
void sc_core::sc_prim_channel::wait (double d, sc_time_unit u, const sc_event & e) protected
Definition at line 212 of file sc_prim.cc.
References sc_core::wait().
wait() [10/13]
void sc_core::sc_prim_channel::wait (const sc_time & t, const sc_event_or_list & eol) protected
Definition at line 218 of file sc_prim.cc.
References sc_core::wait().
wait() [11/13]
void sc_core::sc_prim_channel::wait (double d, sc_time_unit u, const sc_event_or_list & eol) protected
Definition at line 224 of file sc_prim.cc.
References sc_core::wait().
wait() [12/13]
void sc_core::sc_prim_channel::wait (const sc_time & t, const sc_event_and_list & eal) protected
Definition at line 230 of file sc_prim.cc.
References sc_core::wait().
wait() [13/13]
void sc_core::sc_prim_channel::wait (double d, sc_time_unit u, const sc_event_and_list & eal) protected
Definition at line 236 of file sc_prim.cc.
References sc_core::wait().
Friends And Related Function Documentation
sc_gem5::Channel
friend class sc_gem5::Channel friend
Definition at line 108 of file sc_prim.hh.
sc_gem5::Kernel
friend class sc_gem5::Kernel friend
Definition at line 96 of file sc_prim.hh.
Member Data Documentation
_gem5_channel
sc_gem5::Channel* sc_core::sc_prim_channel::_gem5_channel private
Definition at line 109 of file sc_prim.hh.
Referenced by async_request_update(), request_update(), sc_prim_channel(), and ~sc_prim_channel().
The documentation for this class was generated from the following files:
systemc/ext/core/sc_prim.hh
systemc/core/sc_prim.cc