gem5: AtagHeader Class Reference
AtagHeader Class Reference abstract
#include <atag.hh>
Public Member Functions
virtual uint32_t tag ()=0
Tag (normally starts with 'T''A' and 16 bits of number.
virtual bool null ()
If the header should be 0 size.
uint32_t size () const
AtagHeader (uint32_t s)
virtual ~AtagHeader ()
uint32_t copyOut (uint8_t *p)
Protected Attributes
uint32_t * storage
uint32_t _size
Detailed Description
Definition at line 57 of file atag.hh.
Constructor & Destructor Documentation
AtagHeader()
AtagHeader::AtagHeader (uint32_t s) inline
Definition at line 71 of file atag.hh.
References size().
~AtagHeader()
virtual AtagHeader::~AtagHeader () inline virtual
Definition at line 77 of file atag.hh.
References storage.
Member Function Documentation
copyOut()
uint32_t AtagHeader::copyOut (uint8_t * p) inline
Definition at line 82 of file atag.hh.
References null(), size(), and tag().
Referenced by LinuxArmSystem::initState().
null()
virtual bool AtagHeader::null () inline virtual
If the header should be 0 size.
Reimplemented in AtagNone.
Definition at line 67 of file atag.hh.
Referenced by copyOut().
size()
uint32_t AtagHeader::size () const inline
Definition at line 69 of file atag.hh.
References _size.
Referenced by AtagHeader(), AtagCmdline::cmdline(), copyOut(), and LinuxArmSystem::initState().
tag()
virtual uint32_t AtagHeader::tag () pure virtual
Tag (normally starts with 'T''A' and 16 bits of number.
Implemented in AtagNone, AtagCmdline, AtagSerial, AtagRev, AtagMem, and AtagCore.
Referenced by copyOut().
Member Data Documentation
_size
uint32_t AtagHeader::_size protected
Definition at line 61 of file atag.hh.
Referenced by AtagCmdline::cmdline(), and size().
storage
uint32_t* AtagHeader::storage protected
Definition at line 60 of file atag.hh.
Referenced by AtagCmdline::cmdline(), AtagCore::flags(), AtagMem::memSize(), AtagMem::memStart(), AtagCore::pagesize(), AtagRev::rev(), AtagCore::rootdev(), AtagSerial::sn(), and ~AtagHeader().
The documentation for this class was generated from the following file:
arch/arm/linux/atag.hh