gem5: TreePLRURP Class Reference
TreePLRURP Class Reference
#include <tree_plru_rp.hh>
Classes
struct TreePLRUReplData
Tree-PLRU-specific implementation of replacement data.
Public Types
typedef TreePLRURPParams Params
Convenience typedef.
Public Types inherited from BaseReplacementPolicy
typedef BaseReplacementPolicyParams Params
Convenience typedef.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
TreePLRURP (const Params *p)
Construct and initiliaze this replacement policy.
~TreePLRURP ()
Destructor.
void invalidate (const std::shared_ptr< ReplacementData > &replacement_data) const override
Invalidate replacement data to set it as the next probable victim.
void touch (const std::shared_ptr< ReplacementData > &replacement_data) const override
Touch an entry to update its replacement data.
void reset (const std::shared_ptr< ReplacementData > &replacement_data) const override
Reset replacement data.
ReplaceableEntry * getVictim (const ReplacementCandidates &candidates) const override
Find replacement victim using TreePLRU bits.
std::shared_ptr< ReplacementData > instantiateEntry () override
Instantiate a replacement data entry.
Public Member Functions inherited from BaseReplacementPolicy
BaseReplacementPolicy (const Params *p)
Construct and initiliaze this replacement policy.
virtual ~BaseReplacementPolicy ()
Destructor.
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void init ()
init() is called after all C++ SimObjects have been created and all ports are connected.
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual Port & getPort (const std::string &if_name, PortID idx=InvalidPortID)
Get a port with a given name and index.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Private Types
typedef std::vector< bool > PLRUTree
Instead of implementing the tree itself with pointers, it is implemented as an array of bits.
Private Attributes
const uint64_t numLeaves
Number of leaves that share a single replacement data.
uint64_t count
Count of the number of sharers of a replacement data.
PLRUTree * treeInstance
Holds the latest temporary tree instance created by instantiateEntry().
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 82 of file tree_plru_rp.hh.
Member Typedef Documentation
Params
typedef TreePLRURPParams TreePLRURP::Params
Convenience typedef.
Definition at line 155 of file tree_plru_rp.hh.
PLRUTree
typedef std::vector<bool> TreePLRURP::PLRUTree private
Instead of implementing the tree itself with pointers, it is implemented as an array of bits.
The index of the node defines its position in the tree, and its parent. Index 0 represents the root, 1 is its left node, and 2 is its right node. Then, in a BFS fashion this is expanded to the following nodes (3 and 4 are respectively 1's left and right nodes, and 5 and 6 are 2's left and right nodes, and so on).
i.e., the following trees are equivalent in this representation: ____1____ 0 1 0 1 1 0 A B C D E F G H
1 0 1 0 1 1 0
Notice that the replacement data entries are not represented in the tree to avoid unnecessary storage costs.
Definition at line 104 of file tree_plru_rp.hh.
Constructor & Destructor Documentation
TreePLRURP()
TreePLRURP::TreePLRURP (const Params * p)
Construct and initiliaze this replacement policy.
Definition at line 100 of file tree_plru_rp.cc.
References fatal_if, isPowerOf2(), and numLeaves.
Referenced by instantiateEntry().
~TreePLRURP()
TreePLRURP::~TreePLRURP () inline
Destructor.
Definition at line 165 of file tree_plru_rp.hh.
References getVictim(), instantiateEntry(), invalidate(), reset(), and touch().
Member Function Documentation
getVictim()
ReplaceableEntry * TreePLRURP::getVictim (const ReplacementCandidates & candidates) const override virtual
Find replacement victim using TreePLRU bits.
It is assumed that all candidates share the same replacement data tree.
Parameters
candidates Replacement candidates, selected by indexing policy.
Returns
Replacement entry to be replaced.
Implements BaseReplacementPolicy.
Definition at line 169 of file tree_plru_rp.cc.
References leftSubtreeIndex(), numLeaves, and rightSubtreeIndex().
Referenced by ~TreePLRURP().
instantiateEntry()
std::shared_ptr< ReplacementData > TreePLRURP::instantiateEntry () override virtual
Instantiate a replacement data entry.
Consecutive calls to this function use the same tree up to numLeaves. When numLeaves replacement data have been created, a new tree is generated, and the counter is reset. Therefore, it is essential that entries that share the same replacement data call this function consecutively.
Returns
A shared pointer to the new replacement data.
Implements BaseReplacementPolicy.
Definition at line 197 of file tree_plru_rp.cc.
References count, numLeaves, treeInstance, and TreePLRURP().
Referenced by ~TreePLRURP().
invalidate()
void TreePLRURP::invalidate (const std::shared_ptr< ReplacementData > & replacement_data) const override virtual
Invalidate replacement data to set it as the next probable victim.
Makes tree leaf of replacement data the LRU (tree bits point to it).
Parameters
replacement_data Replacement data to be invalidated.
Implements BaseReplacementPolicy.
Definition at line 109 of file tree_plru_rp.cc.
References isRightSubtree(), and parentIndex().
Referenced by ~TreePLRURP().
reset()
void TreePLRURP::reset (const std::shared_ptr< ReplacementData > & replacement_data) const override virtual
Reset replacement data.
Used when an entry is inserted. Provides the same functionality as touch().
Parameters
replacement_data Replacement data to be reset.
Implements BaseReplacementPolicy.
Definition at line 161 of file tree_plru_rp.cc.
References touch().
Referenced by ~TreePLRURP().
touch()
void TreePLRURP::touch (const std::shared_ptr< ReplacementData > & replacement_data) const override virtual
Touch an entry to update its replacement data.
Makes tree leaf of replacement data the MRU.
Parameters
replacement_data Replacement data to be touched.
Implements BaseReplacementPolicy.
Definition at line 135 of file tree_plru_rp.cc.
References isRightSubtree(), and parentIndex().
Referenced by reset(), and ~TreePLRURP().
Member Data Documentation
count
uint64_t TreePLRURP::count private
Count of the number of sharers of a replacement data.
It is used when instantiating entries to share a replacement data among many replaceable entries.
Definition at line 116 of file tree_plru_rp.hh.
Referenced by instantiateEntry().
numLeaves
const uint64_t TreePLRURP::numLeaves private
Number of leaves that share a single replacement data.
Definition at line 109 of file tree_plru_rp.hh.
Referenced by getVictim(), instantiateEntry(), and TreePLRURP().
treeInstance
PLRUTree* TreePLRURP::treeInstance private
Holds the latest temporary tree instance created by instantiateEntry().
Definition at line 121 of file tree_plru_rp.hh.
Referenced by instantiateEntry().
The documentation for this class was generated from the following files:
mem/cache/replacement_policies/tree_plru_rp.hh
mem/cache/replacement_policies/tree_plru_rp.cc