gem5: ExecContext Class Reference
ExecContext Class Reference abstract
The ExecContext is an abstract base class the provides the interface used by the ISA to manipulate the state of the CPU model.
#include <exec_context.hh>
Public Types
typedef TheISA::PCState PCState
using VecRegContainer = TheISA::VecRegContainer
using VecElem = TheISA::VecElem
using VecPredRegContainer = TheISA::VecPredRegContainer
Public Member Functions
virtual ThreadContext * tcBase ()=0
Returns a pointer to the ThreadContext.
Integer Register Interfaces
virtual RegVal readIntRegOperand (const StaticInst *si, int idx)=0
Reads an integer register.
virtual void setIntRegOperand (const StaticInst *si, int idx, RegVal val)=0
Sets an integer register to a value.
Floating Point Register Interfaces
virtual RegVal readFloatRegOperandBits (const StaticInst *si, int idx)=0
Reads a floating point register in its binary format, instead of by value.
virtual void setFloatRegOperandBits (const StaticInst *si, int idx, RegVal val)=0
Sets the bits of a floating point register of single width to a binary value.
virtual const VecRegContainer & readVecRegOperand (const StaticInst *si, int idx) const =0
Vector Register Interfaces.
virtual VecRegContainer & getWritableVecRegOperand (const StaticInst *si, int idx)=0
Gets destination vector register operand for modification.
virtual void setVecRegOperand (const StaticInst *si, int idx, const VecRegContainer &val)=0
Sets a destination vector register operand to a value.
virtual ConstVecLane8 readVec8BitLaneOperand (const StaticInst *si, int idx) const =0
Vector Register Lane Interfaces.
virtual ConstVecLane16 readVec16BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 16bit operand.
virtual ConstVecLane32 readVec32BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 32bit operand.
virtual ConstVecLane64 readVec64BitLaneOperand (const StaticInst *si, int idx) const =0
Reads source vector 64bit operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::Byte > &val)=0
Write a lane of the destination vector operand.
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::TwoByte > &val)=0
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::FourByte > &val)=0
virtual void setVecLaneOperand (const StaticInst *si, int idx, const LaneData< LaneSize::EightByte > &val)=0
virtual VecElem readVecElemOperand (const StaticInst *si, int idx) const =0
Vector Elem Interfaces.
virtual void setVecElemOperand (const StaticInst *si, int idx, const VecElem val)=0
Sets a vector register to a value.
virtual const VecPredRegContainer & readVecPredRegOperand (const StaticInst *si, int idx) const =0
Predicate registers interface.
virtual VecPredRegContainer & getWritableVecPredRegOperand (const StaticInst *si, int idx)=0
Gets destination predicate register operand for modification.
virtual void setVecPredRegOperand (const StaticInst *si, int idx, const VecPredRegContainer &val)=0
Sets a destination predicate register operand to a value.
Condition Code Registers
virtual RegVal readCCRegOperand (const StaticInst *si, int idx)=0
virtual void setCCRegOperand (const StaticInst *si, int idx, RegVal val)=0
Misc Register Interfaces
virtual RegVal readMiscRegOperand (const StaticInst *si, int idx)=0
virtual void setMiscRegOperand (const StaticInst *si, int idx, RegVal val)=0
virtual RegVal readMiscReg (int misc_reg)=0
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
virtual void setMiscReg (int misc_reg, RegVal val)=0
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
PC Control
virtual PCState pcState () const =0
virtual void pcState (const PCState &val)=0
Memory Interface
virtual Fault readMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Perform an atomic memory read operation.
virtual Fault initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > &byteEnable=std::vector< bool >())
Initiate a timing memory read operation.
virtual Fault writeMem (uint8_t *data, unsigned int size, Addr addr, Request::Flags flags, uint64_t *res, const std::vector< bool > &byteEnable=std::vector< bool >())=0
For atomic-mode contexts, perform an atomic memory write operation.
virtual Fault amoMem (Addr addr, uint8_t *data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
virtual Fault initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op)
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
virtual void setStCondFailures (unsigned int sc_failures)=0
Sets the number of consecutive store conditional failures.
virtual unsigned int readStCondFailures () const =0
Returns the number of consecutive store conditional failures.
SysCall Emulation Interfaces
virtual void syscall (int64_t callnum, Fault *fault)=0
Executes a syscall specified by the callnum.
ARM-Specific Interfaces
virtual bool readPredicate () const =0
virtual void setPredicate (bool val)=0
virtual bool readMemAccPredicate () const =0
virtual void setMemAccPredicate (bool val)=0
X86-Specific Interfaces
virtual void demapPage (Addr vaddr, uint64_t asn)=0
Invalidate a page in the DTLB and ITLB.
virtual void armMonitor (Addr address)=0
virtual bool mwait (PacketPtr pkt)=0
virtual void mwaitAtomic (ThreadContext *tc)=0
virtual AddressMonitor * getAddrMonitor ()=0
Detailed Description
The ExecContext is an abstract base class the provides the interface used by the ISA to manipulate the state of the CPU model.
Register accessor methods in this class typically provide the index of the instruction's operand (e.g., 0 or 1), not the architectural register index, to simplify the implementation of register renaming. The architectural register index can be found by indexing into the instruction's own operand index table.
Note
The methods in this class typically take a raw pointer to the StaticInst is provided instead of a ref-counted StaticInstPtr to reduce overhead as an argument. This is fine as long as the implementation doesn't copy the pointer into any long-term storage (which is pretty hard to imagine they would have reason to do).
Definition at line 73 of file exec_context.hh.
Member Typedef Documentation
PCState
typedef TheISA::PCState ExecContext::PCState
Definition at line 75 of file exec_context.hh.
VecElem
using ExecContext::VecElem = TheISA::VecElem
Definition at line 78 of file exec_context.hh.
VecPredRegContainer
using ExecContext::VecPredRegContainer = TheISA::VecPredRegContainer
Definition at line 79 of file exec_context.hh.
VecRegContainer
using ExecContext::VecRegContainer = TheISA::VecRegContainer
Definition at line 77 of file exec_context.hh.
Member Function Documentation
amoMem()
virtual Fault ExecContext::amoMem (Addr addr, uint8_t * data, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) inline virtual
For atomic-mode contexts, perform an atomic AMO (a.k.a., Atomic Read-Modify-Write Memory Operation)
Reimplemented in SimpleExecContext.
Definition at line 271 of file exec_context.hh.
References panic.
armMonitor()
virtual void ExecContext::armMonitor (Addr address) pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
demapPage()
virtual void ExecContext::demapPage (Addr vaddr, uint64_t asn) pure virtual
Invalidate a page in the DTLB and ITLB.
Implemented in SimpleExecContext, CheckerCPU, Minor::ExecContext, and BaseDynInst< Impl >.
Referenced by initiateMemAMO().
getAddrMonitor()
virtual AddressMonitor* ExecContext::getAddrMonitor () pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
getWritableVecPredRegOperand()
virtual VecPredRegContainer& ExecContext::getWritableVecPredRegOperand (const StaticInst * si, int idx) pure virtual
Gets destination predicate register operand for modification.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
getWritableVecRegOperand()
virtual VecRegContainer& ExecContext::getWritableVecRegOperand (const StaticInst * si, int idx) pure virtual
Gets destination vector register operand for modification.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
initiateMemAMO()
virtual Fault ExecContext::initiateMemAMO (Addr addr, unsigned int size, Request::Flags flags, AtomicOpFunctorPtr amo_op) inline virtual
For timing-mode contexts, initiate an atomic AMO (atomic read-modify-write memory operation)
Reimplemented in SimpleExecContext, and Minor::ExecContext.
Definition at line 282 of file exec_context.hh.
References armMonitor(), demapPage(), getAddrMonitor(), mwait(), mwaitAtomic(), panic, readMemAccPredicate(), readPredicate(), readStCondFailures(), setMemAccPredicate(), setPredicate(), setStCondFailures(), syscall(), tcBase(), MipsISA::vaddr, and X86ISA::val.
initiateMemRead()
virtual Fault ExecContext::initiateMemRead (Addr addr, unsigned int size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>()) inline virtual
Initiate a timing memory read operation.
Must be overridden for exec contexts that support timing memory mode. Not pure virtual since exec contexts that only support atomic memory mode need not override (though in that case this function should never be called).
Reimplemented in SimpleExecContext, and Minor::ExecContext.
Definition at line 251 of file exec_context.hh.
References panic, and writeMem().
Referenced by X86ISA::initiateMemRead().
mwait()
virtual bool ExecContext::mwait (PacketPtr pkt) pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
mwaitAtomic()
virtual void ExecContext::mwaitAtomic (ThreadContext * tc) pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
pcState() [1/2]
virtual PCState ExecContext::pcState () const pure virtual
Implemented in BaseDynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
Referenced by DecoderFaultInst::execute(), ArmISA::ArmStaticInst::readPC(), ArmISA::ArmStaticInst::setAIWNextPC(), ArmISA::ArmStaticInst::setIWNextPC(), and ArmISA::ArmStaticInst::setNextPC().
pcState() [2/2]
virtual void ExecContext::pcState (const PCState & val) pure virtual
Implemented in BaseDynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
readCCRegOperand()
virtual RegVal ExecContext::readCCRegOperand (const StaticInst * si, int idx) pure virtual
Implemented in Minor::ExecContext, BaseO3DynInst< Impl >, SimpleExecContext, and CheckerCPU.
readFloatRegOperandBits()
virtual RegVal ExecContext::readFloatRegOperandBits (const StaticInst * si, int idx) pure virtual
Reads a floating point register in its binary format, instead of by value.
Implemented in BaseO3DynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
readIntRegOperand()
virtual RegVal ExecContext::readIntRegOperand (const StaticInst * si, int idx) pure virtual
Reads an integer register.
Implemented in BaseO3DynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
readMem()
virtual Fault ExecContext::readMem (Addr addr, uint8_t * data, unsigned int size, Request::Flags flags, const std::vector< bool > & byteEnable = std::vector<bool>()) inline virtual
Perform an atomic memory read operation.
Must be overridden for exec contexts that support atomic memory mode. Not pure virtual since exec contexts that only support timing memory mode need not override (though in that case this function should never be called).
Reimplemented in SimpleExecContext.
Definition at line 237 of file exec_context.hh.
References panic.
Referenced by X86ISA::readMemAtomic(), and X86ISA::readPackedMemAtomic().
readMemAccPredicate()
virtual bool ExecContext::readMemAccPredicate () const pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
readMiscReg()
virtual RegVal ExecContext::readMiscReg (int misc_reg) pure virtual
Reads a miscellaneous register, handling any architectural side effects due to reading that register.
Implemented in CheckerCPU, SimpleExecContext, Minor::ExecContext, and BaseO3DynInst< Impl >.
readMiscRegOperand()
virtual RegVal ExecContext::readMiscRegOperand (const StaticInst * si, int idx) pure virtual
Implemented in CheckerCPU, SimpleExecContext, Minor::ExecContext, and BaseO3DynInst< Impl >.
readPredicate()
virtual bool ExecContext::readPredicate () const pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
readStCondFailures()
virtual unsigned int ExecContext::readStCondFailures () const pure virtual
Returns the number of consecutive store conditional failures.
Implemented in BaseDynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
Referenced by initiateMemAMO().
readVec16BitLaneOperand()
virtual ConstVecLane16 ExecContext::readVec16BitLaneOperand (const StaticInst * si, int idx) const pure virtual
Reads source vector 16bit operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
readVec32BitLaneOperand()
virtual ConstVecLane32 ExecContext::readVec32BitLaneOperand (const StaticInst * si, int idx) const pure virtual
Reads source vector 32bit operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
readVec64BitLaneOperand()
virtual ConstVecLane64 ExecContext::readVec64BitLaneOperand (const StaticInst * si, int idx) const pure virtual
Reads source vector 64bit operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
readVec8BitLaneOperand()
virtual ConstVecLane8 ExecContext::readVec8BitLaneOperand (const StaticInst * si, int idx) const pure virtual
Vector Register Lane Interfaces.
Reads source vector 8bit operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
readVecElemOperand()
virtual VecElem ExecContext::readVecElemOperand (const StaticInst * si, int idx) const pure virtual
Vector Elem Interfaces.
Reads an element of a vector register.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
readVecPredRegOperand()
virtual const VecPredRegContainer& ExecContext::readVecPredRegOperand (const StaticInst * si, int idx) const pure virtual
Predicate registers interface.
Reads source predicate register operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
readVecRegOperand()
virtual const VecRegContainer& ExecContext::readVecRegOperand (const StaticInst * si, int idx) const pure virtual
Vector Register Interfaces.
Reads source vector register operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
setCCRegOperand()
virtual void ExecContext::setCCRegOperand (const StaticInst * si, int idx, RegVal val) pure virtual
Implemented in BaseDynInst< Impl >, Minor::ExecContext, BaseO3DynInst< Impl >, CheckerCPU, and SimpleExecContext.
setFloatRegOperandBits()
virtual void ExecContext::setFloatRegOperandBits (const StaticInst * si, int idx, RegVal val) pure virtual
Sets the bits of a floating point register of single width to a binary value.
Implemented in BaseDynInst< Impl >, BaseO3DynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
setIntRegOperand()
virtual void ExecContext::setIntRegOperand (const StaticInst * si, int idx, RegVal val) pure virtual
Sets an integer register to a value.
Implemented in BaseDynInst< Impl >, BaseO3DynInst< Impl >, CheckerCPU, Minor::ExecContext, and SimpleExecContext.
setMemAccPredicate()
virtual void ExecContext::setMemAccPredicate (bool val) pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
setMiscReg()
virtual void ExecContext::setMiscReg (int misc_reg, RegVal val) pure virtual
Sets a miscellaneous register, handling any architectural side effects due to writing that register.
Implemented in CheckerCPU, SimpleExecContext, Minor::ExecContext, and BaseO3DynInst< Impl >.
setMiscRegOperand()
virtual void ExecContext::setMiscRegOperand (const StaticInst * si, int idx, RegVal val) pure virtual
Implemented in CheckerCPU, SimpleExecContext, Minor::ExecContext, and BaseO3DynInst< Impl >.
setPredicate()
virtual void ExecContext::setPredicate (bool val) pure virtual
Implemented in BaseDynInst< Impl >, SimpleExecContext, CheckerCPU, and Minor::ExecContext.
Referenced by initiateMemAMO().
setStCondFailures()
virtual void ExecContext::setStCondFailures (unsigned int sc_failures) pure virtual
Sets the number of consecutive store conditional failures.
Implemented in BaseDynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
Referenced by initiateMemAMO().
setVecElemOperand()
virtual void ExecContext::setVecElemOperand (const StaticInst * si, int idx, const VecElem val) pure virtual
Sets a vector register to a value.
Implemented in BaseDynInst< Impl >, BaseO3DynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
setVecLaneOperand() [1/4]
virtual void ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::Byte > & val) pure virtual
Write a lane of the destination vector operand.
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
setVecLaneOperand() [2/4]
virtual void ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::TwoByte > & val) pure virtual
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
setVecLaneOperand() [3/4]
virtual void ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::FourByte > & val) pure virtual
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
setVecLaneOperand() [4/4]
virtual void ExecContext::setVecLaneOperand (const StaticInst * si, int idx, const LaneData< LaneSize::EightByte > & val) pure virtual
Implemented in BaseO3DynInst< Impl >, SimpleExecContext, Minor::ExecContext, and CheckerCPU.
setVecPredRegOperand()
virtual void ExecContext::setVecPredRegOperand (const StaticInst * si, int idx, const VecPredRegContainer & val) pure virtual
Sets a destination predicate register operand to a value.
Implemented in BaseDynInst< Impl >, BaseO3DynInst< Impl >, CheckerCPU, and SimpleExecContext.
setVecRegOperand()
virtual void ExecContext::setVecRegOperand (const StaticInst * si, int idx, const VecRegContainer & val) pure virtual
Sets a destination vector register operand to a value.
Implemented in BaseDynInst< Impl >, BaseO3DynInst< Impl >, CheckerCPU, and SimpleExecContext.
syscall()
virtual void ExecContext::syscall (int64_t callnum, Fault * fault) pure virtual
Executes a syscall specified by the callnum.
Implemented in CheckerCPU, SimpleExecContext, Minor::ExecContext, and BaseO3DynInst< Impl >.
Referenced by initiateMemAMO().
tcBase()
virtual ThreadContext* ExecContext::tcBase () pure virtual
Returns a pointer to the ThreadContext.
Implemented in BaseDynInst< Impl >, CheckerCPU, SimpleExecContext, and Minor::ExecContext.
Referenced by MiscRegImplDefined64::execute(), McrMrcMiscInst::execute(), McrMrcImplDefined::execute(), initiateMemAMO(), MipsISA::readRegOtherThread(), MipsISA::setRegOtherThread(), and ArmISA::ArmStaticInst::softwareBreakpoint32().
writeMem()
virtual Fault ExecContext::writeMem (uint8_t * data, unsigned int size, Addr addr, Request::Flags flags, uint64_t * res, const std::vector< bool > & byteEnable = std::vector< bool >()) pure virtual
For atomic-mode contexts, perform an atomic memory write operation.
For timing-mode contexts, initiate a timing memory write operation.
Implemented in SimpleExecContext, and Minor::ExecContext.
Referenced by initiateMemRead(), X86ISA::writeMemAtomic(), X86ISA::writeMemTiming(), and X86ISA::writePackedMem().
The documentation for this class was generated from the following file:
cpu/exec_context.hh