gem5: sc_dt::sc_uint_base Class Reference
sc_dt::sc_uint_base Class Reference
#include <sc_uint_base.hh>
Public Member Functions
sc_uint_base (int w=sc_length_param().len())
sc_uint_base (uint_type v, int w)
sc_uint_base (const sc_uint_base &a)
sc_uint_base (const sc_uint_subref_r &a)
template<class T >
sc_uint_base (const sc_generic_base< T > &a)
sc_uint_base (const sc_bv_base &v)
sc_uint_base (const sc_lv_base &v)
sc_uint_base (const sc_int_subref_r &v)
sc_uint_base (const sc_signed_subref_r &v)
sc_uint_base (const sc_unsigned_subref_r &v)
sc_uint_base (const sc_signed &a)
sc_uint_base (const sc_unsigned &a)
virtual ~sc_uint_base ()
sc_uint_base & operator= (uint_type v)
sc_uint_base & operator= (const sc_uint_base &a)
sc_uint_base & operator= (const sc_uint_subref_r &a)
template<class T >
sc_uint_base & operator= (const sc_generic_base< T > &a)
sc_uint_base & operator= (const sc_signed &a)
sc_uint_base & operator= (const sc_unsigned &a)
sc_uint_base & operator= (const sc_fxval &a)
sc_uint_base & operator= (const sc_fxval_fast &a)
sc_uint_base & operator= (const sc_fxnum &a)
sc_uint_base & operator= (const sc_fxnum_fast &a)
sc_uint_base & operator= (const sc_bv_base &a)
sc_uint_base & operator= (const sc_lv_base &a)
sc_uint_base & operator= (const char *a)
sc_uint_base & operator= (unsigned long a)
sc_uint_base & operator= (long a)
sc_uint_base & operator= (unsigned int a)
sc_uint_base & operator= (int a)
sc_uint_base & operator= (int64 a)
sc_uint_base & operator= (double a)
sc_uint_base & operator+= (uint_type v)
sc_uint_base & operator-= (uint_type v)
sc_uint_base & operator*= (uint_type v)
sc_uint_base & operator/= (uint_type v)
sc_uint_base & operator%= (uint_type v)
sc_uint_base & operator&= (uint_type v)
sc_uint_base & operator|= (uint_type v)
sc_uint_base & operator^= (uint_type v)
sc_uint_base & operator<<= (uint_type v)
sc_uint_base & operator>>= (uint_type v)
sc_uint_base & operator++ ()
const sc_uint_base operator++ (int)
sc_uint_base & operator-- ()
const sc_uint_base operator-- (int)
sc_uint_bitref & operator[] (int i)
const sc_uint_bitref_r & operator[] (int i) const
sc_uint_bitref & bit (int i)
const sc_uint_bitref_r & bit (int i) const
sc_uint_subref & operator() (int left, int right)
const sc_uint_subref_r & operator() (int left, int right) const
sc_uint_subref & range (int left, int right)
const sc_uint_subref_r & range (int left, int right) const
bool test (int i) const
void set (int i)
void set (int i, bool v)
int length () const
virtual int concat_length (bool *xz_present_p) const
virtual bool concat_get_ctrl (sc_digit *dst_p, int low_i) const
virtual bool concat_get_data (sc_digit *dst_p, int low_i) const
virtual uint64 concat_get_uint64 () const
virtual void concat_set (int64 src, int low_i)
virtual void concat_set (const sc_signed &src, int low_i)
virtual void concat_set (const sc_unsigned &src, int low_i)
virtual void concat_set (uint64 src, int low_i)
bool and_reduce () const
bool nand_reduce () const
bool or_reduce () const
bool nor_reduce () const
bool xor_reduce () const
bool xnor_reduce () const
operator uint_type () const
uint_type value () const
int to_int () const
unsigned int to_uint () const
long to_long () const
unsigned long to_ulong () const
int64 to_int64 () const
uint64 to_uint64 () const
double to_double () const
long long_low () const
long long_high () const
const std::string to_string (sc_numrep numrep=SC_DEC) const
const std::string to_string (sc_numrep numrep, bool w_prefix) const
void print (::std::ostream &os=::std::cout) const
void scan (::std::istream &is=::std::cin)
Public Member Functions inherited from sc_dt::sc_value_base
virtual ~sc_value_base ()
Protected Attributes
uint_type m_val
int m_len
int m_ulen
Private Member Functions
void invalid_length () const
void invalid_index (int i) const
void invalid_range (int l, int r) const
void check_length () const
void check_index (int i) const
void check_range (int l, int r) const
void check_value () const
void extend_sign ()
Friends
class sc_uint_bitref_r
class sc_uint_bitref
class sc_uint_subref_r
class sc_uint_subref
bool operator== (const sc_uint_base &a, const sc_uint_base &b)
bool operator!= (const sc_uint_base &a, const sc_uint_base &b)
bool operator< (const sc_uint_base &a, const sc_uint_base &b)
bool operator<= (const sc_uint_base &a, const sc_uint_base &b)
bool operator> (const sc_uint_base &a, const sc_uint_base &b)
bool operator>= (const sc_uint_base &a, const sc_uint_base &b)
Detailed Description
Definition at line 465 of file sc_uint_base.hh.
Constructor & Destructor Documentation
sc_uint_base() [1/12]
sc_dt::sc_uint_base::sc_uint_base (int w = sc_length_param().len()) inline explicit
Definition at line 514 of file sc_uint_base.hh.
sc_uint_base() [2/12]
sc_dt::sc_uint_base::sc_uint_base (uint_type v, int w) inline
Definition at line 520 of file sc_uint_base.hh.
sc_uint_base() [3/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_uint_base & a) inline
Definition at line 527 of file sc_uint_base.hh.
sc_uint_base() [4/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_uint_subref_r & a) inline explicit
Definition at line 531 of file sc_uint_base.hh.
sc_uint_base() [5/12]
template<class T > sc_dt::sc_uint_base::sc_uint_base (const sc_generic_base< T > & a) inline explicit
Definition at line 538 of file sc_uint_base.hh.
References ArmISA::a, and ArmISA::v.
sc_uint_base() [6/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_bv_base & v) explicit
Definition at line 389 of file sc_uint_base.cc.
References check_length(), and ArmISA::v.
sc_uint_base() [7/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_lv_base & v) explicit
Definition at line 395 of file sc_uint_base.cc.
References check_length(), and ArmISA::v.
sc_uint_base() [8/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_int_subref_r & v) explicit
Definition at line 401 of file sc_uint_base.cc.
References check_length(), and sc_dt::sc_int_subref_r::to_uint64().
sc_uint_base() [9/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_signed_subref_r & v) explicit
Definition at line 407 of file sc_uint_base.cc.
References check_length(), and sc_dt::sc_signed_subref_r::to_uint64().
sc_uint_base() [10/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_unsigned_subref_r & v) explicit
Definition at line 413 of file sc_uint_base.cc.
References check_length(), and sc_dt::sc_unsigned_subref_r::to_uint64().
sc_uint_base() [11/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_signed & a) explicit
Definition at line 420 of file sc_uint_base.cc.
References check_length(), and sc_dt::sc_signed::to_uint64().
sc_uint_base() [12/12]
sc_dt::sc_uint_base::sc_uint_base (const sc_unsigned & a) explicit
Definition at line 427 of file sc_uint_base.cc.
References check_length(), and sc_dt::sc_unsigned::to_uint64().
~sc_uint_base()
virtual sc_dt::sc_uint_base::~sc_uint_base () inline virtual
Definition at line 555 of file sc_uint_base.hh.
Member Function Documentation
and_reduce()
bool sc_dt::sc_uint_base::and_reduce () const
Definition at line 544 of file sc_uint_base.cc.
References m_ulen, m_val, and sc_dt::UINT_ZERO.
Referenced by sc_dt::sc_uint_subref_r::and_reduce(), and sc_dt::and_reduce().
bit() [1/2]
sc_uint_bitref & sc_dt::sc_uint_base::bit (int i) inline
Definition at line 1156 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::initialize(), and sc_dt::sc_uint_bitref::m_pool.
bit() [2/2]
const sc_uint_bitref_r & sc_dt::sc_uint_base::bit (int i) const inline
Definition at line 1165 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::initialize(), and sc_dt::sc_uint_bitref::m_pool.
check_index()
void sc_dt::sc_uint_base::check_index (int i) const inline private
Definition at line 486 of file sc_uint_base.hh.
check_length()
void sc_dt::sc_uint_base::check_length () const inline private
Definition at line 478 of file sc_uint_base.hh.
References SC_INTWIDTH.
Referenced by sc_uint_base().
check_range()
void sc_dt::sc_uint_base::check_range (int l, int r) const inline private
Definition at line 494 of file sc_uint_base.hh.
check_value()
void sc_dt::sc_uint_base::check_value () const private
Definition at line 377 of file sc_uint_base.cc.
References X86ISA::limit, sc_core::SC_ID_OUT_OF_BOUNDS_, SC_REPORT_WARNING, and sc_dt::UINT_ZERO.
concat_get_ctrl()
bool sc_dt::sc_uint_base::concat_get_ctrl (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 571 of file sc_uint_base.cc.
References BITS_PER_DIGIT, m_len, ArmISA::mask, and sc_dt::UINT_ZERO.
concat_get_data()
bool sc_dt::sc_uint_base::concat_get_data (sc_digit * dst_p, int low_i) const virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 608 of file sc_uint_base.cc.
References BITS_PER_DIGIT, DIGIT_MASK, m_len, m_val, ArmISA::mask, sc_dt::UINT_ZERO, and X86ISA::val.
concat_get_uint64()
virtual uint64 sc_dt::sc_uint_base::concat_get_uint64 () const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 815 of file sc_uint_base.hh.
References sc_dt::and_reduce().
concat_length()
virtual int sc_dt::sc_uint_base::concat_length (bool * xz_present_p) const inline virtual
Reimplemented from sc_dt::sc_value_base.
Definition at line 807 of file sc_uint_base.hh.
References length.
concat_set() [1/4]
void sc_dt::sc_uint_base::concat_set (int64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_uint< W > >.
Definition at line 669 of file sc_uint_base.cc.
concat_set() [2/4]
void sc_dt::sc_uint_base::concat_set (const sc_signed & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_uint< W > >.
Definition at line 675 of file sc_uint_base.cc.
References sc_dt::sc_signed::length().
concat_set() [3/4]
void sc_dt::sc_uint_base::concat_set (const sc_unsigned & src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_uint< W > >.
Definition at line 684 of file sc_uint_base.cc.
References sc_dt::sc_unsigned::length().
concat_set() [4/4]
void sc_dt::sc_uint_base::concat_set (uint64 src, int low_i) virtual
Reimplemented from sc_dt::sc_value_base.
Reimplemented in sc_core::sc_signal< sc_dt::sc_uint< W > >.
Definition at line 693 of file sc_uint_base.cc.
extend_sign()
void sc_dt::sc_uint_base::extend_sign () inline private
Definition at line 504 of file sc_uint_base.hh.
References sc_dt::UINT_ZERO.
Referenced by operator=().
invalid_index()
void sc_dt::sc_uint_base::invalid_index (int i) const private
Definition at line 355 of file sc_uint_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
invalid_length()
void sc_dt::sc_uint_base::invalid_length () const private
Definition at line 345 of file sc_uint_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, SC_INTWIDTH, and SC_REPORT_ERROR.
invalid_range()
void sc_dt::sc_uint_base::invalid_range (int l, int r) const private
Definition at line 365 of file sc_uint_base.cc.
References sc_core::sc_abort(), sc_core::SC_ID_OUT_OF_BOUNDS_, and SC_REPORT_ERROR.
length()
int sc_dt::sc_uint_base::length () const inline
Definition at line 803 of file sc_uint_base.hh.
Referenced by sc_dt::assign_v_().
long_high()
long sc_dt::sc_uint_base::long_high () const inline
Definition at line 844 of file sc_uint_base.hh.
References sc_dt::SC_DEC, sc_dt::to_string(), and sc_dt::UINT64_32ONES.
long_low()
long sc_dt::sc_uint_base::long_low () const inline
Definition at line 843 of file sc_uint_base.hh.
References sc_dt::UINT64_32ONES.
nand_reduce()
bool sc_dt::sc_uint_base::nand_reduce () const inline
Definition at line 823 of file sc_uint_base.hh.
References sc_dt::and_reduce(), and sc_dt::or_reduce().
Referenced by sc_dt::nand_reduce().
nor_reduce()
bool sc_dt::sc_uint_base::nor_reduce () const inline
Definition at line 825 of file sc_uint_base.hh.
References sc_dt::or_reduce(), and sc_dt::xor_reduce().
Referenced by sc_dt::nor_reduce().
operator uint_type()
sc_dt::sc_uint_base::operator uint_type () const inline
Definition at line 830 of file sc_uint_base.hh.
operator%=()
sc_uint_base& sc_dt::sc_uint_base::operator%= (uint_type v) inline
Definition at line 669 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator%=().
operator&=()
sc_uint_base& sc_dt::sc_uint_base::operator &= (uint_type v) inline
Definition at line 678 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator&=().
operator()() [1/2]
sc_uint_subref & sc_dt::sc_uint_base::operator() (int left, int right) inline
Definition at line 1175 of file sc_uint_base.hh.
References sc_dt::sc_uint_subref_r::initialize(), and sc_dt::sc_uint_subref::m_pool.
operator()() [2/2]
const sc_uint_subref_r & sc_dt::sc_uint_base::operator() (int left, int right) const inline
Definition at line 1184 of file sc_uint_base.hh.
References sc_dt::sc_uint_subref_r::initialize(), and sc_dt::sc_uint_subref::m_pool.
operator*=()
sc_uint_base& sc_dt::sc_uint_base::operator*= (uint_type v) inline
Definition at line 655 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator*=().
operator++() [1/2]
sc_uint_base& sc_dt::sc_uint_base::operator++ () inline
Definition at line 715 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint< W >::operator++().
operator++() [2/2]
const sc_uint_base sc_dt::sc_uint_base::operator++ (int) inline
Definition at line 722 of file sc_uint_base.hh.
operator+=()
sc_uint_base& sc_dt::sc_uint_base::operator+= (uint_type v) inline
Definition at line 641 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator+=().
operator--() [1/2]
sc_uint_base& sc_dt::sc_uint_base::operator-- () inline
Definition at line 731 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint< W >::operator--().
operator--() [2/2]
const sc_uint_base sc_dt::sc_uint_base::operator-- (int) inline
Definition at line 738 of file sc_uint_base.hh.
operator-=()
sc_uint_base& sc_dt::sc_uint_base::operator-= (uint_type v) inline
Definition at line 648 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator-=().
operator/=()
sc_uint_base& sc_dt::sc_uint_base::operator/= (uint_type v) inline
Definition at line 662 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator/=().
operator<<=()
sc_uint_base& sc_dt::sc_uint_base::operator<<= (uint_type v) inline
Definition at line 699 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator<<=().
operator=() [1/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (uint_type v) inline
Definition at line 559 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator=(), operator=(), sc_dt::sc_uint< W >::sc_uint(), and sc_core::sc_signal< sc_dt::sc_uint< W > >::update().
operator=() [2/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (const sc_uint_base & a) inline
Definition at line 566 of file sc_uint_base.hh.
References m_val.
operator=() [3/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (const sc_uint_subref_r & a) inline
Definition at line 573 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [4/19]
template<class T > sc_uint_base& sc_dt::sc_uint_base::operator= (const sc_generic_base< T > & a) inline
Definition at line 581 of file sc_uint_base.hh.
operator=() [5/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_signed & a)
Definition at line 437 of file sc_uint_base.cc.
References extend_sign(), ArmISA::i, sc_dt::sc_signed::length(), m_len, sc_dt::sc_min(), sc_dt::sc_signed::sign(), and sc_dt::sc_signed::test().
operator=() [6/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_unsigned & a)
Definition at line 454 of file sc_uint_base.cc.
References extend_sign(), ArmISA::i, sc_dt::sc_unsigned::length(), m_len, sc_dt::sc_min(), and sc_dt::sc_unsigned::test().
operator=() [7/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_fxval & a) inline
Definition at line 264 of file scfx_other_defs.hh.
References sc_dt::sc_fxval::get_bit(), ArmISA::i, sc_dt::sc_fxval::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [8/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_fxval_fast & a) inline
Definition at line 279 of file scfx_other_defs.hh.
References sc_dt::sc_fxval_fast::get_bit(), ArmISA::i, sc_dt::sc_fxval_fast::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [9/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_fxnum & a) inline
Definition at line 294 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum::get_bit(), ArmISA::i, sc_dt::sc_fxnum::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [10/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_fxnum_fast & a) inline
Definition at line 309 of file scfx_other_defs.hh.
References sc_dt::sc_fxnum_fast::get_bit(), ArmISA::i, sc_dt::sc_fxnum_fast::is_normal(), sc_core::SC_ID_INVALID_FX_VALUE_, and SC_REPORT_ERROR.
operator=() [11/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_bv_base & a)
Definition at line 471 of file sc_uint_base.cc.
References extend_sign(), sc_dt::sc_bv_base::get_bit(), ArmISA::i, sc_dt::sc_bv_base::length(), m_len, and sc_dt::sc_min().
operator=() [12/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const sc_lv_base & a)
Definition at line 487 of file sc_uint_base.cc.
References extend_sign(), sc_dt::sc_lv_base::get_bit(), ArmISA::i, sc_dt::sc_lv_base::length(), m_len, sc_dt::sc_min(), and to_bool().
operator=() [13/19]
sc_uint_base & sc_dt::sc_uint_base::operator= (const char * a)
Definition at line 503 of file sc_uint_base.cc.
References PowerISA::aa, ArmISA::len, m_len, operator=(), sc_core::SC_ID_CONVERSION_FAILED_, sc_dt::SC_ON, SC_REPORT_ERROR, sc_dt::SC_TRN, and sc_dt::SC_WRAP.
operator=() [14/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (unsigned long a) inline
Definition at line 597 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [15/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (long a) inline
Definition at line 604 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [16/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (unsigned int a) inline
Definition at line 611 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [17/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (int a) inline
Definition at line 618 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [18/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (int64 a) inline
Definition at line 625 of file sc_uint_base.hh.
References ArmISA::a.
operator=() [19/19]
sc_uint_base& sc_dt::sc_uint_base::operator= (double a) inline
Definition at line 632 of file sc_uint_base.hh.
operator>>=()
sc_uint_base& sc_dt::sc_uint_base::operator>>= (uint_type v) inline
Definition at line 706 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator>>=().
operator[]() [1/2]
sc_uint_bitref & sc_dt::sc_uint_base::operator[] (int i) inline
Definition at line 1138 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::initialize(), and sc_dt::sc_uint_bitref::m_pool.
operator[]() [2/2]
const sc_uint_bitref_r & sc_dt::sc_uint_base::operator[] (int i) const inline
Definition at line 1147 of file sc_uint_base.hh.
References sc_dt::sc_uint_bitref_r::initialize(), and sc_dt::sc_uint_bitref::m_pool.
operator^=()
sc_uint_base& sc_dt::sc_uint_base::operator^= (uint_type v) inline
Definition at line 692 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator^=().
operator|=()
sc_uint_base& sc_dt::sc_uint_base::operator|= (uint_type v) inline
Definition at line 685 of file sc_uint_base.hh.
References ArmISA::v.
Referenced by sc_dt::sc_uint< W >::operator|=().
or_reduce()
bool sc_dt::sc_uint_base::or_reduce () const
Definition at line 550 of file sc_uint_base.cc.
References m_val.
Referenced by sc_dt::sc_uint_subref_r::or_reduce(), and sc_dt::or_reduce().
print()
void sc_dt::sc_uint_base::print (::std::ostream & os = ::std::cout) const inline
Definition at line 852 of file sc_uint_base.hh.
References MipsISA::is, X86ISA::os, sc_dt::SC_DEC, sc_dt::sc_io_base(), sc_dt::sc_io_show_base(), and sc_dt::to_string().
Referenced by sc_dt::operator<<().
range() [1/2]
sc_uint_subref & sc_dt::sc_uint_base::range (int left, int right) inline
Definition at line 1193 of file sc_uint_base.hh.
References sc_dt::sc_uint_subref_r::initialize(), and sc_dt::sc_uint_subref::m_pool.
range() [2/2]
const sc_uint_subref_r & sc_dt::sc_uint_base::range (int left, int right) const inline
Definition at line 1202 of file sc_uint_base.hh.
References sc_dt::sc_uint_subref_r::initialize(), and sc_dt::sc_uint_subref::m_pool.
scan()
void sc_dt::sc_uint_base::scan (::std::istream & is = ::std::cin)
Definition at line 701 of file sc_uint_base.cc.
References ArmISA::s.
Referenced by sc_dt::operator>>().
set() [1/2]
void sc_dt::sc_uint_base::set (int i) inline
Definition at line 795 of file sc_uint_base.hh.
References ArmISA::i, and sc_dt::UINT_ONE.
set() [2/2]
void sc_dt::sc_uint_base::set (int i, bool v) inline
Definition at line 797 of file sc_uint_base.hh.
References ArmISA::i, and sc_dt::UINT_ONE.
test()
bool sc_dt::sc_uint_base::test (int i) const inline
Definition at line 793 of file sc_uint_base.hh.
References sc_dt::UINT_ONE.
to_double()
double sc_dt::sc_uint_base::to_double () const inline
Definition at line 841 of file sc_uint_base.hh.
References sc_dt::uint64_to_double().
Referenced by sc_dt::sc_uint_subref_r::to_double().
to_int()
int sc_dt::sc_uint_base::to_int () const inline
Definition at line 835 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_int().
to_int64()
int64 sc_dt::sc_uint_base::to_int64 () const inline
Definition at line 839 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_int64().
to_long()
long sc_dt::sc_uint_base::to_long () const inline
Definition at line 837 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_long().
to_string() [1/2]
const std::string sc_dt::sc_uint_base::to_string (sc_numrep numrep = SC_DEC) const
Definition at line 526 of file sc_uint_base.cc.
References PowerISA::aa, ArmISA::len, m_len, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
Referenced by sc_dt::sc_uint_subref_r::to_string(), and sc_dt::sc_int_subref_r::to_string().
to_string() [2/2]
const std::string sc_dt::sc_uint_base::to_string (sc_numrep numrep, bool w_prefix) const
Definition at line 534 of file sc_uint_base.cc.
References PowerISA::aa, ArmISA::len, m_len, sc_dt::SC_ON, sc_dt::SC_TRN, sc_dt::SC_WRAP, and sc_dt::sc_fxnum::to_string().
to_uint()
unsigned int sc_dt::sc_uint_base::to_uint () const inline
Definition at line 836 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_uint().
to_uint64()
uint64 sc_dt::sc_uint_base::to_uint64 () const inline
Definition at line 840 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_uint64().
to_ulong()
unsigned long sc_dt::sc_uint_base::to_ulong () const inline
Definition at line 838 of file sc_uint_base.hh.
Referenced by sc_dt::sc_uint_subref_r::to_ulong().
value()
uint_type sc_dt::sc_uint_base::value () const inline
Definition at line 833 of file sc_uint_base.hh.
xnor_reduce()
bool sc_dt::sc_uint_base::xnor_reduce () const inline
Definition at line 827 of file sc_uint_base.hh.
References sc_dt::xor_reduce().
Referenced by sc_dt::xnor_reduce().
xor_reduce()
bool sc_dt::sc_uint_base::xor_reduce () const
Definition at line 556 of file sc_uint_base.cc.
References m_val, ArmISA::mask, ArmISA::n, SC_INTWIDTH, sc_dt::UINT_ZERO, and X86ISA::val.
Referenced by sc_dt::sc_uint_subref_r::xor_reduce(), and sc_dt::xor_reduce().
Friends And Related Function Documentation
operator!=
bool operator!= (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 753 of file sc_uint_base.hh.
operator<
bool operator< (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 758 of file sc_uint_base.hh.
operator<=
bool operator<= (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 763 of file sc_uint_base.hh.
operator==
bool operator== (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 748 of file sc_uint_base.hh.
operator>
bool operator> (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 768 of file sc_uint_base.hh.
operator>=
bool operator>= (const sc_uint_base & a, const sc_uint_base & b) friend
Definition at line 773 of file sc_uint_base.hh.
sc_uint_bitref
friend class sc_uint_bitref friend
Definition at line 468 of file sc_uint_base.hh.
sc_uint_bitref_r
friend class sc_uint_bitref_r friend
Definition at line 467 of file sc_uint_base.hh.
sc_uint_subref
friend class sc_uint_subref friend
Definition at line 470 of file sc_uint_base.hh.
sc_uint_subref_r
friend class sc_uint_subref_r friend
Definition at line 469 of file sc_uint_base.hh.
Member Data Documentation
m_len
int sc_dt::sc_uint_base::m_len protected
Definition at line 861 of file sc_uint_base.hh.
Referenced by concat_get_ctrl(), concat_get_data(), operator=(), and to_string().
m_ulen
int sc_dt::sc_uint_base::m_ulen protected
Definition at line 862 of file sc_uint_base.hh.
Referenced by and_reduce().
m_val
uint_type sc_dt::sc_uint_base::m_val protected
Definition at line 860 of file sc_uint_base.hh.
Referenced by and_reduce(), concat_get_data(), sc_dt::operator!=(), sc_dt::operator<(), sc_dt::operator<=(), sc_dt::sc_uint< W >::operator=(), operator=(), sc_dt::operator==(), sc_dt::operator>(), sc_dt::operator>=(), or_reduce(), and xor_reduce().
The documentation for this class was generated from the following files:
systemc/ext/dt/int/sc_uint_base.hh
systemc/dt/int/sc_uint_base.cc
systemc/ext/dt/fx/scfx_other_defs.hh