gem5: DMASequencer Class Reference
DMASequencer Class Reference
#include <DMASequencer.hh>
Public Types
typedef DMASequencerParams Params
Public Types inherited from RubyPort
typedef RubyPortParams Params
Public Types inherited from ClockedObject
typedef ClockedObjectParams Params
Parameters of ClockedObject.
Public Types inherited from SimObject
typedef SimObjectParams Params
Public Member Functions
DMASequencer (const Params *)
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
RequestStatus makeRequest (PacketPtr pkt) override
bool busy ()
int outstandingCount () const override
bool isDeadlockEventScheduled () const override
void descheduleDeadlockEvent () override
void dataCallback (const DataBlock &dblk, const Addr &addr)
void ackCallback (const Addr &addr)
void recordRequestType (DMASequencerRequestType requestType)
Public Member Functions inherited from RubyPort
RubyPort (const Params *p)
virtual ~RubyPort ()
void init () override
init() is called after all C++ SimObjects have been created and all ports are connected.
Port & getPort (const std::string &if_name, PortID idx=InvalidPortID) override
Get a port with a given name and index.
void setController (AbstractController *_cntrl)
uint32_t getId ()
DrainState drain () override
Notify an object that it needs to drain its state.
bool isCPUSequencer ()
Public Member Functions inherited from ClockedObject
ClockedObject (const ClockedObjectParams *p)
const Params * params () const
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Enums::PwrState pwrState () const
std::string pwrStateName () const
std::vector< double > pwrStateWeights () const
Returns the percentage residency for each power state.
void computeStats ()
Record stats values like state residency by computing the time difference from previous update.
void pwrState (Enums::PwrState)
Public Member Functions inherited from SimObject
const Params * params () const
SimObject (const Params *_params)
virtual ~SimObject ()
virtual const std::string name () const
virtual void loadState (CheckpointIn &cp)
loadState() is called on each SimObject when restoring from a checkpoint.
virtual void initState ()
initState() is called on each SimObject when not restoring from a checkpoint.
virtual void regProbePoints ()
Register probe points for this object.
virtual void regProbeListeners ()
Register probe listeners for this object.
ProbeManager * getProbeManager ()
Get the probe manager for this object.
virtual void startup ()
startup() is the final initialization call before simulation.
DrainState drain () override
Provide a default implementation of the drain interface for objects that don't need draining.
virtual void memWriteback ()
Write back dirty buffers to memory using functional writes.
virtual void memInvalidate ()
Invalidate the contents of memory buffers.
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from EventManager
EventManager (EventManager &em)
EventManager (EventManager *em)
EventManager (EventQueue *eq)
EventQueue * eventQueue () const
void schedule (Event &event, Tick when)
void deschedule (Event &event)
void reschedule (Event &event, Tick when, bool always=false)
void schedule (Event *event, Tick when)
void deschedule (Event *event)
void reschedule (Event *event, Tick when, bool always=false)
void wakeupEventQueue (Tick when=(Tick) -1)
void setCurTick (Tick newVal)
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Member Functions inherited from Drainable
DrainState drainState () const
Return the current drain state of an object.
virtual void notifyFork ()
Notify a child process of a fork.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void regStats ()
Callback to set stat parameters.
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Member Functions inherited from Clocked
void updateClockPeriod ()
Update the tick to the current tick.
Tick clockEdge (Cycles cycles=Cycles(0)) const
Determine the tick when a cycle begins, by default the current one, but the argument also enables the caller to determine a future cycle.
Cycles curCycle () const
Determine the current cycle, corresponding to a tick aligned to a clock edge.
Tick nextCycle () const
Based on the clock of the object, determine the start tick of the first cycle that is at least one cycle in the future.
uint64_t frequency () const
Tick clockPeriod () const
double voltage () const
Cycles ticksToCycles (Tick t) const
Tick cyclesToTicks (Cycles c) const
Private Types
typedef std::unordered_map< Addr, DMARequest > RequestTable
Private Member Functions
void issueNext (const Addr &addr)
Private Attributes
uint64_t m_data_block_mask
RequestTable m_RequestTable
int m_outstanding_count
int m_max_outstanding_requests
Additional Inherited Members
Static Public Member Functions inherited from SimObject
static void serializeAll (CheckpointOut &cp)
Serialize all SimObjects in the system.
static SimObject * find (const char *name)
Find the SimObject with the given name and return a pointer to it.
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Member Functions inherited from RubyPort
void trySendRetries ()
void ruby_hit_callback (PacketPtr pkt)
void testDrainComplete ()
void ruby_eviction_callback (Addr address)
bool recvTimingResp (PacketPtr pkt, PortID master_port_id)
Called by the PIO port when receiving a timing response.
Protected Member Functions inherited from Drainable
Drainable ()
virtual ~Drainable ()
virtual void drainResume ()
Resume execution after a successful drain.
void signalDrainDone () const
Signal that an object is drained.
Protected Member Functions inherited from Clocked
Clocked (ClockDomain &clk_domain)
Create a clocked object and set the clock domain based on the parameters.
Clocked (Clocked &)=delete
Clocked & operator= (Clocked &)=delete
virtual ~Clocked ()
Virtual destructor due to inheritance.
void resetClock () const
Reset the object's clock using the current global tick value.
virtual void clockPeriodUpdated ()
A hook subclasses can implement so they can do any extra work that's needed when the clock rate is changed.
Protected Attributes inherited from RubyPort
RubySystem * m_ruby_system
uint32_t m_version
AbstractController * m_controller
MessageBuffer * m_mandatory_q_ptr
bool m_usingRubyTester
System * system
std::vector< MemSlavePort * > slave_ports
Protected Attributes inherited from ClockedObject
Enums::PwrState _currPwrState
To keep track of the current power state.
Tick prvEvalTick
ClockedObject::ClockedObjectStats stats
Protected Attributes inherited from SimObject
const SimObjectParams * _params
Cached copy of the object parameters.
Protected Attributes inherited from EventManager
EventQueue * eventq
A pointer to this object's event queue.
Detailed Description
Definition at line 56 of file DMASequencer.hh.
Member Typedef Documentation
Params
typedef DMASequencerParams DMASequencer::Params
Definition at line 59 of file DMASequencer.hh.
RequestTable
typedef std::unordered_map<Addr, DMARequest> DMASequencer::RequestTable private
Definition at line 81 of file DMASequencer.hh.
Constructor & Destructor Documentation
DMASequencer()
DMASequencer::DMASequencer (const Params * p)
Definition at line 48 of file DMASequencer.cc.
Referenced by recordRequestType().
Member Function Documentation
ackCallback()
void DMASequencer::ackCallback (const Addr & addr)
Definition at line 193 of file DMASequencer.cc.
References issueNext(), and m_RequestTable.
busy()
bool DMASequencer::busy () inline
Definition at line 65 of file DMASequencer.hh.
dataCallback()
void DMASequencer::dataCallback (const DataBlock & dblk, const Addr & addr)
Definition at line 173 of file DMASequencer.cc.
References DataBlock::getData(), ArmISA::i, issueNext(), ArmISA::len, m_data_block_mask, m_RequestTable, and ArmISA::offset.
descheduleDeadlockEvent()
void DMASequencer::descheduleDeadlockEvent () inline override virtual
Implements RubyPort.
Definition at line 68 of file DMASequencer.hh.
References addr.
init()
void DMASequencer::init () override virtual
init() is called after all C++ SimObjects have been created and all ports are connected.
Initializations that are independent of unserialization but rely on a fully instantiated and connected SimObject graph should be done here.
Reimplemented from SimObject.
Definition at line 55 of file DMASequencer.cc.
References RubySystem::getBlockSizeBits(), RubyPort::init(), m_data_block_mask, ArmISA::mask, and RubyPort::slave_ports.
isDeadlockEventScheduled()
bool DMASequencer::isDeadlockEventScheduled () const inline override virtual
Implements RubyPort.
Definition at line 67 of file DMASequencer.hh.
issueNext()
void DMASequencer::issueNext (const Addr & addr) private
Definition at line 121 of file DMASequencer.cc.
References Clocked::clockEdge(), Clocked::cyclesToTicks(), DPRINTF, MessageBuffer::enqueue(), RubySystem::getBlockSizeBytes(), ArmISA::i, m_data_block_mask, RubyPort::m_mandatory_q_ptr, m_max_outstanding_requests, m_outstanding_count, m_RequestTable, makeLineAddress(), and RubyPort::ruby_hit_callback().
Referenced by ackCallback(), and dataCallback().
makeRequest()
RequestStatus DMASequencer::makeRequest (PacketPtr pkt) override virtual
Implements RubyPort.
Definition at line 65 of file DMASequencer.cc.
References DMARequest::bytes_issued, Clocked::clockEdge(), Clocked::cyclesToTicks(), data, DMARequest::data, DPRINTF, MessageBuffer::enqueue(), Packet::getAddr(), RubySystem::getBlockSizeBytes(), Packet::getPtr(), Packet::getSize(), Packet::isWrite(), ArmISA::len, m_data_block_mask, RubyPort::m_mandatory_q_ptr, m_max_outstanding_requests, m_outstanding_count, m_RequestTable, makeLineAddress(), and ArmISA::offset.
outstandingCount()
int DMASequencer::outstandingCount () const inline override virtual
Implements RubyPort.
Definition at line 66 of file DMASequencer.hh.
recordRequestType()
void DMASequencer::recordRequestType (DMASequencerRequestType requestType)
Definition at line 200 of file DMASequencer.cc.
References DMASequencer(), and DPRINTF.
Member Data Documentation
m_data_block_mask
uint64_t DMASequencer::m_data_block_mask private
Definition at line 79 of file DMASequencer.hh.
Referenced by dataCallback(), init(), issueNext(), and makeRequest().
m_max_outstanding_requests
int DMASequencer::m_max_outstanding_requests private
Definition at line 85 of file DMASequencer.hh.
Referenced by issueNext(), and makeRequest().
m_outstanding_count
int DMASequencer::m_outstanding_count private
Definition at line 84 of file DMASequencer.hh.
Referenced by issueNext(), and makeRequest().
m_RequestTable
RequestTable DMASequencer::m_RequestTable private
Definition at line 82 of file DMASequencer.hh.
Referenced by ackCallback(), dataCallback(), issueNext(), and makeRequest().
The documentation for this class was generated from the following files:
mem/ruby/system/DMASequencer.hh
mem/ruby/system/DMASequencer.cc