gem5: Arguments Class Reference
Arguments Class Reference
#include <arguments.hh>
Classes
class Data
Public Member Functions
Arguments (ThreadContext *ctx, int n=0)
Arguments (const Arguments &args)
~Arguments ()
ThreadContext * getThreadContext () const
const Arguments & operator= (const Arguments &args)
bool operator! ()
Arguments & operator++ ()
Arguments operator++ (int)
Arguments & operator-- ()
Arguments operator-- (int)
const Arguments & operator+= (int index)
const Arguments & operator-= (int index)
Arguments operator[] (int index)
template<class T >
operator T ()
template<class T >
operator T* ()
operator char * ()
Protected Member Functions
uint64_t getArg (uint16_t size=(uint16_t)(-1), bool fp=false)
Protected Attributes
ThreadContext * tc
int number
std::shared_ptr< Data > data
Detailed Description
Definition at line 40 of file arguments.hh.
Constructor & Destructor Documentation
Arguments() [1/2]
Arguments::Arguments (ThreadContext * ctx, int n = 0) inline
Definition at line 64 of file arguments.hh.
Referenced by operator[]().
Arguments() [2/2]
Arguments::Arguments (const Arguments & args) inline
Definition at line 67 of file arguments.hh.
~Arguments()
Arguments::~Arguments () inline
Definition at line 69 of file arguments.hh.
Member Function Documentation
getArg()
uint64_t Arguments::getArg (uint16_t size = (uint16_t)(-1), bool fp = false) protected
Definition at line 53 of file arguments.cc.
References AlphaISA::getArgument(), number, and tc.
Referenced by operator char *(), operator T(), operator T*(), and operator!().
getThreadContext()
ThreadContext* Arguments::getThreadContext () const inline
Definition at line 71 of file arguments.hh.
References tc.
operator char *()
Arguments::operator char * () inline
Definition at line 143 of file arguments.hh.
References getArg(), ThreadContext::getVirtProxy(), and PortProxy::readString().
operator T()
template<class T > Arguments::operator T () inline
Definition at line 130 of file arguments.hh.
References ArmISA::d, and getArg().
operator T*()
template<class T > Arguments::operator T* () inline
Definition at line 137 of file arguments.hh.
References getArg(), ThreadContext::getVirtProxy(), and PortProxy::readBlob().
operator!()
bool Arguments::operator! () inline
Definition at line 83 of file arguments.hh.
References getArg().
operator++() [1/2]
Arguments& Arguments::operator++ () inline
Definition at line 87 of file arguments.hh.
References number.
operator++() [2/2]
Arguments Arguments::operator++ (int) inline
Definition at line 93 of file arguments.hh.
References number.
operator+=()
const Arguments& Arguments::operator+= (int index) inline
Definition at line 113 of file arguments.hh.
References MipsISA::index.
operator--() [1/2]
Arguments& Arguments::operator-- () inline
Definition at line 100 of file arguments.hh.
References number.
operator--() [2/2]
Arguments Arguments::operator-- (int) inline
Definition at line 106 of file arguments.hh.
References number.
operator-=()
const Arguments& Arguments::operator-= (int index) inline
Definition at line 119 of file arguments.hh.
References MipsISA::index.
operator=()
const Arguments& Arguments::operator= (const Arguments & args) inline
Definition at line 73 of file arguments.hh.
References data, number, and tc.
operator[]()
Arguments Arguments::operator[] (int index) inline
Definition at line 125 of file arguments.hh.
References Arguments().
Member Data Documentation
data
std::shared_ptr<Data> Arguments::data protected
Definition at line 61 of file arguments.hh.
Referenced by operator=().
number
int Arguments::number protected
Definition at line 44 of file arguments.hh.
Referenced by getArg(), operator++(), operator--(), and operator=().
tc
ThreadContext* Arguments::tc protected
Definition at line 43 of file arguments.hh.
Referenced by getArg(), getThreadContext(), and operator=().
The documentation for this class was generated from the following files:
sim/arguments.hh
sim/arguments.cc