gem5: sc_gem5::TraceValBase Class Reference
sc_gem5::TraceValBase Class Reference abstract
#include <tracefile.hh>
Public Member Functions
TraceValBase (int _width)
virtual ~TraceValBase ()
int width ()
virtual void finalize ()
virtual bool check ()=0
Protected Attributes
int _width
Detailed Description
Definition at line 48 of file tracefile.hh.
Constructor & Destructor Documentation
TraceValBase()
sc_gem5::TraceValBase::TraceValBase (int _width) inline
Definition at line 54 of file tracefile.hh.
~TraceValBase()
virtual sc_gem5::TraceValBase::~TraceValBase () inline virtual
Definition at line 55 of file tracefile.hh.
Member Function Documentation
check()
virtual bool sc_gem5::TraceValBase::check () pure virtual
Implemented in sc_gem5::TraceVal< T, VcdTraceValBase >, sc_gem5::TraceVal< ::sc_core::sc_event, VcdTraceValBase >, sc_gem5::TraceVal< ::sc_core::sc_time, VcdTraceValBase >, sc_gem5::TraceVal< sc_dt::sc_logic, VcdTraceValBase >, and sc_gem5::TraceVal< bool, VcdTraceValBase >.
Referenced by finalize().
finalize()
virtual void sc_gem5::TraceValBase::finalize () inline virtual
Reimplemented in sc_gem5::VcdTraceValTime, sc_gem5::VcdTraceValLogic< T >, sc_gem5::VcdTraceValFinite< T >, sc_gem5::TraceVal< T, VcdTraceValBase >, sc_gem5::TraceVal< ::sc_core::sc_event, VcdTraceValBase >, sc_gem5::TraceVal< ::sc_core::sc_time, VcdTraceValBase >, sc_gem5::TraceVal< sc_dt::sc_logic, VcdTraceValBase >, and sc_gem5::TraceVal< bool, VcdTraceValBase >.
Definition at line 59 of file tracefile.hh.
References check().
width()
int sc_gem5::TraceValBase::width () inline
Definition at line 57 of file tracefile.hh.
References _width.
Referenced by sc_gem5::VcdTraceFile::addTraceVal(), sc_gem5::VcdTraceScope::output(), sc_gem5::VcdTraceValFinite< T >::output(), sc_gem5::VcdTraceValFxnum< T >::output(), sc_gem5::VcdTraceValInt< T >::output(), sc_gem5::VcdTraceValBase::printVal(), and sc_gem5::TraceFile::traceDeltas().
Member Data Documentation
_width
int sc_gem5::TraceValBase::_width protected
Definition at line 51 of file tracefile.hh.
Referenced by sc_gem5::TraceValFxnumBase<::sc_dt::sc_fxnum_fast, Base >::finalize(), sc_gem5::VcdTraceValFinite< T >::finalize(), sc_gem5::VcdTraceValLogic< T >::finalize(), sc_gem5::VcdTraceValTime::finalize(), and width().
The documentation for this class was generated from the following file:
systemc/utils/tracefile.hh