gem5: dev/virtio/base.hh File Reference
base.hh File Reference
#include "arch/isa_traits.hh"
#include "base/bitunion.hh"
#include "base/callback.hh"
#include "dev/virtio/virtio_ring.h"
#include "mem/port_proxy.hh"
#include "sim/sim_object.hh"
Classes
class VirtDescriptor
VirtIO descriptor (chain) wrapper.
class VirtQueue
Base wrapper around a virtqueue.
class VirtQueue::VirtRing< T >
VirtIO ring buffer wrapper.
struct VirtQueue::VirtRing< T >::Header
class VirtIODeviceBase
Base class for all VirtIO-based devices.
class VirtIODummyDevice
Functions
VirtIO endian conversion helpers
VirtIO prior to version 1.0 (legacy versions) normally send values to the host in the guest systems native byte order. This is going to change in version 1.0 which mandates little endian. We currently only support the legacy version of VirtIO (the new and shiny standard is still in a draft state and not implemented by the kernel). Once we support the new standard, we should negotiate the VirtIO version with the guest and automatically use the right type of byte swapping.
template<>
vring_used_elem swap_byte (vring_used_elem v)
template<>
vring_desc swap_byte (vring_desc v)
Function Documentation
swap_byte() [1/2]
template<> vring_used_elem swap_byte (vring_used_elem v) inline
Definition at line 70 of file base.hh.
References vring_used_elem::id, vring_used_elem::len, and ArmISA::v.
Referenced by swap_byte(), and TEST().
swap_byte() [2/2]
template<> vring_desc swap_byte (vring_desc v) inline
Definition at line 77 of file base.hh.
References vring_desc::addr, vring_desc::flags, vring_desc::len, vring_desc::next, swap_byte(), and ArmISA::v.