gem5: sim/eventq.hh File Reference
eventq.hh File Reference
#include <algorithm>
#include <cassert>
#include <climits>
#include <functional>
#include <iosfwd>
#include <memory>
#include <mutex>
#include <string>
#include "base/flags.hh"
#include "base/types.hh"
#include "debug/Event.hh"
#include "sim/serialize.hh"
Classes
class EventBase
Common base class for Event and GlobalEvent, so they can share flag and priority definitions and accessor functions.
class Event
class EventQueue
Queue of events sorted in time order.
class EventQueue::ScopedMigration
Temporarily migrate execution to a different event queue.
class EventQueue::ScopedRelease
Temporarily release the event queue service lock.
class EventManager
class EventWrapper< T, F >
class EventFunctionWrapper
Functions
EventQueue * getEventQueue (uint32_t index)
Function for returning eventq queue for the provided index.
EventQueue * curEventQueue ()
void curEventQueue (EventQueue *q)
bool operator< (const Event &l, const Event &r)
bool operator> (const Event &l, const Event &r)
bool operator<= (const Event &l, const Event &r)
bool operator>= (const Event &l, const Event &r)
bool operator== (const Event &l, const Event &r)
bool operator!= (const Event &l, const Event &r)
void dumpMainQueue ()
Variables
Tick simQuantum
Simulation Quantum for multiple eventq simulation.
uint32_t numMainEventQueues
Current number of allocated main event queues.
std::vector< EventQueue * > mainEventQueue
Array for main event queues.
__thread EventQueue * _curEventQueue
The current event queue for the running thread.
bool inParallelMode
Current mode of execution: parallel / serial.
Function Documentation
curEventQueue() [1/2]
EventQueue* curEventQueue () inline
Definition at line 85 of file eventq.hh.
References _curEventQueue.
Referenced by abortHandler(), BaseGlobalEvent::deschedule(), EventQueue::deschedule(), doSimLoop(), BaseGlobalEvent::BarrierEvent::globalBarrier(), EventQueue::handleAsyncInsertions(), StatTest::init(), DistIface::RecvScheduler::init(), BaseKvmCPU::kvmRun(), GlobalSyncEvent::BarrierEvent::process(), DistIface::SyncEvent::process(), DistIface::RecvScheduler::pushPacket(), pybind_init_event(), DistIface::recvThreadFunc(), EventQueue::reschedule(), StatTest::run(), EventQueue::schedule(), EventQueue::ScopedMigration::ScopedMigration(), BaseKvmCPU::tick(), and EventQueue::ScopedMigration::~ScopedMigration().
curEventQueue() [2/2]
void curEventQueue (EventQueue * q) inline
Definition at line 86 of file eventq.hh.
References _curEventQueue, and ArmISA::q.
dumpMainQueue()
void dumpMainQueue ()
Definition at line 369 of file eventq.cc.
References ArmISA::i, and numMainEventQueues.
Referenced by EventQueue::~EventQueue().
getEventQueue()
EventQueue* getEventQueue (uint32_t index)
Function for returning eventq queue for the provided index.
The function allocates a new queue in case one does not exist for the index, provided that the index is with in bounds.
Definition at line 64 of file eventq.cc.
References csprintf(), MipsISA::index, Event::instanceCounter, and numMainEventQueues.
Referenced by dumprstStatsHandler(), dumpStatsHandler(), exitNowHandler(), StatTest::init(), ioHandler(), pybind_init_event(), and PollQueue::setupAsyncIO().
operator!=()
bool operator!= (const Event & l, const Event & r) inline
Definition at line 449 of file eventq.hh.
References Event::priority(), and Event::when().
operator<()
bool operator< (const Event & l, const Event & r) inline
Definition at line 416 of file eventq.hh.
References Event::priority(), and Event::when().
operator<=()
bool operator<= (const Event & l, const Event & r) inline
Definition at line 430 of file eventq.hh.
References Event::priority(), and Event::when().
operator==()
bool operator== (const Event & l, const Event & r) inline
Definition at line 443 of file eventq.hh.
References Event::priority(), and Event::when().
operator>()
bool operator> (const Event & l, const Event & r) inline
Definition at line 423 of file eventq.hh.
References Event::priority(), and Event::when().
operator>=()
bool operator>= (const Event & l, const Event & r) inline
Definition at line 436 of file eventq.hh.
References Event::priority(), and Event::when().
Variable Documentation
_curEventQueue
__thread EventQueue* _curEventQueue
The current event queue for the running thread.
Access to this queue does not require any locking from the thread.
Definition at line 60 of file eventq.cc.
Referenced by curEventQueue(), and curTick().
inParallelMode
bool inParallelMode
Current mode of execution: parallel / serial.
Definition at line 61 of file eventq.cc.
Referenced by EventQueue::deschedule(), EventQueue::reschedule(), EventQueue::schedule(), and simulate().
mainEventQueue
std::vector<EventQueue *> mainEventQueue
Array for main event queues.
Definition at line 59 of file eventq.cc.
Referenced by LdsState::TickEvent::deschedule(), BaseGlobalEvent::deschedule(), Trace::TarmacParserRecord::dump(), eventqDump(), BaseGlobalEvent::reschedule(), BaseGlobalEvent::schedule(), LdsState::TickEvent::schedule(), simulate(), and Serializable::unserializeGlobals().
numMainEventQueues
uint32_t numMainEventQueues
Current number of allocated main event queues.
Definition at line 58 of file eventq.cc.
Referenced by BaseGlobalEventTemplate< GlobalSyncEvent >::BaseGlobalEventTemplate(), BaseGlobalEvent::deschedule(), dumpMainQueue(), eventqDump(), getEventQueue(), BaseGlobalEvent::reschedule(), BaseGlobalEvent::schedule(), BaseGlobalEvent::scheduled(), simulate(), Serializable::unserializeGlobals(), BaseGlobalEvent::when(), and BaseGlobalEvent::~BaseGlobalEvent().
simQuantum
Tick simQuantum
Simulation Quantum for multiple eventq simulation.
The quantum value is the period length after which the queues synchronize themselves with each other. This means that any event to scheduled on Queue A which is generated by an event on Queue B should be at least simQuantum ticks away in future.
Definition at line 50 of file eventq.cc.
Referenced by exitSimLoop(), Root::Root(), Stats::schedStatEvent(), and simulate().