gem5: base/fiber.test.cc File Reference
fiber.test.cc File Reference
#include <gtest/gtest.h>
#include <initializer_list>
#include <iostream>
#include <vector>
#include "base/fiber.hh"
Classes
class SwitchingFiber
class LinkedFiber
Functions
TEST (Fiber, Starting)
This test is checking if the "started" member has its expected value before and after the fiber runs.
SwitchingFiber a ("A", { &b, &a, Fiber::primaryFiber(), &b, &c })
SwitchingFiber b ("B", { &a, &c })
SwitchingFiber c ("C", { &a, Fiber::primaryFiber(), Fiber::primaryFiber() })
TEST (Fiber, Switching)
TEST (Fiber, Linked)
Variables
SwitchingFiber a
SwitchingFiber b
SwitchingFiber c
std::vector< SwitchingFiber * >::iterator expectedIt
std::vector< SwitchingFiber * > expected ({ &a, &b, &a, &a, &a, &b, &c, &a, &c, &c, &c })
int currentIndex = 0
Function Documentation
a()
SwitchingFiber a ("A" , { &b, &a, Fiber::primaryFiber(), &b, &c })
b()
SwitchingFiber b ("B" , { &a, &c })
c()
SwitchingFiber c ("C" , { &a, Fiber::primaryFiber(), Fiber::primaryFiber() })
TEST() [1/3]
TEST (Fiber , Starting)
This test is checking if the "started" member has its expected value before and after the fiber runs.
In the test an empty fiber is used since we are just interested on the _started member and nothing more.
Do nothing
Definition at line 56 of file fiber.test.cc.
References Fiber::Fiber(), Fiber::main(), and Fiber::primaryFiber().
TEST() [2/3]
TEST (Fiber , Switching)
Definition at line 124 of file fiber.test.cc.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, expected, expectedIt, Fiber::finished(), and Fiber::run().
TEST() [3/3]
TEST (Fiber , Linked)
Definition at line 164 of file fiber.test.cc.
References EXPECT_EQ, Fiber::primaryFiber(), and Fiber::run().
Variable Documentation
a
SwitchingFiber a("A", { &b, &a, Fiber::primaryFiber(), &b, &c })
Definition at line 65 of file miscregs_types.hh.
Referenced by AddrRange::addIntlvBits(), ArmISA::Crypto::aesFFMul(), sc_dt::sc_uint_subref_r::and_reduce(), sc_dt::sc_int_subref_r::and_reduce(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), SMMUv3SlaveInterface::atsSlaveRecvAtomic(), TAGE_SC_L_TAGE::calcDep(), MuxingKvmGic::clearBankedDistRange(), MuxingKvmGic::clearDistRange(), sc_dt::sc_bitref< X >::clone(), SMMUTranslationProcess::completePrefetch(), SMMUTranslationProcess::completeTransaction(), IGbE::TxDescCache::completionWriteback(), sc_dt::convert_to_bin(), sc_dt::convert_to_fmt(), MuxingKvmGic::copyBankedDistRange(), MuxingKvmGic::copyDistRange(), SparcISA::TLB::demapPage(), SMMUProcess::doDelay(), SMMUProcess::doRead(), ItsProcess::doRead(), SMMUProcess::doSleep(), SMMUProcess::doWrite(), ItsProcess::doWrite(), RiscvISA::AtomicGenericOp< T >::execute(), ArmISA::AtomicGeneric2Op< T >::execute(), ArmISA::AtomicGeneric3Op< T >::execute(), ArmISA::AtomicGenericPair3Op< T >::execute(), sc_dt::scfx_ieee_double::exponent(), sc_dt::scfx_ieee_float::exponent(), TAGE_SC_L_TAGE::F(), ArmISA::fp16_cvtf(), ArmISA::fp16_process_NaN(), ArmISA::fp32_cvtf(), ArmISA::fp32_process_NaN(), ArmISA::fp64_cvtf(), ArmISA::fp64_process_NaN(), ArmISA::fpMax(), ArmISA::fpMaxNum(), ArmISA::fpMin(), ArmISA::fpMinNum(), MultiperspectivePerceptron::ACYCLIC::getHash(), MultiperspectivePerceptron::MODHIST::getHash(), MultiperspectivePerceptron::MODPATH::getHash(), MultiperspectivePerceptron::GHISTMODPATH::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), AtomicSimpleCPU::getInstPort(), MPP_TAGE::handleAllocAndUReset(), MultiperspectivePerceptron::GHIST::hash(), MultiperspectivePerceptron::MPPBranchInfo::hash1(), System::initState(), QTIsaac< ALPHA >::isaac(), MasterPort::isSnooping(), TimingSimpleCPU::isSquashed(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), sc_dt::lrotate(), SMMUCommandExecProcess::main(), SMMUTranslationProcess::main(), ItsCommand::main(), sc_dt::scfx_ieee_double::mantissa1(), MemoryImage::mask(), SMMUv3::masterRecvReqRetry(), SMMUv3::masterTableWalkRecvReqRetry(), MathExpr::MathExpr(), MemoryImage::offset(), sc_dt::operator&(), sc_dt::operator&=(), SNHash::operator()(), Net::operator<<(), sc_dt::sc_proxy< sc_subref_r< X > >::operator<<(), sc_core::operator<<(), AlphaISA::VAddr::operator=(), PowerISA::VAddr::operator=(), sc_dt::sc_bitref< X >::operator=(), sc_dt::sc_uint_base::operator=(), sc_dt::sc_int_base::operator=(), sc_dt::sc_subref< X >::operator=(), sc_dt::sc_unsigned::operator=(), sc_dt::sc_signed::operator=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator>>(), sc_dt::operator^(), sc_dt::operator^=(), sc_dt::operator|(), sc_dt::operator|=(), sc_dt::sc_proxy< sc_subref_r< X > >::operator~(), sc_dt::sc_uint_subref_r::or_reduce(), sc_dt::sc_int_subref_r::or_reduce(), sc_dt::print_other(), MasterPort::printAddr(), StackDistCalc::printStack(), AnnotateDumpCallback::process(), SMMUv3::processCommands(), QTIsaac< ALPHA >::randinit(), SMMUv3SlaveInterface::recvAtomic(), Gicv3Its::recvReqRetry(), AddrRange::removeIntlvBits(), sc_dt::reverse(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), sc_dt::rrotate(), sc_dt::rshift(), sc_dt::sc_abs(), sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), sc_dt::sc_fxnum_fast_bitref::sc_fxnum_fast_bitref(), sc_dt::sc_int_base::sc_int_base(), sc_dt::sc_int_subref::sc_int_subref(), SC_MODULE(), sc_dt::sc_signed_subref::sc_signed_subref(), sc_dt::sc_uint_base::sc_uint_base(), sc_dt::sc_uint_subref::sc_uint_subref(), sc_dt::sc_unsigned_subref::sc_unsigned_subref(), sc_dt::scfx_is_equal(), sc_dt::scfx_rep::scfx_rep(), tlm::tlm_dmi::set_granted_access(), Trace::InstRecord::setMem(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), swap_byte(), System::System(), ItsProcess::terminate(), TEST(), tlm::tlm_to_hostendian_single(), sc_dt::sc_bit::to_char(), sc_dt::sc_uint_subref_r::to_double(), sc_dt::sc_uint_subref_r::to_int(), sc_dt::sc_uint_subref_r::to_int64(), sc_dt::sc_uint_subref_r::to_long(), sc_dt::sc_uint_subref_r::to_string(), sc_dt::sc_int_subref_r::to_string(), sc_dt::sc_uint_subref_r::to_uint(), sc_dt::sc_uint_subref_r::to_uint64(), sc_dt::sc_uint_subref_r::to_ulong(), sc_dt::uint64_to_double(), MultiperspectivePerceptron::update(), StackDistCalc::verifyStackDist(), SparcISA::TLB::writeSfsr(), sc_dt::sc_uint_subref_r::xor_reduce(), sc_dt::sc_int_subref_r::xor_reduce(), QTIsaac< ALPHA >::randctx::~randctx(), sc_dt::sc_fxnum_fast_subref::~sc_fxnum_fast_subref(), and sc_dt::sc_fxnum_subref::~sc_fxnum_subref().
b
SwitchingFiber b("B", { &a, &c })
Definition at line 355 of file miscregs_types.hh.
Referenced by ArmISA::Crypto::aesFFMul(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::b_and(), sc_dt::b_or(), sc_dt::b_xor(), divCeil(), BaseDynInst< Impl >::effAddrValid(), sc_gem5::Scheduler::elaborationDone(), execveFunc(), sc_gem5::Port::finalize(), findRegDataType(), ArmISA::fp16_scale(), ArmISA::fp32_scale(), ArmISA::fp64_scale(), ArmISA::fpAdd(), ArmISA::fpAddD(), ArmISA::fpAddS(), ArmISA::fpDiv(), ArmISA::fpDivD(), ArmISA::fpDivS(), ArmISA::fpMax(), ArmISA::fpMaxNum(), ArmISA::fpMin(), ArmISA::fpMinNum(), ArmISA::fpMul(), ArmISA::fpMulD(), ArmISA::fpMulS(), ArmISA::fpRecps(), ArmISA::fpRecpsS(), ArmISA::fpRSqrts(), ArmISA::fpRSqrtsS(), ArmISA::fpSub(), ArmISA::fpSubD(), ArmISA::fpSubS(), sc_dt::sc_fxnum_fast::get_slice(), PciDevice::getBAR(), BaseRemoteGDB::getbyte(), MultiperspectivePerceptron::MODHIST::getHash(), MultiperspectivePerceptron::SGHISTPATH::getHash(), Network::getNumNodes(), PerfectSwitch::getOutLinks(), MultiperspectivePerceptron::GHIST::hash(), sc_core::sc_inout< bool >::initialize(), MultiperspectivePerceptron::ThreadData::insertRecency(), QTIsaac< ALPHA >::isaac(), sc_dt::sc_proxy< sc_subref_r< X > >::lrotate(), MathExpr::MathExpr(), MPP_TAGE::MPP_TAGE(), ArmISA::mul64x32(), tlm::tlm_bool< D >::operator bool(), sc_dt::operator<<(), sc_dt::sc_uint_bitref::operator=(), sc_dt::sc_int_bitref::operator=(), Gicv3Its::pageAddress(), tlm::circular_buffer< T >::poke_data(), sc_dt::print_other(), AnnotateDumpCallback::process(), DRAMCtrl::Rank::processRefreshEvent(), QTIsaac< ALPHA >::randinit(), DRAMCtrl::Rank::Rank(), tlm_utils::callback_binder_fw< tlm::tlm_base_protocol_types >::register_port(), QTIsaac< ALPHA >::rngstep(), sc_dt::sc_proxy< sc_subref_r< X > >::rrotate(), sc_dt::rshift(), sc_dt::sc_fxnum_bitref::sc_fxnum_bitref(), sc_dt::sc_int_bitref::sc_int_bitref(), SC_MODULE(), sc_dt::sc_uint_bitref::sc_uint_bitref(), sc_dt::sc_fxnum_bitref::scan(), sc_dt::sc_fxnum_fast_bitref::scan(), sc_dt::sc_bit::scan(), sc_dt::sc_uint_bitref::scan(), sc_dt::sc_int_bitref::scan(), sc_dt::scfx_is_equal(), DRAMCtrl::Rank::scheduleWakeUpEvent(), Network::setFromNetQueue(), Network::setToNetQueue(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), TAGE_SC_L_TAGE::TAGE_SC_L_TAGE(), BitUnionData::templatedFunction(), sc_dt::sc_bit::to_char(), to_number(), sc_dt::sc_bit::to_value(), sc_dt::vec_from_str(), NetworkInterface::wakeup(), MPP_StatisticalCorrector::BranchInfo::~BranchInfo(), TAGEBase::BranchInfo::~BranchInfo(), LTAGE::LTageBranchInfo::~LTageBranchInfo(), QTIsaac< ALPHA >::randctx::~randctx(), and TAGE::TageBranchInfo::~TageBranchInfo().
c
SwitchingFiber c("C", { &a, Fiber::primaryFiber(), Fiber::primaryFiber() })
Definition at line 53 of file miscregs_types.hh.
Referenced by Trace::TarmacParserRecord::advanceTrace(), sc_dt::sc_proxy< sc_subref_r< X > >::assign_(), sc_dt::sc_bv_base::assign_from_string(), sc_dt::sc_lv_base::assign_from_string(), sc_gem5::Scheduler::clear(), SrcClockDomain::clockPeriod(), RiscvISA::PCState::compressed(), sc_gem5::Scheduler::current(), Clocked::cyclesToTicks(), sc_dt::div_scfx_rep(), Trace::Logger::dump(), BaseRemoteGDB::encodeBinaryData(), ArmISA::AtomicGeneric3Op< T >::execute(), ArmISA::AtomicGenericPair3Op< T >::execute(), AddrRangeMap< AbstractMemory *, 1 >::find(), ArmISA::fp64_div(), ArmISA::fp64_sqrt(), FUPool::FUPool(), SystemCounter::getHypControl(), RiscvISA::Interrupts::getInterrupt(), BloomFilter::Bulk::hash(), PS2Device::hostDataAvailable(), PS2Device::hostRegDataAvailable(), CPA::hwWe(), sc_gem5::Kernel::init(), MultiperspectivePerceptron::insert(), PS2Keyboard::keyPress(), sc_dt::lsh_scfx_rep(), PowerISA::IntOp::makeCRField(), PowerISA::FloatOp::makeCRField(), sc_dt::mult_scfx_rep(), sc_dt::neg_scfx_rep(), LinearEquation::operator*=(), sc_dt::sc_fxval::operator++(), sc_dt::sc_fxval_fast::operator++(), sc_dt::sc_fxnum::operator++(), sc_dt::sc_fxnum_fast::operator++(), sc_dt::scfx_string::operator+=(), sc_dt::sc_fxval::operator--(), sc_dt::sc_fxval_fast::operator--(), sc_dt::sc_fxnum::operator--(), sc_dt::sc_fxnum_fast::operator--(), sc_dt::operator<<(), sc_core::sc_out< bool >::operator=(), sc_dt::sc_fix::operator~(), sc_dt::sc_ufix::operator~(), sc_dt::sc_fix_fast::operator~(), sc_dt::sc_ufix_fast::operator~(), sc_dt::overflow(), sc_dt::overflow_scfx_rep(), MathExpr::parse(), SparcISA::SparcStaticInst::passesCondition(), Printk(), AnnotateDumpCallback::process(), HardBreakpoint::process(), tlm::tlm_endian_context_pool::push(), sc_dt::quantization(), sc_dt::quantization_scfx_rep(), QTIsaac< ALPHA >::randinit(), Terminal::readData(), ArmSemihosting::readString(), BaseRemoteGDB::recv(), SerialDevice::regInterfaceCallback(), VirtIODeviceBase::registerKickCallback(), ClockDomain::registerWithClockDomain(), sc_gem5::Kernel::regStats(), sc_dt::rsh_scfx_rep(), sc_dt::sc_abs(), SC_MODULE(), sc_dt::sc_logic::scan(), sc_dt::sc_bitref< X >::scan(), BaseRemoteGDB::send(), IdeDisk::setController(), Message::setMsgCounter(), QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), sc_gem5::Kernel::startup(), sc_gem5::Kernel::stopWork(), Trace::TarmacBaseRecord::TarmacBaseRecord(), TEST(), ArmISA::testPredicate(), to_lower(), to_number(), PortProxy::tryReadString(), PS2Device::unserialize(), DerivedClockDomain::updateClockPeriod(), MultiperspectivePerceptronTAGE::updatePartial(), Stats::validateStatName(), sc_dt::vec_from_str(), Terminal::write(), Terminal::writeData(), and QTIsaac< ALPHA >::randctx::~randctx().
currentIndex
int currentIndex = 0
Definition at line 148 of file fiber.test.cc.
expected
std::vector<SwitchingFiber *> expected({ &a, &b, &a, &a, &a, &b, &c, &a, &c, &c, &c })
Referenced by SwitchingFiber::checkExpected(), and TEST().
expectedIt
std::vector<SwitchingFiber *>::iterator expectedIt
Definition at line 94 of file fiber.test.cc.
Referenced by TEST().