gem5: dev/virtio/fs9p.hh File Reference
fs9p.hh File Reference
#include <map>
#include <memory>
#include <string>
#include "base/pollevent.hh"
#include "dev/virtio/base.hh"
Classes
struct P9MsgHeader
class VirtIO9PBase
This class implements a VirtIO transport layer for the 9p network file system.
struct VirtIO9PBase::Config
VirtIO 9p configuration structure.
class VirtIO9PBase::FSQueue
Virtqueue for 9p requests.
class VirtIO9PProxy
VirtIO 9p proxy base class.
class VirtIO9PDiod
VirtIO 9p proxy that communicates with the diod 9p server using pipes.
class VirtIO9PDiod::DiodDataEvent
class VirtIO9PSocket
VirtIO 9p proxy that communicates with a 9p server over tcp sockets.
class VirtIO9PSocket::SocketDataEvent
Typedefs
typedef uint8_t P9MsgType
typedef uint16_t P9Tag
Functions
template<typename T >
T p9toh (T v)
Convert p9 byte order (LE) to host byte order.
template<typename T >
T htop9 (T v)
Convert host byte order to p9 byte order (LE)
template<>
P9MsgHeader p9toh (P9MsgHeader v)
template<>
P9MsgHeader htop9 (P9MsgHeader v)
Variables
struct P9MsgHeader M5_ATTR_PACKED
Typedef Documentation
P9MsgType
typedef uint8_t P9MsgType
Definition at line 50 of file fs9p.hh.
P9Tag
typedef uint16_t P9Tag
Definition at line 53 of file fs9p.hh.
Function Documentation
htop9() [1/2]
template<typename T > T htop9 (T v) inline
Convert host byte order to p9 byte order (LE)
Definition at line 70 of file fs9p.hh.
References htole().
Referenced by htop9(), VirtIO9PProxy::recvTMsg(), and VirtIO9PBase::sendRMsg().
htop9() [2/2]
template<> P9MsgHeader htop9 (P9MsgHeader v) inline
Definition at line 82 of file fs9p.hh.
References htop9(), P9MsgHeader::len, P9MsgHeader::tag, P9MsgHeader::type, and ArmISA::v.
p9toh() [1/2]
template<typename T > T p9toh (T v) inline
Convert p9 byte order (LE) to host byte order.
Definition at line 66 of file fs9p.hh.
References letoh().
Referenced by VirtIO9PBase::FSQueue::onNotifyDescriptor(), p9toh(), and VirtIO9PProxy::serverDataReady().
p9toh() [2/2]
template<> P9MsgHeader p9toh (P9MsgHeader v) inline
Definition at line 73 of file fs9p.hh.
References P9MsgHeader::len, p9toh(), P9MsgHeader::tag, P9MsgHeader::type, and ArmISA::v.
Variable Documentation
M5_ATTR_PACKED
struct P9MsgHeader M5_ATTR_PACKED