gem5: systemc/tests/systemc/misc/synth/add_chain_FUNC/add_chain.h File Reference
add_chain.h File Reference
Macros
#define LIMIT 257
#define WIDTH 8
#define LATENCY 3
Functions
void f_RESET_STIM (const char *, sc_clock &, sc_signal< bool > &, sc_signal< bool > &, sc_signal< int > &)
void f_DATA_GEN (const char *, sc_clock &, const sc_signal< bool > &, signal_bool_vector8 &, sc_signal< int > &)
void f_add_chain (const char *, sc_clock &, const sc_signal< bool > &, const signal_bool_vector8 &, signal_bool_vector4 &, sc_signal< bool > &)
void f_DISPLAY (const char *, const sc_signal< bool > &, const signal_bool_vector8 &, const signal_bool_vector4 &)
Variables
bool_vector8 mem []
Macro Definition Documentation
LATENCY
#define LATENCY 3
Definition at line 40 of file add_chain.h.
LIMIT
#define LIMIT 257
Definition at line 38 of file add_chain.h.
WIDTH
#define WIDTH 8
Definition at line 39 of file add_chain.h.
Function Documentation
f_add_chain()
void f_add_chain (const char * , sc_clock & , const sc_signal< bool > & , const signal_bool_vector8 & , signal_bool_vector4 & , sc_signal< bool > &)
Referenced by testbench::testbench().
f_DATA_GEN()
void f_DATA_GEN (const char * , sc_clock & , const sc_signal< bool > & , signal_bool_vector8 & , sc_signal< int > &)
Referenced by testbench::testbench().
f_DISPLAY()
void f_DISPLAY (const char * , const sc_signal< bool > & , const signal_bool_vector8 & , const signal_bool_vector4 &)
Referenced by testbench::testbench().
f_RESET_STIM()
void f_RESET_STIM (const char * , sc_clock & , sc_signal< bool > & , sc_signal< bool > & , sc_signal< int > &)
Referenced by testbench::testbench().
Variable Documentation
mem
bool_vector8 mem[]
Definition at line 43 of file reset_stim.h.
Referenced by SC_MODULE().