gem5: mem/ruby/system/GPUCoalescer.hh File Reference
GPUCoalescer.hh File Reference
#include <iostream>
#include <unordered_map>
#include "base/statistics.hh"
#include "mem/request.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Consumer.hh"
#include "mem/ruby/protocol/HSAScope.hh"
#include "mem/ruby/protocol/HSASegment.hh"
#include "mem/ruby/protocol/PrefetchBit.hh"
#include "mem/ruby/protocol/RubyAccessMode.hh"
#include "mem/ruby/protocol/RubyRequestType.hh"
#include "mem/ruby/protocol/SequencerRequestType.hh"
#include "mem/ruby/system/Sequencer.hh"
Classes
struct GPUCoalescerRequest
class RequestDesc
class GPUCoalescer
Functions
HSAScope reqScopeToHSAScope (const RequestPtr &req)
HSASegment reqSegmentToHSASegment (const RequestPtr &req)
std::ostream & operator<< (std::ostream &out, const GPUCoalescerRequest &obj)
std::ostream & operator<< (std::ostream &out, const GPUCoalescer &obj)
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & out, const GPUCoalescerRequest & obj)
operator<<() [2/2]
std::ostream& operator<< (std::ostream & out, const GPUCoalescer & obj) inline
Definition at line 347 of file GPUCoalescer.hh.
References GPUCoalescer::print().
reqScopeToHSAScope()
HSAScope reqScopeToHSAScope (const RequestPtr & req)
Definition at line 73 of file GPUCoalescer.cc.
References fatal.
Referenced by GPUCoalescer::issueRequest().
reqSegmentToHSASegment()
HSASegment reqSegmentToHSASegment (const RequestPtr & req)
Definition at line 93 of file GPUCoalescer.cc.
References fatal.
Referenced by GPUCoalescer::issueRequest().