gem5: KVM Interrupt handling.
KVM Interrupt handling.
These methods control interrupt delivery to the guest system.
Functions
void BaseKvmCPU::kvmNonMaskableInterrupt ()
Send a non-maskable interrupt to the guest.
void BaseKvmCPU::kvmInterrupt (const struct kvm_interrupt &interrupt)
Send a normal interrupt to the guest.
void KvmVM::createIRQChip ()
Create an in-kernel interrupt controller.
void KvmVM::setIRQLine (uint32_t irq, bool high)
Set the status of an IRQ line using KVM_IRQ_LINE.
bool KvmVM::hasKernelIRQChip () const
Is in-kernel IRQ chip emulation enabled?
void KvmVM::enableKernelIRQChip ()
Tell the VM and VCPUs to use an in-kernel IRQ chip for interrupt delivery.
Detailed Description
These methods control interrupt delivery to the guest system.
Function Documentation
createIRQChip()
void KvmVM::createIRQChip ()
Create an in-kernel interrupt controller.
Note
This functionality depends on Kvm::capIRQChip().
Definition at line 487 of file vm.cc.
References KvmVM::_hasKernelIRQChip, KvmVM::ioctl(), panic, and warn.
enableKernelIRQChip()
void KvmVM::enableKernelIRQChip () inline
Tell the VM and VCPUs to use an in-kernel IRQ chip for interrupt delivery.
Note
This is set automatically if the IRQ chip is created using the KvmVM::createIRQChip() API.
Definition at line 362 of file vm.hh.
Referenced by KvmKernelGicV2::KvmKernelGicV2().
hasKernelIRQChip()
bool KvmVM::hasKernelIRQChip () const inline
Is in-kernel IRQ chip emulation enabled?
Definition at line 353 of file vm.hh.
Referenced by BaseArmKvmCPU::kvmRun().
kvmInterrupt()
void BaseKvmCPU::kvmInterrupt (const struct kvm_interrupt & interrupt) protected
Send a normal interrupt to the guest.
Note
Make sure that ready_for_interrupt_injection in kvm_run is set prior to calling this function. If not, an interrupt window must be requested by setting request_interrupt_window in kvm_run to 1 and restarting the guest.
Parameters
interrupt Structure describing the interrupt to send
Definition at line 834 of file base.cc.
References BaseKvmCPU::ioctl(), BaseKvmCPU::numInterrupts, and panic.
Referenced by X86KvmCPU::deliverInterrupts(), and BaseKvmCPU::getGuestData().
kvmNonMaskableInterrupt()
void BaseKvmCPU::kvmNonMaskableInterrupt () protected
Send a non-maskable interrupt to the guest.
Note
The presence of this call depends on Kvm::capUserNMI().
Definition at line 826 of file base.cc.
References BaseKvmCPU::ioctl(), BaseKvmCPU::numInterrupts, and panic.
Referenced by X86KvmCPU::deliverInterrupts(), and BaseKvmCPU::getGuestData().
setIRQLine()
void KvmVM::setIRQLine (uint32_t irq, bool high)
Set the status of an IRQ line using KVM_IRQ_LINE.
Note
This ioctl is usually only used if the interrupt controller is emulated by the kernel (i.e., after calling createIRQChip()). Some architectures (e.g., ARM) use it instead of BaseKvmCPU::kvmInterrupt().
Parameters
irq Interrupt number
high Line level (true for high, false for low)
Definition at line 502 of file vm.cc.
References KvmVM::ioctl(), ArmISA::irq, and panic.
Referenced by BaseArmKvmCPU::kvmRun(), ArmKvmCPU::kvmRun(), and KvmKernelGicV2::setIntState().