gem5: KVM low-level ioctl interface.
KVM low-level ioctl interface.
These methods provide a low-level interface to the underlying KVM layer.
Functions
int BaseKvmCPU::ioctl (int request, long p1) const
vCPU ioctl interface.
int BaseKvmCPU::ioctl (int request, void *p1) const
int BaseKvmCPU::ioctl (int request) const
int Kvm::ioctl (int request, long p1) const
Main VM ioctl interface.
int Kvm::ioctl (int request, void *p1) const
int Kvm::ioctl (int request) const
int KvmVM::ioctl (int request, long p1) const
KVM VM ioctl interface.
int KvmVM::ioctl (int request, void *p1) const
int KvmVM::ioctl (int request) const
Detailed Description
These methods provide a low-level interface to the underlying KVM layer.
Function Documentation
ioctl() [1/9]
int Kvm::ioctl (int request, long p1) const protected
Main VM ioctl interface.
Parameters
request KVM request
p1 Optional request parameter
Returns
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 274 of file vm.cc.
References Kvm::kvmFD.
Referenced by Kvm::capXSave(), Kvm::checkExtension(), Kvm::createVM(), Kvm::getVCPUMMapSize(), Kvm::ioctl(), KvmVM::ioctl(), and Kvm::Kvm().
ioctl() [2/9]
int Kvm::ioctl (int request, void * p1) const inline protected
Definition at line 230 of file vm.hh.
References Kvm::ioctl().
ioctl() [3/9]
int Kvm::ioctl (int request) const inline protected
Definition at line 233 of file vm.hh.
References Kvm::createVM(), Kvm::ioctl(), Kvm::Kvm(), KvmVM::kvm, X86ISA::L, and Kvm::operator=().
ioctl() [4/9]
int KvmVM::ioctl (int request, long p1) const protected
KVM VM ioctl interface.
Parameters
request KVM VM request
p1 Optional request parameter
Returns
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 577 of file vm.cc.
References KvmVM::KvmVM(), KvmVM::vmFD, and warn_once.
Referenced by KvmVM::allocVCPUID(), KvmVM::coalesceMMIO(), KvmVM::createDevice(), KvmVM::createIRQChip(), KvmVM::createVCPU(), KvmVM::setIRQLine(), KvmVM::setTSSAddress(), and KvmVM::setUserMemoryRegion().
ioctl() [5/9]
int KvmVM::ioctl (int request, void * p1) const inline protected
Definition at line 512 of file vm.hh.
References Kvm::ioctl().
ioctl() [6/9]
int KvmVM::ioctl (int request) const inline protected
Definition at line 515 of file vm.hh.
References Kvm::ioctl(), Kvm::KvmVM, X86ISA::L, Kvm::operator=(), and ArmISA::vm.
ioctl() [7/9]
int BaseKvmCPU::ioctl (int request, long p1) const protected
vCPU ioctl interface.
Parameters
request KVM vCPU request
p1 Optional request parameter
Returns
-1 on error (error number in errno), ioctl dependent value otherwise.
Definition at line 1178 of file base.cc.
References panic, and BaseKvmCPU::vcpuFD.
Referenced by BaseKvmCPU::archIsDrained(), X86KvmCPU::getDebugRegisters(), BaseKvmCPU::getFPUState(), X86KvmCPU::getMSRs(), BaseKvmCPU::getOneReg(), BaseKvmCPU::getRegisters(), BaseArmKvmCPU::getRegList(), ArmKvmCPU::getRegList(), BaseKvmCPU::getSpecialRegisters(), X86KvmCPU::getVCpuEvents(), X86KvmCPU::getXCRs(), X86KvmCPU::getXSave(), BaseKvmCPU::ioctl(), BaseKvmCPU::ioctlRun(), BaseArmKvmCPU::kvmArmVCpuInit(), ArmKvmCPU::kvmArmVCpuInit(), BaseKvmCPU::kvmInterrupt(), BaseKvmCPU::kvmNonMaskableInterrupt(), X86KvmCPU::setCPUID(), X86KvmCPU::setDebugRegisters(), BaseKvmCPU::setFPUState(), X86KvmCPU::setMSRs(), BaseKvmCPU::setOneReg(), BaseKvmCPU::setRegisters(), BaseKvmCPU::setSignalMask(), BaseKvmCPU::setSpecialRegisters(), X86KvmCPU::setVCpuEvents(), X86KvmCPU::setXCRs(), and X86KvmCPU::setXSave().
ioctl() [8/9]
int BaseKvmCPU::ioctl (int request, void * p1) const inline protected
Definition at line 567 of file base.hh.
References BaseKvmCPU::ioctl().
ioctl() [9/9]
int BaseKvmCPU::ioctl (int request) const inline protected
Definition at line 570 of file base.hh.
References BaseKvmCPU::ioctl(), and X86ISA::L.