gem5: kern/linux/helpers.cc File Reference
helpers.cc File Reference
#include "kern/linux/helpers.hh"
#include "arch/isa_traits.hh"
#include "config/the_isa.hh"
#include "cpu/thread_context.hh"
#include "mem/fs_translating_port_proxy.hh"
#include "sim/byteswap.hh"
#include "sim/system.hh"
Classes
struct DmesgEntry
Functions
static int dumpDmesgEntry (const uint8_t *base, const uint8_t *end, const ByteOrder bo, std::ostream &os)
Variables
struct DmesgEntry M5_ATTR_PACKED
Function Documentation
dumpDmesgEntry()
static int dumpDmesgEntry (const uint8_t * base, const uint8_t * end, const ByteOrder bo, std::ostream & os) static
Definition at line 59 of file helpers.cc.
References X86ISA::base, PowerISA::bo, ccprintf(), X86ISA::de, Linux::dumpDmesg(), ArmISA::e, SymbolTable::findAddress(), System::getGuestByteOrder(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), gtoh(), AlphaISA::GuestByteOrder, System::kernelSymtab, DmesgEntry::len, length, X86ISA::os, PortProxy::read(), PortProxy::readBlob(), X86ISA::system, DmesgEntry::text_len, DmesgEntry::ts_nsec, and warn.
Variable Documentation
M5_ATTR_PACKED
struct DmesgEntry M5_ATTR_PACKED