gem5: sim/init.hh File Reference
init.hh File Reference
#include "pybind11/pybind11.h"
#include <list>
#include <map>
#include <string>
#include <inttypes.h>
Classes
struct EmbeddedPython
class EmbeddedPyBind
Typedefs
typedef _object PyObject
Functions
void registerNativeModules ()
int m5Main (int argc, char **argv)
Typedef Documentation
PyObject
typedef _object PyObject
Definition at line 55 of file init.hh.
Function Documentation
m5Main()
int m5Main (int argc, char ** argv)
Definition at line 261 of file init.cc.
References ArmISA::i, m5MainCommands, panic, and PyCC.
Referenced by main().
registerNativeModules()
void registerNativeModules ()
Definition at line 239 of file init.cc.
References __attribute__(), EmbeddedPyBind::initAll(), m5MainCommands, and panic.
Referenced by main().