gem5: sim/init_signals.cc File Reference
init_signals.cc File Reference
#include "sim/init_signals.hh"
#include <sys/types.h>
#include <unistd.h>
#include <csignal>
#include <iostream>
#include <string>
#include "base/atomicio.hh"
#include "base/cprintf.hh"
#include "base/logging.hh"
#include "sim/async.hh"
#include "sim/backtrace.hh"
#include "sim/core.hh"
#include "sim/eventq.hh"
Functions
static bool setupAltStack ()
static void installSignalHandler (int signal, void(*handler)(int sigtype), int flags=SA_RESTART)
static void raiseFatalSignal (int signo)
void dumpStatsHandler (int sigtype)
Stats signal handler.
void dumprstStatsHandler (int sigtype)
void exitNowHandler (int sigtype)
Exit signal handler.
void abortHandler (int sigtype)
Abort signal handler.
static void segvHandler (int sigtype)
Segmentation fault signal handler.
static void ioHandler (int sigtype)
void initSignals ()
Variables
static uint8_t fatalSigStack [2 *SIGSTKSZ]
Function Documentation
abortHandler()
void abortHandler (int sigtype)
Abort signal handler.
Definition at line 147 of file init_signals.cc.
References ccprintf(), curEventQueue(), PowerISA::eq, EventQueue::getCurTick(), print_backtrace(), raiseFatalSignal(), and STATIC_ERR.
Referenced by initSignals().
dumprstStatsHandler()
void dumprstStatsHandler (int sigtype)
Definition at line 126 of file init_signals.cc.
References async_event, async_statdump, async_statreset, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
dumpStatsHandler()
void dumpStatsHandler (int sigtype)
Stats signal handler.
Definition at line 117 of file init_signals.cc.
References async_event, async_statdump, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
exitNowHandler()
void exitNowHandler (int sigtype)
Exit signal handler.
Definition at line 137 of file init_signals.cc.
References async_event, async_exit, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
initSignals()
void initSignals ()
Definition at line 185 of file init_signals.cc.
References abortHandler(), dumprstStatsHandler(), dumpStatsHandler(), exitNowHandler(), installSignalHandler(), ioHandler(), segvHandler(), setupAltStack(), and warn.
Referenced by main().
installSignalHandler()
static void installSignalHandler (int signal, void(*)(int sigtype) handler, int flags = SA_RESTART) static
Definition at line 87 of file init_signals.cc.
References panic.
Referenced by initSignals().
ioHandler()
static void ioHandler (int sigtype) static
Definition at line 172 of file init_signals.cc.
References async_event, async_io, getEventQueue(), and EventQueue::wakeup().
Referenced by initSignals().
raiseFatalSignal()
static void raiseFatalSignal (int signo) static
Definition at line 102 of file init_signals.cc.
References STATIC_ERR.
Referenced by abortHandler(), and segvHandler().
segvHandler()
static void segvHandler (int sigtype) static
Segmentation fault signal handler.
Definition at line 162 of file init_signals.cc.
References print_backtrace(), raiseFatalSignal(), and STATIC_ERR.
Referenced by initSignals().
setupAltStack()
static bool setupAltStack () static
Definition at line 72 of file init_signals.cc.
References fatalSigStack, and X86ISA::stack.
Referenced by initSignals().
Variable Documentation
fatalSigStack
uint8_t fatalSigStack[2 *SIGSTKSZ] static
Definition at line 69 of file init_signals.cc.
Referenced by setupAltStack().