gem5: arch/x86/bios/intelmp.hh File Reference
intelmp.hh File Reference
#include <string>
#include <vector>
#include "base/bitfield.hh"
#include "enums/X86IntelMPAddressType.hh"
#include "enums/X86IntelMPInterruptType.hh"
#include "enums/X86IntelMPPolarity.hh"
#include "enums/X86IntelMPRangeList.hh"
#include "enums/X86IntelMPTriggerMode.hh"
#include "sim/sim_object.hh"
Classes
class X86ISA::IntelMP::FloatingPointer
class X86ISA::IntelMP::BaseConfigEntry
class X86ISA::IntelMP::ExtConfigEntry
class X86ISA::IntelMP::ConfigTable
class X86ISA::IntelMP::Processor
class X86ISA::IntelMP::Bus
class X86ISA::IntelMP::IOAPIC
class X86ISA::IntelMP::IntAssignment
class X86ISA::IntelMP::IOIntAssignment
class X86ISA::IntelMP::LocalIntAssignment
class X86ISA::IntelMP::AddrSpaceMapping
class X86ISA::IntelMP::BusHierarchy
class X86ISA::IntelMP::CompatAddrSpaceMod
Namespaces
X86ISA
This is exposed globally, independent of the ISA.
X86ISA::IntelMP
Functions
template<class T >
uint8_t writeOutField (PortProxy &proxy, Addr addr, T val)
uint8_t writeOutString (PortProxy &proxy, Addr addr, std::string str, int length)
Function Documentation
writeOutField()
template<class T > uint8_t writeOutField (PortProxy & proxy, Addr addr, T val)
Definition at line 74 of file intelmp.cc.
References htole(), and PortProxy::writeBlob().
Referenced by X86ISA::IntelMP::FloatingPointer::writeOut(), X86ISA::IntelMP::ConfigTable::writeOut(), X86ISA::IntelMP::Processor::writeOut(), X86ISA::IntelMP::Bus::writeOut(), X86ISA::IntelMP::IOAPIC::writeOut(), X86ISA::IntelMP::IntAssignment::writeOut(), X86ISA::IntelMP::AddrSpaceMapping::writeOut(), X86ISA::IntelMP::BusHierarchy::writeOut(), and X86ISA::IntelMP::CompatAddrSpaceMod::writeOut().
writeOutString()
uint8_t writeOutString (PortProxy & proxy, Addr addr, std::string str, int length)