gem5: base/intmath.test.cc File Reference
intmath.test.cc File Reference
#include <gtest/gtest.h>
#include "base/intmath.hh"
Functions
TEST (IntmathTest, isPowerOf2)
TEST (IntmathTest, power)
TEST (IntmathTest, floorLog2)
TEST (IntmathTest, ceilLog2)
TEST (IntmathTest, divCeil)
TEST (IntmathTest, roundUp)
TEST (IntmathTest, roundDown)
Function Documentation
TEST() [1/7]
TEST (IntmathTest , isPowerOf2)
Definition at line 36 of file intmath.test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and isPowerOf2().
TEST() [2/7]
TEST (IntmathTest , power)
Definition at line 47 of file intmath.test.cc.
References EXPECT_EQ, and power().
TEST() [3/7]
TEST (IntmathTest , floorLog2)
Definition at line 54 of file intmath.test.cc.
References EXPECT_EQ, and floorLog2().
TEST() [4/7]
TEST (IntmathTest , ceilLog2)
Definition at line 66 of file intmath.test.cc.
References ceilLog2(), and EXPECT_EQ.
TEST() [5/7]
TEST (IntmathTest , divCeil)
Definition at line 79 of file intmath.test.cc.
References divCeil(), and EXPECT_EQ.
TEST() [6/7]
TEST (IntmathTest , roundUp)
Definition at line 88 of file intmath.test.cc.
References EXPECT_EQ, and roundUp().
TEST() [7/7]
TEST (IntmathTest , roundDown)
Definition at line 96 of file intmath.test.cc.
References EXPECT_EQ, and roundDown().