gem5: mem/ruby/common/MachineID.hh File Reference
MachineID.hh File Reference
#include <iostream>
#include <string>
#include "base/cprintf.hh"
#include "mem/ruby/protocol/MachineType.hh"
Classes
struct MachineID
Functions
std::string MachineIDToString (MachineID machine)
bool operator== (const MachineID &obj1, const MachineID &obj2)
bool operator!= (const MachineID &obj1, const MachineID &obj2)
std::ostream & operator<< (std::ostream &out, const MachineID &obj)
Function Documentation
MachineIDToString()
std::string MachineIDToString (MachineID machine) inline
Definition at line 53 of file MachineID.hh.
References csprintf(), MachineID::num, and MachineID::type.
operator!=()
bool operator!= (const MachineID & obj1, const MachineID & obj2) inline
Definition at line 65 of file MachineID.hh.
References MachineID::num, operator<<(), and MachineID::type.
operator<<()
std::ostream & operator<< (std::ostream & out, const MachineID & obj) inline
Definition at line 74 of file MachineID.hh.
References MachineID::num, and MachineID::type.
Referenced by operator!=().
operator==()
bool operator== (const MachineID & obj1, const MachineID & obj2) inline
Definition at line 59 of file MachineID.hh.
References MachineID::num, and MachineID::type.