gem5: mem/ruby/slicc_interface/Message.hh File Reference
Message.hh File Reference
#include <iostream>
#include <memory>
#include <stack>
#include "mem/packet.hh"
#include "mem/ruby/common/NetDest.hh"
#include "mem/ruby/protocol/MessageSizeType.hh"
Classes
class Message
Typedefs
typedef std::shared_ptr< Message > MsgPtr
Functions
bool operator> (const MsgPtr &lhs, const MsgPtr &rhs)
std::ostream & operator<< (std::ostream &out, const Message &obj)
Typedef Documentation
MsgPtr
typedef std::shared_ptr<Message> MsgPtr
Definition at line 40 of file Message.hh.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & out, const Message & obj) inline
Definition at line 130 of file Message.hh.
References Message::print().
operator>()
bool operator> (const MsgPtr & lhs, const MsgPtr & rhs) inline
Definition at line 118 of file Message.hh.
References Message::getLastEnqueueTime(), Message::getMsgCounter(), MipsISA::l, and MipsISA::r.