gem5: sc_gem5 Namespace Reference
sc_gem5 Namespace Reference
Classes
struct BuiltinExceptionWrapper
class Channel
class ClockTick
class CThread
struct DefaultReportMessages
class DynamicSensitivity
class DynamicSensitivityEvent
class DynamicSensitivityEventAndList
class DynamicSensitivityEventOrList
struct enable_if
struct enable_if< true, T >
class Event
struct ExceptionWrapper
struct ExceptionWrapperBase
class Gem5ToTlmBridge
class Gem5ToTlmBridgeBase
class InternalScEvent
struct is_const
struct is_const< const T >
struct is_more_const
struct is_same
struct is_same< T, T >
class Kernel
struct ListNode
class Method
class Module
struct NodeList
class Object
class Port
class Process
struct ProcessFuncWrapper
struct ProcessMemberFuncWrapper
struct ProcessObjFuncWrapper
struct ProcessObjRetFuncWrapper
struct PythonInitFunc
struct PythonReadyFunc
struct remove_const
struct remove_const< const T >
struct remove_special_fptr
struct remove_special_fptr< special_result &(*)(T)>
struct ReportMsgInfo
struct ReportSevInfo
class Reset
class ScEvent
class ScExportWrapper
class ScHalt
class Scheduler
class ScInterfaceWrapper
class ScMainFiber
class ScPortWrapper
class ScSignalBase
class ScSignalBaseBinary
class ScSignalBasePicker
class ScSignalBasePicker< bool >
class ScSignalBasePicker< sc_dt::sc_logic >
class ScSignalBaseT
class ScSignalBinary
class Sensitivity
class SensitivityEvent
class SensitivityEvents
struct special_result
class StaticSensitivity
class StaticSensitivityEvent
class StaticSensitivityExport
class StaticSensitivityFinder
class StaticSensitivityInterface
class StaticSensitivityPort
class Thread
class TlmInitiatorBaseWrapper
class TlmTargetBaseWrapper
class TlmToGem5Bridge
class TlmToGem5BridgeBase
class TraceFile
class TraceVal
class TraceVal<::sc_core::sc_event, Base >
class TraceVal<::sc_core::sc_signal_in_if< T >, Base >
class TraceVal<::sc_dt::sc_fxnum, Base >
class TraceVal<::sc_dt::sc_fxnum_fast, Base >
class TraceValBase
class TraceValFxnumBase
class UniqueNameGen
class UnwindExceptionKill
class UnwindExceptionReset
class VcdTraceFile
class VcdTraceScope
class VcdTraceVal
class VcdTraceValBase
class VcdTraceValBool
class VcdTraceValEvent
class VcdTraceValFinite
class VcdTraceValFloat
class VcdTraceValFxnum
class VcdTraceValFxval
class VcdTraceValInt
class VcdTraceValLogic
class VcdTraceValScLogic
class VcdTraceValTime
class WriteChecker
class WriteChecker< sc_core::SC_MANY_WRITERS >
class WriteChecker< sc_core::SC_ONE_WRITER >
Typedefs
typedef std::vector< sc_core::sc_event * > Events
typedef std::vector< sc_core::sc_object * > Objects
typedef Objects::iterator ObjectsIt
typedef Events::iterator EventsIt
typedef std::list< ScEvent * > ScEvents
typedef NodeList< Process > ProcessList
typedef NodeList< Channel > ChannelList
typedef std::vector< DynamicSensitivity * > DynamicSensitivities
typedef std::vector< StaticSensitivity * > StaticSensitivities
template<unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
using TlmInitiatorWrapper = TlmInitiatorBaseWrapper< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, N, POL >
template<unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
using TlmTargetWrapper = TlmTargetBaseWrapper< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, N, POL >
Functions
EventsIt findEvent (const std::string &name)
Module * currentModule ()
Module * newModuleChecked ()
Module * newModule ()
static Module * pickParentModule ()
static void pushParentModule (Module *m)
static void popParentModule ()
std::string pickUniqueName (::sc_core::sc_object *parent, std::string base)
const std::vector< sc_core::sc_object * > & getTopLevelScObjects ()
sc_core::sc_object * findObject (const char *name, const Objects &objects)
sc_core::sc_object * pickParentObj ()
void pushParentObj (sc_core::sc_object *obj)
void popParentObj ()
void throw_it_wrapper (Process *p, ExceptionWrapperBase &exc, bool inc_kids)
void newReset (const sc_core::sc_port_base *pb, Process *p, bool s, bool v)
void newReset (const sc_core::sc_signal_in_if< bool > *sig, Process *p, bool s, bool v)
Process * newMethodProcess (const char *name, ProcessFuncWrapper *func)
Process * newThreadProcess (const char *name, ProcessFuncWrapper *func)
Process * newCThreadProcess (const char *name, ProcessFuncWrapper *func)
uint64_t getChangeStamp ()
Process * spawnWork (ProcessFuncWrapper *func, const char *name, const ::sc_core::sc_spawn_options *opts)
bool listContains (ListNode *list, ListNode *target)
Process * getCurrentProcess ()
const ::sc_core::sc_report reportifyException ()
void newStaticSensitivityEvent (Process *p, const sc_core::sc_event *e)
void newStaticSensitivityInterface (Process *p, const sc_core::sc_interface *i)
void newStaticSensitivityPort (Process *p, const sc_core::sc_port_base *pb)
void newStaticSensitivityExport (Process *p, const sc_core::sc_export_base *exp)
void newStaticSensitivityFinder (Process *p, const sc_core::sc_event_finder *f)
void newDynamicSensitivityEvent (Process *p, const sc_core::sc_event *e)
void newDynamicSensitivityEventOrList (Process *p, const sc_core::sc_event_or_list *eol)
void newDynamicSensitivityEventAndList (Process *p, const sc_core::sc_event_and_list *eal)
tlm::tlm_generic_payload * packet2payload (PacketPtr packet)
Convert a gem5 packet to a TLM payload by copying all the relevant information to new tlm payload.
PacketPtr payload2packet (MasterID masterId, tlm::tlm_generic_payload &trans)
PacketPtr payload2packet (tlm::tlm_generic_payload &trans)
std::map< std::string, ReportMsgInfo > & reportMsgInfoMap ()
std::map< int, std::string > & reportIdToMsgMap ()
Variables
std::set< Channel * > allChannels
Events topLevelEvents
Events allEvents
Kernel * kernel
UniqueNameGen globalNameGen
std::list< Module * > allModules
Objects topLevelObjects
Objects allObjects
std::list< Port * > allPorts
BuiltinExceptionWrapper< UnwindExceptionReset > resetException
BuiltinExceptionWrapper< UnwindExceptionKill > killException
ScMainFiber scMainFiber
Scheduler scheduler
const char * TimeUnitNames []
const char * TimeUnitConstantNames []
double TimeUnitScale []
Tick TimeUnitFrequency []
Gem5SystemC::MemoryManager mm
Instantiate a tlm memory manager that takes care about all the tlm transactions in the system.
const char * reportSeverityNames []
ReportSevInfo reportSevInfos [sc_core::SC_MAX_SEVERITY]
int reportVerbosityLevel = sc_core::SC_MEDIUM
sc_core::sc_actions reportSuppressedActions = sc_core::SC_UNSPECIFIED
sc_core::sc_actions reportForcedActions = sc_core::SC_UNSPECIFIED
sc_core::sc_actions reportCatchActions = sc_core::SC_DISPLAY
sc_core::sc_report_handler_proc reportHandlerProc
std::unique_ptr< sc_core::sc_report > globalReportCache
bool reportWarningsAsErrors = false
Typedef Documentation
ChannelList
typedef NodeList<Channel> sc_gem5::ChannelList
Definition at line 55 of file scheduler.hh.
DynamicSensitivities
typedef std::vector<DynamicSensitivity *> sc_gem5::DynamicSensitivities
Definition at line 110 of file sensitivity.hh.
Events
typedef std::vector< sc_core::sc_event * > sc_gem5::Events
Definition at line 56 of file event.hh.
EventsIt
typedef Events::iterator sc_gem5::EventsIt
Definition at line 47 of file object.hh.
Objects
typedef std::vector<sc_core::sc_object *> sc_gem5::Objects
Definition at line 42 of file object.hh.
ObjectsIt
typedef Objects::iterator sc_gem5::ObjectsIt
Definition at line 46 of file object.hh.
ProcessList
typedef NodeList<Process> sc_gem5::ProcessList
Definition at line 52 of file scheduler.hh.
ScEvents
typedef std::list<ScEvent *> sc_gem5::ScEvents
Definition at line 41 of file sched_event.hh.
StaticSensitivities
typedef std::vector<StaticSensitivity *> sc_gem5::StaticSensitivities
Definition at line 125 of file sensitivity.hh.
TlmInitiatorWrapper
template<unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> using sc_gem5::TlmInitiatorWrapper = typedef TlmInitiatorBaseWrapper<BUSWIDTH, tlm::tlm_fw_transport_if<TYPES>, tlm::tlm_bw_transport_if<TYPES>, N, POL>
Definition at line 124 of file tlm_port_wrapper.hh.
TlmTargetWrapper
template<unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> using sc_gem5::TlmTargetWrapper = typedef TlmTargetBaseWrapper<BUSWIDTH, tlm::tlm_fw_transport_if<TYPES>, tlm::tlm_bw_transport_if<TYPES>, N, POL>
Definition at line 131 of file tlm_port_wrapper.hh.
Function Documentation
currentModule()
Module * sc_gem5::currentModule ()
Definition at line 192 of file module.cc.
findEvent()
EventsIt sc_gem5::findEvent (const std::string & name)
Definition at line 224 of file event.cc.
Referenced by sc_core::sc_find_event(), sc_core::sc_hierarchical_name_exists(), and sc_gem5::Event::~Event().
findObject()
sc_core::sc_object * sc_gem5::findObject (const char * name, const Objects & objects)
Definition at line 298 of file object.cc.
Referenced by sc_core::sc_find_object(), and sc_core::sc_hierarchical_name_exists().
getChangeStamp()
uint64_t sc_gem5::getChangeStamp ()
Definition at line 39 of file sc_prim.cc.
References sc_gem5::Scheduler::changeStamp(), and scheduler.
Referenced by sc_gem5::ScSignalBase::_signalChange(), sc_gem5::ScSignalBaseBinary::_signalNegedge(), sc_gem5::ScSignalBaseBinary::_signalPosedge(), sc_gem5::WriteChecker< sc_core::SC_ONE_WRITER >::checkWriter(), sc_gem5::WriteChecker< sc_core::SC_MANY_WRITERS >::checkWriter(), sc_gem5::ScSignalBase::event(), sc_gem5::ScSignalBaseBinary::negedge(), and sc_gem5::ScSignalBaseBinary::posedge().
getCurrentProcess()
Process * sc_gem5::getCurrentProcess ()
Definition at line 492 of file scheduler.cc.
References sc_gem5::Scheduler::current(), and MipsISA::r.
Referenced by sc_core::sc_signal_rv< W >::write().
getTopLevelScObjects()
const std::vector<sc_core::sc_object *>& sc_gem5::getTopLevelScObjects ()
Definition at line 292 of file object.cc.
References topLevelObjects.
listContains()
bool sc_gem5::listContains (ListNode * list, ListNode * target)
Definition at line 228 of file scheduler.cc.
References ArmISA::n, and sc_gem5::ListNode::nextListNode.
newCThreadProcess()
Process * sc_gem5::newCThreadProcess (const char * name, ProcessFuncWrapper * func)
Definition at line 86 of file sc_module.cc.
References sc_gem5::Process::dontInitialize(), sc_core::sc_object::name(), MipsISA::p, sc_gem5::Scheduler::reg(), sc_core::SC_ID_MODULE_CTHREAD_AFTER_START_, sc_core::sc_is_running(), SC_REPORT_ERROR, and scheduler.
newDynamicSensitivityEvent()
void sc_gem5::newDynamicSensitivityEvent (Process * p, const sc_core::sc_event * e)
Definition at line 190 of file sensitivity.cc.
References ArmISA::s, and sc_gem5::Process::setDynamic().
Referenced by sc_core::next_trigger(), sc_gem5::StaticSensitivityFinder::StaticSensitivityFinder(), and sc_core::wait().
newDynamicSensitivityEventAndList()
void sc_gem5::newDynamicSensitivityEventAndList (Process * p, const sc_core::sc_event_and_list * eal)
Definition at line 207 of file sensitivity.cc.
References sc_gem5::SensitivityEvent::event, ArmISA::s, and sc_gem5::Process::setDynamic().
Referenced by sc_core::next_trigger(), sc_gem5::StaticSensitivityFinder::StaticSensitivityFinder(), and sc_core::wait().
newDynamicSensitivityEventOrList()
void sc_gem5::newDynamicSensitivityEventOrList (Process * p, const sc_core::sc_event_or_list * eol)
Definition at line 198 of file sensitivity.cc.
References sc_gem5::SensitivityEvent::event, ArmISA::s, and sc_gem5::Process::setDynamic().
Referenced by sc_core::next_trigger(), sc_gem5::StaticSensitivityFinder::StaticSensitivityFinder(), and sc_core::wait().
newMethodProcess()
Process * sc_gem5::newMethodProcess (const char * name, ProcessFuncWrapper * func)
Definition at line 56 of file sc_module.cc.
References sc_core::sc_object::name(), MipsISA::p, sc_gem5::Scheduler::reg(), sc_core::SC_ID_MODULE_METHOD_AFTER_START_, sc_core::sc_is_running(), SC_REPORT_ERROR, and scheduler.
newModule()
Module * sc_gem5::newModule ()
Definition at line 208 of file module.cc.
Referenced by sc_gem5::Object::Object().
newModuleChecked()
Module * sc_gem5::newModuleChecked ()
Definition at line 200 of file module.cc.
References sc_core::SC_ID_MODULE_NAME_STACK_EMPTY_, and SC_REPORT_ERROR.
newReset() [1/2]
void sc_gem5::newReset (const sc_core::sc_port_base * pb, Process * p, bool s, bool v)
Definition at line 427 of file process.cc.
References sc_gem5::Port::addReset(), sc_gem5::Port::fromPort(), and Ps2::Reset.
Referenced by sc_core::sc_module::async_reset_signal_is(), sc_core::sc_module::reset_signal_is(), and spawnWork().
newReset() [2/2]
void sc_gem5::newReset (const sc_core::sc_signal_in_if< bool > * sig, Process * p, bool s, bool v)
Definition at line 434 of file process.cc.
References sc_gem5::Reset::install(), Ps2::Reset, and sc_gem5::Process::reset().
newStaticSensitivityEvent()
void sc_gem5::newStaticSensitivityEvent (Process * p, const sc_core::sc_event * e)
Definition at line 124 of file sensitivity.cc.
References sc_gem5::Process::addStatic(), and ArmISA::s.
Referenced by sc_gem5::SensitivityEvents::addEvent(), sc_core::sc_sensitive::operator()(), sc_core::sc_sensitive::operator<<(), and spawnWork().
newStaticSensitivityExport()
void sc_gem5::newStaticSensitivityExport (Process * p, const sc_core::sc_export_base * exp)
Definition at line 149 of file sensitivity.cc.
References sc_gem5::Process::addStatic(), and ArmISA::s.
Referenced by sc_gem5::SensitivityEvents::addEvent(), and spawnWork().
newStaticSensitivityFinder()
void sc_gem5::newStaticSensitivityFinder (Process * p, const sc_core::sc_event_finder * f)
Definition at line 157 of file sensitivity.cc.
References sc_gem5::Process::addStatic(), sc_gem5::Port::fromPort(), sc_core::sc_event_finder::port(), ArmISA::s, and sc_gem5::Port::sensitive().
Referenced by sc_gem5::SensitivityEvents::addEvent(), sc_core::sc_sensitive::operator()(), sc_core::sc_sensitive::operator<<(), and spawnWork().
newStaticSensitivityInterface()
void sc_gem5::newStaticSensitivityInterface (Process * p, const sc_core::sc_interface * i)
Definition at line 132 of file sensitivity.cc.
References sc_gem5::Process::addStatic(), and ArmISA::s.
Referenced by sc_gem5::SensitivityEvents::addEvent(), sc_core::sc_sensitive::operator<<(), and spawnWork().
newStaticSensitivityPort()
void sc_gem5::newStaticSensitivityPort (Process * p, const sc_core::sc_port_base * pb)
Definition at line 140 of file sensitivity.cc.
References sc_gem5::Process::addStatic(), sc_gem5::Port::fromPort(), ArmISA::s, and sc_gem5::Port::sensitive().
Referenced by sc_gem5::SensitivityEvents::addEvent(), sc_core::sc_sensitive::operator<<(), and spawnWork().
newThreadProcess()
Process * sc_gem5::newThreadProcess (const char * name, ProcessFuncWrapper * func)
Definition at line 71 of file sc_module.cc.
References sc_core::sc_object::name(), MipsISA::p, sc_gem5::Scheduler::reg(), sc_core::SC_ID_MODULE_THREAD_AFTER_START_, sc_core::sc_is_running(), SC_REPORT_ERROR, and scheduler.
packet2payload()
tlm::tlm_generic_payload * sc_gem5::packet2payload (PacketPtr packet)
Convert a gem5 packet to a TLM payload by copying all the relevant information to new tlm payload.
Definition at line 86 of file gem5_to_tlm.cc.
References tlm::tlm_generic_payload::acquire(), Gem5SystemC::MemoryManager::allocate(), data, Packet::getAddr(), Packet::getPtr(), Packet::getSize(), tlm::tlm_generic_payload::has_mm(), Packet::isInvalidate(), Packet::isRead(), Packet::isWrite(), Request::NO_ACCESS, Packet::req, sc_assert, SC_REPORT_FATAL, tlm::tlm_generic_payload::set_address(), tlm::tlm_generic_payload::set_auto_extension(), tlm::tlm_generic_payload::set_command(), tlm::tlm_generic_payload::set_data_length(), tlm::tlm_generic_payload::set_data_ptr(), tlm::tlm_generic_payload::set_streaming_width(), tlm::TLM_IGNORE_COMMAND, tlm::TLM_READ_COMMAND, and tlm::TLM_WRITE_COMMAND.
Referenced by sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomic(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvAtomicBackdoor(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvFunctional(), sc_gem5::Gem5ToTlmBridge< BITWIDTH >::recvTimingReq(), and FastModel::ScxEvsCortexA76< Types >::sendFunc().
payload2packet() [1/2]
PacketPtr sc_gem5::payload2packet (MasterID masterId, tlm::tlm_generic_payload & trans)
Definition at line 73 of file tlm_to_gem5.cc.
References tlm::tlm_generic_payload::get_address(), tlm::tlm_generic_payload::get_command(), tlm::tlm_generic_payload::get_data_length(), tlm::tlm_generic_payload::get_data_ptr(), MemCmd::ReadReq, SC_REPORT_FATAL, tlm::TLM_IGNORE_COMMAND, tlm::TLM_READ_COMMAND, tlm::TLM_WRITE_COMMAND, and MemCmd::WriteReq.
Referenced by sc_gem5::TlmToGem5Bridge< BITWIDTH >::b_transport(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::get_direct_mem_ptr(), sc_gem5::TlmToGem5Bridge< BITWIDTH >::handleBeginReq(), and sc_gem5::TlmToGem5Bridge< BITWIDTH >::transport_dbg().
payload2packet() [2/2]
PacketPtr sc_gem5::payload2packet (tlm::tlm_generic_payload & trans)
pickParentModule()
static Module* sc_gem5::pickParentModule () inline static
Definition at line 143 of file module.hh.
References mod(), and pickParentObj().
Referenced by popParentModule(), sc_core::sc_export_base::sc_export_base(), sc_core::sc_gen_unique_name(), and sc_core::sc_port_base::sc_port_base().
pickParentObj()
sc_core::sc_object * sc_gem5::pickParentObj ()
Definition at line 312 of file object.cc.
References sc_gem5::Scheduler::current(), MipsISA::p, and scheduler.
Referenced by sc_gem5::Event::Event(), sc_gem5::Object::Object(), and pickParentModule().
pickUniqueName()
std::string sc_gem5::pickUniqueName (::sc_core::sc_object * parent, std::string base)
Definition at line 275 of file object.cc.
References X86ISA::base, sc_gem5::Object::getFromScObject(), sc_gem5::Object::pickUniqueName(), sc_core::sc_gen_unique_name(), topLevelEvents, and topLevelObjects.
Referenced by sc_gem5::Event::Event(), and sc_gem5::Object::Object().
popParentModule()
static void sc_gem5::popParentModule () inline static
Definition at line 157 of file module.hh.
References allModules, pickParentModule(), and popParentObj().
Referenced by sc_gem5::Module::beforeEndOfElaboration(), sc_gem5::Module::endOfElaboration(), sc_gem5::Module::endOfSimulation(), sc_gem5::Module::finish(), sc_gem5::Module::pop(), and sc_gem5::Module::startOfSimulation().
popParentObj()
void sc_gem5::popParentObj ()
Definition at line 325 of file object.cc.
Referenced by popParentModule(), and sc_core::sc_vector_base::unforceParent().
pushParentModule()
static void sc_gem5::pushParentModule (Module * m) inline static
Definition at line 152 of file module.hh.
References sc_gem5::Module::obj(), pushParentObj(), and sc_gem5::Object::sc_obj().
Referenced by sc_gem5::Module::beforeEndOfElaboration(), sc_gem5::Module::endOfElaboration(), sc_gem5::Module::endOfSimulation(), sc_gem5::Module::finish(), and sc_gem5::Module::startOfSimulation().
pushParentObj()
void sc_gem5::pushParentObj (sc_core::sc_object * obj)
Definition at line 324 of file object.cc.
Referenced by sc_core::sc_vector_base::forceParent(), and pushParentModule().
reportIdToMsgMap()
std::map< int, std::string > & sc_gem5::reportIdToMsgMap ()
Definition at line 58 of file report.cc.
References ArmISA::m.
Referenced by sc_core::sc_report::get_message(), sc_core::sc_report::is_suppressed(), sc_core::sc_report::register_id(), sc_core::sc_report_handler::report(), and sc_core::sc_report::suppress_id().
reportifyException()
const ::sc_core::sc_report sc_gem5::reportifyException ()
Definition at line 506 of file scheduler.cc.
References ArmISA::e, panic, MipsISA::r, reportHandlerProc, sc_core::SC_ID_SIMULATION_UNCAUGHT_EXCEPTION_, SC_REPORT_ERROR, and sc_core::sc_report_handler::set_handler().
Referenced by sc_gem5::ScMainFiber::main(), sc_gem5::Scheduler::TimeSlot::process(), and sc_gem5::Scheduler::throwUp().
reportMsgInfoMap()
std::map< std::string, ReportMsgInfo > & sc_gem5::reportMsgInfoMap ()
Definition at line 51 of file report.cc.
References ArmISA::m.
Referenced by sc_core::sc_report_handler::get_count(), sc_core::sc_report::is_suppressed(), sc_core::sc_report::register_id(), sc_core::sc_report_handler::report(), sc_core::sc_report_handler::set_actions(), sc_core::sc_report_handler::stop_after(), and sc_core::sc_report::suppress_id().
spawnWork()
Process * sc_gem5::spawnWork (ProcessFuncWrapper * func, const char * name, const ::sc_core::sc_spawn_options * opts)
Definition at line 47 of file sc_spawn.cc.
References sc_gem5::Process::dontInitialize(), ArmISA::e, ArmISA::f, ArmISA::i, sc_core::sc_object::name(), newReset(), newStaticSensitivityEvent(), newStaticSensitivityExport(), newStaticSensitivityFinder(), newStaticSensitivityInterface(), newStaticSensitivityPort(), MipsISA::p, sc_gem5::Scheduler::reg(), sc_core::sc_gen_unique_name(), sc_core::SC_ID_DISABLE_WILL_ORPHAN_PROCESS_, SC_REPORT_WARNING, scheduler, and warn.
Referenced by sc_gem5::ProcessObjRetFuncWrapper< T, R >::call(), and sc_core::sc_spawn().
throw_it_wrapper()
void sc_gem5::throw_it_wrapper (Process * p, ExceptionWrapperBase & exc, bool inc_kids)
Definition at line 421 of file process.cc.
References sc_gem5::Process::throw_it().
Referenced by sc_gem5::ExceptionWrapper< T >::throw_it(), and sc_core::sc_process_handle::throw_it().
Variable Documentation
allChannels
std::set< Channel * > sc_gem5::allChannels
Definition at line 60 of file channel.cc.
Referenced by sc_gem5::Channel::Channel(), sc_gem5::Kernel::init(), sc_gem5::Kernel::regStats(), sc_gem5::Kernel::startup(), sc_gem5::Kernel::stopWork(), and sc_gem5::Channel::~Channel().
allEvents
Events sc_gem5::allEvents
Definition at line 221 of file event.cc.
Referenced by sc_gem5::Event::Event(), sc_core::sc_find_event(), sc_core::sc_hierarchical_name_exists(), and sc_gem5::Event::~Event().
allModules
std::list< Module * > sc_gem5::allModules
Definition at line 213 of file module.cc.
Referenced by sc_gem5::Module::finish(), sc_gem5::Kernel::init(), popParentModule(), sc_gem5::Kernel::regStats(), sc_gem5::Kernel::startup(), sc_gem5::Kernel::stopWork(), and sc_gem5::Module::~Module().
allObjects
Objects sc_gem5::allObjects
Definition at line 289 of file object.cc.
Referenced by sc_core::sc_simcontext::first_object(), sc_core::sc_simcontext::next_object(), sc_gem5::Object::Object(), sc_core::sc_hierarchical_name_exists(), and sc_gem5::Object::~Object().
allPorts
std::list< Port * > sc_gem5::allPorts
Definition at line 169 of file port.cc.
Referenced by sc_gem5::Kernel::init(), sc_gem5::Kernel::regStats(), sc_gem5::Kernel::startup(), and sc_gem5::Kernel::stopWork().
globalNameGen
UniqueNameGen sc_gem5::globalNameGen
Definition at line 51 of file module.cc.
Referenced by sc_gem5::Event::Event(), sc_gem5::UniqueNameGen::gen(), and sc_core::sc_gen_unique_name().
globalReportCache
std::unique_ptr< sc_core::sc_report > sc_gem5::globalReportCache
Definition at line 73 of file report.cc.
Referenced by sc_core::sc_report_handler::clear_cached_report(), sc_core::sc_report_handler::get_cached_report(), and sc_core::sc_report_handler::report().
kernel
Kernel * sc_gem5::kernel
Definition at line 183 of file kernel.cc.
Referenced by sc_gem5::Scheduler::initPhase(), sc_gem5::Scheduler::pause(), sc_gem5::Scheduler::start(), sc_gem5::Kernel::startup(), and sc_gem5::Scheduler::stop().
killException
BuiltinExceptionWrapper<UnwindExceptionKill> sc_gem5::killException
Definition at line 65 of file process.cc.
mm
Gem5SystemC::MemoryManager sc_gem5::mm
Instantiate a tlm memory manager that takes care about all the tlm transactions in the system.
Definition at line 79 of file gem5_to_tlm.cc.
reportCatchActions
sc_core::sc_actions sc_gem5::reportCatchActions = sc_core::SC_DISPLAY
Definition at line 68 of file report.cc.
Referenced by sc_core::sc_report_handler::get_catch_actions(), and sc_core::sc_report_handler::set_catch_actions().
reportForcedActions
sc_core::sc_actions sc_gem5::reportForcedActions = sc_core::SC_UNSPECIFIED
Definition at line 67 of file report.cc.
Referenced by sc_core::sc_report_handler::force(), and sc_core::sc_report_handler::report().
reportHandlerProc
sc_core::sc_report_handler_proc sc_gem5::reportHandlerProc
Initial value:
=
    &sc_core::sc_report_handler::default_handler
Definition at line 70 of file report.cc.
Referenced by sc_gem5::ScMainFiber::main(), sc_core::sc_report_handler::report(), reportifyException(), sc_core::sc_report_handler::set_handler(), and sc_gem5::Scheduler::throwUp().
reportSeverityNames
const char * sc_gem5::reportSeverityNames
Initial value:
= {
    [sc_core::SC_INFO] = "Info",
    [sc_core::SC_WARNING] = "Warning",
    [sc_core::SC_ERROR] = "Error",
    [sc_core::SC_FATAL] = "Fatal"
}
Definition at line 35 of file report.cc.
Referenced by sc_core::sc_report_compose_message().
reportSevInfos
ReportSevInfo sc_gem5::reportSevInfos
Initial value:
=
{
    [sc_core::SC_INFO] = ReportSevInfo(sc_core::SC_DEFAULT_INFO_ACTIONS),
    [sc_core::SC_WARNING] = ReportSevInfo(sc_core::SC_DEFAULT_WARNING_ACTIONS),
    [sc_core::SC_ERROR] = ReportSevInfo(sc_core::SC_DEFAULT_ERROR_ACTIONS),
    [sc_core::SC_FATAL] = ReportSevInfo(sc_core::SC_DEFAULT_FATAL_ACTIONS)
}
Definition at line 42 of file report.cc.
Referenced by sc_core::sc_report_handler::get_count(), sc_core::sc_report_handler::report(), sc_core::sc_report_handler::set_actions(), sc_core::sc_report_handler::stop_after(), sc_core::sc_report::suppress_infos(), and sc_core::sc_report::suppress_warnings().
reportSuppressedActions
sc_core::sc_actions sc_gem5::reportSuppressedActions = sc_core::SC_UNSPECIFIED
Definition at line 66 of file report.cc.
Referenced by sc_core::sc_report_handler::report(), and sc_core::sc_report_handler::suppress().
reportVerbosityLevel
int sc_gem5::reportVerbosityLevel = sc_core::SC_MEDIUM
Definition at line 64 of file report.cc.
Referenced by sc_core::sc_report_handler::get_verbosity_level(), sc_core::sc_report_handler::report(), and sc_core::sc_report_handler::set_verbosity_level().
reportWarningsAsErrors
bool sc_gem5::reportWarningsAsErrors = false
Definition at line 75 of file report.cc.
Referenced by sc_core::sc_report::make_warnings_errors(), and sc_core::sc_report_handler::report().
resetException
BuiltinExceptionWrapper<UnwindExceptionReset> sc_gem5::resetException
Definition at line 64 of file process.cc.
scheduler
Scheduler sc_gem5::scheduler
Definition at line 491 of file scheduler.cc.
Referenced by sc_gem5::Channel::asyncRequestUpdate(), sc_core::sc_clock::before_end_of_elaboration(), sc_gem5::Event::cancel(), sc_gem5::Process::cancelTimeout(), sc_gem5::WriteChecker< sc_core::SC_ONE_WRITER >::checkWriter(), sc_gem5::WriteChecker< sc_core::SC_MANY_WRITERS >::checkWriter(), sc_core::sc_report_handler::clear_cached_report(), sc_gem5::ClockTick::createProcess(), sc_core::sc_report_handler::default_handler(), sc_core::sc_simcontext::elaboration_done(), sc_core::sc_report_handler::get_cached_report(), sc_core::sc_simcontext::get_curr_proc_info(), getChangeStamp(), sc_gem5::Kernel::init(), sc_gem5::VcdTraceFile::initialize(), sc_gem5::Process::injectException(), sc_gem5::Kernel::Kernel(), sc_gem5::ScMainFiber::main(), sc_gem5::Thread::Context::main(), newCThreadProcess(), newMethodProcess(), newThreadProcess(), sc_core::next_trigger(), sc_gem5::Event::notify(), sc_gem5::Sensitivity::notify(), pickParentObj(), sc_gem5::Process::ready(), sc_gem5::Kernel::regStats(), sc_core::sc_report_handler::report(), sc_gem5::Channel::requestUpdate(), sc_gem5::Process::reset(), sc_gem5::Process::resume(), sc_core::sc_close_vcd_trace_file(), sc_core::sc_create_vcd_trace_file(), sc_core::sc_delta_count(), sc_core::sc_export_base::sc_export_base(), sc_core::sc_gen_unique_name(), sc_core::sc_get_curr_process_handle(), sc_core::sc_get_current_process_handle(), sc_core::sc_module::sc_module(), sc_core::sc_module_name::sc_module_name(), sc_core::sc_pause(), sc_core::sc_pending_activity_at_current_time(), sc_core::sc_pending_activity_at_future_time(), sc_core::sc_port_base::sc_port_base(), sc_core::sc_prim_channel::sc_prim_channel(), sc_core::sc_report_compose_message(), sc_core::sc_set_location(), sc_core::sc_start(), sc_core::sc_stop(), sc_core::sc_time_stamp(), sc_core::sc_time_to_pending_activity(), sc_gem5::Process::setTimeout(), sc_gem5::Process::signalReset(), spawnWork(), sc_gem5::Kernel::startup(), sc_gem5::Kernel::stopWork(), sc_gem5::Process::suspend(), sc_gem5::Kernel::t0Handler(), sc_gem5::ClockTick::tick(), sc_core::timed_out(), sc_gem5::VcdTraceFile::trace(), sc_gem5::Event::triggered(), sc_core::sc_mutex::trylock(), sc_core::sc_mutex::unlock(), sc_core::wait(), sc_core::sc_signal_resolved::write(), sc_gem5::ClockTick::~ClockTick(), sc_gem5::Event::~Event(), sc_core::sc_clock::~sc_clock(), sc_gem5::ScEvent::~ScEvent(), and sc_gem5::VcdTraceFile::~VcdTraceFile().
scMainFiber
ScMainFiber sc_gem5::scMainFiber
Definition at line 80 of file sc_main_fiber.cc.
Referenced by sc_gem5::Kernel::init(), sc_gem5::Scheduler::pause(), sc_gem5::Kernel::regStats(), sc_core::sc_argc(), sc_core::sc_argv(), sc_gem5::ScMainFiber::setArgs(), sc_gem5::Kernel::startup(), sc_gem5::Scheduler::stop(), and sc_gem5::Scheduler::throwUp().
TimeUnitConstantNames
const char * sc_gem5::TimeUnitConstantNames
Initial value:
= {
    [::sc_core::SC_FS] = "SC_FS",
    [::sc_core::SC_PS] = "SC_PS",
    [::sc_core::SC_NS] = "SC_NS",
    [::sc_core::SC_US] = "SC_US",
    [::sc_core::SC_MS] = "SC_MS",
    [::sc_core::SC_SEC] = "SC_SEC"
}
Definition at line 46 of file time.cc.
Referenced by sc_core::sc_time::sc_time().
TimeUnitFrequency
Tick sc_gem5::TimeUnitFrequency
Initial value:
= {
    [::sc_core::SC_FS] = 1ULL * 1000 * 1000 * 1000 * 1000 * 1000,
    [::sc_core::SC_PS] = 1ULL * 1000 * 1000 * 1000 * 1000,
    [::sc_core::SC_NS] = 1ULL * 1000 * 1000 * 1000,
    [::sc_core::SC_US] = 1ULL * 1000 * 1000,
    [::sc_core::SC_MS] = 1ULL * 1000,
    [::sc_core::SC_SEC] = 1ULL
}
Definition at line 64 of file time.cc.
Referenced by sc_core::sc_set_time_resolution().
TimeUnitNames
const char * sc_gem5::TimeUnitNames
Initial value:
= {
    [::sc_core::SC_FS] = "fs",
    [::sc_core::SC_PS] = "ps",
    [::sc_core::SC_NS] = "ns",
    [::sc_core::SC_US] = "us",
    [::sc_core::SC_MS] = "ms",
    [::sc_core::SC_SEC] = "s"
}
Definition at line 37 of file time.cc.
Referenced by sc_core::sc_time::sc_time(), sc_gem5::TraceFile::set_time_unit(), and sc_core::sc_time_tuple::unit_symbol().
TimeUnitScale
double sc_gem5::TimeUnitScale
Initial value:
= {
    [::sc_core::SC_FS] = 1.0e-15,
    [::sc_core::SC_PS] = 1.0e-12,
    [::sc_core::SC_NS] = 1.0e-9,
    [::sc_core::SC_US] = 1.0e-6,
    [::sc_core::SC_MS] = 1.0e-3,
    [::sc_core::SC_SEC] = 1.0
}
Definition at line 55 of file time.cc.
Referenced by sc_core::sc_set_default_time_unit(), sc_core::sc_set_time_resolution(), and sc_gem5::TraceFile::set_time_unit().
topLevelEvents
Events sc_gem5::topLevelEvents
Definition at line 220 of file event.cc.
Referenced by sc_gem5::Event::clearParent(), sc_gem5::Event::Event(), pickUniqueName(), sc_core::sc_get_top_level_events(), and sc_gem5::Event::~Event().
topLevelObjects
Objects sc_gem5::topLevelObjects
Definition at line 288 of file object.cc.
Referenced by getTopLevelScObjects(), sc_gem5::Object::Object(), pickUniqueName(), sc_core::sc_get_top_level_objects(), and sc_gem5::Object::~Object().