gem5: PseudoInst Namespace Reference
PseudoInst Namespace Reference
Classes
struct InitParamKey
Unique keys to retrieve various params by the initParam pseudo inst.
Functions
static void panicFsOnlyPseudoInst (const char *name)
uint64_t pseudoInst (ThreadContext *tc, uint8_t func, uint8_t subfunc)
Execute a decoded M5 pseudo instruction.
void arm (ThreadContext *tc)
void quiesce (ThreadContext *tc)
void quiesceSkip (ThreadContext *tc)
void quiesceNs (ThreadContext *tc, uint64_t ns)
void quiesceCycles (ThreadContext *tc, uint64_t cycles)
uint64_t quiesceTime (ThreadContext *tc)
uint64_t rpns (ThreadContext *tc)
void wakeCPU (ThreadContext *tc, uint64_t cpuid)
void m5exit (ThreadContext *tc, Tick delay)
void m5fail (ThreadContext *tc, Tick delay, uint64_t code)
void loadsymbol (ThreadContext *tc)
void addsymbol (ThreadContext *tc, Addr addr, Addr symbolAddr)
uint64_t initParam (ThreadContext *tc, uint64_t key_str1, uint64_t key_str2)
void resetstats (ThreadContext *tc, Tick delay, Tick period)
void dumpstats (ThreadContext *tc, Tick delay, Tick period)
void dumpresetstats (ThreadContext *tc, Tick delay, Tick period)
void m5checkpoint (ThreadContext *tc, Tick delay, Tick period)
uint64_t readfile (ThreadContext *tc, Addr vaddr, uint64_t len, uint64_t offset)
uint64_t writefile (ThreadContext *tc, Addr vaddr, uint64_t len, uint64_t offset, Addr filename_addr)
void debugbreak (ThreadContext *tc)
void switchcpu (ThreadContext *tc)
void togglesync (ThreadContext *tc)
void workbegin (ThreadContext *tc, uint64_t workid, uint64_t threadid)
void workend (ThreadContext *tc, uint64_t workid, uint64_t threadid)
Function Documentation
addsymbol()
void PseudoInst::addsymbol (ThreadContext * tc, Addr addr, Addr symbolAddr)
Definition at line 373 of file pseudo_inst.cc.
References debugSymbolTable, DPRINTF, FullSystem, ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), SymbolTable::insert(), System::kernelSymtab, panicFsOnlyPseudoInst(), and PortProxy::readString().
Referenced by pseudoInst().
arm()
void PseudoInst::arm (ThreadContext * tc)
Definition at line 231 of file pseudo_inst.cc.
References Kernel::Statistics::arm(), DPRINTF, FullSystem, ThreadContext::getKernelStats(), and panicFsOnlyPseudoInst().
Referenced by pseudoInst().
debugbreak()
void PseudoInst::debugbreak (ThreadContext * tc)
Definition at line 576 of file pseudo_inst.cc.
References Debug::breakpoint(), and DPRINTF.
Referenced by pseudoInst().
dumpresetstats()
void PseudoInst::dumpresetstats (ThreadContext * tc, Tick delay, Tick period)
Definition at line 463 of file pseudo_inst.cc.
References curTick(), DPRINTF, ThreadContext::getCpuPtr(), SimClock::Int::ns, BaseCPU::params(), and Stats::schedStatEvent().
Referenced by pseudoInst().
dumpstats()
void PseudoInst::dumpstats (ThreadContext * tc, Tick delay, Tick period)
Definition at line 449 of file pseudo_inst.cc.
References curTick(), DPRINTF, ThreadContext::getCpuPtr(), SimClock::Int::ns, BaseCPU::params(), and Stats::schedStatEvent().
Referenced by pseudoInst().
initParam()
uint64_t PseudoInst::initParam (ThreadContext * tc, uint64_t key_str1, uint64_t key_str2)
Definition at line 390 of file pseudo_inst.cc.
References DPRINTF, FullSystem, ThreadContext::getCpuPtr(), System::init_param, ArmISA::len, panic, panicFsOnlyPseudoInst(), DistIface::rankParam(), DistIface::sizeParam(), BaseCPU::system, and X86ISA::val.
Referenced by pseudoInst().
loadsymbol()
void PseudoInst::loadsymbol (ThreadContext * tc)
Definition at line 321 of file pseudo_inst.cc.
References addr, DPRINTF, eat_white(), fatal, FullSystem, ThreadContext::getCpuPtr(), ThreadContext::getSystemPtr(), SymbolTable::insert(), System::kernelSymtab, panicFsOnlyPseudoInst(), System::params(), BaseCPU::system, and to_number().
Referenced by pseudoInst().
m5checkpoint()
void PseudoInst::m5checkpoint (ThreadContext * tc, Tick delay, Tick period)
Definition at line 477 of file pseudo_inst.cc.
References curTick(), DPRINTF, exitSimLoop(), ThreadContext::getCpuPtr(), SimClock::Int::ns, BaseCPU::params(), and DistIface::readyToCkpt().
Referenced by pseudoInst().
m5exit()
void PseudoInst::m5exit (ThreadContext * tc, Tick delay)
Definition at line 303 of file pseudo_inst.cc.
References curTick(), DPRINTF, exitSimLoop(), SimClock::Int::ns, and DistIface::readyToExit().
Referenced by pseudoInst().
m5fail()
void PseudoInst::m5fail (ThreadContext * tc, Tick delay, uint64_t code)
Definition at line 313 of file pseudo_inst.cc.
References curTick(), DPRINTF, exitSimLoop(), and SimClock::Int::ns.
Referenced by pseudoInst().
panicFsOnlyPseudoInst()
static void PseudoInst::panicFsOnlyPseudoInst (const char * name) inline static
Definition at line 91 of file pseudo_inst.cc.
References panic.
Referenced by addsymbol(), arm(), initParam(), loadsymbol(), and readfile().
pseudoInst()
uint64_t PseudoInst::pseudoInst (ThreadContext * tc, uint8_t func, uint8_t subfunc)
Execute a decoded M5 pseudo instruction.
The ISA-specific code is responsible to decode the pseudo inst function number and subfunction number. After that has been done, the rest of the instruction can be implemented in an ISA-agnostic manner using the ISA-specific getArguments functions.
Parameters
func M5 pseudo op major function number (see utility/m5/m5ops.h)
subfunc M5 minor function number. Mainly used for annotations.
Definition at line 97 of file pseudo_inst.cc.
References addsymbol(), arm(), debugbreak(), DPRINTF, dumpresetstats(), dumpstats(), AlphaISA::getArgument(), ArmISA::i, initParam(), loadsymbol(), m5checkpoint(), m5exit(), m5fail(), X86ISA::m5PageFault(), X86ISA::m5Syscall(), panic, ThreadContext::pcState(), quiesce(), quiesceCycles(), quiesceNs(), quiesceTime(), readfile(), resetstats(), rpns(), switchcpu(), togglesync(), wakeCPU(), warn, workbegin(), workend(), and writefile().
Referenced by handlePseudoInst(), and ArmKvmCPU::onKvmExitHypercall().
quiesce()
void PseudoInst::quiesce (ThreadContext * tc)
Definition at line 242 of file pseudo_inst.cc.
References DPRINTF, and ThreadContext::quiesce().
Referenced by DefaultFetch< Impl >::fetch(), pseudoInst(), and ThreadContext::~ThreadContext().
quiesceCycles()
void PseudoInst::quiesceCycles (ThreadContext * tc, uint64_t cycles)
Definition at line 263 of file pseudo_inst.cc.
References Clocked::clockEdge(), DPRINTF, ThreadContext::getCpuPtr(), and ThreadContext::quiesceTick().
Referenced by pseudoInst().
quiesceNs()
void PseudoInst::quiesceNs (ThreadContext * tc, uint64_t ns)
Definition at line 256 of file pseudo_inst.cc.
References curTick(), DPRINTF, SimClock::Int::ns, and ThreadContext::quiesceTick().
Referenced by FreeBSD::UDelayEvent::process(), Linux::UDelayEvent::process(), and pseudoInst().
quiesceSkip()
void PseudoInst::quiesceSkip (ThreadContext * tc)
Definition at line 249 of file pseudo_inst.cc.
References DPRINTF, ThreadContext::getCpuPtr(), Clocked::nextCycle(), and ThreadContext::quiesceTick().
quiesceTime()
uint64_t PseudoInst::quiesceTime (ThreadContext * tc)
Definition at line 270 of file pseudo_inst.cc.
References DPRINTF, SimClock::Int::ns, ThreadContext::readLastActivate(), and ThreadContext::readLastSuspend().
Referenced by pseudoInst().
readfile()
uint64_t PseudoInst::readfile (ThreadContext * tc, Addr vaddr, uint64_t len, uint64_t offset)
Definition at line 491 of file pseudo_inst.cc.
References DPRINTF, ArmISA::fd, FullSystem, ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), ArmISA::len, MipsISA::p, panic, panicFsOnlyPseudoInst(), System::params(), ULL, and PortProxy::writeBlob().
Referenced by pseudoInst().
resetstats()
void PseudoInst::resetstats (ThreadContext * tc, Tick delay, Tick period)
Definition at line 435 of file pseudo_inst.cc.
References curTick(), DPRINTF, ThreadContext::getCpuPtr(), SimClock::Int::ns, BaseCPU::params(), and Stats::schedStatEvent().
Referenced by pseudoInst().
rpns()
uint64_t PseudoInst::rpns (ThreadContext * tc)
Definition at line 279 of file pseudo_inst.cc.
References curTick(), DPRINTF, and SimClock::Int::ns.
Referenced by pseudoInst().
switchcpu()
void PseudoInst::switchcpu (ThreadContext * tc)
Definition at line 583 of file pseudo_inst.cc.
References DPRINTF, and exitSimLoop().
Referenced by pseudoInst().
togglesync()
void PseudoInst::togglesync (ThreadContext * tc)
Definition at line 590 of file pseudo_inst.cc.
References DPRINTF, and DistIface::toggleSync().
Referenced by pseudoInst().
wakeCPU()
void PseudoInst::wakeCPU (ThreadContext * tc, uint64_t cpuid)
Definition at line 286 of file pseudo_inst.cc.
References ThreadContext::activate(), MipsISA::cpuid, DPRINTF, ThreadContext::getSystemPtr(), System::numContexts(), ThreadContext::status(), ThreadContext::Suspended, System::threadContexts, and warn.
Referenced by FullO3CPU< O3CPUImpl >::deactivateStage(), and pseudoInst().
workbegin()
void PseudoInst::workbegin (ThreadContext * tc, uint64_t workid, uint64_t threadid)
Definition at line 602 of file pseudo_inst.cc.
References BaseCPU::cpuId(), DPRINTF, exitSimLoop(), ThreadContext::getCpuPtr(), ThreadContext::getSystemPtr(), System::incWorkItemsBegin(), System::markWorkItem(), System::params(), BaseCPU::workItemBegin(), and System::workItemBegin().
Referenced by pseudoInst().
workend()
void PseudoInst::workend (ThreadContext * tc, uint64_t workid, uint64_t threadid)
Definition at line 665 of file pseudo_inst.cc.
References BaseCPU::cpuId(), DPRINTF, exitSimLoop(), ThreadContext::getCpuPtr(), ThreadContext::getSystemPtr(), System::incWorkItemsEnd(), System::markWorkItem(), System::params(), BaseCPU::workItemEnd(), and System::workItemEnd().
Referenced by pseudoInst().
writefile()
uint64_t PseudoInst::writefile (ThreadContext * tc, Addr vaddr, uint64_t len, uint64_t offset, Addr filename_addr)
Definition at line 533 of file pseudo_inst.cc.
References OutputDirectory::close(), OutputDirectory::create(), DPRINTF, ThreadContext::getVirtProxy(), ArmISA::len, OutputDirectory::open(), X86ISA::os, panic, PortProxy::readBlob(), PortProxy::readString(), simout, and OutputStream::stream().
Referenced by pseudoInst().