gem5: Stats Namespace Reference
Stats Namespace Reference
Classes
class Average
A stat that calculates the per tick average of a value.
class AverageDeviation
Calculates the per tick mean and variance of the samples.
class AverageVector
A vector of Average stats.
class AvgSampleStor
Templatized storage for distribution that calculates per tick mean and variance.
class AvgStor
Templatized storage and interface to a per-tick average stat.
class BinaryNode
class ConstNode
class ConstVectorNode
class DataWrap
class DataWrapVec
class DataWrapVec2d
class DistBase
Implementation of a distribution stat.
struct DistData
class DistInfo
class DistInfoProxy
struct DistParams
The parameters for a distribution stat.
struct DistPrint
class DistProxy
class Distribution
A simple distribution stat.
class DistStor
Templatized storage and interface for a distribution stat.
class Formula
A formula for statistics that is calculated when printed.
class FormulaInfo
class FormulaInfoProxy
class FormulaNode
class FunctorProxy
struct Global
class Group
Statistics container.
class Hdf5
class Histogram
A simple histogram stat.
class HistStor
Templatized storage and interface for a histogram stat.
class Info
class InfoAccess
class InfoProxy
class MethodProxy
A proxy similar to the FunctorProxy, but allows calling a method of a bound object, instead of a global free-standing function.
class Node
Base class for formula statistic node.
struct OpString
struct OpString< std::divides< Result > >
struct OpString< std::minus< Result > >
struct OpString< std::modulus< Result > >
struct OpString< std::multiplies< Result > >
struct OpString< std::negate< Result > >
struct OpString< std::plus< Result > >
struct Output
class ProxyInfo
class SampleStor
Templatized storage and interface for a distribution that calculates mean and variance.
class Scalar
This is a simple scalar statistic, like a counter.
class ScalarBase
Implementation of a scalar stat.
class ScalarInfo
class ScalarInfoProxy
struct ScalarPrint
class ScalarProxy
A proxy class to access the stat at a given index in a VectorBase stat.
class ScalarProxyNode
class ScalarStatNode
struct SimTicksReset
class SparseHistBase
Implementation of a sparse histogram stat.
struct SparseHistData
Data structure of sparse histogram.
class SparseHistInfo
class SparseHistInfoProxy
class SparseHistogram
struct SparseHistPrint
class SparseHistStor
Templatized storage and interface for a sparse histogram stat.
class StandardDeviation
Calculates the mean and variance of all the samples.
class StatEvent
Event to dump and/or reset the statistics.
class StatStor
Templatized storage and interface for a simple scalar stat.
struct StorageParams
class SumNode
class Temp
Helper class to construct formula node trees.
class Text
class UnaryNode
class Value
class ValueBase
class ValueProxy
class Vector
A vector of scalar stats.
class Vector2d
A 2-Dimensional vecto of scalar stats.
class Vector2dBase
class Vector2dInfo
class Vector2dInfoProxy
class VectorAverageDeviation
This is a vector of AverageDeviation stats.
class VectorBase
Implementation of a vector of stats.
class VectorDistBase
class VectorDistInfo
class VectorDistInfoProxy
class VectorDistribution
A vector of distributions.
class VectorInfo
class VectorInfoProxy
struct VectorPrint
class VectorProxy
class VectorStandardDeviation
This is a vector of StandardDeviation stats.
class VectorStatNode
Typedefs
typedef std::shared_ptr< Node > NodePtr
Shared pointer to a function Node.
typedef void(* Handler) ()
Register reset and dump handlers.
typedef std::map< const void *, Info * > MapType
typedef std::map< std::string, Info * > NameMapType
typedef uint16_t FlagsType
typedef ::Flags< FlagsType > Flags
typedef double Counter
All counters are of 64-bit values.
typedef std::vector< Counter > VCounter
vector of counters.
typedef std::map< Counter, int > MCounter
map of counters
typedef std::numeric_limits< Counter > CounterLimits
typedef double Result
All results are doubles.
typedef std::vector< Result > VResult
vector of results.
typedef unsigned int size_type
typedef unsigned int off_type
Enumerations
enum DistType { Deviation, Dist, Hist }
Functions
list< Info * > & statsList ()
MapType & statsMap ()
NameMapType & nameMap ()
bool validateStatName (const string &name)
void registerHandlers (Handler reset_handler, Handler dump_handler)
void processResetQueue ()
Process all the callbacks in the reset callbacks queue.
void processDumpQueue ()
Process all the callbacks in the dump callbacks queue.
void registerResetCallback (Callback *cb)
Register a callback that should be called whenever statistics are reset.
bool enabled ()
void enable ()
void dump ()
Dump all statistics data to the registered outputs.
void reset ()
void registerDumpCallback (Callback *cb)
Register a callback that should be called whenever statistics are about to be dumped.
Temp operator+ (Temp l, Temp r)
Temp operator- (Temp l, Temp r)
Temp operator* (Temp l, Temp r)
Temp operator/ (Temp l, Temp r)
Temp operator- (Temp l)
template<typename T >
Temp constant (T val)
template<typename T >
Temp constantVector (T val)
Temp sum (Temp val)
bool validateStatName (const std::string &name)
std::unique_ptr< Output > initHDF5 (const std::string &filename, unsigned chunking, bool desc, bool formulas)
string ValueToString (Result value, int precision)
Output * initText (const string &filename, bool desc)
Output * initText (const std::string &filename, bool desc)
void pythonDump ()
void pythonReset ()
double statElapsedTime ()
Tick statElapsedTicks ()
Tick statFinalTick ()
void initSimStats ()
void schedStatEvent (bool dump, bool reset, Tick when=curTick(), Tick repeat=0)
Schedule statistics dumping.
void periodicStatDump (Tick period=0)
Schedule periodic statistics dumping.
void updateEvents ()
Update the events after resuming from a checkpoint.
void registerPythonStatsHandlers ()
Register py_...
Variables
int debug_break_id = -1
Handler resetHandler = NULL
Handler dumpHandler = NULL
CallbackQueue dumpQueue
CallbackQueue resetQueue
bool _enabled = false
const FlagsType none = 0x0000
Nothing extra to print.
const FlagsType init = 0x0001
This Stat is Initialized.
const FlagsType display = 0x0002
Print this stat.
const FlagsType total = 0x0010
Print the total.
const FlagsType pdf = 0x0020
Print the percent of the total that this entry represents.
const FlagsType cdf = 0x0040
Print the cumulative percentage of total upto this entry.
const FlagsType dist = 0x0080
Print the distribution.
const FlagsType nozero = 0x0100
Don't print if this is zero.
const FlagsType nonan = 0x0200
Don't print if this is NAN.
const FlagsType oneline = 0x0400
Print all values on a single line.
const FlagsType __reserved = init | display
Mask of flags that can't be set directly.
Time statTime (true)
Tick startTick
GlobalEvent * dumpEvent
SimTicksReset simTicksReset
Typedef Documentation
Counter
typedef double Stats::Counter
All counters are of 64-bit values.
Definition at line 43 of file types.hh.
CounterLimits
typedef std::numeric_limits<Counter> Stats::CounterLimits
Definition at line 49 of file types.hh.
Flags
typedef ::Flags<FlagsType> Stats::Flags
Definition at line 42 of file info.hh.
FlagsType
typedef uint16_t Stats::FlagsType
Definition at line 39 of file info.hh.
Handler
typedef void(* Stats::Handler) ()
Register reset and dump handlers.
These are the functions which will actually perform the whole statistics reset/dump actions including processing the reset/dump callbacks
Definition at line 3363 of file statistics.hh.
MapType
typedef std::map<const void *, Info *> Stats::MapType
Definition at line 3391 of file statistics.hh.
MCounter
typedef std::map<Counter, int> Stats::MCounter
map of counters
Definition at line 47 of file types.hh.
NameMapType
typedef std::map<std::string, Info *> Stats::NameMapType
Definition at line 3394 of file statistics.hh.
NodePtr
typedef std::shared_ptr<Node> Stats::NodePtr
Shared pointer to a function Node.
Definition at line 2131 of file statistics.hh.
off_type
typedef unsigned int Stats::off_type
Definition at line 57 of file types.hh.
Result
typedef double Stats::Result
All results are doubles.
Definition at line 52 of file types.hh.
size_type
typedef unsigned int Stats::size_type
Definition at line 56 of file types.hh.
VCounter
typedef std::vector<Counter> Stats::VCounter
vector of counters.
Definition at line 45 of file types.hh.
VResult
typedef std::vector<Result> Stats::VResult
vector of results.
Definition at line 54 of file types.hh.
Enumeration Type Documentation
DistType
enum Stats::DistType
Enumerator
Deviation
Dist
Hist
Definition at line 175 of file info.hh.
Function Documentation
constant()
template<typename T > Temp Stats::constant (T val) inline
Definition at line 3334 of file statistics.hh.
Referenced by StatTest::init(), SimpleNetwork::regStats(), EtherDevice::regStats(), Switch::regStats(), Throttle::regStats(), BaseTags::BaseTagStats::regStats(), and BaseSimpleCPU::regStats().
constantVector()
template<typename T > Temp Stats::constantVector (T val) inline
Definition at line 3341 of file statistics.hh.
dump()
void Stats::dump ()
Dump all statistics data to the registered outputs.
Definition at line 561 of file statistics.cc.
References dumpHandler, and fatal.
Referenced by debugDumpStats(), PowerISA::StackTrace::decodePrologue(), RiscvISA::StackTrace::decodePrologue(), MipsISA::StackTrace::decodePrologue(), X86ISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), ArmISA::StackTrace::decodePrologue(), DependencyGraph< DynInstPtr >::empty(), EventQueue::empty(), PCEventQueue::equal_range(), Event::Event(), ArmISA::StackTrace::getstack(), CPA::hwWe(), Trace::InstPBTraceRecord::InstPBTraceRecord(), sc_core::sc_object::kind(), sc_dt::sc_unsigned::print(), sc_dt::sc_signed::print(), AnnotateDumpCallback::process(), Stats::StatEvent::process(), DistEtherLink::RxLink::rxDone(), StoreSet::StoreSet(), sum(), DistEtherLink::TxLink::txDone(), and DVFSHandler::UpdateEvent::updatePerfLevel().
enable()
void Stats::enable ()
Definition at line 552 of file statistics.cc.
References fatal.
Referenced by pybind_init_stats(), and sum().
enabled()
bool Stats::enabled ()
Definition at line 546 of file statistics.cc.
References _enabled.
Referenced by System::_getMasterId(), IGbE::TxDescCache::completionWriteback(), Iris::ThreadContext::initFromIrisInstance(), AnnotateDumpCallback::process(), pybind_init_stats(), and sum().
initHDF5()
std::unique_ptr< Output > Stats::initHDF5 (const std::string & filename, unsigned chunking, bool desc, bool formulas)
Definition at line 318 of file hdf5.cc.
References Stats::Hdf5::Hdf5(), OutputDirectory::resolve(), and simout.
Referenced by pybind_init_stats().
initSimStats()
void Stats::initSimStats ()
Definition at line 208 of file stat_control.cc.
Referenced by pybind_init_stats().
initText() [1/2]
Output* Stats::initText (const std::string & filename, bool desc)
initText() [2/2]
Output* Stats::initText (const string & filename, bool desc)
Definition at line 779 of file text.cc.
References Stats::SparseHistPrint::desc, Stats::Text::descriptions, OutputDirectory::findOrCreate(), Stats::Text::open(), simout, and OutputStream::stream().
Referenced by pybind_init_stats().
nameMap()
NameMapType & Stats::nameMap ()
Definition at line 150 of file statistics.cc.
Referenced by validateStatName().
operator*()
Temp Stats::operator* (Temp l, Temp r) inline
Definition at line 3315 of file statistics.hh.
operator+()
Temp Stats::operator+ (Temp l, Temp r) inline
Definition at line 3303 of file statistics.hh.
operator-() [1/2]
Temp Stats::operator- (Temp l, Temp r) inline
Definition at line 3309 of file statistics.hh.
operator-() [2/2]
Temp Stats::operator- (Temp l) inline
Definition at line 3327 of file statistics.hh.
operator/()
Temp Stats::operator/ (Temp l, Temp r) inline
Definition at line 3321 of file statistics.hh.
periodicStatDump()
void Stats::periodicStatDump (Tick period = 0)
Schedule periodic statistics dumping.
This allows you to dump and reset the built-in statistics on a regular basis, thereby allowing the extraction of temporal trends in the data.
Parameters
period The period at which the dumping should occur.
Definition at line 258 of file stat_control.cc.
References curTick(), BaseGlobalEvent::deschedule(), schedStatEvent(), and BaseGlobalEvent::scheduled().
Referenced by pybind_init_stats().
processDumpQueue()
void Stats::processDumpQueue ()
Process all the callbacks in the dump callbacks queue.
Definition at line 532 of file statistics.cc.
References CallbackQueue::process().
Referenced by pybind_init_stats().
processResetQueue()
void Stats::processResetQueue ()
Process all the callbacks in the reset callbacks queue.
Definition at line 526 of file statistics.cc.
References CallbackQueue::process().
Referenced by pybind_init_stats().
pythonDump()
void Stats::pythonDump ()
Definition at line 63 of file stats.cc.
References ArmISA::m.
Referenced by registerPythonStatsHandlers().
pythonReset()
void Stats::pythonReset ()
Definition at line 70 of file stats.cc.
References ArmISA::m.
Referenced by registerPythonStatsHandlers().
registerDumpCallback()
void Stats::registerDumpCallback (Callback * cb)
Register a callback that should be called whenever statistics are about to be dumped.
Definition at line 579 of file statistics.cc.
References CallbackQueue::add().
Referenced by AbstractController::AbstractController(), Network::Network(), and RubySystem::RubySystem().
registerHandlers()
void Stats::registerHandlers (Handler reset_handler, Handler dump_handler)
Definition at line 516 of file statistics.cc.
Referenced by registerPythonStatsHandlers().
registerPythonStatsHandlers()
void Stats::registerPythonStatsHandlers ()
Register py_...
functions as the statistics handlers
Definition at line 50 of file stat_register.cc.
References pythonDump(), pythonReset(), and registerHandlers().
Referenced by pybind_init_stats().
registerResetCallback()
void Stats::registerResetCallback (Callback * cb)
Register a callback that should be called whenever statistics are reset.
Definition at line 538 of file statistics.cc.
References CallbackQueue::add().
Referenced by FunctionProfile::FunctionProfile(), Stats::Global::Global(), and MemFootprintProbe::regStats().
reset()
void Stats::reset ()
Definition at line 570 of file statistics.cc.
References fatal, and resetHandler.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::areaChanged(), sc_gem5::Port::bind(), BaseCache::CacheStats::CacheStats(), DmaReadFifo::DmaDoneEvent::canceled(), DependencyGraph< DynInstPtr >::DependencyGraph(), sc_gem5::Process::disabled(), IdeController::EndBitUnion(), tlm::tlm_generic_payload::has_mm(), RiscvISA::initCPU(), ArmISA::initCPU(), AlphaISA::initCPU(), sc_core::sc_process_handle::operator=(), Stats::StatEvent::process(), sc_gem5::Process::run(), SC_MODULE(), DVFSHandler::UpdateEvent::updatePerfLevel(), WriteAllocator::WriteAllocator(), and IGbE::DescCache< iGbReg::RxDesc >::~DescCache().
schedStatEvent()
void Stats::schedStatEvent (bool dump, bool reset, Tick when = curTick(), Tick repeat = 0)
Schedule statistics dumping.
This allows you to dump and/or reset the built-in statistics. This can either be done once, or it can be done on a regular basis.
Parameters
dump Set true to dump the statistics.
reset Set true to reset the statistics.
when When the dump and/or reset should occur.
repeat How often the event should repeat. Set 0 to disable repeating.
Definition at line 248 of file stat_control.cc.
References simQuantum.
Referenced by doSimLoop(), PseudoInst::dumpresetstats(), PseudoInst::dumpstats(), periodicStatDump(), DumpStatsPCEvent::process(), Stats::StatEvent::process(), pybind_init_stats(), and PseudoInst::resetstats().
statElapsedTicks()
Tick Stats::statElapsedTicks ()
Definition at line 96 of file stat_control.cc.
References curTick(), and startTick.
Referenced by Stats::Global::Global().
statElapsedTime()
double Stats::statElapsedTime ()
Definition at line 86 of file stat_control.cc.
References Time::setTimer(), and statTime.
Referenced by Stats::Global::Global().
statFinalTick()
Tick Stats::statFinalTick ()
Definition at line 102 of file stat_control.cc.
References curTick().
Referenced by Stats::Global::Global().
statsList()
std::list< Info * > & Stats::statsList ()
Definition at line 68 of file statistics.cc.
Referenced by __nan(), pybind_init_stats(), Stats::InfoAccess::setInfo(), and MathExprPowerModel::startup().
statsMap()
MapType & Stats::statsMap ()
Definition at line 75 of file statistics.cc.
Referenced by Stats::InfoAccess::info(), and Stats::InfoAccess::setInfo().
sum()
Temp Stats::sum (Temp val) inline
Definition at line 3347 of file statistics.hh.
References dump(), enable(), enabled(), and Stats::InfoProxy< Stat, Base >::reset().
Referenced by Stats::HistStor::add(), Stats::SampleStor::prepare(), and Stats::AvgSampleStor::prepare().
updateEvents()
void Stats::updateEvents ()
Update the events after resuming from a checkpoint.
When resuming from a checkpoint, curTick will be updated, and any already scheduled events can end up scheduled in the past. This function checks if the dumpEvent is scheduled in the past, and reschedules it appropriately.
Definition at line 288 of file stat_control.cc.
References curTick(), BaseGlobalEvent::reschedule(), BaseGlobalEvent::scheduled(), and BaseGlobalEvent::when().
Referenced by pybind_init_stats().
validateStatName() [1/2]
bool Stats::validateStatName (const string & name)
Definition at line 173 of file statistics.cc.
References ArmISA::c, Stats::Info::name, nameMap(), MipsISA::p, panic, Stats::Info::setName(), and tokenize().
validateStatName() [2/2]
bool Stats::validateStatName (const std::string & name)
ValueToString()
std::string Stats::ValueToString (Result value, int precision)
Definition at line 207 of file text.cc.
References X86ISA::val.
Referenced by Stats::ScalarPrint::operator()().
Variable Documentation
__reserved
const FlagsType Stats::__reserved = init | display
Mask of flags that can't be set directly.
Definition at line 66 of file info.hh.
_enabled
bool Stats::_enabled = false
Definition at line 543 of file statistics.cc.
Referenced by enabled(), CPA::hwWe(), and AnnotateDumpCallback::process().
cdf
const FlagsType Stats::cdf = 0x0040
Print the cumulative percentage of total upto this entry.
Definition at line 55 of file info.hh.
Referenced by Stats::ScalarPrint::operator()(), Stats::VectorPrint::operator()(), and Stats::ScalarPrint::update().
debug_break_id
int Stats::debug_break_id = -1
Definition at line 158 of file statistics.cc.
display
const FlagsType Stats::display = 0x0002
Print this stat.
Definition at line 49 of file info.hh.
Referenced by Stats::Info::baseCheck(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::DataWrap(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::name(), Stats::Text::noOutput(), and SC_MODULE().
dist
const FlagsType Stats::dist = 0x0080
Print the distribution.
Definition at line 57 of file info.hh.
Referenced by Topology::createLinks(), Topology::print(), Random::random(), Minor::MinorStats::regStats(), InstructionQueue< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultCommit< Impl >::regStats(), ArmISA::TableWalker::regStats(), and Topology::shortest_path().
dumpEvent
GlobalEvent* Stats::dumpEvent
Definition at line 74 of file stat_control.cc.
dumpHandler
Handler Stats::dumpHandler = NULL
Definition at line 513 of file statistics.cc.
Referenced by dump().
dumpQueue
CallbackQueue Stats::dumpQueue
Definition at line 522 of file statistics.cc.
init
const FlagsType Stats::init = 0x0001
This Stat is Initialized.
Definition at line 47 of file info.hh.
Referenced by Stats::Info::baseCheck(), FALRU::CacheTracking::CacheTracking(), FastModel::SCGIC::Terminator::countUnbound(), DmaDevice::dmaPending(), ListOperand::getSrcOperand(), sc_core::sc_vector< svp_gicv3_comms::gicv3_comms_target_socket<> >::init(), DRAMCtrl::init(), ImmOperand< SrcCType >::init_from_vect(), init_range(), X86ISA::initCPU(), Minor::MinorDynInst::isMemRef(), PerfectSwitch::name(), MemDepUnit< MemDepPred, Impl >::name(), PioDevice::params(), BaseCPU::params(), RegOrImmOperand< RegOperand, T >::RegOrImmOperand(), SC_MODULE(), sc_core::sc_vector< svp_gicv3_comms::gicv3_comms_target_socket<> >::sc_vector(), Stats::InfoAccess::setInit(), StoreSet::StoreSet(), FastModel::SCGIC::Terminator::Terminator(), and AbstractMemory::~AbstractMemory().
nonan
const FlagsType Stats::nonan = 0x0200
Don't print if this is NAN.
Definition at line 61 of file info.hh.
Referenced by StatTest::init(), Stats::ScalarPrint::operator()(), MemFootprintProbe::regStats(), BaseTags::BaseTagStats::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), AbstractMemory::MemStats::regStats(), ClockedObject::ClockedObjectStats::regStats(), BaseXBar::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), and AlphaISA::Kernel::Statistics::Statistics().
none
const FlagsType Stats::none = 0x0000
Nothing extra to print.
Definition at line 45 of file info.hh.
Referenced by StreamGen::create(), tlm::tlm_event_finder_t< IF, T >::find_event(), sc_core::sc_event_finder_t< sc_core::sc_signal_inout_if< bool > >::find_event(), DistIface::SyncNode::progress(), FlashDevice::regStats(), UFSHostDevice::regStats(), DistIface::SyncNode::requestCkpt(), DistIface::SyncNode::requestExit(), DistIface::SyncNode::run(), DistIface::SyncSwitch::run(), DistIface::SyncNode::SyncNode(), and Terminal::terminalDump().
nozero
const FlagsType Stats::nozero = 0x0100
Don't print if this is zero.
Definition at line 59 of file info.hh.
Referenced by StatTest::init(), BaseXBar::Layer< MasterPort, SlavePort >::Layer(), CommMonitor::MonitorStats::MonitorStats(), Stats::ScalarPrint::operator()(), Stats::VectorPrint::operator()(), Stats::DistPrint::operator()(), StackDistProbe::regStats(), SimpleNetwork::regStats(), MemFootprintProbe::regStats(), Profiler::regStats(), Switch::regStats(), Throttle::regStats(), HDLcd::regStats(), AbstractController::regStats(), Router::regStats(), GarnetNetwork::regStats(), BaseTags::BaseTagStats::regStats(), CacheMemory::regStats(), QoS::MemCtrl::MemCtrlStats::regStats(), MessageBuffer::regStats(), BaseSimpleCPU::regStats(), AbstractMemory::MemStats::regStats(), ClockedObject::ClockedObjectStats::regStats(), BaseXBar::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), UFSHostDevice::regStats(), DRAMCtrl::DRAMStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), and AlphaISA::Kernel::Statistics::Statistics().
oneline
const FlagsType Stats::oneline = 0x0400
Print all values on a single line.
Useful only for histograms.
Definition at line 63 of file info.hh.
Referenced by Stats::VectorPrint::operator()(), Stats::DistPrint::operator()(), Profiler::regStats(), and GarnetNetwork::regStats().
pdf
const FlagsType Stats::pdf = 0x0020
Print the percent of the total that this entry represents.
Definition at line 53 of file info.hh.
Referenced by StatTest::init(), CommMonitor::MonitorStats::MonitorStats(), Stats::ScalarPrint::operator()(), Stats::VectorPrint::operator()(), StackDistProbe::regStats(), Profiler::regStats(), Minor::MinorStats::regStats(), SMMUv3BaseCache::regStats(), GarnetNetwork::regStats(), CacheMemory::regStats(), InstructionQueue< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultCommit< Impl >::regStats(), FlashDevice::regStats(), SMMUv3::regStats(), DefaultFetch< Impl >::regStats(), ClockedObject::ClockedObjectStats::regStats(), WalkCache::regStats(), ArmISA::TableWalker::regStats(), UFSHostDevice::regStats(), AlphaISA::Kernel::Statistics::Statistics(), and Stats::ScalarPrint::update().
resetHandler
Handler Stats::resetHandler = NULL
Definition at line 512 of file statistics.cc.
Referenced by reset().
resetQueue
CallbackQueue Stats::resetQueue
Definition at line 523 of file statistics.cc.
simTicksReset
SimTicksReset Stats::simTicksReset
Definition at line 107 of file stat_control.cc.
startTick
Tick Stats::startTick
Definition at line 72 of file stat_control.cc.
Referenced by statElapsedTicks().
statTime
Time Stats::statTime(true)
Referenced by statElapsedTime().
total
const FlagsType Stats::total = 0x0010
Print the total.
Definition at line 51 of file info.hh.
Referenced by PacketFifo::check(), ROB< Impl >::countInsts(), LSQ< Impl >::getCount(), QueuedPrefetcher::getMaxPermittedPrefetches(), StatTest::init(), QueuedPrefetcher::nextPrefetchReadyTime(), LSQ< Impl >::numFreeLoadEntries(), LSQ< Impl >::numFreeStoreEntries(), LSQ< Impl >::numLoads(), BaseCPU::numSimulatedInsts(), BaseCPU::numSimulatedOps(), LSQ< Impl >::numStores(), Stats::VectorPrint::operator()(), Stats::DistPrint::operator()(), Stats::Formula::operator=(), Minor::MinorStats::regStats(), GarnetNetwork::regStats(), BaseTags::BaseTagStats::regStats(), CacheMemory::regStats(), InstructionQueue< Impl >::regStats(), DefaultRename< Impl >::regStats(), BaseSimpleCPU::regStats(), DefaultIEW< Impl >::regStats(), DefaultCommit< Impl >::regStats(), AbstractMemory::MemStats::regStats(), FullO3CPU< O3CPUImpl >::regStats(), CopyEngine::regStats(), Minor::Fetch2::regStats(), DefaultFetch< Impl >::regStats(), BaseXBar::regStats(), ArmISA::TableWalker::regStats(), BaseCache::CacheStats::regStats(), BaseCache::CacheCmdStats::regStatsFromParent(), SC_MODULE(), AlphaISA::Kernel::Statistics::Statistics(), Stats::VectorBase< Vector, StatStor >::total(), Stats::VectorProxy< Stat >::total(), Stats::Vector2dBase< Vector2d, StatStor >::total(), Stats::UnaryNode< Op >::total(), Stats::BinaryNode< Op >::total(), FullO3CPU< O3CPUImpl >::totalInsts(), FullO3CPU< O3CPUImpl >::totalOps(), Stats::ScalarPrint::update(), and Stats::Text::visit().