gem5: iGbReg::TxdOp Namespace Reference
iGbReg::TxdOp Namespace Reference
Functions
bool isLegacy (TxDesc *d)
uint8_t getType (TxDesc *d)
bool isType (TxDesc *d, uint8_t type)
bool isTypes (TxDesc *d, uint8_t t1, uint8_t t2)
bool isAdvDesc (TxDesc *d)
bool isContext (TxDesc *d)
bool isData (TxDesc *d)
Addr getBuf (TxDesc *d)
Addr getLen (TxDesc *d)
void setDd (TxDesc *d)
bool ide (TxDesc *d)
bool vle (TxDesc *d)
bool rs (TxDesc *d)
bool ic (TxDesc *d)
bool tse (TxDesc *d)
bool ifcs (TxDesc *d)
bool eop (TxDesc *d)
bool ip (TxDesc *d)
bool tcp (TxDesc *d)
uint8_t getCso (TxDesc *d)
uint8_t getCss (TxDesc *d)
bool ixsm (TxDesc *d)
bool txsm (TxDesc *d)
int tucse (TxDesc *d)
int tucso (TxDesc *d)
int tucss (TxDesc *d)
int ipcse (TxDesc *d)
int ipcso (TxDesc *d)
int ipcss (TxDesc *d)
int mss (TxDesc *d)
int hdrlen (TxDesc *d)
int getTsoLen (TxDesc *d)
int utcmd (TxDesc *d)
Variables
const uint8_t TXD_CNXT = 0x0
const uint8_t TXD_DATA = 0x1
const uint8_t TXD_ADVCNXT = 0x2
const uint8_t TXD_ADVDATA = 0x3
Function Documentation
eop()
bool iGbReg::TxdOp::eop (TxDesc * d) inline
Definition at line 262 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, isData(), and isLegacy().
Referenced by IGbE::TxDescCache::pktComplete().
getBuf()
Addr iGbReg::TxdOp::getBuf (TxDesc * d) inline
Definition at line 245 of file i8254xGBe_defs.hh.
References iGbReg::TxDesc::d1, isData(), and isLegacy().
Referenced by IGbE::TxDescCache::getPacketData(), and IGbE::TxDescCache::processContextDesc().
getCso()
uint8_t iGbReg::TxdOp::getCso (TxDesc * d) inline
Definition at line 266 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isLegacy().
getCss()
uint8_t iGbReg::TxdOp::getCss (TxDesc * d) inline
Definition at line 267 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isLegacy().
getLen()
Addr iGbReg::TxdOp::getLen (TxDesc * d) inline
Definition at line 246 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isLegacy().
Referenced by IGbE::TxDescCache::getPacketData(), IGbE::TxDescCache::getPacketSize(), IGbE::TxDescCache::headerComplete(), IGbE::TxDescCache::pktComplete(), and IGbE::TxDescCache::processContextDesc().
getTsoLen()
int iGbReg::TxdOp::getTsoLen (TxDesc * d) inline
Definition at line 286 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isType().
Referenced by IGbE::TxDescCache::processContextDesc().
getType()
uint8_t iGbReg::TxdOp::getType (TxDesc * d) inline
Definition at line 238 of file i8254xGBe_defs.hh.
References bits(), and iGbReg::TxDesc::d2.
Referenced by ide(), and isType().
hdrlen()
int iGbReg::TxdOp::hdrlen (TxDesc * d) inline
Definition at line 279 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, iGbReg::TxDesc::d2, isAdvDesc(), and isContext().
Referenced by iGbReg::Regs::SRRCTL::hdrLen(), and IGbE::TxDescCache::processContextDesc().
ic()
bool iGbReg::TxdOp::ic (TxDesc * d) inline
Definition at line 252 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, isData(), and isLegacy().
Referenced by RiscvISA::ISA::readMiscReg(), ArmISA::ISA::readMiscReg(), and RiscvISA::ISA::setMiscReg().
ide()
bool iGbReg::TxdOp::ide (TxDesc * d) inline
Definition at line 249 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, getType(), and isLegacy().
ifcs()
bool iGbReg::TxdOp::ifcs (TxDesc * d) inline
Definition at line 261 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, isData(), and isLegacy().
ip()
bool iGbReg::TxdOp::ip (TxDesc * d) inline
Definition at line 263 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isContext().
Referenced by Net::hsplit(), Net::operator<<(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), Net::UdpPtr::pstart(), NSGigE::recvPacket(), Sinic::Device::rxKick(), NSGigE::rxKick(), Sinic::Device::transmit(), NSGigE::transmit(), Sinic::Device::txKick(), NSGigE::txKick(), and IGbE::txWire().
ipcse()
int iGbReg::TxdOp::ipcse (TxDesc * d) inline
Definition at line 275 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
ipcso()
int iGbReg::TxdOp::ipcso (TxDesc * d) inline
Definition at line 276 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
ipcss()
int iGbReg::TxdOp::ipcss (TxDesc * d) inline
Definition at line 277 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
isAdvDesc()
bool iGbReg::TxdOp::isAdvDesc (TxDesc * d) inline
Definition at line 241 of file i8254xGBe_defs.hh.
References isLegacy(), and isTypes().
Referenced by hdrlen().
isContext()
bool iGbReg::TxdOp::isContext (TxDesc * d) inline
Definition at line 242 of file i8254xGBe_defs.hh.
References isLegacy(), and isTypes().
Referenced by hdrlen(), ip(), ipcse(), ipcso(), ipcss(), mss(), IGbE::TxDescCache::processContextDesc(), tcp(), tucse(), tucso(), tucss(), and utcmd().
isData()
bool iGbReg::TxdOp::isData (TxDesc * d) inline
Definition at line 243 of file i8254xGBe_defs.hh.
References isLegacy(), and isTypes().
Referenced by eop(), getBuf(), IGbE::TxDescCache::getPacketData(), ic(), ifcs(), ixsm(), IGbE::TxDescCache::pktComplete(), IGbE::TxDescCache::processContextDesc(), txsm(), and vle().
isLegacy()
bool iGbReg::TxdOp::isLegacy (TxDesc * d) inline
Definition at line 237 of file i8254xGBe_defs.hh.
References bits(), and iGbReg::TxDesc::d2.
Referenced by eop(), getBuf(), getCso(), getCss(), getLen(), IGbE::TxDescCache::getPacketData(), ic(), ide(), ifcs(), isAdvDesc(), isContext(), isData(), IGbE::TxDescCache::pktComplete(), and vle().
isType()
bool iGbReg::TxdOp::isType (TxDesc * d, uint8_t type) inline
Definition at line 239 of file i8254xGBe_defs.hh.
References getType(), and type.
Referenced by getTsoLen(), isTypes(), IGbE::TxDescCache::processContextDesc(), and tse().
isTypes()
bool iGbReg::TxdOp::isTypes (TxDesc * d, uint8_t t1, uint8_t t2) inline
Definition at line 240 of file i8254xGBe_defs.hh.
References isType().
Referenced by isAdvDesc(), isContext(), isData(), and tse().
ixsm()
bool iGbReg::TxdOp::ixsm (TxDesc * d) inline
Definition at line 269 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isData().
Referenced by IGbE::TxDescCache::pktComplete().
mss()
int iGbReg::TxdOp::mss (TxDesc * d) inline
Definition at line 278 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isContext().
Referenced by IGbE::TxDescCache::processContextDesc().
rs()
bool iGbReg::TxdOp::rs (TxDesc * d) inline
Definition at line 251 of file i8254xGBe_defs.hh.
References bits(), and iGbReg::TxDesc::d2.
setDd()
void iGbReg::TxdOp::setDd (TxDesc * d) inline
Definition at line 247 of file i8254xGBe_defs.hh.
References iGbReg::TxDesc::d2, replaceBits(), and ULL.
Referenced by IGbE::TxDescCache::pktComplete(), and IGbE::TxDescCache::processContextDesc().
tcp()
bool iGbReg::TxdOp::tcp (TxDesc * d) inline
Definition at line 264 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isContext().
Referenced by Net::hsplit(), IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), IGbE::TxDescCache::processContextDesc(), NSGigE::recvPacket(), Sinic::Device::rxKick(), NSGigE::rxKick(), Sinic::Device::transmit(), NSGigE::transmit(), Sinic::Device::txKick(), and NSGigE::txKick().
tse()
bool iGbReg::TxdOp::tse (TxDesc * d) inline
Definition at line 253 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, isType(), and isTypes().
Referenced by IGbE::TxDescCache::processContextDesc().
tucse()
int iGbReg::TxdOp::tucse (TxDesc * d) inline
Definition at line 272 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
tucso()
int iGbReg::TxdOp::tucso (TxDesc * d) inline
Definition at line 273 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
tucss()
int iGbReg::TxdOp::tucss (TxDesc * d) inline
Definition at line 274 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d1, and isContext().
txsm()
bool iGbReg::TxdOp::txsm (TxDesc * d) inline
Definition at line 270 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isData().
Referenced by IGbE::TxDescCache::pktComplete().
utcmd()
int iGbReg::TxdOp::utcmd (TxDesc * d) inline
Definition at line 287 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, and isContext().
vle()
bool iGbReg::TxdOp::vle (TxDesc * d) inline
Definition at line 250 of file i8254xGBe_defs.hh.
References bits(), iGbReg::TxDesc::d2, isData(), and isLegacy().
Referenced by IGbE::TxDescCache::pktComplete().
Variable Documentation
TXD_ADVCNXT
const uint8_t iGbReg::TxdOp::TXD_ADVCNXT = 0x2
Definition at line 234 of file i8254xGBe_defs.hh.
TXD_ADVDATA
const uint8_t iGbReg::TxdOp::TXD_ADVDATA = 0x3
Definition at line 235 of file i8254xGBe_defs.hh.
Referenced by IGbE::TxDescCache::processContextDesc().
TXD_CNXT
const uint8_t iGbReg::TxdOp::TXD_CNXT = 0x0
Definition at line 232 of file i8254xGBe_defs.hh.
Referenced by IGbE::TxDescCache::processContextDesc().
TXD_DATA
const uint8_t iGbReg::TxdOp::TXD_DATA = 0x1
Definition at line 233 of file i8254xGBe_defs.hh.