gem5: arch/hsail/operand.cc File Reference
operand.cc File Reference
#include "arch/hsail/operand.hh"
Functions
BrigRegOperandInfo findRegDataType (unsigned opOffset, const BrigObject *obj)
Function Documentation
findRegDataType()
BrigRegOperandInfo findRegDataType (unsigned opOffset, const BrigObject * obj)
Definition at line 213 of file operand.cc.
References ArmISA::b, Brig::BRIG_KIND_DIRECTIVE_VARIABLE, Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_CONSTANT_BYTES, Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_KIND_OPERAND_WAVESIZE, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, Brig::BRIG_TYPE_NONE, Brig::BrigData::byteCount, Brig::BrigData::bytes, Brig::BrigOperandOperandList::elements, fatal, BrigObject::getCodeSectionEntry(), BrigObject::getData(), BrigObject::getOperand(), Brig::BrigBase::kind, ArmISA::offset, X86ISA::op, X86ISA::reg, Brig::BrigOperandAddress::reg, Brig::BrigOperandRegister::regKind, Brig::BrigOperandAddress::symbol, type, and Brig::BrigDirectiveVariable::type.
Referenced by BrigRegOperandInfo::BrigRegOperandInfo(), HsailISA::decodeAtomicHelper(), HsailISA::decodeLd(), HsailISA::decodeLd2(), HsailISA::decodeLda(), HsailISA::decodeSt(), and HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::StInst().