gem5: arch/hsail/operand.hh File Reference
operand.hh File Reference
Defines classes encapsulating HSAIL instruction operands.
#include <limits>
#include <string>
#include "arch/hsail/Brig.h"
#include "base/trace.hh"
#include "base/types.hh"
#include "debug/GPUReg.hh"
#include "enums/RegisterType.hh"
#include "gpu-compute/brig_object.hh"
#include "gpu-compute/compute_unit.hh"
#include "gpu-compute/hsail_code.hh"
#include "gpu-compute/shader.hh"
#include "gpu-compute/vector_register_file.hh"
#include "gpu-compute/wavefront.hh"
Classes
class BaseOperand
class BrigRegOperandInfo
class BaseRegOperand
class SRegOperand
class DRegOperand
class CRegOperand
class ImmOperand< T >
class RegOrImmOperand< RegOperand, T >
class AddrOperandBase
class RegAddrOperand< RegOperandType >
class NoRegAddrOperand
class LabelOperand
class ListOperand
class FunctionRefOperand
Typedefs
typedef RegOrImmOperand< SRegOperand, uint32_t > SRegOrImmOperand
typedef RegOrImmOperand< DRegOperand, uint64_t > DRegOrImmOperand
typedef RegOrImmOperand< CRegOperand, bool > CRegOrImmOperand
typedef RegAddrOperand< SRegOperand > SRegAddrOperand
typedef RegAddrOperand< DRegOperand > DRegAddrOperand
Functions
BrigRegOperandInfo findRegDataType (unsigned opOffset, const BrigObject *obj)
Detailed Description
Defines classes encapsulating HSAIL instruction operands.
Definition in file operand.hh.
Typedef Documentation
CRegOrImmOperand
typedef RegOrImmOperand<CRegOperand, bool> CRegOrImmOperand
Definition at line 578 of file operand.hh.
DRegAddrOperand
typedef RegAddrOperand<DRegOperand> DRegAddrOperand
Definition at line 704 of file operand.hh.
DRegOrImmOperand
typedef RegOrImmOperand<DRegOperand, uint64_t> DRegOrImmOperand
Definition at line 577 of file operand.hh.
SRegAddrOperand
typedef RegAddrOperand<SRegOperand> SRegAddrOperand
Definition at line 703 of file operand.hh.
SRegOrImmOperand
typedef RegOrImmOperand<SRegOperand, uint32_t> SRegOrImmOperand
Definition at line 576 of file operand.hh.
Function Documentation
findRegDataType()
BrigRegOperandInfo findRegDataType (unsigned opOffset, const BrigObject * obj)
Definition at line 213 of file operand.cc.
References ArmISA::b, Brig::BRIG_KIND_DIRECTIVE_VARIABLE, Brig::BRIG_KIND_OPERAND_ADDRESS, Brig::BRIG_KIND_OPERAND_CONSTANT_BYTES, Brig::BRIG_KIND_OPERAND_OPERAND_LIST, Brig::BRIG_KIND_OPERAND_REGISTER, Brig::BRIG_KIND_OPERAND_WAVESIZE, Brig::BRIG_REGISTER_KIND_DOUBLE, Brig::BRIG_REGISTER_KIND_SINGLE, Brig::BRIG_TYPE_NONE, Brig::BrigData::byteCount, Brig::BrigData::bytes, Brig::BrigOperandOperandList::elements, fatal, BrigObject::getCodeSectionEntry(), BrigObject::getData(), BrigObject::getOperand(), Brig::BrigBase::kind, ArmISA::offset, X86ISA::op, X86ISA::reg, Brig::BrigOperandAddress::reg, Brig::BrigOperandRegister::regKind, Brig::BrigOperandAddress::symbol, type, and Brig::BrigDirectiveVariable::type.
Referenced by BrigRegOperandInfo::BrigRegOperandInfo(), HsailISA::decodeAtomicHelper(), HsailISA::decodeLd(), HsailISA::decodeLd2(), HsailISA::decodeLda(), HsailISA::decodeSt(), and HsailISA::StInst< MemDataType, SrcDataType, AddrOperandType >::StInst().