gem5: python/pybind11/stats.cc File Reference
stats.cc File Reference
#include "config/use_hdf5.hh"
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "base/statistics.hh"
#include "base/stats/text.hh"
#include "sim/stat_control.hh"
#include "sim/stat_register.hh"
Namespaces
Stats
Functions
void Stats::pythonDump ()
void Stats::pythonReset ()
void pybind_init_stats (py::module &m_native)
Function Documentation
pybind_init_stats()
void pybind_init_stats (py::module & m_native)
Definition at line 79 of file stats.cc.
References Stats::Group::addStatGroup(), Stats::Info::baseCheck(), Stats::Output::begin(), Stats::Output::beginGroup(), Stats::Info::check(), Stats::Info::desc, Stats::Info::enable(), Stats::enable(), Stats::enabled(), Stats::Output::end(), Stats::Output::endGroup(), Stats::Info::flags, Stats::Group::getStatGroups(), Stats::Group::getStats(), Stats::Info::id, Stats::initHDF5(), Stats::initSimStats(), Stats::initText(), ArmISA::m, Stats::Info::name, Stats::periodicStatDump(), Stats::Group::preDumpStats(), Stats::Info::prepare(), Stats::processDumpQueue(), Stats::processResetQueue(), Stats::registerPythonStatsHandlers(), Stats::Group::regStats(), Stats::Info::reset(), Stats::Group::resetStats(), Stats::schedStatEvent(), Stats::statsList(), Stats::updateEvents(), Stats::Output::valid(), Stats::Info::visit(), and Stats::Info::zero().