gem5: python/pybind11/event.cc File Reference
event.cc File Reference
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "base/logging.hh"
#include "sim/eventq.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
#include "sim/simulate.hh"
Classes
class PyEvent
PyBind wrapper for Events.
Macros
#define PRIO(n) c_event.attr(# n) = py::cast((int)Event::n)
Functions
void pybind_init_event (py::module &m_native)
Macro Definition Documentation
PRIO
#define PRIO (n) c_event.attr(# n) = py::cast((int)Event::n)
Referenced by pybind_init_event().
Function Documentation
pybind_init_event()
void pybind_init_event (py::module & m_native)
Definition at line 105 of file event.cc.
References EventBase::CPU_Switch_Pri, EventBase::CPU_Tick_Pri, curEventQueue(), EventBase::Debug_Break_Pri, EventBase::Debug_Enable_Pri, EventBase::Default_Pri, EventBase::Delayed_Writeback_Pri, EventQueue::deschedule(), Event::dump(), EventQueue::dump(), EventBase::DVFS_Update_Pri, ArmISA::e, PowerISA::eq, exitSimLoop(), GlobalSimLoopExitEvent::getCause(), GlobalSimLoopExitEvent::getCode(), getEventQueue(), Event::isExitEvent(), ArmISA::m, EventBase::Maximum_Pri, MaxTick, EventBase::Minimum_Pri, Event::name(), EventQueue::name(), PRIO, Event::priority(), EventBase::Progress_Event_Pri, ArmISA::q, EventQueue::reschedule(), EventQueue::schedule(), Event::scheduled(), EventBase::Serialize_Pri, EventBase::Sim_Exit_Pri, simulate(), Event::squash(), Event::squashed(), EventBase::Stat_Event_Pri, ArmISA::t, and Event::when().
Referenced by EmbeddedPyBind::initAll().