gem5: python/pybind11/debug.cc File Reference
debug.cc File Reference
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include <map>
#include <vector>
#include "base/debug.hh"
#include "base/output.hh"
#include "base/trace.hh"
#include "sim/debug.hh"
Namespaces
Debug
Functions
static void output (const char *filename)
static void ignore (const char *expr)
void pybind_init_debug (py::module &m_native)
Function Documentation
ignore()
static void ignore (const char * expr) static
Definition at line 74 of file debug.cc.
References Trace::Logger::addIgnore(), and Trace::getDebugLogger().
Referenced by SparcISA::TLB::doMmuRegWrite(), and pybind_init_debug().
output()
static void output (const char * filename) static
Definition at line 63 of file debug.cc.
References OutputDirectory::create(), OutputDirectory::find(), Trace::setDebugLogger(), simout, and OutputStream::stream().
Referenced by ArmISA::Crypto::aesFFMul2(), ArmISA::RemoteGDB::availableFeatures(), FDArray::FDArray(), pybind_init_debug(), reverseBits(), SC_MODULE(), BaseRemoteGDB::system(), and TEST().
pybind_init_debug()
void pybind_init_debug (py::module & m_native)
Definition at line 82 of file debug.cc.
References Debug::allFlags(), Debug::allFlagsVersion, clearDebugFlag(), Debug::Flag::desc(), Debug::Flag::disable(), Trace::disable(), dumpDebugFlags(), Debug::Flag::enable(), Trace::enable(), Debug::findFlag(), ignore(), Debug::Flag::kids(), Debug::Flag::name(), output(), schedBreak(), setDebugFlag(), setRemoteGDBPort(), and Debug::Flag::sync().
Referenced by EmbeddedPyBind::initAll().