gem5: python/pybind11/core.cc File Reference
core.cc File Reference
#include "pybind11/pybind11.h"
#include "pybind11/stl.h"
#include "python/pybind11/core.hh"
#include <ctime>
#include "base/addr_range.hh"
#include "base/inet.hh"
#include "base/logging.hh"
#include "base/random.hh"
#include "base/socket.hh"
#include "base/types.hh"
#include "sim/core.hh"
#include "sim/drain.hh"
#include "sim/serialize.hh"
#include "sim/sim_object.hh"
Classes
class PybindSimObjectResolver
Resolve a SimObject name using the Pybind configuration.
Functions
static void init_drain (py::module &m_native)
static void init_serialize (py::module &m_native)
static void init_range (py::module &m_native)
static void init_net (py::module &m_native)
void pybind_init_core (py::module &m_native)
Variables
PybindSimObjectResolver pybindSimObjectResolver
const char * compileDate
const bool flag_DEBUG = false
const bool flag_NDEBUG = false
const bool flag_TRACING_ON = TRACING_ON
Function Documentation
init_drain()
static void init_drain (py::module & m_native) static
Definition at line 100 of file core.cc.
References Drained, Draining, Drainable::drainState(), DrainManager::instance(), DrainManager::isDrained(), ArmISA::m, Drainable::notifyFork(), DrainManager::preCheckpointRestore(), DrainManager::resume(), Running, DrainManager::signalDrainDone(), DrainManager::state(), and DrainManager::tryDrain().
Referenced by pybind_init_core().
init_net()
static void init_net (py::module & m_native) static
Definition at line 180 of file core.cc.
References ArmISA::m.
Referenced by pybind_init_core().
init_range()
static void init_range (py::module & m_native) static
Definition at line 145 of file core.cc.
References AddrRange::end(), AddrRange::granularity(), Stats::init, AddrRange::interleaved(), AddrRange::intersects(), AddrRange::isSubset(), ArmISA::m, AddrRange::mergesWith(), RangeEx(), RangeIn(), RangeSize(), AddrRange::size(), AddrRange::start(), AddrRange::stripes(), AddrRange::to_string(), and AddrRange::valid().
Referenced by pybind_init_core().
init_serialize()
static void init_serialize (py::module & m_native) static
Definition at line 132 of file core.cc.
References ArmISA::m.
Referenced by pybind_init_core().
pybind_init_core()
void pybind_init_core (py::module & m_native)
Definition at line 206 of file core.cc.
References ListenSocket::allDisabled(), clockFrequencyFixed(), compileDate, curTick(), ListenSocket::disableAll(), doExitCleanup(), Logger::FATAL, fixClockFrequency(), flag_DEBUG, flag_NDEBUG, flag_TRACING_ON, getClockFrequency(), Logger::HACK, Logger::INFO, Random::init(), init_drain(), init_net(), init_range(), init_serialize(), ListenSocket::loopbackOnly(), MaxTick, Logger::PANIC, random_mt, Serializable::serializeAll(), setClockFrequency(), Logger::setLevel(), setOutputDir(), ArmISA::t, Serializable::unserializeGlobals(), and Logger::WARN.
Referenced by EmbeddedPyBind::initAll().
Variable Documentation
compileDate
const char* compileDate
Definition at line 31 of file date.cc.
Referenced by pybind_init_core(), and PybindSimObjectResolver::resolveSimObject().
flag_DEBUG
const bool flag_DEBUG = false
Definition at line 90 of file core.cc.
Referenced by pybind_init_core(), and PybindSimObjectResolver::resolveSimObject().
flag_NDEBUG
const bool flag_NDEBUG = false
Definition at line 95 of file core.cc.
Referenced by pybind_init_core().
flag_TRACING_ON
const bool flag_TRACING_ON = TRACING_ON
Definition at line 97 of file core.cc.
Referenced by pybind_init_core().
pybindSimObjectResolver
PybindSimObjectResolver pybindSimObjectResolver
Definition at line 73 of file core.cc.