gem5: mem/ruby/slicc_interface/RubySlicc_Util.hh File Reference
RubySlicc_Util.hh File Reference
#include <cassert>
#include "debug/RubySlicc.hh"
#include "mem/packet.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/BoolVec.hh"
#include "mem/ruby/common/DataBlock.hh"
#include "mem/ruby/common/TypeDefines.hh"
#include "mem/ruby/common/WriteMask.hh"
Functions
Cycles zero_time ()
NodeID intToID (int nodenum)
int IDToInt (NodeID id)
int addressToInt (Addr addr)
Addr intToAddress (int addr)
int mod (int val, int mod)
int max_tokens ()
bool testAndRead (Addr addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
bool testAndReadMask (Addr addr, DataBlock &blk, WriteMask &mask, Packet *pkt)
This function accepts an address, a data block, a write mask and a packet.
bool testAndWrite (Addr addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
int countBoolVec (BoolVec bVec)
Function Documentation
addressToInt()
int addressToInt (Addr addr) inline
Definition at line 64 of file RubySlicc_Util.hh.
References addr.
countBoolVec()
int countBoolVec (BoolVec bVec) inline
Definition at line 175 of file RubySlicc_Util.hh.
References X86ISA::count.
IDToInt()
int IDToInt (NodeID id) inline
Definition at line 57 of file RubySlicc_Util.hh.
References ArmISA::id.
intToAddress()
Addr intToAddress (int addr) inline
Definition at line 71 of file RubySlicc_Util.hh.
References addr.
intToID()
NodeID intToID (int nodenum) inline
Definition at line 50 of file RubySlicc_Util.hh.
References ArmISA::id.
max_tokens()
int max_tokens () inline
Definition at line 83 of file RubySlicc_Util.hh.
mod()
int mod (int val, int mod) inline
Definition at line 78 of file RubySlicc_Util.hh.
Referenced by sc_gem5::pickParentModule(), sc_core::sc_gen_unique_name(), sc_core::sc_module_sc_new(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_b_transport_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_b_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_get_direct_mem_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_get_direct_mem_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_invalidate_direct_mem_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_nb_transport_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_nb_transport_ptr(), tlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr(), tlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_dbg_ptr(), tlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::set_transport_dbg_ptr(), tlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr(), and tlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process::set_transport_ptr().
testAndRead()
bool testAndRead (Addr addr, DataBlock & blk, Packet * pkt) inline
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to read, then the data from the data block is written to the packet. True is returned if the data block was read, otherwise false is returned.
This is used during a functional access "search the world" operation. The functional access looks in every place that might hold a valid data block and, if it finds one, checks to see if it is holding the address the access is searching for. During the access check, the WriteMask could be in any state, including empty.
Definition at line 101 of file RubySlicc_Util.hh.
References data, Packet::getAddr(), DataBlock::getByte(), Packet::getPtr(), Packet::getSize(), ArmISA::i, and makeLineAddress().
testAndReadMask()
bool testAndReadMask (Addr addr, DataBlock & blk, WriteMask & mask, Packet * pkt) inline
This function accepts an address, a data block, a write mask and a packet.
If the valid address range for the data block contains the address which the packet needs to read, then the data from the data block is written to the packet. True is returned if any part of the data block was read, otherwise false is returned.
Definition at line 127 of file RubySlicc_Util.hh.
References data, Packet::getAddr(), DataBlock::getByte(), Packet::getPtr(), Packet::getSize(), ArmISA::i, makeLineAddress(), and WriteMask::test().
testAndWrite()
bool testAndWrite (Addr addr, DataBlock & blk, Packet * pkt) inline
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to write, then the data from the packet is written to the data block. True is returned if the data block was written, otherwise false is returned.
Definition at line 156 of file RubySlicc_Util.hh.
References data, Packet::getAddr(), Packet::getConstPtr(), Packet::getSize(), ArmISA::i, makeLineAddress(), and DataBlock::setByte().
zero_time()
Cycles zero_time () inline
Definition at line 47 of file RubySlicc_Util.hh.