gem5: sim/serialize.cc File Reference
serialize.cc File Reference
#include "sim/serialize.hh"
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <cerrno>
#include <fstream>
#include <list>
#include <string>
#include <vector>
#include "base/inifile.hh"
#include "base/output.hh"
#include "base/trace.hh"
#include "debug/Checkpoint.hh"
#include "sim/eventq.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
#include "sim/sim_object.hh"
#include "sim/stat_control.hh"
Classes
class Globals
Container for serializing global variables (not associated with any serialized object).
Functions
void objParamIn (CheckpointIn &cp, const string &name, SimObject *&param)
void debug_serialize (const string &cpt_dir)
Variables
Globals globals
The one and only instance of the Globals class.
std::set< std::string > version_tags
The version tags for this build of the simulator, to be stored in the Globals section during serialization and compared upon unserialization.
Function Documentation
debug_serialize()
void debug_serialize (const string & cpt_dir)
Definition at line 328 of file serialize.cc.
References Serializable::serializeAll().
objParamIn()
void objParamIn (CheckpointIn & cp, const string & name, SimObject *& param)
Definition at line 319 of file serialize.cc.
References Serializable::currentSection(), fatal, and CheckpointIn::findObj().
Referenced by AnnotateDumpCallback::process().
Variable Documentation
globals
Globals globals
The one and only instance of the Globals class.
Definition at line 96 of file serialize.cc.
Referenced by main(), and py_interact().
version_tags
std::set<std::string> version_tags
The version tags for this build of the simulator, to be stored in the Globals section during serialization and compared upon unserialization.
Referenced by Globals::serialize(), and Globals::unserialize().