gem5: sim/core.cc File Reference
core.cc File Reference
#include "sim/core.hh"
#include <iostream>
#include <string>
#include "base/callback.hh"
#include "base/cprintf.hh"
#include "base/logging.hh"
#include "base/output.hh"
#include "sim/eventq.hh"
Namespaces
SimClock
These are variables that are set based on the simulator frequency.
SimClock::Float
SimClock::Int
These variables equal the number of ticks in the unit of time they're named after in a 64 bit integer.
Functions
void fixClockFrequency ()
bool clockFrequencyFixed ()
void setClockFrequency (Tick tps)
Tick getClockFrequency ()
void setOutputDir (const string &dir)
CallbackQueue & exitCallbacks ()
Queue of C++ callbacks to invoke on simulator exit.
void registerExitCallback (Callback *callback)
Register an exit callback.
void doExitCleanup ()
Do C++ simulator exit processing.
Variables
Tick SimClock::Frequency
The simulated frequency of curTick(). (In ticks per second)
Tick SimClock::Int::s
second
Tick SimClock::Int::ms
millisecond
Tick SimClock::Int::us
microsecond
Tick SimClock::Int::ns
nanosecond
Tick SimClock::Int::ps
picosecond
double SimClock::Float::s
These variables equal the number of ticks in the unit of time they're named after in a double.
double SimClock::Float::ms
millisecond
double SimClock::Float::us
microsecond
double SimClock::Float::ns
nanosecond
double SimClock::Float::ps
picosecond
double SimClock::Float::Hz
These variables the inverse of above.
double SimClock::Float::kHz
kHz
double SimClock::Float::MHz
MHz.
double SimClock::Float::GHz
GHz.
Function Documentation
clockFrequencyFixed()
bool clockFrequencyFixed ()
Definition at line 112 of file core.cc.
Referenced by pybind_init_core(), sc_core::sc_set_default_time_unit(), and sc_core::sc_set_time_resolution().
doExitCleanup()
void doExitCleanup ()
Do C++ simulator exit processing.
Exported to Python to be invoked when simulator terminates via Python's atexit mechanism.
Definition at line 153 of file core.cc.
References CallbackQueue::clear(), exitCallbacks(), and CallbackQueue::process().
Referenced by pybind_init_core().
exitCallbacks()
CallbackQueue& exitCallbacks () inline
Queue of C++ callbacks to invoke on simulator exit.
Definition at line 133 of file core.cc.
Referenced by doExitCleanup(), and registerExitCallback().
fixClockFrequency()
void fixClockFrequency ()
Definition at line 84 of file core.cc.
References cprintf(), SimClock::Frequency, SimClock::Float::GHz, SimClock::Float::Hz, SimClock::Float::kHz, SimClock::Float::MHz, SimClock::Int::ms, SimClock::Int::ns, SimClock::Int::ps, SimClock::Int::s, and SimClock::Int::us.
Referenced by sc_core::sc_time::from_value(), and pybind_init_core().
getClockFrequency()
Tick getClockFrequency ()
Definition at line 121 of file core.cc.
Referenced by pybind_init_core().
registerExitCallback()
void registerExitCallback (Callback * callback)
Register an exit callback.
Register a callback to be called when Python exits.
Definition at line 143 of file core.cc.
References CallbackQueue::add(), and exitCallbacks().
Referenced by BaseTags::BaseTags(), ComputeUnit::ComputeUnit(), CowDiskImage::CowDiskImage(), Trace::InstPBTrace::createTraceFile(), DRAMSim2::DRAMSim2(), ElasticTrace::ElasticTrace(), MemTraceProbe::MemTraceProbe(), O3ThreadState< Impl >::O3ThreadState(), AnnotateDumpCallback::process(), SimpleThread::SimpleThread(), and VirtIO9PDiod::VirtIO9PDiod().
setClockFrequency()
void setClockFrequency (Tick tps)
Definition at line 115 of file core.cc.
References panic_if.
Referenced by pybind_init_core(), and sc_core::sc_set_time_resolution().
setOutputDir()
void setOutputDir (const string & dir)
Definition at line 124 of file core.cc.
References OutputDirectory::setDirectory(), and simout.
Referenced by pybind_init_core().