gem5: sim/sim_exit.hh File Reference
sim_exit.hh File Reference
#include <string>
#include "base/types.hh"
Functions
Tick curTick ()
The universal simulation clock.
void registerExitCallback (Callback *)
Register a callback to be called when Python exits.
void exitSimLoop (const std::string &message, int exit_code=0, Tick when=curTick(), Tick repeat=0, bool serialize=false)
Schedule an event to exit the simulation loop (returning to Python) at the end of the current cycle (curTick()).
void exitSimLoopNow (const std::string &message, int exit_code=0, Tick repeat=0, bool serialize=false)
Schedule an event as above, but make it high priority so it runs before any normal events which are schedule at the current time.
Function Documentation
curTick()
Tick curTick () inline
The universal simulation clock.
The current simulated tick.
Definition at line 47 of file core.hh.
References _curEventQueue, and EventQueue::getCurTick().
exitSimLoop()
void exitSimLoop (const std::string & message, int exit_code = 0, Tick when = curTick(), Tick repeat = 0, bool serialize = false)
Schedule an event to exit the simulation loop (returning to Python) at the end of the current cycle (curTick()).
The message and exit_code parameters are saved in the SimLoopExitEvent to indicate why the exit occurred.
Definition at line 90 of file sim_events.cc.
References curTick(), GlobalSimLoopExitEvent::GlobalSimLoopExitEvent(), simQuantum, and warn_if.
Referenced by TraceCPU::checkAndSchedExitEvent(), MemTest::completeRequest(), doSimLoop(), Trace::TarmacParserRecord::dump(), ExitGen::enter(), exitImpl(), GoodbyeObject::fillBuffer(), BaseCache::incMissCount(), PseudoInst::m5checkpoint(), PseudoInst::m5exit(), PseudoInst::m5fail(), LocalSimLoopExitEvent::process(), Trace::TarmacParserRecord::TarmacParserRecordEvent::process(), CountedExitEvent::process(), DistIface::SyncEvent::process(), pybind_init_event(), DistIface::recvThreadFunc(), ArmSemihosting::semiExit(), TCPIface::sendTCP(), DrainManager::signalDrainDone(), PseudoInst::switchcpu(), takeCheckpoint(), GarnetSyntheticTraffic::tick(), RubyDirectedTester::wakeup(), RubyTester::wakeup(), PseudoInst::workbegin(), PseudoInst::workend(), SimpleUart::write(), and Pl011::write().
exitSimLoopNow()
void exitSimLoopNow (const std::string & message, int exit_code = 0, Tick repeat = 0, bool serialize = false)
Schedule an event as above, but make it high priority so it runs before any normal events which are schedule at the current time.
Definition at line 101 of file sim_events.cc.
References GlobalSimLoopExitEvent::GlobalSimLoopExitEvent().
Referenced by sc_gem5::Scheduler::pause(), and sc_gem5::Scheduler::stop().
registerExitCallback()
void registerExitCallback (Callback * callback)
Register a callback to be called when Python exits.
Defined in sim/main.cc.
Register a callback to be called when Python exits.
Definition at line 143 of file core.cc.
References CallbackQueue::add(), and exitCallbacks().
Referenced by BaseTags::BaseTags(), ComputeUnit::ComputeUnit(), CowDiskImage::CowDiskImage(), Trace::InstPBTrace::createTraceFile(), DRAMSim2::DRAMSim2(), ElasticTrace::ElasticTrace(), MemTraceProbe::MemTraceProbe(), O3ThreadState< Impl >::O3ThreadState(), AnnotateDumpCallback::process(), SimpleThread::SimpleThread(), and VirtIO9PDiod::VirtIO9PDiod().