gem5: X86ISA::EmulEnv Struct Reference
X86ISA::EmulEnv Struct Reference
#include <emulenv.hh>
Public Member Functions
EmulEnv (RegIndex _reg, RegIndex _regm, int _dataSize, int _addressSize, int _stackSize)
void doModRM (const ExtMachInst &machInst)
void setSeg (const ExtMachInst &machInst)
Public Attributes
RegIndex reg
RegIndex regm
SegmentRegIndex seg
uint8_t scale
RegIndex index
RegIndex base
int dataSize
int addressSize
int stackSize
Detailed Description
Definition at line 50 of file emulenv.hh.
Constructor & Destructor Documentation
EmulEnv()
X86ISA::EmulEnv::EmulEnv (RegIndex _reg, RegIndex _regm, int _dataSize, int _addressSize, int _stackSize) inline
Definition at line 62 of file emulenv.hh.
References doModRM(), and setSeg().
Member Function Documentation
doModRM()
void EmulEnv::doModRM (const ExtMachInst & machInst)
Definition at line 48 of file emulenv.cc.
References X86ISA::ExtMachInst::addrSize, base, X86ISA::ExtMachInst::dispSize, index, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::modRM, ArmISA::NUM_INTREGS, X86ISA::ExtMachInst::rex, X86ISA::rm, scale, seg, X86ISA::SEGMENT_REG_DS, X86ISA::SEGMENT_REG_SS, and X86ISA::ExtMachInst::sib.
Referenced by EmulEnv().
setSeg()
void EmulEnv::setSeg (const ExtMachInst & machInst)
Definition at line 115 of file emulenv.cc.
References X86ISA::ExtMachInst::legacy, seg, and X86ISA::SEGMENT_REG_DS.
Referenced by EmulEnv().
Member Data Documentation
addressSize
int X86ISA::EmulEnv::addressSize
Definition at line 59 of file emulenv.hh.
base
RegIndex X86ISA::EmulEnv::base
Definition at line 57 of file emulenv.hh.
Referenced by doModRM().
dataSize
int X86ISA::EmulEnv::dataSize
Definition at line 58 of file emulenv.hh.
index
RegIndex X86ISA::EmulEnv::index
Definition at line 56 of file emulenv.hh.
Referenced by doModRM().
reg
RegIndex X86ISA::EmulEnv::reg
Definition at line 52 of file emulenv.hh.
regm
RegIndex X86ISA::EmulEnv::regm
Definition at line 53 of file emulenv.hh.
scale
uint8_t X86ISA::EmulEnv::scale
Definition at line 55 of file emulenv.hh.
Referenced by doModRM().
seg
SegmentRegIndex X86ISA::EmulEnv::seg
Definition at line 54 of file emulenv.hh.
Referenced by doModRM(), and setSeg().
stackSize
int X86ISA::EmulEnv::stackSize
Definition at line 60 of file emulenv.hh.
The documentation for this struct was generated from the following files:
arch/x86/emulenv.hh
arch/x86/emulenv.cc