gem5: Net::UdpHdr Struct Reference
Net::UdpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint16_t sport () const
uint16_t dport () const
uint16_t len () const
uint16_t sum () const
void sum (uint16_t sum)
void len (uint16_t _len)
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 614 of file inet.hh.
Member Function Documentation
bytes() [1/2]
const uint8_t* Net::UdpHdr::bytes () const inline
Definition at line 625 of file inet.hh.
bytes() [2/2]
uint8_t* Net::UdpHdr::bytes () inline
Definition at line 627 of file inet.hh.
dport()
uint16_t Net::UdpHdr::dport () const inline
Definition at line 617 of file inet.hh.
len() [1/2]
uint16_t Net::UdpHdr::len () const inline
Definition at line 618 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete().
len() [2/2]
void Net::UdpHdr::len (uint16_t _len) inline
Definition at line 622 of file inet.hh.
payload() [1/2]
const uint8_t* Net::UdpHdr::payload () const inline
Definition at line 626 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
payload() [2/2]
uint8_t* Net::UdpHdr::payload () inline
Definition at line 628 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
size()
int Net::UdpHdr::size () const inline
Definition at line 624 of file inet.hh.
sport()
uint16_t Net::UdpHdr::sport () const inline
Definition at line 616 of file inet.hh.
sum() [1/2]
uint16_t Net::UdpHdr::sum () const inline
Definition at line 619 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete(), Sinic::Device::txKick(), and NSGigE::txKick().
sum() [2/2]
void Net::UdpHdr::sum (uint16_t sum) inline
Definition at line 621 of file inet.hh.
References sum().
Referenced by sum().
The documentation for this struct was generated from the following file:
base/inet.hh