gem5: Net::Ip6Opt Struct Reference
Net::Ip6Opt Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t nxt () const
uint8_t extlen () const
uint8_t len () const
uint8_t rtType2Type () const
uint8_t rtType2SegLft () const
const uint8_t * rtType2Addr () const
uint16_t fragmentOfflg () const
uint32_t fragmentIdent () const
uint8_t dstOptType () const
uint8_t dstOptLength () const
const uint8_t * dstOptAddr () const
Additional Inherited Members
Public Attributes inherited from Net::ip6_opt_hdr
uint8_t ext_nxt
uint8_t ext_len
union {
struct ip6_opt_fragment fragment
struct ip6_opt_routing_type2 rtType2
struct ip6_opt_dstopts dstOpts
} ext_data
Detailed Description
Definition at line 481 of file inet.hh.
Member Function Documentation
dstOptAddr()
const uint8_t* Net::Ip6Opt::dstOptAddr () const inline
Definition at line 502 of file inet.hh.
References ext_data.
dstOptLength()
uint8_t Net::Ip6Opt::dstOptLength () const inline
Definition at line 501 of file inet.hh.
References ext_data.
dstOptType()
uint8_t Net::Ip6Opt::dstOptType () const inline
Definition at line 500 of file inet.hh.
References ext_data.
extlen()
uint8_t Net::Ip6Opt::extlen () const inline
Definition at line 484 of file inet.hh.
References ext_len.
fragmentIdent()
uint32_t Net::Ip6Opt::fragmentIdent () const inline
Definition at line 497 of file inet.hh.
References ext_data.
fragmentOfflg()
uint16_t Net::Ip6Opt::fragmentOfflg () const inline
Definition at line 496 of file inet.hh.
References ext_data.
len()
uint8_t Net::Ip6Opt::len () const inline
Definition at line 485 of file inet.hh.
Referenced by Net::Ip6Hdr::extensionLength(), Net::Ip6Hdr::getExt(), and Net::Ip6Hdr::proto().
nxt()
uint8_t Net::Ip6Opt::nxt () const inline
Definition at line 483 of file inet.hh.
References ext_nxt.
Referenced by Net::Ip6Hdr::extensionLength(), Net::Ip6Hdr::getExt(), and Net::Ip6Hdr::proto().
rtType2Addr()
const uint8_t* Net::Ip6Opt::rtType2Addr () const inline
Definition at line 493 of file inet.hh.
References ext_data.
rtType2SegLft()
uint8_t Net::Ip6Opt::rtType2SegLft () const inline
Definition at line 492 of file inet.hh.
References ext_data.
rtType2Type()
uint8_t Net::Ip6Opt::rtType2Type () const inline
Definition at line 491 of file inet.hh.
References ext_data.
The documentation for this struct was generated from the following file:
base/inet.hh