gem5: TAGE::TageBranchInfo Struct Reference
TAGE::TageBranchInfo Struct Reference
#include <tage.hh>
Public Member Functions
TageBranchInfo (TAGEBase &tage)
virtual ~TageBranchInfo ()
Public Attributes
TAGEBase::BranchInfo * tageBranchInfo
Detailed Description
Definition at line 66 of file tage.hh.
Constructor & Destructor Documentation
TageBranchInfo()
TAGE::TageBranchInfo::TageBranchInfo (TAGEBase & tage) inline
Definition at line 69 of file tage.hh.
~TageBranchInfo()
virtual TAGE::TageBranchInfo::~TageBranchInfo () inline virtual
Definition at line 72 of file tage.hh.
References ArmISA::b, TAGE::btbUpdate(), TAGE::lookup(), MaxAddr, SimObject::params(), TAGE::predict(), TAGE::squash(), TAGE::TAGE(), tageBranchInfo, TAGE::uncondBranch(), and TAGE::update().
Member Data Documentation
tageBranchInfo
TAGEBase::BranchInfo* TAGE::TageBranchInfo::tageBranchInfo
Definition at line 67 of file tage.hh.
Referenced by TAGE::btbUpdate(), TAGE::lookup(), TAGE::predict(), TAGE::squash(), TAGE::uncondBranch(), TAGE::update(), and ~TageBranchInfo().
The documentation for this struct was generated from the following file:
cpu/pred/tage.hh