gem5: Net::IpAddress Struct Reference
Net::IpAddress Struct Reference
#include <inet.hh>
Public Member Functions
IpAddress ()
IpAddress (const uint32_t __ip)
uint32_t ip () const
std::string string () const
Protected Attributes
uint32_t _ip
Detailed Description
Definition at line 193 of file inet.hh.
Constructor & Destructor Documentation
IpAddress() [1/2]
Net::IpAddress::IpAddress () inline
Definition at line 199 of file inet.hh.
IpAddress() [2/2]
Net::IpAddress::IpAddress (const uint32_t __ip) inline
Definition at line 201 of file inet.hh.
Member Function Documentation
ip()
uint32_t Net::IpAddress::ip () const inline
Definition at line 204 of file inet.hh.
References MipsISA::ia, Net::operator<<(), Net::operator==(), and Net::EthAddr::string().
Referenced by Net::operator<<(), and Net::operator==().
string()
string Net::IpAddress::string () const
Definition at line 141 of file inet.cc.
Member Data Documentation
_ip
uint32_t Net::IpAddress::_ip protected
Definition at line 196 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc