gem5: AlphaBackdoor::Access Struct Reference
AlphaBackdoor::Access Struct Reference
#include <backdoor.hh>
Public Member Functions
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Public Attributes inherited from AlphaAccess
uint32_t last_offset
uint32_t version
uint32_t numCPUs
uint32_t intrClockFrequency
uint64_t cpuClock
uint64_t mem_size
uint64_t kernStart
uint64_t kernEnd
uint64_t entryPoint
uint64_t diskUnit
uint64_t diskCount
uint64_t diskPAddr
uint64_t diskBlock
uint64_t diskOperation
uint64_t outputChar
uint64_t inputChar
uint64_t cpuStack [64]
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 77 of file backdoor.hh.
Member Function Documentation
serialize()
void AlphaBackdoor::Access::serialize (CheckpointOut & cp) const override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 256 of file backdoor.cc.
References ArmISA::numCPUs, SERIALIZE_ARRAY, and SERIALIZE_SCALAR.
Referenced by AlphaBackdoor::params(), and AlphaBackdoor::serialize().
unserialize()
void AlphaBackdoor::Access::unserialize (CheckpointIn & cp) override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 278 of file backdoor.cc.
References ArmISA::numCPUs, UNSERIALIZE_ARRAY, and UNSERIALIZE_SCALAR.
Referenced by AlphaBackdoor::params(), and AlphaBackdoor::unserialize().
The documentation for this struct was generated from the following files:
dev/alpha/backdoor.hh
dev/alpha/backdoor.cc