gem5: tlm_utils::time_ordered_list< PAYLOAD >::element Struct Reference
tlm_utils::time_ordered_list< PAYLOAD >::element Struct Reference
#include <peq_with_cb_and_phase.h>
Public Member Functions
element (PAYLOAD &p, sc_core::sc_time t, sc_dt::uint64 d)
element ()
Public Attributes
struct element * next
PAYLOAD p
sc_core::sc_time t
sc_dt::uint64 d
Detailed Description
template<typename PAYLOAD>
struct tlm_utils::time_ordered_list< PAYLOAD >::element
Definition at line 39 of file peq_with_cb_and_phase.h.
Constructor & Destructor Documentation
element() [1/2]
template<typename PAYLOAD> tlm_utils::time_ordered_list< PAYLOAD >::element::element (PAYLOAD & p, sc_core::sc_time t, sc_dt::uint64 d) inline
Definition at line 45 of file peq_with_cb_and_phase.h.
element() [2/2]
template<typename PAYLOAD> tlm_utils::time_ordered_list< PAYLOAD >::element::element () inline
Definition at line 48 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::time_ordered_list< std::pair >::delete_top(), tlm_utils::time_ordered_list< std::pair >::insert(), and tlm_utils::time_ordered_list< std::pair >::~time_ordered_list().
Member Data Documentation
d
template<typename PAYLOAD> sc_dt::uint64 tlm_utils::time_ordered_list< PAYLOAD >::element::d
Definition at line 44 of file peq_with_cb_and_phase.h.
next
template<typename PAYLOAD> struct element* tlm_utils::time_ordered_list< PAYLOAD >::element::next
Definition at line 41 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::time_ordered_list< std::pair >::delete_top(), and tlm_utils::time_ordered_list< std::pair >::insert().
p
template<typename PAYLOAD> PAYLOAD tlm_utils::time_ordered_list< PAYLOAD >::element::p
Definition at line 42 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::time_ordered_list< std::pair >::insert(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::delta_list::insert().
t
template<typename PAYLOAD> sc_core::sc_time tlm_utils::time_ordered_list< PAYLOAD >::element::t
Definition at line 43 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::time_ordered_list< std::pair >::insert().
The documentation for this struct was generated from the following file:
systemc/ext/tlm_utils/peq_with_cb_and_phase.h