gem5: Trace::TarmacTracerRecord::TraceInstEntry Struct Reference
Trace::TarmacTracerRecord::TraceInstEntry Struct Reference
Instruction Entry.
#include <tarmac_record.hh>
Public Member Functions
TraceInstEntry (const TarmacContext &tarmCtx, bool predicate)
virtual void print (std::ostream &outs, int verbosity=0, const std::string &prefix="") const override
Public Member Functions inherited from Printable
Printable ()
virtual ~Printable ()
Protected Attributes
bool secureMode
True if instruction is executed in secure mode.
uint8_t instSize
Instruction size: 16 for 16-bit Thumb Instruction 32 otherwise (ARM and BigThumb)
Static Protected Attributes
static uint64_t instCount = 0
Number of instructions being traced.
Detailed Description
Instruction Entry.
Definition at line 95 of file tarmac_record.hh.
Constructor & Destructor Documentation
TraceInstEntry()
Trace::TarmacTracerRecord::TraceInstEntry::TraceInstEntry (const TarmacContext & tarmCtx, bool predicate)
Definition at line 118 of file tarmac_record.cc.
References RefCountingPtr< T >::get(), ArmISA::inSecureState(), instCount, instSize, ArmISA::opcode, secureMode, Trace::TarmacContext::staticInst, and Trace::TarmacContext::thread.
Member Function Documentation
print()
void Trace::TarmacTracerRecord::TraceInstEntry::print (std::ostream & outs, int verbosity = 0, const std::string & prefix = "") const override virtual
Implements Printable.
Reimplemented in Trace::TarmacTracerRecordV8::TraceInstEntryV8.
Definition at line 409 of file tarmac_record.cc.
References Trace::InstRecord::addr, ccprintf(), csprintf(), curTick(), Trace::TarmacBaseRecord::RegEntry::isetstate, Trace::iSetStateToStr(), ArmISA::mode, ArmISA::opcode, and Trace::opModeToStr().
Member Data Documentation
instCount
uint64_t Trace::TarmacTracerRecord::TraceInstEntry::instCount = 0 static protected
Number of instructions being traced.
Definition at line 105 of file tarmac_record.hh.
Referenced by TraceInstEntry().
instSize
uint8_t Trace::TarmacTracerRecord::TraceInstEntry::instSize protected
Instruction size: 16 for 16-bit Thumb Instruction 32 otherwise (ARM and BigThumb)
Definition at line 114 of file tarmac_record.hh.
Referenced by TraceInstEntry().
secureMode
bool Trace::TarmacTracerRecord::TraceInstEntry::secureMode protected
True if instruction is executed in secure mode.
Definition at line 108 of file tarmac_record.hh.
Referenced by TraceInstEntry().
The documentation for this struct was generated from the following files:
arch/arm/tracers/tarmac_record.hh
arch/arm/tracers/tarmac_record.cc