gem5: X86ISA::Walker::WalkerSenderState Struct Reference
X86ISA::Walker::WalkerSenderState Struct Reference
#include <pagetable_walker.hh>
Public Member Functions
WalkerSenderState (WalkerState *_senderWalk)
Public Member Functions inherited from Packet::SenderState
SenderState ()
virtual ~SenderState ()
Public Attributes
WalkerState * senderWalk
Public Attributes inherited from Packet::SenderState
SenderState * predecessor
Detailed Description
Definition at line 153 of file pagetable_walker.hh.
Constructor & Destructor Documentation
WalkerSenderState()
X86ISA::Walker::WalkerSenderState::WalkerSenderState (WalkerState * _senderWalk) inline
Definition at line 156 of file pagetable_walker.hh.
References X86ISA::addr, X86ISA::Walker::getPort(), InvalidPortID, ArmISA::mode, X86ISA::Walker::start(), and X86ISA::Walker::startFunctional().
Member Data Documentation
senderWalk
WalkerState* X86ISA::Walker::WalkerSenderState::senderWalk
Definition at line 155 of file pagetable_walker.hh.
Referenced by X86ISA::Walker::recvTimingResp().
The documentation for this struct was generated from the following file:
arch/x86/pagetable_walker.hh