gem5: O3ThreadState< Impl > Struct Template Reference
O3ThreadState< Impl > Struct Template Reference
Class that has various thread state, such as the status, the current instruction being processed, whether or not the thread has a trap pending or is being externally updated, the ThreadContext pointer, etc.
#include <commit.hh>
Public Types
typedef ThreadContext::Status Status
typedef Impl::O3CPU O3CPU
Public Types inherited from ThreadState
typedef ThreadContext::Status Status
Public Member Functions
O3ThreadState (O3CPU *_cpu, int _thread_num, Process *_process)
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
ThreadContext * getTC ()
Returns a pointer to the TC of this thread.
void syscall (int64_t callnum, Fault *fault)
Handles the syscall.
void dumpFuncProfile ()
Public Member Functions inherited from ThreadState
ThreadState (BaseCPU *cpu, ThreadID _tid, Process *_process)
virtual ~ThreadState ()
void serialize (CheckpointOut &cp) const override
Serialize an object.
void unserialize (CheckpointIn &cp) override
Unserialize an object.
int cpuId () const
uint32_t socketId () const
ContextID contextId () const
void setContextId (ContextID id)
void setThreadId (ThreadID id)
ThreadID threadId () const
Tick readLastActivate () const
Tick readLastSuspend () const
void initMemProxies (ThreadContext *tc)
Initialise the physical and virtual port proxies and tie them to the data port of the CPU.
void dumpFuncProfile ()
EndQuiesceEvent * getQuiesceEvent ()
void profileClear ()
void profileSample ()
Kernel::Statistics * getKernelStats ()
PortProxy & getPhysProxy ()
PortProxy & getVirtProxy ()
Process * getProcessPtr ()
void setProcessPtr (Process *p)
Counter readFuncExeInst () const
Reads the number of instructions functionally executed and committed.
void setFuncExeInst (Counter new_val)
Sets the total number of instructions functionally executed and committed.
Status status () const
Returns the status of this thread.
void setStatus (Status new_status)
Sets the status of this thread.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
PCEventQueue pcEventQueue
EventQueue comInstEventQueue
An instruction-based event queue.
bool noSquashFromTC
bool trapPending
Whether or not the thread is currently waiting on a trap, and thus able to be externally updated without squashing.
ThreadContext * tc
Pointer to the ThreadContext of this thread.
Public Attributes inherited from ThreadState
Counter numInst
Number of instructions committed.
Stats::Scalar numInsts
Stat for number instructions committed.
Counter numOp
Number of ops (including micro ops) committed.
Stats::Scalar numOps
Stat for number ops (including micro ops) committed.
Stats::Scalar numMemRefs
Stat for number of memory references.
Counter numLoad
Number of simulated loads, used for tracking events based on the number of loads committed.
Counter startNumLoad
The number of simulated loads committed prior to this run.
Tick lastActivate
Last time activate was called on this thread.
Tick lastSuspend
Last time suspend was called on this thread.
FunctionProfile * profile
ProfileNode * profileNode
Addr profilePC
EndQuiesceEvent * quiesceEvent
Kernel::Statistics * kernelStats
Counter funcExeInst
unsigned storeCondFailures
Private Attributes
O3CPU * cpu
Pointer to the CPU.
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Protected Attributes inherited from ThreadState
ThreadContext::Status _status
BaseCPU * baseCpu
ContextID _contextId
ThreadID _threadId
Process * process
PortProxy * physProxy
A port proxy outgoing only for functional accesses to physical addresses.
PortProxy * virtProxy
A translating port proxy, outgoing only, for functional accesse to virtual addresses.
Detailed Description
template<class Impl>
struct O3ThreadState< Impl >
Class that has various thread state, such as the status, the current instruction being processed, whether or not the thread has a trap pending or is being externally updated, the ThreadContext pointer, etc.
It also handles anything related to a specific thread's process, such as syscalls and checking valid addresses.
Definition at line 59 of file commit.hh.
Member Typedef Documentation
O3CPU
template<class Impl> typedef Impl::O3CPU O3ThreadState< Impl >::O3CPU
Definition at line 70 of file thread_state.hh.
Status
template<class Impl> typedef ThreadContext::Status O3ThreadState< Impl >::Status
Definition at line 69 of file thread_state.hh.
Constructor & Destructor Documentation
O3ThreadState()
template<class Impl> O3ThreadState< Impl >::O3ThreadState (O3CPU * _cpu, int _thread_num, Process * _process) inline
Definition at line 99 of file thread_state.hh.
References O3ThreadState< Impl >::dumpFuncProfile(), FullSystem, ThreadState::profile, ThreadState::profileNode, ThreadState::profilePC, and registerExitCallback().
Member Function Documentation
dumpFuncProfile()
template<class Impl> void O3ThreadState< Impl >::dumpFuncProfile () inline
Definition at line 156 of file thread_state.hh.
References OutputDirectory::close(), OutputDirectory::create(), csprintf(), FunctionProfile::dump(), X86ISA::os, ThreadState::profile, and simout.
Referenced by O3ThreadState< Impl >::O3ThreadState().
getTC()
template<class Impl> ThreadContext* O3ThreadState< Impl >::getTC () inline
Returns a pointer to the TC of this thread.
Definition at line 148 of file thread_state.hh.
References O3ThreadState< Impl >::tc.
serialize()
template<class Impl> void O3ThreadState< Impl >::serialize (CheckpointOut & cp) const inline override virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 123 of file thread_state.hh.
References ThreadState::serialize(), and O3ThreadState< Impl >::tc.
syscall()
template<class Impl> void O3ThreadState< Impl >::syscall (int64_t callnum, Fault * fault) inline
Handles the syscall.
Definition at line 151 of file thread_state.hh.
References ThreadState::process, and Process::syscall().
unserialize()
template<class Impl> void O3ThreadState< Impl >::unserialize (CheckpointIn & cp) inline override virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 131 of file thread_state.hh.
References O3ThreadState< Impl >::tc, and ThreadState::unserialize().
Member Data Documentation
comInstEventQueue
template<class Impl> EventQueue O3ThreadState< Impl >::comInstEventQueue
An instruction-based event queue.
Used for scheduling events based on number of instructions committed.
Definition at line 82 of file thread_state.hh.
cpu
template<class Impl> O3CPU* O3ThreadState< Impl >::cpu private
Pointer to the CPU.
Definition at line 74 of file thread_state.hh.
noSquashFromTC
template<class Impl> bool O3ThreadState< Impl >::noSquashFromTC
Definition at line 92 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::conditionalSquash().
pcEventQueue
template<class Impl> PCEventQueue O3ThreadState< Impl >::pcEventQueue
Definition at line 77 of file thread_state.hh.
tc
template<class Impl> ThreadContext* O3ThreadState< Impl >::tc
Pointer to the ThreadContext of this thread.
Definition at line 145 of file thread_state.hh.
Referenced by O3ThreadState< Impl >::getTC(), O3ThreadState< Impl >::serialize(), and O3ThreadState< Impl >::unserialize().
trapPending
template<class Impl> bool O3ThreadState< Impl >::trapPending
Whether or not the thread is currently waiting on a trap, and thus able to be externally updated without squashing.
Definition at line 97 of file thread_state.hh.
Referenced by O3ThreadContext< Impl >::conditionalSquash().
The documentation for this struct was generated from the following files:
cpu/o3/commit.hh
cpu/o3/thread_state.hh