gem5: Stats::DistPrint Struct Reference
Stats::DistPrint Struct Reference
Public Member Functions
DistPrint (const Text *text, const DistInfo &info)
DistPrint (const Text *text, const VectorDistInfo &info, int i)
void init (const Text *text, const Info &info)
void operator() (ostream &stream) const
Public Attributes
string name
string separatorString
string desc
Flags flags
bool descriptions
int precision
const DistData & data
Detailed Description
Definition at line 371 of file text.cc.
Constructor & Destructor Documentation
DistPrint() [1/2]
Stats::DistPrint::DistPrint (const Text * text, const DistInfo & info)
Definition at line 388 of file text.cc.
References init().
DistPrint() [2/2]
Stats::DistPrint::DistPrint (const Text * text, const VectorDistInfo & info, int i)
Definition at line 394 of file text.cc.
References desc, init(), Stats::Info::name, name, Stats::Text::statName(), Stats::VectorDistInfo::subdescs, Stats::VectorDistInfo::subnames, and sc_dt::to_string().
Member Function Documentation
init()
void Stats::DistPrint::init (const Text * text, const Info & info)
Definition at line 408 of file text.cc.
References Stats::Info::desc, desc, Stats::Text::descriptions, descriptions, Stats::Info::flags, flags, Stats::Info::name, name, Stats::Info::precision, precision, Stats::Info::separatorString, separatorString, and Stats::Text::statName().
Referenced by DistPrint().
operator()()
void Stats::DistPrint::operator() (ostream & stream) const
Definition at line 419 of file text.cc.
References X86ISA::base, Stats::DistData::bucket_size, ccprintf(), Stats::ScalarPrint::cdf, Stats::DistData::cvec, data, Stats::ScalarPrint::desc, desc, Stats::ScalarPrint::descriptions, descriptions, Stats::Deviation, Stats::Dist, Stats::ScalarPrint::flags, flags, Stats::Hist, ArmISA::i, Flags< T >::isSet(), Stats::DistData::logs, Stats::DistData::max, Stats::DistData::max_val, Stats::DistData::min, Stats::DistData::min_val, Stats::ScalarPrint::name, name, NAN, Stats::nozero, Stats::oneline, Stats::DistData::overflow, Stats::ScalarPrint::pdf, Stats::ScalarPrint::precision, precision, Stats::DistData::samples, separatorString, Stats::DistData::squares, Stats::DistData::sum, Stats::total, Stats::DistData::type, Stats::DistData::underflow, Stats::ScalarPrint::update(), and Stats::ScalarPrint::value.
Member Data Documentation
data
const DistData& Stats::DistPrint::data
Definition at line 380 of file text.cc.
Referenced by operator()().
desc
string Stats::DistPrint::desc
Definition at line 375 of file text.cc.
Referenced by DistPrint(), init(), and operator()().
descriptions
bool Stats::DistPrint::descriptions
Definition at line 377 of file text.cc.
Referenced by init(), operator()(), and Stats::Text::visit().
flags
Flags Stats::DistPrint::flags
Definition at line 376 of file text.cc.
Referenced by init(), and operator()().
name
string Stats::DistPrint::name
Definition at line 373 of file text.cc.
Referenced by DistPrint(), init(), and operator()().
precision
int Stats::DistPrint::precision
Definition at line 378 of file text.cc.
Referenced by init(), and operator()().
separatorString
string Stats::DistPrint::separatorString
Definition at line 374 of file text.cc.
Referenced by init(), and operator()().
The documentation for this struct was generated from the following file:
base/stats/text.cc