gem5: Net::EthAddr Struct Reference
Net::EthAddr Struct Reference
#include <inet.hh>
Public Member Functions
EthAddr ()
EthAddr (const uint8_t ea[ETH_ADDR_LEN])
EthAddr (const eth_addr &ea)
EthAddr (const std::string &addr)
const EthAddr & operator= (const eth_addr &ea)
const EthAddr & operator= (const std::string &addr)
int size () const
const uint8_t * bytes () const
uint8_t * bytes ()
const uint8_t * addr () const
bool unicast () const
bool multicast () const
bool broadcast () const
std::string string () const
operator uint64_t () const
Protected Member Functions
void parse (const std::string &addr)
Detailed Description
Definition at line 77 of file inet.hh.
Constructor & Destructor Documentation
EthAddr() [1/4]
Net::EthAddr::EthAddr ()
Definition at line 60 of file inet.cc.
References data.
EthAddr() [2/4]
Net::EthAddr::EthAddr (const uint8_t ea[ETH_ADDR_LEN])
Definition at line 65 of file inet.cc.
References data, ArmISA::ea, and ArmISA::i.
EthAddr() [3/4]
Net::EthAddr::EthAddr (const eth_addr & ea)
Definition at line 71 of file inet.cc.
References data, and ArmISA::i.
EthAddr() [4/4]
Net::EthAddr::EthAddr (const std::string & addr)
Definition at line 77 of file inet.cc.
Member Function Documentation
addr()
const uint8_t* Net::EthAddr::addr () const inline
Definition at line 95 of file inet.hh.
References data.
Referenced by Net::operator<<().
broadcast()
bool Net::EthAddr::broadcast () const inline
Definition at line 98 of file inet.hh.
References data, ArmISA::i, and string().
Referenced by multicast(), EtherSwitch::Interface::recvPacket(), and NSGigE::rxFilter().
bytes() [1/2]
const uint8_t* Net::EthAddr::bytes () const inline
Definition at line 92 of file inet.hh.
References data.
Referenced by Net::operator==(), Net::EthHdr::payload(), Net::IpHdr::payload(), Net::Ip6Hdr::payload(), Net::TcpHdr::payload(), Net::TcpOpt::payload(), and Net::UdpHdr::payload().
bytes() [2/2]
uint8_t* Net::EthAddr::bytes () inline
Definition at line 93 of file inet.hh.
References data.
multicast()
bool Net::EthAddr::multicast () const inline
Definition at line 97 of file inet.hh.
References broadcast(), and unicast().
Referenced by EtherSwitch::Interface::recvPacket(), and NSGigE::rxFilter().
operator uint64_t()
Net::EthAddr::operator uint64_t () const inline
Definition at line 110 of file inet.hh.
References data, ArmISA::ea, Net::operator<<(), Net::operator==(), and X86ISA::reg.
operator=() [1/2]
const EthAddr & Net::EthAddr::operator= (const eth_addr & ea)
Definition at line 83 of file inet.cc.
References data.
operator=() [2/2]
const EthAddr & Net::EthAddr::operator= (const std::string & addr)
Definition at line 90 of file inet.cc.
parse()
void Net::EthAddr::parse (const std::string & addr) protected
Definition at line 97 of file inet.cc.
References data, and ArmISA::i.
size()
int Net::EthAddr::size () const inline
Definition at line 90 of file inet.hh.
Referenced by Net::EthHdr::payload(), Net::IpHdr::payload(), Net::TcpHdr::payload(), Net::TcpOpt::payload(), Net::UdpHdr::payload(), Net::IpPtr::pstart(), Net::Ip6Ptr::pstart(), Net::TcpPtr::pstart(), and Net::UdpPtr::pstart().
string()
string Net::EthAddr::string () const
Definition at line 119 of file inet.cc.
Referenced by broadcast(), Net::IpAddress::ip(), Net::IpNetmask::netmask(), and Net::IpWithPort::port().
unicast()
bool Net::EthAddr::unicast () const inline
Definition at line 96 of file inet.hh.
References data.
Referenced by multicast(), and NSGigE::rxFilter().
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc