gem5: Trace::TarmacTracerRecordV8::TraceInstEntryV8 Struct Reference
Trace::TarmacTracerRecordV8::TraceInstEntryV8 Struct Reference
Instruction entry for v8 records.
#include <tarmac_record_v8.hh>
Public Member Functions
TraceInstEntryV8 (const TarmacContext &tarmCtx, bool predicate)
virtual void print (std::ostream &outs, int verbosity=0, const std::string &prefix="") const override
Public Member Functions inherited from Trace::TarmacTracerRecord::TraceInstEntry
TraceInstEntry (const TarmacContext &tarmCtx, bool predicate)
Public Member Functions inherited from Printable
Printable ()
virtual ~Printable ()
Public Member Functions inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
TraceEntryV8 (std::string _cpuName)
Protected Attributes
Addr paddr
bool paddrValid
Protected Attributes inherited from Trace::TarmacTracerRecord::TraceInstEntry
bool secureMode
True if instruction is executed in secure mode.
uint8_t instSize
Instruction size: 16 for 16-bit Thumb Instruction 32 otherwise (ARM and BigThumb)
Protected Attributes inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
std::string cpuName
Additional Inherited Members
Static Protected Attributes inherited from Trace::TarmacTracerRecord::TraceInstEntry
static uint64_t instCount = 0
Number of instructions being traced.
Detailed Description
Instruction entry for v8 records.
Definition at line 78 of file tarmac_record_v8.hh.
Constructor & Destructor Documentation
TraceInstEntryV8()
Trace::TarmacTracerRecordV8::TraceInstEntryV8::TraceInstEntryV8 (const TarmacContext & tarmCtx, bool predicate)
Definition at line 48 of file tarmac_record_v8.cc.
References Trace::InstRecord::addr, ThreadContext::getDTBPtr(), paddr, paddrValid, Trace::InstRecord::thread, Trace::TarmacContext::thread, and ArmISA::TLB::translateFunctional().
Member Function Documentation
print()
void Trace::TarmacTracerRecordV8::TraceInstEntryV8::print (std::ostream & outs, int verbosity = 0, const std::string & prefix = "") const override virtual
Reimplemented from Trace::TarmacTracerRecord::TraceInstEntry.
Definition at line 235 of file tarmac_record_v8.cc.
References Trace::InstRecord::addr, ccprintf(), Trace::TarmacTracerRecordV8::TraceEntryV8::cpuName, csprintf(), curTick(), Trace::iSetStateToStr(), ArmISA::mode, ArmISA::opcode, and Trace::opModeToStr().
Member Data Documentation
paddr
Addr Trace::TarmacTracerRecordV8::TraceInstEntryV8::paddr protected
Definition at line 88 of file tarmac_record_v8.hh.
Referenced by TraceInstEntryV8().
paddrValid
bool Trace::TarmacTracerRecordV8::TraceInstEntryV8::paddrValid protected
Definition at line 89 of file tarmac_record_v8.hh.
Referenced by TraceInstEntryV8().
The documentation for this struct was generated from the following files:
arch/arm/tracers/tarmac_record_v8.hh
arch/arm/tracers/tarmac_record_v8.cc