gem5: Net::IpNetmask Struct Reference
Net::IpNetmask Struct Reference
#include <inet.hh>
Public Member Functions
IpNetmask ()
IpNetmask (const uint32_t __ip, const uint8_t __netmask)
uint8_t netmask () const
std::string string () const
Public Member Functions inherited from Net::IpAddress
IpAddress ()
IpAddress (const uint32_t __ip)
uint32_t ip () const
std::string string () const
Protected Attributes
uint8_t _netmask
Protected Attributes inherited from Net::IpAddress
uint32_t _ip
Detailed Description
Definition at line 212 of file inet.hh.
Constructor & Destructor Documentation
IpNetmask() [1/2]
Net::IpNetmask::IpNetmask () inline
Definition at line 218 of file inet.hh.
IpNetmask() [2/2]
Net::IpNetmask::IpNetmask (const uint32_t __ip, const uint8_t __netmask) inline
Definition at line 220 of file inet.hh.
Member Function Documentation
netmask()
uint8_t Net::IpNetmask::netmask () const inline
Definition at line 224 of file inet.hh.
References Net::operator<<(), Net::operator==(), and Net::EthAddr::string().
Referenced by Net::operator==().
string()
string Net::IpNetmask::string () const
Definition at line 165 of file inet.cc.
Member Data Documentation
_netmask
uint8_t Net::IpNetmask::_netmask protected
Definition at line 215 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc