gem5: QTIsaac< ALPHA >::randctx Struct Reference
QTIsaac< ALPHA >::randctx Struct Reference
#include <isaac.h>
Public Member Functions
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
randctx (void)
~randctx (void)
Public Attributes
UINT32 randcnt
UINT32 * randrsl
UINT32 * randmem
UINT32 randa
UINT32 randb
UINT32 randc
Detailed Description
template<UINT32 ALPHA = (8)>
struct QTIsaac< ALPHA >::randctx
Definition at line 46 of file isaac.h.
Constructor & Destructor Documentation
randctx() [1/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [1/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
randctx() [2/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [2/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [3/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [3/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [4/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [4/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [5/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [5/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [6/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [6/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [7/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [7/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [8/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [8/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [9/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [9/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [10/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [10/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [11/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [11/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [12/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [12/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [13/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [13/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
randctx() [14/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::randctx (void) inline
Definition at line 48 of file isaac.h.
References QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::randctx::randmem, and QTIsaac< ALPHA >::randctx::randrsl.
~randctx() [14/14]
template<UINT32 ALPHA = (8)> QTIsaac< ALPHA >::randctx::~randctx (void) inline
Definition at line 54 of file isaac.h.
References ArmISA::a, ArmISA::b, ArmISA::c, ArmISA::d, ArmISA::e, ArmISA::f, MipsISA::g, GOLDEN_RATIO, ArmISA::i, QTIsaac< ALPHA >::ind(), QTIsaac< ALPHA >::isaac(), ArmISA::m, QTIsaac< ALPHA >::m_rc, SparcISA::mm, QTIsaac< ALPHA >::N, QTIsaac< ALPHA >::QTIsaac(), MipsISA::r, QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randa, QTIsaac< ALPHA >::randctx::randb, QTIsaac< ALPHA >::randctx::randc, QTIsaac< ALPHA >::randctx::randcnt, QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::randctx::randmem, QTIsaac< ALPHA >::randctx::randrsl, QTIsaac< ALPHA >::rngstep(), ArmISA::s, QTIsaac< ALPHA >::shuffle(), QTIsaac< ALPHA >::srand(), X86ISA::x, and QTIsaac< ALPHA >::~QTIsaac().
Member Data Documentation
randa
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::randctx::randa
Definition at line 63 of file isaac.h.
Referenced by QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
randb
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::randctx::randb
Definition at line 64 of file isaac.h.
Referenced by QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
randc
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::randctx::randc
Definition at line 65 of file isaac.h.
Referenced by QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
randcnt
template<UINT32 ALPHA = (8)> UINT32 QTIsaac< ALPHA >::randctx::randcnt
Definition at line 60 of file isaac.h.
Referenced by QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randinit(), and QTIsaac< ALPHA >::randctx::~randctx().
randmem
template<UINT32 ALPHA = (8)> UINT32 * QTIsaac< ALPHA >::randctx::randmem
Definition at line 62 of file isaac.h.
Referenced by QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::randctx::randctx(), QTIsaac< ALPHA >::randinit(), and QTIsaac< ALPHA >::randctx::~randctx().
randrsl
template<UINT32 ALPHA = (8)> UINT32 * QTIsaac< ALPHA >::randctx::randrsl
Definition at line 61 of file isaac.h.
Referenced by QTIsaac< ALPHA >::isaac(), QTIsaac< ALPHA >::rand(), QTIsaac< ALPHA >::randctx::randctx(), QTIsaac< ALPHA >::randinit(), QTIsaac< ALPHA >::srand(), and QTIsaac< ALPHA >::randctx::~randctx().
The documentation for this struct was generated from the following file:
systemc/tests/systemc/datatypes/int/arith/arith02/isaac.h