gem5: testbench Struct Reference
testbench Struct Reference
#include <tb.h>
Public Member Functions
testbench (const sc_module_name &NAME, sc_clock &TICK)
testbench (const sc_module_name &NAME, sc_clock &TICK)
testbench (const sc_module_name &NAME, sc_clock &TICK, sc_clock &TICK2)
testbench (sc_module_name NAME, sc_clock &CLK, const sc_signal< double > &IN_, sc_signal< double > &OUT1, sc_signal< double > &OUT2)
testbench (sc_module_name NAME, sc_clock &TICK, sc_clock &TICK2)
testbench (sc_module_name NAME, sc_clock &CLK, const sc_signal< double > &IN_, sc_signal< double > &OUT1, sc_signal< double > &OUT2)
Public Attributes
sc_signal< int > addr
sc_signal< bool > reset
sc_signal< bool > ready
signal_bool_vector8 data
signal_bool_vector4 sum
RESET_STIM rd1
DATA_GEN dg1
ADD_CHAIN ac1
DISPLAY d1
sc_signal< bool > out_clk_pos
sc_signal< bool > out_clk_neg
sc_signal< bool > out_clk2_pos
sc_signal< bool > out_clk2_neg
CLK_POS clkp
CLK_NEG clkn
CLK2_POS clkp2
CLK2_NEG clkn2
numgen N
display D
clk_pos clkp
clk_neg clkn
clk2_pos clkp2
clk2_neg clkn2
Detailed Description
Definition at line 50 of file tb.h.
Constructor & Destructor Documentation
testbench() [1/6]
testbench::testbench (const sc_module_name & NAME, sc_clock & TICK) inline
Definition at line 62 of file tb.h.
testbench() [2/6]
testbench::testbench (const sc_module_name & NAME, sc_clock & TICK) inline
Definition at line 60 of file add_chain_tb.h.
References f_add_chain(), f_DATA_GEN(), f_DISPLAY(), and f_RESET_STIM().
testbench() [3/6]
testbench::testbench (const sc_module_name & NAME, sc_clock & TICK, sc_clock & TICK2) inline
Definition at line 54 of file tb.h.
testbench() [4/6]
testbench::testbench (sc_module_name NAME, sc_clock & CLK, const sc_signal< double > & IN_, sc_signal< double > & OUT1, sc_signal< double > & OUT2) inline
Definition at line 48 of file testbench.h.
testbench() [5/6]
testbench::testbench (sc_module_name NAME, sc_clock & TICK, sc_clock & TICK2) inline
Definition at line 54 of file tb.h.
testbench() [6/6]
testbench::testbench (sc_module_name NAME, sc_clock & CLK, const sc_signal< double > & IN_, sc_signal< double > & OUT1, sc_signal< double > & OUT2) inline
Definition at line 48 of file testbench.h.
Member Data Documentation
ac1
ADD_CHAIN testbench::ac1
Definition at line 58 of file tb.h.
addr
sc_signal< int > testbench::addr
Definition at line 51 of file tb.h.
clkn [1/2]
clk_neg testbench::clkn
Definition at line 49 of file tb.h.
clkn [2/2]
CLK_NEG testbench::clkn
Definition at line 49 of file tb.h.
clkn2 [1/2]
CLK2_NEG testbench::clkn2
Definition at line 51 of file tb.h.
clkn2 [2/2]
clk2_neg testbench::clkn2
Definition at line 51 of file tb.h.
clkp [1/2]
clk_pos testbench::clkp
Definition at line 48 of file tb.h.
clkp [2/2]
CLK_POS testbench::clkp
Definition at line 48 of file tb.h.
clkp2 [1/2]
CLK2_POS testbench::clkp2
Definition at line 50 of file tb.h.
clkp2 [2/2]
clk2_pos testbench::clkp2
Definition at line 50 of file tb.h.
D
display testbench::D
Definition at line 45 of file testbench.h.
d1
DISPLAY testbench::d1
Definition at line 59 of file tb.h.
data
signal_bool_vector8 testbench::data
Definition at line 54 of file tb.h.
dg1
DATA_GEN testbench::dg1
Definition at line 57 of file tb.h.
N
numgen testbench::N
Definition at line 44 of file testbench.h.
out_clk2_neg
sc_signal< bool > testbench::out_clk2_neg
Definition at line 47 of file tb.h.
out_clk2_pos
sc_signal< bool > testbench::out_clk2_pos
Definition at line 46 of file tb.h.
out_clk_neg
sc_signal< bool > testbench::out_clk_neg
Definition at line 45 of file tb.h.
out_clk_pos
sc_signal< bool > testbench::out_clk_pos
Definition at line 44 of file tb.h.
rd1
RESET_STIM testbench::rd1
Definition at line 56 of file tb.h.
ready
sc_signal< bool > testbench::ready
Definition at line 53 of file tb.h.
reset
sc_signal< bool > testbench::reset
Definition at line 52 of file tb.h.
sum
signal_bool_vector4 testbench::sum
Definition at line 55 of file tb.h.
The documentation for this struct was generated from the following files:
systemc/tests/systemc/misc/synth/add_chain/tb.h
systemc/tests/systemc/misc/synth/add_chain_FUNC/add_chain_tb.h
systemc/tests/systemc/misc/user_guide/chpt4.2/testbench.h