gem5: test Struct Reference
test Struct Reference
#include <test.h>
Public Member Functions
SC_HAS_PROCESS (test)
test (const char *NAME)
void reset_loop ()
SC_HAS_PROCESS (test)
test (const char *NAME)
void reset_loop ()
SC_HAS_PROCESS (test)
test (const char *NAME)
void reset_loop ()
SC_HAS_PROCESS (test)
test (const char *NAME)
void reset_loop ()
Public Attributes
sc_in< bool > reset
sc_in_clk clk
sc_in< sc_uint< 8 > > dati
sc_out< sc_uint< 8 > > dato
sc_out< bool > done
sc_in< sc_lv< 14 > > dati
sc_out< sc_lv< 14 > > dato
sc_out< sc_logic > ready
sc_out< sc_logic > done
Detailed Description
Definition at line 38 of file test.h.
Constructor & Destructor Documentation
test() [1/4]
test::test (const char * NAME) inline
Definition at line 48 of file test.h.
References reset_loop(), and SC_CTHREAD.
test() [2/4]
test::test (const char * NAME) inline
Definition at line 48 of file test.h.
References reset_loop(), and SC_CTHREAD.
test() [3/4]
test::test (const char * NAME) inline
Definition at line 48 of file regfile.h.
References reset_loop(), and SC_CTHREAD.
test() [4/4]
test::test (const char * NAME) inline
Definition at line 48 of file regfile.h.
References reset_loop(), and SC_CTHREAD.
Member Function Documentation
reset_loop() [1/4]
void test::reset_loop ()
Referenced by test().
reset_loop() [2/4]
void test::reset_loop ()
reset_loop() [3/4]
void test::reset_loop ()
reset_loop() [4/4]
void test::reset_loop ()
SC_HAS_PROCESS() [1/4]
test::SC_HAS_PROCESS (test)
SC_HAS_PROCESS() [2/4]
test::SC_HAS_PROCESS (test)
SC_HAS_PROCESS() [3/4]
test::SC_HAS_PROCESS (test)
SC_HAS_PROCESS() [4/4]
test::SC_HAS_PROCESS (test)
Member Data Documentation
clk
sc_in_clk test::clk
Definition at line 41 of file test.h.
dati [1/2]
sc_in< sc_lv< 14 > > test::dati
Definition at line 42 of file test.h.
dati [2/2]
sc_in<sc_lv<14> > test::dati
Definition at line 42 of file regfile.h.
dato [1/2]
sc_out< sc_lv< 14 > > test::dato
Definition at line 43 of file test.h.
dato [2/2]
sc_out<sc_lv<14> > test::dato
Definition at line 43 of file regfile.h.
done [1/2]
sc_out< sc_logic > test::done
Definition at line 44 of file test.h.
done [2/2]
sc_out<sc_logic> test::done
Definition at line 44 of file regfile.h.
ready
sc_out< sc_logic > test::ready
Definition at line 44 of file regfile.h.
reset
sc_in< bool > test::reset
Definition at line 40 of file test.h.
The documentation for this struct was generated from the following files:
systemc/tests/systemc/misc/stars/star103601-2/test.h
systemc/tests/systemc/misc/stars/star107755/regfile.h