gem5: MPP_StatisticalCorrector::MPP_SCThreadHistory Struct Reference
MPP_StatisticalCorrector::MPP_SCThreadHistory Struct Reference
#include <multiperspective_perceptron_tage.hh>
Public Member Functions
MPP_SCThreadHistory ()
int64_t getHistoryStackEntry () const
void updateHistoryStack (Addr target, bool taken, bool is_call, bool is_return)
unsigned int getPointer () const
Public Member Functions inherited from StatisticalCorrector::SCThreadHistory
SCThreadHistory ()
void setNumOrdinalHistories (unsigned num)
void initLocalHistory (int ordinal, int numHistories, int shift)
int64_t getLocalHistory (int ordinal, Addr pc)
void updateLocalHistory (int ordinal, Addr branch_pc, bool taken, Addr extraXor=0)
Public Attributes
int64_t globalHist
std::vector< int64_t > historyStack
unsigned int historyStackPointer
Public Attributes inherited from StatisticalCorrector::SCThreadHistory
int64_t bwHist
int64_t imliCount
Detailed Description
Definition at line 111 of file multiperspective_perceptron_tage.hh.
Constructor & Destructor Documentation
MPP_SCThreadHistory()
MPP_StatisticalCorrector::MPP_SCThreadHistory::MPP_SCThreadHistory () inline
Definition at line 113 of file multiperspective_perceptron_tage.hh.
Member Function Documentation
getHistoryStackEntry()
int64_t MPP_StatisticalCorrector::MPP_SCThreadHistory::getHistoryStackEntry () const inline
Definition at line 119 of file multiperspective_perceptron_tage.hh.
Referenced by MPP_StatisticalCorrector_8KB::gPredictions(), MPP_StatisticalCorrector_64KB::gPredictions(), MPP_StatisticalCorrector_8KB::gUpdates(), and MPP_StatisticalCorrector_64KB::gUpdates().
getPointer()
unsigned int MPP_StatisticalCorrector::MPP_SCThreadHistory::getPointer () const inline
Definition at line 141 of file multiperspective_perceptron_tage.hh.
updateHistoryStack()
void MPP_StatisticalCorrector::MPP_SCThreadHistory::updateHistoryStack (Addr target, bool taken, bool is_call, bool is_return) inline
Definition at line 124 of file multiperspective_perceptron_tage.hh.
References MipsISA::index.
Referenced by MPP_StatisticalCorrector_8KB::scHistoryUpdate(), and MPP_StatisticalCorrector_64KB::scHistoryUpdate().
Member Data Documentation
globalHist
int64_t MPP_StatisticalCorrector::MPP_SCThreadHistory::globalHist
Definition at line 115 of file multiperspective_perceptron_tage.hh.
Referenced by MPP_StatisticalCorrector_8KB::gPredictions(), MPP_StatisticalCorrector_64KB::gPredictions(), MPP_StatisticalCorrector_8KB::gUpdates(), MPP_StatisticalCorrector_64KB::gUpdates(), MPP_StatisticalCorrector_8KB::scHistoryUpdate(), and MPP_StatisticalCorrector_64KB::scHistoryUpdate().
historyStack
std::vector<int64_t> MPP_StatisticalCorrector::MPP_SCThreadHistory::historyStack
Definition at line 116 of file multiperspective_perceptron_tage.hh.
historyStackPointer
unsigned int MPP_StatisticalCorrector::MPP_SCThreadHistory::historyStackPointer
Definition at line 117 of file multiperspective_perceptron_tage.hh.
The documentation for this struct was generated from the following file:
cpu/pred/multiperspective_perceptron_tage.hh