gem5: StatisticalCorrector::SCThreadHistory Struct Reference
StatisticalCorrector::SCThreadHistory Struct Reference
#include <statistical_corrector.hh>
Public Member Functions
SCThreadHistory ()
void setNumOrdinalHistories (unsigned num)
void initLocalHistory (int ordinal, int numHistories, int shift)
int64_t getLocalHistory (int ordinal, Addr pc)
void updateLocalHistory (int ordinal, Addr branch_pc, bool taken, Addr extraXor=0)
Public Attributes
int64_t bwHist
int64_t imliCount
Private Member Functions
unsigned getEntry (Addr pc, unsigned idx)
Private Attributes
std::vector< int64_t > * localHistories
std::vector< int > shifts
unsigned numOrdinalHistories
Detailed Description
Definition at line 69 of file statistical_corrector.hh.
Constructor & Destructor Documentation
SCThreadHistory()
StatisticalCorrector::SCThreadHistory::SCThreadHistory () inline
Definition at line 70 of file statistical_corrector.hh.
References bwHist, imliCount, and numOrdinalHistories.
Member Function Documentation
getEntry()
unsigned StatisticalCorrector::SCThreadHistory::getEntry (Addr pc, unsigned idx) inline private
Definition at line 122 of file statistical_corrector.hh.
Referenced by getLocalHistory(), and updateLocalHistory().
getLocalHistory()
int64_t StatisticalCorrector::SCThreadHistory::getLocalHistory (int ordinal, Addr pc) inline
Definition at line 94 of file statistical_corrector.hh.
References getEntry(), localHistories, and numOrdinalHistories.
Referenced by MPP_StatisticalCorrector_8KB::gPredictions(), MPP_StatisticalCorrector_64KB::gPredictions(), MPP_StatisticalCorrector_8KB::gUpdates(), and MPP_StatisticalCorrector_64KB::gUpdates().
initLocalHistory()
void StatisticalCorrector::SCThreadHistory::initLocalHistory (int ordinal, int numHistories, int shift) inline
Definition at line 86 of file statistical_corrector.hh.
References isPowerOf2(), localHistories, numOrdinalHistories, ArmISA::shift, and shifts.
Referenced by MPP_StatisticalCorrector_8KB::makeThreadHistory(), and MPP_StatisticalCorrector_64KB::makeThreadHistory().
setNumOrdinalHistories()
void StatisticalCorrector::SCThreadHistory::setNumOrdinalHistories (unsigned num) inline
Definition at line 78 of file statistical_corrector.hh.
References localHistories, numOrdinalHistories, and shifts.
Referenced by MPP_StatisticalCorrector_8KB::makeThreadHistory(), and MPP_StatisticalCorrector_64KB::makeThreadHistory().
updateLocalHistory()
void StatisticalCorrector::SCThreadHistory::updateLocalHistory (int ordinal, Addr branch_pc, bool taken, Addr extraXor = 0) inline
Definition at line 101 of file statistical_corrector.hh.
References getEntry(), localHistories, and numOrdinalHistories.
Referenced by MPP_StatisticalCorrector_64KB::scHistoryUpdate(), and StatisticalCorrector::scHistoryUpdate().
Member Data Documentation
bwHist
int64_t StatisticalCorrector::SCThreadHistory::bwHist
Definition at line 75 of file statistical_corrector.hh.
Referenced by StatisticalCorrector::scHistoryUpdate(), and SCThreadHistory().
imliCount
int64_t StatisticalCorrector::SCThreadHistory::imliCount
Definition at line 76 of file statistical_corrector.hh.
Referenced by TAGE_SC_L_64KB_StatisticalCorrector::gPredictions(), TAGE_SC_L_64KB_StatisticalCorrector::gUpdates(), StatisticalCorrector::scHistoryUpdate(), and SCThreadHistory().
localHistories
std::vector<int64_t>* StatisticalCorrector::SCThreadHistory::localHistories private
Definition at line 118 of file statistical_corrector.hh.
Referenced by getLocalHistory(), initLocalHistory(), setNumOrdinalHistories(), and updateLocalHistory().
numOrdinalHistories
unsigned StatisticalCorrector::SCThreadHistory::numOrdinalHistories private
Definition at line 120 of file statistical_corrector.hh.
Referenced by getLocalHistory(), initLocalHistory(), SCThreadHistory(), setNumOrdinalHistories(), and updateLocalHistory().
shifts
std::vector<int> StatisticalCorrector::SCThreadHistory::shifts private
Definition at line 119 of file statistical_corrector.hh.
Referenced by initLocalHistory(), and setNumOrdinalHistories().
The documentation for this struct was generated from the following file:
cpu/pred/statistical_corrector.hh