gem5: Stats::Output Struct Reference
Stats::Output Struct Reference abstract
#include <output.hh>
Public Member Functions
virtual ~Output ()
virtual void begin ()=0
virtual void end ()=0
virtual bool valid () const =0
virtual void beginGroup (const char *name)=0
virtual void endGroup ()=0
virtual void visit (const ScalarInfo &info)=0
virtual void visit (const VectorInfo &info)=0
virtual void visit (const DistInfo &info)=0
virtual void visit (const VectorDistInfo &info)=0
virtual void visit (const Vector2dInfo &info)=0
virtual void visit (const FormulaInfo &info)=0
virtual void visit (const SparseHistInfo &info)=0
Detailed Description
Definition at line 60 of file output.hh.
Constructor & Destructor Documentation
~Output()
virtual Stats::Output::~Output () inline virtual
Definition at line 62 of file output.hh.
References begin(), beginGroup(), end(), endGroup(), name(), valid(), and visit().
Member Function Documentation
begin()
virtual void Stats::Output::begin () pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by pybind_init_stats(), and ~Output().
beginGroup()
virtual void Stats::Output::beginGroup (const char * name) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by pybind_init_stats(), and ~Output().
end()
virtual void Stats::Output::end () pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by pybind_init_stats(), and ~Output().
endGroup()
virtual void Stats::Output::endGroup () pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by pybind_init_stats(), and ~Output().
valid()
virtual bool Stats::Output::valid () const pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by pybind_init_stats(), and ~Output().
visit() [1/7]
virtual void Stats::Output::visit (const ScalarInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
Referenced by Stats::InfoProxy< Stat, FormulaInfo >::visit(), Stats::ProxyInfo::visit(), and ~Output().
visit() [2/7]
virtual void Stats::Output::visit (const VectorInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
visit() [3/7]
virtual void Stats::Output::visit (const DistInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
visit() [4/7]
virtual void Stats::Output::visit (const VectorDistInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
visit() [5/7]
virtual void Stats::Output::visit (const Vector2dInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
visit() [6/7]
virtual void Stats::Output::visit (const FormulaInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
visit() [7/7]
virtual void Stats::Output::visit (const SparseHistInfo & info) pure virtual
Implemented in Stats::Text, and Stats::Hdf5.
The documentation for this struct was generated from the following file:
base/stats/output.hh