gem5: QoS::MemCtrl::MemCtrlStats Struct Reference
QoS::MemCtrl::MemCtrlStats Struct Reference
#include <mem_ctrl.hh>
Public Member Functions
MemCtrlStats (MemCtrl &mc)
void regStats () override
Callback to set stat parameters.
Public Member Functions inherited from Stats::Group
Group ()=delete
Group (const Group &)=delete
Group & operator= (const Group &)=delete
Group (Group *parent, const char *name=nullptr)
Construct a new statistics group.
virtual ~Group ()
virtual void resetStats ()
Callback to reset stats.
virtual void preDumpStats ()
Callback before stats are dumped.
void addStat (Stats::Info *info)
Register a stat with this group.
const std::map< std::string, Group * > & getStatGroups () const
Get all child groups associated with this object.
const std::vector< Info * > & getStats () const
Get all stats associated with this object.
void addStatGroup (const char *name, Group *block)
Add a stat block as a child of this block.
Public Attributes
const MemCtrl & memCtrl
Stats::VectorStandardDeviation avgPriority
per-master average QoS priority
Stats::VectorStandardDeviation avgPriorityDistance
per-master average QoS distance between assigned and queued values
Stats::Vector priorityMinLatency
per-priority minimum latency
Stats::Vector priorityMaxLatency
per-priority maximum latency
Stats::Scalar numReadWriteTurnArounds
Count the number of turnarounds READ to WRITE.
Stats::Scalar numWriteReadTurnArounds
Count the number of turnarounds WRITE to READ.
Stats::Scalar numStayReadState
Count the number of times bus staying in READ state.
Stats::Scalar numStayWriteState
Count the number of times bus staying in WRITE state.
Detailed Description
Definition at line 126 of file mem_ctrl.hh.
Constructor & Destructor Documentation
MemCtrlStats()
QoS::MemCtrl::MemCtrlStats::MemCtrlStats (MemCtrl & mc)
Definition at line 284 of file mem_ctrl.cc.
Member Function Documentation
regStats()
void QoS::MemCtrl::MemCtrlStats::regStats () override virtual
Callback to set stat parameters.
This callback is typically used for complex stats (e.g., distributions) that need parameters in addition to a name and a description. Stat names and descriptions should typically be set from the constructor usingo from the constructor using the ADD_STAT macro.
Reimplemented from Stats::Group.
Definition at line 310 of file mem_ctrl.cc.
References AbstractMemory::_system, avgPriority, avgPriorityDistance, Stats::DataWrap< Derived, InfoProxyType >::flags(), System::getMasterName(), ArmISA::i, Stats::VectorBase< Derived, Stor >::init(), Stats::VectorStandardDeviation::init(), ArmISA::j, System::maxMasters(), memCtrl, Stats::nonan, Stats::nozero, QoS::MemCtrl::numPriorities(), Stats::DataWrap< Derived, InfoProxyType >::precision(), priorityMaxLatency, priorityMinLatency, Stats::Group::regStats(), Stats::DataWrapVec< Derived, InfoProxyType >::subname(), AbstractMemory::system(), and sc_dt::to_string().
Member Data Documentation
avgPriority
Stats::VectorStandardDeviation QoS::MemCtrl::MemCtrlStats::avgPriority
per-master average QoS priority
Definition at line 135 of file mem_ctrl.hh.
Referenced by QoS::MemCtrl::logRequest(), and regStats().
avgPriorityDistance
Stats::VectorStandardDeviation QoS::MemCtrl::MemCtrlStats::avgPriorityDistance
per-master average QoS distance between assigned and queued values
Definition at line 140 of file mem_ctrl.hh.
Referenced by QoS::MemCtrl::logRequest(), and regStats().
memCtrl
const MemCtrl& QoS::MemCtrl::MemCtrlStats::memCtrl
Definition at line 132 of file mem_ctrl.hh.
Referenced by regStats().
numReadWriteTurnArounds
Stats::Scalar QoS::MemCtrl::MemCtrlStats::numReadWriteTurnArounds
Count the number of turnarounds READ to WRITE.
Definition at line 147 of file mem_ctrl.hh.
numStayReadState
Stats::Scalar QoS::MemCtrl::MemCtrlStats::numStayReadState
Count the number of times bus staying in READ state.
Definition at line 151 of file mem_ctrl.hh.
numStayWriteState
Stats::Scalar QoS::MemCtrl::MemCtrlStats::numStayWriteState
Count the number of times bus staying in WRITE state.
Definition at line 153 of file mem_ctrl.hh.
numWriteReadTurnArounds
Stats::Scalar QoS::MemCtrl::MemCtrlStats::numWriteReadTurnArounds
Count the number of turnarounds WRITE to READ.
Definition at line 149 of file mem_ctrl.hh.
priorityMaxLatency
Stats::Vector QoS::MemCtrl::MemCtrlStats::priorityMaxLatency
per-priority maximum latency
Definition at line 145 of file mem_ctrl.hh.
Referenced by QoS::MemCtrl::logResponse(), and regStats().
priorityMinLatency
Stats::Vector QoS::MemCtrl::MemCtrlStats::priorityMinLatency
per-priority minimum latency
Definition at line 143 of file mem_ctrl.hh.
Referenced by QoS::MemCtrl::logResponse(), and regStats().
The documentation for this struct was generated from the following files:
mem/qos/mem_ctrl.hh
mem/qos/mem_ctrl.cc