gem5: StatTest Struct Reference
StatTest Struct Reference
Public Member Functions
void run ()
void init ()
Public Attributes
Scalar s1
Scalar s2
Average s3
Scalar s4
Vector s5
Distribution s6
Vector s7
AverageVector s8
StandardDeviation s9
AverageDeviation s10
Scalar s11
Distribution s12
VectorDistribution s13
VectorStandardDeviation s14
VectorAverageDeviation s15
Vector2d s16
Value s17
Value s18
Histogram h01
Histogram h02
Histogram h03
Histogram h04
Histogram h05
Histogram h06
Histogram h07
Histogram h08
Histogram h09
Histogram h10
Histogram h11
Histogram h12
SparseHistogram sh1
Vector s19
Vector s20
Formula f1
Formula f2
Formula f3
Formula f4
Formula f5
Formula f6
Detailed Description
Definition at line 73 of file stattest.cc.
Member Function Documentation
init()
void StatTest::init ()
Definition at line 129 of file stattest.cc.
References Stats::constant(), cprintf(), curEventQueue(), getEventQueue(), Stats::nonan, Stats::nozero, Stats::pdf, ArmISA::q, ArmISA::sh1, RiscvISA::sum, testfunc(), Stats::total, and ULL.
Referenced by stattest_init_pybind().
run()
void StatTest::run ()
Definition at line 395 of file stattest.cc.
References curEventQueue(), curTick(), ArmISA::i, MipsISA::random, EventQueue::setCurTick(), ArmISA::sh1, and ULL.
Referenced by stattest_init_pybind().
Member Data Documentation
f1
Formula StatTest::f1
Definition at line 110 of file stattest.cc.
f2
Formula StatTest::f2
Definition at line 111 of file stattest.cc.
f3
Formula StatTest::f3
Definition at line 112 of file stattest.cc.
f4
Formula StatTest::f4
Definition at line 113 of file stattest.cc.
f5
Formula StatTest::f5
Definition at line 114 of file stattest.cc.
f6
Formula StatTest::f6
Definition at line 115 of file stattest.cc.
h01
Histogram StatTest::h01
Definition at line 93 of file stattest.cc.
h02
Histogram StatTest::h02
Definition at line 94 of file stattest.cc.
h03
Histogram StatTest::h03
Definition at line 95 of file stattest.cc.
h04
Histogram StatTest::h04
Definition at line 96 of file stattest.cc.
h05
Histogram StatTest::h05
Definition at line 97 of file stattest.cc.
h06
Histogram StatTest::h06
Definition at line 98 of file stattest.cc.
h07
Histogram StatTest::h07
Definition at line 99 of file stattest.cc.
h08
Histogram StatTest::h08
Definition at line 100 of file stattest.cc.
h09
Histogram StatTest::h09
Definition at line 101 of file stattest.cc.
h10
Histogram StatTest::h10
Definition at line 102 of file stattest.cc.
h11
Histogram StatTest::h11
Definition at line 103 of file stattest.cc.
h12
Histogram StatTest::h12
Definition at line 104 of file stattest.cc.
s1
Scalar StatTest::s1
Definition at line 75 of file stattest.cc.
s10
AverageDeviation StatTest::s10
Definition at line 84 of file stattest.cc.
s11
Scalar StatTest::s11
Definition at line 85 of file stattest.cc.
s12
Distribution StatTest::s12
Definition at line 86 of file stattest.cc.
s13
VectorDistribution StatTest::s13
Definition at line 87 of file stattest.cc.
s14
VectorStandardDeviation StatTest::s14
Definition at line 88 of file stattest.cc.
s15
VectorAverageDeviation StatTest::s15
Definition at line 89 of file stattest.cc.
s16
Vector2d StatTest::s16
Definition at line 90 of file stattest.cc.
s17
Value StatTest::s17
Definition at line 91 of file stattest.cc.
s18
Value StatTest::s18
Definition at line 92 of file stattest.cc.
s19
Vector StatTest::s19
Definition at line 107 of file stattest.cc.
s2
Scalar StatTest::s2
Definition at line 76 of file stattest.cc.
s20
Vector StatTest::s20
Definition at line 108 of file stattest.cc.
s3
Average StatTest::s3
Definition at line 77 of file stattest.cc.
s4
Scalar StatTest::s4
Definition at line 78 of file stattest.cc.
s5
Vector StatTest::s5
Definition at line 79 of file stattest.cc.
s6
Distribution StatTest::s6
Definition at line 80 of file stattest.cc.
s7
Vector StatTest::s7
Definition at line 81 of file stattest.cc.
s8
AverageVector StatTest::s8
Definition at line 82 of file stattest.cc.
s9
StandardDeviation StatTest::s9
Definition at line 83 of file stattest.cc.
sh1
SparseHistogram StatTest::sh1
Definition at line 105 of file stattest.cc.
The documentation for this struct was generated from the following file:
unittest/stattest.cc