gem5: sc_gem5::PythonReadyFunc Struct Reference
sc_gem5::PythonReadyFunc Struct Reference abstract
#include <python.hh>
Public Member Functions
PythonReadyFunc ()
~PythonReadyFunc ()
virtual void run ()=0
Public Attributes
PythonReadyFunc * next
Detailed Description
Definition at line 38 of file python.hh.
Constructor & Destructor Documentation
PythonReadyFunc()
sc_gem5::PythonReadyFunc::PythonReadyFunc ()
Definition at line 76 of file python.cc.
~PythonReadyFunc()
sc_gem5::PythonReadyFunc::~PythonReadyFunc () inline
Definition at line 43 of file python.hh.
References run().
Member Function Documentation
run()
virtual void sc_gem5::PythonReadyFunc::run () pure virtual
Referenced by sc_gem5::PythonInitFunc::~PythonInitFunc(), and ~PythonReadyFunc().
Member Data Documentation
next
PythonReadyFunc* sc_gem5::PythonReadyFunc::next
Definition at line 40 of file python.hh.
The documentation for this struct was generated from the following files:
systemc/core/python.hh
systemc/core/python.cc