gem5: Net::IpHdr Struct Reference
Net::IpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t version () const
uint8_t hlen () const
uint8_t tos () const
uint16_t len () const
uint16_t id () const
uint16_t frag_flags () const
uint16_t frag_off () const
uint8_t ttl () const
uint8_t proto () const
uint16_t sum () const
uint32_t src () const
uint32_t dst () const
void sum (uint16_t sum)
void id (uint16_t _id)
void len (uint16_t _len)
bool options (std::vector< const IpOpt *> &vec) const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 253 of file inet.hh.
Member Function Documentation
bytes() [1/2]
const uint8_t* Net::IpHdr::bytes () const inline
Definition at line 275 of file inet.hh.
Referenced by Net::cksum().
bytes() [2/2]
uint8_t* Net::IpHdr::bytes () inline
Definition at line 277 of file inet.hh.
dst()
uint32_t Net::IpHdr::dst () const inline
Definition at line 266 of file inet.hh.
frag_flags()
uint16_t Net::IpHdr::frag_flags () const inline
Definition at line 260 of file inet.hh.
frag_off()
uint16_t Net::IpHdr::frag_off () const inline
Definition at line 261 of file inet.hh.
hlen()
uint8_t Net::IpHdr::hlen () const inline
Definition at line 256 of file inet.hh.
Referenced by Net::__tu_cksum(), and Net::cksum().
id() [1/2]
uint16_t Net::IpHdr::id () const inline
Definition at line 259 of file inet.hh.
Referenced by IGbE::RxDescCache::pktComplete(), IGbE::TxDescCache::pktComplete(), NSGigE::recvPacket(), Sinic::Device::rxKick(), NSGigE::rxKick(), and Sinic::Device::transmit().
id() [2/2]
void Net::IpHdr::id (uint16_t _id) inline
Definition at line 269 of file inet.hh.
len() [1/2]
uint16_t Net::IpHdr::len () const inline
Definition at line 258 of file inet.hh.
Referenced by Net::__tu_cksum(), and IGbE::TxDescCache::pktComplete().
len() [2/2]
void Net::IpHdr::len (uint16_t _len) inline
Definition at line 270 of file inet.hh.
options()
bool Net::IpHdr::options (std::vector< const IpOpt *> & vec) const
Definition at line 262 of file inet.cc.
References data, Net::IpOpt::len(), and ArmISA::len.
payload() [1/2]
const uint8_t* Net::IpHdr::payload () const inline
Definition at line 276 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
Referenced by Net::__tu_cksum().
payload() [2/2]
uint8_t* Net::IpHdr::payload () inline
Definition at line 278 of file inet.hh.
References Net::EthAddr::bytes(), and Net::EthAddr::size().
proto()
uint8_t Net::IpHdr::proto () const inline
Definition at line 263 of file inet.hh.
size()
int Net::IpHdr::size () const inline
Definition at line 274 of file inet.hh.
src()
uint32_t Net::IpHdr::src () const inline
Definition at line 265 of file inet.hh.
sum() [1/2]
uint16_t Net::IpHdr::sum () const inline
Definition at line 264 of file inet.hh.
Referenced by IGbE::TxDescCache::pktComplete(), Sinic::Device::txKick(), and NSGigE::txKick().
sum() [2/2]
void Net::IpHdr::sum (uint16_t sum) inline
Definition at line 268 of file inet.hh.
References sum().
Referenced by sum().
tos()
uint8_t Net::IpHdr::tos () const inline
Definition at line 257 of file inet.hh.
ttl()
uint8_t Net::IpHdr::ttl () const inline
Definition at line 262 of file inet.hh.
version()
uint8_t Net::IpHdr::version () const inline
Definition at line 255 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc