gem5: ArmISA::PMU::PMUEvent Struct Reference
ArmISA::PMU::PMUEvent Struct Reference abstract
Event definition base class.
#include <pmu.hh>
Public Member Functions
PMUEvent ()
virtual ~PMUEvent ()
void attachEvent (PMU::CounterState *user)
attach this event to a given counter
void detachEvent (PMU::CounterState *user)
detach this event from a given counter
virtual void increment (const uint64_t val)
notify an event increment of val units, all the attached counters' value is incremented by val units.
virtual void enable ()=0
Enable the current event.
virtual void disable ()=0
Disable the current event.
virtual void updateAttachedCounters ()
Method called immediately before a counter access in order for the associated event to update its state (if required)
Protected Attributes
std::set< PMU::CounterState * > userCounters
set of counters using this event
Detailed Description
Event definition base class.
Definition at line 295 of file pmu.hh.
Constructor & Destructor Documentation
PMUEvent()
ArmISA::PMU::PMUEvent::PMUEvent () inline
Definition at line 297 of file pmu.hh.
~PMUEvent()
virtual ArmISA::PMU::PMUEvent::~PMUEvent () inline virtual
Definition at line 299 of file pmu.hh.
References attachEvent(), detachEvent(), disable(), enable(), increment(), and AlphaISA::Kernel::user.
Member Function Documentation
attachEvent()
void ArmISA::PMU::PMUEvent::attachEvent (PMU::CounterState * user)
attach this event to a given counter
Parameters
a pointer to the counter where to attach this event
Definition at line 446 of file pmu.cc.
References X86ISA::enable.
Referenced by ~PMUEvent().
detachEvent()
void ArmISA::PMU::PMUEvent::detachEvent (PMU::CounterState * user)
detach this event from a given counter
Parameters
a pointer to the counter where to detach this event from
Definition at line 464 of file pmu.cc.
References Trace::disable().
Referenced by ~PMUEvent().
disable()
virtual void ArmISA::PMU::PMUEvent::disable () pure virtual
Disable the current event.
Implemented in ArmISA::PMU::SWIncrementEvent, and ArmISA::PMU::RegularEvent.
Referenced by ~PMUEvent().
enable()
virtual void ArmISA::PMU::PMUEvent::enable () pure virtual
Enable the current event.
Implemented in ArmISA::PMU::SWIncrementEvent, and ArmISA::PMU::RegularEvent.
Referenced by ~PMUEvent().
increment()
void ArmISA::PMU::PMUEvent::increment (const uint64_t val) virtual
notify an event increment of val units, all the attached counters' value is incremented by val units.
Parameters
the quantity by which to increment the attached counter values
Definition at line 456 of file pmu.cc.
Referenced by ~PMUEvent().
updateAttachedCounters()
virtual void ArmISA::PMU::PMUEvent::updateAttachedCounters () inline virtual
Method called immediately before a counter access in order for the associated event to update its state (if required)
Definition at line 338 of file pmu.hh.
Member Data Documentation
userCounters
std::set<PMU::CounterState*> ArmISA::PMU::PMUEvent::userCounters protected
set of counters using this event
Definition at line 343 of file pmu.hh.
The documentation for this struct was generated from the following files:
arch/arm/pmu.hh
arch/arm/pmu.cc