gem5: SignaturePathPrefetcher::PatternEntry Struct Reference
SignaturePathPrefetcher::PatternEntry Struct Reference
Pattern entry data type, a set of stride and counter entries.
#include <signature_path.hh>
Public Member Functions
PatternEntry (size_t num_strides, unsigned counter_bits)
void reset () override
Reset the entries to their initial values.
PatternStrideEntry * findStride (stride_t stride)
Returns the entry with the desired stride.
PatternStrideEntry & getStrideEntry (stride_t stride)
Gets the entry with the provided stride, if there is no entry with the associated stride, it replaces one of them.
Public Member Functions inherited from TaggedEntry
TaggedEntry ()
virtual ~TaggedEntry ()
bool isValid () const
Consult the valid bit.
void setValid ()
Sets the entry to valid.
void setInvalid ()
Sets the entry to invalid.
Addr getTag () const
Obtain the entry tag.
void setTag (Addr t)
Sets the tag of the entry.
bool isSecure () const
Consult if this entry refers to a memory in the secure area.
void setSecure (bool s)
Sets the secure value bit.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
std::vector< PatternStrideEntry > strideEntries
group of stides
SatCounter counter
use counter, used by SPPv2
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Additional Inherited Members
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
Pattern entry data type, a set of stride and counter entries.
Definition at line 95 of file signature_path.hh.
Constructor & Destructor Documentation
PatternEntry()
SignaturePathPrefetcher::PatternEntry::PatternEntry (size_t num_strides, unsigned counter_bits) inline
Definition at line 101 of file signature_path.hh.
Member Function Documentation
findStride()
PatternStrideEntry* SignaturePathPrefetcher::PatternEntry::findStride (stride_t stride) inline
Returns the entry with the desired stride.
Parameters
stride the stride to find
Returns
a pointer to the entry, if the stride was found, or nullptr, if the stride was not found
Definition at line 121 of file signature_path.hh.
References ArmISA::stride.
getStrideEntry()
SignaturePathPrefetcher::PatternStrideEntry & SignaturePathPrefetcher::PatternEntry::getStrideEntry (stride_t stride)
Gets the entry with the provided stride, if there is no entry with the associated stride, it replaces one of them.
Parameters
stride the stride to find
Returns
reference to the selected entry
Definition at line 67 of file signature_path.cc.
References SignaturePathPrefetcher::PatternStrideEntry::counter, SatCounter::counter, SatCounter::reset(), SignaturePathPrefetcher::PatternStrideEntry::stride, and ArmISA::stride.
Referenced by SignaturePathPrefetcher::updatePatternTable().
reset()
void SignaturePathPrefetcher::PatternEntry::reset () inline override virtual
Reset the entries to their initial values.
Reimplemented from TaggedEntry.
Definition at line 106 of file signature_path.hh.
References SatCounter::reset().
Member Data Documentation
counter
SatCounter SignaturePathPrefetcher::PatternEntry::counter
use counter, used by SPPv2
Definition at line 100 of file signature_path.hh.
Referenced by SignaturePathPrefetcherV2::calculateLookaheadConfidence(), SignaturePathPrefetcherV2::calculatePrefetchConfidence(), and SignaturePathPrefetcherV2::increasePatternEntryCounter().
strideEntries
std::vector<PatternStrideEntry> SignaturePathPrefetcher::PatternEntry::strideEntries
group of stides
Definition at line 98 of file signature_path.hh.
Referenced by SignaturePathPrefetcher::calculatePrefetch(), and SignaturePathPrefetcherV2::increasePatternEntryCounter().
The documentation for this struct was generated from the following files:
mem/cache/prefetch/signature_path.hh
mem/cache/prefetch/signature_path.cc