gem5: ExtensionPool< T >::entry Struct Reference
ExtensionPool< T >::entry Struct Reference
Public Member Functions
entry (T *content)
Public Attributes
T * that
entry * next
Detailed Description
template<class T>
struct ExtensionPool< T >::entry
Definition at line 25 of file extensionPool.h.
Constructor & Destructor Documentation
entry()
template<class T> ExtensionPool< T >::entry::entry (T * content) inline
Definition at line 27 of file extensionPool.h.
References ExtensionPool< T >::entry::next, and ExtensionPool< T >::entry::that.
Referenced by ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::construct(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::ExtensionPool(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::free(), and ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::~ExtensionPool().
Member Data Documentation
next
template<class T> entry* ExtensionPool< T >::entry::next
Definition at line 32 of file extensionPool.h.
Referenced by ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::construct(), ExtensionPool< T >::entry::entry(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::free(), and ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::~ExtensionPool().
that
template<class T> T* ExtensionPool< T >::entry::that
Definition at line 31 of file extensionPool.h.
Referenced by ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::construct(), ExtensionPool< T >::entry::entry(), ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::ExtensionPool(), and ExtensionPool< MultiSocketSimpleSwitchAT::ConnectionInfo >::free().
The documentation for this struct was generated from the following file:
systemc/tests/tlm/multi_sockets/extensionPool.h