gem5: sc_gem5::NodeList< T > Struct Template Reference
sc_gem5::NodeList< T > Struct Template Reference
#include <list.hh>
Public Member Functions
NodeList ()
void pushFirst (T *t)
void pushLast (T *t)
T * getNext ()
bool empty ()
Public Member Functions inherited from sc_gem5::ListNode
ListNode ()
virtual ~ListNode ()
void popListNode ()
Additional Inherited Members
Public Attributes inherited from sc_gem5::ListNode
ListNode * nextListNode
ListNode * prevListNode
Detailed Description
template<typename T>
struct sc_gem5::NodeList< T >
Definition at line 65 of file list.hh.
Constructor & Destructor Documentation
NodeList()
template<typename T> sc_gem5::NodeList< T >::NodeList () inline
Definition at line 67 of file list.hh.
Member Function Documentation
empty()
template<typename T> bool sc_gem5::NodeList< T >::empty () inline
Definition at line 108 of file list.hh.
Referenced by sc_gem5::Scheduler::pendingCurr(), sc_gem5::Scheduler::runReady(), and sc_gem5::Scheduler::starved().
getNext()
template<typename T> T* sc_gem5::NodeList< T >::getNext () inline
Definition at line 107 of file list.hh.
Referenced by sc_gem5::Scheduler::clear(), sc_gem5::Scheduler::getNextReady(), sc_gem5::Scheduler::initPhase(), and sc_gem5::Scheduler::runUpdate().
pushFirst()
template<typename T> void sc_gem5::NodeList< T >::pushFirst (T * t) inline
Definition at line 74 of file list.hh.
Referenced by sc_gem5::Scheduler::runNext(), and sc_gem5::Scheduler::runNow().
pushLast()
template<typename T> void sc_gem5::NodeList< T >::pushLast (T * t) inline
Definition at line 91 of file list.hh.
Referenced by sc_gem5::Scheduler::asyncRequestUpdate(), sc_gem5::Scheduler::ready(), sc_gem5::Scheduler::reg(), sc_gem5::Scheduler::requestUpdate(), sc_gem5::Scheduler::resume(), and sc_gem5::Scheduler::runUpdate().
The documentation for this struct was generated from the following file:
systemc/core/list.hh