gem5: EtherSwitch::Interface::PortFifoEntry Struct Reference
EtherSwitch::Interface::PortFifoEntry Struct Reference
#include <etherswitch.hh>
Public Member Functions
PortFifoEntry (EthPacketPtr pkt, Tick recv_tick, unsigned id)
~PortFifoEntry ()
void serialize (CheckpointOut &cp) const
Serialize an object.
void unserialize (CheckpointIn &cp)
Unserialize an object.
Public Member Functions inherited from Serializable
Serializable ()
virtual ~Serializable ()
void serializeSection (CheckpointOut &cp, const char *name) const
Serialize an object into a new section.
void serializeSection (CheckpointOut &cp, const std::string &name) const
void unserializeSection (CheckpointIn &cp, const char *name)
Unserialize an a child object.
void unserializeSection (CheckpointIn &cp, const std::string &name)
Public Attributes
EthPacketPtr packet
Tick recvTick
unsigned srcId
Additional Inherited Members
Static Public Member Functions inherited from Serializable
static const std::string & currentSection ()
Get the fully-qualified name of the active section.
static void serializeAll (const std::string &cpt_dir)
static void unserializeGlobals (CheckpointIn &cp)
Static Public Attributes inherited from Serializable
static int ckptCount = 0
static int ckptMaxCount = 0
static int ckptPrevCount = -1
Detailed Description
Definition at line 103 of file etherswitch.hh.
Constructor & Destructor Documentation
PortFifoEntry()
EtherSwitch::Interface::PortFifoEntry::PortFifoEntry (EthPacketPtr pkt, Tick recv_tick, unsigned id) inline
Definition at line 105 of file etherswitch.hh.
~PortFifoEntry()
EtherSwitch::Interface::PortFifoEntry::~PortFifoEntry () inline
Definition at line 112 of file etherswitch.hh.
References serialize(), and unserialize().
Member Function Documentation
serialize()
void EtherSwitch::Interface::PortFifoEntry::serialize (CheckpointOut & cp) const virtual
Serialize an object.
Output an object's state into the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 304 of file etherswitch.cc.
References SERIALIZE_SCALAR.
Referenced by EtherSwitch::Interface::PortFifo::size(), and ~PortFifoEntry().
unserialize()
void EtherSwitch::Interface::PortFifoEntry::unserialize (CheckpointIn & cp) virtual
Unserialize an object.
Read an object's state from the current checkpoint section.
Parameters
cp Checkpoint state
Implements Serializable.
Definition at line 312 of file etherswitch.cc.
References UNSERIALIZE_SCALAR.
Referenced by EtherSwitch::Interface::PortFifo::size(), and ~PortFifoEntry().
Member Data Documentation
packet
EthPacketPtr EtherSwitch::Interface::PortFifoEntry::packet
Definition at line 108 of file etherswitch.hh.
recvTick
Tick EtherSwitch::Interface::PortFifoEntry::recvTick
Definition at line 109 of file etherswitch.hh.
Referenced by EtherSwitch::Interface::PortFifo::EntryOrder::operator()().
srcId
unsigned EtherSwitch::Interface::PortFifoEntry::srcId
Definition at line 111 of file etherswitch.hh.
Referenced by EtherSwitch::Interface::PortFifo::EntryOrder::operator()().
The documentation for this struct was generated from the following files:
dev/net/etherswitch.hh
dev/net/etherswitch.cc