gem5: Trace::TarmacTracerRecordV8::TraceMemEntryV8 Struct Reference
Trace::TarmacTracerRecordV8::TraceMemEntryV8 Struct Reference
Memory Entry for V8.
#include <tarmac_record_v8.hh>
Public Member Functions
TraceMemEntryV8 (const TarmacContext &tarmCtx, uint8_t _size, Addr _addr, uint64_t _data)
virtual void print (std::ostream &outs, int verbosity=0, const std::string &prefix="") const override
Public Member Functions inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
TraceEntryV8 (std::string _cpuName)
Protected Attributes
Addr paddr
Protected Attributes inherited from Trace::TarmacTracerRecordV8::TraceEntryV8
std::string cpuName
Detailed Description
Memory Entry for V8.
Definition at line 133 of file tarmac_record_v8.hh.
Constructor & Destructor Documentation
TraceMemEntryV8()
Trace::TarmacTracerRecordV8::TraceMemEntryV8::TraceMemEntryV8 (const TarmacContext & tarmCtx, uint8_t _size, Addr _addr, uint64_t _data)
Definition at line 63 of file tarmac_record_v8.cc.
References Trace::InstRecord::addr, ThreadContext::getDTBPtr(), paddr, Trace::InstRecord::thread, Trace::TarmacContext::thread, and ArmISA::TLB::translateFunctional().
Member Function Documentation
print()
void Trace::TarmacTracerRecordV8::TraceMemEntryV8::print (std::ostream & outs, int verbosity = 0, const std::string & prefix = "") const override virtual
Definition at line 265 of file tarmac_record_v8.cc.
References Trace::InstRecord::addr, ccprintf(), Trace::TarmacTracerRecordV8::TraceEntryV8::cpuName, curTick(), Trace::InstRecord::data, and Trace::InstRecord::size.
Member Data Documentation
paddr
Addr Trace::TarmacTracerRecordV8::TraceMemEntryV8::paddr protected
Definition at line 144 of file tarmac_record_v8.hh.
Referenced by TraceMemEntryV8().
The documentation for this struct was generated from the following files:
arch/arm/tracers/tarmac_record_v8.hh
arch/arm/tracers/tarmac_record_v8.cc