gem5: DeltaCorrelatingPredictionTables::DCPTEntry Struct Reference
DeltaCorrelatingPredictionTables::DCPTEntry Struct Reference
DCPT Table entry datatype.
Public Member Functions
DCPTEntry (unsigned int num_deltas)
Constructor.
void reset () override
Reset callback called when invalidating the entry.
void addAddress (Addr address, unsigned int delta_num_bits)
Adds an address to the entry, if the entry already existed, a delta will be generated.
void getCandidates (std::vector< QueuedPrefetcher::AddrPriority > &pfs, unsigned int mask_bits) const
Attempt to generate prefetch candidates using the two most recent deltas.
Public Member Functions inherited from TaggedEntry
TaggedEntry ()
virtual ~TaggedEntry ()
bool isValid () const
Consult the valid bit.
void setValid ()
Sets the entry to valid.
void setInvalid ()
Sets the entry to invalid.
Addr getTag () const
Obtain the entry tag.
void setTag (Addr t)
Sets the tag of the entry.
bool isSecure () const
Consult if this entry refers to a memory in the secure area.
void setSecure (bool s)
Sets the secure value bit.
Public Member Functions inherited from ReplaceableEntry
ReplaceableEntry ()=default
virtual ~ReplaceableEntry ()=default
virtual void setPosition (const uint32_t set, const uint32_t way)
Set both the set and way.
uint32_t getSet () const
Get set number.
uint32_t getWay () const
Get way number.
Public Attributes
Addr lastAddress
Last accessed address.
unsigned int deltaPointer
Position of the first free entry, or the oldest element, if it is full.
std::vector< Addr > deltas
Stored deltas.
Public Attributes inherited from ReplaceableEntry
std::shared_ptr< ReplacementData > replacementData
Replacement data associated to this entry.
Additional Inherited Members
Protected Attributes inherited from ReplaceableEntry
uint32_t _set
Set to which this entry belongs.
uint32_t _way
Way (relative position within the set) to which this entry belongs.
Detailed Description
DCPT Table entry datatype.
Definition at line 62 of file delta_correlating_prediction_tables.hh.
Constructor & Destructor Documentation
DCPTEntry()
DeltaCorrelatingPredictionTables::DCPTEntry::DCPTEntry (unsigned int num_deltas) inline
Constructor.
Parameters
num_deltas number of deltas stored in the entry
Definition at line 78 of file delta_correlating_prediction_tables.hh.
References addAddress(), getCandidates(), and reset().
Member Function Documentation
addAddress()
void DeltaCorrelatingPredictionTables::DCPTEntry::addAddress (Addr address, unsigned int delta_num_bits)
Adds an address to the entry, if the entry already existed, a delta will be generated.
Parameters
address address to add
delta_num_bits number of bits of the delta
Definition at line 57 of file delta_correlating_prediction_tables.cc.
Referenced by DeltaCorrelatingPredictionTables::calculatePrefetch(), and DCPTEntry().
getCandidates()
void DeltaCorrelatingPredictionTables::DCPTEntry::getCandidates (std::vector< QueuedPrefetcher::AddrPriority > & pfs, unsigned int mask_bits) const
Attempt to generate prefetch candidates using the two most recent deltas.
Prefetch candidates are added to the provided vector.
Parameters
pfs reference to a vector where candidates will be added
mask_bits the number of lower bits that should be masked (ignored) when comparing deltas
Definition at line 82 of file delta_correlating_prediction_tables.cc.
References addr, and ArmISA::i.
Referenced by DeltaCorrelatingPredictionTables::calculatePrefetch(), and DCPTEntry().
reset()
void DeltaCorrelatingPredictionTables::DCPTEntry::reset () override virtual
Reset callback called when invalidating the entry.
Reimplemented from TaggedEntry.
Definition at line 47 of file delta_correlating_prediction_tables.cc.
Referenced by DCPTEntry().
Member Data Documentation
deltaPointer
unsigned int DeltaCorrelatingPredictionTables::DCPTEntry::deltaPointer
Position of the first free entry, or the oldest element, if it is full.
Definition at line 70 of file delta_correlating_prediction_tables.hh.
deltas
std::vector<Addr> DeltaCorrelatingPredictionTables::DCPTEntry::deltas
Stored deltas.
Definition at line 72 of file delta_correlating_prediction_tables.hh.
lastAddress
Addr DeltaCorrelatingPredictionTables::DCPTEntry::lastAddress
Last accessed address.
Definition at line 65 of file delta_correlating_prediction_tables.hh.
Referenced by DeltaCorrelatingPredictionTables::calculatePrefetch().
The documentation for this struct was generated from the following files:
mem/cache/prefetch/delta_correlating_prediction_tables.hh
mem/cache/prefetch/delta_correlating_prediction_tables.cc