gem5: std::hash< X86ISA::ExtMachInst > Struct Template Reference
std::hash< X86ISA::ExtMachInst > Struct Template Reference
#include <types.hh>
Public Member Functions
size_t operator() (const X86ISA::ExtMachInst &emi) const
Detailed Description
template<>
struct std::hash< X86ISA::ExtMachInst >
Definition at line 357 of file types.hh.
Member Function Documentation
operator()()
size_t std::hash< X86ISA::ExtMachInst >::operator() (const X86ISA::ExtMachInst & emi) const inline
Definition at line 358 of file types.hh.
References X86ISA::ExtMachInst::addrSize, X86ISA::ExtMachInst::displacement, X86ISA::ExtMachInst::dispSize, X86ISA::ExtMachInst::immediate, X86ISA::ExtMachInst::legacy, X86ISA::ExtMachInst::mode, X86ISA::ExtMachInst::modRM, name(), X86ISA::ExtMachInst::op, X86ISA::ExtMachInst::opcode, X86ISA::ExtMachInst::opSize, paramIn(), paramOut(), X86ISA::ExtMachInst::rex, X86ISA::ExtMachInst::sib, X86ISA::ExtMachInst::stackSize, X86ISA::ExtMachInst::type, and X86ISA::ExtMachInst::vex.
The documentation for this struct was generated from the following file:
arch/x86/types.hh