gem5: sim/syscall_emul.hh File Reference
syscall_emul.hh File Reference
This file defines objects used to emulate syscalls from the target application on the host machine.
#include <sys/mount.h>
#include <fcntl.h>
#include <net/if.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include <cerrno>
#include <memory>
#include <string>
#include "arch/generic/tlb.hh"
#include "arch/utility.hh"
#include "base/intmath.hh"
#include "base/loader/object_file.hh"
#include "base/logging.hh"
#include "base/trace.hh"
#include "base/types.hh"
#include "config/the_isa.hh"
#include "cpu/base.hh"
#include "cpu/thread_context.hh"
#include "mem/page_table.hh"
#include "params/Process.hh"
#include "sim/emul_driver.hh"
#include "sim/futex_map.hh"
#include "sim/process.hh"
#include "sim/syscall_debug_macros.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul_buf.hh"
#include "sim/syscall_return.hh"
Macros
#define NO_STAT64 0
Typedefs
typedef struct statfs hst_statfs
typedef struct stat hst_stat
typedef struct stat64 hst_stat64
Functions
void warnUnsupportedOS (std::string syscall_name)
SyscallReturn unimplementedFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Handler for unimplemented syscalls that we haven't thought about.
SyscallReturn ignoreFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.) and should not affect the correct behavior of the program.
SyscallReturn fallocateFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn exitFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target exit() handler: terminate current context.
SyscallReturn exitGroupFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target exit_group() handler: terminate simulation. (exit all threads)
SyscallReturn setTidAddressFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target set_tid_address() handler.
SyscallReturn getpagesizeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getpagesize() handler.
SyscallReturn brkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target brk() handler: set brk address.
SyscallReturn closeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target close() handler.
SyscallReturn lseekFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target lseek() handler.
SyscallReturn _llseekFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target _llseek() handler.
SyscallReturn munmapFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target munmap() handler.
SyscallReturn shutdownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target shutdown() handler.
SyscallReturn gethostnameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target gethostname() handler.
SyscallReturn getcwdFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getcwd() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc, int index=0)
Target readlink() handler.
SyscallReturn readlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn unlinkHelper (SyscallDesc *desc, int num, ThreadContext *tc, int index)
Target unlink() handler.
SyscallReturn unlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn linkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target link() handler.
SyscallReturn symlinkFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target symlink() handler.
SyscallReturn mkdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target mkdir() handler.
SyscallReturn mknodFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target mknod() handler.
SyscallReturn chdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target chdir() handler.
SyscallReturn rmdirFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn renameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target rename() handler.
SyscallReturn truncateFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target truncate() handler.
SyscallReturn ftruncateFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target ftruncate() handler.
SyscallReturn truncate64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target truncate64() handler.
SyscallReturn ftruncate64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target ftruncate64() handler.
SyscallReturn umaskFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target umask() handler.
SyscallReturn gettidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target gettid() handler.
SyscallReturn chownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target chown() handler.
SyscallReturn getpgrpFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getpgrpFunc() handler.
SyscallReturn setpgidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target setpgid() handler.
SyscallReturn fchownFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target fchown() handler.
SyscallReturn dupFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target dup() handler.
SyscallReturn dup2Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target dup2() handler.
SyscallReturn fcntlFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target fcntl() handler.
SyscallReturn fcntl64Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target fcntl64() handler.
SyscallReturn setuidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target setuid() handler.
SyscallReturn pipeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target pipe() handler.
SyscallReturn pipeImpl (SyscallDesc *desc, int num, ThreadContext *tc, bool pseudo_pipe, bool is_pipe2=false)
Internal pipe() handler.
SyscallReturn pipe2Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target pipe() handler.
SyscallReturn getpidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getpid() handler.
SyscallReturn getpeernameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn bindFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn listenFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn connectFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn sendtoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn recvfromFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn recvmsgFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn sendmsgFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getuidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getgidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getgid() handler.
SyscallReturn getppidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getppid() handler.
SyscallReturn geteuidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target geteuid() handler.
SyscallReturn getegidFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getegid() handler.
SyscallReturn accessFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target access() handler.
SyscallReturn accessFunc (SyscallDesc *desc, int num, ThreadContext *tc, int index)
SyscallReturn getsockoptFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn setsockoptFunc (SyscallDesc *desc, int num, ThreadContext *tc)
SyscallReturn getsocknameFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn futexFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Futex system call Implemented by Daniel Sanchez Used by printf's in multi-threaded apps.
SyscallReturn pipePseudoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
SyscallReturn getpidPseudoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getpidPseudo() handler.
SyscallReturn getuidPseudoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getuidPseudo() handler.
SyscallReturn getgidPseudoFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target getgidPseudo() handler.
template<class T1 , class T2 >
void getElapsedTimeMicro (T1 &sec, T2 &usec)
Helper function to convert current elapsed time to seconds and microseconds.
template<class T1 , class T2 >
void getElapsedTimeNano (T1 &sec, T2 &nsec)
Helper function to convert current elapsed time to seconds and nanoseconds.
template<typename target_stat , typename host_stat >
void convertStatBuf (target_stat &tgt, host_stat *host, ByteOrder bo, bool fakeTTY=false)
template<typename target_stat , typename host_stat64 >
void convertStat64Buf (target_stat &tgt, host_stat64 *host, ByteOrder bo, bool fakeTTY=false)
template<class OS >
void copyOutStatBuf (PortProxy &mem, Addr addr, hst_stat *host, bool fakeTTY=false)
template<class OS >
void copyOutStat64Buf (PortProxy &mem, Addr addr, hst_stat64 *host, bool fakeTTY=false)
template<class OS >
void copyOutStatfsBuf (PortProxy &mem, Addr addr, hst_statfs *host)
template<class OS >
SyscallReturn ioctlFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target ioctl() handler.
template<class OS >
SyscallReturn openImpl (SyscallDesc *desc, int callnum, ThreadContext *tc, bool isopenat)
template<class OS >
SyscallReturn openFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target open() handler.
template<class OS >
SyscallReturn openatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target openat() handler.
template<class OS >
SyscallReturn unlinkatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target unlinkat() handler.
template<class OS >
SyscallReturn faccessatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target facessat() handler.
template<class OS >
SyscallReturn readlinkatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target readlinkat() handler.
template<class OS >
SyscallReturn renameatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target renameat() handler.
template<class OS >
SyscallReturn sysinfoFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target sysinfo() handler.
template<class OS >
SyscallReturn chmodFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target chmod() handler.
template<class OS >
SyscallReturn pollFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn fchmodFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target fchmod() handler.
template<class OS >
SyscallReturn mremapFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target mremap() handler.
template<class OS >
SyscallReturn statFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target stat() handler.
template<class OS >
SyscallReturn stat64Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target stat64() handler.
template<class OS >
SyscallReturn fstatat64Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target fstatat64() handler.
template<class OS >
SyscallReturn fstat64Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target fstat64() handler.
template<class OS >
SyscallReturn lstatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target lstat() handler.
template<class OS >
SyscallReturn lstat64Func (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target lstat64() handler.
template<class OS >
SyscallReturn fstatFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target fstat() handler.
template<class OS >
SyscallReturn statfsFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target statfs() handler.
template<class OS >
SyscallReturn cloneFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
template<class OS >
SyscallReturn fstatfsFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target fstatfs() handler.
template<class OS >
SyscallReturn readvFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target readv() handler.
template<class OS >
SyscallReturn writevFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target writev() handler.
template<class OS >
SyscallReturn mmapImpl (SyscallDesc *desc, int num, ThreadContext *tc, bool is_mmap2)
Real mmap handler.
template<class OS >
SyscallReturn pwrite64Func (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn mmapFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target mmap() handler.
template<class OS >
SyscallReturn mmap2Func (SyscallDesc *desc, int num, ThreadContext *tc)
Target mmap2() handler.
template<class OS >
SyscallReturn getrlimitFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getrlimit() handler.
template<class OS >
SyscallReturn prlimitFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
template<class OS >
SyscallReturn clock_gettimeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target clock_gettime() function.
template<class OS >
SyscallReturn clock_getresFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target clock_getres() function.
template<class OS >
SyscallReturn gettimeofdayFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target gettimeofday() handler.
template<class OS >
SyscallReturn utimesFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target utimes() handler.
template<class OS >
SyscallReturn execveFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
template<class OS >
SyscallReturn getrusageFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target getrusage() function.
template<class OS >
SyscallReturn timesFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target times() function.
template<class OS >
SyscallReturn timeFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
Target time() function.
template<class OS >
SyscallReturn tgkillFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn socketFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn socketpairFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn selectFunc (SyscallDesc *desc, int callnum, ThreadContext *tc)
template<class OS >
SyscallReturn readFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn writeFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn wait4Func (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn acceptFunc (SyscallDesc *desc, int num, ThreadContext *tc)
template<class OS >
SyscallReturn eventfdFunc (SyscallDesc *desc, int num, ThreadContext *tc)
Target eventfd() function.
Variables
const int one_million = 1000000
A readable name for 1,000,000, for converting microseconds to seconds.
const int one_billion = 1000000000
A readable name for 1,000,000,000, for converting nanoseconds to seconds.
const unsigned seconds_since_epoch = 1000000000
Approximate seconds since the epoch (1/1/1970).
Detailed Description
This file defines objects used to emulate syscalls from the target application on the host machine.
Definition in file syscall_emul.hh.
Macro Definition Documentation
NO_STAT64
#define NO_STAT64 0
Definition at line 53 of file syscall_emul.hh.
Typedef Documentation
hst_stat
typedef struct stat hst_stat
Definition at line 531 of file syscall_emul.hh.
hst_stat64
typedef struct stat64 hst_stat64
Definition at line 532 of file syscall_emul.hh.
hst_statfs
typedef struct statfs hst_statfs
Definition at line 526 of file syscall_emul.hh.
Function Documentation
_llseekFunc()
SyscallReturn _llseekFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target _llseek() handler.
Definition at line 332 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), System::getGuestByteOrder(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, ArmISA::offset, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), and unameFunc().
acceptFunc()
template<class OS > SyscallReturn acceptFunc (SyscallDesc * desc, int num, ThreadContext * tc)
We poll the socket file descriptor first to guarantee that we do not block on our accept call. The socket can be opened without the non-blocking flag (it blocks). This will cause deadlocks between communicating processes.
Definition at line 2748 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, SyscallReturn::retry(), and ArmISA::sa.
accessFunc() [1/2]
SyscallReturn accessFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target access() handler.
Definition at line 1167 of file syscall_emul.cc.
References accessFunc().
Referenced by faccessatFunc().
accessFunc() [2/2]
SyscallReturn accessFunc (SyscallDesc * desc, int num, ThreadContext * tc, int index)
Definition at line 1150 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
Referenced by accessFunc(), and unameFunc32().
bindFunc()
SyscallReturn bindFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1327 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::status.
brkFunc()
SyscallReturn brkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target brk() handler: set brk address.
Definition at line 242 of file syscall_emul.cc.
References ChunkGenerator::done(), DPRINTF_SYSCALL, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, PortProxy::memsetBlob(), MipsISA::p, AlphaISA::PageBytes, roundDown(), and roundUp().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
chdirFunc()
SyscallReturn chdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target chdir() handler.
Definition at line 1190 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, startswith(), and PortProxy::tryReadString().
chmodFunc()
template<class OS > SyscallReturn chmodFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target chmod() handler.
Definition at line 1031 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::mode, and PortProxy::tryReadString().
chownFunc()
SyscallReturn chownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target chown() handler.
Definition at line 688 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
clock_getresFunc()
template<class OS > SyscallReturn clock_getresFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target clock_getres() function.
Definition at line 2057 of file syscall_emul.hh.
References BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
clock_gettimeFunc()
template<class OS > SyscallReturn clock_gettimeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target clock_gettime() function.
Definition at line 2037 of file syscall_emul.hh.
References ArmISA::byteOrder(), getElapsedTimeNano(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, MipsISA::p, and seconds_since_epoch.
cloneFunc()
template<class OS > SyscallReturn cloneFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Note that ProcessParams is generated by swig and there are no other examples of how to create anything but this default constructor. The fields are manually initialized instead of passing parameters to the constructor.
Definition at line 1496 of file syscall_emul.hh.
References ThreadContext::activate(), Process::assignThreadContext(), BufferArg::bufferPtr(), Process::childClearTID, ThreadContext::clearArchRegs(), ThreadContext::contextId(), BaseBufferArg::copyOut(), ThreadContext::cpuId(), DPRINTF_SYSCALL, fatal, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, Process::initState(), System::maxPID, MipsISA::p, panic, ThreadContext::pcState(), Process::pid(), Process::pTable, ThreadContext::readIntReg(), Process::revokeThreadContext(), ThreadContext::setIntReg(), ThreadContext::setProcessPtr(), Process::setSyscallReturn(), EmulationPageTable::shared, Process::sigchld, AlphaISA::SyscallPseudoReturnReg, AlphaISA::SyscallSuccessReg, ThreadContext::threadId(), and Process::useForClone.
closeFunc()
SyscallReturn closeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target close() handler.
Definition at line 302 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
connectFunc()
SyscallReturn connectFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1369 of file syscall_emul.cc.
References addr, BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::status.
convertStat64Buf()
template<typename target_stat , typename host_stat64 > void convertStat64Buf (target_stat & tgt, host_stat64 * host, ByteOrder bo, bool fakeTTY = false)
Definition at line 589 of file syscall_emul.hh.
References PowerISA::bo, and htog().
convertStatBuf()
template<typename target_stat , typename host_stat > void convertStatBuf (target_stat & tgt, host_stat * host, ByteOrder bo, bool fakeTTY = false)
Definition at line 541 of file syscall_emul.hh.
References htog().
copyOutStat64Buf()
template<class OS > void copyOutStat64Buf (PortProxy & mem, Addr addr, hst_stat64 * host, bool fakeTTY = false)
Definition at line 621 of file syscall_emul.hh.
References ArmISA::byteOrder().
copyOutStatBuf()
template<class OS > void copyOutStatBuf (PortProxy & mem, Addr addr, hst_stat * host, bool fakeTTY = false)
Definition at line 610 of file syscall_emul.hh.
References ArmISA::byteOrder().
copyOutStatfsBuf()
template<class OS > void copyOutStatfsBuf (PortProxy & mem, Addr addr, hst_statfs * host)
Definition at line 633 of file syscall_emul.hh.
References PowerISA::bo, ArmISA::byteOrder(), BaseBufferArg::copyOut(), and htog().
dup2Func()
SyscallReturn dup2Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target dup2() handler.
We need a valid host file descriptor number to be able to pass into the second parameter for dup2 (newfd), but we don't know what the viable numbers are; we execute the open call to retrieve one.
Definition at line 761 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by unameFunc32().
dupFunc()
SyscallReturn dupFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target dup() handler.
Target dup() handler.
Really, it's difficult to maintain fields like file offset or flags since an update to such a field won't be reflected in the metadata for the fd entries that we maintain for checkpoint restoration.
Definition at line 739 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), unameFunc(), and unameFunc32().
eventfdFunc()
template<class OS > SyscallReturn eventfdFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target eventfd() function.
Definition at line 2819 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and warnUnsupportedOS().
execveFunc()
template<class OS > SyscallReturn execveFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Note that ProcessParams is generated by swig and there are no other examples of how to create anything but this default constructor. The fields are manually initialized instead of passing parameters to the constructor.
Prevent process object creation with identical PIDs (which will trip a fatal check in Process constructor). The execve call is supposed to take over the currently executing process' identity but replace whatever it is doing with a new process image. Instead of hijacking the process object in the simulator, we create a new process object and bind to the previous process' thread below (hijacking the thread).
Work through the file descriptor array and close any files marked close-on-exec.
Definition at line 2129 of file syscall_emul.hh.
References ThreadContext::activate(), Process::assignThreadContext(), ArmISA::b, BufferArg::bufferPtr(), ThreadContext::clearArchRegs(), ThreadContext::contextId(), BaseBufferArg::copyIn(), Process::fds, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::i, sc_dt::inc(), MipsISA::index, Process::initState(), MipsISA::p, ThreadContext::pcState(), SyscallDesc::setFlags(), ThreadContext::setNPC(), ThreadContext::setProcessPtr(), Process::sigchld, SyscallDesc::SuppressReturnValue, and PortProxy::tryReadString().
exitFunc()
SyscallReturn exitFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target exit() handler: terminate current context.
Definition at line 223 of file syscall_emul.cc.
References exitImpl().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
exitGroupFunc()
SyscallReturn exitGroupFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target exit_group() handler: terminate simulation. (exit all threads)
Definition at line 229 of file syscall_emul.cc.
References exitImpl().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), tgkillFunc(), unameFunc(), and unameFunc32().
faccessatFunc()
template<class OS > SyscallReturn faccessatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target facessat() handler.
Definition at line 949 of file syscall_emul.hh.
References accessFunc(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), MipsISA::index, and warn.
fallocateFunc()
SyscallReturn fallocateFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1124 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, ArmISA::len, ArmISA::mode, ArmISA::offset, MipsISA::p, and warnUnsupportedOS().
Referenced by unameFunc32().
fchmodFunc()
template<class OS > SyscallReturn fchmodFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target fchmod() handler.
Definition at line 1138 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), MipsISA::index, ArmISA::mode, and MipsISA::p.
fchownFunc()
SyscallReturn fchownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target fchown() handler.
Definition at line 711 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
fcntl64Func()
SyscallReturn fcntl64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target fcntl64() handler.
Definition at line 837 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and warn.
Referenced by setThreadAreaFunc(), unameFunc(), and unameFunc32().
fcntlFunc()
SyscallReturn fcntlFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target fcntl() handler.
Definition at line 792 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and warn.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
fstat64Func()
template<class OS > SyscallReturn fstat64Func (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target fstat64() handler.
Definition at line 1341 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
fstatat64Func()
template<class OS > SyscallReturn fstatat64Func (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target fstatat64() handler.
Definition at line 1304 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), MipsISA::index, PortProxy::tryReadString(), and warn.
fstatfsFunc()
template<class OS > SyscallReturn fstatfsFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target fstatfs() handler.
Definition at line 1638 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
fstatFunc()
template<class OS > SyscallReturn fstatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target fstat() handler.
Definition at line 1436 of file syscall_emul.hh.
References DPRINTF_SYSCALL, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
ftruncate64Func()
SyscallReturn ftruncate64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target ftruncate64() handler.
Definition at line 656 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, length, and MipsISA::p.
Referenced by unameFunc(), and unameFunc32().
ftruncateFunc()
SyscallReturn ftruncateFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target ftruncate() handler.
Definition at line 614 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, length, and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
futexFunc()
template<class OS > SyscallReturn futexFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Futex system call Implemented by Daniel Sanchez Used by printf's in multi-threaded apps.
Definition at line 334 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), System::futexMap, getgidPseudoFunc(), getpidPseudoFunc(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getSystemPtr(), getuidPseudoFunc(), ThreadContext::getVirtProxy(), MipsISA::index, M5_VAR_USED, X86ISA::op, pipePseudoFunc(), FutexMap::requeue(), FutexMap::suspend(), FutexMap::suspend_bitset(), X86ISA::val, FutexMap::wakeup(), FutexMap::wakeup_bitset(), and warn.
getcwdFunc()
SyscallReturn getcwdFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getcwd() handler.
Definition at line 391 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
getegidFunc()
SyscallReturn getegidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getegid() handler.
Definition at line 1117 of file syscall_emul.cc.
References Process::egid(), and ThreadContext::getProcessPtr().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getElapsedTimeMicro()
template<class T1 , class T2 > void getElapsedTimeMicro (T1 & sec, T2 & usec)
Helper function to convert current elapsed time to seconds and microseconds.
Definition at line 501 of file syscall_emul.hh.
References curTick(), one_million, and SimClock::Int::us.
Referenced by getrusageFunc(), gettimeofdayFunc(), and timeFunc().
getElapsedTimeNano()
template<class T1 , class T2 > void getElapsedTimeNano (T1 & sec, T2 & nsec)
Helper function to convert current elapsed time to seconds and nanoseconds.
Definition at line 512 of file syscall_emul.hh.
References curTick(), SimClock::Int::ns, and one_billion.
Referenced by clock_gettimeFunc().
geteuidFunc()
SyscallReturn geteuidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target geteuid() handler.
Definition at line 1103 of file syscall_emul.cc.
References Process::euid(), and ThreadContext::getProcessPtr().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getgidFunc()
SyscallReturn getgidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getgid() handler.
Definition at line 1110 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::gid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getgidPseudoFunc()
SyscallReturn getgidPseudoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getgidPseudo() handler.
Definition at line 1055 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
gethostnameFunc()
SyscallReturn gethostnameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target gethostname() handler.
Definition at line 375 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), hostname, MipsISA::index, name(), and MipsISA::p.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
getpagesizeFunc()
SyscallReturn getpagesizeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getpagesize() handler.
Definition at line 235 of file syscall_emul.cc.
References AlphaISA::PageBytes.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
getpeernameFunc()
SyscallReturn getpeernameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1789 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
getpgrpFunc()
SyscallReturn getpgrpFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getpgrpFunc() handler.
Definition at line 986 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::pgid().
getpidFunc()
SyscallReturn getpidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getpid() handler.
Definition at line 1075 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::tgid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getpidPseudoFunc()
SyscallReturn getpidPseudoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getpidPseudo() handler.
Definition at line 1029 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
getppidFunc()
SyscallReturn getppidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getppid() handler.
Definition at line 1089 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::ppid().
Referenced by SparcISA::getresuidFunc(), and unameFunc32().
getrlimitFunc()
template<class OS > SyscallReturn getrlimitFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getrlimit() handler.
Definition at line 1952 of file syscall_emul.hh.
References PowerISA::bo, ArmISA::byteOrder(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, System::numContexts(), and warn.
getrusageFunc()
template<class OS > SyscallReturn getrusageFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target getrusage() function.
Definition at line 2222 of file syscall_emul.hh.
References ArmISA::byteOrder(), getElapsedTimeMicro(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, and warn.
getsocknameFunc()
SyscallReturn getsocknameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1749 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, MipsISA::p, ArmISA::sa, and ArmISA::status.
getsockoptFunc()
SyscallReturn getsockoptFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1706 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, X86ISA::level, MipsISA::p, ArmISA::status, and X86ISA::val.
gettidFunc()
SyscallReturn gettidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target gettid() handler.
Definition at line 1082 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::pid().
Referenced by unameFunc32().
gettimeofdayFunc()
template<class OS > SyscallReturn gettimeofdayFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target gettimeofday() handler.
Definition at line 2075 of file syscall_emul.hh.
References ArmISA::byteOrder(), getElapsedTimeMicro(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, and seconds_since_epoch.
getuidFunc()
SyscallReturn getuidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1096 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), and Process::uid().
Referenced by SparcISA::getresuidFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
getuidPseudoFunc()
SyscallReturn getuidPseudoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target getuidPseudo() handler.
Definition at line 1042 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by futexFunc(), and osf_setsysinfoFunc().
ignoreFunc()
SyscallReturn ignoreFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Handler for unimplemented syscalls that we never intend to implement (signal handling, etc.) and should not affect the correct behavior of the program.
Print a warning only if the appropriate trace flag is enabled. Return success to the target program.
Definition at line 76 of file syscall_emul.cc.
References SyscallDesc::name(), SyscallDesc::needWarning(), warn, and SyscallDesc::warnOnce().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
ioctlFunc()
template<class OS > SyscallReturn ioctlFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target ioctl() handler.
For the most part, programs call ioctl() only to find out if their stdout is a tty, to determine whether to do line or block buffering. We always claim that output fds are not TTYs to provide repeatable results.
For lack of a better return code, return ENOTTY. Ideally, we should return something better here, but at least we issue the warning.
Definition at line 681 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), DPRINTF_SYSCALL, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, EmulatedDriver::ioctl(), MipsISA::p, ThreadContext::pcState(), ArmISA::status, and warn.
linkFunc()
SyscallReturn linkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target link() handler.
Definition at line 510 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
listenFunc()
SyscallReturn listenFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1351 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, and ArmISA::status.
lseekFunc()
SyscallReturn lseekFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target lseek() handler.
Definition at line 312 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
lstat64Func()
template<class OS > SyscallReturn lstat64Func (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target lstat64() handler.
Definition at line 1402 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and PortProxy::tryReadString().
lstatFunc()
template<class OS > SyscallReturn lstatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target lstat() handler.
Definition at line 1373 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and PortProxy::tryReadString().
mkdirFunc()
SyscallReturn mkdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target mkdir() handler.
Definition at line 552 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc32().
mknodFunc()
SyscallReturn mknodFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target mknod() handler.
Definition at line 1173 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::mode, MipsISA::p, and PortProxy::tryReadString().
mmap2Func()
template<class OS > SyscallReturn mmap2Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target mmap2() handler.
Definition at line 1944 of file syscall_emul.hh.
mmapFunc()
template<class OS > SyscallReturn mmapFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target mmap() handler.
Definition at line 1936 of file syscall_emul.hh.
mmapImpl()
template<class OS > SyscallReturn mmapImpl (SyscallDesc * desc, int num, ThreadContext * tc, bool is_mmap2)
Real mmap handler.
Definition at line 1741 of file syscall_emul.hh.
References createObjectFile(), debugSymbolTable, DPRINTF_SYSCALL, fatal, BaseTLB::flushAll(), ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), ThreadContext::getProcessPtr(), HBFDEntry::getSimFD(), ThreadContext::getVirtProxy(), MipsISA::index, length, ObjectFile::loadAllSymbols(), EmulatedDriver::mmap(), ArmISA::offset, MipsISA::p, AlphaISA::PageBytes, ThreadContext::pcState(), X86ISA::prot, roundUp(), warn, and PortProxy::writeBlob().
mremapFunc()
template<class OS > SyscallReturn mremapFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target mremap() handler.
Definition at line 1160 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), MipsISA::index, AlphaISA::PageBytes, roundUp(), and warn.
munmapFunc()
SyscallReturn munmapFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target munmap() handler.
Definition at line 363 of file syscall_emul.cc.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
openatFunc()
template<class OS > SyscallReturn openatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target openat() handler.
Definition at line 927 of file syscall_emul.hh.
openFunc()
template<class OS > SyscallReturn openFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target open() handler.
Definition at line 919 of file syscall_emul.hh.
openImpl()
template<class OS > SyscallReturn openImpl (SyscallDesc * desc, int callnum, ThreadContext * tc, bool isopenat)
If using the openat variant, read in the target directory file descriptor from the simulated process.
Retrieve the simulated process' memory proxy and then read in the path string from that memory space into the host's working memory space.
Translate target flags into host flags. Flags exist which are not ported between architectures which can cause check failures.
If the simulated process called open or openat with AT_FDCWD specified, take the current working directory value which was passed into the process class as a Python parameter and append the current path to create a full path. Otherwise, openat with a valid target directory file descriptor has been called. If the path option, which was passed in as a parameter, is not absolute, retrieve the directory file descriptor's path and prepend it to the path passed in as a parameter. In every case, we should have a full path (which is relevant to the host) to work with after this block has been passed.
Since this is an emulated environment, we create pseudo file descriptors for device requests that have been registered with the process class through Python; this allows us to create a file descriptor for subsequent ioctl or mmap calls.
Fall through here for pass through to host devices, such as /dev/zero
We make several attempts resolve a call to open.
1) Resolve any path redirection before hand. This will set the path up with variable 'redir_path' which may contain a modified path or the original path value. This should already be done in prior code. 2) Try to handle the access using 'special_paths'. Some special_paths and files cannot be called on the host and need to be handled as special cases inside the simulator. These special_paths are handled by C++ routines to provide output back to userspace. 3) If the full path that was created above does not match any of the special cases, pass it through to the open call on the HOST to let the host open the file on our behalf. Again, the openImpl tries to USE_THE_HOST_FILESYSTEM_OPEN (with a possible redirection to the faux-filesystem files). The faux-filesystem is dynamically created during simulator configuration using Python functions. 4) If the host cannot open the file, the open attempt failed in "3)". Return the host's error code back through the system call to the simulated process. If running a debug trace, also notify the user that the open call failed.
Any success will set sim_fd to something other than -1 and skip the next conditions effectively bypassing them.
The file was opened successfully and needs to be recorded in the process' file descriptor array so that it can be retrieved later. The target file descriptor that is chosen will be the lowest unused file descriptor. Return the indirect target file descriptor back to the simulated process to act as a handle for the opened file.
Definition at line 760 of file syscall_emul.hh.
References DPRINTF_SYSCALL, FileFDEntry::getFileName(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::i, MipsISA::index, ArmISA::mode, EmulatedDriver::open(), MipsISA::p, startswith(), PortProxy::tryReadString(), and warn.
Referenced by ArmSemihosting::File::open().
pipe2Func()
SyscallReturn pipe2Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target pipe() handler.
Definition at line 978 of file syscall_emul.cc.
References pipeImpl().
pipeFunc()
SyscallReturn pipeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target pipe() handler.
Definition at line 972 of file syscall_emul.cc.
References pipeImpl().
Referenced by unameFunc32().
pipeImpl()
SyscallReturn pipeImpl (SyscallDesc * desc, int num, ThreadContext * tc, bool pseudo_pipe, bool is_pipe2 = false)
Internal pipe() handler.
Now patch the read object to record the target file descriptor chosen as the write end of the pipe.
Alpha Linux convention for pipe() is that fd[0] is returned as the return value of the function, and fd[1] is returned in r20.
Copy the target file descriptors into buffer space and then copy the buffer space back into the target address space.
Definition at line 869 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, ThreadContext::setIntReg(), and AlphaISA::SyscallPseudoReturnReg.
Referenced by pipe2Func(), pipeFunc(), and pipePseudoFunc().
pipePseudoFunc()
SyscallReturn pipePseudoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Pseudo Funcs - These functions use a different return convension, returning a second value in a register other than the normal return register.
Definition at line 966 of file syscall_emul.cc.
References pipeImpl().
Referenced by futexFunc(), SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), and unameFunc().
pollFunc()
template<class OS > SyscallReturn pollFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Record the target file descriptors in a local variable. We need to replace them with host file descriptors but we need a temporary copy for later. Afterwards, replace each target file descriptor in the poll_fd array with its host_fd.
We cannot allow an infinite poll to occur or it will inevitably cause a deadlock in the gem5 simulator with clone. We must pass in tmout with a non-negative value, however it also makes no sense to poll on the underlying host for any other time than tmout a zero timeout.
If blocking indefinitely, check the signal list to see if a signal would break the poll out of the retry cycle and try to return the signal interrupt instead.
Replace each host_fd in the returned poll_fd array with its original target file descriptor.
Copy out the pollfd struct because the host may have updated fields in the structure.
Definition at line 1061 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ArmISA::fd, ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, SyscallReturn::retry(), System::signalList, and ArmISA::status.
prlimitFunc()
template<class OS > SyscallReturn prlimitFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Definition at line 1993 of file syscall_emul.hh.
References PowerISA::bo, ArmISA::byteOrder(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, ArmISA::n, and warn.
pwrite64Func()
template<class OS > SyscallReturn pwrite64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1911 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::offset, and MipsISA::p.
readFunc()
template<class OS > SyscallReturn readFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 2613 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and SyscallReturn::retry().
readlinkatFunc()
template<class OS > SyscallReturn readlinkatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target readlinkat() handler.
Definition at line 962 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), MipsISA::index, readlinkFunc(), and warn.
readlinkFunc() [1/2]
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc, int index = 0)
Target readlink() handler.
Definition at line 429 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), fatal, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::p, PortProxy::tryReadString(), and warn_once.
Referenced by readlinkatFunc().
readlinkFunc() [2/2]
SyscallReturn readlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 423 of file syscall_emul.cc.
References readlinkFunc().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), readlinkFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
readvFunc()
template<class OS > SyscallReturn readvFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target readv() handler.
Definition at line 1664 of file syscall_emul.hh.
References ArmISA::byteOrder(), X86ISA::count, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), gtoh(), htog(), ArmISA::i, MipsISA::index, MipsISA::p, PortProxy::readBlob(), and PortProxy::writeBlob().
recvfromFunc()
SyscallReturn recvfromFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1393 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::sa.
recvmsgFunc()
SyscallReturn recvmsgFunc (SyscallDesc * desc, int num, ThreadContext * tc)
struct msghdr { void *msg_name; // optional address socklen_t msg_namelen; // size of address struct iovec *msg_iov; // iovec array size_t msg_iovlen; // number entries in msg_iov i // entries correspond to buffer void *msg_control; // ancillary data size_t msg_controllen; // ancillary data buffer len int msg_flags; // flags on received message };
struct iovec { void *iov_base; // starting address size_t iov_len; // number of bytes to transfer };
The plan with this system call is to replace all of the pointers in the structure and the substructure with BufferArg class pointers. We will copy every field from the structures into our BufferArg classes.
We will use these address place holders to retain the pointers which we are going to replace with our own buffers in our simulator address space.
Record msg_name pointer then replace with buffer pointer.
Record msg_iov pointer then replace with buffer pointer. Also, setup an array of buffer pointers for the iovec structs record and replace their pointers with buffer pointers.
Record msg_control pointer then replace with buffer pointer.
Definition at line 1495 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), ArmISA::i, MipsISA::index, and MipsISA::p.
renameatFunc()
template<class OS > SyscallReturn renameatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target renameat() handler.
Definition at line 975 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), MipsISA::index, PortProxy::tryReadString(), and warn.
renameFunc()
SyscallReturn renameFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target rename() handler.
Definition at line 568 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and PortProxy::tryReadString().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), unameFunc(), and unameFunc32().
rmdirFunc()
SyscallReturn rmdirFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1218 of file syscall_emul.cc.
References PowerISA::bo, BufferArg::bufferPtr(), BaseBufferArg::copyOut(), X86ISA::count, System::getGuestByteOrder(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, MipsISA::p, ArmISA::status, and PortProxy::tryReadString().
selectFunc()
template<class OS > SyscallReturn selectFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Host fields. Notice that these use the definitions from the system headers instead of the gem5 headers and libraries. If the host and target have different header file definitions, this will not work.
Copy in the fd_set from the target.
We need to translate the target file descriptor set into a host file descriptor set. This involves both our internal process fd array and the fd_set defined in Linux header files. The nfds field also needs to be updated as it will be only target specific after retrieving it from the target; the nfds value is expected to be the highest file descriptor that needs to be checked, so we need to extend it out for nfds_h when we do the update.
By this point, we know that we are looking at a valid file descriptor set on the target. We need to check if the target file descriptor value passed in as iter is part of the set.
We know that the target file descriptor belongs to the set, but we do not yet know if the file descriptor is valid or that we have a host mapping. Check that now.
Add the sim_fd to tgt_fd translation into trans_map for use later when we need to zero the target fd_set structures and then update them with hits returned from the host select call.
We know that the host file descriptor exists so now we check if we need to update the max count for nfds_h before passing the duplicated structure into the host.
Add the host file descriptor to the set that we are going to pass into the host.
It might be possible to decrement the timeval based on some derivation of wall clock determined from elapsed simulator ticks but that seems like overkill. Rather, we just set the timeval with zero timeout. (There is no reason to block during the simulation as it only decreases simulator performance.)
If the timeval pointer is null, setup a new timeval structure to pass into the host select call. Unfortunately, we will need to manually check the return value and throw a retry fault if the return value is zero. Allowing the system call to block will likely deadlock the event queue.
If blocking indefinitely, check the signal list to see if a signal would break the poll out of the retry cycle and try to return the signal interrupt instead.
We need to translate the host file descriptor set into a target file descriptor set. This involves both our internal process fd array and the fd_set defined in header files.
Definition at line 2417 of file syscall_emul.hh.
References BaseBufferArg::copyIn(), BaseBufferArg::copyOut(), ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), ArmISA::i, MipsISA::index, MipsISA::p, SyscallReturn::retry(), and System::signalList.
sendmsgFunc()
SyscallReturn sendmsgFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Reserve buffer space.
Assuming msgHdr.msg_iovlen >= 1, then there is no point calling recvmsg without a buffer.
Cannot instantiate buffers till inside the loop. Create array to hold buffer addresses, to be used during copyIn of send data.
Iterate through the iovec structures: Get the base buffer addreses, reserve iov_len amount of space for each. Put the buf address into the bufferArray for later retrieval.
Free dynamically allocated memory.
Malloced above.
Definition at line 1636 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
sendtoFunc()
SyscallReturn sendtoFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1458 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and ArmISA::sa.
setpgidFunc()
SyscallReturn setpgidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target setpgid() handler.
Definition at line 993 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getSystemPtr(), ThreadContext::Halted, ArmISA::i, MipsISA::index, System::numContexts(), Process::pgid(), Process::pid(), and System::threadContexts.
Referenced by unameFunc32().
setsockoptFunc()
SyscallReturn setsockoptFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 1819 of file syscall_emul.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, ArmISA::len, X86ISA::level, MipsISA::p, and ArmISA::status.
setTidAddressFunc()
SyscallReturn setTidAddressFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target set_tid_address() handler.
Definition at line 291 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), and MipsISA::index.
Referenced by unameFunc32().
setuidFunc()
SyscallReturn setuidFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target setuid() handler.
Definition at line 1065 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and warn.
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
shutdownFunc()
SyscallReturn shutdownFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target shutdown() handler.
Definition at line 1309 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), MipsISA::index, and MipsISA::p.
socketFunc()
template<class OS > SyscallReturn socketFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 2370 of file syscall_emul.hh.
References ArmISA::domain, ThreadContext::getProcessPtr(), MipsISA::index, MipsISA::p, X86ISA::prot, and type.
socketpairFunc()
template<class OS > SyscallReturn socketpairFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 2390 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ArmISA::domain, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, X86ISA::prot, ArmISA::status, and type.
stat64Func()
template<class OS > SyscallReturn stat64Func (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target stat64() handler.
Definition at line 1270 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and PortProxy::tryReadString().
statfsFunc()
template<class OS > SyscallReturn statfsFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target statfs() handler.
Definition at line 1464 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, PortProxy::tryReadString(), and warnUnsupportedOS().
statFunc()
template<class OS > SyscallReturn statFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target stat() handler.
Definition at line 1240 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and PortProxy::tryReadString().
symlinkFunc()
SyscallReturn symlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target symlink() handler.
Definition at line 531 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and MipsISA::p.
sysinfoFunc()
template<class OS > SyscallReturn sysinfoFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target sysinfo() handler.
Definition at line 1011 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, and seconds_since_epoch.
tgkillFunc()
template<class OS > SyscallReturn tgkillFunc (SyscallDesc * desc, int num, ThreadContext * tc)
This system call is intended to allow killing a specific thread within an arbitrary thread group if sanctioned with permission checks. It's usually true that threads share the termination signal as pointed out by the pthread_kill man page and this seems to be the intended usage. Due to this being an emulated environment, assume the following: Threads are allowed to call tgkill because the EUID for all threads should be the same. There is no signal handling mechanism for kernel registration of signal handlers since signals are poorly supported in emulation mode. Since signal handlers cannot be registered, all threads within in a thread group must share the termination signal. We never exhaust PIDs so there's no chance of finding the wrong one due to PID rollover.
Definition at line 2320 of file syscall_emul.hh.
References exitGroupFunc(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getSystemPtr(), ArmISA::i, MipsISA::index, System::numContexts(), Process::pid(), Process::tgid(), and System::threadContexts.
timeFunc()
template<class OS > SyscallReturn timeFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target time() function.
Definition at line 2300 of file syscall_emul.hh.
References ArmISA::byteOrder(), getElapsedTimeMicro(), ThreadContext::getProcessPtr(), Process::getSyscallArg(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, MipsISA::p, seconds_since_epoch, ArmISA::t, and PortProxy::writeBlob().
timesFunc()
template<class OS > SyscallReturn timesFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target times() function.
Definition at line 2274 of file syscall_emul.hh.
References ArmISA::byteOrder(), curTick(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), htog(), MipsISA::index, and SimClock::Int::s.
truncate64Func()
SyscallReturn truncate64Func (SyscallDesc * desc, int num, ThreadContext * tc)
Target truncate64() handler.
Definition at line 631 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, length, and PortProxy::tryReadString().
Referenced by unameFunc32().
truncateFunc()
SyscallReturn truncateFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target truncate() handler.
Definition at line 595 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, length, MipsISA::p, and PortProxy::tryReadString().
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
umaskFunc()
SyscallReturn umaskFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Target umask() handler.
Definition at line 677 of file syscall_emul.cc.
Referenced by osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
unimplementedFunc()
SyscallReturn unimplementedFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Handler for unimplemented syscalls that we haven't thought about.
Definition at line 67 of file syscall_emul.cc.
References fatal, and SyscallDesc::name().
unlinkatFunc()
template<class OS > SyscallReturn unlinkatFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target unlinkat() handler.
Definition at line 935 of file syscall_emul.hh.
References ThreadContext::getProcessPtr(), Process::getSyscallArg(), MipsISA::index, unlinkHelper(), and warn.
unlinkFunc()
SyscallReturn unlinkFunc (SyscallDesc * desc, int num, ThreadContext * tc)
Definition at line 489 of file syscall_emul.cc.
References unlinkHelper().
Referenced by SparcISA::getresuidFunc(), osf_setsysinfoFunc(), setThreadAreaFunc(), unameFunc(), and unameFunc32().
unlinkHelper()
SyscallReturn unlinkHelper (SyscallDesc * desc, int num, ThreadContext * tc, int index)
Target unlink() handler.
Definition at line 495 of file syscall_emul.cc.
References ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::p, and PortProxy::tryReadString().
Referenced by unlinkatFunc(), and unlinkFunc().
utimesFunc()
template<class OS > SyscallReturn utimesFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target utimes() handler.
Definition at line 2095 of file syscall_emul.hh.
References ArmISA::byteOrder(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), gtoh(), ArmISA::i, MipsISA::index, and PortProxy::tryReadString().
wait4Func()
template<class OS > SyscallReturn wait4Func (SyscallDesc * desc, int num, ThreadContext * tc)
Currently, wait4 is only implemented so that it will wait for children exit conditions which are denoted by a SIGCHLD signals posted into the system signal list. We return no additional information via any of the parameters supplied to wait4. If nothing is found in the system signal list, we will wait indefinitely for SIGCHLD to post by retrying the call.
Definition at line 2686 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), DPRINTF_SYSCALL, ThreadContext::getProcessPtr(), ThreadContext::getSystemPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, SyscallReturn::retry(), and System::signalList.
warnUnsupportedOS()
void warnUnsupportedOS (std::string syscall_name)
Definition at line 61 of file syscall_emul.cc.
References warn.
Referenced by eventfdFunc(), fallocateFunc(), and statfsFunc().
writeFunc()
template<class OS > SyscallReturn writeFunc (SyscallDesc * desc, int num, ThreadContext * tc)
We don't want to poll on /dev/random. The kernel will not enable the file descriptor for writing unless the entropy in the system falls below write_wakeup_threshold. This is not guaranteed to happen depending on host settings.
Definition at line 2644 of file syscall_emul.hh.
References BufferArg::bufferPtr(), BaseBufferArg::copyIn(), ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), MipsISA::index, MipsISA::p, and SyscallReturn::retry().
writevFunc()
template<class OS > SyscallReturn writevFunc (SyscallDesc * desc, int callnum, ThreadContext * tc)
Target writev() handler.
Definition at line 1704 of file syscall_emul.hh.
References ArmISA::byteOrder(), X86ISA::count, ThreadContext::getProcessPtr(), ThreadContext::getVirtProxy(), gtoh(), ArmISA::i, MipsISA::index, MipsISA::p, and PortProxy::readBlob().
Variable Documentation
one_billion
const int one_billion = 1000000000
A readable name for 1,000,000,000, for converting nanoseconds to seconds.
Definition at line 490 of file syscall_emul.hh.
Referenced by getElapsedTimeNano().
one_million
const int one_million = 1000000
A readable name for 1,000,000, for converting microseconds to seconds.
Definition at line 488 of file syscall_emul.hh.
Referenced by getElapsedTimeMicro().
seconds_since_epoch
const unsigned seconds_since_epoch = 1000000000
Approximate seconds since the epoch (1/1/1970).
About a billion, by my reckoning. We want to keep this a constant (not use the real-world time) to keep simulations repeatable.
Definition at line 495 of file syscall_emul.hh.
Referenced by clock_gettimeFunc(), gettimeofdayFunc(), sysinfoFunc(), and timeFunc().