gem5: mem/cache/replacement_policies/tree_plru_rp.cc File Reference
tree_plru_rp.cc File Reference
Copyright (c) 2018 Inria All rights reserved.
#include "mem/cache/replacement_policies/tree_plru_rp.hh"
#include <cmath>
#include "base/intmath.hh"
#include "base/logging.hh"
#include "params/TreePLRURP.hh"
Functions
static uint64_t parentIndex (const uint64_t index)
Get the index of the parent of the given indexed subtree.
static uint64_t leftSubtreeIndex (const uint64_t index)
Get index of the subtree on the left of the given indexed tree.
static uint64_t rightSubtreeIndex (const uint64_t index)
Get index of the subtree on the right of the given indexed tree.
static bool isRightSubtree (const uint64_t index)
Find out if the subtree at index corresponds to the right or left subtree of its parent tree.
Detailed Description
Copyright (c) 2018 Inria All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer; redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution; neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Authors: Daniel Carvalho
Definitions of a Tree-PLRU replacement policy, along with some helper tree indexing functions, which map an index to the tree 2D-array.
Definition in file tree_plru_rp.cc.
Function Documentation
isRightSubtree()
static bool isRightSubtree (const uint64_t index) static
Find out if the subtree at index corresponds to the right or left subtree of its parent tree.
Parameters
index The index of the subtree.
Returns
True if it is a right subtree, false otherwise.
Definition at line 89 of file tree_plru_rp.cc.
Referenced by TreePLRURP::invalidate(), and TreePLRURP::touch().
leftSubtreeIndex()
static uint64_t leftSubtreeIndex (const uint64_t index) static
Get index of the subtree on the left of the given indexed tree.
Parameters
index The index of the queried tree.
Returns
The index of the subtree to the left of the queried tree.
Definition at line 64 of file tree_plru_rp.cc.
Referenced by TreePLRURP::getVictim().
parentIndex()
static uint64_t parentIndex (const uint64_t index) static
Get the index of the parent of the given indexed subtree.
Parameters
Index of the queried tree.
Returns
The index of the parent tree.
Definition at line 52 of file tree_plru_rp.cc.
Referenced by TreePLRURP::invalidate(), and TreePLRURP::touch().
rightSubtreeIndex()
static uint64_t rightSubtreeIndex (const uint64_t index) static
Get index of the subtree on the right of the given indexed tree.
Parameters
index The index of the queried tree.
Returns
The index of the subtree to the right of the queried tree.
Definition at line 76 of file tree_plru_rp.cc.
Referenced by TreePLRURP::getVictim().