gem5: base/types.test.cc File Reference
types.test.cc File Reference
#include <gtest/gtest.h>
#include <sstream>
#include "base/types.hh"
Functions
TEST (CyclesTest, NoCycles)
TEST (CyclesTest, PrefixIncrement)
TEST (CyclesTest, PrefixDecrement)
TEST (CyclesTest, InPlaceAddition)
TEST (CyclesTest, GreaterThanLessThan)
TEST (CyclesTest, AddCycles)
TEST (CyclesTest, SubtractCycles)
TEST (CyclesTest, ShiftRight)
TEST (CyclesTest, ShiftLeft)
TEST (CyclesTest, OutStream)
TEST (MicroPCTest, CheckMicroPCRomBit)
TEST (MicroPCTest, RomMicroPCTest)
TEST (MicroPCTest, NormalMicroPCTest)
TEST (MicroPCTest, IsRomMicroPCTest)
TEST (MicroPCTest, IsNotRomMicroPCTest)
TEST (TypesTest, FloatToBits32)
TEST (TypesTest, floatToBits64)
TEST (TypesTest, floatsToBitsDoubleInput)
TEST (TypesTest, floatsToBitsFloatInput)
Function Documentation
TEST() [1/19]
TEST (CyclesTest , NoCycles)
Definition at line 50 of file types.test.cc.
References EXPECT_EQ.
TEST() [2/19]
TEST (CyclesTest , PrefixIncrement)
Definition at line 56 of file types.test.cc.
References EXPECT_EQ.
TEST() [3/19]
TEST (CyclesTest , PrefixDecrement)
Definition at line 65 of file types.test.cc.
References EXPECT_EQ.
TEST() [4/19]
TEST (CyclesTest , InPlaceAddition)
Definition at line 73 of file types.test.cc.
References EXPECT_EQ.
TEST() [5/19]
TEST (CyclesTest , GreaterThanLessThan)
Definition at line 81 of file types.test.cc.
References EXPECT_TRUE.
TEST() [6/19]
TEST (CyclesTest , AddCycles)
Definition at line 89 of file types.test.cc.
References EXPECT_EQ.
TEST() [7/19]
TEST (CyclesTest , SubtractCycles)
Definition at line 97 of file types.test.cc.
References EXPECT_EQ.
TEST() [8/19]
TEST (CyclesTest , ShiftRight)
Definition at line 105 of file types.test.cc.
References EXPECT_EQ, and ULL.
TEST() [9/19]
TEST (CyclesTest , ShiftLeft)
Definition at line 112 of file types.test.cc.
References EXPECT_EQ, and ULL.
TEST() [10/19]
TEST (CyclesTest , OutStream)
Definition at line 119 of file types.test.cc.
References EXPECT_EQ, and ArmISA::ss.
TEST() [11/19]
TEST (MicroPCTest , CheckMicroPCRomBit)
Definition at line 131 of file types.test.cc.
References EXPECT_EQ, and MicroPCRomBit.
TEST() [12/19]
TEST (MicroPCTest , RomMicroPCTest)
Definition at line 136 of file types.test.cc.
References EXPECT_EQ, MicroPCRomBit, and romMicroPC().
TEST() [13/19]
TEST (MicroPCTest , NormalMicroPCTest)
Definition at line 141 of file types.test.cc.
References EXPECT_EQ, MicroPCRomBit, and normalMicroPC().
TEST() [14/19]
TEST (MicroPCTest , IsRomMicroPCTest)
Definition at line 146 of file types.test.cc.
References EXPECT_TRUE, isRomMicroPC(), and MicroPCRomBit.
TEST() [15/19]
TEST (MicroPCTest , IsNotRomMicroPCTest)
Definition at line 151 of file types.test.cc.
References EXPECT_FALSE, and isRomMicroPC().
TEST() [16/19]
TEST (TypesTest , FloatToBits32)
Definition at line 161 of file types.test.cc.
References EXPECT_EQ, and floatToBits32().
TEST() [17/19]
TEST (TypesTest , floatToBits64)
Definition at line 166 of file types.test.cc.
References EXPECT_EQ, and floatToBits64().
TEST() [18/19]
TEST (TypesTest , floatsToBitsDoubleInput)
Definition at line 176 of file types.test.cc.
References EXPECT_EQ, floatToBits(), floatToBits64(), and X86ISA::val.
TEST() [19/19]
TEST (TypesTest , floatsToBitsFloatInput)
Definition at line 182 of file types.test.cc.
References EXPECT_EQ, floatToBits(), floatToBits32(), and X86ISA::val.