gem5: arch/generic/vec_pred_reg.hh File Reference
vec_pred_reg.hh File Reference
#include <array>
#include <cassert>
#include <vector>
#include "arch/generic/vec_reg.hh"
#include "base/cprintf.hh"
Classes
class VecPredRegContainer< NumBits, Packed >
Generic predicate register container.
class VecPredRegT< VecElem, NumElems, Packed, Const >
Predicate register view.
class VecPredRegContainer< NumBits, Packed >
Generic predicate register container.
Functions
template<size_t NumBits, bool Packed>
bool to_number (const std::string &value, VecPredRegContainer< NumBits, Packed > &p)
Helper functions used for serialization/de-serialization.
using DummyVecPredReg = VecPredRegT< DummyVecElem, DummyNumVecElemPerVecReg, DummyVecPredRegHasPackedRepr, false >
using DummyConstVecPredReg = VecPredRegT< DummyVecElem, DummyNumVecElemPerVecReg, DummyVecPredRegHasPackedRepr, true >
using DummyVecPredRegContainer = DummyVecPredReg::Container
constexpr bool DummyVecPredRegHasPackedRepr = false
Dummy type aliases and constants for architectures that do not implement vector predicate registers.
constexpr size_t DummyVecPredRegSizeBits = 8
Typedef Documentation
DummyConstVecPredReg
using DummyConstVecPredReg = VecPredRegT<DummyVecElem, DummyNumVecElemPerVecReg, DummyVecPredRegHasPackedRepr, true>
Definition at line 399 of file vec_pred_reg.hh.
DummyVecPredReg
using DummyVecPredReg = VecPredRegT<DummyVecElem, DummyNumVecElemPerVecReg, DummyVecPredRegHasPackedRepr, false>
Definition at line 396 of file vec_pred_reg.hh.
DummyVecPredRegContainer
using DummyVecPredRegContainer = DummyVecPredReg::Container
Definition at line 400 of file vec_pred_reg.hh.
Function Documentation
to_number()
template<size_t NumBits, bool Packed> bool to_number (const std::string & value, VecPredRegContainer< NumBits, Packed > & p) inline
Helper functions used for serialization/de-serialization.
Definition at line 382 of file vec_pred_reg.hh.
References ArmISA::c, and ArmISA::i.
Referenced by SymbolTable::load(), PseudoInst::loadsymbol(), main(), parseParam(), and TEST().
Variable Documentation
DummyVecPredRegHasPackedRepr
constexpr bool DummyVecPredRegHasPackedRepr = false
Dummy type aliases and constants for architectures that do not implement vector predicate registers.
Definition at line 394 of file vec_pred_reg.hh.
DummyVecPredRegSizeBits
constexpr size_t DummyVecPredRegSizeBits = 8
Definition at line 401 of file vec_pred_reg.hh.