gem5: cpu/kvm/x86_cpu.cc File Reference
x86_cpu.cc File Reference
#include "cpu/kvm/x86_cpu.hh"
#include <linux/kvm.h>
#include <algorithm>
#include <cerrno>
#include <memory>
#include "arch/registers.hh"
#include "arch/x86/cpuid.hh"
#include "arch/x86/faults.hh"
#include "arch/x86/interrupts.hh"
#include "arch/x86/regs/msr.hh"
#include "arch/x86/utility.hh"
#include "cpu/kvm/base.hh"
#include "debug/Drain.hh"
#include "debug/Kvm.hh"
#include "debug/KvmContext.hh"
#include "debug/KvmIO.hh"
#include "debug/KvmInt.hh"
Classes
struct FXSave
Macros
#define MSR_TSC 0x10
#define IO_PCI_CONF_ADDR 0xCF8
#define IO_PCI_CONF_DATA_BASE 0xCFC
#define SEG_SYS_TYPE_TSS_AVAILABLE 9
#define SEG_SYS_TYPE_TSS_BUSY 11
#define SEG_CS_TYPE_ACCESSED 9
#define SEG_CS_TYPE_READ_ACCESSED 11
#define SEG_TYPE_BIT_ACCESSED 1
#define FOREACH_IREG()
#define FOREACH_SREG()
#define FOREACH_DREG()
#define FOREACH_SEGMENT()
#define FOREACH_DTABLE()
#define APPLY_IREG(kreg, mreg) inform("\t" # kreg ": 0x%llx\n", regs.kreg)
#define APPLY_SREG(kreg, mreg) inform("\t" # kreg ": 0x%llx\n", sregs.kreg);
#define APPLY_SEGMENT(kreg, idx) dumpKvm(# kreg, sregs.kreg);
#define APPLY_DTABLE(kreg, idx) dumpKvm(# kreg, sregs.kreg);
#define APPLY_IREG(kreg, mreg) regs.kreg = tc->readIntReg(mreg)
#define APPLY_SREG(kreg, mreg) sregs.kreg = tc->readMiscRegNoEffect(mreg)
#define APPLY_SEGMENT(kreg, idx) setKvmSegmentReg(tc, sregs.kreg, idx)
#define APPLY_DTABLE(kreg, idx) setKvmDTableReg(tc, sregs.kreg, idx)
#define APPLY_SEGMENT(kreg, idx) checkSeg(# kreg, idx + MISCREG_SEG_SEL_BASE, sregs.kreg, sregs)
#define APPLY_IREG(kreg, mreg) tc->setIntReg(mreg, regs.kreg)
#define APPLY_SREG(kreg, mreg) tc->setMiscRegNoEffect(mreg, sregs.kreg)
#define APPLY_SEGMENT(kreg, idx) setContextSegment(tc, sregs.kreg, idx)
#define APPLY_DTABLE(kreg, idx) setContextSegment(tc, sregs.kreg, idx)
Functions
template<typename STRUCT , typename ENTRY >
static STRUCT * newVarStruct (size_t entries)
static void dumpKvm (const struct kvm_regs &regs)
static void dumpKvm (const char *reg_name, const struct kvm_segment &seg)
static void dumpKvm (const char *reg_name, const struct kvm_dtable &dtable)
static void dumpKvm (const struct kvm_sregs &sregs)
static void dumpFpuSpec (const struct FXSave &xs)
static void dumpFpuSpec (const struct kvm_fpu &fpu)
template<typename T >
static void dumpFpuCommon (const T &fpu)
static void dumpKvm (const struct kvm_fpu &fpu)
static void dumpKvm (const struct kvm_xsave &xsave)
static void dumpKvm (const struct kvm_msrs &msrs)
static void dumpKvm (const struct kvm_xcrs &regs)
static void dumpKvm (const struct kvm_vcpu_events &events)
static bool isCanonicalAddress (uint64_t addr)
static void checkSeg (const char *name, const int idx, const struct kvm_segment &seg, struct kvm_sregs sregs)
static void setKvmSegmentReg (ThreadContext *tc, struct kvm_segment &kvm_seg, const int index)
static void setKvmDTableReg (ThreadContext *tc, struct kvm_dtable &kvm_dtable, const int index)
static void forceSegAccessed (struct kvm_segment &seg)
template<typename T >
static void updateKvmStateFPUCommon (ThreadContext *tc, T &fpu)
void setContextSegment (ThreadContext *tc, const struct kvm_segment &kvm_seg, const int index)
void setContextSegment (ThreadContext *tc, const struct kvm_dtable &kvm_dtable, const int index)
template<typename T >
static void updateThreadContextFPUCommon (ThreadContext *tc, const T &fpu)
static struct kvm_cpuid_entry2 makeKvmCpuid (uint32_t function, uint32_t index, CpuidResult &result)
Variables
struct FXSave M5_ATTR_PACKED
Macro Definition Documentation
APPLY_DTABLE [1/3]
#define APPLY_DTABLE (kreg, idx) dumpKvm(# kreg, sregs.kreg);
APPLY_DTABLE [2/3]
#define APPLY_DTABLE (kreg, idx) setKvmDTableReg(tc, sregs.kreg, idx)
APPLY_DTABLE [3/3]
#define APPLY_DTABLE (kreg, idx) setContextSegment(tc, sregs.kreg, idx)
APPLY_IREG [1/3]
#define APPLY_IREG (kreg, mreg) inform("\t" # kreg ": 0x%llx\n", regs.kreg)
APPLY_IREG [2/3]
#define APPLY_IREG (kreg, mreg) regs.kreg = tc->readIntReg(mreg)
APPLY_IREG [3/3]
#define APPLY_IREG (kreg, mreg) tc->setIntReg(mreg, regs.kreg)
APPLY_SEGMENT [1/4]
#define APPLY_SEGMENT (kreg, idx) dumpKvm(# kreg, sregs.kreg);
APPLY_SEGMENT [2/4]
#define APPLY_SEGMENT (kreg, idx) setKvmSegmentReg(tc, sregs.kreg, idx)
APPLY_SEGMENT [3/4]
#define APPLY_SEGMENT (kreg, idx) checkSeg(# kreg, idx + MISCREG_SEG_SEL_BASE, sregs.kreg, sregs)
APPLY_SEGMENT [4/4]
#define APPLY_SEGMENT (kreg, idx) setContextSegment(tc, sregs.kreg, idx)
APPLY_SREG [1/3]
#define APPLY_SREG (kreg, mreg) inform("\t" # kreg ": 0x%llx\n", sregs.kreg);
APPLY_SREG [2/3]
#define APPLY_SREG (kreg, mreg) sregs.kreg = tc->readMiscRegNoEffect(mreg)
APPLY_SREG [3/3]
#define APPLY_SREG (kreg, mreg) tc->setMiscRegNoEffect(mreg, sregs.kreg)
FOREACH_DREG
#define FOREACH_DREG ()
Value:
do {                                        \
        APPLY_DREG(db[0], MISCREG_DR0);         \
        APPLY_DREG(db[1], MISCREG_DR1);         \
        APPLY_DREG(db[2], MISCREG_DR2);         \
        APPLY_DREG(db[3], MISCREG_DR3);         \
        APPLY_DREG(dr6, MISCREG_DR6);           \
        APPLY_DREG(dr7, MISCREG_DR7);           \
    } while (0)
Definition at line 137 of file x86_cpu.cc.
Referenced by dumpKvm().
FOREACH_DTABLE
#define FOREACH_DTABLE ()
Value:
do {                                                        \
        APPLY_DTABLE(gdt, MISCREG_TSG - MISCREG_SEG_SEL_BASE);  \
        APPLY_DTABLE(idt, MISCREG_IDTR - MISCREG_SEG_SEL_BASE); \
    } while (0)
Definition at line 159 of file x86_cpu.cc.
Referenced by dumpKvm(), X86KvmCPU::updateKvmStateSRegs(), and X86KvmCPU::updateThreadContextSRegs().
FOREACH_IREG
#define FOREACH_IREG ()
Value:
do {                                        \
        APPLY_IREG(rax, INTREG_RAX);            \
        APPLY_IREG(rbx, INTREG_RBX);            \
        APPLY_IREG(rcx, INTREG_RCX);            \
        APPLY_IREG(rdx, INTREG_RDX);            \
        APPLY_IREG(rsi, INTREG_RSI);            \
        APPLY_IREG(rdi, INTREG_RDI);            \
        APPLY_IREG(rsp, INTREG_RSP);            \
        APPLY_IREG(rbp, INTREG_RBP);            \
        APPLY_IREG(r8, INTREG_R8);              \
        APPLY_IREG(r9, INTREG_R9);              \
        APPLY_IREG(r10, INTREG_R10);            \
        APPLY_IREG(r11, INTREG_R11);            \
        APPLY_IREG(r12, INTREG_R12);            \
        APPLY_IREG(r13, INTREG_R13);            \
        APPLY_IREG(r14, INTREG_R14);            \
        APPLY_IREG(r15, INTREG_R15);            \
    } while (0)
Definition at line 106 of file x86_cpu.cc.
Referenced by dumpKvm(), X86KvmCPU::updateKvmStateRegs(), and X86KvmCPU::updateThreadContextRegs().
FOREACH_SEGMENT
#define FOREACH_SEGMENT ()
Value:
do {                                                        \
        APPLY_SEGMENT(cs, MISCREG_CS - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(ds, MISCREG_DS - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(es, MISCREG_ES - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(fs, MISCREG_FS - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(gs, MISCREG_GS - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(ss, MISCREG_SS - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(tr, MISCREG_TR - MISCREG_SEG_SEL_BASE);   \
        APPLY_SEGMENT(ldt, MISCREG_TSL - MISCREG_SEG_SEL_BASE); \
    } while (0)
Definition at line 147 of file x86_cpu.cc.
Referenced by dumpKvm(), X86KvmCPU::updateKvmStateSRegs(), and X86KvmCPU::updateThreadContextSRegs().
FOREACH_SREG
#define FOREACH_SREG ()
Value:
do {                                                \
        APPLY_SREG(cr0, MISCREG_CR0);                   \
        APPLY_SREG(cr2, MISCREG_CR2);                   \
        APPLY_SREG(cr3, MISCREG_CR3);                   \
        APPLY_SREG(cr4, MISCREG_CR4);                   \
        APPLY_SREG(cr8, MISCREG_CR8);                   \
        APPLY_SREG(efer, MISCREG_EFER);                 \
        APPLY_SREG(apic_base, MISCREG_APIC_BASE);       \
    } while (0)
Definition at line 126 of file x86_cpu.cc.
Referenced by dumpKvm(), X86KvmCPU::updateKvmStateSRegs(), and X86KvmCPU::updateThreadContextSRegs().
IO_PCI_CONF_ADDR
#define IO_PCI_CONF_ADDR 0xCF8
Definition at line 56 of file x86_cpu.cc.
Referenced by X86KvmCPU::handleKvmExitIO().
IO_PCI_CONF_DATA_BASE
#define IO_PCI_CONF_DATA_BASE 0xCFC
Definition at line 57 of file x86_cpu.cc.
Referenced by X86KvmCPU::handleKvmExitIO().
MSR_TSC
#define MSR_TSC 0x10
Definition at line 54 of file x86_cpu.cc.
Referenced by X86KvmCPU::getHostCycles().
SEG_CS_TYPE_ACCESSED
#define SEG_CS_TYPE_ACCESSED 9
Definition at line 65 of file x86_cpu.cc.
Referenced by X86KvmCPU::updateKvmStateSRegs().
SEG_CS_TYPE_READ_ACCESSED
#define SEG_CS_TYPE_READ_ACCESSED 11
Definition at line 67 of file x86_cpu.cc.
Referenced by X86KvmCPU::updateKvmStateSRegs().
SEG_SYS_TYPE_TSS_AVAILABLE
#define SEG_SYS_TYPE_TSS_AVAILABLE 9
Definition at line 60 of file x86_cpu.cc.
Referenced by X86KvmCPU::updateKvmStateSRegs().
SEG_SYS_TYPE_TSS_BUSY
#define SEG_SYS_TYPE_TSS_BUSY 11
Definition at line 62 of file x86_cpu.cc.
Referenced by X86KvmCPU::updateKvmStateSRegs().
SEG_TYPE_BIT_ACCESSED
#define SEG_TYPE_BIT_ACCESSED 1
Definition at line 71 of file x86_cpu.cc.
Referenced by forceSegAccessed().
Function Documentation
checkSeg()
static void checkSeg (const char * name, const int idx, const struct kvm_segment & seg, struct kvm_sregs sregs) static
Definition at line 383 of file x86_cpu.cc.
References isCanonicalAddress(), M5_FALLTHROUGH, X86ISA::MISCREG_CS, X86ISA::MISCREG_DS, X86ISA::MISCREG_ES, X86ISA::MISCREG_FS, X86ISA::MISCREG_GS, X86ISA::MISCREG_SS, X86ISA::MISCREG_TR, X86ISA::MISCREG_TSL, and warn.
dumpFpuCommon()
template<typename T > static void dumpFpuCommon (const T & fpu) static
Definition at line 262 of file x86_cpu.cc.
References X86ISA::BusyBit, X86ISA::CC0Bit, X86ISA::CC1Bit, X86ISA::CC2Bit, X86ISA::CC3Bit, X86ISA::DEBit, dumpFpuSpec(), X86ISA::ErrSummaryBit, ArmISA::i, X86ISA::IEBit, inform, ArmISA::j, X86ISA::loadFloat80(), X86ISA::OEBit, X86ISA::PEBit, X86ISA::StackFaultBit, X86ISA::UEBit, and X86ISA::ZEBit.
Referenced by dumpKvm().
dumpFpuSpec() [1/2]
static void dumpFpuSpec (const struct FXSave & xs) static
Definition at line 246 of file x86_cpu.cc.
References FXSave::ctrl64, inform, and FXSave::mxcsr_mask.
Referenced by dumpFpuCommon().
dumpFpuSpec() [2/2]
static void dumpFpuSpec (const struct kvm_fpu & fpu) static
Definition at line 254 of file x86_cpu.cc.
References inform.
dumpKvm() [1/9]
static void dumpKvm (const struct kvm_regs & regs) static
Definition at line 172 of file x86_cpu.cc.
References FOREACH_IREG, and inform.
Referenced by X86KvmCPU::dumpDebugRegs(), X86KvmCPU::dumpFpuRegs(), X86KvmCPU::dumpIntRegs(), dumpKvm(), X86KvmCPU::dumpMSRs(), X86KvmCPU::dumpSpecRegs(), X86KvmCPU::dumpVCpuEvents(), X86KvmCPU::dumpXCRs(), and X86KvmCPU::dumpXSave().
dumpKvm() [2/9]
static void dumpKvm (const char * reg_name, const struct kvm_segment & seg) static
Definition at line 188 of file x86_cpu.cc.
References inform.
dumpKvm() [3/9]
static void dumpKvm (const char * reg_name, const struct kvm_dtable & dtable) static
Definition at line 198 of file x86_cpu.cc.
References inform.
dumpKvm() [4/9]
static void dumpKvm (const struct kvm_sregs & sregs) static
Definition at line 205 of file x86_cpu.cc.
References dumpKvm(), FOREACH_DREG, FOREACH_DTABLE, FOREACH_SEGMENT, FOREACH_SREG, ArmISA::i, and inform.
dumpKvm() [5/9]
static void dumpKvm (const struct kvm_fpu & fpu) static
Definition at line 312 of file x86_cpu.cc.
References dumpFpuCommon(), and inform.
dumpKvm() [6/9]
static void dumpKvm (const struct kvm_xsave & xsave) static
Definition at line 319 of file x86_cpu.cc.
References dumpFpuCommon(), and inform.
dumpKvm() [7/9]
static void dumpKvm (const struct kvm_msrs & msrs) static
Definition at line 326 of file x86_cpu.cc.
References X86ISA::e, ArmISA::i, and inform.
dumpKvm() [8/9]
static void dumpKvm (const struct kvm_xcrs & regs) static
Definition at line 338 of file x86_cpu.cc.
References ArmISA::i, and inform.
dumpKvm() [9/9]
static void dumpKvm (const struct kvm_vcpu_events & events) static
Definition at line 351 of file x86_cpu.cc.
References inform.
forceSegAccessed()
static void forceSegAccessed (struct kvm_segment & seg) static
Definition at line 745 of file x86_cpu.cc.
References SEG_TYPE_BIT_ACCESSED.
Referenced by X86KvmCPU::updateKvmStateSRegs().
isCanonicalAddress()
static bool isCanonicalAddress (uint64_t addr) static
Definition at line 372 of file x86_cpu.cc.
Referenced by checkSeg().
makeKvmCpuid()
static struct kvm_cpuid_entry2 makeKvmCpuid (uint32_t function, uint32_t index, CpuidResult & result) static
Definition at line 1410 of file x86_cpu.cc.
References ArmISA::e, and MipsISA::index.
Referenced by X86KvmCPU::updateCPUID().
newVarStruct()
template<typename STRUCT , typename ENTRY > static STRUCT* newVarStruct (size_t entries) static
Definition at line 166 of file x86_cpu.cc.
setContextSegment() [1/2]
void setContextSegment (ThreadContext * tc, const struct kvm_segment & kvm_seg, const int index) inline
Definition at line 992 of file x86_cpu.cc.
References ArmISA::attr, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::MISCREG_SEG_SEL(), and ThreadContext::setMiscReg().
setContextSegment() [2/2]
void setContextSegment (ThreadContext * tc, const struct kvm_dtable & kvm_dtable, const int index) inline
Definition at line 1017 of file x86_cpu.cc.
References X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_LIMIT(), and ThreadContext::setMiscReg().
setKvmDTableReg()
static void setKvmDTableReg (ThreadContext * tc, struct kvm_dtable & kvm_dtable, const int index) inline static
Definition at line 737 of file x86_cpu.cc.
References X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_LIMIT(), and ThreadContext::readMiscRegNoEffect().
setKvmSegmentReg()
static void setKvmSegmentReg (ThreadContext * tc, struct kvm_segment & kvm_seg, const int index) inline static
Definition at line 712 of file x86_cpu.cc.
References ArmISA::attr, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::MISCREG_SEG_SEL(), and ThreadContext::readMiscRegNoEffect().
updateKvmStateFPUCommon()
template<typename T > static void updateKvmStateFPUCommon (ThreadContext * tc, T & fpu) static
Definition at line 826 of file x86_cpu.cc.
References bitsToFloat64(), X86ISA::convX87TagsToXTags(), DPRINTF, X86ISA::FLOATREG_FPR(), X86ISA::FLOATREG_XMM_HIGH(), X86ISA::FLOATREG_XMM_LOW(), ArmISA::i, X86ISA::MISCREG_FCW, X86ISA::MISCREG_FOP, X86ISA::MISCREG_FSW, X86ISA::MISCREG_FTW, X86ISA::MISCREG_MXCSR, ThreadContext::readFloatReg(), ThreadContext::readMiscReg(), ThreadContext::readMiscRegNoEffect(), and X86ISA::storeFloat80().
Referenced by X86KvmCPU::updateKvmStateFPULegacy(), and X86KvmCPU::updateKvmStateFPUXSave().
updateThreadContextFPUCommon()
template<typename T > static void updateThreadContextFPUCommon (ThreadContext * tc, const T & fpu) static
Definition at line 1046 of file x86_cpu.cc.
References X86ISA::convX87XTagsToTags(), DPRINTF, X86ISA::FLOATREG_FPR(), X86ISA::FLOATREG_XMM_HIGH(), X86ISA::FLOATREG_XMM_LOW(), floatToBits64(), ArmISA::i, X86ISA::loadFloat80(), X86ISA::MISCREG_FCW, X86ISA::MISCREG_FOP, X86ISA::MISCREG_FSW, X86ISA::MISCREG_FTAG, X86ISA::MISCREG_FTW, X86ISA::MISCREG_MXCSR, X86ISA::MISCREG_X87_TOP, ThreadContext::setFloatReg(), and ThreadContext::setMiscRegNoEffect().
Referenced by X86KvmCPU::updateThreadContextFPU(), and X86KvmCPU::updateThreadContextXSave().
Variable Documentation
M5_ATTR_PACKED
struct FXSave M5_ATTR_PACKED